### ISSUE TITLE
 Input/output error - &lt;STDERR&gt;

### ISSUE THREAD

**Issue by rubyonrailsworks** [mperham/sidekiq#1039]
Hi all,

 when sending request via xml format using sidekiq as background job. we come across  Input/output error.

 Input/output error - &lt;STDERR&gt;
 /home/rails/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/logger.rb:574:in `write&#x27;

is it a sidekiq problem or a logger problem?

related sidekiq worker code sample like this.

``` ruby

 client = Savon.client(wsdl: wsdl_client)

 # this line fires.
 response = client.call(:so_to_wms, message:{xml: xml})

 result_xml = response.body[:so_to_wms_response][:out]
 result = Hash.from_xml(result_xml).as_json

```

**Comment by nocivus** [comment]
Hi @mperham  did you end solving this problem?

My sidekiq is randomly doing this. Sometimes it goes days without incidents, but now and again it starts throwing these errors and stops processing.

Any ideas?

**Comment by mperham** [comment]
@nocivus This isn't a problem in Sidekiq - it's due to starting Sidekiq incorrectly.  Use upstart/systemd.

**Comment by phensalves** [comment]
Hi @mperham could you please show how can I start properly sidekiq in production to fix this error message? You said that we have to user "upstart/systemd". How would be?

**Comment by mperham** [comment]
Show me how you are starting Sidekiq and I will point out what's wrong.

**Comment by phensalves** [comment]
I am trying this way: 'RAILS_ENV=production bundle exec sidekiq -q default -C config/sidekiq.yml' or 'bundle exec sidekiq -d -L log/sidekiq.log -q default -C config/sidekiq.yml -e production'. What is wrong?


Pedro Alves
pedro_alves@me.com

**Comment by phensalves** [comment]
@mperham I am trying this way: 'RAILS_ENV=production bundle exec sidekiq -q default -C config/sidekiq.yml' or 'bundle exec sidekiq -d -L log/sidekiq.log -q default -C config/sidekiq.yml -e production'. What is wrong?

**Comment by phensalves** [comment]
@mperham Sorry, I tried right now and this approach works for me:

bundle exec sidekiq -d -L log/sidekiq.log -q default -C config/sidekiq.yml -e production

Thank you for your response

**Comment by mperham** [comment]
That command should work on its own. You'll see that error if your Ruby code closes STDERR.  Please also see my blog post entitled "don't daemonize your daemons".

**Comment by phensalves** [comment]
@mperham thank you so much!
