### ISSUE TITLE
Jobs getting stuck

### ISSUE THREAD

**Issue by kavitakanojiya** [mperham/sidekiq#1045]
Hey,
   We have configured our app to have sidekiq-pro. But during past few days, I am facing issues to process jobs since moreover, jobs are getting stuck. When I tried scaling the workers on heroku, it resumes the jobs as desired but after processing some of the jobs, it again gets stuck, thus unable to process further.
Currently, our worker process is scaled to 1. Our app has scheduled jobs processes which high number of background jobs.

Will you advise how to tackle on this ?

Thanks.

**Comment by tioteath** [comment]
> The segfault made the jobs getting stuck.

Is that bug or feature? segfaults must be handled properly, i.e. `sidekiq` must crash, or something.
