### ISSUE TITLE
Queue#latency throws "TypeError: nil can't be coerced into Float"

### ISSUE THREAD

**Issue by dimas-cyriaco** [mperham/sidekiq#1061]
The error happens in this line:
https://github.com/mperham/sidekiq/blob/76bef8ff5bbbc9ca5ff9764e814a0637096f2fbd/lib/sidekiq/api.rb#L116

It seems that the json returned by

```
entry = Sidekiq.redis do |conn|
  conn.lrange(@rname, -1, -1)
end.first
```

doesn't have an 'enqueued_at' key.

Here is an entry from my queue:

```
"{\"retry\":true,\"queue\":\"default\",\"class\":\"Sidekiq::Extensions::DelayedModel\",\"args\":[\"---\\n- !ruby/object:User\\n  attributes:\\n    id: 118157\\n"],\"jid\":\"2452b165d9e313afd1f7c3bc\"}
```

Do I have to do something special to add the 'enqueued_at' to the job?

**Comment by amiel** [comment]
I am also having this issue, and am using [rubykiq](https://github.com/karlfreeman/rubykiq). It looks like the job needs to have an `enqueued_at`, is that correct? I'll work on a pull-request to rubykiq.

**Comment by mperham** [comment]
@amiel Sounds right.

**Comment by amiel** [comment]
@mperham thanks!
