### ISSUE TITLE
Should we make the ActiveRecord middleware optional?

### ISSUE THREAD

**Issue by subelsky** [mperham/sidekiq#1069]
I'm working on an enhancement to the ActiveRecord middleware to partially mitigate connection pool problems like the ones caused by #847 (and numerous other issues). 

The change itself is easy, essentially this:

``` ruby
def perform(args)
  ActiveRecord::Base.connection_pool.with_connection do
    # do stuff
  end
end
```

but I'm having trouble getting a decent unit test written without breaking a bunch of other tests or resorting to disgusting hackery. I'd like to propose modifying the `default_middleware` (https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L23) like so:

``` ruby
def self.default_middleware
  Middleware::Chain.new do |m|
    m.add Middleware::Server::Logging
    m.add Middleware::Server::RetryJobs
    m.add Middleware::Server::ActiveRecord if defined?(ActiveRecord::Base) && ActiveRecord::Base.connected?
  end
end
```

if you don't like the `.connected?` check, I can change the middleware to rescue `ActiveRecord::ConnectionNotEstablished` and emit a warning (or, conversely, we could decide that's an error we want raised right away -- warning people to get their ActiveRecord connection setup before booting Sidekiq.

**Comment by thbar** [comment]
@subelsky by any chance, were you able to try the alternate method suggested in production? Is the code available anywhere maybe? I'm running into a number of issues ([more info here](https://groups.google.com/d/msg/sidekiq/_eFQGtAWm6E/1UXOPstW7ggJ)), so this could help. Thanks!

**Comment by subelsky** [comment]
Our PG usage stabilized so we didn't explore this further, can't really remember the circumstances anymore - sorry!

**Comment by thbar** [comment]
@subelsky no problem - thanks anyway, I'm investigating this possibility to solve my issue, appreciated!
