### ISSUE TITLE
Clustered Mode

### ISSUE THREAD

**Issue by mrrooijen** [mperham/sidekiq#1078]
Any chance something like this could be implemented for Sidekiq?

https://github.com/puma/puma#clustered-mode

This is useful if you're using MRI on for example Heroku, which provides 4 cores per dyno. Sidekiq without Rubinius or JRuby only uses 1 of them. Adding the ability to spawn 4 Sidekiq processes would allow you to leverage all 4 cores on a Heroku dyno.

E.g.

``` bash
sidekiq -q critical -q default -q low -w 4
```

Where `-w 4` would tell Sidekiq to spawn 4 Sidekiq workers, similar to what Puma does.

**Comment by webandtech** [comment]
I run sidekiq on heroku using foreman in production and it works fine.

I have not seen any crashes that I know of, but foreman's behavior is such that if one sidekiq process on the dyno crashes, that causes foreman to stop all processes, which in turn causes heroku to restart foreman, bringing them all back online.
