### ISSUE TITLE
Add the ability to drain a worker unless job is scheduled later

### ISSUE THREAD

**Issue by mattdelacdev** [mperham/sidekiq#1106]
To make sure jobs are correctly scheduled, it'd be good to have the ability to respect the scheduled jobs and use a library such [Timecop](https://github.com/travisjeffery/timecop) to make sure everything works as expected.

When using `HardWorker.drain` it doesn't care if the job is scheduled later or not, it just performs all of them.

**Comment by jfloff** [comment]
Just for the record, I did a slight variation of @iblue's answer:
```
[FooWorker, BarWorker, BazWorker].each do |worker_class|
      # split select and delete so we don't delete jobs while iterating
      worker_class.jobs.select{ |job|
        # Skip jobs that are not to be run yet
        !(job['at'] && job['at'] > Time.now.to_f)
      }.each { |job|
        Sidekiq::Queues.delete_for(job['jid'], job['queue'], worker_class.to_s)
        worker_class.process_job(job)
      }
    end
```
