### ISSUE TITLE
alias_method': undefined method `raw_push' for class `Class' in 'sidekiq/testing'

### ISSUE THREAD

**Issue by oliviermilla** [mperham/sidekiq#1125]
Hello,
    I'm having an error which wasn't showing off before either some recent sidekiq release or me switching away from ActiveRecord in favor of Mongoid.

Here is the entire code of a_spec.rb:

```
require 'sidekiq/testing'

describe A do
end
```

And the error is 

```
/home/muichkine/.rvm/gems/ruby-2.0.0-rc2/gems/sidekiq-2.13.1/lib/sidekiq/testing.rb:7:in `alias_method': undefined method `raw_push' for class `Class' (NameError)
from /home/muichkine/.rvm/gems/ruby-2.0.0-rc2/gems/sidekiq-2.13.1/lib/sidekiq/testing.rb:7:in `singleton class'
from /home/muichkine/.rvm/gems/ruby-2.0.0-rc2/gems/sidekiq-2.13.1/lib/sidekiq/testing.rb:6:in `<class:Client>'
from /home/muichkine/.rvm/gems/ruby-2.0.0-rc2/gems/sidekiq-2.13.1/lib/sidekiq/testing.rb:5:in `<module:Sidekiq>'
from /home/muichkine/.rvm/gems/ruby-2.0.0-rc2/gems/sidekiq-2.13.1/lib/sidekiq/testing.rb:1:in `<top (required)>'
```

Here is my bundle show:
- Ascii85 (1.0.2)
- actionmailer (4.0.0)
- actionpack (4.0.0)
- active_utils (2.0.0)
- activemerchant (1.37.0)
- activemodel (4.0.0)
- activerecord (4.0.0)
- activerecord-deprecated_finders (1.0.3)
- activesupport (4.0.0)
- afm (0.2.0)
- arel (4.0.0)
- atomic (1.1.13)
- bcrypt-ruby (3.1.1)
- builder (3.1.4)
- bundler (1.3.5)
- celluloid (0.14.1)
- chronic (0.9.1)
- coderay (1.0.9)
- coffee-rails (4.0.0)
- coffee-script (2.2.0)
- coffee-script-source (1.6.3)
- connection_pool (1.1.0)
- daemons (1.1.9)
- dalli (2.6.4)
- database_cleaner (1.1.1)
- delorean (2.1.0)
- devise (3.0.3)
- diff-lcs (1.2.4)
- dotenv (0.8.0)
- draper (1.2.1)
- dropbox-sdk (1.6.1)
- erubis (2.7.0)
- eventmachine (1.0.3)
- exceptional (2.0.33)
- excon (0.25.3)
- execjs (2.0.0)
- factory_girl (4.2.0)
- factory_girl_rails (4.2.1)
- faraday (0.8.8)
- ffi (1.9.0)
- figaro (0.7.0)
- fog (1.15.0)
- foreman (0.63.0)
- forgery (0.5.0)
- formatador (0.2.4)
- formtastic (2.2.1)
- guard (1.8.2)
- guard-rspec (3.0.2)
- hashery (2.1.1)
- hike (1.2.3)
- i18n (0.6.5)
- iban-tools (0.0.9)
- jbuilder (1.0.2)
- jquery-rails (3.0.4)
- json (1.8.0)
- kgio (2.8.0)
- listen (1.3.0)
- lumberjack (1.0.4)
- mail (2.5.4)
- method_source (0.8.2)
- mime-types (1.24)
- minitest (4.7.5)
- money (5.1.1)
- mongoid (4.0.0 d0fc225)
- mongoid-rspec (1.9.0)
- moped (1.5.1)
- multi_json (1.7.9)
- multipart-post (1.2.0)
- net-scp (1.1.2)
- net-ssh (2.6.8)
- nokogiri (1.5.10)
- origin (1.1.0)
- orm_adapter (0.4.0)
- pdf-reader (1.3.3)
- polyglot (0.3.3)
- prawn (0.12.0)
- prawn-qrcode (0.2.0)
- pry (0.9.12.2)
- rabl (0.8.6)
- rack (1.5.2)
- rack-test (0.6.2)
- rails (4.0.0)
- railties (4.0.0)
- raindrops (0.11.0)
- rake (10.1.0)
- rb-fsevent (0.9.3)
- rb-inotify (0.9.1)
- rb-kqueue (0.2.0)
- rdoc (3.12.2)
- redis (3.0.4)
- redis-namespace (1.3.1)
- redis-objects (0.7.0)
- request_store (1.0.5)
- rqrcode (0.4.2)
- rspec (2.14.1)
- rspec-core (2.14.5)
- rspec-expectations (2.14.2)
- rspec-mocks (2.14.3)
- rspec-rails (2.14.0)
- ruby-hmac (0.4.0)
- ruby-rc4 (0.1.5)
- sass (3.2.10)
- sass-rails (4.0.0)
- sdoc (0.3.20)
- sidekiq (2.13.1)
- simple_oauth (0.2.0)
- slop (3.4.6)
- sprockets (2.10.0)
- sprockets-rails (2.0.0)
- thin (1.5.1)
- thor (0.18.1)
- thread_safe (0.1.2)
- tilt (1.4.1)
- timers (1.1.0)
- treetop (1.4.15)
- ttfunk (1.0.3)
- turbolinks (1.3.0)
- twitter (4.8.1)
- tzinfo (0.3.37)
- uglifier (2.1.2)
- unicorn (4.6.3)
- warden (1.2.3)
- yard (0.8.7)

**Comment by klaut** [comment]
Had this exact same problem: Local tests ran fine, Travis was failing due to this error.
:+1:
