### ISSUE TITLE
Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by barmstrong** [mperham/sidekiq#1148]
We're seeing this on heroku with double dynos after a pretty short period of time:

```
2013-08-30T00:44:18.310995+00:00 heroku[sidekiq.3]: Process running mem=1024M(100.0%)
2013-08-30T00:44:18.311219+00:00 heroku[sidekiq.3]: Error R14 (Memory quota exceeded)
```

We're using Mongoid and the kiqstand gem (not sure if related). Before we start doing guess and check trying to random jobs to watch for memory growth, was curious if anyone has seen this before and what the culprit was?

Thanks!

**Comment by fabn** [comment]
Getting a similar behavior. Locally with `concurrency: 25` maximum used memory is ~350 MB on heroku I started with `concurrency: 10` then 7 then 5 and I still get R14. Now I put `concurrency: 3` and it doesn't happen.

**Comment by criticerz** [comment]
Having the same issue here. And memory is ramping up really quick. 

Has anyone found a solution to this? I have concurrency set to 7

**Comment by caedmonjudd** [comment]
Are you using New Relic?   That was the source of most of our memory
issues.

**Comment by mberman84** [comment]
We use newrelic and we get a gradual increase in memory over time. We use puma worker killer to restart every 12 hours or so and that helps. Also, switching to Heroku's new pricing scheme with 2.5gb for Web helped a LOT because we had more breathing room for our memory footprint.

**Comment by gorkunov** [comment]
I'm using strategy like unicorn-worker-killer. Original code I found on gitlabhq and adopted it for heroku.
It restarts dyno with sidekiq when memory limit is reached. 
`SIDEKIQ_MEMORY_KILLER_MAX_RSS`, `HEROKU_API_KEY` and `HEROKU_APP_NAME` should be provided using `heroku config:set`.
```ruby
require 'heroku-api'
# from gitlabhq
module Sidekiq
  module Middleware
    module Server
      class MemoryKiller
        # Default the RSS limit to 0, meaning the MemoryKiller is disabled (kilobytes)
        MAX_RSS = Integer(ENV['SIDEKIQ_MEMORY_KILLER_MAX_RSS'] || 0)
        # Give Sidekiq 2 minutes of grace time after exceeding the RSS limit
        GRACE_TIME = Integer(ENV['SIDEKIQ_MEMORY_KILLER_GRACE_TIME'] ||  120)

        # Create a mutex used to ensure there will be only one thread waiting to
        # shut Sidekiq down
        MUTEX = Mutex.new

        def call(worker, job, queue)
          yield
          current_rss = get_rss

          return if current_rss < MAX_RSS

          Thread.new do
            # Return if another thread is already waiting to shut Sidekiq down
            return unless MUTEX.try_lock

            dyno = ENV['DYNO']
            Sidekiq.logger.warn "current RSS #{current_rss} exceeds maximum RSS #{MAX_RSS}"
            Sidekiq.logger.warn "This dyno (#{dyno})  will restart in #{GRACE_TIME} seconds" 
            sleep(GRACE_TIME)

            Sidekiq.logger.warn "Restarting dyno (#{dyno})..." 
            heroku = Heroku::API.new(:api_key => ENV['HEROKU_API_KEY'])
            heroku.post_ps_restart(ENV['HEROKU_APP_NAME'], 'ps' => dyno) 
          end
        end

        private

        def get_rss
          Integer(`ps -o rss= -p #{::Process.pid}`)
        end
      end
    end
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::MemoryKiller
  end
end
```

**Comment by acanyon** [comment]
@barmstrong - Ugh! Migrating to aws.
