### ISSUE TITLE
Add Sidekiq::Batch.delete

### ISSUE THREAD

**Issue by dinedal** [mperham/sidekiq#1205]
We've been using the following monkey patch to delete batches once finished:

``` ruby
class Sidekiq::Batch
  def self.delete(bid)
    Sidekiq.redis do |conn|
      conn.multi do
        conn.del("b-#{bid}")
        conn.zrem("batches", bid)
      end
    end
  end
end
```

Any chance we could see this become apart of the main repo?

**Comment by alexives** [comment]
@mperham did expires_in go away? It looks like it was there, but we're in the process of upgrading one of our apps and that no longer seems to be an option as of sidekiq-pro 3.5.3 (I'm coming from the last version 2). I didn't see a deprecation warning...

If it did go away, is there an alternative that I'm overlooking?

**Comment by mperham** [comment]
@alexives Batches are now deleted immediately once they are successful.  There's no need for an expiry anymore.

**Comment by alexives** [comment]
Ah, thanks!
