### ISSUE TITLE
Chrome still makes update requests to dashboard after closing tab

### ISSUE THREAD

**Issue by augustj** [mperham/sidekiq#1224]
If I have a Chrome tab open, pointing to the Sidekiq dashboard, and then close it, I still see the update requests going to my server.  I have to quit Chrome to stop it.  Not a problem in Safari.  I'm using Chrome 30 on OSX.

**Comment by peresleguine** [comment]
I also saw this once on localhost using Chrome 43 with sidekiq 3.0.2. After restarting the browser I couldn't reproduce it though.
