### ISSUE TITLE
Sidekiq is running only on 1 CPU core (from 10 CPUs)

### ISSUE THREAD

**Issue by ondrejbartas** [mperham/sidekiq#1244]
Hello,

I think this is question not issue, but when I searched issues I found similarity with this:
https://github.com/mperham/sidekiq/issues/1078

I am running sidekiq on virtualized Debian which has 10 CPUs `cat /proc/cpuinfo`:

```
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 44
model name  : Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
stepping    : 2
cpu MHz     : 2399.841
cache size  : 12288 KB
physical id : 0
siblings    : 12
core id     : 0
cpu cores   : 6
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 11
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt lahf_lm ida arat epb dts tpr_shadow vnmi flexpriority ept vpid
bogomips    : 4799.68
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
..
..
..
till 9processor
```

When I start sidekiq with configuration:

`bundle exec sidekiq -e production -P /var/run/sidekiq/pids/sidekiq.pid -d -C /usr/local/www/app/config/sidekiq.yml -L /usr/local/www/app/log/sidekiq.log`

I get normal sidekiq process which is working perfectly fine, but when I push some load into queues, this process will use 100% CPU from only one processor. 
Load of this server is 1.

When I start another sidekiq process (same way but changing pid file), it will start working on new jobs on second core and server load is 2.

For my application I need lots of processes to run as fast ass possible and they consume a lot of CPU. So I just run 10 sidekiq processes with same config.

It gets job done, but my question is: 
Is this problem of Sidekiq or this is related to system?

I am working with puma and in it this problpem is solved by cluster mode.
It starts, then X.times fork itself where X is number of workers.

Thanks for Sidekiq its great and fast :D

**Comment by yoniamir** [comment]
@ondrejbartas if you have sidekiq enterprise, then sidekiq swarm is included. works great for us.
https://www.mikeperham.com/2019/07/19/something-for-nothing/
