### ISSUE TITLE
Sidekiq suddenly refuses to process the "default" queue

### ISSUE THREAD

**Issue by emas80** [mperham/sidekiq#1249]
I just encountered a very strange problem. 

I have a Sidekiq installation that has been running for months in our production environment. It is configured to have 5 queues, from the fastest one critical to the slowest batch.
I updated some days ago to the 2.15.1, I usually run the very latest version, after going through some testing on our other two environments.

This production installation of Sidekiq stopped suddenly to process the "default" queue. It processes without any problem another kind of queue, but the jobs in the default queue are accumulating.
I created a new queue, called "new_default", and I redirected to this queue the jobs that previously run into the "default", and the new queue is processed as expected.
Unfortunately, I don't have currently jobs going to the other three queues configured, so I can't say if other queues could be stuck.

I didn't do anything particular, I didn't break anything, it seems as it stopped working by itself, without any code modification, except that I redeployed the application on Heroku after a real minor change in a worker  - I don't think that changing a log level could destroy Sidekiq,

I read on another issue that a user had a problem like this, everything seemed fine, but Sidekiq did not process any jobs. The response was something similar to "redis and sidekiq not aligned".  (https://github.com/mperham/sidekiq/issues/710)
Checking the logs, I saw that Sidekiq had some problems connecting to Redis instance after the redeploy (timeout problem), and going back, I saw two others warning about 10 hours ago, that time without any redeploy.
I think that I could have the same problem of that guy. 
The Redis instance is hosted on Openredis.

My question is, how can I solve a situation like this? How can I check what's going on? How can I put on sync again the systems?

**Comment by ajahongir** [comment]
had same issue. default queue were not proccesing.

**Comment by ted-hanson** [comment]
I was running into a similar issue and noticed that queues that were being limited by the 'https://github.com/brainopia/sidekiq-limit_fetch' gem were not being processed regardless of what I did...  Flushing the corrupt keys and allowing it to regenerate fixed it for me:

`redis-cli KEYS "limit_fetch:*" | xargs redis-cli DEL`

**Comment by railslauncher** [comment]
I was migrated from RedisToGo to HerokuRedis and faced similar issue. I did two things.

1.
```
# config/initializers/sidekiq,rb

Sidekiq.configure_client do |config|
  config.redis = {url: ENV['REDIS_URL']}
end
```

2. changed REDIS_PROVIDER from REDISTOGO_URL to REDIS_URL

I am not sure which one solved the issue. But the issue solved.

**Comment by mperham** [comment]
@railslauncher Remove that block from your initializer.  You don't need it, it is the default.

**Comment by railslauncher** [comment]
@mperham Nice, I will remove it. Thank you.
