### ISSUE TITLE
Sidekiq nearly 10x slower than foreground processing?

### ISSUE THREAD

**Issue by bdmac** [mperham/sidekiq#1263]
I'm trying to figure out what exactly is going on that may be causing this.  I have some ideas but not positive yet.

I have a process that takes in a bunch of hotel reservation data via a CSV file and parses and inserts it into postgres.  I have a sample CSV file with 188 reservations that need to be created.  I have set up an admin interface for testing that allows me to check a box for whether I want the job to process in the background via Sidekiq (which is what normally happens) or just run it in the web process to compare.

The job parses the CSV and basically just massages things into params for AR to insert.  I have a service object that encapsulates business logic and is used in many places throughout the codebase and is in charge of actually taking the params and creating the reservation.  I have added benchmarking of the time it takes this central create_or_update!(params) method to run.

If I run the job in the foreground, the average call time for ReservationService.create_or_update! is **96.48ms**.  If I run the job through Sidekiq the average performance of that same method degrades to **874.52ms** for the same CSV file.  The only difference is the code path to get to the central create_or_update! call but the call being timed is identical.  That's a nearly 10x performance decrease. :-(

The ReservationService.create_or_update! call spawns off quite a few Sidekiq jobs to be processed on its own (whether initially running in the fg or bg).  My current hunch is that when running the main process in Sidekiq its thread is getting interrupted to run other Sidekiq jobs but when running in the fg web process it doesn't get interrupted.

This is all running on Heroku, 1x dynos for both web and worker.  We are running MRI 2.0.

**Comment by bloolizard** [comment]
@bdmac did his fix ever have any effect?  feeling like dealing with same issue as well.

**Comment by Nattfodd** [comment]
Is anyone else experienced this issue?

I have a pure-ruby app, that uses sidekiq for background processing. Sidekiq config is pretty brief:
```yml
:concurrency: 4
```

I thought I have a lock somewhere in my code, so I simply wrote a dummy function that just iterates over 10,000,000 array (from 1 to 10,000,000). And in a single thread it's processed faster than in 4 threads. Here is a code:

**Calling method (taketask):**
```ruby
namespace :messages do
  task :process do
    KafkaConsumer.new do |message|
      data[:tokens] = *(1..10000000)
      data[:tokens].each_slice(2500000).each do |tokens|
        Worker.perform_async(
          tokens,
          data[:rpush_apps],
          params,
          preprocessed_data.dup
        )
      end
    end
  end
end
```

**Worker itself:**
```ruby
class Worker
  include Sidekiq::Worker

  def perform(tokens)
    result = ''
    tokens.each do |i|
      ((i * i * i) / 59.3) * 987.7 / 11.4
    end
    result
  end
end
```

I start sidekiq with this command:
```bash
sidekiq -e production -r ./workers.rb -C ./config/sidekiq.yml
```

And these are results of executions:
```
2017-01-11T13:56:53.192Z 27520 TID-kzgrw Worker JID-9e59e83026409ac27d41b5e9 INFO: start
2017-01-11T13:56:57.517Z 27520 TID-kzgrw Worker JID-9e59e83026409ac27d41b5e9 INFO: done: 4.325 sec


2017-01-11T13:57:49.565Z 27520 TID-kyzjw Worker JID-60e06e90a7643d677759b2a8 INFO: start
2017-01-11T13:57:51.594Z 27520 TID-kzgrw Worker JID-9885d76eabc4b32b158db0e9 INFO: start
2017-01-11T13:57:52.312Z 27520 TID-kyzjw Worker JID-60e06e90a7643d677759b2a8 INFO: done: 2.746 sec
2017-01-11T13:57:52.824Z 27520 TID-kzgko Worker JID-d9dd42ef5d4b816c5c77e56a INFO: start
2017-01-11T13:57:53.700Z 27520 TID-kyzro Worker JID-246c8d5fd2e1f9686daf3398 INFO: start
2017-01-11T13:57:55.632Z 27520 TID-kzgko Worker JID-d9dd42ef5d4b816c5c77e56a INFO: done: 2.808 sec
2017-01-11T13:57:55.776Z 27520 TID-kzgrw Worker JID-9885d76eabc4b32b158db0e9 INFO: done: 4.182 sec
2017-01-11T13:57:55.881Z 27520 TID-kyzro Worker JID-246c8d5fd2e1f9686daf3398 INFO: done: 2.181 sec
```

As you can see, single-threaded process is at least 2 times faster than 4-threaded.

**Comment by mperham** [comment]
@Nattfodd You are performing very compute-intensive tasks, which do not scale across threads on MRI due to the GIL.  That's not "normal" server-side code.
