### ISSUE TITLE
Opinions regarding (L)GPL

### ISSUE THREAD

**Issue by zmoazeni** [mperham/sidekiq#128]
This was previously an email sent directly to Mike, but at his request I am opening an issue so he (and others) can respond publicly.
## 

First off, this isn't an email bashing your use of LGPL on https://github.com/mperham/sidekiq/ - I completely agree that your code/your decision. I have even read Zed's opinion on why he went with GPL ( http://zedshaw.com/essays/why_i_gpl.html ).

I'm curious about your use of dual commercial/GPL strategy. I've been reading about GPL lately, so seeing sidekiq using it was timely. The thing that doesn't click with me is that a company doesn't have to release GPL if they don't distribute a modified version of the source. Therefore, I could start a company, heavily modify sidekiq, make bags of cash (with big "$" printed on the side), and there would be no need for me to a) release my source or b) purchase the commercial license (which is understandably cheap in sidekiq's case). In fact, the only people who would really need a commercial license are the ones who would heavily modify it and sell it. In essence competing with sidekiq (and you) using your own labor.

So my question to you is, are you looking to use the dual licensing strategy to monetize companies who are using your code (a la Zed) or simply to keep a handle on the competition (that uses sidekiq's source)? Or something else entirely?

I have no ill will towards GPL, and I don't intend this email to change your mind for sidekiq. The more I think about monetizing GPL code w/dual source, the more something feels out of place and I wondered if you wrestled with this question too.

**Comment by cris** [comment]
> 3) companies who wish to embed Sidekiq as part of a closed source commercial offering.

Hey, @mperham I have a question about this item. Let's imagine I develop some kind of CMS that uses `Sidekiq` for background jobs.

As part of my business, I configure this CMS, setup up it for a customer in a cloud and then the customer can use it. So, each customer has its own instance of CMS.

As a part of this deployment, I also set up `Sidekiq`. Does it mean I need to purchase the commercial license? Or item 3 was about providing `Sidekiq` as a service - kinda some AWS queue service offering?

**Comment by mperham** [comment]
You aren’t shipping any code to the customer so the LGPL doesn’t trigger.
SaaS usage is fine.
