### ISSUE TITLE
Process Sidekiq Queue in random order

### ISSUE THREAD

**Issue by TheHodge** [mperham/sidekiq#1307]
We have a couple of use cases where we'd like to add stuff to the queue and either have the workers take a random job from it (rather than it being linear) or be able to mix the order of the queue up via redis / sidekiq commands. 

Is this possible currently?

**Comment by sferik** [comment]
@mperham For what it’s worth, there are constant-time algorithms for random queue popping (pick a random number *i*, between 0 and n; read the *i*th element and then replace it with the *n*th element).

I was also hoping for this feature. Maybe something just for Sidekiq Pro?

**Comment by mperham** [comment]
@sferik I'm not clear those algorithms will work when X Sidekiq threads are all trying to pop a job at the same time.  I'd have to use Lua which would add a lot of overhead to the fetch scheme.  Sidekiq never uses any Lua.

I don't think there's enough demand to warrant me building and supporting this feature but the [Fetch API](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/fetch.rb#L5) is stable and designed for 3rd parties to build their own fetch algorithms if you're so inclined.
