### ISSUE TITLE
Sidekiq.syncronous = true (Processing Jobs Automatically in Test Mode)

### ISSUE THREAD

**Issue by ahawkins** [mperham/sidekiq#132]
I'm proposing a new feature for sidekiq. I'd like to be able to test my app all the way through when doing integration tests. It's common for me to have jobs added to queues from other classes. It's very awkward to test this whole process because I have to assert that a job is in the queue, then find the right arguments, instantiate a new class and call it with those args. I think there is a better way. This feature is inspired by Resque, but resque fails with true syncronous  support.

I'd like to implement this feature in Sidekiq that work this way:
- Jobs are called with the JSON decoded arguments. In resque, the arguments are not roundtriped with JSON. For example, if you enqueue a job with a DateTime/Time/Date the job will receive that object and not whatever the JSON parser spits out.
- Plugins work in syncronous mode. Resque callbacks don't work in when inline is set iirc. This may have changed, but it always annoyed me.
- Current behavior is unchanged.
- Provide `sidekiq/rspec`, `sidekiq/test_unit`, `sidekiq/mini_test`

Thoughts?

**Comment by andresakata** [comment]
For specifc tests, you could mock like that:

```
allow(SomeWorker).to receive(:perform_async) do |something_id|
  SomeWorker.new.perform(something_id)
end
```

**Comment by RajRoR** [comment]
Thanks @andresakata!! :+1: 

It's a wondering for me that sidekiq doesn't have a cleaner way to achieve this goal! Maybe I didn't find one?

**Comment by Sankalan13** [comment]
Is there any way I can do this outside of Rspec. I have an end to end API automation suite that runs a bunch of services with the workers. They run in docker containers, is there any way for me to set the sidekiq to synchronous when I start it with `bundle exec sidekiq -c 1`
