### ISSUE TITLE
Can you override Sidekiq.configure_client?

### ISSUE THREAD

**Issue by mrrooijen** [mperham/sidekiq#1321]
Say you use Puma or Unicorn with their forking capabilities, but would still like to configure the Sidekiq client differently for a different process (e.g. `rails console`).

Assuming you have your app configured as such:

**config/initializers/sidekiq.rb**

``` rb
Sidekiq.configure_client do |config|
  config.redis = {
    :size    => 1,
    :timeout => 1,
    :url     => ENV["REDIS_URL"]
  }
end  
```

**config/puma.rb**

``` rb
on_worker_boot do
  Sidekiq.configure_client do |config|
    config.redis = {
      :size    => 16,
      :timeout => 1,
      :url     => ENV["REDIS_URL"]
    }
  end
end
```

Will the Puma process properly override the configuration to use `16` connections instead of just 1, and will a different process like `rails console` use `1` connection? The `on_worker_boot` is similar to Unicorn's `after_fork` block.

**Comment by zw963** [comment]
Cool, that what i want. 

Thanks
