### ISSUE TITLE
Connecting sidkiq to multiple redis servers

### ISSUE THREAD

**Issue by sshida1211** [mperham/sidekiq#1342]
So we run everything on AWS and every-time we release a big feature, we launch new servers and after we confirm everything works, we kill the servers with the old releases. 

The issue is some of the sidekiq tasks are scheduled to span over several days and thus we aren't able to shut down the sidekiq/EC2 instance that aren't really serving live web traffic. 

 Is there a way to specify multiple redis server to points to? So some tasks that span over long period of time, can be pushed to a clustered worker servers? 

 What we want is to be able to point to the local redis for any immediate tasks that may ran within 5 mins or so and push everything else to the clustered redis instance which the worker clusters reference. 

 Thanks!

**Comment by jonsgreen** [comment]
This is an old ticket so I want to confirm that this is now possible with the new Client API. We are getting ready to try out [SidekiqBus](https://github.com/queue-bus/sidekiq-bus) and need to have the bus jobs get sent to a different Redis instance on a separate server than where the regular workers are processed. 

      pool = ConnectionPool.new { Redis.new(url: ENV['SIDEKIQBUS_URL']) }           
      Sidekiq::Client.via(pool) do
         bus.publish(......)
      end

Is it recommended to memoize the pool somehow or is this not really a problem?

**Comment by mperham** [comment]
@jonsgreen Definitely make it a constant or memo if possible.  The whole point of a pool is to cache a valuable resource.
