### ISSUE TITLE
Dynamically assign queue?

### ISSUE THREAD

**Issue by Shpigford** [mperham/sidekiq#1346]
I'd like to have a "pool" of queues and basically dynamically assign jobs to certain queues based on certain variables.

ie. Assign job X to queue "high_priority" if they are a paying customer.

**Comment by jagthedrummer** [comment]
With the `set` method now available in workers this has become much easier.

```ruby
SomeWorker.set(queue: 'foo').perform_async(....)
```

https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/worker.rb#L169-L172
