### ISSUE TITLE
Workers fail with ruby 2.0 keyword arguments in the perform method

### ISSUE THREAD

**Issue by jeremyhaile** [mperham/sidekiq#1356]
My worker has a perform method that uses ruby 2.0 keyword arguments:

``` ruby
def perform(user_id: nil, send_notification: false)
```

This is then called with:

``` ruby
MyWorker.perform_async(user_id: current_user._id, send_notification: true)
```

Sidekiq shows the following options in the web console: (which is correct)

```
{"user_id"=>"4f2ab6349d285906d800000a", "send_notification"=>true}
```

However, the job fails with the following error:

```
WARN: wrong number of arguments (1 for 0)
WARN:my_worker.rb:3:in `perform'
sidekiq-2.16.1/lib/sidekiq/processor.rb:48:in `block (3 levels) in process'
```

I've played around with adding an initial argument and also keyword arguments. But that then fails with the same error, but just (2 for 1)

Basically it seems that the Sidekiq introspection code doesn't see the keyword argument at all and fails.

**Comment by adrianmacneil** [comment]
:+1: 

This issue shouldn't be closed (or at the very least, sidekiq should return a more useful error message stating that keyword arguments are not supported when it detects them).

**Comment by bshyong** [comment]
+1

**Comment by kpascascio** [comment]
+1

**Comment by jekuta** [comment]
+1

**Comment by ifyouseewendy** [comment]
+1

**Comment by ritec** [comment]
+1
