### ISSUE TITLE
Sidekiq has fake workers busy and returns internal server error

### ISSUE THREAD

**Issue by gamafranco** [mperham/sidekiq#1371]
Hi,

I'm on the 2.17.0, with Rails 3.2.14 and Ruby 1.9.3.

The admin inter ace of Sidekiq says 3 workers are busy, when there is only one worker running and it's free.

When I click on the busy workers link (admin/sidekiq/workers), I get an Internal Server Error.

Don't see error reporting on the rails log file, neither on NGINX error.log.

Thanks.

**Comment by DerKobe** [comment]
I had the same problem and it was caused by the redis gem version 3.1.0. In this version the srem method does not work with arrays as second parameter (but this is used in sidekiq 2.17.8 lib/sidekiq/api.rb:466). Updating to the redis gem to 3.2.1 fixed the problem.
