### ISSUE TITLE
New Relic instrumentation

### ISSUE THREAD

**Issue by fbjork** [mperham/sidekiq#14]
Would be super helpful to get New Relic instrumentation in Sidekiq. Would it be possible to implement using middleware or would have to be added to the rpm_contrib gem?

Here's the documentation:
http://newrelic.com/docs/ruby/monitoring-ruby-background-processes-and-daemons

**Comment by hopewise** [comment]
I know this is an old thread, but any feedback on this question on the NewRelic forum regarding SideKiq workers, would be appreciated: https://forum.newrelic.com/s/hubtopic/aAX8W0000015BQUWA2/detailed-transaction-reporting-for-sidekiq-workers-in-ruby-on-rails-application?t=1688650888384

**Comment by kfalconer** [comment]
@hopewise You probably want to add `add_method_tracer` or `trace_execution_scoped` annotations in your code to get more details. More info here: https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation/

**Comment by hopewise** [comment]
Thank you, so isn't this sufficient https://github.com/sidekiq/sidekiq/issues/14#issuecomment-14083214 ?

**Comment by kfalconer** [comment]
> Thank you, so isn't this sufficient [#14 (comment)](https://github.com/sidekiq/sidekiq/issues/14#issuecomment-14083214) ? I am not sure about difference between `add_transaction_tracer` and `add_method_tracer `

In my experience, no it is not sufficient.  From your post in newrelic you say the following:

>Is there a way to configure NewRelic, or an additional tool I could leverage, to get deeper insights into the execution of the perform method of a Sidekiq worker? I am interested in not only knowing that the perform method is slow, but also pinpointing exactly which lines within that method are causing the slowness.

In the link i sent it says the following:

> However, sometimes you need to instrument something more complex than a single method call. For example, you may want to instrument a few lines of code within a method, or you may want to start a transaction in one part of your code and finish it elsewhere.

and

> Sometimes a single method is so complex that tracking overall time doesn't give enough detail. In these cases, you can wrap a block of code with a tracer. Call trace_execution_scoped passing the code to trace as a block:

Newrelic is giving you the aggregate execution time of the entire `perform` call. If you want more details of other methods in the chain, you need to instruct newrelic to group them separately. Then you'd see them as a tree in the UI you can drill down into. You should have a general idea by looking at the code where the slow part is, start there add the additional instrumentation and see how it looks.

**Comment by hopewise** [comment]
Thank you @kfalconer , seems we will be testing with `trace_execution_scoped`

```
extend ::NewRelic::Agent::MethodTracer
class OurWorkerClass
def perform(lead_id, options = {})
  self.class.trace_execution_scoped(['Custom/slow_action/beginning_work']) do
    # perform code goes here
  end
end
```
