### ISSUE TITLE
Jobs being processed by the wrong app

### ISSUE THREAD

**Issue by natebird** [mperham/sidekiq#1414]
We have a staging environment with three apps running, each with their own Sidekiq process. On one of the apps we have a job that starts a chain of 3-4 other jobs. The first job is kicked off fine but sometimes it is ran by the wrong application. I'm not sure where to start troubleshooting this? Should we namespace queues in Redis? Would Passenger be the culprit here? Any leads would be nice.

Thanks

**Comment by vanboom** [comment]
I am running into the same issue - could you post a sample of how to configure for different namespaces?  Would it work to set the sidekiq queue in sidekiq.yml for each worker, then specify the queue for each rails app? 

thanks!

**Comment by natebird** [comment]
In each app configure the sidekiq.rb file similar to the following adding the namespace option.

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: Rails.application.secrets.redis_url, namespace: 'namespace' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: Rails.application.secrets.redis_url, namespace: 'namespace' }
end
```

**Comment by mperham** [comment]
I don't recommend using namespaces.  Use different numbered databases for different apps: `redis://localhost:6379/0`, `redis://localhost:6379/1`, `redis://localhost:6379/2`, etc.

This allows you to flush the database for an application without affecting your other apps.

**Comment by jonhyman** [comment]
@mperham FYI that more than 1 database per Redis instance is deprecated and won't be supported in Cluster mode (but will in non-cluster mode): https://groups.google.com/forum/#!topic/redis-db/x3-6GByC3xE.

My recommendation is that at the end of the post: multiple Redis instances (on the same host). Redis is single-threaded, so you're not getting any concurrency advantages by splitting it up across databases or namespaces.

**Comment by vanboom** [comment]
I have configured two apps on the same server, setting the default queue using the respective app name
    Sidekiq.default_worker_options = {'queue'=>'app1'}

Then in sidekiq.yml, I specify the queue, and run a Sidekiq worker for each app.  

Everything appears to be working -- no more conflicts.
