### ISSUE TITLE
Customize view

### ISSUE THREAD

**Issue by BrandonMathis** [mperham/sidekiq#1418]
It would be really nice if I could customize the view pages of the sidekiq monitor or at least change the css.

**Comment by MirTalpur** [comment]
Can you explain more about what you mean by set :views to that directory?

**Comment by jatin-apolloio** [comment]
> Can you explain more about what you mean by set :views to that directory?

# in my case it's Sidekiq::Web.set 'views', File.join(Rails.root, %w[app views sidekiq])
Sidekiq::Web.set 'views', File.join(Rails.root, %w[app views sidekiq])
