### ISSUE TITLE
Memory Leak with Ruby 2.1?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1421]
Several people have reported that Sidekiq processes with Ruby 2.1 appear to have a memory leak.

If anyone can provide more detail (ideally using the new ObjectSpace APIs provided in 2.1) that narrows down the cause, you'd be a hero in my eyes.

**Comment by tilo** [comment]
That page moved to : https://gist.github.com/krasnoukhov/a036bb7bc8c8416e9481
