### ISSUE TITLE
Sidekiq::Extensions::DelayedMailer.jobs not populating in the test environment

### ISSUE THREAD

**Issue by lserman** [mperham/sidekiq#1438]
I am trying to background the Clearance mailer. Following the documentation in the wiki I have this simple test:

```
Sidekiq::Extensions::DelayedMailer.jobs.size.should == 0
ClearanceMailer.delay.change_password(User.first)
Sidekiq::Extensions::DelayedMailer.jobs.size.should == 1
```

Which results in

```
Failure/Error: Sidekiq::Extensions::DelayedMailer.jobs.size.should == 1
  expected: 1
    got: 0 (using ==)
```

Right now I am using the fake Sidekiq mode as opposed to inline, but I've tried both. I am using 2.17.3. There is nothing funny that I can see about Clearance that I can see, looks like ClearanceMailer is just a normal ActionMailer. Any idea what is going on? Let me know if you need anything else.

**Comment by srt32** [comment]
The ordering solution fixed it for me. I've added a note to the wiki in https://github.com/mperham/sidekiq/wiki/Logging/_compare/40a7846288cbeca34ac84463b30bcbc3b0242c21...b4a5437f517f4ab1bdac2baf942ce20df93e525c.

Thanks!
