### ISSUE TITLE
How to gracefully finalize worker threads in case of sidekiq shutdown?

### ISSUE THREAD

**Issue by leonidlm** [mperham/sidekiq#1461]
Hi,

I stumble into a situation where I need to finalize the worker gracefully during sidekiq shutdown. Unfortunately I couldn't find a way of signalling to the worker that it has now 8 seconds to finish. 

Celluloid actors have the `:finalize` method, however the worker class is run inside an actor, but by itself it isn't an actor, therefore it can't use the finalize functionality.

Is it possible to achieve such functionality without monkey patching sidekiq processor class?

**Comment by heaven** [comment]
Our worker does run a few additional threads and when we shut down the sidekiq I need to let them know that we are shutting down. We perform long running jobs and need to store some data on shutdown, so that the next time the job started we can continue from the place where we left. This is especially useful with this gem: https://github.com/utgarda/sidekiq-status And following the pattern you force us to use we do loose that point. *Not all jobs need to be idempotent*.

**Comment by heaven** [comment]
@mperham I did not add any specs yet and did not do a pull request, but please take a look if that makes sense to be merged to Sidekiq.

It's not always possible to keep all jobs idempotent, we download big amounts of data and process them, and Sidekiq is good at this even with MRI, but just one iteration of our worker thread could take half an hour or longer and in case of restart we then have to start all over again.

Having a simple ability to know inside the job that we're going to shut down would be very and very helpful. And probably not just for us.

**Comment by mperham** [comment]
@heaven Something like this is far simpler:

```ruby
Signal.trap('USR1') do
  MyWorker.stopping = true
end
```

**Comment by heaven** [comment]
Yeah, I started from this but with `TERM` and `INT` signals, which often lead Sidekiq to freeze, so I decided to notify each job separately from Processor. Another issue was that Sidekiq needs a bit customized behavior for aborted workers, to send them back to Redis. If we simply notify workers/read the signals from workers and shut down in time, Sidekiq will consider these jobs complete and won't re-queue them.

**Comment by heaven** [comment]
@mperham any thoughts about this? Do you think this could be merged into Sidekiq eventually? This does not break the concept of idempotent jobs but adds an ability to gracefully terminate jobs by setting a single `terminated` flag on the job. And it's up to developers which concept to use and when. For my current project over 90% of all jobs are idempotent, but those 10% still exists and need a solution.

**Comment by mperham** [comment]
No, this will never be merged into Sidekiq.  Sidekiq is designed for many short jobs.  If you have long jobs, the official support is tuning `-t` and signaling USR1 well in advance of a deploy.

**Comment by heaven** [comment]
As I described above none of these do work well for long running jobs. And lots of people do use sidekiq for long running jobs too. Anyway, up to you.

**Comment by avit** [comment]
We would find this useful as well. We're still using Sidekiq 3.5 here because we are checking `Sidekiq::Fetcher.done?` at intervals in our long-running jobs. Not everyone has many short jobs...

**Comment by mperham** [comment]
Also note deployment event handlers might be useful: https://github.com/mperham/sidekiq/wiki/Deployment#events

**Comment by avit** [comment]
Thanks for that! So would this be the new supported way?

```
config.on(:quiet) do
  MyWorker.cleanup!
end
```

**Comment by mperham** [comment]
Exactly.  Those events handlers have existed since Sidekiq 3.0.

**Comment by avit** [comment]
Ha, that just shows how well Sidekiq's been running for us that I barely look at it for so long... :smile:
