### ISSUE TITLE
Monitor job duration / jobs history

### ISSUE THREAD

**Issue by troessner** [mperham/sidekiq#1462]
I'd like to monitor our sidekiq jobs a little bit closer, what i'd like to see is:
- A list of all processed jobs telling me how long they took
- Filtering that list by job classes, success / failure, and so on

As far as I can tell there is no way of doing this with sidekiq itself.
There is a gem out there which comes pretty close: https://github.com/socialpandas/sidekiq_monitor - this seems to offer everything I am looking for. However, this requires a heavy AR migration we cant run due to a rather complicated set up.

We recently purchased sidekiq-pro and I noticed that there is an enhanced monitoring feature: https://github.com/mperham/sidekiq/wiki/Metrics

However, this also seems to require a complicated set up, managing a statsd and Graphite service, monitoring them and so on.

Am I missing something here or is there really nothing we can do than to bite the bullet and use statsd?

**Comment by syedsanahassan** [comment]
@troessner was there something that you came up with for your requirement?

Setting up statsd+graphite/graphana is one more system to maintain, wish the sidekiq_monitor was maintained
