### ISSUE TITLE
Dead job queue

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1471]
Sidekiq 3.0 will introduce a dead job queue for jobs which keep failing after the 25th retry.

The DJQ cannot be a memory leak though; it has to be limited somehow.  What should the retain policy be?  6 months or 10,000 jobs?

If I configure a job to have 10 retries, should it go to the DJQ on the 11th?  I assume **yes**.  If I configure a job to have no retries, should it go to the DJQ upon failure?  I assume **no**.

**Comment by heaven** [comment]
@mperham Hi, how do we put the job to the morgue if retries are disabled? We're processing payments and if a job fails we don't need it to retry automatically but want to see all failed jobs in the morgue instead. Tried `retry: false`, `retry: 0`, and `dead: true`, but the job doesn't appear in the morgue anyway. Sidekiq 4.2.10.

**Comment by mperham** [comment]
`retry: 0` is how you get a job to skip retries and go straight to DJQ.

**Comment by kapildewade** [comment]
@mperham Hi, is there a way to customize DJQ size?

**Comment by artamonovdev** [comment]
> @mperham Hi, is there a way to customize DJQ size?

```
Sidekiq.configure_server do |config|
  config.options[:dead_max_jobs] = 100_000
  config.options[: dead_timeout_in_seconds] = 15_552_000
end
```

_Sidekiq does not store unlimited number of jobs in Dead queue forever. By default, right after adding a new job to the Dead queue, it removes all but last 10_000 dead jobs (Sidekiq.options[:dead_max_jobs]), it also removes all dead jobs older than 6 months (Sidekiq.options[:dead_timeout_in_seconds])._
