### ISSUE TITLE
Nested Batches

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1485]
Right now jobs can mutate Batches by adding new jobs **but** Batches can't currently be nested like database transactions.  A workflow like this is impossible today because we can't create a nested batch to wait for both D jobs to finish to trigger an E job.

```
    B  --  F
  /           \
A         D      G
   \    /   \  /
     C       E 
        \   /
          D
```

Add the notion of a parent batch.  The C job should be able to create a new batch whose parent is the batch C is part of.  The child batch must complete before the parent batch can be considered complete.  The child batch's callbacks should fire as normal.

1. Should the parent know about the child batch?
1. How should the UI change to reflect this relationship?

**Comment by mperham** [comment]
I think I figured out a clean way to implement this!!!!!!!  I'm hoping this will be the lead feature in Sidekiq Pro 2.0, coming this Spring!!

**Comment by ryansch** [comment]
Excitement! :rocket:

**Comment by jonhyman** [comment]
Sweet!

**Comment by fuzziness** [comment]
yeah!

**Comment by plukevdh** [comment]
much excite. such batch. very :doge:

**Comment by mperham** [comment]
The initial implementation is done.  I need to figure out a testing plan for Pro 2.0.  Anyone interested in beta testing in a staging environment?

**Comment by plukevdh** [comment]
:hand:

**Comment by aprescott** [comment]
@mperham I'd be down to test 2.0.

**Comment by mperham** [comment]
Got it.  I'll write up some testing / migration notes for Pro 2.0 this week so you guys can give it a test drive.  I want to finalize any data model changes before anyone else tries it out.  Here's the initial notes:

https://github.com/mperham/sidekiq/blob/master/Pro-2.0-Upgrade.md

**Comment by mperham** [comment]
Ok, gang, Sidekiq Pro 2.0.0.beta1 is now available to try out.  Please don't use it in a critical environment; it passes my basic testing but this is prerelease software.

```
gem 'sidekiq-pro', '2.0.0.beta1'
```

Feel free to send PRs for the Pro 2.0 Upgrade notes if something is missing or needs wordsmithing.

**Comment by mrhead** [comment]
This is awesome!

**Comment by harlow** [comment]
Expanding on the example from the README. Will the below sample run `SomeWork1` and `SomeWork2` before running `OtherWork`? i.e. `OtherWork` will not start until both jobs in `a` have completed.

```ruby
a = Sidekiq::Batch.new
a.on(:success, SomeCallback)
a.jobs do
  SomeWork1.perform_async
  SomeWork2.perform_async

  b = Sidekiq::Batch.new
  b.on(:success, MyCallback)
  b.jobs do
    OtherWork.perform_async
  end
end
```

**Comment by mperham** [comment]
@harlow Nope, OtherWork, SomeWork1 and SomeWork2 will all process in parallel but MyCallback is guaranteed to run before SomeCallback.  A nested batch is useful when a subset of jobs need their own callbacks.

If you want OtherWork to happen after SomeWork*, you need to chain the batches by creating the b batch in SomeCallback instead.

**Comment by harlow** [comment]
@mperham thanks. Sorry asking in two places... I realized after the tweet that a code sample would help convey what I was trying to ask!

This all makes sense now -- I'll fire off another batch in the callback. 

Thanks for all the swift replies. We're refactoring a few of our long running jobs into batches and the results thus far are looking great!

**Comment by mperham** [comment]
Almost a year to the day.  Sidekiq Pro 2.0 is now available!
