### ISSUE TITLE
Sidekiq with Mongoid/Kiqstand and Connection Pooling

### ISSUE THREAD

**Issue by daveharris** [mperham/sidekiq#1526]
Hi Mike,

We are running Sidekiq 2.17.7 in production running on ruby 1.9.3 with 25 workers doing mainly RestClient calls and processing the results. These get put into a Mongo database using Mongoid v3.1.3. I has been working great, until ...

Last year we noticed that we were getting errors which looked like DNS failures - we tracked this down to not enough file handles. We increased the amount to 64,000 as recommended by MongoDB. This has the unfortunate result of increasing the number of Mongo connections to 80% of 64,000 (with a max of 20,000). 

After a few months we hit the 20,000 connections in Mongo and starting getting errors from that. This all boils down to the fact that when a Sidekiq job finishes, it doesn't clean up the connection.

As I'm sure you are aware, this is a known issue with Sidekiq and Mongoid - so [Kiqstand](https://github.com/mongoid/kiqstand) was created. We installed this thinking that we were golden - however we now have a big performance issue (jobs are processed ~5x slower now) as Sidekiq presumably creates a Mongoid connection for every job. (What doesn't quite compute is why it's now slower than before when old connections were left around and new ones were created every time)

What we need is a connection pool (which I'm sure you know more than a little about). Mongoid/Moped is introducing a connection pool in version 4, but that requires Rails 4 which ideally needs Ruby v2. We will be moving there in the next few months when Mongoid v4 is stable, but we something for now.

Sorry to be talking so much about Mongoid when I know you aren't the maintainer but I would really love your opinion on what we could do.

I had thought you removing Kiqstand, and using manual connection pools using your connection_pool gem, but we have many different types of workers and the code changes would be to be far-reaching - only to be backed out when Mongoid actually gets connection pooling. Would it be easier to use something like MongoMapper which I understand uses a driver which supports connection pooling?

Can you give some advice about how best to achieve connection pooling? Sorry to create an issue for a non-bug.

Thanks for all the hard work on Sidekiq - apart from the Mongo connection issue it has been fantastic for about a year. We are hoping to upgrade to Pro very soon!

Thanks,
Dave

**Comment by amitsaxena** [comment]
The updated URL for the google group discussion is:
https://groups.google.com/forum/#!topic/mongoid/8rpSlgsRSSc

And the gist can be found here:
https://gist.github.com/markmeeus/6412088

And the one by @jonhyman (ruby 2.0) is here:
https://gist.github.com/jonhyman/7751687
