### ISSUE TITLE
Add process lifecycle events

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1534]
There's probably a lot of people interested in hearing when Sidekiq has:
1. Finished booting but before work is started
2. Starting quiet (USR1)
3. Starting shutdown (TERM)

Allow one or more blocks to be defined for each event.  Possible API:

``` ruby
Sidekiq.configure_server do |config|
  config.on(:start) do
  end
  config.on(:quiet) do
  end
  config.on(:shutdown) do
  end
end
```

**Comment by olivierlacan** [comment]
This appears to be at the process level, is there a way to hook into individual worker threads shutdown?

**Comment by mperham** [comment]
Nope. What are you trying to do?
