### ISSUE TITLE
Auto restart sidekiq in code changes

### ISSUE THREAD

**Issue by sahin** [mperham/sidekiq#1607]
@mperham, There is a feature that we would love to see in sidekiq, restarting sidekiq in each deploy can have problems. ( beginners or advanced users) 

We are nearly used and using many type of servers like thin, unicorn, puma etc etc.
You have to restart the servers in capistrano(or similar) , it is always a problem.
But in passenger, there is a very cool feature. 
"By creating or modifying the file tmp/restart.txt in the Rails application’s root folder. Phusion Passenger will automatically restart the application during the next request.
For example, to restart our example MyCook application, we type this in the command line:
touch /webapps/mycook/tmp/restart.txt
Phusion Passenger checks whether the timestamp of this file has changed in order to determine whether the application should be restarted."

It will be so great to add smth like this. When we touch the sidekiq_restart.txt, sidekiq will automatically load new code. What do u think?

**Comment by steve-cmi** [comment]
Can / shouldn't sidekiq respond to "touch tmp/restart.txt"?
