### ISSUE TITLE
Long running jobs disappear from Web UI

### ISSUE THREAD

**Issue by andoriyu** [mperham/sidekiq#1612]
Hi. I have couple of jobs that are running for long time (hours), and they removed from WebUI after hour or so. How can i fix that?

I can't split them into smaller jobs.

**Comment by glampr** [comment]
@mperham just out of curiosity what library/tools would you suggest for really long running jobs (days or weeks, e.g. collecting twitter streaming data)?

**Comment by mperham** [comment]
@glampr Go.

**Comment by ziaulrehman40** [comment]
I wonder @mperham if you still standby your statement that sidekiq is not for loooong running jobs, i have been recently facing issues of job disappearing lot of memory bloat etc on jobs which interact some apis, and takes ~5-6 hours. So wondering if it is something related to long running jobs or sidekiq latest version now doesn't have this limitation.

**Comment by mperham** [comment]
@ziaulrehman40 Sidekiq (and most any job system) is designed for small, short jobs.  Sidekiq Pro has batches to parallelize a long-running serial workflow.  Sidekiq Enterprise has [rolling restarts](https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts), allowing a Sidekiq process to run until job completion.  Those features give you options for dealing with long-running tasks.
