### ISSUE TITLE
Viewing historical queue depth

### ISSUE THREAD

**Issue by barmstrong** [mperham/sidekiq#1626]
Is there a way to see what the queue depth was over time?

This would be very helpful for capacity planning, or to see when a cron job for example enqueued a large number of jobs and backed things up.

Sometimes we receive anecdotal bug reports that we believe are due to jobs being backed up, but by the time we view the queue things are cleared out.

**Comment by Notalifeform** [comment]
@mperham  Having the number of processed jobs per queue would also be very helpful - I don't think that is currently recorded/exposed; is it?

**Comment by mperham** [comment]
It is not.  I'm working with @davydovanton this summer to build a Sidekiq history gem which will track more metrics.  These are more possible use cases for it.

**Comment by Notalifeform** [comment]
great to hear. I'm looking forward to that feature.

**Comment by davydovanton** [comment]
@Notalifeform, hello!
You can find sidekiq history project in this repository [davydovanton/sidekiq-history](https://github.com/davydovanton/sidekiq-history) (sorry this is GSoC project because that I don't accept any PR).
And if you have any proposals or ideas - I will happy if you share them :smiley:

**Comment by skwp** [comment]
https://github.com/phstc/sidekiq-statsd/blob/master/lib/sidekiq/statsd/server_middleware.rb seems to implement latency reporting. Is this not something sidekiq could do natively?

**Comment by mperham** [comment]
Sidekiq Enterprise will get this feature in 2016.  See issue linked above.
