### ISSUE TITLE
When starting sidekiq with -L or by adding a path to a log file within a config file - relative or absolute, sidekiq will not run, just hangs

### ISSUE THREAD

**Issue by bluengreen** [mperham/sidekiq#1640]
When starting sidekiq with -L or by adding a path to a log file within a config file - relative or absolute, sidekiq will not run, just hangs. Below are a few of the methods I've tried. The only way sidekiq will start is when I remove the -L switch or the log file line in the config. 

bundle exec sidekiq -e production -q queue

bundle exec sidekiq -e production -C /projects/myapp/current/config/sidekiq.yml

bundle exec sidekiq -e production -C /projects/myapp/current/config/sidekiq.yml -i 0 -P /projects/myapp/tmp/pids/sidekiq_production.pid 

bundle exec sidekiq -e production -C /projects/myapp/current/config/sidekiq.yml -i 0 -P /projects/myapp/tmp/pids/sidekiq_production.pid -L /projects/myapp/shared/log/sidekiq.log

nohup bundle exec sidekiq -e production -C /projects/myapp/current/config/sidekiq.yml -i 0 -P /projects/myapp/tmp/pids/sidekiq_production.pid >> /projects/myapp/current/log/sidekiq.log 2>&1 &
## using this config ->

development:
  :logfile: ./log/sidekiq_development.log
  :verbose: true
  :pidfile: ./log/tmp/pids/sidekiq.pid
  :concurrency: 1
  :queues:
    - [queue, 7]

**Comment by kaleemullah360** [comment]
@mperham is there any example file to completely setup sidekiq with `redis`, `rails 4`, `nginx`, `unicorn`.
