### ISSUE TITLE
Sidekiq rspec with no redis testing

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#1662]
Hi,

How to use mockredis with rspec to test sidekiq? Is there any issue regarding on this, can someone point it to me? Also I try to use something like this but it doesn't works

```
Sidekiq::Testing.fake! do
  email_notification_service = EmailNotificationService.new(JSON.parse(valid_email_notification))

  result = email_notification_service.add_to_queue!
  result.should_not be_nil
  result[:status_code].should eq(200)
  result[:status].should eq('Success')
end

class EmailNotificationService
  def add_to_queue!
    begin
      EmailService.perform_async('test')
    rescue Exception => e
      Rails.logger.info e
    end
  end
end
```

My expectation is when it execute this perform_async inside add_to_queue! methods it will be succeed. But I always got this:

```
#<Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (ECONNREFUSED)>
```

I tried to declare this also inside my spec_helper.rb

```
$redis = MockRedis.new
Sidekiq.redis = $redis
```

But it will generate error like this:

```
undefined method `has_key?' for #<MockRedis::Database:0x00000103329610>
```

How to test sidekiq with rspec? I need to mock redis because i want my test to be isolated(Not connecting to other services such as redis.)

Thanks

**Comment by esbanarango** [comment]
@lastobelus Thank you! That worked for me! :+1:

**Comment by kWhittington** [comment]
I've added
```ruby
require 'sidekiq/testing'
. . .
Sidekiq::Testing.inline!
```
To `config/environment/development.rb` and `/test.rb` but `.perform_async` methods still try to connect to `Redis` in `test` mode.

**Comment by mperham** [comment]
You likely have a third-party plug-in that is breaking it but won’t know until you show a backtrace of the error.
