### ISSUE TITLE
Rails.logger not working as expected from inide of the worker in rails 4

### ISSUE THREAD

**Issue by michaltn** [mperham/sidekiq#1682]
Hey I noticed that my Rails.logger calls no longer work when executed from inside of the worker.

If I call MyWorker.new.perform I can see the Rails.logger logging away but when I call MyWorker.perform_async I cant see the log statements in Heroku logs. 

I found a work around by aliasing 
  Rails.logger = Sidekiq::Logging.logger inside Sidekiq.configure_server but would like to understand why Rails.logger does not seem to work as I would expect inside my workers.

Thanks!
-Michal

**Comment by wkemmey** [comment]
Same problem here, but I'm not on Heroku.

**Comment by cometman** [comment]
I had the same problem.  AWS EB, rails 4.  Logger.info outputs to sidekiq console and logger.error doesn't.   So, I switched from doing logger.error to logger.info and all seems well.

**Comment by jordanmaguire** [comment]
I had a similar issue

```ruby
Logger.new(my_path).info("dongs")
```

was not showing up in `my_path`.

If you rewrite that to:

```ruby
::Logger.new(my_path).info("dongs")
```

it's all good in the hood.

**Comment by marshall-lee** [comment]
Maybe this one:
```ruby
Rails.logger = Sidekiq::Logging.logger
ActiveRecord::Base.logger = Sidekiq::Logging.logger
```
And also check out your `Sidekiq::Logging.logger.level` to be what you need it to be.

**Comment by saveav** [comment]
Yeps. I need to redirect too the log manually during the server setup, and all log finally make its way to `sidekiq.log` again.

**Comment by icapuccio** [comment]
I had the same problem with Rails 5 working on development. [Here a similar example](https://stackoverflow.com/questions/17606200/log-inside-sidekiq-worker)

Please re open the issue.

**Comment by reidcooper** [comment]
Whats the difference between having?

`Rails.logger = Sidekiq::Logging.logger` vs. `Sidekiq::Logging.logger = Rails.logger`

within the `config/sidekiq.rb`

**Comment by maxence33** [comment]
It seems I have a similar problem with Rails 5.2.4.3 and Sidekiq 6.0.7 (formerly 5.1.3)
`logger.debug "hello" ` does not print anything in development from the Sidekiq console itself
I have tried adding `Sidekiq::Logging.logger = Rails.logger` to the initializer but then Sidekiq is starting no more with error "uninitialized constant Sidekiq::Logging"

**Comment by choznerol** [comment]
According to [Logging - API Changes](https://github.com/mperham/sidekiq/wiki/Logging#api-changes)

- Sidekiq >= 6.0 : `Sidekiq.logger`
- Sidekiq < 6.0 ：`Sidekiq::Logging.logger`

So @marshall-lee's answer becomes like below when Sidekiq >= 6.0

```rb
# myapp/config/initializers/sidekiq.rb # In our Rails app, for example

Rails.logger = Sidekiq.logger
ActiveRecord::Base.logger = Sidekiq.logger

#  Sidekiq.logger.level = Rails.logger.level # In our Rails app, for example
```

**Comment by CeeBeeUK** [comment]
Inverting it, i.e.
```ruby
# myapp/config/initializers/sidekiq.rb
Sidekiq.logger = Rails.logger
``` 
is now outputting `logger.info`requests inside a job into development.log but this seems like it might be a bit smelly!
