### ISSUE TITLE
Complete vs. Success callback question

### ISSUE THREAD

**Issue by hendricius** [mperham/sidekiq#1697]
Hi,

I have a question regarding the Sidekiq pro's batch feature.

When are the callbacks exactly triggered? One of the jobs had an exception and is still in the queue. However the complete callback was already triggered despite the pending failed worker being completed.

`Completed all all products/categories with errors. Success: 90, Errors: 1`

Is the success callback always triggered when the batch finishes? I need to perform some actions after all workers have finished and none of them is in the queue anymore.

Thanks!

**Comment by amitmahajan12** [comment]
What happens if B never completes successfully and retries on it get exhausted? I am assuming on_success will never be called, but is there another way to detect that all jobs have either completed successfully or their retries have been exhausted?

**Comment by amitmahajan12** [comment]
Never mind, saw this: https://github.com/sidekiq/sidekiq/issues/3615#issuecomment-332895239
