### ISSUE TITLE
Force retry a Sidekiq job

### ISSUE THREAD

**Issue by fastcatch** [mperham/sidekiq#1704]
I have a Sidekiq job that may at times fail to complete successfully because the external API it consumes won't reply in a timely fashion.  It's not an exception (per ruby) but a pretty standard mishap in life :).

Thus I want to make Sidekiq put the job into the retry queue _without_ having to throw a "proper" ruby exception (which would have a number of side effects, most prominently it'd start bugging me for a fix via my error handler service).

How should I go about it?

**Comment by dhempy** [comment]
I posted a reasonable workaround here: http://stackoverflow.com/questions/19682594/sidekiq-airbrake-only-post-exception-when-retries-extinguished 

That said, it would be nice to be about to `return RETRY_LATER` or something for a cleaner exit.

**Comment by f3ndot** [comment]
@jonhyman Just so I understand correctly, when you say "reschedule" do you mean:

```ruby
# app/controller/some_controller.rb
class SomeController < ApplicationController
  def index
    # ...
    SomeWorker.perform_async(remote_resource: RemoteClient.get(params[:id]))
    # ...
  end
end
```

```ruby
# app/workers/some_worker.rb
class SomeWorker
  include Sidekiq::Worker

  def perform(remote_resource:)
    return self.class.perform_in(5.minutes, remote_resource: remote_resource) if remote_resource.ready?
    # do the work once remote resource is ready
  end
end
```

I somewhat wish I could get the exponential backoff that retries afford with a Ruby exception, without the actual raising of exceptions that, as @fastcatch said, causes unwanted side-effects.

**Comment by jonhyman** [comment]
@f3ndot yeah, we basically just do this but we only do it for exceptions that we know can happen / don't want to be alerted about. That is, we wouldn't want this retry indefinitely. For example we do it with Net::OpenTimeout in jobs that upload to S3, or AWS::CloudWatch::Errors::Throttling in monitoring jobs.

```ruby
def perform(*args)
  begin
    do_work()
  rescue KnownException => e
    Logger.info {"#{self.class} caught #{e.inspect()}, retrying"}
    perform_in(2.minutes, *args)
  end
end
```

**Comment by octalmage** [comment]
This is something that I would love to be able to do. We're reaching out to websites, so we want to use the existing retry functionality which triggers when there's an HTTP exception. But the HTTP exceptions are expected, so we want to be able to trigger a retry without the exception. The exceptions hurt our New Relic error rate and dirty Rollbar.

**Comment by mperham** [comment]
@octalmage https://rollbar.com/docs/notifier/rollbar-gem/#exception-level-filters

**Comment by fastcatch** [comment]
For the record: if I remember correctly I ended up defining a new exception and monkey-patching Sidekiq to handle this exception differently (i.e catch and force retry but do not re-raise).

It was a long time ago and have moved on since but I can dig you up the code if you need it.  (It'd take some time, though. And it's more than likely that Sidekiq has changed enough so that it cannot be used w/o modification.)

**Comment by octalmage** [comment]
I’d prefer not to manage blacklists for New Relic and Rollbar, especially since it could silence real errors. I think I’m going to do something like @fastcatch but with Sidekiq middleware. Recast the know exceptions and catch them in the middleware. I’ll let y’all know if this works.

**Comment by darkthirst** [comment]
@lucasdavila 
hey did you found a solution to this.

Basically I want to do "If I understood well by using perform_in it will schedule a new job, so the retry counter will start from 0 (zero), on the new job."
and also to kill the current job so as it doesn't throw any exceptions.

**Comment by rbucks** [comment]
Same, my case is I want to catch a known Exception and then throw it back to the Retry queue (my function relies on a 3rd party service that has intermittent problems) without it showing up in Sentry. So it's the case of yes, it's an error and I want it retried but no, I don't want it going to Sentry. 

As is, I can't catch the error because then it won't go to the Retry queue so my Sentry is littered with these known 500s and I have to clean it every week or so.

**Comment by mperham** [comment]
@rbucks configure Raven to not send the exception.

**Comment by user7788** [comment]
I just run into this problem also and temporary fixed it using a counter on the worker that randomly fails on a specific api call to prevent infinite loop:
```
perform(*args, counter = 0)
  ... 
  perform_in(10.seconds, *args, counter + 1) if error && counter < 3
end
```

**Comment by amir-biybulatov** [comment]
Hi @user7788, while trying your approach, I am getting this error.
`NoMethodError: undefined method `perform_in' for`

**Comment by user7788** [comment]
> Hi @user7788, while trying your approach, I am getting this error.
> 
> ```
> NoMethodError: undefined method `perform_in' for Worker
> ```

self.class.perform_in(10.seconds)
