### ISSUE TITLE
`retry: 0` not `retry: false`

### ISSUE THREAD

**Issue by karavanis** [mperham/sidekiq#1707]
In the documentation https://github.com/mperham/sidekiq/wiki/Error-Handling is suggested to pass `retry: false` as an option in order not to retry again the failed job.

Although after reading really fast this code: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/retry_jobs.rb#L141 I think that the retries should be set to 0 and that false would not work. Right?

**Comment by HenleyChiu** [comment]
@mpherma That line u linked to is no longer valid. Can you tell us the answer? In the future, you shouldn't only link to stuff when answering as those links can easily change.

**Comment by mikegee** [comment]
https://github.com/mperham/sidekiq/wiki/Error-Handling#dead-job-queue

**Comment by barrywoolgar** [comment]
New link: https://github.com/mperham/sidekiq/wiki/Error-Handling#dead-set

In case that changes: `retry: false` will discard the job after failure, `retry: 0` will send the job to the "Dead set" after failure. As I understand it, retry :false` is equivalent to `retry: 0, dead: false`.
