### ISSUE TITLE
 Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (ECONNREFUSED))

### ISSUE THREAD

**Issue by Javed43** [mperham/sidekiq#1720]
I'm using rails 4.1 and sidekiq-3.0.2. It's working fine on localhost. When I deployed app on heroku it gives an error. I have used following configuration in unicorn.rb

before_fork do |server, worker|
  # other settings
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection.disconnect!
  end
end

after_fork do |server, worker|
  # other settings
  if defined?(ActiveRecord::Base)
    config = ActiveRecord::Base.configurations[Rails.env]
    config['reaping_frequency'] = ENV['DB_REAP_FREQ'] || 10 # seconds
    config['pool']            =   ENV['DB_POOL'] || 20
    ActiveRecord::Base.establish_connection(config)
  end
end

**Comment by hopkinschris** [comment]
**+1** Changed `REDIS_PROVIDER` to `REDIS_URL` and all is right in the world.

**Comment by francirp** [comment]
+1 for REDIS_URL

**Comment by jakeatwork** [comment]
+1 for REDIS_URL

**Comment by michaelschmitz** [comment]
+1 for REDIS_URL

**Comment by johnnygoodman** [comment]
+1 for REDIS_URL

**Comment by zulhfreelancer** [comment]
For those who're using RedisCloud on Heroku, make sure you've this inside your env config var:

![00](https://cloud.githubusercontent.com/assets/3416976/17175563/cf3484b0-543a-11e6-93cb-aced8c6af623.jpeg)

And don't forget to create **redis.rb** file inside initializers folder that contains:

```
if ENV["REDISCLOUD_URL"]
    $redis = Redis.new(:url => ENV["REDISCLOUD_URL"])
end
```

**Comment by grempe** [comment]
+1 for REDIS_URL

All other combinations tried resulted in trying 127.0.0.1.

Setting REDIS_PROVIDER to REDISCLOUD_URL also failed.

Setting REDIS_URL to the same string as in REDISCLOUD_URL worked!

**Comment by simonc** [comment]
Hello. Still facing this issue. My problem is that it happens in Review Apps. Their creation fails and I cannot set REDIS_URL since it's removed when Heroku retries the creation.

Is there any way to configure things so that the connection is always established with the right URL?

Thanks

**Comment by mperham** [comment]
@simonc Set REDIS_PROVIDER as documented.

https://github.com/mperham/sidekiq/issues/1720#issuecomment-235573828
https://github.com/mperham/sidekiq/wiki/Deployment#heroku

**Comment by simonc** [comment]
The `REDISCLOUD_URL` variable was set as expected but it kept failing.

It turns out that we are using the sidekiq-cron gem and the initializer in charge of registering the jobs (the one calling `load_from_hash`) did not contain the condition

```ruby
if Sidekiq.server?
```

Everything is working properly now. I thought it might help someone, someday 🙂
