### ISSUE TITLE
Best way to end a job early

### ISSUE THREAD

**Issue by JakeAustwick** [mperham/sidekiq#178]
Not really an issue, just a question.

What's the recommended way of just exiting a job early? Raising an exception? or just returning something, or...?

``` ruby
if @order.status == 1
# End Job Here
else
#Continue
end
```

Thanks in advance.

**Comment by whalesalad** [comment]
Sorry to revive this incredibly old issue but I have one question: when logic is pulled out into separate methods on the worker what would be the best way to end early in that case?

For instance:

```ruby
def die(reason)
  Rails.logger.info("#{reason} – dying.")
end

def perform(params)
  if params[:is_update]
    die("This is an update, not supported *yet*") and return
  end

  begin
    @sale = Spree::Sale.find(params[:sale_id])
  rescue ActiveRecord::RecordNotFound
    die("The sale with ID #{params[:sale_id]} no longer exists") and return
  end
  
  ...removed for brevity
end
```

I would like my little `die()` method to kill everything without marking the job as a failure. Is there a special exception I can raise, or some other thing I can do to terminate the job without `die() and return` everywhere?

**Comment by mperham** [comment]
throw/catch?

**Comment by whalesalad** [comment]
@mperham yeah about 3 minutes after I submitted this comment I came to that realization -- sorry for the noise on this ticket and thank you for Sidekiq!
