### ISSUE TITLE
Mail interceptors skipped with delayed extension

### ISSUE THREAD

**Issue by agius** [mperham/sidekiq#1818]
[Example rails app showing the problem](https://github.com/agius/sidekiq_delay_tests)

run `rake test` and you can see where it does and does not raise errors

Basically, if you register an interceptor with Mail / ActionMailer, then use ExampleMailer.delay.email_method, it enters some kind of bizarro-land where it ignores the interceptors on Mail. The inform_interceptors method on Mail::Message is never called. No idea why.

Problem is fixed if you do not use delayed extensions (ie use a worker instead), but this is potentially a huge "gotcha" - we relied on interceptors to block emails where we couldn't fill in all the data.

**Comment by achru** [comment]
I am using 3.5.x through active job interface, and still interceptors are not called, if i call .deliver_now instead deliver_later, they are, any hint ?
