### ISSUE TITLE
Scheduler issues

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1841]
Reading through `sidekiq/scheduled.rb`, I noticed two issues:

1. The [error handling](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L50) doesn't go thru handle_exception, which means errors never go to any configured error service.  In part this is because we don't want to slam the error service, since we might be polling frequently (e.g. every second).  Perhaps some logic which rate limits any error sent to handle_exception to every 15 seconds?
2. There's a small window for job loss when we remove the job from the sorted set but haven't pushed it onto a queue yet.  Writing a Lua script to handle [this block of logic](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L35-L43) atomically would make sense.

**Comment by jaygen** [comment]
:+1:

**Comment by mperham** [comment]
#2159 is the new Lua-based scheduler.
