### ISSUE TITLE
MessagePack

### ISSUE THREAD

**Issue by jjaffeux** [mperham/sidekiq#1844]
Hi,

have you ever considered replacing JSON by MessagePack (http://msgpack.org) ? Didn't run any benchmark, but it could probably be a little faster and use less memory on the redis instance.

**Comment by ilyazub** [comment]
MessagePack, GZip, and Brotli may decrease the size of a single member in `schedule` from about 210 bytes to about 170 bytes (20% less). For comparison, shortening of JSON keys and values in the `schedule` set may decrease memory usage by 50%. For 100M scheduled jobs, it's a matter of choosing between 16GB and 32GB RAM server on VPS &mdash; approximately $1K per year.

Below is a comparison of original JSON vs MessagePack vs GZip vs Brotli vs shortened JSON.

Given the JSON member that takes about 215 bytes of memory.

```
> ZRANGE schedule 0 1 WITHSCORES
1) "{\"retry\":true,\"queue\":\"default\",\"class\":\"Searches::AsyncSchedulerWorker\",\"args\":[{\"id\":\"60c77be4260ca9914b0df05c\",\"host\":\"127.0.0.1\",\"port\":3000}],\"created_at\":1623686116,\"jid\":\"f12fcfe7a47e644e9607f990\"}"
2) "1623686176"

> DEBUG OBJECT schedule
Value at:0x7f5892477e70 refcount:1 encoding:skiplist serializedlength:215 lru:13073380 lru_seconds_idle:2
```

<details><summary>MessagePack member is 20% smaller than JSON</summary>

```redis
> ZRANGE schedule 0 1 WITHSCORES
1) "\x86\xa5retry\xc3\xa5queue\xa7default\xa5class\xbeSearches::AsyncSchedulerWorker\xa4args\x91\x83\xa2id\xb860c77b9b260ca98fd8bf72e7\xa4host\xa9127.0.0.1\xa4port\xcd\x0b\xb8\xaacreated_at\xce`\xc7{\x9b\xa3jid\xb8eb887928ed7009169a95460f"
2) "1623686103"

> DEBUG OBJECT schedule
Value at:0x7f3a9ce77e10 refcount:1 encoding:skiplist serializedlength:173 lru:13073311 lru_seconds_idle:2
```

</details>

<details><summary>GZipped member is 17% smaller than JSON</summary>

Haven't measured CPU usage of `Sidekiq.dump_json` and `Sidekiq.load_json` with GZip compression and decompression.

```
> ZRANGE schedule 0 1 WITHSCORES
1) "x\x9c\x1d\x8d\xcd\n\xc20\x10\x84\xdfe\xcfE\xd2\x84n\xda\xdc|\x06\x0f\x1eD$?[\xab\x16\xab\x9b\xe4PJ\xdf\xddE\xe62||\xccl\xc0Tx\x05W\xb8R\x03\xdfJ\x95\xc0A\xa2\xd1\xd7\xb9@\x03q\xf69\x0b9\x91\xe78Qv\xee\x98\xd7w<IOu&>/\xfc\"\x16\xd1\xf3]\xbc\xcb\x06\x8f$:\xaah\xed\x90PK\xf1C\x1f:\x0cc\x8ac\x10qZr\x11\xa3\xd5\xf6\xa0$\xad\xa0\xcf\xc2\x82\x8cRj\xbf\xca%\x93/\x94n^X\x8b\xda`\xdfu\x83j\xe0\xf9_N\xda\xe81`\x9f\xd0\xb4*XM6(\xb4\x18a\xff\x01A\xca=\x8c"
2) "1623685650"

> DEBUG OBJECT schedule
Value at:0x7f746c877de0 refcount:1 encoding:skiplist serializedlength:179 lru:13072861 lru_seconds_idle:2
```

</details>

<details><summary>Brotli is 23% smaller than JSON</summary>

Haven't measured CPU usage of `Sidekiq.dump_json` and `Sidekiq.load_json` with Brotli compression and decompression.

```
> ZRANGE schedule 0 1 WITHSCORES
1) "\x1b\xcb\x00`\x8c\xd4Vy#\x04\x0fA\x88\xcb)\x7f\xfa\x81$\xedV\x961w\xb1\xe8<=\xe1\x00\xa5\xad\xa2\xb4\x8a\x12j-\x00\t\xecvp\x93%\x1b\xd5iAf\xfc\xfcr\x99\xdf.o\xe6-\xfcO\x92\x95\x03\xbfA\x92\xab\xf9\xb5V\x92\na*\xbe\x10EO\xf3\x0b\x18_\x96Wv\xbf\xacg$\xca4\xa5\x89$\xd35.y\x96\x162\t\x8b\x89\xa3\xe1\xf2F\xd4R[D:\x83\xd3\xf1\xb2\x9c\x88\xfc\xfb\xf0\xa8\xc3q\xfd\xd2h.\xe6\x90Kh\xd8\xacg\xc44\xfa0\xcbZ\xa2\xf3\xd3\xd9D\x17\x13\xefKc\x99?"
2) "1623685955"

> DEBUG OBJECT schedule
Value at:0x7fdbf5677ed0 refcount:1 encoding:skiplist serializedlength:166 lru:13073159 lru_seconds_idle:2
```

</details>

<details><summary>Shortening of JSON keys reduces memory usage by 34%</summary>

```
ZRANGE schedule 0 1 WITHSCORES
1) "{\"c\":\"Searches::AsyncSchedulerWorker\",\"a\":[{\"i\":\"60c77eb6260ca9914b0df05f\",\"h\":\"127.0.0.1\",\"p\":3000}],\"cat\":1623686838,\"at\":1623686898}"
2) "1624686478"

> DEBUG OBJECT schedule
Value at:0x7f5892477cb0 refcount:1 encoding:skiplist serializedlength:142 lru:13074131 lru_seconds_idle:2
```

</details>

<details><summary>Shortening of JSON keys and values reduces memory usage by 53%</summary>

```
> ZRANGE schedule 0 1 WITHSCORES
1) "{\"c\":\"SearchesWorker\",\"a\":[{\"i\":\"60c77eb6260ca9914b0df05f\"}],\"cat\":1623686838,\"at\":1623686898}"
2) "1624686478"

> DEBUG OBJECT schedule
Value at:0x7f5892477f30 refcount:1 encoding:skiplist serializedlength:101 lru:13074549 lru_seconds_idle:2
```

</details>

That said, memory usage of `schedule` set can be decreased by shortening the keys of an [`item` from `perform_in`](https://github.com/mperham/sidekiq/blob/3330df0ee37cfd3e0cd3ef01e3e66b584b99d488/lib/sidekiq/worker.rb#L210) can be shortened during the serialization and deserialization.

@mperham What do you think about a community extension that decrease the size of a `schedule` set in Redis?

**Comment by mperham** [comment]
Please do not resurrect old issues. Open your own issue.
