### ISSUE TITLE
Sidekiq and "interrupted" jobs

### ISSUE THREAD

**Issue by abrambailey** [mperham/sidekiq#1853]
I just installed Redis and Sidekiq into my Rails 4 project (running on Linux). These are the steps I've taken so far:
1. Installation of Redis
   
   ```
   $ wget http://download.redis.io/releases/redis-2.8.13.tar.gz
   $ tar xzf redis-2.8.13.tar.gz
   $ cd redis-2.8.13
   $ make
   ```
2. Start Redis
   
   ```
   $ src/redis-server
   ```
3. Install Sidekiq
   
   ```
   gem 'sidekiq'(gemfile)
   $ bundle install
   ```
4. Start Sidekiq
   
   ```
   $ bundle exec sidekiq
   ```
5. Install sidekiq_monitor gem
   
   ```
   gem 'sidekiq_monitor' (gemfile)
   $ rails g sidekiq:monitor:install
   $ rake db:migrate
   mount Sidekiq::Monitor::Engine => '/sidekiq' (routes.rb)
   ```
6. Create a test worker
   
   ```
   # app/workers/hard_worker.rb
   class HardWorker
     include Sidekiq::Worker
   
     def perform(name, count)
       result = "#{name} #{count}"
       Rails.cache.write "perform_cache", result
     end
   end
   ```
7. Start rails server and browse to localhost:3000/sidekiq
   
   ![enter image description here](http://i.stack.imgur.com/MdW0t.png)
8. Open the rails console and trigger worker
   
   ```
   2.1.2 :002 > HardWorker.perform_async('bob', 5)
     Sidekiq::Monitor::Job Load (0.4ms)  SELECT  `sidekiq_jobs`.* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`jid` = 'ea5412116fc54ca26667f918' LIMIT 1
      (0.1ms)  BEGIN
     SQL (0.3ms)  INSERT INTO `sidekiq_jobs` (`args`, `class_name`, `enqueued_at`, `jid`, `queue`, `result`, `retry`, `status`) VALUES ('---\n- bob\n- 5\n', 'HardWorker', '2014-07-20 19:19:33', 'ea5412116fc54ca26667f918', 'default', NULL, 1, 'queued')
      (4.4ms)  COMMIT
    => "ea5412116fc54ca26667f918" 
   ```
9. Check Monitor again and see **interrupted** job
   
   ![enter image description here](http://i.stack.imgur.com/WWB7G.png)
10. Check for existence of Rails cache item
    
    ```
    2.1.2 :003 > Rails.cache.read "perform_cache"
     => nil 
    ```
    
    **Why is my job interrupted and what can I do about it?**

**Comment by richkettle** [comment]
I have recently encountered the "interrupted" jobs on sidekiq: Some would go through no problem, others wouldn't even run, no logs, nothing. But the ghost of them existed in the `sidekiq_jobs` table. 

This was a problem on our dev server. The cause of this was that our staging and production servers were incorrectly setup to use the same redis process. So if you encounter Interrupted jobs with seemingly no explination that might be a good place to start.
