### ISSUE TITLE
[WEB UI] add link to return to the app

### ISSUE THREAD

**Issue by seuros** [mperham/sidekiq#1873]
Right now there is no way to return to the app once we are in the dashboard unless we enter the URL manually or hit back x times.

I propose to add button or set the logo to redirect to configurable path. 
Let me know if i should start working on this.

**Comment by ryansimms** [comment]
I'm not proud of this, but I spent a fair amount of time finding an alternative and couldn't find anything - if there is an alternative then please let me know!

I have a Rails app that just has Sidekiq with Devise for auth and all I wanted to do was add a Logout link to the Sidekiq Web UI hence how I ended up here. So I set the app_url to be `/users/sign_out`, but having the button say 'Back to App' was pretty confusing so I did the following:

```
# Put in config/initializers/sidekiq.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/employees/sign_out">Logout</a><a style="display:none'
```

Which renders the button html as the following, hiding the second link it creates:

```
<a class="btn btn-inverse" href="/employees/sign_out">Logout</a><a style="display:none">Back to App</a>
```

I know, cringe, but it did the trick and maybe it'll be a bit of hacky help for someone else until an alternative is created (if it doesn't already exist).

**Comment by marcoadkins** [comment]
Building on what @ryansimms did I took it tiny step further to render a logout and back to app button:
```ruby
Sidekiq::Web.app_url = '/uses/sign_out" style="margin-right: 5px;">Logout</a><a class="btn btn-inverse" href="/"'
```
