### ISSUE TITLE
Testing Middleware

### ISSUE THREAD

**Issue by shedd** [mperham/sidekiq#1900]
I'm trying to test a custom middleware class that controls whether Sidekiq can run or not.  (We're doing a blue/green deployment and I only want Sidekiq to run in the live environment.)

My middleware looks like the following:

```
class Sidekiq::Middleware::OnlyRunInLive
  def call(worker, msg, queue)
    return unless Utils.am_i_live?

    # all seems to be ok, we can execute the worker
    yield
  end
end
```

Then I'm trying to test this:

```
require 'spec_helper'

describe Sidekiq::Middleware::OnlyRunInLive do
  before(:each) { Sidekiq::Worker.clear_all }
  before(:each) { Sidekiq::Testing.inline! }
  after(:each) { Sidekiq::Testing.fake! }

  before do
    $invokes = 0
  end

  class MockWorker
    include Sidekiq::Worker

    def perform
      $invokes += 1
    end
  end

  context 'in a live environment' do
    before do
      Utils.stub('am_i_live?') { true }
    end

    describe 'middleware does not block Sidekiq workers' do
      it 'executes normally' do
        expect($invokes).to eq(0)
        worker = MockWorker.new
        MockWorker.perform_async
        expect($invokes).to eq(1)
      end
    end
  end

  context 'in a non-live environment' do
    before do
      Utils.stub('am_i_live?') { false }
    end

    describe 'middleware blocks Sidekiq workers' do
      it 'does not execute' do
        expect($invokes).to eq(0)
        worker = MockWorker.new
        MockWorker.perform_async
        expect($invokes).to eq(0)
      end
    end
  end
end
```

My problem is that using the `inline` testing mode seems to always execute perform.  I've seen how others are testing middleware - for instance https://github.com/krasnoukhov/sidekiq-middleware/blob/master/test/test_unique_jobs.rb - and I've tried some similar approaches to trying to fire up a custom Sidekiq processor within my test, but I've been hitting a lot of internal errors.

How can I best test whether, from within an rspec test, my middleware will properly block the execution of a Sidekiq job?  Is there a way to do it without having to create a custom Celluloid processor as in the example that I referenced above?

Thanks!

**Comment by javierantonini-st** [comment]
Hey @shedd I know this is a very old thread, but I stumbled upon it while searching for how to test my own custom Sidekiq middleware. After much searching, I found the answer for including the middleware in RSpec testing here: https://github-wiki-see.page/m/mperham/sidekiq/wiki/Testing. Basically, the middleware chain is added differently for testing, it is to be done like this:

```rb
Sidekiq::Testing.server_middleware do |chain|
  chain.add Sidekiq::Middleware::OnlyRunInLive
end
```
