### ISSUE TITLE
Sidekiq startup crashes if config file is empty

### ISSUE THREAD

**Issue by jordan0day** [mperham/sidekiq#1901]
backtrace:

```
$ bundle exec sidekiq
undefined method `delete' for false:FalseClass
sidekiq-3.2.2/lib/sidekiq/cli.rb:357:in `parse_config'
sidekiq-3.2.2/lib/sidekiq/cli.rb:207:in `setup_options'
sidekiq-3.2.2/lib/sidekiq/cli.rb:37:in `parse'
sidekiq-3.2.2/bin/sidekiq:7:in `<top (required)>'
sidekiq:23:in `load'
sidekiq:23:in `<main>'
```

**Comment by henriquecf** [comment]
Hello. I have just had this problem on sidekiq 2.17.8 which is the newest of sidekiq 2.x I suppose. Will you integrate this on sidekiq 2 in the future?

**Comment by seuros** [comment]
@henriquecf, sidekiq 2 is unsupported. Please upgrade to latest version.

**Comment by mperham** [comment]
@henriquecf Sidekiq 2 is still supported but only major bugs or security issues will be fixed.  I prefer stability versus fixing every last bug at this point.
