### ISSUE TITLE
Allow configuring redis key expiry

### ISSUE THREAD

**Issue by nirvdrum** [mperham/sidekiq#191]
The Processor class sets various redis keys with an expiry of Sidekiq::Util::DEFAULT_EXPIRY.  The name "DEFAULT_EXPIRY" implies there's a way to configure it, but as far as I can tell, there isn't.  It probably should just be a set of utility methods in the Sidekiq::Util module, optionally set in the Sidekiq config.

**Comment by jwg2s** [comment]
Just stumbled across this - dealing with the same issue. Has anything moved on this front in terms of making the payload expiry shorter?

**Comment by mperham** [comment]
Don’t resurrect old issues, open your own specific issue.
