### ISSUE TITLE
uninitialized constant Sidekiq::Middleware::Server::RetryJobs::DeadSet

### ISSUE THREAD

**Issue by maccman** [mperham/sidekiq#1915]
The only plugin I'm using is sidekiq-status.

Here's the full backtrace:

https://app.getsentry.com/companyhub/production/group/29658008/

**Comment by usamanasirqb** [comment]
@mperham I am currently facing this issue, I have put require 'sidekiq/api' and  my sidekiq.rb is
`
require 'sidekiq'
require "sidekiq/web"
require 'sidekiq-status/web'

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 7.days # default
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 7.days # default
    chain.add Sidekiq::Middleware::Server::RetryJobs, :max_retries => 0
  end
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 7.days # default
  end
end
`
