### ISSUE TITLE
How to trace stale busy process (Always have 1 busy process)

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#1920]
Hi,

Why my sidekiq web monitoring show I have 1 busy process and can't be complete? how to trace this and solve this?

![screen shot 2014-09-01 at 3 09 30 pm](https://cloud.githubusercontent.com/assets/3470241/4105720/6f447920-31af-11e4-9cf4-305cb7292a65.png)

Best,
Faisal

**Comment by britg** [comment]
Can I re-open this? We're using Sidekiq 3.3.2 on Ruby 2.0.0-p537

I've verified our queue is empty, but immediately upon starting sidekiq, 1 of 25 threads become active and take up 100% CPU:

ps aux | grep side
keyring   7517 88.5  6.4 1400328 249560 ?      Sl   14:55  19:17 sidekiq 3.3.2 keyring [1 of 25 busy] 

![screenshot 2015-02-19 09 19 58](https://cloud.githubusercontent.com/assets/17409/6269405/9440bf5a-b818-11e4-9092-b5db01a2ba05.png)

There are no errors in the logs related to 'heartbeat' - and no job start/finished logs. Looking for direction on how to go about debugging what exactly the active working is doing.

**Comment by mperham** [comment]
@britg Please open your own issue.
