### ISSUE TITLE
ActionMailer proxy doesn't work with Rails 4.2

### ISSUE THREAD

**Issue by pbhogan** [mperham/sidekiq#1923]
I tracked it down to this line: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/extensions/action_mailer.rb#L17

Turns out `__send__` no longer works and just returns false instead of a mailer object. Digging in the Rails source reveals they use `public_send` instead, which does work:
https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_job.rb#L8

**Comment by chibicode** [comment]
So the wiki is out of date? I'm not knowledgeable enough to update this...
https://github.com/mperham/sidekiq/wiki/Delayed-extensions

**Comment by mperham** [comment]
@chibicode The delayed extensions are back to normal in the latest version.
