### ISSUE TITLE
Question: Is it possible to communicate between 2 processes through one Redis using Sidekiq?

### ISSUE THREAD

**Issue by gabrieljoelc** [mperham/sidekiq#1961]
I have 2 apps that are communicating through RabbitMQ right now, but I am very interested in switching to Sidekiq for queuing for the simplicity and possibly Sidekiq Pro. I need to see if my current use cases are possible with Sidekiq though. Here's some of the use cases I'm using RabbitMQ for:
- 2 processes/endpoints - I have 2 applications that are hosted in 2 different Heroku apps. App A owns the RabbitMQ add-on, and I just add the URL to the environment variables of App B. Both apps have subscribers to messages the other app publishes.
- Message types - I'm using RabbitMQ [direct exchanges](https://www.rabbitmq.com/tutorials/tutorial-four-ruby.html) so I can specify a routing key which I use as my message type.
- Multiple subscribers - [Direct exchanges](https://www.rabbitmq.com/tutorials/tutorial-four-ruby.html) also accommodate multiple subscribers for the same message type (routing key).
- Errors and retries - If there's an error in a subscriber, I rescue and publish to a retry queue that uses exponential backoff algorithm and RabbitMQ [message expirations](https://www.rabbitmq.com/ttl.html) to [dead-letter](https://www.rabbitmq.com/dlx.html) messages back to the queue the consumer for that queue failed in. After a number of retries, the message gets published to an error queue.

I have a branch per service that I replaced RabbtiMQ infrastructure with Sidekiq and kind of got them working by themselves, but I cannot figure out how to configure them to pub/sub to each other using the same Redis. Here are some of the things I have tried in Sidekiq to solve the use cases above:
- `Sidekiq::Client.push` - I was assuming I could use this to publish messages for message types that are defined in the other app (e.g. `Sidekiq::Client.push('class' => 'MessageTypeDefinedInAppB'...`), but as you probably know, this doesn't work if you have both processes running a Sidekiq server (I get `Constant not defined`). If I comment out the server configuration of App A and push a message defined in App B from App A, App B's worker does pick it up.
- Multiple Subscribers - I couldn't figure this one out, so as a workaround, I pushed to a `AppB::MyMessageType::Router` class that then `perform_async`s to all of the App B's `AppB::MyMessageType::Worker` worker classes (`const_get('Worker').constants.each { |w| w.perform_async`).
- Which process is the `Sidekiq.configue_client` and `Sidekiq.configure_server` for? - App A is a Rails app and App B is just a Ruby app. I put the `configue_client` and `configue_server` in an initializer in App A. For App B, I put them both in a file that gets loaded when I run Sidekiq i.e. `bundle exec sidekiq -r ./lib/load_all_the_things`. Essentially, that is my App B process. My assumption was is that I need to configure a client to publish and a server to subscribe (have workers). Is that correct? Or am I misunderstanding these 2 configurations entirely?

I'm guessing I'm missing something more fundamental about using Sidekiq and Redis for pub/sub, but I'm not finding a lot of resources that discuss something like this.

**Comment by pamio** [comment]
@mperham 
I tried to make your solution work on my machine. But I'm running through some issues. 
This is what I'm doing:
1. I have 2 app both on Rails, 1 is admin and the other one is frontend. 
2. I have about five workers in the admin which work great 
3. I have one worker in the frontend to clean all the caches. 
4. Both these apps use the same redis db but have different sidekiq processes 
5. Now, I have queues and namespaces to handle any conflicts between the jobs which is also fine. 
6. But, when I want the admin to queue a job for frontend which is `clear_cache` using the command

    object = Model.find('some-id')
    Sidekiq::Client.push('class' => 'KgWorker', 'args' => [JSON.generate({id: object.id, class: object.class, task: 'Cache'})], 'queue' => 'kg_front', 'namespace' => 'kg_main' )

which works but then the same is queued forever and never gets processed by frontend sidekiq.
7. Also, I can see the job queued in the sidekiq web under the admin app but the sidekiq in frontend shows empty always. 

Here are some extra details
1. Admin sidekiq.yml

     :queues:
        - kg_admin
        - default
        - <%= `hostname`.strip %>
2. Admin sidekiq.rb

         Sidekiq.configure_server do |config|
            config.redis = {
             url: 'redis://localhost:6379',
             namespace: 'kg_admin'
           }
        end

        Sidekiq.configure_client do |config|
          config.redis = {
             url: 'redis://localhost:6379',
             namespace: 'kg_admin'
          }
        end

3. frontend sidekiq.yml 

         :queues:
           - kg_front
           - default

4. frontend sidekiq.rb

         Sidekiq.configure_server do |config|
          config.redis = {
             url: 'redis://localhost:6379',
             namespace: 'kg_main'
           }
        end

        Sidekiq.configure_client do |config|
          config.redis = {
             url: 'redis://localhost:6379',
             namespace: 'kg_main'
          }
        end

Am I missing something here ? 

PS: I did start the sidekiq on the frontend app as mentioned by you 

    bundle exec sidekiq -q kg_front

**Comment by mperham** [comment]
@pamio Your problem is that you are using namespaces, so kq_admin's push will have the kq_admin namespace.  You can't change the namespace in Client.push.  Either stop using them or you will need to use Sidekiq's sharding support.

**Comment by pamio** [comment]
@mperham, its now working with the suggested change. However, the very reason I brought namespace into the picture was that I read somewhere on stackoverflow to have namespaces to avoid conflicts with other sidekiq processes. So one sidekiq process with namespace 'A' would always consume jobs from namespace A and another process with namespace 'B' would consume respectively. 

Anyway, its working now and thanks for your support. 

Cheers!

**Comment by mperham** [comment]
http://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by pamio** [comment]
@mperham, Thanks for additional knowledge.
