### ISSUE TITLE
Sidekiq stops processing new jobs, seems alive in system process list

### ISSUE THREAD

**Issue by jumski** [mperham/sidekiq#1963]
Versions:

```
sidekiq (3.2.4)
sidekiq-middleware (0.3.0)
```

Process seems alive and working:

```
$ pgrep -fl sidekiq
21956 sidekiq 3.2.4 tradeapp [23 of 55 busy] 
```

But webui states there are 0 busy workers.

sidekiq.yml

```
:concurrency: 55
staging:
  :concurrency: 55
production:
  :concurrency: 55
:queues:
  - [default, 10]
  - [mailer, 5]
  - [slow, 1]
```

This happens once or twice a day. Nothing specific in the logs.

Do you guys have any idea how to tacke this?

Thanks in advance

**Comment by jhoffner** [comment]
I am having this issue as well. Jobs stop processing about once a week, typically in the middle of the night. I'm running sidekiq 3.2.6 on Heroku. I even have an autoscaler implemented to help scale dynos if the job queue builds up. What happens is that the main worker will stop processing altogether, the scaled workers will start up and work fine, process the queue, and then when its back to the single dyno jobs stop being processed again. A process restart fixes the issue.

**Comment by seuros** [comment]
The latest version is 3.3.3, maybe you should upgrade.

**Comment by mperham** [comment]
Unfortunately you haven't given us any info to diagnose the problem. We need a thread dump.

**Comment by metripurari** [comment]
I have enqueued a process to parse the Spreadsheet with JRuby and POI library. I got an error in the sidekiq view from the java side. And then Sidekiq Stops Picking the Jobs from the queue. But the Process is still Alive when I have checked with 

       ps aux

Here is the versions of Sidekiq and others I am using
     sidekiq-4.1.1
    JRuby-1.7.19

Is the any way to reset the sidekiq so that it will start processing the jobs automatically.

**Comment by jdurand** [comment]
I just experienced this with sidekiq 4.1.4 on Heroku. It looks like the master process stopped responding but didn't crash. I had to scale down and up again.
Here are the relevant logs:

```
Nov 14 13:59:37 my-app heroku/worker.1:  State changed from up to down 
Nov 14 13:59:40 my-app heroku/worker.1:  Stopping all processes with SIGTERM 
Nov 14 13:59:41 my-app heroku/api:  Scaled to console@0:Hobby rake@0:Hobby web@1:Hobby worker@1:Hobby by email@example.com 
Nov 14 14:00:09 my-app heroku/worker.1:  Error R12 (Exit timeout) -> At least one process failed to exit within 30 seconds of SIGTERM 
Nov 14 14:00:09 my-app heroku/worker.1:  Stopping remaining processes with SIGKILL 
Nov 14 14:00:10 my-app heroku/worker.1:  Process exited with status 137 
Nov 14 14:00:15 my-app heroku/worker.1:  Starting process with command `bundle exec sidekiq -C config/sidekiq.yml` 
Nov 14 14:00:16 my-app heroku/worker.1:  State changed from starting to up 
```

Then is started taking jobs again.

**Comment by mperham** [comment]
@jdurand That logging doesn't help.  You need to follow the directions noted on the Problems and Troubleshooting wiki page.

**Comment by jdurand** [comment]
In case anyone ends up here with a similar problem, exit status 137 means your process was killed by Linux’s OOM (Out of Memory) killer.

@mperham: sorry for the trouble, but I think documenting this here might help others Googling this, and incidentally reduce the number of tickets being opened related to memory bloat issues.
