### ISSUE TITLE
Expiring jobs

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#1982]
**New Sidekiq Pro feature**

I want to create a job which has an expiration date.  After the given time period, if it hasn't already finished successfully, I want the job to disappear.

Statically defined:

``` ruby
class SomeWorker
  sidekiq_options expires_in: 1.hour
  ...
end
```

Dynamically calculated:

``` ruby
Sidekiq::Client.push('class' => SomeWorker, 'args' => [...], 'expires_in' => some_time_calc)
```

**Comment by justin808** [comment]
@mperham is this feature still valid? Link above is invalid. All Google could find for me was: https://github-wiki-see.page/m/sidekiq/sidekiq/wiki/Pro-Expiring-Jobs. Is that valid?
