### ISSUE TITLE
Show Sidekiq Pro version in Web UI

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#1991]
The Sidekiq Web UI currently shows the running version of Sidekiq, but not Sidekiq Pro:

![screen shot 2014-10-07 at 17 44 47](https://cloud.githubusercontent.com/assets/342081/4550885/39c4b23c-4e6b-11e4-88db-3326509f95f9.png)

I think it'd be useful to see this somewhere so it's clear what version is in use.

**Comment by mperham** [comment]
![screen shot 2015-01-21 at 10 36 53](https://cloud.githubusercontent.com/assets/2911/5842410/730b8ad4-a159-11e4-8181-50b221f08160.png)

**Comment by jaygen** [comment]
Not seeing this in sidekiq-pro 2.0.0.

**Comment by mperham** [comment]
Make sure you are running sidekiq 3.3.2.
