### ISSUE TITLE
How to get the Job ID inside the worker?

### ISSUE THREAD

**Issue by ChunAllen** [mperham/sidekiq#1999]
Hi @mperham I have a question is it possible to get the job id inside of a worker? 

Currently I can get the job id using 

```
job_id = MyWorker.perform_async("test")
```

but what I want is to get the job id inside of the worker like this: 

```
class MyWorker

   def perform(name)
        //get current job id here
    end

end
```

**Comment by AHaymond** [comment]
Does this only work with `MyWorker.perform_async`??

**Comment by mperham** [comment]
It works with Sidekiq::Client.push too.

**Comment by djpate** [comment]
That doesnt seem to work for me. 

```[20] pry(SearchIndex::Jobs::Indexer)> jid
NameError: undefined local variable or method `jid' for SearchIndex::Jobs::Indexer:Class
from (pry):20:in `evaluate_ruby'
[21] pry(SearchIndex::Jobs::Indexer)> self.jid
NoMethodError: undefined method `jid' for SearchIndex::Jobs::Indexer:Class
from (pry):21:in `evaluate_ruby'
[22] pry(SearchIndex::Jobs::Indexer)> self
=> SearchIndex::Jobs::Indexer```

**Comment by shreeramneupane** [comment]
Hi @mperham,

`MyMailer.delay.my_new_mail` has async the mail through sidekiq 3.4.2, ruby 2.2.1 and rails 4.2.1 .

And, inside the mailer i want `jid` as like below:

```
class MyMailer < ApplicationMailer
  def my_new_mail(applicant_id, message)
       mail(...)
       # jid 
  end
end
```

**Comment by mperham** [comment]
@shreeramneupane You cannot get the JID when using the delayed extensions.

**Comment by sumitisrani** [comment]
Hi @mperham,

When I use delay for
job_id =MyWorker.delay_for(2.day).perform_async(self.id)

And, inside the worker jid get changed, is not same as which I get in job_id
============================================================

But when I use perform at

job_id = MyWorker.perform_at(2.day.from_now, self.id)

And, inside the worker jid  remain same as we get in job_id

Can you please tell me this difference(delay_for and perform_at). I am unable to find this answer?

**Comment by mperham** [comment]
@sumitisrani Don't use delay on a Worker.

**Comment by sumitisrani** [comment]
Hi @mperham,

I am using perform at to delay the job

job_id = MyWorker.perform_at(2.day.from_now, self.id)

But when my job run jid get change,  the jid is not same as which I get when I schedule the job.
I saved that jid in my DB and when my job run I find the records with jid, update the record in my DB.
But due jid get change I am unable to find out the record and my job get failed.

My sidekiq version is (3.3.4)

**Comment by dhempy** [comment]
@mperham - Could you expand on "Don't use delay on a Worker?"  I'm converting a previous implemenation that used a worker (and some wonky `raise`s to implement a retry strategy) into a more pro-active retry that calls `.delay_for(5.minutes)` within the worker to schedule the next attempt, if needed.

Should I not be calling `delay_for` within a worker?  Can you point to an example of how a method can more cleanly re-invoke itself?

**Comment by mperham** [comment]
```ruby
def perform(*args)
  self.class.perform_in(5.minutes, *args)
end
```

**Comment by dhempy** [comment]
Thanks, @mperham !  :-)  I'll give that a whirl!

**Comment by w-A-L-L-e** [comment]
Thanks @mperham, needed this one also.

**Comment by pmaojo** [comment]
@dhempy In which file are you using this code:

`job_id = MyWorker.perform_at(2.day.from_now, self.id)

`
If its on a model, self.id will return the id of the object
 if its in a post model, you'll get the Post ID, not the ID of the job.

**Comment by birthdaycorp** [comment]
> @dhempy In which file are you using this code:
> `job_id = MyWorker.perform_at(2.day.from_now, self.id) `
> ?
> If its on a model, self.id will return the id of the object
> if its in a post model, you'll get the Post ID, not the ID of the job.

i too remain a bit unsure of how this is meant to be implemented. have you figured it out @pmaojo? if i call `perform_async` from a model, and then `perform_in` from within the worker (which is what seems to be the conclusion of this thread), there is still no impact on when the worker executes. 

further: the API states that it's bad/unscalable to search and delete jobs from queues unless the data needs to be repaired.

**Comment by henrik** [comment]
I wanted to get the JID inside a class called by the worker (for logging purposes), so I did the following.

In [Rails CurrentAttributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html), I added an attribute:

``` ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :sidekiq_jid
end
```

All our workers inherit an `ApplicationWorker` class, and I made it set the jid. I couldn't find a built-in callback that runs around `perform`, so I prepended:

```ruby
class ApplicationWorker
  include Sidekiq::Job

  def self.inherited(subclass)
    subclass.prepend(Module.new {
      def perform(...)
        Current.set(sidekiq_jid: jid) { super }
      end
    })

    super
  end
end
```

And speced it:

``` ruby
RSpec.describe ApplicationWorker do
  it "sets Current.sidekiq_job_id" do
    stub_const("MyWorker", Class.new(ApplicationWorker) {
      cattr_accessor :current_jid_was

      def perform
        self.class.current_jid_was = Current.sidekiq_jid
      end
    })

    Sidekiq::Testing.inline! do
      expected_jid = MyWorker.perform_async
      expect(expected_jid).to be_present
      expect(MyWorker.current_jid_was).to eq(expected_jid)
    end
  end
end
```

Now I can use `Current.sidekiq_jid` in a class called by a worker to get the JID.
