### ISSUE TITLE
Stuck Enqueued workers

### ISSUE THREAD

**Issue by krzkrzkrz** [mperham/sidekiq#2003]
Once a day or so, sidekiq just stops processing jobs. The number of enqueued jobs just pile up to a few thousand and don't get processed. As if they are just sitting there.. This is happening on our production server. However, the minute I visit Sidekiq's dashboard (https://foobar.com/sidekiq), the queue starts processing. Very strange.

Should I have some kind of background monitoring process like god or monit, to monitor and restart if the Sidekiq process crashed or went idle? 

I've looked at https://github.com/mperham/sidekiq/issues/1993 but not sure if they are entirely related. On issue 1993, they have suggested to update celluloid to 0.16, which I will try later on today. Curent version is celluloid (0.15.2), apparently has some locking issues.

In the meantime, anyone else come across this issue? Any feedback will be appreciated.

 I am using sidekiq (3.2.5)

**Comment by chinshr** [comment]
@krzkrzkrz Really? But why did the jobs started processing when you visited Dashboard? I seem to have the same problem, but restarting sidekiq seems to work. What is the sidekiq version you are running on right now?

**Comment by krzkrzkrz** [comment]
@chinshr Yea that's the only odd result about this. They start re-processing once you visit the Dashboard. Perhaps this strange behavior is due to high CPU spikes over a constant period of time. Not sure if Sidekiq could have handled this better.

The way forward for now, is to run the workers in batches instead...

**Comment by smasry** [comment]
Also seeing this with Ruby 2.2.0 and Celluloid 0.16.0
Ran a kill -TTID ... https://gist.github.com/smasry/9f567cda9a2ab71919e0

**Comment by chinshr** [comment]
@krzkrzkrz Thanks. My jobs are getting processed without problems (>200k/day) after figuring out that setting `reaping_frequency` on a MySQL connection will actually create a MySQL segfault and halt the sidekiq process. Removing `reaping_frequency` setting solved my problem along with making my jobs [thread safe](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting).

**Comment by jobygoude** [comment]
I have the same problem in production (AWS, ruby 2.0.0p481, sidekiq (3.3.2), celluloid (0.16.0), redis (2.8.4) ). I run kill -TTIN. Can you tell me if you detect the anomaly in log file.
https://gist.github.com/jobygoude/95789aacfbe558aa7539
Thank you in advance for your support.

**Comment by mperham** [comment]
@jobygoude I'd recommend upgrading to Ruby 2.2.

**Comment by alexfalkowski** [comment]
It didn't get much better for me when I upgraded to Ruby 2.2, it still got stuck. What I did to fix it is wrap a mutex around my job and that seemed to get it going again. I need to spend more time trying to diagnose why.

**Comment by mperham** [comment]
BTW I recently discovered that therubyracer gem can cause complete lockups of an MRI process.  If you are using it within your Sidekiq jobs, it's quite likely the cause of stuck processes.

I always update the Problems wiki page with the latest advice on dealing with stuck processes.  https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-workers

**Comment by imgarylai** [comment]
Hi, 

I have the same issue in production. I try to reproduce on my local machine, but everything works...
This my environment variable.  
```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
$ redis-cli -v
redis-cli 3.0.7
$ rails -v
Rails 4.2.5

sidekiq version:  v4.1.1
```
This is result when I did `$ kill -TTIN`.
https://gist.github.com/imgarylai/cfe934f84855ef3b824c

Here is my `Gemfile.lock`
https://gist.github.com/imgarylai/fa25bff4a191bc755d20

**Comment by jobygoude** [comment]
Hello,

do you use rubyracer gem in your project ? If yes, i advise you to use nodejs instead.

**Comment by imgarylai** [comment]
@jobygoude ,yes, I use rubyracer in my project. Okay, I will try this. Do you know what cause this problem?

**Comment by imgarylai** [comment]
@jobygoude After I change rubyracer to nodejs. The problem still exist. 
Here is what I see on the web UI:

<img width="1415" alt="screen shot 2016-03-18 at 12 00 36 am" src="https://cloud.githubusercontent.com/assets/1407908/13852327/9106a106-ec9c-11e5-9c5a-34df01d3e307.png">

Inside the rollbar page:

Job | Argument
---|---
Rollbar::Delay::Sidekiq | please look in gist: https://gist.github.com/imgarylai/3f3b74f6cb113f58c3da

When I found this problem, it seems that sidekiq was dead. 
```
$ ps aux | grep sidekiq
ubuntu   26723  0.0  0.0  10432   668 pts/1    S+   16:06   0:00 grep --color=auto sidekiq
```
So, I couldn't try `$ kill -TTIN` again. 

I don't have any idea to to...

**Comment by mperham** [comment]
@imgarylai Please don't resurrect old issues.  Open your own new issue and we'd be glad to help.

**Comment by imgarylai** [comment]
@mperham sorry for that. I will open a new issue. Thank you.
