### ISSUE TITLE
Sidekiq freezes

### ISSUE THREAD

**Issue by oleander** [mperham/sidekiq#2012]
I've had some difficulties with freezes the past year. After a couple of days sidekiq stops processing background jobs for some reason.

Here is the output from `kill -TTIN <pid>`
https://gist.github.com/oleander/909d2e5390921d9b7fe7

I'm running on the following platform
- sidekiq 3.2.5
- rails 4.0.10
- ruby 2.0.0 p247

I'm not sure if it's relevant, but here is a printscreen of the web interface.

![ps2](https://cloud.githubusercontent.com/assets/220827/4692854/0b051fc0-577d-11e4-8df0-6bb4569f4690.png)

**Comment by oleander** [comment]
It looks like my workers are still freezing for some reason. Here's the output from `kill -TTIN`. https://gist.github.com/oleander/4a93ea30bb6685dd00c5 Thanks.

**Comment by mperham** [comment]
@oleander I see nothing helpful in the TTIN output, unfortunately.

**Comment by oleander** [comment]
How about this one? https://gist.github.com/oleander/0764188605a34f2925a7

**Comment by mperham** [comment]
@oleander Ok, I just noticed it but both do have a subtle weirdness: almost all threads are blocked in this `handle_interrupt` routine:

```
2015-02-27T08:14:39.340Z 24365 TID-8qa9w WARN: /home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:72:in `sleep'
/home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:72:in `block (2 levels) in wait'
/home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
/home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:68:in `block in wait'
/home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
/home/webmaster/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/thread.rb:66:in `wait'
/opt/www/domain/shared/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/mailbox.rb:62:in `bl
```

I suspect a Ruby VM bug.  Upgrade to the latest version of MRI possible please.

**Comment by oleander** [comment]
I've upgraded to `ruby-2.0.0-p598`. I'll keep you posted.

**Comment by oleander** [comment]
That didn't work :( There's my new trace https://gist.github.com/oleander/3bbfb1069706e0d37570

**Comment by mperham** [comment]
I don't think a patchlevel upgrade will fix anything; I was suggesting upgrading to 2.1.x or ideally 2.2.x.

**Comment by rapofran** [comment]
Hi guys, I'm facing a similar issue. Once or twice a day sidekiq stops proccessing any new workers (though sidetiq stills enqueuing new jobs), it appears alive with ``ps aux | grep sidekiq`` with ``[15 of 15 busy]``.

The output of ``kill -TTIN <sidekiq_pid>`` is https://gist.github.com/rapofran/83afa64161c20b0f9a8d

As you can see there are workers that talk to Rserve through rserve-client, and they seem to be locked in the ``recv``call.

@mperham the TTIN output is normal? so this is an issue related to Rserve?

(plus I figured they pass through ``sidekiq/middleware/server/retry_jobs.rb`` so recently I changed to ``sidekiq_options retry: false`` so they don't try to retry)

Thanks a lot for this spectacular gem!

**Comment by mperham** [comment]
@rapofran Please do not hijack someone else's issue.  Open your own.

Your threads are all locked up talking to Rserve, this is bug in rserve-client, you need to be able to set network timeouts:

```
/home/deployer/apps/app/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:72:in `recv'
/home/deployer/apps/app/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/talk.rb:72:in `request'
/home/deployer/apps/app/shared/bundle/ruby/2.1.0/gems/rserve-client-0.3.1/lib/rserve/connection.rb:199:in `eval'
/home/deployer/apps/app/releases/20150311144233/app/models/feed_new_sentiment.rb:16:in `perform'
```

**Comment by rapofran** [comment]
@mperham thanks! and sorry for hijack someone else's issue

**Comment by oleander** [comment]
I've done some experimentation over the past 300M background jobs and found that the following setup works.

- sidekiq 3.3.0
- ruby 2.2.1
- rails 4.0.13

The sidekiq init file has the following line to ensure that `resolv-replace` is loaded.

``` ruby
Rails.application.config.after_initialize do
  if ENV["SIDEKIQ"]
    require "resolv-replace"
  end
end
```

@mperham Thanks for your help!
