### ISSUE TITLE
Add ActiveSupport::Notification instrumentation

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#202]
Seems like a nice feature to have when running within Rails.  What should we instrument?

**Comment by ncuesta** [comment]
@mperham I know this issue is old, but we have a bunch of Rails apps running Sidekiq and we are interested in having this implemented.. any chance this topic is reconsidered?

**Comment by mperham** [comment]
All PRs are welcome and considered.

**Comment by ncuesta** [comment]
Gotcha! I'll take a dive into this and send you a PR.
Thanks!
