### ISSUE TITLE
Not possible to globally set number of retries?

### ISSUE THREAD

**Issue by ncri** [mperham/sidekiq#2030]
Cannot find anything in the docs about it. I would simply like to have an option in sidekiq.yml.

Do I currently have to add an initializer, overwriting the base worker class to achieve this?

**Comment by ethagnawl** [comment]
@seuros Can `default_worker_options` be configured in sidekiq.yml or must that happen in an initializer?

**Comment by seuros** [comment]
@ethagnawl, initializer AFAIK.

**Comment by ethagnawl** [comment]
Good to know. Thanks for the prompt response!
