### ISSUE TITLE
Modify concurrency with signals  [discussion]

### ISSUE THREAD

**Issue by seuros** [mperham/sidekiq#2049]
I would like to use TTIN and TTOUT signal to increase the concurrency of Sidekiq. 
Right now i have to change settings every-time . It will be good to have a Signal API like Puma/[Unicorn](http://unicorn.bogomips.org/SIGNALS.html).
We could use another signal for debugging.

Thoughts ?

**Comment by mperham** [comment]
The problem with modifying concurrency in real time is that you also need to modify the connection pool size to ensure everything works properly.  I sense a lot of support issues around connection pool timeouts.  So in the end, no plans to implement.
