### ISSUE TITLE
test/workers/foo_worker_test.rb is missing from gem (3.3.0)

### ISSUE THREAD

**Issue by pravi** [mperham/sidekiq#2065]
and it causes 1 test failure.

 1) Failure:
WorkerGeneratorTest#test_worker_is_created_and_its_test [/home/pravi/forge/debian/git/pkg-ruby-extras/ruby-sidekiq/test/test_worker_generator.rb:15]:
Expected file "test/workers/foo_worker_test.rb" to exist, but does not

**Comment by pravi** [comment]
@ryansch can you have a look if I can give you ssh access to a debian test environment? This will help me update the sidekiq package in debian.

**Comment by boutil** [comment]
Hi!
I think I found the problem. In @pravi's situation, the name of the directory contains a '~'. The assert_file method calls shellescape to deal with directories with spaces in the name. But shellescaped directory/filenames cannot be correctly used with File.exists?

This is @pravi's situation:
```
require "shellwords"
filename="/build/ruby-sidekiq-S43bT0/ruby-sidekiq-3.3.0~dfsg/tmp/app/workers/foo_worker.rb"
escaped_filename=filename.shellescape
File.exist?(filename) #=> true
File.exists?(escaped_filename) #=> false
```
The problem will also occur if ~ is replaced by +, which are two canonical separators for the Debian dfsg suffix for cleaned upstream versions.

**Comment by pravi** [comment]
@ryansch would it be possible to allow ~ and + in filenames?

**Comment by boutil** [comment]
@pravi, the assert_file method is defined in rails, not in sidekiq. So the request for support of special characters in filenames in assert_file should go to Rails developers.

**Comment by pravi** [comment]
Submitted as a rails bug https://github.com/rails/rails/issues/20042

**Comment by ryansch** [comment]
:+1:
