### ISSUE TITLE
Event bus based on Sidekiq

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#2086]
Is there a event message bus implementation that is based on Sidekiq? 

Similar to this - https://github.com/taskrabbit/resque-bus (this is based on resque)

Thanks.

**Comment by jonsgreen** [comment]
By popular [demand](https://github.com/taskrabbit/resque-bus/issues/10) @bleonard the author of resque-bus has gracefully supported a [refactoring](https://github.com/taskrabbit/resque-bus/pull/13) that will allow for other adapters and already includes a test Sidekiq adapter. I am quite impressed with this gem with its clean DSL, intelligent architecture and thorough test suite . It is being used by the author in production and it allows multiple application to subscribe to events without the publishing application needing to assign to specific workers. We are intending to try this out on a multi-service application and see how well it scales.

A question I have for @mperham is whether there are any other ways besides the command line or sidekiq.yml file to assign queues to a Sidekiq client? It seems that resque allows for an ENV['QUEUES'] setting which is how resque-bus currently communicates to resque.

Also would you be interested in doing a final review of the Sidekiq adapter implementation when it is ready to offer any suggestions and confirm that the implementation is sound?

**Comment by kapso** [comment]
@jonsgreen YAY!! I have looked at `resque-bus` and is indeed very impressive work, `sidekiq` will be a welcomed integration. As always thanks @mperham @bleonard

**Comment by mperham** [comment]
1. The project needs to be renamed; the current name will just sow confusion.
2. You are correct, there's no way to adjust the queues once Sidekiq has started.
3. Sure, I'll give it a review.

**Comment by bleonard** [comment]
By popular demand. ha! I agree with the rename @mperham - suggestions welcome.

I was just thinking 99% of what we have now is called something (background-bus?)
resque-bus requires that and adds the resque adapter.
sidekiq-bus would do the same for sidekiq.
maybe delayed_job if anyone is still into that one.

**Comment by bleonard** [comment]
Just an update on this thread. I made this: https://github.com/queue-bus/sidekiq-bus
The generic (same as the base case) specs pass, but it could use sidekiq-specific integration tests and rake jobs that make things a bit easier.
Maybe some actual in-app testing too :-) If you have any issues, please make them on that repo.
@jonsgreen is helping out.
