### ISSUE TITLE
Auto-reload code changes in development

### ISSUE THREAD

**Issue by cvincent** [mperham/sidekiq#209]
It would be really nice if the Sidekiq worker picked up changes to the code while it was running, without requiring a restart to test them. Could it somehow hook into Rails' own auto-reload capabilities while in development?

**Comment by codener** [comment]
+1!

**Comment by EdvardM** [comment]
@zakmandhro, thanks for the tip!

```require 'sidekiq/testing/inline' if ENV['INLINE_SIDEKIQ'].to_i > 0```

is what I use currently.

**Comment by ryansch** [comment]
Just a note for others: This will keep the job data out of redis and will make batch callbacks fire early and may disrupt other middleware.

**Comment by chrisnicola** [comment]
While I get the altruistic ideals of TDD being professed here, I think it is awkward and inconsistent to have differing behaviour for code reloading in Rails and Sidekiq when using them side-by-side. I think it is absolutely having the option to allow people to have these two things act consistently.

I write a lot of unit tests, but regularly become confused when something doesn't behave as expected when I'm developing, and I have to work through the congitive friction of remembering that Sidekiq doesn't behave as Rails does and go and restart it. This inconsistency does not make for a good development experience and for that reason alone should be changed.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/2450
