### ISSUE TITLE
Namespacing different environments is not working for me

### ISSUE THREAD

**Issue by karlingen** [mperham/sidekiq#2104]
I'm running my production and staging environment on the same server. I'm trying to setup namespaces based on which environment that is running. For instance, I do not want my production environment to handle e-mails queued by the staging environment and vice versa. 
I'm using the same code for my local environment.

Here is the code:

``` ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: "sidekiq_app_name_#{Rails.env}" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: "sidekiq_app_name_#{Rails.env}" }
end 
```

Whenever I use this code the e-mails are being sent to the Default queue but they are not being processed. If I remove the "namespace" part, everything goes back to normal.
This has just been tested locally so far.

Any ideas what I might be missing here?

I'm running sidekiq v3.3.0 as well as capistrano-sidekiq 0.4.0 for deploying.

**Comment by mattherick** [comment]
Any progress on this issue? I have the same problem.. nothing gets processed..

**Comment by karlingen** [comment]
@mattherick The problem with my app was that I somehow manage to add the following code inside config.ru:

```ruby
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { :size => 1 }
end
```

Once removed, everything worked!

**Comment by mattherick** [comment]
And you does your initializer and sidekiq.yml now look like?

**Comment by karlingen** [comment]
```yaml
# config/sidekiq.yml
---
:concurrency: 5
staging:
  :concurrency: 25
production:
  :concurrency: 25
:queues:
  - default
  - mailers
:timeout: 15
```

```ruby
# config/initializers/sidekiq.rb
require 'sidekiq'

Sidekiq.configure_server do |config|
  config.redis = {
    url: "redis://#{ENV['REDIS_SERVER']}:#{ENV['REDIS_PORT']}/#{ENV['REDIS_DB_NUM']}",
    namespace: ENV["REDIS_NAMESPACE"]
  }
  config.server_middleware do |chain|
    chain.remove Sidekiq::Middleware::Server::RetryJobs
  end
  if Rails.env.production?
    config.error_handlers << Proc.new { |ex,ctx_hash| Airbrake.notify_or_ignore(ex, ctx_hash) }
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: "redis://#{ENV['REDIS_SERVER']}:#{ENV['REDIS_PORT']}/#{ENV['REDIS_DB_NUM']}",
    namespace: ENV["REDIS_NAMESPACE"],
    size: 1
  }
end
```
