### ISSUE TITLE
Memory leak if worker raises Exception instead of StandardError (or subclasses)

### ISSUE THREAD

**Issue by deborasetton** [mperham/sidekiq#2107]
Hi,

Sorry if the description below is too long!, but the **TL;DR** is basically the title and what follows is my adventure in Debugging Land.

I'm opening this issue to **a)** ask if this is a known problem and **b)** understand the underlying reason so it won't bite me in the future.
<hr>

I've been tracking down a memory leak in a Sidekiq process. I started debugging my original Rails application, then reduced it to a smaller, minimal Rails app, then to an even simpler Sinatra app and, finally, thanks to the example by @grosser in #1353, to just one file and a few lines of code:

https://gist.github.com/deborasetton/713229c641ba13c6b1b0#file-leak-rb

The results:
- When running this script with 5000 jobs and LEAK=0, the memory usage peaks at **~34MB**;
- When running the same 5000 jobs with LEAK=1, the memory usage goes beyond **250MB**!

After some time debugging both Sidekiq and Celluloid to find the difference in the code path for these two cases, it looks like [this line](https://github.com/celluloid/celluloid/blob/master/lib/celluloid/actor.rb#L167) from Celluloid, if removed, would solve the problem:

```ruby
# celluloid/actor.rb:167
raise unless ex.is_a? StandardError
```

When I remove it and re-run the test script, it seems to work, but I can't explain **why** this fixes my problem. I know very little about Sidekiq and Celluloid internals, so I couldn't find out where this `raise` gets `rescued` (even when stepping into the code with byebug/debugger), or even if it happens within Sidekiq or Celluloid, because, at this point, it seems the code keeps bouncing between the two and a lot of Actors and stuff... So I'm kind of stuck at my investigation.

Has anyone ever come accross this issue before? If not, I would still appreciate any pointers on where to look next!

<hr>

Extra information:

- I've now learned the hard way that I should be raising something else instead of `Exception`, but I'm still curious to understand why this has such different consequences in this case.

- I've tested this code with Ruby 2.0.0, 2.1.4 and 2.2.0, and with Sidekiq 3.2.6 and 3.3.0, all with similar results.

- If the aforementioned Celluloid line is removed, Celluloid specs still pass, so I wasn't able to find a spec or explanation for why it exists, but it's been there since commit [2394d7](https://github.com/celluloid/celluloid/commit/2394d7).

- I got to this line in Celluloid after following @krasnoukhov's [blog post on profiling Sidekiq](http://blog.krasnoukhov.com/posts/2013/01/07/profiling-memory-leaky-sidekiq-applications-with-ruby-2.1.html), so props to it!

- The leaked memory is not released after the jobs are done, but it seems this is normal behavior.

If you got here, thanks so much for your patience! Can you help me? :)

**Comment by sb8244** [comment]
Hey @deborasetton ! I checked this out and I think it boils down to this method:

```
    # Clean the thread locals of an incoming thread
    def clean_thread_locals(thread)
      thread.keys.each do |key|
        next if key == :celluloid_queue

        # Ruby seems to lack an API for deleting thread locals. WTF, Ruby?
        thread[key] = nil
      end
    end
```

When the condition is raise'd up, this code is never able to run and doesn't clean up after itself. I think it's a Celluloid issue so @tarcieri may be interested. I'm interested in looking to put a fix into Celluloid if that is the case.

**Comment by sb8244** [comment]
Confirmed this is not a Sidekiq bug. Here is my gist for an all Celluloid version: https://gist.github.com/sb8244/0a7e505dd1dafe432b31

It has to do with the pool management, so if you weren't using a pool, you wouldn't have been able to recreate.

I recommend closing this and I'm going to open on Celluloid.

**Comment by sb8244** [comment]
Fixed in Celluloid Master https://github.com/celluloid/celluloid/pull/486

**Comment by mperham** [comment]
Thanks for fixing this!

**Comment by deborasetton** [comment]
Thanks, @sb8244 and @tarcieri! That was really quick and the discussion that lead to the fix was very informative!
