### ISSUE TITLE
Enqueued jobs get lost

### ISSUE THREAD

**Issue by chenzeyu** [mperham/sidekiq#2119]
When sending mass delayed email via sidekiq, sometimes the enqueued jobs get cleared.

I am monitoring sidekiq with sidekiq web UI, some email jobs are enqueued and I can see how many are processed and how many are still in the queue, however suddenly enqueued jobs become 0, and actually all counters become 0. But sidekiq is running normally, if new jobs come, it can still enqueue and process them.

**Comment by mperham** [comment]
Something or someone is flushing your Redis db.

**Comment by chenzeyu** [comment]
I'm running redis for Sidekiq and Jbuilder cache, I don't see anyone flush redis, is it possible that Jbuilder cache is flushing? On Sidekiq wiki it says that if old Sidekiq process is  running, jobs may disappear, can you elaborate more on that part? Thanks!
