### ISSUE TITLE
Workers Process in Foreground using Production Mode

### ISSUE THREAD

**Issue by zeknox** [mperham/sidekiq#2121]
Running into an issue where sidekiq is working great in development environment. When changing over to production mode the workers seem to be processed in the foreground and the sidekiq web UI never shows any items processed or added.

I'm running my rails app in production mode using
<pre>
$ rails server -e production
</pre>

Running sidekiq in production mode using
<pre>
$ bundle exec sidekiq -e production
</pre>

Any assistance would be much appreciated!

**Comment by jonhyman** [comment]
I assume you have this somewhere in your code?

```ruby
require 'sidekiq/testing/inline'
```

If so, make sure that you're conditionally requiring it when in development/test. It is not automatically excluded in production because Sidekiq doesn't know anything about Rails.

**Comment by zeknox** [comment]
I originally thought this might be the issue as well, but that line has always been commented out in my worker. Here is a high level skeleton of my files:

File that calls the FileWorker
<pre>
FileWorker.perform_async(param)
</pre>

Actual FileWorker
<pre>
class FileWorker
  include Sidekiq::Worker
  #sidekiq_options retry: false
  #sidekiq_options :retry => 3
  #require 'sidekiq'
  #require 'sidekiq/testing/inline'

  def perform(param)
    ...
  end

end
</pre>

The weird thing is that the code appears to work great in development mode and cannot figure out why nothing will get enqueued within production.

**Comment by jonhyman** [comment]
In development though you can get it to enqueue in Redis?

**Comment by ryansch** [comment]
Could you post your Gemfile?

**Comment by ryansch** [comment]
Could you also grab the value of `Sidekiq::Testing.__test_mode` from your production environment?  If you get an uninitialized constant error that's also interesting.

**Comment by mperham** [comment]
Let's see your initializer.  I wonder how you are connecting to Redis.

**Comment by zeknox** [comment]
@jonhyman Yes, in Development I can get everything working and enqueue the workers without an issues. Simply changing rails to run in production mode causes workers to not enqueue for whatever reason.

@ryansch here is a copy of the Gemfile:
https://gist.github.com/zeknox/0694a76e9026da5d68cc

**Comment by zeknox** [comment]
@mperham Here is what my initializer looks like:

<pre>
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/12' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/12' }
end
</pre>

**Comment by zeknox** [comment]
@ryansch here is a copy of `Sidekiq::Testing.__test_mode`

<pre>
$ rails c -e production
Loading production environment (Rails 4.2.0)
2.1.1 :001 > Sidekiq::Testing.__test_mode
 => :inline 
</pre>

**Comment by ryansch** [comment]
That's certainly the problem then.  Thanks for that output.  Now we just have to figure out where 'sidekiq/testing' or 'sidekiq/testing/inline' is being required.  The correct output in your dev/prod environments should be `NameError: uninitialized constant Sidekiq::Testing`.

**Comment by zeknox** [comment]
Ok great, tell me where to look or what you need from me to narrow this down.

**Comment by ryansch** [comment]
Have you tried searching your application (grep, ag, etc)?  You're not doing anything crazy in your gemfile that would cause inline to be set in production but not in development.

**Comment by zeknox** [comment]
Alright I've got some more info here from trial and error.  I found out that if i modify the production.rb line `config.eager_load = true` to false everything works perfect again.

Here is now what my console displays with disabling eager loading.
<pre>
$ rails c -e production
Loading production environment (Rails 4.2.0)
2.1.1 :001 > Sidekiq::Testing.__test_mode
NameError: uninitialized constant Sidekiq::Testing
  from (irb):1
  from /Users/username/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
  from /Users/username/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
  from /Users/username/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/username/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/username/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
</pre>

**Comment by mperham** [comment]
This will check your entire source base: `git grep testing/inline`

**Comment by zeknox** [comment]
Yes, I do have a couple of thos require lines in some of my workers:
<pre>
$  git grep testing/inline
app/workers/xxx1_worker.rb:  require 'sidekiq/testing/inline'
app/workers/xxx2_worker.rb:  require 'sidekiq/testing/inline'
</pre>

Am I correct in assuming that eager loading sees these require statements (even though they are not any of the workers in question) and places the entire sidekiq library in test mode?

**Comment by mperham** [comment]
Yep, testing mode is process global.

**Comment by mperham** [comment]
Generally you should put that option in your initializer since it's a global option.

**Comment by zeknox** [comment]
So the reason I placed some of the workers in 'testing/inline' is because I needed those to operate synchronously in order. How can I make workers operate in order instead of asynchronous by default?

**Comment by ryansch** [comment]
You can do that yourself.  Call `SomeWorker.new.perform(args)` instead of `SomeWorker.perform_async(args)`.  A sidekiq worker is just a ruby class.

**Comment by zeknox** [comment]
Thanks everyone, this has been extremely helpful and informative!

**Comment by ryansch** [comment]
Anytime!

**Comment by mcollie1** [comment]
When you ran `bundle exec sidekiq -e production`, what happened as a result of it not working?  Did the prompt hang, did it throw an error message, or did something else happen? When it runs perfectly, what should happen in the command prompt?  

I'm trying to run sidekiq in production mode also -- mine too runs fine in development -- but I don't see the sidekiq "logo" like in development.  The prompt just sits there (for lack of better wording). However, when I run `ps aux | grep sidekiq` or `ps aux | grep [s]idekiq`, I receive output indicating it's running.  

` 5:13PM   0:02.65 sidekiq 3.4.2 `.....

**Comment by mperham** [comment]
@mcollie1 https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L156

**Comment by mcollie1** [comment]
That was fast. Thanks! Now I have to figure out the Redis configuration.
