### ISSUE TITLE
Queue without Worker

### ISSUE THREAD

**Issue by louis** [mperham/sidekiq#2122]
Hi, is it possible to add jobs to a queue and just keep them there without a worker processing them?  We would like to be able to leverage Sidekiq for this and use another system (that will use the Redis API directly) to "pop" messages from this queue to process them.

Thanks!

**Comment by jonhyman** [comment]
This can definitely be done with Sidekiq, as it simply issues an `LPUSH` in Redis to add jobs. Though you wouldn't get any of the benefits of middleware, batching, dashboard job status, stats, etc. that you get if you don't use the Sidekiq workers.

Also the jobs will be encoded in the Redis queue in Sidekiq's format (which is JSON) so after you `RPOP` you'll need to decode the JSON and be vulnerable to however Sidekiq's format changes over time.

**Comment by louis** [comment]
That was quick, I love it!  I get the benefits aspect, but would it at least appear in the queue when using the Sidekiq UI?

Here's what I've done so far which fails:  
        redis = Redis.new(:url => "redis://host:port/db")
        msg = { 'args' => [self.as_json], 'jid' => SecureRandom.hex(12), 'retry' => true, 'enqueued_at' => Time.now.to_f }
        redis.lpush("namespace:queue:render", JSON.dump(msg))
        redis.sadd("namespace:queues", "render")

Error from Sidekiq log: : 2015-01-07T19:47:31Z 70662 TID-oxwb3kv10 WARN: undefined method `constantize' for nil:NilClass

**Comment by louis** [comment]
Sidekiq version 2.15.0

**Comment by ryansch** [comment]
I thought you wanted to use sidekiq on the enqueue side and custom code on the dequeue side.  Why are you manually enqueuing them?

**Comment by louis** [comment]
Good question, guess I don't know what alternatives there are.  I don't have a worker to perform_async and didn't see an explicit add or push in the Queue API docs.  Sounds like I might have overlooked something though!

**Comment by jonhyman** [comment]
(unrelated, but 2.15.0 is very old, you should update)

**Comment by louis** [comment]
No doubt! Plan to when I can find the time :)

**Comment by jonhyman** [comment]
Honestly it sounds like you're trying to hack some dashboard together in lieu of building your own for your process, which seems like a smell to me in terms of your architecture design/tech debt with connascence of values against a system you're not using.

**Comment by louis** [comment]
We're prototyping :) Unfortunately the other system is Windows and has to be.

I think I'm still missing something though ... let's say the other system (system B) does in fact use Sidekiq and has the worker to process the queue.  How does the system that enqueues the message actually enqueue it without a worker?

**Comment by ryansch** [comment]
Generally the same codebase is used on both the client and server.  The worker is available on both sides.

**Comment by ryansch** [comment]
If you're going to continue down this path for your prototype, you should either create a worker class that you can `#perform_async` against or have a look at `Sidekiq::Client#push`.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L40
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L46-L63

**Comment by louis** [comment]
Gotcha, for us the Windows system will be processing that queue.  Thanks for the links and the time.  Client#push sounds like it might do the job.

**Comment by ryansch** [comment]
You can still create a worker class in your client as the logical endpoint.  You can call `#perform_async` against it and document the required parameters for reference.  The existence of the class will not cause sidekiq's server to work it off unless you actually run the server process.

**Comment by louis** [comment]
Oh cool, but in this case the sidekiq server process is running on the system that is doing the enqueueing.

**Comment by ryansch** [comment]
Gotcha.  You'd have to start playing with queues at that point.  Good luck with `Client#push`!

**Comment by louis** [comment]
Looks like it requires a worker class, which is what I was trying to avoid.  Is there a way to create the worker as a no-op which would leave the message in the queue?

**Comment by ryansch** [comment]
Easiest way is to set the queue for the worker to something unique and then configure the sidekiq server to not poll that queue for work.

**Comment by louis** [comment]
Nice!!  Thanks again guys.

**Comment by mperham** [comment]
Yep, Ryan's right, this is all you need:

```ruby
Sidekiq::Client.push('class' => 'SomeWorkerClass', 'args' => [...], 'queue' => "the_windows_queue")
```

Sidekiq won't process a queue unless you explicitly list it in `config/sidekiq.yml` or as a `-q` parameter.

**Comment by louis** [comment]
Worked great guys, much appreciated!
