### ISSUE TITLE
ActiveJob Redis namespace support

### ISSUE THREAD

**Issue by ScOut3R** [mperham/sidekiq#2123]
Hi,

I'm trying to integrate Sidekiq with ActiveJob and without defining Redis namepsace for Sidekiq everything is working fine. However when I set a namespace within Sidekiq the jobs are enqueued but not processed. I assume something is amiss between ActiveJob and Sidekiq. Does someone have a tip for me what to do?

Best regards,
Mate

**Comment by seuros** [comment]
That don't sound right.
can you show your sidekiq initializer ?

**Comment by ScOut3R** [comment]
Sure, but I have to warn you, I'm just coding for fun. ;) And don't let the 'memcached' hostname confure you. I'm currently running the development environment.

```
Sidekiq.configure_server do |config|
  if Rails.env.production?
    config.redis = { url: 'redis://memcached.jails', namespace: 'sidekiq:hrf-production' }
  elsif Rails.env.staging?
    config.redis = { url: 'redis://memcached.jails', namespace: 'sidekiq:hrf-staging' }
  else
    config.redis = { url: 'redis://localhost', namespace: 'sidekiq:hrf-development' }
  end
end
```

**Comment by seuros** [comment]
```ruby
if Rails.env.production?
    config_redis = { url: 'redis://memcached.jails', namespace: 'sidekiq:hrf-production' }
  elsif Rails.env.staging?
    config_redis = { url: 'redis://memcached.jails', namespace: 'sidekiq:hrf-staging' }
  else
    config_redis = { url: 'redis://localhost', namespace: 'sidekiq:hrf-development' }
end

Sidekiq.configure_server do |config|
  config.redis = config_redis
end

Sidekiq.configure_client do |config|
  config.redis = config_redis
end

**Comment by ScOut3R** [comment]
Ah, thank you very much! I just didn't pay enough attention to the documentation.
