### ISSUE TITLE
default_worker_options method doesn't use stringify_keys

### ISSUE THREAD

**Issue by ivovh** [mperham/sidekiq#2124]
When defining worker options in a worker, the [sidekiq_options](https://github.com/mperham/sidekiq/blob/27fc88504b15ea5b57929845c7118de66c3120ea/lib/sidekiq/worker.rb#L67) method uses `stringify_keys` to ensure the options all have strings as keys.

Unfortunately the [default_worker_options](https://github.com/mperham/sidekiq/blob/c4fc6dad68f14053af445a52e7e141c312ae6d13/lib/sidekiq.rb#L100) method doesn't stringify the keys. This can lead to conflicting options for a worker:

```ruby
pry(main)> EmailFetcherJob.get_sidekiq_options
=> {"retry"=>false, "queue"=>"default", :retry=>0, :backtrace=>true}
```

**Comment by mperham** [comment]
:+1: Seems like an easy PR. Anyone?

**Comment by seuros** [comment]
I will do it !
