### ISSUE TITLE
best practice for running configure_server block when testing?

### ISSUE THREAD

**Issue by jjb** [mperham/sidekiq#2128]
While working on https://github.com/rollbar/rollbar-gem/pull/197 I noticed that the [block passed to configure_server](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/sidekiq.rb#L22-L34) was not getting executed in my test environment.

This is because sidekiq only runs the configure_server block when in the server environment, which (lexically counterintuitively) [only happens when `Sidekiq::CLI` is defined](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L66-L68)

What's the best way to go about simulating this environment when writing a test? `require 'sidekiq/cli'`?

Here's what I'm working with so far:

```ruby
require 'spec_helper'
require 'sidekiq'
require 'rollbar/sidekiq'
require 'sidekiq/testing'

describe Rollbar::Sidekiq, :reconfigure_notifier => false do
  class FailingWorker
    include Sidekiq::Worker

    class TestException < Exception; end

    def perform
      fail(TestException, 'failing')
    end
  end

  let(:logger) { Rollbar.logger }

  before do
    Sidekiq::Testing.inline!
  end

  it 'sends the exception' do
    expect_any_instance_of(Rollbar::Notifier).to receive(:error).with(kind_of(FailingWorker::TestException))

    expect do
      FailingWorker.perform_async
    end.to raise_error(FailingWorker::TestException)
  end
end
```

**Comment by mperham** [comment]
Good question, Sidekiq's testing API does not try to reproduce the job execution environment exactly.  Notes:

1. configure_client and configure_server are mutually exclusive.  A Ruby environment will only execute one or the other.  As you note, my policy is that configure_server is only executed when a Sidekiq process actually boots.  Every other process, app server, test run, rake task, etc will execute configure_client.
2. The testing API does not execute middleware for each job execution.  This is impossible since job execution usually requires the middleware set up in configure_server, which isn't run due to (1).

Keep in mind that Sidekiq's testing API are simply helper methods.  There's nothing stopping you from rolling your own version that sets up the environment manually and executes a job.  Job execution is pretty simple at the core:

```ruby
def test_rollbar
  Sidekiq.server_middleware.add(RollbarMiddleware)
  worker = MyWorker.new
  msg = {'class' => 'MyWorker', 'args' => [], 'retry' => true}
  Sidekiq.server_middleware.invoke(worker, msg, 'default') do
    worker.perform(*msg['args'])
  end
end
```

**Comment by mperham** [comment]
Better yet, here's a simpler alternative for testing server middleware:

```ruby
def test_rollbar
  r = RollbarMiddleware.new
  assert_nil r.last_error
  assert_raises RuntimeError do
    r.call(nil, nil, nil) do
      raise "boom"
    end
  end
  refute_nil r.last_error
end
```

**Comment by jjb** [comment]
Great, thanks.

So I guess what's going on is: really I'm testing my middleware and not a worker or code that uses a worker, so the usual sidekiq testing helpers aren't directly relevant.

**Comment by mperham** [comment]
Indeed, well said.

**Comment by jjb** [comment]
I am going to ponder some contributions to the documentation, and also I'm going to be refactoring the rollbar code (including the post-3 initializer which doesn't use middleware). So if it's okay, let's keep this open until I'm done exploring the space.

**Comment by jjb** [comment]
Take a look at how the exception handler is attached here: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/sidekiq.rb#L28-L35

1. is this a good way to do it? (i didn't write this code and I'm not familiar with pre-3 vs. 3 error handling)
2. how would you go about testing this? (unless you recommend it not be done this way at all)

**Comment by mperham** [comment]
I would make that Proc a constant in your gem and then call it manually from your test.

```ruby
# in your gem code
SIDEKIQ_HANDLER = Proc.new(...)

# in your test
def test_handler
  SIDEKIQ_HANDLER.call(...)
end
```

**Comment by jjb** [comment]
Okay thanks, will explore that.

(in the refactoring it's going to be it's own method, so that may suffice)

**Comment by jjb** [comment]
in case anyone who finds this ticket in the future is interested, here are the incomplete tests I came up with: https://github.com/rollbar/rollbar-gem/commit/6047689038a8195e529b69adb05944e37c95c8d7
