### ISSUE TITLE
[OT] - Thank you

### ISSUE THREAD

**Issue by elcuervo** [mperham/sidekiq#2129]
TL;DR: This is an OT and useless issue.

I've been part of the Ruby community for a long time and dealing with workers was always a PITA until you took the time to build Sidekiq.

The work and love you gave to this project. You shook the market with the Pro license and thought everyone that you can build stuff the open way and live from it.

If I have the chance at some point I'd like to buy you a beer, a coffee or just give you a hug for all you've done for this community.

**Comment by ryansch** [comment]
:+1: :rainbow: :cake:

**Comment by mperham** [comment]
Thank you!

I accept any and all coffee donations but mostly I want happy devs to encourage their employers to upgrade to Pro.  I love making Sidekiq awesome and Pro sales allow me to do it full-time.
