### ISSUE TITLE
Sidekiq Pro 2.0 super-issue!

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2130]
This is an open issue to track Sidekiq Pro 2.0 work.  All discussion here is exploratory and not a guarantee.

## Batch data model

The current batch data model marshals a Hash to JSON for storage in redis.  Use Redis's native [Hash commands](http://redis.io/commands#hash) instead.

## Remove require activation

Several Pro features say `require 'sidekiq/pro/reliable_fetch'` to activate the feature.  Instead provide a real activation API so require and activation are not conflated, e.g.:

```ruby
Sidekiq::Client.reliable_push!

Sidekiq.configure_server do |config|
  config.reliable_fetch!
end
```

TODO

- [x] Upgrade batch data model to use redis hash commands, not a marshalled JSON hash
- [x] Switch Pro features which use `require` to instead use activation methods.
- [x] Remove deprecated APIs
- [x] Nested batches?  Take another stab at it.

**Comment by jonhyman** [comment]
:+1: to the activation API

**Comment by mperham** [comment]
Batch data model testing, so far so good:

```
Current:
~/src/sidekiq-pro/myapp (2_0)$ ruby -I../lib batch.rb
4.136284 sec
5000 batches took 6259 KB of memory with 20003 keys

2.0:
~/src/sidekiq-pro/myapp (2_0 *)$ ruby -I../lib batch.rb
4.214441 sec
5000 batches took 5008 KB of memory with 10003 keys
```

**Comment by mperham** [comment]
The Batch 2.0 data model will use BIDs based on SecureRandom.urlsafe_base64(10), rather than SecureRandom.hex(8).  It's a larger keyspace but smaller string (16 -> 14 chars). I can tell whether the associated batch is v1 or v2 format easily and it will fit into any existing data models which persist 16 char BIDs.

**Comment by mperham** [comment]
Latest, love it:

```
ruby -I../lib batch.rb
3.879737 sec
5000 batches took 4612 KB of memory with 10003 keys
```

**Comment by mperham** [comment]
Batches: 25% size reduction and a 10% speed up in creation speed.  :+1:

**Comment by jonhyman** [comment]
Sweet!

**Comment by mperham** [comment]
Upgrade notes so far: https://github.com/mperham/sidekiq/blob/master/Pro-2.0-Upgrade.md

**Comment by aprescott** [comment]
I love that batches are now set to expire after the maximum of 30 days. We've been setting it manually on any and every batch.

**Comment by mperham** [comment]
#1991 is in.

**Comment by aprescott** [comment]
I discovered a couple of oddities so far in testing Sidekiq Pro 2.0.0.beta1. One is that there's no Sidekiq Pro version shown in the web UI (using Sidekiq 3.3.0). Not sure if it just didn't make it into the beta1 release.

Another is a `Redis::CommandError` exception for `WRONGTYPE Operation against a key holding the wrong kind of value`. I don't know if this is actually related to any 2.0.0 changes to batches, but I came across this by:

1. Altering `FooJob#perform` to raise, on Sidekiq Pro < 2.0.
* Creating a batch through `FooBarBatchJob#perform`, for `FooJob` and `BarJob`.
* `FooJob` of courses errors out, interrupting the batch.
* Stop the `sidekiq` server.
* Change `FooJob` to no longer raise.
* Switch to Sidekiq Pro 2.0.0.beta1.
* Start the `sidekiq` server.

At some point in that process, the `Redis::Command` error was showing on the jobs retry page for 10 of the 10 `FooJob`. It looks like the jobs eventually retry and successfully finish, although 2 of the 10 seemed to need a manual retry.

```
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:129:in `value'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:121:in `_set'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:63:in `block in finish'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:62:in `each'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:62:in `each_with_index'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:62:in `each'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:62:in `map'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:62:in `finish'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/pipeline.rb:86:in `finish'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:146:in `block in call_pipeline'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:144:in `call_pipeline'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:2147:in `block in multi'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/adamprescott/.rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:2139:in `multi'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:413:in `namespaced_block'
/Users/adamprescott/.gem/ruby/2.2.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:258:in `multi'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-pro-2.0.0.beta1/lib/sidekiq/batch/middleware.rb:90:in `block in add_failure'
/Users/adamprescott/.gem/ruby/2.2.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58:in `with'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72:in `redis'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-pro-2.0.0.beta1/lib/sidekiq/batch/middleware.rb:89:in `add_failure'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-pro-2.0.0.beta1/lib/sidekiq/batch/middleware.rb:25:in `rescue in call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-pro-2.0.0.beta1/lib/sidekiq/batch/middleware.rb:21:in `call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/Users/adamprescott/.gem/ruby/2.2.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/Users/adamprescott/.gem/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by mperham** [comment]
@aprescott Good catch, fixing now.

**Comment by mperham** [comment]
1. Ok, `wrongtype` is fixed.
2. Oh, the product version requires Sidekiq master.  I need to release 3.3.1 soon with support for that.

I've gotten one other reported bug to fix today, beta2 will come out next week.

**Comment by aprescott** [comment]
:+1: I can smoke-test again when beta2 is released.

**Comment by mperham** [comment]
@aprescott beta2 is out.  I'm working on #2154 right now but your issues should be fixed.

**Comment by aprescott** [comment]
:+1: looks good!

**Comment by mperham** [comment]
Ok, anyone else who wants to test Sidekiq Pro 2, be sure to read the upgrade notes and add this to your Gemfile:

```
gem 'sidekiq-pro', '2.0.0.beta3'
```

I'll let things sit for a few weeks.  Look for a release in mid-Feb.

**Comment by mperham** [comment]
2.0.0.beta4 is out with the new reliable scheduler. https://github.com/mperham/sidekiq/blob/master/Pro-2.0-Upgrade.md#reliability Activate it with just a single line in configure_server.  Requires Redis 2.6+.

**Comment by mperham** [comment]
I plan on releasing Pro 2.0 next week unless anyone else finds a bug in beta4.  Now's the time to test on staging if you have a chance.

**Comment by mperham** [comment]
Done and shipped! http://www.mikeperham.com/2015/02/18/sidekiq-pro-2.0/

**Comment by jonhyman** [comment]
:clap: :exclamation:
