### ISSUE TITLE
Slow Redis Reads

### ISSUE THREAD

**Issue by samuelreh** [mperham/sidekiq#2131]
I have an issue, it's not with Sidekiq per se. This might not be the place for it, so let me know if I should post it elsewhere. 

Anyway, I'm intermittently getting really slow response reads from Redis. I wrapped redis-rb's @sock.write and @sock.read in NewRelid traces and here's what I'm getting:

![screen shot 2015-01-09 at 2 45 55 pm](https://cloud.githubusercontent.com/assets/128012/5689055/a5bfe168-9813-11e4-8b18-c9ffb86edc09.png)
Any ideas on why this might happen? Ever seen this happen?

I'm using Redis Cloud, Puma, Heroku. Pretty standard stack right?

I noticed sidekiq doesn't use the responses from Redis, maybe I could make a custom driver that doesn't bother to read redis responses (pretty hack though).

**Comment by mperham** [comment]
I've seen cloud latencies over 5000ms, especially on older instance types.  One minute your latency is 1000ms, the next minute it's 1ms.  No real way to debug because you don't have any visibility into the lower levels of the network, who else you're sharing the machine with, etc.

**Comment by samuelreh** [comment]
Thanks @mperham. Any insight into why it never seems to happen on the writes, just the reads?

**Comment by mperham** [comment]
Possibly a read (which typically instantiates new objects) is triggering a GC cycle.  Ruby 2.1+ doesn't usually have 500ms+ GCs any more but that's hard to know for sure.

**Comment by samuelreh** [comment]
I was originally thinking it was GC related, although NewRelic doesn't show any huge increase in GC time for these requests.

If I wanted to go down the path writing a workaround that writes to redis but doesn't read the responses (just for job creation), any advice?

**Comment by mperham** [comment]
No advice. Not sure the Redis client supports a quiet response mode.
