### ISSUE TITLE
ERROR: Error fetching message: Connection timed out

### ISSUE THREAD

**Issue by gingerlime** [mperham/sidekiq#2132]
Hi @mperham !

Thanks again for sidekiq. It's such an amazing tool.

I'm having a strange issue, and it's probably not a sidekiq problem, but I thought I'll double-check.

We're in the process of upgrading to Ruby 2.2, so I've set-up a new staging server and we've been running it for a couple of days. One odd thing that I noticed is that *occasionally* we're seeing these kinds of errors in our sidekiq log:

`2015-01-11T16:02:16.656Z 11444 TID-42mh0 ERROR: Error fetching message: Connection timed out`

followed by [this trace](https://gist.github.com/gingerlime/6561cc9b41eb55c50e9c), and then

`2015-01-11T16:02:18.881Z 11444 TID-42mh0 INFO: Redis is online, 2.223784923553467 sec downtime`

So it does look like an issue with our redis, but I see absolutely nothing in the redis logs, and the server stats also look pretty clean. CPU / IO seems idle. No other errors or anything that might suggest a problem.

#2003 mentioned a similar error, as well as one comment about seeing issues after upgrading ruby. However, in our case, sidekiq does not seem to be stuck.

Our redis is running on localhost, so I don't suspect any networking issues. It could be a platform / VPS issue, so I'm already in the process of setting up another VPS and trying to see if it produces similar errors. I just thought I'd post this here, in case someone else bumped into this or something similar and maybe we can "compare notes".

p.s. we're running redis 2.8.17 and sidekiq 3.3.0 / celluloid 0.16 on Ubuntu 14.04 64 bit

**Comment by mperham** [comment]
Make sure you aren't swapping. Use Redis's latency monitoring tools and slow log to see if there are any shenanigans going on.

**Comment by gingerlime** [comment]
Thanks for the tips. Can't see any swapping issues (machine has enough memory, and it's not busy), and slowlog doesn't seem to produce much (worst command I spotted was around 42ms). I've updated config to look at latency issues over 100ms in case those crop-up... I'll keep an eye on it and see if I can spot anything.

It's odd, because those errors appear in times where no jobs are executing, and I'm not aware of much activity on redis outside sidekiq either. This box is pretty quiet (just a staging server for testing). We do have the odd scheduled sidekiq job, but those execute fine... So I'm really confused what might cause this...

**Comment by mperham** [comment]
If you're in the cloud, multi-tenancy can lead to random pauses and performance degradation.

**Comment by gingerlime** [comment]
That's my prime suspect. I got another box spinning with the exact same setup on another provider and will keep an eye on things. I'm pretty sure it's nothing to do with sidekiq, but thought it's better to share this just in case... Thanks for the quick response and suggestions, @mperham. If you'd rather close this issue, then please do. Otherwise, I promise to keep you posted as soon as I find anything.

**Comment by gingerlime** [comment]
was running off a different vps for a while and no sign of those issues. Probably something to do with noisy neighbours. Sorry for the trouble and thanks for the tips and being patient with what clearly looks like a non-sidekiq issue.
