### ISSUE TITLE
Sidekiq segfaults

### ISSUE THREAD

**Issue by ngw** [mperham/sidekiq#2137]
Hi, my worker is segfaulting and I don't know which gem or what I'm doing wrong. AFAIK all I use is thread safe, but maybe I'm missing something:

Here is the backtrace:
https://gist.github.com/ngw/8eb963d3aa239fa1f152

Here is my gemset:
https://gist.github.com/ngw/6d31339c265d4d893187

Am I doing something wrong?

**Comment by mperham** [comment]
The problem is libcurl crashing the Ruby VM.  https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do
