### ISSUE TITLE
[Wiki] Using Redis - Namespace Warnings

### ISSUE THREAD

**Issue by cocoahero** [mperham/sidekiq#2140]
In the wiki under [Using Redis](https://github.com/mperham/sidekiq/wiki/Using-Redis#using-redis), it is recommended to utilize the shared Sidekiq.redis connection pool within workers.

However, an unmentioned caveat of this is if you utilize a key namespace (as described under [Advanced Options](https://github.com/mperham/sidekiq/wiki/Advanced-Options#namespaces)), this shared connection would also have this namespace applied. This may have undesired consequences when trying to separate Sidekiq and application specific redis keys using namespaces.

As an additional side comment regarding the wiki discussion on namespaces, would it also make sense to state that if you utilize a namespace for Sidekiq, you would need to set that same namespace in both `Sidekiq.configure_client` and `Sidekiq.configure_server` blocks?

**Comment by mperham** [comment]
That caveat seems obvious to me.  If you use the shared connection, it has all the properties of that shared connection.  :-)

Yep, you need the same namespace in each.  BTW, I'm not really a fan of namespaces personally.  I'd rather people use different databases within Redis for different purposes.

The wiki is publicly editable.  You are welcome to polish any text which isn't clear.
