### ISSUE TITLE
Configure default retries globally and customize retries for emails and AR

### ISSUE THREAD

**Issue by hakunin** [mperham/sidekiq#2146]
Hi,
I'd like to have all jobs fail much faster than with the default setting (21 days, right?).

Also would be great if email jobs failed after few retries and ActiveRecords with a set retries as well without monkey patching.

What do you guys think?

**Comment by mperham** [comment]
You mean you want them to die quicker?  The default retries policy is 25 retries then they die.  Just lower that number to 15 or 20 to get a much quicker job death.  I believe 15 retries takes about 1-2 days, 20 is more like a week.

```ruby
Sidekiq.default_worker_options = { retry: 20 }
```
