### ISSUE TITLE
Jobs failing when they're using ActiveRecord

### ISSUE THREAD

**Issue by kamsz** [mperham/sidekiq#2147]
Hi, when I submit a batch of jobs (10-15 jobs) they'll start to fail with an error:

could not obtain a database connection within 5.000 seconds

When I'll remove all references to the database (find and update methods) from the job they're working properly (without errors). I saw that this might be a bug in Rails 4.1, so I've upgraded to 4.2 without success.

Sidekiq version: 3.3.0
Rails version: 4.2.0
Sidekiq threads: 20
Database pool: 25
Database used: PostgreSQL

Any help will be appreciated.

**Comment by thiagogabriel** [comment]
Try to decrease Sidekiq threads and Database pool. Maybe 15 and 20.
