### ISSUE TITLE
stack level too deep errors

### ISSUE THREAD

**Issue by journalbits** [mperham/sidekiq#2148]
I've created a gist containing the full backtrace that I'm getting when I'm trying to run a worker.

Here's the gist: https://gist.github.com/hamchapman/8b3aff6c81236795a5a6

    class InstapaperWorker
      include Sidekiq::Worker
      sidekiq_options queue: "external_api"

      def perform date, user_id
        accounts = InstapaperAccount.where(user_id: user_id, activated: true)
        accounts.each do |account|
          client = create_client_for account
          save_bookmarks_created_on date, client, user_id, account.id
        end
      end

      def create_client_for account
        client = Instapaper::Client.new({
          consumer_key: ENV['INSTAPAPER_CONSUMER_KEY'],
          consumer_secret: ENV['INSTAPAPER_CONSUMER_SECRET'],
          oauth_token: account.oauth_token,
          oauth_token_secret: account.oauth_secret
        })
        client
      end

      def save_bookmarks_created_on date, client, user_id, account_id
        bookmarks = user_bookmarks_on date, client
        bookmarks.each do |bookmark|
          unless InstapaperEntry.exists?(bookmark_id: bookmark.bookmark_id.to_s)
            InstapaperEntry.create(
              user_id: user_id,
              date: date.to_s[0..9],
              bookmark_id: bookmark.bookmark_id.to_s,
              title: bookmark.title,
              url: bookmark.url,
              instapaper_account_id: account_id
            )
          end
        end
      end

      def user_bookmarks_on date, client
        bookmarks = client.bookmarks
        bookmarks.nil? ? [] : bookmarks.select { |bookmark| Time.at(bookmark.time).to_s[0..9] == date.to_s[0..9] }
      end
    end

And the worker is being called using `InstapaperWorker.perform_async(Time.now, 1)`

Judging by the number of times json appears in the backtrace I feel like that must have something to do with it. However, I can't for the life of me figure out where / why this is happening.

Any suggestions / ideas will be much appreciated!

**Comment by mperham** [comment]
This looks like the relevant part:

```
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/multi_json-1.10.1/lib/multi_json/adapters/json_common.rb:21:in `dump'
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:24:in `dump'
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/multi_json-1.10.1/lib/multi_json.rb:136:in `dump'
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/pusher-0.14.2/lib/pusher/client.rb:291:in `trigger_params'
23:38:21 worker.1 | /Users/Hami/.rvm/gems/ruby-2.2.0/gems/pusher-0.14.2/lib/pusher/client.rb:228:in `trigger'
23:38:21 worker.1 | /Users/Hami/Documents/Ruby/journal_bits/app/models/concerns/entry_pusher.rb:9:in `push_created'
```

Something in your pusher integration is failing to convert the data to JSON.

**Comment by journalbits** [comment]
Thanks, you were completely correct. I just added in oj to my gemfile and so multijson swapped to using that and the errors have all disappeared.
