### ISSUE TITLE
Cancel Batch via Middleware

### ISSUE THREAD

**Issue by ghempton** [mperham/sidekiq#2150]
Recently upgraded to pro and am benefitting immensely from the batches feature. The one pain point, however, is to make all jobs *batch-aware* so that they can be canceled (based on the [docs](https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch)).  This seems counter-intuitive to the batch api itself which just allows any `perform_async` call to be automatically added to the batch via thread locals.

Is there a reason why the `batch.valid?(jid)` check isn't handled by default at the middleware layer? Seems like a simple solution to make this functionality generic, but don't want to embark down this route if I am missing something obvious.

**Comment by mperham** [comment]
Yep, a call to `valid?` requires a round trip to Redis.  99% of Batch jobs don't need this overhead so you have to opt in by calling it manually in your jobs that are cancellable.

**Comment by mperham** [comment]
Glad to hear Pro is working great otherwise.  :+1:

**Comment by mperham** [comment]
Ack, I just realized that `batch.valid?(jid)` will require two round trips to Redis.  I'll fix this for 2.0 so it's a single round trip.
