### ISSUE TITLE
Sidekiq Pro Batching Problem

### ISSUE THREAD

**Issue by lsato** [mperham/sidekiq#2151]
So I have a couple of questions regarding sidekiq pro batching. 

We're using an older version of sidekiq (2.15.2) and sidekiq pro (1.2.4), and we are planning to upgrade this soon. 

In this older version we're using right now, we're getting a lot of batches that have 0 job count. I would understand this happening if the jobs were cleared or such, but we had not done anything with it. Within our code also, we're not creating a new Sidekiq::Batch unless there are multiple jobs that need to be processed.

Another question is if we are not using the notification function or such with batching, is there a benefit of using Sidekiq::Batch vs just kicking off jobs individually? 

Thank you and any knowledge on this is appreciated!

**Comment by mperham** [comment]
Yeah, that's pretty old.  You'll want to upgrade to 2.17.8 + Pro 1.5.1 and run that for a few weeks, then jump onto Sidekiq 3.  See the 3.0-Upgrade notes for details.

If you aren't using the Batch callbacks, there's no advantage to creating the jobs within a Batch.  Just kick them off individually.  As for the behavior you're seeing, I'd suggest upgrading.  I can't support versions that old with bugfixes so the easiest thing to do is upgrade and see if a newer version exhibits the same behavior.

**Comment by lsato** [comment]
That's perfectly understandable. Thanks for your help!
