### ISSUE TITLE
Setting queue at enqueue time

### ISSUE THREAD

**Issue by laserlemon** [mperham/sidekiq#2152]
I apologize if I'm unknowingly revisiting a past topic but this issue is hard to search for. :smiley:

I love the simplicity of mapping worker classes to a specific queue but it seems that there are not-so-unusual cases where one would want to override the queue or even other Sidekiq options at enqueue time. For example:

A video processing service has a `ProcessVideo` worker. Videos belonging to customers on the free plan are processed as part of the `"default"` queue. Videos belonging to customers on the *paid* plan are processed with the exact same worker/code but on a `"priority"` queue that takes precedence over the `"default"` queue.

The use case seems pretty reasonable so I'm sure people have done something like this. How would you recommend going about it? The option that comes to mind is subclassing the default worker to change only the Sidekiq options. And I can do that but it has the potential to get unruly or just plain impractical if I were to need to customize some combination of options including more than just the queue (i.e., retry, etc.).

Thank you!

**Comment by mperham** [comment]
This is definitely a documentation issue, where would you add it to the wiki?  You are looking for `Sidekiq::Client.push`:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L63

**Comment by laserlemon** [comment]
Thank you Mike, that's exactly what I'm looking for. :clap:

**Comment by jonhyman** [comment]
@mperham, what are your thoughts of an interface that's like this?

```ruby
Sidekiq.with_queue(:foo) do
  # Gets enqueued on the :foo queue
  MyJob.perform_async()
end
````

Could make this a bit easier for people to do things like update their code to dynamically use a different queue (e.g., high/med/low priority queues based on customer level). I'm happy to submit a pull if so.

**Comment by mperham** [comment]
IMO using S::C.push is simpler and more explicit.  Perhaps this is my recent Go work influencing my Ruby API design...

```ruby
Sidekiq::Client.push('class' => MyWorker, 'queue' => 'foo', 'args' => [])
```

**Comment by jonhyman** [comment]
Cool sounds good.

**Comment by RKushnir** [comment]
Also, you now have a higher-lever API `MyWorker.set(queue: 'foo').perform_async(1)`.
See https://github.com/mperham/sidekiq/commit/d6538b0b4f3c419ea969dc6710c6431b76a05d2b

It would be nice to have it in the wiki, I could only find it by reading the code. One might be hesitant whether it's public API if it's not documented.

**Comment by mperham** [comment]
You are welcome to add it to the wiki.

**Comment by zben** [comment]
The `set` API has a side effect that may or may not be problem depending on your usage. It will force all subsequent enqueuing of the same type of jobs in the same thread to share the same queue overwrite.

```ruby
class TestJob
  include Sidekiq::Worker
  sidekiq_options queue: :old_queue
end

TestJob.set(queue: :new_queue).perform_async(1) => queue used is 'new_queue'
TestJob.perform_async(1) => queue used is also 'new_queue'
```
If you never need to fall back to the default queue in the same thread, then this is not a problem. Otherwise, it might be.

@mperham, When you designed this feature, did you think forcing set() to only affect a single usage instead of all subsequent usages a bad thing or just too difficult to implement given the design?

**Comment by mperham** [comment]
I don't believe that was my intent for the API, to "infect" all further perform_async calls.  The idea was to implement the following pattern: `Worker.set(...).perform_async(...)`.

I think the right thing to do here is to adjust the semantics to match ActiveJob's semantics as closely as reasonably possible.  We can do this for the 5.0 release and call it a breaking, if hopefully minor, change.

**Comment by zben** [comment]
That makes sense! @mperham thanks for responding.

**Comment by RKushnir** [comment]
@zben When you call `perform_async` it should clear the settings(https://github.com/mperham/sidekiq/blob/a158fa2f7541247f5b7f9558d57277eea925d309/lib/sidekiq/worker.rb#L104).
The situation you described may happen if you call `set(...)` without following it with `perform_async`.

**Comment by RKushnir** [comment]
@mperham I added a short notice about `set` to the wiki https://github.com/mperham/sidekiq/wiki/Advanced-Options#workers

**Comment by zben** [comment]
@RKushnir the line of code you included didn't indicate perform_async clears the setting. Thread local variable is used for setting queue overwrite and keep using them.

I also don't think perform_async should necessarily be responsible for resetting things. I think the preferred idea is to have set() to affect only the current usage. That means set() cannot merely be a modifier that returns the same class object as before. It should instantiate some new object that is a wrapper around the original class and. This way won't be easy. I would read the active job code to see how they do it and get some idea from it.

**Comment by mperham** [comment]
^^^^ Fixed

**Comment by RKushnir** [comment]
@zben Sorry, accidentally clicked on the wrong line. `perform_async` calls `client_push` which clears the setting.

**Comment by RKushnir** [comment]
@mperham Nice! I was going to suggest:
```ruby
class OptionsProxy < SimpleDelegator
  def initialize(worker_class, options)
    super(worker_class)
    @options = options.stringify_keys
  end

  def client_push(item)
    __getobj__.client_push(@options.merge(item))
  end
end

module Sidekiq::Worker::ClassMethods
  def set(options)
    OptionsProxy.new(self, options)
  end
end
```

**Comment by zben** [comment]
@mperham you are unstoppable :)

**Comment by RKushnir** [comment]
Oh, but `Setter#perform_in` now duplicates logic from the `Worker.perform_in`.

**Comment by mperham** [comment]
@RKushnir Your impl looks nicer, you win!  If you want to send a PR, I'll happily accept your version.

**Comment by zben** [comment]
@RKushnir remember to add test if you are making a PR :) 👍

**Comment by RKushnir** [comment]
@mperham Now I see that it doesn't work with delegation 😄 But I'll try to make your version more DRY.

**Comment by zben** [comment]
@RKushnir why does it not work with delegation? I thought it should work.

**Comment by RKushnir** [comment]
@zben Delegator acts only between the object and the user, it cannot get inside the object. Once you have passed control to `perform_async`, you cannot make it use the overridden `client_push`.

I managed to get it working(and, as a side effect, it supports chained `set` calls), but now I'm not sure if it's good:
```ruby
      def set(options)
        klass = self
        Class.new(klass) do
          define_singleton_method :client_push do |item|
            super options.merge(item).merge!('class' => klass)
          end
        end
      end
```
@mperham what do you think?

**Comment by mperham** [comment]
Avoid runtime metaprogramming.  My version, while not DRY, is simpler to understand and faster.  It would be nice to support chained `set`s.

**Comment by Adamantish** [comment]
> You are welcome to add it to the wiki.
> […](#)
> On Mar 30, 2017, at 03:56, RKushnir ***@***.***> wrote: Also, you now have a higher-lever API MyWorker.set(queue: 'foo').perform_async(1). See [d6538b0](https://github.com/mperham/sidekiq/commit/d6538b0b4f3c419ea969dc6710c6431b76a05d2b) It would be nice to have it in the wiki, I could only find it by reading the code. One might be hesitant whether it's public API if it's not documented. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

For anybody reading this now, it's now here in the wiki: https://github.com/mperham/sidekiq/wiki/Advanced-Options#workers

**Comment by TeTiRoss** [comment]
Is it possible to get queue name inside running job in Sidekiq? I see from this thread that It is possible to set custom queue for particular job at enqueue time, but I couldn't find I way to check what exact queue is my job running under, while job execution time. 
I can do `self.sidekiq_options_hash` but it shows me the info that is defined inside the worker class, so the queue name will be same as defined there even if you run the job under other queue.

**Comment by mperham** [comment]
The only data available to a running job are the args. This is by design.

**Comment by wspurgin** [comment]
It's possible with custom middleware to "inject" it to the worker instance from the Sidekiq Server @TeTiRoss but there's nothing out of the box.

```ruby
class InjectRunningQueueStateMiddleware
  def call(worker_instance, msg, queue)
    worker_instance.running_queue = queue if worker_instance.respond_to?(:running_queue=)
    yield
  end
end

# ...
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    #...
    chain.add InjectRunningQueueStateMiddleware
  end
end

class MyWorker
  include Sidekiq::Worker

  attr_accessor :running_queue

  def perform
    logger.info "running_queue=#{running_queue}"
  end
end
```
