### ISSUE TITLE
Using redis pools without sidekiq namespace

### ISSUE THREAD

**Issue by guyisra** [mperham/sidekiq#2153]
I have a redis.rb with 
```
$redis = Redis.new( url:  "#{ENV['REDIS_URL']}")
```
which I use throughout the app

in sidekiq.rb I have
```
Sidekiq.configure_server do |config|
  config.redis = { :url => "#{ENV['REDISCLOUD_URL']}", :namespace => 'sidekiq'}
end

Sidekiq.configure_client do |config|
  config.redis = { :url => "#{ENV['REDISCLOUD_URL']}", :namespace => 'sidekiq' }
end
```
In workers when I use
```
Sidekiq.redis do |conn|
conn.sadd(...)
end
```
The result being that workers don't save to the same key due to the namespace

Is there a quick way I can refer to my redis keys or make sidekiq ignore the namespace inside the connection pool block? (I still want sidekiq to have its own namespace, just not namespace my keys)

**Comment by mperham** [comment]
Using $redis in Sidekiq is a very bad idea.  That's a single socket that will be a major source of contention.  Using your own connection pool to Redis.

https://github.com/mperham/connection_pool#usage

**Comment by guyisra** [comment]
I think you misunderstood me..

I am not using $redis inside sidekiq workers, and as you recommend, I want to use connection pools. 

The problem is with the namespace, since using the connection pool inconjunction with my redis keys will prefix them with the sidekiq namespace, which results in a different key from where my data is.

Is there  a way around this?

**Comment by mperham** [comment]
You have to use a separate connection pool. https://github.com/mperham/sidekiq/wiki/Advanced-Options#connection-pooling
