### ISSUE TITLE
Add new Lua-based scheduler?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2159]
The current scheduler pops jobs to be performed off the scheduled set and pushes them onto the queue.  This isn't atomic so a job can be lost and it means Sidekiq can only schedule jobs as fast as a single thread can pop/push them one at a time.

Can Sidekiq Pro offer a Lua-based scheduler loop to fix both these issues?

**Comment by jonhyman** [comment]
I think you could do this. You'd need to use `cjson.decode` to get the queue name (and also you'd want to do the `sadd` as well that `raw_push` does).

**Comment by mperham** [comment]
Ugh, the one intractable issue is that I can't execute client-side middleware when enqueuing the job.

**Comment by jonhyman** [comment]
D'oh!

**Comment by mperham** [comment]
Obviously I can make this opt-in so the user has to enable it.  It will break any unique jobs plugins that use middleware to guarantee queue uniqueness.

**Comment by mperham** [comment]
I've got it working now.  Pretty damn good numbers, even running on localhost.  These numbers scale linearly and over a network the difference will be even more dramatic:

```
# Enqueueing 1,000 scheduled jobs (sec)
Stock = 0.482193
Lua   = 0.007014
```

**Comment by ryansch** [comment]
I'm concerned by the warning in the lua code.  I've reached out to the redis cloud guys and they said that EVAL(SHA) against keys not listed in the invocation could be an issue on their platform as well.

https://twitter.com/RedisLabsInc/status/560939501942759426

**Comment by mperham** [comment]
I realized it's concern but I don't see any alternative.  The reliable scheduler is opt-in.  If you are using cluster, you can simply not activate it.

**Comment by ryansch** [comment]
Agreed. I just wanted to be clear about the Redis Cloud connection since they aren't technically Redis cluster.

**Comment by itamarhaber** [comment]
You could work both with the OS or our cluster by ensuring the same hashtag/regex mapping for generated keys

**Comment by mperham** [comment]
@itamarhaber Thanks for chiming in but I don't understand your comment.  This Lua operation might mutate any number of lists with keys like "queue:$NAME".  I assume that Redis Cluster will shard those lists across many different nodes, not the same node.

I don't know of any customers running Redis Cluster to be honest.  It's been "not production ready", under development for years now.  Is anyone actually running it?

**Comment by itamarhaber** [comment]
I admit possessing perhaps 0.1% knowledge of Sidekiq :smile: 

Based on my brief exchange with @ryansch and this thread, I proposed you ensure all relevant keys are on the same shard and in the same slot. The quickest way to do it is with a hashtag (e.g. `{sidekiq}queue:$NAME`) and have all keys sit in the same place. That, of course, may turn that slot red hot with activity so a better way of partitioning the queue and script may be called for, but I'm not too savvy on the requirements here.

Re. the use of Redis Cluster, you're actually one of the best sources for that info. It is possible, of course, that the intersect between Sidekiq users and Cluster is an empty set for any number of reasons. I am, however, hearing more and more about Redis cluster users and with yesterday's release of RC3, the Cluster is happening :smile_cat:
