### ISSUE TITLE
Rename Worker to Job

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2160]
Job is clearer and Rails has made the same choice.  Rename Sidekiq::Worker to Sidekiq::Job and everything that entails.

**Comment by aprescott** [comment]
@mperham does this also include not using `app/workers/` for Sidekiq-only, ActiveJob-incompatible classes, as per https://github.com/mperham/sidekiq/pull/1909#issuecomment-53081866?

**Comment by aprescott** [comment]
(I'm personally +1 on using "job" everywhere, and not "worker".)

**Comment by mperham** [comment]
It actually doesn't matter where people create their jobs/workers.  Anything under `app/` will work fine so I'd rather just tell people to put everything in `app/jobs`.  If they want to put everything in `app/sidekiq` or `app/workers`, that'll work too.

**Comment by jonhyman** [comment]
Totally in favor of this. :+1:

**Comment by vassilevsky** [comment]
This is a logical and semantically correct change. Do want.

**Comment by TiagoCardoso1983** [comment]
+1 . One could still refer to Sidekiq::Worker though, and this would point to Sidekiq::Job, backwards compatibility.

**Comment by mperham** [comment]
In retrospect I think it's better to keep Sidekiq's terminology distinct from ActiveJob.  ActiveJob owns "Job", Sidekiq owns "Worker".  Makes it easier to talk about the AJ API vs Sidekiq's native API.  WDYT?

**Comment by vassilevsky** [comment]
I remembered that yesterday at work we thought it was a cool idea to rename Sidekiq to Steve. Then we'll refer to jobs as Steve Jobs.

**Comment by epipheus** [comment]
Personally, I prefer app/ninjas

**Comment by vassilevsky** [comment]
What's the main method name then?

**Comment by epipheus** [comment]
Not sure what you mean by main method.  But I name all my workers "ninja"... it also fits really well with the sidekiq theme. Ninja's kick or ...umm kiq.  I just finished writing a LinodeNinja to concurrently adjust my ZenCash masternodes. Ninja feels just right :)
