### ISSUE TITLE
how to run a selected set of workers in development?

### ISSUE THREAD

**Issue by brettskiii** [mperham/sidekiq#2166]
So in development maybe I want to spin up 1 or 2 workers that I'm currently coding.. Is there a way to do this without spinning up all my workers?

My workers are scheduled through sidetiq so they recur every 15 secs..

**Comment by mperham** [comment]
Sidekiq executes what you enqueue.  There's no way around this.

That said, you should TDD your workers.  They are designed to make TDD super easy: you instantiate and call perform.
