### ISSUE TITLE
ActiveJob and Sidekiq: logging issue

### ISSUE THREAD

**Issue by timobleeker** [mperham/sidekiq#2167]
Since using ActiveJob with Sidekiq as an adapter, the worker's log no longer prints out the name of the job class, but instead prints `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` for each job.

I'm not sure if there is a config setting I'm missing or if this is broken.

activejob (4.2.0)
sidekiq (3.3.1)

**Comment by mperham** [comment]
There's no config setting, this is a limitation of using ActiveJob instead of Sidekiq's native API.

**Comment by timobleeker** [comment]
Ok. However I just realised that on my staging env (above example was local), the jobs do have a meaningful log:
`[ActiveJob] [FooJob] [b9d99be6-8aad-4f82-bf62-ccce583c43ac] Performing FooJob from Sidekiq(default) with arguments: 'foo'`
Anyway it seems more likely that this is an issue or config in ActiveJob then and not with Sidekiq.
