### ISSUE TITLE
Client middleware chain completely returns unexpectedly before actual push to Redis

### ISSUE THREAD

**Issue by vassilevsky** [mperham/sidekiq#2172]
This was something totally unexpected.

Documentation in code says that Sidekiq middleware works like Rack middleware. If that is true, actual push to Redis should be happening in the middle of the chain (it should be in the `&final_action` block). This way middleware classes will be able to do something only if the actual push succeeds.

We wrote a tiny middleware class that [we thought] logs JIDs of enqueued jobs. It does so *after* `yield`ing so we thought we were fine — no logs will be written if the client does not push to Redis.

Recently I was debugging non-working jobs. I looked in the log and it said that jobs had been enqueued. So I was debugging the server processing part. No results. It was only when I ran a `perform_async` call with a debugger that I discovered this little peculiarity.

Now of course I read the documentation in the wiki and see that it does say about that :) But this is unexpected.

Why this invokation order was implemented? Does something prevent an implementation where Redis push is at the heart of the middleware chain?

**Comment by mperham** [comment]
Because otherwise you can't push jobs in bulk using `Sidekiq::Client.push_bulk` with the same semantics.  Your assumption also breaks with Sidekiq Pro's reliable push where it can return JIDs that have not been pushed to Redis yet due to transient network issues.

**Comment by mperham** [comment]
I'd welcome an rdoc patch which clarifies the semantics.
