### ISSUE TITLE
Sidekiq::Stats.new queues is missing

### ISSUE THREAD

**Issue by andywenk** [mperham/sidekiq#2174]
Hi,

I have an issue with 3.3.1. Following is the output from the Rails console:

     2.2.0 :001 > stats = Sidekiq::Stats.new
     => #<Sidekiq::Stats:0x0000000a960b40 @stats={:processed=>10918, :failed=>123,  
    :scheduled_size=>0, :retry_size=>0, :dead_size=>0, :processes_size=>2, :default_queue_latency=>0,   
    :workers_size=>0, :enqueued=>0}>
    :003 > stats.queues
    NoMethodError: undefined method `queues' for #<Sidekiq::Stats:0x007feb83196740>

Am I missing something? I read https://github.com/mperham/sidekiq/blob/master/Changes.md#331 and I don't see that anything has changed here. 

Thanks for any info and help

Cheers

Andy

**Comment by mperham** [comment]
#queues was inadvertently removed from 3.3.1 and is back on master, waiting for a 3.3.2 release.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L47

**Comment by andywenk** [comment]
thanks for the super fast info Mike! Awesome ;-)
