### ISSUE TITLE
Retries exhausted could receive the exception object

### ISSUE THREAD

**Issue by jondeandres** [mperham/sidekiq#2181]
It'd be nice if the `msg` that is passed to `retries_exhausted` had the exception object, https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/retry_jobs.rb#L133.

It can be interesting for gems like [Rollbar](http://github.com/rollbar/rollbar-gem) where the public interface expects an exception object.

```ruby
msg['exception'] = exception
```

This should be enough.

**Comment by mperham** [comment]
Sorry, I'm no longer accepting functional changes to the retry system.

https://github.com/mperham/sidekiq/wiki/Error-Handling#no-more-bike-shedding
