### ISSUE TITLE
Bug in the Reporting of the current job duration.

### ISSUE THREAD

**Issue by timuckun** [mperham/sidekiq#2184]
There seems to be some sort of a race condition in the sidekiq reporting screen.  

Here is the scenario.

I have a job which is being scheduled with sidetiq.  This job is scheduled to run every 10 minutes. Sometimes the job takes longer than 10 minutes to run, when that happens the scheduled job goes into the queue and is run as soon as the first job is over.   The reporting screen then will continue to increment the time showing that the combined time for the two jobs.  This can go on for a long time showing a duration of hours in some cases when in actuality the actual jobs are running in minutes.

On a related note.  Is there a way for sidekiq to report the actual number of minutes and seconds instead of vague "about an hour" type of statements?

Thanks.

**Comment by mperham** [comment]
Sidetiq is not supported by Sidekiq.  Please ask in that repo.
