### ISSUE TITLE
no assets & user gets signed out when access sidekiq page in production

### ISSUE THREAD

**Issue by pkmishra** [mperham/sidekiq#2185]
I am using sidekiq 3.2.6 with Ruby 2.1 and Rails 4.1. Everything works fine locally but on production when I try to access sidekiq page, It gives me page without css/js and logs the user out. Not sure what's going on. I am also getting follow error in chrome console...
```
Refused to execute script from 'http://www.www.io/admin/sidekiq/jobs/javascripts/application.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
jobs:1 Refused to execute script from 'http://www.www.io/admin/sidekiq/jobs/javascripts/locales/jquery.timeago.en.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
jobs:1 Refused to execute script from 'http://www.www.io/admin/sidekiq/jobs/javascripts/dashboard.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

Further I am mounting sidekiq in rails application in routes.rb using following code
```
if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end
```
I am using setting as config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' for nginx. For rails using unicorn. Also using cloudflare.

Let me know if anyone could help.

**Comment by pkmishra** [comment]
Alright so pausing cloudflare brings everything to normal. When cloudflare is enabled for assets getting 302 redirect to login page, only for sidekiq web UI.

**Comment by maran** [comment]
Sorry for the necro but @pkmishra did you find a way to work around this?

**Comment by pkmishra** [comment]
Not really. I had to create different server end point with disabled cloudflare.

**Comment by codeodor** [comment]
I have this same issue, but it is happening in development mode, with no cloudflare. Any ideas of things I could try?

**Comment by rylanb** [comment]
I think https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden will help you @codeodor ? 

I ended up just switching to: 

    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
         ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
         ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
    end if Rails.env.production? 

from https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes.

The 'Rack session and protection against web attacks' will give you more insight into what is likely happening. Session isn't being passed properly to Sidekiq and logging you out. I had issues trying with ActiveAdmin / Devise login.

**Comment by codeodor** [comment]
Thanks @rylanb. I'll give it a shot when I've got a moment to make the switch again.
