### ISSUE TITLE
Undeprecate ActionMailer.delay

### ISSUE THREAD

**Issue by karlingen** [mperham/sidekiq#2186]
How can I pass the parameter `retry: false` to the deliver_later method as I could before ActiveJob was implemented in rails?

Before:
```
UserMailer.delay(retry: false).welcome(@user)
```

After:
```
UserMailer.welcome(@user).deliver_later
```

`deliver_later` does not seem to accept `retry: false`. I do not want it to keep retrying if the mail sending fails.

Any ideas?

**Comment by mperham** [comment]
Unfortunately you cannot.  This is a limitation of Active Job.

https://github.com/mperham/sidekiq/wiki/Active-Job#limitations

**Comment by karlingen** [comment]
@mperham what are my options here then? 
Should I keep on using the deprecated `.deliver(retry: false)` option until this is fixed?

**Comment by mperham** [comment]
That's a good point, we deprecated `delay` with 4.2 but it doesn't offer full backwards compat.

@seuros It seems like we need to "undeprecate" the ActionMailer delay.  WDYT?

**Comment by karlingen** [comment]
Seems to be an open discussion here regarding allow passing options to underlying library: https://groups.google.com/forum/#!topic/rubyonrails-core/r_incU_gtcw

**Comment by seuros** [comment]
"Undeprecating"  will print deprecation messages unless we silence them and won't work in Rails 5. 
I'm going to look if we can fix that somehow.

**Comment by karlingen** [comment]
@seuros thanks for taking the time to sort this one out!

**Comment by karlingen** [comment]
@mperham can we not keep this issue open?

**Comment by karlingen** [comment]
@seuros anything new regarding this issue?

**Comment by mperham** [comment]
I'll take care of this now.
