### ISSUE TITLE
Is there any difference between sidekiq as a daemon or not?

### ISSUE THREAD

**Issue by flyingdev** [mperham/sidekiq#2190]
Hello, Mike
I love to work with sidekiq, and have one question.

Is there any difference between
 bundle exec sidekiq 
and
 bundle exec sidekiq -d -L sidekiq.log
?

**Comment by mperham** [comment]
The first runs in the foreground, the latter does not.

I do not recommend using daemon mode.  Modern Unix daemons should be run with a process manager (Upstart, Systemd, etc) which handles everything for you.

http://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/

**Comment by flyingdev** [comment]
Very thanks.
:+1:
