### ISSUE TITLE
Number of Redis connections increases as I refresh web UI

### ISSUE THREAD

**Issue by anujbiyani** [mperham/sidekiq#2195]
I have a local server with sidekiq's web UI running. On the first page load, it reports 5 connections to Redis. Redis `client list` shows the cmds client, smembers, and info (client is my command-line connection):
```
id=279 addr=127.0.0.1:53755 fd=5 name= age=2419 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
id=526 addr=127.0.0.1:58935 fd=6 name= age=14 idle=14 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=smembers
[...]
id=527 addr=127.0.0.1:58937 fd=7 name= age=14 idle=14 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info
```

If I refresh it, the number of connections jumps by 3 and redis `client list` reports 3 more entries with `cmd=smembers`. If you ignore old connections getting cleaned up, then it seems like every refresh increases the number by 3.

Why does the number of connections increase with each refresh? Shouldn't old connections simply be reused?

**Comment by mperham** [comment]
I don't know the answers to these questions. I'll try to reproduce the issue tomorrow.

**Comment by mperham** [comment]
Running locally in WEBrick, everything works as expected here.  I max out at 4 connections: 1 for `client list`, 2 for Sidekiq's internals and 1 for the Web UI.

**Comment by ciihla** [comment]
Same issue on my side:
Running on Puma(1 worker)
configuration: 
````
Sidekiq.configure_client do |config|
  config.redis = { namespace: 'sidekiq-worker', size: ENV['SIDEKIQ_CLIENT_SIZE'] || 1 }
end

Sidekiq.configure_server do |config|
  config.redis = { namespace: 'sidekiq-worker', size: ENV['SIDEKIQ_SERVER_SIZE'] || 4 }
end

# sidekiq.yml
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
````

Also using redis_objects gem for counters (if this is relevant):
````
Redis.current = ConnectionPool.new(size: 2) { ... }
Redis::Objects.redis = Redis.current
````

Any help is appreciate!

**Comment by ciihla** [comment]
UPDATE:
It seems that in version 3.3.0 the number of connections increments by +1 after each page refresh(CTRL+R with cca 1sec delay) on the dashboard (you can watch it in the connections box in the bottom).

In version 3.3.2 the number increments by +3 after each refresh.

**Comment by mperham** [comment]
You can try redis 3.2.1 + connection_pool master and see if the behavior improves.

**Comment by ciihla** [comment]
Thanks a lot! That really fixed the issue!
