### ISSUE TITLE
High CPU usage when there is no worker working... 

### ISSUE THREAD

**Issue by sahin** [mperham/sidekiq#2196]
![sidekiq](https://cloud.githubusercontent.com/assets/2508980/6262185/11c85098-b7b3-11e4-96f9-688936655ce2.png)

@mperham , I start to see this scene a lot. There is [0 of X] but there is high CPU usage and in UI there is no worker. The workers are not stuck either meaning they are accepting new jobs if come. 

We have around 20 small worker apps distributed in multiple server. 

We are in ruby 2.2.0, latest version of sidekiq 

Any ideas how can we find the high CPU usage?

**Comment by mperham** [comment]
Show me your initializer.  You can strace the processes and see if they are making tons of system calls.  That could give you a hint as to why the CPU usage is so high.

**Comment by justicel** [comment]
I'm wondering if there's a ruby 2.2.0 issue with sidekiq. We upgraded to 2.2 and are seeing random issues like this and extraordinary memory usage on random servers. Still trying to track it down but I'm going to try disabling 2.2 tomorrow to see if things work as expected again on 2.1.x

**Comment by sahin** [comment]
@mperham 
````
require 'sidetiq'

Sidekiq.configure_client do |config|
  config.redis = SETTINGS.redis.sidekiq.to_hash
end

Sidekiq.configure_server do |config|
  config.redis = SETTINGS.redis.sidekiq.to_hash
  config.poll_interval = 1
end

class CustomSidekiqLogger < Logger::Formatter
  # Provide a call() method that returns the formatted message.
  def call(severity, time, program_name, message)
    "#{context} #{severity}: #{time.utc.iso8601(3)} #{::Process.pid} TID-#{Thread.current.object_id.to_s(36)} #{message}\n"
  end
end


Sidekiq::Logging.logger = Le.new('cfc0575c-8c20-48d1-9f94-a169f39dfe6c')
Sidekiq::Logging.logger.level = Logger::DEBUG
# Sidekiq.logger.formatter = CustomSidekiqLogger.new

# "#{time.utc.iso8601} #{Process.pid} TID-#{Thread.current.object_id.to_s(36)}#{context} #{severity}: #{message}\n"


if defined? Sidekiq::Failures
  Sidekiq.configure_server do |config|
    config.failures_max_count = false
    config.failures_default_mode = :exhausted
  end
end


module Sidekiq
  module ExceptionHandler
    def handle_exception(ex, context={})
      Bugsnag.notify_or_ignore(ex, :parameters => context)
    end
  end
end


Sidekiq.remove_delay!

#end

````

**Comment by mperham** [comment]
You can remove your ExceptionHandler hack, the latest version of the bugsnag gem does this automatically for you.  Show me your queue configuration.

Also note sidetiq and ice_cube can result in terrible CPU usage: https://github.com/tobiassvn/sidetiq/issues/31#issuecomment-27934016  Make sure you are using the latest version of those gems and you read that issue.

**Comment by sahin** [comment]
removed ExceptionHandler
I did the sidetiq config. ( I hate to use extensions :) ), (I wish we can scheduler in sidekiq or in pro version. )

let me close the issue, if we got the same thing about CPU usage, I will reopen this issue.

**Comment by mperham** [comment]
@sahin In case you haven't seen it, my recommendations for recurring jobs: https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs#recurring-jobs

**Comment by sahin** [comment]
I know this very well. Even had a yml and load in the init.

recurring-jobs is very minimalist and good enough.

but I feel sidetiq way of doing recurring is more sidekiq way :) like below, u create a class with perform , sidetiq has a UI ( which is a plus)

````
class AutoConnectionPublishScheduler
  include SidekiqScheduler

  sidekiq_options queue: queue_name(:social_posting_user_action), retry: 2

  recurrence { daily(1) }

  def perform

  end

end
````

**Comment by exAspArk** [comment]
Bumping version of `ice_cube` (for `sidetiq`) to `0.11.3` really helped us
