### ISSUE TITLE
Confuse about how Sidekiq process work on a dedicated server

### ISSUE THREAD

**Issue by nicolas-besnard** [mperham/sidekiq#2197]
I'm new on Sidekiq, and I'm really confuse on how thinks work. I'm doing my test on my local machine : so far everything is ok.

Now, I plan to make my app available on the Internet. For this, I would like to dedicated a server (or a VPS) to the Sidekiq worker. My question is : How the worker know which method to call if they aren't on the same server as my Rails app ? Is there any tutorial to do that ?

[Here's what I want to do](http://i.imgur.com/xorOXf7.png)

Sorry if this is not the right place to ask.

**Comment by seuros** [comment]
The worker should be run within the rails app code. 

Basically, the VPS will have all the code of the rails app.

**Comment by nicolas-besnard** [comment]
Will it work if I just copy-paste my rails-app on the worker server ? Or the rails-app need to be running ?

**Comment by johnathanludwig** [comment]
The web server does not need to be running. You do need to have gems and any other dependencies installed though. You just copy the code to the server, install what's needed for the app to run, and then run `sidekiq`.

**Comment by seuros** [comment]
@nicolas-besnard , yes. You just need the workers class and their dependencies.

**Comment by nicolas-besnard** [comment]
Thanks to both of you !
