### ISSUE TITLE
Bundler Changes

### ISSUE THREAD

**Issue by veverkap** [mperham/sidekiq#2199]
Bundler is changing the way that it handles multiple sources in a Gemfile.  

From http://bundler.io/v1.7/whats_new.html#version17:

```
Bundler has always supported fetching gems from multiple gem servers, but it isn't always clear what gems come from what source. Complicating this, Bundler has not been consistent about source priority ordering from one version to another.

Because of this, a Gemfile with multiple top-level source lines cannot reliably control the gem server that a particular gem is fetched from. This might result in installation of gem code from an unexpected source.

Applications that only have a single source in their Gemfile are not affected.
```

It is requiring a "source" block to make sure that sidekiq-pro is coming from contribsys.

So we need to change from this:

```
source "https://rubygems.org"
source "https://user:pass@gems.contribsys.com/"
gem "mysql2"
<snip>
gem "sidekiq-pro"
```
 to this

```
source "https://rubygems.org"
gem "mysql2"
<snip>

source "https://user:pass@gems.contribsys.com/" do
  gem "sidekiq-pro"
end
```

However, when we do that, any calls to bundle exec ... give:

```
Could not find gem 'sidekiq-pro (>= 0) ruby' in rubygems repository https://user:pass@gems.contribsys.com/.
Source does not contain any versions of 'sidekiq-pro (>= 0) ruby'
Run `bundle install` to install missing gems.
```

**Comment by seuros** [comment]
You have bundler 1.8 ? is yes, downgrade to 1.7.2+

**Comment by veverkap** [comment]
@seuros I appreciate your response.  We are using bundler 1.8.2.  When running with the previous Gemfile, we would get a notice that having multiple sources is a problem.

**Comment by seuros** [comment]
I think it a bug with bundler, i had similar bug this week .
I had to downgrade to fix it.

**Comment by mperham** [comment]
All new customers are already getting updated info to use the `source` block form with Bundler 1.7.12+.  I figured existing customers would learn about it naturally.  Bundler has stated that the old way will continue to work for Bundler 1.x which is why I haven't mailed my customer list about it.

If it's not working in 1.8, that's a Bundler bug.

**Comment by veverkap** [comment]
Okay, thanks @seuros!

And @mperham do you have any docs for existing customers that you can point me at?

Thanks!

**Comment by mperham** [comment]
@veverkap I don't but I can write up something in the wiki since I'm sure it will come up repeatedly over the next few years.

**Comment by veverkap** [comment]
Thanks!

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Pro-Installation

**Comment by veverkap** [comment]
What's interesting is that the only difference between the two in the Gemfile.lock is that one has an exclamation point and the other doesn't.

![screen shot 2015-02-20 at 5 54 49 pm](https://cloud.githubusercontent.com/assets/22348/6310920/c175b7fc-b929-11e4-9911-883056ed53a2.png)

**Comment by mperham** [comment]
The bang usually indicates you are using a local git copy.

**Comment by veverkap** [comment]
Okay, thanks.  We're following some tickets on bundler.

https://github.com/bundler/bundler/issues/3175

**Comment by TimMoore** [comment]
@veverkap can you try it out with Bundler 1.7.13?

I think this is a bug that was introduced in Bundler 1.8. There's a pending fix at #3427.

**Comment by veverkap** [comment]
@TimMoore we are good if we use 1.7.13.  I see your changes were merged, so I'll have to test that as well.

**Comment by TimMoore** [comment]
This should be fixed in Bundler 1.8.3 (released today).

**Comment by veverkap** [comment]
Thanks @TimMoore!

**Comment by mattvanhorn** [comment]
Not fixed in 1.8.3, at least for me. 1.7.13 works, though.

**Comment by TimMoore** [comment]
@veverkap / @mattvanhorn would you be able to test out a fix?

https://github.com/TimMoore/bundler/tree/revert-local-rubygems

Clone that repo, check out the `revert-local-rubygems` branch, then run `rake install` to install the patched version.

**Comment by mattvanhorn** [comment]
That did seem to work for me, thanks!

**Comment by aprescott** [comment]
@TimMoore @veverkap were your comments about the `!` in `sidekiq-pro!`? I'm trying to switch to using the block form of `source` and it seems that I cannot, on Bundler 1.8.3 and 1.8.4, avoid a `!` showing up in my Gemfile.lock after I change to using the block form of source.

Is this a known problem? Should I create an issue with Bundler?

**Comment by TimMoore** [comment]
Bundler 1.8.4 has been released with this fix.

**Comment by aprescott** [comment]
@TimMoore the one I described? I had that same issue on both 1.8.3 and 1.8.4. It seems that 1.8.5 was just released today, too, and has the same problem: all gems referenced via a `source` block end up in `Gemfile.lock` with a `!`, even though they're not referring to local gems.

**Comment by aprescott** [comment]
In case anyone finds this in future...

Thanks to a coworker, it turns out that the `!` means something other than just "this gem comes from a local copy": https://github.com/bundler/bundler/blob/cab48fb8273108eb95d5b4332bdb9ad21a6524fb/lib/bundler/lockfile_parser.rb#L106-L134

So the `sidekiq-pro!` (with `!`) when using a `source` block is to be expected.
