### ISSUE TITLE
Can't Click Buttons when Redis domain name to long

### ISSUE THREAD

**Issue by newdark** [mperham/sidekiq#2204]
You can't click the buttons at the bottom when the domain name for the redis domain name is to long. We have this problem came up using services like object rocket.  

![screen shot 2015-02-26 at 10 28 05 pm](https://cloud.githubusercontent.com/assets/13140/6407496/f69bb1fc-be06-11e4-93b6-1bdb2aacb2f2.png)

**Comment by mperham** [comment]
Can you set up a CNAME for the hostname to something shorter?

**Comment by mperham** [comment]
The bug here is that the black footer CSS should not block the content.  You should be able to scroll down to reveal the button, even with a terribly long hostname.

**Comment by newdark** [comment]
Sadly no I can't because the padding bottom is set to 60px and wll not handle this much larger footer

![screen shot 2015-02-26 at 11 55 10 pm](https://cloud.githubusercontent.com/assets/13140/6408092/018f508a-be13-11e4-929b-b19427c8c0f6.png)

This image shows the green is the padding bottom and the blue is the content. It is not much but it changes usability of the tool. 

As for setting up a CNAME we are trying to do that, however the time it takes to get that done is almost not worth it considering it is simpler delete the text that is causing the problem. I think your right the redis domain name is to long and that is are problem however it is a bit out of my control considering the domain names are handle by object rocket and the networking team, but I will keep pushing on my side to get this fixed.

**Comment by mperham** [comment]
I'd need a CSS pro to tell me the right way to fix that. Web front end is not my area.

**Comment by seuros** [comment]
I will fix it.

**Comment by seuros** [comment]
@newdark can you try #2205 ?
