### ISSUE TITLE
Wrong RAILS_ENV value

### ISSUE THREAD

**Issue by jcarlson** [mperham/sidekiq#2206]
I'm going crazy here. I have a worker that `puts Rails.env` when processed. 

When I run `bundle exec sidekiq` from within my project, the workers correctly output `"development"`. When I run `sidekiq` (no bundle exec), the workers output `"test"`.

I can't figure out why the workers are starting in the test environment outside of `bundle exec`. Is it something Sidekiq is doing? Something in my project that I'm not aware of?

**Comment by mperham** [comment]
I don't know why you are seeing this.

You should always use Bundler.  Without Bundler, you don't have stable gem dependencies.

**Comment by jcarlson** [comment]
@mperham We have a couple folks on our team seeing this behavior. I use Bundler bin stubs in my project, so `sidekiq` should be the same as `bundle exec sidekiq`... right? Any further thoughts?

**Comment by mperham** [comment]
No further thoughts except that it is a terminal/bundler/bash config issue, perhaps due to a .rvmrc file or something like that.

**Comment by jcarlson** [comment]
@mperham I found the culprit! We had this gem installed in our project: https://github.com/johnvoloski/spring-commands-sidekiq

For whatever reason, that gem defaults to the `test` environment when starting through Spring. Nuked that gem, all is well.
