### ISSUE TITLE
`delay` doesn't execute `where` scope !

### ISSUE THREAD

**Issue by zakwanhaj** [mperham/sidekiq#2211]
Why do the following query delete everything in friends table??
`Friend.where(user_id: 34565).delay.delete_all`

When I execute the query without `delay`, it works properly. But, It seems that `delay` method doesn't see `where` scope: `where(user_id: 34565)` !

Do I use it incorrectly or Is it a bug?

**Comment by mperham** [comment]
Neither.  There's way too much Ruby/Rails magic happening under the covers for delay to handle that use case.  You'd be better off creating an explicit Worker for it:

```
class FriendDeleter
  include Sidekiq::Worker
  def perform(user_id)
    Friend.where(user_id: user_id).delete_all
  end
end
```
