### ISSUE TITLE
Wrong order while iterating Sidekiq::ScheduledSet

### ISSUE THREAD

**Issue by fabn** [mperham/sidekiq#2212]
I'm playing with sidekiq api and I'm trying to inspect scheduled jobs through `::Sidekiq::ScheduledSet` iterator. I found that it's returning jobs in the wrong order, isn't it supposed to return jobs in execution order? Here's a failing spec:

```ruby
  describe ::Sidekiq::ScheduledSet do

    it 'should return items ordered' do
      ::Sidekiq::ScheduledSet.new.each_cons(2) do |j1, j2|
        expect(j1.at).to be <= j2.at
      end
    end

  end
```

I run a debugger and stopped the execution at first iteration of [each method](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L486) just before the `zrange` call and I see that range variables get wrong values (green values are from debugger)

![first iteration](https://cloud.githubusercontent.com/assets/324213/6463893/9d5438cc-c1b6-11e4-8ee0-162b81bc0244.png)

**Comment by mperham** [comment]
I don't believe the scheduled set API makes any guarantee about the order in which it traverses.

**Comment by mperham** [comment]
It iterates in reverse so to minimize conflicts with Sidekiq processes pulling elements off the zset in real-time.

**Comment by fabn** [comment]
I think that some order guarantee would be great to improve some code (e.g. fetch the next 10 jobs could become `::Sidekiq::ScheduledSet.new.take(10)` or all jobs before a given timestamp `::Sidekiq::ScheduledSet.new.take_while { |j| j.at < my_time }`). Without it one needs to walk the whole queue or use other (I guess semi-private) [methods](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/paginator.rb)

In any case you can close this if it's a non issue and that behavior was intentional.
