### ISSUE TITLE
Testing delay method

### ISSUE THREAD

**Issue by Olgagr** [mperham/sidekiq#2218]
I have an issue when I try to test delay method. Code I'm testing looks like this:

```
def save
    if valid?
        UserMailer.delay.share(from, email, to, message)			
        true
    else
        false
    end
end
```

And the spec:

```
it "sends email" do
    expect {
        ShareForm.new(email: 'test@test.com', from: 'John', to: 'test2@test.com', message: 'some message').save
     }.to change(Sidekiq::Extensions::DelayedMailer.jobs, :size).by(1) 
end
```

In my rails_helper.rb file I have:
require 'sidekiq/testing'

When I run this test:
rspec spec/models/share_form_spec.rb

I got an error that Sidekiq::Extensions::DelayedMailer.jobs.size didn't changed. I check that UserMailer.delay was called.

When I run this test with spring, it passes:
./bin/rspec spec/models/share_form_spec.rb

My environment is:
Rails 4.2.0
Ruby 2.2.0
Sidekiq 3.3.2

**Comment by mperham** [comment]
I suspect you are using `sidekiq/testing/inline` somewhere in your test suite.

**Comment by Olgagr** [comment]
Hi,

thanks for answer. I grep the whole repo to be sure but I don't use sidekiq/testing/inline anywhere in the project.
