### ISSUE TITLE
Error for sidekiq/morgue

### ISSUE THREAD

**Issue by ncri** [mperham/sidekiq#2219]
![bildschirmfoto 2015-03-06 um 12 30 12](https://cloud.githubusercontent.com/assets/16925/6523843/4d411dd0-c3fc-11e4-85cd-aee6fd103a5e.png)

```
NoMethodError (undefined method `join' for #<String:0x007fa0ae18a988>):
  sinatra (1.4.4) lib/sinatra/show_exceptions.rb:37:in `rescue in call'
  sinatra (1.4.4) lib/sinatra/show_exceptions.rb:21:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  sinatra (1.4.4) lib/sinatra/base.rb:180:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  sinatra (1.4.4) lib/sinatra/base.rb:2004:in `call'
  sinatra (1.4.4) lib/sinatra/base.rb:1469:in `block in call'
  sinatra (1.4.4) lib/sinatra/base.rb:1778:in `synchronize'
  sinatra (1.4.4) lib/sinatra/base.rb:1469:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
```

**Comment by seuros** [comment]
can you remove newrelic gem and try again.

**Comment by ncri** [comment]
Same error

**Comment by seuros** [comment]
Can you provide a sample app with this error ?

**Comment by ncri** [comment]
Well, its a big app this is in, but i can try. Not sure when though. The error suddenly started to appearing today, first i was able to browse the dead jobs just fine. Then the error appeared, first only when paginating. So I assume it has something to do with the type of job listed. But not sure.

**Comment by ismaelga** [comment]
Maybe that's some bug in that version of rack or sinatra

https://github.com/sinatra/sinatra/blame/master/lib/sinatra/show_exceptions.rb#L35
https://github.com/rack/rack/commit/893a2c50

**Comment by mperham** [comment]
I suspect your admin user check is buggy.

**Comment by ncri** [comment]
Admin user check? How could that be buggy? Not sure what you mean.

**Comment by ncri** [comment]
And my admin user check is as simple as it gets, When the user is of class User::Admin it returns true, because in that class i have:

  def is_admin?
    true
  end

But I don't understand how that could be related?

**Comment by seuros** [comment]
The bug is not present in sidekiq. Your app code or a gem is monkeypatching something.

Please provide a minimalistic application that reproduce the bug.

**Comment by ncri** [comment]
Okay, I will try, but you could leave this open, its not solved yet and its not sure yet that its a problem with our app or another lib. Might as well be a combination.

**Comment by seuros** [comment]
As i said, the issue is not bug in Sidekiq.  I advice you to open an issue in the conflicting lib repo when you locate it. 
please provide your Gemfile.lock, maybe someone is award of some conflict.

**Comment by ncri** [comment]
Okay, well, it is rather big and has a few private gems in them, I removed those here:

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.0)
      actionview (= 4.2.0)
      activesupport (= 4.2.0)
      rack (~> 1.6.0)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    active_attr (0.8.5)
      activemodel (>= 3.0.2, < 5.0)
      activesupport (>= 3.0.2, < 5.0)
    activejob (4.2.0)
      activesupport (= 4.2.0)
      globalid (>= 0.3.0)
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.2.3)
      actionpack (>= 3, < 5)
      activerecord (>= 3, < 5)
    addressable (2.3.6)
    aggregate (0.2.2)
    arbre (1.0.3)
      activesupport (>= 3.0.0)
    arel (6.0.0)
    aws-ses (0.4.4)
      builder
      mail (> 2.2.5)
      mime-types
      xml-simple
    bcrypt (3.1.9)
    bourbon (4.2.1)
      sass (~> 3.4)
      thor
    builder (3.2.2)
    cancan (1.6.10)
    capybara (2.3.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.1.0)
      capybara (~> 2.0, >= 2.0.2)
      json
    celluloid (0.16.0)
      timers (~> 4.0.0)
    childprocess (0.5.5)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    chunky_png (1.3.4)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.8.0)
    commonjs (0.2.7)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    compass-rails (2.0.4)
      compass (~> 1.0.0)
      sass-rails (<= 5.0.1)
      sprockets (< 2.13)
    connection_pool (2.1.2)
    countries (0.9.3)
      currencies (~> 0.4.2)
    coveralls (0.7.0)
      multi_json (~> 1.3)
      rest-client
      simplecov (>= 0.7)
      term-ansicolor
      thor
    currencies (0.4.2)
    daemons (1.1.9)
    dalli (2.7.0)
    database_cleaner (1.2.0)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
    diff-lcs (1.2.5)
    docile (1.1.3)
    dotenv (0.9.0)
    erubis (2.7.0)
    eventmachine (1.0.4)
    excon (0.39.5)
    execjs (2.3.0)
    factory_girl (4.2.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.2.1)
      factory_girl (~> 4.2.0)
      railties (>= 3.0.0)
    faraday (0.8.9)
      multipart-post (~> 1.2.0)
    faraday_middleware (0.9.1)
      faraday (>= 0.7.4, < 0.10)
    ffi (1.9.0)
    flying-sphinx (1.0.0)
      faraday_middleware (~> 0.7)
      multi_json (>= 1.3.0)
      pusher-client (~> 0.3)
      rash (~> 0.3.0)
      riddle (>= 1.5.6)
      thinking-sphinx
    fog (1.22.1)
      fog-brightbox
      fog-core (~> 1.22)
      fog-json
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-brightbox (0.5.1)
      fog-core (~> 1.22)
      fog-json
      inflecto
    fog-core (1.24.0)
      builder
      excon (~> 0.38)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.0)
      multi_json (~> 1.0)
    foreman (0.63.0)
      dotenv (>= 0.7)
      thor (>= 0.13.6)
    formatador (0.2.5)
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.1.1)
    garb (0.9.8)
      activesupport (>= 2.2)
      multi_json (>= 1.3)
    gibbon (1.1.1)
      httparty
      multi_json (>= 1.3.4)
    globalid (0.3.3)
      activesupport (>= 4.1.0)
    has_scope (0.6.0)
      actionpack (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
    has_setting (0.7.3)
    hashie (1.2.0)
    heroku-api (0.3.19)
      excon (~> 0.38)
      multi_json (~> 1.8)
    hike (1.2.3)
    hitimes (1.2.2)
    html_truncator (0.4.0)
      nokogiri (~> 1.5)
    httparty (0.13.0)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    inflecto (0.0.2)
    innertube (1.1.0)
    ipaddress (0.8.0)
    iso8601 (0.4.1)
    joiner (0.3.4)
      activerecord (>= 4.1.0)
    jquery-cookie-rails (1.3.1.1)
      railties (>= 3.2.0, < 5.0)
    jquery-fileupload-rails (0.4.1)
      actionpack (>= 3.1)
      railties (>= 3.1)
    jquery-minicolors-rails (2.1.4.0)
      jquery-rails
      rails (>= 3.2.8)
    jquery-rails (3.1.0)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-tablesorter (1.14.0)
      railties (>= 3.1, < 5)
    jquery-ui-rails (5.0.3)
      railties (>= 3.2.16)
    json (1.8.2)
    jwt (0.1.11)
      multi_json (>= 1.5)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.9.3)
    koala (1.10.0)
      addressable
      faraday
      multi_json
    launchy (2.3.0)
      addressable (~> 2.3)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (2.6.0)
      actionpack (>= 3.1)
      less (~> 2.6.0)
    less-rails-bootstrap (3.3.2.0)
      less-rails (~> 2.6.0)
    librato-metrics (1.4.0)
      aggregate (~> 0.2.2)
      faraday (~> 0.7)
      multi_json
    librato-rack (0.4.5)
      librato-metrics (~> 1.1)
    librato-rails (0.11.1)
      activesupport (>= 3.0)
      librato-rack (~> 0.4.2)
      railties (>= 3.0)
    libv8 (3.16.14.7)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    memcachier (0.0.2)
    middleware (0.1.0)
    mime-types (2.4.3)
    mini_magick (3.7.0)
      subexec (~> 0.2.1)
    mini_portile (0.6.0)
    minitest (5.5.1)
    mobile-fu (1.3.1)
      rack-mobile-detect
      rails
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (1.2.0)
    mysql2 (0.3.17)
    nested_form_fields (0.5.3)
      rails (>= 3.2.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.8.0)
    netrc (0.7.9)
    newrelic_rpm (3.9.9.275)
    nokogiri (1.6.2.1)
      mini_portile (= 0.6.0)
    non-stupid-digest-assets (1.0.4)
    oauth (0.4.7)
    oauth2 (0.9.3)
      faraday (>= 0.8, < 0.10)
      jwt (~> 0.1.8)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.1)
      hashie (>= 1.2, < 3)
      rack (~> 1.0)
    omniauth-facebook (1.6.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-oauth2 (1.1.2)
      faraday (>= 0.8, < 0.10)
      multi_json (~> 1.3)
      oauth2 (~> 0.9.3)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    paper_trail (3.0.0)
      activerecord (>= 3.0, < 5.0)
      activesupport (>= 3.0, < 5.0)
    pdfkit (0.6.1)
    pg (0.17.1)
    pusher-client (0.6.0)
      json
      websocket (~> 1.0)
    rack (1.6.0)
    rack-attack (4.2.0)
      rack
    rack-cache (1.2)
      rack (>= 0.4)
    rack-mobile-detect (0.4.0)
      rack
    rack-protection (1.5.2)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.0.3)
    rack-zippy (1.2.1)
    rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.5)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_autolink (1.1.6)
      rails (> 3.1)
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.3)
    railties (4.2.0)
      actionpack (= 4.2.0)
      activesupport (= 4.2.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.4.2)
    ransack (1.6.3)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.1)
    rash (0.3.2)
      hashie (~> 1.2.0)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.1.1)
    redis (3.2.1)
    redis-namespace (1.5.1)
      redis (~> 3.0, >= 3.0.4)
    ref (1.0.5)
    render_anywhere (0.0.8)
      rails (>= 3.0.7)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rest_client (1.8.1)
      netrc (~> 0.7.7)
    rollbar (1.2.13)
      multi_json (~> 1.3)
    rspec-collection_matchers (0.0.3)
      rspec-expectations (>= 2.99.0.beta1)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-rails (3.1.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    ruby-duration (3.1.0)
      activesupport (>= 3.0.0)
      i18n
      iso8601
    rubyzip (1.1.6)
    sass (3.4.12)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    select2-rails (3.5.9.2)
      thor (~> 0.14)
    selenium-webdriver (2.45.0.dev2)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    sidekiq (3.3.2)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-status (0.5.1)
      sidekiq (>= 2.7, < 3.4)
    simple-random (0.9.3)
    simple_form (3.1.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simple_oauth (0.2.0)
    simplecov (0.8.2)
      docile (~> 1.1.0)
      multi_json
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    sinatra (1.4.4)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sitemap_generator (5.0.1)
      builder
    slim (3.0.2)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slim-rails (3.0.1)
      actionmailer (>= 3.1, < 5.0)
      actionpack (>= 3.1, < 5.0)
      activesupport (>= 3.1, < 5.0)
      railties (>= 3.1, < 5.0)
      slim (~> 3.0)
    split (0.7.0)
      redis (>= 2.1)
      redis-namespace (>= 1.1.0)
      simple-random
      sinatra (>= 1.2.6)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    state_machine (1.2.0)
    sticky-rails (1.0.0)
    subexec (0.2.3)
    temple (0.7.5)
    term-ansicolor (1.3.0)
      tins (~> 1.0)
    therubyracer (0.12.1)
      libv8 (~> 3.16.14.0)
      ref
    thin (1.6.1)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    thinking-sphinx (3.1.3)
      activerecord (>= 3.1.0)
      builder (>= 2.1.2)
      innertube (>= 1.0.2)
      joiner (>= 0.2.0)
      middleware (>= 0.1.0)
      riddle (>= 1.5.11)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    timecop (0.7.1)
    timers (4.0.1)
      hitimes
    tins (1.0.0)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.4.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.3)
      unf_ext
    unf_ext (0.0.6)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    utf8-cleaner (0.0.9)
    warden (1.2.3)
      rack (>= 1.0)
    websocket (1.2.1)
    whenever (0.9.3)
      chronic (>= 0.6.3)
    will_paginate (3.0.5)
    xml-simple (1.1.3)
    xpath (2.0.0)
      nokogiri (~> 1.3)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack
      sass-rails
    youtube_it (2.1.1)
      builder
      builder
      faraday
      faraday (>= 0.7.3)
      nokogiri
      oauth
      oauth (>= 0.4.4)
      simple_oauth
      simple_oauth (>= 0.1.5)
    zurb-foundation (4.3.2)
      sass (>= 3.2.0)

PLATFORMS
  ruby

DEPENDENCIES
  acts-as-taggable-on
  aws-ses (~> 0.4.1)
  cancan
  capybara
  capybara-webkit
  coffee-rails
  coffee-script-source (~> 1.8.0)
  compass-rails
  country_select!
  coveralls
  dalli
  database_cleaner
  devise
  devise-async
  devise-encryptable
  factory_girl_rails
  faraday (= 0.8.9)
  ffi (= 1.9.0)
  flying-sphinx
  fog (>= 1.20.0)
  foreman
  formtastic
  garb
  geocoder!
  gibbon
  globalize (~> 5.1)!
  globalize-versioning!
  has_setting
  heroku-api (>= 0.3.17)
  html_truncator (~> 0.2)
  i18n!
  i18n_routing!
  inherited_resources!
  jquery-cookie-rails
  jquery-rails
  jquery-tablesorter
  jquery-ui-rails
  koala (~> 1.10.0rc)
  launchy
  librato-rails
  memcachier
  mini_magick (>= 3.3)
  mobile-fu
  mysql2 (= 0.3.17)
  nested_form_fields (>= 0.5.2)
  net-sftp
  newrelic_rpm
  non-stupid-digest-assets
  omniauth
  omniauth-facebook
  owlcarousel-rails!
  paper_trail
  pdfkit (>= 0.5.4)
  pg
  polyamorous!
  rack-attack
  rack-cache
  rack-timeout
  rack-zippy
  rails (~> 4.2)
  rails-html-sanitizer!
  rails_12factor
  rails_autolink
  ransack
  redcarpet
  render_anywhere
  responders (~> 2.1.0)
  rest_client
  riddle (~> 1.5.9)!
  rollbar (~> 1.2.4)
  rspec-collection_matchers
  rspec-rails
  ruby-duration
  s3_direct_upload!
  sass-rails
  seer (>= 0.5.7)!
  select2-rails
  selenium-webdriver
  sidekiq
  sidekiq-status
  simple_form
  sinatra
  sitemap_generator
  slim
  slim-rails
  split
  sprockets
  state_machine
  sticky-rails
  thin
  thinking-sphinx (>= 3.1.3)
  timecop
  turbolinks
  uglifier (>= 1.0.3)
  unf
  unicorn
  utf8-cleaner
  whenever
  will_paginate
  youtube_it (= 2.1.1)
  zurb-foundation

Is it possible to delete the dead jobs without being able to open that section? The error might be hard to track down, but I can try to debug. Not sure if its worth it, as it doesn't affect much of our app.

**Comment by seuros** [comment]
`Sidekiq::DeadSet.new.clear`

**Comment by ncri** [comment]
Thx.

**Comment by mperham** [comment]
This is a Sinatra bug: https://github.com/sinatra/sinatra/issues/951

**Comment by ncri** [comment]
Ah thanks, and its fixed there!

**Comment by ncri** [comment]
Just for the record, the issue is solved now by upgrading sinatra, but there is another underlying issue.... I will create a new issue...
