### ISSUE TITLE
Starting sidekiq using foreman

### ISSUE THREAD

**Issue by cscairns** [mperham/sidekiq#222]
I configured foreman proc file like so:

web: bundle exec unicorn_rails
redis: redis-server
worker: bundle exec sidekiq

When I go into a rails console session and call a worker like HardWorker.perform_async, the message isn't processed. At least not until I call bundle exec sidekiq in the root of my app.

Now I'm pretty new to sidekiq and background processing in general, but I am wondering why you can start sidekiq process using foreman?

**Comment by heftyashish** [comment]
I had the same issue, however this link solved it for me https://github.com/ddollar/foreman/wiki/Process-immediately-terminating as I was starting my sidekiq worker in daemonized mode

**Comment by aruprakshit** [comment]
@heftyashish So what did you change in your Procfile?

**Comment by heftyashish** [comment]
@aruprakshit I removed -d flag, as I was running sidekiq in daemonized mode before. Here's how my Procfile looks like:

web: rails s -p 3000
log: tail -f log/development.log
redis: redis-server
worker: bundle exec sidekiq -c 5 -L log/sidekiq.log -q default -q mailers
