### ISSUE TITLE
Remove, and disable, unsafe UI buttons?

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2221]
I've thought of this a few times, but #2217 prompted me again.

We have our Sidekiq web UI behind an ActiveAdmin page with CanCan(Can) integration. That way, you must explicitly have permission given to you to be able to view `/admin/sidekiq`.

However, anyone with access to the Sidekiq UI could, say, erase an entire queue, or mass-delete a bunch of failing jobs, even accidentally.

![screen shot 2015-03-06 at 14 23 25](https://cloud.githubusercontent.com/assets/342081/6532155/76deee28-c40c-11e4-96fe-d74494174f60.png)

![screen shot 2015-03-06 at 14 23 31](https://cloud.githubusercontent.com/assets/342081/6532158/79624a78-c40c-11e4-98d0-ad056e45526b.png)

They could also stop any/all Sidekiq processes.

![screen shot 2015-03-06 at 14 24 52](https://cloud.githubusercontent.com/assets/342081/6532180/9a74e478-c40c-11e4-8c63-9d4a9df9b884.png)

I personally have never and will never press any of the buttons shown on these screenshots. (The idea of deleting a queue is somewhat terrifying, depending on the interpretation of "delete".) The red ones, especially, even though process killing should be under supervision by a monitoring process.

I'm wondering whether it would be good to have a configuration setting that would let us disable "unsafe" buttons like this, not just so that they're hidden on the UI, but also so that the HTTP endpoints don't do anything.

I do realise, however, that individual jobs must be killable (to the morgue) and deletable to remove them. It seems good to not have a way to mass delete anything or stop an entire process, though, if it needs to be difficult to do so.

**Comment by aprescott** [comment]
(... "Retry All" is obviously not dangerous. :))

**Comment by mperham** [comment]
I think the simplest workaround here is to deny all non-GETs to the Web UI routes.  Make the UI read-only.  Might not require any code changes at all, just a tweak to routes or your web server config?

**Comment by aprescott** [comment]
Sorry for being so slow in getting back to this, I took a break from work for a couple of weeks. I like that idea and will try it out!
