### ISSUE TITLE
Trouble with mina

### ISSUE THREAD

**Issue by npearson72** [mperham/sidekiq#2222]
I'm trying to start/stop sidekiq with mina, and while stop works, start does not.

Here is the mina task:
````
namespace :sidekiq do
  task start: :environment do
    queue "cd #{app_path} && rails_env=#{rails_env} && bin/bundle exec sidekiq -d -C config/sidekiq.yml -L log/sidekiq.log"
  end

  task stop: :environment do
    queue "cd #{app_path} && bin/bundle exec sidekiqctl stop tmp/pids/sidekiq.pid"
  end
end
````

When I run the start command manually, it works, but it does not when using mina.

Oddly though, the mina stop task works.

**Comment by mperham** [comment]
Use RAILS_ENV, not rails_env?

**Comment by mperham** [comment]
Set the environment explicitly, i.e. `queue "cd #{app_path} && bin/bundle exec sidekiq -e #{rails_env} ...`

**Comment by npearson72** [comment]
I tried that, still doesn't work :-\

**Comment by npearson72** [comment]
BTW, it seems I can get it to work without daemonizing it, but when I use the -d flag through mina, it won't work. I can do it manually though. Any ideas?

**Comment by mperham** [comment]
I recommend people use upstart/systemd to control Sidekiq.  Then mina just needs to do `initctl restart sidekiq`.

**Comment by npearson72** [comment]
Hi @mperham 

I'm trying to get it working with upstart. I'm using Vagrant locally as my dev environment, and tried putting this into `/etc/init/sidekiq.conf`

````
# /etc/init/sidekiq.conf - Sidekiq config
description "Sidekiq Background Worker"

stop on (stopping workers or runlevel [06])

setuid vagrant
setgid vagrant
env HOME=/home/vagrant

respawn
respawn limit 3 30

normal exit 0 TERM

instance $index

script
exec /bin/bash <<'EOT'
  cd /vagrant
  bundle exec sidekiq -i ${index} -e development -L /home/vagrant/log/sidekiq.log
EOT
end script
````

I use this command and get this feedback:

````
vagrant@precise64:/vagrant$ sudo start sidekiq index=0
sidekiq (0) start/running, process 2257
````

But when I grep for the process, it's not there

When I try to run it as a service, I get this:

````
vagrant@precise64:/vagrant$ sudo service sidekiq start
start: Unknown parameter: index
````

Is there something wrong with my config?

**Comment by npearson72** [comment]
Also, when I try using `initctl restart sidekiq`, I get this:

````
vagrant@precise64:/vagrant$ initctl restart sidekiq
initctl: Rejected send message, 1 matched rules; type="method_call", sender=":1.2" (uid=1000 pid=1885 comm="initctl restart sidekiq ") interface="com.ubuntu.Upstart0_6.Job" member="Restart" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init")
````

Any ideas? Sorry.. I have no experience with upstart.

**Comment by npearson72** [comment]
Ah, I figured it out. Turns out I needed to pass the index=0 argument into starting the service. Thanks for your help. I'm closing this out. Cheers.

**Comment by snitko** [comment]
This solution ended up helping me: http://www.codedisqus.com/CSVkXVUqVU/sidekiq-daemon-crashes-when-starting-with-mina.html

Basically, mina exits before a daemon is spawned. So it doesn't start. Thus it needs this `sleep 1`.
