### ISSUE TITLE
How can I profile Sidekiq using ruby-prof to track down what my workers are doing and where the bottlenecks are?

### ISSUE THREAD

**Issue by dmagliola** [mperham/sidekiq#2223]
I see through Googling that Sidekiq used to have a "profile" option, but it's been removed.

Has it been replaced with something else? Is there any way to achieve the same thing?

Thanks!

**Comment by mperham** [comment]
```ruby
profile_this do
  SomeWorker.new.perform(...)
end
```

Now implement `profile_this`

**Comment by dmagliola** [comment]
I basically have a huge queue (dumped from production), that I'd like Sidekiq to process and be able to profile it, so I can test changes to the code, and run the same queue again and compare times. Doing this would imply doing the reading of the queue myself...

(Also, I'm not sure how I'd implement profile_this, sorry)

**Comment by mperham** [comment]
You cannot profile Sidekiq as a whole, MRI does not have thread-friendly profiling tools.  You can only profile individual jobs by executing them manually.  If you have JRuby, one of the fancy commercial profilers for the JVM might work.  I've used JProfiler with Sidekiq successfully.

**Comment by dmagliola** [comment]
I see. Ok, i'll find another way. Thanks!

**Comment by lenferer** [comment]
undefined method `profile_this'

**Comment by mperham** [comment]
Yes it is, you need to implement the ruby-prof integration code.
