### ISSUE TITLE
uninitialized constant Collector

### ISSUE THREAD

**Issue by ewamarciniak** [mperham/sidekiq#2224]
Hi, I am trying to test rescheduling of my messages with RSpec and therefore I have followed your testing instructions:

```MessagesWorker.perform_in(date_1, nil, message.id)
message.reschedule_msg(date_2)
Collector.should have_queued_job_at(date_2,1)```

I presumed that Collector class is part of the Sidekiq but it looks like it is not.

**Comment by mperham** [comment]
I have no idea what you are talking about.

**Comment by ewamarciniak** [comment]
Custom matchers  => https://github.com/mperham/sidekiq/wiki/Testing => I am talking about the Collector class

**Comment by jonhyman** [comment]
`Collector` is not a class in Sidekiq, it's an example just like `MyWorker` is not a class in Sidekiq.

**Comment by mperham** [comment]
Ok, now I see.  Rspec support is via a 3rd party gem.  That documentation should be shifted to the rspec-sidekiq gem so whoever wrote that content can fix it.

And it looks like you should change Collector to MessagesWorker there.

**Comment by ewamarciniak** [comment]
I see! Excellent, thank you!
