### ISSUE TITLE
How to test for enqueue job if class reference not available?

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#2225]
All of our worker classes live in a separate repo and occasionally we'll want to test to make sure a job was enqueued in respec.

```ruby
Workers::SomeClass.perform_async(trigger_object)

expect(Workers::SomeClass.jobs.count).to eq(1)
```
This combo works!

In the non worker based projects, we do *not* have access to the constant and have to enqueue jobs like this

```ruby
  trigger_object = {                                                                
        user_id: user.id
      }
      
      sidekiq_arguments = {
        class: 'Workers::SomeClass',
        args: trigger_object.to_json,
        jid: SecureRandom.hex(12),
        retry: false,
        enqueued_at: Time.now.to_f
      }.to_json
     redis_reference.lpush("queue:default", sidekiq_arguments)

    #later
    expect(Workers::SomeClass.jobs.count).to eq(1)
```
Any way around this or a suggestion on how to properly test this use case? Thanks ! :dancer:

**Comment by jonhyman** [comment]
I'd highly recommend that you use `Sidekiq::Client` to enqueue jobs. When you do it yourself, you lose so many things that Sidekiq provides for you, such as middleware, reliable push (if you have Sidekiq Pro), and differentiating between scheduled items and items to process now.

In our code where we do this, it looks like this:

```ruby
Sidekiq::Client.new(pool).push('queue' => queue, 'class' => class_name, 'args' => args)
```

Then we just stub out the `Client` and assert that it receives `push` with the appropriate parameters.
