### ISSUE TITLE
Command-line arguments don't override config file weighted/ordered queues setting

### ISSUE THREAD

**Issue by nate00** [mperham/sidekiq#2228]
Usually, if a setting appears in both the config file and the command-line arguments to the `sidekiq` command, the command-line argument takes precedence. This doesn't happen in the case of the implicit weighted/ordered queues setting, however.

In a new Rails app, if `config/sidekiq.yml` contains
```yaml
---
:queues:
  - ['foo', 1]
  - ['bar', 1]
```
and I run `bundle exec sidekiq -q foo -q bar`, I expect Sidekiq to execute jobs from `bar` only when `foo` is empty. Instead, the worker randomly takes jobs from `foo` and `bar`.

**Comment by nate00** [comment]
(In my case, I didn't actually need any settings from the config file, so adding a `--config NONE` argument sufficed as a workaround.)

**Comment by mperham** [comment]
I think your expectation is correct.

**Comment by eabrahamsen-handy** [comment]
Took a look at this bug. How would we want to handle queue priorities when the number of queues on the CLI is greater than 10? My initial hunch is to start the implied weight at 10 and drop to 1; then any queue after 10 default to 1.  Sound about right?

**Comment by mperham** [comment]
Either the weight is specified or it is 1.

**Comment by mperham** [comment]
No plans to fix.

**Comment by patbl** [comment]
In Sidekiq 6, the `--config NONE` trick stops working and you get the error `ArgumentError: No such file NONE`. We're working around this by specifying an empty file as the config file.
