### ISSUE TITLE
Sidekiq as an upstart is not working

### ISSUE THREAD

**Issue by shilpi230** [mperham/sidekiq#2229]
I want to start sidekiq whenever my systems reboots. I made three files according to this https://github.com/mperham/sidekiq/tree/master/examples/upstart/manage-many but in my log files i am getting this errors.

`bundler: command not found: sidekiqctl`
`Install missing gem executables with `bundle install``
`bundler: command not found: sidekiq`
`Install missing gem executables with `bundle install``
`bundler: command not found: sidekiq`
`Install missing gem executables with `bundle install``
`bundler: command not found: sidekiq`
`Install missing gem executables with `bundle install``
`bundler: command not found: sidekiq`
`Install missing gem executables with `bundle install``

**Comment by moracca** [comment]
same issue

**Comment by carlos-soto** [comment]
same issue, any ideas?
