### ISSUE TITLE
Programmatically pass configuration to Sidekiq

### ISSUE THREAD

**Issue by philostler** [mperham/sidekiq#2230]
I'm working on a new gem that aggregates configuration for different Ruby systems into a single application YAML file and then configures those systems via adapters on sub-sections of the configuration.

ActiveRecord and Sidekiq are quite similar in that they follow the pattern of allowing the configuration to be passed via their own YAML file. Programmatically, achieving this in ActiveRecord is easy...

```ruby
ActiveRecord::Base.configurations[environment] = configuration
```

...but I'm having a little more trouble finding a point in Sidekiq's interface I can do the same.

The configuration YAML block will be the same as it would be from Sidekiq's standalone file, I just need to know where to inject it.

Any pointers would be greatly appreciated :+1:

**Comment by mperham** [comment]
Everything winds up in `Sidekiq.options` but I'm not sure this is actually what is passed into the Manager to configure the actors.  I don't believe it is possible to do this.

**Comment by philostler** [comment]
Thanks for the reply. I'll attempt piping the configuration into `Sidekiq.options` and see where I get, otherwise I'll have to settle for configuring the client and server blocks only. Will report back either way and close when I know if it works or not

**Comment by mperham** [comment]
I prefer to close issues unless there's truly an bug.  Feel free to open another issue if you find something which needs tweaking.
