### ISSUE TITLE
The wiki about reliability is out of date

### ISSUE THREAD

**Issue by sdeframond** [mperham/sidekiq#2231]
[This page](https://github.com/mperham/sidekiq/wiki/Reliability) is outdated. It instructs to add this code to an initializer: 

```ruby
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!
end
```
But those methods are not even in Sidekiq Pro's codebase as of version 1.7.5.

I went around the problem by simply requiring the files:
```ruby
require 'sidekiq/pro/reliable_push' unless Rails.env.test?
require 'sidekiq/pro/reliable_fetch'
```

I found nothing about reliable scheduler though.

Did I miss anything ?

**Comment by aprescott** [comment]
The bang methods are in Pro 2.0+, whereas the require equivalents are pre-2.0. It's probably worth mentioning the difference in the wiki.

**Comment by sdeframond** [comment]
Thank you for your quick answer.

I was actually using Sidekiq 3.0 so bundler installed Sidekiq Pro 1.7. Everything runs well after upgrading :smile: 

Problem solved!

**Comment by aprescott** [comment]
Glad I could help!
