### ISSUE TITLE
stack level too deep in monitoring UI

### ISSUE THREAD

**Issue by nornagon** [mperham/sidekiq#2232]
I started the Sidekiq monitoring UI in a standalone process (through Rake), and got the following message on the console trying to load the dashboard:

```[2015-03-11 17:40:22] INFO  WEBrick::HTTPServer#start: pid=26247 port=9494
SystemStackError - stack level too deep:
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/lib/sidekiq/web_helpers.rb:24```

Here's an excerpt from the stacktrace (gleaned via pry-byebug):

```
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/lib/sidekiq/web_helpers.rb:30:in `get_locale'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/lib/sidekiq/web_helpers.rb:34:in `t'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_status.erb:3:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_status.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_status.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_status.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:6:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:13:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:349:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:6:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:13:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:349:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:6:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:13:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:349:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:6:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:13:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/layout.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:349:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:6:in `block in singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `instance_eval'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-5:in `singleton class'
 /Users/nornagon/work/www/vendor/bundle/gems/sidekiq-3.3.0/web/views/_nav.erb:-7:in `__tilt_70126296964040'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
 /Users/nornagon/work/www/vendor/bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:343:in `render'
 /Users/nornagon/work/www/vendor/bundle/gems/sinatra-1.0/lib/sinatra/base.rb:302:in `erb'
# ...
```

any ideas?

**Comment by mperham** [comment]
Your Sinatra gem is ancient. Upgrade.

**Comment by nornagon** [comment]
Fixed. Thanks much!

**Comment by ismaelga** [comment]
This kind of issues could be avoided if sidekiq-web was a different gem with proper dependency specification.

**Comment by seuros** [comment]
maybe we should merge https://github.com/mperham/sidekiq/pull/2105 ?

**Comment by ismaelga** [comment]
@seuros That looks to be a good solution too.

**Comment by mperham** [comment]
@ismaelga We've had this discussion before.  The UI is optional and Rubygems does not support optional dependencies so we're stuck with this behavior unless we add some sort of Sinatra version check.  I'd be ok with that.  We're not going to split it into a separate gem.
