### ISSUE TITLE
per-worker server middleware

### ISSUE THREAD

**Issue by phstc** [mperham/sidekiq#2236]
Hi

Shoryuken now supports per-worker server middleware:

https://github.com/phstc/shoryuken/wiki/Middleware#registering-per-worker-middleware

So besides the global middleware, a worker can define its own middleware:

```ruby
class MyWorker
  include Shoryuken::Worker

  def perform(sqs_mg, body)
    # ...
  end

  server_middleware do |chain|
    # This will join all "global" middleware with `MyWorkerSpecificMiddleware`
    # if you want to run only `MyWorkerSpecificMiddleware` for this worker
    # you can `chain.clear`
    # or to remove specific middleware for this worker you can `chain.remove OtherMiddleware`
    chain.add MyWorkerSpecificMiddleware
  end
end
```

The implementation is super simple:

* https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L36-L40
* https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/processor.rb#L25
* https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/chain.rb#L52-L54

Is that something interesting to contribute back to Sidekiq?

**Comment by mperham** [comment]
Hi Pablo, people have suggested this in the past and I've rejected the idea.  Middleware is meant to be orthogonal to workers and this would conflate the two ideas which I want to avoid.

**Comment by phstc** [comment]
:smile: 

Gotcha! Makes sense. I believe in most cases per-worker middleware isn't necessary.
