### ISSUE TITLE
Odd Missing Batch Error

### ISSUE THREAD

**Issue by veverkap** [mperham/sidekiq#2237]
We have workers that create and process the batch in a separate app.  The workers project is using sidekiq 1.9.2 with the following Gemfile.lock:

```
    sidekiq (3.3.2)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-failures (0.4.3)
      sidekiq (>= 2.16.0)
    sidekiq-pro (1.9.2)
      sidekiq (>= 3.2.3)
```

We have a separate tiny Sinatra app that is running Sidekiq-Web with the following Gemfile.lock:

```
sidekiq (3.3.2)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-pro (2.0.0)
      sidekiq (>= 3.3.2)
```

So we have a mismatch in sidekiq versions, but should that be a problem if one is just viewing them?  We get our error on the workers though, not on the web app which is newer.  We are recently seeing this error show up:

Sidekiq::Batch::NoSuchBatch: Couldn't find Batch e87c6e477db75e5b in redis

We have no code modifying the batch after it is created in our workers.  

```
{
  "args" => "[\"complete\", \"e87c6e477db75e5b\"]",
  "class" => "Sidekiq::Batch::Lifecycle",
  "enqueued_at" => "1425992407.4565227",
  "error_class" => "Sidekiq::Batch::NoSuchBatch",
  "error_message" => "Couldn't find Batch e87c6e477db75e5b in redis",
  "failed_at" => "1425992407.459025",
  "jid" => "f1deca7d196f7f4686347dbb",
  "queue" => "sender",
  "retried_at" => "1426428082.466823",
  "retry" => "true",
  "retry_count" => "19"
}
```

Do we need to get the versions identical?  Is this just a cosmetic issue or a real problem?

**Comment by mperham** [comment]
While I don't recommend separate versions for the web and workers (**especially across major versions**), it should work fine in this case.

I suspect you had a batch expire before all jobs were finished processing, e.g. if you had a job retry for a few weeks.  In this case there's no solution except to delete the job.

2.0 does not suffer from possible early batch expiration like 1.x.  The answer is to upgrade your workers to 2.0 at your convenience.

**Comment by veverkap** [comment]
Thanks @mperham!
