### ISSUE TITLE
Is there a way to kill jobs which are running longer than a specified timeout?

### ISSUE THREAD

**Issue by ncri** [mperham/sidekiq#2239]
Couldn't find anything about it. We have jobs blocking the queue sometimes.

Ideally I would like to wrap the sidekiq job execution in a timeout and handle timeouts as well, by logging the error and sending a mail to us...

**Comment by mperham** [comment]
Unfortunately there's no safe way to terminate a running thread.  Using `Timeout.timeout` is not thread safe and causes lots of pain and bugs so Sidekiq does not allow job timeouts.  You absolutely should put socket timeouts on all network calls.

**Comment by ncri** [comment]
okay, thx.
