### ISSUE TITLE
internationalize the panel sidekiq

### ISSUE THREAD

**Issue by frankyston** [mperham/sidekiq#2243]
hello,

I wonder if the sidekiq has internationalization, wanted to leave the panel in Portuguese.

Thanks.

**Comment by mperham** [comment]
Yes.  https://github.com/mperham/sidekiq/blob/master/web/locales/pt.yml

**Comment by frankyston** [comment]
How do I set to leave in Portuguese?

**Comment by mperham** [comment]
The language preferences in your browser should be set to Portuguese.

**Comment by kochka** [comment]
Hello,

I've just upgraded to 3.3.3 from 3.1.4 and the panel stay in english despite my browser settings seems ok (french).
it was ok in 3.1.4.  I've checked in Chromium and Firefox.

Cheers

**Comment by mperham** [comment]
@kochka Show us your browser language preferences.

**Comment by kochka** [comment]
![chromium](https://cloud.githubusercontent.com/assets/60413/7072722/c460df60-deee-11e4-9322-af6cc6fc0928.png)

**Comment by kochka** [comment]
I've removed the 2 "english" entries to be sure it was not interfering, but it remain in english.
By the way, I was running my dev version in 3.3.3 and the production one in 3.1.4 at the same time in the same browser and the 3.1.4 was in french.

**Comment by mperham** [comment]
If you remove the first entry, it will work.  The code does not work with compound locales like "fr-FR", just "fr".

**Comment by mperham** [comment]
I will fix this now.

**Comment by kochka** [comment]
Yes you're right, works with only french. Good if it can be fixed.
Thanks a lot :)

Cheers
