### ISSUE TITLE
Pro - Batch tracking

### ISSUE THREAD

**Issue by rselk** [mperham/sidekiq#2250]
My team and I have a Parent worker which creates a number of Child jobs in a batch. These child jobs each could potentially fail and need to be able to retry. Currently the included batch callbacks on_success or on_complete seem to not be quite what we are looking for. Ideally we would have a callback which fired when the jobs all finished processing (either successfully or had exceeded max retries).

We are thinking of using redis, and keeping track of the number of jobs each batch has executing. Incrementing the value when the job begins, decrementing when finished (either successfully or though retries exhausted). We can then check if the queue has a value of 0 to ensure that the batch is done processing.

Does this approach seem reasonable or are we going about this the wrong way?

**Comment by mperham** [comment]
Good question.  I think you've nailed the problem: there's no way for the retry and batch middlewares to coordinate.  The batch middleware treats all exceptions as failures so if you want a job to count as a success, you'll need to rescue the error in your worker so it doesn't get to the middleware.

The other thing you can do, which is probably simpler than tracking in Redis, is to treat an exception as a success in your job but schedule a new job to try again later:

```ruby
sidekiq_options retry: false

def perform(retry_count, *args)
  begin
    # do stuff
  rescue => ex
    if retry_count < 10
      batch.jobs do
        # reopen the batch and add a new job to act as the retry
        self.class.perform_in(retry_count.minutes, retry_count+1, *args)
      end
    end
  end
end
```

**Comment by rselk** [comment]
Thanks for the information and quick reply Mike. We decided to build on top of your existing callback infrastructure using our own tracking mechanism.
