### ISSUE TITLE
Random prioritization within same queue

### ISSUE THREAD

**Issue by baldwindavid** [mperham/sidekiq#2251]
Is there an easy way to randomize the order of jobs in the same queue? I have the following queues...

```yaml
  - [critical, 3]
  - [default, 2]
  - [low, 1]
```

I kickoff a job in the "default" queue that includes a batch (Batch A) that queues up 50,000 jobs in the "low" queue. Shortly after, I kickoff another job in the "default" queue that includes a batch (Batch B) that queues up 10,000 jobs in the "low" queue. Those jobs in Batch B seem to have to wait until all Batch A jobs have been completed before a single Batch B job starts.

Is there an easy way to dynamically set the priority weighting for each child job that it could force randomization within the same queue? Something with this type of effect...

```ruby
class BatchBChildJobClass
  include Sidekiq::Worker

  def priority
    rand(1.0..1.00001)
  end

  def perform
    #...
  end
end
```

**Comment by mperham** [comment]
There's no way to do this; jobs are designed to be run in the order they are enqueued.  Sidekiq makes having lots of worker threads cheap; can you start up more Sidekiq processes if you are seeing queue backlog?

**Comment by baldwindavid** [comment]
If that is the way it is, I'm sure we can work around it. I just wanted to make sure I wasn't missing something.

**Comment by lksv** [comment]
@mperham Processing queue in random order has practical use case:
I have got a queue of pages (URLs) to download. These URL points to several servers. Jobs for each of servers are enqueued almost consecutive to the queue.
That means:
* I may case load issues on the server (when several workers work in concurrent).
* If one of the server time-outs then whole queue is locked (even if I have several workers).

What is the right solution with Sidekiq? I hope that Sidekiq is the right choice and there exists some solution.

**Comment by mperham** [comment]
@lksv The right solution is [rate limiting](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting).  There is no way to implement random pick from a Redis list safely and efficiently.

**Comment by lksv** [comment]
thanks for quick answer.
I understand that it is not feasible.

Unfortunately, it's not the right solution for me:
* it does not solve the second issue (If one of the server time-outs then whole queue is locked). I would need to custom limmiting by the jobs arguments (e.g. the url server).
* (it's out of bugged of hobby project)

I can solve the first issue by dynamic custom timeout defined by the retry number. e.g. when I am trying to download the page first time I set timeout to 3s, on later the timeout will be quadratic longer.

**Comment by jonhyman** [comment]
You can introduce randomness somewhere. One design could be to save urls to
a database with a random number in a known range (like 0-9999), then have
the enqueued job randomly read a url based on randomness (the job generates
random numbers in the range and queries the db for urls). Another design
could be to enqueue each job at a random time in the future, say within 0
and 100 seconds.

Sent from my mobile device

@lksv <https://github.com/lksv> The right solution is rate limiting
<https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting>. There is no
way to implement random pick from a Redis list safely and efficiently.

—
Reply to this email directly or view it on GitHub
<https://github.com/mperham/sidekiq/issues/2251#issuecomment-184299301>.

**Comment by lksv** [comment]
thanks @jonhyman , I though this way too:
* enqueue to more queues (lets say 10 for my case) which will be processed with the same sidekiq process.
* within the worker randomly re-enqueue some jobs to later instead of processing them (could be even used with perform_in with random time).

...but the easiest solution is yours (enqueue jobs directly at random time in the future). Thanks.
