### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by Biggless** [mperham/sidekiq#2252]
Monitor is configured from here https://github.com/mperham/sidekiq/wiki/Monitoring.

When running my app as 'rails s' - monitor works fine. But when running 'puma -p 3000' - dashboard is empty.

Can I get any advise to solve this?

**Comment by aprescott** [comment]
I wonder if this related to the way that Rails 4.2.0 started listening on `0.0.0.0` for certain web servers? I know we had some difficulty with using Puma when moving from 4.1.x to 4.2.0.

**Comment by mperham** [comment]
Define 'empty'.
