### ISSUE TITLE
Unique simultaneous job per user_id - Mysql2::Error: Deadlock found with sidekiq workers

### ISSUE THREAD

**Issue by acegilz** [mperham/sidekiq#2253]
I need to assure that no more than one job per user_id is worked simultaneosly by any of the 25 workers to avoid deadlocks.

I have tried some things already but deadlocks keep occoring because it keeps trying to process all pending jobs on the queue without looking for the user_id on the params.

Is there any easy way to fix this?

Thanks

**Comment by mperham** [comment]
This is an issue with the database logic you are using, you should fix your database queries.  Sidekiq isn't designed to do what you want: https://github.com/mperham/sidekiq/wiki/Best-Practices#3-embrace-concurrency
