### ISSUE TITLE
Memory leak when polling a job queue in the we UI

### ISSUE THREAD

**Issue by sdeframond** [mperham/sidekiq#2254]
Hi there,

We noticed that polling a job queue in the UI (for example `/sidekiq/queues/default`) ends up bloating the server's memory. The effect is even stronger when jobs have a heavy payload.

It is not critical in our case but I imagine it could be bad.

Keep up the good work!

using Rails 4.1.9 on heroku
sidekiq-3.3.2
sidekiq-3.3.2

```ruby
# initializer/sidekiq.rb
Sidekiq::Mailer.excluded_environments= 'test'

require 'sidekiq/pro/notifications'
Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!

  config.options[:notifications][:email] = {...}
end

```

**Comment by mperham** [comment]
@sdeframond Unfortunately people report Sidekiq as the source of memory leaks all the time.  Because it is a framework, it gets blamed for every leak.  How do you know the fault isn't in Sinatra, MRI, Rack, json or other library?

**Comment by sdeframond** [comment]
You have a point. I will try to come up with a more specific case.

This being said, if for example Sinatra is the cause, the symptom appears indeed in Sidekiq. Sinatra's problem is both your and my problem. (Replace Sinatra with any other relevant dependency in the previous sentence.)

**Comment by seuros** [comment]
@sdeframond Did you mixup Github with Oracle or Microsoft VIP support ?
If a FOSS don't work for you, either use another one or go commercial.

**Comment by seuros** [comment]
@sdeframond could you tell me the version of sidekiq-pro & ruby you are running ?

**Comment by mperham** [comment]
@seuros Let's not be rude please.  Issues can be frustrating for all involved.

**Comment by seuros** [comment]
@sdeframond @mperham Sorry.

**Comment by seuros** [comment]
@sdeframond There is a know memory leak in ruby 2.2.0.

**Comment by sdeframond** [comment]
@seuros oh, good to know. We are using ruby 2.2.0.

This is not really critical for us right now. Just something to keep watching. I definitely understand that chasing every single dependency's memory leak is close to impossible.

It is good to know that ruby itself may be the source of the issue though :smile: 

Still, this is an issue, for both you and me ;)

**Comment by seuros** [comment]
update to 2.2.1

**Comment by sdeframond** [comment]
Will do and let you know.

**Comment by seuros** [comment]
:+1:
