### ISSUE TITLE
Sidekiq#inline! should not run jobs enqueued for the future

### ISSUE THREAD

**Issue by dbalatero** [mperham/sidekiq#2255]
/cc @mperham 

I'm running into an issue where if I have `Sidekiq::Testing.inline!` turned on, it will run jobs that are scheduled to run hours in the future.

This really blows up my integration tests, as certain future-scheduled jobs are meant to run as expirys, etc, and I don't want those to prematurely run expiration code in the lifecycle of the test.

If we can't modify `Sidekiq::Testing.inline!` due to compatibility reasons, I'd love to be able to turn off `inline!` for jobs made with `perform_at`.

Thoughts?

**Comment by seuros** [comment]
Did you take a look at Sidekiq::Testing.fake! ?

**Comment by dbalatero** [comment]
I basically want my jobs that enqueue now to run now, and I want my jobs scheduled for the future to not run, which `fake!` doesn't seem to give you.

Also, since Sidekiq is mixed in as a module, it's hard to globally stub out `perform_at`, which I would be okay with as a solution.

**Comment by mperham** [comment]
You don't need to /cc me, I'm the project owner.  :-)

The "right" semantic is not clear here and for backwards compatibility I'm reluctant to change it.  I think your best bet is to stub out the call.  You can do it globally by reopening the module:

```ruby
# don't execute future scheduled jobs when testing
module Sidekiq::Worker
  def perform_at(*args); end
  def perform_in(*args); end
end
```

**Comment by dbalatero** [comment]
I don't think you should change current calls, but what about adding another option to disable future scheduled jobs in test?

**Comment by dbalatero** [comment]
This actually was what ended up working for me:

```ruby
require 'sidekiq/worker'

module Sidekiq::Worker::ClassMethods
  def perform_at(*args)
  end

  def perform_in(*args)
  end
end
```

**Comment by mperham** [comment]
:+1:

**Comment by BananaNeil** [comment]
I realize this is old and closed, but I agree with dbalatero's original post.
I entirely expected `perform_at` to not be run when `Sidekiq::Testing.inline!` unless the specified run time was before `Time.now`

I also agree that "adding another option to disable future scheduled jobs in test" would be a sufficient way to handle this use case.

**Comment by ericchapman** [comment]
Quick note to add to @dbalatero's answer.  If you are using the "set()" method you will also need to override the "Setter" proxy

```ruby
module Sidekiq::Worker::ClassMethods
  def perform_at(*args)
  end

  def perform_in(*args)
  end
end

class Sidekiq::Worker::Setter
  def perform_at(*args)
  end

  def perform_in(*args)
  end
end
```

**Comment by joeyAghion** [comment]
Our application uses scheduled jobs quite a bit, and for ease of data-mocking I wanted to continue to inline jobs that were intended to run "in the past." I opted for middleware for this, loaded only in test mode.

```ruby
class SidekiqInlineUnlessScheduledMiddleware
  def call(_worker_class, job, _queue, _redis_pool)
    return if Sidekiq::Testing.inline? && job['at'] && job['at'] > Time.now.to_f
    yield
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add SidekiqInlineUnlessScheduledMiddleware
  end
end

Sidekiq.configure_server do |config| # because jobs can queue other jobs
  config.client_middleware do |chain|
    chain.add SidekiqInlineUnlessScheduledMiddleware
  end
end
```

Hope that's helpful for others.

**Comment by letiesperon** [comment]
@joeyAghion this also helped me in 2025, thanks 😍
