### ISSUE TITLE
Batch with sequential processing

### ISSUE THREAD

**Issue by olistik** [mperham/sidekiq#2256]
I use Sidekiq to fetch a batch of files via SFTP and then I need to import them preserving the filename ordering.

For example, given these remote files:

- /out/log_a1.csv
- /out/log_a2.csv
- ...
- /out/log_z9.csv

I need to import log_a1.csv before log_a2.csv and I need to wrap these imports into a batch so that I can easily track it, retry it and also trigger a callback after its completion (for example to spin up a worker that deletes remote files).

There is the [sidekiq-limit_fetch gem](https://github.com/brainopia/sidekiq-limit_fetch) that allows me to set a concurrency limit of 1 to a specific queue, therefore ensuring sequential processings, but I think that having this feature embedded in the Batch feature would allow the user application code to be smaller and simpler.

**Comment by jonhyman** [comment]
Why not just do this in one job and keep your progress stored in Redis or another database of your choosing? You'd be adding parallelism for something that doesn't seem to need (and in fact, is the anthesis of) parallelism. Your job can periodically write to Redis or some other database as it imports each file, and if it restarts or fails, it can see where it needs to start from.

**Comment by mperham** [comment]
You can do this with Sidekiq today.

```ruby
files = ['log_a1.csv', 'log_a2.csv', ...]
ProcessFiles.perform_async(files, files)

def perform(current_files, all_files)
  filename = current_files.pop
  process(filename)
  if current_files.empty?
    cleanup(all_files)
  else
    ProcessFiles.perform_async(current_files, all_files)
  end
end
```

**Comment by jonhyman** [comment]
Heh, great idea.

**Comment by olistik** [comment]
@mperham that's clean enough for me :-)

But I forgot to mention that my use case (indeed very specific) implies not knowing a priori the available (as in *already downloaded*) files.

This is because I download them asynchronously but also notify their availability in sequential ordering.
So, for example, if I download log_a2.csv before log_a1.csv, I can't process it until I've finished downloading and processing log_a1.csv first.

**Comment by mperham** [comment]
You might be able to use the filesystem for that.  Have `downloaded` and `processing` directories so your workers can tell which files are ready for processing and which are in progress.

**Comment by olistik** [comment]
@mperham yes, I could use a solution like this, but isn't the purpose of abstractions to keep away the lower details allowing the user to focus as much as possible on the highest details?
Don't you think that a DSL that wraps the execution of several jobs into a batch, customizable by concurrency level and execution ordering would allow a simpler user level code? :-)

**Comment by olistik** [comment]
Let me expand this a bit further.

By using the same kind of solution you've proposed, I have to make some quite sensible compromises.
Instead of delegating the execution of N jobs to an abstraction like in this pseudo-code:

```pseudo-code
job_generator = JobGenerator.new
batch = Batch.new(processing_order: :sequential) # implies concurrency size of 1
batch.perform do
  job_generator.perform do |job|
    batch.jobs << job
  end
end
```

I have to resort to application specific workarounds, probably different for each application context.

**Comment by mperham** [comment]
@olistik Sidekiq provides features which are "safe" and scalable.  Adding distributed locking and process coordination is never safe or scalable, especially in a generic form that anyone can use.  That's why I recommend the application do the heavy lifting.  The app developer is in the best position to determine the safest, easiest way to coordinate the work.

**Comment by olistik** [comment]
@mperham fair enough :-)
That generic feature, if feasible, would probably deserve a bigger wrapper around Sidekiq instead of being embedded into it.
