### ISSUE TITLE
Hide header navbar in mobile and tablet screen size

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2258]
Hello.
I think that header navbar takes up too much space in mobile and tabled screen sizes.
![screenshot 2015-03-25 00 32 41](https://cloud.githubusercontent.com/assets/1147484/6813500/b89e2076-d286-11e4-8d28-cd7d44c11c4a.jpg)

That why I want to suggest hide navbar on mobile or tablet screen size as well as in the [bootstrap](http://getbootstrap.com/components/#navbar).
![screenshot 2015-03-25 00 35 32](https://cloud.githubusercontent.com/assets/1147484/6813518/e83e18f4-d286-11e4-9f9c-1cd3e102f010.jpg)
![screenshot 2015-03-25 00 35 42](https://cloud.githubusercontent.com/assets/1147484/6813519/e8737882-d286-11e4-9127-1f4f36310394.jpg)

What do you think about this idea?

**Comment by mperham** [comment]
Fantastic, a "hamburger" menu button would be great.  I'm terrible at UI so someone else will need to do the work.

**Comment by davydovanton** [comment]
@mperham okay, i will fix it :ok_hand:

**Comment by davydovanton** [comment]
Fixed
