### ISSUE TITLE
Custom error handler

### ISSUE THREAD

**Issue by mattherick** [mperham/sidekiq#2261]
Hi!

My custom error handler is not working.. any idea what I am doing wrong?

I use:
     
    sidekiq (3.3.1)

I have following:

config/initializers/sidekiq.rb

    require 'sidekiq/web'
    require Rails.root + "lib/sidekiq_error_notifier"

    Sidekiq.configure_server do |config|
      config.error_handlers << Proc.new {|exception, context_hash| SidekiqErrorNotifier.notify(exception, context_hash) }
    end

lib/sidekiq_error_notifier.rb

    class SidekiqErrorNotifier
  
      def self.notify(exception, context_hash)
        ErrorMailer.notify_about_sidekiq_exception(exception, context_hash).deliver_later
      end

    end

workers/my_worker.rb

    class MyWorker
      include Sidekiq::Worker
      sidekiq_options :queue => :visits

      def perform(id)
        raise "exception which should trigger the custom error handler and send me an email..."
      end

    end

If I call

    MyWorker.perform_async(self.id)

in my model I only see the error in the log files, but my custom email is not sent..

**Comment by mperham** [comment]
You're sending the sidekiq error emails through Sidekiq?  That seems like a bad idea. Use deliver_now.

**Comment by mattherick** [comment]
Okay thank you for your reply. With deliver_now it works!
