### ISSUE TITLE
Activating reliable fetch causes redis connections to leak in certain instances

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#2262]
We're having a very strange issue ever since we've enabled reliable fetch. When I disable reliable fetch locally, the issue goes away. When I start up a sidekiq server locally (`bundle exec sidekiq -c 5 -q scraper -i ${DYNO:-1}`) and then start up a Rails console, I can get sidekiq to leak redis connections. In an initializer, we create a global $redis variable (`$redis = Redis.new(REDIS_CONFIG) if REDIS_CONFIG.present?`). Using that, I just call any redis command over and over (20-30 times quickly) and sidekiq will start leaking connections. I use `$redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count` so that I can call it while counting the number of clients connected to Redis as reported by Redis. Our sidekiq initializer is as follows:

```
require 'redis/namespace'

connection_pool = ConnectionPool.new(timeout: 1, size: (Sidekiq.server? ? (Sidekiq.options[:concurrency] + 2) : 5)) do
  Redis::Namespace.new('sidekiq', redis: Redis.new(url: REDIS_CONFIG[:fullpath], timeout: 10))
end

Sidekiq.configure_server do |config|
  config.redis = connection_pool
  # config.reliable!
  config.reliable_fetch!
  # config.reliable_scheduler!
end

Sidekiq.configure_client do |config|
  config.redis = connection_pool
end
```

These are all momentary leaks. If I wait long enough, they'll clean themselves up. As soon as I shut down sidekiq, they all clean themselves up. Note that I have zero jobs queued up and running, sidekiq is just up and waiting for jobs. Here's an example of me running the CLIENT LIST command after doing as I just described, then shutting down sidekiq and running it one more time.

```
irb(main):086:0> $redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count
=> 27
irb(main):087:0> $redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count
=> 11
irb(main):088:0> $redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count
=> 15
irb(main):089:0> $redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count
=> 15
irb(main):090:0> $redis.method_missing('client', 'list').split("\n").collect {|x| x.scan(/127.0.0.1:([0-9]*)/)}.flatten.count
=> 1
```

We were notified by our Redis provider that our connections started to spike to over 50k at some point last week and we noticed that it coincided with us deploying our new Sidekiq Pro implementation. We run ~280 sidekiq instances with five concurrency, so we shouldn't have many more than 1960 connections alive at any one time.

I can't think of any other details to provide right now, so let me know if you're able to reproduce this or not and any other information that might be helpful.

**Comment by mperham** [comment]
Are you using the latest version? There was a fix for Redis connections.

**Comment by jakemack** [comment]
I believe so? Here's the info from our Gemfile.lock. I tried to bundle update each and neither changed. So, if there's a new version that was released recently, I'll have to chase down the dependency issue that's not allowing me to update.

```
    sidekiq (3.3.3)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.1.1)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-pro (2.0.1)
      sidekiq (>= 3.3.2)
```

**Comment by mperham** [comment]
You need the latest connection_pool and Redis gems.

**Comment by jakemack** [comment]
Okay, I'll update them and report back, thanks

**Comment by jakemack** [comment]
Looks like it's working, I had to upgrade from redis 3.2.0 to 3.2.1. Thanks for the quick reply, I can get this into production tonight still!
