### ISSUE TITLE
Mount multiple Sidekiq Webviews

### ISSUE THREAD

**Issue by samuelreh** [mperham/sidekiq#2264]
I'm interested in deploying an app for monitoring my service's sidekiqs. Is it possible to run multiple web views (with different redis connections) on one sinatra app? I'm having a hard time namespacing the global redis connection. Is this possible or do I have to make some modifications to the web view?

Thanks!

**Comment by mperham** [comment]
It's not possible due to the `Sidekiq.redis` singleton.  You need a separate process per web view.  I want to fix this at some point in the future, possibly for 4.0.

**Comment by samuelreh** [comment]
good to know, thanks!

**Comment by mperham** [comment]
https://github.com/sinatra/sinatra/issues/990

**Comment by samuelreh** [comment]
@mperham let me know if there's anything I can do to make this happen. I'd love to contribute.
