### ISSUE TITLE
Change page reload on ajax request in livereload mode

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2266]
Hello! :octocat:
Now livereload reloads current page each N seconds (two by default). I think that this behavior is not correct because:
1. Interface is twitches
2. Collapsed navbar is closed each N seconds

That why I request change current behaviour on to ajax requests for page containers.
What do you think?

**Comment by mperham** [comment]
It hasn't used Ajax before because I was afraid of the increase in JavaScript complexity.  Since the Dashboard uses Ajax now, I would be happy to reconsider.

**Comment by davydovanton** [comment]
:cool: Furthermore I have some interesting ideas how i can create this :smiley:

**Comment by davydovanton** [comment]
Completed :fireworks:
