### ISSUE TITLE
Strange batch callback

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#2268]
We have an intermittent problem (it has happened twice in about a week now) that involves a callback job being queued up but having no callbacks defined in the status.

We're getting a Sidekiq::Batch::Callback job queued up for the success event (the only two callbacks we have defined in the system are both success events, so this makes sense so far). The issue seems to be with the data defined in the Sidekiq::Batch::Status class (and thus the actual data stored in Redis). For this batch id, we currently have two keys still defined in Redis: "sidekiq:b-iqnPs2aZ53-ycQ-jids" and "sidekiq:b-iqnPs2aZ53-ycQ". The jids key has 19 values in it and the hash key equals `{"pending"=>"-14", "kids"=>"0", "total"=>"19"}`. Pending -14 concerns me. In addition, none of our batches queue up only 19 jobs, they both queue up considerably more. The second batch (the one I believe causing the issue) uses jobs that, on certain conditions, will add another job to the batch they are a member of before completing. The Sidekiq::Batch::Status object, when loaded, has no callbacks defined on it, so line sidekiq/batch/callback.rb#28 crashes with `NoMethodError: undefined method `[]' for nil:NilClass`.

Here's what our Sidekiq::Batch::Status object looksl like inspected in a console.

```
#<Sidekiq::Batch::Status:0x007f00643bc570 @pool=#<ConnectionPool:0x007f0061cdf538 @size=5, @timeout=1, @available=#<ConnectionPool::TimedStack:0x007f0061cdf358 @create_block=#<Proc:0x007f0061cdf4e8@/app/config/initializers/sidekiq.rb:3>, @created=1, @que=[#<Redis::Namespace:0x007f00643c7880 @namespace="sidekiq", @redis=#<Redis client v3.2.1 for redis://our.redis.address>, @warning=false, @deprecations=false>], @max=5, @mutex=#<Mutex:0x007f0061cdf2b8>, @resource=#<ConditionVariable:0x007f0061cdf0b0 @waiters={}, @waiters_mutex=#<Mutex:0x007f0061cdee58>>, @shutdown_block=nil>, @key=:"current-69819808807340">, @bid="iqnPs2aZ53-ycQ", @props={"pending"=>"-14", "kids"=>"0", "total"=>"19"}, @failures=0, @completed=0>
```

Any ideas what may be going on? Or do you have an idea of how I can go about debugging what might be happening? My first thought is that it's being caused by a redis connectivity issue because this specific batch has 1400 workers running (on 280 dynos, so there are also another 560 connections for the managers and pollers).

**Comment by mperham** [comment]
Batch::Status should always have a callbacks hash, even if empty.  This is created on batch.rb#53 and persisted on batch.rb#148.  I have no idea how you could get a batch with a nil callbacks attribute.

I am pretty dumbfounded by your symptoms.  No explanation for how pending could go negative.  There's only one place where it is decremented: middleware.rb#44.  How could a job be counted as a success multiple times?

I'll continue to think about it.  Let me know if you find further data.

**Comment by jakemack** [comment]
Yeah, it totally doesn't seem possible. It happened again last night, but it's not a showstopper, luckily. It seems to be an extra callback in addition to the one we set. I'll look into it more early next week and come back with whatever new information I find.

**Comment by jakemack** [comment]
So, the nil callbacks attribute has not happened again since I posted this, so I think for now we can ignore that. However, the negative pending happens to us every night. Looking at middleware.rb, what happens in add_success if Redis times out at line 59 or 69? Does the job get queued up again? It will definitely call add_failure after the first part of add_success changing values in the batch. I'm going to test manually modifying add_success to simulate this tomorrow and see exactly what happens. Redis timing out is one issue, but what if Heroku restarts the dyno anywhere after 53 and before the end of Server#call? Hopefully I can attach the answers to these questions tomorrow and they might give us some insight into how pending can become negative.

**Comment by mperham** [comment]
If those pushes fail, it is possible that the job would get retried later and counted as a second success, yes, but those pushes only happen twice once all of the jobs have finished.

Can you give more detail about your setup?  What 3rd party Sidekiq extensions/middleware are you using?  Are you using Heroku + Redis SaaS?  Initializer?

**Comment by jakemack** [comment]
We're not using any 3rd middleware. The only extension we have is something small I wrote to add a method to Sidekiq::Worker that will requeue a job based on certain conditions so that all jobs can use the method in their perform method. The method also adds the requeued job to the current batch, if a batch exists. We are using Heroku and Redis Labs. We have a peak of 1400 worker threads running at any one time. We used to queue up 9+ million in this one batch and have now broken it down into many sub-batches of 10,000. The odd part is that a few (5-10 each night) of these sub-batches will have the same exact issue and pending will always be in the area of -1 to -10. This makes me think it's an issue that only crops up right when batches are ending and some specific race conditions occur.

As for our initializer:
```
connection_pool = ConnectionPool.new(timeout: 1, size: (Sidekiq.server? ? (Sidekiq.options[:concurrency] + 2) : 5)) do
  Redis::Namespace.new('sidekiq', redis: Redis.new(url: REDIS_CONFIG[:fullpath], timeout: 10))
end

Sidekiq.configure_server do |config|
  config.redis = connection_pool
  config.reliable!
end

Sidekiq.configure_client do |config|
  config.redis = connection_pool
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove Sidekiq::Middleware::Server::Logging
  end
end
```

**Comment by mperham** [comment]
Can you show me that method you wrote?  I was thinking about requeuing and batches this weekend and how that can lead to this type of issue...

**Comment by mperham** [comment]
And 9 millions jobs in a single batch is nuts, I'd never imagined people would make batches that big.  I guess it scales pretty damn well...

**Comment by jakemack** [comment]
Yeah, definitely. Depending on how much requeuing happens during the night, I've seen the batch grow as large as ~30 million before the night is over.

Here are the two extra methods added. One thing about these jobs is that some may involve a call to sleep. I'm unsure exactly how that plays out with dyno restarts initiated by Heroku and Sidekiq shutdowns. In case sleep was causing issues, I changed it to sleep for two seconds, then wake up, then sleep in a loop until the desired time has passed. I think interrupts work through sleep, but I wasn't positive. In any case, I didn't see a change there in terms of symptoms but wanted to mention the sleep since it's probably atypical.

```
def handle_captcha(page, *args)
      if page.throttled?
        batch_perform_async self.class, *args
        page.handle_throttling

        false
      elsif page.internal_error?
        batch_perform_async self.class, *args

        false
      else
        page.ok?
      end
    end

    def batch_perform_async(klass, *args)
      bid ? (batch.jobs {klass.perform_async *args}) : klass.perform_async(*args)
    end
```

**Comment by mperham** [comment]
I'm almost positive this is weird behavior due to out of memory for your Redis plan.  Check your max memory usage with `info` and bump up your plan if necessary.

**Comment by TheCorp** [comment]
Our Redis plan maxes out at 50gb and we've never even come close to that so I have a feeling its not related to that.

**Comment by jakemack** [comment]
I agree that it's not an out of memory error, but could definitely be another error such as any sort of connection error. I haven't had time to look into it more yet, but I'm going to continue testing at the end of the month when I'm back from vacation.

**Comment by mperham** [comment]
Can you show your `info` output so we can see the memory stats?

**Comment by TheCorp** [comment]
```
pub-redis-11677.us-east-1-3.2.ec2.garantiadata.com:11677> info
# Server
redis_version:2.8.12
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 3.2.0-48 virtual x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.6.3
process_id:7350845
run_id:0db0e45ab26257a6046ce6c8bf9e764740724ddf
tcp_port:11677
uptime_in_seconds:67902721
uptime_in_days:785
hz:10
lru_clock:0

# Clients
connected_clients:29
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:4

# Memory
used_memory:65637798
used_memory_human:62.59M
used_memory_rss:65637798
used_memory_peak:29462258646
used_memory_peak_human:27.43G
used_memory_lua:81920
mem_fragmentation_ratio:1
mem_allocator:jemalloc-3.2.0

# Persistence
loading:0
rdb_changes_since_last_save:47568636223
rdb_bgsave_in_progress:0
rdb_last_save_time:1427273178
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:2217000555
total_commands_processed:205255972070
instantaneous_ops_per_sec:27
rejected_connections:0
sync_full:5
sync_partial_ok:0
sync_partial_err:0
expired_keys:2589261
evicted_keys:0
keyspace_hits:53985248484
keyspace_misses:5627143297
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0

# Replication
role:master
connected_slaves:1
slave0:ip=0.0.0.0,port=0,state=online,offset=0,lag=0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Keyspace
db0:keys=7016,expires=472,avg_ttl=75168226950
```

**Comment by mperham** [comment]
Looks good :+1:

**Comment by TheCorp** [comment]
Ok great. The 27gb peak usage is also very rare, we were testing something out of the usual scope of things when we rarely break 5-10gb. 

As Jake said we'll revisit this soon and see if there's any way to pin down what's going on. Its odd, it only seems to happen on very long runs (~10m jobs broken up into 10k sub batches) but the issues only seem to occur on the final batches which makes it harder for me to believe its a redis connectivity issue unless there's something specific about whats going on at the end of these batches that causes it. 

We'll report back later, thanks for all the help.

**Comment by GermanDZ** [comment]
I experienced many _negative_ pending jobs in batches. It occurs when you launch many workers with the same `index`, all workers will share the internal queue. If some workers get killed at restart could process the same job many times (from the internal queue) or after moving the same job back to the original queue.
