### ISSUE TITLE
Bootstrap navbar bug in web UI

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2274]
I think you know about bootstrap navbar bug. Navbar can breaks when container contain too much elements. If you will install more than two sidekiq plugins you can see this bug.
![screenshot 2015-03-31 00 55 18](https://cloud.githubusercontent.com/assets/1147484/6908047/85e752c6-d743-11e4-9d18-11576c484cca.jpg)

Also you can see this behavior on other sites which using bootstrap navbar too, far examples:
![screenshot 2015-03-31 00 58 42](https://cloud.githubusercontent.com/assets/1147484/6908054/8d8158ce-d743-11e4-97ed-5b2402109890.jpg)
![screenshot 2015-03-31 00 59 06](https://cloud.githubusercontent.com/assets/1147484/6908055/8d879536-d743-11e4-8d9b-51475892539b.jpg)

I want to suggest two ideas for solving this problem:
1. Minimize the navbar at large width (currently 768px);
2. Make the dropdown button, which contain all plugin links;

Who has any ideas how fix this?

**Comment by seuros** [comment]
:+1:  for 2
