### ISSUE TITLE
Accessibility improvements?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2276]
It would be nice to evaluate the Web UI for possible accessibility improvements for use with screen readers and related devices.  I don't have a lot of knowledge in this area but I'd welcome any help.

**Comment by davydovanton** [comment]
What kind of programs you mean? And could you provide some examples to illustrate how it will be work?

**Comment by davydovanton** [comment]
Oh/ I'm sorry, I mean name of programs :cold_sweat:

**Comment by seuros** [comment]
Any screen reader. 
We will need to add the aria attributes for examples.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA .
I can work on it pretty soon.

**Comment by mperham** [comment]
Here's a few links.  The idea is to make the Web UI more usable for the people without vision, people with color blindness, people who can't use a mouse, etc.  Maybe there's some easy changes we can make to help accessibility.

https://webaccessibility.withgoogle.com/course
https://developer.mozilla.org/en-US/docs/Web/Accessibility

**Comment by davydovanton** [comment]
Thanks, i got it

**Comment by davydovanton** [comment]
@seuros if you do not mind, I can do it today :smiley_cat:

**Comment by sidnc86** [comment]
We are a team based in Pune, India working on Accessibility with Rails. We would like to contribute as well. Before we do that, to confirm, we will first need to 
1. Have an application which uses sidekiq gem
2. Looking at the episode 366 of RailsCasts, we would eventually have a URL within the application context to access the sidekiq web interface.

With this confirmed, we can go through the web interface using JAWS and NVDA on Windows and provide you with feedback.

**Comment by sidnc86** [comment]
Forgot to mention the important point about having blind Ruby/Rails programmers on board to be able to propose contributions on this front.
