### ISSUE TITLE
Redis down for some seconds -> previous record gets deleted

### ISSUE THREAD

**Issue by SaschaKrause** [mperham/sidekiq#2278]
Hi,
we are using a Sidekiq worker in a normal controller like that:

```
result = Result.new(name: "hello")
result.save!

DoStuffWithResultWorker.perform_async(result.id)
```

This is working perfectly when redis is up and running. But IF redis is down for some seconds, the results get not stored (result.save!). Still, the results record had to be there for a short time, because the result.id was a correct id (just the record in the DB is not there).

Am I missing something? Is this by design? 
PS: I'm not calling it from an ActiveRecord::Base.transaction

**Comment by mperham** [comment]
Unless that entire code block is within a transaction, the perform_async failing cannot affect the record persistence.
