### ISSUE TITLE
Upstart example script: Why no "start on" ?

### ISSUE THREAD

**Issue by robinboening** [mperham/sidekiq#2281]
Hi!

Thanks a lot for sidekiq and all your efforts on this gem! :)

I have a question concerning the upstart script example and the comment on line 20: https://github.com/mperham/sidekiq/blob/master/examples/upstart/manage-one/sidekiq.conf#L20

I just got feedback from a client who told me a worker did not do its job... Then I noticed sidekiq is not running at all just because the server was rebootet a few days ago.

What is the reason you do not want to start sidekiq automatically? I cant see any situation when this might be useful :)

Isn't the most wanted behavior the other way round?

**Comment by mperham** [comment]
Yeah, that makes no sense. Git blame and ask the author.

**Comment by robinboening** [comment]
> mperham authored on Feb 19, 2013
```
...
no "start on", we don't want to automatically start
...
```

:trollface: 

But thanks for your answer. I will provide a pull request for the example.

**Comment by tvdeyen** [comment]
Famous git blame answers :)
