### ISSUE TITLE
Some jobs are stuck in Enqueue

### ISSUE THREAD

**Issue by rvarma1848** [mperham/sidekiq#2286]
I have just now update to ruby (2.1.5), rails (3.2.21), sidekiq (2.17.8), puma (2.11.1) because of performance issue.

I see that some jobs are stuck in Enqueue and others are being processed fine.

I did not see any exceptions in production.log or sidekiq.log, For jobs processed
by sidekiq I see start and end logs in sidekiq.log and I do not see any info for
the jobs stuck in the queue.

I tried to do sidekiq -v to see there is any more info. Unfortunately nothing more shown.

What would cause certain jobs to get stuck in the queue and others being processed fine?

**Comment by mperham** [comment]
You need to supply a thread dump with the TTIN signal.

**Comment by rvarma1848** [comment]
I see nothing...
kill -s TTIN 4762
# ps -aef | grep sidekiq
deploy    4762     1  0 Apr05 ?        00:02:40 sidekiq 2.17.8 qliqweb [0 of 25 busy]                                                                          
# kill -s TTIN 4762

**Comment by ryansch** [comment]
Sidekiq puts the TTIN trace output in the log file.

**Comment by rvarma1848** [comment]
I got it to work. It was throwing exception in connecting to mail server.
