### ISSUE TITLE
Update tables for mobile screen

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2290]
Hello all :v:
I have the idea to update the table layouts, so that they are more adaptive. For example long tables for mobile screen looks like this:
![screenshot 2015-04-07 00 00 12](https://cloud.githubusercontent.com/assets/1147484/7012477/2a4198b0-dcba-11e4-90a8-a2c6b902afb3.jpg)
![screenshot 2015-04-07 00 00 22](https://cloud.githubusercontent.com/assets/1147484/7012478/2a702a0e-dcba-11e4-8ac2-cd824251a115.jpg)

But I want that they looks like this:
![screenshot 2015-04-06 23 57 46](https://cloud.githubusercontent.com/assets/1147484/7012480/2fad5370-dcba-11e4-8801-ab877c65e99e.jpg)
![screenshot 2015-04-06 23 57 54](https://cloud.githubusercontent.com/assets/1147484/7012481/2fade826-dcba-11e4-8e5f-2d5a4facd658.jpg)

What do you think?

**Comment by seuros** [comment]
:shipit:

**Comment by mperham** [comment]
I'm mostly concerned about the Dashboard and Busy pages on mobile.  No one has ever asked for improved tables on mobile so I'm not sure how much demand there is.  I guess it's hard to say without seeing the actual code changes.

**Comment by davydovanton** [comment]
So, I create simple prototype for scheduled page:
![download](https://cloud.githubusercontent.com/assets/1147484/7030924/cd61950c-dd70-11e4-93a3-490a3c17486b.png)

@seuros and @mperham what do you think?

**Comment by seuros** [comment]
I like it. Do you have any branch where i can test it ?
I think the checkbox should be pulled to the left.

**Comment by davydovanton** [comment]
Yes, of course [davydovanton/sidekiq#mobile-tables](https://github.com/davydovanton/sidekiq/tree/mobile-tables). Also I deploy this branch to my [heroku application](https://sidekiq-history-gem.herokuapp.com/sidekiq/scheduled)

**Comment by mperham** [comment]
What does the code look like?  I don't see a lot of value to it frankly - I'd prefer to drag left to see the columns off screen and not have to scroll down forever.

**Comment by mperham** [comment]
I see.  https://github.com/davydovanton/sidekiq/commit/95883824e862bea41db71c8557109019c68dd82c The code's fine but I'm not sure it should be vertical when the width is 750px.  Seems like it should be vertical only on the thinnest of displays: 360px and less?

**Comment by davydovanton** [comment]
yes, I agree with you - `750px`+ isn't correct value.  But I have checked screen width for iphone 6+ in chrome mobile mode and this equal `414px`.
Also I think that center is great place for checkbox, @seuros what do you think?

**Comment by seuros** [comment]
@davydovanton center is fine too.

**Comment by davydovanton** [comment]
Mike, I think I know another solution for this problem. I can set `overflow` property for table (result you can see on this gif):
![sidekiq-long-table-overflow](https://cloud.githubusercontent.com/assets/1147484/7608470/883d5222-f972-11e4-9a33-85fe1cb2aadf.gif)

What do you think, it's better for you?

**Comment by mperham** [comment]
Looks good.
