### ISSUE TITLE
Committer Alumni?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2292]
There's a few committers who haven't contributed to Sidekiq in years.  I'd like to consider moving those people to "alumni" status [a la Rails][0] and removing their commit bit.  Anyone have an opinion one way or another?  Moving to alumni status would be optional; any committer who wants to retain their commit bit can ask.

[0]: http://rubyonrails.org/core/alumni/

**Comment by davydovanton** [comment]
Interesting idea :+1: , but I think that we should to notify this people before doing something

**Comment by mperham** [comment]
Removed a few people whom I haven't seen around for two years.
