### ISSUE TITLE
sidekiq_options in ActionMailer

### ISSUE THREAD

**Issue by davidmilo** [mperham/sidekiq#2294]
Hi,

Is it possible to override sidekiq_options in ActionMailer?

Something like this would be great but it doesnt work:
```
class UserMailer < ActionMailer::Base
  include Sidekiq::Worker
  sidekiq_options queue: "devise_emailss"

  def my_mail(options)
  end
end
```

I know I can do ``UserMailer.delay(queue: :my_queue).my_mail(user: 1)`` but I do not want to specify queue in the calling every time I call it. Would love to have it as a setup in the mailer.

**Comment by davydovanton** [comment]
Hello David!
I found [andersondias/sidekiq_mailer](https://github.com/andersondias/sidekiq_mailer) gem in which, according to the documentation, you can [set any sidekiq options](https://github.com/andersondias/sidekiq_mailer/wiki/Overriding-sidekiq-options). May be it's will be helpful for you.

**Comment by davidmilo** [comment]
I found it too but it has few differences - for example way of calling jobs.

``UserMailer.delay(queue: :my_queue).my_mail(user: 1)``
vs
``UserMailer.unban(:user => User.last).deliver``

Plus I could see that sidekiq_mailer serialise params to redis in a bit different way. I am gonna use it for now but my question is whether there is any way it could be updated in next versions of sidekiq so that options can be overridden without using external gems.

**Comment by davydovanton** [comment]
so I understood you, thanks for exploration :+1:

**Comment by mperham** [comment]
You can reopen the Sidekiq::Extensions::DelayedMailer class to set sidekiq_options.

**Comment by davydovanton** [comment]
Mike, may be will be great to add  `sidekiq_options` to all sidekiq extensions?

**Comment by mperham** [comment]
All extensions are Sidekiq::Workers and therefore already have `sidekiq_options`.  You just have to reopen the class to access it.

**Comment by srghma** [comment]
@mperham can you provide an example how to `reopen the class to access sidekiq_options`

**Comment by mperham** [comment]
```ruby
class Sidekiq::Extensions::DelayedMailer
  sidekiq_options queue: 'my_queue', retry: false, etc
end
```
