### ISSUE TITLE
sidekiq executes jobs when called in rails console, but not in app controller

### ISSUE THREAD

**Issue by avifoxi** [mperham/sidekiq#2300]
Thanks for reading, I'm new to Sidekiq -- and hope that this is a simple configuration issue I'm missing. 
Anyhoo -- 

Redis is up locally. Foreman loads rails and sidekiq's sinatra app. 
I call a sidekiq method in the rails console- and it executes immediately (though is not registered in the dashboard at  localhost/sidekiq ... but job is processed and email is sent).

I call the same method in the controller, within the app, and the job enqueues, but never executes.
So -- what am I doin wrong? 

here's some code!

Procfile
```ruby
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec sidekiq  2>&1 | logger -t sidekiq
```

config/unicorn.rb
```ruby
worker_processes Integer(ENV["WEB_CONCURRENCY"] || 5)
timeout 15
preload_app true

before_fork do |server, worker|
  Signal.trap 'TERM' do
    puts 'Unicorn master intercepting TERM and sending myself QUIT instead'
    Process.kill 'QUIT', Process.pid
  end

  defined?(ActiveRecord::Base) and ActiveRecord::Base.connection.disconnect!
end

after_fork do |server, worker|
  Signal.trap 'TERM' do
    puts 'Unicorn worker intercepting TERM and doing nothing. Wait for master to send QUIT'
  end

  defined?(ActiveRecord::Base) and ActiveRecord::Base.establish_connection

  Sidekiq.configure_client do |config|
    config.redis = { size: 1 }
  end
end
```

config/initializers/sidekiq.rb
```ruby

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/12' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/12' }
end
```

I call 
```ruby
DonationMailerWorker.perform_async(Donation.last.id) 
```
in the console. and get a nice sidekiq return id:
"5725654a3b202d8ea5fc2ef3"
and recieve some email shortly thereafter. 
hurray!

BUT -- 
I call the SAME METHOD in the controller
Sidekiq adds the job to the default queue, shown in the dashboard UI, but never executes it. 

Also -- in the controller -- if I call the method synchronously -- ala
```ruby
DonationMailerWorker.new.perform(Donation.last.id) 
```
It DOES execute correctly and immediately. 

So -- people of greater sidekiq capability -- 
Please help.

Also--- what are your preferred methods for sidekiq worker logging and debugging ? (i realize this is a totally distinct question... ignore if irrelevant) 

And -- more stats re: my dev env -->
ruby 2.0.0
rails 4.1.5
mailgun email via smtp

Thank you!

**Comment by davydovanton** [comment]
hello, may be are you running sidekiq and rails application in different rails environments?

**Comment by avifoxi** [comment]
entirely possible -- how can I check this ?

**Comment by davydovanton** [comment]
you could run `Rails.env` in console and `puts Rails.env` in your rails application

**Comment by avifoxi** [comment]
of course-- tnx -- will do

**Comment by avifoxi** [comment]
@davydovanton just checked -- and both contexts are 'development'

**Comment by davydovanton** [comment]
can you display your sidekiq log?

**Comment by avifoxi** [comment]
so this is very odd. 
Sidekiq is not logging the method call in the controller at all, though it is logging the command line call.


```ruby
# Logfile created on 2015-04-16 11:06:30 -0400 by logger.rb/41954
2015-04-16T15:06:36.048Z 45905 TID-oxbb98sfg INFO: Booting Sidekiq 3.3.3 with redis options {:url=>"redis://localhost:6379/12"}
2015-04-16T15:06:37.624Z 45905 TID-oxbb98sfg INFO: Running in ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.0.0]
2015-04-16T15:06:37.624Z 45905 TID-oxbb98sfg INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-04-16T15:06:37.624Z 45905 TID-oxbb98sfg INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-04-16T15:06:37.625Z 45905 TID-oxbb98sfg INFO: Starting processing, hit Ctrl-C to stop
```
right now I execute the command in the controller, no log entry.
Next, I do it on the command line -- and we get this:

```ruby
2015-04-16T15:11:23.263Z 45905 TID-oxbc8g2hw DonationMailerWorker JID-3d9a93069f724e0339613314 INFO: start
2015-04-16T15:11:23.299Z 45905 TID-oxbc8g2hw DonationMailerWorker JID-3d9a93069f724e0339613314 INFO: Things are happening.
2015-04-16T15:11:23.904Z 45905 TID-oxbc8g2hw DonationMailerWorker JID-3d9a93069f724e0339613314 INFO: done: 0.641 sec

```

**Comment by davydovanton** [comment]
@avifoxi sorry I have no idea why this is happening(I don't have the required amount of data). But may be I can help you if you give simple application with this bug. :smiley:

*P.S.: sorry for delay :sweat_smile:*

**Comment by joshreback** [comment]
@avifoxi dunno if this problem is still affecting you, but I was having this same problem and it seems to be an ordering issue...when I booted the rails server _before_ booting Redis and Sidekiq, the jobs did not kick off properly. However, when I made sure to boot Rails after Redis and Sidekiq, `perform_async` worked just fine from within the Rails app.

**Comment by mattppp** [comment]
For anybody still having this issue, make sure you use `redis://localhost:6379/0` instead of `redis://localhost:6379/12`.
