### ISSUE TITLE
Pro 2.0.2 not tagged or released

### ISSUE THREAD

**Issue by ryansch** [mperham/sidekiq#2301]
@mperham It looks like you bumped pro 2.0.2 but never tagged or released.  I'm looking to upgrade to pro 2.x with the new 2.2.0 connection_pool stuff.

**Comment by mperham** [comment]
2.0.2 has not been released. You can just bump connection pool's version to pick up the fix.

**Comment by ryansch** [comment]
I was unclear on if I needed the fix from pro 47.  Pro 2.0.1 with connection_pool 2.2.0 is safe?

**Comment by mperham** [comment]
I believe so.

**Comment by ryansch** [comment]
Ok, thanks.
