### ISSUE TITLE
Feature idea: Batch::Callback should log event and bid

### ISSUE THREAD

**Issue by ryansch** [mperham/sidekiq#2305]
Seeing "Sidekiq::Batch::Callback JID-foobar" over and over in the log doesn't help me diagnose batch issues.  Could we add the callback event (ex: success) and the bid the callback is for?

**Comment by mperham** [comment]
Latest Sidekiq should log BID if available.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/logging.rb#L11

**Comment by ryansch** [comment]
Right, but the batch callbacks are not run _inside_ of the batch they're running on behalf of.

**Comment by mperham** [comment]
Ah, got it.  Yeah.  Hmmm...

**Comment by mperham** [comment]
So Sidekiq Pro since 2.0 will log the BID and event but at the debug level since I didn't want to add too much more logging output.  Think that should be be INFO?

```ruby
logger.debug { "BID-#{bid} #{event}" }
```

Unfortunately I can't think of a clean way to integrate your request with Sidekiq's built-in logging middleware.
