### ISSUE TITLE
How to run Sidekiq with ActiveJob?

### ISSUE THREAD

**Issue by andrewhavens** [mperham/sidekiq#2306]
I am working on a new Rails 4.2 app. I have added Sidekiq as the ActiveJob backend and added the Sidekiq web UI. I have a mailer that is supposed to be sending emails. I can see the email ending up in the mailers queue. However the job is not being run. I am running this app on Ninefold and converted to using a Procfile (like Heroku). I specified `worker: bundle exec sidekiq`. I followed all of the documentation that I could find, but I feel like I'm missing a step. What am I doing wrong?

**Comment by mperham** [comment]
-q mailers -q default 

Need to tell Sidekiq to process that queue.

**Comment by dftaher** [comment]
I'm having the same problem even though I specify the queues when running the workers.

**Comment by andrewhavens** [comment]
It worked for me when I specified the queues as Mike mentioned:

    bundle exec sidekiq -q mailers -q default

So @dftaher you must be having a different issue than I was.

**Comment by mperham** [comment]
Active Job integration documentation is in the wiki:

https://github.com/mperham/sidekiq/wiki/Active-Job

There's no known bugs right now; any issues you are seeing are almost certainly due to application issues.
