### ISSUE TITLE
Having reliable push ignore certain types of exceptions?

### ISSUE THREAD

**Issue by jonhyman** [mperham/sidekiq#2307]
I was looking at logs for one of our applications today and saw a really bad loop on one of our servers due to reliable push:

> Apr 17 00:32:33 stdout.log:  2015-04-17T04:32:33.365Z 29947 TID-or66uma64 INFO: [ReliablePush] Connectivity restored, draining local queue
> Apr 17 00:32:33 stdout.log:  2015-04-17T04:32:33.365Z 29947 TID-or66uma64 WARN: [ReliablePush] Enqueueing job locally due to error: source sequence is illegal/malformed utf-8
> Apr 17 00:32:33 stdout.log:  2015-04-17T04:32:33.846Z 29947 TID-or66uma64 INFO: [ReliablePush] Connectivity restored, draining local queue
> Apr 17 00:32:33 stdout.log:  2015-04-17T04:32:33.846Z 29947 TID-or66uma64 WARN: [ReliablePush] Enqueueing job locally due to error: source sequence is illegal/malformed utf-8

It was looping over this, creating GBs of logs. What are your thoughts on ignoring certain types of exceptions for reliable push? Namely, `JSON::GeneratorError`?

**Comment by jonhyman** [comment]
Found another one from today. This web app directly enqueues jobs and it seems like some content is being posted up malformed. 

> Apr 21 09:16:14 stdout.log:  2015-04-21T13:16:14.821Z 372 TID-ovqh0bhtk INFO: [ReliablePush] Connectivity restored, draining local queue
> Apr 21 09:16:14 stdout.log:  2015-04-21T13:16:14.822Z 372 TID-ovqh0bhtk WARN: [ReliablePush] Enqueueing job locally due to error: "\xF8" from ASCII-8BIT to UTF-8

**Comment by mperham** [comment]
Can we JSONify earlier, so the exception isn't trapped in the push rescue?  Ideally that rescue should only catch network errors; other errors should raise.

**Comment by jonhyman** [comment]
That's certainly a possibility. I'm about to hop on a flight to SF for the week, so can't work on anything more substantial right now. However, since `raw_push` is private, it should be able to be refactored.

**Comment by jonhyman** [comment]
I had 15 minutes and came back to this to think about. It's possible, but I have to rewrite both `raw_push` and `raw_push_with_backup` since right now, with aliasing on `raw_push`, if `raw_push` took in already JSON'd payloads, then it also needs to know the `at` and `queue` and pass that to `atomic_push` so that method knows whether or not to `zadd` or `sadd` and `lpush`.

You down for me to do a larger refactor? You'll need to bump minor versions on both sidekiq and sidekiq-pro because they won't be compatible with each other.

... unless I'm missing something, I think that's the only way to do it if you want to JSONify earlier and thus have reliable push only handle commands to Redis.

**Comment by mperham** [comment]
If you're up for it, I'd be open to see what it looks like.

**Comment by jonhyman** [comment]
Okay cool, I'll loop back around and get something in 2-3 weeks.
