### ISSUE TITLE
How to get batch on_success 'original' args in server middleware?

### ISSUE THREAD

**Issue by homanchou** [mperham/sidekiq#2310]
We are attempting to use Apartment gem to switch postgres search_path to a merchant's schema based on merchant_id passed into a Sidekiq worker.  

This works well with sidekiq middleware, we have something like this:

```
class SwitchSchema
  def call(worker, job, queue)
    job_hash = job['args'][0]
    if worker.is_a?(Sidekiq::Extensions::DelayedClass)
      merchant_id = Psych.load(job_hash)[2][3]['merchant_id']
      Sidekiq.logger.info("Switching to schema: merchant_#{merchant_id}")
      Apartment::Tenant.switch("merchant_#{merchant_id}") do
        yield
      end
    elsif job_hash.is_a?(Hash) && job_hash['merchant_id']
      Sidekiq.logger.info("Switching to schema: merchant_#{job_hash['merchant_id']}")
      Apartment::Tenant.switch("merchant_#{job_hash['merchant_id']}") do
        yield
      end
    else
      yield
    end
  end
end
```

Essentially we want to DRY up our workers by wrapping execution within an Apartment::Tenant.switch block whenever the job args contains the 'merchant_id'.  

The above sidekiq server middleware works with regular sidekiq classes with `perform_async` and even `delay extensions`, however doesn't work with the on_success handler with Sidekiq pro batches.  In the context of the middleware we see that the worker is type of `Sidekiq::Batch::Callback`, but the job args are nothing like what was passed to `batch.on(:success, self.class.name, args)`.  Is there a way to get the original args?

Using:
sidekiq-pro (1.9.2)
sidekiq (3.3.0)

**Comment by mperham** [comment]
Hmmm, good point.  You could have the callback explicitly set up its Apartment:

```ruby
class MyCallback
  def on_success(status, options)
    # you could use Module#prepend to extract this apartment setting code
    within_apartment(options) do
    end
  end
end
```

Or you can add explicit checks for callback jobs in your middleware.  The second argument for Sidekiq::Batch::Callback is the BID.  You can do this in the middleware:

```ruby
if worker.class.name == 'Sidekiq::Batch::Callback' && msg['args'][0] == 'success'
  b = Sidekiq::Batch.new(msg['args'][1])
  options = b.callbacks['success']
  Apartment::Tenant.switch("merchant_#{options['merchant_id']}") do
    yield
  end
end
```

**Comment by ryansch** [comment]
We use an approach much closer to what https://github.com/influitive/apartment-sidekiq uses.  Keeps us from having to see the 'apartment' switching.
