### ISSUE TITLE
Sidekiq does not die with Ctrl-C on foreman

### ISSUE THREAD

**Issue by sonots** [mperham/sidekiq#2312]
Procfile

```
test1: bundle exec sidekiq -q test1
test2: bundle exec sidekiq -q test2
test3: bundle exec sidekiq -q test3
```

MyWorker.rb

```
class MyWorker
  include Sidekiq::Worker
  sidekiq_options retry: false

  def perform(params)
    Sidekiq.logger.info { "start" }
    sleep 10
    Sidekiq.logger.info { "finish" }
  end
end
```

reproduce:

```
$ bundle exec rails c
rails> Sidekiq::Client.enqueue_to('test1', MyWorker, 'foo')
```

then, Ctrl-C on foreman

```
$ bundle exec foreman s
(omit)
01:18:58 test1.1 | 2015-04-22T16:18:58.954Z 8101 TID-otp6bh2ho INFO: Starting processing, hit Ctrl-C to stop
01:19:24 test1.1 | 2015-04-22T16:19:24.574Z 8101 TID-otolbbd84 MyWorker JID-ba53c839c56c5cdb53578efe INFO: start
01:19:24 test1.1 | 2015-04-22T16:19:24.574Z 8101 TID-otolbbd84 MyWorker JID-ba53c839c56c5cdb53578efe INFO: start
^CSIGINT received
01:19:27 system  | sending SIGTERM to all processes
01:19:28 test3.1 | exited with code 0
```

ps. one of three processe survived this time

```
$ ps -ef | grep sidekiq
sonots      7169     1  1 01:13 pts/6    00:00:04 sidekiq 3.3.4 argus [0 of 25 busy]
```

**Comment by sonots** [comment]
It seems this is caused because foreman does not wait until all of its children dies. `foreman` creates pipe and passes it to its children, so that STDOUT can be shown on foreman's colorful display, but sidekiq tries to `write(2)` to STDOUT even after `foreman` dies (pipe is closed). 

But, what I feel wierd is that I have never experienced the same situation with `unicorn` or others. Any clues?

**Comment by sonots** [comment]
Issued to foreman, too https://github.com/ddollar/foreman/issues/553

**Comment by euge** [comment]
I have been running into the same thing and after playing with different versions of sidekiq and foreman...i've been able to trace it down to the upgrade from sidekiq 3.2.6 to 3.3.0. For me 3.2.6 is the last version in which sidekiq doesn't leave the processes behind.

**Comment by perldork** [comment]
I've looked into this a little; if you set the timeout to something low like 1 you'll see all workers cleaned up cleanly. The default timeout is 8 and sidekiq will wait that period of time before hard terminating workers - so the one worker that has a job doesn't exit right away, it waits for the timeout, then kills the job - and yeah by that time stdout would be closed because foreman has exited.

**Comment by mperham** [comment]
The `-t` argument implies that Foreman will wait 5 seconds for children to exit before KILLing them.  Looks like that argument should be set to 10 for Sidekiq.  Either way, this is outside of Sidekiq's purview; it's an issue with Foreman.

```
$ foreman help start
Usage:
  foreman start [PROCESS]

Options:
  -c, [--color], [--no-color]        # Force color to be enabled
  -e, [--env=ENV]                    # Specify an environment file to load, defaults to .env
  -m, [--formation="alpha=5,bar=3"]  
  -p, [--port=N]                     
  -t, [--timeout=N]                  # Specify the amount of time (in seconds) processes have to shutdown gracefully before receiving a SIGKILL, defaults to 5.
```
