### ISSUE TITLE
Remove Sinatra?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2313]
What would it take to remove our Sinatra dependency?  Can we ship the Sidekiq Web UI using bare Rack only?

**Comment by tarcieri** [comment]
Perhaps you could use Angelo instead of Sinatra?

https://github.com/kenichi/angelo

cc @kenichi

**Comment by mperham** [comment]
That would add more gem dependencies overall, arguably a net negative.

**Comment by w-A-L-L-e** [comment]
What's wrong with sinatra rb ? It's always just worked fine for me?

**Comment by mperham** [comment]
I didn't say there was anything wrong with Sinatra but it's one more gem that users need in their Gemfile to use the Web UI.

**Comment by w-A-L-L-e** [comment]
Ow ok. Keep up the great work with sidekiq it's one of my favourite gems ;).

**Comment by mperham** [comment]
:+1:

**Comment by kenichi** [comment]
thanks for the thought, @tarcieri. for sidekiq/web, "rack-able" is probably a key feature, no?. on the rack side of things, i've been using roda lately and really like it, but still not "bare rack".

**Comment by tarcieri** [comment]
Yeah nm :wink: Just thought it might be cool in this use case (e.g. if you had realtime websockets reports of what's happening)

**Comment by mperham** [comment]
It would be totally sweet but I think that Reel requires an ops cost which Sidekiq can't demand.

**Comment by tarcieri** [comment]
@kenichi's point about mounting it as rack middleware is spot on. That's the way we run a lot of our Sidekiq dashboards at Square

**Comment by davydovanton** [comment]
Mike, good idea, but I have some questions:
1. What will we do with projects(or plugins) that aren't supported for a long time but it used with sidekiq? (for example sidetiq)
2. Sinatra gives simple and userful DSL based on rack. How difficult is it to maintain a clean rack application?

**Comment by mperham** [comment]
1 is a great point, we'd have to allow some sort of extension point, ideally with an identical or similar API.  We can break the API but only at 4.0.

2 is unknown.  This issue is really just a thought and requires some serious prototyping and experimentation to determine if it's really possible.

**Comment by davydovanton** [comment]
Mike, what do you want to use? I think that I can try create branch with vanilla rack application tomorrow.

**Comment by mperham** [comment]
Just plain rack.

**Comment by davydovanton** [comment]
okay :+1:

**Comment by mperham** [comment]
In retrospect this seems like a pretty big change.  Closing as not worth it.
