### ISSUE TITLE
Feature idea: Callback once all jobs eventually complete

### ISSUE THREAD

**Issue by harlow** [mperham/sidekiq#2314]
To my understanding there are currently two callbacks:

1. `onSuccess` which only fires if ALL workers complete successfully on first run
1. `onComplete` which fires after each worker has completed (regardless of success/failure)

We'd get a lot of use out of a callback that would fire once a worker eventually succeeds.

**Comment by ryansch** [comment]
The batch success callback fires after all workers complete successfully.  They don't have to do it on the first run, they just have to complete before automatic job retry gives up (or if it's disabled).

https://github.com/mperham/sidekiq/wiki/Batches#callbacks
https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry
