### ISSUE TITLE
Sidekiq::Logging.initialize_logger closes STDOUT

### ISSUE THREAD

**Issue by sonots** [mperham/sidekiq#2315]
Calling

```
Sidekiq::Logging.initialize_logger('/path/to/log/file')
```

without `-L` option for `sidekiq` command closes STDOUT at https://github.com/mperham/sidekiq/blob/3056a5ac96376038c1951fab2a3524f878c61709/lib/sidekiq/logging.rb#L34

**Comment by sonots** [comment]
Here, the simplest patch

```diff
index b5863c5..9412a26 100644
--- a/lib/sidekiq/logging.rb
+++ b/lib/sidekiq/logging.rb
@@ -31,7 +31,11 @@ module Sidekiq
       @logger = Logger.new(log_target)
       @logger.level = Logger::INFO
       @logger.formatter = Pretty.new
-      oldlogger.close if oldlogger && !$TESTING # don't want to close testing's STDOUT logging
+      if oldlogger
+        logdev = oldlogger.instance_variable_get(:@logdev)
+        dev    = logdev.instance_variable_get(:@dev)
+        oldlogger.close unless dev == STDOUT || dev == STDERR
+      end
       @logger
     end
```

**Comment by mperham** [comment]
That's not intended to be a public API.  Why are you calling it?

**Comment by sonots** [comment]
I am calling it because I wanted to change log file inside ruby code (not -L option). Is there another public API?

**Comment by mperham** [comment]
There's no way for Ruby code to change the logger, on purpose.  My belief is that daemons should log to stdout always and use the init system + operating system to control service logging.  See "New-Style Daemons" here:

http://0pointer.de/public/systemd-man/daemon.html

This means that Ideally users should NOT be using the -P -L and -d flags.  They were a mistake to add.

**Comment by sonots** [comment]
Hmm, I will look the doc. Thanks.
