### ISSUE TITLE
options for a more reliable Scheduled::Poller

### ISSUE THREAD

**Issue by cainlevy** [mperham/sidekiq#2317]
I'm coming from resque/resque-scheduler, where the poller is a single thread that is both efficient (low load on Redis) and reliable (regular and consistent poll intervals). I understand that Sidekiq runs multiple Pollers, one for each process on each machine, and has to do something to remain efficient. My concern is that it accomplishes this at the expense of reliability.

## randomness vs averages

The Poller uses [`2 * rand`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L66) to stagger processes against each other, and then depends on everything averaging out. But averages aren't reliable.

In a simple case, where Sidekiq's threading model is used to full advantage and an application only runs a single Poller on a single server, the process will sometimes wait up to 30 seconds before finding and running scheduled jobs. It may not happen frequently, but it will not be uncommon.

Scaling up doesn't help either; it actually makes the inevitable outliers worse. If someone ends up running many Sidekiq processes and has many Pollers, then the automatically adjusted `poll_interval` will grow to some large number (e.g. [450 seconds with 30 processes](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L78)). At that point each process will sleep between 0 and 900 seconds, which will rarely (but inevitably) result in gaps in scheduling far greater than 30 seconds and rarely (but inevitably) result in load spikes on Redis.

## ideas

The quickest patch would be to make [`15.seconds`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L90) configurable without overriding Sidekiq's `ProcessSet.new.size`-based strategy. This would allow someone to pick, say, `5.seconds` and narrow the worst scheduling gaps from 30 seconds to 10 seconds on a single server. But it doesn't really solve the problem when scaling to multiple processes, and could make those inevitable load spikes on Redis more common.

Another idea might be for Sidekiq to rely entirely on the [`initial_wait`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L52) to stagger the Pollers, and then rely on non-random polling intervals afterwards. This would still create random scheduling gaps, and might actually be worse because those gaps would persist until something restarted.

A more robust solution might be for Sidekiq to elect a single Poller from a single process, and run it with a non-random and unadjusted polling interval. The other Pollers might continue to check in randomly and see if they need to take over scheduling duties. This is probably the coolest solution.

Finally, Sidekiq could allow the Poller to be enabled/disabled, so that the deployment strategy could control how many Pollers to run, with a static interval. The Poller would be enabled by default, for backwards compatibility and easy deployment by people who aren't bothered by scheduling gaps. This is probably the most pragmatic solution and I'd personally be happy to build around it.

**Comment by jonhyman** [comment]
Fwiw, we keep the polling frequency turned up rather high. Redis sorted
sets are implemented as skiplists, so zrangebyscore -inf, now with a limit
of 1 is O(1), so we hammer on it relatively often and don't use the process
set estimation.

**Comment by cainlevy** [comment]
@jonhyman Nice. Can you share what interval and number of pollers you're currently running?

**Comment by mperham** [comment]
I know that the current solution is not perfect; Sidekiq's scheduled jobs are not precise: they can execute many seconds after.  It does have the advantage of scaling to N processes easily without a SPOF while also minimizing Redis load.

Regarding leader election, I don't want to pull in a consensus protocol and all that it entails.  Sidekiq is explicitly designed so worker processes never have to talk to each other.

Is this issue a theoretical concern or can you give more data about actual operational problems you've seen?  I have customers using Sidekiq to process tons of jobs with hundreds of processes and the current algorithm has not been controversial as long as you can accept the random delay jitter in scheduling.

**Comment by cainlevy** [comment]
@mperham Agreed that electing a single Poller is a lot of complexity for the problem. It sounds cool, but not pragmatic. That's why I'd be happy to elect one with an option to disable that actor on all but one or two processes.

We haven't rolled Sidekiq out to anything in production yet, so this is definitely theoretical. But unless we can use a static polling interval and trust Redis to handle it (something the library discourages but @jonhyman appears to have success with), the random delay jitter does sound less than ideal. Some of our scheduled jobs expect to run within seconds of the scheduled time, e.g. to match up with a public countdown on www.kickstarter.com. I know there will always be moments where that doesn't happen, but they're a nice thing to minimize.

**Comment by mperham** [comment]
I'd suggest simply lowering the poll interval to something that makes sense for your usecase.  If you're running 10 Sidekiq processes and want to check every 5 seconds on average, set poll_interval to 50 and you should see more predictable behavior at the expense of a little more Redis overhead.

Limiting to one or two Pollers means that your scheduled jobs are limited to run on just those 1 or 2 processes which limits your concurrency.  Typically ok with light load but not if you schedule many thousands of jobs.

**Comment by cainlevy** [comment]
>  If you're running 10 Sidekiq processes and want to check every 5 seconds on average, set poll_interval to 50 and you should see more predictable behavior at the expense of a little more Redis overhead.

Would you be open to making that target number configurable while still reusing Sidekiq's `ProcessSet.new.size` logic? Something like [`pcount * Sidekiq.options[:foo]`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L90)?

> Limiting to one or two Pollers means that your scheduled jobs are limited to run on just those 1 or 2 processes which limits your concurrency. Typically ok with light load but not if you schedule many thousands of jobs.

True. The ideal setup would probably vary for each application, which is why I find the option to control how many Pollers are running so appealing. The bulk of our jobs are unscheduled, and we've been well served by a single resque-scheduler process so far.

**Comment by mperham** [comment]
Side note: I'd like to deprecate `poll_interval` option because it's unwieldy and tough for users to understand.  I'd like to use `average_scheduled_poll_check` (better name?) instead where the user just says "I want to check every 5 seconds on average" and Sidekiq uses the process count to calculate the equivalent poll_interval internally.

I'd be happy to get a PR from you with your suggested changes.  I think it wouldn't be too much work to get something concrete to discuss.

**Comment by wyaeld** [comment]
I'm :+1: on `average_scheduled_poll_check` being the api.  Its a lot clearer to understand, and I've seen people get tripped up with the current.

**Comment by cainlevy** [comment]
long live `Sidekiq.average_scheduled_poll_interval`
