### ISSUE TITLE
on_complete intermittently not being called?

### ISSUE THREAD

**Issue by trdinich** [mperham/sidekiq#2318]
sidekiq (3.2.3)
sidekiq-middleware (0.3.0)
sidekiq-pro (1.7.6)

I have a batch worker job that does a push bulk on ~1,000 small jobs, with on_complete defined to finish up the work.  On somewhat rare occasion (something like 2% of the time), the push_bulk is called, all of the jobs seemingly run, but on_complete is never called.  At first I didn't believe this, but I put in logging immediately before/after the push_bulk as well as in the first line of on_complete.

Do you know of any reason why on_complete could fail to be called?  I could buy some sort of out of memory situation, but I certainly haven't been able to narrow it to that based on everything I'm seeing on the box.

**Comment by mperham** [comment]
I can't think of any issue that might cause this to happen.  If you can upgrade, you might `bundle update sidekiq-pro` to pick up any possible fixes.

**Comment by trdinich** [comment]
fair enough, thanks for the quick reply.  If I find anything I'll reopen and discuss.

**Comment by webandtech** [comment]
I've ran into issues with custom middleware, including gems such as sidekiq-unique-jobs which will silently chuck jobs in the round file.
