### ISSUE TITLE
reload schedules

### ISSUE THREAD

**Issue by lechen26** [mperham/sidekiq#2320]
Hi

i'm using Sidekiq 3.1.4 with Sidekiq-scheduler 1.0 with Ruby 2.0 and i'm having issues Reloading my schedules.  my basic sidekiq.rb looks like:
```
   #./sidekiq.rb
   Sidekiq.configure_server do |config|
     config.redis = {  url: 'REDIS_URL', namespace: "sidekiq" , :size => 5}
   end
   Dir["./myworker.rb"].each { |file| require file }
   Sidekiq::Scheduler.dynamic = true
   Sidekiq.schedule = YAML.load_file(File.expand_path('../schedule.yml',__FILE__))
```
```
  #./sidekiq.yml
  :concurrency: 25
  :pidfile: ./sidekiq.pid
  :logfile: ./sidekiq.log
  :queues:
    - default
    - myqueue
```
when loading my schedule from the rakefile using "bundle exec sidekiq -r ./sidekiq.rb -C ./sidekiq.yml -d" i see on the log that it loaded the schedules and he enqueue them according to the cron arguments.

what i dont fully understand is how flexible the scheduling can be. i want to have the ability to update a job, for example argument or different cron time, and want to add additional jobs while system is running, without the need to restart sidekiq process.

found few posts that suggest to search for the jid of the job and update it, although indicate performance issues on that solution.

now i saw on the Sidekiq API that there is a method like "reload_schedule!"
i i've tried  to do something like 
```
   config =  {
        :class => 'MyWorker',
        :cron => '*/1 * * * * ',
        :args => 'myargs'
    }
   Sidekiq.set_schedule('testSystem1',config)
   Sidekiq.reload_schedule!
   schedules =Sidekiq.get_all_schedules
   #does show the new schedule but it doesnt really loaded it for actual work of the workers.
```
i though that i should see on the sidekiq.log something like "Schedule loaded" as it wrote at the startup, and now with the new addition.

any help will be appriciated.

Thanks!

Levi

**Comment by mperham** [comment]
Wrong project, sidekiq-scheduler is a 3rd party gem.
