### ISSUE TITLE
Bulk job scheduling?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [mperham/sidekiq#2321]
Is it possible to more effectively add jobs when they need to be scheduled with an individual offset?

Currently I do:
```ruby
time_frame = 1000
ids_to_be_performed = [1,2,3,4,5,6,7,8,9,10]
time_between_jobs = time_frame / ids_to_be_performed.count

off_set = 0
ids_to_be_performed.each do |id|
  WorkerJob.perform_in(off_set, id)
  off_set += time_between_jobs
end
```
Would I be possible to use the `Sidekiq::Client.push_bulk(sidekiq_item)` in a similar way?

**Comment by mperham** [comment]
There's no way to bulk push jobs which require different scheduled time offsets.  You can bulk push jobs which have the same time offset.
