### ISSUE TITLE
Outdated comments?

### ISSUE THREAD

**Issue by kamen-hursev** [mperham/sidekiq#2324]
I think the comments here: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L559 are not up to date.
Shouldn't it be something like:
```
r = Sidekiq::ScheduledSet.new
r.select do |retri|
  retri.display_class == 'User.setup_new_subscribe' &&
  retri.display_args[0] == 53
end
```
At least when I try to access `job.args` I get an array with one serialized object in it. And as far as I see from the code `display_class` and `display_args` are responsible for de-serializing it. Or am I doing something wrong?

**Comment by mperham** [comment]
The display_* methods are, as the naming suggests, meant for prettier display in the Web UI.  klass and args access the low-level job data and still work as before.  You can use whatever works for your jobs.
