### ISSUE TITLE
Sidekiq::Queue.all is not being mocked in test

### ISSUE THREAD

**Issue by lazywei** [mperham/sidekiq#2325]
Hi,

I've turned on `Sidekiq::Test.inline!`. However, `Sidekiq::Queue.all` is still trying to connect to Redis.
How can I test against `Sidekiq::Queue.all` without mocking Redis?

Thanks

**Comment by mperham** [comment]
The API does not support a testing mode.  What are you trying to test?

**Comment by lazywei** [comment]
I got code like this:

```ruby
        Sidekiq::Queue.all.each do |q|
          q.each do |job|
            job.delete if job.jid == sidekiq_jid
          end
        end
```

somewhere in my model file. The purpose is find the specific job and remove it from the queue.
Is there any proper way to test this? Currently, I mock the `Sidekiq::Queue` myself.

**Comment by aprescott** [comment]
That approach to deleting jobs seems like it's going to lead to a bad time. I think it's generally better to structure things so that the job knows itself when it can complete without performing any work.

**Comment by lazywei** [comment]
@aprescott oh... you're damn right! I can just check if the worker need to skip itself at the very beginning!
Thanks a lot!

**Comment by mperham** [comment]
That'll be horribly slow at scale.  Use the APIs which are designed for JID lookup.

**Comment by lazywei** [comment]
@mperham do you think it is okay if I follow @aprescott 's suggestion -- instead of remove from queue, we just check if the worker need to skip or not?

**Comment by mperham** [comment]
Absolutely that's the best course of action.

**Comment by aprescott** [comment]
Happy to help!
