### ISSUE TITLE
is it possible to export something and download it to client from sidekiq worker

### ISSUE THREAD

**Issue by niuxiufeng** [mperham/sidekiq#2327]
I use rails 4.2 and gem rubyXL to export something
I can download it use send_data in controller without sidekiq

but the data is big and I want to use background job to do it
yesterday i created a job and copied controller code to the job
and i received error like this

2015-04-27T08:27:13.985Z 19847 TID-oxgut0tyk WARN: uninitialized constant ExportInfolocal::DataStreaming

is it possible to download the excel to client from sidekiq ??

thank you very much!

**Comment by davydovanton** [comment]
Hello, I think your problem in `ActionController::DataStreaming#send_data` method.
May be this links will be helpfull for you:
1. [SO question: Break Out File Download into Background Process Using Sidekiq](http://stackoverflow.com/questions/20197779/break-out-file-download-into-background-process-using-sidekiq)
2. [Sidekiq and pdf reports](http://community.gotealeaf.com/t/sidekiq-and-pdf-reports/381/3)

Good luck! :blush:

**Comment by mperham** [comment]
There's no easy solution to this.

You can use something complex like Pusher and web sockets or you can do something simple, like have Sidekiq generate the file to a known path and then have a Rails action which tries to download the file at that path.
