### ISSUE TITLE
Cross-Site Scripting(XSS) issue 

### ISSUE THREAD

**Issue by KelvinLin** [mperham/sidekiq#2330]
when page queues page 
using bellow url will can cause Cross-Site Scripting(XSS) 
`%url%/sidekiq/queues/%3c%69%4d%67%20%53%72%43%3d%78%20%4f%6e%45%72%52%6f%52%3d%61%6c%65%72%74%28%34%38%34%37%33%29%3e`

**Comment by mperham** [comment]
I can't reproduce.  When I hit http://localhost:3000/sidekiq/queues/%3c%69%4d%67%20%53%72%43%3d%78%20%4f%6e%45%72%52%6f%52%3d%61%6c%65%72%74%28%34%38%34%37%33%29%3e I just get an empty page.

For everyone else, the URL is actually `http://localhost:3000/sidekiq/queues/%3CiMg%20SrC%3dx%20OnErRoR%3dalert%2848473%29%3E`

**Comment by mperham** [comment]
Ok, chrome ignored it but firefox reproduced it.

**Comment by KelvinLin** [comment]
Yap Firefox,

**Comment by KelvinLin** [comment]
thank you! is working & more security  now !

**Comment by aprescott** [comment]
In case anyone is wondering, Chrome has some XSS security built into it where it will detect if pieces of the URL show up as HTML/DOM elements. (Not really sure why Firefox doesn't have it...)
