### ISSUE TITLE
Polling removes formatted timestamps

### ISSUE THREAD

**Issue by edwinv** [mperham/sidekiq#2331]
The new polling with AJAX requests has an issue with the timestamps on a page. Normally the timestamps are replaced by a representation like "less than a minute ago". When the page is refreshed by AJAX for the first time, the timestamp representation is not changed and the original timestamp is shown.

![sidekiq_pro](https://cloud.githubusercontent.com/assets/563294/7471388/a1b134be-f326-11e4-96ba-6a4822ea7145.png)

Sidekiq version 3.3.4

**Comment by mperham** [comment]
@davydovanton ?

**Comment by davydovanton** [comment]
As i can see this bug is in pro version. Mike can you show code that is responsible for this?

**Comment by edwinv** [comment]
Issue is also present on "Busy" page, seems not related to the fact that we are using Pro.

**Comment by davydovanton** [comment]
@edwinv yes, you are right. I create PR with fix for this problem

**Comment by edwinv** [comment]
Any news on the release containing this fix?

**Comment by mperham** [comment]
Seems like it's about time for 3.3.5.  Later this week.
