### ISSUE TITLE
Some questions about Batch failure cases

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2333]
I had some questions that the wiki doesn't seem to answer, although I can guess exactly what would happen. I thought I'd open an issue here, get some solid answers, and then incorporate that into the wiki.

Questions are for Sidekiq Pro 2.0+.

A couple of these are related to the 30-day expiration limit, which isn't in the wiki, but is at least [mentioned in the Pro 2.0 upgrade notes](https://github.com/mperham/sidekiq/blob/19ef4722e19c29bd14ee714045fabdcaf10ed6f9/Pro-2.0-Upgrade.md#batch-data).

## Batches with a job that is killed or deleted

Say a batch has 5 jobs and 1 of those jobs fails. Someone goes into the Web UI and deletes the job because the work no longer needs to happen. (Ideally, the job would just know when it can `return` early, but that isn't always the case.)

What happens to the batch? Will the success callback ever fire?

Does the outcome depend on a job being killed vs deleted?

Based on what I've seen, it looks like, the batch information remains in Redis until the 30-day expiration limit, and the success callback will never automatically fires, when a job is killed _or_ deleted. Is there a supported way (API?) to take a batch ID (through the web UI) and force it to trigger its success callback and remove itself from Redis?

## Callback retries

If a batch callback itself errors, does it retry? Based on https://github.com/mperham/sidekiq/issues/1744 I believe the answer is yes, although it isn't in the wiki.

## Batch expiration with a failing job

If a job for a particular batch doesn’t succeed for over 30 days, what happens?

Does the batch data expire from Redis? Does the job itself remain longer than 30 days, continuing to fail? Is it entirely on developers/whoever, to recognise that a job that failed until day 31+ may be part of a batch that no longer exists?

**Comment by mperham** [comment]
Excellent questions.

1. Deleting a job means the batch will never be successful.  If you want this behavior, you'd need to roll it yourself.  I've always pointed people to using [cancellation](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job) instead.
2. Yes, and this is why callbacks were redesigned to be jobs themselves in 2.0 - so they have the same retry safety net as an application job.
3. The default retry is 25 (~21 days).  After 21 days the job will go to the DJQ and likely the batch will expire 9 days later.  The job can be fixed and manually retried from the DJQ but the batch data will not longer exist so the callback job would need to be triggered manually too.

**Comment by aprescott** [comment]
Thanks for the speedy reply!

> Deleting a job means the batch will never be successful. If you want this behavior, you'd need to roll it yourself. I've always pointed people to using cancellation instead since that results in a "success".
>
> [...]
>
> The job can be fixed and manually retried from the DJQ but the batch data will no longer exist so the callback job would need to be triggered manually too.

I'm super not-inclined to start layering custom batch callback logic on top of what Sidekiq Pro gives us, but the way I've been tackling this problem right now is to manually read the code for a batch callback and then manually execute the correct stuff in a console. A lot of the time, though, the batch then sticks around in Redis (and the web UI) for 20+ days after I've already addressed the problem. Is there a good way to avoid that?

Based on the API I can see in the current [Batches wiki page](https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch), I can take a batch ID from the web UI and get a new `Batch` object easily enough:

```ruby
batch = Sidekiq::Batch.new(some_batch_id)
```

But I guess there's no way to do something like `bid.trigger_success_callback` to force the success callback to fire?

It looks like there is `batch.invalidate_all` — I assume if there are no more jobs for a batch, then invalidating just removes batch data from Redis? That would at least let me clear out clutter for batches I know don't have anymore jobs.

**Comment by aprescott** [comment]
I guess for my question to make sense I need to justify not having "self-cancelling" jobs. Most of the time, jobs will happily take care of themselves and return early or whatever, but in a few cases something exceptional can happen which we'd rather require manual intervention because it isn't always obvious what caused the problem.

Having said all that, the batch data sticking around for at most 2-3 weeks isn't a huge deal, it can just lead to some confusion about what has and hasn't been addressed manually.

**Comment by mperham** [comment]
> A lot of the time, though, the batch then sticks around in Redis (and the web UI) for 20+ days after I've already addressed the problem. Is there a good way to avoid that?

`Sidekiq::Batch::Status.new(bid).delete` will prune all data about the batch from Redis.  This is what Sidekiq Pro runs when the success callback completes.

Invalidating is how you cancel one or more jobs in a batch so those jobs don't do any work. I believe the calbacks would still fire though.  Perhaps instead of deleting a batch job, you could invalidate it?  Invalidation does require your job to call `valid_within_batch?` https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch

I've been conservative around this area because I'd rather have the developer perform manual data repair than for Sidekiq to be "smart" and accidentally do the wrong thing.

**Comment by aprescott** [comment]
`delete` looks like the thing I want, as long as it's an API intended to be used outside of the Pro codebase.

> I've been conservative around this area because I'd rather have the developer perform manual data repair than for Sidekiq to be "smart" and accidentally do the wrong thing.

Huge +1!

**Comment by mperham** [comment]
Yeah, delete is meant for those very rare cases where you want to clean up a batch for some reason.

**Comment by aprescott** [comment]
Finally got around to adding this to the Batches wiki page. Thanks again!
