### ISSUE TITLE
Failures but no failures?

### ISSUE THREAD

**Issue by bbialek-raise** [mperham/sidekiq#2334]
I'm running Sidekiq v3.3.2.  The UI reports lots of Failed jobs but the Failures tab has no description of a single one of them... What have I missed configured?
![failed_failures](https://cloud.githubusercontent.com/assets/9676972/7495253/74b70004-f3d2-11e4-92b3-a525e003a8ca.png)

**Comment by johnathanludwig** [comment]
Check the dead job section. If nothing is there then you have jobs that are failing initially but end up finishing when retried. You can check the logs or add an error handler to capture the errors and report them to you as mentioned here: [Error-Handling](https://github.com/mperham/sidekiq/wiki/Error-Handling)

I use [Bugsnag](www.bugsnag.com) and it works great.

**Comment by mperham** [comment]
The failures tab is not part of Sidekiq, it is part of the sidekiq-failures gem.

If a job raises an error when run, Sidekiq increments "Failed" and moves the job to the Retries tab (i.e. jobs to be retried in the future).

**Comment by bbialek-raise** [comment]
Thanks!  I'll read up on sidekiq-failures.
