### ISSUE TITLE
Fake testing & batches

### ISSUE THREAD

**Issue by mikz** [mperham/sidekiq#2336]
Given following code:

```ruby
require 'sidekiq-pro'
require 'sidekiq/testing'
 
class Worker
  include Sidekiq::Worker
  
  def self.enqueue
    batch = Sidekiq::Batch.new
    batch.description = 'test batch'
    
    batch.jobs do
      perform_async self
    end
  end
  
  
  def perform(*)
    batch.jobs do
      raise 'expected error'
    end
  end
end
 
Worker.enqueue
Worker.perform_one
```

Raising 'expected error' is expected, but `NoMethodError: undefined method 'jobs' for nil:NilClass` is raised instead.

Why? Looks like `Sidekiq::Testing.fake!` [does set just `jid` of the job, not `bid`](https://github.com/mperham/sidekiq/blob/19ef4722e19c29bd14ee714045fabdcaf10ed6f9/lib/sidekiq/testing.rb#L164).

Suggested solution: initialize both `jid`  and `bid` if available. I know batches testing is not exactly supported, but this breaks it hard.

Or do you have some suggestion how to implement it differently so it is testable ?
Inside the job, I'd like to enqueue more jobs to the batch.

**Comment by mperham** [comment]
Sounds good.  PR?

**Comment by mikz** [comment]
@mperham ok! Will do.
