### ISSUE TITLE
Document ability for custom retry delay to fallback to default implementation

### ISSUE THREAD

**Issue by brittlewis12** [mperham/sidekiq#2338]
I'd like to discuss the idea of documenting and officially supporting the ability to fall back from a custom `sidekiq_retry_in` to the default implementation. This already works today, albeit with a questionable interface. The current implementation of `Sidekiq::Middleware::Server#delay_for` reads the worker's `sidekiq_retry_in_block` property and, if present, calls the block, otherwise calling `#seconds_to_delay`. The `||` allows for the block to return a falsy value to achieve the desired outcome.

The use case that I've found for this involves wanting to insert an arbitrary, large delay after `n` number of retries, but otherwise use the nice exponential backing off that comes for free with retries. So effectively, let's say after it fails 10 times, I want to wait 10 hours, and otherwise continue the normal delay strategy for all retries before and after the 10th.

What do you all think? Is this intentionally undocumented? Is this an inappropriate use of the block's return value? Would you like to support this with a different API? The smallest change would be to update the wiki's copy from saying the block must return an integer to saying an integer or `false` for the fall back, but I understand if you'd like to approach it differently (read, more robustly).

**Comment by mperham** [comment]
This is way too "edge-casey" for me to want to expand the documentation to cover it.  It's not relevant to 99% of Sidekiq users.
