### ISSUE TITLE
Is there a central place to find the status of the job via job_id?

### ISSUE THREAD

**Issue by joshidhruv** [mperham/sidekiq#2339]
I have a app where I am running sidekiq jobs multiple time. Before I start new method I wanted to make sure if the status of the job is done(finished). I have looked at the sidekiq_status gem but even if gives me status I dont have the job id.

This is what I am trying to do.
       I wanted to check if anyjob is running currently and if it is I wanted to know its name.

Thanks,
Dhruv

**Comment by mperham** [comment]
There is no way to get the status of a job from JID.  This is by design.
