### ISSUE TITLE
Question: Can you mix 'Strict queue ordering algorithm' with 'Weighted random algorithm'

### ISSUE THREAD

**Issue by comjf** [mperham/sidekiq#2342]
Quick question, Can you mix 'Strict queue ordering algorithm' with 'Weighted random algorithm' in regards to the Fetch algorithms.

Example, sidekiq.yml
:queues:
  - [mailer]
  - [high, 10]
  - [backend, 1]
  - [medium, 5]

Would this first run everything in the mailer group, then create the random set of 16 items to select the next priority?

Thanks!

**Comment by mperham** [comment]
Nope, mailer will get a default weight of 1.
