### ISSUE TITLE
Include no-timestamp log option?

### ISSUE THREAD

**Issue by aripollak** [mperham/sidekiq#2343]
We already get microsecond-precision timestamps out of the Heroku logplex, so recording the timestamp again from Sidekiq just adds unnecessary verbosity. We've been doing this in an initializer instead, but it might be nice to include it as an option for other people in a similar situation. If including it isn't desirable for some reason, I'd be happy to add this to the wiki.

```ruby
class SidekiqLoggerWithoutTime < Sidekiq::Logging::Pretty
  def call(severity, time, program_name, message)
    "#{::Process.pid} TID-#{Thread.current.object_id.to_s(36)}#{context} #{severity}: #{message}\n"
  end
end

Sidekiq.logger.formatter = SidekiqLoggerWithoutTime.new
```

**Comment by jonhyman** [comment]
Imo seems like being able to inject the formatter, per the current design,
seems like the right level of control for others in a similar situation
rather than bloating with more options.

**Comment by mperham** [comment]
I'd consider a PR which special-cases Heroku and removes the timestamp from the default logger.
