### ISSUE TITLE
Display callback information for a batch

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2347]
You can view information for a batch in the web UI:

![screen shot 2015-05-13 at 11 34 08](https://cloud.githubusercontent.com/assets/342081/7614331/19e66498-f964-11e4-8284-9c214b0b1165.png)

However, if the batch has any callback configuration, you can't see it in this table. For example, if the batch has an `on(:success, ...)`:

```ruby
batch.on(:success, FooJob, "user_id" => user_id)
```

It would be good to see that there are args `"user_id" => 4567` associated with this batch data.

Is that possible?

**Comment by mperham** [comment]
Absolutely.  :+1:

**Comment by mperham** [comment]
Trying to figure out the best way to display the data in a table.

![screen shot 2015-05-13 at 09 52 32](https://cloud.githubusercontent.com/assets/2911/7615970/f7759c3e-f955-11e4-99d0-fb8e8d233533.png)

**Comment by mperham** [comment]
Maybe different "Success" and "Complete" rows instead of a single "Callbacks" row?

**Comment by aprescott** [comment]
Different rows sounds reasonable, yeah. Makes it clear when there's, say, no complete callback.

**Comment by mperham** [comment]
![screen shot 2015-05-13 at 10 21 14](https://cloud.githubusercontent.com/assets/2911/7616521/d1d9db3a-f959-11e4-84a7-0d08605f8352.png)

**Comment by aprescott** [comment]
Looks great to me!

**Comment by mperham** [comment]
Fixed and 2.0.3 released.
