### ISSUE TITLE
Display private queues on web UI?

### ISSUE THREAD

**Issue by johnathanludwig** [mperham/sidekiq#2348]
We recently ran into an issue where jobs for batches were being "lost". Turned out to be autoscaling killing servers and Sidekiq was not being sent the proper signals to requeue its jobs (we are using reliable fetch so they are in the private queues). It took a bit of digging to figure out what was going on since no errors were being thrown and the web UI was empty.

Something on the UI side would make it eastier to track down issues like this. Could the UI have a separate section that shows the private queues used by reliable fetch and the jobs in it? On top of that, possibly a button to move the job back to its original queue so we could recover a job? We are using AWS so the hostname is the private IP of the server. So once it is terminated it is near impossible to get a new one with the same hostname.

**Comment by mperham** [comment]
Private queues use the same naming scheme as public queues "queue:#{name}" with a suffix.  You can use Redis's KEYS command to iterate over that keyspace and introspect any old private queues.

I'm not sure how this would fit into the current Web UI, given it's likely to cause more confusion than solve problems. ("What's a private queue?", "Why are these jobs here?")

**Comment by mperham** [comment]
But yeah, autoscaling is a common source of "lost" jobs if not done carefully.

**Comment by johnathanludwig** [comment]
Yeah, I used redis.keys confirm what was happening to the jobs, but I was less sure about how to properly move them and not mess anything up. 

Sounds like it would better fit as an extension then. Thanks for the input!

**Comment by jonhyman** [comment]
We have a monitor which runs every 30 minutes and checks all the reliable
queues using SCAN, stashes what they're working on, and inspects it against
what it found the last time it ran. I wrote it after we had this exact
issue with autoscaling our workers. It's also extremely helpful as a stuck
jobs monitor. I'd recommend writing something like that. Happy to provide a
sample gist when I get to a computer if it's helpful.

**Comment by johnathanludwig** [comment]
Yes, that would be great @jonhyman.

**Comment by jonhyman** [comment]
Take a look at https://gist.github.com/jonhyman/7c488e7091a9e7bc03e2.
