### ISSUE TITLE
Feature Suggestion: delete batches from Web UI

### ISSUE THREAD

**Issue by mikz** [mperham/sidekiq#2351]
I created few batches, that had two jobs. 
One job was failing, so I deleted the retries because it would never succeed.

However, now I have batches, that say they have 1 pending job.
I tried `invalidate_all` without success. And from inspecting the code, there is a way to delete a batch, but it is not accessible from the web.

It would be pretty nice to do so from the web ui.

**Comment by aprescott** [comment]
I touched on this same problem in #2333. I believe `delete` is what you're after.

(Sorry for not yet having time to update the wiki with those answers!)

**Comment by mikz** [comment]
Yes. In the end I found `delete`. But copying ids from web to console is not very pleasant. Having a button for that would be nice.

**Comment by mperham** [comment]
I'm not sure I want to expose this in the Web UI.  Too easy to delete one and then realize you needed it.  I'll consider it.  Other opinions?

**Comment by mikz** [comment]
There is button to delete a queue. Which is probably more dangerous. Maybe just sufficient protection from doing it by mistake would be enough?

Would it be feasible to do as a plugin?

**Comment by mperham** [comment]
I don't want Batches to be deletable via UI.  If Batches are lingering, there's a problem that needs to be diagnosed and fixed.  It is not a good idea to make this problem easy to paper over.

For the record, you can delete a batch via API with `Sidekiq::Batch::Status.new(bid).delete`
