### ISSUE TITLE
Lateness?

### ISSUE THREAD

**Issue by L-Oto** [mperham/sidekiq#2354]
Hello,

I'm observing lateness with my Sidekiq queue (v3.3.0): I'm using the perfom_at to schedule tasks at a precise moment. Unfortunately, the task are processed with delay.

On my local machine, I measured at most 15 seconds between the time I set in the perfom_at and the moment the task was actually being executed. The lateness varies the shortest delay I measured was 5 seconds.

Does Sidekiq in optimal conditions guarantee any job to be processed on time?
If not what would be a safe margin?
Can it be related to my settings? I'm new to Sidekiq.

Thank you!

**Comment by mperham** [comment]
Have you read the scheduled jobs wiki page?

**Comment by L-Oto** [comment]
I did by unfortunately I found no answer there.

**Comment by L-Oto** [comment]
My Rspec are all green, every scheduled job has the right trigger date. This is why I'm asking for help.

**Comment by mperham** [comment]
You're right, it's not explained explicitly but Sidekiq by default checks every 15 seconds so scheduled jobs aren't accurate to the second. The scheduled time is the earliest time at which the job might execute.

**Comment by L-Oto** [comment]
In my project, is it somehow possible to increase the frequency of the checks without compromising Sidekiq?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs#checking-for-new-jobs
