### ISSUE TITLE
Add Sidekiq gem's metadata on rubygems.org

### ISSUE THREAD

**Issue by JuanitoFatas** [mperham/sidekiq#2355]
Hello Sidekiq,

Could you please fill metadata information in sidekiq's page on rubygems.org

https://rubygems.org/gems/sidekiq/edit

Here are my suggestions:

| URL                   | VALUE                                     |
| --------------------- | ----------------------------------------- |
| **Source Code URL**   | https://github.com/mperham/sidekiq        |
| **Documentation URL** | http://www.rubydoc.info/gems/sidekiq      |
| **Wiki URL**          | https://github.com/mperham/sidekiq/wiki   |
| **Mailing List URL**  | https://gitter.im/mperham/sidekiq         |
| **Bug Tracker URL**   | https://github.com/mperham/sidekiq/issues |

Thank you!

**Comment by mperham** [comment]
I'd love to get a PR with gemspec updates.

**Comment by JuanitoFatas** [comment]
OK. Will do!

**Comment by davydovanton** [comment]
@JuanitoFatas I think that you need change mailing list URL to https://groups.google.com/forum/?fromgroups#!forum/sidekiq :smiley:

**Comment by JuanitoFatas** [comment]
> I'd love to get a PR with gemspec updates.

Sorry Mike, just recall that currently `.gemspec` cannot specify these metadata. Please see (and help push :blush:) rubygems/rubygems.org#718 & rubygems/rubygems.org#724. So will need to trouble you to manually update these on https://rubygems.org/gems/sidekiq/edit.

> I think that you need change mailing list URL to https://groups.google.com/forum/?fromgroups#!forum/sidekiq

Awww. From the README, I see it mentioned gitter first.

> mperham/sidekiq on Gitter is dedicated to this project

I thought this is now preferred way of communication. Leave Mike to decide then. Thank you.

**Comment by mperham** [comment]
Updated mailing list and wiki. Any others?  Gitter is really unofficial since I don't pay attention to it.

**Comment by davydovanton** [comment]
Mike, I think you forget add bug tracker link :sweat:

**Comment by JuanitoFatas** [comment]
All good now! Thanks Mike and Anton!

**Comment by davydovanton** [comment]
thanks you too :+1:
