### ISSUE TITLE
Starting Sidekiq with namespace causes jobs not to be started

### ISSUE THREAD

**Issue by firefueled** [mperham/sidekiq#2357]
Sorry if I'm not understanding how Sidekiq should work with multiple instances.

I have two separate rails apps and I want them to use their own Sidekiq instance, but the same Redis server, that's running on localhost. I've scoured the internet and I've found that the proper way to do this is by having the two Sidekiq instances connect to Redis using different namespaces. I can start the instances properly but I cannot succesfuly launch jobs on them.

Whenever I call them, they show up under the Enqueued section on the Sidekiq web interface, but never get started.
This doesn't happen if I start Sidekiq without a namespaced Redis connection.

Do I have to pass some special namespace parameter to perform_async if I start Sidekiq on a namespaced Redis connection?

I'm williing to change my Sidekiq/Redis installation/configuration if there's a easier/better way to accomplish this. 

thanks

**Comment by mperham** [comment]
How are you starting Sidekiq?  Show us your initializer?

**Comment by Slpk** [comment]
I tried using [this] (https://gist.github.com/CD1212/5326706) coupled with the initializer

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: "app_name" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://locahost:6379/0', namespace: "app_name" }
end
```

and configuration `:concurrency: 5`

Thanks for helping!

**Comment by mperham** [comment]
That seems fine.  I'm not sure why it's not working.
