### ISSUE TITLE
`.sidekiq_options` with ActiveJob?

### ISSUE THREAD

**Issue by rmosolgo** [mperham/sidekiq#2358]
Hi,

Thanks for your great work with this gem! Switching to sidekiq has been a big win. 

We're also using ActiveJob. I'm interested in using [`sidekiq-throttler`](https://github.com/gevans/sidekiq-throttler) which depends on calling `sidekiq_options` in the Job definition. However, if the Job extends `ActiveJob::Base`, there's no such method `sidekiq_options`. Starting Sidekiq raised this error:

```
undefined method `sidekiq_options' for UpdatePeopleJob:Class
/app/jobs/update_people_job.rb:4:in `<class:UpdatePeopleJob>'
```
 
First, I checked the [wiki page for Active Job](https://github.com/mperham/sidekiq/wiki/Active-Job), but didn't see any explicit mention of `sidekiq_options`.

Then, I took a shot in the dark and just included `Sidekiq::Worker` in the Job. There wasn't a `undefined method` error, but it also didn't seem to heed the options I passed. 

Is there a way to use `sidekiq_options` _and_ ActiveJob?

In the meantime, I've made this particular job `include Sidekiq::Worker` instead of extending `ActiveJob::Base`.

Thanks!

**Comment by mperham** [comment]
If you want to customize your sidekick options you have to use a sidekick specific worker.  I don't believe there's any way to make it work with active job although I could be proven wrong.

**Comment by rmosolgo** [comment]
:+1: well there's that!

**Comment by muriloime** [comment]
For those coming here recently, afaik this is now possible in 6.0 version as per https://github.com/mperham/sidekiq/blob/master/Changes.md
