### ISSUE TITLE
Timestamp format changes when polling the busy page in the web UI

### ISSUE THREAD

**Issue by AlexWiles** [mperham/sidekiq#2359]
Just upgraded to 3.3.4
When live polling the busy page with the web UI, the started timestamp in the busy jobs table changes from the "less than a minute ago" style to the "2015-05-18 17:50:22 +0000" style after the first update. Also seeing this in the retry queue. I find the human readable timestamp syntax to be very useful and it would be nice to have along with the sweet new ajax polling.

**Comment by davydovanton** [comment]
Hello, please use master branch. I fixed this some times ago in #2331

**Comment by AlexWiles** [comment]
Oops I missed that. Thanks!

**Comment by davydovanton** [comment]
you are welcome :smiley:
