### ISSUE TITLE
Sidekiq upstrat script can't find bundler

### ISSUE THREAD

**Issue by THPubs** [mperham/sidekiq#2361]
The upstart script (https://github.com/mperham/sidekiq/blob/master/examples/upstart/manage-one/sidekiq.conf) can't find the bundler and always crash. After searching for several hours I found the solution in here :

http://stackoverflow.com/questions/26439555/did-upstart-or-bash-scripts-change-on-ubuntu-14-04-trying-to-boot-sidekiq-with

The selected answer is the solution. Please update the script :-)

**Comment by mperham** [comment]
You update the script. This is open source and we accept pull requests. :-)
