### ISSUE TITLE
Question: ActionMailer delay during redis multi-az failover (read only state)

### ISSUE THREAD

**Issue by rosskevin** [mperham/sidekiq#2362]
We plan to use Sidekick Pro, if that would make a difference with the circumstances below.

**Assumption:**
Using AWS Multi-AZ ElastiCache for redis

**Background:**
During a failover, redis will become read-only for a short period of time, disallowing queuing of jobs. I realize this time is likely to be short, but it is important for our business case to not lose emails and we would like to use the `delay` functionality as a default.

**Scenario:**
For most of our jobs, failing to enqueue for a brief period of time, even up to a few hours, will not be a problem.  The problem comes into play when we would not be able to `delay` an email.  It would likely be very difficult for us to find/recover/resend emails that failed to enqueue.  I think it would be acceptable for this brief period where if `delay` failed to enqueue, it would _failover_ and directly call `deliver` on the caller's thread. 

**Question:**
1.  Has anyone else considered this case?  How did you handle it?
2.  Would a `delay` fallback to `deliver` make sense?

**Comment by mperham** [comment]
Sidekiq Pro's reliable push should handle the case where the server becomes read-only for a transient period.  It will catch the exception raised and enqueue the job to be delivered later.  It's designed to provide a catch-all backup for any short-term networking / redis errors which might pop up.
