### ISSUE TITLE
Batches in tests

### ISSUE THREAD

**Issue by edwinv** [mperham/sidekiq#2363]
We are using batches for our jobs and test the scheduling of jobs through Rspec. `Sidekiq::Testing.fake!` is our default test method, in other cases we use the `inline!` method. In both cases, no Redis connection is required.

When we want to use a batch to schedule the jobs, suddenly we need a valid Redis connection. This resulted in an error because we didn't configure a Redis connection in our test environment because we never needed this. Easy to solve, but I'm wondering if it is correct to depend on a Redis connection when no job scheduling in Redis is done.

Maybe the batch feature should also skip the creation of batches in Redis when `Sidekiq::Testing` is enabled?

**Comment by mperham** [comment]
Should be as simple as throwing this in `spec/support/`:

```ruby
class Sidekiq::Batch
  def jobs
    yield
  end
end
```

rspec-sidekiq also has some support for Batches in test mode although I've never used it.

**Comment by aprescott** [comment]
I was wondering why I've never encountered this in our test suite. I think the reason might be that, before we started using Sidekiq, we added `fakeredis` from a separate feature requirement. It is a drop-in replacement that fakes out Redis access (no configuration required!).

We use `rspec-sidekiq` but I don't believe it has batch support. To test batches we directly call `FooJob.new.on_success(double, "x" => "y")` to simulate the callback completion in the test.

Maybe you can add `fakeredis`?

**Comment by greganswer** [comment]
Here's what I did to get my unit tests to pass in RSpec:

```ruby
RSpec.describe SomeBatchWorker do
  describe '#perform_async' do
    let(:batch) { instance_double(Sidekiq::Batch) }

    before do
      allow(Sidekiq::Batch).to receive(:new).and_return(batch)
      allow(batch).to receive_messages([:description=, :on])
      allow(batch).to receive(:jobs) { |&block| block.call }
    end
  
    # RSpec examples here...
  end
end
```

**Comment by Aeon** [comment]
Hi @mperham, just wondering, is this the blessed way to deal with testing with Batch, and if so, should this be in the Batch wiki page?
