### ISSUE TITLE
Rails mailer ignores attachments when using sidekiq

### ISSUE THREAD

**Issue by thisisole** [mperham/sidekiq#2366]
dont know if this is a sidekiq-problem, but if i am using sidekiq, my attachments are ignored.

http://stackoverflow.com/questions/30368194/rails-mailer-ignores-attachment-when-using-deliver-later-with-sidekiq

**Comment by mperham** [comment]
Let's stick with SO.

**Comment by charlieshort** [comment]
@thisisole i'm having the same issue but can't determine the solution. Please could you explain?

**Comment by thisisole** [comment]
sorry, didnt get this message... dont know if you still have this problem. My problem was that I had to restart the sidekiq-queues and my problem was solved.
