### ISSUE TITLE
Is sidekiq not suitable for frequent jobs ?

### ISSUE THREAD

**Issue by nikolay211** [mperham/sidekiq#2367]
Hi, 

I'm recently developing a e-commerce platform and planning to use sidekiq for background jobs. 

So I have initially configured and created some worker. 

The problem for me is that it's not performing well. The worker is about to upload posting to facebook but it works well for the first time and if I repeat same action again sooner, it's not likely to be performing. 

I couldn't find any error log about it and It wasn't seemed to be calling the worker.

I inspected through web UI and it's still counted under <Processed> statistics in dashboard but actually, the worker didn't run. 

I really can't find any clue how this's happening and if anyone here can guide me to track it or hopefully can help me to find it, I'd appreciate it. 

Thanks in advance.

**Comment by mperham** [comment]
Sidekiq is well suited to frequent jobs, I know of users pumping thousands of jobs per second through Sidekiq.

That said, there's not much to go on here.  This sounds like an application issue that you need to spend more time tracking down and understanding.
