### ISSUE TITLE
Sidekiq process dies silently

### ISSUE THREAD

**Issue by mbajur** [mperham/sidekiq#2368]
Hello
i'm using sidekiq in a lot of my apps and that's a first time i've encountered such issue. 

I'm deploying my app using mina (kind of like capistrano) which has a sidekiq plugin which i'm using. After each deploy, sidekiq is being restarted and it works for about 10 minutes without any issues and processing jobs, than the process gets killed and there is no info in the logs, syslogs nor anywhere (or maybe i just don't know where to look).

The sidekiq process is initialized with the following command ([check it here](https://github.com/Mic92/mina-sidekiq/blob/master/lib/mina_sidekiq/tasks.rb#L11)):

    bundle exec sidekiq -d -e #{rails_env} -C #{sidekiq_config} -i #{idx} -P #{pid_file} -L #{sidekiq_log}]

Can you advice me on how i can actually know what's going on and why that process is being killed? What can i do about it?

* ruby 2.2.1
* sidekiq 3.2.6

Thanks!

**Comment by mperham** [comment]
Maybe this? https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-disappearing

**Comment by mbajur** [comment]
Yeah that's totally possible, my VPS has just 512 MB of RAM. I've enabled a swap and now waiting for the results. Will let you know.

**Comment by mbajur** [comment]
It seems that was it. Thank you!

**Comment by rahulmurkute-tudip** [comment]
This is my script in deploy.rb

namespace :sidekiq do
  task :quiet do
    on roles(:app) do
      execute "pgrep -f 'sidekiq'| xargs kill  -USR1"
    end
  end
  task :restart do
    on roles(:app) do
      execute "cd #{current_path} bundle exec sidekiq -C config/sidekiq.yml -d"
    end
  end
end

after 'deploy:starting', 'sidekiq:quiet'
after 'deploy:reverted', 'sidekiq:restart'
after 'deploy:published', 'sidekiq:restart'

My sidekiq process is killed after some seconds , I continuously hit the " ps aux|grep 'sidekiq' " on server while deploying. Then I noticed the process id is generated but after few seconds it disappear. 

I check the ram and cpu usage that is not a issue.

Any help would be appreciated.
