### ISSUE TITLE
Sidekiq not "in sync" with Rails

### ISSUE THREAD

**Issue by tibra** [mperham/sidekiq#2371]
Hello Sidekiq-Team,

a problem we're experiencing frequently is that our Sidekiq instance is getting "out of sync" with a Rails instance. For example, when using Capistrano which creates distinct "releases" directories for each deployment, Sidekiq is trying to access an old (and sometimes already deleted) directory causing weird "MissingTemplate" errors. 
Nevertheless, the currently deployed Rails application pushes jobs successfully into the Sidekiq queue, but when Sidekiq tries to execute, it looks for files in an old releases directory. On a `cap deploy:restart`, we both restart our app workers (unicorn) as well as Sidekiq. I'm sure this is a problem on our side and we're approaching something in a non-standard way.
We're restarting sidekiq by executing 
```
kill -USR2 `cat <%=shared_path%>/pids/sidekiq.pid`
```

I'd be happy getting some tips on where to look for a probable cause. Do you have any ideas?
Thank you!

**Comment by mperham** [comment]
Is this an issue for Capistrano-sidekiq? Sidekiq doesn't know anything about cap.

**Comment by tibra** [comment]
Thanks for the fast reply! We're not using Capistrano-Sidekiq since we're starting, stopping, and restarting Sidekiq on our own. This is the restart script:
```
kill -USR2 `cat <%=shared_path%>/pids/sidekiq.pid`
``
This is the start script:
```
<%= wrapper_dir %>/bundle exec sidekiq --index 0 -C config/sidekiq.yml --environment <%=rails_env%> --logfile <%=shared_path%>/log/sidekiq.log -d
```

We're doing this because Monit is watching Sidekiq and we thus have a single place to execute stopping, starting, and restarting. On deploy:restart we simply run the scripts via Capistrano:
```
task :restart, :except => { :no_release => true } do
   puts "\n\n=== Executing restart script ===\n\n"
   run "#{shared_path}/scripts/restart.sh"
   run "#{shared_path}/scripts/restart_sidekiq.sh"
end
```

**Comment by mperham** [comment]
Usr2 does not do what you think it does. Review the Signals wiki page.

**Comment by tibra** [comment]
Thank you, Mike :-)
