### ISSUE TITLE
Sidekiq does not support keyword arguments

### ISSUE THREAD

**Issue by richardjortega** [mperham/sidekiq#2372]
First off, thank you for Sidekiq! Hopefully this issue is a valid one. 

### Problem
Sidekiq does not seem to support keyword arguments for its worker `perform` method. Ruby introduced in 2.0 the ability to do *keyword arguments* and in 2.1 provide a way to do *required keyword arguments*. It does not seem to accept **required keyword arguments** which are expressed via `keyword_argument:` with the trailing colon.

Note: Possibly changing to double spat operator `**` may solve this issue.

### Analysis
Below is code and backtrace showing that when you run `perform_async` you'll get an `ArgumentError: wrong number of arguments (1 for 0)`. This only occurs when running with `perform_async`, separately I ran it with `Worker.new.perform arguments` and it was fine but that's synchronously so not sure if it's related to how it's sent/retrieved from Redis after.

For now, I just use old syntax for method arguments as workaround.

### Version info
- Rails: 4.2.1
- Ruby: 2.2.2p95
- Sidekiq: 3.3.4
- Redis: 3.0.1
- Docker 1.6
- CentOS 7.1

### Code (which won't work)
```ruby
class TestWorker
  include Sidekiq::Worker
  sidekiq_options queue: :default, retry: false, backtrace: true

  def perform required_keyword_argument:, another_keyword_argument: 'test'
    begin
      puts required_keyword_argument
      puts another_keyword_argument
    rescue => ex
      logger.info ex.message
      logger.info ex.backtrace.join("\n")
    end
  end
end

TestWorker.perform_async(required_keyword_argument: 'test_string', another_keyword_argument: 'test_2_string')
```

#### Backtrace
```
worker_1      | 2015-06-01T22:46:38.601Z 1 TID-ori7rdvmg TestWorker JID-fb882113cd4c899f048d1855 INFO: start
worker_1      | 2015-06-01T22:46:38.602Z 1 TID-ori7rdvmg TestWorker JID-fb882113cd4c899f048d1855 INFO: fail: 0.001 sec
worker_1      | 2015-06-01T22:46:38.603Z 1 TID-ori7rdvmg WARN: {"class"=>"TestWorker", "args"=>[{"required_keyword_argument"=>"test_string", "another_keyword_argument"=>"test_2_string"}], "retry"=>false, "queue"=>"default", "backtrace"=>true, "jid"=>"fb882113cd4c899f048d1855", "enqueued_at"=>1433198798.593975, "error_message"=>"wrong number of arguments (1 for 0)", "error_class"=>"ArgumentError", "processor"=>"732b5246d3e5:1", "failed_at"=>1433198798.6015728, "error_backtrace"=>["/usr/src/app/app/workers/test_worker.rb:5:in `perform'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:75:in `execute_job'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-failures-0.4.3/lib/sidekiq/failures/middleware.rb:9:in `call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/logging.rb:24:in `with_context'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:11:in `call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `call'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `invoke'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:51:in `block in process'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:98:in `stats'", "/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:50:in `process'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'", "/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'"]}
worker_1      | 2015-06-01T22:46:38.603Z 1 TID-ori7rdvmg WARN: wrong number of arguments (1 for 0)
worker_1      | 2015-06-01T22:46:38.603Z 1 TID-ori7rdvmg WARN: /usr/src/app/app/workers/test_worker.rb:5:in `perform'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:75:in `execute_job'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-failures-0.4.3/lib/sidekiq/failures/middleware.rb:9:in `call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/logging.rb:24:in `with_context'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:11:in `call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `call'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `invoke'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:51:in `block in process'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:98:in `stats'
worker_1      | /usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:50:in `process'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
worker_1      | /usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
worker_1      | 2015-06-01 22:46:38.603 [ERROR] Actor crashed!
worker_1      | ArgumentError: wrong number of arguments (1 for 0)
worker_1      | 	/usr/src/app/app/workers/test_worker.rb:5:in `perform'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:75:in `execute_job'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-failures-0.4.3/lib/sidekiq/failures/middleware.rb:9:in `call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/logging.rb:24:in `with_context'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/server/logging.rb:11:in `call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `call'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/middleware/chain.rb:132:in `invoke'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:51:in `block in process'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:98:in `stats'
worker_1      | 	/usr/local/bundle/gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:50:in `process'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
worker_1      | 	/usr/local/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create' (pid:1)
```

### Code (will work)
```ruby
class TestWorker
  include Sidekiq::Worker
  sidekiq_options queue: :default, retry: false, backtrace: true

  def perform required_keyword_argument, another_keyword_argument = 'test'
    begin
      puts required_keyword_argument
      puts another_keyword_argument
    rescue => ex
      logger.info ex.message
      logger.info ex.backtrace.join("\n")
    end
  end
end

TestWorker.perform_async('test_string', 'test_2_string')
```

#### Backtrace
```
worker_1      | 2015-06-01T22:58:05.635Z 1 TID-os0yrozo4 IncomingBinaryMessageProcessorWorker JID-d27c87af04e9fe9bc5fada98 INFO: done: 0.064 sec
worker_1      | 2015-06-01T22:58:07.462Z 1 TID-os0yrozo4 TestWorker JID-a64deb68be64a0613e52d2e3 INFO: start
worker_1      | test_string
worker_1      | test_2_string
worker_1      | 2015-06-01T22:58:07.463Z 1 TID-os0yrozo4 TestWorker JID-a64deb68be64a0613e52d2e3 INFO: done: 0.0 sec
```

**Comment by mperham** [comment]
Sidekiq serializes the perform method arguments as an array of JSON entities.  It doesn't support symbols or more complex serialization.  AJ does support both at the cost of [more complex serialization](https://github.com/rails/rails/blob/master/activejob/lib/active_job/arguments.rb).

**Comment by richardjortega** [comment]
Yes, familiar with Sidekiq not accepting complex arguments parameter values. However, I wasn't familiar it also related to the method signature itself.

Please close this out and if anyone runs into this same gotcha, searching can point them here.

**Comment by tobico** [comment]
Can this be reopened? Seems like a big limitation for Sidekiq to fail on a standard and commonly used Ruby feature.

**Comment by mperham** [comment]
@tobico It's a fundamental design decision I made: arguments are serialized as plain JSON, for interoperability with all programming languages. https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple

**Comment by b-nik** [comment]
In the rare cases I need to call my worker with keyword arguments I do something like this:

```ruby
# worker
def perform(id, options={})
  arg1 = options["arg1"] || []
  arg2 = options["arg2"] || []
  # ....
end

# usage
MyWorker.perform_async(id, arg1: [1, 2, 3], arg2: [a, b, c])
```

**Comment by DannyBen** [comment]
Since I *really* want to have strong keyword args in my jobs, I have been toying with this approach:

```ruby
# jobs/job.rb
class Job
  include Sidekiq::Worker
  
  # ... more default options here

  def perform(params={})
    params = params.to_h.transform_keys(&:to_sym)
    execute params
  end
end

# jobs/greet_job.rb
class Greet < Job
  def execute(name: "there")
    puts "Hi #{name}!"
  end
end
```

So now all jobs simply define `execute` instead of defining `perform`.

And it even works nicely in specs:

```ruby
# spec/greet_job_spec.rb
expect(Greet).to have_enqueued_sidekiq_job(name: "Lloyd Chrostmas")
```

Anyone seeing any problem with this pattern?

**Comment by axos88** [comment]
@mperham, why exactly would keyword arguments introduce extra complexity?
Without delving too deep into how `Sidekiq::Worker` works (ha!), I think it could be as simple as 

      def perform_async(*args, **kwargs)
        client_push('class' => self, 'args' => args, 'kwargs' => kwargs)
      end

And then deserialize and call the perform method accordingly where required. If the issue is that the hash sent to `client_push` needs to be flat, one could argue that it could be converted to json and back, without a serious (or probably even measurable for most cases) performance hit.

**Comment by axos88** [comment]
Although I don't see why `client_push` would require a flat hash, since `args` is an array itself, which would suggests it (probably) doesn't need to be.

**Comment by axos88** [comment]
As far as I see JSON.generate gets called, so `client_push` should be able to take a non-flat hash.

**Comment by jnarowski** [comment]
Is there any proposed workaround for this? I'm migrating my jobs from ActiveJob to Sidekiq so I can use sidekiq_options (we're on rails 5). I LOVE the strictness of keyword arguments (all of our jobs have them). 

I'd really like to keep keyword arguments when migrating to calling Sidekiq directly. Has anyone solved this problem? I was going to dig into how ActiveJob does it (looks like they generate a wrapper class), but wanted to avoid the Rabbit hole if there was a simpler way.

**Comment by ezekg** [comment]
I currently do something like this. It's not ideal, since the worker doesn't raise when called with invalid keyword arguments — instead, the job fails with an argument error. But it does do the job of cleaning up the worker's code quite nicely.

```ruby
class ExampleWorker
  include Sidekiq::Worker

  def perform(kwargs)
    perform_with_kwargs(**kwargs.to_h.symbolize_keys)
  end

  private

  def perform_with_kwargs(foo:, bar:, baz: nil)
    # ...
  end
end
```

**Comment by rgaufman** [comment]
Any solution to this?

**Comment by adamniedzielski** [comment]
@rgaufman have you read all the comments above before leaving your own comment? I can point you to the best one of all the 12  (I'm not counting yours) - https://github.com/mperham/sidekiq/issues/2372#issuecomment-458608612.

It's a conscious decision so it's not considered to be a problem. And as there's no problem there is also no solution. If you want to change this situation you need to challenge the design decision and make a good case against it. I'm honestly curious to hear your arguments, because based on my five years of experience using Sidekiq https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple really makes a lot of sense.

**Comment by rgaufman** [comment]
I strongly disagree with this decision and it leads to silent bugs and unexpected behaviour.

Even knowing this limitations, occasionally myself and other developers would add a symbol or a keyword argument, test it with worker.new.perform or in a spec that runs inline but then get problems when running the method with a delay or async.

I have read that document but I don't understand why anyone would think this is a good decision, maybe I am missing something. Support for all languages makes no sense either for not adding optional support for a different serialiser, when you don't need that "feature".

**Comment by adamniedzielski** [comment]
I can see that it's indeed causing a lot of frustration for you and your team. 5 years of using a tool that doesn't sparkle joy is a lot to handle 😢 

> I don't understand why anyone would think this is a good decision, maybe I am missing something

Yes, I think you are. If you don't have this knowledge on your team a good solution is often to hire an external consultant. Mike is offering support - both paid and unpaid - https://sidekiq.org/support.html. Maybe this can help you and your team?

**Comment by rgaufman** [comment]
We have spoken to external consultants that complain of the same design decision. If you scroll through the referenced comments, you would see they are rationed heavily in favour of re-opening, including the comment directly above my one.

**Comment by mperham** [comment]
> Even knowing this limitations, occasionally myself and other developers would add a symbol or a keyword argument, out of habit doing this many times per day, test it with worker.new.perform or in a spec that runs inline but then get problems when running the method with a delay or async.

Then use ActiveJob. It supports the full spectrum of Ruby method argument options.

> Often it's Rubocop even that says oh, this needs to be a keyword argument and every one on the team has to remember, oh no, Sidekiq doesn't like that - this is a common occurrence and frustration every developer on our team feels often for the 5+ years we've been using Sidekiq.

Sidekiq 6.4 now warns if you pass arguments that do not serialize cleanly. If Rubocop complains, that's a Rubocop bug. Sidekiq's best practice has been firm and in place for 10 years now. It will not change.

**Comment by rgaufman** [comment]
10 years ago Ruby didn't have keyword arguments, the language itself has changed and I think that was one of the most important improvements. I will try ActiveJob again thank you, last time we had to move away as we couldn't get sidekiq_options to work, but this was some time ago.

**Comment by tobico** [comment]
> It's a conscious decision so it's not considered to be a problem. And as there's no problem there is also no solution. If you want to change this situation you need to challenge the design decision and make a good case against it. I'm honestly curious to hear your arguments, because based on my five years of experience using Sidekiq https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple really makes a lot of sense.

I agree that small and simple arguments are a good thing. I don't agree with the implication that keyword arguments can in any way be considered big or complex. They're a feature that was added to the language for a reason, to make code more readable and maintainable, and not supporting them makes Sidekiq a less useful library than it could be.

**Comment by ezekg** [comment]
I completely agree that keyword arguments would make some jobs much, much safer. But this is nothing a few tests can't resolve, and I do respect your decision, @mperham, even if I don't 100% agree with it.

An an example — this is a real-world request log job for my business.

```ruby
RequestLogWorker.perform_async(
  current_account,
  current_bearer_type,
  current_bearer_id,
  current_resource_type,
  current_resource_type,
  request_id,
  request_date,
  request_user_agent,
  request_method,
  request_url,
  request_request_body,
  request_ip,
  request_signature,
  request_response_body,
  request_status,
)
```

I've passed the args in the wrong order more than once during refactors. Thankfully, it was caught by automated tests. But still, it _has_ been a real issue. I have a couple other jobs that take a large number of args, and same problem.

**Comment by wksmall** [comment]
@ezekg I think you should consider taking all those arguments and passing them to sidekiq as a hash with string keys so you will have no worries about their order. Frankly, any method accepting more than 4 or 5 arguments is a code smell but that's another issue entirely. 

We are just now moving to Sidekiq 6 and welcome the argument strictness. It couldn't come soon enough for me. In spite of documentation and online training that we offer our devs, invariably someone will forget Sidekiq's Best Practices (or claim ignorance). As I am reviewing our various job parameters as part of the update, I am noticing how some devs have been programming around the fact that the symbolic keys passed to a sidekiq job end up being string keys within the job. Now, they'll have to pass the right data up front.

**Comment by nbcraft** [comment]
We made the decision to move out of ActiveJobs and back to standard Sidekiq jobs, but wanted to limit the impact on the entire codebase, and keep our jobs using keyword arguments.

After reading this thread, I came up with this solution:
```rb
# ActiveJob is slower: https://github.com/mperham/sidekiq/wiki/Active-Job#performance
class ApplicationJob
  include Sidekiq::Worker

  def self.inherited(subclass)
    super
    subclass.prepend(PerformWrapper)
  end

  def self.perform_now(*args, **kwargs)
    perform_inline(args, kwargs.stringify_keys) # Pass args and kwargs as regular arguments to sidekiq
  end

  def self.perform_later(*args, **kwargs)
    perform_async(args, kwargs.stringify_keys) # Pass args and kwargs as regular arguments to sidekiq
  end

  def self.perform_later_in(run_in, *args, **kwargs)
    perform_in(run_in, args, kwargs.stringify_keys) # Pass args and kwargs as regular arguments to sidekiq
  end
end

# Wraps around the child class implementation of #perform to transform the sidekiq job arguments back to keyword args
module PerformWrapper
  # receive args and kwargs as regular arguments from sidekiq
  def perform(args, kwargs = {})
    super(*args, **kwargs.symbolize_keys) # pass them back to child job class as args and keyword-args
  end
end

class MyJob < ApplicationJob
  def perform(reg_arg, key_arg:)
    # do things
  end
end

MyJob.perform_later(1, key_arg: 2)
```
It's probably not perfect, but might help others looking for an option to do this, or use this as a base for a better implementation.

I wasn't at all familiar with prepending modules, but used [this](https://stackoverflow.com/a/49564134/3379701) as inspiration.

----------

I also have a version where we pass `args` as a list to sidekiq and just append `kwargs` at the end:
- It allows to keep using sidekiq methods `.perform_inline`, `.perform_async` ... without breaking on `#perform`
- But if you actually wanna pass a `Hash` as last arg, it probably will break as it will try to send it as keyword arguments (didn't test)

```rb
  def self.perform_later(*args, **kwargs)
    perform_async(*args, kwargs.stringify_keys) # Pass kwargs as last regular argument to sidekiq
  end

module PerformWrapper
  # receive kwargs as last regular argument from sidekiq
  def perform(*args)
    kwargs = args.last&.is_a?(Hash) ? args.pop : {} # Extract kwargs if last argument is a Hash
    super(*args, **kwargs.symbolize_keys) # pass them back to child job class as args and keyword-args
  end
end
```

**Comment by inspire22** [comment]
I ran into trouble with this too - the "ruby way" has moved to named parameters and it's pretty 1999 that sidekiq doesn't support the main format of the language it's written in.  Sure there's backend reasons.

Ultimately it's causing production issues/confusion due to the default of tests being run inline and therefore supporting named parameters.  Just wanted to throw my 2c at the dead horse :)

**Comment by jakeonfire** [comment]
i've been simply converting them in the job class since that also benefits from seeing exactly where the boundary between the more universal JSON and the ruby-specific kwargs happens. it's not hard and there are many other solutions mentioned above.

```ruby
class TestMetricsWorker
  include Sidekiq::Worker
  include MetricsHelper

  def perform(options = {debug: Rails.env.development?}.with_indifferent_access)
    do_work(do_error: options["do_error"], debug: options["debug"])
  end

  private

  def do_work(do_error:, debug:)
    log_metrics if debug
    sleep 0.5
    raise RuntimeError if do_error
  end
end
```

@rgaufman 
> test it with `worker.new.perform` or in a spec that runs inline but then get problems when running the method with a delay or async.

i would consider the first case a Sidekiq anti-pattern; `perform_inline` or `Sidekiq::Testing.inline!` + `perform_async` are better options. using either of those methods should fail on keyword arguments, so seems like you have other issues or are mis-remembering?

**Comment by tonytonyjan** [comment]
Hope it helps.


```ruby
module KwargsToArgs
  def perform(**kwargs)
    args = []
    method(:perform).super_method.parameters.each do |type, name|
      case type
      when :req then args << kwargs.fetch(name)
      when :opt then args << kwargs.fetch(name) if kwargs.key?(name)
      end
    end
    super(*args)
  end
end

# Usage
class A
  prepend KwargsToArgs
  def perform(a, b, c = 1)
    [a, b, c]
  end
end

pp A.new.perform(a: 1, b: 2, c: 3) # => [1, 2, 3]
pp A.new.perform(a: 1, b: 2)       # => [1, 2, 1]
```

**Comment by xxx** [comment]
I'm using a combo of middleware and `prepend`ed module on the `ApplicationJob` class (this is in a Rails app, so replace the Rails-isms in other contexts):

```ruby
module ArgSplitter
  def perform(*args)
    opts = args.extract_options!
    opts.symbolize_keys!

    super(*args, **opts)
  end
end

class ApplicationJob
  include Sidekiq::Job

  def self.inherited(base)
    super
    base.prepend(ArgSplitter)
  end
end

class SidekiqClientMiddleware
  include Sidekiq::ClientMiddleware

  def call(_worker_class, job, _queue, _redis_pool)
    job['args']&.each { it.try(:stringify_keys!) }
    yield
  end
end

```

`MyJob.perform_async(id: 123)`, `MyJob.perform_bulk([[{id: 123}], [{id: 456}]])` etc. should all work fine
