### ISSUE TITLE
Latency is confusing for scheduled jobs

### ISSUE THREAD

**Issue by mrsimo** [mperham/sidekiq#2373]
We're monitoring our [queue's `latency`](https://github.com/mperham/sidekiq/blob/2fc1d81cc9691c9232a088f1410c5a27fae5e11f/lib/sidekiq/api.rb#L213-L219) to get notified if it gets out of control.

We recently released a feature that schedules a sidekiq job to run in 10 hours. It's working great, but has caused that our monitoring sometines reports a latency of ~3600s (10 hours).

This is some debugging info:

```
low has a latency of 36003.53266143799
entry.enqueued_at: 1433196986.023483
Time.now:          1433232989.5564206
"{\"retry\":0,\"queue\":\"low\",\"class\":\"WarnAboutRunawayTimerWorker\",\"args\":[337121779],\"jid\":\"b5acceac3b94680bc7d06448\",\"enqueued_at\":1433196986.023483}"
```

I guess the `enqueued_at` is correct in a sense, but I wonder if we could do something about it. I've been using `Sidekiq::Stats::Queue#latency` to get that number, but I'd be fine calculating it manually.

Would it make sense to change the `enqueued_at` to the time it's actually pulled from the scheduled set and into the actual queue? Maybe add another field `originally_enqueued_at` or something.

That's just an idea, anything that would let me know a more realistic latency would be welcome.

Thanks a lot!

**Comment by mperham** [comment]
Agreed, that's confusing.  The attribute is poorly named and not implemented precisely.  We could rename it `created_at` and have a separate `enqueued_at` which is set only when actually pushing to a queue.
