### ISSUE TITLE
Reschedule restarted jobs with a delay

### ISSUE THREAD

**Issue by ivanovv** [mperham/sidekiq#2378]
Right now, if I have a frozen job in Sidekiq the only way to deal with it is to restart Sidekiq process. But I have many Sidekiq processes running it is hard to reliably kill the 'bad' job - I have to putt them all in quite mode, kill the one with the frozen job, inspect the queue and delete it, restart those sidekiqs that have no jobs running (to make them accept jobs again).

It would be awesome if the jobs from the manually stopped process would be rescheduled with a delay, say 30s, so I can delete the 'bad' job from the queue while it is there.

**Comment by mperham** [comment]
Why not spend more time figuring out why your jobs are freezing the process?

**Comment by ivanovv** [comment]
Well, "frozen" job isn't freezing the process - it is just a job I want to cancel, but it waits on some external call or, for example, here
```
status = Sidekiq::Batch::Status.new(batch.bid)
status.join
```

I agree that investigating why the job has failed is the best way to deal with such issues, but the issue was raised from a Operations perspective - code evolves, bugs do happen.

But after a second thought, it looks like 30 seconds delay will be a disaster for a highload project. So to make this one right, one needs some unique signal to stop Sidekiq (in order to tell it that this shutdown is special and it needs to reschedule jobs with a delay)

Looks like a tiny change, but if my case is quite a rare one and such feature would be of no great value for the Sidekiq users - feel free to close the issue.

Main reason I opened it is the mantra "there is no _kill job_ feature in Sidekiq" and we have to stop the process and in multi Sidekiq envs it becomes quite cumbersome to catch that failing job ))

**Comment by mperham** [comment]
There's no safe way to kill a job in progress so Sidekiq does not provide a way.  The job must check itself if it should quit.

**Comment by ivanovv** [comment]
Yeah, that's the mantra exactly, I just wanted to explain why I want a special behaviour for rescheduling jobs after we stopped Sidekiq. Looks like you didn't hear that ))

In short: 
```kill -SOME_SPECIAL_SIGNAL sedekiq_pid```
Sidekiq waits ```timeout``` and then puts unfinished jobs back in the queue, but scheduled to run in 30s.
So I can avoid putting all Sidekiq in quite mode so that they don't run that unfinished jobs immediately. 

Hope it makes some sense.
