### ISSUE TITLE
BatchSet doesn't seem to represent all open batches

### ISSUE THREAD

**Issue by TheCorp** [mperham/sidekiq#2379]
This is definitely an odd one, in the docs it says "You can iterate through all known Batches, getting a Sidekiq::Batch::Status"

Normally if we run the following it will delete all open batches but for some reason this currently doesn't seem to be working:

`Sidekiq::BatchSet.new.each(&:delete)`

Not sure why this doesn't work and the count never changes after we delete them:

```
Sidekiq::BatchSet.new.count
=> 150
```

The original delete seemed to delete some of the batches but not all.

**Comment by TheCorp** [comment]
I ran it a few more times like this `Sidekiq::BatchSet.new.each {|batch| batch.delete }` and eventually it deleted them all. This reminds me of a very long time ago when trying to delete retries would only delete half at a time.

**Comment by mperham** [comment]
Deleting during iteration is undefined behavior. I'd to_a it to pull all batches into memory first.

It would be a lot safer to flushdb instead.

**Comment by TheCorp** [comment]
Unfortunately we can't flushdb, there's a number of non Sidekiq things in our redis but we'll definitely pull it into memory to delete from now on.
