### ISSUE TITLE
Troubles with open-uri

### ISSUE THREAD

**Issue by mbajur** [mperham/sidekiq#2380]
Hello
I have a really strange situation going on right now. Actially it's a horrible thing because it happens on one of my production apps and a lot of commercial clients are not able to use my app.

One of my workers is using open-uri `open` method to read a remote file and save it locally. It was working like that for about two years, and today, after about 2 months since last commit, it accidentialy stopped working and i'm not able to do anything about it. The code looks more or less like that:

```
require 'open-uri'

class DownloadOriginalFileWorker
  include Sidekiq::Worker
  sidekiq_options :queue => :download_original_file

  def perform(video_id, grinder_id)
    File.open(Rails.root.join('tmp', 'download_original_worker', filename), "wb") do |saved_file|
      open(sas_url, "rb", ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE, 'User-Agent' => 'opera') do |read_file|
        saved_file.write(read_file.read)
      end
    end
  end
end
```

And line with `open()` method returns `OpenURI::HTTPError: 403`. The interesting part is that i'm able to run that code outside of a worker without any problems (using the same `sas_url` value) but running it asynchronously or using `DownloadOriginalFileWorker.new.call(:perform, args)` throws that error. Thats really strange because it seems like nothing related to sidekiq but for some reason, it breaks just when used in sidekiq context.

Any ideas what's going on? Thanks

**Comment by mperham** [comment]
No idea what's wrong.  I would re-implement it with Net::HTTP and proper socket timeouts.

**Comment by davydovanton** [comment]
@mbajur hello! I think you have a problem with your `User-Agent` value ( I mean `opera` ). Please try set any of [this](http://www.useragentstring.com/pages/Opera/) values for opera.

**Comment by mbajur** [comment]
Well i have set that agent because i've found a bit similar thread somewhere and one commenter said that some webservers have user-agent restrictions and, for instance, if you want to make a request using 'ruby' user agent which is the default one (as far as i know), such server can respond with 403. 

Anyway, VPS reboot resolved that issue for now. I've tried restarting redis/sidekiq/nginx/passenger/sinatra and that didn't. I'm still curious what was that about.
