### ISSUE TITLE
Intercept a sigterm to do extra logging?

### ISSUE THREAD

**Issue by rokas3883** [mperham/sidekiq#2383]
To avoid once-in-a-while occurring memory leaks with our sidekiq workers, we've set up monit to restart the worker if its memory footprint exceeds a certain amount. 

When the worker gets restarted (with sigterm), I'd like to send an Airbrake, as well as log it in Mongo, so we can see/analyze how often these workers are restarted.

Is there a clean way to do this with sidekiq? I haven't found any in the documentation yet.

**Comment by ryansch** [comment]
Generally you would do the alerting with whatever you're using to restart sidekiq (monit in this case).  I use something other than monit and I have it send alerts to our slack channel.

**Comment by mperham** [comment]
You should configure monit to do this. There's no way to do it in Sidekiq.

**Comment by rokas3883** [comment]
Thanks for the responses. I'll look into monit doing the alerts.

**Comment by VishalRam** [comment]
@ryansch - What kind of service do you use for alerting? Can you I know some other options?

**Comment by ryansch** [comment]
There are a number of good choices for monitoring processes.  I happen to know the guy who maintains https://github.com/mperham/inspeqtor

:wink:
