### ISSUE TITLE
Question: high concurrency limitations

### ISSUE THREAD

**Issue by yarivdev** [mperham/sidekiq#2385]
> Don't set the concurrency higher than 50. I've seen stability issues with concurrency of 100

Assuming connection pools, ulimit etc.. are all good, is there a problem setting the concurrency to the thousands?

**Comment by w-A-L-L-e** [comment]
Yes memory and cpu limits...

On Thursday, June 11, 2015, yarivdev <notifications@github.com> wrote:

> Don't set the concurrency higher than 50. I've seen stability issues with
> concurrency of 100
>
> Assuming connection pools, ulimit etc.. are all good, is there a problem
> setting the concurrency to the thousands?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2385>.
>


-- 

*SIT BVBA * <http://www.sitweb.eu>

   - Phone: +32.486.11.88.36
   - Fax: +32.3.239.68.24
   - Mail: Walter@Schreppers.com

**Comment by mperham** [comment]
I don't know.  Benchmark 25, 50, 100, 200, 500, 1000 threads and show us the results.

**Comment by yarivdev** [comment]
Workers perform a tiny task, just a few ms. but a LOT of them. I've actually set the concurrency to 20k and haven't noticed any issues while testing. However it is stated "Don't".. so i gotta ask

**Comment by mperham** [comment]
MRI is limited to one core.  Adding more threads won't do anything if the CPU is already pegged.

**Comment by w-A-L-L-e** [comment]
That's the thing it depends on how much you're workers are doing and also
on what server you run and what other components you are using like mysql
vs postgres. Redis and or memcached etc etc. it's specific to your
situation and implementation...

On Thursday, June 11, 2015, yarivdev <notifications@github.com> wrote:

> Workers perform a tiny task, just a few ms. but a LOT of them. I've
> actually set the concurrency to 20k and haven't noticed any issues while
> testing. However it is stated "Don't".. so i gotta ask
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2385#issuecomment-111232254>.
>


-- 

*SIT BVBA * <http://www.sitweb.eu>

   - Phone: +32.486.11.88.36
   - Fax: +32.3.239.68.24
   - Mail: Walter@Schreppers.com

**Comment by yarivdev** [comment]
> MRI is limited to one core. Adding more threads won't do anything if the CPU is already pegged.

Very helpful,
Thanks.

**Comment by w-A-L-L-e** [comment]
Hmmm but with puma or unicorn or passenger you can easily utilise all
cores... again its how you setup and implement your system that defines its
limits ... And yes benchmarking can pinpoint bottlenecks.
Kind regards and keep up the great work on sidekiq,
Walter

On Thursday, June 11, 2015, yarivdev <notifications@github.com> wrote:

> MRI is limited to one core. Adding more threads won't do anything if the
> CPU is already pegged.
>
> Very helpful,
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2385#issuecomment-111233453>.
>


-- 

*SIT BVBA * <http://www.sitweb.eu>

   - Phone: +32.486.11.88.36
   - Fax: +32.3.239.68.24
   - Mail: Walter@Schreppers.com
