### ISSUE TITLE
uninitialized constant XXXXXWorker

### ISSUE THREAD

**Issue by sahin** [mperham/sidekiq#2387]
@mperham 

We started to get this issue a lot. Sidekiq is retrying and we dont see any error at the end of the day but we see these in our bugsnags/honeybadger. 

We are in latest version sidekiq  and rails 4.2.0

Is it a memory issue?

NameError gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261

```
NameError uninitialized constant CinemaWorker
gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261const_get
gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261block in constantize
gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259each
gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259inject
gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259constantize
gems/activesupport-4.2.0/lib/active_support/core_ext/string/inflections.rb:66constantize
gems/sidekiq-3.3.4/lib/sidekiq/processor.rb:46process
gems/celluloid-0.16.0/lib/celluloid/calls.rb:26public_send
gems/celluloid-0.16.0/lib/celluloid/calls.rb:26dispatch
gems/celluloid-0.16.0/lib/celluloid/calls.rb:122dispatch
gems/celluloid-0.16.0/lib/celluloid/cell.rb:60block in invoke
gems/celluloid-0.16.0/lib/celluloid/cell.rb:71block in task
gems/celluloid-0.16.0/lib/celluloid/actor.rb:357block in task
gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57block in initialize
gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15block in create

````

**Comment by mperham** [comment]
It's likely a Rails autoloading issue.  This is an issue with your app code and not Sidekiq.  If you can reproduce it, you can use `git bisect` to find the commit that broke it.

**Comment by sahin** [comment]
@mperham, this happends a lot, CinemaWorker is in the workers folder actually. For autoloading or requires do u have any suggestion to read. I can also add smth in sidekiq wiki for autoloading.

**Comment by mperham** [comment]
Autoloading often hides the underlying issue.  CinemaWorker might be there but something that **it** requires is missing.  Typically it's a class in `lib/` which does not follow the Rails autoloading naming convention.
