### ISSUE TITLE
Sidekiq is not designed to work well with dozens of queues.

### ISSUE THREAD

**Issue by troessner** [mperham/sidekiq#2388]
We have a lot of different workers and are considering using a single queue for everyone of them since this gives us more flexibility in moving workers around priority-wise since.
It also seems to be a cleaner separation of concerns: one worker == one functionality == one queue

However the sidekiq wiki says:

>> I don't recommend having more than a handful of queues. Sidekiq is not designed to work well with dozens of queues.

Could you please elaborate on why this is and possibly add it to the README as well?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Reliability#watch-out

**Comment by troessner** [comment]
Thanks for the answer!
