### ISSUE TITLE
ActiveJob and Sidekiq::Worker

### ISSUE THREAD

**Issue by phawk** [mperham/sidekiq#2389]
Not sure if this is just something that won’t work but I have some workers running inheriting from active job and another couple that just `include Sidekiq::Worker` to take advantage of additional options.

Should these work side by side? I get errors on some jobs (the ones that include sidekiq worker) such as:

```
undefined method `job_id=' for #<ItemBackupJob:0x007f32f8e244b0>

active_job/core.rb ? in deserialize
         job.job_id               = job_data['job_id']
active_job/execution.rb ? in execute
         job = deserialize(job_data)
active_job/queue_adapters/sidekiq_adapter.rb ? in perform
           Base.execute job_data
sidekiq/processor.rb ? in execute_job
       worker.perform(*cloned_args)
sidekiq/processor.rb ? in block (2 levels) in process
             execute_job(worker, cloned(msg['args']))
sidekiq/middleware/chain.rb ? in block in invoke
             yield
sidekiq/middleware/server/active_record.rb ? in call
           yield
sidekiq/middleware/chain.rb ? in block in invoke
             chain.shift.call(*args, &traverse_chain)
sidekiq/middleware/server/retry_jobs.rb ? in call
           yield
sidekiq/middleware/chain.rb ? in block in invoke
             chain.shift.call(*args, &traverse_chain)
sidekiq/middleware/server/logging.rb ? in block in call
               yield
sidekiq/logging.rb ? in with_context
       yield
```

Running sidekiq 3.3.4 and rails 4.2.0, ruby 2.2.0, ubuntu 14.04

Thanks,
Pete

**Comment by phawk** [comment]
Actually this could just be me being an idiot and the retry queue having jobs previously queued with active job before I migrated the class to use `Siedkiq::Worker`. Have deleted the from queue. If this is expected to work it would still be great to know, and I shall keep an eye on my failed jobs and make sure this error doesn’t pop up again.

**Comment by mperham** [comment]
I was just going to say, that looks like an old job that used to be an ActiveJob.  Compatibility is tough.  :+1:
