### ISSUE TITLE
Sidekiq - asset path not valid in email : Engineyard : Nginx : Passenger

### ISSUE THREAD

**Issue by shivabhusal** [mperham/sidekiq#2390]
I have used `Sidekiq` for processing emails asynchronously. It works well in development env however it does not render a valid asset URL in email published.  

Expected Asset URL:  
`http://myapp.com/assets/logo-277121cb27cd5798ea5786fa2996c82f.png`  

Got:  
`http://myapp.com/images/logo.png`

I am using `Engineyard` as VPC. In production/staging servers I have a dedicated utility instance named `redis` which comprises of `redis server` and `sidekiq` instances running. They are processing email properly so I guess they are in good condition.  For more info please visit the stackoverflow link

> http://stackoverflow.com/questions/30778513/ruby-on-rails-mailer-sidekiq-asset-path-not-valid-in-email-engineyard

**Comment by mperham** [comment]
Sidekiq doesn't know anything about assets.  This must be a Rails environment configuration issue and I know next to nothing about the asset pipeline so I can't offer any help.
