### ISSUE TITLE
Proper way to transfer jobs between Redis instances

### ISSUE THREAD

**Issue by jonsgreen** [mperham/sidekiq#2391]
This is more of a support question but thought I would ask here in case it is helpful to others. 

I had some jobs fail to be added to a Redis instance on a separate server because a firewall rule was not properly setup (on cloud66). Fortunately, reliable fetch moved these to a local queue with this warning:

    [ReliablePush] Enqueueing job locally due to error: Error connecting to Redis on ....

I now want to move these jobs to their proper home on the other Redis instance so that they can be properly processed. 

I probably could figure out how to do this digging into the code and API but thought I would ask here first especially since I want to get this done right. 

Thanks!

**Comment by mperham** [comment]
There's no "proper" way to do this and I've never done it myself so I'm hesitant to write sample code to do it.  You'll need connections to the old and new Redis.  Pop the jobs off the old local queue and push them to the new public queue.  Beyond that, I don't know what else your situation might call for.

**Comment by jagthedrummer** [comment]
Here's a rake task that I used recently to move Sidekiq jobs from one Redis instance to another.

https://gist.github.com/jagthedrummer/9b18b9c29a489357fb7ee1634bc2049d
