### ISSUE TITLE
Feature idea: pass retry account as part of context hash for exception handlers

### ISSUE THREAD

**Issue by geoffharcourt** [mperham/sidekiq#2394]
(I hope this isn't bike-shedding.)

I have a bunch of situations where jobs fail for some intermittent reason (usually related to external systems not being highly available). I don't care if those jobs fail once or twice, because on subsequent retries they get taken care of. However, I care a lot if those jobs fail for a longer period of time.

I'm trying to set up my exception handler such that the first few retries don't trigger a call to my exception handling service, but after a specified number of retries the handler block goes ahead and sends the notification to the service. `#handle_exception` passes the exception and the context hash. It looks like in most cases the context hash is just a string or hash with the message.

Would you be open to a PR that added the `retry_count` from the job into the context hash sent to `#handle_exception`?

**Comment by mperham** [comment]
I thought the context hash should be the job contents.  Can you show me where it's just a string?

**Comment by aprescott** [comment]
I sounds like I recently did exactly this. Maybe this code is useful to you?

```ruby
module SidekiqFailureTracking
  def self.call(exception, context)
    retry_count = context["retry_count"]
    job_id = context["jid"]
    job_args = context["args"]
    job_class = context["class"]

    failure_count = retry_count + 1

    if failure_count >= YOUR_WARN_THRESHOLD
      message = "#{job_class} failure (#{job_id}, failed #{failure_count} times): #{job_args.to_s.truncate(100)}\n\n#{exception.class} — #{exception.message}"

      if failure_count >= YOUR_ALERT_THRESHOLD
        alert(message)
      else
        warn(message)
      end
    end
  end

  private

  def self.alert(message)
    # your alerting goes here
  end

  def self.warn(message)
    # your warning goes here
  end
end
```

**Comment by aprescott** [comment]
Configuration is with `config.error_handlers << SidekiqFailureTracking` within `configure_server`. (I'm using a class as a fake proc by just defining `self.call`.)

**Comment by geoffharcourt** [comment]
@aprescott, I'm going to take a look at this. Thank you very much for showing your code!
