### ISSUE TITLE
Error using Rails.cache with redis store  no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by dcdieci** [mperham/sidekiq#2395]
Hi,

I want to user redis as cache inside Rails so I set cache store to redis.
Now I get this error inside a workers perform method

no _dump_data is defined for class Proc
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `dump'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.8/lib/active_support/cache.rb:548:in `instrument'
/Users/phil/.rvm/gems/ruby-2.2.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
/Users/phil/RubymineProjects/schneeroute/app/workers/hotelde_worker.rb:65:in `perform'

The records I want to save are simple ActiveRecord objects without Proc.
At the same time
$redis.lpush "results:rates:#{job_id}", rates
is working fine.
So I am wondering why redis complains about the Proc?

**Comment by ismaelga** [comment]
I don't think Sidekiq is the issue here

**Comment by dcdieci** [comment]
That's what I was asking myself, but I have no explanation where else the Proc can come from.

**Comment by ismaelga** [comment]
What does the line 65 of hotelde_worker.rb looks like?

**Comment by dcdieci** [comment]
Rails.cache.write("results:rates:#{job_id}", rates)
But I just noticed that it's most likely another issue.
rates consists of
rates << Rate.new(
              :supplier_id  => candidate.supplier_id,
              :candidate_id => candidate.id,
              :total        => result.total,
              :catering     => result.catering,
              :arrival      => options['arrival'],
              :departure    => options['departure'],
              :nightly_rate => result.per_night,
              :breakfast    => result.breakfast_price
          )
but they don't get save to the db. So I assume that the Rate which got created and pushed to the array is having the Proc inside just because it has not been save yet?!

So it's not related to sidekiq, sorry for the inconveniences I am causing
