### ISSUE TITLE
`Memory Bloat` description in wiki is still correct?

### ISSUE THREAD

**Issue by osdakira** [mperham/sidekiq#2396]
in `Memory Bloat` description, 
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#memory-bloat

> ```rb
   # See if product search returns no results
   return "No results" unless Product.search(...).exists?
> ```
> If the product search returns 10,000 results, this query will create 10,000 objects and then immediately > throw them away
> The right way:
> ```rb
    # See if product search returns no results
    return "No results" if Product.search(...).count == 0
>  ```

At least `rails 4` + `mysql`, `exists?` method call `LIMIT 1` sql.

```rb
[15] pry(main)> User.where(first_name: "mike").exists?
  User Exists (4.5ms)  SELECT  1 AS one FROM `development`.`users` WHERE `development`.`users`.`first_name` = 'mike' LIMIT 1
=> false
```

It seems that the description is outdated.
Is it still correct?
Should I change methods from `exists?` to `count`.

**Comment by davydovanton** [comment]
yep, you're right. `#exist?` call `#limit(1)`, [proof](https://github.com/rails/rails/blob/430a09514a4ad1d0f8481f18a42c4813b6b61e38/activerecord/lib/active_record/relation/finder_methods.rb#L303)

**Comment by davydovanton** [comment]
@mperham we should remove example with AR from wiki page

**Comment by mperham** [comment]
A previous wiki editor had completely misunderstood the point of the "bad" example and "fixed" it.  It should make more sense now.
