### ISSUE TITLE
Celluloid 0.17.0 is shipping.

### ISSUE THREAD

**Issue by digitalextremist** [mperham/sidekiq#2397]
The `0.17.0` version of `Celluloid` is being released to Rubygems, after being [available on GitHub](/celluloid/celluloid/wiki/0.17.0-Prerelease) for some time. Right now `0.17.0.rc1` is on Rubygems.

This new version has two modes. By default it runs in `backported` mode, which ought to work for `Sidekiq` no problem, but if `Celluloid` is loaded using `require 'celluloid/current` it has a different API in certain cases. Without `backported` mode, there would be many sudden breaking changes.

`Sidekiq` has been tested lightly and successfully ( celluloid/celluloid#615 ), using `0.17.0` .. but we would like more feedback and confirmations of stability and performance.

We're going to ship `0.17.0` ( celluloid/celluloid#640 ) in the next few days. Would anyone mind doing some testing with `Sidekiq` itself remaining unchanged? Once `0.17.0` ships, I will refactor `Sidekiq` and submit a patch ( celluloid/celluloid#627 ) unless someone else would prefer to.

**Comment by mperham** [comment]
I can't install it.  Tips?

```
gem install celluloid -v 0.17.0.rc1 --pre
ERROR:  Could not find a valid gem 'celluloid-essentials' (>= 0) in any repository
```

**Comment by digitalextremist** [comment]
@mperham can you try installing `celluloid-essentials` first? It's currently at `0.20.0.pre17` ... but it'd be easier to just pin versions in your gemspec/Gemfile and `bundle update`

**Comment by mperham** [comment]
I am not a fan of splitting Celluloid into more and more, ever smaller gems.  I don't want a dozen different gem dependencies "underneath" Sidekiq.  I guess I will need to change the gemspec to reference just the Celluloid core that Sidekiq uses.

**Comment by digitalextremist** [comment]
Celluloid itself requires the gems itself, but in this case we're talking about multiple levels of prerelease gems so I'm seeing if you need to manually grab the prerelease gem behind celluloid.

And we've decoupled several gems, but at this stage they are interdependent. No amount of singling out gems for install is going to make a difference because Celluloid has its own dependencies given.

The best I can do for you right now is ship the secondary gems at official versions and you'll be able to deploy.

**Comment by mperham** [comment]
It appears to work fine in my simple testing except for the giant warning that prints out on startup.

**Comment by digitalextremist** [comment]
Ok, good. You can get that down to one line by using `require 'celluloid/silent` and/or:

```
export CELLULOID_BACKPORTED='silently'
```

**Comment by mperham** [comment]
0.17 just landed on master.

**Comment by digitalextremist** [comment]
:+1:

**Comment by danieljacobarcher** [comment]
@mperham Will you be releasing to RubyGems or bumping the version on this? I got stuck in limbo locked to Celluloid 0.16.1 (which is no longer on RubyGems?).

**Comment by mperham** [comment]
Not for this. Bundle update sidekiq should update the gems.

**Comment by dubilla** [comment]
@mperham Will `bundle update sidekiq` update Sidekiq's dependencies? I'm in the same boat as @danieljacobarcher , have celluloid locked to Celluloid 0.16.1, and `bundle update sidekiq` is updating Sidekiq to the latest, but it's not touching Celluloid.

**Comment by mperham** [comment]
Yes, it will update all dependencies but I don't know if it handles yanks gracefully.  Update your Gemfile to `gem 'celluloid', '~> 0.16.0.0'` might get you a version that works?

**Comment by dubilla** [comment]
@mperham Yeah, it didn't handle the yank gracefully, unfortunately.

Anyway, updating our Gemfile with your suggestion worked! Thanks a ton for the assistance.

**Comment by mehulkar** [comment]
nice, locking celluloid to 0.16.0 worked for me as well. Thanks!
