### ISSUE TITLE
What does the "12" in 'redis://redis.example.com:7372/12' mean?  And is hiredis the default?

### ISSUE THREAD

**Issue by inspire22** [mperham/sidekiq#2400]
Docs page is here, but I had some questions: https://github.com/mperham/sidekiq/wiki/Using-Redis

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://redis.example.com:7372/12' }
end

What's /12?  The number of threads?  I don't process very many jobs currently, should I lower it?  It's not running on a dedicated machine, but was fine using a single thread/process with delayed_job.

Also, is :hiredis enabled by default when it's in my gemfile?

Thanks for a great project :)

**Comment by davydovanton** [comment]
Hello, `redis://...:1234/...` it's only url to your redis database, where `1234` is port. In wiki page url shows only for example and therefore `12` is only part of url to your redis database.

**Comment by davydovanton** [comment]
Also you can check this link for more information 
http://celery.readthedocs.org/en/latest/getting-started/brokers/redis.html

**Comment by inspire22** [comment]
All my other apps have specified redis using a host / port.  Aah the number-as-path seems to be the redis "database number", which I'd never even heard of.  Not a huge fan of moving away from named arguments to a generic string, but whatever works I guess and there's downstream gems involved...

Thanks!

**Comment by davydovanton** [comment]
You are welcome :)

**Comment by rshiva** [comment]
@davydovanton  Thanks for the explanation. :)

**Comment by davydovanton** [comment]
@rshiva you are welcome :)

**Comment by javierjulio** [comment]
@davydovanton didn't want to open a new issue for this but was wondering the same as @inspire22, if I just include hiredis in my Gemfile, does sidekiq-pro switch to using that or do I need to specify a config option? Had trouble finding an answer to that.

**Comment by mperham** [comment]
@javierjulio 

```ruby
Sidekiq.configure_server do |config|
  config.redis = { driver: 'hiredis' }
end
```

**Comment by javierjulio** [comment]
@mperham thank you!

**Comment by gamesover** [comment]
I don't understand wiki example here. Shouldn't the typical port is `6379` and db number is `0` unless default config is explicitly changed by `sidekiq`? Thus, The typical redis url is `redis://redis.example.com:6379/0` rather than `redis://redis.example.com:7372/12`? Please correct me if I've made a mistake. Thanks.
