### ISSUE TITLE
Upstart script gets executed without passing the index variable

### ISSUE THREAD

**Issue by robinboening** [mperham/sidekiq#2401]
Hi there,

I have been using this upstart script (https://github.com/mperham/sidekiq/blob/master/examples/upstart/manage-one/sidekiq.conf) for a while. Fortunately there was no situation it was really needed until the day the server rebooted. Unfortunately the upstart script had no effect and sidekiq was not started.

After some investigations I think I know why this happend:
The Ubuntu system probably starts the script using this command `initctl start sidekiq`. The script expects a variable named `index`, but it is not passed when the system calls it on a reboot. So the script fails without starting sidekiq.

I fixed the issue for me by just hardcoding the index in the script, but certainly this is not a general and great solution.

Any ideas or suggestions?

Thanks
Robin

**Comment by mperham** [comment]
The `workers` script is supposed to start up everything.  In fact, the sidekiq script should not have the starts on or stops on line since, like you mention, it can't be auto-started.

https://github.com/mperham/sidekiq/blob/master/examples/upstart/manage-one/workers.conf#L18

**Comment by robinboening** [comment]
I think its worth mentioning that the upstart scripts are not built for this purpose.

Or maybe it can by reading environment vars?

**Comment by mperham** [comment]
They are built for exactly that purpose.  It's a bug, I'll fix it and you are welcome to test it.

**Comment by robinboening** [comment]
Ohh, I think now I got the purpose of the `workers.conf` and the relation to the `sidekiq.conf`. I even introduced that bug weeks ago with my PR. Sorry about that!
