### ISSUE TITLE
"warning: instance variable @done not initialized"

### ISSUE THREAD

**Issue by iainbeeston** [mperham/sidekiq#2402]
When I enable ruby warnings (aka verbose mode) I get the following warning:

```
/Users/iain/.gem/ruby/2.2.2/gems/sidekiq-3.0.0/lib/sidekiq/fetch.rb:85: warning: instance variable @done not initialized
```

It happens every second or so (looks like sidekiq is polling for new jobs). It looks like the code has a class variable called `@done` which is read but never initialized [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/fetch.rb).

I'm happy to fix it, but I don't have any good suggestions about how to initialize it cleanly, and wanted to ask in case you have any ideas (before I do the work).

**Comment by davydovanton** [comment]
@iainbeeston hello
Can you display you worker code? or you have this warning for any worker?

**Comment by iainbeeston** [comment]
No this happens immediately after sidekiq starts, and repeats (every second
or so) for as long as sidekiq is running. When a worker is started it
doesn't show (as I said it appears to be when the fetcher is looking for a
job to run)

**Comment by iainbeeston** [comment]
To reproduce, just start up sidekiq with ruby warnings enabled (eg `RUBYOPT=-w bundle exec sidekiq`) and let it run (probably easier to see if there are no jobs waiting to be run). Pretty soon your screen will be full of warnings(!!!)

**Comment by iainbeeston** [comment]
(This is annoying because it's very noisy and makes it hard to find warnings related to workers)

**Comment by davydovanton** [comment]
yep, i see it

**Comment by davydovanton** [comment]
so, @mperham, what do you think, we need to fix it or not?

**Comment by mperham** [comment]
Thanks for the report Iain!
