### ISSUE TITLE
Try out mutant

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2403]
I'd love to see mutation testing integrated with our test suite.  If anyone has an interest in playing with mutant + sidekiq, give it a shot and report back here.

http://blog.arkency.com/2015/06/how-good-are-your-ruby-tests-testing-your-tests-with-mutant/

**Comment by davydovanton** [comment]
Interesting idea, but I see one negative moment. After quick search I found that mutant test is work only with rspec. Also I found mbj/mutant#330 PR with minitest integration but it is still in the works.

**Comment by mperham** [comment]
https://github.com/mbj/mutant/issues/357
