### ISSUE TITLE
Sidekiq + Docker - Handle Docker container termination?

### ISSUE THREAD

**Issue by nvquanghuy** [mperham/sidekiq#2404]
I'm using Rails + Sidekiq + Docker. I plan to deploy my Sidekiq process inside a Docker container. My jobs are quite long-running (from 10s to 1 minute).

When I kill my docker container (as part of a new deployment), how I can tell Sidekiq to gracefully stop so that no existing jobs are interrupted?

Has anyone faced similar situation before. If so, how do you work around this?

-----------
I also posted this question here - http://stackoverflow.com/questions/30994290/running-sidekiq-inside-docker-handle-termination-of-docker-container

**Comment by mperham** [comment]
This is more of a usage question so lets stick with SO.
