### ISSUE TITLE
sidekiq_options inside a Worker have no effect

### ISSUE THREAD

**Issue by andruby** [mperham/sidekiq#2407]
In a Rails 4.2 application I have a worker which I do not want sidekiq to retry.

```ruby
class EmailWorker
  include Sidekiq::Worker
  sidekiq_options retry: false
end
```

The option is correctly stored on `EmailWorker.sidekiq_options_hash` but doesn't seem to be consumed anywhere. Where in the code is this `sidekiq_options_hash` consumed? I couldn't find a reference outside of `lib/sidekiq/worker.rb`.

My current workaround is to disable retries for all workers by setting the middleware max_retries to 0 in `config/initializers/sidekiq.rb`:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::RetryJobs, max_retries: 0
  end
end
```

**Comment by mperham** [comment]
It's consumed in RetryJobs. https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/retry_jobs.rb#L82

**Comment by Novatec1** [comment]
unable to disable retry too from worker.rb. This is strange.
