### ISSUE TITLE
Calling reliable_push! twice creates endless loop

### ISSUE THREAD

**Issue by jonsgreen** [mperham/sidekiq#2408]
This could easily be considered as developer folly but I had Sidekiq::Client.reliable_push! in two different initializers by mistake and the alias_method chains created an endless loop without much of a backtrace. 

To help others avoid this silly pitfall it might be worth making this method idempotent.

I won't be offended if this is closed and would be willing to pull request if desired.

**Comment by mperham** [comment]
I've seen this before; it needs to be fixed. Thanks for reporting it.
