### ISSUE TITLE
Reliable push requeues job to wrong redis instance

### ISSUE THREAD

**Issue by jonsgreen** [mperham/sidekiq#2409]
I am currently pushing certain jobs to an external Redis instance on a separate server for processing using Sidekiq::Client.via. If the client fails to connect with Redis then the jobs are pushed onto the local queue but then when drained they end up being pushed to the local Redis instance. 

I can write a separate script for then re-queuing those jobs to the proper Redis instance but I am wondering if there is a more elegant approach. Is there a way to have reliable push know the proper Redis Instance to queue those jobs to? Or is there a different approach besides the via method for identifying the Redis instance for pushing to?

**Comment by mperham** [comment]
Yep, good catch.  No good workaround that I can think of at the moment.

**Comment by jonsgreen** [comment]
Would it be totally unreasonable to store the redis_pool with the payloads and then push it via the redis_pool when draining?

**Comment by mperham** [comment]
Got a test case which reproduces the issue now.  Yep, I'll get it fixed soon.

**Comment by jonsgreen** [comment]
Thanks!

**Comment by mperham** [comment]
Fixed and released in 2.0.4.

**Comment by jonsgreen** [comment]
Works perfectly. Thanks again.
