### ISSUE TITLE
Display Process' index number (i.e. the number provided by -i option) on Web UI

### ISSUE THREAD

**Issue by asanghi** [mperham/sidekiq#2410]
Would be nice to know which processes might conflict with each other if the UI displayed the index and hostname next to the process name?

**Comment by mperham** [comment]
Since index is optional and only useful for Sidekiq Pro processes, I didn't want to add more visual clutter to the Busy page.  Have conflicting indexes been a problem for anyone?

**Comment by asanghi** [comment]
Yes they have been. During a recent migration to AWS, we got someone unfamiliar with Sidekiq Pro setup multiple processes with the same -i flag. Took a short while before it could be figured out why we had tasks running twice. I think this would help.
