### ISSUE TITLE
Unable to list jobs in queue with reliable fetch

### ISSUE THREAD

**Issue by asanghi** [mperham/sidekiq#2413]
We're using `sidekiq-pro` but are unable to see running jobs on the `/sidekiq/queues/default` page. I can see that they're running on the `/sidekiq/busy` page listed in the bottom section under `Jobs`. Clicking on the queue link takes me to the aforementioned `/sidekiq/queues/default` page but no jobs listed there. 

I would expect that busy jobs would be listed there with the ability to delete them or kill them from that page.

**Comment by mperham** [comment]
The queues page shows jobs which haven't been picked up by a worker thread yet.  If the queue is empty, this page will be empty.

**Comment by asanghi** [comment]
Understood. Thus no way to kill a running job, right?

**Comment by mperham** [comment]
The only way to stop a running job is to shut down the process which is executing it or the job itself needs to check regularly if it should stop.  There's no safe way to stop a Thread  during execution.
