### ISSUE TITLE
enqueued_at not being set for scheduled jobs

### ISSUE THREAD

**Issue by mrsimo** [mperham/sidekiq#2414]
Hi there,

I think I introduced a bug myself with https://github.com/mperham/sidekiq/pull/2376. I got this job from running:

```ruby
Sidekiq.redis { |conn| conn.lrange("queue:low", -1, -1) }.first
```

And parsing it. The result is a job without an `enqueued_at`:

```
{"class"=>"WarnAboutRunawayTimerWorker", "args"=>[347627860], "retry"=>0, "queue"=>"low", "jid"=>"0fe612fb2190090a88b011d5", "created_at"=>1435642577.071437}
```

The `enqueued_at` is being set in [`atomic_push`](https://github.com/mrsimo/sidekiq/blob/224cfe575ce8dc792a2bf17ec82b2b8547dc91e7/lib/sidekiq/client.rb#L195). Is it possible that one of the Sidekiq Pro features is not adding a proper `enqueued_at`?

Thanks a lot!

**Comment by mperham** [comment]
Is it possible you are injecting jobs into Redis directly, without the Sidekiq API?  I reviewed the Pro code and don't see how this could happen.

**Comment by mrsimo** [comment]
We do a simple `WarnAboutRunawayTimerWorker.perform_at(timestamp, day_entry.id)`.

I'm gonna try to dig deeper!

**Comment by mrsimo** [comment]
I think I pinpointed this to the custom lua script from sidekiq pro. There's an instance of `Sidekiq::Scheduled::FastEnq` that takes jobs from the `scheduled` sorted set and puts them in the proper queue.

Is that possible?

**Comment by mperham** [comment]
Yep, good catch.  I forgot that the atomic scheduler bypasses the client-side API.  Will fix asap.

**Comment by mrsimo** [comment]
Thanks a lot!!!

**Comment by mperham** [comment]
Thank you so much for tracking down the issue.  I don't have a release date for 2.0.5 right now but if you need this badly, let me know.

**Comment by mrsimo** [comment]
We're not in a life or death situation, no. We use this for monitoring, so we get random alerts. We've silenced it in the meantime.

Of course the sooner the better, though ;)
