### ISSUE TITLE
Odd Behavior from API after Upgrade to Sidekiq Pro

### ISSUE THREAD

**Issue by toddmetheny** [mperham/sidekiq#2417]
At the company I work for, we have a very long running, low priority job. When running, it consumes all the resources. As a simple and hopefully temporary solution, I'm checking the number of active low priority workers; if half of the available concurrencies are taken up...we escape the perform method. 

I've been using the api to check for these jobs.

For example: 

```ruby

def see_active
  workers = Sidekiq::Workers.new
  p "active workers: #{workers}, number: #{workers.size}"
		
  @low_running = 0
  workers.each do |process_id, thread_id, work|
  p "work: #{work}"
  p "queue: #{work['queue']}" #, worker: #{work['payload']['class']}"
  p "thread_id: #{thread_id['queue']}"
  p "process_id: #{process_id}"

  if work["queue"] == "high" || thread_id["queue"] == "high"
	puts "in a high queue worker, #{work['class']}"
	puts "work payload: #{work['payload']}"
  elsif work["queue"] == "low" || thread_id["queue"] == "low"
	@low_running += 1
	puts "in a low queue worker"
	puts "work payload: #{work['payload']}"
  end
end

```

I know that there's not supposed to be a 'queue' in that thread_id...but that's the behavior I'm getting. work['queue'] is returning as empty...and thread_id isn't returning a thread_id...but instead the hash that work is supposed to be returning. 

Here's an example of the foreman output:

10:36:31 worker.1 | "work: 2015-07-01 10:36:31 -0400"
10:36:31 worker.1 | "queue: "
10:36:31 worker.1 | "thread_id: low"

We recently upgraded to sidekiq pro...but I don't think that should matter. It was working as you'd expect before (thread_id returned a thread_id, work had a queue). I can't find any documentation that suggests the pro/api works differently for these basic things. 

It's entirely possible that this is happening due to something I'm doing wrong. I just know the api was working differently before the upgrade and was hoping someone could help me understand why. I have a hack-y temporary solution in place that works for now. I'm just worried about it being unstable.

**Comment by mperham** [comment]
Somehow you are using Sidekiq 2.x's API.

**Comment by toddmetheny** [comment]
Ah. Okay. Thank you.
