### ISSUE TITLE
Yet another stack level too deep issue

### ISSUE THREAD

**Issue by jonsgreen** [mperham/sidekiq#2418]
I have a worker that fails with or without Sidekiq-Pro but only when run asynchronously (It succeeds fine when run synchronously in the console). 

With some sleuthing I was able to pinpoint the method in the code which triggers the overflow. It is in the last line of this method of active_record/associations/collection_association.rb
```
      def ids_writer(ids)                                                          
        pk_type = reflection.primary_key_type                                      
        ids = Array(ids).reject { |id| id.blank? }                                 
        ids.map! { |i| pk_type.type_cast_from_user(i) }                            
        replace(klass.find(ids).index_by { |r| r.id }.values_at(*ids))             
      end  
```
If there are any more than 15604 records that are being splatted and passed to `values_at` it bombs. 

Of course I will probably find a way to avoid this method since it is probably not very performant but it does seem strange that this only happens when the job is run asynchronously so I thought I would ask just in case this means anything more to you.

**Comment by mperham** [comment]
Sidekiq runs each job in a fiber, it's probably running out of fiber stack space. Typically this isn't a problem, I suspect your stack was extremely big. Passing 16,000 arguments to a method would do it.
