### ISSUE TITLE
Wrong # of Arugments #perform_in

### ISSUE THREAD

**Issue by PDaily** [mperham/sidekiq#2423]
Hello, I just started my journey into using your gem with my fledgling Rails app. Just installed it, set up redis and got everything connected but immediately ran into some issues. Whenever I call #perform_in
I always get an error about incorrect arguments. Either one too little or one too many (tried it both ways)

Trying to set up a job upon a models creation.

```ruby
  def create
    @game_session = GameSession.new(game_session_params)

    respond_to do |format|
      if @game_session.save
       ...
        CleanupGameSessionsWorker.perform_in(1.hour, @game_session.id)
      else
       ...
      end
    end
  end
```

```ruby
class CleanupGameSessionsWorker
  include Sidekiq::Worker

  def perform(game_session_id)
    @game_session = GameSession.find(game_session_id)
    @game_session.update_attribute(active: false)
  end
end
```

**Comment by mperham** [comment]
Sounds like you forgot to restart Sidekiq, Spring or something else after changing your worker code.

**Comment by PDaily** [comment]
I did, found out I made a very rookie mistake. D:

```ruby
@game_session.update_attribute(active: false)
```

Should have been 

```ruby
@game_session.update_attribute(:active, false)
```

Derp. Sorry @mperham !

Thank you for taking the time to reply, cheers!
