### ISSUE TITLE
Testing code that uses Sidekiq::API

### ISSUE THREAD

**Issue by andrelandry** [mperham/sidekiq#2428]
I recently encountered a issue when trying to test code that uses sidekiq/api.

I have a use case that needs to delete a scheduled job. When running a assertion to ensure the job is removed the test fails since the `jobs` array that replaces the redis queue never gets modified from the api.

Here's a example.

```Ruby
require 'sidekiq/testing'
Sidekiq::Testing.fake!

jobid = HardWorker.perform_in(3.hours, 3)

job = Sidekiq::ScheduledSet.new.find_job(jobid)

job.delete

expect(HardWorker.jobs).to be_empty

```

Am I missing something when it comes to testing code that relies on Sidekiq::API? 

If not, are you interested in a pull request that adds Sidekiq::API to sidekiq/testing?

**Comment by mperham** [comment]
This is by design.  https://github.com/mperham/sidekiq/wiki/Testing#api

**Comment by vroy** [comment]
@mperham I'd be curious to **learn** a little bit more about the reasoning behind this.

Is there anything in `Sidekiq::ScheduledSet` implementation or the Redis behaviour that can't easily be replicated in Sidekiq::Testing?

**Comment by mperham** [comment]
@vroy Same reason ActiveRecord doesn't have a testing mode: it's a layer on top of a data model and therefore doesn't make a lot of sense to mock out.

**Comment by vroy** [comment]
Thanks!

**Comment by andrelandry** [comment]
Thanks for clearing this up, I will use `Sidekiq::Testing.disable!` when testing code that uses the API.
