### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by abmahmoodi** [mperham/sidekiq#2430]
Hi,
My problem is high memory usage of Sidekiq processes.
My web app do not have any traffic currently but memory usage of every sidekiq process start from 9MB and increase every 1 minute 0.1MB.

Rails: 4.2.1
ruby: 2.2.2
Ubuntu server: 14.04 LTS
Sidekiq: 3.4.1

Concurrency: 5

![image](https://cloud.githubusercontent.com/assets/659603/8636412/d3b1b672-2874-11e5-8370-f57b89588829.png)

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#no-leak-issues
