### ISSUE TITLE
sidekiq::web javascript Date parsing error

### ISSUE THREAD

**Issue by bcherrington** [mperham/sidekiq#2432]
I am using Sidekiq with Rails and have setup my DateTime::DATE_FORMATS to be "%d/%m/%Y %H:%M:%S". 

When using this format the JavaScript Date.parse (Chrome) function automatically assumes a m/d/y format. As a result the date conversion become "NaN" when it can't determine the correct date.

This issue is preventing the processed and failed history chart from displaying any data.

I have worked around this issue by changing my DateTime format to using a month name (%b) instead of the number. 

However, I believe a suitable fix for this would be to convert the date to a Unix Timestamp in ruby instead of parsing it in JavaScript.

**Comment by mperham** [comment]
Out of curiousity, why would anyone use that format?  I've never seen a format leading with the day.

**Comment by bcherrington** [comment]
There are various date formats used around the world. The most common format 
is actually DMY (https://en.wikipedia.org/wiki/Date_format_by_country).



However, the ISO8601 standard specifies a YMD format.
