### ISSUE TITLE
Changing Rails default DateTime format results in losing the history

### ISSUE THREAD

**Issue by bcherrington** [mperham/sidekiq#2433]
When changing the default DateTime::DATE_FORMATS[:default] in Rails results in the historic processes and failed date being lost.

I assume that this is because the date is stored in Redis using the formatted date. 

This could be resolved by using a Unix Timestamp format to store the data in Redis. Alternatively, converting dates to an ISO8601 format before storing.

This may also resolve issue #2432

**Comment by mperham** [comment]
One issue please.
