### ISSUE TITLE
Cancel delay job

### ISSUE THREAD

**Issue by phanhongphucit** [mperham/sidekiq#2434]
Hi,
After HardWorker.perform_in(5.minutes, 'bob', 5) I want to cancel this delay job. Is there anyway to do this?

Thanks

**Comment by mperham** [comment]
Please read the FAQ in the wiki. It talks about job cancellation.

**Comment by phanhongphucit** [comment]
Thanks mperham, I look around and see this extension https://github.com/utgarda/sidekiq-status
It help to track the status and unschedule the job.

**Comment by mperham** [comment]
Sure but it's extremely slow if your queue is big.
