### ISSUE TITLE
Option for disabling development banner

### ISSUE THREAD

**Issue by kibs** [mperham/sidekiq#2437]
I would very much like an option for disabling the banner printet when booting in development mode. I am using a guard for restarting Sidekiq when code changes, and this banner takes up all my screen, which also prints out test results.

I will create a pull request myself, but only if the idea is supported?

What do you think?

**Comment by mperham** [comment]
You can monkey patch the banner print method to do nothing.

**Comment by kibs** [comment]
Thanks for getting back this fast.

Actually I did monkey patch it. In an rails initializer i did:

````ruby
module Sidekiq
  class CLI
    private

    def print_banner
      # banner taking up all my screen :)
    end
  end
end
````

It works, but something weird is happening. Every time i boot webrick, or run a rake task, which loads the environment. It prints to the console
````
2015-07-15T19:08:38.550Z 72329 TID-ous09uv44 INFO: Booting Sidekiq 3.4.1 with redis options {:namespace=>"sidekiq", :url=>nil}
````

It doesn't do anything else, and doesn't boot the anything.
If I remove the monkey patch, it stops doing that. So i figured maybe an option would be better, hence my issue here.

**Comment by kibs** [comment]
And if i move the monkey patch to the same initializer where I setup Sidekiq, it stops. Forget about this. :)
