### ISSUE TITLE
reload causes Ubuntu 12.04 upstart script to return "unrecognized service"

### ISSUE THREAD

**Issue by dwilkins** [mperham/sidekiq#2440]
Although the documentation at http://upstart.ubuntu.com/cookbook/ doesn't mention any restrictions on it's usage, the `reload` stanza causes the service to be invisible 

Used at https://github.com/mperham/sidekiq/blob/master/examples/upstart/sidekiq.conf#L40

Line 40 of examples/upstart/sidekiq.conf

Since 12.04 precise is very old, there's probably not a good reason to remove the line - maybe just a comment around it.

**Comment by mperham** [comment]
Odd.  I think 12.04 has a pretty old version of Upstart, perhaps it doesn't support the reload command?  Becoming invisible seems really bizarre.
