### ISSUE TITLE
Redis connection pooling

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#2443]
We currently have a connection pool set up for Sidekiq namespaced under `sidekiq` but we also have non-Sidekiq calls to Redis that we'd like to set up a connection pool for. Setting up a separate connection pool will effectively double the connections we set up to Redis. Is there a good way to use the same connection pool for all Redis calls while still having only the Sidekiq calls namespaced? If not currently, perhaps this could be a new feature?

**Comment by mperham** [comment]
It's not possible today.  Perhaps with some modifications to redis-namespace you could make something work.  Another thought: can you un-namespace Sidekiq?

**Comment by jakemack** [comment]
Okay, that's what I was suspecting but I wanted to confirm. Perhaps I'll look into redis-namespace a little. However, removing the namespace might work as well, I just need to confirm that we're not using the same keys anywhere else. It's nice having all of Sidekiq's keys easily discoverable because they're under a namespace, but I have a feeling it's not necessary. Anyway, thanks for the incredibly fast response!

**Comment by TheCorp** [comment]
mpherham for president.

**Comment by mperham** [comment]
If elected, I promise to make JavaScript illegal.

**Comment by jakemack** [comment]
Where are the social features, Github? I need to upvote this, pronto!
