### ISSUE TITLE
double-namespacing in reliable scheduler call

### ISSUE THREAD

**Issue by cainlevy** [mperham/sidekiq#2445]
When the reliable scheduler is called, the key referencing the set of active queues appears to be namespaced twice. It's prefixed once manually (`"#{@prefix}queues"`), then again by [redis-namespace](https://github.com/resque/redis-namespace/blob/master/lib/redis/namespace.rb#L403-L418).

For example, I configured Sidekiq to use `namespace: 'sq'`. When the scheduler calls the script, it invokes:

```
evalsha f60ddc52617059576f4a28d56a9c01528076edd0 2 sq:retry sq:sq:queues 1437297250.1235125 sq:
```

Not sure what the implications are. Maybe the Sidekiq UI doesn't show the full list of queues in some edge cases?

**Comment by mperham** [comment]
Well, :hankey:  I didn't realize that redis-namespace would auto-namespace key arguments to Lua scripts.  Your guess is right, it should just mean the Web UI might not show queues that have jobs in them.
