### ISSUE TITLE
Is it safe to force a single hostname+index for all worker processes?

### ISSUE THREAD

**Issue by sbleon** [mperham/sidekiq#2446]
We are running Sidekiq Pro 2.0.4. We use a tool to automatically scale our worker machines based on CPU load. We've just discovered that we are losing work when workers are scaled out of existence (only if they're running jobs that take longer than the shutdown quiet period). The options that we see are:

1. Disable auto-scaling, which has the potential to increase our hosting bill quite a lot. We've done this temporarily to avoid losing work.
2. Force all Sidekiq processes to share a single hostname and index (with the `-h` and `-i` flags). This feels like a hack, but we don't see any actual negative consequences to doing so. We don't fully understand reasoning behind the naming of the reliability queues. *Would this have adverse effects?*

**Comment by jonhyman** [comment]
The way that we do it is that our autoscale down process runs a script which stops the processes (it just does a `kill -s int` for each of the processes), and the script sleeps and checks every few seconds to see fi they've stopped. It `exit(0)` or `exit(1)` if it worked, and that exit code is used by the decommission script to determine whether or not it can _actually_ decom the machine.

If it `exit(1)`, it re-runs the script later. If that still fails, it notifies our devops team and they inspect logs and manually remove the next day.

**Comment by mperham** [comment]
If you share indexes, you can easily get jobs executing more than once.

Your auto-scaling code needs to send the USR1 quiet signal well in advance of scale down.
