### ISSUE TITLE
push_bulk with a nonsensical class, but no error?

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2447]
I recently made a stupid human error in a Rails console and wrote the equivalent of

```ruby
Sidekiq::Client.push_bulk("class" => "abcd1234", "args" => args)
```

This happened because I mistakenly used `FooJob.perform_async` as the value of `"class"` instead of just `FooJob`.

I was surprised to discover that when the jobs were pulled off the queue to be worked on, no error was raised, the jobs didn't seem to show up as processed or failed or retried anywhere in the web UI.

Is this expected? It seems like I should've hit a NameError on trying to turn `"abcd1234"` into a job class.

**Comment by mperham** [comment]
This should have gone to Sidekiq's global error_handlers when `constantize` fails:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L46
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L61

The default handler prints the backtrace to stdout.  You saw nothing?

**Comment by aprescott** [comment]
I checked again, it does indeed print to stdout with a `NameError`, you're right. It doesn't go into the retry queue, though.

This is on. Sidekiq v3.3.4 / Sidekiq Pro v2.0.3.

**Comment by aprescott** [comment]
(It also never hit New Relic, although I'm unsure why that is.)

**Comment by mperham** [comment]
It can't go into the retry queue.  Retry is implemented via middleware and constantize must take place before the middleware dispatch.

**Comment by mperham** [comment]
This error is more of the form "job is corrupt and can never be processed".  I try to minimize the window were jobs can be lost but I'm not sure how to improve the status quo.  Ideas welcome.

**Comment by aprescott** [comment]
While it makes me uneasy to have jobs lost for this sort of thing, in practice it's probably less of a concern because the review + testing would very likely caught the human error. (Especially if you stick to using constants, not strings, where possible, so you get a NameError before it even hits Sidekiq.)

Happy to close this, just wanted to make sure there wasn't a glaring problem!

**Comment by mperham** [comment]
Gonna close without action because no one else has reported this issue.  I'll consider options if there have been several reports and/or strong feelings.
