### ISSUE TITLE
Error with ActiveJob when upgrade to 3.4.2 from 3.3.4

### ISSUE THREAD

**Issue by thomastran** [mperham/sidekiq#2449]
Hi,
Today i've upgrade gem to 3.4.2 version from 3.3.4 and i met this error when start application. I had to rollback to 3.3.4 version to be able to continue.  Here is error message:

```
/RAILS_APP_PATH/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/worker.rb:27:in `included': You cannot include Sidekiq::Worker in an ActiveJob: JOB_NAME  (ArgumentError)
```
Can you take a look?

**Comment by mperham** [comment]
The error is as clear as I could make it.  You are including `Sidekiq::Worker` in a subclass of ActiveJob::Base.  Don't do that.

**Comment by thomastran** [comment]
@mperham  it made me confused  because it worked with previous versions. 
BTW, thanks for your quick response +1 +1 +1 +1

**Comment by edipox** [comment]
Hi, I am using ActiveJob with Sidekiq and I want to add some Sidekiq specific configuration (retries related).  In view that I can not include Sidekiq::Worker in an ActiveJob subclass. What would you recommend me to do?

**Comment by mperham** [comment]
@edipox ActiveJobs cannot use the Sidekiq native API; it makes no sense to include Sidekiq::Worker in an ActiveJob::Base, which is why it was made an error.  If you want to tune sidekiq_options, you need to make your jobs native Sidekiq::Workers.
