### ISSUE TITLE
Integrate Rails 5's new Interlock

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2450]
Rails 5 now supports [thread-safe code reloading](https://github.com/rails/rails/pull/17102)!!!!!! :tada: :cake:

Integrate the new Interlock into the Processor so we can reload Workers before executing them.  This is Rails 5+ in development mode only so we'll need to keep the current code flow for Rails 3 and 4 and other environments.

**Comment by ryansch** [comment]
Wow! :tada: :balloon:

**Comment by davydovanton** [comment]
looks amazing! :tada: :star2:

**Comment by hbin** [comment]
:clap: :clap: :clap:

**Comment by mperham** [comment]
Coming in 4.2.0.

**Comment by lastobelus** [comment]
This is so great. Thanks.

Something is borken in rails though...sidekiq jobs reload reliably now, but controllers & helpers not so much.
