### ISSUE TITLE
RuntimeError at /sidekiq/scheduled you need to set up a session middleware *before* Rack::Protection::AuthenticityToken

### ISSUE THREAD

**Issue by matisoffn** [mperham/sidekiq#2452]
I've followed the auth instructions and chosen an option from the Wiki: https://github.com/mperham/sidekiq/wiki/Monitoring

I just ran a `bundle update` and it updated Sidekiq to v3.4.2.

In my routes.rb:

```ruby
mount Sidekiq::Web => '/admin/sidekiq'
```

In my config.ru:

```ruby
require 'sidekiq/web'
map '/sidekiq' do
  use Rack::Auth::Basic, "Protected Area" do |username, password|
    username == 'user' && password == 'pass'
  end

  run Sidekiq::Web
end
```

**Comment by mperham** [comment]
Note `Rack::Session::Cookie`:

https://github.com/mperham/sidekiq/wiki/Monitoring#standalone

**Comment by mhuggins** [comment]
I'm using the [Rails HTTP Basic Auth from Routes](https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes) steps on Sidekiq 3.4.2 and getting this error as well.
