### ISSUE TITLE
Enable a mode to not track jids in a batch?

### ISSUE THREAD

**Issue by jonhyman** [mperham/sidekiq#2458]
In the past I had been mildly concerned about Sidekiq keeping track of all the jids in a batch in a Redis set (since deletions of large sets is expensive), but my slowlog never showed anything for Sidekiq Pro 1.x. We just upgraded to Sidekiq Pro 2.x today, and we've already seen entries in our slowlog of the `del` of the various keys, and I'm sure it's the `-jids` key that caused the deletes to be slow. I guess that slowlog doesn't track slow deletes caused by key expiration, but this has potentially been happening a lot.

We routinely have batches with hundreds of thousands of jids, so these deletions are going to be expensive. I don't need this part of the API, what are your thoughts on letting someone turn it off for performance in `Sidekiq.options`? If it was turned off, all methods that interact with the key in `Status` could raise an error.

**Comment by mperham** [comment]
I always prefer to avoid feature switches.  Leads to exponential code paths and testcases.  I'm afraid that this will lead to whack-a-mole over time, chasing inadvertent O(n) operations.

Would nesting smaller groups of jobs into child batches solve the problem?  Any drawbacks?

**Comment by mperham** [comment]
What if we removed the entry from the `jids` set after success?  This would scale down the size so that the final del would take no time at all.

**Comment by jonhyman** [comment]
Oh yes! I'm a fan of that suggestion! That would help us a lot.

**Comment by mperham** [comment]
Try master and let me know if it looks good.

**Comment by jonhyman** [comment]
I can't since it's a private repo, but that looks good to me. Can you cut a release? We get notified by our slowlog monitoring about this a few times an hour.

**Comment by mperham** [comment]
2.0.7 released

**Comment by jonhyman** [comment]
Btw, just to follow up on this, 2.0.7 completely fixed the issue. Our slowlog doesn't pick this up anymore.
