### ISSUE TITLE
Incompatibility between Rack::Session and ActionDispatch::Request::Session

### ISSUE THREAD

**Issue by codebender** [mperham/sidekiq#2460]
It looks like I'm running into this rails bug with the new 3.4.2 CSRF vulnerability fix (https://github.com/rails/rails/issues/15843).

### My Test basic auth config
```ruby
Sidekiq::Web.use Rack::Session::Cookie, secret: 'fake secret here'
Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ['mike perham', 'for president']
end
```

Anyone have a workaround suggestion?

![image](https://cloud.githubusercontent.com/assets/987305/8938605/d917ed48-351c-11e5-95cb-efee6652afee.png)

**Comment by mperham** [comment]
LOL at your test data, but no clue how to fix that.  Looks like an issue between Rack and Rails, not Sidekiq.

**Comment by jonhyman** [comment]
There have been a lot of these issues lately, here's what we do and it works great on the latest version of Sidekiq and we're using Rails.

First, we use Google Auth for our Sidekiq endpoint. Basic auth sucks, you don't want to be typing in a username and password on your phone if you need to check Sidekiq on the go (and we wanted to get the benefit of 2FA behind our Sidekiq dashboard). We use the `omniauth` and `omniauth-google-oauth2`

In a Rails initializer, we have this code

```ruby
# Setup OmniAuth
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, configatron.oauth2.google.client_id, configatron.oauth2.google.client_secret, {
           :prompt => "select_account",
  }
end
```

```
# Setup Sidekiq
Sidekiq::Web.use Rack::Session::Redis, :redis_server => configatron.redis.session_url, :expires_in => 1.hour
Sidekiq::Web.use OmniAuth::Builder do
  provider :google_oauth2, configatron.oauth2.google.sidekiq_client_id, configatron.oauth2.google.sidekiq_client_secret, {
                             :prompt => "select_account", :name => "sidekiq_google_oauth2",
                         }
end
```

Then we wrote an extremely small auth layer:

```ruby
module Sinatra
  module GoogleOauth
    def self.registered(app)
     app.before do
        if self.session[:authenticated] || request.path_info =~ /auth/
          pass()
        end

        redirect to ('/auth/sidekiq_google_oauth2')
     end

      app.get '/auth/sidekiq_google_oauth2/callback' do
        auth = self.request.env['omniauth.auth']
        # Whitelist users who can access this in a configatron value
        if configatron.oauth2.google.sidekiq_authenticated_users.any? {|pattern| auth.info.email =~ pattern}
          self.session[:authenticated] = true
          return redirect to '/'
        else
          Rails.logger.warn{"Someone unauthorized is trying to gain access to Sidekiq: #{auth.info}"}
          return "Unauthorized user"
        end
      end

      app.get '/logout' do
        self.session.clear()
        return redirect to '/'
      end

    end
  end
  register GoogleOauth
end


module Sidekiq
  class Web
    register Sinatra::GoogleOauth
  end
end
```

I realize this is totally orthogonal to what you're doing, but if you find yourself unable to get it working, you can always do this setup and get the benefit of not using basic auth. :)

**Comment by mperham** [comment]
Looks like @jonhyman is shooting for vice president in my administration.

**Comment by jonhyman** [comment]
:laughing:

**Comment by codebender** [comment]
@jonhyman Thanks for the suggestion! I know basic auth is simple, but for many users of sidekiq I imagine that is good enough.

I have always used Sidekiq Web along side a rails app, but it seems with this latest change it must run in its own process because of the rails bug I mentioned above. It would be great for us to have an out of the box solution to this. 

So here is my question: Is it possible to hook Sidekiq Web onto an existing rails app using solely the sidekiq gem and basic auth?

**Comment by mperham** [comment]
This is a Rails 4.2 app running Sidekiq Web without issue:

https://github.com/mperham/sidekiq/tree/master/myapp

**Comment by codebender** [comment]
@mperham I can confirm that with your monkey patch https://github.com/rails/rails/issues/15843#issuecomment-125784043 sidekiq web is working in my rails app...:see_no_evil:...:crying_cat_face:

**Comment by HoneyryderChuck** [comment]
@mperham the example above for google auth integration assumes that `Sidekiq::Web` is a sinatra app. That's not the case anymore, right? Any more up-to-date solution for this? As this issue is still being linked from the [wiki](https://github.com/magicbell-io/sidekiq_web_google_sign_in)

**Comment by mperham** [comment]
@HoneyryderChuck That's a user-supplied integration.  Someone else will have to supply an updated version.

**Comment by yassenb** [comment]
Here is my updated take, based on https://github.com/mperham/sidekiq/issues/2460#issuecomment-125694743, working with Rails 5.2, `sidekiq` 6.3, `omniauth` 2.0, `omniauth-google-oauth2` 1.0.

In an initializer put
```ruby
require 'sidekiq/web'

Sidekiq::Web.use Rack::Session::Redis,
                 redis_server: 'your-redis-url',
                 expires_in: 1.hour
Sidekiq::Web.use OmniAuth::Builder do
  T.cast(self, OmniAuth::Builder).provider(
    :google_oauth2,
    'your-client-id',
    'your-client-secret',
    { prompt: 'select_account' }
  )
end

module Sidekiq
  class Web
    register GoogleOauth
  end
end
```

where `GoogleOauth` is defined like
```ruby
module GoogleOauth
  def self.registered(app)
    app.before do
      next if session[:authenticated] || request.path_info =~ %r{/auth(/|$)}

      # With Oauth 2.0 a redirect won't work because it has to be a POST request to sign in
      html = <<~HTML
        <form action="#{root_path}auth/google_oauth2" method="post">
          <input type="hidden" name="authenticity_token"
                 value="#{session[:csrf]}" />
          <button type="submit">Sign in with Google</button>
        </form>
      HTML
      throw :halt, [200, {}, [html]]
    end

    app.get '/auth/google_oauth2/callback' do
      auth = request.env['omniauth.auth']
      if auth.info.email =~ /@your-domain-here.com$/
        session[:authenticated] = true
        redirect root_path
      else
        Rails.logger.warn "Unauthorized access to Sidekiq: #{auth.info}"
        'Unauthorized user'
      end
    end

    app.get '/logout' do
      session.clear
      redirect root_path
    end
  end
end
```

**Comment by RichardsonWTR** [comment]
Dear @mperham , can you help me with how to write a middleware like mentioned in https://github.com/mperham/sidekiq/issues/2589#issuecomment-145423753 ? 
I've just spent several hours trying how to integrate an OpenID/oauth2 provider with sidekiq, with no success. 
If you help me by providing just a skeleton of middleware, I can try implementing it.

**Comment by RichardsonWTR** [comment]
How could I integrate  https://github.com/nov/rack-oauth2 with Sidekiq?  
[The example](https://github.com/nov/rack-oauth2/wiki/Client-Init) shows the initialization process like this
```ruby
client = Rack::OAuth2::Client.new(
  identifier: YOUR_CLIENT_ID,
  secret: YOUR_CLIENT_SECRET,
  redirect_uri: YOUR_REDIRECT_URI,
  host: 'server.example.com'
)
```
But the Sidekiq middleware integration with a rack middleware works like this:
```ruby
Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ['mike perham', 'for president']
end
```
Is there a way to provide an object to `Sidekiq::Web::use`? Any documentation related to this initialization process will help

**Comment by mperham** [comment]
Sidekiq::Web is a standard Rack app. See https://github.com/mperham/sidekiq/blob/main/myapp/simple.ru for an example microapp. You’d integrate your rack middleware just like the Cookie middleware shown.

**Comment by Nitrodist** [comment]
A good solution is to use Rails route constraints to meter the access ([see 'Advanced Constraints' in the Rails guide](https://guides.rubyonrails.org/routing.html#advanced-constraints)):

```
class AuthorizedSidekiqConstraint
  def self.authorized?(request)
    session[:user_id].present? && User.find(session[:user_id]).can_manage?('sidekiq')
  end
end

Rails.application.routes.draw do
  constraints -> (request) { AuthorizedSidekiqConstraint.authorized?(request) } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end
```

**Comment by nerixim** [comment]
Just in case anyone still looking for Sidekiq Web + Google Auth solution:
https://gist.github.com/phil-monroe/345b5bfcac4e37df52429fa5e3f3aeab

Worked for me with Rails 6.1/Sidekiq 6.5.9 (but failed with 6.3.1) and Sidekiq Cron.
