### ISSUE TITLE
Sidekiq 3.4.2 produces Rack::Protection::AuthenticityToken Error when mounting in Padrino

### ISSUE THREAD

**Issue by hbrysiewicz** [mperham/sidekiq#2461]
[Example Repository](https://github.com/hbrysiewicz/padrino-sidekiq-example/tree/master)

When trying to mount Sidekiq application within Padrino, `Rack::Protection::AuthenticityToken Error` is produced. See example repository for bare bones demonstration. The exact same project works when Sidekiq is explicitly set to 3.4.1. 

Much thanks to the Padrino team and also @jc00ke on the Sidekiq team for the great communication up until now.

**Comment by mperham** [comment]
Sorry you are seeing this pain.  Sidekiq 3.4.2 requires a session store to fix a severe security issue.

This behavior is not a bug and I'm not an expert in Padrino so I can't tell you how to add a session store.  You'll need to consult the Rack / Padrino docs for details.  A bare Rack example is here:

https://github.com/mperham/sidekiq/wiki/Monitoring#standalone

**Comment by hbrysiewicz** [comment]
Hi @mperham I actually did consult the Padrino team before bringing this back to the Sidekiq team. https://github.com/padrino/padrino-framework/issues/1944 who seem to think it is a Sidekiq issue. The standalone doc you have referenced does not actually fix the issue. I realize both teams want to blame the other but would you mind just looking at the example repo or maybe talking to the Padrino team about where the issue lies?

**Comment by jc00ke** [comment]
I believe #2462 should fix this issue. Fingers crossed!
