### ISSUE TITLE
Several process in the pidfile

### ISSUE THREAD

**Issue by papiveron** [mperham/sidekiq#2463]
Hi,

I'm try to manage sidekiq processes start and stop on my system.

I'm using with *"-C"* option with a *".yml"* config file where the pid file is referenced.

I noticed that the pidfile can content only one process pid, even if you run several processes.

In the other hand, when I put all my running process pid in the pid file and run 
```
sidekiqctl stop $pidfile
```
, it just stops the process whose pid is at the first line, and leave the rest.

My question is, can one use sidekiqctl to stop all sidekiq running processes?

Thanks,

Regards,
Eugène NG

**Comment by mperham** [comment]
The pidfile should be specified on the command line, not in the config file.

The answer to your question is no, it only shuts down the PID in the pidfile  that you pass as an argument.
