### ISSUE TITLE
More information on security fixes in Sidekiq and Sidekiq Pro gems

### ISSUE THREAD

**Issue by reedloden** [mperham/sidekiq#2467]
I was reading https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md, and I noticed:

2.0.2 -- "**SECURITY** Fix batch XSS in error data. Thanks to moneybird.com for reporting the issue."

1.9.1 -- "**SECURITY** Fix XSS in batch description, thanks to intercom.io for reporting the issue. If you don't use batch descriptions, you don't need the fix."

Also, https://github.com/mperham/sidekiq/blob/master/Changes.md mentions:

3.4.2 -- "Fix CSRF vulnerability in Web UI, thanks to Egor Homakov for reporting. [#2422]"

In looking through PRs/issues, I also found:

3.4.0 - #2309 (not mentioned in Changes.md at all)

3.4.0 - #2330 (also not mentioned in Changes.md)

Can you provide more information on each one (as well as any other security fixes in Sidekiq or Sidekiq Pro), as I'd like to add them to https://github.com/rubysec/ruby-advisory-db so other people are aware of the issues (and make sure they have up-to-date Gemfile.lock files). Main thing to know is which versions of the gem are affected by each issue.

Thanks!

**Comment by reedloden** [comment]
I requested CVEs for the above issues in Sidekiq (http://seclists.org/oss-sec/2015/q3/267). I will do the same for Sidekiq Pro once I have more information about those two issues (or any more that I haven't found yet).

**Comment by reedloden** [comment]
I got some OSVDB IDs assigned for the Sidekiq issues. Submitted a PR to ruby-advisory-db to get those issues added -- https://github.com/rubysec/ruby-advisory-db/pull/196.

**Comment by mperham** [comment]
Could you be more specific about the information you want?  You should be able to derive the fixed version from tags.  Give me a template to answer and I'll fill out what I can.

**Comment by reedloden** [comment]
Sure, looking for the following basic information for each security issue:

```
Summary: [One-line summary of the issue]
Description: [Longer description of issue, providing whatever details are needed]
Fixed by: [Links to commits of the fix(es)]
Affected: [Versions of Sidekiq and/or Sidekiq Pro that the issue affected]
Fixed in: [Versions of Sidekiq and/or Sidekiq Pro that the issue was fixed in (the new release(s))]
Reported/Found by: [*optional* -- person/company who found issue, for credit purposes]
```

Doesn't need to be super detailed (though, the more detail the better). Mostly just want to ensure all security issues are tracked in the ruby-advisory-db so people know they need to upgrade.

As I mentioned, I think I have most of the detail for the Sidekiq-specific vulnerabilities tracked already (see https://github.com/rubysec/ruby-advisory-db/tree/master/gems/sidekiq), but I don't have access to the Sidekiq Pro github repository to do code splunking myself. There may also be other Sidekiq-specific issues I'm missing, so would love to know about them as well.

**Comment by mperham** [comment]
Since you are a Pro customer, you can apply for access and gather all the data you need.  Reasonable?  I will try to keep to that template in the future.

https://github.com/mperham/sidekiq/wiki/Commercial-collaboration

**Comment by reedloden** [comment]
Sure, that's fine. Submitted issue #2481 to get access.

**Comment by reedloden** [comment]
Submitted https://github.com/rubysec/ruby-advisory-db/pull/201 to add `sidekiq-pro` security issues. I'm going to close this out, as I think that covers everything.

Again, happy to help in the future if you ever have a question about how to handle disclosure of a security vulnerability.

Thanks!

**Comment by mperham** [comment]
You'll be my go-to guy, thanks for doing this!
