### ISSUE TITLE
jid of jobs inside a batch in batch callback

### ISSUE THREAD

**Issue by scottchiang** [mperham/sidekiq#2471]
Is there a way to get the jid of the jobs in a batch in the batch callback?

**Comment by mperham** [comment]
The batch only tracks the JIDs of jobs which have not completed successfully.  So you can get the jids of jobs which did not succeed:

```ruby
def on_complete(status, options)
  p ["Current set of failed jobs:", status.jids]
end
```

But by definition that set will be empty when the success callback is run.

**Comment by scottchiang** [comment]
@mperham Is there any way for me to grab the jids in the success callback as well? I saw this issue https://github.com/mperham/sidekiq/issues/2458 and it seems like their problem was my solution.  Can I still grab all the JIDs in redis somewhere?

**Comment by mperham** [comment]
Unfortunately not.  You can track the JIDs yourself but, as you note, Pro doesn't provide a master list of JIDs anymore.

**Comment by jonhyman** [comment]
@scottchiang what's your use case? Deletion of large sets can be very disruptive on Redis, so it's much better for Sidekiq to slowly drain its `-jids` set. Am curious about what you need the jids for.

**Comment by scottchiang** [comment]
@jonhyman I actually use batches for a single job.  I'm using batches just for the callback functionality.  I have an table in my database that has `jid` as one of its columns.  Inside the callback, I need to query for that object using `jid`.

**Comment by jonhyman** [comment]
Oh. But there's no strong reason to use jid then,  right? You could add a random string to your :on callback and save that to the db as well? That isolates you from sidekiq interface changes.

**Comment by scottchiang** [comment]
yeah that would be one solution.  Thanks for your input.
