### ISSUE TITLE
Sidekiq SortedEntry delete performs a redundant lookup

### ISSUE THREAD

**Issue by pik** [mperham/sidekiq#2472]
For example if `Sidekiq::ScheduledSet.newt.find_job(jid).delete` is run it will actually run the job-set delete after the find_job and perform an expensive operation https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L523 when a `Sidekiq.redis {|c| c.zrem(@parent.name, @value) }` should suffice. (Not to mention the loop doesn't break but actually runs even after a matching jid has been found). 

I'm also have a couple questions/concerns about how the Jobset delete is implemented: 

a) What is the purpose of the single-value-only scoring functionality? `conn.zremrangebyscore(name, score, score)` does anyone actually need to remove jobs at an exact time and while still being unable to remove jobs scheduled within a time-range? Does this serve an internal purpose? 

b) It gives no information about what was removed in it's output, which makes extending Sidekiq rather uncomfortable -- for example SidekiqUniqueExtension needs to hook into the `delete` commands of the api in order to prevent mutexes living after the jobs which created them have been deleted, currently it is only possible to do that by redeclaring the entire Jobset delete method, which isn't very nice at all. Can this be reworked?

**Comment by mperham** [comment]
If you can provide a better impl, I'd be happy to review. It's quite possible it's not optimal.
