### ISSUE TITLE
Switch to static site

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2479]
We're currently using harp to generate the new sidekiq.org pages so there's a complicated process to build and update the static content.  Once the site is stable, tidy the static HTML pages so they can be edited directly and stop using harp.

**Comment by seuros** [comment]
You need help with this ?

**Comment by mperham** [comment]
Not yet, @sethterpstra needs to sign off.  I believe he was looking into making the site look OK without JS.

**Comment by sethterpstra** [comment]
I'll get to this tonight.

**Comment by mperham** [comment]
Static site is now live.
