### ISSUE TITLE
Corrupted unsorted chunks 

### ISSUE THREAD

**Issue by ishank18** [mperham/sidekiq#2480]
I am using ruby 2.2.1 and sidekiq 3.4.2, but getting following after running around 20, 30 jobs. There are around 7000 jobs queued.

*** Error in `sidekiq 3.4.2 xxxxx [5 of 5 busy]': free(): corrupted unsorted chunks: 0x00007fca9c2867b0 ***

Thanks.

**Comment by mperham** [comment]
Upgrade your ruby VM and all native gems to the latest versions. See the problems and troubleshooting wiki page for how to do this.

**Comment by ishank18** [comment]
Seems like it was a issue with thread safety, reduced concurrency to 1 and things are working fine for now.

Thanks for the quick response.

**Comment by mperham** [comment]
Upgrading your versions is often fixes those bugs. :-) glad you found a workaround.

**Comment by ishank18** [comment]
Still facing the same problem, that worked for a day and after that the issue recurred. I have updated all version of gems and even ruby version as well.

**Comment by mperham** [comment]
What does this print out?

```
bundle exec ruby -e 'puts Gem.loaded_specs.values.select{ |i| !i.extensions.empty? }.map{ |i| i.name }'
```

**Comment by ishank18** [comment]
`nokogiri
bcrypt
byebug
hitimes
libv8
mysql2
puma
therubyracer`

This are the gem name shown after running above command

**Comment by mperham** [comment]
Dump `therubyracer` if possible.  It's not thread-safe and will lock up sidekiq.

Otherwise I'm not sure what is causing your problem.  Google "corrupted unsorted chunks" and you'll see it's usually caused by a bug in C code somewhere.  You can try rebuilding MRI from scratch.
