### ISSUE TITLE
Restarting sidekiq with upstart script

### ISSUE THREAD

**Issue by panmari** [mperham/sidekiq#2482]
When trying to restart my sidekiq service configured after the example from here https://github.com/mperham/sidekiq/tree/master/examples/upstart, the sidekiq instances are not terminated properly. Only after killing them on my own via 

    kill $(ps aux | grep 'sidekiq' | awk '{print $2}')

I can successfully restart the job (with `sudo service workers restart`). I'm using Ubuntu 14.04.3 LTS. Is my configuration wrong or is this the expected behavior?

**Comment by mperham** [comment]
You need to give us more precise data.  Show us your exact .conf file, show us the exact command that is failing.

**Comment by panmari** [comment]
Here's my [worker.conf](https://gist.github.com/panmari/e1812a705167a0d73e1f), more or less a direct copy of the one in the trunk. 

Same goes for [sidekiq.conf](https://gist.github.com/panmari/b7caa2171fb21de2f299).

**Comment by mperham** [comment]
Let's see your sidekiq.yml.

**Comment by panmari** [comment]
```yml
---
:logfile: ./log/sidekiq.log
:concurrency:  5
:queues:
  - [high_priority, 7]
  - [default, 5]
  - [low_priority, 3]
```

**Comment by mperham** [comment]
Hmm, can't explain why it's not working then. Looks ok to me.

**Comment by panmari** [comment]
That's what I thought! Shouldn't an upstart job kill its child processes by default?

**Comment by mperham** [comment]
Upstart sends TERM to the child process.  If the child process forks away (e.g. by daemonizing itself), Upstart can lose track of the process.  It's unfortunately complicated.

**Comment by panmari** [comment]
This issue still persists for me. @mperham any ideas what could be causing this?

**Comment by panmari** [comment]
Wouldn't the fix descriped [here](http://superuser.com/questions/708275/how-to-stop-all-child-processes-spawned-by-a-service) help?

**Comment by mperham** [comment]
I don't see how that fix is relevant to you.  You're only exec'ing the bundle binary, which should work fine.  Is your sidekiq.conf still the same?

**Comment by panmari** [comment]
yes
