### ISSUE TITLE
Sidekiq.pid not created

### ISSUE THREAD

**Issue by soapy1** [mperham/sidekiq#2483]
When starting up a sidekiq worker in a docker container using fig it doesn't look like a tmp/pids directory is created. So, when sidekiq is starting up it fails. My config looks like

```
  :pidfile: ./tmp/pids/sidekiq.pid
  :verbose: false
  :queues:
    - default
    - mailers
```

I was wondering if there was any way to get around this and have the tmp/pids file to be created if it doesn't already exist?

**Comment by mperham** [comment]
`tmp/pids` is a Capistrano convention, I believe.  You need to run `cap deploy:setup` once to create its directory structure.  Sidekiq will not create directories.

**Comment by ryansch** [comment]
@soapy1 Any reason why you can't create the directory in your `Dockerfile`?

**Comment by soapy1** [comment]
@ryansch we are trying to avoid adding it to the `Dockerfile` because we use the same one to create two images that differ by the command you pass into it. And, both images do not require `tmp/pids/sidekiq.pid`. 
However, I think this is a problem that can be solved using [ansible files](http://docs.ansible.com/ansible/file_module.html) so I'm going to explore that now.

**Comment by ryansch** [comment]
@soapy1 Have a look at the way elasticsearch deals with entrypoint scripts: https://github.com/docker-library/elasticsearch/blob/258e9b89c3fe675b966a49deb0c26727c7d20551/1.7/docker-entrypoint.sh

I've used that in our `Dockerfile`s for simple things like `mkdir -p tmp/pids`.
