### ISSUE TITLE
segfault running test app w/ Rubinius

### ISSUE THREAD

**Issue by digitalextremist** [mperham/sidekiq#2489]
Discovery in #2438, running the test application at `myapp/` as described in its `readme.md` leads to:

**Segmentation Fault:** https://gist.github.com/digitalextremist/bf64b5b340cb09d70a93

The above is with `rbx-2.5.8` ... using `rbx-2.5.2` results in different failure, in comments.

---

The `segfault` will differ on what worker dies, but they all die here:

```
IO.select in kernel/common/io.rb:931 (+218)
```

Which then cascades, taking out all other running workers.

The call to the segfaulting result originates in `sidekiq` here:

```
while readable_io = IO.select([self_read])
```

In `sidekiq/lib/sidekiq/cli.rb`

---

After the initial `segfault` -- as the process is terminating, workers will continue completing work until the actor system shuts them down. At first, only the worker who hit the `segfault` will die.

---

The number of running workers is relevant:

* With `200` as shown in `readme.md`: **Fail.**
* With `20`: **Fail.**
* With `2`: **Fail.**
* With `1`: **Pass.**

/cc: @brixen

**Comment by digitalextremist** [comment]
With `rbx-2.5.2` instead of a `segfault` you will see:

```
*** Error in `sidekiq 3.4.1 myapp
```

Then the application will not respond to `SIGINT` and must be given `SIGTERM`

**Comment by mperham** [comment]
IMO this bug should be in Rubinius, not Sidekiq.  VM crashes should be impossible with pure ruby, right? Meaning this is a Rubinius bug, not a Sidekiq bug.

**Comment by digitalextremist** [comment]
Agreed. Will move and close this tonight.
