### ISSUE TITLE
Proposal: Add default prefix to queue names

### ISSUE THREAD

**Issue by IvanShamatov** [mperham/sidekiq#2490]
My current problem is that I have couple of Rails applications on one server, and both of them use Logging and Subscription management through ```logs``` and ```subscription``` queues, but format of messages in different applications are different.

Surely I can (knowing this issue) just mention different queue name in ```sidekiq_options```, but I found it unexpectedly, when I got message in sidekiq log of other application with message for first one. More than that if format is similar the message for first app will work and may cause data loss or corruption.

My suggestion is to add prefix to all queue name, getting it from rails main module name or from sidekiq config or command line. I would like to help with that, if you agree and consider which way is the best for that

**Comment by mperham** [comment]
Sounds like you want to namespace. Have you considered using the config.redis namespace option?

**Comment by IvanShamatov** [comment]
Nope. But that will solve my issue. Thanks.
