### ISSUE TITLE
Sidekiq-Pro 3.4.2 uninitialized constant Rack::Protection

### ISSUE THREAD

**Issue by bartimaeus** [mperham/sidekiq#2491]
@mperham I just updated to sidekiq-pro to version 3.4.2. Attempting to start sidekiq results in an error 

```ruby 
uninitialized constant Rack::Protection
```

**Comment by onlyyouandty** [comment]
How did you resolve this @mperham

**Comment by mark-ellul** [comment]
I just added rack-protection to my Gemfile to get around it!

**Comment by bartimaeus** [comment]
Thanks for answering this @mark-ellul. Looks like I did the same.
