### ISSUE TITLE
Oddity while passing ActiveRecord objects as parameters

### ISSUE THREAD

**Issue by bytenel** [mperham/sidekiq#2492]
I have a Sidekiq worker that I want to call with an ActiveRecord object. I have the object in memory already and doing another call to the database in this instance (since it's an external database server) is rather expensive. As such I don't necessarily want to do that if I can avoid it. I call the worker when I create this particular ActiveRecord object and then pass self to the workers perform_async method. When the worker calls perform with the passed parameter however instead of getting what I expect (the ActiveRecord object) I get the to_s of the ActiveRecord object which is not helpful. I believe this is a problem in Sidekiq?

**Comment by bytenel** [comment]
Reread documentation, sorry! Guess I may have to use ActiveJob to get what I want.

**Comment by mperham** [comment]
You can convert it to a hash of attributes and pass it that way.  ActiveJob won't do what you want: it does another lookup under the covers.

**Comment by bytenel** [comment]
Man what a bummer... so the GlobalID isn't like a memory address or something? It's just another id based lookup on the table? Weak. Be nice if somehow we could get that functionality.

**Comment by ryansch** [comment]
Your sidekiq client and sidekiq worker might not even be on the same machine (it's not for us).  You can't use a memory address or other transient/localized information.
