### ISSUE TITLE
sidekiq_options are lost when using .delay syntax

### ISSUE THREAD

**Issue by Nowaker** [mperham/sidekiq#2494]
We've got a base class for all workers - we use `perform_later` to schedule jobs:

```ruby
class SidekiqJob
  include Sidekiq::Worker

  def self.perform_later *args
    self.perform_async *args
  end
end
```

And such jobs look like this:

```ruby
class SomeJob < SidekiqJob
  def perform
    puts 'howdy'
  end
end
```

We also have TrackableJobs:

```ruby
class TrackableJob < SidekiqJob
  def initialize progress_id
    @progress = Progress.find progress_id
    @progress_id = progress_id
  end

  def success
    @progress.update! finished: true
  end

  def self.perform_trackable progress_id, *args
    job = self.new progress_id
    job.perform *args
    job.success
  end

  def self.perform_later user, *args
    progress = Progress.new
    progress.user_id = user.is_a?(Integer) ? user : user.id
    progress.save!

    self.delay.perform_trackable progress.id, *args

    progress.id
  end
```

But their usage is still the same:

```ruby
class SomeTrackableJob < TrackableJob
  def perform
    puts 'howdy'
  end
end
```

The difference is scheduling a TrackableJob actually means scheduling `perform_trackable` to be run, which prepares the ground, then calls the real `perform`, then finalizes stuff. 

Problem: `sidekiq_options` for TrackableJobs are lost. So is `sidekiq_retries_exhausted` or other options set with a block. Nothing works as promised in documentation. I lost two hours trying to make it work, with no result.

Reason: TrackableJob uses `.delay`. Underneath it uses `Sidekiq::Extensions::DelayedClass`, which is  just a wrapper. Therefore, `sidekiq_options` can't work.

What should be done: either document `sidekiq_options` won't work when `.delay` syntax is used, or... make it work. ;) The latter is probably about allowing any method names to be scheduled, not only `perform`.

**Comment by Nowaker** [comment]
I'm quite surprised I closed this issue. I don't know how it happened, I don't remember it and never intended to close it. Funny.

**Comment by mperham** [comment]
The documentation shows how to set options for delay calls:

https://github.com/mperham/sidekiq/wiki/Delayed-extensions#advanced-options

Delay works on any class, it can't assume the class is a Sidekiq::Worker.

**Comment by Nowaker** [comment]
As a Sidekiq new user, that's what I did:

1. Read https://github.com/mperham/sidekiq/wiki/Getting-Started.
1. Read https://github.com/mperham/sidekiq/wiki/The-Basics. This mentions both `perform_async` and `delay`. Everyone's assumption: using it this way or the other is the standard way.
3. Read https://github.com/mperham/sidekiq/wiki/Best-Practices.
4. Read https://github.com/mperham/sidekiq/wiki/Using-Redis.
5. Okay, this is enough to get started with Sidekiq effectively. Now it's time for feature that I specifically need.
2. Googled for "sidekiq retry", read https://github.com/mperham/sidekiq/wiki/Error-Handling. This mentions `sidekiq_options`.
9. So I use it, right? Nope, doesn't work, because I also use `.delay`.

Hope this clarifies why I believe that's a documentation defect and needs a fix.

Note: I probably didn't make my way to https://github.com/mperham/sidekiq/wiki/Delayed-extensions. But if I did, I wouldn't understand https://github.com/mperham/sidekiq/wiki/Delayed-extensions#advanced-options as a statement that `sidekiq_options` doesn't work with `.delay`. This should be very clear there. At the same time, when `sidekiq_options` is first mentioned, it needs to be clearly stated that it doesn't work with `.delay`. 

> What should be done: either document sidekiq_options won't work when .delay syntax is used, or... make it work. ;) The latter is probably about allowing any method names to be scheduled, not only perform.

Or even - `.delay` method could detect `sidekiq_options` being present on the class, and print a warning or raise an Exception, e.g. "Sidekiq detected sidekiq_options on the class. Only execute_async respects these settings. Don't use delay or delete sidekiq_options from the class.".

**Comment by mperham** [comment]
Thanks for the detailed feedback, I appreciate it.  I've updated the Basics and Delayed pages to downplay the delayed extensions even more.

**Comment by Nowaker** [comment]
Thanks. I'd also suggest to put a sentence "Warning: `sidekiq_options` doesn't work here." after the code snippet in https://github.com/mperham/sidekiq/wiki/Delayed-extensions#advanced-options.
