### ISSUE TITLE
Can't Install Sidekiq (3.4.2)  because timers (4.0.2) is removed from rubygem.org

### ISSUE THREAD

**Issue by TangRufus** [mperham/sidekiq#2497]
celluloid (0.16.1) depends on timers (4.0.2) which has been removed from rubygem.org
Thus, installing Sidekiq (3.4.2) gives 
```
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/gems/timers-4.0.2.gem)
An error occurred while installing timers (4.0.2), and Bundler cannot continue.
Make sure that `gem install timers -v '4.0.2'` succeeds before bundling.
```

**Comment by seuros** [comment]
install it with timers 4.0.1.

**Comment by KevinTurnbull** [comment]
I tried installing timers 4.0.1 and had no success. I was still stuck with this same bug. 

Any other known workarounds?

**Comment by seuros** [comment]
```bundle update timers```

or better use sidekiq 4 which don't use timers at all.
