### ISSUE TITLE
How to limit sidekiq processes?

### ISSUE THREAD

**Issue by TangMonk** [mperham/sidekiq#2498]
I running a sidekiq server on my 2GB vps server, today I found I memory grows up from 500M to 1.9G. 

I figure out the sidekiq server eat most memory, when I kill them all, the memory cut down to about 400M.

when I start sidekiq, it create 21 processes for me. (the process will grows up in the feature and eat my memory again)
![image](https://cloud.githubusercontent.com/assets/3498786/9299873/ee1b1b6c-44f2-11e5-8499-b335db044627.png)

i wanna know:

- I set sidekiq concurrency to 10, it means one sidekiq process only create 10 thread. But how to tune the  sidekiq processes?
- how to make sidekiq to lazy load, just like phusion passenger, when the server idle, then close some process, and then server business grow, then create more process.

**Comment by pratik60** [comment]
+1....Sidekiq seems to start out great, and then eventually grow to occupy tremendous memory, to the point that we can only server side reboots.

**Comment by mperham** [comment]
You are seeing threads, not processes.  Press Shift-H in htop to show only processes.  Read the man page for more info.

@pratik60 Your application is occupying tremendous memory.  Sidekiq runs your application code.  You need to tune your application memory usage.

**Comment by TangMonk** [comment]
@mperham thanks
