### ISSUE TITLE
is sidekiq works well under the condition of load-balancing

### ISSUE THREAD

**Issue by wenbo** [mperham/sidekiq#2506]
In our project,  we are using load-balancing to serve http requests. so there are multiple web servers. I'm planning to run sidekiq worker at every web server and to run redis database on one server.
   what I am concerning is that whether Sidekiq works well under such load-balancing condition.

**Comment by mperham** [comment]
Yes, that will work great.

https://github.com/mperham/sidekiq/wiki/Deployment#network-architecture
