### ISSUE TITLE
Sidekiq failing after first request

### ISSUE THREAD

**Issue by grhansen** [mperham/sidekiq#2510]
I'm seeing some really weird behavior from my sidekiq instance.  I'm using v 3.3.0 running on ruby 2.2.2p95.  I'm using the upstart scripts you provided and running 2 workers.  On a fresh start/restart the when i make a request to the application UI, the background job will fire off, run to a successful completion and log the details of the run.  I can see the execution in the Dashboard when watching the sidekiq UI.  When I try and execute the same process again through the application UI the process is failing.  The background process executes b/c the db record is updated with an error message that would occur in the code.  However, nothing is logged to either log file for the 2 workers.  The /sidekiq UI Dashboard does show the job being processed.  I'm trying to execute the same application process both times and it works the first time, but then something/somewhere tries to process it the second time and fails.  I've got sidekiq running at log level debug but nothing shows during the execution of the 2nd request.

I've verified there are no ghost sidekiq processes running (ps aux | grep sidekiq) and even restarted the box to make sure a process wasn't hung.

What else can I try to debug what code is handling the second request and then figure out why it's failing when it should succeed.

Thanks in advance.
Greg

**Comment by mperham** [comment]
No clue.  Upgrade sidekiq?

**Comment by grhansen** [comment]
Mike,

Didn't realize I was a bit behind on my version.  I'll definitely upgrade to the latest version and see if that makes a difference.  In another experiment, I've turned off the upstart workers and submitted a request again, and it appears the request is being processed.  When testing locally w/o a sidekiq instance running the model stays in the "queued" state until i start sidekiq. So it appears I do have an instance of sidekiq running, somehow/somewhere on that box. I'll try and track it down.

Thanks again for the reply.
Greg
