### ISSUE TITLE
Worker depends on its queue

### ISSUE THREAD

**Issue by skrypalyk** [mperham/sidekiq#2512]
Hi

I have this code in my worker
```ruby
module Accounting
  class ExportWorker
    include Sidekiq::Worker
    sidekiq_options :queue => :default

    def perform
      # do something
      Accounting::ExportWorker.perform_in(1.second)
    end

  end
end
```

When queue is default - worker is called only once, then it fails silently( no excpetion in log, counter of failed jobs is incremented ).
If I set new queue(critical for example) - everything works.

No no other workers are in progress.

sidekiq.yml
```
:verbose: false
:concurrency: 2
:queues:
  - [default, 7]
  - [critical, 6]
  - [carrierwave, 5]
  - [mailer, 3]

```

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#jobs-are-mysteriously-disappearing-or-failing-without-anything-in-the-logs
