### ISSUE TITLE
Can I push a non-ActiveRecord object into Sidekiq queue?

### ISSUE THREAD

**Issue by chidumaga** [mperham/sidekiq#2513]
When I try to do this with an <a href="http://github.com/makandra/active_type">ActiveType</a> object I understandably get an UnknownPrimaryKey error as explained in this<a href="http://stackoverflow.com/questions/32230268/sidekiq-throws-active-record-unknown-primary-key-error-on-active-type-object">StackOverflow post</a>. Is there any way around this? 

Any help will be greatly appreciated!

**Comment by ryansch** [comment]
Does the object only exist in memory?  It sounds like you'll need to serialize it to be able to pass it to sidekiq and then deserialize it into an object again in your worker.

**Comment by mperham** [comment]
You cannot push arbitrary ruby objects to Redis, as explained in the Best Practices:

https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple
