### ISSUE TITLE
How do i know when the worker complete

### ISSUE THREAD

**Issue by VoTaiTri** [mperham/sidekiq#2514]
Hi everybody
In controller, after i use sidekiq to start many worker, i want to know that, when do all worker complete to do something else.
so, how can i do that?
i need some help...
thank

**Comment by davydovanton** [comment]
Hello, I think [this](https://github.com/mperham/sidekiq/wiki/FAQ#how-can-i-tell-when-a-job-has-finished) will be helpful fir you

**Comment by VoTaiTri** [comment]
thanks @davydovanton
