### ISSUE TITLE
Why I need read/write access to github profile to use the Dashboard with GitHub OAuth?

### ISSUE THREAD

**Issue by RobertoSchneiders** [mperham/sidekiq#2516]
The [readme](https://github.com/mperham/sidekiq/wiki/Monitoring#standalone-with-github-oauth) sugests the use of `user` [scope](https://gist.github.com/technoweenie/419219#scopes) for GitHub OAuth, which provides `DB read/write access to profile info only.`. 

I tried to change this for the `no scope` option and the dashboard didn't work. So, why the dashboard need write permissions?

Is there a way to use OAuth with read only permissions?

**Comment by mperham** [comment]
That code is not supported, it's just there as a (hopefully helpful) example.  I've never used OAuth before so I have no idea why any scope is required.
