### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [mperham/sidekiq#2520]
Do you follow Semantic Versioning (semver.org)? If yes, can this be mentioned in README. If not, can you consider it?

**Comment by mperham** [comment]
No, we do not. Semantic versioning is a pipe dream that doesn't actually work. 

https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by pravi** [comment]
Thanks for the reply. Glad to see not everyone shares your opinion and some libraries already committing to it (https://github.com/typhoeus/typhoeus/issues/470 and https://github.com/zombor/Validator/commit/b485289b45948ec3e829e8760b4221ee215931c9)
