### ISSUE TITLE
sidekiq stuck, all my workers are busy [10/10] for a long time

### ISSUE THREAD

**Issue by zhaohanweng** [mperham/sidekiq#2521]
My sidekiq workers has been stuck one by one then all my jobs just stuck in the queue.

I am using sidekiq 3.3, and jruby 1.7.21,  celluloid (0.17.1.2)

I have been reading similar issues, such as network call `timeout`, `require 'resolv-replace'`, and added them to my code as well, but I still see a few worker get stuck, not as often now.
All the jobs are from same queue, and the jobs get stuck are random.

Here's the TTIN output https://gist.github.com/zhaohanweng/1ed28dd1c1072a26dd3f

**Comment by mperham** [comment]
That TTIN output looks normal.  You have two threads doing DNS resolution and another few making an HTTP request.  I don't see anything abnormal.

**Comment by zhaohanweng** [comment]
Thanks for look into this. I have finally resolved the issue, the issue is still from the network calls. It's the way I add the timeout, now it's picking up the timeouts properly.
