### ISSUE TITLE
Web UI: select redis instance to view

### ISSUE THREAD

**Issue by donpinkster** [mperham/sidekiq#2526]
In our microservices architecture we have multiple services using the same redis instance for queueing and executing jobs. Main reason for this is that we can have a single web ui to monitor all the queues and dead jobs. 

The ideal situation would be to give each services its own redis instance, and you can configure Sidekiq Web UI with an array of redis instances so you can somehow get a dropdown in the UI to select the correct Redis instance.

What are your thoughts about this?

**Comment by mperham** [comment]
Sidekiq Pro can host multiple Web UIs in the same process, [as explained here](https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#202).

Once you have that set up, I think simple is better: create a bookmark folder in your browser toolbar and add a bookmark for each Web UI instance, e.g. /sidekiq1, /sidekiq2, etc.  Sharding is not a common case and I prefer not to add complexity to the Web UI to support this case directly.

**Comment by donpinkster** [comment]
Thanks! Somehow I missed that one, that will solve our problem.
