### ISSUE TITLE
Sidekiq + Threads causes DB connection to explode

### ISSUE THREAD

**Issue by ankuriitk** [mperham/sidekiq#2527]
Hi,

We are using Sidekiq for our background job processing. Some of those jobs do lot of computation and were really slow. Hence I added threads to parallelize things. I religiously give up ActiveRecord connection when the threads finish up the task assigned to them. What we have noticed is that I run a regular cron job without Sidekiq then I don't have too many database connections issues - in fact pg_stat_activity remains constant. However, if I run the same job with Sidekiq repeatedly then pg_stat_activity keeps increasing until I hit pool size limit after which my Sidekiq job starts failing with too many db connections. Is this a known issue with Sidekiq? Should I not be using threads within a Sidekiq job?

**Comment by mperham** [comment]
You can use threads in Sidekiq but you need to clean up the connections when they are done.  Sounds like you are not doing this correctly:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/active_record.rb#L8

**Comment by ankuriitk** [comment]
Thanks Mike for the quick reply. I was doing ActiveRecord::Base.connection.close instead of ::ActiveRecord::Base.clear_active_connections!. Will try the other one. Is there a difference between the two?

**Comment by mperham** [comment]
Read the source and tell us.
