### ISSUE TITLE
sidekiq_retries_exhausted with extracted (not inline) block

### ISSUE THREAD

**Issue by mooreniemi** [mperham/sidekiq#2529]
I don't want this to fall into the bike-shedding area, so feel free to close this if you think it does. I wanted to show you an issue I had and the solution I came up with that I feel "meh" about.

5 or more of my workers have a custom block for `sidekiq_retries_exhausted`, but all the blocks (inline) are the same. So naively I thought to myself, "ok let's extract them to one place!"

Here's the test I came up with to work through that:

```
require 'rspec'
require 'sidekiq_extensions'
require 'support/dummy_worker'
require 'pry'
#require 'spec_helper'

describe SidekiqExtensions do
  let(:msg) do
    {
      'class' => 'DummyClass',
      'args' => '1,2,3',
      'error_message' => 'StandardError'
    }
  end
  let(:worker) { RetryWorker.new }
  it 'works with #sidekiq_retries_exhausted' do
    expect(Sidekiq).to receive_message_chain(:logger, :warn).
      with("Failed DummyClass with 1,2,3: StandardError")
    worker.sidekiq_retries_exhausted_block.call(msg)
  end
end
```

Nothing unusual in the worker except my attempt at in-lining:
```
require 'sidekiq_extensions'
class RetryWorker
  include Sidekiq::Worker
  include SidekiqExtensions
  sidekiq_retries_exhausted &:send_to_rails_logger
end
```

Which is defined over here:
```
require 'sidekiq'
module SidekiqExtensions
  def send_to_rails_logger(msg)
    Sidekiq.logger.warn "Failed #{msg['class']} with #{msg['args']}: #{msg['error_message']}"
  end
end
```

Confusingly (to me), when I ran the spec I see:
```
rspec spec/lib/sidekiq_extensions_spec.rb

  1) SidekiqExtensions works with #sidekiq_retries_exhausted
     Failure/Error: worker.sidekiq_retries_exhausted_block.call(msg)
     NoMethodError:
       undefined method `send_to_rails_logger' for #<Hash:0x62d89480>
     # ./spec/lib/sidekiq_extensions_spec.rb:19:in `(root)'


Failures:

  1) SidekiqExtensions works with #sidekiq_retries_exhausted
     Failure/Error: worker.sidekiq_retries_exhausted_block.call(msg)
     NoMethodError:
       undefined method `send_to_rails_logger' for #<Hash:0x62d89480>
     # ./spec/lib/sidekiq_extensions_spec.rb:19:in `(root)'

Finished in 0.019 seconds (files took 1.17 seconds to load)
1 example, 1 failure
```

Unless I change the test to explicitly give the receiver in (`worker.sidekiq_retries_exhausted_block.call(worker, msg)`), it uses msg as the receiver.

Of course, after some thought I realize, "ohh hmm, `&:` will call `to_proc` which expects `obj` as its first argument" so I'll either see `ArgumentError: no receiver given` or Hash being used as the receiver depending on how I do the call.

So, dutifully, I restructure to make use of methods instead of procs:

```
require 'sidekiq_extensions'
class ExhaustedWorker
  include Sidekiq::Worker
  extend SidekiqExtensions
  sidekiq_retries_exhausted &method(:send_to_rails_logger)
end
```

And it works. :smile: 

But this seems kinda weird to me. I wondered if you could think of a different solution that'd enable me to extract all these logging calls into a single module/class/whatever.

**Comment by mperham** [comment]
Yep, it may feel weird to you but that's how it's designed to work.  As you discovered, you can convert an inherited method to a block and use that in your workers.

**Comment by mooreniemi** [comment]
Perhaps may want to document that somewhere then? Save someone else the confusion. Thanks again!
