### ISSUE TITLE
Sidekiq can lose jobs even with reliable fetch

### ISSUE THREAD

**Issue by sanjayprabhu** [mperham/sidekiq#2531]
I'm on sidekiq version `2.17.8` (and sidekiq-pro `1.5.1`) and investigating an issue where sidekiq is not performing some jobs even with reliable queueing enabled. 

Currently, looks like this can happen if there was an exception in any of the middleware in the stack before it hits the `RetryJobs` middleware. Or, say, an exception in the `RetryJobs` middleware anytime before it queues up the retry (less likely).

This is because in [this block of code](https://github.com/mperham/sidekiq/blob/v2.17.8/lib/sidekiq/processor.rb#L40-L62):

```ruby
        ack = true
        begin
          msg = Sidekiq.load_json(msgstr)
          klass  = msg['class'].constantize
          worker = klass.new
          worker.jid = msg['jid']

          stats(worker, msg, queue) do
            Sidekiq.server_middleware.invoke(worker, msg, queue) do
              worker.perform(*cloned(msg['args']))
            end
          end
        rescue Sidekiq::Shutdown
          # Had to force kill this job because it didn't finish
          # within the timeout.  Don't acknowledge the work since
          # we didn't properly finish it.
          ack = false
        rescue Exception => ex
          handle_exception(ex, msg || { :message => msgstr })
          raise
        ensure
          work.acknowledge if ack
        end
```

It ack's the job even though the middleware may not have executed successfully. You can reproduce this locally by running sidekiq within foreman, sending it a lot of jobs and `ctrl-c`ing it. [This line](https://github.com/mperham/sidekiq/blob/v2.17.8/lib/sidekiq/middleware/server/logging.rb#L10) fails with `Broken pipe @ io_write - <STDERR>` and you lose the job (`perform` was never called on the worker, `RetryJobs` was never reached, so it doesn't try to retry but we still ack the work so nobody else is going to work on it). My [test worker](https://gist.github.com/sanjayprabhu/350d952f47c5a71fdae2) if you're interested.

Thoughts on how to fix this? Maybe start with `ack=false` and do something like

```ruby
            Sidekiq.server_middleware.invoke(worker, msg, queue) do
              ack = true # we attempted to perform the job
              worker.perform(*cloned(msg['args']))
            end
            ack = true # middleware invoked successfully (may or may not have decided to perform the job)
```

I can open a PR for that if you think that sounds reasonable.

The real kicker is, this codepath is not hit in production for us (`RetryJobs` is the first middleware in our chain), so there's at least one more bug which is causing us to lose jobs. I'm continuing to investigate that.

**Comment by ryansch** [comment]
Interestingly, that method is exactly the same on `v3.5.0` so this may still be an issue.

@sanjayprabhu Can you reproduce this on the newest releases of sidekiq and sidekiq-pro?

**Comment by mperham** [comment]
@sanjayprabhu I think you're right that the code can be improved.  SIGINT is not expected in production though, it's typically only used in development mode for Ctrl-C handling.  Can you reproduce with the expected TERM signal?

Can you send a PR with your suggested fix against master?

**Comment by sanjayprabhu** [comment]
Foreman captures the SIGINT and sends a SIGTERM to it's processes. So sidekiq is only receiving SIGTERM:

```
11:18:19 jobcounter.1  | severity=info dyno=unknown pid=86145 tid=owu2b8v34 ["JobCounter JID-3ee8916729521d329e0eb85c"] done: 0.064 sec
^CSIGINT received
11:18:19 system        | sending SIGTERM to all processes
11:18:19 jobcounter.1  | terminated by SIGTERM
```

Also, yes, this is still happening with the latest versions.

Alright, I can open a PR against master, but I'd also like to backport it to `2.17`
