### ISSUE TITLE
Workers die on Heroku (Celluloid::TaskTimeout linking timeout)

### ISSUE THREAD

**Issue by geoffharcourt** [mperham/sidekiq#2533]
I had this issue occur twice within 36 hours after subjecting my workers on Heroku to a somewhat prolonged stream of unusually intense work (1-4 Heroku worker dynos scaled up and down manually, executed about a million jobs in 24 hours). We scaled up our worker dynos to do a bunch of data import for some new clients, but typically we operate with just one dyno.

My permanent Sidekiq worker dyno just died twice. In both cases, this was the exception:
```
Celluloid::TaskTimeout: linking timeout of 5 seconds exceeded with receiver: #<Sidekiq::Processor:0x007f71d003db28>

vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:208 in block in linking_request
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:97 in exclusive
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:421 in exclusive
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:182 in linking_request
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:56 in monitor
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:67 in link
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:206 in new_link
vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/lib/sidekiq/manager.rb:103 in block in processor_died
vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/lib/sidekiq/util.rb:16 in watchdog
vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/lib/sidekiq/manager.rb:97 in processor_died
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:15 in block in call
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:76 in block in task
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:339 in block in task
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:44 in block in initialize
vendor/bundle/ruby/2.2.0/gems/celluloid-0.17.1.2/lib/celluloid/task/fibered.rb:14 in block in create
```

We had a lot of jobs fail during our data import (parts of the expected data were incomplete), but at the two times where the workers failed there was not an unusual number of retries or exceptions being raised. As soon as I restarted the app on Heroku, everything churned along again without issue (until time number 2), and we haven't had this issue recur since. 

Has anyone else had this issue occur (on Heroku or otherwise) with an idea as to what might be causing it? We're using [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs) on a few of our workers, but no other plugins, etc.

We're on Rails 4.2.4, using PostgreSQL 9.3.9, Sidekiq 3.5.0, and Redis 3.0.2 (Heroku's Redis service).

**Comment by geoffharcourt** [comment]
Update: I had a string of 300 memory errors reported on Heroku leading up until the time I restarted. I'm not sure if the restart was after the errors stopped (and the worker dyno died), or if the memory errors stopped because I executed the restart. My current theory is that Heroku started throttling the dyno because I was consuming over 1.5x the allowed memory before my restart, and that the root cause of the problems is a memory leak in my app.

**Comment by mperham** [comment]
Hmmm, if you're out of memory, all bets are off.  Coincidentally #2532 covers another OOM scenario.

**Comment by geoffharcourt** [comment]
Yeah, I saw that issue and it prompted the investigation into memory. If this happens again I'll update the issue with logs and comments, but I think the main culprit's been identified. Thanks for the happy hour support earlier today, @mperham.
