### ISSUE TITLE
Reliable fetch doesn't work in production without -i option

### ISSUE THREAD

**Issue by sumakumardey** [mperham/sidekiq#2539]
Same code works well in staging not in production without -i option what exactly is the issue?
2015-09-07T12:40:57.662Z 17306 TID-9dy2c ERROR: Actor crashed!
ArgumentError: reliable fetch requires a process index option
	/ruby/2.1.0/gems/sidekiq-pro-2.0.5/lib/sidekiq/pro/fetch.rb:18:in `initialize'
	/ruby/2.1.0/gems/sidekiq-3.4.1/lib/sidekiq/fetch.rb:21:in `new'
	/ruby/2.1.0/gems/sidekiq-3.4.1/lib/sidekiq/fetch.rb:21:in `initialize'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-09-07T12:40:57.662Z 17306 TID-3di7ls ERROR: Actor crashed!

**Comment by jonhyman** [comment]
Check out https://github.com/mperham/sidekiq/wiki/Reliability#server. You should use `-i` in staging as well, there's some code which only requires it in production for convenience in running in dev (otherwise it sets it to 0).
