### ISSUE TITLE
Set process to a worker

### ISSUE THREAD

**Issue by harrysuren** [mperham/sidekiq#2551]
I'm having bit struggle in using Sidekiq with multiple workers and multiple Sidekiq processes.

I'm having three workers (Lets say **"worker1", "worker2" and "worker3"**) and three sidekiq processed (Lets say **"process1", "process2" and "process3"**).

> In my current structure the workers are running on any process which is available. But what I want is the worker1 should run on process1 and worker2 should run on process2 and so on.

My sidekiq processes are: 

`process1: bundle exec sidekiq -q default`
`process2: bundle exec sidekiq -C config/myapp_sidekiq.yml`
`process3: bundle exec sidekiq -q process3`

**Comment by mperham** [comment]
answered on stackoverflow
