### ISSUE TITLE
Is it recommended to create custom methods in the sidekiq worker class?

### ISSUE THREAD

**Issue by krzkrzkrz** [mperham/sidekiq#2552]
So far I see `peform` as a reserved method. Any other method names to be cautious about?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L23

Sidekiq::Worker defines:

```
jid
logger
```

Additionally, Sidekiq::Pro::Worker defines:

```
bid
batch
valid_within_batch?
```

**Comment by krzkrzkrz** [comment]
@mperham do you recommend creating custom methods in the worker class?

**Comment by mperham** [comment]
Workers are normal Ruby objects.  Treat them as such.
