### ISSUE TITLE
Sidekiq Enterprise limiter names don't allow `0` in them

### ISSUE THREAD

**Issue by fnordfish** [mperham/sidekiq#2554]
Given the example from the wiki:

```ruby
user_throttle = Sidekiq::Limiter.bucket("stripe-#{user_id}", 30, :minute, wait_timeout: 5)
```

This will fail with every user_id which happen to have a `0` in it. For example: `"stripe-120"` will fail with:
> ArgumentError: Invalid name 'stripe-120', should be named like a Ruby variable: my_limiter.

My current work-around is to `.tr('0', 'O')` the bucket name.

**Comment by mperham** [comment]
Ugh, typo.  `1-9` instead of `0-9`.

**Comment by mperham** [comment]
0.7.2 released.

**Comment by ryansch** [comment]
`/\A[\w-]+\Z/` would get you there as well

**Comment by mperham** [comment]
Is \\w just [A-Za-z0-9]?

**Comment by ryansch** [comment]
And underscore.
