### ISSUE TITLE
Stats history issue with custom Date default format

### ISSUE THREAD

**Issue by stan** [mperham/sidekiq#2559]
Sidekiq v3.5.0

I'm using a custom Date::DATE_FORMATS[:default] in my application, and this breaks the expectation that `#{Time.now.utc.to_date}` will always return something formatted as "%Y-%m-%d".

Not sure if this should be considered an issue on Sidekiq part, but using `#{Time.now.utc.strftime "%Y-%m-%d"}` instead for the failed and processed history redis keys would fix this.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L106 & https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L118

**Comment by mperham** [comment]
Ack.  We partially fixed this in https://github.com/mperham/sidekiq/commit/513334445cd6ae24b88820ac7b8f06a637cc4c71 but missed those lines.  Want to send a PR so you get credit for the fix?

**Comment by stan** [comment]
Sorry meant to and was sidetracked.. Thanks for the fix!
