### ISSUE TITLE
Fake testing mode requires Worker class to exist

### ISSUE THREAD

**Issue by brandonhilkert** [mperham/sidekiq#2562]
Hey Mike!

I'm implementing a smaller app and looking to use Sidekiq a poor man's message bus. Ideally, I'd like the following to happen:

- Application 1 enqueues a Job on a queue the application's worker processes are not listening to
- Application 2 has a worker process that ONLY listens on that isolated queue and contains the worker class to process the job

In Application 1, I ended up adding a bare worker class to support testing:

```ruby
class SpecialWorker
  include Sidekiq::Worker
  sidekiq_options queue: :special

  def perform(connection_id)
  end
end
```

```ruby
    assert_difference 'SpecialWorker.jobs.size', 2 do
      # invoke the code that enqueues a job
    end
```

Without the job class I could use the raw client:

```ruby
        Sidekiq::Client.push(
          "queue" => "special",
          "class" => "SpecialWorker",
          "args" => [connection.id]
        )

```

However, now with the tests, I can't easily tell whether the job's been enqueued unless I rely on mocks (which i was hoping to avoid), I think because of the call to [`constantize` on the Worker class](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb#L71), which fails because the class doesn't exist in Application 1 (`NameError: uninitialized constant SpecialWorker`).

I'm wondering if there would be any downfalls to using a hash for the stored jobs in the fake implementation and allow access to the class jobs (eg `SpecialWorker.jobs`) if it exists. Otherwise, create an alternative API to access jobs from that global testing hash. 

I'd be happy to submit a PR for it, but wanted to get your thoughts/feedback first. It's totally cool if this is too special a use case.

**Comment by aprescott** [comment]
Why not define the class for the purpose of the test in app 1? Either something like RSpec's `stub_const` or simply defining `SpecialWorker` to be a constant that exists only in the test suite. What's the issue with using mocks?

**Comment by brandonhilkert** [comment]
Feels tangential to value of the tests to me. Why would I add classes that
don't need to be in production to the test suite?

In general, mocking would work, but I'd rather have a direct interface to
the queues without needing to define the worker.

On Saturday, September 19, 2015, Adam Prescott <notifications@github.com>
wrote:

> Why not define the class for the purpose of the test in app 1? Either
> something like RSpec's stub_const or simply defining SpecialWorker to be
> a constant that exists only in the test suite. What's the issue with using
> mocks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2562#issuecomment-141683327>.
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com

**Comment by mperham** [comment]
For this type of integration testing, I think it is reasonable to define the worker class in your test suite.  Looking back, I could have also provided a queue test helper which collected the jobs, independent of any class name.

```ruby
assert_equal 1, Sidekiq::Queues["default"].size
assert_equal "SpecialWorker", Sidekiq::Queues["default"].first["class"]
Sidekiq::Queues.clear
```

I think that might be a reasonably clean approach but I'm not sure how well it would integrate into the current testing infrastructure we already provide.

**Comment by mperham** [comment]
If you want to implement something like that and dogfood it yourself, let me know how it goes.
