### ISSUE TITLE
warning: toplevel constant Session referenced by ActionDispatch::Request::Session

### ISSUE THREAD

**Issue by sivalingams** [mperham/sidekiq#2563]
/Users/user/.rvm/gems/ruby-2.1.5/gems/sidekiq-3.5.0/lib/sidekiq/web.rb:267: warning: toplevel constant Session referenced by ActionDispatch::Request::Session

Just now upgraded sidekiq to 3.5.0 and I'm getting this warning in rails.

**Comment by mperham** [comment]
I can't fix ActionDispatch::Request::Session in Sidekiq.
