### ISSUE TITLE
What settings can I look at if I continually get a connect timeout error?

### ISSUE THREAD

**Issue by HuckyDucky** [mperham/sidekiq#2567]
I'm trying to run ```sidekiq-ent``` on a MySQL server for the first time.

I'm running a single worker with a ```concurrency``` of 50. I have configured ```database.yml``` to have a ```pool``` of 50.

The first 50 jobs go up just fine. After that everything comes to a screeching halt with:

    ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds

It appears these connections aren't being released.

**Comment by mperham** [comment]
Sidekiq does not use active record connections itself. Any connection leakage will be in your app code or gems.  You will need to post your code if you want us to help.
