### ISSUE TITLE
History chart is not refreshed during polling on the dashboard

### ISSUE THREAD

**Issue by ArturT** [mperham/sidekiq#2572]
When I'm on the dashboard and polling is enabled I can see that some processes are in progress on the first chart but on the history chart at the bottom the amount of processes that happened today is still zero. I need to refresh page to see updated bottom chart. Would be great if data on the history chart be refreshed during polling.

![screen shot 2015-09-25 at 12 13 58](https://cloud.githubusercontent.com/assets/662545/10098216/cf4160a6-637f-11e5-8baa-dc354e51a326.png)

**Comment by mperham** [comment]
The page refreshes the real-time stats.  The history stats are another set of data; gathering them would add more overhead just to refresh one minor datapoint.
