### ISSUE TITLE
Quiet All and Stop All not worling

### ISSUE THREAD

**Issue by tdeo** [mperham/sidekiq#2573]
Hello,

I've recently updated to Sidekiq 3.5.0, and the Quiet All and Pause All buttons seem not to work anymore.

I'm running Rails 4.2.3 and ruby 2.2.2 on Ubuntu 14.04.

Any idea what might be happening?

**Comment by mperham** [comment]
Did you read the recent changelog entries?

**Comment by tdeo** [comment]
Actually, the problem came from bundler. I had two versions of Sidekiq in my vendor folder, 3.2.6 and 3.5.0, and the Web UI was still displaying 3.2.6. I figured that out because the API for those buttons changed the parameters name.

However, the workers were running under 3.5.0, so I guess they weren't communicating properly (saw that the endpoint post /busy changed in between 3.2.6 and 3.5.0 from the source code)

Finally, running `bundle clean` removed the old 3.2.6 version from `vendor/`, and after restarting everything it works again. 

Had I missed something in the Changelog ?
