### ISSUE TITLE
Unique jobs fail to enqueue

### ISSUE THREAD

**Issue by thommahoney** [mperham/sidekiq#2574]
I am using:
* Rails 4.2.4
* Sidekiq Enterprise 0.7.2
* Redis Server 2.8.21

I am witnessing a strange behavior where jobs do not seem to be enqueued. I know this because the first thing I do in the job is persist a started_at time in a mysql database. When I do not use the uniqueness feature of Sidekiq Enterprise, the jobs enqueue and finish successfully.

Here is my config/initializer/sidekiq.rb

```ruby
redis_config = {
  :namespace => 'app-name',
  :url       => App.configuration['redis_uri'],
}

Sidekiq.configure_server do |config|
  config.redis = redis_config
end

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

# Disable uniqueness in testing, this has the potential to cause much head scratching...
Sidekiq::Enterprise.unique! unless Rails.env.test? || Rails.env.ci?
```

Here is the gist of the worker class:

```ruby
class SomeWorker
  include Sidekiq::Worker

  sidekiq_options unique_for: 10.minutes unless Rails.env.test? || Rails.env.ci?

  def perform(id)
    ...
  end
end
```

Jobs are enqueued as follows:

```ruby
class SomeClass < ActiveRecord::Base
  after_commit :enqueue, on: :create

  protected

  def enqueue
    SomeWorker.perform_async(id)
  end
end

**Comment by mperham** [comment]
Is it possible the same job was scheduled for some point in the future?  Uniqueness is in effect while a job is scheduled to execute.

**Comment by thommahoney** [comment]
There is only one place where jobs get enqueued in the application. Always using `perform_async` with one parameter (the id). Is there some logging that I can turn on to debug further?

**Comment by mperham** [comment]
The only logging is at the INFO level.  You should see "Skipping enqueue..." in the logs.  Do you see that?

**Comment by thommahoney** [comment]
Yes, I have captured this log line:

```2015-09-25_21:31:46.49616 2015-09-25T21:31:46.495Z 45801 TID-ovbb0ek5o INFO: Skipping enqueue for <SomeWorker>, not unique.```

**Comment by thommahoney** [comment]
Maybe relevant: The Redis instance that I'm using is shared by three (3) other installations of sidekiq-pro (v 2.0.8). This is the only application using sidekiq-ent thus far.

**Comment by mperham** [comment]
No matter what, you should be able to enqueue the job every 10 minutes since that's your uniqueness TTL.  Confirm/deny?

If you have some code in your webapp trying to enqueue these jobs, but there's no Sidekiq process dequeuing the jobs on the "other side", then this behavior is expected.  You'll need to drain the queue, flush Redis or wait 10 minutes.  Are you running a Sidekiq process which is executing the jobs successfully?

**Comment by thommahoney** [comment]
```
irb(main):001:0> SomeWorker.perform_async(3064)
Unique hash for job: 201e119366bf320c92e87a6eaddc7a98a9d6b8f8
2015-09-25T21:52:22.616Z 58714 TID-oxolpiuu0 INFO: Skipping enqueue for SomeWorker, not unique.
irb(main):002:0> Sidekiq.redis { |r| r.get '201e119366bf320c92e87a6eaddc7a98a9d6b8f8' }
=> nil
```

**Comment by mperham** [comment]
You're missing the unique prefix:

```ruby
key = "unique:201e119366bf320c92e87a6eaddc7a98a9d6b8f8"
p(Sidekiq.redis { |r| r.multi { r.get key; r.ttl key } })
```

**Comment by thommahoney** [comment]
> You're missing the unique prefix:

I've altered my comment. Sorry.

**Comment by thommahoney** [comment]
Okay here's the proof:

```
irb(main):001:0> GithubEventWorker.perform_async 3073
2015-09-25T22:02:05.884Z 63093 TID-oupn766j0 INFO: [nil, -2]
2015-09-25T22:02:05.913Z 63093 TID-oupn766j0 INFO: Skipping enqueue for GithubEventWorker, not unique.
```

**Comment by mperham** [comment]
Show me the code you added.

**Comment by thommahoney** [comment]
To get the log lines above, I added the following line between `hash = ` and `result = `

```ruby
Sidekiq.logger.info { Sidekiq.redis { |r| r.multi { r.get hash; r.ttl hash } } }
```

**Comment by mperham** [comment]
Again, you're missing the "unique:" prefix on the hash.  See how `conn.set` adds it?

**Comment by thommahoney** [comment]
Yes of course. :disappointed: Trying again.

**Comment by thommahoney** [comment]
I can't seem to reproduce this after hours of being able to reproduce it without a problem. I'm going to close the issue but I will re-open it if I obtain more information. Sorry to have wasted your time.
