### ISSUE TITLE
Unexpected worker performance limiting.

### ISSUE THREAD

**Issue by shipitko** [mperham/sidekiq#2576]
Hello!
This text is copy of [my stackoverflow question](http://stackoverflow.com/questions/32855613/what-limits-performance-of-worker?noredirect=1). I was advised to create an issue here.

I use Sidekiq for job processing. Using Foreman, I set up six processes in my Procfile:

    redirects: bundle exec sidekiq -c 10 -q redirects
    redirects2: bundle exec sidekiq -c 10 -q redirects
    redirects3: bundle exec sidekiq -c 10 -q redirects
    redirects4: bundle exec sidekiq -c 10 -q redirects
    redirects5: bundle exec sidekiq -c 10 -q redirects
    redirects6: bundle exec sidekiq -c 10 -q redirects

These processes performed at about 1600+ jobs (simple job to increment some hashes in Redis) per second with all 10 threads busy most of the time. I scaled my Digital Ocean droplet from 8 to 12-core, and performance fell to ~400 per second. For each process, there are only 3-5 busy threads out of 10.

What I did to try to fix the issue:

 - Make `perform` method empty
 - Use less/more process count
 - Use less/more concurrency
 - Split queue to server-specific queues (there are three express.js clients from another servers puts jobs in queues)
 - Trying with different `hz` values in redis.conf
 - Setting `somaxconn` to 1024 (`tcp-backlog` in redis.conf too)
 - Turning off RDB save and use only AOF
 - Flush all Redis dbs (there are two databases for all that logic: one for sidekiq and another for hashes in my workers)
 - Running sidekiq from terminal without Foreman (to check if it is Foreman issue)

None of above helped me. What could have caused the performance loss?

**Comment by mperham** [comment]
There's way too much at work to determine.  Keep testing variations.
