### ISSUE TITLE
Reducing Sidekiq::Fetcher::TIMEOUT to 0?

### ISSUE THREAD

**Issue by sriedel** [mperham/sidekiq#2579]
We are currently have 3 closely connected services using sidekiq on different databases on the same redis instance. As long as the queues are filled, everything is running smoothly. However once one service no longer has items in non-retry queues, the brpop with a timeout of 1 on the empty queues starts slowing the other services down.

One way to solve this, would be of course to use different redis instances for each services sidekiq. Another fix, with less administrative overhead, would be to set Sidekiq::Fetcher::TIMEOUT to 0 instead of 1. 

Now, I'm guessing the value of 1 was not chosen arbitrarily here, so before I try with a reduced setting, I wanted to ask what the reasoning behind the value here is and what (if any) negative side effects can be expected.

**Comment by mperham** [comment]
1 is the lowest timeout.  0 means wait forever.  Note you can implement and plug in your own Fetcher if you need.  Given that you have a very specialized use case, I'd suggest that's your best route.

**Comment by sriedel** [comment]
Ok, I'll have a look. Thank you for your feedback.
