### ISSUE TITLE
Add a note to docs that provider_job_id isn't available until rails 5

### ISSUE THREAD

**Issue by mbutsko** [mperham/sidekiq#2585]
Can you add a note to the [active-job page](wiki/Active-Job), where you mention provider_job_id, that it won't be available until rails 5? The provider_job_id assignment is on master, but never made it in to the 4.2 branch:

https://github.com/rails/rails/blob/4-2-stable/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb

**Comment by mperham** [comment]
@mbutsko Why don't you add it?
