### ISSUE TITLE
Remove redis-namespace dependency

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2586]
The user will need to add:

gem 'redis-namespace'

to their Gemfile if they want to use namespaces.  Sidekiq should not install the gem by default since it's not a best practice, per [my recent blog post](http://www.mikeperham.com/2015/09/24/storing-data-with-redis/) on the matter.

**Comment by jonhyman** [comment]
:+1: Agree with you that namespaces are a bad way to use Redis.

**Comment by zedtux** [comment]
It looks like it hasn't been done correctly as it is [still required from the Sidekiq code](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L44), but is no more in the dependencies which makes my app crashing.

**Comment by mperham** [comment]
@zedtux It's been done correctly.  You add the gem to your Gemfile, everything else just works.

**Comment by zedtux** [comment]
You're right, but when this isn't done, the app crash (500 error).

**Comment by mperham** [comment]
What's your point?  That's what it's supposed to do.  How else do you know to add the gem?

https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md#whats-new

**Comment by aprescott** [comment]
I think the confusion is that Sidekiq can support namespaces, but if you use them then it errors. It's an error because you're being nudged against using them, but perhaps it looks broken to people who don't know that?

**Comment by mperham** [comment]
Is the error message not clear?  [It tells the user what to do](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L47).

**Comment by mperham** [comment]
Wait, I guess it doesn't tell the user what to do but rather implies it.  Ok.

**Comment by zedtux** [comment]
Well, after having read the code once again, I've understood what was wrong in my code and I now understand the confusion.

I don't care about the namespaces, so removing that gem is fine for me. The issue is that I haven't removed the namespace from my config.
Removing the `namespace: xxxxxx` form my config fixed it.

**Comment by zedtux** [comment]
@mperham you're right there is a message explaining that the gem is missing and to install it in case he'd like to still use namespaces, but it could also suggest to review the configuration in order to remove the namespace parameter in case he don't care about it.

**Comment by mperham** [comment]
I'm happy to get a PR improving this error message.

**Comment by zedtux** [comment]
I did the PR https://github.com/mperham/sidekiq/pull/2802
