### ISSUE TITLE
Getting forbidden error message when I try delete the retries

### ISSUE THREAD

**Issue by pepibumur** [mperham/sidekiq#2587]
Hi!

I've been some issues opened before with this same errors but any solution on them. I'm getting exactly the same message when I try to delete something, after the confirmation I'm redirected to an empty webpage with a `forbidden` message.

What should I do to get it working? What am I doing wrong?

Thanks for your help

**Comment by rikas** [comment]
This is something that has been bugging me and some other users for a while.

Check #2487 and #1289.

Maybe the solution in #2560 will help you (it didn't work for me).

Cheers

**Comment by pepibumur** [comment]
@mperham any solution? why did you close it?

**Comment by mperham** [comment]
There's already two other linked issues with possible solutions.  Please refer to them.

**Comment by pepibumur** [comment]
Tried all of them and no one is working for me nor  for @rikas . All of these issues are closed and there're still people having the problem.

**Comment by mperham** [comment]
You haven't shown us how you are running the Web UI or provided a minimal app which reproduces your problem.

I test the Web UI standalone and with Rails using the `myapp` application in the Sidekiq repo.  It works fine in both cases.

```
cd myapp && bundle exec rails s && open http://localhost:3000/sidekiq
cd myapp && bundle exec rackup simple.ru && open http://localhost:9292/
```

**Comment by TheJefe** [comment]
I was still getting this issue after making all of these suggested changes. The fix for me was to upgrade our sinatra gem from 1.3.6 to 1.4.7.

**Comment by villins** [comment]
@TheJefe thx

**Comment by xofred** [comment]
@TheJefe thx man, problem solved!
