### ISSUE TITLE
Allow WebUI authentication using a pre-defined block

### ISSUE THREAD

**Issue by abhchand** [mperham/sidekiq#2589]
Sidekiq WebUI for monitoring provides [several options for Auth](https://github.com/mperham/sidekiq/wiki/Monitoring), most of which rely on using the `constraint:` feature on Rails Routes. 

The limitation of the `constrain:` feature is that it's all or nothing - if it returns `true` then the route is matched and if it returns `false` the process moves on to try and match the next available route.

This doesn't let user's do slightly more advanced things with authentication, like redirecting to a separate page if a non-admin tries to access the protected resource. 

It would be great to able to define a block ahead of time that can be used for authentication instead of the `constraint` feature. 

E.g.

    # config/initializers/sidekiq.rb

    Sidekiq::Web.config do |config|
      config.authenticate_with do
        current_user = User.find(session[:user_id])

        unless current_user.admin?
          redirect_to( root_path, alert: "lol, you can't access that")
        end
      end
    

This defines a block ahead of time that will be used during authentication. 

Thoughts on taking pull requests for a feature such as this? Or are there any ways of implementing this that I might have missed?

Thanks for everyone's input!

**Comment by mperham** [comment]
All of this infrastructure is provided by Sinatra and Rack.  It has nothing to do with Sidekiq.

**Comment by mperham** [comment]
What you want is as simple as:

```ruby
Sidekiq::Web.use MyAuthenticationMiddleware
```
