### ISSUE TITLE
warning: method redefined; discarding old sidekiq_options_hash

### ISSUE THREAD

**Issue by mhenrixon** [mperham/sidekiq#2594]
In unique jobs I just got rid of the development dependency on active support which in turn made sidekiq completely crazy and I now get spammed with the following messages

```
/Users/mhenrixon/.gem/ruby/2.2.3/gems/sidekiq-3.5.0/lib/sidekiq/core_ext.rb:18: warning: method redefined; discarding old sidekiq_options_hash
/Users/mhenrixon/.gem/ruby/2.2.3/gems/sidekiq-3.5.0/lib/sidekiq/core_ext.rb:13: warning: previous definition of sidekiq_options_hash was here
/Users/mhenrixon/.gem/ruby/2.2.3/gems/sidekiq-3.5.0/lib/sidekiq/core_ext.rb:18: warning: method redefined; discarding old sidekiq_options_hash
```

It seems the version you have in sidekiq isn't taking into consideration if the method has been redefined and I believe I might be doing something wrong but not sure what to do about it. I am reluctant to turn off warnings.

Suggestions?

**Comment by mperham** [comment]
Check if you are including Sidekiq::Worker in a class twice.

**Comment by mhenrixon** [comment]
Doesn't seem to be it. https://github.com/mhenrixon/sidekiq-unique-jobs/commit/4cdfc1e52cbcaae0f6d99dffdacc5a9b358ec6cf I'll keep looking tomorrow, it has been a long day of NodeJS so mind feels broken at the moment.
