### ISSUE TITLE
Display pending private queues

### ISSUE THREAD

**Issue by asanghi** [mperham/sidekiq#2595]
@mperham Would you consider giving a view into jobs pending in private queues on the WebUI? We recently ran into a problem where a task from over 3 months ago re-ran when it shouldn't have (we've fixed it's idempotency since). We're on AWS and 3 months ago when that process was killed, it remained in the private queue for that hostname (and queue name and index) in redis. The server was shutdown then and decommissioned. A few days back, Opsworks created another server with the same hostname and that task "reliably" got pulled into this server and started executing.

I had misunderstood earlier that private queue tasks would be executed on the next available process but having peeked into the code, I learnt that tasks are ONLY re-run if the machine's hostname remains the same. (_So reliable execution of a job can be somewhat shrouded if while running a job, the server is shutdown and a server with the same hostname is not restarted._)

If we had a view into jobs in internal queues, we would be able to make informed decisions. What's your opinion on this? Happy to invest on a pull request, if I know your views.

/cc @justanshulsharma @gaurish

**Comment by mperham** [comment]
It's something that has come up several times.  Since it would be a Pro feature, I'll implement it myself but I don't have an ETA for it.

**Comment by ryansch** [comment]
Excellent.  I've done some hand wringing about this myself as we're planning to dockerize sidekiq soon in our environment.

**Comment by mperham** [comment]
Covered in #2595, no ETA though.
