### ISSUE TITLE
Job not processing on multiple CPU core.

### ISSUE THREAD

**Issue by brahamshakti** [mperham/sidekiq#2596]
@mperham Is it possible that sidekiq on two cpu core processor may not process job, I am asking it because i am getting this error on one of my cpu processor `Processor: ip-172-30-43-16:19323, NameError: uninitialized constant AppSidekiqJob.` But I didn't find any error in failures tab for my other processor which i think is my main processor. ie.   `Processor: ip-172-31-62-180:19323` because I get this IP on ssh to my server. Is it related to multiple cpu core or ruby mri. My sidekiq.yml file contain

    --
    :verbose: false
    :concurrency: 25
    # Set timeout to 8 on Heroku, longer if you manage your own systems.
    :timeout: 30
    :queues:
      - [high, 3]
      - [default, 2]
      - [low, 1]

    production:
      :concurrency: 5

Is there any thing wrong with my sidekiq.yml or is it something related to which I don't know. My jobs file are inside `app/jobs` folder.

**Comment by mperham** [comment]
I don't understand your question.

**Comment by brahamshakti** [comment]
Actually my aws instance is [t2.medium](https://aws.amazon.com/ec2/instance-types/) which uses two cpu. My question was simply to understand that does sidekiq behavior changes on server having two or more cpu because I am getting uninitialized constant error for:

    NameError: uninitialized constant AppSidekiqJob
    Processor: ip-172-30-43-16:19323

while I did not see this error for another cpu `Processor: ip-172-31-62-180:19323`. When I click on `busy` tab in  sidekiq web interface it shows these processes.

     Name	                            Started	           Threads	Busy	 
     ip-172-30-43-16:19323 App          a day ago	           5     0          Quiet  Stop
     Queues: high, default, low			

     ip-17231-62-180:19323 App          3 day ago	           5     0          Quiet  Stop
     Queues: high, default, low

I don't know why sidekiq giving me uninitialized constant error for for only first process i.e `ip-172-30-43-16:19323`. My job is still executing but with failures.
