### ISSUE TITLE
Loading assets in production?

### ISSUE THREAD

**Issue by mhenrixon** [mperham/sidekiq#260]
No idea if anyone cares about this but I can't get the assets to load in production wich makes the admin page pretty fugly. Any suggestions to how I might make it compile or use the assets needed?

**Comment by fabiancarlos** [comment]
Bah... i loosed my patient, and just put the assets on the public folder: 

+ public/sidekiq/images/image.png
+ public/sidekiq/javascripts/application.js
+ public/sidekiq/javascripts/dashboard.js
+ public/sidekiq/javascripts/graph.js
+ public/sidekiq/stylesheets/application-dark.css
+ public/sidekiq/stylesheets/application.css
+ public/sidekiq/stylesheets/bootstrap.css

On my case, probabily is something configuration about Puma+Nginx, i was using Phusion Passenger, so, when decided to migrate to Puma again, the assets for sidekiq was not processing.

**Comment by mperham** [comment]
I’d guess you’re not forwarding assets requests from nginx to the app.

**Comment by PiotrBracha** [comment]
I have nginx + passenger + rails. Nginx vhost:

```
passenger_set_header X-Accel-Mapping /home/passenger/.rvm/gems/ruby-3.3.6@updateserver/gems/sidekiq-7.3.9/web/assets/=/sidekiq_assets/;
passenger_pass_header X-Accel-Redirect;

location ^~ /sidekiq_assets/ {
    alias /home/passenger/.rvm/gems/ruby-3.3.6@updateserver/gems/sidekiq-7.3.9/web/assets/;
    internal;
}
```
It works fine (of course in Rails production I have `config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'`). I tried to set up symlink and use it inside vhost config. Simple symlink script:
```
#!/bin/bash

APP_ROOT="/home/passenger/updateserver"
LINK="/home/passenger/updateserver/sidekiq_assets"

cd "$APP_ROOT"
GEM_ASSETS="$(bundle show sidekiq)/web/assets"
ln -sfn "$GEM_ASSETS" "$LINK"
```

and above mentioned form would became this:
```
passenger_set_header X-Accel-Mapping /home/passenger/updateserver/sidekiq_assets/=/sidekiq_assets/;
passenger_pass_header X-Accel-Redirect;

location ^~ /sidekiq_assets/ {
    alias /home/passenger/updateserver/sidekiq_assets/;
    internal;
}
```
but unfortunatelly nginx gives 403 on assets. Symlinks are not accepted in the X-Accel-Mapping path?
