### ISSUE TITLE
Redesign reliable fetch

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2600]
The new design for fetch in Sidekiq 4.0 means that Pro's reliable fetch needs to change in tandem.  Re-implement to maintain compatibility.  Notes:

1. Queue (un)pausing should become real-time.
2. Support systems where hostname is ephemeral?
3. Increase efficiency, possible to use BRPOPLPUSH instead of polling?

**Comment by pacoguzman** [comment]
+1 to Support systems where hostname is ephemeral

**Comment by GermanDZ** [comment]
yes please!

**Comment by sanjayprabhu** [comment]
What's the new fetch design? Is there somewhere I can read more about it?

**Comment by mperham** [comment]
Reliable fetch has been reimplemented, no change in semantics.

If you have two processes (old and new) working on the same queue at the same time, you can see job dupes. Your deploy must take this into account.

**Comment by aprescott** [comment]
@mperham that's only while upgrading across the version bump to 4.0, right?

**Comment by mperham** [comment]
@aprescott Reliable fetch in Pro 3.0 continues to use a single thread to fetch, it can't be parallelized like fetch in Sidekiq 4.0.  Nothing will change in Pro 2.x.

Sidekiq 3.x -> Pro 2.x
Sidekiq 4.x -> Pro 3.x
