### ISSUE TITLE
Send Callback after job Done

### ISSUE THREAD

**Issue by acegilz** [mperham/sidekiq#2601]
I am using sidekiq with sidekiq-status to check when the work is done to keep performing the action. The method I use is not much efficient but it does it.

Controller:
```
myjob = JobCreator.perform_async(my_param)

  sleep(1)

  10.times do
    status = Sidekiq::Status::get myjob, :job_status
    if ["OK","FAIL","NOMONEY"].include?(status)
      result << status
      break
    end
    sleep(1)
  end
```
How can I make this on a more direct, fast and efficient way?

**Comment by mperham** [comment]
Sure, replace all that code with:

```ruby
JobCreator.new.perform(my_param)
```

**Comment by acegilz** [comment]
Nice.
with new.perform can I return results (from worker) and then they'll be listed afterwards on controller?

**Comment by mperham** [comment]
It's a method call, you can do anything you want.

**Comment by acegilz** [comment]
Nice. I just have one more question about the new.perform vs perform_async I have been using. 

I have checked that even if I use another queue and that queue is disabled, it still performs.

Question is, does it follow arguments and restrictions setted up there on the worker, or does it go somewhat via a more direct way? 

I'm specifically concerned about if SidekiqUniqueJobs and its rules that are setted-up there on the worker  will still be valid or if that only works on perform_async.

**Comment by acegilz** [comment]
I mean this:

```
class MyJob
  include Sidekiq::Worker
  include Sidekiq::Status::Worker

  SidekiqUniqueJobs.config.unique_args_enabled = true


  sidekiq_options :queue => "critical", :retry => false, unique: true, unique_args: -> (args) { [ args.first ] }


  def perform(my_params)
   ///THECODE
  end
end

```

**Comment by mperham** [comment]
The way to do callbacks is [Sidekiq Pro's Batches feature](https://github.com/mperham/sidekiq/wiki/Batches).
