### ISSUE TITLE
Redis::CannotConnectError: Error when creating batches after upgrading to 3.5.1 (2.1.0 pro) from 3.4.2 (2.0.8 pro)

### ISSUE THREAD

**Issue by webandtech** [mperham/sidekiq#2603]
Every job that creates a batch fails with:
`Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)`
 after upgrading to sidekiq 3.5.1 / 2.1.0 pro from 3.4.2 / 2.0.8 pro. Did something change in how redis is configured? It appears to be attempting to connect to the wrong Redis url.

My redis url is specified in configuration like this:
```
  Sidekiq.configure_client do |config|
    config.redis = { url: ENV['SIDEKIQ_REDIS_URL'], size: Integer(ENV['MAX_THREADS'] || 5) + 2, network_timeout: 5 }
  end
Sidekiq.configure_server do |config|
  config.reliable_fetch!
    config.redis = { url: ENV['SIDEKIQ_REDIS_URL'], size: Integer(ENV['SIDEKIQ_CONCURRENCY'] || 20) + 2, network_timeout: 5 }
end
```

**Comment by mperham** [comment]
I have one other customer who's report the same problem. The workaround is to downgrade to 2.0.8 for now.

**Comment by mperham** [comment]
2.1.1 has been released with a possible fix.

**Comment by webandtech** [comment]
Thanks! We'll try it again next week.
