### ISSUE TITLE
Sidekiq Always in queue status and restart goes interrupted status

### ISSUE THREAD

**Issue by joshuawatson** [mperham/sidekiq#2608]
I used sidekiq(3.4.2) it is worked few days before, but now it's not going to complete status, monitorUI show always in queue status, if i restarted is going to interrupted status. i didn't see any error so how could i resolved this.

Thanks,
Joshva

**Comment by seuros** [comment]
Update to latest version and submit a backtrace if the error persist.

**Comment by joshuawatson** [comment]
I have updated latest version but still no changes. it is in queue first then go for interrupted status.
it not showing any error.
