### ISSUE TITLE
Sidekiq Workers with Postgres and ActiveRecord - RecordNotFound

### ISSUE THREAD

**Issue by fnoelscher** [mperham/sidekiq#2611]
Hi!

My worker will get a record id as an argument and the first thing it does is look up this id using "find". But on many workers, this will fail instantly, with RecordNotFound error being raised. You would expect this to be some kind of the known "sidekiq starts too fast" thing, bug it turns out that even after 5 retries, the job still fails. I tried sleeping 10 seconds before doing the lookup, same thing. Even with sleeping and concurrency set to 1, jobs still fail. Also, there is no pattern in failing jobs - they are all very simliar.
I'm using postgres (with pg gem) as a database and the sidekiq worker runs in its own docker container. I verified that there are enough db connections in the connection pool.
On my development laptop everything seems to work fine but not on the server, making things even worse.

What can I do? Is it postgres messing up?
Any help is greatly appreciated.

**Comment by seuros** [comment]
I think the records don't exist for real.

**Comment by violentinternet** [comment]
That was already checked (if I may intervene). The record exists. We make the same find in the controller before starting async_perform which is successful. Afterwards the find in the Worker fails with record not found.

**Comment by abrahamks** [comment]
Hi @violentinternet , I also encounter this problem when I was running Rails production on my local machine.

The sidekiq worker pointed to wrong database `my_app_development` instead of `my_app_production`. I discovered this problem by trying to log all object on my database on the worker class, like:
```
class YourWorkerClass
	include Sidekiq::Worker
	def perform(campaign_id)
    Logger.info (YourModel.all)
  end
end
```

Is it the same problem like yours?
