### ISSUE TITLE
Workers process 1 jobs each, then hang

### ISSUE THREAD

**Issue by mskog** [mperham/sidekiq#2613]
After upgrading to sidekiq 3.5.1 from 3.2.5 and the workers seem to pick up one job each, process that and then hang. Jobs pile up in the queue as normal but none are processed. After restarting Sidekiq another 25 jobs are processed and then the workers hang again.

What makes this worse is that we cannot seem to reproduce it on our local machines or in our staging environments. The staging machines are identical to the production environment, except that the Redis server is running on another machine.

Killing the process with TTIN puts this in the log for each worker:

```
2015-10-21T14:38:20.076Z 21316 TID-ow5wz8zo0 WARN: Thread TID-ow5x6ugww
2015-10-21T14:38:20.076Z 21316 TID-ow5wz8zo0 WARN: /var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:63:in `sleep'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:63:in `wait'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:63:in `block in check'
/var/www/app/shared/bundle/ruby/2.2.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/mailbox.rb:58:in `check'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor.rb:155:in `block in run'
/var/www/app/shared/bundle/ruby/2.2.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor.rb:152:in `run'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor.rb:131:in `block in start'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/group/spawner.rb:50:in `call'
/var/www/app/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.2/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

Any ideas?

**Comment by antifun** [comment]
Seeing something similar here. In our case, many jobs (those that have short durations, it seems) finish fine. Our longest running job, which also calls out to a few external APIs, will sit and spin for hours and hours. (Currently we have one that's been "running" for 18 hours.) The same spot in the code is implicated in our traces.

**Comment by karlingen** [comment]
+1

**Comment by mperham** [comment]
Can you bisect between Sidekiq versions 3.2.5 and 3.5.1 and find the version that broke for you?

**Comment by karlingen** [comment]
@antifun Are you running redis on the same server as sidekiq?

**Comment by mperham** [comment]
Are you running any 3rd party sidekiq extensions?

**Comment by DouweM** [comment]
I'm seeing the same problem with a GitLab instance with Sidekiq 3.3.0. Redis is on the same server as Sidekiq, and GitLab uses Sidetiq.

**Comment by mperham** [comment]
No info -> close.

**Comment by karlingen** [comment]
@45cali three years ago. Cant remember 🤭
