### ISSUE TITLE
backtrace working in development, not in staging

### ISSUE THREAD

**Issue by zedtux** [mperham/sidekiq#2614]
Given the following `config/sidekiq.yml` file in my Rails application:

```
---
:pidfile: tmp/pids/sidekiq.pid
:backtrace: true
:queues:
  - cron
  - default
staging:
  :concurrency: 10
production:
  :concurrency: 20
```

In development, when I open the retry page of a failed job, I got the backtrace.
Then I did the deployment to staging but here I do not have the backtrace.

I'm deploying using `capistrano` and `capistrano-sidekiq` which executes the following line:

```
~/.rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /home/yellow/yellow/shared/tmp/pids/sidekiq.pid --environment staging --logfile /home/yellow/yellow/shared/log/sidekiq.log --config /home/yellow/yellow/current/config/sidekiq.yml --daemon
```

So the configuration file is well passed.

Can you please guide me to a solution or give me some checks I could do ?

**Comment by mperham** [comment]
Backtrace does not go in sidekiq.yml. It's a worker option.

**Comment by zedtux** [comment]
Thank you for your fast reply. Was looking nice to me to have it in the `sidekiq.yml` file.
