### ISSUE TITLE
Guidance on tying into logging

### ISSUE THREAD

**Issue by evanphx** [mperham/sidekiq#2615]
I'm working on some logging integrations with Sidekiq (to provide structured logging output) and I'm curious if y'all have any guidance on doing so. Should it be a separate server middleware? Do people commonly change their server middlewares?

**Comment by mperham** [comment]
The existing logger is definitely for unstructured output.  Adding a server middleware is appropriate.  You can remove the existing logging middleware or use both.

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove Sidekiq::Middleware::Server::Logging # or
    chain.insert_before Sidekiq::Middleware::Server::Logging, Evanphx::Slogger
  end
end
```

You can also add a [global error handler](https://github.com/mperham/sidekiq/wiki/Error-Handling#error-handlers) to get log output upon job errors (this will be redundant if you log upon rescue in the middleware) or more fatal process errors.

**Comment by mperham** [comment]
You can put that block in your main .rb file so when bundler activates your gem within the Sidekiq process, the middeware will automatically activate.

**Comment by evanphx** [comment]
Is there a proper way to detect Sidekiq? Railtie gems typically still use `defined?(Rails)` so perhaps `defined?(Sidekiq)`?

**Comment by mperham** [comment]
Yep, `defined?(Sidekiq)` or ask the user to `require 'evanphx/slogger/sidekiq` in their Sidekiq initializer to enable the feature.

**Comment by evanphx** [comment]
This is what I opt'd to do. Works fairly well and integrates with Rails to use it's configuration to enable support for each environment.

https://github.com/vektra/currentsh/commit/aefd5cf057ed469253994c7bd2e0c61567589abe
