### ISSUE TITLE
Strange behavior with Sidekiq::Limiter wait_timeout set to 0

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2616]
if its `0<wait_timeout<1`, it gives `ArgumentError: wait_for must be >= 1`. If its 0, it does nothing, no exception raised. Idea being I don't want a worker to wait around at all if the concurrent maximum has been reached but either way, weirdo behavior.

**Comment by mperham** [comment]
Can you give me the exact line of code you are using to build the limiter?

**Comment by kreynolds** [comment]
I actually misreported .. its fine with 0 and fine with >=1, but not in between. At any rate, this is the code:

```
Sidekiq::Limiter.concurrent(project.user_id, 1, wait_timeout: 0, lock_timeout: 60).within_limit do
  ProjectService.send(type, project, request_id: project_id)
end
```

**Comment by mperham** [comment]
That's correct.  The wait is blocking and Redis can only block on an integer number of seconds, so 0<wait_timeout<1 is impossible to implement.

**Comment by kreynolds** [comment]
Alright, that makes sense, I guess just change the error message to say 0 or >=1.

**Comment by mperham** [comment]
Changed to "wait_timeout must be an integer value", hope that's better.

**Comment by kreynolds** [comment]
perfect
