### ISSUE TITLE
Issue w/ AWS Opsworks & Rails & Redis Pool Size

### ISSUE THREAD

**Issue by markalanevans** [mperham/sidekiq#2621]
@mperham ,

We spoke a few weeks ago on one of your free support sessions. I had an issue w/ not having available database connections in the pool. Well we solved it.

The problem ended up being that Pool Size in the rails app database.yml was not being used. :(

If you happen to have questions from folks, that use Amazon OpsWorks, The Rails Apps they offer utilize Chef recipes.

The settings that drive the DB connection and configuration are defined in the OpsWorks infrastructure, 
NOT from the   /app/config/database.yml 

This is where the recipe reads / writes out the config file that will end up on the EC2 instances:

https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/rails/templates/default/database.yml.erb#L11

So whoever is dealing with this, needs to set custom JSON inside of OPSWorks.
ex:

```json
{
    "opsworks_nodejs": {
        "version": "0.10.33"
    },
    "deploy" : {
    "intentadashboard" : {
      "database" : {
        "pool" : "25"
      }
    }
  }
}
```
![Screen Shot](https://www.evernote.com/l/AJGDAjSTla9MAabqtgPf6kwfR3pFvUOeydQB/image.png)

Hopefully it helps someone.

Cheers & Thanks again,

-Mark

**Comment by mperham** [comment]
Thanks for the followup Mark.  This is good stuff to know.
