### ISSUE TITLE
Queue stops working after bunch of failures

### ISSUE THREAD

**Issue by ManuelArno** [mperham/sidekiq#2622]
Hey!

So when something breaks an lots of jobs fail, the queue just won't stop being idle.

It's most probably just a n00b issue I'm having, since it says "Sidekiq idle" on the top left.

Can somebody with some sidekiq skill chime in?

KIND REGARDS
Manuel

**Comment by bdewater** [comment]
Have you read https://github.com/mperham/sidekiq/wiki/Error-Handling?

**Comment by mperham** [comment]
@ManuelArno Please read: https://github.com/mperham/sidekiq/blob/master/Contributing.md#issues

**Comment by ManuelArno** [comment]
Ok, I will get back to you guys. Maybe it's a bug with capistrano-sidekiq,
I'm not sure yet. If that's not the issue I will file an issue in the
format described in the Contributing readme.

2015-10-25 15:43 GMT+01:00 Mike Perham <notifications@github.com>:

> @ManuelArno <https://github.com/ManuelArno> Please read:
> https://github.com/mperham/sidekiq/blob/master/Contributing.md#issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2622#issuecomment-150930972>.
>



-- 
Manuel Arno Korfmann
Luetzowstrasse 8
24105 Kiel

manu @ korfmann . info
+49 40 210913788

www.manuel-korfmann.de
