### ISSUE TITLE
Why Sidekiq keep all connection to database after job finished?

### ISSUE THREAD

**Issue by Yoshyn** [mperham/sidekiq#2624]
Hi,

I notice with pghero on my rails application that sidekiq does not release connection to my postgres database. 

It's maybe normal but i don't understand this behavior.

Let me explain with step :

 1. **(User action)** Launch a sidekiq process for the 'default' queue with a concurency set to 15.
 2. **(Sidekiq)** Establish one connection to the database.
 3. **(User action)** Enqueue 100 job in the default queue.
 4. **(Sidekiq)** Process the jobs 15 by 15. Open 15 new connection to the database (So now 16 connection).
 4. **(Sidekiq)** Finish to process all the job. There's no more job enqueue but there's still 16 connections open related to sidekiq in the database.

Why does sidekiq need to keep connection to the database after all the jobs are processed?

**Comment by mperham** [comment]
Sidekiq does not access your database or manage your database connections at all.  This is an issue between Rails and your application code.

**Comment by HenleyChiu** [comment]
@mperham Is this statement above by you still true today? I recalled there was a line in the Sidekiq code that closes ActiveRecord connections after the worker is done processing.

**Comment by mikegee** [comment]
@HenleyChiu Sidekiq calls `ActiveRecord::Base.clear_active_connections!`, which returns connections to the pool. ActiveRecord probably won't close the connection at that point. 

see: https://github.com/mperham/sidekiq/blob/c4a854cac8acf360b89d71d66a6b295b8eaef1ad/lib/sidekiq/middleware/server/active_record.rb#L8
and: http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionHandler.html#method-i-clear_active_connections-21

**Comment by mperham** [comment]
There is one place where connections can leak in Sidekiq 4.x: the `sidekiq_retries_exhausted` hook.  If you use a DB connection in it, use `AR::Base.with_connection` or it can leak.  This issue has been fixed in Sidekiq 5.x + Rails 5.x with the redesign of the retry/logging subsystem.

Note that Sidekiq 5.x + Rails 4.x can still leak.

**Comment by sunil-lulla** [comment]
hi @mperham 
any resolution to the leak for Rails 4.x?
