### ISSUE TITLE
ReliableFetch assumes old process will die before new process starts up

### ISSUE THREAD

**Issue by sanjayprabhu** [mperham/sidekiq#2625]
This is somewhat of a followup to #2531. I finally tracked down the other reason why we're losing jobs. 

Currently, ReliableFetch assumes the old process will die before the new process starts up. We use [ECS](https://aws.amazon.com/ecs/) which does not guarantee this. This is causing us to "miss" scheduled messages on restart or code deployments. Here's a simplified view of what's happening in cases where the old worker stays up longer:

1. v1 of the worker pulls m1 into it's private queue and works on it
2. v2 of the worker starts up, reads all the messages (m1) in the private queue and starts working on them
3. v1 of the worker completes m1, pulls m2 into the private queue and is terminated before completing it

At this point, m2 is "lost" until the next restart which may not happen for hours or days. This is particularly bad for time sensitive jobs. 

I'm not sure there's an easy fix for this, would be nice if the [reliable fetch redesign](https://github.com/mperham/sidekiq/issues/2600) took this into account.

(Sidekiq 3.5.0, sidekiq-pro 2.0.8)

**Comment by mperham** [comment]
Yes, this is a requirement for reliable fetch.  You must stop the old process before starting the new process.  If you can't ensure this, you can send the USR1 signal well in advance to ensure all jobs are complete or stagger your index values so that the new process and the old process use different indexes and therefore different private queues, e.g. if you have 2 processes, you can flip indexes on each deploy:

start 0 and 1
start 2 and 3, stop 0 and 1
start 0 and 1, stop 2 and 3
etc

**Comment by sanjayprabhu** [comment]
Makes sense. It's a reasonable design decision. But please make this requirement explicit in the [reliability wiki](https://github.com/mperham/sidekiq/wiki/Reliability).

Staggering indexes alone is not sufficient though. You could still have jobs left over in the 2 and 3 private queues when those processes die that will not be picked up until the next restart. I'll look into sending USR1.

**Comment by mperham** [comment]
Added a note to the (caveats](https://github.com/mperham/sidekiq/wiki/Reliability#caveats)

**Comment by sanjayprabhu** [comment]
> You must ensure that the old process using reliable fetch is shut down before starting up a new process to replace it during deploy. If old and new processes are running at the same time, it's possible for jobs to be processed twice.

It's not just the fact that jobs will be processed twice. Our code can handle that. The bigger issue is that jobs that were in processes when the old processes is killed will not be processed again until the next deploy (see m2 in the description).

**Comment by mperham** [comment]
This is because your timeout `-t` is too long.  Are you using sidekiqctl to stop the process?

**Comment by sanjayprabhu** [comment]
/facepalm

I didn't realize sidekiq would push jobs back to redis on SIGTERM. It was a bug on our side. Signals weren't being forwarded to sidekiq because it was launched from a bash script directly without exec.

Thanks for your help @mperham!
