### ISSUE TITLE
Perform worker in time interval

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2626]
Hello!
Sometimes I need to perform my worker in time interval. For example, I want to run all jobs at night (from 2 am to 6 am). Quick search has not given an answer or any solution for this problem. Therefore I think it'll be great to realize similar feature (in separate plugin for pro/enterprise version).

What do you think?

**Comment by zzet** [comment]
:+1:

**Comment by seuros** [comment]
In pro/entreprise, you can pause the queue.

**Comment by davydovanton** [comment]
@seuros yes. But I want automatic tool for this :smiley:

**Comment by davydovanton** [comment]
So, sidekiq PRO have a [batches](https://github.com/mperham/sidekiq/wiki/Batches#overview) but as I can see batches doesn't support before callback.

**Comment by mperham** [comment]
I think pausing queues is the right solution. Pause at 6am, unpause at 2am.

**Comment by seuros** [comment]
You can do that with a cron job.

**Comment by zzet** [comment]
@davydovanton I wrote a small gem (https://github.com/zzet/sidekiq-tip) that solves this problem.

**Comment by mperham** [comment]
@zzet Looks pretty slick except this line is wrong: https://github.com/zzet/sidekiq-tip/blob/master/lib/sidekiq/tip/server/middleware.rb#L17
