### ISSUE TITLE
Unnecessary rescheduling of job if new timestamp is same as previous

### ISSUE THREAD

**Issue by yogeshjain999** [mperham/sidekiq#2627]
In `lib/sidekiq/api.rb`,  `SortedEntry#reschedule` method unnecessarily delete and schedules a job if job score and given timestamp is same. Should it ignore rescheduling of job in such case ?

<hr/>

```ruby
def reschedule(at)
  delete
  @parent.schedule(at, item)
end
```

If you confirm this, I can send a PR for it.

**Comment by mperham** [comment]
I'd prefer to keep it as is.  Seems like a minor edge case to add a conditional and complexity to the code.
