### ISSUE TITLE
Retry options blocked by footer in UI

### ISSUE THREAD

**Issue by jcavalieri** [mperham/sidekiq#2628]
Hi,

The retry options, like kill and delete are being blocked by the banner at the bottom of the page for sidekiq's web interface.

<img width="147" alt="screen shot 2015-10-28 at 10 32 14 am" src="https://cloud.githubusercontent.com/assets/2171614/10793566/6d0eaa48-7d5f-11e5-8753-fa951503e7d3.png">

That's a screen shot from the bottom of the page. As you can see the buttons are hidden.

I'm using latest chrome.

-John

**Comment by mperham** [comment]
We've fixed and re-fixed this issue a dozen times now.  A change fixes one page but breaks another.  Use a shorter namespace?

**Comment by jcavalieri** [comment]
I see what you are saying. It looks like our really long redis url is the culprit.

I wonder if this could be solved with overflow. E.g.

.navbar-text {
    white-space: nowrap;
    width: 250px;
    overflow: hidden;
    text-overflow: ellipsis;
}
And if there was a title attribute then the user could hover over to get the full string.

**Comment by mperham** [comment]
Actually overflow hidden and a title attribute sound like a decent compromise.  I don't recall what we did in the past though; maybe we tried that and there was some issue.

**Comment by mperham** [comment]
Using DNS to alias the hostname to something shorter is also a workaround.

**Comment by jcavalieri** [comment]
I'm working on a PR.

I realized to, since we have enterprise we also have the longer version string:

"Sidekiq v3.5.0 / Pro v2.0.8 / Enterprise v0.7.3"

**Comment by mperham** [comment]
@jcavalieri `bundle update sidekiq-ent` to get a shorter version string.

**Comment by jcavalieri** [comment]
thanks, I'll give it a try

**Comment by jcavalieri** [comment]
Hmmm, nothing updated.  And I don't have it locked down to a version in the Gemfile.

```sidekiq-ent (0.7.3)```

This is the version I have.

**Comment by mperham** [comment]
You have something locked down.  0.7.7 is the latest.

**Comment by jcavalieri** [comment]
Oh got it. I had a deployment freeze set with bundler. Thanks @mperham!

**Comment by jcavalieri** [comment]
Hi @mperham, I think this will be more responsive:
https://github.com/mperham/sidekiq/pull/2645
