### ISSUE TITLE
Track private queues and display contents in Web UI

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2629]
Several customers have asked for the ability to introspect reliable fetch's private queues.  Add this feature to Pro 3.0.

0. Add hook in Sidekiq's queue page which Pro can use.
1. Add private queue names to a sorted set.
2. Add API to enumerate private queues.
3. Add panel to Web UI showing content of any private queues.

Issue: need to ensure queue names are GC'd from the set.

**Comment by ivanovv** [comment]
+1 for this one, I used `redis-cli` to inspect those, UI would be nice.

**Comment by mperham** [comment]
I'm not going to implement this.  If you are in a more dynamic environment like autoscaling where jobs could be left in private queues, I'd recommend using the new timed_fetch algorithm for the scaled processes.

https://github.com/mperham/sidekiq/wiki/Reliability#using-timed_fetch
