### ISSUE TITLE
[TASKS][DEV-ACC] Upgrade Ruby to 2.2.2 Batch2

### ISSUE THREAD

**Issue by pollosp** [mperham/sidekiq#2632]
##### Deployment tasks

- Unicorn processes must be restarted using stop & start

### Motivation 
Right now we are using some applications with old Ruby versions. We have to update it at least to ruby 2.2.2.
We are going to do it in batches in order to reduce the impact if something fails. 

### Tasks 
  We have to follow this steps in every app.
- Upgrade ruby gems which uses C like unicorn, kgio, eventmachine
- Run bundle install/update
- Upgrade ruby-version file
- Run tests

### First batch
- [ ] API : 2.1.6 (unicorn)
- [ ] salesforce : 2.1.6
- [ ] Tracker : 2.1.6 (unicorn)
- [ ] matching: 2.1.6
- [ ] gateway : 2.1.6
- [ ] filer: 2.1.6
- [ ] Common_app (unicorn)
- [ ] Callback

### Acceptance
Tests have to be in green

**Comment by mperham** [comment]
Wrong repo.
