### ISSUE TITLE
Timeout::Error in sidekiq 4.0.0 pre

### ISSUE THREAD

**Issue by muhammet** [mperham/sidekiq#2634]
@mperham 

We were checking the excited upcoming realease. 

We are getting the following error in sidekiq 4.0.0 pre, any ideas?

Timeout::Errorgems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:85

```
bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:115:in `❤': uninitialized constant Sidekiq::Launcher::PROCESSED (NameError)
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:70:in `heartbeat'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:137:in `start_heartbeat'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/util.rb:16:in `watchdog'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/util.rb:24:in `block in safe_thread'

Caused: gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:85:in `block in pop': Waited 1 sec (Timeout::Error)
	from org/jruby/RubyKernel.java:1292:in `loop'
	from gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
	from org/jruby/ext/thread/Mutex.java:151:in `synchronize'
	from gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
	from gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
	from gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
	from org/jruby/RubyThread.java:659:in `handle_interrupt'
	from gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq.rb:81:in `redis'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:81:in `❤'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:70:in `heartbeat'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/launcher.rb:137:in `start_heartbeat'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/util.rb:16:in `watchdog'
	from bundler/gems/sidekiq-18bc1fc5529e/lib/sidekiq/util.rb:24:in `block in safe_thread'
````

@sahin

**Comment by mperham** [comment]
What is the size of your server connection pool?  Looks like it is too small.

**Comment by muhammet** [comment]
we didnt defined , I see that default is 25

**Comment by muhammet** [comment]
if it is the case, is there any way to have better error message?

**Comment by muhammet** [comment]
we will try with 

redis_pool_size = YAML.load_file('config/sidekiq.yml')['production'][:concurrency].to_i + 1

**Comment by muhammet** [comment]
I think, it might be a great idea to have the default as connection_poll + 2, instead of 25

**Comment by muhammet** [comment]
Im checking. Thanks.

**Comment by mperham** [comment]
Default is concurrency + 2. Maybe it needs to be 3 or 4.

**Comment by sahin** [comment]
@mperham wierd, we are still getting the error, I think there is a problem in the redis server, 

what is the command to get the current redis connection setting?

Sidekiq.redis.pool?

**Comment by mperham** [comment]
The connection pool is at Sidekiq.redis_pool.  As you can see, I just bumped up the default size in case that was the issue.

**Comment by mperham** [comment]
I've found a bug in Pro 3.0.0.pre1 which causes excessive connection usage.  I will have pre2 out on Monday to fix.

**Comment by mhuggins** [comment]
Looks like pre2 is on rubygems now

**Comment by mperham** [comment]
Correct, 4.0.0.pre2 and Pro 3.0.0.pre2 are now available.
