### ISSUE TITLE
sidekiqctl now failing due to use of Process.kill

### ISSUE THREAD

**Issue by Geesu** [mperham/sidekiq#2636]
The use of `kill` to stop processes was recently switched to `Process.kill`.  As a result, a new exception will be thrown if the process isn't actually found.

If you are using capistrano to start/stop workers this causes quite a problem as now you have to rescue from `SSHKit::Runner::ExecuteError` which is pretty generic, and not ideal.

I'd recommend reverting the below commit.

https://github.com/mperham/sidekiq/commit/ccc70d2ee1cbd5fe5510aa2cf96e310644bff024#commitcomment-14115772

**Comment by mperham** [comment]
Reverted, thanks for the note.  I should have checked for any change in semantics.
