### ISSUE TITLE
Simulate processing?

### ISSUE THREAD

**Issue by mhenrixon** [mperham/sidekiq#2637]
Hi,

I'm in the business of simulating Sidekiq processing. I want to get as close as possible to the real deal but I'd be fine using something like hawknewton/rspec-eventually, laserlemon/rspec-wait or http://myronmars.to/n/dev-blog/2012/03/building-an-around-hook-using-fibers. I want to make absolutely sure that for this edge case someone posted a while ago I am able to replicate what happens in production through a test case.

Let me try to explain what I want to do

```ruby
it 'rejects nested subsequent jobs with the same arguments' do
  Sidekiq::Testing.disable! do
    jid = SimpleWorker.perform_async 1
    expect(SimpleWorker.perform_async 1).to eq(nil)
    expect(SpawnSimpleWorker.perform_async 1).not_to eq(nil)

    Sidekiq.redis do |c|
      wait_for { c.llen('queue:default') }.to eq(1)
      wait_for { c.llen('queue:not_default') }.to eq(1)
    end

    launcher = Sidekiq::Launcher.new(queues: %w(not_default))
    launcher.run

    Sidekiq.redis do |c|
      expect(c.llen('queue:default')).to eq(1)
      wait_for { c.llen('queue:not_default') }.to eq(0)
    end

    launcher.stop

    Sidekiq.redis do |c|
      expect(c.llen('queue:default')).to eq(1)
    end

    launcher = Sidekiq::Launcher.new(queues: %w(default))
    launcher.run

    Sidekiq.redis do |c|
      expect(c.llen('queue:not_default')).to eq(0)
      wait_for { c.llen('queue:default') }.to eq(0)
    end

    launcher.stop
  end
end
```

Forget about configuration etc. I am fine with all the code and cumbersome setup I am basically just in the business of making sure that things happen in the right order. Do you have any better suggestions on how to achieve something equally trustworthy?

**Comment by mperham** [comment]
I don't have any suggestions.

**Comment by mhenrixon** [comment]
Do you mean that as in `I don't have any *better* suggestions` or `I don't give a shit, fuck off with the stupid none-issues`? Hard to tell by the answer...

**Comment by mperham** [comment]
Both and neither.  It's not a supported Sidekiq use case and I don't have any deep understanding of what you are trying to achieve so I don't want to speculate on how to best solve your problem.

**Comment by mhenrixon** [comment]
I want to simulate processing a single queue like in real mode and then switch to processing another queue. The first job has a sleep inside it and to simulate some time consuming work and the second job should be able to run at the same time.

I've been looking at the test suite but haven't found anything that I found particularly useful; the closest I've seen on what I want to do is https://github.com/mperham/sidekiq/blob/master/bin/sidekiqload

**Comment by ryansch** [comment]
We simulate processing using the standard `fake` testing mode alongside `timecop` in our test suite without issue.

**Comment by mhenrixon** [comment]
Thanks @ryansch! Unfortunately I am not entirely happy with that approach since I am doing all kinds of overrides on the overrides sidekiq::testing does. I want to verify that a certain scenario is always working the real deal so that users of the gem won't have to. I am more than happy to have a single slow test for that purpose.

**Comment by mperham** [comment]
I didn't realize you were the author of a unique plugin.  Got it, I understand why you'd want to do this now.  There's no official way to do integration testing like this so APIs might change but generally I try to keep things stable.

**Comment by ryansch** [comment]
Agreed.  Keep us posted if you come up with something clever.

**Comment by mhenrixon** [comment]
Not sure if anyone cares but this is what I came up with: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq/simulator.rb I have a test using the code here: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/spec/lib/sidekiq_unique_jobs/client/middleware_spec.rb#L25

**Comment by mperham** [comment]
@mhenrixon That looks great and this comment makes me happy: https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq/simulator.rb#L41

**Comment by mhenrixon** [comment]
@mperhamn version 4 seems a lot easier to work with for my purposes. Not sure why but I never liked celluloid to be honest and all the warnings about not stopping actors in time etc over the last few years has made me stay away from it. Now it was proven again. I couldn't get the test so work without a gazillion warnings in earlier sidekiq versions. All stemming from Celluloid. 

Glad you took the plunge!

**Comment by mperham** [comment]
Another positive Sidekiq 4.0 review, glad people are using it successfully, thank you!
