### ISSUE TITLE
Using alternate ConnectionPool

### ISSUE THREAD

**Issue by sloops77** [mperham/sidekiq#2638]
Hi,
I want to reuse my server's redis connection pool for sidekiq. But my sidekiq pool is namespaced separately from my main app's keys. My idea was to decorate the connections checked out of the pool by  executing a decoration block that wraps the retrieved connection in a RedisNamespace object.

While i have this to work inheriting from ConnectionPool it would be cooler to change the code in lib/sidekiq.rb from
```
  def self.redis=(hash)
    @redis = if hash.is_a?(ConnectionPool)
       hash
    else
       Sidekiq::RedisConnection.create(hash)
    end
  end
```

to

```
  def self.redis=(hash)
    @redis = if hash.responds_to?(:with)
        hash
      else
        Sidekiq::RedisConnection.create(hash)
    end
  end
```

Alternatively we could create a ConnectionPool superclass with `with`, `checkout` & `checkin` defined so that it could be inherited from for alternate implementations. Thoughts?

**Comment by mperham** [comment]
Use a monkeypatch.  That use case isn't something I want to officially support.

**Comment by sloops77** [comment]
No probs, i have a patched version in production now.

I would argue that the connection pooling is logically separate concept from wanting to namespace keys and hence should be handled via decoration or a filter. 

Here's a gist of what i did: https://gist.github.com/sloops77/dc5dfe7eec3c9424844e
