### ISSUE TITLE
undefined method `reliable_push!' for Sidekiq::Client:Class

### ISSUE THREAD

**Issue by jhollinger** [mperham/sidekiq#2640]
We just switched to Pro and are trying to enable the "reliability" feature per https://github.com/mperham/sidekiq/wiki/Reliability. But those methods don't seem to exist anymore. Is the documentation just out of date?

**Comment by mperham** [comment]
If you don't see those methods, you're not initializing your gems correctly.

**Comment by mperham** [comment]
For instance, `gem 'sidekiq-pro', require: false` will break.

**Comment by jhollinger** [comment]
This is what we have:

    source "https://REDACTED@gems.contribsys.com/" do
      gem 'sidekiq-pro'
    end

We also have some "plugins" like `sidekiq-gelf`, `sidekiq-unique-jobs`, and `sidekiq-failured` (those last two might be redundant now with pro - not sure).

**Comment by mperham** [comment]
Then you might not be booting Bundler correctly. https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#sinatra

My unique jobs feature is in Enterprise, not Pro.  I don't know what the other two do.

**Comment by jhollinger** [comment]
Yeah, I'm pretty sure we're booting bundler correctly. FWIW I located the sidekiq-pro gem folder on disk and grepped for `reliable_push`, `reliable_fetch`, and `reliable_scheduler` and found nothing except:

    lib/sidekiq/reliable_fetch.rb:puts "Warning: 'sidekiq/reliable_fetch' has moved to 'sidekiq/pro/reliable_fetch'"
    lib/sidekiq/reliable_fetch.rb:require 'sidekiq/pro/reliable_fetch'

**Comment by mperham** [comment]
It's at the bottom of lib/sidekiq/pro/push.rb

**Comment by jhollinger** [comment]
No such file here. Our Gemfile.lock locked sidekiq-pro in at 1.7.5 if that helps.

**Comment by mperham** [comment]
1.7.5 is over a year old.  "Just switched to Pro" implies you are using something current.  The docs cover the current major version.

**Comment by ryansch** [comment]
The documentation is for Pro 2.x. Please upgrade.

**Comment by jhollinger** [comment]
Yeah, we just switched a few weeks ago. No idea why bundler installed an ancient version. We certainly didn't tell it to.

**Comment by ryansch** [comment]
You probably need to upgrade sidekiq as well. Your Gemfile.lock will show you what Pro depends on.
