### ISSUE TITLE
Sidekiq freezing jobs, jobs randomly throwing exceptions

### ISSUE THREAD

**Issue by ewamarciniak** [mperham/sidekiq#2643]
Hi,
I have a problem that I hope you would be able to help me with. I had Sidekiq up and running for a long time and it worked like a charm until about a month ago, when I started seeing performance issues. The problem seems to be complex enough:

1. I get a number of errors like: "Lost connection to MySQL server during query", "MySQL server has gone away" which seem to be appearing on ActiveRecord queries that are quite simple. I've run those queries in the console without much of a problem. 
2. Jobs randomly freeze in the queue and are restarted with a Server restart - there is no warning. 

I looked up the first issue online and found nothing helpful. I suspect it is a configuration problem, that has to do with the connection to mysql database but don't know what this can be.  As for the second issue- in the Troubleshooting section of wiki you mention 2 reason for frozen processes- how can I find you which one is causing this. Can this be related to and caused by the first issue?

I will be grateful for any pointers that you could give me. 
All the best

**Comment by mperham** [comment]
I don't have any advice.  These types of issues can be caused by literally any code in your stack, from app down.  If you can reproduce the problem, `git bisect` might be an option.
