### ISSUE TITLE
Can't see job in queue

### ISSUE THREAD

**Issue by vanboom** [mperham/sidekiq#2646]
I have a worker in which I have assigned a non-default queue "myqueue" using sidekiq_options.

When I monitor the job in the Sidekiq UI, it properly shows the queue as "myqueue"... but when I use the Queues panel (i.e. http://localhost:3000/sidekiq/queues), the queue is empty, even though the job is still running. 

Furthermore, if I try to get the size of the queue using the API Sidekiq::Queue.new("myqueue").size, it returns zero. 

Is this a bug?  Or possibly there is a configuration I am missing? 

thanks!

**Comment by mperham** [comment]
When a job is being worked on, it's no longer in the queue.  It's being worked on.  :-)

**Comment by vanboom** [comment]
Roger that!  :)
