### ISSUE TITLE
Testing sidekiq worker RetrySet

### ISSUE THREAD

**Issue by ganeshkumar** [mperham/sidekiq#2648]
I have a worker 

class MyWorker
  include Sidekiq::Worker
  sidekiq_options :retry => 5

  def perform(input_Data)
   logic to manipulate data
  end
end

I tried to test the above code using minitest and i see that the job is not going to retry queue only in testing. Any help ? Thanks in advance.

Sidekiq::Testing.inline! do
  Sidekiq::Testing.server_middleware do |chain|
       chain.add Sidekiq::Server::Middleware::RetryJobs
  end
  MyWorker.expects(:connect).raises(Exception)
  MyWorker.perform_async(input data)
  assert_equal 1, Sidekiq::RetrySet.new.size
end

**Comment by we4tech** [comment]
Hi @ganeshkumar  what's your specific sidekiq version ?

**Comment by ganeshkumar** [comment]
I am using 3.5.2 version.

**Comment by mperham** [comment]
Answered on stackoverflow

**Comment by LeZuse** [comment]
@mperham Can you please provide a link for others?

**Comment by Tensho** [comment]
@LeZuse https://stackoverflow.com/questions/33580605/testing-sidekiq-worker-and-retryset-rails-minitest
