### ISSUE TITLE
sidekiq Install missing gem executables with `bundle install` on AWS Elastic beanstalk ruby standalone

### ISSUE THREAD

**Issue by marcelamiach** [mperham/sidekiq#2650]
I use AWS Elastic Beanstalk Ruby standalone to deploy my rails application.

I use rails 4.1.0 and I am trying to deploy my app using sidekiq. In development mode, I have no problem.

I have the following code to deploy it to elastic beanstalk:
```
commands:
  create_post_dir:
    command: "mkdir /opt/elasticbeanstalk/hooks/appdeploy/post"
    ignoreErrors: true
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/50_restart_sidekiq":
    mode: "000777"
    content: |
      #!/usr/bin/env bash
      cd /var/app/current

      if [ -f /var/app/support/pids/sidekiq.pid ]
      then
        kill -TERM `cat /var/app/support/pids/sidekiq.pid`
        rm -rf /var/app/support/pids/sidekiq.pid
      fi

      . /opt/elasticbeanstalk/support/envvars.d/sysenv

      sleep 10
      
      chmod -R 777 /var/app/support/logs/
      chmod -R 777 /var/app/current/log/

      bundle exec sidekiq \
        -e production \
        -P /var/app/support/pids/sidekiq.pid \
        -L /var/app/support/logs/sidekiq.log \
        -q default \
        -d

  "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_sidekiq":
    mode: "000777"
    content: |
      #!/usr/bin/env bash
      if [ -f /var/app/support/pids/sidekiq.pid ]
      then
        kill -USR1 `cat /var/app/support/pids/sidekiq.pid`
      fi
```

I get the following log: 
"Command failed on instance. Return code: 127 Output: bundler: command not found: sidekiq Install missing gem executables with `bundle install`. Hook /opt/elasticbeanstalk/hooks/appdeploy/post/50_restart_sidekiq failed."

When I ssh and run ```bundle exec sidekiq```, I have no problems. But, I can't deploy new version with this code automatically.

**Comment by mperham** [comment]
Hi @marcelamiach, I don't know anything about EBS so can't help.  Please ask on an AWS forum or StackOverflow.

**Comment by fagiani** [comment]
Just for the record, I had the same issue recently and it looks like when you clone a environment on AWS elastic beanstalk it will bug the new setup and this error therefore happens. To fix it, create a new environment from scratch.

Hope it helps as it took me several hours to figure this out!
