### ISSUE TITLE
Sidekiq not putting Job back into queue after SIGTERM

### ISSUE THREAD

**Issue by onetwopunch** [mperham/sidekiq#2653]
I have several workers that use `Open3` to run `ffmpeg` and other long running commands and save progress to a database. The problem is that when a deploy or log roll happens (every morning), unicorn restarts and the jobs get lost. I would like to see these jobs get re-enqueued and restarted after sidekiq restarts but they don't. 

I'm assuming this has to do with this issue https://github.com/mperham/sidekiq/issues/110 but I've tried many things to try to get it to work and it doesn't seem to. I currently have the following signal handler code run before the `Open3.popen3` call:

    #Signal handler for when Sidekiq restarts
    sig = "TERM"
    Signal.trap(sig) do
      if pid
        Logplexer.info( "Caught SIGTERM from unicorn. Killing child process #{pid}")
        Process.kill(sig, pid)
      end
      #Forward TERM signal back to self
      Process.kill(sig, 0)
    end

Then `@pid` is set inside the popen3 block. When I run this, it's successfully sending SIGTERM to the child process as well as the parent, but the job never gets re-enqueued. 

According to this wiki https://github.com/mperham/sidekiq/wiki/Signals#term, it should re-enqueue before exiting, but it never does.

Any help is appreciated.

BTW we are using Pro. Would [reliable_fetch](https://github.com/mperham/sidekiq/wiki/Reliability) help out here?

**Comment by mperham** [comment]
I'm confused by your use of Unicorn and Sidekiq together.  What does one have to do with the other?

Yes, reliable fetch will ensure that jobs will be restarted, even if they don't get pushed back to the queue.

Generally if you are losing jobs during deploy, it's because you aren't giving Sidekiq enough time to shut down properly.  The `-t` timeout is for graceful shutdown.  Sidekiq can take several seconds beyond the `-t` time to kill the remaining busy worker threads and push back those remaining jobs if the network is slow, etc.  The default timeout is 8 secs; after 8 seconds, Sidekiq will start the "hard shutdown" process.

**Comment by onetwopunch** [comment]
@mperham Sorry for the confusion, unicorn being restarted is irrelevant. I tried reliable fetch and the job was still not enqueued. It turns out that since we're using upstart to kill processes, the process group is killed with SIGTERM, which immediately kills the sidekiq job and the process it forked as well. What we are trying to do now to avoid this is essentially wrap the forked process in the bash script that can ignores the first SIGTERM to let the process time out, then it will hopefully get re-enqueued which doesn't work either. I think I'm going to have another look at reliable jobs since the last time I tried, it told me it was initialized then didn't re-enqueue the job after the failure. Any input is appreciated.

**Comment by mperham** [comment]
Reliable fetch means the job is never removed from Redis until it is actually finished.  It doesn't need to be re-enqueued.

**Comment by onetwopunch** [comment]
@mperham Right, but if the SIGTERM makes the job finish, the job does not restart once sidekiq is restarted. Is there extra code I need to add to make this functionality happen?

**Comment by mperham** [comment]
If the job stops without raising an error, that's a success.  You need to make sure your job either doesn't stop or raises an error.

**Comment by onetwopunch** [comment]
@mperham Thanks so much for the help, I took another look through the code and it turns out there was a case where it would fail without raising an error. Once I surfaced that error, it restarted just fine. Thanks :+1:
