### ISSUE TITLE
"Stack level too deep" - Rails 3.2

### ISSUE THREAD

**Issue by charlie-ablett** [mperham/sidekiq#2654]
Hi there, 

I'm migrating from Resque 1.25 on a Rails 3.2 legacy app. I've commented out Resque in the relevant bits (including initialisers), modified the workers to use Sidekiq. 

I've also removed the mounted Sidekiq app and mounted the Sinatra app via the routes file. As far as I'm aware, I haven't done anything extra, and I've followed the normal installation procedure. When I start my server and navigate to `localhost:3000/sidekiq`, I get:

    SystemStackError - stack level too deep:
     /home/user/.rvm/gems/ruby-2.0.0-p481@example.com/gems/sidekiq-3.4.1/lib/sidekiq/web.rb:16

Any help appreciated :)

**Comment by mperham** [comment]
I don't have an answer, try upgrading Sinatra to latest.

**Comment by charlie-ablett** [comment]
I literally just installed Sinatra to use carrierwave, so it didn't have to update anything, but I did anyway.

> Using sinatra 1.0

**Comment by mperham** [comment]
Sinatra 1.0 is ancient.  Sidekiq requires 1.3+.

**Comment by charlie-ablett** [comment]
Ah yes, I see that sinatra had been locked by another gem to v1.0. Sorted, thanks.
