### ISSUE TITLE
Sidekiq restarts automatically in a different environment

### ISSUE THREAD

**Issue by andresakata** [mperham/sidekiq#2656]
I'm running Sidekiq in my production environment, and everything works fine.

But, for some reason, at sometime, Sidekiq reboots automatically and uses a different environment when getting up - i can see that because it tries to connect in a development database.

Why could it restart? And why getting a different environment after that - is something to set up?

I am using capistrano-sidekiq for deployment.

**Comment by Apokly** [comment]
I have same issue. At a certain moment (not same everyday), Sidekiq working on my production server loses every scheduled jobs + stats and "reboot", sometimes adding a con job into development environment.

Need to find manually what jobs were scheduled and re-schedule them. Nothing looking like a bug or an error in Sidekiq logs (both development and production). Queues are still actives even after a "reboot" btw.

**Comment by mperham** [comment]
This sounds like an application or environmental issue.

**Comment by Apokly** [comment]
Hey @andresakata, are you using Sidekiq on the same server ?

Found this : http://doc.gitlab.com/ce/operations/sidekiq_memory_killer.html

**Comment by andresakata** [comment]
Actually, i am not using GitLab, but it seens to be related to memory - i increased the memory swap file and stopped restart...

**Comment by andresakata** [comment]
I discovered what was happening in my case, and even that it was an environment issue (not related to Sidekiq), i'll explain here because it can occurs with others too.

We use `capistrano-sidekiq` with `monitor` to make deploys. So, `monitor` sets up a daemon configuration to turn on Sidekiq again if some error occurs.

The problem was that in `/etc/monit/conf.d/`, which is where the daemon command lies, there was an old configuration for a different environment (because that machine used to be used for development).

So, if you are noticing this behavior (Sidekiq changing its environment magically), and you use `monitor`, check monitor configurations, clean it up, and restarts it.
