### ISSUE TITLE
Enterprise: Unable to bypass `unique_for`

### ISSUE THREAD

**Issue by RobinDaugherty** [mperham/sidekiq#2658]
According to [the doc](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#bypassing-uniqueness) (and also the doc block in `unique.rb`), we should be able to bypass a job's `unique_for` setting by adding `unique_for: false`. I just ran into an issue where we had to requeue some items, and I couldn't because of the unique constraint.

I tried to use the following:

```ruby
Sidekiq::Client.push('class' => 'IndexUpdatingWorker', 'args' => [klass, ids], 'unique_for' => false)
```

and got

```
NoMethodError: undefined method `to_i' for false:FalseClass
from /data/aperture/releases/20151113030912/vendor/bundle/ruby/2.2.0/gems/sidekiq-ent-0.7.5/lib/sidekiq-ent/unique.rb:64:in `call'
```

Looking at the code, I thought maybe this would work:

```ruby
Sidekiq::Client.push('class' => 'IndexUpdatingWorker', 'args' => [klass, ids], 'unique_for' => 0)
```

but I then got

```
Redis::CommandError: ERR invalid expire time in SETEX
from /data/aperture/releases/20151113030912/vendor/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
```

I'm at a loss. It seems that the documentation is wrong, but I don't have a better answer.

To solve this, I would settle for a way to add the jobs while bypassing uniqueness, or a way to reset and clear out the list of unique hashes.

**Comment by mperham** [comment]
0.7.8 is now available with this fix.
