### ISSUE TITLE
Add ability to specify shard for batch information

### ISSUE THREAD

**Issue by johnathanludwig** [mperham/sidekiq#2660]
In sidekiq-pro you've added the ability to shard batches. With that change it is chosen randomly which shard the batch information is going to live in. It would be useful to us to be able to specify the shard the batch information goes to.

In our case we are setting up different shards that have workers dedicated to specific queues that have lots of work. We create a batch and send the jobs to their respective shard. However we have callbacks on our batch that are for a different queue which get processed by the workers on the primary shard. If the batch information gets sent to one of the dedicated shards shard we see those callbacks get queued on that shard where there isn't a worker watching the queue.

**Comment by johnathanludwig** [comment]
Actually I believe the callback jobs get sent to whichever shard processed the last job for the batch. If thats the case then the option needed would be able to specify the shard index for the callback job.

**Comment by mperham** [comment]
My gut reaction is this leads to an overly complex network architecture.  I'd prefer to keep sharding batches randomly.  Can you use a 'callback' queue that all workers on all shards listen to?

**Comment by johnathanludwig** [comment]
Yeah that is what I am doing now. I just wanted to avoid adding another queue to the other workers and making sure all callbacks use the same one. Especially since we should avoid having a bunch of queues.

This is still true right?
> I don't recommend having more than a handful of queues. Sidekiq is not designed to work well with dozens of queues.

**Comment by mperham** [comment]
Unfortunately it is true until Redis adds [this feature request](https://github.com/antirez/redis/issues/1785)

**Comment by johnathanludwig** [comment]
Alright, thanks for the help! The callback queue solution is easy enough.

**Comment by johnathanludwig** [comment]
We are experimenting with creating a separate service for some of our jobs to remove some heavy dependencies from our main application in the same style mentioned [here](brandonhilkert.com/blog/sidekiq-as-a-microservice-message-queue/). The main difference is that we would also be using multiple shards to even out the load.

The jobs that run on the other service would be part of a batch but would not have access to the code for the callbacks so they wouldn't be able to run on that shard.

I was looking at the batch code again and see 7 different points which push callback jobs to a queue. We could extract that into one place, and add an option to the batch to specify a target shard index for callback jobs. Then in that method send it to the shard index if it is present. A less flexible option would be to make a global config option providing the pool for callback jobs so it doesn't have to be set in and pulled out of redis.

What are your thoughts on doing something like this? If it's not acceptable, the extraction into a method would still be helpful and make it simple for me extend in my own code.

**Comment by mperham** [comment]
@johnathanludwig Without knowing more about the exact problem and architecture, it sounds like you're trying to put a square peg into a round hole.  If this is truly an independent service, it shouldn't be relying on hacks like specific shards.  Perhaps your extracted batch could run a callback which makes an HTTP call back to the original service, that service pointing to a different set of servers so it can execute the actual callback logic.

**Comment by johnathanludwig** [comment]
I am trying to just split out a few workers into their own sidekiq application with the minimal amount of changes to the existing code.

In this case, we would have batches generated on the primary workers. These batches generate some jobs for the workers that would move to the other application. Those jobs in turn generate jobs that are run by the primary workers (still part of the batch). So it's a bit of back and forth. I'd like to not have it know about shards as well but then the batch wouldn't know if the jobs were run, and the jobs generated by the separate application wouldn't be part of that batch.

I realize it it isn't the best design, but I am trying to avoid refactoring the process any more than I have to already from pulling out this dependency. Sidekiq already has the functionality to allow this to work by pushing things to other shards and looking batches up on other shards. It's just barely missing the bit of control we need on where the callback jobs end up. I could monkey-patch but the methods that send the callbacks are quite large and I'd like to avoid making it brittle.

Is just the extraction of the pushes to callback queues ok? I could submit a PR for that. That would allow me to override the method on my end more safely to wrap with block to send it to a specific shard.

**Comment by mperham** [comment]
Sure, I'm ok with centralizing the callback push if you want to send a PR.  I won't add support to do this out of the box.  It's one step too far for my comfort.
