### ISSUE TITLE
Testing mode no longer working

### ISSUE THREAD

**Issue by sethvargo** [mperham/sidekiq#2663]
After upgrading to 4.0, any job that uses the following format is failing:

```ruby
expect {
  MyWorker.perform_async("arg")
}.to change(MyWorker.jobs, :size).by(1)
```

Is this a regression?

I'm going to go code diving, but I suspect that the value of `job` is somehow being cached, because this works:

```ruby
expect {
  MyWorker.perform_async("arg")
}.to change { MyWorker.jobs }
```

**Comment by petergoldstein** [comment]
@sethvargo @brandonhilkert This appears to be due to the queue-based jobs change that was recently introduced.

Specifically, the worker class' `jobs` method used to return a reference to the underlying array of jobs.  That array gets updated when new jobs are added.  Now the `jobs` method returns an array derived from the underlying array at the time the method is called, and this derived array is not updated as jobs are added to the queue.  See below:

           def jobs
    -        Worker.jobs[self]
    +        Queues.jobs[queue].select { |job| job["class"] == self.to_s }
           end

**Comment by mperham** [comment]
@brandonhilkert I'm pretty busy at rubyconf.  Can you fix and/or revert, whatever you're comfortable with?  I'll get a 4.0.1 release out asap with whatever you decide.  I'm ok with killing the feature if it's half-baked.  Likely no one is using it yet.

**Comment by sethvargo** [comment]
@mperham oh have fun at RubyConf!

In my testing and exploration, it looks like RSpec is quietly moving away from the `change(thing, :method)` toward `change { }`. None of the documentation recommends that pattern anymore. While it hasn't been deprecated, I wonder if it would just be worth calling out in the changelog as a breaking change (it was a major version bump after all), and updating the wiki?

**Comment by mperham** [comment]
@sethvargo There's millions of lines of Ruby with that pattern.  I don't want to break everyone's code just for this feature that slipped in late.

**Comment by brandonhilkert** [comment]
PR for the revert: https://github.com/mperham/sidekiq/pull/2664

**Comment by mperham** [comment]
4.0.1 is out.

**Comment by brandonhilkert** [comment]
@sethvargo Any chance you could run your tests against the updated `queue-api` branch?

**Comment by sethvargo** [comment]
@brandonhilkert I refactored all our tests to use the other RSpec syntax when we were blocked by the original issue. So, yes, I can run them, but it won't be a good indicator if the problem is fixed :smile:. Sorry!

**Comment by brandonhilkert** [comment]
Bummer, ok. Any chance you can change one of them to use `change()`. If not, not big deal :)

**Comment by sethvargo** [comment]
Hey @brandonhilkert  - I just changed one test back to the old syntax and it's still failing. The gemfile is pointing to the queue-api branch off mperham/sidekiq.

**Comment by brandonhilkert** [comment]
@sethvargo Thanks for the update. I appreciate it.

**Comment by sethvargo** [comment]
@brandonhilkert no problem. It might be worth just adding a test to sidekiq itself to verify the behavior doesn't regress

**Comment by brandonhilkert** [comment]
@sethvargo Definitely. I attempted to, but perhaps I'm not doing it right. The test suite isn't Rspec, so it makes it a little challenging. 

https://github.com/mperham/sidekiq/commit/c4330cb32628627045287b22442cf71600218108#diff-db88da5a19a4fee1b469d961e1d38a81R333
