### ISSUE TITLE
Slow net requests from workers

### ISSUE THREAD

**Issue by vnazarenko** [mperham/sidekiq#2666]
Hi, we have a strange situation with net to api from workers. We have a lot of jobs which do a some amount of external requests ( using httpclient gem), and locally it took something like 600-700ms for 1 request, but in sidekiq, it tooks like 5 - 10 times more ( 4 - 8 seconds). What could you suggest to improve this?

**Comment by mehdi-farsi** [comment]
Hi,

This issue partially covers the problem. You can start there:

[issue 1946][https://github.com/mperham/sidekiq/issues/1946#issuecomment-55517693]

**Comment by vnazarenko** [comment]
Thanks
