### ISSUE TITLE
Enterprise: Periodic job list does not update unless web servers are stopped

### ISSUE THREAD

**Issue by RobinDaugherty** [mperham/sidekiq#2668]
We use Passenger Enterprise on our web servers, which performs a rolling restart of the Rails process, starting a new Rails server process before it kills the old one.

After making a change to our list of Sidekiq periodic jobs (removing one entry and changing the cron pattern of another), the list in the Cron tab of the Sidekiq web interface is still showing the old list. After an upgrade from Sidekiq v3.5.1 / Pro v2.1.1 / Enterprise v0.7.5 to Sidekiq 4.0.1 / Pro 3.0.0 / Ent 1.0.0, the list of periodic jobs was left empty. Downgrading to the previous version didn't fix it.

It seems that even though we're restarting all Sidekiq processes, since we're not killing all web server processes, the Periodic job list is not being reloaded.

**Comment by mperham** [comment]
Make sure you are running the latest as there have been bug fixes in the periodic stuff.  In fact I will be pushing a new release tomorrow with another periodic fix for an outstanding bug.

**Comment by mperham** [comment]
Ent 1.0.1 is out.  Can you reproduce the issue with the latest version?

**Comment by RobinDaugherty** [comment]
I've upgraded to Ent 1.0.0 and Sidekiq 4.0.1. Now the displayed Cron list is empty. I'm trying to determine whether jobs are actually running, but it doesn't look like it.

**Comment by mperham** [comment]
There's not much to go on here.  Can you shut down everything, start up one Sidekiq process and then refresh the Web UI?

**Comment by RobinDaugherty** [comment]
I've shut down all sidekiq processes, and restarted the web processes. But our web servers use Passenger in rolling-restart mode, which starts a new Rails server process before killing the old one.

After downgrading to Sidekiq 3.5.3 / Pro 2.1.3 / Ent 0.7.8, the Cron list is still empty.

I've scheduled a maintenance window where I'll shut down the web servers completely while the sidekiq processes are also shut down and see if that fixes it. If not, I'll switch to a new, empty Redis instance to see if that fixes it.

**Comment by RobinDaugherty** [comment]
Fully shutting down the Rails web server instances fixed the issue. I've updated the issue description and title to reflect the actual issue, which is that we're using rolling restarts for the web processes.

Is it possible that I'm going to find a way to fix this? (It doesn't make a ton of sense to me because I thought the Rails server processes would have not act like a Sidekiq server instance.) I could make a call from Capistrano during a deployment for example, if I can figure out what.

**Comment by mperham** [comment]
That behavior doesn't make any sense to me.  The Web UI fetches the current version of the periodic data and displays the associated periodic jobs, see lib/sidekiq-ent/periodic.rb line 26.  It does not cache anything; refreshing the page should show the latest.  I have no idea why you'd need to shut the web processes down.

**Comment by RobinDaugherty** [comment]
I'm going to put together a better test case to confirm the original issue and that it's still an issue.

**Comment by mperham** [comment]
Reopen if you find anything.
