### ISSUE TITLE
Footer covers the bottom of page content

### ISSUE THREAD

**Issue by RobinDaugherty** [mperham/sidekiq#2669]
This may be specific to Enterprise. With a switch of routes from Sidekiq Pro to Sidekiq Enterprise, the Enterprise interface has a larger footer that covers the bottom of the page content if that content is tall enough.

This is with Sidekiq v3.5.1 / Pro v2.1.1 / Enterprise v0.7.5.

![sidekiq web interface footer overlap-1](https://cloud.githubusercontent.com/assets/1005280/11249328/29b7eac0-8df4-11e5-8b26-f780f3fbe1ff.jpg)

**Comment by mperham** [comment]
That's fixed in 4.0.

**Comment by RobinDaugherty** [comment]
Confirmed, it's fixed in Sidekiq 4.0.
