### ISSUE TITLE
Possible Sidekiq performance regression?

### ISSUE THREAD

**Issue by benubois** [mperham/sidekiq#2672]
Hi @mperham,

The upgrade to 4.0 went smoothly for me and everything has been stable. Thanks! 

However, one thing I noticed is that average execution time went up after the upgrade. Here's a few jobs that get run a lot on Feedbin. 

![performance](https://cloud.githubusercontent.com/assets/133809/11280134/3ad71bea-8ea9-11e5-8cb0-dce4452e959a.png)

The vertical line is when the upgrade happened. The large spikes are from daily database maintenance and backups.

I'd be happy to provide more information or dig into this but if it's an isolated incident then no worries, this isn't negatively impacting anything for me.

Here's the code that measures performance:

```ruby
require 'sidekiq'

Sidekiq.configure_server do |config|
  ActiveRecord::Base.establish_connection
  config.server_middleware do |chain|
    chain.add WorkerStat
  end
end

class WorkerStat
  def call(worker, item, queue)
    Librato.timing "worker.#{worker.class.to_s.underscore}" do
      yield
    end
  end
end
```

**Comment by mperham** [comment]
AFAIK nothing changed in how workers are executed.  I'm really surprised as you shouldn't see any change in time within a middleware yield.  Is it possible another gem was updated as part of the upgrade which is causing this?

**Comment by benubois** [comment]
> Is it possible another gem was updated as part of the upgrade which is causing this?

Thats a good point! Looks like I did go from Rails 4.2.4 -> 4.2.5 and pg 0.18.3 -> 0.18.4 at the same time. I could try downgrading to see if that changes anything. However I'm not seeing much of a change in controller performance after the update.

<img width="1385" alt="screen shot 2015-11-19 at 11 01 03 am" src="https://cloud.githubusercontent.com/assets/133809/11280913/168d2e1a-8ead-11e5-896e-b50ad082e15e.png">

**Comment by mhenrixon** [comment]
Probably not related but SidekiqUniqueJobs test suite went from 0.7 seconds to 6-7 seconds with the upgrade. I think it has to do with one specific *integration* test I have though where I wait for some stuff asynchronously in the test. With Celluloid I could just force quite (terminate) with the new API I have to wait for workers to be available/stopped in the test before executing the code.  I think specifically it is the waiting for the workers to shut down that is causing me the slowdown.

Apart from that I see no negative change when testing at least.

**Comment by benubois** [comment]
I have a little more data now. I have two servers with the same hardware. One is running Sidekiq 3.5.3, the other is running 4.0.1. I'm still seeing higher average perform times with 4.0.1.

To do this I updated the profiling code to also report the Sidekiq version.

```ruby
class WorkerStat
  def call(worker, item, queue)
    Librato.timing "worker.#{worker.class.to_s.underscore}", source: Sidekiq::VERSION do
      yield
    end
  end
end
```

![1](https://cloud.githubusercontent.com/assets/133809/11330251/da85e5a8-915c-11e5-8d6b-597af1ff40ed.png)
![2](https://cloud.githubusercontent.com/assets/133809/11330252/da875802-915c-11e5-8164-a321a3f63249.png)
![3](https://cloud.githubusercontent.com/assets/133809/11330259/f5a0ea7c-915c-11e5-9c40-8e5e405380fb.png)

One thing about my setup is redis is running in a separate data center with ~7ms latency to the servers running sidekiq. Maybe this has something to do with 4.0's parallel fetch?

**Comment by mperham** [comment]
You are timing what's happening inside that yield. None of sidekiq's code runs within that yield. Are you using Sidekiq.redis within your worker?  Is it possible you need to increase your connection pool size?

**Comment by benubois** [comment]
worker.feed_refresher_receiver does call `Sidekiq.redis` but the other two do not.

I just added stats to count the number of jobs each is performing. It looks like 4.0.1 processes a lot more jobs so maybe the average time is up due to resource contention?

![count](https://cloud.githubusercontent.com/assets/133809/11330647/765cdbac-9163-11e5-98fe-5ea158434976.png)

**Comment by benubois** [comment]
Well 4.0.1 is definitely utilizing the hardware more, looking at the load averages and job count below. I think average execution time being up might not really be meaningful based on how much more volume is going through. What do you think?

![load](https://cloud.githubusercontent.com/assets/133809/11330814/8580d3f6-9166-11e5-8989-26007db28914.png)
![count](https://cloud.githubusercontent.com/assets/133809/11330815/85814cc8-9166-11e5-9776-fc52030b2332.png)

**Comment by mperham** [comment]
Yeah, it looks like you're actually pegging the CPUs now with 4.0 so you might need to reduce concurrency and increase processes.  That's possibly why your time is up: CPU starved.

**Comment by benubois** [comment]
Thanks! Yeah, it looks like I need to rebalance processes and threads a bit. Adding more processes and reducing threads has already brought down average execution. Will continue to tweak that.
