### ISSUE TITLE
ActiveRecord connection pool issue

### ISSUE THREAD

**Issue by penso** [mperham/sidekiq#2674]
Hi,

I'm trying to fix an issue about exhausting my activerecord connection pool. I log the current connections from within the worker to try to find a pattern but it doesn't give me much details. The reserved connections keep growing, and I feel like some connections aren't released. I do not use any `Thread` within the worker and I use `ActiveRecord::Base.connection_pool.with_connection` but the problem remains. I catch all Exceptions in the Worker as well.

I use sidekiq 4.0 (but I think I had that bug before), rails 4.0.13 and mysql 0.3.18. Any help would be appreciated.

My worker looks like:

```
class RssParserWorker
  include Sidekiq::Worker
  include LogWorker # for the log method

  sidekiq_options queue: :rss_parser

  def perform(id, method, *args)
    log "#{$$} #{jid} BEFOR available: #{ActiveRecord::Base.connection_pool.instance_variable_get("@available").instance_variable_get("@queue").size}; "  +
      "reserved: #{ActiveRecord::Base.connection_pool.instance_variable_get("@reserved_connections").size}; " +
      "total: #{ActiveRecord::Base.connection_pool.instance_variable_get("@connections").size}; " +
      "pool size: #{ActiveRecord::Base.connection_pool.size}"
    ActiveRecord::Base.connection_pool.with_connection do
      instance = RssFeedr.find(id)
      instance.send(method, *args) if instance
    end
    log "#{$$} #{jid} AFTER available: #{ActiveRecord::Base.connection_pool.instance_variable_get("@available").instance_variable_get("@queue").size}; "  +
      "reserved: #{ActiveRecord::Base.connection_pool.instance_variable_get("@reserved_connections").size}; " +
      "total: #{ActiveRecord::Base.connection_pool.instance_variable_get("@connections").size}; " +
      "pool size: #{ActiveRecord::Base.connection_pool.size}"
  rescue ActiveRecord::RecordNotFound
    log "sidekiq: RssFeedr #{id} not found"
  rescue Exception
    log "Exception: #{$!}"
    raise $!
  end
end
```

**Comment by penso** [comment]
My logs starts like:

```
BEFOR available: 0; reserved: 1; total: 1; pool size: 60
(... some time later ...)
AFTER available: 2; reserved: 9; total: 11; pool size: 60
(... some time later ...)
BEFOR available: 0; reserved: 60; total: 60; pool size: 60
Exception: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
```

So there are clearly connections not being put back to the pool, but I can't find a way to track those. I guess I could manually pull out a connection from the pool myself and using `ensure` in the worker to put it back?

**Comment by penso** [comment]
Oh and I use 10 concurrency in the Sidekiq configuration file. So anything > 20 connections is probably abnormal.

**Comment by mperham** [comment]
You need to determine the backtrace of where those connections were reserved by instrumenting AR yourself.  This isn't a Sidekiq bug so closing.

**Comment by penso** [comment]
Upgrading to Rails 4.2 seems to have fixed it. Thanks @mperham for the hard work on sidekiq.
