### ISSUE TITLE
Scheduled (Throttled) jobs in Sidekiq::Batch

### ISSUE THREAD

**Issue by fillman** [mperham/sidekiq#2675]
Example use case (most of code removed):
```ruby
class Worker
   ...
   def self.update_all
     ...
     batch.jobs { perform_async } # many jobs scheduled here
   end
end
```
This will schedule jobs inside of batch and will increment `job count` in batch.
Lets say we have a throttle middleware:
```ruby
class ThrottleMiddleware
  def call(worker, job, queue, redis_pool)
    # here we want to catch the job before it run
    # and reenqueue it if it exceeds throttle
    ...
    if exceed_maximum_number_of_jobs
      batch = Sidekiq::Batch.new(job['bid'])
      batch.jobs { worker.class.perform_in(1.hour, job['args']) } # Boom, this will increment job count once more (first time in worker class in +update_all+ method), which will lead to (picture attached)
    else
      yield # otherwise process job in batch
    end
  end
end
```
It seems to me that problem is in `perform_in` it doesn't accept batch id.
I could add `job['at'] = delay` and `yield` but inside of `perform_in` some validations are made, and I don't want to duplicate them. 

![screen shot 2015-11-22 at 7 28 37 pm](https://cloud.githubusercontent.com/assets/43970/11337434/a359ed2e-91f5-11e5-87fb-7d2ecde5dd23.png)

**Comment by fillman** [comment]
The problem here is that batch.jobs {} increment job count no matter if job is added to queue or not.

**Comment by mperham** [comment]
You have to make sure your middleware comes after the batch middleware or returning early by not yielding will not mark the batch job as a success.
