### ISSUE TITLE
Big refactor required for 4.0.1 upgrade

### ISSUE THREAD

**Issue by fedenusy** [mperham/sidekiq#2683]
I frequently call `MyClass.delay.some_method`, or `OtherClass.delay_for(1.minute).some_other_method`. But because of [this change](https://github.com/mperham/sidekiq/commit/242109e872090c1214ff848ea409c3e2de2d994f), all those invocations now raise errors.

What should I use as the new, correct syntax? The errors suggest to use `perform_async` and `perform_in`, which implies I should rename all delayed class methods to `perform`.

This is a big refactor for my codebase. It'll prevent me from upgrading to 4.0.1 for quite some time. Is there any way around this issue?

**Comment by mperham** [comment]
Those classes should not be workers.  Worker classes have a single public perform method.  By stuffing a bunch of static methods into a worker class, you are turning it into a utility drawer class, violating SRP.

You can split your code into two classes: one for the Worker and one which holds all the misc class methods to delay.

**Comment by mperham** [comment]
And I'm sincerely sorry this breaks your code.  The change was made because some people were actually doing MyWorker.delay.perform(args...); I'm trying to be pro-active to show people the expected way to use Sidekiq's APIs.

**Comment by fedenusy** [comment]
Just to make sure we're on the same page, I'll illustrate my use case in more detail:

```
class A
  include Sidekiq::Worker

  class << self
    def method_1
      # do something
    end

    def method_2
      # do something else
    end

    def method_3
      method_1
      # do another thing
      method_2
    end
  end

  def some_instance_method
    # do something
  end
end
```

Several parts of my codebase call `A.method_1`, `A.method_2`, and `A.method_3` synchronously. It makes sense to group these methods together under `class A`, since they're closely related to each other.

Are you suggesting I create 3 new classes (`A::Method1Worker`, `A::Method2Worker`, and `A::Method3Worker`), and then call `perform_async` on *those* Worker classes?

If that's your suggestion, I'm not sure I see the benefit. In fact, it feels like my code would be *harder* to maintain this way. Now I have to create a new file whenever I want to delay a class method, and if I decide to rename the class method, I have to update the Worker class.

It seems like a very opinionated, sudden change in sidekiq's public API. But if you're sticking to it, then I guess I have no choice :/

**Comment by mperham** [comment]
No, I'm suggesting you create `AWorker`:

```ruby
class AWorker
  include Sidekiq::Worker
  def perform
    A.delay.method1
    A.delay.method2
    A.method3
  end
end
```

**Comment by fedenusy** [comment]
Calling `perform_async` on `AWorker` would trigger all 3 methods.

I need to delay each method independently, which means I'd have to write a wrapper Worker class for each of the 3 methods.

IMHO [this change](https://github.com/mperham/sidekiq/commit/242109e872090c1214ff848ea409c3e2de2d994f) is a step backwards in terms of sidekiq's public API. Easily avoidable if we tweak the `delay` proxy object instead.

If you agree I'll happily give it a try and submit a PR.

**Comment by jonhyman** [comment]
Just as an outside observer here, that `delay` works at all is a hack IMO. You can't set any sidekiq options like which queue, retry behavior, etc. when you use `delay`. IMO it's a relic from DelayedJob and exists for ease of switching.

Why does `class A` need to be a `Sidekiq::Worker`? Can you remove that, and then you can call `delay` on it?

**Comment by fedenusy** [comment]
@jonhyman that just makes way too much sense. Didn't know that was possible. Thank you.

**Comment by mperham** [comment]
@jonhyman You can set the options: `Class.delay(queue: :low).method`

**Comment by jonhyman** [comment]
Hah I stand corrected then :grin:
