### ISSUE TITLE
Allow Window/Bucket limiters to take Integer intervals as well as sym

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2686]
Its pretty common for APIs that I interact with to have 5-second, 10-second, 30-second request rate limits on them. It looks pretty straight forward to add but since its enterprise only, I can't just send you a PR.

**Comment by mperham** [comment]
I've wondered about this.  I'll look into it.  Are you on Enterprise 1.0 or 0.x?

**Comment by kreynolds** [comment]
1.0.1

**Comment by mperham** [comment]
0.7.9 and 1.0.2 will allow window limiters to have an arbitrary window size:

```
# allow 5 calls within 30 seconds
Sidekiq::Limiter.window("foo", 5, 30)
```

**Comment by ryansch** [comment]
:+1:

**Comment by kreynolds** [comment]
huzzah

**Comment by mperham** [comment]
Now available!
