### ISSUE TITLE
Job link in batch interface should link to scheduled jobs, not retries when the error is OverLimit

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2687]
As you can see in the following screenshot, the link when there is an OverLimit error goes to retries, except those jobs are not retried, they are scheduled in the future so it links to nothing. (mouse is currently hovering over a job link and you can see it in the status bar)

![screen shot 2015-12-02 at 3 45 51 pm](https://cloud.githubusercontent.com/assets/324744/11543646/db5c68c4-990b-11e5-861d-eccb19176ae6.png)

**Comment by kreynolds** [comment]
As a possible addendum, the error message here also doesn't show the same error message that appears in the sidekiq logs. For instance, in this interface it just says `Sidekiq::Limiter::OverLimit` but in the logs it says:
```
2015-12-02T21:02:11.004Z 42545 TID-ovyzam25c CompetitionWorker JID-9b1046c35bd2bc7ad1d59aa7 BID-Eohqi6dsTG9YZw INFO: Limit 'user-1' over rate limit, rescheduling for later
```

Would be nice to have that visibility in the interface as well.

**Comment by mperham** [comment]
Should be easy enough to implement: will make the error message a little more helpful.

**Comment by mperham** [comment]
The error message is now the name of the limiter, which should tell which rate limit was violated.

**Comment by mperham** [comment]
I'm still unsure how and if I want to adjust the link.  Special casing the error class seems like a nasty hack.

**Comment by kreynolds** [comment]
OverLimit is already a special enterprise case in a lot of ways. I think its fine to extend that here for now until something better occurs to you. Whats there now is broken .. if you don't want to special case it, remove the link imo.

**Comment by mperham** [comment]
Unfortunately there's a case where OverLimit is scheduled and another case where it is retried and I can't tell which without access to the job payload itself.  I think this will have to remain a known issue for now.  I think continuing to link to retries is the right thing to do as that case is the one that would typically require human intervention to debug the issue.
