### ISSUE TITLE
Within a batch, OverLimit exceptions count as failures, should create and use retries?

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2689]

**Comment by mperham** [comment]
Nope, this semantic was changed in 0.7.6 and no plans to revert.  Many people track their jobs via JID and we don't want to create additional jobs with different JIDs that represent the same work.

https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md#076

**Comment by kreynolds** [comment]
No, thats the whole point, and I think I was the impetus for that change. I don't want anything about the job itself to change, what I want is for how the stat is counted in the batch to change. To the job, that is a retry with the same jid and not a failure. To the overall sidekiq stat, thats not a failure. To the batch, its counted as a failure, which is a violation of expectation.

**Comment by mperham** [comment]
I'm confused.  A batch failure is a retry.

**Comment by kreynolds** [comment]
![screen shot 2015-12-03 at 4 07 03 pm](https://cloud.githubusercontent.com/assets/324744/11574150/e75d0a8a-99d7-11e5-8e24-ce8111c1ccfb.png)

In this status screenshot, there are 6 jobs in the batch, only 2 of which run at once using the concurrency limiter. When the batch starts, two jobs run, and 4 jobs are rescheduled because of OverLimit. At that point, the `pending` column changes to 4 and the `failed` column changes to 4. When job number 3 runs, the `pending` column changes to 3 and the `failed` column changes to 3 .. its confusing that just above in the summary, the `failed` job count never changes, let alone goes back down. I understand *why* its doing what its doing, but the juxtaposition of the sidekiq dashboard above with the identically-named-but-differently-behaving counts below is confusing. I think in the specific case of OverLimit (which you want to preserve as a special case), if its rescheduled it should just stay `pending`, and not count as `failed`. A job rescheduled due to OverLimit in every other context is not a failure.

**Comment by mperham** [comment]
It might be a bit confusing but this is correct and how it is designed to work.  You have 1 job still pending (pending means that they haven't succeeded yet).  A batch job is a failure if it executed but did not succeed.  By that logic, an OverLimit reschedule is still a failure.

**Comment by kreynolds** [comment]
I know *why* it says what it says, I just think its confusing when the same words are used on the same screen and mean something completely different. Entirely possible nobody else cares.
