### ISSUE TITLE
perform_in fails when passed a string for the interval

### ISSUE THREAD

**Issue by selenetelenav** [mperham/sidekiq#2691]
```
 :001 > SomeJob.perform_in '60'
TypeError: can't convert String into an exact number
	from /Users/selenet/.rvm/gems/ruby-2.2.2@ventura/gems/activesupport-4.1.9/lib/active_support/core_ext/time/calculations.rb:208:in `+'
	from /Users/selenet/.rvm/gems/ruby-2.2.2@ventura/gems/activesupport-4.1.9/lib/active_support/core_ext/time/calculations.rb:208:in `plus_with_duration'
	from /Users/selenet/.rvm/gems/ruby-2.2.2@ventura/gems/sidekiq-4.0.1/lib/sidekiq/worker.rb:60:in `perform_in'
	from (irb):1
```

This was introduced in https://github.com/mperham/sidekiq/pull/2198 .

**Comment by mperham** [comment]
What's the bug?  This seems like correct behavior.

**Comment by selenetelenav** [comment]
Prior to #2198, passing a numeric string to .perform_in worked. e.g. `perform_in('60')` would schedule the job for 60 seconds in the future.

**Comment by mperham** [comment]
The intent has always been that the first argument must be a timestamp, numeric or something that acts numeric (like an AS time interval).  Sorry if that intent was under-documented but no plans to support a String argument.
