### ISSUE TITLE
Unexpected "You are using Redis v2.6.7..." error in version 4

### ISSUE THREAD

**Issue by volkanunsal** [mperham/sidekiq#2697]
I'm using Redis 3.0.5. I don't even have Redis 2.6.7 installed. Why would Sidekiq get this wrong?

**Comment by jonhyman** [comment]
stack trace?

**Comment by mperham** [comment]
Sidekiq doesn't make up version numbers.  You are getting that error because you are connecting to Redis 2.6.7 somehow.

**Comment by volkanunsal** [comment]
Sorry for the late response. 

> Sidekiq doesn't make up version numbers. 

Perhaps I'm dreaming it then? Here is the stack trace.

https://gist.github.com/volkanunsal/9d60f71190092bae1265

**Comment by volkanunsal** [comment]
Btw, downgrading to 3.5.3 gets rid of this error.

**Comment by mperham** [comment]
Well, yeah, because it doesn't require Redis 2.8.  Are you setting REDIS_URL?

**Comment by volkanunsal** [comment]
Not to my knowledge, no.

On Mon, Dec 7, 2015 at 4:16 PM, Mike Perham <notifications@github.com>
wrote:

> Well, yeah, because it doesn't require Redis 2.8. Are you setting
> REDIS_URL?
>
> > On Dec 7, 2015, at 13:11, Volkan Unsal <notifications@github.com> wrote:
> >
> > Btw, downgrading to 3.5.3 gets rid of this error.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mperham/sidekiq/issues/2697#issuecomment-162666031>.
>



-- 
*Volkan Unsal*
*web and mobile development*
volkanunsal.com

**Comment by jonhyman** [comment]
@volkanunsal on 3.5.3, can you open up a rails console and type

```ruby
Sidekiq.redis {|r| r.info}
Sidekiq.redis {|r| r.client.host}
Sidekiq.redis {|r| r.client.port}
```

This should tell you which host/port and version you're connecting to.

**Comment by volkanunsal** [comment]
I think there was a phantom Redis process. Restarting the computer fixed it for me. Thanks for the help!
