### ISSUE TITLE
[Pro] Check if acknowledging worked as expected

### ISSUE THREAD

**Issue by stephankaag** [mperham/sidekiq#2699]
In our setup we adjust the job msg in `retrieve_work` slightly in order to track some things.

This caused `acknowledge` to no longer be able to `lrem` the message. This stayed unnoticed for a while resulting in jobs not being removed from the internal queue.
In my opinion `acknowledge` should check if the result is 1 (meaning 1 job removed) and log a warning otherwise.

What do you think?

**Comment by mperham** [comment]
You need to use middleware to adjust the job contents.  I can't support monkeypatches.

**Comment by mperham** [comment]
I understand your suggestion now, sounds reasonable.  Will go into the next Pro 3 release.
