### ISSUE TITLE
Unclear if YML config & -q CLI option work together

### ISSUE THREAD

**Issue by mhuggins** [mperham/sidekiq#2702]
Apologies if this is a dumb question.  I read through [this wiki article](https://github.com/mperham/sidekiq/wiki/Advanced-Options), and it's unclear to me if I can use both a `sidekiq.yml` config file in addition to `-q` options to specify queues.

My goal is to have a single config file to manage, while being able to have different processes manage different queues.  Would that work?  What takes precedence?

**Comment by mperham** [comment]
Yes, just don't have a queues section in your yml file.  CLI takes precedence.
