### ISSUE TITLE
Rate limited locks can lose their expiration

### ISSUE THREAD

**Issue by DanThiffault** [mperham/sidekiq#2704]
We're using a window limiter setup like this:

```ruby
    Sidekiq::Limiter.window("product-api-limit", 2, :second, wait_timeout: 2)
````

We noticed after a hammering away with 12 threads that jobs were just cycling between their queue and the Scheduled set. Looking into redis the bucket assigned to this limiter had no expiration and had a value around 3 million. As soon as I deleted that key jobs started flowing again with the expected rate limiting.

Looking into it a little further, I think there may be a race condition in lib/sidekiq-ent/limiter/window.rb:62--65. Reading the redis docs I'm not sure, but I think it may be possible for the variable to expire after the set with nx check but before the increment. The multi explicitly handles serializing against other clients, but I can't find any mention about how it handles expiration within a multi block. Otherwise I believe an error in the set command would cause the same behavior (although I don't see how that could be happening).

Environment info:
 * ruby 2.2.2p95
 * sidekiq (3.5.0)
 * sidekiq-ent (0.7.3)
 * sidekiq-pro (2.0.8)
 * redis 2.8.6

and our sidekiq initializer
```ruby
require 'sidekiq/logging/json'

redis = {
  url: Rails.configuration.sidekiq_redis_url,
  namespace: Rails.configuration.sidekiq_redis_namespace
}

Sidekiq.configure_server do |config|
  config.redis = redis
end

Sidekiq.configure_client do |config|
  config.redis = redis
end

unless Rails.env.test?
  Sidekiq::Client.reliable_push!
  Sidekiq::Enterprise.unique!
end

Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!

  if Rails.configuration.run_perodic_jobs?
    config.periodic do |mgr|
      # see any crontab reference for the first argument
      # e.g. http://www.adminschoice.com/crontab-quick-reference
      # 6 scheduled jobs omitted one of which uses the limiter daily
    end
  end

end

Sidekiq.logger.formatter = Sidekiq::Logging::Json::Logger.new
```

**Comment by mperham** [comment]
Yes, I've gotten reports of this but hadn't been able to figure out the issue.  Complete description here: http://www.bennadel.com/blog/2785-volatile-keys-can-expire-mid-multi-transaction-in-redis-jedis.htm

**Comment by mperham** [comment]
I believe I know how to work around this issue; expect a new release today.

**Comment by mperham** [comment]
0.7.9 and 1.0.2 are now available with this fix.

**Comment by DanThiffault** [comment]
Thank you! We'll roll that out and let you know if there are any issues in the future
