### ISSUE TITLE
Human readable "created_at" scheduled queue

### ISSUE THREAD

**Issue by shible2014** [mperham/sidekiq#2705]
Hi,
When I go to Schedule jobs, I saw 
{"created_at"=>1449686863.6166751}
It is not human readable. How to change it so that it shows data&time?

**Comment by mikegee** [comment]
You see `{"created_at"=>1449686863.6166751}` under the column labeled "When"?

I see links to the jobs with text like "1 minute from now".

**Comment by mperham** [comment]
Will be in a future 4.x release.
