### ISSUE TITLE
is there performance problem if i change the inteval shorter

### ISSUE THREAD

**Issue by lanjingyu** [mperham/sidekiq#2708]
config.average_scheduled_poll_interval = 1
config.average_scheduled_poll_interval = 3

if i change the average_scheduled_poll_interval shorter 1 second or 3 second, is there any performance problem?

because i want my job more precise, because my project is about stock market , the stock price every second is important, but i worried about the performance.

**Comment by mperham** [comment]
Depends on how many Sidekiq processes you have and the size of your retry and scheduled queues.  If few and small, then not really.

If money is at stake, perhaps hacking Sidekiq to work is not a good idea.

**Comment by lanjingyu** [comment]
Only a socket heartbeat job needs 3 second, if not , the server close the socket.
Other jobs do not need this condition.
So, I think cann't change the average_scheduled_poll_interval for just one job.
