### ISSUE TITLE
/queues/:name not listing jobs on Web UI

### ISSUE THREAD

**Issue by pramodshinde** [mperham/sidekiq#2710]
I have long running workers, which typically takes 10-20 minutes to complete. I want confirm following 
When I start my worker 
```ruby
jid = EmailValidationWorker.perform_async(890) # 890 is record id
``` 
Immediately after starting worker I go to Web UI I can see my job is running under [/sidekiq/busy](https://drive.google.com/file/d/0B7cGHeLBP3EKdEJWakFlekM5c1E/view?usp=sharing) tab
But when I click on queue name, it does not list busy/running jobs under [/sidekiq/queues/contact-email-validation](https://drive.google.com/file/d/0B7cGHeLBP3EKNzZnSFlRSDRYTk0/view?usp=sharing) (queue_name: contact-email-validation) 

I also verified using API's like
```ruby
workers = Sidekiq::Workers.new
workers.size # => 1
workers.first
=> [
  "Pramod-ThinkPad:18372:92c0ab55341f",
  "80ta8",
   {
     "queue"=>"contact-email-validation",
     "payload"=>
      {
        "class"=>"EmailValidationWorker",
        "args"=>[890],
       "retry"=>false,
       "queue"=>"contact-email-validation",
       "backtrace"=>true,
       "expires_in"=>86400,
       "jid"=>"0140dc7dc4dc852c23830240",
       "created_at"=>1449946453.3465931,
       "enqueued_at"=>1449946453.3469982},
       "run_at"=>1449946453
    }
]
```
And I know `Sidekiq::Workers.new` gives live data but I tried following immediately (while job was running)
```ruby
@queue = Sidekiq::Queue.new("contact-email-validation")
@queue.size #=>0
```
I drilled down to code see why UI is not listing jobs for particular queue found following 
```ruby
@queue = Sidekiq::Queue.new(@name)
(@current_page, @total_size, @messages) = page("queue:#{@name}", params[:page], @count)
# page("queue:#{@name}", params[:page], @count) 
# always returning [1, 0, []] after checking key type which is 'none' for this case.
```
I am using 
- sidekiq (3.5.1)
- ruby-2.1.2 & Rails 4.1.6
- Ubuntu 

Is this expected behavior or this is an issue?

**Comment by mperham** [comment]
Expected behavior. A working job is not enqueued.

**Comment by pramodshinde** [comment]
If it is an expected behavior, I have following thoughts 
+ If /queues/:name is only meant for listing enqueued jobs (like to confirm this) then [CurrentMessagesInQueue](https://github.com/mperham/sidekiq/blob/master/web/locales/en.yml#L25) should be changed to `Current enqueued jobs in <span class='title'>%{queue}</span>`
+ Also If there are no jobs to list on this page, Can we have alert message like `No enqeued jobs were found` or `No  jobs were found` to be consistent with other tabs ?

Let me know your thoughts, I would be happy to make these changes.
