### ISSUE TITLE
Human-friendly names for ActionMailer jobs

### ISSUE THREAD

**Issue by dreyks** [mperham/sidekiq#2712]
When using Sidekiq with ActiveJob and calling `UserMailer.welcome_email(@user).deliver_later` the WebUI reports 
`Job`: `ActionMailer::DeliveryJob`
`Arguments`: `'UserMailer', 'welcome_email', 'deliver_now', 'actual args'`

Would it be even more human-friendly if it was something like this?
`Job`: `UserMailer#welcome_email`
`Arguments`: `'actual args'`

**Comment by mperham** [comment]
PR welcome.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L279
