### ISSUE TITLE
Questions about monitoring sidekiq workers

### ISSUE THREAD

**Issue by fields** [mperham/sidekiq#2713]
We've encountered a number of situations where the sidekiq workers are still running (linux processes present), but for some reason they're not processing any jobs. In some cases, there has been a failed deploy and the workers were quieted at the beginning of the deploy and just left in the quiet state and never restarted. In other cases this has not obviously happened but the sidekiq workers are still not processing jobs. In all of these cases, restarting the worker causes the queue processing to be resumed.

I'd like to monitor these states with monit and restart the sidekiq process automatically if needed, but it's not clear how to get this status from sidekiq. Is there a state I can query that will tell me if sidekiq is actively processing jobs?

**Comment by mperham** [comment]
The ps title adds "stopping" when quieted.  You can look for that.
