### ISSUE TITLE
Concurrency over 25 uses 100% CPU all the time without any workers

### ISSUE THREAD

**Issue by Silex** [mperham/sidekiq#2718]
Hello,

With sidekiq version 4.0.1, whenever I use `config/sidekiq.yml` with the following contents:

``` yaml
---
:concurrency: 26
```

Then sidekiq uses 100% cpu all the time. Dropping to a number under or equal to 25 uses the expected 0%.

**Comment by mikegee** [comment]
Send `TTIN` at the high cpu using process to see what its up to.

https://github.com/mperham/sidekiq/wiki/Signals

**Comment by mperham** [comment]
Sounds like you might not have enough Redis connections.  Are you limiting the pool size?

**Comment by Silex** [comment]
Hum, after some tests the problem happens because of the gem `sidekiq-limit_fetch`. You can ignore this, thanks for the hints!
