### ISSUE TITLE
Historical queue metrics and monitoring

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2719]
Sidekiq Pro has statsd integration to send individual job execution metrics but nothing enabling a big picture overview of Redis and the queues.  Create a separate redis and queue health monitoring feature.  Metrics collection will require Enterprise since it will depend on the leader election feature.

This will solve #1626.

**Comment by davydovanton** [comment]
interesting feature! if I can help I would be glad to help you :blush:

**Comment by mperham** [comment]
Unfortunately I can't give Enterprise source access unless you're a customer.  You're plenty helpful with Sidekiq anyways so thank you for the offer! :+1:

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics

**Comment by mperham** [comment]
Will be available in Enterprise 1.1.0 coming later this month.
