### ISSUE TITLE
always record not found randomly

### ISSUE THREAD

**Issue by karrra** [mperham/sidekiq#2720]
rails 4.2.0
sidekiq 3.5.1

I have already used after_commit and perform_in, but everyday my server sidekiq log display record not found! I'm sure those records all exist, anyone can help me?

**Comment by davydovanton** [comment]
@karrra hello!
Try to use `perform_in` method with 1 second delay like as:
```
MyWorker.perform_in(1.seconds, 1, 2, 3)
```

**Comment by mperham** [comment]
As this is not a Sidekiq bug, you'd be better off asking for help on StackOverflow.
