### ISSUE TITLE
NameError - uninitialize constant

### ISSUE THREAD

**Issue by silvercrow27** [mperham/sidekiq#2721]
I have this code in my worker
```
class MailSender
  include Sidekiq::Worker
  def perform(post)
    @post = Post.find post
    @post.subject.student_ids.each do |r|
      UserMailer.send_notification(post, r.email)
    end 
  end
end
```
and on my controller 
```
MailSender.perform_async(@post.id)
```
but it gives me an error shown on the image below. I have other workers that I'm using but they are working perfectly.

Some info. 
Ruby 2.2.2p95
Rails 4.1.7
Sidekiq 4.0.1
OS Ubuntu 15.10

![uninitializeconstant](https://cloud.githubusercontent.com/assets/6946531/11836132/82898f3e-a413-11e5-9e4c-1831dc99f4e9.png)

**Comment by davydovanton** [comment]
@silvercrow27 hello!
Could you create gist with full stacktrace and show me this?

**Comment by silvercrow27** [comment]
https://gist.github.com/silvercrow27/6adda57218dd07e79265

that't the link of the gist.

**Comment by mperham** [comment]
Looks like your controller can't find the MailSender class.  Make sure it is in app/workers/mail_sender.rb.

**Comment by silvercrow27** [comment]
that works now.. but why is that the other workers are working even if they have the same filename and class name?
