### ISSUE TITLE
Jobs Retrying even with retry set to 0 (v3.5.3)

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#2723]
We're having a regularly failing job that's going to the Retry queue even though I have the following options set

```
    class KeyholeParser
      include Sidekiq::Worker
      sidekiq_options :retry => 0, :queue => :workers
```

This job is enqueued every 5 minutes by a cronjob, and since I only added :retry=>0 this morning to the options I thought that was involved?
In any case I started enqueing the job manually with `Sidekiq::Client.push('class' => "Chirpify::Workers::KeyholeProcessor", 'args' => [], 'queue' => 'workers' )` and it still has `retry => true` in the arguments when the worker runs.

What am I doing wrong?

Edit: Using sidekiq 3.5.3

**Comment by bobber205** [comment]
Adding that currently I am only seeing this weird behavior in a named queued, have yet to see this in the `default` queue.

**Comment by bobber205** [comment]
More details! :)

When it runs, fails, and retries. Note that retry is set to `true`. (took out args array for brevity's sake)
```
{"class"=>"Workers::KeyholeParser","queue"=>"workers", "retry"=>true, "jid"=>"b451d30e248b54481d98edde", "created_at"=>1450298411.2172089, "enqueued_at"=>1450298411.217243, "error_message"=>"undefined method `[]' for nil:NilClass", "error_class"=>"NoMethodError", "failed_at"=>1450298411.3506722, "retry_count"=>0}
```

This job was run from a manual enqueuing like so (in irb)

```
Sidekiq::Client.new.push('class' => "Workers::KeyholeParser", 'args' => [], 'queue' => 'workers' )
```

Options

```
Workers::KeyholeParser.sidekiq_options
=> {"retry"=>0, "queue"=>:workers}
```

Is this a sidekiq bug?

**Comment by mperham** [comment]
Your problem is due to passing the class as a String rather than as a Class.  If you pass a String, Sidekiq uses the option defaults; it does not constantize and pull the options.

`Sidekiq::Client.new.push('class' => "Workers::KeyholeParser",`

**Comment by bobber205** [comment]
Is there a way to enqueue to a class with its defined options if I don't have the constant available?

**Comment by bobber205** [comment]
Can I pass options to the `push` method?

**Comment by mperham** [comment]
Read the rdoc.  https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L63

**Comment by pnomolos** [comment]
@mperham Can this be re-opened?  I am also seeing this issue, but I am not manually enqueing:

```ruby
class QuoteFilesWorker
  include Sidekiq::Worker
  sidekiq_options retry: 0
```

Being enqueued via:

```ruby
QuoteFilesWorker.perform_async(quote.id)
```

**Comment by pnomolos** [comment]
@mperham Actually, scratch that ... I think this is because I killed my workers partway through and set the retry options to zero - looks like some jobs were re-enqueued with their retry count and that is still respected?

**Comment by UTKARS** [comment]
> Your problem is due to passing the class as a String rather than as a Class. If you pass a String, Sidekiq uses the option defaults; it does not constantize and pull the options.
> 
> `Sidekiq::Client.new.push('class' => "Workers::KeyholeParser",`

@mperham if we see https://github.com/sidekiq/sidekiq/blob/b7236f814ccb61d3b1e6fc5251ed3d3ac7428eb3/lib/sidekiq/client.rb#L114
it says that we should pass class name as string 

please suggest for push_bulk method also weather we should pass class name as string or as class itself
