### ISSUE TITLE
Ghost Processes

### ISSUE THREAD

**Issue by duboff** [mperham/sidekiq#2725]
This has been happening for several hours now:

![screenshot 2015-12-17 13 18 33](https://cloud.githubusercontent.com/assets/5929988/11870569/b8c650fc-a4c0-11e5-8d1d-35c55b5811b3.png)

When I run *ps -ef | grep sidekiq*, I see no processes with busy status. Yet when I connect through API I again see processes with jobs stuck in busy. Clearing them through API (via the stop command) does not help, same with web UI.

From my intense googling it looks like some segfault but I might be wrong. I tried restarting Sidekiq / Redis and my whole container. Did not help.

I am on Sidekiq v4.0.1 and Redis 3.0.4.

Appreciate your help

**Comment by mperham** [comment]
If it's been happening for a few hours now, what happened a few hours ago?

**Comment by duboff** [comment]
yes, pushed new version of the app, everything seemed fine. Then ran a big job, and it got stuck.

**Comment by mperham** [comment]
Any more info?

**Comment by duboff** [comment]
@mperham, I was not able to get any better idea of the cause of the problem or solve it. Had to rebuild the app completely.
