### ISSUE TITLE
Sidekiq 4.0.1 seems to have a large delay when doing perform_later within a job.

### ISSUE THREAD

**Issue by drogar** [mperham/sidekiq#2726]
This behavior does not happen in 3.5.2: When running a job which then tries to enqueue other jobs, each enqueue has a significant delay (around 40 seconds for us).

I created a test case that looks like this:
```
class RunnerJob < ActiveJob::Base
  queue_as :low

  def perform(count)
    (1..count).each { DoItJob.perform_later(rand(10)) }
  end
end
```
and

```
class DoItJob < ActiveJob::Base
  queue_as :low

  def perform(amount)
    sleep(amount)
  end
end
```

In the console, if I run `RunnerJob.perform_now(5)`, the 5 `DoITJob`s are queued immediately. If I do `RunnerJob.perform_later(5)`, each job is queued approximately 40 seconds apart. The `RunnerJob` terminates only after queueing the last run of `DoItJob`.

I also tested this with pure SideKiq and observed the same behavior.  
I then downgraded to 3.5.2 and the `perform_later` run queued all the sub jobs with no delays.

Our sidekiq config file:
```
redis_conn = proc {
  $redis_sidekiq
}

Sidekiq.configure_client do |config|
  if Rails.env.test?
    config.redis = { driver: Redis::Connection::Memory }
    Sidekiq::Logging.logger = Rails.logger
  else
    config.redis = ConnectionPool.new(size: 100, &redis_conn)
  end
end

Sidekiq.configure_server do |config|
  ActiveRecord::Base.configurations[Rails.env]['pool'] = 50
  ActiveRecord::Base.configurations[Rails.env.test? ? 'test_warehouse' : 'warehouse']['pool'] = 50
  Warehouse::Connector.establish_connection
  ActiveRecord::Base.establish_connection
  config.redis = ConnectionPool.new(size: 100, &redis_conn)
end
```
Our redis config:
```
config = {url: AppConfig.redis_url, timeout: AppConfig.redis_timeout}

redis         = Redis.new(config)
redis_sidekiq = Redis.new(config)

if AppConfig.redis_namespace.blank?
  $redis = redis
else
  $redis = Redis::Namespace.new(AppConfig.redis_namespace,
                                redis: redis)
end

if AppConfig.sidekiq_namespace.blank?
  $redis_sidekiq = redis_sidekiq
else
  $redis_sidekiq = Redis::Namespace.new(AppConfig.sidekiq_namespace,
                                redis: redis_sidekiq)
end
```

**Comment by mperham** [comment]
You've hacked the config to give the Sidekiq one global Redis connection. I'm honestly shocked that it works at all.

**Comment by drogar** [comment]
OK - I'll see if changing that makes a difference.

**Comment by drogar** [comment]
Thanks tons @mperham ! Fixing our config made it work correctly.
