### ISSUE TITLE
Request Store vs Sidekiq 4

### ISSUE THREAD

**Issue by albertodega** [mperham/sidekiq#2727]
Hi!
I've been using sidekiq for a few years.
My application uses request_store gem to set per thread(request) variables used by activerecord to filter some datas in activerecord.
In the last 6 months we have used this gem also in sidekiq 3. at the very beginning of the worker a variable in request_store is set to what is needed, and when the worker finished his work the variable is emptied out. with this configuration i've never had any problem with sidekiq, having the scopes inside actirerecord correctly selecting the subsets selected.
after the upgrade to sidekiq 4, some strange behaviors began in my worker processes: i actually don't understand if some of the workers are now sharing the same variable(which is set something like Thread.current[:foo] = bar) and with the new un-celluoloid-ed sidekiq 4 or if there is something wrong in the variable setting part of the request_store gem.
I've also filed up an issue on the request_store project, but first i think i need to actually understand how threads are returned to the main  process and if the variables there setted up are cleaned or reshared within the next process running.
thank you in advance for your time, if you need anything else don't hesitate to ask!
alberto

**Comment by mperham** [comment]
I don't know why it would break in Sidekiq 4.  I haven't heard of threading problems from anyone else, the upgrade feedback has been almost entirely positive.

You could build a client/server middleware pair which saves any store values into the job payload on the client-side and then restores those values into the store on the server-side.  Easy.

**Comment by albertodega** [comment]
unfortunately i don't think i can do as suggested:
the application mostly works as follow:
at the very beginning of the worker, there is a call to a method which sets the environment variable for the current job;
```ruby
Subsystem.set 1
```
it runs something like this:
```ruby
subsystem = Subsystem.unscoped.find(subsystem)
RequestStore.store[:subsystem] = subsystem
RequestStore.store[:subsystem_ids] = subsystem.present? ? subsystem.id : Subsystem.unscoped.pluck(:id)
```
then the whole application models have something like this as a default scope:
```ruby
default_scope {where( id: Subsystem.get_current_system_ids )}
```

in that way i can scope every model in the application for the selected subsystem.
this system works greatly in sidekiq 3, but it behaves randomly in sidekiq 4. i don't know if the variables are affected by concurrent runing processes or what, but i often obtain wrongly scoped results from the workers.

**Comment by mperham** [comment]
You're rolling your own multitenacy. Look into the apartment gem and how it works with Sidekiq.

**Comment by ryansch** [comment]
Agreed.  We use RequestStore and an approach very similar to apartment in our app.  Works great!
