### ISSUE TITLE
Rails + Sidekiq::Web + wildcard domain session = confliciting cookies

### ISSUE THREAD

**Issue by 1st8** [mperham/sidekiq#2730]
Hey Mike,

I've just tracked down a weird problem resulting in several cookies being created under different domains (with and without wildcard) and even different keys when using `Sidekiq::Web` (from 4.0.1) in a Rails (4.2.x) application using sessions on wildcard domains.
The solution might be useful someplace in the wiki, but I wasn't sure how to contribute there. Perhaps there is a better solution, which I overlooked. What do you think?

`config/initializers/session_store.rb` configures my session store like this:

```
Dummy::Application.config.session_store :cookie_store, domain: :all
```

**Solution:**
After reading the sinatra source, I found a way to configure the session store correctly. I added this to my `config/initializers/sidekiq.rb` (which is loaded after the session_store.rb from above)

```
Sidekiq::Web.set :sessions, domain: 'all'
```

I would have loved to reuse the options from session_store.rb (which are available under `Dummy::Application.config.session_options`), but Rack::Session::Cookie requires `:domain` to be a String, while the Rails pendant requires it to be the Symbol `:all` ...

**Comment by mperham** [comment]
:metal: Great detective work!

Good question, I'm not sure how best to document this.  The Web UI has turned into a quagmire, with lots of issues with people suggesting various hacks which make the Forbidden error go away for them.  This could be one more necessary step to get everything working reliably, especially in a wildcard setup.  I think the best solution is to link to this issue from the wiki so people can read the details themselves.  I'll do that now.

**Comment by mperham** [comment]
> If you have wildcard domains with your Rails app and want to access the Web UI from all of them, see issue #2730.

**Comment by 1st8** [comment]
Very cool, I am happy to help. Thanks!

**Comment by iangreenleaf** [comment]
Just a note on this: the problem is accurate, but I'm not sure why `domain: 'all'` worked for @1st8. I don't see anything in Sinatra or Rack source to suggest that "all" is a special value in those frameworks, and for me it didn't solve the issue. To get my install working I had to give it my actual cookie domain, like this:
```
Sidekiq::Web.set :sessions, domain: '.mydomain.com'
```

**Comment by blunckr** [comment]
I just ran into this too. I feel like it could go in the guide, because lots of people could run into it. I was unable to sign out of my app because of the conflicting cookies. Just a suggestion.

**Comment by chipmunkgeek** [comment]
OP's fix worked for me.  Great job!  Thanks!

Agree that it would be helpful for this to go into the guide.  It took awhile to figure out that sessions were having problems, which were due to CSRF problems, which turned out to be conflicting cookies, which led me to here.

**Comment by danmayer** [comment]
ran into this and `Sidekiq::Web.set :sessions, domain: 'all'` as recommend in this thread solved my issues as well.

**Comment by pbrumm** [comment]
the 'all' will work but only if you sign in from root domain.    if you sign in from subdomain then ".mydomain.com" is the correct approach.

**Comment by rgaufman** [comment]
When I run:

```
Sidekiq::Web.set :sessions, domain: 'all'
```

I get this warning:

```
WARNING: Sidekiq::Web.sessions= is no longer relevant and will be removed in Sidekiq 7.0. /usr/local/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/web.rb:75:in `set'
```

Any ideas?

**Comment by mperham** [comment]
This issue is no longer revelant to modern Sidekiq.

**Comment by mperham** [comment]
@rgaufman It sounds like you are trying to configure a cookiestore option. See here for setting cookiestore options:

https://github.com/mperham/sidekiq/wiki/Monitoring#standalone
