### ISSUE TITLE
issue with exec /bin/bash

### ISSUE THREAD

**Issue by pandugreycampus** [mperham/sidekiq#2733]
I used this approach to start sidekiq and i placed both sidekiq.conf and workers.conf. 
When i used  
sudo start sidekiq index=0
pandu@pandu:/etc/init$ sudo start sidekiq index=0
sidekiq (0) start/running, process 4113

But when i used
sudo status sidekiq index=0
pandu@pandu:/etc/init$ sudo status sidekiq index=0
status: Unknown instance: 0

and it does not performing any operation on jobs and i got logs like this
/bin/bash: line 15: exec: bundle: not found
/bin/bash: line 15: exec: bundle: not found
/bin/bash: line 15: exec: bundle: not found
/bin/bash: line 15: exec: bundle: not found

Then i tried in some other manner i changed the line 15 as 
exec /bin
then i got logs as below
/proc/self/fd/9: 4: exec: /bin: Permission denied
/proc/self/fd/9: 4: exec: /bin: Permission denied
/proc/self/fd/9: 4: exec: /bin: Permission denied
/proc/self/fd/9: 4: exec: /bin: Permission denied

Please help me.

**Comment by mikegee** [comment]
"`/bin/bash: line 15: exec: bundle: not found`" looks like bundler isn't installed or isn't in that process's `PATH`.
