### ISSUE TITLE
Website looks terrible on iPhone

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2735]
It's pretty bad. Not sure if it's just iPhone or all mobile. http://sidekiq.org

**Comment by seifertd** [comment]
Looks bad on an Android Nexus 5 as well

**Comment by davydovanton** [comment]
@mperham this issue about sidekiq.org site or web part of sidekiq?

**Comment by mperham** [comment]
Sidekiq.org

**Comment by davydovanton** [comment]
@mperham if you want I can create this responsive table
http://codepen.io/icutpeople/pen/pfHDj

This is look like normal for you?

**Comment by mperham** [comment]
:+1: That looks like a nice alternative.

**Comment by mperham** [comment]
@davydovanton Thank you so much for fixing this!  I feel pretty helpless trying to fix web styling problems, it's awesome to have better web people than me willing to help out.

**Comment by davydovanton** [comment]
@mperham I am always glad to help :blush:
