### ISSUE TITLE
Remove Celluloid reference from the wiki

### ISSUE THREAD

**Issue by seuros** [mperham/sidekiq#2736]
Here is the pages that need updating: 
https://github.com/mperham/sidekiq/wiki/Ent-Leader-Election
https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs

**Comment by mperham** [comment]
Note this code is still relevant for Enterprise 0.x, which is still being maintained for compatibility with Sidekiq 3.x.

**Comment by mperham** [comment]
Pages updated.
