### ISSUE TITLE
Forking support for sidekiq?

### ISSUE THREAD

**Issue by bbozo** [mperham/sidekiq#2738]
The puma team did a magnificent job with the forking + threading option for C ruby - it basically enables you (through tweaking) to achieve that every ruby process uses 1 CPU to the full.

Yes, the GIL disables you from evaluating 2 pieces of ruby code at the same time, but the IO operations do not have this constraint, so our Puma web server running 2 processes with 4 threads each achieves perfect cpu utilization with 8 parallel requests on 1 Heroku 1x worker.

At the moment, through a freak of change requests :D and a large memory footprint, we're running sidekiq on 1x Heroku workers with C ruby (2.0) with really good results - we enjoy full CPU utilization and the 1x worker has only 1 core anyway. IF only there's a way to spawn 2 sidekiq processes and be able to run the same thing on 2x ^_^

Did you maybe consider adding forking support to sidekiq and maybe even shelve resque in the long run?

**Comment by mperham** [comment]
#2677

**Comment by bbozo** [comment]
:+1:  :D <3
