### ISSUE TITLE
heroku worker autoscaling

### ISSUE THREAD

**Issue by acds** [mperham/sidekiq#274]
Hi

Given Heroku deployment scenarios, have you given any thought to integrating or including the ability to autoscale the sidekiq worker, as in fire it up and tear it down deepening on the concurrency load.

I see that that HireFire is available as open source or hosted on Heroku as a plugin and is currently designed to support Delayed Job and Resque.

I also saw this... http://verboselogging.com/2010/07/30/auto-scale-your-resque-workers-on-heroku

This might be a nice feature to at least be able to support, at least for activity that is not scheduled to perform significantly in the future.

When a request is queued, it perhaps can see if sidekiq is running and if not fire it up, and when sidekiq identifies that all requests have been processed shut the worker down. 

Just a thought...

Thanks!
-Simon

PS: I think I'm getting the hang of how to use sidekiq properly...and have changed some of my approach accordingly.

**Comment by gmac** [comment]
Eight years later... I was looking for a bit more governance around the quiet/shutdown process and wanted a reporting UI, so spun this foundation off into a newer plugin configuration: https://github.com/gmac/sidekiq-heroku-autoscale. Thanks for paving the way here, @JustinLove.
