### ISSUE TITLE
Disque support

### ISSUE THREAD

**Issue by sandstrom** [mperham/sidekiq#2746]
Disque RC1 is out. I realize it's early, but would be useful if Sidekiq would support it.

Supporting it early is also an opportunity for Sidekiq to get more users.

> Disque is a distributed, in memory, message broker. Its goal is to capture the essence of the "Redis as a jobs queue" use case and move it into an ad-hoc, self-contained, scalable, and fault tolerant design, still resembling Redis in terms of simplicity and performance.

More details:
https://github.com/antirez/disque
http://antirez.com/news/100

**Comment by mperham** [comment]
Pretty much already covered by this FAQ:

https://github.com/mperham/sidekiq/wiki/FAQ#wouldnt-it-be-awesome-if-sidekiq-supported-mongodb-postgresql-mysql-sqs--for-persistence

Disque doesn't support many of the job features that Sidekiq does: unique, periodic, expiring, batches, rate limiting, etc and can't be "bolted onto the side" of Disque.  Those features can be implemented with the flexible data structures that Redis provides.

**Comment by sandstrom** [comment]
I've seen that FAQ entry. That Disque is developed by the same person who built Redis, specifically to be a distributed job queue, doesn't change anything then?

**Comment by mperham** [comment]
I understand its lineage but I can't build Sidekiq on Disque anymore than I can build on top of beanstalkd.  High-level APIs mean I can only support the high-level functionality it exposes, which would be a gigantic step backwards.  I'm sure someone will port Sidekiq to Disque just as someone ported it to SQS, with all the pros and cons that entails.
