### ISSUE TITLE
Upgrading to Sidekiq 3.5.3

### ISSUE THREAD

**Issue by shakycode** [mperham/sidekiq#2756]
I'm working with a Rails 4.1.x app with Ruby 2.1.1, Sidetiq 0.6.3 and existing Sidekiq 3.3.4 trying to upgrade to 4 eventually but for now looking at the latest version of the 3 branch (3.5.3).

I updated my gemfile with the following line `gem 'sidekiq', '< 4'` and ran a `bundle update`.  Everything bundled fine but when I went to test sidekiq in developement `bundle exec sidekiq` I get the following stacktrace:

````
uninitialized constant Celluloid::SupervisionGroup
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidetiq-0.6.3/lib/sidetiq/supervisor.rb:2:in `<module:Sidetiq>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidetiq-0.6.3/lib/sidetiq/supervisor.rb:1:in `<top (required)>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidetiq-0.6.3/lib/sidetiq.rb:32:in `require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidetiq-0.6.3/lib/sidetiq.rb:32:in `<top (required)>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `each'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `block in require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `each'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.1/lib/bundler.rb:132:in `require'
/Users/jjelinek/code/streetcred/config/application.rb:18:in `<top (required)>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:241:in `require'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:241:in `boot_system'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:50:in `run'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/gems/sidekiq-3.5.3/bin/sidekiq:13:in `<top (required)>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/bin/sidekiq:23:in `load'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/bin/sidekiq:23:in `<main>'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/bin/ruby_executable_hooks:15:in `eval'
/Users/jjelinek/.rvm/gems/ruby-2.1.1@streetcred/bin/ruby_executable_hooks:15:in `<main>'
````

I'm assuming this is some sort of problem with sidetiq and celluloid conflicting with sidekiq 3.5.3.  based on this issue [sidetiq #140](https://github.com/tobiassvn/sidetiq/issues/140).  This was supposedly fixed but I'm still having the issue.

I totally realize this is probably not the best place to post the issue and it appears sidetiq is the problem, but I was going to ask if there's a different gem I can use similar to sidetiq to schedule recurring job.

**Comment by mperham** [comment]
You're correct, sidetiq is the root cause.  Sidekiq Enterprise offers [periodic job](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs) functionality.

**Comment by shakycode** [comment]
@mperham Thanks Mike.  Sorry for opening this issue, just figured I'd check.  Looks like we need enterprise.  I have some questions so I'll ping you on Twitter. :+1:
