### ISSUE TITLE
What does the "Failed" count mean?

### ISSUE THREAD

**Issue by indirect** [mperham/sidekiq#2760]
After re-reading all of the docs around error handling twice, I still can't figure out what "Failed" means. The docs say: 

> Sidekiq will retry failures with an exponential backoff […] The Sidekiq Web UI has a "Retries" and "Dead" tab which lists failed jobs

It seems that my "Failed" count is increasing, but I do not see any jobs in the "Retries" or "Dead" tabs. What does "failed jobs" mean (is it just "count of times a job threw an exception"?), and how do those "failed jobs" relate to the "Failure" count on the web UI?

**Comment by mperham** [comment]
Good question - this has been a source of confusion for new users.

* **Retry** - a 'retry' is a job which has failed and will be retried sometime in the future.  The Retries tab shows a list of those jobs which will be executed at some point in the future, listed in chronological order.
* **Dead** - a 'dead' job is one which will no longer be retried but is saved by Sidekiq so it can be manually retried at some point in the near future.  The Dead tab lists jobs in this state.
* **Failed** - is a counter of the number of times any job was executed by Sidekiq and raised an error.

The `retry` property can be set on a worker or specific job to disable retries completely (job goes straight to Dead) or disable death (failed job is simply discarded).  If your Failed count is increasing but you don't see anything in the Retry or Dead tabs, it's likely you've disabled one or both of those:

```ruby
class SomeWorker
  # will be completely ephemeral, not in Retry or Dead
  sidekiq_options retry: false
```

**Comment by indirect** [comment]
Awesome, thanks for the explanation. My confusion turns out to have been exacerbated by the `sidekiq-failures` gem, which logs failures/exceptions into a "Failed" tab in the web UI—it looks like those jobs were immediately retrying and succeeding, but still creating entries in the "Failed" tab as well as incrementing the "Failed" count.

**Comment by mperham** [comment]
Yes, I don't see why anyone uses the sidekiq-failures gem.  AFAIK it acts like the Dead tab so maybe it was useful pre-3.0?

**Comment by codeanpeace** [comment]
@mperham Your elaboration was very helpful!

If I'm understanding correctly, if there are Failed jobs but no Dead jobs, that would mean the jobs successfully retried, right?

By the way, I think it'd be beneficial to add your explanation to the wiki - perhaps under either Monitoring and/or API.

**Comment by mperham** [comment]
Yes, or the Dead jobs were removed or expired.  There's so many edge cases that documenting what the number means would take a few paragraphs.  I prefer the documentation to be more succinct and task-oriented than that.

**Comment by codeanpeace** [comment]
Ahh fair enough, perhaps a data flow diagram that outlines about the jobs workflow to help interpret the dashboard? Something to this effect:
![image](https://user-images.githubusercontent.com/2991389/29632389-ddedb250-8810-11e7-8574-b94601ef2d8d.png) *let me know if I misinterpreted anything here

Hmm, good to know. I see from the docs that you can manually clear Dead jobs via the API, but how would they expire? Thanks!

**Comment by mperham** [comment]
Dead jobs will expire after 6 months or the dead set grows to 10,000
entries.  Otherwise the dead set is effectively a memory leak in Redis.

Thanks for the diagram; it's complicated enough that it only raises more
questions.  Perhaps the topic needs its own wiki page, e.g. “Job
Lifecycle”.  You are welcome to create a first revision, I’d be happy to
collaborate on it.

**Comment by kenn** [comment]
I had the same exact confusion.

I think this is primarily a UI/UX issue - The "Failed" count stops being meaningful to most people unless you remember what it was before.

I have a few suggestions:

* Count "dead" rather than retries. It means historical tally of dead jobs.
* Count all failures per Job ID as +1. Possibly -1 when a retry succeeds. (Ideal, but keeping all failed Job IDs as a Redis Set-type (for uniqueness) might take up too much memory)
* Or just add a "reset (to zero)" button below the failed count. It signals that it is just an ephemeral number for your convenience.

In any case, counting retries as a total is too granular to be useful, and unintuitive.

What do you think?

**Comment by justinoue** [comment]
IMO 'failed' implies some finality. Obviously it's a small label so it's hard to put something more verbose like 'failed individual attempts that were retried' but maybe a different word or phrase would be more descriptive. 'Errors' seems more appropriate.

Maybe just a hover tooltip (even a simple html title attribute) with a brief explanation.

**Comment by swrobel** [comment]
@mperham I took a stab at the wiki page: https://github.com/mperham/sidekiq/wiki/Job-Lifecycle

@codeanpeace I hope you don't mind that I incorporated your diagram

**Comment by mperham** [comment]
That's a really nice page!  Make sure it is linked from the main wiki index page, ideally toward the top of the list since it is high-level info.

**Comment by 2k-joker** [comment]
> Good question - this has been a source of confusion for new users.
> 
> * **Retry** - a 'retry' is a job which has failed and will be retried sometime in the future.  The Retries tab shows a list of those jobs which will be executed at some point in the future, listed in chronological order.
> * **Dead** - a 'dead' job is one which will no longer be retried but is saved by Sidekiq so it can be manually retried at some point in the near future.  The Dead tab lists jobs in this state.
> * **Failed** - is a counter of the number of times any job was executed by Sidekiq and raised an error.  Since the default retry policy is 25, a single job can lead to Failed increasing by 25.
> 
> The `retry` property can be set on a worker or specific job to disable retries completely (job goes straight to Dead) or disable death (failed job is simply discarded). If your Failed count is increasing but you don't see anything in the Retry or Dead tabs, it's likely you've disabled one or both of those:
> 
> ```ruby
> class SomeWorker
>   # will be completely ephemeral, not in Retry or Dead
>   sidekiq_options retry: false
>   # will go immediately to the Dead tab upon first failure
>   sidekiq_options retry: 0
> ```

@mperham I have a question about this - What happens if `retry: 0` and the job crashes because it couldn't finish within the shutdown timeout, when sidekiq gets a `TERM` signal? I don't want my worker to retry at all, unless it gets interrupted and I'm not sure how to set that up

**Comment by mperham** [comment]
If a job is re-queued due to shutdown, that is not considered a failure/retry and won't increment the retry counter. The job will restart execution when Sidekiq restarts.

**Comment by 2k-joker** [comment]
Thanks!
