### ISSUE TITLE
We should be able to test enterprise workers in the same context as the server

### ISSUE THREAD

**Issue by relwell** [mperham/sidekiq#2768]
Using Sidekiq::Testing in RSpec with Sidekiq Enterprise, we've found that attempting to directly stub Sidekiq::Senate results in a NameError, since this module is not loaded until the server starts up.

It would be great to have some kind of test runner component that allows us to load a runtime that is as close to the Sidekiq server as possible so that we can more adequately test some of these worker behaviors.

**Comment by mperham** [comment]
If your code uses Sidekiq::Senate, it should `require 'sidekiq-ent/senate'`.

I do have a few test helper methods that I use for code which uses the leader feature.  I'll get that baked and documented in the next version.

```ruby
class Sidekiq::Senate
  def lead!
    @leader_until = Time.now.to_f + 100
  end
  def follow!
    @leader_until = 0
  end
end
```

**Comment by relwell** [comment]
Awesome, thanks. I did try to require it within the context of the test runner, and it didn't seem to work. We can work around it for now, though, if there's a long-term plan for test helpers.

**Comment by mperham** [comment]
Here's how I use them.

```ruby
# To test leader code path
Sidekiq::Senate.instance.lead!

# To test follower code path
Sidekiq::Senate.instance.follow!
```
