### ISSUE TITLE
Sidekiq process disappearing from ui

### ISSUE THREAD

**Issue by antonzaytsev** [mperham/sidekiq#2773]
Sidekiq process disappearing from ui, but process is still there. Worker not processing jobs. No new logs in logs files for worker, no even error in logs before it stopped. The only way to fix this is to kill process with `kill -9` and start worker again. We also use `god` to monitor workers, restart them on memory leaks.

At this moment we processing jobs with 15 workers, each has concurrency equals 6.
I don't know how to reproduce this even with our stack as it appears random.

We use Sidekiq Pro.

Please let me know what additional info you need.

__initializers/sidekiq.rb__
``` Ruby
Sidekiq.default_worker_options = {
  backtrace: true
}

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'], namespace: "retailers_sidekiq_#{Rails.env}" }
  # config.error_handlers << Proc.new { |ex, context| Airbrake.notify_or_ignore(ex, parameters: context) }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'], namespace: "retailers_sidekiq_#{Rails.env}" }
end

# Sidekiq Pro Reliability feature
Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.reliable_scheduler!
end
```
Ruby: 2.2.2
Rails: 4.2.4
Sidekiq: 4.0.1
OS: Ubuntu 14.04.3 LTS

**Comment by mperham** [comment]
Post the TTIN output. If it doesn't respond, follow the GDB instructions on the Troubleshooting wiki page.

**Comment by D-side** [comment]
This may not be a problem with Sidekiq itself. It may indicate a deadlock between the worker threads for whatever reason. That's what I had at least, sympthoms are the same.

**Comment by antonzaytsev** [comment]
@mperham sorry for delay in answer.
Can you still help with it https://gist.github.com/antonzaytsev/a38b0b9827dee25ce521 ?

**Comment by D-side** [comment]
@antonzaytsev ha! You seem to be experiencing the same thing that we were. Maybe something else also, so consider inspecting Ruby backtraces as described at the bottom of [this section](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes).

As for what I had... I'm suspicious about [line 1123 of your trace](https://gist.github.com/antonzaytsev/a38b0b9827dee25ce521#file-dgb_output-L1123) and cowboyd/therubyracer#270.

**Comment by mperham** [comment]
therubyracer is not safe to use and will lock up the Sidekiq process.  @D-side is correct, your GDB shows exactly that.

**Comment by antonzaytsev** [comment]
@D-side @mperham thanks for investigate it!
I use `therubyracer` for `V8`, I have code to eval js and manipulate variables.
Is there any thread-safe replacement for `therubyracer` ?

**Comment by mperham** [comment]
You have to create your own global lock for it. Discourse has one somewhere.

**Comment by antonzaytsev** [comment]
Thanks @mperham.
For now I use mutex.
``` ruby
cxt = V8::Context.new
semaphore = Mutex.new
  semaphore.synchronize do
    cxt.eval(js)
  end
end
```
