### ISSUE TITLE
Sidekiq 4 crashes on startup when redis server pool size comes from an env var

### ISSUE THREAD

**Issue by bbonamin** [mperham/sidekiq#2775]
Hello there!

First of all. Let me say that I LOVE Sidekiq. It's a very fine piece of engineering and it's helped us a lot. :heart: 

Now, after upgrading our production environment to the latest version, I found that our workers couldn't boot up. The logs pointed me to a `sidekiq.rb` initializer that we've been using for the past year. 

Basically, we fetch the server pool size from an environment variable, or fall back to a default value. This gives us flexibility in scaling without needing to re-deploy our code.

The following configuration was working fine until we updated to Sidekiq 4.0.2
```ruby
Sidekiq.configure_server do |config|
  server_pool_size = ENV['SIDEKIQ_SERVER_POOL_SIZE'] || 6
  config.redis = { size: server_pool_size, namespace: 'website' }
end
```

[Here](https://gist.github.com/bbonamin/ac7972b5f6467369d25a) is a log extract of the crash.

I've tracked the issue down to this commit and line https://github.com/mperham/sidekiq/commit/907828c5b9e35cde133400eccb7a4692665155b2#diff-b97259b5fc5f983778f9d492eaa87f9fR35

What seems to be going on is that `Sidekiq::RedisConnection.verify_sizing` doesn't like env vars as input in `Sidekiq.options[:concurrency] `. I assume this is because env vars are all strings.

I can change my configuration code to convert the env to an integer like this:
```ruby
Sidekiq.configure_server do |config|
  server_pool_size = ENV['SIDEKIQ_SERVER_POOL_SIZE'].to_i || 6
  config.redis = { size: server_pool_size, namespace: 'website' }
end
```

But since this seems to be a common pattern around the Internet, I would suggest changing what populates `Sidekiq.options` to convert values to integers when reading them from config files. I'm happy to look into providing a PR doing so if you think it's a good idea.

Thanks!

**Comment by mperham** [comment]
I don't think it's too much to ask that people pass an integer for size.  WDYT?

**Comment by bbonamin** [comment]
The issue is that variables that come from ENV are all strings, regardless of what is set. Unless the coercion is done manually, the Sidekiq initialization process crashes, and the error message that's raised is not very helpful, unless you pry the code open. (Maybe ArgumentError can be raised if type is not Integer?)

Since strings for size used to be accepted  (Although perhaps it was never an intended "feature"), it's kind of unexpected that it's stopped working

It's a matter of taste, but it's a simple fix from Sidekiq's end, and you might save an Issue or two being posted about this topic in the future :tongue:

**Comment by mperham** [comment]
If something worked before only due to a implementation detail and is obviously wrong (passing a string for an integer), I fall into the "let it break" camp.  I'm serious about backward compatibility with my APIs but not "bugward compatibility".

`(ENV['SIDEKIQ_SERVER_POOL_SIZE'] || 6).to_i`
