### ISSUE TITLE
Sidekiq, Capybara, Poltergeist, Phantom JS - memory quota exceeded errors

### ISSUE THREAD

**Issue by tomgallagher** [mperham/sidekiq#2776]
Hello

Some background: Rails app. Background jobs. I'm running Sidekiq with multiple theads, each one of them is using Capybara, Poltergeist and PhantomJS in order to test and take screenshots of different pages.

I'm hitting critical memory quota exceeded errors in my worker. It seems highly likely that I'm collecting multiple instances of PhantomJS on my worker, despite the jobs finishing as expected.

Are there any options I could enable in Sidekiq that would ensure that new instances of Phantom JS are killed once the Sidekiq worker has completed its job? It seems strange that instances remain open.

Any help would be massively appreciated.

Tom

**Comment by mperham** [comment]
This is a StackOverflow question.
