### ISSUE TITLE
How can i get that worker got USR1 signal

### ISSUE THREAD

**Issue by vnazarenko** [mperham/sidekiq#2778]
Hi, I've updated my service to siekiq 4, i have some long running jobs, and previously i used Sidekiq::Fetcher.done? method to check i task should be stopped, and restarted a bit later. But now i'm getting  uninitialized constant Sidekiq::Fetcher error. 
Please advise me, where can i check that sidekiq got USR1 signal, and task should be stopped?
I just have a long runngin tasks, and i should pause them gracefully

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Deployment#events
