### ISSUE TITLE
Runtime queue selection

### ISSUE THREAD

**Issue by sirwolfgang** [mperham/sidekiq#2779]
Is there a way to override the default queue for a worker at runtime?

I have a synchronization task that mostly will run at `low` priority, providing a level of guaranteed eventual consistency. However there are some events, like an update, that naturally require a higher priority synchronization. Ideally I would like to be able to specify this option when calling `#perform_async`.

Naturally it wouldn't be possible for this to safely be able to have this option in `#perform_async`'s `*args`, but could possibly be done with an ActiveRecord style chaining syntax. `Worker.queue(:high).perform_async`.

**Comment by mperham** [comment]
Sidekiq::Client.push https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L63

**Comment by alex88** [comment]
Or as said in another issue, `MyWorker.set(queue: 'somequeue').perform_async(...)`
