### ISSUE TITLE
Nested batch in inconsistent state

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#2781]
I have some really complex workflows with nested batches that generally work just fine, but this morning one of them appeared in an inconsistent state. A job X is in batch `TCnoEKr9bdhoGQ` which has a parent batch of `cp1lCzI62Qw3vQ`.

Status::Batch::New loads up `TCnoEKr9bdhoGQ` just fine but the parent `cp1lCzI62Qw3vQ` fails with `Sidekiq::Batch::NoSuchBatch: Couldn't find Batch cp1lCzI62Qw3vQ in redis`.

The data in redis looks like:

```
irb(main):027:0> r.keys '*cp1lCzI62Qw3vQ*'
=> ["b-cp1lCzI62Qw3vQ-notify", "b-cp1lCzI62Qw3vQ-success", "b-cp1lCzI62Qw3vQ-complete"]
irb(main):028:0> r.keys '*TCnoEKr9bdhoGQ*'
=> ["b-TCnoEKr9bdhoGQ-jids", "b-TCnoEKr9bdhoGQ", "b-TCnoEKr9bdhoGQ-failinfo", "b-TCnoEKr9bdhoGQ-notify"]
```

Looking at the data for the parent batch, I see

```
irb(main):045:0> r.smembers 'b-cp1lCzI62Qw3vQ-complete'
=> ["TCnoEKr9bdhoGQ", "3TnO8p09oAE2-w", "8gyckfl3_L5ymA", "Wr9v-q3a2XjCoA"]
irb(main):046:0> r.smembers 'b-cp1lCzI62Qw3vQ-success'
=> ["3TnO8p09oAE2-w", "8gyckfl3_L5ymA", "Wr9v-q3a2XjCoA"]
```

Which correctly seem to indicate that the child batch has completed, but not succeeded. Everything looks completely normal, except that there is no key at all for the parent batch.

When I look at the key for the child batch, it looks like:
```
r.hgetall 'b-TCnoEKr9bdhoGQ'
=> {"created_at"=>"1452805942.9492667", "kids"=>"0", "total"=>"2", "callbacks"=>"{\"success\":[{\"Worker#finished\":{\"id\":2497306954}}]}", "parent"=>"cp1lCzI62Qw3vQ", "pending"=>"1", "description"=>""}
```

I have a process which tries to find the root batch of a child batch, and that appears to be what is actually failing here. Its possible things would continue on without issue if I didn't try to do that, but it seems odd that the parent batch cannot be found at all. Is this key not being there a normal aspect of operation?

**Comment by mperham** [comment]
Post the output of redis-cli info.  I wonder if you ran out of memory and Redis evicted some keys.

**Comment by kreynolds** [comment]
```
"expired_keys"=>"609", "evicted_keys"=>"0"
```

Its possible though unlikely

**Comment by kreynolds** [comment]
Any other theories or debug information I can provide? I've only seen this once but it is definitely weird.

**Comment by mperham** [comment]
I can't think of any reason why a batch would just disappear unless we're talking expiration or eviction.  How old are these batches?  Batches have a standard TTL of 30 days so they will expire soon if one or more jobs moves to the Dead queue after the default 21 days of retries.

**Comment by mperham** [comment]
I should probably consider raising the TTL to 90 days.  Batches are removed upon success so they don't take that much space in practice.

**Comment by kreynolds** [comment]
At the time it was a batch that started 4 days prior

**Comment by mperham** [comment]
Then expiration is out.  Do you use the unique or cron jobs features?  I believe that's the only Sidekiq data that expires, aside from batches.

**Comment by kreynolds** [comment]
I don't yet use cron or unique for this project

**Comment by mperham** [comment]
Ok, I don't have an explanation then.

**Comment by mperham** [comment]
The only time a batch is removed from Redis is the Batch::Status#delete method which is only called in the success callback handler and removes ALL batch keys in one transaction.  I don't see any way for the main batch key to be deleted on its own.

**Comment by kreynolds** [comment]
The answer is almost assuredly a no, but is there any possibility that something could trigger the success callback then cause the job to raise an exception that causes it to be retried, maybe even something I'm doing accidentally?

**Comment by mperham** [comment]
Not that I can think of off-hand.  The success job runs all success callbacks.  These can raise an error, so the success job will be retried like any other job.  Literally the last thing the success job does is delete the batch so all defined callbacks must run without error before that happens.

**Comment by kreynolds** [comment]
Well maybe I'll just pretend this never happened and wait for it to happen again. Closing for now.
