### ISSUE TITLE
sikeqik can't run (getaddrinfo)

### ISSUE THREAD

**Issue by pevargasg** [mperham/sidekiq#2782]
Hi, I'm trying to run sidekiq but I'm getting this error:

getaddrinfo: No address associated with hostname

this is what I have in my sidekiq file (configinitializers):
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://Policia9@host:6379'}
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://Policia9@host:6379'}
end

Seems I simply used the non-existent host given in the docu, of course I need to put my own host or ip in there,but I don't know where to find the file.

**Comment by mperham** [comment]
https://stackoverflow.com/questions/34879344/sidekiq-getaddrinfo-errorno-address
