### ISSUE TITLE
Sidekiq died due to the following error:NOAUTH Authentication required.

### ISSUE THREAD

**Issue by workhardcc** [mperham/sidekiq#2785]
2016-01-22T04:20:56.988Z 13625 TID-os7udzc74 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2016-01-22T04:20:56.988Z 13625 TID-os7udzc74 WARN: NOAUTH Authentication required.
2016-01-22T04:20:56.989Z 13625 TID-os7udzc74 WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:1320:in `block in smembers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.2.1/lib/redis.rb:1319:in `smembers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:392:in `call_with_namespace'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-namespace-1.5.1/lib/redis/namespace.rb:289:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/api.rb:557:in `block in cleanup'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/connection_pool-2.1.0/lib/connection_pool.rb:58:in `with'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq.rb:72:in `redis'

**Comment by mperham** [comment]
NOAUTH Authentication required.

**Comment by mperham** [comment]
https://stackoverflow.com/questions/34207523/rails-sidekiq-redis-noauth

**Comment by workhardcc** [comment]
hello, I deploy  a gitlab in my company and i found that error in log. I followed your suggestion but it doesn't work.

**Comment by workhardcc** [comment]
i fix it. Thank you!

**Comment by ulwanski** [comment]
@workhardcc how you fix it?
