### ISSUE TITLE
Separate #pause! and #unpause! features from ReliableFetch strategy

### ISSUE THREAD

**Issue by jcarlson** [mperham/sidekiq#2786]
Our deployment infrastructure poses constraints that make `ReliableFetch` somewhat unrealistic to implement. However, as a commercial customer, I would still like to be able to take advantage of the `#pause!` and `#unpause!` extensions to the `Queue` API afforded by the Pro license.

**Comment by mperham** [comment]
I've got this 90% done now and will go out in the next release.

**Comment by mperham** [comment]
3.0.4
