### ISSUE TITLE
perform_in - with custom queue

### ISSUE THREAD

**Issue by robly** [mperham/sidekiq#2790]
With 4.x we can no longer call .delay and pass in a custom queue if it is part of a Worker class. Instead we need to use perform_in, but how can we use a custom/dynamic queue?

We tried Sidekiq::Client.push but it does not contain an option for delay function. Just the custom queue. 

eg of what we tried: 
Sidekiq::Client.push({
  'class' => BulkEmailWorker,
  'queue' => 'bulk_mails',
  'args'  => [ 1, 2 ]
})

Thanks

**Comment by mperham** [comment]
Take a look at the Client API:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L148

**Comment by mperham** [comment]
You will also be able to do this in the next version:

```ruby
MyWorker.set(queue: 'foo').perform_async(1,2,3)
```

**Comment by robly** [comment]
Having the ability to use .set with .perform_in would be wonderful. We can't wait for the next release.
