### ISSUE TITLE
Is the unique jobs feature reliable?

### ISSUE THREAD

**Issue by bronson** [mperham/sidekiq#2791]
On the [homepage](http://sidekiq.org/), Unique Jobs is shown as a feature of the Enterprise edition.

But in the [wiki](https://github.com/mperham/sidekiq/wiki/Related-Projects) you say:

> job uniqueness or locking is impossible to implement safely and efficiently in a distributed system. I recommend using optimistic or pessimistic locking with database transactions instead of using these projects.

Does that mean Enterprise's Unique Jobs feature is unsafe or inefficient or both?  Thanks.

**Comment by mperham** [comment]
Fair question.  Uniqueness is one of those features I wish didn't have to exist but reality sometimes requires trade offs.  Sidekiq is designed for small, idempotent jobs.  Uniqueness is useful if you have jobs which are big and/or non-idempotent.  I've made the feature as efficient as I can and it's there if you need it.  From the wiki page:

> Design your jobs so that uniqueness is considered best effort, not a 100% guarantee.

Hope that explains things better.

**Comment by bronson** [comment]
It does.  Thanks!
