### ISSUE TITLE
Weird query related to sidekiq occurs in every request

### ISSUE THREAD

**Issue by sauronnikko** [mperham/sidekiq#2792]
Hi. I'm using Rails 4.2.5 with Sidekiq 4.0.2.

I'm having a very weird issue. Every request my app receives ends up executing this query:

`SELECT  "users".* FROM "users" WHERE LOWER("users"."email") = LOWER('sidekiq')  ORDER BY "users"."id" ASC LIMIT 1`

There is no instance of our code where that query is explicitly run.

What's going on?

**Comment by mperham** [comment]
No idea but Sidekiq does not use AR.  This must be something in your app.
