### ISSUE TITLE
Support for multiple instances of Sidekiq::Web to monitor multiple Ruby apps

### ISSUE THREAD

**Issue by treble37** [mperham/sidekiq#2793]
I have a Rails 4 application (app A) running sidekiq.  I have another Rails 4 application (app B) that mounts Sidekiq::Web to monitor app A.  If I have another Rails 4 app (or other Ruby based app) running sidekiq (app C), is it possible to monitor it via Sidekiq::Web from app B?  It seems like it's not.  If that's the case, any chance this is going to be possible in a future release of standard or PRO version?

**Comment by mperham** [comment]
It isn't documented well but Sidekiq Pro can do this today.  I've cleaned up the wiki page a bit to document it:

https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding
