### ISSUE TITLE
Need new feature of filter logger message

### ISSUE THREAD

**Issue by zhen639** [mperham/sidekiq#2794]
For the moment, when a worker retry exhausted or raise an exception, sidekiq would logger the args and error message, but there maybe some private information in the args so that I don't want it be loged.
Is there anyhow to config the sidekiq logger for filter some parameters? similar to "Rails.application.config.filter_parameters += [:password, :args, :class]" in rails?

**Comment by mperham** [comment]
There's no way to do this today.

**Comment by mperham** [comment]
No plans to implement.  I welcome a PR to improve this, perhaps we can just remove the logging of the job args.
