### ISSUE TITLE
Can not modify frozen Array on engine load when trying to set eager_load_paths

### ISSUE THREAD

**Issue by bbozo** [mperham/sidekiq#2795]
Hello :)

Sidekiq reported "RuntimeError: Can't modify frozen Array" when executing `config.eager_load_paths`

``` ruby
module TrcCommon
  class Engine < ::Rails::Engine
    isolate_namespace TrcCommon

    # autoload the '/lib' folder
    config.eager_load_paths << File.expand_path("../..", __FILE__)

  end
end
```

and this works as a workaround:

``` ruby
module TrcCommon
  class Engine < ::Rails::Engine
    isolate_namespace TrcCommon

    # autoload the '/lib' folder
    if Object.const_defined?(:Sidekiq) and Sidekiq.server?
      config.autoload_paths << File.expand_path("../..", __FILE__)
    else
      config.eager_load_paths << File.expand_path("../..", __FILE__)
    end

  end
end
```

This feels like a bug, because 

1. the Rails docs say this is the way you should set up autoload / eager load from an engine
2. everything else worked

On the other hand, the docs say that Sidekiq will flat-out ignore `config.autoload_paths` so I'm wondering if I did the right thing

I'm using sidekiq (3.5.1), rails 4.2.4 and ruby 2.0.0

**Comment by mperham** [comment]
This is not a Sidekiq bug but a Rails configuration issue.  I don't know how to do it correctly.

**Comment by jrochkind** [comment]
not really a sidekiq issue, but the only place I find googling for my problem (which is not actually about sidekiq at all) -- @bbozo did you ever get to the bottom of this? I've suddenly started getting this error in an app, that I didn't used to get it in, without any rails version upgrade or anything else that would be suspicious, complete mystery.

**Comment by bbozo** [comment]
@jrochkind kind of, I got into a fight with the lead maintainer of bundler and stopped using rails engines :laughing:

**Comment by jrochkind** [comment]
OK, thanks. Getting into fights with the lead maintainer of bundler seems to be going around!

This has nothing to do with sidekiq, but for those who find this on google: In mt case, it was an exception raised somewhere else entirely, but during the boot process. Something about an exception being raised caused _something_ to run the engine initializer a second time, and that second time, the array was frozen. The second time wouldn't have happened without the bug causing an unexpected raise at a different point in initialization though. Still no idea why the second time _did_ happen in this circumstance.

**Comment by bbozo** [comment]
@jrochkind I found the commit related to the fix for the above:

``` ruby
diff --git a/common/lib/trc_common/engine.rb b/common/lib/trc_common/engine.rb
index b130966..b47df2d 100644
--- a/common/lib/trc_common/engine.rb
+++ b/common/lib/trc_common/engine.rb
@@ -3,7 +3,12 @@ module TrcCommon
     isolate_namespace TrcCommon
 
     # autoload the '/lib' folder
-    config.eager_load_paths << File.expand_path("../..", __FILE__)
+    # https://github.com/mperham/sidekiq/issues/2795
+    if Object.const_defined?(:Sidekiq) and Sidekiq.server?
+      config.autoload_paths << File.expand_path("../..", __FILE__)
+    else
+      config.eager_load_paths << File.expand_path("../..", __FILE__)
+    end
 
   end
 end
```

I hope this helps you!
