### ISSUE TITLE
reliable fetch in pro version getting tasks from the end of the queue

### ISSUE THREAD

**Issue by DzmitryNikitsin** [mperham/sidekiq#2798]
i am using Sidekiq Pro v2.0.8 & Sidekiq v3.5.1 & have reliable push/fetch activated. 

what i found, push adding jobs to the beginning of redis queue https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L192(link to current version, but in 3.5.1 these piece is the same) , but pro/fetch.rb#40 - getting range from redis & start iterating, as result - job that came first - will be processed last. in my case - job processing some time & i have uniqueness validation, due to this issue - uniqueness validation(with timeout) does not make any sense, because i can have in the queue let's say 100k jobs, that should be processed & every time i am adding new jobs - new jobs will be executed, but also uniqueness timeout will expire for old jobs & we will add more not unique jobs. 

i do not see any reason why in pro i can't do rpush. 

do you see it as an issue & are you going to fix it in future releases ?

**Comment by mperham** [comment]
That `lrange` command is only when the process is starting up and needs to check the private queue for any lingering jobs (e.g. jobs which were processing when the process crashed).  The normal check for a job is on line 116, rpoplpush, which uses right side pop just like the [normal fetch](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/fetch.rb#L35) check.

So your code needs to use an LPUSH to enqueue jobs.

**Comment by DzmitryNikitsin** [comment]
thank you @mperham
