### ISSUE TITLE
Is there a way i can push certain cpu-intensive jobs to a different server?

### ISSUE THREAD

**Issue by deXterbed** [mperham/sidekiq#2799]
I understand that pushing jobs to a different redis server should work, but i don't know how to configure it inside the code, do/can we have some kind of DSL method to achieve this at runtime ?

**Comment by mperham** [comment]
Start a Sidekiq process to work on a "heavyweight" queue:

```
bundle exec sidekiq -q heavyweight
```

Push a job onto the heavyweight queue:

```ruby
MyWorker.set(queue: 'heavyweight').perform_async(some, args)
```

**Comment by deXterbed** [comment]
@mperham thanks for response :) , by different redis server i actually meant a server which is running on a different machine.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Sharding
