### ISSUE TITLE
perform(_at/_in) with seconds are taking minutes to enqueue

### ISSUE THREAD

**Issue by zakwanhaj** [mperham/sidekiq#2800]
Hi 

After updating to Sidekiq 4.x . I noticed that the scheduled jobs which should be enqueued after seconds, they are actually enqueued after 1-3 minutes.

example: 

`MyWorker.perform_in(3.seconds, self.id)` or `MyWorker.perform_at(3.seconds.from_now, self.id)` 

I'm seeing them in the list of scheduled jobs as '2 minutes from now' or 'about a minute from now'

Why?

**Comment by mperham** [comment]
Are your clocks sync'd?  Also, https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs#checking-for-new-jobs

**Comment by zakwanhaj** [comment]
You are right. My servers weren't synced with NTP. That's the issue.
Thank you
