### ISSUE TITLE
Sidekiq with Action Mailer doesn't work with AWS SES

### ISSUE THREAD

**Issue by dlihhats** [mperham/sidekiq#2803]
In my Rails 4 app, I am sending emails through Amazon SES:
`gem 'aws-ses', '~> 0.6.0', require: 'aws/ses'`

While
`UserMailer.contact_us(@form).deliver_now`
works perfectly fine with
`config.action_mailer.delivery_method = :ses`,
I cannot make Sidekiq also use SES to send out emails when I call
`UserMailer.contact_us(@form).deliver_later`.

I get the following errors:
`2016-01-30T13:27:45.917Z 15746 TID-ot4l3an3s WARN: Net::OpenTimeout: execution expired
2016-01-30T13:27:45.917Z 15746 TID-ot4l3an3s WARN: /home/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/smtp.rb:541:in 'initialize'
/home/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/smtp.rb:541:in 'open'
/home/username/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/smtp.rb:541:in 'tcp_socket'
<...>`

Why does Sidekiq use SMTP connection if I specified Action Mailer to use SES?

**Comment by mperham** [comment]
This seems like an aws-ses question, nothing really to do with sidekiq.
