### ISSUE TITLE
Create welcome flow for new users and potential customers

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2804]
One issue with my Sidekiq business is that I have no visibility into who might purchase my products until they actually do it.  Create an email drip campaign with helpful resources for new users.  Initial thoughts:

- [x] Add form to collect email addresses on sidekiq.org
- [x] Create a set of short screencasts on various Sidekiq, Pro and Enterprise features
- [x] Drip the videos to interested users once per day, link to associated wiki pages too
- [x] Send quarterly update emails with new features and changes

Any tips on how to implement this type of email campaigning (relevant SaaSes, blog posts, etc) would be appreciated.

**Comment by davydovanton** [comment]
About email me form:
You can use solution from thoughtbot
https://formkeep.com/

**Comment by mperham** [comment]
Thanks, I'll look into that, Google Forms and Wufoo. I'll need something that integrates into an email service so I can send a periodic newsletter.

**Comment by davydovanton** [comment]
So, do you want to create form only for newsletter?

**Comment by mperham** [comment]
Not sure. Right now I want to collect emails to drip them a daily video and then send a quarterly email. Hopefully that's automated.
