### ISSUE TITLE
Sidekiq Web 502 with nginx unicorn access

### ISSUE THREAD

**Issue by denovez** [mperham/sidekiq#2805]
Please help why sidekiq web in my live system 502 bad gateway.
I'm using nginx & unicorn for accessing this app.

this log app

> I, [2016-01-31T22:05:12.889209 #10495]  INFO -- : Completed 200 OK in 11ms (Views: 3.7ms | ActiveRecord: 1.5ms)
I, [2016-01-31T22:46:30.339019 #10495]  INFO -- : Started GET "/admin/sidekiq" for 127.0.0.1 at 2016-01-31 22:46:30 -0500
I, [2016-01-31T23:07:42.361389 #10495]  INFO -- : Started GET "/admin/sidekiq" for 127.0.0.1 at 2016-01-31 23:07:42 -0500

this log in nginx

> 
192.168.1.123 - - [31/Jan/2016:22:46:30 -0500] "GET /admin/sidekiq HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
192.168.1.123 - - [31/Jan/2016:23:07:42 -0500] "GET /admin/sidekiq HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
192.168.1.123 - - [31/Jan/2016:23:07:42 -0500] "GET /favicon.ico HTTP/1.1" 200 0 "http://192.168.71.2/admin/sidekiq" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"

anyone please help for solving this issue. :) 

Kind Regards,
denovez

**Comment by mikegee** [comment]
You will probably get more help on StackOverflow, since this seems like a problem with your setup, rather than a sidekiq bug.
