### ISSUE TITLE
Sidekiq will not start on Ubuntu via Upstart

### ISSUE THREAD

**Issue by jasper502** [mperham/sidekiq#2808]
I have been using https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu as a guide to no success.  I can launch Sidekiq manually and all is good.

If I try via Upstart my logs fill with `sidekiq respawning too fast, stopped` and `sidekiq main process (4188) terminated with status 127`.

The usual Google / Stackexchange search come up dry (as far as I can find) and I am hoping someone else has seen this.

I am running Sidekick 3.5.1 and Ubuntu 14.04.3 LTS.

I am pretty much using these https://github.com/mperham/sidekiq/tree/master/examples/upstart out of the box (except modifying for my path etc.)

**Comment by mperham** [comment]
You'll need to debug your startup script.  Start here:

http://upstart.ubuntu.com/wiki/Debugging

If anyone else has debugging / logging tips, please comment.

**Comment by jasper502** [comment]
Ok.. first off thanks for the tips - not a Ubuntu expert by any means so this was a good starting point.  It's a ruby issue I think.  Piped the output of my script to a log:

    usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/ubuntu/staging/current/bin/sidekiq:14:in `<main>'```

So I have:

    $ which -a ruby
    /home/ubuntu/.rbenv/shims/ruby
    /usr/bin/ruby

    $ rbenv versions
    system
    * 2.2.3 (set by /home/ubuntu/.rbenv/version)

My rails app is using 2.2.3 so can I just delete the 1.9.1 version manually or via rbenv (`rbenv uninstall system`)?

**Comment by mperham** [comment]
I would never uninstall the system ruby.  Ensure your conf initializes rbenv so it picks up 2.2.3.

**Comment by jasper502** [comment]
Your tip got me in the right direction and came across this:

http://stackoverflow.com/questions/26439555/did-upstart-or-bash-scripts-change-on-ubuntu-14-04-trying-to-boot-sidekiq-with

    export HOME=/home/ubuntu
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
    
    # Logs out to /var/log/upstart/sidekiq.log by default
    
     cd /home/ubuntu/staging/current
     exec bundle exec sidekiq -i ${index} -e staging -L log/sidekiq.log

Used this with the example conf files and it's all good.  Thanks again.
