### ISSUE TITLE
note on wiki that capistrano-sidekiq ignores upstart job

### ISSUE THREAD

**Issue by Genda1ph** [mperham/sidekiq#2810]
So, config provided here https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu works, however, if deployment is done via capistrano-sidekiq, sidekiq receives SIGUSR1 and then SIGTERM, which triggers respawn. After deployment is complete, capistrano starts another sidekiq.
For now we're using a workaround - we tell upstart that if sidekiq exits on SIGTERM with code 0, it's ok:
```
# TERM is sent by sidekiqctl when stopping sidekiq.  Without declaring these as normal exit codes, it just respawns.
normal exit 0 TERM
```
This should be fixed in capistrano-sidekiq itself, since sidekiq started by capistrano doesn't respawn.
However, I ask you to note this on the wiki, so this would not cause confusion for people.

**Comment by mperham** [comment]
I've updated the wiki to remove the inline file contents and point to the actual .conf file.
