### ISSUE TITLE
Redis memory usage slowly increases

### ISSUE THREAD

**Issue by kpheasey** [mperham/sidekiq#2812]
I'm using Sidekiq Pro with reliability enabled and calculating a few hundred thousand to 20+ million jobs in a day.  We have a dynamic number of sidekiq processes running on an AWS elastic beanstalk, usually between 1-10 all running 25 workers.

The redis memory usage will go up as the queue increases and drop a little as the queue is processed.  However, the memory usage never goes all the way back down.  Overtime it's building up more and more.

Our jobs are defined pretty simply.  Just a class name and an id.  When we have 0 memory usage, I can queue up 10+ million jobs.  But now after 20 days, I am worried that 100K jobs is going to cause the server to run out of memory.

The only solution is to call `flushdb` in redis or restart the elasticache server hosting redis.

![screen shot 2016-02-03 at 5 44 07 pm](https://cloud.githubusercontent.com/assets/3934075/12799930/a6e42882-ca9f-11e5-8e32-93006175f378.png)

![screen shot 2016-02-03 at 5 53 32 pm](https://cloud.githubusercontent.com/assets/3934075/12799958/e8999ad2-ca9f-11e5-8880-5a6f84cdd4c7.png)

**Comment by mperham** [comment]
Are you using Redis for anything else?  Are you using it directly?  100k enqueued jobs should not == 11GB of RAM.  Are you using any Sidekiq plugins?

There's no way to tell what the leak is without sampling the keyspace and looking for keys that shouldn't be there.

**Comment by kpheasey** [comment]
Redis is used exclusively for sidekiq.  We use the unique-jobs gem.  There is a background process that cleans up old private queues as well.

I tried going through redis to see if there was any extra data, but it was tough to tell for sure.  I'm pretty green when it comes to redis.

**Comment by mperham** [comment]
I can't speak for the unique-jobs gem but no one else has reported a leak.  I know that sidekiq-statistic has a pretty serious leak but that's the only misbehaving plugin I'm aware of.  If you want to gist a sample of 1000 or 2000 keys using [RANDOMKEY](http://redis.io/commands/randomkey) from your Redis, maybe that'll give me a clue.

**Comment by kpheasey** [comment]
I have just restarted the server, so I can't do that

I had enabled a replication server for high availability.  Before this, I didn't notice an issue, but I also upgraded to Pro at the same time.  I'm removing the read replica and will re-open this issue if I see a problem over the next few days.  At which point, I'll link a gust with RANDOMKEY.

**Comment by kpheasey** [comment]
I saw the problem happening again this morning.  While running RANDOMKEY I found tons of jobs for uinquejobs, looks like they aren't being released correctly.  I'll bring the issue up with them.  Thanks

**Comment by mperham** [comment]
For others, this might be a useful tool: https://github.com/gamenet/redis-memory-analyzer#redis-memory-analyzer
