### ISSUE TITLE
Periodic jobs: backfills

### ISSUE THREAD

**Issue by ivanovv** [mperham/sidekiq#2814]
Would be nice to have backfill option, to enqueue the job if it has been skipped last time for some reason

This is exactly the same functionality as in `sidetiq` gem https://github.com/tobiassvn/sidetiq/wiki/Backfills

**Comment by mperham** [comment]
Fair request, I addressed this feature here: https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#limitations In summary I believe backfill is hacky and suggest designing your jobs to be resilient to a missed interval if possible.  That said, I might implement this later this year but it is lower priority right now.

**Comment by mperham** [comment]
Decided against implementing it.  Cron jobs should be designed to handle "holes" in execution.
