### ISSUE TITLE
Sidekiq::Worker.set can behave very strangely unless perform_async is called immediately.

### ISSUE THREAD

**Issue by Senjai** [mperham/sidekiq#2816]
If I understand d6538b0b4f3c419ea969dc6710c6431b76a05d2b correctly.

With code like the following:

```ruby
queue1 = MyWorker.set(queue: 'queue1')
queue2 = MyWorker.set(queue: 'queue2')
queue1.perform_async(1)
queue2.perform_async(2)
```

Both messages would go to queue2. It's not immediately apparent that perform_async called at some point after set could perform undesired and difficult to diagnose behaviour. 

We might be able to fix this by using a proxy object instead of returning self, or storing this information using the object id.

**Comment by mperham** [comment]
Yep, that's not how the API is designed to work today.  The documented pattern is always:

```ruby
FooWorker.set(...).perform_async(...)
```

AcitveJob does this and I'd be happy to accept PRs more in line with that.

https://github.com/rails/rails/blob/master/activejob/lib/active_job/core.rb#L59
https://github.com/rails/rails/blob/master/activejob/lib/active_job/configured_job.rb

**Comment by Senjai** [comment]
Greate, I'll look into it!
