### ISSUE TITLE
Setting redis with config block breaks my tests

### ISSUE THREAD

**Issue by natematykiewicz** [mperham/sidekiq#2817]
I'm trying to upgrade to Sidekiq 4.1.0 from 3.5.1. I'm switching Sidekiq to use its own Redis DB, since it's recommended, and our app uses Redis for other things as well.

The tests that I have breaking are the only ones that use Sidekiq and my own Redis stuff at the same time.

All of my uses of Redis simply use `Redis.current` (so, default everything -- redis://127.0.0.1:6379/0).

I'm working on setting Sidekiq to use DB 1 -- redis://127.0.0.1:6379/1.

I can't set REDIS_URL because Redis.current would use that too. 

I followed the wiki's instructions:
```
#config/initializers/sidekiq.rb
Sidekiq.configure_client do |config|
  config.redis = { :url => 'redis://127.0.0.1:6379/1' }
end

Sidekiq.configure_server do |config|
  config.redis = { :url => 'redis://127.0.0.1:6379/1' }
end
```

This results in a lot of failing tests.

Then we tried something that DOES work. We set the following environment variables and ran the test suite.
```
REDIS_PROVIDER=SIDEKIQ_REDIS_URL
SIDEKIQ_REDIS_URL=redis://127.0.0.1:6379/1
```

Why does this work and using the config block doesn't?

Taking another example from the docs, we tried this:
```
redis = proc { Redis.new({ :url => 'redis://127.0.0.1:6379/1' }) }
Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(:timeout => 1, :size => 5, &redis)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(:timeout => 1, :size => 5, &redis)
end
```
This also works.

For "fun", we also tried:
```
Sidekiq.configure_client do |config|
  config.redis = Sidekiq::RedisConnection.create({ :url => 'redis://127.0.0.1:6379/1' })
end

Sidekiq.configure_server do |config|
  config.redis = Sidekiq::RedisConnection.create({ :url => 'redis://127.0.0.1:6379/1' })
end
```
This did NOT work.

This makes me think that there is a problem with `Sidekiq::RedisConnection.create`, though I couldn't figure out what.

We're kind of banging our heads against the wall over here.

Side note, it would be nice if there were a SIDEKIQ_REDIS_URL env that took precedence over REDIS_PROVIDER and REDIS_URL, if it's set.

We're going to keep digging into this tomorrow, because we really want to upgrade to v4+, but if you have any ideas on things to try, I'd gladly help.

**Comment by mperham** [comment]
Try:

```ruby
config.redis = { db: 1 }
```

**Comment by natematykiewicz** [comment]
Unfortunately, that also did not work.

**Comment by mperham** [comment]
You haven't given an actual error so it's hard to diagnose further.

**Comment by natematykiewicz** [comment]
I know... And, all I have to go off of is that I expect some values to change in my own Redis and they don't. And I can get consistent successes/failures with the scenarios I described above.

How about this angle:
What's different from using the config blocks, vs using REDIS_PROVIDER?

Why would one work and not the other?

Sidekiq::RedisConnection.create literally says `options[:url] ||= determine_redis_provider`, so I don't understand what the difference would be, but I've watched the keys come in and out of both Redises. 

The dual environment variable setup works, and the config block doesn't.

**Comment by natematykiewicz** [comment]
I should mention, I expect the value in my own Redis to change, as the result of a Sidekiq job running successfully.

**Comment by mperham** [comment]
If you are using your own connection, it should work fine.  `Redis.new` will go to DB 0, `Sidekiq.redis` will go to DB 1.

**Comment by natematykiewicz** [comment]
> If you are using your own connection, it should work fine. 

I'm not sure what you mean. You mean setting config.redis to a ConnectionPool?

**Comment by mperham** [comment]
No, whatever you configure via block or URL are **Sidekiq's** connections.  It will always be DB 1.  If you want to connect and do stuff in DB 0, you need to create your own pool and use it in your workers:

```ruby
APPDB = ConnectionPool.new { Redis.new(db: 0) }

def perform
  APPDB.with do |conn|
    conn.set('foo', 1)
  end
end
```

**Comment by natematykiewicz** [comment]
Are you saying that if I configure Sidekiq to DB 1 (using a hash in the config), and use `Redis.current` in a job, Redis.current will actually return DB 1 instead of DB 0?

**Comment by mperham** [comment]
I have no idea what Redis.current will return.  It's a bad idea to share a single Redis connection across 25 threads.  That's why you create a pool.

**Comment by natematykiewicz** [comment]
I see. Thanks. I'll do some digging tomorrow and let you know what I find.

**Comment by natematykiewicz** [comment]
What would be a good way to output the current Sidekiq Redis and `Redis.current` from within a job? I'm still curious why the dual environment variable setup works and config blocks don't. Now, I want to confirm that I'm indeed using the Redises that I think I am. Though when I watched the keys that were created within Redis itself, it sure looked like everything was working correctly.

**Comment by mperham** [comment]
```
irb(main):002:0> require 'redis'
irb(main):003:0> Redis.current
=> #<Redis client v3.2.2 for redis://127.0.0.1:6379/0>
irb(main):004:0> require 'sidekiq'
irb(main):006:0> Sidekiq.redis { |c| c }
=> #<Redis client v3.2.2 for redis://127.0.0.1:6379/0>
```

**Comment by natematykiewicz** [comment]
```
irb(main):001:0> Redis.current
=> #<Redis client v3.2.2 for redis://127.0.0.1:6379/0>
irb(main):002:0> Sidekiq.redis { |c| c }
=> #<Redis client v3.2.2 for redis://127.0.0.1:6379/1>
```

How do I tell how many connections are in the pool and what they are? Is it possible that I have something unwanted in my `Sidekiq.redis` pool?

**Comment by mperham** [comment]
`p Sidekiq.redis_pool`

**Comment by natematykiewicz** [comment]
```
irb(main):001:0> p Sidekiq.redis_pool

#<ConnectionPool:0x007f0a9e9dfcb0 @size=5, @timeout=1, @available=#<ConnectionPool::TimedStack:0x007f0a9e9dfbe8 @create_block=#<Proc:0x007f0a9e9dfc60@/home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/redis_connection.rb:21>, @created=0, @que=[], @max=5, @mutex=#<Mutex:0x007f0a9e9dfb98>, @resource=#<Thread::ConditionVariable:0x007f0a9e9dfb70>, @shutdown_block=nil>, @key=:"current-69841793777140">
=> #<ConnectionPool:0x007f0a9e9dfcb0 @size=5, @timeout=1, @available=#<ConnectionPool::TimedStack:0x007f0a9e9dfbe8 @create_block=#<Proc:0x007f0a9e9dfc60@/home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/redis_connection.rb:21>, @created=0, @que=[], @max=5, @mutex=#<Mutex:0x007f0a9e9dfb98>, @resource=#<Thread::ConditionVariable:0x007f0a9e9dfb70>, @shutdown_block=nil>, @key=:"current-69841793777140">
```

**Comment by natematykiewicz** [comment]
I figured out my problem!

The test I'm working on is an integration test. I enqueue some work, wait for Sidekiq to perform the job, and then test that my changes worked. I couldn't figure out a good way to make sure that Sidekiq is done, so I had just done `sleep 2` (terrible, I know). That used to work, but apparently it takes a bit longer now to pick up the job and start performing it. Also, apparently the dual ENV strategy is faster than the configure block, though I don't know by how much. I was probably getting really lucky that the ENV thing even worked.

My problem is that this test invloves retrying jobs. So, I need to know that there are no jobs enqueued and no jobs currently in progress. `Sidekiq::Stats.new.enqueued.zero?` tells me if there are any jobs enqueued, but it doesn't help me in knowing that there are none in progress.

Is there a good way to wait for Sidekiq to finish, preferably with some timeout in case it NEVER finishes?

Currently, the best I can figure out is:
```ruby
sleep 0.2 until Sidekiq::Stats.new.enqueued.zero? # Make sure the job has started
sleep 2 # Give the job time to complete
```
This is still fragile, but works... I'd love something like:

```ruby
Sidekiq::Testing.wait_for_job_completion(10.seconds)
```
This method would block until everything has been processed, and raise an error if the Timeout was exceeded. 

Also, as far as using a Redis conneciton pool for my own use, I came up with this:
```ruby
#config/initializers/redis.rb
size = defined?(Sidekiq) && Sidekiq.server? ? Sidekiq.options[:concurrency] : 1
Redis.current = ConnectionPool.wrap(:size => size) { Redis.new }
```

Now, I can still continue to use Redis.current in my main app, and not really change any code, but it has the benefit of using a connection pool, now. Thoughts on that?

**Comment by mperham** [comment]
There's no way to wait for Sidekiq to process a job.  It's asynchronous by definition, you can poll but there's no guarantee how long you will have to wait.

Good start on the pool, I would keep it simple and do something like this:

```ruby
Redis.current = ConnectionPool.wrap(size: 10) { Redis.new }
```

**Comment by natematykiewicz** [comment]
@mperham, I don't entirely understand how the connection pools work. But, if my Redis.current is going to be used inside a 25 Sidekiq workers, wouldn't I want Redis.current to have 25 connections in the pool?

Also, I know that it's asynchronous, but assuming that I'm specifically enqueuing things for a test, is there no way to tell that there are currently no jobs enqueued or in progress (meaning Sidekiq is completely idle)? What would polling for that look like? I'm fine with waiting, but I haven't found a good way to poll with certainty.

**Comment by mperham** [comment]
The safest way to poll is to set a flag in Redis via the worker when it is done.  Your test just polls Redis every few seconds.

You might have 25 threads but that doesn't mean they all need to access Redis at the exact same time.  That's the point of sharing.

**Comment by natematykiewicz** [comment]
Interesting, so if 11 threads try to use Redis at once, 1 of them just has to wait? Or does it completely break?

**Comment by mperham** [comment]
It waits, up to the wait_timeout setting, default of 5 seconds.

**Comment by natematykiewicz** [comment]
Cool. Thanks for all your help!
