### ISSUE TITLE
Authentication is required for gems.contribsys.com error

### ISSUE THREAD

**Issue by bdensmore** [mperham/sidekiq#2818]
We have been using sidekiq pro for quite some time without issue, but just over the past few days we started seeing the following error when trying to do new pushes to heroku:

"Authentication is required for gems.contribsys.com.
Please supply credentials for this source. You can do this by running:
 bundle config gems.contribsys.com username:password"

I've tried running the bundle command with the username and password we have but it doesn't seem to do anything.

Has anyone else experienced this issue?

Thanks,
Ben

**Comment by mperham** [comment]
Please email me (mike at contribsys com) with your company info so I can verify.  People regularly fail to renew their subscription (usually due to credit card expiration) and are cut off.

**Comment by sophia-eb** [comment]
I meet the same issue, and could you please give me some help? Thanks!
