### ISSUE TITLE
HTML not properly escaped in sidekiq-web retries parameters

### ISSUE THREAD

**Issue by brightbits** [mperham/sidekiq#2824]
I'm seeing the page ending prematurely because the text in the retry parameters contains `<script>` so the browser is treating the rest of the page as a script... XSS?

Using version: 3.5.4

**Comment by brightbits** [comment]
```html
<td>{"job_class"=>"AsyncMailer::Job", "job_id"=>"16c53db7-e7f1-42d8-8a99-0e5dda3b898f", "queue_name"=>"email", "arguments"=>["Mailer", {"_aj_globalid"=>".."}, nil, "..", {"order"=>{"_aj_globalid"=>".."}, "personal_message"=>".."}, ["<SCRIPT/QSS", "SRC=//localhost/j>"]]}</td>
...
```

**Comment by mperham** [comment]
Running latest version?

**Comment by brightbits** [comment]
No, We're running 3.5.4, I thought I'd highlight it though, if it has been fixed, please close.

**Comment by mperham** [comment]
Tell us exactly how to reproduce it.  Works for me:

<img width="715" alt="screen shot 2016-02-08 at 08 37 24" src="https://cloud.githubusercontent.com/assets/2911/12892086/4ac2d0b4-ce3f-11e5-9f17-d77e664c5452.png">

**Comment by brightbits** [comment]
This was on the main retries page (/sidekiq/retries), in the table.

![image](https://cloud.githubusercontent.com/assets/196514/12896447/fdd3206e-ce99-11e5-9976-b7c32c05b604.png)

The job column, and what I posted above is exactly how it came out in the final HTML

**Comment by mperham** [comment]
I can't reproduce it.  You'll need to give me an exact repro scenario: `FooJob.perform_later(...what...)`.

<img width="664" alt="screen shot 2016-02-08 at 12 51 45" src="https://cloud.githubusercontent.com/assets/2911/12898678/c8a806fc-ce62-11e5-83b1-ce3977e6fbcc.png">

**Comment by mperham** [comment]
I'm not sure how it got to that point but what's displayed in that Job column is the value for `job["class"]`.  This seems to indicate a pretty fundamental problem in your app.  Sidekiq doesn't escape that value because it should be a class name within your app and not user-defined input.  Can you show us how that job got enqueued?

**Comment by brightbits** [comment]
The column contains the args to the job, as well as the class (isn't it JSON of the whole job?). one of the arguments was a string, which contained a script tag. The job was to send an email to a users friend, with a personal message in from that user, a vulnerability scan tested against this form, caused a job to get in to the queue with script tags in the message, which were not escaped.

**Comment by mperham** [comment]
What is an `AsyncMailer::Job`?  That's not a Sidekiq class or an ActiveJob class that I know of.  Please show me the exact lines of code creating this job.

**Comment by brightbits** [comment]
```ruby
  class Job < ActiveJob::Base
    queue_as :email

    # emails_class is a string
    # campaign is a GlobalID
    # server port is an integer
    # method_name is a string (the email method on the mailer we want to execute
    # arguments is an array of things, which are generally GlobalIDs and strings. This is the one that contained a string that wasn't escaped
    def perform(emails_class, campaign, server_port, method_name, *arguments)
      ..
    end
end
```

**Comment by mperham** [comment]
Ok, that's the job defintion.  Please show me the exact lines of code creating the job.
