### ISSUE TITLE
Feature Request: Specify Certain Errors not to Retry

### ISSUE THREAD

**Issue by aselder** [mperham/sidekiq#2826]
I'd love to be able to specify for a given worker class errors that should not be retried.

For instance, we have a worker that does some fiddling with IPA files. There are certain errors which get raised if certain parts of the IPA are malformed. In this case, retrying the job 25 times  doesn't make sense as it will never succeed. 

However, there are some errors that do get raised during the processing which may be transient and a retry is appropriate.

Perhaps a list of exceptions in the sidekiq_options for a job to not retry.

I'd be happy to hack on it if people think it's a worthwhile feature.

**Comment by mperham** [comment]
Is it not possible to rescue and ignore those errors in your perform method?

```ruby
def perform(input)
  begin
    do_something
  rescue Ignorable
  end
end
```

**Comment by aselder** [comment]
That would work to avoid the retry, but the job would be counted as a success. I'd like it to count as a failed job, squawk at Honeybadger, and end up in the DJQ for inspection and handling just like any other failure. I just don't want Sidekiq to retry it a bunch of times pointlessly.

**Comment by mperham** [comment]
Hmmm, I don't see how to do that with the current system for sure but this feels a little too close to my [No More Bike Shedding](https://github.com/mperham/sidekiq/wiki/Error-Handling#no-more-bike-shedding) policy for comfort.  There are 3rd party gems which expand the retry logic; you might investigate those.

**Comment by aselder** [comment]
Fair enough.. Just thought I'd throw it out there. Thanks.
