### ISSUE TITLE
Sidekiq on AWS ElasticBeantaslk not connecting to DB

### ISSUE THREAD

**Issue by swimlanes** [mperham/sidekiq#2829]
Im having trouble launching Sidekiq on my AWS ElasticBeanstalk environment.

I am running Sidekiq 4.1.0 with my Rails application.

I logged directly into the EC2 instance to start Sidekiq manually and when I run this:

bundle exec sidekiq -e staging -q default -q mailers

I get this error from the Insance:

```
2016-02-10T07:19:34.172Z 1655 TID-gn7dktok8 INFO: Booting Sidekiq 4.1.0 with redis options {:url=>"redis://xxxx.amazonaws.com:6379"}
'xxxx.xxxx.rds.amazonaws.com' database is not configured. Available: ["default", "development", "test", "production", "staging"]
```

I checked the RDS database URL its trying to connect to and its the right one for the environment I am trying to run this on.

My sidekiq config file looks like this:

```
redis_url = ENV['REDIS_URL']

Sidekiq.configure_server do |config|
   config.redis = { url: redis_url, namespace: "swimlanes_#{Rails.env}" }
end

Sidekiq.configure_client do |config|
   config.redis = { url: redis_url, namespace: "swimlanes_#{Rails.env}" }
end
```

I have tried everything. Do you know what I am missing?

**Comment by swimlanes** [comment]
Do I actually need to supply Sidekiq with any DB connection information??

**Comment by mperham** [comment]
Sidekiq doesn't use a DB at all; it uses Redis.  If your app uses a DB, it needs to configure it as normal, via config/database.yml or elsewhere.

**Comment by swimlanes** [comment]
Yes. It uses Redis to store the queue. But if I run an ActiveJob with `User.create()' in it, doesn't it need to know how to insert that into the DB as the Redis instance is separated from the application?

The Sidekiq worker needs to know about this? Or am I not understanding it?

**Comment by mperham** [comment]
Sidekiq boots Rails which handles all that for your app.

**Comment by swimlanes** [comment]
Ok I see. Thanks for explaining. 

So you don't have any hints at why Sidekiq is sending back that error message when it tries to bootup?

**Comment by mperham** [comment]
Sidekiq doesn't have such an error message.  You are starting Sidekiq but that doesn't mean it's at fault for every error you see.

**Comment by mperham** [comment]
Show us a backtrace, that will help 1000x more than any back and forth here.

**Comment by swimlanes** [comment]
Hey. Thank you for looking at this for me. I understand this may not have anything to do with Sidekiq, I love the project and just want to use it in my app. Here is the backtrack directly after I get that error above:

/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:231:in `resolve_string_connection'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:213:in `resolve_connection'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-import-0.10.0/lib/activerecord-import.rb:4:in `establish_connection_with_activerecord_import'
/var/app/current/config/initializers/sidekiq.rb:5:in `block in <top (required)>'
/home/rof/cache/bundler/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:62:in `configure_server'
/var/app/current/config/initializers/sidekiq.rb:3:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `call'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
/var/app/current/config/environment.rb:17:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:235:in `boot_system'
/home/rof/cache/bundler/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/cli.rb:49:in `run'
/home/rof/cache/bundler/ruby/2.2.0/gems/sidekiq-4.1.0/bin/sidekiq:12:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.2.0/bin/sidekiq:23:in `load'
/home/rof/cache/bundler/ruby/2.2.0/bin/sidekiq:23:in `<main>'

**Comment by mperham** [comment]
Yep, you just don't have your AR configuration correct.  Triple check your database.yml.  Nothing to do with Sidekiq.

**Comment by swimlanes** [comment]
I dont understand why I wouldn't as everything else works fine... Doing a User.Create() is fine in the environment. database.yml is correct. :(

**Comment by mperham** [comment]
Then you haven't set the environment correctly with -e.

**Comment by swimlanes** [comment]
Sorry. Here is the call I make that produces the error:

bundle exec sidekiq -e staging

Here is the DB yaml file:

staging:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>  

And it even states in the error that 'staging' is an option.

**Comment by mperham** [comment]
Let's see the actual values for those variables, except for password.

**Comment by mperham** [comment]
`'xxxx.xxxx.rds.amazonaws.com' database is not configured` makes it sound like the environment is set to the DB hostname, rather than "staging".

**Comment by swimlanes** [comment]
Good call. I'll have a look into this. Don't want to waste too much of your time.

**Comment by swimlanes** [comment]
Yes that was it. Thank you for your time. Even though it wasn't really a sidekiq issue I really appreciate it.
