### ISSUE TITLE
Config for Redis?

### ISSUE THREAD

**Issue by georgeu2000** [mperham/sidekiq#2830]
I looked through the docs but did not see how to set the config for Redis.

**Comment by ryansch** [comment]
https://github.com/mperham/sidekiq/wiki/Using-Redis

**Comment by ryansch** [comment]
Cheers!

**Comment by mperham** [comment]
The public wiki was defaced recently, losing the footer.  I've restored it.

**Comment by georgeu2000** [comment]
Thanks for the info. I didn't find the info when I first looked for it so I updated the Wiki a bit. Hope that is OK...

BTW, is there a review process for updating the Wiki?

**Comment by mperham** [comment]
There is no review process; I revert incorrect changes all the time. Caveat reader.

**Comment by mikeryz-rosie** [comment]
@georgeu2000 your title change broke the top Google result for "sidekiq redis". I don't know how to set up a redirect so I just created a new page with a "Go Here" link to the renamed page, but if you know how to configure this (if GitHub wiki allows it) I'm sure others would appreciate it.

**Comment by mperham** [comment]
Please do not rename wiki pages.
