### ISSUE TITLE
Redis connections never get closed (sidekiq pro 3.0.5)

### ISSUE THREAD

**Issue by samdvr** [mperham/sidekiq#2831]
Redis connections never get closed which results concurrent connections on redis to grow constantly.
I have tested this locally having 4 jobs run concurrently with retry option 5.
connections grew to 32 and after closing the main 4 sessions connections it remained at 28.
I am using **sidekiq pro 3.0.5**, **redis 3.0.3**, **connection_pool 2.0.2** with hanami

I have used the default configs and also explicit connection pooling but had the same issue.

My initializer 
```
require 'sidekiq'

redis_conn = proc do
  Redis.new(url: ENV.fetch('REDIS_URL'))
end

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 27, &redis_conn)
end
```

**Comment by mperham** [comment]
> Jobs are now fetched from Redis in parallel, making Sidekiq more resilient to high network latency. This means that Sidekiq requires more Redis connections per process. You must have a minimum of concurrency + 2 connections in your pool or Sidekiq will exit. When in doubt, let Sidekiq size the connection pool for you.

https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md#whats-new
