### ISSUE TITLE
idle sidekiq threads use huge memory

### ISSUE THREAD

**Issue by evrenios** [mperham/sidekiq#2833]
Hello, i have 3 sidekiq process with concurrency set to 10

Even tho i have no running job, i see all the empty threads use memory. And the screenshot i'm sharing is right after the starting workers, no job ever worked on these freshly initialized process, so i dont think it's a memory leak issue.

Is it a normal thing that sidekiq do ? 

http://prntscr.com/a3h7hz

**Comment by mperham** [comment]
Each sidekiq process is a box, your rails app fills it with junk.  Not much I can do about it.  Clean up your app, like so:

http://www.mikeperham.com/2016/02/09/kill-your-dependencies/

Also, htop shows one entry per thread.  Hit "H" to show processes only.
