### ISSUE TITLE
Batch complete/success interface

### ISSUE THREAD

**Issue by mhuggins** [mperham/sidekiq#2837]
I'm reading through the [documentation for batching](https://github.com/mperham/sidekiq/wiki/Batches#callbacks) as we're about to purchase the pro version, and I have a question/suggestion regarding the interface for handling success/complete callbacks.  Actually, I have two thoughts.

My first thought is that it doesn't seem to make sense to use an instantiable class since there's no benefit to instantiating.  Given that, why not just use the actual object passed in?  The would allow the user to either simply define a module with public methods, or to instantiate an object that then gets called.

**Module approach:**

```ruby
module BatchHandler
  def self.on_success(status, options)
    # ...
  end
end

batch.on(:success, BatchHandler, 'uid' => current_user.id)
```

**Instantiable class approach:**

```ruby
class BatchHandler
  attr_accessor :ids

  def initialize(ids)
    self.ids = ids
  end

  def on_success(status, options)
    # ...
  end
end

handler = BatchHandler.new(user_ids)
batch.on(:success, handler, 'uid' => current_user.id)
```

Both of the above interfaces could be handled in the same way on sidekiq's end, but it would make the implementation a bit more dynamic for the developer.

Another suggestion is that this feels like a perfect opportunity to define a block.  The drawback is that this isn't as reusable as a class or module like before, but thought I'd throw this out there.

```ruby
batch.on(:success) do |status|
  # don't need explicit 'uid' option since parent context is in scope
end
```

**Comment by mperham** [comment]
Using module-level methods is a recipe for thread-unsafety and would be harder to test.  Ever tried mocking/stubbing a global method before?  It's much easier to deal with instances.

The block design can't be serialized over the network.  You have to be able to transfer the closure, including all its current state, from the client to the server.  Extremely inefficient.

**Comment by mperham** [comment]
My Rubyconf 2012 presentation talked about some of the fundamental decisions I made with Sidekiq's API and design.

http://confreaks.tv/videos/rubyconf2012-asynchronous-processing-for-fun-and-profit

**Comment by mhuggins** [comment]
Ahh, I hadn't gathered that the complete/success was happening in a separate thread or process.  Thanks for that clarification.
