### ISSUE TITLE
WebUI Rails 5 LoadError rack/showexceptions 

### ISSUE THREAD

**Issue by olegantonyan** [mperham/sidekiq#2839]
ruby 2.3.0, rails 5.0.0.beta2, sidekiq 4.1.0
```ruby
# Gemfile
gem 'sinatra', require: false

# routes.rb
require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'
```
With `require 'sidekiq/web'` in routes I get an error on server start:
```
/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require': cannot load such file -- rack/showexceptions (LoadError)
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/sidekiq-4.1.0/lib/sidekiq/web.rb:3:in `<top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/projects/restome/config/routes.rb:18:in `block in <top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
from /home/oleg/projects/restome/config/routes.rb:1:in `<top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `block in load'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:296:in `load'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `each'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:16:in `reload!'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/file_update_checker.rb:75:in `execute'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:27:in `updater'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `instance_exec'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:30:in `run'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:55:in `block in run_initializers'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:347:in `each'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:347:in `call'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:226:in `tsort_each'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/2.3.0/tsort.rb:205:in `tsort_each'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/initializable.rb:54:in `run_initializers'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/application.rb:350:in `initialize!'
from /home/oleg/projects/restome/config/environment.rb:5:in `<top (required)>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
from /home/oleg/projects/restome/config.ru:3:in `block in <main>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
from /home/oleg/projects/restome/config.ru:in `new'
from /home/oleg/projects/restome/config.ru:in `<main>'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:58:in `app'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:136:in `log_to_stdout'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/server.rb:76:in `start'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `tap'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:85:in `server'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
from /home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'

```

Sidekiq itself works (without require in routes)

**Comment by mperham** [comment]
Use Sinatra master.

**Comment by olegantonyan** [comment]
Thanks! It works

**Comment by yanperron** [comment]
Hi @mperham, 
could you tell me how to use sinatra master ? 

Thanks a lot, 

Yan

**Comment by seuros** [comment]
@yanperron in your Gemfile

```
gem 'sinatra', github: 'sinatra'
```

**Comment by vassyz** [comment]
I'm getting the same error with Rails Beta 4.
```
.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta4/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rack/showexceptions (LoadError)
```

**Comment by waghanza** [comment]
@vassyz  'till have the error ?

**Comment by vassyz** [comment]
Yes, same thing as OP. If I remove Sidekiq from routes it works fine.

Ruby 2.2.3
Rails 5.0.0.rc1
Sidekiq 4.1.2

    /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rack/showexceptions (LoadError)
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/web.rb:4:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/Sites/Obelisk/hq/config/routes.rb:1:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/file_update_checker.rb:77:in `call'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application/finisher.rb:116:in `block in <module:Finisher>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `run'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/application.rb:352:in `initialize!'
	from /Users/vasi/Sites/Obelisk/hq/config/environment.rb:5:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/vasi/Sites/Obelisk/hq/config.ru:3:in `block in <main>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `initialize'
	from /Users/vasi/Sites/Obelisk/hq/config.ru:in `new'
	from /Users/vasi/Sites/Obelisk/hq/config.ru:in `<main>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:49:in `eval'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:218:in `app'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:59:in `app'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:77:in `start'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/vasi/Sites/Obelisk/hq/bin/rails:9:in `require'
	from /Users/vasi/Sites/Obelisk/hq/bin/rails:9:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/vasi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/vasi/Sites/Obelisk/hq/bin/spring:13:in `require'
	from /Users/vasi/Sites/Obelisk/hq/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by mperham** [comment]
You need Sinatra master.

**Comment by vassyz** [comment]
Sorry, my bad. I replied in a hurry.
I can confirm that the Sinatra master branch fixes it.

**Comment by sekrett** [comment]
I was getting this:

```
Bundler could not find compatible versions for gem "rack-protection":
  In Gemfile:
    sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack-protection (~> 2.0)

Could not find gem 'rack-protection (~> 2.0)', which is required by gem 'sinatra', in any of the sources.
```

Have to add this to make it work:
```
gem 'rack-protection', '~> 2.0', github: 'sinatra/rack-protection', require: false
gem 'sinatra', github: 'sinatra/sinatra', require: false
```

**Comment by badosu** [comment]
@sekrett Rack-Protection 2.0.0 is only available using the master branch for now

**Comment by dbackeus** [comment]
Beta versions are out now so can start using those instead:
`gem "sinatra", ">= 2.0.0.beta2", require: false # https://github.com/mperham/sidekiq/issues/2839`

The `rack-protection` 2.0.0.beta2 seems to get pulled in automatically from that so no need for the extra declaration.

**Comment by jamesw** [comment]
I've just hit this same issue with ruby '2.6.3' and gem 'rails', '~> 6.0.2.1'
Any ideas on how to resolve this please?
