### ISSUE TITLE
Are unique jobs really unique during the time interval ?

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#2844]
I just got my Sidekiq licence and I want to rely on unique jobs.

The [documentation](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#use) states :
> If your job retries for a while, 10 minutes can pass, thus allowing another copy of the same job to be pushed to Redis.

Then If I set a unique job this way:
```
sidekiq_options unique_for: 5.months
```
Is it 100% guarantied this job will be unique for 5 months or before success ?

**Comment by mperham** [comment]
In distributed systems, nothing is 100% guaranteed.  I can think of edge cases that will lead to duplicate jobs but under normal circumstances, uniqueness should work fine.  A key can be evicted if you have the wrong persistence configuration, a network drop at exactly the right microsecond can lead to unexpected behavior, etc.

Yes, uniqueness will last as long as you define.  Redis does not have a limit to TTL, unlike memcached.

**Comment by Micka33** [comment]
Good Enough. Thank you.

**Comment by ryansch** [comment]
For one of our algorithms that needs that 100% guarantee we use a dual lock system.  We use sidekiq unique jobs as our first cheap lock that is fast and keeps most of the duplicate jobs from being scheduled.  We then use redlock as our second expensive lock that guarantees mutual exclusion (as long as you hit your time budget).  You could substitute any kind of distributed lock for redlock there.

**Comment by Micka33** [comment]
@ryansch 
> and keeps most of the duplicate jobs from being scheduled.

Do you mean you met cases where it was duplicated ? Can you elaborate on that ?
