### ISSUE TITLE
Cursor not found only inside Sidekiq using MongoDriver

### ISSUE THREAD

**Issue by fcruxen** [mperham/sidekiq#2845]
Just like ticket #63 

I get this cursor not found error using mongo driver, but only when the query is invoked inside a sidekiq worker. Tested with sidekiq 3.5 and 4.1.

I've already opened a JIRA ticket for the mongo driver guys, but since the error is only occuring in sidekiq workers I thought I should try here as well. mongo driver and mongoid are thread safe, but thats exactly were it's failing in sidekiq.

Here's the error output:
2016-02-23T18:04:49.333Z 64962 TID-ox4zzsn80 WARN: {"class"=>"SomeWorker", "args"=>[], "retry"=>true, "queue"=>"queue", "jid"=>"cb701eddb7283164b30feb9f", "created_at"=>1456250684.413802, "enqueued_at"=>1456250684.4139001, "error_message"=>"Cursor not found (namespace: 'db.document', id: 5486708915067151895). (43)", "error_class"=>"Mongo::Error::OperationFailure", "failed_at"=>1456250689.333214, "retry_count"=>0}
2016-02-23T18:04:49.333Z 64962 TID-ox4zzsn80 WARN: Mongo::Error::OperationFailure: Cursor not found (namespace: 'db.document', id: 5486708915067151895). (43)
2016-02-23T18:04:49.333Z 64962 TID-ox4zzsn80 WARN: /Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/operation/result.rb:256:in `validate!'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/operation/executable.rb:36:in `block in execute'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/server/connection_pool.rb:108:in `with_connection'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/server/context.rb:63:in `with_connection'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/operation/executable.rb:34:in `execute'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/cursor.rb:163:in `block in get_more'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/retryable.rb:51:in `call'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/retryable.rb:51:in `read_with_retry'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/cursor.rb:162:in `get_more'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/cursor.rb:88:in `each'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongo-2.2.2/lib/mongo/collection/view/iterable.rb:44:in `each'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.0/lib/mongoid/query_cache.rb:207:in `each'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.0/lib/mongoid/contextual/mongo.rb:405:in `reduce'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.0/lib/mongoid/contextual/mongo.rb:405:in `pluck'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.0/lib/mongoid/contextual.rb:20:in `pluck'
/Users/fcruxen/Developer/Ark/app/workers/raccoon_queue_janitor_worker.rb:10:in `perform'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'
/Users/fcruxen/Developer/Ark/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'

**Comment by mperham** [comment]
This isn't a Sidekiq issue, you'll need to take it up with the Mongo folks.
