### ISSUE TITLE
Can I dynamically add jobs to an already running batch ?

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#2846]
Let's say I have a similar workflow than described [below](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches).
![](https://raw.githubusercontent.com/mperham/sidekiq/master/examples/complex_batch_workflow.png)

The major Difference is that, jobs B,C,D,E,F will also create jobs. And I want to go to G only when all of them are done.

Can I make B,C,D,E,F add the jobs they create to the batch they are in ?

**Comment by phrodrigues** [comment]
A gem that realizes exactly what you're asking is https://github.com/chaps-io/gush

**Comment by mperham** [comment]
@Micka33 Absolutely you can add more jobs to a batch from within any job of that batch, just reopen the batch and declare more jobs:

```ruby
def perform(...)
  batch = Sidekiq::Batch.new(bid)
  batch.jobs do
    # add more jobs
    AnotherWorker.perform_async
  end
end
```

You can even dynamically add child batches:

```ruby
def perform(...)
  batch = Sidekiq::Batch.new(bid)
  batch.jobs do
    child = Sidekiq::Batch.new
    child.on(:success, ...) # parent batch won't succeed until the child batch has succeeded
    child.jobs do
      # add more jobs
      AnotherWorker.perform_async
    end
  end
end
```

**Comment by mperham** [comment]
@phrodrigues I'm glad it works for you but it's not for everyone.  The problem with using 3rd party extensions is you have no idea how well they are going to perform or interact with various other features.

Sidekiq Pro's Batches feature has been tuned for high performance for years now.  I have customers with batches containing millions of jobs running >10,000 job/sec.  It also works well with other premium features: unique jobs, rate limiting, etc.  That quality is something lots of companies are willing to pay for.
