### ISSUE TITLE
Multiple processes running?

### ISSUE THREAD

**Issue by randy-girard** [mperham/sidekiq#2847]
when I start up sidekiq, it will launch multiple processes. They seem to increase and decrease automatically. Sometimes there could be 5 or 6 and they are usually processing 0 of 5. Is this normal behavior of has anyone heard of this before?

```
# sidekiq.yml
---
:concurrency: 5
:queues:
  - somequeue
production:
  :concurrency: 5
```

```
# sidekiq.rb
Sidekiq.configure_server do |config|
  if Rails.env.production?
    config.redis = { url: '...' }  
  end
  
  config.server_middleware do |chain|
    chain.add Sidekiq::Throttler, storage: :redis
  end
end


Sidekiq.configure_client do |config|
  if Rails.env.production?
    config.redis = { url: '...' }  
  end
end
```

**Comment by mperham** [comment]
If you are looking at htop, press Shift-H. Those are threads, not processes.

**Comment by randy-girard** [comment]
I was curious about that too, so I ran a pstree on it, and it appears to be actual processes.

THis is in top without thread view:
![image](https://cloud.githubusercontent.com/assets/91918/13291341/6166ca5c-dae5-11e5-9b6e-b8ff954bcd0b.png)

Here is with thread view:
![image](https://cloud.githubusercontent.com/assets/91918/13291391/8683a90e-dae5-11e5-8550-8e64804a381c.png)

**Comment by mperham** [comment]
I'd guess you have an issue with your environment or deploy script then.  Sidekiq does not ever create processes or fork, only threads.

**Comment by Faisal-nfl** [comment]
@randy-girard 
I am facing same issue, did u figured that what was the issue?

**Comment by randy-girard** [comment]
Sorry, I never figured out what the issue was with this :(

**Comment by mperham** [comment]
@phensalves Please don't resurrect old issues.  Open your own specific issue.
