### ISSUE TITLE
Reliability feature is not usable on ECS and EBS

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2849]
Deployments using Amazon's ECS and EBS can't use reliable fetch.  The issue is that hostnames are ephemeral **and** index cannot be set since they require all processes to look identical.  Without either of those two elements, there's no way to allocate private queues to each unique process.

Fixing this would require a complete rewrite of the reliability feature.  No ETA.  Feedback welcome since I'm not very familiar with these services.

**Comment by ryansch** [comment]
I'm working on dockerizing our application right now and I'm planning to leverage consul to solve this.  I'll report back once I get there.

**Comment by johvet** [comment]
We've dockerized our application already and are also using consul. Maybe that's the way to go.

**Comment by jonhyman** [comment]
We use yml files to configure each of our worker processes. You could have a new option called `reliable_fetch_hostname` that was used instead of `Socket.gethostname`, and let people use their configuration management tools to set it just like we set the index.

**Comment by jonhyman** [comment]
Oh wait, I just realized you said index can't be used. Not sure, then.

**Comment by mperham** [comment]
@jonhyman every EBS process must look identical so it can auto-scale them.  There's no way to give them different ymls afaik.

**Comment by jhoffner** [comment]
I was just looking into this and had started down a path of dynamically selecting an index based off of the sidekiq process list. Each process within ECS will have a unique hostname, so the host name would be matched against the process list and a list in Redis that stores which indexes have been assigned to hostnames. So basically this:
- Sidekiq process starts
- Retrieves a list of all running sidekiq processes
- Retrieves a list of all mapped hostnames/indexes (from redis)
- Determines which mapped hostnames are still running by intersecting the two lists
- Determines the lowest index that is not yet mapped
- Assigned that index to the hostname and updates the hostname/index mappings within Redis
- Sets `config.options[:index]` to the index determined

Of course to do this it looks like a Redis lock will need to be utilized. `setnxex` should be good enough. 

I'm putting out fires so I didn't get too far with this. I may have time later this week to give it a try.

**Comment by mperham** [comment]
The new timed_fetch algorithm is designed for ECS and containers.

https://github.com/mperham/sidekiq/wiki/Reliability#using-timed_fetch
