### ISSUE TITLE
Incompatibility with servers that rename-command INFO (since 4.1.0)

### ISSUE THREAD

**Issue by lwe** [mperham/sidekiq#2850]
First of all, thanks a lot for giving us sidekiq and contributing so much to the Ruby ecosystem.

Our workers are running on a CloudFoundry instance and a Redis service also running on CloudFoundry. The operator decided to disable `INFO` command due to security reasons, i.e. they basically added the following to their configuration file:

```ini
rename-command INFO ""
```

This week we switched from Sidekiq 3.x to Sidekiq 4.1.0 and our workers stopped booting with the following error `Redis::CommandError: ERR unknown command 'info'`. Checking to sidekiq source revealed that commit d285f194803780b639dd6095a785f638b627720f added an additional check:

```ruby
  ver = conn.info['redis_version']
  raise "Oops, you are using Redis v#{ver}, Sidekiq requires Redis v2.8.0 or greater" if ver < '2.8'
```

to ensure that it's really running against Sidekiq 2.8 or greater. We contacted our operator and they don't seem too inclined to make security related changes. Currently there are two remaining options for us

1. **Monekypatching**, we already did that as a quick-fix, but not really sure if this might break something else down the line: https://gist.github.com/lwe/590fbf613284d85cf1a3
2. **Creating a PR** on sidekiq to skip it or find a decent alternative (e.g. checking for a specific command added in 2.8.0?)

However before investing our time in a PR, do you think there is any possibility that this skip / check would make sense, if so any proposals or favorites to pursue?

### Environment

```
Redis server v=3.0.1 sha=00000000:0 malloc=libc bits=64 build=bf58331b4c8133f5
Sidekiq version (v4.1.0): ac6c23521e4f64fb47de77d2adbb96ea0536059f
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
Rails 4.2.5.1
```

### Stack trace

```
Redis::CommandError: ERR unknown command 'info'
    /_path_/gems/redis-3.2.2/lib/redis/client.rb:114:in `call'
    /_path_/gems/redis-3.2.2/lib/redis.rb:211:in `block in info'
    /_path_/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
    /_path_/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /_path_/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
    /_path_/gems/redis-3.2.2/lib/redis.rb:210:in `info'
    /_path_/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
    /_path_/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
    /_path_/sidekiq/test/test_sidekiq.rb:92:in `block (3 levels) in <class:TestSidekiq>'
    /_path_/sidekiq/lib/sidekiq.rb:84:in `block in redis'
    /_path_/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
    /_path_/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
    /_path_/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
    /_path_/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
    /_path_/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
    /_path_/sidekiq/lib/sidekiq.rb:81:in `redis'
```

### Reproduction steps

```bash
# 1. checkout repo
git clone https://github.com/mperham/sidekiq.git

# 2. checkout tag v4.1.0
git checkout v4.1.0

# 3. bundle
bundle install

# 4. start redis-server with rename-command:
redis-server - <<EOF
rename-command INFO ""
EOF

# 5. open another console and run the tests
bundle exec rake test
```

### Other call sites

A quick search on the sidekiq repo revealed other call sites to `info`:

```bash
$> ag '\.info' | grep -v logger
lib/sidekiq/cli.rb:71:        ver = conn.info['redis_version']
lib/sidekiq/util.rb:64:      info = Sidekiq.redis {|c| c.info }
lib/sidekiq/web_helpers.rb:129:          conn.redis.info
lib/sidekiq/web_helpers.rb:131:          conn.info
```

1. In `util.rb` the method is `want_a_hertz_donut?`, but I don't see this method called directly anywhere :smile:, found a reference to it in issue #2431, so probably useful for debugging?
2. the `web_helpers.rb` basically wants the following keys from `INFO`: `%w(redis_version uptime_in_days connected_clients used_memory_human used_memory_peak_human)` and displayed in a `stats-container` on the dashboard

Not sure what to do about the method in `util.rb`, but for `web_helpers.rb` we could simply return an empty hash or fill in `"n/a"` or `"blocked"` or something.

PS: Not sure if there are additional implications on Sidekiq Pro.

**Comment by lwe** [comment]
Implementation idea: as `Sidekiq::Util` is included almost anywhere, how about adding a method `redis_info` in there which catches this specific exception and returns an empty hash instead or a hash with `{ 'version' => '2.8' }` and then change all call sites to use this method instead?

Not really happy with string comparing an exception message... but  ¯\_(ツ)_/¯

**Comment by mperham** [comment]
Sidekiq needs the INFO command.  One thing I can see working: adding command aliasing support to redis-rb so that if you do `rename-command INFO foobar`, you could do something like:

```ruby
r = Redis.new(:commands => { :info => 'foobar' })
r.info['redis_version'] # would actually call "FOOBAR"
```

See https://github.com/redis/redis-rb/issues/111 and the commit in the last comment.

If you want to send a PR to encapsulate the info usage so you can easily disable it via monkeypatch, I'd consider that.

**Comment by lwe** [comment]
Thanks for the quick answer. They actually aliased it to an empty string, so aliasing is sadly not working (was hoping that too at first). Regarding the encapsulation idea, so e.g. adding `redis_info` to `Util` with a default implementation and then one could monkeypatch `Sidekiq::Util#redis_info`?

**Comment by mperham** [comment]
Yeah, that's a reasonable idea.

**Comment by lwe** [comment]
Okay, thanks, will pursue that as a PR then, in addition adding an exception handler directly (so no monkey patching is required - that is my goal actually :smile:) could be easily done then too.

**Comment by lwe** [comment]
Would it also be okay to add this method to `sidekiq.rb` instead of `Util`, as the `web_helpers.rb` do not include `Util`?

**Comment by lwe** [comment]
Closing this in favour of the referenced PR.
