### ISSUE TITLE
How to add redis password in the config file of  sidekiq?

### ISSUE THREAD

**Issue by zxx1988328** [mperham/sidekiq#2852]
**Here is my  "/home/git/gitlab/log/production.log"  ,**

`Redis::CommandError (NOAUTH Authentication required.):
  vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis/client.rb:85:in `call'
  vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:675:in `block in set'
  vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:36:in `block in synchronize'
  /usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:36:in `synchronize'
  vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:671:in `set'
  vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:9:in `set'`

 ** And here is my  "/home/git/gitlab/config/initializers/4_sidekiq.rb" file **

`config_file = Rails.root.join('config', 'resque.yml')

resque_url = if File.exists?(config_file)
               YAML.load_file(config_file)[Rails.env]
             else
               "redis://localhost:6379"
             end

#print(config_file);

Sidekiq.configure_server do |config|
  config.redis = {
    url: resque_url,
    password: 'zxx123456',
    namespace: 'resque:gitlab'
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: resque_url,
    password: 'zxx123456',
    namespace: 'resque:gitlab'
  }
end
`

**my redis.conf has set "requirepass". Why "Redis::CommandError (NOAUTH Authentication required.)"?**

**Comment by zxx1988328** [comment]
![Uploading image.png…]()

**Comment by mperham** [comment]
Please contact gitlab for support.

**Comment by zxx1988328** [comment]
@mperham  thanks
