### ISSUE TITLE
Batches report pending jobs, but I don't see those jobs anywhere

### ISSUE THREAD

**Issue by jonathan-upstart** [mperham/sidekiq#2855]
Hi, we're a Sidekiq Pro user and have started using Sidekiq Batches (awesome feature!). Today I ran a large batch job, and it's currently reporting 5 pending jobs. But when I examine the Busy queue (along with Enqueued, Retries, Scheduled, etc) in the Sidekiq UI, I see only 1 related job that is still running.

Batches UI showing 5 pending:
<img width="773" alt="screen shot 2016-02-26 at 5 31 23 pm" src="https://cloud.githubusercontent.com/assets/2081825/13369805/c6272372-dcae-11e5-98d2-e4613bb5495e.png">

But only 1 related job appears anywhere here (inside the "Busy" queue):
<img width="780" alt="screen shot 2016-02-26 at 5 31 47 pm" src="https://cloud.githubusercontent.com/assets/2081825/13369813/d88fe79c-dcae-11e5-8604-6581f45130fd.png">

Is there a place where jobs sometimes "hide"? I've noticed that sometimes I see jobs disappear for a bit, only to re-appear later in the Enqueued or Busy section.

Thanks,
Jonathan

**Comment by jonathan-upstart** [comment]
Update: the Sidekiq UI now shows 4 pending jobs in the batch, but none of those 4 jobs can be found running or enqueued (or failed).

**Comment by mperham** [comment]
They can be stuck in a private queue until the associated process is restarted. https://github.com/mperham/sidekiq/issues/2629
