### ISSUE TITLE
Jobs deletion after restart

### ISSUE THREAD

**Issue by vmatekole** [mperham/sidekiq#2857]
Hi!

It appears since upgrading to Sidekiq 4 jobs are now being deleted after restart of my Ruby app and my Redis persisting to disk. Can you confirm this behaviour? How do I get Sidekiq to preserve all jobs even after reboot?

~victor

**Comment by mperham** [comment]
No behavior has changed in 4.  No one else is reporting this so I assume it is an environmental or application issue.

**Comment by vmatekole** [comment]
@mperham  Thanks for getting back. Perhaps, I am misleading myself... How can I ensure that job history is preserved after application restart? What are the prescribed steps?

**Comment by mperham** [comment]
Jobs are persisted in Redis until they are processed.  If enqueued jobs are disappearing upon deploy, you might have something which is calling FLUSHDB in Redis or something like that.
