### ISSUE TITLE
Different behaviors for Redis re-connect  on MRI and JRuby

### ISSUE THREAD

**Issue by khelll** [mperham/sidekiq#2858]
I stopped the Redis server and observed 2 different stacks, one runs Sidekiq with Ruby MRI, and the other with JRuby. In both of them I got the same error message:

`Error fetching job: Error connecting to Redis`

However, when I ran the Redis server again, the MRI version could connect again and work without troubles, while the JRuby one got stuck, and couldn't connect to Redis again. So I had to kill the process and start it again.

I'm wondering if this is something that can be fixed for the JRuby runs, and I need a way to automate the kill/start of such workers when it can't connect to Redis, it shouldn't stuck like that. May be a way to check if the worker is working or stuck?

**Comment by mperham** [comment]
I don't understand.  If JRuby is acting different, why is that a Sidekiq issue?

**Comment by khelll** [comment]
I just did more  investigation and it turns out that Redis is indeed reconnecting but the worker is setting idle after that:

``` Ruby
Sidekiq::Queue.new('caching').size #=> 2 
ps = Sidekiq::ProcessSet.new
ps.size # => 1
ps.each do |process|
  p process['busy']     # => 0
  p process['hostname'] # => 'some ip'
  p process['pid']      # => 9679
end
```

**Comment by mperham** [comment]
I still don't understand.  What is the issue?  Is this a Sidekiq issue or JRuby issue?

**Comment by khelll** [comment]
I'm not sure, but I tend to believe it's a Sidekiq issue:

Here is the scenario again: When the Redis connection disconnects(say you stopped the Redis server) then reconnects why on JRuby the workers become idle while in MRI they resume working as if nothing happened?

**Comment by mperham** [comment]
**Why** do you believe it is a Sidekiq issue?  It works perfectly on MRI, if JRuby isn't acting like MRI, isn't that a JRuby issue?

**Comment by khelll** [comment]
Shouldn't Sidekiq handle such a case where the worker is Idle although there are jobs queued? Some mechanism to self restart?

**Comment by mperham** [comment]
[It already does](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L90).  I did fix a bug in the error recovery handling a few days ago, maybe try master and see if it works better on JRuby?

**Comment by khelll** [comment]
Actually it did. Code never reached [this](https://github.com/mperham/sidekiq/blob/dd420c55991f4476c46d6d5ade015fa96526885f/lib/sidekiq/processor.rb#L86) debugging statement before the fix you mentioned, but now being on master things are working.

**Comment by mperham** [comment]
Great, thanks for being patient with me and explaining.

**Comment by khelll** [comment]
Hmm sorry for opening this again, just noticed something else:
Retries work, but enqueued jobs are not working without restarting the Sidekiq process. So, the queue seems to pick the retrials and leave the enqueued jobs without picking them up.

**Comment by mperham** [comment]
#2866
