### ISSUE TITLE
ENV variables and rails secrets are missing due the time.

### ISSUE THREAD

**Issue by lemoniak2** [mperham/sidekiq#2861]
Hello :) I'm struggling with that issue like 3 weeks so I decided to post issue here.
Here is my situation:
I'm using sidekiq jobs for pulling data from some external services. I'm running thousands of jobs per hour. At the beginning (20 minutes - 1 hour after start) everything is working fine. After that some of the jobs can't read rails secrets and ENV variables logs looks like this: secrets: {:secret_key_base=>nil, :oauth_url=>nil, :oauth_key=>nil, :oauth_secret=>nil, :item_counters_max_size=>nil, :base_domain=>nil, :share_domain=>nil, :insights_domain=>nil, :go
ogle_issuer=>nil, :google_public_api_key=>nil}

the same issue with envs:
ENV['GOOGLE_PUBLIC_API_KEY'] =
ENV['GOOGLE_ISSUER'] =

Some of the jobs are working fine but after like 3 hours all of them does not have filled all the env variables and secrets - and import doesn't work anymore. Simetimes restart of the sidekiq helps but not everytime. Do you have any clue what could be wrong?

Thanks in advance :)

**Comment by mperham** [comment]
Sidekiq doesn't touch ENV or secrets.  No clue what the problem might be but I'd suspect another gem, perhaps one that modifies the ENV when creating subprocesses.
