### ISSUE TITLE
How to call system to run command line from os using Sidekiq

### ISSUE THREAD

**Issue by buithehien1991** [mperham/sidekiq#2863]
I have MyModel class
```
def do_work
  system("java -jar my_java_program.jar")
end
```
When I want to call do_work() function
`MyModel.delay.do_work()`
But java program is never called. 
If you know this issue, please show me how to fix it. 
Thank you very much.

**Comment by seuros** [comment]
don't use `.delay`. delay is just a helper to migrate from resque.

Create a worker and call your java program there.

**Comment by buithehien1991** [comment]
Thank you so much for your answer. 
I'll try to do that.

**Comment by mperham** [comment]
You need to make it a class method:

```ruby
def self.do_work
  system("java -jar my_java_program.jar")
end
```

MyModel.delay.do_work
