### ISSUE TITLE
"perform_in" is not scheduling a job

### ISSUE THREAD

**Issue by sarathprasath** [mperham/sidekiq#2865]
Hi,

We are using sidekiq enterprise and we are having around million scheduled jobs. The issue what we are seeing is we are not able to schedule any new jobs. Are you aware of any such issues ? Also would like to know the internals how scheduler in sidekiq works?

Thanks,
Sarathprasath

**Comment by mperham** [comment]
> we are not able to schedule any new jobs

What does that mean?  Give me a complete backtrace or error message.

> Also would like to know the internals how scheduler in sidekiq works?

The scheduler is open source.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb
