### ISSUE TITLE
Feature Request: Web UI displays which process is the leader

### ISSUE THREAD

**Issue by AvonGenesis** [mperham/sidekiq#2867]
Would be nice to see which process is the current leader of the senate in the WEB UI, possibly a tag or something on the busy page under processes?

**Comment by mperham** [comment]
Yeah, I'd thought about this.  There's no "clean" way to implement this today but I'll continue to ponder how it might be done.

**Comment by mperham** [comment]
Done. Requires Enterprise 1.6.0 and Sidekiq 5.0.1, which will be released at some point in the near future.

**Comment by mperham** [comment]
All the colors of the rainbow!

<img width="375" alt="screen shot 2017-05-26 at 10 19 39 am" src="https://cloud.githubusercontent.com/assets/2911/26505596/3cc1abb4-41fe-11e7-91ac-e3013801f826.png">
