### ISSUE TITLE
Should Sidekiq Error when `perform_async` is called with poorly serializable arguments?

### ISSUE THREAD

**Issue by EndangeredMassa** [mperham/sidekiq#2870]
Many hours have been lost by those I know (and many more beyond, I'm sure) to the quirk of sidekiq's implementation over redis that causes arguments passed to `perform_async` to be serializable to json and back. This causes symbols and some other values to be mutated between scheduling a worker and it executing, from the perspective of the caller.

Should Sidekiq force the arguments to be perfectly serializable and deserializable to the same value? Or at least, could there be an option to enable this behavior?

This could be accomplished by adding a guard to `perform_async` such as:

```ruby
def perform_async(*args)
  if args != JSON.load(JSON.dump(args))
    # TODO: craft a better error message
    raise StandardError.new("BAD ARGS")
  end
  client_push('class' => self, 'args' => args)
end
```

**Comment by mperham** [comment]
It would be a good idea to run that in non-production.

**Comment by EndangeredMassa** [comment]
I'm perfectly happy to have this default to off.

Personally, however, I would actually like to run this in production. I'd rather have a more explicit error from this check than a more vague error (like a nil reference somewhere) down in the execution of the worker.

Would you consider a PR that adds this under a sidekiq config value that defaults to false?

**Comment by mperham** [comment]
I would like it non-production because this is the type of error that should be caught during testing.  It has a significant performance penalty so I'd prefer it not enabled in production.

It also has the potential to break existing user code so I don't want to break production.  No, I don't want to make it user-configurable.

**Comment by EndangeredMassa** [comment]
Ah, yeah. It could be a performance problem. Good call.

So, always on when environment is not `production`?

**Comment by mperham** [comment]
Right.

**Comment by mperham** [comment]
I looked into this but ActiveJob breaks this check so I can't enable it.
