### ISSUE TITLE
Support for sidekiq "via" pool with batches

### ISSUE THREAD

**Issue by djreimer** [mperham/sidekiq#2876]
I might be wrong, but I'm thinking this use case is distinct from the use case described here: #2548.

I'm trying to ensure that a particular batch operation is always pushed to a specific redis instance. This instance happens to be the non-default one, so I have this in place (simplified example):

```ruby
Sidekiq::Client.via(SECONDARY_POOL) do
  batch = Sidekiq::Batch.new

  batch.jobs do
    enqueue_jobs
  end
end
```

This used to work before upgrading to Sidekiq Pro 3. Now I'm seeing the batch is always pushed to my default instance. I don't want to randomly spread batch jobs between instances, but rather ensure that all jobs the batch are isolated to one particular instance.

---

After a little source diving, perhaps allowing one to optionally specify which shard could work?

```
batch = Sidekiq::Batch.new(shard: 1)
```

**Comment by mperham** [comment]
What version of Pro did you upgrade from?  That should work.  Anything unusual about `enqueue_jobs`?

**Comment by mperham** [comment]
Yeah, Batches don't obey `via`, by design.  You can't just get a `bid` and call `Sidekiq::Batch::Status.new(bid)` on it because Sidekiq wouldn't know where to get the data.  Instead you have to follow the ShardSet API so the Batch can encode its shard and the status API can find the right shard.

```ruby
# initializer
Sidekiq::Shards.set [POOL1, POOL2, etc]

# your app code
Sidekiq::Shards.on(2) do
  batch = Sidekiq::Batch.new
  batch.jobs do
    Sidekiq::Client.via(POOL2) do
      enqueue_jobs
    end
  end
end
```

**Comment by djreimer** [comment]
Ah, I think that will do it! Thanks :star2:

**Comment by djreimer** [comment]
Hi @mperham! We are running into some trouble with this. After doing a little source diving, it appears that `Sidekiq::Batch.new` is always choosing a random shard for the batch, regardless of `Sidekiq::Shards.on(...)`:

```ruby
ss = Sidekiq::Shards
if ss.enabled?
  @shard = ss.random_index
  @bid += "@@#{@shard}"
else
  @shard = 0
end
```

It does appear that all the jobs are getting enqueued in the right shard.

**Comment by mperham** [comment]
Hmmm, looks like you are correct and I was mistaken.  The original requirement was to spread the jobs over N shards but the batch could be "homed" on any shard, so a random one was preferred to even the load.  I don't think we've ever been able to target everything about a batch to a single shard.

**Comment by djreimer** [comment]
Got it. My use case is that I have large batches of jobs that I want to process in a "low priority" queue, independent of my "main" queue. I noticed the batch record itself getting placed in the "main" queue half the time and assumed that was problem, but it sounds like that might not be the case. Should it just work?

**Comment by mperham** [comment]
A batch is not a job so it would never appear in a queue.  The batch callbacks **are** jobs and will go into whatever queue was used by the final job in the batch to execute unless you set the callback_queue attribute when creating the batch, i.e. `batch.callback_queue = "critical"`

**Comment by djreimer** [comment]
Sorry, misused the terminology :). I meant batch was being homed in on our main shard, despite all its jobs being pushed to the low priority shard. I think I'm starting to wrap my head around this though, and it seems like that wont actually cause any problems with the batch processing. Thanks!
