### ISSUE TITLE
Sidekiq Batch Pending -1. How ?

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#2879]
How can I have a batch with a pending -1 ?
It seems to happen when I start a new Sidekiq processes and the batch is already running.
It also seems to happen when I abruptly shutdown a Sidekiq process.

Here is a picture worth thousands words.

![screen shot 2016-03-10 at 10 19 52](https://cloud.githubusercontent.com/assets/3918958/13664915/141c6c2c-e6aa-11e5-82a0-491e87017ec6.png)

**Comment by mperham** [comment]
I suspect you are executing duplicate jobs.  Are you using reliable fetch?  Is it possible you are starting two processes on the same host with the same index (maybe the old and new processes are running concurrently)?

**Comment by mperham** [comment]
Have you taken steps to make your Docker hostnames stable and give each process a unique index?  If you haven't, turn off reliable fetch and see if the problem goes away.  Read the wiki page on server reliability:

https://github.com/mperham/sidekiq/wiki/Reliability#limitations

I'm working on a new fetch algorithm that will work better within Docker, EBS, ECS, etc.

**Comment by Micka33** [comment]
`reliable fetch` turned off fixed the problem.
I will work on `to make your Docker hostnames stable and give each process a unique index`.

Thank you.
