### ISSUE TITLE
Sidekiq Pro: 9 minute delay between "startup complete" and "started processing"

### ISSUE THREAD

**Issue by dacoinminster** [mperham/sidekiq#2880]
After deployment to heroku of sidekiq pro, I've been seeing a disturbingly long delay between the "Sidekiq startup complete" message and the "Starting processing" message. From our logs:

Mar 10 15:21:43 cl-recipe-manager app/sidekiq.5: Sidekiq startup complete. ENV['SIDEKIQ_AR_DB_POOL_SIZE']=10, ENV['SIDEKIQ_CONCURRENCY']=5, Rails configured to be 10. 
Mar 10 15:30:15 cl-recipe-manager app/sidekiq.5: 3 TID-osrk1fes8 INFO: Starting processing, hit Ctrl-C to stop 

What could cause such a long delay? It seems to be getting worse over time. I think it took 5 minutes last deployment a few weeks ago - this time it took almost 9 minutes.

The delay is starting to affect users negatively, so I hope you can help us sort this out.

Thanks!

**Comment by mperham** [comment]
"Sidekiq startup complete." is not a log message in the Sidekiq code so that doesn't help.

Check your [slowlog](http://redis.io/commands/slowlog).  Monitor your Redis `redis-cli monitor` and see what operations it is performing.

**Comment by dacoinminster** [comment]
Aha! I thought it was a sidekiq message, but that is a status message from our code (sorry, I should have known that, but I inherited this codebase). Here's the relevant code snippet:
```
Sidekiq.configure_server do |config|
  config.redis = Connector.sidekiq_config
  config.on(:startup) do
    Connector.disconnect
    desired_pool_size = Integer(ENV['SIDEKIQ_AR_DB_POOL_SIZE'] || 10)
    Connector.connect(ar_db_pool_size: desired_pool_size)

    pool_size = ActiveRecord::Base.connection_pool.instance_eval {@size}
    Rails.logger.info("Sidekiq startup complete. ENV['SIDEKIQ_AR_DB_POOL_SIZE']=#{ENV['SIDEKIQ_AR_DB_POOL_SIZE']}, ENV['SIDEKIQ_CONCURRENCY']=#{ENV['SIDEKIQ_CONCURRENCY']}, Rails configured to be #{pool_size}.")
  end
end
```
It appears that I should be looking at redis to see what is happening here, as you suggested. Thanks for pointing me in the right direction.
