### ISSUE TITLE
Getting ERROR: Actor crashed!  because of ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by z5h** [mperham/sidekiq#2881]
I have some code which can cause a sidekiq job to tun before a record is persisted.
That's my own fault and I should fix it.
Still, I expected an exception to put the job into the retry queue, but it failed it instead.

> ERROR: Actor crashed!     
> ActiveRecord::RecordNotFound: Couldn't find [...] with 'id'=3

The documentation says:

> Either way, Sidekiq's retry mechanism's got your back. The first time might fail with RecordNotFound but the retry will succeed.

Gemfile.lock details
```
    sidekiq (3.5.4)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
```

**Comment by mperham** [comment]
That's a normal error message when a job raises an error.  The job should still be in the retry queue.
