### ISSUE TITLE
Enterprise: Periodic.rb errors out by trying to use Sidekiq::Periodic::Config before requiring it

### ISSUE THREAD

**Issue by sampriddy** [mperham/sidekiq#2882]
Using sidekiq-ent 1.2.1, Sidekiq errors at periodic.rb:17 by trying to use the Sidekiq::Periodic::Config class and raising a NameError when it can't find it. It looks like this is because the code tries to use the class before it is required; moving the require statements above the method at line 17 fixed the error.

Adding `require 'sidekiq-ent/periodic/config'` to the top of the sidekiq initializer seems to work as a temporary fix.

**Comment by mperham** [comment]
Sam, it sound like you might not be starting Sidekiq with `bundle exec`.  Line 69 should execute when periodic.rb is required, well before line 17.  Are you calling the `periodic` method outside of a `configure_server` block?

**Comment by mperham** [comment]
Show me your code which is failing and how you are starting Sidekiq.

**Comment by sampriddy** [comment]
The periodic method is only called one time, from within a configure_server block. The command to kick off sidekiq is formatted like this: `sidekiq_cmd = /bin/env RAILS_ENV=#{rails_env} bundle exec sidekiq --index 1 --concurrency 1 --tag #{application}:#{revision}`

**Comment by mikegee** [comment]
Here's the full `config/initializers/sidekiq.rb` for that app:

```ruby
require 'sidekiq-ent/periodic/config' # latest sidekiq errors out otherwise

redis_conn = proc { elided_redis_info }

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 20, &redis_conn)
  config.reliable_fetch!
  config.reliable_scheduler!
end

Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    mgr.register('0 2 * * *', ElasticsearchBuilder, retry: 7) # every 2am
  end
end

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 20, &redis_conn)
end
```

**Comment by mperham** [comment]
I can't reproduce your issue, it works fine for me and I'm doing something similar to you:

```ruby
Sidekiq.configure_server do |config|
  config.redis = { namespace: "myapp_development", host: 'my.local.redis.server.on.localhost' }
  config.reliable!
  config.periodic do |mgr|
    mgr.register "* * * * *", ScheduledWorker, retry: 1
    mgr.register "*/4 * 10 * *", ScheduledWorker, retry: 2
  end
  config.save_history(statsd)
end
```

Ideas?  Can you post the full backtrace of the error?

**Comment by sampriddy** [comment]
I tried and failed to reproduce the issue this morning. No guesses as to what changed in the environment to make things work. Thanks for your time.
