### ISSUE TITLE
Redis eviction ALLKEYS-LRU issue

### ISSUE THREAD

**Issue by comjf** [mperham/sidekiq#2883]
Hello there Mike!

Here at WeddingWire, we're long term users of sidekiq pro and rely on it as our primary async job server. We've been using it in prod for at least 2 years now. This issue is specific to an issue we're debugging with redis eating up memory and evicting keys... now that isn't specific to sidekiq, but what I'm finding is, redis is almost always evicting sidekiq keys first when I know there are older things for it to evict.

We use ElastiCache service from AWS but that shouldn't matter as it's just a clustered redis 2.8.22 server. Our max-memory policy is ALLKEYS-LRU and according to the docs: allkeys-lru: evict keys trying to remove the less recently used (LRU) keys first, in order to make space for the new data added.

What I am concerned about is, whenever we start evicting keys, I go to the sidekiq UI and I see all of my stats are being wiped (number of jobs processed, failed, etc) and I'm very worried that redis is evicting sidekiq keys for jobs even before they have run. If I find a random key in a different DB, then run OBJECT IDLETIME on that key... it may be 90 days... yet after some keys are evicted... that old key wasn't but all of my sidekiq keys were.

I suppose this is more of a question for redis maintainers, but do you know any reason why evictions are favoring sidekiq as opposed to older keys in different dbs?

Thanks!
James Flowers

**Comment by mperham** [comment]
Hi James, I don't really know much about Redis' LRU algorithm.  I suppose those Sidekiq keys are unused by its own metric but I don't know that metric.

I definitely do not recommend running Sidekiq with that policy.  If you are using Redis for caching, you should use a separate instance that is configured for caching.  I've added a note to the wiki: https://github.com/mperham/sidekiq/wiki/Using-Redis#memory

**Comment by comjf** [comment]
Mike, Thanks for the quick response! I understand where you're coming from in recommending sidekiq to use a persistent redis setup. There are a few business and cost reasons why we can't implement this at the current time, but I'll go ahead and close this issue.

Our temporary solution is going to make sure we have enough free-memory and ensure every key has a sane TTL set. This is our primary problem as we have a lot of very old keys eating up an insane amount of memory that never expire... My concern was more of why redis isn't evicting those keys first but instead picking on sidekiq. I wasn't sure if you saw similar behavior or not, but it sounds like you haven't (since you don't even use the same policy).

Thanks for your help!
