### ISSUE TITLE
sidekiq options support in ActiveJob

### ISSUE THREAD

**Issue by vsorlov** [mperham/sidekiq#2884]
Hi, what do you think of adding sidekiq options support in `ActiveJob`? Isn't it as simple as adding `options` setter to `ActiveJob` and then find it in wrapper class instead of a job class?
https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L20

Not sure what Rails core team thinks about it, but sidekiq options add some crucial features. Sure it is better to create some common solution for all active job adapters.

**Comment by mperham** [comment]
I don't control ActiveJob.  If you want options support, you'll need to push for it in ActiveJob 5.x with the Rails team.
