### ISSUE TITLE
Explain memory bloat more thoroughly

### ISSUE THREAD

**Issue by skatenerd** [mperham/sidekiq#2886]
In the [memory bloat](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#memory-bloat) section in the wiki, we have:

`If you have a memory bloating and your Sidekiq process goes from X MB to BIG MB over time, much of the time the cause is unoptimized ActiveRecord queries`

Got it!

But then it goes on to say,

`If the product search returns 10,000 results, this query will create 10,000 objects and then immediately throw them away. Terrible!`

I'm not exactly sure how this is a problem.  I guess I don't fully understand what's happening when we "throw away" the results.  Shouldn't GC clean the unused objects up after the job completes?  I imagine that this is what happens when you, say, make a large AR query within a Rails controller.  

Would it make sense to manually `GC.start` at the end of my jobs, just to make sure that these thrown-away records get cleaned up?

**Comment by mperham** [comment]
You need to have all 10,000 objects in memory at the same time.  That expands the heap and causes VM bloat.

**Comment by skatenerd** [comment]
Addressed with https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting/_compare/3255e32781fda0df76b57c6d7400dc827dc52249...2b30adf3a3e021eb50e57028ae7bb0a95a416e62
