### ISSUE TITLE
Jobs in batches in Sidekiq Pro run but stay marked as "pending"

### ISSUE THREAD

**Issue by thatmoodyguy** [mperham/sidekiq#2888]
I'm using Sidekiq Pro's batches feature to generate a series of batched jobs, and all of the jobs in the batch execute (each job sends a message that I can see, so I know they're running), but the batch still indicates that all the jobs are pending, and the complete callback never fires.  What am I missing?

**Comment by thatmoodyguy** [comment]
The code that creates the batches:

`      send_batch = Sidekiq::Batch.new
      send_batch.description = "Message ##{self.id}"
      send_batch.on(:complete, 'Message#on_message_send_batch_complete', "message_id" => self.id, "start_time" => start)

      recipients.in_groups_of(1000, false).each do |recipient_group|
        send_batch.jobs do
          recipient_group.each do |recipient|
            begin
              Message.send_message_to_recipient!
            end
          end
        end
      end`

**Comment by mperham** [comment]
Put the jobs block around the in_groups_of block. You can't add jobs to a batch multiple times like you are currently.

**Comment by thatmoodyguy** [comment]
Did that, but getting the same result - the jobs inside the batch run, but they're still showing as pending.

**Comment by mperham** [comment]
So you are doing this?

```ruby
      send_batch = Sidekiq::Batch.new
      send_batch.description = "Message ##{self.id}"
      send_batch.on(:complete, 'Message#on_message_send_batch_complete', "message_id" => self.id, "start_time" => start)
      send_batch.jobs do
        recipients.in_groups_of(1000, false).each do |recipient_group|
          recipient_group.each do |recipient|
            begin
              Message.send_message_to_recipient!
            end
          end
        end
      end
```

That doesn't make any sense then unless you've removed the batch server middleware somehow.  Show us your initializer.

**Comment by thatmoodyguy** [comment]
Here it is:

```
require 'sidekiq'

begin
  REDIS_CONFIG = YAML.load_file("#{Rails.root}/config/redis.yml")[Rails.env]

  # if there is a password pass that with blank username (hence leading :)
  connection_string = "redis://" +
    (REDIS_CONFIG["password"] ? ":#{ REDIS_CONFIG["password"] }@" : "") +
    "#{ REDIS_CONFIG["host"] }:#{ REDIS_CONFIG["port"] }"

  Sidekiq.configure_server do |config|
    config.failures_max_count = false
    config.redis = {:url => connection_string}
    config.average_scheduled_poll_interval = 2
  end

  Sidekiq.configure_client do |config|
    config.redis = {:url => connection_string}
  end

rescue => e
end
```

**Comment by mperham** [comment]
I'd get rid of that `begin..rescue`.  It's hiding startup errors.

**Comment by mperham** [comment]
And you can get rid of the `require 'sidekiq'`.  Bundler does that for you.  You are using Bundler to initialize everything normally, yes, with `gem 'sidekiq-pro'` in your Gemfile?  Using `gem 'sidekiq-pro', require: false` will break things.

**Comment by thatmoodyguy** [comment]
Yes, I'm using Bundler, and I've booted the `require 'sidekiq'` line.  Still no joy.

**Comment by mperham** [comment]
I can't explain why it's not working for you then.

**Comment by mperham** [comment]
When you boot the server with `-v`, what does it print out?

**Comment by thatmoodyguy** [comment]
```
Booting Sidekiq 3.5.3 with redis options {:url=>"redis://:REDACTED@redis-01:6379"}
Running in ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
Sidekiq Pro 2.1.4, commercially licensed.  Thanks for your support!
Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Failures::Middleware, Sidekiq::Middleware::Server::RetryJobs, Sidekiq::Middleware::Server::ActiveRecord, Sidekiq::Batch::Server, Honeybadger::Plugins::Sidekiq::Middleware
Starting processing, hit Ctrl-C to stop
{:queues=>["admin", "notify", "sms-01", "sms-01", "sms-01", "sms-01", "sms-02", "sms-02", "sms-02", "sms-02", "post", "post", "account", "mailchimp", "logging", "mail_integration", "mo", "mo", "mo", "mo", "mo", "mo", "mo", "mo", "mo-2", "mo-2", "mo-2", "mo-2", "mo-27800", "mo-27800", "mo-27800", "mo-27800", "mo-30311", "mo-30311", "mo-30311", "mo-30311", "mo-35001", "mo-35001", "mo-35001", "mo-35001", "mo-47400", "mo-47400", "mo-47400", "mo-47400", "mo-55404", "mo-55404", "mo-55404", "mo-55404", "mo-88022", "mo-88022", "mo-88022", "mo-88022", "mo-80810", "mo-80810", "mo-80810", "mo-80810", "mo-85100", "mo-85100", "mo-85100", "mo-85100", "mo-88250", "mo-88250", "mo-88250", "mo-88250", "mo-55022", "mo-55022", "mo-55022", "mo-55022", "send_msg", "send_msg", "send_msg", "send_msg", "send_msg", "send_msg", "send_msg", "send_msg", "clean_subscribers"], :labels=>[], :concurrency=>25, :require=>".", :environment=>"production", :timeout=>30, :poll_interval_average=>nil, :average_scheduled_poll_interval=>2, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x007ff7592919b0>, #<Proc:0x007ff75b3d32b8@/home/web/tatango/20160316_232406_335/vendor/bundle/ruby/2.3.0/gems/honeybadger-2.0.6/lib/honeybadger/plugins/sidekiq.rb:28>], :lifecycle_events=>{:startup=>[#<Proc:0x007ff75a32d788@/home/web/tatango/20160316_232406_335/vendor/bundle/ruby/2.3.0/gems/sidekiq-pro-2.1.4/lib/sidekiq/shard_set.rb:70>], :quiet=>[], :shutdown=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :verbose=>true, :pidfile=>"./tmp/pids/sidekiq.pid", :logfile=>"./log/sidekiq.log", :strict=>false, :config_file=>"config/sidekiq.yml", :backup_limit=>1000, :tag=>"20160316_232406_335"}
```

**Comment by mperham** [comment]
Well, there's the batch middleware.  I can't explain why it's not working for you.  You're seeing the exact behavior as if the server middleware was not running.  If the Web UI shows XX jobs pending, that means the client middleware is running correctly.  The server middleware subtracts from pending and fires the callback, which is exactly what isn't working for you.

**Comment by thatmoodyguy** [comment]
It took some time to find the issue, but for posterity: if it looks like your server batch middleware isn't running, but `sidekiq -v` says that it is, make sure you're actually calling a worker in your batch.jobs loop.  I wasn't. 

Thanks so much for your help @mperham!
