### ISSUE TITLE
PG::Error: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by igorkasyanchuk** [mperham/sidekiq#2892]
From worker I'm receiving from time to time this issue:
PG::Error: server closed the connection unexpectedly
    This probably means the server terminated abnormally
     before or while processing the request.

Full stack trace:
https://gist.github.com/igorkasyanchuk/e42882ce98e7060ba413

**Comment by mperham** [comment]
Sounds like you have a problem with PG, possibly with a firewall closing idle database connections.  Most likely not Sidekiq related.
