### ISSUE TITLE
There is currently no retry option for batch callbacks

### ISSUE THREAD

**Issue by amilligan** [mperham/sidekiq#2893]
I have a number of jobs I would like to not retry in the event that they fail.  For jobs this is reasonably straightforward (could be better with ActiveJob, but I appreciate that's a DHH issue, not a Sidekiq issue), but is, as far as I can tell, not possible with batch callbacks.

I can imagine something like this:
```
  batch = Sidekiq::Batch.new(retry: false)
```
or
```
  class BatchCallbacks
    sidekiq_options retry: false
    def on_success
      ...
```

Adding the option to Batch#on would, I imagine, be difficult to do without changing the interface.  In any case, I don't have much opinion on the how.

Thoughts?

**Comment by mperham** [comment]
Catch all errors so the job succeeds.

**Comment by amilligan** [comment]
Gosh, you'd think I could have thought of that.

On the other hand, we have a well defined error management model that consistently manages our errors so they are reported in a particular way.  Given that we can set the retry on jobs, and that batch callbacks are basically jobs, it seems reasonable to want to treat them consistently.

**Comment by mperham** [comment]
You can reopen the class in your initializer:

```ruby
class Sidekiq::Batch::Callback
  sidekiq_options retry: false
end
```

But this would affect every batch callback.

The problem with `retry: false` is that **any** bug or error means the job is discarded.  Sidekiq can't distinguish between a 3rd party service error that will never work and a null pointer that is a bug which should be fixed and the job retried.  Your application code needs to rescue errors that don't matter.

**Comment by johvet** [comment]
I agree with @amilligan that this should be configurable on the callback class or the `:on ...` call. I am having a similar problem. While some batch-callbacks are retry-able some aren't. And reopening does not seem like a viaable solution.

We want the *unexpected* situations to escalate into our monitoring systems and have our error-processing take care of that. But at the same time, I do *not* want the callback to be retried (maybe I already know it won't ever be able to recover).

**Comment by foxtacles** [comment]
I agree with @johvet

**Comment by richardmonette** [comment]
Do `Sidekiq::Batch::Callback` retries respect the global max_retries config option https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/job_retry.rb#L52?

**Comment by mperham** [comment]
@richardmonette yes, they should.
