### ISSUE TITLE
Processes/Jobs Disappear from Web UI

### ISSUE THREAD

**Issue by scarpenter** [mperham/sidekiq#2895]
Sidekiq version: 4.1.1
Redis version: 2.8.24 (AWS ElastiCache)
Rails version: 3.2.19
Ruby version: 2.1.2p95

I recently created a new worker that executes a bunch of non-ActiveRecord SQL against our database. It does this by using the Mysql2 client directly. When this SQL is running, the Sidekiq process and job disappears from the web UI (and judging by the log, no other jobs are picked up by this process). Once the SQL execution completes, the process reappears in the web UI.

I have no trouble believing that I'm doing something that's adversely affecting the Sidekiq process, but I'm not sure what it is. Sample code for the SQL execution:

```ruby
sql = "
create temporary table whatever
select col1, col2
from table1;

update ....."
connection_options = { host: "hostname", user: "user", password: "password", flags: Mysql2::Client::FOUND_ROWS | Mysql2::Client::MULTI_STATEMENTS }
client = Mysql2::Client.new(connection_options)
begin
  result = client.query(sql)
  while client.next_result
    result = client.store_result
  end
ensure
  client.close
end
```

**Comment by mperham** [comment]
Weird.  Make sure you are using the latest mysql2 but I've never heard of this happening before.  Sounds like it is not releasing the GIL and so the entire Ruby process halts while the database grinds away at the SQL.

**Comment by scarpenter** [comment]
Thanks for the quick response. Unfortunately other things are conspiring against updating to the latest Mysql2 gem at the moment, but it definitely seems like this is related there and not to Sidekiq.
