### ISSUE TITLE
perform_at is the same as perform_in?

### ISSUE THREAD

**Issue by giangnguyennet** [mperham/sidekiq#2896]
Hi,

I'm using sidekiq 3.4.2 and `perform_at` to send out notifications on a certain day in the future, something like this

```ruby
EventStartNotificationWorker.perform_at(1.day.ago(@event.start_date), @event.id)
```

and got this exception:

```ruby
undefined method `to_f' for Sat, 26 Mar 2016:Date
```

Due to [this wiki](https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs) `perform_at` and `perform_in` are different and the args are different too, one accepts a `timestamp` and the other accepts an `interval` as the first argument respectively.

But on line 41, `lib/sidekiq/woker.rb` there's an alias

```ruby
 alias_method :perform_at, :perform_in
```
So they are the same and obviously the exception occurs or am I missing something?

Thanks,

**Comment by mperham** [comment]
You have to pass something that converts to an epoch float.  DateTime or Timestamp; I guess a Date won't work.  `1.day.ago` will work, I don't know what `1.day.ago(@event.start_date)` means.

**Comment by mperham** [comment]
You could try `1.day.ago(@event.start_date).to_datetime`

**Comment by giangnguyennet** [comment]
You're right! I was wrong when passing a Date instead of DateTime or Timestamp. Thank you!
