### ISSUE TITLE
Window Rate Limiting can be off by one

### ISSUE THREAD

**Issue by DanThiffault** [mperham/sidekiq#2897]
If the race condition occurs that was fixed as part of #2704 the bucket is reset to zero instead of one so one extra request can be made. I think the fix is to add an additional increment line to line 86 of limiter/window.rb.

This isn't a high priority for us but we noticed it while debugging another issue.

sidekiq-ent 0.7.10

**Comment by mperham** [comment]
I'm not sure this is the case.  If `incr` creates the limiter bucket, it will set the value to 1, not 0.  My "fix" just ensures the expiry is set.

**Comment by DanThiffault** [comment]
Sorry misread the docs. Thanks for the fast response
