### ISSUE TITLE
Sidekiq batch is orphaned (has "pending jobs" when none are enqueued)

### ISSUE THREAD

**Issue by jasonjei** [mperham/sidekiq#2900]
It looks like the Sidekiq worker crashed while processing a batch:
```
2016-03-25T16:36:00.413Z 7 TID-owe5l6qzc SyncDumpSingleProcessWorker JID-4c655c8f2178d3ed10a04edc BID-Etk0Z-5OKR15lw INFO: start
09:36:00.000
2016-03-25T16:36:00.526Z 7 TID-owdw4n4fs SyncDumpSingleProcessWorker JID-b27af90f12c8dd7800fe38b4 BID-Etk0Z-5OKR15lw INFO: start
09:36:00.000
*** Error in `sidekiq 4.1.1 app [1 of 25 busy]': free(): invalid size: 0x00007fc658cb2610 ***
09:36:00.000
/run.sh: line 7: 7 Aborted sidekiq
09:36:11.000
2016-03-25T16:36:11.616Z 7 TID-oxhaa1pjg INFO: Booting Sidekiq 4.1.1 with redis options {:url=>"redis://:REDACTED@pub-redis-12676.us-central1-1-1.gce.garantiadata.com:12676/0"}
09:36:12.000
2016-03-25T16:36:12.535Z 7 TID-oxhaa1pjg INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
09:36:12.000
2016-03-25T16:36:12.535Z 7 TID-oxhaa1pjg INFO: Sidekiq Pro 3.0.6, commercially licensed. Thanks for your support!
09:36:12.000
2016-03-25T16:36:12.631Z 7 TID-oxhaa1pjg INFO: Starting processing, hit Ctrl-C to stop
09:37:18.000
2016-03-25T16:37:18.505Z 7 TID-oxhb0uv3g SyncWorker JID-7ab0170f4112a6ed237e46fd INFO: start
09:37:18.000
```
No jobs are actually enqueued in Sidekiq, while the batch shows 6 pending jobs:
![screen-shot-2016-03-25-at-10 33 52-am](https://cloud.githubusercontent.com/assets/318085/14051180/33faef20-f27e-11e5-89de-82d2d037d5f7.jpg)
Is this issue related to #2474 or #1772? What's the best guard for cleaning up dead batches? 

I was thinking of having a batch cleanup sentinel job (perhaps using the scheduled job feature) to go through the batches to verify they are alive.  For example, checking to see if a batch JIDs actually exist when it shows it has pending jobs, and if they don't delete the batch. For example, I could write a job to iterate over all the batches and do a simple test like below:
```
> batch = Sidekiq::BatchSet.new.detect { |v| v.bid == "Etk0Z-5OKR15lw" }
=> #<Sidekiq::Batch::Status:0x007f5e3ccd8240 @bid="Etk0Z-5OKR15lw", @props={"created_at"=>"1458923739.6318066", "callbacks"=>"{\"success\":[{\"SyncWorkerCallback\":{\"company_id\":3,\"last_sync_start_time\":\"2016-03-25T14:36:19Z\"}}],\"complete\":[{\"SyncWorkerCallback\":{\"company_id\":3,\"last_sync_start_time\":\"2016-03-25T14:36:19Z\"}}]}", "pending"=>"6", "kids"=>"0", "total"=>"17", "description"=>""}, @failures=0, @completed=0>
> batch.jids
=> ["92a8668d22bd251158e23e9c", "e80c9365c101b004988fdcfa", "c17ee3302751277e44d6e252", "b27af90f12c8dd7800fe38b4", "1e90d05ba74ad497a57a942f", "4c655c8f2178d3ed10a04edc"]
> job_alive = Sidekiq::Queue.new.find_job(batch.jids.first)
=> nil
> batch.delete if not job_alive
```
Environment is Sidekiq v4.1.1 / Sidekiq Pro v3.0.6, in a Docker container based on the ruby 2.2.0p0 (2014-12-25 revision 49005) image (which is based on the Debian jessie buildpack docker image), on Google Compute Enginer/Container Engine Kubernetes 1.1.8, with Rails 4.2.3, Redis gem 3.2.2. Let me know if you want me to post my Gemfile, Dockerfile, or anything else.

**Comment by jasonjei** [comment]
Alright, I'll manually delete the batch, try your sync again.  I can write some guard code to detect when a batch crashed.  Unfortunately, this looks like a bug in Sidekiq. But we can detect when it died and fix it.

**Comment by jasonjei** [comment]
It looks like I'm also using an older version of Pro (3.0.6) as opposed to the 3.2.0 version.  Does the 3.2.0 support detection of dead zombie batches? Also, the invalid memory reference with free()--is that a Ruby bug or Sidekiq bug?

**Comment by mperham** [comment]
free() is a Ruby / native gem bug, not Sidekiq.

Looks like you have not enabled reliable fetch so those 6 jobs were lost forever.  Upgrade to the latest Pro and add this to your initializer:

```ruby
Sidekiq.configure_server do |config|
  config.timed_fetch!
end
```

You can delete a batch with `Sidekiq::Batch::Status.new(bid).delete`.
