### ISSUE TITLE
Sidekiq queue jobs keep dissapearing

### ISSUE THREAD

**Issue by aussiDavid** [mperham/sidekiq#2901]
The application I have I am using sidekiq to deliver emails (within jobs).
I only ever send emails immediately or in 48 hours time. The latter is used as a reminder email.

When I send emails immediately via sidekiq they appear as processed (as it should). When I schedule a reminder email (in 48 hours time) it appears scheduled (also, as it should).
However, after a certain time it appears my sidekiq instance gets wiped. The number of processed jobs and scheduled jobs disappear and return to 0.

There does not appear to be any traces in any log.
I deploy the rails app via capistrano.

I'm running out of ideas on determining and fixing the issue.
Any guidance would be most appreciated.

Note: This issue only affects my production installation of my rails app on a Ubuntu 14.04 LTS

**Comment by seuros** [comment]
something/one is flushing the database(redis).

**Comment by mperham** [comment]
Make sure Redis is not open to the public, listening on 0.0.0.0.
