### ISSUE TITLE
Stuck enqueued workers

### ISSUE THREAD

**Issue by ancv1990** [mperham/sidekiq#2902]
Hi @mperham, I got problem when workers process jobs, the workers get stuck and cannot finish. 
Here is the TTIN output:
[TTIN](https://gist.github.com/ancv1990/4a733d9265bb1f004e27#file-ttin-txt)

And here is log of sidekiq.log:
[https://gist.github.com/ancv1990/c32faaf90601f874535c](https://gist.github.com/ancv1990/c32faaf90601f874535c)

Please help me.
Thanks,

**Comment by mperham** [comment]
Your network and/or Redis is performing miserably.  Verify Redis isn't out of memory and the network is ok.

**Comment by mperham** [comment]
And you're running **really** old gem versions.  Upgrade.

**Comment by ancv1990** [comment]
Thanks @mperham for checking my problem. 
Can you tell me how to verify if redis is out of memory and how to check network is ok or not

And now if I upgrade redis to latest version, what should I notice so that it does not make any break to our system?

Thanks

**Comment by mperham** [comment]
Those questions are too broad; I can't teach you devops.

**Comment by ancv1990** [comment]
Thanks @mperham
