### ISSUE TITLE
Incorrect "Sidekiq::Client.via is not re-entrant" error

### ISSUE THREAD

**Issue by junghlee90** [mperham/sidekiq#2905]
I think the conditional statement here needs to be modified:

lib/sidekiq/client.rb line 110
`raise RuntimeError, "Sidekiq::Client.via is not re-entrant" if x = Thread.current[:sidekiq_via_pool] && x != pool`

the above statement is equivalent to:

`raise RuntimeError, "Sidekiq::Client.via is not re-entrant" if x = (Thread.current[:sidekiq_via_pool] && x != pool)`

The RuntimeError is raised when you are using Sidekiq::Client.via with the same pool, but at the time of evaluation x will be unassigned.

**Comment by mperham** [comment]
Can you send a PR with the fix and a test?

**Comment by Abhimaropost** [comment]
Hi, 
Is there any patch for same. Because it is not resolved.

**Comment by mperham** [comment]
You can refactor your code to not be re-entrant.

```ruby
Sidekiq::Client.via(pool) do
  AWorker.perform_async(...)
end
```

is the same as this:

```ruby
AWorker.set(pool: pool).perform_async(...)
```
