### ISSUE TITLE
How do you kill "busy" jobs ?

### ISSUE THREAD

**Issue by nimashariatian** [mperham/sidekiq#2907]
Hi guys,
I apologize if this question has been asked before, I looked all over the internet and couldn't find a straight answer.

We have a situation where we are using Sidekiq for some background computation.
But a user can "opt-out" anytime during the process.

At that point, the Job is no longer in the Queue as it is already being executed, so job.delete wont work.
Is there a way to kill the running job without killing the sidekiq process? 
If we kill the sidekiq process, it will kill all the running jobs which obviously doesn't work.

I am curious to know how other people are approaching this issue..

Any help would be greatly appreciated!

**Comment by mikegee** [comment]
I think your job should check to see whether or not the result is wanted when it is finished doing its work.

**Comment by nimashariatian** [comment]
thanks @mikegee , i guess my question was is there a way to notify the job to "bail out" to save wasted cpu computing power?

**Comment by mikegee** [comment]
The job doesn't have to wait until it is finished. It could periodically check if the work it is doing is still needed.

**Comment by nimashariatian** [comment]
For anyone interested, i found a solution to this. 
You can use  `Sidekiq::Client.push` to push a worker that would loop through the threads and kill the given thread ID, you can find the thread_id via `Sidekiq::Workers.new`

**Comment by mperham** [comment]
There's a reason Sidekiq does not provide this functionality: it's a terrible idea.  Using Thread#kill can have unpredictable effects on your application.  Your job **must** poll to see if it should exit early.

**Comment by nimashariatian** [comment]
@mperham  after speaking with my lead engineer, we are not going to kill the thread as you suggested. 
so you are correct on that end. 
however, we would love to hear any ideas regarding how to implement this. 
would it make sense to store to "job to cancel id" in redis and poll for it inside the worker?

**Comment by mperham** [comment]
It's a FAQ: https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job

**Comment by darkslategrey** [comment]
@nimashariatian I used this code from the web dashboard to cancel one job https://github.com/mperham/sidekiq/blob/bbf8c328338d1764133e744870317214529d282c/lib/sidekiq/web/application.rb#L44

**Comment by nimashariatian** [comment]
thank you @darkslategrey  !

**Comment by adiakritos** [comment]
> There's a reason Sidekiq does not provide this functionality: it's a terrible idea. Using Thread#kill can have unpredictable effects on your application. Your job **must** poll to see if it should exit early.

I read the FAQ and was unclear what to expect after running the `cancel!` method, or why there was a `cancelled?` method. Your insight here makes that FAQ much clearer. It would be helpful to add that to the FAQ.

This now brings up some new questions. How often does Sidekiq poll for theads to kill? Can we configure how often it does this? Can we trigger a poll to speed up the process in the event a process is doing something very damaging?

**Comment by mikegee** [comment]
> How often does Sidekiq poll for theads to kill?

Sidekiq doesn't poll for threads to kill. The code in the wiki doesn't do anything like that. The application code is responsible for determining if a job was cancelled.

**Comment by adiakritos** [comment]
> > How often does Sidekiq poll for theads to kill?
> 
> Sidekiq doesn't poll for threads to kill. The code in the wiki doesn't do anything like that. The application code is responsible for determining if a job was cancelled.

Got it. 

What is the expected behavior after a worker has been set to cancelled, assuming the job is currently in a busy state? 

Will it simply wait for the worker to finish without eventually interrupting the worker?

What exactly does setting worker to cancelled do?

**Comment by birthdaycorp** [comment]
> > How often does Sidekiq poll for theads to kill?
> 
> Sidekiq doesn't poll for threads to kill. The code in the wiki doesn't do anything like that. The application code is responsible for determining if a job was cancelled.

this is super confusing. one site says the worker should cancel itself, another says the application should cancel the worker, and the wiki is anything but clear on how to implement any of this. that code doesn't cancel the job, it just executes the background worker. calling `Worker.cancel! jid` in a model elsewhere just gives a `undefined local variable or method 'jid'`. 

how can i access that jid in my model?

**Comment by mperham** [comment]
@birthdaycorp I'm sorry you are frustrated but this will happen with any new system you learn.  Open source comes without support and no one wants to help a jerk. I'd suggest you adopt a less judgmental, more patient attitude ("Y is super confusing" -> "I would find X useful", "how do I do Z?").  Take a walk, get some sleep.

1. The wiki code works fine, cancelled jobs return from perform() early so they do nothing.
2. https://www.rubydoc.info/github/redis/redis-rb/Redis:setex
3. `jid = YourWorker.perform_async(...args...)`

**Comment by nimashariatian** [comment]
@mperham just wanted to chime in and say i really appreciate all the hard work you've been putting in this. some of us are really thankful !

**Comment by Tensho** [comment]
@mperham Thank you, Mike, for your incredible work 🙇   To understand any concurrent system is always hard and usually require to shift your mind from application to system level. Build any concurrent system even harder. Before I dove to Sidekiq internals I read the book ["Advanced Programming in the UNIX Environment"](https://www.amazon.com/Advanced-Programming-UNIX-Environment-3rd/dp/0321637739), which I recommend to every developer.

**Comment by 976590355** [comment]
> For anyone interested, i found a solution to this.
> You can use `Sidekiq::Client.push` to push a worker that would loop through the threads and kill the given thread ID, you can find the thread_id via `Sidekiq::Workers.new`
> 
> The worker to kill the thread would look something like:
> 
> ```
> class ThreadKillerWorker
>   include Sidekiq::Worker
>   def perform(tid)
>     Thread.list.each {|t|
>       if t.object_id.to_s(36) == tid
>         t.exit
>       end
>     }
>   end
> end
> ```

it's useful

**Comment by nimashariatian** [comment]
@976590355 the solution worked at the time but it's not a good one anyway. there are better one's suggested in the thread and now there's a FAQ for it as well: 
https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job

**Comment by 976590355** [comment]
@nimashariatian 
thank you for reply__

**Comment by Adarsh6xutz** [comment]
> @976590355 the solution worked at the time but it's not a good one anyway. there are better one's suggested in the thread and now there's a FAQ for it as well: https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job

Hi @nimashariatian, as per your original question the job was already in execution so are you checking cancelled? many time in your code?
as the user can opt out any time may be just after the first check of cancelled?.
