### ISSUE TITLE
Scheduled jobs are disappearing after being enqueued

### ISSUE THREAD

**Issue by DrMavenRebe** [mperham/sidekiq#2908]
First my stack & config: 

* ruby 2.1.7
* rails 3.2.22
* sidekiq 3.0.0
* docker containers forked form [Passenger-Full]([https://hub.docker.com/r/phusion/passenger-full/)

**Sidekiq Gems**
```
    sidekiq (3.0.0)
      celluloid (>= 0.15.2)
      connection_pool (>= 2.0.0)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq-failures (0.4.1)
      sidekiq (>= 2.16.0)
    sidekiq-middleware (0.3.0)
      sidekiq (>= 2.12.4)
    sidekiq-status (0.5.0)
      sidekiq (>= 2.7, < 3.1)
    sidekiq-throttler (0.4.1)
      activesupport
      sidekiq (>= 2.5, < 4.0)
```

**Sidekiq Config**
```
require 'sidekiq'
require 'sidekiq-status'
require 'fooda/async_logger'

Sidekiq.configure_server do |config|
  redis_url = ENV['REDIS_URL']
  raise "define environment varialbe REDIS_URL" if redis_url.nil? or redis_url.empty? 
  config.redis = { url: "#{redis_url}", namespace: "myapp_#{Rails.env}" }

  # Allow Rails.logger.<log_level> calls to output to the async logs when accessed via the worker
  Rails.logger = Sidekiq.logger

  config.server_middleware do |chain|
    chain.add Sidekiq::Throttler, storage: :redis
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
    chain.add Fooda::AsyncLogger
    chain.add Fooda::AsyncFailureHandler
  end

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq.configure_client do |config|
  redis_url = ENV['REDIS_URL']  
  raise "define environment varialbe REDIS_URL(#{redis_url})" if redis_url.nil? or redis_url.empty? 
  config.redis = { url: "#{redis_url}" , namespace: "myapp_#{Rails.env}" }

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end
```

***

I've been seeing this behavior for about a week now. Twenty jobs or so will be scheduled with a `perform_at` method and be correctly sitting in the sidekiq schedule tab. When the time comes to fire them off, about ~95% of them execute on time. I see the results in the database and their jid and log calls in my log aggregator but 0-2 will not fire. The missing jobs do not show up in the log aggregator, they do not perform their task. 

If we manually trigger the missing job with a perform_async, everything goes well and the job completes. 

I have 8 machines running 1 docker container with 25 workers per container. The cluster is namespaced and the different environments are using different redis clusters. Could this be a [sidekqi scheduler reliability issue](https://github.com/mperham/sidekiq/wiki/Reliability)? Is there a chance a rouge staging process is picking up production jobs? 

Any thoughts or comments are greatly appreciated.

**Comment by mperham** [comment]
You're using an old sidekiq with dozens of bugs fixed. Please upgrade to 3.5.4.

**Comment by DrMavenRebe** [comment]
beautiful. I'll check that and report. Thanks!

:smoking: :fish:

**Comment by Charizard** [comment]
@mperham I have a similar issue with sidekiq `4.1.1` and I am consistently able to replicate it.

I have a simple worker
```
  1 class MixpanelEventWorker
  2   include Sidekiq::Worker
  3
  4   def perform
  5     puts "Hi how are you?"
  6   end
  7 end
```
In rails console,
```
> MixpanelEventWorker.perform_async();MixpanelEventWorker.perform_async()
```
Ideally the job needs to be run 2 times, this is working as expected in local where the redis-server is running in the local machine iteself. But in my staging (where the redis is a Elasticache cluster), the job is executed only one time.

I also tried downgrading to `3.5`. Still stays the same. My theory is that the network delay in accessing the redis-server is causing something to break in sidekiq.

Thanks for the awesome gem and the great work :smile:

**Comment by DrMavenRebe** [comment]
I'm also running on AWS with vanilla EC2 machines, the passanger-full docker image and 1-node ElasticCache.

**Comment by mperham** [comment]
@Charizard There are no known issues pushing jobs quickly.  It is possible for client-side middleware to stop a job push, especially any unique middleware you might be running.  Also, the "app" part of your Redis URL is wrong, Redis expects a database number there.

**Comment by Charizard** [comment]
@mperham Thanks for pointing it out, I will check the `app` part of the URL. But, one more update is that when I change the queue of the worker from default to something else, it seems to work stably :cry:

**Comment by DrMavenRebe** [comment]
For anyone that comes across this thread later, updating to sidekiq 4.1.2 did not solve the our disappearing job problem but upgrading to sidekiq pro with `timed_fetch` did. I think it has to do with the network hop between our separate web and sidekiq worker clusters.

Happy hunting and big thanks to @mperham. 

🚬 🐟

**Comment by jclif** [comment]
I'm seeing this issue in my docker setup as well.
