### ISSUE TITLE
Scheduling/Recurring jobs in Sidekiq 4

### ISSUE THREAD

**Issue by shakycode** [mperham/sidekiq#2909]
I'm currently on Sidekiq 3.5.1 using Sidetiq with a backported version of celluloid.  All is working well.  But we want to move away from this version to 4.0 for the performance gains.

My question is, we have several workers that fire every 2-3 seconds.  What is the best way to schedule recurring jobs with Sidekiq 4?  I'm not sure if sidetiq will work with it or not because of celluloid backporting.  There's also the clock_work gem which might work too.

How are you guys dealing with recurring workers and/or workers that need to run at a certain time every day/etc?

Sorry if this is not a true issue, just trying to figure out the best way to approach our upgarde.

**Comment by mperham** [comment]
I don't know of anything that will fire a job every few seconds.  Sidekiq Enterprise's cron support only goes down to minute granularity.  You can use Enterprise's [leader election](https://github.com/mperham/sidekiq/wiki/Ent-Leader-Election) feature plus your own hand-written loop to fire jobs as you wish.

**Comment by shakycode** [comment]
@mperham Thanks for the information.  I'll see what I can do to make this work.  Clock_work gem should do it.  I'd like to get Sidekiq enterprise but being in the startup world and running lean it's hard to afford with 100+ app instances.  Closing :)
