### ISSUE TITLE
priority queue

### ISSUE THREAD

**Issue by yatish27** [mperham/sidekiq#291]
how to add priority to a queue in sidekiq, so that the worker will check that queue first and then other queues

**Comment by rohandaxini** [comment]
Hello @mperham, Is this gem `sidekiq-priority` https://github.com/socialpandas/sidekiq-priority useful ?
Sometimes, we want to set priority as `high` or `low` for few jobs that we trigger from console but with same existing queues that we already defined as critical, high, medium, low.

Scenario - We have few queues defined in our app as critical, high, medium, low. Now our users use the app and it triggers few jobs that are queued in various queues as per priority - fair and good enough. Now we want to do some hot fix and trigger few jobs from console assuming all queues are empty at this moment. We trigger - say 10K jobs from console and they are queued in various queues that we defined by us in app, and being executed by Sidekiq. During this same time, our Live users performs some  operation in the app that results into 1K jobs. Now they are also queued behind the existing queue of 10K running jobs - in various queues. We want to give priority to User's jobs and next priority to console jobs that we manually triggered. In this case we think gem `sidekiq-priority` will be useful.
Your thoughts ?

**Comment by mperham** [comment]
```ruby
Sidekiq::Client.enqueue_to(:low, MyWorker, args...)
```

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L143

**Comment by rohandaxini** [comment]
@mperham actually in my case lets say Low queue is already having 10K jobs running that I executed via console. Now my users comes and triggers a functionality that in turn runs some jobs thru Low queue. Now I want preference to user's jobs in low queue and not my 10K jobs running via console that I already queued in Sidekiq. In such cases will that gem be useful ?

**Comment by mperham** [comment]
@rohandaxini That gem hasn't been touched in almost 2 years.  I wouldn't touch it.

When in doubt, run more Sidekiq processes.  This way you can process any backlog faster.

**Comment by rohandaxini** [comment]
Thanks for the suggestions @mperham Sure

**Comment by onetwopunch** [comment]
@mperham Love that you included this API. Quick question though, will using `Sidekiq::Client` override the `sidekiq_options` queue value if you have it set in the worker already? I have several workers designed for heavy processing for which I specify a `compute` queue in the `sidekiq_options`, but would like to elevate them to a separate queue under certain conditions. Just want to make sure this will work

**Comment by mperham** [comment]
@onetwopunch It will override.

**Comment by onetwopunch** [comment]
@mperham Awesome! Thanks for the quick response! :+1:
