### ISSUE TITLE
Unable to get JID from API

### ISSUE THREAD

**Issue by hobakill** [mperham/sidekiq#2911]
I thought this would be simple. I'm new to the API so bare with me if this is idiotic. I am unable to find a way to get the JID for jobs in, say, the Retry , Dead, and Scheduled queues. I don't see what I need here but maybe I'm missing something. Any help would be greatly appreciated:

https://github.com/mperham/sidekiq/wiki/API

**Comment by mperham** [comment]
The values in those sorted sets are JSON blobs; the API converts them to a normal Ruby object when iterating through it.

```ruby
rs = Sidekiq::RetrySet.new
rs.each do |job|
  puts job.jid
end
```

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L271

**Comment by hobakill** [comment]
A million thanks!
