### ISSUE TITLE
Why does Sidekiq::Client.new.push require an array for the arguments?

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#2915]
Doing something like

```
Sidekiq::Client.new.push('queue' => 'default', 'class' => "CopyImageWorker", 'args' => msg)
```

results in a msg must be an array error message. Easy enough to fix! :)

But we're enqueuing jobs in PHP with a 3rd party library. I've noticed it does enforce this restriction and whenever we pass an object as a json string sidekiq doesn't JSON.load() that object and our single parameter is a string instead of a ruby object.

I know the library should enforce the array but just curious if this is the cause of the weird behavior we're seeing.
Does sidekiq not use JSON.load() if the argument isn't an array?

**Comment by mperham** [comment]
Consistency.  The args are always an array.  Sidekiq will splat them into your worker:

```
[1,2,3] => def perform(a, b, c)
```
