### ISSUE TITLE
Configuration Symmetry 

### ISSUE THREAD

**Issue by sandstrom** [mperham/sidekiq#2916]
Sidekiq has been easy to setup this far. Very happy!

One thing that could be improved is the symmetry in configuration. For example, I had to use different syntax for server/client (see below).

```ruby
Sidekiq.configure_server do |config|
  config.redis = { :url => 'redis://my-redis:6379/0' }

  config.reliable_fetch! # Works! 
  config.reliable_scheduler! # Works!
end

Sidekiq.configure_client do |config|
  config.redis = { :url => 'redis://my-redis:6379/0' }

  # config.reliable_push! unless Rails.env.test? # Doesn't work
end

Sidekiq::Client.reliable_push! unless Rails.env.test? # Works!
```

**Comment by mperham** [comment]
Client and server blocks are mutually exclusive.  Only one will execute, depending on which process this is.  reliable_push is something we want to enable for both client and server.  The way to ensure that is to pull the config outside of those blocks.

**Comment by sandstrom** [comment]
@mperham Got it, thanks for clarifying! 

Perhaps a `configure_both` block would work? Would also make this (the sharing) more obvious — I didn't know.

Not trying to criticize, I like Sidekiq so I'm only spending time suggesting things because I'd like to help out.
