### ISSUE TITLE
Ghost process in the Processes section of the web UI

### ISSUE THREAD

**Issue by penso** [mperham/sidekiq#2917]
Sidekiq version: 4.0.1
Rails version: 4.2.5
Ruby version: 2.2.1

I have a process listed with: `Started: 2 months ago` but this process doesn't exist (I actually killed the server it ran on). Quiet or Stop doesn't work, how could I remove this process from the processes list?
![screen shot 2016-04-08 at 9 17 07 pm](https://cloud.githubusercontent.com/assets/7703/14394978/4fd44e9c-fdcf-11e5-8eaf-53eca24a091a.png)

**Comment by mperham** [comment]
Did you dump/restore any Redis data?  Looks like that process heartbeat lost its TTL and so sidekiq thinks it's always alive.

**Comment by penso** [comment]
I have not, I use a managed redis instance on AWS and didn't dump/restore.

**Comment by penso** [comment]
Btw I'd be happy to run a redis command to remove this manually, it bothered me for long enough :)

**Comment by mperham** [comment]
You can use srem to remove it. http://redis.io/commands/srem

**Comment by penso** [comment]
`srem "processes" "<id>"` worked. Thanks!
