### ISSUE TITLE
Mark process as Leader

### ISSUE THREAD

**Issue by benkruger** [mperham/sidekiq#2918]
## What
On startup have a process either be the leader or not be the leader via configuration.

## Why
We have a single instance of Redis but have multiple applications with different code bases consuming from the queue. 

Server A running code base A and server B running code base B. Both server A and B connect to our Redis instance. This is the functionality that is required. The issue we are having is that Server A always needs to be the leader. However, we have an issue that server B becomes the leader after that 20 seconds if a deploy is taking a long time or server A is down for whatever reason. I am in need of a way to make server A always the leader 100% of the time. This is because that is the server that my periodic tasks are in. So if server B becomes the leader because it is the only server running or first started then none of our cron run.

**Comment by mikegee** [comment]
Do these two applications really need to share the same redis? Perhaps they should have their own redis servers (or use redis-namespace).

**Comment by benkruger** [comment]
They do. Due to our dynamic environments, it is cost prohibitive to use multiple servers.

**Comment by mikegee** [comment]
I guess I meant to ask if these two applications really need to share the same redis database. Redis can be segmented in a few ways without running another server:
- running multiple redis processes on the same server
- using a non-zero redis database for one of the applications (http://www.rediscookbook.org/multiple_databases.html)
- using a namespace (https://github.com/resque/redis-namespace#redis-namespace)

Also, the leader is the process that enqueues the periodic job, not necessarily the one that runs it.

**Comment by benkruger** [comment]
I looked into both solutions. While the multiple database is good to know and useful for us in the future, it will not solve this issue do to our constraints. We need to peg one box as the leader. We are actually blocked on move sidekiq ent into production do to this. We are not able to utilize the cron component which was a big reason behind the paid upgrade.

**Comment by mperham** [comment]
@benkruger Avoiding machine and process specialization is the reason for the current design.  Specializing means adding operational complexity and SPOFs and Sidekiq's design tries to make the simple, robust design easy.  For tasks which must run on a particular machine, there's no reason why you can't use a mix of tools: use unix cron to enqueue jobs, e.g.
