### ISSUE TITLE
Sidekiq Pro removes Batch info after a job successfully done.

### ISSUE THREAD

**Issue by SamMolokanov** [mperham/sidekiq#2919]
Hello! 

I have got a couple of problems with Sidekiq Pro Batches. 

Our Gemfile.lock looks like 

```
    sidekiq (3.5.4)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sidekiq-cron (0.3.1)
      rufus-scheduler (>= 2.0.24)
      sidekiq (>= 2.17.3)
    sidekiq-pro (2.1.5)
      sidekiq (~> 3, >= 3.4.2)
    sidekiq-throttled (0.1.0)
      sidekiq (< 4)
```

The first problem is related to `Sidekiq::Rack::BatchStatus`: if method `call` falls to rescue exception it raises another error in rack linter `Rack::Lint::LintError: No Content-Type header found` because of `return [401, {}, [ex.message]]` - no Content-Type header given (I would suggest to put `"text/plain"` value or/and add exception handling with HTTP-error code). For example request to url `http://localhost:3000/batch_status/non-existent-batch-here.json` raises Rack::Lint error.

The second problem is a bit more complicated, related to short-polling Batch status feature described here [https://github.com/mperham/sidekiq/wiki/Batches#polling] (https://github.com/mperham/sidekiq/wiki/Batches#polling): after batch was successfully done, it removes statistic data from redis according to source code in file `sidekiq-pro-2.1.5/lib/sidekiq/batch/callback.rb:62`. How it happens - until a job is done we can receive proper batch status `is_complete: false...` but as soon as job get completed it removes status from redis and we cannot recognize that job is done via short-polling. 

Our workaround:

```
# import_worker.rb
class ImportWorker
  include Sidekiq::Worker
  sidekiq_options queue: :import

  # Wrapper around Sidekiq::Batch in order to return batch id
  def self.import(*args)
    Sidekiq::Batch.new.tap do |batch|
      batch.jobs { perform_async *args }
    end.bid
  end

  def perform()
  	# hard job here
  end
end
```

```
# imports_controller.rb
class ImportsController < ApplicationController
  def create
    bid = ImportWorker.import(import_params)
    render json: {bid: bid}, status: :created
  end
end
```

Backtrace is pretty simple:

```
2.2.3 :001 > bid = ImportWorker.import params
 => "PSKAGn1oBnqXwg"
2.2.3 :002 > batch = Sidekiq::Batch::Status.new bid
Sidekiq::Batch::NoSuchBatch: Couldn't find Batch PSKAGn1oBnqXwg in redis
	from /Users/sam/.rvm/gems/ruby-2.2.3/gems/sidekiq-pro-2.1.5/lib/sidekiq/batch/status.rb:45:in `load_data'
	from /Users/sam/.rvm/gems/ruby-2.2.3/gems/sidekiq-pro-2.1.5/lib/sidekiq/batch/status.rb:19:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /Users/sam/.rvm/gems/ruby-2.2.3/gems/railties-3.2.22.2/lib/rails/commands/console.rb:47:in `start'
	from /Users/sam/.rvm/gems/ruby-2.2.3/gems/railties-3.2.22.2/lib/rails/commands/console.rb:8:in `start'
	from /Users/sam/.rvm/gems/ruby-2.2.3/gems/railties-3.2.22.2/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

Here we actually have only single job per batch, just to use Batch status features to recognize that job is done without any 3rd-party tools.

Thanks for help in advance!

**Comment by mperham** [comment]
Both issues now fixed, will be in the next patch release.

**Comment by SamMolokanov** [comment]
@mperham I am very sorry to write here again, but the problem with removing batch status from redis after a batch successfully done seems still exists. We have updated our sidekiq-pro version to 3.2.1. 

This is a code snippet from the gem source code:

```
# sidekiq-pro-3.2.1/lib/sidekiq/batch/callback.rb : 26

def success(status, queue)

  # ......
  # omited
  # ......

  Sidekiq::Batch.redis(bid) do |conn|
    conn.pipelined do
      conn.del "b-#{bid}",
               "b-#{bid}-failinfo",
               "b-#{bid}-notify",
               "b-#{bid}-cbsucc",
               "b-#{bid}-success",
               "b-#{bid}-complete",
               "b-#{bid}-jids"
      conn.zrem('batches'.freeze, bid)
      conn.publish("batch-#{bid}", '$')
    end
  end
end
```

As you can see, this code removes a batch info from redis and publish the notification to redis channel.  The problem here that we cannot use a polling feature to fetch batch status as described here - https://github.com/mperham/sidekiq/wiki/Batches#polling - when batch done, we'll receive `Sidekiq::Batch::NoSuchBatch` as it never exists before.

Can we keep the statistic in redis, since it has 30-days expiration anyway?

**Comment by mperham** [comment]
You are correct, there's no safe way to poll for batch success today.  It's possible I will remove the poll feature as it cannot be implemented correctly anymore.  You can workaround by building your own polling mechanism via a success callback, like so.

```ruby
# create batch
batch = Sidekiq::Batch.new
Sidekiq.redis { |c| c.setex("poll-#{batch.bid}", 7*24*60*60, "started") }
batch.on(:success, self)
batch.jobs do
  # define jobs
end

def on_success(status, options)
  Sidekiq.redis { |c| c.setex("poll-#{status.bid}", 7*24*60*60, "done") }
end

def poll(bid)
  loop do
    status = Sidekiq.redis {|c| c.get("poll-#{bid}") }
    raise "No such batch" unless status
    break if status == "done"
    sleep 1
  end
end
```

**Comment by SamMolokanov** [comment]
Thanks for the answer!
