### ISSUE TITLE
Jobs remain stuck in queue when process restarts quickly and maintains pid

### ISSUE THREAD

**Issue by SamSaffron** [mperham/sidekiq#2920]
Quite a few times we have notice a "stuck" sidekiq. All the jobs in the queue appear to be "stuck" in a running state forever.

I managed to isolate what is causing it today and would like some tips on how to correct it. 

It appears the "identity" of job's owner is determined based on `hostname:PID` 

If you hang-up a processor Sidekiq  "detects" that a `hostname:PID` is not around about 20-30 seconds after its is terminated. When that happens it will clear all the jobs it thought that `hostname:PID` owned.

**However** in a docker world we are able to do very quick restarts that **very often** maintain the same `hostname:pid` after restart before Sidekiq detects that the old job processor died. 

This sequence leaves us with jobs that appear to be running forever.

This issue has popped up many times on many customers and internally, but we never really picked up on the reason till now. 

I guess my questions

1. Can we amend sidekiq so it uses an additional piece of data for job processor identity, eg: `hostname:PID:guid`  ? 

2. Can we improve our shutdown sequence to cleanly clear the currently running jobs? 

3. Any other ideas? (timeout can work here, but it will have a very delayed effect) 

Note: we can not use any of the Sidekiq professional or enterprise features as we need the fix to apply to all Discourse open source users.

**Comment by mperham** [comment]
A process's identity [includes a nonce](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/util.rb#L45) to handle just this case.  I can't find a case where this nonce is not included.  The heartbeat [uses it here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/launcher.rb#L121) to keep the process data alive in Redis.

**Comment by SamSaffron** [comment]
the heartbeat works fine, I think its the keying of the actual jobs in the redis "running" queue

**Comment by mperham** [comment]
Please be precise -- I don't know what a "running" queue is.

During the heartbeat, the state of each working thread is pushed to Redis [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/launcher.rb#L88) and the key is based on the process identity, with its nonce.

**Comment by SamSaffron** [comment]
Sorry about this, yes I just reviewed the implementation and my bug report really is not making sense. 

I will see if I can do anything to consistently repro the issue and let you know, closing for now.
