### ISSUE TITLE
Sidekiq Pro: 11 minute delay before "started processing" when lots of tasks enqueued

### ISSUE THREAD

**Issue by dacoinminster** [mperham/sidekiq#2921]
I previously I asked about long delays starting up here:

https://github.com/mperham/sidekiq/issues/2880

We recently had this happen again, and I have some more information about this problem:

1) Redis slowlog does not show any slow requests at all
2) Normal sidekiq startup takes about 1.5 minutes
3) Sidekiq startup seems to take a lot longer when there are a ton of tasks enqueued (in this case, ~50k tasks enqueued meant Sidekiq took 11 minutes to start processing them)
4) During this long startup, Sidekiq dashboard shows all the the tasks enqueued, but none running, so Sidekiq can clearly see the tasks, but is not running them for some reason
5) Redis logs show no writes during this period, but writes take off again as soon as Sidekiq starts processing. Presumably the writes are sidekiq marking tasks as complete.

Our environment is Sidekiq Pro on Heruku running Redis Cloud.

Do we need to just be careful not to restart Heroku when there are a ton of tasks enqueued? Is that just an unavoidable consequence of how Sidekiq works, or is there something we can do about it?

Thanks!

**Comment by mperham** [comment]
The size of queues should have nothing to do with Sidekiq's startup speed.  I suspect you have something in your app that is poorly written/designed running on startup.  How long does it take for a Rails console in the same environment to start?  What 3rd party gems are you using?

**Comment by dacoinminster** [comment]
Rails console takes ~5 seconds to launch. We're using a lot of 3rd party gems - I'd rather not post all of them here - do you want me to email them to you?

**Comment by mperham** [comment]
Email or gist is fine.

Since console is fast, I also want to see any `Sidekiq.configure_server` blocks you have in your app.

**Comment by dacoinminster** [comment]
That led me to what is probably the problem. There's a command in Sidekiq.configure_server which builds a big cache for the sidekiq jobs to use. It's not clear why sometimes it takes many minutes and sometimes it takes less than 2 minutes, but I bet that's where the problem is.
