### ISSUE TITLE
How to limit size of sidekiq log?

### ISSUE THREAD

**Issue by mystdeim** [mperham/sidekiq#2922]
I have a rails app with sidekiq. Sidekiq writes log in log/sidekiq.log and I have a such config:
> ---
> :concurrency: 10
> :logfile: ./log/sidekiq.log
> :queues:
>   - [import, 10]
>   - [utils, 10]
>   - [cache, 1]
>   - [notify, 1]

**Comment by seuros** [comment]
What do you mean by  limit the log ?

**Comment by mystdeim** [comment]
limit of size log

**Comment by seuros** [comment]
You can use logrotate for that.

**Comment by mystdeim** [comment]
How to use it? In my Rails app I could do just this:  ActiveSupport::Logger.new(config.paths['log'].first, 1, 100_000_00)

**Comment by aprescott** [comment]
If your logs are too verbose, you could set the logging level higher:

```ruby
# config/initializers/sidekiq.rb
Sidekiq::Logging.logger.level = Logger::WARN
```

**Comment by mperham** [comment]
You can do this but @seuros is right, `logrotate` is the correct solution.

```ruby
Sidekiq::Logging.logger = ActiveSupport::Logger.new(config.paths['log'].first, 1, 100_000_00)
```

**Comment by shamimevatix** [comment]
Sidekiq::Logging.logger = ActiveSupport::Logger.new(config.paths['log'].first, 1, 100_000_00)
doesn't work anymore in ruby 2.7.2. rails 7.0.3

using gem 'sidekiq', '~> 6.4', '>= 6.4.2'

**Comment by Lukom** [comment]
I've configured this way:

```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  # ...
  logger_target = STDOUT.isatty ? STDOUT : 'log/sidekiq.log'
  config.logger = Sidekiq::Logger.new(logger_target, 5, 20.megabytes, level: :info).tap do |log|
    log.level = Logger::INFO
    log.formatter = Sidekiq::Logger::Formatters::Pretty.new
  end
end

```
This way:
- the log is rotated - 5 files / 20 megabytes each
- output is written to console if sidekiq is running in interactive console and to log file otherwise
