### ISSUE TITLE
Redis choice

### ISSUE THREAD

**Issue by yangsr** [mperham/sidekiq#2923]
There are two Redis service in my company, one is single node redis, and the other is distributed Redis.

When I use the single node Redis service, everything works OK.

But when I use the distributed Redis, as I type `bundle exec sidekiq`，the terminal tells me `disconnected`.

After debugging, I find the distributed Redis in my company does not support `brpop` and `info` command. When sidekiq calls `info` or `brpop`， the agent layer would cut off the connection of the distributed Redis.

So, is it necessary to use distributed Redis?

Can I use `rpop` command instead of `brpop` command?

Thx.

**Comment by mperham** [comment]
Blocking is critical to get good efficiency so BRPOP is required.  You should use single node Redis.
