### ISSUE TITLE
`Processed` counter counts failed jobs

### ISSUE THREAD

**Issue by bikramwp** [mperham/sidekiq#2928]
Using v4.1.1 on Ruby 2.3.0.

I noticed that the `Processed` count in the Web UI is incremented for failed jobs.

I would've expected that `Processed` jobs only incremented for jobs that 'succeeded'.

I'm not sure if this is a v4 issue or it is by design?
If it is by design, is adding a `Succeeded` counter acceptable to you?

The commit below shows that `PROCESSED.increment` is called in an `ensure` block and is always incremented: https://github.com/mperham/sidekiq/commit/752bfc6d8b21058222655cd780d4295b6c61ce8e#diff-9377a003db0befb7e1a28504dc97254fR127

**Comment by mperham** [comment]
It's been that way from day one, by design.

**Comment by bikramwp** [comment]
So is adding a `Succeeded` counter acceptable to you? I would make a pull request for it

**Comment by mperham** [comment]
No thanks.

**Comment by bikramwp** [comment]
Is there a already a built-in way to get at the count of jobs that did not fail?

**Comment by mperham** [comment]
See the API. Processed - failed.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/API#stats
