### ISSUE TITLE
Rails 5 integration with Sidekiq monitoring

### ISSUE THREAD

**Issue by fertapric** [mperham/sidekiq#2931]
I'm not sure if this is even an issue or if it should be reported here, but I thought it would be nice to share it.

Rails 5.0.0.beta3 (and probably the upcoming Rails 5.0.0) depends on [rack ~> 2.x](https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/actionpack/actionpack.gemspec#L24) meanwhile Sinatra requires versions of rack ~> 1.x. Requiring both dependencies produces:

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      railties (= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
        actionpack (= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
          rack (~> 2.x)

    sinatra (~> 1.4.6) was resolved to 1.4.6, which depends on
      rack (~> 1.4)
```

**Comment by mperham** [comment]
The list of necessary gems is in the issue:

https://github.com/mperham/sidekiq/pull/2457#issue-97138263
