### ISSUE TITLE
Feature Request: Sidekiq Unique Jobs, check if job exists w/ args already

### ISSUE THREAD

**Issue by ChaoticBoredom** [mperham/sidekiq#2932]
W/ Unique jobs, it would be nice if instead of attempting to queue the job, and then seeing it not go through, we could check to see in advance if the job will conflict/job w/ args exists. The main use case that I could see this supporting is being able to prevent a user from believing they can queue a job when it will not go through due to an existing job w/ that unique arg. It's not a full status check, but a shortcut to see in advance.

**Comment by mperham** [comment]
Thanks for the reminder, done!  The RDoc:

```ruby
      # Check to see if the unique lock is currently present
      # for the given (queue, klass, args) tuple.  Keep in mind that
      # the args must be *exactly* what would be deserialized
      # from JSON so no symbols, objects or non-JSON datatypes.
      #
      # Note this method IS RACY.  It can return false and then another
      # thread take the lock microseconds later - treat it as advisory only.
      #
      # Returns truthy if the unique lock is present.
      #
      def self.locked?(queue=nil, klass, args)
 ```

Example:

```ruby
    locked = Sidekiq::Enterprise::Unique.locked?(SomeWorker, [1,2,3])
    locked = Sidekiq::Enterprise::Unique.locked?('foo', SomeWorker, [1,2,3])
```

I'll release 1.2.2 in a few days with this feature in it.

**Comment by ChaoticBoredom** [comment]
Awesome! Thanks for doing that, sorry about forgetting to create the issue until now
👍
