### ISSUE TITLE
Feature Request: Disable job time logging

### ISSUE THREAD

**Issue by JadedEvan** [mperham/sidekiq#2933]
Thinking it would be nice to expose some configuration to enable or disable output for job timing. In non-production environments job timing represents a majority of the output. Being able to disable this via a configuration setting would make debugging / replaying tasks much easier. Even in production environments we're not typically concerned with job timing, as we often have other metrics that let us know if we have very long-lived processes. Would love to cut down on the noise!

**Comment by mperham** [comment]
You can remove the logging middleware:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove Sidekiq::Middleware::Server:Logging if Rails.env.development?
  end
end
```
