### ISSUE TITLE
Sidekiq Process Monitoring in Container

### ISSUE THREAD

**Issue by ccastan1** [mperham/sidekiq#2936]
I'm running a single Sidekiq process on a container and I need a way to do a health check. Is there some tcp endpoint to query?

**Comment by mikegee** [comment]
I'm not sure such an endpoint exists. Sidekiq has an optional web interface that could be scraped, I suppose.

Where I work, we expose various aspects of the application's health via [pinglish](https://github.com/jbarnette/pinglish). One item is the number of enqueued sidekiq jobs. We alert if that number gets too far from zero. That indicates Sidekiq's health indirectly, but more inline with the business impact of an unhealthy Sidekiq.

Our infrastructure team also uses [Shinken](http://www.shinken-monitoring.org/) to monitor each host for the appropriate number of Sidekiq worker processes, but I'm not as familiar with that part.

**Comment by mperham** [comment]
What does a health check look like, do you have any documentation?  Sidekiq isn't a network service - it doesn't open any listening sockets.

**Comment by ccastan1** [comment]
We're using marathon to manage docker containers and it has a health check ping such as 
```
[
  {
    "path": "/health_check",
    "protocol": "HTTP" 
  }
]
```
But launching sidekiq as a service container has presented problems with monitoring. I'm able to do something like to get it to pass but would like to have bettter monitoring in place. 
```
[
   {
    "protocol": "COMMAND",
    "portIndex": 0,
    "command": {
      "value": "ps ax | grep -v grep | grep sidekiq > /dev/null"
    }
] 
```

**Comment by mperham** [comment]
That type of health check makes sense for a web service, where you want to ensure the port is open and requests are routing.  It makes less sense for Sidekiq: the workers could be locked up but the health check return 200 all day.  Your ps command is just as useful.  As @mikegee pointed out, really you want to monitor your queue sizes and ensure they aren't backing up.

**Comment by phlegx** [comment]
@mperham Facing a similar problem with Rancher. Rancher offers health checks to a (web) service docker container. In case it is not healthy anymore (TCP or HTTP check), Rancher spins up a new container on a different host.

The Web interface input fields in Rancher do look like that:

![screenshot from 2017-12-04 13-28-24](https://user-images.githubusercontent.com/111506/33553031-635971b8-d8f7-11e7-9fcc-e27940a3bf69.png)
![screenshot from 2017-12-04 13-28-12](https://user-images.githubusercontent.com/111506/33553032-6372a93a-d8f7-11e7-8b65-50823c2294e5.png)

I know that Sidekiq is not a network service. But it would be really nice if with Sidekiq one could optionally for health checks  bring up a web endpoint and/or if I could tell to Sidekiq to simply open a Port.

**Comment by jcomeaux** [comment]
I totally agree with @phlegx ...@mperham 's comments are entirely correct unless you factor in the huge popularity of running everything in containers...and they sometimes die...and the scheduler needs to know :)

**Comment by mikegee** [comment]
Perhaps a Sidekiq plug-in can do this? I imagine it could be as simple as returning http 200 unconditionally, where failure to connect implies the service is unhealthy.

**Comment by Monte9** [comment]
Has anyone found a workaround for this use case yet?

I am running into the same issue where I have deployed sidekiq in a docker container and need it to respond to `/alive.txt` endpoint for Marathon to consider it "alive" and not kill the instance.

**Comment by mikegee** [comment]
@Monte9 it looks like Marathon supports [running arbitrary commands](https://mesosphere.github.io/marathon/docs/health-checks.html). Perhaps check if Sidekiq is healthy by looking at the output of `ps`.

**Comment by Monte9** [comment]
Thanks for the response @mikegee! I was able to find a workaround in my specific case.

Basically I had a Docker container that was running sidekiq, and what I ended up doing was before I ran sidekiq, I started a simple python web server in the background that just returned 200 for the `alive.txt` endpoint. That way, when Marathon hit my sidekiq docker container, it got the alive reponse as needed.

**Comment by mahmoudawadeen** [comment]
@mperham Just thinking out load here, what about a service that connects to redis checks the heartbeat of all the existing sidekiq processes (using the sidekiq api)? Of course then it would need to know about the expected number of sidekiq processes (containers) Assuming that if the process is having a heartbeat it's alive and can process jobs.

**Comment by mperham** [comment]
Never used it but possibly relevant: https://github.com/arturictus/sidekiq_alive
