### ISSUE TITLE
How to launch independent workers(threads) for specific queue(s) ?

### ISSUE THREAD

**Issue by gihnius** [mperham/sidekiq#2937]
How can I have 1 or more workers only to process a specific queue ?

**Comment by mikegee** [comment]
Check out the docs: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues

**Comment by gihnius** [comment]
@mikegee I was not clear.
For example, sidekiq launch 20 threads after started up, and there are queues called: 'critical', 'normal', 'low'.
I want to allocate 10 threads of the 20 always to process queue 'critical', and the remaining threads for queue 'normal' and 'low'.

**Comment by mperham** [comment]
You can't do this with Sidekiq out of the box.  Look into Related Projects. https://github.com/mperham/sidekiq/wiki/Related-Projects#queue-limits
