### ISSUE TITLE
Sporadic nil models

### ISSUE THREAD

**Issue by himberjack** [mperham/sidekiq#2938]
I am running sidekiq jobs on a few models (ARs). Sometimes, sporadically, I am getting exceptions of nil models. That is, the models (which can be very old in the DB) are nil. I have IF conditions before the job to allow only when NOT nil, the code passes, but sometimes it gets the nil somewhere in the code.

I do not have reaping policy (using the default) in the database.yml, thus I am not sure why this is happening.

When I am retrying the jobs (even after a few seconds) - they succeed.

What can cause this break inside the job???

**Comment by mikegee** [comment]
I can't imagine how this would be a Sidekiq bug. Perhaps post your worker code to StackOverflow?

**Comment by mperham** [comment]
Sounds like an issue between AR and your app code.
