### ISSUE TITLE
ephemeral_hostname vs. timed fetch, and a question on the timeout handling

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2939]
I'm looking at moving a handful of apps that use Sidekiq Pro away from reliable fetch, because they've been moved over to container environments and their hostnames are not consistent across deployments.

I initially thought that it would be a case of switching to the new timed fetch algorithm, but then noticed that [the Pro 3.0 upgrade notes mention an `:ephemeral_hostname` option](https://github.com/mperham/sidekiq/blob/e9fb6c25eb81748b84abf2d5bdc7e4c38fc4ecbc/Pro-3.0-Upgrade.md#whats-new).

I can't seem to find any documentation on what `ephemeral_hostname: true` does. How does it differ from `timed_fetch`?

Related: Some of the applications have jobs that inherently take several minutes to complete. I'm unclear on how this would work when using `timed_fetch`. If a Sidekiq process is actively working on a job that exceeds the timed fetch timeout period, does the algorithm account for the fact the Sidekiq process is still working on it? For example, if the timeout is 10 minutes, is there a difference between: (A) actively working on a job for over 10 minutes; and (B) the Sidekiq process crashing, then 10 minutes elapsing? The wiki currently says:

> If the job execution is not finished and acknowledged by the Sidekiq process within that timeout period, the job can be pushed back onto the queue for another process to pick up.

If (A) doesn't differ from (B), I think this would stop us using timed fetch; it seems like jobs either wouldn't fully finish executing or they'd overlap indefinitely as replacement jobs come in.

I also can't seem to find a documented way to configure the timed_fetch timeout period. Is it different from the timeout configured for `-t` and receiving a `TERM` signal?

**Comment by mperham** [comment]
A does not differ from B.  Sidekiq cannot tell the difference between a thread that is working hard for 15 minutes and a thread that has been deadlocked for 15 minutes.

`config.timed_fetch! 3600 # one hour default`

**Comment by mperham** [comment]
ephemeral_hostname was a hack to get reliable_fetch to sort of work in containers and Heroku.  It's deprecated now and so undocumented.

**Comment by aprescott** [comment]
Thanks for the quick reply! We'll weigh up a sensible threshold. (And then I'll probably forever worry about exceeding it. :))

**Comment by mperham** [comment]
You could use process(es) using standard fetch to process long jobs from a special queue.  Use reliability with your fast, transactional jobs.
