### ISSUE TITLE
Connection Timeout Error

### ISSUE THREAD

**Issue by AlexandruCD** [mperham/sidekiq#2943]
Hello,

I am having some troubles with sidekiq, and after I tried some things, I've decided to ask here.
I receive that error:
`ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds (waited 5.000166496 seconds). The max pool size is currently 5; consider increasing it.`
Ruby on Rails 3, Sidekiq version 2.17.7, mysql.
Database pool is 5.
Sidekiq settings looks so:
```
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 5
:timeout: 30
:logfile: ./log/sidekiq.log
:queues:
  - [high, 4]
  - [medium, 3]
  - [default, 2]
  - [low, 1]
```

I have also tried with concurrency 3. Also sometimes I receive Redis Timeout, but I am not sure they are linked. Hosting on Amazon.

**Comment by dmitry** [comment]
You have to increase database pool size to `sidekiq_concurrecy + 2`.

**Comment by mperham** [comment]
> You have to increase database pool size to sidekiq_concurrecy + 2.

That's not true.  Sidekiq's internal threads never use ActiveRecord so they don't need a connection.  pool size == concurrency should be fine.

**Comment by AlexandruCD** [comment]
Thanks, mpherham. What you think it may the problem? The airbrakes are thrown in the context of the job's classes that are including Sidekiq::Worker. And ofc, here i have AR querys.

**Comment by dmitry** [comment]
Check out MySQL for the `max_connections` and your number of connections when the exception is thrown, decrease `reaping_frequency` to lower than 5 (once you find it solves your issue, increase it again, as it could decrease performance of application).

**Comment by mperham** [comment]
pool exhaustion is always due to app code or a gem, possibly if you are using your own Threads.  There's no Sidekiq issue here.

**Comment by shivabhusal** [comment]
I forgot to set `REDIS_POOL_SIZE` when I set it, the error was gone
