### ISSUE TITLE
Question: Global start-stop event

### ISSUE THREAD

**Issue by vnazarenko** [mperham/sidekiq#2945]
Hi, we are using sidekiq with some long-running jobs. This jobs has ability to shutdown gracefully and resume from stopped place. We have 10 servers with 2 processes on each server, and during deploy all tasks are stopped. So after deployment is finished, we need to run some 'bootstrap' script which will prepare some data and start corresponding tasks. Now I use   config.on(:startup) section in initializer, 
but it works for each started process, and even when last process is not yet stopped, first has been already started. So what is the best way to handle 'one' for all processes on all server callbacks?

**Comment by dmitry** [comment]
What about using `:shutdown` callback to mark a flag so newly started jobs could continue to work?

**Comment by mperham** [comment]
Sidekiq Enterprise has the notion of a 'leader' process:

```ruby
Sidekiq.configure_server do |config|
  config.on(:leader) do
  end
end
```

That block will run every time a process is newly elected.

https://github.com/mperham/sidekiq/wiki/Ent-Leader-Election

**Comment by vnazarenko** [comment]
Thank you )
