### ISSUE TITLE
Running exec() in a Sidekiq Worker causes Sidekiq to quit

### ISSUE THREAD

**Issue by matisoffn** [mperham/sidekiq#2946]
I have a binary that needs to be run from Ruby.  I'm using the `exec` method to do this, and it's being done in a Sidekiq Worker.

When running the the `exec` method in a worker it quits out of Sidekiq (in my development environment).

How can this be prevented/what is an alternative?

**Comment by mperham** [comment]
I don't follow. More detail and show some code?

**Comment by matisoffn** [comment]
Nevermind, solved my problem using `system()` in the worker rather than `exec()`
