### ISSUE TITLE
Unable to get logging to work

### ISSUE THREAD

**Issue by ch33foong** [mperham/sidekiq#2947]
Hi,

I am trying out Sidekiq, I added a couple of logger.debug in to the worker class but the log does not appears in STOUT or development.log. My rails app is a simple one, all default configuration from "rails new" command. Rails version is 4.2.6 and Sidekiq is  4.1.1. 

Here is my worker code:

class ProductImportWorker
    include Sidekiq::Worker
    def perform()
        logger.debug "Importing products..."
        sleep 10
        logger.debug "Finish import products."
    end
end 

What could be causing this? From the doc (https://github.com/mperham/sidekiq/wiki/Logging) it does not seems to suggest any configuration needed. 

Any pointers are much appreciated.

Thanks,
Foong

**Comment by mperham** [comment]
Debug level is disabled by default. Turn it on with -v.

**Comment by ch33foong** [comment]
@mperham thank you very much!
