### ISSUE TITLE
Securing redis connection

### ISSUE THREAD

**Issue by gingermusketeer** [mperham/sidekiq#2949]
I am using sidekiq 4.1 with rails and I have been trying to determine how to go 
about securing the connection to redis. 

The app is hosted on Heroku and they recommend using stunnel to secure the connection to redis. They have a good write up here https://devcenter.heroku.com/articles/securing-heroku-redis

So instead of `bundle exec sidekiq -C config/sidekiq.yml` to start the worker one would use `bin/start-stunnel bundle exec sidekiq -C config/sidekiq.yml`

I have been looking through the code to try and determine if I should be using 
stunnel with both the web and worker processes but have not had much luck. 

Am I correct in thinking that when a job is enqueued from within a rails web context sidekiq will connect to redis to store the information related to the job?

**Comment by mperham** [comment]
I think Redis Labs supports SSL out of the box.  Use it with redis-rb 3.3.

https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#330

**Comment by gingermusketeer** [comment]
@mperham Awesome. Many thanks
