### ISSUE TITLE
Jobs listed in dashboard not returned in query

### ISSUE THREAD

**Issue by DaveCollinsJr** [mperham/sidekiq#2950]
sidekiq-pro, 3.3.2, redis 2.8.6

I have noticed a large number of jobs (these would normally be very short running) listed in the dashboard as running for a long time.  While investigating I have found that very often the internal Sidekiq data structure does not show these jobs at all:

Examples:
**Currently on the Busy tab:**
p-10-102-183-13:6965:4fcd8579bcdb vyqao 6dc4db1e8df0dc6075ecc845  high  Kiosk::BlobQueueWorker  
511
10 minutes ago
ip-10-102-183-13:6965:4fcd8579bcdb  oeru0 26f01b61b204c2a20f4a3248  high  Kiosk::BlobQueueWorker  
73
10 minutes ago
ip-10-102-183-13:6965:4fcd8579bcdb  vkfe0 212d68585c4c770e3e1ac9a8  high  Kiosk::BlobQueueWorker  
514
10 minutes ago
ip-10-102-183-13:6965:4fcd8579bcdb  txnuk fbb68bf25447b855be552717  high  Kiosk::BlobQueueWorker  
27
10 minutes ago
ip-10-102-183-13:6965:4fcd8579bcdb  vkxds 1e66e7095e1bb885257f2949  high  Kiosk::BlobQueueWorker  
513
10 minutes ago
ip-10-102-183-13:6965:4fcd8579bcdb  vu00o 343a496283107a97b6e9d858  high  Kiosk::BlobQueueWorker  
512
10 minutes ago
ip-10-186-45-171:6961:0cd23e082daf  w5wx8 d681cdc36d27245e52145b94  high  Kiosk::BlobQueueWorker  
519
35 minutes ago
ip-10-186-45-171:6961:0cd23e082daf  zpvek a58228f2699f71669f9cac4c  high  Kiosk::BlobQueueWorker  
517
35 minutes ago
ip-10-186-45-171:6961:0cd23e082daf  zpapk 59d23321620b3895456c1e2d  high  Kiosk::BlobQueueWorker  
522
35 minutes ago

**But if I execute this query, it is not returned:**
Sidekiq::Queue.new("high").each { |job| puts "#{job.jid}\t#{job.klass}\t#{job.args}" if job.klass == 'Kiosk::BlobQueueWorker' }

Steps for troubleshooting?  These jobs appear to be orphaned or zombied and are causing us to have to run a much higher level of workers than we would normally run.

**Comment by mperham** [comment]
Enqueued jobs are ready to be picked up by the next available thread.  Busy jobs are what the threads are working on **right now**.  They are mutually exclusive.

**Comment by mperham** [comment]
Use the TTIN signal to get thread dumps from your process.  That will show where they are stuck.
