### ISSUE TITLE
Why does Sidekiq not depend on Gem redis-namespace?

### ISSUE THREAD

**Issue by paulmenzel** [mperham/sidekiq#2951]
Despite having Sidekiq 4.1.0 installed (in `Gemfile` and `Gemfile.lock`) it fails.

> LoadError: cannot load such file -- redis/namespace

Is there a reason why [redis-namespace](https://github.com/resque/redis-namespace) is not pulled in as a dependency?

**Comment by mperham** [comment]
Please read the 4.0 upgrade notes.
