### ISSUE TITLE
Stats in API showing zero but interface showing nonzero values

### ISSUE THREAD

**Issue by equivalent** [mperham/sidekiq#2952]
When I do:

```ruby
Sidekiq::Stats.new.queues 
# {"low"=>0, "transfer_s3"=>0, "paperclip"=>0, "medium"=>0, "high"=>0, "sqs_pull"=>0}

# or 

Sidekiq::Queue.new('sqs_pull').size 
# => 0

# even like

loop do
  sleep 0.001
  puts Sidekiq::Stats.new.queues 
  #  => zero values
end
```

but Sidekiq web interface is showing non-zero stats. (e.g.  `sqs_pull`queue has 3 jobs)

```
  * sidekiq (4.1.1)
  * redis (3.2.0)
  * rails (4.2.5.1)
ruby 2.2.2
```

Jobs are being scheduled / executed properly (as the web interface is showing ) 
I triple checked both the `Sidekiq.configure_server` and `Sidekiq.configure_client` use same Redis host, port and db number

...huge mystery

**Comment by equivalent** [comment]
looking at how Sidekiq Web is implementing this `https://github.com/mperham/sidekiq/blob/master/web/views/busy.erb`  

so when I do 

```
Sidekiq::Workers.new.map { |process_id, thread_id, work| work['payload']['queue']}
# => ["sqs_pull"]
```

it works

works

**Comment by equivalent** [comment]
ok getting closer to the problem

in https://github.com/mperham/sidekiq/blob/78fc103d561792b876854706f0e8acdc3b3379f4/lib/sidekiq/api.rb#L204

code does : 

```
  class Queue
    # ...
    attr_reader :name

    def initialize(name="default")
      @name = name
      @rname = "queue:#{name}"
    end
# ...
```
but when I do 

```
Sidekiq.redis { |con|  con.keys } .select { |q| q.match 'que' } 
=> ["queues"]
```

so Sidekiq::Queue#initialize works with `queue:xxx` (singular) but data is written in  `queues:xxx` plural

**Comment by equivalent** [comment]
ok it looks like a Redis version issue

on Staging server where I'm having this problem we are running `2.8.21`  (AWS elastic cache) While at my development maching (I've upgraded to `3.0.3`)  and it works 

```
Sidekiq::Queue.new('sqs_pull').size
=> 10
```

so Redis version is the answer :)

**Comment by equivalent** [comment]
I'll leave this open for now as you guys may have some feedback on this. Feel free to close

**Comment by equivalent** [comment]
if anyone else have problem with this replace

```
def overlimit
  Sidekiq::Queue.new("sqs_pull").size.to_i > 20
end
```


with 

```
def overlimit
    Sidekiq::Workers
      .new
      .map { |process_id, thread_id, work| work['queue']}
      .select { |queue_name| queue_name == "sqs_pull" }
      .size > 20
end

```

**Comment by equivalent** [comment]
I guess there is no point of refactoring `Sidekiq::Queue#size` ([here](https://github.com/mperham/sidekiq/blob/78fc103d561792b876854706f0e8acdc3b3379f4/lib/sidekiq/api.rb#L209)) to use this as this works with newer Redis. 

But if you guys think it may be worth re-factoring it for backwards compatibility give me a shout I'll do a Pull Request

**Comment by mperham** [comment]
Busy is the set of jobs which are executing right now.  They are no longer enqueued.

**Comment by equivalent** [comment]
forgot to update the comment. This is not only about the  in "Busy" from web-interface. 

I'm talknig about `sidekiq/api` mainly 

Given I enque 1000 tasks in a job `sqs_pull`
When I run `Sidekiq::Queue.new('sqs_pull').size` I got 0  from redis 2.8
When I run `Sidekiq::Queue.new('sqs_pull').size` I got 1000  from redis 3.2

**Comment by mperham** [comment]
I suspect you're pointing to the wrong redis.

**Comment by equivalent** [comment]
> I triple checked both the Sidekiq.configure_server and Sidekiq.configure_client use same Redis host, port and db number

I've checked again still the same host port and db number

**Comment by mperham** [comment]
`Sidekiq.redis { |c| p c.info }` will show the currently connected Redis info.
