### ISSUE TITLE
Upgrade from 3.3.4 to 4.1.1 now get undefined method `default' for Sidekiq::Client:Class on Sidekiq::Batch.new.jobs

### ISSUE THREAD

**Issue by IanVaughan** [mperham/sidekiq#2953]
Recent update of sidekiq in a Rails  4.2.4 project :
```diff
-    sidekiq (3.3.4)
-      celluloid (>= 0.16.0)
-      connection_pool (>= 2.1.1)
-      json
-      redis (>= 3.0.6)
-      redis-namespace (>= 1.3.1)
+    sidekiq (4.1.1)
+      concurrent-ruby (~> 1.0)
+      connection_pool (~> 2.2, >= 2.2.0)
+      redis (~> 3.2, >= 3.2.1)
```
Now get `NoMethodError: undefined method 'default' for Sidekiq::Client:Class` on the `.jobs` call :
```ruby
    batch = Sidekiq::Batch.new
    batch.description = "Something"

    batch.jobs do # <= error raised on this line
      # ...
    end
```

This only happens on production atm, and trying to reproduce locally, but wondered if anyone might be able to shed any light on it?

Changeset is quite big https://github.com/mperham/sidekiq/compare/v3.3.4...v4.1.1

**Comment by mperham** [comment]
You need to update sidekiq pro too.

**Comment by IanVaughan** [comment]
That was the issue, it now works, many thanks.

`bundle update sidekiq-pro` 

```diff
-    sidekiq-pro (2.0.1)
-      sidekiq (>= 3.3.2)
+    sidekiq-pro (3.2.1)
+      sidekiq (>= 4.0.0)
```
