### ISSUE TITLE
Rails session_store flags getting removed by sidekiq/web

### ISSUE THREAD

**Issue by mikebaldry** [mperham/sidekiq#2954]
Our current configuration for `session_store` is:
```ruby
Buyapowa::Application.config.session_store :active_record_store,
  key: "bp_sid",
  secure: true,
  expire_after: 1.month
```

Making requests to any of our normal pages results in a header like this:
```
Set-Cookie: bp_sid=455ad9fa38c3a1b0233ffb510a9d1629b8bcb3adf981ee1b2a94ad698d593358; path=/; expires=Sat, 28 May 2016 15:16:40 -0000; secure; HttpOnly
```

However when I hit the same server on /sidekiq the cookie gets set to this:
```
Set-Cookie: bp_sid=da02f71b7d822c54353282a5d8e3f4a0c3e36825fc8779e74869842ffc793302; path=/; HttpOnly
```

I can't really see much from the code as to why or how this would happen.

Any ideas?

**Comment by mperham** [comment]
Set the session options? https://github.com/mperham/sidekiq/issues/2910#issuecomment-206978212

**Comment by mikebaldry** [comment]
That did indeed fix it. Can you put this somewhere more prominent? Cheers

**Comment by mperham** [comment]
It's already here:

https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden
