### ISSUE TITLE
Upstart + redirection = unclean shutdown

### ISSUE THREAD

**Issue by mcclymont** [mperham/sidekiq#2957]
I have just realised that our Rails app in production is not shutting down Sidekiq workers cleanly when doing ```service sidekiq restart```. I was able to confirm this by creating a dummy job that simply sleeps for 5 minutes, starting it and then doing ```service sidekiq stop```. The job either stays stuck in Busy or disappears and does not get Enqueued.

This was the main line in the upstart configuration file /etc/init/sidekiq.conf. It is like this because we have a fairly hard requirement to send output to syslog with the tag 'sidekiq'. This is adapted from the Sidekiq wiki https://github.com/mperham/sidekiq/wiki/Logging#syslog
```
exec bundle exec sidekiq -c "$COUNT" -P "$PIDFILE" 2>&1 | logger -t sidekiq
```

If I watch syslog while issuing ```service sidekiq stop```, I expect to see messages like this
INFO: Shutting down
INFO: Shutting down X quiet workers
But they do not appear - the sidekiq process just exits immediately (and I don't see the job re-enqueued).

I'm pretty sure I have figured out the cause: when Upstart stops a service, it sends SIGTERM (the default signal) to the _process group_ which means that both Sidekiq and the logger process get the signal. Logger exits immediately, and now Sidekiq has a broken STDOUT and STDERR. Sidekiq is in its shutdown phase but as soon as it calls logger.info or similar, that call causes it to crash with an error like this
Errno::EPIPE: Broken pipe @ io_write - <STDERR>
(which is not normally visible unless you strace Sidekiq while doing this)

I have solved this problem in my case by getting the logger process to ignore the SIGTERM signal, like this:

```
script
  exec /bin/bash -e <<EOT
    exec &> >(trap -- '' SIGTERM && logger -t sidekiq)
    exec bundle exec sidekiq -c "$COUNT" -P "$PIDFILE"
EOT
end script
```

However it would be nice if Sidekiq could somehow rescue this broken pipe error and ignore it during this critical phase of shutdown.

You can reproduce the crash behaviour without using upstart by using some kind of simple dummy job I described, and doing this:
```
bundle exec sidekiq 2>&1 | logger -t sidekiq
pkill logger
pkill sidekiq
```

Update: It also fails if you redirect both STDERR and STDOUT to somewhere that gets closed. If you only redirect STDOUT, then you get errors on STDERR about the broken pipe, but the job correctly gets re-enqueued. I think this has something to do with how ruby Logger just warns about the exception which causes the same exception again, which by default the backtrace would go to STDERR https://github.com/rubysl/rubysl-logger/blob/d9c6c5438d6017668641154b75a59a1e3cb1a125/lib/rubysl/logger/logger.rb#L564

**Comment by mperham** [comment]
Check out the answer I linked here: https://github.com/mperham/sidekiq/wiki/Logging#syslog

**Comment by mcclymont** [comment]
Thanks for updating the Wiki.

My upstart script solution I outlined in my original report was actually adapted from the serverfault page you have now linked to in the wiki. However I thought that the mkfifo solution looked too complicated, so I didn't try it and I opted for this other way of doing it, which doesn't re-parent logger to init: http://serverfault.com/a/666970

The problem with both solutions is that upstart kills everything in the process group which includes the logger process (even when re-parented to init). So in the mkfifo solution you linked to, Sidekiq can still write to its STDOUT because it's going to a FIFO file, but anything it writes there during 'stop' won't get logged because logger has been killed. At least with the mkfifo method Sidekiq doesn't crash, and completes the shutdown process properly. Unfortunately you don't get to see in the logs whether it shut down immediately or whether it had to wait for workers to finish or had to kill some of the workers and re-queue them.

The solution I outlined in my issue fixes both problems so Sidekiq shuts down properly and all its logging during shutdown still gets sent to syslog.

**Comment by mperham** [comment]
Ugh, this is so much harder than systemd, where you can set a few attributes and you're done.

https://github.com/mperham/inspeqtor/blob/master/packaging/root/usr/share/inspeqtor/systemd/inspeqtor.service#L27

I'll point the wiki here instead but I have no idea what the right solution is for syslog + upstart.  It's a shame that such hacks are necessary.

**Comment by mcclymont** [comment]
The upstart cookbook/manual says to exec > /dev/kmsg for logging to syslog http://upstart.ubuntu.com/cookbook/#log-script-section-output-to-syslog

But 
1. You can't write to that device without being root
2. It won't tag the messages like I need

So yeah it is a shame. Thanks for taking the time to read this and update the wiki.
