### ISSUE TITLE
Periodic Job Stop Enqueuing Failed

### ISSUE THREAD

**Issue by chaslemley** [mperham/sidekiq#2958]
We ran into an issue yesterday and today. A couple of our periodic jobs stopped enqueueing. Everything else was running as expected.

The issue appears to coincide with a redis connection exception. A stacktrace can be found here: https://gist.github.com/chaslemley/8df6394c38a541743803f959bfdafe41

Interestingly, the issue only affected jobs that were set to enqueue every minute (* * * * *). Other jobs with longer intervals were not affected.

Killing the current leader by using the stop link in the Web UI resolved the issue.

**Comment by mperham** [comment]
Did your minutely jobs fail for enqueue for many minutes?

That exception is from the leader failing to re-elect itself.  That's expected upon network failure - another Sidekiq process should elect itself leader and then that new leader will start enqueuing jobs within a minute or so.  So the question is: did you lose 1 or 2 minutes of jobs (expected) or many, many minutes of jobs (unexpected, a bug)?

**Comment by chaslemley** [comment]
They failed for many minutes. They were down for at least 2 hours each time.

**Comment by mperham** [comment]
I can't determine a root cause for this.  You are running an older version and it's possible there have been fixes since 1.0.2.  Try an upgrade and let me know if it happens again?

**Comment by chaslemley** [comment]
Sounds good. I'll do that and keep an eye on it. We have monitoring in place now to ensure we're notified of another occurrence of it. Thanks @mperham!
