### ISSUE TITLE
How to find Redis memory leaks?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2959]
Is there a way to:

1. Run the full test suite.
2. Tell Redis to advance time to "some distant future".
3. Verify all Sidekiq data has expired from Redis?

I want to verify that all Sidekiq data has an expiration.  Is there a way to enumerate any keys in Redis without an expiry set?

**Comment by jonhyman** [comment]
In your test suite you can do something like this, right? Maybe?

```ruby
after :each do 
  Sidekiq.redis do |r|
    r.scan_each do |key|
      r.ttl(key).should be > 0
    end
  end
end
```

**Comment by mperham** [comment]
Yeah, something like that but I think it's harder than that due to minitest.

I think someone found a memory leak with the `workers` key in the heartbeat so I want to make sure we find any further leaks and prevent future leaks.

**Comment by jasonrclark** [comment]
We do something like this in newrelic_rpm on minitest to look for thread leaks https://github.com/newrelic/rpm/blob/master/test/test_helper.rb#L45

**Comment by jakemack** [comment]
Since upgrading last week, we've occasionally been getting stale workers showing up in the busy jobs list. Would that be related to the memory leak for the workers key? If not, I'll create a separate issue for it

**Comment by mperham** [comment]
@jakemack I don't know why those entries appear but it's possible.  You see stale workers on 4.1.2?

**Comment by jakemack** [comment]
Yeah, we've seen one or two stale workers on three of our last eight nightly job batches where we process ~6.6 million jobs so it seems pretty infrequent given the absolute quantity

**Comment by jakemack** [comment]
I vaguely remember removing some extra code to remove stale worker data when I upgraded to Sidekiq 4 (from 3.5) back in December so I have a feeling this is related. I'll examine the Sidekiq redis data next time I see stale workers and let you know what I find

**Comment by mperham** [comment]
Doesn't seem to be any reasonable way to implement this.
