### ISSUE TITLE
Was drain removed? Is there an alternative?

### ISSUE THREAD

**Issue by softwaregravy** [mperham/sidekiq#2961]
Doing some testing per https://github.com/mperham/sidekiq/wiki/Testing and getting a `undefined method 'drain' for SendSmsWorker:Class` error. I'm searching the project, but can't find the drain method outside of docs and comments. Was it removed? 

Is there anything similar to the `#work_off` method from `delayed_job` in which we can manually (e.g. from a test) have Sidekiq process the jobs on the queue?

**Comment by mikegee** [comment]
Perhaps you didn't `require 'sidekiq/testing'` in your suite?

`drain` is implemented in https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb

**Comment by softwaregravy** [comment]
I quite possibly didn't. Thanks
