### ISSUE TITLE
Does Redis making my server irresponsive

### ISSUE THREAD

**Issue by Faisal-nfl** [mperham/sidekiq#2962]
I am working on a rails app in which I 'm using Sidekiq to make the process of sending email on sign up Asynchronous(I have installed Redis on my local server). Everything work fine in development mode.

But When I deployed it to Digital Ocean Droplet. It worked fine except email sending, So I installed Redis on digital Ocean and it solved the mailing issue.

Almost after a day Digital Ocean Server became irresponsive, when I try

`ssh root@Server-IP`
it `givesConnection timed out` error.

It has happened twice in couple of weeks. Last time it happened, It didn't even allow to delete droplet. But Somehow my team lead created a new droplet. I installed everything and than deployed my rails app to it, it worked fine for almost a day and than became irresponive too.

Why its happening, It has anything to do with Redis?

**Comment by mperham** [comment]
Your question isn't clear enough to understand the problem so we can't help with a solution.  I hope you figured it out.
