### ISSUE TITLE
Worker is still listed within admin/busy when it isn't running

### ISSUE THREAD

**Issue by Geesu** [mperham/sidekiq#2964]
I have 2 workers that for some reason are still appearing within sidekiq admin even though they have long since been terminated. They both started over 3 months ago and are definitely not running.

Is there a way to remove these?

**Comment by mperham** [comment]
There was a bug fixed recently that led to leaked worker data.  Upgrade to 4.1.2 and run this script to expire that data:

https://github.com/mperham/sidekiq/blob/master/Changes.md#412

**Comment by Geesu** [comment]
How long does it take to remove them from the busy view (It has been about 10 minutes and they are still there)? Also I noticed one of the workers wasn't in the list of keys printed by the above script.

Or do I need to do anything else?

I am running sidekiq 4.1.2.

**Comment by mperham** [comment]
I don't know why your data isn't disappearing.

**Comment by mperham** [comment]
If you learn anything more, please let us know.
