### ISSUE TITLE
perform_in(1.minute, ...) performing the job immediately

### ISSUE THREAD

**Issue by szimmer1** [mperham/sidekiq#2967]
I have a worker `S3Worker` that writes to S3, which I sometimes want to delay. If I call with `S3Worker.perform_in(1.minute, options)`, I'm observing the S3 file being written immediately. You'll notice I `require 'sidekiq/testing/inline'` for debugging on Rails dev and test envs. But the issue happens on staging environments too.

I'm using `gem 'sidekiq', '~> 3.5.4'`

The worker skeleton looks like this:

    require 'sidekiq/testing/inline' if Rails.env.development? || Rails.env.test?
    
    class S3Worker
      include Sidekiq::Worker
      sidekiq_options queue: 's3_upload'
      sidekiq_options retry: false
    
      def perform( options )
         # code that writes to S3
      end
    end

**Comment by mperham** [comment]
You are probably pulling in inline somewhere else.  Raise an error in the job and look at the stack trace to determine if so.
