### ISSUE TITLE
Make accessible in top/htop what jobs are being executed

### ISSUE THREAD

**Issue by quentindemetz** [mperham/sidekiq#2968]
It's difficult to see in standard linux monitoring tools (htop / top) which sidekiq worker is running which jobs. 
In `top` in tree view (press `V`), displaying threads (press `H`) I can see the following:
```
 91967 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:12.95  `- ruby2.2
 92131 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:00.04      `- ruby-timer-thr
 92786 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:01.05      `- util.rb:23
 92787 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:00.00      `- util.rb:23
 92788 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:00.39      `- util.rb:23
 92789 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:30.37      `- util.rb:23
 92790 www-data  20   0 1073132 428456   8124 S  0.0  0.6   0:00.40      `- util.rb:23
```

I can get a different kind of output by then pressing `c`:
```
 91888 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:12.86  `- sidekiq 4.1.0 pricematch [0 of 2 busy]
 92117 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:00.03      `- sidekiq 4.1.0 pricematch [0 of 2 busy]
 92774 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:00.94      `- sidekiq 4.1.0 pricematch [0 of 2 busy]
 92775 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:00.00      `- sidekiq 4.1.0 pricematch [0 of 2 busy]
 92776 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:03.30      `- sidekiq 4.1.0 pricematch [0 of 2 busy]
 92777 www-data  20   0 1005552 518752   8200 S  0.0  0.8   0:02.37      `- sidekiq 4.1.0 pricematch [0 of 2 busy]
```

But I'm still unable to know which worker is running which jobs.

I would like to make two suggestions:
- if possible, change the name of the thread to include something identifying the current job (ActiveJob ID for example). I'm not sure you can change a thread's name after it's been created
- add to the worker's name all the IDs of the jobs it's currently running (seems like http://stackoverflow.com/a/29017015 explains how to do this)

What is your experience performing this kind of debugging, and how would you go about solving this ?

Thanks

**Comment by mikegee** [comment]
You can make Sidekiq dump all the threads current stacks to the log: https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by mperham** [comment]
80 columns only gives you a small space for a brief summary.  Use the Web UI or API if you need more extensive data.
