### ISSUE TITLE
Typo in wiki regarding licenses?

### ISSUE THREAD

**Issue by jc00ke** [mperham/sidekiq#2970]
I'm pretty sure this should be "inappropriate" but didn't want to just change it.

```
The standard license is appropriate for SaaS usage as it does not allow distribution.
```

It's the `appropriate/does not allow` combo that's throwing me off. Found [here](/mperham/sidekiq/wiki/Commercial-FAQ#can-i-distribute-sidekiq-pro-or-enterprise-to-my-customers)

**Comment by mperham** [comment]
It's correct but confusing. SaaSes don't need to distribute, appliances do since they are installed onsite.

**Comment by mperham** [comment]
Changed it to:

```
The standard license is only appropriate for SaaS usage as it does not allow distribution.
```
