### ISSUE TITLE
it might be nice if sidekiq pro set a default options[:index] in production too for reliable_fetch

### ISSUE THREAD

**Issue by kjg** [mperham/sidekiq#2971]
We didn't set an index option and everything looked like it was running fine in our staging env, but when we deployed to prod, sidekiq raised the error `reliable fetch requires a process index option`

It appears a default index is set when not in production `Sidekiq.options[:index] ||= 0 if Sidekiq.options[:environment] != 'production'` it would be nice if this was consistent in every env.

I know the docs say to specify an index, but since it worked in staging and we have unique static host names, I thought the index wouldn't be required in prod, but I was wrong.

If the default behavior is not going to be consistent, it might be useful to at least make it more clear in the docs that things will FAIL in production env, but not in other envs, if the index isn't set.

**Comment by mperham** [comment]
I think you're right, it should act the same in production as staging.  I will adjust it to this.

```
Sidekiq.options[:index] ||= 0 if Sidekiq.options[:environment] == 'development'
```

**Comment by kjg** [comment]
Thanks! I still it might also be good to make it very clear what it means when you say `other environments must set an index if you wish to use reliable_fetch`. That the sidekiq process will raise and error and exit if an index isn't set but reliable_fetch is.

**Comment by phantomwhale** [comment]
Ooof yeah, we upgraded, everything looked fine in development, then pushed to production and *boom* things started to fail. I would have preferred this to be consistent across all environments, so we would have picked this up in development first.
