### ISSUE TITLE
Delayed message through Active Job behavior clarification

### ISSUE THREAD

**Issue by rhuppert** [mperham/sidekiq#2972]
I've run into something curious using Rails 4.2.6 & Sidekiq 4.1.2 with redis option.

In development, I use Mailtrap to capture mail output.  It imposes a 2 email per second limit with their free account.  In a block, I add a 2 second sleep delay after the ActionMailer job to avoid Sidekiq errors. I also added a 10 second delayed message as per https://github.com/mperham/sidekiq/wiki/Active-Job#action-mailer testing both :wait and :wait_until.  

It appears that all mailers in the queue get processed at the same time (after 10 seconds), which triggers the 2 email per second error(s).  They are successfully delivered upon subsequent retries, however.

Is this the designed behavior?

```
events.find_each do |event|
  EventMailer.new_event_email(event.id).deliver_later!(wait_until: 10.seconds.from_now)
  sleep 2 if Rails.env.development?
end

events.find_each do |event|
  EventMailer.new_event_email(event.id).deliver_later!(wait: 10.seconds)
  sleep 2 if Rails.env.development?
end

**Comment by mperham** [comment]
That's totally normal.  Sidekiq runs 25 threads by default so you can get up to 25 jobs processed at the same time.  Sidekiq Enterprise has a rate limiting API which you could use in your job to ensure the rate limit is met.

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#window

**Comment by mikegee** [comment]
Further clarification please: this can happen with concurrency turned down to 1 with only 1 worker process running too, right?

I'm thinking about the 15 second default poll interval for scheduled jobs that have become due. A 2 second delay between enqueuing them will almost always result in both of the jobs becoming due during the same check.

**Comment by rhuppert** [comment]
Thanks.  I was confused as to where the delay was taking place.
