### ISSUE TITLE
Sidekiq Crashing on startup on Ruby 2.2.4

### ISSUE THREAD

**Issue by jmscholen** [mperham/sidekiq#2973]
`$ bundle exec sidekiq

2016-05-14T02:21:33.045Z 12302 TID-84nw8 INFO: Running in ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
2016-05-14T02:21:33.045Z 12302 TID-84nw8 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-05-14T02:21:33.045Z 12302 TID-84nw8 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
no implicit conversion of String into Integer
/home/rails/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:70:in `[]'
/home/rails/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:70:in `run'
/home/rails/.rvm/gems/ruby-2.2.4/gems/sidekiq-4.1.1/bin/sidekiq:12:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.4/bin/sidekiq:23:in `load'
/home/rails/.rvm/gems/ruby-2.2.4/bin/sidekiq:23:in `<main>'
/home/rails/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/home/rails/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'`

any help to dig into this....this is working on another server except that it is running Ruby 2.2.3... this is all I get in the log.

**Comment by mperham** [comment]
Turn on -v.  Show us your config/sidekiq.yml.

**Comment by mperham** [comment]
That error means there was some problem fetching the Redis version you are using.

**Comment by jmscholen** [comment]
Ok, I'll look into that..

Using capistrano-sidekiq gem to deploy:

set :sidekiq_concurrency, 5
set :sidekiq_queue, ['default']
set :sidekiq_log, File.join(release_path, 'log', 'sidekiq.log')
set :sidekiq_pid, File.join(release_path, 'tmp', 'pids', 'sidekiq.pid')
set :sidekiq_role, :task
