### ISSUE TITLE
Sidekiq Pool Size Calculation

### ISSUE THREAD

**Issue by ssotos** [mperham/sidekiq#2974]
Hey All, 

Can someone explain as much in detail as possible how to set the maximum pool size in Sidekiq with all the math I have to do? 

My architecture is the following:

Rails + Mongodb + Sidekiq + Redis 

Thanks in Advance :) 

RegardsSoto

**Comment by mperham** [comment]
https://bryanrite.com/heroku-puma-redis-sidekiq-and-connection-limits/
http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/

**Comment by mperham** [comment]
When in doubt, don't set any size.  Let Sidekiq size it for you.

**Comment by ssotos** [comment]
Thank you
