### ISSUE TITLE
Sidekiq Unitialized Constatnt error

### ISSUE THREAD

**Issue by grandmasterspoc** [mperham/sidekiq#2976]
I'm getting an error
 `uninitialized constant SmsWorker` 

but `SmsWorker` doesn't exist anywhere in the application, and I'm not calling it from anywhere. (I made sure to do a `CMD+shift+f` to search for it)

any idea why I keep getting this error?

**Comment by mperham** [comment]
You have an old job in Redis referencing this class.  You can run `redis-cli flushall` to clear your Redis completely or go into the Web UI and delete it.
