### ISSUE TITLE
Can we restrict sidekiq to write many and read only once 

### ISSUE THREAD

**Issue by SaiVardhan** [mperham/sidekiq#2979]
Hi,
I have setup sidekiq and redis in my rails application to run background jobs.
I have two instances of my application and thought of adding ec2 redis cluster so that both the instances can use the same cluster to append jobs.

So what I want is to make two instances to write to redis when job is created but to make only one instance to read from it.

Is that possible.If so, How can we achieve that?

Thanks in advance

**Comment by mperham** [comment]
I'm not sure that's possible.  If it is, I don't know how to do this.
