### ISSUE TITLE
ERR max number of clients reached (Redis::CommandError)

### ISSUE THREAD

**Issue by mrrooijen** [mperham/sidekiq#298]
Hey there,

I've been trying to push an app to Heroku with JRuby 1.7. However, I am experiencing some issues.

I am using RedisToGo, a small instance that allows up to 50 connections. My Sidekiq configuration looks like this:

``` ruby
Sidekiq.configure_server do |config|
  config.redis = {:url => url}
end

Sidekiq.configure_client do |config|
  config.redis = {:url => url, :size => 30}
end
```

I am running 3 processes on Heroku:
- web
- processor (Sidekiq)
- service (Clockwork, which enqueues stuff in to Redis using Sidekiq)

Since there are 3 processes, does this mean that it's trying to establish 3*30=90 connections to the Redis instance? If so then I might want to make `:size` differ per process using an environment variable or something.

This is the error I receive:

```
ERR max number of clients reached (Redis::CommandError)
```

Cheers

**Comment by gabeodess** [comment]
Just FYI, I found that I get this error on Heroku if I don't have a Sidekiq process running with the `-e production` flag.
