### ISSUE TITLE
Race condition leading to processes lingering in the Busy tab

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2982]
I believe there is a race condition in the heartbeat code which leads to the rare case of a process lingering in Busy forever.

```ruby
        _, _, _, msg = Sidekiq.redis do |conn|
          conn.pipelined do
            conn.sadd('processes', key)
            conn.hmset(key, 'info', json, 'busy', Processor::WORKER_STATE.size, 'beat', Time.now.to_f, 'quiet', @done)
            conn.expire(key, 60)
            conn.rpop("#{key}-signals")
          end
        end
```

Because this is a `pipelined` call, the `hmset` can take place and then the process killed before the `expire` can run.  Fix is to change this block to a `multi`.

**Comment by tisba** [comment]
As far as I can tell, this was not yet released in the 4.x series, right?

**Comment by mperham** [comment]
That's right.  I was planning on a release at the end of the month so expect it very soon.

**Comment by tisba** [comment]
Great, thanks!
