### ISSUE TITLE
Stuck in idle status

### ISSUE THREAD

**Issue by rejeep** [mperham/sidekiq#2984]
Hi,

We use Sidekiq to run integrations and it works great, thanks! 👍 

Sometimes though, it gets stuck showing "idle" in the GUI:

![image](https://cloud.githubusercontent.com/assets/20277/15496973/8be0eb88-2198-11e6-85f9-6438a373935a.png)

From the code it looks like it is in idle-mode if there are no workers. Why is that and why is it that it suddenly loses them?

The logs says nothing and I've tried restarting everything, but it doesn't help so I'm out of ideas. Would appreciate some help here.

Ruby: `ruby 2.0.0p643 (2015-02-25) [x86_64-linux]`
Rails: `4.2.4`
OS: `3.14.27-25.47.amzn1.x86_64 (EC2)`
Sidekiq: `4.1.1`

Thanks!

**Comment by rejeep** [comment]
Ok so rebooting the machine solved the issue, but we would really like to know why this happens.

**Comment by mperham** [comment]
Show us TTIN output from a process when it stops processing. https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by rejeep** [comment]
It happens again and `kill -TTIN PID` gave no output.

**Comment by rejeep** [comment]
And now I know why. It wasn't Sidekiq, it was the service that adds jobs to Sidekiq. But then I must be misunderstanding the idle status. Why would the workers stop because no jobs are added?

Closing this since the issue was not in Sidekiq.

**Comment by mperham** [comment]
Idle means they aren't working on anything right now.

**Comment by rejeep** [comment]
Ok, thanks and sorry for the noise.
