### ISSUE TITLE
Calling worker from worker is extremely slow

### ISSUE THREAD

**Issue by asgorgulho** [mperham/sidekiq#2986]
I'm noticing that some of my jobs are taking 10 seconds or more to run. While debugging I notice that the problem is while calling another worker from the current worker, it can take from 0.1 to 10 seconds or more and also when accessing redis, just a simple command as GET can take a while.  What could cause this slowness? I'm using the latest sidekiq version 4.1.2 and ruby version 2.2.4. Don't know if it could be related with my redis and sidekiq configuration.

On my redis initializer I have:
```ruby
$redis = Redis.new(host: XXX, port: 6379)
redis_pool = proc {
    $redis
}
```

On my sidekiq initializer I have:
```ruby
redis_pool = proc { $redis }

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 1000, &redis_pool)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 2000, &redis_pool)
end
```

Accessing redis outside a sidekiq job runs extremelly fast, the issue seems to happen only on sidekiq jobs.

**Comment by mperham** [comment]
You've setup the Redis pool in the worst possible way for performance. That's why. You have all N sidekiq threads sharing a single connection.

**Comment by asgorgulho** [comment]
Thanks for the input. So should I have something like the configuration below? It's better but still getting some very slow jobs.

'''ruby
# redis.rb
$redis_uri = URI.parse(ENV['REDIS_URL']) if ENV['REDIS_URL']

$redis = Redis.new(host: ($redis_uri.nil? ? 'localhost' : $redis_uri.host), port: ($redis_uri.nil? ? '6379' : $redis_uri.port), db: 7, namespace: 'rt-analytics')
'''

'''ruby
# sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { url: "redis://#{ENV['REDIS_ADDRESS']}:6379/7" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://#{ENV['REDIS_ADDRESS']}:6379/7" }
end
'''

**Comment by patriotphoenix** [comment]
> You've setup the Redis pool in the worst possible way for performance. That's why. You have all N sidekiq threads sharing a single connection.
> 
> > On May 25, 2016, at 03:56, asgorgulho [notifications@github.com](mailto:notifications@github.com) wrote:
> > I'm noticing that some of my jobs are taking 10 seconds or more to run. While debugging I notice that the problem is while calling another worker from the current worker, it can take from 1 to 10 seconds or more. What could cause this slowness? I'm using the latest sidekiq version 4.1.2 and ruby version 2.2.4. Don't know if it could be related with my redis and sidekiq configuration.
> > On my sidekiq initializer I have:
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub

What do you recommend then?
