### ISSUE TITLE
Unable to run 4.1.2 with jruby-1.7.* versions

### ISSUE THREAD

**Issue by ryanbjones** [mperham/sidekiq#2987]
Did a bundle update to `4.1.2` using `jruby-1.7.20.1` (we've had issues with performance when upgrading to `jruby-9.*`).  The issue did not occur with `jruby-9.*`

```
SyntaxError: /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/sidekiq-4.1.2/lib/sidekiq.rb:49: Invalid char `\235' ('') in expression
  def self.â¨â¯Â°â¡Â°â©â¯ï¸µâ»ââ»
            ^
          require at org/jruby/RubyKernel.java:1072
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274
  load_dependency at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274
           (root) at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/sidekiq-cron-0.4.2/lib/sidekiq-cron.rb:1
          require at org/jruby/RubyKernel.java:1072
           (root) at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/sidekiq-cron-0.4.2/lib/sidekiq-cron.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/bundler-1.11.2/lib/bundler/runtime.rb:1
             each at org/jruby/RubyArray.java:1613
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/bundler-1.11.2/lib/bundler/runtime.rb:77
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/bundler-1.11.2/lib/bundler/runtime.rb:72
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/bundler-1.11.2/lib/bundler/runtime.rb:61
          require at org/jruby/RubyKernel.java:1072
          require at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/bundler-1.11.2/lib/bundler.rb:99
          require at org/jruby/RubyKernel.java:1072
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/config/application.rb:7
          require at org/jruby/RubyKernel.java:1072
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/config/environment.rb:1
             load at org/jruby/RubyKernel.java:1091
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/config/environment.rb:2
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/spec/spec_helper.rb:1
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/spec/spec_helper.rb:17
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/spec/lib/abacus/account_merger_spec.rb:1
           (root) at /Users/ryanbjones/Desktop/main-repos/abacus/spec/lib/abacus/account_merger_spec.rb:1
           (root) at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361
             load at org/jruby/RubyKernel.java:1091
  load_spec_files at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359
             eval at org/jruby/RubyKernel.java:1111
           (root) at /Users/ryanbjones/.rvm/gems/jruby-1.7.20.1@abacus/bin/jruby_executable_hooks:15
```

While I appreciate the humor of the method, unfortunately it has caused an issue. If you don't think you'll remove it, perhaps the [failure](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L4) you provide should catch it. 

Thanks for all you do with this project :)

**Comment by mperham** [comment]
Sidekiq requires 1.9-mode.  Looks like you might be in 1.8 mode.

**Comment by jcarley** [comment]
I'm getting the same error on travis-ci.  I have jruby-19mode set, and I even added JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8" to then env section.  Unable to find a solution.

https://travis-ci.org/jcarley/activecommand/jobs/137066543

**Comment by fergmastaflex** [comment]
Maybe just remove the emoji method? It's all fun and games until there's a breaking change.

**Comment by mperham** [comment]
Paging @headius.  If JRuby 1.7.* doesn't support full unicode method names in 1.9 mode, that's a JRuby bug.  Sidekiq requires a Ruby interpreter with utf8 source support.

**Comment by tels7ar** [comment]
Sigh, this just broke a jruby-1.7.19 deployment for me.  While I agree it's a clever and fun method name, it is causing problems for people out in the real world.

**Comment by enebo** [comment]
@mperham it is a signficant amount of work to fix this on 1.7.x (we did get this working on 9k).  So we would prefer to not put in work for something we plan on supporting for 5 more months.   This more than a simple parser fix too it digs into how we cope with symbols as well with how we register method names as Java Strings.

**Comment by headius** [comment]
@mperham Sidekiq also appears to only support Ruby 2.0-compatible and higher, which would not include JRuby 1.7. I agree this is a bug in JRuby 1.7 but practically speaking should Sidekiq even be expected to run on that version anymore?

**Comment by mperham** [comment]
@headius I'm fine either way.  I thought that 1.9.3 supported Unicode methods and 1.7 was supposed to be 1.9.3 compat so figured it to be a JRuby bug.  I only advertise 9k support any more.

**Comment by headius** [comment]
@ryanbjones If you haven't, please report your JRuby 9k perf issues as bugs, so we can help you make the move. If you've already reported the issues, let me know what they are :-)
