### ISSUE TITLE
Adding sidekiq to an existing Resque processing farm

### ISSUE THREAD

**Issue by nextofsearch** [mperham/sidekiq#2990]
Hi,

I am adding sidekiq to an existing resque processing farm but sidekiq is not processing jobs enqueued by resque. I tripple-checked redis address and queue name. I have just learned that resque uses a key "resque:queues" while sidekiq uses "queues". Can it be a cause for the problem?

Thanks in advance.

**Comment by mperham** [comment]
Sounds like you need to use a "resque" namespace.

**Comment by nextofsearch** [comment]
@mperham Thanks for the help. It would be nice if it is described in the wiki, which could save me several hours. :)

**Comment by mperham** [comment]
I don't recommend namespaces, which is why I don't document them.  That said, it's reasonable to document them on the Resque Compatibility page for this edge case.

http://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by nextofsearch** [comment]
@mperham the link is not working.

I think the current description is a bit misleading since it doesn't work without namespace tweak.
"Sidekiq is compatible with Resque. It uses the exact same message format as Resque so it can integrate into an existing Resque processing farm. You can have Sidekiq and Resque run side-by-side at the same time and use the Resque client to enqueue jobs in Redis to be processed by Sidekiq."

If you don't recommend namespaces, I think it should be stated that adding a sidekiq node to a resque processing farm would not work because of the difference in namespace somewhere in the doc.

**Comment by nextofsearch** [comment]
I found this in wiki, which I missed. It looks good enough.
https://github.com/mperham/sidekiq/wiki/Resque-Compatibility#redis
