### ISSUE TITLE
Workers stuck in "stopping"

### ISSUE THREAD

**Issue by filiptepper** [mperham/sidekiq#2992]
I have a set of workers running, I restart them with monit when a worker reaches a certain memory consumption level. Recently I started noticing that these workers are stuck in "stopping" state and won't shut down gracefully. I see "Bye!" in the log and that's it, the worker sits idle.

Anything I could do to further debug the issue?

**Comment by mperham** [comment]
Sidekiq outputs "Bye" when calling exit().  That process is messed up pretty badly if it doesn't exit upon exit().

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L100
