### ISSUE TITLE
Sidekiq web UI does not display any workers in action

### ISSUE THREAD

**Issue by nextofsearch** [mperham/sidekiq#2993]
Hi,

I have a dashboard web server using sidekiq to put a job in the queue and a separate processing sidekiq node to process the job. When I have sidekiq web-ui implemented in the dashboard web server, I don't see any registered worker under 'Workers' tab even though there is a running sidekiq worker and it processes jobs in the queue. Should I implement it in the sidekiq processing node to see worker status? Or is it mis-configured somehow?

Thanks,

**Comment by mperham** [comment]
Either you aren't pointing to the right Redis or your jobs aren't running long enough.  The worker data is not real-time so the job has to run for at least 5 seconds if you want to guarantee it will show up.  Add a "sleep 15" to your job, kick one off and refresh the page after 5 seconds.  It will show up.
