### ISSUE TITLE
Sidekiq-4.1.2 | sidekiq.rb:49: invalid multibyte char

### ISSUE THREAD

**Issue by kulvind3r** [mperham/sidekiq#2994]
Hi,
Require fails to load sidekiq gem on ubuntu 14.04 LTS (Trusty Tahr) throwing Bundler::GemRequireError saying there is an invalid multibyte character in sidekiq.rb at line 49. When i checked the file itself i found this method

```
def self.❨╯°□°❩╯︵┻━┻
  puts "Calm down, yo."
end 
```
Umm, is this suppose to be there? Could this be the cause of failure to load?

**Comment by mikegee** [comment]
That method isn't causing problems for most folks. I wonder why your system differs. Which version of Ruby are you using?

**Comment by ryansch** [comment]
What's the value of the 'LANG' env var on your system?

**Comment by kulvind3r** [comment]
1. Ruby version 1.9.3, 
2. LANG is en_US.UTF-8

We had to go back to using sidekiq 2.16.1 and things are working fine. The method is still there and it is not throwing issues.

**Comment by mperham** [comment]
Please read the upgrade notes when upgrading major versions. It will tell you what is wrong.
