### ISSUE TITLE
Sidekiq admin localization: configuring server-side vs. in browser

### ISSUE THREAD

**Issue by patio11** [mperham/sidekiq#2995]
Hiya Mike and Sidekiq team.

We've run into an interesting usability thing with Sidekiq.  Presently, the localization for the admin defaults to using the browser's Accept-Language header.  I get why you'd want to do that, but in some organizations it is not entirely desirable: users may not have control over their Accept-Language header because that is managed by IT, and in multi-lingual environments the DevOps team might be more comfortable with engineering information displayed in the company's common language (since it leaks everywhere via e.g. screenshots posted to Slack) rather than in each user's individual language.

The selfish rationale for this is "I use all of my computers in Japanese but would prefer to read my admin in English."

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web_helpers.rb#L65

I can trivially patch this locally, but given that this is a potentially-not-just-me issue, would you like a patch which does one or both of:

* Overrides the present behavior iff an environment variable is set with the language to use (server-side)?
* Adds a configuration option to sidekiq.yml which if set functions similar to the above suggestion?

**Comment by mperham** [comment]
IMO the complexity added by a config switch for this rare edge case outweighs its value.  Some people will use a second browser with a different language config.  Alternatively you can monkeypatch in the behavior you'd like to see.  You could put this in an initializer:

```ruby
require 'sidekiq/web'

module Sidekiq
  module WebHelpers
    def locale
      'en'
    end
  end
end
```

**Comment by patio11** [comment]
Cool!  Thought I'd mention it since we ran into it during onboarding.  We'll use our monkeypatch locally.

Considering this closed.

**Comment by vizcay** [comment]
Hi! It took me a while to find how to do this going through the issue list.

For places where English is not our main language (but we use it all the time) this is really useful, and at least should be at the FAQ if not a config switch IMHO.

Anyway, great work mperham with this gem.
