### ISSUE TITLE
Non Existent Process / Stuck 'Busy' Jobs

### ISSUE THREAD

**Issue by danmayer** [mperham/sidekiq#2998]
Sidekiq web and `ps = Sidekiq::ProcessSet.new` show a process. That seems like it shouldn't possibly exist.

Sorry if an answer to this exists elsewhere, I looked through the wiki and google group but didn't see anything. We are deploying our Sidekiq background processes on ECS. Our Docker containers start from `ruby:2.3.1-slim`, We have Sidekiq Pro and are using `Sidekiq::Client.reliable_push!` and `config.timed_fetch!`. We had some issues crashing our Sidekiq tasks and were restarting the ECS services to get back running. After resolving some of those issues we have a 'zombie' process, 

The process claims to be processing two 'busy' jobs for the last 4 days. It shows in the process list

`63758c1f1b9c:40 app reliable 
Queues: default, paperclip, exports	4 days ago	3	2`

The task has been killed for days, multiple deploys have occurred and everything is working, except this zombie isn't going away. 

If a bug or solution related to this already exists feel free to point me in the right direction.

**Comment by mperham** [comment]
I suspect this: https://github.com/mperham/sidekiq/blob/master/Changes.md#head

**Comment by danmayer** [comment]
wow, fast reply! Thanks OK cool, we will upgrade when next release comes up. Thanks, if we could do something to help you debug / confirm etc let me know happy to run a pre build.

**Comment by mperham** [comment]
You can run master. I'll try to develop a cleanup script tomorrow.

**Comment by mperham** [comment]
See b6d9db3
