### ISSUE TITLE
What happens when Redis is not writable ?

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#2999]
Here is my use-case.

I have a Redis cluster on AWS-Elasticache. it looks like this.
```
DNS_URL
   |
   /\
  /  \
 M    R
```
The Master is read/write while the Replica is read-only.

If the Master fail (for any reason) : 
 - the Replica will be promoted master
 - the DNS_URL will point to the Replica

It happened to me this wednesday. This process takes about 5-6 seconds.
The problem is : 
 - It appears that the jobs that terminated during this period got lost
 - there is no retry so every sidekiq call to redis is lost during those 5-6 seconds

How can I prevent this ?

NB: I am using Sidekiq Enterprise with the following options : 
- Sidekiq::Enterprise.unique!
- Sidekiq::Client.reliable_push!
- config.options[:ephemeral_hostname] = true
- config.reliable_fetch!
- config.reliable_scheduler!

**Comment by mperham** [comment]
Have you looked into timed_fetch yet?  Works much better on ephemeral systems.

[There is retry support for replica promotion](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L94) but data consistency will depend on your replication setup.  If job data is async replicated to the replica, it can be missing some of the latest data.

**Comment by Micka33** [comment]
How do I configure Sidekiq to know the replica ?

**Comment by mperham** [comment]
That's between ElastiCache and the Redis driver.  I'm not sure.  It may be a DNS thing: Sidekiq will disconnect the socket and when it reopens it - it may go to the IP address for the new primary.

**Comment by Micka33** [comment]
If I understand correctly [this (sidekiq.rb#L96)](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L96), is the default behavior, right ?
Also, it will also retry only once, with no delay.

How to make sure it waits, or how to make it retry more times ?

**Comment by mperham** [comment]
It will just retry that one operation.  There's no way to tell if Sidekiq should retry once, twice or a dozen times.

If the retry fails, the exception will unwind the stack and Sidekiq will go back to its default state: trying to fetch new jobs, once per second.  As to what happens to the current jobs, they will be lost unless you are using reliable_fetch or timed_fetch.
