### ISSUE TITLE
When does this happen ? "Lost leadership of Sidekiq cluster"

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#3002]
When can this message be displayed ?
```txt
Lost leadership of Sidekiq cluster
```

It seems that when this messages appeared, the jobs currently being processed stopped.
What's happening ?

**Comment by mperham** [comment]
That indicates that the leader process couldn't reach Redis before its leadership token expired.  Tokens last one minute and the leader tries to renew its token every 15 seconds.  If it's a problem with the leader's machine, another process on another machine will step up and elect itself leader.  If it's a problem with Redis itself, the entire cluster will be leaderless until connectivity is restored.

The leader is responsible for enqueuing cron jobs and a few other Enterprise features.
