### ISSUE TITLE
default_latency in sidekiq dashboard

### ISSUE THREAD

**Issue by pankajgrovertt** [mperham/sidekiq#3003]
what does "default_latency" mean in sidekiq dashboard json. And Is there any way to find latency for each queue in sidekiq using sidekiq dashboard json ?

PS: I'm newbie.

**Comment by mperham** [comment]
Newbies are ok, I was a newbie once too.  🍰 

The `default_queue_latency` is the latency of the default queue.  Latency is the time diff between when the first job on the queue was enqueued vs now.  If the queue gets backed up for some reason, the latency will go from 0.xxx to a larger number.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L77
