### ISSUE TITLE
In rspec, jobs size is always returning 0

### ISSUE THREAD

**Issue by dyoganand** [mperham/sidekiq#3007]
Rails 4.2.6, Ruby 2.3.0
Using ActiveJob, and have set the queue_adapter as :sidekiq
In rspec,
expect { job }.to change { Sidekiq::Worker.jobs.size }.by(1) - passes
expect { job }.to change(Sidekiq::Worker.jobs, :size).by(1)  - fails, and returns 0 always. Why is it so???

**Comment by petergoldstein** [comment]
So I thought @brandonhilkert fixed the breaking change on this a while back, but it may be worth revisiting the discussion in issue #2663  .  The observed behavior sounds similar, and the problem may have been reintroduced.

**Comment by brandonhilkert** [comment]
@dyoganand Can you share your `Gemfile.lock`?

**Comment by dyoganand** [comment]
@brandonhilkert here it is http://pastebin.com/yLexRZBF

**Comment by mperham** [comment]
Do we expect jobs which go through ActiveJob to integrate with our testing functionality?  I'd think not.  If you use ActiveJob in your tests, you should be using AJ's testing functionality too.

**Comment by dyoganand** [comment]
Well, I would use AJ's testing functionality if I set the `queue_adapter` as `:test`, which can then be tested by checking the `ActiveJob::Base.queue_adapter.enqueued_jobs` array. In this specific case, the queueing system is set as sidekiq for testing, and `require 'sidekiq/testing'` is included in rails_helper.rb.. Hence expected the 'Sidekiq::Worker.jobs' array to accumulate the jobs. It actually does, but when the jobs array size is checked in 2 different ways, one passes while the other fails.

It seems [#2663](https://github.com/mperham/sidekiq/issues/2663) is exactly the same issue.

**Comment by mperham** [comment]
Right, this is because Sidekiq::Worker.jobs no longer returns the same, mutable array but recreates the results on each call:

```ruby
      def jobs # :nodoc:
        Queues.jobs_by_queue.values.flatten
      end
```

I'm content to call this a breaking change in the 4.0 upgrade and leave it as is.  Other opinions?
