### ISSUE TITLE
Use your commercial license

### ISSUE THREAD

**Issue by vasilakisfil** [mperham/sidekiq#3010]
Interesting blog post here: http://www.mikeperham.com/2015/11/23/how-to-charge-for-your-open-source/

However I think MIT license (as you also mention) is not appropriate for license based software. Do you mind if I copy your license (and modify where is appropriate) for my fremium software I am developing ?

**Comment by mperham** [comment]
You are welcome to modify and use my license with the understanding that I make no claims or warrant its fitness for use in your part of the world.  Every state and country is different.

Inspeqtor Pro also has a custom license, more appropriate to its pricing model, which you are welcome to  also. https://github.com/mperham/inspeqtor-pro/blob/master/COMM-LICENSE
