### ISSUE TITLE
Adding a limit to Scheduled::Enq?

### ISSUE THREAD

**Issue by jonhyman** [mperham/sidekiq#3012]
Hey Mike,

Check out these crazy graphs. What I believe happened is that, we had something like a million or few million jobs all set to run at 3:30pm ET today. Let's just say it was 1M jobs.

![image](https://cloud.githubusercontent.com/assets/832655/15993801/7dafc5da-30bf-11e6-9f5e-966a687c7250.png)

![image](https://cloud.githubusercontent.com/assets/832655/15993804/876bafe4-30bf-11e6-99cb-7b21dfc8c63b.png)

We have a lot of workers running. I think that the line https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb#L20 

```ruby
while job = conn.zrangebyscore(sorted_set, '-inf'.freeze, now, :limit => [0, 1]).first do
```

was basically causing every worker to loop over those 1M jobs and all call zrangebyscore and zrem on them in a thundering herd, because they did not get any chance to sleep due to this loop. The `wait` method won't get called until all the jobs have been moved over. But since we probably also had a million jobs set to run around 4pm and 4:30pm ET, it just kept going until all were moved over.

I'm thinking about writing my own `Sidekiq::Scheduled::Enq` that only lets the loop iterate, say, `Sidekiq.options[:scheduled_enq_max_loop]` times before returning, which then lets the `Poller` perform its `wait` method. Thoughts on that?

**Comment by jonhyman** [comment]
Eh actually I'll probably write our own Enq. Given how many workers we have and how many jobs we schedule, it's quite inefficient for them all to loop calling zrangebyscore with only one winner doing a zrem. We run through probably a hundred  million scheduled jobs each day, so I can do something more efficient.

**Comment by mperham** [comment]
Have you looked at the reliable scheduler?

**Comment by jonhyman** [comment]
We can't use it because of custom Middleware I have hacked into the enqueuing of jobs, unfortunately.

**Comment by jonhyman** [comment]
Will close this and write my own thing.

**Comment by mperham** [comment]
Yeah, I think at your scale more and more components need to be custom.

**Comment by jonhyman** [comment]
For posterity if anyone finds this issue, I just subclassed Enq that calls super inside a semaphore and it seems to have been helpful.

**Comment by mperham** [comment]
You mean a redis semaphore?  An in-process Mutex certainly wouldn't help.

**Comment by jonhyman** [comment]
Yup. It's a semaphore that uses `Sidekiq.redis_pool` to store state. It's a slight modification to the semaphore code I demo'd at RedisConf, https://github.com/jonhyman/redisconf-concurrency-2016/blob/master/lib/semaphore.rb that better handles staleness by using key rotation.
