### ISSUE TITLE
Issue with labels on standalone monitor using GitHub OAuth

### ISSUE THREAD

**Issue by dustinsgoodman** [mperham/sidekiq#3013]
We're trying to stand up a standalone monitoring app but we're seeing some inconsistencies with the UI that are of concern. Specifically, the UI labels don't update across apps. In my screenshots below, you can see that the rails application says that the "greenlights" queue is paused whereas the monitor app does not indicate the same information. Did some digging into how the queue pausing works in Sidekiq Pro and and how the UI renders and there aren't any clear indications as to what is causing this one.  I've updated the config.ru recently to match all the gotchas and suggestions in the wiki to no avail. Any ideas what we're missing or is this an actual bug in Sidekiq Pro?

**Main App**
ruby 2.1.2
rails 4.0.7
sidekiq 4.1.1
sidekiq-ent 1.2.1

**Monitor App**
ruby 2.3.0
sinatra 1.4.7
sidekiq 4.1.1
sidekiq-ent 1.2.1

```
# config.ru
require 'dotenv'
require 'sidekiq'
require 'sidekiq-ent'
require 'sidekiq/web'
require 'sidekiq/pro/web'
require 'sidekiq-ent/web'
require 'sinatra_auth_github'

# Load local .env file
Dotenv.load

# Configure Sidekiq client
sidekiq_opts = { url: ENV['REDIS_URL'], size: 10 }
sidekiq_opts[:namespace] = ENV['REDIS_NAMESPACE'] if ENV['REDIS_NAMESPACE']
Sidekiq.configure_client { |config| config.redis = sidekiq_opts }

# Use Github OAuth to authenticate users
module Sidekiq
  class Web
    set :session_secret, ENV['RACK_SESSION_COOKIE']

    set :github_options, {
      scopes: 'user',
      client_id: ENV['GITHUB_CLIENT_ID'],
      secret: ENV['GITHUB_CLIENT_SECRET']
    }

    register Sinatra::Auth::Github

    before do
      authenticate! if ENV['RACK_ENV'] == 'production'
      github_organization_authenticate!(ENV['GITHUB_ORGANIZATION']) if ENV['GITHUB_ORGANIZATION']
    end

    get '/logout' do
      logout!
    end
  end
end

run Sidekiq::Web
```

```
[4] pry(main)> q = Sidekiq::Queue.new('greenlights')
=> #<Sidekiq::Queue:0x007f81f4ea9840 @name="greenlights", @rname="queue:greenlights">
[5] pry(main)> q.pause
=> "OK"
[6] pry(main)> q.paused?
=> "true"
```

<img width="1392" alt="screen shot 2016-06-12 at 4 59 51 pm" src="https://cloud.githubusercontent.com/assets/1815379/15993786/2ebfc16e-30bf-11e6-8c40-b32e8271bac6.png">
<img width="1392" alt="screen shot 2016-06-12 at 4 59 55 pm" src="https://cloud.githubusercontent.com/assets/1815379/15993787/2ebfe75c-30bf-11e6-8c2b-4d55fb311f9f.png">

**Comment by mperham** [comment]
`q.pause` is not an API method.  `q.pause!` or `q.paused?` are the only methods.  I'm not sure what `q.pause` is.

Looks like you might be talking to two different Redis instances?

**Comment by dustinsgoodman** [comment]
Hey @mperham. Thanks for the quick response. 

I can't exactly explain this one but `q.pause!` does not work for us in practice. It does change the UI indicator but the queue in question doesn't actually pause. What's more interesting is the UI behavior change completely. `q.pause!` actually changed our standalone monitor to have the flag whereas the in app flag never appears. First thing I did was ensure that both applications are pointing at the same Redis instance so I can confirm that isn't the issue we're experiencing. Do you have any other suggestions by any chance?

**Comment by mperham** [comment]
Are you using any 3rd party Sidekiq extensions?

**Comment by dustinsgoodman** [comment]
We have [sidekiq-limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch) and [sidekiq-symbols](https://github.com/aprescott/sidekiq-symbols) installed as well. Just a quick peak at the documents tells me that limit_fetch is the problem. That's where the `#pause` method was coming from and the nice warning regarding incompatibilities with sidekiq-pro.

Whelp, I fixed my problem. Installing and configuring limit_fetch on my monitoring app got the behavior I was expecting. Going to talk to my team about killing limit_fetch in the near term but I'm good to go now. Thanks for the good leading questions!
