### ISSUE TITLE
web api support for json format?

### ISSUE THREAD

**Issue by camallen** [mperham/sidekiq#3014]
I've got a use case for exposing the list of running sidekiq processes via json requests. Is this something that would be useful as a PR to the existing web api? 

e.g. with header `Accept: application/json`  get sidekiq/busy` would return something like 
```
{ processes: [ {process_object: data}..], jobs: [ {job_data: data}..] }
```

**Comment by mperham** [comment]
The web UI is not meant to be a comprehensive set of JSON resources -- it's human focused. If you need some API data in JSON form, you can expose the API in your own endpoint. As you point out, it should be very easy to do.

**Comment by camallen** [comment]
Cool - thanks for the prompt response.
