### ISSUE TITLE
Enqueued showing 46 years ago

### ISSUE THREAD

**Issue by cameronmccord2** [mperham/sidekiq#3016]
![screen shot 2016-06-14 at 4 27 01 pm](https://cloud.githubusercontent.com/assets/2424811/16061875/dc5dd1c4-324c-11e6-9b1e-41b909e699e8.png)

The job was created by running 
```ruby
self.class.perform_in(5.minutes, {"album_to_item_id"=>10016, "user_id"=>1})
```

Versions:
ruby 2.2.1p85
Sidekiq 3.4.2
Rails 4.2.5.1
redis-cli 3.0.0

/config/sidekiq.yml file:
```yml
:queues:
  - [createAlbumOnFacebook, 7]
  - [uploadItemToFacebook, 5]
  - [generateCollage, 4]
  - [processRemoteImages, 4]
  - [default, 4]
  - [deleteItemFromFacebook, 3]

:concurrency: 5
```

/config/initializers/sidekiq.rb
```ruby
Sidekiq.default_worker_options = { 'backtrace' => true }
```

This isn't a show stopper bug.

**Comment by mperham** [comment]
It's because it's not enqueued yet, just scheduled.  😆
