### ISSUE TITLE
Sidekiq + Grape == boom?

### ISSUE THREAD

**Issue by mshappe** [mperham/sidekiq#3017]
I have the beginnings of a Grape API defined more or less according to the guidelines [here](http://funonrails.com/2014/03/building-restful-api-using-grape-in-rails/).

In `config/routes.rb`:
```
mount API::Root => '/'
```

in `config/application.rb`:
```
  config.paths.add File.join('app', 'api'), glob: File.join('**', '*.rb')
  config.autoload_paths += Dir["#{config.root}/lib","#{config.root}/app/workers/**/","#{config.root}/app/services/**/","#{config.root}/app/api/**/"]
  config.eager_load_paths += ["#{config.root}/app/api/**/"]
```

Normal rails loads things fine.

Sidekiq does not:

```
uninitialized constant API::Root
/Users/michael/projects/fizz-api/config/routes.rb:85:in `block in <top (required)>'
```

Note above that I am already following the advice regarding `eager_load_paths`...

Sidekiq v4.1.1
Rails 4.2.4
Grape 0.16.2

**Comment by mperham** [comment]
Rails already autoloads anything under `app/`.  I'd remove all your custom path config and ensure your files all follow Rails naming conventions so they autoload properly.
