### ISSUE TITLE
Question regarding retry

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [mperham/sidekiq#3018]
Currently we have this unique situation that we can't retry the jobs that we queue (stupid, but it is so).  

Currently we have set:

```ruby
Sidekiq.default_worker_options = { retry: 0 }
```

When I SIGTERM the process I would expect the job to end up in the dead queue, though it is just thrown away. Is there a way to make it end up in the dead queue?

We are using Sidekiq 4.1.2

**Comment by mperham** [comment]
`retry: 0` is how you send failed jobs to the DJQ immediately upon
exception.  If they are being lost, it's likely because Sidekiq is not
getting the chance to shut down cleanly.

**Comment by segantii-alex-falkowski** [comment]
I'm just using foreman to start a process and Ctrl + C on my local machine.

**Comment by segantii-alex-falkowski** [comment]
Cool you are right. foreman start -t 15 will wait. I don't want it to go to the Enqueued can I make it go to the Dead queue?

**Comment by mperham** [comment]
Nope, dead set is only for jobs which raised unexpected errors. Easiest thing you can do is rescue Sidekiq::Shutdown and immediately return. Job will be considered successful and not re-enqueued.

**Comment by segantii-alex-falkowski** [comment]
What is deemed an unexpected error?

**Comment by segantii-alex-falkowski** [comment]
Can I rescue Sidekiq::Shutdown from ActiveJob?

**Comment by mperham** [comment]
Any error raised by a job is unexpected.  ActiveJob can rescue any type
afaik.

**Comment by segantii-alex-falkowski** [comment]
OK thanks for your help :)
