### ISSUE TITLE
Need a specific way to handle unicity of jobs

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#3020]
Hi,

I have a specific need.
I want to be able the specify how the job is uniq.
So I can have :
 - Many jobs uniques between them;
 - A job with many params uniq only based on a subset of them

I believe I need to develop a middleware for it.

How can I do it ?
Do you have any recommendation ?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Related-Projects#unique-jobs
