### ISSUE TITLE
How to delay a failed job retry?

### ISSUE THREAD

**Issue by leemour** [mperham/sidekiq#3021]
I have a lot of jobs failed and I need to delay their retry time by several hours. How can I do this? I also don't want all jobs to be enqueued at the same time but in an interval, say 1 hour between 1000 jobs. Is it possible?

**Comment by mperham** [comment]
None of that is possible out of the box but you can use the [API](https://github.com/mperham/sidekiq/wiki/API) to script it.

**Comment by leemour** [comment]
In case someone has this problem, I solved it using this code:
```ruby
rs = Sidekiq::RetrySet.new

job_ids = rs.map &:jid
job_ids.each_slice(100).with_index do |group, hour|
  group.each do |jid|
    job = rs.find_job(jid)
    interval = Time.now + hour.hours
    job.reschedule(interval)
  end
end
```

I know it uses inefficient `find_job` but iteration over jobs using `Sidekiq::RetrySet.new.each` would never finish (I only have 500 retry jobs). Probably because I was rescheduling them inside loop.

**Comment by atomical** [comment]
Is this available in Sidekiq Pro?
