### ISSUE TITLE
sidekiqswarm logging

### ISSUE THREAD

**Issue by nwalke** [mperham/sidekiq#3023]
We'd love to keep logs that the sidekiqswarm process spits out (like this: https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#memory-monitoring), but our workers are generally too noisy at the `INFO` level for us to keep all of our logs.  

It would be nice if there was a way to either prefix sidekiqswarm specific messages or direct them at a specific syslog facility.

**Comment by mperham** [comment]
Have you bumped up the logging level to WARN?  That should dramatically cut down on the noise.  Something like this should work:

```ruby
Sidekiq.configure_server do |config|
  config.logger.level = Logger::WARN
end
```

Right now, the swarm code uses `puts` to log directly to STDOUT but it should use a prefix so you can at least grep.

**Comment by nwalke** [comment]
We had not.  I'm in the process of doing that now.  Thanks!
