### ISSUE TITLE
Slow and steady memory usage increase in skeleton Sidekiq app. 

### ISSUE THREAD

**Issue by crazydog115** [mperham/sidekiq#3024]
I set up a skeleton sidekiq application on Heroku to see if I could reproduce an issue I'm experiencing in a production application, where the Sidekiq process sloooowly uses more and more memory. Like, 20 MB per hour.

[Here is the application](https://github.com/crazydog115/sidekiq-memory-test) that's been running. I enabled heroku's [log-runtime-metrics](https://devcenter.heroku.com/articles/log-runtime-metrics) feature, and [here is the output from the last boot of the application until now](https://gist.github.com/crazydog115/2dbedad5f6f706f3628b773a761bc60d).

As you can see, over a period of nearly two hours, the RSS usage has increased from 59.94 MB at dyno boot time (or perhaps 79.56 MB after stabilizing a bit) up to 101.29 MB. This almost corresponds exactly to the 20 MB/hour memory usage increase seen in my production environment.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#no-leak-issues-please
