### ISSUE TITLE
Sidekiq fails, dequeueing mongoid connection times out, probably too many connections

### ISSUE THREAD

**Issue by ChristofferJoergensen** [mperham/sidekiq#3026]
In order to get to the bottom of this issue I have created [this open Stackoverflow bounty](http://stackoverflow.com/questions/37898574/sidekiq-fails-dequeueing-mongoid-connection-times-out-probably-too-many-connec). Feel free to contribute wherever you prefer, then I'll draft a summery afterwards.

I am currently running `sidekiq 4.1.2`. I've never managed to be able to run more than a handfull of jobs concurrently. Recently it's been looking like I've run into an issue described in the Sidekiq's Troubleshooting WIKI called [Too many connections to MongoDB](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#too-many-connections-to-mongodb). Apparently, `mongoid 3` doesn't properly disconnect workers. However, I am using `mongoid 5.1.3`.

My issue surfaces when a job, while a few other jobs are running, tries to hit the database with a query:

    Timeout::Error: Timed out attempting to dequeue connection after 30 sec.
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:190:in `wait_for_next!'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:176:in `block in dequeue_connection'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:190:in `wait_for_next!'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:176:in `block in dequeue_connection'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:172:in `loop'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:172:in `dequeue_connection'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:62:in `block in dequeue'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:61:in `synchronize'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool/queue.rb:61:in `dequeue'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool.rb:51:in `checkout'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/connection_pool.rb:107:in `with_connection'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/server/context.rb:63:in `with_connection'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/operation/executable.rb:34:in `execute'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/collection/view/iterable.rb:80:in `send_initial_query'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/collection/view/iterable.rb:41:in `block in each'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/retryable.rb:51:in `call'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/retryable.rb:51:in `read_with_retry'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongo-2.2.5/lib/mongo/collection/view/iterable.rb:39:in `each'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/query_cache.rb:207:in `each'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/contextual/mongo.rb:121:in `each'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/contextual/mongo.rb:295:in `map'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/contextual/mongo.rb:295:in `map'
    /home/me/applications/myapp/shared/bundle/ruby/2.2.0/gems/mongoid-5.1.3/lib/mongoid/contextual.rb:20:in `map'
    /home/me/applications/myapp/releases/20160618143407/app/jobs/myjob.rb:8:in `block in perform'

After one job fails, the other jobs fail soon after. This most often happens after a few handfull of jobs have finished succesfully, which could indicate that those jobs don't disconnect from the database. Looking at `top` I can't see that mongo load cpu is too much.

At the same time this started to occur, I noticed that my `sidetiq 0.7.0` enabled recurring jobs were not scheduled properly. One job has stopped being queued, and others are only queued once after restart.

According to my Sidekiq web interface I have 1 queue, called **default**, with 25 threads. Max. 12-15 of them get busy at the same time.

Any idea how to troubleshoot this issue?

**Comment by mperham** [comment]
I don't know anything about Mongoid.  I hope something with that project can help you.

**Comment by ryansch** [comment]
We're still on 4.x but I know @jonhyman has some experience with newer mongoid.

**Comment by jonhyman** [comment]
I can't use the supported driver's connection pooling since we use multiple databases (and they open up a new pool on a per-database level instead of a per-host:port level, which causes our mongoS to run out of file descriptors and they don't want to support that architecture because of privilege delegation). I'm on my own custom fork of the driver that has a bunch of other stuff we rely on.

Do you have monitoring on your mongoD/mongoS such as MMS where you can graph connection counts and see how they rise/fall?

Though the likely situation is that the mongo ruby driver's max pool queue size is 5 (you can update it via `max_pool_size` in your mongoid.yml as an option). Since you have 25 concurrency in Sidekiq but are stuck with a driver pool size of 5, you're likely running into contention there. I'd bump up your `max_pool_size` or drop the concurrency down to 5 or less.

**Comment by ChristofferJoergensen** [comment]
Thanks for for helping out. I have bumped up `max_pool_size`, so my config now looks like this:

    production:
      clients:
        default:
          database: mydb
          hosts:
            - localhost:27017
          options:
            heartbeat_frequency: 10
            local_threshold: 5
            server_selection_timeout: 30
            max_pool_size: 100
            min_pool_size: 1
            wait_queue_timeout: 30
            connect_timeout: 30
            socket_timeout: 30
      options:
        use_activesupport_time_zone: true
        use_utc: false

I will let it run on the server for a day, and then I will update with the result. Again, thanks for taking the time to help out!

**Comment by jaymanklu** [comment]
@ChristofferJoergensen can you update us with your findings after you increased `max_pool_size`?

**Comment by ChristofferJoergensen** [comment]
Yes, it did help to increase `max_pool_size`.

My config now looks like this.

    production:
      clients:
        default:
          options:
            max_pool_size: 25

However, I don't seem to be allowed to use all 25 workers at the same time. I will try to experiment with more queues. Currently, all my job types run in the same default queue.

**Comment by jonhyman** [comment]
Ruby isn't truly multi threaded and has a global interpreter lock, so depending on the types of jobs you have, you may not use the concurrency you set. We opt for multiple processes with lower concurrency but ymmv
