### ISSUE TITLE
Consider keeping a succeeded batch in a list for 24hrs

### ISSUE THREAD

**Issue by krasnoukhov** [mperham/sidekiq#3027]
I was just thinking that it could be very useful to see a list or recent batches in a Web UI, just for a quick glance. So since batch hash is being kept anyway now for internal reasons (#3011), it might make sense to keep the bid in a list as well.

I tried implementing that myself, like pushing it back on success, but since callbacks are ran _before_ batch is removed from a list, it does not seem like solution is obvious on app side.

So my suggestion would be just to replace `zrem('batches'.freeze, bid)` call with `zremrangebyscore('batches'.freeze, '-inf'.freeze, Time.now.to_f - 86400)` in a `Sidekiq::Batch::Callback`, which should not add a lot of overhead or introduce a Redis memory leak. This way batch will still be removed from a list if `delete` is called directly on a batch object.

Please let me know if you want me to send a PR, I'd love to. Thanks!

**Comment by mperham** [comment]
The issue I see is that many companies create many thousands of batches daily.  The Web UI would be overwhelmed with batches that have already finished successfully.

**Comment by krasnoukhov** [comment]
Ok, that makes sense. Maybe this is something that can be enabled with a flag? Feel free to close this otherwise. Thanks!

**Comment by mperham** [comment]
I avoid config knobs.  If you want to monkeypatch in that behavior, anything is fair game.
