### ISSUE TITLE
Unable to delete sidekiq job retries in Rails

### ISSUE THREAD

**Issue by TanookiMario** [mperham/sidekiq#3030]
Using sidekiq version 4.1.2
Using rails version 4.2.5.2

1. Create a sidekiq job that fails and needs to retry
2. Visit your rails sidekiq dashboard
3. Go to the retries page
4. Click the checkbox next to a retried job and click 'delete'

At this point I get a blank page that says 'forbidden' and it deletes my session. The POST returns a 403: forbidden

**Comment by seuros** [comment]
Use Firefox or https://github.com/mperham/sidekiq/issues/2910#issuecomment-206978212

**Comment by TheJefe** [comment]
using firefox does not fix this issue, nor does setting in config.ru

```ruby
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
Sidekiq::Web.set :sessions, Rails.application.config.session_options
```

same result when using `secret_token_base` instead of `secret_token`.

We are using sidekiq-pro, does that make a difference?

**Comment by mperham** [comment]
Firefox won't solve this problem.  Sidekiq Pro shouldn't make a difference.

You need to hook up your Rails session to Sinatra.  Since you configure the session, you need to pass it to Sinatra too.  Sidekiq can't do it.

**Comment by TheJefe** [comment]
I was able to fix our issue by upgrading the sinatra gem. We were still on 1.3.6, I upgraded us to 1.4.7 and it fixed it for us.

It might make sense to move sinatra from a development dependency, to a regular dependency? wdyt ?

**Comment by mperham** [comment]
@TheJefe Sinatra is a dev dependency because the Web UI is optional but you are right that it would safer to control the minimum version.

**Comment by epintos** [comment]
Upgrading Sinatra didn't work for me

**Comment by outpark** [comment]
Upgrading Sinatra didn't work for me either. I'm having a trouble understanding "hook up your Rails session to Sinatra" too. Could someone help me?

**Comment by esparkman** [comment]
Firefox worked for me, after I setup Nginx and passing my session to Sinatra. However Chrome still did not work.
