### ISSUE TITLE
[Question] is Sidekiq queue a stack?

### ISSUE THREAD

**Issue by alexsotocx** [mperham/sidekiq#3031]
It's a strange question, But when I push a job using Sidekiq API and loop over the queue jobs it works like a stack Last In First Out
```ruby
q = Sidekiq::Queue.new("mailer")
Sidekiq::Client.push('queue' => q.name, 'class' => "None", 'args' => ['message1'])
Sidekiq::Client.push('queue' => q.name, 'class' => "None", 'args' => ['message2'])
Sidekiq::Client.push('queue' => q.name, 'class' => "None", 'args' => ['message3'])
q.each do |job|
  puts job.args
end
```

And the ouput
```
message3
message2
message1
```

Is there a way to make it work like a queue FIFO?

EDIT: Sidekiq version 4.1.2

**Comment by mperham** [comment]
How it is iterated is not how it is processed. I iterate backwards so you can safely remove elements while iterating.

**Comment by alexsotocx** [comment]
I see, I'm trying to something a bit hacky, I'm pushing some elements to the queue (I'm using this time sidekiq as an interface to push a job to Redis) and in a job using Sidekiq-scheduler (3rd party gem) I want to empty that queue.

That's why I'm asking if there is a way to process or iterate over it in the order they arrive.

Thanks.

If there is no way I just simply reverse they array and done :)

**Comment by mperham** [comment]
Depending on the size of the queue, doing `Sidekiq::Queue.new("foo").to_a.reverse` might be easiest.  If all you want to do is pull elements, you can do it yourself with something like this:

```ruby
loop do
  elm = Sidekiq.redis do |conn|
    conn.lpop("queue:my_queue") # or rpop, I forget which
  end
  break unless elm
  hash = JSON.parse(elm)
  process(hash)
end
```

Of course that has no error handling, retries, logging, etc.

**Comment by alexsotocx** [comment]
Thanks, I was thinking the same :) I made an wrapper for that.
