### ISSUE TITLE
Rails Sidekiq ERROR: can't find object 

### ISSUE THREAD

**Issue by SupremeA** [mperham/sidekiq#3032]
I have several sidekiq workers in my rails 4 app and can't figure out why the processes are failing. I am passing the User_id to the worker as a string but it can't seem to find the user. But when I search the same id in my console it finds the user. What am i doing wrong? Here is my code. I am using Mongoid 5.1.0 for my DB.

Controller.rb

      def update
       @user = current_user
        if @user.bill.update_attributes(bill_params)
          RandomWorker.perform_async(@user.id.to_s)
          redirect_to users_dashboard_path, :notice => "Payment Informaton Updated"
        else
          ...  
        end
      end

Randomworker.rb
    
      def perform(user_id)
        user_id = user_id["$oid"] unless user_id.is_a?(String)
        user = User.find(user_id)
        user.process.update_report 
        user.process.save
      end

My error comes back as

    RandomWorker  "575a..." Mongoid::Errors::DocumentNotFound: message: Document(s) not found for class User with id(s) 575a.... summary: When calling User.find with an id or array of ids, each parameter...

--EDIT--

My db config file is as shown:

    development:
     adapter: sqlite3
     database: db/development.sqlite3
     pool: 5
     timeout: 5000

    production:
     adapter: sqlite3
     database: db/production.sqlite3
     pool: 25
     timeout: 5000

And my mongoid.yml 

    development:
       # Configure available database clients. (required)
         clients:
       # Defines the default client. (required)
           default:
       # Defines the name of the default database that Mongoid can connect to.
       # (required).
             database: development_db
       # Provides the hosts the default client can connect to. Must be an array
       # of host:port pairs. (required)
             hosts:
                - localhost:27017
             options:

**Comment by mperham** [comment]
The error message makes sense to me: "575a..." is not a valid user_id.  Pass a value to `perform_async` that you can actually use to look up the user.

**Comment by matthewford** [comment]
I've come across this with mongoid 7, and sidekiq 5, adding a significant delay and multiple retries helps
