### ISSUE TITLE
ERR max number of clients reached on heroku

### ISSUE THREAD

**Issue by SupremeA** [mperham/sidekiq#3033]
I need to know how to fix or reset this error. I know you can pay for more connections but my app only has me testing in production. I don't believe the connections are closing which caused the problem. How do I fix this on heroku. Cant seem to find an answer other than increasing the concurrency in a sidekiq.yml file and that doesn't solve it

sidekiq.yml

    # Configuration file for Sidekiq.
    # Options here can still be overridden by cmd line args.
    # Place this file at config/sidekiq.yml and Sidekiq will
    # pick it up automatically.

    :concurrency:  25
    :timeout: 8

**Comment by mperham** [comment]
Set the concurrency **lower**, to 5 maybe.
