### ISSUE TITLE
How to clean the "uniq keys" ?

### ISSUE THREAD

**Issue by Micka33** [mperham/sidekiq#3034]
I am using the uniq job feature.

At some point I accidentally deleted some jobs that were in retry.
I gone through redis and found some keys `namespace:uniq:783409erjfhdy3`.
Deleting them made my sidekiq accept jobs again.

Now, it regularly happen that my sidekiq is not accepting jobs, even though none are running nor did I delete them.

Is there something I missed ?

For example, right now I have 15 of these keys, but no jobs running nor in retry.
```
irb(main):001:0> $redises.KEYS("#{ENV['SIDEKIQ_NAMESPACE']}:uniq*")
=> ["mynamespace:unique:1fb8de64133b73a49a8afae3ea7422a56e5e8250",
 "mynamespace:unique:c6fe5680abfb96461d89b726763a1a8619c8bddc",
 "mynamespace:unique:b4e520248d67e2e9ec4a1ecb635697a0a6f247b0",
 "mynamespace:unique:c088e9cbfb0b88c06fdac3c451027aef1922803a",
 "mynamespace:unique:40c8aa81e8928f81767add6052e7d8f943a90438",
 "mynamespace:unique:6b53b31679503cc282955579b5d089d2533db093",
 "mynamespace:unique:fbb9461dd5f42630ab542ad4bf473bd4c7e45770",
 "mynamespace:unique:9c2d75c9064be011351479f510934e2b2a13f552",
 "mynamespace:unique:f587caaa406becaaa362d92c8bcfab4ba9c9f4de",
 "mynamespace:unique:3c0ab730c525f47507855692c4004e6c07c883e9",
 "mynamespace:unique:c1c756035c1312215f1768319b726bfaf2f44d38",
 "mynamespace:unique:da4a5f3513569a67dd9d131902ed04f77f4b7ba3",
 "mynamespace:unique:5c66d414e465205c3b8414cb20eb842de81b40ba",
 "mynamespace:unique:3bc8e7bbd3d8a254b25a395e037cd40f8b44651e",
 "mynamespace:unique:0b38c94ccc5f31292fe023c9054f52af47ce6b54"]
irb(main):002:0> $redises.KEYS("#{ENV['SIDEKIQ_NAMESPACE']}:uniq*").count
=> 15
```

**Comment by mperham** [comment]
Those keys will automatically expire once the `unique_for` expiry period has passed.

**Comment by Micka33** [comment]
Indeed, but I often don't want to wait that much time before I try again.

Allow another question:
 - Can a job succeed and leave its uniq key untouched ?

**Comment by mperham** [comment]
1. https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#bypassing-uniqueness
2. Nope, once a job has succeeded, it removes the lock so the same job can be enqueued again.
