### ISSUE TITLE
Sidekiq Pro Lua Scheduler runs only once

### ISSUE THREAD

**Issue by HenleyChiu** [mperham/sidekiq#3037]
Taking a look at your code for scheduler.rb, in Sidekiq Pro, it doesn't seem like enqueue_jobs is happening in an infinite loop, with a sleep.

https://github.com/mperham/sidekiq-pro/blob/3ee4bc276385b4b6099c5d56bd56bd83690c387a/lib/sidekiq/pro/scheduler.rb

In the Sidekiq code, the scheduler is in a constant loop with a sleep interval period.
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/scheduled.rb

```
def start
        @thread ||= safe_thread("scheduler") do
          initial_wait

          while !@done
            enqueue
            wait
          end
          Sidekiq.logger.info("Scheduler exiting...")
        end
      end
```

Is this a bug?
I am asking because I am noticing that retries + scheduled jobs are not being queued over and over. It happens only when the workers first initialize/start.

**Sidekiq versions**:
sidekiq-3.4.2
sidekiq-pro-2.1.0
redis 3.0.7
ruby 2.1.2
Rails 3.2.13

(Pro Customer)

**Comment by mperham** [comment]
You should update Sidekiq and Sidekiq Pro if possible, looks like you're about a year behind.

The sleep is done in that `wait` call.  When the system first boots, it performs an `initial_wait` and then settles into a steady loop of wait / enqueue.  That `start` method that you've shown is the main scheduler loop in Sidekiq Pro too.
