### ISSUE TITLE
sidekiq_retries_exhausted not called when dead is disabled

### ISSUE THREAD

**Issue by sirwolfgang** [mperham/sidekiq#3038]
I was setting up some jobs to use `sidekiq_retries_exhausted` and to report the record as failed after a few attempts. The issue I have found that is if I disable the `dead` queue for that worker, the `sidekiq_retries_exhausted` does not fire. 

Is this by design? Documentation would not lead me to believe this is intended behavior.

**Comment by mperham** [comment]
Not true according to my reading of the code:

1. Call exhausted hook https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/retry_jobs.rb#L142
2. Send to the dead queue https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/retry_jobs.rb#L148

**Comment by sirwolfgang** [comment]
Confirmed expected behavior with isolated testing.
