### ISSUE TITLE
[Pro] Duplicate batched jobs with exact same JID

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#3039]
Hello

We have a couple of long running jobs that run inside a batch. Things start out ok, but right now, those jobs seem to have duplicated. When I look in sidekiq-web, i can see them multiple times in the list in the "Busy" tab. I can also see them on the status tab. The status of the jobs is identical, but i assume this is just because the status library stores it based on JID.

Sidekiq: 4.1.2
Sidekiq Pro: 3.3.1
Sidekiq Failures: 0.4.5
Redis: 3.0.7

Any help would be appreciated.

**Comment by mperham** [comment]
Is it possible the process is dying and the job being restarted?  Is the duplicate listed on the page a minute later?  Are you using reliable_fetch or timed_fetch?

**Comment by scottrobertson** [comment]
Sorry, should have closed this. We have added timed_fetch, and it seems to have solved the issue. 

It's worth noting though, we have been running sidekiq for years, and this has never happened, so I suspect it will be related to Batches since we have added that recently.
