### ISSUE TITLE
Sidekiq Web processes that we cannot find

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#3040]
Hey

There are 2 processes that sidekiq web claims are running. These are nowhere to be seen on the actual server (checked with `ps aux`) and the stop button does nothing to them.

Any ideas?

**Comment by mperham** [comment]
It's possible you've run into #2982.  I need to release 4.1.3 today.

**Comment by scottrobertson** [comment]
Thank you :) shall confirm once that is out and close this ticket.
