### ISSUE TITLE
Jobs stuck as pending on a batch

### ISSUE THREAD

**Issue by mlarraz** [mperham/sidekiq#3041]
See https://github.com/mperham/sidekiq/issues/2474#issuecomment-229337029.

Essentially we have a daily batch where one job always fails (due to a bug in our code, nothing to do with Sidekiq). Somehow this causes 60-70 jobs be stuck "pending" and never get executed.

Creating a new batch with the remaining jobs after the first one gets stuck appears to run without a problem (except the one failure), but ideally this wouldn't be necessary.

Redis version is 3.0.7.

Relevant Gemfile section:

``` ruby
    redis (3.2.2)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    ...
    ...
    ...   
    sidekiq (4.1.2)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-failures (0.4.5)
      sidekiq (>= 2.16.0)
    sidekiq-pro (3.3.0)
      sidekiq (>= 4.0.0)
    sidekiq-scheduler (2.0.5)
      multi_json (~> 1)
      redis (~> 3)
      rufus-scheduler (~> 3.1.8)
      sidekiq (>= 3)
      tilt (~> 2.0)
    sidekiq-unique-jobs (4.0.17)
      sidekiq (>= 2.6)
      thor
```

**Comment by mperham** [comment]
It's possible your unique jobs plugin is causing jobs to be registered in the batch but never actually pushed to Redis to be executed.  Sidekiq Enterprise takes special pains to make sure this won't happen but I can't guarantee it for a 3rd party plugin.

**Comment by mperham** [comment]
Did you find any more detail about this?

**Comment by mlarraz** [comment]
Disabling locking for the worker didn't change anything, but the plugin seems to affect all pushes regardless of whether or not it's enabled for a given worker.

Obviously the next step would be to remove the gem altogether and see if it helps, but I'm more than a little wary of removing all locking.
