### ISSUE TITLE
Cannot remove some jobs from web UI

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#3044]
Ruby version: 2.2.5
Sidekiq / Pro / Enterprise version(s): 
- Sidekiq: 4.1.3 
- Pro: 3.3.1

There are a few jobs that I cannot seem to remove from the queues page. I click the delete button, and it redirects back to the same page.

If i use the `delete_job` method, it works.

**Comment by mperham** [comment]
Unless you can show me an error, I can't tell what's wrong.

**Comment by mperham** [comment]
Any word?

**Comment by scottrobertson** [comment]
I wasn't able to get an error message. No errors in the log etc, just hits the delete endpoint and redirects back.

**Comment by mperham** [comment]
I'm not able to reproduce the issue.  I created 150 jobs and then deleted 10 or so from various pages in the listing.  They disappeared exactly as expected.  The code does not inspect the return value from the Sidekiq::Job#delete method - I'm not sure what could cause it to fail.  Maybe you can add some debugging about the jobs and the delete parameters so we can get more context?

**Comment by scottrobertson** [comment]
@mperham shall give it a go :) feel free to close this for now, and I will open it again when I get more info.

**Comment by scottrobertson** [comment]
@mperham got it. It's returning `303 See Other`

**Comment by mperham** [comment]
The Web UI never returns a 303.  I suspect something wrong/odd with your setup, maybe a Rack middleware?
