### ISSUE TITLE
Long job is being dropped from busy queue

### ISSUE THREAD

**Issue by wafendy** [mperham/sidekiq#3046]
Ruby version: 2.0.0p648
Sidekiq v4.0.1 / Sidekiq Pro v3.0.0

If relevant, please include your initializer and any error message with the full backtrace.

Hi,

For some reason Sidekiq drops my long running jobs after around 20mins or so. They are just disappeared from the busy queue without any trace, no exceptions thrown in sidekiq logs, and no failures reported within Sidekiq Web UI. Sidekiq process (from ps aux command) is also showing 0 processes running. 

Any idea why?

**Comment by mperham** [comment]
Can you reproduce this when running the latest versions?  You should upgrade to the latest versions to pick up bug fixes.

**Comment by liamwhite** [comment]
Do you shell out or otherwise assign $? from within these jobs?
