### ISSUE TITLE
Add support for log stash lograge-style

### ISSUE THREAD

**Issue by iMacTia** [mperham/sidekiq#3049]
I'm in the process of setting up the ELK stack for all our applications to manage log aggregation.
[Lograge](https://github.com/roidrage/lograge) has been extremely useful to compress rails multi-line log into a single-line JSON log.
It would be great to have the same for Sidekiq, so I'm here asking if there's anything already in place (a setting, a plugin, ...) which will do the job.
If that's not the case, what's the preferred course of actions in this case?

1. I write an extension/ monkey-patch sidekiq on my application (suggestions would be welcome in this case)
2. I try to implement and issue a pull request to make it available for everyone (again, direction/suggestions really welcome)
3. You already know how to do it, so I just wait 😄

Thanks,

Mattia

**Comment by mperham** [comment]
```ruby
Sidekiq.configure_server do |config|
  config.logger.formatter = LogrageFormatter.new
end
```

Now you provide LogrageFormatter based on the [default formatter](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/logging.rb#L9).  I'm not aware of an existing plugin but you are welcome to OSS your solution.

**Comment by iMacTia** [comment]
Many thanks, I'll work on it based on the 'default formatter'.
Would you prefer this to be implemented as an additional formatter inside sidekiq gem (PR) or as a standalone plugin-gem?

**Comment by mperham** [comment]
Standalone.  It's small enough that someone can put it in an initializer and customize as necessary.

**Comment by iMacTia** [comment]
As promised: https://github.com/iMacTia/sidekiq-logstash
It's still a WIP and I would like to make it customisable based on input from other developers.
@mperham, I know you're a busy man, but your input would be really much appreciated :)

**Comment by mperham** [comment]
I have no real input but thanks for publishing it; I hope it works well for you and your users.
