### ISSUE TITLE
Callbacks not executed on a batch if not child jobs are defined

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#3050]
Ruby version: 2.2
Sidekiq / Pro / Enterprise version(s): 4.0.2 / 3.0.2 / 1.2.0

If relevant, please include your initializer and any error message with the full backtrace.

I have a set of batches where sometimes some of the data inside the batch needs to be updated, but not always. While iterating and adding necessary jobs to the batch, occasionally none will be added. When this happens, no callbacks are run. I can work around it by checking for that condition and calling the callback explicitly, or I can always add a NOOP job to make sure the callback gets run, but I'd prefer the callbacks to just do their thing regardless of whether or not child jobs are added, seems more intuitive.

**Comment by mperham** [comment]
Could you show some code?  Two points might be relevant to you:

1. Jobs cannot be safely added to a batch "outside" of the batch after the first `jobs` block has finished.  I'm not sure if you are doing that here.
2. It is true that batches with 0 jobs will not run callbacks.  You will need to check for the empty jobs case explicitly.  I could add code to raise an error if a batch is created with no jobs but I don't want to assume I should fire callbacks if no jobs are defined.

**Comment by kreynolds** [comment]
Its clearly #2.

Code-wise is as simple as: 
```
Sidekiq::Batch.new.tap do |child|
  child.on(:success, 'Worker#notify_that_update_is_done')
  child.jobs do
    Model.complex_sql_finder_for_updates.each do |model|
      ModelWorker.perform_async(model.id)
    end
  end
end
```

I understand I can write that in a few different ways to accomplish the same thing, but then I also have to fake the status if the callback uses it. I understand not wanting to make any assumptions, except you are already assuming that the callback shouldn't be called and make it a bit awkward to do so manually. If somebody wants to no-op the callback, imo they should just check @total on the status inside the callback and return.

**Comment by kreynolds** [comment]
And regarding #1, it appears you can under the circumstance that you are only using the `success` callback and not the `completed` callback of the parent batch. If in any callback of a child batch you add another job to the parent batch, it will run, but it could (and probably will) run after the `complete` callback of the parent, but it will definitely run before the `success` callback of the parent. That works reliably at scale at least until the code changes.

**Comment by mperham** [comment]
The implementation has worked this way for years now.  I can't change the semantics at this point; I can't assume that the callbacks are appropriate to run if no jobs execute.  It could also be that having no jobs is an error condition that needs to be reported, not silently ignored.

**Comment by kreynolds** [comment]
If you must keep the current behavior for historical reasons then I guess any other conversation is moot. Would you consider a PR that made that behavior tunable now?

**Comment by kreynolds** [comment]
For posterity, for now I just added a NoopWorker that does absolutely nothing but ensures the callbacks occur. It seems to be the easiest way of making sure the callbacks are fired with an appropriate status object.

**Comment by mperham** [comment]
I try to avoid config knobs and instead document the designed behavior as best I can.  This behavior is undocumented but I think you are right that it deserves to be mentioned to avoid surprise, I will update the wiki.
