### ISSUE TITLE
Net::OpenTimeout while sending mail using sidekiq_delay

### ISSUE THREAD

**Issue by brahamshakti** [mperham/sidekiq#3051]
Hi I am getting error while sending email to user using `sidekiq_delay` method.

![netopentimeout](https://cloud.githubusercontent.com/assets/2370848/16610054/3012ed24-4376-11e6-8155-75a4d152a320.png)

This is what my sidekiq initializer file contain

    Sidekiq.hook_rails!
    Sidekiq.remove_delay!

    Sidekiq.configure_server do |config|
        config.redis = { :url => redis_url, :namespace => 'twistilled', network_timeout: 5}
    end

and I am calling my send email method as

    UserMailer.sidekiq_delay.send_signup_email(current_user)

Here is the log file content for reference

    2016-07-06T02:11:10.878Z 373 TID-1z9m1c WARN: Net::OpenTimeout: execution expired
    2016-07-06T02:11:10.878Z 373 TID-1z9m1c WARN: /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
    /home/rubyist/myapp/shared/bundle/ruby/2.2.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
    /home/rubyist/myapp/shared/bundle/ruby/2.2.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
    /home/rubyist/myapp/shared/bundle/ruby/2.2.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `block in deliver'

Why it is showing net open timeout error? What is going wrong with sidekiq?

**Comment by mperham** [comment]
That means the remote mail server is down.  It's totally normal.
