### ISSUE TITLE
Sidekiq::Extensions::DelayedClass: DONE but email not send [Sidekiq Delay]

### ISSUE THREAD

**Issue by hotanlamvnn** [mperham/sidekiq#3053]
Ruby version: 2.2.4
Sidekiq : 4.1.4
Use: ActionMailer, Rack, ActiveRecord
Without Rails

In case: `UserMailer.password_reset('hotanlam@gmail.com').deliver_now`
```
=> #<Mail::Message:70145266411420, Multipart: false, Headers: <Date: Thu, 07 Jul 2016 13:20:38 +0700>, <From: minhtu250192@gmail.com>, <To: hotanlam@gmail.com>, <Message-ID: <577df4b6aab26_9f2b3fcbf6052204956ea@TanLam.local.mail>>, <Subject: Password reset>, <Mime-Version: 1.0>, <Content-Type: text/html>, <Content-Transfer-Encoding: 7bit>>
```
It's ok, i got the mail

However, in case: `UserMailer.delay.password_reset('hotanlam@gmail.com')`
```
UserMailer.delay.password_reset('hotanlam@gmail.com')
=> "5232c7319fbcdf77e7b96462"

2016-07-07T06:22:32.732Z 40748 TID-oukhi4am0 Sidekiq::Extensions::DelayedClass JID-5232c7319fbcdf77e7b96462 INFO: start
2016-07-07T06:22:32.735Z 40748 TID-oukhi4am0 Sidekiq::Extensions::DelayedClass JID-5232c7319fbcdf77e7b96462 INFO: done: 0.003 sec
```
SidekiqLog done and SidekiqWeb processed but email not send. 

And i cannot `binding.pry` when call `delay` method, but `deliver_now` is ok 
Please, help me.

**Comment by mperham** [comment]
Show us the usermailer code.

**Comment by hotanlamvnn** [comment]
```
# app/mailers/mailer.rb
class Mailer < ActionMailer::Base
  default from: 'mymail@gmail.com'
  layout 'mailer'
end
```
```
require './app/mailers/mailer.rb'
class UserMailer < Mailer
  def password_reset(user)
    @user = user
    mail(to: user.email, subject: 'Password reset') do |format|
      format.html
    end
  end
end
```

**Comment by mperham** [comment]
`Sidekiq::Extensions::DelayedClass`

This should say `Sidekiq::Extensions::DelayedMailer`.  Do you need to restart Sidekiq to pick up your code changes?

**Comment by hotanlamvnn** [comment]
i tried so many times, but it's still not work

**Comment by mperham** [comment]
Show your initializer.

**Comment by hotanlamvnn** [comment]
In config.ru
```
require 'sidekiq'
require 'sidekiq/api'
require 'grape'
require 'action_view'
require 'grape-rabl'
require 'rails/railtie'
require 'rails/all'
require 'active_support/dependencies'
require 'i18n'
require 'logger'
require './app/api/root_v1'
require './db/connect.rb'
require './config/action_mailer.rb'
require 'rack/cors'
require_dependency './app/mailers/user_mailer.rb'

use Rack::Cors do
  allow do
    origins '*'
    resource '*', headers: :any, methods: [:get, :post, :options, :put, :delete]
  end
end

use Rack::Config do |env|
  env['api.tilt.root'] = 'app/views/api'
end

Config ActionMailer
```
ActionMailer::Base.raise_delivery_errors = true
ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  address:                'smtp.gmail.com',
  port:                       587,
  authentication:       :plain,
  user_name:            < myemail@gmail.com >,
  password:              < mypassword >,
  enable_starttls_auto: true
}
ActionMailer::Base.view_paths = File.join(Rack::Directory.new('').root, '/app/views')
```

**Comment by hotanlamvnn** [comment]
And Gemfile

```
source 'https://rubygems.org'

gem 'rack', platforms: :ruby
gem 'activerecord', platforms: :ruby
gem 'pg', platforms: :ruby
gem 'grape'
gem 'grape-rabl'
gem 'yajl-ruby', require: 'yajl'
gem 'standalone_migrations', platforms: :ruby
gem 'unicorn'
gem 'activesupport'
gem 'racksh'
gem 'rack-cors', require: 'rack/cors'
gem 'actionmailer', require: 'action_mailer'
gem 'axlsx'
gem 'redis'
gem 'sidekiq'
gem 'i18n'
```

**Comment by mperham** [comment]
I think your problem is that you're booting everything manually.  Put sidekiq below rails.

**Comment by hotanlamvnn** [comment]
sorry
but my project is not allowed to use the rails :(

**Comment by mperham** [comment]
You are requiring it right here:

```
require 'rails/railtie'
require 'rails/all'
```

**Comment by hotanlamvnn** [comment]
Because I try to use sidekiq :(((((((

**Comment by mperham** [comment]
Sidekiq does not require Rails.  Your code requires Rails because you are using ActionMailer.  I don't understand your project constraints; I think you should talk to someone local who better understands what you are trying to do.
