### ISSUE TITLE
Job is not added

### ISSUE THREAD

**Issue by USvER** [mperham/sidekiq#3055]
I try to run job, but it's not get executed and as far as i can see it's not even added properly to the queue.

When i do `MyJob.perform_async(id)` i'm getting back task id, but it's never executed
Sidekiq process does not show any message about task start\end.
Sidekiq:web inteface shows 0 tasks
I've cleaned up redis with `flushall`, still no luck.

Ruby version: 2.2.2
Rails version: 5.0.0
Sidekiq / Pro / Enterprise version(s): 4.1.0
Redis version: 3.0.4

**Comment by mperham** [comment]
I'd guess you are using rspec-sidekiq or sidekiq/testing in development mode.

**Comment by USvER** [comment]
My sidekiq related gems:
```
sidekiq (4.1.0, 3.5.0)
sidekiq-cron (0.4.2)
sidekiq-status (0.6.0)
```

**Comment by USvER** [comment]
Strange thing is there was no start/stop of any job, but when i stop sidekiq i'm getting this:
```
INFO: Pushed 11 jobs back to Redis
```

**Comment by mperham** [comment]
That means there are 11 jobs which were executing (have been popped off the queue) but didn't finish.

**Comment by USvER** [comment]
Problem is: job is taken out of queue but never started...

**Comment by USvER** [comment]
Problem is fixed by using master branch. 

You are reading my mind!
