### ISSUE TITLE
No Dead Job When :retry => false

### ISSUE THREAD

**Issue by pedro-brentan** [mperham/sidekiq#3059]
Ruby version: 2.2.2
Sidekiq / Pro / Enterprise version(s): Sidekiq v4.1.1

When retry option is set to `false` the job goes to nowhere when fail. If the the retry is set to `0` it goes to the DeadSet.

I see this as a bad behavior, even because in the [Advanced Options Wiki Page](https://github.com/mperham/sidekiq/wiki/Advanced-Options) it shows the `:retry => false` option without any disclaimer about not going to DeadSet.

**Comment by mperham** [comment]
Already noted here that Sidekiq will save **nothing** about a job if it fails with `retry: false`

https://github.com/mperham/sidekiq/wiki/Error-Handling#configuration

**Comment by pedro-brentan** [comment]
Ok, in another page you say that, well done.

Using `:retry => 0` has no retry attempts but saves the error data. I would rather use this approach on the wiki.

Best.
