### ISSUE TITLE
Sidekiq silently falls back to default URL on malformed REDIS_URL

### ISSUE THREAD

**Issue by coreyward** [mperham/sidekiq#3062]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.1.2 (non-enterprise)

When `ENV['REDIS_URL']` is malformed, Sidekiq falls back to the default of `localhost:6379/0`. This was resulting in some issues as database `0` is not the correct source for the application in question. 

The specific URL used for `REDIS_URL` was `redis:://localhost:6379/1` (note the double-colon typo).

An error message, even just output to the console or log, would have gone a long way toward helping debug the issue.

Thanks for considering.

**Comment by mperham** [comment]
Want to send a PR?

**Comment by coreyward** [comment]
@mperham Happy to put something together; can you point me in the right direction? Doesn't look like `redis_connection.rb` does any validating or handling of exceptions regarding the URL. Is this handled by `Redis`, or is something else afoot?

**Comment by mperham** [comment]
This looks like a limitation in Ruby's URI module.  URI looks to be extremely tolerant so even an ampersand in the hostname doesn't trigger an InvalidURIError.

```
> u = URI.parse("redis://local&host:6379/1")
=> #<URI::Generic redis://local&host:6379/1>
> u.host
=> "local&host"
> u = URI.parse("redis:://local&host:6379/1")
=> #<URI::Generic redis:://local&host:6379/1>
> u.host
=> nil
```

I don't know how to fix this.
