### ISSUE TITLE
Ability to add/remove queues during runtimes

### ISSUE THREAD

**Issue by heaven** [mperham/sidekiq#3065]
We have some jobs that we need to limit to a few calls per second (due to API rate limits). The existing built in solution does lock the workers entirely, so no other jobs performed when we reached the limit. Existing gems have serious performance issues and they try to override the `#fetch` method and put the throttled jobs back to the queue.

My idea is to rate limit queues instead of jobs. So we can set the limits and once they reached disable the queue (remove it from the `@queues` array and resend the `BRPOP`). That might be a lock with the expiration time in Redis or we can track removed queues inside the process.

Sidekiq might implement only the API to enable/disable queues, other work could be done from extensions. What do you think about this approach?

**Comment by jonhyman** [comment]
My opinion would be to write your own fetcher. That's what we did, as we dynamically add and remove queues programmatically and it works well for us. Then you can do whatever logic is custom to you and let sidekiq just be the serialization and process management layer (with its other benefits).

**Comment by heaven** [comment]
Simply overriding the fetcher is possible, there are two gems I know that do this: sidekiq-throttler and sidekiq-rate-limiter, but they both have serious bugs that couldn't be fixed at the moment.

How do you remove queues programmatically? Is there an API to enable/disable them in runtime? Or do you override the `BasicFetch`?

**Comment by jonhyman** [comment]
Our fetcher also fetches queues from a custom redis set in addition to the "queues" key. 

We also have a redis hash of the form "queue_name=>json string of configuration options" that our fetcher uses  to adjust queue priorities dynamically.

For performance, we have different threads grabbing those custom things at a different interval. That way we're not doing an smembers or hget(all) more than, say, twice per second.

**Comment by heaven** [comment]
Thanks for the point, this sounds similar to what thought to do. I was thinking to start a separate thread per the rate limited queue and remove it from the `@queues` when requested. Then create a lock in redis with the expiration time and send `BKEY` to wait for the lock to expiry and to add the queue back to the pool. And then I learned there's no `BKEY` :)

**Comment by jonhyman** [comment]
So one of the configuration options that is in the redis hash that we use is a 0 to 1 probability of whether or not to process the queue. If you adapt a similar pattern, when the rate limit has been hit, you could set the probability of a queue to process to 0 and do a `perform_at` for a job that runs to set it back to 1.

Once you write your own Fetcher, the sky's the limit. 😄

**Comment by jonhyman** [comment]
Going to close this out, but feel free to re-open if you disagree and can get mperham's official take on it at that time.

**Comment by mperham** [comment]
Adding concurrency limiting to the fetch logic would dramatically increase the complexity and dramatically lower the performance.  Almost certainly fetching would become a heavyweight Lua call; a bad idea with Redis where any sort of latency hits system performance hard.

Your options are:

1. Use Sidekiq Enterprise's rate limiting functionality, which is not based on fetching or queues.
2. Use a OSS throttler or another tool like connection pooling or a limiter proxy.
3. Build something which solves your specific problem - Sidekiq is not a 100% solution for everything.

Good luck.
