### ISSUE TITLE
Access provider_job_id inside the job

### ISSUE THREAD

**Issue by Azzurrio** [mperham/sidekiq#3073]
Ruby version: 2.3.0
Sidekiq version(s): 4.1.2

I need to access `provider_job_id` attribute inside a job but it always returns `nil`. I looked at `SidekiqAdapter` class inside `ActiveJob` gem, and it looks like that `enqueue` method here already fire the job before assigning its id to `job.provider_job_id`. 
```
 def enqueue(job) #:nodoc:
        #Sidekiq::Client does not support symbols as keys
        job.provider_job_id = Sidekiq::Client.push(
          'class'   => JobWrapper,
          'wrapped' => job.class.to_s,
          'queue'   => job.queue_name,
          'args'    => [ job.serialize ])
      end
```
so, any idea how to improve this?

**Comment by mperham** [comment]
This is a Rails issue. I don't control ActiveJob::Base. You can access jid within a Sidekiq::Worker.

**Comment by Azzurrio** [comment]
@mperham Ok, so could you give me any idea how could I fix that in `ActiveJob::Base` side?

**Comment by mperham** [comment]
No idea off-hand.  You might want to open a Rails issue and ask but I'm not sure it'll fly.  After all, the idea of AJ is to hide provider-specific details.  Maybe explain why you need access to it.

**Comment by Azzurrio** [comment]
@mperham I need to access it so I can use `Sidekiq::Status` [tracking-progress methods](https://github.com/utgarda/sidekiq-status#tracking-progress-saving-and-retrieving-data-associated-with-job). The basic idea behind these methods is to store the progress using the `jid` attribute within `Sidekiq::Worker`. So inside `ActiveJob` while we don't have access to that `jid`attribute, we can easily work around that by using a `before_perform` callback like that
```
class ActiveJob::Base
  attr_accessor :jid

  before_perform do |job|
    job.jid = job.provider_job_id
  end
end
```
So the problem now, is that `provider_job_id` always returns `nil` inside the job because of what I just explained in first comment.

**Comment by mperham** [comment]
Sorry I wasn't clear: don't explain to me, explain to Rails core in that issue you need to open.

**Comment by Azzurrio** [comment]
oh, ok. I found a solution for that and and I did a PR in rails (https://github.com/rails/rails/pull/25961) 
could you check it?
