### ISSUE TITLE
Error message in logs: "Unable to remove job from private queue"

### ISSUE THREAD

**Issue by scottmartinnet** [mperham/sidekiq#3076]
Ruby version: 2.1.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.2, Sidekiq Pro 3.2.1

We periodically see the message "Unable to remove job from private queue" in our logs, but things appear to be working properly otherwise.  Does this message signify a problem, or should it be ignored?

**Comment by mperham** [comment]
It possibly means that you have two processes sharing the same reliable_fetch index.  They are both working on the same job and one wins the race to remove the job upon completion.

**Comment by scottmartinnet** [comment]
That's exactly what it is.  Thank you, that is incredibly helpful.
