### ISSUE TITLE
Redesign reliable_fetch

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3077]
* Remove the hostname/index hack.
* Keep the O(1) performance.

Processes should register a private queue upon startup, associated with their heartbeat.  On startup, each process should check the validity of each process heartbeat.  If invalid, any private queue contents should be re-enqueued.

ETA: September.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server#super_fetch

```ruby
Sidekiq.configure_server do |config|
  config.super_fetch!
end
```

`super_fetch!` will become an alias for `reliable_fetch!` in Sidekiq Pro 4.0 so that hostname/index issues become a thing of the past.

**Comment by inkstak** [comment]
Hi @mperham, any idea about the release date of `super_fetch!`?

**Comment by mperham** [comment]
Twoish weeks.

**Comment by inkstak** [comment]
:ok_hand:
