### ISSUE TITLE
Ent Unique Jobs / Choose params

### ISSUE THREAD

**Issue by danielnc** [mperham/sidekiq#3078]
Ruby version: 2.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.3 / Pro 3.3.1 / Ent 1.3.1

If there an option to customize uniqueness of job?

Assuming i have a job with those arguments:

perform(file_id, row_number, row_data)

I want the job to be unique only by file_id and row_data and ignore row_number

Is this something that is possible to do?

**Comment by mperham** [comment]
I don't know of any way to do this.  Enterprise's unique feature does not allow you to pick which arguments are unique.

**Comment by danielnc** [comment]
I was looking at ent-code and this shouldn't be hard to implement

can we put this as a feature request?

```ruby
sidekiq_options unique_for: 10.minutes, unique_args: [:file_id, :row_data]
```

**Comment by mperham** [comment]
I've already considered this feature and discarded it as a bad idea.  That said, I'm open to convincing otherwise.

**Comment by aprescott** [comment]
With a method like

```ruby
def perform(file_id, row_number, row_data)
  # ...
end
```

the arguments are positional, and I don't think there's a direct way of taking a set of arguments to `perform`, say,

```ruby
["file_id_1", "row_number_20", "this-is-row-data"]
```

and determining that the first value is for the `file_id` argument. It's _possible_, for sure.

```ruby
class X
  def foo(a, b, c)
  end
end


x = X.new
method_params = x.method(:foo).parameters
# => [[:req, :a], [:req, :b], [:req, :c]]

args = [1, 2, 3]
params_to_unique_on = [:b, :c]

desired_indices = params_to_unique_on.map do |desired_param|
  method_params.index do |param_type, param_name|
    desired_param == param_name
  end
end
# `desired_indices` may contain `nil` if `params_to_unique_on` isn't a subset of
# the actual `method_params`, e.g., because of a mismatch in worker configuration.

values_to_unique_on = args.values_at(*desired_indices)
# => [2, 3], corresponding to the values for `b` and `c`
```

In general, `Method#parameters` will be more complex, of course, which would affect the implementation.

```ruby
def bar(x, y = 1, *args, required:, optional: 5, **kwrest)
end

method(:bar).parameters
# => [[:req, :x], [:opt, :y], [:rest, :args], [:keyreq, :required], [:key, :optional], [:keyrest, :kwrest]]
```

Let's say you want to use `args` as the values to unique on for `bar()`. To correctly do that in general would, I think, require implementing (or finding a metaprogramming way to borrow) the same logic that Ruby uses internally to map arguments given at a method call site to that method's parameter names — in this case, making sure to pull off `x` and `y` and splat the rest of the args into `args`, then use that subset as the values to unique on.

**Comment by ryansch** [comment]
It seems like we're trying to compute a hash key. Why don't we just test
for a hash key method to let the user override the default behaviour?
Disclaimer: I haven't looked at what we would need to do with redis.

**Comment by aprescott** [comment]
That's definitely the way to go. (I was mostly trying to describe the difficulty of doing this with just references to parameter names. I might have gone overboard!)

**Comment by mperham** [comment]
Other implementations can do this but I'm unconvinced.  I'm going to reject this for now.

https://github.com/mhenrixon/sidekiq-unique-jobs#finer-control-over-uniqueness

**Comment by henare** [comment]
We're Sidekiq Enterprise customers moving a job from Resque that uses [Resque Lock](https://github.com/defunkt/resque-lock) to ensure only one job of a certain class is queued at a time. The feature described in this issue would allow us to do this.

I like the idea of being able to override the method used to generate the lock key but we don't have an immediate use case for this more general approach.

@mperham any chance of reconsidering this feature request or should we look at other implementations instead? Thank you in advance :slightly_smiling_face:

**Comment by mperham** [comment]
@henare There are other unique lock impls that provide this. Mine does not. You can use a concurrent rate limiter of size 1 to achieve a similar result.
