### ISSUE TITLE
sidekiq/testing does not stub Sidekiq::Workers or Sidekiq::Queue

### ISSUE THREAD

**Issue by postmodern** [mperham/sidekiq#3081]
I have some code which introspects queues and workers that I would like to test without redis. Unfortunately, `sidekiq/testing` does not seem to stub `Sidekiq::Workers` or `Sidekiq::Queue`, resulting in attempted connections to redis.

**Comment by mperham** [comment]
'sidekiq/api' is there to present an OOP view of the data in Redis.  Asking for it to work without Redis is like asking for ActiveRecord to work without a database.

**Comment by postmodern** [comment]
@mperham https://gist.github.com/unnitallman/944011

ActiveRecord can work entirely in memory and so can mock_redis. Sounds like your `sidekiq/testing` API is incomplete. Maybe we should fix that?

**Comment by seuros** [comment]
@postmodern this is not the same . 
Using sqlite3 memory in tests while your database is postgres/mysql in production is asking for troubles.

**Comment by mperham** [comment]
You can use fake_redis or you can stub out your methods which touch sidekiq/api but I don't want to add the complexity of another mode of operation.
