### ISSUE TITLE
redis instance filled with batch keys even after their success

### ISSUE THREAD

**Issue by andreaseger** [mperham/sidekiq#3083]
we at have been using sidekiq batches quite heavily since about a week in production and noticed that it fills our redis instance with IMO useless keys even for successfully completed batches.

These keys look like `b-#{bid}-notify` and `b-#{bid}-cbsucc` both of which have an expiry of 30 days. In addition we see hashes named like `b-#{bid}` with an expiry of 24h.
As we process a couple million jobs a day in lot of small batches (to model a complex workflow) after just 6 days in production we have an overhead in our redis instance of > 6 million keys which won't expire anytime soon. (according to redis info it's using as of writing ~1.76GB memory and the keyspace looks like this `keys=6337386,expires=6337291,avg_ttl=1915837014` while having basically empty queues according to sidekiq)

I guess having the hashes for each batch around for 24 hours would be ok although it would be nice to be able to configure this. The main problem in my opinion is the notify and cbsucc keys as they would stay around for 30 days with no apparent reason. And this overhead we already see will just get bigger and bigger till we start seeing some kind of stabilization.

Looking at the source of the sidekiq-pro gem this snippet I found around `lib/sidekiq/batch/callback.rb:64` seems to be the cause of the problem.

I don't quite understand what "running callbacks inline" means in this context but at a first guess this doesn't seem like something that would be applicable to a production system anyway.
If not at this point wouldn't the place which calls the callbacks be able to cleanup these keys in redis?

Hope there is a solution to this problem as this issue makes the use of batches only usable with a huge overhead.

Ruby version: `jruby 9.1.2.0`
Sidekiq / Pro / Enterprise version(s):

```
    sidekiq (4.1.4)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
      sinatra (>= 1.4.7)
    sidekiq-ent (1.3.1)
      algorithms
      sidekiq (~> 4, >= 4.0.2)
      sidekiq-pro (~> 3, >= 3.0.1)
    sidekiq-pro (3.3.1)
      sidekiq (>= 4.0.0)
```

**Comment by mperham** [comment]
This is released now in 3.3.2.  You'll want to tune Batch::LINGER too.

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#332

**Comment by lefty313** [comment]
@mperham 

How I can set 

```
Sidekiq::Batch::LINGER
```

in rails initializer so I won't get

```
/Users/lewy/code/lolsumo/config/initializers/sidekiq.rb:23: warning: already initialized constant Sidekiq::Batch::LINGER
```

**Comment by mperham** [comment]
That's what I'd do.

**Comment by lefty313** [comment]
I thought you could move this to `sidekiq config` block or something like that. 

btw

Imo this keeping batches after success should be disabled as default because it really causes memory bloat when you are scheduling a lot of batches. Until you know about most people will get unpleasant surprise on production.

I'm not sure but i could be that on amazon elasticcache in worst case you will loose all data stored in redis because will be rebooted

http://serverfault.com/questions/724047/avoiding-swap-on-elasticache-redis

**Comment by mperham** [comment]
This isn't an official configuration point, more of an extraction to make tuning possible.

Keep in mind that you're in the top 1% when you are creating millions of batches per day in one app.  Most people at that scale have multiple apps using multiple, larger Redises.  The default configuration ensures that all functionality works out of the box.  As you need to scale, you'll need to start doing more low-level tuning.

**Comment by lefty313** [comment]
> Keep in mind that you're in the top 1% when you are creating millions of batches per day in one app. Most people at that scale have multiple apps using multiple, larger Redises.

fair enough

> The default configuration ensures that all functionality works out of the box. As you need to scale, you'll need to start doing more low-level tuning.

should I add short explanation of this problem and fix to 

https://github.com/mperham/sidekiq/wiki/Batches 

?

**Comment by mperham** [comment]
No, as it's not something I want to document.  The wiki won't have a canonical list of every possible tweak you can make to Sidekiq.

**Comment by lefty313** [comment]
ok than I guess you can close this issue. Thank you for all help 👍
