### ISSUE TITLE
Sidekiq randomly stops processing jobs on Heroku

### ISSUE THREAD

**Issue by Deekor** [mperham/sidekiq#3084]
Every couple weeks or so our sidekiq (Sidekiq v3.5.4) will stop processing jobs, they will continue to queue up but never make it in to busy. If I restart the worker Dyno running sidekiq the jobs start processing again normally. The worker dyno has plenty of RAM. 

Is there some special configuration for Heroku I might be missing here? We are using the Free tier of [Heroku Redis](https://elements.heroku.com/addons/heroku-redis) but aren't even close to using up the allotted resources.

![](http://i.imgur.com/JwjIMxZ.png)

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes
