### ISSUE TITLE
Web UI Dashboard Leaves Orphaned Jobs Listed Even After Completed

### ISSUE THREAD

**Issue by thegranddesign** [mperham/sidekiq#3087]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 3.2.6 standard

For some reason I can't understand, the "Busy" tab of the Web UI doesn't clear out some of the jobs.  They hang out in there with things like started "4 hours ago" which is not correct.

I can restart the servers and the erroneous jobs are removed from the Busy tab.

The erroneous "busy" jobs then begin accumulating again.

FWIW, the "Busy" number in the stats bar on the Web UI shows the correct number of busy jobs.

**Comment by mperham** [comment]
your Sidekiq version is about a year old, please upgrade for bug fixes.
