### ISSUE TITLE
Process in stopping? mode forever despite dyno restarts

### ISSUE THREAD

**Issue by jwg2s** [mperham/sidekiq#3088]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.4

We've got a stuck process that we're unable to stop.  Despite dyno restarts with heroku, the process continues to live on, and it's `stopping?` method always returns true.

Happy to provide any more info that you'd find relevant.

**Comment by mperham** [comment]
Heroku should always be able to stop a process that is running.  Are you talking about a Sidekiq process that is not disappearing from the Web UI's Busy tab?

**Comment by jwg2s** [comment]
@mperham if the dyno isn't running anymore, my assumption would be that there is no way the process could still be running.  This is on the web ui busy tab.  My guess is some data got orphaned in redis that keeps track of which workers/processes are running and nothing can automatically clean it up?

Haven't dived too deep into Sidekiq code and how all of that is managed, but maybe you could point me in the right direction?

**Comment by mperham** [comment]
See script here https://github.com/mperham/sidekiq/blob/master/Changes.md#413

**Comment by jwg2s** [comment]
@mperham awesome thanks!
