### ISSUE TITLE
Conflict in Rake version when using Rails 5.0.0

### ISSUE THREAD

**Issue by spaquet** [mperham/sidekiq#3089]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Community (free)
Rails version: 5.0.0 (final stable, not rc or beta)

Error message when running **bundle update**

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
          rack (~> 2.0)

    sidekiq was resolved to 4.1.4, which depends on
      sinatra (>= 1.4.7) was resolved to 1.4.7, which depends on
        rack (~> 1.5)
```

Is there a plan to align rack versions? Is there a way to not install reporting tools (UI)? and finally, is this related to the following push: https://github.com/mperham/sidekiq/pull/3075

**Comment by mperham** [comment]
#3048
