### ISSUE TITLE
Sidekiq dies intermittently with no visible exception

### ISSUE THREAD

**Issue by snarfmason** [mperham/sidekiq#3092]
OS: Ubuntu Ubuntu 12.04.5 LTS
Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]
Rails version: 4.2.5.2

Sidekiq / Pro / Enterprise version(s):
We tried two configs, we upgraded all our Sidekiq gems during this process.
Initially: Sidekiq 4.1.2, Pro 3.2.1, Ent 1.2.1, redis 3.2.1
After upgrade: Sidekiq 4.1.4, Pro 3.3.2, Ent 1.3.2, redis 3.2.2

(Gut feeling, the issue is a little better post upgrades, but still present.)
initializer: https://gist.github.com/snarfmason/1ed0b8ef7e2813172d4736c09f5774b6

General description:
We have two instances of Sidekiq running:
main: `sidekiq -q default,2 -q notifications`
integration: `sidekiq -q integration`

On the integration queue, we have a sidekiq periodic job `QueueIntegrationScheduleJob` that checks for stale data in our 15 integration datasets. If a dataset is stale (15 minutes old), it kicks off another job to fetch that integration's data set.

Intermittently, the Sidekiq process running our integration queue will simply die mid-run. The main sidekiq does not appear to be affected. This has happened several dozen times today, but on no particular schedule. Sometimes it happens immediately after booting up, sometimes it runs fine for half an hour before dying.

There's no error message per se, it just dies. syslog reports:
```
init: sidekiq-integration main process (10929) terminated with status 134
init: sidekiq-integration main process ended, respawning
```

Tailing the sidekiq log, I see `Booting Sidekiq` without the normal log messages indicating a clean shutdown.

This does not appear to be a primarily memory use related issue. Upgrading the sidekiq versions helped memory use considerably, and there are several GB free on the machine. I've tried to track memory use through Newrelic, and it dies at different levels of used memory, although it does seem to increase over time.

We were not able to get a response to `TTIN` signal, but did attach a GDB debugger and got: https://gist.github.com/snarfmason/d6bd2c5080e522fd7f3fb56848bb5f49

This is a hard issue to describe, I've tried to include everything I can think of as relevant. Please ask if there is any other information you think we can provide.

**Comment by mperham** [comment]
You need to install ruby debugging symbols (I think in ruby-devel or some package like that) so the GDB output is usable.

**Comment by mperham** [comment]
You've got a segfault or some other hard crash.  There's not much I can tell without debugging symbols and a coredump.  (1) remove or (2) upgrade all of your native extensions to the latest version.

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do

**Comment by jc00ke** [comment]
Hmm, OK, we'll try to get a debuggable Ruby working on staging.

**Comment by mperham** [comment]
Any progress?

**Comment by snarfmason** [comment]
I believe so. Following your advice to focus on bits written in C, I narrowed it down to apparently a libcurl failure. That narrowed it down to https://github.com/typhoeus/typhoeus of which we had a very old version. 

It seems ethon was misusing libcurl: https://github.com/typhoeus/ethon/commit/4e9140fcd9d05ba06b6c7fa5b08909cad04887fe#diff-a7af4077f7e04b5191c1e2c593b3d713

 It's FFI not a native extension, but same same to us I think. So far things seem to be running alright with the gem upgrades.

**Comment by mperham** [comment]
Yep, typheoauis is already "grey-listed" as a troublesome gem to avoid:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#not-thread-safe-gems
