### ISSUE TITLE
Setting up WEB UI Pro / Ent

### ISSUE THREAD

**Issue by rjrobinson** [mperham/sidekiq#3093]
Ruby version:
Enterprise (latest), located at the bottom of the Sidekiq::Web mounted UI
```shell
Sidekiq v4.1.4 / Sidekiq Pro v3.3.2
redis://127.0.0.1:6379/0
11:27:50 UTC
```

I just set up the Ent version, and it seems to be working fine, but I am unaware of what the difference between the Pro UI and the Ent UI.

is Sidekiq::Pro::Web no longer working?

here is my routes.rb
```ruby
# require 'resque_web'
require 'sidekiq/web'
require 'sidekiq/pro/web'

Rails.application.routes.draw do

  # mount Resque::Server.new, at: '/resque'

  mount Sidekiq::Pro::Web => '/sidekiq'

...
```
when I try to run this, I get an error about a rack based mount. 

```shell
/Users/rrobin244/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/mapper.rb:580:in `mount': A rack application must be specified (RuntimeError)
```

I can run the "basic" version, and it does say ENT at the top. I just wanted to know if this was an error on my part, of if the docs were not updated.

**Comment by mperham** [comment]
You're so close, RJ.  This is all you need do:

```ruby
require 'sidekiq-ent/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
```

**Comment by rjrobinson** [comment]
Thanks!!! so much. However,  I am noticing that when I am looking at the dashboard in one window, and on my application in another window, im getting an `ActionController::InvalidAuthenticityToken` error.

**Comment by mperham** [comment]
I believe this is due to Sinatra and Rails sessions not being set up correctly.  See if you can submit a form in the Web UI (e.g. retry a job).

https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden

**Comment by rjrobinson** [comment]
Awesome ! Thanks so much for the assist. 

However, now Im getting taht forbidden error that you speak of. 

routes.rb
```ruby
require 'sidekiq-ent/web'
Sidekiq::Web.set :session_secret, Rails.configuration.secret_token

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
...
```

In my gem file I have `gen 'sinatra', require: false ` and I am still getting that error. 

Any ideas?

**Comment by mperham** [comment]
That issue is an integration issue between Rails, Sinatra, Rack and your session setup.  Neither Sidekiq nor I can help since every app is slightly different.

**Comment by rjrobinson** [comment]
Hrmmm... Any way I can get some support being a Ent customer? 

I have also noticed that i cannot have the Sidekiq UI open and my app open at the same time ( different tabs )

**Comment by mperham** [comment]
Support is for Sidekiq functionality, not Sidekiq's app integration.  I can't support the app integration because every app and customer is different.

https://github.com/mperham/sidekiq/wiki/Commercial-Support

**Comment by mperham** [comment]
I do offer custom support if your team needs help to get past this: http://sidekiq.org/support Shoot me an email if interested.

**Comment by mperham** [comment]
There are lots of closed issues with people reporting the same symptoms - they may contain clues as to a solution.
