### ISSUE TITLE
Web interface shows queues in alphabetical order

### ISSUE THREAD

**Issue by nickpoorman** [mperham/sidekiq#3094]
Ruby version :ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Sidekiq / Pro / Enterprise version(s): sidekiq-ent (1.2.2)

```yml
---
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
:queues:
  - realtime
  - high
  - publisher
  - default
  - medium
  - mailers
  - tasks
  - importer
  - events
  - low
```

We have our queues in a specific order in our .yml file. In the web interface, on the Queues page, they appear in alphabetical order. It would be nice if we had a way to display them by priority (the order they are in the .yml file) in the web interface instead of alphabetical order.

**Comment by mperham** [comment]
They are displayed in alphabetical order because they are stored in an unsorted set in Redis so the ordering would be non-deterministic otherwise.  The Web UI does not use the YML.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L199
