### ISSUE TITLE
ArgumentError: invalid uri scheme ''

### ISSUE THREAD

**Issue by alienxp03** [mperham/sidekiq#3095]
I been running Sidekiq and works just fine. Both on local and staging(Heroku). Deployed to AWS and I'm getting this error. Seems like it's not recognising which schema is should be using?

Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-gnu]
Sidekiq version: 4.1.4

`sidekiq.rb`:
```
Sidekiq.configure_server do |config|
 config.redis = { url: "redis://#{ENV['REDIS_URL']}:6379/12" }
end

Sidekiq.configure_client do |config|
 config.redis = { url: "redis://#{ENV['REDIS_URL']}:6379/12" }
end
```

`Stacktrace`:
[ArgumentError: invalid uri scheme ''
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/redis-3.3.0/lib/redis/client.rb:416:in `_parse_options'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/redis-3.3.0/lib/redis/client.rb:81:in `initialize'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/redis-3.3.0/lib/redis.rb:51:in `new'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/redis-3.3.0/lib/redis.rb:51:in `initialize'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/redis_connection.rb:42:in `new'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/redis_connection.rb:42:in `build_client'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/redis_connection.rb:21:in `block in create'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:169:in `try_create'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/client.rb:176:in `raw_push'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/client.rb:68:in `push'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/worker.rb:116:in `client_push'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/worker.rb:75:in `perform_in'
  from (irb):3
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /var/www/myapp/shared/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:8:in `require'
  from bin/rails:8:in `<main>](url)

**Comment by mperham** [comment]
REDIS_URL is not set.

**Comment by alienxp03** [comment]
I did set the URL. I even set it manually, eg `config.redis = { url: "redis://my.elastic.cache.amazon.url.com:6379/12" }` and still getting the same error

**Comment by shavo007** [comment]
hi @alienxp03 , im getting the same issue. How you resolve it?

In kubernetes, i have defined the env variable as REDIS_URL=xxxx-redis.xxx.xxx.apse2.cache.amazonaws.com

Get error 

```
ArgumentError: invalid uri scheme 'xxx-xxx-redis.xxx.0001.apse2.cache.amazonaws.com'
	/usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:416:in `_parse_options'
	/usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:81:in `initialize'
	/usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:51:in `new'
	/usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:51:in `initialize'
	/usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq/redis_connection.rb:47:in `new'

```

**Comment by wangping0105** [comment]
> I did set the URL. I even set it manually, eg `config.redis = { url: "redis://my.elastic.cache.amazon.url.com:6379/12" }` and still getting the same error

did u find the reason

**Comment by wangping0105** [comment]
@alienxp03

**Comment by mikegee** [comment]
The code posted by @shavo007 will lead to this error. `REDIS_URL` needs to begin with "redis://".

The code in the original report does not raise this error. It falls back to localhost:

```ruby
Redis.new url: "redis://#{ENV['MISSING_FROM_ENV']}:6379/12"
  #=> <Redis client v3.3.3 for redis://127.0.0.1:6379/12>
```

**Comment by prcongithub** [comment]
I am facing similar issue. Does anyone know what's going wrong here?
My URL looks like this: 
redis://:somepassword@localhost:6379/0

**Comment by adil-bouchaara** [comment]
@mperham you don't have the right to close that ticket, as many people still face the same error as i do

**Comment by mperham** [comment]
```
> r = Redis.new(url: "redis://:somepassword@localhost:6379/0")
=> #<Redis client v4.2.5 for redis://localhost:6379/0>
```

Works for me. `REDIS_URL=xxxx-redis.xxx.xxx.apse2.cache.amazonaws.com` fails because that is not a URL, it's a hostname only. Provide a URL with scheme, hostname, port and db number and it will work.

**Comment by UICJohn** [comment]
Gem redis client use REDIS_URL env for the connection: <redis-4.4.0/lib/redis/client.rb>.  Try use another name for the env
