### ISSUE TITLE
Error handler for not retrying certain errors

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#3097]
I have a error handler to disable retrying of some errors, but doesn't seem to be working. Anything I am doing wrong?

```ruby
Sidekiq.configure_server do |config|
  # Error handler for not retrying certain errors
  no_retry_error_handler = -> (e, context) do
    if ActiveRecord::RecordNotFound === e
      context['retry'] = false
    end
  end

  config.error_handlers << no_retry_error_handler
end
```

Using following ruby/gem versions.

```ruby
ruby '2.3.1'
gem 'rails', '4.2.7'
gem 'sidekiq', '4.1.4'
```

**Comment by mperham** [comment]
Error handlers can't control retry.  You can only rescue and return in the perform method.

```ruby
def perform
  begin
    # ...
  rescue ActiveRecord::RecordNotFound
  end
end
```

**Comment by kapso** [comment]
I am using this gem (https://github.com/andersondias/sidekiq_mailer) and dont have control on the `perform` method and so was looking for a hook within Sidekiq.

**Comment by kapso** [comment]
I am using this gem (https://github.com/andersondias/sidekiq_mailer) so dont have control on the `perform` method and thats why was looking for internal Sidekiq hook.

**Comment by mperham** [comment]
I don't know of any way to do what you want then.  There are 3rd party retry middlewares that may support that functionality.
