### ISSUE TITLE
So, cocaine isn't thread safe - what now?

### ISSUE THREAD

**Issue by geoffw8** [mperham/sidekiq#310]
Hey

I can't tell you how excited I am about the potential of using sidekiq. We have just bought a new box, and I was concerned we'd need another one pretty soon.

However, one of the jobs we plan on running uses Paperclip, and so, cocaine.

What does it mean if it isn't thread safe? What can do we do to circumvent this? Use an alternative to paperclip?

Thanks,

Geoff

**Comment by andreiglingeanu** [comment]
Nothing new on that?
