### ISSUE TITLE
Sidekiq Ent Limiter.concurrent Testing

### ISSUE THREAD

**Issue by sirwolfgang** [mperham/sidekiq#3100]
Ruby version: `2.3.1` 
Sidekiq / Pro / Enterprise version(s): `Sidekiq 4.1.4 / Pro 3.3.2 / Ent 1.3.2`

I feel like I am missing something super obvious.. I wrote a simple function that wraps a function call with the `THROTTLE.within_limit` block. When I attempt to run the test, it sits for the 5 sec timeout I have set, than fails with the `Sidekiq::Limiter::OverLimit` error.

**Comment by mperham** [comment]
Show us the code.

**Comment by sirwolfgang** [comment]
```ruby
module Throttler
  THROTTLE = Sidekiq::Limiter.concurrent(:ftp, 10, wait_timeout: 5, lock_timeout: 30)

  def self.upload_report(endpoint, username, password, report_filename, file_contents)
    THROTTLE.within_limit do
      FTP.upload_report(endpoint, username, password, report_filename, file_contents)
     end
  end
end
```
```ruby
RSpec.describe Throttler, type: :worker do
  let(:endpoint)        { 'ENDPOINT' }
  let(:username)        { 'USERNAME' }
  let(:password)        { 'PASSWORD' }
  let(:report_filename) { 'REPORT_FILENAME' }
  let(:file_contents)   { 'FILE_CONTENTS' }

  describe '.upload_report' do
    let(:params) { [endpoint, username, password, report_filename, file_contents] }

    it 'calls FTP.upload_report with the expected params' do
      expect(FTP).to receive(:upload_report).with(*params)
      described_class.upload_report(*params)
    end
  end
end
```

**Comment by mperham** [comment]
Works fine for me.  If I can't reproduce it, I'm not sure how to help you since the code looks like it should work.

```
$ bundle exec rspec spec/test.rb 
.

Finished in 0.0058 seconds (files took 0.17677 seconds to load)
1 example, 0 failures
```

**Comment by sirwolfgang** [comment]
After running it on someone else's machine, verifying it was the project and not me... and playing the delete thing until it works game. I was able to reduce the issue down to this:

```ruby
RSpec.configure do |config|
  config.before(:each) do
    Rails.cache.clear
  end
end
```
I am not yet sure as to why this would be an issue.

**Comment by sirwolfgang** [comment]
```ruby
    config.cache_store = :redis_store, { url: ENV.fetch('CACHE_URL') }
```
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('SIDEKIQ_URL') }
end
```

In this case, during testing, they are the same redis server/namespace. So it seems like the `Rails.cache.clear` might be nuking everything. Since `THROTTLE` is created before the cache clear, it gets nuked as well. Meaning its not there when it goes to be used.

I understand how I can fix this in test, by separating out the namespaces on redis, or in code by allocating the lock at runtime. But this to me seems like an edge case that should be handled. If the lock goes to grab a handle that isn't there for some reason, it can try to reallocate it.

**Comment by mperham** [comment]
> Note: limiters are somewhat heavyweight to create, requiring a round-trip to Redis. If possible, create limiters once during startup and reuse them (as with ERP_THROTTLE below).

If you clear Redis, the limiter behavior is undefined.  Production systems don't flush the DB randomly and handling this edge case would add a major performance penalty.
