### ISSUE TITLE
Do jobs retried from the dead job pool not use base retry logic?

### ISSUE THREAD

**Issue by MaartenG** [mperham/sidekiq#3101]
Ruby version: 2.2.3
Sidekiq version(s): 4.1.1
Rails 4.2.7.1

I'm trying to understand behavior I'm seeing with retrying dead jobs. Amongst the many workers in one of our projects, there is one with the following setup logic

```
sidekiq_options queue: :default
sidekiq_options :retry => 4
```

The worker is in charge of doing a certain database operation if other conditions are met. It checks if those conditions are met, and does an uncatched raise if not, allowing for the retries to start. And if I look at the Retries tab in the UI during various points of the day, I will occasionally see a job from this worker being retried. A couple of these jobs end up in the dead pool because they will run out of retries.

If I then go to the Dead tab, use the check box to select my dead jobs, and hit the "Retry now" option, a couple of these jobs will now finish, but others will immediately end up in the Dead pool again. Do they not attempts the same 4 retries again?

**Comment by mperham** [comment]
Once the auto retries are exhausted, retry is manual only.

**Comment by MaartenG** [comment]
Alright, thanks for clearing that up!
