### ISSUE TITLE
Expose the internal reliable fetch queue in UI

### ISSUE THREAD

**Issue by sandstrom** [mperham/sidekiq#3103]
When a job runs indefinitely there is no easy way of removing a 'poison pill' job.

When I've stopped the worker, I cannot find the job it got stuck on under 'retries', but somehow it will magically re-appear in the UI after starting the worker again.

This makes it tricky to kill/remove the job, because I cannot kill it while it's being worked on, and I cannot kill it after stopping the worker (because now the job is no longer visible).

These jobs are (afaik) stored in `"queue:#{q}_#{Socket.gethostname}_#{options[:index]}"`.

Would be awesome if these could be deleted in an easy fashion in the otherwise excellent UI! ⛵

**Comment by mperham** [comment]
I'm not putting any more time into reliable fetch.  Instead I recommend switching to timed_fetch or waiting for the new super_fetch which should be out in a month or so.

https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server
https://github.com/mperham/sidekiq/issues/3077

**Comment by sandstrom** [comment]
@mperham sounds good, looking forward to `super_fetch` then!
