### ISSUE TITLE
sidekiq 4.1.4 with rails 5 enqueued but not processed

### ISSUE THREAD

**Issue by tuanlv1206** [mperham/sidekiq#3105]
Ruby version:2.3.1
sidekiq 4.1.4 

Can anyone help me explain why jobs and workers are enqueued but not processed?
Thanks a lot!

**Comment by tuanlv1206** [comment]
it worked but take a long time to process job.

**Comment by mperham** [comment]
Often because your clock is far out of sync.  Make sure your server clocks are accurate.

**Comment by tuanlv1206** [comment]
@mperham thank you very much for the explanation!
