### ISSUE TITLE
Sidekiq does not run pending jobs

### ISSUE THREAD

**Issue by aaroalan** [mperham/sidekiq#3106]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Sidekiq v4.0.1

According with my sidekiq status page it does not have more jobs to process
![screenshot 2016-08-18 09 02 59](https://cloud.githubusercontent.com/assets/5009343/17776518/97b7dc82-6522-11e6-860d-6eaffee01f3a.png)

but I checked a local counter that I implement and it says that still pending 5 jobs, checking redis there are those jobs but I do not know why redis does not process them.
![screenshot 2016-08-18 09 04 41](https://cloud.githubusercontent.com/assets/5009343/17776584/d3197da8-6522-11e6-9a43-414a846cc121.png)

**Comment by mperham** [comment]
I have no idea what could be wrong.
