### ISSUE TITLE
Sidekiq take a longer time to complete when another sidekiq proces is perfomed inside the parent sidekiq process

### ISSUE THREAD

**Issue by ckgagan** [mperham/sidekiq#3112]
Ruby version: jruby 9.1.2.0
Sidekiq / Pro / Enterprise version(s): Sidekiq

Hi,
Why does the parent sidekiq process takes longer time to complete if another sidekiq process is instantiated within in.
```
class ParentWorker   
  include Sidekiq::Worker

  def perform(params)
    array = [array of numbers]

    array.each do |num|
      ChildWorker.perform_async(num)
    end
  end
end
```
Now seems like the parent sidekiq worker must complete it's task pretty much quickly as it just sidekicking jobs to background. But it is not. ParentWorker is taking longer time. In my case its longer than 20 seconds for array with 3 elements.

I asked the question in stackoverflow, but no one answered. Is it a wrong practice to start another sidekiq process from within a sidekiq process.

**Comment by mperham** [comment]
Sounds like you might have the testing inline mode activated.

**Comment by ckgagan** [comment]
@mperham No this is in development mode and it also happens in production mode.

**Comment by mperham** [comment]
All you need is `Sidekiq::Testing.inline!` somewhere in your code, doesn't matter what environment you are in.

**Comment by ckgagan** [comment]
I think 

> Sidekiq::Testing.inline!

 is used for performing the task inline. But that's not what I wanted.

I am trying to fire multiple sidekiq worker process (B,C,D) from within a sidekiq worker (A).

But sidekiq worker A completes after sidekiq process B,C ,D completes.
Don't you think worker A must complete before all worker B, C, D completes, because the work of Worker A is just send the worker B, C, D to background?

But we see time to complete for Worker A is longer than that of B, C, D.

**Comment by mperham** [comment]
That doesn't make any sense.  You have something wrong with your environment.  Yes, B C and D should fire in the background so A should finish first.
