### ISSUE TITLE
Remove image files from Web UI

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3115]
Putting images on the filesystem means we need to serve assets, which sometimes requires overly complex nginx/apache static file rules and slows down the Web UI by requiring multiple requests per page.  Could we convert the images into base64 data that can be embedded inline?

**Comment by nateberkopec** [comment]
> slows down the Web UI by requiring multiple requests per page

Image requests are easily parallelized, and don't delay the display of the page. Moving images inline (into a CSS file, I guess, right?) makes them *block* page rendering, because the CSS must be downloaded before anything can be displayed. I think there's only about 50-100kb of images in the web UI, so it's not a huge slowdown, but I don't see this speeding up the web UI.

That said, it may be worth the extra 50kb of CSS if it means easier installation, re: Nginx/Apache.

**Comment by mperham** [comment]
Yes, ease of use with complex nginx/apache setups is the primary benefit for the change.  Browser caching makes speed a non-issue.  I was thinking of embedding the data in the img tag, CSS not applicable.

**Comment by mperham** [comment]
But that said, setting up caching rules for the images is still annoying so speed is by no means guaranteed.

**Comment by natebird** [comment]
Here are the base64 encodes of the assets in the images folder: https://gist.github.com/natebird/d545d65226d15b3e0bb256ddc1fd5c94

**Comment by jelder** [comment]
None of the assets are particularly complex. The most complex is the logo, which I bet @mperham has in vector format somewhere. What about converting everything to inline SVGs?

**Comment by mperham** [comment]
Sounds reasonable.  These are the only SVGs I have.

https://github.com/mperham/sidekiq/tree/gh-pages/assets

**Comment by natebird** [comment]
I couldn't find a converter for the .ico file. I'm not sure if there is an alternative format we can use.

**Comment by jelder** [comment]
@mperham What browsers does the web interface target?

**Comment by nateberkopec** [comment]
You're probably better off just putting it in the CSS, then. `data-uri`s aren't cached separately from the containing document, so adding them to the HTML means they're only cached if the HTML page is cached. I'm guessing Sidekiq's HTML documents aren't really cacheable, so embedding these in the `img src` adds their ~50kb to every request. Better to just put in the CSS, which is highly cacheable.

**Comment by mperham** [comment]
@jelder "Modern" browsers are fine.  UI is expected to be used by developers who tend to run current stuff.

**Comment by mperham** [comment]
Putting in CSS sounds fine.  I'd like to get close to one request per page when cache is warm if possible.  That means emitting Cache-Control headers for assets we serve.

**Comment by mperham** [comment]
#3117 is a start
