### ISSUE TITLE
High concurrency slows job processing time

### ISSUE THREAD

**Issue by smidwap** [mperham/sidekiq#3118]
Hey there,

I have a database intensive "account installation" job that's run right after a new user signs up. This job should run and finish asap, so I've placed it in a "critical" queue that has top priority.

While testing I noticed that if Sidekiq is super busy and all workers are working, the account installation job takes significantly longer to process. When no workers are busy, the job finishes in ~3 seconds. When all 25 workers are busy, the job can take 30+ seconds to run! Bad news for users who sign up when Sidekiq is busy.

To understand the problem better, I ran a test: while varying concurrency (i.e. number of workers), I queued the account installation job with Sidekiq busy (queue is full, all workers working). Here's what I found:

![image](https://cloud.githubusercontent.com/assets/794163/18110911/489a78e6-6ee9-11e6-8d52-7d281dd7898b.png)

It's clear that the more workers running, the longer the account installation job takes to complete. Even at just 2 workers, the slowdown is noticeable (2x slower).

I parsed the logs, and I believe the cause for the slowdown is time spent in the database. SQL query times increase as the number of workers increase.

I can't make sense of this. My database pool size is 25, so I wouldn't expect workers to be blocking each other's database access. Each worker should have its own db connection, right? So the account installation job shouldn't have to fight other workers for a connection. Am I missing something?

Or is database performance to be blamed? I have a hard time believing this, though, because I noticed a 2x slowdown going from one to just two workers.

Here are my app's details:

* Rails 4.2
* Ruby 2.0.0
* Sidekiq 3.3.0
* MySQL

Thanks in advance for any help!

**Comment by mperham** [comment]
Seems like this has everything to do with your database (and hardware).  Possibly you are slamming the disk.  If the task is CPU-heavy, the job concurrency won't scale well due to GIL.

**Comment by smidwap** [comment]
Thanks as always for the quick replies.

I don't think this is a database performance issue. I did another experiment to see if the database is at fault. With Sidekiq busy, I ran my critical job both in Sidekiq and in a separate process (rails console) and measured the processing time of the job. If the database were at fault, I'd expect the processing times to be about equal, since the job queries the same db regardless of where it's run.

I don't think this is a database performance issue. I did another experiment to see if the database is at fault. With Sidekiq busy, I ran my critical job both in Sidekiq and in a separate process (rails console) and measured the processing time of the job. If the database were at fault, I'd expect the processing times to be about equal, since the job queries the same db regardless of where it's run.

Instead, I found a dramatic increase in processing time when the job was run in Sidekiq.

Here are the two jobs I set up for the experiment:

```ruby
class CriticalJob < ApplicationJob
  queue_as :critical

  def perform(organization)
    1000.times { organization.touch }
  end
end

class OtherJob < ApplicationJob
  def perform(suggestion)
    suggestion.touch
  end
end
```

To put Sidekiq to work, I queued up `OtherJob` a few thousand times. Concurrency was set to 20 threads, and the db pool size was 20. I ran `CriticalJob`, both in Sidekiq and in my console, and measured a few trials. Here are my results:

Critical Job Run Where? | Trial 1 | Trial 2 | Trial 3 | Average (ms)
------------ | ------------- | ------------- | ------------- | -------------
Sidekiq | 53,221	| 59,810 | 49,526 | 54,186
Console | 5,355	| 4,594 | 5,417 | 5,122

`CriticalJob` saw a 10x increase in processing time when run in Sidekiq.

I also profiled time spent in the database. `CriticalJob` spent ~7s in the db when run in Sidekiq, and ~1.4s when run in the console. That's a bit mystifying to me, since the db should be under equal load in both cases. That's why I questioned Sidekiq's use of the db pool in my original note.

Could this be a CPU issue? Doesn't seem as if I'm running anything CPU-intensive. But I'll be the first to admit I'm not sure how to profile CPU usage and run a test to isolate that effect. All ears if you have ideas.

Thanks again for your help. Would love to get to the bottom of this. High concurrency isn't all that useful if jobs simply take longer to run.

**Comment by mperham** [comment]
Sidekiq does not use active record at all, therefore I'm not sure how sidekiq can influence the behavior unless there is a threading issue in your application's configuration.

**Comment by mperham** [comment]
What you need to do is run multiple jobs concurrently in N threads in the console.  If it doesn't show the same slowdown, that lends more credence to your claim that Sidekiq is at fault.

**Comment by smidwap** [comment]
I'll try that and report back. Thanks for the tip.

**Comment by smidwap** [comment]
Ran the test you suggested (run a bunch of jobs concurrently in the console), and it showed the same slowdown as Sidekiq. Confirms that Sidekiq isn't at fault here. I'm just hitting the limits of concurrency.

So high concurrency isn't great for time-sensitive jobs that are CPU-heavy. Or put another way, concurrency is most useful when tasks are heavily blocked by something other than the CPU (external database calls, email delivery, etc). Hadn't thought about it before. Makes sense. Good lesson here.

**Comment by prsanjay** [comment]
@smidwap So how did you handle CPU intensive but critical jobs then?

**Comment by smidwap** [comment]
Can't recall this specific case. But apps should be designed so a
relatively slow job doesn't disrupt the user's experience. e.g. display

a loading indicator / spinner if needed.

On February 4, 2021, Sanjay Prajapati <notifications@github.com> wrote:

> @smidwap <https://github.com/smidwap> So how did you handle CPU
> intensive but critical jobs then?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mperham/sidekiq/issues/3118#issuecomment-773780691>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAGB4MYOWRZBP7AYLXI63GDS5NYLFANCNFSM4COEOQWQ>.
