### ISSUE TITLE
Redis credentials leaked in the logs when sidekiq is booted

### ISSUE THREAD

**Issue by srkgupta** [mperham/sidekiq#3119]
I am using the Heroku and use Sidekiq with Redis. From the heroku logs, I see that Sidekiq is leaking the Redis credentials by displaying a log like this:

Booting Sidekiq 4.1.4 with redis options {:url=>"redis://:xxxxxxxxxxxxx"}

This is highly insecure as the logs are being read by several applications and these credentials can easily be compromised. We do not want any credentials to be shown in the logs.

**Comment by mperham** [comment]
We already [take pains to scrub the password out](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L75).  Maybe demand less from OSS maintainers and help track down the bug instead?

**Comment by srkgupta** [comment]
OK didnt realize this is already handled. Thanks.
