### ISSUE TITLE
Lost in Sidekiq::Client#raw_push?

### ISSUE THREAD

**Issue by oogali** [mperham/sidekiq#3121]
Ruby version: 2.2.3
Sidekiq version: 4.1.4
Rails version: 4.2.7.1
Redis version: 3.0.7

I'm trying to use Sidekiq with ActiveJob, and I'm running into a weird scenario -- jobs never get executed, specifically, jobs never make it to Redis.

I've defined a job class that subclasses from ActiveJob. I'm invoking the job by calling `#perform_later`. I've inserted some debugging prints all the way from `ActiveJob::QueueAdapters::SidekiqWrapper` to `Sidekiq::Client`.

I can dump the contents of `normed` and `payload` from within `#push`. But where I'm stuck is, it doesn't seem like `#raw_push` is being executed. I've inserted a simple puts call before we call out to Redis connection pool (with a block), and I don't see anything.

I've tried tracing things out from the Redis side, and there, I have no keys in Sidekiq that correspond to the set of queues, nor the lists that Sidekiq performs a blocking read against (with a 2 second timeout).

I thought it might be that I'm calling `#perform_later` from a scheduler that doesn't like threads (the clockwork gem), but even with Rails console/runner I get the same behavior.

Any thoughts or suggestions? Before I go down the dark road of ripping everything apart?

![That damned light bulb](http://i.imgur.com/t0XHtgJ.gif)

**Comment by mperham** [comment]
Middleware can block a push. Use "redis-cli monitor" to watch your Redis instance.

**Comment by oogali** [comment]
I started down that road and launched tcpdump. I don't see any new connections to Redis when I start/stop my scheduler (but I do see them when I start/stop my Rails app), so I now think my issue is outside the scope of this project.

I have to rip everything apart until I find the pesky gremlin.

**Comment by oogali** [comment]
This.

http://stackoverflow.com/questions/20365580/sidekiq-not-enqueuing-jobs
