### ISSUE TITLE
Can Sidekiq be configured to use events rather than threads?

### ISSUE THREAD

**Issue by JohnMerlino1** [mperham/sidekiq#3122]
On the github page, it says the following:

> Sidekiq uses threads to handle many jobs at the same time in the same process. 

The problem with threads is each thread requires its own stack, which increases memory consumption and can be a constrain on servers that have limited memory. Second, and more importantly, a thread blocks until the I/O operation (e.g. read, write) is ready. This is very inefficient, especially if the I/O takes a long time to respond. That thread is wasting time sitting there for a response. Event-driven runtimes like epoll do not block. A signal will notify the event loop when I/O is ready. 

So can Sidekiq use event architectures like how Nginx and Nodejs work?

**Comment by mperham** [comment]
Nope.  Ruby in general is not designed to be evented.  Almost every major library/gem assumes a threaded architecture, except ones designed for EventMachine.
