### ISSUE TITLE
Sidekiq::Web browser cache is not invalidated

### ISSUE THREAD

**Issue by dsander** [mperham/sidekiq#3127]
Ruby version: 2.3.1p112
Sidekiq version(s): 4.2.0@0168d42

The web interface does not invalidate the browser cache correctly when the content changes.

Reproduction steps:

* Have a rails application with sidekiq and sidekiq web mounted in the routes
* Start the rails server
* Open the scheduled jobs in the web interface
* Schedule a job `HardWorker.perform_in(1.hour, 123)`
* Refresh the scheduled jobs page
* The job is not shown in the page. 

Actions that "fix" the problem:

* Click on "Add to queue" with no job selected which then redirects back and shows the job
* Disable or clear the browser cache
* Restart the rails server

Please let me know if you need a sample repository to demonstrate the issue.

**Comment by dsander** [comment]
I should have noted, the rails env is development with puma as the application server.

**Comment by mperham** [comment]
Yeah, the page should not be cached at all.  @badosu This was reported by someone else too.  Any idea what's wrong?

**Comment by badosu** [comment]
I'll check this soon, thanks for reporting!

**Comment by badosu** [comment]
@mperham Where was this middleware being set up?

**Comment by mperham** [comment]
Rails

**Comment by melder** [comment]
Has this been fixed? Sidekiq AJAX requests are still being cached, even after reinstalling sidekiq 4.2.0

Whenever a /jobs/stats call is made a 304 is returned which indicates cache hit.

Using Rails 5.0.0.1

**Comment by mperham** [comment]
The html responses are not cached. I guess I missed the json responses. 

Mike

**Comment by mperham** [comment]
@melder Should be fixed on master now if you want to verify.

**Comment by melder** [comment]
Looks good. Thank you
