### ISSUE TITLE
Improve Batch tools

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3130]
Several customers have had batches which occasionally don't complete or trigger callbacks due to various issues: 3rd party plugins which subtly break Batch, incorrect Batch API usage, network outages, or bugs in the implementation.  How could we improve the Web UI and API to reduce problems and help the user to fix these problems?

Concerns: I don't want this tooling to become a chronic workaround to breakage.  Obviously the best solution is to find and fix the root cause.
1. Fix the `jobs` method so it can't be called outside of a batch job after the initial call - otherwise this introduces a race condition that can add extra jobs into the batch after callbacks have fired.
2. Update the Web UI to show JIDs which have not completed successfully if less than 10.  Allows the customer to search logs and the retry queue to help debug the issue.
3. Add a link on each batch to search the Retry queue for that BID - would find any jobs still awaiting retry which are blocking the success of the batch.
4. Most controversially, add a "Finish" button to Web UI which would fire the complete and success callbacks if the pending count is <= 0.  This would work around the negative pending counts a few customers have seen (which could mostly be due to [1]).

Further ideas welcome.

**Comment by kpheasey** [comment]
Delete batch option or someway to remove batches whose jobs have been deleted.

I've had problems where jobs in a batch could not be completed, so when I deleted them from retries.  This causes the batch to stick around forever.  I'm not sure how to clear them.

![screen shot 2016-10-11 at 5 47 42 pm](https://cloud.githubusercontent.com/assets/3934075/19289911/fc18ba1a-8fda-11e6-96ae-03995d2eabea.png)
![screen shot 2016-10-11 at 5 47 35 pm](https://cloud.githubusercontent.com/assets/3934075/19289912/fc1ce432-8fda-11e6-83db-7888243aa607.png)

**Comment by mperham** [comment]
You can use Sidekiq::Batch::Status#delete to remove all evidence of a batch.

**Comment by kpheasey** [comment]
How would I load only those batches?  There are batches constantly being created and processed.  I need to somehow identify only those problem batches that are lingering.

I'm not really annoyed by the lingering data, but application administrators investigating system state are annoying by it.

**Comment by mperham** [comment]
You can use `Sidekiq::BatchSet.new.each { |status| status.delete if lingering?(status) }` but you'll need to supply the lingering? method logic.  This is **highly** unsupported.

**Comment by kpheasey** [comment]
I apologize if this is bringing the issue off topic...

For the future, how can I handle deleting jobs without breaking batches?

**Comment by mperham** [comment]
You cannot delete jobs without really messing up Sidekiq.  You must [cancel them](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job).

**Comment by mperham** [comment]
One customer discovered that the Cloud66 PaaS was shutting down Sidekiq incorrectly, leading to missing jobs in their batches at deploy time.  They were using QUIT instead of USR1 to signal upcoming shutdown.

**Comment by mperham** [comment]
The Batch UI now shows the pending JIDs if the pending count is < 10 and has a Search button to find any Retries associated with this batch.

<img width="981" alt="screen shot 2017-03-17 at 10 18 17 am" src="https://cloud.githubusercontent.com/assets/2911/24054914/4287b4d8-0afb-11e7-8fed-c0d8dd989111.png">

**Comment by kohder** [comment]
Nice feature. Thanks!

Rob

**Comment by mperham** [comment]
Almost all stuck batch problems I've diagnosed have turned out to be due to incorrect deployment.  Send USR1/TSTP as early as possible, send TERM as late as possible and NEVER `kill -9` Sidekiq.
