### ISSUE TITLE
Sidekiq Enterprise Periodic Job Wiki Issue

### ISSUE THREAD

**Issue by DodgeDerek** [mperham/sidekiq#3132]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 0.7.10

The documentation around the explanation for the cron expression step format appears to be incorrect. According to some quick basic testing, the definitions are interpreted in the same fashion as typical cron expressions. The changes introduced [here](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs/_compare/f6f07f327cfe4a5117ae9de5beab541a3b0e1326...0f97327d4125d085af1a5daadd7c16f0515f3437) are where the different definition was introduced.

**Comment by mperham** [comment]
Hmm. I didn't make that wiki change. Just revert it if it's incorrect.

**Comment by wtfiwtz** [comment]
Sorry, I misread the code:

```
2.3.1 :026 >   stepped_range(0..60, 5)
 => [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
2.3.1 :027 > stepped_range(0..24, 5)
 => [0, 5, 10, 15, 20]
```

It is indeed a 'step value' not a 'divisor'...
