### ISSUE TITLE
Stacktrace (or line number) for errors

### ISSUE THREAD

**Issue by sandstrom** [mperham/sidekiq#3135]
Would it be possible to keep a stacktrace (or at least the line/col which raised the exception) for errors?

Right now it's a bit of guess-work to figure it out.

I know it's possible to grab the error and extract this info (we do this in production), but great benefit with the current admin-UI is that it's simple and convenient.

So extending it with stacktrace/line-number would be in that spirit. ⛵ 

![image](https://cloud.githubusercontent.com/assets/122287/18476805/ba17cc20-79cb-11e6-8f29-303f5f802816.png)

**Comment by mperham** [comment]
sidekiq_options backtrace: true

**Comment by sandstrom** [comment]
@mperham Thanks! 😄

**Comment by BartlomiejSkwira** [comment]
I have placed this snippet in my `config/initializers/sidekiq.rb` file:
```
#print backtraces when exceptions occur
Sidekiq.default_worker_options = { 'backtrace' => true }
```
Just remembert to restart the server for the initializer to work

The output should look like this:
![screen shot 2016-12-24 at 14 55 53](https://cloud.githubusercontent.com/assets/1316517/21467316/65d151d6-c9e9-11e6-889a-75261653d32d.jpg)
