### ISSUE TITLE
Makara Gem And Mysql2 Threads in use

### ISSUE THREAD

**Issue by grossjo** [mperham/sidekiq#3137]
Ruby version: 2.0
Sidekiq / Pro / Enterprise version(s): Sidekiq  4.1.3

I've recently started integrating the makara gem, and noticed some strange behaviour.
The stack trace is below.  This occurs in a low volume environment.  I was wondering if any one has some insight into this.

```
ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by: #<Thread:0x007fe9d80bd6e0 sleep>: SELECT `payment_provider_plans`.* FROM `payment_provider_plans` WHERE `payment_provider_plans`.`id` = 1 LIMIT 1
(eval):31:in `block in execute'
(eval):15:in `_makara_hijack'
(eval):27:in `execute'
(eval):51:in `block in exec_query'
(eval):15:in `_makara_hijack'
(eval):47:in `exec_query'
(eval):49:in `block in exec_query'
(eval):17:in `_makara_hijack'
(eval):47:in `exec_query'
```

**Comment by mperham** [comment]
I don't know anything about makara.  Seems like opening an issue with them would be more fruitful.
