### ISSUE TITLE
Could not fetch specs from https://gems.contribsys.com/ 20hrs ago 🙈

### ISSUE THREAD

**Issue by zerOnepal** [mperham/sidekiq#3141]
Ruby version: **2.3.0**
Sidekiq / Pro / Enterprise version(s): sidekiq-pro (3.0.0)
Full context:
```
:>grep sidekiq Gemfile.lock 
    sidekiq (4.0.1)
    sidekiq-pro (3.0.0)
      sidekiq (>= 4.0.0.pre1)
  sidekiq-monitor-stats
  sidekiq-pro!
```

**Problem:** : While doing bundle roughly  20 hrs ago i.e. `2016-09-14 08:25:43.151117 UTC`

> stdout: Could not fetch specs from https://gems.contribsys.com/

**Context**: I am using ansible to pull the latest codebase during autoscaling. And yesterday all of my worker instances were chocking with same error like, it cound't fetch specs from  _gems.crontribsys.com_  

**Was there any issue with server ?** Looks like we faced some server timeouts during that period. Lucky yesterday, no damange in TAT because of it  :see_no_evil: , but  it could be a serious disaster :skull: in days to come.
  
**cogent evidence**: raw  ansible debug logs: (not sure if its useful) 
```
TASK: [ansicap | Application requirement via bundler] ************************* 
failed: [127.0.0.1] => {"changed": true, "cmd": ["chruby-exec", "2.3.0", "--", "bundle", "install", "--binstubs", "bin", "--without", "development", "test", "darwin", "--frozen", "--quiet"], "delta": "0:02:26.176810", "end": "2016-09-14 08:28:09.327927", "rc": 17, "start": "2016-09-14 08:25:43.151117", "warnings": []}
stdout: Could not fetch specs from https://gems.contribsys.com/
FATAL: all hosts have already failed -- aborting
```
I found similar story https://github.com/mperham/sidekiq/issues/1220 
@mperham @kajisaap @sameergautam

**Comment by mperham** [comment]
Please email me with your account info.

**Comment by zerOnepal** [comment]
:smile: sure

**Comment by ACPK** [comment]
@mperham - It started hitting this same issue about an hour ago.

**Comment by thapakazi** [comment]
**Back to the square one, my bundle is chocking for the same reason**. I wonder if someone's got paged :pager: for this. :neckbeard:  

Looks like some kind of outage, I will send my sidekiq details if necessary @mperham

**Comment by jorge-d** [comment]
Same here, we can't deploy as our `bundle install` step fails

**Comment by rohandaxini** [comment]
Same issue for us as well, unable to deploy due to these failures,

**Comment by iMacTia** [comment]
Same here, https://gems.contribsys.com/ is timing out.
Production deploy blocked.
Anyone aware of a quick fix? We don't really need to update Sidekiq, we just need to deploy with Capistrano

**Comment by austinwang** [comment]
Same here.

**Comment by lefty313** [comment]
@iMacTia

maybe `bundle package` on localhost from your personal gemset ? :)

**Comment by dawidpawliszko** [comment]
Same here. Got timeout when calling https://gems.contribsys.com/.

**Comment by iMacTia** [comment]
Guys, please report in the new #3427 rather than in this closed Issue

**Comment by iMacTia** [comment]
@lefty313 thanks, I'll have a look at that

**Comment by NielsKSchjoedt** [comment]
same here
