### ISSUE TITLE
Recurring/Scheduled jobs in Sidekiq 4

### ISSUE THREAD

**Issue by shakycode** [mperham/sidekiq#3142]
Ruby version: 2.1.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 4 open source

Currently not experiencing any exceptions but looking for a way to schedule jobs using Sidekiq 4 or another 3rd party gem.

Up until 3.5.1 Sidetiq was my go to tool for scheduling jobs (as I have an app that has jobs firing off ever 2-3 seconds 24/7.  This worked great (and still does) on =< 3.5.1 but upgrading to Sidekiq 4 in a testing branch Sidetiq is not compatible and the Celluloid actors crash immediately.

The app I'm working on is open source so I'm not in a position to purchase Pro/Enterprise (although i'd love to use it), but was wondering if anyone in the community can give me an idea of how to schedule recurring jobs or use a tool that will work with Sidekiq4.  (Clockwork, or sidekiq-cron perhaps?)

Thanks in advance and sorry if this is not a real issue, just trying to figure out if we move to Sidekiq 4 or stick at 3.5.1

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Related-Projects#recurring-jobs
