### ISSUE TITLE
Possible bug in testing.rb, when using Sidekiq::Testing

### ISSUE THREAD

**Issue by cbaines** [mperham/sidekiq#3144]
When adding the job to the Queue, it [uses the value corresponding to the `"queue"` key in the job hash][2], but for [deleting that it has just processed ][1], the [queue from the sidekiq_configuration of the Worker is used][3]. This means that the job is only removed from the `jobs_by_worker` hash in the Queue, and not the `jobs_by_queue` Hash, leading to `drain_all` repeatedly trying to get a worker to work on the job (as it uses `jobs_by_queue`), and the worker not finding a job to work on (as it uses `jobs_by_worker`).

[1]: https://github.com/mperham/sidekiq/blob/72fe3289eabb5e4b01165d3e4e61b1ee08869223/lib/sidekiq/testing.rb#L267
[2]: https://github.com/mperham/sidekiq/blob/72fe3289eabb5e4b01165d3e4e61b1ee08869223/lib/sidekiq/testing.rb#L72
[3]: https://github.com/mperham/sidekiq/blob/72fe3289eabb5e4b01165d3e4e61b1ee08869223/lib/sidekiq/testing.rb#L249

**Comment by cbaines** [comment]
I managed to get my test working if I [switched to using the value for the `queue` key of the job (instead of the Worker default) here](https://github.com/mperham/sidekiq/blob/72fe3289eabb5e4b01165d3e4e61b1ee08869223/lib/sidekiq/testing.rb#L267).

**Comment by mperham** [comment]
Sounds like you've found the fix, send a PR?

**Comment by cbaines** [comment]
Unfortunately, I fall in to the "cannot or do not want to reassign those rights" category as described in the contributor guidelines.
