### ISSUE TITLE
Possible to unlock rack-protection version?

### ISSUE THREAD

**Issue by apolzon** [mperham/sidekiq#3145]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 4.2.x

Was really happy to see the ability to remove the sinatra dependency and still use the sidekiq web-ui. However, I have a test-environment gem which still needs edge sinatra, and the updated sidekiq dependency of rack-protection ~> 1.5 causes a dependency conflict.

Edge sinatra currently has a minimum dependency of rack-protection 2.0.0.beta2. Is it possible that the new sidekiq web-ui code will be updated to support rack-protection 2.x? I totally understand if it doesn't happen before rack-protection moves to an official release, but it would be a bummer if any Rails 5+ app that needed sinatra was stuck on Sidekiq 4.1.x.

Thanks.

**Comment by mperham** [comment]
If someone wants to test it, that's fine.  I don't generally support gems until they are out of beta but if it works, we can unlock the dependency.
