### ISSUE TITLE
Sidekiq mails are processed but not getting to inbox

### ISSUE THREAD

**Issue by NRamakrishna** [mperham/sidekiq#3149]
Hello all, I am using redis-server with sidekiq for background jobs. In development environment mails are sending to the inbox but not getting mails in production mode.

I am using ruby 2.1.8, rails 4.1.8 and redis server 2.8.4

Please let me know the solution.
Thankyou

**Comment by seuros** [comment]
This issue in unrelated to sidekiq. Check your configuration(SPF,DMKS,ect) or use a SAAS service.

**Comment by NRamakrishna** [comment]
@seuros 

Everything working good if not using sidekiq and redis, but when background jobs not getting mails

**Comment by seuros** [comment]
You probably passing an object to the worker. 

Show me the worker perform().

**Comment by NRamakrishna** [comment]
I am not using any worker.

config.ru
require 'sidekiq'
Sidekiq.configure_client do |config|
  config.redis = { :size => 1 }
end
require 'sidekiq/web'
run Sidekiq::Web

**Comment by NRamakrishna** [comment]
Please guide me on this.
Thankyou

**Comment by mperham** [comment]
Please read through the ActiveJob guide to make sure your Rails app is configured correctly.  This is not a Sidekiq bug so please search on StackOverflow to find solutions to your problem.

http://guides.rubyonrails.org/active_job_basics.html#action-mailer
https://stackoverflow.com/search?q=%5Bsidekiq%5D+email
