### ISSUE TITLE
Web UI in 4.2 is partially broken

### ISSUE THREAD

**Issue by whitelancer** [mperham/sidekiq#3150]
Ruby version: 2.3.0
Sidekiq version(s): 4.2, 4.2.1

config/routes.rb:
```
authenticate :user do
  mount Sidekiq::Web => '/sidekiq'
end
```

Before 4.2 (ie, 4.1.x) we were using our sidekiq web dashboard as normal.  After this change, I am seeing two issues.

First, all our assets return 404 errors -- I cannot seem to load them.  We do use puma/nginx but again, we've got those settings as they should be with nginx forwarding our assets directly to rails (as per the FAQ for sidekiq).  In addition we have rails' x_sendfile configured properly: `config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'`

Again, everything was working pre 4.2 just fine.  The move to rack has changed something there.

Additionally, I'm also getting 500 errors when I click over into any of the categories .... busy, retried, enqueued, etc.  However when I reload, that 500 error *usually* goes away and I can load the page's data (sans css) normally.  It's really strange.  Sometimes it takes multiple reloads to get the data to show, but it does usually show up.

I don't really know how to debug this; I've been trying to watch our logs to see about errors, but I'm not seeing any of the sidekiq requests hitting our rails logs.  

How may I help you with debugging this issue?

**Comment by mperham** [comment]
Best is if you can get us a simple Rack/Rails app which reproduces the problem.  Assets are served by Rack::File here: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L130

**Comment by whitelancer** [comment]
Alright, thanks.  I'll see what I can do to identify.  Do you know of any logging that I can enable that may help track down what's going on?

**Comment by mperham** [comment]
I don't.

**Comment by whitelancer** [comment]
Just an update; I compared one app to another and one of the differences has been an older version of devise.  I was running 3.x on the broken server and 4.2 on the good one.  After upgrading my app that was having issues to devise 4.2, Sidekiq's web UI stopped working.

Just for kicked I downgraded to devise 3.5.6 and got the same broken sidekiq UI.  I have no idea why but I'm sure there's something with the way they both mount into the routing somehow?  Maybe devise 3.x was interfering with the rack-based setup of Sidekiq 4.2.

**Comment by mperham** [comment]
Sidekiq 4.2 completely rewrote the Web UI internals.  I'd guess it will work with Sidekiq 4.1.4.

**Comment by whitelancer** [comment]
Hi Mike,

Yes, that's correct!  I also can verify that Sidekiq 4.1.4 works with that older version of Devise.  That was our original course of action to "fix" this issue.  However we're very excited for the on-demand code reloading in Sidekiq 4.2 --- thank you so much for that!!  We were definitely looking forward to that feature and now I'm glad 4.2 seems to be happy with the latest version of Devise.  Thanks again for helping out!  Consider this closed but perhaps you might mention the incompatibility with Devise 3.x when upgrading to Sidekiq 4.2?  Thanks!

**Comment by mperham** [comment]
Thanks for the update.  It's very confusing that Devise is also version 4.2. :-)
