### ISSUE TITLE
New Web UI Rack App doesn't respond to root URL without trailing slash

### ISSUE THREAD

**Issue by timdorr** [mperham/sidekiq#3151]
This is silly, but annoying only because I have to get my browser to re-learn a new favorite URL. Feel free to file this under a "whine" label!

Because of the new internal router on the Rack-ified Web UI, if you have it mounted on a URL like `/sidekiq`, it will not match for `http://whatever.com/sidekiq`. It instead needs the trailing slash: `http://whatever.com/sidekiq/`

Pretty silly and pedantic. Probably a quick fix in there somewhere (maybe a special case for the `/` route?). But it's the only annoyance I've had with the new code. Otherwise, it's pretty solid!

**Comment by timdorr** [comment]
BTW, I was able to work around this with a little bit of monkey patching:
```rb
module Sidekiq
  class WebApplication
    get '' do
      redirect(root_path)
    end
  end
end
```

**Comment by mperham** [comment]
Thanks, Tim, want to send a PR?

**Comment by timdorr** [comment]
Yep, I'll get something together tomorrow when I'm not on a phone.
