### ISSUE TITLE
Access JID from within ActiveJob callbacks

### ISSUE THREAD

**Issue by antstorm** [mperham/sidekiq#3155]
Ruby version: 4.2.7
Sidekiq / Pro / Enterprise version(s): 4.1.4

I'm in the process of switching from Resque to Sidekiq and it's been fairly painless because of the ActiveJob. But one thing that I'm still trying to figure out — we're using ActiveJob callbacks for external logging purposes and there's an AJ `job_id` and `jid` mismatch (I need a way for our support team to reference Web UI jobs to log records). So… is there a way to access Sidekiq's `jid` from AJ callback?

I know you can catch it in `around_enqueue` and assign to a local variable, but that's obviously not available in `_perform` callbacks, so that didn't work.

P.S. Yes, I know that I can move to Sidekiq's Middware. Wondering if I can get away with AJ callbacks.

**Comment by mperham** [comment]
I don't know the answer.  Rails 5.0 exposes the JID as `provider_job_id`, but I don't know if it's available in callbacks.

**Comment by antstorm** [comment]
@mperham thanks, I'll dig in then and report back if I find the answer.

**Comment by antstorm** [comment]
Ok, so after digging around it seems like there's no way of doing that because `JobWrapper` looses all references to `Sidekiq::Worker` when running `Base.execute`. Seems like the only way to get around this is by establishing a back-reference to the original class which would require changes in both AJ and Sidekiq.

At first ActiveJob seemed like a great idea, but now after digging through the implementation details it looks like a big mess. Yes, we are getting a better structure, but at a quite high cost.

I ended up monkey-patching `Sidekiq::Job#display_args` to include AJ's `job_id` in Web UI, but that's just a temporary solution before we switch to a pure Sidekiq solution.
