### ISSUE TITLE
Rails 5 Reloader Threading Issues

### ISSUE THREAD

**Issue by sj26** [mperham/sidekiq#3157]
We upgraded to Rails 5.0.0.1 and Sidekiq 4.2.1 + Sidekiq Pro 3.3.3 last week. :tada:

After the upgrade we started noticing threading issues in our Sidekiq workers.

Turns out [the new Rails reloader](https://github.com/mperham/sidekiq/blob/v4.2.1/lib/sidekiq/cli.rb#L243) does a lot of funny business which isn't entirely obvious including [ActiveRecord connection management](https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/query_cache.rb#L46-L50), [QueryCache enable/disable](https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/query_cache.rb#L26-L41) around each job, and [code reloading](https://github.com/rails/rails/blob/v5.0.0.1/railties/lib/rails/application/finisher.rb#L115-L175) with mutexes and shared locks. Some of these things are done by the Executor, not the Reloader, but they seem pretty interlinked with one calling the other. With several threads starting similar jobs with similar autoloaded dependencies we discovered workers were easily becoming deadlocked on code reloading, and we've also been experiencing stale QueryCache results within worker threads.

As a fix for now we've added a `:require: ./config/sidekiq.rb` to our `config/sidekiq.yml` with `config/sidekiq.rb` containing [the old Rails 4 behaviour](https://github.com/mperham/sidekiq/blob/v4.2.1/lib/sidekiq/cli.rb#L233-L239):

```ruby
require "./config/application.rb"
::Rails::Application.initializer "sidekiq.eager_load" do
  ::Rails.application.config.eager_load = true
end
require "sidekiq/rails"
require "./config/environment.rb"
```

The actual root cause of the threading issues is so far unclear, but I suspect lies within Rails 5's concurrency primitives. I found [ActiveSupport::Concurrency::ShareLock](https://github.com/rails/rails/blob/v5.0.0.1/activesupport/lib/active_support/concurrency/share_lock.rb) at the top of most locked threads' stack traces.

**Comment by mperham** [comment]
Ugh, not surprising considering how complex this is but there's not much we can do about it in Sidekiq.  Please do open a rails/rails issue so that the core team knows this, especially if you have a sample app/script which can repro the behavior.

**Comment by sj26** [comment]
Sorry, I do realise that this isn't really something sidekiq can fix and I am working on a repro case for rails — but, as you can imagine, it's proving pretty difficult to make it consistent! Just thought it might be nice to drop a note here, given that it was a sidekiq change that has introduced unexpected behaviour which might catch others and can be reverted to the (perhaps less correct) prior behaviour.

It might be worth adding a note in the changelog that the reloader also changes how code is loaded in production and introduces ActiveRecord connection management and query caching which folks might not expect? Especially if they're using the ActiveRecord sidekiq middleware as well.

Does the reloader setup still do an eager_load at sidekiq boot time in production, or does it wait for the first request?

It also looks like the reloader is always used, even in production? This doesn't seem to be the case [in ActionDispatch](https://github.com/rails/rails/blob/f08bb28702a2df5d2f9e3a354aa63cf7e738dc58/railties/lib/rails/application/default_middleware_stack.rb#L51-L53) and ActionCable does [something even more funky](https://github.com/rails/rails/blob/f08bb28702a2df5d2f9e3a354aa63cf7e738dc58/actioncable/lib/action_cable/engine.rb#L52-L75).

**Comment by mperham** [comment]
Sidekiq uses the Reloader API in all environments.  I assume it is inactive in production but don't know for sure.

**Comment by mperham** [comment]
Your Rails production environment configuration should declare eager load, otherwise that's a big performance hit, and I believe it's the default setting.

**Comment by connorshea** [comment]
@mperham maybe that should be mentioned in the Changelog or something?

**Comment by mperham** [comment]
No one else is reporting issues.  Is it possible your app config is slightly funny/nonstandard?

**Comment by sj26** [comment]
[Our app](http://buildkite.com) is a pretty standard-ish Rails setup, except that it does high frequency at high concurrency so we tend to hit any threading issues that could possibly occur. We have many machines running a several of either puma or sidekiq processes with many threads each. It's possible that nobody else will hit this issue, and it's just our system's emergent complexity from this concurrency.

I haven't had much more time to craft a test case for Rails, but if I can replicate it then I'll take it upstream. I'm fairly sure we're hitting issues with the new ActiveSupport::Dependencies::Interlock. I'm not sure why we were getting stale QueryCache entries, but removing the reloader as I mentioned in the initial issue report seems to prevent QueryCache use completely which is our current workaround.

In the meantime, maybe Sidekiq should follow the ActionController and ActionCable conventions to use Rails::Application#executor around all jobs and add the Rails::Application#reloader only when cache_classes is off, i.e. in development. I'm not convinced that this would solve our issues, but it seems like the more expected behaviour. @matthewd may have opinions on this?

The part I found most surprising, though, is that the changelog entry "Enable development-mode code reloading" actually changed production behaviour and opted us in to ActiveRecord query caching. I think maybe the changelog could be a little more explicit about the side effects of that change.

**Comment by mperham** [comment]
@matthewd wrote the Sidekiq integration IIRC, I assume it would act correctly in development and production.  If you want to send a PR with your proposed changes, he and I can review.

**Comment by matthewd** [comment]
The reloader only actually reloads things in development mode (well, when cache_classes is off)... but it does invoke the executor, which handles "other stuff" that should occur around any user code. Within the framework, that's currently query caching and DB connection management (returning AR connections to the pool).

Sidekiq has its own mechanism for the latter, of course, so if you skip the reloader you're not missing out on anything vital.

We omit the reloader middleware if we know reloading's going to [be disabled](https://github.com/rails/rails/blob/v5.0.0.1/railties/lib/rails/application/finisher.rb#L145), just because our middleware stack is substantial and visible, so it's worth avoiding the no-op entry. But we still invoke the executor.

If you're having an issue with the AR query cache, that's probably where we need to focus: it's supposed to work :smile:

Sadly we don't have a good way to just disable the cache at the moment -- my best suggestion would be to install an executor hook that disables it just after it gets enabled. We need to improve that story for other reasons, though.

**Comment by sj26** [comment]
Had a chat to @matthewd and we discovered there is a bug here. Sidekiq adds the ActiveRecord middleware automatically, and also adds the Rails reloader automatically, but they are incompatible.

The reloader turns on query caching before it yields, and turns it back off and clears the cache afterward. But the middleware clears the active connection before it gets back to the reloader so it doesn't know which connection's query cache to clear. This means new jobs could start with a previous job's dirty query cache. This is the issue we were seeing.

I've just prepared a pull request to fix it: #3166

**Comment by sj26** [comment]
For my code loading issue, it's probably becoming locked on a shared resource. I'm investigating it separately, and I suspect it's something to fix in our code or in Rails.

@matthewd helpfully pointed out there is a handy tool for diagnosing code loading deadlocks available on Rails master for anybody else who might discover this thread:

https://github.com/mperham/sidekiq/pull/3166

**Comment by sj26** [comment]
We've been able to restore code reloading while preventing stale query caches in Sidekiq by removing the default ActiveRecord middleware from our server middleware chain:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware.remove Sidekiq::Middleware::Server::ActiveRecord
end
```

We've also added this as a guard:

```ruby
class ActiveRecordQueryCacheGuardMiddleware
  def call(*args)
    unless ActiveRecord::Base.connection.query_cache.empty?
      Sidekiq.logger.warn "Beginning job with dirty query cache, clearing."
      ActiveRecord::Base.connection.query_cache.clear
    end

    yield
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware.add ActiveRecordQueryCacheGuardMiddleware
end
```

After #3166 we'll be able to remove these and everything should be fine!
