### ISSUE TITLE
Shouldn't we document an official blue-green deployment strategy in the Wiki?

### ISSUE THREAD

**Issue by rosenfeld** [mperham/sidekiq#3160]
Hi, while reading the Deployment guide instructions I missed a common case for getting zero downtime, often referred in as green-blue (or A/B) deployment.

The way I see it being used for Sidekiq would be (suppose we are deploying to green and all current traffic is going to blue):

Each variation (blue, green, whatever) would have its own Sidekiq queue. With that in mind:

1 - stop the green app (it should be already inactive by now);
2 - stop the sidekiq processes processing the green queue (usually that would happen immediately as most likely all jobs from the green queue have finished processing long ago);
3 - upgrade the green version with latest changes;
4 - start the green app processes;
5 - start sidekiq processes processing the green queue;
6 - verify the green variation is working as expected, run tests and so on;
7 - switch the main domain to point to green;

The reason for these steps are to ensure sidekiq jobs are processed with the expected code and database running in the app (think about migrations for example, or changes in the job params).

Since this differ a lot from the current instructions, maybe it would be a good idea to document how blue-green deployment would work there. Maybe others could read and suggest any improvements to those steps...

Please let me know if you would like me to add such changes to the Wiki when I find a spare time.

Cheers.

**Comment by rosenfeld** [comment]
Please notice that this use case is different from this other strategy which also uses the same name (canary) but for different purposes:

http://dmathieu.com/articles/development/sidekiq-canary/
https://github.com/dmathieu/sidekiq-canary

That case will consider the API of the jobs remain the same and they want to see if the new version won't introduce regressions, while the strategy I described has other goals, like avoiding errors when the job params have changed or if the database schema has changed...

**Comment by mperham** [comment]
If you want to add a section documenting it, I think that's great - go ahead.  I would love to see a user document their working process.
