### ISSUE TITLE
Periodic jobs not scheduled

### ISSUE THREAD

**Issue by edwinv** [mperham/sidekiq#3163]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.4 / Pro 3.3.3 / Ent 1.3.2

Today we discovered that SQ Periodic hasn't scheduled the jobs for a particular service since 4 days. This service hasn't been restarted since the last deploy (6 days ago).

The `dear-leader` Redis key contains a valid process id. This process is running, although we haven't checked if it is actively processing jobs. A restart of the process fixed the issue, all periodic jobs are scheduled again.

We have search for other exceptions around this time, but we cannot find a cause for this issue. There was some load on Redis last week, but this hasn't caused any outages or fail-overs. We'd expect more exceptions when this would happen.

We are now in the process of upgrading to the latest SQ versions and will keep monitoring the periodic jobs.

**Comment by mperham** [comment]
If this happens again, please send the TTIN signal to the leader process to get an active thread dump.

**Comment by mperham** [comment]
Edwin, I reviewed the code and don't see anything that might cause the periodic subsystem to stop but that doesn't mean it's not there.  The subsystem logs its events with the word "periodic" so review your logs if this happens again for that word and see if you can get the leader's TTIN dump too.  I'm going to close this in the meantime so it doesn't linger forever.
