### ISSUE TITLE
Missing sidekiq_web_path

### ISSUE THREAD

**Issue by kotowick** [mperham/sidekiq#3164]
Ruby version: 3.2.1
Sidekiq / Pro / Enterprise version(s):

It seems like the prefix verb for Sidekiq::Web is missing. Getting a complaint in the web view about sidekiq_web_path not existing. Any ideas?

<img width="701" alt="screen shot 2016-09-27 at 3 55 38 pm" src="https://cloud.githubusercontent.com/assets/1714316/18894956/e999eec4-84ca-11e6-8b7b-7e033250886c.png">

The route file contains:
  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/schedules'
  end

**Comment by mperham** [comment]
I don't plan on adding this.  If you want this, seems simpler to add a constant to your code.

**Comment by timdorr** [comment]
You should be able to add an alias with `as:`:
```rb
mount Sidekiq::Web, at: '/schedules', as: 'sidekiq_web'
```
