### ISSUE TITLE
OpenSSL::SSL::SSLErrorWaitWritable

### ISSUE THREAD

**Issue by mydiemho** [mperham/sidekiq#3165]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq

Problem:
OpenSSL error when trying to push a large payload > 128 KB to ssl port on Redis.

Description:
I'm doing some performance test from Sidekiq to [Azure Redis Cache](https://azure.microsoft.com/en-us/documentation/articles/cache-faq/).  

1) When pushing a large payload (>128KB) to a non-ssl port, everything works fine.

2) When pushing a large payload (>128KB) to a ssl port, client crash with 

```
/home/mho/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:379:in `syswrite_nonblock': write would block (OpenSSL::SSL::SSLErrorWaitWritable)
        from /home/mho/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:379:in `write_nonblock'`
```

**Comment by mperham** [comment]
This is not a Sidekiq issue but an OpenSSL issue with your Ruby binary.  Nothing Sidekiq can do about it and you'd get the same behavior in rails console.

**Comment by mydiemho** [comment]
Thank you for the clarification.
