### ISSUE TITLE
Sidekiq keep shutting down (prod)

### ISSUE THREAD

**Issue by liborzahradka** [mperham/sidekiq#3172]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.1.4

I'm just wondering if someone had same issue with sidekiq like me.. Using rails with 2 env on different instances(prod,dev), but on prod sidekiq just keep shutting down after several hours, and dev is working just fine.

Sidekiq log checked (no error)
Redis server log checked (no error)
Prod log checked (no error)
System log checked
Sidekiq job is fine
Checked OOM Killers

So I'm wondering where or what i missed. Appreciate any help with that..

**Comment by mperham** [comment]
Sounds like you've covered everything I can think of, I have nothing further to suggest.  Sorry to hear of your troubles and I hope you track it down quickly.
