### ISSUE TITLE
Feature Request: Conditional Retry Logic

### ISSUE THREAD

**Issue by corytheboyd** [mperham/sidekiq#3173]
We have a non-trivial worker class with a nasty amount of `rescue` statements performing custom error handling. Some branches of the error handling behave differently when retrying the job-- sometimes we should retry indefinitely, or never retry, or only retry 5 times at a constant interval of 5 seconds instead of the default exponential backoff.

It would be nice to leverage the existing error handling mechanisms [documented here](https://github.com/mperham/sidekiq/wiki/Error-Handling), but those only kick in when _any_ exception is raised.

Without mandating what it should look like, it would be awesome if the retry mechanism of Sidekiq could be configured with different strategies based on exception class.

What are your thoughts? The idea still needs some work, but am curious to hear some thoughts on the subject.

---

Ruby version: 2.1.7
Sidekiq / Pro / Enterprise version(s): `sidekiq@4.1.0` `sidekiq-pro@3.3.1`

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Error-Handling#no-more-bike-shedding

There are 3rd party gems which add more bells and whistles to the retry subsystem, e.g. https://github.com/govdelivery/sidekiq-retries, but I don't want one person's really complex requirements to make the code complex for everyone.  I believe the current impl is a fair balance between simple and complex and offers enough flexibility for 90% of users.
