### ISSUE TITLE
Question: "Stuck" worker

### ISSUE THREAD

**Issue by harukizaemon** [mperham/sidekiq#3175]
I am using Sidekiq to manage a queue of work around physical devices. I have a demo box that has only 1 physical device attached and therefore the concurrency is set to 1.

I am also running ActiveJobs in a Rails environment.

I had an initialiser that sets the ActiveRecord connection pool size to match the concurrency and in this case that means it was set to 1 also.

When this happened, I could see log messages from Sidekiq that my job had "started" but the ActiveJob code never ran.

I then set the pool size 2 and, voila!

As you can see, I've now added a buffer of 2 connections anyway but I was still curious if anyone knew why this was happening?

Ruby version: 2.3.1
Sidekiq gem: 4.2.2;
Redis gem: 3.3.1
Redis version: 3.2.4

Initializer:

```ruby
# frozen_string_literal: true

Sidekiq.configure_client do |_config|
end

Sidekiq.configure_server do |_config|
  Rails.application.config.after_initialize do
    Rails.logger.info("DB Connection Pool size for Sidekiq Server before disconnect is: #{ActiveRecord::Base.connection.pool.instance_variable_get("@size")}")
    ActiveRecord::Base.connection_pool.disconnect!

    ActiveSupport.on_load(:active_record) do
      config = Rails.application.config.database_configuration[Rails.env]
      config["pool"] = Sidekiq.options[:concurrency] + 2
      ActiveRecord::Base.establish_connection(config)

      Rails.logger.info("DB Connection Pool size for Sidekiq Server is now: #{ActiveRecord::Base.connection.pool.instance_variable_get("@size")}")
    end
  end
end
```

**Comment by mperham** [comment]
It's common for gems to use the DB while running initializers so the main thread may have a DB connection checked out for all time, which would explain why you need two.

**Comment by harukizaemon** [comment]
@mperham Thanks Mike. That makes sense, and much appreciated.
