### ISSUE TITLE
failed job details

### ISSUE THREAD

**Issue by junaid-malik-confiz** [mperham/sidekiq#3176]
Hello,

We have some failed jobs and we want to know job detail so that we can submit again manually. I tried gem 'https://github.com/mhfs/sidekiq-failures' but it didn't work and displayed no job in the 'Failures' tab. Anyone can tell how we can find this information.

Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): Sidekiq free version

If relevant, please include your initializer and any error message with the full backtrace.

Sidekiq.configure_client do |config|
  config.redis = Discourse.sidekiq_redis_config
end

Sidekiq.configure_server do |config|
  config.redis = Discourse.sidekiq_redis_config
  config.failures_max_count = 5000

  config.server_middleware do |chain|
    chain.add Sidekiq::Pausable
    # ensure statistic middleware is included in case of a fork
    chain.add Sidekiq::Statistic::Middleware
  end
end

Regards,
Junaid

**Comment by mperham** [comment]
You are looking for the Retries tab, which saves all failed jobs for retry later.  Note the `backtrace` option.  Read more: https://github.com/mperham/sidekiq/wiki/Error-Handling

Note that sidekiq-statistic has a bad memory leak and should not be used.
