### ISSUE TITLE
Top menu vanishes when enclosed inside an iframe

### ISSUE THREAD

**Issue by akkee** [mperham/sidekiq#3177]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.4

When enclosing the sidekiq_web_path inside an iframe, the top menu does not appear in the sidekiq dashboard.

**Comment by mperham** [comment]
Screenshot?  HTML page which reproduces the problem?

**Comment by akkee** [comment]
![image](https://cloud.githubusercontent.com/assets/10128534/19315189/6497f3be-90ba-11e6-8c73-3c031a5f9b43.png)

**Comment by mperham** [comment]
You have to push down bootstrap page content on your page containing the iframe.

http://stackoverflow.com/a/22949128/1494519

**Comment by akkee** [comment]
Thank you. I think that would work.
