### ISSUE TITLE
Can't load UI assets in Heroku production env

### ISSUE THREAD

**Issue by benoittgt** [mperham/sidekiq#3179]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.2 / 3.3.3

Hello

I udpated to last sidekiq (normal and pro) and since I don't have anymore assets with the admin dashboard. The problem is, it happens only in production (not integration, or demo). Heroku return: 

`sock=backend at=error code=H18 desc="Server Request Interrupted" method=GET path="/admin/sidekiq/stylesheets/bootstrap.css"` 
`sock=backend at=error code=H18 desc="Server Request Interrupted" method=GET path="/admin/sidekiq/stylesheets/application.css"`

Any idea?

I will also contact Heroku support.

Thanks

**Comment by mperham** [comment]
If it works in other Heroku environments but not production, I would speculate that something is configured differently in production.  This thing immediately came to mind:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#sidekiq-web-does-not-render-correctly-in-production-but-works-fine-in-development

**Comment by benoittgt** [comment]
Hello Mike

Thanks for you answer. I'm on Rails 4.2.5.2 and assets don't return 404. 
![capture d ecran 2016-10-06 a 10 04 22](https://cloud.githubusercontent.com/assets/8417720/19144882/5f97633a-8bac-11e6-8b5f-956fd5e9932e.png)

The reponse from Heroku is to make local curl request on a sidekiq asset
```sh
$ heroku run bash -a app-production
```
then on the dyno
```sh
$ bundle exec puma -C config/puma.rb &
$ curl http://localhost:$PORT/admin/sidekiq/stylesheets/bootstrap.css
Dalli/SASL authenticating as memcached-app258737
Dalli/SASL: Authenticated
Started GET "/admin/sidekiq/stylesheets/bootstrap.css" for 127.0.0.1 at 2016-10-05 15:05:09 +0000
cache: [GET /admin/sidekiq/stylesheets/bootstrap.css] miss
You need to sign in or sign up before continuing.
```
But with warden it's a pain to authenticate with curl. For the moment it's a fail.

**Comment by benoittgt** [comment]
For the update I jump from
```diff
-    sidekiq-pro (3.2.1)
+    sidekiq-pro (3.3.3)
-    sidekiq (4.1.2)
+    sidekiq (4.2.2)
+      rack-protection (~> 1.5)
```
and small redis update.

**Comment by mperham** [comment]
So the asset request is returning 200 OK and 0 bytes because it hasn't authenticated?  If you disable the Warden authentication, does everything work?

**Comment by benoittgt** [comment]
The issue was https://github.com/mperham/sidekiq/issues/3169

To reproduce the behavior. Login to your production sidekiq, then copy cookie.
```sh
$ bundle exec puma -C config/puma.rb &
$ curl --cookie "_app_session_id=08****bcf6b8;remember_admin_user_key=W*****Xldc3aec3cf392" http://0.0.0.0:25615/admin/sidekiq/stylsheets/application.css

Started GET "/admin/sidekiq/stylsheets/application.css" for 127.0.0.1 at 2016-10-07 07:13:38 +0000

RuntimeError (can't modify frozen Hash):
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:20:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
```

**Comment by benoittgt** [comment]
We still the have the issue even with sidekiq at 9abf52f. I will reopen the issue because it seems more related to a server issue. I will keep the this ticket to date for people how have the same problem.

It happens only in production environnement as before.

The configurations are the same between production and other environnements. I still have H18 from Heroku and curl fail: 

```
curl -v -H 'Cache-Control: no-cache' --cookie "***" http://0.0.0.0:16289/admin/sidekiq/javascripts/dashboard.js
* Hostname was NOT found in DNS cache
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (127.0.0.1) port 16289 (#0)
> GET /admin/sidekiq/javascripts/dashboard.js HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 0.0.0.0:16289
> Accept: */*
> Cookie: ****
> Cache-Control: no-cache
>
Dalli/SASL authenticating as memcached-app
Dalli/SASL: Authenticated
Started GET "/admin/sidekiq/javascripts/dashboard.js" for 127.0.0.1 at 2016-10-10 14:56:49 +0000
cache: [GET /admin/sidekiq/javascripts/dashboard.js] miss, store
< HTTP/1.1 200 OK
< Last-Modified: Mon, 10 Oct 2016 14:14:22 GMT
< Content-Type: application/javascript
< Cache-Control: public, max-age=86400
< X-Request-Id: f0cf146e-8dr9-4cdf-9cfe-cbf3daa4b299
< X-Runtime: 0.333989
< Date: Mon, 10 Oct 2016 14:56:49 GMT
< X-Content-Digest: d4r90df4ed9545bw8c1edff3drf8a9ewddr52
< Age: 0
< X-Rack-Cache: miss, store
< Vary: Accept-Encoding, Origin
< Content-Length: 231197
<
* transfer closed with 231197 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 231197 bytes remaining to read
```

**Comment by mperham** [comment]
Can you narrow this down with a trivial Rails app that reproduces the behavior?

**Comment by benoittgt** [comment]
Thanks for your help. I build a new app from scratch with quite similar gems and config as our app but was not able to reproduce the issue locally in production ENV and on Heroku. Things that are different are maybe caching because I didn't plug addons we use for our app on Heroku. 

I don't want to take too much of your time for this issue how seems related to our server configuration and other tools and gem we use. Will keep digging.

Thanks @mperham  🎉

**Comment by martinstreicher** [comment]
@benoittgt Did you ever resolve this?

**Comment by benoittgt** [comment]
@martinstreicher For the moment we are still with:
```ruby
gem 'sidekiq', '~> 4.1.4'
source 'https://...@gems.contribsys.com/' do
  gem 'sidekiq-pro', '~> 3.3.2'
end
```

We should upgrade soon

**Comment by benoittgt** [comment]
We jumped to `sidekiq (5.0.5)` and `sidekiq-pro (3.5.3)` and we still have the issue. No 404, the CSS and the JS file are just empty with the error : `net::ERR_INCOMPLETE_CHUNKED_ENCODING`.

Chrome
<img width="1181" alt="capture d ecran 2017-10-04 a 10 51 41" src="https://user-images.githubusercontent.com/8417720/31167456-6a2cebe4-a8f2-11e7-934a-572c0f054cbb.png">

Firefox
![capture d ecran 2017-10-04 a 10 51 34](https://user-images.githubusercontent.com/8417720/31167463-6d20d252-a8f2-11e7-86f8-61b58538becd.png)

@martinstreicher  Do you think you can share your gemfile ? We have the issue only in production
We use this
```
group :production do
  gem 'rails_12factor'
  gem 'heroku-deflater'
  gem 'rails_serve_static_assets'
  gem 'sqreen'
end
```

We use a staging heroku dyno that have the same config/environments as production and we don't have the issue.

**Comment by benoittgt** [comment]
Ok good news. Without the gem heroku-deflater it works.

**Comment by jaxn** [comment]
Having the exact same symptoms, but not using the `heroku-deflater` gem.

**Comment by benoittgt** [comment]
@jaxn are you using `rails_serve_static_assets`?
