### ISSUE TITLE
Sidekiq::Web + Wildcard domains regression

### ISSUE THREAD

**Issue by inkstak** [mperham/sidekiq#3180]
Upgrading from Sidekiq 4.1 to Sidekiq 4.2 induce regression of #2730 

To refresh your memory - We're using wildard domains in Rails
```Dummy::Application.config.session_store :cookie_store, domain: :all```

after authentication (with Devise), Sidekiq::Web create two cookies:
* _foo @ .localhost.dev
* _foo @ jobs.localhost.dev

Since Sinatra dependency has been removed, the suggested fix in #2730 doesn't work.

I've also suggested a fix in https://github.com/mperham/sidekiq/issues/2555#issuecomment-149594650 which doesn't work too.

@mperham you tried to broach the subject in #3147, but the issue is already closed.

So what's the proper solution today to use authentication ?
I'm still trying to fix it on my side, but advices are welcome :)

**Comment by inkstak** [comment]
I've digged into my problem and have few ideas.

In my case, I use Devise to authenticate :
```
Jobs::Engine.routes.draw do
  authenticate :user, lambda { |u| u.super_hero? } do
    mount Sidekiq::Web, at: '/'
  end
end
```

Devise relies on Warden to authenticate and use the session provided by Rails.
It doesn't care about the session initiated by Sidekiq::Web in [lib/sidekiq/web.rb#L116](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L116).
This second session becomes useless, unless it causes problems by creating a second cookie.

To fix this, I monkeypatched the `build` method and removed references to `Rack::Protection` and `Rack::Session::Cookie`. It works like a charm.

I'm preparing a pull request to disable sessions like Sinatra.

**Comment by mperham** [comment]
I suspected that adding our own session always wouldn't work sometimes but it's hard to auto-detect this case.  Looking forward to your PR.

**Comment by mperham** [comment]
I'll fix this on Monday if you haven't sent a PR by then.  It's blocking a 4.2.3 release.

**Comment by badosu** [comment]
@inkstak Fixed?
