### ISSUE TITLE
Feature Request - create a job on sidekiq without a dedicated worker

### ISSUE THREAD

**Issue by dbenjamin57** [mperham/sidekiq#3181]
Hi there, I was wondering why isnt there an option to schedule a job on sidekiq without creating a worker for it. 

Lets say I have a class X with 2 methods: a and b. And let's say method a is the runner method for b. So a executes method b 100 times. 

So in this case instead of just writing the following:
```
class X  
 def a
  100.times(perform_async_method(b))
 end

 def b
  #do something
 end
end
```

I need to write something like this

```
class X  
 def a
  100.times(BWorker.perform_async)
 end

 def b
  #do something
 end
end

class BWorker
 def perform
   X.b
 end
end
```

Was wondering if you have a way to resolve this or a solution?

**Comment by mperham** [comment]
`perform_async_method` has an implicit instance receiver, which would need to be marshalled.

The first 15 minutes of this talk explain how I designed Sidekiq's API and explain why it looks a little odd for a Ruby API, tl;dr it minimizes state which requires marshalling over the network:

http://confreaks.tv/videos/rubyconf2012-asynchronous-processing-for-fun-and-profit
