### ISSUE TITLE
TTIN signal is not producing a stack trace

### ISSUE THREAD

**Issue by j-mcnally** [mperham/sidekiq#3184]
Ruby version: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux-gnu]
Sidekiq / Pro / Enterprise version(s): 4.2.2

If relevant, please include your initializer and any error message with the full backtrace.
Have 4 of 10 working for the last 15 hours. 

Found the PID of the sidekiq process (i think)

```
root@e42b019c31d1:/var/app# kill -TTIN 106
root@e42b019c31d1:/var/app#
```

Produces nothing in the terminal or the log.

```
app        106  1.3  4.0 2831524 588552 ?      Sl   Oct08  12:42 sidekiq 4.2.2 app [4 of 10 busy]
```

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes

**Comment by j-mcnally** [comment]
The process is still processing jobs. Just 4 slots are stuck? And the process isnt doing anything when it is sent TTIN as advised in the link you sent. So im not sure what you want me to do because you just sent me a link ive already read.

**Comment by j-mcnally** [comment]
Gonna try GDB

**Comment by mperham** [comment]
If the process is still processing jobs but TTIN isn't working, that means you aren't looking in the right place for the log output.  The link was to point out that if TTIN isn't working, you need to use GDB.
