### ISSUE TITLE
NameError: uninitialized constant Sidekiq::Sinatra

### ISSUE THREAD

**Issue by JohnMerlino2** [mperham/sidekiq#3186]
I have a project using sidekiq. The gem is included in Gemfile and I ran bundle install and confirm the gem was installed. I want the monitoring panel. So I add the following to routes.rb:

      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'

But then when I try to run a rake task or anything that loads the Rails app, I get the following:

    NameError: uninitialized constant Sidekiq::Sinatra

Why this error? I am using Rails not Sinatra.

**Comment by mperham** [comment]
We need the full backtrace.

**Comment by JohnMerlino2** [comment]
$ bundle exec rake db:migrate
rake aborted!
NameError: uninitialized constant Sidekiq::Sinatra
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/sidekiq-4.1.4/lib/sidekiq/web.rb:12:in `<module:Sidekiq>'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/sidekiq-4.1.4/lib/sidekiq/web.rb:11:in `<top (required)>'
/home/viggy/Documents/github/core/config/routes.rb:225:in `block in <top (required)>'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:337:in `instance_exec'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:337:in `eval_block'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/actionpack-4.1.5/lib/action_dispatch/routing/route_set.rb:315:in `draw'
/home/viggy/Documents/github/core/config/routes.rb:1:in `<top (required)>'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:40:in `each'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/activesupport-4.1.5/lib/active_support/file_update_checker.rb:75:in `call'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/activesupport-4.1.5/lib/active_support/file_update_checker.rb:75:in `execute'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application/finisher.rb:71:in `block in <module:Finisher>'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `instance_exec'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `run'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application.rb:300:in `initialize!'
/home/viggy/Documents/github/core/config/environment.rb:5:in `<top (required)>'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application.rb:276:in `require_environment!'
/home/viggy/.rvm/gems/ruby-2.1.2@core/gems/railties-4.1.5/lib/rails/application.rb:379:in `block in run_tasks_blocks'
/home/viggy/.rvm/gems/ruby-2.1.2@core/bin/ruby_executable_hooks:15:in `eval'
/home/viggy/.rvm/gems/ruby-2.1.2@core/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by mperham** [comment]
Add Sinatra to your gemfile.

**Comment by mperham** [comment]
Since I was on my phone, my response was brusque.

You are using an old version of Sidekiq, the wiki only covers the current version, thus your problem.  If you wish to use the web ui for Sidekiq <4.2.0, you need to add this to your Gemfile:

```ruby
gem 'sinatra', require: nil
```
