### ISSUE TITLE
problem reading locale 

### ISSUE THREAD

**Issue by ctammes** [mperham/sidekiq#3189]
Versions:
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
Rails 4.2.7.1
Sidekiq 4.1.4 (gem)

In my model I have this code (line 3):

`OBJECT_TYPES= I18n.translate(:object_type, scope: 'nl.simple_form.options.management_report_column').keys`

When I run the application, no error is generated and the constant is filled as expected. 

But when I start Sidekiq on the server, like this:
`bundle exec sidekiq -d -P tmp/sidekiq.pid -L log/sidekiq.log`

I get this error in the log and Sidekiq stops:
`undefined method 'keys' for #<String:0x007fbb035da488>
/usr/src/app/app/models/management_report_column.rb:3:in '<class:ManagementReportColumn>'
`

Any suggestions?

Chris

**Comment by jeffrey008** [comment]
I think this is not a problem related to sidekiq.

The error message said there is no method `keys` in `String` class. Which is true.

Probably  `I18n.translate(:object_type, scope: 'nl.simple_form.options.management_report_column')` will return a string, not a hash or array.

Please tell us more if the problem is still going

**Comment by ctammes** [comment]
@jeffrey008 It returns an array, not a string, and it doesn't give this error when the model is used in the application, only when used by Sidekiq.

In the application, the information is used to show a list of items in a view.

I read something about a timing problem? Sidekiq being too fast or I18n too slow? I tried other suggestions, but nothing worked, yet.

**Comment by mperham** [comment]
Sidekiq does nothing with locales.  You likely have some app code or a gem which is monkeypatching the locale APIs.
