### ISSUE TITLE
How to do one job at any time?

### ISSUE THREAD

**Issue by jeffrey008** [mperham/sidekiq#3190]
Ruby version: 2.3.0
Sidekiq version: 4.2.0

Hello guys, I am new to sidekiq. I want to know more about this gem. 

Suppose I have a` MyWorker` class and this class is gonna perform a job. This job can take 10 seconds to 10 minutes to finish, depending on the job's complexity. Also, this job takes up a lot of CPU and memory, so I want at most 1 job working at any time. 

So in my `sidekiq.yml`, I added this setting:
`:concurrency: 1`
Now my worker only performs 1 job at any moment, but when a new job comes, it does not store into the queue. Then after my current job is finished, the new job is not processed.

Is my setting wrong? How could I make sidekiq satisfy my use-case? Thank you.

**Comment by mperham** [comment]
Concurrency: 1 is the correct way to limit Sidekiq to serial execution.  I don't know what this means:

> Now my worker only performs 1 job at any moment, but when a new job comes, it does not store into the queue. Then after my current job is finished, the new job is not processed.

Jobs created with perform_async should go into a queue in Redis.  The most common reason why a job does not go to Redis is if you have `sidekiq/testing` required or are activating `rspec-sidekiq`.
