### ISSUE TITLE
Queues being renamed in production (ActiveJob, Sidekiq, ElasticBeanstalk, Whenever)

### ISSUE THREAD

**Issue by rudf0rd** [mperham/sidekiq#3191]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.2

Hey guys,

My queue is being renamed from `api_updater` to `<app_name>_<environment>_api_updater` in staging/production.  So I'm trying to trace down exactly where this is occurring.  I am calling the job from a rake task like:

rake task -> job queues -> failed naming

Testing this out in dev, no prepending to the queue name, but if I added in a `RAILS_ENV` other than development, it changes it.

This would be all well and good, but when starting up sidekiq with `RAILS_ENV` it uses the normal queue names instead of the prepended ones.

Anyone run into this before or is there a config I'm missing?

**Comment by rudf0rd** [comment]
BTW, my current fix is to add a queue block in my `sidekiq.yml` that matches the prepended queue names.

**Comment by shaneog** [comment]
You should check your code for anywhere that's setting the ActiveJob queue name prefix:
`queue_name_prefix`

**Comment by mperham** [comment]
I don't see how this could possibly be a sidekiq issue - sidekiq never touches the queue name, just uses what you tell it to use.  There must be another layer of logic or app code which is mucking with the queue names.
