### ISSUE TITLE
Sidekiq does not see changes in database table

### ISSUE THREAD

**Issue by ctammes** [mperham/sidekiq#3192]
Versions:
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
Rails 4.2.7.1
Sidekiq 4.1.4 (gem)

In my application I can add report columns and these columns are added to a database table that is used to supply data to these reports. I use ActiveRecord::Migration add_column to add the column. After adding I issue a reset_column_information for the table.

The column is indeed added, but when I run the Sidekiq job, it complains about this new column missing:
` ActiveRecord::UnknownAttributeError: unknown attribute 'aantal huisartsen' for Client
ReportColumn`

In the job, the first instruction is also reset_column_information. Restarting Sidekiq doesn't help.

This doesn't happen in development, only in production.

Any suggestions?

**Comment by mperham** [comment]
Sidekiq does not use ActiveRecord.  As it is 99% likely this is an application issue, please ask your question on StackOverflow.
