### ISSUE TITLE
Sidekiq pro dependency

### ISSUE THREAD

**Issue by benoittgt** [mperham/sidekiq#3194]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.2 / 3.3.3

Hello

I'm wondering if `sidekiq pro` dependency requirement should be change to `sidekiq 4.2.0`. 
```
    sidekiq-pro (3.3.3)
      sidekiq (>= 4.0.0)
```
Does https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#333 mean that if we are using `sidekiq-pro 3.3.3` we need at least `sidekiq 4.2.0` ? 

Thanks 
Benoit

**Comment by mperham** [comment]
Nope, the code is backwards and forwards compatible.

**Comment by benoittgt** [comment]
Thanks @mperham
