### ISSUE TITLE
[Pro] About super_fetch

### ISSUE THREAD

**Issue by inkstak** [mperham/sidekiq#3196]
Hi, I'm playing with `super_fetch!` and seeing strange behavior.

I have a sidekiq process (A) running with 1 concurrency.
While a job is running, I brutally killed the process (A) and start immediately a new one (B).

The first process (A) is still present for few minutes in busy UI.
On starting, the new process (B) don't see the job in private queue.

The job in private queue won't be called from deads, until I'm waiting for the first process (A) to disappeared from UI and starting a new one (C).

The new one (C) will recover the dead job on startup.
But the second process (B) will never try to recover them.

Is it an expected behavior ?

Gems used:
* sidekiq (github master - 4.2.3)
* sidekiq-pro (3.4.0)

**Comment by mperham** [comment]
Yes, that's exactly as designed.

**Comment by inkstak** [comment]
So, it requires to respect an "unload time" after a process is killed and before an other one is started.

How is it defined "unload time" ?
Why the second process (B) doesn't try to fetch the dead jobs, even after being started ?

My cloud platform brutally kill all processes after the new ones are ready, so my dead jobs stay dead until the next deployment.

**Comment by mperham** [comment]
The process heartbeat must expire before jobs will be recovered. I believe it is one minute.

The deploy wiki page talks about it but the USR1 signal is strongly recommended when starting a deploy to minimize rerunning jobs.

**Comment by inkstak** [comment]
I'm discussing with my cloud provider (CleverCloud) to handle signals and improve sidekiq support on deployments.

But may I ask you why the new processes try to recover dead jobs only on startup and never later ?

**Comment by mperham** [comment]
Because the most common reason for jobs to be orphaned is due to unexpected process death; it's assumed that processes will be restarting often.

Even without USR1, Sidekiq will push back unfinished jobs upon TERM.  If by "brutally kill" you mean they send the KILL signal with no forewarning, that's not a supported means of shutdown because it doesn't allow any shutdown at all.  Heroku for instance sends TERM and then 10 seconds later sends KILL.  That's an expected and supported pattern.

**Comment by inkstak** [comment]
The problem is actually about KILL. My provider doesn't send any signals before the KILL, no matter it restarts after a push, a maintenance or a crash.
That's why I've put great hopes in the reliability feature, in particular in `superfetch`.
It catches dead jobs, but dont recover them on time in my case.

I'll try to find a workaround to extract them from the private queue, maybe by playing with SuperFetch class.
If you have tips to do it safely, I'll take them.

Unless you're open to provide new features around reliability, you can close the issue.
Thanks for your support.

**Comment by mperham** [comment]
The "pause" that super_fetch has allows it to handle "poison pill" jobs somewhat gracefully.  If another process recovered those jobs immediately, it would immediately die upon executing the poison pill too.

What you can do is have your initializer kick off a custom worker that executes the super_fetch job recovery routine 1 minute after startup:

```ruby
DeployCleanupWorker.perform_in(1.minute)

class DeployCleanupWorker
  include Sidekiq::Worker
  def perform
    Sidekiq::Pro::SuperFetch.instance.cleanup_the_dead
  end
end
```

**Comment by wafendy** [comment]
Rails example:

```ruby
# app/workers/deploy_cleanup_worker.rb

class DeployCleanupWorker
  include Sidekiq::Worker
  def perform
    Sidekiq::Pro::SuperFetch::Retriever.instance.cleanup_the_dead
  end
end
```
```ruby
# config/initializers/sidekiq.rb

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('REDIS_URL') }

  config.super_fetch!

  config.reliable_scheduler!
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch('REDIS_URL') }
end

DeployCleanupWorker.perform_in(1.minute)

```

**Comment by danmayer** [comment]
NameError (uninitialized constant Sidekiq::Pro::SuperFetch)

**Comment by edavis10** [comment]
This DeployCleanWorker has been working well to catch orphaned and dead jobs.

But upgrading from Sidekiq 5.2.7 to 6.1.2 (Pro from 4.0.4 to 5.2.0) it's now not possible to call `#cleanup_the_dead`.

I wanted to post here so people finding this know the cleanup job is no longer a solution.

I no-op'd the job and have let the app run for about 48 hours in production and am now seeing jobs getting stuck in the private queues in Heroku again. Restarting the processes (or letting Heroku restart them) will recover them but that requires watching for them manually or accepting upto a 24 hour delay before they get recovered and the job can complete. Which can be a problem when it's a batch job that's holding up other jobs.

As the bulk of the stuck jobs are doing network I/O I'll be looking into ways to reduce the stuck-ness there, but it sucks that this safety net no longer works in the latest version and there's no way to reproduce it short of copying out a bulk of super fetch's code into the app code.

**Comment by mperham** [comment]
@edavis10 The API has changed slightly, yes. It is not a public API and undocumented so you are responsible for keeping up with internal changes which might break your use.

**Comment by edavis10** [comment]
@mperham Yeah I understand, I just wanted to make it clear to others that this solution no longer works in the current version.

**Comment by inkstak** [comment]
Here is the last version of my cleanup Worker with Sidekiq (6.1.2) & Pro (5.2.0)

```ruby
class DeployCleanupWorker
  include Sidekiq::Worker

  def perform
    Sidekiq.options[:fetch].cleanup_the_dead
    Sidekiq.options[:fetch].check_for_orphans
  end
end
```

**Comment by inkstak** [comment]
Hi @mperham, since we upgraded to Sidekiq-Pro 7.x, the hack above is not working anymore.
CleanupDeadJob
I finally get this new version working (but didn't test against actual orphan jobs)


```ruby
class CleanupDeadJob
  include Sidekiq::Job
  sidekiq_options queue: "critical"

  def perform
    Sidekiq.default_configuration.default_capsule.fetcher.cleanup_the_dead
    Sidekiq.default_configuration.default_capsule.fetcher.check_for_orphans
  end
end
```

**Comment by inkstak** [comment]
Since years, we have to deal with this private API.
Would you consider any built-in strategy to allow us to clean dead jobs with a delay after a bootup ?

**Comment by mperham** [comment]
As of 5.5.2, every Sidekiq Pro process will recover orphans upon startup **if no one else has run the recovery process within the last minute**. That's quite aggressive; I don't see any need for you to clean up manually. Please remove your code and let the system clean up when it wants to.

**Comment by edgurgel** [comment]
The problem I remember seeing was:

* 3 instances running v1
* SIGTERM is sent to v1
* 3 instances start with v2 code (recovering orphan jobs)
* instances with v1 take some time to finish

Orphan jobs are left unrecovered until a new version is pushed or a new instance starts/restarts

Another case was:

* Operator decreases the amount of instances running Sidekiq from 3 to 2
* Instance did not stop gracefully so jobs are orphaned

Until a new instance starts up or restarts these jobs are going to be forgotten.

Because of these cases we ended up running the code to recover orphans every 2 minutes regardless of what happened with the cluster.

**Comment by mperham** [comment]
Seen from another angle, that's not a good idea. Poison pill jobs will kill any process that runs them. If you have a poison pill, you don't want to recover it quickly. Two minutes later it'll kill another process.

1. Do you know which code is creating poison pills? How many jobs do you recover daily?
2. What makes those jobs so time-sensitive?

**Comment by inkstak** [comment]
Our issue is

> As of 5.5.2, every Sidekiq Pro process will recover orphans upon startup **if no one else has run the recovery process within the last minute**. That's quite aggressive; I don't see any need for you to clean up manually. Please remove your code and let the system clean up when it wants to.

Out issue is still the same :
in the case of a new deployement, the new version is started before the older one is killed, so dead jobs are never recovered by the system at startup.
Our provider doesn't send any signals before the KILL, no matter it restarts after a push, a maintenance or a crash.

Also,

**Comment by mperham** [comment]
What provider are you using? It is strange that they don't implement signals to shutdown properly.

**Comment by inkstak** [comment]
[Clever Cloud](https://www.clever-cloud.com), a french provider.

**Comment by mperham** [comment]
I’m not going to support that. Sidekiq requires some amount of time to shut down. Killing it without notice is not supported and you should open a ticket with Clever Cloud: they need to send the TERM signal and wait 30 seconds before sending KILL. That’s standard practice at every PaaS afaik.
