### ISSUE TITLE
Is sleep() thread safe?

### ISSUE THREAD

**Issue by dsshap** [mperham/sidekiq#3199]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq

@mperham Is using `sleep()` okay to use with sidekiq? Or is there something better you would recommend?

My situation is that I send out a number of http requests sequentially from a worker and need to account for some network latency (us-east1 -> china). In order to ensure that requests come in a specific order and have time to complete (a response from http request does not symbol complete, in my case).

So I tested by putting `sleep(0.2)` in between some of the commands and that took care of the issue.

But before I roll with this solution, I want to ensure this is the appropriate mechanism within the sidekiq env.

Thank you!

**Comment by mperham** [comment]
Yep, it's perfectly fine to use albeit expensive.  Ruby will context switch to other threads while the sleep is happening.  You're tying up an entire thread doing nothing during that time so it's a hit to the overall efficiency.  Typically you'd want to multiplex many web calls onto one thread via a reactor-based system: eventmachine, node.js, etc.

**Comment by Adamantish** [comment]
I was thinking of using one infinite sidekiq job as a poor man's throttled event loop. i.e. it's the closest thing I have already set up to async call other jobs every 2 seconds after checking for new updates. It costs the memory of a thread but I'm right in thinking it won't cost much CPU time? What better option would you suggest to someone who wants it merged to master in an hour?

**Comment by mperham** [comment]
@Adamantish Side note: please don't hijack old issues for your questions.

I don't advise on architectural issues since I know nothing about the system you are building but, in general, cobbling together a "poor man's" anything is dubious.

**Comment by Adamantish** [comment]
Ok, thanks. Will avoid in future.

**Comment by Adamantish** [comment]
And yes, the dubious feeling is why I asked. Will see how it runs and with the assumption it will need replacing when we're not under deadline frenzy like now.
