### ISSUE TITLE
Sidekiq not eager loading in Rails 5

### ISSUE THREAD

**Issue by evendir** [mperham/sidekiq#3203]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.3

Spent a while trying to track down what was causing a very easy to replicate deadlock with sidekiq, eventually realized it was due to the autoloader, which then led me to realize that sidekiq isn't eager loading for Rails 5.  (given that the check is for <4 or 4)

**Comment by pitops** [comment]
I am not sure if its the same issue, but with sidekiq 4.2.3 it stopped delivering emails said it could not find the class/module (argumentError). Reverted back to 4.1.4 and it works as expected.

**Comment by mperham** [comment]
Rails doesn't eager load in production by default?  Can you post your config/environments/production.rb?

**Comment by mperham** [comment]
Fixed on master, could you verify?
