### ISSUE TITLE
Moving from one redis server to another

### ISSUE THREAD

**Issue by dorongutman** [mperham/sidekiq#3204]
How do I migrate all the jobs from one redis server to another with zero downtime ? 

I'm moving our sidekiq from one redis server to another, and since we always have scheduled jobs and jobs there get enqueued at any second, I want to move it gradually by making the workers listen on 2 different redis servers.
Then, I'll only enqueue new jobs to the new redis server, and wait until all jobs from the older redis server are gone.

Is this feasible and/or how can it be done ? 

I'm using sidekiq enterprise if that's relevant.

**Comment by mperham** [comment]
It's beyond the scope of support for me to lay out a step-by-step process of migration, but yes, this can be done.  You can have two Redis servers running in parallel, old and new.  Assign Sidekiq processes to each server and target all new jobs to the new server.  This can be hard if you are using batches or more complex job workflows (e.g. if the old jobs create new jobs).  It can take up to a few weeks for retries to succeed or die and you'll lose your historical stats.

This isn't a common need but would make for a cool wiki page if someone wanted to collect the set of steps they followed to migrate.
