### ISSUE TITLE
Standalone monitoring docs should be updated

### ISSUE THREAD

**Issue by spizm** [mperham/sidekiq#3206]
Sidekiq / Pro / Enterprise version(s): Pro 3.4.0 / 4.2.3

I noticed my sidekiq monitoring rake task broke with a recent update. It seems to be written as a rack app now? Running `Rack::Server.start app: Sidekiq::Web` launches it, so the docs here probably should be updated:

https://github.com/mperham/sidekiq/wiki/Monitoring#standalone

**Comment by mperham** [comment]
The wiki is publicly editable.  Update as you see fit.
