### ISSUE TITLE
'.drain' in enterprise doesn't decrypt encrypted worker

### ISSUE THREAD

**Issue by rufusroflpunch** [mperham/sidekiq#3208]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 4.2.3 / 3.4.0 / 1.3.2

I have noticed that using '.drain' on a worker in tests doesn't decrypt the secret bag on encrypted workers. However, executing the job directly in the test '.perform' does decrypt the secret bag.

**Comment by mperham** [comment]
Tests do run client-side middleware but don't run through server-side middleware.  You won't be able to use `drain` with jobs that require server-side middleware features.  I have no plans to fix this but I'll keep this open and consider what I could do.

**Comment by mperham** [comment]
If this is a problem for you, I'd suggest this tweak to disable encryption when testing:

```ruby
Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  # keys...
end unless Rails.env.test?
```
