### ISSUE TITLE
Sidekiq behaves strangely after update and even after downgrade

### ISSUE THREAD

**Issue by pitops** [mperham/sidekiq#3209]
Ruby version:2.3.1
Sidekiq / Pro / Enterprise version(s): just normal free one

this is the server log
```
ActionController::RoutingError (No route matches [GET] "/sidekiq/images/status.png"):

actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendered collection of /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb [80 times] (22.2ms)
  Rendered /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.6ms)
  Rendering /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /Users/pitops/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (112.8ms)
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:03 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:05 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:07 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:09 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:11 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:13 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:15 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:17 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:19 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:21 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:23 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:25 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:27 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:29 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:31 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:34 +0300
Started GET "/sidekiq/retries" for ::1 at 2016-10-27 19:14:35 +0300
```

As you can see above when i am on sidekiq/retries page, before it wouldn't make GET requests all the time like that. Would only happen once. Also on top you can see that it can't find sidekiq/images/status.png which i am not sure if its a problem with my setup locally or if its problem when i upgraded to v4.2.3 then back to 4.1.4 and then back to 4.1.1. Seems all versions exhibit same issue.

In addition, there is a flash message in dashboard page which does not even exist on that page and it won't leave even after refreshes. I found if i close the localhost:3000/sidekiq/retries page then that message disappears as well.

Also tried updating a model through a form and sometimes the saving happens and sometimes it does not. I do not know if all these are correlated but its very strange behavior.

any clues?

**Comment by mperham** [comment]
You hit the "Live Poll" button, that's why it makes a request every two seconds to refresh the page.

**Comment by seanwmitchell** [comment]
I actually am getting this error too. More specifically the missing image file only.

It happens when I first go to the status page but not when the live poll refreshes. It happens in both production and development. I have uninstalled the gem and reinstalled it. I also updated from Ruby 3.1.2 to 3.2.0 (which starts a new set of bundled gems) and the issue continues.

Ruby 3.2.0
Rails 7.0.4.2

sidekiq (6.5.8)
      connection_pool (>= 2.2.5, < 3)
      rack (~> 2.0)
      redis (>= 4.5.0, < 5)
    sidekiq-congestion (0.1.1)
      congestion (~> 0.1)
      sidekiq (>= 3.0)

Started GET "/sidekiq/stats" for ::1 at 2023-02-13 08:30:31 +1300
08:30:32 web.1     |   ActiveRecord::SchemaMigration Pluck (0.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
08:30:32 web.1     |   ↳ config/initializers/handle_bad_encoding_middleware.rb:14:in `call'
08:30:36 web.1     | Started GET "/sidekiq/stats" for ::1 at 2023-02-13 08:30:36 +1300
08:30:41 web.1     | Started GET "/sidekiq/stats" for ::1 at 2023-02-13 08:30:41 +1300
08:30:45 web.1     | Started GET "/sidekiq" for ::1 at 2023-02-13 08:30:45 +1300
08:30:45 web.1     | Started GET "/sidekiq/images/status.png" for ::1 at 2023-02-13 08:30:45 +1300
08:30:45 web.1     |   
08:30:45 web.1     | ActionController::RoutingError (No route matches [GET] "/sidekiq/images/status.png"):
08:30:45 web.1     |   
08:30:45 web.1     | config/initializers/handle_bad_encoding_middleware.rb:14:in `call'
08:30:50 web.1     | Started GET "/sidekiq/stats" for ::1 at 2023-02-13 08:30:50 +1300
08:30:55 web.1     | Started GET "/sidekiq/stats" for ::1 at 2023-02-13 08:30:55 +1300

Any clues?

**Comment by abatko** [comment]
I am seeing this too. Any recommended solutions? 🙏 

`sidekiq (6.5.8)`

```
ActionController::RoutingError (No route matches [GET] "/images/status.png")
```

**Comment by mperham** [comment]
It seems like maybe the app does not have Rack::Static working, is your app disabling it somehow?

https://github.com/sidekiq/sidekiq/blob/0175cdbe03c3a9edf908a155ae6f006061b5c224/lib/sidekiq/web.rb#L143

**Comment by abatko** [comment]
At the console:
```
irb(main):001:0> Rack::Static
=> Rack::Static
```

And my `RAILS_SERVE_STATIC_FILES` is set to `enabled`, thus this line resolves to true:

https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L27

Also, I can pick a file from my app's `public` directory, e.g. `favicon-32x32.png` and request it with my web browser (e.g. `www.mywebsite.com/favicon-32x32.png`) - and see it successfully.


What else should I check?

**Comment by mperham** [comment]
Can you get fetch Sidekiq-specific static assets?

```
/images/logo.png
/images/status.png
/images/favicon.ico
/stylesheets/application.css
```

**Comment by abatko** [comment]
Yes, I can fetch them all.

**Comment by mperham** [comment]
If you can fetch them manually I'm not sure why it wouldn't work in your browser. 🤷‍♂️

**Comment by mperham** [comment]
Can you give me a sample app which reproduces the bug?
