### ISSUE TITLE
Wrong documentation in wiki?

### ISSUE THREAD

**Issue by fabn** [mperham/sidekiq#3210]
This is not a real issue with sidekiq it's a request about this sentence in [API documentation](https://github.com/mperham/sidekiq/wiki/API)

> The Web UI uses the API exclusively - anything you can do in the UI can be scripted with the API.

Is this sentence still true? I'm trying to retrieve last _n_ jobs from Sidekiq::ScheduledSet.new and I'm not able to do that without iterating the whole queue.

When I look at web UI source code I see that [pagination is implemented using redis raw calls](https://github.com/mperham/sidekiq/blob/2c9f7662fcdcb52d59b72ba0fe7dc5f963de4904/lib/sidekiq/paginator.rb) and not with api methods.

Full background for my issue is [here](http://stackoverflow.com/questions/40312181/getting-last-n-jobs-from-a-queue-using-sidekiq-api) if relevant.

Thanks.

**Comment by mperham** [comment]
You are correct that there is no public API for paginated access to the sets.  I'd be happy to get a PR to fix this.
