### ISSUE TITLE
Is concurrency > 50 stable?

### ISSUE THREAD

**Issue by nitzanav** [mperham/sidekiq#3211]
I am referring to this quote
> Don't set the concurrency higher than 50. I've seen stability issues with concurrency of 100, for example

written here - https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency

Is it still relevant? 

The memory consumption of one of my sidekiq worker server is low enough (only sidekiq, now rails, and almost no gems) to enable 300 threads to reach 400MB in the highest load. It is currently 80 and I didn't see any stability issues.

What number of threads do you recommend? will 300 be stable?

**Comment by mperham** [comment]
My advice is often in the general case.  If you test it and it works for your specific use case, bump it up to whatever works.

**Comment by mperham** [comment]
If you can give me feedback about what worked for you, that's good data for me to have. 👍

**Comment by nitzanav** [comment]
For sure that I will give the feedback,
but how will I know there are no issues.

Are those issues  hard to spot? What kind of issues are they? termination of worker? Worker/thread not accepting jobs? or jobs being terminated in the middle of execution without the ability to track that it happen?

As long as it will not remove any uncompleted job from the queue, I can take the risk.

**Comment by mperham** [comment]
I'm not sure how it will manifest.  Test your system at load and see what happens.

Sidekiq normally pulls uncompleted jobs from the queue.  You have to use Sidekiq Pro's reliability feature to keep jobs in Redis while processing.

**Comment by nitzanav** [comment]
It seems that I will never know if something wrong happened, I will ask out in stackoverflow to see if anyone else encounter stability issues in high concurrency and what were the issues.

**Comment by nitzanav** [comment]
Update:

I increased concurrency from 80 to 160, the maximum memory is only 150MB in the 24h period. But I did get this error 'can't create Thread: Resource temporarily unavailable' you mentioned here to be github.com/mperham/sidekiq/issues/286 to be caused due a thread leak that should be monitored with this github.com/mperham/sidekiq/wiki/Signals#ttin. I will monitor it and update.

**Comment by nitzanav** [comment]
Here are 3 examples of output of ttin:
Please note:

1. The number at beginning of line is the number of traces
2. Only the first output was close to a time where the error occurs
3. I produced the the output using this command line: `(heroku logs -t -r sidekiq | grep "app/" > raw.txt) && (cat raw.txt | grep "3 TID" | cut -d ' ' -f 2-1000 | sort | uniq -c | sort -r > aggregation.txt)`

180 threads, when I had the issue few minutes before the output:
```
  58 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:187:in `lock'
   3 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
   3 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
   1 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:95:in `join'
   1 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
   1 app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:82:in `select'
```

100 threads, when I had no issue :
```
  81 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
  11 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
   6 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:187:in `lock'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:934:in `wait_readable'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/launcher.rb:144:in `sleep'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/cli.rb:147:in `backtrace'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:82:in `select'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:86:in `sleep'
   1 app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `sleep'
```

80 threads, when I had no issue :
```
  42 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:187:in `lock'
  13 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:95:in `join'
  12 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
   4 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
   3 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
   3 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:82:in `select'
   2 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
   1 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:934:in `wait_readable'
   1 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/launcher.rb:144:in `sleep'
   1 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/cli.rb:147:in `backtrace'
   1 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:86:in `sleep'
   1 app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `sleep'
```

**Comment by nitzanav** [comment]
@mperham I will be extremely happy for input from you:)?

**Comment by mperham** [comment]
Input about what?

**Comment by nitzanav** [comment]
The ttin sees mainly those lines in the backtrace, does any of those seems to be a thread leak as you described https://github.com/mperham/sidekiq/issues/286 or is it another issue?

```
app[worker.1]: 3 TID-ow5z46exw WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:187:in `lock'
```

```
app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
```

```
app[worker.1]: 3 TID-os9ulw8ps WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:95:in `join'
```

```
app[worker.1]: 3 TID-osjnd6zac WARN: /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
```

**Comment by mperham** [comment]
Looks fine to me.

**Comment by nitzanav** [comment]
OK, no luck in spotting the root cause.

just a note that I was wrong in the link to other issue regarding thread leak - it is actually https://github.com/mperham/sidekiq/issues/2862
