### ISSUE TITLE
stuck workers in production

### ISSUE THREAD

**Issue by dbenjamin57** [mperham/sidekiq#3213]
Hi there, we are using Sidekiq v4.2.3 with ruby 2.3.1 (regular sidekiq not pro). 

After a long processing of multiple jobs we had in our queue I noticed that we have 9 stuck workers (workers that usually end in less than a second. 

I ran the worker manually with the same parameters and noticed it executes properly. Any idea on how to understand why these workers are stuck and maybe put a timeout on the execution of a worker so if they do get stuck once in a while, sidekiq will just kill it eventually? (say 1h since started processing...)

![image](https://cloud.githubusercontent.com/assets/1243052/19836761/e911ea7c-9eb2-11e6-8beb-d77a5f94411c.png)

**Comment by mperham** [comment]
You likely have a network call without a timeout.  Looks like you had a hiccup in the network 12 hours before that should have caused your connections to time out.  Use TTIN to get the backtrace.

**Comment by HenleyChiu** [comment]
Did you experience this problem in prev versions of Sidekiq (before upgrading)?
