### ISSUE TITLE
Automate testing successful boot of Sidekiq Process

### ISSUE THREAD

**Issue by joshuamcginnis** [mperham/sidekiq#3214]
Ruby version: 2.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 3.3.3

We've had a couple of issues recently in our Rails 4 app that could have been prevented with a simple check to see that both the main app and a worker process correctly boot up our application.

Our Procfile for Heroku looks like so:
```
web: bundle exec unicorn -p $PORT -c config/heroku/unicorn.rb
sidekiq: bundle exec sidekiq -q high -q medium -q low
```

Right now, we run a very large test suite that takes 30 mins to complete, even when bisecting the suite across 10+ containers.

We use CircleCI and are considering adding a test like follows that simulates the Sidekiq bootup process.

```ruby
require 'spec_helper'

RSpec.describe 'Booting processes' do

  context 'Sidekiq server' do
    it 'loads successfully' do
      boot_sidekiq_sequence = <<-SEQ
        require 'sidekiq/cli'
        Sidekiq::CLI.instance.environment = '#{ENV['RAILS_ENV']}'
        Sidekiq::CLI.instance.send(:boot_system)
      SEQ

      expect(system(%{echo "#{boot_sidekiq_sequence}" | ruby > /dev/null})).to be_truthy,
        "The Sidekiq process could not boot up properly. Run `sidekiq` to troubleshoot"
    end
  end
end
```

The problems I see with this approach are:

* It's not quite a complete test of our application boot process which would require reading from our Procfile (we also want to protect devs from making breaking changes there)
* It's slow and would add approx 30 secs to our test runtime

What makes testing the Sidekiq boot process in particular challenging is that it will only exit if there is an exception on boot.

Can anyone recommend a better, faster, more thorough approach to automating this kind of test?

**Comment by mperham** [comment]
I don't have a recommended approach to this type of integration testing aside from running a staging environment to flush out deployment issues.  We'll see if StackOverflow delivers.

**Comment by joshuamcginnis** [comment]
I hear you. If it were my company, we'd have some UAT step as part of the release process. My understanding is that imposing this step at this organization has shown to be unreliable in the past.

**Comment by mikegee** [comment]
This is slightly modified spec I wrote to make sure some other process could boot. I haven't actually done this for Sidekiq yet:

```ruby
require "open3"

describe "running Sidekiq command" do

  it "executes succesfully" do
    cmd = %w(bundle exec sidekiq -q high -q medium -q low)
    Open3.popen2e(*cmd) do |_, out, wait_thr|
      pid = wait_thr.pid
      output_pending = IO.select([out], nil, nil, 10)
      Process.kill "TERM", pid
      if output_pending
        expect(out.read).to match(/Running/)
      else
        fail Timeout::Error
      end
    end
  end

end
```

**Comment by widescape** [comment]
@mikegee I like!

I wanted to make sure that I execute exactly the command defined in the `Procfile`, so I adjusted your test like this:

```ruby
require 'foreman/procfile'
require 'open3'

# Utilizes a Procfile like this:
# web: bundle exec puma -C config/puma.rb
# workers: bundle exec sidekiq
#
describe Sidekiq do
  let(:procfile_name){ 'Procfile' }
  let(:command_name){ 'workers' }
  let(:command){ Foreman::Procfile.new(procfile_name)[command_name] || raise("'#{command_name}' not defined in '#{procfile_name}'") }

  it 'launches without errors' do
    expect(output_from(command)).to match(/Starting processing/)
  end

  def output_from(command)
    Open3.popen2e(*command.split) do |_, out, wait_thr|
      pid = wait_thr.pid
      output_pending = IO.select([out], nil, nil, 10.seconds)
      Process.kill 'TERM', pid
      if output_pending
        out.read
      else
        raise Timeout::Error
      end
    end
  end
end
```
