### ISSUE TITLE
Seeing mixed TZ in log entries

### ISSUE THREAD

**Issue by pchaganti** [mperham/sidekiq#3216]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.3

The docs in the wiki mention that all log entries are stamped with UTC times. Seeing mixed times in the logs like below. I am in the Eastern TZ and my time is 09:06 currently. The TZ on the server is set to UTC.

```
I, [2016-11-01T09:06:48.299918 #99348]  INFO -- : importing  ...
I, [2016-11-01T09:06:48.457074 #99348]  INFO -- : done: 1.262 sec
I, [2016-11-01T06:06:56.229891 #99348]  INFO -- : start
I, [2016-11-01T06:06:56.231223 #99348]  INFO -- : start
I, [2016-11-01T06:06:56.299605 #99348]  INFO -- : done: 0.07 sec
```

```Ruby
2.3.1 :001 > Time.now
 => 2016-11-01 13:10:15 +0000
2.3.1 :002 > Time.now.utc
 => 2016-11-01 13:10:23 UTC
```

Is there anything I need to configure to set the log entries to always be UTC?

thanks!

**Comment by pchaganti** [comment]
Switched to using a custom formatter that ensures UTC.

thanks

**Comment by mperham** [comment]
That's not the default log formatter. I have no idea who's formatting those lines.
