### ISSUE TITLE
Ent: sidekiqswarm ENV var names

### ISSUE THREAD

**Issue by jelder** [mperham/sidekiq#3218]
Ruby version: 2.2.4p230
Sidekiq / Pro / Enterprise version(s): sidekiq-4.2.3, sidekiq-pro-3.4.0, sidekiq-ent-1.3.2

It would be nice if the relevant ENV vars (such as `COUNT` and `MAXMEM_KB`) were prefixed with `SIDEKIQ_` or `SIDEKIQSWARM_`. As a Heroku user, I can't dynamically control ENV vars on a per-process basis without redeploying code. Having a more specific prefix would let me tune these values more easily, and #with less potential for side effects.

**Comment by mperham** [comment]
Yeah, good thought.  This is something I'd like to do for Enterprise 2.0.
