### ISSUE TITLE
How to config sidekiq to run specific type of job in a queue?

### ISSUE THREAD

**Issue by jeffrey008** [mperham/sidekiq#3219]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 3.2.0

Suppose I have a worker which can recognise human's gender by their face.
In each job the worker will run a script to determine this photo is man or female.
Each job is given a `truth` tag, to represent the real gender of the photo.

Now, if I only want to execute job with  `truth == "male"`, how do I do this in sidekiq?

The only way I can think of is: 
```ruby
class GenderWorker
  include Sidekiq::Worker  
  sidekiq_options :retry => 10
  
  def perform(truth, image_path)
    raise "currently only do male detection" if(truth == "female")  
    // do detection...
  end
	
end
```

This sounds a hack to me, is there a better way to do it? Thanks.

**Comment by mikegee** [comment]
> Now, if I only want to execute job with truth == "male", how do I do this in sidekiq?

Don't enqueue it in the first place or `return` early. The `raise` in your sample code will make Sidekiq retry it later.

**Comment by mperham** [comment]
The only way you can target specific jobs to a specific process is via custom queues.  Put all male jobs in a male queue and start the Sidekiq process with `bundle exec sidekiq -q male`.

**Comment by mperham** [comment]
Send a job to a specific queue like so: `GenderWorker.set(queue: g).perform_async(g, some_path)`
