### ISSUE TITLE
Workers sometimes can't find records

### ISSUE THREAD

**Issue by chris-lee** [mperham/sidekiq#322]
I have a message model with an after_create callback that queues up a sidekiq worker to email the message to the user.

In my rspec test I call `.drain` on the worker class to send the message and this works most of the time, but sometimes I get `ActiveRecord::RecordNotFound` errors. Since this worker is created via an after_create callback it should be there (and is in most test runs).

Any idea what's up?

``` Ruby
class Message < ActiveRecord::Base
  after_create :send_new_message_email

  def send_new_message_email
    EmailMessageJob.perform_async id
  end
end
```

``` Ruby
class EmailMessageJob
  include Sidekiq::Worker

  def perform(message_id)
    message = Message.find(message_id) <<<<< ActiveRecord::RecordNotFound

    # do stuff
  end
end
```

ruby 1.9.3 / rails 3.2.7

**Comment by sur** [comment]
For someone who might still be running in same issue:

Rails' after_commit needs to be used with precautions and understanding.

In my specific case, it was not useful to use the after_commit callback and I had to use the after_save (have to call on both create/update).

The issue can better be handled by using sidekiq's enqueuing:

earlier I had this:

```
after_save :notify
def notify
  MyMailer.notify(self, param1).deliver_later
end
```

which was having the above mentioned issues, however the sidekiq's retry mechanism was processing it successfully the next time but I wanted a clean way where it would not raise the error and should not queue in retries.
And this simple tweak fixed it:

```
after_save :notify
def notify
  MyMailer.notify(self, param1).deliver_later(wait: 30.seconds)
end
```


~ sur

**Comment by shinnyx** [comment]
> This callback is called after a record has been created, updated, or destroyed.

Not sure if it's a good idea to use `after_commit`. It might works fine for now since we only have `create` action in the controller. But it will be troublesome if we going to do stuffs in the console or adding features like editing the activity content.

**Comment by nickdowse** [comment]
Another option if you're on Rails 3/4 and having issues with the `after_commit` not running in specs is to use the `test_after_commit` gem: https://github.com/grosser/test_after_commit. (See also http://stackoverflow.com/questions/22988968/testing-after-commit-with-rspec-and-mocking)

**Comment by prashantsirohi04** [comment]
I am using rails 4.2 with sidekiq and facing the same issue as the original question, i have used after_commit :on_create and this is not in tests but in actual background job. Any suggestions?
