### ISSUE TITLE
Is Sidekiq Web UI compatible with Rails API (Rails 5)

### ISSUE THREAD

**Issue by UniIsland** [mperham/sidekiq#3222]
My team is considering to use sidekiq with an API only rails 5 app.

I'm not very familiar with rails internals, and wonder if sidekiq web ui works without the middlewares to handle js/css assets.

Can anybody shed light?

**Comment by mperham** [comment]
Sidekiq's UI only requires rack and rack-protection, it does not use Rails at all.
