### ISSUE TITLE
Connection timeouts from sidekiq workers

### ISSUE THREAD

**Issue by dbenjamin57** [mperham/sidekiq#3228]
Hi there, wanted to consult regarding an issue we have in production regarding DB connection pool optimizations.

We host on Google cloud and we use MySQL DB Gen 2. This DB allows up to 4K active connections. 

Today we have 30 processing servers up and we build the concurrency between our servers through Sidekiq.  Each app server has a limit of max 100 sidekiq workers (total of 3K total workers available for work). Our web application server is Puma.

When we first went live, we started receiving an issue of ActiveRecord::ConnectionTimeoutError/Faraday::ConnectionFailed: execution expired/Faraday::TimeoutError: too many connection resets. Initially, our DB pool in prod was 20.  So our quick solution was to give our servers the same amount of DB connections as workers (connection pool 100). We knew this was wasteful and we would need to optimize but this was a good enough solution for then. 

Now, we still get the these errors many times (workers restart and then they work fine). These errors come at much lower scale, but I don’t understand why they should ever occur. 

Any ideas on why this happening and how should we go about to mitigate this issue? 

Thanks in advance,
Dan

**Comment by mperham** [comment]
No clue but I hope you figured it out.  Please let us know if you tracked it down.
