### ISSUE TITLE
Controlling Concurrency Per Worker

### ISSUE THREAD

**Issue by gniquil** [mperham/sidekiq#3230]
Ruby version: 2.2
Sidekiq

In my system there are many workers. Among these there is 1 worker with which I'd like to execute only 1 at a time. Is there a built-in way for me to do this? I do not want to change the global concurrency setting to 1 as concurrency works well for all other workers.

If not, there are 2 ways I can imagine to do it:

1. for that particular worker, add it to a separate queue. Then add another instance of sidekiq to just work on that queue and set the global concurrency setting to 1; remove the new queue from the original sidekiq instance. (Cons: this increases the cost and the second instance will probably have very low utilization)

2. Within the worker, I will add some locking mechanism (probably just use redis) and rely on retry in case the lock can't be acquired. (Cons: more complexity => less reliable)

Anyway suggestions?

**Comment by mperham** [comment]
You are exactly right.

1. Sidekiq can do this out of the box.
2. With Sidekiq Enterprise you can use a [concurrent limiter](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#concurrent).

**Comment by gniquil** [comment]
sigh... ok. :)
