### ISSUE TITLE
# of process on AWS EC2 C3

### ISSUE THREAD

**Issue by dsshap** [mperham/sidekiq#3231]
Ruby version: 2.3
Sidekiq

Hi - 

I am running two AWS EC2 Instances (C3 Large, https://aws.amazon.com/ec2/instance-types/#c3)

vCPU: 2	
Mem (GiB): 3.75
SSD Storage (GB): 2 x 16

On each instance I have 6 sidekiq processes running (concurrency 25). Processing about ~700 jobs per second, and the jobs take anywhere between 300 to 800ms.

This feels like a lot of process for one instance - but after monitoring the memory usage (over a week) I am barely breaking 50%. It seems like I can safely increase the number of process to achieve ~75% utilization. 

I know a lot of this is dependent on the type of application, but I am curious what your thoughts are on this strategy?

**Comment by mperham** [comment]
General rule is one process per core, increase concurrency until cores are maxed.  YMMV of course.

**Comment by dsshap** [comment]
Interesting - I could have sworn I read a post from you that said keep concurrency low and increase the number of processes.

**Comment by mperham** [comment]
You can't increase concurrency forever, generally MRI is limited to <= 50, but again YMMV.

**Comment by dsshap** [comment]
Is there any harm to running ~5-8 process on the instance type I am using?

**Comment by mperham** [comment]
Try it and see.  You have two CPUs.  They'll all contend for CPU time and take more memory.
