### ISSUE TITLE
Consume jobs in batches

### ISSUE THREAD

**Issue by mnort9** [mperham/sidekiq#3232]
I'm considering switching from [Shoryuken](https://github.com/phstc/shoryuken) to Sidekiq. Shoryuken is able to "fetch in batches" on the consumer side without having to prepare batches on the producer side. 

This is really convenient for sending data off to a third party api that has batch capabilities. Is similar functionality available on Sidekiq?

**Comment by mperham** [comment]
Sidekiq does not support fetching multiple jobs at a time.  Sounds like that's an SQS feature.  You can do something like sending an array of ids as a job argument: [1,2,3] and have the job process the array but that's considered a single job and would need to be enqueued by the client like that.
