### ISSUE TITLE
Why does the wiki on ActiveJob use both .deliver_later and deliver_later!

### ISSUE THREAD

**Issue by vincentwoo** [mperham/sidekiq#3236]
From the [ActionMailer](https://github.com/mperham/sidekiq/wiki/Active-Job#action-mailer) section:

To send a basic message to the Job Queue we can use:

```ruby
UserMailer.welcome_email(@user).deliver_later
````

New syntax to send delayed message through Active Job:

```ruby
UserMailer.welcome_email(@user).deliver_later!(wait: 1.hour)
UserMailer.welcome_email(@user).deliver_later!(wait_until: 10.hours.from_now)
```

Is there a particular reason the one with a deliver delay needs to use `deliver_later!` with the bang (!)?

**Comment by mperham** [comment]
I've never heard of that bang method.  I removed the bangs.
