### ISSUE TITLE
Job for old class name stuck in private queue

### ISSUE THREAD

**Issue by johnathanludwig** [mperham/sidekiq#3239]
Ruby version: 2.25
Sidekiq / Pro / Enterprise version(s): 4.2.5 / 3.4.0 / 1.3.2

We have a job for a worker that has been removed that is stuck in the private queue. Periodically it gets retried and generates an uninitialized constant Schedule5MinScan error, but it never moves into the retry set. This has happened with reliable fetch before as well, but as you can see here we are now using super fetch.

The private queue it gets stuck in is one for a current existing worker. 

![screenshot 2016-11-14 11 30 44](https://cloud.githubusercontent.com/assets/1262078/20273277/a7a56d86-aa5e-11e6-9435-f0f53cea1bb7.png)

**Comment by mperham** [comment]
The easiest solution is to create a dummy class with an empty perform that will execute the job so it goes away.  Like a database column names, Sidekiq persists the job class names so you need to treat changing a worker name like a multi-step column rename migration: 1. create the new job, 2. deploy, 3. make sure all old jobs have finished and no longer referenced, 4. remove the old one.

**Comment by johnathanludwig** [comment]
Yeah I can fix this on our end. I just wanted to report it since it seemed like a bug because it never makes its way to the retryset. It would be a lot easier to have it there and just be able to delete the job.

**Comment by mperham** [comment]
The job dispatch redesign for 4.3 should fix this.  The error is when constantize is called, which is outside the retry block in 4.2 but inside the retry block in 4.3.  That redesign is here:

https://github.com/mperham/sidekiq/blob/redesign_dispatch/lib/sidekiq/processor.rb#L122
