### ISSUE TITLE
Jobs that fail with retry: false and unique_for, don't clear their unique lock

### ISSUE THREAD

**Issue by foeken** [mperham/sidekiq#3240]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 3.5.4 / 2.1.3 / 0.7.10

When the unique job feature is enabled, the jobs that have retry false and crash never have their lock automatically released (but after the timeout they do naturally).

**Comment by mperham** [comment]
This is by design, the job never succeeds so the lock waits for the timeout: https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#retries
