### ISSUE TITLE
QUESTION:  Is it possible to customize UI?

### ISSUE THREAD

**Issue by richessler** [mperham/sidekiq#3242]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Pro

If relevant, please include your initializer and any error message with the full backtrace.

I have several types of admin user roles, and I do not want to give actionable permissions to all users in the portal. Is it possible to configure the UI to have, say, a read-only option?

Thanks in advance!

**Comment by mperham** [comment]
It's not possible today but that's an interesting idea for a feature.

**Comment by richessler** [comment]
@mperham Thanks! much appreciated!

**Comment by mperham** [comment]
Actually you could implement a Rack middleware that blocks POST requests before they are dispatched to the webapp.  How to do this is undocumented and not really supported but can be done afaik.

**Comment by nthx** [comment]
Hey @mperham 
I appreciate your work :+1: 

Is there any new regarding the mentioned functionality?
I'm thinking about giving users with different permissions access to actionable buttons in UI (like pausing queue)

**Comment by mperham** [comment]
@nthx Please don't resurrect decade old issues. Open your own new issue.
