### ISSUE TITLE
Provide an option to disable/hide the "delete all" / "retry all" button in the morgue

### ISSUE THREAD

**Issue by Chetane** [mperham/sidekiq#3243]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Enterprise

We're running Sidekiq in a production environment on a large codebase with tens of contributors. As a result, at times, there are multiple dead jobs in the morgue of various importance. Rarely (but it happens), someone on the team accidentally clicks `Delete all` instead of `Delete` which is *very* dangerous for us. 

Would it be possible to have a configuration option to disable/hide the `Delete All` and `Retry All` buttons from the Morgue Web UI? Because this may not be useful for most users of `Sidekiq`, it would work for us if it were an enterprise only option.

Thanks in advance @mperham, and happy to submit a PR if you're OK with the idea.

**Comment by Chetane** [comment]
I should also mention this often happens when filtering down jobs in the morgue. For example, if there are 1,000 failed jobs to delete, we've filtered by the job name and then selected `Delete All` . This will counter-intuitively delete all jobs, rather than only the filtered ones. It would be nice for `Delete All` to respect the filter. 

I can open a separate issue for that, if you agree that should be the expected behavior.

**Comment by mperham** [comment]
@Chetane Please open a separate issue for that second comment.  That's arguably a bug and I think we can fix it by hiding the All buttons when filtering is active.

**Comment by mperham** [comment]
That commit, plus #3251, should handle your feedback.
