### ISSUE TITLE
Web UI issue not showing job runs on that particular queue

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3244]
![sidekiq](https://cloud.githubusercontent.com/assets/3119321/20432186/01cf6074-adc4-11e6-8e25-fdc7d234cae7.PNG)

Ruby version: 2.1.4
Sidekiq / Pro / Enterprise version(s): 4.1.4
Redistogo:
Heroku

in intializer:

`````
require 'sidekiq'
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  # config.redis = { db: 1 }
  config.redis = { url: ENV['REDISTOGO_URL'] }
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 90.minutes # default
  end
end

Sidekiq.configure_client do |config|
  config.redis = { size: 1, url: ENV['REDISTOGO_URL'] }
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 90.minutes # default
  end
end
``````````

In busy state how we can see this should I have to buy pro?

**Comment by mperham** [comment]
You've already processed all the jobs.  Go to the Busy tab to see jobs that are executing **right now**.
