### ISSUE TITLE
Add enqueued_at when fake Testing

### ISSUE THREAD

**Issue by Ferdy89** [mperham/sidekiq#3245]
Ruby version: 2.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.2, Sidekiq Pro 3.3.3, Sidekiq Ent 1.3.2

This is a feature request, not a bug.

While running some tests, we realized queuing jobs while on fake testing mode doesn't add the `enqueue_at` attribute. It feels to us that it could be a simple change to make fake mode closer to the real one.

We're happy to implement this change if approved.

**Comment by mperham** [comment]
:+1:
