### ISSUE TITLE
Inter-worker communication via pubsub hangs

### ISSUE THREAD

**Issue by darrhiggs** [mperham/sidekiq#3246]
Ruby version: 2.3.1
Sidekiq version(s): 4.2.6

I have setup a [rails app](https://github.com/darrhiggs/sidekiq_pubsub) to try and demonstrate the issue fully.

Th app has two workers

1. Subscriber - that blocks awaiting messages.
2. Publisher - sends a close message to the channel the Subscriber is listening to.

When the app "initially" sets up a Subscriber blocking awaiting messages, it hangs, stopping the Publisher from executing.

Using `redis-cli` it's possible to send messages to the subscriber e.g. `PUBLISH subscriber close`.

Once a message is published via `redis-cli` the issue disappears and the app is able to freely start Subscribers and Publishers.

**Comment by mperham** [comment]
In general, Sidekiq is not an appropriate platform for pubsub.  Synchronous communication between workers is not supported.

Specifically, your app is hanging because the publisher is publishing before the subscriber has subscribed.

**Comment by darrhiggs** [comment]
Ok, so would you suggest polling in preference?

I spent a reasonable amount of time putting this bug report together in a concise manner, and if the point is that it is not something you support, that's fine. But, I don't believe you diagnosis of the issue is correct.

Did you try the [app](https://github.com/darrhiggs/sidekiq_pubsub)?

**Comment by mperham** [comment]
Yes, I looked at the app.

At a high level, I have no idea what you are trying to do but Sidekiq is designed for jobs which are small and self-contained, it is not designed to implement app components communicating via pubsub.

**Comment by darrhiggs** [comment]
I have a usecase whereby I my app receives a request to complete some non-trivial amount work.

I respond to this with a 202 Accepted and a link to a status monitor (a representation of a worker that is tracking the total job progress) so that the frontend can display an ETA for job completion.

I was planning to purchase sidekiq-pro, & use the batches feature. I would create a subscriber (status monitor), pass it a batch ID to use as a channel to listen on. Then all jobs that are created as part of that batch could communicate with the subscriber how much of their work that had done and if they had created more work (added more sub-tasks to the batch) by publishing to the channel.

The jobs are all small and self contained, I just am looking to implement finer grained status than queued/working/complete/failed.

The app I created is just a reduction of this pattern, with the publisher being the on_success callback for the batch, killing the status monitor as the work is complete/.

I hope this makes a bit more sense.

**Comment by mperham** [comment]
Batch status can be watched via pubsub or polling, as explained on the Batches page, but you cannot use pubsub to monitor from another job because there is no guarantee when the batch will be done, safest and easiest option is to poll via JavaScript.

**Comment by darrhiggs** [comment]
Ok, thanks for your feedback.
