### ISSUE TITLE
Expose Pause/Unpause button on Queues in Web UI

### ISSUE THREAD

**Issue by ckorhonen** [mperham/sidekiq#3247]
Ruby version: 2.3.2
Sidekiq / Pro / Enterprise version(s): Pro / Enterprise

Love the pause queue feature in Sidekiq Pro. Would love a toggle button in the Web UI to pause/unpause.

**Comment by mperham** [comment]
:+1:

**Comment by mperham** [comment]
Ah right.  I forgot: pausing queues is explicitly meant to be API only.  You use it as part of automation, not an ad-hoc manual process.

**Comment by phantomwhale** [comment]
As someone who just ad-hoc stopped his queues, so he can ad-hoc update a search index before ad-hoc restarting the queue, this has not proven to be true.

Obviously this is a process we would like to automate going forward, but all automations start with a a little ad-hoc work initially, and it's a shame to have lost the pause button. I mean, we can still start up a rails console and execute `#pause!` on the queue, but certainly less convenient than it used to be.

**Comment by ACPK** [comment]
@phantomwhale - I agree with you, and would love a pause button as part of the "pro" web UI.

**Comment by sj26** [comment]
We would also love Pause and Unpause buttons in the Sidekiq web UI. Or the capability to add one with a plugin.

**Comment by bladepop** [comment]
Agree, this would be very nice to have!

**Comment by nakulpathak3** [comment]
1.5 years too late but I also agree. This is especially important as people are going serverless. For example, we're using ECS Fargate now and SSH-ing onto a fargate machine is quite complicated and often discouraged. We use this functionality during incidents and planned maintenances to avoid triggering all our monitors.

**Comment by mperham** [comment]
This was added in [Sidekiq 6.0.4](https://github.com/mperham/sidekiq/blob/master/Changes.md#604)
