### ISSUE TITLE
Sidekiq Pro quiet process still accepts jobs without executing them

### ISSUE THREAD

**Issue by 9diov** [mperham/sidekiq#3249]
Ruby version: 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): 2.0.5 (Pro)

I'm having issue with Sidekiq Pro quiet process (being quiet either by Sidekiq UI or sending signal) that still accepts jobs into its internal queue without executing them. When I shutdown the quiet process (via Ctrl-C or SIGTERM), the jobs are returned back to the global queue and other non-quiet processes can actually pick up and execute them.

Here is the relevant part of the log. Note that at 07:03:29.797 I used Ctrl-C to terminate the quiet process and then it returns back 3 jobs to the global queue:

```
2016-11-20T07:00:50.129Z 2798 TID-1bfrag INFO: Received USR1, no longer accepting new work
2016-11-20T07:00:50.129Z 2798 TID-1bfrag INFO: Terminating 22 quiet workers
2016-11-20T07:00:52.800Z 2798 TID-1esncw JobWorker JID-5ae7dc9b2cedfd22e20602aa INFO: done: 12.158 sec
2016-11-20T07:00:56.936Z 2798 TID-1fa5z4 JobWorker JID-e5698bac143f089dee4f89c6 INFO: done: 14.093 sec
2016-11-20T07:01:10.793Z 2798 TID-1frgd8 JobWorker JID-c970fbf8a824c71e5eb17386 INFO: done: 30.154 sec
2016-11-20T07:01:10.794Z 2798 TID-1bfrag INFO: Moving work from queue:filter_thanh-desktop_0 back to queue:filter
2016-11-20T07:01:10.794Z 2798 TID-1bfrag INFO: Moving work from queue:report_thanh-desktop_0 back to queue:report
^C2016-11-20T07:03:29.797Z 2798 TID-5a8ys INFO: Shutting down
2016-11-20T07:03:31.662Z 2798 TID-1bfrag INFO: Terminating 0 quiet workers
2016-11-20T07:03:31.663Z 2798 TID-1bfrag INFO: Moving work from queue:report_thanh-desktop_0 back to queue:report
2016-11-20T07:03:31.663Z 2798 TID-1bfrag INFO: Moving work from queue:report_thanh-desktop_0 back to queue:report
2016-11-20T07:03:31.663Z 2798 TID-1bfrag INFO: Moving work from queue:report_thanh-desktop_0 back to queue:report
```

**Sidekiq initializer**

```
redis_conn = proc {
  Redis.new(host: Rails.application.secrets.sidekiq_redis_host,
            port: Rails.application.secrets.sidekiq_redis_port,
            db: Rails.application.secrets.sidekiq_redis_db)
}
Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  Sidekiq::Logging.logger.level = Logger::INFO
  Sidekiq.logger.formatter = Sidekiq::Logging::Json::Logger.new if Rails.env.production?
  Rails.logger = Sidekiq::Logging.logger

  config.redis = ConnectionPool.new(size: 25, &redis_conn)
  config.reliable_fetch!

  config.reliable_scheduler! # Note: this is not safe for Redis Cluster
end
```

**Backtrace**
[backtrace.txt](https://github.com/mperham/sidekiq/files/601895/backtrace.txt)

**Comment by mperham** [comment]
Two things:

1. If you think you have found a bug, upgrade your version; it may have already been fixed.  You're on a pretty old version.
2. That sequence of events looks normal - I don't understand why you think the quiet process has picked up jobs, could you detail exactly what you think looks wrong?

**Comment by 9diov** [comment]
Hi Mike, thanks for your response.

1. I tried upgrading to latest Sidekiq Pro (3.4.0) and the issue persists
2. To reproduce the problems, here are the steps:

- Spawn up a few sidekiq processes with different index (sidekiq -i <num>)
- Choose one process to quiet, let's say process with index 2. Send out USR1 or use Sidekiq UI to this process.
- Send out a dozen jobs.
- Some of them (random subset) will seem to disappear without showing in the Sidekiq UI
- From here, you can do either: spawn another Sidekiq process with the same index as the quiet one (2) OR send SIGTERM to the quiet process.
- The "missing" jobs now suddenly got picked up. In the first case, they got picked up due to ReliableFetch of the same index process (Log message: Processing recovered job from queue queue:report (queue:report_thanh-desktop_2)).
- In the 2nd case, the jobs are picked up as if they just have been sent.

I will try to reproduce the issue using other type of fetch to see if there is any difference.

**Comment by 9diov** [comment]
I can confirm that some jobs are added to the quiet process's private queue even after the process is quiet. Here is the log from the quiet process (index 0)

```
2016-11-21T16:21:33.108Z 13724 TID-oxc93ltq8 INFO: Received USR1, no longer accepting new work
2016-11-21T16:21:33.108Z 13724 TID-oxc93ltq8 INFO: Terminating 25 quiet workers
```

The queue on Redis:
```
127.0.0.1:6379[1]> lrange queue:report_Dinhs-MacBook-Pro.local_0 0 -1
1) "{\"class\":\"JobWorker\",\"args\":[85],\"queue\":\"report\",\"retry\":true,\"jid\":\"6a90bce41d5bf5c0231bfc77\",\"created_at\":1479745440.19731,\"enqueued_at\":1479745440.197376}"
2) "{\"class\":\"JobWorker\",\"args\":[84],\"queue\":\"report\",\"retry\":true,\"jid\":\"08951f44073445bb818ac796\",\"created_at\":1479745307.889347,\"enqueued_at\":1479745307.8898911}"
```

Note the enqueued timestamp is after the log message when it says the quiet process was quiet.

**Comment by 9diov** [comment]
@mperham After digging further into Sidekiq Pro source code for ReliableFetch, looks like the Retriever singleton thread is not terminated when the Sidekiq process is quiet. Adding the 3 lines in `Retriever::start` seems to fix the problem:
```
          config.on(:quiet) do
            self.terminate
          end
```

```
    class Retriever
      def start(options)
        # some code...
        Sidekiq.configure_server do |config|
          config.on(:quiet) do
            self.terminate
          end
        end
        # some code...
      end
    end

```
Do you mind merging this patch? This is critical for our production system since we need to be able to quiet Sidekiq processes to manage our server resources.

**Comment by mperham** [comment]
All jobs in the internal queues are pushed back to the public queue upon TERM shutdown so why is it a critical matter that a job goes into an internal queue for a few seconds?  Are you shutting down the process correctly?  Have you tried using super_fetch instead?  reliable_fetch is all but deprecated at this point.

**Comment by 9diov** [comment]
@mperham First of all, super_fetch uses the exact same code for Retriever class so it suffers from the same issue. The good thing is that the exact same fix I proposed earlier would work.

Second of all, you are arguing the wrong point here. The issue has nothing to do with TERM. It is about the expectation of quieting the Sidekiq process. When I quiet a process, I don't expect it to keep accepting new jobs without executing it. **It is clearly a bug.** Jobs can't be executed in a timely manner when they are stuck in the process's private queue. Both current reliable_fetch and super_fetch suffers from the same issue and can be fixed very easily by adding the callback for quiet.

Third of all, you argue that the issue doesn't matter. It DOES matter for our workload. For us, we are running jobs with diverse execution time ranging from a few seconds up to more than one hour. Re-starting a job is something we try to avoid as much as possible since it causes issues downstream for our customers. In order to conserve memory yet avoiding restarting a running job, we need to quiet a Sidekiq process after a certain memory threshold, wait for all the jobs to finish then restart it. As a result, this period when a Sidekiq process is in quiet mode can last up to more than one hour. For us, **it is critical** that the quiet process doesn't hog the jobs that were sent to Sidekiq during this period. Our business requirements dictate that we need the jobs to execute as soon as they are sent.

Hope you understand our situation and the issue we are facing.

**Comment by mperham** [comment]
Thanks for the info, it's unusual for TERM to be sent an hour after USR1, I can understand this would make you more sensitive to lingering jobs.

The wiki documents that upon USR1 the process will stop processing new jobs but this isn't millisecond precise.  Notably, the fetch implementations will block waiting for a job for a second, meaning there is a one second window after USR1 where a job can be picked up.

No doubt there's room for improvement; if we can remove this window that would be a step forward.  I'm not convinced that adding a terminate call would fix this issue - the reliable job check call (e.g. super_fetch line 240) can still push jobs into the private queue after USR1.

**Comment by nvquanghuy** [comment]
Hi Mike, first thanks for a great piece of engineering.

I work with @9diov and would like to circle back to this issue, as we're moving towards zero-downtime deployment; gracefully restarting Sidekiq (without interfering with existing jobs) is important for us.

As mentioned by @9diov, our background works mainly consist of very-long running jobs (e.g. executing an analytics query against customer's database - millions of records).

What we intend(ed) to do, as per your [document](https://github.com/mperham/sidekiq/wiki/Deployment#overview), is send a USR1 signal, and wait for the running job to finish before sending the TERM signal (this means it can wait up to 30mins or more).

From the way Sidekiq works now, jobs are still being sent to private queue after USR1 signal, and released back to public queue after TERM system. That means those unlucky jobs are being delayed (up to 30 mins) unnecessarily. This affects our customers waiting for the jobs to be done.

Do you have any thoughts on how we can solve this problem? Either by modifying Sidekiq, or any workaround we can implement?

Regards,
Huy

**Comment by mperham** [comment]
Here's the quiet flow:

1. USR1 received, launcher.quiet -> manager.quiet -> [processor.terminate](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/manager.rb#L56)
2. If any fetcher retrieves a job after terminate is called, it is [immediately requeued](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L99).

The core issue is that Pro's reliable_fetch doesn't implement requeue.  **They let the job be picked up immediately after process restart.**  This is done because requeueing a job (removing from one list and pushing to another) cannot be performed safely without Lua and reliable_fetch was originally designed to work with Redis 2.4, before Lua.

timed_fetch does implement requeue.  **I'm adding a requeue implementation for super_fetch right now, which should fix your issue.**  I have no plans to backport this to reliable_fetch.

Thanks for following up, this fix will be in 3.4.4.

**Comment by nvquanghuy** [comment]
This is awesome. Thank you so much @mperham !

**Comment by nvquanghuy** [comment]
@mperham Circling back to this, do you have a timeline on when 3.4.4 will be released? And any suggestions/workaround we can do until then?

Regards,

**Comment by mperham** [comment]
I just released Pro 3.4.4 and Enterprise 1.5.2.

**Comment by nvquanghuy** [comment]
Awesome thank you!

**Comment by jcope2013** [comment]
am I correct that this/related fix wouldn't be an issue just using sidekiq basic fetch and is specific to the pro version?
