### ISSUE TITLE
[/lib/systemd/system/sidekiq.service:31] Executable path is not absolute

### ISSUE THREAD

**Issue by hendranata** [mperham/sidekiq#3250]
Ruby version: 2.3
Sidekiq / Pro / Enterprise version(s): 4.2.4

If relevant, please include your initializer and any error message with the full backtrace.

i want to enable systemd using sidekiq
but it always faild to: [/lib/systemd/system/sidekiq.service:31] Executable path is not absolute

[Service]
Type=simple
WorkingDirectory=/home/hendranata/project/gimart
ExecStart=bundle exec sidekiq -e development
User=deploy
Group=deploy
UMask=0002

**Comment by mperham** [comment]
The error message seems clear to me: `bundle` must be absolute.

**Comment by hendranata** [comment]
i have change the bundle path also not working.

ExecStart=/home/hendranata/.rvm/gems/ruby-2.3.0/bin/bundle exec sidekiq -e development


any idea? that is absolute path right?

**Comment by hendranata** [comment]
and now here is the log:

Nov 21 09:18:30 hendranata-N46VZ systemd[1]: sidekiq.service: Unit entered failed state.
Nov 21 09:18:30 hendranata-N46VZ systemd[1]: sidekiq.service: Failed with result 'exit-code'.
Nov 21 09:18:31 hendranata-N46VZ systemd[1]: sidekiq.service: Service hold-off time over, scheduling restart.
Nov 21 09:18:31 hendranata-N46VZ systemd[1]: Stopped sidekiq.
Nov 21 09:18:31 hendranata-N46VZ systemd[1]: sidekiq.service: Start request repeated too quickly.
Nov 21 09:18:31 hendranata-N46VZ systemd[1]: Failed to start sidekiq.
