### ISSUE TITLE
sidekiq systemd failed

### ISSUE THREAD

**Issue by hendranata** [mperham/sidekiq#3252]
Ruby version:2.3
Sidekiq / Pro / Enterprise version(s): latest version

If relevant, please include your initializer and any error message with the full backtrace.

here is the error log:
sudo systemctl status sidekiq

● sidekiq.service - sidekiq
   Loaded: loaded (/lib/systemd/system/sidekiq.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sen 2016-11-21 09:21:22 WIB; 5s ago
  Process: 5910 ExecStart=/home/hendranata/.rvm/gems/ruby-2.3.0/bin/bundle exec sidekiq -e development (code=exited, status=217/USER)
 Main PID: 5910 (code=exited, status=217/USER)

Nov 21 09:21:21 hendranata-N46VZ systemd[1]: sidekiq.service: Unit entered failed state.
Nov 21 09:21:21 hendranata-N46VZ systemd[1]: sidekiq.service: Failed with result 'exit-code'.
Nov 21 09:21:22 hendranata-N46VZ systemd[1]: sidekiq.service: Service hold-off time over, scheduling restart.
Nov 21 09:21:22 hendranata-N46VZ systemd[1]: Stopped sidekiq.
Nov 21 09:21:22 hendranata-N46VZ systemd[1]: sidekiq.service: Start request repeated too quickly.
Nov 21 09:21:22 hendranata-N46VZ systemd[1]: Failed to start sidekiq.

i have use absolute path in sidekiq.service

[Unit]
Description=sidekiq
After=syslog.target network.target

[Service]
Type=simple
Environment=RACK_ENV=development
WorkingDirectory=/home/hendranata/project/gimart/
ExecStart=/home/hendranata/.rvm/gems/ruby-2.3.0/bin/bundle exec sidekiq -e development
User=deploy
Group=deploy
UMask=0002

# if we crash, restart
RestartSec=1
Restart=on-failure

StandardOutput=syslog
StandardError=syslog

SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target

**Comment by alicjap** [comment]
same here at production
