### ISSUE TITLE
[Rails 5] Can't download web UI javascripts because of new CSRF strategy?

### ISSUE THREAD

**Issue by mariogintili** [mperham/sidekiq#3253]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

- ruby "2.3.1"
- Rails "5.0.0.1" and [CSRF forgery](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#csrf-protection-from-remote-script-tags)
- Sidekiq, "4.2.5"

```
ActionController::InvalidCrossOriginRequesthome#index
Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
```

Happens when the sidekiq web UI tries to load the javascript in my rails API

![screen shot 2016-11-22 at 9 46 10 am](https://cloud.githubusercontent.com/assets/3522106/20518838/879250e6-b098-11e6-9d68-f34f0730d7a1.png)

Are there any known work-arounds for this? I'm setting the web UI's secret to be the same as my Rails app

**Comment by mperham** [comment]
This is something specific to your browser or server setup.
