### ISSUE TITLE
Test with redis-rb 4.0.0 RC1

### ISSUE THREAD

**Issue by djanowski** [mperham/sidekiq#3256]
I just released redis-rb 4.0.0 RC1.

Can you please test with it and report back?

Thank you!

**Comment by mperham** [comment]
I can't, as redis-namespace locks to 3.x.

**Comment by djanowski** [comment]
OK, https://github.com/resque/redis-namespace/issues/124.

**Comment by mperham** [comment]
Any interest in integrating namespace support into redis-rb?  That would kill the middleman, so to speak.

**Comment by djanowski** [comment]
redis-namespace is a total nightmare and shouldn't be used. It's the exact opposite of simplicity.

Any interest in dropping redis-namespace from Sidekiq?

**Comment by mperham** [comment]
I wish, bro. http://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by mperham** [comment]
For Sidekiq 5 I could draw a line in the sand but I'm not sure that's a battle I want to fight.

**Comment by djanowski** [comment]
I'm sorry I'm not familiar with Sidekiq's codebase, but why do you need redis-namespace?

**Comment by mperham** [comment]
Because tons of users use it.  Migrating their persistent job data would be a huge hassle. https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L45

**Comment by djanowski** [comment]
I understand the need to put all Sidekiq stuff inside a namespace. But do you really need all the black magic redis-namespace is doing?

**Comment by mperham** [comment]
Removing namespace support, looks like the test suite passes if I change `conn.client` to `conn._client`.  Would you be able to add this same accessor in a new Redis 3.x release so I can release the next version of Sidekiq to work with >= 3.3.3?

**Comment by mperham** [comment]
Well, I'd be all for teaching people to use the 16 different DBes but Redis SaaSes often don't allow those to be used AFAIK.  There's a lot of users who share the same cheap Redis plan between web/Sidekiq by using namespaces.  Telling them to migrate just to lose a gem dependency, even if it's a bit painful for us, isn't really an option.  The sum of their pain would be >>>>> our pain.

**Comment by djanowski** [comment]
> Removing namespace support, looks like the test suite passes if I change `conn.client` to `conn._client`. Would you be able to add this same accessor in a new Redis 3.x release so I can release the next version of Sidekiq to work with >= 3.3.3?

Of course!

> Well, I'd be all for teaching people to use the 16 different DBes but Redis SaaSes often don't allow those to be used AFAIK.

Clearly I'm lacking context so apologize my ignorance. Can't Sidekiq just build the keys it uses by prepending the given string namespace?

**Comment by mperham** [comment]
Fair question.  I access Redis at hundreds of different call sites so this would be a big undertaking but perhaps something I should consider for Sidekiq 5.  Maybe I can vendor my own copy of redis-namespace.

**Comment by badboy** [comment]
I'd be happy to help with getting this into sidekiq directly with the minimal code possible to avoid the hassle of redis-namespace (something simple as [nido](https://github.com/soveran/nido) might actually do the trick)

**Comment by djanowski** [comment]
FYI redis-rb 4.0 is out.

**Comment by mperham** [comment]
Thanks for the note and your ongoing effort in maintaining the gem! 👍
