### ISSUE TITLE
allow serial processing within a queue

### ISSUE THREAD

**Issue by ejlangev** [mperham/sidekiq#326]
The basic idea would be that I could mark a given queue to be processed serially by some identifier or argument enqueued with the job.  An example use case is a job that updates a cache.  Say it enqueues two jobs the first says "Set cache entry a to be 0" and the second says "Set cache entry a to be 1."  The expected result is that when the jobs have finished running cache entry a equals 1.  However, in a parallel operation I have no guarantee the the jobs will be processed in order and I could end up with the second job happening before the first and my cache getting set to the incorrect value.

I've looked through the documentation and open issues related to sidekiq and didn't see anything related to this type of problem nor could I think of a good way to solve this type of problem given the current functionality.  Apologies if I've missed something and this has already been sovled,  interested to hear other thoughts on this

**Comment by pioz** [comment]
Any valid alternative to achieve this goal?

**Comment by mperham** [comment]
@pioz Don't resurrect six year old closed issues.  Other people associated with the issue will likely not care anymore.  Open your own issue with a description of your own problem.
