### ISSUE TITLE
disappearing jobs - known issue with extensions?

### ISSUE THREAD

**Issue by dbenjamin57** [mperham/sidekiq#3261]
Hi there, we have encountered an issue that some jobs dont get executed even though they get enqueued(we see them in the enqueued tab in sidekiq web ui). We can't really replicate as this happens once every 1K jobs or more but its hitting us with integration testing.

Today we are using these 3 in conjuction:
gem 'sidetiq'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-throttled'

Are there any known issues we should be aware of? The specific disspearing jobs we have noticed are only using 2 gems though:

class SomeWorker
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
 
  sidekiq_options unique: :until_and_while_executing
  sidekiq_throttle({ concurrency: { limit: 30 } })
end

Any ideas?

**Comment by mperham** [comment]
Make sure you are using 4.2.7. I don't support those 3rd party gems but I'm not aware of any problems with them.

**Comment by dbenjamin57** [comment]
@mperham upgraded to 4.2.7 from 4.2.6, will post if that did the trick
