### ISSUE TITLE
Sidekiq threads all dead (segfaulted) but master process still alive

### ISSUE THREAD

**Issue by jmondo** [mperham/sidekiq#3263]
Here's the issue. We run a process with 25 threads and we have a bug in our code that over time will segfault. (We are investigating why that is...) What happens though is that eventually all 25 threads halt with the same segfault. But the main sidekiq process continues to run and appear healthy. This causes our process manager to think everything is healthy with the process and let it keep running, meanwhile no work is happening. Should sidekiq exit with a non-zero status code when all of it's workers are effectively dead? That would be a great feature!

Ruby version:
2.2.3

Sidekiq / Pro / Enterprise version(s):
sidekiq-pro (2.1.3)
sidekiq (3.5.2)

If relevant, please include your initializer and any error message with the full backtrace.
```
/opt/app/app/social_services/facebook_profile/parser.rb:165: [BUG] Illegal instruction at 0x007fb4874a811f
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0052 p:---- s:0242 e:000241 CFUNC  :split
c:0051 p:0025 s:0238 e:000237 METHOD /opt/app/app/social_services/facebook_profile/parser.rb:165
c:0050 p:0023 s:0231 e:000230 BLOCK  /opt/app/app/social_services/facebook_profile/parser.rb:103 [FINISH]
c:0049 p:---- s:0226 e:000225 IFUNC
c:0048 p:0011 s:0224 e:000222 BLOCK  /opt/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187 [FINISH]
c:0047 p:---- s:0220 e:000219 CFUNC  :upto
c:0046 p:0013 s:0216 e:000215 METHOD /opt/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186 [FINISH]
...
```
cc @jessebuesking

**Comment by mperham** [comment]
A thread can't segfault, only a process can and then the entire process dies.  If you are spinning up your own child Sidekiq processes, you'll need to monitor them and restart them somehow.  Sidekiq Enterprise's [multi-process feature](https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process) has this monitoring built-in.

It looks like the fault is somewhere in nokogiri.

Also, you're on a version over a year old.  You might consider updating sometime soon.

**Comment by jmondo** [comment]
Ah sorry I misspoke about threads vs processes. Yes, the process segfaulted. But when I run top on that machine I still get:

`    1     0 root     S     502m   3%   2  13% {bundle} sidekiq 3.5.2 app [22 of 25 busy]`

But in the sidekiq UI this process has been dropped from the "Busy" tab.

**Comment by mperham** [comment]
I can't decipher that ps line. Sidekiq should never be PID 1.

**Comment by jmondo** [comment]
It's pid 1 because we are running it within a kubernetes pod. Kube always makes the main process in a pod pid 1. When that process dies, it restarts the whole pod. (That's why we are hoping sidekiq would exit when it segfaults, so that kube can auto-restart it.)

**Comment by jmondo** [comment]
i am upgrading sidekiq now also, perhaps that will change the behavior.

**Comment by mperham** [comment]
Sidekiq is definitely not designed to run as pid 1.  I don't know how it will behave, for example it does not reap child processes. Sidekiqswarm does.

**Comment by ryansch** [comment]
@jmondo Try something like https://github.com/Yelp/dumb-init or https://github.com/krallin/tini for container usage.

**Comment by jmondo** [comment]
ah nice this looks helpful thanks!

**Comment by mperham** [comment]
@ryansch By any chance have you tried running sidekiqswarm directly?  It implements the minimal `wait` loop required to reap child processes so should be able to run as PID 1 (I should probably document it better as "container-friendly" in that regard).
