### ISSUE TITLE
Sidekiq working but no stats on Web UI

### ISSUE THREAD

**Issue by mmcnl** [mperham/sidekiq#3266]
I've got Sidekiq (seemingly) working on Heroku, i.e. ActiveJob seems to be enqueueing and processing my mailer jobs and the emails are going out.

```
Dec 02 13:24:31  app/web.1:  [ActiveJob] [ActionMailer::DeliveryJob] [c6288fe5-2810-4c73-8ba2-35e931190bbb] Performing ActionMailer::DeliveryJob from Async(mailers) with arguments: "Notifier", "video_uploaded_notice", "deliver_now", #<GlobalID:0x007f2fec01f838 @uri=#<URI::GID gid://metta/Video/77>>, #<GlobalID:0x007f2fec01ed48 @uri=#<URI::GID gid://metta/User/153>> 
Dec 02 13:24:33  app/web.1:  [ActiveJob] [ActionMailer::DeliveryJob] [c6288fe5-2810-4c73-8ba2-35e931190bbb] Performed ActionMailer::DeliveryJob from Async(mailers) in 1765.72ms 
```

However, Sidekiq isn't recording any action in the Web UI:

![image](https://cloud.githubusercontent.com/assets/1498727/20851165/92cd5bba-b893-11e6-9a6e-1d1314ce0150.png)

![image](https://cloud.githubusercontent.com/assets/1498727/20851190/b35c5926-b893-11e6-82a8-708d4aa861b3.png)

What could I be missing here?

Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 4.2.7

If relevant, please include your initializer and any error message with the full backtrace.

```
#config/initializers/sidekiq.rb
if Rails.env.production? || Rails.env.staging? || ENV['ENABLE_SIDEKIQ']
  require 'sidekiq'
  require 'sidekiq/web'
  Sidekiq.redis(&:info)
  LOGGER.info "Redis is available, using Sidekiq for ActiveJob"
  Rails.application.config.active_job.queue_adapter = :sidekiq
else
  puts (message = "Using inline ActiveJob adapter")
  LOGGER.warn message
  Rails.application.config.active_job.queue_adapter = :inline
end
```

**Comment by mperham** [comment]
Please include your initializer.

**Comment by mmcnl** [comment]
I've edited the original post to include the initializer. The logic in there was intended to allow graceful bypass of Sidekiq in development mode (unless overridden with the ENV var). Maybe that's a bad idea?

**Comment by mperham** [comment]
I would always recommend using the same infrastructure in development as production.  You'll catch problems much earlier.

If you do that, you can remove that entire initializer as long as you update config/application.rb to enable sidekiq for AJ and require sidekiq/web in config/routes.rb.

**Comment by mperham** [comment]
Do all that and see if your web UI works better.

**Comment by mmcnl** [comment]
Thanks for the input. Removing the initializer did the trick, though I'm still not sure where the problem lay. I'll post back here if I investigate further later, but closing for now. Thanks again for the tip.
