### ISSUE TITLE
How to check the logs in Heroku

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3267]
We are using Sidekiq for our app. But not able to see the log instead We follow all set up mention here

https://github.com/mperham/sidekiq/wiki/Logging

Please suggest

We are using redis to go plugin there 

Ruby version: 2.2.3
Sidekiq / Pro / Enterprise version(s): 4.1.4

If relevant, please include your initializer and any error message with the full backtrace.

**Comment by mperham** [comment]
Are you looking for `heroku logs | grep worker`?

**Comment by rajcybage** [comment]
Hi Mike the log is showing in sidekiq

**Comment by mperham** [comment]
I would suggest you remove any custom logging configuration you might have, if any.
