### ISSUE TITLE
Feature Request: Print the job class and its arguments in the log.

### ISSUE THREAD

**Issue by tioteath** [mperham/sidekiq#3268]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.5 / 3.3.1

It often happens that dashboard isn't available (due to the general errors in the app), so it's impossible to understand from the log what's going on. If the job class (name) was available in the log that would  greatly simplify the analysis.

**Comment by mperham** [comment]
The job class is printed.  The args can be very long, contain private info, etc so they aren't.

**Comment by tioteath** [comment]
> The job class is printed. 

It doesn't seem so as I can't grep a single of them, could you please point me to the line in sidekiq's code where it's being printed, so I could debug why it isn't being printed to me?

> The args can be very long, contain private info, etc so they aren't.

By any mean the web-dashboard is much much less secure than a log. If a cracker got an access to the log, any talk about security is pointless as all the database/redis credentials are right over here in the configuration file  (I personally, wouldn't even bother to look in the log in a such case). So question stays open, why parameters are shown in the dashboard, but not in the log?

**Comment by mperham** [comment]
`klass` https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/logging.rb#L26
