### ISSUE TITLE
Ghost job executing after removal of periodic job

### ISSUE THREAD

**Issue by grosscr** [mperham/sidekiq#3269]
Ruby version: 2.2.2 
Sidekiq / Pro / Enterprise version(s):
  - Sidekiq: 4.2.2
  - Pro: 3.3.3
  - Enterprise: 1.3.2

I'm having an issue where we have removed a periodic job from the schedule with a configuration change, but there was still a retry attempt in the queue when this was done. After the configuration was removed we began seeing errors for an "uninitialized constant" that was the class name of the scheduled job that was removed. Looking through the logging it traces back to a job that was created before the code was removed.

I have attempted to resolve these errors by removing the relevant job from sidekiq, but it doesn't exist anywhere. It's not in the enqueued, scheduled, or retried queues. I've also checked the host specific queues in redis and haven't been able to find it there either. It also appears to get kicked off every time our sidekiq workers cycle. Looking in the sidekiq logs, the retry count is also not being incremented so it won't kill itself off either. Any ideas as to where this job could be hiding and how I get rid of it?

Stack trace:
```
NameError: uninitialized constant MarkAndEmailStaleRequests
  from active_support/inflector/methods.rb:238:in `const_get'
  from active_support/inflector/methods.rb:238:in `block in constantize'
  from active_support/inflector/methods.rb:236:in `each'
  from active_support/inflector/methods.rb:236:in `inject'
  from active_support/inflector/methods.rb:236:in `constantize'
  from active_support/core_ext/string/inflections.rb:66:in `constantize'
  from sidekiq/processor.rb:126:in `block in process'
  from sidekiq.rb:35:in `call'
  from sidekiq.rb:35:in `block in <module:Sidekiq>'
  from sidekiq/processor.rb:122:in `call'
  from sidekiq/processor.rb:122:in `process'
  from sidekiq/processor.rb:81:in `process_one'
  from sidekiq/processor.rb:69:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mperham** [comment]
It's in a private queue.  Create a dummy worker with the same name so the job can "execute" and go away peacefully; make sure you treat worker renames or removals as a migration since the class names are persisted in Redis.
