### ISSUE TITLE
alternative to `.delay`?

### ISSUE THREAD

**Issue by mtyeh411** [mperham/sidekiq#3272]
I'm looking at documentation for [delayed extensions](https://github.com/mperham/sidekiq/wiki/Delayed-extensions).  Am I correct to interpret that it should not be used for Rails 5 development and in general given long-term roadmap?

I think it's really handy to be able to use the `.delay` class method for any Ruby class.  Is the only option to create a worker that proxies arguments to my Ruby class when the worker is `perform`ed?

**Comment by mperham** [comment]
It'll continue to be supported, it'll likely just become opt-in so it doesn't pollute Class by default.

**Comment by mtyeh411** [comment]
@mperham thanks for clarifying. closing now
