### ISSUE TITLE
Tune super_fetch orphan check timeout

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3273]
Right now, super_fetch automatically checks for orphaned jobs/queues every 24 hours at process startup.  This means if a process crashes, the jobs for the process can linger for up to 24 hours + time until the next restart.  Lower the window to 1 hour to minimize the orphan delay.

**Comment by such** [comment]
Hey, Is this still the case? Looking at the code I can't figure out how it's done. It seems it's not configurable either. Can you confirm?

**Comment by mperham** [comment]
It is configurable with:

```ruby
Sidekiq.configure_server do |config|
  config.options[:super_fetch_orphan_check] = 3600
  config.super_fetch!
end
```

but I do not recommend lowering it to less than one hour. The scan process can be hard on Redis and it'll make Sidekiq run any poison pill jobs more frequently.
