### ISSUE TITLE
Be more explicit about requiring a running Redis server

### ISSUE THREAD

**Issue by slhck** [mperham/sidekiq#3278]
This is a minor suggestion for the docs: As a new user, when you want to use Sidekiq and follow the instructions from the README where it says "Installation", you will basically be prompted to only do a  `gem install sidekiq`. When you later follow the steps in the "Getting Started" page, you will receive an error message about Redis not being available.

I know that Redis is mentioned in "Requirements" and that users should RTFM, but when you're just skimming the front page, it's quite easy to miss it. A new user might not even know what Redis is or why they'd need it, and that it doesn't just install "with Sidekiq" when using `gem`.

Perhaps this part could be made a little more readable:

> ## Requirements
>
> * Ruby: CRuby 2.0+ and JRuby 9k.
> * Rails >= 3.2
> * [Redis](https://redis.io/) >= 2.8 (3.0.3+ is recommended for large installations with thousands of worker threads)
>
> ## Installation
>
> Install and start [Redis](https://redis.io/) first. Then:
> 
>     gem install sidekiq

Or it could be mentioned in the "Getting Started" page right before running `bundle exec` (e.g. "make sure that the Redis server is running and reachable at …")

**Comment by mperham** [comment]
You can edit files directly on GitHub.  Edit the readme so it'll send me a PR?

**Comment by slhck** [comment]
Gotcha, I've never done this before through the web. PR submitted!
