### ISSUE TITLE
Hide the intial preview line when using Show All in the UI 

### ISSUE THREAD

**Issue by YesThatAllen** [mperham/sidekiq#3282]
**Ruby version:** `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
**Sidekiq / Pro / Enterprise version(s)**: `Sidekiq v4.2.7 / Sidekiq Pro v3.4.1`

When viewing a queued job in the web UI, using the `Show All` button displays the first line twice.

I understand that the button is showing the full job, it would be helpful if the initial preview line was hidden.

![screenshot_2310](https://cloud.githubusercontent.com/assets/2879972/21289088/54d097c4-c459-11e6-963f-0148e4a10c25.png)

**Comment by mperham** [comment]
Easy PR if someone is looking to contribute!
