### ISSUE TITLE
Enqueuing Jobs causes Sidekiq to hang

### ISSUE THREAD

**Issue by asheehan** [mperham/sidekiq#3283]
Ruby version: 2.1.9
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.7 / Sidekiq Pro 3.4.1

I am having an issue where Sidekiq Pro seems to be freezing/hanging on some jobs.  When I start new workers while some workers are already enqueued Sidekiq stops processing new jobs and will enqueue new jobs, but never finish processing any of them.  Restarting Sidekiq (via kill -9) only occasionally returns things to an actual running state.

Sidekiq does not respond to the TTIN signal (nor any signal except -9).

Also of note, the process list often shows that some workers are busy, however the Sidekiq gui shows `0 Busy, # Enqueued`.  The number of enqueued often does not match the process list.

`asheehan 61418   0.0  2.2  3646736 361784 s007  S+    4:05PM   0:33.23 sidekiq 4.2.7 apollo [9 of 25 busy]`

If relevant, please include your initializer and any error message with the full backtrace.
initializer/gdb gist: https://gist.github.com/asheehan/4a8a596bac3df141b8e9017e1e283170

**Comment by mperham** [comment]
Your lockup is caused by therubyracer. As the problems wiki page notes, this gem is not safe to use within Sidekiq.
