### ISSUE TITLE
Cannot mount multiple apps with sidekiq-pro for WEB UI

### ISSUE THREAD

**Issue by ToniRib** [mperham/sidekiq#3287]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): sidekiq 4.2.7, sidekiq-pro 3.4.1

I have two apps, which I will call App A and App B that are both rails apps using sidekiq-pro. I'm attempting to set up a third app using Sinatra, App C, that will mount the sidekiq web UI to monitor both apps A & B. However, when I try this via the instructions on the pro web UI with sharding, it doesn't seem to pick up the connection pools and their URLs. When I start locally, the web UI tells me I am connected to redis://127.0.0.1:6379/0 instead of either of the heroku hosted redis urls that I provided via environment variables.

This is my config.ru file:

```
require 'sidekiq'
require 'sidekiq/pro/web'

APP_A = ConnectionPool.new { Redis.new(url: ENV['APP_A_PRODUCTION_REDIS_URL']) }
APP_B = ConnectionPool.new { Redis.new(url: ENV['APP_B_PRODUCTION_REDIS_URL']) }

map '/app-a' do
  use Rack::Auth::Basic, "Protected Area" do |username, password|
    username == ENV['USERNAME'] && password == ENV['PASSWORD']
  end

  run Sidekiq::Pro::Web.with(redis_pool: APP_A)
end


map '/app-b' do
  use Rack::Auth::Basic, "Protected Area" do |username, password|
    username == ENV['USERNAME'] && password == ENV['PASSWORD']
  end

  run Sidekiq::Pro::Web.with(redis_pool: APP_B)
end
```

Any idea how I can get these routes to actually connect to the correct, remote redis instances?

**Comment by mperham** [comment]
I don't think you can call run multiple times like that.  The `run` method never returns until the server is shutting down.  You need to use a URLMap to mount multiple Rack apps.  Something like:

```ruby
run Rack::URLMap.new(
  '/app-a' => Sidekiq::Pro::Web.with(redis_pool: APP_A,
  '/app-b' => Sidekiq::Pro::Web.with(redis_pool: APP_B,
)
```

All of this is untested so I could be completely wrong but try something like that.

**Comment by ToniRib** [comment]
@mperham Thank you for the quick input! I ended out trying that, so my config.ru file now looks like:

```
require 'sidekiq'
require 'sidekiq/pro/web'

APP_A = ConnectionPool.new { Redis.new(url: ENV['APP_A_PRODUCTION_REDIS_URL']) }
APP_B = ConnectionPool.new { Redis.new(url: ENV['APP_B_PRODUCTION_REDIS_URL']) }

run Rack::URLMap.new(
  '/app-a' => Sidekiq::Pro::Web.with(redis_pool: APP_A),
  '/app-b' => Sidekiq::Pro::Web.with(redis_pool: APP_B),
)
```

However, when I start up the server (using either `foreman start` or just `rackup config.ru` I'm still seeing the bottom of the screen show that is connected to my localhost: `redis://127.0.0.1:6379/0`.

Any other ideas I can try? It's like it's just ignoring the redis_pool that I'm trying to use to connect to the remote apps. Unfortunately there's nothing really useful in the logging to help guide me in why this might be happening.

**Comment by mperham** [comment]
Print out APP_A_PRODUCTION_REDIS_URL and  APP_B_PRODUCTION_REDIS_URL.  If they don't exist, Redis defaults to what you are seeing.

**Comment by ToniRib** [comment]
They're definitely in there as the correct Heroku redis cloud urls that I would expect. I've also checked what the Redis.new calls return, and they are correctly being set up as Redis v3.3.2 clients for the given remote url.

**Comment by ToniRib** [comment]
I'm curious if using the Redis client to set up the ConnectionPool is working as expected. I've been checking out the ConnectionPool documentation (http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-c-new <- assuming this is the correct doc) and in the actual source code for initialize, it looks like the Redis client would be used as the 'spec' in this case, but the redis client doesn't respond to some of the methods given.

**Comment by mperham** [comment]
Ok, seems legit, I will try to reproduce the issue tomorrow as I have personal stuff taking the rest of the day.

**Comment by ToniRib** [comment]
Thanks! I really appreciate your help @mperham!

**Comment by mperham** [comment]
This works exactly as expected for me:

```ruby
# multiple.ru
require 'sidekiq-pro'
require 'sidekiq/pro/web'

APP_A = ConnectionPool.new { Redis.new(db: 1) }
APP_B = ConnectionPool.new { Redis.new(db: 2) }

run Rack::URLMap.new(
  '/' => Sidekiq::Web,
  '/a' => Sidekiq::Pro::Web.with(redis_pool: APP_A),
  '/b' => Sidekiq::Pro::Web.with(redis_pool: APP_B),
)
```

Run via `bundle exec rackup multiple.ru`.  Going to "/", "/a" and "/b" all show different Redis URLs in the footer, as expected, since they are using different databases.

**Comment by ToniRib** [comment]
Hmm well in that case I have no idea what I'm doing wrong. I see with your Redis.new calls you're using the `db` option instead of the `url` option that I was using so I tried switching to that. I've been using the REDISCLOUD_URL variables provided to me via our Heroku config since we're using RedisCloud as our specific addon, but I'm seeing the same thing when I start up that only the local redis URL will show up in the footer. I figured then that maybe `db` was meant to be the DATABASE_URL, but even initializing the Redis client with that has no effect.

I appreciate your help and I'm glad you were able to get it to work. Seems like it still might just be something weird with my setup. I will keep trying!

**Comment by ToniRib** [comment]
Ended out pulling it down on a different laptop and trying it and it worked with the `url` option. Very strange, I'm not sure what happened locally to cause it to work on one laptop and not another.

**Comment by mperham** [comment]
Glad you got it working. Boo to the gremlins in the system!

**Comment by ToniRib** [comment]
@mperham I'd like to reopen this with a further question. What we previously discussed in this thread got my Sinatra app connected to the correct redis instances, but while I see the correct redis data (version, uptime, connections, etc...) I don't see any information on workers, even though I know they are running and processing correctly. The workers in both apps are namespaced under 'workers' which I thought might be the issue, but adding a namespace didn't seem to help.

Here's an example of one of the app's config files:
```
unless Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 5
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 7}
    config.options[:queues] = %w(default)

    database_url = ENV['DATABASE_URL']
    if database_url
      ENV['DATABASE_URL'] = "#{database_url}?pool=10"
      ActiveRecord::Base.establish_connection
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 1}
  end
end

# Start sidekiq locally 'bundle exec sidekiq'
if Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 2
    config.redis = {url: 'redis://127.0.0.1:6379/0', size: 3}
    config.options[:queues] = %w(default)
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: 'redis://127.0.0.1:6379/0', size: 1}
  end
end
```

Attached is a screenshot of what I am seeing.
![screen shot 2017-01-06 at 12 41 14 pm](https://cloud.githubusercontent.com/assets/10429574/21730579/973e47e6-d40d-11e6-8874-7ac4e13641f0.png)

Any ideas on what to try to get the worker information flowing to this UI?

**Comment by mperham** [comment]
Could you supply a simple app which reproduces the problem?  It works for me.

**Comment by ToniRib** [comment]
Turns out it's definitely just the namespacing of workers.

I figured this out first by pointing a route from my sinatra app to a different app of mine that has no namespacing, and all the workers showed up just fine in the web UI. I then made a branch of our one our other apps that removed the worker namespacing and it then showed all the jobs just fine.

Unfortunately, I couldn't find any way to allow the Sinatra app to know about namespacing of workers in the Rails apps. It didn't seem to help adding some type of 'namespace' to anything in my code. I think the only solution left appears to be to just remove the namespacing from the 2 apps I'm trying to monitor.

**Comment by mperham** [comment]
The web UI must use the exact same Redis connection config as the workers do, including the namespace.

**Comment by ToniRib** [comment]
Unfortunately the redis config across the 2 apps is slightly differently. Is there way to specify a redis config separately for each one? I would have hoped I could pass the same variables (namespace, size, etc.) to the `Redis.new` command but its initialize method doesn't seem to take them. And I see that if I use `Sidekiq.configure_client` to specify the redis config, I can only set that once, and these redis configs have different sizes based on the app so they couldn't be **exactly** the same.

Even when I tried to set 

```
Sidekiq.configure_client do |config|
  config.redis = { namespace: 'workers' }
end
```

inside of the Sintra app (to at least match the namespace, since that is the same across both apps) the worker information wouldn't show up.

Is there a good way around this?

**Comment by mperham** [comment]
Give me the exact specifics and I can explain how to configure the UI.  Pool size doesn't matter but things like url, db and namespace must be identical between workers and UI.

**Comment by mperham** [comment]
Sidekiq processes read and write data to Redis.  If you want the UI to show that data, it needs to be configured to read from that exact same space in Redis.

**Comment by ToniRib** [comment]
**Sinatra App** 
(you can assume the ENV variables are correctly mapped to the appropriate Redis URLs, as is the username and password)
```
require 'sidekiq-pro'
require 'sidekiq/pro/web'

IMAGE_REC_PROD = ConnectionPool.new { Redis.new(url: ENV['IMAGE_REC_PRODUCTION_REDIS_URL']) }
IMAGE_REC_STAGING = ConnectionPool.new { Redis.new(url: ENV['IMAGE_REC_STAGING_REDIS_URL']) }
IMAGE_REC_REVIEW = ConnectionPool.new { Redis.new(url: ENV['IMAGE_REC_REVIEW_REDIS_URL']) }

MAIN_APP_PROD = ConnectionPool.new { Redis.new(url: ENV['MAIN_APP_PRODUCTION_REDIS_URL']) }
MAIN_APP_STAGING = ConnectionPool.new { Redis.new(url: ENV['MAIN_APP_STAGING_REDIS_URL']) }
MAIN_APP_REVIEW = ConnectionPool.new { Redis.new(url: ENV['MAIN_APP_REVIEW_REDIS_URL']) }
MAIN_APP_QA = ConnectionPool.new { Redis.new(url: ENV['MAIN_APP_QA_REDIS_URL']) }

Sidekiq.configure_client do |config|
  config.redis = { size: 1 }
end

run Rack::URLMap.new(
  '/image-rec/production' => Sidekiq::Pro::Web.with(redis_pool: IMAGE_REC_PROD),
  '/image-rec/staging' => Sidekiq::Pro::Web.with(redis_pool: IMAGE_REC_STAGING),
  '/image-rec/review' => Sidekiq::Pro::Web.with(redis_pool: IMAGE_REC_REVIEW),
  '/main-app/production' => Sidekiq::Pro::Web.with(redis_pool: MAIN_APP_PROD),
  '/main-app/staging' => Sidekiq::Pro::Web.with(redis_pool: MAIN_APP_STAGING),
  '/main-app/review' => Sidekiq::Pro::Web.with(redis_pool: MAIN_APP_REVIEW),
  '/main-app/qa' => Sidekiq::Pro::Web.with(redis_pool: MAIN_APP_QA),
)
```

**Main App (Rails, sidekiq.rb):**
```
unless Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 5
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 7}
    config.options[:queues] = %w(user_exports background default picture_post_processing)

    database_url = ENV['DATABASE_URL']
    if database_url
      ENV['DATABASE_URL'] = "#{database_url}?pool=10"
      ActiveRecord::Base.establish_connection
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 1}
  end
end

# Start sidekiq locally 'bundle exec sidekiq'
if Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 2
    config.redis = {url: 'redis://127.0.0.1:6379/0', namespace: 'workers', size: 3}
    config.options[:queues] = %w(user_exports background default picture_post_processing)

    # config.server_middleware do |chain|
    #   chain.add Sidekiq::Throttler, storage: :redis
    # end
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: 'redis://127.0.0.1:6379/0', namespace: 'workers', size: 1}
  end
end
```

**Image Rec App (Rails, sidekiq.rb):**
```
unless Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 5
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 5}
    config.options[:queues] = %w(default)

    database_url = ENV['DATABASE_URL']
    if database_url
      ENV['DATABASE_URL'] = "#{database_url}?pool=10"
      ActiveRecord::Base.establish_connection
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: ENV['REDISCLOUD_URL'], namespace: 'workers', size: 1}
  end
end

# Start sidekiq locally 'bundle exec sidekiq'
if Rails.env.development?
  Sidekiq.configure_server do |config|
    config.options[:concurrency] = 2
    config.redis = {url: 'redis://127.0.0.1:6379/0', size: 3}
    config.options[:queues] = %w(default)
  end

  Sidekiq.configure_client do |config|
    config.redis = {url: 'redis://127.0.0.1:6379/0', size: 1}
  end
end
```

I chose to use only the `Sidekiq.configure_client` in the Sinatra app since that is how the example is in the wiki and there is no actual redis server associated with that app. However, adding `namespace: 'workers'` to the redis config for that doesn't fix the issue. The queues are different so I'm not sure how to handle that. Unfortunately I didn't write either of the Rails app configs so I'm not sure exactly what decisions were made for writing these and why they are exactly the way they are.

**Comment by mperham** [comment]
This won't work.

```ruby
Redis.new(url: ENV['IMAGE_REC_PRODUCTION_REDIS_URL'], namespace: 'workers')
```

You need to create a proper namespaced Redis client:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L48

Read my blog post about Redis namespaces.  I strongly recommend against using them.

http://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by ToniRib** [comment]
Based on reading that and discussing it with my team, we are likely moving towards removing our namespaces and taking advantage of the multiple databases. One of my coworkers had the following concern about removing the redis namespace from our sidekiq configs:
```
The implication of this change is that any existing sidekiq data in Redis inside the namespace will no longer be known to the sidekiq code. We will want to make sure that all in-flight work is "drained" before deploying the updated code.
```
Is this a valid concern, and is there a good way to ensure all currently processing and scheduled jobs are processed prior to deleting the namespacing?

**Comment by mperham** [comment]
It's not obvious at first that namespacing is not supported by the plain Redis driver so I totally get where the confusion came from.

Your concern is absolutely correct, migration is non-trivial.  Most people will drain the queues as much as possible and then run a single "old" Sidekiq process to process old retries, scheduled jobs, etc for a week or two.  The rest of the Sidekiq processes can process using the new Redis config.

The alternative is a quick but much more complex migration script which de-namespaces keys and MOVEs them to the proper database within Redis but this is undocumented and unsupported.
