### ISSUE TITLE
Connection Timed out. Please suggest us regarding the configuration #3271

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3289]
We have followed exactly what have you told on (removing size: 1)https://stackoverflow.com/questions/41041194/connection-timed-out-please-suggest-us-regarding-the-configuration but still getting error .

Please suggest should we upgrade redis plan?

#3271 
should we took redistogo update version? currently it is lite

should we took sidekiq pro/premium?

Please advice us @mperham

Many thanks
Rajarshi

Ruby version:
Sidekiq / Pro / Enterprise version(s):

If relevant, please include your initializer and any error message with the full backtrace.

**Comment by mperham** [comment]
I don't have enough info to solve your problem.  Since this is a Redis timeout issue, I'd contact RedisToGo and ask if they can help you diagnose.  You should also read this:

https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud

**Comment by rajcybage** [comment]
Ok Great Thanks a Million Mike.
