### ISSUE TITLE
Very few threads created when there is some latency involved

### ISSUE THREAD

**Issue by nick-desteffen** [mperham/sidekiq#3290]
Ruby version: 2.2.2
Sidekiq / Pro / Enterprise version(s): 4.2.2 / 3.3.3 / NA

#### sidekiq.yml: https://gist.github.com/nick-desteffen/a4cd7e4ac7e233c7c9437c44ec327775

We recently moved our secondary Sidekiq server to a location that is geographically different from our Redis server.  We have noticed that this server is only creating 1-2 threads per worker process when our primary Sidekiq server (located in the same datacenter as our Redis server) is creating the same number threads per worker as defined as our concurrency.  The latency between the datacenters is around ~37ms

**Comment by mperham** [comment]
One thing I would suggest: disabling Sentinel.  I don't know how it will behave in a high latency environment.  If you just use a plain old Redis, does the system behave differently?

Change the default concurrency in your YML file from 2 to 5 and see if that causes any change.

**Comment by nick-desteffen** [comment]
Thanks Mike, we'll give it a try after the holidays.  I don't wanna rock the boat too much while most of the team is out.

**Comment by nick-desteffen** [comment]
Mike,
I finally had a chance to test our Sidekiq processes with a load and without going through Sentinel.  Unfortunately Sentinel doesn't seem to be an issue.

Here is a screenshot of the workers when going through Sentinel:
https://dl.dropboxusercontent.com/spa/a6qksjg8w5g2imd/hrcu-6q8.png

The top 3 Sidekiq processes are running on a server hosted in San Jose, connecting to our Redis master server (through Sentinel) hosted in Dallas.  The bottom 3 processes are running on a server hosted in Dallas in the same cluster as our master Redis server.

After changing the processes on `util1` to connect directly to Redis instead of going through Sentinel:
https://dl.dropboxusercontent.com/spa/a6qksjg8w5g2imd/b99m4mfm.png

Same issue.

**Comment by mperham** [comment]
I have no idea what the problem might be.  I'd check the slowlog and see if there are any anomalies.  When you start those processes with -v, are they showing a concurrency setting of 32?

**Comment by nick-desteffen** [comment]
I really think this has to do with the latency in our environment.  Maybe the hop between our workers and Redis is fine, but then when you add another hop to the DB then it starts to show.  When we queue longer running jobs (a min or 2 to complete) we don't experience this problem.  Thanks for your help @mperham
