### ISSUE TITLE
Sidekiq not working with any config other than default namespace and db for Redis

### ISSUE THREAD

**Issue by noctivityinc** [mperham/sidekiq#3292]
Im running Sidekiq 4.2.7 with Ruby 2.3.1.  No rails, just plain old ruby.  My worker file runs fine IF I don't try to use a db other than 0 with Redis or any namespace.  But if I set either a db or namespace, such as this:

```
require 'rubygems'
require 'sidekiq'
require 'httparty'

redis_uri = ENV["REDIS_URL"] || "redis://localhost:6379/2"

puts "Running redis on #{redis_uri}"

Sidekiq.configure_server do |config|
  config.redis = { url: redis_uri,  namespace: 'ping' }
end
```

Then sidekiq doesnt work.  There is nothing appearing in the logs and Im not seeing any activity on what the worker should be doing.  However, when I check the keys in Redis, I see this:

```
127.0.0.1:6379> keys ping:*
1) "ping:stat:failed"
2) "ping:processes"
3) "ping:stat:processed:2016-12-23"
4) "ping:Joshuas-MacBook-Pro.local:34567:b53c606e3736"
5) "ping:stat:processed"
6) "ping:stat:failed:2016-12-23"
```

So Redis appears to be getting some activity from Sidekiq but then nothing.

**Comment by mperham** [comment]
Can you supply a small app or script which reproduces the problem?

**Comment by mperham** [comment]
Ah, read this:

https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-initializer

**Comment by noctivityinc** [comment]
Interesting.  Thanks.  Ill give it a go.




Joshua Lippiner
.:t 704.323.5661
.:e jlippiner@noctivity.com


On December 23, 2016 at 11:14:50 AM, Mike Perham (notifications@github.com)
wrote:

Ah, read this:

https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-initializer

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mperham/sidekiq/issues/3292#issuecomment-269012213>,
or mute
the thread
