### ISSUE TITLE
Possible thread-safe issue on the mail gem, worth to add to docs

### ISSUE THREAD

**Issue by Ferdy89** [mperham/sidekiq#3295]
Ruby version: 2.2.4
Sidekiq 4.1.2 / Pro 3.3.3 / Enterprise version(s) 1.3.2

We're seeing the following error in our application:
```ruby
NameError: uninitialized constant Mail::Parsers::ContentTypeParser
```

The details about the possible root cause for this and how to solve it are being discussed in https://github.com/mikel/mail/issues/912. Seems a similar issue with `autoload` as with the AWS gem.

One of the gem's collaborators said to use
```ruby
Mail.eager_autoload!
```
to fix the issue, just like with the AWS gem. Would it be worth adding to the [Problems and troubleshooting](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting) section of the wiki?

**Comment by mperham** [comment]
Sure, add a note and link to the issue.

**Comment by Ferdy89** [comment]
Done https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#not-thread-safe-gems
