### ISSUE TITLE
Move jobs with bad JSON directly to Dead set

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3296]
Today if a job has bad JSON, it will be (a) lost in Sidekiq, (b) retried forever in Sidekiq Pro.  Instead, move jobs which throw parse errors straight to the Dead set as they must be handled manually.

**Comment by motymichaely** [comment]
@mperham Any workaround for the time being?

**Comment by mperham** [comment]
You can test and verify the quality of the data by converting it to and from JSON before sending it to Sidekiq. Aside from that there's no workaround.
