### ISSUE TITLE
Batch failing, but which worker?

### ISSUE THREAD

**Issue by HuckyDucky** [mperham/sidekiq#3297]
Ruby version: 2.1.6p336
Sidekiq / Pro / Enterprise version(s): 4.0.2 / 3.2.1 / 1.2.1

Every day I see a few batches failing. But I have no idea which Workers are associated with them.

The Error Message is always (from the Retries page):

    "\xC8" from ASCII-8BIT to UTF-8

It gives me a JID, such as:

    a0755fd58fe38e17740ede12

And they always fail while calling "on_complete":

    "complete", "HDxYosnHusr6WQ", "bulk"

How do I find out which workers these are coming from? I have lots of users in Asia-Pacific, so I'm not sure which code of mine  is trying to read a file as ASCII.

**Comment by mperham** [comment]
Can you upgrade to something newer?  Do you have a full backtrace?

**Comment by HuckyDucky** [comment]
Can definitely upgrade, I'll do that first. There is no backtrace that I can see in the Retries screen. Maybe once they become Dead.

**Comment by mperham** [comment]
You'll need to turn on backtraces. Sidekiq assumes your error service saves backtraces.

**Comment by mperham** [comment]
Any progress?
