### ISSUE TITLE
super_fetch is not discarding some jobs after successful processing

### ISSUE THREAD

**Issue by YesThatAllen** [mperham/sidekiq#3298]
Ruby version: 2.3.1  / (rails 4.2.7.1 ) 
Sidekiq / Pro / Enterprise version(s):
( Sidekiq v4.2.7 / Sidekiq Pro v3.4.1 )

[our initializer ](https://gist.github.com/YesThatAllen/b5f81dfe7a32e21c255a2f1416958f27)

Relevant gems in use:

```
# From Gemfile.lock

    # redis (3.3.2)
    # sidekiq (4.2.7)
    #   concurrent-ruby (~> 1.0)
    #   connection_pool (~> 2.2, >= 2.2.0)
    #   rack-protection (>= 1.5.0)
    #   redis (~> 3.2, >= 3.2.1)
    # sidekiq-datadog (0.3.4)
    #   dogstatsd-ruby (~> 2.0.0)
    #   sidekiq
    # sidekiq-pro (3.4.1)
    #   sidekiq (>= 4.1.5)
    # sidekiq-status (0.6.0)
    #   sidekiq (>= 2.7)
    # sidekiq-unique-jobs (4.0.18)
    #   sidekiq (>= 2.6)
    #   thor
```

The redis instance we are using is Elasticache in the same region (US-West) as the EC2 instances which are running our app. I can reproduce the issue locally on my Mac running its local `redis-server`.

We use `whenever` to generate emails which are sent to sidekiq for processing. The jobs are passed to postmarkapp for delivery. When the same emails are triggered manually, they have the same issue I'm about to describe.

Once we implemented Sidekiq pro, we saw a drastic improvement in our jobs performing small transactions to services like Zendesk/RepairShopr/Autotask/ConnectWise. However, larger jobs which are sent to Postmark are completed (an email is successfully sent) but end up getting re-run after the worker is terminated.

The jobs in question range from 350k to 4.7mb (maybe more?). Disabling super_fetch results in worse performance in our integrations, but jobs are no longer re-attempted.

Because the job is "hidden" in the web UI, only to return later, I wondered if it was related to #3294. The jobs aren't malformed or corruption in any way we can see, so this may be new.

We can't see the job in the queue until we stop the worker which picked it up for processing, but we can see that the job is placed back in the queue.

```
Dec 27 09:46:27 sidekiq.log:  2016-12-27T15:46:27.809Z 8734 TID-ou1wd3sp4 INFO: Shutting down
Dec 27 09:46:27 sidekiq.log:  2016-12-27T15:46:27.809Z 8734 TID-ou1wd3sp4 INFO: Terminating quiet workers
Dec 27 09:46:27 sidekiq.log:  2016-12-27T15:46:27.809Z 8734 TID-ou1x2qbsk INFO: Scheduler exiting...
Dec 27 09:46:27 sidekiq.log:  2016-12-27T15:46:27.910Z 8734 TID-ou1wd3sp4 INFO: Pausing to allow workers to finish...
Dec 27 09:46:29 sidekiq.log:  2016-12-27T15:46:29.712Z 8734 TID-ou1wd3sp4 INFO: Moving job from queue:sq_ip-10-92-5-144:8734:4f110c8ea59c_default back to queue:default
Dec 27 09:46:29 sidekiq.log:  2016-12-27T15:46:29.716Z 8734 TID-ou1wd3sp4 INFO: Moving job from queue:sq_ip-10-92-5-144:8734:4f110c8ea59c_mailers back to queue:mailers
Dec 27 09:46:29 sidekiq.log:  2016-12-27T15:46:29.722Z 8734 TID-ou1wd3sp4 INFO: Moving job from queue:sq_ip-10-92-5-144:8734:4f110c8ea59c_mailers back to queue:mailers
Dec 27 09:46:29 sidekiq.log:  2016-12-27T15:46:29.725Z 8734 TID-ou1wd3sp4 INFO: Moving job from queue:sq_ip-10-92-5-144:8734:4f110c8ea59c_mailers back to queue:mailers
Dec 27 09:46:29 sidekiq.log:  2016-12-27T15:46:29.727Z 8734 TID-ou1wd3sp4 INFO: Bye!
```

There is no error logged during the processing of the job. We aren't hearing reports of duplicates for other emails we send, it's just these larger summary emails.

Attempting to delete these jobs via the web-ui often results in a redis timeout error. In a test, I was able to delete 2171 smaller jobs in single request with no timeout. 

No timeout errors are logged (that I can see) when `super_fetch` is trying to run the job, and we don't have duplicate job issues with `super_fetch` disabled.

We're looking to see how else to troubleshoot the reason super_fetch isn't discarding the job at the end of its run.

**Comment by mperham** [comment]
Can you post your initializer here?  First thought is that you should raise the network_timeout from 1 to 10 when dealing with such large payloads.  I wonder if the process heartbeat is dying due to timeout.

**Comment by mperham** [comment]
Sorry I missed the initializer link!

**Comment by mperham** [comment]
Thanks for the update.  It's hard for me to remember each email so that's why I prefer to have open issues that I can refer back to. 👍 

EC2 networking can be hit or miss unless you're paying for the good instances; being in the same region means that you can still be in different data centers (i.e. a non-trivial distance).  Rails apps can have occasional very large GCs which trigger timeouts.  In other words, it's hard to diagnose timeouts and their cause.  The fact that you can reproduce the issue locally means we can discard those possibilities.

I will scan the super_fetch code on Monday and see if anything looks suspect but the size of the job should not make a difference.  Internally it is using RPOPLPUSH which should be very fast, even for a large payload.  Do you only see these job duplication problems during deployment?

**Comment by YesThatAllen** [comment]
Define good instances? here's a screenshot of our setup from AWS/Elasticache

![screenshot_2356](https://cloud.githubusercontent.com/assets/2879972/21580312/d11d5dae-cfb1-11e6-9c08-788eef4e28ab.png)

Near as I can tell, here's what happens:

The jobs is processed, and the resulting email is sent via postmarkapp. The job doesn't show in any pending/active queue (presumably because it's in a worker's private queue).

The worker doesn't seem to fully understand that the job was successful, despite the desired email being sent.

Or maybe it can't delete the job afterwards? (but why does normal sidekiq not suffer?)

In any case, when the underlying ec2 instance is terminated, the worker places the job back in to the queue.   From there, it seems the next worker picks up the job as if it was never processed.

On staging, if I stop the queue, then stop sidekiq, I can see the job put back into the queue (and it's logged.. see above `Moving job from queue:sq_ip-10-92-5-144:8734:4f110c8ea59c_mailers back to queue:mailers`)

Because sidekiq is fully stopped, I can see the job in the web-ui. Manually deleting the job via the ui will often result in a timeout logged in our https://bugsnag.com setup. (omg :heart: bugsnag).

For whatever reason, using sidekiq without super_fetch, the jobs are processed & disposed of, and we don't have any duplicate emails being sent.

**Comment by YesThatAllen** [comment]
I should point out that change we're making to stop the repeating emails is commenting out [line 35](https://gist.github.com/YesThatAllen/b5f81dfe7a32e21c255a2f1416958f27#file-initializers-sidekiq-rb-L35) in our initializer.

> # config.super_fetch!

With that line commented out, we don't see duplication of jobs.  When the line is un-commented & active, some email jobs get stuck, resulting in duplicates.

**Comment by mperham** [comment]
Job acknowledgment requires Sidekiq to push the entire job to Redis over the network which, with your jobs, can be a large payload and trigger timeouts in edge cases.  Aside from that, I don't see anything else that strikes me as a problem in the codebase.  I'm not hearing any other reports from others so I think two things might help:

1. Reduce the size of those job arguments as much as you can.  I believe you've already started this effort.
2. Let's chat more about your application at Friday HH and possibly give me access to the app codebase.  I can glance through your app worker code to make sure it all looks ok.

**Comment by mperham** [comment]
A user diagnosed a Redis edge case that can lead to dupe JIDs, #3303.

**Comment by mperham** [comment]
We determined that Allen's deploy was running `kill -9` before the TERM signal could be processed successfully, leading to this issue.
