### ISSUE TITLE
Constant Enqueue VS Enqueue Delay w/ increased Scheduled Poll Interval

### ISSUE THREAD

**Issue by dsshap** [mperham/sidekiq#3304]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.5

Hi, I have a situation where I run a lock on a worker using the `sidekiq-lock` gem. In the logs I am seeing that if the worker does not acquire a lock, then it re-enqueues the job immediately for reprocessing. This is all correct, as this is how I have written the worker. 

I am observing that is happening very often, and a specific job gets enqueued sometimes >10 times before the lock is acquired. So far this sounds reasonable - since each job communicates with external services so it can take as much as 300ms to complete (often it takes less time). 

The alternative approach I have come up with is to enqueue the job with a 0.3 second delay. In order to keep things responsive, I would also need to increase the frequency of the scheduled poll interval to less than or equal to 1 second.

Would you recommend sticking with original implementation where a job is enqueued many times before being processed or go with the alternative?

**Comment by mperham** [comment]
Looks like sidekiq-lock replicates some of the functionality in my [concurrent rate limiter](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#concurrent).  I can't support libraries I don't write; I'd suggest asking the sidekiq-lock maintainers on their recommendations.
