### ISSUE TITLE
Use /etc/sudoers to allow sudo command?

### ISSUE THREAD

**Issue by stoivo** [mperham/sidekiq#3305]
Ruby version: irrelevant
Sidekiq / Pro / Enterprise version(s): irrelevant

https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu#set-up-sudo
In the wiki it stated the you should give you deploy user sudo rights which is not in general recommended.

In /etc/sudoers which is changed with visudo you can allow one user to run only one command as root without getting prompted for password. I added it like this 
```
deployer ALL=(ALL:ALL) NOPASSWD: /bin/systemctl restart sidekiq
```

Is there any reason why i should not to this?

**Comment by mperham** [comment]
I don't feel confident enough in my sysadmin/security credentials to give any sort of feedback on sudo setup.  Perhaps ServerFault might have some wisdom.

**Comment by mperham** [comment]
Oh, I didn't write that wiki page.  While its content looks mostly ok, the sudo stuff is not something I would include.

**Comment by stoivo** [comment]
This is probably stated somewhere else as well.

How is the preferred way of restarting sidekiq on every deploy (with capistrano), and start sidekiq in boot if we would restart the container?

**Comment by stoivo** [comment]
To run `systemctl reload/restart sidekiq` don't the user need to have sudo rights?

**Comment by mperham** [comment]
I don't know, I'm not a sysadmin.  Maybe systemd supports user services which run as user X and can be controlled by user X.
