### ISSUE TITLE
Systemd production

### ISSUE THREAD

**Issue by alicjap** [mperham/sidekiq#3308]
Ruby version:2.3.3
Sidekiq / Pro / Enterprise version(s):4.2.7
same like in 
https://github.com/mperham/sidekiq/issues/3252

now starts for develop  but same error like in 3252 for production (-e production)

**Comment by mperham** [comment]
Post your config/sidekiq.yml.  Likely because you have `daemonize: true`.

**Comment by alicjap** [comment]
sidekiq.yml 
`:verbose: false
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid

production:
  :concurrency: 25
`

**Comment by mperham** [comment]
Show us your sidekiq.service file.

**Comment by alicjap** [comment]
```
[Unit]
Description=discourse sidekiq service
After=syslog.target network.target

[Service]
Type=simple
WorkingDirectory=/home/alice/ror/testside/
ExecStart=/home/alice/.rvm/bin/systemd_bundle exec sidekiq -e production -C config/sidekiq.yml

User=alice
Group=alice
UMask=0002
Restart=on-failure
RestartSec=10
StandardError=syslog

[Install]
WantedBy=multi-user.target
```

**Comment by mperham** [comment]
What happens when you run `/home/alice/.rvm/bin/systemd_bundle exec sidekiq -e production -C config/sidekiq.yml` manually?

**Comment by alicjap** [comment]
i was trying to set path without wrapper but i didnt help.

**Comment by mperham** [comment]
I don't understand.

**Comment by alicjap** [comment]
i used wrapper to take control over ruby version:
`rvm wrapper 2.3.1 systemd bundle`

**Comment by mperham** [comment]
You aren't answering my question.

What happens when you run /home/alice/.rvm/bin/systemd_bundle exec sidekiq -e production -C config/sidekiq.yml manually?  What's the output?

**Comment by alicjap** [comment]
im sorry, here you are:


```
alice@alice-X550JK:~/ror/testside$ /home/alice/.rvm/bin/systemd_bundle exec sidekiq -e production -C config/sidekiq.yml
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
2017-01-07T21:29:35.223Z 17533 TID-gsj768rtk INFO: Running in ruby 2.3.3 (2016-11-15 revision 56796) [x86_64-linux]
2017-01-07T21:29:35.224Z 17533 TID-gsj768rtk INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-01-07T21:29:35.224Z 17533 TID-gsj768rtk INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-01-07T21:29:35.224Z 17533 TID-gsj768rtk INFO: Booting Sidekiq 4.2.7 with redis options {:url=>nil}
2017-01-07T21:29:35.224Z 17533 TID-gsj768rtk INFO: Starting processing, hit Ctrl-C to stop
```

**Comment by mperham** [comment]
Looks like it works fine when you start it manually.  My guess is that you didn't tell systemd to reload the .service file after editing it, using `sudo systemctl daemon-reload`.

**Comment by alicjap** [comment]
i did it many times

**Comment by mperham** [comment]
I have no more advice, good luck.

**Comment by alicjap** [comment]
thx

**Comment by nhannguyen** [comment]
I have the same issue and solved it by using sth like
`ExecStart=/home/deploy/.rvm/gems/ruby-2.3.3/wrappers/bundle exec sidekiq -e production -C config/sidekiq.yml`

Note that I change **bin** to **wrappers**

**Comment by chongfai13** [comment]
> I have the same issue and solved it by using sth like
> `ExecStart=/home/deploy/.rvm/gems/ruby-2.3.3/wrappers/bundle exec sidekiq -e production -C config/sidekiq.yml`
> 
> Note that I change **bin** to **wrappers**

Thanks nhannguyen, I manage to solve it.

**Comment by sachingevariya** [comment]
> I have the same issue and solved it by using sth like
> `ExecStart=/home/deploy/.rvm/gems/ruby-2.3.3/wrappers/bundle exec sidekiq -e production -C config/sidekiq.yml`
> 
> Note that I change **bin** to **wrappers**

Thanks, @nhannguyen, this helped me a lot

**Comment by urchymanny** [comment]
> I have the same issue and solved it by using sth like
> `ExecStart=/home/deploy/.rvm/gems/ruby-2.3.3/wrappers/bundle exec sidekiq -e production -C config/sidekiq.yml`
> 
> Note that I change **bin** to **wrappers**

How about rbenv users?
