### ISSUE TITLE
NoMethodError: undefined method on initial jobs

### ISSUE THREAD

**Issue by TheCorp** [mperham/sidekiq#331]
So, not entirely sure about this issue but maybe you can help us track down the cause. I went through the existing open and closed issues and haven't found anything yet that seems related to this. 

Basically right when we start Sidekiq workers up (on Heroku) the first few jobs always seem to error out with "NoMethodError" or "uninitialized constant" errors. For example:

NoMethodError: undefined method `initial_count_for' for #ActiveRecord::Associations::AliasTracker:0x000000064d68a8
NameError: uninitialized constant OneOfOurModels::HttpHelper
etc

initial_count_for is definitely a method in ActiveRecord and HttpHelper is a ruby library that should always be available. There are other instances of this if you want more examples. Basically it seems like the full Rails/Ruby environment hasn't been loaded into memory for the thread processing this Job? 

After a minute (or less) all the jobs seem to process just fine so it seems like once things are warmed up and everything is in memory all of the jobs seem to have access to all of the functions that get mixed in. Here's our setup:

Ruby 1.9.2p290
Rails 3.2 
Heroku Cedar

Let me know if this makes any sense or if you need more details about our config.

**Comment by akhilesharora** [comment]
{"class":"PostmanWorker","args":["lmd"],"retry":true,"queue":"critical","jid":"04a7ac2fa0b59a792c6d72e4","created_at":1456753992.873091,"enqueued_at":1456754044.180575,"error_message":"undefined method `perform' for #<PostmanWorker:0x007fd28ce293a0 @jid=\"04a7ac2fa0b59a792c6d72e4\">","error_class":"NoMethodError","failed_at":1456754009.4919481,"retry_count":1,"retried_at":1456754044.182247}

**Comment by chickensmitten** [comment]
@biznickman did the arbitrary ActiveRecord call solve your problem? I am facing a problem similar to yours. Unfortunately, the ActiveRecord call in sidekiq initializer did not work for me.

In config/initializers/sidekiq.rb, I added:
`User.first.blank?`

Rails 4.2.1
