### ISSUE TITLE
Possible to see exact schedule time when going into job details

### ISSUE THREAD

**Issue by desheikh** [mperham/sidekiq#3310]
When looking at the details for a job that is scheduled in for example 4 hours 59 minutes, the job details will show show 4 hours.
While rounding down the number isn't an issue in the list view, it would be nice if the details page actually showed the exact time.

![image](https://cloud.githubusercontent.com/assets/27354/21752468/9c56b1ce-d5a6-11e6-8949-39bcaf4e729b.png)

**Comment by mperham** [comment]
Mouse over and look at the tool tip.

**Comment by desheikh** [comment]
Thanks for the quick response @mperham . Looks like this doesn't work for the latest Sidekiq:
Ruby version: 2.3.3
Sidekiq v4.2.7

Not sure if it's a Pro only feature. I can see it work on the Sidekiq at work:
Sidekiq v3.3.4 / Sidekiq Pro v2.0.1

**Comment by mperham** [comment]
It's not a Pro feature, likely regressed.
