### ISSUE TITLE
Can I enqueue jobs from within an exception handler?

### ISSUE THREAD

**Issue by ericgross** [mperham/sidekiq#3315]
Ruby version: Latest
Sidekiq / Pro / Enterprise version(s): None

Is it OK to enqueue new jobs (to send a notification to Slack) from within one of these?

```
  config.error_handlers << proc do |ex, ctx_hash|
    SidekiqTools.send_slack_error_notifications(ctx_hash: ctx_hash, ex: ex)
  end

```

If not, is it OK to run a job?

It seems that enqueuing a job causes the worker to crash while running them inline does work.

**Comment by mperham** [comment]
I would not exercise such a large portion of Sidekiq's APIs within the
error handler.  You don’t know if Sidekiq is useable.  The error could be
related to Redis, in which case it won’t work.

**Comment by ericgross** [comment]
Do you agree that running a job using `.new.perform` would be less likely to break?

**Comment by mperham** [comment]
Absolutely.
