### ISSUE TITLE
undefined local variable or method `poll_path' for

### ISSUE THREAD

**Issue by chenzhenzhen1992** [mperham/sidekiq#3317]
Ruby version: 2.2.0
Sidekiq / Pro / Enterprise version(s): 4.0.0

If relevant, please include your initializer and any error message with the full backtrace.
P: undefined local variable or method `poll_path' for
C:  require 'sidekiq/web'
     Sidekiq::Web.set 'views', File.join(Rails.root, 'app', 'views', 'sidekiq')
the above added to my routes.rb and I copy all .erb file in web/views to app/views/sidekiq in my app
how do I  do that, thanks!

**Comment by mperham** [comment]
Upgrade to latest

**Comment by chenzhenzhen1992** [comment]
resolved, thanks!
