### ISSUE TITLE
Review official Ruby and Rails version support

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3318]
For Sidekiq 5.0, determine minimum supported Ruby and Rails versions.  We currently support a minimum of Ruby 2.0 and Rails 3.2.

**Comment by mperham** [comment]
I'm in favor of bumping that to Ruby 2.1 and Rails 4.0.  Neither Ruby 2.0 or Rails 3.2 are officially supported anymore by their respective teams.

Ruby 2.0 was released in Feb 2013, making it 4 years old.  Rails 3.2 was released in Spring 2012, making it 5 years old.

**Comment by mperham** [comment]
Several major gems have recently added a minimum version of Ruby 2.2 due to the symbol GC feature.  I'm thinking that if Rails 5.0 requires a minimum of Ruby 2.2.2, maybe we should do the same and skip Ruby 2.1 altogether.

**Comment by mathieujobin** [comment]
I wonder if we should yank '5.0 -> 5.0.3' which can be installed on ruby 2.1 but will fail on boot
