### ISSUE TITLE
UI redesign idea

### ISSUE THREAD

**Issue by jcoyne** [mperham/sidekiq#3319]
<img width="1197" alt="screen shot 2017-01-17 at 10 21 31 am" src="https://cloud.githubusercontent.com/assets/92044/22029006/c8fc534c-dc9e-11e6-875a-510950651c03.png">

This status bar makes all tabs appear as equal, but the first two items are counters and the the rest are links to other pages.  It would be helpful to visually distinguish the counters from the navigation items.

I think this would help people who are confused such as https://github.com/mperham/sidekiq/issues/2760

**Comment by mperham** [comment]
This is a fine idea but I have no design skills and therefore have no desire to implement anything myself.  PRs are always welcome with improvements.
