### ISSUE TITLE
Raising an exception within a worker silently fails

### ISSUE THREAD

**Issue by axsuul** [mperham/sidekiq#332]
Would raising an exception within a worker cause it to retry? Right now, the behavior appears to be that it silently fails. The job doesn't seem to get placed in the retry queue and the "processed" and "failed" count increment by one. This is what my worker code looks like.

``` ruby
module Worker
  class Foo
    include Sidekiq::Worker
    sidekiq_options queue: :critical, retry: true

    def perform
      sleep 10
      raise Exception, "Please please please!"
    end
  end
end
```

Queue the worker

``` ruby
Worker::Foo.perform_async
```

**Comment by sekmo** [comment]
Is this still valid? Does it mean that if a StandardError or Exception is raised, we will just see an increment of 1 to the Processed and Failed counters? Where I can read about this in the documentation?
