### ISSUE TITLE
Tripping over parameters

### ISSUE THREAD

**Issue by iamvery** [mperham/sidekiq#3320]
Ruby version: N/A (but the project I'm working with is 2.2.3)
Sidekiq / Pro / Enterprise version(s): Free 3.3.2

**Note:** I'm a pretty light Sidekiq user, so I beg your forgiveness if I'm ignorant in this discussion.

## Simple Arguments
In my experience, one of the biggest tripping points of background process libraries in Ruby is making sure serialization works correctly. People necessarily forget the gritty details for job serialization and design their works as they would any object. This, of course, leads to problems when workers are serialized to the jobs database and for later run. The solution is generally to tote around the tribal knowledge that job calls are special and must be serializable to JSON. The Sidekiq Wiki [notes](https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple) that:

> The arguments you pass to perform_async must be composed of simple JSON datatypes: string, integer, float, boolean, null, array and hash.

## Stricter Enforcement?
So I'm curious, why not enforce this at call time? I feel that an error for "invalid" arguments might offer a better development experience. On my current project, for example, some design choices were made about a worker that passed all tests locally and on CI only to fail in production. This is because development, test, etc. never actually run a job through the full Sidekiq stack.

All that said, I imagine there are probably exceptional cases that prevent Sidekiq from being so heavy-handed with enforcing arguments. Might it make sense as a configuration option? Or perhaps there is a way to design a set of tests that _do_ exercise the stack for confidence in your worker design?

## ❤️
Thank you for taking the time to read this and your consideration. And thank you so much for the untold hours of time and care you've given to produce an excellent tool that helps many folks be productive! You are very appreciated 🙂

**Comment by mperham** [comment]
You make a fine point.  I've considered this in the past.  It would add a fair amount of overhead to the client API since we'd have to marshal/unmarshal everything and can get pretty messy.

One thing you can do is turn on [Sidekiq::Testing's inline mode](https://github.com/mperham/sidekiq/wiki/Testing#testing-workers-inline) when in development.  This API does a full round-trip via JSON and so it does exercise argument marshalling.

```ruby
if Rails.env.development?
  require 'sidekiq/testing'
  Sidekiq::Testing.inline!
end
```

Of course this excludes actually using Sidekiq in development.  Other ideas to improve this area are welcome.

**Comment by iamvery** [comment]
Thank you so much for the fast response! ❤️
