### ISSUE TITLE
Question about Batch callback behavior after calling invalidate_all

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#3321]
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s): Pro 3.4.1

I've got a behavior question that doesn't seem to be answered in the wiki.  As described here - https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch - one can cancel a batch by calling `invalidate_all` on the batch, and early terminating the workers based on the `valid_within_batch?` method.

With that approach, what is the expected behavior for the callbacks?  Technically all of the workers in the batch will have run without error.  So does the success callback fire?  Or is that prevented by the `invalidate_all` call?

My preferred behavior would be that the complete callback runs, but the success callback does not.  But in any case I'd like to be clear on what the behavior is, and ensure that it's documented and enforced by Sidekiq Pro.

**Comment by mperham** [comment]
Both the complete and success callbacks should run.  When you invalidate, the job skips the application code and early return means success.

**Comment by petergoldstein** [comment]
@mperham Can the fact that the batch was invalidated be detected in the callback?

**Comment by mperham** [comment]
Unfortunately I don't believe so at the moment.  A reasonable feature request though.

**Comment by petergoldstein** [comment]
@mperham Ok.  Would love to see that as a feature.  Can we get it on the road map?  I can't really implement batch cancellation until I can block the execution of the logic in my success callback.

**Comment by mperham** [comment]
Sure, do you want to open an issue and I'll comment on the API?
