### ISSUE TITLE
When all periodic jobs are removed the previous jobs still show up in the Web UI

### ISSUE THREAD

**Issue by leklund** [mperham/sidekiq#3322]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.4 / 3.3.2 / 1.3.2

1. Register a periodic job and start the server
2. Stop the server and remove that job or bypass the `cron.periodic` block entirely
3. restart the server
4. see that the job still appears in the cron tab

The jobs don't run so it's not a major issue but it is confusing to see them in the interface.
It seems that it's only deleting the old periodic jobs from redis when there is at least one entry in the periodic jobs list.

**Comment by mperham** [comment]
Ah, I see.  Yep, an empty job list skips the periodic subsystem completely so the data is not updated.
