### ISSUE TITLE
[Ent] Concurrent limiter does not expire lmtr-cfree-* key

### ISSUE THREAD

**Issue by krasnoukhov** [mperham/sidekiq#3323]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.7 / 3.4.1 / 1.4.0

Can be easily reproduced with simple concurrent limiter:

```ruby
limiter = Sidekiq::Limiter.concurrent("test", 1, { ttl: 60 })
limiter.within_limit { puts "lol" }

# Expires correctly, as well as other lmtr-* keys
Sidekiq::Limiter.redis { |r| r.ttl("lmtr-c-test") }

# Returns -1, does not expire
Sidekiq::Limiter.redis { |r| r.ttl("lmtr-cfree-test") }
```

I'm not sure if this is an actual key leak, but let me know what you think anyway

**Comment by mperham** [comment]
Yep, tracked it down.  The key understanding is that when Redis sees that a list has been emptied, it **deletes** the list.  This has been a major source of subtle bugs in my Redis code for years unfortunately.

cfree holds the list of available tokens.  Once all tokens are in use, the list is empty and deleted, losing the ttl.  Once unlocked, the lock is returned to the list, implicitly recreating the list but with no expiry.

**Comment by krasnoukhov** [comment]
Ok thanks for looking into it. Do you think calling `expire` after token is returning would work?

**Comment by mperham** [comment]
Correct, that's the immediate fix.  I'll also develop a quick migration script to expire any existing data.

**Comment by krasnoukhov** [comment]
Thanks! Sounds good.

We recently noticed that default limiter expiration is too much for our use case, so this is a script I used to "migrate" expiration to a shorter time window for all limiters. Sharing because it might be useful:


```ruby
TTL = 48 * 60 * 60
Sidekiq::Limiter.redis do |redis|
  set = Sidekiq::LimiterSet.new
  set.each do |limiter|
    name = limiter.name
    keys = case limiter.type
    when :bucket
      ["lmtr-b-#{name}"]
    when :concurrent
      ["lmtr-c-#{name}", "lmtr-cused-#{name}", "lmtr-cfree-#{name}", "lmtr-cpend-#{name}"]
    else []
    end

    keys.each do |key|
      redis.expire(key, TTL)
      puts "Expired #{key}"
    end
  end
end
```

**Comment by mperham** [comment]
Since used and pend are normally empty, they shouldn't be much of a leak concern.  I would do something like:

```ruby
expiry = 48.hours.to_i; Sidekiq::Limiter.redis { |c| c.scan_each(match: "lmtr-cfree-*") { |key| c.expire(key, expiry) } }
```

**Comment by mperham** [comment]
Thank you for your detailed report!  Your strong detective work makes for a quick fix.

**Comment by krasnoukhov** [comment]
Haha thanks. I'm glad it fixed now. Is there a way for us to use sidekiq-ent HEAD to test this?

**Comment by mperham** [comment]
Unfortunately not.  You can run that script now to expire existing data and run it again once 1.5.2 is out.
