### ISSUE TITLE
Is it possible to customize the Web UI?

### ISSUE THREAD

**Issue by joshuamcginnis** [mperham/sidekiq#3324]
We're using Pro and would like to know if there is a formally accepted way to modify the web UI. In particular, we'd like to add some additional meta data to each scheduled job from the schedule jobs tab. 

My thanks in advance.

**Comment by mperham** [comment]
The job details page has an "Extra" row which contains any job attributes that aren't part of Sidekiq's core.  You can stuff any old data into a job and it will appear there, e.g.

```ruby
SomeWorker.set(customer_key: "acmecorp").perform_async(args)
```

And the UI will show `"customer_key" => "acmecorp"`

**Comment by joshuamcginnis** [comment]
Thanks!
