### ISSUE TITLE
Document result of scheduling in the past

### ISSUE THREAD

**Issue by z5h** [mperham/sidekiq#3325]
In the documentation, there is no mention of what will occur if something is scheduled to occur in the past. e.g. `MyWorker.perform_at(3.hours.ago, 'mike', 1)`  
https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs

Will it be run at all? Is this an error? Is the behaviour undefined?

In the code, we see there is an optimization so that such jobs are enqueued immediately.
https://github.com/mperham/sidekiq/blob/40f72c643ee16d44f87ca8ff56893de18fefcac5/lib/sidekiq/worker.rb#L72
Is this behaviour guaranteed? If yes, can it be clarified in the documentation?

Thanks.

**Comment by mperham** [comment]
Just added a note about it.

**Comment by dungpham1804** [comment]
@mperham any update on this issue ?

**Comment by tejasbubane** [comment]
For anyone else like me who stumbles here, this is documented in the [wiki for scheduled jobs](https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs):

> Jobs which are scheduled in the past are enqueued for immediate execution.
