### ISSUE TITLE
Feature Request: Expose Cancelled Batch Status to Callbacks

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#3326]
This is a feature request following up on the discussion in issue #3321 .  

When a batch is cancelled using `invalidate_all` and the cancel pattern suggested in the wiki is used, both the success and complete callbacks are fired.  But from the callback code it is currently not possible to determine whether the batch completed normally or if it was cancelled.  This makes clean cancellation impossible.

We'd like to be able to see whether a batch was cancelled from the callbacks.  That would allow the callback method to change behavior based on whether the batch was cancelled or proceeded to completion without cancellation.  

The simplest approach would probably be to introduce a 'cancelled' value for the status with which the callback is invoked.  But alternate approaches (passed values in the options, etc.) could work as well.  @mperham may have ideas here.

**Comment by mperham** [comment]
Thanks for opening the issue.  Here's a possible API:

```ruby
status.invalidated? # => Indicates if one or more jobs in batch were invalidated
```

`invalidate_jids` can invalidate one or more jobs.  `invalidate_all` will invalidate all of them.  Do you think it's important to be able to tell the difference?

Also keep in mind that invalidation is racy - a job can be executed before it can be invalidated.  This is one reason why I advise customers to track the batch work themselves.  Only they know when a job has finished from the application's perspective.  Sometimes if one job has been executed, the batch can't be invalidated anymore.  lf none of this matters for your use case, the API should be sufficient.  WDYT?

**Comment by petergoldstein** [comment]
Thanks Mike.  That API would be fine for our use case.

We view the batch as a totality - jobs are loaded at creation and it's all or nothing.  All of our jobs within a batch are designed to be idempotent, so one can restart the batch easily.  There's just a bunch of callback logic that we want to handle differently - basically the on_success callback assumes that everything ran correctly and, if it didn't because it was invalidated, we want to know that and act accordingly.

I'm also aware that invalidation can be racy.  In our particular circumstance that's unlikely to be an issue.  The only batches we're likely to want to cancel are ones containing long running jobs (potentially 1 hour+) or large, large numbers of jobs.  In these circumstances such race conditions are unlikely to come into play, and we accept that if they do we'll accept the cost of re-running the batch.

**Comment by mperham** [comment]
3.4.2 is out with your API!
