### ISSUE TITLE
Queues are not URI escaped

### ISSUE THREAD

**Issue by betesh** [mperham/sidekiq#3327]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): sidekiq 4.1.4, sidekiq-ent 1.3.2

I created a queue with special characters, and when I try to delete it, the generated URL has invalid characters.  The delete button's link is generated [here](https://github.com/mperham/sidekiq/blob/v4.1.4/web/views/queues.erb#L20), and it is not URI-escaped.

**Comment by mperham** [comment]
You should be able to use the API to delete it for now. Will fix in the next release.
