### ISSUE TITLE
Overwrite default Database url per queue?

### ISSUE THREAD

**Issue by nas887** [mperham/sidekiq#3328]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

If relevant, please include your initializer and any error message with the full backtrace.

We run multiple sidekiq queues on Heroku with dedicated dynos per queue. Procfile is pasted below: 

```
web: bin/start-pgbouncer-stunnel bundle exec unicorn -p $PORT -c ./config/unicorn.rb
sidekiq_critical: bundle exec sidekiq -q critical
sidekiq_notifications: bundle exec sidekiq -q notifications
sidekiq_integrations: bundle exec sidekiq -q integrations
sidekiq: bundle exec sidekiq -C config/sidekiq.yml
```

Our initializer is listed as so: 

require 'sidekiq'
require 'sidekiq-status'

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
  end
end
```
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Throttler
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
  end
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end

  sidekiq_concurrency = config.options[:concurrency]
  pool_size = ENV['SIDEKIQ_DB_POOL'] || sidekiq_concurrency

  database_url = ENV['DATABASE_URL']
  if database_url
    ENV['DATABASE_URL'] = "#{database_url}?pool=25"
  end
end

Sidekiq.remove_delay!
```

As far as I understand it, this initializer defines the database url for each instance of sidekiq. 

Is there a way to overwrite the database connection in one set of dynos? For instance in my integrations queue? Can I use s propery like :database_url: in a specific .yml file and use the -C flag? 

Thank you.

**Comment by mperham** [comment]
Generally you use something like the apartment gem if you want to dynamically change databases/schemas.

https://github.com/influitive/apartment-sidekiq#apartmentsidekiq
