### ISSUE TITLE
Question: Add a queue name programmatically.

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [mperham/sidekiq#3329]
Hi Mike,

Sorry if this is not the right medium. Is there a way for me to add a queue name via the API rather than through sidekiq.yml?

Regards,
Alex

**Comment by mperham** [comment]
Nope.  The process is configured through CLI or config.yml only.

**Comment by jonhyman** [comment]
If you absolutely needed this, you could write your own `Fetcher` that pulls its queues from an API.
