### ISSUE TITLE
Wait for the end of transactions before adding jobs to the queue

### ISSUE THREAD

**Issue by Dorian** [mperham/sidekiq#3330]
Ruby version: 2.3.3
Rails version: 5.0.0
Sidekiq version: 0.7.2

If a transaction changes the model, the sidekiq job could be fired and executed before the transaction ends, thus getting on old state of the model while the transaction is not finished.

```ruby
class Show < ActiveRecord::Base
  after_commit(on: :update) do
    p previous_changes
  end

  def calculations
    sleep 10
  end
end

show = Show.create!(name: 'The Show', description: 'The Description', artist: 'The Artist')

Show.transaction do
  show.update!(name: 'Another Show')
  show.delay.send_ticket_confirmation
  show.calculations
end
````

Full template for the example: https://gist.github.com/Dorian/3cca25378419922a4405bf9d945b8512

A very simple reduction would be:

```ruby
class Show < ActiveRecord::Base
end

fork do
  show = Show.create!(name: 'The Show')

  Show.transaction do
    puts "---> transaction start"
    show.update!(name: 'Another Show')
    sleep 3
    puts "---> transaction end"
  end
end

fork do
  10.times { |i| p i, Show.last; sleep 1 }
end
```

Which is gonna print something including:

```ruby
---> transaction start
#<Show id: 1, name: "The Show">
---> transaction end
#<Show id: 1, name: "Another Show">
```

Full example: https://gist.github.com/f4740c979b0a5cad3552116570c9ca83

What do you think? I have a 5 seconds delay for now because sending any job to sidekiq because of that.

**Comment by mikegee** [comment]
This seems like it should be the application's responsibility. Changing the behavior like you suggest would likely break a bunch of applications that don't expect Sidekiq to be concerned about ActiveRecord transactions.

**Comment by Dorian** [comment]
@mikegee it could an option then?

**Comment by mperham** [comment]
You need to use after_commit to make work happen upon commit.
