### ISSUE TITLE
Defining a Sidekiq::Worker before requiring Sidekiq causes NoMethodError

### ISSUE THREAD

**Issue by Ferdy89** [mperham/sidekiq#3333]
Ruby version: 2.2.4
Sidekiq 4.1.2

```ruby
require 'sidekiq/worker'

class MyWorker
  include Sidekiq::Worker

  sidekiq_options queue: 'normal'
end

# NoMethodError: undefined method `default_worker_options' for Sidekiq:Module
#         from /sidekiq-4.1.2/lib/sidekiq/worker.rb:105:in `get_sidekiq_options'
#         from /sidekiq-4.1.2/lib/sidekiq/worker.rb:93:in `sidekiq_options'
#         from (irb):6:in `<class:MyWorker>'
```

However, changing the `require 'sidekiq/worker'` to just `require 'sidekiq'` makes the code above work as expected.

This felt like unexpected behavior to me. It seems to me like `worker.rb` should be requiring the global `sidekiq` the same way it requires `sidekiq/cli`. If so, I'd be happy to make a PR for it.

**Comment by mperham** [comment]
It is expected that you are running within Bundler, where 'sidekiq' is automatically required for you when the Bundler environment is booted.  If you are not, you must require 'sidekiq' before using any APIs.
