### ISSUE TITLE
Docs for custom middleware missing how to test, e.g. in external libraries

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#3334]
Ruby version: Any supported
Sidekiq / Pro / Enterprise version(s): Any

Issue: Missing documentation on how to test server middleware.

I haven't found a good way to test adding options to the middleware chain either in the Sidekiq source or other repos.  I admit I haven't read everything yet, but I've put in some effort.

Is there perhaps a way to test setting these options that I may have overlooked?  Would you recommend using [`Sidekiq::Testing`](https://github.com/mperham/sidekiq/wiki/Testing#testing-server-middleware) for this scenario?

Details:

I have a PR in [attentive_sidekiq](https://github.com/twonegatives/attentive_sidekiq/pull/4#discussion_r97640205) in which I want to be able to configure the server middleware with options as below:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add SidekiqMiddleware, option1: 1, option2: 2
  end
end
```

and that `SidekiqMiddleware` Is something like

```ruby
class SidekiqMiddleware
  def initialize(options = {})
    Sidekiq.options[:option1] = options.fetch(:option1) { Sidekiq.options.fetch(:option1) { :default1 } }
    Sidekiq.options[:option2] = options.fetch(:option2) { Sidekiq.options.fetch(:option2) { :default2 } }
  end

  def call(worker, msg, queue)
    process_before(msg)
    yield
  ensure
    process_after(msg)
  end
end
```

and I'm not sure how to test that I can set the value 
- via the sidekiq.yml, 
- passing an option when inserting the middleware
- or fallback to a default value.  

Specifically, how to initialize the current middleware, set it aside, re-initialize it, test that, then restore the original?

And is storing options in Sidekiq.options a bad idea? And with string vs. symbol keys?

A somewhat-related initialization question-- the attentive_sidekiq gem wants to start a Concurrent::TimerTask when in server mode, so, on require, it runs `Concurrent::TimerTask.new { process_things }.tap {|task| task.add_observer(CanObserve) }.execute if Sidekiq.server?`, but that seems to me it should be in some server initializer.

**Comment by mperham** [comment]
You test the middleware like so:

```ruby
foo = Foo.new(a: 1, b: 2)
foo.call(...)
```

You cannot test sidekiq.yml or inserting.  sidekiq.yml options is not officially supported, only configuring the middleware via initializer.

**Comment by bf4** [comment]
@mperham Thanks for the quick reply. 

So, we can rely on `chain.add SidekiqMiddleware, option1: 1, option2: 2` being passed to `SidekiqMiddleware.new` as a hash, so that the signature should be `def initialize(options = {})`? And that we should moreover not test the state of an already initialized middleware?

And you are strongly discouraging storing middleware configuration in `Sidekiq.options`, which means also discouraging getting them from sidekiq.yml.  That's very helpful, thanks! :)

**Comment by mperham** [comment]
Correct.  I've never documented using sidekiq.yml.  This is all I've written and support:

https://github.com/mperham/sidekiq/wiki/Middleware#server-side-middleware
