### ISSUE TITLE
Official support for adding tabs to web-ui?

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#3335]
Ruby version: Any
Sidekiq / Pro / Enterprise version(s): Any

A number of userland sidekiq gems add tabs to the web ui.  I was looking at one and noticed it didn't use pagination. So, I went looking for how to add it, and didn't find any docs on it, besides just reading the sidekiq source code.

Is adding tabs to the sidekiq web-ui, especially as part of a custom middleware, officially supported?

**Comment by mperham** [comment]
Yes, adding tabs is supported.  It's not documented well but it's used by a lot of gems, including Pro and Enterprise, so it's supported.

**Comment by bf4** [comment]
@mperham Ok, I'll see if I can figure it out before someone else bestows documentation :)

**Comment by mperham** [comment]
Should be as simple as:

```ruby
class Myapp::Web
    ROOT = File.expand_path('../../../../web', __FILE__)

    def self.registered(app)
      app.get "/myapp" do
          render(:erb, File.read("#{ROOT}/views/myapp.erb"))
      end

      app.tabs['Myapp'] = 'myapp'.freeze
  end

end

::Sidekiq::Web.register Myapp::Web
```

**Comment by bf4** [comment]
@mperham I think with the pagination helper it would be as below, though my code actually uses a 'hash' type, so I can't use it :(

```ruby
app.get "/myapp" do
  @count = (params['count'] || 25)
  (@current_page, @total_size, @myappthings) = app.page("myapp-rediskey", params['page'], @count, reverse: true)
  @myappthings = @myappthings.map {|redis_value| MyApp.new(redis_value) }
  render(:erb, File.read("#{ROOT}/views/myapp.erb"))
end
```

as long as `"myapp-rediskey"` is a list or sorted set.

I tried adding a hash condition to the Paginator just for funsies, even though there's obvious performance implications

```ruby
        when 'hash'
          total_size = conn.hlen(key)
          keys = conn.hkeys(key)[starting...(ending > total_size ? total_size : ending)]
          items = conn.hmget(key, keys)
          [current_page, total_size, items]
```
