### ISSUE TITLE
SSL certificate verification failed

### ISSUE THREAD

**Issue by matthiassiegel** [mperham/sidekiq#3336]
Ruby version: 2.3.3
Sidekiq version: 4.2.9
Rails 4.2.7.1
macOS Sierra

I'm trying to track down an issue with SSL certificate verification. When I just work in Rails (e.g. on the console), I can interact with AWS just fine (e.g. API calls on buckets), using the `aws-sdk` gem. If the exact same code runs in a Sidekiq job, they always fail with SSL verification errors like `Seahorse::Client::NetworkingError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`. This only affects local development environment.

Since that error doesn't happen on the console, I'm assuming Ruby has been built with correct OpenSSL references. I was therefore wondering if Sidekiq or its dependencies perhaps use their own references to CA bundle paths, or if there is any possibility that Sidekiq's SSL settings could differ from Ruby's.

Thanks

**Comment by mperham** [comment]
Sidekiq has nothing to do with SSL.  If there's a problem, it's not in Sidekiq.
