### ISSUE TITLE
SuperFetch copies jobs into wrong queue if queue name includes underscore

### ISSUE THREAD

**Issue by jsmilani** [mperham/sidekiq#3339]
Ruby version: 2.1.2
Sidekiq / Pro / Enterprise version(s): sidekiq-pro-3.4.2

SuperFetch attempts to copy the dead jobs from one queue back to the original but if the queue name included an underscore the destination queue name gets mangled because it only uses the last component (ie. 'source_service' becomes 'service').

sidekiq-pro-3.4.2/lib/sidekiq/pro/super_fetch.rb:173
`(*_, q) = priv.split("_")`

This will cause the priv value "queue:localhost.local:54368:c686d9bc76f3_source_service" to become 'service' instead of the expected name, 'source_service'.

**Comment by jsmilani** [comment]
I tested `q = priv.slice(/:[^:_]+_([^:]*)$/, 1)` as a substitute for line 173 and it seemed to fix the problem. I am sure there is a more concise alternative but I wanted to offer a solution.

**Comment by mperham** [comment]
I'm think this will work:

```diff
-              (*_, q) = priv.split("_")
-              while conn.rpoplpush(priv, "queue:#{q}")
+              (_, _, *q) = priv.split("_")
+              while conn.rpoplpush(priv, "queue:#{q.join("_")}")
```

WDYT?

**Comment by jsmilani** [comment]
That still strips off the first component from the queue name, but `(_, *q) = priv.split("_")` seems to work.

**Comment by mperham** [comment]
Nope, the private queue name is sq_$identity_$queuename so we need to trim the first two parts.

**Comment by jsmilani** [comment]
oh, I must have sanitized my example too much. I just tested with my actual host name and it works. You are right.

**Comment by mperham** [comment]
Fix is in master.  I'll release 3.4.3 tomorrow.  Thank you!
