### ISSUE TITLE
super_fetch not respecting paused queues in production-like environment

### ISSUE THREAD

**Issue by azach** [mperham/sidekiq#3341]
Ruby version: 2.1.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.7 / Pro 3.4.1

Jobs are continuing to process when a queue is paused in staging/production environments -- however, it seems like the pause is respected when I run sidekiq locally. Here's a gif of this in action:

![](http://g.recordit.co/5zsniTbyOr.gif)

Not sure what other information would be valuable in helping debug this.

Sidekiq initializer:

```ruby
Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'], namespace: 'sidekiq', size: 1 }
end

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!

  config.redis = { url: ENV['REDIS_URL'], namespace: 'sidekiq' }

  proc_name = File.basename(config.options[:pidfile], '.pid')
  job_name = "public-#{proc_name}"

  config.server_middleware do |chain|
    chain.add Sidekiq::Throttler, storage: :redis
    chain.add Sidekiq::Middleware::Server::Prometheus, job_name: job_name
    # don't want or need start/done/fail log message lines
    chain.remove Sidekiq::Middleware::Server::Logging
  end
end

Sidekiq::Client.reliable_push! if ['production', 'staging'].include?(ENV['RACK_ENV'])
```

**Comment by mperham** [comment]
I can't reproduce locally; pause and unpause work as expected.  Perhaps there is something unusual about your environments.

**Comment by azach** [comment]
Yup, that's my guess too @mperham; any suggestions on what to look at to try and isolate the cause?

**Comment by mperham** [comment]
Nothing comes to mind.  You can monitor the Redis traffic using `redis-cli monitor` if staging is pretty quiet.
