### ISSUE TITLE
Jobs Not Retrying with retry set to TRUE

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3343]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.7

If relevant, please include your initializer and any error message with the full backtrace.

We have a very heavily used worker called GenericLoggerWorker with the following options:

```
sidekiq_options :retry => true, :queue => :workers
```
A small percentage of the time when this job fails (due to 10s database write timeout) it falls into the Dead Queue instead of the Retry Queue. 99% it retries just fine (I see it in the queue) but occasionally it just goes to dead queue.

Grepping logs I can verify that this job and its associated data only ran once.

What's going on?

**Comment by mikegee** [comment]
Your initializer and the error message with the full backtrace would be nice here.

**Comment by bobber205** [comment]
The backtrace is just Sequel saying something timed out.

Initializer is just plugins. Not sure what is meant by that.

**Comment by mperham** [comment]
Please include your initializer.

**Comment by bobber205** [comment]
```Sidekiq::Logging.logger.level = Chirpify::Environment.log_level.to_i

schedule_file = "config/cron_schedule.yml"

analytics_cron_file = "config/analytics_cron.yml"

if File.exists?(schedule_file)
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
end

if File.exists?(analytics_cron_file)
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(analytics_cron_file)
end
```

is that what you need?

**Comment by bobber205** [comment]
FWIW I'm not able to retest with those cron jobs disabled.

**Comment by mperham** [comment]
I have no clue why a job would go to the Dead set directly instead of retrying unless the job was configured that way.

**Comment by bobber205** [comment]
Yeah. Me either.
It seems to be just be every once in a while.
Normally they retry just fine. Could :retry => true be interpreted as just retry once?

**Comment by mperham** [comment]
Nope, `retry: true` means use the retry subsystem's defaults: 25 retries.

**Comment by bobber205** [comment]
![sidekiq 2017-02-03 13-00-50](https://cloud.githubusercontent.com/assets/5841107/22608355/51bf0542-ea11-11e6-9d3e-236fd0937088.png)
![sidekiq 2017-02-03 13-00-32](https://cloud.githubusercontent.com/assets/5841107/22608356/51d4ec5e-ea11-11e6-9f55-a25eb08694e2.png)

We're under some heavy load at the moment so I was able to find a "tried more than once example".

Still seems about 1% or less of jobs are dropping into dead queue.

Is there anything I can provide to help with debugging this? We don't really wanna have to resort to manually rescheduling the jobs.

**Comment by mperham** [comment]
Those images don't tell me anything.  I think you'll need to add more logging to determine why the job is being moved to the Dead queue.
