### ISSUE TITLE
No route matches [GET] "/sidekiq/images/favicon.ico"

### ISSUE THREAD

**Issue by knzudgt** [mperham/sidekiq#3344]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.7

I use Sidekiq + Sidekiq-Cron.
When I use Sidekiq web UI I receive from Puma the following error message:

```
Started GET "/sidekiq/images/favicon.ico" for 127.0.0.1 at 2017-02-06 10:05:54 +0100
  ActiveRecord::SchemaMigration Load (35.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  
ActionController::RoutingError (No route matches [GET] "/sidekiq/images/favicon.ico"):
```

The web UI is mounted correctly as explained in the Wiki documentation as follows:
`mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new`

While the /sidekiq url takes me to the web UI, it seems that Puma also tries to get the url:
` "/sidekiq/images/favicon.ico"`

and it fails. I do not understand what is all about and the reason of this failure.
There are no other issues apart from this, Sidekiq working as expected.

**Comment by shaneog** [comment]
It's not Puma. It's your browser that's making the request based on the `shortcut icon` meta tag [here](https://github.com/mperham/sidekiq/blob/master/web/views/layout.erb#L9).

This file does exist, is your web server (e.g. nginx/Apache) doing something "special" with those requests. For example have to told it to serve requests that end in certain extensions from disk, else send to Puma?

**Comment by knzudgt** [comment]
I have no other application server than Puma.
It is a rails application, I noticed this issue in development and I thought it may propagate in production. What would you suggest to do? I suppose the existing root_path named route is considered as referred to my application's root_path, and of course there is not a sidekiq directory in my application root path.

**Comment by shaneog** [comment]
Your app doesn't need to have a `sidekiq` directory. It's mounted via the sidekiq gem: `mount Sidekiq::Web => '/sidekiq'`

If this is occurring in development, is Rails/Puma set up to serve assets?

This is **definitely** not a Sidekiq issue, hence the closure of this issue.

**Comment by knzudgt** [comment]
I honestly do not know if Puma is set up to serve assets by default.
Certainly I did not set up it myself.
Do you think is this the issue?

**Comment by shaneog** [comment]
Without configuration, etc. it's anyones guess. I suggest formulating a question on StackOverflow.

**Comment by mperham** [comment]
I think you should probably do some Googling on favicon.ico.  This is normal and can be ignored.  If someone wants to submit a dank favicon.ico, that would be cool.

**Comment by anothermh** [comment]
[favicons.zip](https://github.com/mperham/sidekiq/files/756173/favicons.zip)

Created from http://sidekiq.org/assets/kicker.svg with https://realfavicongenerator.net, but if you're looking for the least amount of work then you probably just want `favicon.ico` out of the zip. GitHub doesn't allow posting .ico files here, so you get the whole zip instead.

**Comment by knzudgt** [comment]
@shaneog @mperham I am pretty sure this is an issue with Vivaldi browser.
No issues with Firefox and SeaMonkey.
