### ISSUE TITLE
Add an in_batch? method to worker

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#3346]
Ruby version: N/A
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 3.4.3+

I'd like to be able to check whether a worker is running within a batch in a forward supported way.  Right now I can do that by checking if `!bid.nil?`, but this feels like an exposure of a low-level implementation detail that may change in the future. 

I'm proposing the addition of a method to worker.rb in SidekiqPro, provisionally named `in_batch?`, which wraps this implementation and becomes part of the API going forward.

The specific use case that drives this need is related to cancelling.  I have workers that may or may not be running within a batch.  I want to allow them to check whether they are part of a cancelled batch.  The `valid_within_batch?` method is insufficient by itself, as it raises a RuntimeError if the worker isn't part of the batch.

**Comment by mperham** [comment]
As you note, this is equivalent:

```ruby
module Sidekiq::Worker
  alias_method :in_batch?, :bid
end
```

If you aren't sure if a worker is part of a batch, you will need to do something like `bid && valid_within_batch?`.
