### ISSUE TITLE
Latest stable version of sidekiq broken on heroku servers?

### ISSUE THREAD

**Issue by qnoox** [mperham/sidekiq#3347]
Ruby version: 2.3.3/rails 5.0.0.1
Sidekiq / Pro / Enterprise version(s): Sidekiq

This is more a question then a fact as i have for 5 days tried to get it to work again after update
of sidekiq i get this error all the time now. 

(on heroku, so i wanted to ask the question to see if the support for sidekiq on heroku is broken or is it just me?).

Used: Redis to go, Puma, sidekiq, actioncable.

Error:
```
    [ActionCable] [mail] Could not execute command from {"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\"}", "data"=>"\"message:message\""}) 
    [NoMethodError - undefined method `except' >for "message: message":String
    2017-02-06T00:48:33.207838+00:00 app[web.1]:
    Did you >mean?  exec]:       /app/vendor/bundle/ruby/2.3.0/gems/actioncable->
    5.0.1/lib/action_cable/channel/base.rb:272:in `block in   action_signature' 
    | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-  5.0.1/lib/action_cable/channel/base.rb:271:in `tap' 
    | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-  5.0.1/lib/action_cable/channel/base.rb:271:in `action_signature' 
    |   /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:169:in   `perform_action' 
    | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-  5.0.1/lib/action_cable/connection/subscriptions.rb:53:in `perform_action'

```

sidekiq.rb
`Sidekiq.configure_client do |config|
  config.redis = { :size => 4 }
end

Sidekiq.configure_server do |config|
  config.redis = { :size => 30 }
end
`

sidekiq.yml
`production:
  :concurrency: 28
queues:
  - [default, 1]`

in my model:
`after_create_commit { BroadcastMessageJob.perform_later self }`

BroadcastMessageJob.rb
`class BroadcastMessageJob < ApplicationJob
  queue_as :default

  def perform(message)
    ActionCable.server.broadcast 'room_channel', message: render_message(message)
  end

  private
    def render_message(message)
      ApplicationController.renderer.render(partial: 'messages/message', locals: { message: message })
    end
end`

Procfile
`web: bundle exec puma -e production
worker: bundle exec sidekiq -e production -C config/sidekiq.yml`

Any information would be greatly appreciated.
Thank you in advance.

**Comment by mperham** [comment]
Sidekiq works fine on Heroku with no known problems.  This isn't the right place for help with ActionCable but the error message `undefined method 'except' for "message: message":String` should give you some hint.
