### ISSUE TITLE
Feature request: Use Rails logger in development

### ISSUE THREAD

**Issue by aripollak** [mperham/sidekiq#3350]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 3.3.0

In the Rails development environment, `rails server` and `rails console` will, by default, log to both `log/development.log` and STDOUT, which is very nice since I can see all the relevant output from the single terminal that I'm running `foreman` or the rails console from.

However, when running the Sidekiq server while using ActiveJob, the default logging situation isn't ideal - ActiveJob/ActiveRecord/Rails information only goes to log/development.log, but Sidekiq-specific information only goes to STDOUT, especially job exception backtraces. 

Would you consider making this more closely match `rails server` behavior by default when running the server in Rails development? Something roughly equivalent to putting this in a Rails project's config/environments/development.rb:
```ruby
  if Sidekiq.server?
    config.log_formatter = Sidekiq::Logging::Pretty.new

    config.after_initialize do
      console = ActiveSupport::Logger.new(STDOUT)
      console.formatter = Sidekiq::Logging::WithoutTimestamp.new
      console.level = Rails.logger.level

      unless ActiveSupport::Logger.logger_outputs_to?(Rails.logger, STDOUT)
        Rails.logger.extend(ActiveSupport::Logger.broadcast(console))
      end

      Sidekiq::Logging.logger = Rails.logger
    end
  end
```

**Comment by mperham** [comment]
I'm always interested in better Rails integration but I have no idea how to implement this.  Advice welcome.

Sidekiq uses its own logger formatting which outputs useful data like TID and JID so I'm not convinced it would be a good idea to intermix job and web output in the same file.  Perhaps `log/development.log` is better named `log/web_development.log`?

**Comment by mperham** [comment]
vs `log/job_development.log`.

**Comment by aripollak** [comment]
The code snippet in the first message includes the the TID/JID on all the log lines (and timestamp in the file) by making the Rails logger use Sidekiq's formatters. 

development.log also intersperses console/rake/server output, so this probably wouldn't be worse from that perspective, but you could set the `log_file` to `sidekiq_development.log` there too?

**Comment by mperham** [comment]
In thinking about this more, any use of explicit logfiles is the wrong direction IMO.  Modern services should use STDOUT, the process owner/supervisor should redirect as necessary and tools like Foreman can aggregate.

**Comment by aripollak** [comment]
I agree with that in the 12-factor app scenario when running a server, but in Rails development, logfiles are explicitly used by default, so every Rails app using Sidekiq is in a pretty weird/inconsistent logging state by default.

**Comment by mperham** [comment]
Rails is (slowly) moving in this direction:

http://blog.bigbinary.com/2016/04/12/rails-5-allows-to-send-log-to-stdout-via-environment-variable.html
