### ISSUE TITLE
Recurrent `NameError: uninitialized constant NameOfRemovedJob` after job code has been removed.

### ISSUE THREAD

**Issue by vpithart** [mperham/sidekiq#3352]
Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): Sidekiq v4.2.7 / Sidekiq Pro v3.4.0

# What happens
After code for one of jobs have been removed intentionally (the `/app/jobs/process_agreement.rb` that contained `class ProcessAgreement` no longer exists) while one instance of this job was in `retry` queue, and after this retry have been deleted via `/queues/retries` web UI, this error:

```
Feb 10 07:45:15 app/worker.1:  4 TID-ostjfd50w WARN: NameError: uninitialized constant ProcessAgreement 
Feb 10 08:45:15 app/worker.1:  4 TID-osu11gq2c WARN: NameError: uninitialized constant ProcessAgreement 
Feb 10 09:45:15 app/worker.1:  4 TID-ostkpny20 WARN: NameError: uninitialized constant ProcessAgreement 
```

keeps popping up every 60 minutes.

# Backtrace
```
Feb 10 09:45:15 wealthbar app/worker.1:  4 TID-ostkpny20 WARN: TimedFetch pushed back 1 timed out jobs 
Feb 10 09:45:15 app/worker.1:  4 TID-ostkpny20 WARN: {"context":"Job raised exception","job":{"class":"ProcessAgreement","args":[3839],"retry":true,"queue":"default","jid":"209fffdd81c60662c8adb09f","created_at":1486064506.650744,"enqueued_at":1486155738.2643118,"error_message":"index 5 out of string","error_class":"IndexError","failed_at":1486064506.7940922,"retry_count":13,"retried_at":1486127000.766908},"jobstr":"{\"class\":\"ProcessAgreement\",\"args\":[3839],\"retry\":true,\"queue\":\"default\",\"jid\":\"209fffdd81c60662c8adb09f\",\"created_at\":1486064506.650744,\"enqueued_at\":1486155738.2643118,\"error_message\":\"index 5 out of string\",\"error_class\":\"IndexError\",\"failed_at\":1486064506.7940922,\"retry_count\":13,\"retried_at\":1486127000.766908}"} 
Feb 10 09:45:15 app/worker.1:  4 TID-ostkpny20 WARN: NameError: uninitialized constant ProcessAgreement 
Feb 10 09:45:15 app/worker.1:  4 TID-ostkpny20 WARN: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:268:in `const_get' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:268:in `block in constantize' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `each' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `inject' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `constantize' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:127:in `block in process' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog' 
Feb 10 09:45:15 app/worker.1:  /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread' 
```

**Comment by mperham** [comment]
Never remove a worker class without ensuring there are no jobs associated with that worker.

Create an empy worker class with that name so the job will execute and go away.

**Comment by vpithart** [comment]
Makes sense; empty one-off worker class makes sense as an workaround.
I still feel a kind of buggy behaviour the fact that a job might be stuck somewhere else than in queues (retry queue, namely).
Would you accept a patch/pullrequest to fix this, if I find a time to do so?

**Comment by mperham** [comment]
Many people have reported this issue.  I'm open for discussion on how to fix but I've never found a solution with reasonable semantics: Sidekiq should never silently swallow jobs.

**Comment by vpithart** [comment]
Sidekiq should never silently swallow jobs ... totally agree. I'm thinking about having such an orphan job in a `retry` queue, hence a possibility to delete it manually exists.

**Comment by mperham** [comment]
Sidekiq Pro has `Sidekiq::Queue#delete_by_class` but that functionality doesn't exist for JobSets (which is what the scheduled and retry queues are).  Perhaps I should add those APIs, then you could run this to clean out old worker names:

```ruby
klass = "ProcessAgreement"
%w(retry schedule).each {|name| Sidekiq::JobSet.new(name).delete_by_class(klass) }
```

**Comment by nathancarnes** [comment]
We're having the same issue, but the deleted job class doesn't exist in any of the visible `JobSet`s -- it's not in scheduled, retries, or dead.

Is there a way to resolve this without manually munging it out of Redis? It seems like there are zombie jobs floating around our Sidekiq internals somehow.

Let me know if you'd prefer me to open a new issue with as much detail as I have (which, unfortunately, does not include clean repro steps).

**Comment by mperham** [comment]
@nathancarnes The answer is already posted: create an empty Worker with that name, let it run successfully so the job goes away.  It's likely in the internal queues used by the reliability feature.

https://github.com/mperham/sidekiq/issues/3352#issuecomment-279032312

**Comment by nathancarnes** [comment]
@mperham thanks for the quick response! We'll do that.
