### ISSUE TITLE
How to test job.delete for Sidekiq::ScheduledSet?

### ISSUE THREAD

**Issue by ruslansavenok** [mperham/sidekiq#3353]
Ruby version:ruby 2.2.2p95
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.7

My workers have following `cancel_scheduled` method:
```
class ApplicationWorker
  include Sidekiq::Worker

  def self.cancel_scheduled(*args)
    Sidekiq::ScheduledSet.new.each { |job|
      job.delete if job.item['class'] === self.name && job.item['args'] == args
    }
  end
end
```

Which doesn't work in test env because all jobs are pushed to `MyWorker.jobs` instead of ` Sidekiq::ScheduledSet`

Any suggestions on how I can test this case?

**Comment by mperham** [comment]
Do not implement cancellation like that -- it's terribly slow and inefficient.

https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job
