### ISSUE TITLE
Feature Request: Track metrics about duplicate jobs

### ISSUE THREAD

**Issue by weppos** [mperham/sidekiq#3354]
I have a feature request related to the ["unique jobs"](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs) feature of Sidekiq Enterprise.

It would be useful to track metrics about unique/duplicate jobs in Statsd. That would allow to determine, for example, which worker is sending the majority of duplicate jobs and/or the ratio between unique and total, pretty much like you would track cache hit/miss events  in a cache system.

**Comment by mperham** [comment]
With the new Statsd support in Sidekiq Pro 3.6, this metric will be available in the next version of Sidekiq Ent.

```
jobs.duplicate - a job was not enqueued because it was not unique
jobs.duplicate.$WorkerClassName - metric with the worker's class name included, for debugging
```

http://www.mikeperham.com/2017/12/11/sidekiq-pro-statsd-support----new-and-improved/

**Comment by weppos** [comment]
Awesome, thanks!

**Comment by mperham** [comment]
Thanks for your patience.  I'll likely wait a few weeks to release Sidekiq Enterprise with these metrics, so Pro 3.6 can get some usage and prove stable first.
