### ISSUE TITLE
Mutex deadlock when calling ActiveRecord

### ISSUE THREAD

**Issue by chrisyuska** [mperham/sidekiq#3359]
Ruby version: 2.3.3
Sidekiq version: 4.2.9

If a job includes an ActiveRecord query wrapped in a mutex and two workers hit the mutex around the same time (while one is still in the mutex), both workers become deadlocked.  Take the following job's perform method:

```ruby
@@job_mutex = Mutex.new

def perform
  @@job_mutex.synchronize do
    records_count = Sample.count
  end
end
```

If this job is queued twice and two workers perform around the same time, they'll both deadlock.  I've created a sample application to isolate the issue: https://github.com/chrisyuska/sidekiq-mutex-deadlock-demo.  The README in that repo gives instructions to reproduce the issue (make sure you enqueue the job twice before starting sidekiq to start both jobs around the same time).

A few things I've noticed:

* Wrapping the method in `Thread.new {...}` seems to fix the issue, but isn't practical for Sidekiq jobs.
* The sample app uses an ActiveJob, but the issue persists in pure Sidekiq jobs too.
* Only ActiveRecord queries result in the deadlock.  Pure SQL queries seemingly don't have any effect.
* I've also tried this with both the `redis-mutex` gem and `redis-semaphore` gem and the issue persists with both.

Is there something I'm missing about how Sidekiq handles concurrency?  Thanks for any help.

**Comment by ryansch** [comment]
Are you planning on running sidekiq on only one machine?  Memory based locks aren't a good fit for distributed systems.

**Comment by chrisyuska** [comment]
@ryansch I'm using redis-mutex in my app but wanted to simplify the example.  The issue persists with any mutex system I've tried.

**Comment by ryansch** [comment]
@chrisyuska Facepalm.  You said that near the bottom.  Sorry for the oversight.

**Comment by mperham** [comment]
I have no idea why this would happen but I also don't see how it could possibly be an issue with sidekiq, sidekiq can't affect how threads interact.

Deadlocks are usually caused by threads that take locks in different orders.

**Comment by mperham** [comment]
Also note that threads can take database locks if they perform any type of operation (there are both R and R/W locks for transactional purposes) which can lead to deadlock too.  Thread 1 takes a lock on the Sample table and tries to take @@job_lock, Thread 2 takes @@job_lock and then tries to take the Sample table lock.

**Comment by chrisyuska** [comment]
@mperham, @ryansch  Thanks for the quick responses.  I really appreciate it.

If there's a database lock happening, I wouldn't expect it to occur until the worker is within the mutex lock, as that's the only ActiveRecord reference I have, which *shouldn't* deadlock the first worker.  Would ActiveRecord really lock the table for a simple `*.count` query too?

Note that I can run create two threads to process the jobs in the rails console and there's no deadlock issue (like so):

```ruby
2.times do
  Thread.new { TestJob.perform_now }
end
```

How much does the above really differ from how Sidekiq workers process the jobs?

I just tried something else to attempt to narrow this down.  If I start a second job while the first job is within the mutexed method but past the ActiveRecord query (using `sleep(30)` after the ActiveRecord query), the mutex behaves properly and no deadlock occurs.  Putting a `sleep(30)` within the mutexed method before the ActiveRecord query and starting the second job while the first job is sleeping (~25s before the ActiveRecord query) still results in deadlock though.

So Deadlock occurs if two Sidekiq workers perform mutexed jobs when the first job still has an ActiveRecord query coming up.  I think I'm even more confused now.

**Comment by mperham** [comment]
Use the TTIN signal and postgres tooling to determine where the threads are blocked.

**Comment by alflennik** [comment]
Any solutions? [I'm still getting this issue!](https://stackoverflow.com/questions/46777824/activerecord-deadlock-in-worker-with-rails-mysql-sidekiq-and-a-mutex)
