### ISSUE TITLE
Get current worker uniq id

### ISSUE THREAD

**Issue by esiegel** [mperham/sidekiq#3360]
I see from the source that there is a way to get the current job id within the Job, but is there a way to get information about the worker/thread processing the job.  Specifically, if I am running with `concurrency: 25`, I would like the same thread/process to have the same concurrency_id every time - some number between 0-24.

My use case might be strange, but I need to guarantee that all of the running jobs have a unique id in the range of the concurrency.  I am using this unique id to help create readable randomish strings that are prefixed with this uniq id.

Of course I could write some shared service that all workers can communicate with to fetch this id, but I'm just hoping that sidekiq has something similar already.

Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.2

**Comment by mperham** [comment]
Sidekiq doesn't provide anything that specialized. Sounds like you'd need to roll your own.

**Comment by esiegel** [comment]
Would you be open to a pull request that:

1. Added the notion of Processor Id, which would just be the index that the Manager created it.
  It would reuse the id if the processor died.

2. Pass the processor id down to the worker in a similar fashion that JID is passed down?

I know in the general case that each worker should be exactly the same and shouldn't need this information, but I can think of some situations where it might be nice (excluding my selfish needs).  

For example, I could imagine using sidekiq for parallel processing of a large task where each worker chooses a chunk to work on.  By having a ProcessorId one wouldn't need a coordinator divvying out the specific chunks and instead the workers could choose them theirselves.

**Comment by mperham** [comment]
Too specialized for core, but sounds like it could be a useful 3rd party gem.

**Comment by esiegel** [comment]
Gotcha, Thanks for the quick responses.
