### ISSUE TITLE
Sidekiq & current_user timezone around_filter issue

### ISSUE THREAD

**Issue by rsiddle** [mperham/sidekiq#3361]
Ruby version: 2.3.0p0

Problem: Receiving an `invalid date` error when creating Sidekiq Job for Production (web) only. I've traced the error back to my function which https://gist.github.com/rsiddle/24824d470f6fb825e5086af48b6ec4e7

```
# application_controller.rb
around_filter :user_time_zone, if: :current_user

private

def user_time_zone(&block)
   Time.use_zone(current_user.normalize_timezone, &block)
end
```

```
# user.rb
def normalize_timezone
   time_zone.present? ? time_zone : 'London'
end
```
This works fine on my local machine (Mac OSX 10.11.6). However when using a Ubuntu box (14.04) through the production website, it throws that error above. If I `ssh` into the server and run a test job, it works correctly too.

```ssh
current_user = User.first
Time.use_zone(current_user.normalize_timezone) do
  TestJob.set(wait_until: (Time.zone.now - 20.seconds)).perform_later
end
```

*UPDATE: I've been using Sidekiq via ActiveJob. If I create a Sidekiq worker through `rails g sidekiq:worker Test`, then there is no issue with the 'invalid date'. It looks to be an issue with ActiveJob?*

**Comment by mperham** [comment]
This has nothing to do with Sidekiq but fwiw "London" is not a proper timezone.  "Europe/London" is.

https://en.wikipedia.org/wiki/List_of_zoneinfo_time_zones
