### ISSUE TITLE
Sidekiq Enterprise periodic jobs on JRuby?

### ISSUE THREAD

**Issue by jegt** [mperham/sidekiq#3362]
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.73-b02 on 1.8.0_73-b02 +jit [solaris-x86_64]
Sidekiq Pro 3.4.3 / Sidekiq Enterprise 1.3.2, commercially licensed.

Are there any known problems with running periodic jobs on jruby? We're using periodic jobs on several apps with MRI but on our single jruby app the jobs are just not picked up. No error but they do not show up in the UI and don't run.

**Comment by mperham** [comment]
There are no known issues.  Let me know if you get more detail.
