### ISSUE TITLE
Sidekiq picks up $concurrency jobs on start, then those jobs vanish

### ISSUE THREAD

**Issue by henrebotha** [mperham/sidekiq#3365]
* Ruby version: 2.3.1
* Sidekiq version: 4.2.1
* I am using ActiveJob

Last week, I deployed two changes two production. One was an HTML change unrelated to any Sidekiq job. The other was a password for a database (which later turned out to be the wrong password).

Sidekiq flat-out stopped performing any jobs the minute that deployment went through.

Since then, I have fixed the database password. Sidekiq is no longer logging db login failures, so that's good. However, the problem persists.

The pattern:

1. I restart Sidekiq.
2. Sidekiq grabs 15 jobs. At this point the web UI shows the PID of the Sidekiq process under "busy".
3. About a minute later, those 15 jobs _vanish_. They are not in processed, failed, retries, scheduled, or dead.
4. At this point, the web UI stops showing the Sidekiq process under "busy". `ps aux | grep sidekiq` shows that the process still lives.

It seems that restarting Sidekiq creates a new process, but the old processes are still running over an hour later (saying `[0 of 15 busy]`).

`kill -TTIN $pid` does not log anything.

No errors are logged. All I see in the logs is Sidekiq starting up, and then those 15 jobs being picked up.

The job I'm trying to run is a mailer.

It's not the Linux OOM thing.

**Comment by henrebotha** [comment]
And now, after almost 24 hours of fruitless debugging, it chooses to actually do something. Oh well.

**Comment by emerson-h** [comment]
I am also seeing this behavior with Sidekiq 4.2.2.

**Comment by mperham** [comment]
Upgraydd!

**Comment by henrebotha** [comment]
Lol @mperham, are you saying there is a particular issue with the versions we're running, or are you just saying it's generally good to stay updated?

**Comment by emerson-h** [comment]
@mperham I've been able to trace the issue to a worker getting stuck in IO wait because of a broken NFS descriptor.  However, I am at a loss as to why that's causing the supervisor to drop out of the Busy queue in the UI.

**Comment by henrebotha** [comment]
My issue has recurred, so I'm reopening this.

`strace` consistently shows it hanging on this:

```
select(16, [15], NULL, NULL, NULL
```

(Though it's not always `16` & `15` - those numbers change every time I restart sidekiq.)

I've attached `strace` to the sidekiq process shortly (a few seconds) after restarting it. The summary looks like this:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 59.92    2.698767          36     74644     72977 open
 12.46    0.560992          40     13891      1972 stat
  6.87    0.309548          31      9923           lstat
  6.70    0.301851          37      8256           getdents
  4.31    0.193892          47      4129         2 openat
  4.02    0.181009          31      5792           close
  1.55    0.069830          39      1812           read
  1.29    0.058117          24      2460           fstat
  0.44    0.019828          24       822       821 ioctl
  0.42    0.018808          23       823           fcntl
  0.38    0.017234          21       802           getuid
  0.37    0.016518          21       802           geteuid
  0.36    0.016306          20       802           getgid
  0.36    0.016254          20       802           getegid
  0.20    0.008835          72       123        20 futex
  0.16    0.007236          28       259           brk
  0.04    0.001747          30        59           getcwd
  0.03    0.001572          32        49           mmap
  0.03    0.001366          33        41           write
  0.03    0.001169          29        40           chdir
  0.02    0.001003          31        32           mprotect
  0.02    0.000866          46        19           clone
  0.02    0.000698          24        29           lseek
  0.01    0.000264          24        11           sched_yield
  0.00    0.000035          35         1           uname
  0.00    0.000032          32         1           munmap
  0.00    0.000027          27         1         1 access
  0.00    0.000000           0         5           rt_sigaction
  0.00    0.000000           0         1           select
  0.00    0.000000           0         1           socket
  0.00    0.000000           0         2         1 connect
  0.00    0.000000           0         1           times
  0.00    0.000000           0         2           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00    4.503804                126437     75794 total
```

The full log is very long (126k lines) so I won't paste it here (I also don't know enough about security to know whether pasting it could constitute a security risk).

Something I'd like to do is put explicit exception logging in my mailer workers that outputs to the sidekiq logger. However, I have not explicitly defined workers - it's being done automagically somewhere. How can I get logging in my mailer workers?

**Comment by mperham** [comment]
Use TTIN or get a GDB backtrace.  https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes

**Comment by henrebotha** [comment]
TTIN doesn't work (nothing gets logged). I'll speak to sysadmins tomorrow about installing gdb on the server.

**Comment by mperham** [comment]
What version are you using now?  4.2.9?  It's also very important to upgrade all of your native gems:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do

**Comment by henrebotha** [comment]
Excellent, thanks. I missed that particular piece of advice. I'll update my gems and see whether that resolves the problem.
