### ISSUE TITLE
sidekiq fails to properly shutdown after kill

### ISSUE THREAD

**Issue by interone-ms** [mperham/sidekiq#3367]
Ruby version: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]`
Sidekiq / Pro / Enterprise version(s): `Sidekiq 4.2.7`

Hi,

I am using sidekiq bundled with gitlab 8.17 and have the bug that when killing sidekiq (because for some reason one job gets stuck and no other jobs get processed at all), sometimes sidekiq does not push back the jobs to redis but immediately exits after a normal `kill` (in contrast to `kill -9`, where this is expected), leading to a job loss.

Is there a way to increase debug output in order to submit a proper bugreport?

**Comment by mperham** [comment]
This is not a gitlab support channel, please contact gitlab with issues.
