### ISSUE TITLE
Process Freezing Constantly

### ISSUE THREAD

**Issue by kpheasey** [mperham/sidekiq#3369]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
```
sidekiq (4.2.3)
sidekiq-pro (3.4.0)
```

This is a continuation of issue #3337.  The problem was not resolved and we have updated our cookbooks to use a ruby version with debug symbols.  Please see the gdb output from two different frozen processes below:

https://gist.github.com/kpheasey/959b673608bdfdaec04d6062f83957e6

We had separated our `FeederWorkers` (api scrapers) from the `CalculatorWorkers`.  We thought maybe there were net http requests that were hanging, despite having open and read timeouts.  

After the separation, only processes running `CalculatorWorkers` would freeze.

All native gems are up to date.

**Comment by kpheasey** [comment]
Occasionally, when the processes freeze, our database usage goes crazy.  The the chart below is our production aurora cluster cpu usage.  The process froze around 03/03 2:30 and you can see the usage starts spiking and holding around 100%.

When I look at the running processes on the database server, there are queries that have been running for as long as the sidekiq process froze.  The queries range simple selects by primary index, or more complex updates with additional triggers.

Blue - Master
Orange - Replica

Once again, this is only an occasional side effect from the processes freezing.  As soon as the process is restarted, the cpu usage will drop back to normal.

![screen shot 2017-03-03 at 8 57 31 am](https://cloud.githubusercontent.com/assets/3934075/23553647/bf95777e-ffef-11e6-8726-ccd03a58e3a2.png)

**Comment by mperham** [comment]
Does the process respond to signals?  Ideally I need the TTIN output.  If the process doesn't respond to TTIN, then the GDB output is necessary but I don't see any obvious problems in your GDB output.

**Comment by kpheasey** [comment]
Nothing appears in the log when I send the TTIN signal.  The process will force quit after the specified 5 minute timeout.

**Comment by mperham** [comment]
I'm not seeing any native gem stack frames, which is the typical culprit.  Most threads appear to be waiting for a Mutex but that could be normal.  There is one thread pinging mysql, one possibility is that you have database connection exhaustion.  Is your database.yml pool setting plenty big for your concurrency?

**Comment by kpheasey** [comment]
I run 2 processes per server, with a concurrency of 15.  The DB pool size is 50.  I assumed I would only need a pool size of 30 but gave some extra room.  The DB itself has a max connection count of 1000+.  We usually have between 2-6 processes running, depending on the load.

**Comment by mperham** [comment]
The only known issue with DB connection exhaustion is noted here at the end of the Configuration section, beware of using connections within `sidekiq_retries_exhausted`:

https://github.com/mperham/sidekiq/wiki/Error-Handling#configuration

**Comment by mperham** [comment]
Your pool size only needs to match the concurrency size so `pool: 15` is sufficient.

**Comment by kpheasey** [comment]
We do get a high number of retries with our `CalculatorWorker` due to db deadlocks when similar records are being processed at the same time.  Sometimes a single job can be retried 3 or more times, but usually only 1-2 times.  However, we do not explicitly use `sidekiq_retries_exhausted` and jobs rarely make it to the DJQ.

I think our program may be causing deadlocks in the DB that MySQL/Aurora does not recover from, causing the deadlock exception to not be thrown.  However, I don't understand how that would cause every worker in the process to stall.  Do you think an uncaught deadlock in mysql could cause the whole process to lock up?

**Comment by mperham** [comment]
IIRC mysql detects possible deadlocks at the database level and raises an error to rollback/retry in one of the transactions to avoid the deadlock.

**Comment by kpheasey** [comment]
The `CalculateWorker`job calls a `#calculate!` method on a single record.  We use a pessimistic lock on the record to ensure it's cache flag, `is_calcated`, is not changed while calculating.

Here's the method: https://gist.github.com/kpheasey/3df5ed64a99933be211f76fae12ffcc3

Any idea where I could start looking to further debug this?

**Comment by mperham** [comment]
Dive into mysql sql tracing, optimization and profiling.  I think things like innodb status will show you some lock detail but no idea how useful.

I would also consider refactoring the implementation to push it into the database itself, using a stored procedure, trigger or similar, if possible.  Distributed locks are always dangerous.
