### ISSUE TITLE
Sidekiq seems to be stuck

### ISSUE THREAD

**Issue by BrandonShega** [mperham/sidekiq#3372]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.6

It seems that we have a lot of jobs that are 'stuck' in the queue.  The queue is always busy with 3 jobs and a lot are failing.  Here is an example of a failed job:

<img width="1207" alt="screen shot 2017-03-06 at 11 19 26 am" src="https://cloud.githubusercontent.com/assets/1090748/23618678/159ba0b4-025f-11e7-9616-d62542bbd250.png">

Everything was working fine until this morning and now I'm not sure what happened.  Any help is greatly appreciated.

**Comment by mperham** [comment]
http://localhost:1313/2016/08/05/debugging-stuck-ruby-processes/
