### ISSUE TITLE
How to restart sidekiq after completing running jobs?

### ISSUE THREAD

**Issue by rajputvijay32** [mperham/sidekiq#3374]
Hi ,
Bellow is my script to restart Sidekiq. Now I want to restart sidekiq it completing all jobs in my process_list. It should not add new jobs to queue.

How can I do this?

def process_list
  config = YAML::load_file(arg('-C', 'config/sidekiq_prod.yml'))
  config.map do |group|
    {
        '-tg' => group[:tag],
        '-c' => group[:concurrency],
        '-L' => "log/sidekiq_#{group[:tag]}.log",
        '-P' => "tmp/pids/sidekiq_#{group[:tag]}.pid",
        '-g' => "Sidekiq_#{group[:tag]}",
        '-e' => arg('-e', ENV['RAILS_ENV']) || 'production',
        '-t' => arg('-t', '30'),
        '-qs' => group[:queues].map { |q| "-q #{q.join(',')}" }.join(' ')
    }
  end
end

def process_start(p)
  args = %w(-c -L -P -g -e).map { |a| [a, p[a]] }.flatten
  args << p['-qs'] << '-d'
  exec "~/.rvm/bin/rvm default do bundle exec sidekiq #{args.join(' ')}"
end

def process_stop(p)
  args = [p['-P'], '-t', p['-t']]
  exec "~/.rvm/bin/rvm default do bundle exec sidekiqctl stop #{args.join(' ')}"
end

def process_status(p)
  begin
      pidfile = p['-P']
      pid = File.read(pidfile).to_i
      Process.getpgid(pid)
      puts "Tag #{p['-tg']} Pid #{pid} running"
    rescue Errno::ENOENT
      puts "Tag #{p['-tg']} Pidfile #{pidfile} not found"
    rescue Errno::ESRCH
      puts "Tag #{p['-tg']} Pid #{pid} not running"
    end
end

def status
  process_list.each { |p| process_status p }
end

def start
  process_list.each { |p| process_start p }
end

def stop
  process_list.each { |p| process_stop p }
end

def restart
  process_list.each do |p|
    process_stop p
    process_start p
  end
end

Thanks

**Comment by mperham** [comment]
```ruby
require 'sidekiq/api'
q = Sidekiq::Queue.new
loop do
  break if q.size == 0
  sleep 1
end
```
