### ISSUE TITLE
undefined method `new' for Utils::Paginator:Module

### ISSUE THREAD

**Issue by mockdeep** [mperham/sidekiq#3375]
Ruby version: `ruby 2.3.3p222`

Sidekiq / Pro / Enterprise version(s): `4.2.9`

We're trying to define a class `Utils::Paginator` in our application, but when trying to access it we see the following error:

```
undefined method `new' for Utils::Paginator:Module
```

Grepping through our gems, it looks like Sidekiq is the only place where a `module Paginator` is defined, so I'm wondering if Sidekiq is somehow injecting that module into the global namespace and making it so Rails autoloading can't find ours. There is this line which looks suspicious to me in that regard:

```ruby
Sidekiq::WebApplication.helpers Sidekiq::Paginator
```

**Comment by mperham** [comment]
Use `source_location` to find where it's defined:

```ruby
meth = (::Utils::Paginator.methods - Object.methods).first
::Utils::Paginator.method(meth).source_location
=> ["/Users/mikeperham/.gem/ruby/2.3.2/gems/rake-12.0.0/lib/rake/ext/core.rb", 17]
```

**Comment by mockdeep** [comment]
Turns out it was because we were using `stub_const('Utils::Paginator::DEFAULT_RECORDS_PER_PAGE', 2)` in our specs.
