### ISSUE TITLE
Is this the normal shape of the dashboard chart?

### ISSUE THREAD

**Issue by caseyohara** [mperham/sidekiq#3376]
I'm curious if this is the typical shape of the dashboard timeline chart as Sidekiq is processing the queue, all of the peaks and valleys? What accounts for the valleys with 0 jobs processed?

![http://i.imgur.com/Qg5XGhU.png](http://i.imgur.com/Qg5XGhU.png)

**Comment by mperham** [comment]
Good point, I think this was caused by the refactor for Sidekiq 4.0 that changed the heartbeat to update stats every 5 seconds.  Try moving the slider to update ever 5 seconds and see if it looks better then.  If so, I'll change the default.

**Comment by caseyohara** [comment]
I adjusted the slider to 5 seconds and it does look better. I believe we started noticing the change when we upgraded to Sidekiq 4.0, so that seems consistent.

Thanks Mike!

![http://i.imgur.com/xskBC1I.png](http://i.imgur.com/xskBC1I.png)
