### ISSUE TITLE
Sidekiq web messes up user sessions

### ISSUE THREAD

**Issue by heaven** [mperham/sidekiq#3377]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.9

Our app is running on a subdomain, like "sub.domain.com". We have sessions configured to be shared across all subdomains:
```ruby
Carmen::Application.config.session_store :active_record_store,
  key: "_wego#{"_#{Rails.env}" unless Rails.env.production?}_session", :domain => :all
```

After accessing the app a session is created and stored for ".domain.com". But after accessing "/sidekiq" another session appears in cookies for "sub.domain.com", which breaks the app, log out and a few other things.

**Comment by badosu** [comment]
Hello @heaven,

When mounting the `Sidekiq::Web` middleware, could you try setting up the Session options manually?

E.G.

```ruby
app = Sidekiq::Web.new

app.use Rack::Session::Cookie, options
```

See [this page](http://www.rubydoc.info/github/rack/rack/Rack/Session/Cookie) on how to configure it. Do not forget to pass `app` instead of `Sidekiq::Web` to `mount`.

**Comment by heaven** [comment]
I can but it anyway then runs `Sidekiq::Web#build_sessions` which inserts `::Rack::Session::Cookie` to middlewares array.

**Comment by badosu** [comment]
@heaven This is weird, as `build_sessions` checks if there's an already mounted middleware or the `sessions` option as [seen here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L163).

Would you mind posting your code that mounts the middleware?

**Comment by heaven** [comment]
It does, but it also performs a few other actions that I don't completely understand so I have to copy a decent part of this method. Is there a way to copy application settings inside `build_sessions`?

**Comment by badosu** [comment]
@heaven I can't know the context of your question without seeing the changes you are performing. 

You could try using the `Sidekiq::Web.set :sessions, opts` method as well.

**Comment by heaven** [comment]
@badosu this worked, thanks:
```ruby
Sidekiq::Web.set :sessions, { domain: ".domain.com" }
```
Was wondering if this could be detected in Sidekiq, from the :domain option that I pass in session_store.rb

**Comment by badosu** [comment]
@heaven Glad it worked! AFAIK Sidekiq Web is totally agnostic of the framework you're using.

**Comment by dbalatero** [comment]
@heaven I found another solution to this, in case anyone else is Googling:

*config/initializers/session_store.rb*

```ruby
require 'sidekiq/web'

Rails.application.config.session_store :active_record_store,
  key: '_my_session_key'

# Turn off Sinatra's sessions, which overwrite the main Rails app's session
# after the first request
Sidekiq::Web.disable(:sessions)
```
*lib/admin_constraint.rb*
```ruby
class AdminConstraint
  def matches?(request)
    user = request.env['warden'].user(:user)
    user && user.admin?
  end
end
```

*config/routes.rb*
```ruby
constraints AdminConstraint.new do
  mount Sidekiq::Web => '/sidekiq'
end
```
