### ISSUE TITLE
Memory leak when db_pool smaller than concurrency? (heroku)

### ISSUE THREAD

**Issue by lastobelus** [mperham/sidekiq#3382]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 4.2.9

I have an app on that is worker-heavy, and I'm using a hobby-basic postgres instance on heroku, which is limited to 20 connections.

I decided to split that between web and worker, and since that left me with a lot of extra redis connections to work with, to set sidekiq concurrency higher than  the rails db pool size.

When I did so my worker started to leak memory. I'm confident this change was the cause, as my worker had processed about 45000 jobs previously without any sign of increasing memory usage, and I made no other changes in about 36h prior to this change. Before the change it was using just under half the memory of a 1X dyno. After the change it would start at about half and expand fairly rapidly. I reduced sidekiq concurrency somewhat, and it grew more slowly, but still grows  and eventually causes R14s when concurrency is > db pool size.

Is this a known issue?

Is it a waste of time to have concurrency higher than db pool size if every worker talks to the db at some point in its life? IE, do workers grab their db connection exclusively over their life?

**Comment by mperham** [comment]
A job will take a DB connection the first time it touches the DB and, generally, won't release that connection until the job is finished.  If your jobs are long-running or use the DB heavily, there's not a lot of point to increasing concurrency past the pool size.

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#no-leak-issues-please
