### ISSUE TITLE
Warn when using the Testing API outside of test environment

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3384]
It's fairly common for people to accidentally activate the testing API and then later spend an hour trying to figure out why jobs aren't going to Redis.  Print out a warning when using the testing API outside of Rails's test environment.

**Comment by everton** [comment]
@mperham the reason for your warning is very clear but it is also common to use the inline mode to run jobs immediately in development env when you don't want redis as an development dependency (there is a lot of sites recommending this approach).

I know this kind of decision has nothing to do with sidekiq team, but I think that you must provide an alternative to disable this warning, maybe through some ENV var or anything else, but the way this is implemented (using a simple puts) let no easy way for developers to avoid the warning and this became a problem when you need to run a scripts or anything in console.

**Comment by everton** [comment]
P.S.: or maybe you can do the puts into STDERR instead of STDOUT, the annoyance will persist but at least scripts running on console can have his output redirected without the chance that the warning will go into redirection target

**Comment by mperham** [comment]
That's not a supported usecase, the Testing API is for testing only.  If you want that functionality, I'd suggest creating a gem which people can activate in a Bundler :development group which has a similar effect.
