### ISSUE TITLE
Sidekiq stops processing jobs, and Web UI throws errors

### ISSUE THREAD

**Issue by percyhanna** [mperham/sidekiq#3386]
Ruby version: `2.3.1p112`
Sidekiq / Pro / Enterprise version(s): `sidekiq (4.2.9)`

Lately we've had problems where the Web UI raises exceptions, and the sidekiq workers stop grabbing new jobs from the queue. To resolve this issue we've manually pruned some of the jobs from the queue(s) and then bumped the sidekiq processes, at which point Sidekiq drains the queue successfully without any further issue. The last time this happened, there were no active jobs on any of the nodes.

We also use the `sidekiq-unique-jobs` Gem (version 4.0.18), but from what we can tell this appears to be an issue with `sidekiq` itself.

**Stacktrace:**
```
TypeError: nil can't be coerced into Float
  from sidekiq/api.rb:78:in `-'
  from sidekiq/api.rb:78:in `fetch_stats!'
  from sidekiq/api.rb:8:in `initialize'
  from sidekiq/web/helpers.rb:111:in `new'
  from sidekiq/web/helpers.rb:111:in `stats'
  from (eval):5:in `_erb__summary'
  from sidekiq/web/action.rb:89:in `_erb'
  from sidekiq/web/action.rb:55:in `erb'
  from (eval):22:in `_render'
  from sidekiq/web/action.rb:60:in `erb'
  from sidekiq/web/application.rb:41:in `block in <class:WebApplication>'
  from sidekiq/web/application.rb:266:in `instance_exec'
  from sidekiq/web/application.rb:266:in `block in call'
  from sidekiq/web/application.rb:262:in `catch'
  from sidekiq/web/application.rb:262:in `call'
  from rack/auth/basic.rb:25:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from rack/urlmap.rb:65:in `block in call'
  from rack/urlmap.rb:50:in `each'
  from rack/urlmap.rb:50:in `call'
  from rack/builder.rb:138:in `call'
  from sidekiq/web.rb:103:in `call'
  from sidekiq/web.rb:108:in `call'
  from action_dispatch/journey/router.rb:71:in `block in call'
  from action_dispatch/journey/router.rb:59:in `each'
  from action_dispatch/journey/router.rb:59:in `call'
  from action_dispatch/routing/route_set.rb:678:in `call'
  from rack/deflater.rb:25:in `call'
  from rack/etag.rb:23:in `call'
  from rack/conditionalget.rb:25:in `call'
  from rack/head.rb:11:in `call'
  from action_dispatch/middleware/params_parser.rb:27:in `call'
  from app/middleware/catch_json_parse_errors.rb:7:in `call'
  from action_dispatch/middleware/flash.rb:254:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from action_dispatch/middleware/cookies.rb:560:in `call'
  from active_record/query_cache.rb:36:in `call'
  from wellness/middleware.rb:30:in `call'
  from active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  from action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from active_support/callbacks.rb:82:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:27:in `call'
  from action_dispatch/middleware/remote_ip.rb:76:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  from action_dispatch/middleware/show_exceptions.rb:30:in `call'
  from lograge/rails_ext/rack/logger.rb:15:in `call_app'
  from rails/rack/logger.rb:20:in `block in call'
  from active_support/tagged_logging.rb:68:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:68:in `tagged'
  from rails/rack/logger.rb:20:in `call'
  from action_dispatch/middleware/request_id.rb:21:in `call'
  from rack/methodoverride.rb:21:in `call'
  from rack/runtime.rb:17:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  from rack/sendfile.rb:112:in `call'
  from rack/cors.rb:80:in `call'
  from raven/integrations/rack.rb:53:in `call'
  from rails/engine.rb:514:in `call'
  from rails/application.rb:144:in `call'
```

**Comment by percyhanna** [comment]
Also wanted to point out that Redis was behaving more or less fine. I was able to run Sidekiq commands directly through the Rails console without any issues.

**Comment by mperham** [comment]
That backtrace indicates a job that does not have an `enqueued_at` attribute.  This has been fixed on master but not released.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby

**Comment by percyhanna** [comment]
That explanation makes perfect sense. I forgot to mention that we are pushing jobs to the queue from a separate Java system. Sounds like the next release will fix this issue, but we will also investigate the job queuing from Java.

**Comment by percyhanna** [comment]
Any idea on when the change will be released? I noticed the commit that fixed the issue is earmarked for 5.0.0 release.

**Comment by mperham** [comment]
The commit should be on master.  I'll likely release 4.2.10 on Friday.

**Comment by mperham** [comment]
4.2.10 is out.

**Comment by percyhanna** [comment]
Thanks.

For posterity, we actually found the root cause of this "bug": a recent change to our deployment process meant that we were not properly stopping and starting our Sidekiq processes. Because of this, our cluster got into a state where all Sidekiq processes were in the "quiet" state, yet no new processes were started, and the quiet processes were never fully killed off. For whatever reason, this set of circumstances led to the symptoms we experienced above.

**Comment by bafalurd** [comment]
resolví asi 
Modifiqué  api.rb
 se encuentra aqui
/usr/share/rvm/gems/ruby-2.5.3/gems/sidekiq-6.0.7/lib/sidekiq

en la linea 84, 85 y 86 

lo sustituí  estaba asi 
s = processes.size
workers_size = pipe2_res[0...s].sum(&:to_i)
enqueued = pipe2_res[s..-1].sum(&:to_i)

lo sustituí por esto 

s = processes.size
slice = pipe2_res[0...s] || []
workers_size = slice.compact.map(&:to_i).sum

enqueued_slice = pipe2_res[s..-1] || []
enqueued = enqueued_slice.compact.map(&:to_i).sum



cambie la linea 87 que estaba asi 
default_queue_latency = if (entry = pipe1_res[6].first)
 por esta 
default_queue_latency = if (entry = pipe1_res[6].to_a.first)
 y listo

**Comment by mperham** [comment]
@bafalurd sidekiq 6.0 is no longer supported.
