### ISSUE TITLE
Colorblind-friendly Web UI Colours

### ISSUE THREAD

**Issue by mtthwhggns** [mperham/sidekiq#3387]
Ruby version: 2.2.6
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.9 / Pro 3.4.5 / Ent 1.5.2

In the "Batches" interface in Sidekiq Pro's web interface, red and green can appear next to one another if the batch contains only successful and failed jobs.

![Batches progress bars without stripes](https://cloud.githubusercontent.com/assets/6674046/23946521/5a8b4fd2-0983-11e7-8e0e-b47fa575cb0b.png)

This is a bit of a pain for red-green colorblind users (3-4% of the population), as red and green can appear indistinguishable, making it difficult to tell where the border between them is.

My suggested quick improvement would be to use Bootstrap's `progress-bar-striped` on only the failure side, so that it gives an effect like this;

![Batches progress bars with stripes](https://cloud.githubusercontent.com/assets/6674046/23946620/c9f2cef4-0983-11e7-82b1-7a5094481a96.png)

I haven't noticed anywhere else that colour is relied upon. 

I'd have made a PR myself if I could access the repo.

**Comment by mperham** [comment]
Great idea. I'll implement it today.
