### ISSUE TITLE
Is there a way to "kill" scheduled Jobs?

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3390]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.9

If relevant, please include your initializer and any error message with the full backtrace.

We have hundreds of "bad" scheduled jobs, ones with now invalid parameters.
I'd like to programmatically add all of these to the dead queue to retry/rerun later but when I run the `kill` command I get this

`
RuntimeError: Kill not available on jobs which have not failed
`

Is there a clever way around this?

**Comment by mperham** [comment]
I think I just copied the retry code and didn't consider this possibility.  Thanks!

**Comment by mperham** [comment]
Right, so the Dead tab assumes the job has an error associated with it, i.e. it's a retry.  You can remove a scheduled job but you can't currently kill it until it executes once.  I'll need to fix this.

**Comment by bobber205** [comment]
Thanks @mperham ! <3

**Comment by mperham** [comment]
Ok, you can try master and see if it behaves the way you wish.
