### ISSUE TITLE
Periodic jobs: adding arguments

### ISSUE THREAD

**Issue by agrobbin** [mperham/sidekiq#3392]
We just this week upgraded from Sidekiq Pro to Sidekiq Enterprise and are looking to switch from clockwork for our scheduled jobs to Enterprise's periodic jobs feature. In the wiki page you note:

> The `perform` method for periodic workers must take **NO** parameters (or have default values for all parameters).

Our current clockwork configuration pushes all work into Sidekiq background jobs already, but a bunch of our jobs take arguments even when enqueued periodically. For example, we have a bunch of different notifications (email, push, SMS) that get all triggered the exact same way, and rather than have a different job class for every type, we have a job class that looks like this:

```ruby
class PostalEventBatchJob < ApplicationJob
  def perform(event)
    PostalEvents.const_get(event.camelize).enqueue_batch!
  end
end
```

Our clockwork configuration then looks like this:

```ruby
every(1.hour, "Foo", at: "**:00") do
  PostalEventBatchJob.perform_async("foo")
end

every(1.hour, "Bar", at: "**:30") do
  PostalEventBatchJob.perform_async("bar")
end
```

I'm curious what the reason is for not supporting arguments in the periodic job configuration. When I was looking at the `sidekiq-ent` source code (I won't paste it here) it looks like something that could be reasonably easy to add support for. Something similar to this maybe?

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    mgr.register('0 * * * *', PostalEventBatchJob, args: ["foo"])
    mgr.register('30 * * * *', PostalEventBatchJob, args: ["bar"])
  end
end
```

I'm not sure if you accept pull requests to `sidekiq-ent`, but if so I'd be happy to take a stab at adding support for something like this!

**Comment by mperham** [comment]
Yep, that will work.  You can pass in args like that as long as you use String keys:

```ruby
mgr.register('0 * * * *', PostalEventBatchJob, 'args' => ["foo"])
```

**Comment by agrobbin** [comment]
Oh, even better that it doesn't require any changes! Should the [wiki page](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#notes) be updated to note that it's doable?

**Comment by mperham** [comment]
Done https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#notes

**Comment by agrobbin** [comment]
💥 thanks for the quick turn-around @mperham!

**Comment by jamesncampbell** [comment]
Apologies for chiming in on such a long-closed issue but I've recently come across this during a migration to enterprise and had a question about the args.

If I wanted to use `Time` as an argument, would it be possible to cast that to a string in the sidekiq_server_config, with something like:
```
config.periodic do |mgr|
  mgr.register('*/5 * * * *', "SomeJobName", 'args' => ["Time.now.to_i.to_s"])
end
```

which I'd then be able to parse back to an Int within the job? Or is it expected that this argument should always be the same?

**Comment by mperham** [comment]
args must be static since they are evaluated at boot time.
