### ISSUE TITLE
Missing log entries?

### ISSUE THREAD

**Issue by gingerlime** [mperham/sidekiq#3393]
Ruby version: 2.3.1p112
Sidekiq / Pro / Enterprise version(s): 4.1.0

Please include your initializer and any error message with the full backtrace.

sidekiq.yml

```yml
---
:verbose: false
:pidfile: /var/run/sidekiq/sidekiq.pid
:daemon: true
:logfile: /var/log/kenhub/sidekiq.log
:concurrency:  20
:timeout:  15
:queues:
  - [mailer, 7]
  - [default, 5]
  - [batch, 1]
```

Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?

It's a slightly older version, but I couldn't spot anything directly related in the changelog

https://github.com/mperham/sidekiq/blob/master/Changes.md

I'm looking at my rails log file and sidekiq, and I'm pretty sure some entries are missing from the sidekiq log. I think jobs are running fine, but not all log records get written. Even with the same workers.

We have a very simple rails controller that receives webhooks from Stripe, and then pushes them to a `StripeWebhooks` worker. Both the controller and worker log the data they receive and then continue.

The code (pretty much verbatim):

```ruby
# stripe_controller.rb
class StripeController < ApplicationController
  # webhooks don't have CSRF tokens
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  def webhook
    check_token(Kenhub.config.x.stripe.webhook_token)
    logger.info("Stripe webhook: #{params[:stripe]}")
    logger.debug(params[:stripe].pretty_inspect)
    StripeWebhooks.perform_async(params.require(:stripe))
    render :nothing => true, :status => 200
  end

  private

  def check_token(token)
    raise ActiveRecord::RecordNotFound unless params[:token] == token
  end
end

# stripe_webhooks.rb
class StripeWebhooks
  include Sidekiq::Worker

  def perform(event)
    logger.info("async processing stripe webhook: #{event}")
    case event['type']
    when 'customer.subscription.updated'
      # ...
    end
  end
# ...
end
```

If I look at my rails log file, I can see the `Stripe webhook: {...}` entry being logged with the stripe webhook data, and the response is 200. No errors.

The sidekiq.log file also shows `async processing stripe webhook: {...}` being logged, but not always.

Our production.log and sidekiq.log are fully aligned and get logratated at the same time. If I do something like this, I get about 50% less entries in my sidekiq.log files as I would on my production.log file

```shell
cat production.log | grep invoice.payment_succeeded | wc -l
cat sidekiq.log | grep invoice.payment_succeeded | wc -l
```

As far as I can tell, all jobs run successfully as well (those jobs send emails out, update the database etc, and we didn't see anything NOT working). So it doesn't look like the problem with the job not running, but simply that the log entries don't always get written.

Hope I explained the problem clearly. I was scratching my head for hours trying to figure out what went on, when I was looking at a particular entry, but then I realized there's some kind of a pattern, and some log entries just go missing.

Any tips on what could possibly cause this? or what to look for?

**Comment by mperham** [comment]
Don't daemonize and logrotate yourself.  Let upstart/systemd do it all for you.

**Comment by gingerlime** [comment]
Thanks so much for the speedy response, @mperham !

Ah! Of course!! It now seems so obvious, no clue how I didn't think of it...

So there was a "lost" sidekiq process that obviously didn't get the USR2 signal ...

We're on 14.04, so I think systemd isn't available yet, but I've had some not-so-great experience with it (although it was a few years ago now), and the next upgrade we'll probably be on systemd. I'll meanwhile just make sure we don't lose any sidekiq processes with a temporary hack or some manual check in the init.d script.

Thanks so much again Mike!
