### ISSUE TITLE
safe to upgrade redis Gem to 3.3.3 ?

### ISSUE THREAD

**Issue by gingerlime** [mperham/sidekiq#3394]
We're seeing some odd `Redis::TimeoutError`s even though our redis is local and pretty small. These errors are not only from Sidekiq, but also our session store. Can't find anything in the redis logs, or anything concrete to indicate where the problem might be.

We're using the redis 3.2.2 gem, and I saw something in the redis [changelog](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md) about fixing / improving timeout issues in redis 3.3.3. So I'd like to upgrade.

However, the Sidekiq changelog mentions something about memory leaks and that people should stick to redis 3.2.2 (?). Those leaks were fixed in 3.3.1. Is it therefore safe to update our redis gem to 3.3.3 with Sidekiq 4.2.10?

**Comment by gingerlime** [comment]
P.S. would appreciate any suggestions on the redis server version (we're currently on 3.0.7 and considering upgrade to 3.2.x), and if anyone has any experience resolving weird intermittent timeout issues :-/

hope I'm not asking for too much :)

**Comment by mperham** [comment]
Anything 3.x should be fine although 3.0.3+ is recommended for large scale installs running 1000s of threads.  2.8 is still the minimum requirement.

I'n not aware of any current issues with 3.3.3, I'd suggest going through redis-rb's issue tracker and/or opening an issue there.  There were issues with 3.3.0 and 3.3.1 iirc.

**Comment by gingerlime** [comment]
Thanks Mike! Good to know.

We upgraded sidekiq to 4.2.10 and redis gem to 3.3.3 and it looks ok for now (fingers crossed). We have a very small scale setup though. We're still using redis 3.0.7, but plan to upgrade to 3.2.x at some point...
