### ISSUE TITLE
`perform_in` swallowing jobs

### ISSUE THREAD

**Issue by jstastny** [mperham/sidekiq#3396]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Pro

We are on:
- Sidekiq: 4.2.9
- SidekiqPro: 3.4.3

We have recently been observing issue with `perform_in` not actually scheduling job. For example:
- We call `MyWorker.perform_in(20.seconds, 4343434, 'retry_count' => 2)`.
- The call returns Job ID, let's say `967c40658f800fa5aabb836d` (we started logging the output of the `peform_in` command as part of the troubleshooting of this issue)
- The job `967c40658f800fa5aabb836d` never appears in Scheduled Set and never gets executed.

We use the following initializer:
```ruby
	Sidekiq::Client.reliable_push!

	Sidekiq.configure_server do |config|
		config.reliable_fetch!
		config.reliable_scheduler!
	end
```

Our Scheduled set now contains something over 40k records, but I believe that should not be causing such issues.

Has any of you observed similar behavior? Any suggestions what we should check / do?

**Comment by mperham** [comment]
What versions are you using?  Are you using rspec-sidekiq?

**Comment by jstastny** [comment]
We are on:
- Sidekiq: 4.2.9
- SidekiqPro: 3.4.3

**Comment by mperham** [comment]
I've heard of:

1. people messing up deployment so that all Sidekiq processes were quiet
2. rspec-sidekiq being activated in production so that all jobs are captured, rather than going to redis
3. different client/server Redis config so created jobs aren't picked up by the Sidekiq process

There is no known issue that would cause your problem.

**Comment by jstastny** [comment]
Thanks for hints. I have checked them:

1. This does not seem to be the case as we are processing many other jobs and the swallowed job is rather an exception. Vast majority gets processed correctly.
2. We don't use rspec-sidekiq at all.
3. Incorrect queue does not seem to be the cause either as we many (most) jobs scheduled the same way are processed correctly.

**Comment by jstastny** [comment]
To gather more details about the issue we have been capturing redis `MONITOR` and for the job that has been "swallowed" we have only found following (when searching by JID):
```
1490101211.382482 [0 10.239.147.86:46357] "zadd" "schedule" "1490101231.3395069" "{\"class\":\"ImageProcessing::CampaignAssetPreviewWorker\",\"args\":[81380539,{\"retry_count\":1}],\"retry\":0,\"queue\":\"image_processor_outbound\",\"backtrace\":true,\"jid\":\"aca92df8e74f82f6ee8e39a8\",\"created_at\":1490101211.3395407}"
```
I can provide larger context of this command if needed.
When we then searched for the job directly in Redis using ZSCAN, we could not find the job in Redis.

For the jobs, that have not been "swallowed" we could find that in addition to `zadd`, there was also `lpush` and `lrem` in the `MONITOR` output:
```
1490102018.926125 [0 10.239.147.86:45172] "zadd" "schedule" "1490102038.8910868" "{\"class\":\"ImageProcessing::CampaignAssetPreviewWorker\",\"args\":[81381778,{\"retry_count\":1}],\"retry\":0,\"queue\":\"image_processor_outbound\",\"backtrace\":true,\"jid\":\"4758b61028ab6d96620b5ce7\",\"created_at\":1490102018.891117}"
1490102043.505048 [0 lua] "lpush" "queue:image_processor_outbound" "{\"class\":\"ImageProcessing::CampaignAssetPreviewWorker\",\"args\":[81381778,{\"retry_count\":1}],\"retry\":0,\"queue\":\"image_processor_outbound\",\"backtrace\":true,\"jid\":\"4758b61028ab6d96620b5ce7\",\"created_at\":1490102018.891117,\"enqueued_at\":1490102043.4665627}"
1490102056.856536 [0 10.239.147.86:46833] "lrem" "queue:image_processor_outbound_1" "-1" "{\"class\":\"ImageProcessing::CampaignAssetPreviewWorker\",\"args\":[81381778,{\"retry_count\":1}],\"retry\":0,\"queue\":\"image_processor_outbound\",\"backtrace\":true,\"jid\":\"4758b61028ab6d96620b5ce7\",\"created_at\":1490102018.891117,\"enqueued_at\":1490102043.4665627}"
```

**Comment by mperham** [comment]
Are you running 3.4.5 which has a scheduling fix?  My previous "no code issue" assumed you had upgraded to pick up bug fixes.

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#345

**Comment by jstastny** [comment]
We will upgrade immediately. 
Sorry we missed this upgrade. We started solving this issue already before the mentioned 3.4.5 was released and before https://github.com/mperham/sidekiq/issues/3371 was reported -- I reported this to you first via email on 1st March.

**Comment by mperham** [comment]
Yeah, the bug was introduced in 3.4.3 so you have all the qualifications necessary to experience this sweet bug.  Sorry for the trouble.

**Comment by jstastny** [comment]
That is good news. It would be great if this fixed our issues. We just upgraded and looking forward to see results. Will keep you posted.

**Comment by jstastny** [comment]
I just analyzed the logs from last cca 12 hours (after the deploy of updated Sidekiq) and so far it seems we got no more lost scheduled jobs. I will keep monitoring, but it seems the sidekiq bug really was the root cause.
