### ISSUE TITLE
Sidekick Enterprise Batch count

### ISSUE THREAD

**Issue by jondavidchristopher** [mperham/sidekiq#3398]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Enterprise

@mperham ,

Is there a way for us to open a pull request for sidekiq enterprise? I have an issue where My batch count for pending jobs goes to -1. It always happens around the time of a release so I would assume that there is some sort of race condition where a job completes, decrements the counter right before it is terminated and added back into the queue to be processed when the server restarts. Happy to fix myself but not sure how your handling pull requests on Enterprise. 

    - LMK & Thanks

**Comment by mperham** [comment]
I've helped lots of people with this problem and it's always a bad deploy script.

1. Signal USR1 as early as possible in your deploy.
2. Signal TERM as late as possible.
3. Don't ever `kill -9` the process.

Tell me about your deploy process.

**Comment by jondavidchristopher** [comment]
We are using codeship to deploy to heroku. 


It is using this on codeship from what I can see:
    git remote add heroku_resafari git@heroku.com:resafari.git
    git push heroku_resafari $CI_COMMIT_ID:refs/heads/master
    heroku_run rake db:migrate resafari
    /usr/bin/heroku restart --app resafari

I would assume that its the last line that needs to be adjusted? Or maybe some configuration on heroku itself?

**Comment by jondavidchristopher** [comment]
Just googling, i found this:

https://github.com/mperham/sidekiq/wiki/Deployment#heroku

I suppose triggering:

Sidekiq::ProcessSet.new.each(&:quiet!)

after CI tests pass is probably going to solve this issue?

**Comment by mperham** [comment]
Yes, I suspect it would help.  More than that, I can't say since I don't know what those cmds are actually doing.

**Comment by jondavidchristopher** [comment]
There is a good 2-3 minutes of deploy time before it gets to those commands...So I would assume that shutting those down would do the trick. Anything else I should be doing here? My only fear is that Heroku does something stupid like trying to start them back up after you put in the request to shut them down.

**Comment by jondavidchristopher** [comment]
Also, anything to combat regular Heroku restarts? There is a rolling one every 24 hours by default.

**Comment by mperham** [comment]
USR1 helps but as long as you send TERM and then give the process the full 10 seconds to exit, it should shut down cleanly.  I'm not sure why your Sidekiq process doesn't but it's always because people kill -9 the process too soon.

**Comment by jondavidchristopher** [comment]
Makes sense. I found this feature in beta from heroku:

https://devcenter.heroku.com/articles/release-phase

I popped in a rake task that runs:
Sidekiq::ProcessSet.new.each(&:quiet!)
sleep 10

This should pretty much cover all cases on heroku, even changing ENV vars. Not sure, but this might be worth mentioning in the readme.

**Comment by mperham** [comment]
Thanks for the tip!  Reopen if nothing changes.
