### ISSUE TITLE
Upgrading redis 2.8.12 to 3.2.6

### ISSUE THREAD

**Issue by dorongutman** [mperham/sidekiq#3404]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): Enterprise

I'm using the following versions of sidekiq:
sidekiq (4.1.4)
sidekiq-ent (1.3.2)
sidekiq-pro (3.3.2)

Is there any problem with upgrading redis from 2.8.12 to 3.2.6 ? 
Is there any migration needed ?

**Comment by mperham** [comment]
This is more of a Redis question, I'm not sure of the answer.  You might be able to point the new version to the old datafile and it'll just migrate the file transparently on startup or you might need to start the new version as a slave of the old version first.  Here's what a quick search came up with:

https://redis.io/topics/admin#upgrading-or-restarting-a-redis-instance-without-downtime

**Comment by mperham** [comment]
WRT Sidekiq, there's no migration necessary.  You might consider upgrading; looks like your versions are about 6-9 months out of date.
