### ISSUE TITLE
Worker is timing out?

### ISSUE THREAD

**Issue by myfitment** [mperham/sidekiq#3409]
Ruby version:2.1
Sidekiq / Pro / Enterprise version(s): 4.2.9 / 3.4.5 / 1.5.2

I have a Sidekiq worker class with a "run" class method. This method accepts a customer id, then kicks off a job for each record in the customer's product table.

I also have another Worker class in front of this whose sole purpose is to call the run method. That's so I can kick the whole job off from a controller action without delaying the request.

For customers with over a million products, this container worker returns this error message:

```
Connection lost (EPIPE)
```

Could the connection be timing out?

**Comment by mperham** [comment]
Can you give the whole backtrace?

**Comment by myfitment** [comment]
Definitely looks like a redis timeout issue. What pattern can I use for running a job that will create a batch out of tens or even hundreds of thousands jobs and still be non-blocking with respect to the web application?

Connection lost (EPIPE)
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:257:in `rescue in io'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:250:in `io'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:269:in `write'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:228:in `block (3 levels) in process'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:222:in `each'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:222:in `block (2 levels) in process'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:367:in `ensure_connected'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:187:in `call_pipelined'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:157:in `block in call_pipeline'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
/data/myfitment/shared/bundled_gems/ruby/2.1.0/gems/redis-3.3.3/lib/redis/client.rb:155:in `call_pipeline'

**Comment by mperham** [comment]
The key is to parallelize the creation of the batch.

1. Create one primary job which creates the batch and a set of N child jobs.
2. Each child job should create jobs for 1/Nth of the products and add them to the batch.

For example, for a million products, you might create 100 jobs each of which creates jobs for 10,000 products.

**Comment by mperham** [comment]
Sample code for step 1:

```ruby
class PrimaryWorker
  include Sidekiq::Worker
  def perform(entity_id)
    cnt = Entity.find(entity_id).product_ids.count
    return if cnt == 0

    batch = Sidekiq::Batch.new
    batch.on(:success, something)
    batch.jobs do
      amt = cnt / 1000
      amt.times do |idx|
        ChildWorker.perform_async(entity_id, idx, 1000)
      end
    end
  end
end
```

**Comment by mperham** [comment]
Step 2:

```ruby
class ChildWorker
  include Sidekiq::Worker
  def perform(entity_id, idx, cnt)
    pids = Entity.find(entity_id).product_ids.limit(1000).offset(idx*1000)
    batch.jobs do
      pids.each do |pid|
        ProductWorker.perform_async(entity_id, pid)
      end
    end
  end
end
```

This is all pseudocode so caveat runner.

**Comment by myfitment** [comment]
This pattern worked great. Couple of minor changes for anybody watching:

```
class PrimaryWorker
  include Sidekiq::Worker
  def perform(entity_id, batch_size = 1000)
    cnt = Entity.find(entity_id).product_ids.count
    return if cnt == 0

    batch = Sidekiq::Batch.new
    batch.on(:success, something)
    batch.jobs do
      amt = [cnt / batch_size].ceil
      amt.times do |idx|
        ChildWorker.perform_async(entity_id, idx, batch_size)
      end
    end
  end
end
```

```
class ChildWorker
  include Sidekiq::Worker
  def perform(entity_id, idx, cnt)
    pids = Entity.find(entity_id).product_ids.limit(cnt).offset(idx*cnt)
    batch.jobs do
      pids.each do |pid|
        YourWorker.perform_async(entity_id, pid)
      end
    end
  end
end
```

**Comment by ronakjangir47** [comment]
Thanks @myfitment @mperham for sharing sample code.

While implementing the same we found an issue with the queue of jobs.

Let's say  `ChildWorker` has `base` queue and `ProductWorker` has `notifications` queue. 
But using above sample code, jobs of `ProductWorker` use `default` queue instead of `notifications`.

**Comment by mperham** [comment]
@ronakjangir47 It will use whatever queue you have set in `sidekiq_options` unless you override it:

```ruby
ProductWorker.set(queue: "something").perform_async(...)
```

**Comment by ronakjangir47** [comment]
Here is the full sample code to demo this. I used `push_bulk` instead of `perform_async`.

Step 1
````ruby
class PrimaryWorker
  include Sidekiq::Worker
  def perform
    batch = Sidekiq::Batch.new
    batch.jobs do
      10.times do |idx|
        ChildWorker.perform_async(ProductWorker.name, (1..1000).map{|x| [x]})
      end
    end
  end
end
````

Step 2
````ruby
class ChildWorker
  include Sidekiq::Worker
  sidekiq_options retry: true, queue: :base

  def perform(worker_klass, jobs)
    batch.jobs do
      Sidekiq::Client.push_bulk('class' => worker_klass, 'args' => jobs)
    end
  end
end
````

Step 3
````ruby
class ProductWorker
  include Sidekiq::Worker
  sidekiq_options retry: true, queue: :notifications

  def perform(pid)
    sleep(1)
  end
end
````

But it's working fine if I replace Step 2 with following
````ruby
class ChildWorker
  include Sidekiq::Worker
  sidekiq_options retry: true, queue: :base

  def perform(worker_klass, jobs)
    batch.jobs do
      jobs.each do |job|
        worker_klass.safe_constantize.send(:perform_async, job)
      end
    end
  end
end
````

I think the problem is with `push_bulk`.

**Comment by mperham** [comment]
The problem is not with push_bulk, it's that you are passing a String instead of a Class.  This will work:

Sidekiq::Client.push_bulk('class' => worker_klass.constantize, 'args' => jobs)

**Comment by ronakjangir47** [comment]
It worked thanks
