### ISSUE TITLE
How will SideKiq behave on Elastic Beanstalk?

### ISSUE THREAD

**Issue by mabdelfattah** [mperham/sidekiq#3413]
I'm using sidekiq on  Elastic Beanstalk that has 3 EC2 instances, my question now, how will it behave for scheduled jobs? will it run on the 3 machines and do the same job 3 times? or run only on one machine?

here is the .ebextension

    # Sidekiq interaction and startup script
    commands:
      create_post_dir:
        command: "mkdir -p /opt/elasticbeanstalk/hooks/appdeploy/post"
        ignoreErrors: true
    files:
      "/opt/elasticbeanstalk/hooks/appdeploy/post/50_restart_sidekiq.sh":
        mode: "000755"
        owner: root
        group: root
        content: |
          #!/usr/bin/env bash
          . /opt/elasticbeanstalk/support/envvars

          EB_APP_DEPLOY_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k app_deploy_dir)
          EB_APP_PID_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k app_pid_dir)
          EB_APP_USER=$(/opt/elasticbeanstalk/bin/get-config container -k app_user)
          EB_SCRIPT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k script_dir)
          EB_SUPPORT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k support_dir)

          . $EB_SUPPORT_DIR/envvars
          . $EB_SCRIPT_DIR/use-app-ruby.sh

          SIDEKIQ_PID=$EB_APP_PID_DIR/sidekiq.pid
          SIDEKIQ_CONFIG=$EB_APP_DEPLOY_DIR/config/sidekiq.yml
          SIDEKIQ_LOG=$EB_APP_DEPLOY_DIR/log/sidekiq.log

          cd $EB_APP_DEPLOY_DIR

          if [ -f $SIDEKIQ_PID ]
          then
            su -s /bin/bash -c "kill -TERM `cat $SIDEKIQ_PID`" $EB_APP_USER
            su -s /bin/bash -c "rm -rf $SIDEKIQ_PID" $EB_APP_USER
          fi

          . /opt/elasticbeanstalk/support/envvars.d/sysenv

          sleep 10

          su -s /bin/bash -c "bundle exec sidekiq \
            -e $RACK_ENV \
            -P $SIDEKIQ_PID \
            -C $SIDEKIQ_CONFIG \
            -L $SIDEKIQ_LOG \
            -d" $EB_APP_USER

      "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_sidekiq.sh":
        mode: "000755"
        owner: root
        group: root
        content: |
          #!/usr/bin/env bash
          . /opt/elasticbeanstalk/support/envvars

          EB_APP_USER=$(/opt/elasticbeanstalk/bin/get-config container -k app_user)
          EB_SCRIPT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k script_dir)
          EB_SUPPORT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k support_dir)

          . $EB_SUPPORT_DIR/envvars
          . $EB_SCRIPT_DIR/use-app-ruby.sh

          SIDEKIQ_PID=$EB_APP_PID_DIR/sidekiq.pid
          if [ -f $SIDEKIQ_PID ]
          then
            su -s /bin/bash -c "kill -USR1 `cat $SIDEKIQ_PID`" $EB_APP_USER
          fi

**Comment by spinx** [comment]
See https://github.com/mperham/sidekiq/wiki/Reliability#scheduler

**Comment by mperham** [comment]
If you schedule one job it will execute one job, no matter how many Sidekiq processes you are running.
