### ISSUE TITLE
Mutex deadlock when calling ActiveRecord (ext version)

### ISSUE THREAD

**Issue by lizard2010** [mperham/sidekiq#3415]
Ruby version: 2.3.1
Sidekiq version: 4.2.10
rails: 5.0.0
thinking-sphinx: 3.3.0

Have same problem like described in #3359.
The attached [worker](https://github.com/mperham/sidekiq/files/884902/run_search_doubles_worker.rb.txt) is started in several jobs at the same time.
And all they are blocked on updating the record, which calls thinking-sphinx.
As you can see in attached [trace](https://github.com/mperham/sidekiq/files/884901/trace.txt) for one of the jobs,
ActiveRecord update_attribute call thinking-sphinx callback, which try get indices configuration.
This operation made thread safe with \@\@mutex use,  look at sources:
[thinking_sphinx/configuration.rb#L78](https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/configuration.rb#L78
)

I have no idea, how to use Sidekiq with thinking-sphinx simultaneously.
As I understand,  thinking-sphinx configuration block inside mutex protect take a relatively much time, but why all threads got deadlock?

**Comment by mperham** [comment]
Upgrade rails, try 5.0.2.

**Comment by lizard2010** [comment]
I tried, and have got mostly same result: [trace2](https://github.com/mperham/sidekiq/files/885687/trace2.txt)

Just for check, I remove mutex protect in thinking-sphinx.
Yes, it is have no sense for safe threading, but after this jobs begun successful execute.

**Comment by mperham** [comment]
That's a thinking-sphinx issue, please open an issue with them to determine the right solution.

**Comment by alflennik** [comment]
Getting the same issue, and I'm not using Thinking Sphinx, but RedisMutex. Only occurs when calling ActiveRecord. [Stackoverflow here.](https://stackoverflow.com/questions/46777824/activerecord-deadlock-in-worker-with-rails-mysql-sidekiq-and-a-mutex)
