### ISSUE TITLE
Query corruption on Sidekiq jobs

### ISSUE THREAD

**Issue by Draiken** [mperham/sidekiq#3416]
Ruby version: 2.2.5
Sidekiq / Pro / Enterprise version(s): 4.1.2
Rails version: 4.2.7.1

This is a long shot, but I'm a bit desperate here, so if you can help in any way, I'd appreciate it. Read through the changelogs and couldn't find any major bug like what I'm experiencing.

Basically, we upgraded ruby from 2.1.5 to 2.2.5 and after a while started having some problems with Sidekiq jobs. Eventually some jobs would not get created (without any errors), but we discarded it as random failures. Until one day an entire table was updated by an SQL query.

Of course we immediately checked any code related to that table looking maybe for a bad `update_all`, even tho it didn't make much sense since it was code that wasn't changed in a long time. Needless to say we found nothing.

Well, we dealt with it, then after a while, this happened again. After some more investigation, we found other tables had similar problems.
We found SQLs clearly generated by ActiveRecord to update one record, but without a WHERE clause. Updating the `updated_at` column, for example, something that's hardly ever done manually.

The only connection between all of the errors I'm having is Sidekiq and, by extension Redis. But while Redis could explain a missing job, it wouldn't deal with concurrency and active record.

We don't have error backtraces, because the jobs aren't failing, they're just updating wrong things. This seems to happen randomly, since we couldn't find a pattern for this.

Sidekiq's used heavily by our application and we've never had problems like this before. I'm going to try updating sidekiq to the latest version, but it's honestly another shot in the dark. I'm considering migrating hundreds of workers to something else just as a hope to fix this. Of course I would hate to do that, but I don't have many choices if I can't find a fix for this.

Again, thanks for any help

**Comment by mperham** [comment]
Sounds like a threading issue in your application.  Look for unsafe code, possibly in any code that generates queries dynamically.  Since Sidekiq does not use AR at all, it can't be the source of your bug.

**Comment by Draiken** [comment]
I don't do the threading, Sidekiq does. We don't use any threading in our workers (except for Sidekiq's concurrency) :slightly_frowning_face: 

Okay, thanks I guess.

**Comment by Draiken** [comment]
@mperham We added a logger for UPDATE queries without conditions and got a hit with stacktrace in production: https://gist.github.com/Draiken/1092c7b139a5acedf5f157a95a8ee0a9

This code has no threading on it, except for Sidekiq's `concurrency` option on the servers and we just updated to sidekiq's latest version. This only happens on sidekiq workers.

Could you please take a second look?

**Comment by mperham** [comment]
That backtrace is telling you that you are running an UPDATE without any conditions, i.e. it will update every row in your table.

Again, any application code run by Sidekiq MUST be thread-safe.  It looks like you have thread-unsafe code within your `PokerRoster.update_counters` method.

**Comment by Draiken** [comment]
That is an active record method. Not ours

**Comment by ryansch** [comment]
What is the first argument passed to `update_counters` on `app/models/hand_stats.rb:92`?

Rails is running `unscoped.where(primary_key => id).update_all updates.join(', ')` where id is the first parameter to `update_counters`.

**Comment by mperham** [comment]
Yeah, I'd bet that ID is nil.

**Comment by Draiken** [comment]
Unfortunately no, I checked that and `nil` generates a `WHERE id IS NULL` query...

**Comment by Draiken** [comment]
Running on my console:
```
irb(main):001:0> PokerRoster.update_counters(nil, hands_played: 1)
  SQL (0.1ms)  UPDATE `poker_rosters` SET `hands_played` = COALESCE(`hands_played`, 0) + 1 WHERE `poker_rosters`.`id` IS NULL
=> 0
```

**Comment by Draiken** [comment]
I understand the skepticism but I don't think this is a newbie coding mistake. This code has been running the exact same way for probably 2+ years and now it's the first time we're having problems with it.

Something happens on the Sidekiq's threads that I imagine corrupts the ActiveRecord model in some way that generates the query without a primary key.

I have looked at the code running on the ActiveRecord gem and couldn't find an obvious threading mistake, but I am not an expert on that.

**Comment by mperham** [comment]
Have you tried upgrading to the latest Sidekiq to see if a newer version fixes your problem?

**Comment by Draiken** [comment]
Yes, as I mentioned we just upgraded it to 4.2.10 and still got this error. Or do you mean to Sidekiq 5? Haven't read if there are breaking changes on that yet.

**Comment by mperham** [comment]
4.2.10 is what I meant.  Sorry, don't know how else to help.  Best of luck tracking it down.

**Comment by ryansch** [comment]
@Draiken I'd recommend instrumenting that code so you can see what the arguments are when it fails.  Somehow you're getting rails to drop this where clause: https://github.com/rails/rails/blob/v4.2.7.1/activerecord/lib/active_record/counter_cache.rb#L84

Best of luck.

**Comment by rajagopals** [comment]
Just wanted to mention we are running into the exact same issue on rails 4.2.10 and latest Sidekiq. We had previously put checks in place to make sure the updates don't go through by setting  sql_safe_updates=1 on the database layer, however we are now seeing this in select queries as well. Its happening in like 2-3 queries a day ( we run 30-40 million queries a day). 
We are now planning to add some checks on the application side globally so that these bad queries don't go through. 

@Draiken any other update from your end on this issue? Any chance you tried Rails 5?

**Comment by Draiken** [comment]
Unfortunately no. We implemented some monkey patches to block the updates and never had the time to go back and try to fix the real cause of this issue...

We're still having this problem happening on average once every week. We haven't noticed SELECT dropping the WHERE clause but it might be happening and we just haven't noticed yet

**Comment by Darep** [comment]
We recently upgraded to Rails 4.2 and ran into this same issue. Sidekiq 4.2.10. The latest incident ran `Article.find(id).update_attributes(cover_image: cover_url)` without WHERE and set the cover image of 9 million articles to be the same image :)

**Comment by Draiken** [comment]
I personally think this is one of the most scary bugs I've ever encountered.
Unfortunately given how much time it'll require to reproduce/fix it, I can't justify spending days/weeks on this. 

Our "workaround" was to patch ActiveRecord and raise an error if we detect any update without a condition. I'd be very grateful if someone had the time to really look into this, but I don't believe it will ever be done for the same reasons I couldn't.

**Comment by Darep** [comment]
Thanks! We are also in the process of patching ActiveRecord for the time being :)

Btw, are you running sidekiq on standalone machines or machines with also a rails web server on them? atm. we haven't seen this problem happen on our standalone sidekiq machines, only on machine with both sidekiq & unicorn running.

P.S. We also randomly get `ActiveModel::MissingAttributeError: missing attribute: some_id` in our workers. Random columns, random models. Also rare.

**Comment by Draiken** [comment]
We're running on Kubernetes, so it's all inside Docker containers.

The missing attributes error is probably as old as Rails. I've had those on all job based systems used (resque and sidekiq) with varying degrees of recurrence.

**Comment by Darep** [comment]
Gotcha! Thanks for the peer support :)
