### ISSUE TITLE
5.0.0.beta3 WebUI actions under SSL

### ISSUE THREAD

**Issue by jfabre** [mperham/sidekiq#3417]
Ruby version: 2.4.1
sidekiq version: 5.0.0.beta3

Only happens on SSL website.

First issue:

If I try to remove a scheduled job in my list in the WEB UI I get firefox telling me:
An error occurred during a connection to www.my_website.com:80. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG.
So somehow it's trying to use port 80 on SSL connection?

Edit:
I removed the second issue, I don't think this has anything to do with this and if there's really a bug
I will create another issue.

**Comment by mperham** [comment]
Sounds like you are trying to link to "https://www.my_website.com:80", i.e. trying to use SSL on an HTTP port.

**Comment by mperham** [comment]
Anyhow, I have no idea what could cause this, perhaps a web server misconfiguration of some sort.

**Comment by jfabre** [comment]
Maybe I wasn't clear. 

It happens when I try remove a scheduled job in the Web UI interface. It also happens for any other job action that I do using the Sidekiq Web UI interface.

It only happens in production where my website in using SSL.
It doesn't happen in development.

**Comment by jfabre** [comment]
It also doesn't happen on Sidekiq 4.

**Comment by mperham** [comment]
Sidekiq 4.?.?.  4.2.10?  4.0.0?

**Comment by jfabre** [comment]
Using sidekiq 4.2.10

**Comment by mperham** [comment]
It sounds like the system is calculating the full path of the redirect incorrectly after the POST action, but this calculation is just a call to `Rack::Request#base_url`.  This would happen if your web server was configured incorrectly to not proxy SSL headers to the webapp correctly.  For instance:

https://github.com/mperham/sidekiq/issues/2910#issuecomment-220665905

If you can only reproduce it in production, there's not much I can do.  You'll need to provide a reproducible app if you want me to debug it.

**Comment by jfabre** [comment]
Ok, it makes sense. I will investigate deeper soon..

**Comment by jfabre** [comment]
It was the 
```
proxy_set_header X-Forwarded-Proto https 
```
in my Nginx config. 

The template I used had it declared twice,  once for http and once for https.
I removed the http declaration and it fixed it.

Don't have the time to know why it worked with Rails, but not with Sinatra and also why it only occurred  under Sidekiq 5.

Thanks for taking the time to point me to the other issue.
