### ISSUE TITLE
Web UI throws errors and they're not logged by sidekiq logger

### ISSUE THREAD

**Issue by koss-lebedev** [mperham/sidekiq#3419]
Recently I started getting 500 "something went wrong" when I'm trying to access a Web UI (sidekiq worker, however, works like a clock). I haven't checked Web UI for a while, so I'm not sure when it stopped working. Anyway, I want to debug this issue, but I don't seem to find any error details neither in Sidekiq log file, nor in Rails log file. Is it possible to configure sidekiq to log Web UI-related errors? Or maybe you have some general recommendations how to debug such issue?

As I mentioned, I don't have any error details to include.

Version details:

Ruby: 2.2.2
Sidekiq: 4.2.10

Initializer:
```
Sidekiq.configure_server do |config|
  config.redis = {
      network_timeout: 5
  }
end

Sidekiq::Logging.logger = Rails.logger
Sidekiq::Logging.logger.level = Logger::DEBUG
```

**Comment by mperham** [comment]
The Web UI is a Rack app and does not perform any error logging itself.  Any exceptions raised should be logged by the Rack host, i.e. puma, unicorn, webrick, etc.

To debug, I would start first by removing all log redirection.

**Comment by crystianwendel** [comment]
Hey @koss-lebedev, did you solve this? It's happening to me, there is no error logs to see what's going on...

The only log i get is: 
`2018-12-13T11:55:37.448579542Z app[web.1]: Started GET "/sidekiq/" for xxx.xxx.xxx.xxx at 2018-12-13 11:55:37 +0000`
