### ISSUE TITLE
Feature Request: Process newest/latest job in queue

### ISSUE THREAD

**Issue by xanview** [mperham/sidekiq#3420]
Any way to tell Sidekiq to always process the newest/latest job in a specific queue? -- I have a specific queue which needs to always do the newest job and catch up on older ones later in the day. Any way to achieve that?

For example:

```
item1 -> queue1
item2 -> queue1
item3 -> queue1
sidekiq <- item3
item4 -> queue1
item5 -> queue1
sidekiq <- item5
sidekiq <- item4
sidekiq <- item2
sidekiq <- item1
```

**Comment by mperham** [comment]
Queue processing is always FIFO.  Your scheme means that it is possible that item1 will never be processed at all, aka starvation, which is rarely a desirable trait.  Queue prioritization is the only tuning mechanism to control which job Sidekiq will pull next.

**Comment by xanview** [comment]
Yes, what I want to achieve is queue starvation and then a periodic cron job to clear the jobs that will never be processed. How would one achieve this?

**Comment by mperham** [comment]
I'd suggest asking on StackOverflow.  Sidekiq can't do this and this isn't a venue for solving arbitrary programming problems.
