### ISSUE TITLE
Putting Batch job

### ISSUE THREAD

**Issue by ACPK** [mperham/sidekiq#3423]
Ruby version: Pro
 
How would I put a batch job inside of a batch job, so that the main job doesn't get marked as "successful" if any of the sub-batch jobs fail?

For example, this is the first batch job and Sidekiq Pro marked it as running 100% successful.

    def step2(status, options)
      scheduled_time = options["scheduled_time"]

      update_quovo_accounts_batch = Sidekiq::Batch.new
      update_quovo_accounts_batch.description = 'Download data test.... '
      update_quovo_accounts_batch.on(:complete, self.class)
      update_quovo_accounts_batch.on(:success, 'DailyWorkflowJob#step3', 'scheduled_time' => scheduled_time)

      update_quovo_accounts_batch.jobs do
        User.all.each do |user|
          UserSyncJob.perform_async(user.id, scheduled_time)
        end
      end
    end

Within that batch, I make a call to another batch (i.e. UserSyncJob). 100% of that batch failed but Sidekiq said that the main batch completed 100%.

    class UserSyncJob
      include Sidekiq::Worker

      def perform(user_id, scheduled_time)
        user = User.find(user_id)

        batch = Sidekiq::Batch.new
        batch.description = "Updating user-#{user.id} accounts"
        batch.on(:success, self.class, 'user_id' => user_id)
        batch.jobs do
          user.accounts.where.not(status: 'login').each do |account|
            AccountSyncJob.perform_async(account.id, scheduled_time)
          end
        end
        puts "Just started batch for user-#{user.id}"
      end

I'm all ears if you have any recommendations my Sidekiq batch jobs!

Thank you in advance.

**Comment by mperham** [comment]
If you want to create a child batch within a parent batch, you need to reopen the parent batch and create the child batch within it:

```ruby
  def step1_done(status, options)
    overall = Sidekiq::Batch.new(status.parent_bid)
    overall.jobs do
      step2 = Sidekiq::Batch.new
      step2.on(:success, 'FulfillmentCallbacks#step2_done', 'oid' => oid)
      step2.jobs do
        B.perform_async
      end
    end
  end
```

Each child batch is a sequential step in the overall workflow.  If you link the batches, the parent batch will not fire the {complete,success} callback until the child batch has fired that callback.

**Comment by ACPK** [comment]
@mperham - Thank you!

**Comment by mperham** [comment]
I don't understand your question.

**Comment by ACPK** [comment]
@mperham - I get the error below as the sub-batch is inside of  "UserSyncJob.perform_async".

    NameError: undefined local variable or method `status' for #

**Comment by mperham** [comment]
The code snippet I gave was designed to run inside a callback, not a job, where you have a status argument.

**Comment by ACPK** [comment]
@mperham - Yes.

**Comment by ACPK** [comment]
@mperham - I tried the following, but got get the error "RuntimeError: Batch xdAQ has finished, you cannot modify it anymore".

    UserSyncJob.perform_async(user.id, scheduled_time, batch.bid)


      def perform(user_id, scheduled_time, pid)
      user = User.find(user_id)
      status = Sidekiq::Batch::Status.new(pid)
      overall = Sidekiq::Batch.new(status.parent_bid)
      overall.jobs do
        batch = Sidekiq::Batch.new
        
        ....
      end
    end

**Comment by mperham** [comment]
Can you gist all your batch code?  That snippet looks very wrong, you can only reopen the parent batch in a callback. You can reopen the associated batch or its parent batch within a batch job.

**Comment by ACPK** [comment]
@mperham - I got the code above working.
