### ISSUE TITLE
FetchError: bad response Unauthorized 401 (URL.gem) An error occurred while installing sidekiq-pro (3.4.5), and Bundler cannot continue. Make sure that `gem install sidekiq-pro -v '3.4.5'` succeeds before bundling.

### ISSUE THREAD

**Issue by Hareesh007** [mperham/sidekiq#3426]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
Your subscription has expired. You'll need to buy a new one if you wish to continue using Sidekiq pro. Please email me if you wish to discuss further. .
