### ISSUE TITLE
Bundler::HTTPError Could not fetch specs from https://gems.contribsys.com/

### ISSUE THREAD

**Issue by ACPK** [mperham/sidekiq#3427]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Pro

I started receiving the following error about an hour ago when trying to deploy to production.

    Bundler::HTTPError Could not fetch specs from https://gems.contribsys.com/

**Comment by kelishrestha** [comment]
Same here 👎 
Ruby version: *2.3.0*

`Could not fetch specs from https://gems.contribsys.com/`

**Comment by TheWudu** [comment]
Same here .. 
JRuby-Version 9.0.4.0. 

`Bundler::HTTPError Could not fetch specs from https://enterprise.contribsys.com/`

**Comment by TheTeaNerd** [comment]
+1, I'm getting `Bundler::HTTPError Could not fetch specs from https://enterprise.contribsys.com/`

**Comment by smeyfroi** [comment]
Same: this is blocking our production deployments using sidekiq-ent.

@mperham Could we get a status update soon so we can plan around the issue please?

**Comment by matthewbennink** [comment]
Same. Heroku build hangs with `Fetching source index from https://gems.contribsys.com/`.

**Comment by iMacTia** [comment]
Same here, https://gems.contribsys.com/ is timing out.
Production deploy blocked.
Anyone aware of a quick fix? We don't really need to update Sidekiq, we just need to deploy with Capistrano

**Comment by dawidpawliszko** [comment]
+1

**Comment by austinwang** [comment]
+1

**Comment by saveyou** [comment]
+1

**Comment by a-setyadi** [comment]
+1. Same here.

**Comment by oricodes89** [comment]
+1

**Comment by rohandaxini** [comment]
Same issue for us as well, unable to deploy due to these failures for `bundle install`
URL https://gems.contribsys.com/ is down

**Comment by ffiller** [comment]
+1

**Comment by scottrobertson** [comment]
+1

**Comment by TruptiPotdar-Edmodo** [comment]
+1

**Comment by pachkovsky** [comment]
Our CD broken because of this!

**Comment by thapakazi** [comment]
Damn, it could break our autoscaling 😠 minions...

**Comment by ryantownsend** [comment]
According to various people on Twitter, this outage is caused by Digital Ocean – https://status.digitalocean.com

**Comment by asanghi** [comment]
We vendored the gem from our development environment and checked it in into our repo to proceed.

**Comment by prasathsarath** [comment]
@asanghi : Im getting the Could not find gem 'sidekiq-pro' in source at 'location_of_gem_folder in vendor'
Source does not contain any versions of 'sidekiq-pro'

**Comment by Bivek** [comment]
@iMacTia if it working fine in your dev env you can `bundle package` as a workaround for now

**Comment by iMacTia** [comment]
@Bivek I was able to `bundle package` from another project and got the .gem file to use in production so we're now fine.
Anyway, it's not an absolute working solution as in another project `bundle package` is trying to contact the https://gems.contribsys.com server

**Comment by douglascamata** [comment]
"enterprise" gem's host doesn't have a mirror outside of the Digital Ocean SF datacenter that is affected? A bit lame.

**Comment by zoras** [comment]
Guys, try mirroring your own local `gem server` with `gemirro`. I've partial success with with
http://guides.rubygems.org/run-your-own-gem-server/

**Comment by svenfuchs** [comment]
@prasathsarath you'll need to copy the `gemspec` over, too

```
mkdir -p vendor
gem=$(bundle show sidekiq-pro)
cp -r $gem vendor/sidekiq-pro
cp "$gem/../../specifications/sidekiq-pro-3.4.0.gemspec" vendor/sidekiq-pro/

# Gemfile:
# gem 'sidekiq-pro', path: 'vendor/sidekiq-pro'

bundle install
```

**Comment by mperham** [comment]
Server outage has been resolved.  I do have a warm backup server running at all times but use DNS failover which needs to be triggered manually.  I have server uptime monitoring which worked perfectly but unfortunately I was asleep during this outage.  I apologize for the delayed response; I will look into how I might get my phone to wake me up in this instance.

**Comment by mperham** [comment]
As someone pointed out, the root cause was an extended datacenter outage at DigitalOcean SFO2.

**Comment by svenfuchs** [comment]
@mperham #ophugs ❤️

**Comment by smeyfroi** [comment]
@mperham have you considered (something like) https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring.html to avoid manual intervention?

**Comment by douglascamata** [comment]
@mperham we don't need you to wake up, it needs to be done automatically.

**Comment by thapakazi** [comment]
Thanks @mperham 

Next time maybe, we would have some dedicated workers ready to `SIG9` you up bad  :neckbeard: 
![sig_9_alarm_for_programmers](https://cloud.githubusercontent.com/assets/1695906/24913846/251902fc-1ef2-11e7-82d4-fc8687063912.gif)

**Comment by ryansch** [comment]
@mperham I've had good experiences with using PagerDuty.  I can set it to call me twice inside of 5 minutes to punch through iOS's do not disturb.

**Comment by corytheboyd** [comment]
On the subject of PagerDuty, their mobile application has a setting to override your phone's system volume. Useful for when you don't want normal notifications to wake you up, but you want pages to be loud and clear. Furthermore, the alert sounds feature such hits as "Cry", "Network's Down", and "Server's On Fire" ;)

**Comment by mperham** [comment]
PagerDuty is sounding pretty good, I'll evaluate it.  My current monitor, UptimeRobot, doesn't have any notification support beyond a simple email.

**Comment by mperham** [comment]
For future reference, this is the best place to ask about server status.  Everyone sending me individual emails and DMs only jams my inbox.

Some steps I've taken this morning:

1. New status site: https://status.sidekiq.org/
2. PagerDuty purchased, installed on phone and integrated with UptimeRobot.
3. New gem server replica built (the two current servers are in Toronto and Frankfurt)

Again, sorry for the extended outage and I hope these steps will prevent any further late night outages.

**Comment by mperham** [comment]
(If anyone wants to send me a 400x200 image that doesn't look terrible for that status page logo, I would be forever grateful)

**Comment by ACPK** [comment]
@mperham - I noticed that this was closed. Will there be an automated fix in the future?

**Comment by mperham** [comment]
It's certainly possible and something I'd like to get to but there's no quick solution that I know of today.

**Comment by rhazegh** [comment]
Happening now:

```
       Fetching source index from https://gems.contribsys.com/
       
       Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://gems.contribsys.com/
       Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.contribsys.com/
       Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://gems.contribsys.com/
       Could not fetch specs from https://gems.contribsys.com/
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by ricardson** [comment]
yes... again...

**Comment by minghz** [comment]
+1

**Comment by ricardson** [comment]
+1

**Comment by aHaydenLSS** [comment]
+1

**Comment by aleccarper** [comment]
+1

**Comment by liyucun** [comment]
+1

**Comment by ideaoforder** [comment]
+1

**Comment by g24fitzgerald** [comment]
+1

**Comment by jsilvia721** [comment]
+1

**Comment by aHaydenLSS** [comment]
Looks to be up and running again. Worked for me, anyways.

**Comment by remotezygote** [comment]
Status page says up, but it's still completely unreachable for me.

**Comment by mperham** [comment]
DNS caching.

**Comment by scottrobertson** [comment]
Fine here

**Comment by thiagoao** [comment]
+1

**Comment by tinbka** [comment]
+1

**Comment by mperham** [comment]
The gem server moved from NYC to Amsterdam this weekend (due to scheduled DO maint in NYC).  I had one other customer report trouble and it was because they were geo-fencing their allowed network connections.

If you suddenly have problems, please check the https://status.sidekiq.org page.  If that is green, please assume the trouble is on your end.  Either due to Bundler misconfig, network policies or account cancellation.
