### ISSUE TITLE
Recurrence - executing at specific time in every time zones

### ISSUE THREAD

**Issue by chadwtaylor** [mperham/sidekiq#3429]
Is there a strategy to execute a recurrence at a specific time for every time zones across the globe?

For example, execute a task every day at:

```
...
8:00 PM EST
8:00 PM CST
8:00 PM MST
8:00 PM PST
...

**Comment by mikegee** [comment]
How is this different than hourly?

**Comment by mperham** [comment]
Sidekiq doesn't have a recurrence feature.  You can investigate the [various cron options](https://github.com/mperham/sidekiq/wiki/Related-Projects#recurring-jobs) to see what they offer.
