### ISSUE TITLE
Feature Request: Pro: Setting for amount of jobs pulled from scheduler

### ISSUE THREAD

**Issue by kainage** [mperham/sidekiq#3431]
Ruby version: 2.4.1
Sidekiq version: 4.2.10 / 3.4.2

We have a massive application using (some might say abusing) sidekiq. We schedule jobs **a lot** and frequently have 1000's that need to be pulled per call from the scheduled set into the queues.

We cannot upgrade sidekiq pro any higher version 3.4.2 because of this change:

```
Limit reliable scheduler to enqueue up to 100 jobs per call, minimizing Redis latency [#3332]
```

Can you make this an optional or allow us to set this value?

**Comment by mperham** [comment]
I think you are misinterpreting the change.  The change is that the scheduler thread calls a Lua script, which enqueues up to 100 jobs per invocation.  **If 100 jobs are scheduled, it will call the script again until the script returns less than 100.**

Your 1000 jobs will be scheduled by 10 calls to the script in a loop.  The advantage is that the 10 calls give Redis a chance to do other work in the meantime so the scheduler does not monopolize Redis and spike latency.

**Comment by kainage** [comment]
Hmm okay. That makes sense. It must be something else causing the jobs to not be picked up fast enough and start backing up. The jobs started sitting there and the time keeps going into the future saying "20 seconds ago" etc. Is there something else you can think of for me to look for? It's tough to reproduce _not_ in production and I don't really want to test it out there again heh.

**Comment by mperham** [comment]
There's #3430 and was a serious bug with the scheduler in 3.4.3 and 3.4.4 where it was dropping jobs.  Did you test 3.4.5?

**Comment by kainage** [comment]
No I have not. Haven't tried since rolling back to 3.4.2.  I will test out on 3.4.5 and see what results I get. Thank you sir.
