### ISSUE TITLE
Sidekiq::Batch: on_success callback firing before all batched jobs succeeded

### ISSUE THREAD

**Issue by danapczynski** [mperham/sidekiq#3432]
### Our Workflow
We have a fairly straightforward `Sidekiq::Batch` workflow, in which we batch several thousand jobs that insert rows into a handful of temporary tables in Postgres. When we finish the batched jobs, we fire an `on_success` callback that renames the temporary tables. We deeply depend on `on_success` indicating a 100% success rate in the batched jobs; if batched jobs are somehow still running at the time the callback fires, then the import tables are no longer there when they finish and we get an ugly error.

### The Problem
This approach usually works fine, but we've witnessed the ugly case described above when deploys take place while the batched jobs are running. We end up with 99.9% of the jobs completing as normal, having `on_success` fire, then seeing some other jobs attempting to complete and triggering Postgres errors because they can't find the temporary tables (which have already been renamed). 

### The Band-Aid
As an interim solution, I've wrapped the table-rename process in its own job (still triggered in `on_success`), and delayed it by several minutes so that any stragglers have a chance to finish. This appears to be working for now, but we'd like to get to the root of the problem and structure this job correctly if at all possible.

### Job Code
```
class MakeMeSadJob
  include Sidekiq::Worker

  def perform(some_option = "some_value")
    batch = Sidekiq::Batch.new
    batch.on(:success, self.class, "some_option" => some_option)

    batch.jobs do
      enqueue_a_bunch_of_jobs_that_insert_rows_into_temporary_tables
    end
  end

  def on_success(_status, options)
    method_that_logs_stuff("Successfully inserted all the things! #{options['some_option']}")

    # Doing the following without delaying leads to Postgres errors in any batched jobs
    # that haven't finished successfully, because temporary tables can no longer be found.
    # But.. all jobs were supposed to have finished successfully?
    rename_temporary_tables
  end
end
```

### Ruby version: 
```
2.4.1p111
```
### Sidekiq / Pro / Enterprise version(s): 
```
sidekiq (4.2.10)
sidekiq-pro (3.4.5)
```

### Initializer Code

```
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.redis = { url: <secret> }
  config.options[:ephemeral_hostname] = true
  config.super_fetch!
  config.reliable_scheduler!

  config.server_middleware do |chain|
    chain.add SidekiqMemoryProfile
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: <secret> }
end

Sidekiq::Logging.logger = Rails.logger
```

**Comment by mperham** [comment]
I don't really have any way to debug the problem. Can you give me a small app or script which reproduces the problem?

**Comment by mperham** [comment]
It would also help greatly if you showed the exact batch code you are executing.  Any code blocks associated with the batch and any callbacks in any way.
