### ISSUE TITLE
How do I configure the global timeout for timed_fetch?

### ISSUE THREAD

**Issue by vergenzt** [mperham/sidekiq#3433]
I'm considering purchasing Pro and was looking at the [server reliability](https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server) docs; a "con" mentioned under the `timed_fetch` option was:

> All jobs must finish within the global job timeout or they can be re-executed.

Is that global timeout configurable? I didn't see documentation anywhere on how to set it.

**Comment by mperham** [comment]
super_fetch is the recommended fetch strategy.  timed_fetch should be considered deprecated, is there a particular reason you want to use it in particular?

The timeout is the optional parameter, defaulting to 3600: `config.timed_fetch!(7200)`

**Comment by vergenzt** [comment]
> super_fetch is the recommended fetch strategy. timed_fetch should be considered deprecated, is there a particular reason you want to use it in particular?

Ahh okay that makes sense. The docs only mentioned that `reliable_fetch` was deprecated and I wasn't sure how stable `super_fetch` was considered at this point. If it's recommended though I'll go with that.

Thanks!

**Comment by mperham** [comment]
I just rejiggered the wiki page to make the current status of everything clearer.
