### ISSUE TITLE
Questions/some comments about ActiveJob integration

### ISSUE THREAD

**Issue by vergenzt** [mperham/sidekiq#3434]
1. (Question)

    From the [Sidekiq/ActiveJob wiki page](https://github.com/mperham/sidekiq/wiki/Active-Job):

    > Note that more advanced Sidekiq features (sidekiq_options) cannot be controlled or configured via ActiveJob, e.g. saving backtraces.

    Does _global_ worker configuration via `Sidekiq.default_worker_options` work when using ActiveJob?

2. (Question)

    From the same wiki page:

    > **Commercial Features**
    >
    > Many of Sidekiq Pro and Sidekiq Enterprise's features will break in unpredictable ways if you try to use ActiveJob with those features. For instance, creating ActiveJobs within a Batch will work in the base case but fail if you use ActiveJob's retry mechanism in those jobs. When in doubt, don't mix your use of AJ with Sidekiq's native APIs.

    Does using ActiveJob interfere with any of the worker-side fetching options provided by Pro like `super_fetch!` or `reliable_scheduler!`?

3. (Note)

   I just thought I'd mention that ActiveJob's `queue_as :some_queue_name` does work with Sidekiq queues, so if you don't need to tune retries or backtraces ActiveJob works. :)

**Comment by mperham** [comment]
1. Yes, it works.
2. Not that I know of but I can't guarantee anything about ActiveJob since I don't control its direction.  Their retry support is an example of them adding a feature which breaks many Sidekiq features.
3. Yep, good point.
