### ISSUE TITLE
Web: Localization in wrong language in Chrome & Safari (Mac)

### ISSUE THREAD

**Issue by johanlunds** [mperham/sidekiq#3437]
**Ruby version:** 2.4
**Sidekiq / Pro / Enterprise version(s):** sidekiq (4.2.10), sidekiq-pro (3.4.5)

**Chrome version:** 57.0.2987.133 (stable)
**Safari version:** 10.0.3
**OS version:** 10.12.3 (macOS Sierra)

~~Please include your initializer and any error message with the full backtrace.~~

**Are you using an old version?** No
**Have you checked the changelog to see if your issue has been fixed in a later version?** Yes

## Description

**Reproduce:** Set OS localization settings like mine (see screenshot below). I have it set as English primary and Swedish secondary. All other apps in the OS will be localized in English with these settings. Open Chrome. Go then to the Sidekiq Web GUI. Do the same in Safari.

**Expected behavior:** In **both Chrome & Safari** Sidekiq Web GUI should be localized in **English.**

**Actual behavior:**  In **Chrome** Sidekiq Web GUI is localized in **Swedish**. In **Safari** it works as expected - it is in **English**.

**Investigation:**

Header sent in Chrome request is `Accept-Language: en-US,sv-SE;q=0.8,sv;q=0.6,en;q=0.4`.

Safari doesn't seem to send a `Accept-Language` header (?). Using the Ruby debugger I see that `env['HTTP_ACCEPT_LANGUAGE']` is `en-us` then.

**Screenshot of OS settings:** 

![language___region_and_new_issue_ _mperham_sidekiq](https://cloud.githubusercontent.com/assets/22144/25136281/e0eb9d8e-2454-11e7-8d82-f489f26b04bd.png)

**Comment by johanlunds** [comment]
Further testing: switching the OS locale settings to be (1) Swedish preferred, (2) English secondary (and restarting Safari so it is now in Swedish), the Sidekiq Web GUI is still in English.

Expected behavior would be that it is in Swedish (since that is the primary, preferred language set in the OS settings).

Inspecting the request in Safari:

![_development__sidekiq_pro_and_web__localization_in_wrong_language_in_chrome__mac__ _issue__3437_ _mperham_sidekiq](https://cloud.githubusercontent.com/assets/22144/25137595/8960ab46-2458-11e7-8398-8e82399ca298.png)

However, using a Ruby debugger to inspect the Rack request gives `env['HTTP_ACCEPT_LANGUAGE'] # => "sv-se"` so it is obviously sent by Safari.

**Comment by johanlunds** [comment]
I think the bug is that `en-US` in `Accept-Language: en-US,sv-SE;q=0.8,sv;q=0.6,en;q=0.4` should be interpreted as `en-US;q=1.0`.

These Rack Utils methods can be used: https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L131-L155

Current code in Sidekiq is: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web/helpers.rb#L80-L91

Still, there might be an issue with `en-US` vs `en` vs `sv-SE` vs `sv` perhaps?

I tried to dig a little bit into how Rails and I18n `I18n.locale = ` decides on those cases, but did not figure it out completely. [1](https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L275-L286), [2](https://github.com/svenfuchs/i18n/blob/master/lib/i18n/config.rb#L11-L59)

**Comment by mperham** [comment]
I'd love a PR which switches the web helper to use that Rack::Utils method.  That header value syntax is so convoluted, I'm sure I got the parsing logic wrong somehow.
