### ISSUE TITLE
Sidekiq Pro 4.2.10 is not processing

### ISSUE THREAD

**Issue by PratheepV** [mperham/sidekiq#3438]
We recently tried upgrading sidekiq from 3.5.4 to 4.2.10 and  sidekiq-pro from 2.1.5 to 3.4.5. Its starting but not processing any job.  Even ctrl+c is not even killing the process in dev.

we are using rails 5.0.2, Running in ruby 2.3.1p112.  Please help us debugging.

Gem versions:
Sidekiq: **4.2.10** (was 3.5.4)
Sidekiq Pro: **3.4.5**(was 2.1.5)
rails: **5.0.2** (was 4.2.7.2)

My initializer 
```ruby
require 'redis-namespace'

config = Rails.application.config_for(:sidekiq_redis)
sidekiq_config = Rails.application.config_for(:sidekiq)

$sidekiq_conn = Redis.new(:host => config["host"], :port => config["port"])
$sidekiq_datastore = proc {
  Redis::Namespace.new(config["namespace"], :redis => $sidekiq_conn) }
$sidekiq_redis_pool_size = sidekiq_config[:concurrency]
$sidekiq_redis_timeout = sidekiq_config[:timeout]


Sidekiq.default_worker_options = { 'retry' => true, 'queue' => 'default', 'backtrace' => true }
Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(:size => 1,
    :timeoout => $sidekiq_redis_timeout, &$sidekiq_datastore)
  config.client_middleware do |chain|
    chain.add Sidekiq::CurrentUser::Client
  end
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(:size => $sidekiq_redis_pool_size,
    :timeoout => $sidekiq_redis_timeout, &$sidekiq_datastore)
  config.reliable_fetch!

  config.client_middleware do |chain|
    chain.add Sidekiq::CurrentUser::Client
  end

  config.server_middleware do |chain|
    chain.insert_before ActsAsTenant::Sidekiq::Server, Sidekiq::Sharding::Server
    chain.insert_after ActsAsTenant::Sidekiq::Server, Sidekiq::CurrentAccount::Server
    chain.insert_after Sidekiq::CurrentAccount::Server, Sidekiq::CurrentUser::Server

    # http://stackoverflow.com/questions/28412913/disable-automatic-retry-with-activejob-used-with-sidekiq
    chain.add Sidekiq::Middleware::Server::RetryJobs
  end
end
```

**Comment by mperham** [comment]
Please define the values for the various $redis_* variables.

**Comment by PratheepV** [comment]
sidekiq_redis.yml
```yml
defaults: &defaults
  host: localhost
  port: 6379
  namespace: sidekiqjobs

development:
  <<: *defaults

test:
  <<: *defaults
  namespace: testsidekiqjobs
```

sidekiq.yml
```yml
defaults: &defaults
  :verbose: true
  :concurrency: 5
  :logfile: ./log/sidekiq.log
  :timeout: 30
  :queues:
    - [default]

development:
  <<: *defaults

test:
  <<: *defaults
```
run command

```ruby
bundle exec sidekiq -C config/sidekiq.yml
```

**Comment by mperham** [comment]
It's likely that your $sidekiq_redis_pool_size is too low but you haven't defined that.

**Comment by PratheepV** [comment]
changed the concurrency to **20**, still its not processing. Another observation is sidekiq is not killing by **ctrl+c** command.

**Comment by mperham** [comment]
What is the value of that variable?

**Comment by PratheepV** [comment]
Its **20**(was 5) currently. I am using **concurrency** value which is defined in sidekiq.yml.

**Comment by mperham** [comment]
Did you read the 3rd bullet point of the upgrade notes?

https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md#whats-new

**Comment by mperham** [comment]
Oops, 4th

**Comment by mperham** [comment]
Please remove `:size => $sidekiq_redis_pool_size` from your server pool.

**Comment by PratheepV** [comment]
removed ```:size => $sidekiq_redis_pool_size``` and still its not processing.

**Comment by mperham** [comment]
Sorry  I forgot that if you hand sidekiq the pool manually you also need to specify the size explicitly so you should set the size to concurrency +2

**Comment by PratheepV** [comment]
changed to ```:size => $sidekiq_redis_pool_size+2``` and still its not processing.

**Comment by mperham** [comment]
🤷‍♂️  No clue what's wrong then.  Try Rails 4.2.7.2, I've heard of lockups in dev mode using Rails 5.

**Comment by mperham** [comment]
In general, it's a good idea to upgrade one thing at a time.  Upgrade Sidekiq, get it running, and then upgrade Rails.

**Comment by PratheepV** [comment]
In rails 4.2.7.2 also its same.  If I use sidekiq 3.5.4, its working in both rails 4 and rails 5.

**Comment by mperham** [comment]
Can you show us the first dozen lines of logging with `-v` enabled?  If you hard code `:size => 100` in both client and server, does it work?

**Comment by PratheepV** [comment]
I am using ``` config.active_job.queue_adapter = :sidekiq ```. Does this has any impact.

**Comment by mperham** [comment]
no

**Comment by PratheepV** [comment]
bundle exec sidekiq -v -C config/sidekiq.yml
```log
2017-04-19T04:04:58.352Z 20720 TID-ouwquckro DEBUG: Autoload disabled in development, Sidekiq will not reload changed classes
2017-04-19T04:04:58.681Z 20720 TID-ouwquckro INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
2017-04-19T04:04:58.682Z 20720 TID-ouwquckro INFO: Sidekiq Pro 3.4.5, commercially licensed.  Thanks for your support!
2017-04-19T04:06:36.173Z 20733 TID-oupf1km44 DEBUG: Autoload disabled in development, Sidekiq will not reload changed classes
2017-04-19T04:06:36.468Z 20733 TID-oupf1km44 INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
2017-04-19T04:06:36.468Z 20733 TID-oupf1km44 INFO: Sidekiq Pro 3.4.5, commercially licensed.  Thanks for your support!
2017-04-19T04:07:31.349Z 20740 TID-ovb1yerrg DEBUG: Autoload disabled in development, Sidekiq will not reload changed classes
2017-04-19T04:07:31.624Z 20740 TID-ovb1yerrg INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
2017-04-19T04:07:31.624Z 20740 TID-ovb1yerrg INFO: Sidekiq Pro 3.4.5, commercially licensed.  Thanks for your support!
2017-04-19T04:08:39.223Z 20753 TID-oxgj3j76s DEBUG: Autoload disabled in development, Sidekiq will not reload changed classes
2017-04-19T04:08:39.534Z 20753 TID-oxgj3j76s INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
2017-04-19T04:08:39.534Z 20753 TID-oxgj3j76s INFO: Sidekiq Pro 3.4.5, commercially licensed.  Thanks for your support!

**Comment by mperham** [comment]
That logging only generates more questions.  Why is it repeating four times like that?  Why is your autoload disabled?  I don't know what is printing out `Autoload disabled in development, Sidekiq will not reload changed classes`, as neither 3.5.4 or 4.2.10 log that line.  And where's the "Booting Sidekiq x.y.z with redis options {...}" line?

It looks like your application is configured so non-standard that you'll need to debug this yourself.  This is not unusual for larger, older Rails apps.  You can use the TTIN signal to determine why Sidekiq is stuck after Ctrl-C.

**Comment by PratheepV** [comment]
Its not repeating, its just has previous run logs also. 

Let me clean my gemset and try upgrading.

**Comment by DrMavenRebe** [comment]
Did anything come of this? Any troubleshooting techniques you found useful?

**Comment by PratheepV** [comment]
@DrMavenRebe I tried with clean gemset still its not processing.

**Comment by mperham** [comment]
I think you'll need to give me an app which reproduces the problem.  This has to be something specific to your environment but I'm at a loss to help more.

**Comment by DrMavenRebe** [comment]
Just a small update on our end. We discovered that we had locking issues with our logging service. It looked like sidekiq was getting stuck but it was actually unrelated.

**Comment by PratheepV** [comment]
@mperham attaching gdb backtrace 

```
Thread 3 (Thread 0x1a03 of process 87895):
#0  0x00007fff9400507a in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010a0ae459 in ?? () from /Users/pratheepv/.rvm/rubies/ruby-2.3.1/lib/libruby.2.3.0.dylib
#2  0x00007ff71126487c in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x1903 of process 87895):
#0  0x00007fff940062a2 in poll () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010a0b2843 in ?? () from /Users/pratheepv/.rvm/rubies/ruby-2.3.1/lib/libruby.2.3.0.dylib
#2  0x0001000100000003 in ?? ()
#3  0x0000000100000005 in ?? ()
#4  0x7c00ff00e9d34bb1 in ?? ()
#5  0x0000700000005000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x8b0

Thread 1 (Thread 0x1803 of process 87895):
#0  0x00007fff94004db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff8ffdb728 in ?? () from /usr/lib/system/libsystem_pthread.dylib
#2  0x0000000000000000 in ?? ()
Detaching from program: /Users/pratheepv/.rvm/rubies/ruby-2.3.1/bin/ruby, process 87895
```

**Comment by mperham** [comment]
@PratheepV That's not a valid GDB backtrace.  GDB backtraces are hundreds of lines long.  It looks like you're missing debug symbols in your Ruby build, for one.

**Comment by PratheepV** [comment]
@mperham when I remove ConnectionPool.new and pass redis config hash, its started processing.

**Comment by mperham** [comment]
There's no reason to pass a connection pool, all of those items can be configured with the hash.

**Comment by PratheepV** [comment]
@mperham I agree but sidekiq do support connection pool and I tried debugging why its not processing with connection pool but no luck. I tried even with sidekiq 5. Does Sidekiq supports only redis hash from now on? Correct me if I am wrong.

**Comment by mperham** [comment]
Sidekiq supports both but when you pass a pool, Sidekiq can't size it as necessary, so you can give a pool that is too small.
