### ISSUE TITLE
There is no way to access the `perform_in` interval set for a specific worker

### ISSUE THREAD

**Issue by tiagonbotelho** [mperham/sidekiq#3439]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): Sidekiq

`RepositoryUpdateRemoteMirrorWorker.perform_in(backoff_delay.seconds, self.id, Time.now)`

Hello,

Since the `backoff_delay` is dynamic I wanted to check that it is actually working in my test suite but for some reason I can't seem to find a way to access that interval. Is this intended behaviour? Is there a way of doing it? If not should it be implemented?

Thank you 😄

**Comment by mperham** [comment]
You're looking for the 'at' attribute in the job payload.

```ruby
require 'sidekiq/testing'

time = 1.hour.from_now.to_f
FooWorker.perform_at(time)
assert_equal time, FooWorker.jobs.first['at']
```
