### ISSUE TITLE
Sidekiq::JobSet#find_job efficiency

### ISSUE THREAD

**Issue by tjohnell-handy** [mperham/sidekiq#3440]
Ruby version:
Latest Sidekiq Ent

Hey Mike,

We use the sidekiq debounce gem to delay processing a lot of repeat jobs, and it has worked wonderfully.  However, I noticed a particular endpoint of mine was taking quite a long time to process a worker:
![image](https://cloud.githubusercontent.com/assets/13623283/25360284/7d849c0c-2916-11e7-91f2-84d93c8a408c.png)

I should note that only one worker is attempted to be enqueued this instance.

Upon investigating, `zscan` is being called thousands of times and it's taking quite a long time to process.  The debounce gem uses two methods within the `Sidekiq` api that that could potentially be the culprit:

`Sidekiq::JobSet#find_job` and `Sidekiq::SortedEntry#reschedule`

I'm pretty sure it's `find_job`, using Sidekiq Pro's beefier version with `zscan_each`. I was wondering if you could provide any insight on why this search could be so slow in some cases.  I've tried running this on a quite a few jids in production with very little to no delay, so I've not been able to repro.  I thought it might be due to the number of scheduled jobs we have.  Any insight helps, thanks.

**Comment by mperham** [comment]
There's no way to implement debounce efficiently in Sidekiq, that's why my products don't provide it. You are hitting that scalability wall.

**Comment by tjohnell-handy** [comment]
That scalability wall being the lookup for a job by jid?

**Comment by mperham** [comment]
Yes, The lookup is O(N) so it's slow. Designed for manual operations in the Web UI only.

**Comment by tjohnell-handy** [comment]
Thanks for the quick response. I'll close this.  I'm going to look into implementing a quicker debounce using the cancellation strategy outlined in the wiki.
