### ISSUE TITLE
Weird behavior after child process restarted by swarm

### ISSUE THREAD

**Issue by rafaelsales** [mperham/sidekiq#3447]
Ruby version:
Sidekiq / Pro / Enterprise version(s): sidekiq 5.0.0.rc1 and enterprise 1.5.2

We are seeing a weird behavior in our app each time a child sidekiq process is restarted by swarm due to memory bloat, and would like to know if you think this could be related to how swarm spawns a new child process after a memory bloat.

The error is an unexpected Rails JSON serialization (`serialize :attribute, JSON`) when inserting records, and it only happens on a child process that was restarted by sidekiq swarm. Here are two examples that I found in the logs, the former with wrong serialization and latter with correct serialization. Both occurred in different threads.

```
# wrong
D, [2017-04-28T06:12:33.994780 #14614] DEBUG -- :   SQL (65.1ms) INSERT INTO `events` (`metadata`) VALUES ('\"{\\\"foo\\\":\\\"bar\\\"}\"')
```

```
# correct
D, [2017-04-28T06:12:33.340745 #12230] DEBUG -- :   SQL (4.1ms) INSERT INTO `events` (`metadata`) VALUES ('{\"foo\":\"bar\"}')
```

These inserts with serialization happens many times per minute, and I observed that when a thread presents the issue, it does from the first insert to the last of its lifetime. Threads that don't present the issue, never present it in its lifetime.

This can totally be not related to sidekiq, but the fact that it only happens in one thread and only after a child process restarts is what makes us think it could be related to sidekiq.

Thanks

**Comment by mperham** [comment]
Looks double encoded to me but I have no idea how Rails could get into that bad state.  Are you on the latest patch version of Rails?

**Comment by mperham** [comment]
How are you starting sidekiqswarm?

**Comment by rafaelsales** [comment]
Yes, the effect is exactly double serialization (`.to_json.to_json`)

Our upstart conf:
```
description "Sidekiq Swarm"

setuid deployer
env HOME=/home/deployer

stop on runlevel [06]

start on runlevel [2345]
respawn
respawn limit 3 30

# TERM is sent by sidekiqctl when stopping sidekiq. Without declaring these as
# normal exit codes, it just respawns.
normal exit 0 TERM

env SIDEKIQ_COUNT=5
env SIDEKIQ_MAXMEM_KB=512000
env SIDEKIQ_PRELOAD=

script
exec /bin/bash <<'EOT'
  cd /home/deployer/project/current
  exec bin/sidekiqswarm --tag project -e production -r . -c 10
EOT
end script
```

We are updating to latest Rails just in case

**Comment by mperham** [comment]
Any outcome?

**Comment by rafaelsales** [comment]
@mperham Thanks for following up with this. We found out the issue was related to rails AR schema loading: https://github.com/rails/rails/issues/28589
