### ISSUE TITLE
Uninitialized constant Sidekiq::CronParser

### ISSUE THREAD

**Issue by spinx** [mperham/sidekiq#3458]
Ruby 2.4.0
Using sidekiq 5.0.0
Using sidekiq-pro 3.5.0
Using sidekiq-ent 1.5.3

When upgrading to 5.0 and opening web ui at CRON tab, it blows up with this error. Can't figure out why it is not loading properly. Tried the usual re-install and such. 

`
10.10.0.1 - - [04/May/2017:17:31:26 +0100] "GET /limits HTTP/1.1" 200 5540 0.0067
NameError: uninitialized constant Sidekiq::CronParser
	/gems/sidekiq-ent-1.5.3/lib/sidekiq-ent/periodic.rb:58:in `next_run'
	(erb):22:in `block in _erb'
	/gems/sidekiq-ent-1.5.3/lib/sidekiq-ent/periodic.rb:37:in `block in each'
	/gems/sidekiq-ent-1.5.3/lib/sidekiq-ent/periodic.rb:36:in `each'
	/gems/sidekiq-ent-1.5.3/lib/sidekiq-ent/periodic.rb:36:in `each'
	(erb):17:in `each_with_index'
	(erb):17:in `_erb'
	/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `eval'
	/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `result'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/action.rb:83:in `_erb'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/action.rb:54:in `erb'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/action.rb:63:in `render'
	/gems/sidekiq-ent-1.5.3/lib/sidekiq-ent/web.rb:24:in `block in registered'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/application.rb:266:in `instance_exec'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/application.rb:266:in `block in call'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/application.rb:262:in `catch'
	/gems/sidekiq-5.0.0/lib/sidekiq/web/application.rb:262:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
	/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
	/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
	/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
	/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
	/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
	/gems/sidekiq-5.0.0/lib/sidekiq/web.rb:103:in `call'
	/gems/sidekiq-5.0.0/lib/sidekiq/web.rb:108:in `call'
	/gems/rack-2.0.1/lib/rack/tempfile_reaper.rb:15:in `call'
	/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
	/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
	/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
	/gems/rack-2.0.1/lib/rack/common_logger.rb:33:in `call'
	/gems/rack-2.0.1/lib/rack/chunked.rb:54:in `call'
	/gems/rack-2.0.1/lib/rack/content_length.rb:15:in `call'
	/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
	/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	/rubies/ruby-2.4.0/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
`

Rack file:

`
require 'sidekiq-ent'
require 'sidekiq-ent/web'

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['SIDEKIQ_REDIS_URL'] }
end

run Sidekiq::Web
`

**Comment by mperham** [comment]
Fixed in 1.5.4 (which likely won't be out for a while).  Add `require 'sidekiq-ent/periodic/cron'` to your initializer to fix.

**Comment by mperham** [comment]
1.5.4 is out with this fix since I've had multiple complaints.  :-)
