### ISSUE TITLE
NameError: uninitialized constant DepositCollectorWorker

### ISSUE THREAD

**Issue by Deekor** [mperham/sidekiq#3459]
Rails 5.0.2
Sidekiq 4.2.10

I ran `rails g sidekiq:worker deposit_collector` and then filled out the code I needed inside the `perform` method.

To test I logged into the rails console and typed: `DepositCollector.perform_async` and I get the error: 

    NameError: uninitialized constant DepositCollectorWorker

The worker is where it should be in the `app/workers/` folder. I've used sidekiq on several projects before and have never run into this.

**Comment by seuros** [comment]
You probably have to restart Spring to load the new app/workers folder. 
This is not a sidekiq error.

**Comment by BM5k** [comment]
what to do if restarting sidekiq and/or spring doesn't help?
