### ISSUE TITLE
Sidekiq::Workers not reflecting current workers

### ISSUE THREAD

**Issue by jasonbuehler** [mperham/sidekiq#3461]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.7

Hi Mike, first thanks so much for such an awesome async worker lib, it's great! We have a few Shopify apps that we use Sidekiq to process API updates with among other things. Shopify has a leaky bucket throttling mechanism that throttles API calls on shop id, so coupled with a pause we put in to stop an error from being raised what inevitably happens is all of our workers get backed up with jobs for one shop waiting for the throttling to free them up when they could be processing work for other shops. Our goal is to create a serial mechanism so that shops are processed without concurrency to mitigate this.

I am 95% of the way to my solution, however I am running into an issue when I try to safeguard against stranding the mutex I am using to stop concurrency. It seems that Sidekiq::Workers is not returning an accurate list of currently working processes. In the documentation on Sidekiq::Workers.new.size it's noted that the value returned is only updated with the heartbeat (every 5 seconds). Is Sidekiq::Workers.new.each the same way? The docs seem to suggest otherwise:

```
  ##
  # A worker is a thread that is currently processing a job.
  # Programmatic access to the current active worker set.
  #
  # WARNING WARNING WARNING
  #
  # This is live data that can change every millisecond.
  # If you call #size => 5 and then expect #each to be
  # called 5 times, you're going to have a bad time.
  #
  #    workers = Sidekiq::Workers.new
  #    workers.size => 2
  #    workers.each do |process_id, thread_id, work|
  #      # process_id is a unique identifier per Sidekiq process
  #      # thread_id is a unique identifier per thread
  #      # work is a Hash which looks like:
  #      # { 'queue' => name, 'run_at' => timestamp, 'payload' => msg }
  #      # run_at is an epoch Integer.
  #    end
  #
```

I have a test job that looks like this:
```
class TestJob
  include Sidekiq::Worker

  sidekiq_options({ queue: :default })

  def perform shop_id
    puts "Started job for #{shop_id}, about to sleep for 10"
    sleep 10
    puts "Completed job for #{shop_id} slept for 10"
  end
end
```

and this server side middleware:
```
class TestWorkersCount
  def call worker, msg, queue
    count = 0
    Sidekiq::Workers.new.each do |worker|
      count += 1
    end
    puts "Workers count: #{count}"
    yield
  end
end
```

When I run this from the console: 
```
2.3.0 :013 > 5.times do TestJob.perform_async(1) ; sleep 1 end
```

I get something like this:
```
Workers count: 0
Started job for 1, about to sleep for 10
Workers count: 0
Started job for 1, about to sleep for 10
Workers count: 2
Started job for 1, about to sleep for 10
Workers count: 2
Started job for 1, about to sleep for 10
Workers count: 2
Started job for 1, about to sleep for 10
Completed job for 1 slept for 10
Completed job for 1 slept for 10
Completed job for 1 slept for 10
Completed job for 1 slept for 10
Completed job for 1 slept for 10
```

Is the list of workers updated at the same interval as Sidekiq::Workers.new.size? Any insight you can provide would be very helpful. Thanks

**Comment by mperham** [comment]
You won't be able to implement something useable with the Sidekiq::Workers API.  As you note, the data is only updated every 5 seconds.  I've already implemented Rate Limiting, documented here: https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting

**Comment by jasonbuehler** [comment]
Thanks Mike, we will have a look.
