### ISSUE TITLE
Failed worker backtrace not stored when retry set to false

### ISSUE THREAD

**Issue by ahoernecke** [mperham/sidekiq#3467]
Sidekiq: 4.2.10/5.0.0
Sidekiq-ent: 1.5.4
Sidekiq-pro: 3.5.0

We would like to be able to get a backtrace for failed tasks, even though we don't want them to be retried. The [documentation](https://github.com/mperham/sidekiq/wiki/Advanced-Options) suggests this configuration:
```
sidekiq_options :queue => :crawler, :retry => false, :backtrace => true
```

...which would presumably do what we'd like to see; however this doesn't seem to be the case. With this configuration tasks are not retried (as expected) but I can't find anywhere the backtrace is exposed (except the log). Additionally I poked around redis and couldn't find the data stored there either.

**Comment by mperham** [comment]
You need to use `retry: 0` so the job is immediately moved to the Dead set.  `retry: false` leads to the job being discarded immediately so the backtrace would also disappear immediately.
