### ISSUE TITLE
Sidekiq Pro's API: Delete enqueued jobs based on "Job Name"

### ISSUE THREAD

**Issue by ACPK** [mperham/sidekiq#3468]
Using Sidekiq Pro, how would I delete enqueued jobs based on the job name?

**Comment by mperham** [comment]
Check out this https://github.com/mperham/sidekiq/wiki/Pro-API

**Comment by ACPK** [comment]
@mperham - I did, but didn't see a way to search by job name.

**Comment by mperham** [comment]
Delete_by_class

**Comment by ACPK** [comment]
@mperham - Is there a way to search both successful and unsuccessful jobs based on class? I'd like the new job to know when the last job ran in addition to the former status.

**Comment by mperham** [comment]
Nope, there's no easy way to do that.  Any Sidekiq API you use to implement that would be pretty inefficient.  I'd suggest storing that data yourself somehow.

**Comment by ACPK** [comment]
@mperham - The data must be stores as it's available in the Web UI.

**Comment by mperham** [comment]
It's not in a form you can get to quickly per jid.

**Comment by ACPK** [comment]
I don't want it per jid; Looking for the EXACT same thing the Web UI has.

**Comment by mperham** [comment]
"The last job" implies you are looking for a specific job. The API can find jobs like that but not efficiently. It is designed for paging through the sets in groups of the next N jobs, as you do in the UI.

**Comment by ACPK** [comment]
@mperham - I didn't know that the UI was random :( :( Thought the jobs where descending based on when they ran.

**Comment by mperham** [comment]
They are ordered by time.

**Comment by ACPK** [comment]
Exactly what I'm looking for.

**Comment by mperham** [comment]
I don't think I understand what you are trying to accomplish and so this conversation isn't very productive.  Why don't you open a new issue with what you are trying to accomplish.  I would be happy to advise whether or not various Sidekiq features can help.
