### ISSUE TITLE
Solution for Duplicate JIDs processed by different Threads

### ISSUE THREAD

**Issue by d11wtq** [mperham/sidekiq#3470]
Ruby version: 2.4.1 and 2.2.2
Sidekiq / Pro / Enterprise version(s): 4.2.10

In relation to #3303, we have written the following middleware to compare JIDs with Thread IDs using Redis and avoid processing the job if there is a mismatch. Does this look like it could cause bigger issues for us, or does what we're doing here seem sensible? The duplicates we saw in our logs (hundreds of thousands of them over a few days) were all across different TIDs (in fact, possibly coincidentally, different PIDs).

The actual issue was in relation to sending push notifications, so the issue was considered quite serious for us. Many customers got 3 duplicate notifications due to duplication of Sidekiq JIDs via a series of Sidekiq jobs that enqueue other Sidekiq jobs.

FWIW, the code application had worked beautifully for 3 months until 3 days ago when this issue started and continued until today.

The duplication of JIDs doesn't appear to have been linked to timeouts in our case. Something else was going on, possibly with our Redis sentinels.

``` ruby
module Core
  # Protect against processing the same JID twice in Sidekiq.
  #
  # We observed a serious defect in production, in which Sidekiq jobs were
  # being enqueued once in the code, but processed twice in the worker. We were
  # able to definitively see the same JIDs repeated across different TIDs
  # within the log files. Not once or twice, but 75% of the time. JIDs should
  # be unique, however it appears that in the case of Redis issues, the Redis
  # client will retry operations, leading to these potential duplicate jobs.
  #
  # This middleware compares the ID of the current thread with the ID stored in
  # a Redis-based lock (using SETNX) and refuses to process the job if the IDs
  # do not match.
  class SidekiqDuplicateJobMiddleware
    def initialize(ttl:)
      @ttl = ttl
    end

    # This is a Sidekiq Middleware method.
    #
    # Invokes job only if its JID is not yet processed by another worker.
    #
    # @param [Sidekiq::Worker] worker
    #   the sidekiq worker that will process the job
    # @param [Hash] job
    #   the job payload
    # @param [String] queue
    #   the name of the queue the job is processed on
    def call(worker, job, queue)
      yield unless processed?(job['jid'])
    end

    private

    def tid
      # https://github.com/mperham/sidekiq/blob/d8f11c26518dbe967880f76fd23bb99e9d2411d5/lib/sidekiq/logging.rb#L14
      Thread.current.object_id.to_s(36)
    end

    def acquired_job_key(jid)
      format('acquired_job:%s', jid)
    end

    def acquired_by_tid(jid)
      Sidekiq.redis do |redis|
        redis.setnx(acquired_job_key(jid), tid)
        redis.expire(acquired_job_key(jid), @ttl)
        redis.get(acquired_job_key(jid))
      end
    end

    def processed?(jid)
      acquired_by_tid(jid) != tid
    end
  end
end
```

**Comment by mperham** [comment]
I suspect #3303.

```ruby
config.redis = { reconnect_attempts: 0 }
```

**Comment by d11wtq** [comment]
We were worried about using that as it sounded like it caused other problems, hence why you ultimately reverted that patch. Can you clarify if using this option is likely to cause secondary issues such as dropped connections in production?

**Comment by mperham** [comment]
I can't clarify.  Only you can determine how your production environment will behave.

**Comment by d11wtq** [comment]
We also suspect that the cause of this issue was that some clients were reading from the slave instead of the master due to misbehaving sentinels, leading to duplication as the master and slave race each other. We don't have conclusive data on that, but the hypothesis holds up since jobs those clients enqueued were not duplicated (as they were only written to the slave, and therefore not replicated).

**Comment by d11wtq** [comment]
Thanks @mperham, much appreciated :)

**Comment by mperham** [comment]
You're welcome.  I have no idea what your business is or its tolerance to failure but if your "safe" sentinel option is less reliable than Redis by itself, perhaps a rethink is in order.  I would personally either run Redis standalone myself or pay for Redis Cluster as a SaaS (Elasticache, Redis Labs, etc).

**Comment by d11wtq** [comment]
I agree, @mperham. I think we need to have a close look at our sentinel usage and reliability. We write software for a bank, and in general we don't control the supporting infrastructure (but we do have some influence).
