### ISSUE TITLE
Sidekiq.perform_async() loses encoding!

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3473]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.10

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

I've discovered a really odd bug with Sidekiq and UTF8 encoding.

If we're in the right namespace we enqueue like this

```
::Chirpify::Workers::Analytics::SocialAccountKeeperWorker.perform_async(social_accounts_payload)
```

Otherwise we do this

```
            Sidekiq::Client.new.push(
              'queue' => 'workers',
              'class' => 'Chirpify::Workers::Analytics::SocialAccountKeeperWorker',
              'args' => [social_accounts_payload])         
```

If we use perform_async, any UTF 8 characters are lost and replaced with ??

Using the `.new.push` method no encoding is lost.

Thanks for your help!

**Comment by mperham** [comment]
UTF8 characters in what?

**Comment by bobber205** [comment]
UTF8 characters in the arguments.

**Comment by mperham** [comment]
I can't explain that.  Sidekiq doesn't touch the arguments.  It stringify's the hash keys but I don't see why that would touch the values.

**Comment by bobber205** [comment]
does the stringify function have a certain encoding implied?

**Comment by mperham** [comment]
I don’t know.  Debug it or give me a reproducible script and I’ll look into
it.

**Comment by mperham** [comment]
Let me know if you ever get a script to reproduce.  Closing for now.

**Comment by awaage** [comment]
@bobber205 did you ever figure this out? I seem to be encountering a similar problem, so wanted to check in before I dig more. thanks

**Comment by bobber205** [comment]
I converted what I needed to to the .new.push syntax.

**Comment by awaage** [comment]
Got it - thanks
