### ISSUE TITLE
Send email with Sidekiq but want to deliver it once not multiple times.

### ISSUE THREAD

**Issue by axiom88-guru** [mperham/sidekiq#3477]
Thanks for the great library. 
I am going to send email to my customers at a certain time. I've been building a Event app which sends email notification to users at a certain time (this is configured by users). 

So I made a job and run this function .
            NotificationMailerJob.set(wait_until: Time.now + 10.seconds).perform_later(event)
This will call below function. 
  def perform(event)
    p 'Performing job..'
    NotificationMailer.send_notification(event).deliver
  end

When I go to console and check the log...this is the what i can see
"Performing job.."
after 10 seconds
"Performing job.."
after 10 seconds
"Performing job.."
.....
It finally stopped after repeating 6~7 times within 1 minute. 
What's happening here? 
Is there anything that I am missing? 

Any help would be much appreciated. 
Thanks in advance

**Comment by mperham** [comment]
I don't know what's going on there but you haven't shown us the code, the initializer, your versions, etc so we can't debug.
