### ISSUE TITLE
Postgres connection leak

### ISSUE THREAD

**Issue by junaid-malik-confiz** [mperham/sidekiq#3478]
Hello Guys,

We are facing error regarding the postgres connection locking in off hours. Can you tell us the hook to clear Postgres connections?

Ruby version: 2.1.2
Sidekiq / Pro / Enterprise version(s): Sidekiq

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?
Here is initializer code https://gist.github.com/junaid-malik-confiz/c1593e38dedd0147b636fdd5810f4673

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
Looks like you are using Sidekiq through Discourse, perhaps you should ask them for help.  I don't know what's wrong.
