### ISSUE TITLE
Reliability wiki page confusing regarding super_fetch

### ISSUE THREAD

**Issue by heironimus** [mperham/sidekiq#3482]
https://github.com/mperham/sidekiq/wiki/Reliability says to user super_fetch, but then goes into a bunch of detail about everything but super_fetch. It would be nice if super_fetch was mentioned first and the others referenced as legacy only or something.

**Comment by mperham** [comment]
Yep, that page is mostly legacy.  Thanks for the reminder, I will clean it up.
