### ISSUE TITLE
Making dashboard/stats graphs more color blind friendly

### ISSUE THREAD

**Issue by ZachBeta** [mperham/sidekiq#3483]
Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s): sidekiq (4.2.10)
Rails: rails (5.0.2)

I'm having trouble figuring out the best way to make the graph more immediately color blind friendly. It's not immediately obvious where I can override the default colors to make them more clear at a glance to someone who has color blindness.

Functionally it's still usable (if the lines converge then it's all errors, and if the lines separate the failures are always below as a subset of processed), but could be a nice small fix to improve usability for other devs.

**Comment by mperham** [comment]
I don't have any ideas to fix/improve.  Are you going to submit a PR?  Are you looking for help or suggestions?
