### ISSUE TITLE
Sidekiq working in kind of parallel but not as fast as expected

### ISSUE THREAD

**Issue by Faisal-nfl** [mperham/sidekiq#3485]
This jobs get followers of user_id given to it
```
class FollowerJob < ActiveJob::Base
  queue_as :default

  def perform(user_id) 
    #code to get followers 50 by 50
  end
end
```
Didn't need to config as I 'm on deploying cloud66 which is handling this. I just made a worker to 1 from 0 in proccesses of cloud66.

From console If I call
`FollowerJob.perform_later(1)`
Than in 1 hour it gets around 18,000 followers of user. and if I call multiple background jobs like
```
FollowerJob.perform_later(1)
FollowerJob.perform_later(2)
FollowerJob.perform_later(3)
FollowerJob.perform_later(4)
FollowerJob.perform_later(5)
```
Than I was expecting (18,000 * 5 = ) 90,000 followers per hour .
But it still getting around 18,000 followers in total for all 5 users.

Is not each job is working in parallel, Which part I got wrong ?

**Comment by mperham** [comment]
There's many reasons why this might not scale linearly: rate limiting, CPU limits, etc.  It's impossible for us to tell where the bottleneck is.
