### ISSUE TITLE
Parsing error for text/plain email content

### ISSUE THREAD

**Issue by rhuppert** [mperham/sidekiq#3486]
On my development system, I'm using rails 5.03, ruby 2.4, sidekiq 5.0, and premailer-rails 1.96, with a vanilla implementation of ActiveJob and ActionMailer.

Sidekiq generates the following warning 105 times on outgoing email:
```
2017-05-26T22:04:43.784Z 27193 TID-gqne3mkwo ActionMailer::DeliveryJob JID-29e4d82779187041b6c3d80c INFO: start
WARNING: Could not parse (and so ignoring) 'Content-Type: text/plain'
WARNING: Could not parse (and so ignoring) 'Content-Type: text/plain'
WARNING: Could not parse (and so ignoring) 'Content-Type: text/plain'
... 
2017-05-26T22:04:46.331Z 27193 TID-gqne3mkwo ActionMailer::DeliveryJob JID-29e4d82779187041b6c3d80c INFO: done: 2.547 sec
```
The plain text version does get delivered

I've spent quite a bit of time trying to narrow this down , but I not sure if this is a sidekiq, premailer-rails,  premailer, mail parser, or rails issue.  

This was not an issue in rails 4.2.8.

**When sending an email with skip_premailer: true (which bypasses premailer), the warning does goes away.**

Can this warning be safely ignored?  Any thoughts would be appreciated. 
_
[sidekiq.rb.txt](https://github.com/mperham/sidekiq/files/1033138/sidekiq.rb.txt)
_

**Comment by mperham** [comment]
If it generates the same warning with `deliver_now` instead of `deliver_later` then it has nothing to do with Sidekiq.

**Comment by rhuppert** [comment]
Thanks for the quick response, Mike.

I did change one mailer to deliver_now and it generated no warnings, but maybe I'm looking in the wrong place.  Nothing in the rails console, just the sidekiq terminal.
I also added the following code so Devise would run through Sidekiq and it generated errors as it does use deliver_later.
'''
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
'''
I checked the dev log and nothing unusual stands out.  Should I look for something in particular?

**Comment by rhuppert** [comment]
I saw that the version of the mail gem was using 2.7.0.rc1 instead of 2.6.5,
After reverting, the warning went away.
Thanks for your help.

**Comment by rhuppert** [comment]
This ([https://github.com/mikel/mail/pull/1105](url)) might be related to my issue.

**Comment by mperham** [comment]
I see the rescue block in that PR is rescuing multi-byte errors.  My guess is that you are serializing something to Redis and seeing string encoding issues when you pull the data out of Redis to execute.  All Sidekiq argument data must be UTF8.  For example, maybe you have Latin1 characters for user's names in the To address.

You should ask them to expose the underlying error message in this warn because a warning is useless if you have no idea how to fix the issue.

https://github.com/mikel/mail/pull/1105/files#diff-480c9cbc16ce0b8fb4b396b9f46187f6L249

cc mikel/mail#1105

**Comment by mperham** [comment]
Looks like mail master gives more context for the warning.  Try using mail master:

```ruby
gem 'mail', github: 'mikel/mail'
```
