### ISSUE TITLE
Making tuning information available on Sidekiq Web

### ISSUE THREAD

**Issue by nateberkopec** [mperham/sidekiq#3488]
I'm tuning a Sidekiq install for a client right now, and when I was done, I was trying to think about how the Sidekiq dashboard could tell Sidekiq users when things are wrong, or at least make certain information more obvious. 

Here are the problems Sidekiq could "yell" at the user about somehow:

* Queues with vastly varying job execution times. As with any load-balancing situation, you want work to be fast and predictable. Now, in the real world, not every job class will behave like that. Perhaps you're waiting on an HTTP response, etc. Now, the problem comes when you mix slow jobs with fast ones - slow jobs can "take over" your worker threads, causing fast jobs to back up in the queue. If a sidekiq process generally processes it's jobs in 200 milliseconds, and then performs a job in 20 seconds, it should say something. 
* DB pool not set to the same size as concurrency. Rails specific, but I see it all the time, especially in older apps before RAILS_MAX_THREADS was introduced as a convention.
* Sidekiq::Limiter's wait_timeout of 5 is inappropriate for jobs which are minute/hour bucket/window limited. Sidekiq could yell at the user when there are many jobs sitting in threads which are just waiting for the wait_timeout.
* Similarly, minute/hour bucket/window limiters could benefit from custom backoffs. Instead of trying every 5 minutes, a minute limited job should try every minute.
* Could Sidekiq report what percentage of it's total memory usage is taken up by Limiters? What about by job type? (this could surface people calling delay on object instances, for example, even though tests yell about that already)

So, possible solutions:

* More information about Sidekiq processes and their threads. What I would want to know is a) on average, this process is doing work on which queues (80% high, 20% low for example) b) how long does it take for this process to complete a job on average c) are there job types performed by this process that are usually slower than that average d) how long does this process jobs stay in a Sidekiq::Limiter wait timeout.
* A warning on the top of the UI if the Rails db pool is smaller than the concurrency setting.
* A limiter report which can deal with dynamic limiter names - for example, if I have a limiter for the Github API which is keyed on the user ID, so something like "github-123123", I'd like a report for *all* "github-*" limiters.
* I have no idea how Sidekiq does this r/n, but Sidekiq's thread pool could adopt a first-unused-thread routing strategy. That is, we ID threads from 0 to concurrency, then always route to the lowest-index thread which is not busy. What this would allow is us to report when a thread was *last used*. If threads 1-5 were last used <30 seconds ago, and threads 6-10 were never used, I know I'm over-provisioned. This might also cut down on memory fragmentation (malloc will alloc fewer per-thread arenas). 
* More insight into what types of jobs, limiters, etc are contributing to Sidekiq's Redis memory usage.

EDIT: edited to make clear when I was talking about worker classes versus sidekiq processes

**Comment by mperham** [comment]
There's a lot to unpack here so forgive me if I miss a few points but a few quick things:

* Sidekiq::Limiter's wait_timeout only applies to :second limiters.  :minute/:hour will immediately raise because we don't want to block a Thread for that long.
* Sidekiq::Limiter supports a custom global backoff scheme.
* Tools for querying Redis key memory usage aren't Sidekiq-specific.  There are tools out there but the demand isn't enough to warrant building something Sidekiq-specific.  I've linked to some tools on the Using Redis wiki page.
* sidekiq-statistic is one example of a plugin which saves execution history and provides aggregate metrics per Worker class.  It has major memory leak which makes me not recommend it but it is a good place to start if you are looking for something useful.
* Sidekiq's threads === instances of Sidekiq::Processor.  They are all running concurrently under OS control and each fetches from Redis separately.  It may be possible to lazy instantiate Sidekiq::Processors but I'm unclear what kind of actual memory savings vs code complexity would result.

I like your idea about DB pool size warnings.  We already have something similar for Redis pool size, a PR would be very welcome.

**Comment by nateberkopec** [comment]
> Sidekiq::Limiter's wait_timeout only applies to :second limiters. :minute/:hour will immediately raise because we don't want to block a Thread for that long.

Well that's good to hear. What does `but they will not sleep until the next interval` mean in the wiki then? Did you mean `will not sleep until wait_timeout has passed`?

> Sidekiq::Limiter supports a custom global backoff scheme.

Yeah, I implemented this for the client but retrying a minute-limited job every 5 minutes just doesn't make sense as a default IMO.

> Tools for querying Redis key memory usage aren't Sidekiq-specific. There are tools out there but the demand isn't enough to warrant building something Sidekiq-specific. I've linked to some tools on the Using Redis wiki page.

point taken

> sidekiq-statistic is one example of a plugin which saves execution history and provides aggregate metrics per Worker class

Yeah I'm not interested in per-worker though, I pretty much already get that from NewRelic. What I want is per-Sidekiq::Processor. How often are they idle, what do they spend their time doing, etc.

**Comment by nateberkopec** [comment]
Yeah, the easy way to do this (and I think would be 80% as useful) is not to try to collect metrics over time, but more like a sampling profiler - what are my threads doing *right now*, and let the user collect 3-4 of those to get a rough guess.

**Comment by mperham** [comment]
A `rack-mini-profiler` for Sidekiq via server middleware would be amazing.  I'm going to close this since it doesn't have any specific TODOs and don't want it to linger open.
