### ISSUE TITLE
Unable to use Devise methods/Rails helper methods in Sidekiq Views

### ISSUE THREAD

**Issue by pbharadiya** [mperham/sidekiq#3491]
Hello,

I'm stuck at one point. How can I use devise current_user method in Sidekiq view e.g queue.erb?
Or any helper method that I add in ApplicationHelper?

The requirement is I do not want to authenticate for /sidekiq but for particular action or link.

I'm using Sidekiq 4.2.4 with ruby 2.0.0 and rails 3.2.

Please help me or suggest page where I can look into. Thanks in advance.

P.S I'm customising sidekiq UI and added views at app/views/sidekiq

-Parth

**Comment by pbharadiya** [comment]
I'm not sure whether it is right solution but I have found word around in case somebody is facing the same issue.

I have added below line to access ApplicationHelper method in Sidekiq views.
<pre><code>#app/config/initializers/sidekiq.rb
Sidekiq::WebAction.send(:include, ApplicationHelper)</code></pre>

**Comment by mperham** [comment]
Sidekiq::Web is a standard Rack app.  If you want to control authentication, you insert a Rack middleware before it and do what you need.
