### ISSUE TITLE
Controlling Redis Memory Usage

### ISSUE THREAD

**Issue by jolim** [mperham/sidekiq#3493]
Ruby version: 2.4
Sidekiq / Pro / Enterprise version(s): 5.0.0

Running on Heroku Redis, I set the redis eviction policy to `noeviction`, as specified in the docs (https://github.com/mperham/sidekiq/wiki/Using-Redis).

It seems that there is some data which is not deleted from Redis after a Sidekiq job completes. The data store continues to grow pretty steadily, using up more and more memory over time, leading me to have to upgrade my plan.

Am I doing something wrong?

**Comment by mperham** [comment]
You aren't doing anything wrong but you'll need to dive into the keyspace and determine which keys are lingering.

**Comment by jolim** [comment]
Thanks. Here's a sample of what I'm seeing (tail of `KEYS *`):

```
1532) stat:processed:2017-05-10
1533) stat:processed:2016-10-16
1534) stat:failed:2016-04-21
1535) stat:failed:2016-06-30
1536) stat:failed:2017-02-01
1537) stat:failed:2016-04-12
1538) stat:failed:2016-12-17
1539) stat:processed:2016-11-12
1540) stat:failed:2016-07-29
1541) stat:processed:2016-07-15
```
and, FWIW:
```
irb(main):029:0> Sidekiq::ScheduledSet.new
=> #<Sidekiq::ScheduledSet:0x00000008281c40 @name="schedule", @_size=581>
irb(main):030:0> Sidekiq::RetrySet.new
=> #<Sidekiq::RetrySet:0x00000008270328 @name="retry", @_size=0>
irb(main):031:0> Sidekiq::DeadSet.new
=> #<Sidekiq::DeadSet:0x000000082636c8 @name="dead", @_size=0>
```

Do you think these are orphaned records, or is there a Sidekiq queue that I'm not aware of that is likely managing these?

**Comment by mperham** [comment]
Those are all perfectly normal.  The stats are daily processed/failed stats so we can show the execution history on the Web UI Dashboard page.  They are stored for 5 years so you'll see 2*5*365 of them, should be less than 1MB of data.  The scheduled set holds jobs that are scheduled to run in the future: `perform_in(3.days, ...)`.  You have 581 jobs pending.

**Comment by mperham** [comment]
I assume this is the cause of your slight growth.  Please reopen if you find other keys are lingering.
