### ISSUE TITLE
Can't background email with MyCustomWorker

### ISSUE THREAD

**Issue by marcosanfilippo** [mperham/sidekiq#3494]
Hi, 

I'm going to send `DEVISE` email with a custom worker class.

I need to so do something like this...

```
def confirmation_instructions(record, token, opts={})
    devise_mail(record, :confirmation_instructions, opts)
end
```

to background...

```
def confirmation_instructions(record, token, opts={})
    MyCustomWorker.perform_in 1.minutes, devise_mail(record, :confirmation_instructions, opts)
end
```

But it doesn't work.

**Comment by seuros** [comment]
You can't pass a mail object to a sidekiq job since it can serialize.

Maybe you should do something like 

```ruby
def confirmation_instructions(record, token, opts={})
    MyCustomWorker.perform_in(1.minutes, record.id, token, opts)
end

**Comment by marcosanfilippo** [comment]
But there's a way to give Sidekiq a function/block/lambda that will be executed in background? Or is not possible for the same reason?

**Comment by mperham** [comment]
You can't serialize a lambda. JSON data types only.
