### ISSUE TITLE
Question: giving a worker access to some http headers

### ISSUE THREAD

**Issue by mkaito** [mperham/sidekiq#3500]
Hi!

I want to link back to my application in an email it sends. It's your typical email verification/account activation thing. We have a testing server, a staging server, and soon a production server. Each with a different URL. I'd like the email to link back to the environment that sent it. This is most easily done by grabbing the URL from the HTTP environment. That is, I use `request.base_url` in Sinatra.

Why am I sending email in a worker? Because I use Mailgun, and I don't want API lag or failures to hold up the main thread.

How would I go about telling the worker about this? Should I just pass it as an argument to the perform() method, or is there some way to take care of it automatically?

**Comment by mperham** [comment]
You can pass it in as an argument or you can calculate it with a case statement in your worker:

```ruby
case Rails.env
when "production": "https://www.example.com";
when "staging": "https://beta.example.com";
end
```
