### ISSUE TITLE
Customize sidekiq job logger

### ISSUE THREAD

**Issue by AlfonsoUceda** [mperham/sidekiq#3501]
Ruby version: 2.3.3
Sidekiq: 5.0.2

Hi:

I updated sidekiq from 4.2.8 to 5.0.2 and I were using a custom middleware for logging, so we removed the default one and we added the new one.
With the upgrade, I noticed these middlewares have gone and they were merged in the Sidekiq::Processor class.

I'm using the same middleware in my app but I noticed that [job_logger](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_logger.rb) is adding info lines to the log and it's causing to add garbage to our ELK server.

Is there a way to replace job_logger with your custom job logger? without monkey patching the job logger class or amending those lines to make them `debug` instead `info`.

Thanks for your time.

**Comment by mperham** [comment]
There's no way today but you can always submit a PR.

**Comment by AlfonsoUceda** [comment]
@mperham thanks, I'll do that ;)

**Comment by s-mansouri** [comment]
I try to use custom job_logger_class but I don't know how to use it, can you explain more about it?

**Comment by rafbm** [comment]
@s-mansouri A bit late, but I just added [instructions to the wiki](https://github.com/mperham/sidekiq/wiki/Logging#overwrite-default-logger) on how to overwrite `:job_logger`. Happy New Year! ✌️

**Comment by s-mansouri** [comment]
@rafbm Thanks. Happy New Year to you, too. :+1:
