### ISSUE TITLE
Remove/Silence sidekiq job logger

### ISSUE THREAD

**Issue by stevenjackson** [mperham/sidekiq#3503]
Ruby version: 2.2.5
Sidekiq / Pro / Enterprise version(s): Sidekiq

Regarding https://github.com/mperham/sidekiq/issues/3501, is there any way to remove the logger?    My concern with the custom class is that we have to `yield` and `rescue` to maintain compatibility and this feels somewhat fragile considering how deep this is inside sidekiq.  Maybe an option to reduce the logging level?

**Comment by mperham** [comment]
Just set the logger level to WARN in your initializer.
