### ISSUE TITLE
Can't set options on Sidekiq::Extensions::DelayedMailer on 5.0.2

### ISSUE THREAD

**Issue by lucascartaxo** [mperham/sidekiq#3504]
Ruby version: `2.4.1p111`
Sidekiq / Pro / Enterprise version(s):
sidekiq  `5.0.2`
sidekiq-ent `1.5.4`
sidekiq-pro `3.5.0`

_______________________

Hello

First of all, I would like to thank and congratulate @mperham for the awesome job on this awesome gem.

Since the release of Sidekiq 5, delay extensions are [disabled by default](https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md#whats-new) and more specifically since [PR #3174](https://github.com/mperham/sidekiq/pull/3299), the `action_mailer` extensions are being lazy loaded.

However, this behavior crashed some configurations on my environment.

Due to business rules of my app, all of my workers need to run in a specific queue, in a specific database. Thus, I had the following config on my `sidekiq.rb` initializer:

```ruby
Sidekiq::Extensions::DelayedMailer.sidekiq_options queue: :read_only_default, db: :read_only
```

By upgrading my sidekiq from `4.2.10` to `5.0.2`, I started to have the following error

```
uninitialized constant Sidekiq::Extensions::DelayedMailer (NameError)
```

In order to maintain my business rule behavior, I had to manually require the DelayedMailer class
```ruby
# require DelayedMailer class in order to bypass lazy load
# https://github.com/mperham/sidekiq/pull/3299
require 'sidekiq/extensions/action_mailer'
Sidekiq::Extensions::DelayedMailer.sidekiq_options queue: :read_only_default, db: :read_only
```
Is this an expected behavior? How can I set this `sidekiq_option` if the `DelayedMailer` extension class is not available in the sidekiq initializer?

Thanks in advance!

**Comment by mperham** [comment]
That behavior was never documented; implementation can change and break between major releases.  The supported way to do this is to pass the options into `delay`:

```ruby
MyMailer.delay(queue: :read_only_default, db: :read_only).some_method
```

**Comment by pinnymz** [comment]
@lucascartaxo I've found that (at least for Sidekiq >= 5.0) if you call `Sidekiq::Extensions.enable_delay!` prior to invoking the DelayedMailer, it works fine.  Per the documentation, the DelayedMailer extension is no longer declared by default.
