### ISSUE TITLE
Multiple batch.jobs calls causes jobs to be dimissed

### ISSUE THREAD

**Issue by lucascartaxo** [mperham/sidekiq#3505]
Ruby version: `2.4.1p111`
Sidekiq / Pro / Enterprise version(s):
sidekiq `4.2.10`
sidekiq-ent `1.5.2`
sidekiq-pro `3.4.1`

_____________________

Hello

Allocating batch jobs may be quite confusing when we can reopen a batch:
With only one block of jobs, everything works fine:
```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  FirstJob.perform_async
  SecondJob.perform_async
end
```
But, if we use multiple blocks to add jobs in the batch:
```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  FirstJob.perform_async
  SecondJob.perform_async
end
# Schedule the following job after the end of batch has ended:
batch.jobs do
  Third.perform_async
end
```
---
The third job will never run.
This behavior can lead to many problems, specially when you're dealing with high concurrency models.
After a lot of digging, I realized that when the block is closed we can't add more jobs to the batch. In my opinion it would be useful to allow only one call to batch.jobs per batch.

**Comment by mperham** [comment]
I've known this to be a possible API problem before but I've never been able to figure out a way to catch this usage pattern as there are a number of edge cases.  The wiki page states that you cannot add more jobs to an existing batch unless you are within a job within that batch.
