### ISSUE TITLE
undefined method stringify_keys when registering a cron

### ISSUE THREAD

**Issue by spinx** [mperham/sidekiq#3506]
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s):
5.0.2 / 3.5.0 / 1.5.4

Initializer:
https://gist.github.com/spinx/00e270a8aba368293c7399b51d34d6ee

This defect comes from upgrading Sidekiq to 5.0.2 and is also present in 5.0.1

**Comment by mperham** [comment]
Please give the full backtrace

**Comment by spinx** [comment]
``
2017-06-08T11:03:51.852Z 3242 TID-aru80 INFO: Booting Sidekiq 5.0.2 with redis options {:url=>"redis://127.0.0.1:6379/0", :namespace=>"devbox"}
undefined method `stringify_keys' for {:args=>[1], :queue=>"sync_high"}:Hash
access-layer-app/gems/sidekiq-ent-1.5.4/lib/sidekiq-ent/periodic/config.rb:30:in `register'
access-layer-app/sidekiq.rb:61:in `block (3 levels) in <top (required)>'
access-layer-app/sidekiq.rb:60:in `each'
access-layer-app/sidekiq.rb:60:in `block (2 levels) in <top (required)>'
access-layer-app/gems/sidekiq-ent-1.5.4/lib/sidekiq-ent/periodic.rb:18:in `periodic'
access-layer-app/sidekiq.rb:55:in `block in <top (required)>'
access-layer-app/gems/sidekiq-5.0.2/lib/sidekiq.rb:73:in `configure_server'
access-layer-app/sidekiq.rb:41:in `<top (required)>'
access-layer-app/gems/sidekiq-5.0.2/lib/sidekiq/cli.rb:264:in `require'
access-layer-app/gems/sidekiq-5.0.2/lib/sidekiq/cli.rb:264:in `boot_system'
access-layer-app/gems/sidekiq-5.0.2/lib/sidekiq/cli.rb:54:in `run'
access-layer-app/gems/sidekiq-5.0.2/bin/sidekiq:12:in `<top (required)>'
access-layer-app/bin/sidekiq:22:in `load'
access-layer-app/bin/sidekiq:22:in `<top (required)>'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
access-layer-app/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
access-layer-app/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
access-layer-app/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
access-layer-app/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
access-layer-app/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
access-layer-app/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
access-layer-app/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
access-layer-app/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
access-layer-app/bin/bundle:22:in `load'
access-layer-app/bin/bundle:22:in `<main>'
``

**Comment by mperham** [comment]
Ah right, I need to release sidekiq-ent too.

**Comment by mperham** [comment]
1.6.0 is out.
