### ISSUE TITLE
High Redis Memory Usage

### ISSUE THREAD

**Issue by nazarhussain** [mperham/sidekiq#3507]
Ruby version: 2.3.4
Sidekiq version(s): 5.0

Here is the status of jobs in sidekiq; 
<img width="1188" alt="screenshot at jun 08 12-18-28" src="https://user-images.githubusercontent.com/112468/26924179-f772c092-4c44-11e7-9473-7786fdab28fc.png">

And here is the memory usage; 
<img width="678" alt="screenshot at jun 08 12-18-44" src="https://user-images.githubusercontent.com/112468/26924188-fd98bab2-4c44-11e7-9e71-a7f593f22487.png">

Literally no job in queue and its taking over `3.6GB` of Redis memory. 

This is the package combination I am using; 

```
gem 'sidekiq', '~> 5.0'
gem 'sidekiq-unique-jobs', '~> 5.0', '>= 5.0.8'
gem 'sidekiq-scheduler', '~> 2.1', '>= 2.1.5'
gem 'redis-namespace', '~> 1.5', '>= 1.5.3'
```
May be it would be a sidekiq issue, but how to debug further this situation? My server can't hold much longer with that much redis memory consumption.

**Comment by mperham** [comment]
There's no way for us to know what's taking so much memory.  I would first run the scripts for 4.1.2 and 4.1.3 against your Redis and see if that frees up anything.  If not, sample the keyspace with:

```
redis-cli "SCAN 0 COUNT 50"
```

and see what keys are lingering.
