### ISSUE TITLE
Is there any reason why the Ruby version enforcement is not done through the gemspec?

### ISSUE THREAD

**Issue by rafaelfranca** [mperham/sidekiq#3510]
The Rails 4.2 test suite started to fail with Ruby 2.0 and Ruby 2.1 because it upgraded to sidekiq 5.0 and it don't support Ruby < 2.2 anymore. Could this version enforcement be put in the gemspec so bundle don't even try to install that sidekiq 5.0 in those versions?

**Comment by mperham** [comment]
I don't know how well that works with Jruby?

**Comment by rafaelfranca** [comment]
Oh, that is a good question. I think, it would just work since jruby version is greater than 2.2.2. Rails can be installed in jruby and we have it configured in the gemspec.
