### ISSUE TITLE
Are batches documentation up to date?

### ISSUE THREAD

**Issue by fgrehm** [mperham/sidekiq#3511]
Hey @mperham!

I've recently been doing a lot of work using batches following recommendations on the [Really Complex Workflows with Batches](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches) but the other day I came across the last sentence on [this page](https://github.com/mperham/sidekiq/wiki/Batches) which says:

> A Batch with zero jobs is invalid, its behavior is undefined. If you define a child Batch with jobs, the parent Batch must also have at least one job in order to get well-defined behavior.

But on the Really Complex Workflow with Batches page we have the following code:

```ruby
overall = Sidekiq::Batch.new
overall.on(:success, 'FulfillmentCallbacks#shipped', 'oid' => order.id)
overall.description = "Fulfillment for Order #{order.id}"
overall.jobs do
  step1 = Sidekiq::Batch.new
  step1.on(:success, 'FulfillmentCallbacks#step1_done', 'oid' => order.id)
  step1.jobs do
    A.perform_async(order.id)
  end
end
```

Isn't an `overall` batch an invalid batch according to the quoted text above? 🤔 Things have been working just fine for us using that approach but I wonder if it is working "by accident" or the fact that `step1` has at least one job makes `overall` valid.

I've also noticed that the overall batch never shows up on the UI using sidekiq 4.1.2 / 5.0.2 & sidekiq-pro 3.3.1 / 3.5.0.

Tks in advance!

**Comment by mperham** [comment]
That's a good point, I think it is invalid as is.

**Comment by fgrehm** [comment]
So what is the right approach for this? Maybe something like:

```ruby
overall = Sidekiq::Batch.new
overall.on(:success, 'FulfillmentCallbacks#shipped', 'oid' => order.id)
overall.description = "Fulfillment for Order #{order.id}"
overall.jobs do
  StartWorkflow.perform_async(order.id)
end

class StartWorkflow
  def perform
    batch.jobs do
      step1 = Sidekiq::Batch.new
      step1.on(:success, 'FulfillmentCallbacks#step1_done', 'oid' => order.id)
      step1.jobs do
        A.perform_async(order.id)
      end
    end
  end
end
```

**Comment by mperham** [comment]
Yep, that's a great approach.  I will update wiki.

**Comment by fgrehm** [comment]
Thanks!

**Comment by codeanpeace** [comment]
On a related note, is it okay if a child batch with no children batches of its own has no jobs?

**Comment by codeanpeace** [comment]
Hmm, just to clarify by "That batch" are you referring to the child batch and/or parent batch?

Example below is where a parent batch at least one job that has a child_batch with no jobs. Would the parent job never complete/succeed because its child batch has no jobs? And therefore the parent callback would never fire? And the batches would be stuck in pending limbo on the UI because they hard crashed?

Thanks!

```
overall = Sidekiq::Batch.new
overall.on(:success, 'WorkflowCallbacks#report_results')
overall.description = "Workflow"
overall.jobs do
  StartWorkflow.perform_async(organization.id)
end

class StartWorkflow
  def perform
    child_batch = Sidekiq::Batch.new
    child_batch.jobs do
      # If the following query returns no records meaning no jobs added to `child_batch`
      ExternalEvent.where(created_at: some_time_range).find_each do |event|
        EventWorker.perform_async(event.id)
      end
    end
  end
end
```

**Comment by codeanpeace** [comment]
Thanks a bunch! Would it be worth adding something to the effect of:

> And vice versa, child Batch must also have at least one job in order to get well-defined behavior at the parent level.

**Comment by mperham** [comment]
Clarified: https://github.com/mperham/sidekiq/wiki/Batches#notes
