### ISSUE TITLE
Sidekiq::Testing.inline! doesn't always execute block

### ISSUE THREAD

**Issue by devonestes** [mperham/sidekiq#3513]
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s): Sidekiq versions 4.2.10 & 5.0.2

Sorry in advance for a rather long description, but I haven't been able to generate a reproducible script to demonstrate this bug, and I don't think I'm allowed to share our code publicly...

So, we have a feature test that looks like the following

```ruby
it 'updates all of the associated data' do
  Sidekiq::Testing.inline! do
    visit line_item_path(line_item)
    click_on 'Update'
    fill_in 'line_item[lines]', with: 2
    fill_in 'line_item[bandwidth]', with: 10
    fill_in 'line_item[cost]', with: 50_000
    fill_in 'line_item[note]', with: 'Updating line item!'
    click_on 'Update'
  end

  # assertions here
end
```

When I run that file on its own in RSpec (by running `bundle exec rspec spec/features/feature_spec.rb`), everything behaves correctly. Similarly, when I run all feature specs (by running `bundle exec rspec spec/features`), everything behaves correctly. However, when I run the entire suite (by running `bundle exec rspec`), the block isn't executed. I've confirmed this by putting a call to `byebug` inside the block to be executed, and when run in the context of the entire test suite, that block is never hit. When running just the file individually or all feature specs together, that debugger entry point is hit without problem.

Also, to make things even more weird, we have other tests in that same spec that use `Sidekiq::Testing.inline!` with a block, and those blocks are all executed without issue when we run the whole suite. It's just this one unlucky block.

This only became an issue when we upgraded to Rails 5.1. When we started that upgrade we were still on 4.2.10, but this behavior still appears on 5.0.2. If it helps, we're also using RSpec 3.6.0.

I'd be happy to provide any further information that you might need. Also, I'm not sure if your happy hour is really the right time for such things, but I think I could chat with you about this bug further during that time if it would be helpful to you.

**Comment by mperham** [comment]
No clue.  inline! always calls its block so that behavior shouldn't be possible.

**Comment by devonestes** [comment]
We ended up just refactoring our tests since we couldn't find why that was happening... Probably for the best, anyway 😉

**Comment by fylooi** [comment]
Had this same issue, discovered that one of my specs calls `ActiveJob::Base.queue_adapter = :test`.  Calling `Sidekiq::Testing.inline!` will have no effect if this spec runs before it. 

One solution is to change the adapter back after the spec in question, eg:

```
    around do |example|
      current_adapter = ActiveJob::Base.queue_adapter
      ActiveJob::Base.queue_adapter = :test

      example.run

      ActiveJob::Base.queue_adapter = current_adapter
    end
```

**Comment by daqing** [comment]
I hit this problem today, and I found that it was caused by  the `sidekiq-unique-jobs` gem. I removed that gem from Gemfile and the job was run inline successfully.

**Comment by ramhoj** [comment]
We've been having the same issue. I **think** (hasn't failed for a while since) I was able to solve it by adding:

```
# From https://makandracards.com/makandra/28125-perform-sidekiq-jobs-immediately-in-development
# Perform jobs immediately
config.active_job.queue_adapter = :sidekiq
require "sidekiq/testing"
Sidekiq::Testing.inline! # NOTE: see https://github.com/mperham/sidekiq/wiki/Testing
```

to `config/environments/test.rb` and never change it. Previously we used `fake!` as the implicit default and run certain tests in `Sidekiq::Testing.inline! {} ` just as @devonestes.

**Comment by martinstreicher** [comment]
I ran into this issue yesterday. In my case, even though I am using a `Sidekiq::Testing.inline!` block to run a spec, the adapter active in the block is `Test`, not Sidekiq. I have a `byebug` in the job and it's never hit. 

I made some changes to get inline to work, although it causes other issues detailed below: 
* _test.rb_ has the statement `config.active_job.queue_adapter = :sidekiq`
* I **removed** an initializer for the test envirionment that had this:
```
RSpec.configure do |config|
  config.include ActiveJob::TestHelper

  config.before do
    clear_enqueued_jobs
  end
end
```

*  I **added** this initializer for the test environment: 
```
require 'sidekiq/testing'

Sidekiq::Testing.inline!

RSpec::Sidekiq.configure do |config|
  # Clears all job queues before each example
  config.clear_all_enqueued_jobs = true # default => true

  # Whether to use terminal colours when outputting messages
  config.enable_terminal_colours = true # default => true

  # Warn when jobs are not enqueued to Redis but to a job array
  config.warn_when_jobs_not_processed_by_sidekiq = true # default => true
end
```

This does make inline succeed. However, I get other errors now: 

```
StandardError:
  To use ActiveJob matchers set `ActiveJob::Base.queue_adapter = :test`
./spec/controllers/api/brand/promotions_controller_spec.rb:203:in `block (4 levels) in <top (required)>'
```

```
NameError:
  undefined local variable or method `enqueued_jobs' for #<RSpec::ExampleGroups::SendRepInvitationJob::PerformLater:0x00005576e8061850>
  Did you mean?  enqueue_job
```

LIke some of the other observations above, it seems like something is setting the queue adapter to test. Removing this...

```
```
RSpec.configure do |config|
  config.include ActiveJob::TestHelper

  config.before do
    clear_enqueued_jobs
  end
end
```

... seems to leave the adapter as sidekiq. 

I am still looking for a combination of settings that works in all the cases.

**Comment by AlexanderFisenko** [comment]
Hey! In case it will help somebody. Spent several hours on that and finally fixed. I had a problem in rspec, when I used `Sidekiq::Testing.inline!` and started MyWorker.perform_async it just returned nil and nothing happened. The problem was not in gem Sidekiq but in the gem 'sidekiq-unique-jobs' and after I added logging
```
class ApplicationWorker
  include Sidekiq::Worker

  sidekiq_options(
    backtrace: true,
    retry: 0,
    lock: :until_executed,
    on_conflict: { client: :log, server: :reject }
  )
end
```
I found out that it wrote digests to Redis and did not remove them although it should.

`2021-08-12T09:57:32.693Z 92302 TID-ox77n3csu uniquejobs-client DIG-uniquejobs:93e1b71f15cf61b107e37c6f71c19763 INFO: Skipping job with id (ea14368dc721ce0df9a87077) because lock_digest: (uniquejobs:93e1b71f15cf61b107e37c6f71c19763) already exists`

The I also ran `redis-cli keys '*' | grep uniquejobs` just to ensure.

Just in case you did not know you can easily clear Redis from ruby console with `Sidekiq.redis { |conn| conn.keys('uniquejobs:*').each { |key| conn.del(key) }; conn.del('uniquejobs') }`

What I actually did to fix it:

- added `require 'sidekiq_unique_jobs/testing'` to spec/rails_helper.rb
- added `SidekiqUniqueJobs.configure { |config| config.enabled = !Rails.env.test? }` to sidekiq initializer

**Comment by letiesperon** [comment]
@daqing @AlexanderFisenko 
Thank you both. I came to this thread because of a similar issue and in my case it was also the sidekiq uniq jobs gem that was making the same job not execute twice in the same test. Thanks a lot!
