### ISSUE TITLE
Proposal: simulate JSON dump/load round trip of job arguments in sidekiq/testing

### ISSUE THREAD

**Issue by jeandenis-k** [mperham/sidekiq#3514]
Hi! You can't pass symbols or complex ruby objects to Sidekiq workers (which is understandable and well-documented), but that actually works in testing mode. It's easy to have worker that pass tests when they're in fact broken.

To catch these mistakes, I now use the following hack in my test_helper file :

```ruby
require 'sidekiq/testing'
module Sidekiq
  module Worker
    module ClassMethods
      alias orig_drain drain
      def drain
        jobs.each do |job|
          job['args'] = JSON.parse(job['args'].to_json)
        end
        orig_drain
      end
    end
  end
end
```

Do you think it would be worth doing this in Sidekiq directly ? For instance, by redefining the testing method `process_job` to dump and parse job arguments. If you think this is useful, I can provide a pull request.

Thank you for your help!

**Comment by mperham** [comment]
What makes you think it doesn't do this already?

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb#L81

**Comment by jeandenis-k** [comment]
Ah! I have a previous version of Sidekiq that doesn't simulate the JSON round trip in testing. I scanned master to make sure the round trip wasn't simulated already, but obviously I missed it. Thanks for your help!
