### ISSUE TITLE
Sidekiq should set CLIENT SETNAME for debugging

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3516]
Redis's CLIENT SETNAME allows the client to give info about the connection for debugging purposes.  You cannot include spaces in the ID.  My initial idea is this ID:

```ruby
options[:id] ||= "Sidekiq-#{Sidekiq.server? ? "server" : "client"}-PID-#{$$}"
 ```

Any other suggestions for useful info to include?

**Comment by ryansch** [comment]
PID isn't useful in containerized environments.  Hostname would be the container id and would be far more useful to me.

**Comment by mperham** [comment]
Good point, I'm not sure if I should assume containers or not.  Notice the hammer operator; the default id can be customized:

```ruby
config.redis = { :id => '...' }
```

**Comment by ryansch** [comment]
I've never heard it called the "hammer operator" before.  That's great.

**Comment by mperham** [comment]
I left it as is.  The remote IP should already be available in the list of connections.  The PID is there to narrow down which process on that host/container.

**Comment by vassilevsky** [comment]
If your Redis server administrator has renamed the CLIENT command (to prevent CLENT KILLs):
* If you know the renamed command, you can remap it: https://github.com/redis/redis-rb/pull/586#issuecomment-310629204
* If you don't know the renamed command, and so CLIENT commands are inaccessible, you can disable this feature by setting id to nil: https://github.com/mperham/sidekiq/issues/3521#issuecomment-310056217
