### ISSUE TITLE
[Feature Request] Pause Periodic Jobs in Cron Tab

### ISSUE THREAD

**Issue by samrispaud** [mperham/sidekiq#3523]
The Sidekiq Cron gem had functionality to pause periodic jobs from the Sidekiq UI. We've recently upgraded to enterprise and I don't see any way to do this in the UI or via the API but I think something like this would be very useful. 

Does something like this exist in enterprise already or would it be possible to add something like this?

**Comment by mperham** [comment]
Can you give us the use case?

**Comment by samrispaud** [comment]
So there are two uses cases:
1) Generally, we have jobs that run very frequently and rely on external APIs. If these API have outages or other problems it's been convenient to pause these jobs instead of having them run frequently and cause errors to bubble up.

2) In a specific case, we have a job that runs every 60 seconds and calls a subscriptions API. The endpoint only returns changed since the last time it was called. In the past, if we every wanted to test this endpoint locally we could pause the periodic job in our staging environment and run the periodic job locally to ensure the local environment is receiving the subscription changes from the API.

**Comment by mperham** [comment]
Thanks, this is useful to know.

1. is best handled by disabling retries.  Retries are critical for event-driven jobs but not usually necessary for frequently run periodic jobs.  If one minute fails, the next one will succeed, etc.
2. is pretty specific to your app and that particular API.

You can add a form of this functionality to your app directly: have your periodic jobs check if they are disabled when they run:

```ruby
def perform
  return if disabled?
  ...
end

def disabled?
  !!Sidekiq.redis {|c| c.get("disable_periodic_jobs") }
end

def self.disable!
  # set a flag in Redis, it will expire after 10 minutes
  Sidekiq.redis {|c| c.set("disable_periodic_jobs", 1, ex: 600) }
end
```

Call disable! whenever you want in a console and you've got a 10 minute window to work with.  All this said, I might add an API similar to this in a future version.

**Comment by mperham** [comment]
Further thought leads me to think that adding this API would be a bad idea.  Having a global disable is fine but then another customer will immediately show a use case where they want to pause X and Y but don't want to pause Z.  It's better to defer this task to the application where the developer can control the exact semantics.

**Comment by samrispaud** [comment]
I agree the global disable could cause a problem like the one you describe above. I was more thinking along the lines of being able to pause each job individually (ie. you could pause MyPeriodicWorkerA but leave behavior of other jobs like MyPeriodicWorkerB untouched) but not sure how easy this solution is to implement
