### ISSUE TITLE
how to bypass aliases in active_record extension?

### ISSUE THREAD

**Issue by michelson** [mperham/sidekiq#3524]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
sidekiq 5.0.4 & pro 3.3.3 , rails 4.1.14

previously in sidekiq 4 I've handled the delayed extensions bypassing the alias methods.

```ruby
# delay extensions available but prefixed with sidekiq_
Sidekiq.hook_rails! 
# disable delayed extensions
Sidekiq.remove_delay!
```

in current version `hook_rails` is not available, and when the `require "sidekiq/extensions/active_record"
` is required in initializer it adds the alias methods (ie, delay). 

how can I bypass those aliases ? we need that in order to not collide with a `.delay` method on one model.

ps: I've commented the aliases and our app's specs pass. would you accept a patch in which aliases can be skipped ?

**Comment by mperham** [comment]
They're not meant to be configurable and I try to discourage their use at all.  Is there some reason you can't rename that model's method?

**Comment by michelson** [comment]
Hi @mperham , right now is complicated because we already have a column named delay and has millions of rows.
Given that you discourage the use of this extension maybe it would be a good idea to remove the alias names :dagger: :)

**Comment by mperham** [comment]
If you enable the delay extensions, you are going to get the delay methods.  Don't use them if they conflict with your app or remove the aliases in a monkeypatch in your initializer.

**Comment by michelson** [comment]
Thanks Mike, monkeypatch seems to be a good idea in this case.

I've fixed my problem with: 
```
Sidekiq::Extensions.enable_delay!
ActiveRecord::Base.send :undef_method, :delay
```
