### ISSUE TITLE
Updating 5.0.2 => 5.0.3 increased 1.5min load time of our puma server

### ISSUE THREAD

**Issue by rafaelsales** [mperham/sidekiq#3525]
Ruby version: ruby 2.3.4-p301
Sidekiq / Pro / Enterprise version(s): sidekiq (5.0.3) sidekiq-ent (1.5.4) sidekiq-pro (3.5.1)

Reverting the following commit fixes the issue:
Update how delayed extensions are loaded, fixes #3509 - https://github.com/mperham/sidekiq/commit/ad98a32cbc478b3559796b1c96b66e9f40cba414

**Comment by mperham** [comment]
Try master. There was a fix.

**Comment by rafaelsales** [comment]
@mperham works like a charm! thanks!

**Comment by mhuggins** [comment]
@mperham Is there a sidekiq-pro release coming for this?  We are experiencing this slowness as well.

**Comment by mperham** [comment]
Right now you need to use master. 5.0.4 later this week.
