### ISSUE TITLE
How to prevent Sidekiq from maxing out RAM

### ISSUE THREAD

**Issue by hmistry** [mperham/sidekiq#3527]
Is there a configuration for Sidekiq to check if RAM is say >80%, it will halt spawning another worker thread to perform jobs in the queue? When RAM dips below the set limit, it will resume.

You can guess the use case: set threads to a large number, small memory jobs = many workers gets processed, large memory jobs = fewer workers to stay within RAM limits and not hit the swap disk bringing the system to a crawl.

**Comment by mperham** [comment]
There is not.

**Comment by hmistry** [comment]
Ok thanks. Might be a nice addition down the road... if possible.

**Comment by mperham** [comment]
Sidekiq can't control memory allocation anymore than any other gem. It's up to the app to keep itself under control.

**Comment by hmistry** [comment]
Correct, not expecting it to do that.
