### ISSUE TITLE
Consequences of Extensions.enable_delay! ?

### ISSUE THREAD

**Issue by narfanator** [mperham/sidekiq#3528]
I'm looking at committing the `SideKiq::Extensions.enable_delay!` directive into a live website, but I don't know what the additional consequences or effects are of the directive.

What else happens when you enable these extensions?

~and/or~

Why are the extensions not enabled by default?

Thanks!

**Comment by mperham** [comment]
> The Delayed Extensions delay, delay_in and delay_until APIs are no longer available by default. The extensions allow you to marshal job arguments as YAML, leading to cases where job payloads could be many 100s of KB or larger if not careful, leading to Redis networking timeouts or other problems. As noted in the Best Practices wiki page, Sidekiq is designed for jobs with small, simple arguments.
