### ISSUE TITLE
Sane way to shutdown Sidekiq

### ISSUE THREAD

**Issue by eredi93** [mperham/sidekiq#3529]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s):
sidekiq (5.0)
sidekiq-ent (1.5.4)
sidekiq-pro (3.5.0)

I'm trying to kill the master sidekiq process from within a sidekiq job. Some context:
My setup is monit that manages a bunch of sidekiq processes, on a release of the new app ( we update a symlink) i want to kill the sidekiq process once the job is finish and monit will restart a new one running the new release.
With a middleware i wanna kill the sidekiq after the yield block.
Is there a sane way to do this?

**Comment by mperham** [comment]
You send it the TERM signal.

**Comment by eredi93** [comment]
as i wanna run this once finish the job and i dont know which PID the master thread is running on i ended up creating a middleware that run launcher.stop if the process is running on an old release
```
      class ReleaseCheck
        def initialize(launcher:)
          @launcher = launcher
        end
        def call(*)
          yield

          return if current? || @launcher.stopping?
          @leader.stop
        end
      end
```
i there anything wrong with ^^?

**Comment by mperham** [comment]
TERM doesn't actually shut down the process until all jobs are complete or `-t` timeout has passed:

```ruby
`kill -TERM #{Process.ppid}`
```
