### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by neilmiddleton** [mperham/sidekiq#3530]
I've just done a `bundle up` on sidekiq-pro, which has taken me from sidekiq 3.3.3 to 5.0.3.

However, I now see this:

```
  Gem Load Error is: constant Sidekiq::LICENSE not defined
```

I haven't been able to find anything docs wise to suggest that I need to do something, so is there something I need to do?

**Comment by mperham** [comment]
I think you are locked on an old Pro version in your Gemfile.
