### ISSUE TITLE
Jobs don't requeue

### ISSUE THREAD

**Issue by ggennrich** [mperham/sidekiq#3533]
We have some long running workers that don't always finish during a Capistrano deploy and terminate after 60 seconds. My expectation is that these workers would requeue the job but the job just disappears. I thought the reliability in Sidekiq Pro addresses this but we just purchased it and are seeing the same issues. We are using Rails 4.0.13, Ruby 2.3.1, Sidekiq 5.0.0, Sidekiq Pro 3.5.1 on Ubuntu 14.04 machines.

**Comment by mperham** [comment]
If you are using super_fetch, the jobs will be retried at some point in the future but not immediately.  I'd guess that your deploy is killing the Sidekiq process too quickly.

```
To safely shut down Sidekiq, you need to send it the TSTP signal as early as possible in your deploy process and the TERM signal as late as possible. TSTP tells Sidekiq to stop pulling new work and finish all current work. TERM tells Sidekiq to exit within N seconds, where N is set by the -t timeout option and defaults to 8. Using TSTP+TERM in your deploy process gives your jobs the maximum amount of time to finish before exiting.
```

**Comment by ggennrich** [comment]
Thanks for your response. We are definitely sending the TSTP signal at the start of the deploy using `bundle exec sidekiqctl quiet` and then at the end of the deploy we send the TERM signal using `bundle exec sidekiqctl stop`. There is about a 60 second window.

As a test, I created a worker than is just an infinite while loop. This job would obviously never finish so my expectation is that it would get requeued. Looking in the Web UI, after the TSTP signal is sent on deploy I see that worker with the 'quiet' tag. It stays that way for a minute and then it disappears. The job never shows back up in the queue. It should since it would never finish. What else are we doing wrong?

**Comment by mperham** [comment]
It's in a private queue and will be recovered by super fetch at some point in the future. Recovery does not happen immediately.

**Comment by lacco** [comment]
@ggennrich I am experiencing the exact issues with an infinite-while-loop worker, but using the normal and not pro version of sidekiq. How did you solve your issue?
