### ISSUE TITLE
Pro Batches: OnComplete Callback doesn't seem to trigger when batches are nested

### ISSUE THREAD

**Issue by swanandp** [mperham/sidekiq#3535]
Ruby version: 2.3.1

Sidekiq versions:
sidekiq (4.2.10)
sidekiq-pro (3.5.1)
sidekiq-ent (1.6.0)

Please include your initializer and any error message with the full backtrace.

```Ruby
redis_url = "redis://#{Rails.application.secrets.redis_url}/12"

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url, driver: :hiredis }
end

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.redis = { url: redis_url, driver: :hiredis }

  config.super_fetch!
  config.reliable_scheduler!

  Rails.logger = Sidekiq::Logging.logger
  ActiveRecord::Base.logger = Sidekiq::Logging.logger

  config.periodic do |mgr|
    # see any crontab reference for the first argument
    # e.g. http://www.adminschoice.com/crontab-quick-reference
    #      https://crontab.guru/
    if Rails.env.production?
        # some periodic jobs here
    end
  end
end
```

> Are you using an old version?

Nope

> Have you checked the changelog to see if your issue has been fixed in a later version?

Checked, no mention of this issue in Wiki or Changelog

## Description

The `:complete` callback doesn't seem to trigger for a top level batch when jobs are completed within workflows that are nested under the top level batch. I say workflows because simple nesting ( described further down ) _does_ work.

## What works

Enqueuing simple, non-batched jobs under the top level batch.  With this, the callback is triggered.

```Ruby
def perform(user_id)
  # other stuff
  # ...
  top_level_batch = Sidekiq::Batch.new
  top_level_batch.on(
    :complete,
    NightlyRefreshCallback,
    "user_id" => user.id
  )

  top_level_batch.jobs do
    SimpleSidekiqJobWithNoBatches.perform_async(user.id, collection.first)
  end
end
```

Enqueuing a single level nested batch under the top level batch.  With this, both `NightlyRefreshCallback#other_callback` and the `NightlyRefreshCallback#on_complete` are triggered.

```Ruby
def perform(user_id)
  # other stuff
  # ...
  top_level_batch = Sidekiq::Batch.new
  top_level_batch.on(
    :complete,
    NightlyRefreshCallback,
    "user_id" => user.id
  )

  top_level_batch.jobs do
    nested_batch = Sidekiq::Batch.new

    top_level_batch.on(
      :complete,
      'NightlyRefreshCallback#other_callback',
      "user_id" => user.id
    )

    nested_batch.jobs do
      collection do |element|
        SimpleSidekiqJobWithNoBatches.perform_async(user.id, element)
      end
    end
  end
end

```

## What doesn't work

```Ruby
class MyTopLevelJob
  include Sidekiq::Worker

  def perform(user_id)
    user = User.find(user_id)
    # ... other stuff
    collection = gather_data # representative code, not actual code
    # ...
    top_level_batch = Sidekiq::Batch.new
    top_level_batch.on(
      :complete,
      NightlyRefreshCallback,
      "user_id" => user.id
    )

    top_level_batch.jobs do
      collection.each do |element|
        OperationThatEnqueuesComplexWorkflows.import(user, element)
      end
    end
  end
end
```

`OperationThatEnqueuesComplexWorkflows` is an object that processes the element, and enqueues further jobs under a [really complex workflow](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches). These nested workflows have `:success` callbacks that _do_ get triggered.

## Problem

`NightlyRefreshCallback#on_complete` should get triggered, but it isn't.

Is this expected?  What can I do to ensure the top-level callback gets triggered?

**Comment by mperham** [comment]
Does it work if you switch the top level callback to :success?

**Comment by swanandp** [comment]
I'll try, but success might not work for me, because some jobs definitely
fail frequently. And I really like to rely on the retry with exponential
back off feature.

But let me check it out.

**Comment by mperham** [comment]
Does the top level batch have a job in it?

**Comment by swanandp** [comment]
> Does the top level batch have a job in it?

It doesn't , but I tried adding a job. Here's the observation:

1. If I add a job to the top-level batch, the batch shows up in `/sidekiq/batches`, but the callback doesn't trigger.   The batch UI shows the correct callback registered.
2. If I don't add a job to the top-level batch, then batch doesn't even show up in `/sidekiq/batches`

 I tried the `:success` callback as well, instead of `:complete`, but same behaviour.

**Comment by mperham** [comment]
1. Hmmm.  I have a **ton** of tests around batches to verify callbacks are fired in various cases.  Can you give me a standalone script which reproduces the problem so I can verify, fix the issue and add it as a regression test?
2. Correct, batches are not registered with the UI until they have a job in them.  The documentation is very clear: batches are considered invalid until they have a job in them.

**Comment by swanandp** [comment]
Here's an attempt at creating a standalone script that reproduces the problem: https://github.com/swanandp/sidekiq-batch-test

Not surprisingly, the code works here, and callback gets triggered.  Which tells me there is some quirk in the production code.  I will try and bring parity between the example code and production code.

But please do look at the code, you might spot potential root cause by just looking at the code.

**Comment by mperham** [comment]
Yep, the script code looks fine to me.  Please follow up when you discover the difference.

**Comment by swanandp** [comment]
Closing this, because I think Sidekiq is doing the right thing:

> If I add a job to the top-level batch, the batch shows up in /sidekiq/batches, *but the callback doesn't trigger*. The batch UI shows the correct callback registered.

In my repeated testing with various combinations, this statement (with emphasis) is proven to be wrong. The callbacks are actually working, just not the way I want.  They get triggered when the top-level job finishes running once.

It _isn't effective for me_, because I need the callback to be based on the jobs that are created from the workflows, not from the top-level batch. i.e. without any jobs in the top-level batch, I want the callbacks triggered when all the workflows are "complete".
