### ISSUE TITLE
Should region code in the locale code be uppercase?

### ISSUE THREAD

**Issue by acenqiu** [mperham/sidekiq#3538]
All locale files in sidekiq use lowercase locale name now, like `zh-cn`, `pt-br`. However, gems like [rails-18n](https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale) and [devise-i18n](https://github.com/tigrish/devise-i18n/tree/master/rails/locales) use the format of upcased  region code, which make inconsistent. So I am wondering which one is the ruby way.

**Comment by mperham** [comment]
I downcase everything so it doesn't matter what the browsers send in the "Accept-Language" header: zh-cn, zh-CN, Zh-Cn.  I'm not sure if the case matters but it hasn't mattered in the last 4 years.  :-)
