### ISSUE TITLE
Rescue `EOFError` in a worker

### ISSUE THREAD

**Issue by juandazapata** [mperham/sidekiq#3542]
## Versions

```
Sidekiq / Pro / Enterprise version(s): Enterprise
Running in ruby 2.3.3p222
Sidekiq Pro 3.4.5 / Sidekiq Enterprise 1.5.2, commercially licensed.
```

## Initializer
```ruby
# config/initializers/sidekiq.rb
Sidekiq.default_worker_options = { backtrace: false, retry: true, queue: :default }
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.failures_default_mode = :exhausted
end
```

## Problem
We're constantly getting in our error reporting tool an `EOFError` when sending emails and when interacting with some external services. Per #2618, we know that this happens when the external service experiences outages or reliability issues.

Rescuing the exception in the perform method won't work and we don't want to ignore the `EOFError` application-wide because we only want to ignore/retry in some specific cases:

```ruby
class MyWorker
  def perform
    # do something...
  rescue EOFError
    # This doesn't get called
  end
end
```

Any ideas on how to handle this rescue?

**Comment by mperham** [comment]
How are you sending emails in your worker?  Could you show me the actual code sending the email?

**Comment by juandazapata** [comment]
After further exploration, this seems like a problem with `ActionMailer` itself for our use case. Sorry for taking your time and thanks for being so responsive. I'm closing this now.
