### ISSUE TITLE
Did not find our own heartbeat within 10 seconds, that's bad

### ISSUE THREAD

**Issue by mathieujobin** [mperham/sidekiq#3543]
Ruby version:
  * ruby-2.3.4
  * rails (5.0.4)

Sidekiq / Pro / Enterprise version(s):
  * rspec-sidekiq (3.0.1)
  * sidekiq (4.2.10)
  * sidekiq-failures (1.0.0)
  * sidekiq-pro (3.5.1)
  * sidekiq-status (0.6.0)
  * sidekiq-unique-jobs (3.0.14)

Please include your initializer and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
  config.redis = REDIS_CONFIG
  config.super_fetch!
end

Sidekiq.configure_client do |config|
  config.redis = REDIS_CONFIG
end
```

Error:
`Did not find our own heartbeat within 10 seconds, that's bad`

Trace:
```
10 non-project frames
1
File "/var/lib/gems/2.3.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb" line 194 in wait_for_heartbeat
2
File "/var/lib/gems/2.3.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb" line 223 in block in startup
3
File "/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb" line 17 in watchdog
4
File "/var/lib/gems/2.3.0/gems/sidekiq-pro-3.5.1/lib/sidekiq/pro/super_fetch.rb" line 215 in startup
5
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 348 in run_task
6
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 337 in block (3 levels) in create_worker
7
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 320 in loop
8
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 320 in block (2 levels) in create_worker
9
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 319 in catch
10
File "/var/lib/gems/2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb" line 319 in block in create_worker
```

we haven't tested 5.x yet, could it solve this issue ?

I checked the changed log, there is a slowdown regression from 5.0.2 that got fix in 5.0.4
but nothing in 4.x

**Comment by mperham** [comment]
It typically means your Redis is in really bad shape.  Do you have any monitoring or historical metrics for Redis?  Do you see anything unusual around the same time?

**Comment by mathieujobin** [comment]
thanks for the hint, we'll investigate

**Comment by mathieujobin** [comment]
I'm not seeing anything out of the ordinary in our monitoring ..
this only occurs once on deploy. it seems to have started happening after enabling Superfetch

**Comment by mperham** [comment]
What is REDIS_CONFIG in your initializer?

**Comment by scottmartinnet** [comment]
I'm also experiencing this on our superfetch-enabled system that's running Ruby 2.3.4, Rails 4.2.8, Sidekiq 5.0.0 and Sidekiq Pro 3.5.0.  It appears to happen with no pattern we can discern.  Our Redis server appears healthy.  If there's anything I can add to help narrow this down, let me know.

**Comment by mperham** [comment]
@scottmartinnet Could you show me your initializer and upgrade to the latest versions?

**Comment by mathieujobin** [comment]
```

**Comment by mperham** [comment]
Doesn't give me any ideas. I'd use the TTIN signal and maybe "redis-cli monitor" to debug what's happening upon startup.

**Comment by scottmartinnet** [comment]
Here's my initializer:

`
Sidekiq.configure_client do |config|
  config.redis = {url: ENV.fetch('REDIS_PROVIDER', 'redis://127.0.0.1:6379/') }
end

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  
  config.redis = { url: ENV.fetch('REDIS_PROVIDER', 'redis://127.0.0.1:6379/') }

  database_url = ENV['DATABASE_URL']
  if database_url
    ENV['DATABASE_URL'] = "#{database_url}?pool=50"
    ActiveRecord::Base.establish_connection
  end
end

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq::Extensions.enable_delay!
`

REDIS_PROVIDER is a normal redis URL with no extra options.

**Comment by scottmartinnet** [comment]
I've committed a upgrade to the Sidekiq versions for the next release of our app, after which I'll let you know whether the crash changes.

**Comment by mperham** [comment]
Thanks.

BTW, your Redis config is unnecessary and potentially harmful.  REDIS_PROVIDER is not supposed to be a URL, it is supposed to be the name of the ENV variable that contains the URL.  If it's not set, Sidekiq will fall back to localhost:6379.

```
heroku config:set REDIS_PROVIDER=REDISTOGO_URL
```

**Comment by scottmartinnet** [comment]
I see.  I'll correct this as well.

**Comment by mperham** [comment]
Any progress?

**Comment by scottmartinnet** [comment]
We deployed the update to sidekiq 5.0.4 and sidekiq-pro 3.5.2, along with the suggested change to the configuration.  The errors continue unchanged.

**Comment by mperham** [comment]
Can you show me the top set of numbers in your Web UI?  I'd like to know how many retries, scheduled, etc you have in Redis.  Also, please gist me the output of `redis-cli info` against your Redis instance.

**Comment by scottmartinnet** [comment]
Numbers from web UI:
5,903,271 Processed
526,884 Failed
7 Busy
33 Enqueued
0 Retries
16,179 Scheduled
334 Dead

redis-cli info:
https://gist.github.com/scottmartinnet/3064b798f2a52fddd823029f816f1f8a

**Comment by mperham** [comment]
Can you post your initializer?

```
# Keyspace
db0:keys=4043680,expires=4043548,avg_ttl=1927991567
```

I think I see one thing wrong: you're stuffing everything into one Redis database.  If you are using Redis as a cache, it is recommended to put Sidekiq's data in a different database:

```
config.redis = { db: 1 }
```

super_fetch has to scan the entire keyspace when looking for orphaned jobs, that means about 20,000 calls to scan your 4 million keys at 200 keys per call.  I'd guess that 99% of those keys are cached data and not related to Sidekiq.

**Comment by scottmartinnet** [comment]
I see.  We'll switch to using database 1 in our next release.

**Comment by mathieujobin** [comment]
we had a lot of redis usage in /0 and we make a huge split, separating nonces from cache, from sidekiq, etc... I am not seeing this error anymore

thank you

**Comment by scottmartinnet** [comment]
We switched to using /1, which is not used by any other parts of our application and these errors have continued, but at a much lower frequency.  Is there anything else we can do to address this problem?  It's at a low enough frequency that we could just ignore it, but I'd rather not.

**Comment by mperham** [comment]
@scottmartinnet It's possible that you have an extremely busy Redis and 0 is just taking most of the CPU time.  The other thing to do would be to move Sidekiq onto its own Redis instance.  Now that you've moved databases, it should be easier to move to a separate instance.
