### ISSUE TITLE
Freezing of jobs

### ISSUE THREAD

**Issue by h0lyalg0rithm** [mperham/sidekiq#3544]
Hi Mike,
Before I start with the issue, I would like to thank you for all of the open source work you have done for the community for last few years.

Here is my issue: 
Sidekiq processes are stuck and not being processed.Here is my configuration.

Ruby version: 2.2.2
Sidekiq / Pro / Enterprise version(s):  Sidekiq open-source

Please include your initializer and any error message with the full backtrace.

 ```
   require 'sidekiq'
   require 'resolv-replace'
     
   if ENV['REDIS_URL'].present?
     Sidekiq.configure_server do |config|
       config.redis = { url: "#{ENV['REDIS_URL']}", network_timeout: 15 }
     end 
     Sidekiq.configure_client do |config|
       config.redis = { url: "#{ENV['REDIS_URL']}", network_timeout: 15 }
    end
  end
```
I am using version 4.2.10 of sidekiq.

Here is the trace by running `kill --ttin pid`
[https://gist.github.com/h0lyalg0rithm/31cd1a393dc484b52a3168db5a7fdc03](https://gist.github.com/h0lyalg0rithm/31cd1a393dc484b52a3168db5a7fdc03)

**Comment by mperham** [comment]
Looks like you have a few threads simply waiting for jobs from Redis, another few waiting for a DB connection and one thread trying to ping postgresql over the network.  There's nothing obviously wrong.  I would do a couple of things:

1. Remove that resolv-replace.  It hasn't been necessary for years now afaik.
2. Update the pg gem to latest version.
3. Update to rails 4.2.9.
4. Update ruby to something newer if possible.

**Comment by h0lyalg0rithm** [comment]
@mperham I am extremely sorry.The bug was related to the database.I set a timeout in the postgresql database and the issue seems to be disappeared.

I did upgrade the gem to the latest versions however couldn't do it for the ruby version.I think it would be good to add this to the [Troubleshooting page](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting) .

This way we dont create unwanted issues on the repository.

Here is my config

```
tcp_keepalives_idle = 60                # TCP_KEEPIDLE, in seconds;
                                        # 0 selects the system default
tcp_keepalives_interval = 60            # TCP_KEEPINTVL, in seconds;
                                        # 0 selects the system default
tcp_keepalives_count = 100              # TCP_KEEPCNT;
                                        # 0 selects the system default
```

Thanks for your help
