### ISSUE TITLE
Someone destroyed wiki page `Monitoring`

### ISSUE THREAD

**Issue by Zhomart** [mperham/sidekiq#3546]
I accidentally saved something there. Currently it's empty.

https://github.com/mperham/sidekiq/wiki/Monitoring/_history

**Comment by ryansch** [comment]
Looks like it was a brand new github user.

**Comment by ryansch** [comment]
After a false start I was able to revert the changes in question.

**Comment by mperham** [comment]
Thanks, I or another committer will need to check out the wiki content and revert that change manually.  It's a pain but can be restored. I blocked that user.  Feel free to report him.

**Comment by mperham** [comment]
Can you confirm that was his only change?

**Comment by ryansch** [comment]
@mperham Yes.  No legitimate changes since May.  I just rolled the page back to that point.
