### ISSUE TITLE
Network error while fetching enterprise.contribsys.com

### ISSUE THREAD

**Issue by eproulx-petalmd** [mperham/sidekiq#3551]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 5.0.4 / 3.5.1 / 1.6.0

Hi, we have a problem when bundling :

Bundler::HTTPError Could not fetch specs from https://enterprise.contribsys.com/Fetching source index from https://enterprise.contribsys.com/

Network error while fetching https://our_user_name@enterprise.contribsys.com/quick/Marshal.4.8/sidekiq-ent-0.5.0.gemspec.rz (too many connection resets (due to Net::OpenTimeout - Net::OpenTimeout) after 0 requests on
70198226871840, last used 1500402478.6304681 seconds ago)

Thanks

**Comment by jonhoman** [comment]
Appears to be similar to https://github.com/mperham/sidekiq/issues/3427. 

Sidekiq status page, https://status.sidekiq.org/, also shows the outage.

**Comment by mperham** [comment]
The network flapping.  I suspect DigitalOcean or Cloudflare is having big network problems as I have three servers in three different datacenters and all are struggling.

**Comment by mperham** [comment]
Keep trying, it seems to be getting better.

**Comment by eproulx-petalmd** [comment]
It's back. Thanks for the quick response

**Comment by dylanbromby** [comment]
FYI this is not back up for everyone - we're still getting timeouts both from Bundler and straight up curl from the CLI.
