### ISSUE TITLE
403 Forbidden after update to 5.0.4

### ISSUE THREAD

**Issue by CJStadler** [mperham/sidekiq#3553]
Ruby version: 2.3.4
Rails version: 5.0.0.1
Sidekiq / Pro / Enterprise version(s):
sidekiq (5.0.4)
sidekiq-pro (3.5.1)

Initializer:
```rb
require 'sidekiq/pro/web'

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end

Sidekiq.default_worker_options = { retry: Settings.sidekiq.retries }

Sidekiq::Web.app_url = '/admin'
```

Upgrading to sidekiq 5.0.4 triggered an update of rack-protection to 2.0.0 due to the dependency constraint changing in https://github.com/mperham/sidekiq/commit/d1cd699d2d1e83c936bc11ff6ef46e53b7a33710. After this all actions from the web UI returned 403 Forbidden with the log `attack prevented by Rack::Protection::AuthenticityToken`. Following the related instructions [on the wiki](https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden) did not resolve the issue.

I noticed that https://github.com/sinatra/sinatra/commit/4f1bdba0c50e7a69d7dddaaf49231799ab98a192 on rack-protection acknowledges breaking compatibility with Rails, but based on my testing it was first broken in https://github.com/sinatra/sinatra/commit/aac8e3bce4d5c1be211fe25a1ea012572b841df8. These commits suggest to me that it should not be possible on rack-protection 2.0 for the sidekiq web app and Rails to share an authenticity token. Am I misunderstanding something or does this mean that sidekiq should require rack_protection < 2.0?

I have not been able to recreate this on other apps so there must also be something about our configuration that is triggering this.

Thanks!

**Comment by mperham** [comment]
I can't lock down the rack gems; it will cause compatibility issues with Rails versions.

I would upgrade rails and rack to make sure you pick up any fixes, 5.0.4 is the latest Rails 5.0 patch.  You'll need to find a combination of gem versions that work together; Sidekiq can't enforce that AFAIK or control your web session subsystem.

**Comment by CJStadler** [comment]
Rails does not have a dependency on `rack-protection`, so I'm confused why pinning its version would cause compatibility issues. Of course that would not be ideal for other reasons.

I guess my question is whether sidekiq web needs to share the same session as the Rails app, because I believe that with `rack-protection` 2.0 [that is no longer possible](https://github.com/sinatra/sinatra/commit/4f1bdba0c50e7a69d7dddaaf49231799ab98a192).

**Comment by mperham** [comment]
You need to give Sidekiq Web a valid and working session that it can use with rack-protection -- that's it.  It doesn't require you to share the session with Rails.

I guess I'm still unclear how Sidekiq could fix this.  Isn't this is a bug between rack-protection and rails?  Don't they need to work out the compatibility issues?

**Comment by CJStadler** [comment]
The fix for this turned out to be as simple as clearing cookies after upgrading. The incompatible csrf token was actually just from the older version of rack-protection, so clearing the session caused it to generate a new one. The incompatibility between Rails's and rack-protection's csrf tokens isn't actually an issue because they are stored separately in the session.

Thanks for your help!

**Comment by jaman1020** [comment]
Honestly I feel like saying that you should clear cookies when upgrading should be added to the wiki somewhere. Cookie issues were causing this for me and this is the only place I found that referenced it after 30 minutes of making sure I hadn't messed up my config somewhere...

**Comment by CJStadler** [comment]
@jaman1020 you could add something about it on [this page](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting).

**Comment by mperham** [comment]
@jaman1020 The Sidekiq wiki is not a repository for every Rack session edge case.  Rack session configuration is specific to each app; the wiki would contain dozens of cargo culted solutions -- this way leads madness.
