### ISSUE TITLE
Timeout for https://gems.contribsys.com

### ISSUE THREAD

**Issue by dylanbromby** [mperham/sidekiq#3554]
FYI this is not back up for everyone - we're still getting timeouts both from Bundler and straight up curl from the CLI. Our datacenter is in Southern Cal and we're attempting to hit https://gems.contribsys.com which we've done successfully since upgrading to Sidekiq Pro last August.

**Comment by mperham** [comment]
What IP address are you seeing?

**Comment by dylanbromby** [comment]
46.101.47.74

46.101.47.7446.101.47.74

46.101.47.74

Also, Github is down.

**Comment by mperham** [comment]
That's the right IP. Sounds like you're having network issues too. No one has reported problems for the last 8 hours.

**Comment by dylanbromby** [comment]
We're not having network issues - we're having the same issue in our Orange County and Seattle locations - and we're not all on the same network - in addition to our datacenter. Could it be an issue with our account? We acquired a license in August of last year so it *shouldn't* be an issue...

**Comment by mperham** [comment]
If your account is suspended, you'll get a 403 Unauthorized, not a timeout.  Can you curl http://gems.contribsys.com locally? You should get a simple "https only" message.

**Comment by dylanbromby** [comment]
Yeah we get a 401 unauth locally on a curl - but even curl time out from the datacenter. I'm actually wondering if - for some bizarre reason - our perimeter FW systems suddenly blocked the site. Looking into that now. It'd be odd timing considering it seems like the site had legitimate issues today.

**Comment by mperham** [comment]
Sorry, I don't know your customer email so I don't know your account and it's status.

**Comment by dylanbromby** [comment]
Any issue posting it here?

**Comment by dylanbromby** [comment]
Not our firewall either. We'll keep digging - I doubt it's an account issue. Hopefully it's something silly on our end. Our NOC is investigating too.

**Comment by mperham** [comment]
You can email me directly but the Bundler credentials are what you need to protect, not the email address.

**Comment by dylanbromby** [comment]
We can ping contribsys.com w/out any issue so there's something amok with the DNS or the specific IP.

**Comment by mperham** [comment]
You should never get a 401 with http.  You are still using https.  Curl the basic hostname with http.

**Comment by dylanbromby** [comment]
Locally we see the https-only message, timing out from our network. I'm sure it's on our end. I'll close this out while we dig deeper. Appreciate the time and input.
