### ISSUE TITLE
Are rails code reloading in dev officially supported on sidekiq 5.0+?

### ISSUE THREAD

**Issue by fgrehm** [mperham/sidekiq#3555]
I remember reading that code reloading works on 5.0+ and I remember confirming last time I tried. I can't seem to find the docs / wiki page where that is mentioned but I did find a [FAQ entry saying that it is not supported](https://github.com/mperham/sidekiq/wiki/FAQ#why-doesnt-sidekiq-autoload-my-rails-application-code) so I was wondering what's up with that 😄 

Thanks in advance!

**Comment by mperham** [comment]
It will reload code.  I've updated the FAQ.

**Comment by fgrehm** [comment]
Thanks!
