### ISSUE TITLE
Access Queue from within Worker

### ISSUE THREAD

**Issue by ShiroiKuma** [mperham/sidekiq#3556]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): Sidekiq v4.2.10 

I've got a Worker that's only job is to output the current Queue by email, however when I call the following from within a Worker. It's always empty even though I have over 30 jobs in my queue via the Sidekiq WebUI.

```
queue = Sidekiq::Queue.new
queue.each do |job|
  puts job.klass
end
```
Is this a limitation?

**Comment by mperham** [comment]
That will examine the `default` queue.  Presumably your queue has another name?

**Comment by ShiroiKuma** [comment]
Currently I'm only using the default queue.

My entire test worker's coder is below. Between the 2 puts statements, nothing else get's outputted at all.

```
require 'sidekiq/api'

class MaintenanceWorker
  include Sidekiq::Worker

  def perform(*args)

byebug

    puts '### Start Queue Check'
    queue = Sidekiq::Queue.new
    queue.each do |job|
      puts job.klass
    end
    puts '### End Queue Check'

    MaintenanceWorker.perform_in(1.minutes)
  end
end
```

**Comment by mperham** [comment]
It's possible Sidekiq is fetching all jobs from the queue at once.  Sidekiq will process 25 jobs concurrently by default.

It's not a good idea to write a "self-scheduling"/"looping" worker like that.  If there's ever a problem, you can get retries which cause multiple copies to be running at once.

**Comment by ShiroiKuma** [comment]
It's possible. Albeit several of them are scheduled very fair in advance. Let me go back to the documentation and see if I can find a call to get the currently processing list too.

![screen shot 2017-07-19 at 12 17 03](https://user-images.githubusercontent.com/7948640/28349215-624870ea-6c7c-11e7-85ca-28c5e2cb85fc.png)

For scheduling/looping, I'm probably better off using a rake task and cron right?

**Comment by mperham** [comment]
Sidekiq::Workers.new is the API, but it's not millisecond precise, only updated every 5 seconds.

Yep, I would use cron or a periodic job.

**Comment by ShiroiKuma** [comment]
Thanks for the help and advice. It's very much appreciated.
