### ISSUE TITLE
Configure Redis via sidekiq.yml

### ISSUE THREAD

**Issue by franzliedke** [mperham/sidekiq#3557]
It seems like it is not possible to configure the equivalent of the [proposed initializer code](https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-initializer) via the config file config/sidekiq.yml.

This would be nice to have because we have different Redis connection settings in our various (!) production environments, which means we currently generate initializer code via Puppet when we deploy. This has multiple problems, starting with the order of initializers in which initializers are run etc.

Or am I missing something?

**Comment by mperham** [comment]
You can use the initializer or environment.  You cannot configure Redis in the yml file, by design.

**Comment by franzliedke** [comment]
Thanks for your response (and the awesome project, while we're at it)!

Can you explain (or link to an explanation) why this is by design? As explained above, I would rather refrain from configuring Redis via generated initializer code. (It seems like configuring using environment variable does not allow me to set the namespace.)

And lastly: How does Sidekiq behave when both an environment variable and an initializer are present?

**Comment by mperham** [comment]
I recommend [against using namespaces at all](http://www.mikeperham.com/2015/09/24/storing-data-with-redis/).  Use the environment, this also makes it trivial to move to/from a Redis SaaS in the future.

Sidekiq allows simple Redis config via ENV or complex Redis config via Ruby.  Adding a third config location via YAML just muddies the water and makes the system more complex.
