### ISSUE TITLE
How to set a label on a Sidekiq process

### ISSUE THREAD

**Issue by magnusvk** [mperham/sidekiq#3559]
When I retrieve a `Sidekiq::ProcessSet` all the processes have a `labels` key that would be convenient for me to use. However, I can't figure out a way to actually set those labels to anything. The [`parse_options` method in the `CLI` class](https://github.com/mperham/sidekiq/blob/7fe2515138177eea88823398423470834806b323/lib/sidekiq/cli.rb#L297]) doesn't support either `--label` or `--labels`. Am I missing something, or does this have to be added there?

Thank you.

**Comment by mperham** [comment]
There is no documented way. It's not a public API.
