### ISSUE TITLE
Web footer displays redis client string instead of url

### ISSUE THREAD

**Issue by ryansch** [mperham/sidekiq#3560]
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s):
Sidekiq 5.0.4 / Pro 3.5.1 / Ent 1.6.0

<img width="592" alt="screen shot 2017-07-21 at 10 31 24 am" src="https://user-images.githubusercontent.com/146013/28475078-c74c674c-6dff-11e7-92ee-611171d79b25.png">

**Comment by mperham** [comment]
The Redis driver returns the :id option instead of the location if the option is set. We need to update the code to avoid that.
