### ISSUE TITLE
Sidekiq pro: Sidekiq job hangs in perform and needs a sidekiq restart

### ISSUE THREAD

**Issue by sudhindra-glooko** [mperham/sidekiq#3561]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Sidekiq Pro

Please include your initializer and any error message with the full backtrace.
We are using the stock initializer from your documentation.

This is what we see in newrelic.
83,300,000 | 100.00% | Application code (xxx::xxxRegistrationWorker/perform)

It fixed itself when a deployment happened which restarted sidekiq. 

Wondering if you have a way to keep track and kill these long running jobs or timing them out..

**Comment by mperham** [comment]
Unfortunately there's no easy answer here. You'll need to debug to determine what is wrong, Sidekiq doesn't provide any features to help in this case.

It's impossible for me to provide a safe job timeout so I don't.
