### ISSUE TITLE
same worker using multiple PG connections

### ISSUE THREAD

**Issue by jalberto** [mperham/sidekiq#3562]
Ruby version: 2.3
Sidekiq / Pro / Enterprise version(s): 5.0.4

while investigating this: https://stackoverflow.com/questions/45277397/sidekiq-jobs-stuck-in-busy-with-postgres-rails-5 (it adds some context)

I found this in PG connections list:

```
+------------+-------+-----------------+-----------------------------------+
| database   |   pid | username        | application                       |
|------------+-------+-----------------+-----------------------------------|
| app      | 53744 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53732 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53740 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53736 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53752 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53748 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53764 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53768 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53756 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53760 | app           | sidekiq 5.0.4 app [0 of 30 busy]  |
| app      | 53772 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53776 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53780 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53784 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53792 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53788 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53800 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53796 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
| app      | 53804 | app           | sidekiq 5.0.4 app [10 of 30 busy] |
```

Does this indicates a single worker is using multiple connections?

(notice I am wrapping my code in ActiveRecord#with_connection)

**Comment by mperham** [comment]
What is a worker?

**Comment by jalberto** [comment]
I mean a Job, there is only one sidekiq process with 30 threads.

so, Is this telling one thread is using multiple connections?

Thanks in advance

**Comment by mperham** [comment]
Nope, it means your db connection pool has expanded due to multiple threads running jobs at the same time. Each thread gets a connection.

**Comment by jalberto** [comment]
thanks for the answer (and great work) @mperham 

I still don't get it, if each thread gets one connection, is the output of that sql table wrong? I would expect something like:

```
sidekiq 5.0.4 app [0 of 30 busy]
sidekiq 5.0.4 app [1 of 30 busy]
sidekiq 5.0.4 app [2 of 30 busy]
[...]
```

or is this indicating the thread is not returning the connection to the pool?

Root symptom being, some random jobs get "stuck" for hours even days in "busy" state, but PG is reporting no locks or "idle in transaction" connections

**Comment by mperham** [comment]
The description doesn't matter, note the different pid for each thread.

**Comment by jalberto** [comment]
so then this is only a aesthetic issue? is a bit confusing the same "description" is being used for different threads, puma has a similar behavior, but I can clearly see which puma thread is running each query.

Any suggestion or clue for the "stuck" thing problem?

(feel free to close this if you think is not relevant)

**Comment by mperham** [comment]
Did you read the Problems wiki page?  It has suggestions on how to deal with stuck threads.

**Comment by jalberto** [comment]
yep, I am debugging this from 1 week now, I tried:

- TTIN
- AR#connection_with
- Remove any SQ plugin
- different tweaks in reaper & variables
- even #clear_active_connections! & #connection.close
- a plethora of PG queries/tweaks/timeouts to check any lock or bad connection
- lot of small tweaks in old sidekiq and AR older issues

and of course I am not able to reproduce it in local, the only common thing is the TTIN trace last line:

```
connection_adapters/postgresql_adapter.rb:598:in `async_exec'
```

**Comment by mperham** [comment]
Gist the full TTIN dump.

**Comment by jalberto** [comment]
Much appreciated @mperham 

https://gist.github.com/jalberto/93e68d4d41d757f3fe6f73f4e7d00ea2

At same time I am doing some test with pgbouncer trying to narrow the issue.

**Comment by mperham** [comment]
Do you know the actual sql being executed by pg?  It's possible you have db lock contention.

**Comment by mperham** [comment]
Any idea why your backtraces don't show the pg gem? That has been buggy, make sure you are on latest.

**Comment by jalberto** [comment]
@mperham good quesiton, I am in pg 0.21.0
as for locks, I try to get lock directly form DB, but I cannot see any reported lock (using snippets from here: https://wiki.postgresql.org/wiki/Lock_Monitoring)

**Comment by mperham** [comment]
Seems like the original issue was just a misunderstanding of the pg output.  It's impossible to know more about your stuck issue but the common point is `app/services/etl/ie_filing/parse_to_db.rb:57` which seems to be a bottleneck.  Suggest you focus there if you haven't already tracked down the problem.

**Comment by jalberto** [comment]
@mperham thanks for your help.

The issue was related to Azure DB service, after couple of weeks they literally "enabled Feature in your region" and now it works as expected.

So anyone using Azure PosgresDB service can find this useful.
