### ISSUE TITLE
Reliability feature - monitoring local queue size

### ISSUE THREAD

**Issue by dmydlarz** [mperham/sidekiq#3564]
Ruby version: 2.1.2
Sidekiq / Pro / Enterprise version(s): Pro

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
```Gemfile.lock
    sidekiq (4.2.10)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-pro (3.5.1)
      sidekiq (>= 4.1.5)
```

Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

---
How can I check local queue size that is introduced with *Reliability Features* from *Pro* version https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Client?
I would like to monitor it, and set alerts, etc.

**Comment by dmydlarz** [comment]
Ok, I have found it with:
```ruby
Sidekiq::Client.new.local_queue.size
```

It could be included in documentation.

**Comment by mperham** [comment]
You're the first person to ever ask about it.  Generally I don't document something unless multiple people have asked or else the wiki would be clogged with irrelevant detail to most users.  Glad you tracked it down.
