### ISSUE TITLE
Getting this on production enviroment - no implicit conversion of Symbol into String file: utils.rb location: + line: 284

### ISSUE THREAD

**Issue by steamboy** [mperham/sidekiq#3567]
When I run sidekiq web, i get the error below

*no implicit conversion of Symbol into String on /home/deployer/apps/learntalkapp/shared/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/utils.rb:284:in `+'*

`BACKTRACE
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/utils.rb in +
        domain  = "; domain="  + value[:domain]       if value[:domain]
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/utils.rb in set_cookie_header!
        domain  = "; domain="  + value[:domain]       if value[:domain]
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in set_cookie
            Utils.set_cookie_header!(headers, @key, cookie)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in commit_session
            set_cookie(env, headers, cookie.merge!(options))
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in context
          commit_session(env, status, headers, body)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in call
          context(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/nulllogger.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/head.rb in call
    status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/base.rb in call
      result, callback = app.call(env), env['async.callback']
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/base.rb in call
      @stack.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/base.rb in block in call
        synchronize { prototype.call(env) }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/base.rb in synchronize
          yield
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/sinatra-1.4.7/lib/sinatra/base.rb in call
        synchronize { prototype.call(env) }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb in serve
            @app.call req.env
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb in block in serve
          status, headers, body = route.app.serve(req)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb in each
        find_routes(req).each do |match, parameters, route|
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb in serve
        find_routes(req).each do |match, parameters, route|
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb in call
        @router.serve(req)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/omniauth-1.3.1/lib/omniauth/strategy.rb in call!
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/omniauth-1.3.1/lib/omniauth/strategy.rb in call
      dup.call!(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/rack/agent_hooks.rb in traced_call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/rack/browser_monitoring.rb in traced_call
      result = @app.call(env)   # [status, headers, response]
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/warden-1.2.7/lib/warden/manager.rb in block in call
        @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/warden-1.2.7/lib/warden/manager.rb in catch
      result = catch(:warden) do
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/warden-1.2.7/lib/warden/manager.rb in call
      result = catch(:warden) do
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/etag.rb in call
      status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/conditionalget.rb in call
        status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-user_agent-0.5.2/lib/rack/user_agent.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/head.rb in call
    status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/remotipart-1.3.1/lib/remotipart/middleware.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in context
          status, headers, body = app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/session/abstract/id.rb in call
          context(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb in call
      status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activerecord-4.2.1/lib/active_record/query_cache.rb in call
      response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb in call
        response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb in block in call
          @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/callbacks.rb in _run_callbacks
        block.call if block
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/callbacks.rb in _run_call_callbacks
              _run_callbacks(_#{name}_callbacks, &block)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/callbacks.rb in run_callbacks
      send "_run_#{kind}_callbacks", &block
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb in call
      result = run_callbacks :call do
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/raygun4ruby-1.1.9/lib/raygun/middleware/rails_insert_affected_user.rb in call
        response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/raygun4ruby-1.1.9/lib/raygun/middleware/rack_exception_interceptor.rb in call
        response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb in call
      _, headers, body = response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/rack/logger.rb in call_app
        resp = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/rack/logger.rb in block in call
          logger.tagged(compute_tags(request)) { call_app(request, env) }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb in block in tagged
      formatter.tagged(*tags) { yield self }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb in tagged
        yield self
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb in tagged
      formatter.tagged(*tags) { yield self }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/rack/logger.rb in call
          logger.tagged(compute_tags(request)) { call_app(request, env) }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/request_store-1.3.2/lib/request_store/middleware.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb in call
      @app.call(env).tap { |_status, headers, _body| headers["X-Request-Id"] = env["action_dispatch.request_id"] }
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/methodoverride.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/runtime.rb in call
      status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb in call
            response = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb in call
      @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/sendfile.rb in call
      status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb in call
      @app.call(sanitize(env))
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/engine.rb in call
      app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/application.rb in call
      super(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/newrelic_rpm-3.18.1.330/lib/new_relic/agent/instrumentation/middleware_tracing.rb in call
            result = (target == self) ? traced_call(env) : target.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/content_length.rb in call
      status, headers, body = @app.call(env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/connection.rb in block in pre_process
        response = @app.call(@request.env)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/connection.rb in catch
      catch(:async) do
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/connection.rb in pre_process
      catch(:async) do
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/connection.rb in process
        post_process(pre_process)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/connection.rb in receive_data
      process if @request.parse(data)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/eventmachine-1.0.9.1/lib/eventmachine.rb in run_machine
          run_machine
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/eventmachine-1.0.9.1/lib/eventmachine.rb in run
          run_machine
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/backends/base.rb in start
          EventMachine.run(&starter)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/thin-1.5.1/lib/thin/server.rb in start
      @backend.start
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/handler/thin.rb in run
        server.start
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/rack-1.6.8/lib/rack/server.rb in start
      server.run wrapped_app, options, &blk
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands/server.rb in start
      super
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb in block in server
        server.start
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb in tap
      Rails::Server.new.tap do |server|
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb in server
      Rails::Server.new.tap do |server|
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb in run_command!
        send(command)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/railties-4.2.1/lib/rails/commands.rb in <top (required)>
Rails::CommandsTasks.new(ARGV).run_command!(command)
/vagrant/learntalk/bin/rails in require
require 'rails/commands'
/vagrant/learntalk/bin/rails in <top (required)>
require 'rails/commands'
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/client/rails.rb in load
          load Dir.glob(Spring.application_root_path.join("{bin,script}/rails")).first
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/client/rails.rb in call
          load Dir.glob(Spring.application_root_path.join("{bin,script}/rails")).first
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/client/command.rb in call
        new(args).call
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/client.rb in run
      command_for(args.first).call(args)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/bin/spring in <top (required)>
Spring::Client.run(ARGV)
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/binstub.rb in load
    load bin_path
/home/vagrant/.rvm/gems/ruby-2.3.1@learntalk/gems/spring-1.7.1/lib/spring/binstub.rb in <top (required)>
    load bin_path
/vagrant/learntalk/bin/spring in require
    require 'spring/binstub'
/vagrant/learntalk/bin/spring in <top (required)>
    require 'spring/binstub'
bin/rails in load
  load File.expand_path('../spring', __FILE__)
bin/rails in <main>
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)`

Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.1.4

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
Something to do with Rack and cookie parsing from the looks of it.  Not a Sidekiq issue but try upgrading to a recent version and see if it works better.
