### ISSUE TITLE
Wiki claims exponential backoff, but it's really a quartic backoff

### ISSUE THREAD

**Issue by JordanVerasamy** [mperham/sidekiq#3569]
`(retry_count ** 4) + 15 + (rand(30) * (retry_count + 1))`

[This page](https://github.com/mperham/sidekiq/wiki/Error-Handling) claims that this is the logic for the exponential backoff timing for retries.

This looks to me like a quartic function of `retry_count`, not an exponential one.

Am I missing something? I'm not a Sidekiq expert so I might just be wrong.

**Comment by mperham** [comment]
🤷‍♂️

**Comment by victormours** [comment]
It is indeed a quartic (or polynomial) backoff which is different from an exponential backoff (https://en.wikipedia.org/wiki/Exponential_backoff).

After a few retries, the difference between retrying after `retry_count**4` seconds (quarctic) or `4**retry_count` seconds (actually exponential) is pretty big.

However, having a quartic backoff is not a bad strategy : sidekiq's 25 retries in about 20 days is pretty good (https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry).

But it's not the accurate name for this strategy, and it's confusing to get polynomial backoff when we're expecting exponential.

What's weirder is that this naming error seems to be in most major Ruby libraries : I found it in ActiveJob (https://github.com/rails/rails/pull/25991/commits/0be5d5d4c4c26d28fd1f39496a7a88d208afff13#diff-c017408d8f8e9b0a914da28fdcebc291c5fba624174fb9ca5bec3b4fc1c61d51R97) and in Delayed Jobs (https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/backend/base.rb#L110), which both have quartic backoff but call it exponential.

Maybe just changing the naming in the documentation could be less confusing? The term "quartic" isn't used very often, and i feel like "polynomial" is more common (and gives the same amount of information).

Or maybe I've missed something, and the ruby community has actually proved that P=NP ! 🎉 Go team!

**Comment by JordanVerasamy** [comment]
Thank you so much for [fixing this in Rails](https://github.com/rails/rails/pull/49292) @victormours! I appreciate you a lot, especially after Mike's frankly disappointing response :)
