### ISSUE TITLE
Sidekiq Pro stores very long error messages for batches

### ISSUE THREAD

**Issue by abezzub** [mperham/sidekiq#3570]
Ruby version: ruby 2.4.1p111
Sidekiq / Pro / Enterprise version(s): Sidekiq (4.2.10), Sidekiq Pro (3.4.5)

Our app ran some bad jobs using sidekiq batches. Job produced an error with very long error message, individual error message was around 8Mb (PG query had out of memory error and included full content of the query). Sidekiq stored full content of the message in Redis hash (it is used on `/sidekiq/batches/id` page). After enough errors happened Redis instance ran out of memory and started to discard all jobs. 

Ideally Sidekiq should trim bad error messages and not pollute Redis.

**Comment by mikegee** [comment]
We ran into this with the regular job (non-batch) error messages a few years ago. 

I suggested a configurable error message truncation (to retain the existing behavior by default):
https://github.com/mperham/sidekiq/pull/1843

@mperham decided to truncate all long error messages instead:
https://github.com/mperham/sidekiq/commit/840c8f6e1622ae3a8236fcc34b0f102c15b60b11
