### ISSUE TITLE
Testing: infinite loop in Sidekiq::Worker.drain_all

### ISSUE THREAD

**Issue by mcclymont** [mperham/sidekiq#3571]
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s): >= 4.0.2
Seems to be introduced by https://github.com/mperham/sidekiq/commit/ed55232a78aa551f3580bce658a03c8e8814966b

In testing.rb, there are 2 hashes keeping track of jobs. One keyed by queue name and one keyed by worker class name. Thus there are certain methods which must be called when accessing or modifying these collections of jobs, otherwise they can get into a bad state where they don't match. 

Using these interfaces yield the correct result, where both the jobs_by_queue and jobs_by_worker are updated:
* Sidekiq::Worker.clear_all
* Queues.clear_all
* SpecificWorker.clear

However when using ```SpecificWorker.jobs.clear``` as shown in the Wiki https://github.com/mperham/sidekiq/wiki/Testing, the jobs_by_worker class is emptied directly (as we are calling only Array#clear) and jobs_by_queue is left untouched.

In this case (if there were any jobs queued), SidekiqWorker.drain_all runs in an infinite loop as it checks whether jobs are still in jobs_by_queue, while draining them based on jobs_by_worker.

My fork adds a spec which shows the problem, as well as a possible solution (that is probably not the best solution). I think the Wiki just needs to be updated to not use .jobs.clear as an example.
https://github.com/mperham/sidekiq/compare/master...mcclymont:drain_all-infinite-loop?expand=1

**Comment by mperham** [comment]
Seems like clear should change both structures, not just jobs_by_worker.

**Comment by mperham** [comment]
Oh I see. Hmmmm.

**Comment by mperham** [comment]
No plans to fix.  You are welcome to update the wiki.
