### ISSUE TITLE
Cleanup old unused limit keys

### ISSUE THREAD

**Issue by juandazapata** [mperham/sidekiq#3577]
Ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859)
Sidekiq / Pro / Enterprise version(s): Enterprise

We're experimenting with rate limits, and I was wondering how can we cleanup old limit keys that are not being used anymore (see image below).

Is there a command to do so? I couldn't find any in the docs

![_development__sidekiq_enterprise](https://user-images.githubusercontent.com/145506/29334096-e17d3ac6-81cb-11e7-9cea-9e6d031fda44.png)

**Comment by mperham** [comment]
You need to set the TTL for the limiter.

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#ttl
