### ISSUE TITLE
Reporting of Redis exceptions with Sidekiq Pro's reliable_push!

### ISSUE THREAD

**Issue by marionzualo** [mperham/sidekiq#3578]
Hi,

Thanks for making sidekiq.

Sidekiq Pro's (v 3.4.3) [reliable_push!](https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Client) is swallowing Redis exceptions in order to enqueue locally the job for delivery once the the issues have been resolved.

It is understandable that the feature works like this but I wonder if there would be a way to get notifications of the swallowed errors? Basically, we'd have a way to make sure that those errors get to an exception notification service.

Example pseudocode:
```
def current_reliable_push(job)
  push_to_redis(job)
rescue Redis::BaseError => ex
  enqueue_locally(job)
end

def desired_reliable_push(job)
  push_to_redis(job)
rescue Redis::BaseError => ex
  ExceptionTracker.notify(ex) # example: bugsnag, rollbar, etc
  enqueue_locally(job)
end
```

Naturally we can't add `ExceptionTracker.notify(ex)` to the gems code, but I wonder if a sort of Observer pattern could be developed in case the gem's users wish to plug into this behaviour.

This is super helpful in order to monitor spikes in Redis errors when placing jobs into the queue. reliable_push behaves well if there is a minor network hiccup but if the Redis instance is unavailable for a longer period of time we'd like to be aware of that through exceptions at the application level.

What do you think?

**Comment by mperham** [comment]
I designed it this way because I didn't want Redis errors to DDOS your error service if Sidekiq is under heavy load.  I guess an observer would be opt-in but the first improvement people will ask for is a way to rate limit the notification.

**Comment by marionzualo** [comment]
I think that is a fair concern. 

Though in case such a feature would be used for exception notification services, that issue would be mitigated by the exception notification service. Since some services have [throttling](https://docs.bugsnag.com/product/plans-and-billing/#event-usage-amp-throttling) procedures in place.

I don't have any suggestions on how to best deal with it.

**Comment by mperham** [comment]
If your Redis is misbehaving, you'll hear about exceptions from the Sidekiq processes.  After some thought I don't think sending client exceptions is really necessary.

**Comment by marionzualo** [comment]
Sure. That is a fair conclusion. Thanks for taking the time to think about this. I will close the issue.
