### ISSUE TITLE
The jobs statuses list without worker/jid or arguments

### ISSUE THREAD

**Issue by Morxander** [mperham/sidekiq#3579]
Ruby version: V2.3.1
Sidekiq : V5.0.4

I have a Ruby on Rails App uses Sidekiq and it was working fine until today, I found the current running jobs without a worker/jid or arguments.

![screenshot](http://i.imgur.com/a2hlSRt.png)

And till now all the new jobs have the same issue, the jobs are working fine but in the status page they are without a worker/jid or args.
I tried to restart the Rails App but the problem still there.

**Comment by mperham** [comment]
That's a 3rd party extension, I don't support it. Please open an issue in its repo.

**Comment by Morxander** [comment]
Sorry my mistake I didn't notice that the app is using a 3rd party extension for this page.
