### ISSUE TITLE
How to customize Sidekiq Web UI? 

### ISSUE THREAD

**Issue by axiom88-guru** [mperham/sidekiq#3582]
I'm using sidekiq Pro and usually monitor my workers' process on their Web UI. Whenever there's an Error, the task is moved to Retries tab where the queue name and an error messsage are displayed. The thing is I would like to add data to this message (specifically class name and line number), but i havent found information about this anywhere. Is it possible to edit/configure the Web UI display? If that's so, how?

**Comment by mperham** [comment]
It's not possible to change the existing web ui pages without editing the erb files directly.  You could fork the erb file, add your content and then ensure it is in front of the path for the Web UI's erb file lookup.  Unfortunately this process isn't documented.

**Comment by axiom88-guru** [comment]
Hi, I am using ActiveJob to perform a mailer job . 
Just read another post : https://github.com/mperham/sidekiq/issues/3324
SomeWorker.set(customer_key: "acmecorp").perform_async(args)
It seems pretty possible but since I use ActiveJob instead of using Worker, I am not sure how to do it .
jobinstance = NotificationMailerJob.set(wait_until: remind_time, event).perform_later(event,user)
Here is the script , the only thing I want to do is to add event.name next to job or arguments column. 
Any help would be appreciated.
 
On 8/22/2017 10:41:38 AM, Mike Perham <notifications@github.com> wrote:
It's not possible to change the existing web ui pages without editing the erb files directly. You could fork the erb file, add your content and then ensure it is in front of the path for the Web UI's erb file lookup. Unfortunately this process isn't documented.

**Comment by axiom88-guru** [comment]
Quick question, If I bought SidekiqPro version, would you have provided  the way to customize web UI?

**Comment by mperham** [comment]
You previously said you are using Sidekiq Pro so you don't need to buy it.

I always consider feature requests -- you can open a request with your use case and I'll consider it but Sidekiq's recommendation has always been to use a real error service.  The Web UI is not meant to replace something like Honeybadger, Bugsnag, Sentry, etc.
