### ISSUE TITLE
Concurrency Setup and AR Database Pool Bottleneck

### ISSUE THREAD

**Issue by ThomasSertorio** [mperham/sidekiq#3584]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 4.2.7

Each night, I have to process around 50k Background Jobs, each taking an average of 60s. Those jobs are basically calling the Facebook, Instagram and Twitter APIs to collect users' posts and save them in my DB. The jobs are processed by sidekiq.

At first, my setup was:
- `:concurrency: 5` in `sidekiq.yml`
- `pool: 5` in my `database.yml`
- RAILS_MAX_THREADS set to 5 in my Web Server (puma) configuration.

My understanding is that my sidekiq process will use 5 threads (as the concurrency is set to 5), which is also OK as the connection pool is set to 5.

In order to process more jobs in the same time and reducing the global time to process all my jobs, I decided to increase the sidekiq concurrency to 25. In Production, I provisionned a Heroku Postgres Standard Database with a maximum connection of 120 an upgrade my Redis Store, to be sure I will be able to use Sidekiq concurrency. Thus, now the setup is:
- `:concurrency: 25` in `sidekiq.yml`
- `pool: 25` in my `database.yml`
- RAILS_MAX_THREADS set to 5 in my Web Server (puma) configuration.

I can see that 25 sidekiq workers are working but each Job is taking way more time (sometimes more than 40 minutes instead of 1 minute) ?

So I am wondering: is my understanding of the rails database.yml connection pool and sidekiq concurrency right ?

**Comment by mperham** [comment]
Yes.  There's no way to tell what is causing the slowdown; good performance at 5 but bad performance at 25 can happen if those 25 threads just overload the server.  You may have an unoptimized query, etc.  No way for us to tell; you need to profile and debug it.
