### ISSUE TITLE
Activate the unique job feature just for one worker!

### ISSUE THREAD

**Issue by Mardiniii** [mperham/sidekiq#3585]
Ruby version: `ruby 2.2.4`
Sidekiq / Pro / Enterprise version(s):

```
*** LOCAL GEMS ***

rspec-sidekiq (2.2.0)
sidekiq (4.2.10, 3.3.4)
sidekiq-datadog (0.3.5)
sidekiq-ent (1.6.0)
sidekiq-limit_fetch (2.4.2)
```

Hi, we are using Sidekiq Enterprise to implement The unique jobs feature for one of our workers. After adding the line below to our initializer I have a couple of questions: 

```ruby
# Disable uniqueness in testing, this has the potential to cause much head scratching...
Sidekiq::Enterprise.unique! unless Rails.env.test?
```

1. This means we are making all of our jobs unique?
2. In case the answer to the question above will be true, How can I/we add this feature for specific workers without affecting the normal behavior of the others in our application?.

**Comment by mperham** [comment]
1. No
2. Workers are not unique unless you add the unique_for attribute.  The feature will do nothing without that element.

**Comment by Mardiniii** [comment]
Nice, thanks for your answer @mperham
