### ISSUE TITLE
Jobs of child batches that have an error do not increment failures count in parent batch status.

### ISSUE THREAD

**Issue by meenie** [mperham/sidekiq#3586]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 4.1.0 / 3.3.1 / 1.2.2

Going off the example provided on the wiki called ["Really Complex Workflows with Batches"](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches), if any of the jobs `A`, `B`, etc have an error, that failure does not propagate up to the parent batch.  It's `on_complete` callback is called and `status.failures` still equals 0.

I've looked in the changelogs and I don't see anything mentioning a fix for this issue.

**Comment by mperham** [comment]
Yeah, that's expected behavior.  on_complete is called when all jobs have been executed, not necessarily successfully, including child batches.

**Comment by meenie** [comment]
Yes, I expect it would.  The problem is the overall batch (in the above example) doesn't have the failures registered.  I'm wondering if I'm going to have to use redis to register those errors in the child batch `on_complete` and check it in the parent batch `on_complete`?

**Comment by mperham** [comment]
I'm not sure I understand, maybe I need more detail.  The errors are registered on the child batch.  If you don't want the parent to do something until all children are error-free, use on_success.

**Comment by meenie** [comment]
I think I may have misunderstood how everything fit together with your "Really Complex" example.  The parent batch runs a job which sets up a child batch that also runs jobs.  Technically the child batch finished without issue, which is why the parent batch has no errors registered.  The jobs of the child batch have an error, so that is registered with the child batch and does not propagate up to the parent batch.

I will close this now.  Thank you for your time.
