### ISSUE TITLE
Documentation request: Better documentation for Middlewares

### ISSUE THREAD

**Issue by IvanDelsinne** [mperham/sidekiq#3587]
I've been fiddling around with the Middlewares to try to implement a "before" and an "after" middleware and I was only able to set up one after a lot of retries.

The "before" midddleware is the one documented, even if it's not explicitly called "Before" but the "after" version isn't and since the chain order change for the After one, it can be confusing and considered as an unknown behaviour.

For a test code, you can use [this one](https://paste.artemix.xyz/v/dYnuG7kame3lI7lVP6Nud4BiuPUwIxiZ/dOBgUl56hjJg7eLC3ahCK5XGz0nlKBJa).

On the test code I gave, even if the chain config in sidekiq `server_middleware` is in the A1A2A3 order, they are executed as A3A2A1 and this behaviour isn't documented and can be confusing.

**Comment by mperham** [comment]
That's how function chaining and a call stack works.  I'm glad you figured it out but I don't think it's the responsibility of Sidekiq's wiki to teach code flow patterns.  I don't want the docs to be overloaded with unnecessary detail.
