### ISSUE TITLE
Special characters in password failed sidekiq for connecting redis when using url in redis options

### ISSUE THREAD

**Issue by xtremerui** [mperham/sidekiq#3589]
Hi when using sidekiq connecting to redis we found sidekiq has trouble to do auth IF config.redis is set to use `url` AND the password has special characters.

Logs from working example:
```
Booting Sidekiq 5.0.4 with redis options {:host=>"192.168.0.11", :port=>6379, :password=>"REDACTED", :namespace=>"some-name", :id=>"Sidekiq-server-PID-44", :url=>nil}
...
```

Logs from failing example:
```
Booting Sidekiq 5.0.4 with redis options {:url=>"redis://:REDACTED@192.168.0.11:6379/0", :namespace=>"some-name", :id=>"Sidekiq-server-PID-45"}
...
ERR invalid password
```
The masked password is: ` vyP0qkA4PsuA+3Ea1+h9u8v0zRU=`

If using a simple password like `randompassword`, both redis options works.

Ruby version: 2.3.4
Sidekiq / Pro / Enterprise version(s): 5.0.4

**Comment by mperham** [comment]
You are not constructing the URL legally.

> require 'cgi'
> CGI.unescape("vyP0qkA4PsuA+3Ea1+h9u8v0zRU=")
=> "vyP0qkA4PsuA 3Ea1 h9u8v0zRU="

https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L411
