### ISSUE TITLE
Put job to dead jobs during the job process flow

### ISSUE THREAD

**Issue by IvanDelsinne** [mperham/sidekiq#3591]
I'd want to be able to kill (abort without any retry) a job if the passed arguments it received are invalid (arguments validation).

As far as I've seen in the documentation, there is no way to either cancel or kill a job during its process time, except by directly tinkering associated Redis data.

The goal for this is to avoid having massive retries until the max retry count is reached, thus avoiding polluting the Redis storage for pending jobs.

Also, a constraint to add is that I should be able to catch when a job is killed/aborted to be able to send a notification. "Natural" reached retry-count is achieved with the `sidekiq_retries_exhausted` method, so when killed/aborted, it should pass by such a callback.

I've been trying multiple solutions, including the [Sidekiq-status](https://github.com/utgarda/sidekiq-status) extension but haven't managed to do so.

**Comment by mperham** [comment]
There's no way to do most of this.  The API does have a `Sidekiq::Job#kill` method but the retry/dead process is not designed for people to special case.

It would help if you'd tell us your use case/problem rather than asking us how to implement a solution.

**Comment by IvanDelsinne** [comment]
I gave a case but I'll explain it a bit better:

When starting to process jobs, we retrieve a payload from a remote API, which is encoded in JSON.

We want to decode this payload and, if unable to decode, or if something's missing (thus the payload being invalid), to abort the job and send an email to the support, since invalid payload means that somewhere, something's generating broken data.

Since cancel and kill was found in most other solutions, I assumed there was something here, but couldn't find it. Also, for the Sidekiq::Job#kill method, I wasn't able to find it until you put it in your answer.

Without having to manually tweak the Redis storage, do you have any way to actually implement such an "abort" method that wouldn't go against the Queue system as it was designed ?

**Comment by mperham** [comment]
I think you are mistaking Sidekiq's job failure process, which is designed to handle accidental developer bugs, with data validation, which is normal and part of every business application where you are accepting data from an external system you don't control.

Your job's perform method should parse the JSON argument and process the result or send email if there's a problem.  In both cases, the job was successfully processed from Sidekiq's POV.
