### ISSUE TITLE
Periodic Jobs - define inside a worker

### ISSUE THREAD

**Issue by dorongutman** [mperham/sidekiq#3594]
[According to the wiki](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#definition), the definition of a periodic job is done as part of the initializer of the server of sidekiq.

Is there a way to define the cron schedule of a worker inside the worker file (for example as a sibling to the `sidekiq_options` property) ?

**Comment by mperham** [comment]
None that I'm aware of.

**Comment by mikegee** [comment]
Perhaps `Sidekiq.configure_server` can be called more than once and the configs will be merged?
If so, I'd suggest that your initializer explicitly `require` your periodic workers in which you reconfigure the server to define their schedule. It should be straightforward to verify or refute.

**Comment by mperham** [comment]
The periodic method is not implemented to merge schedules like you say.  I wouldn't advise such a thing.  The idea behind the design is to have a single point where all your periodic schedules are defined, not spread across dozens of *_worker.rb, akin to crontab.
