### ISSUE TITLE
Redis 4

### ISSUE THREAD

**Issue by DemidenkoAndrey** [mperham/sidekiq#3595]
Will you update dependency to allow use gem redis version 4?https://github.com/mperham/sidekiq/blob/master/sidekiq.gemspec#L20

**Comment by mperham** [comment]
Happy to.  Want to send me a PR to allow 3.3.3 or greater?

**Comment by DemidenkoAndrey** [comment]
@mrerham  I will send a PR as soon as [redis-namespace ](https://github.com/resque/redis-namespace/blob/master/redis-namespace.gemspec#L21)will update their dependency

**Comment by kirkelifson** [comment]
@DemidenkoAndrey dependency updated in https://github.com/resque/redis-namespace/commit/9cb81bfb3d76f26e63475beac2d23ce1ba7b896f

**Comment by bodrovis** [comment]
https://github.com/resque/redis-namespace/issues/139

**Comment by mperham** [comment]
#3617
