### ISSUE TITLE
[Question] Dedicated worker servers vs More App Servers

### ISSUE THREAD

**Issue by allaire** [mperham/sidekiq#3598]
Is it recommended to have dedicated worker servers (Rails codebase w/ Sidekiq) not attached to our Load Balancer instead of running it within our app servers? We're wondering if we should bump the specs of our app servers, or move Sidekiq to its own servers (we're guilty of un-optimized workers).

_Note: Initially asked on Twitter, @mperham told me to open an issue to leave a trace and because 140 chars is not enough for the answer._

**Comment by ryansch** [comment]
I can tell you what we do.  We run sidekiq as a backend service in two different configurations to work on different queues.  We have far more resources for our sidekiq containers than we do for the rails containers that are connected to our load balancers.  We strive to get our frontend to respond as quickly as possible so it can serve a lot more traffic on few resources.

**Comment by mperham** [comment]
Network architecture is situation-dependent.  I worked at a corp with a big monolith.  We didn't need to autoscale and kept our app servers identical, with pumas and sidekiqs, which made deploys simple.

OTOH, if your system needs resource scaling, it's easier to treat the webs and workers as two separate clusters and scale them individually.

I'm a big fan of optimizing things for the resources you have.  Modern machines, especially physical hardware, are often way more powerful than apps need and a little hunting for low hanging fruit can lead to 5-10x performance leaps.  You'll learn a lot about your stack and app as you profile and get a sense for where the CPU time is going in your codebase.  The knowledge gained can help a ton when you have production issues that need quick debugging.
