### ISSUE TITLE
Sidekiq::Sidekiq::Client enforces args must be an array but job is processed anyway if queued manually 

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3599]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 5.0.4

A few weeks back I submitted a bug where occasionally the sidekiq web interface would fail with 

    #<NoMethodError: undefined method `map' for #<String:0x007f370b92f1a0>>

In sidekiq-web.log

Wasn't a big deal but I decided to do some more digging today since I finally found a way to easily reproduce the problem.

We have scenarios where we need to queue into redis via PHP or some other language where we don't have access to the Sidekiq gem natively to use `Sidekiq::Client.new` or `.perform_async`.

When I try to do this

`Sidekiq::Client.new.push('queue' => 'default', 'class' => "CopyImageWorker", 'args' => msg.to_json)` 

I get the error that the args element must be an array. Totally makes sense given that's how it's enqueued when using `perform_async`.

When we enqueue using our PHP api for instance the job looks like this in redis

`"{\"args\":\"{\\\"url\\\":\\\"https:\\\\\\/\\\\\\/pbs.twimg.com\\\\\\/profile_images\\\\\\/892058915801673728\\\\\\/HK5hNhVK_normal.jpg\\\",\\\"key\\\":\\\"profile_images\\\\\\/892058915801673728\\\\\\/HK5hNhVK_normal.jpg\\\"}\",\"class\":\"CopyImageWorker\",\"enqueued_at\":1504734336.3684,\"jid\":\"04d4794a5be4\",\"retry\":false}"`

Proof of the job running fine:

```
2017-09-06T21:46:54.822Z 9515 TID-ox61f1yoc CopyImageWorker JID-04d4794a5be4 INFO: start
2017-09-06T21:46:54.886Z 9515 TID-ox61f1yoc CopyImageWorker JID-04d4794a5be4 INFO:
 {"url":"https:\/\/pbs.twimg.com\/profile_images\/892058915801673728\/HK5hNhVK_normal.jpg","key":"profile_images\/892058915801673728\/HK5hNhVK_normal.jpg"}
```

The sidekiq web seems to be expecting an array for the args and using map to prepare the data for the UI.

Not sure what the fix would actually be here, just a slight inconsistency probably for BC sake?

**Comment by mperham** [comment]
The PHP should be fixed to create the job payload in the correct format:

```
{ "args": [1, 2, 3] }
```

It's quite possible that Sidekiq can be improved to handle more and more edge cases but this is a very rare bug so I'm unlikely to want to gracefully handle it.  Sometimes bad data should cause pain so it is fixed upstream.  Reasonable?

**Comment by bobber205** [comment]
Oh absolutely. I fixed the PHP issue shortly after this was submitted.
Just seems weird it'll run the job just fine it just fails to display in the web UI

**Comment by mperham** [comment]
Yeah, understood.  That's a random implementation quirk, technically it's invalid but I guess the execution codepath happens to work.
