### ISSUE TITLE
"ERROR: Unable to remove job from private queue!" with SuperFetch

### ISSUE THREAD

**Issue by agelwarg** [mperham/sidekiq#3601]
We are trying to trace down an issue -- when using SuperFetch, we are periodically getting the following error:

`ERROR: Unable to remove job from private queue!`

From the source code, this looks to be that a call to Redis `conn.lrem` is expecting there to be a job that is no longer there.  Separately but possibly related, we are seeing other log messages such as:

`Moving job from queue:sq_5787def964f8:35379:ea53e23c3cf7_default back to queue:default`

...but we don't know if they're related as the timestamps don't necessarily match up close enough.

Has anyone seen anything like this before?

Ruby:
  * ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

Relevant Gems:
  * sidekiq (4.2.10)
  * sidekiq-ent (1.5.2)
  * sidekiq-pro (3.4.5)
  * redis (3.3.1)
  * activesupport (2.3.18)

Redis server is:
  * docker.io/redis:3.2.8-alpine

**Comment by mperham** [comment]
When you see this error, is anything else "interesting" happening at the same time?  Specifically I'm thinking of deploys / container restarts / etc.

**Comment by agelwarg** [comment]
Unfortunately, nothing we have been able to identify.  Definitely not any deployments.

**Comment by mperham** [comment]
Can you gist/post the output of `redis-cli info` against your production Redis instance?

**Comment by agelwarg** [comment]
```# Server
redis_version:3.2.8
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:32f2359aa7cbfaec
redis_mode:standalone
os:Linux 3.10.0-514.10.2.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:6.2.1
process_id:1
run_id:04203d8425fde151b5e37fb5af3224b98c6f311a
tcp_port:6379
uptime_in_seconds:927285
uptime_in_days:10
hz:10
lru_clock:11975881
executable:/data/redis-server
config_file:/redis.conf

# Clients
connected_clients:159
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:62909040
used_memory_human:59.99M
used_memory_rss:93458432
used_memory_rss_human:89.13M
used_memory_peak:108564464
used_memory_peak_human:103.54M
total_system_memory:101196345344
total_system_memory_human:94.25G
used_memory_lua:55296
used_memory_lua_human:54.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.49
mem_allocator:jemalloc-4.0.3

# Persistence
loading:0
rdb_changes_since_last_save:5850118
rdb_bgsave_in_progress:0
rdb_last_save_time:1505084830
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:22353
total_commands_processed:228696274
instantaneous_ops_per_sec:205
total_net_input_bytes:28638218915
total_net_output_bytes:1977335787274
instantaneous_input_kbps:34.63
instantaneous_output_kbps:40.96
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:15590
evicted_keys:0
keyspace_hits:56982819
keyspace_misses:172328
pubsub_channels:0
pubsub_patterns:32
latest_fork_usec:2182
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:7487.17
used_cpu_user:5097.93
used_cpu_sys_children:0.79
used_cpu_user_children:2.98

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=210,expires=66,avg_ttl=158508216
db1:keys=2,expires=0,avg_ttl=0```

**Comment by mperham** [comment]
> db0:keys=210,expires=66,avg_ttl=158508216

I've never seen a production keyspace that small, with only 210 keys.  Is it possible someone is running FLUSHDB or FLUSHALL on the instance???  That would definitely trigger the error message you are seeing.  Sidekiq is designed to run as small and efficient as possible so that might be normal but it's still really surprising.

**Comment by mperham** [comment]
Also, can you post your initializer and config/sidekiq.yml?
