### ISSUE TITLE
Error when `perform_async` is called multiple times on an instance of `Setter`

### ISSUE THREAD

**Issue by mvalipour** [mperham/sidekiq#3602]
### Why

As per [this line](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L49), `perform_async` of the `Setter` class, mutates the given options hash and then pass it on to the `client_push` method (which then further mutates it).

This is causing issue in my setup, where I memoise the result of the `set` method (the `Setter` instance) and any `perform_async` call after the first one given me the following error.

```
NoMethodError: undefined method `client_push' for "Materialist::EventWorker":String
```

This is due to the fact that the key `'class'` key of the `opts` is serialised when being executed in the `client_push` method.

### What

I know in various places in sidekiq, the preferred approach has been to mutate hash arguments (rather than cloning), but it feels like a bug that one would not be able to call `perform_async` on a `Worker.set(queue: :my_queue)` any more than once.

I would suggest changing `merge!` to `merge` to rectify this issue.

Thoughts?

**Comment by mperham** [comment]
I think I can fix this with some API refactoring.  I'm hoping to avoid the extra hash allocations.
