### ISSUE TITLE
Heroku and Quiet

### ISSUE THREAD

**Issue by delphaber** [mperham/sidekiq#3607]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 5.0.4 (free version)
Heroku stack: heroku-16

Please include your initializer and any error message with the full backtrace.

```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('SIDEKIQ_REDIS_URL'), namespace: ENV.fetch('SIDEKIQ_NAMESPACE'), network_timeout: 3 }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch('SIDEKIQ_REDIS_URL'), namespace: ENV.fetch('SIDEKIQ_NAMESPACE'), network_timeout: 3 }
end
```

Here ( https://github.com/mperham/sidekiq/wiki/Deployment#heroku ) I've read about the need to run `Sidekiq::ProcessSet.new.each(&:quiet!)` on Heroku before a deploy. Is this still true with Sidekiq 5 and current Heroku stack (heroku-16) ?

Thank you!

**Comment by mperham** [comment]
You don't **need** to run it, but it gives your jobs more than 8 seconds to finish.  Additionally, you can now increase the shutdown timeout to 25 on Heroku.  They recently increased their process timeout from 10 to 30.

```
bundle exec sidekiq -t 25
```

This gives your jobs 25 seconds to finish and Sidekiq 5 more seconds to force stop any outstanding jobs.

**Comment by delphaber** [comment]
Thank you!
