### ISSUE TITLE
Best practices for development mode with Sidekiq Pro?

### ISSUE THREAD

**Issue by LeeXGreen** [mperham/sidekiq#3608]
First off, thanks for the work you put in building and maintaining Sidekiq!

My organization recently purchased a Sidekiq Pro license -- reliability, metrics, and TTL are features that we need in staging / production environments.

Obviously, we'll run Sidekiq Pro in staging / production environments. However, for devs not actively working with Sidekiq, it seems like we'd rather not give them the one set of production credentials which allow for Pro usage. We trust our devs, obviously, but we'd like to minimize the possibility of a credential leak.

Are there best practices around this? Is there a way to fall back to "vanilla" Sidekiq if Pro credentials are not provided?

How will "vanilla" Sidekiq operate in dev mode if we make calls to Pro features? I think the ideal behavior would be that the Pro features simply don't activate, without raising NoMethodError or similar.

I haven't yet read the two codebases to see what would happen -- I thought I'd ask here first.

**Comment by mperham** [comment]
I'm not sure that's a realistic approach; it can lead to working code in dev breaking in staging/production or vice versa.  If you do want to proceed anyways:

Do this in Ruby:

```
if defined?(::Sidekiq::Pro)
  # activate some Pro feature
end
```

and this in your Gemfile:

```ruby
if Bundler.settings["gems.contribsys.com"]
  source ... do
    gem 'sidekiq-pro'
  end
end
```

That will disable gem access without established credentials.

**Comment by LeeXGreen** [comment]
Okay -- we're happy to run Pro everywhere; we'd rather not share credentials across the org.

Can you confirm that our Pro license allows for us to make the gem available on a local server? This server is only accessible to members of our organization.

**Comment by mperham** [comment]
Confirmed.  As long as you maintain a subscription, you may vendor and cache the gems locally.

**Comment by mperham** [comment]
@dhempy vendor the gems. They’re just Ruby.

**Comment by CiTroNaK** [comment]
Hi @LeeXGreen and @dhempy, you can use Gemstash to handle the credentials for Sidekiq Pro. I wrote a short [article](https://petr.codes/blog/ruby/gem-credentials-management-with-gemstash/) about it.
