### ISSUE TITLE
Can't access /sidekiq on rails app- 500(undefined method 'split')

### ISSUE THREAD

**Issue by brentluna** [mperham/sidekiq#3609]
Ruby version: 2.3.4
Rails 4.0.13
sidekiq 4.1.0
sidekiq-batch 0.1.3
sidekiq-hierarchy 2.1.0

----config/initializers/sidekiq.rb----
SIDEKIQ_NAMESPACE = "cureus-marketing-#{Rails.env}"

Sidekiq.configure_client do |config|
  config.redis = {namespace: SIDEKIQ_NAMESPACE}
  config.client_middleware do |chain|
    chain.add Sidekiq::Hierarchy::Client::Middleware
  end
end

Sidekiq.configure_server do |config|
  config.redis = {namespace: SIDEKIQ_NAMESPACE}
  config.client_middleware do |chain|
    chain.add Sidekiq::Hierarchy::Client::Middleware
  end
  config.server_middleware do |chain|
    chain.add Sidekiq::Hierarchy::Server::Middleware
  end

  database_url = ENV['DATABASE_URL']
  if database_url
    ENV['DATABASE_URL'] = "#{database_url}?pool=25"
    ActiveRecord::Base.establish_connection
  end
end

----Stacktrace----
Started GET "/sidekiq" for 127.0.0.1 at 2017-09-19 15:17:08 -0700
!! Unexpected error while processing request: undefined method `split' for nil:NilClass
----The  line below is returned if i try to refresh after the first spllit error, another refresh will return the split error again, and follow the same pattern-----
!! Unexpected error while processing request: deadlock; recursive locking

**Comment by mperham** [comment]
bundle up sidekiq

**Comment by brentluna** [comment]
@mperham do you mean `bundle update sidekiq` ? I did bundle update sidekiq, and got the following changes 

Updating files in vendor/cache
  * connection_pool-2.2.1.gem
  * redis-3.3.3.gem
  * sidekiq-4.2.10.gem

Still had same issue.

**Comment by mperham** [comment]
There's no way to know what's wrong without a backtrace.

**Comment by brentluna** [comment]
Yeah, that's the only thing I get in my log are the 2 lines in the OP, making it very difficult to find a solution.

**Comment by mperham** [comment]
You'll need to track down what code is eating the exception in your web stack.
