### ISSUE TITLE
Limit number of jobs sidekiq gets?

### ISSUE THREAD

**Issue by dare05** [mperham/sidekiq#3611]
I have a central Redis database and I want to run Sidekiq server processes on multiple computers that will get items to process from this database.

Here's the thing: This Redis database contains several million items. I don't want each Sidekiq process to 'download' a copy of each of the 1 mil items. I want to impose a limit, for eg, don't have more than 10k items in your 'to-do' list. I've tried to find such an option for Sidekiq but couldn't find anything.

**Comment by mperham** [comment]
Why do you think that each process will download all million elements?

**Comment by dare05** [comment]
@mperham I've watched your presentation and somehow confused the 'scheduled' tab in web UI meaning 'all items from Redis'. It seems this isn't the case.

**Comment by mperham** [comment]
The Scheduled/Retries/Dead tabs are all paginated.  They download only the data needed to show that page of elements.

I'm not sure the Queue page is paginated so be careful looking at a full queue in the Web UI.
