### ISSUE TITLE
Feature request: pull tasks in random order from queue

### ISSUE THREAD

**Issue by jbeyer05** [mperham/sidekiq#3614]
Feature request:

For a project that I'm working on, I would find it very useful to pull tasks randomly from the work queue.  The use case is that users request that work be completed.  That work is broken up into hundreds or thousands of tasks.  If the work queue operates strictly as a FIFO queue, the work requests that were submitted later see zero progress until the earlier requests are complete, and the user sees no progress on their request.  We have experimented with multiple weighted queues, but it is difficult to get a satisfactory solution.

Ideally, I could process X% of tasks in FIFO order, and Y% of tasks in random order.  That would allow for some progress on all jobs, while still prioritizing those placed into the queue first.

I haven't seen any way to do this.  If someone knows of a clever way to achieve this, please let me know.

**Comment by mperham** [comment]
There's no way to do this with Sidekiq and won't be as it's not needed by 95% of users.

**Comment by jbeyer05** [comment]
> There's no way to do this with Sidekiq

Is that due to a fundamental limitation with Redis?  If there is no fundamental limitation with Redis, I'd be happy to explore adding this functionality.
