### ISSUE TITLE
Pending Jobs wiped when sidekiq restarts

### ISSUE THREAD

**Issue by wordjelly** [mperham/sidekiq#3616]
Ruby version: 2.1.8p440 
Sidekiq : 3.2.5

I am using sidekiq with a single worker.

```
class OtpJob 
    include Sidekiq::Worker
    def perform(args)
        puts args.to_s
    end
end
```

I start sidekiq before starting rails by doing this on the command line:

```
bundle exec sidekiq -C ./sidekiq.yml
```
I then enqueue a job through the rails console:

```
OtpJob.perform_later(job_arguments)
```

After this I shutdown my workers, by killing the process in sidekiq.pid

I then enqueue another job , and through the sidekiq web UI i can see it as an 'enqueued' job.

If I subsequently restart the sidekiq workers. The enqueued jobs have disappeared, but they are never processed.

Is there any way to prevent this from happening?

```
sidekiq.yml:

---
:concurrency: 25
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - [high_priority, 2]
:daemon: true

```

**Comment by mperham** [comment]
You are using an ancient version of Sidekiq.  I'd strongly recommend an upgrade.

You haven't told me how you are shutting down Sidekiq but I suspect it isn't getting enough time to shutdown properly, causing the jobs to be lost.  Please read:

https://github.com/mperham/sidekiq/wiki/Deployment#overview

It's also possible that you aren't stopping the process correctly and an old process is pulling the enqueued job.
