### ISSUE TITLE
Batch does not execute callback right after finish all jobs

### ISSUE THREAD

**Issue by aaroalan** [mperham/sidekiq#3619]
Ruby version: 2.3.1
Sideiq Pro

Initializer
```rb
batch = Sidekiq::Batch.new
batch.description = description
batch.on(:success, PostBatchHelper, message_id: id)
batch
```
Sidekiq command: `bundle exec sidekiq -C config/sidekiq-file-worker.yml -c 1 `

Versions: `sidekiq-pro sidekiq-pro (3.4.5)`, `sidekiq (4.2.10)`

I sent a http notification when a batch starts and when it success, first batch finishes all the jobs but it does not execute the callback until the second batch finishes so I get both notifications at the same time even if first batch finishes before start the second one.

This is the complete log, I replace the http request for a `puts **********...` to have more visibility and you can see that both batches finish at the same time in the log.
[sample.log](https://github.com/mperham/sidekiq/files/1349560/sample.log)

Also this is a video where you can see the sidekiq dashboard, first batch finishes all jobs but still in page until second one finishes.
[errorVideo.zip](https://github.com/mperham/sidekiq/files/1349562/errorVideo.zip)

Thanks

**Comment by mperham** [comment]
If you put all the jobs in the same queue, those jobs will be processed in order.  Callbacks are jobs like any other.  You can set `batch.callback_queue = :critical` to increase their priority, for example.
