### ISSUE TITLE
Sidekiq::Job#display_args mutates args

### ISSUE THREAD

**Issue by rmachielse** [mperham/sidekiq#3620]
Ruby version: 2.4.2
Sidekiq version: 5.0.4
Rails version: 5.1.4

When retrieving the job through the sidekiq api, the `Sidekiq::Job#display_args` method seems to mutate the original `args` on the object.

For example when assembling a job object from it's item hash:

```ruby
job = Sidekiq::Job.new(item)
job.args
# => ["---\n- !ruby/class 'UserMailer'\n- :notify\n- - f06a3873-3dd8-424a-bbf1-b0eddd7d9aa3\n"]
job.display_args
# => ["f06a3873-3dd8-424a-bbf1-b0eddd7d9aa3"]
job.args
# => ["f06a3873-3dd8-424a-bbf1-b0eddd7d9aa3"]
```

The original `args` are now replaced by the outcome of `display_args`.
This causes for example `display_class` to fail, when called after `display_args`:

```ruby
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.4.2/gems/sidekiq-5.0.4/lib/sidekiq/api.rb:327:in `display_class'
```

**Comment by mperham** [comment]
Happy to get a PR to fix this but note that this method was written for Web UI usage, the output could change in the future.

**Comment by rmachielse** [comment]
@mperham thanks for your quick response! #3621 will fix this problem (I verified).
I took those methods from the web interface indeed. Is there a better way to retrieve the job's class name, method and arguments in a similar format?

**Comment by mperham** [comment]
It's unlikely to change but I can't control AJ so it's hard to say.

**Comment by rmachielse** [comment]
Alright 👍  thanks for the merge. Any idea when the next release will be?

**Comment by mperham** [comment]
Just now.

**Comment by rmachielse** [comment]
Awesome, thanks a lot!
