### ISSUE TITLE
Systemd with Rbenv dosen't work

### ISSUE THREAD

**Issue by ggoral** [mperham/sidekiq#3622]
About this file

https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service#L29

I've problems with line #29

`# ExecStart=/bin/bash -lc 'bundle exec sidekiq -e production'`

I fix this issue with fullpath on rbenv, for example:
`ExecStart=/home/deploy/.rbenv/bin/rbenv bundle exec sidekiq -e production`

**Comment by mperham** [comment]
Those files are examples because they will need to be customized for your environment.

**Comment by ggoral** [comment]
@mperham yes, I custimized my files for my environment, but the solution is not good enough for me. Those parameters for bash dosen't work.
bash -l >> Make bash act as if it had been invoked as a login shell
but dosen't load rbenv therefore #L29 had problems.
