### ISSUE TITLE
Connections leaked on job exception in Rails 5

### ISSUE THREAD

**Issue by jwilm** [mperham/sidekiq#3624]
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s):
Sidekiq OSS 5.0.5

We've recently upgraded from Rails 4 to Rails 5, and in doing so found that ActiveRecord connections are not being cleaned up when a job encounters an exception. After looking around Sidekiq a bit, it looks like the previous `call` impl had an `ensure` block which ran `::ActiveRecord::Base.clear_active_connections!`. Allegedly, the new `Reloader` is supposed to handle connection management, but whatever it's doing isn't sufficient for cleaning up in this case.

**Comment by mperham** [comment]
What version of Rails?  Sidekiq is now deferring all connection management to the Reloader so any bugs would have to be fixed there.

**Comment by jwilm** [comment]
Hey @mperham, thanks for following up. We're on Rails 5.0.6, but it looks like 5.1.4 is available today.

We'll try updating to the latest and see if that has an effect. Otherwise, your response here will be helpful in getting it resolved upstream.
