### ISSUE TITLE
Question about upgrading from reliable_fetch to super_fetch

### ISSUE THREAD

**Issue by meenie** [mperham/sidekiq#3625]
We've finally gotten around to upgrading all of our Sidekiq gems and want to use the new `super_fetch` feature.  I did some initial testing by starting a long-running job, stopped the worker in the middle of that job, upgraded the gem (switch to the branch with the upgraded gems) and then started the worker up again and the job is never picked back up.  If I stop the worker again, downgrade and then start the worker back up, then that job is picked up using the old `reliable_fetch`.  I tried searching around the wiki and old issues, but haven't found a solution to this.  What is the recommended way to upgrade?

**Comment by mperham** [comment]
There's no specific tooling or process for the upgrade.  You can start new processes running super_fetch and quiet the old processes so they finish their jobs over time.  Stopping a worker process gracefully should not result in a job stuck in the private queue unless your process for stopping a worker does not follow the best practices.

https://github.com/mperham/sidekiq/wiki/Deployment#overview

**Comment by meenie** [comment]
We use Heroku. Would this be a good course of action?:
1) Start deployment of updated Sidekiq
2) Quiet the currently running workers so they finish what they are doing
3) Once deployment is done, the old workers will be killed off
4) New workers will start working the queues

**Comment by meenie** [comment]
That works on my local testing. We'll do some more testing in our staging environment in Heroku to make sure.  Thanks for your time!
