### ISSUE TITLE
Sidekiq stops working jobs after SystemStackError

### ISSUE THREAD

**Issue by evanlemke** [mperham/sidekiq#3627]
Ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]
Sidekiq version: 5.0.0

I had an error in a job that throws `SystemStackError: stack level too deep` and Sidekiq would consistently stop popping jobs from the queue.  `ps aux` & `htop` show Sidekiq running fine and using normal amounts of memory.  

In this screenshot, you'll see no workers are busy, and the 32 jobs in the queue continue to grow and never get worked.  If I restart Sidekiq everything begins to process like normal.
![image](https://user-images.githubusercontent.com/3923517/31295003-28d9a89a-aa9a-11e7-87cb-c760fcef9133.png)

I have fixed the issue in my job, but I'm concerned that a problem in one job can cause Sidekiq to hang permanently.  Also, I'm not sure how to detect that Sidekiq is no longer working jobs and have a process monitor restart it.

**Comment by mperham** [comment]
SystemStackError means the VM is in bad shape.  Generally you shouldn't rescue a VM exception like this, but rather let the VM crash so it can restart everything in a good, known state.  I can't explain why Sidekiq stopped but it's difficult to explain any behavior after a VM fault like that.

If Busy == 0 and Enqueued > 0, it's possible that something is wrong but there are edge cases where this state is normal: pausing all queues, quieting all processes pre-deploy are two such cases.

**Comment by evanlemke** [comment]
I was not rescuing the exception, and expecting sidekiq to put the  the retry queue.  Instead, sidekiq just stops working on all threads.

> If Busy == 0 and Enqueued > 0

I first found this issue in in production where we work tens of thousands of jobs per day making the activity pretty easy to track.  As soon as I enqueue the job that causes this exception all jobs stop processing.  A restart of sidekiq brings it back to normal (must restart because sidekiq is still running).

My biggest concern is that the sidekiq pid is still running and unchanged.  There is no way for me to know that sidekiq has stopped working jobs because it passes all health checks.

**Comment by mperham** [comment]
> I was not rescuing the exception, but expecting for it to fail and be put in the retry queue. Instead, sidekiq just stops working on all threads.

Sidekiq does not rescue VM-level exceptions, for all the reasons I gave above.

> My biggest concern is that the sidekiq pid is still running and unchanged. There is no way for me to know that sidekiq has stopped working jobs because it passes all health checks.

Me too.  I have no idea how to fix this.  Ideas welcome.

**Comment by mperham** [comment]
Perhaps you hit a Ruby bug and should try upgrading to 2.3.5?

**Comment by evanlemke** [comment]
> Sidekiq does not rescue VM-level exceptions, for all the reasons I gave above.

I feel like it is rescuing because it stays running, I'd much prefer sidekiq to just crash.  Would you be interested in looking at a code sample that reproduces the issue?

 >Perhaps you hit a Ruby bug and should try upgrading to 2.3.5?
 
Will try this.

**Comment by mperham** [comment]
I take that back:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_retry.rb#L78
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L178

It should keep processing, but as I said, when the VM is in a bad state, all bets are off.

**Comment by marzapower** [comment]
I am experiencing something similar, but I don't know if it's related. When the day changes, `sidekiq` stops working. As said previously, the process seems to be fine, it appears in the `ps` results and in the `top`/`htop` listings, and nothing gives me a hint of what's happening. But basically after midnight every queue will get stuck. It's the third day straight now, and I'm reverting to v. `4.x` now.

**Comment by mperham** [comment]
I can't debug this without more information, a full stack and more complete gem version listing would help.  Make sure you are on the latest Sidekiq/Rails versions possible.
