### ISSUE TITLE
Feature Request: Exit Sidekiq when things are going mad...

### ISSUE THREAD

**Issue by lfarcy** [mperham/sidekiq#3628]
Ruby version: 2.2.2p95
Sidekiq / Pro / Enterprise version(s): Sidekiq 3.3.4

We recently had an incident in production where we would have appreciated if Sidekiq had decided to exit by itself. And let our monitoring solution restart its process(es).

After enqueuing a few thousand jobs on the same worker class, every job execution immediately failed with the same error. Each job was trying to save an active record but raised a NoMethodError. The transaction that was opened had a nil parent. Something we've never seen before for the few millions jobs we've executed so far. Something we have not been able to explain.

In such a situation, where a sudden peak in failures happens, which all raise the same (system) error, it could be wise for Sidekiq to acknowledge something mad is happening and exit.

I'm wondering if such a feature has already been discussed and how it could be implemented (a StopMadness middleware could eventually make it).

Thanks for your feedbacks.

**Comment by mperham** [comment]
> In such a situation, where a sudden peak in failures happens, which all raise the same (system) error, it could be wise for Sidekiq to acknowledge something mad is happening and exit.

**could be wise**.  There's plenty of situations where this isn't true and the devil is in the details.  You are welcome to propose something but the right thing for Sidekiq to do here in the face of incomplete knowledge is be conservative.

**Comment by lfarcy** [comment]
Thx for the reply. I totally understand your point. That's why I'm more thinking of an optional middleware that could be configured with a few rules and parameters and make Sidekiq to shutdown under some (very) special circumstances.

If I go this way, I may have some difficulties to articulate this logic together with the RetryJobs middleware. Having the right order in the middleware stack should make it.

BTW, I thought of a better name: EmergencyExit. This is really what I'm thinking about, to walk through in case of a major blaze.

Last, I need to better understand how I can make Sidekiq exit gracefully.

**Comment by mperham** [comment]
If you get something you think will work for everyone, let us know.  I'd be happy to review.

**Comment by lfarcy** [comment]
Will definitively ask for review if I move forward. Thx.
