### ISSUE TITLE
Sidekiq attempting to push jobs to Redis in testing.

### ISSUE THREAD

**Issue by pnomolos** [mperham/sidekiq#3630]
Ruby version: 2.3.3p222
Sidekiq / Pro / Enterprise version(s): 5.0.5 / 3.5.3 / nil

### Initializer
```ruby
Sidekiq.configure_server do |config|
  # config.super_fetch! unless $environment == :test
  config.server_middleware do |chain|
    # if :development == $environment
    #   chain.add(RssReportingMiddleware)
    # end

    if :production == $environment
      chain.add(Sidekiq::Middleware::Server::Datadog)
    end
  end
end
```

I'm having an issue during testing (rspec), and I've removed all third -  in a rather complicated scenario using nested batches I'm seeing jobs pushed to Redis even though I have the following in my spec helper:

```ruby
  config.before(:each) do
    Sidekiq::Worker.clear_all
  end

  config.around(:each) do |example|
    Sidekiq::Testing.inline! do
      example.run
    end
  end
```

I've tried completely shutting down Redis and my code fails on the last line of the following with a `Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)` error:

```ruby
    results = []
    Sidekiq.logger.debug("UPLOADING FILE - #{Sidekiq::Testing.enabled?} - #{Sidekiq::Testing.fake?} - #{Sidekiq::Testing.inline?}")
    b = Sidekiq::Batch.new
    # b.on(:success, ProcessUploadedFileJob::UPLOAD_BATCH_HANDLER)
    b.jobs do
```

The output of that debug statement is "Sidekiq -- UPLOADING FILE - true - false - true" or "Sidekiq -- UPLOADING FILE - true - true - false" depending on whether I'm using `inline!` or `fake!`.  In either case I get the `ECONNREFUSED`.

**Comment by mperham** [comment]
Batches don't support fake or inline modes.  They always use Redis.

**Comment by pnomolos** [comment]
Would you be open to a PR that on Batch.new or <batch>.jobs outputs a
notice if you’re attempting to use it in inline or fake mode?

**Comment by mperham** [comment]
I wouldn't want a PR for that.  Batches require Redis so the error is expected.  I will add a note to the wiki so people understand that is a specific design decision I made.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Batches#testing

**Comment by pnomolos** [comment]
@mperham Sorry to re-open this, but I'm running in to issues with that example testing code you provided - It's not running some/any of the non-batch jobs.  It looks like they're being pushed to Redis as well even with Sidekiq in testing mode.  Would you like me to try and produce a minimal test case?

**Comment by pnomolos** [comment]
Nevermind, load order issues - was requiring 'sidekiq/testing' before 'sidekiq-pro' was loaded, which meant that the 'sidekiq-pro' implementation of `raw_push` was overriding the testing version.

**Comment by mperham** [comment]
:+1: Thanks for the update.

**Comment by pnomolos** [comment]
@mperham Would you be open to a PR for that (detect if `Sidekiq::Testing` exists when 'sidekiq-pro' is required)?  I realize it's probably a pretty rare occurrence but it was a massive pain in the butt to track down.

**Comment by mperham** [comment]
I'd say no, it feels a little too specialized/rare to handle specifically.
