### ISSUE TITLE
Combine Reliability and Pro-Reliability-Server wiki pages?

### ISSUE THREAD

**Issue by aripollak** [mperham/sidekiq#3632]
Is there any reason these pages should not be combined? They seem to overlap a bunch.

**Comment by mperham** [comment]
The Reliability page is legacy but referenced by the Pro source code in a deprecation warning.  Ideally it's not linked anywhere. It contains old info relevant to older Sidekiq Pro versions (e.g. reliable_fetch, timed_fetch, etc).  super_fetch should be the only documented thing for current versions.

**Comment by aripollak** [comment]
Would it make sense to at least combine most of the Reliability page with Pro Reliability and link to the latter? They both seem to talk about legacy strategies.

**Comment by mperham** [comment]
It's fine the way it is.  The public page, Reliability, only explains super_fetch and has a note about the old strategies at the bottom.  The Pro-Server-Reliability page is referenced in the deprecating warning and talks more about the old strategies and why super_fetch is better.  New users don't need that noise.
