### ISSUE TITLE
Sidekiq rejects output of Marshal.dump

### ISSUE THREAD

**Issue by emirkin** [mperham/sidekiq#3638]
[cross-submitted to https://bugs.ruby-lang.org/issues/14018]
I encountered this bug when using ActiveJob in Rails. Here is what happens...

```
parcel = Marshal.dump(1508129809) # => "\x04\bl+\a\x11<\xE4Y"
MyJob.perform_later(parcel) # this is where the error happens (as the parcel is being prepared for the send-off)
```

When I use the built-in Rails 5 queue adapter, everything works fine. If, however, I switch to Sidekiq, I get this:
`Encoding::UndefinedConversionError ("\xE4" from ASCII-8BIT to UTF-8)`

**Comment by mperham** [comment]
Job parameters must be JSON-friendly, meaning UTF-8 text.  Marshal outputs raw binary data and will not work.

https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple

**Comment by emirkin** [comment]
Well, technically, Marshal outputs an Ascii string - as identified by `output.class` and `output.encoding`. So, it should be acceptable, no?

**Comment by mperham** [comment]
It's ASCII-8BIT, which is binary.

**Comment by mperham** [comment]
Could you include the full backtrace of the error and I'll double check?

**Comment by emirkin** [comment]
There is no stack trace, actually... The top of the exception points to my `.perform_later` call (and further down, there are other functions from my codebase that lead to this call). So, the exception is thrown in some implicit conversion of parameters between my call and ActiveJob.perform.

Try creating a bare knuckles ActiveJob descendant and pass that parcel of mine to it. That should do it.

**Comment by Awlter** [comment]
Hi, @emirkin , could you elaborate what you mean by "Try creating a bare knuckles ActiveJob descendant and pass that parcel of mine to it"
