### ISSUE TITLE
Sidekiq UI CSS/JS is not loading

### ISSUE THREAD

**Issue by sandstrom** [mperham/sidekiq#3639]
Ruby version: 2.4.1
Sidekiq: 5.0
Sidekiq Pro: 3.5

![image](https://user-images.githubusercontent.com/122287/31611710-7808e4fe-b27d-11e7-925e-fad5990e5659.png)

We're using Rails 4.2, as an API (so we don't use the asset-pipeline, for example). Could that play a role in this?

I looked at the assets in this repo, doesn't seem like they need any precompilation though.

**Comment by mperham** [comment]
Give us a small app to reproduce the problem.  These are, 99.99% of the time, caused by app-specific config.

**Comment by sandstrom** [comment]
I'll see what I can do.

So there is no requirement to use the asset pipeline for the web UI to work?

**Comment by mperham** [comment]
The web UI uses nothing but Rack.  There's no rails usage, asset processing or anything else baked in.

**Comment by jeremybdk** [comment]
Are you using Heroku? We had this issue because of one gem: https://github.com/mperham/sidekiq/issues/3179

**Comment by sandstrom** [comment]
Thanks @jeremybdk and @mlefrancois19 for the suggestions. In our case it's not heroku, but don't quite know yet.

I'll close this issue for now, since it's not very actionable. Will re-open if I have more actionable data, reproduction, etc.
