### ISSUE TITLE
Smarter or manual dequeueing ?

### ISSUE THREAD

**Issue by HealtheFilings-readonly** [mperham/sidekiq#3641]
Is there a way for a worker to decide which queue to dequeue from? Example

`Files` queue has zip files which are unzipped and creates jobs on the `imports` queue.  Would like to normally prioritize `imports` queue over `files` queue, but when the `imports` queue is low enough, I'd like to process one off the `file` queue, so workers on the `imports` queue don't get starved.

I currently use weighted queues to give imports greater weight, but that is limited in that the zip files could have any number of files in them.  Also, I considered using the API to check the queue size and recreating the `file` job but that seems like a hack and reorders the imports which I don't like.

Is there an API for this, or a pattern I am missing?

Thanks

jeff

**Comment by mperham** [comment]
Nope and nope.  Sidekiq can do strict priority or weighted priority -- the 80/20 solution.  More complex scenarios like you describe wouldn't be useful to most users and require a big performance hit in Redis.
