### ISSUE TITLE
sidekiq.org optimization

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3642]
For search ranking, we need to implement TLS on sidekiq.org.  GitHub Pages does not support TLS on custom domains, use Let's Encrypt and move the website onto the contribsys server or another host.

See also, https://developers.google.com/speed/pagespeed/insights/?url=sidekiq.org&tab=mobile

**Comment by ryansch** [comment]
@mperham You can also use S3 +CloudFront to do free SSL with ACM.

**Comment by mperham** [comment]
@ryansch I'm allergic to AWS, maybe because of the unpredictable bill at the end of each month.

**Comment by ryansch** [comment]
Fair enough!
