### ISSUE TITLE
logging configuration

### ISSUE THREAD

**Issue by steveburkett** [mperham/sidekiq#3651]
In our sidekiq server logs (sidekiq.log), i was finding that it's filling up with rails logging information.  Setting 
```
Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }
  config.logger.level = ::Logger::INFO
end
```
failed to stop the flow of debug level rails logging into the sidekiq.log.

this worked better.  does this look right?  it seems odd to have to set both Rails.logger and ActiveRecord::Base.logger to the Sidekiq logger, but this is the only way i've found to have 1 server side logging setting to control the flow of logging. 
```
Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }
  config.logger.level = ::Logger::INFO

  Rails.logger = Sidekiq::Logging.logger
  ActiveRecord::Base.logger = Sidekiq::Logging.logger
end
```

**Comment by mperham** [comment]
I don't know of any better way to do this.  Expert opinions and cleaner options very welcome.

**Comment by netwire88** [comment]
@mperham Is this still the correct way to set Sidekiq logging level in 2022? Or is it using Rails logging level now?

**Comment by mperham** [comment]
Yes. Sidekiq.logger is the only supported API.  Don’t use Sidekiq::Logging in your code.
