### ISSUE TITLE
Data Loss while sending more than 6k records

### ISSUE THREAD

**Issue by rajcybage** [mperham/sidekiq#3653]
Hi ;

While any ETL sending 6K record to load using api services and background using sidekiq. Some are loaded and some are lost

While we are using simple load without sidekiq it is loaded.

Can you please let us know what may be the reason for it?

Our Code is Thread safe

We have retry true

Thanks
Rajarshi

Ruby version: 2.2.3
Sidekiq / Pro / Enterprise version(s): Enterprise 1.5.1

Please include your initializer and any error message with the full backtrace.

```
require 'sidekiq'
require 'sidekiq/web'
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'], network_timeout: 3600 }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'], network_timeout: 3600 }
end

Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
Sidekiq::Web.set :sessions, Rails.application.config.session_options

````
Are you using an old version?
Have you checked the changelog to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by mperham** [comment]
You'll need to be more specific with your situation.  "Some are loaded and some are lost" is not enough for me to understand the problem or determine the issue.  It would help to see all relevant code.
