### ISSUE TITLE
Web UI for stale jobs?

### ISSUE THREAD

**Issue by adrian-gomez** [mperham/sidekiq#3656]
Ruby version:
- ruby 2.3.4p301

Sidekiq / Pro / Enterprise version(s):
- sidekiq (5.0.5)

Hi I'm wondering if Sidekiq has a way of showing "stale" jobs on the Web UI, by stale I mean a job is started and is never finished because the whole sidekiq process gets shutdown unexpectadly. The problem is that we are running our prod code on https://www.aptible.com/, and for brackground jobs they dont send any signal to the container before shuting it down (lame I know) and while we are using `Sidekiq::ProcessSet.new.each(&:quiet!)` and `Sidekiq::ProcessSet.new.each(&:stop!)` before out deploy starts it could happen that Aptible kills the container before the workers are terminated by Sidekiq.

Resque notifies about this with `Resque::PruneDeadWorkerDirtyExit` error, is there something like that on sidekiq? If not anyone has any advice on where would be the best place to check for that?

A way to replicate that is to create a long running worker (by putting a sleep on it) starting it and then killing the sidekiq process with `kill -9`, when you restart sidekiq the job/worker dissapears from all lists on the Web UI.

Thanks

**Comment by mperham** [comment]
There's no way to recover from that with normal Sidekiq, the Busy data expires quickly without a process heartbeat, that's why it disappears from the Busy page.  You need Sidekiq Pro to recover jobs lost due to kill -9.

**Comment by natematykiewicz** [comment]
If the problem really is only from deployments, you're probably shutting down Sidekiq wrong. Check out https://github.com/mperham/sidekiq/wiki/Signals.

**Comment by adrian-gomez** [comment]
@natematykiewicz The platform we use wont send shutdown signals to the workers nor will it allow us to configure a wait timeout. Lame I know but it is what it is.

@mperham Sorry for the late response and to bring this zombie back up, is this something you are willing to add to sidekiq? Its not a a big change and I have already coded it, I can create a PR for it if you want to consider it. If not I understand and I'll try to make it into an extension (probably an ugly one as it needs to update two internal methods.

**Comment by mperham** [comment]
@adrian-gomez I don't know what "this" is so I don't know but Sidekiq's shutdown/deployment process is pretty set in stone at this point.  It's a bad sign that your PaaS doesn't signal to processes upon shutdown, kill -9 is not a good idea.

**Comment by adrian-gomez** [comment]
@mperham This would be showing on the web iu zombie workers. That means not setting an expiration on the `[process tuid]` and `[process tuid]:workers` keys on redis.
And updating `ProcessSet.cleanup` to check if there any processes whose last heartbeat is older than 60 seconds. If so it gets removed and an entry is added to the dead job queue.

So no changes to the deployment.

PS: I know that the lack of signals on our PaaS its a really bad thing, but we need to stay on it for hipaa reasons.

**Comment by adrian-gomez** [comment]
These would be the changes required: https://github.com/mperham/sidekiq/compare/master...adrian-gomez:dirty-exit?expand=1

**Comment by adrian-gomez** [comment]
@mperham ^

**Comment by mperham** [comment]
Not expiring the process record in Redis is much more difficult than you think.  It is the "heartbeat" that powers a few other features; both Pro's SuperFetch and Enterprise's Leader election rely on the expiring heartbeat to work properly.

**Comment by mperham** [comment]
Sidekiq Pro's reliable fetch will allow your jobs to survive on aptible.  Why not just buy it and consider the problem solved?  You must be paying through the nose for a HIPAA compliant PaaS so the cost should be minimal.

**Comment by adrian-gomez** [comment]
Got it, it makes sense.
I'll probably keep what I have for personal use for now and see how it goes.

Yeah I'm pushing for sidekiq pro but its not my call. I just convinced the team to migrate over from resque, so one step at a time.

Thanks for the help and sidekiq!
