### ISSUE TITLE
Record not found even if not in a transaction

### ISSUE THREAD

**Issue by benoittgt** [mperham/sidekiq#3657]
Ruby version: 2.4
Sidekiq versions:   sidekiq (5.0.5)  sidekiq-pro (3.5.3)

Hello

I already contacted Mike Perham [on twitter](https://twitter.com/mperham/status/926481775768977408). But I didn't find a way to understand what is happening with my code and workers.

Here is my first worker

```ruby
class ProcessBinaryLinkWorker
  include Sidekiq::Worker

  sidekiq_options queue: :primary, retry: false

  def perform(binary_id)
    binary = Binary.find(binary_id)
    # other code but no transactions
    method_that_do_some_saving_to_db_using_active_record(binary, params)
    Sidekiq.logger.info("ProcessBinaryLinkWorker binary.group_ids: #{binary.group_ids}") # Will print [1, 2, 3]
    binary.publish! # This method will call PublishWorker with binary_id
  end
end
```

Where `method_that_do_some_saving_to_db_using_active_record` does

```ruby
binary.update!(params)
```
and `PublishWorker` does

```ruby
class PublishWorker
  include Sidekiq::Worker
  sidekiq_options queue: :other_queue, retry: false

  def perform(binary_id)
     binary = Binary.find(binary_id)
     Sidekiq.logger.info("PublishWorker binary.group_ids: #{binary.group_ids}") # will sometimes print []
     binary.big_sql_query
  end
end
```

In my log I see when it fails
```
ProcessBinaryLinkWorker JID-0febcd0332d064a6445e3e52 INFO: start
PublishWorker JID-279bfcc33cc5323b4a91e72d INFO: start
ProcessBinaryLinkWorker JID-0febcd0332d064a6445e3e52 INFO: ProcessBinaryLinkWorker binary.group_ids: [1, 2, 3]
PublishWorker JID-279bfcc33cc5323b4a91e72d INFO: SidekiqMemorySampling queue=visibility worker=PublishWorker jid=279bfcc33cc5323b4a91e72d args=[273935, {"notify"=>nil}] started_at=2017-11-01T08:55:21+00:00 ended_at=2017-11-01T08:55:21+00:00 elapsed_ms=21.503973
PublishWorker JID-279bfcc33cc5323b4a91e72d INFO: done: 0.026 sec
ProcessBinaryLinkWorker JID-0febcd0332d064a6445e3e52 INFO: PublishWorker binary.group_ids: [] # !!!!!!!!!!!!!!!!!!!!!!!
ProcessBinaryLinkWorker JID-0febcd0332d064a6445e3e52 INFO: SidekiqMemorySampling queue=primary worker=ProcessBinaryLinkWorker jid=0febcd0332d064a6445e3e52 args=[273935, 8454, 210880, {}] started_at=2017-11-01T08:55:16+00:00 ended_at=2017-11-01T08:55:21+00:00 elapsed_ms=5433.250164
ProcessBinaryLinkWorker JID-0febcd0332d064a6445e3e52 INFO: done: 5.435 sec
```

When it works
```
ProcessBinaryLinkWorker JID-364a5e02cbf08bb44a55764e INFO: start
ProcessBinaryLinkWorker JID-364a5e02cbf08bb44a55764e INFO: ProcessBinaryLinkWorker binary.group_ids: [1, 2, 3]
ProcessBinaryLinkWorker JID-364a5e02cbf08bb44a55764e INFO: SidekiqMemorySampling queue=primary
worker=ProcessBinaryLinkWorker jid=364a5e02cbf08bb44a55764e args=[274364, 6680, 149044, {}] started_at=2017-11-03T10:43:52+00:00 ended_at=2017-11-03T10:43:53+00:00 elapsed_ms=1128.265477
ProcessBinaryLinkWorker JID-364a5e02cbf08bb44a55764e INFO: done: 1.13 sec
PublishWorker JID-722d5470ff901b835ef6b16b INFO: start
PublishWorker JID-722d5470ff901b835ef6b16b INFO: PublishWorker binary.group_ids: [1, 2, 3]
PublishWorker JID-722d5470ff901b835ef6b16b INFO: SidekiqMemorySampling queue=visibility worker=PublishWorker jid=722d5470ff901b835ef6b16b args=[274364, {"notify"=>nil}] started_at=2017-11-03T10:43:53+00:00 ended_at=2017-11-03T10:43:53+00:00 elapsed_ms=42.843255
PublishWorker JID-722d5470ff901b835ef6b16b INFO: done: 0.058 sec
```

Our issue is sometimes `PublishWorker` seems not able to get the data set into `method_that_do_some_saving_to_db_using_active_record`. It try to publish but infos (`groups_ids`) are not available. In the log below first case failed, second case worked. 
Is it possible that sidekiq is too fast for the transaction to finish and the next job doesn't have the data commited into database? 

`method_that_do_some_saving_to_db_using_active_record(binary, params)` and `binary.publish!` are not wrapped into a transaction block. `method_that_do_some_saving_to_db_using_active_record` `COMMIT` changes before going to the next method and call `PublishWorker`.

Thanks for the help

**Comment by mperham** [comment]
Try explicitly using a transaction before creating the job.

```ruby
  def perform(binary_id)
    Binary.transaction do
      binary = Binary.find(binary_id)
      method_that_do_some_saving_to_db_using_active_record(binary, params)
    end
    binary.publish! # This method will call PublishWorker with binary_id
  end
```

**Comment by benoittgt** [comment]
Thanks will try it next day.

**Comment by benoittgt** [comment]
Ok we still have the issue even with the transaction block.

One strange thing is `Sidekiq.logger.info("PublishWorker binary.group_ids: #{binary.group_ids}")` will print log slightly before `Sidekiq.logger.info("ProcessBinaryLinkWorker binary.group_ids: #{binary.group_ids}")` when it should be the other behavior.

Today for example
```
13:29:40.453873+00:00 app worker_visibility.1 - - 4 TID-or32m26yk PublishWorker JID-960e22ba9d8c9f5ee5190820 INFO: PublishWorker binary.group_ids []
..
13:29:40.633428+00:00 app worker_primary.1 - - 4 TID-otsq6pqyw ProcessBinaryLinkWorker JID-c97a660052b90ce82071d2fb INFO: ProcessBinaryLinkWorker binary.group_ids: [1479]
```
I don't know if I could rely on this time difference. Our app is on Heroku with workers on different queues.

**Comment by mperham** [comment]
Easy solution: `perform_in(5.seconds, args...)`

Hard solution: keep debugging and determine why you aren't seeing real transactional semantics.

**Comment by benoittgt** [comment]
Yep. Thanks for the help.

I tried to write reproduce code this morning but was not able to make it fail like in see in our production env (5% failing average).

Will close it for now because I don't have reproduce code and I think it's more related to our code base but will keep this thread updated when I will find the answer.

**Comment by benoittgt** [comment]
Ok I probably found the issue.  In some case `method_that_do_some_saving_to_db_using_active_record` call an other method that will call `PublishWorker`. So I was correct `PublishWorker` is called sometimes before `    Sidekiq.logger.info("ProcessBinaryLinkWorker binary.group_ids: #{binary.group_ids}")`. But the reason second worker is never called is because we are using https://github.com/mhenrixon/sidekiq-unique-jobs . The second job was skipped silently because it had the same parameters as the first call.

So the fix was simply don't call `PublishWorker` in `method_that_do_some_saving_to_db_using_active_record` and second careful when using sidekiq-unique-job. Always [enable log](https://github.com/mhenrixon/sidekiq-unique-jobs#logging).

**Comment by mperham** [comment]
Sidekiq Enterpise's unique jobs always logs when cancelling a job push, to avoid that mystery.  :wink:
