### ISSUE TITLE
Sidekiq::Stats lib recognizes 0 jobs processed

### ISSUE THREAD

**Issue by dblack10** [mperham/sidekiq#3661]

**Comment by mperham** [comment]
The config file doesn't matter at all.  What matters is your Redis config in the initializer.

**Comment by dblack10** [comment]
The redis config in my initializer only sets the namespace param on both client and server configs using the middleware/i18n lib like so:

config.redis = { namespace: '<name>'}

However, I have another environment that doesn't mention redis at all in the initializer, yet I am able to pull stats as expect. The only difference is resolv-replace is used instead of the middleware/i18n.

What do I need to add to the first initializer in order to read stats from redis?
Once config.redis is declared, is the url param mandatory for sidekiq/api to read stats?
Would using resolv-replace in place of the middleware lib make any significant changes?

**Comment by mperham** [comment]
A namespace of "" is very different from a nil namespace.  That's possibly the issue.

**Comment by mperham** [comment]
resolv-replace and i18n have nothing to do with this issue.

**Comment by dblack10** [comment]
"" was just an example namespace

**Comment by mperham** [comment]
I can't help you if you won't show me your initializer.
