### ISSUE TITLE
Missing unique jobs when batch has any error

### ISSUE THREAD

**Issue by andersondias** [mperham/sidekiq#3662]
Ruby version: ruby 2.4.1p111
Sidekiq / Pro / Enterprise version(s): 5.0.5, 3.5.3, 1.6.1

Hi ;)

During some Sidekiq Batch tests I've found an edge case:

```ruby
class UniqueWorker
  include Sidekiq::Worker
  sidekiq_options unique_for: 1.day

  def perform(id); end
end

batch = Sidekiq::Batch.new
batch.jobs do
  UniqueWorker.perform_async(1)
  raise
end

batch = Sidekiq::Batch.new
batch.jobs do
  UniqueWorker.perform_async(1)
  UniqueWorker.perform_async(2)
end

UniqueWorker.perform_async(1)
```

During the second round of batch scheduling I got this message:

```
2017-11-11T16:45:17.147Z 19318 TID-ouhknjufw INFO: Skipping enqueue for UniqueWorker, not unique.
```

When I looked for execution stats I've found that only the second job in the batch has ran.
It looks like the first unique job has been scheduled but it will never be executed.

Any thoughts on this?
Best!

**Comment by mperham** [comment]
Yep, that looks like the current behavior.  The unique lock is taken when that perform_async line executes but the exception prevents the batch jobs from actually going to Redis so the lock will be held for 24 hours.

At first glance I don't see any way to fix this without greatly increasing complexity.  I would pull the unique job out of the batch if possible.

**Comment by andersondias** [comment]
I found this edge case during my studies and would definitely not use unique jobs inside of batches. But, it can lead other devs to really complex situations. I would prefer to have a safer batch API that tells me I'm doing something wrong or even disabling the unique feature inside the batch.

**Comment by mperham** [comment]
I think the main issue can be solved by adjusting the order of client middleware.

**Comment by mperham** [comment]
Nevermind, the main issue still remains.  I've fixed the issue where a unique job that did not push to Redis is still counted as part of the batch.

**Comment by mperham** [comment]
I don't see how to fix this further without pretty major surgery.  I've updated the Batch wiki page notes to recommend against uniqueness in batch jobs.

**Comment by philipbjorge** [comment]
@mperham -- Do you know if this edge case applies when we have a job that creates a batch?

```
class UniqueWorker
  include Sidekiq::Worker
  sidekiq_options unique_for: 1.day

  def perform
    batch = Sidekiq::Batch.new
    batch.jobs do
      RegularWorker.perform_async(1)
      raise
    end
  end
end
```

Would this scenario release the lock?

**Comment by mperham** [comment]
That would behave like any failed unique job: the lock is not released until it times out or the job succeeds.
