### ISSUE TITLE
 ActionController::Parameters turn into JSON strings when passed to jobs.

### ISSUE THREAD

**Issue by aselder** [mperham/sidekiq#3667]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s): 4.2.10

If you pass an instance of ActionController::Parameters as an argument to a sidekiq worker, when it appears in the sidekiq job, it is a json string of the value

For instance:

If the following is passed to a job:
```
<ActionController::Parameters {"category"=>"Hello", "sub_category"=>"Bye", "description"=>"99 problems", "skip_description_validation"=>true} permitted: true>
```
 inside the job this becomes:

```
"{\"category\"=>\"Hello\", \"sub_category\"=>\"Bye\", \"description\"=>\"99 problems\", \"skip_description_validation\"=>true}"
```

This behavior changes form Rails 4.2 to Rails 5.0 btw. I'm guessing it has to do with AC::Parameters inheriting from Hash in Rails 4.2 and not in Rails 5.0.

The fairly easy working around is to call `.to_unsafe_h` on the AC::Parameters object before sending to sidekiq

I'm wondering if there would be a way to automatically get an AC::Parameters object turned into a hash when sent thru sidekiq.

I understand if you don't want to add the complexity, so feel free to close this. About 50% of the purpose of this issue is documentation incase someone else runs into the same problem.

**Comment by smeriwether** [comment]
I am seeing this same issue. 

Rails: 5.0.5
Sidekiq: 3.5.4

Passing `ActionController::Parameters` to a worker results in this string:
```
=> "{\"email\"=>\"foo@example.com\", \"eventName\"=>\"sms\", \"dataFields\"=><ActionController::Parameters {\"smsMessage\"=>\"This is a test message\", \"toPhoneNumber\"=>\"+1111111111\", \"fromSMSSenderId\"=>\"111\"} permitted: true>}"
```

**Comment by mperham** [comment]
As you say, I don't plan to special case **any** Ruby objects for serialization, basic JSON types only.  ActiveJob decided to go all the way on serialization magic, I decided against any magic.  Each is a perfectly fine choice with tradeoffs.
