### ISSUE TITLE
Sidekiq performance under Kubernetes

### ISSUE THREAD

**Issue by randomm** [mperham/sidekiq#3670]
Hi all,

this is really a question, rather than an issue. I'm migrating an application from using Heroku Sidekiq workers to an Azure hosted Kubernetes setup and am witnessing a markedly poorer Sidekiq performance (by a factor of ten or so). Has anyone experience similar issues? My Kubernetes has plenty of resources available, and regardless of any resource allocation settings for K8s I'm not able to get oomp out of my K8s pods... I'm guessing that this is a Kubernetes / Docker / Linux issue rather than a Sidekiq one, but just thought to ask if anyone has experienced the same.

many thanks,

Jani

ps. Ruby 2.3.5 and latest Sidekiq 4 series...

**Comment by mperham** [comment]
I would investigate Redis network performance and latency in each environment.
