### ISSUE TITLE
Config file keys inconsistent types

### ISSUE THREAD

**Issue by dpogue** [mperham/sidekiq#3672]
Ruby version: 2.4.1
Sidekiq / Pro / Enterprise version(s): 5.0.5

It is confusing and error-prone for the sidekiq config file to require a mix of string keys and symbol keys. It currently appears that options need to be symbol keys, but environment groups need to be string keys.
I ran into issues with my workers yesterday when setting up a new project because of `queues:` vs `:queues:` in config/sidekiq.yml.

Rails config files tend to use strings everywhere in the Yaml, and then load as a HashWithIndifferentAccess. I don't necessarily think we want to depend on ActiveSupport for that, but other options might include `Hash#deep_symbolize_keys` or `Hash#deep_stringify_keys` and always doing hash lookups with a consistent type.

**Comment by mperham** [comment]
Yep, symbols & strings should both be supported, that's a bug.

**Comment by mperham** [comment]
This hash should be indifferent:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L388
