### ISSUE TITLE
Am I using `inline!` wrong? Job doesn't appear to execute

### ISSUE THREAD

**Issue by ttrmw** [mperham/sidekiq#3676]
Ruby version: 2.4.0p0
Sidekiq / Pro / Enterprise version(s): Pro, 3.5.3

I'm attempting to make a failing test that I know should result in an exception. I am not sure if I'm misunderstanding the docs, but it seems like wrapping my test in a

```
Sidekiq::Testing.inline! do 
   ...
end
```

should do the trick if I want to see the exception raised, right? Except it doesn't seem to! If I put in a debugger right where the `Job.perform_later` call is, and call `perform_now` instead, I get the exception as expected.

Have I misunderstood or messed something up in my setup?

**Comment by ttrmw** [comment]
ah also the test log shows the job as "enqueued" unless I use `perform_now`, in which case it perform.

**Comment by mperham** [comment]
it’s possible that inline only works with sidekiq jobs, not active jobs.

**Comment by ttrmw** [comment]
Ah fair.. Would you recommend not using ActiveJob? I'm not especially wedded to it 😛

**Comment by mperham** [comment]
From my biased POV, AJ doesn't offer much value.
