### ISSUE TITLE
Rubygems sidekiq-pro gem submission

### ISSUE THREAD

**Issue by penguincoder** [mperham/sidekiq#3678]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Sidekiq Pro

Someone has uploaded a gem called "sidekiq-pro" to https://rubygems.org/gems/sidekiq-pro to spoof your paid gem. I use Sidekiq Enterprise with an implicit Sidekiq Pro dependency and this has caused by bundle install to fail unless I explicitly set the source of the Sidekiq Pro gem.

I am sure this is not your intended behavior.

**Comment by mperham** [comment]
```ruby
source "..." do
  gem "sidekiq-pro"
  gem "sidekiq-ent"
end
```
