### ISSUE TITLE
Persistent PSUBSCRIBE connections from Sidekiq Pro

### ISSUE THREAD

**Issue by mdehoog** [mperham/sidekiq#3682]
**Description**
We are having trouble with the number of connections to our Redis instance. We recently migrated to a new Redis instance, and noticed that our old unused Redis still has 5k connections. I performed a `CLIENT LIST` and everything came up as `PSUBSCRIBE` connections. Confirmed with:
```ruby
redis.client.call([:pubsub, :numpat])
=> 5629
```

I noticed that `Sidekiq::Pro::ConfigListener` is doing a `psubscribe` to support real-time config updates. Should there also be a corresponding `punsubscribe` to close the persistent connection?

**Versions**
Ruby version: 2.3.5
Sidekiq: 4.2.10
Pro: 3.5.3
Enterprise: 1.6.1

**Initializer**
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: SIDEKIQ_REDIS_URL }
  config.failures_default_mode = :exhausted
  config.average_scheduled_poll_interval = 10

  config.super_fetch!
  config.reliable_scheduler!
end

Sidekiq.configure_client do |config|
  config.redis = { url: SIDEKIQ_REDIS_URL }
end
```

**Comment by mperham** [comment]
Each Pro/Ent process opens one pubsub connection which stays around for the life of the process. Could those connections be for something else?  Run this:

```
PUBSUB NUMSUB sidekiq:config
```

to get the number of active Sidekiq pubsub connections.

**Comment by mdehoog** [comment]
I tried this, but both the number of subscribers and number of channels came back empty for both our old Sidekiq Redis and our current one in production.

```ruby
irb(main):009:0> redis.client.call([:pubsub, :numsub, "sidekiq:config"])
=> ["sidekiq:config", 0]
irb(main):010:0> redis.client.call([:pubsub, :channels])
=> []
```

**Comment by mperham** [comment]
Sounds like something is wrong with your setup then.  If you are running Sidekiq processes, there should be subscribers listening on that channel.

**Comment by mdehoog** [comment]
Thanks for your fast response, we will investigate further 👍

**Comment by mperham** [comment]
hmm, possibly using redis-namespace which is prefixing that channel name?
