### ISSUE TITLE
[feature request] Permit search worker in gems

### ISSUE THREAD

**Issue by zw963** [mperham/sidekiq#3686]
Hi, I want to write a gem, which create a sidekiq worker, always be used by our project again and again.

 is there any search PATH which can auto use the worker defined in my gem?

Thanks.

**Comment by mikegee** [comment]
If your gem is loaded by Bundler, it will be available to your application code. `SearchWorker.perform_async` should work. 

I don't understand what Sidekiq needs to do to help with this.

**Comment by zw963** [comment]
@mikegee , Thanks for know that.

But, how the correct folder structure for that?

e.g.  `lib/worker` or `lib/app/worker` or `app/worker`?

**Comment by mikegee** [comment]
Those things are not related to Sidekiq, just how Ruby gems work. I recommend closing this issue.

The worker can be defined where you like. Given a gem called 'your_gem', and an application's  `Gemfile` containing `gem 'your_gem'`, Bundler will add the `lib` directory inside your gem to Ruby's `LOAD_PATH`, then it will `require('your_gem')` to load the file `lib/your_gem.rb` inside your gem. That file (`lib/your_gem.rb`) may `require` the file that defines the worker whereever it is. It might contain a line: `require('your_gem/worker')` if the worker is defined in `lib/your_gem/worker.rb`.

That is more complicated than I hoped it would be when I started writing it. More documentation is available here: http://guides.rubygems.org/make-your-own-gem/

**Comment by mperham** [comment]
Yep, this has nothing to do with Sidekiq.  Sounds like you're new to Ruby; look into `require` and how gems load their code.

**Comment by zw963** [comment]
@mikegee , @mperham , sorry for heard for that I am new to ruby, in fact, i am not. : )

What I thought before create this issue is i guess sidekiq maybe can add some special `LOAD_PATH` 
for search worker file within, but, i forget I can add one worker file manually in my gem. whatever, i understood now, Thank all very much.
