### ISSUE TITLE
Resque Compatibility: Hooks

### ISSUE THREAD

**Issue by yaauie** [mperham/sidekiq#369]
The following job hooks are invokable by Resque; provide ability to create same hooks at an instance level:
- `before_enqueue` - returning `false` causes the job to not be enqueued
- `after_enqueue`
- `before_perform` - raising something like `DontPerform` causes the job to not be performed
- `around_perform` - each yields to the next, innermost yields a perform call
- `after_perform`
- `on_failure` - exception is passed as an argument

This would make it easier to build plugins for Sidekiq (or migrate existing ones) that are isolated and resilient.

**Comment by bsutherland** [comment]
For anyone else looking for this, here's what I've come up with so far:

```
# Instantiate an ActiveJob instance from the serialized job data
def deserialize_job(sidekiq_job_data)
  active_job = ActiveJob::Base.deserialize(sidekiq_job_data['args'].first)
end

class ClientCallbackMiddleware
  def call(worker, job_data, _queue, _redis_pool)
    activejob = deserialize_job(job_data)
    activejob.try(:before_enqueue)
    result = yield
    activejob.try(:after_enqueue)
    result
  end
end

class ServerCallbackMiddleware
  def call(_worker, job_data, _queue)
    activejob = deserialize_job(job_data)
    activejob.try(:before_perform)
    result = yield
    activejob.try(:after_perform)
    result
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add(ClientCallbackMiddleware)
  end
end

Sidekiq.configure_server do |config|
  config.client_middleware do |chain|
    chain.add(ClientCallbackMiddleware)
  end

  config.server_middleware do |chain|
    chain.add(ServerCallbackMiddleware)
  end
end
```
