### ISSUE TITLE
Documentation for older sidekiq versions?

### ISSUE THREAD

**Issue by AlexVPopov** [mperham/sidekiq#3693]
When keeping the documentation of Sidekiq in the wiki, it means that only the documentation for the latest version can be found. Example: in Sidekiq 4.0 it used to be possible to manually clear the retry set:

```ruby
Sidekiq::RetrySet.new.clear
```

This was documented in the wiki, but I guess, since this is no longer possible in version 5, this info has been deleted from the wiki.

What is a way to access documentation for older versions?

**Comment by mperham** [comment]
The wiki does reflect the latest versions and this is one incentive to keep up-to-date.  Your example is incorrect -- that code still works in Sidekiq 5.
