### ISSUE TITLE
restarting Sidekiq (Enterprise) periodically

### ISSUE THREAD

**Issue by steveburkett** [mperham/sidekiq#3697]
We have tons of jobs...some of them appear to leak memory...we're working to try to fix this, but in the meantime....  

w/ SKE, is there a way to either: 
(1) configure sidekiq to periodically restart itself when idle
(2) or signal SK to "come to a stop", then when idle, restart itself, periodically.  

Thanks! :)

**Comment by mperham** [comment]
For memory leaking and growth, this:

https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#memory-monitoring

Sidekiq does not have any autoscaling built-in, autoscaling is proprietary to each deployment environment, e.g. Heroku has their own support.

https://www.google.com/search?q=sidekiq+autoscaling&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
