### ISSUE TITLE
Getting different results each time on batch of batches.

### ISSUE THREAD

**Issue by myfitment** [mperham/sidekiq#3698]
Ruby version: 2.3.3p222
Sidekiq / Pro / Enterprise version(s): 5.0.4 / 3.4.5 / 1.5.2

Have also run with version:
5.0.5 / 3.6.0 / 1.6.1

Are you using an old version?
See above

Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes, I can't locate anything that says parent batches are firing on_complete prematurely. Possible "Fix edge case in Batch::Status#poll leading to premature completion [#3640]" I guess but again I haven't seen it in others.

I've done this setup about 50 times and I know it inside and out.

1) Parent worker chunks product objects
2) Parent worker creates a batch, and within the batch sends each chunk to a Child worker.
3) Child worker creates a batch of individual Worker jobs for each product in its chunk.
3) Worker gets information for individual product and writes it to redis. 
4) After Parent batch completes it fires on_complete, which collects data from redis and writes report file.

I have the craziest behavior in this new one I wrote. Sometimes when I run it, it's emtpy. Sometimes it has data for a product. But it's mostly empty. It's really maddening. I'm literally getting different results every single time.

There is some kind of state management issue, and after 16 hours I can't find it. Where should I look?

I guarantee that the on_complete method is firing too early though. Because I'm watching it fire while there are still Worker (3rd level) jobs going.

I have also tried this with the on_success method and the results are the same.

**Comment by mperham** [comment]
I don't have a good answer for you.  You can share your code and I can look it over for typical mistakes.  Different results for different runs usually implies a race condition in the batch job execution.

**Comment by foxtacles** [comment]
Unfortunately it is very easy to get something wrong if you are trying to build a complex workflow with Sidekiq Pro's batches, by my own experience. For example accidently appending a new child batch in a complete/success callback to the current batch instead of the parent batch (yielding hard to debug, undefined behaviour).

A working example is documented here: https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches maybe have a look at that.

**Comment by foxtacles** [comment]
Also verify you are not mixing complete/success callbacks in your dynamically expanding batches/child batches. It may not work like you think it does
