### ISSUE TITLE
Sidekiq Pro 3.6.0 statsd connection pool exhaustion

### ISSUE THREAD

**Issue by sj26** [mperham/sidekiq#3700]
Ruby version 2.4.2, Sidekiq Pro 3.6.0

We followed the upgrade advice and removed `:client` from `Sidekiq::Middleware::Server::Statsd` and replaced it by setting `Sidekiq::Pro.statsd` to a block. But this creates a connection pool with the default size (which [seems to be 5](https://github.com/mperham/connection_pool/blob/master/lib/connection_pool.rb#L35)) which is much less than our sidekiq concurrency (25), and because each worker is wrapped by a `statsd.time { ... }` call in the middleware it caused our jobs to start timing out.

We've solved it using:

```ruby
Sidekiq::Pro.statsd = ConnectionPool.new(size: Sidekiq.options[:concurrency]) { Datadog::Statsd.new }
```

But there might need to be some advice in the upgrade notes or docs to ensure the connection pool is big enough. We didn't realise there were any caveats when following the notes.

Thanks!

**Comment by mperham** [comment]
Oops, I had envisioned the client checkouts being very fast and not long running but that's one use case I missed.  3.6.1 will use the same "concurrency + 2" size that the redis pool uses.

**Comment by petergoldstein** [comment]
@mperham What's the timeline on 3.6.1?  The deprecation warnings are causing excessive hits on our logging infra, and we're blocked on eliminating because of this issue.  If 3.6.1 is a day or two away, we'll wait it out.  But if not we'll roll back to 3.5.x

**Comment by mperham** [comment]
What deprecation warning?

**Comment by mperham** [comment]
3.6.1 will be out today.

**Comment by mperham** [comment]
I see what you mean and removed the message.  3.6.1 is out.
