### ISSUE TITLE
Consider jid as a unique hash for all future execute background job?

### ISSUE THREAD

**Issue by zw963** [mperham/sidekiq#3702]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 4.2.10

Hi,  here have a feature i want to implement.

I want to add a job, this job will execute in the future one day.
but, I will maybe change this future date frequently, so, if i change to
a new deadline, i will expect previous is invalid.

so, what i want is:  bind active record object with job id, that is,
when i add a new delayed worker, i will write this job id to one
column, when feature invoke that job, i will validate that job id
with record job id, if matched, job is execute, otherwise, job just
do no-op.

so, that require we have a unique job id,  is this consider a better
solution?

Thanks.

**Comment by zw963** [comment]
Following is a example:

```sh
# enqueue
job_id = MyWorker.perform_async("test")
my_record.update(jid: job_id)
```

```rb
# in the worker

class MyWorker

   def perform(name)
      # find my my_record
       if my_record.jid == self.jid
            # do what i want
       else
           # no-op
       end
   end
end
```

Is those feature what as i want? thanks

**Comment by mikegee** [comment]
I've solved this problem in a very different way. I create database records with a `run_at` timestamp and every minute enqueue the jobs that have just become due (`run_at < now()`). This allows me to delete or reschedule the jobs with simple database operations rather than introduce complexity in the Sidekiq workers.

**Comment by zw963** [comment]
@mikegee , Cool, that help me a lot.

But, I am not see any code which `ensure run every minute`, how to archive this?

sidekiq has this feature?

**Comment by mperham** [comment]
@mikegee is correct, store and edit these "future work requests" within your database.  Create the jobs within Sidekiq only when they actually need to run.

Sidekiq does not have cron functionality built-in.  Sidekiq Enterprise does.

**Comment by mikegee** [comment]
@zw963 my employer licenses Sidekiq Enterprise. I suppose there are other ways to run a job every minute too.

**Comment by zw963** [comment]
@mperham , @mikegee , Thanks all, help me a lot.
