### ISSUE TITLE
Sidekiq 5.0.5 web ui not loading assets

### ISSUE THREAD

**Issue by AmazingMoon** [mperham/sidekiq#3703]
Ruby version: ruby 2.3.0
rails version: Rails 5.0.6
sidekiq version: Sidekiq 5.0.5

![image](https://user-images.githubusercontent.com/23205097/34316063-7789ae16-e7c8-11e7-8c94-440dca5b2f66.png)

**Comment by AmazingMoon** [comment]
[https://github.com/mperham/sidekiq/wiki/FAQ#why-dont-cssjsimg-assets-load-properly-when-i-go-to-sidekiqs-web-ui](url)
I found this solution but still did not solve the problem

**Comment by AmazingMoon** [comment]
https://github.com/mperham/sidekiq/wiki/FAQ#why-dont-cssjsimg-assets-load-properly-when-i-go-to-sidekiqs-web-ui

I found this solution but still did not solve the problem

**Comment by AmazingMoon** [comment]
@mperham

**Comment by mperham** [comment]
OSS has no guarantee of support. Please do not @ me. I saw your issue and have no idea what the problem is.

**Comment by AmazingMoon** [comment]
![image](https://user-images.githubusercontent.com/23205097/34331767-bbd726dc-e964-11e7-8675-0f99d2dc2d0a.png)
local is ok,however, assets can not be loaded after deploy.

**Comment by modusss** [comment]
I'm experiencing the exactly same problem here...
