### ISSUE TITLE
Sidekiq overriding the original job params when displaying

### ISSUE THREAD

**Issue by camol** [mperham/sidekiq#3706]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.0.5 / Sidekiq Ent 1.6.1

Hi,

I've encountered an issue when trying to use the ent feature `encrypt`. I was always getting `[encrypted data]` for my "secret bag" params. The place which actually is responsible for setting this string is [here](https://github.com/mperham/sidekiq/blob/v5.0.5/lib/sidekiq/api.rb#L354). This line in fact is overriding the original arguments for me and when I check the "secret bag" inside the job after the decryption process I'm getting the `[encrypted data]` which means that this stuff is getting encrypted in first place.

When I comment out this line I won't see `[encrypted data]` in the web ui (which was the original purpose of it) but my jobs are getting the proper arguments.

By looking at the code I see that previous lines are not modifying anything just creating something new. But this line is in fact modifying this stuff. I'm just curious why I'm getting this because I would expect that anyone who uses the `encrypt` feature is getting this.

PS.

I posted this issue here because the code responsible for my issue comes from the Sidekiq API.

**Comment by mperham** [comment]
That line overrides the args in the Sidekiq::Job instance that Sidekiq::Web is showing in that data table.  It has no effect on the job data in Redis or what is passed to the worker when executing the job.  My guess is that you are doing something unexpected and unsupported with the Sidekiq API.

**Comment by camol** [comment]
It might seem like. But I do not do anything more than the example on the Sidekiq wiki page shows.

**Comment by mperham** [comment]
If you can give me sample code that reproduces the problem, I will look deeper.

**Comment by camol** [comment]
The part of the Sidekiq config related to that:

```
Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  File.open("./config/crypto/secret.#{Rails.env}.#{version}.key").read
end
```

Sample job code:

```
class LinkAccount
  include Sidekiq::Worker
  sidekiq_options queue: 'account', encrypt: true

  def perform(account_id, type, credentials)
    
  end
end
```

Scheduling the job:

```
LinkAccount.perform_async 1, "spending", Hashie::Mash.new(a: "A", b: "B")
```

**Comment by mperham** [comment]
The feature works perfectly fine in my testing.

1. Create an encrypted job.
2. Look in Web UI, shows "encrypted data".
3. Start Sidekiq, prints the expected bag contents inside the job.

**Comment by alecgorge** [comment]
For what it is worth, I cannot create a small reproduction case yet but I see this issue as well when I am enqueuing an encrypted job from a job that is not encrypted.

Commenting out the line in api.rb fixes everything for me as well. I'll post more if I find out anything else.

**Comment by alecgorge** [comment]
When I call `perform_async` on an encrypted worker it hits the branch in `api.rb` (379 is a print line I added) that anonymizes things:

![image](https://user-images.githubusercontent.com/261668/66246532-9e4a5f80-e6c9-11e9-9ac8-dd3fdac686c9.png)

This caused the value `[encrypted data]` to be encrypted and stored in redis. When the job is run, it appropriately decrypts the data and passes that literal string `"[encrypted data]"` to the method.

The real issue is that the [Sidekiq::Status](https://github.com/utgarda/sidekiq-status) plugin [calls `display_args`](https://github.com/utgarda/sidekiq-status/blob/master/lib/sidekiq-status/client_middleware.rb#L38) which then calls down into the base implementation of `display_args`.

Making my jobs that need encryption bypass calling `include Sidekiq::Status::Worker` has fixed the issue for me.

I have filed a bug on that repo: https://github.com/utgarda/sidekiq-status/issues/153

**Comment by mperham** [comment]
Can you replace your sidekiq-status usage with Batches instead?

**Comment by alecgorge** [comment]
I hadn’t considered that. We just started implementing the enterprise features today.

Are you suggesting we use batches of 1 job to get the status reporting?

**Comment by mperham** [comment]
With one big job it’s not really useful but if you can break the big job into a batch of smaller jobs, you can track the status of the group.

**Comment by alecgorge** [comment]
In our case, the job we want to encrypt is one of the smaller jobs unfortunately so I think we'll probably just stick with not using `Sidekiq::Status` for now

**Comment by kimyu92** [comment]
```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_client do |config|
  Sidekiq::Status.configure_client_middleware config
end

Sidekiq.configure_server do |config|
  Sidekiq::Status.configure_server_middleware config
  Sidekiq::Status.configure_client_middleware config
end

# worker
class Workers::Foo
  include Sidekiq::Worker
  include Sidekiq::Status::Worker

  sidekiq_options queue: 'default', retry: 0, encrypt: true

  def perform(a, secret_bag)
    puts secret_bag
  end
end

# caller
Workers::Foo.perform_async('a', { secret: 'bar' })
```

@mperham any insight on this issue? Maybe instead of middleware calling `display_args`, any suggestion for middleware to hook in without getting this decryption issue?

**Comment by mperham** [comment]
If you order the middleware correctly, you can see the unencrypted data. The ordering of the chains is critical.

**Comment by kimyu92** [comment]
> If you order the middleware correctly, you can see the unencrypted data. The ordering of the chains is critical.

Sorry, do you mind to share how I could order my middleware differently other than the sample that I posted above?

**Comment by mperham** [comment]
The Middleware wiki page should be your starting point:

https://github.com/mperham/sidekiq/wiki/Middleware#middleware-ordering

**Comment by mperham** [comment]
If this is a client-side issue, specifically you'll use the `insert_before` API to ensure the status middleware is placed before the encryption middleware in the chain.

**Comment by kimyu92** [comment]
> If this is a client-side issue, specifically you'll use the `insert_before` API to ensure the status middleware is placed before the encryption middleware in the chain.

Glad to know I could potentially utilize `insert_before`, what is the middleware for encryption? `Sidekiq::Enterprise::Crypto`?

Is that what you suggested?
```ruby
Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.insert_before Sidekiq::Enterprise::Crypto, Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq.configure_server do |config|
  config.client_middleware do |chain|
    chain.insert_before Sidekiq::Enterprise::Crypto, Sidekiq::Status::ClientMiddleware
  end
end
```

**Comment by mperham** [comment]
The middleware chains are printed out when you start Sidekiq with `-v`. Yes, your code will adjust the ordering, except the names are wrong, use `-v`. I don't know the exact issue with Sidekiq::Status so I can't confirm if that's the correct fix.

**Comment by kimyu92** [comment]
Using the verbose mode, show server/client middlewares are indeed before `Sidekiq::Enterprise::Crypto::Server` and `Sidekiq::Enterprise::Crypto::Client`. Does it need to be before batch client?

```ruby
Sidekiq::Batch::Client,
Sidekiq::Status::ClientMiddleware
Sidekiq::Enterprise::Crypto::Client

Sidekiq::Limiter::Middleware,
Sidekiq::Batch::Server,
Sidekiq::Status::ServerMiddleware,
Sidekiq::Enterprise::Crypto::Server
```

**Comment by mperham** [comment]
i assume the status server middleware needs to come after crypto if it needs access to the args.

**Comment by kimyu92** [comment]
Thanks @mperham for your help 🙏 . 

The setup below seems to solves the problem, I have watched the redis queue receiving encrypted payload for last argument and have seen the worker decrypting the right value. Potentially prepend could resolve the issue as well 🤔 but not tested with it.

```ruby
# initializers/sidekiq
Sidekiq.configure_client do |config|
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.insert_before Sidekiq::Enterprise::Crypto::Server, Sidekiq::Status::ServerMiddleware
  end

  config.client_middleware do |chain|
    chain.insert_before Sidekiq::Enterprise::Crypto::Client, Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  File.read(Rails.root.join('my1.key'))
end
```


```ruby
# client middleware
Sidekiq::Status::ClientMiddleware
Sidekiq::Batch::Client
Sidekiq::Enterprise::Crypto::Client

# server middleware
Sidekiq::Status::ServerMiddleware
Sidekiq::Limiter::Middleware 
Sidekiq::Batch::Server
Sidekiq::Enterprise::Crypto::Server
```

**Comment by mperham** [comment]
you want to use insert_after for the server middleware

**Comment by kimyu92** [comment]
> you want to use insert_after for the server middleware

I have tried insert status middleware behind crypto and experience the same issue that decryption would work but I can see sidekiq job without args and argument on sidekiq-status page. 

Also, worth mentioning, `insert_after` itself won't place the crypto behind, it requires me to move up the `Sidekiq::Enterprise::Crypto` block before `Sidekiq.configure_server` in order to change the behavior of crypto middleware always be the last middleware

**Comment by mperham** [comment]
Ah, ok. If it works for you, ignore me. 😎
