### ISSUE TITLE
sidekiq-pro rubygems mirror makes bundler very slow

### ISSUE THREAD

**Issue by mathieujobin** [mperham/sidekiq#3707]
Ruby version: 2.4.2 and 2.3.5

Sidekiq / Pro / Enterprise version(s): Pro 3.6.1

encountered this issue

https://github.com/bundler/bundler/issues/6216

isolated this is happening because I load sidekiq-pro with a source block like this

```
source "https://LOGIN:PASWORD@gems.contribsys.com/" do
  gem 'sidekiq-pro', '~> 3.0'
end
```

does not happen when I load the source on the top

```
source "https://LOGIN:PASWORD@gems.contribsys.com/"
gem 'sidekiq-pro', '~> 3.0'
```

but I like the idea that this source is only use for this one gem.

this leads to `bundle update` taking several minutes, from 8 to up to 24 minutes
while without it, it runs under 1 minute

I tried to reproduce without including sidekiq-pro with other rubygems mirrror without success.

its likely a bug on bundler, but since I can only reproduce with your source, I thought of opening an issue here as well.
maybe you just need to refresh your mirror ?

see the link issue for more details

thanks

**Comment by mperham** [comment]
I don’t see what I could do to fix this issue but I can give the Bundler team a temporary credential if they want to reproduce the problem privately. They are welcome to contact me by email.
