### ISSUE TITLE
monit restart script for memory leaks/bloat

### ISSUE THREAD

**Issue by steveburkett** [mperham/sidekiq#3708]
does someone have a production monit script i can use as a start for Sidekiq?

for us...we have tons of big (nasty) jobs that leak memory...so the script needs some robustness built in to keep things rolling (restarting sidekiq due to memory problems).

in the background...we'll try finding where these big jobs are having problems....but need a good example to use for monit to keep sidekiq up and running and restarting when memory gets bad.

on this topic...is there a feature of PRO/ENT that signal SK to restart itself once some criteria is met (like mem over 3G) ONCE it comes idle?  the issue we have are these super long running jobs that eat up memory (and may be difficult to figure out, we dont know yet)...but at least would like SK having the smarts to be able to keep itself up and running.

**Comment by mperham** [comment]
If you use the [shutdown_pending hack documented here](https://github.com/mperham/sidekiq/wiki/Deployment#events), you can use Ent's Multi-process memory monitoring feature to cleanly shutdown and restart long-running jobs.  The job must periodically check if the process is stopping though.
