### ISSUE TITLE
Queue Priorities

### ISSUE THREAD

**Issue by sirwolfgang** [mperham/sidekiq#3709]
Ruby version: 2.3.0
Sidekiq / Pro / Enterprise version(s): 5.0.4 / 3.5.1 / 1.6.0

Looking at the [documentation](https://github.com/mperham/sidekiq/wiki/Advanced-Options) our interpretation is that non-bracketed queues should process and complete before moving into bracketed/weight queues. However, with the deployed settings as defined below, we are seeing our critical queue not empty before lower jobs are processed. Is this behaving as expected?

```yaml
:queues:
  - critical
  - [high,    4]
  - [default, 2]
  - [low,     1]
  - apathetic
```

**Comment by mperham** [comment]
The two schemes are mutually exclusive.  If you have **any** queue weights specified, the default weight is 1.  In your example, critical and apathetic are weighted the same as low; the behavior is expected.
