### ISSUE TITLE
Sidekiq::Batch & Sidekiq::Shutdown Callback Behavior

### ISSUE THREAD

**Issue by mullen3** [mperham/sidekiq#3710]
Ruby version: 2.1.2
Sidekiq / Pro / Enterprise version(s): 4.2 / 3.6.0 / 1.6.1

Opening an issue because I'm not entirely clear if the current behavior is expected.

We're using `Sidekiq::Batch` and have implemented our own manual retries due to the way `Sidekiq::Batch` callbacks play with retries (see https://github.com/mperham/sidekiq/issues/2250, https://github.com/mperham/sidekiq/issues/3615). As suggested in #2250, we have disabled retries in our batch jobs and manually requeue our own unit of work to avoid the `:complete` being called as soon as a single job fails.

This has worked well for application failures, but we're still dealing with some undesirable behavior when a `Sidekiq::Shutdown` is raised. As documented, the `Sidekiq::Shutdown` requeues any jobs that were running during shutdown. It doesn't seem like the jobs that are interrupted due to a shutdown are treated as failures. This makes sense conceptually because the jobs did not fail, they were just interrupted. However, the batch `:complete` callback still is being fired with the failure from the shutdown.

Is this the expected behavior? If so, do you have any suggestions of how to work around this? We could rescue the Sidekiq::Shutdown and requeue the work as we did for other failures, but the documentation explicitly says not to do so.

**Comment by mperham** [comment]
To be clear, the root issue is that jobs which die after running out of retries don't trigger the :success callback and the :complete callback is too early (doesn't give the jobs time to retry and succeed)?

 I'll think about how best to handle this case.  It may be the best solution is a new callback, e.g. :unsuccessful, which is "success but with 1 or more job deaths".

Have you maximized the amount of time you wait before forcing shutdown during a deploy?

**Comment by mullen3** [comment]
Thanks for the quick response @mperham.

The work-a-round that we implemented is due to the root issue that you flagged, which is that `:complete` fires before jobs have exhausted retries. Ideally there'd be a callback that fires when a batch is either successful or dead, but I understand the reasons for this limitation and was more asking about the specific shutdown behavior. 

I think that jobs which are shutdown should be treated as a NOOP. They neither failed nor succeeded. AFAIK, this is how the retry code treats them, but this is not mirrored by the batch callbacks. I think that adding a special catch and noop for a `Shutdown` exception in the Batch middleware would make the behavior more consistent (similar to how the retry middleware does: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_retry.rb#L75)

**Comment by mperham** [comment]
I've been working on this for the past hour.  Would you be interested in beta testing a preview release which handles Sidekiq::Shutdown gracefully?

Also, I think I've tracked down the race condition that leads to the infamous "negative pending batch" bug and have a fix for it too.

**Comment by mullen3** [comment]
Awesome! Yes I'd be willing. Would I be able to look at the diff before using the preview release? Happy to take this to email if that makes this easier to coordinate.

**Comment by mperham** [comment]
Yes, please email.

**Comment by mullen3** [comment]
Sounds good. Sent you an email.

**Comment by philipbjorge** [comment]
@mperham -- Have you found a fix for the infamous negative pending batch?
We'd be interested in testing it.

**Comment by mperham** [comment]
@philipbjorge The reports of negative pending have greatly diminished since the fix in Pro 3.7.0.  If you're running an earlier version, definitely upgrade.
