### ISSUE TITLE
NameError: uninitialized constant ScheduledtaskJob(MyJob)

### ISSUE THREAD

**Issue by KiranAdroit** [mperham/sidekiq#3711]
I am getting following error when I enque new job. 
NameError: uninitialized constant ScheduledtaskJob

But the strange thing is, I am executing same job multiple times then also sometimes it works and sometimes it is not. Not getting actually what is happening. I have also included following line in application.rb.
And also, It is working fine in development server but not working in production.

config.eager_load_paths << Rails.root.join("app","workers","scheduledtask_job") and also tried with autoloads_path but both seems to not work.

I have created following Worker

class ScheduledtaskJob
    include Sidekiq::Worker
    include Sidekiq::Status::Worker
    sidekiq_options :retry => 5
 .
 .
 .

end

Help needed!

**Comment by mperham** [comment]
1. Don't ever touch Rails's paths.
2. Try master and see if that helps.  There was a fix for constantize.
