### ISSUE TITLE
Deadlock with Sidekiq::Testing

### ISSUE THREAD

**Issue by heaven** [mperham/sidekiq#3713]
Hi, we have the following case:
```ruby
Sidekiq::Testing.inline! do
  job.approved!(:offline_payment => true)
end
```

Once a job is approved it schedules a delayed job, but `#inline!` performs jobs from the scheduled set as well. And that would be okay unless this scheduled job did re-schedule itself. So we have a job that is scheduled during the approval and re-schedules itself endlessly.

I can stub the method that re-schedules the job to avoid the recursion but was thinking it would be great to have a better flexibility and ability to run jobs individually or at least to specify whether to run scheduled jobs along with queued and how many jobs to run.

**Comment by mperham** [comment]
No plans to fix this.  Structure your tests to remove this cyclical scheduling.
