### ISSUE TITLE
Uninitialized constant Sidekiq::Util

### ISSUE THREAD

**Issue by interpegasus** [mperham/sidekiq#3714]
Hi, 

First thank you for a great library. 

I get an exception via the latest sidekiq 5.0.6.

**Ruby version:**
interpreter:  "ruby"
    version:      "2.3.3p222"
    date:         "2016-11-21"
    platform:     "x86_64-darwin16"
    patchlevel:   "2016-11-21 revision 56859"
    full_version: "ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]"

**Backtrace**
{"status":500,"exception_message":"uninitialized constant Sidekiq::Util","exception_backtrace":["/home/deploy/.bundler/pico_sports/ruby/2.3.0/bundler/gems/sidekiq-a9c939218b1d/lib/sidekiq/logging.rb:14:in `call'","/usr/local/lib/ruby/2.3.0/logger.rb:546:in `format_message'","/usr/local/lib/ruby/2.3.0/logger.rb:434:in `add'","/usr/local/lib/ruby/2.3.0/logger.rb:498:in `warn'","/home/deploy/.bundler/pico_sports/ruby/2.3.0/bundler/gems/sidekiq-a9c939218b1d/lib/sidekiq/extensions/generic_proxy.rb:24:in 

**Initializer**
```
Sidekiq::Extensions.enable_delay!

if File.expand_path(File.dirname(__FILE__)).include? "MYAPPNAME"
	db_number = '0'
elsif File.expand_path(File.dirname(__FILE__)).include? "MYAPPNAME_DEV"
	db_number = '1'
else
	db_number = '2'
end

if ['development','devlocal','local'].include? Rails.env
	Sidekiq.configure_server do |config|
		config.redis = { url: 'redis://localhost:6379/' + db_number, network_timeout: 3 }
	end
	Sidekiq.configure_client do |config|
		config.redis = { url: 'redis://localhost:6379/' + db_number, network_timeout: 3 }
	end
else
	Sidekiq.configure_server do |config|
		config.redis = { url: 'redis://MYSERVER.nzyxma.ng.0001.use1.cache.amazonaws.com:6379/' + db_number, network_timeout: 3 }
	end
	Sidekiq.configure_client do |config|
		config.redis = { url: 'redis://MYSERVER.nzyxma.ng.0001.use1.cache.amazonaws.com:6379/' + db_number, network_timeout: 3 }
	end
end

Sidekiq.default_worker_options = {
	backtrace: true,
	unique: :until_executing, unique_expiration: 10, # 10 minutes
	# unique_args: ->(args) { [ args.first.except('job_id') ] }
}
SidekiqUniqueJobs.config.unique_args_enabled = true
```

**Are you using an old version?**
It was working fine via sidekiq 5.0.4. But not 5.0.6.

Thanks

**Comment by mperham** [comment]
I see the problem but I need the full backtrace.

You are trying to create a very large delayed job.  Sidekiq is trying to log a warning about its size but a recent logger change made the logger only work in the Sidekiq server process.
