### ISSUE TITLE
Rails Model is not recognized into perform method

### ISSUE THREAD

**Issue by RuanHerculano** [mperham/sidekiq#3722]
Ruby version: 2.3.1
Sedekiq: 5.0.5

Im create the directory `app/workers`, and create into directory the file `clean_posts.rb`.
Right after, add the down code for this file.
  
```ruby
# app/workers/clean_posts.rb
class CleanPosts
  include Sidekiq::Worker
  # sidekiq_options :queue => :background

  def perform
    # Post model is not recognized
    # Error: "WARN: NameError: uninitialized constant Post"
    ::Post.recent.destroy_all
  end
end
```

Import the created directory.
```ruby
# config/application.rb
config.autoload_paths << Rails.root.join('app', 'workers')
```
Run with this command:
`bundle exec sidekiq -r ./app/workers/clean_posts.rb`

And the following error happened:
`WARN: NameError: uninitialized constant Post `

**Comment by mperham** [comment]
You have not booted Rails, you've loaded an individual Ruby file with `-r`.  It must require everything it needs or you need to boot Rails.

**Comment by mperham** [comment]
> config.autoload_paths << Rails.root.join('app', 'workers')

Pro-tip: Don't ever touch Rails paths.  Ever.
