### ISSUE TITLE
Namespaced workers question

### ISSUE THREAD

**Issue by paxer** [mperham/sidekiq#3723]
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): 5.0.5

Hi,

I have a parent application, which is Rails 5.1 and a Rails Engine which is namespaced as let's say MyEngine. I would like to use Sidekiq from the parent Rails application but have workers namespaced inside my Rails engine. So, I've created a worker like this inside my Rails engine app/workers folder and included sidekiq as a dependency.

```
module MyEngine
  module SomeNamespace
    class CreateSomethingWorker
      include Sidekiq::Worker
      
      def perform(name, count)
        # do something
      end
    end
  end
end
```

When I start my parent application (my Rails engine is mounted to it) I can start worker from the console or app code like `MyEngine::SomeNamespace::CreateSomethingWorker.perform_async` and it get's pushed to Redis correctly, however after that I've got an error which I see in Retry tab 

```
uninitialized constant SomeNamespace::CreateSomethingWorker
```

so seems like Sidekiq expect that my engine worker will be not namespaced like all other workers  in the parent application, but with the engine it does not work as all engine classes are namespaced even if I remove  my custom `SomeNamespace` and leave only `MyEngine:: CreateSomethingWorker `

The question - is there a way to specify a worker class/namespace for a queue in the configuration file or during an initialisation of a worker? Ideally I would like to use the same Sidekiq/ Reds instance as the parent application, but just a different queue for my engine workers. My parent application already have workers but I need to have a separate namespaced workers in my rails engine which still use parent application Sidekiq process and Redis instance if it is possible of course.

**Comment by mperham** [comment]
Try master.

**Comment by paxer** [comment]
@mperham thank you very much! It works with 5.1 (current master)
