### ISSUE TITLE
Sidekiq enterprise periodic job does not respect worker queue configuration

### ISSUE THREAD

**Issue by AlexMooney** [mperham/sidekiq#3726]
Ruby version: 2.2.2p95 🤦‍♂️ 
Sidekiq / Pro / Enterprise version(s): 5.0.4 / 3.5.2 / 1.6.0

Please include your initializer and any error message with the full backtrace.

```ruby
# config/initializers/sidekiq.rb
require 'sidekiq-ent/web'

Sidekiq.configure_server do |config|
  config.reliable_fetch!
  config.redis = ConnectionPool.new(size: Sidekiq.options[:concurrency] + 2, timeout: 1) do
    RedisSentinelWrapper.redis
  end
  config.average_scheduled_poll_interval = 1

  config.server_middleware do |chain|
    chain.add SidekiqMiddlewares::StatsMiddleware
  end

  config.periodic do |mgr|
    App::JOBS.each do |job, job_config|
      next if job_config.nil?

      next unless job_config.include? :crontab
      mgr.register(job_config[:crontab], job.to_s)
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: Sidekiq.options[:concurrency] + 2, timeout: 1) do
    RedisSentinelWrapper.redis
  end
end

if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    Sidekiq.configure_client do |config|
      config.redis = ConnectionPool.new(size: Sidekiq.options[:concurrency] + 2, timeout: 1) do
        RedisSentinelWrapper.redis
      end
    end if forked
  end
end

Sidekiq::Extensions.enable_delay!
```

```yaml
# config/app.yml
…
JOBS:
  PeriodicWorker:
    key: 'some_config'
    crontab: "15 0 * * *"
…
```

```ruby
# app/jobs/periodic_worker.rb
class PeriodicWorker
  include Sidekiq::Worker
  sidekiq_options queue: 'long_job', retry: 4 # about 5 minutes of retrying
  
  def perform
    sleep 600 # this worker takes a long time, so we want it to only run on the `long_job` queue
  end
end
```

I expect that `PeriodicWorker` will be run on the `long_job` queue by virtue of the `sidekiq_options` line in the class definition, but it is actually run on the `default` queue.  If I modify the `mgr.register` line in the initializer to add the `queue: 'long_job'`, then it works as expected.  The documentation [here](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#definition) says (emphasis mine):
> Periodic job options will **override** any options set with `sidekiq_options` within the Worker class.

This leads me to believe that there is a bug in the scheduling mechanism because the options from within the worker are seemingly ignored.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?
> None of the change longs seem to address this issue.

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
You need to pass the actual class.

> mgr.register(job_config[:crontab], job)

**Comment by AlexMooney** [comment]
Thanks for your prompt help!  `mgr.register(job_config[:crontab], job.to_s.constantize)` worked.
