### ISSUE TITLE
CLI does not fail if specified config file specified doesn't exist

### ISSUE THREAD

**Issue by thbar** [mperham/sidekiq#3735]
I've been surprised by the behaviour so I just wanted to ask if this is by design. Thanks!

Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.0.0

While setting up a sidekiq install, I noticed that if one passes a config file like this:

```
bundle exec sidekiq -C config/foobar.yml -r ./setup/boot.rb
```

with `foobar.yml` an non-existent file, Sidekiq will start anyway & will default to the default configuration.

Note that creating the file then running with `--verbose` I can see the options (e.g. concurrency) taking effect.

**Comment by mperham** [comment]
It is by design so things like capistrano-sidekiq can point to a file, even if it doesn't exist.  You can make a case that there should be a warning.

**Comment by thbar** [comment]
I wondered about that - indeed it's convenient when a systemd config refers to it but it's not there yet, I was pretty sure that was the reasoning behind that.

Thanks for the clarification - just wanted to make sure I hadn't missed anything.

I'm going to go ahead and close this. Thanks!

**Comment by alxgsv** [comment]
I've just shot myself in a leg because of this. Created config file for separate queue with typo in it's name several days ago and launched sidekiq. Today I found out that sidekiq has been running with default config all these days :-(

**Comment by mperham** [comment]
I think we can add logic to raise if the user supplies a -C param and it doesn’t exist.

**Comment by mperham** [comment]
PRs welcome, this should be relatively easy to implement.
