### ISSUE TITLE
Sidekiq.server? returns Constant

### ISSUE THREAD

**Issue by cmer** [mperham/sidekiq#3736]
Ruby version: 2.5
Sidekiq / Pro / Enterprise version(s): OSS

As described here: https://stackoverflow.com/questions/28367069/how-can-i-detect-whether-my-code-is-running-inside-sidekiq-server-or-puma

`#server?` returns "constant" instead of a boolean.

**Comment by mperham** [comment]
It's normal for predicate APIs (ones with ?) to return truthy values, not boolean.  This is not a bug.
