### ISSUE TITLE
[Wiki/Docs] Pro Metrics statsd syntax clarification

### ISSUE THREAD

**Issue by tjschuck** [mperham/sidekiq#3740]
This is a question regarding the info in these three places:

* This wiki page: https://github.com/mperham/sidekiq/wiki/Pro-Metrics
* This blog post: http://www.mikeperham.com/2017/12/11/sidekiq-pro-statsd-support----new-and-improved/
* This release note: https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#360

Currently, the code sample on the top of the Wiki page is:

```ruby
require 'dogstatsd-ruby'
Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new("metrics.example.com", 8125) }

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end
end
```

Should it be updated to be:

```ruby
require 'dogstatsd-ruby'
Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new("metrics.example.com", 8125) }
```

```ruby
require 'statsd-ruby'
Sidekiq::Pro.statsd = ->{ ::Statsd.new("127.0.0.1", 8125) }
```

_i.e._ both with a new syntax for initializing "normal" statsd, and also with the two examples broken apart to indicate that they're separate setups for two different tools?

Mostly just trying to figure out if the `Sidekiq::Middleware::Server::Statsd` style of setup is deprecated in favor of the `Sidekiq::Pro.statsd` style instead.

Thanks!

**Comment by mperham** [comment]
Dogstatsd is the recommended client so that final block with `statsd-ruby` is supported but not recommended.

The code sample at the top of the wiki is correct.  Most importantly, you need to set the global dogstatsd instance.  Since per-job metrics via the middleware are optional, you need to enable them as a second step.

**Comment by tjschuck** [comment]
I guess I don't understand how you're currently supposed to configure non-Datadog/dogstatsd "vanilla" statsd, then.

Right now, in our app on Sidekiq 4.2.10, we're doing the following to configure statsd:

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd, client: Stats
  end
end
```

where `Stats` is our global statsd instance (via `Stats = Statsd.new(...)` in our statsd initializer).

Should that be updated to use `Sidekiq::Pro.statsd = ->{ Stats }` instead of the `client: Stats` argument in Sidekiq 5?  Is that a breaking change going from SK 4 to 5 or just a deprecated method of getting the statsd client into the middleware?

**Comment by mperham** [comment]
`Should that be updated to use Sidekiq::Pro.statsd = ->{ Stats } instead of the client: Stats `

No, it's a terrible idea to use a global singleton and will kill scalability.  Let Sidekiq create and pool the clients for you.

` Is that a breaking change going from SK 4 to 5 or just a deprecated method of getting the statsd client into the middleware?`

It's deprecated and will print a warning.

Side note: this has nothing to do with Sidekiq.  This is all in Sidekiq Pro.

**Comment by tjschuck** [comment]
Thanks for clarifying.

By the way, looking at the source of Pro 3.7.0, using the `:client` option is only deprecated with a comment and it does _not_ print a warning, which would have helped clarify this issue.

**Comment by mperham** [comment]
Oops, my mistake, thanks.

**Comment by jamtur01** [comment]
There is a change that needs to be made here. The require:

```
require 'dogstatsd-ruby'
```

Should be:

```
require 'datadog/statsd'
```

**Comment by mperham** [comment]
@jamtur01 Thank you, fixed.

**Comment by mrsimo** [comment]
I see my colleague @tjschuck already opened this some time ago, I guess trying to update our other app. I've tried using `Sidekiq::Pro.statsd = -> { ... }` and I'm getting an error, which I'll do some research but I'm pasting the stack trace at the end of this comment.

I just wanted to mention the slight disappointment that this got deprecated. We've been merrily running sidekiq and have run a few billion jobs so far, all very nicely. 

I don't know if we'll ever migrate to dogstatsd... but doesn't seem very likely. It's the first time I personally hear about it. Isn't statsd way more widely used than dogstatsd? I mean, even if dogstatsd just extends statsd, we can't send dogstatsd metrics to standard statsd servers, right? I would have expected statsd to be supported by default, and maybe support some extra sauce on top of that if you use dogstats.

We can always implement the middleware on our own, of course, but it was just... so tidy! Here's a humble request for you to reconsider.

The previously mentioned stack trace:

```
2018-02-19T17:52:02.519Z 44400 TID-ow1wjx76o WARN: ArgumentError: comparison of Float with Hash failed
2018-02-19T17:52:02.519Z 44400 TID-ow1wjx76o WARN: /Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:466:in `<'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:466:in `send_stats'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:338:in `count'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:320:in `increment'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.0/lib/sidekiq/middleware/server/statsd.rb:46:in `block in call'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:71:in `easy'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/statsd-ruby-1.3.0/lib/statsd.rb:411:in `batch'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.0/lib/sidekiq/pro/metrics.rb:108:in `block in batch'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.0/lib/sidekiq/pro/metrics.rb:108:in `batch'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.0/lib/sidekiq/middleware/server/statsd.rb:45:in `rescue in call'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-pro-4.0.0/lib/sidekiq/middleware/server/statsd.rb:34:in `call'
/Users/albert/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
```

**Comment by mperham** [comment]
You're not imaging it; this looks like a bug.  My tests mocked out Statsd and I did integration testing with dogstatsd-ruby so I didn't have any integration testing with statsd-ruby.  I'll get a 4.0.1 out with a fix this week.

I understand the reluctance to change if something is working for you.  Part of my long-term Sidekiq maintenance is ensuring that the entire system is well supported and that includes all dependencies.  statsd-ruby is no longer maintained while dogstatsd-ruby sees regular maintenance and improvements, e.g. https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md  It has additional features (like tags and histograms) that other Sidekiq customers have been requesting.

Remember a deprecation is not a removal.  I generally give at least a year between deprecation and removal.  Statsd-ruby will be supported until Sidekiq Pro 5.0 so you have plenty of time to switch over (and my understanding is that the APIs are very, very similar, it might just drop in).

**Comment by mperham** [comment]
And my understanding is that the dogstatsd-ruby protocol is backwards compatible with the Statsd server so the upgrade is safe.  Some other Statsd-like servers (InfluxDB, etc) understand the more advanced features (tags, events, etc) in the protocol.

https://github.com/mperham/sidekiq/wiki/Pro-Metrics#importing-statsd

**Comment by mperham** [comment]
@mrsimo Monkeypatch workaround, put in your initializer:

```ruby
class Sidekiq::Pro::Metrics::Statsd
 def batch(&block)
  @statsd.with do |c|
    c.batch do
      yield self
    end
  end
 end
end
```

**Comment by mrsimo** [comment]
Thanks a lot for the mindful response, @mperham. I'll play around with datadog's gem, see if it works for us. Probably should've done some research first, too 💃 .
