### ISSUE TITLE
[Sidekiq Ent] Testing Sidekiq::Limiter in dev environment without redis

### ISSUE THREAD

**Issue by SeanDunford** [mperham/sidekiq#3741]
Hi, we just upgraded to sidekiq-ent. We run all our tests in CircleCi, we don't currently have Redis installed on those instances. In the past `Sidekiq::Testing.fake!` and `Sidekiq::Testing.inline!` has solved all of our needs. 

After upgrading I attempted to include a the new rate limiter api  `Sidekiq::Limiter` and it's giving us exceptions about connecting to Redis. What is the appropriate way to handle this situation? Is Redis required for the test environment? I've also looked https://github.com/mperham/sidekiq/wiki/Testing and don't see anything mentioning the Limiting API.

**OS**: reproduceable on all operating systems
**Ruby version**: 2.4.3
**Sidekiq / Pro / Enterprise version(s)**: 4.2.10 / 3.7.0 / 1.6.1

> app.rb
```
require 'rspec'
require 'sidekiq'
require 'sidekiq-ent'
require 'sidekiq/testing'

Sidekiq::Testing.fake!

redis_info = { url: nil, db: nil }
Sidekiq.configure_server do |config|
  config.redis = redis_info 
end

Sidekiq.configure_client do |config|
  config.redis = redis_info
end


Sidekiq::Limiter.concurrent('google_analytics', 2, wait_timeout: 5, lock_timeout: 30)
```

> Gemfile
```
source 'https://rubygems.org'

gem "rspec"
gem 'sidekiq', '5.0.5'

source 'https://enterprise.contribsys.com/' do
  gem 'sidekiq-ent'
  gem 'sidekiq-pro'
end
```
**command**: `bundle exec rspec app.rb`

**Error**:
```
Failure/Error: raise CannotConnectError, "Error connecting to Redis on #{location} (#{$!.class})"

Redis::CannotConnectError:
  Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
# ./app.rb:17:in `<top (required)>'
# ------------------
# --- Caused by: ---
# IO::EINPROGRESSWaitWritable:
#   Operation now in progress - connect(2) would block
#   ./app.rb:17:in `<top (required)>'
No examples found.


Finished in 0.00069 seconds (files took 0.30182 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
Are you using an old version? No.
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes.

**Comment by mperham** [comment]
Beyond basic `perform_async`, Sidekiq has never and will never support a mode of operation without Redis.  You'll need to mock things or install Redis.

**Comment by SeanDunford** [comment]
Thank you.
