### ISSUE TITLE
Sidekiq jobs getting duplicated after restart

### ISSUE THREAD

**Issue by maxwell** [mperham/sidekiq#3742]
Ruby version: 2.4.2
Sidekiq Open Source Version

Please include your initializer and any error message with the full backtrace.

Are you using an old version? sidekiq (4.2.10)
Have you checked the changelogs to see if your issue has been fixed in a later version?
yes

For some time, we've had some jobs that seemingly only have gotten queued once, but seem to have evidence that they ran twice for unknown reasons.  Today I caught a job that I know was only queued once (it was manually added by me), and yet showed up today as running multiple times.

<img width="1250" alt="sidekiq" src="https://user-images.githubusercontent.com/69663/35637099-0bb60c34-0668-11e8-9259-6a14e970aa56.png">

This job is a long-running data backfill.  Some jobs take 1 minute, some take many hours. The way I implemented this job was to pass a current shard to backfill, and a list of all shards which need to backfill in the future.  At the end of the backfill, I pop a shard ID off the list and start a queue a new job with the adjusted parameters.

Sometimes, our queues restart, which pops the job back to be queued, then Sidekiq reboots, and the job restarts.  It seems after my last restart, somehow either two jobs got re-queued, (my guess) or the job got pulled off multiple times.

I realize this is minimal info. Is there some logging or something I could hook into that might expose where/what is happening?  I feel like I just got finally lucky enough to have some sort of proof here, but it seems to have been happening to us for a bit.

Thank you very much.

**Comment by mperham** [comment]
I can't debug an anecdote.  You'll need to show actual code.

**Comment by maxwell** [comment]
No problem, thanks for the quick response.

```ruby
class BackfillRemoteUserIdWorker
  include Sidekiq::Worker

  sidekiq_options retry:false

  def self.initial_queue
   projects =  [1,2,3,4,5,6]
   perform_async(projects.pop, projects)
  end

  def perform(project_id, remaining_projects)
    @project = Project.find(project_id)

    #long running backfill code with lots of DB queries

    BackfillRemoteUserIdWorker.perform_async(remaining_projects.pop, remaining_projects)
  end
end
```

**Comment by mperham** [comment]
I don't see how you could be getting job dupes except possibly through the Redis client reconnect attempts, see #3303

**Comment by mperham** [comment]
any further data?
