### ISSUE TITLE
How to setup dedicated Sidekiq Server

### ISSUE THREAD

**Issue by Vipala** [mperham/sidekiq#3746]
I have a rails app which deployed on 2 ec2 instance with nginx and capistrano. For background job, I had used sidekiq with redis. I have 50 gb memory on server. I also have set max_pool_size to 50 of sidekiq concurrency. I want use one instance as a dedicated server for Sidekiq. How shall I do that?

**Comment by mperham** [comment]
Dupe of https://stackoverflow.com/questions/48584960/how-to-setup-dedicated-sidekiq-server
