### ISSUE TITLE
Sidekiq Job Prioritization/Job Bandwidth Usage

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3747]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 5.0.5

Got a particular tricky issue I'd like your advice on. Or if anyone with more experience customizing/advanced usage of Sidekiq has any ideas I'd love to hear it.

We process mass traffic from our clients and we have a limited set of resources -- basically one Sidekiq server.

I've finagled and configured as much as I can to try to get traffic to flow through as fast as humanly possible but I'm hitting the limits of our own hardware. What I'm leaning towards limiting how much of our bandwidth a certain client can take.
Does any paid level of Sidekiq allow me to do this even remotely easily?

I'd like to knowing we can process say 2000 transactions a minute that brand/client X can have 90% of that bandwidth but brand/client Y who pays us much less can have 10% of that bandwidth during heavy load.

I've thought about using queues but we have dozens of costumers and I know sidekiq performs well with a handful of queues not dozens.

Thanks for any help you might have! I know this is probably a instance of "sorry we don't support that" but I wanted to document my use case for future generations.

**Comment by mperham** [comment]
Have you looked into Enterprise's rate limiting feature?  You could limit a customer to X jobs/minute by using custom middleware + a per-customer limiter.

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting
