### ISSUE TITLE
Web interface calls conn._client for redis < 4

### ISSUE THREAD

**Issue by joofow** [mperham/sidekiq#3749]
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): 5.1.0

Please include your initializer and any error message with the full backtrace.
```
Redis::CommandError (ERR unknown command '_client'):

(eval):11:in `_erb__footer'
(eval):40:in `_render'
```
Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

Please note that many Rails users need to pin Redis version to 3.3.5 until ActionCable allows for use of Redis 4 (probably in 5.2)

When attempting to open the web inteface the `_footer.erb` calls `redis_connection_and_namespace` from `helpers.rb`. That in turn attempts to call `redis_connection` in the same file.

This currently attempts to use `conn._client` which will fail for Redis < 4. Could be resolved by using the same structure used in 'test_redis_connection.rb`:
```
    def redis_connection
      Sidekiq.redis do |conn|
        c = if conn.respond_to?(:_client)
              conn._client
            else
              conn.client
            end
        "redis://#{c.location}/#{c.db}"
      end
    end
```

**Comment by mperham** [comment]
It's fixed on master.
