### ISSUE TITLE
Sidekiq initializer crashes

### ISSUE THREAD

**Issue by Loschcode** [mperham/sidekiq#3750]
**Ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
Sidekiq : v5.1.0**

Hello guys,

I installed a fresh Sidekiq from your last release and added an initializer ...

```
Sidekiq.configure_server do |config|
  config.redis = {
    id: nil,
    url: ENV['REDIS_URL']
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    id: nil,
    url: ENV['REDIS_URL']
  }
end
```

Pretty casual, except it crashes with the following message when I try to reach the `/sidekiq` dashboard

> Redis::CommandError (ERR unknown command '_client'):
> 
> (eval):11:in `_erb__footer'
> (eval):40:in `_render

I solved the problem by downgrading to v5.0.5 so it might be a problem with the latest release.

Thanks for the good work ;)

**Comment by mperham** [comment]
Fixed on master.  5.1.1 will be out today.
