### ISSUE TITLE
How to test Sidekiq::Stats.new using rspec

### ISSUE THREAD

**Issue by bragboy** [mperham/sidekiq#3751]
Ruby version: `2.5.0`
Sidekiq Pro: `4.0.0` and Sidekiq: `5.1.1`
Are you using an old version? `No`
Have you checked the changelogs to see if your issue has been fixed in a later version? `Yes`

I have a method like this to test whether the queue is empty or not (I need it for a logical reason). These queues are named from `depth_0`, `depth_1`.. .. `depth_5`

```
  def queue_is_empty?
    stats = Sidekiq::Stats.new
    all_queues = stats.queues
    ((0..5).map{|i| all_queues["depth_#{i}"].to_i}.sum + stats.enqueued) == 0
  end
```

This works perfect and no problem. However, when I write a simple spec to test this, it is not taking the values from the test environment, rather it takes the queue stats from Live Redis server. 

```
  it 'should return true when no jobs are added to the queue' do
    Sidekiq::Worker.clear_all
    expect(queue_is_empty?).to be_truthy
  end
```

Can you please advise me how to test this?

**Comment by mperham** [comment]
Tests should test your code not my code.

**Comment by mikegee** [comment]
One way to accomplish the separation of app code from library code is dependency injection. This style has worked well for me:

```ruby
  def queue_is_empty?(stats: Sidekiq::Stats.new)
    all_queues = stats.queues
    ((0..5).map{|i| all_queues["depth_#{i}"].to_i}.sum + stats.enqueued) == 0
  end
```

With this method signature, it works the same as it did at runtime but your tests can provide a fake `Sidekiq::Stats` instance.

**Comment by bragboy** [comment]
@mikegee - I am satisfied with your solution. Thanks!
