### ISSUE TITLE
Sidekiq Unique Redis Error

### ISSUE THREAD

**Issue by tjohnell-handy** [mperham/sidekiq#3753]
Ruby version:
Sidekiq Enterprise version: 1.5.1

Please include your initializer and any error message with the full backtrace.

```
Redis::CommandError: ERR invalid expire time in set
from /Users/tjohnell/development/repos/handybook/.bundle/gems/redis-3.3.5/lib/redis/client.rb:121:in `call'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/redis-3.3.5/lib/redis.rb:752:in `block in set'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/redis-3.3.5/lib/redis.rb:750:in `set'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/unique.rb:94:in `block in call'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
from /Users/tjohnell/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/unique.rb:93:in `call'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
from /Users/tjohnell/development/repos/handybook/.bundle/bundler/gems/gem-logger-9eb09a26acb6/lib/sidekiq/sidekiq_client_middleware.rb:11:in `call'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
... 5 levels...
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/client.rb:206:in `process_single'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/client.rb:65:in `push'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/worker.rb:116:in `client_push'
from /Users/tjohnell/development/repos/handybook/.bundle/gems/sidekiq-4.2.9/lib/sidekiq/worker.rb:75:in `perform_in'
```

Hey, I do not have the latest enterprise which includes changes to the unique library in 1.6.0, but I wanted to share a bug I ran into.  I realized while looking through the Sidekiq Ent uniqueness code, that I could re-purpose it for the debounce functionality I so desperately need. I talked to you previously about the debounce gem here: https://github.com/mperham/sidekiq/issues/3440

Similar to the business use-case mentioned in https://github.com/mperham/sidekiq/issues/3471, I need a way to asynchronously offload expensive tasks, and if possible, avoid doing the work twice due to multiple subsequent requests.  The jobs are idempotent, but still very expensive.

I noticed if I were to utilize Sidekiq Ent's unique, with a `unique_for` set at 0 seconds, and then schedule jobs, let's say, 5 seconds into the future, I could avoid duplicate subsequent requests within a span of time until the original eventually executes.  Perfect for my use-case.  It also sounds very similar to the `unique_until: :start` use-case, so I'll make sure and update to check it out.

However, I wanted to point out, that if `unique_for` is set to 0 seconds, and `perform_in` is called with a 0 second delay, this results in a redis error due to attempting to set an expiration TTL of 0 seconds in Redis.  Obviously this is not a normal use-case, but if `perform_in` is being computed programmatically, it's not insane to think this could occur.

Best,
Tom

**Comment by mperham** [comment]
I don't think `unique_for: 0` is a valid value although I don't enforce that.  I would use `unique_for: 0.1` to avoid this edge case.  The scheduler isn't second-precise so you're not losing anything afaict.
