### ISSUE TITLE
Multiple instances 

### ISSUE THREAD

**Issue by myfitment** [mperham/sidekiq#3757]
Ruby version: 2.3.3p222
Sidekiq / Pro / Enterprise version(s): 5.1.1 / 4.0.0 / 1.7.0

Please include your initializer and any error message with the full backtrace.

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

I have several scheduled hourly jobs that are beginning to overlap. Then the same job with the same parameter ends up running 4 or 5 times simultaneously and causes exclusive locks in the database which grinds things to a halt. As you can see in the image below there are multiple instances of UserStatisticsGenerator running for the same user id. How can I avoid this:
![image](https://user-images.githubusercontent.com/2339454/36287226-90ec55d2-1281-11e8-88e4-ad3d0db1336b.png)

**Comment by mperham** [comment]
Wrap the job in a concurrent rate limiter with appropriate timeout.

**Comment by bobber205** [comment]
I had a similar issue and had to go what Mike is suggesting.

**Comment by mperham** [comment]
```ruby
def perform(user_id)
  Sidekiq::Limiter.concurrent(:"stats-#{user_id}", 1, lock_timeout: 90.minutes).within_limit do
    # do work
  end
end
```

Any sort of global lock will work, postgres has a similar feature. https://www.postgresql.org/docs/9.4/static/explicit-locking.html
