### ISSUE TITLE
is it possible to enable live polling by default with config file?

### ISSUE THREAD

**Issue by voordev** [mperham/sidekiq#3763]
Sorry for posting this here but could not find a solution anywhere.

Is it possible to enable live polling by default with config file?

**Comment by mperham** [comment]
Nope, that’s a browser thing, totally separate from Sidekiq.

**Comment by voordev** [comment]
Ok thank you for clarifying. I could not find anything online

**Comment by panchew** [comment]
The navigation links could have the ?poll=true by default per configuration value
