### ISSUE TITLE
Why there's a need to configure the client and server URLs separately?

### ISSUE THREAD

**Issue by bazinga012** [mperham/sidekiq#3764]
Can you please give me a use case where we would want to use different redis URLs for client and server? AFAIU  task data is pushed in redis instance corresponding to client setting and server pulls task data from redis instance corresponding to server setting but i'm not able to understand when would we want these two to be different?

**Comment by mperham** [comment]
90% of the time you shouldn't need to configure the URL at all.  Sidekiq can figure it out using `ENV['REDIS_PROVIDER']`.

Setting the URL in Ruby can be useful in cases where you are sharding across multiple Redises.

**Comment by mperham** [comment]
Show me your initializer and I'll show you how to properly configure it.
