### ISSUE TITLE
Serializable Enterprise Rate Limiters

### ISSUE THREAD

**Issue by ariens-shopify** [mperham/sidekiq#3767]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Ruby 2.3.3 Enterprise 1.6.1

Just a quick question hopefully about ent rate limiters.  Can limiters be created before the job, serialized and passed in as a job argument?

**Comment by mperham** [comment]
Sidekiq always has the same argument marshalling rules: JSON types only.  So nope, you can't pass any complex Ruby objects into your workers.

A rate limiter is identified only by its name and type, you could pass the name/type as arguments and construct the rate limiter dynamically within the worker.

**Comment by ariens-shopify** [comment]
If the name/type is provided (or otherwise derived) and each job then calls `Sidekiq::Limiter.bucket(limiter_name, 30, :second, wait_timeout: 30)` is that still considered expensive?  Would a map of limiter name/type to something shared/accessible globally on the job server be  a better approach?

**Comment by mperham** [comment]
The rate limiter is global and stored in Redis (how else could it work across all Sidekiq processes on different machines?) and there is no single "job server", unless you are referring to Redis.  The name/type is how Sidekiq can make calls to the rate limiter in Redis.  Every limiter creation in Ruby requires a trip to Redis to sync with the data in Redis and each call to within_limit requires a trip to Redis.

**Comment by ariens-shopify** [comment]
I should have been a little more specific.  By "job server" I was referring to a dedicated Sidekiq worker instance that runs 25 concurrent jobs. Let's say that my app has runs 10 of those workers that can all run 25 concurrent jobs, and there are a lot 5000K+ jobs enqueued.  At any given time there will be up to 250 jobs running.

My use case requires limiting Shopify API calls that are made within these jobs, certain jobs can execute 10s of API calls that we need to use a bucket limiter to ensure that we don't exceed 40 API calls per second.

The limiters being created and API rate limits are per Shopify shop, and the app makes calls against many shops.

I suppose the only optimization is to ensure that a given job only ever creates the limiter once, and then reuses it for every API call being made.  Since the concurrent threads cannot otherwise access shared limiters.

**Comment by mperham** [comment]
You are right that it's important to tune every network round trip with that level of traffic.  The easiest thing to do in your specific instance is to keep an in-memory cache of rate limiters, you can do something as simple as:

```ruby
def perform(...)
  # it's ok to use the thread-unsafe hammer operator here
  LIMITERS[customer_name] ||= Sidekiq::Limiter.bucket(:"api-#{customer_name}", 40, :second, ...)
  LIMITERS[customer_name].within_limit do
    # perform api call
  end
end
```
