### ISSUE TITLE
The Sidekiq jobs don't seem to running properly.  There are 4 server with a concurrency of 25 available.  The queue limits show that there should be more jobs running.

### ISSUE THREAD

**Issue by visheshPuro** [mperham/sidekiq#3768]
The Sidekiq jobs don't seem to running properly.  There are 4 server with a concurrency of 20 available.  The queue limits show that there should be more jobs running.

     1368 47.0  3.7 905056 601652 ?       Sl   07:26  10:08 sidekiq 4.1.4  [6 of 20 busy]

how to solve it get as much as jobs to be busy

**Comment by mperham** [comment]
I don't know how to help you.  Issues aren't for basic debugging, perhaps StackOverflow would be a better place to start.
