### ISSUE TITLE
Sidekiq doesn't ROLLBACK ActiveRecord transactions on quit

### ISSUE THREAD

**Issue by MSch** [mperham/sidekiq#377]
When terminating sidekiq does put the job back on the queue, but the current ActiveRecord transaction is COMMITed and not ROLLBACKed, making the whole "jobs should be idempotent" thing useless.

I also posted this on the mailing list but IMO it's clearly an issue.

**Comment by fiestacasey** [comment]
For anyone who finds this thread I'd like to point out that as of [AR 4.2.4](https://github.com/rails/rails/blob/v4.2.4/activerecord/CHANGELOG.md) this is no longer accurate:

> When a thread is killed, rollback the active transaction, instead of committing it during the stack unwind. Previously, we could commit half- completed work. This fix only works for Ruby 2.0+; on 1.9, we can't distinguish a thread kill from an ordinary non-local (block) return, so must default to committing.

via @chanks I believe but I'm having trouble digging up the exact commit or reasoning for the change.
