### ISSUE TITLE
WARN: LoadError: Unable to autoload constant

### ISSUE THREAD

**Issue by joshuamcginnis** [mperham/sidekiq#3772]
Hello. I'm having some trouble identifying the cause of these warnings.

When first enqueuing a bunch of the same jobs, I get these pair of warnings for each job:
> warning: already initialized constant Foo
warning: previous definition of Foo was here

Then, when the queue goes to execute a job, each one warns:
> WARN: LoadError: Unable to autoload constant Foo::TestJob, expected /Users/me/sandbox/test/app/jobs/foo/test_job.rb to define it

I've perused similar issues here and on StackOverflow, but none of the suggested remedies work.

I'm using ruby v2.50, and `sidekiq', '~> 5.1', '>= 5.1.1'`. 

To remedy, I've tried adding the following to `config/application.rb`:
```ruby
config.autoload_paths += %W(#{config.root}/app/jobs/foo)
config.eager_load_paths += %W(#{config.root}/app/jobs/foo)
```

```ruby
# config/initializers/sidekiq.rb
schedule_file = 'config/sidekiq/schedule.yml'

if Sidekiq.server? && ENV['SIDEKIQ_SCHEDULER_ENABLED'] == 'true'
  Sidekiq::Cron::Job.load_from_hash(YAML.load_file(schedule_file))
end
```

Not sure if it matters, but the job itself is using ActiveJob:

```ruby
module Foo
  class TestJob < ApplicationJob
    queue_as :default

    def perform(params)
      if params.key?(:key)
        return foo(key)
      end

      key.each do |key|
        self.class.perform_later(key: key)
      end
    end

    def foo(key)
      long_running_task(key)
    end
  end
end
```

To test this, I'm issuing `Foo::TestJob.perform_now` from `rails c` and I've had sidekiq started in another term session via: `bundle exec sidekiq -c 10 -v`

Any ideas or things I can try to resolve this?

**Comment by joshuamcginnis** [comment]
I was able to resolve the issue by requiring all jobs at the top of `config/initializers/sidekiq.rb`.

**Comment by Mifrill** [comment]
@joshuamcginnis  Hi, I got exactly the same issue with the same version of Sidekiq.
Please, help to resolve it: how are you `require all jobs`?
I'ed just try to use it: `Dir['app/jobs/**/*.rb'].each { |f| require f }`, but got the `require: cannot load such file`  at startup of rails server, can you help please?
Thanks in advance

**Comment by seuros** [comment]
In rails, if you name your files correctly, you won't have to require them.

If you recently created the folder and using spring, restart it.
