### ISSUE TITLE
Sidekiq Enterprise Unique - duplicated jobs

### ISSUE THREAD

**Issue by camol** [mperham/sidekiq#3774]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s):
5.0.5 / 3.7.1 / 1.6.1

Initializer:
```
require 'sidekiq'

if ENV['SIDEKIQ_REDIS_URL']
  Sidekiq.configure_server do |config|
    config.super_fetch!
    config.reliable_scheduler!
    config.failures_default_mode = :all

    config.redis = { url: ENV.fetch('SIDEKIQ_REDIS_URL') }
    config.periodic do |mgr|
      mgr.register '5 0 * * *', Stuff::SomeJob
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = { url: ENV.fetch('SIDEKIQ_REDIS_URL') }
  end
end

Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.default_worker_options["retry"] = 3

Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  File.open("./config/crypto/secret.#{Rails.env}.#{version}.key").read
end
```

Based on the [WIKI](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs) we enabled the `Sidekiq::Enterprise.unique!` functionality and we assumed that each job is unique until the job is actually processed. But I'm able to enqueue same job multiple times and I do not get the message which I would expect in that case:
`Skipping enqueue for TestJob, not unique`.

So we tried out same scenario but also with `unique_for`. I set the `unique_for: 5.seconds` and during this time I'm not able to enqueue the same job twice but after 5 seconds I'm able to do it once more and I get the message mentioned above.

In the test local scenario I do not run sidekiq processes so it does not pick the jobs from the queue. My expected behaviour here is that I should not be able to enqueue the same job twice until it's completely processed (which means the job is no longer in the queue and is not being processed by any sidekiq thread).

**Comment by mperham** [comment]
It sounds like it is behaving as designed in all cases.  Jobs must have a unique_for option set, and after that time period, the unique lock expires and the job can be re-enqueued.

**Comment by camol** [comment]
So there is no something like default uniqueness for jobs, right? Setting `unique_for` is only responsible for that? So probably I will be able to achieve such behaviour if I will set e.g. 24.hours as default `unique_for` for every job, right?

The other this is that it does not fully work with periodic functionality. Because when periodic initiates the job which has `unique_for` set, I'm still able to manually schedule the same job during processing of the first one.

**Comment by mperham** [comment]
You are relying on uniqueness  too much if you want a global default. Make your jobs idempotent.  Uniqueness is a band-aid for a buggy implementation, not a good idea.  It's ok for a few jobs, not good app-wide.

https://github.com/mperham/sidekiq/wiki/Best-Practices

If you want me to debug a problem, you will need to give me a specific app or script to reproduce.

**Comment by camol** [comment]
In general we do not rely on it that much, this is something I observed when I noticed that other issue with periodic and thought that I can somehow overcome it by relying more on the uniqueness functionality. So we are totally fine with the way it works. Still feels not ok that I can enqueue (e.g. manually) a job even when it is processing right now but was fired from periodic.

**Comment by mperham** [comment]
Unique and Periodic work together fine.  Your configuration is likely making it not work. e.g.

```ruby
class SomeWorker
  sidekiq_options unique_for: 119.seconds
```

```ruby
config.periodic do |mgr|
  mgr.register '* * * * * *', SomeWorker
```

will only enqueue every two minutes because of the lock.

**Comment by mperham** [comment]
The real issue is #3773, let's figure out why you have two leaders.

**Comment by camol** [comment]
You are only referring to periodic at this point. Try the following example:
```
config.periodic do |mgr|
  mgr.register '* * * * * *', SomeWorker
```

```
class SomeWorker
  sidekiq_options unique_for: 40.seconds

  def perform
     sleep 30
```

open the e.g. Rails console and once you spot that this job was picked up and is in the middle of processing fire `SomeWorker.perform_async` and it will enqueue this job once more. So I will end up with `SameWorker` being processed by two threads.

I agree that the main problem is the periodic.

**Comment by mperham** [comment]
I'm not seeing your reported behavior:

```
2018-02-26T20:07:00.005Z 95613 TID-ox1tlqzwt INFO: Enqueued periodic job ScheduledWorker with JID 599adf217461dc870b8cd73c for 2018-02-26 12:07:00 -0800
2018-02-26T20:07:00.550Z 95613 TID-ox1tnebm9 ScheduledWorker JID-599adf217461dc870b8cd73c INFO: start
2018-02-26T20:07:30.559Z 95613 TID-ox1tnebm9 ScheduledWorker JID-599adf217461dc870b8cd73c INFO: done: 30.01 sec
2018-02-26T20:07:32.636Z 95613 TID-ox1tsrub1 ScheduledWorker JID-248479e9c043f4ad6d12e949 INFO: start
2018-02-26T20:08:00.006Z 95613 TID-ox1tlqzwt INFO: Skipping enqueue for ScheduledWorker, not unique.
2018-02-26T20:08:00.006Z 95613 TID-ox1tlqzwt INFO: Periodic job ScheduledWorker did not push to Redis
2018-02-26T20:08:02.640Z 95613 TID-ox1tsrub1 ScheduledWorker JID-248479e9c043f4ad6d12e949 INFO: done: 30.005 sec
```

```
irb(main):002:0> ScheduledWorker.perform_async
2018-02-26T20:07:09.654Z 95535 TID-ovnxj0brn INFO: Skipping enqueue for ScheduledWorker, not unique.
=> nil
irb(main):003:0> ScheduledWorker.perform_async
=> "248479e9c043f4ad6d12e949"
```
