### ISSUE TITLE
Write can't be called from trap context [Windows]

### ISSUE THREAD

**Issue by Bernica** [mperham/sidekiq#3775]
Platform: Windows
Ruby version: 2.4.3
Sidekiq 5.1.1

Hi, I can't figure out why, but hitting Ctrl-C when running Sidekiq's CLI on Windows generates "can't be called from trap context" (and doesn't exit). I guess it has something to do with the way `puts` is implemented.

The backtrace:
```
can't be called from trap context
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:68:in 'write'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:68:in 'puts'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:68:in 'block (2 levels) in run'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:107:in 'select'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:107:in 'run'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sidekiq-5.1.1/bin/sidekiq:12:in '<top (required)>'
C:/Ruby24-x64/bin/sidekiq:23:in 'load'
C:/Ruby24-x64/bin/sidekiq:23:in '<main>'
```

Possible solution:
I tried replacing `self_write.puts(sig)` with `self_write.write("#{sig}\n")` in `cli.rb`, and it worked, sidekiq exits. But, I'm not sure it's ok to do that, maybe you could tell.

Bye!

**Comment by mperham** [comment]
Yep, puts() is often implemented as two operations so it's not atomic.  Nice job fixing it!  Want to send me a PR with your fix?

**Comment by Bernica** [comment]
Done! #3776
