### ISSUE TITLE
Enterprise Concurrency Limiter Not Working 

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3777]
Ruby version: 2.3.1p112
Sidekiq / Pro / Enterprise version(s): 

Sidekiq 5.1.1 / Pro 4.0.1 / Ent 1.7.0

Please include your initializer and any error message with the full backtrace.

```
NORMALIZATION_WORKER_GLOBAL_THROTTLE = Sidekiq::Limiter.concurrent('Chirpify-Limiter-NormalizationWorker-Global', 1, wait_timeout: 5, lock_timeout: 30)
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

![sidekiq 1](https://user-images.githubusercontent.com/5841107/36690246-91944126-1ae6-11e8-9d16-c67962401d05.png)

![sidekiq2](https://user-images.githubusercontent.com/5841107/36690256-988908f4-1ae6-11e8-8a4d-a74641752538.png)

Testing out the concurrent limiters -- the middleware we were using wasn't working as reliably as we need it to so we're on Enterprise.

I've decided to test Enterprise's limiter by only letting 1 job run at at time.
I have the limiter in use like this:

```
 begin
        NORMALIZATION_WORKER_GLOBAL_THROTTLE.within_limit do 
          Chirpify::Workers::Normalizers::Normalizer.new(message).normalize
        end
```
It's only being used in 1 spot at the moment.
As you can see in my screenshots all 30 threads are running the normalization worker instead of just 1 like I expect. The limiter tab looks legit though. 

What am I doing wrong? I stopped our other sidekiq process running on this instance just in case that was part of the issue.

Thanks!

**Comment by bobber205** [comment]
Note: The goal here was only allowing N limits of a job to be processed in the queue at a time -- leaving the other threads open. That doesn't seem to be how this feature works? 

We can have say 30 threads open on a server -- I only want X threads to be taking up at any point in time to be worker Y.

Is this possible using any Enterprise feature?

**Comment by mperham** [comment]
You've told the limiter it can block for up to 5 seconds, waiting for the lock.  Possible all 30 jobs are blocked for those 5 seconds?

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#limiting-is-not-throttling

**Comment by mperham** [comment]
Rate limiting is for accessing other services; none of my Sidekiq work provides any sort of throttling because any implementation would be very Redis intensive.  If you need throttling, it is best to push those jobs to a special queue and dedicate a Sidekiq instance to processing that queue.

**Comment by bobber205** [comment]
I think it'd be a great feature to offer -- I agree it's probably very redis intensive but for some customers that likely isn't a deal breaker. Having a bunch of sidekiq instances is also very resource intensive, resources that are often more expensive than a redis instance.

**Comment by mperham** [comment]
Agreed, I'd like to offer it but I can't find a way to do it without killing Sidekiq and Redis scalability.  At least this way I've documented a design decision so people understand why it is this way.

**Comment by bobber205** [comment]
Putting this here for future people googling this ==>
1) Upgrading to Enterprise was the easiest thing I've ever done
2) This gem has served our purposes quite nicely even under extreme load https://github.com/brainopia/sidekiq-limit_fetch
