### ISSUE TITLE
NameError uninitialized constant MyWorker

### ISSUE THREAD

**Issue by AshvinChauhan** [mperham/sidekiq#3779]
Rails version: 5.1.4
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): 5.1.0

**sidekiq.yml**
 ```
---
:concurrency: 25
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
```

**sidekiq.rb**

```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end
```

**Error**
`NameError uninitialized constant MyWorker`
Every time I am getting this error, and after some retries its working fine. and in development everything is working fine, but in production its not.
I also try to add it in `application.rb` as following
`config.autoload_paths += Dir[Rails.root.join('app', 'workers')]`

**Comment by mikegee** [comment]
The advice from [this blog post in 2014](https://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/) has solved this kind of problem for me.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#autoloading

**Comment by paneq** [comment]
@mikegee I am happy my blog post was helpful to you. (just remember that what you were trying to do was probably unnecessary https://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/#one_more_thing ) and if you have `app/workers/one/my_worker.rb` then the convention is to name it `One::MyWorker` and not `MyWorker` for autoloading to work.

**Comment by mikegee** [comment]
Thanks @paneq! I’ve used your advice to add `lib` to the path in about a dozen apps since you posted that.

**Comment by AshvinChauhan** [comment]
Solution is not working for me, my `worker` is in `app` folder, and I am not added it in `autoloading` or `eagerloading` still its showing `NameError uninitialized constant MyWorker`, and after retry its working, I mean in first try its not working, it always running after retry.

**Comment by paneq** [comment]
@AshvinChauhan what is the full path to the file (`app/my_worker.rb` ?) and full class name (`MyWorker` without namespaces?)

**Comment by AshvinChauhan** [comment]
full path is `app/workers/my_worker.rb`

and my)worker.rb containing following

```
class MyWorker
  include Sidekiq::Worker

  def perform(args*)
    # My stuff
  end
end
```

**Comment by AshvinChauhan** [comment]
@mperham can you please reopen the issue, because my issue is not resolved yet.

**Comment by mperham** [comment]
You’ll need to give us a Rails app that reproduces the problem. This issue is not a Sidekiq bug.

**Comment by AshvinChauhan** [comment]
Issue is only in rails 5, its working proper in older version of rails.

**Comment by AshvinChauhan** [comment]
Any update?

**Comment by mperham** [comment]
Still waiting on your app to reproduce the problem.

**Comment by AshvinChauhan** [comment]
Okay will provide you soon

**Comment by nflorentin** [comment]
In rails 5, same problem here with a simple mailer in app/mailers. Sometimes email is sent, sometimes after one or various retries. Always the same error "uninitialized constant ContactMailer" but randomly occurs. Sidekiq 5.2.5, redis 4.1.0, rails 5.2.2, ruby 2.5.3. Never had this problem before.

**Comment by ritesh2741** [comment]
I am having exact same issue, Sending text messages using it , the order of the gets messed up because of the uninitialized constant error. Sidekiq 5.2.6, Rails 5.1.6, Ruby 2.5.3, Redis 4.0. Works after one or couple retries. 
@mperham or @AshvinChauhan Can you please share some thoughts ?

**Comment by ceimox** [comment]
Oh Man this was really hard to figure out for me, it has nothing to do with the eager_load or autoload paths. If you are using puma with many workers then you need to call these below the workers number in your config/puma.rb

```
workers 2
preload_app! #used when workers are more than 0

```

**Comment by LegolasVzla** [comment]
I am having exact same issue too in development mode. I am using:
ruby 2.5.7
rails 5.2.3
sidekiq 6.0.0

These are my files and paths:

```app/workers/save_message_worker.rb```
```
class SaveMessageWorker
  include Sidekiq::Worker

  def perform(message_list)
	# When I tried the below line, I got: *** NameError Exception: uninitialized constant SaveMessageWorker::Message
	message = Message.new(message: message_list)

  end
end
```

```api/v1/messages_controller.rb```
```
    def multiple_concurrent_workers
        begin

            SaveMessageWorker.perform_async("Hello World!")
            return (render json: {status: "success", data:"processed successfully"})

        rescue => exception
            logger.error CONTROLLER_NAME + ': An error happened in method multiple_concurrent_workers: ' + exception.to_json
            return (render json: {status: "error", message: exception})
        end
    end
```

```config/routes.rb```
```
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users 
    namespace :api, defaults: { format: "json" } do
      namespace :v1 do

          resources :messages do
            collection do
              post :multiple_concurrent_workers
            end
          end

      end
    end

end
```

```config/initializers/sidekiq.rb```
```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://' + Rails.application.credentials[Rails.env.to_sym][:redis][:host].to_s + ':' +Rails.application.credentials[Rails.env.to_sym][:redis][:port].to_s + '/' + Rails.application.credentials[Rails.env.to_sym][:redis][:database].to_s }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://' + Rails.application.credentials[Rails.env.to_sym][:redis][:host].to_s + ':' +Rails.application.credentials[Rails.env.to_sym][:redis][:port].to_s + '/' + Rails.application.credentials[Rails.env.to_sym][:redis][:database].to_s }
end
```

**Comment by Mirk32** [comment]
In my case, I just restarted Sidekiq on production and it fixed a problem: `sudo service sidekiq restart`

**Comment by sunwooz** [comment]
Restarting the sidekiq service worked for me as well

**Comment by HeppokoNeet** [comment]
> Restarting the sidekiq service worked for me as well

I solved too!
