### ISSUE TITLE
Update rack-protection to version > 1.5.3

### ISSUE THREAD

**Issue by nick-f** [mperham/sidekiq#3780]
> Ruby version: 2.4.3
> Sidekiq / Pro / Enterprise version(s): 5.1.1
> Are you using an old version? No
> Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

There is a [vulnerability in rack-protection](https://github.com/sinatra/sinatra/pull/1379) <= 1.5.3 related to path traversal.

I'm not sure how much work would be needed to get sidekiq using rack-protection >= 2.0.0, but the vulnerability has been fixed in a [backported version of rack-protection](https://github.com/sinatra/rack-protection/pull/120).

https://github.com/rubysec/ruby-advisory-db/pull/331

**Comment by mperham** [comment]
Sidekiq only uses the CSRF middleware so I doubt there is a problem here but I’m happy to upgrade.

**Comment by mperham** [comment]
The gemspec uses ">= 1.5.0" so the latest version will be pulled if you do `bundle up sidekiq`.  There's no code to be fixed here AFAICT.
