### ISSUE TITLE
How to organize crawler workflow with sidekiq?

### ISSUE THREAD

**Issue by strivemag** [mperham/sidekiq#3783]
Hello,
**this is not an issue, but more advice I'm looking for.**

Is it possible to build architecture with Sidekiq Basic like there:
www.michaelnielsen.org/ddi/how-to-crawl-a-quarter-billion-webpages-in-40-hours/

Feel free if you want to close this issue!

**Comment by mperham** [comment]
This isn't an appropriate issue, StackOverflow is a better forum for general advice around "how do I build a crawler".  It may be that Sidekiq is not the right tool for what you need to do!
