### ISSUE TITLE
raise Sidekiq::Shutdown does not re-queue jobs

### ISSUE THREAD

**Issue by JamesChevalier** [mperham/sidekiq#3784]
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.1.1

Initializer:

```rb
Sidekiq::Logging.logger.level = Rails.env.development? ? Logger::INFO : Logger::WARN
$shutdown_pending             = false

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['redis_url'], network_timeout: 5 }

  config.on(:quiet) do
    $shutdown_pending = true
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['redis_url'], network_timeout: 5 }
end
```

I'm taking the advise from the [Deployment Events Wiki](https://github.com/mperham/sidekiq/wiki/Deployment#events) to forcefully re-queue long-running jobs during deploy. The jobs do stop, and the `Failed` count is incremented in the Web UI, but the jobs are not placed back into the queue and do not restart after I stop/start Sidekiq.

I'm forcefully re-queuing the job with `raise Sidekiq::Shutdown if $shutdown_pending` at the top of a long-running `each` block.

What's working well right now is still very useful. The `$shutdown_pending` variable is set to `true`, and the job does stop running, allowing me to gracefully deploy. As a workaround I've been noting the long-running jobs, performing the deploy, and then manually re-queuing the jobs myself.

Am I doing something wrong?
Can I provide any additional information to help debug this (assuming debugging is possible/needed)?

**Comment by mperham** [comment]
Ah, oops.  This works on Sidekiq Pro with super_fetch but doesn't work on basic Sidekiq because of differences in the fetch semantics.  I will update the wiki.
