### ISSUE TITLE
Rolling restart keeps old process

### ISSUE THREAD

**Issue by dandunckelman** [mperham/sidekiq#3789]
# Summary
When performing a rolling restart, the old process doesn't die.

I need help making sense of the log messages after sending `kill -TTIN SIDEKIQ_PID` to the stuck process.

## Environment
- OS:  Ubuntu 16.04
- Ruby version:  2.4.3
- Rails version:  5.1.4
- Sidekiq / Pro / Enterprise version(s):  5.1.1

## Initializer

```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['TA_PORTAL_REDIS_SERVER'] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['TA_PORTAL_REDIS_CLIENT'] }
end
```

## Config.yml

```
:concurrency: 5
```

## Stacktrace
https://gist.github.com/dandunckelman/736a5dc5d2622d0b48229735905edba5

Please let me know if more info is needed.

Thanks

**Comment by mperham** [comment]
Rolling restart is a paid feature. It does not work if you aren’t running Sidekiq Enterprise.

**Comment by dandunckelman** [comment]
😢 

Thanks anyway
