### ISSUE TITLE
Sidekiq intermittent Segmentation Fault crashes

### ISSUE THREAD

**Issue by augustosamame** [mperham/sidekiq#3791]
Ruby version: 2.3.1p112
Sidekiq / Pro / Enterprise version(s): 4.2.9
Ubuntu 16.04 / rvm 1.29.1 
which ruby shows: /home/deploy/.rvm/rubies/ruby-2.3.1/bin/ruby

Hello. I am getting intermittent crashes that bring all Sidekiq threads down within a few hours. I haven't been able to pinpoint the specific sidekiq job that is causing the issue.

I would appreciate any help you give us as we're testing this in prelaunch and will upgrade to Sidekiq Pro once we launch.

Backtrace follows:

Full backtrace: https://gist.github.com/augustosamame/8c4c76888a834ca21f98d20bbfc93f88

2018-03-17T14:57:55.807Z 28392 TID-bbg0c INFO: Booting Sidekiq 4.2.9 with redis options {:url=>"redis://redis-production.########.use1.cache.amazonaws.com:6379/5"}
2018-03-17T14:57:56.432Z 28392 TID-bbg0c DEBUG: Autoload disabled in production, Sidekiq will not reload changed classes
2018-03-17T14:57:56.507Z 28392 TID-bbg0c INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
2018-03-17T14:57:56.507Z 28392 TID-bbg0c INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-03-17T14:57:56.507Z 28392 TID-bbg0c INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-03-17T14:57:56.540Z 28392 TID-bbg0c DEBUG: Client Middleware: 
2018-03-17T14:57:56.540Z 28392 TID-bbg0c DEBUG: Server Middleware: Sidekiq::Middleware::Server::Logging, Sidekiq::Middleware::Server::RetryJobs, Rollbar::Sidekiq::ClearScope
2018-03-17T14:57:56.544Z 28392 TID-bbg0c DEBUG: {:queues=>["default", "rollbar", "apple_push_notifications", "android_push_notifications", "web_push_notifications", "apple_silent_push_notifications", "algolia_operations"], :labels=>[], :concurrency=>5, :require=>".", :environment=>"production", :timeout=>8, :poll_interval_average=>nil, :average_scheduled_poll_interval=>15, :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x000000031cb3c8>, #<Proc:0x000000075bd608@/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/rollbar-2.15.5/lib/rollbar/plugins/sidekiq.rb:15>], :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]}, :dead_max_jobs=>10000, :dead_timeout_in_seconds=>15552000, :reloader=>#<Proc:0x0000000304daa0@/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35>, :executor=>#<Sidekiq::Rails::Executor @app=Qounterapi::Application>, :verbose=>true, :pidfile=>"/home/deploy/rails_app/shared/tmp/pids/sidekiq-0.pid", :logfile=>"/home/deploy/rails_app/shared/log/sidekiq.log", :index=>0, :daemon=>true, :config_file=>"config/sidekiq.yml", :strict=>true, :identity=>"ip-172-31-90-103:28158:6835bcbe0aa3", :tag=>"rails_app"}
2018-03-17T14:57:56.547Z 28392 TID-123h0w Sidekiq::Extensions::DelayedModel JID-61ad828b5f35a4ba6518985a INFO: start
2018-03-17T14:57:56.552Z 28392 TID-1240j4 Sidekiq::Extensions::DelayedClass JID-61051c41b377632a0491adc8 INFO: start
2018-03-17T14:57:56.553Z 28392 TID-1241do Sidekiq::Extensions::DelayedClass JID-1866cc18ebee26e56a700f89 INFO: start
2018-03-17T14:57:56.555Z 28392 TID-1242yw Sidekiq::Extensions::DelayedClass JID-1f7766809d622f5e57b8bf8f INFO: start
2018-03-17T14:57:56.556Z 28392 TID-12425g Sidekiq::Extensions::DelayedClass JID-5ffc386e3c36f02ca2c08c51 INFO: start
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322: [BUG] Segmentation fault at 0x007f12141549e0
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0049 p:---- s:0222 e:000221 CFUNC  :syswrite
c:0048 p:0172 s:0218 e:000217 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322
c:0047 p:0010 s:0209 e:000208 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:340
c:0046 p:0031 s:0205 e:000204 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:211
c:0045 p:0010 s:0200 e:000199 BLOCK  /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:185
c:0044 p:0028 s:0198 e:000197 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:202
c:0043 p:0009 s:0194 e:000193 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:184
c:0042 p:0051 s:0190 e:000189 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:329
c:0041 p:0042 s:0183 e:000182 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:186
c:0040 p:0024 s:0176 e:000175 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:121
c:0039 p:0024 s:0170 e:000169 BLOCK  /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1435 [FINISH]
c:0038 p:---- s:0168 e:000167 CFUNC  :catch
c:0037 p:0027 s:0164 e:000163 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434
c:0036 p:0072 s:0157 e:000156 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407
c:0035 p:0040 s:0150 e:000149 BLOCK  /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1400
c:0034 p:0047 s:0148 e:000147 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853
c:0033 p:0020 s:0145 e:000144 METHOD /home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398
c:0032 p:0031 s:0138 e:000137 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:109
c:0031 p:0110 s:0131 e:000130 LAMBDA /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:55 [FINISH]
c:0030 p:0033 s:0125 e:000124 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/list_resource.rb:94
c:0029 p:0138 s:0120 e:000119 METHOD /home/deploy/rails_app/releases/20180309050058/lib/services/sms_notification.rb:14
c:0028 p:0038 s:0108 e:000107 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/extensions/class_methods.rb:18
c:0027 p:0013 s:0101 e:000100 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158
c:0026 p:0030 s:0096 e:000095 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138
c:0025 p:0006 s:0094 e:000093 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:90
c:0024 p:0031 s:0092 e:000091 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:85
c:0023 p:0014 s:0088 e:000087 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:89
c:0022 p:0011 s:0085 e:000084 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133
c:0021 p:0015 s:0083 e:000082 LAMBDA /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128
c:0020 p:0019 s:0081 e:000080 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/rollbar-2.15.5/lib/rollbar/plugins/sidekiq/plugin.rb:11
c:0019 p:0034 s:0075 e:000074 LAMBDA /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130
c:0018 p:0006 s:0073 e:000072 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74
c:0017 p:0034 s:0066 e:000065 LAMBDA /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130
c:0016 p:0034 s:0064 e:000063 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11
c:0015 p:0062 s:0061 e:000060 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32
c:0014 p:0025 s:0057 e:000056 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7
c:0013 p:0034 s:0051 e:000050 LAMBDA /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130 [FINISH]
c:0012 p:0029 s:0049 E:001ed8 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133
c:0011 p:0026 s:0043 E:001e40 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132
c:0010 p:0062 s:0041 e:000040 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174
c:0009 p:0053 s:0034 E:001df0 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131 [FINISH]
c:0008 p:0009 s:0030 e:000029 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35 [FINISH]
c:0007 p:0055 s:0027 E:001180 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126
c:0006 p:0025 s:0018 e:000017 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82
c:0005 p:0018 s:0015 e:000014 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70 [FINISH]
c:0004 p:---- s:0011 e:000010 IFUNC 
c:0003 p:0006 s:0009 e:000008 METHOD /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17
c:0002 p:0032 s:0004 e:000003 BLOCK  /home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26 [FINISH]
c:0001 p:---- s:0002 e:000001 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/rollbar-2.15.5/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:89:in `call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:90:in `block in call'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/extensions/class_methods.rb:18:in `perform'
/home/deploy/rails_app/releases/20180309050058/lib/services/sms_notification.rb:14:in `send_sms'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/list_resource.rb:94:in `create'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:55:in `block (2 levels) in <class:BaseClient>'
/home/deploy/rails_app/shared/bundle/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:109:in `connect_and_send'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1435:in `block in transport_request'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:121:in `exec'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:186:in `send_request_with_body'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/generic_request.rb:329:in `write_header'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:184:in `write'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:202:in `writing'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:185:in `block in write'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:211:in `write0'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
/home/deploy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f12141549e0 RBP: 0x00007f121408b820 RSP: 0x00007f12236eb0c8
 RAX: 0x00007f12141549e0 RBX: 0x00007f121408d540 RCX: 0x0000000000000005
 RDX: 0x00000000000001e3 RDI: 0x00007f121408d540 RSI: 0x00007f1210187ec0
  R8: 0x0000000000000000  R9: 0x0000000000000041 R10: 0x0000000000000000
 R11: 0x0000000000000206 R12: 0x00000000ffffffff R13: 0x00007f12237ef410
 R14: 0x00000000031905c0 R15: 0x0000000000000001 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/deploy/.rvm/rubies/ruby-2.3.1/bin/../lib/libruby.so.2.3(rb_vm_bugreport+0x4ea) [0x7f123007e68a] vm_dump.c:688
/home/deploy/.rvm/rubies/ruby-2.3.1/bin/../lib/libruby.so.2.3(rb_bug_context+0xd4) [0x7f122ff10294] error.c:435
/home/deploy/.rvm/rubies/ruby-2.3.1/bin/../lib/libruby.so.2.3(sigsegv+0x3e) [0x7f122ffed07e] signal.c:890
/lib/x86_64-linux-gnu/libc.so.6 [0x7f122fafd4b0]
[0x7f12141549e0]

-- Other runtime information -----------------------------------------------

* Loaded script: sidekiq 4.2.9 rails_app [1 of 5 busy]

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do
