### ISSUE TITLE
session logout when accessing /sidekiq

### ISSUE THREAD

**Issue by surajit** [mperham/sidekiq#3792]
I'm using ruby-2.4.2 and Rails-5.1.4 and for multi tenancy with apartment. When I'm trying to access /sidekiq rails automatic session logout. Though I've used the below scope as described here:
https://github.com/mperham/sidekiq/issues/3085
devise_scope :user do
    authenticated :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
But its not working in myside. What I need to do? Please suggest.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden
