### ISSUE TITLE
[idea] reliable push to file?

### ISSUE THREAD

**Issue by dragosmiron** [mperham/sidekiq#3793]
In my company we just used Sidekiq Pro Reliable Push for first time and we thought of the following scenario:
If Redis is unavailable and someone restarts the process or the machine, or deploys at the exact same time, we lose the jobs which are in memory

What if we would have reliable push have an extra option to keep jobs in a file?

**Comment by mperham** [comment]
Persisting to file would open a large number of questions and support issues.

* Can I set the filename / directory?
* Can I persist the file to S3 / other cloud service?
* Can I use it on NFSv4 / other network filesystem?

Right now the feature is best effort and as simple as possible to avoid such complexity and error cases.

**Comment by dragosmiron** [comment]
I'd argue that even the simplest way - file on disk anywhere (File.new(path)) would be much better than memory for the reason stated above.
I was thinking maybe reason why is not done is because you cannot write to file fast enough for high volume applications.
But if this is not the reason, we would be a lot more relaxed if we know someone cannot deploy over downtime period.
Thing is... i don't know if we're allowed to "fork" sidekiq pro and put it in ourselves :)

**Comment by seuros** [comment]
@dragosmiron ,  What about having a table instead ? You could store the payload in a json column and the name of the worker . 
A Cron job could monitor it and try to enqueue them every few minutes. 99.99% of the time, the cron job will be NOPing 

The file method wont work with lot of servers that are readonly (Heroku for example), and uploading a file to S3 cost more than a query. Also what the case of Spot servers (You spin more servers when your load increase and kill them later), the files will be gone with them.

As for fork sidekiq pro `forking`. You are allowed to extend it within your application. right @mperham ?

**Comment by dragosmiron** [comment]
We have the Spot problem currently as well, but we are thinking that implementing a termination hook based on a file might be more doable than implementing a hook based on the class variable of the in memory jobs.
Although you are right we can `extend` it and make like a `lock` file or something if the class var is non empty to prevent Spot autoscale, deploy, restart , etc. I'm no systems engineer so I might talk nonsense.

**Comment by mperham** [comment]
You can do whatever you want with Sidekiq Pro **internally** as long as you maintain a subscription.  You cannot distribute your changes externally/publicly.  Reliable push is meant to be better than normal Sidekiq, that doesn't mean it's the perfect solution in all cases; you are welcome to build on it.
