### ISSUE TITLE
How to set database connection parameters?

### ISSUE THREAD

**Issue by kpheasey** [mperham/sidekiq#3794]
My workers require increase db memory usage.  I thought each worker had a single database connection (because the docs say to make sure pool size is equal to concurrency).  However, I run into issues that would indicate each worker has access to the complete pool of connections.

```ruby
class MyWorker
  include Sidekiq::Worker

  def perform
    ApplicationRecord::Base.connection.execute <<-SQL
        SET TEMP_BUFFERS TO '#{TEMP_BUFFERS}';
        SET WORK_MEM TO '#{WORK_MEM}';
    SQL

    # do some database work

  ensure
    ActiveRecord::Base.connection.reset!
  end
end
```

Eventually one of the workers will complain that I'm trying to set TEMP_BUFFERS even though temporary tables have already been accesses.  This means that the connection I call `reset!` on, is not the connection that i set the buffers on.

How can I ensure each worker has a unique database connection?

**Comment by mikegee** [comment]
[`ActiveRecord::Base.with_connection`](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-with_connection) will probably do what you want.

I don't think this issue is a Sidekiq problem btw. StackOverflow would have probably been a better place to ask about using ActiveRecord with concurrency.

**Comment by mperham** [comment]
first thing that strikes me is that your connection checkout and reset don't match; they use different classes and therefore might not match.  but as mikegee points out, this is ultimately an AR issue separate from Sidekiq; I don't know the actual problem.

**Comment by kpheasey** [comment]
@mperham That was a typo with the different conneciton checkout methods, I was just simplifying the example....

Just to clarify, sidekiq doesn't mess with AR connection pooling?  Each sidekiq process shares on AR connection pool for all workers?

**Comment by mperham** [comment]
Correct.  Rails creates a pool for the process on boot.  Sidekiq does not touch it.
