### ISSUE TITLE
Forbidden on Deleting Jobs out of Retry Queue

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3801]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 5.1.1

Something I've noticed for awhile when messin' around in the scheduled and retry queue.
I'll hit the "delete all" button and randomly get `Forbidden` over and over.  The only way to clear it is to close the tab and reopen. Sometimes this takes several times. I thought maybe was it was something weird about our setup on AWS but I have recently deployed sidekiq instance to Heroku and got it almost immediately.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden

**Comment by bobber205** [comment]
👍😻
