### ISSUE TITLE
sidekiq Rate Limiting: Minimum value for backoff

### ISSUE THREAD

**Issue by prasannakumar1989** [mperham/sidekiq#3802]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
Sidekiq Pro 4.0.1 / Sidekiq Enterprise 1.6.1

We are using Sidekiq Rate Limiting feature. 
What can be the minimum acceptable value for `config.backoff` parameter. 
Can it be as small as 5 seconds.

**Comment by mperham** [comment]
It can be any value > 0 but it’s used to schedule the job and Sidekiq’s scheduler isn’t super precise. 5 seconds is probably the smallest value I would recommend.
