### ISSUE TITLE
Creating Limiter which can never expires

### ISSUE THREAD

**Issue by prasannakumar1989** [mperham/sidekiq#3804]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
Sidekiq Pro 4.0.1 / Sidekiq Enterprise 1.6.1

We want to create a limiter which would never expire , 
we are not creating these dynamically, we create these during application initialization 
`in config/initializer` 

I see the default ttl is set to 90 days.
Is there a way to say that the limiter never expires ? 

 Currently , we are just setting it as 

```
SAMPLE_LIMIT =
  Sidekiq::Limiter.window('SampleLimit',
                          20,
                          :second,
                          ttl: 999.years).freeze
```

**Comment by mperham** [comment]
You’ve got the correct solution, set the ttl to something very long.
