### ISSUE TITLE
What happens with redis data loss?

### ISSUE THREAD

**Issue by jrynyt** [mperham/sidekiq#3811]
Hi,

What is the behavior if any of the data in redis is lost? Are only enqueued jobs lost, or is sidekiq itself affected?

I'm familiar with https://github.com/mperham/sidekiq/wiki/Using-Redis and am using `maxmemory-policy = noeviction`. However, we're running in AWS Elasticache, which [doesn't really offer usable AOF](https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/RedisAOF.html), so we rely on [auto failover on master failure](https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/FaultTolerance.html#FaultTolerance.Redis). Since replication is asynchronous, there is a chance of some data loss on failover. We're ok with some jobs being lost in this situation, but want to verify that sidekiq itself can recover.

Thanks.

**Comment by mperham** [comment]
Sidekiq uses MULTI where necessary to make complex data changes atomic.  So any changes lost should still leave Redis (and therefore Sidekiq) in a usable state.

**Comment by jrynyt** [comment]
ok thanks. Do you have any experience using Elasticache with Sidekiq? any other gotchas?

**Comment by mperham** [comment]
There's lots of Elasticache questions in the closed issues, have you looked through them?  In general, just make sure you aren't using Cluster mode.  If you can tune the memory policy, do so.  Everything else should just work.

**Comment by jrynyt** [comment]
thanks for the help, I'll take a look at the other issues.
