### ISSUE TITLE
worker retries despite retry option set to false

### ISSUE THREAD

**Issue by blayvant** [mperham/sidekiq#3812]
Ruby version: 2.4.1
Rails version: 5.1.2
Sidekiq version: 5.0.5

I have the following options in my worker:
 sidekiq_options queue: "sms_response", retry: false

Despite the above settings, the worker continues to retry upon failure, as evident from the fact that the job can be retrieved from RetrySet in the console.
NOTE: I have removed certain sensitive information from the Sidekiq::SortedEntry output, but the relevant parameters such as 'queue' and 'retry' are still present. If some additional output is needed, please let me know.

```
irb(main):002:0> retry_set = Sidekiq::RetrySet.new
=> #<Sidekiq::RetrySet:0x0055ee921352f0 @name="retry", @_size=1>
irb(main):003:0> retry_set.to_a.first
=> #<Sidekiq::SortedEntry:0x0055ee9211cc28 @args=nil, `@value="{\"class\":\"SmsResponseWorker\",\"args\":[\"queue\":\"sms_response\",\"retry\":true....
```

**Comment by mikegee** [comment]
You don't get the `sidekiq_options` applied if you aren't enqueuing the job by calling `perform_async` on the worker class. How are these jobs enqueued?

**Comment by blayvant** [comment]
Thank you for the clarification! The job is enqueued from another application as follows:
Sidekiq::Client.push "class" => "SmsResponseWorker", "args" => [data], "queue" => "sms_response"
Are you aware of any way to pass options with the above implementation?

**Comment by mperham** [comment]
You must use the actual class if you wish to inherit the options from it.  It will inherit the queue too.

```ruby
Sidekiq::Client.push "class" => SmsResponseWorker, "args" => [data]
```
