### ISSUE TITLE
Limit retries by time?

### ISSUE THREAD

**Issue by swrobel** [mperham/sidekiq#3813]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.1.1

Is it possible to have a job stop retrying if it's after a certain length of time from the first attempt? Here is my use-case: Stripe supports [idempotent requests](https://stripe.com/docs/api#idempotent_requests), which is great for complex jobs that require a lot of Stripe requests all running in a batch (although they don't support any concept of a database-style transaction that would roll back the whole batch if part of it failed). The catch is that idempotency keys can be reused after 24 hours from the first request, which means that I don't want jobs to retry automatically after that time.

I realize that this can be approximately accomplished by limiting the number of retries to around 12 to account for the randomness of the exponential retry schedule, but it still makes me uneasy. Is there nay straightforward way to just configure a job to not retry if 24 hours have expired since the first try?

**Comment by mperham** [comment]
Sidekiq Pro has expiring jobs. `sidekiq_option expires_in: 24.hours`  Sidekiq doesn't have that feature; as you note, limiting the retries is the easiest approach.

**Comment by dhempy** [comment]
Just to clarify...if a job is in the retry queue, does expires_in apply to retries from the original job creation? 

For example, a job is enqueued at 9:00, with `expires_in: 1.hour, retry: true` . It fails several times. At 10:03, it comes up for another retry. At that point with the job expire and go away without running?

My use case is I'm watching for a file to settle on an SFTP server. I check for the file every hour. If it doesn't settle (have the same size twice in a row) within an hour, I want the job to die, as the next hourly worker will find it. So, I think I want to say `expires_in: 45.minutes`  (my job takes up to 5 minutes to process the file) to be eager about retrying, but avoid conflicting with the next hourly worker.

Will that work? 

Related, I tried creating a chart of typical retry delays, and I haven't gotten it right. I about nine days for 25 retries, not 21 days. Any idea what I got wrong here: https://docs.google.com/spreadsheets/d/1G1bV2C4dP0fa6oe2wtv4oDMdr1YjNJsHXIasWxyN3xg/edit?usp=sharing   (Before I discovered `expires_in`, I was going to use something like `retries: 6` to keep retries under an hour.)

**Comment by mperham** [comment]
Yes. Expiry is checked right before calling `perform` so your job might retry but it will immediately expire rather than actually run.

Retries are a bit unpredictable by design because they include some amount of jitter.

**Comment by dhempy** [comment]
Thanks, Mike! :-)

Regarding the jitter, I think I captured your fallback equation correctly, but my numbers are still way off. Just wondering if I've missed something big in this:

`=(A4 ^ 4) + 15 + (RAND()*30 * (A4 + 1))`

**Comment by dhempy** [comment]
Oh...never mind...I was summing the wrong cells. *blush*
