### ISSUE TITLE
Sidekiq Route Mount doesn't rewrite URL in Rails API

### ISSUE THREAD

**Issue by antodoms** [mperham/sidekiq#3815]
Hi Team,

Ruby version: 2.4.0
Sidekiq: 5.0.4

I have a website 
xyz.com -> Standalone Angular APP (Container)
xyz.com/api/ -> Standalone Rails API APP (Container)
xyz.com/api/sidekiq -> Mounted to Rails api routes.

When I try to access the /api/sidekiq it loads the data but assets are still pointing to xyz.com/sidekiq instead of xyz.com/api/sidekiq. And all when I click retry it tries to submit to xyz.com/sidekiq instead of xyz.com/api/sidekiq. Is there a way to force sidekiq to use a different path?

Is there a way to get the sidekiq web view as a seperate standalone application container?

**Comment by mperham** [comment]
AFAIK Rack passes `SCRIPT_NAME` in the env to indicate the path prefix.  If you call `mount "/sidekiq", Sidekiq::Web`, Sidekiq will think it is at /sidekiq.  I'm not sure how to get the full `/api/sidekiq` prefix.

```ruby
    def root_path
      "#{env['SCRIPT_NAME']}/"
    end
```

**Comment by mperham** [comment]
I suspect the problem is that the Rails app doesn't know it is at `/api/` so it doesn't prefix its own namespace to the mount path.  More info:

http://www.rubydoc.info/github/rack/rack/file/SPEC

**Comment by mperham** [comment]
See also https://github.com/hanami/router/issues/87

**Comment by antodoms** [comment]
Thanks @mperham,

I had found a work around for this problem by tweaking Nginx Ingress Controller configuration to my rails app service. Hope this helps someone: https://stackoverflow.com/a/55004957/4289344

cheers!!!
