### ISSUE TITLE
Testing the scheduler?

### ISSUE THREAD

**Issue by jagthedrummer** [mperham/sidekiq#3818]
Just wondering if there are any tips/tricks to writing tests around the scheduler. It seems that in both `fake` and `inline` mode anything that is scheduled goes directly into the ultimate destination queue immediately.

We're hoping to be able to do something like:

```
Sidekiq::Testing.fake!

MyWorker.perform_in(3.hours, 'mike', 1)
assert_equal 0, MyWorker.jobs.size

Timecop.travel(Time.now + 3.hours)

expect {  
  Sidekiq::Testing.process_schedule
}.to change(MyWorker.jobs, :size).by(1)
```

I realize that this particular example is easy enough to test for by inspecting what's in the queue, but the actual tests we're trying to write are considerably more involved.

I think for this to work the testing module would have to maintain a seperate array of scheduled jobs that would then be moved into the actual/fake queues by calling `process_schedule` or whatever.

Would you be open to a PR that adds something like this?

**Comment by mperham** [comment]
The scheduler is not something you should test but you can test that the job is scheduled by checking the `at` attribute.  This might work?

```ruby
MyWorker.perform_in(3.hours, 'mike', 1)
assert_equal 1, MyWorker.jobs.size
assert_in_delta (Time.now + 3.hours).to_f, MyWorker.jobs.first['at'], 0.1
```
