### ISSUE TITLE
Latency Display Doesn't seem to work after upgrading to 5.1.3

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3819]
Ruby version: 2.3.4
Sidekiq / Pro / Enterprise version(s): 5.1.3

![image](https://user-images.githubusercontent.com/5841107/38395086-0fcb7f38-38e6-11e8-94e4-fb0be1df065a.png)

I noticed sometime in the 5.x series this nice latency value was added to the dashboard. Very handy!
But after I upgraded from 5.1.1 to 5.1.3 it always says 0

**Comment by mperham** [comment]
I can't reproduce this, I suspect you have something wrong with your app or you are pushing jobs to the queue which do not have an `enqueued_at` attribute.  The latency column works fine for me locally.
