### ISSUE TITLE
Auto-configure web from `config/sidekiq.yml`

### ISSUE THREAD

**Issue by chaffeqa** [mperham/sidekiq#3822]
I dove around in the code, and found no clean way to apply the same config file loading as in `cli.rb` to the `web.rb` configuration.  Was wondering if I was missing something (since [it says this file is respected](https://github.com/mperham/sidekiq/blob/master/examples/config.yml#L3)) or if I could make a pull request to try loading the default config file(s) if they exist.

Ruby version:
Sidekiq / Pro / Enterprise version(s):
> Sidekiq

Please include your initializer and any error message with the full backtrace.
> Not applicable

Are you using an old version?
> No

Have you checked the changelogs to see if your issue has been fixed in a later version?
> Yes

**Comment by mperham** [comment]
I don't understand your problem.  Please tell me what's wrong.

**Comment by chaffeqa** [comment]
Sorry I should have closed this earlier,  I talked with a colleague and he pointed out that the web interface figures out the `active` queues from redis, not configuration (reading the `queues`).

That actually makes sense the more and more I thought about it.  Great work!
