### ISSUE TITLE
 Sidekiq Enterprise DB reconection

### ISSUE THREAD

**Issue by icotanchev** [mperham/sidekiq#3826]
Ruby version: 2.2.2
Rails version: 4.2.7.1
Sidekiq Enterprise version: 1.7.1

We have purchased an Enterprise license for 400 workers and after the migration to sidekiq we have noticed a few failed jobs with lost connection to the DB. I checked wikis but did not find any available option to ensure that will retry a lost DB connection. Is there any option that can help us with this behaviour? We have a few long-running(around 20 mins) jobs that export or import data to/from a file, also, a few jobs to archive old data into another DB. Also, can you advise us on the `pool` value in `database.yml` (I have read that it should be bigger than sidekiq concurrency) in case that some jobs establishing 2 connections to different databases?

**Comment by emilpetkov** [comment]
AFAIK [Rails has 5 as the default value for the DB conn pool](http://guides.rubyonrails.org/configuring.html#database-pooling). Sow with `concurrency: 5` we should be good already, no changes needed here

**Comment by mperham** [comment]
I haven't implemented anything.  I think AR has an attribute in database.yml which controls reconnection, but my memory fails me on the specifics.
