### ISSUE TITLE
Active Job Retry Error Line Number

### ISSUE THREAD

**Issue by SampsonCrowley** [mperham/sidekiq#3827]
Are there any plans to allow storing backtraces with ActiveJob? it's really annoying to not at least know the line where an error occurred

**Comment by mperham** [comment]
I don’t control ActiveJob so I’m not sure how could I do this.  Most people are using error services to track and report on production errors. If you use Sidekiq’s retry system, it will store backtraces if configured to do so.

**Comment by SampsonCrowley** [comment]
thanks
