### ISSUE TITLE
Remove concurrent-ruby dep?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3830]
Concurrent-ruby is used very little in Sidekiq and I've heard rumors it is not getting reliable maintenance anymore.  Can we vendor what little code we need (is it just the thread-safe Hash for stats in processor.rb?) or reimplement easily?

**Comment by pointlessone** [comment]
Do you consider dropping concurrent-ruby dependency on sidekiq-pro as well?

**Comment by mperham** [comment]
Sidekiq Pro’s usage of c-r is more extensive and therefore not easy to remove.
