### ISSUE TITLE
Sidekiq jobs stuck

### ISSUE THREAD

**Issue by yasir47** [mperham/sidekiq#3832]
JRuby version: 1.7.13
Sidekiq version(s): 3.3.0

Facing an issue on my QA server after 2 or 3 hours jobs getting stuck and i have to restart the server every-time to fix this . 

Error Message in sidekiq.log : 
	org/jruby/RubyKernel.java:877:in `exit'
	org/jruby/RubyKernel.java:840:in `exit'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/sidekiq-3.3.0/lib/sidekiq/launcher.rb:33:in `actor_died'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `call'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `task'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `task'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `initialize'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/task.rb:34:in `initialize'
	/home/yasir/.rvm/gems/jruby-1.7.13/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `create'

**Comment by mperham** [comment]
I can’t support a version that old. Please upgrade to Sidekiq 4.2 or 5.1.
