### ISSUE TITLE
fork error when try to start sidekiq at MacOS high sierra

### ISSUE THREAD

**Issue by arthurbryant** [mperham/sidekiq#3833]
## Environment
- System Version: macOS 10.13.3 (17D102)
- Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin17]
- rails (5.0.3)
- sidekiq (5.0.0)

## Issue
When try to start sidekiq at High Sierra, I got the following error message: 

```
objc[96412]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[96412]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**I thought maybe my sidekiq is old, so I updated to siekiq 5.1.3, but still doesn't work.**

I searched on the internet and found this article: 

https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/ 

also the workaround: 

```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

But I was wondering can this problem be solved eventually? Thank you!

**Comment by mperham** [comment]
1. ‘bundle up sidekiq’
2. Sidekiq doesn’t fork. This is an issue with something else.

**Comment by arthurbryant** [comment]
@mperham  Thank you for your reply.

upgrade sidekiq doesn't work for me

> Sidekiq doesn’t fork. This is an issue with something else.

I see. I will update here if I found anything.

**Comment by mikegee** [comment]
@arthurbryant check this out: https://bugs.ruby-lang.org/issues/14009 I'm pretty sure it's related.

**Comment by mperham** [comment]
It's a bad idea to fork Sidekiq unless you know exactly what you are doing.  For instance, don't use the `parallel` gem inside a job.  Split the work into smaller jobs and let Sidekiq do the work concurrently.
