### ISSUE TITLE
What options do I have for tracking down a bad job in production? (Sidekiq Enterprise)

### ISSUE THREAD

**Issue by jamesbrauman** [mperham/sidekiq#3834]
In our production environment, we use Sidekiq Enterprise with the Swarm functionality. We have a recurring issue where the memory consumption of a Sidekiq process exceeds our set limit and the process terminates. On average this happens about once per minute, but periods of thirty minutes or more where this does not occur.

I have not been able to reproduce this issue locally or in our test environment, so I have been attempting to diagnose this issue in production.

So far, I have patched Sidekiq to produce structured log messages upon job start, which I have visualised in Kibana. I have also visualised the messages that Sidekiq enterprise produces when it kills a child process for consuming too much memory. I've attempted to correlate the two, but can't find any correlations.

I assume that we have a job that is executing that is consuming too much memory for some particular set of arguments. On average, we execute about 50,000 jobs per hour.

In an ideal world, for each job execution I would like to see memory allocated before the job executes, and memory allocated after the job executes and garbage collection has been executed, so I can find jobs that are leaking memory.

In case it is not a job that is leaking memory but instead just a job using too much memory, I'd like to see what jobs are actually currently executing on each thread of a Sidekiq process when it shuts down.

There also might be other options I haven't thought of.

Could anyone please advise on the best way to approach this problem? I've spent the better part of a week on this issue with no resolution.

Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): sidekiq (5.1.1) sidekiq-pro (4.0.1)  sidekiq-ent (1.7.0)

**Comment by mperham** [comment]
Read my latest blog post. It will help you immensely.

**Comment by jamesbrauman** [comment]
Thanks @mperham I read the blog post and found some useful information there. However I did not find information about tracking down a bad job, but lowering overall memory usage.

**Comment by mperham** [comment]
I mentioned it because it's normal for people mistake memory bloat with a memory leak.  It's easy to tune the bloat away and then see if your process still continues to "leak".  It's hard to find a specific leak so do the easy thing first.

**Comment by mperham** [comment]
To be clear:

1. Set MALLOC_ARENA_MAX=2.  See if it helps.
2. Rejigger your app to use jemalloc.  It almost always helps but takes more effort.

See the Problems and Troubleshooting wiki page for more tips and gotchas.
