### ISSUE TITLE
Error message for `unique_` options when unique mode isn't setup

### ISSUE THREAD

**Issue by cheerfulstoic** [mperham/sidekiq#3838]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
```
sidekiq-ent (1.7.1)
sidekiq-pro (4.0.2)
sidekiq (5.1.3)
```

Please include your initializer and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1' }
  config.server_middleware do |chain|
    chain.add Sidekiq::Statsd::ServerMiddleware, env: 'production',
                                                 prefix: 'worker',
                                                 host: '127.0.0.1',
                                                 port: 8125
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1' }
end

Sidekiq::Enterprise.unique! unless Rails.env.test?
```

I had `unique_for` and `unique_until` options on my workers for a while but didn't realize that they weren't actually doing anything because `Sidekiq::Enterprise.unique!` hadn't been run.  Obviously that's entirely my fault for not reading the documentation closely enough, but I was wondering in the spirit of the helping users "fall into the pit of success", perhaps there should be an error if you try to use `unique_` options without doing the setup.  That way people could know right away and the options don't just silently not doing anything (unless I'm missing something)

Thanks for Sidekiq!

**Comment by mperham** [comment]
Unfortunately I don't see any way to do this without additional runtime overhead.  I do try to call out incorrect API usage where possible but I don't see it as feasible in this case.

**Comment by cheerfulstoic** [comment]
Thanks!

I figured it could be implemented when the `sidekiq_options` is called, which I would think would be done just once per process / thread on startup.  It's your code, though, so you'd know better about the runtime impact ;)
