### ISSUE TITLE
Jobs cannot enqueue due to Uniqueness even when queue is empty

### ISSUE THREAD

**Issue by tmlee** [mperham/sidekiq#3839]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s): Enterprise 1.7.1

The job seem to suddenly stop getting enqueued.
Went to the /sidekiq dashboard to delete the queue and tried to enqueue it manually using `perform_async` from the console and got the error below

```
> ABCWorker.perform_async 385888
> INFO: Skipping enqueue for ABCWorker, not unique.
```

Resolved by flushing the Redis queue in its entirety. Hopefully there are better ways to deal with this

Sidekiq options for worker is as below
```
sidekiq_options queue: 'throttling',
                  retry: false,
                  unique_for: 12.hours, unique_until: :start
```

**Comment by mperham** [comment]
Manual changes to the data in Redis will not clear any associated unique locks.  As you have discovered.

**Comment by mperham** [comment]
Remember you can always force a job push like so:

```ruby
MyWorker.set(unique_for: false).perform_async(...)
```

I strongly urge people to keep their timeouts as low as possible.  12 hours is a really long time to hold that unique lock.  If you have a long running job, try to break it into pieces with a Batch or use a concurrent rate limiter of size 1 to ensure exclusion during one smaller block within the job.

**Comment by mperham** [comment]
> Is there a convenient way to clear out the unique locks during development workflows like this?

redis-cli flushall

> 
> > Manual changes to the data in Redis will not clear any associated unique locks.
> 
> seems confusing because running `redis-cli --scan --pattern 'unique:*' | xargs redis-cli DEL` seems have the effect I would want.

"Manual changes" in the Web UI. Yes, if you clear Redis, you clear all unique locks too. Yep, your script will work fine.
