### ISSUE TITLE
sidekiq/web support for Rails 5.x?

### ISSUE THREAD

**Issue by s0rin** [mperham/sidekiq#3843]
Currently **sidekiq/web** works with Rails >= 4.2 only

    Bundler could not find compatible versions for gem "rails":
      In snapshot (Gemfile.lock):
        rails (= 5.2.0)

    In Gemfile:
      rails (= 5.2.0)

      sidekiq-web was resolved to 0.0.1, which depends on
        rails (~> 4.2.0)

Is there any plan to support Rails 5.x ?

**Comment by mikegee** [comment]
`sidekiq-web` is some sort of third-party companion gem. I don't know what it does.

`sidekiq/web` is a file proved by the `sidekiq` gem, [from this repo](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb).

Try removing `sidekiq-web` from your `Gemfile`.

**Comment by s0rin** [comment]
Indeed, **sidekiq/web** works in Rails 5.x, here an example from `config/routes.rb`:

```
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
```

Thank you!
