### ISSUE TITLE
Losing jobs after processes are killed

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#3845]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.1.3/4.0.2/1.7.1

Upfront apologies about this ticket, as it's not going to contain much information right now, as i need help debugging it. 

Basically, if a process is killed, we are losing jobs. It doesn't happen all the time, and i am not able to replicate it reliability.  

Basically when redeploying we have X jobs running, and then once the deploy is done, the jobs are not in Enqueued, and once the processes start again, there are none running. I cannot get this to happen every single time though. It could be linked to situations when our memory usage (on the app server, not redis) is very high.

```
require 'sidekiq'
require 'sidekiq-status'

Sidekiq::Enterprise.unique! unless Rails.env.test?
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end

  config.super_fetch!
  config.reliable_scheduler!
end
```

We are also using https://github.com/brainopia/sidekiq-limit_fetch but i am 90% sure i have observed this behaviour before we used this gem.

Any help trying to work out what is going on here, and how to replicate it would be much appreciated. We are using super_fetch, so this stuff should be rock solid, right?

**Comment by scottrobertson** [comment]
I have done a bit more digging, and this is 100% happening. 

Just had 50 jobs running, all of which had 10s of minutes left to go before they would be finished, and 0 enqueued jobs. Redeployed (see below for how that is done), and once everything settled, there were no jobs running, no jobs enqueued, no fails, no retries and processed count had not increased.

This is how we are handling deploys:

- TSTP 
- wait 25s
- TERM
- wait 5
- kill

Any ideas on how to debug this further?

**Comment by scottrobertson** [comment]
Also just to counter my previous point about memory. All app servers were using ~20% memory and very low CPU at the time of this happening. Redis is hardly doing anything in terms of CPU/Memory.

**Comment by scottrobertson** [comment]
I potentially worked this out. So while the deploy flow is defined as (now):

`TSTP, (wait for 25s), TERM`

We had another command that was running at the very very start of deployment for some reason:

```
ps aux | grep "sidekiq" | awk '{print $2}' | sudo xargs kill --signal USR1
```

A mix of these was causing the jobs to go missing for some reason. I need to do some more testing to confirm.

**Comment by mperham** [comment]
super_fetch and limit_fetch are mutually exclusive.  If you are running the latter, you are not getting the reliability of the former.

**Comment by scottrobertson** [comment]
That makes sense then. Can you think of a way to replicate the `limits` of limit_fetch while keeping the reliability of super_fetch?

Basically, we have about 50 different queues, each requiring a limit to the number of jobs that can run at a given time. We used to handle this by just having about 50 different entries in the Procfile, but it becomes very wildly to maintain and manage.

**Comment by mperham** [comment]
You can get something that sort of looks like limiting concurrency if you use a concurrent rate limiter (🤔) but it's not the same thing.  I don't recommend having that many queues; it's possible you could divide the queues into two types: (safe and unlimited) || (unsafe but limited).  You start each Sidekiq process using one fetch scheme or the other.

**Comment by scottrobertson** [comment]
> You can get something that sort of looks like limiting concurrency if you use a concurrent rate limiter 

As in https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting? I did look into it before looking at the fetch_limit library, but it doesn't seem to fit our needs in the same way. It would still end up starving the queues and preventing other jobs from running as fast as possible where there is room from what i can see.

>  I don't recommend having that many queues; it's possible you could divide the queues into two types: (safe and unlimited) || (unsafe but limited). You start each Sidekiq process using one fetch scheme or the other.

Our flow doesn't allow for that type of setup sadly. It needs to be very closely controlled, otherwise certain queues will be starved and will take a huge amount of time to process the jobs. We process well over a billion jobs a year, so it gets pretty crowded in there, and needs close control.

If you want, i can ping you an email with more detailed reasons as to why this flow works the way it does, but it gets pretty into our business logic, and i wouldnt really want to post that publicly.

**Comment by mperham** [comment]
If you are limiting your queues because you don't have enough machine resources, there's not much I can do.  If you are limiting your queues because of 3rd party API SLAs, then using the rate limiting API is the correct solution.  The jobs will only block as long as the `wait_timeout` before giving up and fetching another job.  This timeout can be 0 if you don't want to wait at all for the lock.

**Comment by scottrobertson** [comment]
I will need to think of a way to explain the logic around why we do this, as it's pretty difficult without understanding the whole of our system. Will get back to you. Feel free to close this ticket, and i can just carry on via email or something, as it's not an actual Sidekiq code issue.
