### ISSUE TITLE
memory leak, check my ttin log and please help me

### ISSUE THREAD

**Issue by shatle** [mperham/sidekiq#3846]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): 5.0.5

Issue:
I have a large of tasks in sidekiq. When i start it about 20 minutes, the process will use all memory.
And, i get that the process's workers just wait for something, maybe it should be dead.

Then, i send `kill -TTIN PID` and Got [https://gist.github.com/shatle/531deec02e68d50bf42279b4952eda5b](https://gist.github.com/shatle/531deec02e68d50bf42279b4952eda5b)

Also,  althought I know that sidekiq disable the Rails cache in rails5 pro env, i add `ActiveRecord::Base.uncached ` to worker, and got
[https://gist.github.com/shatle/b07429a7c2189279e188000d84121e19](https://gist.github.com/shatle/b07429a7c2189279e188000d84121e19) 

i dont have any idea for that, please help me.
Thanks.

**Comment by mperham** [comment]
You need to optimize this query, all of your threads are stuck on it, likely it needs indexing or rewriting to do more work in SQL and less work in Ruby:

app/models/user.rb:491:in `unread_statistic'

Also, please see this:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#memory-bloat

**Comment by shatle** [comment]
@mperham Thanks, get it
