### ISSUE TITLE
TTIN signal doing nothing, even on dev machine

### ISSUE THREAD

**Issue by soberstadt** [mperham/sidekiq#3847]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 5.1.3 / 4.0.3 Pro

Please include your initializer and any error message with the full backtrace.
https://gist.github.com/soberstadt/2599b996e9a2f8a0e9e7fc526202bab7

I have been trying to debug stuck processes in our production Sidekiq env (https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes) and was unable to get the signal sending to have any effect on our prod servers even though jobs were being processed by that worker. After trying everything I could think of, I tried to test it on my dev machine. So I made a worker:
```
class RunOnce::TimeoutTestWorker
  include Sidekiq::Worker

  sidekiq_options queue: :api_default

  def perform
    sleep 10
    url = 'https://www.google.com:81/'
    RestClient::Request.execute(method: :get, url: url, timeout: nil)
  end
end
```
And enqueued a bunch of instances. Shorting after starting sidekiq (bundle exec sidekiq), I found the pid and tried to send the TTIN signal to the process:
![image](https://user-images.githubusercontent.com/1080613/40393457-8079e342-5ded-11e8-903b-cd4f087c6fae.png)
But nothing was logged in my terminal or log/development.log file.

Am I doing something wrong? Should I be looking elsewhere for the output of the signal?

**Comment by mperham** [comment]
It logs to stdout.  Add a puts, find the puts output and you'll find the TTIN.

**Comment by soberstadt** [comment]
Thanks for your help! I found the stack trace in my sidekiq logs on my machine, and that showed me that they were being silenced in production because our Logging level was set to FATAL.

We love Sidekiq here, easily one of our highest value licenses!
