### ISSUE TITLE
Redis performance issues due to `smembers('processes')` when using large number of processes

### ISSUE THREAD

**Issue by ffiller** [mperham/sidekiq#3848]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): sidekiq (5.1.3), sidekiq-pro (4.0.2), sidekiq-ent (1.7.1)

Hi Mike,

We're running 1k+ sidekiq processes and are seeing the redis `smembers('processes')` calls causing performance issues with our redis instance. These queries are showing between 100-500ms latency in the slowlog.

I'm assuming the guarantees that come with scan aren't sufficient for these calls?

Do you have any recommendations on what to do?

Thanks
Fried @Baremetrics

**Comment by mperham** [comment]
I think it would be fine to move to a scan-based impl; it was implemented before Redis 2.8 was required so scan wasn't available.  Want to send a PR?

**Comment by ffiller** [comment]
See #3849

**Comment by scottrobertson** [comment]
Hey @mperham 

Just a random thought...

We are using Sidekiq Swarm, i don't suppose any of that code (i cannot see it as it aint open source) is using similar methods to keep track of processes that could be rewritten to use this more performant code?

**Comment by mperham** [comment]
Generally, features use the API, so they’d all pick up your change. Swarm uses normal Unix methods only to track child processes.
