### ISSUE TITLE
optiona super_fetch

### ISSUE THREAD

**Issue by goncalopereira** [mperham/sidekiq#3850]
Hello,
we've been getting latency issues due to super_fetch, mostly with jobs we don't care about reliability.

Is there an option to switch it on or off per job, the same way we can switch queue before calling perform_async?

If not I'm afraid we'll have to switch it off as a whole.

Regards

**Comment by mperham** [comment]
super_fetch is configured per-process.  You can pretty easily toggle this with something like:

```ruby
# SUPER_FETCH=1 bundle exec sidekiq
config.super_fetch! if ENV['SUPER_FETCH']
```

Latency is almost greatly affected by networking.  Make sure your Redis instance is in the same data center as your workers.

https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud

How many queues do you have in your system?  I don't recommend using more than a dozen.

**Comment by goncalopereira** [comment]
Hi! It's heroku based so I know we're in the same region (auto generated by Heroku, EU-WEST-1 in our case) but maybe not same DC.

We're currently on 8 queues.

I suppose we can split queues per worker and have one worker with all the reliable queues.

**Comment by mperham** [comment]
Sidekiq is not meant to be a real-time system but there are things you can do to make latency better or worse.  What kind of latencies are you seeing?  Can you run those Redis latency commands here and show me the output?

https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud

You can also put your most important jobs in one queue and list it first when using strict priority:

`-q critical -q default -q low`

You should see very little latency for `critical` jobs.

**Comment by goncalopereira** [comment]
Don't have an easy way to run from inside the DC/Web app server, I tried from my desktop but the latency is too high.

I do have metrics and I get the following results 

![screen shot 150](https://user-images.githubusercontent.com/410638/40554903-2e3e2d96-603f-11e8-9efe-4139e3df30a8.png)

We're using weighted queues for all 8.
Three processes, concurrency 30 each

**Comment by goncalopereira** [comment]
In this scenario I don't want the Datawarehouse Update (Blue time consumption) or S3 to be under super_fetch but I do want to leave Inventory and others

**Comment by mperham** [comment]
brpoplpush is a blocking command.  It will not show your actual latency.  what are you actually trying to fix?  those peaks in the query time graph?

**Comment by goncalopereira** [comment]
We're getting timeouts when queueing workers on Sidekiq from the Web App our timeout is already quite high.

We're still trying to figure out possible causes.

**Comment by mperham** [comment]
Enqueueing has nothing to do with super_fetch.  That's all network latency and Redis performance.  Look into your Redis metrics and slowlog.
