### ISSUE TITLE
allow jobs to store/track custom metadata on Batches?

### ISSUE THREAD

**Issue by jdc0589** [mperham/sidekiq#3851]
Current sidekiq version(s): `Sidekiq v4.2.10 / Sidekiq Pro v3.7.1`

I have some Batches that have a small number of child jobs (<= 4 children). The jobs will always "succeed", as we catch error conditions and don't want out-of-the-box sidekiq retries right now.

But, I need to know about the state child jobs were in at completion time in my Batch callback(s). This would be easy enough to do directly via Redis, but it also seems like it might make sense to be supported natively in Sidekiq Batches.

**Example:** Batch (b1) has two child jobs (j1, j2). j1 completes with what my logic defines a "success" status, j2 completes with a "failure x" status, and then b1's `complete` callback fires. I need to know that j2 had an internal failure, and it feels natural to be able to track that info on the batch somehow.

So, 1) is there any way to safely shoehorn this in sidekiq Batches as-is today?, and 2) would it make sense to formally support?

**Comment by mperham** [comment]
Yeah, there's a lot of rakes to step on here so it's best to build your own simple API to store batch data for each job.  Something like:

```ruby
# reopen module to add new method to all workers running in Sidekiq Pro
module Sidekiq::Pro::Worker
  def save_string(msg)
    Sidekiq.redis do |c|
      c..pipelined do
        c.hsetex("#{bid}-strings", jid, msg)
        c.expire("#{bid}-strings", 30*86400)
      end
    end
  end
end
```

Use like:

```ruby
class MyWorker
  include Sidekiq::Worker

  def perform(...)
    begin
      # do work
    rescue => ex
      save_string(ex.message)
    end
  end
end
```

Now you can get all the strings associated with the BID, keyed by the associated JID:

```ruby
Sidekiq.redis {|c| c.hgetall("#{bid}-strings") } # => { "<jid>" => "<msg>" }
```

**Comment by mperham** [comment]
Note the data will stay in Redis for 30 days.  There's no easy way to remove the data so we just let Redis garbage collect it, assuming it won't be high volume.

**Comment by jdc0589** [comment]
yea, the roll-your-own redis version is super easy. Just figured I would check since I have worked with some background job/multistep-transaction frameworks that do support this kind of thing.

Thanks!
