### ISSUE TITLE
Uptime and number of retries related to a specific queue

### ISSUE THREAD

**Issue by nisevi** [mperham/sidekiq#3853]
Ruby version: 2.5.0
Sidekiq-Pro: 4.0.1

Hi, is there a way by using the [Pro-API](https://github.com/mperham/sidekiq/wiki/Pro-API) to retrieve the uptime of a give queue as well as the number of retries?

For example lets say that I have a queue called 'slack' and I'm sending all my slack notifications by using this queue:
- Is there a way to ask for the uptime of the 'slack' queue?
- Is there a way to ask for the numbers of retries related to the 'slack' queue?

I have read that `retries` inside sidekiq it is [orthogonal to the jobs](https://github.com/mperham/sidekiq/issues/845) so the answer is probably no. But I just wanted to be sure that I wasn't missing something in the documentation :+1:

**Comment by mperham** [comment]
In short, no.  You're not missing anything.  That kind of data is not easily calculated.

**Comment by nisevi** [comment]
Thank you very much your quick response @mperham :+1:
