### ISSUE TITLE
callbacks that run when jobs are enqueued

### ISSUE THREAD

**Issue by humzashah** [mperham/sidekiq#3857]
Hi. :wave: 

I want to report various metrics to an agent while my jobs get _enqueued_. I can use the middlewares feature to report job stats when they get _dequeued_ but I also **need** the ability to setup methods that intercept `perform_async`, `push_bulk`, and `push`, for reporting purposes e.g. a graph on a third party tool that shows me spikes of certain jobs being enqueued.

I was thinking of achieving this with another layer of middleware called "enqueuing_middleware" (current one is called "server_middleware"). The middleware addition options would include the method to intercept and the middleware class. For example:

```ruby
Sidekiq.configure_server do |config|
  config.enqueueing_middleware do |chain|
    chain.add :perform_async, ReportPerformAsync
```

**Comment by mperham** [comment]
You want client middleware.  https://github.com/mperham/sidekiq/wiki/Middleware

**Comment by humzashah** [comment]
Thanks for the quick response, @mperham. That's an oversight on my part. However, the docs don't confirm/deny that client middleware will intercept `push_bulk`. Is there an existing way to intercept that?

**Comment by mperham** [comment]
Yep, push, push_bulk and perform_* all run client middleware.  The only edge case where client middleware is not invoked is when Sidekiq Pro's reliable scheduler enqueues a scheduled job atomically via Lua.

https://github.com/mperham/sidekiq/wiki/Reliability#scheduler
