### ISSUE TITLE
Enqueue job outside batch

### ISSUE THREAD

**Issue by lalifraco-devspark** [mperham/sidekiq#3858]
Hi Mike,

Is there a way to enqueue a job without a batch from inside a batch job?
A very simplified example would be:
```
class SimpleBatchWorker
  include Sidekiq::Worker

  def perform()
    batch = Sidekiq::Batch.new
    batch.on(:success, SimpleBatchWorker)
    batch.jobs do
      # do something...

      # I don't want this on the batch,
      # or have to wait for this to complete for the batch to succeed.
      MySimpleWorker.perform_async  
      
      # do something else...
    end
  end
end
```

In the real use case I need to solve, ```MySimpleWorker.perform_async``` is actually fired on an ActiveRecord callback, as a consequence of something I do need to be on the batch.

I could not find anything on the Sidekiq Pro documentation.

Thanks

**Comment by mperham** [comment]
You would need to pull it out of the callback and enqueue it separately.  Any job created within the jobs block will be part of the batch.
