### ISSUE TITLE
The sidekiq daemon dies after few second while adding in script

### ISSUE THREAD

**Issue by rahulmurkute-tudip** [mperham/sidekiq#3860]
This is my script in deploy.rb

namespace :sidekiq do
  task :quiet do
    on roles(:app) do
       execute "pgrep -f 'sidekiq'| xargs kill -USR1"
    end
   end
   task :restart do
     on roles(:app) do
       execute "cd #{current_path} bundle exec sidekiq -C config/sidekiq.yml -d"
     end
   end
end

after 'deploy:starting', 'sidekiq:quiet'
after 'deploy:reverted', 'sidekiq:restart'
after 'deploy:published', 'sidekiq:restart'

My sidekiq process is killed after some seconds while adding above script , I continuously hit the " ps aux|grep 'sidekiq' " on server while deploying. Then I noticed the process id is generated but after few seconds it disappear.

I check the ram and cpu usage that is not a issue.

The important thing if a run the command manually to create daemon it worked successfully. (Not disappear)

Any help would be appreciated.

**Comment by mperham** [comment]
Please read the Deployment wiki page and look into systemd.

**Comment by rahulmurkute-tudip** [comment]
I already read Deployment wiki page and I am booting sidekiq in deploy.rb. I dont think so I have to look into systemd.
I am really stuck into this from last one week.
I have tried so many things but it not helped. 
Please look into this.

**Comment by rahulmurkute-tudip** [comment]
If you know What I am doing doing wrong Please let me know.

**Comment by mperham** [comment]
Learning how to manage system services with systemd is critical to correctly administering your own Linux boxes.  If you don't wish to learn it, you can use Heroku or another PaaS.

https://github.com/seuros/capistrano-sidekiq#integration-with-systemd
