### ISSUE TITLE
Sidekiq Server not loading Rails configuration

### ISSUE THREAD

**Issue by plribeiro3000** [mperham/sidekiq#3861]
Ruby version: 2.5.1
Rails version: 5.2.0
Sidekiq version: 5.1.3
Running on Heroku + PgBouncer

For performance reasons i did set `Rails` `belongs_to_required_by_default` config to false so i don't get extra queries being executed. 
If i load the rails console through `heroku run rails c` and execute my Worker synchronously my code works but when running through sidekiq asynchronously it get validations issues for all the fields i do not want to be validated.
If i force it to be optional with `optional: true` it works
I did also try to remove PGBouncer but it did not work either.

I did find this rails issue: rails/rails#27777 but since i don't have enough knowledge of the codebase of sidekiq i don't know where to look.

Initializers:

`config/initializers/sidekiq.rb`
```ruby
require 'sidekiq'
require 'sidekiq/middleware/i18n'
require 'configuration'

configuration = Configuration.new

Sidekiq.configure_client do |config|
  config.redis = configuration.sidekiq_client
end

Sidekiq.configure_server do |config|
  config.redis = configuration.sidekiq_server

  # Sidekiq::Cron initialization
  Sidekiq::Cron::Job.load_from_hash YAML.load_file('config/sidekiq-schedule.yml')

  ar_configuration = ActiveRecord::Base.configurations[Rails.env]
  ar_configuration['pool'] = 25
  ActiveRecord::Base.establish_connection(ar_configuration)
end
```

`config/initializers/rails_config.rb`
```ruby
Rails.application.config.active_record.belongs_to_required_by_default = false
```

`lib/configuration.rb`
```ruby
class Configuration
  def puma_workers
    Integer(ENV.fetch('WEB_CONCURRENCY', 2))
  end

  def puma_threads
    [2, Integer(ENV.fetch('WEB_MAX_THREADS', 5))].max
  end

  def sidekiq_client
    {
      driver: :hiredis,
      url: redis_url,
      size: puma_workers * (puma_threads / 2)
    }
  end

  def sidekiq_server
    {
      driver: :hiredis,
      url: redis_url
    }
  end

  private

  def redis_url
    ENV.fetch('REDIS_URL')
  end
end
```

`Procfile`
```ruby
web: bin/start-pgbouncer-stunnel bundle exec puma -C config/puma.rb
worker: bin/start-pgbouncer-stunnel bundle exec sidekiq
```

`sidekiq.yml`
```yaml
:queues:
  - [default, 1]
  - [dashboard, 1]
  - [document_processing, 2]
  - [commission_processing, 4]
  - [statement_generation, 5]
  - [attachment_processing, 7]
  - [attachment_expiring, 8]
  - [company_session_destroyer, 10]
  - [data_dog, 10]
  - [rollbar, 10]
```

`sidekiq.yml`
```yaml
attachment_expirator:
  cron: '0 1 * * *'
  class: 'AttachmentExpirator'
```

**Comment by mperham** [comment]
How are you restarting the worker?

**Comment by mperham** [comment]
puma has nothing to do with sidekiq.  you need to restart the worker dyno to pick up code changes although a redeploy should do that.  Other people who reported this problem invariably find that they are doing something wrong and they aren't actually changing the code in Heroku.

**Comment by plribeiro3000** [comment]
I agree `puma` has nothing to do with `sidekiq`.
I only pasted it here to show i'm not controlling any restart (and i do agree it was kind of dumb of me)

I've spent the last day looking into this and i couldn't find anything obvious.
Sidekiq is loading all the configurations inside my `config/initializers`. I can confirme because Sidekiq is using `hiredis`
I've tried removing al gems that could be troublesome and got no sucess

I'm starting to think that maybe this rails configuration has a race condition or something.

But then i found rails/rails#23589 and more precisely https://github.com/rails/rails/23589#issuecomment-221036080

Maybe there is something to be done here too?

**Comment by mperham** [comment]
That sounds plausible. Thanks for sharing that link. Rails app initialization can be tricky; Sidekiq just kicks off the app boot process, it can’t control or fix load order issues.

**Comment by plribeiro3000** [comment]
So what does that mean exactly?

Is it out of `Sidekiq` scope or does not worthy the trouble?

**Comment by mperham** [comment]
It’s impossible for Sidekiq to fix a Rails initializer bug.

**Comment by plribeiro3000** [comment]
I originally though it was more like a problem with the plugins hooking into `rails` to soon but it might be a rails bug like you mentioned. I think its worthy to wait a bit and see what happens.

Anyway, i'm fine for now since i did add `optional: true` to all my associations.

So we are good here (at least for now) =D

Thanks for your support!

**Comment by robinsingh-bw** [comment]
For anyone else who runs into this, also add this to your initializer file:
`ActiveRecord::Base.belongs_to_required_by_default = false`
