### ISSUE TITLE
Feature Flow 

### ISSUE THREAD

**Issue by nsushmitha** [mperham/sidekiq#3862]
How scheduled set jobs workflow happen? Is there any detailed documentation on that?

**Comment by mperham** [comment]
I don’t understand your question. Please expand.

**Comment by nsushmitha** [comment]
So when I enqueue a job using set(wait: time), the job gets pushed into the scheduled set. Every n seconds a poller checks the scheduled set, and pops the jobs whose scheduled time has exceeded or equal to current time. So what happens after that? The job gets pushed into the enqueued queue. But there is a delay. So there is an interval where the job is neither present in scheduled set or the enqueued queue.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Reliability#scheduler
