### ISSUE TITLE
Sidekiq JobRetry and shutdown while job is in progress skips client middleware 

### ISSUE THREAD

**Issue by alecjacobs5401** [mperham/sidekiq#3863]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.1.3, Pro 4.0.2

Example Intializer:
```ruby
Sidekiq.configure_server do |config|
  config.reliable!
  config.average_scheduled_poll_interval = 1

  config.server_middleware do |chain|
    chain.add SidekiqLogging::Server
  end

  config.client_middleware do |chain|
    chain.add SidekiqLogging::Client
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add SidekiqLogging::Client
  end
end
```
where `SidekiqLogging::Client` and `SidekiqLoggin::Server` are just simple middleware that log some debug information for me to prove the issue.

I'm noticing that failed jobs that retry or jobs that are killed and moved back to their original queue by `SuperFetch` will execute the Server middleware, but not the client middleware when the second Sidekiq process picks up the work (if it is configured for the server to run as well). 

Is it the intended case for this to happen? If I'm using the `sidekiq-unique-jobs` gem, this means that I'm clearing my unique lock but the job is immediately picked up in another Sidekiq process without setting the lock again.

Initial Sidekiq process picking up job: (note the `hit the client middleware!` log line)
![Initial Sidekiq Process Working](https://user-images.githubusercontent.com/12898497/41117011-b9c8224e-6a40-11e8-88e8-fef0c5abfc06.png)

Second Sidekiq process picking up job after first process restarts: (note no `hit the client middleware!` log line)
![screen shot 2018-06-07 at 10 50 56 am](https://user-images.githubusercontent.com/12898497/41117068-ddbbd5b0-6a40-11e8-8019-0efd22dcb057.png)

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Reliability#scheduler

> This feature is optional but highly recommended to enable. It does have the drawback that client-side middleware is not invoked when enqueuing the scheduled jobs, since the entire operation takes place within Redis.

**Comment by alecjacobs5401** [comment]
Ah. I see. 
Thanks for dropping the knowledge bombs! (probably should have _really_ dug through the wiki again)

**Comment by mperham** [comment]
The Enterprise unique jobs page documents several caveats like this.  I can't speak for sidekiq-unique-jobs.

https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs
