### ISSUE TITLE
Redis Memory Error

### ISSUE THREAD

**Issue by taylorbrooks** [mperham/sidekiq#3864]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 4.2.9

I don't think this is a Sidekiq issue per se... but I've been getting memory errors from Redis lately: `Redis::CommandError: OOM command not allowed when used memory > 'maxmemory'`

When I sample some keys stored in Redis, this is what I get:
<img width="921" alt="screen shot 2018-06-10 at 1 53 17 pm" src="https://user-images.githubusercontent.com/117657/41205397-606bd3ba-6cb8-11e8-8864-b15c62e0733a.png">

I feel like I shouldn't have that many keys with `sidekiq:queue:backup:*`, but I'm not sure what's creating so many or how/if I they should be expiring...

**Comment by mperham** [comment]
what are the actual names of the “back” keys?  what is the output of “redis-cli info”?

**Comment by taylorbrooks** [comment]
![screen shot 2018-06-10 at 8 31 29 pm](https://user-images.githubusercontent.com/117657/41208929-55df87d6-6ced-11e8-94be-e4ad0cd61500.png)

**Comment by mperham** [comment]
what are the actual names of the “back” keys?

**Comment by taylorbrooks** [comment]
I figured out that the backup keys were coming from this library I'm using in Elixir: https://github.com/akira/exq/blob/master/lib/exq/redis/job_queue.ex

Basically I'm using Redis as a message bus between two apps. There's something funky the Elixir client is doing. 

Closing. Thanks for taking a look!
