### ISSUE TITLE
PID not being deleted

### ISSUE THREAD

**Issue by rainerborene** [mperham/sidekiq#3867]
If you start `sidekiq` with the following command the `pidfile` is created successfully but not deleted after the process is shutdown.

    $ sidekiq -P /var/run/sidekiq.pid

I guess the `pidfile` should be deleted after finishing the shutdown process. Today, only if you invoke `sidekiqctl stop` will ensure that the file is deleted, as you can see on [this line](https://github.com/mperham/sidekiq/blob/master/bin/sidekiqctl#L76). I think this is a bug, or inconsistent at least.

**Comment by mperham** [comment]
Sidekiq will create a PID file but it won't delete it.  Whatever is managing the Sidekiq process should delete it upon confirming that Sidekiq has exited.
