### ISSUE TITLE
Filtering of to-be-retried jobs ('retries') does not work in Sidekiq Web UI

### ISSUE THREAD

**Issue by koenrh** [mperham/sidekiq#3869]
Ruby version: **2.5.1**
Sidekiq / Pro / Enterprise version(s): Sidekiq **5.1.3**, Sidekiq Pro **4.0.3**

The 'Failures' section on the batch details page (e.g. `/batches/[id]`) list failed jobs that "deeplink" (e.g. `/filter/retries?substr=[job_id]`) to that particular job on the 'retries' page. However, that filtering (scanning) does not seem to work at the moment. When following these links, you get always redirected to the 'retries' page, without any filtering being applied.

Observed behavior:

1. Client sends GET request to `/filter/retries?substr=33600ae3f5e7921dc8aced9f` (job ID)
2. Client is redirected (302) to `/retries`

Expected behavior:

1. Client sends GET request to `/filter/retries?substr=33600ae3f5e7921dc8aced9f` (job ID)
2. The retry set is filtered based on the provided `substr` parameter, and the result set is rendered.

---

It seems the issue is caused by the use of the equality operator in the following route in `lib/sidekiq/pro/web.rb`:

```ruby
app.get '/filter/retries' do
  x = params[:substr]
  return redirect "#{root_path}retries" unless x && x == ''
  @retries = search(Sidekiq::RetrySet.new, params[:substr])
  erb :retries
end
```

It currently just redirects the client to the 'retries' page if any value is provided for the parameter 'substr'. Unless I'm missing something obvious, that equaliy-to operator (`==`) should likely be replaced with the not-equal-to operator (`!=`) operator.

**Comment by mperham** [comment]
Wow, 18 month old typo bug.  Good find!
