### ISSUE TITLE
Sidekiq with ruby 1.9.3

### ISSUE THREAD

**Issue by vishnurkrishnan** [mperham/sidekiq#3872]
Ruby version: **1.9.3**
Rails Version: **3.2.22**

I have been using delayed_job_active_record gem since 2014 and now the application has to run lots of background jobs so decided to use sidekiq. I was trying to install sidekiq **4.0.0** and  **'redis', '~> 3.0', '>= 3.0.6'**, when i am doing the bundle i am getting this error:

![screen shot 2018-06-22 at 12 45 58 pm](https://user-images.githubusercontent.com/5127803/41762980-434b3706-761a-11e8-88de-53a0bbf3d379.png)

I also have tried some other version but still i am getting this error, also i would like to know which is the  compatible version  of sidekiq which i can use it with ruby 1.9.3?

Also i would like to know is there any other gem versions do we need to consider like redis....?

**Comment by mperham** [comment]
I haven't supported Ruby 1.9.3 for 4 years now, since Sidekiq 2.x.
