### ISSUE TITLE
Commercial license ambiguity

### ISSUE THREAD

**Issue by latortuga** [mperham/sidekiq#3873]
Sections 1.2 and 1.3 of the COMM-LICENSE file seem to be a bit ambiguous about naming the Unlimited and Limited organization licenses (emphasis mine):

> 1.2 **Unlimited Organization License**. If you purchased an **Organization License** (included with the Sidekiq Pro Software), you may install the Software on an unlimited number of Hosts. “Host” means any physical or virtual machine which is controlled by you. You may also run an unlimited number of Workers. “Worker” means a thread within a Sidekiq server process which executes jobs. You may concurrently run the software on an unlimited number of Hosts, with each host running an unlimited number of Workers.
> 1.3 **Limited Organization License**. If you purchased an **Organization License** (included with the Sidekiq Enterprise Software), you may install the Software on an unlimited number of Hosts. “Host” means any physical or virtual machine which is controlled by you. The aggregate number of Workers run by the hosts must not exceed the maximum number of Workers authorized at the time of purchase. “Worker” means a thread within a Sidekiq server process which executes jobs. In order to run additional Workers, you must purchase an additional allowance from Contributed Systems. 

This reads to me as though a single kind of Organization License is included with both Sidekiq Pro and Sidekiq Enterprise, and I think it's meant to be Unlimited with Pro and Limited with Enterprise.

**Comment by mperham** [comment]
Yes, sorry for the vagueness.  It is meant to be limited in Enterprise.  An Enterprise customer may only use N threads, even if those threads only use Sidekiq Pro functionality.

**Comment by mperham** [comment]
A customer may elect to purchase a separate Pro license and use that with their "large" apps, saving their Enterprise thread count for one or two special apps.
