### ISSUE TITLE
after_save callback not working properly with delay sidekiq extension

### ISSUE THREAD

**Issue by shilpi230** [mperham/sidekiq#3875]
Ruby version: 2.1.3
Sidekiq / Pro / Enterprise version(s): 4.2.10

I have a model, which has one callback and that callback is going through delay sidekiq extension. And when lastly, it goes to method `update_version_of_handle ` it should go inside the if block, but because sidekiq is available before it commit to the db it keeps saying false.

```
after_save :update_color

def update_color
   Car.sidekiq_delay_for(1, :queue => Sidekiq::Queues::DEFAULT_QUEUE).update_color(self.id)
end

def self.update_color(id)
  car = Car.find_by_id(id)
  car.update_version_of_handle
end

def update_version_of_handle
  if car.some_attribute_changed? 
     puts "Yes changed"
  end
end
```

**Comment by mperham** [comment]
`after_commit :update_color`

This is covered in the documentation:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting
