### ISSUE TITLE
JID processed multiple times

### ISSUE THREAD

**Issue by andydust** [mperham/sidekiq#3876]
Ruby version: ruby-2.4.4p296
Sidekiq / Pro / Enterprise version(s): 5.0.5 / 4.0.0

Frequently we are seeing a distinct JID being processed multiple times. This is within the same process albeit on different thread IDs. For each duplication the job lifecycle appears to complete successfully (there is a START log entry and a DONE entry each time for the JID). However, this is usually followed by the below.

> ERROR: Unable to remove job from private queue...

These are very long running jobs, usually over an hour in duration.  The duplications dont appear to overlap, but are produced sequentially.

**Comment by mperham** [comment]
Hmmm. Show me your initializer.

**Comment by andydust** [comment]
The initialiser is below. My current hunch is that because Superfetch cannot remove the jobs from the private queue, they are being requeued as orphans whenever the orphan check next happens to run. I'll see if I can send which JIDs are being sent back to the queue to the debug log...

```ruby
require 'sidekiq'
require 'sidekiq-status'
require 'sidekiq/scheduler'
require 'datadog/statsd'

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.default_worker_options = { 'queue' => "default.#{Worker.archive}" }

# Status
Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 72.hours # default
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 72.hours # default
  end
end

# Super fetch
Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end

# Metris
Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new("127.0.0.1", 8129) }
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end
end

# Scheduler
Sidekiq.configure_server do |config|
  config.on(:startup) do
    if Rails.env.production?
      Sidekiq.schedule = YAML.load_file(File.expand_path('../../sidekiq_schedule.yml', __FILE__))
      Sidekiq::Scheduler.reload_schedule!
    end
  end
end
```

**Comment by mperham** [comment]
The only thing I've seen cause that error is the following steps:

1. Enqueue a job
2. super_fetch moves a job from public queue to private queue
3. Application code calls FLUSH{DB,ALL} to clear Redis completely.
4. super_fetch finishes job and tries to remove job from private queue.
5. remove fails because everything was deleted in 3.

So generally there is some code deleting the job or queue somehow but I can't guess who or why.
