### ISSUE TITLE
Small typo on restarts page

### ISSUE THREAD

**Issue by jcavalieri** [mperham/sidekiq#3881]
Hi Mike,

Small typo on this page
https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts

> a Sidekiq process will **quiet** immediately

Ruby version: n/a
Sidekiq / Pro / Enterprise version(s): n/a

Please include your initializer and any error message with the full backtrace.
n/a

-John

**Comment by mperham** [comment]
Quiet is the correct term. That’s what TSTP does.

**Comment by jcavalieri** [comment]
Ahh. Good to know.

_______________
John Cavalieri
