### ISSUE TITLE
sidekiq was stopped suddenly

### ISSUE THREAD

**Issue by hoanglannet** [mperham/sidekiq#3882]
Ruby version:
Sidekiq, 2.17.8

Hi all,

Recently, I got the sidekiq stopped suddenly after we started generating an excel report via sidekiq. I am not sure it's from this or not.

we are running 4 EC2 instances, sidekiq connecting with redis.
That was terrible! when a sidekiq stopped in one EC2, then three remaining EC2 sequently stopped, that was leading sidekiq in the whole system was stopped. 

Could you expert guys let me what the reason sidekiq stopped in any cases? 
Thank you,
Lan

-------------
Here is our config:

uri = ENV["REDIS_URL"]

Sidekiq.configure_server do |config|
  config.redis = { url: uri, size: Sidekiq.options[:concurrency] + 2, namespace: "default" } 
end

Sidekiq.configure_client do |config|
  config.redis = { url: uri, size: 1, namespace: "default" }
end

**Comment by mperham** [comment]
You're running a very old version - you really should consider upgrading to something modern.  Sidekiq 2.x is about 5 years old.

There's no way for me to know why your process crashed.

I would remove the sizing from your Redis config, it is unnecessary.
