### ISSUE TITLE
Jobs in queue, workers don't process jobs

### ISSUE THREAD

**Issue by kevin-jj** [mperham/sidekiq#3883]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): sidekiq

I deploy our app at local docker. Web and sidekiq is in a separated container

Jobs in queue, workers don't process jobs. Sidekiq keep idle status.

**Executing kill -TTIN pid get the following info:**

2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: Thread TID-gnfirvpa1 
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `sleep'
sidekiq_1        | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:299:in `block (2 levels) in run'
sidekiq_1        | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:298:in `loop'
sidekiq_1        | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:298:in `block in run'
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: Thread TID-gnfj0xkk5 
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:307:in `readpartial'
sidekiq_1        | /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:307:in `readpartial'
sidekiq_1        | /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:278:in `read_events'
sidekiq_1        | /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:242:in `process'
sidekiq_1        | /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:225:in `run'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: Thread TID-gnfj0xkcx 
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/config.rb:19:in `sleep'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/processor.rb:59:in `_sleep'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/processor.rb:84:in `_wait_until_events'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/processor.rb:16:in `block in loop_for'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
sidekiq_1        | /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: Thread TID-gnfiqlqf1 
sidekiq_1        | 2018-07-11T10:21:19.756Z 1 TID-gnfi1xlvd WARN: /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:307:in `readpartial'
sidekiq_1        | /usr/local/bundle/gems/rb-inotify-0.9.10/lib/rb-inotify/notifier.rb:307:in `readpartial'

any idea? @mperham Thanks.

**Comment by taq** [comment]
Did you figured out what was wrong? Just got on the same situation here.
