### ISSUE TITLE
[Ent] RuntimeError: Unknown platform: x86_64-freebsd11.0, memory monitoring not available

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#3884]
Ruby version: 2.3.4
Sidekiq / Pro / Enterprise version(s): 1.7.1

Please include your initializer and any error message with the full backtrace.
env SIDEKIQ_COUNT=2 SIDEKIQ_MAXMEM_MB=1024 RAILS_ENV=production bundle exec sidekiqswarm -e production -c 16 -q high -q default -q low

```
RuntimeError: Unknown platform: x86_64-freebsd11.0, memory monitoring not available, please open an issue
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:141:in `ps_cmd'
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:54:in `monitor'
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:44:in `start_and_monitor'
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/gems/sidekiq-ent-1.7.1/bin/sidekiqswarm:51:in `<top (required)>'
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/bin/sidekiqswarm:22:in `load'
  /usr/home/rails/apps/r/vendor/bundle/ruby/2.3.0/bin/sidekiqswarm:22:in `<top (required)>'
```

sidekiqswarm errors out with the above error message. The sidekiq workers themselves continue to run.

**Comment by mperham** [comment]
I’ll get back to you Monday and add FreeBSD support for you.

**Comment by mperham** [comment]
Can you help me with the correct FreeBSD command?  This works on Darwin, does it work on FreeBSD?

```
ps -o ppid,pid,rss | grep ^#{$$}
```

**Comment by kreynolds** [comment]
Looks like you want to find processes spawned by the parent of the current shell, for FreeBSD I believe you need
```
ps -o ppid,pid,rss | grep -e "^$$"
```

**Comment by mperham** [comment]
Cool, that works on Darwin too so FreeBSD can use the same logic.

**Comment by mperham** [comment]
What does `puts RUBY_PLATFORM` print on freebsd?

**Comment by mperham** [comment]
nevermind, there it is at the top!
