### ISSUE TITLE
Incomplete / invalid JSON saved to Redis as job payload

### ISSUE THREAD

**Issue by steakchaser** [mperham/sidekiq#3887]
Ruby version: 2.5.1
Sidekiq: 5.0.5 (have also tried with 5.1.3)

```
json: 1.8.6
redis: 4.0.1
sidekiq-throttled: 0.8.2
``` 

Just attempted a Rails 4.2.10 -> 5.2.1 upgrade and started getting very bizarre errors emanating from Sidekiq jobs when being processed under load.  Can't yet reproduce this in a staging or local environment.

The gist of the error is that we see jobs fail at random times because they are sending **invalid JSON** to various REST APIs.  Then, when the job is written back to the queue, the resulting job payload is also invalid; from here retries fail until dead.  Here's an example of a dead job.

**Error:** (Notice how the job args are actually valid)
```
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: 784: unexpected token at '{"class":"MyModule::EmailSyncWorker","args":[{"data":{"setting-1":1,"setting-2":1,"email_setting_link":"https://www.example.com/email-preferences/12345?email=email628%40example.com","first_name":"First Name","last_name":"Last Name","last_opened_at":null,"setting-3":1,"setting-4":1,"user_created_at":"07/13/2018"},"email":"email@example.com","previous_email":null}],"retry":true,"queue":"email_sync","jid":"6cfc0117bec4383ce3b755ab","created_at":1531515580.7988615,"enqueued_at":1531515580.7989'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:172:in `load_json'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:26:in `block (2 levels) in enqueue_jobs'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:15:in `each'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:95:in `block in redis'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
2018-07-13T19:53:56.196Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:77:in `enqueue'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:68:in `block in start'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
2018-07-13T19:53:56.197Z 9529 TID-1dtsj0 ERROR: /ruby/2.5.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

We have no idea why invalid JSON is being generated, either to the REST API or when saving the job for retry.  Maybe a random class loading issue, something not thread-safe?

Wondering if anyone here has any ideas?

Initializer.

```ruby
Sidekiq::Extensions.enable_delay!

# Perform Sidekiq jobs immediately in development, so you don't have to run a separate process.
if ENV['SIDEKIQ_STATUS'] == 'off'
  require 'sidekiq/testing'
  Sidekiq::Testing.inline!
end

# Setup throttling for dealing with rate-limited APIs
require 'sidekiq/throttled'
Sidekiq::Throttled.setup!
```

**Comment by mperham** [comment]
I've never seen this error, it's likely something specific to your app/env.

**Comment by mperham** [comment]
Please reopen if you determine a root cause that I can help with.

**Comment by steakchaser** [comment]
Hi @mperham - still struggling with this one.  Have a little more information.  Wondering if you have any ideas?

Here's a quick example...

1. We make an API call using Net:HTTP, which raises an error stating that the request contained invalid JSON: `{"foo": "b`
2. Subsequent Sidekiq operations attempt to use the rest of the JSON payload `Redis::CommandError: ERR unknown command 'ar"}'`

Here's a real error:

```
2018-10-12T23:36:10.622Z 24249 TID-jiqzl ERROR: ERR unknown command '0}'
2018-10-12T23:36:10.622Z 24249 TID-jiqzl WARN: Redis::CommandError: ERR unknown command '0}'
2018-10-12T23:36:10.623Z 24249 TID-jiqzl WARN: /var/www/my_production/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis/client.rb:119:in `call'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/redis.rb:74:in `call'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:1858:in `block in zrangebyscore'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:45:in `block in synchronize'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:45:in `synchronize'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:1857:in `zrangebyscore'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:15:in `each'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:95:in `block in redis'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:92:in `redis'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:77:in `enqueue'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:68:in `block in start'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:16:in `watchdog'
/var/www/my_production/shared/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Also, of note:

1. This occurs randomly - we can sometimes run for 30 minutes without a single error.
2. We've tried running Sidekiq with only a single process, and still see the error.

**Comment by mperham** [comment]
Why would a Redis socket share data with a Net::HTTP call?  That error makes no sense to me, even with a race condition.

I can’t support and don’t know what Sidekiq throttled does.  Does anything change if you remove it?

**Comment by aflanagan** [comment]
Hi @mperham, I've been working on this issue with @steakchaser. We are having a really hard time articulating this issue because it is so strange. However, I wanted to clarify a couple of points.

1. Even though we use the sidekiq throttled gem for some of our throttled queues I don't think that has anything to do with the issue (we mainly see this on queues that are only managed by sidekiq).

2. The problem manifests itself when a sidekiq worker sends a JSON payload to an API endpoint that we call heavily from our workers. The API responds that it was given invalid JSON. When we look at those payloads we can see that it's true, the payloads are invalid, and furthermore the data we expect to see is truncated, and some of the job fields are present. Here's an example (truncating the beginning of the payload for brevity)

```
...
\"fullsize_img_url\":\"https://res.cloudinary.com/xxxx/image/upload/f_auto,q_","error_class":"SendWithUs::ApiBadRequest","failed_at":1539390996.137958,"retry_cou'
```

The URL is truncated and there should be a few more fields from our payload in there. Instead we see the error_class from a previous call and you can see the `retry_count` is also cut off.

At the same time we start seeing the following exceptions bubbling up. 

```
Error message
Redis::CommandError: ERR invalid cursor

Sample stack trace (show Rails)
…bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis/client.rb: 200:in `call_pipelined'
…bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis/
client.rb: 158:in `block in call_pipeline'
…bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis/client.rb: 294:in `with_reconnect'
…bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis/client.rb: 156:in `call_pipeline'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:2317:in `block in pipelined'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:  45:in `block in synchronize'
…/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb: 226:in `mon_synchronize'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:  45:in `synchronize'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.2/lib/redis.rb:2313:in `pipelined'
…undle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/api.rb: 746:in `block in cleanup'
…ed/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:  95:in `block in redis'
….5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:  65:in `block (2 levels) in with'
….5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:  64:in `handle_interrupt'
….5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:  64:in `block in with'
….5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:  61:in `handle_interrupt'
….5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:  61:in `with'
…ed/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:  92:in `redis'
…undle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/api.rb: 744:in `cleanup'
…undle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/api.rb: 737:in `initialize'
…ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb: 155:in `new'
…ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb: 155:in `process_count'
…ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb: 120:in `random_poll_interval'
…ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:  89:in `wait'
…ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/scheduled.rb:  69:in `block in start'
…ndle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:  16:in `watchdog'
…ndle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/util.rb:  25:in `block in safe_thread'
```

````
Redis::CommandError: ERR unknown command 'l}'
…bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:  119:in `call'
…5.2.0.345/lib/new_relic/agent/instrumentation/redis.rb:   74:in `call'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb: 2003:in `block in hset'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:   45:in `block in synchronize'
…/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:  226:in `mon_synchronize'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:   45:in `synchronize'
…shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb: 2002:in `hset'
````

Redis is getting commands issued that look like the endings of previous payloads, and I'm guessing those invalid cursor errors are similarly related.

While all of this is happening our webservers are also running Rails 5 and talk to Redis on every request. We see no errors there, only from within Sidekiq jobs.

We're really grasping at straws trying to figure out what would corrupt Redis like this. Any ideas/suggestions you have would be very appreciated.

**Comment by mperham** [comment]
It looks like you have a bare socket exposed to multiple threads, causing race conditions from every thread sharing the same data.  Make sure all your Redis clients are properly locked (the redis gem does this by default).

**Comment by aflanagan** [comment]
@mperham thanks for the quick reply. That's been our hypothesis as well. 

We tried to test that hypothesis by running sidekiq single threaded, and unfortunately we still see the same problem. Is it possible for connections (via connection pool) to be shared across sidekiq processes? Is there something else that could explain how it's happening in a single threaded environment?

We only connect to redis using the redis gem (v4.0.2), both from our webservers and our workers via sidekiq. Do you have any ideas/suggestions how to test this hypothesis further?

**Comment by mperham** [comment]
Sidekiq has several internal threads using Redis concurrently.  You can’t avoid multithreading in that sense.

**Comment by aflanagan** [comment]
@mperham ok, that makes sense.

Clearly some change in our environment has caused this, but we are finding it very difficult to debug:

- We haven't successfully replicated it on a staging environment even when trying to simulate load/jobs
- This is only occurs on a worker server that only executes rake tasks (on cron jobs) and runs Sidekiq
- Sidekiq is the only multithreaded library that we use that connects to Redis

Have you ever encountered this type of bug in the past when working with multi-threaded ruby code?
Could you offer any recommendations on where you would start looking next?

I know you're quite busy, thanks for taking the time to read/reply to these.

**Comment by mperham** [comment]
I've never seen this before.  You're doing something very wrong but I have no idea what it is.  Do you have some weird JSON hacks or gem setup that's possible unsafe?  Make sure you are using the stock, default JSON gem only.

Trying to reproduce it is key: with a small app or on staging.

**Comment by mperham** [comment]
maybe you can git bisect your codebase to narrow down when the bug appears?
