### ISSUE TITLE
safe+easy way to move an existing job to a new queue?

### ISSUE THREAD

**Issue by jdavisclark** [mperham/sidekiq#3888]
Ruby version: 2.2.2
Sidekiq / Pro / Enterprise version(s):
Sidekiq v4.2.10 / Sidekiq Pro v3.7.1

**Scenario:** I have a job that's been live for a long time, `Job1`. Job1 is currently on queue `multipurpose`. I need to move Job1 to queue `just_for_job1` so I can give it dedicated workers+queue.

**Problem**: My workers exist in a (versioned) shared gem consumed by multiple (3) services. If I just change over to `just_for_job1` queue, then my updated workers are only going to be listening on `just_for_job1`, but some jobs will still be enqueued to `multipurpose` until a gem update rolls out to all the consuming services.

Am I missing some easy way to make this transition, or do I literally have to create a worker with a new name that specifies the new queue, get all the consuming applications producing jobs via the new worker, and then deprecate the old one? (thats totally do-able, its just a lot of extra steps I'd love to avoid)

**Comment by mperham** [comment]
Jobs are persistent, which means you need to treat any changes to that persistent data like a migration.  Your last paragraph sums it up: run old and new in parallel unless you can verify that old jobs are gone.  Remember that jobs can stick around in the retry queue for weeks.

**Comment by jdavisclark** [comment]
that's what I figured. I was hoping maybe there was some hidden magic "consume multiple queues from one worker" option or something that would make it a bit easier. but, oh well.

thanks.

**Comment by mperham** [comment]
`sidekiq -q oldname -q newname`

**Comment by jdavisclark** [comment]
not what I meant, but I'm good.
thanks for the quick response.
