### ISSUE TITLE
Scheduled set not enqueueing due to large retry set

### ISSUE THREAD

**Issue by sb8244** [mperham/sidekiq#3889]
Sidekiq / Pro / Enterprise version(s):

Sidekiq 4.2.10
Pro 3.5.0

I have noticed a problem where my schedule set doesn't enqueue for 10-20 minutes, usually once per hour. I have whittled it down to the fact that retry/schedule happens in the same poller, and my retry set is quite large (>100k entries). My theory currently is that the retry enqueueing is taking quite a long time to operate, which is causing the scheduled enqueueing to be delayed by that much time.

Is it possible for users of Sidekiq to separate the retry / schedule enqueueing into different actors? In this way, they could execute simultaneously rather than one after the other. I have checked 5.x vs 4.x but I do not see a difference.

I looked at the option of putting the set order to `scheduled, retry` in the Enq class, but I think that this would not help because the retry enqueueing would still take the same amount of time and execute in the same thread as scheduled.

I could also be wrong and this isn't related to the size of the retry set at all. The redis cluster isn't reacting negatively during it.

**Comment by mperham** [comment]
Have you activated the reliable scheduler?  Your Pro version is pretty old too, upgrade.

**Comment by sb8244** [comment]
This queue is not reliable.

I'll look at getting us upgraded.

**Comment by mperham** [comment]
The scheduler is different from the fetcher. I would turn on the reliable scheduler and see if that helps performance, it should.

**Comment by sb8244** [comment]
Thanks Mike. I will try out the reliable scheduler.

I appreciate your help on this problem.

**Comment by sb8244** [comment]
With reliable scheduler active, I am seeing the 15-20 minute retry/scheduled enqueueing still occurring. To be clear, this is what it ends up looking like:

![image](https://user-images.githubusercontent.com/1231659/42826913-8851ddf8-89b3-11e8-8d22-12ede4563cf0.png)

Does the `average_scheduled_poll_interval` significantly impact this? We have it at the pre 5 default (15).

The retry queue ends up facing the same symptoms, no retries occurring for 10-20 minutes sometimes.

**Comment by mperham** [comment]
Can you supply your initializer?

**Comment by sb8244** [comment]
I don't think I can supply that on Github unfortunately. Are there certain things I would be able to pick out that you'd be looking for?

**Comment by mperham** [comment]
You can email it to support @ contribsys.com for me to examine privately.

**Comment by sb8244** [comment]
Thanks @mperham I sent that over.

I was just checking out the effect of reliable scheduler. Set based commands is way down, which I believe is from that.

My next plan of action is to place loggers when the Scheduled::Poller starts / finishes a queue.

**Comment by mperham** [comment]
I would also check out your SLOWLOG and see if there's anything causing problems with Redis.  Read:

https://www.mikeperham.com/2017/04/20/monitoring-redis/

**Comment by mperham** [comment]
Initializer looks ok.  You've got a lot of custom middleware but I don't see any red flags.

**Comment by sb8244** [comment]
I just checked this out. I do see some entries from yesterday, but none in the past 5 hours:

```
irb(main):041:0> log = $redis.slowlog('GET', 200) ; log.count
=> 128
irb(main):042:0> log.select { |l| l[1] > (Time.now.to_i - (60*60*5)) }.count
=> 0
```

I am not sure what it's configured to, but I will assume 10ms since I see 1 bulk enqueue for 12ms in it.

**Comment by mperham** [comment]
If you open a console in production and run `require 'sidekiq/api';Sidekiq::ProcessSet.new.size`, what does it return?

I would set average_scheduled_poll_interval to 5 now.  There's no reason to set it as high as 15 anymore.

**Comment by mperham** [comment]
And I know I've heard of this problem before but I can't find any previous issue for it.  Can you get onto Sidekiq 5?

**Comment by mperham** [comment]
Are you actually running 169 Sidekiq processes?  If not, they aren't shutting down cleanly and the extra process entries are adversely affecting the initial scheduler delay.  See lib/sidekiq/scheduled.rb for details.

**Comment by sb8244** [comment]
We are running exactly 169 processes

**Comment by sb8244** [comment]
After reading the code for how interval polling happens, it entirely makes sense of why we're seeing the delay on boot. 169*15 = 2535s average. An initial 

I've annotated the method below with average wait. Is this correct?

```
      def start
        @thread ||= safe_thread("scheduler") do
           # 5-15s initial wait time due to no special configuration
          initial_wait

          while !@done
            # executes 1 time for each process on boot
            enqueue

            # 2535 +- 50% = (1267, 3802) = (21min - 63min)
            wait
          end
          Sidekiq.logger.info("Scheduler exiting...")
        end
      end
```

The solution here could be to set `Sidekiq.options[:poll_interval_average]` to something reasonable but much smaller. Combined with reliable scheduler optimizations, the calls to redis should be okay.

**Comment by mperham** [comment]
That's an abnormally large number of processes, which is why I'd only seen this issue once before.

Reducing from 15 to 3 should cut that delay down.  I'm welcome to suggestions for improvement; I'd like this to scale to your numbers.

**Comment by sb8244** [comment]
Thanks for your advice Mike. I am happy to explain in a different place why we have so many processes, if it helps you out.

I'm going to try reducing from 15 to 3 to see how it works. The math works out to roughly a 225s delay on reboot. I think that the problem that I'm seeing is the difference between starting up and the long term running of a process. In our case, the long term execution is great, but startup has a gap. Having more control over the initial wait time (maybe a config) could be useful.

Another idea could be to allow turning off the scheduled poller on a sidekiq instance. This would allow us to have the task performed distributed (no single point of failure) and also configure what the `poll_interval_average` is based on the number of nodes that are allowed to run the scheduled poller.

**Comment by sb8244** [comment]
1 more solution that was suggested by my teammate. She pointed out that we could set the interval value on a small set of boxes manually, and let the rest work by default. As such, we have 12 of our pods running on `poll_interval_average=24`, and the rest running `average_scheduled_poll_interval=3`. This should decrease the initial startup time and not overwhelm redis in the long run.

**Comment by mperham** [comment]
See #3894, I welcome a review from you and your colleague.
