### ISSUE TITLE
Sidekiq-pro throttling

### ISSUE THREAD

**Issue by Blokh** [mperham/sidekiq#3890]
Hey Mike, we use sidekiq-pro for the past year and with it we use sidekiq-throttled for the ability to pause and resume queues. Recently, this functionality has stopped working for us. 

While I know this is not related to Sidekiq-Pro, is there the same functionality available for us to use through sidekiq/sidekiq-pro so can eliminate our use of throttled? 

Thanks in advance,
Daniel.

**Comment by mperham** [comment]
Like this? https://github.com/mperham/sidekiq/wiki/Pro-API#pausing-queues

**Comment by Blokh** [comment]
![image](https://user-images.githubusercontent.com/35891501/42822534-f6d4c12a-89e3-11e8-94e6-ebd032fbc0ef.png)


I've just tried that, apparently there is some issue with the pausing functionality.
Do you have any idea where it might come from?

**Comment by mperham** [comment]
Please provide versions and initializer if you want me to diagnose anything.  https://github.com/mperham/sidekiq/blob/master/.github/issue_template.md

**Comment by Blokh** [comment]
Sidekiq / Pro / Enterprise version(s):
 sidekiq-pro (4.0.2)
 sidekiq (5.1.3)

initializer: 
require 'sidekiq-cron'
require 'sidekiq-unique-jobs'
require 'sidekiq/pro/expiry'

Sidekiq.configure_server do |config|
  config.redis = *REDIS_CONFIGS
end


Sidekiq.configure_server do |config|
  config.redis =  *REDIS_CONFIGS
config.on(:startup) do
    puts "Starting SideKiq"
  end
  config.on(:quiet) do
    puts "Got USR1, stopping further job processing..."
  end
  config.on(:shutdown) do
    puts "Got TERM, shutting down process..."
  end
end

Sidekiq.default_worker_options = { 'backtrace' => false }

Sidekiq::Cron::Job.load_from_hash YAML.load(ERB.new(File.read(schedule_file)).result)

that's pretty much it.

**Comment by mperham** [comment]
I think the solution is to remove throttled completely.

https://github.com/sensortower/sidekiq-throttled/blob/master/lib/sidekiq/throttled/patches/queue.rb#L7
