### ISSUE TITLE
Methods not entering job queue on specific rails model

### ISSUE THREAD

**Issue by Cernewein** [mperham/sidekiq#3891]
Ruby version: 2.3.0
Sidekiq 4.2.10

Hello everyone,

I have multiple models on rails and use Sidekiq on some of them, and everything works well. You'll ask yourself why am I writing if everything works fine ? Well sidekiq **works on every model except one**.. And I can't figure out what I'm doing wrong.

As for every model, I import Sidekiq delay with the line
         `include Sidekiq::Delay`

I want to put some job into the queue like this
        ```
 self.delay.my_method
or
         delay.my_method
       ```

This works fine all the time, except on one specific model, and this happens with all methods of my model. It simply does not add a job to the queue. So I try to lauch this in command line and get the following error:

 ```
NoMethodError: undefined method `client_push' for nil:NilClass
        from /usr/local/rvm/gems/ruby-2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/extensions/generic_proxy.rb:20:in `method_missing'
        from /app/app/models/event.rb:161:in `handle_asynchronicity_and_stack_workload'
        from /app/app/models/event.rb:236:in `delay_if_no_return'
        from (irb):83
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

So it seems like the model is not able to load the sidekiq method, but I don't know why... Any clues ? Has this already happened to someone ?

Thank you !

**Comment by mperham** [comment]
`include Sidekiq::Delay` is not a thing.  Where did you get the idea to do this?

You'd be best served to stick with the patterns recommended by Sidekiq, with Sidekiq::Worker classes that perform your jobs; don't use class methods.

**Comment by Cernewein** [comment]
I joined a team using Sidekiq like this, I don't really know where they got this from. I must admit I have just tried to replicate their usage, not looking at the recommended patterns. My bad, I will look that up and address that issue with the team. Thank you for your quick response and sorry for such a question..
