### ISSUE TITLE
How do I cleanup my Redis DB?

### ISSUE THREAD

**Issue by jruijgers** [mperham/sidekiq#3895]
Ruby version: 2.3.7
Sidekiq / Pro version(s): 4.2.9 / 3.4.3

Our Redis DB has grown over the years and at the moment we have almost 500K Sidekiq related entries in here. We want to clean these up, considering we only have about 2K 'active' messages (including lots of dead ones).

* We have seen lots of `sidekiq:status:[JID]` keys. How can we find the related message?
* There are a lot of entries related to running workers. How can I determine if these can be deleted?

Any other steps that can be taken to clean the DB up?

**Comment by mperham** [comment]
Look at the changelog, circa 4.1.2. There’s a script to run to clean up leaked data.

Those status messages are likely related to the sidekiq-status gem? No comment there, since that’s not Sidekiqs data.

**Comment by jruijgers** [comment]
I will check that script out and give it a run.

Interesting! We do indeed use the `sidekiq-status` gem. I'll be going to track those down separately.

```
    sidekiq (4.2.9)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-pro (3.4.3)
      sidekiq (>= 4.1.5)
    sidekiq-retry_exceptions (0.1.0)
    sidekiq-status (0.5.4)
      sidekiq (>= 2.7)
    sidekiq-throttler (0.5.1)
      activesupport
      sidekiq (>= 2.5, < 5.0)
```

**Comment by jruijgers** [comment]
I used your script to set an expiry on my `sidekiq-status` things.

Thanks for the help!
