### ISSUE TITLE
replacing redis

### ISSUE THREAD

**Issue by mathieujobin** [mperham/sidekiq#3897]
Ruby version: 2.3.7 mostly
Sidekiq 5.1.3 / Pro 4.0.x

Hello,

we use Sidekiq-pro for quite some time, but we have sporadic issues with Redis. and we wanted to know if you support another backend for sidekiq queues?

note we also use the sidekiq-unique-job gem which rely on lua/redis

have you considered incorporating those features in the main sidekiq?

thanks

**Comment by mperham** [comment]
Sidekiq Enterprise has had unique job support for several years now.  Check out the list of commercial features here:

https://github.com/mperham/sidekiq/wiki#sidekiq-pro

Sidekiq will never use anything but Redis. https://github.com/mperham/sidekiq/wiki/FAQ#wouldnt-it-be-awesome-if-sidekiq-supported-mongodb-postgresql-mysql-sqs--for-persistence

**Comment by mathieujobin** [comment]
thanks for your answer
