### ISSUE TITLE
Setting the logfile incompatible with sidekiqswarm?

### ISSUE THREAD

**Issue by kreynolds** [mperham/sidekiq#3902]
Possible ignorance on my part, but I'm not sure how to set the log file appropriately using sidekiqswarm. One cannot use the -L option and setting the logfile in sidekiq.yml causes the following IOError. If I remove all of the logging options and it just logs to stdout, it seems to work fine. What am I missing here?

Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 1.7.1

Please include your initializer and any error message with the full backtrace.

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

	12: from /opt/rubies/ruby-2.5.1/bin/sidekiqswarm:23:in `<top (required)>'
	11: from /opt/rubies/ruby-2.5.1/bin/sidekiqswarm:23:in `load'
	10: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/bin/sidekiqswarm:51:in `<top (required)>'
	 9: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:44:in `start_and_monitor'
	 8: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:85:in `monitor'
	 7: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:176:in `spawn'
	 6: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:180:in `forkit'
	 5: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:180:in `fork'
	 4: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:181:in `block in forkit'
	 3: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:187:in `rescue in block in forkit'
	 2: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:39:in `log'
	 1: from /opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:39:in `puts'
/opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/sidekiq-ent-1.7.1/lib/sidekiq-ent/swarm.rb:39:in `write': closed stream (IOError)

**Comment by mperham** [comment]
Modern services should not daemonize and should [log to stdout only](http://0pointer.de/public/systemd-man/daemon.html).  systemd will log the output according to how you configure it.

**Comment by kreynolds** [comment]
Ok. Trying to get sidekiqswarm running on elastic beanstalk which uses upstart and I'm not winning yet, but I'll keep trying and see if I can make it work the modern way.

**Comment by kreynolds** [comment]
Its not, but I suspect thats something local to EB. The swarm itself is running now so I guess thats crisis averted, thanks.
