### ISSUE TITLE
sidekiq-pro not starting any processes and no jobs are consumed

### ISSUE THREAD

**Issue by eranamiel86** [mperham/sidekiq#3903]
Ruby version: 2.2.3, rails 4.2.9
Sidekiq / Pro version(s): sidekiq 5.1.3 with sidekiq-pro 4.03

i'm running sidekiq 5.1.3 with no problem and all working well.
when i installed sidekiq pro, i run **sidekiq** command, as always, in my terminal, its start running and all seems ok.
i also can see in the web ui the it running with pro version.

the problem is that i don't see any busy workers and no jobs are being consumed.
i also try to run with verbose mode but there is no indication for any problem.
i'm using mac os x high sierra 10.13.6.

this is my sidekiq.yml
# Sidekiq process #1 - high-flow, regular events
---
:verbose: true
:concurrency: 1
:queues:
  - [events, 10]
  - [events_memsql, 9]
  - [reindex_users, 8]
  - [facebook_split_spends, 5]
  - [halo, 5]
  - [alexa, 5]
  - [default, 5]
  - [visitor_attribution, 5]
  - [link_visitors_to_users, 5]
  - [visitors_tracking, 3]
  - [alerts, 3]
  - [google_calendar, 4]
  - [reports, 2]
  - [active_campaign, 1]
  - [active_campaign_low ,1]
  - [active_campaign_medium ,3]
  - [active_campaign_high ,10]
  - [match_upgrades, 8]
  - [touch_points, 8]
  - [zombies, 5]
  - [platform_sync, 10]
  - [platform_sync_low, 1]
  - [ab_test, 10]
  - [memsql_sync, 10]

![image](https://user-images.githubusercontent.com/15541291/43358786-f58bb7d2-929f-11e8-91ad-adbfce5dd370.png)

![image](https://user-images.githubusercontent.com/15541291/43358793-0c264778-92a0-11e8-9116-7f2ab3b5d6dd.png)

**Comment by mperham** [comment]
What is the Redis url for the Sidekiq process and in the footer of the web UI?  I’d guess they are different. Post your initializer.

**Comment by eranamiel86** [comment]
i'm running redis locally
$redis = Redis.new({
  :host => $creds.get('REDIS/HOST'),
  :port => $creds.get('REDIS/PORT'),
  :password => $creds.get('REDIS/PASSWORD')
})


redis_conn = proc {
  $redis
}

Sidekiq.configure_client do |config|
	config.redis = ConnectionPool.new(size: 10, &redis_conn)
end

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 30, &redis_conn)
end

**Comment by eranamiel86** [comment]
and also why there no running procees ?
![image](https://user-images.githubusercontent.com/15541291/43358874-6a26524a-92a1-11e8-8c54-a48c3e75f789.png)

**Comment by mperham** [comment]
That's what we're trying to figure out.

I believe you are misconfiguring Sidekiq.  Let it handle the connection pooling for you:

```ruby
redis = {
  :host => $creds.get('REDIS/HOST'),
  :port => $creds.get('REDIS/PORT'),
  :password => $creds.get('REDIS/PASSWORD')
}

Sidekiq.configure_client do |config|
  config.redis = redis
end

Sidekiq.configure_server do |config|
  config.redis = redis
end
```

**Comment by eranamiel86** [comment]
ok. now it's working, can u explain what is the reason ?
what is the difference between what i did and your way ?

**Comment by mperham** [comment]
You were giving Sidekiq one Redis socket to share across N threads.
Sidekiq needs many sockets to work quickly.

I don’t know why you configured the connection pool that way but if you
copied it from someone/somewhere, please let them know their code is
terribly broken.
