### ISSUE TITLE
Queue prioritization and nested batches

### ISSUE THREAD

**Issue by iamtheschmitzer** [mperham/sidekiq#3910]
Ruby version: 2.3.4
Sidekiq / Pro / Enterprise version(s):
4.2.10/Pro 3.4.5

My configuration looks like this:

```yaml
:queues:
  - calculation_priority
  - user_report
  - quality_reporting
  - calculation
  - segment_calculation
  - patient_import
  - [default, 1]
  - [mailer, 1]
```

I am creating a batch of jobs (about 100) in `segment_calculation`, which when they run create jobs (about 50) in `calculation` in a nested batch.  When that batch completes, some cleanup is done in a callback.

I expect one `segment_calculation` job to run, create its child batch, and then all `calculation` jobs to run and finish that child batch.  That is, I expect `calculation` to have higher priority than `segment_calculation`, and usually to see about 50 or less `calculation` jobs.  However I see both `calculation` and `segment_calculation` jobs mixed in, to where I have roughly 5000 calculation jobs enqueued. 

Are batches or nested batches having an impact on priority?

We also use `calculation_priority`, and any job there jumps ahead of `calculation` jobs, but the `calculation_priority` job is not in any batch (created by a callback of a batch, though).  

Thanks

**Comment by mperham** [comment]
Make the last two queues consistent and it should start working better. Those weights of one are forcing it to pick from a random Queue.

**Comment by iamtheschmitzer** [comment]
That it did, thanks
