### ISSUE TITLE
Duplicate Queue in Config Switches from Strict to Random Weighted Fetch

### ISSUE THREAD

**Issue by chadrschroeder** [mperham/sidekiq#3911]
Sidekiq / Pro / Enterprise version(s): sidekiq-5.1.3, sidekiq-pro-4.0.3

I noticed that if mistakenly duplicate a queue name in my config, `SuperFetch` will switch from strict ordering to random weighted because the `@queues.length == @queues.uniq.length` check fails.  Would it be possible to raise an `ArgumentError` for this misconfiguration instead?

**Comment by mperham** [comment]
Happy to get a PR in cli.rb for this, interested?
