### ISSUE TITLE
CSP Missing for Admin Pages

### ISSUE THREAD

**Issue by thegorgon** [mperham/sidekiq#3912]
Ruby version: 2.5.1p57
Sidekiq / Pro / Enterprise version(s): 5.1.3

Please include your initializer and any error message with the full backtrace.

No errors with Sidekiq, but given that the Sidekiq admin does not define it's own Content-Security-Policy, if a parent application is using a CSP, e.g. in Rails 5.2, the parent policy will be used for the admin pages. This may cause problems with the admin pages, depending on the application policy.

I've forked the repository with a commit to add a CSP that seems conservative for security's sake, but that i believe works with all pages. Unfortunately, defining a report-uri seems impractical, but, the pages are simple enough that this policy should be fine.

Fork: https://github.com/thegorgon/sidekiq

Given the sensitive nature of the content on the admin pages, a CSP does seem prudent and this seemed to me like the best way to achieve it. Open to other suggestions.   

One concern I'm now realizing, submitting this issue - if the asses for the admin page are hosted outside the main app (e.g. on S3) this CSP will be problematic. Is that a common usecase? If so, there are a few ways to update the policy to account for that case.

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Create a PR?

**Comment by thegorgon** [comment]
I tried to - but I get a permission error:

```
ERROR: Permission to mperham/sidekiq.git denied to thegorgon.
```

**Comment by mperham** [comment]
Go to your fork's root on github.com.  The GitHub UI **should** have a banner asking if you want to create a PR.

**Comment by thegorgon** [comment]
I see - sorry, clearly I'm new to this.
