### ISSUE TITLE
sidekiq process at 100% CPU

### ISSUE THREAD

**Issue by tisba** [mperham/sidekiq#3918]
**Ruby version** 2.5.1

**Sidekiq version** 5.1.3

**Initializer**
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch("SIDEKIQ_REDIS_URL") }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch("SIDEKIQ_REDIS_URL") }
end
```

**sidekiq.yml**
```yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 15
:timeout: 400
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]
```

**Are you using an old version?** No

**Have you checked the changelogs to see if your issue has been fixed in a later version?** There is no newer released version, not sure about the changes for the unreleased version.

## Issue Description

After some time (~30-90min), and unfortunately only in production, we see sidekiq at 100%. Jobs still seem to be processed though. `strace`ing the PID results in only one line scrolling through at a high rate (not sure if this is relevant to this issue though):

```
futex(0x561ecc68c488, FUTEX_WAKE_PRIVATE, 1) = 0
```

I already tried to lower concurrency from 25 to now 15, but the issue is still present. There is not much pressure on the system, and most of the time sidekiq is idle (`0 of 15 busy`).

So far I could not spot any issues from logs, redis (using 4.0.9) also seems to be okay (only used for sidekiq, no load, no errors being logged).

**Comment by tisba** [comment]
Just found https://github.com/mperham/sidekiq/issues/2249. The effect is different as jobs are still being processed. We are not using `therubyracer`, but `mini_racer` and not as part of sidekiq jobs.

Also memory usage is rather low <300MB in case that might be relevant.

**Comment by mperham** [comment]
Maybe TTIN will help? https://github.com/mperham/sidekiq/wiki/Signals#ttin

**Comment by tisba** [comment]
I already took a look, but I'm not sure if I can spot something that relates to this issue: https://gist.github.com/tisba/6c31cf34bf94a1d0128f362667a3f1c6

There are several `mon_synchronize` in the backtrace but they all are related to redis gem (v4.0.1).

One guess would be:
```
2018-08-09T15:58:17.107Z 32153 TID-go6gmh1k5 WARN: /srv/www/forge/shared/bundle/ruby/2.5.0/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:136:in `sleep'
/srv/www/forge/shared/bundle/ruby/2.5.0/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:136:in `block in run_eviction_loop'
/srv/www/forge/shared/bundle/ruby/2.5.0/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:132:in `loop'
/srv/www/forge/shared/bundle/ruby/2.5.0/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:132:in `run_eviction_loop'
/srv/www/forge/shared/bundle/ruby/2.5.0/gems/sshkit-1.17.0/lib/sshkit/backends/connection_pool.rb:49:in `block in initialize'
```

But I'm not sure how to debug this further currently. Any help or hints would be very much appreciated!

**Comment by mperham** [comment]
That all looks normal.  You'll need to provide more data.  First thing I would do is ensure all of your native gems are up to date.  See the command here:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-crashing-what-do-i-do

**Comment by tisba** [comment]
Thanks for your help, @mperham 💕 

I'm 99% sure that the problem is caused by https://github.com/capistrano/sshkit/issues/438. After I applied a workaround I could no longer reproduce the problem. I'm working on further confirmation and a possible patch for sshkit.
