### ISSUE TITLE
Problems with configure_server & client

### ISSUE THREAD

**Issue by NorseGaud** [mperham/sidekiq#3919]
Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Sidekiq / Pro / Enterprise version(s):
sidekiq (5.1.3)
sidekiq-pro (3.7.0)

I'm trying to get cwebtools-po-1s.sys.XXX.net, where the apache/passenger/rails is running, queue up jobs (from a user on the GUI) to cwebdb-po-1s.sys.XXX.net's redis, but process them on cwebtools and NOT cwebdb. I just want the redis database on cwebdb used so that cwebtools-po-1s and cwebtools-po-2s are seeing the same batch

Within my config/initializers/sidekiq.rb:

```
# Using multiple Redis DB: https://stackoverflow.com/questions/14742020/configuring-redis-sidekiq-in-production
require 'sidekiq/pro/web'
Sidekiq::Web.set :sessions, false

# Need to use the same Redis so job ids don't throw a Sidekiq::Batch::NoSuchBatch
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.development?
  config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.production?
end
Sidekiq.configure_client do |config|
    config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.development?
    config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.production?
end
```
* Both cwebtools and cwebdb have this config.

This seems to use redis on cwebdb, but nothing processes on either cwebtools or cwebdb. It sits in Enqueued.

Is this something wrong with the configure_client/server or am I misunderstanding how this works? Is Redis limited to the host sidekiq is running on?

**Comment by mperham** [comment]
The client config is where the jobs will be pushed to.  The server config is where jobs will be pulled from.  Right now you are telling it to push jobs to 127.0.0.1.

**Comment by NorseGaud** [comment]
Thanks for the follow up Mike.

I noticed that I copied the wrong config. I'm using:
```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.development?
  config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.production?
end
Sidekiq.configure_client do |config|
    config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.development?
    config.redis = { url: 'redis://cwebdb-po-1s.sys.XXX.net:6379/12' } if Rails.env.production?
end
```

**Comment by mperham** [comment]
🤷‍♂️  I'm not sure what the problem is.  Your deployment is too complex for me to follow.

**Comment by NorseGaud** [comment]
I have one server with rails and sidekiq installed: Server A
I want another server (Server B), with rails and sidekiq also, to store the redis jobs I queue up on Server A.
However, I still want Server A to process the jobs locally, and not on Server B where redis is stored.

Is this possible?

**Comment by mperham** [comment]
```
A client -> B redis
A server -> A redis
B client -> B redis
B server -> B redis
```

Sounds like you want to have everyone except the A client to use the localhost default.  Remove all your Redis configuration in the initializer.  In the A rails process production environment, set REDIS_URL = 'redis://cwebdb-po-1s.sys.XXX.net:6379/12'.  I think that's what you want.

**Comment by mperham** [comment]
Oh, and remove that "/12" garbage.  I'm almost 100% you cargo culted that and don't need it.

**Comment by NorseGaud** [comment]
Weird. My comment disappeared. All good, thanks again.

**Comment by NorseGaud** [comment]
Hey @mperham, quick second question. Wanted to include it here if someone stumbles on this later.

Can I set the redis database to use per-worker instead of for sidekiq as a whole?
Setting ENV['REDIS_URL'] inside of the worker doesn't seem to do anything.

**Comment by mperham** [comment]
Worker is not a precise term, avoid it.

Redis is set per-process.  You cannot set it per thread as all threads draw from the same redis connection pool.

`REDIS_URL=redis://localhost:6379/2 bundle exec sidekiq` for example.
