### ISSUE TITLE
Sidekiq::Shutdown exception error message exploding logs files

### ISSUE THREAD

**Issue by suryateja619** [mperham/sidekiq#3920]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 4.2

Please include your initializer and any error message with the full backtrace.

`Error performing WorkJob (Job ID: 7ce4a99a-7bec-490e-91f2-f3086558ea07) from Sidekiq(default) in 212433.16ms: Sidekiq::Shutdown (Sidekiq::Shutdown):`

I have been seeing this error message on my log files. There aren't any jobs currently running or enqued. We keep on seeing this error messages every 5 minutes. Tried resetting the Redis server and clearing all the queues. 
 
Any thoughts?

**Comment by mperham** [comment]
No clue.

**Comment by bobber205** [comment]
Can you try moving to a different redis instance just for Sidekiq? Do you have anything else running heavy traffic on the redis instance?
