### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by greysteil** [mperham/sidekiq#3921]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.0

Please include your initializer and any error message with the full backtrace.

```
ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper.sidekiq_options(
  retry: false,
)
```

Upgraded to 5.2.0 yesterday evening (great looking release). Saw this a few hours later. Have only seen it once, so may be a red herring 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/1144873/43950263-b7a1b6aa-9c87-11e8-95d2-5af15355708b.png)
![image](https://user-images.githubusercontent.com/1144873/43950332-edee07fe-9c87-11e8-8c17-57f716af6fc0.png)

Had a quick look at the code and couldn't see how Ruby would be looping through `WORKER_STATE` in that stack trace, but figured I'd create an issue you might. Will report again if I get any more of these.

**Comment by greysteil** [comment]
FYI, just seen this again. I'm going to downgrade to 5.1.3 for now, but let me know if I can help debug at all.

**Comment by mperham** [comment]
Yep, I’ll need to fix that tomorrow. It iterates in the launcher.rb heartbeat code.

**Comment by greysteil** [comment]
Thanks for the quick fix!

**Comment by jimgrimmett** [comment]
Heya. Long time user of free sidekiq here. 

Recently upgraded from 5.0.5 to 5.1.3 and saw the "can't add a new key into hash during iteration" error. Reading your comment above, I moved up to sidekiq 5.2.7.

We're on ruby 2.5.1 and rails 5.1.5

I'm still seeing this in my logs

`.454959+00:00 app worker.1 - - /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/set.rb:349:in `add': can't add a new key into hash during iteration (RuntimeError)
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/manager.rb:95:in `block in processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/manager.rb:91:in `synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/manager.rb:91:in `processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:77:in `rescue in run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:68:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'Exception`

I'm running sidekiq in Heroku with 
`worker: bundle exec sidekiq`

our sidekiq.rb is pretty empty
`require 'sidekiq'`

`Sidekiq.configure_client do |config|`
`  config.redis = { :size => 10 }`
`end`

`# Sidekiq.configure_server do |config|`
`#   # The config.redis is calculated by the`
`#   # concurrency value so you do not need to`
`#   # specify this. For this demo I do`
`#   # show it to understand the numbers`
`#   config.redis = { :size => 10 }`
`# end`

redis gets its data from ENV and I'm using the sidekiq.yml to specify a number of queues (with sidekiq-limit-fetch and sidekiq-scheduler to help out).

We were running around 350k jobs a day, but I've been optimising the jobs and are up to over 1M jobs a day now. I'm stuill seeing lots of jobs running, but the busy queue reported in the UI goes down and down. It seems like the jobs are still being processed at a rate of knots... but I can't see them running - does that sound right or insane?

Restarting the heroku worker brings everything back.

I looked into concurrent ruby. We're still have version 1.1.5 required by active-support 5.1.5 and sprockets 3.7.1

Anyway, anything you can add would be most welcome.

J.
