### ISSUE TITLE
rate of enqueue limitation? only a fraction of jobs getting enqueued

### ISSUE THREAD

**Issue by epipheus** [mperham/sidekiq#3922]
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s): 5.1.3

Is there any known issue with sidekiq concerning an enqueuing rate limit?  I am stumped on why I'm only seeing a fraction of my jobs actually enqueue. I'm curious if there is any known limitation to the rate or volume of jobs that can be enqueued? This is all on a local dev machine.  Before I package up all relevant information, etc.,  I'm presently provisioning a super cleaner environment with minimum gems to isolate sidekiq. Also bumping up to Ruby 2.5.1 just in case. I've also reduced data being passed to sidekiq to simple a record id.   Only 1/4 - 1/3 of the jobs are getting enqueued, the rest never hit Redis.

**Comment by mperham** [comment]
Remove all your config, benchmark pushing a very simple job. Add back more and more config until it slows.

Post your initializer and worker code if you want me to verify it.

**Comment by epipheus** [comment]
I must have put my machine into some crazy state with my stress test.  Only a reboot fixed it. Closing this. 

Mike, just wanted to say that I appreciate your responsiveness and the high quality of Sidekiq.
