### ISSUE TITLE
How to properly test ```config.periodic```?

### ISSUE THREAD

**Issue by danielnc** [mperham/sidekiq#3924]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 

We have some custom code to load period jobs from a yml file(similar to what you can do with dynamic periodic jobs from the database).

```
  if File.exist?(schedule_file)
    config.periodic do |mgr|
      YAML.load_file(schedule_file).each do |job_config|
        args = job_config["args"] || []
        mgr.register(job_config["cron"], job_config["class"].constantize, args: args)
      end
    end
  end
```

I am wondering what is the best way to test that our config is correct and we expect all periodic jobs to be created with correct arguments.

Is there a way we can access periodic configs? Similar to what you can do with ```Sidekiq.options```

**Comment by mperham** [comment]
There is no user-accessible registry.  You can extract that logic into a method and pass in a periodic mock to verify the contents of your YAML file.
