### ISSUE TITLE
Feature Request | Kill single stucked worker

### ISSUE THREAD

**Issue by erprincebansal** [mperham/sidekiq#3925]
I am facing an issue that due to some reason worker stuck and running for last 12 hours. It is consuming a lot of memory. There is no option to kill running single worker using thread_id using some ruby code.

Ruby version: ruby 2.3.1p112
Sidekiq / Pro / Enterprise version(s): sidekiq - 4.1.4

**Comment by mperham** [comment]
It is impossible to safely kill a thread, so Sidekiq does not offer that feature.
