### ISSUE TITLE
Sidekiq.options has not been set from initializer when RedisConnection is created

### ISSUE THREAD

**Issue by fonglh** [mperham/sidekiq#3926]
Ruby version: 2.4.4
Sidekiq / Pro / Enterprise version(s): 5.2.1

Please include your initializer and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
    config.redis = { url: "redis://#{ENV["REDIS_HOST"]}:6379/0", password: ENV["REDIS_PASS"] }
    Sidekiq.options[:concurrency] = ENV["MAX_SIDEKIQ_THREADS"].to_i
end

Sidekiq.configure_client do |config|
    config.redis = { url: "redis://#{ENV["REDIS_HOST"]}:6379/0", password: ENV["REDIS_PASS"] }
end
```

Are you using an old version? No

I have the initializer as shown above to configure the number of Sidekiq threads. After #3892, a worker I configured with 20 threads was unable to start up. The error message was `Your pool of 15 Redis connections is too small, please increase the size to at least 22`. It looks like that when the size of the Redis connection pool is set at https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L18, the `configure_server` block has not been read yet.

Would it be possible for the `RedisConnection` object to also use the concurrency option in the initializer?

**Comment by mperham** [comment]
The standard Rails env variable to control concurrency is `RAILS_MAX_THREADS`.  See 4.2.0 changes: https://github.com/mperham/sidekiq/blob/master/Changes.md#420

Use that and remove your options line and it'll work.

**Comment by fonglh** [comment]
Thanks that works!
