### ISSUE TITLE
Can we prepare worker with a pre-work to earn time ?

### ISSUE THREAD

**Issue by Argorate** [mperham/sidekiq#3929]
I have an app with lot of jobs enque, it works fine but it's verry longer (many second to execute the script), so I would to know if it's possible to prepare the worker with task always done at start of each job, in my exemple : I create a headless Chrome browser for each job, like : `browser  = Watir::Browser.new`

It was pretty cool if when a worker ending execute a job, it can prepare it self for the next job with a specific code, for exemple : 

def perform_prepare
  @browser  = Watir::Browser.new
end

like that, we earn time when dequeue and execute job because workers have already done a static part of a task.

I don't know if im clear, but what about this?

**Comment by mperham** [comment]
Or use a connection pool of browser instances, shared by the jobs.

**Comment by Argorate** [comment]
How do you implement persistent pool of Browser accessible by workers? im sry I dont know how do that ...

**Comment by mperham** [comment]
See the connection pool section on the Advanced Options wiki page.

**Comment by Argorate** [comment]
ok I see, and what about 2 workers Class for 2 tasks different but shared the same "pool" ?

It works if I call MyWorker1::MEMCACHED_POOL in MyWorker2 class ? otherwise how create shared pool for multiple workers ?

thx for your precious help ! ;)

**Comment by mperham** [comment]
Put it in a global constant, in an initializer.
