### ISSUE TITLE
Stack level too deep when using Sidekiq::Testing.disable!

### ISSUE THREAD

**Issue by Tolsto** [mperham/sidekiq#3930]
Ruby version: 2.5.1p57
Sidekiq / Pro / Enterprise version(s): 5.2.1 with Sidekiq-pro 4.0.3

The change introduced in https://github.com/mperham/sidekiq/pull/3852 doesn't seem to work with Sidekiq Pro. Calling `Sidekiq::Testing.disable! {}` now results in a `stack level too deep`. The `super` in `testing.rb` calls Sidekiq Pro's `raw_push_with_backup` which calls then `push_initial` which in turn calls `raw_push_without_backup` which is an alias for `raw_push` and we are back in `testing.rb`'s `raw_push`.

**Comment by Tolsto** [comment]
I'm not really familiar with Minitest but I was able to reproduce the problem using your test file by adding `require sidekiq-pro`. We use Rails with RSpec and sidekiq-pro gets autoloaded in our test environment.

**Comment by mperham** [comment]
If I use this testcase and run it with `ruby -Ilib test/test_test.rb`, it works exactly as expected.  I can't fix this without a reproduction because of its complexity -- unfortunately this code is brittle.

```ruby
require 'sidekiq-pro'
require 'minitest/autorun'
require 'sidekiq/testing'

class TestTest < Minitest::Test
  class AWorker
    include Sidekiq::Worker
    def perform
      puts "hello"
    end
  end

  def test_test
    Sidekiq::Client.reliable_push!

    Sidekiq::Testing.fake!

    assert_equal 0, AWorker.jobs.size
    AWorker.perform_async
    assert_equal 1, AWorker.jobs.size

    Sidekiq::Testing.inline! do
      AWorker.perform_async
    end
    assert_equal 1, AWorker.jobs.size

    Sidekiq::Testing.disable! do
      AWorker.perform_async
    end
    assert_equal 1, AWorker.jobs.size

  ensure
    Sidekiq::Testing.disable!
  end
end
```

**Comment by Tolsto** [comment]
It should fail if you put `require sidekiq-pro` after `require sidekiq/testing`.

```
require 'sidekiq/testing'
require 'minitest/autorun'
require 'sidekiq-pro'
```

If you still cannot reproduce it now then I'll try to come up with a Vagrantfile.

**Comment by mperham** [comment]
Nope.

```
require 'sidekiq/testing'
require 'minitest/autorun'
require 'sidekiq-pro'
```

```
$ ruby -Ilib test/test_test.rb 
Run options: --seed 31183

# Running:

hello
.

Finished in 0.002530s, 395.2569 runs/s, 1581.0276 assertions/s.
```

**Comment by mperham** [comment]
I verified I'm running against Sidekiq 5.2.1.

**Comment by mperham** [comment]
Nevermind, I needed to run `bundle exec ruby test/test_test.rb` to ensure I was running against Sidekiq 5.2.1!  It breaks now, thanks.

**Comment by mperham** [comment]
Fixed, will be in 4.0.4 out next week.

**Comment by Tolsto** [comment]
@mperham Do you have an updated release date for `4.0.4`?

**Comment by mperham** [comment]
Yes, apologies, I got busy with other things and dropped this.  I will release it now.
