### ISSUE TITLE
Sidekiq idle, jobs never arrive to it, but it looks they are being processed

### ISSUE THREAD

**Issue by albertogilf** [mperham/sidekiq#3932]
Ruby version: 9.1.16.0 (2.3.3)
Sidekiq / Pro / Enterprise version(s): 5.1.1

Please include your initializer and any error message with the full backtrace: 
initializer/sidekiq.rb
```
if Rails.env.development?
	Sidekiq.configure_server do |config|
	  config.redis = {url: 'redis://127.0.0.1:6379/1', network_timeout: 5, id: "Sidekiq-server-PID-72254"}
	end

	Sidekiq.configure_client do |config|
	  config.redis = {url: 'redis://127.0.0.1:6379/1', network_timeout: 5, id: "Sidekiq-server-PID-72254"}
	end
elsif Rails.env.production?
	Sidekiq.configure_server do |config|
	  config.redis = {url: 'redis://127.0.0.1:6379/1', network_timeout: 5}
	end
	Sidekiq.configure_client do |config|
	  config.redis = {url: 'redis://127.0.0.1:6379/1', network_timeout: 5}
	end
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

I am trying to deploy an application not written by me and the jobs are never processed by sidekiq, so there is no any error log, when I look into the history or in the web interface sidekiq is idle and there is no job in any queue, although I have sent some of them and I see in the ruby log that the jobs are being processed (they never finish, I do not know what it is really happening).

**Comment by mperham** [comment]
I'm not sure I understand what's really going on.  You'll need to supply more info about your production environment, verbose log output, etc.
