### ISSUE TITLE
Has a "Kill All" button for retries ever been considered?

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#3933]
Using the latest Sidekiq FWIW.

I'll often have 100+ retries that basically are reminders to get back to fixing a bug. Making them go into the dead queue with the single page kill button is pretty laborious.

Has a button next to retry all and delete all for killing all the jobs been considered? 🙏

**Comment by mperham** [comment]
Happy to get a PR for this, should be easy to replicate the existing Retry All functionality.
