### ISSUE TITLE
How to find pending jid in batch?

### ISSUE THREAD

**Issue by hzchirs** [mperham/sidekiq#3935]
Ruby version: 2.3.7
Sidekiq Pro: 3.5.0
Sidekiq Enterprise: 1.5.4

<img width="1219" alt="2018-08-22 11 03 58" src="https://user-images.githubusercontent.com/4735528/44472355-8b5d0300-a660-11e8-9d72-306e69243c2e.png">

There's a pending job in batch and never complete, how to find the pending job by the pending jid?

**Comment by mperham** [comment]
1. Upgrade.  `bundle up sidekiq-ent`.  You're missing a lot of fixes, including a batch fix in 3.7.0.
2. Usually missing jobs are due to job loss somehow and restarting Sidekiq occasionally will find them and run them.
