### ISSUE TITLE
Feature Requeusts: sidekiq_queue, job_args, requeue

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#3937]
Feature requests (mostly related):

Wouldn't it be cool if workers knew what queue they were on? It would be trivial to add accessors for `sidekiq_queue` to the Worker module and set the queue while dispatching the worker in Processor. I currently have middleware add this but the method doesn't exist when I call `MyWorker.new.perform` so I have to protect it with `respond_to?(:sidekiq_queue) && sidekiq_queue`. The motivation is I can manually queue a job to a queue that is different than the one defined in `sidekiq_options` (I do this for certain high priority jobs that are identical otherwise) and I may want to requeue the job, or a subsequent job that it creates, to that other queue.

Wouldn't it be neat if workers knew what their job arguments were? I often need to requeue a job because of a known intermittent failure such as an HTTP connection error. I rather catch these errors and requeue than have sidekiq go through its exception processing and have another timeout error land in our exception tracker. Similarly to `sidekiq_queue`, it would be trivial to add this. I currently manage this with a mixin to the Sidekiq::Worker module that adds a `set_job_args` method to save the job args to an instance variable for ease of use later. I call this with all of the job arguments as the first line of the perform method so that the two arg lists are right next to each other. This at least helps prevent changing the method signature of the `perform` method and forgetting to change the arguments sent to any requeueing later because the two lines mirror each other, but it is not foolproof.

Wouldn't it be AMAZING if workers could requeue themselves?! This is my ultimate goal. Having a `requeue` method and a `requeue_in` method simplify a lot of the things I do. I mentioned a couple, I'm sure it's not hard to imagine a few more. If a worker knew what queue it was on and what its job arguments were, it would be trivial for it to requeue itself. I believe this is a job best handled by Sidekiq instead of middleware or manual handling. After all, it already has all of the details needed to requeue the job while maintaining all the extra details about the job that aren't exposed to the worker (batch id, various sidekiq timestamps, potential retry count, extra data added in middleware, etc.) which would be lost with a manual requeue.

I'm sure there's a solution here that doesn't clobber a worker's namespace with a million Sidekiq methods, but we already have a couple so they shouldn't be a huge issue as long as they are documented.

Thoughts?

**Comment by mperham** [comment]
Could you raise a custom exception in a worker which tells the middleware to requeue the job?  Maybe something like this would work?

```ruby
def call(worker, job, q)
  begin
    yield
  rescue Requeue => ex
    Sidekiq::Client.push(job)
  end
end
```

**Comment by jakemack** [comment]
Let me think through that for a bit. On first glance, it seems it would solve most of my current issues, though not quite all. But I could probably live with that.

Is there a reason you're unsure about adding it? If it's the work, I'd gladly submit a pull request. If it's ethical, I won't do any of my testing on animals. :-P

I see general value in these three methods, but maybe more generally, I see value in being able to get the data about the job inside the job. With that I could requeue (even without a requeue method), I could retry without throwing an exception, I could dump jobs that were one hour older than their enqueued_at timestamp because they are no longer relevant. I can already do some things like this, but only if the job has not started processing. And maybe my suggested methods are wrong, perhaps there is a better API to do this but it just feels like it gives me more control over my workers.

At the end of the day, I should be able to add all of these methods via middleware and just deal with the inefficiencies. I was just hoping you thought some worker introspection would be a useful feature as well.

**Comment by mperham** [comment]
The idea is that Worker#perform's concern should be executing its business logic, not interweaving queueing and retry logic within.  Mixing concerns like that makes testing 10x harder and much more complex code.  Workers are expected to conform to Sidekiq's error handling and retry conventions.  If you don't, you need to really question why and is it worth the additional complexity?

**Comment by mperham** [comment]
Sounds like you want a periodic job to check the FTP site every N minutes.  Use a redis flag to short circuit once the file has been processed for the day.

```ruby
# run this job every 5 minutes during working hours, don't retry
mgr.periodic("*/5 8-17 * * *", FtpChecker, retry: 0)
```

```ruby
def perform
  return if Sidekiq.redis { |conn| conn.get(Date.today.to_s) }
  # grab file
  Sidekiq.redis { |conn| conn.set(Date.today.to_s, "done", ex: 24.hours) }
end
```

**Comment by jakemack** [comment]
If the file is large and takes an hour to download, I will have up to six of these jobs running at once which is definitely not what I want. I also run my workers on Heroku and automatically scale up different dynos to process jobs based on the queue they are on. I don't want to scale up and down 40+ extra dynos every day, incurring extra costs as we go. As a minor nitpick, I don't want to have this extra, now pointless job being processed ahead of other jobs that need to be done. Lastly, in the case of a rare issue preventing the file from being uploaded that day, I want my worker to keep trying until I see fit to mark it as complete, be that days, weeks, or months.

**Comment by jakemack** [comment]
We could probably go back and forth a bit suggesting issues and solutions to this specific problem, but there's a elegant simplicity to the following:

```ruby
def perform(ftp_address, filename, save_dir)
  if file = download(ftp_address, filename)
    save(save_dir, file)
  else
    self.class.perform_in 10.minutes, ftp_address, filename, save_dir
    # or
    requeue_in 10.minutes
  end
end
```

**Comment by mperham** [comment]
For now, `self.class.perform_in` is the recommendation.
