### ISSUE TITLE
Heroku, Sendgrid, ActiveJob, Sidekiq -> fails on port 443 error

### ISSUE THREAD

**Issue by resistorsoftware** [mperham/sidekiq#3941]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): Sidekiq

**Failed to open TCP connection to :443 (Connection refused - connect(2) for nil port 443)**

If I run my mailer from the heroku console, the mail is sent no trouble. It is only inside the Sidekiq job that an attempt to send email fails. Any idea why a call to send email would fail inside a Sidekiq job?

**Comment by resistorsoftware** [comment]
Ok... so... given that, is there some trickery to ensure a call to a Mailer inside a job, has access to the parent environment? I guess that is the solution, but I am not seeing that in any docs, anywhere.

**Comment by resistorsoftware** [comment]
At the Heroku command line, instantiating the mailer works perfect. So it is only inside Sidekiq job, running in the worker, where this is an issue. Anyone! Please! What am I missing here. How to have the Action Mailer work inside a worker?

**Comment by ruckus** [comment]
Can you post some code?

* Worker class
* Any rails configuration files (obfuscate any credentials)

**Comment by resistorsoftware** [comment]
config for production:

config.action_mailer.perform_deliveries = true
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_url_options = { host: 'https://xxxx.herokuapp.com' }
  config.action_mailer.smtp_settings = {
    address: 'smtp.sendgrid.net',
    port: '587',
    authentication: :plain,
    user_name: ENV['SENDGRID_USERNAME'],
    password: ENV['SENDGRID_PASSWORD'],
    domain: 'xxxx.herokuapp.com',
    enable_starttls_auto: true
  }

  config.action_mailer.perform_caching = false

**Comment by ruckus** [comment]
If you're using SMTP then **what** is trying to connect on blank host port 443 (your original error message)?

**Comment by ruckus** [comment]
Ultimately this is not a Sidekiq issue though

**Comment by resistorsoftware** [comment]
I cannot tell from the logs... the class code is:

# This class represents the job of transferring inventory
class InventoryTransferJob < ApplicationJob
  queue_as :default

  def perform(data)
    begin
      # do stuff
      MerchantMailer.update_completed('elmer@fudd.com', results).deliver_now
    rescue StandardError => e
      puts "Bad things happen here like #{e.message}"
    end

  end
end

**Comment by resistorsoftware** [comment]
The routine bombs at the call to MerchantMailer and yes, I am also not able to pin down this call to a port 443 from the logs...

**Comment by resistorsoftware** [comment]
I like your confidence @ruckus ... but I wish there was some info on where else to look for a whoopseedo...

**Comment by ruckus** [comment]
well with that bogus email `elmer@fudd.com` its unclear if that maybe

`config.action_mailer.raise_delivery_errors = true` 

is causing an exception and you might have some other mis-configured exception notification library that *itself* is mis-configured and unable to establish the TCP 443 connection?

**Comment by resistorsoftware** [comment]
I obfuscated a real email there... the point is... I am not seeing anything that could be wanting to call port 443... and I started with delivery_errors false...

**Comment by ruckus** [comment]
Is

> Failed to open TCP connection to :443 (Connection refused - connect(2) for nil port 443)

being printed from your own rescue block? If so, dump the backtrace to the logs

`puts e.backtrace.join("\n")`

**Comment by resistorsoftware** [comment]
["/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'", "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1213:in `get'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:131:in `block in request'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:128:in `request'", "/app/vendor/bundle/ruby/2.5.0/gems/shopify_api-4.12.0/lib/shopify_api/connection.rb:15:in `request'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on429.rb:9:in `block in request'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on429.rb:18:in `block in with_retrial_on_429'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on429.rb:16:in `times'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on429.rb:16:in `with_retrial_on_429'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on429.rb:8:in `request'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on5xx.rb:9:in `block in request'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on5xx.rb:22:in `block in with_retrial_on_5xx'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on5xx.rb:20:in `loop'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on5xx.rb:20:in `with_retrial_on_5xx'", "/app/vendor/bundle/ruby/2.5.0/bundler/gems/shopify_api_mixins-d529d77d63a9/lib/shopify_api_mixins/retry_on5xx.rb:8:in `request'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:92:in `block in get'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:227:in `with_auth'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/connection.rb:92:in `get'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:1043:in `find_one'", "/app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.0.0/lib/active_resource/base.rb:937:in `find'", "/app/vendor/bundle/ruby/2.5.0/gems/shopify_api-4.12.0/lib/shopify_api/resources/shop.rb:6:in `current'", "/app/app/jobs/inventory_transfer_job.rb:75:in `perform'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/execution.rb:39:in `block in perform_now'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/i18n-1.1.0/lib/i18n.rb:284:in `with_locale'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/logging.rb:46:in `tag_logger'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/execution.rb:35:in `perform_now'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/execution.rb:24:in `block in execute'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:83:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/execution.rb:22:in `execute'", "/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185:in `execute_job'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:166:in `block in process'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:98:in `local'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:42:in `block in call'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:72:in `wrap'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:41:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217:in `stats'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73:in `global'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125:in `block in dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48:in `with_context'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42:in `with_job_hash_context'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124:in `dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165:in `process'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83:
2018-08-30T22:09:50.378521+00:00 app[worker.1]: in `process_one'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71:in `run'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16:in `watchdog'", "/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'"]

**Comment by ruckus** [comment]
Looks like it starts right around here:

```
/app/vendor/bundle/ruby/2.5.0/gems/shopify_api-4.12.0/lib/shopify_api/connection.rb:15:in request'
```

Whats the shopify request doing?

I dont know jack about Shopify but from what I can tell it has nothing to do with a mailer error (nor Sidekiq) and its related to that shopify integration and that logic trying to make some outbound request.

**Comment by resistorsoftware** [comment]
True... I am looking into that.. I see from the logs that all the code to
do with Shopify seemingly ends correctly... leaving nothing but the call to
the mailer...

In other words, before I added the call the mailer, the job just ended
nice... hence my suspicion around the mailer line of code... but yes, I too
see Net::http being the problem in the backtrace... just not sure why ...
it is even a thing..

Will dig further... thanks...




514.795.9601
Book an Appointment!
https://calendly.com/dlazar

**Comment by resistorsoftware** [comment]
Solved. Not sure why, but asking to do an API call in the block was not working... thanks for your troubles! Saved my bacon!

**Comment by mperham** [comment]
David, a couple of tips:

1. Don't rescue exceptions, let Sidekiq catch them and log them so you get a full backtrace.
2. Don't use deliver_now in a job, use deliver_later. Jobs should only do one thing or else they quickly become non-idempotent.  If your email send fails, it will retry the inventory transfer over again, possibly causing havok with your inventory counts.

**Comment by resistorsoftware** [comment]
Thanks Mike! Will adjust and make that a habit! You guys rock!
