### ISSUE TITLE
Sidekiq Limiter and retry: false

### ISSUE THREAD

**Issue by goncalopereira** [mperham/sidekiq#3943]
Hello, 
We've been using the Limiter option to throttle the use of a third party API.

The workers using this Limiter are a mix that might use or not use retry (depending on READ/WRITE for example)

It seems that the ones set as retry: false are still being rescheduled and that caused consistency issues.

Is this an expected behaviour?

**Comment by mperham** [comment]
Yes, limiter retries are considered different from error retries.  You can move the within_limit to the start of your job or redesign your job to be idempotent.  There is no option to disable limit retries today.
