### ISSUE TITLE
Feature Request: Automatic hiredis driver detection

### ISSUE THREAD

**Issue by tbuehlmann** [mperham/sidekiq#3944]
I just got on a greenfield Rails application and did my regular sidekiq setup. As I'm _always_ getting the hiredis configuration wrong, I just thought about making that part easier.

First, why am I using the hiredis driver? I read about it being great performance-wise, tried it, looked good. I couldn't see any downsides, so that's about it.

So, what am I doing wrong all the time? Well, requiring the gem (and file) correctly in the Gemfile is the first part. Right now the Gemfile part looks like this:

```ruby
gem 'hiredis'
gem 'redis', require: ['redis', 'redis/connection/hiredis']
gem 'sidekiq'
```

Can't do much about this in sidekiq's code, I guess. I couldn't find a wiki page for it, so maybe adding a simple hiredis portion would help here.

After requiring the gems correctly, new redis connections will automatically use the hiredis driver:

```ruby
Redis::Connection.drivers # => [Redis::Connection::Ruby, Redis::Connection::Hiredis]
Redis.new.instance_variable_get(:@client).options[:driver] # => Redis::Connection::Hiredis
```

Sidekiq, however, will not use this driver, we will have to set that part up manually like this:

```ruby
# config/initializers/sidekiq.rb

Sidekiq.configure_client do |config|
  config.redis = {driver: 'hiredis'}
end

Sidekiq.configure_server do |config|
  config.redis = {driver: 'hiredis'}
end
```

Why's this? Well, it seems we're hard setting the `Redis::Connection::Ruby` driver [here](https://github.com/mperham/sidekiq/blob/v5.2.1/lib/sidekiq/redis_connection.rb#L81):

```ruby
opts[:driver] ||= 'ruby'
```

I couldn't find any reasoning about this decision (a harder dependency on redis implementations?, MRI/JRuby compatibility?, sentinel stuff?, general dislike for hiredis?, love for the ruby driver?, it is how it is, …), so maybe @mperham could shed some light on this.

The actual suggestion: What about we change that part and use the hiredis driver if it's available? We could still override the driver by having the same `driver` configuration, but defaulting to what redis does.

Redis does the [following](https://github.com/redis/redis-rb/blob/v4.0.1/lib/redis/client.rb#L448):

```ruby
options[:driver] = _parse_driver(options[:driver]) || Connection.drivers.last
```

If there's any interest in implementing this, I'd be more than happy to help.

**Comment by mperham** [comment]
I feel like this would be better as a small PR rather than a big issue. Show me what you propose.

**Comment by tbuehlmann** [comment]
Great, I agree, I'll come up with a PR. Just wanted to follow [protocol](https://github.com/mperham/sidekiq/blob/v5.2.1/.github/contributing.md#code).
