### ISSUE TITLE
retrieve the scheduled date of a sidekiq worker within it

### ISSUE THREAD

**Issue by ngouy** [mperham/sidekiq#3945]
Let's have a lot of jobs queued for a certain Date `my_date`.

There is so much job for this exact same date that some of them are working only 20 minutes after their scheduled_date.

How can I retrieve this original scheduled date once I am in my perform method, even if I am in a retry (within my currently running job) ? 

ps : I can't pass this scheduled_date as params, because its a Cron job (and I can only pass static params)

stackoverflow : https://stackoverflow.com/questions/52163449/retrieve-the-scheduled-date-of-a-sidekiq-worker-within-it

**Comment by mperham** [comment]
How are you creating the Cron jobs? Show your config.

**Comment by ngouy** [comment]
I am using the following : 
```
name = "MyCronName"
cron = "* * * * *"
klass="MyWorker"
 Sidekiq::Cron::Job.create(
          name: name,
          cron: cron,
          class: klass
        )
```
(but my queue can be full of many other waiting job, not crons ones)

**Comment by mperham** [comment]
Looks like you are asking us to support a 3rd party extension.  Please ask your questions in their issue tracker.

**Comment by ngouy** [comment]
well. I am not asking to support any extention. 

The cron extention just create a regular sidekiq worker

But out of the box, my point is the following : Is there a way (without passing it as a param) to retrieve the original scheduled_date ? regardless of the retries number, or the queue delaying ?
