### ISSUE TITLE
5 second delay between SIGTERM & Sidekiq shutdown message

### ISSUE THREAD

**Issue by swrobel** [mperham/sidekiq#3946]
Ruby version: 2.5.1p57
Sidekiq / Pro / Enterprise version(s): 5.2.1

Procfile: `worker: bin/sidekiq -c ${SIDEKIQ_WORKERS-10}`

initializer:
```ruby
if defined?(Sidekiq)
  Sidekiq.configure_server do |config|
    config.redis = { driver: 'hiredis' } if defined?(Hiredis)

    config.death_handlers << ->(job, _ex) { Notifier.notify!("#{job['wrapped']} died with #{job['error_message']} #{Rails.application.routes.default_url_options[:host]}/admin/sidekiq/morgue", channel: '#dev-stream') }
  end

  Sidekiq.configure_client do |config|
    config.redis = { size: Integer(ENV.fetch('PUMA_THREADS', 5)) }
  end
end
```

sidekiq.yml:
```yml
:max_retries: 12
:timeout: 25
:queues:
  - critical
  - default
  - low
```

logs:
```
Sep 04 16:41:04 heroku/worker.1:  Stopping all processes with SIGTERM 
Sep 04 16:41:04 app/worker.1:  agentmon: Got signal terminated. Shutting down. 
Sep 04 16:41:09 app/worker.1:  4 TID-gqm8r8b7o INFO: Shutting down 
Sep 04 16:41:34 heroku/worker.1:  Error R12 (Exit timeout) -> At least one process failed to exit within 30 seconds of SIGTERM 
Sep 04 16:41:34 heroku/worker.1:  Stopping remaining processes with SIGKILL
```

Typically the "INFO: Shutting down" message seems to occur immediately after SIGTERM, like the agentmon log, but it seems in this case there was a 5 second delay, which, added with the 25 second exit timeout, led to Heroku killing my worker after 30 seconds rather than Sidekiq shutting down gracefully. It's worth noting that there was a particularly expensive job running at the time (it takes about 10 minutes to finish) and it was not put back in the queue.

I've since changed `timeout` to 20, but since the 5 second delay seems arbitrary, I'm not sure if this is a long-term solution, plus this just doesn't seem right...

**Comment by mperham** [comment]
Use the TTIN signal to get backtraces during that 5 second pause.

**Comment by mperham** [comment]
In a Heroku production IRB:

```
require 'sidekiq/api'
Sidekiq::ProcessSet.new.each(&:dump_threads)
```

**Comment by mperham** [comment]
Unfortunately that is async so it might not happen within the 5 seconds but try it a few times and it might fire within that 5 sec shutdown window.
