### ISSUE TITLE
Sidekiq-ent loops disappear from web UI

### ISSUE THREAD

**Issue by hanahiroAze** [mperham/sidekiq#3948]
Ruby version: 2.4.3
Sidekiq / Pro / Enterprise version(s): 5.0.4 / 3.7.1 / 1.6.1
redis-rails version: 3.3.5

---

logs
```
lv:info 2018-09-06T06:35:39.876Z 12990 TID-gmowx9zdg INFO: Lost leadership of Sidekiq cluster
lv:info 2018-09-06T06:36:39.877Z 12990 TID-gmowx9zdg INFO: Gained leadership of the cluster
lv:info 2018-09-06T06:37:24.878Z 12990 TID-gmowx9zdg INFO: Lost leadership of Sidekiq cluster
lv:info 2018-09-06T06:38:24.879Z 12990 TID-gmowx9zdg INFO: Gained leadership of the cluster
```

sidekiq.yml
```
Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV.fetch("SIDEKIQ_REDIS_URI") { "redis://localhost:6379/0" },
  }

  config.periodic do |mgr|
    mgr.register('0 23 * * *', MyWorker)
    mgr.register('*/5 * * * *', TestWorker)
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV.fetch("SIDEKIQ_REDIS_URI") { "redis://localhost:6379/0" },
  }
end
```

After above log, sidekiq loops's web UI says 'NoLoopsFound'.
However cron(`TestWorker`) still work.
I wonder why this happens and is related to #3002.

Do you have any idea to fix this?

**Comment by mperham** [comment]
Thank you, your report uncovered a bug in #3950.

It sounds like there is something very wrong with your Redis, perhaps it is being flushed somehow but it is not normal to repeatedly lose cluster leadership like that.  I can't tell any more than that from your report.

**Comment by hanahiroAze** [comment]
@mperham 
Thanks for your reply. It may happened by Redis's eviction.

**Comment by mperham** [comment]
I’ve never heard of that happening like this. It doesn’t evict everything.

**Comment by hanahiroAze** [comment]
@mperham Sorry it was caused by my env var configuration.
As I divided worker's server and web UI server, web's server didn't see the worker's Redis.
