### ISSUE TITLE
Jobs in queue, idle workers won't process them

### ISSUE THREAD

**Issue by geoffw8** [mperham/sidekiq#395]
Hi

I have a weird issue, I've got 2 servers, one is working almost blissfully processing images, and the other for some heavier lifting. The second server has processed jobs previously, but after some heavy deploying and process killing it is now refusing to run jobs. Its like I've killed something too many times, something "odd" feels like its happening.

I am in a position where I have 100 workers sitting idle:

deploy   19692  1.4  0.3 468216 120292 pts/2   Sl   12:51   0:10 sidekiq 2.3.0 [0 of 100 busy]

and 2 jobs, just image fetching jobs in a urgent queue, but the workers won't process them. I'm at a bit of a loss, I've kind of exhausted all my known options. I've upgraded sidekiq (was on 1.2.1, now 2.3.0), restarted redis, redeployed (to see if this caused it to boot back up).

The code to get the images is very simple (and working successfully on the other server).

Please can you tell me what additional information you might need, and/or whats likely to be the problem? Things I should look at etc etc. 

Thanks, its very much appreciated.

Cheers,

Geoff

**Comment by tambakoo** [comment]
@mperham how do I monitor sidekiq if I have 2 process workers that address multiple different type of queues ?
