### ISSUE TITLE
Error fetching job: Connection timed out using Compose.io deployments

### ISSUE THREAD

**Issue by zdraganov** [mperham/sidekiq#3953]
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.1

Regular error "Error fetching job: Connection timed out", using Compose.io [Compose.io](https://app.compose.io) (twice per minute).
I tried with `:tcp_keepalive = 300` on the Redis client configuration, tcp_keepalive and timeout options on the Compose deployment settings and the error started to be rare. 20-30 minutes after new deployment there is no error, and then it starts to fail regularly.

When running latency-history using redis-cli here is the output:
```
root@etracker-worker-554599887f-skn9s:~/application# redis-cli -h gcp-us-east1-cpu.6.dblayer.com -p 18995 -a <PASSWORD> --latency-history
min: 0, max: 8, avg: 0.82 (1323 samples) -- 15.01 seconds range
min: 0, max: 12, avg: 0.80 (1321 samples) -- 15.01 seconds range
min: 0, max: 8, avg: 0.73 (1313 samples) -- 15.01 seconds range
min: 0, max: 8, avg: 0.69 (1348 samples) -- 15.00 seconds range
```

No such error seen when using self-hosted Redis deployment.

**Comment by mperham** [comment]
Perhaps this would be a better ticket for the compose.io team, sounds specific to that environment.
