### ISSUE TITLE
Sidekiq rails generator creates tests with MiniTest::Unit::TestCase instead of Minitest::Test

### ISSUE THREAD

**Issue by kmcd** [mperham/sidekiq#3954]
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Sidekiq / Pro / Enterprise version(s): Pro

Sidekiq rails generator creates tests with `MiniTest::Unit::TestCase` resulting in the following error:

```
MiniTest::Unit::TestCase is now Minitest::Test. From X:2:in `<main>'
rake aborted!
```

**Comment by mperham** [comment]
Maybe you are on an old version?  The current code checks:

https://github.com/mperham/sidekiq/blob/master/lib/generators/sidekiq/templates/worker_test.rb.erb#L3
