### ISSUE TITLE
undefined method `clear_all' for Sidekiq::Worker:Module

### ISSUE THREAD

**Issue by wonderer007** [mperham/sidekiq#3955]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 4.2.10

`spec/spec_helper.rb`

```
   RSpec.configure do |config|
     config.before(:each) do
       Sidekiq::Worker.clear_all
     end
   end
```

Error
```
     Failure/Error: Sidekiq::Worker.clear_all
     
     NoMethodError:
       undefined method `clear_all' for Sidekiq::Worker:Module
```

**Comment by mperham** [comment]
What's bug?  You're on an old version that didn't have that function.  Upgrade to 5.

**Comment by helphop** [comment]
I'm using Sidekiq version 5.2.3 and getting the same error.

**Comment by helphop** [comment]
Thank you for getting back to quickly on this issue. I had some problem with Spring and when I stopped all servers and started them again it seems to have cleared up this issue. Now it is working.
