### ISSUE TITLE
Jobs lingering in busy despite having completed (on jruby)

### ISSUE THREAD

**Issue by mattbooks** [mperham/sidekiq#3958]
Ruby version: jruby 9.1.16.0
Sidekiq / Pro / Enterprise version(s): 5.2.1 / pro 3.4.5

Please include your initializer and any error message with the full backtrace.
- It's hard for me to get that, and there are no exceptions.

Are you using an old version? no
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes. A different concurrency issue with `WORKER_STATE` was fixed recently, however: #3921

**TL;DR: I believe this is a thread safety issue with `WORKER_STATE` on jruby**

Here's why I think that: 

I can see jobs linger in the busy tab in the web UI. I believe they are finished executing because I can see the logs from them completing.

I checked if the data powering the admin page was stale, but it appears as though the heartbeat in `sidekiq/launcher` is refreshing it, as I can see the expiry being refreshed for `hget("<proc>:workers")`.

Since that reads from the global `WORKER_STATE` variable, which is annotated with 

```
# This is mutable global state but because each thread is storing
# its own unique key/value, there's no thread-safety issue AFAIK.
```

I suspected this might be a thread safety issue. I also know that MRI apps at my company are not reporting this issue, so perhaps it is an issue with the jruby implementation, which is not threadsafe AFAIK (I think you need to use `Concurrent::Hash`)

To test this theory, I wrote this script:

```
require 'concurrent/hash'

GLOBAL_HASH = Concurrent::Hash.new
# GLOBAL_HASH = {}

do_modifications = Proc.new do |name|
  Thread.new do
    loop do
      begin
        k = "#{name}:#{rand.to_s}"
        GLOBAL_HASH[k] = name
        GLOBAL_HASH.delete(k)
      rescue => e
        puts "caught error in #{name}"
        puts e
        raise
      end
    end
  end
end

do_modifications.call('foo')
do_modifications.call('bar')

puts "Running!"
1000000.times do
  # puts GLOBAL_HASH
  bad_hash = GLOBAL_HASH.dup
  raise "Too many keys: #{bad_hash}" if bad_hash.size > 2
end
```

(run with `while true; do; jruby test.rb; done` since it doesn't fail every time)

with `{}` it raises, with `Concurrent::Hash`, it does not. I have not seen this fail on MRI either.

Indeed, testing this in our staging environment using `Concurrent::Hash` for `WORKER_STATE` seems to resolve the issue.

**Comment by mattbooks** [comment]
I'm not sure how (if at all) you'd like to test something like this, but if you have an approach you'd like to see I can add that.

**Comment by mperham** [comment]
Usually I extract the racy stuff to a method, and pound it 1000 times with a few threads.  Takes a few ms and will blow up non-deterministically but almost assuredly if there's a problem.

**Comment by mattbooks** [comment]
Do you have an idea of when this fix might be released?

**Comment by mperham** [comment]
I'll release 5.2.2 on monday.
