### ISSUE TITLE
Sidekiq silently ignores ActiveRecord::RecordNotFound, and doesnt retry

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#3960]
Ruby version: 2.5.1 / Rails 5.2.1
Sidekiq: 5.2.1

This is what I am doing in the `perform` method - 

`raise ActiveRecord::RecordNotFound.new('data not found')`

**Comment by mperham** [comment]
Sidekiq does not specifically handle any Rails/AR exceptions.  If something is going wrong, it's somewhere in your app or error handler config.
