### ISSUE TITLE
delay_for and tests

### ISSUE THREAD

**Issue by hachpai** [mperham/sidekiq#3962]
I've a specific time-sensitive case: on creation of a model, I call delay_for to planify a job 24 hours later. On each call, i check that the model is not older than 5 days, and planify a new job. After 5 days there's no more scheduled job. Issue is: the jobs are executed inline and the time doesn't evolve, resulting in endless job calls.

My original class method:
```ruby
class Ticket < ActiveRecord::Base
 def self.planify_ticket_notification(ticket_id)
    ticket=Ticket.find(ticket_id)
    binding.pry if ticket.title == "j'ai un pblm"
    ticket.notify #email notification and ticket closing
    if(!ticket.closed?) #keep on checking any unclosed ticket, planify next check
      Ticket.delay_for(24.hours).planify_ticket_notification(ticket_id)
    end
  end
end
```
Monkey-patched in test_helper.rb to use time travel helper:
```ruby  
Ticket.class_eval do
    extend ActiveSupport::Testing::TimeHelpers
    @@original_planify_ticket_notification=::Ticket.method(:planify_ticket_notification)
    def self.planify_ticket_notification(ticket_id)
      travel 1.day
      @@original_planify_ticket_notification.call(ticket_id)
    end
 end
```
Maybe that should be integrated into sidekiq to reproduce real-world conditions.
```ruby  

# File 'lib/sidekiq/extensions/active_record.rb', line 35
 extend ActiveSupport::Testing::TimeHelpers
def sidekiq_delay_for(interval, options={})
  travel interval if Rails.env.test?
  Proxy.new(DelayedModel, self, options.merge('at' => Time.now.to_f + interval.to_f))
end
```

**Comment by mperham** [comment]
This is  too specific of a need to go into core.  I think you are overtesting here -- I would just test that the method schedules a job.
