### ISSUE TITLE
Invalidate batch

### ISSUE THREAD

**Issue by samatha-kankipati** [mperham/sidekiq#3963]
I am trying to invalidate a batch using https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch
But it is not working.
valid_within_batch? in worker is giving true always.

We are using sidekiq-pro 3.5.0 version.

**Comment by mperham** [comment]
I need to see  worker code, the code which invalidates and your initializer.

**Comment by samatha-kankipati** [comment]
application.rb

` put '/stop/:batch_id' do
      batch = Sidekiq::Batch.new(params[:batch_id])
      batch.invalidate_all
      status 204
   end`

in worker.rb

` def perform(limit = nil, offset = nil, params = {})
      print valid_within_batch?
      return unless valid_within_batch?
      --------------------
  end`

**Comment by mperham** [comment]
That's pretty simple and should work.  Can you give me a testcase or app which reproduces the problem that I can run locally to debug?

**Comment by samatha-kankipati** [comment]
Our application is so huge. so, I am working on providing an example.

Till now what i observed is, if call 

   batch = Sidekiq::Batch.new(params[:batch_id])
      batch.invalidate_all

inside worker perform method, it is working
print valid_within_batch? is coming false

Other than that, if i put it anywhere else, not working.
print valid_within_batch? is giving true

**Comment by mperham** [comment]
> if i put it anywhere else, not working.

What does this mean?  Give me an example.  `valid_within_batch?` is only meant to be called within perform.

**Comment by samatha-kankipati** [comment]
> > if i put it anywhere else, not working.
> 
> What does this mean? Give me an example. `valid_within_batch?` is only meant to be called within perform.

not valid_within_batch.

invalidate_all..
if i call invalidate_all in worker perform, i am getting valid_within_batch? as false for subsequent calls

but if i call invalidate_all outside worker, like i mentioned above application.rb, valid_within_batch? is always coming true

**Comment by mperham** [comment]
Is `params[:batch_id]` actually valid?

**Comment by samatha-kankipati** [comment]
yes, i am getting Batch object from that

> Is `params[:batch_id]` actually valid?

yes i am getting Batch object. Also, verified, what is coming in params[:batch_id]

**Comment by samatha-kankipati** [comment]
yes.. there is some discrepancy in batch id.. when we start the job looks like there are multiple batches starting. thanks for pointing out @mperham 

It is working now.. 
closing the issue
