### ISSUE TITLE
Feature Request : see queue priorities on the dashboard

### ISSUE THREAD

**Issue by deneuxa** [mperham/sidekiq#3964]
It would be very nice to have the possibility to order the queue on the dashboard, not only by alphabetical order, but as well by priorities. So you can easily check if your higher priorities queue are correctly being processed.

I think it should be the default order. And If I had to choose one, it would be this one.

The difficulty is to represent correctly same-priority queue but I'm sure it can be done :) 

Maybe only add small labels, next to the queue name, representing the priority and the weight of the queue ?

Sidekiq.xml :  

![image](https://user-images.githubusercontent.com/359847/45531248-e917e180-b7ff-11e8-8c23-830df116f413.png)

Dashboard : 

![image](https://user-images.githubusercontent.com/359847/45531246-e1f0d380-b7ff-11e8-898c-1d5dd9f499c7.png)

**Comment by mperham** [comment]
Different Sidekiq processes can have different queue priorities.  There's not one "right" way to view priority in many installs.  Alphabetically a queue's place within the list never changes.

If you are trying to monitor your system, you'd best be served by writing a script with the [Sidekiq API](https://github.com/mperham/sidekiq/wiki/API).
