### ISSUE TITLE
Sidekiq documentation has conflicting information

### ISSUE THREAD

**Issue by jcohenho** [mperham/sidekiq#3966]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

Hello there! I'm confused about the default concurrency number. I see in the source code, the default is 25: https://github.com/mperham/sidekiq/blob/52562b715174e447a0f7666136838521fda69214/lib/sidekiq/manager.rb#L33

However, in the advanced options wiki, it says its 10: https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency. Does the documentation just need to be updated?

**Comment by mperham** [comment]
You’re looking at the wrong file. Use -v to see options on startup. 
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L20

**Comment by jcohenho** [comment]
Oops my mistake! I've been used to the default of 25 for some time. I just saw the closed issue where the number was reduced: https://github.com/mperham/sidekiq/issues/3892. Thanks for clarifying!
