### ISSUE TITLE
How can i check when the sidekiq license expiration date?

### ISSUE THREAD

**Issue by soanni** [mperham/sidekiq#3967]
Hello! I'm a newbie in my company. I'm not a developer but rather a DevOps person, and i really need to know what version of Sidekiq we are running Pro or Entrerprise and when it expires to not break a system and prolongate the license in advance. I searched the wiki pages but can't find the answers where can i get this info

**Comment by mperham** [comment]
Bottom of the Web UI.  Sidekiq also prints it out when starting.  If you have a commercial version, you can email info @ contribsys.com with the company details and I'll look it up for you.  The email address on record is emailed one week before renewal so you can modify/cancel as necessary.

<img width="336" alt="screen shot 2018-09-16 at 7 51 28 am" src="https://user-images.githubusercontent.com/2911/45597743-70db2880-b985-11e8-9638-990845af78dd.png">
<img width="791" alt="screen shot 2018-09-16 at 7 50 48 am" src="https://user-images.githubusercontent.com/2911/45597744-733d8280-b985-11e8-8edd-1b853177f07b.png">
