### ISSUE TITLE
Validate REDIS_PROVIDER

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3969]
REDIS_PROVIDER is meant to hold the name of the env var that contains the Redis URL.  I see people misunderstand this abstraction and place the URL directly in REDIS_PROVIDER frequently.  Add validation that will fail fast if the user makes this mistake.  This is a breaking change and needs to be called out in the changelog loudly.

```
REDIS_PROVIDER should be set to the name of the variable which contains the Redis URL, not a URL itself.
Platforms like Heroku will sell addons that publish a *_URL variable.  You need to tell Sidekiq with REDIS_PROVIDER, e.g.:

REDIS_PROVIDER=REDISTOGO_URL
REDISTOGO_URL=redis://somehost.example.com:6379/4
```

**Comment by seuros** [comment]
Maybe we should namespace the variable too and deprecate REDIS_PROVIDER  ?SIDEKIQ_REDIS_PROVIDER ? wdyt ?
I can work on it in another PR .

**Comment by mperham** [comment]
Hmm, I like it. 👍

**Comment by Tensho** [comment]
Sorry, why Sidekiq provides indirect Redis server reference? What's wrong with direct`REDIS_URL` setting at Heroku?

**Comment by mperham** [comment]
How would you use a 3rd party Redis add-on, like Redis-to-Go?

**Comment by Tensho** [comment]
I have never deployed `sidekiq` to Heroku, does Redis-to-Go requires specific URL env var name?

**Comment by mperham** [comment]
All Redis providers require a custom *_URL variable. That’s how Heroku addons work.

**Comment by Tensho** [comment]
Yeah, I [see](https://devcenter.heroku.com/articles/redistogo#provisioning-the-add-on). I doubt people deploy multiple Redis add-ons and it's sensible for me to have a common env var name – `REDIS_URL`. Thanks for the clarification 🙇

**Comment by mperham** [comment]
Assume you are using Redis-To-Go.  Heroku will only allow RTG to modify the ENV var called REDISTOGO_URL in your app.  So if they want to migrate you seamlessly to another datacenter, your app uses their variable directly and they modify the value so that on reboot, your app picks up the new Redis instance.  REDIS_URL is not a thing they can control.  Sidekiq supports it for those people who want to run and manage their own Redis instance.

Since there are many Redis service providers, you use REDIS_PROVIDER to tell Sidekiq which ENV var is the live Redis and Sidekiq will use that variable to find Redis.

**Comment by Tensho** [comment]
Got it, thank you 🙇
