### ISSUE TITLE
Super Fetch job log info

### ISSUE THREAD

**Issue by cstuart1021** [mperham/sidekiq#3982]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): Pro 4.0.4

I'm working with sidekiq and Heroku. When a job uses more memory than Heroku allows us, an [R15](https://devcenter.heroku.com/articles/error-codes#r15-memory-quota-vastly-exceeded)  is created and Heroku will kill the dyno that's running the job. Super Fetch will then put the job back on the queue, but it's hard to figure out which job(s) caused the R15. It would be great if super fetch had a configuration that could allow logging the job name and its arguments when requeueing a job.

**Comment by mperham** [comment]
Sidekiq will execute a bunch of jobs concurrently so it’ll be hard to tell which one is at fault. Did you see my recent blog post about taming Rails bloat? Turn down the concurrency and it’ll help.

**Comment by cstuart1021** [comment]
Thank you for sharing your blog post! We have played with memory allocation and unfortunately found that it is not enough. Adding the job name and its arguments to logs, even with a bunch of jobs, will help us to identify a subset of jobs that are at fault. In addition, if there's a specific job in the subset that repeatedly is requeued, the additional log info will further help us to identify the job(s) at fault.

**Comment by mperham** [comment]
Side note: if you aren't used an APM already, Nate says Scout has the best tooling for tracking down bloat sources.

https://twitter.com/nateberkopec/status/1045064013413986304
https://scoutapp.com/

Today, super_fetch does log a warning for each job string it restores: `Sidekiq.logger.warn { "SuperFetch recovered job: #{job}" }`, which gives you the entire job payload, not just type/args.  Is that sufficient?  I realize it's not super human-readable but I think things like the JID are critical to have so you can track down "what happened to that one job?"
