### ISSUE TITLE
Rendering a Rails view from within a Sidekiq Worker

### ISSUE THREAD

**Issue by luisamacedo** [mperham/sidekiq#3983]
I have a Sidekiq worker that does some background processing and then finally POSTs a message. In the message I'd like to link back to my site in a properly formatted way. This naturally sounds like a view to me. I'd love to simply use a view template, render it to HTML and finally post it off to the site.

Until now I could not run the render a view from within my Sidekiq worker.

Ruby version: ruby 2.3.0

**Comment by mperham** [comment]
I think you are asking how do I render ERB templates in Sidekiq?  Like in any Ruby code:

```ruby
    require 'erb'
    foo = 1
    here = File.expand_path("..", __FILE__)
    content = ERB.new(File.read("#{here}/somefile.html.erb")).result(binding)
```

somefile.html.erb:

```
<%= foo %>
```

**Comment by luisamacedo** [comment]
Thaks, but it not work for me.

I'm doing heavy background processing using sidekiq to leave the main thread free. At the end of this processing, I'd like to render the result on the website (user's) main thread. I could not show this until now. Thank you, if you can help me.


    class ScanEmailBoxWorker    
        include Sidekiq::Worker
        sidekiq_options retry: false
          
        def perform()
        end
   end

I want to render partial in perform()

**Comment by mperham** [comment]
That's not how Sidekiq works.  Sidekiq performs **background** work.  You cannot pause the user, waiting for Sidekiq to perform some work, that's foreground work.  You can email the result to the user, which can render HTML email templates.

Rendering views outside of a controller is a Rails issue, I don't know how or even if it is possible to do it in Sidekiq.  Maybe the rendering guide will help? https://guides.rubyonrails.org/layouts_and_rendering.html
