### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - log/<custom file>.log

### ISSUE THREAD

**Issue by mareczek** [mperham/sidekiq#3985]
Hi, thanks for a great tool :)

in my worker I have:
```ruby
  def logger
    @logger ||= Logger.new("#{Rails.root}/log/send_lockers_map.log")
  end
```

and very randomly the worker fails due to:
```ruby
Errno::ENOENT: No such file or directory @ rb_sysopen - log/send_lockers_map.log
```

After a 3rd or 6th retry it doesn't have problems with opening the log file.

Is there a better way to do this? :)

Thanks in advance

**Comment by diesl** [comment]
@mareczek Almost 3 years later, I am facing exactly the same problem!

Most of the time, the log file can be opened, and in some rare cases, this error occurs. I can not really reproduce it, it occurs completely random.

Did you manage to find a solution or the root cause?
