### ISSUE TITLE
Redis Memory Spike

### ISSUE THREAD

**Issue by darrrelll** [mperham/sidekiq#3986]
I'm seeing a large Redis memory increase recently in our application. I'm wondering if it's related to NOT using ActiveRecord::Base.uncached {} block or due to the quantity of jobs scheduled or BOTH. We recently moved from processing about 15x jobs more a day, with most loading an active record object.

Ruby version:'2.3.4' on Rails 5.0.1

**Comment by darrrelll** [comment]
<img width="1212" alt="memory drop" src="https://user-images.githubusercontent.com/6189272/46235659-48154480-c330-11e8-8038-f305dd0a8e53.png">

**Comment by mperham** [comment]
ActiveRecord memory usage has nothing to do with Redis memory.  ActiveRecord is in your Ruby process.  It looks to me like you might need to increase your Redis instance size.  Are you using ElasticCache or another SaaS where they limit your instance memory?  Would you show the numbers at the top and bottom of the Web UI too?

**Comment by mperham** [comment]
And the output of `redis-cli info` against your Redis instance would be useful.

**Comment by darrrelll** [comment]
Good to know about AR I [thought this was related, but understand it's not now](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#activerecord-query-cache), I guess it's the job count then  
<img width="1202" alt="redis stats" src="https://user-images.githubusercontent.com/6189272/46236658-b3f9ac00-c334-11e8-9849-23f6cea3601b.png">

**Comment by darrrelll** [comment]
<img width="1210" alt="redis top bar" src="https://user-images.githubusercontent.com/6189272/46236748-15ba1600-c335-11e8-93af-851658ab15ba.png">

**Comment by mperham** [comment]
That's using **WAY** more memory than Sidekiq would for that job set.  Are you sharing that Redis with a cache?  Those job stats should equal 5-10MB of Redis memory.

**Comment by darrrelll** [comment]
Yes, it is :( . However, the number of items in the cache hasn't changed as much as the increase in job count, but these baseline numbers help me eliminate both AR cache and job count as root causes. I'll close the issue ...will reopen if the same pattern exists on a dedicated redis.
