### ISSUE TITLE
Enterprise: Unique until timeout

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#3987]
Hi there,

We still don't have the enterprise version of sidekiq but reading the documentation I'm seeing that I can not set a job to be unique until timeout (sidekiq-unique-jobs have this option).

What we need is that a job cannot be enqueued since the same job has been scheduled/processed until the timeout window has been completed.

Example: I can't schedule `MyJob('x')` before 30 minutes since the last `MyJob('x')` has been scheduled or processed.

Currently I'm doing that by hand but as you can imagine, we have to schedule the job and process to only then discover that it has already been processed in the last 30 minutes and can be ignored.

```ruby
class MyJob
  include Sidekiq::Worker

  def perform(url)
    return false unless acquire_lock(url)

    # ...
  rescue
    unlock_lock(url)

    raise $!
  end

  private

  TTL = 30.minutes
  private_constant :TTL

  def acquire_lock(url)
    Sidekiq.redis do |redis|
      redis.set(redis_key(url), Time.current, nx: true, ex: TTL)
    end
  end

  def release_lock(url)
    Sidekiq.redis do |redis|
      redis.del(redis_key(url))
    end
  end

  def redis_key(url)
    "#{self.class.name.underscore}:#{Digest::MD5.hexdigest(url)}"
  end
end
```

Make sense to have that?

**Comment by sobrinho** [comment]
Also, this is not battle tested, only a prototype.

It assumes a lot of things like having only one instance of redis, that you can wait for 30 minutes if the process dies unexpectedly and that the job lasts less than 30 minutes (no concurrency treatment).

**Comment by sobrinho** [comment]
Even better (sorry for flooding):

We currently have `unique_until: :start` and `unique_until: :success`, I was expecting to have `unique_until: :timeout`.

**Comment by mperham** [comment]
This is a pretty specialized usecase, no one else has ever asked for it nor have I ever needed it.  I generally only provide features that are requested by many customers.

**Comment by sobrinho** [comment]
I thought so 😭 

Thanks, I will close the issue if someone else asks about something similar we have a reference! 👍
