### ISSUE TITLE
New related project SidekiqAlive

### ISSUE THREAD

**Issue by arturictus** [mperham/sidekiq#3989]
Hi,
I released a gem for integrating Sidekiq with Kubernetes for checking pod liveness.
Can it be added to related projects?
Thanks

### Kubernetes
- [Sidekiq Alive](https://github.com/arturictus/sidekiq_alive) Liveness probe for Sidekiq in Kubernetes deployments

**Comment by mperham** [comment]
The wiki is publicly editable.  You don't need to ask permission.
