### ISSUE TITLE
DEVISE mailer. Doc not working

### ISSUE THREAD

**Issue by marcosanfilippo** [mperham/sidekiq#3990]
Ruby version: 2.4.4
Sidekiq / Pro / Enterprise version(s): Free

Problem:
**Doc is not correct.**

Hi, I'm trying to follow this doc:
https://github.com/mperham/sidekiq/wiki/Devise

But is not working as expected. It requires some params, but I can't figure out which.
The old `user.save!` is not working anymore. Maybe this doc is not up to date.

Thanks.

**Comment by mperham** [comment]
Thank you, that page is community-contributed.  I've never used Devise and since it has grown out of date, I think we should delete it.
