### ISSUE TITLE
Batches Polling: Access-Control-Allow-Origin herader

### ISSUE THREAD

**Issue by SmyzerT** [mperham/sidekiq#3993]
Ruby version: 2.4
Sidekiq / Pro / Enterprise version(s): Pro

BatchStatus middleware doesn't return 'Access-Control-Allow-Origin' header. Can you add this header with a value '*'? It's a cause of the CORS issue if a project uses the different front app.

Are you using an old version? We are using 3.7.1
Have you checked the changelogs to see if your issue has been fixed in a later version? It hasn't been fixed yet.

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Sidekiq will not assume a security policy.  You need to do this yourself, here's one example. https://github.com/cyu/rack-cors
