### ISSUE TITLE
ActiveJob set(wait_until: ...) does not appear to work

### ISSUE THREAD

**Issue by nozpheratu** [mperham/sidekiq#3995]
The `wait_until` syntax for ActiveJob does not appear to work with Sidekiq.

notify_job.rb
```
class NotifiyJob < ApplicationJob
  def perfom(message)
    puts message
  end
end
```

Invocation the job with the following, executes the job immediately:

```
NotifyJob.set(wait_unil: 10.years.from_now).perform_later('foo')
```

If I convert the job to a Sidekiq::Worker, and invoke it with perform_at, the jobs appears to be scheduled correctly.

>Ruby version:

Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.2, Rails 5.2.1.

>Please include your initializer and any error message with the full backtrace.

No initializer, default settings.

**Comment by nozpheratu** [comment]
Trying to debug this further, when I dropped a breakpoint on:

https://github.com/rails/rails/blob/dca5596f997b863a2de6a0fe1ed2c26a9f027359/activejob/lib/active_job/configured_job.rb#L14

It doesn't appear to ever get called. There must be some sort of black magic at work here.

**Comment by nozpheratu** [comment]
@mperham It's actually not present to begin with:

```
class ApplicationJob < ActiveJob::Base
end

```

**Comment by mperham** [comment]
I’m not sure what’s wrong then.

**Comment by mperham** [comment]
Reopen if you discover an issue I can fix.

**Comment by pftg** [comment]
Issue still presents, for rails 6.1.4 on development env

**Comment by mperham** [comment]
It seems to work for the standard Rails 6.1.4.1 app in /myapp. You'll need to provide repro code.

**Comment by pftg** [comment]
Will investigate and provide updates, I think some settings or other gems breaks this behaviour

**Comment by andretf** [comment]
It just came across me and I noticed OP code had a typo: `wait_unil`. Not sure the actual code had that too, but that typo should explain the unexpected behavior.
