### ISSUE TITLE
Programmatically accessing details of completed job

### ISSUE THREAD

**Issue by saitho** [mperham/sidekiq#3996]
Hi,

I have a frontend which creates jobs in Sidekiq to execute asychronously.
The jobs call other APIs which return error codes. Errors due to invalid input data are ignored and the job is marked as succeeded. Those jobs are marked as "failed" in my frontend and require user interaction like adjusting the input values.
For that functionality I'd like to get the previously used arguments from the completed job.
I know of ScheduledSet, RetrySet and DeadSet. I've been wondering if there is a way for me to access the arguments of completed jobs. Couldn't use JobSet.

Thanks.

**Comment by mperham** [comment]
Sidekiq can’t do this, you’d need to implement it yourself.
