### ISSUE TITLE
Systemd restart on failure always restart

### ISSUE THREAD

**Issue by Systho** [mperham/sidekiq#3998]
Ruby version: any
Sidekiq / Pro / Enterprise version(s): any

It looks like the provided systemd script is configured to restart sidekiq `on-failure` but it restart the process on clean exit, too.

When sending `TERM` to sidekiq , it exits with a status of `1` which is naturally considered by systemd to not be clean.

adding this line to the systemd script adds `1` as a clean status code and will allow you to manually stop/start 

`SuccessExitStatus=1`

**Comment by mperham** [comment]
Sidekiq should exit with 0. Odd.

**Comment by Systho** [comment]
I feel very stupid because now I can't reproduce it neither. 
I had some problem making this script work while allowing new deploy (a new deployment starts a new process and systemctl does not seem designed to handle that case :) )

Currently I have disabled any Restart behaviour which means I'm only using this script for the boot process.

I have probably messed something in my setup leading to this strange status code of 1.

I'm deeply sorry to have wasted your time on this. You can close this issue.

**Comment by mperham** [comment]
👍 No problem, thanks for following up.
