### ISSUE TITLE
Handling interrupts in workers

### ISSUE THREAD

**Issue by janko-m** [mperham/sidekiq#4006]
Ruby version: `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`
Sidekiq / Pro / Enterprise version(s): `Sidekiq 5.2.2`

We have a worker which needs to handle interrupts that can happen when sending `sidekiqctl stop` during deploys, and it needs to avoid an inconsistent state. To do that, the `#perform` method has a `rescue Interrupt` clause (which also catches `Sidekiq::Shutdown`):

```rb
class MyWorker
  include Sidekiq::Worker

  def peform
    # do work
  rescue Interrupt
    # clean up
  end
end
```

However, the issue is that, when Sidekiq sends `thread.raise Sidekiq::Shutdown` to all its processor threads, it doesn't wait for them to finish, and that's deliberate: https://github.com/mperham/sidekiq/blob/10342b61316ce73d426b063a2fe20112ebe0d751/lib/sidekiq/cli.rb#L116-L123

Why is that? Because of that behaviour, depending on how long does the cleanup code take to execute, it might or might not finish in time. This makes it impossible to reliably handle interrupts that happen during deploys.

To illustrate, here is a worker which does some work for 30 seconds, and cleans up for 1 second in case of an `Interrupt`:

```rb
# boot.rb
class MyWorker
  include Sidekiq::Worker

  def perform
    sleep 30
  rescue Interrupt
    sleep 1
    puts "CLEANUP DONE"
  end
end
```

If I schedule this worker:

```
$ ruby -r sidekiq -r ./boot -e 'MyWorker.perform_async'
```

Then run the `sidekiq` command:

```
$ sidekiq -r ./boot.rb -P sidekiq.pid
```

And then run `sidekiqctl stop`:

```
$ sidekiqctl stop sidekiq.pid 30
```

Then I will never see "CLEANUP DONE" in the `sidekiq` output:

```
2018-10-26T19:16:14.945Z 27177 TID-owpcetyx5 INFO: Running in ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
2018-10-26T19:16:14.945Z 27177 TID-owpcetyx5 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2018-10-26T19:16:14.945Z 27177 TID-owpcetyx5 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2018-10-26T19:16:14.945Z 27177 TID-owpcetyx5 INFO: Booting Sidekiq 5.2.2 with redis options {:id=>"Sidekiq-server-PID-27177", :url=>nil}
2018-10-26T19:16:14.947Z 27177 TID-owpcetyx5 INFO: Starting processing, hit Ctrl-C to stop
2018-10-26T19:16:19.337Z 27177 TID-owpcfigjl MyWorker JID-97323dc06b98b5692a59f802 INFO: start
2018-10-26T19:16:22.489Z 27177 TID-owpcetyx5 INFO: Shutting down
2018-10-26T19:16:22.489Z 27177 TID-owpcetyx5 INFO: Terminating quiet workers
2018-10-26T19:16:22.489Z 27177 TID-owpcfj2z9 INFO: Scheduler exiting...
2018-10-26T19:16:22.591Z 27177 TID-owpcetyx5 INFO: Pausing to allow workers to finish...
2018-10-26T19:16:30.417Z 27177 TID-owpcetyx5 WARN: Terminating 1 busy worker threads
2018-10-26T19:16:30.417Z 27177 TID-owpcetyx5 WARN: Work still in progress [#<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", job="{\"class\":\"MyWorker\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"jid\":\"97323dc06b98b5692a59f802\",\"created_at\":1540581379.335893,\"enqueued_at\":1540581379.33605}">]
2018-10-26T19:16:30.418Z 27177 TID-owpcetyx5 INFO: Pushed 1 jobs back to Redis
2018-10-26T19:16:30.418Z 27177 TID-owpcetyx5 INFO: Bye!
```

My proposition is that Sidekiq waits for all processor threads to finish when it receives a `SIGTERM` or `SIGINT`. If user is stopping the `sidekiq` process with `Ctrl-C` (as opposed to via `sidekiqctl stop`), pressing `Ctrl-C` again could mean "ok, now really abort".  The `sidekiqctl stop` command already has a kill timeout which will `kill -9` the sidekiq process after the timeout expires, which allows `sidekiq` to behave like a good citizen and wait for processor threads to finish.

Without this, our workers can never truly guarantee not to leave an inconsistent state.

**Comment by mperham** [comment]
There is no way to do this if systemd is starting Sidekiq directly.  Processes must stop within a certain configured timeout -- systemd cannot just wait until they are done and exit themselves.

The only way around this is to abstract how the process is managed so you can use a rolling restart mechanism, which is implemented in Sidekiq Enterprise.  This still puts limitations on deploys (e.g. more RAM usage, you need major/minor deploys). Detail: https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts

**Comment by janko-m** [comment]
> Processes must stop within a certain configured timeout -- systemd cannot just wait until they are done and exit themselves.

Isn't that what the `sidekiqctl stop` command already ensures with its kill timeout? I don't know how do people typically configure systemd with Sidekiq, but we run Sidekiq with Monit, which configures a start command (`sidekiq ...`) and a stop command (`sideqkictl stop`). I don't think that the Sidekiq process needs to think about how long processor threads take to finish on shutdown, `sidekiqctl stop` already comes with a kill-switch.

I didn't know that Sidekiq Enterprise has this functionality, I guess waiting for processor threads to finish is more involved then I thought.

**Comment by mperham** [comment]
Yes, systemd and sidekiqctl make the same assumption: sidekiq must exit within a certain time or they use kill -9.

**Comment by janko-m** [comment]
But I thought the advantage of `sidekiqctl stop` is that the `sidekiq` process can wait for processor threads to finish after `Sidekiq::Shutdown` was raised in processor threads. Having `sidekiq` terminate processor threads without waiting is for me effectively `kill -9`, except the jobs get re-queued back (which is of course necessary). If workers are not able to handle `Sidekiq::Shutdown` exceptions (or they can but that handler code is not guaranteed to get executed whole), then I don't see much difference.

I don't need `sidekiq` shutdown to exit within a certain time by itself, because I already have the kill timeout in `sidekiqctl stop` which will do it for me. That way workers would be able to handle `Sidekiq::Shutdown` exceptions. I came up with the following patch that seems to work, I hope you don't mind if I share it here:

```rb
require "sidekiq/manager"

module SidekiqManagerWaitStop
  def stop(*args)
    processors = super

    # wait for processor threads to finish when Sidekiq::Shutdown is raised
    processors.each do |processor|
      processor.thread.join
    end
  end
end

Sidekiq::Manager.prepend SidekiqManagerWaitStop
```

**Comment by mperham** [comment]
sidekiqctl can't requeue the jobs.  Sidekiq does have a waiting period, the shutdown timeout controlled with `-t`.  After that period, it requeues any lingering jobs and exits.

Your patch does not work where the processor thread swallows Sidekiq::Shutdown.  Badly written Sidekiq::Workers can hose the shutdown in that case.

**Comment by janko-m** [comment]
Thank you for the warning. You're right, for example `Open3.capture3` will react to `Sidekiq::Shutdown` only after the shell command has finished, so workers running any long-running shell commands using `Open3.capture3` would not get their jobs re-queued.

The waiting then needs to happen after re-queueing, so overriding `Sidekiq::Launcher#stop` like this seems like a good solution for me:

```rb
require "sidekiq/launcher"

module SidekiqLauncherWaitStop
  def stop(*args)
    processors = @manager.workers.dup

    super

    # wait for processor threads to finish when Sidekiq::Shutdown is raised
    processors.each do |processor|
      processor.thread.join
    end
  end
end

Sidekiq::Launcher.prepend SidekiqLauncherWaitStop
```

**Comment by janko-m** [comment]
Thank you very much for your help. I will close this issue as the feature I want is already available in Sidekiq Enterprise.
