### ISSUE TITLE
Redis::CannotConnectError: Error connecting to Redis using Heroku Redis

### ISSUE THREAD

**Issue by 8vius** [mperham/sidekiq#4009]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.2

Stack trace in honeybadger:

```
client.rb  348 rescue in establish_connection(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:348:in `rescue in establish_connection'
346            Errno::ETIMEDOUT
347 
348       raise CannotConnectError, "Error connecting to Redis on #{location} (#{$!.class})"
349     end
 client.rb  331 establish_connection(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:331:in `establish_connection'
329     end
330 
331     def establish_connection
332       server = @connector.resolve.dup
 client.rb  99 block in connect(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:99:in `block in connect'
 97       # Don't try to reconnect when the connection is fresh
 98       with_reconnect(false) do
 99         establish_connection
100         call [:auth, password] if password
101         call [:select, db] if db != 0
 client.rb  294 with_reconnect(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:294:in `with_reconnect'
292       begin
293         original, @reconnect = @reconnect, val
294         yield
295       ensure
296         @reconnect = original
 client.rb  98 connect(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:98:in `connect'
 96 
 97       # Don't try to reconnect when the connection is fresh
 98       with_reconnect(false) do
 99         establish_connection
100         call [:auth, password] if password
 client.rb  367 ensure_connected(...)
[GEM_ROOT]/gems/redis-4.0.2/lib/redis/client.rb:367:in `ensure_connected'
365           end
366         else
367           connect
368         end
```

My initializer: 

```
Sidekiq::Extensions.enable_delay!
```

I had already properly pointed the `REDIS_PROVIDER` to `REDIS_URL` as you can see here in my env variables:

```
REDIS_PROVIDER:               REDIS_URL
REDIS_URL:                    redis://xxxxxxx.com:6969
```

The error had stopped for a while but came back up again and I have no idea what I'm missing. I'm also not using RedisToGo but rather the Redis Heroku addon.

**Comment by ChrisLahaye** [comment]
You did not provide a full stack trace so its hard to see where the exception is thrown. Just note that a timeout can happen when waiting longer than 5 seconds for an available redis connection. This can happen when you run more concurrent workers than the size of your redis connection pool. So you need to make sure that the size of your connection pool (declared in your sidekiq initializer) is greater than the number of concurrent workers (declared in the sidekiq.yml configuration file).

**Comment by 8vius** [comment]
@ChrisLahaye Sorry to bother again, this is my `sidekiq.yml` and in my original post I have my initializer which only contains 1 line, what is the default connection pool size for sidekiq? Seems what you mentioned might be the issue. 
 
```
---
:concurrency: 4
staging:
  :concurrency: 4
:production:
  :concurrency: 25
:queues:
  - default
  - mailers
```

**Comment by ChrisLahaye** [comment]
@8vius The default by sidekiq for the redis connection pool is MAX_RAILS_THREADS. This variable is usually defaulted to five.

You need to make sure every sidekiq worker can use a redis connection, this means that your concurrency factor MUST NOT be greater than the size of your redis connection pool thread. The author of this repo advices to take at least a pool of (concurrency + 5).

Also make sure that your sidekiq workers can each check out a database connection. The database connection pool by rails is also set to MAX_RAILS_THREADS.

So in the end the connection pools a worker depend on all have MAX_RAILS_THREADS or greater size. So your concurrency factor should be that. I scale all these variables based on MAX_RAILS_THREADS and do the following:

initializers/sidekiq.rb
```
Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
  end
  # The connection pool size for clients should match the number of
  # Rails threads such that each thread has its own redis connection.
  # This avoids blocking and matches the default sidekiq client initialization.
  config.redis = ConnectionPool.new(
    size: ENV.fetch('RAILS_MAX_THREADS') { 5 }
  ) { Redis.new }
end

Sidekiq.configure_server do |config|
  # The connection pool size for servers should provide plenty of connections
  # for the threads running in each process. A Sidekiq server process requires
  # at least (concurrency + 5) connections.
  #
  # See https://github.com/mperham/sidekiq/wiki/Using-Redis
  #
  config.redis = ConnectionPool.new(
    size: Sidekiq.options[:concurrency] + 5
  ) { Redis.new }
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
  end
end
```

sidekiq.yml
```
# The number of workers should match the size of the database connection
# pool thread to avoid blocking. So scaling should be performed via the
# RAILS_MAX_THREADS environment variable.
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
```
