### ISSUE TITLE
Redis v5 Optimizations?

### ISSUE THREAD

**Issue by chaffeqa** [mperham/sidekiq#4011]
Was just curious on whether [any of the new features](https://redislabs.com/blog/redis-5-0-is-here/) introduced in v5 can be used to optimize sidekiq (or faktory)... I know its a ways down the road that most cloud providers will support that version, but still curious, got any thoughts?

**Comment by mperham** [comment]
I keep track of Redis and what it might add to help but I have to beware because Sidekiq must support older versions of Redis.  5.0 doesn't add anything useful for Sidekiq that I'm aware of but I'm happy to hear brilliant ideas if anyone's got one.
