### ISSUE TITLE
Redis Cluster with sidekiq doubts

### ISSUE THREAD

**Issue by mPanasiewicz** [mperham/sidekiq#4012]
Hello @mperham,

I'd like to implement on my infrastructure redis cluster. When I was reading about clustering sidekiq I was surprised because of that https://github.com/mperham/sidekiq/wiki/Using-Redis#architecture

Can you tell me what is the real danger of clustering redis instead of sentinel?
Why SaaS solution is recomended than my own dedicated solution on my own VPSes??

Kind Regards

**Comment by mperham** [comment]
Cluster is for caching and similar workloads that can scale horizontally.  That is not Sidekiq.
