### ISSUE TITLE
Would it be possible to crash if "sidekiq/testing" is required in production?

### ISSUE THREAD

**Issue by ndbroadbent** [mperham/sidekiq#4013]
I thought I would be clever and use a `Sidekiq::Testing.inline!` block during one of my rake tasks that loads some demo data. Basically I needed to chain a few background jobs in a sequence, so that I could generate some dummy data. I reached for `Sidekiq::Testing.inline!` because it seemed like it would do what I want.

What I didn't realize is that calling `require "sidekiq/testing"` would actually call `Sidekiq::Testing.fake!` behind the scenes (I thought I would need to do this manually.) 
I added `require "sidekiq/testing"` at the top of one of my Ruby files, and inadvertently disabled all of my background jobs. Fortunately I caught this on staging when I noticed that none of my jobs were running. But it would have been much better if my deployment had crashed during the `assets:precompile` task.

Would it be possible to add a new setting to `sidekiq.yml`, so that I could configure Sidekiq to crash with an error if `sidekiq/testing` is required in production? I won't do that again, but I'd like to prevent any other developers from making that mistake.

**Comment by ndbroadbent** [comment]
Actually `assets:precompile` wouldn't have caught it because I'm not loading the Rails environment. But it would have crashed during `db:migrate`, because I always run that during deploys.

I decided to add this to the bottom of `config/environments/production.rb`:

```ruby
  config.after_initialize do
    if defined?(Sidekiq::Testing)
      raise '⛔️ You must never call \'require "sidekiq/testing"\' in production! ⛔'
    end
  end
```

That's a good workaround for now, but I think it would be great if Sidekiq either crashed by default when `Rails.env.production?`, or if `require "sidekiq/testing"` didn't have any side effects.

**Comment by mperham** [comment]
I don’t think this is a sharp edge that needs dulling. If you use the testing API outside of the testing environment, you are on your own.
