### ISSUE TITLE
Error fetching job: Connection timed out

### ISSUE THREAD

**Issue by FRdevs** [mperham/sidekiq#4014]
[Timeout error](https://gist.github.com/FRdevs/e1eef98a6b01b0a22b10acfcb075d812) sometimes happen on our server. I searched the related issues to fix this, but they didn't work for me. The log after running `kill TTIN $pid` are [here](https://gist.github.com/FRdevs/f5d1999393f724a7dcba0010c64f4502)
, our configuration:
`pool: 25`
...
```
:verbose: false
:concurrency:  20
:queues:
  - critical
  - default
```

**Comment by mperham** [comment]
Please upgrade Sidekiq to latest.

**Comment by mperham** [comment]
Reopen if it continues.

**Comment by FRdevs** [comment]
I got new error after updating to the lastest version(5.2.2), redis 3.3.5:
```
2018-11-07T21:02:40.820Z 6937 TID-1iro7t WARN: Redis::TimeoutError: Connection timed out
2018-11-07T21:02:43.701Z 6937 TID-1isoqx ERROR: Error fetching job: Connection timed out
```

**Comment by mperham** [comment]
The issue template says to include your initializer. Include your initializer.

**Comment by mperham** [comment]
Your config is far more complex than it needs to be but I don't see anything wrong that would cause timeouts.  I'm guessing you need to debug your Redis plan.

https://github.com/mperham/sidekiq/wiki/Using-Redis#timeouts
