### ISSUE TITLE
Feature Request: invalidate batches from Web UI

### ISSUE THREAD

**Issue by mcfadden** [mperham/sidekiq#4015]
We currently handle invalidating batches as described in the wiki [here](https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch).

There are times where we need to manually invalidate a batch, which we currently do using `Sidekiq::Batch.new(bid).invalidate_all`. Since we are already pulling up the web UI to find the batch id for that call, it would nice if there was an "Invalidate All" button on the batch in the UI.

The only concern that comes to mind is someone who isn't implementing a check for `valid_within_batch?` might be confused when nothing happens when they click that button.

And a bonus feature request: if the UI indicated that a batch has been invalidated it would make my day.

**Comment by mperham** [comment]
I think I'm going to stick with what we already have today.  I think an invalid badge or count would be of limited usefulness to most customers.

**Comment by badosu** [comment]
We have a use case where a button to invalidate a batch would be very useful, and it does not make sense to tie the bid to a model. We also have limited access to the production environment, so direct access is not possible.

I am looking at building a plugin tab to enable a provided bid to be invalidated, monkey-patching a button to perform it in the batches UI or adding a command to our bot.

Either way, it would surely be a useful addition for our team.
