### ISSUE TITLE
web server long response time for push request to sidekiq

### ISSUE THREAD

**Issue by zarnautovi** [mperham/sidekiq#4017]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 5.2.1

Hi,

I am using sidekiq with rails 5.2.1 and I have long web server response when sidekiq client push request to queue. I find out that this is happening when I recieve larger json  request (100-300 KB). In those cases my response time goes to 29000 ms.
Application is on Heroku and I find out through new relic that redis database query:
multi
sadd ?
lpush ?
exec
taking 99% of reponse time.

We are using puma server (2 workers with 5 threads pre worker), Sidekiq concurency is set to 20 and db pool is also set on 20.

This is our sidekiq.rb:

```
Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_SIDEKIQ_URL'], network_timeout: 3600}
end
if Rails.env.production?
  Sidekiq.configure_server do |config|
    poll_size =  (Sidekiq.options[:concurrency] + 2)
    config.redis = { url: ENV['REDIS_SIDEKIQ_URL'], network_timeout: 3600, size: poll_size }
    Rails.application.config.after_initialize do

      Rails.logger.info("DB Connection Pool size for Sidekiq Server before disconnect is: #{ActiveRecord::Base.connection.pool.instance_variable_get('@size')}")
      ActiveRecord::Base.connection_pool.disconnect!

      ActiveSupport.on_load(:active_record) do
        config = Rails.application.config.database_configuration[Rails.env]
        config['reaping_frequency'] = ENV['DATABASE_REAP_FREQ'] || 10 # seconds
        config['pool'] = poll_size
        ActiveRecord::Base.establish_connection(config)
        Rails.logger.info("DB Connection Pool size for Sidekiq Server is now: #{ActiveRecord::Base.connection.pool.instance_variable_get('@size')}")
      end
    end
  end
else
  Sidekiq.configure_server do |config|
    config.redis = { url: ENV['REDIS_SIDEKIQ_URL'], network_timeout: 3600 }
  end
end

Sidekiq::Web.set :sessions, false
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
```

Do you have some tips how to solve this (is this redis database problem or my sidekiq configuration is bad) ?

**Comment by zarnautovi** [comment]
I have more information regarding this. I manage to reproduce this on another instance of my application but it happend randomly, so size of request is not issue.
I takeover this app and now trying to fix stuff that are not working good, and this is my observation:

rack-timeout is instaled and timeout option is set to 29 sec. Code for creating this jos is:

```
@job = BatchWorker.perform_async(params.merge!({:channel => request.headers["channel"]}).permit!.to_unsafe_h)
      h = {"response" => {"job_id" => @job}}
      render json: h
    end
rescue Rack::Timeout::RequestTimeoutException, StandardError, SystemCallError
    render json: {status: "Fix the error"}
```
Now I understand that rack-timout is set 1 sec before heroku 30 sec timeout. (So what I assuming is that previous developers set this so they dont get timeout from heroku and then other side know to re run request).

Those request never get to worker so web client timeout when trying push request to worker. (This is random behaviour because same request get to worker on next request).

**Comment by mperham** [comment]
I'm not sure what you expect us to do here.  If your app, network or infrastructure is slow, there's nothing we can do to fix that.

**Comment by zarnautovi** [comment]
I just asking is my sidekiq setup and how requests are queued ok ? And Do you have the thought that most likely caused this?

**Comment by mperham** [comment]
I think a 30+ sec web request is a sign you need to profile and tune that action.

The worst part of your initializer is `network_timeout: 3600`, which is **way** too long.  Don't set it higher than 5 unless you have a specific reason.

**Comment by zarnautovi** [comment]
thanks you :)

**Comment by ppascualv** [comment]
Hi @zarnautovi 
I'm facing the same issue that you posted long time ago, did you find any solution?
