### ISSUE TITLE
Sidekiq is able to run only 10 jobs when the concurrency is 10. If we are required run 20 jobs simultaneously, 10 of them are failing silently

### ISSUE THREAD

**Issue by rubystar** [mperham/sidekiq#4018]
Ruby version: 2.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq opensource version

Please include your initializer and any error message with the full backtrace. 
No Errors
initializer code:
```ruby
require "sidekiq"
 
redis_url = ENV.fetch("REDIS_URL")
 
Sidekiq.configure_client do |config|
  config.redis = { url: redis_url, namespace: "sidekiq" }
end
 
Sidekiq.configure_server do |config|
  config.redis = { url: redis_url, :namespace => "sidekiq" }
end
 
SIDEKIQ_CONFIG ||= YAML.load(ERB.new(File.read("config/sidekiq.yml")).result).fetch(ENV['RACK_ENV'])
```

Are you using an old version?
 yes, version: 2.17.8
Have you checked the changelogs to see if your issue has been fixed in a later version?
No, it doesn't appear to be a version issue

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

config/sidekiq.yml
```ruby
:verbose: false
:concurrency: 10
:queues:
  - default
 
default: &default
  :pidfile: 'tmp/pids/sidekiq.pid'
  :logfile: 'log/sidekiq.log'
  :errlog: 'log/sidekiq.err'
  monitoring:
    username: 'username'
    password: 'password'
 
development: 
  <<: *default
  :concurrency: 5
  :verbose: true
 
test:
  <<: *default
  :concurrency: 1
 
sandbox:
  <<: *default
  :concurrency: 5
 
integration:
  <<: *default
  :concurrency: 10
 
staging:
  <<: *default
  :concurrency: 20
 
production:
  <<: *default
  :concurrency: 20
```

**Comment by mperham** [comment]
I don't support Sidekiq 2 anymore.  Please upgrade to at least Sidekiq 4.

**Comment by rubystar** [comment]
Wow, thanks for replying so quickly. i'll upgrade it tomorrow and provide more details. Thanks so much.
But in general, when the concurrency is 10, the other jobs should wait until the queue is free without failing right?

**Comment by mperham** [comment]
Yes, but you haven't shown us any error message or backtrace so I have no clue what might possibly be wrong.

And note you have a password in your description.

**Comment by rubystar** [comment]
Hi, I'm still in the process of upgrading it to 4.x. On my local machine, with 4.x i see the sidekiq UI is better than the old version and it can show up the failures under `dead` tab. So that would help to see why are jobs failing. It appears it's going to take some more time for me to give any update. Thanks

**Comment by rubystar** [comment]
It turns out the issue is not with sidekiq, but in application code. Closing this. Thank you.

**Comment by rubystar** [comment]
@mperham i do see an issue only on staging/production but not in development.
My use case is: 
I have 2 separate apps, let's say App A and App B
B calls a A, and A triggers a sidekiq job and provide a redis key to check the progress of sidekiq job
B calls A to know the progress of sidekiq job.
Sometimes, A can't find the key in redis(which it should find)
B throws error saying key not found at A

B triggers a number sidekiq jobs at A through a loop. Some of them have no issues but 5 out of 20 are failing with the key is not found issue.
Again, this is not happening on development. I see 100% success rate on development.

In your experience has anybody faced such issue? i think it's mostly to deal with Redis. Can you pls advice what could be the issue? Thanks

**Comment by mperham** [comment]
@rubystar I can't help you debug your app code or any custom job status code you wrote.  It sounds like you have a race condition.  Your code can [fetch the status](https://github.com/mperham/sidekiq/wiki/Batches#status) of a batch via API but I don't have any APIs for tracking a single job.
