### ISSUE TITLE
Web UI is not closing Redis client connections on exit.

### ISSUE THREAD

**Issue by umar221b** [mperham/sidekiq#4019]
Heroku app:
Ruby version: 2.4.1
Rails version: 5.1.6
Sidekiq version: 5.1.3
Web UI accessed on MacOS (on both Chrome 70.0.3538.77 and Safari 12.0.1)

My initializer is pretty straightforward:
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['redis_server_url'] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['redis_server_url'] }
end

Sidekiq.default_worker_options['retry'] = 0
```

It seems that the Web UI is not closing its client connections to Redis after the tab/browser is closed. The Web UI clients are still showing when I `CLIENT LIST` from redis-cli.
Is this intended?

Clients go under the name: Sidekiq-client-PID-3, I made sure it is the Web UI client as it resets the idle counter each time I open the Web UI.

![screen shot 2018-11-12 at 12 49 58 pm](https://user-images.githubusercontent.com/30433769/48342934-af394f00-e679-11e8-89f4-5ab19284e1d8.png)

**Comment by mperham** [comment]
That’s as designed. Connections stay open.

**Comment by umar221b** [comment]
Thanks, Mike.
I am closing this.
Though, I would really love to learn if it is designed this way to gain a certain advantage, or is it just not worth it to close the connections?

**Comment by mperham** [comment]
The connection is between the Ruby app server and Redis. The reason is performance. The connections are lazy created so if you only use one it will only create one.

**Comment by umar221b** [comment]
Thank you.
