### ISSUE TITLE
Stale Sidekiq jobs blocking sidekiq

### ISSUE THREAD

**Issue by heamaral** [mperham/sidekiq#4020]
Hi,
I'm using GitLab CE and after some hours running sidekiq hangs and doesn't respond to TTIN signal.

Ruby version: 2.4.5p335
Sidekiq version: 5.2.1

Gist with full backtrace of threads:
https://gist.github.com/heamaral/0ae43f35b9d446e1732fbc970cf591b1

**Comment by mperham** [comment]
Please contact GitLab support.
