### ISSUE TITLE
Sidekiq is having a hard time loading the class 

### ISSUE THREAD

**Issue by kchoiinfluitive** [mperham/sidekiq#4021]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): 4.2.1

We're using sidekiq on top of hanami service and we're facing an issue where class name is not being loaded in time so Sidekiq errors out with `NameError: uninitialized constant <class name>`

Following is the stack trace, 

```
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261 :in `const_get`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261 :in `block in constantize`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `each`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `inject`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259 :in `constantize`
[GEM_ROOT]/gems/activesupport-4.2.10/lib/active_support/core_ext/string/inflections.rb:66 :in `constantize`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:127 :in `block in process`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq.rb:35 :in `block in <module:Sidekiq>`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126 :in `process`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82 :in `process_one`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70 :in `run`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17 :in `watchdog`
[GEM_ROOT]/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26 :in `block in safe_thread`
```

We're suspicious about `sidekiq-4.2.10/lib/sidekiq/processor.rb:127 :in block in process`. 
Our theory is that it might be because while multiple threads are running, it fails to pass around the state properly and while one thread is about to load the class another thread is trying to fetch it which results in a failure.

**Comment by mikegee** [comment]
This should help: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#autoloading
