### ISSUE TITLE
one thread on a specific process

### ISSUE THREAD

**Issue by MarieS1415** [mperham/sidekiq#4024]
Ruby version: 2.3.0
Sidekiq version: 4.2.10

Hello, 
I would like to have only one thread on a specific sidekiq worker, but to keep multithreads on my other workers.
Is it possible?

With what I understood form https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency, I tried to add `sidekiq_options :concurrency => 1` on top of my worker class but it does no have any effect.

Thank you for your help!

**Comment by mperham** [comment]
`bundle exec sidekiq -c 1`
