### ISSUE TITLE
Job Lifecycle clarification

### ISSUE THREAD

**Issue by josh-m-sharpe** [mperham/sidekiq#4025]
https://github.com/mperham/sidekiq/wiki/Job-Lifecycle

This page states: `It's important to note that a job will never end up in Failed, as it's a purely transitive state.` However, I can click on the "Failures" tab and be taken to `/sidekiq/failures` which shows "Failed Jobs"  These things seem contradictory.

Maybe related, but what's the difference between a Failed and a Dead job? Maybe I'm missing something, somewhere?

Much appreciated, Thanks!

**Comment by mperham** [comment]
Remove the sidekiq-failures gem from your Gemfile.

**Comment by josh-m-sharpe** [comment]
Seems like that did it.  Thanks! 👍
