### ISSUE TITLE
DRY inside job supporting batch & no batch

### ISSUE THREAD

**Issue by tjbp** [mperham/sidekiq#4033]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): Pro

This is really a query as to whether I'm missing something in Sidekiq's batch API. I have a job that is called from inside a batch sometimes, but not always. I end up having to repeat code as such when queueing another job that must be in the same batch (if we're in a batch at all):

    if batch
      batch.jobs do
        # queue other job
      end
    else
      # queue other job repeated
    end

**Comment by mperham** [comment]
You can write a wrapper like so:

```ruby
def more_jobs
  if batch
    batch.jobs do
      yield
    end
  else
    yield
  end
end

# inside your worker
def perform
  more_jobs do
    SomeWorker.perform_async
  end
end
```

Now you've DRY'd up that conditional.
