### ISSUE TITLE
Prepend automatically ActiveJob queue name prefix when starting Sidekiq with Rails

### ISSUE THREAD

**Issue by Startouf** [mperham/sidekiq#4034]
I have recently made an edit to the wiki https://github.com/mperham/sidekiq/wiki/Active-Job to add hints on how to deal with queue name prefix from ActiveJob.

I was wondering if maybe this should be integrated directly into Sidekiq default config, or via an option ?

```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  queue_name_prefix = ::ActiveJob::Base.queue_name_prefix
  queue_name_delimiter = ::ActiveJob::Base.queue_name_delimiter

  config.options[:queues] = config.options[:queues].map do |queue_name|
    [queue_name_prefix, queue_name].compact.join(queue_name_delimiter)
  end
end
```

Note : I found [this relevant issue](https://github.com/mperham/sidekiq/issues/3191), but which seems to have been closed without thinking too much about it

**Comment by mperham** [comment]
What is the usecase?  Why prepend?

**Comment by Startouf** [comment]
So basically, given that we configure ActiveJob with a prefix like

```ruby
config.active_job.queue_name_prefix = "MyApp_#{Rails.env}"
```

This means that whenever we are writing a job using `queue_name` like

```ruby
class MyJob < ApplicationJob
  queue_as :my_queue 
  def perform
    ...
  end
end
```

The job will actually be enqueued, not on `my_queue` but either `MyApp_development_my_queue`, `MyApp_staging_my_queue`, etc.

And so, you would need per-environment configuration in the `sidekiq.yml` and duplicate the configuration, and you would need to include the full queue name

```yaml
---
:concurrency: 5
staging:
  :queues:
    - [MyApp_staging_my_queue, 2]
    - ['...', 1]
production:
  :queues:
    - [MyApp_production_my_queue, 2]
    - ['...', 1]
```

In other ActiveJob Adapters, it is possible to simply add the queue name without prefix, and if we detect an ActiveJob integration, the lib would automatically add the prefix (**pre**fix --> **pre**pend). 

With my code in the initializer it is possible to just declare a single time the queue list, without the prefix, Drying-up the code

```ruby
:concurrency: 5
:queues:
    - [my_queue, 2]
    - ['...', 1]
```

I am asking if this could become a feature of Sidekiq (for a better ActiveJob integration), or if this is better left in the wiki.

**Comment by mperham** [comment]
It's a hack and shouldn't be used, exactly like redis namespaces are a terrible idea too.  You will still have environments sharing retries, scheduled jobs, dead jobs and the Web UI will be intermingled too. **Don't use this feature.**

https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/

If you want to share a single Redis with many environments, use a different db number:

```ruby
dbnum = Rails.env.staging? ? 1 : 0
config.redis = { db: dbnum }
```

https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-initializer

No hacky magical config required and each environment is encapsulated in its own Redis database which can be flushed separately.

**Comment by Startouf** [comment]
Thanks for the reference to the article, actually I did not think too much about it my situation, but it is a bit different than what you are thinking.

I am migrating from a Shoryuken ActiveJob Adapter. It relies on AWS SQS where we don't have separate databases, and instead must rely on different queue names, and basically I HAD to use a prefix to separate production from staging queues. AWS SQS is designed this way, can't really help it : the name of the queue actually acts as an ID for that queue/the queue service, and there is no other way to namespace it. (Actually it would be possible to use different AWS account IDs to act as different namespaces but meh...)

I guess this prefix no longer has any real meaning if I switch to a redis database with the sidekiq adapter. I can actually set up a whole different DB server, I wasn't planning to use the same DB for all environments : I intend to have one redis database per environment, so actually the prefix won't be really helpful here, but as you can see it can be useful if I decide to rollback using SQS/Shoryuken adapter or possibly a different adapter.

So, I believe I have still a good point in trying to use the namespace, not in order to SHARE the redis storage with other applications, but just to preserve a good abstract implementation of ActiveJob.

(However I do really appreciate you linking this article, as I could have been tempted to **also** share the Redis for several applications taking advantage of namespaces)

**Comment by lucaspiller** [comment]
@mperham Would it be possible to spit out a warning or similar if this option set? I've just upgraded an old app to Rails 5.2, and saw `config/environments/production.rb` has this configuration by default: 

```
  # Use a real queuing backend for Active Job (and separate queues per environment)
  #config.active_job.queue_adapter     = :resque
  #config.active_job.queue_name_prefix = "myapp_#{Rails.env}"
```

I thought simply uncommenting those two lines and s/resque/sidekiq would mean I'm good to go. It's not  obvious that this feature isn't supported by Sidekiq, other than this closed issue.

**Comment by mperham** [comment]
@lucaspiller Maybe someone should open an issue with ActiveJob, stating that this feature is dangerous and unsupported for some adapters?  I would be happy with a boot-time check in `sidekiq/rails` that checks if queue_name_prefix is set and prints an error message.

**Comment by gr8bit** [comment]
Sorry to jump in on this closed issue @mperham , but I would like to throw in my use case which I think requires something like queue prefixes:
I have a "multi tenancy" application using ActiveJob with sidekiq backend which is being built into two docker images - each containing its own assets, views and other tenant-specific data. These images are hosted as separate services, one per tenant.
Each service has a separate sidekiq container for asynchronous processing of tasks like PDF generation or sending emails. Currently each tenant app is just configured using a different queue prefix but using the same Redis DB.
I could let each tenant use a different DB as you already suggested, but:
I have the case where tenant A (the operator of the application) invites people (=give them logins) to other tenants. When devise (which I use) sends out its account generation emails, these emails are sent out by the tenant A's service and therefore with the texts and design of that service. This is not what I want. They should be sent out in the design and with the texts of the tenant they are invited to! So the tenant A service has to be able to put something in the queues of another tenant's service.
How would you recommend doing this?

**Comment by mperham** [comment]
Please open your own issue.

**Comment by dorianmariefr** [comment]
I think this should do it:

```
Sidekiq.configure_client do |config|
  config.redis = { namespace: Rails.configuration.active_job.queue_name_prefix }
end

Sidekiq.configure_server do |config|
  config.redis = { namespace: Rails.configuration.active_job.queue_name_prefix }
end
```
