### ISSUE TITLE
Question about Sidekiq Batches Callback

### ISSUE THREAD

**Issue by danielnc** [mperham/sidekiq#4035]
I could not find any information if callbacks will be called only once whenever a job completes/is successful or if due to the concurrent nature of sidekiq we cannot guarantee that the method will only be called once and there won't be concurrency issues

 https://github.com/mperham/sidekiq/wiki/Batches#callbacks

Could you help me better understand this to see if I need to deal with concurrency on my callback code or is it safe to assume it will be called only once?

**Comment by mperham** [comment]
Batch callbacks are implemented as just another Sidekiq job.  They might be executed more than once under certain circumstances (for instance, during a deploy stop/start current jobs are pushed back to Redis and restarted).

Several batches might have their callbacks called concurrently in the same process, meaning your callback code still needs to be threadsafe.

**Comment by danielnc** [comment]
@mperham thank you!

I think it would be a good idea to update sidekiq documentation to make this explicit
