### ISSUE TITLE
ActiveRecord models don't populate created_at attributes

### ISSUE THREAD

**Issue by Valve** [mperham/sidekiq#4036]
Ruby version: ruby 2.5.3p105
Sidekiq / Pro / Enterprise version(s): Sidekiq Enterprise 1.7.1

My initializer:

```ruby
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    if Rails.env.production?
       mgr.register('0 * * * *', Scheduled::CheckEnqueuedSidekiqSizeWorker)
       mgr.register('57 * * * *', Scheduled::EmailHealthWorker)
       # many more jobs (around 30 more)
    end
end
```

Sidekiq.yml

```yams
---
:queues:
  - [priority, 5]
  - default
  - mailers
  - rollbar
```
many other queues with priorities < 1

Rails version:
5.2.1

Deployed on Heroku with:

```sh
worker: bundle exec sidekiq -c 8 -t 25 -C ./config/sidekiq.yml -v
```

2X workers (4 dynos).

**This error is intermittent and hard to reproduce reliably**. This leads me to think it's a threading/concurrency issue.

Essentially, when we call `create!` on any ActiveRecord model, `created_at` are not populated by Rails automatically and we get this (a lot of these):

```
PG::NotNullViolation:
ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1234, 393, 3936, null, null)
```

Sometimes restarting the worker helps, sometimes it does not.

What **DOES** help is the downgrade to Sidekiq OSS version. All errors go away. We're running regular OSS version of sidekiq now even though we have an enterprise subscription. Any help in diagnosing t his is much appreciated!

**Comment by mperham** [comment]
I've never seen or heard of this issue.  Sidekiq doesn't touch Rails except to boot it and run all jobs within the ActiveSupport::Executor.  I have no clue why Pro/Enterprise might cause ActiveRecord problems.

Can you give me a smaller app which reproduces the problem?

**Comment by Valve** [comment]
@mperham we'll try to create a minimal reproducible example app today/Monday

**Comment by Valve** [comment]
issue was in our code, closing

**Comment by sgara** [comment]
@Valve could you share what kind issue of you had? Got the same error and can't find where it comes from...
Thanks!

**Comment by Valve** [comment]
@sgara unfortunately I don't remember the details and no longer have access to that code.. but I do remember that sidekiq wasn't guilty, it was a bug in our code; somehow we overwrote the values for created_at/updated_at
