### ISSUE TITLE
Sharing Redis Instance Across Multiple Heroku Rails Applications

### ISSUE THREAD

**Issue by garyfoster** [mperham/sidekiq#4040]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.2

We manage a system of multiple related Rails applications deployed in Heroku Enterprise Private Spaces. The add-ons on this private platform such as Redis are quite expensive and I'm wondering if it's possible to share a Redis instance for Sidekiq across multiple applications.

I did a quick test and it appeared to act unexpectedly but I can't tell for sure since I am not familiar with the internals of Sidekiq and how it interacts with storage. It seems as though sidekiq on each app was possibly getting jobs from the other apps.

Figured I'd ask a question here before diving in deeper with a lot more effort. We are also open to the idea of upgrading to Pro or Enterprise if that will help here.

**Comment by mperham** [comment]
The only way you can share a Redis instance between different apps is with databases or namespaces.  I'm not sure if your Redis provider allows you to use multiple databases, but that is the better solution if possible.  Both are [discussed here](https://www.mikeperham.com/2015/09/24/storing-data-with-redis/) and work with Sidekiq OSS.  Sidekiq (and the industry generally) calls each separate Redis database a "shard".

Sidekiq Pro allows you to aggregate multiple shards into one Rack process, so you don't need one Web UI process/dyno per shard:

https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding

**Comment by mperham** [comment]
More discussion of sharding: https://github.com/mperham/sidekiq/wiki/Sharding

**Comment by garyfoster** [comment]
Excellent article. I'm going to try to implement the multiple database option which makes sense for our usage cases.
