### ISSUE TITLE
Add the Ability to Sort Enqueued Page Both By "Most Recently Enqueued" As Well As "Next To Process"

### ISSUE THREAD

**Issue by jfelchner** [mperham/sidekiq#4041]
This is a feature request from #4037 

I'd like to have the ability to sort the "enqueued" page so that it shows the jobs either by "Most Recently Enqueued" (as it does now) as well as "Next To Process".

The rationale is that I'd like to be able to sit on the first page (especially with Live Poll enabled) and watch which items are about to be run (among other reasons)

**Comment by mperham** [comment]
I have no plans to implement but would be open to a PR if you want to dive in.
