### ISSUE TITLE
Correctly calculating queueing delay with super_fetch!

### ISSUE THREAD

**Issue by christos** [mperham/sidekiq#4044]
Ruby Version: 2.5.3p105
Sidekiq Version: Sidekiq 5.2.3 / Sidekiq Pro 4.0.4

We use the following middleware to calculate and send queueing delay stats to DataDog via Statsd:

```ruby
class SidekiqInstrumentationMiddleware
  def call(worker, msg, queue, &block)
    name = msg["wrapped"] || worker.class.to_s
    queueing_delay_ms = (Time.current.to_f * 1000).to_i - (msg["enqueued_at"].to_f * 1000).to_i
    begin
      Statsd.client.histogram("sidekiq.jobs.queueing_delay_ms", queueing_delay_ms, tags: tags)
      Statsd.client.increment("sidekiq.jobs.count", tags: tags)
      Statsd.client.time("sidekiq.jobs.perform", tags: tags, &block)
      Statsd.client.increment("sidekiq.jobs.success", tags: tags)
    rescue StandardError
      Statsd.client.increment("sidekiq.jobs.failure", tags: tags)
      raise
    end
  end
end
```

After enabling `super_fetch!` in production we saw queueing delay almost tripled. Strangely enough no other stats (e.g. jobs processed/sec) were affected.

<img width="627" alt="screenshot 2018-12-07 at 16 34 43" src="https://user-images.githubusercontent.com/736/49658286-f977db00-fa41-11e8-8b1a-30a18a5ea58f.png">

My hypothesis is that since `super_fetch!` moves work to private per/process queues (in batches!?) the `enqueued_at` is somehow not representative of the real time the job spent in the queue waiting because of the blocking `POP` operation.

Either that or that moving from the original queue to the private queue does *really* add some fixed overhead to the queueing delay.

I tried to follow the Pro gems source code but couldn't quite figure it out. Any ideas if either of my hypothesis are correct?

**Comment by mperham** [comment]
With basic_fetch, every processor thread pulls its own job directly from Redis.  With super_fetch, every processor thread stalls, waiting on a single fetcher thread which pulls from Redis.  This is necessary because of the increased number of Redis operations necessary to reliably fetch.

So, yeah, super_fetch will have more queue latency; this graph doesn't surprise me.  Safety often comes with a cost.

**Comment by christos** [comment]
Makes sense. 

Maybe worth a mention in the Wiki docs so that it catches less people by surprise?

**Comment by mperham** [comment]
It's the first Note on the Reliability page.  Perhaps it could be worded more clearly.

https://github.com/mperham/sidekiq/wiki/Reliability#notes
