### ISSUE TITLE
Batches Are Not Removed From UI Given Negative Pending Jobs

### ISSUE THREAD

**Issue by jfelchner** [mperham/sidekiq#4049]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Latest

I've had multiple batches get "stuck" on the UI when they have no pending JIDs.  In fact, some of them get stuck with a count that is negative.

![image](https://user-images.githubusercontent.com/285582/49700164-df084380-fba0-11e8-8b0b-28bebb94d8e1.png)

**Comment by jfelchner** [comment]
"Latest" means "Latest versions at the time this was posted"

```
Sidekiq 5.2.3 / Pro 4.0.4 / Ent 1.7.1
```

**Comment by jfelchner** [comment]
I'm also having issues with them not being removed when it says there's a pending job and yet the job it says is pending no longer exists.

This seems to generally happen when that job was retried at least once.

**Comment by jfelchner** [comment]
This can also be accompanied by an incorrect pending count on the batch.  For example, a pending count of `7` but once the queue is drained, the pending count remains `7` and the batch doesn't disappear despite the fact that there are no longer any jobs in the queue.

**Comment by mperham** [comment]
Initializer?  Do you modify the batch at runtime at all, e.g. remove/cancel jobs using the API, have unique jobs enabled, add jobs during batch execution?

**Comment by jfelchner** [comment]
I don't do anything special with regards to manipulating the batches.  I add them when I enqueue them (via the `jobs` block) and that's basically it.

**Comment by mperham** [comment]
Are any of the jobs marked as `unique_for`?  What do your middleware chains look like (start Sidekiq with `-v` to see)?

**Comment by jfelchner** [comment]
Yes, both the job that queues the jobs in the batch as well as the jobs in the batch are unique.

Middleware:

```
2018-12-10T21:59:58.157Z 11233 TID-owxyjps5t DEBUG: Client Middleware: Sidekiq::Enterprise::Unique::Client, Sidekiq::Batch::Client
2018-12-10T21:59:58.157Z 11233 TID-owxyjps5t DEBUG: Server Middleware: Bugsnag::Sidekiq, Sidekiq::Limiter::Middleware, Sidekiq::Enterprise::Unique::Server, Sidekiq::Batch::Server
```

**Comment by mperham** [comment]
I'm worried that a unique job will get tracked by the batch and then not pushed to Redis, leading to a "missing job" that counts in pending.  I specifically try to handle that case by putting the unique client before the batch client but l'm still worried that it's happening somehow.

If possible, you can remove the uniqueness from those jobs and see if the pending issue goes away.

**Comment by mperham** [comment]
Oh wait, you're seeing negative pending.  That case would lead to positive pending.  Nevermind.

**Comment by jfelchner** [comment]
I'm definitely seeing "positive pending" after a job has failed.  Would the uniqueness cause that issue?

It wouldn't be great if we had to remove the uniqueness to keep this from happening. :(

**Comment by mperham** [comment]
Removing uniqueness was just a thought.

Best I can recommend at this point is turning on verbose logging, -v, and look for logging related to any JIDs listed in the Pending JIDs section of each unfinished batch with positive pending.  Do the broken batches have any other commonalities, e.g. same type of batch or type of job?

**Comment by mperham** [comment]
super_fetch can leave jobs pending for hours if it needs to resurrect orphans. Have these batches been pending for minutes or days? Do you see any common exceptions or error data in the batches?

**Comment by jfelchner** [comment]
@mperham give me a day to let these batches sit around and see if they eventually expire.  I know they've sat around for over 12 hours before.  I currently have one that's been in there for 22 hours.

I'm only running one type of job right now but I have other jobs that do similar things in a similar structure.  I'll let you know if they exhibit the same behavior.

**Comment by jfelchner** [comment]
If we can't solve this problem, having a button to be able to delete batches like we delete queues and jobs would be nice.  Otherwise I'm having to spin up a heroku dyno console and copy/paste IDs just to remove them.

**Comment by mperham** [comment]
Any update?

**Comment by jfelchner** [comment]
@mperham now that I'm not jamming through hundreds of batches, this seems to have gone away for the most part.  There's definitely a bug, but tracking it down now would be very difficult.  If you get an itch, I'd try pushing through hundreds of batches with hundreds of thousands of jobs which randomly fail.

If this comes up again I'll reopen.
