### ISSUE TITLE
Cannot run Selenium geckodriver/firefox web scraper asynchronously

### ISSUE THREAD

**Issue by minter** [mperham/sidekiq#4051]
Ruby version: 2.5.3p105 (Ubuntu 18.04)
Sidekiq version(s): 5.2.3
Rails version: 5.2.2

In our application, we do a fair amount of web scraping via background jobs, using Waitr, Selenium, geckodriver, and Firefox. We have these jobs currently running successfully in Resque, but are porting all of our Resque workers over to Sidekiq.

With our ported jobs, if we run them synchronously in the console (eg, `Automator::DishNetwork::OFSC::DispatchRecon::QueuerWorker.new.perform`), they work properly. However, if we run them asynchronously (either with `.perform_async` or launching as a scheduled job), they're failing with this error:

`Selenium::WebDriver::Error::UnknownError: invalid argument: can't kill an exited process`

It also seems to leave orphaned geckodriver processes hanging around on the server until we stop/restart Sidekiq:

```deployer  8408  0.0  0.0  18244  5152 ?        Sl   18:32   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4444
deployer  8423  0.0  0.0  18244  5156 ?        Sl   18:32   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4445
deployer  8434  0.0  0.0  18244  5152 ?        Sl   18:34   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4446
deployer  8454  0.0  0.0  18244  5152 ?        Sl   18:35   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4447
deployer  8486  0.0  0.0  18244  5156 ?        Sl   18:37   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4448
deployer  8873  0.0  0.0  18244  5160 ?        Sl   18:44   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4449
deployer 15133  0.0  0.0  18244  5236 ?        Sl   20:29   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4450
deployer 15576  0.0  0.0  18244  5232 ?        Sl   20:30   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4451
deployer 17047  0.0  0.0  18244  5224 ?        Sl   20:31   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4452
deployer 17618  0.0  0.0  18244  5236 ?        Sl   20:32   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4453
deployer 17693  0.0  0.0  18244  5232 ?        Sl   20:35   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4454
deployer 18154  0.0  0.0  18244  5232 ?        Sl   20:40   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4455
deployer 18986  0.0  0.0  18244  5236 ?        Sl   20:52   0:00 /usr/bin/geckodriver --binary=/usr/bin/firefox --port=4456
```

Our best guess at this point is that there's something with threading that is causing this, but we haven't been able to gather enough diagnostic information to confirm that. Are there any known issues or gotchas in Sidekiq that might generate these types of symptoms?

**Comment by minter** [comment]
Attn @chubchenko

**Comment by mperham** [comment]
Does it work as expected with `-c 1` (i.e. single threaded)?

**Comment by minter** [comment]
We tried a separate Sidekiq process running `-c 1` and only listening on the queue for the web scraper (to isolate its jobs in single concurrency), and had the same error. We've also tried the `sidekiq-limit_fetch` gem to have one job running at a time (which we need for session management), same error.

**Comment by mperham** [comment]
I'm drawing a blank.  Browser driving has always been very brittle in my experience, where version upgrades can get things out of whack.  There's nothing in Sidekiq that prevents a thread-safe scraper but I can't determine anything further.  If you can narrow the issue down with a small app that reproduces the problem, I can dive in further.

**Comment by mperham** [comment]
Are you running the exact same versions in Resque?

**Comment by minter** [comment]
I think we may have a lead from the Selenium debug log - I'm working to confirm, and will follow up if it's the case.

**Comment by minter** [comment]
Based on your suggestion to turn on the selenium debug log, I think we found out what was going on. When we looked at the log, we saw this line:

`Error: no DISPLAY environment variable specified`

We had DISPLAY set up in the shell for the user that runs the worker processes:

```
deployer@production-worker02:~/current$ echo $DISPLAY
:0.0
```

Which had proven to be sufficient for Resque. However, it looks like Sidekiq may handle shell environment variables differently? At any rate, we went into a Rails initializer and added the `ENV` variable:

```
deployer@production-worker02:~/current$ cat config/initializers/selenium.rb 
Selenium::WebDriver.logger.level = :debug
Selenium::WebDriver.logger.output = '/tmp/selenium.log'
ENV['DISPLAY']=':0.0'
```

Restarted Sidekiq, and the jobs started succeeding. So in the end, as with most things, it was user error. Thanks for all the help in pointing us in the right direction!

**Comment by minter** [comment]
Once again, you show why you're better at this than I am. That's exactly right - resque was being started by Monit with the env variable specified, sidekiq by systemd without the env specified.

**Comment by mperham** [comment]
brb, sending you an invoice for $0.

**Comment by minter** [comment]
![giphy](https://user-images.githubusercontent.com/955/49822730-f6376480-fd4b-11e8-96f1-1e8da77ba1fe.gif)
