### ISSUE TITLE
Gem ocassionally not fetching jobs

### ISSUE THREAD

**Issue by lucascharlab** [mperham/sidekiq#4052]
Ruby version: 2.1.10
Sidekiq Enterprise version: 4.2.2

I'm having this issue, in both web ui and gem, sometimes I can't see running jobs. Also, sometimes they fetch some of the jobs, sometimes others and sometimes all of them.
Here is a simplified version of the code
```
ids = []
workers = Sidekiq::Workers.new
workers.each do |process_id, thread_id, work|
  ids << work['payload']['args'].first
end
```
Did someone have the same problem? 
Thank you!

**Comment by mperham** [comment]
Worker data is async and changes all the time.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L882

**Comment by mperham** [comment]
And upgrade. 4.2.2 is years old.
