### ISSUE TITLE
Sidekiq 6.0

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4056]
Welcome to Sidekiq 6.0, the modernization release!

Changes:

* New log format: JSON! [#4050]
* Remove daemonization, pidfile and logfile options [#4045]
* Supported: Rails 5.0+, Ruby 2.5+, Redis 4.0+
* Larger pool size validation [#3970]
  Connection pool size must be >= (concurrency+2), which has been recommended for years now.
* REDIS_PROVIDER validation [#3970]
  Variable must not hold a URL.

**Comment by Tensho** [comment]
@mperham I have been thinking about the general approach for the multiple systems (Rails, Sidekiq, etc) logging in the context of the [daemon hunt](#4045). The new world declares to spit the log entries primary to `STDOUT/STDERR` and abandons the log file. Does it mean Rails on Puma and Sidekiq (both are threaded systems) logs should be multiplexed in a **one flow with the unified log entry structure** and segregated with some sharp tools on demand? What kind of the logging systems would you suggest? Sidekiq documentation always leads the [best practices]. For example, you provided a wonderful [deployment documentation](https://github.com/mperham/sidekiq/wiki/Deployment) with [`systemd`](https://github.com/mperham/sidekiq/tree/master/examples/systemd) and [`upstart`](https://github.com/mperham/sidekiq/tree/master/examples/upstart) examples. It would be very helpful to have a guidence about logging either.

**Comment by mperham** [comment]
If you log to stdout and use systemd for your Ruby services, all log entries from puma, sidekiq, etc will all go into journald, where you can use systemd tooling to grep and inspect output from each service. You'd have to read the systemd docs for more detail, I'm not super familiar with all the options but I'm sure it integrates with syslog, for example.

I don't agree with their differentiation between STDOUT and STDERR but systemd does have a way to mark each logline with a level so systemd can ignore log output beyond a certain level (INFO, DEBUG, etc).

https://www.loggly.com/ultimate-guide/linux-logging-with-systemd/

**Comment by JanStevens** [comment]
Any chance on an update when version 6 will be released? We are holding back for it now (we really like the json logging)

**Comment by mperham** [comment]
When Rails 6 ships.

**Comment by hjhart** [comment]
Hi @mperham – [Rails 6 has shipped](https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/)! Any update when this will be published?

**Comment by mperham** [comment]
When I’m not on vacation, poor timing on my part!

**Comment by hjhart** [comment]
Seemed like there was no telling when rails was going to ship this release, so no, not poor timing. Enjoy your vacation! Look forward to hearing about a release at some point in the future.
