### ISSUE TITLE
Sidekiq hangs and waits for other jobs to finish

### ISSUE THREAD

**Issue by lsg-braymon** [mperham/sidekiq#4059]
Ruby version: 2.5
Sidekiq / Pro / Enterprise version(s): 5.1.2

We have a situation in our app (development environment) wherein we are running 10 the same workers simultaneously. Somewhere in the worker a method is called that is created using `define_method` that looks something like this (basically depending on the configuration if a local or S3 storage will be used):
```
define_method(m) do |*args, &b|
  (local? ? Local : S3).send(m, *args, &b)
end
```
When the process reaches this point, the worker hangs and does not proceed until all 10 jobs are finished.

As a work around we added this to our sidekiq initializer that we grabbed from here https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L275-L277:
```
Rails::Application.initializer "sidekiq.eager_load" do
  Rails.application.config.eager_load = true
end
```
We are wondering if this setup should also be enabled for Rails 5 as well?

Thank you.

**Comment by mperham** [comment]
Don’t do runtime meta programming as it is not thread safe. Do the define_method on boot in an initializer.
