### ISSUE TITLE
Sidekiq with periodic job fails to boot: uninitialized constant

### ISSUE THREAD

**Issue by srpouyet** [mperham/sidekiq#4062]
Ruby version: 2.5.3
Sidekiq Enterprise version: 5.2.1

Hi, when defining a periodic job in the Rails initializer as defined in the [wiki](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#definition):

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # see any crontab reference for the first argument
    # e.g. http://www.adminschoice.com/crontab-quick-reference
    # or   https://crontab.guru/ 
    mgr.register('0 7 * * *', MyPeriodicJob)
  end
end
```

`bundle exec sidekiq` fails to boot:

```
~ master ❯ bundle exec sidekiq                                                                                                         ✭
2018-12-19T13:51:37.949Z 64486 TID-ov8g16yna INFO: Booting Sidekiq 5.2.1 with redis options {:id=>"Sidekiq-server-PID-64486", :url=>nil}
2018-12-19T13:51:37.967Z 64486 TID-ov8g16yna INFO: Booting Sidekiq 5.2.1 with redis options {:url=>"redis://localhost:6379/12", :namespace=>"company:development:sidekiq", :id=>"Sidekiq-server-PID-64486"}
uninitialized constant MyPeriodicJob
```

The solution seems to be to pass the class name as a string:

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # see any crontab reference for the first argument
    # e.g. http://www.adminschoice.com/crontab-quick-reference
    # or   https://crontab.guru/ 
    mgr.register('0 7 * * *', 'MyPeriodicJob')
  end
end
```

Is this correct? If so, maybe you could update the wiki to reflect this?

**Comment by mikegee** [comment]
The last line implies your worker's `sidekiq_options` are typically factored in:

> Periodic job options will override any options set with `sidekiq_options` within the Worker class.

That can only work if the class is loaded, not referred to by string.

I suspect your app has a loading issue and that workers should be loaded when configuring the server.

**Comment by srpouyet** [comment]
Aha, that could very well be the issue. I'll look into it and close this issue for now. Thank you for the prompt response!
