### ISSUE TITLE
"Retry Count" doesn't increment with "Retry All" button

### ISSUE THREAD

**Issue by JacobEvelyn** [mperham/sidekiq#4063]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): 5.2.3 / 4.0.4

I have a Sidekiq job that's deterministically failing. After a few failures, I see it in the "Retries" tab of the Web UI and click "Retry All." The job retries and fails again, and goes back into the "Retries" tab, but this time the "Retry Count" is the same even though the "Next Retry" has gone up as I expect.

This may be intentional behavior but I didn't see any mention of it in the changelogs so I thought I'd flag it in case it's a bug.

**Comment by mperham** [comment]
Correct.  Manual retries don't increment so jobs don't "die" if you want to retry them yourself (like when testing a bugfix).
