### ISSUE TITLE
Native systemd log format

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4066]
* Investigate systemd logging best practices. Document them here.
* Create logger formatter which encapsulates those best practices.
* Automatically detect if Sidekiq is started by systemd and enable log formatter by default.

https://www.loggly.com/ultimate-guide/linux-logging-with-systemd/
https://blog.selectel.com/managing-logging-systemd/

> Instead of using the syslog() call to log directly to the system syslog service, a new-style daemon may choose to simply log to standard error via fprintf(), which is then forwarded to syslog by the init system. If log levels are necessary, these can be encoded by prefixing individual log lines with strings like "<4>" (for log level 4 "WARNING" in the syslog priority scheme), following a similar style as the Linux kernel's printk() level system. For details, see sd-daemon(3) and systemd.exec(5).

http://0pointer.de/public/systemd-man/sd-daemon.html

**Comment by Tensho** [comment]
### Resources

- [Introducing the Journal](https://docs.google.com/document/pub?id=1IC9yOXj7j6cdLLxWEBAGRL6wl97tFxgjLUEHIX3MSTs)
- [Logster and our error logging strategy at Discourse](https://samsaffron.com/archive/2018/12/27/logster-and-our-logging-strategy-at-discourse)

**Comment by Tensho** [comment]
Default `systemd` log entry has the next pattern:
```
<timestamp> <hostname> <unitname>[<pid>]: <message>
```
Sidekiq could omit own timestamp and PID in a systemd formatter.

**Comment by mperham** [comment]
Reading those links, it sounds like journald allows custom context parameters but it exposes a C API which requires a native gem to access[0].  We can definitely make that work but I'm not sure how many people actually want to use journald as opposed to something like papertrail or rsyslog.

[0]: https://github.com/theforeman/journald-logger

**Comment by Tensho** [comment]
Just to recap what I have learnt on the subject. Here are the next feasible ways to push a journal entry:

1. [`printk()`](https://en.wikipedia.org/wiki/Printk) call in **kernel**
2. [`syslog()`](http://man7.org/linux/man-pages/man3/syslog.3.html) call in **daemon process**
3. Write to `STDOUT`/`STDERR` of **daemon process**
4. [Native journal API](https://www.freedesktop.org/software/systemd/man/sd-journal.html) call in **daemon process**

Both [`Syslog::Logger`](http://ruby-doc.org/stdlib-2.6/libdoc/syslog/rdoc/Syslog/Logger.html) [2] and  daemon's `STDOUT` output [3] don't allow to handle a custom context, only the message itself. Therefore the only feasible way is a native journal API [4].

Regarding a potential dependency, as the initial author of [`journald-logger`](https://github.com/theforeman/journald-logger) (depends on [`journald-native`](https://github.com/theforeman/journald-native)) states – [`systemd-journal`](https://github.com/ledbettj/systemd-journal) doesn't support null-terminated strings. So the only choice is `journald-logger`/`journald-native`.

### Fun facts

- [Ruby core team promoted `logger` to a separate stdlib gem starting from `2.6`](https://rubyreferences.github.io/rubychanges/2.6.html#libraries-promoted-to-default-gems)

**Comment by mperham** [comment]
What do you think about making this journald integration a separate gem? I'd guess that 95% of Sidekiq users aren't going to use it, even if they use systemd, so it's probably not a good idea to have it in core.

**Comment by mperham** [comment]
And there's no point in building any of this if we don't do 4.  Sidekiq 5 can support 2 and 3 today.

**Comment by mperham** [comment]
I like having the systemd formatter because it helps to have several different loggers to prove our pluggable logger API but at the same time I don't want to maintain a bunch of plugins that 5% of Sidekiq users use.

**Comment by Tensho** [comment]
> What do you think about making this journald integration a separate gem?

> it helps to have several different loggers to prove our pluggable logger API 

I'll go along with you ^_^ Please could you suggest an example of the popular external sidekiq gem to grasp a naming convention, e.g. `sidekiq-super-ext`, `super-ext_sidekiq`?

**Comment by mperham** [comment]
I think this is a little too specific and not something we'll add to core.  People are welcome to publish their own env-specific loggers.
