### ISSUE TITLE
"Poisonous" jobs will retry forever

### ISSUE THREAD

**Issue by alecjacobs5401** [mperham/sidekiq#4069]
Ruby version: 2.4.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.1.3, Pro 4.0.2

Example Intializer:
```rb
Sidekiq.configure_server do |config|
  config.reliable!
  config.average_scheduled_poll_interval = 1

  config.server_middleware do |chain|
    chain.add SidekiqLogging::Server
  end

  config.client_middleware do |chain|
    chain.add SidekiqLogging::Client
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add SidekiqLogging::Client
  end
end
```

The Job Retry mechanism of Sidekiq keeps track of the retry count _after_ a job has failed instead of keeping track of an attempt count that is incremented when a job is picked up and started working. 

This means that "poisonous" jobs (i.e. jobs that consume too much memory while processing and crash nodes/kill processes abruptly) may never get its retry count incremented, causing them to potentially spin around in a whirlwind of destruction requiring someone to intervene and manually kill the offending job. 

Without the reliable scheduler, this could potentially be mitigated using client middleware, but with the reliable scheduler we do not have this luxury.

Is this a common issue/ something that should be addressed or is it an expected downfall to the reliable scheduler? 

Happy to discuss further, thanks!

**Comment by mperham** [comment]
There’s no alternative that is safe. The process can crash at any time. Let me know if you have suggestions.

**Comment by alecjacobs5401** [comment]
Yeah, I was afraid of that. 

The only suggestion/way about it that I could imagine is if the basic fetch / super fetch mechanisms tracked an attempt count.

For `SuperFetch`, it would require a `RPOPLPUSH` to claim the work, and them modifying the claimed job to track an attempt count. After it does that, it would have to replace the item in the super queue...which is kind of nasty but it _should_ be safe in theory.

This way, as soon as a worker claims a job it can increment the attempt count..which would prevent poisonous jobs from running rampant. It wouldn't save 100% of cases..but it would be something.

If this is something you're open to, I'd be happy to put together a PR

**Comment by mperham** [comment]
If you have unsafe/poison jobs, things you can do:

1. Debug and fix the underlying issue, duh. :-)
1. Split the work into smaller, more stable chunks using Batches
1. Put them on their own queue, which you can pause and unpause to monitor/manage manually
1. Spin up a custom Sidekiq process only for that queue, with more memory or resources

There's really no good, safe automated solution here that I'm aware of.
