### ISSUE TITLE
Bump Redis requirement

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4072]
We've required Redis 2.8+ for many years now.  Bump the requirement in Sidekiq 6.0 to Redis 4.0 so we can use newer Redis features and commands.

**Comment by mperham** [comment]
`brew upgrade redis` will upgrade developers on macOS.

**Comment by mike1o1** [comment]
I think this is a good move, but I just wanted to document that if anybody else is using Heroku Redis as their datastore for Sidekiq, it appears that they are still on version 3.2 of Redis.

https://devcenter.heroku.com/articles/heroku-redis#version-support-and-legacy-infrastructure

**Comment by mperham** [comment]
Thanks, that’s great info. We’ll bump to 3.2 then.

**Comment by mperham** [comment]
Heroku Redis has beta support for Redis 4.0 now. https://devcenter.heroku.com/changelog-items/1549

**Comment by mperham** [comment]
I'm going to stick with the requirement for Redis 4.0 as it has been out for 2 years now.  Heroku Redis users can upgrade to the beta or stick with Sidekiq 5.x until it goes GA.

**Comment by mperham** [comment]
@chacon Sidekiq Pro and Sidekiq Enterprise both use more advanced Redis functionality. No one is forcing you to use Sidekiq 6, Sidekiq 5 still works perfectly fine.

**Comment by chacon** [comment]
@mperham No worries, I appreciate the insight!
