### ISSUE TITLE
Support for ad-hoc job tags?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4073]
In #4071 we raised the idea of tags or labels for jobs.  Right now the only metadata we have about a job is the class and args, everything else is user-specific.

Just as processes can have labels displayed next to their entry in the Busy tab, it might be useful to show tags or labels on the different pages that show job listings. Of course we'd surface these things in the API also.

> NB: I don't want these features to power application logic.  Application code should not be iterating through queues or sorted sets to find labels / tags, this is for emergency repairs or Web UI usage only.

WDYT?

**Comment by gearnode** [comment]
@mperham How add tag on Worker? With`sidekiq_options`?

I think it can be a nice feature, do you accept pull request for this?

**Comment by mperham** [comment]
@gearnode This was an idea I had but it's not necessarily something which will happen.  I'd like to see a little more formal proposal around the idea: a couple of sample use cases or problems it could solve, how it would be implemented, any limitations, etc.  Perhaps the most important question is: what percentage of Sidekiq's users would use this feature?  Would this solve an actual need?

**Comment by JanStevens** [comment]
We definitely would want this feature. For example we would tag every job based on the Tenant that triggered it (we are using apartment gem with multi tenancy).

Right now we patched the logger to prefix the `schema` name it got scheduled for but we would like to see in the sidekiq UI easily the tenant. Right now we can only do this by viewing the job and arguments.

Also for logging purposes this would be handy, so we know that the server scheduled a job for a specific tenant and then which worker picked it up.

Other tags that might be useful is categorising jobs so you can easily see to which part of the application they belong. We right now use namespaces for it but it would be handy to tag jobs as being part of the `authorization` framework or something

**Comment by mperham** [comment]
@JanStevens FYI you can add random key/values to the job payload with client-side middleware and then view those key/values on the job details page in the Web UI, search for tenant-specific jobs with Pro's filtering, etc. All that's possible today.
