### ISSUE TITLE
Question on Sidekiq Leader and Periodic Jobs

### ISSUE THREAD

**Issue by goncalopereira** [mperham/sidekiq#4078]
Ruby version: 2.4.5
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.5 / Pro 4.0.4 / Ent 1.7.2

Hi,
I've separated my workers on multiple projects attached to the same cluster.

On one project the worker is a Slack Bot

On another project I have Cron Jobs running through Periodic

I've noticed that if I restart the Slack Bot workers might become Leader, which has no list of Periodic jobs so they simply disappear.
The Slack Bots do not use the 'cronjob' queue.

Is there a way to attach Periodic Jobs independent of the Leader,
prevent the Slack Bot workers becoming Leaders OR
another solution?

Right now the Periodic Jobs seem to be a SPOF attached to the unique Leader and cannot be a mix of different lists of Periodics on different projects.

Kind Regards

**Comment by goncalopereira** [comment]
Hi,
In my scenario, following your advice, I'd have apps that would need to queue Workers on different databases, is this possible?

**Comment by mperham** [comment]
See Sharding wiki page.
