### ISSUE TITLE
Monitoring Queue Latency

### ISSUE THREAD

**Issue by wyattEpp** [mperham/sidekiq#4079]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.1 / 4.0.2 / 1.7.1

I'm in the process of extending the monitoring and alerting for our Sidekiq implementation. For context, we use a multi-queue approach, segmented by priority. Per-queue latency, which I'd regard as one of the most important metrics, is conspicuously absent from statsd. I'd like to know if I'm I just overlooking it, if I've misconfigured something, or if it's intentionally excluded.

If it is intentionally excluded, do you have any recommendations on an easy way to expose this information (outside of scraping JSON from endpoints described by https://github.com/mperham/sidekiq/wiki/Monitoring#monitoring-queue-latency)? Ideally, I'd like to keep all metrics in statsd, but if I must push these to statsd myself, I'd have to incorporate a separate scheduler to keep monitoring independent of the observed system.

Initializer:
```
require 'sidekiq/middleware/server/statsd'

# setup historical metrics
# sidekiq uses a single instance to send metrics from the leader
# these appear in statsd as 'jarvis.sidekiq'
statsd = Statsd.new('127.0.0.1', 8125).tap { |me| me.namespace = 'jarvis' }
Sidekiq.save_history(statsd, 30)

# setup real time queue metrics
# each thread calls this block after prcessing a job to send metrics
# these appear in statsd as 'jarvis.jobs'
Sidekiq::Pro.statsd = -> {
  Statsd.new('127.0.0.1', 8125).tap { |me| me.namespace = 'jarvis' }
}

Sidekiq.server_middleware.add Sidekiq::Middleware::Server::Statsd

Sidekiq.configure_server do |config|
  config.redis = {
    url: Rails.application.secrets.redis_queue_url,
    ssl: !(Rails.env.test? || Rails.env.development?)
  }

  config.periodic do |mgr|
    mgr.register('*/5 * * * *', ExportIncrementalReportsWorker) # Incremental exports every 5 minutes.
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: Rails.application.secrets.redis_queue_url,
    ssl: !(Rails.env.test? || Rails.env.development?)
  }
end

Sidekiq.logger = Rails.logger

# See https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs for details on the "unique jobs" feature.
Sidekiq::Enterprise.unique! unless Rails.env.test?
```

**Comment by mperham** [comment]
4769187c3da5e5d523d916b7374c7cd8d02d2387

**Comment by wyattEpp** [comment]
Makes sense. I had a hunch it might be due to cost - I was hoping there might be a way to enable it with a configurable interval.

**Comment by mperham** [comment]
You can do this today, modify queue names as appropriate:

```ruby
Sidekiq.configure_server do |config|
  config.save_history(statsd, 30) do |s|
    s.batch do
      %w(default critical).each do |qname|
        q = Sidekiq::Queue.new(qname)
        s.gauge("sidekiq.latency.#{q.name}", q.latency)
      end
    end
  end
end
```

**Comment by wyattEpp** [comment]
Fantastic, thanks for adding to the Wiki.

**Comment by ryanwi** [comment]
@mperham @wyattEpp can the latency gauge be sent with Pro, or only Enterprise? I know save_history is only on Ent, but is there another hook to wire it up?

**Comment by mperham** [comment]
@ryanwi There's no recurring hooks in Pro, you'd need to implement it yourself. Ent has the infrastructure necessary to perform recurring tasks on a cluster leader process. If you have 100 Sidekiq processes, you don't want to be submitting 100 latency checks...

**Comment by mijoharas** [comment]
hey, sorry for posting on an old thread. I'm just looking over the `statsd` middleware for sidekiq pro (`sidekiq-pro-5.0.0/lib/sidekiq/middleware/server/statsd.rb:32:21`) I'll obviously not post the code here as it's pro, but since you have the `msg` ready in the `call` can't you submit a `timing` value with `Time.now.to_f - msg['enqueued_at']` which will give the queue latency? Then we don't need to do a redis latency check, we'd just be submitting another latency metric (as we've already popped it off).

Can we add this to the middleware?

Let me know if there's something I'm missing here.

**Comment by adamniedzielski** [comment]
@mijoharas that's pretty much what I was doing at my previous company - https://github.com/liefery-it-legacy/loggery-gem/blob/master/lib/loggery/metadata/middleware/sidekiq.rb#L46-L55

We were then using Logstash to parse the logs and they eventually ended up in Kibana. That gives you what I call "execution delay". I'm not sure how it corresponds to the definition of queue latency that Sidekiq uses. I never figured it out :sweat_smile: The advantage is that you have the values in a more fine-grained way and can still aggregate them by queue name if you want. Or by any other dimension :slightly_smiling_face:
