### ISSUE TITLE
Any way to dynamically adjust concurrency?

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#408]
Some of my jobs are more intensive than others -- and I don't know in advance how they will pan out. I'd like to find a way to keep system load between 0.9 and 1.1, for example, by adjusting concurrency on the fly. Is this crazy -- should I do it another way?

One idea: is it possible to send concurrency-adjusting signals to Sidekiq from Monit? That would do the trick.

**Comment by bgvo** [comment]
Anyone came up with a solution for this?
