### ISSUE TITLE
Cannot access the monitoring UI when HTTP_X_FORWARDED_HOST is not present

### ISSUE THREAD

**Issue by mmustala** [mperham/sidekiq#4080]
Ruby version: ruby-2.4.2
Sidekiq / Pro / Enterprise version(s): normal 5.2.5

In order to improve my app security, I remove the HTTP_X_FORWARDED_HOST from the headers with a middleware

    class StripXForwardedHost
      def initialize(app)
        @app = app
      end

      def call(env)
        env.delete('HTTP_X_FORWARDED_HOST')
        default_url_options = Rails.application.config.action_controller.default_url_options
        env['HTTP_HOST'] = (default_url_options && default_url_options[:host]) || env['HTTP_HOST']
        @app.call(env)
      end
    end
    config.middleware.use StripXForwardedHost

However, doing this makes the Sidekiq monitoring UI inaccessible. When trying to access it I get "route not found" error. I tested that if I comment out the line where the HTTP_X_FORWARDED_HOST is deleted, Sidekiq monitoring UI is accessible again.

I mount it with

    authenticate :user, lambda { |u| u.super_admin? } do
      mount Sidekiq::Web, at: '/sidekiq'
    end

Is there any workaround?

**Comment by mmustala** [comment]
https://github.com/rails/rails/issues/29893 recommends deleting the header to mitigate the host header attack.

**Comment by mperham** [comment]
That’s a Rack/Rails question; Sidekiq doesn’t use that header in any way AFAIK.

**Comment by mmustala** [comment]
Thanks. I hoped it would be something in Sidekiq. Would have been much easier to solve. I'll add a comment to that Rails issue I already linked.
