### ISSUE TITLE
Pluggable loggers in 6.0

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4081]
Right now in 6.0, we have hard-coded log formats.  I'd like to get to pluggable log formatters.  Here's one example API, I'm open to other conventions:

```ruby
require 'acme_corp/plain_log_formatter'
Sidekiq.log_format = AcmeCorp::PlainLogFormatter
```

**Comment by Tensho** [comment]
Good idea 👍 I'd suggest to stick with Rails style – formatter instance:
```
config.log_formatter = AcmeCorp:: PlainFormatter.new
```

---

P.S. Sorry, I have not managed to recover from flu yet. Will work on this the next week.
