### ISSUE TITLE
Make Sidekiq OOM Signal Configurable 

### ISSUE THREAD

**Issue by mstruve** [mperham/sidekiq#4084]
Ruby version: 2.5.3p105
Sidekiq Enterprise version(s): 1.7.1

When the memory for a process exceeds the amount set by the ENV variable `SIDEKIQ_MAXMEM_MB`, Sidekiq will issue a USR2 signal to tell the process to gracefully shutdown. Sidekiq then waits for the current job to finish before it shuts down the process. In our situation, the currently running job however, will continue to use up more memory, to the point where it is above the threshold for systemd. At this point, systemd will issue a SIGKILL to the process to shut it down. **The problem is, when the process shuts down, the job that was causing the OOM will get put back in the queue only to be picked up by another worker and the cycle starts again.** 

To deal with this problem we decided to handle the Sidekiq OOM signal by doing something like this:
```ruby
class Sidekiq::Processor
  module OutOfMemoryProcessKiller
    def process(work)
      Signal.trap('USR2') do
        @thread.raise StandardError.new('OOM issued by Sidekiq')
        ::Process.kill('TERM', ::Process.pid)
      end

      super(work)
    end
  end

  prepend OutOfMemoryProcessKiller
end
```
We then handle that OOM error by moving the offending job to the DeadSet to ensure it cannot cause another OOM error. 

This was a great plan until we discovered that USR2 is also used during deploys for a graceful shutdown to ensure long running jobs are not interrupted. During a deploy, we obviously do not want to be trapping these signals and issuing TERM signals instead.

If we could separate the two signals by making the OOM signal different than a USR2 then we could ensure that we handle an OOM appropriately. I thought an easy way to do this would be to make it configurable with an ENV variable, `OUT_OF_MEMORY_SIGNAL` or something along those lines. 

That is a lot of information, please let me know if I need to clarify anything!

**Comment by mperham** [comment]
I'm missing something.  If you know the job type causing the problem, why not fix the bug that is causing excessive memory usage?

> We then handle that OOM error by moving the offending job to the DeadSet to ensure it cannot cause another OOM error.

I don't understand how you can do this, many jobs are running concurrently, no?

What signal do you want to use?  TERM is also used normally to shutdown Sidekiq so it's probably not a good pick either.

**Comment by mstruve** [comment]
Sometimes we get unexpected OOMs from jobs due to bad data or due to a bug someone introduced unexpectedly. That is what  this would  be for, the unexpected times when an OOM occurs. By putting the job aside we can then take our time figuring out what went wrong while Sidekiq processing continus.  

What prompted this inquiry was last week when we had some bad data go through our workers that caused a single job which normally uses less than a 1MB of data to use over a gig. It happened over night causing a ton of restarts and we ended up with a mess in the morning.

The signal I was thinking of using would be USR1. Honestly, it could be any signal that's not used as a Sidekiq life cycle signal.

**Comment by mperham** [comment]
Can't use USR1, that's the legacy quiet signal.  If we extract the signal to a method so you can monkeypatch it, would that be ok? Keep in mind that I think Einhorn might require USR2 also so I'm still not positive how this would work fully...

**Comment by mstruve** [comment]
What I was thinking to avoid backwards compatibility issues with older versions and to avoid monkey patching was a configurable signal. 
```ruby
signal = env['SIDEKIQ_OOM_SIGNAL'] || 'USR2' 
Process.kill(signal, Process.pid)
```

If you are not a fan of that idea, totally fine. Extracting it into a method to monkey patch I can definitely work with!

**Comment by mperham** [comment]
Monkeypatch is ok.  I don't want to document this as a config option.  No one else is asking for this so I can't justify it.

**Comment by mperham** [comment]
Ok, your monkeypatch is in master now.  I'll drop a new release sometime this month.

**Comment by mstruve** [comment]
Thank you!!!!

**Comment by mstruve** [comment]
Any chance a release with that method is coming soon for Enterprise?!

**Comment by mperham** [comment]
@mstruve Thanks for your patience, I was coordinating the 6.0 work, a Pro release and this too.  Good news: it's now available.
