### ISSUE TITLE
Redis version exception

### ISSUE THREAD

**Issue by TeTiRoss** [mperham/sidekiq#4085]
Rails `5.2.2`
Ruby: `2.5.1`
Sidekiq: `5.2.2`

Starting from sidekiq version `5.2.2` I'm receiving error when running `bundle exec sidekiq`:

```
You are using Redis v2.6.16, Sidekiq requires Redis v2.8.0 or greater
/Users/tetiross/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.2.2/lib/sidekiq/cli.rb:81:in `run'
/Users/tetiross/.rvm/gems/ruby-2.5.1/gems/sidekiq-5.2.2/bin/sidekiq:12:in `<top (required)>'
./bin/sidekiq:29:in `load'
./bin/sidekiq:29:in `<main>'
```

`redis-server --version` returns following:
```
Redis server v=5.0.3 sha=00000000:0 malloc=libc bits=64 build=457be8ba4fa3e51f
```

Sidekiq versions prior to `5.2.2` works fine.

**Comment by zdk** [comment]
I got the same error as well.

Ruby version: `2.5.3`
Sidekiq version: `5.2.5`
Redis version: `5.0.3`

```
sidekiq_1        | 2019-01-31T05:15:18.501Z 17 TID-gsgq5tt5d INFO: Booting Sidekiq 5.2.5 with redis options {:url=>"redis://redis:6379", :id=>"Sidekiq-server-PID-17"}
sidekiq_1        | 2019-01-31T05:15:20.326Z 17 TID-gsgq5tt5d INFO: Running in ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
sidekiq_1        | 2019-01-31T05:15:20.327Z 17 TID-gsgq5tt5d INFO: See LICENSE and the LGPL-3.0 for licensing details.
sidekiq_1        | 2019-01-31T05:15:20.327Z 17 TID-gsgq5tt5d INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
sidekiq_1        | You are using Redis v2.6.16, Sidekiq requires Redis v2.8.0 or greater
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:74:in `run'
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/gems/sidekiq-5.2.5/bin/sidekiq:12:in `<top (required)>'
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/bin/sidekiq:23:in `load'
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/bin/sidekiq:23:in `<main>'
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
sidekiq_1        | /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by mperham** [comment]
The error message is very clear.  You are connecting to a different version of Redis than you think.

**Comment by zdk** [comment]
Should it be stated in Changelog https://github.com/mperham/sidekiq/blob/master/Changes.md#522 that gem version update from requires Redis v2.8.0 or greater?

**Comment by mperham** [comment]
Sidekiq has required 2.8+ for years. 5.2.2 didn’t change anything.

**Comment by zdk** [comment]
Ok, interesting. Then why Sidekiq versions prior to `5.2.2` was working with `Redis v2.6.16` as stated in the issue?

**Comment by TeTiRoss** [comment]
Yes, I did not change anything regarding Redis, just gem version of Sidekiq and that problem occurred. Which is why I downgraded to be able to use Sidekiq.

**Comment by mperham** [comment]
What was your previous Sidekiq version?

**Comment by TeTiRoss** [comment]
`5.2.1` - version that is working ok. 
`5.2.2` - version with the error above. And all the versions up.

**Comment by mperham** [comment]
@TeTiRoss There was no changes in 5.2.2 which would cause this behavior.  I believe you are mistaken and something changed in your local environment also during the upgrade.

See for yourself with this repo: `git diff v5.2.1...v5.2.2`

**Comment by rcaught** [comment]
@TeTiRoss I had this same problem due to running https://github.com/guilleiguaran/fakeredis in my dev/test bundler group FYI.

**Comment by TeTiRoss** [comment]
@rcaught yes, I do use `fakeredis`, and when I disabled it for dev env - there is no such error with Sidekiq anymore. Thanks.

**Comment by ammar** [comment]
Sorry for jostling a closed issue, but this bit us earlier. We misinterpreted the error message, and thought it referred to the redis gem version.

I think the error message could be made a little clearer by replacing `"You are using Redis v#{ver} ..."` with `"You are connecting to Redis v#{ver} ..."`.

**Comment by mperham** [comment]
@ammar Seems like a good idea, send me a PR.

**Comment by ammar** [comment]
Submitted #4340 . Thanks

**Comment by chrisjones120** [comment]
You can configure sidekiq to not use fakeredis without having to disable the gem by adding the following to your `config/environments/development.rb` file.
```
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { driver: Redis::Connection::Ruby }
end

Sidekiq.configure_server do |config|
  config.redis = { driver: Redis::Connection::Ruby }
end
```

**Comment by birthdaycorp** [comment]
> The error message is very clear. You are connecting to a different version of Redis than you think.

Sorry for bringing this up again, but I too just got bit by this, and I'm a little bit confused about how to go about telling Sidekiq to use the correct version of Redis. Like everyone else, I thought it was a gem dependency, but realized I probably just needed to run `brew upgrade redis`. 

My Redis is now `Redis server v=5.0.7 sha=00000000:0 malloc=libc bits=64 build=af5f21930527c0ac`, but Sidekiq is still requesting the old version. How do I tell it to use the new one?
