### ISSUE TITLE
Sidekiq can't find ActiveRecord objects 

### ISSUE THREAD

**Issue by asmatameem** [mperham/sidekiq#4088]
Ruby version: 2.4.2
Sidekiq Enterprise version(s): 

```
  * apartment-sidekiq (1.1.0)
  * rspec-sidekiq (3.0.3)
  * sidekiq (4.1.2)
  * sidekiq-ent (1.3.2)
  * sidekiq-pro (3.3.3)
```

Sidekiq is unable to find the activerecord object. The worker's ` perform ` method takes just the object's uuid and does a ` .find_by(uuid: uuid) ` on it, and fails to find the object. (This model is not tenanted)

Note that the object is created well in advance and Sidekiq worker is triggered through a different endpoint which gets called much later after the create. (can be after a few hours, days/weeks) and even then sidekiq worker cannot find it. However, we are able to see the object on the rails console so we know it's persisted in the database. 

We also ruled out the possibility of it reading from a slave database, as this job is critical and reads from master only.

**Comment by mperham** [comment]
Your versions are several years old, have you considered upgrading?
