### ISSUE TITLE
kill sidekiq at heroku

### ISSUE THREAD

**Issue by louman** [mperham/sidekiq#409]
im running sidekiq@rails3 on heroku. I have a crawler that runs in background and take a few hours to complete.

While im still testing it on heroku, i would like to kill it and start again but i am unable to do it.

I tried clearing worker list at sidekiq interface, scaling down workers to zero but whenever i scale it again to 1, the same job starts over.

Is there a way to kill it for good?

**Comment by yu-coder** [comment]
Hi, @bobbytables.
I ran Sidekiq.redis {|r| r.flushall } but it seems workers were killed but they have started again without running command.
