### ISSUE TITLE
fix documentation regarding serialization

### ISSUE THREAD

**Issue by jjb** [mperham/sidekiq#4094]
On this page:

https://github.com/mperham/sidekiq/wiki/Best-Practices

"What you are doing here is serializing the entire Quote object to Redis" suggests that this approach will work but is not recommended. However, some experimentation suggests that sidekiq actually doesn't support this at all (which is fine and probably a good idea, I'm just wondering if the docs should be updated).

When I did a test sending a User object to a job, I got 

```
Couldn't find User with 'id'=#<User:0x0000000006e57288> 
```

**Comment by mperham** [comment]
Thanks, updated.
