### ISSUE TITLE
Cannot open Sidekiq morgue in mounted admin app because of job with invalid arguments

### ISSUE THREAD

**Issue by Mange** [mperham/sidekiq#4095]
Trying to open the morgue gives a 500 Internal Server Error. Underlying error is:

```
NoMethodError: undefined method `map' for "(...)":String
Did you mean?  tap
  from sidekiq/web/helpers.rb:210:in `display_args'
  from (eval):49:in `block in _erb_morgue'
  from (eval):34:in `each'
  from (eval):34:in `_erb_morgue'
  from sidekiq/web/action.rb:85:in `_erb'
  from sidekiq/web/action.rb:54:in `erb'
  from sidekiq/web/application.rb:111:in `block in <class:WebApplication>'
  from sidekiq/web/application.rb:287:in `instance_exec'
  from sidekiq/web/application.rb:287:in `block in call'
  from sidekiq/web/application.rb:283:in `catch'
  from sidekiq/web/application.rb:283:in `call'
```

Sidekiq 5.2.3

From reading the code at the point of failure, it looks like the arguments are a string instead of an array.

---

We don't think we've scheduled any jobs except through the official API, but until we can inspect the message we can't tell what it is.

Best-case would be some defensive fallback for the argument rendering so it's kept around, allowing us to investigate it.

I'd also be happy to just have a way to get rid of the offending message so I can get back the morgue.

Thank you for your time!

---

_Extracted from https://github.com/mperham/sidekiq/issues/3389#issuecomment-460538773_

**Comment by mperham** [comment]
Issue should be fixed, you are welcome to pull master and verify for your case.
