### ISSUE TITLE
Dropdown CSS removed

### ISSUE THREAD

**Issue by urkle** [mperham/sidekiq#4099]
Ruby version: 2.4.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.5

Issue:
When upgrading from Sidekiq 5.1.3 to 5.2.5 CSS for some custom extensions to the web UI broke due to the removal of the dropdown CSS.  This was (i believe) accidentally removed from work in issue #3914.  As only the CSS ws removed.. the JS code for the dropdown plugin remains in application.js.  

Can we add back in the dropdown CSS (and the .caret class)?

**Comment by mperham** [comment]
Oops! Can you submit a PR, happy to merge a fix.

**Comment by urkle** [comment]
@mperham added PR #4103
