### ISSUE TITLE
Sidekiq does not give any time for workers to handle the Sidekiq::Shutdown exception

### ISSUE THREAD

**Issue by jarthod** [mperham/sidekiq#4101]
Ruby version: 2.5.3
Sidekiq: 5.0.3 (open source)

You can find our initializer below but it's not very relevant to this matter.
I've checked the changelog and didn't find any change about this, neither in the code.

Here is the issue we noticed, we have jobs in production which are long (10s+) but can be killed with an exception (like `Sidekiq::Shutdown`), these workers take a lock and release it in an `ensure` block (so when they exit or on exception). We noticed that when restarting the sidekiq workers, some on these jobs would get killed as expected after the 8 sec grace period, but the lock would still be present in some case, because the ensure block wasn't event called (or not entirely). After looking at the code the explanation was pretty logical to me: Sidekiq doesn't wait after the `hard_shutdown` method so the exception is raise and just after that the process exists which kills the worker threads. If they are luck to get enough time before the context switch they sometime manages to execute the rescue/ensure blocks, and if they are not, well :fire:.

We can't wait for them to finish of course as we can't control that (especially if the Shutdown exception was caught and ignored), but I think it should at least wait for a small duration like the `PAUSE_TIME` used at the beginning of the `Manager#stop`. I've made this little patch on my side (just adding PAUSE_TIME after the `hard_shutdown`) which we are using in production and it seem to be more than enough for our workers to handle the exception and unlock/exists cleanly.

```ruby
    def stop(deadline)
      quiet
      fire_event(:shutdown, true)

      # some of the shutdown events can be async,
      # we don't have any way to know when they're done but
      # give them a little time to take effect
      sleep PAUSE_TIME
      return if @workers.empty?

      logger.info { "Pausing to allow workers to finish..." }
      remaining = deadline - Time.now
      while remaining > PAUSE_TIME
        return if @workers.empty?
        sleep PAUSE_TIME
        remaining = deadline - Time.now
      end
      return if @workers.empty?

      hard_shutdown

      # Original method ends here, this is the addition:
      logger.info { "Giving a bit more time to allow exception handling..." }
      sleep PAUSE_TIME
    end
```

This may not be the best way to handle the problem but it sounds reasonable, it only adds 0.5 sec when there's a hard shutdown (so we waited 8.5 sec already). There's no point in sending an exception to handle rolling back db transactions (or unlocking ressource in our case) if we don't actually let the exception handlers run. I guess in most case if the exception handling path is simple and fast or you're lucky it can get processed before any context switch but in our case it was failing like half of the time.

Please let me know what you think or you have a better suggestion!

Initializer:
```ruby
require 'sidekiq/logstash_middleware'
require 'sidekiq/qos_fetch'

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add LogstashMiddleware
  end

  config.average_scheduled_poll_interval = 1
  config.options[:fetch] = Sidekiq::QosFetch
end

SidekiqUniqueJobs.config.unique_args_enabled = true
Sidekiq::Logging.logger = Rails.logger
```

**Comment by mperham** [comment]
There's no good solution here. A thread can take an arbitrary amount of time to shut down, especially if that ensure block does something which goes over a network.  The Sidekiq process itself can crash and leave those locks lingering.  Distributed locks, in general, are a bad idea.

Use `-t 25` to increase your hard timeout.

**Comment by jarthod** [comment]
Yes of course, but the problem is not the time it take to unlock here, the code doesn't even reach this line in most case because it really has 0ms to execute. So in the current state the whole exception sending is useless as it can't work, it's not better than removing all this code and killing the threads. If you put this system in place I guess it was to help with this kind of issue (like DB transaction as in your example) but here it's not helping (unless you're lucky). Don't you think we should either remove this and advertise the expected behavior or make it work as the implementation suggests?

Increasing the timeout wouldn't help in our case, these workers can take hours. Also we'll upgrade at some point of course but I don't see any change which would help here. I sounds to me like this is the standard way to do it for any process management system by the way, systemd, supervisorctl, etc... they all send a term signal and then wait a bit for cleanup before killing the process. Here sidekiq is doing like sending a shutdown signal (the exception) and instantly after killing the thread :/

Anyway If you're confident the current behavior is best I won't spam you :)
We'll just run our fork then and people with the same issue may find this ticket and give more feedback / ideas.

**Comment by mperham** [comment]
As I said, there is no right timeout except "wait until every thread is done".  This is already implemented in Sidekiq Enterprise's support for long-running jobs and rolling restarts. Rolling restarts are documented here: https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts

**Comment by mperham** [comment]
If Sidekiq waits 0.5sec, someone will post an issue that their ensure block took 0.6sec. :-/

**Comment by jarthod** [comment]
Haha well fair enough if it's in entreprise then ;)
We'll keep our fix then.
