### ISSUE TITLE
Two wiki pages give conflicting information

### ISSUE THREAD

**Issue by PhilCoggins** [mperham/sidekiq#4102]
My issue is related to some conflicting information that I read between two wiki pages regarding the hard limit that Heroku put on a process before it is shut down (e.g. during a deploy).

https://github.com/mperham/sidekiq/wiki/FAQ#what-happens-to-long-running-jobs-when-sidekiq-restarts

> By default, Sidekiq gives workers 8 seconds to shut down. This is carefully chosen because Heroku gives a process 10 seconds to shutdown before killing it.

https://github.com/mperham/sidekiq/wiki/Deployment#heroku
> Keep in mind that Heroku puts a hard limit of 30 seconds on a process restart, the -t 25 tells Sidekiq to give the jobs 25 seconds to finish before starting the "force shutdown" procedure.

I'm trying to better understand what I should set my timeout to in Heroku and am hoping to get a clear answer, hopefully cited directly from a Heroku document / person if at all possible.

Thanks for all the great work on Sidekiq!

**Comment by mperham** [comment]
The FAQ is old and needs to be updated , use `-t 25`. This will be the default in Sidekiq 6.0.

**Comment by mikegee** [comment]
I updated https://github.com/mperham/sidekiq/wiki/FAQ.
