### ISSUE TITLE
Testing the sidekiq_retry_in for workers

### ISSUE THREAD

**Issue by maxrosecollins** [mperham/sidekiq#4104]
I checked the docs but couldn't see it.
How am I able to test the `sidekiq_retry_in` with rspec?

Thanks!

**Comment by mperham** [comment]
Extract the block to a constant, test the constant.

```ruby
RETRY_IN = proc {|count, exception| count * 10 }
sidekiq_retry_in(&RETRY_IN)


RETRY_IN.call(2, nil).should eq(20)
```

**Comment by maxrosecollins** [comment]
I get a `NoMethodError Exception: undefined method `sidekiq_retry_in'` when I try to do this

**Comment by mperham** [comment]
It's psuedo-code I wrote in 30 seconds to show the idea, not meant to be run as is.

**Comment by maxrosecollins** [comment]
Ha okay 👍
