### ISSUE TITLE
Ability to isolate threads for `.fake!` data

### ISSUE THREAD

**Issue by inossidabile** [mperham/sidekiq#4107]
I'm looking for a way to properly isolate multithreaded testing which is getting damaged by using single storage when `fake!` is used. It could be achieved with moving `Queues` hashes to `Thread.current` when certain flag is activated (Something like `Sidekiq::Testing.threadsafe!`).

If that's something that would be accepted to the repo, I would be happy to prepare a PR.

**Comment by mperham** [comment]
Yep, multithreaded testing is not supported by the testing API.  You can disable testing and use Sidekiq in live mode or fork a child for each test.

**Comment by inossidabile** [comment]
@mperham do you think implementing it in aforementioned way could work and would be useful to people?

**Comment by mperham** [comment]
It might be useful to you but I doubt many will find it useful, especially in light of the complexity it adds.
