### ISSUE TITLE
Hooks to rack-protection or the request cycle?

### ISSUE THREAD

**Issue by why-el** [mperham/sidekiq#4108]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.9 (free-tier)

> Please include your initializer and any error message with the full backtrace.

Not applicable. 

> Are you using an old version?

Yes, but newer versions do not have the capability judging by changes. 

## Problem

For reasons I can't delve into, we need to load an entire rails application in an iframe. This is trivial in Rails (with the usual caveats and guards against malicious origins), but since Sidekiq runs under its own Rack hierarchy (?), we need a mechanism to disable certain protections, such as `X-Frame-Options`. 

The `build_sessions` method in `web.rb` can be rewritten to do:

```
middlewares.unshift [[::Rack::Protection, { use: :authenticity_token, except: frame_options }], nil]
```

but I'd prefer if there is a cleaner way? Even though we do not use rack-protection in the main Rails application, but even if we did, any settings there would not cascade to Sidekiq, naturally.

**Comment by mperham** [comment]
A PR would be welcome if you want to prototype something.

**Comment by mperham** [comment]
No plans to implement but PRs are welcome.

**Comment by why-el** [comment]
@mperham thanks. I went with a simple override for lack of time. Thanks for the promptness as always. 👍 If/when some time opens up, I'll be glad to patch it.
