### ISSUE TITLE
Request/Idea: Batch Status Join Timeout

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#4109]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): Latest

```
status = Sidekiq::Batch::Status.new(batch.bid)
status.join
```

Would it be possible to add a timeout param to `join`? 

So if the batch does not complete within that time, it raises an exception.

Unsure of how this is working under the hood, so perhaps it's not possible.

**Comment by mperham** [comment]
It’s meant to duplicate Thread#join but it’s totally possible. The default could be wait forever, as today.

**Comment by scottrobertson** [comment]
Although, now i see it's actually just doing a `while true` and `sleep 1` internally. This is what we are doing, so i would not worry about implementing this (unless you think it will benefit others).
