### ISSUE TITLE
Possible loading issue with cancancan and active record.

### ISSUE THREAD

**Issue by raivil** [mperham/sidekiq#4110]
Ruby version: `2.5.3p105 (2018-10-18 revision 65156)`
Sidekiq / Pro / Enterprise version(s):
```
Sidekiq 5.2.5
Sidekiq Pro 4.0.5 
Sidekiq Enterprise 1.8.0
```

Hey Mike,

I'm having issues with cancancan ("~> 2.2") and sidekiq (5.2.5).

Cancancan create some methods on ActiveRecord models such as `model.accessible_by(ability)`.
This method can be used to retrieve records that are related to a specific user or any other rule.

Cancancan will load AR adapters it on https://github.com/CanCanCommunity/cancancan/blame/feature/2.2.0/lib/cancan.rb#L12

While running rails (latest  5.2.2), puma or console, I'm able to use `accessible_by`. 
However, if this method is in a job, it will fail with `NoMethodError: undefined method `accesible_by' for #<Class:0x00007fde4f671828>`

Same issue happens on staging/production.

I've created a simple app to test the issue. Readme file has examples.
It's available on https://github.com/raivil/sidekiq_cancancan_loading.

Can you give some help on this?

**Comment by mperham** [comment]
The method is spelled `accessible_by`.

**Comment by raivil** [comment]
@mperham sorry about the misspell. 
I've updated the description with the correct error.

What is happening is that the cancancan adapters doesn't seem to be loading on sidekiq.
