### ISSUE TITLE
Polish codebase with standardrb

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4113]
There's a few nice fixes (e.g. double quotes everywhere) but a few rules that I explicitly don't want (e.g. Sidekiq uses hashrockets in the Client API because I don't want people using symbols in the job payload, it's not valid JSON).

Pull in standardrb and accept its changes unless it looks obviously wrong or there is a good reason not to conform.

https://github.com/testdouble/standard

**Comment by mperham** [comment]
We also need to think about how to get this running automatically so the codebase does not regress with future contributions.

**Comment by gearnode** [comment]
@mperham What's about add rule in the CI to enforce the style?

**Comment by mperham** [comment]
@gearnode Sure, that's one good idea.
