### ISSUE TITLE
 Daemonization mode will be removed in Sidekiq Error

### ISSUE THREAD

**Issue by vilusa** [mperham/sidekiq#4118]
Hi everyone,
I am using `sidekiq 5.2.5` version

> Error: WARNING: Daemonization mode will be removed in Sidekiq 6.0, see #4045. Please use a proper process supervisor to start and manage your services
WARNING: PID file creation will be removed in Sidekiq 6.0, see #4045. Please use a proper process supervisor to start and manage your services

![screen shot 2019-03-04 at 5 10 08 pm](https://user-images.githubusercontent.com/8127141/53738614-be4e4200-3ea0-11e9-8134-a273a47fa850.png)

This errors puts console, Is there any solution or resource for this problem ?
#4045 I looked at this source, but I didn't see any solution.

**Comment by mperham** [comment]
The solution is "Please use a proper process supervisor to start and manage your services"

**Comment by vilusa** [comment]
@mperham  Project sidekiq works with 6 different workers as background jobs unfortunately I could not find a source for how to organize this rake

**Comment by mperham** [comment]
There are examples of systemd and upstart integration in the [examples](https://github.com/mperham/sidekiq/tree/master/examples) directory. I recommend everyone learn systemd as it is the current best tool to run Sidekiq.

**Comment by chongfai13** [comment]
> There are examples of systemd and upstart integration in the [examples](https://github.com/mperham/sidekiq/tree/master/examples) directory. I recommend everyone learn systemd as it is the current best tool to run Sidekiq.

Can you advise the method or type here the cmd to start sidekiq?

I am using bundle exec sidekiq -d -C config/sidekiq.yml but failed.
