### ISSUE TITLE
Move off Travis CI

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4120]
Travis has been acquired by private equity vultures, move our CI build before they kill off their OSS tier and leave us stranded.  CircleCI?  Another? Recommendations?

**Comment by dodeja** [comment]
We use SeamaphoreCI and are happy users. https://semaphoreci.com/product. Also heard good things  but requires more hand-holding.

**Comment by renchap** [comment]
Good experience with CircleCI here, very customisable and nice OSS offering. Fasterthan Travis too.

**Comment by czj** [comment]
Been using Semaphore CI 1.0 for 18 months, Ruby support was lagging recently. Their 2.0 is very immature at the moment but promising.

Switch to Circle CI 2.0 about 4 months ago and been extremely happy with it. Needs a lot more configuration than Travis CI though, but using Docker images as base is very handy.

**Comment by joshuap** [comment]
Been happy w/ CircleCI at Honeybadger. I'm planning to move our OSS libs there.

**Comment by Tensho** [comment]
CircleCI 👍

**Comment by petergoldstein** [comment]
Another vote for CircleCI.

**Comment by joshpuetz** [comment]
Putting in my plug for CodeShip (disclaimer: I work for CodeShip 😉 )

**Comment by HoneyryderChuck** [comment]
Move to gitlab, it has CI integration. You kill 2 corporate acquisitions with one stone :)

**Comment by dzunk** [comment]
Very happy with CircleCI, +1

**Comment by seuros** [comment]
I moved everything to CircleCi and never looked back.

**Comment by gearnode** [comment]
What's about [Github Actions](https://github.com/features/actions)?

**Comment by armilam** [comment]
I've had a good experience with [CodeShip](https://blog.codeship.com/codeship-launches-free-tier-docker-ci-product-codeship-pro/) (I _don't_ work for them).

**Comment by mperham** [comment]
Does anyone have a good .circleci/config.yml sample which runs their test suite against multiple 2.x Rubies?

**Comment by mperham** [comment]
Airbrake seems to have a good, complex one here:

https://github.com/airbrake/airbrake-ruby/blob/dedc37519a519a72aaa7bec9986ac223ee630c8c/.circleci/config.yml

**Comment by mperham** [comment]
Sidekiq is now live on CircleCI!

https://circleci.com/gh/mperham/sidekiq

**Comment by n-rodriguez** [comment]
> move our CI build before they kill off their OSS tier and leave us stranded. CircleCI? Another? Recommendations?

Just a question : why leave Travis since it says it will always be free for OSS? (https://travis-ci.com/)

> Testing your open source projects will always be free!
> Seriously. Always.

Thank you!

**Comment by mperham** [comment]
Travis CI sold to a holding company, proclaiming their shared vision for Travis.

https://blog.travis-ci.com/2019-01-23-travis-ci-joins-idera-inc

A month later they laid off about half the staff.  Actions speak louder than words -- they are private equity vultures.  Not a company I want to implicitly endorse by using their product.

**Comment by n-rodriguez** [comment]
> A month later they laid off about half the staff. Actions speak louder than words -- they are private equity vultures. Not a company I want to implicitly endorse by using their product.

Thank you!!
