### ISSUE TITLE
Multipule processes starting with systemd

### ISSUE THREAD

**Issue by stoivo** [mperham/sidekiq#4123]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): Sidekiq, open source (5.2.5)

I have a question related to systemd and sidekiq. I have seen the example, [/examples/systemd/sidekiq.service](https://github.com/mperham/sidekiq/blob/91d76800f6aace27c72183d1de469b4a3213e545/examples/systemd/sidekiq.service). We have been running with one process for a year. Now we would like to setup 3 more processes. So we can utilize more of our cors.

How can we do that with systemd, I  search around and could not find a good solution. So my question is. What would you recomend me?

**Comment by mperham** [comment]
cp sidekiq.service sidekiq2.service
cp ...
etc

There’s no clean way without Sidekiq Enterprise’s multi process support.

**Comment by stoivo** [comment]
Thank you
