### ISSUE TITLE
Opencensus / Google Cloud trace integration

### ISSUE THREAD

**Issue by danielmbarlow** [mperham/sidekiq#4124]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): "sidekiq-ent", "1.7.1"

A management decision has required us to stop using Appsignal which was great for tracing Sidekiq jobs. We have try to implement Google Cloud trace.

I checked the Changelogs and don't see any reference to integration with Google cloud trace, so I am looking into coding an interface myself. I have been [recommended to add that functionality to the opencensus gem](https://github.com/googleapis/google-cloud-ruby/issues/2836).

I'm creating this issue to make sure I'm not duplicating another project to provide Google Cloud Trace integration. Do you know of any such projects?

**Comment by mperham** [comment]
I’ve never heard of anything about GC trace and Sidekiq.

**Comment by danielmbarlow** [comment]
Thanks for your answer. This is the PR I'm working on to implement this feature in case anyone else stumbles on this thread: https://github.com/census-instrumentation/opencensus-ruby/pull/102
