### ISSUE TITLE
Processes never finishing

### ISSUE THREAD

**Issue by prakash-subramani** [mperham/sidekiq#4125]
Ruby version: 2.1.6
Sidekiq : 4.1.2

The sidekiq dashboard always shows, there is 4 process running even there are no jobs to process. I can't able to stop or kill the process from the dashboard. Here is the screenshot. Please advise

<img width="1434" alt="Screenshot 2019-03-13 at 3 55 56 PM" src="https://user-images.githubusercontent.com/17075742/54271944-98175900-45a8-11e9-8886-304304db4ae8.png">

**Comment by mperham** [comment]
Please upgrade. This bug was fixed three years ago.
