### ISSUE TITLE
Typo in Sidekiq Pro

### ISSUE THREAD

**Issue by ramaboo-deliv** [mperham/sidekiq#4126]
Ruby version: 2.6.2
Sidekiq Pro 4.0.5

<img width="1410" alt="Screen Shot 2019-03-13 at 4 01 28 PM" src="https://user-images.githubusercontent.com/32721566/54320342-e842eb00-45a9-11e9-86c1-7437d44b80cb.png">

There are 2 spaces between the `licensed.` and `Thanks` there should be one.

**Comment by mikegee** [comment]
There is still some disagreement about two spaces after the period in monospaced text. I would characterize this as a preference rather than an error.

**Comment by ramaboo** [comment]
True there are a few hold outs on spacing from the old days. Much of sidekiqs own codebase is single spaced and it seems the world is moving towards a single space always approach given how much of text now exists on the web and the web simply does not support double space.

**Comment by mperham** [comment]
What color should we paint the bike shed?
