### ISSUE TITLE
[ENT] save_history(statsd, seconds) is deprecated

### ISSUE THREAD

**Issue by stormsilver** [mperham/sidekiq#4127]
Ruby version: `2.6.1`
Sidekiq / Pro / Enterprise version(s): `Sidekiq 5.2.5 / Pro 4.0.5 / Ent 1.8.1`

Please include your initializer and any error message with the full backtrace.
```ruby
Sidekiq.configure_server do |config|
  config.save_history(Sidekiq::Pro.metrics, 60) do |statsd, sidekiq_stats|
    statsd.batch do |s|
      s.gauge('sidekiq.default_queue_latency', sidekiq_stats.default_queue_latency)
      s.gauge('sidekiq.process_count', sidekiq_stats.processes_size)
    end
  end
end
```

When I fire up Sidekiq, I receive this helpful deprecation notice:

```
WARN: `save_history(statsd, seconds)` is deprecated, see https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics for current API
```

Unfortunately, when I go to the URL to see the current API, it appears that it is identical to the deprecated API.

* Perhaps we thought this should be deprecated but then we changed our minds?
* Perhaps we forgot to update the wiki to show the preferred code?
* Perhaps I'm missing something obvious?

**Comment by mperham** [comment]
Thanks for the reminder, I forgot to update the docs after releasing the latest version.  Fixed.
