### ISSUE TITLE
Web UI 'Plugins' dropdown menu problems

### ISSUE THREAD

**Issue by murat** [mperham/sidekiq#4128]
Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.10
Rails version: 4.2.11.1

I'm using `sidekiq` with `sidekiq-sceheduler` and `sidekiq-statistics` plugins. In Web UI, `Plugins` dropdown in navbar behaving weirdly when app running on the production environment. Please look at the screenshots.

![Screen Shot 2019-03-15 at 15 07 51](https://user-images.githubusercontent.com/1137480/54431355-4224eb80-4737-11e9-8ee6-d96fa34f9628.png)

Tried these solutions:

1. bootstrap.min.css(v3.3.7) fetched from CDN
2. `.nav.navbar-nav`'s `width: 100%` style removed

It fixed some things but I could not see `dropdown-menu` when it opened, because of it still under the navbar, I tried to increase `z-index` property but it does not work.

![Screen Shot 2019-03-15 at 15 34 13](https://user-images.githubusercontent.com/1137480/54431636-fe7eb180-4737-11e9-98c8-118de581dd82.png)

**Comment by mperham** [comment]
Upgrade to 5.2.

**Comment by murat** [comment]
Thanks for the suggestion, but I cannot upgrade because of other gems incompatible with 5.x, I'll try to fix the problem on v4.2.10 tag.
