### ISSUE TITLE
Version check mistake

### ISSUE THREAD

**Issue by kovalevvv** [mperham/sidekiq#4131]
Ruby version: 2.2.10
Sidekiq / Pro / Enterprise version(s): 5.0.3

Gem Load Error is: Sidekiq 5.0.3 does not support Ruby versions below 2.2.2.

===================
sidekiq-5.0.3/lib/sidekiq.rb
...
fail "Sidekiq #{Sidekiq::VERSION} does not support Ruby versions below 2.2.2." if RUBY_PLATFORM != 'java' && RUBY_VERSION < '2.2.2'

2.2.10 :007 > '2.2.10' > '2.2.2'
 => false

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/Changes.md#513
