### ISSUE TITLE
sidekiq jobs not getting re-queued

### ISSUE THREAD

**Issue by davidneudorfer** [mperham/sidekiq#4133]
Ruby version: 2.3.7p456
Sidekiq / Pro / Enterprise version(s): Pro 4.0.5

According to the [docs](https://github.com/mperham/sidekiq/wiki/Deployment#events) 
> To safely shut down Sidekiq, you need to send it the TSTP signal as*early*as possible in your deploy process and the TERM signal as*late*as possible. TSTP tells Sidekiq to stop pulling new work and finish all current work. TERM tells Sidekiq to exit within N seconds, where N is set by the-ttimeout option and defaults to 8. Using TSTP+TERM in your deploy process gives your jobs the maximum amount of time to finish before exiting.

> If any jobs are still running when the timeout is up, Sidekiq*will*push those jobs back to Redis so they can be rerun later.

If you follow my [log](https://gist.github.com/davidneudorfer/2de4ae3f0573a0851d8c6d268c8c8033) I send both the TSTP+TERM signals but jobs are never pushed back to Redis. What can I do to further troubleshoot the issue?

_Note though we are on Sidekiq Pro we are not yet using `super_fetch`._

**Comment by mperham** [comment]
Turn on verbose logging, it will print out a few more lines with detail of interest.  I assume your process is KILLed before your `-t` timeout setting runs out.  The `-t` shutdown timeout starts once TERM is received so if you have `-t 25`, you will see a "pushing jobs back" message 25 seconds after sending TERM if any jobs are still running.

If you didn't know, Sidekiq Enterprise's [rolling restart feature](https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts) will allow long-running jobs to run as long as necessary to finish and then exit.  No more timeouts and shutdown races.

**Comment by davidneudorfer** [comment]
Thanks @mperham. I've enabled verbose [logging](https://gist.github.com/davidneudorfer/2de4ae3f0573a0851d8c6d268c8c8033#file-gistfile2-txt).

```
2019-03-26T17:58:17.239Z 23084 TID-gqj6zex8s DEBUG: Got TERM signal
2019-03-26T17:58:17.239Z 23084 TID-gqj6zex8s INFO: Shutting down
2019-03-26T17:58:17.740Z 23084 TID-gqj6zex8s INFO: Pausing to allow workers to finish...
2019-03-26T17:59:51.073Z 25735 TID-gol7nn3hr INFO: Booting Sidekiq 5.2.2 with redis options {:url=>"redis://lrnz-qa-jobs.ua96ya.ng.0001.use1.cache.amazonaws.com:6379/0", :namespace=>"sidekiq", :network_timeout=>5, :id=>"Sidekiq-server-PID-25735"}
```

According to the logs thats 94 seconds between receiving the TERM and starting sidekiq.

Since we don't set a timeout, is the default 8 seconds?

Our systemd script:
```
[Unit]
Description=sidekiq
After=syslog.target network.target
[Service]
WorkingDirectory=/www/learnzillion/staging/current
ExecStart=/www/learnzillion/staging/current/bin/sidekiq -e staging -C config/sidekiq.yaml
User=deployer
Group=developers
UMask=0002

Environment=PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=RAILS_ENV=staging
Environment=TORBA_HOME_PATH=/www/learnzillion/staging/shared/vendor/torba
Environment=NEW_RELIC_APP_NAME=qazillion.com-sidekiq

RestartSec=1
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I also went ahead and enabled `super_fetch` before seeing your response but that isn't helping either.

**Comment by mperham** [comment]
You aren’t including the debug line on startup that logs the configured options hash. That will tell you the timeout. Super fetch will help but it takes a few hours and a process restart to rescue any orphaned jobs.

**Comment by mperham** [comment]
Ah it’s in the gist. 1800 seconds, far too long. I’m guessing systemd has a 90 second timeout so I’d investigate an option in your unit file.

**Comment by mperham** [comment]
Your timeout is coming from config/sidekiq.yml.

**Comment by mperham** [comment]
Looks like you want `TimeoutSec=` here http://0pointer.de/public/systemd-man/systemd.service.html

**Comment by mperham** [comment]
Yep, on Ubuntu 18.04, `/etc/systemd/system.conf`:

DefaultTimeoutStopSec=90s

**Comment by mperham** [comment]
In other words, change 1800 to 60 in your sidekiq.yml and everything should work.  If you want your long-running jobs to finish without restarting, you need rolling restarts.

**Comment by davidneudorfer** [comment]
Thanks @mperham that was it. I'll look at Sidekiq Enterprise as well.
```
2019-03-26T18:40:39.053Z 6217 TID-gr7t8ejzh WARN: Terminating 1 busy worker threads
2019-03-26T18:40:39.053Z 6217 TID-gr7t8ejzh WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork queue="queue:default", job="{\"class\":\"CustomerDeletionWorker\",\"args\":[717],\"retry\":3,\"queue\":\"default\",\"jid\":\"125cd3dd24fc420100a7fb55\",\"created_at\":1553625528.9092643,\"enqueued_at\":1553625537.8817515}">]
2019-03-26T18:40:39.053Z 6217 TID-gr7t8ejzh DEBUG: Re-queueing terminated jobs
2019-03-26T18:40:39.054Z 6217 TID-gr7t8ejzh INFO: Pushed 1 jobs back to Redis
```
