### ISSUE TITLE
sidekiqctl status not work with custom redis config

### ISSUE THREAD

**Issue by lingceng** [mperham/sidekiq#4134]
Ruby version: 2.5.3
Sidekiq version(s): 5.2.5

I use Sidekiq with Rails 5.2.2 and Docker. I config Redis in `config/initializers/sidekiq.rb`

     Sidekiq.redis = { host: 'jobredis' }

The `sidekiq` command works fine but `sidekiqctl status` not work.
```
root@963eb4d95d47:/myapp# bundle exec sidekiqctl status
Sidekiq 5.2.5
2019-04-01 07:52:46 +0000

---- Overview ----
Couldn't get status: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
```
It seems the `sidekiqctl` not respect the config in `config/initializers/sidekiq.rb`

**Comment by mperham** [comment]
Use `REDIS_URL=redis://jobredis sidekiqctl ...`

**Comment by lingceng** [comment]
Thanks a lot. It works

    REDIS_URL=redis://jobredis sidekiqctl status
