### ISSUE TITLE
How does multiple sidekiq process coordinate one single queue?

### ISSUE THREAD

**Issue by jgomo3** [mperham/sidekiq#4136]
Could someone elaborate a bit on how the coordination between multiple sidekiq processes (in different machines) using the same queue works? Or is there any documentation on the feature?

Thank you.

Related: https://github.com/mperham/sidekiq/issues/3603

**Comment by mperham** [comment]
Redis ensures that popping a job off a queue is atomic, every call by Sidekiq will either get a job or time out.  https://redis.io/commands/BLPOP
