### ISSUE TITLE
Custom JobLogger in Sidekiq Enterprise

### ISSUE THREAD

**Issue by benfb** [mperham/sidekiq#4139]
Ruby version: `2.4.5`
Sidekiq / Pro / Enterprise version(s): `5.2.5`/`4.0.5`/`1.8.1`

Initializer:
```
Sidekiq.configure_server do |config|
  ...
  config.options[:job_logger] = SidekiqParametersLogger
  ...
end
```

Gives error: `NameError: uninitialized constant Sidekiq::JobLogger` on startup.

This is the custom JobLogger class, which works if Pro and Enterprise are not installed:
```ruby
class SidekiqParametersLogger < Sidekiq::JobLogger
  def call(item, queue)
    # Logs job parameters if they exist
    Sidekiq::Logging.with_context("") do
      begin
        start = ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
        logger.info("start parameters: #{item['args'].inspect}")
        yield
        logger.info("done: #{elapsed(start)} sec")
      rescue Exception
        logger.info("fail: #{elapsed(start)} sec")
        raise
      end
    end
  end
end
```

Do pro and enterprise not support the custom JobLogger class?

**Comment by mperham** [comment]
Pro and Enterprise should support all the same logging options as Sidekiq OSS.  Maybe you need to require something at the top of your class?

**Comment by benfb** [comment]
The odd thing is when I run `bundle exec rails c` with the `sidekiq-pro` and `sidekiq-ent` gems or just `sidekiq-pro` installed, `Sidekiq::JobLogger` doesn't show up in the console and gives a NameError, but when only `sidekiq` is installed, it does show up, despite the initializer not changing. Is there a difference in the way that class is loaded in the pro version?

**Comment by mperham** [comment]
JobLogger should only be loaded inside the Sidekiq process itself.  It shouldn't be loaded in the console so you want to do this:

```ruby
Sidekiq.configure_server do |config|
  require 'sidekiq_parameters_logger'
  config.options[:job_logger] = SidekiqParametersLogger
end
```

**Comment by benfb** [comment]
Thanks!
