### ISSUE TITLE
push_bulk only executing one item from an array of items

### ISSUE THREAD

**Issue by sqlninja** [mperham/sidekiq#4140]
Ruby version: 2.5.0p0
Sidekiq version(s): 5.2.5

Please include your initializer and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'], size: ENV['SIDEKIQ_CONCURRENCY'].to_i + 2 }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'], size: 1 }
end
```
`SIDEKIQ_CONCURRENCY : 7`

Are you using an old version? Don't think so...
Have you checked the changelogs to see if your issue has been fixed in a later version? Been searching all day after a refactor

I have a worker that queries for records that need processing, and this worker then puts all ids into an array.
This worker then loops over the array in groups of 1000 and calls push_bulk (on a different worker) to add each record to the queue to be processed.

On my local machine, I have ~800 records that are processable, but every time I call the "parent" worker it only seems to call the child worker once*.

*this is verified by watching the sidekiq web UI and by calling perform on the parent worker from the terminal.

I have spot checked the child job by calling it manually, passing a random processable record id. Also when I simply try to send 5 ids into push_bulk I get the same results, just one job id.

```
records = [1,3,7,9,33]
p records.map {|id| [id] }
job_ids = Sidekiq::Client.push_bulk({ 'class' => RecordProcessWorker, 'args' => records.map {|id| [id] }, 'queue' => RecordProcessWorker.sidekiq_options['queue'] })

=> ["09b3a29d82a5169c1dece24d"] 
```

**Comment by mperham** [comment]
Works for me.

```
$ bundle exec rails c
Loading development environment (Rails 5.2.2)
irb(main):001:0> records = [1,3,7,9,33]
=> [1, 3, 7, 9, 33]
irb(main):002:0> p records.map {|id| [id] }
[[1], [3], [7], [9], [33]]
=> [[1], [3], [7], [9], [33]]
irb(main):003:0> job_ids = Sidekiq::Client.push_bulk({ 'class' => "RecordProcessWorker", 'args' => records.map {|id| [id] }})
=> ["76b6c3a0cf21f2ffd33ad1eb", "cb23fdbfba52f7600641c925", "9415de4a2b76dc65bbf2ba32", "62c67d0686d6296eba37d249", "ef89a38e780e31beca117061"]
```

**Comment by sqlninja** [comment]
🤔
Thanks for the quick reply, but is there anything more diagnostic I should be looking for?
I'll add that originally this was simply on my local machine, so I pushed my code to our dev server to eliminate the "does/doesn't work on my machine concern" and I'm seeing the same issue on the dev server which is only creating one "child" job

I'll add that the individual child jobs work fine when called with `#new.perform(...)`

Also, i notice that you are passing a string as the class in your example, is that simply because you don't actually have that class/model or should I be passing it as a string as well?

Thanks,
John

**Comment by mperham** [comment]
Maybe use `pry` to step into the push_bulk call and follow the execution?

**Comment by mperham** [comment]
Yes, I'm using a String because I don't have the class.  This is how you push a job from one app to another.

**Comment by sqlninja** [comment]
@mperham So, I tried stepping into the push_bulk execution with pry, but it always stepped over...

Another oddity I noticed, was if I supply a junk worker name string (one that does not exist in my system) push_bulk would create all the jobs (They all fail of course), but when using the actual worker name or worker name as a string it never creates the jobs...

{{scratching my head...}}

so to recap...
```
job_ids = Sidekiq::Client.push_bulk('class' => 'RealWorkerName', 'args' => (1..50).to_a.map { |x| Array(x) })
```
`NO JOB IDS RETURNED`

```
job_ids = Sidekiq::Client.push_bulk('class' => 'FAKEWorkerName', 'args' => (1..50).to_a.map { |x| Array(x) })
```
`50 JOB IDS RETURNED`


I feel like I have to be missing something obvious...

**Comment by mperham** [comment]
🤷‍♂️

**Comment by sqlninja** [comment]
I guess I just needed this issue to be my 🦆 

I found the issue in the child job...

Thanks for the pry suggestion and listening...
