### ISSUE TITLE
Add shutdown_completed Hook

### ISSUE THREAD

**Issue by madejejej** [mperham/sidekiq#4145]
Hi @mperham!

We have an additional background-processing thread running along with Sidekiq processes. Some of our Sidekiq workers push data into that thread and it does (micro)batch processing on the data.

Our thread has a `shutdown` procedure where it flushes all the data it has and stops receiving data. If another thread wants to push a unit of work into the queue, it raises an error.

We can't come up with a clean shutdown procedure using the current `:shutdown` hook. That's because it's being called before all the workers finish processing, so the following concurrency scenario is an issue for us:

1. We quiet Sidekiq during deploy/shutdown
2. We shutdown Sidekiq
3. The `:shutdown` hook is run and it stops our background processing thread
4. Some workers are still running and trying to push data into our queue which results in errors

The cleanest option for us would be to use a hook which guarantees all workers are stopped. Are you opened to having such a hook in Sidekiq?

**Comment by mperham** [comment]
Isn’t this Ruby’s at_exit?

**Comment by madejejej** [comment]
You're right. I don't know why but I thought Sidekiq uses `at_exit`. Then ours would run before Sidekiq's. Sorry for bothering!
