### ISSUE TITLE
delete_by_class will miss jobs if queue size changes between batches

### ISSUE THREAD

**Issue by heironimus** [mperham/sidekiq#4146]
Ruby version: 2.3.8
Sidekiq / Pro / Enterprise version(s): Pro 4.0.5

`delete_by_class` loads jobs in batches of 50, but does not take into account any changes in the queue size between batch loads, meaning if the queue size increases, it will quit looking before it gets to the end. Or if the queue size decreases, it will skip over jobs.

I'm pretty sure it should use something like a `deleted_size` value [that is used](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L283) in `Sidekiq::Queue#each`

**Comment by mperham** [comment]
each uses that logic because the user can call `delete` on the job when inside the yield so it has to account for deletes within its own iteration.

delete_by_class does not allow any outside actions or yield and it deletes starting from the tail so that its actions will not shift the list.  I'm not sure what other actions it can take.

**Comment by heironimus** [comment]
I was talking about workers on other processes adding jobs to the queue while this is traversing it. Won't that cause an issue?

**Comment by mperham** [comment]
Yes, but how am I supposed to detect and account for that?

**Comment by heironimus** [comment]
So are you saying that the paid pro feature `delete_by_class` is very unreliable if used on a running system, but that's ok because it's hard/impossible to fix? I'm not sure what you are asking.

**Comment by mperham** [comment]
I have to work within the semantics that Redis provides but I'm always open to suggestions on how to improve it.  One possibility is to provide a "strict" version which uses Lua but then every other work process trying to operate on that queue will pause until it is done.  In fact I believe delete_by_class used to be implemented in Lua until a customer complained about the latency hit so ... 🤷🏼‍♂️

**Comment by heironimus** [comment]
It seems like using something like the  `deleted_size` method that `each` uses will work here. In any case, it looks like this will have the same issue as #4147 

I just thought you would want to know about this and possibly document the issue if you don't fix it.

**Comment by mperham** [comment]
Added notes to API wiki page, noting that any operation which iterates can be racy.
