### ISSUE TITLE
Sidekiq::Queue#each thread safe

### ISSUE THREAD

**Issue by heironimus** [mperham/sidekiq#4147]
Ruby version: 2.3.8
Sidekiq / Pro / Enterprise version(s): 5.2.6

I think there is an issue where if the queue size changes between execution in a loop of [this line](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L283) and [this_line](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L276) jobs will either be skipped or duplicated. I was able to duplicate by putting a breakpoint in the code and adding/deleting entries from the queue, then continuing.

**Comment by mperham** [comment]
We are mutating a distributed data structure without a lock.  You need to either use Lua so the prune is atomic (which acts as a lock and would lead to a huge "stop the world" pause for large queues) or accept this limitation.  We have to operate on windows of data in order to avoid that pause and allow concurrency from other connections.

This is one of the reasons why I explicitly state that the API is not for application logic but for maintenance/data migrations only, where you can better control access.

**Comment by heironimus** [comment]
Ok. That doesn't seem clear from the documentation. 

> WARNING the API exposes some operations which are not scalable and should not be used in an automated fashion or in bulk as part of your application functionality. You should not be scanning through queues/sets and deleting jobs unless something has gone wrong and you need to repair data manually.

I took that to mean it would be really slow, but not necessarily that it might be incorrect.

I see what you are saying and I completely understand you not adding the extra overhead, if it's even possible, to work around this. In that case, should the warning be a little more explicit about the possibility of missed/duplicated jobs?

**Comment by mperham** [comment]
Sure, you are welcome to update the wiki.

**Comment by heironimus** [comment]
I added the WARNING 2 section at the top of the [the API page](https://github.com/mperham/sidekiq/wiki/API) Does that sound right?

**Comment by mperham** [comment]
It's overly general, the limitation is specific to Sidekiq::Queue.

Sidekiq uses Redis' SCAN support* for hashes, sets and zsets which guarantee iteration of all elements present when the scan starts:

https://redis.io/commands/scan#scan-guarantees

* In fact, now that I look at api.rb, I can see that JobSet#each does not use zscan_each, which is either a bug or there's a semantic reason why we aren't using it.
