### ISSUE TITLE
After my sidekiq upgrade to gitlab, there are frequent process exits

### ISSUE THREAD

**Issue by elain** [mperham/sidekiq#4148]
Ruby version: 2.5.3p105
Sidekiq v5.2.1

my error message, The detailed logs are attached.

---------------------------------
2019-04-15T02:09:59.810Z 16196 TID-otni0euv0 ExpireJobCacheWorker JID-8352ef8982a380549ac6fb8d INFO: start
/home/micode/micode/lib/gitlab/untrusted_regexp.rb:23: [BUG] Segmentation fault at 0x00007f6200000000
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0049 p:---- s:0253 e:000252 CFUNC  :error
c:0048 p:0066 s:0249 e:000246 METHOD /home/micode/micode/lib/gitlab/untrusted_regexp.rb:23 [FINISH]
c:0047 p:---- s:0240 e:000239 CFUNC  :new
c:0046 p:0031 s:0235 e:000234 METHOD /home/micode/micode/lib/gitlab/ci/trace/stream.rb:83
c:0045 p:0008 s:0229 e:000228 BLOCK  /home/micode/micode/lib/gitlab/ci/trace.rb:33
c:0044 p:0023 s:0225 e:000224 METHOD /home/micode/micode/lib/gitlab/ci/trace.rb:78
c:0043 p:0005 s:0220 e:000219 METHOD /home/micode/micode/lib/gitlab/ci/trace.rb:32
c:0042 p:0011 s:0215 e:000214 METHOD /home/micode/micode/app/models/ci/build.rb:438
c:0041 p:0020 s:0210 e:000209 METHOD /home/micode/micode/app/workers/build_coverage_worker.rb:9
c:0040 p:0038 s:0205 e:000204 BLOCK  /home/micode/micode/app/workers/build_finished_worker.rb:14
c:0039 p:0036 s:0201 e:000200 METHOD /home/micode/micode/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_e
xt/object/try.rb:74
c:0038 p:0029 s:0195 e:000194 METHOD /home/micode/micode/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/core_e
xt/object/try.rb:63
c:0037 p:0018 s:0189 E:001af8 METHOD /home/micode/micode/app/workers/build_finished_worker.rb:11
c:0036 p:0009 s:0184 e:000183 METHOD /home/micode/micode/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185
c:0035 p:0019 s:0178 e:000177 BLOCK  /home/micode/micode/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167
c:0034 p:0010 s:0175 e:000174 BLOCK  /home/micode/micode/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:
128

.......

7f62a417c000-7f62a41a0000 r--s 00000000 fd:00 539378                     /usr/lib64/libpthread-2.17.so
7f62a41a0000-7f62a41ad000 r-xp 00000000 fd:00 538746                     /usr/lib64/libnss_myhostname.so.2
7f62a41ad000-7f62a41b0000 r--p 0000c000 fd:00 538746                     /usr/lib64/libnss_myhostname.so.2
7f62a41b0000-7f62a41b1000 rw-p 0000f000 fd:00 538746                     /usr/lib64/libnss_myhostname.so.2
7f62a41bf000-7f62a42c5000 rw-p 00000000 00:00 0
7f62a42c6000-7f62a42c7000 rw-p 00000000 00:00 0
7f62a42c7000-7f62a42c8000 r-xp 00000000 00:00 0
7f62a42c8000-7f62a42cf000 r--s 00000000 fd:00 1184493                    /usr/lib64/gconv/gconv-modules.cache
7f62a42cf000-7f62a42d0000 ---p 00000000 00:00 0
7f62a42d0000-7f62a42d4000 rw-p 00000000 00:00 0                          [stack:16198]
7f62a42d4000-7f62a42d5000 r--p 0001f000 fd:00 538907                     /usr/lib64/ld-2.17.so
7f62a42d5000-7f62a42d6000 rw-p 00020000 fd:00 538907                     /usr/lib64/ld-2.17.so
7f62a42d6000-7f62a42d7000 rw-p 00000000 00:00 0
7f62a42d7000-7f62a45ff000 r-xp 00000000 fd:00 152313                     /usr/local/bin/ruby
7f62a47ff000-7f62a4804000 r--p 00328000 fd:00 152313                     /usr/local/bin/ruby
7f62a4804000-7f62a4805000 rw-p 0032d000 fd:00 152313                     /usr/local/bin/ruby
7f62a4805000-7f62a4817000 rw-p 00000000 00:00 0
7f62a5a4e000-7f62a6d0c000 rw-p 00000000 00:00 0                          [heap]
7f62a6d0c000-7f62b9d2e000 rw-p 00000000 00:00 0                          [heap]
7fff00036000-7fff00835000 rw-p 00000000 00:00 0                          [stack]
7fff00858000-7fff0085a000 r--p 00000000 00:00 0                          [vvar]
7fff0085a000-7fff0085c000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

----------------------------------

[sidekiq.log](https://github.com/mperham/sidekiq/files/3084727/sidekiq.log)

**Comment by mperham** [comment]
I don't provide support for GitLab.  You need to talk to them.
