### ISSUE TITLE
Report Enterprise Rate Limiting Metrics to Statsd

### ISSUE THREAD

**Issue by shaley91** [mperham/sidekiq#4150]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Enterprise

Would it be possible to report the Enterprise Rate Limiting Metrics to Statsd?

Metrics - https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#concurrent-metrics

**Comment by mperham** [comment]
Most of the concurrent metrics implementation is in Redis Lua so it's not accessible to statsd in realtime.  You can use the extensible historical metrics support to collect and send metrics for limiters you care about:

https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics#custom

```ruby
# for this limiter
ERP = Sidekiq::Limiter.concurrent("erp", 4)

# save stats
Sidekiq.configure_server do |config|
  config.retain_history(30) do |s|
    c = Sidekiq::Limiter::Status::Concurrent.new(nil, "erp")

    # save c.wait_time, c.held_time, c.immediate, c.waited, c.reclaimed, etc.
    s.batch do |b|
      b.gauge(...)
      b.counter(...)
    end
  end
end
```

**Comment by shaley91** [comment]
Thanks @mperham!!!
