### ISSUE TITLE
Strategies for conflicts with unique jobs

### ISSUE THREAD

**Issue by plentz** [mperham/sidekiq#4151]
Ruby version: 2.6.2
Sidekiq / Pro / Enterprise version(s): sidekiq (5.1.3) / sidekiq-pro (4.0.3) / sidekiq-ent (1.6.1)

Basically what https://github.com/mhenrixon/sidekiq-unique-jobs#replace does.

**Comment by mperham** [comment]
Sidekiq Enterprise's unique jobs feature tries to be much simpler than that gem because those features and edge cases are full of race conditions and horribly slow performance at scale.
