### ISSUE TITLE
Statsd should errror if passed an instance

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4152]
Currently Sidekiq Pro supports this:

```ruby
Sidekiq::Pro.statsd = ::Statsd.new('127.0.0.1', 8125)
```

This uses a global singleton for statsd, which creates a hotspot for contention among Sidekiq's processor threads.  We've been emitting this warning for many months now, recommending people move to a form that can be pooled:

```
WARN: Sidekiq::Pro.statsd should be set to a Proc, e.g. ->{ ::Statsd.new('127.0.0.1', 8125) }
```

Instead now raise an ArgumentError.

**Comment by nakulpathak3** [comment]
Another "issue" here (not sure if you would call this an issue or a design decision) is that if a bad instance is passed, it errors out the job altogether even if nothing went wrong with the `perform` or middlewares other than the metrics one.
