### ISSUE TITLE
Rails Encrypted Secrets with sidekiq

### ISSUE THREAD

**Issue by ranupratapsingh** [mperham/sidekiq#4154]
Ruby version: 2.6.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.7
Rails Version: 6.0.0.beta3

Hi, I am trying to use rails encrypted credentials with sidekiq.yml and getting `uninitialized constant Rails` error.

sidekiq.yml
-----------------

    redis_default: &redis_defaults
      host: 127.0.0.1
      port: 6379
      namespace: 'bg'
      db: 1
      password: <%= Rails.application.credentials.sidekiq_redis_password %>
    
    development: &default
      :concurrency: 5
      :logfile: ./log/sidekiq.log
      logger:
        level: Logger::DEBUG
      :redis_config:
        <<: *redis_defaults
      :queues:
        - default
        - providers

sidekiq initializer
-----------------

    redis_config = Rails.application.config_for(:sidekiq)['redis_config']
    redis_url = "redis://#{redis_config['host']}:#{redis_config['port']}/#{redis_config['namespace']}"
    redis_password = redis_config['password']

    Sidekiq.configure_server do |config|
      config.redis = { url: redis_url, password: redis_password}
    end

    Sidekiq.configure_client do |config|
      config.redis = { url: redis_url, password: redis_password}
    end

Error Stack Trace
-----------------

    uninitialized constant Rails
    (erb):4:in `<main>'
    /Users/rpsingh/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/erb.rb:901:in `eval'
    /Users/rpsingh/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/erb.rb:901:in `result'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:414:in `parse_config'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:255:in `setup_options'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:31:in `parse'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/gems/sidekiq-5.2.7/bin/sidekiq:11:in `<top (required)>'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/bin/sidekiq:23:in `load'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/bin/sidekiq:23:in `<main>'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
    /Users/rpsingh/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'

Workaround
------------
I got this working by

 1. removing password line from `config/sidekiq.yml`
 2. Replacing `redis_password = redis_config['password']` with `redis_password = Rails.application.credentials.sidekiq_redis_password`

Is this the recommended way of doing it or the first way should also work ?

**Comment by mperham** [comment]
Sidekiq.yml is processed before Rails is booted. Besides, Redis config is not designed to go in that yml, only command line arguments. The initializer should hold all of your Redis setup logic.

**Comment by ranupratapsingh** [comment]
Thanks @mperham for confirming the recommended way.
