### ISSUE TITLE
Deleting a large batch is expensive

### ISSUE THREAD

**Issue by marcboquet** [mperham/sidekiq#4155]
We have some batches with hundreds of thousands of jobs, we're following the [Huge Batches](https://github.com/mperham/sidekiq/wiki/Batches#huge-batches) tips to avoid latency spikes when creating the batch.

But when Sidekiq Pro is deleting the batch we're also seeing big spikes. The biggest offender for us is this line in `Batch::Callback#success`:
```ruby
conn.del "b-#{bid}-failinfo", "b-#{bid}-success", "b-#{bid}-complete", "b-#{bid}-jids"
```
It sometimes takes 10ms+ according to `slowlog`.

We're using Redis 4 so we would benefit from using `unlink` instead of `del` for these calls.

**Comment by mperham** [comment]
Sidekiq 6 requires Redis 4 so Pro 5.0 will have the same requirement. Not sure of timeline but you can alias del to unlink for an easy workaround.

**Comment by marcboquet** [comment]
When you say alias you mean we could do `rename-command UNLINK DEL`?

**Comment by mperham** [comment]
I mean alias_method the Redis client in your initializer. Semantics should be the same.

**Comment by marcboquet** [comment]
Ended up doing
```
rename-command DEL ""
rename-command UNLINK DEL
```
And it reduced redis latency by ~20%, pretty happy with it.

Thanks!

**Comment by mperham** [comment]
💪🏻😎
