### ISSUE TITLE
Sidekiq schedular stops at 1 week

### ISSUE THREAD

**Issue by HisashiQ** [mperham/sidekiq#4157]
Ruby version: 2.5.1
Sidekiq version: Sidekiq 5.2.1

Hi

I am setting up an email schedular that sends emails every 2 days from sign up until the 12th day. Day 2, 3, 4, 6 work fine. Everything after that appears to get scheduled as 1 week. Does the scheduler round everything over 1 week down to 1 week?  This is the basic setup:

`2.step(12, 2) do |i|
      SendgridMailWorker.perform_at(
          i.days.from_now,
          user_email,
          ENV["SENDGRID_LEARNING_PLAN_#{i}_TEMPLATE_ID"]
      )
    end`

I have looked in the docs and nothing mentions a limit on the schedular. Did I miss it. I looked for a discussion on this topic but found nothing.

Thanks in advance.

**Comment by mperham** [comment]
Scheduling should work up to one billion seconds in the future. I don’t know why you are seeing that behavior.

**Comment by HisashiQ** [comment]
Is it an issue with the Sidekiq Web?  

<img width="1218" alt="Screenshot 2019-04-30 at 17 26 26" src="https://user-images.githubusercontent.com/15221950/56977696-aed03a00-6b6d-11e9-9266-74c3ce198151.png">

The screen shot shows the LearningPlanEmailerJob who's second argument is the time value i used to schedule the jobs. You can see that once it gets over a week it defaults to 'in one week'.

Will this still fire at the right time and it's a UI issue or will it really fire anything over a week in 1 week?

Any help is appreciated.

**Comment by HisashiQ** [comment]
I just dived into the web frontend code and noticed a helper function called `relative_time` which is outputting the relative time of the scheduled job and is also marking the datetime attribute with the ISO8601 standard which allowed me to check the actual date each of these is going to go out and they are indeed going out at the correct time. Example being:

`<time class="ltr" dir="ltr" title="2019-05-16T17:19:54Z" datetime="2019-05-16T17:19:54Z">in 2 weeks</time>`

However, I feel as though the scheduled job UI should always explicitly show the time you scheduled. (If you used days then days and if you used seconds then seconds). It would have saved me an afternoon for example. What do you think?

**Comment by mperham** [comment]
If you mouse over the "in one week", the tooltip is the precise time.

**Comment by mperham** [comment]
As you've discovered, those relative time descriptions are approximate and supposed to be human-friendly, so we don't overwhelm the UI with unnecessary data.
