### ISSUE TITLE
Support Bundler API in gem server 

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4158]
Add support for Bundler’s /versions endpoint and any others. Ping @matthewd

**Comment by mperham** [comment]
https://github.com/bundler/compact_index/blob/master/README.md

**Comment by mperham** [comment]
So I have a gem repo which looks like this:

```
drwxr-xr-x@ 93 mikeperham  staff  2976 Apr 10 10:05 gems
-rw-r--r--@  1 mikeperham  staff   104 Apr 10 10:05 latest_specs.4.8
-rw-r--r--@  1 mikeperham  staff   103 Apr 10 10:05 latest_specs.4.8.gz
-rw-r--r--@  1 mikeperham  staff   198 Apr 10 10:05 prerelease_specs.4.8
-rw-r--r--@  1 mikeperham  staff   119 Apr 10 10:05 prerelease_specs.4.8.gz
drwxr-xr-x@  3 mikeperham  staff    96 Apr 10 10:05 quick
-rw-r--r--@  1 mikeperham  staff  2084 Apr 10 10:05 specs.4.8
-rw-r--r--@  1 mikeperham  staff   356 Apr 10 10:05 specs.4.8.gz
```

I have a Ruby script which scrapes the `/gems` directory to build a /versions static file:

```ruby
#!/usr/bin/ruby

require 'compact_index'

Gems = {
  "sidekiq-pro" => [],
  "sidekiq-ent" => [],
}

gemdir = ARGV[0] || raise("Missing required gem directory")
puts "Processing gems in #{gemdir}"

Dir["#{gemdir}/gems/*.gem"].each do |filename|
  name = File.basename(filename)
  puts name
  m = name.match(/([a-z-]+)-(\d\.\d{1,2}\.\d{1,2}(\.[a-z0-9]+)?).gem/)
  raise "No match for #{name}" unless m
  Gems[m[1]] << m[2]
end

extra_gems = []
Gems.each_pair do |gemname, vers|
  extra_gems << CompactIndex::Gem.new(gemname, vers.map {|ver| CompactIndex::GemVersion.new(ver, "ruby") }) unless vers.empty?
end

File.open("#{gemdir}/versions", "w+") do |file|
  file.write CompactIndex.versions(CompactIndex::VersionsFile.new("./versions"), extra_gems)
end
```

That gets me this file:

```
sidekiq-pro 1.9.3,2.0.4,2.0.5,2.0.6,2.0.7,2.0.8,2.1.0,2.1.1,2.1.2,2.1.3,2.1.4,2.1.5,3.0.0,3.0.0.pre1,3.0.0.pre2,3.0.1,3.0.2,3.0.3,3.0.4,3.0.5,3.0.6,3.1.0,3.2.0,3.2.1,3.2.2,3.3.0,3.3.1,3.3.2,3.3.3,3.4.0,3.4.0.pre1,3.4.1,3.4.2,3.4.3,3.4.4,3.4.5,3.5.0,3.5.1,3.5.2,3.5.3,3.5.4,3.6.0,3.6.1,3.7.0,3.7.0.pre1,3.7.1,4.0.0,4.0.1,4.0.2,4.0.3,4.0.4,4.0.5 
sidekiq-ent 0.5.0,0.6.0,0.7.0,0.7.1,0.7.10,0.7.2,0.7.3,0.7.4,0.7.5,0.7.6,0.7.7,0.7.8,0.7.9,1.0.0,1.0.0.pre1,1.0.1,1.0.2,1.1.0,1.2.0,1.2.1,1.2.2,1.2.3,1.2.4,1.3.0,1.3.1,1.3.2,1.4.0,1.5.0,1.5.1,1.5.2,1.5.3,1.5.4,1.6.0,1.6.1,1.7.0,1.7.1,1.7.2,1.8.0,1.8.1
```

It sounds like I might also need to generate the `/deps/sidekiq-pro` and `/deps/sidekiq-ent` files.

**Comment by mperham** [comment]
I've got `/versions` and `/info/{gemname}` files created and Bundler is requesting `/versions` but always downloads the .rz files individually instead of downloading the `/info/*` files.  No idea why but needs debugging.

**Comment by mperham** [comment]
Ah, the issue is that Apache cannot provide an ETag based on the file's content, which is O(n).  It can only provide Etags based on filesize, last mod time -- data available from File::Stat and O(1).

https://httpd.apache.org/docs/current/mod/core.html#fileetag

Bundler debug output:

```
HTTP 200 OK https://enterprise.contribsys.com/versions
The checksum of /versions does not match the checksum provided by the server! Something is wrong (local checksum is "\"487d3ce58e001af260de7036a3625682\"", was expecting "\"1d7-589906e773a9c\"").
```

This is a hard block; I don't see how to support the Bundler endpoints with Apache and static files. cc @indirect

**Comment by indirect** [comment]
I think if there’s no etag at all bundler will ignore it? If that doesn’t work, it’s probably a big we need to fix.

**Comment by mperham** [comment]
@indirect Looks like not:

```
The checksum of /versions does not match the checksum provided by the server! Something is wrong (local checksum is "\"487d3ce58e001af260de7036a3625682\"", was expecting "").
```

**Comment by indirect** [comment]
@mperham oof. I guess in that case I would suggest having the script generate a `.htaccess` file with this content:

```
FileETag none
Header unset Etag
Header set Etag #{Digest::MD5.hexdigest(File.read("./versions"))}
```

...or something like that. The file contents aren't going to change unless you run the script again, so it should be possible to generate the Etag header directly from the script.

**Comment by matthewd** [comment]
@mperham your `versions` file is missing the `---` header separator. I'm not sure how much of a contributing factor that is with your Bundler test, but it's certainly confusing Gel. 😅 

(:heart::heart::heart: for working on this, btw)

**Comment by mperham** [comment]
I'm punting on this in frustration right now.  It's adding more Apache complexity than I'm comfortable with; I can't get various combinations of .htaccess and <Files "versions"> to output the expected ETag header.

AFAIK adding a concurrent downloader is the main thing that would speed up `bundler install`, today it is still downloading one .rz file at a time (I also wonder if HTTP/2 support for pipelined downloads is possible).

Bundler is assuming the ETag is generated dynamically by Ruby.  Could it instead treat the ETag as a literal value or allow a nil value so that versions is downloaded every time?  For private servers like mine, the size of the versions file is under 1k.

**Comment by indirect** [comment]
I definitely think downloading the file again every time if the ETag header is missing is the right behavior for Bundler to have. We’ll need to explicitly make that happen, but that seems fine. 👍🏻

**Comment by mperham** [comment]
@indirect Any update on this?  Did any improvements land in Bundler? I'd be happy to sponsor some time for improvements if necessary.

**Comment by indirect** [comment]
@mperham to be honest, I've totally lost track. Let me see where things are at...

It looks like it would be relatively straightforward to make Bundler work with servers that don't provide an ETag by changing the conditional to something like `if !response.headers.has_key?("ETag") || etag_for(local_temp_path) == response_etag`: https://github.com/rubygems/rubygems/blob/a753447de8fb92dad30e927656984aa2b7765f3d/bundler/lib/bundler/compact_index_client/updater.rb#L70. I'll add it to my list for sometime in the vaguely near future, and if someone else beats me to it I'm happy to review the PR.

**Comment by indirect** [comment]
@mperham can you try building Bundler from rubygems/rubygems head and report if that fixes things? IIRC the steps are `git clone; cd bundler; rake deps; rake install`.

**Comment by mperham** [comment]
I don't have any of the necessary `versions` or `/info/<gem>` files server-side.  I will need to spend a day redoing this work and testing.

**Comment by mperham** [comment]
@indirect I have `names` and `versions` created now. Is it `/deps/<gemname>` or `/info/<gemname>`? These links are conflicting:

https://github.com/rubygems/compact_index/blob/master/README.md
https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/

If I have a set of .rz files for each gem version, how do I convert that into the info/deps files?

**Comment by indirect** [comment]
The gem itself is canonical (and is currently used by rubygems.org to generate the files): https://github.com/rubygems/compact_index.

Unfortunately I don't have any examples to get from .rz files into the compact index format—rubygems.org feeds the results of database queries into the `compact_index` API shown in the readme. The `GemVersion` objects are a struct that takes specific gem info as the fields: https://github.com/rubygems/compact_index/blob/da776808d1b22b8ef24259bb8027f2c64a19cdb1/lib/compact_index/gem_version.rb#L5-L6

**Comment by mperham** [comment]
This still feels really specific to Rubygems.org and not something that I can easily integrate into my own system. Would someone on the rg/bundler team be interested in contracting for me and spiking a prototype? Happy to pay the $150/hr standard rate.  Seems like a good feedback cycle for how easy it is for 3rd parties to integrate the Bundler API.

**Comment by indirect** [comment]
Good to know, I'll pass this around to the rest of the team. I think you're right and it would help create something that others could use more easily.

**Comment by sonalkr132** [comment]
> sidekiq-pro 1.9.3,2.0...4,4.0.5 
sidekiq-ent 0.5.0,0.6.0,0.7....7.2,1.8.0,1.8.1

Note this is not correct. versions file should end with the checksum of `info` response.

Try the following and let me know if any issues. You will need to run this any time you make changes to `/gems` dir (ie yank/push):
```ruby
require "rubygems/package"
require "compact_index"

STATIC_RESOURCE_PATH="/home/aditya/rgs/compact_index_static"
gem_dir = Dir[STATIC_RESOURCE_PATH + "/gems/*"]

compact_index_by_gem = {}

gem_dir.each do |gem_file|
  gem_content = File.read(gem_file)
  gem_spec = Gem::Package.new(StringIO.new(gem_content)).spec

  deps = []
  gem_spec.dependencies.each do |dependency|
    reqs = dependency.requirements_list.join(", ")
    deps << CompactIndex::Dependency.new(dependency.name, reqs) if dependency.type.to_s == "runtime"
  end

  name = gem_spec.name.to_s
  number = gem_spec.version.to_s
  platform = gem_spec.original_platform.to_s

  sha256 = Digest::SHA2.base64digest(gem_content)
  sha256_hex = sha256.unpack1("m0").unpack1("H*")

  required_rubygems_version = gem_spec.required_rubygems_version.to_s
  required_ruby_version = gem_spec.required_ruby_version.to_s

  compact_index_version = CompactIndex::GemVersion.new(number, platform, sha256_hex, nil, deps, required_ruby_version, required_rubygems_version)

  if compact_index_by_gem.key?(name)
    compact_index_by_gem[name] << compact_index_version
  else
    compact_index_by_gem[name] = [compact_index_version]
  end
end


compact_index_gem = []

compact_index_by_gem.each do |gem_name, compact_index_version|
  info_checksum = Digest::MD5.hexdigest(CompactIndex.info(compact_index_version))
  compact_index_version.each { |v| v.info_checksum = info_checksum }

  File.open(STATIC_RESOURCE_PATH + "/info/#{gem_name}", "w") { |f| f << CompactIndex.info(compact_index_version) }
  compact_index_gem << CompactIndex::Gem.new(gem_name, compact_index_version)
end

versions_file = CompactIndex::VersionsFile.new STATIC_RESOURCE_PATH + "/versions"
versions_file.create compact_index_gem
```

> I can't get various combinations of .htaccess and <Files "versions"> to output the expected ETag header.

You can try uploading these static files to s3 (which supports range requests) and proxy passing to the bucket URL.

**Comment by mperham** [comment]
@sonalkr132 **Well done!**

I disabled ETag in Apache, ran your script on the Pro and Enterprise repos and ran `bundle` without a Gemfile.lock:

Before: 10s
After: 2.8s

I think I can sign off on Bundler 2.2 and will advocate people upgrade to it!

**Comment by sonalkr132** [comment]
I am glad it worked out for you. I will add this to the compact_index gem at some point. 
>  Would someone on the rg/bundler team be interested in contracting for me and spiking a prototype? Happy to pay the $150/hr standard rate. 

It wasn't that big a task (at least for me) to warrant a contract. If you want, you can donate to [Rubytogther](https://rubytogether.org/developers) whatever it was worth to you :slightly_smiling_face:

**Comment by mperham** [comment]
For anyone coming to this issue: some older versions of Bundler no longer work with the files in place. I know that 1.17 and 2.x do work so anyone who has contacted me has just been told to upgrade. I've heard from two people on 1.13 and one on 1.14; 1.13 is five years old.
