### ISSUE TITLE
Whats the frequency of Sidekiq picking jobs from Redis?

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#4160]
I remember reading somewhere that Sidekiq fetches jobs from Redis every few seconds. Whats the default value and is this value configurable?

I am using the standard version of Sidekiq.

Thanks.

**Comment by mperham** [comment]
Sidekiq’s basic fetcher does not poll, it blocks so picking up jobs should be instantaneous.

**Comment by kapso** [comment]
Excellent, instantaneous is what I was hoping for. Thanks for your amazing work on this 🙏
