### ISSUE TITLE
Undefined method using rescue_from in Mailers

### ISSUE THREAD

**Issue by Bramjetten** [mperham/sidekiq#4161]
Ruby version: 2.2.3
Sidekiq version: 5.2.5

I have a few mailers where I need to rescue exceptions when sending to bounced email addresses. (an exception by Postmark)

```ruby
class LessonMailer < ApplicationMailer
  rescue_from Postmark::InactiveRecipientError, Postmark::ApiInputError, with: :notify_delivery_error
```

This works fine locally, but it *sometimes* fails in production with the following error message:

```
NameError: undefined method `notify_delivery_error' for class `Class'
```

It looks like it can't find a class method `notify_delivery_error`, but I thought it should simply call the instance method that's defined on `LessonMailer`. Is there something I'm missing here?

**Comment by mperham** [comment]
You are using ActiveJob. That’s not a Sidekiq API.
