### ISSUE TITLE
Unique Jobs vs Dead queue

### ISSUE THREAD

**Issue by andersondias** [mperham/sidekiq#4162]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 1.8.1

I've being trying to setup a worker using a specific options setup:

```ruby
class UniqueWorker
  include Sidekiq::Worker

  sidekiq_options retry: 0, unique_for: 1.day, dead: false
  
  def perform(_)
    raise
  end
end
```

I expected to be able to resend the job as it skips dead queue after retries has exhausted. But I keep receiving the following error even though the job can't be find anywhere:

`Skipping enqueue for UniqueWorker, not unique.`

I've assume that once the job skips the dead queue, it's unique lock should be released.

Is there any way to get this to work? Can I help you somehow?

**Comment by mperham** [comment]
Today unique locks are never unlocked except upon success or they expire (after 1 day in your case). Adding a death_handler which expires any lock associated with the job seems reasonable as that feature was added in 5.1. https://github.com/mperham/sidekiq/blob/master/Changes.md#510

**Comment by andersondias** [comment]
Doesn't it make sense to have this as a feature?

I've added the following death_handler to achieve the expected behavior:
```ruby
Sidekiq::Enterprise.unique!

Sidekiq.configure_server do |config|
  config.death_handlers << ->(job, ex) do
    return unless Sidekiq.const_defined?("Enterprise::Unique")
    return if job["dead"].nil? || job["dead"]

    unique_key = job[Sidekiq::Enterprise::Unique::UNIQUE_KEY]
    if unique_key && unique_key.to_i >= 0
      hash = job[Sidekiq::Enterprise::Unique::TOKEN_KEY]
      timestamp = job[Sidekiq::Enterprise::Unique::LOCKED_KEY]

      Sidekiq::Enterprise::Scripting.call(:unique_unlock, ["unique:#{hash}"], [timestamp])
    end
  end
end
```

**Comment by mperham** [comment]
Oh yes, it does! Thank you for the suggestion. Look for it in a future version. In the meantime, I’m happy you could roll your own!

**Comment by andersondias** [comment]
Thank you for that! I'm going to use this snippet in the meantime.

**Comment by andersondias** [comment]
Here is a small patch I've made to the `Sidekiq::Enterprise::Unique::Server` class. There is a little duplication in it and if you're going to unlock the job outside of the Server scope, you will probably need something like that:

```ruby
module Sidekiq
  module Enterprise
    module Unique
      def self.unlock_for(job)
        hash = job[TOKEN_KEY]
        timestamp = job[LOCKED_KEY]

        # Only the job which locked the hash can unlock the hash, since only it
        # should have this exact timestamp
        Sidekiq::Enterprise::Scripting.call(:unique_unlock, ["unique:#{hash}"], [timestamp])
      end

      class Server
        def call(worker, job, queue)
          if job[UNIQUE_KEY] && job[UNIQUE_KEY].to_i >= 0
            policy = job[UNIQUE_UNTIL] || 'success'

            Unique.unlock_for(job) if policy == 'start'

            yield

            Unique.unlock_for(job) if policy != 'start'
          else
            yield
          end
        end

        Sidekiq::Enterprise::Scripting::LUA[:unique_unlock] = <<-LUA
          if redis.call('get', KEYS[1]) == ARGV[1] then
            redis.call('del', KEYS[1])
          end
        LUA
      end
    end
  end
end
```
