### ISSUE TITLE
Update server cert

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4163]
The TLS cert expires October 9th, in 5 months.

**Comment by natematykiewicz** [comment]
Friendly reminder: this is next Wednesday.

**Comment by mperham** [comment]
All active servers are using the new cert as of yesterday. This is only open because I need to destroy the last old server.

**Comment by natematykiewicz** [comment]
Sounds good! I honestly didn’t look into it at all. I just noticed the date and thought “I should remind Mike, just in case.”
