### ISSUE TITLE
Display current time on Sidekiq Dashboard

### ISSUE THREAD

**Issue by aliismayilov** [mperham/sidekiq#4165]
Most of the servers are running on UTC, while none of us officially live in UTC. It'd be helpful to see the current system time on Sidekiq dashboard when comparing timestamps. This information would be useful when looking at Periodic Jobs listing, Next Run column.

I'd like to see if it's a good idea and then move on preparing a pull request for it.

**Comment by mikegee** [comment]
@mperham How do you fee about some javascript in the page changing the user-visible timestamps based on the browser's current time zone, and putting the original UTC time in a `title` attribute so it is visible on hover? I'm pretty sure that's possible.

**Comment by mperham** [comment]
There are no absolute times displayed in the Web UI except for the footer. Everything is relative timing and the title of those elements contains the UTC time stamp. The idea is that those times can be cross referenced with log entries with same time across many machines and many data centers, all using UTC as the common zone. 

I’m not flexible here. No local times.

**Comment by mikegee** [comment]
Relative times with UTC on hover is definitely the way to go. I assumed UTC was more prevalent based on the context of this issue. Thanks for the clarification.

**Comment by Tensho** [comment]
I guess browser extension may easily replace all the datetime fields in the browser's current time zone.

**Comment by aliismayilov** [comment]
I haven't noticed the current UTC timestamp in the footer. That's good enough for me. Thanks for your time!
