### ISSUE TITLE
Could sidekiq incorporate gitlab's forbid_sidekiq_in_transactions feature?

### ISSUE THREAD

**Issue by UniIsland** [mperham/sidekiq#4166]
Enqueueing a job while it's desired data has not been committed to database yet, is a common and easily made mistake, which is addressed in the troubleshooting wiki page.

> Sidekiq is so fast that it is quite easy to get transactional race conditions where a job will try to access a database record that has not committed yet. The clean solution is to use `after_commit`.

I stumble upon a gitlab initializer that raises an error when a job is enqueued inside a transaction: [forbid_sidekiq_in_transactions.rb](https://github.com/gitlabhq/gitlabhq/blob/master/config/initializers/forbid_sidekiq_in_transactions.rb)

Could sidekiq incorporate this feature, for instance raising an error or issuing a warning under such circumstances? It could be an optional configuration that can be enabled manually.

I'm not sure if it is too closely coupled with active_record. Other ORM should have similar issues. If this feature does not fit into core sidekiq, maybe we could use a separate gem.

**Comment by mperham** [comment]
I think this is a very reasonable 3rd party gem but I don’t want it in core.

**Comment by buddhistpirate** [comment]
Another approach to this is to patch ActiveRecord and add a method to sidekiq to delay enqueuing of sidekiq jobs until after the current transaction is finished. 

The more general problem here is to allow delaying of a generic block of code until after the current transaction is finished. We implemented this and then built the ability to use it for sidekiq enqueueing on top of that.
