### ISSUE TITLE
Sidekiq doesn't know objects that are created after a process is started

### ISSUE THREAD

**Issue by krtschmr** [mperham/sidekiq#4168]
240.times do |i|
        sleep(1)
        otp = ->{Sms.otp_from_ref(ref)}.call # tried lambda, also didnt work
        if otp
          break
        else
          p "no OTP found. this was try #{i}"
        end
      end

while this runs in a sidekiq process, i manually create the Sms in another console window.

Sidekiq never finds the Sms.

why is that?

**Comment by mikegee** [comment]
Does `Sms.otp_from_ref(ref)` look in a shared resource like a database or just in Ruby's memory?

**Comment by mperham** [comment]
Sidekiq doesn't know anything about your objects or datastore, it only provides a thread to execute your job.  Perhaps you are running within a transaction and that object is not visible within the current transaction?

**Comment by krtschmr** [comment]
@mikegee  It's an ActiveRecord Object

@mperham i thought so. But my reality looks different.  What i do is, i open a headless browserwindow, create a banktransfer wait for the Sms. The SMS is send to Twilio, who then makes a call to my server via HTTP. I save the content of the Sms. So the SMS is indeed in my database. 

During development, all works fine. Just wenn i run this via sidekiq, the SMS is always unknown and he loops for 4 minutes and dies

**Comment by krtschmr** [comment]
i made you guys a video, showing my problem and this should be easy to replicate

https://www.youtube.com/watch?v=S-GwdTkdRhY&feature=youtu.be

**Comment by krtschmr** [comment]
another way to reproduce

Start sidekiq worker, put `binding.pry` in it. Create objects in a second terminal. They won't be available in the sidekiq process. tried with `sms` but also with `Devise User`.

If the object is created within the sidekiq process, sidekiq knows it.

what really confuses me: 

- run sidekiq, halt it with `binding.pry`
- create outside `3 User`
- `User.count` will return 0 in sidekiq process
- create `User` within pry
- now `User.all` returns all 4 user 

really weired, but it's reproduceable

**Comment by krtschmr** [comment]
the fix for my problem is, to just try to create a nonvalid object `User.create` and then sidekiq knows all new objects that came to the database during runtime.

**Comment by mperham** [comment]
That’s definitely a transaction visibility issue and should have nothing to do with Sidekiq. Try repro’ing the problem with two pry consoles.

**Comment by krtschmr** [comment]
btw, the solution is to call `.uncached` on your ActiveRecord model
```
Sms.uncached do
  Sms.find_by ....
end
```
