### ISSUE TITLE
Redis connection refused when using sidekiq in production EC2

### ISSUE THREAD

**Issue by LuckyGStar** [mperham/sidekiq#4170]
Ruby version: ruby 2.6.0p0
Sidekiq version: 5.2.7
Redis version: redis (4.1.1)

I am deploying rails project into Amazon EC2, and it uses active_storage for file uploading. 
But after deployment I get redis connection refused error. Here is the log info. 

Completed 500 Internal Server Error in 25ms (ActiveRecord: 2.9ms)
F, [2019-05-18T14:48:53.547843 #2050] FATAL -- : [67c3c32a-63f4-4cc3-87c0-35f25bc82020]
F, [2019-05-18T14:48:53.547875 #2050] FATAL -- : [67c3c32a-63f4-4cc3-87c0-35f25bc82020] Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
F, [2019-05-18T14:48:53.547895 #2050] FATAL -- : [67c3c32a-63f4-4cc3-87c0-35f25bc82020]
F, [2019-05-18T14:48:53.547914 #2050] FATAL -- : [67c3c32a-63f4-4cc3-87c0-35f25bc82020] app/controllers/designs_controller.rb:46:in `block in update'
[67c3c32a-63f4-4cc3-87c0-35f25bc82020] app/controllers/designs_controller.rb:45:in `update'

I think this is related to redis configuration because active_storage uses sidekiq for active_job_queue but not sure how to fix this issue. 

I have used *rbenv-vars* library for ENV vars. Here is redis uri, I set in production. 
REDIS_URL=redis://127.0.0.1:6379/0?password=deploy

Here is my config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { url: (ENV["REDIS_URL"] || 'redis://localhost:6379/0') }
end

Sidekiq.configure_client do |config|
  config.redis = { url: (ENV["REDIS_URL"] || 'redis://localhost:6379/0') }
end

Looking for your help. 

Regards

**Comment by mperham** [comment]
`Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379)`

Sounds like you need to start Redis?

**Comment by LuckyGStar** [comment]
Hello @mperham Thank you for your response. I have already restarted redis service and it works well. PIng is also working with redis.
