### ISSUE TITLE
I want Sidekiq to support multiple dynamic databases

### ISSUE THREAD

**Issue by ashishprajapati** [mperham/sidekiq#4172]
**I want Sidekiq to support multiple dynamic databases for the same project**

```ruby
desc "Start sending the client invitation"

task "sidekiq:start", [:database] => :environment do |task, args|
  database = args[:database]
  config = ActiveRecord::Base.establish_connection(
     :adapter  => "postgresql",
     :host     => "localhost",
     :username => "postgres", 
     :password => 12345678,
    :database => database
  )

  puts "Start Running Sidkiq Server for new database instance - #{database}"
  system("bundle exec sidekiq -d -L log/sidekiq.log -P tmp/pids/#{database}_sidekiq.pid")
  puts "Finished Running Sidkiq Server for new database instance - #{database}"

  puts "Finished connecting the client sidkiq"

end
```

```
rake sidekiq:start[hellodb]
```

Is there any thing within sidekiq to pass database configuration dynamically ? 
* It's always taking the database configuration from database.yml, even I used this establish_connection method. I want it to support database configurations dynamically. 
* Basically, I am using multiple databases in my project depending on the sub domains. There, I am using same project but using multiple databases dynamically. So, I am looking for some ability that may allow using multiple sidekiq instances for different databases. 
```
  config = ActiveRecord::Base.establish_connection(
     :adapter  => "postgresql",
     :host     => "localhost",
     :username => "postgres", 
     :password => 12345678,
    :database => database
  )
```

I will appreciate community views on the same :)

**Comment by ashishprajapati** [comment]
@mperham  :) If you have few seconds then please guide me over it. I am working on one of the big project. Thanks :)

**Comment by mperham** [comment]
Sidekiq doesn't know anything about databases.  You are trying to dynamically configure ActiveRecord.  Take a look at Apartment. https://github.com/influitive/apartment-sidekiq/
