### ISSUE TITLE
Missing CSRF protection in Live Poll [Security Issue]

### ISSUE THREAD

**Issue by Shashank-In** [mperham/sidekiq#4175]
Hi!
I was doing a security audit of my client who was using 
```
Sidekiq 4.2.9 / Pro 3.4.5 / Ent 1.3.2
```
I realized that the "Live Poll" feature is vulnerable to CSRF attacks. So a malicious attacker can  initiate a "Live Poll" by making the victim user click on something like 

```
https://somewebsite.com/sidekiq/batches?poll=true
```

I checked the code and realized there is no anti-CSRF token being asked.
```
https://github.com/mperham/sidekiq/blob/master/web/views/_poll_link.erb
```
Meanwhile, all the other features do have anti-CSRF protection.

**Comment by mperham** [comment]
Thanks, this is really by design.  Add the poll parameter to any Web UI link and it will live update.  Please let me know if you can think of any malicious threat vector.

**Comment by Shashank-In** [comment]
@mperham The feature you said could have been implemented using CORS policies. I think removing the CSRF tokens is not the correct option. Let me know what you think.
