### ISSUE TITLE
Sidekiq is slow on Mongoid operations

### ISSUE THREAD

**Issue by kooinam** [mperham/sidekiq#4176]
Ruby version: 2.5
Sidekiq / Pro / Enterprise version(s): N/A

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

I have operations involving simple Mongoid insert and update that would take up to 2 seconds in Sidekiq which normally resolved in foreground within ~200ms. Is this an expected behavior? I am using Mongoid 6 and not using Kiqstand

**Comment by UlfR** [comment]
i have same problem on sidekiq 5.2.7 and mongoid 6.1.1

**Comment by WeiGangqiang** [comment]
i have same problem too
