### ISSUE TITLE
Free Threads Not Being Used

### ISSUE THREAD

**Issue by kceb** [mperham/sidekiq#4177]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq v4.2.10

Please include your initializer and any error message with the full backtrace.
```
# frozen_string_literal: true

Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

redis_conn =  {
    url: "rediss://:#{ENV['REDIS_AUTH_TOKEN']}@#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/12", password: ENV['REDIS_AUTH_TOKEN'],
}

Sidekiq.configure_server do |config|
  config.redis = redis_conn

  config.on(:startup) do
    Rails.logger.info "Starting up Sidekiq... #{Time.now}"
  end

  config.on(:quiet) do
    Rails.logger.info "Got TSTP, stopping further job processing... #{Time.now}"
  end

  config.on(:shutdown) do
    Rails.logger.info "Got TERM, shutting down process.... #{Time.now}"
  end
end

Sidekiq.configure_client do |config|
  config.redis = redis_conn
end

Sidekiq::Logging.logger = Rails.logger
Sidekiq::Logging.logger.level = ENV.fetch("LOG_LEVEL") { Logger::INFO }
```
Are you using an old version?
Yes
Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes

Issue:

I was wondering if there was a common cause for unused threads. I checked the CPU utilization of the instance, and it's relatively low (~30%)

![Sidekiq](https://cdn-std.dprcdn.net/files/acc_650298/wEbQGB)

Note that I am using the typhoeus gem which has been documented to crash: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting, and I'm currently trying to see if that is the issue.

**Comment by mperham** [comment]
Perhaps those jobs are enqueued in a different queue that those processses don’t fetch from?

**Comment by kceb** [comment]
> Perhaps those jobs are enqueued in a different queue that those processses don’t fetch from?

Unfortunately, not the case. If I manually autoscale up the instances and add 5 more instances, the jobs get processed and eventually the queue empties.

**Comment by mperham** [comment]
Bump up to Sidekiq 5 and I’ll help you further. I’m not really supporting 4 anymore.

**Comment by mperham** [comment]
Here's another common cause of low thread utilization, you'll see low CPU if you are only utilizing one core per machine: https://www.mikeperham.com/2019/07/19/something-for-nothing/

**Comment by RaresSalcudean** [comment]
@mperham I don't want to hijack this thread but I believe the same issue applies to me as well:

Sidekiq - 5.2.7

<img width="1244" alt="Screenshot 2019-08-06 at 17 27 11" src="https://user-images.githubusercontent.com/29229646/62548528-9c058980-b86f-11e9-84ee-1664cfb84aab.png">

<img width="1258" alt="Screenshot 2019-08-06 at 17 32 31" src="https://user-images.githubusercontent.com/29229646/62548893-3665cd00-b870-11e9-876a-7b8d504a5c5d.png">

The workers don't use all the available threads.

Side question: Even doe job processing works properly and I have no issues to get the jobs done. I have no idea why my Enqueued stats who 0. In the image from above, there are 3 million jobs enqueued.

**Comment by mperham** [comment]
@RaresSalcudean Read the blog post linked above your comment.

**Comment by kceb** [comment]
Seems like the issue disappeared for me. Not sure what fixed it. Closing for now

**Comment by 9mm** [comment]
@kceb are you still using typheous OK? Im having difficulty finding an ACTUAL thread safe http library. I was going to use typheous (not hydra feature) to simply issue a `Typhoeus.post(url)`. have you found this works OK?
