### ISSUE TITLE
Sidekiq Enterprise Mutliprocess Question

### ISSUE THREAD

**Issue by michaeldiscala** [mperham/sidekiq#4180]
Hi there -

We're trying to decide whether to upgrade to sidekiq-enterprise for some of the multiprocess features and were hoping for a little bit more insight into the debugging and monitoring features that it supports. For example, is it possible for us to log out per process memory statistics (so we can distinguish if we have a problem w/ a single process blowing up memory or if all of them are using the same amount)? How are process crashes reported/logged? Are there any other nice-things that enterprise provides in terms of visibility into the processes running on the server? 

Thanks,
--Mike

**Comment by mperham** [comment]
Hi Mike, we can talk back and forth and send pointers to various docs but I think it would be better for you to trial it:

1. Buy a $179 license here: https://billing.contribsys.com/sent/new.cgi
2. Try it out for 14 days.
3. If it doesn't meet your needs, email me for a refund.  If it works for you, email me to adjust the license to meet your concurrency needs long-term.  I'm mike@contribsys.com.

If you have suggestions for how to improve multi-process visibility, I'd welcome any feedback. Don't be afraid to add comments here and I'd be happy to help you work through more specific issues.

**Comment by michaeldiscala** [comment]
That's fair! Will do thanks!
