### ISSUE TITLE
Update Bootstrap and normalize.css to the latest version

### ISSUE THREAD

**Issue by Medvezo** [mperham/sidekiq#4183]
Current version of a Bootstrap library is 3.3.7. Update it to the latest version, which is [4.3.1](https://getbootstrap.com/docs/4.3/getting-started/introduction/)

Current version of a normalize.css (embedded in a bootstrap.css file) is 3.0.3, latest version is [8.0.1](https://github.com/necolas/normalize.css)

**Comment by mikegee** [comment]
Would you like to make the PR and get them working? I’m concerned there’s a bunch of tedious work getting those updated.

**Comment by mperham** [comment]
As Mike points out, this is a lot of work. It's not going to happen unless someone else feels it necessary or can give me good reason(s) how Sidekiq's users would benefit.

**Comment by Medvezo** [comment]
@mperham sooner or later you will have to move on from these versions (jquery included), which won't be maintained for years at that point. The more you put off, the harder it gets to update. Just take a look at CVEs for [bootstrap](https://www.cvedetails.com/vulnerability-list/vendor_id-19522/product_id-51406/Getbootstrap-Bootstrap.html) and [jQuery](https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html).

Now I dont know if exposing your users to XSS vulnerabilities is a good enough reason for you.

@mikegee more than happy to contribute, but I have never used bootstrap.
