### ISSUE TITLE
Status does not seem to have a parent_bid 

### ISSUE THREAD

**Issue by ritec** [mperham/sidekiq#4184]
Ruby version: `2.4.3`
Sidekiq / Pro / Enterprise version(s): `Enterprise 1.6.0`

When initiating a batch callback, I see the documentation asks to reference the `status.parent_bid` in order to generate nested batches however my `status` does not have a `.parent_bid` it does have a `bid` Am I missing something? Is the `.bid` the same as the `parent_bid`?

```
[1] pry(#<Some::SchedulerJob>)> status
=> #<Sidekiq::Batch::Status:0x00007f9c8935b920
 @bid="xYOoNJ4Clm_IPg",
 @callbacks={"success"=>[{"Some::SchedulerJob#call"=>{}}]},
 @completed=0,
 @failures=0,
 @pending=0,
 @props={"description"=>"Notifier Batch", "callbacks"=>"{\"success\":[{\"Some::SchedulerJob#call\":{}}]}", "pending"=>"0", "kids"=>"0", "created_at"=>"1559686858.678839", "total"=>"1"},
 @total=1>
```

**Comment by mperham** [comment]
Sounds like the batch that finished has no parent then. Are you saying it does? Have you seen the same behavior in the latest version?

**Comment by ritec** [comment]
I will close this issue, ended up adding jobs dynamically to the batch as opposed to using the callbacks.
