### ISSUE TITLE
[Request] Sidekiq::Client#push_bulk + perform_in/perform_at

### ISSUE THREAD

**Issue by danielnc** [mperham/sidekiq#4187]
Hi Mike,

Wondering if it would be possible to do a push_bulk for perform_in/at.

I am a pro & ent user so having that as a paid functionality would be great for me aswell

Do you see any pros and cons?

Another suggestion is, there is a gem that makes the interface to push_bulk a lot easier and I've been relying on it, if sidekiq her a more user-friendly interface that would be great too:
https://github.com/CareMessagePlatform/sidekiq-bulk

**Comment by mperham** [comment]
That’s a private repo so I can’t see it. 

If you have a suggested API, show me. I’m not against it, just don’t know how popular it would be.

**Comment by danielnc** [comment]
sorry @mperham 

This is the API

```
FooJob.push_bulk([1, 2, 3])
```

and for multiple args:

```
FooJob.push_bulk(all_users) do |user|
  [user.id, "foobar"]
end

# enqueues one job for each element of `all_users`, where each job
# has two arguments: the user ID and the string "foobar".
#
# equivalent to, but faster than:

all_users.each do |user|
  FooJob.perform_async(user.id, "foobar")
end
```


As ar as the push_bulk with perform_in/at do you think its possible?

**Comment by mperham** [comment]
It's technically possible because ZADD can handle multiple args. https://redis.io/commands/zadd But no one has proposed an API and I've never needed it before.  I think one other person has suggested it before.

**Comment by danielnc** [comment]
This would be really good for our product since we have lots of jobs that are enqueued in bulk and we've been using push_bulk but right now we can't do anything for the ones we have delayed 

Let me know if its something you think you can add to one of the versions of sidekiq pro, or if I should work on creating a standalone gem

**Comment by mperham** [comment]
I wouldn't consider this a commercial feature; I'd be happy to see it worked on publicly and roll it into core.  If you want to start a PR, that would be a huge boost.

**Comment by mperham** [comment]
Just merged.

**Comment by danielnc** [comment]
Thank you!!
