### ISSUE TITLE
DB connection leak after removal of AR middleware

### ISSUE THREAD

**Issue by lifeBCE** [mperham/sidekiq#4188]
Ruby version: `2.5.1`
Rails version: `5.2.3`
Sidekiq / Pro / Enterprise version(s): `5.2.7`

Recently upgraded from sidekiq `5.2.5` to `5.2.7` and instantly starting having issues with database connection leaks. I noticed that you removed the active record middleware in `5.2.6` that used to ensure connections checked out in sidekiq threads were properly checked back in. It seems as though the understanding was that rails 5 handles this now via the reloader and that seemed to be true prior to rails 5.2. That logic that [cleared connections](https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/query_cache.rb#L46-L50) inside the executor block is [no longer present](https://github.com/rails/rails/blob/536a190ab3690810a3b342b897f2585c4971229d/activerecord/lib/active_record/query_cache.rb#L48). Looks like it was refactored a bit and moved to the [complete method](https://github.com/rails/rails/blob/536a190ab3690810a3b342b897f2585c4971229d/activerecord/lib/active_record/query_cache.rb#L43).

Our solution was to wrap each of our jobs in a `with_connection` block AND set an ensure to do what the old middleware used to do. Long term we will probably monkey patch (or alias method chain) back in that middleware so we can keep our job classes a bit cleaner.

You may want to consider bringing that middleware back just for sanity sake. This was also a total surprise to us that a breaking change would be introduced in a patch release. Pessimistic versioning using the ole twiddle wakka will not protect from this.

**Comment by mperham** [comment]
Cc @matthewd

**Comment by mperham** [comment]
A concern: Why is no one else complaining of this problem?

**Comment by matthewd** [comment]
@lifeBCE 👋🏻

I see you already found where the connection-clearing moved to... could you elaborate on why its new location would make it less effective?

Is your application doing anything relevant? (e.g. changing default executor behaviour, changing query cache handling, manually managing database connections)

**Comment by lifeBCE** [comment]
@matthewd Our assumption at this point is the leaks happen now when an exception is raised in the processing of the job. It seems that method that contains the moved logic is not called in those instances?

Our jobs are not doing any of those things mentioned (db con management, changing executor or query caching)

**Comment by lifeBCE** [comment]
Apologies gentlemen, I had some time to dig into this issue this last week and it turned out to have nothing to do with sidekiq. Was a misconfiguration in our logic that dealt with a secondary database connection pool. We did not allow enough connections in that pool to account for all sidekiq threads.

Closing this as invalid.
