### ISSUE TITLE
Unable to supply credentials for sidekiq enterprise gem install in Dockerfile

### ISSUE THREAD

**Issue by bpirtle-nova** [mperham/sidekiq#4190]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq (4.2.10), sidekiq-ent (1.6.1), sidekiq-pro (3.7.1)

```
# config/initializers/sidekiq.rb

Sidekiq.hook_rails!
Sidekiq.remove_delay!

#Sidekiq.default_worker_options = { 'backtrace' => true }

Sidekiq::Client.reliable_push! unless Rails.env.test?

#Second resolution for checking for scheduled jobs, plus reliable scheduler and super fetch
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://REDACTED@nova-redis-prod-east.redis.cache.windows.net:6379', network_timeout: 5 }

  config.average_scheduled_poll_interval = 1 #seconds
  config.super_fetch!
  config.reliable_scheduler!

  config.periodic do |mgr|
    mgr.register('* * * * *', HubspotCronWorker)
    mgr.register('* * * * *', NotificationCronWorker)
    #mgr.register('* * * * *', PersonalizationCronWorker)
    mgr.register('* * * * *', SendCronWorker)
    mgr.register('* * * * *', RefreshCronWorker)
  end
end

Sidekiq::Limiter.configure do |config|
  # job is the job hash, 'overrated' is the number of times we've failed due to rate limiting
  # limiter is the associated limiter that raised the OverLimit error
  # https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting
  # https://github.com/mperham/sidekiq/issues/2168

  config.backoff = ->(limiter, job) do
    rand(80..100).to_f / 100 * (job['overrated'] ** 1.1)
  end
end
```
When I tried to dockerize my app (Just an image to run sidekiq) I was getting a 401 error from the Sidekiq gem servers when it tried to run bundle install during the build process.

I tried all of the methods listed in the original email for giving the bundler our sidekiq enterprise credentials, as follows, but none of them worked and I kept getting a 401:

1. bundle config enterprise.contribsys.com <name>:<pass> (In Dockerfile before bundle install)
2. BUNDLE_ENTERPRISE__CONTRIBSYS__COM=<name>:<pass> (In .env file verified in docker config)
3. bundle config --local enterprise.contribsys.com <name>:<pass> (In Dockerfile before bundle install)

Then, I found this: https://github.com/johaywood/docker-sidekiq-ent-web/blob/master/Gemfile

This method worked with just bundle install and no need to set up any config in the bundler.

My question is, any ideas why these other methods didn't work properly? I am using Docker for mac and docker-compose up --build using these files:

Dockerfile:
```
FROM ruby:2.1.3

RUN mkdir /app
WORKDIR /app

COPY . .

COPY Gemfile Gemfile.lock ./

RUN bundle config enterprise.contribsys.com <name>:<pass>

RUN bundle install --binstubs

LABEL maintainer="Bryan Pirtle <bryan@nova.ai>"

CMD puma -C config/puma.rb
```

docker-compose.yml
```
version: '2'

services:
  sidekiq:
    build: .
    command: sidekiq -q long -c 10 -t 25
    volumes:
      - '.:/app'
    env_file:
      - '.env'
```

**Comment by mperham** [comment]
I don't use Docker heavily so I can't claim to have deep knowledge here.  Does anyone else using Docker have ideas?  I believe `bundle config --local` will create a file with the creds; I believed that further Docker commands should see that file on the filesystem so I'm not clear why this isn't working.

It would be useful to have a Docker wiki page with tips for containerizing Sidekiq + how to use the commercial versions within those containers but I'll leave that for someone with more Docker expertise than I.

**Comment by kenichi** [comment]
🤔  https://github.com/docker-library/ruby/issues/129 might have something to do with it. perhaps try unsetting `BUNDLE_APP_CONFIG`?

**Comment by kreek** [comment]
We use the 2nd method (settings an env var) above for [vets-api](https://github.com/department-of-veterans-affairs/vets-api). I'm actually on vacation right now 🌴 or I'd dig in further but feel free to browse our docker files 😄

**Comment by nevalla** [comment]
To use env variables during docker build you should use build arguments:

docker-compose.yml
```yaml
...
  sidekiq:
    build:
      context: .
      args:
        ENT_USERNAME: <username>
        ENT_PASSWORD: <password>
...
```

And then reference these arguments in `Dockerfile`:
```Dockerfile
FROM ruby:2.1.3
ARG ENT_USERNAME
ARG ENT_PASSWORD
ENV ENT_USERNAME ${ENT_USERNAME}
ENV ENT_PASSWORD ${ENT_PASSWORD}
...
```

Docker Compose will use `.env` file [automatically](https://docs.docker.com/compose/environment-variables/#the-env-file) so you can actually reference those variables in docker-compose.yml if you want:

```yaml
...
  sidekiq:
    build:
      context: .
      args:
        ENT_USERNAME: ${ENT_USERNAME}
        ENT_PASSWORD: ${ENT_PASSWORD}
...
```
(Assuming that `.env` file contains those variables.)

**Comment by bpirtle-nova** [comment]
Hey guys, thank you for all the ideas! I tried using the vets-api info from the repo to modify the Dockerfile and docker-compose.yml to the following:

Dockerfile:
```
FROM ruby:2.1.3

ARG sidekiq_license
ENV BUNDLE_ENTERPRISE__CONTRIBSYS__COM=$sidekiq_license

RUN mkdir /app
WORKDIR /app

COPY . .

COPY Gemfile Gemfile.lock ./

RUN bundle install

LABEL maintainer="Bryan Pirtle <bryan@nova.ai>"

CMD puma -C config/puma.rb
```

docker-compose.yml
```
version: '3'

services:
  sidekiq:
    build:
      context: .
      args:
          sidekiq_license: "${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
    command: sidekiq -q long -c 10 -t 25
    volumes:
      - '.:/app'
    env_file:
      - '.env'
```

Result of docker-compose config:
```
$ docker-compose config
services:
  sidekiq:
    build:
      args:
        sidekiq_license: <my license shown here>
      context: /Users/bryanpirtle/nova-backend
    command: sidekiq -q long -c 10 -t 25
    environment:
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: <my license shown here>
      sidekiq_license: <my license shown here>
    volumes:
    - /Users/bryanpirtle/nova-backend:/app:rw
version: '3.0'
```

Here is the build command and output (Still a failure to authenticate I'm afraid):
```
$ docker-compose up --build
Building sidekiq
Step 1/10 : FROM ruby:2.1.3
 ---> e1f10119c75a
Step 2/10 : ARG sidekiq_license
 ---> Using cache
 ---> 831cda76a426
Step 3/10 : ENV BUNDLE_ENTERPRISE__CONTRIBSYS__COM=$sidekiq_license
 ---> Using cache
 ---> 189c82727c3b
Step 4/10 : RUN mkdir /app
 ---> Using cache
 ---> 2848806c7eee
Step 5/10 : WORKDIR /app
 ---> Using cache
 ---> 6792d7b86b49
Step 6/10 : COPY . .
 ---> 233347f5ec92
Step 7/10 : COPY Gemfile Gemfile.lock ./
 ---> 3eacda2ddc55
Step 8/10 : RUN bundle install
 ---> Running in 8bc662f1967d
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Your Gemfile lists the gem cld (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching source index from https://enterprise.contribsys.com/
Fetching source index from https://enterprise.contribsys.com/
Fetching source index from http://rubygems.org/
Resolving dependencies.................
Authentication is required for Net::HTTPUnauthorized: <!DOCTYPE HTML PUBLIC
"-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at enterprise.contribsys.com Port
443</address>
</body></html>
.
Please supply credentials for this source. You can do this by running:
bundle config Net::HTTPUnauthorized: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML
2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at enterprise.contribsys.com Port
443</address>
</body></html>
 username:password
ERROR: Service 'sidekiq' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 17
```

**Comment by mperham** [comment]
If you can run a command inside the Docker image, try running `bundle config` or `DEBUG=1 bundle` to see the current environment.

**Comment by mayuresh-srivastava** [comment]
Seriously [this](https://github.com/johaywood/docker-sidekiq-ent-web/blob/master/Gemfile) worked like a charm.

**Comment by kennethteh90** [comment]
I know this issue is closed, but if anyone stumbles upon this (as I did) while trying to run Sidekiq Pro in a Dockerfile orchestrated by `docker-compose`, here is what I did:

```
# docker-compose.yml

services:
  my_service:
    build:
      args:
        BUNDLE_GEMS__CONTRIBSYS__COM: $BUNDLE_GEMS__CONTRIBSYS__COM
```
This reads the environment variable from your host environment, so it's likely only useful for local development. 

```
# Dockerfile

ARG BUNDLE_GEMS__CONTRIBSYS__COM

```

The benefit of this setup is that you can do something like `echo export BUNDLE_GEMS__CONTRIBSYS__COM=<username>:<password> >> ~/.zshrc` and your local `bundle install` will work too.

You can do something similar for enterprise (the ENV name will change to `BUNDLE_ENTERPRISE__CONTRIBSYS__COM`)

**Comment by kwent** [comment]
That also took me a while to figure it out. If using multi stage build you'll need to do

```
ONBUILD ARG BUNDLE_ENTERPRISE__CONTRIBSYS__COM
ONBUILD ENV BUNDLE_ENTERPRISE__CONTRIBSYS__COM="${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
```

**Comment by marckohlbrugge** [comment]
For anyone using [Kamal](https://kamal-deploy.org):

```yml
# ./config/deploy.yml
# Add the secrets to your builder config in

builder:
  secrets:
    - BUNDLE_ENTERPRISE__CONTRIBSYS__COM
```

```Dockerfile
# ./Dockerfile
# Replace the `bundle install` step in your Dockerfile with this:

COPY Gemfile Gemfile.lock ./
RUN --mount=type=secret,id=BUNDLE_ENTERPRISE__CONTRIBSYS__COM \
    BUNDLE_ENTERPRISE__CONTRIBSYS__COM=$(cat /run/secrets/BUNDLE_ENTERPRISE__CONTRIBSYS__COM) \
    bundle install && \
    rm -rf /usr/local/bundle/cache
```
