### ISSUE TITLE
statsd 4.2 gem is not compatible with pro statsd middleware

### ISSUE THREAD

**Issue by dahlb** [mperham/sidekiq#4191]
Ruby version: 2.5
Sidekiq / Pro / Enterprise version(s): 5.2.7 / 4.0.5

Please include your initializer and any error message with the full backtrace.

ArgumentError: :client option no longer accepted
statsd.rb  29 initialize(...)
[GEM_ROOT]/gems/sidekiq-pro-4.0.5/lib/sidekiq/middleware/server/statsd.rb:29:in `initialize'

Are you using an old version? no

statsd 4.2 gem is not compatible with pro statsd middleware

**Comment by mperham** [comment]
Please show your initializer. I don’t think you are initializing statsd correctly in Pro 4.x

**Comment by dahlb** [comment]
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    require 'datadog/statsd' # gem 'dogstatsd-ruby'
    chain.add Sidekiq::Middleware::Server::Statsd, client: Datadog::Statsd.new("statsd-svc.monitoring", 9125, tags: ["env:#{Rails.env}"])
  end
end

**Comment by dahlb** [comment]
sorry I see the difference in the wiki now

**Comment by dahlb** [comment]
thank you
