### ISSUE TITLE
Rails 6 + DEPRECATION WARNING: Initialization autoloaded the constants...

### ISSUE THREAD

**Issue by philipbjorge** [mperham/sidekiq#4192]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 5.2.7

In our initializers/sidekiq.rb:
```
  config.periodic do |mgr|
    mgr.register("2-59/10 * * * *", FullReindexWorker, "args" => ["Product"])
  end
```

With Rails 6.RC1, we're seeing the following deprecation notice.

```
DEPRECATION WARNING: Initialization autoloaded the constants FullReindexWorker

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload FullReindexWorker, for example,
the expected changes won't be reflected in that stale Class object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```

---

Do you know what the resolution is on this? We've resolved this in other initializers by requiring the dependency explicitly, but we don't care or expect reloading to work for these.

What's the status of sidekiq hot reloading in Rails 6?

**Comment by mperham** [comment]
Reloading does not work for constants that are loaded during initialization, which is the pattern that Enterprise's cron jobs uses today.  I will likely change the API slightly to do this:

```ruby
config.periodic do |mgr|
  mgr.register("2-59/10 * * * *", :FullReindexWorker, "args" => ["Product"])
end
```

In a future version, using a symbol to denote the class will tell Sidekiq Enterprise to constantize the symbol every time the job should fire which should play well with Rails 6.  Today Sidekiq Enterprise only supports the class name directly or a String, which it does not try to constantize (because the Sidekiq process might not have direct access to the source code for that job class).

**Comment by mperham** [comment]
Note you can fix this today by using the String instead (`"FullReindexWorker"`) but the issue is that any fired jobs will not include the `sidekiq_options` declared in the class definition.

**Comment by mperham** [comment]
I can't reproduce this deprecation warning with 6.0rc1.  Did you enable some flag or log level?  If I can repro it, I can fix it.

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    mgr.register "* * * * *", ScheduledWorker, retry: 1
    mgr.register "*/4 * 10 * *", ScheduledWorker, retry: 2
  end
end
```

**Comment by philipbjorge** [comment]
I am unaware of any changes to the log level or flags.
I can try and make a minimal repro for you.

```
DEPRECATION WARNING: Initialization autoloaded the constants FullReindexWorker, SyncModifiedWordpressPostsWorker, and RefreshMaterializedViewWorker.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload FullReindexWorker, for example,
the expected changes won't be reflected in that stale Class object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/philip.bjorge/Leafly-com/consumer-api/config/environment.rb:5)
```

**Comment by mperham** [comment]
Haven't been able to reproduce this in order to redesign the API.  Please feel free to open a new issue if you see this in Rails 6.0.
