### ISSUE TITLE
Safe to delete batch after calling invalidate_all?

### ISSUE THREAD

**Issue by philipbjorge** [mperham/sidekiq#4194]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 5.2.7

Is the following code snippet safe to use?

```
batch = Sidekiq::Batch.new(bid)
batch.invalidate_all
batch.status.delete
```

> Deleting a batch will break Sidekiq if there are still jobs associated with that batch in Redis.

All of our batch jobs have the appropriate `valid_within_batch?` handling inside them...  But I'm guessing the above snippet is still unsafe because the jobs are still associated with the batch?

Thanks

**Comment by philipbjorge** [comment]
For some additional context...

We have a job that runs on a schedule and creates a batch to rebuild an elasticsearch index. At the start of this job, we check if there is an identical batch already running and if so we don't schedule it because concurrent rebuilding of this index has the potential to cause problems.

This has been working fine until we got hit by a -1 pending job and we are now looking to add a reconciliation step to the worker that will invalidate and possibly delete the stuck batch so we can schedule a new one.

---

I would like to know the answer to the above question, but am also open to advice on the above problem.

Thanks!

**Comment by mperham** [comment]
It's an implementation detail but that should be safe.  The valid check uses Redis data structures directly and should return false if the batch has been invalidated or deleted.
