### ISSUE TITLE
Retry attribute cannot be set in distributed system

### ISSUE THREAD

**Issue by fzf** [mperham/sidekiq#4196]
Ruby version:
Sidekiq: 5.2.27

We are utilizing [Sidekiq::Client.push](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/client.rb#L69) to enqueue jobs over service boundaries. Due to this we don't have class definitions while enqueuing. This means that the `Sidekiq.default_worker_options` sets the retry count for a given job even if retry is explicitly set to nil in the push call. This would be okay if processing consulted the worker class when making decisions about retry but unfortunately it [only checks the worker if retry is nil](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/job_retry.rb#L119), which we have already established is a near impossible state to be in. 
Even in the case that we are able to force retry to be nil by setting `Sidekiq.default_worker_options['retry'] = nil` we will now run into another issue. Unless retry is set for every worker independently it won't fall back to the services Sidekiq retry default. It seems to me that the retry threshold is the responsibility of the worker class. I would suggest that instead of setting it to the global default of the service that is enqueuing, it we should be able to set it to nil and allow processing to use that nil value as a flag to check the worker or default to [`@max_retries`](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/job_retry.rb#L67). I am happy to open a pull request if that helps.

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

**Comment by mperham** [comment]
Can you clear out `Sidekiq.default_worker_options` or remove the `retry` key so it can't screw up the push?

RE: changes https://github.com/mperham/sidekiq/wiki/Error-Handling#no-more-bike-shedding
