### ISSUE TITLE
Sidekiq Pro Batches Callback not working with ActsAsTenant Gem

### ISSUE THREAD

**Issue by manishankar2** [mperham/sidekiq#4197]
I am trying to send an email after exporting data using Sidekiq Batch callback. But The Job Sidekiq::Batch::Callback is getting failed because ActsAsTenant.current_tenant is set as nil while enqueueing this job. Basically, everytime when we enqueue a job we will set current_tenant as account. But the batch callback job doesn't do that because it runs by default. Is there a way this can be set in the Callback job. ?

**Comment by mperham** [comment]
Could you show me the two DEBUG lines that print the active middleware when you start Sidekiq with -v?

**Comment by manishankar2** [comment]
Client Middleware: Sidekiq::Batch::Client, ActsAsTenant::Sidekiq::Client, Sidekiq::CurrentUser::Client, Sidekiq::CurrentRequest::Client
Server Middleware: Sidekiq::Batch::Server, NewRelic::SidekiqInstrumentation, Sidekiq::Sharding::Server, ActsAsTenant::Sidekiq::Server, Sidekiq::CurrentAccount::Server, Sidekiq::CurrentRequest::Server, Sidekiq::CurrentUser::Server

**Comment by manishankar2** [comment]
This is the Act as Tenant Client class. Whenever we enqueue any job  ActAsTenant.current_tenant is always set. Even if I change the order of middleware(i.e. ActAsTenantClient enqueued before batch client ) I am worried that current_tenant will not be set. 
`class Client
    def call(worker_class, msg, queue, redis_pool)
      msg['acts_as_tenant'] ||=
        {
            'class' => ActsAsTenant.current_tenant.class.name,
            'id' => ActsAsTenant.current_tenant.id
        } if ActsAsTenant.current_tenant.present?

      yield
    end
  end`

**Comment by mperham** [comment]
Your tenant server needs to come before the batch server middleware.

**Comment by manishankar2** [comment]
Hi @mperham , Thanks a lot it works !.  
One question, Let's say there is a master job which splits into number of batches and enqueues multiple child jobs. Will the batch callback success run at end of success of all the child job ?. If so, will they use same queue as the child job ?.

**Comment by mperham** [comment]
I assume you are talking about nested batches.  If you nest them properly, yes, the callbacks should fire in reverse order (the child's callbacks fire first, then the parents).  See the Complex workflows wiki page for example.
