### ISSUE TITLE
Using the same limiter with different timeouts?

### ISSUE THREAD

**Issue by philipbjorge** [mperham/sidekiq#4198]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 5.2 / 1.8.1 / 4.0.5

Hi @mperham 

We have two areas of code that we would like to protect with the same concurrent limiter -- In the `#perform` method of a worker that creates a batch and the batch's `#success` callback.

Is it possible to use the same limiter, but specify different timeouts?
 
We expect that the `#perform` method could take longer than the `#on_success` method and would like to avoid holding a lock longer than necessary if we know we don't need to.

```
Sidekiq::Limiter.concurrent("some_lock", 1, wait_timeout: 0, lock_timeout: 30.seconds)

Sidekiq::Limiter.concurrent("some_lock", 1, wait_timeout: 0, lock_timeout: 10.minutes)
```

Thanks again

**Comment by mperham** [comment]
Reviewing the code, it looks like lock_timeout is purely a runtime attribute and not something inherent in the concurrent limiter in Redis.  You might be able to use two different instances, as you show, and have it work as you want.  Let me know if this works for you.  It's not a trait I officially designed or document but I'm curious to see if it works for you.

**Comment by philipbjorge** [comment]
@mperham -- This looks to work after some testing with multiple console processes.

What's your opinion on using this in production code? If behavior of this changed, would it be noted in a CHANGELOG? Is this something that could be documented and made official?

**Comment by mperham** [comment]
I have no problem deeming it official behavior.  Make it so!

**Comment by philipbjorge** [comment]
I added a note to https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#notes

Thanks alot!
