### ISSUE TITLE
Retry 0/false being ignored, jobs retrying anyway

### ISSUE THREAD

**Issue by scottrobertson** [mperham/sidekiq#4200]
Ruby version: 2.5.5
Sidekiq: 5.2.5
Pro: 4.0.5
Enterprise: 1.8.1

As you can see, the class has retry set to `0`, so it should never retry. I have tried `false` too. These jobs are inside a batch.

The sidekiq addons we have are `sidekiq-datadog`, `sidekiq-status` and `sidekiq-failures`

<img width="398" alt="Screenshot 2019-06-27 at 16 15 20" src="https://user-images.githubusercontent.com/68361/60278160-cc641a80-98f6-11e9-941a-fbf5cfef4815.png">

However, we are getting retry jobs created.

![OcxrUBZ](https://user-images.githubusercontent.com/68361/60278039-9b83e580-98f6-11e9-871a-29ed06375026.jpg)

For reference, the only code in StatusWorker that isn't just helper methods is:

```
sidekiq_options failures: :exhausted
```

Tried removing that line, but it's still the same.

Can you point me in any direction as to how i may start debugging this more? Is `sidekiq-failures` known for getting in the way here?

```
WARN: {"context":"Job raised exception","job":{"class":"WorkerClass","queue":"queue_1","args":["1d79d15f-2c79-4ed2-90f9-3df95dc088cd",null],"retry":true,"jid":"01f564524f9fbdfa217cc391","created_at":1561647933.0404842,"bid":"tiNNNi7MHxZ0hw","enqueued_at":1561647933.043218,"error_message":"hi","error_class":"ExceptionClass","processor":"scotts-mbp.lan:90555","failed_at":1561647933.721576},"jobstr":"{\"class\":\"WorkerClass\",\"queue\":\"queue_1\",\"args\":[\"1d79d15f-2c79-4ed2-90f9-3df95dc088cd\",null],\"retry\":true,\"jid\":\"01f564524f9fbdfa217cc391\",\"created_at\":1561647933.0404842,\"bid\":\"tiNNNi7MHxZ0hw\",\"enqueued_at\":1561647933.043218}"}
```

Here is the line from the logs. Not sure why `retry: true` is in there?

```
WorkerClass.get_sidekiq_options['retry']
=> 0
```

**Comment by scottrobertson** [comment]
Worked this out. It's because we are using `Sidekiq::Client.push` (because we need to dynamically set the queue).

@mperham i am not sure if this is something that should be discussed further. It was my (probably stupid) assumption that the jobs would use the `sidekiq_options`, even if `Sidekiq::Client.push` was used.

Will leave open, but feel free to close.

**Comment by mperham** [comment]
If you use `push("class" => "WorkerClass")` it will not use the sidekiq_options because it won't constantize.  If you use `push("class" => WorkerClass)` it will use the sidekiq_options.

https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/client.rb#L234

**Comment by scottrobertson** [comment]
That makes perfect sense. Told you my assumption was stupid 😂
