### ISSUE TITLE
Workers frozen

### ISSUE THREAD

**Issue by jbescoyez** [mperham/sidekiq#4204]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s):
* Sidekiq: 5.2.7
* Sidekiq Pro: 4.0.5
* Rails: 5.1.2
* Mail gem:  2.7.1

Our workers get stuck periodically (2-3 times a week). So far, we have identified that the issue might be in the Mail gem but we have no idea what might get our worker stuck. Our app is hosted on Heroku. Restarting the dyno would usually solve the issue (sometimes, we need 2-3 restarts).

TTIN Output: https://gist.github.com/jbescoyez/f98379b4c1ff91c127b46093b1fb7e5b

**Comment by mperham** [comment]
Looks like you are running bootsnap. I don’t think it is supposed to run in production?

**Comment by jbescoyez** [comment]
Ouch. Indeed. I've removed it from production and I'll let you know if we still experience issues.

**Comment by mikegee** [comment]
It is supposed to be ok to run bootsnap in production: https://github.com/Shopify/bootsnap#environments

**Comment by mperham** [comment]
Good point.  If you look in that TTIN output, there are a load of threads are stuck in mail header parsing, with one thread deep inside loading the mail gem.  Ah, wait a second.  Add this to an initializer and see if it fixes the issue:

```ruby
Mail.eager_autoload!
```

**Comment by mperham** [comment]
As noted here: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#not-thread-safe-gems

**Comment by jbescoyez** [comment]
@mperham Tnx. I missed this one in the docs. I've deployed the fix today. I'll let you know if we still experience the issue this week.
