### ISSUE TITLE
Sidekiq retry statsd metrics

### ISSUE THREAD

**Issue by calston** [mperham/sidekiq#4205]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 4.0.4/1.7.1

Would it be possible to get jobs metrics about the retry queue? It seems there are currently only count, duplicate, success and failure. Failures might possibly create a retry but I don't know if that's guaranteed?

**Comment by mperham** [comment]
Do the Enterprise historical metrics supply what you need?

https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics

**Comment by calston** [comment]
Ah, yeah I guess they would, will update version and enable those too.
