### ISSUE TITLE
worker hang randomly

### ISSUE THREAD

**Issue by allen12921** [mperham/sidekiq#4206]
Ruby version: 2.5.1
Sidekiq: 5.1.3

We're encountering random worker hang issue..
When it happens, it won't receive any signal.
this is the gdb output.
https://gist.github.com/allen12921/ab02c66746b07245160e2fd155b57e39

Pls help

**Comment by mperham** [comment]
Please follow the directions and include all the backtrack data:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes

**Comment by allen12921** [comment]
My staff already restarted the main process..I'll try to send the fill backtrace here in next issue time ..

**Comment by allen12921** [comment]
@mperham 
The problem happened again
I have attached detailed gdb trace log,pls help  to have a look
https://gist.github.com/allen12921/ab02c66746b07245160e2fd155b57e39

when I call call (void)rb_backtrace() from gdb,only get belows from sidekiq log file:

        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:12:in `block in start!'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:12:in `loop'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:13:in `block (2 levels) in start!'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch.rb:34:in `redis_retryable'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:15:in `block (3 levels) in start!'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:48:in `update_heartbeat'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:92:in `redis'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:95:in `block in redis'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch/global/monitor.rb:49:in `block in update_heartbeat'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:284:in `multi'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:478:in `namespaced_block'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:2345:in `multi'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
        from /home/ubuntu/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis.rb:2353:in `block in multi'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/redis.rb:87:in `call_pipeline'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/redis.rb:29:in `port_path_or_id_for'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:36:in `port'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/transaction/datastore_segment.rb:21:in `initialize'
        from /var/apps/goku/shared/bundle/ruby/2.5.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/datastores/redis.rb:69:in `append_pipeline_command'

**Comment by mperham** [comment]
I don't see any obvious causes.  I would upgrade your Ruby version.
