### ISSUE TITLE
Sidekiq::Limiter::OverLimit wrong link under Sidekiq::Batch page

### ISSUE THREAD

**Issue by aliismayilov** [mperham/sidekiq#4209]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 5.2.5 / 4.0.5 / 1.8.1

I have:
```ruby
# app/workers/parent_worker.rb
class ParentWorker
  include Sidekiq::Worker

  def perform
    batch = Sidekiq::Batch.new

    batch.jobs do
      1.upto(5).each do |number|
        ChildWorker.perform_async(number)
      end
    end
  end
end

# app/workers/child_worker.rb
class ChildWorker
  include Sidekiq::Worker

  def perform(number)
    rate_limit do
      # some work...
    end
  end

  def rate_limit
    Sidekiq::Limiter.concurrent('children', 1, wait_timeout: 5, lock_timeout: 180).within_limit do
      yield
    end
  end
end
```

If a `ChildWorker` gets fails because of `Sidekiq::Limiter::OverLimit` as per https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#take-it-to-the-limit it gets rescheduled.

When I click on the job that's listed under the batch page of sidekiq-ent/web (example URL `/sidekiq/batches/3t0W3xDznyDDpg`) I'm taken to `/sidekiq/retries` page, where the job is not found. The overlimit job is actually listed on `/sidekiq/scheduled`.

**Comment by mperham** [comment]
Yep, this is an unfortunate implementation detail of the rate limiting subsystem. Not sure if I can easily fix it, will investigate.

**Comment by mperham** [comment]
<img width="1200" alt="Screen Shot 2019-10-02 at 9 59 07 AM" src="https://user-images.githubusercontent.com/2911/66065250-d9973380-e4fb-11e9-838a-1918f2ae11ac.png">

I've redesigned the batch failure listing to give direct links to the retries and scheduled jobs associated with the batch. The linked JID will be wrong BUT you can click the Scheduled button to see the job you are looking for. Unfortunately the page can't tell which tab the job will be in without scanning through Redis, which would be way too heavyweight.

**Comment by aliismayilov** [comment]
I see the new 2 Retries and Scheduled buttons which were already available in the top Summary bar and the Navigation bar. The displayed JIDs are still links and they navigate to Retries page where it says "No retries were found".

I'd like to understand why the issue is closed while the problem is still there.

**Comment by mperham** [comment]
If you click the Scheduked button, it will show scheduled jobs *for that batch*. That will show your job.

**Comment by aliismayilov** [comment]
I see. That's helpful. Thank you!
