### ISSUE TITLE
Per-limiter backoff setting

### ISSUE THREAD

**Issue by pirj** [mperham/sidekiq#4219]
Ruby version: 2.5.5
Sidekiq / Pro / Enterprise version(s): 5.1.3/4.0.3/1.7.2

I'm scratching my own itch with this, we've started using Sidekiq, and we're working with a range of external APIs, including the infamous Google ones that have quite odd rate limits.

Backoffs differ significantly for different limiters.
That resulted in a quite cumbersome global backoff setting proc with nested `case`, so I thought it would be nice to have this setting on limiter itself.

Global backoff setting has two downsides:
 - it becomes quite unwieldy as the number of limiters grows
 - it is separated from the job and makes it harder to understand the job behaviour without looking up in the initializer

Also, limiters can't be compared (by either `==` or `===`), so in the global backoff setting proc you can't:

```ruby
Sidekiq::Limiter.configure do |config|
  config.backoff = ->(limiter, job) do
    case limiter
    when Limiters::DAILY_LIMITER
      # ...
    when Limiters::MINUTE_LIMITER
      # ...
    else
      Sidekiq::Limiter::DEFAULT_BACKOFF.call(limiter, job)
    end
  end
end
```

and we resort to checking by `limiter.name == 'daily_limiter'`, which is not so convenient.

No rush, we can safely live with that until the next major `sidekiq-ent` release.

**Comment by krasnoukhov** [comment]
@mperham I see that an improvement for this is listed in 2.0 release notes, but is there updated documentation for per-limiter backoff? Thanks
