### ISSUE TITLE
Pro and Enterprise logging naming customization

### ISSUE THREAD

**Issue by nakulpathak3** [mperham/sidekiq#4220]
Ruby version: 2.3.8
Sidekiq / Pro / Enterprise version(s): 5.2.3 / 4.0.4 / 1.8.1

Initializer 
```ruby
Sidekiq.configure_server do |config|
  Sidekiq::Pro.dogstatsd = ->{ CustomMetric.dogstatsd } # we have a dogstatsd instance we use for all metrics so we pass it to Sidekiq too
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end

  logging_frequency_seconds = 30
  config.retain_history(logging_frequency_seconds)
end
```

The Pro metrics seem to create metrics in the form of `jobs.TestWorker.<metric>` and Enterprise metrics as `sidekiq.<metric>`. I was wondering if there's functionality to edit the naming of these logs other than the `dogstatsd` `namespace` option setting for prefixes. 

For example, can I have a worker log to `jobs.test_worker` (or `sidekiq.workers.TestWorker`) instead of `jobs.TestWorker`?

**Comment by mperham** [comment]
Nope, there is no provision for changing the naming scheme except the namespace option as you note.

**Comment by nakulpathak3** [comment]
Thanks for the information :)
