### ISSUE TITLE
Enterprise: Signal USR2 doesn't restart Sidekiq

### ISSUE THREAD

**Issue by jodosha** [mperham/sidekiq#4221]
Ruby version: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-gnu]
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.7 / Sidekiq Pro 4.0.5 / Sidekiq Enterprise 1.8.1

According to the [documentation](https://github.com/mperham/sidekiq/wiki/Signals#usr2), `USR2` should restart Sidekiq:

> Sidekiq will reopen all logfiles that have been rotated using logrotate (without copytruncate) or similar tools. This behavior is the same behavior as Unicorn's USR1 response. I do not recommend using this, your daemon should be logging to stdout and letting upstart/systemd handle your logs for you.
> 
> Sidekiq Enterprise uses USR2 as the trigger for a rolling restart.

But it doesn't seem to restart Sidekiq:

```shell
$ ps aux | grep -i sidekiq
webapp   11702  0.4  0.3 2716388 209864 ?      Ssl  07:04   0:27 sidekiq 5.2.7 webapp [0 of 24 busy] leader
jodosha  14426  0.0  0.0  14428  1052 pts/0    S+   08:56   0:00 grep --color=auto -i sidekiq
```

```shell
$ sudo kill -USR2 11702
```

By retrying several times to check if the process has been restarted, it doesn't include Sidekiq the list of the processes.

```shell
$ ps aux | grep -i sidekiq
jodosha  15739  0.0  0.0  14428  1000 pts/0    S+   08:57   0:00 grep --color=auto -i sidekiq
```

With a fresh deploy of the app, I'm able to properly restart Sidekiq.

---

The reason why we send `USR2` is for log rotation purposes: we use log files, instead of stdout.

**Comment by mperham** [comment]
You need to start Sidekiq (or sidekiqswarm) with einhorn to get rolling restarts. Can you show how you are starting it?

**Comment by jodosha** [comment]
```shell
/usr/local/bin/bundle exec sidekiq -e <environment> -t <timeout> -i 0
```

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts#how

**Comment by jodosha** [comment]
@mperham Thanks both for Sidekiq and your quick reply. 💚
