### ISSUE TITLE
sidekiq_retry_in_block not called never with exception

### ISSUE THREAD

**Issue by danielgomezrico** [mperham/sidekiq#4222]
Ruby version: 2.4.3p205
Sidekiq / Pro / Enterprise version(s): sidekiq (4.2.10)

In the readme [wiki/Error-Handling](https://github.com/mperham/sidekiq/wiki/Error-Handling) it mentions:

```
sidekiq_retry_in do |count, exception|
end
```

I tried it but that is never called. when is that function called?

I tried with 

```
sidekiq_retry_in do |count|
end
```

and it was used indeed. It looks like the one with the exception is called sometimes, when?

**Comment by mperham** [comment]
The wiki covers the current version. Your version is years old.
