### ISSUE TITLE
Sidekiq waste all system memory and then killed

### ISSUE THREAD

**Issue by DevelopMan** [mperham/sidekiq#4225]
Ruby version: ruby-2.6.0-preview2
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.7
OS: Ubuntu 18.04.1 LTS

config/sidekiq/main.yml
```
:concurrency: 5
:queues:
  - analizer
```

perform method of the worker:
```
  def perform(audit_id)
    Audit.find(audit_id).generate(self)
  end
```

Method generate of the model Audit make a lot of suff, including website parsing with saving page contents. For sites with a lot of pages Sidekiq process killed by system because it use all of the memory (2Gb). By the way if I execute
```
Audit.find(audit_id).generate()
```
for the same website it works fine, without any memory leaks.

What I tried:
ActiveRecord::Base.cache { AnaliseWorker.new.perform(Audit.last.id) }
as well as
ActiveRecord::Base.uncached { AnaliseWorker.new.perform(Audit.last.id) }
With equal result: process killed by system.

There is a no any errors from the Rails, Ruby or Sidekiq because the system just kill Sidekiq process.

**Comment by mperham** [comment]
See Problems and Troubleshooting wiki page. No leak issues without proof.
