### ISSUE TITLE
Some workers are not working correctly.

### ISSUE THREAD

**Issue by freshcoderchan** [mperham/sidekiq#4228]
Hi
I have run 5 workers using Sidekiq.
Each worker manipulates **100k** rows from the database but **3~4** workers always have been finished by only manipulating **3k** rows.

`2019-08-20T08:40:31.003Z 32101 TID-owc4a78fh ProductWorker JID-579d01a1358adefa424919a5 INFO: done: 193.834 sec
`

Does anyone know why this happens?

**Comment by freshcoderchan** [comment]
Hi @mperham  - thanks for your great work!
Could you please help me to fix the above issue I have now?

**Comment by lmansur** [comment]
Could you post the application code for your workers?

**Comment by freshcoderchan** [comment]
@lmansur this is my code,

**Controller**

```
3.times {|i| 
ProductWorker.perform_async(i)
}
```

**ProductWorker**

```
def perform(n)
   CSV.open("csv/products.csv", "wb") do |csv|
       csv << Product.headers.split(",").map(&:strip)
      limit = 100000
      offset = n * limit
      Product.all.limit(limit).offset(offset).find_each do |product|
        csv << map_csv_order_row(product)
      end
   end
end
```

This worker makes csv file with 100k rows.

**Comment by freshcoderchan** [comment]
I have fixed.
This was not related with Sidekiq.
