### ISSUE TITLE
Documentation about Logging configuration out of date

### ISSUE THREAD

**Issue by fdr** [mperham/sidekiq#4233]
Ruby version:
2.6.3

Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.0.0 upgrade from 5.2.7

So I noted via Dependabot that Sidekiq 6.0.0 fails for us on this line that is also seen on the manual page https://github.com/mperham/sidekiq/wiki/Logging#default-logger-and-verboseness

```
Failure/Error: Sidekiq::Logging.logger.level = Logger::WARN

NameError:
  uninitialized constant Sidekiq::Logging
```

**Comment by mperham** [comment]
I've updated the wiki page and removed a lot of outdated content.  Please close if it looks ok to you.

**Comment by fdr** [comment]
Works great, thanks.
