### ISSUE TITLE
Does Sidekiq Pro 5 actually require Sidekiq 6?

### ISSUE THREAD

**Issue by dbackeus** [mperham/sidekiq#4235]
According to https://github.com/mperham/sidekiq/blob/master/Pro-5.0-Upgrade.md#whats-new Sidekiq Pro 5 requires Sidekiq 6.0+.

If this is correct how come the gemspec declares `sidekiq >= 5.2.7`?

**Comment by mperham** [comment]
Mistake. If it runs, great. But the intent is 6.0+.
