### ISSUE TITLE
Sidekiq.logger = nil does not work in 6.0

### ISSUE THREAD

**Issue by philipbjorge** [mperham/sidekiq#4240]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): 6.0, 5.0, 2.0

Setting `Sidekiq.logger = nil` doesn't appear to stop logging anymore.
https://github.com/mperham/sidekiq/wiki/Logging#turning-off-logging-in-the-test-environment

What is the recommended way to disable logging in test env now?

**Comment by mperham** [comment]
Do you think it's better to disable it completely or set the level to ERROR or FATAL? Wouldn't you want tests to log errors?

**Comment by mperham** [comment]
I've adjusted the documentation to show how to set the level to ERROR.  I think that's a better way to see less log output.

**Comment by philipbjorge** [comment]
In our tests, sometimes we specifically test scenarios that trigger `logger.error` and I prefer those logs to not appear in our test output.

I've gone with setting the log level to `FATAL` for our test env which generally solves the issue.

Thanks!

**Comment by mperham** [comment]
6.0.1 will automatically set level to FATAL if nil is passed in since a nil logger is not technically supported.  Thanks for the feedback!
