### ISSUE TITLE
Sidekiq v6 logging to Logstash (custom logger)

### ISSUE THREAD

**Issue by collimarco** [mperham/sidekiq#4254]
With Sidekiq v5 we used the following code to send logs directly to Logstash (Logz.io):

```
Sidekiq.configure_server do |config|
  if Rails.env.production?
    Sidekiq::Logging.logger = LogStashLogger.new(Rails.configuration.logstash)
    Sidekiq::Logging.logger.level = Logger::WARN
  end
end
```

Now, after the upgrade to Sidekiq v6, we have tried to use the following code:

```
Sidekiq.configure_server do |config|
  if Rails.env.production?
    Sidekiq.logger = LogStashLogger.new(Rails.configuration.logstash)
    Sidekiq.logger.level = Logger::WARN
  end
end
```

However that raises an error at runtime:

```
NoMethodError: undefined method `with_context' for #<Logger:0x000054da73a57580>
Did you mean?  with_options
/home/myuser/www/myuser/shared/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/job_logger.rb:27:in `with_job_hash_context'
/home/myuser/www/myuser/shared/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/processor.rb:120:in `dispatch'
/home/myuser/www/myuser/shared/bundle/ruby/2.6.0/gems/sidekiq-6.0.0/lib/sidekiq/processor.rb:159:in `process'
...
```

From [the implementation](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L202) it seemed possible to set a custom logger, but it doesn't work.

How can we use [LogStashLogger](https://github.com/dwbutler/logstash-logger) with Sidekiq v6?

Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s): Sidekiq v6

**Comment by mperham** [comment]
Check out the last few closed issues.

**Comment by collimarco** [comment]
@mperham Thanks for the reply. I have just checked the latest closed issues, but I don't see this exact problem (maybe I am missing something). Could you be more specific? Is there any solution?

**Comment by mperham** [comment]
Look at the Rails semantic logger issue. Same problem.

**Comment by collimarco** [comment]
@mperham Ok, so basically we should wait next release.

**Comment by collimarco** [comment]
A last question: any idea of when the next version (with the fix) will be released? And, in the meantime, is it safe to use Sidekiq from Github master branch (`gem 'sidekiq', github: 'mperham/sidekiq'`)? Or is there a better workaround?

**Comment by mperham** [comment]
I don’t predict release dates. Master should be fine to use until 6.0.1.
