### ISSUE TITLE
Sidekiq Enterprise Web UI displaying inconsistent metrics across pages. 

### ISSUE THREAD

**Issue by kyreeves** [mperham/sidekiq#4255]
The metrics seem to be inconsistent when navigating between pages on the web UI. The number of jobs processed changes by the hundreds on each page. The number of busy jobs changes by 1 or 2. Any thoughts on why this is happening?

- Live polling is on
- Cache has been cleared
- 0 jobs enqueued

Ruby version: 2.5.1
Sidekiq-Pro version: 4.0.5
Sidekiq-Ent version: 1.7.2

**Comment by mperham** [comment]
Do you have any proxies or caches in front of the Sidekiq UI?  Can you give me a more precise set of steps to reproduce the behavior?  The Processed count is only ever incremented so if you are seeing it drop, you are seeing a cached copy somehow.

If you can give me private access to your UI (sending details in email is fine), I would be happy to reproduce it there myself.

**Comment by kyreeves** [comment]
Yep. Just configured Fastly to ignore sidekiq routes and it's working now! 

Thanks for the help @mperham! Appreciate the timely response.

**Comment by mperham** [comment]
👍
