### ISSUE TITLE
Jobs moving directly from queued to scheduled

### ISSUE THREAD

**Issue by baileyspace** [mperham/sidekiq#4266]
Ruby version:
ruby 2.4.1

Sidekiq Enterprise 1.7.2
sidekiq-pro (4.0.5)
sidekiq (5.2.1)

I'm using the `process_async` method for all my workers, but I consistently see enqueued jobs move into the Scheduled Jobs tab. Is there any reason a job would be added to Scheduled other than using `perform_in` or `perform_at`?

**Comment by mperham** [comment]
Any payload with an ‘at’ attribute will go into Scheduled.
