### ISSUE TITLE
Scheduled job being pushed directly to the queue from reliable_push

### ISSUE THREAD

**Issue by andrehjr** [mperham/sidekiq#4267]
Ruby version: 2.5.5
Sidekiq / Pro / Enterprise version(s):Sidekiq 5.2.6, Sidekiq-Pro: 4.0.5 

Hi there!

We had an issue when one of our Redis instances had connectivity problems while some jobs were being pushed to it. I made a script reproducing the issue below. (it also fails on Sidekiq(6.0.0) / Sidekiq-Pro(5.0.0)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'minitest'
  gem 'redis'

  source "https://gems.contribsys.com/" do
    gem 'sidekiq-pro', '< 6'
  end
end

redis_conn = proc { Redis.new }

Sidekiq::Client.reliable_push!

Sidekiq.configure_server do |config|
  config.redis = ConnectionPool.new(size: 5, &redis_conn)
  config.super_fetch!
  config.reliable_scheduler!
  config.reliable_push!
end

class MyWorker; include Sidekiq::Worker; end

class Redis
  def zadd(*args)
    raise Redis::BaseError.new('Simulating connection issues')
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def setup
    Sidekiq::Queue.new('not_for_now').clear
    Sidekiq::Queue.new('normal_queue').clear
    Sidekiq::ScheduledSet.new.clear
  end

  def test_scheduling_with_redis_issues
    Sidekiq::Client.enqueue_to_in(:not_for_now, 500, MyWorker, 'in_the_future', 1, :bat => 'bar') # should go to scheduled jobs # Redis throws an error and the payload is saved.
    Sidekiq::Client.enqueue_to(:normal_queue, MyWorker, 'foo', 1, :bat => 'bar')

    assert_equal Sidekiq::ScheduledSet.new.size, 1
    assert_equal Sidekiq::Queue.new('not_for_now').size, 0
    assert_equal Sidekiq::Queue.new('normal_queue').size, 1    
  end
end
```

Output:
```
Fetching source index from https://gems.contribsys.com/
Fetching gem metadata from https://rubygems.org/..........
Fetching source index from https://rubygems.org/
Resolving dependencies.....
Using bundler 1.17.3
Using concurrent-ruby 1.1.5
Using connection_pool 2.2.2
Using minitest 5.11.3
Using rack 2.0.7
Using rack-protection 2.0.7
Using redis 4.1.2
Using sidekiq 6.0.0
Using sidekiq-pro 5.0.0
Run options: --seed 23496

# Running:

2019-09-14T14:42:30.567Z pid=42265 tid=ox24g31o9 WARN: [ReliablePush] Enqueueing job locally due to Redis::BaseError: Simulating connection issues
2019-09-14T14:42:30.567Z pid=42265 tid=ox24g31o9 INFO: [ReliablePush] Connectivity restored, draining local queue
F

Finished in 0.003655s, 273.5978 runs/s, 273.5978 assertions/s.

  1) Failure:
BugTest#test_scheduling_with_redis_issues [bug_report.rb:52]:
Expected: 0
  Actual: 1

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

If I remove the `zadd` monkeypatch the test finishes with success. The job is scheduled as expected and not sent directly to the queue.

Seems like the `at` gets lost [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/client.rb#L197-L200). Am I missing something?

**Comment by andrehjr** [comment]
I'm trying a few things over here, seems like changing `atomic_push` to not delete `at` before calling ZADD fixes it for me (at least for the bug_report.rb above). Doing it that way, when the payload gets recovered and calling atomic_push the job gets send to the ScheduledSet as expected.

But I'm not sure if that breaks something else or that side effects on doing that. If this change makes sense or if you could point me in the right direction I can try making a PR for that. 

Does it make sense? Or if there's a workaround for this scenario.

**Comment by mperham** [comment]
Right, because atomic_push mutates the payload before calling Redis, saving the payload after a Redis error means we won't have that `at` attribute when we drain upon reconnection. I'll need to think about this one, I don't see a cheap, easy fix.  We could deep clone the entire `payloads` argument before calling but that's pretty expensive. A much cheaper fix is only handle the case where payloads.size == 1 by saving the `at` value before calling super.  I think that's a reasonable compromise, wdyt?

**Comment by mperham** [comment]
I think I'm happy with that compromise, it's extremely rare to push multiple scheduled jobs at once (in fact I believe it's only possible in Sidekiq 6.0.1 with the recent push_bulk change).

**Comment by andrehjr** [comment]
That was fast 🚀payloads.size == 1 does makes sense.

I'll wait for when Pro 5.0.1 is out, thanks @mperham !

**Comment by andrehjr** [comment]
Hi @mperham !

We had this issue again. I'm testing the repro script above with sidekiq 6.1.2 and sidekiq-pro 5.2.0 and it seems to still be losing the 'at' somehow 🤔  the job got pushed to the queue directly when ReliablePush executes.

I'll try to dig deeper to find out what's happening, just wanted to let you know.
