### ISSUE TITLE
Feature request: Compressing worker backtraces before pushing into redis

### ISSUE THREAD

**Issue by fatkodima** [mperham/sidekiq#4270]
Compressing backtraces before pushing/poping from redis will save a bunch of memory and bandwidth.
Testing locally, even for `backtrace: 20` lines of backtrace I got 5x savings, and for larger backtraces with `backtrace: true` it even came near 10x times.

**Comment by mperham** [comment]
Yeah, this is one of those smart ideas that seems obvious in retrospect. Backtraces are very compressible.

**Comment by fatkodima** [comment]
👍 i will try to implement.
