### ISSUE TITLE
Support for custom batch props

### ISSUE THREAD

**Issue by bdelo** [mperham/sidekiq#4273]
We have a use case where we create a handful of different "types" of batches periodically, and we want to be able to query the status of all the batches of a certain type. So for example, we might have a concept of a "backfill" batch type, with many different batches performing that similar function. 

We want to implement an internal page to show statuses of those types of batches. Currently, we are able to achieve this by overloading the `description` prop to a constant when creating this type of batch:
```ruby 
batch = Sidekiq::Batch.new
batch.description = BACKFILL_BATCH_TYPE
```
and then using the API to select off the description:
```ruby
bs = Sidekiq::BatchSet.new
backfill_batch_statuses = batch_set.select{|status| status.data[:description] == BACKFILL_BATCH_TYPE}
```

While this works, overloading the `description` prop means we have to sacrifice an actual description and things we might actually want in there (what is it backfilling, what customers we're backfilling for, etc in this hypothetical). 

A `@type` prop or something would probably be way to niche to our uses, but what are your thoughts on being able to pass a `@custom_props` hash or something similar to a batch that would be able to be pulled back in a `Status` object? This would allow users to identify their batches with more precision and ease than just through a single `description` field.

**Comment by mperham** [comment]
Create a batch description convention and logic around it:

```
btype = "BACKFILL"
desc = "for user #12345"
batch.description = "[#{btype}] #{desc}"

batch_set.select{|status| status.data[:description].match?("\A[#{BACKFILL_BATCH_TYPE}] ") }
```
