### ISSUE TITLE
Fetch scheduled jobs in batches

### ISSUE THREAD

**Issue by fatkodima** [mperham/sidekiq#4274]
The current implementation of scheduling is https://github.com/mperham/sidekiq/blob/537a8e7ce8216bace25d3fbbd1b66ef822f61c42/lib/sidekiq/scheduled.rb#L21-L30

In a loop, 
1. fetch one job
2. shift queues for that job

While limiting step 2 to only one job is reasonable to avoid race conditions and jobs loss, but for step 1 we can fetch jobs in batches, say 100 items at a time, thus greatly speeding things up.

Mike, what do you think about this change? Is there a reason, why it is implemented that way?

**Comment by mperham** [comment]
It’s done one at a time so if there is a Redis network error, only one job is lost. What if net fails on step 2, would you lose 100 jobs?

**Comment by fatkodima** [comment]
> What if net fails on step 2, would you lose 100 jobs?

No.

Maybe I explained not clear enough, what i propose is something like:
```ruby
jobs = conn.zrangebyscore(sorted_set, '-inf', now, limit: [0, 100])
jobs.each do |job|
  if conn.zrem(sorted_set, job)
    Sidekiq::Client.push(Sidekiq.load_json(job))
  end
end
```

So we *read* in memory 100 jobs at once, but *process* (moving from one queue to another) one at a time.

**Comment by mperham** [comment]
Ah, sure, sounds good. Benchmark if possible.
