### ISSUE TITLE
Logger: JSON output format not working

### ISSUE THREAD

**Issue by belgoros** [mperham/sidekiq#4277]
Ruby version: `2.6.3`
Rails `5.2.3`.
Sidekiq / Pro / Enterprise version(s): `6.0.0` (free)

```ruby
# config/initializers/sidekiq.rb
sidekiq_config = { url: ENV['JOB_WORKER_URL'] }

Sidekiq.configure_server do |config|
  config.redis = sidekiq_config
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_config
end
```

Here is the content of `sidekiq.yml` file:
```yml
:schedule:
  posts_display:
    class: PostsDisplayJob
    every: '15s'
```
And here is the content of `app/jobs/posts_display.rb` file:
```ruby
class PostsDisplayJob < ApplicationJob
  queue_as :default

  def perform(*args)
    puts "#{Time.current}: Found posts: #{Post.count}"
  end
end
```
The output in the Terminal tab running sidekiq:
```
sidekiq_app git:(master) ✗ sidekiq
2019-09-19T13:55:35.874Z pid=35102 tid=ovge8ky0u INFO: Booting Sidekiq 6.0.0 with redis options {:url=>nil, :id=>"Sidekiq-server-PID-35102"}
2019-09-19T13:55:35.926Z pid=35102 tid=ovge8ky0u INFO: Running in ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
2019-09-19T13:55:35.926Z pid=35102 tid=ovge8ky0u INFO: See LICENSE and the LGPL-3.0 for licensing details.
2019-09-19T13:55:35.926Z pid=35102 tid=ovge8ky0u INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2019-09-19T13:55:35.942Z pid=35102 tid=ovge8ky0u INFO: Loading Schedule
2019-09-19T13:55:35.942Z pid=35102 tid=ovge8ky0u INFO: Scheduling posts_display {"class"=>"PostsDisplayJob", "every"=>"15s", "queue"=>"default"}
2019-09-19T13:55:35.944Z pid=35102 tid=ovge8ky0u INFO: Schedules Loaded
2019-09-19T13:55:35.944Z pid=35102 tid=ovge8ky0u INFO: Starting processing, hit Ctrl-C to stop
2019-09-19T13:55:51.069Z pid=35102 tid=ovgef39ay INFO: queueing PostsDisplayJob (posts_display)
2019-09-19T13:55:51.072Z pid=35102 tid=ovgef7se2 class=PostsDisplayJob jid=f3d2856fd2b0e334c6dbf25b INFO: start
2019-09-19 13:55:51 UTC: Found posts: 10
2019-09-19T13:55:51.267Z pid=35102 tid=ovgef7se2 class=PostsDisplayJob jid=f3d2856fd2b0e334c6dbf25b elapsed=0.195 INFO: done
2019-09-19T13:56:06.201Z pid=35102 tid=ovgef39ay INFO: queueing PostsDisplayJob (posts_display)
2019-09-19T13:56:06.203Z pid=35102 tid=ovgef7sva class=PostsDisplayJob jid=b264b155cf9f71c543525524 INFO: start
2019-09-19 13:56:06 UTC: Found posts: 10
2019-09-19T13:56:06.206Z pid=35102 tid=ovgef7sva class=PostsDisplayJob jid=b264b155cf9f71c543525524 elapsed=0.003 INFO: done
^C2019-09-19T13:56:10.878Z pid=35102 tid=ovge8ky0u INFO: Shutting down
....
```
The output format is still in STDOUT format instead of being JSON as the wiki [Logging](https://github.com/mperham/sidekiq/wiki/Logging#output-format) section explains.

What am I missing? Example app is [here](https://github.com/belgoros/sidekiq_app). 
Thank you.

**Comment by mperham** [comment]
Is it possible you have Rails config or a gem which is touching the logger too?

You can delete your Redis config in the initializer if you set REDIS_PROVIDER:

REDIS_PROVIDER=JOB_WORKER_URL

```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
end
```

https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-env-variable

**Comment by belgoros** [comment]
> Is it possible you have Rails config or a gem which is touching the logger too?
I use [sidekiq-scheduler](https://github.com/moove-it/sidekiq-scheduler) as an additional Sidekiq related gem. There is nothing special regarding Rails loggings, everything being left by default, - you can take a look at the provided [app code source](https://github.com/belgoros/sidekiq_app).

> You can delete your Redis config in the initializer if you set REDIS_PROVIDER:
> REDIS_PROVIDER=JOB_WORKER_URL

I set `REDIS_PROVIDER` to `REDIS_PROVIDER: "http://localhost:6379"` in the Rails credentials.

**Comment by mperham** [comment]
> I set `REDIS_PROVIDER` as `REDIS_PROVIDER: "http://localhost:6379"` in the Rails credentials.

There are two mistakes:

1. It is an environment variable, not a credential. I don't think Sidekiq will see it.
2. I didn't say to set it to a URL, I said to set the value to literally "JOB_WORKER_URL".

**Comment by tremulaes** [comment]
@mperham I apologize if this is answered elsewhere, but does your most recent response here mean that Sidekiq 6.0.0 requires Rails 6.0.0? I'm seeing the same issue with the JSON formatter, but I'm also only on rails 5.2.

**Comment by mperham** [comment]
No, it means I don’t know what Rails 6 does when configured with 5.2 defaults.

**Comment by seuros** [comment]
@mperham it do nothing particular. It just wont load the new default or use the new loader.
These defaults are loaded in 6.0 too.
```ruby
          if respond_to?(:active_record)
            active_record.cache_versioning = true
            # Remove the temporary load hook from SQLite3Adapter when this is removed
            ActiveSupport.on_load(:active_record_sqlite3adapter) do
              ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer = true
            end
          end

          if respond_to?(:action_dispatch)
            action_dispatch.use_authenticated_cookie_encryption = true
          end

          if respond_to?(:active_support)
            active_support.use_authenticated_message_encryption = true
            active_support.use_sha1_digests = true
          end

          if respond_to?(:action_controller)
            action_controller.default_protect_from_forgery = true
          end

          if respond_to?(:action_view)
            action_view.form_with_generates_ids = true
          end
```

**Comment by seuros** [comment]
@belgoros did you check that it not a Spring issue ?

**Comment by tremulaes** [comment]
I believe I've found the issue and it looks to be already addressed!

The wiki's instructions for JSON formatting are the following:
```
Sidekiq.configure_server do |config|
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
end
```

This matches what is currently in master for Sidekiq
```
  def self.log_formatter=(log_formatter)
    @log_formatter = log_formatter
    logger.formatter = log_formatter
  end
```

However, after updating to sidekiq 6.0, looking at the source that's bundled in, the method is different:

```
def self.log_formatter=(log_formatter)
  @log_formatter = log_formatter
end
```

So the wiki instructions do not actually alter the formatter in the 6.0.0 release, but it looks like the problem has already been addressed. @belgoros you can update the logger format with a small alteration until the next version of sidekiq comes out:

```
Sidekiq.configure_server do |config|
  config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new
end
```

I have tested this and it works as expected.

**Comment by belgoros** [comment]
@mperham :
>I don't know if this means anything but this line is loading Rails 5.2 config, not 6.0.
https://github.com/belgoros/sidekiq_app/blob/master/config/application.rb#L23

The provided example app uses Rails `5.2.3` and not `6.0`, that's why it is so.

>It is an environment variable, not a credential. I don't think Sidekiq will see it.
100% right, to get a value stored in Rails credentials, I had to use:
```
Rails.application.credentials.dig(:key_name)
```
and not like `ENV[:key_name]`, - it worked with `figaro` gem this way. So I totally removed redis config settings and `sidekiq.rb` looks like that now:
```ruby
#sidekiq_config = { url: Rails.application.credentials.dig(:REDIS_PROVIDER)}

Sidekiq.configure_server do |config|
  #config.redis = sidekiq_config
#  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
  config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new

  # Touch a file so we know Sidekiq worker has started.
  # Useful for health checks
  config.on(:startup) do
    FileUtils.touch(Rails.root.join("tmp", "pids", "sidekiq_started"))
  end
  # Delete the touched file so we know Sidekiq worker has stopped.
  # Useful for health checks
  config.on(:shutdown) do
    FileUtils.rm(Rails.root.join("tmp", "pids", "sidekiq_started"))
  end
end

#Sidekiq.configure_client do |config|
#  config.redis = sidekiq_config
#end
```

@tremulaes:
>I apologize if this is answered elsewhere, but does your most recent response here mean that Sidekiq 6.0.0 requires Rails 6.0.0?

Agreed, I didn't find an answer nor some dependencies about required Rails versions. I'm also reproduced on Rails `5.2.3`.

After setting the log formatter as @tremulaes suggested:
```ruby
config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new
```
the outut is in JSON format:
```json
{"ts":"2019-09-20T07:42:31.333Z","pid":4850,"tid":"ox329wq26","lvl":"INFO","msg":"start","ctx":{"class":"PostsDisplayJob","jid":"0c47ef06b9f65c9dafa4e7ad"}}
2019-09-20 07:42:31 UTC: Found posts: 10
{"ts":"2019-09-20T07:42:31.657Z","pid":4850,"tid":"ox329wq26","lvl":"INFO","msg":"done","ctx":{"class":"PostsDisplayJob","jid":"0c47ef06b9f65c9dafa4e7ad","elapsed":"0.324"}}
{"ts":"2019-09-20T07:42:46.193Z","pid":4850,"tid":"ox32dz3tu","lvl":"INFO","msg":"queueing PostsDisplayJob (posts_display)"}
{"ts":"2019-09-20T07:42:46.194Z","pid":4850,"tid":"ox329wtd6","lvl":"INFO","msg":"start","ctx":{"class":"PostsDisplayJob","jid":"e393b26c4981f065f32553bb"}}
2019-09-20 07:42:46 UTC: Found posts: 10
```
Thank you all, guys 👍
