### ISSUE TITLE
sidekiq_options doesn't seem to work with Active job.   

### ISSUE THREAD

**Issue by Arafatk** [mperham/sidekiq#4281]
Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
Sidekiq / Pro / Enterprise version(s): 6.0.0
ActiveJob Version: 5.2.3

I am not sure if I should raise this issue here or in the active job repo but in the docs [here](https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling) It is mentioned that  

![image](https://user-images.githubusercontent.com/11155207/65380580-3d279280-dcac-11e9-954b-3b6c114cee13.png)

I can't seem to find a `6.0.1` version so maybe this is a future goal.   But since I could use this method with my code, I decided to try it out and it doesn't seem to work for me.        
The retry strategy just goes back to the default retry strategy with 25 retries.     

I can't seem to figure out how to debug the issues with my jobs so  I put a debug statement [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L51)
where I get 
```
#{opts} = {retry: 3} 
```

I also put in another debug statement [here]()
 
where I get   
```
 #{worker.class.get_sidekiq_options} =  {"retry"=>true, "queue"=>"default"}       

 #{worker} = #<ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper:0x00007fe1e0e30228>
```

So it seems to me that the `sidekiq_options_hash`  isn't the same in between [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L52)  and [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_retry.rb#L121)        

I couldn't trace the changes any further. The main reason I used this was because I was using the [retry_on](https://api.rubyonrails.org/v6.0.0/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) method in active job and that doesn't seem to work either(This method too changes the retry strategy to default silently and my jobs keep retrying for 25 times exponentially).       

I guess the issue that I am facing comes back to what is described in [this comment](https://github.com/rails/activejob/issues/47#issuecomment-218586593).         

I already have a work around for this(Using `resque_from`) so my issue is solved but I just wanted to figure out why this isn't working.          

Is this a known issue or is something wrong with my configuration?      
Should this issue be raised in ActiveJob too?

**Comment by Arafatk** [comment]
Just to be clear, I understand that you do not control activejob so it's probably not a good idea to ask this question to you but I only asked because I saw [this](https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling) in the documentation(which mentions compatibility with activejob) and I figured that I might get some insights from raising this issue here.


Thanks a lot.

**Comment by mperham** [comment]
Use master.

**Comment by mperham** [comment]
Oh and you need Rails master too, it needs Rails 6.0.1.

**Comment by Arafatk** [comment]
Thanks for the comment.       
I am using things in a production environment so I guess I will have to wait for an official release.      
Can you tell me when we might have an official release?

**Comment by mperham** [comment]
I don’t know when Rails 6.0.1 will be released. It won’t work until then.

**Comment by jaimerson** [comment]
This still seems to be the case on Rails with [this patch](https://github.com/rails/rails/pull/37214). `retry` option, `sidekiq_retry_in_block` ([see](https://github.com/mperham/sidekiq/blob/v6.0.2/lib/sidekiq/job_retry.rb#L216)) and `sidekiq_retries_exhausted_block` ([see](https://github.com/mperham/sidekiq/blob/v6.0.2/lib/sidekiq/job_retry.rb#L186)) all seem to be ignored in favor of `worker` (which in `ActiveJob`'s case would be `JobWrapper`) instead of `msg['wrapped']`.

**Comment by jaimerson** [comment]
@mperham can you confirm this is the case? I managed to get it working by patching `JobRetry`. So unless I'm missing something there are some changes required. I can send a PR if that's the case.

**Comment by mperham** [comment]
@jaimerson The retry blocks will not work but the changelog didn't say that.  `sidekiq_options`, including `retry`, will work.

**Comment by jaimerson** [comment]
@mperham would you like me to submit a PR for them to work? I mean, since it's available in the ActiveJob API it's intuitive that it should work.

**Comment by mperham** [comment]
No, I don't like those block features and regret adding them.

**Comment by pirj** [comment]
Update: support code will only make it to Rails 6.0.2 https://github.com/rails/rails/pull/37214#issuecomment-550431355

**Comment by mperham** [comment]
@fotinakis I don't believe AJ supports the pool option. That's implemented in Sidekiq::Job.

**Comment by fotinakis** [comment]
@mperham ok thanks — so to confirm, there is no way to get an ActiveJob to pass a pool option through? The job must be converted to a native Sidekiq::Job?

**Comment by mperham** [comment]
Correct.
