### ISSUE TITLE
Jobs stuck in busy after updating to rails 6

### ISSUE THREAD

**Issue by awadhwana** [mperham/sidekiq#4283]
Ruby version: 2.5.3
Sidekiq version: 5.2.7
Redis version=4.0.14
 Running in standalone mode
 Port: 6379
 PID: 840

```
# config/initializers/sidekiq.rb

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: "my_namespace_sidekiq#{Rails.env}" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0', namespace: "my_namespace_sidekiq_#{Rails.env}" }
end
```

Recently upgraded to rails 6 and now my jobs passes through enqueued and are stuck in busy, both the queues: default, mailers have be defined.
The process is also started.
![sidekiq](https://user-images.githubusercontent.com/44188995/65513382-cd5a1780-def8-11e9-8e8e-55f7bb6efd78.png)

I also tried upgrading to Sidekiq version: 6, but even that didn't help

**Comment by fernandoluizao** [comment]
Maybe you are using ['classic' autoloader](https://github.com/mperham/sidekiq/issues/4216)?

Happened to me too...

**Comment by ronval** [comment]
I was having this issue as well it turned out to be my application.rb file
I had config.load_defaults 5.2

I changed that to config.load_defaults 6.0

It fixed the jobs getting stuck on busy. Hope that helps someone.
