### ISSUE TITLE
Job-specific log levels

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4286]
Rails just added request-specific log levels. Sidekiq should support per-job log levels so you can turn on debugging for problematic workers. Investigate thread safe loggers.

**Comment by fatkodima** [comment]
> so you can turn on debugging for problematic workers

👍 
So, are you planning to work on this or I can take a stab, if you don't mind?

**Comment by mperham** [comment]
You are welcome to implement. I envision `sidekiq_options log_level: :debug`.
