### ISSUE TITLE
Comment Wording for Upstart Configuration

### ISSUE THREAD

**Issue by d-pfeif** [mperham/sidekiq#4288]
https://github.com/mperham/sidekiq/blob/78f11fba262b6e9244562c21c17bc484ffda7ec1/examples/upstart/sidekiq.conf#L45

I know this is minor, but there's a difference with the commands `reload` and `reload signal`. 
`reload` was added in v0.6.5 and sends a SIGHUP signal to a job.
`reload signal` was added in v1.10 and allows the user to send a specific command to the process.
http://upstart.ubuntu.com/cookbook/

The wording was a little confusing to me...I didn't know that `reload signal` was it's own command for upstart.

**Comment by mperham** [comment]
Send a PR if you want to fix it.
