### ISSUE TITLE
best practice to update model using activejob globalid

### ISSUE THREAD

**Issue by disastrous-charly** [mperham/sidekiq#4291]
Hi,

Just a quick question regarding ruby 2.6, rails 5.2, activejob and non commercial sidekiq.

I want to generate a token and then send a mail with the token.

I was generating the token inside a model function and then sending the mail in a  perform_later  using globalid.

I end up sometimes with no token in the mail, due to the concurrency of db access and asynchronous execution I guess ?

Will it be a better practice to do the update with the token generation inside the job to ensure it is made in the same thread ?

thanks for your help, sorry if it's a dumb question !

**Comment by mperham** [comment]
It's not a dumb question but this is a better question for StackOverflow.
