### ISSUE TITLE
SystemExit swallowed

### ISSUE THREAD

**Issue by axos88** [mperham/sidekiq#4295]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.1

I would like to create a worker that can force sidekiq to exit. Can't do it, because it seems like SystemExit is swallowed. 
The use case is that I want to have a special queue that is processed from time to time from a different machine (my laptop) that does not continously run. I'd like to be able to kick this process off, it should run, and process a few jobs, then when a specific condition is met (nothing more to do), it should exit.

**Comment by mperham** [comment]
This is not and won't be a supported use case.  You'll need to roll your own.

**Comment by axos88** [comment]
@mperham Any reason as of why? Catching all exceptions is not considered a good practice, because you are also catching things such as NoMemoryError, ScriptError, SecurityError, SignalException, SystemStackError, which sidekiq isn't able to gracefully handle. 
In case the system runs out of memory catching NoMemoryError will result in sidekiq trying to carry on as if nothing happened, which is clearly not the correct way to handle it.

Can you elaborate why catching exceptions is not restricted to StandardError, and let ruby clean up and handle the other cases? Then a supervisor can restart the sidekiq process if that's desired.

**Comment by axos88** [comment]
@mperham Btw, the problem is that I cannot "roll my own", because all methods to exit the process are swallowed.

**Comment by mperham** [comment]
SystemExit is sent to all worker threads to signal that Sidekiq is shutting down.  It is not a way for a worker to signal that Sidekiq should exit.

You can have the worker thread call `Process.kill("TERM", $$)` to trigger a clean shutdown.

**Comment by axos88** [comment]
Yeah that works. Thanks!
