### ISSUE TITLE
Sidekiq.logger.class.with_context gets overridden by Sidekiq

### ISSUE THREAD

**Issue by bobvanderlinden** [mperham/sidekiq#4296]
Ruby version: all
Sidekiq / Pro / Enterprise version(s): master

Currently on master Sidekiq will always extend the `logger` to include `Sidekiq::LoggingUtils`. This results in `with_context` always being overridden upon setting the `Sidekiq.logger`. See:

https://github.com/mperham/sidekiq/blob/cd2be18a8fdd479aea330d22fadc99f779cc7d1c/lib/sidekiq.rb#L208

Even if the logger that is being set implements their own version of `with_context`, the method will be overridden by Sidekiq. There is little a logging framework (like SemanticLogger) can do to properly support Sidekiq this way.

Any help regarding supporting Sidekiq in SemanticLogger would be helpful: https://github.com/rocketjob/rails_semantic_logger/pull/95

**Comment by mperham** [comment]
What’s your alternative suggestion?

**Comment by bobvanderlinden** [comment]
I think there are a few options:

### Checking for `with_context`

```
logger.extend(Sidekiq::LoggingUtils) unless logger.method_defined? :with_context
```

### Checking for `Sidekiq::LoggingUtils` module
Exposing `Sidekiq::LoggingUtils` publicly and:

```
logger.extend(Sidekiq::LoggingUtils) unless logger.class.include? Sidekiq::LoggingUtils
```

### Requiring `with_context`

Not touching the `logger` at all and requiring the logger to have a `with_context` method.

This solution will probably break some existing implementations, but I think it's the cleanest one.

### Not using `with_context`

Sidekiq currently uses `with_context` in a few places, but it's not a method that's part of Rails logging interface. Not using it when it's not available would resolve the issue as well.

**Comment by mperham** [comment]
I agree, I really dislike this metaprogramming. I would like to extract this functionality out of the logger itself and assume the logger is nothing more than a stdlib Logger. Let me think about it.

**Comment by mperham** [comment]
I tried reimplementing Sidekiq::Logger as a delegator but the code quickly gets pretty nasty. One reason is because ::Logger#add uses `@level` directly rather than calling a method to fetch the current level so it's very tricky to implement thread-specific log levels.

I don't want to make a runtime respond_to? check for every job execution. I don't want to force Logger instances to implement a with_context. What about using a static method?  It's only referencing local arguments and a TLV.

```
class Sidekiq::Logger
    def self.with_context(hash)
      ctx.merge!(hash)
      yield
    ensure
      hash.each_key { |key| ctx.delete(key) }
    end

    def self.ctx
      Thread.current[:sidekiq_context] ||= {}
    end
end
```

**Comment by mperham** [comment]
How does that look? ^^^^^^

**Comment by bobvanderlinden** [comment]
Nice! Yes, I think that'll work great!
