### ISSUE TITLE
What exactly does `config.redis = { size: 1 }` mean?

### ISSUE THREAD

**Issue by denishaskin** [mperham/sidekiq#4297]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.3

Please include your initializer and any error message with the full backtrace.

```
Sidekiq.configure_client do |config|
  config.redis = { size: 1 }
end
```

From various discussion, I'm pretty sure that `config.redis = { size: 1 }` is the source of `Timeout::Error: Waited 1 sec` errors in our environment.  But I'm having a devil of a time figuring out exactly what `size` means in that line.  I'm pretty sure it's passed straight through to redis, no?

This is a Rails app on Heroku, we're configured as:

web dynos: 3
worker dynos: 2

web: 3 dynos * 1 conn per process (sidekiq.rb) = 3 conns
workers: 2 workers * (5 redis connections per worker (by default) + concurrency set to 16) = 42

According to Redis stats page, we're at 50 connections about 90%+ of the time, occasionally bumping as high as 53.

**Comment by mperham** [comment]
That means your web dynos will use a max of one connection to push jobs to Redis, no matter how many threads they have.

Sidekiq 4 is not supported anymore.  You should upgrade to 5 some time soon.
