### ISSUE TITLE
SortedSet scan method

### ISSUE THREAD

**Issue by HolyWalley** [mperham/sidekiq#4304]
Ruby version:
Sidekiq: 6.0.0

According to the documentation here: https://github.com/mperham/sidekiq/wiki/API#scan 

method `scan` has been available since the 6.0.0 version of Sidekiq, however, I can't find it here 
(https://github.com/mperham/sidekiq/blob/v6.0.0/lib/sidekiq/api.rb#L529)

as I did on the master branch (https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L556).

**Comment by mperham** [comment]
Yep, the wiki says 6.0.  The scan method is in 6.0.1 (which is pending release very soon).
