### ISSUE TITLE
Sidekiq frozen process

### ISSUE THREAD

**Issue by seddarj** [mperham/sidekiq#4310]
Ruby version: 2.6.2
Sidekiq / Pro / Enterprise version(s): 4.2.10

Hi, we're having an issue where a Sidekiq process will randomly freeze and stop processing jobs. When this happens, the process is completely unresponsive and won't respond to signals and the CPU utilization at 0%.

I tried sending a `TTIN` signal to the frozen process but that doesn't do anything, no logs in our log files. Therefore I used `gdb` to generate the following backtrace: 

https://gist.github.com/seddarj/a8c8c13d5f059086851935a08041c1b8

**Comment by mperham** [comment]
therubyracer is not threadsafe. 

https://github.com/cowboyd/therubyracer/issues/432

**Comment by seddarj** [comment]
Thanks for the lightning fast answer!

(Probably could have seen that in the dump myself)
