### ISSUE TITLE
Sidekiq 6.x / ActiveJob queue name not honored

### ISSUE THREAD

**Issue by n-rodriguez** [mperham/sidekiq#4311]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): Community gem

I've updated Sidekiq from 5.2 to 6.x and it seems that queue name is not honored on 6.x :

```ruby
# classes
class ApplicationJob < ActiveJob::Base
end

class AsyncJob < ApplicationJob
  def perform(params = {}, context = {})
    AsyncOperation.({ params: params }.merge(context))
  end
end

class FifoJob < AsyncJob
  queue_as :fifo_job
end

# test
require 'rails_helper'

RSpec.describe FifoJob do
  it { is_expected.to be_processed_in 'fifo_job' }
end
```
With Sidekiq 6.x it returns `default`
Tests are run with [rspec-sidekiq](https://github.com/philostler/rspec-sidekiq)

After some searches I found this :

https://github.com/philostler/rspec-sidekiq/blob/develop/lib/rspec/sidekiq/matchers/be_processed_in.rb#L23

```ruby
# Sidekiq 5.2
puts FifoJob.get_sidekiq_options
no method error

puts FifoJob.queue_name
fifo_job

# Sidekiq 6.x
puts FifoJob.get_sidekiq_options
{"retry"=>true, "queue"=>"default"}

puts FifoJob.queue_name
fifo_job
```

**Comment by mperham** [comment]
Looks like rspec-sidekiq is buggy. ActiveJob overrides the sidekiq_option for queue so this looks like expected behavior.

**Comment by DmitryDD** [comment]
hey @n-rodriguez did you find the way to solve this? I'm facing exactly the same problem 😔
