### ISSUE TITLE
How kill Sidekiq workers on Heroku?

### ISSUE THREAD

**Issue by yu-coder** [mperham/sidekiq#4315]
Hi, I am running **Sidekiq workers** on Heroku by running
`CustomerWorker.perform_async` on **Heroku rails console**.

What is the best way to kill those **Sidekiq workers**?

**Comment by mperham** [comment]
Stop the process. Stopping a thread is not safe.

**Comment by yu-coder** [comment]
I see. But sometimes I need to update code and re-run.

**Comment by mperham** [comment]
Yes, that’s exactly what a deploy does. Have you read the Deployment wiki page?

**Comment by yu-coder** [comment]
Thank you.
But can I kill **Sidekiq workes** without pushing any unfinished jobs back to **Redis**?

**Comment by mperham** [comment]
No. That would lose jobs and Sidekiq tries very hard not to lose jobs.

**Comment by yu-coder** [comment]
I see.
Thank you.

**Comment by yu-coder** [comment]
Hi @mperham sorry commenting about this issue again!
But I could kill Sidekiq workers but they started again even I hadn't run.

**Comment by mperham** [comment]
I don't know what you are trying to do.  Why are you doing this?

**Comment by yu-coder** [comment]
Locally, I could kill running Sidekiq workers by running this command.
**ps -ef | grep sidekiq | grep -v grep | awk '{print $2}' | xargs kill -9**

I want to know the way to kill on Heroku like locally.

**Comment by mperham** [comment]
Again, please explain to me why you are killing the Sidekiq process without any warning.  **This is a terrible idea.**

**Comment by yu-coder** [comment]
There was an error on my old Sidekiq worker. So it failed.
I updated the worker and want to run again.

**Comment by mperham** [comment]
Starting in Rails 5.0, Sidekiq supports auto-reloading changed code in development.  You don't have to do anything.

Why are you daemonizing Sidekiq in development?  Run `bundle exec sidekiq` in your Terminal and hit Ctrl-C to stop Sidekiq.

**Comment by mperham** [comment]
Heroku will automatically restart Sidekiq when you push to heroku:master.

**Comment by yu-coder** [comment]
I see. 
Thank you.
