### ISSUE TITLE
Worker not sending email with custom mailer after Rails 5 upgrade

### ISSUE THREAD

**Issue by samuelebistoletti** [mperham/sidekiq#4320]
Hi,
we are using Sidekiq 6.0.1 free with Rails 5.1.7 (upgraded from Rails 3.2).

We have many workers that are not sending email any more, no idea why. Worker is scheduled, executed successfully without any exception, but it seems that method call to mailer is not performed. For example:

```
class ReservationMailerWorker
  include Sidekiq::Worker

  sidekiq_options retry: false
  sidekiq_options queue: "mail"

  def perform(user_id, seat_ids, pj_id, group_code)
    TicketMailer.reservation_email(user_id, seat_ids, pj_id, group_code)
    # method "reservation_email" is not called, also tried with raise inside method, but nothing happens: worker successfully executed, but no action is performed, neither any exeception.
  end
end
```

And this is the mailer:

```
class TicketMailer < ApplicationMailer
  layout "mail", only: [:ticket_email, :product_ticket_email]

  def reservation_email(user_id, seat_ids, pj_id, group_code)
   # ......... code ....

    Support::MailerUtility.try_deliver(@user) do
      mail(from: Settings.app.notifications.default_mail_sender, reply_to: @current_cinema.email, to: @user.email, subject: reservation_subject).deliver
    end
  end
end
```

Any idea why? Could be a Sidekiq issue or an error on our side?

Thanks

**Comment by mperham** [comment]
Shouldn’t that be deliver_now?

**Comment by samuelebistoletti** [comment]
No way also with deliver_now.
But the point is that for some strange reason no code inside that method or, in general a mailer method, is executed. The call to TicketMailer.reservation_email(user_id, seat_ids, pj_id, group_code) or to any other method inside classe TicketMailer is ignored.

**Comment by fatkodima** [comment]
@samuelebistoletti Can you provide a minimal reproducible test script, which shows a problem?

**Comment by samuelebistoletti** [comment]
Not really, to make that working it needs all the codebase. But I think that an empty mailer or with random text and the worker I provided in that issue should be enough to reproduce the issue.

```
class TicketMailer < ApplicationMailer
  def reservation_email
    mail(from: "noreply@example.com", to: "someone@example.com", subject: "test").deliver

# and some kind of view for email body
  end
end
```

```
class ReservationMailerWorker
  include Sidekiq::Worker

  sidekiq_options retry: false
  sidekiq_options queue: "default"

  def perform
    TicketMailer.reservation_email
  end
end
```

**Comment by fatkodima** [comment]
> Rails 5.1.7 (upgraded from Rails 3.2).

It is a really bad idea to upgrade several major versions at a time.

Here is what is working for me:
Sidekiq 6.0.1
Rails 5.1.7

```ruby
class TicketMailer < ApplicationMailer
  def reservation_email
    mail(from: "noreply@example.com", to: "someone@example.com", subject: "test") # <== no need to call deliver
  end
end

class ReservationMailerWorker
  include Sidekiq::Worker

  sidekiq_options retry: false
  sidekiq_options queue: "default"

  def perform
    TicketMailer.reservation_email.deliver_now # <=== need to call deliver_now
  end
end

ReservationMailerWorker.perform_async
```
