### ISSUE TITLE
Determine what queue a worker is running on from the worker.

### ISSUE THREAD

**Issue by mijoharas** [mperham/sidekiq#4324]
Ruby version:
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.7

Please include your initializer and any error message with the full backtrace.

Are you using an old version? yes
Have you checked the changelogs to see if your issue has been fixed in a later version? checked the code

If I use the `.set(*args)` api to set some arguments for my sidekiq job (i.e. what queue it runs on) is there a way to determine from within the worker what queue it is running on?

As far as I can tell, it's only the `jid` that gets set on the worker, should the worker instances `sidekiq_options_hash` get set to whatever options the sidekiq job was actually enqueued with?

I'd probably be happy to throw together a Pr, just wanted to:
a) check I'm not missing anything obvious
b) check whether this is something that would be wanted.

**Comment by mperham** [comment]
There is no way and this is by design. The only state available to a job is the JID, BID and arguments.

**Comment by mijoharas** [comment]
Ah, I wondered if it was by design. Could you explain why?

For context, my intended usecase, is a job triggering another job, and setting the queue of the job that is triggered to the same queue as the triggering job. I could obviously pass the priority in as an argument as well as calling `set()` to do what I want, but that doesn't look very nice.

So reasons I could guess for banning the job from inspecting the options set on it:
* introducing this would encourage people to write worse code. (I guess allowing introspection of sidekiq options could be bad, but the default options are available, so this isn't really different, and the code example above is definitely qualitatively worse).
* what people want to do with this api can be more easily/cleanly achieved with other features (if so, please let me know if I'm missing something!)
* introducing this would introduce unnecessary complexity to the codebase.
* something I'm not thinking of. (please let me know!).

Thanks for your prompt response, as always.

**Comment by mperham** [comment]
If the worker can access it magically, it's global state that becomes hard to understand and debug. The design ethos is that the only worker state is the class name and perform arguments, to keep the mental model simple.
