### ISSUE TITLE
Getting number of Sidekiq process working on a queue

### ISSUE THREAD

**Issue by fatkodima** [mperham/sidekiq#4329]
When there are many queues and processes, for debugging purposes, it is hard to track how many (if any) processes are working on a queue. So it will be useful to have official api to retrieve this count and retrieve those processes. Those counters can be also displayed on queue page in web ui.

**Comment by mperham** [comment]
The working data is asynchronous meaning it’s not reliable. I don’t want to give people too many APIs of that nature because they can’t rely on it. That’s my concern here.

**Comment by fatkodima** [comment]
Got your point 👍
