### ISSUE TITLE
Questions about migrating to Sidekiq 6 from Sidekiq 5 regarding pidfile and logfile

### ISSUE THREAD

**Issue by feliperaul** [mperham/sidekiq#4335]
Ruby version:
Sidekiq / Pro / Enterprise version(s): sidekiq opensource

Mike, this is the third weekend I've set myself to update Sidekiq to version 6.0 and couldn't manage it 😕

I'm a Rails developer with little DevOps knowledge, so the migration guide didn't contain enough information for me to fully understand the steps I must take to migrate and feel safe about doing so. I hope that with this post I can help other future searchers and maybe issue a pull request to improve the migration guide.

We alredy use Ubuntu's `systemd` to mange our sidekiq as a service for us. Here's our `sidekiq.service` file:

```
[Unit]
Description=Sidekiq

After=network.target syslog.target redis.service mysql.service
Wants=network.target syslog.target redis.service mysql.service

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=app

Environment=RAILS_ENV=production
WorkingDirectory=/var/www/app/current

PIDFile=/var/www/app/shared/tmp/pids/sidekiq.pid

ExecStart=/usr/local/rvm/bin/rvm default do bundle exec sidekiq -e production -C /var/www/app/current/config/sidekiq.yml
ExecReload=/bin/kill -TSTP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID

RestartSec=3
Restart=always

StandardOutput=syslog
StandardError=syslog

SyslogIdentifier=sidekiq

# Greatly reduce Ruby memory fragmentation and heap usage
# https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
Environment=MALLOC_ARENA_MAX=2
```

And here's our `sidekiq.yml` file:

```
---
:concurrency: 25 
production:
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq_production.log
development:
  :logfile: ./log/sidekiq_development.log
:queues:
  - high
  - low
  - average
```

## PID file removal

If I understood correctly, I can remove the lines PIDFile from `sidekiq.service` and `:pidfile` from sidekiq.yml since they are now useless?

What about `ExecReload` and `ExecStop` lines, they should be removed as well (I see your example [systemd sidekiq.service](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service) file don't contain them).

Removing all these lines, do I have to do anything else? How can I be sure sidekiq is actually being restarted correctly and reloading my application code?

## Logging
It's stated on the logging wiki that "As of Sidekiq 6.0, Sidekiq does not directly support log redirection". So If I understand correctly, the `logfile` line in `sidekiq.yml` has no use anymore.

We had very good user experience by using `/log/sidekiq_production.log`, since it was very quick and easy to check and debug, and we had logrotate installed on /log folder (as I assume most Rails deploy do since I still havent' seen a deploy guide without it). 

Sorry for the very naive question but if you now log to `stdout`, where exactly should I find sidekiq logs? My systemd sidekiq.service (pasted above) is using `StandardOutput=syslog`, which I assume is an override of stdout, but I don't fully understand where I'll see logs in production now.

**Comment by mperham** [comment]
What Linux distro and version are you on?

**Comment by feliperaul** [comment]
Ubuntu 16, about to migrate to 18.

**Comment by mperham** [comment]
Yes, remove the PIDFile option; it does not apply to Sidekiq as it is not a forking daemon.

As for logging, you can do this in Ubuntu 18.04+:

```
StandardOutput=file:/var/log/sidekiq.log
```

I'm not sure if that will ever rotate logs though, it could get huge over time.  Might be better to let it go through syslog so it can be rotated automatically.  See also here on how to redirect syslog entries to a specific file:

https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file#43830129

**Comment by mperham** [comment]
Leave the Exec* lines.  Those are useful.

**Comment by feliperaul** [comment]
Thank you!

**Comment by vizcay** [comment]
```
StandardOutput=file:/var/log/sidekiq.log
```

At least for me is not working as intended as it does not appends to the file when the service gets reloaded.

For that you need:
```
StandardOutput=append:/var/log/sidekiq.log
```
But unfortunately is only available in systemd v240+ (https://github.com/systemd/systemd/blob/fb906b00c68e34b8692e207a658bcfa3df62456c/NEWS#L3354) so it doesn't works on Ubuntu Server 18.04.
