### ISSUE TITLE
'Wake up' quiet Sidekiq Processes

### ISSUE THREAD

**Issue by andrewlynch** [mperham/sidekiq#4336]
Ruby version: Puma with Ruby 2.6   
Sidekiq v5.2.7

I've deployed my Rails app with AWS EB. The one process seems to go quiet and doesn't 'Wake up' when there are 10k jobs enqueued. How does one wake up a sidekiq process or prevent it from going quiet in the first place?

<img width="1209" alt="Screen Shot 2019-10-15 at 14 52 36" src="https://user-images.githubusercontent.com/684735/66833201-aa50df80-ef5b-11e9-966e-c891f680506a.png">

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Signals#tstp

There is no way to "unquiet" Sidekiq.  Once quieted, the process must exit.
