### ISSUE TITLE
Question on sidekiq batches

### ISSUE THREAD

**Issue by HarrisJT** [mperham/sidekiq#4339]
Ruby version: Ruby 2.3.7
Sidekiq / Pro / Enterprise version(s): Sidekiq v5.2.7

Regarding Sidekiq batches: Will the "batch job" tie up one of the worker threads while the individual jobs it's watching process? In theory, I think I could get to a spot where all my workers are just batch watch jobs? With just 5 threads for example, if 5 workers are queued up and they start batches of another worker job, none of those will be able to be processed because there are no threads and my whole sidekicks will be blocked.

Is there a mechanism for preventing this or a better architectural pattern for handling this? Possibly having the batch on a separate queue with its own threads?

**Comment by mperham** [comment]
There is no parent batch job.  Each batch job updates the batch status as it completes. Yes, if you create a batch with 100 jobs and have one Sidekiq process with 10 worker threads, it's possible that all 10 threads will be processing jobs for that batch, excluding others.  The solution is to start more Sidekiq processes so you have enough workers to drain your queues quickly.

**Comment by HarrisJT** [comment]
Thanks!
