### ISSUE TITLE
Failed Job not going to RetrySet

### ISSUE THREAD

**Issue by chrisjwu** [mperham/sidekiq#4341]
Ruby version: 2.6.4

Sidekiq / Pro / Enterprise version(s):
Sidekiq 5.2.7 / Pro 4.0.5

Initializer:

```
redis_config = Rails.application.config_for(:redis)
redis_url = "#{redis_config['host']}:#{redis_config['port']}"
redis_url = 'redis://' + redis_url if redis_url !~ /^redis:\/\//

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.redis = { url: redis_url, netowrk_timeout: 2, db: 1 } 
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url, netowrk_timeout: 2, db: 1 } 
end
```

A few hours ago, we had a db freakout causing ~500 failures.  My understanding was that failed jobs would go into the RetrySet, instead they were requeued back into the original queue:

```
# rails c
Loading production environment (Rails 5.2.3)
irb(main):001:0> Sidekiq::RetrySet.new.size
=> 0
irb(main):002:0>  queue = Sidekiq::Queue.new('slow_batch_run_1')
=> #<Sidekiq::Queue:0x000055ed549098a8 @name="slow_batch_run_1", @rname="queue:slow_batch_run_1">
irb(main):003:0> queue.detect { |job| job.item.has_key? 'error_backtrace' }
=> #<Sidekiq::Job:0x000055ed54964488 @args=nil, @value="{\"queue\":\"slow_batch_run_1\",\"class\":\"LocationsWorker\",\"args\":[9636079],\"retry\":5,\"backtrace\":10,\"jid\":\"8f1463be6df24792bcac7c5f\",\"created_at\":1571266975.2583575,\"enqueued_at\":1571282597.4532022,\"bid\":\"EFtAkinSHcAIFg\",\"error_message\":\"Incomplete state: initialized for id 9636079\",\"error_class\":\"LocationException\",\"failed_at\":1571282293.3838565,\"retry_count\":0,\"error_backtrace\":[\"/monstro/app/workers/locations_worker.rb:37:in `perform'\",\"/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'\",\"/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'\",\"/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\",\"/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'\",\"/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'\",\"/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'\",\"/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/usr/local/bundle/gems/sidekiq-pro-4.0.5/lib/sidekiq/batch/middleware.rb:29:in `call'\",\"/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\"]}", @item={"queue"=>"slow_batch_run_1", "class"=>"LocationsWorker", "args"=>[9636079], "retry"=>5, "backtrace"=>10, "jid"=>"8f1463be6df24792bcac7c5f", "created_at"=>1571266975.2583575, "enqueued_at"=>1571282597.4532022, "bid"=>"EFtAkinSHcAIFg", "error_message"=>"Incomplete state: initialized for id 9636079", "error_class"=>"LocationException", "failed_at"=>1571282293.3838565, "retry_count"=>0, "error_backtrace"=>["/monstro/app/workers/locations_worker.rb:37:in `perform'", "/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'", "/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'", "/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'", "/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'", "/usr/local/bundle/gems/newrelic_rpm-6.7.0.359/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'", "/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-pro-4.0.5/lib/sidekiq/batch/middleware.rb:29:in `call'", "/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'"]}, @queue="slow_batch_run_1">
```

**Comment by chrisjwu** [comment]
I went back and looked at server logs and none of the servers restarted either.  Not sure what other information would be helpful to identify this issue, or if I'm just misunderstanding how retries work.

**Comment by mperham** [comment]
`netowrk_timeout`: misspelled.

Jobs go into the RetrySet for some amount of time and then are pushed onto the original queue so workers can fetch and re-execute them.

**Comment by chrisjwu** [comment]
> `netowrk_timeout`: misspelled.

Good catch, fortunately hasn't broken anything yet!

Ok, thanks for the explanation, I always assumed the retry set counting down was due to workers pulling directly off it, must have missed that detail in the documentation.

I'm thinking of doing away with retries altogether per another issue about on_complete / on_success callback behavior (I can't find the issue number atm).  Where you recommended pushing a new job rather than retrying in order to use the on_complete callback to act as a 'all jobs finished with or without errors' callback.  As part of that I could also requeue the failed job into a higher priority queue to approximate it's place in line.

Does that sound like a workable approach?

**Comment by mperham** [comment]
I don’t understand the context enough to be able to recommend any approach.

**Comment by chrisjwu** [comment]
Found the comment I was thinking of: https://github.com/mperham/sidekiq/issues/2250#issuecomment-85167186

Our callback generates a csv summarizing the job results for a batch, so failures are fine to include in there.  Right now, I'm manually debugging failures to get the batch to success, but that isn't scalable or necessary I'm thinking (external services can't be trusted 100%).  It's been on my to-do to change this behavior.

I wanted to make sure this was still a recommended approach since I saw this comment - https://github.com/mperham/sidekiq/issues/2877#issuecomment-193981169

And while i was in there, I was thinking of doing something like this to keep batches from getting stuck behind later batches if a job retries.

```
      batch.jobs do
        # reopen the batch and add a new job to act as the retry
        Sidekiq::Client.enqueue_to_in(:retries, retry_count.minutes, self.class, retry_count+1, *args)
      end
```

**Comment by mperham** [comment]
I'm confused.  You want to fire a callback when all batch jobs have been executed, with or without failures, right?  But that's exactly what `on(:complete)` does.  So why not use that instead of :success?

**Comment by chrisjwu** [comment]
I wanted to have a small number of retries to give external services a chance to respond successfully before running the csv.  So when all jobs in batch are successful or dead basically.

**Comment by mperham** [comment]
Batches support an undocumented `on(:death)` callback which is fired by the first job that dies within a batch, you can use it in tandem with :success.  Maybe I should document it??? 🤪

**Comment by chrisjwu** [comment]
I did come across that before, I think I'll go back and see if some combination of these callbacks will get me to where I want.  Thanks for your time.

**Comment by mperham** [comment]
Updated the Batches wiki a bit to add more detail.
