### ISSUE TITLE
Feature Request: Add Pause button to Sidekiq UI

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#4343]
Having the ability to pause a queue without launching a Ruby shell of some sort seems like a no brainer. It would be particularly useful to pause or unpause a misbehaving queue from a phone when a computer is not easily accessible. I had just such an issue last night where I was out and one queue with newly deployed jobs was draining resources from all other jobs. Simply pausing the queue allowed everything else to proceed as usual until the offending job was fixed, but it all had to wait until I could find a computer.

Would you be open to a PR for this?

**Comment by mperham** [comment]
My belief is that if you want to pause a queue, there's usually a more involved process that needs to happen (alert emails sent, maybe a Slack warning, add a security or audit trail, etc).  You should build your own UI with a button to enable that entire process and use the `Sidekiq::Queue#pause!` API in that button handler.

**Comment by jakemack** [comment]
Ideally, that would be the case, but unfortunately the real world isn't ideal. Such a button is useful for the emergencies where a process hasn't been built around an issue yet. Ideally, one would have time to build that process after the first such emergency but unfortunately, not all businesses cooperate with that logic. It could be that the cost of building such a system around it is not worth the extra cost to the business when a manual, ad-hoc pause suffices.

In addition, a number of the other features in the Web UI also follow such logic: usually there should be a more involved process for quieting or stopping a given worker, there should likely be a more involved process around deciding to run a scheduled job earlier than scheduled, etc. Apart from a few easily viewable metrics, the Web UI is really a collection of conveniences for ad-hoc manipulation of Sidekiq. Adding one more seems to fit right in with the theme. And until you can say there is _always_ a more involved process around an action, there will be situations where an ad-hoc, manual action is appropriate.

**Comment by mperham** [comment]
Ok, I can be flexible here and willing to consider a PR if you want to put something together. Take a look at the Filtering code if you want to see a similar feature.

**Comment by jakemack** [comment]
Awesome, I'll see what I can put together

**Comment by shayonj** [comment]
Came across this multiple times (operationally, mostly) in the past and every time I felt it'd be nice to have this feature. So, I whipped a quick PR :). There are some open questions in the PR as to supporting this behavior cleanly between regular version of sidekiq and sidekiq pro.

**Comment by mperham** [comment]
Now available in Sidekiq 6.0.4.
