### ISSUE TITLE
b-XXX-died jobs consuming redis memory 

### ISSUE THREAD

**Issue by aclarembeau** [mperham/sidekiq#4344]
Ruby version:2.6.3

Sidekiq / Pro / Enterprise version(s):
sidekiq (5.2.7)
sidekiq-pro (4.0.5)

Hi, 

Recently, we discovered that the memory that the Redis instance linked to sidekiq is consuming more and more memory every day. 
After investigating, we found that it was caused by sidekiq creating keys like b-XXX-died job for our died jobs. But, they don't seem to clear automatically. 

So, could someone help me to understand: 
1. If we can safely flush those keys 
2. Why aren't they deleted automatically (are they used for some purpose)? 

Thanks a lot

**Comment by fatkodima** [comment]
You need to upgrade to Pro >= 5.0
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#500

**Comment by aclarembeau** [comment]
Perfect, thanks a lot. 
Do you know if there is some specific manipulation to remove them from redis once the migration has been done. Do we need to do it manually or sidekiq will do it?

**Comment by mperham** [comment]
New batches won’t do it. Old batches will eventually go away. There’s no quick cleanup.
