### ISSUE TITLE
Can't only run more than 6 workers on Heroku

### ISSUE THREAD

**Issue by yu-coder** [mperham/sidekiq#4346]
Hi,
I want to run more than 5 workers like 6~7 workers synchronously but can only run max 5 workers on Heroku.

This is my **Procfile**.
`myworker: bundle exec sidekiq -c 10`

Could anyone help me?

**Comment by courtsimas** [comment]
What error do you run into? Is it a database pool issue? Ram issue? What causes you to believe you can't run more than 5?

**Comment by yu-coder** [comment]
@courtsimas 
I am getting this issue.
**not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use**

Currently, I am running 8 workers.

DB_POOL: 100
Sidekiq_Concurrency: 10
RAILS_MAX_THREADS: 25

But 5 workers work without issue. Only 3 workers are having that issue.

**Comment by yu-coder** [comment]
I think my issue is related to the DB pool size.
It seems it is only 5 even I set DB pool size more than 10.

**Comment by courtsimas** [comment]
Well you’ve got 25 rails threads and 10 (default) for your sidekiq concurrency, and if all of them need to run at once, you’ll probably need more than 100 db connection in the pool.

**Comment by yu-coder** [comment]
Currently, I am using `standard-0` Heroku Postgres plan which max connection limit is `120`
