### ISSUE TITLE
Hide Dead Job Retry All and Delete All Buttons

### ISSUE THREAD

**Issue by mkolenda** [mperham/sidekiq#4347]
Ruby version:
Sidekiq Version: 5.2.5
Sidekiq Enterprise version(s): 1.7.2

Please include your initializer and any error message with the full backtrace.

sidekiq.rb
```
require 'sidekiq-ent'

Sidekiq.configure_client do |config|
  config.redis = SIDEKIQ_REDIS_CONNECTION_POOL
end

Sidekiq.configure_server do |config|
  config.redis = SIDEKIQ_REDIS_CONNECTION_POOL

  config.periodic do |mgr|
    # The DynamicJobWorker needs to be in the most important queue so it is processed as often as reasonable
    mgr.register('* * * * *', ::Jobs::Engine::DynamicJobWorker, retry: 0, queue: 'jimmy_page', backtrace: true)
  end
end
```
I'm trying to hide the `Retry All` `Delete All` buttons on the `/morgue` page.  This commit exposes a way to do that: https://github.com/mperham/sidekiq/commit/e537b4dffb61e17deba71e496a0de0cb3426b8c5#diff-7bcd419e60ea7ae098e18f5a09f58fc1

I'm struggling to prepend `/filter` to the rackenv `PATH_INFO` value. 

Here is a middleware I wrote to do just that (results in a routing error)

```
class HideButtons
  def initialize(app)
    @app = app
  end

  def call(env)
    @status, @headers, @response = @app.call(env)

    puts "BEFORE PATH_INFO: #{env["PATH_INFO"] || ''}"

    env.merge!("PATH_INFO" => "/filter" + (env["PATH_INFO"] || ''))

    puts "AFTER PATH_INFO: #{env["PATH_INFO"] || ''}"

    @app.call(env)
  end
end
```

 Is there a document that shows how to do this? 

Thanks!

**Comment by mperham** [comment]
This is not a supported feature. The commit was so that a "Retry All" button on a filtered results page doesn't mislead the user into thinking that "Retry All" means "Retry the search results on this page".

**Comment by mkolenda** [comment]
Thanks for the quick response!
