### ISSUE TITLE
Dead Batch error: uninitialized constant Sidekiq::Batch::DeadSet::NoSuchBatch

### ISSUE THREAD

**Issue by zerobearing2** [mperham/sidekiq#4348]
Trying to iterate through dead batches get following error:
```
NameError: uninitialized constant Sidekiq::Batch::DeadSet::NoSuchBatch
```

Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): sidekiq-pro-5.0.1

Reproduce with following (assumes you have a dead batch): 
```ruby
bds = Sidekiq::Batch::DeadSet.new
bds.each{|s| s.dead_jids}
```
```
NameError: uninitialized constant Sidekiq::Batch::DeadSet::NoSuchBatch
Caused by Sidekiq::Batch::NoSuchBatch: Couldn't find Batch 8UFyk1R7wqnjtw in redis
from /...redacted.../vendor/bundle/gems/sidekiq-pro-5.0.1/lib/sidekiq/batch/status.rb:34:in `load_data'```

**Comment by mperham** [comment]
Are you requiring things manually?  If you do `require 'sidekiq-pro'`, that constant should be defined.

**Comment by zerobearing2** [comment]
I'm using Rails (autoload), but I tried to manually require too, no joy. I think the namespace is off in the `Sidekiq::Batch::DeadSet` class. To fix, I patched file locally:

```ruby
# sidekiq-pro-5.0.1/lib/sidekiq/batch/death.rb#47
rescue NoSuchBatch
```
to
```ruby
# sidekiq-pro-5.0.1/lib/sidekiq/batch/death.rb#47
rescue Sidekiq::Batch::NoSuchBatch
```

**Comment by mperham** [comment]
Thanks for pointing this out.  Batch data can expire normally after 30 days OR you might have Redis misconfigured and the data was purged when under memory pressure.  Make sure you've enabled `noeviction`:

https://github.com/mperham/sidekiq/wiki/Using-Redis#memory
