### ISSUE TITLE
Start processing jobs added to batch without waiting until all jobs are added?

### ISSUE THREAD

**Issue by ragulka** [mperham/sidekiq#4349]
I'm trying to figure out if it's possible to create a batch and add some jobs to it and have them start processing immediately, while I continue to add more jobs to the batch?

My use-case is to process around 30k items I'm fetching from an API. I'm paging through an API and creating a job for each returned item. My idea was that since I don't know how many pages there are, I would fetch the first page which has 50 items, add these to the batch, then fetch the next page, add them to the batch and so on. My hope was that while I'm fetching the next page, the first 50 jobs would already start processing.

However, no matter how I try, it seems that perhaps batches do not support this type of setup? It looks that the jobs added to a batch will only start processing when all the jobs have been added to the batch. I tried with re-opening the batch for each page, but that does not seem to have any effect.

Basically, I'm trying something like this:

```ruby
class ImportWorker
  def perform
    batch = Sidekiq::Batch.new

    chunk = []
    per_page = 50

    fetch_items(batch, per_page)
  end

  def fetch_items(per_page, page = 1)
    SomeClass.external_api_fetch(per_page) do |items, next_page|
      import_items batch, items
      fetch_items(per_page, next_page) if next_page?
    end
  end

  def import_items
    batch.jobs do
      Rails.logger.debug "Importing #{items.length} items (BID: #{batch.bid})"
      items.each do |item|
        ItemImporterWorker.perform_async item
      end
    end    
  end
end
```

FWIW, I have also tried with having the `ImportWorker` be part of the batch, and using `push_bulk`, but it seems to have no effect. The only difference I've seen was that the first 25 items start processing but will hang on the first DB query in the job - and only continue when all the jobs have been added to the batch.

Perhaps I am misusing batches? Are they _designed_ to _not_ start processing the jobs until the all jobs have been added to the batch? Am I re-opening the batch in the wrong place?

**Comment by mperham** [comment]
You’d need to use this same pattern:

https://github.com/mperham/sidekiq/wiki/Batches#huge-batches

**Comment by ragulka** [comment]
@mperham I believe that's what I originally tried, but the issue there was that while the jobs started to process, they hanged on the first ActiveRecord call (I was querying a model from the DB)... until all of the jobs were pushed to the batch. Only then would the jobs ActiveRecord call go through and return the DB record.

**Comment by ragulka** [comment]
Also, FWIW, I can't really fetch all the pages in parallel, because I do not know how many pages there are... I'm in a similar situation as in https://github.com/mperham/sidekiq/issues/2083 - I have to load the pages serially, until there are no more results from the API.

Basically, I would like to achieve this:
1. Fetch 1st page of items from API
2. Add items from 1st page to batch
3. Start processing jobs in the batch immediately
4. At the same time, fetch 2nd page of items from API
5. Add items from 2nd page to batch
6. Jobs from the 1st page may be finished now, or most likely still running. Either way, we should simply continue processing jobs in the batch
7. Fetch the next page... and loop until all pages have been fetched and no more items have been returned.

As you can see, I need to fetch pages in serial, but items can be processed in parallel. I do not need to wait for the items jobs to finish before I can fetch the next page.

**Comment by mperham** [comment]
So create a job to fetch the 2nd page, which then loads more batch jobs and creates a job to fetch the 3rd page....

**Comment by ragulka** [comment]
@mperham hmm, what you just said and based on your [comment here](https://github.com/mperham/sidekiq/issues/3401#issuecomment-288257963) I think I'm beginning to understand what I might be doing wrong...

My initial version which followed https://github.com/mperham/sidekiq/wiki/Batches#huge-batches more closely actually works, I was running into the same issue as https://github.com/mperham/sidekiq/issues/3401 Once I turned on eager loading in development, it started to process jobs immediately like expected.

Can it be that reason I'm running into this is because my initial job simply loops over the pages returned from the api, re-opening and closing the batch for each page to add jobs to it? Note that the initial job only finishes after fetching all pages. I think I see how breaking that initial job into pieces, by having the job only fetch 1 page at a time and then finish (while creating a job to fetch the next page) could help.

**Comment by mperham** [comment]
Yes, in development mode, Rails uses a lock to make Sidekiq single-threaded.  That's why your batch wasn't processing in parallel.

Batches push all jobs from the `jobs` block atomically at the end.  That's why the initial job scanning through each page doesn't process anything until the end.
