### ISSUE TITLE
Sidekiq Pro should have an ability to skip some queues from super fetch

### ISSUE THREAD

**Issue by arumugaraja-thirumani** [mperham/sidekiq#4351]
Ruby version: 2.4.7
Sidekiq / Pro / Enterprise version(s): 4.2.10/3.7.1

It would be better if we have an option to skip specific queues from the superfetch.

It will be useful in the cases like scheduled jobs, i.e the job is being triggered every n min. In this case it will be okay to skip a single schedule. I have done skipping the queues in my local server, I will be happy to share if you feel this is useful feature.

**Comment by mperham** [comment]
The current design requires one fetch algorithm per process.  You can create a different Sidekiq process that does not enable super_fetch and have it process specific queues.
