### ISSUE TITLE
How does Sidekiq handle - Redis::CommandError?

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#4353]
Curious how does Sidekiq treat the following error if it encounters it during `perform` method. In our case this happens during `perform_async` which is called from within another worker. Will the failing perform_async get retried?

`Redis::CommandError - OOM command not allowed when used memory > 'maxmemory'.`

Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): 6.0.3 (open source)
Rails: 6.0.0

**Comment by mperham** [comment]
It only looks for a READONLY warning which triggers a disconnect for failover purposes. Other errors, like that one, are raised to the application.  Note that the redis gem itself has support for retrying commands in case of error, which can cause problems like #3303.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L98
https://github.com/redis/redis-rb#reconnections

**Comment by kapso** [comment]
Great thanks, that helps.
