### ISSUE TITLE
CAN SOMEBODY FROM SIDEKIQ REACT ON MY EMAILS 

### ISSUE THREAD

**Issue by heldopslippers** [mperham/sidekiq#4355]
SO I have been mailing Sidekiq Enterprise for weeks now without a reaction
PLEASE REACT! ASAP

**Comment by mperham** [comment]
I have not gotten any emails. Can you please explain?

**Comment by heldopslippers** [comment]
Ah, weird. I have been mailing to the email-addresses on the site. (and also to the email that was sent to me when I signed up for enterprise edition).

**Comment by mperham** [comment]
I’m sorry to hear that. Anything sent to contribsys.com will get to me. No one else has reported problems but email is a complex thing, perhaps there is gum in the machinery somewhere. You are welcome to open issues here for me.

**Comment by heldopslippers** [comment]
Thanxs for that. I will send you the email via your github account. Closing this.
