### ISSUE TITLE
`Success` callback of a sidekiq batch is never fired

### ISSUE THREAD

**Issue by leandrogoe** [mperham/sidekiq#4361]
Ruby version: 2.6.1
Sidekiq / Pro / Enterprise version(s): 5.1.1 / 4.0.3 / N/A

We are running into a situation in which the success callback of a batch is never called and the pending job count of the Batch ends up being negative. I am not 100% sure, but the following seems to be the sequence of events that causes this behaviour:

1) A Sidekiq process that is running a given job X - which is part of batch - is instructed to be shut down. A warning stating that Job X is still in progress is logged out. 
2) Before the Sidekiq process is actually dead, Sidekiq manages to both  a) decrement the `pending` job count of the Batch and b) enqueue the job again back into the queue.
3) Job Y - also part of the batch - finishes and the batch `pending` count reaches zero. At this point the completed callback is created. Successful callback is not created yet, since the completed callback has not run.
4) Job X is re-run and the `pending` count reaches -1. 
5) Completed callback is run. Since the `pending` count is negative we don't run the successful callback.

It's not yet fully clear to me why the Sidekiq process keeps running for so long after the warning, I see that we immediately raise a `Sidekiq::Shutdown` after logging that message.

Any help is appreciated!

If helps here is the log showing the job re-run:

```
$ zgrep 3ffb0b5e8aaf63e5f1d67859 sidekiq*                                                                                                                                                               
sidekiq.log.24.gz:2019-11-04T20:12:18.032Z 72267 TID-70nl9nvn ExportManualChunkWorker JID-3ffb0b5e8aaf63e5f1d67859 BID--yWMyFRTAMRxRA INFO: start                                                       
sidekiq.log.24.gz:2019-11-04T20:12:28.032Z 72267 TID-70mc8faz WARN: Work still in progress [#<struct Sidekiq::Pro::SuperFetch::Retriever::UnitOfWork queue="queue:export_chunks", job="{\"class\":\"Expo
rtManualChunkWorker\",\"args\":[\"5dc0861ad27cbe124761d076\",95],\"lock_expiration\":86400,\"retry\":4,\"queue\":\"export_chunks\",\"environment\":\"production\",\"crash_limit\":5,\"jid\":\"1f861ed44e
d27ad28822a123\",\"created_at\":1572898334.838574,\"enqueued_at\":1572898337.075958,\"bid\":\"-yWMyFRTAMRxRA\",\"care_provider_id\":\"59c091e3d27cbe326af69d68\"}", local_queue="queue:sq|PROD-SK2-NJ-IB
M2:72267:dff2933a64a2|export_chunks">, #<struct Sidekiq::Pro::SuperFetch::Retriever::UnitOfWork queue="queue:export_chunks", job="{\"class\":\"ExportManualChunkWorker\",\"args\":[\"5dc0810aff16723f466
d8f2d\",7],\"lock_expiration\":86400,\"retry\":4,\"queue\":\"export_chunks\",\"environment\":\"production\",\"crash_limit\":5,\"jid\":\"fa32f1dd492a549527faf45b\",\"created_at\":1572898160.479705,\"en
queued_at\":1572898160.492984,\"bid\":\"ZjRd3kMXy5j61A\",\"care_provider_id\":\"5730ee00acc0db0fee00012f\"}", local_queue="queue:sq|PROD-SK2-NJ-IBM2:72267:dff2933a64a2|export_chunks">, #<struct Sideki
q::Pro::SuperFetch::Retriever::UnitOfWork queue="queue:export_chunks", job="{\"class\":\"ExportManualChunkWorker\",\"args\":[\"5dc0810aff16723f466d8f2d\",2],\"lock_expiration\":86400,\"retry\":4,\"que
ue\":\"export_chunks\",\"environment\":\"production\",\"crash_limit\":5,\"jid\":\"596d442a4963e7a372b89d25\",\"created_at\":1572898160.479705,\"enqueued_at\":1572898160.492984,\"bid\":\"ZjRd3kMXy5j61A
\",\"care_provider_id\":\"5730ee00acc0db0fee00012f\"}", local_queue="queue:sq|PROD-SK2-NJ-IBM2:72267:dff2933a64a2|export_chunks">, #<struct Sidekiq::Pro::SuperFetch::Retriever::UnitOfWork queue="queue
:export_chunks", job="{\"class\":\"ExportManualChunkWorker\",\"args\":[\"5dc0861ad27cbe124761d076\",70],\"lock_expiration\":86400,\"retry\":4,\"queue\":\"export_chunks\",\"environment\":\"production\"
,\"crash_limit\":5,\"jid\":\"3ffb0b5e8aaf63e5f1d67859\",\"created_at\":1572898334.838574,\"enqueued_at\":1572898337.075958,\"bid\":\"-yWMyFRTAMRxRA\",\"care_provider_id\":\"59c091e3d27cbe326af69d68\"}
", local_queue="queue:sq|PROD-SK2-NJ-IBM2:72267:dff2933a64a2|export_chunks">]                                                                                                                           
sidekiq.log.24.gz:2019-11-04T20:12:29.307Z 22274 TID-70rioixy ExportManualChunkWorker JID-3ffb0b5e8aaf63e5f1d67859 BID--yWMyFRTAMRxRA INFO: start                                                       
sidekiq.log.24.gz:2019-11-04T20:12:39.677Z 72267 TID-70nl9nvn ExportManualChunkWorker JID-3ffb0b5e8aaf63e5f1d67859 BID--yWMyFRTAMRxRA INFO: done: 21.646 sec                                            
sidekiq.log.24.gz:2019-11-04T20:12:42.545Z 22274 TID-70rioixy ExportManualChunkWorker JID-3ffb0b5e8aaf63e5f1d67859 BID--yWMyFRTAMRxRA INFO: done: 13.239 sec 
```

**Comment by mperham** [comment]
1. I would recommend you upgrade to Sidekiq 5.2.7 and Pro 4.0.5.
2. The -1 pending count always has the same cause: your deploy is `kill -9`ing the process. Solve that and the problem will go away.

**Comment by leandrogoe** [comment]
Thanks for the prompt reply!

We are not forcing a `kill -9`. We are killing the process based on memory limits using `sidekiqctl` (via Bluepill). Unfortunately we need to do that at some points, otherwise memory bloat can overload the server. 😢 

If you look at the log, you will see that the process still lives 10 more minutes after the signal is received.

**Comment by mperham** [comment]
I believe sidekiqctl itself will send a kill -9 if the process does not exit within the hard timeout. See the source.

Sidekiq Enterprise has memory monitoring and restart built in if you have the budget for an upgrade that will simplify your devops.

**Comment by leandrogoe** [comment]
I do see the same. However, the process did not die (it was still running even 10 minutes afterwards).

Anyway, I found a workaround for this issue, but I think Sidekiq pro code could be made more robust. We could easily restrict the manipulation of the `pending` counter so that it only takes place when the job id was not already removed, for instance:

```
conn.hincrby(key, "pending", -1) if conn.srem("#{key}-jids", jid) > 0
```

**Comment by mperham** [comment]
Any proposed solution will have a race condition between removing the job from Redis and decrementing the pending counter unless the operations are made atomically.  Unfortunately I haven't found a clean way to do this.
