### ISSUE TITLE
Global death_handler called before job is sent to morgue

### ISSUE THREAD

**Issue by Subskii** [mperham/sidekiq#4362]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0.3

Inside the global `death_handler`, we can send a notification to slack whenever a job dies but I am wondering how to construct a link back to the dead job as well e.g. `"sidekiq/morgue/#{job.score}-#{job.jid}` so that it can be easily retried?

I've noticed that the `death_handler` is called [before the job is sent to the morgue](https://github.com/mperham/sidekiq/blob/48cd79b886a2feaf12e78bba733a236b9f51a385/lib/sidekiq/job_retry.rb#L192-L198). This doesn't seem right to me and I'm wondering if it is intentional?

I think ideally the `death_handler` would be called _after_ the job is sent to the morgue... WDYT?

**Comment by mperham** [comment]
Sounds like a good idea. Do you want to send a PR?

**Comment by Subskii** [comment]
Awesome.

I'll get a PR up soon.
