### ISSUE TITLE
Safest method to retry hanging jobs?

### ISSUE THREAD

**Issue by 1001Tracklists** [mperham/sidekiq#4368]
Hey Mike,
first of all - thanks so much for all the great work you've been putting into Sidekiq! It's working absolutely great for us and we're processing over a million jobs daily!

We've been running into an issue where some of our API calls to the Spotify & Apple Music APIs seem to get stuck in the busy queue and clocking up our Concurrency Limit. Usually the jobs take an average of max 10 seconds to complete, and we comfortably hold a threshold of 30 jobs / 5seconds.

With more jobs stuck in the busy queue tho, we slow everything down, and some of them are in there for over an hour until eventually resolving themselves. I read up quite a bit about timeouts and expirations, and saw your repeated advice to be careful in ruby to timeout jobs.

Hence why the question: Which method right now is the safest and best to use, that if a job gets hung up in a weird state like this, to reschedule it and clear the thread for other jobs, and then eventually retry the original job that got hung up, so that it hopefully completes just fine.

Really appreciate your advice on this and thanks again for such great support across the board!

All the best,
Oskar

**Comment by mperham** [comment]
I don't know why but I never saw this issue.

Hanging means you don't have proper timeouts. Put timeouts on all your network calls. The timeout will raise an error, let Sidekiq retry it as normal. Don't overthink it.
