### ISSUE TITLE
More informative log messages

### ISSUE THREAD

**Issue by DannyBen** [mperham/sidekiq#4369]
I have recently seen info level log messages in my log, with zero useful information. Took me a while to track them down. They looked like this:

```
I, [2019-11-11T09:14:29.133599 #12808]  INFO -- : start
I, [2019-11-11T09:14:29.136168 #12808]  INFO -- : done
```

repeating multiple times.

I believe they come from here:

https://github.com/mperham/sidekiq/blob/daabec1c7bc6fede5a11ff1dbde9193495eaf2c4/lib/sidekiq/job_logger.rb#L11-L20

Shouldn't these messages be more informative, and say something about what is started / done / failing? Or if not possible, perhaps remove these altogether?

**Comment by mperham** [comment]
You are not using the default Sidekiq log format.  The default format is more informative.
