### ISSUE TITLE
Add sidekiq.jobs.enqueued metrics by worker

### ISSUE THREAD

**Issue by nakulpathak3** [mperham/sidekiq#4375]
Ruby version: 2.4.7
Sidekiq / Pro / Enterprise version(s): 5.2.5 / 4.0.4 / 1.8.1

```ruby
Sidekiq.configure_server do |config|
  Sidekiq::Pro.dogstatsd = ->{ CustomMetric.dogstatsd } # we have a dogstatsd instance we use for all metrics so we pass it to Sidekiq too
  config.server_middleware do |chain|
    require 'sidekiq/middleware/server/statsd'
    chain.add Sidekiq::Middleware::Server::Statsd
  end

  logging_frequency_seconds = 30
  config.retain_history(logging_frequency_seconds)
end
```

Having a metric that gives enqueued by worker level metrics is valuable because:

1) As a dev, I don't care about the queue's latency as much as I care about my worker's. 
2) As a Sidekiq system level owner, I want to find out which worker enqueued 5 million jobs yesterday which is causing latency issues for my entire queue and stop the bleeding. 

What do you think? I see two approaches:
 * Add a new client middleware level metric called `scribd.jobs.enqueued` with tag `worker: worker_name` 
* Adding the same tag^ to the 30s global metric `sidekiq.enqueued.<queue_name>`

Are you using an old version? Yes
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

**Comment by mperham** [comment]
Sidekiq Pro emits the `jobs.count` metric with a tag of `worker:<class_name>` for every job performed. I realize it's not quite the same as `enqueued` but you can add your own client middleware which emits `jobs.enqueued`.
