### ISSUE TITLE
Cannot find per-worker DataDog metrics for Batch Callbacks

### ISSUE THREAD

**Issue by vrinek** [mperham/sidekiq#4376]
Ruby version: **2.4.7**
Sidekiq / Pro / Enterprise version(s): **5.2.5 / 4.0.4 / 1.8.1**

Please include your initializer and any error message with the full backtrace.

(abbreviated initializer to relevant parts, no errors)
```ruby
Sidekiq.configure_server do |config|
  # [...]
  Sidekiq::Pro.dogstatsd = -> { CustomMetric.instance.dogstatsd }
  # [...]
end
```

```ruby
require 'datadog/statsd'

class CustomMetric
  include Singleton
  # [...]
  attr_reader :dogstatsd

  def initialize
    # [...]
    @dogstatsd = Datadog::Statsd.new(DOGSTATSD_HOST, DOGSTATSD_PORT, opts)
  end

  # [...]
end

```

Are you using an old version? **just a little bit**
Have you checked the changelogs to see if your issue has been fixed in a later version? **yep, I could not find any relevant fix there**

---

We are using DataDog to gather metrics on Sidekiq jobs. Recently we started making use of [Batches](https://github.com/mperham/sidekiq/wiki/Batches) and noticed that the collected metrics do not break down the batch callbacks by worker. Instead they seem to be collected all together in a `scribd.jobs.count{worker:sidekiq::batch::callback}` metric with no more tags for further breakdown into `success`/`complete`/`death` or per the worker that initiated the batch.

Are the callback metrics collected somehow else per worker?

**Comment by mperham** [comment]
This is as designed. Callbacks are implemented with a single callback worker class that calls your code.

**Comment by vrinek** [comment]
Looking into the code for Sidekiq Pro, I see that there are indeed metrics gathered at the callback level as `batches.#{event}` (with `event` being `success`/`complete`/`death`). As far as I see, it would be trivial to:

1. Add a `klass_name` dimension to these metrics (it is already available as a local variable in the `execute_callback` method)
2. Potentially also add a `method` dimension (not immediately necessary in my case but I can see how it can become useful when one does not use the default `on_success`/`on_complete`/`on_death` methods)
2. Also provide the metrics where each dimension (event/klass/method) is a tag with `batches.count` as the metric name in order to keep it symmetrical with the `jobs.count` metrics (this would be immensely useful for DataDog users)

What do you think?

I would offer an MR but Sidekiq Pro is not open source.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Commercial-collaboration
