### ISSUE TITLE
Migrating from one redis server to another

### ISSUE THREAD

**Issue by kernow** [mperham/sidekiq#4381]
Ruby version: Sidekiq

We have a need to periodically migrate to a new server, for instance we might need to upgrade to a new version of ubuntu on a new server, or upgrade the version of redis being used etc.

In this situation we would want to be able to migrate our queue to the new server and would like to know if this will work or if it's a crazy idea. I've been considering using the redis MIGRATE command https://redis.io/commands/migrate to copy jobs from one server to another. The process would go something like:

1. Create new redis server
1. Set workers and rails app to only use the new server
1. At this point there should be no new jobs being created on the old server
1. Use redis MIGRATE (or a custom script) to copy all of the jobs from the old server to the new one

If this works how I hope it will mean that anything that has not been run yet or any scheduled jobs will still get run once they are copied to the new server. We could also copy over the dead jobs if we want to. We would also be able to copy over the statistics entries if we wanted to so we don't lose the historic meta data.

Is this approach sensible or are there better ways to achieve the same thing?

My second choice approach is to have some "legacy" workers that continue to pull jobs from the old server until there are no active jobs left. The downsides to this approach is that we would need to keep the old server running for days until all the jobs have been processed, dead jobs will be lost so we can't re-run any jobs once code fixes have been deployed, stats don't get migrated.

**Comment by mperham** [comment]
No, that's not a good way.

To migrate, you set up a new replica of the old primary, let it replicate, shut down workers, shut down primary, promote new replica to new primary, start up workers.

https://redis.io/topics/replication

**Comment by kernow** [comment]
Thanks @mperham I will look into replication.

**Comment by saipraveen-a** [comment]
> No, that's not a good way.
> 
> To migrate, you set up a new replica of the old primary, let it replicate, shut down workers, shut down primary, promote new replica to new primary, start up workers.
> 
> https://redis.io/topics/replication

@mperham Don't we need to ensure the replication is complete before shutting down the workers and promoting the new replica to primary and starting the workers again? We might otherwise be left with unprocessed jobs in the old Redis server?

**Comment by mperham** [comment]
Yes, there could be downtime. Moving your primary Redis datastore can be just as tricky as moving your primary Postgres datastore. All clients must pause or disconnect. There are aggressive tricks you can use with HAProxy but by far the easiest is to just accept a few seconds of downtime.

**Comment by mperham** [comment]
https://serverfault.com/questions/431997/haproxy-pause-queue-all-traffic-without-losing-requests For instance

**Comment by psahni** [comment]
@mperham 
We are migrating elastic cache (redis) from AWS to alicloud, can we use this strategy in our case.

We were thinking to migrating it to new instance, and quiet the old redis instance, new jobs will go to new instance

Thanks for your vaulable inputs.
