### ISSUE TITLE
WEBUI for all failures

### ISSUE THREAD

**Issue by Rubioli** [mperham/sidekiq#4382]
First of all great Gem 🥇 

I know I can see my failures on the retry tab when it's trying to retry, but I was wondering if there is any way, we can see the failures, with the error messages after the retry as well?

Thanks in advance!

**Comment by mperham** [comment]
You want to see jobs which failed in the past? That data takes Redis memory which is precious; Sidekiq frees job data once it is successful.

**Comment by Rubioli** [comment]
Thanks a lot @mperham for your reply. appreciate it a lot :)

I saw this gem https://github.com/mhfs/sidekiq-failures (I know its not an official gem).

The reason we need to see the failures is mainly for debugging a few of the issues we have, which mostly are nomethod errors.

Is there any way we can save them someplace to do the debugging?

Thanks in advance

**Comment by mperham** [comment]
Well, any jobs that retry without success will go to the Dead tab. Review
this page:

https://github.com/mperham/sidekiq/wiki/Error-Handling

**Comment by ThomasKoppensteiner** [comment]
@Rubioli maybe the https://github.com/ThomasKoppensteiner/sidekiq-undertaker plugin can help you. It's a fork from sidekiq-cleaner.
