### ISSUE TITLE
--timeout cli option not being honored

### ISSUE THREAD

**Issue by bcantin** [mperham/sidekiq#4384]
Ruby version: 

`2.5.5`

Sidekiq / Pro / Enterprise version(s): 
```
sidekiq (6.0.3)
sidekiq-cron (1.1.0)
sidekiq-ent (2.0.1)
sidekiq-pro (5.0.1)
```
Please include your initializer and any error message with the full backtrace.

`bundle exec sidekiq -C ./config/sidekiq.yml -e ${RAILS_ENV:-development} --timeout 3`

We are trying to prove that
- sidekiq will honor the timeout sent from the command line
- that sidekiq will put any running jobs back on the stack

We are using super_fetch to ensure that any jobs that are running are put back on the stack. 
We are using dockers to launch our sidekiq job locally.  Once docker is running and processing jobs, we have a 5 minute job that we launch.  We then issue a docker stop command with a timeout of 30 seconds. 

We expected to see the running job to get terminated after our --timeout of 3 seconds. We are seeing that the LongJob (below) continues to run until the docker container shuts down instead of the 3 seconds that we expected.

We can confirm that super_fetch is putting the LongJob back on the stack as expected. 

The job

```Ruby
class LongJob
  include Sidekiq::Worker

  def perform
    future_time = Time.now + 5.minutes
    until Time.now > future_time
      puts (future_time - Time.now).to_i
      sleep(1.0)
    end
  end

end
```

**Comment by mperham** [comment]
Does -t 3 work?

**Comment by bcantin** [comment]
We tried both -t on the command line as well as putting a 

`:timeout: 3` 

in the sidekiq.yml

**Comment by mperham** [comment]
-v will print out the options so you can see if it’s in the global option hash. I’m at Rubyconf right now so I can’t get to this until Friday but keep the issue updated if you learn anything new.

**Comment by bcantin** [comment]
Ok thanks.  We are seeing it being set with the -v option, but we are not seeing any evidence of it being used.  Enjoy Rubyconf

**Comment by mperham** [comment]
Dumb question but how are you sending TERM? The timeout doesn’t start until Sidekiq receives that signal.

**Comment by mperham** [comment]
I don’t know what that does. Does it send TERM? Are you seeing a log statement about shutting down?

**Comment by bcantin** [comment]
Here is a link to the docker documentation for a stop command

https://docs.docker.com/engine/reference/commandline/stop/

So the running process inside should get the SIGTERM signal. 

I will try to see if I can override it to TERM.

**Comment by Gedrovits** [comment]
I have guess that it's either unexpected signal or it's not directly propagated to started process.

For override we can try using this: https://docs.docker.com/v17.09/engine/reference/builder/#stopsignal

**Comment by bcantin** [comment]
OK   Thank you for your indulgence.  

When I send 

`kill -TERM #{@pid}`

sidekiq does log the signal and it respects the --timeout properly.

This seems to be an issue with docker sending the signal, not sidekiq processing it.  I will close this issue.
