### ISSUE TITLE
Some jobs seem to be treated as duplicate despite empty queue

### ISSUE THREAD

**Issue by EGibbs87** [mperham/sidekiq#4385]
Ruby version: 2.4.5
Sidekiq / Pro / Enterprise version(s): 5.2.7

Please include your initializer and any error message with the full backtrace.

Are you using an old version? Y
Have you checked the changelogs to see if your issue has been fixed in a later version? Y

I have a job that I want to run every hour on about 60 items, but a select number of those items (typically around 10 or 15) seem to be treated as duplicates, and thus won't send the job for processing.

```
class MyWorker
  include Sidekiq::Worker
  sidekiq_options queue: :low
  sidekiq_options unique: :until_executed

  def perform(id)
    item = Item.find(id)
    item.do_method
  end
end

```
I first verified, both on the GUI dashboard and in the console, that the queue is empty and there are no busy or enqueued processes:

```
Sidekiq::Workers.new.size
> 0
Sidekiq::Queue.all.map(&:size)
> [0, 0]
Sidekiq::ProcessSet.new.map { |ps| ps['busy'] }
> [0]
```
When I manually run something like: `MyWorker.perform_async(11497)`, I get the output `nil`. However, when I run `MyWorker.perform_async(11496)`, `MyWorker.perform_async("11497")`, or `MyWorker.set(:queue => :high).perform_async(11497)`, I get the expected :jid response.

This seems to be reset every day, because when this runs around 1 AM, the problem items are properly processed, but that will be the only time of the day.

I do run processes a few times throughout the day to clean up Redis and Sidekiq, but I don't think those are related, as I run these scripts 4 times per day, and would thus expect the problem items to process 4 times per day rather than the current one.

**Comment by mperham** [comment]
I don’t support sidekiq-unique-jobs.
