### ISSUE TITLE
Request: add note about removed CLI option --index

### ISSUE THREAD

**Issue by latortuga** [mperham/sidekiq#4386]
[This commit](https://github.com/mperham/sidekiq/commit/5987a8c352a220a94e1850c79186d82c35050d85#diff-411201f0104d91346964914342a07cefL322-L327) removes the `--index` option from the CLI without deprecation. This unfortunately broke an upgrade deployment for us due to having it sitting around in a config file. I realize it was "unused" as mentioned in the comment, but removing it actually prevents start up because the parser fails.

I would like a note added to the changelog and upgrade notes about this so others that run into this on upgrade can find it easily. I hope I'm not being too much of a jerk to request a deprecation warning next time :smile:

**Comment by mperham** [comment]
Want to send a PR? Index hasn’t been relevant for 3+ years or so now so I didn’t think it would affect enough people to warrant a note.

**Comment by thebravoman** [comment]
It affected us now. An upgrade failed because of the removal of the --index. Would have been great to have it in the release note
