### ISSUE TITLE
Undocumented change in API return value

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#4387]
The commit to avoid json cloning (https://github.com/mperham/sidekiq/commit/60361b03a31e15f6055d0c928b6c9c9320c8cc0f) has introduced a bug in either a) the API return value for `Sidekiq::Workers#each` or b) the documentation of changes between version 6.0.1 and 6.0.2. 

In 6.0.1:
```ruby
process_id, thread_id, work = Sidekiq::Workers.new.first
work['payload'].class # returns Hash
```

In 6.0.2:
```ruby
process_id, thread_id, work = Sidekiq::Workers.new.first
work['payload'].class # returns String
```

This is a breaking change for anyone who uses the `Sidekiq::Workers` API. The test suite does not have a test to ensure this value stays the same type so I'm not sure if this change was intentional or an unintended side effect of the optimization in commit 60361b0. I am now handling both cases in my API usage but a decision should be made on the type of the payload key and a test added to ensure it stays the same. If `String` is chosen, the documentation should be updated to mention this breaking change.

**Comment by mperham** [comment]
You're right, we need a breaking test and a fix.

**Comment by jakemack** [comment]
Awesome, thanks for the quick fix
