### ISSUE TITLE
How to report exception manually will also sending the job into dead?

### ISSUE THREAD

**Issue by kernow** [mperham/sidekiq#4388]
Hi,

We have a job that processes incoming emails and needs to match the email up with a user in our system. Sometimes the incoming email can't be matched to a user, largely this is due to spam email but we want to check each one to ensure it is no legitimate. When an email can't be matched to a user we want to report the error to Sentry with the specific error level of `info` and have the job moved to dead to later review.

We are using ActiveJob on top of sidekiq.

Is it possible to catch the error so it can be manually raised to Sentry while also having the job move to dead?

Here is a contrived example:

``` ruby
class OurJob < ApplicationJob

  retry_on MissingMailboxHashError, attempts: 1 do |_, error|
    Raven.capture_message(error, level: "info")
  end

  def perform
    raise MissingMailboxHashError, "Error details..."
  end

end
```

When the `MissingMailboxHashError` is raised it's caught by `retry_on` and only attempted the 1 time but as we are call `retry_on` with a block the error is swallowed and sidekiq thinks the job was successful so deletes it.

If we do this:

``` ruby
class OurJob < ApplicationJob

  retry_on MissingMailboxHashError, attempts: 1

  def perform
    raise MissingMailboxHashError, "Error details..."
  end

end
```

Then the job is sent to dead but the error sent to Sentry does not have the level of `info` as required.

Is there a way we can achieve both behaviours?

Thanks

**Comment by nakulpathak3** [comment]
I'm not very familiar with ApplicationJob but why don't you just do 
```ruby
class OurJob < ApplicationJob

  retry: 0

  def perform
    raise MissingMailboxHashError, "Error details..."
   rescue MissingMailboxHashError => e
     Raven.capture_message(error, level: "info")
     raise e
  end
end
```
The retry 0 will make sure it goes to dead queue on the first shot. The rescue + Raven capture + re-raise will make sure it counts as a failure thus triggering the dead queue.

**Comment by mperham** [comment]
Sidekiq‘s retry subsystem is not that flexible, by design. This sounds like an admin review process that should be built into your app, rather than trying to jury rig something with Sidekiq and its UI.

**Comment by nakulpathak3** [comment]
I agree with Mike but I also have a hacky solution for you 😄 
```ruby
class OurJob < ApplicationJob

  retry: 0

  def perform
    raise MissingMailboxHashError, "Error details..."
   rescue MissingMailboxHashError => e
     Raven.capture_message(error, level: "info")
     raise <some_ignored_exception>
  end
end
```
The retry 0 will make sure it goes to dead queue on the first shot. The rescue + Raven capture + re-raise an exception you ignore will get you a failure without an exception sent to Sentry.

If you're unfamiliar with Raven's ignoring exceptions, look at https://docs.sentry.io/clients/ruby/config/ for `excluded_exceptions`. You could create a custom one. Of course, very hacky and ideally you want a UI or page where you rescue your exception and send it over to.

**Comment by kernow** [comment]
> Sidekiq‘s retry subsystem is not that flexible, by design. This sounds like an admin review process that should be built into your app, rather than trying to jury rig something with Sidekiq and its UI.

I didn't think there was any way to (easily) do this from looking through the docs. I'll let the exception bubble up to Sentry in the normal way and live without the level being set I think.

The reporting is a temporary thing until we are satisfied no legitimate message processing is failing. It doesn't make sense for us to put any resource into building a UI for reviewing that will only be used for a short amount of time. We look at the exception in Sentry and then delve into our database to investigate if the message is SPAM, we don't get that many due to our setup.

@nakulpathak3 I'd already considered doing something along these lines but it's just too far from decent coding practice for my liking. The error being raised isn't in the job itself in practice, our jobs only ever have a couple of lines of code in the `perform` method, they usually call a service object to perform the actual task.

Thanks for the help both of you.
