### ISSUE TITLE
Why on earth would the success and failed jobs tab be just counts?

### ISSUE THREAD

**Issue by gregblass** [mperham/sidekiq#4390]
I have no idea why the creators of this library would not think that it's useful to be able to view failed and completed jobs. I always thought it was a way to get people to buy sidekiq pro (which is fine, despite the fact that $950 is really steep for startups who are pre-revenue). When I learned today that this was not the case, I was very baffled. I've gotta say as well - the existing github issues surrounding this issue are confusing. 

Once your job fails enough times, it's gone forever? ... And you can't see what it was? ... Why would anyone want this to be the default behavior? And why on earth would you make them tabs, that look like other tab links, if they are just counts? That's one of the worst UX patterns I've ever encountered, hands down.

There are just so many times where I've wanted to see what jobs went into this failed state. I can't imagine the negative impact that this has had globally on all rails apps using sidekiq. At least save the data for a week or something.

We had a bunch of jobs end up in the 'forever-lost' failed tab yesterday, and my only option to see what they were this morning was to sort through a ton of rollbar errors to get the id's of the records that failed permanently. This took a good deal of time, when I could have just viewed it in that failed tab.

I just fundamentally think this was a poor decision, and I really would not be surprised if hundreds of other developers agree with me.

I would encourage the sidekiq creators/maintainers to re-think this, but - I know that this post probably won't change anything, because to actually implement it that way must have been very deliberate. Still, it is just so bewildering to me that I had to post this. We ended up adding the sidekiq-status gem, which gave us a way to see failed jobs. But I really believe that this should not be necessary.

In any case - what was the reasoning here???

**Comment by mperham** [comment]
You can view failed jobs. They are called Retries and Dead jobs.

**Comment by gregblass** [comment]
So this idea of an un-viewable failed job tab does not exist? I'm just totally misunderstanding this? You can always view failed jobs in the retries or dead tabs?

**Comment by mperham** [comment]
Yes unless you’ve disabled retries or job death. See the Error Handling wiki page.

**Comment by gregblass** [comment]
Thank you for the response @mperham - I apologize for the misunderstanding here!
