### ISSUE TITLE
processes no longer exist but remain in sidekiq portal

### ISSUE THREAD

**Issue by jason-yardley** [mperham/sidekiq#4392]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
pro
Please include your initializer and any error message with the full backtrace.

Are you using an old version?
sidekiq 5.2.7 redis 5.0.5
Have you checked the changelogs to see if your issue has been fixed in a later version?
yes cant see a fix
https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

I am hoping my issue has a quick fix. 
It seems that during a redis replication during an outage, then a restore has left some processes in the sidekiq console which dont actually exist anymore. i can see the new processes processing jobs. just need to know how to remove the old processes. i ran a cleanup script (checks worker heartbeat) but it returned 0 processes to be deleted

**Comment by mperham** [comment]
Any lingering worker data can be cleaned up with the two scripts at 4.1.2 and 4.1.3 here:

https://github.com/mperham/sidekiq/blob/master/Changes.md#413

If you run those scripts and the data doesn't disappear after a few minutes, please let me know.

**Comment by jason-yardley** [comment]
Thank you, running the script in 4.1.3 worked! this issue can be closed out. thank you for fast response time i struggled to find any other help online
