### ISSUE TITLE
Sharding issue

### ISSUE THREAD

**Issue by camol** [mperham/sidekiq#4393]
Ruby version: 2.4.5
Sidekiq / Pro / Enterprise version(s): 5.2.7 / 4.0.5 / 1.8.1

Initializer:
```
require 'sidekiq'

if ENV['SIDEKIQ_REDIS_HOST']
  redis_server = {
    host: ENV.fetch('SIDEKIQ_REDIS_HOST'),
    port: ENV.fetch('SIDEKIQ_REDIS_PORT'),
    db: ENV.fetch('SIDEKIQ_REDIS_DB')
  }
  if !(password = ENV.fetch('SIDEKIQ_REDIS_PASSWORD', '')).blank?
    redis_server[:password] = password
  end

  Sidekiq.configure_server do |config|
    config.super_fetch!
    config.reliable_scheduler!
    config.failures_default_mode = :all

    config.redis = redis_server
    config.periodic do |mgr|
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = redis_server
  end
end

Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq.default_worker_options["retry"] = 3

Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  File.open("./config/crypto/secret.#{Rails.env}.#{version}.key").read
end
```

I want to be able to schedule a job for a different service (which also uses Sidekiq) in my infrastructure. When I tested this piece of code in Rails console:

```
redis_client = Redis.new(different_service_redis_config)

sidekiq_client = ::Sidekiq::Client.new(
        ConnectionPool.new { redis_client }
      )

sidekiq_client.push(
        "class" => "DifferentServiceWorkerClassName",
        "queue" => "some_queue",
        "args" => my_args
      )
```

It works and the "different" service receives the job and starts processing it. However, if I put the same code in a sidekiq background job of the "original" Rails application, the job instead of being pushed to different service it is being pushed to the "original" service to the defined "queue" and of course stays there because that service does not handle such queue.

**Comment by mperham** [comment]
You'll need to show me the code for the "original" job where it is failing.

**Comment by camol** [comment]
The problem is that the job is not failing, simply the scheduled jobs instead of landing in "different" service is being put in the redis of the "original" one is responsible for the initial scheduling.

**Comment by mperham** [comment]
I mean "failing to go to the right Redis".

**Comment by camol** [comment]
Ok sorry for that I will try to be more precise:

Service A:
class WorkerA
def perform
redis_client = Redis.new(service_B_redis_config)

sidekiq_client = ::Sidekiq::Client.new(
        ConnectionPool.new { redis_client }
      )

sidekiq_client.push(
        "class" => "WorkerB",
        "queue" => "queue_B",
        "args" => my_args
      )
end
end


Service B:
class WorkerB
end


After processing of the background job WorkerA I check both Sidekiq Webs and Service A shows enqueued job in queue `queue_B` and Service B shows nothing.

**Comment by mperham** [comment]
That's not working code.  Please give me the exact code or give me an app to reproduce.

**Comment by camol** [comment]
Restarting the worker instance somehow fixed the issue. Thx!
