### ISSUE TITLE
Sidekiq strange discrepancy 

### ISSUE THREAD

**Issue by noma4i** [mperham/sidekiq#4394]
- Sidekiq PRO 4.0.5.

![image](https://user-images.githubusercontent.com/210667/69950444-7485ab80-1547-11ea-8a38-70aae2f4c827.png)

**Comment by noma4i** [comment]
Looks like count been not used from same variable.

**Comment by mperham** [comment]
Expected in a real time system and those are different number, one is total across all queues.

**Comment by noma4i** [comment]
-_- Im dumb

**Comment by noma4i** [comment]
All good. Looks like discrepancy comes from different queues been processes faster then I can spot in UI. Sorry about that.
