### ISSUE TITLE
Ghost job/process that refuses to go away

### ISSUE THREAD

**Issue by riqwan** [mperham/sidekiq#4397]
I have 2 jobs that refuses to go away. Its been enqueued for days now. We have just 1 dyno running with a concurrency of 5. But we see 2 processes. 

I would like to remove them. 

Additionally, whenever jobs get enqueued on one of these processes, I couldn't find any logs of that particular job, but when it lands on the other process. 

I have:
- Stopped the queues
- Flushed redis
- tried to srem processes

In the web UI when I go to the default queue page, it doesn't show any active jobs running. 

<img width="1227" alt="Screen Shot 2019-12-05 at 1 43 55 PM" src="https://user-images.githubusercontent.com/5105988/70216522-ad9b6700-1765-11ea-95b6-c1958fd191e6.png">

<img width="1217" alt="Screen Shot 2019-12-05 at 1 49 46 PM" src="https://user-images.githubusercontent.com/5105988/70216723-239fce00-1766-11ea-8395-34ffb5d3d100.png">

Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): 5.2.7

Please include your initializer and any error message with the full backtrace.
`---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - low
`

`require 'sidekiq/web'

# HTTP auth for sidekiq
Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == [
    Rails.application.secrets.sidekiq_username,
    Rails.application.secrets.sidekiq_password
  ]
end`

Are you using an old version?
5.2.7

Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
The queue page shows jobs that are NOT active.  The busy page shows jobs that are actively being processed.  Shut down your Sidekiq process, worker.1, and those busy jobs should disappear within 1 minute and they should appear in the queue page.
