### ISSUE TITLE
Is it possible to shard Redis in ClientMiddlewares?

### ISSUE THREAD

**Issue by nakulpathak3** [mperham/sidekiq#4398]
Ruby version: 2.4.7
Sidekiq / Pro / Enterprise version(s): 5.2.5 / 4.0.4 / 1.8.1

I found issue https://github.com/mperham/sidekiq/issues/660 which allows usage of `Redis::Distributed` to split the data. However, what I want is the ability to enqueue jobs into a specific Redis Server based on custom if-conditions, not just an auto-distribution. This is because we are trying to migrate from a data center to a cloud solution and would like to be able to rollout our workers gradually.

Since I'm trying to do this in a non-intrusive way for our 100s of enqueuing sites across the code, adding [`Sidekiq::Client.via(REDIS_B)`](https://github.com/mperham/sidekiq/wiki/Sharding#how-to-shard) won't work. I'm hoping a client middleware can work so as to avoid monkey patching `Sidekiq::Worker::ClassMethods`'s `perform_*` methods and `Sidekiq::Worker::Setter`'s `perform_*` methods since that seems like the only way.

I did try 
```ruby
class TestClientMiddleware
    def call(_worker, _job, _queue, redis_pool)
      redis_pool = MY_OTHER_REDIS_CONNECTION_POOL
      yield
    end
  end
```
but unfortunately it seems the `_redis_pool` is already set.

**Comment by mperham** [comment]
It is not possible.  You are correct, the redis destination shard is already selected by the time client middleware is executed.
