### ISSUE TITLE
Need to set web asset_host path

### ISSUE THREAD

**Issue by jsmartt** [mperham/sidekiq#4400]
Ruby version: 2.4.5
Sidekiq version: 5.2.7

I know there is plenty of documentation debugging loading assets in production, but I believe my issue is a bit different. My server is running in an environment with multiple applications under the same domain, namespaced by paths. For example:

```bash
# My Application root:
https://example.com/services/myservice/0

# Route to Sidekiq Web:
https://example.com/services/myservice/0/sidekiq
```

I can fix the asset path issues on my main application by:

```ruby
# config/environments/production.rb

Rails.application.configure do
  config.action_controller.asset_host = 'https://example.com/services/myservice/0'
end
```

However, the sidekiq HTML templates are producing asset source paths like the following, which fail to load:
- `https://example.com/sidekiq/stylesheets/bootstrap.css`
- `https://example.com/sidekiq/javascripts/application.js`

Those URLs are missing the necessary `/services/myservice/0` path prefix. I'm having trouble figuring out how I can set the asset_host on the sidekiq engine's application config, and would appreciate any help I can get.
Thanks!

**Comment by mperham** [comment]
You need Sidekiq Pro to support Web UI sharding.

https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding

**Comment by jsmartt** [comment]
Thanks for the quick reply. I'm not necessarily trying to monitor multiple shards with a single web interface though. I'm just trying to get a single web interface to work with a path prefix. The following monkey patch *almost* makes it work:

```ruby
# Support setting an asset host environment variable to modify the asset path.
# Examples for setting the ASSET_HOST environment variable:
#  - http://localhost:3000
#  - https://example.com/services/myservice/0
require 'sidekiq/web'
module Sidekiq
  module WebHelpers
    def root_path
      "#{ENV['ASSET_HOST']}#{env['SCRIPT_NAME']}/"
    end
  end
end
```

The assets load and the action buttons successfully send their requests, but those actions have an issue on the redirect. The final URL looks correct (and reloading via the browser button works), but chrome gives me a request saying:

```
This page isn't working
localhost sent an invalid response.
ERR_INVALID_REDIRECT
```

Since the assets load and the action does get sent, this may work for me, although I'd prefer being able to set a config option instead of monkey patching.

**Comment by nkrasnogor** [comment]
@jsmartt I am having a similar problem. Did you manage to get a response from mperham? or did you stick with your solution?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Monitoring#proxying-the-web-ui

**Comment by mperham** [comment]
From rack/lint.rb:

```
        ## The environment is required to include these variables
        ## (adopted from {PEP 333}[https://peps.python.org/pep-0333/]), except when they'd be empty, but see
        ## below.

        ## <tt>SCRIPT_NAME</tt>:: The initial portion of the request
        ##                        URL's "path" that corresponds to the
        ##                        application object, so that the
        ##                        application knows its virtual
        ##                        "location". This may be an empty
        ##                        string, if the application corresponds
        ##                        to the "root" of the server.

        ## <tt>PATH_INFO</tt>:: The remainder of the request URL's
        ##                      "path", designating the virtual
        ##                      "location" of the request's target
        ##                      within the application. This may be an
        ##                      empty string, if the request URL targets
        ##                      the application root and does not have a
        ##                      trailing slash. This value may be
        ##                      percent-encoded when originating from
        ##                      a URL.
```

**Comment by mperham** [comment]
@tak1n I can't find docs for X-Script-Name either. Don't recall where that came from or if I tested it, as that wiki content is years old.

**Comment by tak1n** [comment]
> @tak1n I can't find docs for X-Script-Name either. Don't recall where that came from or if I tested it, as that wiki content is years old.

I see, thx for the quick response. We fixed it for now by setting `SCRIPT_NAME` as an environment variable (not through a header). This is also somewhat weird, I can't seem to find any documentation on why `ENV["SCRIPT_NAME"]` should affect rack `env["SCRIPT_NAME"]`. Either it is something I couldn't find in the docu, it is undocumented or some other middleware modifies the rack env in this regard. 🤔 

Just for the sake of completeness, our rails app is accessed through something like `https://app.example.com/api/<service-name>`, with sidekiq being mounted under `/sidekiq` and accessed through `https://app.example.com/api/<service-name>/sidekiq`, therefore we set `ENV["SCRIPT_NAME"]` to `/api/<service-name>`.

**Comment by mperham** [comment]
You must be doing something a little different. If you mount Sidekiq::Web in `config/routes.rb`, everything should Just Work™. If you mount it aside the Rails app using `Rack::URLMap`, it should Just Work™.
