### ISSUE TITLE
[Request] Allow Worker.perform_async to throw error if keyword arguments used

### ISSUE THREAD

**Issue by jai-x** [mperham/sidekiq#4403]
Ruby version: 2.6.5p114
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.0.3

As Sidekiq does not currently support keyword arguments being used in the `perform_async` method of a `Sidekiq::Worker`, using them should throw an error.

I think this would add a small amount of overhead when enqueuing a new worker, but throwing an error early seems preferable than allowing the unsupported kwargs to be serialized and then having the worker throw the error later.

example:
```ruby
class SomeWorker
  include Sidekiq::Worker

  def perform(some:, args:)
    ...
  end
end

SomeWorker.perform_async(some: 'foo', args: 'bar') # <= Should throw ArgumentError
```

**Comment by rgaufman** [comment]
Better still, keyword arguments is one of the best additions to Ruby in recent years and Sidekiq feels outdated not supporting them.
