### ISSUE TITLE
Backtrace in web ui doesn't show

### ISSUE THREAD

**Issue by woto** [mperham/sidekiq#4404]
Ruby on Rails: 6.0.2
Ruby version: 2.5.6
Sidekiq / Pro / Enterprise version(s): Sidekiq (6.0.3)

Please include your initializer and any error message with the full backtrace:
https://github.com/woto/sidekiq_backtrace

Here is one commit with all changes I've made since init commit with `rails new sidekiq_backtrace` 
https://github.com/woto/sidekiq_backtrace/commit/b40efadc14013ffc5607ecc4c2d25c1c988fe061

I do `FakeJob.perform_later` in the console. But don't see backtrace in the web admin.

![image](https://user-images.githubusercontent.com/146704/71086281-894e7a00-21aa-11ea-9286-2e9ab26e5321.png)

It seems it is a bug or I'm doing something wrong?
Best regards!

**Comment by mperham** [comment]
The backtrace is only shown in the job details.  Click the "1 hour ago" link.

**Comment by woto** [comment]
@mperham nope, it doesn't work too

![image](https://user-images.githubusercontent.com/146704/71104975-cc6e1480-21cd-11ea-9cc8-d729dedf3202.png)

I made some investigation and found that `msg["backtrace"]` by some reason is `nil`
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/job_retry.rb#L159
after setting its value to true Error Backtrace became shown.

**Comment by mperham** [comment]
You are using ActiveJob.  It will catch errors and skip Sidekiq's error handling, including saving backtraces.  Try using a native Sidekiq::Worker.

**Comment by woto** [comment]
@mperham I definitely sure that it will work in pure Sidekiq. Cause I've already played with it in my pet project and liked this feature.
 
But in my current work, it seems it will not be too easy to replace AJ. I thought that it should work https://github.com/mperham/sidekiq/blob/master/Changes.md#60

**Comment by mperham** [comment]
Thank you, this did turn out to be a bug.  I added a failing test and fixed the issue.  You can use master for now, I will release 6.0.4 tomorrow.

**Comment by woto** [comment]
Great! Thank you so much!

**Comment by kreintjes** [comment]
Note: this change seems to have broken the ability to set sidekiq options using `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper.sidekiq_options` (for example in an initializer to disable retries). For anyone who was using this: setting sidekiq_options in the job itself (for example`sidekiq_options retry: false` in ApplicationJob) fixes the problem (in Rails 6+).
