### ISSUE TITLE
Job Flow Diagram

### ISSUE THREAD

**Issue by Phillita** [mperham/sidekiq#4405]
Ruby version: 2.4.4
Sidekiq (5.2.7) / Pro (4.0.5)

Hello Sidekiq Team, 

This is not a bug / Error issue. 

I was actually hoping to find out if you have any sort of flow diagram showing how a job progresses through Sidekiq. Including the chain of events from client -> server -> success/death.

I'm actually hooking into the death handler, in my current process, at the end of a jobs life and am curious how it gets called within the flow (Is it before the server middleware finishes or during etc). I'd also like to see where these pieces fit when using custom middleware within the chain as well.

Thanks!

**Comment by mperham** [comment]
Unfortunately I don't know of any diagram.  If anyone does create such a thing it would be received with much gratitude.

**Comment by Phillita** [comment]
No worries! It was mostly to help me figure out a processing issue I'm having. I would make one up myself but due to my current lack of understanding, I don't think I'm the right person.
