### ISSUE TITLE
Sidekiq systemd logging problem

### ISSUE THREAD

**Issue by galievruslan** [mperham/sidekiq#4408]
Ruby version: 2.6.5
Rails version: 6.0.2
Sidekiq version: 6.0.3

Sidekiq initializer:
```
# initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.redis = { url: Setting.sidekiq_host }
  config.logger.level = Logger::WARN
end
Sidekiq.configure_client do |config|
  config.redis = { url: Setting.sidekiq_host }
  config.logger.level = Logger::WARN
end
Sidekiq.default_worker_options = { 'backtrace' => true }
```
On the production server, I run Sidekiq through systemd. Guided by the instruction [https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service)

My service(/home/deploy/.config/systemd/user/sidekiq-production.service):

```
[Unit]
Description=sidekiq for track-server (production)
After=syslog.target network.target

[Service]
Type=simple
#Environment=RAILS_ENV=production
Environment=MALLOC_ARENA_MAX=2
WorkingDirectory=/var/www/track-server/current
#ExecStart=/usr/local/bin/bundler exec sidekiq -e production
#ExecStart=/home/deploy/.rvm/bin/rvm 2.6.5 do bundle exec sidekiq -e production >> /var/www/track-server/shared/log/sidekiq.log
#ExecStart=/home/deploy/.rvm/bin/rvm 2.6.5 do bundle exec sidekiq -e production 2>&1
#ExecStart=/home/deploy/.rvm/bin/rvm 2.6.5 do bundle exec sidekiq -e production | tee /var/www/track-server/shared/log/sidekiq.log
ExecStart=/bin/bash -lc '/home/deploy/.rvm/bin/rvm 2.6.5 do bundle exec sidekiq -e production'
ExecReload=/bin/kill -TSTP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID

#User=deploy
#Group=deploy
#UMask=0002

RestartSec=1
Restart=on-failure

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=sidekiq

[Install]
WantedBy=default.target
```
After each change to the service startup file, I run 
`systemctl --user daemon-reload`

The service starts without problems and sidekiq works. But it does not write anything to the log (/var/log/syslog or to another file). I have already tried various startup options (ExecStart), nothing helps.

Tell me, what am I doing wrong?

**Comment by mperham** [comment]
Get rid of bash when starting Sidekiq. Don't use RVM.

ExecStart=/usr/local/bin/bundler exec sidekiq -e production
