### ISSUE TITLE
[Request] Add config option to force light/dark mode

### ISSUE THREAD

**Issue by CHTJonas** [mperham/sidekiq#4409]
It would be nice to be able to override the CSS `@media` queries for light/dark mode so that, regardless of the user's theme choice in their OS, a specified theme is always served. This could take the form of a config option in `config/sidekiq.yml` for example:

```YAML
---
:theme: light
```

This addresses some of the tail comments from #4231.

**Comment by mperham** [comment]
I disagree with the premise, the user should have control over the UI and theme.

**Comment by heldopslippers** [comment]
Sorry to get into this again. 
There are also teams that really don't like the dark Sidekiq theme, but still are using the "dark" theme on their computers. 
Why would it be so bad to make it possible to be able to force a default if somebody once to.

**Comment by mperham** [comment]
I'd love to have CSS PRs which make the dark theme better. I'm not interested in a switch which forces light/dark on all users.
