### ISSUE TITLE
Access Job arguments in sidekiq_retries_exhausted call back

### ISSUE THREAD

**Issue by AsaKiran12** [mperham/sidekiq#4411]
I want to access the arguments to a job in the sidekiq_retries_exhausted call back is it possible ?

```
class ConcernedJob
  include Sidekiq::Worker

  sidekiq_retries_exhausted do |msg, ex|
    #Access arg1 and arg2 here
  end
  def perform(arg1, arg2)
       #jobs work
  end
end
```

Ruby version: 2.3.7
Sidekiq / Pro / Enterprise version(s): Pro

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
msg[“args”]

**Comment by AsaKiran12** [comment]
Can we access the job id too in the callback ?

**Comment by mperham** [comment]
msg['args'], msg['jid'], msg['bid']

See the pattern?
