### ISSUE TITLE
How to use Sidekiq with Active Record Slave?

### ISSUE THREAD

**Issue by goodgravy** [mperham/sidekiq#4413]
Ruby version: 2.6.3p62
Sidekiq / Pro / Enterprise version(s): Pro

Are you using an old version? No: 6.0.4

[Active Record Slave](https://github.com/rocketjob/active_record_slave) uses thread-local variables to remember whether it should send queries to the master DB or a slave by default. Their recommendation is to set this default in an initializer – so far so good.

However, due to Sidekiq's multi-threaded setup those defaults aren't shared with the actual worker threads consuming our Sidekiq jobs.

**Question:** is there a way to set per-thread configuration in Sidekiq, like an initialization block or something similar?

Note that I'm not looking to synchronise the thread-local Active Record Slave state between threads – merely set a default upfront.

**Comment by goodgravy** [comment]
All of our Sidekiq worker classes inherit from a single base class, so we **could** override the constructor there with something like:

```
  def initialize
    ActiveRecordSlave.read_from_master!
    super
  end
```

… but I'd love to know if there's a more idiomatic approach!

**Comment by mperham** [comment]
Maybe this:

```ruby
Sidekiq.configure_server do
  ActiveRecordSlave.read_from_master!
end
```
