### ISSUE TITLE
Adding job to existing batch

### ISSUE THREAD

**Issue by mrchucho** [mperham/sidekiq#4415]
Ruby version: 2.3.1
Sidekiq / Pro / Enterprise version(s): sidekiq-5.1.3, sidekiq-pro-4.0.3

According to the [Batches Wiki](https://github.com/mperham/sidekiq/wiki/Batches#notes):

>You can dynamically add jobs to a Batch but only by another job within that batch

Does that mean that -- **even if you have the batch ID** -- you cannot add jobs any other way? E.g. in a separate, non-job process could you not do the following?

```ruby
    # not in a worker class
    Sidekiq::Batch.new(current_batch_id).tap do |batch|
      batch.jobs do
          Worker.perform_async(batch_id: batch.bid)
        end
      end
    end
```

The wiki is pretty explicit, but I wasn't sure how strict this requirement was (or if perhaps I was misinterpreting it) given that you're doing the "same thing" just not in a job/worker.

**Comment by mperham** [comment]
Technically you can do that, the API will not stop you, but **that is one big race condition**.  Sidekiq is trying to finish your batch jobs as fast as possible and you are adding more.  What happens when you add a job after Sidekiq has finished the batch? BOOM. Undefined behavior but it probably won't be good.

**Comment by mrchucho** [comment]
Thank you for the quick response.

In our case, we have two types of long-running jobs. We may start one then add another shortly thereafter. As such we might be able to avoid a race condition, but I'll definitely look into an alternative (safer) approach.

**Comment by mperham** [comment]
One thing you can do is schedule a job within the batch.  That will guarantee the batch won't close until that scheduled job runs, e.g. 10 minutes from now.

**Comment by mrchucho** [comment]
> One thing you can do is schedule a job within the batch. That will guarantee the batch won't close until that scheduled job runs, e.g. 10 minutes from now.

Interesting suggestion, thank you!
