### ISSUE TITLE
Empty queues not removed from queues set

### ISSUE THREAD

**Issue by spaceform** [mperham/sidekiq#4417]
Ruby version: 2.5.7
Sidekiq / Pro / Enterprise version(s): Sidekiq Open Source 5.2.6

Hi. I am using the ideas in https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-ensure-a-job-processes-on-a-given-machine to create a queue per machine. Machines are replaced frequently as part of our deployment and scaling processes and the unique machine queues are empty when that happens.

These empty queues appear to remain in the queues set forever with size 0. They show both in redis in the queues set and in `Sidekiq::Queue.all` and `Sidekiq::Stats.new.queues` output. The queue set therefore continues to grow.

Is this okay or could this potentially cause a future issue with sidekiq, such as a performance issue?

Are there any suggestions for working with this situation or alternative approaches to avoid it?

Perhaps I should be regularly clearing the empty queues to remove them from the set. There may be some complexities with this approach as I wouldn't want to have bad timing around clearing a queue just before a job is added.

**Comment by mperham** [comment]
I believe if you delete them from the Web UI, they shouldn't reappear so you can do this manually?

To automate this, I would write a Lua script which iterates through `queues` and SREM any entry whose corresponding "queue:#{name}" list does not exist. You need to use Lua to prevent the race condition of a job being added between the check and removal.

**Comment by spaceform** [comment]
Thanks for the feedback and suggestions. I think I'll implement the Lua script idea as it seems like a straightforward approach to automate and the script itself should have little overhead.

**Comment by xdmx** [comment]
@spaceform did you end up writing such Lua script to auto clean empty queues? Would you be able to share that? It'd be much appreciated.

I'm running a similar issue (creating dynamic queues that only run sporadically) and I need to clear the empty ones to avoid crashing the Redis instance.

**Comment by spaceform** [comment]
@xdmx - I went with a different approach. The sidekiq healthcheck job itself first calls `Sidekiq::Queue.new(queue_name).clear` before doing the actual health check logic. This seems to fully delete the queue. This is okay for me as I only ever want these queues to have one job, which is the job being executed, and I use a systemd oneshot service/timer to regularly add new healthcheck jobs.

I use the free version of sidekiq and so I don't know if the above is okay for the paid versions of sidekiq which have the Enhanced Reliability feature.

The only time queues are left over is if the healthcheck job or sidekiq server fails. I don't automatically remove such queues (I manually tidy them up). If I wanted to automate removal, I would also have the healthcheck job itself remove unempty queues with jobs older than a certain time.

I'm sure there are better ways of handling all of this, but this approach has been working okay for me.
