### ISSUE TITLE
Rack::File deprecation warning

### ISSUE THREAD

**Issue by DannyBen** [mperham/sidekiq#4423]
Ruby version: 2.6.3
Sidekiq version(s):  6.0.4

### Issue

Warning displayed:
`Rack::File is deprecated, please use Rack::Files instead.`

### Reproduction code

```ruby
require 'sidekiq/web'
puts "ok"
```

### Output

```
$ ruby test.rb
Rack::File is deprecated, please use Rack::Files instead.
ok
```

### Additional info

- The warning was introduced in Rack 2.1.0 - ref: https://github.com/rack/rack/blob/2.1.0/lib/rack/file.rb

**Comment by mperham** [comment]
https://github.com/rack/rack/commit/f80e65d5dde251ee446e4c0bd038f8bc4ec30314
