### ISSUE TITLE
REDIS_PROVIDER not replacing REDISCLOUD_URL

### ISSUE THREAD

**Issue by Subomi** [mperham/sidekiq#4426]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0.3

`config/initializer/sidekiq.rb`
```
Sidekiq.configure_server do |config|
	config.redis = { url: ENV['REDIS_PROVIDER']}
end

Sidekiq.configure_client do |config|
	config.redis = { url: ENV['REDIS_PROVIDER']}
end
```
 
`.env`
```
REDISURL=redis://:password@localhost:6379/
REDIS_PROVIDER=REDISURL
```

However, what I find is, this fails with the following line
`2020-01-13T00:56:26.925Z pid=12082 tid=gr8223v62 INFO: Booting Sidekiq 6.0.3 with redis options {:url=>"REDISURL", :id=>"Sidekiq-server-PID-12082"}
`
Then, `invalid uri scheme ''  `

If I move the `config/initializers/sidekiq.rb` to `config/sidekiq.rb` it works.

Please what I'm I doing wrongly ?

**Comment by mperham** [comment]
Get rid of the lines in config/initializer/sidekiq.rb.  You've told Sidekiq where Redis is in your .env.  You don't need any further code.
