### ISSUE TITLE
Are middleware docs incorrect about nesting under `Server`?

### ISSUE THREAD

**Issue by henrik** [mperham/sidekiq#4428]
Hi!

https://github.com/mperham/sidekiq/wiki/Middleware gives `class Sidekiq::Middleware::Server::ErrorLogger` as an example of how to define server middleware, but there doesn't seem to be such a module/class anymore.

Is there a suggested new naming scheme for these?

I see the changelog mentions having renamed `Sidekiq::Middleware::Server::RetryJobs -> Sidekiq::JobRetry` and `Sidekiq::Middleware::Server::Logging -> Sidekiq::JobLogger` but doesn't  clearly state anything about middleware in general.

We're upgrading a project and started getting errors from nesting under `Server`, so just checking if there's an official recommendation. It's easy enough to name it `Sidekiq::Middleware::ServerMyFooBar` or whatever to get around the issue, of course.

**Comment by henrik** [comment]
Seems like `Server` was removed in https://github.com/mperham/sidekiq/commit/4a0470de42c2b2d5942040cd3693310d9fc33729#diff-e57f74c74b749c14d6844dc9a479b950.

**Comment by mperham** [comment]
You can use any naming scheme you want, Sidekiq doesn't care.  The wiki page assumes you understand the basics of defining modules and classes.

You definitely should not be creating modules and classes within `Sidekiq` so the wiki page examples have been edited.

**Comment by henrik** [comment]
Cheers, @mperham! Aware of the technical side but wasn’t sure about any naming conventions.
