### ISSUE TITLE
Potential type errors

### ISSUE THREAD

**Issue by mckaz** [mperham/sidekiq#4429]
These were caught by a novel type inference system built on [RDL](https://github.com/tupl-tufts/rdl/).

1. There is [no variable or method named `e`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L184) in this rescue branch.

2. There [doesn't appear to be a constant](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/logger.rb#L86) called `UNKNOWN` defined in this scope.

3.  [Here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L462) `@parent.delete_by_value(...)` is called. `@parent` may be an instance of the class `SortedSet` (see [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L558) and [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb#L453)). However, the `SortedSet` class has no instance method `delete_by_value`. This may not be an issue if the SortedSet#scan method is only called on instances of JobSet (a subclass of SortedSet which does define `delete_by_value`), but based on the code this may not always be the case and there are no checks to ensure it.

4. [Here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/testing.rb#L260) and [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L237) the `get_sidekiq_options` method is called from inside the `Sidekiq::Worker::ClassMethods` module, but this method is actually defined in `Sidekiq::Worker::Options::ClassMethods`. This may not be an issue depending on how modules are meant to be composed/included.

**Comment by mperham** [comment]
1 and 2 will be fixed.

3. SortedSet is meant to be abstract but it can probably be combined with JobSet.

4. An artifact of recent refactoring but should be harmless. The test suite exercises this code path very heavily.

**Comment by mperham** [comment]
In a different timeline I think 1 could have been a possible serious issue.  In practice I don't think it had any negative affect but it's still great that you caught it.
