### ISSUE TITLE
'NameError: uninitialized constant Rails::VERSION' when running on Sinatra

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [mperham/sidekiq#4432]
Ruby version: jruby-9.2.9.0
Sidekiq / Pro / Enterprise version(s): `5.2.7` / `5.0.0` / `1.8.1`

When upgrading from Sidekiq `4.x` to `5.x` we see the following error.

```
NameError: uninitialized constant Rails::VERSION

…q-5.2.7/lib/sidekiq/middleware/server/active_record.rb:  10:in `initialize'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb: 146:in `make_new'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:  76:in `each'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:  76:in `each'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb: 117:in `map'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb: 117:in `retrieve'
…5.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb: 125:in `invoke'
…ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb: 164:in `block in process'
…ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb: 137:in `block in dispatch'
…ruby/2.5.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb: 109:in `local'
```

In our setup, we use Sinatra, not Rails. We also use `ActiveRecord` and `ActiveSupport`.
The issue is, that the check`if defined?(::Rails) && ::Rails::VERSION::MAJOR >= 5` in `sidekiq/middleware/server/active_record` only checks for `::Rails` and not additionally for `::Rails::VERSION`.

**Comment by mperham** [comment]
Sidekiq 5.x is basically frozen: "serious bugs without a workaround" maintenance only. You can fix this by redefining initialize:

```ruby
class Sidekiq::Middleware::Server::ActiveRecord
  def initialize
  end
end
```

**Comment by ThomasKoppensteiner** [comment]
@mperham Thank you for the suggested workaround.

I created a Pull Request, with a possible (for us working) fix.
Please feel free to merge or decline it.

**Comment by mperham** [comment]
Thank you, I won't release 5.2.8 unless there is a major issue but you are welcome to run off the branch or use the workaround I posted.
