### ISSUE TITLE
Sidekiq 6.0.4 start issue

### ISSUE THREAD

**Issue by chongfai13** [mperham/sidekiq#4436]
Ruby version: 2.5.6
Sidekiq / Pro / Enterprise version(s): 6.0.4

Please include your initializer and any error message with the full backtrace.

bundle exec sidekiq -d -C config/sidekiq.yml
ERROR: Daemonization mode was removed in Sidekiq 6.0, please use a proper process supervisor to start and manage your services
2020-01-20T04:10:39.273Z pid=61132 tid=43d1o INFO: Booting Sidekiq 6.0.4 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq_development", :id=>"Sidekiq-server-PID-61132"}

Are you using an old version? Nope
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

**Comment by Vasfed** [comment]
`-d` option has beed deprecated and removed, see [6.0 upgrade notes](https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md)
