### ISSUE TITLE
Is there a way to perform sidekiq periodic jobs test using Rspec?

### ISSUE THREAD

**Issue by panuza** [mperham/sidekiq#4438]
Ruby version: 2.6.3 
Sidekiq Enterprise version: 2.0.1

I have integrated sidekiq periodic jobs using sidekiq-ent. However, when trying to run the test using RSpec I do not get to see any list of periodic jobs. Is there a way to test specifically with RSpec and view periodic jobs along with the scheduled time.

**Comment by mperham** [comment]
This is the only bit on testing periodic config.

https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#testing
