### ISSUE TITLE
Superfetch reschedules running job

### ISSUE THREAD

**Issue by aliismayilov** [mperham/sidekiq#4441]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0.4 / 5.0.1 / 2.0.1

I'm not sure if the following behavior of sidekiq is expected or it's a bug? We received multiple reports that a unique job was not unique. 

We have a long running worker A, which we enqueue every 3 hours and it usually gets done in less than an hour. On Heroku restart, it doesn't finish in 30 seconds, so the job is expected to be restarted in the new sidekiq process.

The following logs are curious:
```
30 Jan 2020 11:48:54.774195 <190>1 2020-01-30T11:48:54.565934+00:00 host app worker.1 - pid=3 tid=gsjx7v27f class=LongRunningWorker jid=542877c2decfc668bbdd0c25 bid=KKQqDOCGS51Hjw INFO: start
30 Jan 2020 11:48:54.888626 <190>1 2020-01-30T11:48:54.483634+00:00 host app worker.1 - pid=3 tid=gsp1cabmn WARN: Work still in progress [#<struct Sidekiq::Pro::SuperFetch::Retriever::UnitOfWork queue="queue:default", job="{\"retry\":false,\"queue\":\"default\",\"unique_for\":\"3600\",\"class\":\"LongRunningWorker\",\"args\":[],\"jid\":\"542877c2decfc668bbdd0c25\",\"created_at\":1580374800.9343834,\"unique_token\":\"6f64edc67a9db1f7a4b3b2af12847c64ddef1fd4\",\"unlocks_at\":\"1580378490.9343529\",\"bid\":\"KKQqDOCGS51Hjw\",\"enqueued_at\":1580374897.1678405}", local_queue="queue:sq|worker.1:3:978c12eab990|default">]
30 Jan 2020 11:48:54.888211 <190>1 2020-01-30T11:48:54.664341+00:00 host app worker.1 - pid=3 tid=gsp3h4d6v class=LongRunningWorker jid=542877c2decfc668bbdd0c25 bid=KKQqDOCGS51Hjw elapsed=2159.822 INFO: fail
```

Seems like `tid=gsjx7v27f` (thread id?) started to reprocess the `jid=542877c2decfc668bbdd0c25` before `tid=gsp3h4d6v` got shutdown. Is this expected behavior?

**Comment by mperham** [comment]
I can't explain that log output. And as the wiki notes, uniqueness is not guaranteed: there are edge cases which will lead to job duplication.
