### ISSUE TITLE
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):

### ISSUE THREAD

**Issue by belgoros** [mperham/sidekiq#4442]
Ruby version: `2.6.5`
Sidekiq (open-source): `6.0.4`

Gemfile:
```yml
# outside of any group
gem 'sidekiq',                  '~> 6.0'
gem 'sidekiq-scheduler',        '~> 3.0'
```
The initializer file:
```rb
# config/sidekiq.rb

sidekiq_config = { url: ENV['JOB_WORKER_URL'] }
  Sidekiq.configure_server do |config|
    config.redis = sidekiq_config
    config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new

    # Touch a file so we know Sidekiq worker has started.
    # Useful for health checks
    config.on(:startup) do
      FileUtils.touch(Rails.root.join("tmp", "pids", "sidekiq_started"))
    end
    # Delete the touched file so we know Sidekiq worker has stopped.
    # Useful for health checks
    config.on(:shutdown) do
      FileUtils.rm(Rails.root.join("tmp", "pids", "sidekiq_started"))
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = sidekiq_config
  end
```
When uploading an image,it tries to connect to **Redis** and run the job:
```
Service Create (1.2ms)  INSERT INTO "services" ("categories", "country_id", "description", "language_id", "link", "modified_by", "name", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["categories", "{SEASONAL}"], ["country_id", 1], ["description", "ghjklm"], ["language_id", 245], ["link", "dfghjklm"], ["modified_by", "Z28SCAMB"], ["name", "jjjbl"], ["created_at", "2020-01-31 09:59:21.638828"], ["updated_at", "2020-01-31 09:59:21.638828"]]
  ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "photo"], ["record_type", "Service"], ["record_id", 9], ["blob_id", 23], ["created_at", "2020-01-31 09:59:21.641315"]]
  Service Update (0.6ms)  UPDATE "services" SET "updated_at" = $1 WHERE "services"."id" = $2  [["updated_at", "2020-01-31 09:59:21.642387"], ["id", 9]]
   (0.4ms)  COMMIT
   (0.2ms)  BEGIN
  ActiveStorage::Blob Update (0.4ms)  UPDATE "active_storage_blobs" SET "metadata" = $1 WHERE "active_storage_blobs"."id" = $2  [["metadata", "{\"identified\":true}"], ["id", 23]]
   (0.3ms)  COMMIT
Completed 500 Internal Server Error in 125ms (ActiveRecord: 15.7ms)

Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
```
Have no idea why, because I use Sidekiq and Redis only in `staging`and `production, moreover, only via Docker (Redis service is declared in the corresponding `docker-compose.yml` file)
The routes look like that:
```rb
# routes.rb

require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'
...
# other routes come here
```

The `config.ru` file:
```rb
require_relative 'config/environment'

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

run Sidekiq::Web

run Rails.application
```

No idea if it is a good solution, but I fixed as follows:
- add `if` condition to the `routes.rb`, config.rb` files:
```
unless Rails.env.development?
... require of sidekiq, etc.
end
```
- moved `config.active_job.queue_adapter = :sidekiq` from the `application.rb` to `staging.rb` and `production.rb`.
- moved the `sidekiq` related gems to `::staging, :production` group in the `Gemfile`

Any idea about that? Thank you.

**Comment by mperham** [comment]
You need to start Redis.

**Comment by belgoros** [comment]
@mperham yes, I guessed it, but why should I do in `development`?

**Comment by mperham** [comment]
Sounds like you’re trying to not run sidekiq in development mode. Why is running Redis a problem?

**Comment by belgoros** [comment]
> Sounds like you’re trying to not run sidekiq in development mode

Yes, you are right. I do not need to run `sidekiq` in development ni test modes and I was a bit surprised that it tried to connect to Redis, - I have no job to be executed in the time of running the app. Existing schedules are defined as follows:
```yml
:schedule:
  update_shops:
    class: XXXJob
    cron: '0 0 3 * * 1-5 Europe/Paris' #At 03:00AM on every day-of-week Monday through Friday
    description: "This job ....."
  migrate_mystore_info:
    class: XXXJob
    cron: '0 0 22 * * 1-5 Europe/Paris' #At 10:00PM every day-of-week Monday through Friday
    description: "This job ....."
```
So why on Earth Rails is trying to connect to Redis, especially only on the routes that upload a file? If it was conceived like that and I don't see a solution except for the one I posted earlier.

**Comment by mperham** [comment]
You need to show the full backtrace of the error.

**Comment by belgoros** [comment]
OK, here are the logs from the Terminal console:
```
Started POST "/rails/active_storage/direct_uploads" for ::1 at 2020-01-31 16:03:37 +0100
Processing by V1::DirectUploadsController#create as */*
  Parameters: {"blob"=>{"filename"=>"diagram.png", "content_type"=>"image/png", "byte_size"=>384548, "checksum"=>"+3idgvw2l6JtK5r4WhiVfw=="}, "direct_upload"=>{"blob"=>{"filename"=>"diagram.png", "content_type"=>"image/png", "byte_size"=>384548, "checksum"=>"+3idgvw2l6JtK5r4WhiVfw=="}}}
   (0.3ms)  BEGIN
  ActiveStorage::Blob Create (0.6ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["key", "anF8PH5SkS2xVB6weCv7sMub"], ["filename", "diagram.png"], ["content_type", "image/png"], ["byte_size", 384548], ["checksum", "+3idgvw2l6JtK5r4WhiVfw=="], ["created_at", "2020-01-31 15:03:37.312585"]]
   (0.3ms)  COMMIT
  Disk Storage (0.5ms) Generated URL for file at key: anF8PH5SkS2xVB6weCv7sMub (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWRZVzVHT0ZCSU5WTnJVeko0VmtJMmQyVkRkamR6VFhWaUJqb0dSVlE2RVdOdmJuUmxiblJmZEhsd1pVa2lEbWx0WVdkbEwzQnVad1k3QmxRNkUyTnZiblJsYm5SZmJHVnVaM1JvYVFNazNnVTZEV05vWldOcmMzVnRTU0lkS3pOcFpHZDJkekpzTmtwMFN6VnlORmRvYVZabWR6MDlCanNHVkE9PSIsImV4cCI6IjIwMjAtMDEtMzFUMTU6MDg6MzcuMzE1WiIsInB1ciI6ImJsb2JfdG9rZW4ifX0=--9bbaa405937a5154295840e72667ed7394fa9abe)
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.24ms)
Completed 200 OK in 12ms (Views: 6.5ms | ActiveRecord: 1.2ms)


Started PUT "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWRZVzVHT0ZCSU5WTnJVeko0VmtJMmQyVkRkamR6VFhWaUJqb0dSVlE2RVdOdmJuUmxiblJmZEhsd1pVa2lEbWx0WVdkbEwzQnVad1k3QmxRNkUyTnZiblJsYm5SZmJHVnVaM1JvYVFNazNnVTZEV05vWldOcmMzVnRTU0lkS3pOcFpHZDJkekpzTmtwMFN6VnlORmRvYVZabWR6MDlCanNHVkE9PSIsImV4cCI6IjIwMjAtMDEtMzFUMTU6MDg6MzcuMzE1WiIsInB1ciI6ImJsb2JfdG9rZW4ifX0=--9bbaa405937a5154295840e72667ed7394fa9abe" for ::1 at 2020-01-31 16:03:37 +0100
Processing by ActiveStorage::DiskController#update as */*
  Parameters: {"encoded_token"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWRZVzVHT0ZCSU5WTnJVeko0VmtJMmQyVkRkamR6VFhWaUJqb0dSVlE2RVdOdmJuUmxiblJmZEhsd1pVa2lEbWx0WVdkbEwzQnVad1k3QmxRNkUyTnZiblJsYm5SZmJHVnVaM1JvYVFNazNnVTZEV05vWldOcmMzVnRTU0lkS3pOcFpHZDJkekpzTmtwMFN6VnlORmRvYVZabWR6MDlCanNHVkE9PSIsImV4cCI6IjIwMjAtMDEtMzFUMTU6MDg6MzcuMzE1WiIsInB1ciI6ImJsb2JfdG9rZW4ifX0=--9bbaa405937a5154295840e72667ed7394fa9abe"}
  Disk Storage (2.0ms) Uploaded file to key: anF8PH5SkS2xVB6weCv7sMub (checksum: +3idgvw2l6JtK5r4WhiVfw==)
Completed 204 No Content in 3ms (ActiveRecord: 0.0ms)


Started PATCH "/shops/1" for ::1 at 2020-01-31 16:03:41 +0100
Processing by V1::ShopsController#update as JSONAPI
  Parameters: {"data"=>{"id"=>"1", "attributes"=>{"category"=>"DECATHLON", "fax"=>"03-12345678", "identifier"=>1, "leader"=>"DECATHLON", "modified_by"=>"Z28SCAMB", "name"=>"ENGLOS", "opening_date"=>"1976-07-27T00:00:00.000Z", "phone"=>"0320001700", "photo"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--703fb91c1beb519e15274632b0c88edb9c0a303b", "status"=>"open", "updated_at"=>"2020-01-31T14:40:30.965Z"}, "relationships"=>{"country"=>{"data"=>{"type"=>"countries", "id"=>"1"}}}, "type"=>"shops"}, "identifier"=>"1"}
   (0.2ms)  BEGIN
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."username" = $1 LIMIT $2  [["username", "Z28SCAMB"], ["LIMIT", 1]]
  User Update (0.5ms)  UPDATE "users" SET "token" = $1 WHERE "users"."id" = $2  [["token", "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik1BSU4iLCJwaS5hdG0iOiI2In0.eyJzY29wZSI6WyJwcm9maWxlIiwib3BlbmlkIl0sImNsaWVudF9pZCI6ImRlY2FzdG9yZSIsImlzcyI6ImlkcGRlY2F0aGxvbi5wcmVwcm9kLm9yZyIsImp0aSI6Ilk2UjBXNVRydUUiLCJzdWIiOiJaMjhTQ0FNQiIsInVpZCI6IloyOFNDQU1CIiwib3JpZ2luIjoiY29ycG9yYXRlIiwiZXhwIjoxNTgwNDg4NzYxfQ.yaQWi_onEP4FYmUpU-HgqqgdS20gSrM83Joo2A8LOhHmwKSMWr3khl987ZgXX_3c4CWs1f60hh28WilmxzHpCgc14XtKTEKTbuFli9CozS5WmHGBTyns_YUyV9fgkn0_YhAf4bvRBkHRBOija__bnslC5SJt2J50KGekTzSckJ-Ktjoygf54GbillrsVb6sWByWSK7acWN6iINHn1CU1JTq1Q06gy_HZiQG1ZialdaqlhOHTyaFtYXOBHwNWEfndqt8-0sWfR1KjN0ZNDxKyyk4roOm6tqqwUzTqmjfmdTOIIHT287VPJQef4zrqu4UON1Gc1gywPgs42FOKD7U2Hg"], ["id", 4]]
   (1.0ms)  COMMIT
  Shop Load (0.5ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."identifier" = $1 LIMIT $2  [["identifier", 1], ["LIMIT", 1]]
Unpermitted parameters: :opening_date, :country_id
   (0.2ms)  BEGIN
  ActiveStorage::Attachment Load (0.3ms)  SELECT  "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Shop"], ["name", "photo"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.2ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 16], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.2ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 27], ["LIMIT", 1]]
  ActiveStorage::Attachment Destroy (0.4ms)  DELETE FROM "active_storage_attachments" WHERE "active_storage_attachments"."id" = $1  [["id", 8]]
  ActiveStorage::Attachment Create (0.4ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "photo"], ["record_type", "Shop"], ["record_id", 1], ["blob_id", 27], ["created_at", "2020-01-31 15:03:41.503333"]]
   (0.3ms)  ROLLBACK
Completed 500 Internal Server Error in 38ms (ActiveRecord: 4.7ms)
  
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
  
app/controllers/v1/shops_controller.rb:17:in `update'
```
The problem is happening only when trying to attach an image for a Shop:
```
class Shop < ApplicationRecord
...
has_one_attached :photo
end
```

**Comment by mperham** [comment]
Again, I need a **full backtrace** to help. This is not enough:

```
app/controllers/v1/shops_controller.rb:17:in `update'
```

**Comment by belgoros** [comment]
How can I provide more logs if the default one is `debug` ?
The `ShopsController#update` actions enough trivial:
```rb
module V1
  class ShopsController < ApplicationController
    before_action :set_shop, only: %i[show update]
...

def update
      if @shop.update_attributes(permitted_attributes(@shop))
        head :no_content
      else
        respond_with_errors @shop
      end
    end
...

private

def set_shop
  @shop = Shop.find_by!(identifier: params[:identifier])
end

def pundit_params_for(_record)
  ActionController::Parameters.new(shop_params)
end

    def shop_params
      ActiveModelSerializers::Deserialization.jsonapi_parse!(
        params,
        only: %i[category country fax leader modified_by name opening_date phone photo status]
      )
    end
```

**Comment by Prithivi-Raj** [comment]
> Ruby version: `2.6.5` Sidekiq (open-source): `6.0.4`
> 
> Gemfile:
> 
> ```yaml
> # outside of any group
> gem 'sidekiq',                  '~> 6.0'
> gem 'sidekiq-scheduler',        '~> 3.0'
> ```
> 
> The initializer file:
> 
> ```ruby
> # config/sidekiq.rb
> 
> sidekiq_config = { url: ENV['JOB_WORKER_URL'] }
>   Sidekiq.configure_server do |config|
>     config.redis = sidekiq_config
>     config.logger.formatter = Sidekiq::Logger::Formatters::JSON.new
> 
>     # Touch a file so we know Sidekiq worker has started.
>     # Useful for health checks
>     config.on(:startup) do
>       FileUtils.touch(Rails.root.join("tmp", "pids", "sidekiq_started"))
>     end
>     # Delete the touched file so we know Sidekiq worker has stopped.
>     # Useful for health checks
>     config.on(:shutdown) do
>       FileUtils.rm(Rails.root.join("tmp", "pids", "sidekiq_started"))
>     end
>   end
> 
>   Sidekiq.configure_client do |config|
>     config.redis = sidekiq_config
>   end
> ```
> 
> When uploading an image,it tries to connect to **Redis** and run the job:
> 
> ```
> Service Create (1.2ms)  INSERT INTO "services" ("categories", "country_id", "description", "language_id", "link", "modified_by", "name", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["categories", "{SEASONAL}"], ["country_id", 1], ["description", "ghjklm"], ["language_id", 245], ["link", "dfghjklm"], ["modified_by", "Z28SCAMB"], ["name", "jjjbl"], ["created_at", "2020-01-31 09:59:21.638828"], ["updated_at", "2020-01-31 09:59:21.638828"]]
>   ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "photo"], ["record_type", "Service"], ["record_id", 9], ["blob_id", 23], ["created_at", "2020-01-31 09:59:21.641315"]]
>   Service Update (0.6ms)  UPDATE "services" SET "updated_at" = $1 WHERE "services"."id" = $2  [["updated_at", "2020-01-31 09:59:21.642387"], ["id", 9]]
>    (0.4ms)  COMMIT
>    (0.2ms)  BEGIN
>   ActiveStorage::Blob Update (0.4ms)  UPDATE "active_storage_blobs" SET "metadata" = $1 WHERE "active_storage_blobs"."id" = $2  [["metadata", "{\"identified\":true}"], ["id", 23]]
>    (0.3ms)  COMMIT
> Completed 500 Internal Server Error in 125ms (ActiveRecord: 15.7ms)
> 
> Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
> ```
> 
> Have no idea why, because I use Sidekiq and Redis only in `staging`and `production, moreover, only via Docker (Redis service is declared in the corresponding `docker-compose.yml` file) The routes look like that:
> 
> ```ruby
> # routes.rb
> 
> require 'sidekiq/web'
> mount Sidekiq::Web => '/sidekiq'
> ...
> # other routes come here
> ```
> 
> The `config.ru` file:
> 
> ```ruby
> require_relative 'config/environment'
> 
> require 'sidekiq/web'
> require 'sidekiq-scheduler/web'
> 
> run Sidekiq::Web
> 
> run Rails.application
> ```
> 
> No idea if it is a good solution, but I fixed as follows:
> 
>     * add `if` condition to the `routes.rb`, config.rb` files:
> 
> 
> ```
> unless Rails.env.development?
> ... require of sidekiq, etc.
> end
> ```
> 
>     * moved `config.active_job.queue_adapter = :sidekiq` from the `application.rb` to `staging.rb` and `production.rb`.
> 
>     * moved the `sidekiq` related gems to `::staging, :production` group in the `Gemfile`
> 
> 
> Any idea about that? Thank you.

Sam doubt

**Comment by PurohitNikunj** [comment]
> @mperham yes, I guessed it, but why should I do it in `development`?

I had this same issue.I am also thinking that why we need redis in development if we are not using sidekiq.But in my case the error is due to my config/application.rb file, i configured the queue_adapter as sidekiq and then not using sidekiq. So if we are not using sidekiq then in config/application.rb file the queue_adapter should set to "async".
