### ISSUE TITLE
Sidekiq web ui - rails 6

### ISSUE THREAD

**Issue by rusikf** [mperham/sidekiq#4443]
Hi, I am using sidekiq 5.2.7 + upgraded to rails 6

Looks, that after upgrade admin ui failed, I don have body tag in html source
https://imgur.com/a/kFOlEaN
https://imgur.com/a/haWWwkA

Any ideas what cause the problem? On sidekiq 6 there i no such problem, but I can't now update to It because of capistrano-sidekiq gem for rails 6

**Comment by mperham** [comment]
#4440 

Try `gem 'rack', '2.0.8'`
