### ISSUE TITLE
Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by EnziinSystem** [mperham/sidekiq#4444]
Ruby version: 2.7.0
Rails version: 6.0.2.1
Sidekiq / Pro / Enterprise version(s): 6.0.4

I get a message, please update for new version Ruby.

`/bundle/ruby/2.7.0/gems/sidekiq-6.0.4/lib/sidekiq/logger.rb:108: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
`

Thanks.

**Comment by mperham** [comment]
Fixed on master
