### ISSUE TITLE
About Redirect. (mount Sidekiq::Web => '/sidekiq')

### ISSUE THREAD

**Issue by Ich-bin-naoya** [mperham/sidekiq#4445]
Ruby version: 2.5.1
Sidekiq: OSS
Sidekiq version: 6.0.4
Sidekiq is on Rails(version:6.0.0)

problem:
'/sidekiq' was mounted like '/sidekiq/users/sign-in'  after redirect

Code is bellow.
``` ruby 
# routes.rb
  authenticate :user, lambda { |user| user.admin_flg? } do
   mount Sidekiq::Web => '/sidekiq'
  end
```

Any solution?

**Comment by mperham** [comment]
I don't know anything about Devise, it looks like you have it right:

https://github.com/mperham/sidekiq/wiki/Monitoring#devise
