### ISSUE TITLE
Experiencing really strange behavior with processing and retries queues

### ISSUE THREAD

**Issue by apcano1978** [mperham/sidekiq#4446]
Ruby version: 2.3.8
Sidekiq / Pro / Enterprise version(s): 5.1.3

I am experiencing an strange problem since I migrated a production project with sidekiq to an elastic environment (elastic beanstalk on AWS) I don’t know if the issue is related.

The fact is that all sidekiq processes enter the queue, with a concurrency set to 5 processes at once. When more than that amount enter the queu, for instance to process images, 5 first process correctly, and all the rest go to retry queue with exception like unknown name, but later on, they process correctly after some retries, but never remain in the process queue, only first 5 processes keep processing, all the rest keep retrying until they enter processing queue with available “slots”

It is really annoying because after some time they get processed, but it may take hours or even days when it is not the desired behavior at all. 

Anybody experienced something like this? Any help would be really appreciated.

Thanks in advance

**Comment by mperham** [comment]
I don't understand. 🤷🏼‍♂️

**Comment by apcano1978** [comment]
I have located the problem. I don´t know why processes get duplicated, I´m not talking about sidekiq jobs, but sidekiq processes. 

I think it is because I am using an elastic envionment (elastic beanstalk AWS) and I suppose that when a second server raises due to auto scaling a second sidekiq process is created running on the second server. The problem is that when the auto scaling system shuts down the second server, I see the second sidekiq process is not killed, and is in this situation where all sidekiq jobs don´t remail in the queue, something strange happens and everything but a few jobs (concurrency amount) goes to retry queue.

Unfortunately I don´t know how to solve this automatically. I have to enter and manually kill one of the sidekiq processes. Some guidance would be really appreciated.

**Comment by mperham** [comment]
Your scale down process needs to use the TERM signal.  Using KILL will lose jobs and leave those lingering records in the Web UI.
