### ISSUE TITLE
Sidekiq::Client.new.push() override worker's default values

### ISSUE THREAD

**Issue by sayduck-daniel** [mperham/sidekiq#4450]
For this Worker:

```ruby
class MyWorker
  include Sidekiq::Worker

  sidekiq_options retry: 30
  sidekiq_retry_in { 10 }

  #...
end
```

When I initialize it with

```ruby
MyWorker.perform_async('foo') 
```

It will:
- retry 25 times - worker default
- every 10 sec - worker default

When I use:
```ruby
Sidekiq::Client.new.push({
  'class' => `MyWorker`,
  'args' => ['foo']
})
```

It will:
- retry 25 times - sidekiq default
- every 10 sec - worker default

I think this might be due to the fact we cannot set a time function with the push function but in my opinion, the push function should not have default values (fallback on worker's values) if they are not set.

**Comment by mperham** [comment]
It's because you are passing a String, not a Class.  This will work:

```ruby
Sidekiq::Client.new.push({
  'class' => MyWorker,
  'args' => ['foo']
})
```

**Comment by sayduck-daniel** [comment]
My problem is that I don't have the `MyWorker` on the same application.

**Comment by mperham** [comment]
If Sidekiq can't use the defaults because you don't have the worker code loaded, you will need to pass the actual options manually:

```ruby
Sidekiq::Client.new.push({
  'class' => `MyWorker`,
  'args' => ['foo'],
  'retry' => 30,
})
```

**Comment by sayduck-daniel** [comment]
Yes, it makes sense.
