### ISSUE TITLE
Feature idea: backtrace = 'app' that only saves lines from Rails app

### ISSUE THREAD

**Issue by deborasetton** [mperham/sidekiq#4451]
Hi,

Currently, there are 3 possible values for the `backtrace` configuration of workers:

> true, false or an integer number of lines to save ([from docs](https://github.com/mperham/sidekiq/wiki/Advanced-Options#workers)).

For people who use Sidekiq with Rails (like us), I thought it'd be interesting to have a 4th possible value (something like `backtrace: "app"`), that would only save backtrace lines related to the Rails app.

In our experience, when using backtrace with an integer value, most of the time the first lines of the backtrace are related to method calls buried deep inside gems, which don't really help to debug which code that _we_ wrote is causing the error. This idea would both help to reduce the amount of backtrace lines that is saved and would be more useful than the first X lines.

The implementation could be something like:

```ruby
# lib/sidekiq/job_retry.rb

if msg['backtrace'] == true
  msg['error_backtrace'] = exception.backtrace
elsif !msg['backtrace']
  # do nothing
elsif msg['backtrace'] == 'app' && defined?(::Rails)
  # THIS IS THE NEW BRANCH
  msg['error_backtrace'] = exception.backtrace.select { |line| line[::Rails.root.to_s] }
elsif msg['backtrace'].to_i != 0
  msg['error_backtrace'] = exception.backtrace[0...msg['backtrace'].to_i]
end
```

What do you think? I could work on a PR if you'd be open to merging it.

**Comment by mperham** [comment]
I don't recommend saving backtraces; I recomemend using an error service.

Rails has a backtrace cleanser built into it, maybe we should run the backtrace through it before persisting. You are welcome to send a PR. https://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html

**Comment by deborasetton** [comment]
> I don't recommend saving backtraces; I recomemend using an error service.

We do use one, but we skip it for jobs that sometimes fail in high volume.
  
That's cool, I didn't know about BacktraceCleaner! But in this case, I think each person would have a different idea about which gems they'd like to silence. At first, I thought `backtrace` could receive a Proc with the exception, which would be much more flexible, but then I saw that the worker options are serialized and saved to Redis, so that wouldn't work.

Ok then, I'll work on the PR!
