### ISSUE TITLE
NameError: uninitialized constant Sidekiq::Ctl::Sidekiqctl

### ISSUE THREAD

**Issue by zedtux** [mperham/sidekiq#4456]
When running the `sidekiqctl` command from the latest current version of the 5.x series (5.2.7), it fails like that:

```
bundle exec sidekiqctl
sidekiqctl - control Sidekiq from the command line.

Usage: sidekiqctl quiet <pidfile> <kill_timeout>
       sidekiqctl stop <pidfile> <kill_timeout>
       sidekiqctl status <section>

       <pidfile> is path to a pidfile
       <kill_timeout> is number of seconds to wait until Sidekiq exits
bundler: failed to load command: sidekiqctl (/usr/local/bundle/bin/sidekiqctl)
NameError: uninitialized constant Sidekiq::Ctl::Sidekiqctl
  /usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq/ctl.rb:21:in `print_usage'
  /usr/local/bundle/gems/sidekiq-5.2.7/bin/sidekiqctl:11:in `<top (required)>'
  /usr/local/bundle/bin/sidekiqctl:23:in `load'
  /usr/local/bundle/bin/sidekiqctl:23:in `<top (required)>'
```

This is because of [this commit](https://github.com/mperham/sidekiq/commit/4d883194350cf9202ff5c1650730dfa5ee3d2e06) where the code has been refactored in a new class `Ctl` but [the constant access has not been updated](https://github.com/mperham/sidekiq/blob/v5.2.7/lib/sidekiq/ctl.rb#L21).

**Comment by zedtux** [comment]
@mperham you've closed this issue but I don't see any new 5.x version.

When will you release it please?

**Comment by mperham** [comment]
5.2.8 has been published.

**Comment by zedtux** [comment]
Thank you so much !
