### ISSUE TITLE
 Could not obtain a database connection within 5.000 seconds

### ISSUE THREAD

**Issue by sinscary** [mperham/sidekiq#4458]
From the last few weeks, I am seeing this error "Could not obtain a database connection within 5.000 seconds." I have tried the following solutions.

As per Sidekiq [Docs][1] I have reduced the concurrency to 10 and increased MySql DB pool size to 12. But I was still getting this error so I increased the DB pool size to 27. But still, the issue is there. Tried solutions from [this][2] and [this][3] answer. My Sidekiq server machine doesn't have any other process running which can consume AR connections. I am not spinning any threads from outside. Below are the configurations I have
```
Sidekiq version - 3.4.2
Rails version - 4.2.4
Active Record version - 4.2.4
Mysql max_connections - 10000
Database pool size - 27
Sidekiq concurrency - 10
```
Any help with this will be appreciated.

  [1]: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-get-database-connection-within-500-seconds
  [2]: https://stackoverflow.com/a/41259300/4614833
  [3]: https://stackoverflow.com/a/57882611/4614833

**Comment by mperham** [comment]
I don't support Sidekiq 3 anymore, please upgrade.
