### ISSUE TITLE
Should Server middleware re-raise exceptions?

### ISSUE THREAD

**Issue by kaspergrubbe** [mperham/sidekiq#4459]
When reading through the documentation for middleware https://github.com/mperham/sidekiq/wiki/Middleware it's not really clear what to do with exceptions and how to deal with them, I guess it can depend on the use-case. 

I can see that the `Sidekiq::InfluxDB` gem does re-raise exceptions it sees, so that does answer my question: https://github.com/vassilevsky/sidekiq-influxdb/blob/3cd3ef39a21e063a8debe22ebe6c217e1e929429/lib/sidekiq/middleware/server/influxdb.rb#L57

It would be nice if the docs could be a bit clearer about this.

**Comment by mperham** [comment]
Middleware should follow the Golden Rule of Exception Handling: if you can't handle an exception explicitly, you should re-raise it. Swallowing unknown exceptions is always bad.
