### ISSUE TITLE
Usage Question - Active Job

### ISSUE THREAD

**Issue by resistorsoftware** [mperham/sidekiq#4460]
Ruby version: 6
Sidekiq / Pro / Enterprise version(s): regular joe version: 6.0.4

I setup a rake task to run a job MyJob.perform_later

The rake task gets called and the job executes. The second time the rake task gets called the job ends up in the queue and never executes. What? Am I supposed to use a different call signature to ensure every time a job hits the queue it executes? I am puzzled about why the job just sat there? It was all primed to run, but never ran till I manually executed the perform with the job ID.

**Comment by mperham** [comment]
I too am puzzled as to why it is sitting there.

**Comment by resistorsoftware** [comment]
So I left it alone till the next run... set for 11:30 EST and 4:30 UTC and then it worked all by itself (joy oh bliss) but actually fired 30 minutes early. Not that that is Sidekiq issue, but it sure make computing fun! Couple of moving parts, clocks and chaos! How the heck does a scheduler find itself running a full 30 minutes early? 

<img width="488" alt="Order_Summary_of_the_Atomic_Filters_FTP_Upload_-_hunkybill_gmail_com_-_Gmail" src="https://user-images.githubusercontent.com/123307/74271467-f1b56580-4cda-11ea-88d5-6a934f1fe0b7.png">


<img width="1211" alt="atomic-filter_·_Scheduler___Heroku" src="https://user-images.githubusercontent.com/123307/74271516-05f96280-4cdb-11ea-9010-4c7681c88b46.png">
