### ISSUE TITLE
Wiki page on deploying to Ubuntu is obsolete

### ISSUE THREAD

**Issue by MGPalmer** [mperham/sidekiq#4461]
Hello hello!

I'm not sure if this is known or not, but it seems to me that this page: https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu might be confusing to some developers as Ubuntu hasn't used upstart for a while now. Maybe add a note to the top of the page?

Thanks for the great tool otherwise!

**Comment by mperham** [comment]
I’ll take care of it. Thanks for the note.

**Comment by MGPalmer** [comment]
Great!
