### ISSUE TITLE
Local Worker Heartbeat Monitor

### ISSUE THREAD

**Issue by juandiegopalomino** [mperham/sidekiq#4462]
Ruby version: 2.6.4
Sidekiq Pro version: 5.0.1"

Hi there,

I was wondering if there was any established way of having a way of determining whether sidekiq is active/listening correctly on a specific server. The use case is to have a set of containers running as a pool of workers, and each container having a heartbeat monitoring that sidekiq is running correctly in said container (e.g. if it were a rest server it would be hitting a /ping endpoint and confirming a 200 response). It's a long shot but I figure other folks might have something similar.

**Comment by mperham** [comment]
5.2.8 has been published.

**Comment by mperham** [comment]
Oops, wrong issue!

**Comment by mperham** [comment]
The Related Projects wiki page links to this project, I've never used it so I can't comment on its  quality:

https://github.com/arturictus/sidekiq_alive
