### ISSUE TITLE
Shutdown without raising an exception

### ISSUE THREAD

**Issue by manuel-sanchez** [mperham/sidekiq#4464]
Ruby version: 2.5
Sidekiq / Pro / Enterprise version(s):
5.2.7
Please include your initializer and any error message with the full backtrace.

I'm using sidekiq in a kubernetes environment, when the pods are terminated because of a deploy SignalException: SIGTERM is raised. In kubernetes a TERM signal is expected when doing a termination of a pod, is there a way to have sidekiq not throw an exception when a TERM signal happens? Puma has an option on their configuration file to avoid throwing this exception (raise_exception_on_sigterm false) maybe there's something similar (but I couldn't find) for sidekiq?
Thanks

**Comment by mperham** [comment]
Sidekiq does not throw an exception upon TERM so you’ll need to be more specific.

**Comment by manuel-sanchez** [comment]
Hi Michael, sorry, Ruby is definitely not a language I handle much, but I'm seeing a SignalException: SIGTERM message on airbrake when the pods containing sidekiq get deleted, after seeing the shutdown messages in the logs:
```
2020-02-17T23:08:53.095Z 1 TID-gn0otdkg5 INFO: Shutting down
2020-02-17T23:08:53.095Z 1 TID-gn0otdkg5 INFO: Terminating quiet workers
2020-02-17T23:08:53.095Z 1 TID-gn0pw85l1 INFO: Scheduler exiting...
2020-02-17T23:08:53.596Z 1 TID-gn0otdkg5 INFO: Pausing to allow workers to finish...
2020-02-17T23:08:54.597Z 1 TID-gn0otdkg5 INFO: Bye!
```

Tracking it down it seems to come from [SIGTERM](https://github.com/mperham/sidekiq/blob/0cfd82bd933ea0835a3af387bd824bab7b291afb/bin/sidekiqload#L72)
Don't know much more to add, is there any other information I can provide?

**Comment by mperham** [comment]
https://github.com/airbrake/airbrake/issues/1025
