### ISSUE TITLE
Tasks never finishing - Hung threads

### ISSUE THREAD

**Issue by Mathiou04** [mperham/sidekiq#4465]
Ruby version: 2.4.9
Sidekiq : 4.2.6
Rails: 4.2.11.1

We are facing an issue where sidekiq jobs never finish: they stay in the dashboard as tasks in progress.
The issue seems to arise under particularly heavy load. It looks like the whole process is not frozen as some tasks are still performed by other threads in the same process.

We followed the guidelines in [Problems & Troubleshooting](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes) and got a gdb [stacktrace](https://gist.github.com/Mathiou04/4ad16789c122ed25ad4a665db7d265b0).

I do not think it is a bug in sidekiq, more an issue with a gem we use but I am not sure how to interpret the stacktrace.
It looks like it could be the `grpc` gem but it is clearly not what I expected (I was convinced that it was related to `pg`).

EDIT: looking a bit closer, this seems related to `pg` as there are few traces where the gem is actually involved.

**Comment by mperham** [comment]
Yes, you have a process frozen on pg, upgrade `pg`.  Sidekiq 4 is no longer supported, please upgrade to 5 when possible.

**Comment by Mathiou04** [comment]
@mperham Thanks for confirming this and having taken a look.
We plan to update our sidekiq version very soon.
