### ISSUE TITLE
environment initialized with RACK_ENV before RAILS_ENV?

### ISSUE THREAD

**Issue by justinlang** [mperham/sidekiq#4466]
Hi!  Less an issue, and more of a question...  Apologies if this is not the right place for it.

I'm wondering what the rationale was for the following change:
https://github.com/mperham/sidekiq/commit/95fa5d90192148026e52ca2902f1b83c70858ce8#diff-411201f0104d91346964914342a07cef

Specifically, the re-ordering of `ENV['RAILS_ENV']` and `ENV['RACK_ENV']` in the initializer.

Note that `ENV['RAILS_ENV']` is still preferred in helper.rb: https://github.com/NeatNerdPrime/sidekiq/pull/37/files

Context: we noticed that sidekiq in our app is being set with the value from `ENV['RACK_ENV']` whereas previously it was using the `ENV['RAILS_ENV']` value.

**Comment by mperham** [comment]
I think it was reordered to be sorted broader-> narrower.  Rails apps are a subset of Rack apps which are a subset of all apps. Looking back, I'm not sure Sidekiq should be responding to RACK_ENV at all but that's water under the bridge now.

**Comment by justinlang** [comment]
Thanks for the context!

**Comment by masterkain** [comment]
this change made sidekiq start and process jobs in `production` env on a staging kubernetes pod that had only defined `RAILS_ENV=staging`.
