### ISSUE TITLE
'sidekiq_options retry: 0' not working with activejob 5.2.4.1

### ISSUE THREAD

**Issue by Diego-Zulu** [mperham/sidekiq#4467]
Ruby version: 2.6.3
Sidekiq version: 6.0.5

Creating a new project with `rails 6.0.2.1`, and adding `sidekiq_options retry: 0` to any jobs implementing `ActiveJob::Base` caused the job to be moved to the dead set if it fails.

Nevertheless, creating a new project with `rails 5.2.4.1`, adding `sidekiq_options retry: 0` to any jobs implementing `ActiveJob::Base` has no effect at all. The job will be retried until max_retries is reached per usual.

Is this intended?

Thanks for the help

**Comment by mperham** [comment]
That integration only works with the latest Sidekiq and Rails.

**Comment by Diego-Zulu** [comment]
Shouldn't that be added to the docs? The only mention of Rails I found on the readme was `Sidekiq 6.0 supports Rails 5.0+ but does not require it.`

**Comment by mperham** [comment]
It is in the docs: the ActiveJob wiki page.

**Comment by Diego-Zulu** [comment]
[This one?](https://github.com/mperham/sidekiq/wiki/Active-Job). In the [customizing error handling section](https://github.com/mperham/sidekiq/wiki/Active-Job#customizing-error-handling) it only mentions `Sidekiq 6.0.1`. Apart from that, I only see `Rails 4.2` mentioned at the top

**Comment by mperham** [comment]
Hmm. When in doubt, read the changelog.

**Comment by Diego-Zulu** [comment]
It was on the changelog for version 6.0, not version 6.0.1 as mentioned on the wiki. I modified the Activejob wiki entry to prevent further confusion. Thanks for your help

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/Changes.md#604
