### ISSUE TITLE
ArgumentError: undefined class/module

### ISSUE THREAD

**Issue by manuelmeurer** [mperham/sidekiq#447]
I'm getting a `ArgumentError: undefined class/module` error when trying to delay a job on a class that's located in the `lib` folder.

`ProductManager.delay.run(991)` produces the following:
http://screencast.com/t/UlGYMxgLw8

I tried with several classes and modules in `lib`, all with the same result.
Doing the same with models in `app/models` works fine.

I autoload lib in `application.rb` via `config.autoload_paths`.
This doesn't seem to work in the Sidekiq workers.

This is probably an error in my setup, not in Sidekiq itself, but I'd appreciate any tips since I'm out of ideas...

**Comment by g-ilham** [comment]
@mperham yep, with `require_dependency` this is working.
