### ISSUE TITLE
Rate limited worker stays paused.

### ISSUE THREAD

**Issue by chrisjwu** [mperham/sidekiq#4471]
Ruby version:
Enterprise 1.8.1

Please include your initializer and any error message with the full backtrace.

```
redis_config = Rails.application.config_for(:redis)
redis_url = "#{redis_config['host']}:#{redis_config['port']}"
redis_url = 'redis://' + redis_url if redis_url !~ /^redis:\/\//

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.redis = { url: redis_url, network_timeout: 2, db: 1 } 
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url, network_timeout: 2, db: 1 } 
end
```

Here's a gist with a tstp call: https://gist.github.com/chrisjwu/e3e450547793121d969a0ceb8ad73a8e

On line 9 you can see it successfully completing a job, line 11, 12, 13 show it polling the rate limiter to see if it can continue.  Then you can see on line 14 that it never woke up, when I quieted all workers to debug a different issue 3 hours later.

Any idea what would cause the worker to hang like that?  To my knowledge this hasn't happened since.

**Comment by mperham** [comment]
The only processor thread is blocked on a database call. I suspect you are looking at a non-Sidekiq thread sleeping.

**Comment by chrisjwu** [comment]
Oh, I see the postgres call now in line 28.  Interesting, so it started execution and hung on the db.  Would explain why it hasn't happened since.  Time to see if there are any db logs I can check now.

Thanks.
