### ISSUE TITLE
Sidekiq is changing ENV variables

### ISSUE THREAD

**Issue by mobilutz** [mperham/sidekiq#4472]
This is more a question, than a bug report and feature report.

With the upgrade to 6.0.5 and the use of `ENV['APP_ENV'] etc.` we saw a problem in our staging system that we did not expect at all.
We are fixing that, as we did have some incorrect setup on our system.

But while looking a bit through sidekiq code, I stumbled over this line:
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L244
This can be traced back to the first sidekiq/rails integration here:
https://github.com/mperham/sidekiq/commit/a1f78816a76dcab0aa7cc37d4ebb2c3c6c920afe#diff-411201f0104d91346964914342a07cefR44

What I am asking is:
Why does sidekiq first read `ENV['RAILS_ENV']` and then changes it what is reads from other ENV variables?

I don't want to open the discussion of `RACK_ENV` should always be the same as `RAILS_ENV`, because this is not the topic of sidekiq, I just want to understand, why sidekiq changes some settings, that have been set on purpose by someone during its initialisation?

**Comment by mperham** [comment]
I think the original thought was to standardize any \*\_ENV variables to a single value but it was probably a mistake to touch anything in the ENV. Unfortunately since it's been baked in like that forever, I'm reluctant to change it.

**Comment by mobilutz** [comment]
Thanks Mike for your response.

I agree, that changing this is not really easy without thinking about it a bit. I wonder, why the change in 6.0.5 was just integrated like this. I am not saying to revert this change, but this was (at least for us - specifically the change in order of `RAILS_ENV` and `RACK_ENV`) a breaking change. But now that it is in sidekiq, it is totally ok.
https://github.com/mperham/sidekiq/commit/95fa5d90192148026e52ca2902f1b83c70858ce8

Would you like to receive a PR to have a graceful change for the ENV change.
What I mean is something like this:
# optional configuration to not change ENVs globally - opt-out
# integrate a Deprecation Warning that the ENVs are being changed
# in a future version, make the configuration the other way round - meaning an opt-in and not an opt-out

This is then a possible way, of removing the ENV change from sidekiq with time heads-up and info on the change.

**Comment by mperham** [comment]
The order change was done because I assumed that people would only set one or the other, not have both set.

I would rather just leave it as is. I don't see a good reason to add configuration elements around it and increase the complexity of the code. In the future I will make an effort not to change any semantics. I'm sorry for the frustration this caused you.
