### ISSUE TITLE
Server middleware `ensure` block is not the last thing to be called?

### ISSUE THREAD

**Issue by jeffblake** [mperham/sidekiq#4473]
Ruby version: 2.7.0
Sidekiq / Pro / Enterprise version(s):

sidekiq (6.0.5)
sidekiq-ent (2.0.1)
sidekiq-pro (5.0.1)

Given a server middleware,

```
class SidekiqMiddleware 
  
  def call(worker_class, job, queue)
    yield
  ensure
    puts 'done'
  end
  
end
```

The `ensure` block above is called before `job_logger` logs its `done` message. I was surprised, and thought the middleware would be at the 'top', similar to rack middleware, but obviously not the case when I looked at  https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L162

I'm sure there's a reason the way it is... and I'm deeply curious. It appears the behavior changed with the release of v5.

**Comment by mperham** [comment]
Nothing has changed, that’s how middleware generally work, as they are implemented with a stack: First in, last out.

**Comment by mperham** [comment]
Ah, the logger used to be middleware. Now it is implemented outside of the middleware stack.

**Comment by jeffblake** [comment]
Yes I see that. Not a big deal, I moved the ensure to the JobLogger. Feels a little dirty, but it's ok. Thought I'd bring it up in case this was overlooked during the v5 refactor.

What I'm doing is logging a single canonical line for every job completion (in JSON), with metadata about things that happened during the job (http requests, etc stored in `Thread.current` state). `Sidekiq::Context` doesn't work here as I don't know the context to add in advance.
