### ISSUE TITLE
Should `establish_connection` method be called explicitly?

### ISSUE THREAD

**Issue by deopard** [mperham/sidekiq#4474]
Ruby version: 2.6.3
Rails version: 5.2.4.1
Sidekiq / Pro / Enterprise version(s): 5.2.7 / - / -

I am not calling `establish_connection` explicitly. The database connection gets established when the first job with ActiveRecord runs.
There's no problem if there are 1 or fewer jobs waiting in the queue. But when there are 2 or more, jobs will start simultaneously and they will all fail after trying to get the database connection.
(ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found.)

Error logs
![image](https://user-images.githubusercontent.com/1886749/75641724-94c72280-5c7c-11ea-8243-04698170683f.png)

The problem doesn't occur when I call the establish_connection method explicitly when configuring Sidekiq server.

```ruby
# config/initializers/sidekiq.rb
  Sidekiq.configure_server do |config|
    config.redis = { url: "redis://#{APP_CONFIG.dig('redis', 'host')}", namespace: APP_CONFIG.dig('redis', 'namespace') }

    ActiveRecord::Base.establish_connection(Rails.configuration.database_configuration[Rails.env])
  end
```

I've been using Sidekiq for few years and never ran into this problem.  I thought that I can use ActiveRecord without thinking thread-safe.

So my final question is **"Does establish_connection method need to be called explicitly when using Sidekiq server?"**

**Comment by mperham** [comment]
No, it doesn’t.

**Comment by deopard** [comment]
@mperham Thanks for the reply. Do you have any idea why this error is happening then?

**Comment by mperham** [comment]
No one else is complaining so I suspect you have some sketchy initializer code somewhere in your app.
