### ISSUE TITLE
Fetching more than one job at a time from the queue

### ISSUE THREAD

**Issue by djpate** [mperham/sidekiq#4477]
Hello,

We are looking for a potential way to fetch more than one job at a time from the queue.

We have a job which has to push items to a FIFO SQS once it's finished and we're being throttled as SQS only allows 300 puts/sec. We could scale this us 10x if we could batch send our messages but in order to do that we would need to fetch 10 jobs out of the queue at once.

Is that something that is doable somehow? We can create our own buffer queue in Redis and somehow send that once it reaches 10 but it would be easier if we could do it from the poller side.

Thanks for any input.

**Comment by mperham** [comment]
Single fetch is how Sidekiq works and many features are implemented on that assumption (e.g. super_fetch).

There's nothing stopping you from implementing your own Redis queue and using a Sidekiq job to occasionally batch fetch and push to SQS yourself but that queue would be outside of Sidekiq's domain and control.
