### ISSUE TITLE
Remove automatic Redis connection naming

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4479]
Unfortunately this feature is often disabled by SaaSes and so Sidekiq users have to manually disable it. I don't believe it adds much value; I've never heard of anyone using it as intended for debugging purposes so let's remove it.

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L15

**Comment by Tolsto** [comment]
We actually did use it :(
Would you consider re-adding it to Sidekiq(-Pro) as a configurable option?

**Comment by mperham** [comment]
You can add it yourself, just add an :id key to the redis hash in your initializer.
