### ISSUE TITLE
Ajax uses setInterval instead of setTimeout, leading to server load

### ISSUE THREAD

**Issue by oskarpearson** [mperham/sidekiq#4480]
Thanks for a great product

Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.8 (code for 6.0.5/master on github contains the same issue)

Initializer and error message: not applicable

### Detail:

The javascript at https://github.com/mperham/sidekiq/blob/master/web/assets/javascripts/application.js#L58 uses `setInterval`. This queues a query to the backend via ajax irrespective of whether the last AJAX request has responded or not.

If there are problems with the infrastructure running the Sidekiq web ui (eg, overloaded web servers), this will make those problems worse - since ajax requests will be queued continuously and increase the established connections to the web ui host.

The general practice is to instead use `setTimeout` to queue a new request on completion of the last request. See https://makitweb.com/how-to-fire-ajax-request-on-regular-interval/ for more information.

### Why:

Unfortunately, we had a large number of items incorrectly queued with large message bodies (exceeding the size listed at https://github.com/mperham/sidekiq/blob/455e9d56f46f0299eaf3b761596207e15f906a39/lib/sidekiq/extensions/generic_proxy.rb#L7)

In trying to access the web page, clicking `poll` would bring the management app down. This is because running `lrange queue:low 0 24` would take 6 seconds to respond. In the time it took the first ajax request to respond another 3 ajax requests were queued - which then took 6 seconds to respond each. In short order, this exceeded the number of connections on the web server and it restarted when the load balancer removed it.

**Comment by mperham** [comment]
Seems like an easy fix but I'm not really very good at JavaScript, anyone care to send a PR?
