### ISSUE TITLE
How to set Sidekiq Queue Priority. [PRO]

### ISSUE THREAD

**Issue by manishankar2** [mperham/sidekiq#4482]
Ruby version: 2.3.1
Sidekiq Pro. We are using 4.0.3 version 
Question: 
We have approx 100 queues in our product. We are planning to have instance specific queues.( i.e fewer queues running in specific instances). Also We are running 3 Sidekiq process with concurrency of 25 each in an instance. (this is also variable depending on the Queues).
Is there a max_value/range we can keep as a priority for a queue. ? 
Is there a recommendation like it should be based on concurrency ?
For eg: Let's say I have
Queue A with priority as 10 and Queue B with priority as 20. 
Is it similar to 
Queue A with priority as 100 and Queue B with priority as 200. ?
Do we have same outcome for both options?

**Comment by manishankar2** [comment]
> Ruby version: 2.3.1
> Sidekiq Pro. We are using 4.0.3 version
> Question:
> We have approx 100 queues in our product. We are planning to have instance specific queues.( i.e fewer queues running in specific instances). Also We are running 3 Sidekiq process with concurrency of 25 each in an instance. (this is also variable depending on the Queues).
> Is there a max_value/range we can keep as a priority for a queue. ?
> Is there a recommendation like it should be based on concurrency ?
> For eg: Let's say I have
> Queue A with priority as 10 and Queue B with priority as 20.
> Is it similar to
> Queue A with priority as 100 and Queue B with priority as 200. ?
> Do we have same outcome for both set of queues ?

**Comment by mperham** [comment]
Yes, and the same as 1 and 2.
