### ISSUE TITLE
Sidekiq workers get stuck when connecting to another redis pool

### ISSUE THREAD

**Issue by fighterleslie** [mperham/sidekiq#4483]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): OSS 3.3.3

Hi, we have sharded our background jobs and often observed that Sidekiq workers get stuck when connecting to one of Redis pools.

TTIN backtrace is below: 

https://gist.github.com/fighterleslie/f6f8b6b89a04ba430ae2aaa6b9c1166e

Other infos:

Sidekiq concurrency: 20

Below are some snippets from initializers:

IN: config/initializers/1_redis.rb

```ruby
UDESK_SIDEKIQ_REDIS_CONFIG = {
  host: UdeskEnv.sidekiq_redis.host,
  port: UdeskEnv.sidekiq_redis.port,
  db: Rails.env.test? ? 3 : 0
}

UDESK_VOLCANO_REDIS_CONFIG = {
  host: UdeskEnv.volcano_redis.host,
  port: UdeskEnv.volcano_redis.port,
  db: Rails.env.test? ? 3 : 0
}
UDESK_VOLCANO_REDIS                        = Redis.new(UDESK_VOLCANO_REDIS_CONFIG)
UDESK_VOLCANO_SIDEKIQ_NAMESPACE            = Rails.env.production? ? :udesk_volcano_sidekiq : :"udesk_volcano_sidekiq_#{Rails.env}"
UDESK_VOLCANO_SIDEKIQ_REDIS_WITH_NAMESPACE = Redis::Namespace.new(UDESK_VOLCANO_SIDEKIQ_NAMESPACE, redis: UDESK_VOLCANO_REDIS)
UDESK_VOLCANO_SIDEKIQ_REDIS_POOL           = ConnectionPool.new(size: 22, timeout: 1) { UDESK_VOLCANO_SIDEKIQ_REDIS_WITH_NAMESPACE }
```

IN config/initializers/sidekiq.rb

```ruby
def sidekiq_redis_config
  server = UDESK_SIDEKIQ_REDIS_CONFIG[:host]
  port   = UDESK_SIDEKIQ_REDIS_CONFIG[:port]
  db     = UDESK_SIDEKIQ_REDIS_CONFIG[:db]

  config = {}
  config[:url]       = "redis://#{server}:#{port}/#{db}"
  config[:namespace] = Rails.env.production? ? 'udesk_proj_sidekiq' : "udesk_proj_sidekiq_#{Rails.env}"
  return config
end

Sidekiq.configure_server do |config|
  config.redis = sidekiq_redis_config
  config.poll_interval = 1
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_redis_config
end
```

The problematic worker which gets stuck often:

```ruby
class ImMonitSessionWorker
  include Sidekiq::Worker
  sidekiq_options queue: :im_monit, retry: false, pool: UDESK_VOLCANO_SIDEKIQ_REDIS_POOL

end
```

in app/models/concerns/im_sub_session_v4.rb
```ruby
  def im_monit_session_data_worker
    ## logic omitted
    ImMonitSessionWorker.perform_async(attrs)
  end
```

This worker `ImMonitSessionWorker` only pushes jobs to the given redis instance (as a client), and the jobs are processed by another application. 

To fix this issue, we have tried:

- increase the UDESK_VOLCANO_SIDEKIQ_REDIS_POOL size, from default 5 to 10, to 20, to 22 (concurrency + 2), not working
- upgrade the redis gem version: from 3.1.0 to 3.3.3, not working

**Comment by mperham** [comment]
You are using global connections within your pool.  Don't do that.
