### ISSUE TITLE
Sidekiq Web UI - partial loading view, navigation only

### ISSUE THREAD

**Issue by paulggapps** [mperham/sidekiq#4484]
We have used Sidekiq and Sidekiq Web UI without incident for over 2 years.

This issue only affects Sidekiq Web not Sidekiq which is working normally. The queue is not really under any stress either. This is a staging and pre release environment and blocking a release to Production.

Now in the latest deployments, the Sidekiq Web UI loads, then after 5 minutes loses all data except [navigation.]
<img width="1440" alt="Screenshot 2020-03-11 at 13 37 06" src="https://user-images.githubusercontent.com/1950932/76422976-02baca80-639e-11ea-930a-d7b19a6f831f.png">

NGINX is under changed for 2 years.

There is nothing in system, application error logs. No specific changes to GemFile.

Very strange! 

Anyone seen anything like this before?

We are looking at upgrading but thought it was worth raising here too.

--

Ruby version: ruby 2.4.2p198

Sidekiq

Please include your initializer and any error message with the full backtrace.
```
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end
```

Only Authenticated Users can access Sidekiq Web:
```
require 'sidekiq/web'
mount Sidekiq::Web => '/admin/sidekiq'
```

Are you using an old version? 
5.0.5

Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md

**Comment by SenikTony** [comment]
I think I have a similar problem too.
![Selection_284](https://user-images.githubusercontent.com/1132944/76614205-a805a800-6530-11ea-85f8-8120ca07dfab.jpg)
![Selection_285](https://user-images.githubusercontent.com/1132944/76614550-5f022380-6531-11ea-9fe3-c1eb57474e4f.jpg)

**Comment by mperham** [comment]
Which browser? Does this happen in Sidekiq 6.0.5?

**Comment by mperham** [comment]
Can't reproduce in Safari or Firefox.  Please give me explicit steps to reproduce.

**Comment by SenikTony** [comment]
@mperham 
- Sidekiq 6.0.2
- Google Chrome browser, Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by SenikTony** [comment]
@mperham, it’s hard for me to highlight any steps... After another deployment to Heroku, the Web UI became a blank screen...

We use Standard-1X dynos with Heroku Redis add-on
We start like this:
```
bundle exec sidekiq -e production -t 25 -C config/sidekiq.yml
```

**Comment by paulggapps** [comment]
@mperham will try rolling back to a previous release to see if a recent gem security update is affecting it. It has been working perfectly for 2 years. We have been using Chrome to access it. The strange thing is console, nginx, application and system logs report no errors.

**Comment by mperham** [comment]
Maybe this is possibly related to the recent Rack troubles? Since you haven't told me your Sidekiq version, I can't know more.

**Comment by mperham** [comment]
I'm going to ship 6.0.6 later this week so if you want me to possibly fix this, I'll need more info ASAP.

**Comment by SenikTony** [comment]
@mperham updating Sidekiq to version **6.0.5** solved my Web UI problem.

**Comment by mperham** [comment]
Thank you!

**Comment by paulggapps** [comment]
@mperham sorry for not replying sooner, we upgraded to 6.0.5 and that too solved the issue. We were using 5.0.5 - thanks for all your help on this.

**Comment by arcreative** [comment]
@mperham I'm having the same issue with this--driving me nuts!  There's nothing particularly interesting about the implementation I'm using, but I have Sidekiq on about a dozen projects, and this is the only one that does it.  In troubleshooting, I removed the New Relic gem that I was using for APM, and that allows the UI to render as expected... is there a max page length or something preventing the entire thing from loading?

**Comment by arcreative** [comment]
And for reference, I'm still encountering the issue on 6.1.2

**Comment by mperham** [comment]
It's a NewRelic bug. Did you `bundle up newrelic_rpm`?

**Comment by arcreative** [comment]
@mperham I did, which seems to have resolved it after a bit more grunt work.  Not sure how a little script injection makes it fail in this way... but seems good for now.   Thanks!
