### ISSUE TITLE
Redis::CannotConnectError at / Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) Ruby	/srv/redis-io/.gs/gems/redis-3.3.2/lib/redis/client.rb: in rescue in establish_connection, line 345

### ISSUE THREAD

**Issue by X025me** [mperham/sidekiq#4486]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
This means Redis is  not  running.
