### ISSUE TITLE
Add systemd notify and watchdog support

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4488]
As Sidekiq is meant to be a long-running daemon, it should support the notification and watchdog functionality that systemd allows.

* [x] Add READY=1 notification upon startup
* [x] Add STOPPING=1 notification upon terminate
* [x] Add WATCHDOG=1 loop

See also https://github.com/agis/ruby-sdnotify
https://www.freedesktop.org/software/systemd/man/sd_notify.html

**Comment by krasnoukhov** [comment]
Can you please clarify whether this works with `sidekiqswarm`? It's not clear from the docs/changes

**Comment by mperham** [comment]
Right now it is only designed to work when running single process. If you want to open an issue, I’d be happy to get it working in swarm.
