### ISSUE TITLE
Question re: queue names and not using a default queue

### ISSUE THREAD

**Issue by akotranza** [mperham/sidekiq#4501]
Ruby version: 2.4.4
Sidekiq / Pro / Enterprise version(s): 3.4.2

We are attempting to do something similar to "[How do I ensure a job process on a given machine?](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-ensure-a-job-processes-on-a-given-machine)" but rather than targeting 1 of N machines, it's targeting 1 of N kubernetes deployments sharing the same redis cluster. (We've read your guidance against sharing, but for the time being...)

Sidekiq is run as follows with `unique-deployment-name` injected in the deployment process
`sidekiq -c 5 -q unique-deployment-name`

I found [this comment](https://github.com/mperham/sidekiq/issues/1249#issuecomment-26282604) that the `default` queue does not exist if it's not specified.

With only modifying the sidekiq args as above I still see a free-for-all of N deployments grabbing jobs enqueued by `unique-deployment-name` deployment

Is it the case that when no `default` queue exists that workers still need to specify the non-default queue name, as in

`sidekiq_options queue: 'unique-deployment-name'`

else they are enqueued in `default`?

I know this is in reference to an ancient version, so I'm more asking for a sanity check :)

Thanks

**Comment by mperham** [comment]
Sorry, I'm not willing to support v3 any more, not even as a sanity check.
