### ISSUE TITLE
Ok to spawn threads in workers?

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#4503]
Ruby version: 2.6.2
Sidekiq  version(s): 6.05

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

Sidekiq stopped processing new jobs a couple of times today.  I haven't been able to to get into the heroku worker dyno yet to send TTIN to get debug info, but I have a suspicion what the source of the problem may be:

I have a worker than spawns four threads.

(I spawn the four threads because we connect to a rate limited api that we need to paginate and it's rate-limited per endpoint, so rather than paginate over four workers, I thought to do them in parallel)

Lately, we had some connection timeouts in the threads so I introduced a handler with a typo which raised an ArgumentError.

and I also set `Thread.abort_on_exception = true` 

so maybe that's just a pile of no-nos for sidekiq? Don't thread within a threaded worker and don't set `Thread.abort_on_exception = true`?  

I haven't seen anything about this in the docs so I thought I'd raise it.

**Comment by mperham** [comment]
Oh dear, no.  Don't use `abort_on_exception` or you might kill Sidekiq. You can use your own threads, yes. I would urge you to use a gem like `parallel` to help manage the threads.
