### ISSUE TITLE
Feature Proposal: Pause/Resume Job Processing

### ISSUE THREAD

**Issue by kellysutton** [mperham/sidekiq#4506]
:wave: Hello! I've got a feature proposal for Sidekiq that I'd like to write up here to see if there's any interest. (If there is a better avenue for such things, let me know).

Some context, we recently switched over to Kubernetes as my work. Kubernetes is interesting because it treats each deploy as bringing up entirely new machines. Although we use Sidekiq Enterprise, we cannot take advantage of the [rolling restarts feature](https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts) because each machine is new on each deploy.

To allow for safe rolling restarts in the context of Kubernetes or things like it, I think the following would work:

- Allow Sidekiq to start in a mode where it will not pick up any jobs. This could be determined by a CLI flag and/or an option in the configuration file. Sidekiq processes loaded this way will eager load all the code and then wait.
- The host system sends a signal to the Sidekiq process to start processing work. (Looking at the [Linux man page for signal(7)](http://man7.org/linux/man-pages/man7/signal.7.html), it looks like `SIGCONT` could be a contender.) The Sidekiq process begins processing jobs.
- On the shutdown side, we can still use [`SIGTSTP` to pause the workers](https://github.com/mperham/sidekiq/wiki/Signals#tstp). 
- Something for discussion, should sending a `SIGCONT` signal to a worker that has received a `SIGTSTP` resume processing of jobs?

These seem like the primitives to allow Sidekiq to work in an environment where new deploys mean entirely new machines.

Is this something that would be useful in Sidekiq? If so, I can take a crack at putting up a PR to enable this functionality for further discussion.

**Comment by mperham** [comment]
I'm ok with exploring this idea with a PR or as a 3rd party gem. Should there be a timeout if the process doesn't ever get CONT? Should a process be listed on the Busy page before it gets CONT?

Iron clad rule: once Sidekiq gets TSTP, the process must exit. You cannot restart processing.

**Comment by kellysutton** [comment]
I'll explore this is as a PR for now, since it will require modifying the [`SIGNAL_HANDLERS` constant](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/cli.rb#L147-L167) from what I can tell. If we get to an implementation that makes sense, we can discuss pulling it out into a gem.

> Iron clad rule: once Sidekiq gets TSTP, the process must exit. You cannot resume processing.

Noted, I'll remove that from consideration.

Agreed on the miscellany required here to figure out. Another thing to add to the mix: How should this affect leader election in Sidekiq Pro?

Here are my thoughts on the other questions proposed:

> Should there be a timeout if the process doesn't ever get CONT?

To keep things simple, I think the answer right now is "No." There might be a future where a timeout would be desirable/configureable. Happy to reconsider this.

> Should a process be listed on the Busy page before it gets CONT?

I think the answer here should be "Yes" to keep the web UI as authoritative in regards to "What are my Sidekiq processes doing right now?" We could label these processes as "Quiet Start" or "Waiting signal to start processing."

> If your old periodic jobs are active and a new process comes online, should the new periodic jobs take effect immediately or not until CONT?

No opinion here. What's the current behavior with same-host rolling-restarts? It might make the most sense to mirror that. If that's not a suitable analog, we can get at it via another question. When in the booting process does registering periodic jobs currently happen: Before or after processing the first job? 

If before, we register the periodic jobs on boot. 

If after, we don't register periodic jobs until the CONT is received.

**Comment by mperham** [comment]
* Leader election is in Enterprise. The current rule is that a process remains leader until it exits.  Even while quiet, it will continue to lead (enqueue periodic jobs, e.g.). There is no current way to force a leader to step down except to exit the process.
* Periodic jobs are registered on boot. When a process takes leadership, it pushes its current set of periodic jobs as the "active" set. That's what the Web UI shows. This "push" can happen well after the process has booted up.

**Comment by kellysutton** [comment]
Cool. This should give me enough to get a PR put together. Thanks!
