### ISSUE TITLE
Sidekiq 6 does not work with Redis-To-Go

### ISSUE THREAD

**Issue by pmichaeljones** [mperham/sidekiq#4507]
I upgraded from Sidekiq 5.2.8 to Sidekiq 6.0.6 yesterday. Rails 5.0.2.4 on Heroku. UI worked perfectly, but jobs only got queued and never got processed, and I noticed my processes never started from my procfile.

<img width="1230" alt="Screen Shot 2020-03-24 at 4 18 30 PM" src="https://user-images.githubusercontent.com/6728265/77517637-c8146000-6e7c-11ea-9c43-a4be13a98a4f.png">

I take a look at my logs and sure enough, Sidekiq crashed because Redis to Go uses Redis 3.2.12 and Sidekiq wants 4. 

![Screen Shot 2020-03-25 at 9 31 36 AM](https://user-images.githubusercontent.com/6728265/77516940-8afb9e00-6e7b-11ea-81da-732c9cc44166.png)

Naturally, I thought this was my mistake and I didn't have the right version of Redis To Go set, but I looked at [Redis to Go Heroku Docs](https://devcenter.heroku.com/articles/redistogo#redis-3-2
) and it appears Redis to Go is still using 3.2.12 and is not planning on upgrading anytime soon. The docs were last updated January 23, 2020, so they're fresh.

![redis-fail](https://user-images.githubusercontent.com/6728265/77516942-8c2ccb00-6e7b-11ea-8247-cbd1607a419a.png)

**Comment by mperham** [comment]
Wow, looking at that website, it really looks like they haven't touched their site in years. Not a good sign.

Alternatives for others to consider:

* RedisLabs.com
* RedisGreen.net
* Heroku Redis

**Comment by mperham** [comment]
Thanks for the heads up.
