### ISSUE TITLE
Doesn't quiet process on another host

### ISSUE THREAD

**Issue by hopewise** [mperham/sidekiq#4512]
Ruby version: 2.7.0
Sidekiq / Pro / Enterprise version(s): Sidekiq

**Initializer:**
```
Sidekiq.configure_server do |config|
  config.redis = {
    url: "redis://#{Settings.redis.host}:#{Settings.redis.port}/#{Settings.redis.db}",
    namespace: "sidekiq"
  }
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
  end
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: "redis://#{Settings.redis.host}:#{Settings.redis.port}/#{Settings.redis.db}",
    namespace: "sidekiq"
  }
  config.client_middleware do |chain|
   chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes
 end
end
```

Are you using an old version? no

**Current behavior:**

I try to quiet a process that is on a different host, I have tried using the rails CLI of my app:

```
ps = Sidekiq::ProcessSet.new
ps.first.quiet!
=> [1, true]
```

but the process will not be quieted, however, I can quiet it if I am at the same host.
is there any settings that I have to allow for the security group? like a port number or so?

**Comment by mperham** [comment]
Do both machines share the same Redis settings?

**Comment by hopewise** [comment]
The above Sidekiq initializer is the only shared settings between two rails apps.

**Comment by mperham** [comment]
Is the console part of app 1 and the Sidekiq process part of app 2?

**Comment by hopewise** [comment]
Yes, to make it clear:

app 1 is an empty rails project, created just to view Sidekiq web ui
Sidekiq process is part of app 2

each app is on a different server

**Comment by mperham** [comment]
I see no reason why that shouldn't work as long as both apps share identical Redis config.

**Comment by hopewise** [comment]
What do you recommend to debug this?

**Comment by mperham** [comment]
puts? I don't have a good answer.
