### ISSUE TITLE
When using Sidekiq as Systemd service, jobs move into enqueued and stay there

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [mperham/sidekiq#4520]
Ruby/Sidekiq version:

```
$ rbenv versions
* 2.4.1 
$ gem list | grep sidekiq
sidekiq (4.2.10)
```
Please include your initializer and any error message with the full backtrace.

Sidekiq runs as a systemd service. Here's the important lines from the service:

```
# /lib/systemd/system/sidekiq.service
Type=simple
# WatchdogSec=5
WorkingDirectory=/var/www/html/RailsApp
ExecStart=/bin/bash -lc 'exec /home/ubuntu/.rbenv/shims/bundle exec sidekiq -e production'
User=ubuntu
Group=ubuntu
UMask=0002
```

Systemd status:

```
$ systemctl status sidekiq
● sidekiq.service - sidekiq
   Loaded: loaded (/lib/systemd/system/sidekiq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-03 03:29:47 UTC; 22min ago
 Main PID: 28893 (bundle)
    Tasks: 29 (limit: 4647)
   CGroup: /system.slice/sidekiq.service
           └─28893 sidekiq 4.2.10 RailsApp [0 of 25 busy]

Apr 03 03:29:47 ip-172-31-33-134 systemd[1]: Started sidekiq.
Apr 03 03:29:50 ip-172-31-33-134 sidekiq[28893]: /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/associations.rb:16
Apr 03 03:29:50 ip-172-31-33-134 sidekiq[28893]: /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/associations.rb:16
Apr 03 03:29:53 ip-172-31-33-134 sidekiq[28893]: 2020-04-03T03:29:53.558Z 28893 TID-gp5pcmws0 INFO: Running in ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux
Apr 03 03:29:53 ip-172-31-33-134 sidekiq[28893]: 2020-04-03T03:29:53.558Z 28893 TID-gp5pcmws0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
Apr 03 03:29:53 ip-172-31-33-134 sidekiq[28893]: 2020-04-03T03:29:53.558Z 28893 TID-gp5pcmws0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sideki
Apr 03 03:29:53 ip-172-31-33-134 sidekiq[28893]: 2020-04-03T03:29:53.558Z 28893 TID-gp5pcmws0 INFO: Booting Sidekiq 4.2.10 with redis option
```

It's surely running:

```
$ ps aux | grep sidekiq
ubuntu   28893  0.6  3.7 458596 149756 ?       Ssl  03:29   0:09 sidekiq 4.2.10 RailsApp [0 of 25 busy]
```

Yet I restart nginx and puma and open up the Rails app. I execute a button that triggers Sidekiq to create a job. And it goes directly in the queue. If I use sidekiq manually from the shell, it works. Why would it be going into the queue with systemd?

**Comment by mperham** [comment]
Different redis config due to different environment?

**Comment by lovefamilychildrenhappiness** [comment]
So this is what I tried doing. I ran again sidekiq from the root of application:

```
RAILS_ENV=production bundle exec sidekiq --queue health_plus,2 --concurrency 1
```

And it works.

Then I try this from the root of the Rails application (it was in the sidekiq.service template provided in your examples):

```
/bin/bash -lc 'exec /home/ubuntu/.rbenv/shims/bundle exec sidekiq -e production'
```

And it doesn't work. It goes into the queue. So it is this specific command. 

At this point, I don't have the gems installed in vendor/bundle. So they are installed in the 'gem env' gem installation directory, which makes 'bundle exec' able to find the binstub. There's no problem finding the sidekiq binstub. 

It does use the l flag which runs environment variables stored in /etc/profile. But I don't have any environment variables. Any configuration in the Rails app is hardcoded in secrets.yml to keep things simple. 

I also know that the bash command will spawn a new child bash shell inside the bash shell (but this should only affect environment variables since environment variables are not carried over to the bash subshell). But the exec command I believe prevents that from happening and just replaces bash with the command and executes it in the current environment.

So I looked at the command I was running again and the command in your template systemd file and I noticed in mine I specified the queues parameter. So when I run it with the queues parameter, it now seems to work, at least when running it directly in the shell:

```
 /bin/bash -lc 'exec /home/ubuntu/.rbenv/shims/bundle exec sidekiq --queue health_plus,2 --concurrency 1 -e production'
```

I'll try to do the same with the systemd service now.

**Comment by lovefamilychildrenhappiness** [comment]
It seems to now be triggered in systemd environment too. I can get the output from systemctl status:

systemctl status sidekiq.service

Although 'journalctl -u sidekiq -rn 100' isn't giving any much useful output other than telling me that service has started.
