### ISSUE TITLE
sidekiq web with webpacker

### ISSUE THREAD

**Issue by carinabs8** [mperham/sidekiq#4521]
Hey guys, I`m dealing with some stylesheet problems on sidekiq dashboard. Since I started using webpacker, new default on rails 6, all style  on sidekiq web starting break. Have you already notice it?
Or will you stilll use sprockers instead of webpacker?
Thanks for all!!

**Comment by carinabs8** [comment]
Yes, I am. I`ve following the troubleshooting wiki, however it just have being working in develop mode. When I start the production the assets arent`t working since I start using webpack with rails 6

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Monitoring#proxying-the-web-ui

**Comment by mperham** [comment]
Typically that's the problem. No one else has reported webpacker issues - the web UI is self-contained and does not depend on Rails/webpacker at all.
