### ISSUE TITLE
systemd notify with watchdog enabled -> random process restarting

### ISSUE THREAD

**Issue by lizdeika** [mperham/sidekiq#4522]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 5.0.1

https://github.com/mperham/sidekiq/issues/4488

I have enabled this feature as documented in `sidekiq-1.service` and `sidekiq-2.service`
And then processes went wild, restarting every several minutes.
Workers were working as they should.

In the logs:

```
Apr  6 13:21:16 background-2 systemd[1]: sidekiq-1.service: Watchdog timeout (limit 5s)!
Apr  6 13:21:17 background-2 systemd[1]: sidekiq-1.service: Main process exited, code=dumped, status=6/ABRT
Apr  6 13:21:17 background-2 systemd[1]: sidekiq-1.service: Unit entered failed state.
Apr  6 13:21:17 background-2 systemd[1]: sidekiq-1.service: Failed with result 'core-dump'.
Apr  6 13:21:18 background-2 systemd[1]: sidekiq-1.service: Service hold-off time over, scheduling restart.
Apr  6 13:21:18 background-2 systemd[1]: Stopped sidekiq.
Apr  6 13:21:18 background-2 systemd[1]: Starting sidekiq...
Apr  6 13:21:19 background-2 sidekiq[22838]: 2020-04-06T13:21:19.459Z pid=22838 tid=8o0g6 INFO: Enabling systemd notification integration
Apr  6 13:21:19 background-2 sidekiq[22838]: 2020-04-06T13:21:19.463Z pid=22838 tid=8o0g6 INFO: Pinging systemd watchdog every 2.5 sec
```

restored to `Type=simple` and everything works nicely again

**Comment by mperham** [comment]
Does it help if you bump up the watchdog timer to 30 seconds?

**Comment by mperham** [comment]
You can also just comment out the watchdog timer if it is making things worse.

**Comment by lizdeika** [comment]
I have just made it `Type=simple` and commented watchdog timer, can not do tests in production environment :|

**Comment by mperham** [comment]
Hopefully you can debug in a staging environment or Vagrant.
