### ISSUE TITLE
Stuck "stopping" state of process

### ISSUE THREAD

**Issue by benone** [mperham/sidekiq#4523]
- Ruby version: **ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]**
- Sidekiq / Pro / Enterprise version(s): **6.0.6**
- sidekiq.yml **is blank**

Hi! Here is my sidekiq.service config:

```
[Unit]
Description=sidekiq
After=syslog.target network.target redis-server.service

[Service]
User=deploy
Group=deploy
UMask=0002

Type=notify
WatchdogSec=5

WorkingDirectory=/var/www/app/current
ExecStart=/home/deploy/.rbenv/shims/bundle exec sidekiq -e production -C /var/www/app/current/config/sidekiq.yml
ExecReload=/bin/kill -TSTP $MAINPID

Environment=MALLOC_ARENA_MAX=2

RestartSec=1
Restart=on-failure

StandardOutput=/var/www/app/shared/log/sidekiq.log
StandardError=/var/www/app/shared/log/sidekiq_error.log
# SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target


```

when I run
`sudo systemctl reload sidekiq`

I have these logs:
```

● sidekiq.service - sidekiq
   Loaded: loaded (/var/www/app/current/other/configs/sidekiq.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-08 20:18:06 MSK; 13min ago
  Process: 557 ExecReload=/bin/kill -TSTP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 477 (bundle)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/sidekiq.service
           └─477 sidekiq 6.0.6 app [0 of 10 busy] stopping

...
Apr 08 20:18:19 app systemd[1]: Reloading sidekiq.
Apr 08 20:18:19 app systemd[1]: Reloaded sidekiq.
Apr 08 20:18:19 app bundle[477]: 2020-04-08T17:18:19.212Z pid=477 tid=8kh INFO: Received TSTP, no longer accepting new work
Apr 08 20:18:19 app bundle[477]: 2020-04-08T17:18:19.212Z pid=477 tid=8kh INFO: Terminating quiet workers
Apr 08 20:18:19 app bundle[477]: 2020-04-08T17:18:19.212Z pid=477 tid=49md INFO: Scheduler exiting...

```

and

`sidekiq 6.0.6 app [0 of 10 busy] stopping`

stuck forever...

**Comment by mperham** [comment]
A quiet process does not pull new jobs to work on but it does not stop.  You need to actually call `systemctl stop sidekiq`.

**Comment by thomasdarde** [comment]
@benone did you resolve your issue ? 
It hasn't be clear for me at this stage, my target is to call " systemctl reload sidekiq" via capistrano after a deploy for Sidekiq to be loaded with the latest app context

**Comment by mperham** [comment]
Ok, everybody, please **erase** "reload" from your mind. `systemctl reload` does not do what you think it does.

There are only two actions you can take with a running Sidekiq process:

* quiet - finishes current working jobs, does not fetch any more jobs
* stop - shut down the process and exit

To quiet: `systemctl kill -s TSTP sidekiq`
To stop: `systemctl stop sidekiq`
To "reload" your app after a deploy: `systemctl restart sidekiq`
