### ISSUE TITLE
Cancelled sidekiq jobs are running

### ISSUE THREAD

**Issue by kirantpatil** [mperham/sidekiq#4524]
Ruby version: ruby 2.4.4

Sidekiq  version(s): Sidekiq 5.2.7

I tried to schedule the sidekiq job using Active job and tried to cancel and but it executes and sends sms in my case. 

Please find the below code executed from rails console in development mode.

[31] pry(main)> job1 = SendCrendentialJob.set(wait: 5.minutes).perform_later("kirantpatil@gmail.com","password1","New password Sir")
Enqueued SendCrendentialJob (Job ID: d4f85435-1b49-4675-baaf-1080cb72070a) to Sidekiq(mailers) at 2020-04-09 07:03:24 UTC with arguments: "kirantpatil@gmail.com", "password1", "New password Sir"
=> #<SendCrendentialJob:0x000055d69c0c6458
 @arguments=["kirantpatil@gmail.com", "password1", "New password Sir"],
 @executions=0,
 @job_id="d4f85435-1b49-4675-baaf-1080cb72070a",
 @priority=nil,
 @provider_job_id="76ee70bdaff96757cceea88b",
 @queue_name="mailers",
 @scheduled_at=1586415804.2576973>

[33] pry(main)> jid1 = job1.provider_job_id
=> "76ee70bdaff96757cceea88b"

[34] pry(main)> Sidekiq.redis {|c| c.exists("cancelled-#{jid1}") }
=> false

[35] pry(main)> Sidekiq.redis {|c| c.setex("cancelled-#{jid1}", 86400, 1) }
=> "OK"

[36] pry(main)> Sidekiq.redis {|c| c.exists("cancelled-#{jid1}") }
=> true

Please let me know how to resolve this issue.

Thanks.

**Comment by mperham** [comment]
You set a flag in Redis. Show me the code in your job that checks for the flag.

**Comment by kirantpatil** [comment]
Sir, I am not running any other code that checks the flag. May I know where can I find it ?
I followed this link only https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job.

**Comment by mperham** [comment]
`return if cancelled?` is what I speak of.  That's what "cancels" the running job.

**Comment by kirantpatil** [comment]
So far I was running it from rails console. I will run the code and verify it.

**Comment by masroorhussainv** [comment]
is this cancellation intended only for the **non-running/non-busy** jobs? I want to terminate a running job. 
Tried [this](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job) as per the FAQs, but it does not seem to work for running jobs at least. 

@mperham could you please advise?
