### ISSUE TITLE
Programmatic Sidekiq worker queue latency checks

### ISSUE THREAD

**Issue by kaustavha** [mperham/sidekiq#4526]
Ruby version: 2.4.7
Sidekiq / Pro / Enterprise version(s): sidekiq 5.2.5 , ent i think

Less of a bug, more of a question. 
Is there a way to check for sidekiq queue latency and job count thresholds in a easy programmable way within the workers? 
like `sidekiq_options unique_for: time`  
but `sidekiq_options within_worker_threshold: xx`

Currently best thing ive come up with is a latency check using whats in the sidekiq docs before we run scripts that may enqueue large numbers of workers

**Comment by mperham** [comment]
I don’t understand.

**Comment by kaustavha** [comment]
Sorry let me try to rephrase. 

So when im writing a sidekiq worker, i can add a line to make sure it is unique. So the worker will not enqueue if another with its args exists in sidekiq. 
`sidekiq_options unique_for: 10.minutes` 

But in an environment with many workers of different types, is there a mechanism to prevent a worker from queueing and scheduling for execution if the queues are at capacity/arbitrary limits? 

E.g. in an environment where jobs automatically get queued and are also sometimes manually queue we always want the latency of the high queue to be less than 10secs. 
Is there a way to write a worker so that it would not enqueue itself if the latency was greater than 10secs on the high queue? Perhaps similar to the unique_for option

**Comment by mperham** [comment]
There’s nothing like that out of the box; there are APIs to get that information but each time will require a round-trip to Redis, you would add significant overhead to each push but the unique feature adds approximately the same amount of overhead.

**Comment by kaustavha** [comment]
Would this be a welcome addition to sidekiq as a small feature?
or better shared in a small util gem outside of sidekiq since its possibly a rare case?

**Comment by mperham** [comment]
I think it would work better as a third-party Gem for now.

**Comment by kaustavha** [comment]
Thanks! 
Really appreciate you taking the time to reply.
Closed.
