### ISSUE TITLE
Incorrect Sidekiq logs. Log messages belong to incorrect jobs

### ISSUE THREAD

**Issue by estebanbouza** [mperham/sidekiq#4527]
Ruby version: 2.6.5
Sidekiq 6.0.4
Rails version: 6.1 beta

**Environment**

- RoR application running Sidekiq without major issues for the last ~2 years
- Running sidekiq as `bundle exec sidekiq -c 25 -q default,2 -q lowpri,1 -q hipri,3 -q mailer,1 -q crawler,1 -q active_storage_purge,1 -q active_storage_analysis,1`
- Running 2x sidekiqs as 2 independent k8s containers (50 threads total)

**Initializer**

```ruby
Sidekiq::Extensions.enable_delay!
redis_conf = 'config/redis-sidekiq.yml'
Sidekiq.configure_server do |config|
  config.redis = { url: YAML.load(ERB.new(File.read(redis_conf)).result)[Rails.env]['url'] }
end
Sidekiq.configure_client do |config|
  config.redis = { url: YAML.load(ERB.new(File.read(redis_conf)).result)[Rails.env]['url'] }
end

schedule_conf = 'config/sidekiq-schedule.yml'
if File.exist?(schedule_conf) && Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_conf)
end
```

**Issue**
Since recently, when adding 2 or more ActiveJobs into sidekiq, the logs mix the ActiveJob UUID and ActiveJob class name. For example, if I did the following

```ruby
AliceJob.perform_later
BobJob.perform_later
```
Then the logs show a mix like

```
[ActiveJob] [AliceJob] [2c5ea055-93af-48e9-9ee0-7e08cf46de71] Doing Job Alice step 1
[ActiveJob] [AliceJob] [2c5ea055-93af-48e9-9ee0-7e08cf46de71] Doing Job Bob first task
[ActiveJob] [AliceJob] [2c5ea055-93af-48e9-9ee0-7e08cf46de71] Doing Job Bob second task
[ActiveJob] [AliceJob] [2c5ea055-93af-48e9-9ee0-7e08cf46de71] Performed BobJob in xxx
```
While the expected output would be
```
[ActiveJob] [AliceJob] [2c5ea055-93af-48e9-9ee0-7e08cf46de71] Doing Job Alice step 1
[ActiveJob] [BobJob] [b509c145-5dc8-42ab-8f4a-b06d44c014b3] Doing Job Bob first task
[ActiveJob] [BobJob] [b509c145-5dc8-42ab-8f4a-b06d44c014b3] Doing Job Bob second task
[ActiveJob] [BobJob] [b509c145-5dc8-42ab-8f4a-b06d44c014b3] Performed BobJob in xxx
```

Happens only sometimes. This looks like a threading issue, but I haven't been successful to diagnose it. Suspected components are a Sidekiq update from 5.x to 6, and the use of Rails 6.1 beta. 
Any clue on what can be going on?

**Comment by mperham** [comment]
I don't support Rails beta (I don't mind bug reports but beta software has bugs by definition) but if you can reproduce this on a released version of Rails, I'd be happy to help.
