### ISSUE TITLE
Job is not performing from rails

### ISSUE THREAD

**Issue by giovapanasiti** [mperham/sidekiq#4534]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s): standard version

Initializer:
```ruby
Sidekiq.configure_server do |config|
  config.redis = {url: 'redis://localhost:6379/0', network_timeout: 5}
end

Sidekiq.configure_client do |config|
  config.redis = {url: 'redis://localhost:6379/0', network_timeout: 5}
end
```

When my model launch the job (on an `after_create` hook) i get this message in console:
```
[ccef5965-b416-4f1c-9c6a-bef11435b597] [ActiveJob] Enqueued JobName (Job ID: 5e738e5c-4ab1-4f2d-a7a1-246a5ff865c6) to Sidekiq(default) with arguments: "urgent", [1, 2, 5, 7, 23]
```

I wait but the job is never executed. If I kill the rails process and run `sidekiq -C config/sidekiq.yml` all the quequed jobs run altogether.

What can i do for it?

**Comment by mperham** [comment]
You have to run a Sidekiq process if you want your jobs to execute.

**Comment by giovapanasiti** [comment]
Just for future readers I managed to make it working with a procfile as follow:

```
web: bundle exec rails server -p $PORT
jobs: bundle exec sidekiq -c 2
```

Just how mperham said it needed a sidekiq process running (OBVIOUSLY)
