### ISSUE TITLE
Lockable Job?

### ISSUE THREAD

**Issue by huguesbr** [mperham/sidekiq#4537]
Hey,

I'm not sure if any locking mechanism exists (beside Job dependency).

So I've created `Sidekiq::LockableJob`, any feedback appreciated ^^

https://github.com/huguesbr/sidekiq_lockable_job

**Comment by mperham** [comment]
This is also available in Enterprise's unique job feature with the `unique_until: :success` option.

**Comment by huguesbr** [comment]
Oh great! Thx 👍
