### ISSUE TITLE
Sidekiq 6.0.2 stats error

### ISSUE THREAD

**Issue by gretch** [mperham/sidekiq#4538]
Ruby version:
   Sidekiq: 6.0.2

Sidekiq statistics is no longer working when upgrading from sidekiq 6.0.1 to sidekiq: 6.0.2.

sidekiq 6.0.1 (working fine):
stats = Sidekiq::Stats.new
=> #<Sidekiq::Stats:0x00007fdf2d49ae30

sidekiq 6.0.2 (error):
stats = Sidekiq::Stats.new
NoMethodError: undefined method `each' for nil:NilClass
from .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/descriptive_statistics-2.5.1/lib/descriptive_statistics/support/convert.rb:37:in `to_array'

**Comment by gretch** [comment]
Closing this issue. This seems to be an Activesupport issue and not Sidekiq.
in stats api [].sum is called

Error thrown  when calling [].sum
NoMethodError: undefined method `each' for nil:NilClass

**Comment by vishal-bacancy** [comment]
@gretch how you resolved it?

**Comment by blk0** [comment]
same issue here. how do we solve this ?

**Comment by gretch** [comment]
@vishal-bacancy @blk0 This is the issue https://github.com/rails/rails/issues/24796.

I fix it using the following:
sum is added in 6.0.2 -> mperham/sidekiq@v6.0.1...v6.0.2
sum issue with descriptive_statistics -> thirtysixthspan/descriptive_statistics#44
