### ISSUE TITLE
Can sidekiq middlewares yield more than once?

### ISSUE THREAD

**Issue by satyanash** [mperham/sidekiq#4539]
Ruby version: `jruby 9.2.6.0 (2.5.3)`
Sidekiq / Pro / Enterprise version(s): Sidekiq Enterprise `sidekiq (~> 5.0.0)`

We have a use case, where we would like to run a job twice with tweaked job arguments.
Should a sidekiq middleware `yield` more than once or is that not a recommended approach?
Assuming the app state is built to handle this, would sidekiq work fine?
Would it count as a single job execution or multiple job executions?

**Comment by mperham** [comment]
That wouldn’t be supported, there are several features that will break and things that will go wrong if you yield multiple times. For example a batch job execution could be counted multiple times.
