### ISSUE TITLE
enterprise.contribsys.com is down

### ISSUE THREAD

**Issue by we4tech** [mperham/sidekiq#4540]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 

Please include your initializer and any error message with the full backtrace.

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Thank you, I've swapped DNS to a new server.

**Comment by we4tech** [comment]
Cool thanks

**Comment by we4tech** [comment]
hi @mperham It looks like earlier credentials are not working. Also, billing.contribsys.com is timing out.

**Comment by mperham** [comment]
https://twitter.com/getajobmike/status/1252664286674968577

**Comment by mperham** [comment]
If your credentials are not working, please email me with your account details so I can debug.

**Comment by aleksandrlat** [comment]
@mperham having this error when `bundle install`
```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://enterprise.contribsys.com/
```

**Comment by mperham** [comment]
e.c.c works fine for me and appears to be up. Bundler 404s are normal as e.c.c does not provide Bundler API endpoints, only plain old rubygems data.

**Comment by aleksandrlat** [comment]
@mperham sorry but I need more help please.

I can ping and trace route `enterprise.contribsys.com`. It resolves to 159.65.69.185 ip

But it is not available via http or https. 

`bundle install` worked just fine couple of hours ago. And it just stopped to work with this error without any changes on my side.

> Bundler 404s are normal as e.c.c does not provide Bundler API endpoints, only plain old rubygems data.

Sorry I'm not sure what this means. Could you please refer to some docs?

**Comment by aleksandrlat** [comment]
@mperham I have this in our Gemfile:
```
source 'https://enterprise.contribsys.com/' do
  gem 'sidekiq-ent', '~> 2.0.1'
  gem 'sidekiq-pro', '~> 5.0.1'
end
```

And I set `bundle config enterprise.contribsys.com $BUNDLE_ENTERPRISE__CONTRIBSYS__COM`

Should this continue to work? Should I change something now?

**Comment by mperham** [comment]
License and credential issues should be resolved privately.  Please contact me by email with your account info.

**Comment by Venkatabulusu** [comment]
@mperham
Gemfile
 source 'https://enterprise.contribsys.com' do
  gem 'sidekiq-ent'
  gem 'sidekiq-pro'
end
bundle config enterprise.contribsys.com $BUNDLE_ENTERPRISE__CONTRIBSYS__COM

Pipeline is failing due to "Bad username or password for enterprise.contribsys.com." Where as everything worked a 3 days back. Also there has been no change in credentials at all.

I dont know if enterprise.contribsys.com is down.... Need some help ASAP

**Comment by mperham** [comment]
Please e-mail for license support, I don’t know who you are.

**Comment by Venkatabulusu** [comment]
> Please e-mail for license support, I don’t know who you are.

Could you please help me with the email for license support?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Commercial-Support#priority-support

**Comment by Venkatabulusu** [comment]
Thanks you so much. @mperham
