### ISSUE TITLE
Sidekiq Swarm tries to restart the app forever on bad deploy

### ISSUE THREAD

**Issue by sanjayprabhu** [mperham/sidekiq#4544]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.8, Pro 3.5.3.2, Enterprise 1.6.1.1

We noticed that on a bad deploys, sidekiq swarm seems to keep restarting the sidekiq processes and doesn't die. This lead to the bad deploy going live but us not having any healthy sidekiq workers.

I believe this is because our app boot takes longer than 10 seconds (the bad code change caused the process to die near the end of the bootup phase). Because it took so long, swarm thought that the processes are healthy. 

 Is it possible to make this timeout configurable? Or have a max limit on the number of restarts before swarm gives up?

**Comment by mperham** [comment]
I might be able to extend that from 10 to 60. Wouldn’t want it any longer. Alternatively we could supply an API that the app can call on successful boot to inform Swarm that the boot process is complete. Maybe we could hook into Rails if it is detected. 🤔

Your versions are a bit old, can you upgrade Pro and Ent?

**Comment by sanjayprabhu** [comment]
Setting it to 60 would work great. 

Hooking into rails loading (perhaps via the [Rails::Application#finisher](https://guides.rubyonrails.org/initialization.html#railties-lib-rails-application-rb)?) seems more foolproof, but honestly, 60s seems good enough.

Yeah, will do. Planning to upgrade to get the fix.

**Comment by mperham** [comment]
I think 60 sec is the quick and easy fix so I'll get that into the next patch release coming soon.
