### ISSUE TITLE
Ability to opt-in to unique jobs?

### ISSUE THREAD

**Issue by jcw-** [mperham/sidekiq#4546]
Ruby version: 2.5.7
Sidekiq / Pro / Enterprise version(s):
Sidekiq Pro 4.0.5 / Sidekiq Enterprise 1.8.1, commercially licensed

Similar question as https://github.com/mperham/sidekiq/issues/3947, I'd like to start using https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs in an existing codebase.

However, it looks like this behaves as "on by default with ability to opt-out", is there any way to use this feature as "off by default with ability to opt-in" as a way to introduce this to an existing code base?

Ideally I would enable this behavior per-worker...

**Comment by mperham** [comment]
The unique feature is opt in. What makes you think otherwise?

**Comment by jcw-** [comment]
Oh! I read the documentation as implying that the initializer config made it on by default, and you had to opt-out using `unique_for: false`:

> To activate the feature, enable it in your initializer

> If you really want to push a job and bypass the uniqueness check, pass false as the unique_for option

One or more of the following clarifications would have helped my past self:
- In the "Enable" section: "To activate the [`unique_for` option] ~feature~, enable it in your initializer"
- In the "Use" section, state that the default value for `unique_for` is false
- In the "Bypassing Uniqueness" section: "If you really want to push a job and bypass the uniqueness check [configured on that worker]"

**Comment by mperham** [comment]
Thank you for the suggestions!
