### ISSUE TITLE
Sidekiq css and js returning 404 in Nginx and Puma

### ISSUE THREAD

**Issue by robertochingon** [mperham/sidekiq#4547]
Hi, 

   I have a problem with the sidekiq web interface because I´m getting a 404 error while trying to get the css and js. I have read some other similar issues and solutions but, at the moment I´m not able to make it work. I need your help.

Please read this post in stackflow to see the details and please kindly let me know if you need any additional details.

**Comment by mperham** [comment]
Read the docs.

https://github.com/mperham/sidekiq/wiki/Monitoring#proxying-the-web-ui
