### ISSUE TITLE
Add a search function to sidekiq/scheduled page

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#4551]
I think it is useful if the sidekiq/scheduled page has a search function.

Search targets are:

```ruby
if params['q']
  query = params['q']
  @scheduled.select! do |entry|
    job_params(entry.item, entry.score).include?(query) ||
        relative_time(entry.at).include?(query) ||
        entry.queue.include?(query) ||
        entry.display_class.include?(query) ||
        display_args(entry.display_args).include?(query)
  end
end
```

Screenshot:

<img width="1205" alt="スクリーンショット 2020-05-04 23 49 35" src="https://user-images.githubusercontent.com/649961/80979169-f9ac1e00-8e61-11ea-9769-c4bcdd00b6d1.png">

Thanks

**Comment by mperham** [comment]
Search is already built into Sidekiq Pro. It’s called filtering.

**Comment by ts-3156** [comment]
Thanks for getting back to me so quickly!
