### ISSUE TITLE
Jobs stuck in busy after change from ruby 2.3.7 to ruby 2.5.7

### ISSUE THREAD

**Issue by jocuman** [mperham/sidekiq#4553]
Ruby version: 2.5.7
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.8
Redis version: 4.0.9

Problem:
I recently upgraded from ruby 2.3.7 to 2.5.7, using chruby (0.3.9). I have 20 threads configured, and jobs will work fine for some random time, I have seen it happening 2 minutes from start or 2 hours later, then some will get stuck in busy, and eventually fill the busy queue, and stop starting new jobs. New jobs will be enqueued until I restart sidekiq. 

As soon as I send the TSTP signal, the jobs in busy will end, and as far as I can tell with no issues. I look at the TTIN logs but I cannot figure out what the problem is.

I am attaching the TTIN info

[sidekiq-ttin-before-restart.txt](https://github.com/mperham/sidekiq/files/4577869/sidekiq-ttin-before-restart.txt)
[sidekiq-ttin-after-restart.txt](https://github.com/mperham/sidekiq/files/4577870/sidekiq-ttin-after-restart.txt)

Initializer:

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1' }
  config.average_scheduled_poll_interval = 0.5
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://127.0.0.1:6379/1' }
end

**Comment by mperham** [comment]
All of your workers are stuck in ActiveJob's logger. I don't know why.

```
2020-05-04T20:52:38.144Z 3414 TID-gnayjk9m6 WARN: Thread TID-gnb0jjv2m processor
2020-05-04T20:52:38.144Z 3414 TID-gnayjk9m6 WARN: /home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:192:in `lock'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:192:in `mon_enter'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `block in mon_synchronize'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `handle_interrupt'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `mon_synchronize'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:688:in `write'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:471:in `add'
/home/deployer/www.latinotopup.com/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:89:in `add'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:527:in `info'
/home/deployer/www.latinotopup.com/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/log_subscriber.rb:96:in `info'
```

**Comment by jocuman** [comment]
Thanks, I moved away from ActiveJob, and it happened again, but now I can see info on my code with the TTIN.

Now I have a question on the TTIN below, is it stuck also in the logger? The first line that it shows of my code (the last line in this paste) is a Rails.logger.info call, and before that I see the info, add and write calls from the logger. Just want to confirm if I'm looking at this correctly.

```2020-05-05T15:14:45.514Z 23072 TID-gsbdl4fdc WARN: Thread TID-ovu41vtgk processor
2020-05-05T15:14:45.515Z 23072 TID-gsbdl4fdc WARN: /home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:192:in `lock'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:192:in `mon_enter'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `block in mon_synchronize'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `handle_interrupt'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:233:in `mon_synchronize'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:688:in `write'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:471:in `add'
/home/deployer/www.latinotopup.com/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/logger.rb:89:in `add'
/home/deployer/.rubies/ruby-2.5.7/lib/ruby/2.5.0/logger.rb:527:in `info'
/home/deployer/www.latinotopup.com/releases/20200504235658/app/lib/provider_request_recargator.rb:103:in `prepare_order'```

**Comment by mperham** [comment]
Yep, same issue.  You're having some sort of problem with logging but I
can't tell anything more than that.

**Comment by jocuman** [comment]
Well, just to follow up with the solution.

It was an old issue already brought up and discussed here.
I was using Timeout.timeout which apparently (with ruby 2.5.7) still brings issues to the table.

The solution was to remove this Timeout.timeout and replace with the proper code in each case.
Mostly using open_timeout and read_timeout in RestClient as suggested in the following references that helped me with this.

[nesquena/backburner/issues/86](https://github.com/nesquena/backburner/issues/86)
[mperham/sidekiq/issues/862](https://github.com/mperham/sidekiq/issues/862#event-245331424)
