### ISSUE TITLE
Follow-up: Fail job and retry without raising error

### ISSUE THREAD

**Issue by zinosama** [mperham/sidekiq#4558]
Ruby version:
Pro 3.7.1

Hello @mperham  (and others), I have a follow-up question on https://github.com/mperham/sidekiq/issues/3689. Not sure if I should re-open a closed issue or open a new one (please feel free to lmk if I'm doing it wrong). Also, please feel free to lmk if you'd rather not have this type of questions as Github issues (happy to reopen this somewhere else).

The recommended solution from 2017 was to configure error monitoring tools (we use Sentry) to ignore the exceptions. However, **for the various timeout errors, we don't care about the initial ones but we do care if the error persists**. Since timeout handling is likely prevalent to many of the sidekiq loyalists, I wonder if you can share some thoughts on the best practices here.

Here's an example of what I want to do
```ruby
class CallSomeAPIWorker
  include Sidekiq::Worker

  # Retry in the next 10-15 minutes 
  # based on the default schedule
  sidekiq_options retry: 6

  def perform(...)
    client = SomeAPIClient.new(timeout: 3, open_timeout: 3)
    client.call_some_method(...)
  rescue Faraday::ConnectionFailed, Faraday::TimeoutError => e
    logger.error('timeout', { ... })
    # I don't care about these exceptions as long as the job
    # has retries left. But I do want to be notified via Sentry 
    # if there's no more retries left.
  end
end
 ```

Here's one approach that I can think of based on my understanding of how sidekiq works. Please let me know if you find this to be a good pattern:
```ruby
# Configure Sentry to ignore this exception, 
# but not the various timeout exceptions
class RetriableTimeoutError < StandardError
  attr_reader :original_exception
  def initialize(original_exception)
    @original_exception = original_exception
    super
  end
end

class CallSomeAPIWorker
  include Sidekiq::Worker

  # Retry in the next 10-15 minutes 
  # based on the default schedule
  sidekiq_options retry: 6

  sidekiq_retries_exhausted do |msg, ex|
    logger.error('timeout_retry_exhausted', { ... })
    Raven.capture_exception(ex.original_exception) if ex.is_a?(RetriableTimeoutError) 
  end

  def perform(...)
    client = SomeAPIClient.new(timeout: 3, open_timeout: 3)
    client.call_some_method(...)
  rescue Faraday::ConnectionFailed, Faraday::TimeoutError => e
    logger.error('timeout', { ... })
    # This exception will trigger a retry but will be discarded 
    # by the Sentry client.
    raise RetriableTimeoutError.new
  end
end
```

Thanks a lot for your time and for building Sidekiq!

**Comment by mperham** [comment]
I think that's fine. Sidekiq, as a general purpose tool with general purpose patterns, can't account for every edge case.  There's also death handlers that you could also use which would allow your code to work across many Worker types.

https://github.com/mperham/sidekiq/wiki/Error-Handling#death-notification

**Comment by zinosama** [comment]
Thank you.

**Comment by moofkit** [comment]
@zinosama Hey, I'm sorry to mention you after 4 years, but I've created the sidekiq plugin to solve exactly this kind of problem https://github.com/moofkit/sidekiq-rescue

With this plugin, it is possible to retry some specific errors with a custom strategy:
```
class CallSomeAPIJob
  include Sidekiq::Job
  include Sidekiq::Rescue::Dsl

  # Try exactly 6 times with a plain 60 seconds delay within the same queue
  # After the limit has been reached it will be handled by default Sidekiq retry mechanism
  sidekiq_rescue Faraday::ConnectionFailed, Faraday::TimeoutError, limit: 6, delay: 60

  def perform(...)
    client = SomeAPIClient.new(timeout: 3, open_timeout: 3)
    client.call_some_method(...)
  end
end
```

I hope this is helpful to you when you head to this problem again.
