### ISSUE TITLE
Sidekiq::Testing does not decrypt secret_bag passed to Worker perform when using Ent Encryption

### ISSUE THREAD

**Issue by darronschall** [mperham/sidekiq#4564]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0.7 / 5.0.1 / 2.0.1

Please include your initializer and any error message with the full backtrace.

```
# Disabled in testing per advice at https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#enable
Sidekiq::Enterprise.unique! unless Rails.env.test?

Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  # this block should return the key for the version N
  #
  # every time you need to rotate the crypto key, you should bump
  # the active_version. this block should always return the key for
  # the given version.

  Figaro.env.send("sidekiq_encryption_key_v#{version}".to_sym)
end
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

We are using Enterprise Encryption per https://github.com/mperham/sidekiq/wiki/Ent-Encryption#configure-your-private-workers

We've noticed that when writing tests and using either `Sidekiq::Testing.inline!` or `.drain` to run the queued jobs, the `secret_bag` that comes in as the third argument is not being decrypted. It's being passed as a Base64-encoded string.

We have a workaround that we implemented to decrypt the content so the worker performs as we expect:

```ruby
secret_bag = decrypt_if_necessary(secret_bag)
```

```ruby
def decrypt_if_necessary(secret_bag)
  return secret_bag if secret_bag.is_a? Hash

  sidekiq_decrypt(Base64.urlsafe_decode64(secret_bag))
end

def sidekiq_decrypt(blob)
  crypto = Sidekiq::Enterprise::Crypto::Default.new do |version|
    Figaro.env.send("sidekiq_encryption_key_v#{version}".to_sym)
  end
  crypto.decrypt(blob)
end
```

**Comment by mperham** [comment]
Correct, just add `unless Rails.env.testing?` to the end of the config block.

**Comment by pusewicz** [comment]
To clarify, this means that:

```ruby
Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  my_secret_goes_here
end
```

Becomes:

```ruby
Sidekiq::Enterprise::Crypto.enable(active_version: 1) do |version|
  my_secret_goes_here
end unless Rails.env.test?
```

Effectively skipping the encryption in the test environment.
