### ISSUE TITLE
Upgrading to sidekiq 6.0 not able to find sidekiq.pid

### ISSUE THREAD

**Issue by anson2590** [mperham/sidekiq#4565]
Ruby version: 2.6.3
Sidekiq version: 6.0.6

I recently upgraded sidekiq from 5.0 to 6.0, after upgrading service is failing to stop sidekiq because its not able to find sidekiq.pid, 

can you please help me is there any alternative way to get pid.

<img width="773" alt="Screenshot 2020-05-15 at 4 08 07 PM" src="https://user-images.githubusercontent.com/30189967/82041462-da18bf00-96c5-11ea-9f5c-c307b5e2f64c.png">

**Comment by seuros** [comment]
Sidekiq 6 dont use a pid file anymore. 
You need to use something like Systemd or Upstart to control the process. 
Please read https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md
