### ISSUE TITLE
Logger being monkey patch is very unexpected

### ISSUE THREAD

**Issue by AlexRiedler** [mperham/sidekiq#4570]
Sidekiq / Pro / Ent Version: 6.0.7 / 5.0.1 / 2.0.1

https://github.com/mperham/sidekiq/blob/fe2915ab8b5485f744fc6a940aa2913b5bbbbae5/lib/sidekiq.rb#L209

This line is super unexpected, as it messes with the any custom logger implementations (e.g. the Logstash logger). Is there a way this can be changed to be a wrapping delegator instead? or is there a good reason for backwards compat. it is like this? (verifying before I do the work)

**Comment by mperham** [comment]
Everyone expects Sidekiq.logger to be a Logger. Delegation is fragile in my experience. That said, happy to review any PRs.
