### ISSUE TITLE
Time zone awareness for Sidekiq Enterprise Limiter clock

### ISSUE THREAD

**Issue by christos** [mperham/sidekiq#4571]
I am trying to use  `Sidekiq::Limiter.bucket` to limit the delivery of a certain email we sent to our users to once a day.

```ruby
Sidekiq::Limiter.bucket("email-user-${@user.id}", 1, :day)
```

The email worker is triggered whenever the user starts a new session with the API, and we want to send the email on the first of those sessions in any given day.

The problem that I came across is that `Sidekiq::Limiter.bucket` builds its buckets using   `Time.now.strftime("%F)`. 

Since `Time.now` is in the server's timezone it often puts  email deliveries for users across different timezones in the same bucket. So some users will get two emails a day because their timezone is offset by say 12 hours from UTC (the server's).

I initially tried to fix this by creating buckets whose name includes the timezone-aware date for the user:

```ruby
date = Time.new.in_time_zone(@user.time_zone).strftime("%F")
Sidekiq::Limiter.bucket("email-user-${@user.id}-#{date}", 1, :day)
```

That works, but it feels inefficient because I am basically re-implementing the bucketing logic that the limiter already has (as well as creating more buckets than I need?!)

So I was wondering if time zone awareness was something you had considered implementing. Or should I just continue using my time zone aware bucket names?

I could see this working in one of two ways:

```ruby
# Assumes someone has loaded ActiveSupport so the limiter 
# can do timezone math (would only work inside a Rails app)
Sidekiq::Limiter.bucket("email-user-${@user.id}, 1, :day, time_zone: @user.time_zone)
```

```ruby
clock = -> { Time.new.in_time_zone(@user.time_zone) }
Sidekiq::Limiter.bucket("email-user-${@user.id}, 1, :day, clock: clock)
```

**Comment by mperham** [comment]
Thanks, interesting issue.

Have you considered using the Redis API? You just want a flag that expires after 86400 seconds, that's easy.  Something like:

```ruby
send_it = Sidekiq.redis {|c| c.set("email-user-#{@user.id}", 1, nx: true, ex: 86400)
send_email(@user) if send_it
```

**Comment by mperham** [comment]
I don't think it's possible to use Sidekiq's Limiter to be timezone aware, and I'm not sure I want it to  be. I think you were going down the right path. If you want to make a timezone-aware daily flag, I think you should mix your code and my code, like so:

```ruby
date = Time.new.in_time_zone(@user.time_zone).strftime("%F")
send_it = Sidekiq.redis {|c| c.set("emailuser-#{@user.id}-#{date}", 1, nx: true, ex: 86400)
```

**Comment by christos** [comment]
Going directly to Redis was my first take on this problem too, but then I thought using the `Sidekiq::Limiter` would have been somehow more reliable. 

I guess if I don't need retries at the middleware level or the pauses for the short duration bucketing, then it doesn't give me anything extra.

I'll take the Redis path. Thanks for your insights Mike.
