### ISSUE TITLE
Question Re: Mixing Queue Sequential Priority & Queue Weight

### ISSUE THREAD

**Issue by dianacamacho** [mperham/sidekiq#4577]
First, thank you for all the work on Sidekiq! 

I was wondering if it was possible to mix the sequential listing of queues with weights for secondary queues. The [wiki](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues) mentions sequential queues and queue weights in separate sections, but no mention of combining the two. 

For example, if you have 3 queues: `critical`, `intermediate`, and `low`, is it possible to have a config such as:

```
:queues:
  - critical
  - [intermediate, 3]
  - [low, 1]
```

Where no `intermediate` or `low` jobs would run unless the `critical` queue was empty (making sure `critical` jobs always run first). And once empty, any `intermediate` jobs would be checked for 3x as often as `low` jobs. I'm not sure if the syntax above would result in an implicit weight of 1 for the `critical` queue, making it lose its sequential priority.

**Comment by mperham** [comment]
Unfortunately not. In your example, `critical` would get a weight of 1.

**Comment by johnnyshields** [comment]
@mperham queue priorities (not weights) must be an often requested feature. Can you give any consideration to adding it? DelayedJob supports priorities, and if Sidekiq also had it, it would be a lot easier for my company to migrate.

I think it would probably be fine if the user had to choose between "weighted mode" and "priority mode"... there's not so much value in mixing the two.

**Comment by mperham** [comment]
@johnnyshields Notice how Resque doesn't have support for priorities either? The DBMS (DJ) and Redis (Sidekiq, Resque) greatly influence the features we can provide and Redis does not provide this functionality.

**Comment by johnnyshields** [comment]
I'm aware of that. I'm surprised there isn't a way to do it with sorted sets / scoring. Hence why I suggested the either/or option, you might have to use a different base set type in order to achieve it (and hence you life with that for the lifetime of your deploy).

**Comment by johnnyshields** [comment]
Hypothetically (again I really know nothing here) but if you did it with a sorted set, you wouldn't have to do N queries for N queues like you do with weighting. Just thinking out load.

**Comment by mperham** [comment]
The Fetch API is there if you want to build your own fetch and there are 3rd party gems which do so.  I provide what I feel is the best trade off between performance and features but YMMV.

Sidekiq does not make N queries for N queues, that's one advantage of BRPOP.

**Comment by johnnyshields** [comment]
Maybe this page is out-of-date: https://github.com/mperham/sidekiq/wiki/Advanced-Options

> M Sidekiq Pro processes polling N queues means O(M*N) operations per second slamming Redis.

**Comment by mperham** [comment]
I said Sidekiq, not Sidekiq Pro. super_fetch does not use BRPOP because it is not reliable.
