### ISSUE TITLE
Sidekiq Pro/Ent and Sentinel support

### ISSUE THREAD

**Issue by raivil** [mperham/sidekiq#4580]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s):  6.0.5 / 5.0.1/ 2.0.1 

Hi Mike,

We're considering using sentinel for high availability and automatic failover and I was wondering about your opinion on it. 
We use [super_fetch](https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server#super_fetch) and according to the documentation it uses [rpoplpush](https://redis.io/commands/rpoplpush) which is atomic.

Do you see any cons in using Sidekiq with Sentinel? 
With reliable push and Sentinel, do you think there's a chance of losing a job? What is the possible risk?

Thank you.
Best Regards.

**Comment by mperham** [comment]
Sentinel should work fine. No known issues.
