### ISSUE TITLE
First job with infinite loop blocks other jobs

### ISSUE THREAD

**Issue by sudarshanbasumatary** [mperham/sidekiq#4584]
When starting a Sidekiq job (_Jinf_) having infinite while loop, it blocks other workers in different queues, if other jobs are started after _Jinf_ has started!

Interestingly, this is not consistent. When another job is scheduled from inside the while loop, _Jinf_ is not blocking anymore! 
Also, if the job _Jinf_ is started after some other job has finished, it doesn't block other queues.

Ruby version: **2.5.7p206**
Sidekiq / Pro / Enterprise version(s): **Sidekiq 5.2.8**
Tested on both Sidekiq 5.2.8 and 5.0.5

```ruby
class InfiniteWorker
    include Sidekiq::Worker
    sidekiq_options queue: :forever_queue

    def perform(loop=true, options={})
        i = 0
        while loop
            sleep(5)
            i += 1
            puts Time.now
            TestWorker.perform_async('test') if i == 3
        end
    end
end
```

```ruby
class TestWorker
    include Sidekiq::Worker
    
    def perform(type, options={})
        puts Time.now
    end
end
```

sidekiq.yml:
```yaml
:verbose: false
:concurrency: 10
:queues:
  - default
  - forever_queue
:limits:
  forever_queue: 1
```

In the screenshot, job `d0b04ebee9dfc874cf9223f3` is not done until  _Jinf_(`841163fccf61ef1c05f90660`) enqueued the job `c89807ed261817394ee78f4e` from `InfiniteWorker:12`

<img width="1440" alt="Screenshot 2020-05-31 at 10 18 09 PM" src="https://user-images.githubusercontent.com/8739597/83358043-4403ba80-a38e-11ea-84df-9fc38e98c625.png">

**Comment by mperham** [comment]
A job is a discrete chunk of work that ends. That’s not a job Sidekiq can support.
