### ISSUE TITLE
Docker - Sidekiq stale state

### ISSUE THREAD

**Issue by marcoroganovic** [mperham/sidekiq#4592]
Ruby version: 2.6.3
Sidekiq / Pro / Enterprise version(s):  6.0.2

Please include your initializer and any error message with the full backtrace.

My problem is that Sidekiq constantly gets stale, I'm using docker-compose to boot up the whole project, and Sidekiq is one of the integral parts for the app, and this really slows down development. I need to restart Docker, rebuild images, etc, etc, and just sometimes it fixes the thing. Most of the time jobs are in the busy state, even though there is plenty of resources available - Sidekiq does not process them. The worst thing is that there aren't any logs present. It just says Job started.

Has anyone encountered a similar issue?

Are you using an old version?
No.

Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes.

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Please reopen this issue if you get some data we can use to debug.
