### ISSUE TITLE
Hide showing Redis warnings in Sidekiq

### ISSUE THREAD

**Issue by nikolacojcic99** [mperham/sidekiq#4595]
I am seeing this in Sidekiq from today.

`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/Users/admin/.rvm/gems/ruby-2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')

Is there any way to disable showing this?

**Comment by mperham** [comment]
#4591

**Comment by MoacirPetry** [comment]
@nikolacojcic99 if you are running a Ruby on Rails app, you can create this file **config/initializers/redis.rb** e put this content: `Redis.exists_returns_integer = true`
