### ISSUE TITLE
Prevent Batch from Finishing

### ISSUE THREAD

**Issue by aaldrich** [mperham/sidekiq#4596]
I've got a scenario where I need to create a batch and return the bid so that it can be polled for status updates. The issue is that I don't know how many child jobs there will be until a later time. The workflow looks something like this:

1. Request is made to start process
2. Batch is created and bid is returned
3. A request is made to a third party service to start getting the data we need and will be returned in via Webhook callbacks in batches.
4. We will start receiving callbacks and each one would be a child job associated to the original batch
5. Once they are all completed we would want to fire off success on the parent batch to update a completed timestamp in the database

In Step 5 I would have the data I need to know if it is the final child and could "complete" the batch if that helps.

You can see in this workflow, I won't really know how many child jobs there will be until I've received them. I can't create an empty batch from the beginning so I've created a Worker and associated it to the parent batch just to get things going but that pretty much immediately fires off the "success" callback.

I tried passing the parent bid down and reopening the parent batch in Step 4 but I keep getting "Batch {bid} has finished, you cannot modify it anymore". According to https://github.com/mperham/sidekiq/issues/3423#issuecomment-293783464 you are supposed to be able to open a batch in a callback but that doesn't work.

I can't find a lot of documentation on how to understand how to reopen or delay the success of the parent batch, any insight would be really helpful.

**Comment by aaldrich** [comment]
I found a way to make this work but it feels kind of hacky. Before I try to open the batch I'm doing the following
`Sidekiq.redis { |r| r.hdel("b-#{parent_batch_id}", "deleted") }`

This seems to allow me to call 
`batch = Sidekiq::Batch.new(parent_batch_id)`

Add the jobs to it and when they are done the on_success fires. 

Is there any harm in doing it this way?

**Comment by mperham** [comment]
Have a state machine which represents the process. You'll kick off the batch with state = "filling", once you hit step 5, change the state to "finishing". Schedule a job **in the batch** to run in N minutes, check for the "finishing" state. Since it is a scheduled job, the batch will not finish until the scheduled job runs. The scheduled job can reschedule itself as long as necessary for the webhooks to finish (i.e. reschedule every 5 minutes, effectively polling for completion every 5 minutes). Make sense?

**Comment by aaldrich** [comment]
@mperham Thank you, that worked great and feels like a much cleaner solution.
