### ISSUE TITLE
Jobs not being picked up on my development server

### ISSUE THREAD

**Issue by samjohn** [mperham/sidekiq#4598]
I think this is an issue particular to our setup. We're using RedisToGo for redis, and it works fine on our production and staging servers. On the development server, I get no errors and the jobs queue properly. They are just never picked up and sit in the queue forever. 

Ruby version: 2.6.6-p146
Sidekiq / Pro / Enterprise version(s): 
    sidekiq (5.2.7)
    sidekiq-ent (1.8.1)
    sidekiq-failures (1.0.0)
    sidekiq-pro (4.0.5)

Please include your initializer and any error message with the full backtrace.
```
Sidekiq::Enterprise.unique! unless Rails.env.test?
Sidekiq::Extensions.enable_delay!

Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # see any crontab reference for the first argument
    # e.g. http://www.adminschoice.com/crontab-quick-reference
    mgr.register('1,11,21,31,41,51 * * * *', WritePopularCacheJob)
    mgr.register('*/2 * * * *', CheckEducatorResponsesJob)
    mgr.register('4,14,24,34,44,54 * * * *', PopulateActivityStreamJob)
    mgr.register('33 0 * * *', RemoveUnregisteredDevicesJob)
    mgr.register('33 1 * * *', PruneOldActivitiesJob)
    mgr.register('33 2 * * *', EnqueueSubscriptionChecksJob)
    mgr.register('8,18,28,38,48,58 * * * *', ElasticSearchBulkUpsertJob)
    mgr.register('*/10 * * * *', SeedTransactionReportJob)
  end
end
```

Are you using an old version?

Have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
I've seen a worrying amount of people complain about Sidekiq dead, not picking up their jobs, but not enough for it to be a MUSTFIX bug, maybe a dozen people in the last 3 months. I don't know what triggers it. You'll need to give me a lot more detail / log output or a reproduction for me to track it down.

**Comment by mperham** [comment]
I just recalled that there is a Rails 6 issue where it can deadlock Sidekiq in development.  Does it work if you use `-c 1`? See #4516
