### ISSUE TITLE
Run sidekiq inline mode in production?

### ISSUE THREAD

**Issue by mmustala** [mperham/sidekiq#4600]
Ruby version: 2.6.6
Sidekiq: 5.2.7

Hi! I need to debug my process in production environment and being able to run the jobs with inline mode from Rails console would be of great help. The wiki only talks about inline mode with testing, but would it be possible to use it in production with:

    Sidekiq::Testing.inline! do
      MyProcess.perform_async(job_id)
    end

**Comment by mperham** [comment]
Yes, this should work but I would prefer:

```ruby
MyProcess.new.perform(job_id)
```

After all, a Sidekiq job is just `new` + `perform(args)`.

**Comment by waylandhe** [comment]
Thanks @mperham. It's so obvious that I sometimes forget we can just straight up call it

**Comment by paulslaby** [comment]
Unfortunately, this method skips all middlewares. I haven't found the correct solution yet.

**Comment by jarthod** [comment]
For the record, the solution executing middlewares would probably be `MyProcess.perform_inline` (https://www.rubydoc.info/gems/sidekiq/Sidekiq/Job/ClassMethods#perform_inline-instance_method). I haven't tested it but it seems to be doing just that according to the doc.

**Comment by patodevilla** [comment]
`perform_inline` does appear to execute middlewares, the only other diff is that `MyProcess.new.perform(job_id)`
returns the method return value and `MyProcess.perform_inline` always returns `true`. To close that gap `perform_inline` could return the method return value.

https://github.com/sidekiq/sidekiq/blob/v8.0.6/lib/sidekiq/job.rb#L247
