### ISSUE TITLE
Better handling of `at` in push_bulk

### ISSUE THREAD

**Issue by BuonOmo** [mperham/sidekiq#4601]
Ruby version: X
Sidekiq version: 6.X

The current (`>= 6`) version of `Sidekiq::Client.push_bulk` accepts an `at` that could be an array of numeric timestamps. However, if the size of that array doesn't match the number of jobs, this will throw a redis error:

```ruby
    # test/test_client.rb
    it 'cannot handle at with different size' do
      at = Time.new(2020, 1, 1).to_f
      first_jid, second_jid = Sidekiq::Client.push_bulk('class' => QueuedWorker, 'args' => [[1], [2]], 'at' => [at]) # will raise +Redis::CommandError: ERR value is not a valid float+
    end
```

I'd be glad to fix this one, but there are many way to do so... Here are the solutions I had in mind:

1. raise properly an `ArgumentError` if size mismatch
2. use the last `at` item as default when at is smaller:
   ```ruby
   Sidekiq::Client.push_bulk('class' => K, 'args' => [[1], [2]], 'at' => [at])
   # would be like
   Sidekiq::Client.push_bulk('class' => K, 'args' => [[1], [2]], 'at' => [at, at])
   ```

**Comment by mperham** [comment]
2 is a non-starter. 1 is fine.

**Comment by BuonOmo** [comment]
Here it is then 🙂
