### ISSUE TITLE
Please clarify documentation on stats

### ISSUE THREAD

**Issue by rwstauner** [mperham/sidekiq#4604]
On https://github.com/mperham/sidekiq/wiki/Pro-Metrics

It mentions that "perform tracks the amount of time spent in the worker"... can you clarify the measurement?  seconds?  milliseconds?

Thanks.

**Comment by mperham** [comment]
Milliseconds, as noted here:

https://github.com/DataDog/dogstatsd-ruby/blob/master/lib/datadog/statsd.rb#L237

**Comment by rwstauner** [comment]
thanks, i didn't know what method you were using, and i'm trying to understand some discrepancies between logs and various metrics.
