### ISSUE TITLE
Multiple web backends behind Nginx load-balancer

### ISSUE THREAD

**Issue by syntruth** [mperham/sidekiq#4605]
Hello,

I have a set up with multiple servers behind a nginx load-balancer. Each server hosts several apps, each with their own Sidekiq set up.

Previously, if I needed the Web UI, I just ran Rake task on a given app that started a stand alone server on port 9494, and I was able to access it via the web backend's direct FQDN:9494.  This worked for our needs, since we rarely needed the Web UI up and accessible. And when done, would just kill the process.

This was the method that started the server.

```ruby
  def start_sidekiq_web(env)
    require 'sidekiq/web'

    Sidekiq::Web.use Rack::Session::Cookie,
                     secret: '<secret here>'

    app = Sidekiq::Web
    app.set :environment, env.to_sym
    app.set :bind, '0.0.0.0'
    app.set :port, 9494

    app.run!
  end
```

Since updating, the Web UI no longer accepts the settings above.  So, I now have them mounted under a mount point on each app, which is fine, but I have no way of forcing my browser to use a specific web backend if I want to check those queues.

Any insight on how I can manage to check each Web UI?  Either an Nginx trick or something? My Google-fu has failed me on finding a solution to this.

**Comment by seuros** [comment]
mount them in different paths, and use nginx upstream to point to the rack server.

**Comment by mperham** [comment]
Are you looking for the simplest way to run a Rack server? There’s this:

https://github.com/mperham/sidekiq/blob/master/myapp/simple.ru

**Comment by syntruth** [comment]
So, I had tried that, but was _not_ setting the host/port on the `rackup` command itself.  Did that and my temporary server is back.

All fixed up now. Thanks! I'll be closing this.
