### ISSUE TITLE
Clarity around retry blocks with Active Job

### ISSUE THREAD

**Issue by nickmealey** [mperham/sidekiq#4606]
It may be helpful to add a blurb about Active Job in the [Error Handling wiki](https://github.com/mperham/sidekiq/wiki/Error-Handling).

I was stumped when I tried something like this after reading the wiki:
```
class ExampleJob < ApplicationJob
  sidekiq_retry_in { 5 }
end

puts ExampleJob.sidekiq_retry_in
# => nil
```

I would expect `sidekiq_retry_in` to raise an exception here or to function properly when defining this method. It wasn't until I read through the [Active Job wiki](https://github.com/mperham/sidekiq/wiki/Active-Job) that made it clear that `rescue_from` is the correct approach and `sidekiq_retry_in` is ignored. I think this is particularly confusing since `sidekiq_options` works as expected.

**Comment by mperham** [comment]
Thanks for the tip. Using ActiveJob adds a whole new level of complexity to your jobs, now you have to navigate which retry features work where and which will subtly break when. I honestly don't know what to write. This is part of the reason why I don't recommend ActiveJob - Sidekiq has a ton more features and I can't guarantee which features work with AJ and which edge cases might break.
