### ISSUE TITLE
Batch callback not called if job stopped because of server stop

### ISSUE THREAD

**Issue by aclarembeau** [mperham/sidekiq#4607]
Sidekiq / Pro / Enterprise version(s):

    sidekiq (6.0.4)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    sidekiq-pro (5.0.1)
      concurrent-ruby (>= 1.0.5)
      sidekiq (>= 6.0.1)
    sidekiq-throttled (0.11.0)
      concurrent-ruby
      redis-prescription
      sidekiq

<img width="1367" alt="Capture d’écran 2020-06-24 à 15 27 29" src="https://user-images.githubusercontent.com/10834626/85565893-d3b82400-b62f-11ea-83e8-5cac83ba8714.png">
<img width="1274" alt="Capture d’écran 2020-06-24 à 15 26 36" src="https://user-images.githubusercontent.com/10834626/85565917-d7e44180-b62f-11ea-86ab-801afd5d37b4.png">

Hello Sidekiq team, 

It's been a few months we're having an annoying problem. 
From time to time, we remark that some batches are stuck, making the callbacks never complete. 

After investigation, we've remarked that it results from the following problem: 

- When a job runs 
- And the dyno running that job suddenly stops (here, stopped by Heroku) 
- The job is neither failed, neither succeeded
- So, the batch callback is never executed

Have you already heard about a similar issue? 

Best,

**Comment by mperham** [comment]
Can we see your initializer?

**Comment by mperham** [comment]
If you are using super_fetch, any lost job will eventually be rescued and the batch callback will run. You can also tune your deployment so a deploy does not result in lost jobs; review the Deployment wiki page.

**Comment by mperham** [comment]
Sidekiq::Throttled replaces super_fetch; you'll lose jobs by activating it. I'd bet that's your problem.

**Comment by aclarembeau** [comment]
Thanks a lot for the answer. 
I've opened a ticket on their side to see if that could be the source of the problem (https://github.com/sensortower/sidekiq-throttled/issues/84). 

I'll let you know
Best,
