### ISSUE TITLE
Consider dropping leader status when worker goes quiet

### ISSUE THREAD

**Issue by rwstauner** [mperham/sidekiq#4609]
Ruby version: 2.5.5
Sidekiq / Pro / Enterprise version(s):
```
gem "sidekiq-ent", "~> 1.8.1"
gem "sidekiq-pro", "~> 4.0.5"
```

Didn't see anything mentioned in the changelogs.

Would you see any issue in giving up leader status as soon as the leader goes quiet?
If the leader worker happens to be stuck on a long running job things like stats can get hung up.

**Comment by mperham** [comment]
That’s a reasonable point, a long running leader might not reflect the latest cron jobs after a deploy.

**Comment by mperham** [comment]
Just checked -- the USR2 rolling restart signal does stop the cron and leader subsystems so this should already work if you are using rolling restarts.

**Comment by rwstauner** [comment]
Oh, good to know, thanks.  Our current script is using TSTP.
