### ISSUE TITLE
Using Sidekiq Pro in open source projects

### ISSUE THREAD

**Issue by thomasleese** [mperham/sidekiq#4612]
We're interested in using Sidekiq Pro in our projects, in particular for the improved reliability and scheduling. However, our projects are open source and available for anyone to download and run locally. Is it possible to use Sidekiq Pro in an open source project? Are there any limits on what features we could use? How would deploying the app to production work?

**Comment by mperham** [comment]
Using Pro/Enterprise within an OSS app is difficult but there are a few tricks that can make it work, I think. Check out this FAQ and let me know how well it works for you. I do have the 14 day refund period and I'd be happy to refund anyone if it is just too awkward or impossible to work smoothly.

https://github.com/mperham/sidekiq/wiki/Commercial-FAQ#can-i-use-sidekiq-pro-or-enterprise-in-an-open-source-app

**Comment by thomasleese** [comment]
Thanks very much, I think that FAQ covers all our concerns! 😃
