### ISSUE TITLE
Issue with Zeitwerk new loader for rails 6

### ISSUE THREAD

**Issue by ranjithjogi88** [mperham/sidekiq#4618]
Ruby version:  ruby-2.6.5
Sidekiq / Pro / Enterprise version(s): 5.0.1

Migration from rails 5 to rails 6 changes the new code loader zeitwerk that comes with Rails 6 by default. With new zietwerk the sidekiq worker jobs are not getting completed and its keeps giving me following logs. Can anyone please suggest weather i can run and deploy my application using  config.autoloader = :classic or any fixes with zietwerk please suggest. 

sidekiq.yml
:verbose: false
:concurrency: 5
:timeout: 5
:pidfile: ./tmp/pids/sidekiq.pid

production:
  :concurrency: 10
  :timeout: 10

:queues:
  - default
  - [mailer, 2]
  - [external_api, 5]
  - [upload, 4]
  - [template_zipper, 2]
  - [custom_report_query, 3]
  - [user_import, 3]
  - [analytics, 1]
  - [cron, 1]

`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/Users/concious/.rvm/gems/ruby-2.6.5@rails-5/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0.

**Comment by mperham** [comment]
Sidekiq does not work with the `classic` autoloader in Rails 6 at all. Sidekiq 6.1 fixes that Redis warning.

**Comment by kalvinchang** [comment]
Is this true for Sidekiq 5.2.2 as well or does only Sidekiq 6.0+ not work with classic autoloading mode in Rails 6.0

**Comment by mperham** [comment]
All Sidekiq versions.

**Comment by mperham** [comment]
If you are seeing lock ups in development, try setting `-c 1` as there is one Rails issue  (in ActionText) which will deadlock Sidekiq in development.
