### ISSUE TITLE
"check all" boxes don't work in UI with Sidekiq 6.1.0

### ISSUE THREAD

**Issue by geoffharcourt** [mperham/sidekiq#4619]
Ruby version:
Sidekiq / Pro / Enterprise version(s):

Sidekiq 6.1.0
Pro 5.1.0
Ent 2.1.0

The box to check all items in the list doesn't check all the items displayed on the Retries, Scheduled, or Dead pages after upgrading.

**Comment by mperham** [comment]
I’d guess this is due to the jquery upgrade.

**Comment by mperham** [comment]
I'm struggling to debug this issue since my JavaScript skills are sad but here's the code:

```js
  $(document).on('click', '.check_all', function() {
    var checked = $(this).attr('checked');
    if (checked == 'checked') {
      $('input[type=checkbox]', $(this).closest('table')).attr('checked', checked);
    } else {
      $('input[type=checkbox]', $(this).closest('table')).removeAttr('checked');
    }
  });
```

and the HTML:

```html
            <th class="table-checkbox checkbox-column">
              <label>
                <input type="checkbox" class="check_all" />
              </label>
            </th>
```

Anyone know why this wouldn't work in jQuery 1.12?

**Comment by jc00ke** [comment]
I'm just taking a stab here, but should `'input[type=checkbox]'` be `'input[type="checkbox"]'`?

**Comment by TheRusskiy** [comment]
@mperham it could be due to this change in 1.9:
https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-
Essentially use prop instead of attr.
```
...
$(elem).prop("checked", true);
$(elem).prop("checked", false);
...
```

disclaimer: I haven't checked out the code and actually tried it

**Comment by mperham** [comment]
```js
  $(document).on('click', '.check_all', function() {
    var checked = $(this).attr('checked');
    if (checked == 'checked') {
      $('input[type=checkbox]', $(this).closest('table')).prop('checked', true);
    } else {
      $('input[type=checkbox]', $(this).closest('table')).prop('checked', false);
    }
  });
```

`prop` seems to have no effect.

**Comment by jc00ke** [comment]
With a later version of jQuery I would get `undefined` from `.attr()`. You can also get it as an boolean by using `this.checked`.

**Comment by mperham** [comment]
@jc00ke Yer a wizard, Jesse! This works. Any reason why it wouldn't work on any modern browser?

```js
$(document).on('click', '.check_all', function() {
    $('input[type=checkbox]', $(this).closest('table')).prop('checked', this.checked);
  });
```

**Comment by jc00ke** [comment]
I can't find any reasons. I'm pretty sure that's been around for a long time.

**Comment by mperham** [comment]
@TheRusskiy @jc00ke Y'all are great, thank you for helping me fix the issue!
