### ISSUE TITLE
Sidekiq was stopped suddenly

### ISSUE THREAD

**Issue by pradeepibz** [mperham/sidekiq#4620]
Hi All,

Can anyone help me? I have used Resque and sidekiq in my application. sometime It was stopped automatically.
Is there any option to find out why It was stopped?

Redis Version - 3.0.6
Resque Version - 1.27.4
Sidekiq Version - 5.2.8

**Comment by mperham** [comment]
The log output should explain why it is shutting down.

**Comment by mperham** [comment]
Looks like it explains if you turn on debug logging: `sidekiq -v`:

```
2020-07-03T15:55:55.526Z pid=35566 tid=xwe DEBUG: Got the INT signal
2020-07-03T15:55:55.526Z pid=35566 tid=xwe INFO: Shutting down
```
