### ISSUE TITLE
Seeing `undefined method `bulk_requeue' for Sidekiq::Pro::BasicFetch:Module` 

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#4622]
I suspect this is related to #4614 , but it may be a separate issue.

Ruby version: 2.6.6
Sidekiq / Pro / Enterprise version(s): Pro 5.1.0 / Sidekiq 6.1.0

Please include your initializer and any error message with the full backtrace.

NoMethodError: undefined method `bulk_requeue' for Sidekiq::Pro::BasicFetch:Module
  from sidekiq/launcher.rb:61:in `stop'
  from sidekiq/cron/launcher.rb:36:in `stop'
  from sidekiq/cli.rb:102:in `rescue in launch'
  from sidekiq/cli.rb:93:in `launch'
  from sidekiq/cli.rb:83:in `run'
  from bundle/ruby/2.6.0/gems/sidekiq-6.1.0/bin/sidekiq:31:in `<top (required)>'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `<main>'

Initializer:

`if Rails.env.production?
  Sidekiq::Pro.statsd = -> { Datadog::Statsd.new('localhost', 8125, namespace: 'sidekiq') }

  Sidekiq.configure_server do |config|
    config.redis = {
      url: redis_url,
      network_timeout: 5
    }

    config.server_middleware do |chain|
      require 'sidekiq/middleware/server/statsd'
      chain.add Sidekiq::Middleware::Server::Statsd
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = {
      url: redis_url,
      network_timeout: 5
    }
  end
end

if Rails.env.production? && Sidekiq.server?
  Sidekiq.logger.level = Logger::WARN
  Sidekiq::Cron::Job.load_from_hash JSON.parse(File.read('config/schedule.json'))
end
`

**Comment by mperham** [comment]
Yep, same as #4616 and same workaround. Did you forget to enable super_fetch or is there some reason you aren't using it?

**Comment by petergoldstein** [comment]
@mperham We didn't forget - it's just not enabled in our infrastructure.  We didn't invest the time in researching the impact because it didn't appear to be something we needed.

**Comment by mperham** [comment]
I’ll release a fix for this tomorrow morning.
