### ISSUE TITLE
Reliable push retry limit

### ISSUE THREAD

**Issue by adrian-gomez** [mperham/sidekiq#4623]
Ruby version: ruby 2.6.5p114
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.0.7 / Pro 5.0.1 / Ent 2.0.1

Please include your initializer and any error message with the full backtrace.
```
if Rails.env.feature? || Rails.env.development?
  require 'sidekiq/web'
  require 'sidekiq-ent/web'
end

require 'sidekiq-status'

# Disable unique jobs and rate limiting in the test environment
if Rails.env.test?
  Sidekiq.default_worker_options = { rate_limiters_disabled: true }
else
  Sidekiq::Enterprise.unique!
  Sidekiq::Client.reliable_push!
end

Sidekiq.configure_server do |config|
  config.redis = { url: Settings.redis.sidekiq_url, namespace: :sidekiq }
  config.super_fetch!
  config.reliable_scheduler!

  # https://github.com/mperham/sidekiq/wiki/Logging#output-format
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new unless Rails.env.development?

  scheduler = ScheduledJob

  return if ENV['CI']

  config.periodic do |manager|
    if ENV['NO_JOBS']
      manager.register(*scheduler.ping)
    else
      scheduler.all.each do |scheduled_job|
        manager.register(*scheduled_job)
      end
    end
  end

  Sidekiq::Status.configure_server_middleware config, expiration: 30.minutes
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
end

Sidekiq.configure_client do |config|
  config.redis = { url: Settings.redis.sidekiq_url, namespace: :sidekiq }

  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
end

Sidekiq::Limiter.configure do |config|
  config.errors << Mailgun::ErrorBase
  config.errors << Hubspot::RateLimitedError
end

require 'sidekiq/extensions/process_set'
require 'sidekiq/overrides/raven_error_handler'
require 'sidekiq/overrides/job_retry'
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

Problem:
Hey we running into an scenario where one of our jobs consumes a lot of ram that in turn kills the sidekiq process a few mins after it starts, as we are using reliable push it picks up the dead job and pushes it back again to a worker (which is great most of the time!) but since the memory issue its still there the worker will get killed again. All that process leads us to a situation of constant restart so our jobs gets processes at a very slow rate leading to build up.

Question?
Is there any way to limit reliable push retry attempts? Like if the same job is pulled from the reliable queue more than a couple of times it might be causing the issue so we want to stop trying.
If not:
- any plans to add it in the future
- any ideas of how we could monkey patch reliable push to archive that?
- any ideas of how we would implement that on our code?

Thanks for sidekiq! We have been enjoying it for more than 2 years now :D

**Comment by mperham** [comment]
There is no way to limit super fetch retries. Simple temporary solution: dedicate a Sidekiq process to that "fat" queue and give the process more memory.

**Comment by adrian-gomez** [comment]
@mperham we have done that in the past but it has been a recurring issue that happens once or twice a year where a change is made to a job that produces a OOM issue.
So it can basically be any worker on any queue that can become troublesome, so the temporary solution we already tried and now we want something better.

Would you consider adding this? if not can you provide some guidance so we can add it ourselves (I'll be more than happy to share the code after so it can be added into sidekiq itself)?

**Comment by mperham** [comment]
I’d certainly consider it. Forget about impl, describe the semantics: how would you want it to work? Should all recovered jobs go immediately to the dead set?

**Comment by adrian-gomez** [comment]
I would imagine a new setting when enabling reliable push to enable us to choose a max number of retries of a single job `Sidekiq::Client.reliable_push!(retry_limit: 5)` , the setting comes to not change current behavior as it will default to nil -> no limit.
When reliable push kicks in and puts jobs back into a regular queue it would count the number of times it has done so for each jid, if the count is greater than the configured number it will send the job to the dead queue instead.
Ideally it would send it with an error message of "Number of reliable push retries exceeded".

From there our engineers would be able to debug the issue and figure our if it was a fluke for that particular job to be discarded (that should be rare, given that our jobs usually wrap up pretty fast) or if it was that that job that was creating issues.

**Comment by mperham** [comment]
Ok, I think X recoveries of JID Y within Z hours is a good heuristic, further recoveries would go to the Dead set and log a warning.

I would like this feature to be turned on by default so I'll likely pick a reasonable default, e.g. 3 recoveries within 72 hours.

**Comment by adrian-gomez** [comment]
sounds great for our use case too, that default would have prevented the big pileup on our end.

Thanks for all the awesome work.
