### ISSUE TITLE
Redis::ConnectionError: Connection lost (ECONNRESET)

### ISSUE THREAD

**Issue by vitobotta** [mperham/sidekiq#4626]
Hi!

I have switched to DigitalOcean's managed Redis a week ago and while everything works, I see occasional `Redis::ConnectionError (Connection lost (ECONNRESET))` errors in Sidekiq's log and the job fails so it has to be retried. 

I have contacted DO but they aren't really helpful. I suspect it's something to do with idle connections or something like that. I upgraded Sidekiq to 6.1 and have set `reconnect_attempts` to 2 and maybe it happens less frequently (not entirely sure), but it still happens.

While I try to get some help from DO, is there a setting in Sidekiq that would make it retry connections without making the jobs fail? Some jobs should happen right away rather than being delayed due to retrying. 

Thanks!

Ruby version:
2.6.6

Sidekiq / Pro / Enterprise version(s):
6.1

Please include your initializer and any error message with the full backtrace.

initializer:
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: Settings.sidekiq_redis_url, reconnect_attempts: 2 }
end

Sidekiq.configure_client do |config|
  config.redis = { url: Settings.sidekiq_redis_url, reconnect_attempts: 2 }
end
```

stacktrace:
```
[ActiveJob] [ExpireBlogCacheJob] [36e1d171-1314-4b36-87f4-cfd4de53ef9e] Error performing ExpireBlogCacheJob (Job ID: 36e1d171-1314-4b36-87f4-cfd4de53ef9e) from Sidekiq(default) in 0.64ms: Redis::ConnectionError (Connection lost (ECONNRESET)):
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:270:in `rescue in io'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:262:in `io'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:274:in `read'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `block in call'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:243:in `block (2 levels) in process'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:384:in `ensure_connected'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
```

**Comment by mperham** [comment]
Hmm, I need the full backtrace.

**Comment by mperham** [comment]
I can't explain it. Sidekiq doesn't retry Redis operations since they frequently aren't idempotent, it only retries errors that indicate a failover took place. The Redis client internally will reconnect as you've discovered.

**Comment by vitobotta** [comment]
Hi @mperham is this better? https://privatebin.net/?296734e244e448d7#CwrrkKrPLf2RA7cXeq6kyjSYguNpMFTGBjUmYfp2hrxp

**Comment by mperham** [comment]
That error has nothing to do with Sidekiq.  You're seeing the error in your own connection in redis_cache_store.

app-worker-5dfd745b4b-92kfk app /app/vendor/cache/ruby/2.6.0/bundler/gems/rails-f485a0da293d/activesupport/lib/active_support/cache/redis_cache_store.rb:233:in `delete_matched'
app-worker-5dfd745b4b-92kfk app /app/app/jobs/expire_blog_cache_job.rb:9:in `block in perform'

**Comment by vitobotta** [comment]
Oh! I don't know how I missed it, thanks! I'll investigate the cache then. Thanks a lot :)

**Comment by meer-online** [comment]
@vitobotta Were you able to figure out this issue?

**Comment by vitobotta** [comment]
@meer-online I can't remember the details because I switched to another provider and I am managing Redis myself in Kubernetes, so I am no longer having that problem.

**Comment by MarcoMatarazzo** [comment]
For whoever lands here having the same issue on Digital Ocean: this is likely caused by the fact that internally they reset SSL/TLS connections after being idle for 12 hours.
