### ISSUE TITLE
Passing 'exists?' command to redis as is; blind passthrough has been deprecated

### ISSUE THREAD

**Issue by dbackeus** [mperham/sidekiq#4627]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): Sidekiq version 6.1.0, Pro version 5.1.1 

Appears that after fixing https://github.com/mperham/sidekiq/issues/4591 we now see a different recurring deprecation warning:

```
Passing 'exists?' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/launcher.rb:161:in `block (2 levels) in ❤')
```

While the previous warning could be silenced by explicitly setting `Redis.exists_returns_integer = false` we are not aware of any similar work around for this warning.

**Comment by mperham** [comment]
That’s an issue with redis-namespace

**Comment by dbackeus** [comment]
Right, I guess this is the issue to pay attention to: https://github.com/resque/redis-namespace/issues/172
