### ISSUE TITLE
CSRF protection change questions 

### ISSUE THREAD

**Issue by FeminismIsAwesome** [mperham/sidekiq#4628]
Hi, while updating my gem to the latest (6.1), it took me a bit of time to realize it was just a simple switch to `Sidekiq::Web.use(Sidekiq::Web::CsrfProtection)` over `Sidekiq::Web.use(::Rack::Protection, {use: :authenticity_token, logging: true, message: "Didn't work!"})`, and while doing so found a wiki page that was out of date due to the inlining of Rack::Protection. In the spirit of being a good neighbor, I tried to take a stab at cleaning up the mentions (https://github.com/mperham/sidekiq/wiki/Monitoring/5abed81171529dd46be3be492f82c088cce3931b) [sorry, thought it would make a PR to the wiki instead of just let me commit the changes, but I did revert them immediately). 

While reviewing those mentions, I noticed that Sidekiq::Web::CsrfProtection currently doesn't do anything with the options, such as the custom logging message that Rack::Protection used to provide. Is that a correct read? ...is it not important and is it as simple as removing that mention of them from the wiki?

Thanks,
Ian

Ruby version:
Sidekiq / Pro / Enterprise version(s):
sidekiq 6.1
sidekiq pro 5.1
sidekiq ent 2.0.1

**Comment by mperham** [comment]
Thanks for the reminder, I've updated the wiki. The wiki reflects the latest version only; I delete out of date content so I've removed any mention of CSRF and rack-protection. If people discover gotchas with the new CSRF code, they are welcome to document them or open an issue.
