### ISSUE TITLE
Sidekiq Pro Web UI Sharding Fobidden Errors

### ISSUE THREAD

**Issue by navied** [mperham/sidekiq#4629]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.1.1
Sidekiq Pro: 5.1.1

I seem to be getting a Forbidden error when doing any Post/Delete requests on the Web UI where [Sharding](https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding) is used. This worked with the previous version but once upgrading I am getting forbidden errors returned. 

Looks like the new CSRF protection is blocking the request:

WARN -- : attack prevented by Sidekiq::Web::CsrfProtection

Edit: Accidentally submitted the issue a bit too quickly, did a quick edit with the problem

**Comment by mperham** [comment]
You need to configure a session, as described in the Monitoring wiki page.

**Comment by navied** [comment]
I tried setting the session right after the require statement as stated in routes.rb there but it doesn't seem to be working still.

How it looks like:

```
require "sidekiq/pro/web"
Sidekiq::Web.set :session_secret, Rails.application.secrets.secret_key_base
```

If the CSRF protection with rack-protection is similar wouldn't this been an issue before with the lack of secret being set?

**Comment by navied** [comment]
Going to close this since it seems solved!
