### ISSUE TITLE
Updating Sidekiq from 6.0.7 to 6.1.0 breaks Web UI. It returns the wrong Content-Length header

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#4630]
Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.1.0

When I use Sidekiq 6.1.0, The Web UI page returns the wrong Content-Length header. Consequently, the browser renders nothing.

The solution is removing the following lines.

```ruby
# https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L180-L182
unless using? ::Rack::ContentLength
  middlewares.unshift [[::Rack::ContentLength], nil]
end
```

If I don't remove them, the HTML response will be truncated. The value of the Content-Length header is 8075 and this number matches with the size of truncated HTML below.

```html
<!doctype html>
<html dir="ltr">
  <head>
    <title>[DEVELOPMENT] Sidekiq</title>
    <meta charset="utf-8" />
<script>/* omitted */</script>
<script>/* omitted */</script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />

    <link href="/sidekiq/stylesheets/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
    

    <link href="/sidekiq/stylesheets/application.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/sidekiq/stylesheets/application-dark.c <- Unintentionally truncated
```

**Comment by mperham** [comment]
Show me your Gemfile.lock.

**Comment by ts-3156** [comment]
Stable Gemfile.lock (using Sidekiq 6.0.7)
https://github.com/egotter/egotter/blob/master/Gemfile.lock

Reported Gemfile.lock (trying to use Sidekiq 6.1.0)
https://github.com/egotter/egotter/blob/8808ae1b01a0a8b099e45bc5cb2fc30d6639e602/Gemfile.lock

The diffs
https://github.com/egotter/egotter/pull/469/files

Please let me know if you need any other information.

**Comment by ts-3156** [comment]
I found out that the Newrelic gem was the cause. when I remove Newrelic gem, the Web UI works correctly.

It's just a guess, but the JS code inserted by Newrelic for the tracking may be the root cause.

**Comment by mperham** [comment]
Update newrelic, they fixed their issue I believe.

**Comment by ts-3156** [comment]
Thank you for your advice!
