### ISSUE TITLE
Passing hashes as args may cause errors

### ISSUE THREAD

**Issue by cabe56** [mperham/sidekiq#4632]
Had an issue and found the root cause was that I was not following one of Sidekiq's [best practices](https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple).

When passing a Ruby hash to a job, I wasn't aware that hashes were not serialized back to Ruby hashes exactly as passed, but as JSON objects. The choice makes sense and now that I am aware I think this won't happen again.

Printing a warning or raising an exception would make this knowledge unnecessary and save developers from debugging this.

**Comment by mperham** [comment]
I can't implement this in any way without disrupting thousands of existing codebases.

**Comment by cabe56** [comment]
Agree, raising an exception in this case changes the existing contract.

Something that looks like a deprecation warning could make it visible that something 'bad' is happening without changing it.
