### ISSUE TITLE
Gracefully handle poison pills

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4633]
### Background

The base version of Sidekiq pops jobs off the Redis queue and executes them. If a job crashes the Sidekiq process (aka a **poison pill**), that job (and any other concurrent jobs) will be lost.

Sidekiq Pro offers super_fetch, which stores executing jobs within a private queue in Redis, ensuring that jobs never leave Redis until they are acknowledged as complete. But this leads to a bad edge case: when super_fetch recovers any crashed jobs and re-executes them, they will (presumably) crash Sidekiq again and again, leading to an ever-growing set of poison pills in Redis.

Today we require the developer to either fix the crash or delete the poison pills manually.

### Improvement

Adjust super_fetch so it will track recoveries by JID in Redis and only allow M recoveries within N hours. If the count goes over M, it should push the job onto the Dead set. This should remove any need for manual processing of poison pills.

- [x] Provide default options of 3 recoveries in 72 hours.
- [x] Add a `jobs.poison` counter metric which increments for each job which goes to the Dead set, with `queue` and `worker` tags.

First discussed in #4623

**Comment by krapans** [comment]
Will this be addressed in any way for Pro or Enterprise users?

**Comment by mperham** [comment]
I don’t understand your question.

**Comment by krapans** [comment]
Sorry, so what I meant is, this is still feature that we were looking up to, though this issue was closed. Will this issue be transformed into different issue to address this problem/feature?

**Comment by mperham** [comment]
It was closed because it was implemented and released in pro 5.2.

**Comment by fschwahn** [comment]
This feature is super-useful for us, as we occasionally get our workers killed by Heroku (due to unusually large data sets and such).

> If the count goes over M, it should push the job onto the Dead set.

I went through the code, but did not see logs emitted when that happens. Is there a possibility to determine a poison pill has been pushed to the Dead set any other way? A log line would be simplest for us, as we'd just create an alert in our log management service.

**Comment by mperham** [comment]
> Is there a possibility to determine a poison pill has been pushed to the Dead set any other way? A log line would be simplest for us, as we'd just create an alert in our log management service.

Good idea. I've added a WARN line for each poison pill killed.

        Sidekiq.logger.warn("Killed poison pill #{klass} #{jid}")

**Comment by fschwahn** [comment]
Awesome, looking forward to the next release 👍

**Comment by victorfgs** [comment]
Is there a way to change the `3 runs` setting or the `72 hours` setting?

**Comment by adamniedzielski** [comment]
@victorfgs if I can read the code well you should be able to do:

```ruby
Sidekiq.configure_server do |config|
  config.super_fetch!(max_recoveries: 5, recovery_window: 73 * 60 * 60)
end
```

That should work in Sidekiq Pro 5.3.0. I only looked into the source code and not tried it, though. If you confirm that it works you could add an example to https://github.com/mperham/sidekiq/wiki/Reliability 🙂

**Comment by adamniedzielski** [comment]
And in general: when you're a happy owner of Sidekiq Pro license I recommend `bundle show sidekiq-pro` and then just read the source code 😉 There are a few undocumented goodies there.

**Comment by victorfgs** [comment]
> And in general: when you're a happy owner of Sidekiq Pro license I recommend `bundle show sidekiq-pro` and then just read the source code wink There are a few undocumented goodies there.

wow! had no idea about this! Thanks for the tip. I'll try and change the recovery settings. Let you know about it in a bit :)

**Comment by victorfgs** [comment]
Yup! That worked for me just fine

**Comment by jongbeau** [comment]
Is there a way to see the parameters that were associated with the job that was killed? We have the generic `Sidekiq::Extensions::DelayedClass` but can't see which class/method caused this poison pill.
