### ISSUE TITLE
Separated Web UI gem

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#4634]
Would you consider offering the Web UI as a separate gem? 

This change makes it easier to customize and debug the Web UI and keeps the size of the Sidekiq itself small.

As far as I could see the recent commits, you are trying to reduce the number of dependent libraries as much as possible. I think it is consistent with this policy to offer it as a separate gem.

Thank you for reading the entire issue.

**Comment by mperham** [comment]
I prefer one complete package with all batteries included, so to speak. With different gems, I have to track versions and API usage carefully. This way I know the API, the Web, the Client and the CLI are all using the same version that are designed and tested together.
