### ISSUE TITLE
Batches with ActiveJob?

### ISSUE THREAD

**Issue by donaldong** [mperham/sidekiq#4637]
Hi, we have some monitoring code (i.e. collecting customized metrics and logging), and some other application-specific abstractions built on top of ActiveJob. If we'de like to use batches, would you recommend rewriting the code on top of `Sidekiq::Worker`?

https://github.com/mperham/sidekiq/wiki/Batches#notes
> Batches don't work well with ActiveJob; it has edge cases which break the job tracking. Please use native Sidekiq Workers.

I'm curious what is specifically breaking the job tracking? Could it be easier for us to fix the edge cases?

Thanks!

**Comment by mperham** [comment]
The major part of ActiveJob that integrates very poorly with Sidekiq is `rescue_from` and exception handling. ActiveJob implements all of that itself so Sidekiq can't track failures and Sidekiq can't keep failed jobs in the Retry Set, visible in the Web UI.

**Comment by donaldong** [comment]
> The major part of ActiveJob that integrates very poorly with Sidekiq is `rescue_from` and exception handling.

If we don't use `rescue_from` and ensure all errors in `perform` are bubbled up to the top, would ActiveJob be okay to use?

**Comment by mperham** [comment]
I don't test batches with ActiveJob and would not recommend it.

**Comment by donaldong** [comment]
Thanks for your quick responses! I will look for other alternatives.
