### ISSUE TITLE
Jobs are randomly changing order in queue

### ISSUE THREAD

**Issue by feliperaul** [mperham/sidekiq#4638]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): 6.0.7

Initializer: 
```
:concurrency: 25
:queues:
  - mailers
  - default
  - importers
  - searchkick
  - other
```

We are currently inspecting a queue that is taking a long time to run ("importers").

On investigating, we noticed a very unusual behavior that we think is a bug and might be causing performance degradation and/or unexpected behavior.

If we activate "Live poll" and watch the queue on the web ui, every 2 seconds we have a completely different order of jobs, even tough no new jobs have been added and no jobs have been processed (these jobs take a few minutes each, and they only receive jobs manually, so it should be very stable during processing). 

Using Rails console to inspect it further, we could confirm that on every poll (a few seconds apart), we get a completely different array of `job.jids`, even tough all the Job Ids remain the same (only the order changes, but the jobs ids remain constant, so no new jobs are being added or removed).

We're using this debug code to confirm the order is changing very rapidly:

```
def debug
  queue = Sidekiq::Queue.new("importers")
  jids = queue.map {|job| job.jid}; p "I have #{jids.size} jobs and my first one id is #{jids[0]}"
  sleep 1
  jids2 = queue.map {|job| job.jid}; p "I have #{jids2.size} jobs and my first one id is #{jids2[0]}"
  p "This is jids2 - jids"
  p jids2 - jids
  p "This is jids - jids2:"
  p jids - jids2
  p "Are they the same?"
  p jids == jids2
  p "But what if I order them?"
  p jids.sort == jids2.sort
end
```

This is the result:

```
(main)> debug
"I have 151 jobs and my first one id is 20480233f53e0b8d62231615"
"I have 151 jobs and my first one id is 0dc7e77f17c1f6b3fc6e59a8"
"This is jids2 - jids"
[]
"This is jids - jids2:"
[]
"Are they the same?"
false
"But what if I order them?"
true
```

AFAIK, Sidekiq guarantees that jobs are going to be fetched in order (even tough, of course, it's an Async job queue, so there's no guarantee they will _finish_ in the order they were added), so we deem this to be a bug.

**Comment by feliperaul** [comment]
Update: here's a quick video demonstrating the changing of the order of the jobs in that queue. 

https://www.loom.com/share/2cd96894f72040f78023f3ed6093a8e1

**Comment by mperham** [comment]
A video is fine, but really I need a script which reproduces the issue locally.

**Comment by feliperaul** [comment]
@mperham Mike I've just realized that this project uses `sidekiq-throttled`, and could confirm the behavior only happens if the throttle is used. 

I'll open an issue in that gem instead. Thank you.
