### ISSUE TITLE
is it possible to log the queue name of a job?

### ISSUE THREAD

**Issue by ToadJamb** [mperham/sidekiq#4639]
I have what I hope to be a relatively simple issue.

I have only used sidekiq for trivial things until now. With Resque, I know the logs indicate which queue a worker is in, but I'm not seeing any trivial way to accomplish this in Sidekiq (as it doesn't appear to occur by default). Am I missing something? Surely there is a way to get the logs to indicate which queue a job was in. What am I missing?

**Comment by mperham** [comment]
The job payload itself includes the queue name; it's accessible from server-side middleware. It's not available to the actual Worker#perform method because the only state accessible to a running job are the arguments.

**Comment by ToadJamb** [comment]
I don't see it:
`2020-07-09T22:42:21.912Z 1265896 TID-rwh0 Orders::StateTransitionWorker JID-06037e58c6699210c02e876a INFO: start`

I'm also not seeing any indication of the parent id when a job spawns a new job. Is that possible to get?

**Comment by ToadJamb** [comment]
As far as that goes, I'm not seeing the `perform` params, either. Is there any reason they might not show up in the logs?

**Comment by mperham** [comment]
You can implement your own parent/child tracking with Middleware, I would suggest you review that wiki page.

The default logger logs what you see only. Arguments can be huge and/or sensitive so they aren't logged. Most people don't need or care to see the queue name so that's never been requested before.
