### ISSUE TITLE
Batches Web UI glitch

### ISSUE THREAD

**Issue by navied** [mperham/sidekiq#4640]
Ruby version: 2.6.6
Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.1.1
Sidekiq Pro: 5.1.1

When multiple [shards](﻿﻿https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding) have active batches it seems to cause the web UI to not display the batches properly, but instead show a blank page, refreshing a couple of time over and over again seems to make it show up finally. 

Screenshot on how it looks:

![image](https://user-images.githubusercontent.com/1896993/87113640-b775d300-c23c-11ea-93e9-522b9081c1ae.png)

Config for shards:

```ruby
mount Sidekiq::Pro::Web.with(redis_pool: ConnectionPool.new { Redis.new(url: redis://host:6379) }), at: "/admin/sidekiq/shard1", as: "sidekiq_shard1"
mount Sidekiq::Pro::Web.with(redis_pool: ConnectionPool.new { Redis.new(url: redis://host:6379/1) }), at: "/admin/sidekiq/shard2", as: "sidekiq_shard2"
mount Sidekiq::Pro::Web.with(redis_pool: ConnectionPool.new { Redis.new(url: redis://host:6379/2) }), at: "/admin/sidekiq/shard3", as: "sidekiq_shard3"
```

**Comment by mperham** [comment]
Show me your initializer.

**Comment by mperham** [comment]
This is a bug, I’m in the process of opening the underlying issue now.
