### ISSUE TITLE
Sort busy processes by it's started_at time

### ISSUE THREAD

**Issue by c2ofh** [mperham/sidekiq#4641]
Ruby version: 2.6.6
Sidekiq / Pro / Enterprise version(s): v6.0.7 / - / -

Currently busy jobs are randomly sorted in the list. (live update enabled)
It would be helpful to recognize a long term running job. 
I see a job, running 2 minutes, the next second the job is gone. No the job is not finished. The job jumped just to the end of the list, to jump to another position seconds later...

When the list is sorted by it's started_at time, then the job doesn't fly out of sight. When it's not there, it'll either be further up or finished. 

I would contribute, but I can't find the right place to sort the processes. 
To sort it directly in the `busy.erb` would not match your style.

**Comment by mperham** [comment]
Good idea, I like it. Should be an easy PR for anyone who wants their first OSS PR.
