### ISSUE TITLE
LoadError (Unable to autoload constant Api::V1::SessionsController, expected /Users/oka/live-projects/my-api/app/controllers/api/v1/sessions_controller.rb to define it):

### ISSUE THREAD

**Issue by chikarao** [mperham/sidekiq#4644]
Ruby version: 2.7.1
Sidekiq: 6.7.0

After installing sidekiq to my rails project (rails v5.1) after upgrading ruby to 2.7.1, I started getting this error in addition to sometimes getting the ArgumentError below. I get the error when I change my rails code and when I restart the rails server. The errors disappear in subsequent refreshes of the browser.

ArgumentError (A copy of Api::V1::Users has been removed from the module tree but is still active!)

I have done fair bit of research and I have been able to get the app running without errors by setting config.eager_load to true in development.rb but I would like to try to resolve fully. I understand there are some issue with including auto-loadable modules with the non-autoloadable, but I cannot seem to find any resolutions that I can implement within my code.

Can you suggest any directions forward in resolving this?

Initializer:
config/sidekiq.rb

Sidekiq.configure_server do |config|
config.redis = { url: 'redis://localhost:6379', namespace: 'test_sidekiq' }
end

Sidekiq.configure_client do |config|
config.redis = { url: 'redis://localhost:6379', namespace: 'test_sidekiq' }
end

LoadError (Unable to autoload constant Api::V1::SessionsController, expected /Users/oka/live-projects/my-api/app/controllers/api/v1/sessions_controller.rb to define it):
LoadError (Unable to autoload constant Api::V1::Users::ConversationsController, expected /Users/oka/live-projects/my-api/app/controllers/api/v1/users/conversations_controller.rb to define it):

LoadError (Unable to autoload constant Api::V1::Users::BlahController, expected /Users/oka/live-projects/my-api/app/controllers/api/v1/users/blah_controller.rb to define it):
activesupport (5.1.5) lib/active_support/dependencies.rb:512:in load_missing_constant' activesupport (5.1.5) lib/active_support/dependencies.rb:202:in const_missing'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in const_get' activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in block in constantize'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in each' activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in inject'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in constantize' activesupport (5.1.5) lib/active_support/dependencies.rb:583:in get'
activesupport (5.1.5) lib/active_support/dependencies.rb:614:in constantize' actionpack (5.1.5) lib/action_dispatch/http/request.rb:85:in controller_class_for'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:99:in binary_params_for?' actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:90:in set_binary_encoding'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:67:in path_parameters=' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:48:in block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in each' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in call' bullet (5.6.1) lib/bullet/rack.rb:12:in call'
warden (1.2.7) lib/warden/manager.rb:36:in block in call' warden (1.2.7) lib/warden/manager.rb:35:in catch'
warden (1.2.7) lib/warden/manager.rb:35:in call' rack (2.0.4) lib/rack/etag.rb:25:in call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in call' rack (2.0.4) lib/rack/head.rb:12:in call'
activerecord (5.1.5) lib/active_record/migration.rb:556:in call' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in block in call'
activesupport (5.1.5) lib/active_support/callbacks.rb:97:in run_callbacks' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in call' railties (5.1.5) lib/rails/rack/logger.rb:36:in call_app'
railties (5.1.5) lib/rails/rack/logger.rb:24:in block in call' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in block in tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in tagged' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in tagged'
railties (5.1.5) lib/rails/rack/logger.rb:24:in call' actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in call' rack (2.0.4) lib/rack/runtime.rb:22:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/static.rb:125:in call'
rack (2.0.4) lib/rack/sendfile.rb:111:in call' rack-cors (1.0.2) lib/rack/cors.rb:97:in call'
railties (5.1.5) lib/rails/engine.rb:522:in call' puma (3.11.3) lib/puma/configuration.rb:225:in call'
puma (3.11.3) lib/puma/server.rb:624:in handle_request' puma (3.11.3) lib/puma/server.rb:438:in process_client'
puma (3.11.3) lib/puma/server.rb:302:in block in run' puma (3.11.3) lib/puma/thread_pool.rb:120:in block in spawn_thread'
activesupport (5.1.5) lib/active_support/dependencies.rb:512:in load_missing_constant' activesupport (5.1.5) lib/active_support/dependencies.rb:202:in const_missing'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in const_get' activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in block in constantize'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in each' activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in inject'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in constantize' activesupport (5.1.5) lib/active_support/dependencies.rb:583:in get'
activesupport (5.1.5) lib/active_support/dependencies.rb:614:in constantize' actionpack (5.1.5) lib/action_dispatch/http/request.rb:85:in controller_class_for'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:99:in binary_params_for?' actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:90:in set_binary_encoding'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:67:in path_parameters=' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:48:in block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in each' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in call' bullet (5.6.1) lib/bullet/rack.rb:12:in call'
warden (1.2.7) lib/warden/manager.rb:36:in block in call' warden (1.2.7) lib/warden/manager.rb:35:in catch'
warden (1.2.7) lib/warden/manager.rb:35:in call' rack (2.0.4) lib/rack/etag.rb:25:in call'
rack (2.0.4) lib/rack/conditional_get.rb:38:in call' rack (2.0.4) lib/rack/head.rb:12:in call'
activerecord (5.1.5) lib/active_record/migration.rb:556:in call' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in block in call'
activesupport (5.1.5) lib/active_support/callbacks.rb:97:in run_callbacks' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in call' railties (5.1.5) lib/rails/rack/logger.rb:36:in call_app'
railties (5.1.5) lib/rails/rack/logger.rb:24:in block in call' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in block in tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in tagged' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in tagged'
railties (5.1.5) lib/rails/rack/logger.rb:24:in call' actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in call' rack (2.0.4) lib/rack/runtime.rb:22:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/static.rb:125:in call'
rack (2.0.4) lib/rack/sendfile.rb:111:in call' rack-cors (1.0.2) lib/rack/cors.rb:97:in call'
railties (5.1.5) lib/rails/engine.rb:522:in call' puma (3.11.3) lib/puma/configuration.rb:225:in call'
puma (3.11.3) lib/puma/server.rb:624:in handle_request' puma (3.11.3) lib/puma/server.rb:438:in process_client'
puma (3.11.3) lib/puma/server.rb:302:in block in run' puma (3.11.3) lib/puma/thread_pool.rb:120:in block in spawn_thread'

/usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/gems/json-2.1.0/lib/json/common.rb:156: warning: Using the last argument as keyword parameters is deprecated
activesupport (5.1.5) lib/active_support/dependencies.rb:512:in load_missing_constant' activesupport (5.1.5) lib/active_support/dependencies.rb:202:in const_missing'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in const_get' activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in block in constantize'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in each' activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in inject'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in constantize' activesupport (5.1.5) lib/active_support/dependencies.rb:583:in get'
activesupport (5.1.5) lib/active_support/dependencies.rb:614:in constantize' actionpack (5.1.5) lib/action_dispatch/http/request.rb:85:in controller_class_for'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:99:in binary_params_for?' actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:90:in set_binary_encoding'
actionpack (5.1.5) lib/action_dispatch/http/parameters.rb:67:in path_parameters=' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:48:in block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in each' actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in call' bullet (5.6.1) lib/bullet/rack.rb:12:in call'
warden (1.2.7) lib/warden/manager.rb:36:in block in call' warden (1.2.7) lib/warden/manager.rb:35:in catch'
warden (1.2.7) lib/warden/manager.rb:35:in call' rack (2.0.4) lib/rack/etag.rb:25:in call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in call' rack (2.0.4) lib/rack/head.rb:12:in call'
activerecord (5.1.5) lib/active_record/migration.rb:556:in call' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in block in call'
activesupport (5.1.5) lib/active_support/callbacks.rb:97:in run_callbacks' actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in call' railties (5.1.5) lib/rails/rack/logger.rb:36:in call_app'
railties (5.1.5) lib/rails/rack/logger.rb:24:in block in call' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in block in tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in tagged' activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in tagged'
railties (5.1.5) lib/rails/rack/logger.rb:24:in call' actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in call' rack (2.0.4) lib/rack/runtime.rb:22:in call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in call' actionpack (5.1.5) lib/action_dispatch/middleware/static.rb:125:in call'
rack (2.0.4) lib/rack/sendfile.rb:111:in call' rack-cors (1.0.2) lib/rack/cors.rb:97:in call'
railties (5.1.5) lib/rails/engine.rb:522:in call' puma (3.11.3) lib/puma/configuration.rb:225:in call'
puma (3.11.3) lib/puma/server.rb:624:in handle_request' puma (3.11.3) lib/puma/server.rb:438:in process_client'
puma (3.11.3) lib/puma/server.rb:302:in block in run' puma (3.11.3) lib/puma/thread_pool.rb:120:in block in spawn_thread'

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#autoloading
