### ISSUE TITLE
All sidekiq workers in idle mode, not processing any job

### ISSUE THREAD

**Issue by priyamwadpathak** [mperham/sidekiq#4645]
Ruby version: 2.4.1
Sidekiq version: 5.1.3

Today I encountered an odd thing that all the sidekiq workers are busy and in idle mode. I found a similar issue [here](https://github.com/mperham/sidekiq/issues/1920)
Enabled live poll but nothing happened.

![image](https://user-images.githubusercontent.com/17009890/87505852-8d327400-c687-11ea-8df4-cb0c292a3ebe.png)

Then I restarted sidekiq and jobs got processed. But 2 workers are still in idle mode.

![image](https://user-images.githubusercontent.com/17009890/87505933-c4a12080-c687-11ea-84bb-55fcff8fb0a6.png)

**Comment by mperham** [comment]
What does the TTIN signal tell you?

**Comment by swistak35** [comment]
I had similar issue when `pool` in my `config/database.yml` was lower than the amount of sidekiq workers in one instance. Considering that the default for rails for development is AFAIR 5, this may be the case for you :)
