### ISSUE TITLE
sidekiqswarm: Add support for preloading Rails app

### ISSUE THREAD

**Issue by donaldong** [mperham/sidekiq#4646]
Ruby version: 2.5.5
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.1.3 / Pro 4.0.3 / Ent 1.7.2

### Context
In my project, with a fresh irb process
```ruby
require 'bundler/setup'
Bundler.require('default', 'development')
```
consumes 272MB memory.

### Repro
Start a sidekiq swarm with 30 processes. The processes consume 10GB (> 30 * 272 MB) memory.

### Investigation
I looked into `/proc/<pid>/smaps` and aggregated the memory segments:
```
{"Shared_Clean:"=>15876, "Shared_Dirty:"=>42376, "Private_Clean:"=>0, "Private_Dirty:"=>279384, "Shared_Hugetlb:"=>0, "Private_Hugetlb:"=>0}
```
About ~9GB (30 * 272 MB) of the segments are under Private Dirty.

I patched it so it calls `boot_system` before forking the child processes. With the patch,
```
{"Shared_Clean:"=>6312, "Shared_Dirty:"=>299552, "Private_Clean:"=>0, "Private_Dirty:"=>21836, "Shared_Hugetlb:"=>0, "Private_Hugetlb:"=>0}
```
The private mem segs only take ~0.62GB, and the overall memory usage dropped to ~1.5GB.

Thoughts on this approach?

**Comment by mperham** [comment]
I'm unclear what you are suggesting.

1. Are you suggesting including the environment group in the Bundler.require?
2. Are you suggesting booting Rails before forking?

1 shouldn't be too hard; you can already do it today with `SIDEKIQ_PRELOAD=default,development`. 2 is a huge change and is fraught with peril, that peril is why every daemon except Sidekiq includes `after_fork` callbacks.

**Comment by donaldong** [comment]
> Are you suggesting booting Rails before forking?

Yes. For my setting at least, the gems preloaded by `Bundler.require` won't stick in the shared memory. All the forked processes ended up having a copy of pretty much all gems.

I'm not sure how to evaluate the risks of this approach -- each process should have their own copy of all objects (copy-on-write), what might go wrong if Rails was booted before forking?

**Comment by mperham** [comment]
The issue is that any locks, threads or sockets created in Rails initializers will be shared by all child processes. That's the purpose of `after_fork` blocks: to cleanup or re-initialize anything needed by each child. Unfortunately it's also a major source of support issues, people frequently don't read the docs and they would think it's a Sidekiq bug breaking their app. I could make it opt-in but that's why I've never implemented it.

**Comment by donaldong** [comment]
> I could make it opt-in

That'd be great! Thank you for explaining, I see how this can be tricky now. For apps that do not require re-initializing, this can be a big win.

Maybe there can be an `after_fork` hook too in sidekiq?

**Comment by mperham** [comment]
No guarantees but I'll investigate.

**Comment by mperham** [comment]
I'm implementing this right now. Here's the before and after memory data I see on OSX.

## Before

```
❯ ps aux | grep sidekiq
mikeperham       38022   0.0  1.0  4436192  81776 s000  S+    2:54PM   0:01.77 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       38021   0.0  1.0  4441336  82664 s000  S+    2:54PM   0:02.00 sidekiq 6.1.1 myapp [0 of 2 busy] leader   
mikeperham       38020   0.0  1.0  4435668  81688 s000  S+    2:54PM   0:01.77 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       38019   0.0  1.0  4435668  81600 s000  S+    2:54PM   0:01.77 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       38013   0.0  0.5  4383092  40528 s000  S+    2:54PM   0:00.94 sidekiqswarm, managing 4 processes      
```

## After

```
❯ ps aux | grep sidekiq
mikeperham       37809   0.2  0.2  4433896  15888 s000  S+    2:53PM   0:00.04 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       37808   0.0  0.2  4433896  15548 s000  S+    2:53PM   0:00.04 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       37807   0.0  0.2  4433896  16040 s000  S+    2:53PM   0:00.04 sidekiq 6.1.1 myapp [0 of 2 busy]      
mikeperham       37806   0.0  0.7  4442852  59056 s000  S+    2:53PM   0:00.32 sidekiq 6.1.1 myapp [0 of 2 busy] leader      
mikeperham       37800   0.0  1.0  4421792  86672 s000  S+    2:53PM   0:01.87 sidekiqswarm, managing 4 processes      
```

Notice the non-leader children drop from 80MB to 15MB. This is on a trivial default Rails app but that's still massive savings.

As for `after_fork`, here's my proposed API:

```ruby
Sidekiq.configure_server do |config|
  config.on(:fork) do
    ActiveRecord::Base.clear_active_connections!
  end
end
```

**Comment by donaldong** [comment]
Awesome! This is great!

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#application-preload

2.1.1 will be released soon.

**Comment by justin808** [comment]
With a memory pattern like this on a Heroku P-L, is there any advantage to disabling with `SIDEKIQ_PRELOAD=`.

In other words, is there any positive or negative speed tradeoff with reduced memory usage?

![image](https://user-images.githubusercontent.com/1118459/139631969-4e2ee67f-21c6-4edc-87b4-eebee651c1ae.png)

**Comment by mperham** [comment]
@justin808 Impossible for me to know. There are always CPU time and memory space tradeoffs in software. That's literally what a cache is.
