### ISSUE TITLE
Cannot update sidekiq to 5.2.9 when having redis 4.2.1 already installed

### ISSUE THREAD

**Issue by AlexanderFedorenko** [mperham/sidekiq#4647]
Ruby version: 2.4.10
Sidekiq / Pro / Enterprise version(s): 5.2.8

> Are you using an old version?

Yes

> Have you checked the changelogs to see if your issue has been fixed in a later version?

Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

Problem

As described in [Sidekiq 5.2.8 locks Rack to 2.0.x (CVE found)](https://github.com/mperham/sidekiq/issues/4566), there are issues with rack, which should be updated to 2.2.x versions.
However, you cannot update sidekiq to 5.2.9 (and rack) if you have redis gem version greater than 4.2.0 (I have 4.2.1), as this commit [Avoid redis-rb >= 4.2 due to `exists` API deprecation](https://github.com/mperham/sidekiq/commit/e2de6826337d2d7bc5020eed3248c712f7351cad) sets redis version cap to 4.2.0.

Command `bundle update sidekiq --conservative` gives this:
```
Bundler could not find compatible versions for gem "redis":
  In snapshot (Gemfile.lock):
    redis (= 4.2.1)

  In Gemfile:
    redis (~> 4)

    redis-namespace (~> 1.7.0) was resolved to 1.7.0, which depends on
      redis (>= 3.0.4)

    redis-rails was resolved to 5.0.2, which depends on
      redis-store (>= 1.2, < 2) was resolved to 1.4.1, which depends on
        redis (>= 2.2, < 5)

    sidekiq (~> 5.2.9) was resolved to 5.2.9, which depends on
      redis (>= 3.3.5, < 4.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Is there a way to keep latest redis 4.2.1 and still update sidekiq to 5.2.9 ?

**Comment by mperham** [comment]
No, you have to run an older Redis gem.

**Comment by AlexanderFedorenko** [comment]
Thanks for answer
