### ISSUE TITLE
concurrency value not being used

### ISSUE THREAD

**Issue by jongbeau** [mperham/sidekiq#4649]
Ruby version: 2.6.5

Sidekiq / Pro / Enterprise version(s):
sidekiq 5.2.7
sidekiq-ent 1.8.1

No matter what value I pass for concurrency, I'm only seeing 1 thread.
For example, if I run: `bundle exec sidekiq -c 20`

This is what I see in the web console:
![image](https://user-images.githubusercontent.com/2096970/88316120-ee3bf680-ccdc-11ea-8f9b-95cef8af7f05.png)

What am I missing?

Thanks!

**Comment by mperham** [comment]
Show me your initializer and the logged output when started with `-v`.

**Comment by mperham** [comment]
Likely because you're running in development mode.  Rails forces Sidekiq to be single threaded so it can reload code.

**Comment by mperham** [comment]
Actually that should say 20 anyways, but you'll only see one job running at a time.

**Comment by jongbeau** [comment]
I figured it out. Looks like we are doing this in the initializer:
` concurrency = (concurrency / Concurrent.processor_count).to_i`
😕

**Comment by mperham** [comment]
That doesn't make much sense; MRI can only use 1 core per sidekiq process.￼
