### ISSUE TITLE
Processing different job in same queue independently from each other

### ISSUE THREAD

**Issue by OskarEichler** [mperham/sidekiq#4651]
Hey Mike,
Got a question regarding queues and allowing different jobs in the same queue to run independently from each other. 

Here is the scenario:
We have a "once_per_week" queue into which we schedule a lot of jobs that usually take a couple of days to complete.
So for example on Monday we schedule 500.000 jobs of one kind. On Tuesday we schedule 600.000 jobs of a different kind.
The problem now is that all the new jobs that came in on Tuesday need to wait until the ones from Monday all went through before they start to be processed, even though they are completely different jobs with different concurrencies and thresholds.

Of course we could schedule them into a different queue, but I read somewhere that it's not ideal to have way too many overall queues and we already have 30+.

Is there a way to configure a particular queue to process these different jobs simultaneously, so that even though technically there's still 200.000 Monday jobs at the head of the queue, it starts already processing the Tuesday jobs as well? So essentially instead of having one ultimate order for all jobs in that queue, the order of processing is defined by the different jobs and the same queue can already start processing newly added jobs of a different nature and with different settings before completing the backlog of other jobs.

Hope this makes sense and looking forward to learning what's the best way of handling this.

All the best,
Oskar

P.S. Running Sidekiq 6.0.7

**Comment by mperham** [comment]
Tough to say. You could create seven queues, one per day, and weight them evenly so jobs are pulled randomly from days. You could [configure daily jobs to expire after 24 hours](https://github.com/mperham/sidekiq/wiki/Pro-Expiring-Jobs) so that next day jobs always take precedence and you don't duplicate work if the same work is enqueued each day.

**Comment by OskarEichler** [comment]
We do need the jobs to finish, so probably more queues is the way to go. What exactly is the downside of having too many queues? Thought I read somewhere that it's not recommended - would it be problematic to have 100+ queues?

Please let me know!

All the best,
Oskar

**Comment by mperham** [comment]
[I wrote a bit about it](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues). Many queues are especially bad with Sidekiq Pro's super_fetch. You can have many queues if you have just a few queues per Sidekiq process, that will scale fine.
