### ISSUE TITLE
Sidekiq::Pro::BasicFetch memory issue

### ISSUE THREAD

**Issue by liaden** [mperham/sidekiq#4652]
Ruby version: 2.7.1
Sidekiq / Pro / Enterprise version(s):
I was seeing it on 6.0.7 / 5.0.1 / 2.0.1
I upgraded to 6.1.1 / 5.1.1 / 2.1.1

We've noticed memory growth during times when our workers are bad and exceptions are thrown. To narrow this down, I was able to reproduce creating a simple worker that causes an error (with retry disabled).

I used `rbtrace` to invoke `GC.stat` to see change in usage:

|  | post boot | 1,000 | 10,000 | 25,000 |
| -- | -- | -- | -- | -- |
| heap_live_slots |  693223 | 914247 | 1226014 | 1639893 |
| heap_free_slots | 513 | 823 | 856 | 693 |

I also tried to compact memory with no impact using `rbtrace  -e '4.times { GC.start }; GC.compact }'`, similar to nakayoshi fork on puma to see if memory would be freed up.

I next ran with sidekiq idle, ran one passing worker, and then enabled `ObjectSpace.trace_object_allocations_start` with rbtrace. I kicked off 20 copies of the ErroringWorker, and then ran `rbtrace --pid $PID -e 'Thread.new{GC.start;require "objspace";io=File.open("/tmp/ruby-heap.dump", "w"); ObjectSpace.dump_all(output: io); io.close'`. 

I used https://gist.github.com/wvengen/f1097651c238b2f7f11d to load it into postgres to try to query and better understand what was going on.

Everything from the 20 job runs is on generation 57 because 58 is after `GC.start` and then the data being dumped.
```
mem_analysis=# select count(*), generation from space_objects group by generation;
```
 count  | generation
--------|------------
|   1122 |         57 |
|      7 |         58 |
| 577490 |          ¤ |

Find ruby objects and count by their types
```
mem_analysis=# select count(*), klass.name from space_objects instance join space_objects klass on klass.address = instance.klass where instance.generation = 57 and instance.type  in ('OBJECT') group by klass.name;
```
 count |           name
-------|--------------------------
|     3 | I18n::Config |
|     5 | IO::EAGAINWaitReadable |
|    20 | Set |
|     7 | Sidekiq::JobLogger |
|     7 | Sidekiq::JobRetry |
|    20 | Sidekiq::Pro::BasicFetch |
|     7 | Sidekiq::Processor |
|     3 | Timeout::Error |

Reading through the code on 6.0.7, I could see `(options[:events] || Sidekiq::Pro::Config).register(self)` which stores it in an array, and 

Showed a lot of arrays that were owning the the BasicFetch:
```
select parent.* from space_objects instance join space_objects klass on klass.address = instance.klass join space_object_references ref on ref.to_address = instance.address join space_objects parent on parent.id = ref.from_id where klass.name in ('Sidekiq::Pro::BasicFetch') and instance.generation = 57 and instance.type  in ('OBJECT');
```

 I monkey patched
```
class Sidekiq::Pro::ConfigListener
  def register(handler)
  end
end
```
to try to prove my hypothesis, and I saw memory usage in line with the empty worker that did nothing.

**config/sidekiq.yml**
```
---
:verbose: true
:concurrency: 5
:queues:
  - [default, 5]
  - [low, 5]
  - [mailers, 5]

development:
  :pidfile: tmp/pids/sidekiq.pid
  :concurrency: 5
  :logfile: log/sidekiq.log
```

**config/initializers/sidekiq.rb**
```
require "sidekiq/extensions/action_mailer"
require "sidekiq/web"

Sidekiq::Web.set :sessions, false

redis_config_file = Rails.root.join("config/redis.yml")

sidekiq_config = YAML.load(ERB.new(File.read(redis_config_file)).result)[Rails.env]&.with_indifferent_access

unless ENV["DISABLE_REDIS"]
  Sidekiq.configure_client do |config|
    config.redis = sidekiq_config
  end
end

Sidekiq.configure_server do |config|
  config.redis = sidekiq_config

  config.periodic do |mgr|
    # Cron format: <Minute> <Hour> <Day_of_the_Month> <Month_of_the_Year> <Day_of_the_Week>
    # For more details and examples: https://en.wikipedia.org/wiki/Cron

    # Daily at 20:00
    mgr.register("0 20 * * *", CleanupWorker)
  end
end
```

**Comment by mperham** [comment]
I don't understand how this is possible. I'm looking at master branch. Sidekiq::Pro::BasicFetch is a Module so how could there be 20 instances of it? The fetcher is instantiated once in sidekiq/launcher.rb and the same instance is used by all threads so it should be a singleton; it is not recreated for every new Processor instance.

I will make this change so we can't re-register the same Fetcher instance over and over:

```diff
+++ b/lib/sidekiq/pro/config.rb
@@ -1,4 +1,5 @@
 require "sidekiq/util"
+require "set"
 
 module Sidekiq::Pro
   Message = Struct.new(:verb, :payload)
@@ -31,7 +32,7 @@ module Sidekiq::Pro
     def initialize
       @thread = nil
       @done = false
-      @handlers = []
+      @handlers = Set.new
     end
 
```

**Comment by liaden** [comment]
Tested this locally and it does fix it! Thank you for the quick response.

**Comment by natematykiewicz** [comment]
@mikeperham, I wonder if something like Spring is being used, and so the process isn't being restarted but reforked without Copy On Write, and so every "restart" actually runs the initializer again over an old instance? I'm not sure if that's a logical theory or not.

**Comment by liaden** [comment]
I was running in a docker container between variations to match production
as closely as possible. There was no app restart without a docker-compose
down, but we do have spring in our Gemfile for development. For my
investigation, I did enable eager loading and other prod settings to keep
it close to production-like.

**Comment by liaden** [comment]
Looking at the changelog for sidekiq-pro, it does not include mention of this issue as an upcoming change. I don't know of anyway to point to a master branch of sidekiq pro to verify if the change is present but not referenced in the changelog, but I wanted to follow up just in case the fix is missing.

**Comment by mperham** [comment]
Yes, it will be in v5.2.0 coming soon. I've added an entry.

**Comment by trev** [comment]
Thanks for this @liaden 👍
