### ISSUE TITLE
Error loading `Rack::Request` inside `Sidekiq::Web::CsrfProtection`

### ISSUE THREAD

**Issue by jakemack** [mperham/sidekiq#4655]
Ruby version: ruby 2.6.3p62
Sidekiq / Pro / Enterprise version(s): 6.1.0, 6.1.1 (works in 6.0.7) / 5.1.1
Rails version: 6.0.3.2

We are using Rails 6.0.3.2 with zeitwerk autoloading enabled. When we attempt to delete a retry from the Sidekiq UI, we get `uninitialized constant Sidekiq::Rack::Request`. The issue appears to stem from adding 

```ruby
require 'sidekiq/rack/batch_status'
use Sidekiq::Rack::BatchStatus
```

to `config.ru` according to the configuration instructions in `lib/sidekiq/rack/batch_status.rb` in sidekiq-pro. It appears the latest changes aren't compatible with using `Sidekiq::Rack::BatchStatus`. I think simply scoping references to Rack to the top level will fix this incompatibility (https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web/csrf_protection.rb#L75 and https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web/csrf_protection.rb#L141)

**Comment by mperham** [comment]
If you run master, it will work. I'm renaming `Sidekiq::Rack::BatchStatus` to `Sidekiq::Pro::BatchStatus` in Pro 5.2+ as I don't want a Rack namespace within Sidekiq in the future.

**Comment by jakemack** [comment]
Great, thanks. We're no longer using `Sidekiq::Rack::BatchStatus` so I was able to remove it instead but I wanted to make sure the issue was reported in case I was the first one to stumble upon it.
