### ISSUE TITLE
Perform Appears to only Execute Intermittently

### ISSUE THREAD

**Issue by GuruKhalsa** [mperham/sidekiq#4657]
Ruby version: 2.4.5
Sidekiq / Pro / Enterprise version(s): 3.3.5

Please include your initializer and any error message with the full backtrace.
```
require 'sidekiq'
require 'sidekiq-status'

redis_url = AppService::Session.redis.base_url
namespace = AppService::Session.build_sidekiq_namespace

Sidekiq.configure_client do |config|
  config.redis = {
    url:        redis_url,
    namespace:  namespace
  }

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end

  # Get rid of Sidekiq printing to stdout in testing
  if Rails.env.test?
    Sidekiq.logger.level = Logger::WARN
  end
end

Sidekiq.configure_server do |config|
  config.redis = {
    url:        redis_url,
    namespace:  namespace
  }

  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
  end

  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end

  config.error_handlers << proc do |ex, context|
    AirbrakeNotifier.notify(ex, parameters: context)
  end
end

Sidekiq::Web.set :sessions, false
```

Are you using an old version?
Yes.
Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes, I did not see a fix.

Hi Mike, thanks for all of the amazing work you've done and continue to do on Sidekiq!

I'm working on a legacy project and, in a deployed (staging) environment, the jobs are all successfully enqueued and all successfully processed but for some jobs about half of the time the `perform` method doesn't appear to be getting executed despite it being processed successfully.  To help troubleshoot, the first line executed in that job's `perform` method is a logging event and when the job is not executed successfully, nothing appears in the logs.  The other half of the time the same job's perform method is executed successfully. 

Nothing out of the ordinary appears to be happening in Redis either.  The correct job details are getting pushed to the correct queue list and items are popped off as expected.  And, as mentioned before, all jobs appear to be recognized in the Sidekiq dashboard as enqueued and then processed, even when they don't seem to execute `perform`.

Just curious if you have any thoughts on what might be going on on the Sidekiq side of things here.

I really appreciate your time and any help/insight you can provide.

**Comment by mperham** [comment]
I’d guess you have a second Sidekiq process.

**Comment by GuruKhalsa** [comment]
Thank you so much Mike, your answer helped me track down what I believe is causing the issue!  There was a separate environment that was pointing to the same Redis instance, and I believe they were processing each other's jobs.

Thanks again!
