### ISSUE TITLE
on_death callback not propagating options

### ISSUE THREAD

**Issue by derfred** [mperham/sidekiq#4658]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
Sidekiq Pro

Please include your initializer and any error message with the full backtrace.

I'm creating a batch with `complete` and `death` callbacks:
```
        batch = Sidekiq::Batch.new

        #.....

        batch.description = "Report #{report_klass_name} id=#{batch.bid}"
        batch.on(:complete, Run, run_options: run_options, args: args)
        batch.on(:death,    Run, run_options: run_options, args: args)
        batch.jobs do
           #....
        end
```

The `on_death` callback however does not receive the options I pass in. Looking at the retry queue the following data is encoded which does not include the additional options:

![Sidekiq_Enterprise](https://user-images.githubusercontent.com/24133/89031995-efe86880-d333-11ea-9572-daf00d336f77.png)

**Comment by mperham** [comment]
Options handling for all callbacks is identical. Option data is stored as part of the batch record in Redis, not in the job arguments, so it can expire or be reclaimed by Redis after the default TTL of 30 days.

As the issue template asks, show me your initializer and tell me your versions.

**Comment by derfred** [comment]
sorry my bad. The issue was in my code, which I realized once I turned on backtrace capture
