### ISSUE TITLE
Push jobs after DB transactions committed

### ISSUE THREAD

**Issue by donaldong** [mperham/sidekiq#4660]
### Motivation
In an ActiveRecord DB transaction, people might want to push Sidekiq jobs to Redis. If the transaction failed, all the database side operations will rollback; but we cannot rollback the API calls to Redis.

It would be helpful if Sidekiq provides an option to defer job pushing until DB transactions have committed successfully -- if the transaction failed, the jobs would be canceled.

I'd be happy to submit a PR, but I noticed the `raw_push` method could be overwritten in Sidekiq-Pro for the Pro features. I can still check if the method is overwritten in the opensource version, tho checking for a Pro overwrite in the opensource version seems a bit odd.

Thoughts?

**Comment by mperham** [comment]
I'd be curious to see a PR if you want to submit something. If possible it should work with Rails 5+. don't worry about Sidekiq Pro, that would be my work if we decide to proceed.

**Comment by axos88** [comment]
@donaldong Take a look at the `after_commit` gem
