### ISSUE TITLE
sidekiq 6.1.1 / Sidekiq Pro v5.1.1 is slower than Sidekiq v5.2.7 / Sidekiq Pro v4.0.5 ?

### ISSUE THREAD

**Issue by ezhenezhen** [mperham/sidekiq#4662]
**Ruby version:** 2.6.2

```
# frozen_string_literal: true

require 'sidekiq'
require 'sidekiq/web'

# Sidekiq::Logging.logger = nil

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == %w[asdf fdsa]
end

Sidekiq::Web.set(:sessions, false)

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }
  config.super_fetch!

  config.on :startup do
    # Clear any connections that might have been obtained before starting
    # Sidekiq (e.g. in an initializer).
    ActiveRecord::Base.clear_all_connections!

    # Load rake tasks for workers
    Rails.application.load_tasks
  end
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'] }
end
```

same machine, 2 processes 25 threads, same records set, same env - cache cleared

**old sidekiqs with pid produce:**
**records per hour rate** 23268
**items per second rate** 873

**old sidekiqs as a service produce:**
**records per hour rate** 28839
**items per second rate** 1081

**new sidekiqs as a service produce:**
**records per hour rate** 21248
**items per second rate** 797

any clue what may be wrong or is that the expected behavior?

**Comment by mperham** [comment]
No clue. I have no idea what you are doing.
