### ISSUE TITLE
I hope to add JID to the list of scheduled programs

### ISSUE THREAD

**Issue by LPFpengfei** [mperham/sidekiq#4663]
Ruby version: 2.6.5
Sidekiq / Pro / Enterprise version(s): 5.2.8

guys, can we add the JID presentation to the list? Just like the busy View, we can't tell which one we want from the data on the page right now, and if the JID exists, we can just go through the page and map out the data that we're planning.

**Comment by mperham** [comment]
Why do you need to see the JID? We don't show it anywhere else; it's an internal identifier you might use with APIs but if you need to know the JID in the Web UI, I'd like to understand your workflow better.

> we can just go through the page and map out the data that we're planning.

Can you be more specific?

**Comment by LPFpengfei** [comment]
We are making a function to send information regularly. I will send a message at some time in the future, so I created a worker: Sometime in the future, may be an hour a week will be sent the written text, suddenly I don't want to send this message, or want to amend the sending time, so I through the ```jid``` to query data that exist in the scheduled, of course, I can find the worker by ```find_job```, but I still hope that when I was trying to identify problems can be through the web UI to determine a list of the worker and I plan to one to one correspondence

**Comment by mperham** [comment]
The JID is part of the link in the row. If you want to delete or run a scheduled job, you should be using the API.
