### ISSUE TITLE
Unique jobs is incompatible with ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper 

### ISSUE THREAD

**Issue by nertzy** [mperham/sidekiq#4667]
Ruby version: 
```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```
Sidekiq / Pro / Enterprise version(s): 
```
  * sidekiq (6.1.1)
  * sidekiq-ent (2.1.1)
  * sidekiq-pro (5.1.1)
```

I'm using Active Job and Sidekiq Enterprise.

In my Rails initializer, I added:
```ruby
Sidekiq::Enterprise.unique! unless Rails.env.test?
```

In a job class, I added:
```ruby
class MyJob < ApplicationJob
  sidekiq_options unique_for: 10.minutes
end
```

When I add a debugger to `Sidekiq::Enterprise::Unique::Client#call`, I see that if I enqueue the same job with the same arguments multiple times, the value of the `ctx` string is unique each time, thus defeating the hash comparison.

Particularly, the `job_id` and `enqueued_at` arguments are pretty much guaranteed never to repeat.

Example values for `ctx`:
```
ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper|default|{"job_class"=>"MyJob", "job_id"=>"df8f34b8-6d46-40f1-87b4-ab83fc466a44", "provider_job_id"=>nil, "queue_name"=>"default", "priority"=>nil, "arguments"=>[48587, {"_aj_ruby2_keywords"=>[]}], "executions"=>0, "exception_executions"=>{}, "locale"=>"en", "timezone"=>"UTC", "enqueued_at"=>"2020-08-11T20:12:52Z"}

ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper|default|{"job_class"=>"MyJob", "job_id"=>"1854204b-c0d0-486c-9d65-b71f866ebdf1", "provider_job_id"=>nil, "queue_name"=>"default", "priority"=>nil, "arguments"=>[48587, {"_aj_ruby2_keywords"=>[]}], "executions"=>0, "exception_executions"=>{}, "locale"=>"en", "timezone"=>"UTC", "enqueued_at"=>"2020-08-11T20:12:56Z"}
```

My plan is to patch this behavior in my own application, but I wanted to report it here as well.

Thanks!

**Comment by mperham** [comment]
Yes, that's one of the commercial features that doesn't work with ActiveJob today. If you have suggestions for how to fix, I'd love feedback. Maybe it should warn that it doesn't work?


https://github.com/mperham/sidekiq/wiki/Active-Job#commercial-features

**Comment by nertzy** [comment]
I'm going to experiment with some ideas and report back.

**Comment by nertzy** [comment]
Perhaps `sidekiq_options` could allow for a way to pass in a Proc to override the logic that takes the arguments and returns a unique object.

It's not incredibly elegant, but it would look something like:
```ruby
class MyJob < ApplicationJob
  sidekiq_options(
    unique_for: 10.minutes, 
    unique_by: -> (job) { job["args"][0].reject { |key, value| %w[job_id enqueud_at].include?(key) } }
  )
end
```
It would be even better if the uniqueness algorithm checked for a method on the Worker instance to get the arguments to consider, and that this method could be defined on ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper to return the appropriate subset of arguments.

**Comment by nertzy** [comment]
Here's the workaround we came up with, for now: https://gist.github.com/nertzy/74d4fbab3440d56b8bda2241b4eb0c4e

**Comment by mperham** [comment]
I'm working on official support in the next release and will update this issue with progress.

**Comment by mperham** [comment]
I've got things working but there are some caveats:

```ruby
SomeJob.perform_later(:foo)
SomeJob.perform_later("foo")
```

Should these result in the same or different locks? Sidekiq enforces JSON data types for arguments but Rails allows more flexible arguments which can result in the same underlying lock because they devolve to the same JSON data when serialized. Right now I'm doing the simplest thing possible.

**Comment by nertzy** [comment]
I think that the simplest thing would be to treat symbols and strings the same, and perhaps warn about that on the wiki page. 

I can't imagine anyone using a string and symbol in the same position in a job's arguments and actually performing different work.
