### ISSUE TITLE
How to enable eager_load in just the Sidekiq server

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#4670]
I want to always enable eager_load in just the Sidekiq server. Is it the right way to call `Rails.application.eager_load!` in the `Sidekiq.configure_server` block? I would like to know if there is a better way to do this.

```ruby
# config/initializers/sidekiq.rb

Sidekiq.configure_server do |config|
  Rails.application.eager_load!
  # ...
end
```

**Comment by mperham** [comment]
That block is the right way to run code within only the Sidekiq process but I don't know if that's the best way or proper time to eager load.

**Comment by ts-3156** [comment]
Thanks for your advice!

I'm sorry I didn't explain it well enough. My application creates threads in a Sidekiq worker, so the Sidekiq server often hangs in that code on the development environment. I suppose I could just explicitly require the classes I need, but since there are so many classes involved, I wanted to solve the problem all at once by enabling eager_load.

**Comment by mperham** [comment]
I would put it in config/environments/development.rb using the `Sidekiq.server?` method.

config.eager_load = Sidekiq.server?

**Comment by ts-3156** [comment]
Thank you for showing me how to do it even better. I didn't know about `Sidekiq.server?`. I will use this API to solve the problem.
