### ISSUE TITLE
Sidekiq web interface logs out users on production

### ISSUE THREAD

**Issue by lacostenycoder** [mperham/sidekiq#4678]
Ruby version: ruby 2.6.4p104
Sidekiq / Pro / Enterprise version(s):  sidekiq-pro (4.0.3)

Please include your initializer and any error message with the full backtrace.  No backtraced, just user is logged out as soon as hitting the route. 

```ruby
#routes.rb
  authenticate :user, -> (u) { u.has_role? :super_admin } do
    mount PgHero::Engine =>  '/pghero'
    mount Sidekiq::Web  => '/sidekiq'
  end
```

```ruby
#config/initializers/sidekiq.rb
require 'sidekiq-pro'
require 'sidekiq/web'
require 'sidekiq-status/web'
require 'sidekiq-scheduler/web'
require 'sidekiq-status'
require 'sidekiq-limit_fetch'
require 'sidekiq/middleware/server/influxdb' if ENV['INFLUX_DB_URL'].present?

Sidekiq::Web.set :sessions, false
Sidekiq::Extensions.enable_delay!

SIDEKIQ_NOTIFY_LIMITS = {
  'searchkick' => ENV['SIDEKIQ_SEARCHKICK_QUEUE_NOTIFY'],
  'default' => ENV['SIDEKIQ_DEFAULT_QUEUE_NOTIFY'],
}.freeze

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDISS_URL'], network_timeout: 5 } if ENV['REDISS_URL']
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
    chain.add Sidekiq::NotifyMiddleware
  end
end

Sidekiq.configure_server do |config|
  config.on(:startup) do
    if Rails.env.production?
      Sidekiq.schedule = YAML.load_file(Rails.root.join('config/sidekiq_scheduler.yml'))
      Sidekiq::Scheduler.reload_schedule!
      text = "Sidekiq/App started on #{ENV['BASE_PATH']} #{ENV['SERVER_NAME'].try(:upcase)} SERVER\n\n"
      text += `git log`
      SlackNotifier.new(text: text, channel: 'server_status').notify
    end
  end

  config.redis = { url: ENV['REDISS_URL'], network_timeout: 5 } if ENV['REDISS_URL']
  config.server_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
    chain.add Sidekiq::Cable::ServerMiddleware
  end
  config.client_middleware do |chain|
    # accepts :expiration (optional)
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 30.minutes # default
  end

  if ENV['INFLUX_DB_URL'].present?
    config.server_middleware do |chain|
      except = [
          CleanupStaleDataWorker, DynamicWorker,
          FakePatientsWorker, SeedsWorker
      ]
      chain.add Sidekiq::Middleware::Server::InfluxDB,
                influxdb_client: InfluxDB::Client.new(url: ENV['INFLUX_DB_URL']), # REQUIRED
                # series_name: 'sidekiq_jobs',                  # optional, default shown
                # retention_policy: nil,                        # optional, default nil
                # start_events: true,                           # optional, default true
                tags: { application: 'Thoroughcare' },          # optional, default {}
                except: except                                  # optional, default []
    end
  end
end
```

Are you using an old version?
Have you checked the changelogs to see if your issue has been fixed in a later version?
I see this issue is closed https://github.com/mperham/sidekiq/issues/2185  but not in changelog and not sure what code supposedly fixed it.

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
Would you please update the Sidekiq Pro and Sidekiq gems as there have been significant changes to the web UI.

**Comment by lacostenycoder** [comment]
We're still tied to Rails 4.2 and we also use these gems.  We have the upgrade to Rails 5 close to done and will eventually go to 6.  Just way behind on our stack. Are we SOL until we upgrade Rails? 

```
#Gemfile
source "https://gems.contribsys.com/" do
  gem 'sidekiq-pro', require: false
end
gem 'request_store-sidekiq', '~> 0.1', require: false
gem 'sidekiq-limit_fetch', '~> 3.4', require: false
gem 'sidekiq-scheduler', require: false
gem 'sidekiq-status', '~> 1.0', require: false
gem 'sidekiq-unique-jobs', '~> 5.0'
gem 'sidekiq-influxdb', require: false
```

**Comment by mperham** [comment]
I generally support two major versions, so Rails 6 and Rails 5. Add this:

> Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

and see if that helps.

**Comment by lacostenycoder** [comment]
We upgraded to Rails 5 do we still keep both of these?
```
Sidekiq::Web.set :sessions, false
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
```

**Comment by mperham** [comment]
Rails 5.what? Be specific.

**Comment by mperham** [comment]
See this: https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden

**Comment by lacostenycoder** [comment]
Rails 5.2.4.1 thanks, I'll refer to the wiki

**Comment by mperham** [comment]
Rails 5.2 changed the API, try:

Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]

**Comment by radilr1** [comment]
In the console when we run:
```
Rails.application.secrets[:secret_key_base]
=> "41115636f26ff78dfdd......."
Rails.application.credentials[:secret_key_base]
=> nil
```
Interesting is that on our local environment it works. On our test server we can login, but as soon as another user logs in it logs out the first user.  On our production environment (multiple servers with load balancer) it logs out the user as soon as they try to open the web interface.
Also interesting that it works the same way no matter if we use `Rails.application.secrets` or `Rails.application.credentials`. Seems like it doesn't take that configuration into account. Could it be related with the session storage? we are using `active_record_store`

We are also using pghero which we mount in the `routes.rb` file the same way and we have the same behavior there.
