### ISSUE TITLE
Heroku: Is it possible to select dyno type instead of the default?

### ISSUE THREAD

**Issue by echan00** [mperham/sidekiq#4679]
My web application processes documents uploaded by users using sidekiq on heroku. Less than 5% of documents are too large and my heroku workers die without warning due to out of memory issues.

Is it possible to boot different worker dynos in sidekiq based on the upload size? 

For example, one can specify one-off dyno types by using `--size`
```
heroku run rails c --size=standard-2x rake heavy:job
heroku run rails c --size=performance-l rake heavy:job
```

**Comment by mperham** [comment]
This is more of a Heroku CLI question, Sidekiq has no influence on the dyno it runs on. Maybe `heroku run --help` will explain?

**Comment by echan00** [comment]
Alright thanks!
