### ISSUE TITLE
Booting up a sidekiq worker raises an error with paused queues.

### ISSUE THREAD

**Issue by Adithya-copart** [mperham/sidekiq#4681]
**Ruby version:** JRuby 9.2.9.0
**Sidekiq / Pro / Enterprise version(s):** sidekiq-pro, '5.1.1'

Is it possible to support booting up a worker with paused queues?
If not, can the error message be improved?

**Initializer:**
```
require 'bundler/inline'

gemfile do
  gem 'activesupport', require: 'active_support/all'
  gem 'sidekiq-pro', '5.1.1'
end

require 'sidekiq/api'

q = Sidekiq::Queue.new('test_queue')
p "Paused? #{q.paused?}"
q.pause!
p "Paused? #{q.paused?}"

# Bootup Sidekiq
require 'sidekiq/cli'
cli = Sidekiq::CLI.instance

# Configure Sidekiq
Sidekiq.configure_server do |config|
  config.super_fetch!
end

Sidekiq::Client.reliable_push!

require 'tempfile'
random_file = Tempfile.new(['', '.rb'])

cli.parse(['sidekiq', '-c', '1', '-r', random_file.path, '-q', 'test_queue'])
cli.run

```

**Error:**
```
2020-08-27T05:57:07.821Z pid=91496 tid=1y2k INFO: Running in jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-b08 +jit [darwin-x86_64]
2020-08-27T05:57:07.823Z pid=91496 tid=1y2k INFO: Sidekiq Pro 5.1.1, commercially licensed.  Thanks for your support!
2020-08-27T05:57:08.051Z pid=91496 tid=1y2k INFO: Starting processing, hit Ctrl-C to stop
2020-08-27T05:57:08.053Z pid=91496 tid=1y2m INFO: SuperFetch activated
2020-08-27T05:57:08.132Z pid=91496 tid=1y28 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"heartbeat"}
2020-08-27T05:57:08.133Z pid=91496 tid=1y28 WARN: Redis::CommandError: ERR wrong number of arguments for 'sadd' command
```

**Are you using an old version?**
No

**Have you checked the changelogs to see if your issue has been fixed in a later version?**
N/A. Using latest.

**Comment by mperham** [comment]
I think Your Redis version is too old.

**Comment by Adithya-copart** [comment]
Tried with `redis 6.0.5` and still the same.
```
$ docker run -p 6379:6379 -d redis:latest && ruby sidekiq_test.rb 
...
2020-08-27T06:50:54.298Z pid=93241 tid=1zvl WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"heartbeat"}
2020-08-27T06:50:54.299Z pid=93241 tid=1zvl WARN: Redis::CommandError: ERR wrong number of arguments for 'sadd' command
``` 
An empty array is being passed to `sadd` during heartbeat which is raising the `ArgumentError`.

**Comment by mperham** [comment]
That’s not a supported use case but I’ll look into this tomorrow. Sounds like a bug.

**Comment by mperham** [comment]
I think trying to boot Sidekiq by hand like that isn't supported and breaks some internal state. Here's a more stable solution:

```ruby
> ruby -e 'require "sidekiq/pro/api";puts Sidekiq::Queue.new("test_queue").pause!'
> bundle exec sidekiq -q test_queue
```

**Comment by Adithya-copart** [comment]
@mperham I can replicate the issue with super fetch enabled using the mentioned approach. Maybe you missed enabling super fetch as the worker clearly boots without super fetch enabled.

The hacky script was my attempt to demonstrate the issue, we boot our worker process using `bundle exec sidekiq` or `bin/sidekiq` where we encountered this issue.

**Comment by mperham** [comment]
I've run the commands I listed and they work perfectly for your described use case: the queue is paused when Sidekiq boots with super_fetch enabled.

Sidekiq does not have a supported API for starting your own Sidekiq instance within a Ruby process. Your example code will not work; you must use the `sidekiq` binary.

**Comment by Adithya-copart** [comment]
> I've run the commands I listed and they work perfectly for your described use case: the queue is paused when Sidekiq boots with super_fetch enabled.

@mperham I spent some more time to look into this. The error appears only in JRuby for me and _could_ be the reason you did not see it.

The `@queues` ivar in `super_fetch.rb` is mutated before `register_myself` in JRuby and after `register_myself` in MRI.
If I update `super_fetch.rb#238` in `5.1.1` to use `get_queues(@options)`, the error is gone.

**Comment by Adithya-copart** [comment]
I was able to reproduce in JRuby with the initial script or the stable solution you suggested by supplying a initializer to enable super_fetch:

```
> ruby -e 'require "sidekiq/pro/api";puts Sidekiq::Queue.new("test_queue").pause!'
> bundle exec sidekiq -r initializer_with_super_fetch -q test_queue
```

**Comment by mperham** [comment]
I've already committed the change to use get_queues so your monkey patch is correct.
