### ISSUE TITLE
Delete OOM jobs?

### ISSUE THREAD

**Issue by donaldong** [mperham/sidekiq#4683]
Hi,

Currently, jobs that run out of memory will be recovered later by sidekiq-pro workers. If the jobs are bound to OOM, I think it'd be nice to be able to delete them from the private queue (either via UI/API).

What do you think?

**Comment by mperham** [comment]
That has already been implemented but not released, see the pro changelog.

**Comment by donaldong** [comment]
Ah, thanks @mperham!
