### ISSUE TITLE
Sidekiq Pro: queue not pausing

### ISSUE THREAD

**Issue by Loschcode** [mperham/sidekiq#4684]
Ruby version: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]
Rails version: Rails 5.2.4
Sidekiq / Pro / Enterprise version(s): 5.0.1

When I click on pause on the Sidekiq dashboard, or programmatically pause the queues it has no effect. I've followed this documentation https://github.com/mperham/sidekiq/wiki/Pro-API

And I've added this configuration https://github.com/mperham/sidekiq/wiki/Reliability

```
2020-09-03T14:55:33.359Z pid=9206 tid=oup3qi7re INFO: Booted Rails 5.2.4 application in development environment
2020-09-03T14:55:33.359Z pid=9206 tid=oup3qi7re INFO: Running in ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]
2020-09-03T14:55:33.359Z pid=9206 tid=oup3qi7re INFO: Sidekiq Pro 5.0.1, commercially licensed.  Thanks for your support!
2020-09-03T14:55:33.361Z pid=9206 tid=oup3qi7re INFO: Starting processing, hit Ctrl-C to stop
2020-09-03T14:55:33.362Z pid=9206 tid=oup33x0ea INFO: SuperFetch activated
```

I don't think it ever worked on our codebase but we need this feature. What could be the problem?

**Comment by mperham** [comment]
Have you tried v5.1.1?

**Comment by Loschcode** [comment]
I've just upgraded to 5.1.1 on my local machine but it still doesn't work, the effect is the exact same as when I click on "pause" it has no effect from the dashboard, I've also tried programmatically

```
[3] pry(main)> q = Sidekiq::Queue.new('critical')
=> #<Sidekiq::Queue:0x00007fe4cb12fe50 @name="critical", @rname="queue:critical">
[4] pry(main)> q.pause!
=> false
[5] pry(main)> q.paused?
=> false
```

What could I do to troubleshoot this?

**Comment by mperham** [comment]
In pry, you need to make sure you require `sidekiq/pro/api`.

**Comment by Loschcode** [comment]
I've just tried, sadly it still doesn't change the end result

**Comment by mperham** [comment]
I can't explain then.

**Comment by Loschcode** [comment]
Ok I've investigated much more and found this was some other Sidekiq related library which was breaking this feature. There's no warning to be found but you should know about it https://github.com/sensortower/sidekiq-throttled

```
gem 'sidekiq-throttled', '~> 0.8.2'
```

I'll try to play with new versions of the same gem, but worst case scenario I'll have to remove it, is there any alternative you can think of which would do the job properly? (throttling)

Thanks

**Comment by mperham** [comment]
Faktory Enterprise implements (queue throttling](https://github.com/contribsys/faktory/wiki/Ent-Throttling). Sidekiq cannot implement it in a reliable and scalable manner.
