### ISSUE TITLE
Sikekiq Pro Batch Jobs Forever Pending

### ISSUE THREAD

**Issue by berniechiu** [mperham/sidekiq#4687]
Hi, we're on Sidekiq Pro plan and first time using the batch feature, interestingly is, if we have more than two batch jobs, the batch queue seems to stuck on pending forever, not really sure why and there're no clear error message. While if it's 1 or 2 with the same code, it actually works somehow! So weird!

As you can see in the image only jobs above 3 are in pending states forever

![Screen Shot 2020-09-07 at 5 59 22 PM](https://user-images.githubusercontent.com/2749593/92376230-dc030400-f134-11ea-9e96-54205ab92eb3.png)

Ruby version: 2.6.2
Rails version: 5.2.5.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.2.10, Pro 3.7.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```yaml
---
:concurrency: 5
:queues:
  - ["default", 1]
  - ["pdf_grouping", 1]

:limits:
  pdf_grouping: 6
```

**Comment by mperham** [comment]
I don't support Sidekiq 4 anymore, only current and previous major version, you'll need to upgrade to something more recent. It's quite possible a later version has fixed your problem. All that said, I've never seen this behavior.

**Comment by berniechiu** [comment]
Ok i'll try to upgrade to see if it occurs again, it actually only occurs in some of our test servers
