### ISSUE TITLE
Request: Licence Expiration in Web UI

### ISSUE THREAD

**Issue by dbrezack** [mperham/sidekiq#4688]
It would be nice to see Pro/Enterprise licence expiration date in the web user interface so developers can be more cognizant of when to renew a licence. 

Currently an email gets sent to purchaser, but this is not always available especially in bigger companies.

Another possible and easier solution might be a warning on the install step that the licence is soon to expire.

**Comment by mperham** [comment]
After thinking about this for a few minutes I realized I can implement a good portion of this but it wouldn't work in your case.

I can't provide licensing info for invoiced customers; that info is only manually accessible to me in Quickbooks. Stripe has a great API for retrieving subscription details but those larger customers are literally paying more so they don't have to pay with credit card via Stripe. Unfortunately that includes your license.

**Comment by dbrezack** [comment]
Hmmmm yeah that would be an issue looking at the key there doesn't seem to be any information regarding expiration date like a JWT. 

Is there anything special encoded into the gem itself ?

**Comment by mperham** [comment]
Nope.

**Comment by dbrezack** [comment]
Darn, Well I'm all out of ideas, I'll close this ticket to keep the board clean thanks for taking a look into this @mperham
