### ISSUE TITLE
Feature: Be able to search in batches 

### ISSUE THREAD

**Issue by heldopslippers** [mperham/sidekiq#4689]
For Sidekiq Pro (and possibly Enterprise as well), It would be amazing to be able to search in batches. 
I think it would not be difficult to use the same search that is already used in for example planned jobs. 

We currently have about 10.000 batches, being able to just search on batch name would be amazing.

**Comment by mperham** [comment]
You can search for BID but you can’t use multiple terms. Is that what you want, “search for jobs matching X within batch Y?”

**Comment by heldopslippers** [comment]
I am not sure if this is actually possible. 

It is not about jobs, but about the Sidekiq Pro batches. 
We give every batch a specific description (based on what tenant we are doing stuff for). At peak times there are 10K batches running. 

If we need to know what is happening for a certain client we have no way to see this in Sidekiq. Having a very basic search functionality on `/sidekiq/batches` would be amazing (just like we have in jobs).

**Comment by mperham** [comment]
I’m not sure it’s possible either. I don’t recall the internal data structures and if we can use SCAN with them. I will check in a few days when I can breathe the Oregon air again.

**Comment by mperham** [comment]
Unfortunately the batch description is not stored in a way that Redis can search, it's only there for display at the moment.

**Comment by heldopslippers** [comment]
I was already afraid of this. 
It still could be possible with some kind of regex search, but it probably won't be very efficient though. 

If I find a solution, I will let you know. You can close this for now if you like.
