### ISSUE TITLE
Jobs stucking in busy process

### ISSUE THREAD

**Issue by nitin-rvm** [mperham/sidekiq#4691]
Hello,

This is my first question on github so don't know much about how to ask and what details I need to share about my issue, sorry for that.

The issue I am having with my sidekiq is sometimes the processes are stucked on the busy section and did not execute, its not happening with all process. when I run those stucked worker code using command line on the server then emails are going out successfully.

Here are configuration details:
rails version: 3.2.13
ruby version: 2.0.0
sidekiq gem version: 3.3.4

**Comment by mperham** [comment]
Those Ruby, Rails and Sidekiq versions are 5 to 10 years old, you’ll need to run something modern for support.

**Comment by nitin-rvm** [comment]
I am using it for a live project and I need to fix it before upgrade, I'll upgrade my project but now my app users are not able to send the email, any alternate way to fix it, thanks.

**Comment by mperham** [comment]
Did you read the problems and troubleshooting wiki page? Look into the TTIN signal.
