### ISSUE TITLE
Sidekiq Pro: Where is the job executed in a multi-worker environment

### ISSUE THREAD

**Issue by MadBomber** [mperham/sidekiq#4697]
Running a multi-worker sidekiq pro environment where each worker is in a separate container.

I have a background job, GEN, which creates a file and stores it in the local filesystem.  The job then does a perform_async on another job, UPLOADER, passing it the file path of file created by job GEN.

Sometimes it works and sometimes it does not.  The assumption is that when it works, its because both jobs, GEN and UPLOADER, are being executed within the same sidekiq-worker process.  When it does not work I assume that its because GEN was executed in one sidekiq-worker and UPLOADER was executed in a different sidekiq-worker... and the two workers do not share a common local file system.

How can job GEN invoke job UPLOADER in a way that constrains UPLOADER to the same sidekiq-worker that is currently processing job GEN?

**Comment by mperham** [comment]
read this. https://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
