### ISSUE TITLE
Ability to have some exceptions kill the job without retries

### ISSUE THREAD

**Issue by janko** [mperham/sidekiq#4698]
I know that in https://github.com/mperham/sidekiq/issues/2072 it was said that Sidekiq doesn't accept new features for its retry system, but I really don't know how to solve this problem myself.

I have a worker which executes some pretty heavy queries, and I want any transient exceptions (e.g. Elasticsearch timeout) to be retried normally, but for all other exceptions that will most likely not succeed I want to send the job straight to Dead set. Note that this is different than scenario in https://github.com/mperham/sidekiq/issues/2072, where the author wanted to ignore an exception and *not* have it kill the job.

Is there a way to achieve this with Sidekiq?

I'm currently experimenting with ActiveJob, which does have this feature. However, the problem is that ActiveJob's retries seem to stack on top of Sidekiq's, and for my worker it's really important not to be retried too many times, because of the load it puts on the database. I know I could set `sidekiq_options retries: 0`, but I'm currently using Sidekiq 4.2 which doesn't provide `sidekiq_options` for ActiveJob (and I cannot easily upgrade to Sidekiq 6.x, because it removes daemonization that our deployment system is relying on).

**Comment by mperham** [comment]
You can upgrade to Sidekiq 5 which has a rewritten job retry subsystem. Sidekiq 4 is no longer officially supported.

There's no way to dynamically send to the Dead set. You can rescue an exception and simply return so the job is counted as a success and discarded.

When creating the ActiveJob, you could use a client middleware to modify the `retry` count at the last second before the ActiveJob wrapper is pushed to Redis.

**Comment by janko** [comment]
Thank you for the reply. We'll definitely upgrade to latest Sidekiq, and then go from there. A middleware approach should be feasible I think. I will report back with what we've come up with.
