### ISSUE TITLE
Child jobs not enqueuing with Sidekiq Pro batches at larger scales

### ISSUE THREAD

**Issue by michberr** [mperham/sidekiq#4700]
Ruby version: 2.6.5
Rails version: 5.2.3
Sidekiq / Pro / Enterprise version(s): Pro 5.0.0, sidekiq 6.0.7

I am using the Batch feature in Sidekiq Pro to process rows from a large-ish CSV (~300k rows)
```
class ParentWorker
  include Sidekiq::Worker
  
  def perform(file)
    batch = Sidekiq::Batch.new
    batch.jobs do
      CSV.foreach(file, headers: true) do |row|
        ChildWorker.perform_async(row['key'])
      end
    end
  end
end
```

The above code caused the child jobs to never be enqueued, but no exception was raised.  The code works perfectly well with smaller CSVs, but not larger ones.

What fixed the issue for me was swapping the batch block with the CSV iterator:
```
class ParentWorker
  include Sidekiq::Worker
  
  def perform(file)
    batch = Sidekiq::Batch.new
    
    CSV.foreach(file, headers: true) do |row|
      batch.jobs do
        ChildWorker.perform_async(row['key'])
      end
    end
  end
end
```

Can you provide any insight into why this is happening? 

Thank you

**Comment by mperham** [comment]
`batch.jobs` is atomic, it will push all jobs at once at the end to ensure atomicity. But Redis has a hard-coded command size limit. I'm 99% sure you're hitting that limit so Redis is returning an error.

Review this:

https://github.com/mperham/sidekiq/wiki/Batches#huge-batches

The proper solution is have parent worker split the CSV into chunks of 1000 rows and create a batch job for each chunk. Each chunk job can reopen the batch and add 1000 row jobs. In this manner, you should be able to scale a batch to Redis's RAM limit.

**Comment by michberr** [comment]
Got it! Thanks for the quick response
