### ISSUE TITLE
custom views 

### ISSUE THREAD

**Issue by jdteheran** [mperham/sidekiq#4701]
I am trying to customize a sidekiq view and I understand that I must copy the .erb files from the web folder and place them in my app. but I don't know where in my project I should place these files or how to configure the custom views to load.

"copy the views from the web folder to your application and modify them as you want, then set :views to that directory." 
this answer makes a lot of sense to me, but I don't know how to execute it. Issue https://github.com/mperham/sidekiq/issues/1418

**Comment by mperham** [comment]
That issue is six years old, it’s no longer relevant. If you can tell me more detail about what you’re trying to do I can give you better advice.

**Comment by jdteheran** [comment]
yes of course, what I am trying to do is add a new column with the creation date of the dead jobs.

**Comment by mperham** [comment]
What’s the use case, what is the business objective here?

**Comment by jdteheran** [comment]
The objective is merely informative. The idea is that the end user can see the creation date and not the last attempt, to be able to assign depending on the last date the person in charge of supporting the dead work.

**Comment by mperham** [comment]
Sidekiq doesn’t support custom views these days; trying to customize one view makes me want to understand how they all could possibly need to change. Perhaps the right thing to do here is to reestablish the ability to fork and customize views. Note that you can extend the web UI with your own custom tabs. Several third-party gems do this today.

**Comment by jdteheran** [comment]
ok, thanks

**Comment by ParthivSavani** [comment]
@mperham Is there any way we can get the memory size of each worker? Any command to check the size of job object?

**Comment by AndreiMz** [comment]
> I am trying to customize a sidekiq view and I understand that I must copy the .erb files from the web folder and place them in my app. but I don't know where in my project I should place these files or how to configure the custom views to load.
> 
> "copy the views from the web folder to your application and modify them as you want, then set :views to that directory."
> this answer makes a lot of sense to me, but I don't know how to execute it. Issue #1418


Copy all the views and place them wherever you want, for example I put them in app/views/sidekiq.

I require sidekiq web in my sidekiq.rb initializer (config/initializers/sidekiq.rb). If you override the default views your code should look something like this
``` 
require 'sidekiq/web'

# in my case it's Sidekiq::Web.set 'views', File.join(Rails.root, %w[app views sidekiq])
Sidekiq::Web.set 'views' , <your custom sidekiq view folder>
```
I managed to obtain custom text to display inside the views after restarting the app.
