### ISSUE TITLE
Dead job removed from dead queue on retry if class is removed

### ISSUE THREAD

**Issue by axos88** [mperham/sidekiq#4703]
Ruby version: 2.7.0
Rails version: n/a
Sidekiq / Pro / Enterprise version(s): 6.0.4

When retrying a job from the dead queue in the ui, if the enqueue fails, the job is lost forever.

Steps to reproduce:

  * Create a failing job, with `sidekiq_options retry: 0`
  * Wait for it to get into the dead queue
  * "accidentally" remove the worker class, restart the service
  *  Go to the sidekiq UI, retry the job

Expected:
  - The job fails to be retried (since the worker class does not exist anymore), and winds up back in the dead queue 

Actual:
  - Job is removed from the dead queue
  - HTTP Error is thrown in our face, due to unknown constant
  - Job data is lost.

**Comment by axos88** [comment]
I also wonder what happens to jobs that are in the retry queue when the worker class is removed. I would expect them to go into the dead queue, but I suppose the same thing happens to them as well

**Comment by mperham** [comment]
> HTTP Error is thrown in our face, due to unknown constant

Please include any error messages and backtracks with your issue.
