### ISSUE TITLE
Rails 6 Autoloading deprecation warning when using config.server_middleware

### ISSUE THREAD

**Issue by ndbroadbent** [mperham/sidekiq#4704]
Ruby version: ruby 2.6.5p114
Rails version: 6.0.3.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.1.2 (standard)

I'm seeing an autoload warning when I reference a class in my Sidekiq initializer. I'm not sure if I am doing something wrong, or if it would be possible to change the `config.server_middleware` block so that it is executed later?

Here is a repo that reproduces the warning: https://github.com/ndbroadbent/sidekiq_server_middleware_zeitwerk
Relevant commit: https://github.com/ndbroadbent/sidekiq_server_middleware_zeitwerk/commit/ee127c1e6edc24e5fafd21edfc77ccce59838ff1

* I added `config.autoload_paths << Rails.root.join('lib').to_s` to `config/application.rb`
* I set `config.log_level = :debug` in `config/environments/development.rb`

Steps to reproduce:

```bash
git clone https://github.com/ndbroadbent/sidekiq_server_middleware_zeitwerk.git /tmp/sidekiq_server_middleware_zeitwerk
cd /tmp/sidekiq_server_middleware_zeitwerk
bundle install
bundle exec sidekiq
```

You should see:

```
$ bundle exec sidekiq
DEPRECATION WARNING: Initialization autoloaded the constants Sidekiq::Middleware::Server and Sidekiq::Middleware::Server::ExampleMiddleware.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Sidekiq::Middleware::Server, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/ndbroadbent/code/sidekiq_server_middleware_zeitwork/config/environment.rb:5)


               m,
               `$b
          .ss,  $$:         .,d$
          `$$P,d$P'    .,md$P"'
           ,$$$$$b/md$$$P^'
         .d$$$$$$/$$$P'
         $$^' `"/$$$'       ____  _     _      _    _
         $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
         `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
                $$:         ___) | | (_| |  __/   <| | (_| |
                $$         |____/|_|\__,_|\___|_|\_\_|\__, |
              .d$$                                       |_|


2020-09-29T11:12:26.365Z pid=25376 tid=ox5hwnlzw INFO: Booted Rails 6.0.3.3 application in development environment
2020-09-29T11:12:26.365Z pid=25376 tid=ox5hwnlzw INFO: Running in ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
2020-09-29T11:12:26.365Z pid=25376 tid=ox5hwnlzw INFO: See LICENSE and the LGPL-3.0 for licensing details.
2020-09-29T11:12:26.365Z pid=25376 tid=ox5hwnlzw INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2020-09-29T11:12:26.366Z pid=25376 tid=ox5hwnlzw INFO: Booting Sidekiq 6.1.2 with redis options {}
2020-09-29T11:12:26.367Z pid=25376 tid=ox5hwnlzw INFO: Starting processing, hit Ctrl-C to stop
```

--------

I've tried using `chain.add 'Sidekiq::Middleware::Server::ExampleMiddleware'` (with a string instead of the class),  but this throws an error:

```
2020-09-29T11:23:55.660Z pid=31003 tid=owkajobvf ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2020-09-29T11:23:55.661Z pid=31003 tid=owkajobvf ERROR: undefined method `new' for "Sidekiq::Middleware::Server::ExampleMiddleware":String
```

I think I could also put `Rails.config.to_prepare` somewhere, maybe like this:

```

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    Rails.config.to_prepare do
      chain.add Sidekiq::Middleware::Server::ExampleMiddleware
    end
  end
end
```

But I tested this, and the middleware is being re-added multiple times when I change a file during development.

I can also require the file explicitly instead of using autoloading:

```
Dir.glob(Rails.root.join('lib', 'sidekiq', '**', '*.rb')).sort.each { |f| require f }

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::ExampleMiddleware
  end
end
```

This is what I'm currently doing in my application to avoid the warnings. But then I need to restart the server whenever I make a change to `Sidekiq::Middleware::Server::ExampleMiddleware` during development. It's not really a problem at all, but I'm just not sure if it's the right way to do it.

Would would be the recommended way to require / autoload the server middleware files for Sidekiq? Or would it work if you executed the `config.server_middleware` block later, e.g. in a `Rails.to_prepare` block?

Thank you!

**Comment by mperham** [comment]
Yep, the solution is to require. You can’t use auto loading in an initializer.
