### ISSUE TITLE
On shutdown, re-enqueued jobs are not re-enqueued correctly if the queue no longer exists

### ISSUE THREAD

**Issue by dnorth98** [mperham/sidekiq#4706]
Ruby version: 2.6.6
Rails version: 6.0.3
Sidekiq / Pro / Enterprise version(s): pro 4.0.5

Sidekiq is started with a `-t 25` flag

When sending the TERM signal to sidekiq while jobs are running, we have observed that they are not re-enqueued _if_ the queue no longer exists.

**Success case**:
- Jobs are running
- Queue still exists but may be empty (or have jobs in it...doesn't matter)
- Send sidekiq a TERM
- After the 25 seconds, Sidekiq sends the jobs back to redis (confirmed in logs and via the UI)
- Start sidekiq
- Jobs running at the time of TERM **are** re-run

**Failure case**:
- Jobs are running
- Delete the queue (whether there are jobs in it or not does not matter)
- Send sidekiq a TERM
- After the 25 seconds, Sidekiq thinks it is sending the jobs back to redis (the log messages are exactly the same as the success case)
- Jobs **do not** appear in the enqueued view / queue is not re-created
- Start sidekiq
- Jobs running at the time of TERM **are not** re-run 

**Expected behaviour**
As with adding a new job, the queue should be created if it does not exist and the jobs being re-enqueued should run when Sidekiq starts up again

**Use Case**
We create queue dynamically and run a cron task that periodically removes empty queues (empty meaning zero jobs).

**Comment by mperham** [comment]
Please show me your initializer.

**Comment by dnorth98** [comment]
Initializer:

```
# frozen_string_literal: true

Sidekiq.configure_server do |server_config|
    # redis
    server_config.redis = {
      url: ENV['SIDEKIQ_REDIS_URL'],
      network_timeout: 5 # https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud
    }
  
    # https://github.com/mhenrixon/sidekiq-unique-jobs#cleanup-dead-locks
    server_config.death_handlers << lambda { |job, _ex|
      SidekiqUniqueJobs::Digests.del(digest: job['unique_digest']) if job['unique_digest']
    }
  
    # spawn cron jobs
    if Nucleus.configuration.load_admin_modules
      rewind_schedule_file = 'config/sidekiq/rewind_cron.yml'
  
      Sidekiq::Cron::Job.load_from_hash YAML.load_file(rewind_schedule_file)
    else
      common_schedule_file = 'config/sidekiq/common_cron.yml'
  
      Sidekiq::Cron::Job.load_from_hash YAML.load_file(common_schedule_file)
    end
  
    server_config.server_middleware do |middleware_chain|
      middleware_chain.add Nucleus::Worker::Middleware::EligibilityPreHook
      middleware_chain.add Nucleus::Worker::Middleware::IgnoreUnauthorizedError unless ENV['SAAS_PLATFORM']&.downcase == 'platform_a'
    end
  end
  
  Sidekiq.configure_client do |config|
    config.redis = {
      url: ENV['SIDEKIQ_REDIS_URL'],
      network_timeout: 5 # https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud
    }
  end
  
  Sidekiq.options[:poll_interval] = 10
  
  # Controls how long a batch record "lingers" in Redis before expiring.
  # This allows APIs like Status#poll to check batch status even after
  # the batch succeeds and is no longer needed.  You can lower this
  # constant if you create lots of batches, want to reclaim the memory
  # and don't use polling.
  silence_warnings do
    Sidekiq::Batch::LINGER = 0 # https://github.com/mperham/sidekiq/issues/3083
  end
  
  Sidekiq.logger.level = Rails.application.config.log_level
  
  # https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Client
  Sidekiq::Client.reliable_push! unless Rails.env.test?
```

**Comment by mperham** [comment]
Deleting queues from Redis isn't a "normal" use case, I'm not clear why you're doing that but it shouldn't make a difference -- an empty queue does not exist in Redis because of how Redis implements Lists.

I notice you are not using `super_fetch` so deploys which kill the process before the jobs can be pushed back to Redis will be lost. I would first enable super_fetch.

**Comment by dnorth98** [comment]
> Deleting queues from Redis isn't a "normal" use case, I'm not clear why you're doing that but it shouldn't make a difference -- an empty queue does not exist in Redis because of how Redis implements Lists.
> 
> I notice you are not using `super_fetch` so deploys which kill the process before the jobs can be pushed back to Redis will be lost. I would first enable super_fetch.

Yeah, I can reproduce this just from the command line just by sending a TERM.  I have the `-t25` flag set but after that, there's nothing else sending a SIGKILL. There's no other processes involved around deployment.  As I said, if the queue still exists everything works just fine.

I'll run a quick test using super_fetch.

**Comment by mperham** [comment]
give me a simple reproduction and I’ll tell you what’s wrong.

**Comment by dnorth98** [comment]
> give me a simple reproduction and I’ll tell you what’s wrong.

I just tried this with superfetch enabled - same result.

The case is incredibly easy to reproduce:

- Have a job running (make sure it's a job that runs for a few mins - at least > the 25 second shutdown timer)
- Delete the queue (I'm just doing this in the web UI under Enqueued and hitting delete)
- Send sidekiq a TERM (just from the command line)
- After the 25 seconds, Sidekiq exits correctly

Result:
- Jobs do not appear in the enqueued view
- queue is not re-created
- Start sidekiq
- Jobs running at the time of TERM are not re-run

Again, if you follow these same steps but leave the queue, everything works just fine and jobs are re-scheduled.

Here's the log for this case.  You can see at the end that it at least thinks the jobs are going back...but they are not.

In the log

- the queue is called `thirdblink_devops`
- the test jobs are `ScheduleReportSidekiqStatsToCloudWatchWorker`. 

[sidekiq.log](https://github.com/mperham/sidekiq/files/5318608/sidekiq.log)

**Comment by mperham** [comment]
The issue is that the UI thinks the queue does not exist. It does in Redis,
it will reappear if you push another job to it normally. Follow your same
steps but at the end, push a new job to the same queue. The queue should
appear in the UI with both jobs.

**Comment by dnorth98** [comment]
> The issue is that the UI thinks the queue does not exist. It does in Redis, it will reappear if you push another job to it normally. Follow your same steps but at the end, push a new job to the same queue. The queue should appear in the UI with both jobs.

Yes but...because we can't guarantee or know when a job will be re-added to the queue, those jobs may not run for hours or days....when they are run right away if the queue does still exist.

I would expect that the re-enqueing the jobs would behave the same as if the jobs were added.  Is there a reason this can't be fixed?  It does seem pretty clearly to be an issue (and we are using the pro version).

**Comment by mperham** [comment]
The queue does exist and the job would be processed. It’s just that the
queue name does not exist in the “queues” set that the Web UI uses to know
which queues exist so it doesn’t appear in the queue list. You can verify
this by constructing the queue page URL directly, go to
/queues/yourqueuename manually.

**Comment by dnorth98** [comment]
It's more than a UI issue.  I just re-ran the test again and confirmed that the jobs are never de-queued.  I did use your URL construct and confirmed that the jobs are there.  But they are never de-queued until the queue is re-created.  

Again, I feel this is a valid issue because the jobs will never be processed until the queue is re-created which is indeterminant.  As our workflow involves creating and removing queues dynamically (across billions of jobs), this is actually a very real problem for us.

**Comment by mperham** [comment]
I’m not sure why you aren’t seeing the jobs processed. If you start a Sidekiq process for that queue, it will pull those jobs.

If you clear the queues with the API rather than the UI, this might work better.

**Comment by dnorth98** [comment]
Yeah I don't know why they aren't processed, hence this issue :) I am starting the sidekiq process for the queue and it's not pulling the jobs.

I've also tried clearing the queues with the API and the same result (we actually have a scheduled task that does this using the API - I fell back to using the UI just to make it easier to test).

Again, this all works FINE if the queue is not deleted.  Ergo, the sidekiq process can read the queue just fine on a restart and process the jobs IF it exists.

I feel I've given a great (and quite simple) reproducible case here.

**Comment by mperham** [comment]
With plain old Sidekiq, it works exactly as designed for me. I create this:

```ruby
class LazyWorker
  def perform
    sleep 30
  end
end
```

I create the job.

```
bundle exec rails c
> LazyWorker.perform_async
```

I start the Web UI and see it in the default queue. I start Sidekiq.

```
bundle exec sidekiq -t 20
```

It starts the job. I immediately delete the queue in the Web UI and then hit Ctrl-C in Sidekiq.

```
^C2020-10-02T18:38:06.629Z pid=52536 tid=1ao8 INFO: Shutting down
2020-10-02T18:38:06.629Z pid=52536 tid=1ao8 INFO: Terminating quiet workers
2020-10-02T18:38:06.629Z pid=52536 tid=1a1s INFO: Scheduler exiting...
2020-10-02T18:38:06.732Z pid=52536 tid=1ao8 INFO: Pausing to allow workers to finish...
2020-10-02T18:38:26.601Z pid=52536 tid=1ao8 WARN: Terminating 1 busy worker threads
2020-10-02T18:38:26.601Z pid=52536 tid=1ao8 WARN: Work still in progress [#<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", job="{\"retry\":true,\"queue\":\"default\",\"class\":\"LazyWorker\",\"args\":[],\"jid\":\"3783a9a7c07285984ebec0a5\",\"created_at\":1601663796.497463,\"enqueued_at\":1601663796.4976242}">]
2020-10-02T18:38:26.602Z pid=52536 tid=1ao8 INFO: Pushed 1 jobs back to Redis
2020-10-02T18:38:26.603Z pid=52536 tid=1b0k class=LazyWorker jid=3783a9a7c07285984ebec0a5 elapsed=22.185 INFO: fail
2020-10-02T18:38:26.603Z pid=52536 tid=1ao8 INFO: Bye!
```

I see the job in the Web UI if I go directly to the queue URL. I restart Sidekiq and it immediately picks up the same job.

```
2020-10-02T18:38:26.603Z pid=52536 tid=1ao8 INFO: Bye!
❯ bundle exec sidekiq -t 20
2020-10-02T18:38:42.010Z pid=53090 tid=1b0y INFO: Booted Rails 6.0.3.1 application in development environment
2020-10-02T18:38:42.010Z pid=53090 tid=1b0y INFO: Running in ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
2020-10-02T18:38:42.010Z pid=53090 tid=1b0y INFO: See LICENSE and the LGPL-3.0 for licensing details.
2020-10-02T18:38:42.010Z pid=53090 tid=1b0y INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2020-10-02T18:38:42.011Z pid=53090 tid=1b0y INFO: Booting Sidekiq 6.1.2 with redis options {}
2020-10-02T18:38:42.013Z pid=53090 tid=1b0y INFO: Starting processing, hit Ctrl-C to stop
2020-10-02T18:38:42.031Z pid=53090 tid=1aou class=LazyWorker jid=3783a9a7c07285984ebec0a5 INFO: start
2020-10-02T18:39:12.194Z pid=53090 tid=1aou class=LazyWorker jid=3783a9a7c07285984ebec0a5 elapsed=30.163 INFO: done
```

**Comment by dnorth98** [comment]
Most interesting.  First thing that caught my eye is version:

You: `Booting Sidekiq 6.1.2`
Us: `Booting Sidekiq 5.2.7`

We have one cluster running 6.1.2 so I tested it there and it works!

The roadmap for getting everything to 6 is long for us.  What's the chances of getting whatever the fix was ported back to 5?

**Comment by mperham** [comment]
We reformatted much of the codebase in 6.0 so I can't read through the diff to find issues. You might try git bisect with different version tags, "vX.Y.Z", and see if you can nail down a commit.
