### ISSUE TITLE
Executable for sidekiqctl removed

### ISSUE THREAD

**Issue by tigris** [mperham/sidekiq#4707]
Ruby version: 2.7.1
Rails version: 5.1.7
Sidekiq / Pro / Enterprise version(s): 6.1.2

I had some scripts that were using `sidekiqctl`. When upgrading to sidekiq 6 (from sidekiq 5), i read through the changes and everything seemed safe for me to upgrade.

After the upgrade, I saw errors around `sidekiqctl` executable being non-existent. I had another read of the changes file to see if i missed something.

I'm happy to update my things to not use it, that's fine. Just not sure if the "bug" is the script was removed, or simply a lack of warning folks in the docs about the script being deprecated/disappearing. Maybe just a simple docs bug.

**Comment by tigris** [comment]
Looks to be deliberate in a recent commit, since all `sidekiqctl` could do in recent 6.* versions was print the status.

As of https://github.com/mperham/sidekiq/commit/5987a8c352a220a94e1850c79186d82c35050d85#diff-5166bff26ec51c85865d70ba9890e7c2 using `sidekiqctl` to quiet/stop the daemon was no longer possible.

My script is easily updatable, but could be worth a mention in the docs 👍

**Comment by mperham** [comment]
Point 3 here:

https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md#whats-new

**Comment by tigris** [comment]
Ahh I see it now. The change makes perfect sense. I just usually check the `CHANGES.md` file which I expect to contain the info I need, but didn't mention it at all. Thanks for the pointer.
