### ISSUE TITLE
Job with same Job Id got enqueued multiple times

### ISSUE THREAD

**Issue by manishankar2** [mperham/sidekiq#4708]
Ruby version: 2.3.0
Rails version: 5.0.7
Sidekiq Pro v4.0.3

We run 4 dedicated instances (c5.2xLarge) in production environment for Sidekiq workers, with each instance running 3 process (Monit) with a concurrency of 25. 
Yesterday we had an issue where the same job got enqueued multiple times and cranked our system. 
This job usually takes a longer time to run. 
The job initially got enqueued on 01:00:00 IST with a Job Id [Enqueued ******* (Job ID: 0e967bde-ad2a-47e6-b8be-1308a8954d59], after 13 mins of run time the job got succeeded ( We observed the performed Job message with the running time). 
A second later the same Job with same Job Id got enqueued in another machine. This pattern continued for a while, since we noticed the issue very late it essentially cranked our system. 
We also noticed that the Super fetch has re-enqueued some of the Job but with a difference of 12+ hours. After we went through the logs we noticed the same Job got re-enqueued 500 + times before the super fetch tried to retrieve the Job. 
Also we have verified in the code and in the logs that we are not enqueueing the same Job again. ( I'm assuming even if its the case of the Job getting enqueued again and again because of a faulty code, the Job id will be different rit ?). 
Also we use ActiveJob if that helps. 

1.  How to debug this issue further or what could be the potential cause of this issue ?
2. Also how can we avoid this in the future?

P.S. We haven't enabled super_fetch till now in our initializer, we still use reliable_fetch!. But we observed this in the log files
"ERROR: reliable_fetch! has been removed from Sidekiq Pro, use super_fetch! instead"
"SuperFetch activated"
"WARN: SuperFetch recovered job:"
Does this means that super_fetch automatically gets activated in Pro version ?. 

Thanks,
Manishankar.

**Comment by mperham** [comment]
If you used reliable_fetch, Pro enables super_fetch instead since you've indicated that you want reliability.

I don't know why you are seeing jobs with the same Job ID, but note that's an ActiveJob thing. Sidekiq uses "JID". If you enqueue two jobs correctly, they should have different JIDs and Job IDs.

The way to debug is to turn on verbose logging and start combing through Sidekiq logs, Redis logs and anything else involved.

**Comment by manishankar2** [comment]
Hi @mperham, 
Usually we get this log "Enqueued ******* " whenever we enqueue the Job via active Job form our code. 
But for this case we only got it once and after the first job completed successfully. 
For this specific job basically send 2100 array of Ids in the job as a parameter. We also observed that even though we got the completed message it has only processed up-to 1100 ids and marked the job as completed.  
Do we have any limit on the array size in the first place ?

Thanks,
Manishankar.

**Comment by manishankar2** [comment]
Also I noticed here you've recommended the user to migrate to super_fetch. He also has reliable_fetch and pro version, why didn't super_fetch got activated by default ?. 
https://github.com/mperham/sidekiq/issues/4706#issuecomment-702404136

**Comment by mperham** [comment]
No array size limit.

He was using an old version that had the previous version. 4.0+ only has super fetch.
