### ISSUE TITLE
undefined method `jid=' for #<SupportRequestAcceptJob:0x00007f545cda5950>

### ISSUE THREAD

**Issue by varalakshmi-prasthana** [mperham/sidekiq#4709]
Ruby version: 2.6.3
Rails version: 5.2.3
Sidekiq / Pro / Enterprise version(s): sidekiq - 5.2.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
**initializer**
```
schedule_file = 'config/sidekiq_jobs.yml'

Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)[Rails.env] if File.exist?(schedule_file) && Sidekiq.server?

```
**sidekiq_jobs.yml**

```
default: &default

  support_request_accept_job:
    cron: '*/5 * * * *' # Runs every 5 mins
    class: SupportRequestAcceptJob
    queue: support_request
```
**backtrace**

`
NoMethodError · undefined method `jid=' for #<SupportRequestAcceptJob:0x00007f545cda5950>

gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:135block (5 levels) in dispatch	

@reloader.call do
  klass  = constantize(job_hash['class'])
  worker = klass.new
  worker.jid = job_hash['jid']
  @retrier.local(worker, pristine, queue) do
  yield worker
 end

gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:42block in call	
gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87wrap	
gems/activesupport-5.2.3/lib/active_support/reloader.rb:73block in wrap	
gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87wrap	
gems/activesupport-5.2.3/lib/active_support/reloader.rb:72wrap	
gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:41call	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132block (4 levels) in dispatch	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217stats	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127block (3 levels) in dispatch	
gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8call	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126block (2 levels) in dispatch	
gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73global	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125block in dispatch	
gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48with_context	
gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42with_job_hash_context	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124dispatch	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165process	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83process_one	
gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71run	
gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16watchdog	
gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25block in safe_thread

`
If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
You need to include Sidekiq::Worker in that class.
