### ISSUE TITLE
Occasional orphaned batches with pending job never started

### ISSUE THREAD

**Issue by hangsu** [mperham/sidekiq#4710]
One every thousand or so batches become orphaned with a pending job.

![image](https://user-images.githubusercontent.com/1279036/95125561-c6283500-071a-11eb-9f3d-e4841641088f.png)

A search through the logs reveals no mention of the pending JID. All other jobs with the BID started and completed. I don't see any evidence of a process crash.

I'll restart all (Heroku) dynos many hours later, and the job pops back into existence and completes, finishing the batch.

Any idea where I can start debugging this?
Thank you.

Ruby version: 2.6.6
Rails version: 5.2.4.4
Sidekiq / Pro / Enterprise version(s): 6.1.2 / 5.2.0 / -

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
# sidekiq.rb
require 'sidekiq/scheduler'

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_client do |config|
  # see https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud
  config.redis = { url: Rails.configuration.redis['sidekiq_url'], network_timeout: 3 }
end

Sidekiq.configure_server do |config|
  config.redis = { url: Rails.configuration.redis['sidekiq_url'], network_timeout: 3 }

  config.super_fetch!
  config.reliable_scheduler!

  config.on(:startup) do
    Sidekiq.schedule = YAML.load(ERB.new(File.read("#{Rails.root}/config/sidekiq_scheduler.yml")).result)
    Sidekiq::Scheduler.instance.reload_schedule!
  end
end
```

```
# sidekiq.yml
---
:verbose: false
:concurrency: 30
:timeout: 25

production:
  :concurrency: 10

:queues:
  - critical
  - default
```

```
# redis-cli info
# Server
redis_version:4.0.14
redis_git_sha1:18572a92
redis_git_dirty:1
redis_build_id:242eb8bde09ff061
redis_mode:standalone
os:Linux 4.4.0-1111-aws x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:5.4.0
process_id:9
run_id:e916345299146c05cda6f714eef2cff0c899f3df
tcp_port:19129
uptime_in_seconds:4252720
uptime_in_days:49
hz:10
lru_clock:8091147
executable:/usr/lib/redis/4/bin/redis-server
config_file:/etc/redis/heroku-redis.conf

# Clients
connected_clients:57
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:16

# Memory
used_memory:8246600
used_memory_human:7.86M
used_memory_rss:16359424
used_memory_rss_human:15.60M
used_memory_peak:28059304
used_memory_peak_human:26.76M
used_memory_peak_perc:29.39%
used_memory_overhead:4121824
used_memory_startup:530752
used_memory_dataset:4124776
used_memory_dataset_perc:53.46%
total_system_memory:16040185856
total_system_memory_human:14.94G
used_memory_lua:55296
used_memory_lua_human:54.00K
maxmemory:262144000
maxmemory_human:250.00M
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.98
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:101557211
rdb_bgsave_in_progress:0
rdb_last_save_time:1598166226
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:712704
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:548864
aof_current_size:27527696
aof_base_size:2108737
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:227028
total_commands_processed:310590745
instantaneous_ops_per_sec:121
total_net_input_bytes:25556929998
total_net_output_bytes:19188881708
instantaneous_input_kbps:8.21
instantaneous_output_kbps:8.09
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:815753
expired_stale_perc:0.17
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:21631474
keyspace_misses:33841964
pubsub_channels:0
pubsub_patterns:8
latest_fork_usec:639
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:1
slave0:ip=10.0.46.210,port=13969,state=online,offset=210809794428,lag=1
master_replid:5f73d65d6f8824a5546683734335902716f76cda
master_replid2:8c157f6d4ad9b60285f7ba35217ce2fc7db7b4b9
master_repl_offset:210809796669
second_repl_offset:198294536996
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:210808748094
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:8328.19
used_cpu_user:5284.52
used_cpu_sys_children:1.24
used_cpu_user_children:7.34

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=9000,expires=7849,avg_ttl=23712838255
```

**Comment by mperham** [comment]
Sounds like you are losing a job somehow and super_fetch is rescuing the orphaned job so it can finish executing. How that job is lost can be like searching for a needle in a haystack. It's up to you to trawl your logs for execution and timing data so you can determine the cause. Typically jobs are lost for two major reasons: (1) a process crash; or (2) a misconfigured deploy meaning the Sidekiq process is force killed before it can return the jobs to Redis.

**Comment by mperham** [comment]
Note that if you click into the Batch, it will show you the pending JIDs which you can use to grep your logs for info.

**Comment by hangsu** [comment]
The pending JID from the batch interface isn't found at all in my logs.

All 78 of the other JIDs can be found in the logs looking like this:

![image](https://user-images.githubusercontent.com/1279036/95128954-d262c100-071f-11eb-99c8-8f358eac0379.png)

I was trying to find out if a process crashed, but couldn't find any evidence. There have been times in the distant past where a native gem caused a segfault, but that doesn't appear to be happening here.

It's also 79 jobs in a batch, all being queued at once, handled by 4 processes with 10 concurrency, so if a process crashed, I would've expected more than 1 job to be lost. The last time this happened, it was 1 job lost out of dozens as well.

The only other thing I can think of that we're doing differently than the normal use-case is that we wrote a custom dyno autoscaler that scales up when there are a lot of jobs to be run, and scales back down to a fixed number when there are no jobs.

The autoscaler scaled up by 1 dyno about 2 minutes before the problem batch ran. Didn't appear to be relevant.

Our deploy is pretty standard Heroku stuff.

I'll try reverting to `gem 'sidekiq-pro', '< 5'`, see if it persists. I don't remember this happening before we upgraded to `<6` several months ago.

Is there a way to trigger the rescuing of orphaned jobs without a full `heroku restart`?

**Comment by mperham** [comment]
Hmm, I'm not sure what to tell you then. I would suspect your autoscaler. You might disable it for a day or two and see if the batch pending problems go away.

There's no official API to rescue orphans on demand. You can look at the Sidekiq Pro internals to see how it's implemented and call the methods yourself but those can change over time.

**Comment by hangsu** [comment]
Okay, thanks for your input. I'll report back if I learn anything new.
