### ISSUE TITLE
Sidekiq web UI css styles not working when location rule is added to nginx.conf 

### ISSUE THREAD

**Issue by robertochingon** [mperham/sidekiq#4713]
Hi, 

   Sidekiq web UI css styles stop working when a location rule like: 

location ~* \.(?:css|js)$ {} 

is added to nginx.conf. 

Best regards,
Roberto.

**Comment by mperham** [comment]
Then don’t do that?

**Comment by robertochingon** [comment]
Is it ironic? Not sure if I understand your answer. There are a lot of reasons why you would want to include a rule like this in nginx config file.

**Comment by mperham** [comment]
If you run `rm -rf /` on a Linux machine, it stops booting.  Is that a Linux issue?

My point is: your nginx configuration breaks Sidekiq. Read the nginx docs and learn how to configure it properly so it doesn't break downstream apps. There's a little about proxying with nginx here:

https://github.com/mperham/sidekiq/wiki/Monitoring#proxying-the-web-ui
