### ISSUE TITLE
Batch Job showing incorrect stats and not firing on_complete

### ISSUE THREAD

**Issue by sulmanweb** [mperham/sidekiq#4716]
Ruby version: 2.6.6
Rails version: 6.0.3.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.1.1 / Pro 5.1.1 / Ent 2.1.1

initializer: bundle exec sidekiq -c 5 -q importer

config/initializers/sidekiq.rb: 
```ruby
Sidekiq::Client.reliable_push!
  Sidekiq::Enterprise.unique!
  Sidekiq::Extensions.enable_delay!

  Sidekiq.configure_server do |config|
    config.super_fetch!
    config.reliable_scheduler!
    config.redis = { url: redis_uri }

    config.server_middleware do |chain|
      chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes
    end

    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = { url: redis_uri }

    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware
    end
  end
```

We're queueing a batch with 5 jobs. We have `complete` and `success` callbacks in our code. In order to test different failure scenarios, we randomly fail our jobs using by raising `StandardError`. Almost always we end up with a scenario where the batch stats show total = 5, pending = 5, failure = 2. In addition, no callbacks are ever fired.

Here is the recent json of batch stats:

```json
{
  "is_complete": true,
  "bid": "ebYqfO1LKGiimQ",
  "total": 5,
  "pending": 3,
  "description": "",
  "failures": 3,
  "created_at": 1602678926.900716,
  "fail_info": [
    {
      "jid": "9ab8676d43f7284a8e18679b",
      "error_class": "StandardError",
      "error_message": "StandardError",
      "backtrace": null
    },
    {
      "jid": "f8718159e7a1ec2e52cde83c",
      "error_class": "StandardError",
      "error_message": "StandardError",
      "backtrace": null
    },
    {
      "jid": "ab011e4966bfe546ad74fe4f",
      "error_class": "StandardError",
      "error_message": "StandardError",
      "backtrace": null
    }
  ]
}
```

## Expected Result:
Batch should have fired the `on_complete` callback and `pending` should have been 0.

**Comment by sulmanweb** [comment]
That is exactly the issue. `complete` is not getting called. Also, we have set `retry: false` in the `sidekiq_options` so there shouldn't be any jobs pending retries.

**Comment by mperham** [comment]
Show me the actual code in question.
