### ISSUE TITLE
Unique jobs are still reporting metrics with the worker class in the metric name

### ISSUE THREAD

**Issue by jeffblake** [mperham/sidekiq#4718]
Ruby version: 2.7.2
Rails version: 6
Sidekiq / Pro / Enterprise version(s): 6.1.2 / 5.2.0 / 2.1.2

The Unique feature of Sidekiq-Ent is still reporting worker classes in the metric name. 

As part of discussion here https://github.com/mperham/sidekiq/issues/4650 and here https://github.com/mperham/sidekiq/issues/4377

I believe Line 121 of `unique.rb` should be removed:

`b.increment("jobs.duplicate.#{c}")`

**Comment by mperham** [comment]
Good report, easy fix, A+++
