### ISSUE TITLE
Jobs with retry set as false, when ActiveRecord::ConnectionTimeout Error is thrown, getting pushed to the dead queue. ( Not a bug need a work around)

### ISSUE THREAD

**Issue by manishankar2** [mperham/sidekiq#4722]
Ruby version: 2.3.1
Rails version: 5.0.7
Sidekiq / Pro / Enterprise version(s): 4.3.0

We have a worker which we don't want to run again even when there is an error because of the business logic. Hence we have enabled retry => false. But when there are too many Jobs enqueued in the system ActiveRecord::ConnectionTimeout Error is thrown (which is expected), and the jobs with retry set as false are also pushed to dead queue.( which is understandable). I tried to rescue the exception in middleware and also in Active Job to reset the retry count it doesn't seem to work, what is the possible work around for this.

**Comment by mperham** [comment]
Increase the `pool` size in database.yml.
