### ISSUE TITLE
(AWS ElastiCache) Production sidekiq trying to connect to localhost

### ISSUE THREAD

**Issue by CarlosUvaSilva** [mperham/sidekiq#4723]
Ruby version: 2.7.1
Rails version: 6.0.3
Sidekiq / Pro / Enterprise version(s): 6.0.7

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

**config/initializers/sidekiq.rb**:
```
require 'sidekiq'
require 'sidekiq/web'

redis_host = "redis://#{Rails.application.credentials.redis_host}:"\
             "#{Rails.application.credentials.redis_port}/"\
             "#{Rails.application.credentials.redis_db}"


Sidekiq.configure_server do |config|
  config.redis = { url: redis_host }

  config.on(:startup) do
    FileUtils.touch(Rails.root.join("sidekiq_started"))
  end

  config.on(:shutdown) do
    FileUtils.rm(Rails.root.join("sidekiq_started"))
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_host }
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == [
    Rails.application.credentials.sidekiq_user,
    Rails.application.credentials.sidekiq_password
  ]
end
```

My sidekiq logs show this `Booting Sidekiq 6.0.7 with redis options {:url=>"redis://aws-redis.euw1.cache.amazonaws.com:6379/1"}` and using set or get with redis is working okay. but when I queu a job into sidekiq I can see the job is queue if I go to the sidekiq dashboard (I have it enabled in production) but it says `Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)`

I don't understand how redis is booting with production Env and sidekiq is trying to connect to localhost. I have exactly the smae config in other project and it's working. did something change?

**Comment by cassidb7** [comment]
Was this ever resolved? Facing a similar issue myself

**Comment by ChadMoran** [comment]
I assume lack of a second s in the scheme of the URI `rediss`
