### ISSUE TITLE
Question: Possible to force a job to the top of the queue?

### ISSUE THREAD

**Issue by jongbeau** [mperham/sidekiq#4727]
If I have a job ID, is it possible to force a job to start running, or move to the top of the queue from the ruby console?

**Comment by mperham** [comment]
Nope, Sidekiq only supports queue prioritization, not job prioritization. You can have a `critical` queue which is checked first before other queues but within a queue jobs are still executed FIFO.

**Comment by jongbeau** [comment]
is it possible to move a job from one queue into another, once it's been queued?

**Comment by mperham** [comment]
Not easily, requires some Redis magic.

**Comment by mperham** [comment]
Easier to delete the job in queue A and create a new copy in queue B.
