### ISSUE TITLE
Sidekiq Web Interface Issue with ActiveRecordStore

### ISSUE THREAD

**Issue by wimpog** [mperham/sidekiq#4728]
Ruby version: 2.6
Rails version: 6.0.2.2
Sidekiq / Pro / Enterprise version(s): 6.1.2 / 5.2.0 / 2.1.2 (or 6.0.7 / 5.0.1 / 2.0.1)
OS: MacOS X 10.14.6, Amazon Linux
Browsers: All

----

### ERROR when accessing the Sidekiq web interface (/sidekiq)
`TypeError can't quote Rack::Session::SessionId`
----

----

### Full Trace
**activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/quoting.rb:231:in `_quote'
activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/quoting.rb:18:in `quote'
activerecord (6.0.2.2) lib/arel/collectors/substitute_binds.rb:17:in `add_bind'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:703:in `visit_Arel_Nodes_BindParam'
activerecord (6.0.2.2) lib/arel/visitors/visitor.rb:31:in `visit'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:611:in `visit_Arel_Nodes_Equality'
activerecord (6.0.2.2) lib/arel/visitors/visitor.rb:31:in `visit'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:790:in `block in inject_join'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `each'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `each_with_index'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `inject_join'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:578:in `visit_Arel_Nodes_And'
activerecord (6.0.2.2) lib/arel/visitors/visitor.rb:31:in `visit'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:790:in `block in inject_join'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `each'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `each_with_index'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:788:in `inject_join'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:181:in `collect_nodes_for'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:161:in `visit_Arel_Nodes_SelectCore'
activerecord (6.0.2.2) lib/arel/visitors/mysql.rb:28:in `visit_Arel_Nodes_SelectCore'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:128:in `block in visit_Arel_Nodes_SelectStatement'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:127:in `each'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:127:in `inject'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:127:in `visit_Arel_Nodes_SelectStatement'
activerecord (6.0.2.2) lib/arel/visitors/mysql.rb:23:in `visit_Arel_Nodes_SelectStatement'
activerecord (6.0.2.2) lib/arel/visitors/visitor.rb:31:in `visit'
activerecord (6.0.2.2) lib/arel/visitors/visitor.rb:11:in `accept'
activerecord (6.0.2.2) lib/arel/visitors/to_sql.rb:18:in `compile'
activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:34:in `to_sql_and_binds'
activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/query_cache.rb:99:in `select_all'
activerecord (6.0.2.2) lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
activerecord (6.0.2.2) lib/active_record/querying.rb:46:in `find_by_sql'
activerecord (6.0.2.2) lib/active_record/relation.rb:810:in `block in exec_queries'
activerecord (6.0.2.2) lib/active_record/relation.rb:828:in `skip_query_cache_if_necessary'
activerecord (6.0.2.2) lib/active_record/relation.rb:797:in `exec_queries'
activerecord (6.0.2.2) lib/active_record/relation.rb:615:in `load'
activerecord (6.0.2.2) lib/active_record/relation.rb:250:in `records'
activerecord (6.0.2.2) lib/active_record/relation.rb:245:in `to_ary'
activerecord (6.0.2.2) lib/active_record/relation/finder_methods.rb:528:in `find_nth_with_limit'
activerecord (6.0.2.2) lib/active_record/relation/finder_methods.rb:513:in `find_nth'
activerecord (6.0.2.2) lib/active_record/relation/finder_methods.rb:120:in `first'
activerecord-session_store (1.1.3) lib/active_record/session_store/session.rb:58:in `find_by_session_id'
activerecord-session_store (1.1.3) lib/active_record/session_store/session.rb:35:in `find_by_session_id'
activerecord-session_store (1.1.3) lib/action_dispatch/session/active_record_store.rb:124:in `block in get_session_model'
activerecord-session_store (1.1.3) lib/active_record/session_store/extension/logger_silencer.rb:47:in `silence_logger'
stackify-api-ruby (1.2.9) lib/stackify/logger_proxy.rb:28:in `method_missing'
activerecord-session_store (1.1.3) lib/action_dispatch/session/active_record_store.rb:123:in `get_session_model'
activerecord-session_store (1.1.3) lib/action_dispatch/session/active_record_store.rb:140:in `find_session'
rack (2.2.3) lib/rack/session/abstract/id.rb:314:in `load_session'
actionpack (6.0.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:46:in `block in load_session'
actionpack (6.0.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:54:in `stale_session_check!'
actionpack (6.0.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:46:in `load_session'
actionpack (6.0.2.2) lib/action_dispatch/request/session.rb:235:in `load!'
actionpack (6.0.2.2) lib/action_dispatch/request/session.rb:227:in `load_for_read!'
actionpack (6.0.2.2) lib/action_dispatch/request/session.rb:144:in `to_hash'
rack (2.2.3) lib/rack/session/abstract/id.rb:197:in `stringify_keys'
rack (2.2.3) lib/rack/session/abstract/id.rb:131:in `update'
rack (2.2.3) lib/rack/session/abstract/id.rb:306:in `prepare_session'
rack (2.2.3) lib/rack/session/abstract/id.rb:265:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
rack (2.2.3) lib/rack/content_length.rb:17:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
rack (2.2.3) lib/rack/builder.rb:244:in `call'
sidekiq (6.1.2) lib/sidekiq/web.rb:105:in `call'
sidekiq (6.1.2) lib/sidekiq/web.rb:110:in `call'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
rack (2.2.3) lib/rack/deflater.rb:44:in `call'
stackify-api-ruby (1.2.9) lib/stackify/rack/errors_catcher.rb:10:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.2) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.2) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.2) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.2) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.2) lib/rails/rack/logger.rb:28:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
lib/health_check.rb:10:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'**

----

### Installed Gems
**-bash-3.2$ bundle install
Using rake 13.0.1
Using concurrent-ruby 1.1.7
Using i18n 1.8.2
Using minitest 5.14.0
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using zeitwerk 2.3.0
Using activesupport 6.0.2.2
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.9
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.5.0
Using rails-html-sanitizer 1.3.0
Using actionview 6.0.2.2
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.0.2.2
Using nio4r 2.5.2
Using websocket-extensions 0.1.4
Using websocket-driver 0.7.1
Using actioncable 6.0.2.2
Using globalid 0.4.2
Using activejob 6.0.2.2
Using activemodel 6.0.2.2
Using activerecord 6.0.2.2
Using mimemagic 0.3.5
Using marcel 0.3.3
Using activestorage 6.0.2.2
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailbox 6.0.2.2
Using actionmailer 6.0.2.2
Using actiontext 6.0.2.2
Using multi_json 1.14.1
Using method_source 1.0.0
Using thor 0.20.3
Using railties 6.0.2.2
Using activerecord-session_store 1.1.3
Using algorithms 0.6.1
Using audited 4.9.0
Using roxml 4.0.0
Using authorizenet 2.0.0
Using aws-eventstream 1.1.0
Using aws-partitions 1.311.0
Using aws-sigv4 1.1.3
Using jmespath 1.4.0
Using aws-sdk-core 3.95.0
Using aws-sdk-accessanalyzer 1.6.0
Using aws-sdk-acm 1.30.0
Using aws-sdk-acmpca 1.23.0
Using aws-sdk-alexaforbusiness 1.35.0
Using aws-sdk-amplify 1.16.0
Using aws-sdk-apigateway 1.40.0
Using aws-sdk-apigatewaymanagementapi 1.13.0
Using aws-sdk-apigatewayv2 1.20.0
Using aws-sdk-appconfig 1.5.0
Using aws-sdk-applicationautoscaling 1.38.0
Using aws-sdk-applicationdiscoveryservice 1.26.0
Using aws-sdk-applicationinsights 1.9.0
Using aws-sdk-appmesh 1.22.0
Using aws-sdk-appstream 1.40.0
Using aws-sdk-appsync 1.25.0
Using aws-sdk-athena 1.25.0
Using aws-sdk-augmentedairuntime 1.4.0
Using aws-sdk-autoscaling 1.35.0
Using aws-sdk-autoscalingplans 1.22.0
Using aws-sdk-backup 1.13.0
Using aws-sdk-batch 1.30.0
Using aws-sdk-budgets 1.29.0
Using aws-sdk-chime 1.24.0
Using aws-sdk-cloud9 1.22.0
Using aws-sdk-clouddirectory 1.23.0
Using aws-sdk-cloudformation 1.34.0
Using aws-sdk-cloudfront 1.27.0
Using aws-sdk-cloudhsm 1.21.0
Using aws-sdk-cloudhsmv2 1.22.0
Using aws-sdk-cloudsearch 1.19.0
Using aws-sdk-cloudsearchdomain 1.17.0
Using aws-sdk-cloudtrail 1.22.0
Using aws-sdk-cloudwatch 1.37.0
Using aws-sdk-cloudwatchevents 1.28.0
Using aws-sdk-cloudwatchlogs 1.30.0
Using aws-sdk-codebuild 1.50.0
Using aws-sdk-codecommit 1.32.0
Using aws-sdk-codedeploy 1.29.0
Using aws-sdk-codeguruprofiler 1.4.0
Using aws-sdk-codegurureviewer 1.4.0
Using aws-sdk-codepipeline 1.30.0
Using aws-sdk-codestar 1.20.0
Using aws-sdk-codestarconnections 1.3.0
Using aws-sdk-codestarnotifications 1.2.0
Using aws-sdk-cognitoidentity 1.21.0
Using aws-sdk-cognitoidentityprovider 1.35.0
Using aws-sdk-cognitosync 1.18.0
Using aws-sdk-comprehend 1.31.0
Using aws-sdk-comprehendmedical 1.16.0
Using aws-sdk-computeoptimizer 1.2.0
Using aws-sdk-configservice 1.44.0
Using aws-sdk-connect 1.24.0
Using aws-sdk-connectparticipant 1.2.0
Using aws-sdk-costandusagereportservice 1.20.0
Using aws-sdk-costexplorer 1.41.0
Using aws-sdk-databasemigrationservice 1.33.0
Using aws-sdk-dataexchange 1.3.0
Using aws-sdk-datapipeline 1.18.0
Using aws-sdk-datasync 1.19.0
Using aws-sdk-dax 1.21.0
Using aws-sdk-detective 1.5.0
Using aws-sdk-devicefarm 1.32.0
Using aws-sdk-directconnect 1.28.0
Using aws-sdk-directoryservice 1.27.0
Using aws-sdk-dlm 1.27.0
Using aws-sdk-docdb 1.16.0
Using aws-sdk-dynamodb 1.46.0
Using aws-sdk-dynamodbstreams 1.18.0
Using aws-sdk-ebs 1.3.0
Using aws-sdk-ec2 1.157.0
Using aws-sdk-ec2instanceconnect 1.5.0
Using aws-sdk-ecr 1.28.0
Using aws-sdk-ecs 1.61.0
Using aws-sdk-efs 1.28.0
Using aws-sdk-eks 1.36.0
Using aws-sdk-elasticache 1.32.0
Using aws-sdk-elasticbeanstalk 1.29.0
Using aws-sdk-elasticinference 1.4.0
Using aws-sdk-elasticloadbalancing 1.21.0
Using aws-sdk-elasticloadbalancingv2 1.42.0
Using aws-sdk-elasticsearchservice 1.34.0
Using aws-sdk-elastictranscoder 1.20.0
Using aws-sdk-emr 1.27.0
Using aws-sdk-eventbridge 1.6.0
Using aws-sdk-firehose 1.27.0
Using aws-sdk-fms 1.25.0
Using aws-sdk-forecastqueryservice 1.4.0
Using aws-sdk-forecastservice 1.4.0
Using aws-sdk-frauddetector 1.3.0
Using aws-sdk-fsx 1.18.0
Using aws-sdk-gamelift 1.30.0
Using aws-sdk-glacier 1.28.0
Using aws-sdk-globalaccelerator 1.17.0
Using aws-sdk-glue 1.54.0
Using aws-sdk-greengrass 1.30.0
Using aws-sdk-groundstation 1.7.0
Using aws-sdk-guardduty 1.30.0
Using aws-sdk-health 1.23.0
Using aws-sdk-iam 1.37.0
Using aws-sdk-imagebuilder 1.5.0
Using aws-sigv2 1.0.1
Using aws-sdk-importexport 1.18.0
Using aws-sdk-inspector 1.25.0
Using aws-sdk-iot 1.49.0
Using aws-sdk-iot1clickdevicesservice 1.20.0
Using aws-sdk-iot1clickprojects 1.20.0
Using aws-sdk-iotanalytics 1.28.0
Using aws-sdk-iotdataplane 1.18.0
Using aws-sdk-iotevents 1.14.0
Using aws-sdk-ioteventsdata 1.7.0
Using aws-sdk-iotjobsdataplane 1.19.0
Using aws-sdk-iotsecuretunneling 1.2.0
Using aws-sdk-iotsitewise 1.1.0
Using aws-sdk-iotthingsgraph 1.6.0
Using aws-sdk-kafka 1.20.0
Using aws-sdk-kendra 1.4.0
Using aws-sdk-kinesis 1.22.0
Using aws-sdk-kinesisanalytics 1.23.0
Using aws-sdk-kinesisanalyticsv2 1.15.0
Using aws-sdk-kinesisvideo 1.24.0
Using aws-sdk-kinesisvideoarchivedmedia 1.23.0
Using aws-sdk-kinesisvideomedia 1.20.0
Using aws-sdk-kinesisvideosignalingchannels 1.2.0
Using aws-sdk-kms 1.31.0
Using aws-sdk-lakeformation 1.3.0
Using aws-sdk-lambda 1.41.0
Using aws-sdk-lambdapreview 1.18.0
Using aws-sdk-lex 1.25.0
Using aws-sdk-lexmodelbuildingservice 1.29.0
Using aws-sdk-licensemanager 1.13.0
Using aws-sdk-lightsail 1.30.0
Using aws-sdk-machinelearning 1.19.0
Using aws-sdk-macie 1.18.0
Using aws-sdk-managedblockchain 1.10.0
Using aws-sdk-marketplacecatalog 1.2.0
Using aws-sdk-marketplacecommerceanalytics 1.22.0
Using aws-sdk-marketplaceentitlementservice 1.18.0
Using aws-sdk-marketplacemetering 1.23.0
Using aws-sdk-mediaconnect 1.21.0
Using aws-sdk-mediaconvert 1.48.0
Using aws-sdk-medialive 1.44.0
Using aws-sdk-mediapackage 1.27.0
Using aws-sdk-mediapackagevod 1.12.0
Using aws-sdk-mediastore 1.24.0
Using aws-sdk-mediastoredata 1.21.0
Using aws-sdk-mediatailor 1.26.0
Using aws-sdk-migrationhub 1.23.0
Using aws-sdk-migrationhubconfig 1.3.0
Using aws-sdk-mobile 1.18.0
Using aws-sdk-mq 1.26.0
Using aws-sdk-mturk 1.21.0
Using aws-sdk-neptune 1.23.0
Using aws-sdk-networkmanager 1.2.0
Using aws-sdk-opsworks 1.23.0
Using aws-sdk-opsworkscm 1.33.0
Using aws-sdk-organizations 1.40.0
Using aws-sdk-outposts 1.4.0
Using aws-sdk-personalize 1.11.0
Using aws-sdk-personalizeevents 1.6.0
Using aws-sdk-personalizeruntime 1.9.0
Using aws-sdk-pi 1.18.0
Using aws-sdk-pinpoint 1.39.0
Using aws-sdk-pinpointemail 1.18.0
Using aws-sdk-pinpointsmsvoice 1.15.0
Using aws-sdk-polly 1.29.0
Using aws-sdk-pricing 1.18.0
Using aws-sdk-qldb 1.3.0
Using aws-sdk-qldbsession 1.3.0
Using aws-sdk-quicksight 1.19.0
Using aws-sdk-ram 1.16.0
Using aws-sdk-rds 1.84.0
Using aws-sdk-rdsdataservice 1.17.0
Using aws-sdk-redshift 1.42.0
Using aws-sdk-rekognition 1.37.0
Using aws-sdk-resourcegroups 1.23.0
Using aws-sdk-resourcegroupstaggingapi 1.24.0
Using aws-sdk-robomaker 1.23.0
Using aws-sdk-route53 1.34.0
Using aws-sdk-route53domains 1.21.0
Using aws-sdk-route53resolver 1.13.0
Using aws-sdk-s3 1.64.0
Using aws-sdk-s3control 1.18.0
Using aws-sdk-sagemaker 1.56.0
Using aws-sdk-sagemakerruntime 1.20.0
Using aws-sdk-savingsplans 1.4.0
Using aws-sdk-schemas 1.3.0
Using aws-sdk-secretsmanager 1.35.0
Using aws-sdk-securityhub 1.24.0
Using aws-sdk-serverlessapplicationrepository 1.26.0
Using aws-sdk-servicecatalog 1.38.0
Using aws-sdk-servicediscovery 1.22.0
Using aws-sdk-servicequotas 1.5.0
Using aws-sdk-ses 1.29.0
Using aws-sdk-sesv2 1.4.0
Using aws-sdk-shield 1.24.0
Using aws-sdk-signer 1.20.0
Using aws-sdk-simpledb 1.18.0
Using aws-sdk-sms 1.19.0
Using aws-sdk-snowball 1.26.0
Using aws-sdk-sns 1.23.0
Using aws-sdk-sqs 1.25.0
Using aws-sdk-ssm 1.77.0
Using aws-sdk-sso 1.3.0
Using aws-sdk-ssooidc 1.2.0
Using aws-sdk-states 1.27.0
Using aws-sdk-storagegateway 1.40.0
Using aws-sdk-support 1.20.0
Using aws-sdk-swf 1.19.0
Using aws-sdk-synthetics 1.1.0
Using aws-sdk-textract 1.14.0
Using aws-sdk-transcribeservice 1.41.0
Using aws-sdk-transcribestreamingservice 1.13.0
Using aws-sdk-transfer 1.19.0
Using aws-sdk-translate 1.21.0
Using aws-sdk-waf 1.29.0
Using aws-sdk-wafregional 1.30.0
Using aws-sdk-wafv2 1.4.0
Using aws-sdk-workdocs 1.22.0
Using aws-sdk-worklink 1.14.0
Using aws-sdk-workmail 1.23.0
Using aws-sdk-workmailmessageflow 1.3.0
Using aws-sdk-workspaces 1.36.0
Using aws-sdk-xray 1.25.0
Using aws-sdk-resources 3.72.0
Using aws-sdk 3.0.1
Using babel-source 5.8.35
Using execjs 2.7.0
Using babel-transpiler 0.7.0
Using bcrypt 3.1.13
Using bindex 0.8.1
Using bundler 2.1.4
Using byebug 11.1.3
Using cancancan 3.1.0
Using climate_control 0.2.0
Using terrapin 0.6.0
Using cocaine 0.6.0
Using orm_adapter 0.5.0
Using ckeditor 4.2.4
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using coffee-rails 5.0.0
Using composite_primary_keys 12.0.1
Using connection_pool 2.2.3
Using sync 0.5.0
Using tins 1.24.1
Using file-tail 1.2.0
Using sexp_processor 4.14.1
Using ruby_parser 3.14.2
Using ruby2ruby 2.4.4
Using sourcify 0.5.0
Using proc_extensions 0.2
Using delegate_matcher 0.4.3
Using responders 3.0.0
Using warden 1.2.8
Using devise 4.7.1
Using diff-lcs 1.3
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using einhorn 0.8.2
Using et-orbi 1.2.4
Using factory_bot 5.2.0
Using factory_bot_rails 5.2.0
Using faker 2.11.0
Using multipart-post 2.1.1
Using faraday 0.17.3
Using ffi 1.12.2
Using figaro 1.1.1
Using raabro 1.1.6
Using fugit 1.3.5
Using google-protobuf 3.11.4 (universal-darwin)
Using has_secure_token 1.0.0
Using hashie 4.1.0
Using http-accept 1.7.0
Using http-cookie 1.0.3
Using jbuilder 2.10.0
Using jquery-rails 4.3.5
Using jwt 2.2.1
Using kaminari-core 1.2.0
Using kaminari-actionview 1.2.0
Using kaminari-activerecord 1.2.0
Using kaminari 1.2.0
Using le 2.7.6
Using ledermann-rails-settings 2.5.0
Using liquid 4.0.3
Using mime-types-data 3.2020.0425
Using mime-types 3.3.1
Using money 6.13.7
Using monetize 1.9.4
Using money-rails 1.13.3
Using multi_xml 0.6.0
Using ruby2_keywords 0.0.2
Using mustermann 1.1.1
Using mysql2 0.5.3
Using net_http_unix 0.2.2
Using netrc 0.11.0
Using oauth2 1.4.4
Using omniauth 1.9.1
Using omniauth-oauth2 1.6.0
Using puma 4.3.3
Using pundit 2.1.0
Using rack-cors 1.1.1
Using rack-host-redirect 1.3.0
Using rack-protection 2.0.8.1
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 6.0.2.2
Using rails-observers 0.1.5
Using rdoc 6.2.1
Using tilt 2.0.10
Using react-rails 2.6.1
Using redis 4.2.2
Using rest-client 2.1.0
Using rolify 5.2.0
Using rspec-support 3.9.3
Using rspec-core 3.9.2
Using rspec-expectations 3.9.2
Using rspec-mocks 3.9.1
Using rspec-rails 4.0.0
Using rufus-scheduler 3.6.0
Using sassc 2.3.0
Using sassc-rails 2.1.2
Using sass-rails 6.0.0
Using sdoc 1.1.0
Using sidekiq 6.1.2
Using sidekiq-pro 5.2.0
Using sidekiq-ent 2.1.2
Using simple_form 5.0.2
Using sinatra 2.0.8.1
Using spring 2.1.0
Using stackify-api-ruby 1.2.9
Using stackify-ruby-apm 1.10.0
Using uglifier 4.2.0
Using web-console 4.0.2
Using wicked_pdf 2.0.2
Using wkhtmltopdf-binary 0.12.5.4
Bundle complete! 60 Gemfile dependencies, 386 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.**

----

### Content of /config/initializers/session_store.rb
`Rails.application.config.session_store :active_record_store, :key => '_my_session'`

if `active_record_store` is changed to `cookie_store`, the issue goes away.

Same issue is described here: https://github.com/rails/activerecord-session_store/issues/152

**Comment by mperham** [comment]
Sidekiq is not the cause, I don’t know what the issue is.

**Comment by wimpog** [comment]
@mperham Have you experienced it yourself? I did not have this issue with older version of Ruby, Rails, Sidekiq.

**Comment by mperham** [comment]
Please look here: https://github.com/rails/activerecord-session_store/issues

**Comment by wimpog** [comment]
@mperham What specifically should I be looking at? You gave me a link to a list of issues. Could you be specific? We paid for Sidekiq Pro, why are we having issues with it?

**Comment by mperham** [comment]
Your issue is with that gem, not Sidekiq Pro. I'm pointing you to their issue tracker. My support doesn't guarantee I will help you debug and fix every problem your application has. Specifically I would look at https://github.com/rails/activerecord-session_store/issues/154

**Comment by wimpog** [comment]
@mperham, Sidekiq is not compatible with the `activerecord-session_store` gem? Works with `cookie_store`, so I don't think there is anything wrong with my application.

**Comment by mperham** [comment]
I didn't say it was incompatible. I didn't say the problem lies in your application. I'm saying the issue does not lie in any Sidekiq code and that's all I guarantee support for because that's the only thing I can control.

**Comment by wimpog** [comment]
@mperham 
> the issue does not lie in any Sidekiq code
How do you know that?

**Comment by mperham** [comment]
The error you are seeing is an integration issue between Rack and activerecord-session_store. Sidekiq::Web works fine with many other session providers.

**Comment by wimpog** [comment]
@mperham why don't you investigate it and/or notify the appropriate people, since it is in your best interests to have this working, even if the issue is not with Sidekiq?

**Comment by mperham** [comment]
I pointed you to the open issue, no?

Ruby apps have tons of open source in them. Because of that, I assume a certain savviness with developers that are reporting issues here. I expect folks to be able to read backtraces, understand that gems can conflict and have integration issues, how to navigate GitHub and search for open issues in repositories, etc. I apologize if this assumption was wrong but I think you are assuming a lot more hand-holding than I provide. I'm happy to help you with Sidekiq-specific problems; Rack session problems might break Sidekiq::Web but the issue is deep within the Rack stack, not in something I can debug and fix.

**Comment by wimpog** [comment]
@mperham which other session providers has Sidekiq been tested with? Since there is no fix, I might need to switch to some other one.

**Comment by wimpog** [comment]
@mperham any update?

**Comment by mperham** [comment]
The issue is closed, what update are you expecting?

**Comment by wimpog** [comment]
@mperham it ain't no working!

**Comment by mperham** [comment]
Then I'd suggest you switch to cookie_store.

**Comment by wimpog** [comment]
@mperham I have used cookie_store before and it is no longer sufficient for my purposes as a cookie has storage limitation. What else would you suggest?

**Comment by mperham** [comment]
Lots of people use a Redis or memcached session store.

**Comment by wimpog** [comment]
@mperham I changed to **redis_session_store**. I can now launch Sidekiq Web interface however, when I do that, it logs me out of my web application. Any idea why this is happening?

Here is my **config/initializers/session_store.rb**:
`Rails.application.config.session_store :redis_session_store,
                                       {
                                         :key => '_enrollify_session',
                                         :url => ENV['REDIS_URL'],
                                         :expire_after => 30.minutes
                                       }`

**Comment by mperham** [comment]
Did you configure this? https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden

**Comment by wimpog** [comment]
@mperham yes! The issue is actually this: https://github.com/redis-store/redis-rails/issues/34#issuecomment-323555260

I added the following lines to config/initializers/session_store.rb:
`require 'sidekiq/web'
Sidekiq::Web.set :sessions, false`

Is that correct?

**Comment by mperham** [comment]
Disabling sessions also disables CSRF protection, meaning you are open to CSRF attacks. 🤷🏼‍♂️

**Comment by wimpog** [comment]
@mperham yes, the Web UI is behind a long wall. 
How do I configure Sidekiq sessions? What is your suggestion?

**Comment by mperham** [comment]
The Monitoring wiki page contains all I know about Rack sessions.

**Comment by mperham** [comment]
Can you show me your application code (e.g. add me to your github org) and I can take a look?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/4671#issuecomment-770279766

**Comment by mperham** [comment]
If you have a Rails app, make sure you are mounting the web UI "inside" the Rails routes, like shown here, so it can reuse the Rails application session:

https://github.com/mperham/sidekiq/wiki/Monitoring#rails

I just had to fix this in the docs.

**Comment by mperham** [comment]
Hi @wimpog, Sidekiq master now has rewritten session usage; one other person now has it running successfully with ActiveRecord::SessionStore, #4821. I'm sorry for the delay but it took me a long time to understand the root issue and how to fix it.

**Comment by wimpog** [comment]
@mperham thanks, but I have already switched to `redis-session-store`. When will you make a new release?

**Comment by swapnilfuturism** [comment]
Mac OS version: 12.0.1
rails version: 5.0.7
ruby version: 2.4.9

can't quote Rack::Session::SessionId facing exactly same issue on sidekiq UI

**Comment by swapnilfuturism** [comment]
> @mperham thanks, but I have already switched to `redis-session-store`. When will you make a new release?

Did you found any work around.

**Comment by mperham** [comment]
> Mac OS version: 12.0.1 rails version: 5.0.7 ruby version: 2.4.9
> 
> can't quote Rack::Session::SessionId facing exactly same issue on sidekiq UI

I need to know your Sidekiq version. Based on your Ruby/Rails versions, I'd guess you need to update your gems. `bundle up sidekiq`.

**Comment by swapnilfuturism** [comment]
> > Mac OS version: 12.0.1 rails version: 5.0.7 ruby version: 2.4.9
> > can't quote Rack::Session::SessionId facing exactly same issue on sidekiq UI
> 
> I need to know your Sidekiq version. Based on your Ruby/Rails versions, I'd guess you need to update your gems. `bundle up sidekiq`.

Many Thanks for reply. my sidekiq gem version is 5.2.10.

**Comment by mperham** [comment]
@swapnilfuturism and Rack version?

**Comment by swapnilfuturism** [comment]
> > > Mac OS version: 12.0.1 rails version: 5.0.7 ruby version: 2.4.9
> > > can't quote Rack::Session::SessionId facing exactly same issue on sidekiq UI
> > 
> > 
> > I need to know your Sidekiq version. Based on your Ruby/Rails versions, I'd guess you need to update your gems. `bundle up sidekiq`.
> 
> Many Thanks for reply. my sidekiq gem version is 5.2.10.


   sidekiq (5.2.10)
      connection_pool (~> 2.2, >= 2.2.2)
      rack (~> 2.0)
      rack-protection (>= 1.5.0)
      redis (~> 4.5, < 4.6.0)

**Comment by mperham** [comment]
@swapnilfuturism That's not your Rack version, that's your version rules. `bundle show | grep rack`

**Comment by swapnilfuturism** [comment]
its rack (2.2.3)
