### ISSUE TITLE
ActiveJob ignores sidekiq_options `pool`

### ISSUE THREAD

**Issue by vitiokss** [mperham/sidekiq#4732]
Ruby version: ruby 2.6.3p62
Rails version: Rails 6.0.3.4
Sidekiq / Pro / Enterprise version(s):
sidekiq: 6.1.2, sidekiq-pro: 5.2.0

```ruby
# config/initializers/sidekiq.rb
REDIS_1 = ConnectionPool.new { Redis.new }
REDIS_2 = ConnectionPool.new { Redis.new(port: 6380) }

Sidekiq.configure_server do |config|
  config.redis =  ENV['REDIS_2_ON'] == '0' ? REDIS_1 : REDIS_2
end

Sidekiq.configure_client do |config|
  config.redis =  ENV['REDIS_2_ON'] == '0' ? REDIS_1 : REDIS_2
end
```

Then we have an ActiveJob
```ruby
# app/jobs/sample_job.rb
class SampleJob < ApplicationJob

  sidekiq_options pool: REDIS_2

  def perform
    p "Done"
  end
end
```

Problem: When we start the service with REDIS_1, and when we fire `SampleJob.perform_later`, it ignores the pool specified in the job by `sidekiq_options` and adds the job into `REDIS_1`.

**Comment by mperham** [comment]
ActiveJob doesn't support every Sidekiq feature. This is one case where you'd need to use a Sidekiq::Worker instead.

**Comment by vitiokss** [comment]
So what is the point then to claim that `sidekiq_options` is being ported to ActiveJob as well if it's not working properly?

**Comment by mperham** [comment]
Just because the method works doesn't mean that every option will work. The point was to enable common use cases like configuring retry. The AJ wiki page is clear: not every advanced Sidekiq feature works with AJ.
