### ISSUE TITLE
Enabling SIDEKIQ_PRELOAD_APP causes only one swarm-managed process at a time to appear in the web interface

### ISSUE THREAD

**Issue by isaacbowen** [mperham/sidekiq#4733]
Overly verbose title. :) We use sidekiqswarm like so:

SIDEKIQ_COUNT=50 SIDEKIQ_MAXMEM_MB=768 sidekiqswarm -c 1 -t 10 -q run_default

... and, _with_ SIDEKIQ_PRELOAD_APP enabled, only one of the worker_run.* processes appears at a time in the web interface. Refreshing the page results in a different process appearing, always labeled as the leader. And, only one job appears at a time in the Jobs list - not necessarily belonging to the process that appears above.

<img width="500" alt="Screen Shot 2020-11-11 at 6 14 13 PM" src="https://user-images.githubusercontent.com/302012/98882530-1a2ce480-2452-11eb-9223-8b84c8aab369.png">

Removing SIDEKIQ_PRELOAD_APP from the environment results in all processes and jobs appearing normally.

Ruby version: 2.6.6
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.1.2 / Pro 5.2.0 / Ent 2.2.0

~~Please include your initializer, sidekiq.yml, and any error message with the full backtrace.~~

~~If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?~~

**Comment by mperham** [comment]
I believe this is a side effect of super fetch so disabling it should also make the bug go away.

**Comment by isaacbowen** [comment]
Ah, then I _will_ include my initializer after all. ;)

```ruby
# config/initializers/sidekiq.rb

$shutdown_pending = false

Sidekiq.configure_server do |config|
  config.redis = Rails.configuration.x.redis_config

  config.super_fetch!
  config.reliable_scheduler!

  config.on(:quiet) do
    $shutdown_pending = true
  end
end

Sidekiq.configure_client do |config|
  config.redis = Rails.configuration.x.redis_config
end

unless Rails.env.test?
  Sidekiq::Client.reliable_push!
  Sidekiq::Enterprise.unique!
end

Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    # a whole bunch of mgr.register lines
  end
end
```

**Comment by mperham** [comment]
Here's the fix:

```diff
--- a/lib/sidekiq/pro/super_fetch.rb
+++ b/lib/sidekiq/pro/super_fetch.rb
@@ -39,7 +39,6 @@ module Sidekiq::Pro
       @changed = true
       qs = options[:queues]
       @algo = options[:strict] && qs.length == qs.uniq.length ? method(:strict) : method(:weighted)
-      @queues = get_queues(options)
       concurrency = options.fetch(:super_fetch_concurrency, 2)
```

That's it, it was eager loading @queues but doesn't need to AFAICT.

**Comment by isaacbowen** [comment]
@mperham Is there a way for us to get access to this before you cut a new release of the gem?

**Comment by mperham** [comment]
Unfortunately not. Next release is still a few weeks away.
