### ISSUE TITLE
Requesting more explanation of using a child batch for complex workflows

### ISSUE THREAD

**Issue by RSR312-206** [mperham/sidekiq#4734]
Ruby version: 5.7.1
Rails version: 5.2.4.4
Sidekiq Pro version(s): 4.0.3

Hello, 

For complex workflows in Sidekiq Pro,  can you please explain a bit more about the need for the child batch which is called from the overall batch?  Specifically in the example code `StartWorkflow`, the first job is called inside a `batch.jobs` block, but why is that necessary when it's already inside the overall batch block?

In the sidekiq logs, it appears that both the parent batch and the child batch (created in the `StartWorkflow` class) are triggered for the `on_complete` or `on_success` callbacks. Here's a paired down example of a job which uses this pattern:

controller: 
```
 def create
    ...
    overall = Sidekiq::Batch.new
     overall.on(:success, "Callbacks::ZipfileServiceCallbacks#on_success", ...)
    args = {
      doc_ids: params[:doc_ids],
      request_id: rquest.id,
      batch_id: overall.bid
    }
    overall.jobs do
      ZipfileServiceWorkflow.perform_async(args)
   end
 end

```
`zipfile_service_workflow.rb`:
```
class ZipfileServiceWorkflow
 ...
 def perform(args)
    return unless valid_within_batch?
    batch.jobs do # this calls Batch.new if batch has not already been declared, I believe.
      step1 = Sidekiq::Batch.new
      step1.on(
        :success,
        "Callbacks::ZipfileServiceCallbacks#upload_file",
        "doc_ids" => args["doc_ids"], ...
      )

      step1.jobs do
        ZipfileCreator.perform_async(args)
      end
    end
```
`zipfile_service_callbacks.rb`:

```
class Callbacks::ZipfileServiceCallbacks
  include BackgroundJobLogger

  def on_success(_status, options)
    # doing stuff 
  end

  def on_complete(status, options)
    # doing stuff
  end

  def upload_file(status, options)
    overall = Sidekiq::Batch.new(status.parent_bid)
    overall.jobs do
      step2 = Sidekiq::Batch.new
      step2.on(:success, "Callbacks::ZipfileServiceCallbacks#delete_tmp_files", "user_id" => options["user_id"])
      step2.jobs do
       
        args = { ... }
        DocumentCreatorService.perform_async(args)
      end
    end
  end

  def delete_tmp_files(status, options)
    overall = Sidekiq::Batch.new(status.parent_bid)
    overall.jobs do
      args = { ... }
      DeleteFromTmpWorker.perform_async(args)
    end
  end

```

And here are the logs for that job - I removed everything except for the creation and completion of the two batches and paired down the output. 
overall batch: `pjo3y3Oo72xBzw`
batch created in the `ZipfileServiceWorkflow` class: `wy5E5BVw2xmEzA`

```
2020-11-12T17:58:10.030Z class=ZipfileServiceWorkflow jid=42c155d26c2b3ada070942a6 bid=wy5E5BVw2xmEzA DEBUG: Adding 1 jobs to batch pjo3y3Oo72xBzw, JIDs ["4cb8e8fc07e0bf8386e6ca96"]
2020-11-12T17:58:10.031Z class=ZipfileServiceWorkflow jid=42c155d26c2b3ada070942a6 bid=wy5E5BVw2xmEzA DEBUG: Skipping empty batch b-wy5E5BVw2xmEzA # what does it mean to "skip" an empty batch in this context? 

# jobs are called in callbacks and completed…

2020-11-12T17:58:11.617Z class=Sidekiq::Batch::Callback jid=e873de1b74f78ddcc206c357 DEBUG: BID-pjo3y3Oo72xBzw complete
2020-11-12T17:58:11.651Z  class=Sidekiq::Batch::Callback jid=f39fdf67bd877f9e23ecc16a DEBUG: BID-wy5E5BVw2xmEzA complete # why is this batch getting called in my on_complete callback, since it is not the overall batch? 
2020-11-12T17:58:11.652Z class=Sidekiq::Batch::Callback jid=b92f51a7610508b606609659 DEBUG: BID-pjo3y3Oo72xBzw success
```
2 questions about these logs:
1. What does it mean to "skip" an empty batch in this context? 
2. Why is this batch `wy5E5BVw2xmEzA` triggering the on_complete callback, since it is not the overall batch? 

Hopefully this is presented in a way that is easy to understand - please let me know if I can clarify anything.

**Comment by mperham** [comment]
I think you'd benefit from reviewing the code. `bundle open sidekiq-pro` and open lib/sidekiq/pro/worker.rb. You can see the code yourself. I will respond in detail soon.

**Comment by mperham** [comment]
The StartWorkflow class acts as placeholder for "step 1" of the overall workflow. When it calls `batch.jobs`, it is **reopening** the overall batch and adding the real Step 1 child Batch with the set of jobs to be done. When that child batch is finished, callbacks will fire which create Step 2 in the overall batch. In this way, we can have an asynchronous set of jobs at each step within a larger serialized workflow.

1. That "Skipping" log indicates an error in the app code: the Batch contained no jobs when the `jobs` block finished. Batches must have 1+ jobs. This is noted at several places in the Batches wiki page.
2. All batches fire all callbacks but not all of them have user-spec'd code to run. It's a no-op.

**Comment by RSR312-206** [comment]
@mperham cool thanks so much for the extra explanation and suggestions.
