### ISSUE TITLE
Batch taking minutes to execute callback after jobs complete

### ISSUE THREAD

**Issue by sajafleming** [mperham/sidekiq#4735]
Ruby version: 2.5.1
Rails version: 5.1
Sidekiq / Pro / Enterprise version(s): Pro

All jobs were completed in the batch were completed in 5 minutes (the screenshot was taken at 6 minutes), however, the batch did not seem to recognize that it was done for another 7 minutes. After 7 more minutes, it disappeared from the batches tab and I saw the completion callback had been registered. Is that expected?
![image](https://user-images.githubusercontent.com/7242179/98997664-b1914680-24e9-11eb-9e85-47b0503861d3.png)

This has happened for every batch now.

**Comment by mperham** [comment]
Jobs are executed in order that they are in queued. If your callback job is using the same queue it might have to wait for thousands of other jobs to finish before the callback is processed.

https://github.com/mperham/sidekiq/wiki/Batches#callback-details

**Comment by sajafleming** [comment]
@mperham thanks, I will try having the callback run in a higher priority queue. Right now the job that kicks off the batch as well as the jobs themselves are in the high priority queue. The callback is in the low priority queue. But I thought it since the callback was set up in a job that runs in the high priority queue, it would trigger from the high priority queue?

**Comment by mperham** [comment]
If you do not set the callback queue, it uses the same queue as the last job to finish in the batch.

**Comment by mperham** [comment]
But as they say: "if everything is high priority, nothing is high priority."
