### ISSUE TITLE
Wiki edit: Batches

### ISSUE THREAD

**Issue by ageacademia** [mperham/sidekiq#4736]
Ruby version: n/a
Rails version: n/a 
Sidekiq / Pro / Enterprise version(s): n/a

Sorry about opening an issue. I was playing around with the wiki and I didn't know I could publicly edit a page without being subject to any review. That seemed a little unsafe, and since the revision history looks permanent, I feel like I should get somebody to review it!

This is the diff: https://github.com/mperham/sidekiq/wiki/Batches/_compare/1243f2aad8856b89b16afa2337752c91a91704bc...a19c091b9b183202c865a826d09b7ce71430e545

I was somewhat unclear on the variable names in the "Huge Batches" section, so I thought I could change it to make the example more explicit.

**Comment by mperham** [comment]
“batch” is a method there, not a variable.
