### ISSUE TITLE
[ent] undefined method retain_history

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4737]
Ruby version: 2.5.5
Rails version: 5.0.7.2
Sidekiq / Pro / Enterprise version(s): 5.2.8 / 4.0.4 / 1.7.2

    ::Sidekiq.configure_server do |config|
      ...

      config.retain_history(30) if defined?(::Sidekiq::Enterprise)
    end

    NoMethodError:
      undefined method `retain_history' for Sidekiq:Module 
      # ./vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:75:in `configure_server'

Our versions do seem a bit dated - we're maintaining local copies in gemfury (asked the team how we typically update those). Is there a better/preferred way to stay up to date there?

**Comment by mperham** [comment]
How to vendor the gem is up to you, I don't give specific advice or recommend any particular service for gem management.

That error would indicate you aren't initializing Bundler correctly so it requires `sidekiq-ent` for you.

**Comment by dudo** [comment]
Noted on the gem management. Working on updating those. Seems to be some functionality that we'd benefit from!

So, we have a gem that sets a bunch of config, and adds consistent middleware across our apps. This is how it's being set up, with a call to `SidekiqConfiguration.configure!` within each app's sidekiq initializer. I just added the explicit `require` for pro and ent, but I get the same error. Does this seem correct? 

    require 'datadog/statsd'

    begin
      require 'sidekiq'
      require 'sidekiq-pro'
      require 'sidekiq-ent'
    rescue LoadError # rubocop:disable Lint/SuppressedException
    end

    class SidekiqConfiguration
      class << self
        def configure!
          configure_statsd
          configure_sidekiq_middleware

          ::Sidekiq::Enterprise.unique! unless Rails.env.test?
        end

        private

        def configure_statsd
          return unless defined?(::Sidekiq::Pro)

          ::Sidekiq::Pro.dogstatsd = -> { build_statsd_client }

          ::Sidekiq.configure_server do |config|
            config.server_middleware do |chain|
              require 'sidekiq/middleware/server/statsd'
              chain.add ::Sidekiq::Middleware::Server::Statsd
            end
          end
        end

        def configure_sidekiq_middleware
          ::Sidekiq.configure_server do |config|
            config.server_middleware do |chain|
              chain.add QueueTimeServerMiddleware
            end

            config.retain_history(30) if defined?(::Sidekiq::Enterprise)
          end
        end

        def build_statsd_client
          ::Datadog::Statsd.new(
            ENV.fetch('DATADOG_HOST', 'localhost'),
            ENV.fetch('DATADOG_PORT', 8125),
            namespace: 'sidekiq'
          )
        end
      end
    end

**Comment by mperham** [comment]
That’s not correct, the Enterprise access email shows you how to initialize the gems correctly by putting them in the Gemfile. You don’t need to require anything in your app code.

**Comment by dudo** [comment]
I don't have that email... I'll reach out to my team. In the interest of time, if you wouldn't mind resending it to me, that'd be amazing. Thanks for the help!

**Comment by mperham** [comment]
You need this in your Gemfile and call `bundle exec`.

```
source "https://enterprise.contribsys.com/" do
     gem 'sidekiq-pro'
    gem 'sidekiq-ent'
end
```

**Comment by dudo** [comment]
Just updating pro and ent seems to have solved the issue. Sorry to bother!

![image](https://user-images.githubusercontent.com/2963800/99327254-5e432f00-282e-11eb-80d9-a4f5a17b100a.png)
