### ISSUE TITLE
Upgrading sidekiq > 6.0 version increase in response time

### ISSUE THREAD

**Issue by anson2590** [mperham/sidekiq#4739]
Ruby version: 2.6.3
Sidekiq version: 6.0.6

I recently upgraded sidekiq from 5.0 to 6.0, after upgrading I can see an increase in response time with a couple of additional transactions been added like Redis time, Redis multi, etc. Is there any possibility that we can reduce response time?

We see an increase in time with additional transactions added,
Redis time => .8ms
Redis multi => .87ms
Redis hexists => .488ms
Reedis lpop => .476ms
Redis hset => 0.401ms 

can you help me with a fix to this performance issue? It's shooting up our response time by 20ms.

**Comment by anson2590** [comment]
Hi, can you please let us know why we have this performance spike and let us know if there is an upcoming fix for this

**Comment by mperham** [comment]
You will need to profile and determine where the slowdown is. I can't profile your system for you.

**Comment by mperham** [comment]
Did you find any cause here?

**Comment by anson2590** [comment]
The issue is resolved we increased newrelic error rate time. We are good to close this issue
