### ISSUE TITLE
Is it possible to set Sidekiq as windows-services?

### ISSUE THREAD

**Issue by DolezalDavid** [mperham/sidekiq#4740]
I try to use Sidekiq on Windows Server and it looks good. Here is manual which I use for testing: https://www.redmine.org/projects/redmine/wiki/SidekiqConfiguration

All work, but I don't know now, how I can configure services for Sidekiq. I prefer good solution before easy way like "start CMD with Ruby and send 'bundle exec sidekiq'. I would like to start it with start of system.

Any ideas?

**Comment by mperham** [comment]
I haven't used Windows in 15 years so I'm not sure. Others will have to chime in.

**Comment by mperham** [comment]
This looks promising but I can't try or test it.

https://abstractcoder.com/2013/07/18/create-a-windows-service-with-ruby-part-1.html
