### ISSUE TITLE
Handling "Batch xxxxxx has finished, you cannot modify it anymore"

### ISSUE THREAD

**Issue by roykolak** [mperham/sidekiq#4741]
I'm trying to understand some behavior I'm seeing with batching.

I accidentally queued up two large batches and I invalidated and deleted one of the batches

```rb
batch = Sidekiq::Batch.new(bid)
batch.invalidate_all
batch.status.delete
```

After running this code, the enqueued count was not decreasing quickly and it appeared as if the jobs in this deleted batch were not removed. It was then that I realized I was not calling `valid_within_batch?` inside the `perform` method for my job
as described here: https://github.com/mperham/sidekiq/wiki/Batches#canceling-a-batch

I updated the `perform` method with... 

```rb 
def perform(id)
  return if batch.present? && !valid_within_batch?
  # ...
end
```

After I deployed, I started seeing the following errors getting thrown from the early return line...

`RuntimeError: Batch xxxxxx has finished, you cannot modify it anymore`

Is this related to invalidating the batch initially w/o having the early return `valid_within_batch` check in place? 

Is there a correct way to hand these errors?

**Comment by mperham** [comment]
Don’t ever delete a batch if there are still jobs in redis. Just invalidate the jobs, it’ll go away on its own eventually.

**Comment by roykolak** [comment]
Gotcha, noted for the future. Thanks!
