### ISSUE TITLE
Is it possible to override queue priority?

### ISSUE THREAD

**Issue by arinhouck** [mperham/sidekiq#4742]
I was wondering If sidekiq can achieve some type of queue override?

```
Sidekiq::Worker.override_options(queue: :low) do
 ServiceObjectA.call
end
```

And within that service object any call made via perform_async would then become low priority.

Use case: I want to backfill or mass update some data and ServiceObjectA has some jobs with high_priority. So I don't want to bog down the queue with high priority jobs.

**Comment by mperham** [comment]
Nope, Sidekiq doesn't provide anything like this.

**Comment by absk1317** [comment]
@arinhouck Probably you can use something like  below:

```
ServiceObjectA.set(queue: :low).perform_async(args)
```

**Comment by absk1317** [comment]
@arinhouck Probably you can use something like  below:

```
ServiceObjectA.set(queue: :low).perform_async(args)
```
