### ISSUE TITLE
Sidekiq Ent Periodic Job - Support for "rate" expression?

### ISSUE THREAD

**Issue by ouranos** [mperham/sidekiq#4743]
Hi,

We're in the process of migrating some old periodic jobs to Sidekiq (we were using CloudWatch Scheduled Events to trigger those jobs).
For the jobs using the cron expressions, it's a straight forward migration. However, for the one using the rate expressions, it's a bit more complicated.

For example, we have a job that runs every 65 minutes, with `rate(65 minutes)`.

Converting to cron syntax, I'd have to add the following lines to our schedule:
```
 0  0 * * *
 5  1 * * *
10  2 * * *
15  3 * * *  
20  4 * * *  
25  5 * * * 
...
15 16 * * *  
20 17 * * *  
25 18 * * *  
30 19 * * *  
35 20 * * *  
40 21 * * *  
45 22 * * *  
```

Would it be possible to add support for `rate` expressions? Or do you have any other suggestions?

More info about CloudWatch Schedule Events: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html

**Comment by mperham** [comment]
So there’s no job in the 23rd hour? 

You could have a job which reschedules itself every 65 minutes only during the day it was created and have a midnight job which kicks it off every day.

**Comment by ouranos** [comment]
Ok, that should do the trick. Thanks.
