### ISSUE TITLE
sidekiq enterprise rate_limiter

### ISSUE THREAD

**Issue by crharvey** [mperham/sidekiq#4744]
Mike,

I am a developer at Manheim (Cox Auto Inc) and we have been using sidekiq enterprise (sidekiq-ent (1.3.2)) in a ruby application for the last 5 years. We originally misunderstood the business requirement which is:  1 transaction every 3 seconds per auctionId
I tried to solve this by "nesting" rate_limiters one  Sidekiq::Limiter.concurrent  which then calls one  Sidekiq::Limiter.window
but even though I have wait_timeout of 1 and  backoff of 3 the workers threads get locked up waiting on concurrent instead
of moving to find another request with a different auctionId

The worker is essentially this before it hits _perform to process the soap request:

```ruby
  # limit per auctionId and allow 1 facilitation per 3 seconds
  def perform(facilitation_request_id, facilitation_request_auction_id)
    TWSService::RATE_LIMIT[facilitation_request_auction_id] ||= construct_rate_limiter(facilitation_request_auction_id)
    TWSService::RATE_LIMIT[facilitation_request_auction_id].within_limit do
      _throttle(facilitation_request_id, facilitation_request_auction_id)
    end
  end

  private

  def construct_rate_limiter(facilitation_request_auction_id)
    Sidekiq::Limiter.concurrent("#{facilitation_request_auction_id}", Settings.tws.concurrency, Settings.tws.options)
  end

  def construct_throttle_limiter(facilitation_request_auction_id)
    Sidekiq::Limiter.window("#{facilitation_request_auction_id}", 1, 3)
  end

  def _throttle(facilitation_request_id, facilitation_request_auction_id)
    TWSService::THROTTLE_LIMIT[facilitation_request_auction_id] ||= construct_throttle_limiter(facilitation_request_auction_id)
    TWSService::THROTTLE_LIMIT[facilitation_request_auction_id].within_limit do
      benchmark 'RequestFacilitationWorker._perform', level: Settings.rails.benchmark_log_level do
        _perform(FacilitationRequest.find(facilitation_request_id))
      end
    end
  end
```

I am certain that "nesting" these rate_limiters is horribly inefficient but I am not sure how to achieve this business
requirement. The target API is a legacy TIBCO SOAP service and fixing the 1 transaction every 3 secs per auctionId issue seems to be far more complicated on that end.

**Comment by mperham** [comment]
I hope you can upgrade, there's tons of improvements in the last 3 years.

I would remove the concurrent limiter, I don't see any reason for it. Other than that, I don't see anything I provide that can improve the situation.

Once every three seconds is a pretty awful rate limit because it's so binary, better would be 20 in one minute but I suspect you have no say in the matter. :(

**Comment by crharvey** [comment]
Mike,
I tried that but then multiple worker threads would send one every three seconds which meant same auctionId could receive more than one in less than three seconds (the subsequent transactions are erroneously flagged as having already been processed) which causes confusion down stream

thanks,
Chuck

**Comment by mperham** [comment]
I can’t see how that’s possible unless if they are different limiters with different names.

**Comment by mperham** [comment]
If you can write a script which reproduces that, I will fix ASAP.

**Comment by wardelleugene** [comment]
Hey Mike, We are working on providing a script to you.
