### ISSUE TITLE
Ability to run sidekiq along with rails server

### ISSUE THREAD

**Issue by uxxman** [mperham/sidekiq#4747]
Since this got added to rails 6.1.rc, https://github.com/rails/rails/commit/868866c1fd7f6c79fd48d90febb1fd02a83380e1, how can we use this to start sidekiq along with rails server, so that in development the developer doesn't need to remember to run sidekiq in a separate terminal everytime.

**Comment by mperham** [comment]
Run [foreman](https://github.com/ddollar/foreman).

**Comment by sedubois** [comment]
@mperham it seems to me relying on Rails' API would make running sidekiq in dev much easier. I always launch the Rails dev server using IntelliJ IDEA (a cousin of RubyMine) to have debugging, coverage, etc. But I'm not aware of a way to start foreman from the IDE while having those debug tools, meaning I instead need to stick to Rails' default async queue adapter.

**Comment by mperham** [comment]
@sedubois Like it or not, the Ruby world is historically focused on the command line. IDEs are popular but most tooling assumes comfort with the CLI as it is cross-platform and scriptable.

There's also a number of questions I have:

* Right now when you run `rails s`, Sidekiq does not start. If I add this feature, now Sidekiq will start every time. For literally every existing Sidekiq user, this will be a surprise. It will slow down their server bootup and take more memory. How do I document and educate users so they aren't shocked by this change?
* Is it ok if Sidekiq's logs are mixed in with (e.g) puma's logs? Should Sidekiq use the Rails logger instead when in-process?
* Sidekiq assumes a disconnect between the Puma/Passenger process ("client") and the Sidekiq process ("server"). Now if this disconnect is no longer, this is a conceptual change I need to think about to determine the ramifications.
* Am I suppose to do this in dev only or staging and production too? How do people enable or disable this feature if they do/don't want auto-start?

IOW, there's lots of edge cases here.

**Comment by uxxman** [comment]
> * Right now when you run `rails s`, Sidekiq does not start. If I add this feature, now Sidekiq will start every time. For literally every existing Sidekiq user, this will be a surprise. It will slow down their server bootup and take more memory. How do I document and educate users so they aren't shocked by this change?

The idea is to not include this in sidekiq core functionality or default usage, but provide a code snippet, so if someone wants to hook sidekiq startup into their rails startup, they can just define this railtie inside their project. Rest is handled by ```rails s```. This way it doesn't break anything for existing users or noramal usage of sidekiq.

```ruby
class MyRailtie < Rails::Railtie
  server do
    Sidekiq.start
  end
end
```

> * Is it ok if Sidekiq's logs are mixed in with (e.g) puma's logs? Should Sidekiq use the Rails logger instead when in-process?

This behaves just like rails async job execution, which most people do in order to avoid running ```rails s``` and ```bundle exec sidekiq```separately and thus endup using two different adapters, **asnyc** for development and **sidekiq** for production.


> * Sidekiq assumes a disconnect between the Puma/Passenger process ("client") and the Sidekiq process ("server"). Now if this disconnect is no longer, this is a conceptual change I need to think about to determine the ramifications.

Sidekiq client and server remain separate as they are, the only difference is sidekiq server autostarts along side with rails server instead of just the sidekiq client running inside rails.



> * Am I suppose to do this in dev only or staging and production too? How do people enable or disable this feature if they do/don't want auto-start?

It is just meant for development and handled by rails railtie. So, it's enabled or disabled by the presence of this railtie.



According to rails docs

```ruby
# Added `Railtie#server` hook called when Rails starts a server.
# This is useful in case your application or a library needs to run
# another process next to the Rails server. This is quite common in development
# for instance to run the Webpack or the React server.
class MyRailtie < Rails::Railtie
  server do
    Sidekiq.start
  end
end
```
