### ISSUE TITLE
Blank sidekiq-web content 

### ISSUE THREAD

**Issue by overallduka** [mperham/sidekiq#4748]
Ruby version: 2.6.5
Rails version: 5.2.4
Sidekiq / Pro / Enterprise version(s): Sidekiq(free)

For some reason Sidekiq web is not showing anything(no menu, no content, nothing) after I update to 6.1.2 gem version:

![image](https://user-images.githubusercontent.com/4923856/100160267-0049c380-2e8e-11eb-8baf-019667384241.png)

Worth saying that I'm using sidekiq-cron as well:

```
    sidekiq (6.1.2)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    sidekiq-cron (1.2.0)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
```

Thank you!

**Comment by mperham** [comment]
I can’t debug a screenshot.

**Comment by ispyropoulos** [comment]
Same here with Sidekiq 6.1.2 (Rails 6.0.3.4, Ruby 2.7.2). I had to revert back Sidekiq 6.0.6 to bring back the UI. I am not sure though which of the in between version caused the regression  `¯\_(ツ)_/¯`

I also tried the 09305a09090ed37f0f32f0f1e097457b41101f6f commit in master with no changes in the behaviour.

**Comment by mperham** [comment]
Upgrade newrelic_rpm?

**Comment by ispyropoulos** [comment]
> Upgrade newrelic_rpm?

I don't have `newrelic_rpm` gem in the application I am afraid.

**Comment by mperham** [comment]
Ok It has been a problem for some. You’ll need to provide an app which
reproduces the problem.

**Comment by jwcooper** [comment]
I had this same issue and upgrading newrelic_rpm fixed it for me. 

I created a basic test app, and couldn't reproduce the issue.

Maybe this will help you as a jumping off point to find the issue:

```
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
  gem 'sidekiq'
end

require 'rails'
require 'active_record'
require 'action_controller/railtie'
require 'minitest/autorun'
require 'logger'
require 'sidekiq/web'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

class TestApp < Rails::Application
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  routes.draw do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

run TestApp
```
run with `puma config.ru`

**Comment by vsrnth** [comment]
removing `newrelic_rpm` gem fixed the issue for me.

**Comment by justinthiele** [comment]
Upgrading the newrelic gem fixed it for me.

**Comment by mperham** [comment]
`bundle up newrelic_rpm` is the fix.
