### ISSUE TITLE
Bulk Queueing + ActiveJob... Should it work?

### ISSUE THREAD

**Issue by njt1982** [mperham/sidekiq#4750]
Hi,

I have a simple ActiveJob.. eg:

```
class ThingyJob < ActiveJob::Base
  queue_as :list

  def perform(thingy_id, other_param = nil)
    Rails.logger.info "JOB -- Working on #{thingy_id}, with other param: #{other_param}"
    ProcessThingyService.new(Thingy.find(thingy_id), other_param).sync
  end
end
```

This works if I do a `ThingyJob.perform_later 123`... But if I do this:

    Sidekiq::Client.push_bulk('class' => ThingyJob, 'args' => [[123], [456], [789]])

I get this error:

    NoMethodError: undefined method `jid=' for #<ThingyJob:0x000055adf2c9d6c8>

Looking at the code, I get a vague impression its intended to work with Worker classes and not ActiveJob?

**Comment by mperham** [comment]
Yep, Many Sidekiq specific APIs only work with Sidekiq::Worker. This is one.

**Comment by njt1982** [comment]
@mperham fab - thought so. Might be worth mentioning this on the Bulk Queueing page. Would have saved me an hour of debugging 🤣

**Comment by mperham** [comment]
Ah, I didn't know there was a Bulk Queueing page! The wiki is publicly editable, sometimes too much so, you are welcome to edit. 😂

**Comment by njt1982** [comment]
https://github.com/mperham/sidekiq/wiki/Bulk-Queueing

I shall add a line :)

**Comment by njt1982** [comment]
Added: https://github.com/mperham/sidekiq/wiki/Bulk-Queueing/e25ff3b5608a63cb462567a5b21dbb0f36cc2f22
