### ISSUE TITLE
[ent] retain_history breakdown by queue?

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4754]
Would it be feasible to tag `capture_default(stats)` metrics with `queue`?

**Comment by mperham** [comment]
I don’t understand.

**Comment by dudo** [comment]
```ruby
s.gauge("sidekiq.retries", stats.retry_size)
s.gauge("sidekiq.dead", stats.dead_size)
s.gauge("sidekiq.scheduled", stats.scheduled_size)
```

These metrics. We'd like to see "one graph per" queue. We have some custom scripts that inject this, too, but they're a bit heavy, and was wondering if it'd be something worth adding upstream.

![image](https://user-images.githubusercontent.com/2963800/101081803-6950cb80-355f-11eb-8bc7-7b752c5e34f2.png)

**Comment by mperham** [comment]
Those aren’t queues in Sidekiq’s terminology, those are scheduled sets which store jobs until they are ready to be enqueued and there’s only one of each whereas you can have N custom queues.

**Comment by mperham** [comment]
So if you want to graph the retry “queue” size, you can graph that gauge. I’m not sure what else to say.

**Comment by dudo** [comment]
Ahhhh, I see. Thanks for the clarification! It seems like we were looking to get info about where a job is going (when scheduled), and where it came from when it's dead or waiting to be retried. I suppose that info is also available from other metrics, though.
