### ISSUE TITLE
Concurrency in Rails 6.1.0.rc leads to problems with ActionText::Content.renderer 

### ISSUE THREAD

**Issue by marckohlbrugge** [mperham/sidekiq#4756]
Ruby version: 2.7.1p83
Rails version: 6.1.0.rc2
Sidekiq version: 6.1.2 

### Context

Rails 6.1.0 changes the way `ActionText::Content.renderer` is set. I might be using the wrong vocabulary as I'm not familiar with the related concepts. But it seems like the renderer is now memoized within the thread to save memory. See the full changes here:

- https://github.com/rails/rails/commit/614e813161ad8f6e13ad19aedd577acdd976d9d6
- https://github.com/rails/rails/pull/38714

### Problem

Using `ActionText::Content.renderer` within a Sidekiq-powered background job is erratic. It works fine without concurrency. But with concurrency `ActionText::Content.renderer` often is nil leading to all kinds of problems. For example when using ActionText within the background job.

### Demo

Clone the following git repository: https://github.com/marckohlbrugge/rails-sidekiq

Use rails console to queue a bunch of jobs:

```ruby
10.times { HelloWorldJob.perform_later }
```

Tail the log file and look for: "Renderer: …" when it starts logging.

```sh
tail -f log/development.log
```

Run Sidekiq without concurrency:

```sh
bundle exec sidekiq -c 1
```

Notice how the logs look fine. Renderer is always set.

```
[ActiveJob] [HelloWorldJob] [65dc7ec0-9805-41ff-86fd-5fcf2cdf9fc5] Performing HelloWorldJob (Job ID: 65dc7ec0-9805-41ff-86fd-5fcf2cdf9fc5) from Sidekiq(default) enqueued at 2020-12-07T01:15:26Z
[ActiveJob] [HelloWorldJob] [65dc7ec0-9805-41ff-86fd-5fcf2cdf9fc5] Renderer: #<ActionController::Renderer:0x00007ff8e1924f00>
[ActiveJob] [HelloWorldJob] [65dc7ec0-9805-41ff-86fd-5fcf2cdf9fc5] Performed HelloWorldJob (Job ID: 65dc7ec0-9805-41ff-86fd-5fcf2cdf9fc5) from Sidekiq(default) in 0.1ms
[ActiveJob] [HelloWorldJob] [31ca3da1-56e0-4e4e-a944-77919b241c03] Performing HelloWorldJob (Job ID: 31ca3da1-56e0-4e4e-a944-77919b241c03) from Sidekiq(default) enqueued at 2020-12-07T01:15:26Z
[ActiveJob] [HelloWorldJob] [31ca3da1-56e0-4e4e-a944-77919b241c03] Renderer: #<ActionController::Renderer:0x00007ff8e1924f00>
[ActiveJob] [HelloWorldJob] [31ca3da1-56e0-4e4e-a944-77919b241c03] Performed HelloWorldJob (Job ID: 31ca3da1-56e0-4e4e-a944-77919b241c03) from Sidekiq(default) in 0.09ms
```

Now repeat those steps, but with concurrency (e.g. `bundle exec sidekiq -c 5`). You will notice the logs are now showing something different. The renderer is often nil.

```
ActiveJob] [HelloWorldJob] [ae0dd62e-4222-4b58-82f9-4da0ed43c2dc] Performing HelloWorldJob (Job ID: ae0dd62e-4222-4b58-82f9-4da0ed43c2dc) from Sidekiq(default) enqueued at 2020-12-07T01:20:11Z
[ActiveJob] [HelloWorldJob] [e7354d55-1366-42f2-91f7-71066ef4055a] Performing HelloWorldJob (Job ID: e7354d55-1366-42f2-91f7-71066ef4055a) from Sidekiq(default) enqueued at 2020-12-07T01:20:11Z
[ActiveJob] [HelloWorldJob] [f6183325-4fcc-4d38-9128-f306934ccc37] Performing HelloWorldJob (Job ID: f6183325-4fcc-4d38-9128-f306934ccc37) from Sidekiq(default) enqueued at 2020-12-07T01:20:11Z
[ActiveJob] [HelloWorldJob] [7eb1bad4-5f7d-402f-9e81-cda240d94b11] Renderer: #<ActionController::Renderer:0x00007fb04b26e1b8>
[ActiveJob] [HelloWorldJob] [7eb1bad4-5f7d-402f-9e81-cda240d94b11] Performed HelloWorldJob (Job ID: 7eb1bad4-5f7d-402f-9e81-cda240d94b11) from Sidekiq(default) in 105.92ms
[ActiveJob] [HelloWorldJob] [ae0dd62e-4222-4b58-82f9-4da0ed43c2dc] Renderer:
[ActiveJob] [HelloWorldJob] [ae0dd62e-4222-4b58-82f9-4da0ed43c2dc] Performed HelloWorldJob (Job ID: ae0dd62e-4222-4b58-82f9-4da0ed43c2dc) from Sidekiq(default) in 10.28ms
[ActiveJob] [HelloWorldJob] [f6183325-4fcc-4d38-9128-f306934ccc37] Renderer:
```

### Notes

This might be related to https://github.com/mperham/sidekiq/issues/4216

I haven't tried this with regular Sidekiq workers as I'm not familiar with them. As you can see from the commits in my repo however it's quite easy to replicate the issue, so hopefully someone can try with non-ActiveJob Sidekiq workers as well.

I'm not 100% sure this is an issue with Sidekiq. It might be an issue with ActiveJob instead. I was about to try the same code with Delayed Job, but then realized it doesn't support concurrency as far as I could tell.

**Comment by mperham** [comment]
This sounds like a Rails thread safety issue. Sidekiq uses a railtie to integrate with Rails but there’s nothing specific about ActionText.

**Comment by mperham** [comment]
I would search the rails issue tracker for action text changes. I don’t know how to fix this.

**Comment by marckohlbrugge** [comment]
Update: I've tried with a regular Sidekiq Worker and it leads to the same problem. See updated repo. So it doesn't seem to be an issue with ActiveJob. It might indeed still be an issue with Rails (rather than Sidekiq).

**Comment by marckohlbrugge** [comment]
@mperham Ah yes, I did search the code changes in Rails. They made some [thread-related changes](https://github.com/rails/rails/commit/614e813161ad8f6e13ad19aedd577acdd976d9d6 ) to `ActionText::Content.renderer` (which is used for ActionText, but in other places).

If you think it's a problem with Rails rather than Sidekiq, I'll open an issue there instead. Thanks!
