### ISSUE TITLE
Add API for running a Sidekiq server in-process

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4758]
Today, Sidekiq will only execute jobs if started at the command line via `sidekiq` or `sidekiqswarm`. Rails 6.1 adds a new railtie API (#4747) for starting development tools inside the Rails server process. Apps like Discourse have created their own unofficial solutions for running Sidekiq in-process.

Research and prototype an API for booting a Sidekiq server in-process. Some things to account for:

0. Is there a big demand for this?
1. Should this Sidekiq instance be a singleton? Can I start two or N Sidekiq instances in the same process?
2. How does this mesh with the new Ractor API? Can we reduce the amount of global data and APIs we touch?
3. How does this affect Sidekiq's "client" and "server" model when one process is both?
4. All configuration today is done with global APIs, how can we refactor to configure per-instance?

The closest thing to this API we have today is `Sidekiq::Launcher`.

**Comment by ioquatix** [comment]
I can give you some ideas about this since all the applications (falcon, rubydns) are all built in an isolated way.

0. I would say it no, but that it does encourage good design/isolation.
1. My opinion about this is yes, instances should be isolated so starting one or more should not be a problem.
2. Your code should not need to know about Ractor. IF someone decides to make multiple ractors, your code should still work (by being isolated).
3. If the code is isolated, it should not matter.
4. Configuration should be captured in an isolated, per-instance way.

We can elaborate on any of the above.

**Comment by sedubois** [comment]
0. I would first make this work in dev for the reasons mentioned [here](https://github.com/mperham/sidekiq/issues/4747#issuecomment-739908038). This new API could additionally allow to run test and prod the same way, offering more predictable deployments.

**Comment by adamniedzielski** [comment]
I read through the code in `Sidekiq::CLI` and this seems difficult to achieve, especially in a long-running project like Sidekiq where we need to move in small steps.

> Configuration should be captured in an isolated, per-instance way.

Agreeded 👌 Currently configuration is split between:
- options passed to the server process
- YAML config file
- initializer

and it's all global.

> How does this affect Sidekiq's "client" and "server" model when one process is both?

> If the code is isolated, it should not matter.

Currently it does matter. The simplest example is https://github.com/mperham/sidekiq/blob/6a6fda35fa9d07c4fe8ed3b05609a0eba6781101/lib/sidekiq.rb#L68-L93

with `redis` being the conflicting option.

I think that the next step here would be to introduce an abstraction like `Sidekiq::Config` that stores all possible config parameters from different sources. `Sidekiq` could then store one particular instance of `Sidekiq::Config`, but there could be more instances.

That's still a big refactoring so I wonder if somebody has an idea for taking a smaller step 🤔

**Comment by mperham** [comment]
Embedded mode is now available on the 7-0 branch.
