### ISSUE TITLE
Sidekiq Batch - on success not being called

### ISSUE THREAD

**Issue by Blokh** [mperham/sidekiq#4760]
Ruby version: 2.5.5
Rails version: 5.1.6
Sidekiq Pro version: 4.0.5

Greetings,
We've been having issues with Sidekiq Batches.
The issue that after all the processes are finished. the on success is not being called.
![image (5) (1)](https://user-images.githubusercontent.com/35891501/101681865-7bed6800-3a6b-11eb-9a3b-d3527d67a10d.png)

The process is quite long and takes over 1 hour to complete.
 But I see no sign of a failing job or any reason the process will not continue to on_success callback.

If anyone has any clue why this issue might occur, I would love to hear about it.

Thanks in advance,
Daniel

**Comment by mperham** [comment]
Show me the code that is creating the batch.

**Comment by Blokh** [comment]
` 
def split_to_batches
    batch = Sidekiq::Batch.new

    init_batch_callback(batch)

    batch.jobs do
      number_of_batches(collection_size).times do |csv_number|
        perform_as_batched(csv_number)
      end
    end
  end

  def init_batch_callback(batch)
    batch.on(
      :success,
      Csvs::SuccessWorker,
      bid: batch.bid,
      user_id: @user_id,
      klass: @klass,
      export_params: @export_params,
      collection: @collection_sql,
      deliver_email: @deliver_email,
      delivery_params: @delivery_params
    )
  end

  def perform_as_batched(csv_number)
    Csvs::BatchWorker.perform_async(
      {
        klass: @klass,
        collection_sql: @collection_sql,
        user_id: @user_id,
        export_params: @export_params
      }.merge!(delivery_params: @delivery_params),
      limit(csv_number, collection_size),
      offset(csv_number)
    )
  end
`

**Comment by Blokh** [comment]
Is there a chance that the on_success process if failing but it does not appear either in RetrySet or in Sidekiq Queue?

**Comment by mperham** [comment]
I doubt it. You could also try upgrading versions but I'm not aware of any batch reliability bugs fixed since 3.7.0. Show me your initializer and the code for Csvs::BatchWorker. Also, verify your Redis has the correct memory policy:

https://github.com/mperham/sidekiq/wiki/Using-Redis#memory
