### ISSUE TITLE
Unique jobs: ability to retrieve job id of worker that holds the unique lock

### ISSUE THREAD

**Issue by niborg** [mperham/sidekiq#4762]
Feature suggestion: ability to retrieve the job id of a job that is holding the unique lock that prevents jobs with identical arguments/queues from getting enqueued.

Scenario:

We have a worker that submits important information to a third party. That third party might take 1-2 minutes to respond. When a user submits this information, we return the job id and have the frontend poll for the status of this job. Pretty standard pattern.

We want to prevent users from resubmitting this information. So, if there is a worker pending, a resubmission by the user would simply return the job id of the currently enqueued/running job and not start a new job. It would be great to use unique jobs to achieve this, but it does not seem that the API supports the return of the currently enqueued/running job.

Solving this problem by keeping track of a running worker's job in, say, Redis, and retrieving it when there is an attempt to create a duplicate job makes using unique jobs becomes superfluous. Unique jobs could kill 2 birds with 1 stone here.

**Comment by mperham** [comment]
I can see how this would be really useful but I can't determine a way to implement this without making the unique implementation more complicated. Today the only thing stored with the unique lock is the timestamp when it expires. To expand the data stored would require it to move to a Hash structure and/or use Lua.

Here's a possible API.

```ruby
jid = SomeJob.perform_async(1, 2, 3)
# can't return the current JID here because then we can't tell if the push worked or not
return if jid

# ok, no JID which means the push failed due to uniqueness.
current_jid = Sidekiq::Enterprise::Unique.current_jid_for(SomeJob, "default", 1,2,3)
# current_jid can be nil!
```

This API would also be racy. The job push could fail due to uniqueness but the lock be deleted a microsecond later, meaning your check for the existing JID could very rarely also return nil.

WDYT? Am I missing a better approach?

**Comment by niborg** [comment]
I think the API you proposed is reasonable. Most using Sidekiq know that it isn't a perfect world and that you can expect racey conditions like this -- in which case you would just simply push the job again. Alternatively I think this might be the same without the race condition you specified:
```ruby
jid = Sidekiq::Enterprise::Unique.current_jid_for(SomeJob, *args) || SomeJob.perform_async(*args)
```
But this still runs into a rare race condition when another thread/process does `SomeJob.perform_async(*args)` just after we check `current_jid_for`. Even home-baked solutions could run into this.

Anything wrong with something like:
```ruby
jid = SomeJob.perform_async_or_retrieve_current_jid(args) # should raise error if job not set to be unique
```
I'm ignorant of the locking features available under the hood, but does this provide an opportunity for Sidekiq to lock the uniqueness row without developers having to fret? Or perhaps this is only possible if the unique lock also stored a job id.

**Comment by mperham** [comment]
This is getting too complex for me to feel comfortable adding it. You should be able to implement this with a few Redis calls but I can't easily shoehorn this into existing APIs.  Something like:

```ruby
user_id = 123
jid = SomeUniqueJob.perform_async(user_id)
if jid
  Sidekiq.redis do |c|
    c.pipelined do
      c.set("op-#{user_id}", jid, ex: 120) # expire in 2 minutes
      c.set("result-#{jid}", "Starting", ex: 120)
    end
end

# poll for "Done", will also exit if key expires after 2 min
loop do
  current = Sidekiq.redis{|c| c.get("result-#{jid}") }
  break current if current != "Starting"
  sleep 1
end
```

```ruby
def perform(user_id)
  ... do work ...
  Sidekiq.redis {|c| c.set("result-#{jid}", "Done", ex: 120)
end
```
