### ISSUE TITLE
Sidekiq Web UI return error 'Request Header Or Cookie Too Large'

### ISSUE THREAD

**Issue by tai-acall** [mperham/sidekiq#4769]
Hello,

I'm running Ruby on Rails API server with sidekiq, puma and nginx as proxy server. not familiar with it so I follow the instruction 'proxying-the-web-ui' in the monitoring part as following URL.

https://github.com/mperham/sidekiq/wiki/Monitoring#proxying-the-web-ui

API URL:
https://my.domain.com/

Sidekiq Web UI URL(I hope):
https://my.domain.com/sidekiq

then I tried to put some nginx setting

        `location /sidekiq {
          proxy_set_header X-Script-Name /sidekiq;
          proxy_pass https://my.domain.com/sidekiq;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header X-Real-IP $remote_addr;
        }`

but I got nginx error '400 Bad Request Request Header Or Cookie Too Large'

maybe I miss something?

any advice will be helpful.

**Comment by mperham** [comment]
Open your browser's Network inspector and delete the cookies for your site so you start fresh. Alternately, just clear all cookies.

**Comment by tai-acall** [comment]
@mperham

thanks for the advice.

I just clear my cookie and cache then the error became to '500 Internal Server Error'.

here is the nginx log.

2020/12/23 10:21:37 [alert] 1231#0: *791 768 worker_connections are not enough while connecting to upstream, client: xxx.xxx.xxx.xxx, server: my.domain.com, request: "GET /sidekiq HTTP/1.0", upstream: "https://xxx.xxx.xxx.xxx:443/sidekiq", host: "my.domain.com"

I'm testing on my staging server and even the server just restarted still shows the same error.
still not understand what's the 'worker_connections are not enough' means.

**Comment by mperham** [comment]
That’s an error in nginx, not part of Sidekiq. Check your app server log.

**Comment by tai-acall** [comment]
@mperham 

I notice that the proxy source setting in the nginx config might not right because I'm using puma as app server source.

I made some change and here is the latest one.

        upstream puma-source {
                server unix:/path/to/sockets/puma.sock;
        }

         location /sidekiq {
          proxy_set_header X-Script-Name /sidekiq;
          proxy_pass http://puma-source/sidekiq;

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header X-Real-IP $remote_addr;
        }


here is the app server log.

`2020-12-23 21:23:12 +0900 [INFO]::[6a682020-b23a-44ec-8057-ea972cc6bb98] Started GET "/sidekiq" for xxx.xxx.xxx.xxx at 2020-12-23 21:23:12 +0900`

it seems app server receive the access to path '/sidekiq' but stuck in some where, my server return '504 Gateway Time-out'.

I also tried to access my Rails App run in the same server and it seems fine.
how do I troubleshooting this?

**Comment by mperham** [comment]
I can’t debug puma and nginx for you.
