### ISSUE TITLE
sidekiq_retry_in and retry not play very well - v5.1.3 

### ISSUE THREAD

**Issue by GiboMac** [mperham/sidekiq#4771]
Ruby version: 2.4.2
Rails version: 5.2.0
Sidekiq : 5.1.3

```ruby
class A
  include Sidekiq::Worker
  sidekiq_options retry: false, queue: 'a',  backtrace: true
  
  def perform(*args)
    [....]
    if error
      B.perform_in(5.minutes, *args)
    end
  end
end

class B
  include Sidekiq::Worker
  sidekiq_options retry: 1, queue: 'b',  backtrace: true
   
  sidekiq_retry_in { 60 * 30 }

  def perform(*args)
    [....]
    if error
      raise 'Error'
    end
  end
end
```

Hello!
I have this situation, when i call A worker, if error, i schedule a new job with same params to another queue
In this new B worker, i've setup retry to 1 and sidekiq_Retry_in { 30 * 60 }

After ther first schedule of the B worker after 5 minutes, the next B worker retry is in 30 minutes.

But if an error occur in B worker, is rescheduled ignoring the retry option.

I'm missing something?

Thanks

G

**Comment by mperham** [comment]
I don’t understand.

**Comment by GiboMac** [comment]
A worker run once
If something wrong i rescue from error and schedule a new worker B after 5 minutes
This new B worker has 1 retry and sidekiq_retry_in 30 minutes

Why if B worker fail after 1 retry, is not going to Dead queue, but it's rescheduled?

**Comment by mperham** [comment]
I don’t know why.  Have you tried upgrading Sidekiq to a recent version?
