### ISSUE TITLE
Sidekiq Instance VS Workers

### ISSUE THREAD

**Issue by kgeoir** [mperham/sidekiq#4773]
Ruby version: 2.7.0
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): 6.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

sidekiq.yml
```
production:
  :concurrency: 20
:queues:
  - default
```
initializer:

```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end

```

Hello,

  I am not reporting a bug but I found a strange issue about processing: I have 2 servers running sidekiq worker and only 1 job that compute stuff before indexing in elasticsearch.  In order to accelerate the processing and seeing that CPU load average is at 1 on a 12Core VM, I increased the number of worker 20 to 25 to 50 and even more. It did not really changed anything. However, I decided to to launch on the same server a second instance of sidekiq with 25 workers: Boom it finally doubled my indexing rate. But I dont understand why. Can anyone explain what's wrong in my configuration/expectation?
  
  Thank you

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
A Ruby process cannot use more than one core. You need this if you want to scale to all cores automatically:

https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process

**Comment by kgeoir** [comment]
I am not sure to understand, each worker is a separate process and I am not doing parallelisation in my worker my point is more about the fact that my workers are not using all the power of my server: on a 12 core machine having 20 workers with a queue of 1M job should load the machine which is not the case.

**Comment by mperham** [comment]
Each worker is not a separate process. -c controls threads.

**Comment by kgeoir** [comment]
Alright, very clear!

Thank you
