### ISSUE TITLE
Death event not propagated from child batches

### ISSUE THREAD

**Issue by Draiken** [mperham/sidekiq#4774]
Ruby version: 2.7.2p137
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): sidekiq-pro-5.2.0

We are using sidekiq for some complex flows with trees of batches.
I have a scenario, where a child batch has all of its children die triggering the death callback, but the parent batch does not get the death callback triggered.

```
Batch 1 (not dead?)
--> Batch 2 (dead)
-----> Job 1 (dead)
```

From my understanding, when batch 2 dies and triggers the death callback it should also trigger the death callback from the parent batch, given all of its children are dead too.

I read through the docs many times and couldn't find any known edge case related to sub-batches, so I believe this is a bug.

**Comment by mperham** [comment]
Correct, right now the death callback does not propagate up the ancestry chain. I will investigate.

**Comment by mperham** [comment]
I'm not convinced the death callback should propagate upwards. The death callback is meant to signal to you that you need to fix dead job(s) for the batch to finish. Once that dead job is fixed and runs, the batch will finish and the parent batch will finish, etc.  If the parent batch has a job that dies, it too will get a death callback for the same reason.

WDYT?

**Comment by Draiken** [comment]
For me, it breaks my expectations when using sub-batches. For all other purposes we treat sub-batches as jobs, but then for this one case, it behaves differently than a job.

When doing complex workflows, I'd expect the parent batch that kicks off other batches to also get the death triggered if one of its children dies, regardless if the child is a job or a batch. From the parent batch's point of view, everything seems normal, but in reality it would never finish successfully or die.

Like you said, the intent is to signal that you need to fix a dead job, but we might have death callbacks stored on the parent batch, and not each of the many child batches. We could in theory have a deeply nested tree of batches, so I think it's important we propagate this event up the chain. The signal to the parent batch would also be correct, since we have to deal with the dead job if we ever want to complete the parent batch too.

To give you a bit more context, I was using these hooks to track the overall state of a big operation that triggers a tree of batches. So I'd hook onto the parent batch to get an overall success/failure state. Unfortunately if the death state doesn't propagate, I simply can't do that, and I'd have to individually hook into every sub-batch to detect any deaths, or change my approach completely.

**Comment by mperham** [comment]
If two child batches die, should the parent batch get two death callbacks or only one?

**Comment by mperham** [comment]
And thanks, that's really useful context.

**Comment by Draiken** [comment]
I would say once, similar to what happens with jobs. Once a single job dies, we get the callback. So once a single sub-batch dies, we get the callback.
