### ISSUE TITLE
Adapters besides redis?

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4776]
Hello! Very high level question. Have you considered supporting other data stores?

- SNS/SQS
- rabbitMQ
- kafka
- SQL
- whatever faktory was using originally (rocksdb)
- tin can and string

I realize some of those are unrealistic, just curious what's been thrown around, historically.

I'm working on a project, for the second time now, that is using SQS specifically. Shoryuken gets tossed around as a viable option for SQS, but I don't love the idea of using a 3yo fork to handle job processing - especially since I rely on pro and ent so much!

I've also built a custom daemon to fetch messages from SQS, just to fan out to sidekiq. Lots of solutions, for sure.

So, question - where do you stand on making sidekiq able to talk to various backends, with some sort of adapter pattern?

**Comment by mperham** [comment]
Answered here: https://github.com/mperham/sidekiq/wiki/FAQ#wouldnt-it-be-awesome-if-sidekiq-supported-mongodb-postgresql-mysql-sqs--for-persistence
