### ISSUE TITLE
perform_async doesn't wait for successful queueing to Redis

### ISSUE THREAD

**Issue by sfcgeorge** [mperham/sidekiq#4777]
Ruby version: 2.7
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): 6.1.2

Searching issues and wiki I couldn't find anything about this but hopefully it's an easy answer.

Does `perform_async` wait for the job to be queued to Redis before returning?

I ask because I wrote a Rake task that simply queues a job and then ran that in Heroku release phase (which is essentially a one-off dyno) but sometimes I believe the job was not being queued.

I deployed the same app to 3 Heroku servers (staging, demo, and production) and 2 of them didn't have the task queued but 1 did, so I don't think my code was bad. I've since added a `sleep 10` after the `perform_async` and now the job is reliably queued. 

So it's as if `perform_async` doesn't wait for a successful response from Redis, and Heroku doesn't wait for TCP connections to be finished before shutting down dynos. Perhaps.

**Comment by mperham** [comment]
Yes, it does wait.

**Comment by sfcgeorge** [comment]
Hmm then I have no idea how Heroku is killing the dyno before that. Heroku support doesn't know either but I'll try them again if you don't have any further thoughts.

**Comment by mperham** [comment]
Nothing rings a bell but I have very little info.
