### ISSUE TITLE
Unexpected SSL error upon 5.x to 6.x upgrade.

### ISSUE THREAD

**Issue by claymcleod** [mperham/sidekiq#4779]
Ruby version: 2.7.0
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): 6.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

-----

Hey there,

We've just updated from `sidekiq v5.2.8` to `sidekiq v6.1.2` using the upgrade guide [here](https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md). I noticed in [this commit](https://github.com/mperham/sidekiq/commit/4c2ea6ebad0955956f01094e7551a6d41934fbfb) (post v5) it appears you've updated the default driver from `ruby` to `hiredis`. 

In looking at the upgrade guide, I didn't see any mention of this. The rubber meets the road because we use end-to-end SSL to connect Sidekiq with Redis, and [SSL is not supported by hiredis](https://github.com/redis/redis-rb/blob/master/lib/redis/connection/hiredis.rb#L17-L18).

So two thoughts on potentially how to proceed:

- I'm not the most familiar with the sidekiq code base, but I think a reasonable thing to do would be to expose some option to configure the driver so that `ruby` could be used in cases where SSL is required.
- Perhaps this detail should be added to the upgrading guide so future developers can account for this?

If you're agreeable with the approach, I can offer to put something together. However, I'm not a Ruby expert and certainly not a Sidekiq expert, so you may find the solution to be subpar. I'm happy to give it a shot though.

**Comment by mperham** [comment]
That’s a benchmark script. The default is the plain ruby driver.

**Comment by claymcleod** [comment]
Ah okay, let me take a look and see if I can uncover further what has happened here then.

**Comment by claymcleod** [comment]
Okay, I think I've found that this was unrelated now. Closed, I'll reopen if I determine otherwise.
