### ISSUE TITLE
Job Tuneup

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4783]
I’d like to start an ongoing series of public video chats where I help people with Rails apps using Sidekiq tune and optimize their usage. Ideally:

* the chats are public and can be viewed later (e.g. on YouTube)
* apps must be using Sidekiq but don’t need to be customers
* developers must be willing to show small bits of their app publicly

The goal is for developers to learn from these chats so they can be as productive as possible with Sidekiq. Any thoughts on the best way or set of services to use to accomplish this?

**Comment by fig** [comment]
This sounds like an awesome initiative. I am always delighted to see product developers aiding and guiding their consumers. Sounds like a win win!

**Comment by dbackeus** [comment]
Zoom (paid) or Jitsi (free) + stream to YouTube is probably your best bet if this is to be in conference format (ie. many people talking to each other in realtime). Unfortunately there are no conferencing alternatives that can do reliable high quality video + audio though (when optimising for low latency you pretty much have to sacrifice quality). To avoid quality completely going down the drain you could make it a requirement for participants to join with a high quality mic + headphones + cabled internet (WiFi is WAY more unreliable for low latency streaming than people imagine).

If image / audio quality is important you would be better off pre-recording screencast style based on some case-studies ahead of time. But then you miss the "chat" aspect.
