### ISSUE TITLE
Is there a way to store BUNDLE_GEMS__CONTRIBSYS__COM in Rails credentials for Sidekiq PRO?

### ISSUE THREAD

**Issue by hubertjakubiak** [mperham/sidekiq#4785]
I would like to use somehow `Rails.application.credentials.bundle_gems_contribsys_com` in the codebase. Possible? We don't use ENVs for storing secret access tokens. That would be one exception.

**Comment by mperham** [comment]
Not that I’m aware of, Bundler is external to Rails.
