### ISSUE TITLE
How to enable TLS for Redis 6 through Sidekiq initializer?

### ISSUE THREAD

**Issue by ogirginc** [mperham/sidekiq#4786]
I am not sure if this is the right place to ask but since [Help wiki](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#help) was quite welcoming I wanted to give it a shot!

Just deployed an RoR app on Heroku-20 stack with Redis 6 (Heroku Premium 0 add-on). I keep getting the error below:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
```

My understading is; I do need to enable TLS. However, I couldn't figure out how. 

Can anyone help, please? Thanks!

**Comment by mperham** [comment]
I think you’ll need to contact Heroku support for help with the add on. That’s not a Sidekiq error but a lower level issue.

**Comment by ogirginc** [comment]
I will do that but was hoping maybe someone did encounter it before. Anyway, thanks a lot for the quick response! Also, I will update this issue, when I have any. 👍

**Comment by ogirginc** [comment]
Solved through adding `OpenSSL::SSL::VERIFY_NONE` to `verify_mode`.

```
Sidekiq.configure_server do |config|
  config.redis = { ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
end

Sidekiq.configure_client do |config|
  config.redis = { ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
end
```

For more detail: https://stackoverflow.com/questions/65834575

**Comment by kreintjes** [comment]
Thanks @ogirginc for this solution! At first I thought it didn't work, but apparently that was because the ActionCable Redis adaption was still causing problems. For anyone running into that problem as well, here is the fix: https://github.com/rails/rails/issues/42036

**Comment by TonsOfFun** [comment]
It might be worth updating the Sidekiq Wiki under Heroku deployments or using Redis 6.
> As of Redis version 6, Hobby plans support both TLS and unencrypted connections, while production plans require TLS connections. For hobby plans you can find the unencrypted (plaintext) and TLS URIs in your app’s config vars REDIS_URL and REDIS_TLS_URL respectively. For Premium, Private, and Shield plans on version 6 your REDIS_URL config var will use the rediss: scheme, and you must enable TLS in your Redis client’s configuration in order to connect to a Redis 6 database.
https://devcenter.heroku.com/articles/heroku-redis#create-a-new-instance

**Comment by mperham** [comment]
@TonsOfFun There's nothing in that paragraph that actually requires action. Sidekiq should work with it all. It would only confuse people.

That said, disabling certificate verification with `VERIFY_NONE` is never recommended. Instead, read the Redis provider documentation on how to trust their self-signed cert.

**Comment by TonsOfFun** [comment]
I appreciate the reply @mperham cause I'm a bit confused at this point what Heroku wants me to do.

I agree disabling verification feels wrong, but that is in their [documentation](https://devcenter.heroku.com/articles/heroku-redis#connecting-in-rails).  I'll contact their support to see if they have a better recommendation. Thanks!

**Comment by ogirginc** [comment]
> I agree disabling verification feels wrong, but that is in their documentation. I'll contact their support to see if they have a better recommendation. Thanks!

fyi, @TonsOfFun, `VERIFY_NONE` was Heroku support's suggestion to me at that time.

**Comment by TonsOfFun** [comment]
I appreciate the reply @ogirginc thanks! 

Yes, I saw your stackoverflow, blogpost, and their docs, but it just feels wrong. Another option I've heard is just request they keep your app on Redis 5. Wondering why that seems to be their only two suggestions offered. Currently my client's staging environment is Redis 6 and production is Redis 5, so failure is pending the add-in's upgrade 😅

**Comment by mperham** [comment]
It's possible Heroku support could give you the CA bundle for their self-signed cert so you could configure the Redis client to trust it.

**Comment by jc00ke** [comment]
Got bit by this today. All I can say is: thank you all for documenting the issue and the fix. :pray:

**Comment by mshtawythug** [comment]
> 

Detto thank you for documenting this

**Comment by sealabcore** [comment]
If we were all using non TLS Redis before, then we start using TLS with `, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }` isn't that the same level of insecure as we were before we started using TLS with the Heroku Redis add on?

Just be sure you're not sending private data, tokens, or keys into Redis if you're setting `ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }`.

I'm only doing this because I want to use Sidekiq 7.0, which requires Redis 6, which requires TLS on Heroku. 😅

**Comment by FutoRicky** [comment]
For anyone still having this issue, this article fixed it for me: https://www.sandipmane.dev/openssl-connection-error-with-redis6-on-heroku
