### ISSUE TITLE
Accessing Rails models from Sidekiq server middleware

### ISSUE THREAD

**Issue by brettwgreen** [mperham/sidekiq#4789]
Ruby version: 2.7.2
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): 6.1.3

initializer:
```
:concurrency: 5
:queues:
  - critical
  - default
  - low
```

We have some sidekiq middlware we are using to record events to a table in our postgres database... call it `my_jobs`.
The client middleware creates the first entry in the table, then the server middleware picks up and tries to look up the my_jobs entry, and write events like 'processing' and 'complete' in `my_job_events` table.

We're getting intermittent failures on `MyJob.find(job_id)` returning RecordNotFound errors in the server middleware. Note, we have no active_record callbacks on that model. 

We've been able to isolate it enough to realize it's a bizarre problem with rails caching. If we wrap the call in something like
```
MyJob.uncached do
   job = MyJob.find(job_id)
end
```
Then it works...

Not necessarily asking you to solve this particular weird issue, but rather asking: Is it ill-advised to be accessing our Rails models inside the Sidekiq _server_ middleware? Does that context introduce different behavior with Rails caching (maybe plugins for Redis) that could cause unanticipated problems?

**Comment by mperham** [comment]
I suspect the issue is this common one.

https://github.com/mperham/sidekiq/wiki/FAQ#why-am-i-seeing-a-lot-of-cant-find-modelname-with-id12345-errors-with-sidekiq

**Comment by brettwgreen** [comment]
Nope... there are no callbacks on our model. Already ran down that rabbit hole because it seemed similar.

**Comment by mperham** [comment]
You don't need callbacks to hit this issue. You need after_commit to fix
the issue.

**Comment by brettwgreen** [comment]
The MyJob record is being created in the client middleware, _before_ the yield, which should then push the job to the sidekiq/redis queue. It also adds the created job_id to the arguments for the sidekiq job. This record creation is not done inside a transaction, and there's no callbacks on it (so no place/reason to add an after_commit?)

Then when the server middleware picks up the job, it successfully rertrieves the job_id, but gets a RecordNotFound on the find for MyJob. 

I tried a retry loop that tries three times up to 6 seconds, and repeatedly gets RecordNotFound (intermittently, mind you.. sometimes it works outright, but it if it gets the first error, the retries never work).

I was able to get a breakpoint in there when it failed. I lot of bizarred behavior. If I did, for example, `MyJob.where(id: job_id)`, I could see the record in the array result. If I then did `MyJob.where(id: job_id).first` I get nil... bizarre. Then, when I wrapped that last call in `MyJob.uncached`, it works. That kinda proved there's something going on with caching... it's not transactions or timing.

In any case, I was trying to decide whether accessing our Models in the middleware seemed like a bad idea... it's pretty invasive and potentially messing with sidekiq durability so we are debating refactoring the entire thing.

**Comment by brettwgreen** [comment]
BTW, the refactor may involve upgrading to PRO since we did a roll your own batches implementation that uses the middleware... in this particular example, there are no 'child' jobs. Just a pretty simple job.

If we refactor away from middleware and just do PORO stuff to track historical start/processing/complete events, we'd probably need PRO batches to do that.

**Comment by mperham** [comment]
I don't know of any fundamental reason why you can't access the database in a server middleware. As you've found, there can be difficulties in getting it to behave but that's between your code and ActiveRecord. If there are problems, Sidekiq's retry can save and retry the job later.
