### ISSUE TITLE
Server middleware / ActiveJob format

### ISSUE THREAD

**Issue by lloydwatkin** [mperham/sidekiq#4790]
No bug just an FYI (as I'm not sure that Github alerts on wiki changes)...

I've added this section to the wiki which talks about the job format when writing server middleware and using activejob -- https://github.com/mperham/sidekiq/wiki/Job-Format#activejob-middleware-format

Feel free to delete/edit/etc as required :+1:

**Comment by mperham** [comment]
That's fine. Thank you!
