### ISSUE TITLE
How to log Sidekiq pro UI request on default rails logger?

### ISSUE THREAD

**Issue by marcocarvalho** [mperham/sidekiq#4792]
Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352)
Rails version: Rails 6.0.3.4

Sidekiq / Pro / Enterprise version(s): 
Using sidekiq 6.1.3
Using sidekiq-pro 5.2.1
Using sidekiq-ent 2.2.1

Hi,

We need to log the requests made to Sidekiq pro UI for audit purposes. I saw the UI uses a stand-alone rack app. There is an easy way to use the default rails logger and formatter to do that? I didn't found anything in the UI code or docs.

**Comment by mperham** [comment]
That's up to your web/app server. Sidekiq Pro's UI is a Rack app. Whatever is serving Rack requests would log the requests, e.g. puma or webrick.
