### ISSUE TITLE
Using rate limiters for throttling

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4793]
Limiting is not throttling, [I know](https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#limiting-is-not-throttling). 

I have several workers that rely on 3rd party services. Those services all have different QPS thresholds, obviously, and they all fail differently. 400, 422, 429, 500, 503, even 200 with a response body. 1 of them is particularly troublesome, where they don't actually have proper throttling on their side... if we hit them too hard, they'll just start to fall over (503s, and even other endpoints start to crap out). So we have an agreement that we'll keep the requests to less than 400 QPS. Fun stuff.

A lot of calls are event driven, so we have `HardWorker.perform_async` scattered about. We have a rate limiter middleware:

```ruby
class RateLimiterMiddleware
  UNLIMITED_LIMITER = Sidekiq::Limiter::Unlimited

  def call(worker, *)
    return yield unless (limiter = limiter(worker))

    limiter.within_limit do
      yield
    end
  end

  private

  def limiter(worker)
    limiter = worker.class.sidekiq_options['rate_limiter'] || UNLIMITED_LIMITER

    raise ArgumentError, 'Invalid limiter given' unless valid_limiter?(limiter)

    limiter
  end

  def valid_limiter?(limiter)
    limiter.is_a?(UNLIMITED_LIMITER || Sidekiq::Limiter::Base)
  end
end
```

This works nicely as a middleware. We found while using the `bucket` limiter, if we lowered the value too low, it put a heavy load on redis - 50K ops per second - up from 30K, and it slowed most operations. We saw blocked clients about double as well. I imagine this is from calling redis so many times in succession

1. pulling the job
2. checking the rate limiter
3. failing, and putting the job back in the scheduled set

So... to the question. Have you seen folks put in client middleware that checks a rate limiter (or I'm even thinking about checking queue latency), and schedules the job instead of yielding? Does that even make sense? I'm basically trying to ensure that typical `perform_async` calls are always scheduled (throttled), so that limits don't actually get hit.

I'm thinking the problem arises from the read/read/write hammering that the single threaded redis is getting hit with when under load. Is that a fair assessment?

**Comment by mperham** [comment]
Can you show me the output `redis-cli info` in production? How many jobs are executing concurrently during your busy times, i.e. what does your Busy page look like?

**Comment by dudo** [comment]
```shell
# Server
redis_version:6.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 4.4.0-1118-aws x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.4.0 20160609
process_id:9826551
run_id:4d8af7b6cd98f0717c650e3bd688e91379d618cd
tcp_port:15748
uptime_in_seconds:18047252
uptime_in_days:208
hz:10
lru_clock:0
config_file:

# Clients
connected_clients:3966
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:285

# Memory
used_memory:698879232
used_memory_human:666.50M
used_memory_rss:698879232
used_memory_peak:6707418592
used_memory_peak_human:6.24G
used_memory_lua:114688
mem_fragmentation_ratio:1
mem_allocator:jemalloc-5.1.0

# Persistence
loading:0
rdb_changes_since_last_save:19108727281
rdb_bgsave_in_progress:0
rdb_last_save_time:1607591993
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:8668112
total_commands_processed:170083965029
instantaneous_ops_per_sec:37700
total_net_input_bytes:29095130749998
total_net_output_bytes:78346771748636
instantaneous_input_kbps:7408.71
instantaneous_output_kbps:20538.73
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:2549986
evicted_keys:0
keyspace_hits:53823215257
keyspace_misses:108651969002
pubsub_channels:0
pubsub_patterns:320
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:1
slave0:ip=0.0.0.0,port=0,state=online,offset=0,lag=0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=5135,expires=4381,avg_ttl=15905975344
```

![image](https://user-images.githubusercontent.com/2963800/106648586-52b9f700-6545-11eb-9706-f95a84c41036.png)

I'm investigating something from a few months ago, unfortunately, so I don't have concrete numbers. Apparently we went from 40 sidekiq processes -> 60 -> 80 -> 60 -> 40. Which makes sense. As we had more workers capable of pulling things off the queues, the limiters started getting hit constantly. What I'm trying to figure out, without much luck so far, is why folks are saying that the rate limiting "killed redis". I don't think "kill" is literal here... Like I mentioned, blocked clients went from 250 -> 500 or so. That's honestly the only stat from the redis dashboard I'm looking at that seems abnormal.

**Comment by mperham** [comment]
Can you email me privately, mike@contribsys.com? I need to discuss a billing issue.

I don't see a good solution here. Faktory Enterprise has real queue throttling but no version of Sidekiq has it. Even fent's throttling is per-job, not per-second, e.g. only 400 jobs in-flight, not 400 per sec. You've described several hacks but, as the term "hack" implies, none of them work very well.

Here's a few blog posts on HAProxy and how it can rate limit and throttle TCP connections. You might consider a custom HAProxy instance "in front of" the service which requires a limit of 400 qps. If each call takes approximately 100ms, you can limit HAProxy's backend connection pool size to 40 so that you get a rough throttle of 400/sec. That might work ok but hard to say for sure

Let the Sidekiq jobs execute as fast as they want and if they get a connection timeout from HAProxy, discard the job or treat it like a rate limit breach and reschedule it as normal. You can also throw in a `expires_in: 10.minutes` option so the jobs don't hammer the service repeatedly if discarding is an option.

https://www.haproxy.com/blog/four-examples-of-haproxy-rate-limiting/
https://severalnines.com/database-blog/connection-handling-throttling-haproxy

**Comment by dudo** [comment]
Tell me more about Ent's per-job throttling. I don't see it mentioned in the docs. I know I can rate limit per job, but if I know the throughput of a job, I could definitely get to an acceptable solution by limiting the number of threads capable of working on a given task.

**Comment by dudo** [comment]
Ah! fent == Faktory Enterprise. Thought that was a typo. Could you backfill that feature to sidekiq ent? you could almost wrap the workers themselves in a `Sidekiq::Limiter.concurrent("worker-#{worker.class}", N, policy: :skip)`. Almost...

**Comment by mperham** [comment]
Yes, you could put a rate limiter in a custom middleware but again, that's a hack; you're still pulling the job from Redis and then pushing it right back. The blog post goes into detail why I cannot backfill.
