### ISSUE TITLE
Undefined local variable logger

### ISSUE THREAD

**Issue by kimyu92** [mperham/sidekiq#4794]
Ruby version: 2.6.6
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): 6.1.2/5.2.0/2.1.2

sidekiq.yml
```yaml
:concurrency: 2
:queues:
  - critical
  - default
  - low
```

According to https://github.com/mperham/sidekiq/wiki/Logging#api-changes, we should be able to use either `Sidekiq.logger` or `logger` interchangeably in worker. However, it will throw an undefined error when using it in `sidekiq_retries_exhausted` block

<img width="1292" alt="undefined_logger" src="https://user-images.githubusercontent.com/2663509/106658091-7475a700-6562-11eb-9835-88c6767f6af5.png">

**Comment by mperham** [comment]
That is a class-scoped block; `logger` is only available in Sidekiq::Worker instance methods, i.e. `perform`. You can use `Sidekiq.logger`.
