### ISSUE TITLE
Process count in web ui

### ISSUE THREAD

**Issue by sj26** [mperham/sidekiq#4795]
Could you please add a process count to the web ui, maybe here in the busy tab? The processes table is too long to count manually, and I can't find a count anywhere else.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/14028/106825759-a52c1c80-66d9-11eb-9aec-f85090fc8e61.png">

**Comment by mperham** [comment]
Sure. PR welcome or I can do it soon.

**Comment by sj26** [comment]
Sorry for the terse fly-by, was mid-investigation and just wanted to drop a note!

**Comment by mperham** [comment]
#4806

**Comment by sj26** [comment]
Sorry I didn't get back to this 😞 but thank you so much!! 🙇🏻
