### ISSUE TITLE
[ent] Limiter name

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4797]
```ruby
module Sidekiq
  module Limiter
    class Base
      attr_accessor :name
      
      ...
```

We created a middleware that allows you to pass a limiter to sidekiq_options. This has to be a class method. I'd like to be able to change the name of the limiter based on info in the job hash. <3

**Comment by mperham** [comment]
The name should be immutable for an limiter instance. That should be an attr_reader. If you want a different name, you need to dynamically look up the Limiter.

**Comment by mperham** [comment]
Looks like you're running an older version, :name is now an accessor.

**Comment by dudo** [comment]
no... we're using the latest. I see the attr_reader. I was more hoping to dynamically change the name, but I see your point. We'd have to create it, then look it up, due to what's in the initializer.
