### ISSUE TITLE
Best practices in AWS Lambda / serverless functions (Wiki)

### ISSUE THREAD

**Issue by jeffblake** [mperham/sidekiq#4798]
Thought it would be neat to add a wiki for lambda function best practices using Sidekiq client. Looking for more feedback to make it a proper wiki.

1. Configure the client and redis connection outside of the lambda function handler so that connections can be re-used when the same function container is executed more than once. Obviously, just `configure_client` and no need for `configure_server`
2. Connections: Set a concurrency limit in the AWS function editor to ensure you don't blow up on connections. I plan to personally experiment with switching to Elasticache as the connection limit is a cool 65,000 (but that's a different topic)
3. Use the `Sidekiq::Client.push` API so you don't have to duplicate worker class definitions between your server and lambda function.
4. Bundle sidekiq in a lambda layer to reduce startup time and function size.

Taking suggestions on

- Is it best to use a Connection Pool or not? Since it is possible to provision permanent lambda functions, I would say so, but I have no idea what kind of concurrency that Lambda allocates each container instance (I think it depends on execution time).

Sidekiq lambda layer gem script:

```
LAYER_NAME="sidekiq-layer"
mkdir $LAYER_NAME && cd $_

bundle init
bundle add sidekiq --skip-install

rm Gemfile.lock

docker run --rm -v $PWD:/var/layer \
           -w /var/layer \
           amazon/aws-sam-cli-build-image-ruby2.7 \
           bundle install --path=ruby

mv ruby/ruby ruby/gems
zip -r layer.zip ruby

aws lambda publish-layer-version \
           --layer-name $LAYER_NAME \
           --region us-east-1 \
           --compatible-runtimes ruby2.7 \
           --zip-file fileb://layer.zip
```

Template for a basic ruby lambda function with Sidekiq.

```
require 'sidekiq'

redis_conn = proc {
  redis_config = { db: 0, url: ENV['REDIS_URL'], id: 'redis.lambda', network_timeout: 2 }
  Redis.new(redis_config)
}

Sidekiq.configure_client do |config|
  config.redis = ConnectionPool.new(size: ENV.fetch('REDIS_CONNECTION_POOL_SIZE', 5), &redis_conn)
end

def lambda_handler(event:, context:)

  jid = Sidekiq::Client.push('queue' => 'default', 'class' => 'YourSidekiqWorker', 'args' => [1,2,3])

end
```

**Comment by mperham** [comment]
I believe Lambda handlers aren't thread-concurrent. Each container instance processes one event at a time so you don't need a pool larger than 1. I would remove all of your Redis conn stuff and just rely on the defaults. Set REDIS_URL and everything should magically work.

```ruby
require 'sidekiq'

def lambda_handler(event:, context:)
  Sidekiq::Client.push('queue' => 'default', 'class' => 'YourSidekiqWorker', 'args' => [1,2,3])
end
```

**Comment by jeffblake** [comment]
@mperham I like less code and config. Is it possible to open the redis connection outside of the lambda handler? Advised? Pros - fewer spikes in execution time (for alerting/monitoring). Cons - my Bugsnag wrapper wouldn't pick up any connection errors (but I could at least monitor Datadog error counts).

**Comment by mperham** [comment]
The connection pool will open a connection when it is required to be used. Connection pools are lazy. The only line in your example code that would open a connection is the push.

**Comment by jeffblake** [comment]
I understand it's lazy, I was wondering if its possible to establish the connection before `Sidekiq::Client.push`

Isn't the default redis `size` 5, not 1? https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L26

**Comment by mperham** [comment]
performing any network op will create a connection, yes. The default size
is the max, it will start at zero and grow only under contention. 100
threads will shared one connection if they all use it very rarely. Since
Lambda handlers are typically single threaded, you’ll only get one
connection.

**Comment by jeffblake** [comment]
OK thanks, I'll leave that alone and let it open the connection lazily.

An idea, what about bundling `sidekiq-client` into its own gem without the `rack` dependency?

**Comment by mperham** [comment]
Unfortunately not. Sidekiq is packaged "batteries included". If you want to build a lightweight client that just uses JSON and Redis, you are welcome to.

https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby

**Comment by jeffblake** [comment]
That is pretty easy to do! Thanks as always, Mike!
