### ISSUE TITLE
Can't bundle sidekiq-ent-2.2.2

### ISSUE THREAD

**Issue by mikewindow** [mperham/sidekiq#4799]
Ruby version:
* ruby 3.0.0p0

Rails version:
* rails (6.1.1)

Sidekiq / Pro / Enterprise version(s):
* sidekiq (6.1.3)
* sidekiq-pro (5.2.1)
* sidekiq-ent (2.2.2)

`bundle` can't find `sidekiq-ent-2.2.2`.
```sh
$ bundle
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://enterprise.contribsys.com/..
Could not find sidekiq-ent-2.2.2 in any of the sources
$
```
`gem` says it's available.
```sh
$ gem list -r --clear-sources -s "https://enterprise.contribsys.com/"         

*** REMOTE GEMS ***

sidekiq-ent (2.2.2)
sidekiq-pro (5.2.1)
$
```

**Comment by mperham** [comment]
What version of Bundler?

**Comment by mperham** [comment]
If you are having credential or server issues, please consider contacting me directly. Use `DEBUG=1 bundle` to get more output.

**Comment by mikewindow** [comment]
Has sidekiq-ent 2.2.2 been released yet? It's not in the changelog.
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

bundler is version 2.2.7 
```sh
$ bundle --version
Bundler is version 2.2.7
$ 
```
```sh
$ tail -5 Gemfile.lock
RUBY VERSION
   ruby 3.0.0p0

BUNDLED WITH
   2.2.7
$
```

**Comment by mikewindow** [comment]
I think our credentials may have been incorrect. Thanks for the help with this.

**Comment by stefanahman** [comment]
I have the same problem with not found "in any of the sources".

**Comment by thewalkingtoast** [comment]
@mperham @stefanahman I am seeing this too:

```ruby
> ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
> bundler -v
Bundler version 2.2.4
> bundle
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://enterprise.contribsys.com/..
Could not find sidekiq-ent-2.2.2 in any of the sources
```

My credentials ARE set correctly because I can downgrade to `sidekiq-ent-2.2.1`

**Comment by mperham** [comment]
Can you upgrade to the latest Bundler and then email me privately the output from `DEBUG=1 bundle` where `Could not find` is the result, mike@contribsys.com?

**Comment by thewalkingtoast** [comment]
Sent 👍🏼

**Comment by mperham** [comment]
The version is here in /versions. I will try to reproduce the problem and debug it. If you can spend 10 minutes in pry/byebug with Bundler, let us know what you learn.

> curl https://enterprise.contribsys.com/versions
sidekiq-ent 1.0.2,1.1.0,1.6.0,1.0.0,1.3.0,1.2.1,1.6.1,1.2.4,**2.2.2**,1.4.0,1.8.0,2.2.0,2.0.1,1.3.2,1.5.1,2.2.1,2.1.1,1.2.2,1.8.1,0.7.10,1.0.1,1.7.0,1.5.2,2.1.2,1.5.4,1.2.0,2.1.0,1.7.2,1.2.3,1.5.0,2.0.0,1.5.3,1.7.1,1.3.1 5df5a274ea64654f33955e46e0b6d9d0
sidekiq-pro 5.2.1,2.1.4,2.0.5,4.0.5,5.1.1,3.2.1,3.0.3,2.1.5,2.1.3,1.9.3,3.0.6,2.0.7,5.2.0,3.0.4,4.0.3,3.6.1,3.5.4,3.0.1,3.3.3,2.1.0,2.0.6,2.1.2,4.0.1,3.2.2,2.0.8,3.4.5,3.0.5,3.5.3,3.0.2,4.0.2,3.7.1,3.1.0,3.4.2,5.1.0,3.2.0,3.3.2,4.0.0,3.4.1,3.5.1,3.5.0,3.5.2,2.0.4,3.4.4,3.4.3,3.0.0,3.3.1,3.4.0,5.0.0,3.3.0,5.0.1,4.0.4,3.6.0,2.1.1,3.7.0 5db2a5c0d6cf0db6c4998b3b8f359056

**Comment by mperham** [comment]
Seems to work on a clean install.

```
$ bundle
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://enterprise.contribsys.com/..
Using bundler 2.2.9
Fetching connection_pool 2.2.3
Installing connection_pool 2.2.3
Fetching einhorn 0.8.2
Installing einhorn 0.8.2
Fetching rack 2.2.3
Installing rack 2.2.3
Fetching redis 4.2.5
Installing redis 4.2.5
Fetching sidekiq 6.1.3
Installing sidekiq 6.1.3
Fetching sidekiq-pro 5.2.1
Installing sidekiq-pro 5.2.1
Fetching sidekiq-ent 2.2.2
Installing sidekiq-ent 2.2.2
Bundle complete! 2 Gemfile dependencies, 8 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

**Comment by thewalkingtoast** [comment]
Our dependabot (old preview .com version) was able to update it. I am on Comcast and using Cloudflare for DNS. I wonder if it could be cached somewhere? I also tried a clean install, no dice:

<img width="923" alt="Screen Shot 2021-02-08 at 1 47 14 PM" src="https://user-images.githubusercontent.com/864643/107285514-28b87700-6a14-11eb-9d85-b7853c6df522.png">

I will try changing DNS.

**Comment by thewalkingtoast** [comment]
No dice:

<img width="1642" alt="Screen Shot 2021-02-08 at 1 50 29 PM" src="https://user-images.githubusercontent.com/864643/107285880-a4b2bf00-6a14-11eb-86e2-5c842d816432.png">

**Comment by mperham** [comment]
That's the right IP. I double checked and I don't have Cloudflare caching enabled for that hostname. It does seem like Bundler might be caching the `versions` content somehow.

**Comment by thewalkingtoast** [comment]
Success. `rm -rf ~/.bundle/cache/compact_index/enterprise.contribsys.com.*`

<img width="731" alt="Screen Shot 2021-02-08 at 1 57 00 PM" src="https://user-images.githubusercontent.com/864643/107286498-8600f800-6a15-11eb-9159-2cb5e65ce875.png">

**Comment by mperham** [comment]
My server doesn't grok or provide ETags so Bundler shouldn't be caching `versions` at all or should default to a minimal cache TTL like one hour.

**Comment by mikewindow** [comment]
This happened again.

```
$ bundle outdated
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://enterprise.contribsys.com/.
Could not find gem 'sidekiq-pro' in rubygems repository https://enterprise.contribsys.com/ or installed locally.
The source contains the following versions of 'sidekiq-pro': 1.9.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.1.0, 2.1.1,
2.1.2, 2.1.3, 2.1.4, 2.1.5, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.3.1,
3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.7.0, 3.7.1,
4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.2.1
$ 
```

Removing the bundle cache for `enterprise.contribsys.com` fixed this.
```sh
rm -rf $BUNDLE_USER_HOME/cache/compact_index/enterprise.contribsys.com.*
```

**Comment by mperham** [comment]
It is a bug in Bundler. https://github.com/rubygems/rubygems/issues/4543

**Comment by mikewindow** [comment]
See #4838
