### ISSUE TITLE
Sidekiq.service not starting

### ISSUE THREAD

**Issue by mountaindog** [mperham/sidekiq#4803]
Ruby version: 2.7.1
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): Sidekiq on RH 7

**sidekiq.yml**  - Very basic
```
:concurrency: 5
development:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - searchkick
  - default
```

**sidekiq.service** - More or less boiler plate
```
WorkingDirectory=/var/www/my_site

ExecStart=/home/my_user/.rvm/gems/ruby-2.7.1/wrappers/bundle exec sidekiq -e development -C config/sidekiq.yml

# !!! Change this to your deploy user account !!!
User=my_user
Group=my_group
UMask=0002
```

**Start sidekiq**
`sudo systemctl restart sidekiq.service`

**Error MSG**
 ```
sidekiq.service - sidekiq
   Loaded: loaded (/usr/lib/systemd/system/sidekiq.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-02-09 04:44:36 UTC; 590ms ago
  Process: 13403 ExecStart=/home/xxxxxxx/.rvm/gems/ruby-2.7.1/wrappers/bundle exec sidekiq -e development -C config/sidekiq.yml (code=exited, status=1/FAILURE)
 Main PID: 13403 (code=exited, status=1/FAILURE)

sidekiq.service: main process exited, code=exited, status=1/FAILURE
Failed to start sidekiq.
```

Running this manually in the site directory starts Sidekiq without issue
`/home/my_user/.rvm/gems/ruby-2.7.1/wrappers/bundle exec sidekiq -e development -C config/sidekiq.yml`

Would love some suggestions and ideas on what might be going wrong.

**Comment by mountaindog** [comment]
To follow up. I was able to get Sidekiq started via service by changing the` Type=notify` to `Type=simple` and commenting out / removing `WatchdogSec=10`. 

What's odd is the documentation says "As of v6.0.6, Sidekiq automatically supports systemd's `Type=notify` and watchdog service monitoring." .  I am running the latest version of Sidekiq. Hmm...

**Comment by mperham** [comment]
RH7 likely has an old version of systemd.
