### ISSUE TITLE
[ent] leaky bucket can't change update its size

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4809]
```lua
local res = redis.call("exists", key)
if res == 0 then
  local ttl = tonumber(ARGV[3])
  redis.call("hset", key, "size", size, "interval", interval, "drops", 0)
  redis.call("expire", key, ttl)
end
```

We just deployed our fancy new shared limiter. Upon deploying we decided we wanted to up the size of our leaky bucket using ENV. We changed the size, and kicked the boxes. The UI still showed the "old" size. We looked at the source code, and noticed the lua script sets the size only if the key doesn't exist. We also noticed the call to expire (which defaults to 24 hours for leaky).

Is there a preferred way of updating the size without waiting for the TTL?

Also, with regards to the TTL, how does this work, exactly? Does this mean every 24 hours our drip rate will reset?

**Comment by mperham** [comment]
Please don't publicize any Enterprise source code.

**Comment by mperham** [comment]
The TTL only controls how long the limiter will live in Redis without being used before it will expire. Today limiters are considered immutable as it is assumed this is a very rare operation. If you want to change the parameters of a limiter, change the name too.

**Comment by dudo** [comment]
Can we revisit this immutable limiter bit? It's a very real scenario that 1 of our vendors is unhealthy, and we need to slow down calls to them. Lowering the limit is how we've achieved that, using the `bucket` limiter.

**Comment by mperham** [comment]
Can you be more specific with the scenario?

If you have an old leaky limiter:

```ruby
Sidekiq::Limiter.leaky('foo', 50, :minute)
```

You can change the name and rate at the same time:

```ruby
Sidekiq::Limiter.leaky('bar', 30, :minute)
```

If you want a custom limiter per account, use the bucket size as part of the name:

```ruby
Sidekiq::Limiter.leaky("#{acct.name}-#{acct.bucket_size}", acct.bucket_size, :minute)
```

So when you change the bucket_size, the system will automagically use a new limiter. WDYT?

**Comment by dudo** [comment]
Ah. Putting the size in the name is acceptable - good call.

As for TTL (on leaky bucket) - we're still under the impression that the key is set to expire upon initialization, and nothing seems to update that as the limiter gets used. Can you clarify?

**Comment by dudo** [comment]
I'm still a little concerned with the "new limiter" in this case. scenario... 

1. business as usual, limiter is set up as leaky(6000/60)
2. external service notifies us that they're having issues, and we need to reduce load
3. we reduce the limiter size to leaky(600/60)
4. if the bucket was full, drip rate is 100/s
5. new burst of 600 is allowed before settling on a drip of 10/s (which could essentially be 700/s, worst case, for the first second)

I guess an argument could be made that this isn't the right solution to this particular problem... I'm curious what you think, though.

**Comment by vartec** [comment]
I believe following changes to Lua script would work in our scenario:

1. split the initialization HSET call into two calls, one setting `size` and `interval`, other one initializing `drops` at zero
2. pull everything except `drops` initialization out of the block gated by `exists`. 

This would achieve what we're looking for: 
- The TTL would get refreshed every time limiter is called;
- Size could be dynamically adjusted without losing current counts.

**Comment by mperham** [comment]
@vartec I was trying to find a way to avoid that overhead but I don't see how. If you are calling this rate limiter 6000 times in a minute, that's 100 times per second which won't saturate Redis but it'll add significant load. Make sure you specify a separate Redis for your rate limiting.

**Comment by dudo** [comment]
Is this ticket worth reopening, @mperham? Feels like a real issue.

**Comment by mperham** [comment]
@dudo It has been fixed and will be available in the next release (which does not have an ETA).

**Comment by mperham** [comment]
I'm considering reverting this change. The fundamental issue is that making the size mutable makes the rate limiter thread-unsafe and I've always documented the rate limiters as shareable and thread-safe.  The safer way to change size is to put the size in the name of the limiter:

```ruby
# e.g. if you have dynamic user levels for rate limit: Free user gets 50/min, Pro user gets 100/min, etc
Sidekiq::Limiter.leaky("stripe-#{user.rate_allowance}", user.rate_allowance, :minute)
```
