### ISSUE TITLE
sidekiqswarm and heroku/docker env variables

### ISSUE THREAD

**Issue by beneichler** [mperham/sidekiq#4812]
I've just upgraded to Enterprise and as a first move am trying to switch from `sidekiq` to `sidekiqswarm`; my sidekiq process runs fine in a heroku dyno when started like this:

```
env NEWRELIC_ENABLE=true bundle exec sidekiq
```

but the child processes immediately crash in exciting ways due to environment variables missing (in miscellaneous other initializers, notably database.yml and algoliasearch-rails) when run like so
```
env NEWRELIC_ENABLE=true SIDEKIQ_MAXMEM_MB=1750 bundle exec sidekiqswarm
```

This smells like a mistake on my end, but is there something special I need to do to get sidekiqswarm to feed my env variables through to the child processes?

(This all happens inside a docker container on Heroku, not using the traditional procfile setup)

Versions:
```
ruby-2.6.6
rails (6.0.3)
sidekiq (5.2.9)
sidekiq-ent (1.8.1)
sidekiq-pro (5.0.0)
```

sidekiq.yml:
```
---
:concurrency: 10
:queues:
  - ["critical", 4]
  - # ...etc
  - ["default", 1]
```

initializer:
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDISGREEN_URL'] }
  config.periodic do |mgr|
    # SidekiqSchedule's values are openstructs with some properties, I'm confident in the syntax for the scheduler though and it works fine when run with regular sidekiq
    SidekiqSchedule.each do |_k, scheduled_job| 
      mgr.register(scheduled_job.cron_machine, scheduled_job.klass, 'args' => scheduled_job.args)
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDISGREEN_URL'] }
end

Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
```

**Comment by mperham** [comment]
Why are you using `env`? I don't recall anyone else mentioning that child processes didn't see ENV but that's the only thing suspicious that I see.

Side note: if you run `heroku config:set REDIS_PROVIDER=REDISGREEN_URL`, you can remove the Redis config in your initializer. https://github.com/mperham/sidekiq/wiki/Heroku#redis

**Comment by beneichler** [comment]
Thanks for the quick response, and the note about the redis config.

`env` is there as a legacy of whoever originally wrote our deploy script, but I've subsequently tried it `env` removed and the same results. However I have noticed a new wrinkle, which is that our `database.yml` references application code:
```
production:
  <% if Environment.is_special_env? %>
    <% _primary_db_path = ENV['SPECIAL_DATABASE_URL'] %>
    <% _logs_db_path = ENV['SPECIAL_LOG_DATABASE_URL'] %>
    <% _super_special_db_path = ENV['SPECIAL_DATABASE_2_URL'] %>
```
which seems like maybe it could be causing the problems I'm seeing? That seems like probably not your problem though

**Comment by mperham** [comment]
Yeah, Impossible for me to say.

**Comment by beneichler** [comment]
I'll go ahead and close then, continued investigation suggests this is just something bad in our setup; thanks for your time and I'll circle back with info if it turns out this was actually caused by sidekiqswarm
