### ISSUE TITLE
Update sidekiq ent rate limiters size

### ISSUE THREAD

**Issue by vicenteferreyra** [mperham/sidekiq#4813]
Hi! I’m working with Sidekiq ent limiters and our use case needs to update the size of the limiter. Since we have several servers, we have to use constants and we can’t have the limiters in variables (if this were the case, we could rewrite the variable with a bigger limiter). The only workaround we thought about was to store the limiter size in redis and initialize it every time we need to use it with the correct size, but we don’t find this solution to be clean enough.

Any thoughts about how we can tackle this issue?

Thanks in advance

**Comment by mperham** [comment]
Can you show me your limiter code?

**Comment by vicenteferreyra** [comment]
Hey, thanks for your response. I'm creating the limiters like this:

`LIMITER = Sidekiq::Limiter.concurrent(limiter_name, limiter_size)`

I would need to update the value of limiter_size after initialization.

**Comment by mperham** [comment]
You cannot change the size after initialization. To do so would be thread-unsafe.

Since you cannot use constants, you'll need to dynamically create or lookup the limiter and include the size as part of the name:

```ruby
limiter = Sidekiq::Limiter.concurrent("some_name-#{dynamic_size}", dynamic_size)
limiter.within_limit do
  ...
end
```
