### ISSUE TITLE
"undefined method for nil:NilClass" when using .delay

### ISSUE THREAD

**Issue by tctrautman** [mperham/sidekiq#4814]
Ruby version: 2.6.6
Rails version: 5.2.4.3
Sidekiq / Pro / Enterprise version(s): sidekiq-pro

Hello!  First off, thanks for the work you've done for the ecosystem.  Also, I don't spend a ton of time using Rails, so apologies if I'm asking anything too obvious - I've done my best to consult docs but haven't had luck.

I'm receiving the error in the issue title when trying to use `.delay` with an ActiveRecord class method like so:

```[Class].delay.[method](args)```

I've read in [these](https://github.com/mperham/sidekiq/wiki/Delayed-extensions) docs your instructions which say to "`Use Sidekiq::Extensions.enable_delay! to turn them on.`", and I believe I might just not be adding `Sidekiq::Extensions.enable_delay!` to the right place in sidekiq.rb (pasted below.)

Would you be able to take a look and let me know if anything looks obviously incorrect to you?

Thank you!

Initializer:
```
# typed: strict
require 'sidekiq'
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] }

  config.options[:error_handlers] = []
  config.error_handlers << proc do |ex, ctx|
    Sidekiq.logger.warn(Sidekiq.dump_json(ctx)) unless ctx.empty?
    Sidekiq.logger.warn("#{ex.class.name}: #{ex.message}")
    unless ex.class.name = [REDACTED]
      Sidekiq.logger.warn(ex.backtrace.join("\n")) unless ex.backtrace.nil?
    end
  end

  config.death_handlers << ->(job, ex) do
    Honeybadger.notify(
      "Uh oh, #{job['class']} just died with error #{ex.message}.",
      backtrace: ex.backtrace,
      context: {
        jid: job['jid'],
        exception_class: ex.class.name,
      }
    )
  end

  # See: https://github.com/mperham/sidekiq/wiki/Reliability
  config.super_fetch!
  config.reliable_scheduler!
end

Sidekiq::Extensions.enable_delay!

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == [ENV["SIDEKIQ_USER"], ENV["SIDEKIQ_PASSWORD"]]
end
```

**Comment by mperham** [comment]
Please include the full backtrace of the error.

**Comment by mperham** [comment]
(It looks fine)

**Comment by tctrautman** [comment]
Hi Mike -- thanks so much for your quick response here.  I'm closing this -- the issue ended up being user error 🤦 .

My class wasn't inheriting directly from ActiveRecord so I needed to add:

```
    def self.delay
        super
    end
```
