### ISSUE TITLE
Complete Workflows with Batch - batch "complete" if first job fails

### ISSUE THREAD

**Issue by mrchucho** [mperham/sidekiq#4816]
Ruby version: 2.6.6p146
Rails version: 5.2.4.4
Sidekiq / Pro / Enterprise version(s): 5.2.8 / 4.0.5 / n/a

Following the example for [Really Complex Workflows with Batches](https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches), I found that the overall batch will be considered completed if the first job fails. Here's my simplified version of the example from the wiki.

```ruby
overall = Sidekiq::Batch.new
overall.description = 'Overall'
overall.on(:success, 'OverallCallbacks#all_done')
overall.jobs do
  StartWorkflow.perform_async
end

class StartWorkflow
  include Sidekiq::Worker
  def perform
    batch.jobs do
      step1 = Sidekiq::Batch.new
      step1.description = 'Step 1'
      step1.jobs do
        A.perform_async
      end
    end
  end
end

class A
  include Sidekiq::Worker
  def perform
    raise "Job failed"
  end
end
```

<img width="1371" alt="Screen Shot 2021-02-17 at 3 18 22 PM" src="https://user-images.githubusercontent.com/10029/108270032-7a5bb280-7134-11eb-8d88-c2fa1e602acc.png">
<img width="1373" alt="Screen Shot 2021-02-17 at 3 18 12 PM" src="https://user-images.githubusercontent.com/10029/108270044-7e87d000-7134-11eb-8f0c-b5edc5e2c8ea.png">

```ruby
2.6.6p146 :122 > Overall.new.execute
 => ["28877210d7b7054d699f9bcd"] 
2.6.6p146 :123 > Sidekiq::Batch::Status.new('o7h6gguiAju3fQ').complete?
 => true 
2.6.6p146 :125 > Sidekiq::Batch::Status.new('o7h6gguiAju3fQ').failures
 => 0 
```

If the step 1 job fails, the overall batch is complete with zero failures, zero pending and 100% success. Even though it isn't "done" and no callbacks have fired. If the step 1 job succeeds and, like in the example, re-opens the parent batch to add more jobs, then the overall batch will now report that it is **not** complete until those new jobs finish.

I assume this is because, during step 1, the parent batch doesn't have any jobs (yet). However, two things seem odd. One, that overall batch would be complete (when step 1 fails) then later **not** complete (after step 1 succeeds and adds jobs). Two, that the overall batch could be complete (and have a success percent of 100%) but its success callback hasn't fired. Because of this I can't use `Sidekiq::Batch::Status.new(...).complete?` to see if a batch is complete since a failure in step 1 will result in the batch being considered complete even though it's still in-progress.

Should I not be using `#complete?` this way? Is there a different way to approach this sort of workflow so that failures don't cause the overall batch to be misrepresented?

Thank you!

**Comment by mperham** [comment]
I think you've found quite a tricky usecase. The complete callback itself will only fire once but using the job numbers to calculate complete means that jobs which initially fail but also add jobs to the batch can change whether complete? is true or false. It sounds like you should be using success instead. There is no equivalent `success?` API because successful batches are immediately deleted. I'm not really sure what you are trying to do so I can't advise further.

**Comment by mrchucho** [comment]
> I'm not really sure what you are trying to do so I can't advise further.

All good. Just wanted to make sure I wasn't completely misunderstanding something or approaching things the wrong way.

For what it's worth, here's what I've been doing (in a nutshell): an API endpoint that creates a multi-step batch like the one described above and returns the "overall" batch ID. The client that submitted a request can then poll the API using that batch ID to see when the overall batch is complete. This works great as long as that first job doesn't fail. Obviously, you can see the problem if the first job fails: clients will be informed that the overall batch is complete even though it's still running.

Easy enough to address: I can just store the batch's status separately and use the success callback to mark the batch as complete. Thanks for the quick response! We love Sidekiq!
