### ISSUE TITLE
[question] Sidekiq Enterprise. Is there a way to bind queue to process?

### ISSUE THREAD

**Issue by dabih** [mperham/sidekiq#4817]
Is there a way to bind queue to process?
I want that different processes have their own threads. And work with different queues.
I need this because we have some tasks which can be processed simultaniously. And some tasks which must be processed one by one.

**Comment by mperham** [comment]
`bundle exec sidekiq -q serial -c 1`

This Sidekiq process will execute one job at a time from the serial queue.

**Comment by dabih** [comment]
Thanks!
But, I'm asking about sidekiq enterprise. If we talk about multi-process mode. Can we bind a specific queue to a specific child process?

**Comment by mperham** [comment]
Nope, all children must be identical.

**Comment by dabih** [comment]
Thanks a lot!
