### ISSUE TITLE
Batch stuck with -1 job remaining

### ISSUE THREAD

**Issue by aclarembeau** [mperham/sidekiq#4818]
Ruby version: 2.7.2
Rails version: 6.1.2.1
Sidekiq / Pro / Enterprise version(s): 5.0.1

<img width="1211" alt="Capture d’écran 2021-02-18 à 15 23 52" src="https://user-images.githubusercontent.com/10834626/108371040-9e36fb00-71fd-11eb-91bb-d6dba88a0bc0.png">

Recently, I've seen that some of my batches never complete and get stuck in a state with -1 job waiting. My jobs are running, but by callback is never invoked. Is that a known issue with sidekiq pro 5.0.1 ? I had a look at the changelog, at it doens't seem it's something that has already been mentioned.

**Comment by mperham** [comment]
This might apply to you (from the Batches wiki page):

> Seeing "negative pending" batches? Make sure you've configured Redis with `maxmemory-policy noeviction`.

Can you check that Redis setting?

**Comment by aclarembeau** [comment]
Hello, 

Thanks for the quick reply. Unfortunately, that's the case. 
I don't know if that can help, but if I remind correctly, at some point, our redis server was having a high number of incoming connections, from a short period of time (higher than the maximum allowed), causing redis clients not to be able connecting anymore. Could that explain the problem? 

Or, maybe, should I upgrade Sidekiq version? 

Best

**Comment by mperham** [comment]
I try to make Sidekiq resilient in the face of Redis outages but that's one of the hardest things to test and prove. If you want to fire that callback and delete the batch manually, hopefully it won't recur any time soon.

**Comment by aclarembeau** [comment]
Thanks a lot for the honest reply. 
I'll definitely note that I need to take care of that problem when a redis instance goes down or is having some issues. 
That's the first time I had this. So, probably this won't happen again.
