### ISSUE TITLE
Is it possible to know inside the perform method that your job came from SuperFetch

### ISSUE THREAD

**Issue by neojin** [mperham/sidekiq#4820]
Hi Mike,

I am having some issues dealing with local database state, which is unrelated to sidekiq. However one way I can resolve this situation is to know that a job came from a superfetch. Is there a way to know this?

Thank you

**Comment by mperham** [comment]
Nope, jobs are very specifically limited to knowing only their JID and arguments.

**Comment by neojin** [comment]
ok thank you
