### ISSUE TITLE
Plain old ruby multiple worker heroku procfile best practices

### ISSUE THREAD

**Issue by johnknapp** [mperham/sidekiq#4823]
Following the [por.rb example](https://github.com/mperham/sidekiq/blob/master/examples/por.rb) I have a single `-r` flag in my Procfile thus:

```
web: bundle exec puma -p $PORT 
sidekiq: bundle exec sidekiq -r ./app/workers/confirm.rb
```

Works great! 

I am having problems with multiple workers!

```
web: bundle exec puma -p $PORT 
sidekiq: bundle exec sidekiq -r ./app/workers/confirm.rb -r ./app/workers/welcome.rb 
```

**Multiple `-r` flags didn't work.**

What is the right way to handle an arbitrary number of por workers in my Procfile?

**Comment by mperham** [comment]
`-r` is the entry point into your app and is one file. Your app uses `require` to load many other Ruby files.
