### ISSUE TITLE
Increased Sidekiq CPU consumption after adding UPSERT Postgres

### ISSUE THREAD

**Issue by borbavanessa** [mperham/sidekiq#4828]
Ruby version: 2.6.2
Rails version: 5.2.3
Sidekiq / Pro / Enterprise version(s): 6.0.7
PostgreSQL: 11.10

Machine Configuration (AWS):
SO: Centos 7
C5.large server (2 vCPU + 4GB of RAM)
Database: postgresql rds (db.m5.4xlarge), 16 vcpu and 64GB colors

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

config/initializers/sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV["REDIS_URL"] }
end
```
Each machine runs two Sidekiq processes, each one configured as:
config/sidekiq.yml
```
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - mailers
```

We have an application Rails 5.2 with a Sidekiq job that performs several actions of select, insert/update in the PostgreSQL database with daily frequency around 3.5k ~ 4.5k rpm. We modified this job to perform insert/update in bulk (upsert) in the table with the largest volume of data. After this modification, we noticed the following behavior: progressively the free memory of the database is reduced to a critical threshold, where we are forced to restart the Sidekiq. After restarting the Sidekiq everything goes back to normal for a few hours, where the scenario repeats itself.

Below an example of the described behavior, the free memory on the machine with PostgreSQL database:
![image (10)](https://user-images.githubusercontent.com/45601147/109568354-91e85300-7ac5-11eb-869a-0334e76d9d2b.png)

The behavior was observed on Sidekiq machines for the same period. Sidekiq machines reach 100% CPU usage, while the database machine reduces free memory to almost 5GB, so we forcing a machine restart.
![image (11)](https://user-images.githubusercontent.com/45601147/109568390-9d3b7e80-7ac5-11eb-8d58-6653eb1ea395.png)

The job in question runs in the default queue. The other queues trigger a single process a day and do not compete in time with the critical range of sending data to the application.

We found this [issue](https://github.com/seamusabshere/upsert/issues/37) that reports problems when using PostgreSQL upsert with Sidekiq. Does this problem exist for the latest versions of Sidekiq?

**Comment by mperham** [comment]
Sidekiq doesn't use or know anything about your database. That's between your app code and the various db gems you are using. Have you read through the Problems and Troubleshooting wiki page?

BTW you can remove your initializer completely if you want. Sidekiq will connect to REDIS_URL by default.
