### ISSUE TITLE
SidekiqPro StatsD middleware job performance

### ISSUE THREAD

**Issue by matt-taylor** [mperham/sidekiq#4829]
Ruby version: `2.5.5`
Rails version: `5.2+`
Sidekiq / Pro / Enterprise version(s):  `6.1.3`, `5.2.0`, `2.2.0`

We are using the StatsD middleware included with Sidekiq Pro. We have noticed that often times our job performs (max and avg) from Datadog and Sidekiq Metrics do not match. 

After further investigation we found this as an example:
We have a job that calls an external API that times out after 30 seconds if no response. If the external API call timeout is reached, it will raise an error. The SidekiqPro StatsD middleware will not report this perform time because an exception had been raised.

I was hoping that `Sidekiq::Middleware::Server::Statsd` could be extended a bit to include perform times of failed jobs as well as successful jobs?
Ideally this metric could then be tagged as success or failure.

Thanks!

**Comment by mperham** [comment]
> The SidekiqPro StatsD middleware will not report this perform time because an exception had been raised.

This says the time is always submitted, success or failure: https://github.com/DataDog/dogstatsd-ruby/blob/958b5e0be075d2b132c45a70aac01e7ede8b2d30/lib/datadog/statsd.rb#L228

I could tag it success or failure, to do so would require me to re-implement the `time` method.
