### ISSUE TITLE
Idea: Export 'dead_max_jobs' option as statistic

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [mperham/sidekiq#4832]
In order to also show the limit for the dead jobs in our Grafana dashboard, I would like to see the `dead_max_jobs` setting exported via the `StatsD` middleware.

When the configuration changes the exported value for the `dead_max_jobs` should also change.

Is this possible?

**Comment by mperham** [comment]
I think the easiest approach is to add a custom metric to the historical metrics:

https://github.com/mperham/sidekiq/wiki/Ent-Historical-Metrics#custom

**Comment by ThomasKoppensteiner** [comment]
Thank you, I'll give this option a try.

**Comment by ThomasKoppensteiner** [comment]
@mperham thank you!
Using custom history metrics worked for us.

```ruby
Sidekiq.configure_server do |config|
  ...
  config.retain_history(30) do |s|
    s.batch do |b|
      b.gauge("sidekiq.dead_max_jobs", config.options[:dead_max_jobs])
    end
  end
...
end
```
