### ISSUE TITLE
Sidekiq-pro On_complete not called by the batch.on() function

### ISSUE THREAD

**Issue by Jagmeetsinghoyo** [mperham/sidekiq#4835]
Ruby version:2.2.3
Rails version:4.2.0
Sidekiq / Pro / Enterprise version(s):sidekiq 4.2.10, sidekiq-pro 3.5.0

I am running sidekiq by the command 
bundle exec sidekiq -q queue_name

sidekiq batch worker working fine but callback function like :complete, :success doesn't work 
i use the binding.pry to see that my call back fxn is called or not but eventually the callback fucntion is not .

Can any one provide me the solution for that

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
I’m not supporting versions that old anymore.
