### ISSUE TITLE
REDIS_URL setting not reflect to sidekiq process

### ISSUE THREAD

**Issue by tai-acall** [mperham/sidekiq#4836]
Hello there,

I try to change the Redis URL setting from 127.0.0.1/0 to a AWS ElastiCache(Redis) endpoint. 

I put the `REDIS_URL="rediss://ElastiCache Endpoint String Here:6379/0"` in my ENV variable and restart the server, the sidekiq connected to ElastiCache successfully, at lease in log.

> log/sidekiq.log
INFO: Booting Sidekiq 5.1.1 with redis options {:id=>"Sidekiq-server-PID-XXX", :url=>"rediss://ElastiCache Endpoint String Here:6379/0"}

then I check the Sidekiq UI and notice that the Redis endpoint still shows '127.0.0.1/0'.

If sidekiq.log shows it connected to the ElastiCache endpoint, why Sidekiq UI still shows 127.0.0.1/0?

**Comment by mperham** [comment]
The Web UI process is not the Sidekiq process. You are seeing the Web UI
Redis.

**Comment by tai-acall** [comment]
@mperham 

Hello, thanks for reply.

I'm confusing now, you mean Web UI process and Sidekiq process using different REDIS_URL setting?

how can I change the REDIS_URL setting for Web UI?

I'm experiencing a strange issue that if I shutdown the 127.0.0.1/0 Redis server, the hole Rails App will not be able to run any Sidekiq related code with return error `Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)`.

any suggestion will be helpful, much appreciate.

**Comment by mperham** [comment]
You pass in REDIS_URL into puma or whatever app server you are using for
the Web UI.

**Comment by tai-acall** [comment]
@mperham 

thanks a lot, I'll debug my puma server and might figure out why the ENV won't pass to the Rails App.
