### ISSUE TITLE
URI scheme of redis connection url should not be hardcoded in redis_connection helper

### ISSUE THREAD

**Issue by andreas-venturini** [mperham/sidekiq#4837]
For newer versions of Redis that use TLS connections the uri scheme might be `rediss` - currently the scheme is hardcoded in the footer partial which could be potentially confusing - e.g. `rediss` is the default for new Heroku Redis instances (see https://devcenter.heroku.com/articles/heroku-redis#create-a-new-instance)

https://github.com/mperham/sidekiq/blob/25ed7c7e39b1e08f69e1ad5a63c036acabc9e31a/lib/sidekiq/web/helpers.rb#L170

**Comment by mperham** [comment]
So send a PR?

**Comment by andreas-venturini** [comment]
Fair enough, I'll add it to my todo list.
