### ISSUE TITLE
Using Bundler 2.2.14 regresses Sidekiq Pro version

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#4838]
Ruby version: 2.7.2
Rails version: 6.0.3 / 6.1.3
Sidekiq / Pro / Enterprise version(s): Pro 5.2.1

I'm not sure if this is a Sidekiq Pro gem repo issue, a bundler issue, or an interaction between the two.

I have an application that uses Sidekiq Pro, and the Gemfile.lock was built with Bundler 2.2.13 and references Sidekiq Pro 5.2.1.  The Gemfile does not explicitly specify the Sidekiq Pro version.

If I upgrade bundler to 2.2.14, and run `bundle upgrade` (or just delete the Gemfile.lock and rebuild) the version of sidekiq-pro in my Gemfile.lock drops from 5.2.1 to 5.2.0. 

If I attempt to explicitly specify the version as '>= 5.2.1' in the Gemfile, I get:

Could not find gem 'sidekiq-pro (>= 5.2.1)' in rubygems repository https://(redacted)@gems.contribsys.com/ or installed locally.
The source contains the following versions of 'sidekiq-pro': 1.2.4, 1.5.1, 1.6.0, 1.7.1, 1.7.5, 1.7.6, 1.9.1, 1.9.2, 1.9.3, 2.0.1, 2.0.3, 2.0.4,
2.0.5, 2.0.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.2.1, 3.2.2, 3.3.1, 3.3.2, 3.3.3,
3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5,
5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.2.0

**Comment by mperham** [comment]
This is a Bundler issue. Delete the local cache with `rm -rf ~/.bundle/cache/compact_index/gems*` and try again. I thought this issue was fixed by https://github.com/rubygems/rubygems/pull/4381

**Comment by petergoldstein** [comment]
@mperham Thanks.  That worked.  Sorry for the noise.
