### ISSUE TITLE
WARNING: Sidekiq::Web.sessions= is no longer relevant and will be removed in Sidekiq 7.0.

### ISSUE THREAD

**Issue by wimpog** [mperham/sidekiq#4846]
How do I fix this warning?

`WARNING: Sidekiq::Web.sessions= is no longer relevant and will be removed in Sidekiq 7.0.`

**Comment by mperham** [comment]
Delete the line in your initializer.

**Comment by wimpog** [comment]
@mperham I don't have such line in my initializer!

**Comment by mperham** [comment]
Then use grep.

**Comment by mperham** [comment]
`git grep "sessions ="`

**Comment by wimpog** [comment]
Tried with grep, didn't find anything.

**Comment by jeffblake** [comment]
Mine is set up as....
`Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]`

**Comment by wimpog** [comment]
@mperham I found this line in `config/initializers/sessio_store.rb`:

`Sidekiq::Web.set :sessions, false`

Should I completely remove this line?

**Comment by mperham** [comment]
Yes. And any `session_secret` line. Sidekiq 6.2.0+ does not provide any session infrastructure but relies on Rails or Rack providing it.

**Comment by wimpog** [comment]
Thanks, I'll try that.

**Comment by wimpog** [comment]
@mperham thank you, that works.

**Comment by twe4ked** [comment]
For future `grep`pers, the `.disable` function could also be the source of this. Our offending line was `Sidekiq::Web.disable(:sessions)`.
