### ISSUE TITLE
perform_async in after_commit does not count as job in a Batch

### ISSUE THREAD

**Issue by sayduck-daniel** [mperham/sidekiq#4847]
We are on the latest version of both Sidekiq and Sidekiq-pro

It appears that a job queued from a `after_commit, on: :create ` callback doesn't get added to the batch.

Is this  expected behaviour?

**Comment by mperham** [comment]
That is correct. Sidekiq knows nothing about your database. You might be able to put a transaction within the jobs block.

**Comment by sayduck-daniel** [comment]
fair enough
