### ISSUE TITLE
Non-actionable warnings about RTT

### ISSUE THREAD

**Issue by MGPalmer** [mperham/sidekiq#4851]
Ruby version: 2.7.2
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s): 6.2.0

sidekiq.yml:
```
---
:verbose: true
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8
:queues:
  - ['critical', 6]
  - ['high', 4]
  - ['default', 2]
  - ['low', 1]


```

Hello!
I'm a little worried about the recently introduced warnings about RTT: https://github.com/mperham/sidekiq/issues/4824
I noticed this warning showing up in our logs several times a day, usually with around this range:

```
Mar 23 23:32:58 mge-application app/worker.1 pid=4 tid=2lps WARN: Your Redis network connection is performing extremely poorly.
Mar 23 23:32:58 mge-application app/worker.1 Current RTT is 95404 µs, ideally this should be < 1000.
Mar 23 23:32:58 mge-application app/worker.1 Ensure Redis is running in the same AZ or datacenter as Sidekiq.

```

However, usually the RTT is somewhere between 800 and 5000. The thing is, we're on Heroku and have basically no control over the Redis instance except the plan size (we have a medium-range "premium-5" instance). Sidekiq jobs seem to be handled reliably and speedily, no complaints.

So this warning is currently just noise to us. Is there a way to turn them off? Or am I missing something important here?

Thanks!
(BTW, love Sidekiq and your work, thanks :))

**Comment by jwilsjustin** [comment]
Yeah. For deployments on Heroku there is no way for us to have a guaranteed AZ. [See here](https://help.heroku.com/NOTG5GDT/how-do-multi-availability-zones-work-on-heroku). Maybe logging this as INFO would still suffice for those who want it?

**Comment by MGPalmer** [comment]
Ah thanks. Hmm the principle is fine :) From the top of my head, I would like to keep the warnings but configure the threshold to our case. Making it possible to override RTT_WARNING_LEVEL via ENV var and/or sidekiq.yml would be great for us.

**Comment by mperham** [comment]
Perhaps I shouldn't be taking one reading and WARNing based on it. I should be taking 3-5 readings over 30 seconds before logging anything, that would minimize log noise due to transient spikes.

I avoid config switches as they add code complexity.

**Comment by jwilsjustin** [comment]
+1 for that, @mperham.

**Comment by MGPalmer** [comment]
I guess that would work for us, too, the warnings for today for example are usually minutes up to an hour apart.

**Comment by PhilCoggins** [comment]
I am also on Heroku and have just started to notice these in my logs recently Some of the values are _very_ high:

> Mar 29 07:14:46 fleetio app/sidekiq.2:           Current RTT is 16703645 µs, ideally this should be < 1000.

If I'm not mistaken, this is a **16 second ping** (not full request) from my Sidekiq server to Redis? I have opened a support request with Heroku, as this is pretty bad.

Would it be reasonable to correlate consistently high values with `ERROR: heartbeat: Connection timed out`? And is it possible for jobs to be dropped when seeing these errors?

**Comment by mperham** [comment]
@PhilCoggins That's awful. If you are seeing consistently poor performance, I would explain to Heroku Support about the poor latency and ask them to fail you over to a new Redis instance. Something is terribly wrong with that one.

**Comment by mperham** [comment]
I've updated master to take 5 samples and only warn if all five samples are above the threshold.

**Comment by MGPalmer** [comment]
Thanks everyone!

**Comment by edmorley** [comment]
@mperham I don't suppose it would be possible to publish a new sidekiq release to pick up 5b94bfe? A number of customers are opening tickets and presumably many (if not all) are due to transient spikes, rather than consistent slow RTT.

**Comment by mperham** [comment]
@edmorley Can you explain more? Is there some aspect that makes this high priority? I have one other thing I'm still looking into but it's possible I can release later this week.

**Comment by edmorley** [comment]
@mperham Just that the message in 6.2.0 can be the result of a temporary false positive, rather than a consistent high RTT, and the new sampling approach will eliminate the noise from those. Customers open tickets with "sidekiq says there is a problem with my Redis instance", and after investigation there is no issue with the Redis instance, and the ping is typically low.

**Comment by mperham** [comment]
Got it, thanks for the feedback. I need to remember that with great power
comes great responsibility, sorry for the support noise. I will ship 6.2.1
tomorrow.

**Comment by mperham** [comment]
6.2.1 is out.

**Comment by edmorley** [comment]
Thank you :-)

**Comment by soma** [comment]
❤️

**Comment by MGPalmer** [comment]
Looks like it's working :) Thanks!
