### ISSUE TITLE
Is it possible to get the morgue to auto-clean itself?

### ISSUE THREAD

**Issue by btzc** [mperham/sidekiq#4853]
:wave: Hey! Sorry for the noob question but I was wondering if there was a way get Sidekiq to auto-clean the morgue. I saw in the options I can set `dead_timeout_in_seconds` and `dead_max_jobs` but these seem to only get used when `DeadSet.new.kill` gets called. https://github.com/mperham/sidekiq/blob/285d6541a51d2d06f288036e96244f98f012c6ca/lib/sidekiq/api.rb#L719

I'm looking for a way to try and delete all jobs that are older than a certain amount of time from the morgue automatically. Should I create a cron job to do this for me or is this something I can get Sidekiq to do out of the box? Thanks!

**Comment by mperham** [comment]
It does clean anything older than six months, which is the default for that timeout value. You can adjust that timeout, but I would recommend no smaller than one month. Yes, I suppose you could put in a cron job to clean proactively.

**Comment by btzc** [comment]
Hey thanks for the quick reply! I might be using the options wrong or maybe I'm misunderstanding how it's meant to work but I've included my options below:

```
[2] pry(main)> Sidekiq.options
=> {:queues=>['default'],
 :labels=>[],
 :concurrency=>10,
 :require=>".",
 :environment=>nil,
 :timeout=>8,
 :poll_interval_average=>nil,
 :average_scheduled_poll_interval=>5,
 :error_handlers=>[#<Sidekiq::ExceptionHandler::Logger:0x000055da9b800068>],
 :death_handlers=>
  [#<Proc:0x000055da9b968248@/usr/local/bundle/gems/sidekiq-pro-4.0.5/lib/sidekiq/batch/death.rb:59 (lambda)>],
 :lifecycle_events=>{:startup=>[], :quiet=>[], :shutdown=>[], :heartbeat=>[]},
 :dead_max_jobs=>10000,
 :dead_timeout_in_seconds=>120,
 :reloader=>
  #<Proc:0x000055da9ad3ce88@/usr/local/bundle/gems/sidekiq-5.2.7/lib/sidekiq.rb:37>,
 :backup_limit=>1000
```

<img width="1208" alt="Screen Shot 2021-03-25 at 2 07 23 PM" src="https://user-images.githubusercontent.com/14955042/112521945-747c7100-8d73-11eb-9df0-a4bad1e7d6a7.png">

Just to test it out I had set the `dead_timeout_in_seconds` to be 120 seconds. I had expected it to clean out those two jobs since they were older than 120 seconds but they still remained in the morgue after the options change. Is there something else I'm meant to do or am I misunderstanding how it works?

Thanks a ton!! I really appreciate the help.

**Comment by mperham** [comment]
I don't know why it's not working for you.

**Comment by btzc** [comment]
Is there a way to debug it out on my own? Would be interested in figuring it out. Thanks!

**Comment by mperham** [comment]
It’s just code, throw pry in there and have fun.

**Comment by btzc** [comment]
Figured it out sorry to bug ya! Closing the issue.
