### ISSUE TITLE
Raising BRPOP timeout improves CPU utilization on Redis

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [mperham/sidekiq#4855]
Ruby version: n/a
Rails version: n/a
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.9

GitLab SRE here,

We are running a sizeable Sidekiq deployment, and one of the scaling challenges is Redis CPU. We are pushing around 5k jobs/s with 4-5k clients listening on ~270 queues. 

We've been using CPU profiling to identify opportunities to optimize. We identified 5-11% of CPU of the Redis process being spent in `clientsCronHandleTimeout` -- a code path that is invoked when `BRPOP` calls reach their timeout.

The `BRPOP` timeout in sidekiq is [hardcoded as 2 seconds](https://github.com/mperham/sidekiq/blob/ed8483784348976edc3943ec235bde14e4626210/lib/sidekiq/fetch.rb#L9). While we use [our own fetcher](https://gitlab.com/gitlab-org/sidekiq-reliable-fetch), it had also been using a timeout of 2 seconds.

Our hypothesis was that raising the timeout from 2 seconds to 5 seconds would make us run into the expensive code path less frequently, and thus allow us to reclaim some of those cycles on the mostly single-threaded Redis process.

We rolled out that change last week, and the results are very promising:

![image](https://user-images.githubusercontent.com/11158255/112875022-f1854e80-90c3-11eb-9873-1db64647f31f.png)

On this graph you can see 5-10% of the Redis main thread core being reclaimed. There is some more analysis [in our downstream issue](https://gitlab.com/gitlab-com/gl-infra/production/-/issues/4052).

Since others may be running into similar issues when deploying Sidekiq at scale, we figured it'd be worth sharing. Perhaps it'd be worthwhile to make this BRPOP timeout configurable in Sidekiq core for those who need it.

**Comment by mperham** [comment]
It is configurable in that is extracted into a constant that can be tweaked in your initializer. It will negatively affect process shutdown when you hit Ctrl-C in development.

**Comment by mperham** [comment]
I’ve had customers report 25k jobs/sec so I suspect you can vertically scale your hardware, ie move to faster cores. Are you using Redis 6 and IO threads?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
We're aware that there is a trade-off with shutdown time, which is why I suggested making it configurable. If overriding the constant is the proposed method for doing that, this works for me. :) 

We are already running on GCP C2 instances, which are running on Cascade Lake. Those are some of the fastest currently available, especially when it comes to clock speeds.

We saw some good results by using threaded I/O with Redis 6 on the non-sidekiq Redis instance. For Sidekiq we were blocked due to a [performance regression](https://github.com/redis/redis/issues/8668) affecting BRPOP. This regression [has been patched](https://github.com/redis/redis/pull/8689), and we have backported it to 6.0 and expect to be rolling that out in production soon(tm).

We suspect an additional factor negatively impacting performance is having very long queue lists in our BRPOPs. This is something we're looking at tuning further on our end as well.

**Comment by mperham** [comment]
Good to know, thanks for the links. 

> We suspect an additional factor negatively impacting performance is having very long queue lists in our BRPOPs.

This is one of the reasons I recommend limiting each Sidekiq process to a handful of queues only. Specialize your processes rather than having every process check every queue.

**Comment by mperham** [comment]
I think you've nailed down a scaling issue here: one worker type == one queue does not scale with hundreds of worker types. Fair? It sounds like BRPOP exhibits O(N) behavior with lots of arguments.

The quick workaround for your issue is to put this in your initializer:

Sidekiq::BasicFetch::TIMEOUT = 5

**Comment by smcgivern** [comment]
Yes, exactly that. Thanks for the quick responses here!
