### ISSUE TITLE
Ent Concurrency limiter will revert to previous value after being changed

### ISSUE THREAD

**Issue by reidparhamdexcom** [mperham/sidekiq#4857]
**NOTE:** please consider this _low_ in urgency but maybe “medium” in importance. This is not a serious problem, but more of a curiosity and operational complication. (We rarely change these limiters)

**Summary:** I’m unable to get a change to a concurrency limiter value to actually persist. I have tried a few approaches around stopping/starting the cluster but it appears only clearing out the entire queue and starting fresh was the way to get the new, desired value to stick.

**My best guess:** the rescheduling middleware allows the old limiter values to persist.

------

Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
Rails version: `6.0.3.4`
Sidekiq / Pro / Enterprise version(s): `sidekiq (6.2.0)` `sidekiq-ent (2.2.2)` `sidekiq-pro (5.2.1)`

> **Please include your initializer, sidekiq.yml, and any error message with the full backtrace.**

`initializers/sidekiq.rb`
```ruby
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.reliable_scheduler!
  config.super_fetch!
end
```

`sidekiq.yml`
```yaml
---
:queues:
  - ["JobSchedulers", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_JOB_SCHEDULERS'] || 16384 %>]
  - ["UserInitiatedJobsHighUrgency", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_USER_INITIATED_JOBS_HIGH_URGENCY'] || 8192 %>]
  - ["UserInitiatedJobsLowUrgency", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_USER_INITIATED_JOBS_LOW_URGENCY'] || 512 %>]
  # NOTE: the parallelized clinic export feature (ENABLE_ASYNC_BULK_EXPORTS) requires us to split up processing of clinics by their relative sizes
  # NOTE: equal values cause round-robin-ish processing; without this, a large clinic could fully block a small clinic
  #       (the goal is these groupings all proceed at roughly the same rate)
  - ["ExportSmallBatch", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_EXPORT_SMALL_BATCH'] || 512 %>]
  - ["ExportMediumBatch", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_EXPORT_MEDIUM_BATCH'] || 512 %>]
  - ["ExportLargeBatch", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_EXPORT_LARGE_BATCH'] || 512 %>]
  - ["DailyPushNotifications", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_DAILY_PUSH_NOTIFICATIONS'] || 128 %>]
  - ["WeeklyPushNotifications", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_WEEKLY_PUSH_NOTIFICATIONS'] || 64 %>]
  - ["PeriodicUserTasks", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_PERIODIC_USER_TASKS'] || 3 %>]
  - ["EmailNotifications", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_EMAIL_NOTIFICATIONS'] || 2 %>]
  - ["PeriodicSystemTasks", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_PERIODIC_SYSTEM_TASKS'] || 1 %>]
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 1 %>
:timeout: 98
```

> **If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?**

Yes! Thanks.

## User Story

Given I have a group of Sidekiq processes with identical configurations
When I change to a concurrency limiter (stored and propagated as `ENV[]` var)
And I perform a rolling restart (Kubernetes 1.15)
Then I see concurrency limiter values change as expected
And when _some event happens_ the concurrency limiter reverts to its previous value

## The Limiter
```ruby
Sidekiq::Limiter.concurrent(
  :heavy_db_work,
  ENV['CONCURRENT_HEAVY_DB_WORK_LIMIT'], # this env var is provided at runtime by Kubernetes mounting ConfigMaps
  wait_timeout: 15,
  lock_timeout: 1200, # these are large, long-running exports
)
```
…its metrics look good: (we’re not seeing this odd side effect from overages or reclamation)
<img width="753" alt="Screen Shot 2021-04-02 at 12 16 51 PM" src="https://user-images.githubusercontent.com/59100293/113446755-5b944100-93ad-11eb-940e-69a4c20f159e.png">

## Hypotheses

* Is this a race condition during rolling restarts?
  * Yes, absolutely; that’s understandable — (as I read it…) pods with the “old” limiter value that are still online and doing work will try hard to set the value they know it should be (`if not (lsz + zsz + psz == tonumber(ARGV[1])) then`)
  * (I would assume…) the last pod to restart be the one to finally see and correct the value to what it should “now” be?
* Is this a race condition when I scale everything down (wait ~10 minutes) and then scale back up?
  * Yes — why?!
  * Is SuperFetch doing this? (No; I did not see coincidental log messages of SuperFetch job recoveries to the resets of the limiters)
  * Is this coincidental to process startup? No, there’s something not quite visible to me triggering the change

My best guess: the `Sidekiq::Limiter::Middleware#reschedule` method is passing along the older limiter value and allowing it to persist in Redis beyond pod restarts.

My remaining curiosity: why wouldn’t the new, ongoing work see the current limiter value and reset the side effect from the reschedules? (I suspect this is a side effect of an optimization to reduce reads/writes on the limiters’ values.)

## The Logs

```
# TZ=UTC
# I changed the k8s configmap and triggered a rolling restart of our Sidekiq deployment (6 replicas)
M 02 Apr 14:32:18.492 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# something happened
M 02 Apr 14:44:08.977 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# I triggered another rolling restart of our Sidekiq pods; it saw the correct current ENV var value
M 02 Apr 15:26:07.301 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# something happened
M 02 Apr 15:39:40.104 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# I triggered another rolling restart of our Sidekiq pods; it saw the correct current ENV var value
M 02 Apr 15:41:49.821 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# something happened
M 02 Apr 16:12:17.725 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# leader change?
M 02 Apr 17:07:38.080 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# something happened
M 02 Apr 17:08:05.486 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# I scaled the k8s deployment down to 0 replicas, let it sit for a bit, and then scaled up to 6 replicas
M 02 Apr 18:21:15.757 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# something happened
M 02 Apr 18:39:17.619 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# I deleted all the queues and batches
M 02 Apr 19:25:46.526 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# possibly one of the last reschedules or batch callbacks firing?
M 02 Apr 19:35:47.616 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
# I started up the soak test again and finally see the expected value; will it persist? (I think so)
M 02 Apr 19:36:10.239 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 25 to 60, rebuilding...
# dang it!!!
M 02 Apr 19:50:12.787 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 25, rebuilding...
```

**Comment by mperham** [comment]
When you have a rolling restart, you have both old and new processes running at the same time. Seems like some of them will be running with 25, others with 60 and there will be a race condition as to which hits Redis last to resize it. Are your old processes running for hours after signalling shutdown due to long running jobs?

PS You may not care about this but this weight will result in an Array of 16384 elements and eat a fair amount of memory:

- ["JobSchedulers", <%= ENV['SIDEKIQ_QUEUE_WEIGHT_JOB_SCHEDULERS'] || 16384 %>]

I would recommend sticking to queue weights in the range of 1-100.

**Comment by reidparhamdexcom** [comment]
@mperham the rolling restart race condition makes perfect sense to me.

What’s odd is I confirmed the race will reoccur after a full shutdown, wait, and startup sequence. See the logs around `02 Apr 18:21:15.757` above. That involved…

```
kubectl -n <namespace> delete hpa <name>
kubectl -n <namespace> scale deployment <name> --replicas=0
# wait 10-ish minutes; confirm zero replicas running and zero processes in the web UI
kubectl -n <namespace> scale deployment <name> --replicas=6
```

Thanks for the weighting tips! I think we can afford the memory in this case — the ratio of work performed per queue is something that’s moderately inflexible for this use case. (We did previously have strictly ordered queues but the blocking behavior between them was becoming problematic)

**Comment by mperham** [comment]
It sounds like there's a process that still has the old value. It may not be a worker process, maybe you have a rake or web process that is also using that limiter but didn't pick up the ENV change?

**Comment by reidparhamdexcom** [comment]
Thanks! We do run the Sidekiq web UI in a different container. I’ll try that and also the front end workloads.

The only class that uses this specific limiter is a worker class, so I’m quite confident the only invocation of the limiter are from the Sidekiq processes.

**Comment by reidparhamdexcom** [comment]
And, to confirm end to end on the setting…

ConfigMap:
```
kubectl -n <namespace> get configmap -o yaml | grep HEAVY
    CONCURRENT_HEAVY_DB_WORK_LIMIT: "60"
```

Shell:
```
kubectl -n <namespace> exec…
…
env | grep HEAVY
CONCURRENT_HEAVY_DB_WORK_LIMIT=60
```

Rails console:
```
bin/rails c
2.7.2 :001 > ENV['CONCURRENT_HEAVY_DB_WORK_LIMIT']
 => "60" 
2.7.2 :002 > RogueEnv.CONCURRENT_HEAVY_DB_WORK_LIMIT
 => 60 
```

**Comment by reidparhamdexcom** [comment]
Aha! It totally was the pod running the web UI. Thanks so much, Mike. I’ll update our internal docs for how to change limiter values 😃 

Steps to reproduce…

1. Set ConfigMap limiter value to 65 (anything different from before)
2. Restart every single Rails pod (3 deployments: interactive, sidekiq, and private API)
3. Confirm 65 is new agreed value across all processes (and in Redis logs)
```
M 02 Apr 20:48:51.065 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 60 to 65, rebuilding...
```
4. Set `ENV` override for only the private API deployment
5. Observe private API restart
6. See private API try to change the limiter
```
M 02 Apr 20:51:52.929 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 65 to 55, rebuilding...
```
7. See the next Sidekiq job execution set the expected value
```
M 02 Apr 20:51:55.959 # [sidekiq] Concurrent limiter 'heavy_db_work' changed size from 55 to 65, rebuilding...
```

That settles it enough for me. I want to suggest any of these actions as helpful for whomever might run into this quirk in the future… (but understand if they don’t make the cut)

 * Add note in https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting regarding the required restart of _every single process_ for a concurrent limiter change to stick
 * Add identifiable information in the `[sidekiq] Concurrent limiter…` warn logger about which client triggered the change (I have no clue if this is possible in the Lua context for Redis)
 * Log from the Ruby side when a limiter changes (it appears this would require more round trips; this seems the least important)

**Comment by reidparhamdexcom** [comment]
@mperham this can be closed if/when you’d like. Thanks, again!
