### ISSUE TITLE
Sidekiq Pro, Feature Request: Dead Orphan Notification

### ISSUE THREAD

**Issue by kellysutton** [mperham/sidekiq#4859]
After looking at the public APIs in Sidekiq Pro, we were excited to see that `SuperFetch` now allows specifying of an "orphan handler." This is great! We're now able to alert specific teams when their jobs might be poison pills.

We'd also like to alert teams when a poison pill job definitely won't be retried anymore (i.e. the job is moved to the DeadSet). We noticed from the source that notify_orphan is not called when super fetch moves the job to the dead set. Would it be possible to include that information in the `orphan_handler` callback?

**Comment by mperham** [comment]
Good idea. Today you can't tell the difference between an innocent orphan job being rescued and a dangerous poison pill being killed. The orphan handler looks like this:

```ruby
config.super_fetch! do | jobstr |
  # jobstr is the raw string from Redis, we don't parse it for you because even
  # JSON parsing could be the trigger for a poison pill crash.
end
```

The next Pro release (5.2.2) adds a new `pill` parameter to the block above. If `pill` is nil, that means this was a normal orphan rescue. If it is not nil, that means it was determined to be a poison pill and the job was killed. You can find the job in the Dead set using that item:

```ruby
config.super_fetch! do | jobstr, pill |
  p [pill.klass, pill.jid, pill.job_string, pill.dead_score]
  jobstr = Sidekiq.redis {|c| c.zrangebyscore("dead", pill.dead_score, pill.dead_score).first
end
```
