### ISSUE TITLE
Job logging

### ISSUE THREAD

**Issue by dudo** [mperham/sidekiq#4860]
https://github.com/mperham/sidekiq/blob/3b5ae30c4e5e9e760268243ab5c14664a2f8d236/lib/sidekiq/job_logger.rb#L16

Can we change these to `debug`? Or maybe give them a bit more context if you feel strongly about keeping them around? Not a huge blocker, as I'm just going to remove the middleware, but figured I'd bring it up.

**Comment by dudo** [comment]
Oh... that's not middleware anymore. hmmm... Seems like I'd have to call all our jobs with a custom job_logger, that does nothing, eh?

**Comment by dudo** [comment]
Nope. The options get passed down by `Launcher.new`, which gets its options hash from `Sidekiq.options`. I think I preferred the middleware...

**Comment by mperham** [comment]
This is pretty baked into everyone's assumptions about Sidekiq output now. If you have specific improvements, I'm happy to hear them or see PRs but I don't want nebulous "can we improve this?" issues lingering open as there's no specific resolution.
