### ISSUE TITLE
Sidekiq Pro / Dogstatsd 5.x compatibility

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#4863]
Dogstatsd just released 5.0.0 with the breaking API change that was in 4.9.0 (referenced here - https://github.com/mperham/sidekiq/issues/4849)

Will Sidekiq Pro be updated to handle this API change with an upcoming version?

**Comment by mperham** [comment]
https://github.com/DataDog/dogstatsd-ruby/issues/173

I'd prefer if they restore compatibility. I really don't like the hard cut of 4.x + batch or 5.x + flush. That forces me to mandate one version or another. We'll see how they respond.

**Comment by petergoldstein** [comment]
@mperham We just deployed Sidekiq 5.2.2 and Dogstatsd 5.0.0 in combination, and we encountered an error in our environment indicating that the libraries are not compatible:

<img width="623" alt="Screen Shot 2021-04-08 at 4 04 27 PM" src="https://user-images.githubusercontent.com/421488/114106796-70c51000-9884-11eb-9dfd-ceb5b855546b.png">

**Comment by mperham** [comment]
Show me your initializer.

**Comment by mperham** [comment]
The `batch` method is re-introduced in [dogstatsd-ruby 5.0.1](https://github.com/DataDog/dogstatsd-ruby/pull/176). I don't believe it has been released yet.

**Comment by petergoldstein** [comment]
@mperham Here is the initializer:

    def redis_url
      Rails.application.config.redis[:redis_url]
    end

    Sidekiq::Pro.statsd = -> { Datadog::Statsd.new('localhost', 8125, namespace: 'sidekiq') }

    Sidekiq.configure_server do |config|
       config.redis = {
         url: redis_url,
         network_timeout: 5
       }
      config.server_middleware do |chain|
        require 'sidekiq/middleware/server/statsd'
        chain.add Sidekiq::Middleware::Server::Statsd
      end
    end

    Sidekiq.configure_client do |config|
      config.redis = {
         url: redis_url,
         network_timeout: 5
      }
    end

**Comment by mperham** [comment]
I thought so. You use `Sidekiq::Pro.dogstatsd = ...`

**Comment by petergoldstein** [comment]
@mperham Ok.  What should we be doing instead?

**Comment by mperham** [comment]
use Sidekiq::Pro.dogstatsd = ... Instead of Sidekiq::Pro.statsd = ...

**Comment by petergoldstein** [comment]
@mperham Danke.

**Comment by mperham** [comment]
In retrospect, it’s not a great API design to provide different setters for different types. Easy to make the mistake you made.

**Comment by petergoldstein** [comment]
Especially when the names are so similar.  But no worries.  Thanks for clarifying.

The non-deprecated removal of `batch` on the Dogstatsd side was a bigger issue.
