### ISSUE TITLE
Namespacing with Sidekiq

### ISSUE THREAD

**Issue by matt-taylor** [mperham/sidekiq#4864]
Ruby version: 2.5.5
Rails version: 5.2+
Sidekiq / Pro / Enterprise version(s): 6.2.1, 5.2.0, 2.2.0

At present Sidekiq allows the usage of passing in a namespace when building a redis connection.
https://github.com/mperham/sidekiq/blob/v6.2.1/lib/sidekiq/redis_connection.rb#L60

`Redis::Namespace` is currently in development of v2.0.0 which will remove the ability to make [AdministrativeCommands](https://github.com/resque/redis-namespace/blob/v1.8.1/lib/redis/namespace.rb#L207-L223) on the Namespaced Redis Object. In `v1.8.1` a [Warning is displayed](https://github.com/resque/redis-namespace/blob/v1.8.1/lib/redis/namespace.rb#L330-L345).

`Sidekiq::Ent` v2.20 currently uses `script` to load scripts on the redis namespaced redis object (when a namespace is passed into the Redis connection). 
I am unsure if `Sidekiq::Ent` or `Sidekiq::Pro` utilizes any other of the [AdministrativeCommands](https://github.com/resque/redis-namespace/blob/v1.8.1/lib/redis/namespace.rb#L207-L223) as defined by Redis::Namespace, but can this be fixed? Seems like a straightforward fix would be to use the `client` on the namespaced redis object for a subset of commands. 

We have pinned the version of `redis-namespace ~>1.0` so the major version upgrade does not effect us, but we would like to upgrade eventually.

**Comment by mperham** [comment]
If this becomes an issue, I'm more likely to remove support for namespaces in Sidekiq 7. I've argued against using them for years. Is there some reason why you use namespaces instead of databases?

* https://www.mikeperham.com/2015/09/24/storing-data-with-redis/
* https://www.mikeperham.com/2017/04/10/migrating-from-redis-namespace/

**Comment by matt-taylor** [comment]
Understood. That makes sense.

Default Redis conf is set to allow for 16 databases as defined in `redis.conf` for redis v6.0
https://raw.githubusercontent.com/redis/redis/6.0/redis.conf
> \# Set the number of databases. The default database is DB 0, you can select
> \# a different one on a per-connection basis using SELECT <dbid> where
> \# dbid is a number between 0 and 'databases'-1
> databases 16

We currently use a managed Redis provider and changing this number seems difficult at best (I have opened a ticket with them to see if it is possible).

We were more keen on using namespacing because it essentially allows for boundless namespaces as we build out our testing infrastructure that could include more than the default number of redis databases.

For our purposes, namespacing was the most straightforward solution. But if Sidekiq will not supported redis-namespace gem in the future we will push on our provider to see about increasing DB counts.

**Comment by mperham** [comment]
Yeah, that’s been 99% of the pushback. The SaaS Redis providers don’t want
to support databases because it would cannibalize low end (testing,
staging) instance sales and clustering support is much harder with
multi-db.
