### ISSUE TITLE
FloatDomainError when opening /busy

### ISSUE THREAD

**Issue by EdCordata** [mperham/sidekiq#4870]
Ruby version: 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
Rails version: Rails 6.0.3.3
Sidekiq / Pro / Enterprise version(s): regular sidekiq version

```ruby
# config/initializers/custom/sidekiq.rb
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  config.redis = 'redis://localhost:6379/1'
end

Sidekiq.configure_client do |config|
  config.redis = 'redis://localhost:6379/1'
end
```
```ruby
# Gemfile
gem 'sidekiq', github: 'mperham/sidekiq'
```
```ruby
# routes
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/jobs', constraints: SidekiqConstraint.new #  constraint always returns true
end
```
```ruby
# app/workers/hard_worker.rb
class HardWorker
  include Sidekiq::Worker

  def perform
    sleep 5
  end

end
```

Error screenshot:
![FloatDomainError at _busy - Google Chrome 2021-04-09 11 35 41](https://user-images.githubusercontent.com/71574639/114153454-2d928d80-98d4-11eb-994c-f76108232bd9.png)

This happens only in `/busy` path, others work fine:
![1](https://user-images.githubusercontent.com/71574639/114153799-91b55180-98d4-11eb-9e88-7fbeecf4e164.png)

This error happens when `sidekiq` is not running, only rails server.

**Comment by mperham** [comment]
I need the full backtrace.
