### ISSUE TITLE
"undefined method `[]' for nil:NilClass" in /busy

### ISSUE THREAD

**Issue by EdCordata** [mperham/sidekiq#4871]
Ruby version: 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
Rails version: Rails 6.0.3.3
Sidekiq / Pro / Enterprise version(s): regular sidekiq version

```ruby
# config/initializers/custom/sidekiq.rb
require 'sidekiq/web'

Sidekiq.configure_server do |config|
  config.redis = 'redis://localhost:6379/1'
end

Sidekiq.configure_client do |config|
  config.redis = 'redis://localhost:6379/1'
end
```
```ruby
# Gemfile
gem 'sidekiq', github: 'mperham/sidekiq'
```
```ruby
# routes
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/jobs', constraints: SidekiqConstraint.new #  constraint always returns true
end
```
```ruby
# app/workers/hard_worker.rb
class HardWorker
  include Sidekiq::Worker

  def perform
    sleep 5
  end

end
```

Error screenshot:
![2](https://user-images.githubusercontent.com/71574639/114155547-777c7300-98d6-11eb-8974-8f6a55402fde.png)

This error happens when there is a worker running in the background and when there is not.
Other tabs work fine.

**Comment by mperham** [comment]
`regular sidekiq version` is not a version number. Please help me out by giving me actual usable data to debug with. I can see v6.2.1 in your backtrace screenshot.

It appears that your Redis has some old process records with incomplete data. If this is your local Redis database and isn't important (e.g. development), use `redis-cli -n 1 flushdb` to clear old data and start fresh.
