### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError

### ISSUE THREAD

**Issue by hckcksrl** [mperham/sidekiq#4874]
Ruby version: 2.5.3
Rails version: 5.2.2
Sidekiq / Pro / Enterprise version(s): 5.2.5

2 sidekiq ec2 instances in use on aws

When the pool: 5, concurrency: 20 is set, the error occurs repeatedly, so the pool: 20, concurrency: 10 is set, but it still occurs. 
When retrying, some of them are not in a waiting state, but workers do not work and an ActiveRecord::ConnectionTimeoutError occurs.

### db
```
pool: 5 => 20
```
### sidekiq
```
staging:
  :concurrency: 10 
production:
  :concurrency: 20 => 10
```
## puma
```
min_threads: 5  max_threads: 5
```
### error
ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use
/var/www/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:201:in `block in wait_poll'
/var/www/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `loop'

**Comment by mperham** [comment]
Something else is using database connections and holding onto them. It's impossible for me to tell how or why.
