### ISSUE TITLE
Trap process's kill signal

### ISSUE THREAD

**Issue by hxt365** [mperham/sidekiq#4877]
Can you show me a way to trap the kill signal in my code when Sidekiq decides to kill a process so that I can log a meaningful error message?

**Comment by mperham** [comment]
Can you be more specific with the use case? Are you talking about with enterprise multi process?

**Comment by hxt365** [comment]
Thank you for the quick response. Currently I have multiple long jobs on the job queue, and sometimes they consume a lot of memory. I also implemented a manager that constantly checks memory usage of processes. If a process consumes more memory than a given threshold, then the manager will make it quite and stop it when all jobs in it finish, or after a time T. However, jobs in quite processes continue running and can consume more memory, so those processes can get killed by OOM killer. 
So, my problem is that I want to log a message for each job when a process gets killed or stopped.

**Comment by mperham** [comment]
I mean there’s Kernel#trap. I don’t know anything else.
