### ISSUE TITLE
Issues updating Sidekiq-Pro due to `versions` file format

### ISSUE THREAD

**Issue by dougedey-shopify** [mperham/sidekiq#4880]
Ruby version: 2.7.2
Rails version: 6.1.3.1
Sidekiq / Pro / Enterprise version(s): 6.2.1 / 5.2.1 (moving to 5.2.2)

This isn't an issue with the source/any of the Gems directly, but an issue with running `bundle update sidekiq-pro`

Timeline: 

* Dependabot detected a new version last week and PR'd a bump last week that I merged this with no issues
* I tried to update a different gem and got an issue that Bundle could not find Sidekiq-Pro 5.2.2
* Running `gem list sidekiq-pro --all --remote --source $SOURCE_URL` shows *5.2.2 is available* [0]
but `bundle update sidekiq-pro` won't pick it up: `Could not find sidekiq-pro-5.2.2 in any of the sources` and it knocks it down to 5.2.1: `Using sidekiq-pro 5.2.1 (was 5.2.2)`
* adding --verbose to bundle update shows it's getting a 206 partial response from the remote URL
* `gem install ... --source` works [1]

One of my colleagues identified that deleting the bundler cache locally (`rm -rf ~/.bundle/cache/compact_index/gems.contribsys.com...`) works around the issue. But I wanted to dig deeper

From investigating the Bundler source, Bundler expects versions files to be appended to, so when you do a request to update it looks at the size of the local cache, and uses the [Range](https://github.com/rubygems/rubygems/blob/96e5cff3df491c4d943186804c6d03b57fcb459b/bundler/lib/bundler/compact_index_client/updater.rb#L38-L45) header to request (n-1) bytes to the end of the file on the [server](https://github.com/rubygems/rubygems/blob/96e5cff3df491c4d943186804c6d03b57fcb459b/bundler/lib/bundler/compact_index_client/updater.rb#L54-L58) (and appends when it has a partial response to the local cache).

This is how [Ruby Gems](https://index.rubygems.org/versions) provides updates, the updates go to the end of the file.

But for Sidekiq-Pro, the version is appended to the existing list for the sidekiq pro entry

Is this something that can be fixed with future updates? Right now I have to wait for people to hit this issue and inform them to clear their bundler cache (I'm not 

[0]

```
*** REMOTE GEMS ***
sidekiq-pro (5.2.2, 5.2.1, 5.2.0, 5.1.1, 5.1.0, 5.0.1, 5.0.0, 4.0.5, 4.0.4, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.7.1, 3.7.0, 3.6.1, 3.6.0, 3.5.4, 3.5.3, 3.5.2, 3.5.1, 3.5.0, 3.4.5, 3.4.4, 3.4.3, 3.4.2, 3.4.1, 3.4.0, 3.3.3, 3.3.2, 3.3.1, 3.2.2, 3.2.1, 3.1.0, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.8, 2.0.5, 2.0.4, 2.0.3, 2.0.1, 1.9.3, 1.9.2, 1.9.1, 1.7.6, 1.7.5, 1.7.1, 1.6.0, 1.5.1, 1.2.4, 0.0.3)
sidekiq-process-health-check (1.0.0, 0.0.7, 0.0.6)
sidekiq-process_manager (1.0.1, 1.0.0)
sidekiq-prometheus-exporter (0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0)
sidekiq-promise (0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0)
```

[1]

```
gem install  sidekiq-pro --version 5.2.2  --source $SOURCE_URL
Fetching sidekiq-pro-5.2.2.gem
Successfully installed sidekiq-pro-5.2.2
Parsing documentation for sidekiq-pro-5.2.2
Installing ri documentation for sidekiq-pro-5.2.2
Done installing documentation for sidekiq-pro after 0 seconds
1 gem installed
```

**Comment by mperham** [comment]
https://github.com/rubygems/rubygems/issues/4543
