### ISSUE TITLE
sidekiqswarm support for running different worker processes

### ISSUE THREAD

**Issue by amitsaxena** [mperham/sidekiq#4883]
As of now you can run multiple worker processes of the same kind on a single dyno in Heroku using something like this:

```
worker: SIDEKIQ_MAXMEM_MB=1700 SIDEKIQ_COUNT=8 bundle exec sidekiqswarm
```

We use different worker processes in our application for different types of jobs and some of them have custom config like a different database query timeout for long running queries, etc. - so it's not possible to merge them. Instead it will be really nice if I could use `sidekiqswarm` to spawn different worker processes from different config files. Below is an example to elaborate more on the use case.

Let's say I have 3 types of workers in my Procfile:
```
worker_one: bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_one.yml
worker_two: WORKER_TWO=true bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_two.yml
worker_three: WORKER_THREE=true bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_three.yml
```

Now I want to use `sidekiqswarm` to spawn all those 3 worker processes on a single dyno. It will be really nice if `sidekiqswarm` can read the process details from a config file and start the processes using that. Something like this:

```
# Procfile
worker: bundle exec sidekiqswarm -r ./lib/application.rb --swarm-config config/sidekiqswarm.yml

# config/sidekiqswarm.yml
:processes:
  - :command: SIDEKIQ_MAXMEM_MB=1700 bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_one.yml
    :count: 2 # Defaults to 1
  - :command: SIDEKIQ_MAXMEM_MB=1700 WORKER_TWO=true bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_two.yml
    :count: 3 # Defaults to 1
  - :command: SIDEKIQ_MAXMEM_MB=1700 WORKER_THREE=true bundle exec sidekiq -r ./lib/application.rb -C config/sidekiq_three.yml
    :count: 3 # Defaults to 1
```

PS: `WORKER_TWO` & `WORKER_THREE` are env variables we use to have custom config for those workers in code.

**Comment by mperham** [comment]
Use `SIDEKIQ_COUNT=x` with each worker type?

**Comment by mperham** [comment]
```
worker_one: SIDEKIQ_COUNT=2 bundle exec sidekiqswarm -r ./lib/application.rb -C config/sidekiq_one.yml
worker_two: SIDEKIQ_COUNT=3 bundle exec sidekiqswarm -r ./lib/application.rb -C config/sidekiq_two.yml
worker_three: SIDEKIQ_COUNT=3 bundle exec sidekiqswarm -r ./lib/application.rb -C config/sidekiq_three.yml
```

**Comment by amitsaxena** [comment]
But wouldn't that need 3 dynos? I want to run the 3 types of worker processes on the same dyno using `sidekiqswarm`.

**Comment by mperham** [comment]
Unfortunately that conflicts with the design on sidekiqswarm. Swarm provides multiple, identical copies of Sidekiq. It's not designed to manage different configurations.

**Comment by mperham** [comment]
Anyone have an example of starting multiple processes within one dyno?

**Comment by amitsaxena** [comment]
> Anyone have an example of starting multiple processes within one dyno?

Is that even technically possible now? Or are you looking for a potential use case? If you are looking for a potential use case then I could describe one. We have a `critical` queue (needs a dedicated worker) which is low volume but needs more resources, so we run it on a PL dyno. Now it uses very little resources of that dyno so we want to add more workers which process the `default` and `low` priority queues. Then we have another worker which needs a higher query timeout and reads from a follower database - we can use the spare capacity on the  PL dyno to run this worker as well. As of now we have to run all of these 3 workers on separate dynos and it isn't very cost efficient.

**Comment by mperham** [comment]
Sure, I get all that. I don’t have a solution. Use 1x or 2x dynos where scale is low.

**Comment by amitsaxena** [comment]
> Use 1x or 2x dynos where scale is low
The jobs need more memory and error out on 2x dynos, so that's not an option for us.
