### ISSUE TITLE
Sidekiq queue stuck "paused". And pausing then unpausing causes the queue to drain normally

### ISSUE THREAD

**Issue by skunkworker** [mperham/sidekiq#4885]
Ruby version: jruby-9.2.13.0
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): 6.2.1, pro: 5.2.2

```
 /usr/bin/java -Djdk.home=/usr -Djruby.home=/usr/local/rvm/rubies/jruby-9.2.13.0 -Djruby.script=jruby -Djruby.shell=/bin/sh -Djffi.boot.library.path=/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/ppc64le-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/sparcv9-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/mips64el-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/ppc64-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/x86_64-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/aarch64-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/arm-Linux:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jni/i386-Linux -Xss2048k -Dsun.java.command=org.jruby.Main -Xbootclasspath/a:/usr/local/rvm/rubies/jruby-9.2.13.0/lib/jruby.jar -cp  -Djava.security.egd=file:/dev/urandom -Djava.security.egd=file:/dev/./urandom -XX:+UseConcMarkSweepGC -XX:HeapDumpPath=/srv/app/current/tmp/app_app-worker.hprof -XX:-HeapDumpOnOutOfMemoryError -XX:+ExitOnOutOfMemoryError -Xms3072m -Xmx3072m -server -Djruby.cext.enabled=true org/jruby/Main --disable:did_you_mean /usr/local/rvm/rubies/jruby-9.2.13.0/bin/jruby_executable_hooks /srv/app/shared/bundle/jruby/2.5.0/bin/sidekiq -q app,500 -q node3,400 -q app_batch_data,400 -q app_lower_data,200 -q app_lower_data2,200 -q app_lower_data3,200 -q app_loest_data,1 -c 18 -t 30
```

Earlier today on our application we ran into an issue where on of our queues was "stuck". We are using the latest `sidekiq-pro` and this queue `node3` had a latency of 12 hours and jobs were continually being added into the queue, but the queue was never draining.

We didn't observe any out of memory errors, out of disk space errors or anything else other than no jobs were being processed on the specific queue.

When using the `sidekiq/api` rails console we confirmed that the queue was not paused, so we went ahead and paused the queue, confirmed it was paused, then unpaused the queue and this caused the queue to start draining like normal. The sidekiq process on `node3` was never touched or restarted.

Below is the commands that were run in a rails console.

```
jruby-9.2.13.0 :036 > Sidekiq::Queue.new("node3")
 => #<Sidekiq::Queue:0x26d02dc6 @rname="queue:node3", @name="node3"> 
jruby-9.2.13.0 :037 > queue = _
 => #<Sidekiq::Queue:0x26d02dc6 @rname="queue:node3", @name="node3"> 
jruby-9.2.13.0 :038 > queue.count
 => 377 
jruby-9.2.13.0 :039 > queue.count # queue still increasing
 => 378 
jruby-9.2.13.0 :040 > queue.paused?
 => false 
jruby-9.2.13.0 :041 > queue.pause!
 => true 
jruby-9.2.13.0 :042 > queue.paused?
 => true 
jruby-9.2.13.0 :043 > queue.unpause!
 => true 
jruby-9.2.13.0 :044 > queue.size
 => 381 
jruby-9.2.13.0 :046 > queue.size # now draining
 => 379 
jruby-9.2.13.0 :047 > queue.size
 => 378 
jruby-9.2.13.0 :048 > queue.size
 => 377 
jruby-9.2.13.0 :049 > queue.size
 => 375 
jruby-9.2.13.0 :050 > queue.size
 => 375 
```

@film42

**Comment by mperham** [comment]
I've never seen this behavior before and the pausing code hasn't changed in many versions AFAIK. 🤷🏼‍♂️

**Comment by skunkworker** [comment]
It looks like we have another queue that has gotten stuck in a similar way. Is there information or internal state information that I could dump in order to try to debug this? I could grab a JRuby dump as well if that would be helpful.

**Comment by mperham** [comment]
You can read the code? `bundle open sidekiq-pro`

**Comment by skunkworker** [comment]
I went through the code and it looks like `basic_fetch.rb#notify` does not log if it receives a message to pause or unpause a queue, only `super_fetch.rb#notify` is logging that event. I've added a line there to log out events received in `basic_fetch.rb` and will hopefully capture any events that are going to that instance causing it to change the internal state.
