### ISSUE TITLE
Stale Processes in Heroku

### ISSUE THREAD

**Issue by cmunozgar** [mperham/sidekiq#4891]
Ruby version: 2.6.7
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): Sidekiq v6.2.1 / Sidekiq Pro v5.2.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```
require 'sidekiq/middleware/i18n'
require 'sidekiq/job_logger'

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end

# Configure Server
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDISCLOUD_URL'], concurrency: (ENV['WORKER_CONCURRENCY'] || 2) }
end
# Configure Client
Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDISCLOUD_URL'], size: 2 }
end

module Sidekiq
  class JobLogger
    # override existing log to include the arguments passed to `perform`
    def job_hash_context(job_hash)
      # If we're using a wrapper class, like ActiveJob, use the "wrapped"
      # attribute to expose the underlying thing.
      h = {
        class: job_hash["wrapped"] || job_hash["class"],
        jid: job_hash["jid"]
      }
      h[:bid] = job_hash["bid"] if job_hash["bid"]
      h[:tags] = job_hash["tags"] if job_hash["tags"]
      h[:args] = job_hash["args"] if job_hash["args"]
      h
    end
  end
end
```

```
---
:verbose: false
:concurrency: 2

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  # - recommendable
  - mailers
  - slack
  - maintenance_mode
  - twitter
  - metrics
  - default
  - mailers_low_priority


# you can override concurrency based on environment
production:
  :concurrency: <%= ENV['WORKER_CONCURRENCY'] %>
development:
  :concurrency: 1

:limits:
  counters: 1

:process_limits:
  counters: 1
```

This is not an issue per se with Sidekiq but I wanted to share it here too because it drove me nuts until I finally discovered the root cause. Sidekiq was listing many processes that were quiet and running for days, as you can see in this screenshot.
 
<img width="1420" alt="Screenshot 2021-05-04 at 06 53 13" src="https://user-images.githubusercontent.com/2612865/116962159-8b34b280-aca5-11eb-92af-d82e4526c06d.png">

I clicked the stop button but those processes were not removed. I also tried to remove keys from Redis but that didn't work too.

The root cause of these processes in this stale mode was there were ["phantom" dyno processes still running on an app](https://status.heroku.com/incidents/2236). 

I think this can be useful to others experiencing a similar "issue".

**Comment by mperham** [comment]
I’d heard that Heroku had some recent difficulties in this area; I hope it was a transient bug which they have fixed now.
