### ISSUE TITLE
Fire batch callbacks manually

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#4892]
For testing purposes, it would be nice to be able to force firing callbacks. I've come up with the following hack to do so:

```
  def complete_batch(bid)
    Sidekiq::Batch.new(bid).callbacks["complete"].flat_map { |cc| cc.map { |k, v| k.constantize.new.on_complete(nil, v) } }
  end
```

This allows me to test that my callbacks are setup correctly.

Does Sidekiq Pro support this somehow?

**Comment by mperham** [comment]
Nope, looks like you've got a nice helper for it.

**Comment by mollerhoj** [comment]
Okay, good to know thanks
