### ISSUE TITLE
Frequently unable to install Sidekiq-pro-5.2.2

### ISSUE THREAD

**Issue by pboling** [mperham/sidekiq#4894]
We had this problem on April 13th, across many different machines, and ultimately decided to downgrade to 5.2.1.

Then we upgraded to 5.2.2 again yesterday (May 3rd), and immediately some installs are unable to source the gem.
```
➜  api git:(stage) bundle install           
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://enterprise.contribsys.com/..
Could not find sidekiq-pro-5.2.2 in any of the sources
```

This is an uncommon problem for gems generally, but this 5.2.2 version of Sidekiq-pro in particular seems to be particularly difficult to source.  I'm reporting it here in case anyone else came looking.  We're going to try to stay on 5.2.2 this time, and hopefully with enough repetition it will eventually install everywhere, and we can close this.  

Seems likely to be some kind of a bundler ecosystem problem, but also seems to be particularly relevant to only gems on `https://enterprise.contribsys.com`.  Maybe `https://enterprise.contribsys.com` is using a gem server version that is out of date?

**Comment by mperham** [comment]
There’s two or three closed issues that already cover this. Take a look.

**Comment by pboling** [comment]
Thanks for the hint.  I've now reviewed the following.

https://github.com/mperham/sidekiq/issues/4880
https://github.com/rubygems/rubygems/issues/4543
https://github.com/rubygems/rubygems/pull/4563

I have upgraded to latest bundler, and latest rubygems.
```
% gem -v
3.2.16
% bundle -v
Bundler version 2.2.16
```

Now when I attempt to do a blanket bundle update I get the following:
```
src/rivi/api[stage]% bundle update
Fetching gem metadata from https://enterprise.contribsys.com/..
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://enterprise.contribsys.com/.
Could not find gem 'sidekiq-ent (>= 2)' in rubygems repository https://enterprise.contribsys.com/ or installed locally.
The source contains the following versions of 'sidekiq-ent': 0.7.10, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0,
1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1
```

Now I'm wondering if there isn't really a fix for this, and @mperham did not imply there was one, only that there are related "closed issues".  So maybe we're stuck running an old version?

**Comment by mperham** [comment]
you have to use the “rm” workaround until 2.2.17 is released.

**Comment by pboling** [comment]
Just found https://github.com/mperham/sidekiq/issues/4838.  Will try the `rm` workaround.  Thanks!

**Comment by deivid-rodriguez** [comment]
I'll release 2.2.17 today :+1:.
