### ISSUE TITLE
Nested batches

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#4896]
I understand that a batch will only `complete` once it's child batches `completes`. However it seems that the nesting only works 1 level deep?

```
class PlaygroundManager
  def call
    batch = Sidekiq::Batch.new
    batch.on(:complete, "PlaygroundManager#step1")
    batch.jobs do
      batch2 = Sidekiq::Batch.new
      batch2.on(:complete, "PlaygroundManager#step2")
      batch2.jobs do
        batch3 = Sidekiq::Batch.new
        batch3.on(:complete, "PlaygroundManager#step3")
        batch3.jobs do
          PlaygroundJob1.perform_later
        end
      end
    end
    @bid = batch.bid
  end

  def bid
    @bid
  end

  def step1(_status, options)
    puts "STEP1"
  end

  def step2(_status, options)
    puts "STEP2"
  end

  def step3(_status, options)
    puts "STEP3"
  end

  class PlaygroundJob1 < SidekiqJob
    def perform
    end
  end
end
```

Only STEP3 and STEP2 are completed. Is this a bug, or it is how the system is supposed to work?

**Comment by mperham** [comment]
A batch is considered invalid and will display undefined behavior unless it has a job in it. Your top two batches do not have any jobs in them.

**Comment by mollerhoj** [comment]
Alright, thanks for clarifying that.

As a new user, I find the batch api very difficult to understand. Without knowing how sidekiq works internally, it's hard understand the reasoning behind rules as the one you mention above.

**Comment by mperham** [comment]
I agree. The Batch API is distributed, asynchronous and dynamic. It is very difficult to provide all of that in one easy, simple API.

**Comment by mollerhoj** [comment]
Got it, and I really appreciate how difficult this is to make simple.

I guess what would really help here is reading the reference for the batch api. However, getting access to this is troublesome. I'll open a new issue

**Comment by mperham** [comment]
`bundle open sidekiq-pro` -> lib/sidekiq/batch{/*,.rb}

**Comment by mollerhoj** [comment]
Thanks again. Could you point me in any direction to try and understand why nested batches must have a job to be valid? It seems that to fix the code above I can either:
- A) Add a Job to each Batch that does nothing.
- B) Add a Job to each Batch that starts the nested batch (and nests it in the parent batch using `batch.jobs`)

I see B is proposed here" https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches, but I can't help but feel all this wrapping and unwrapping of batches in jobs is jumping through some strange hoops without knowing why.

**Comment by mperham** [comment]
Sure, understood.

A batch never "executes", jobs execute. If a batch has no jobs, when does it execute? How could Sidekiq determine success/failure and what callbacks to fire?

In thinking about it, I guess I could add a NOOP job to a batch if no jobs are defined; that might fix this limitation but I'm unclear if it would break other semantics.

**Comment by mperham** [comment]
There is one usecase where an empty batch is valid: if a child batch will dynamically add jobs or other batches to its parent batch. But adding a NOOP job to the parent batch shouldn't break that usecase...

**Comment by mollerhoj** [comment]
Wait thats not right, it is? An empty batch is valid only if a child batch adds jobs to its parent (not if batches are added, as demonstrated in the code above)

I get that batches are never executed, but: If a batch has no pending jobs, and its child batch completes/succeeds, should it not also complete/succeed?

I get that a NOOP job would solve this, I just don't see why its even necessary?

**Comment by mperham** [comment]
Also note that you are using ActiveJob with Batches. I don't support that officially as I don't totally control ActiveJob::Base. Try using Sidekiq::Worker.

I see what you mean, your initial example should work because the third batch will run the job and then everything else **should** roll up. I'm not sure what's wrong but I can take a look deeper tomorrow.

**Comment by mollerhoj** [comment]
Ah okay, so batch nesting is actually supposed to work? In that case, I believe I've found a bug. I actually didn't use ActiveJob in the example above, `perform_later` is just an alias. I've made the example clearer below:

```
class TestWorkflow
  def call
    batch1 = Sidekiq::Batch.new
    batch1.on(:complete, "TestWorkflow#step1")
    batch1.jobs do
      batch2 = Sidekiq::Batch.new
      batch2.on(:complete, "TestWorkflow#step2")
      batch2.jobs do
        batch3 = Sidekiq::Batch.new
        batch3.on(:complete, "TestWorkflow#step3")
        batch3.jobs do
          TestJob.perform_async
        end
      end
    end
  end

  def step1(_status, _options)
    puts "Batch 1 completed"
  end

  def step2(_status, _options)
    puts "Batch 2 completed"
  end

  def step3(_status, _options)
    puts "Batch 3 completed"
  end

  class TestJob
    include Sidekiq::Worker
    def perform; end
  end
end
```

```
TestWorkflow.new.call =>
Batch 3 completed
Batch 2 completed
```

Bug: Batch 1 is not completed.

**Comment by mperham** [comment]
The issue was that Batch 2 did not have any jobs so it did not register itself as a child batch to Batch 1, therefore the callback was not fired for Batch 1. Batch 3 did have a job so it registered itself with Batch 2.

I've adjusted the code to handle your case because I do want the callback "rollup" to work as expected.

**Comment by mollerhoj** [comment]
Great! When will the update be available? I just ran `bundle update sidekiq-pro` and tried again, but nothing has changed. I'm on:
```
Using sidekiq 6.2.1
Using sidekiq-pro 5.2.1
```

**Comment by mperham** [comment]
I don’t have a release date. 5.2.2 was released recently so it likely won’t
be for a while. As I mentioned, you can add a NOOP job to get the desired
behavior today.
