### ISSUE TITLE
Sidekiq using wrong job class

### ISSUE THREAD

**Issue by mockdeep** [mperham/sidekiq#4899]
Ruby version: 2.7.3
Rails version: 6.0.3.7
Sidekiq / Pro / Enterprise version(s): 6.2.1 / 5.2.2 / 2.2.2

Once every couple of days we get a really surprising error in out application. It raises an error from a job, but the job that it is trying to execute is the wrong job class. We enqueue the job with one class, and it gets run with a different class. After it fails the first time, the job then gets requeued by Sidekiq and gets run against the correct class.

<details>
  <summary>UniqueCallableJob</summary>

```rb
class UniqueCallableJob < CallableJob
  sidekiq_options unique_for: 30.minutes
end
```
</details>

<details>
  <summary>CallableJob</summary>

```rb
class CallableJob < ApplicationJob

  def perform(callable_name, *args, **kwargs)
    callable_name.constantize.call(*args, **kwargs)
  end

end
```

</details>

<details>
  <summary>ChangeSet::Job (the job that gets executed the first time)</summary>

```rb
module ChangeSet
  class Job < ActiveJob::Base
    include BulkJob # serializes/deserializes arguments

    def perform(change_set_class:, params_sets: [])
      change_set_class.constantize.save(params_sets)
    end

    # used by BulkJob
    def includes(arguments)
      klass = arguments.first.fetch('change_set_class').constantize
      klass.const_defined?(:INCLUDES) ? klass::INCLUDES : {}
    end
  end
end
```
</details>

<details>
  <summary>Error Trace</summary>

    [PROJECT_ROOT]/lib/change_set/job.rb:10 :in `perform`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/execution.rb:40 :in `block in perform_now`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112 :in `block in run_callbacks`
    [GEM_ROOT]/gems/i18n-1.8.10/lib/i18n.rb:314 :in `with_locale`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/translation.rb:9 :in `block (2 levels) in <module:Translation>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `instance_exec`

    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `block in run_callbacks`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/core_ext/time/zones.rb:66 :in `use_zone`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/timezones.rb:9 :in `block (2 levels) in <module:Timezones>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `instance_exec`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `block in run_callbacks`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/logging.rb:25 :in `block (4 levels) in <module:Logging>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180 :in `block in instrument`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24 :in `instrument`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180 :in `instrument`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/logging.rb:24 :in `block (3 levels) in <module:Logging>`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/logging.rb:45 :in `block in tag_logger`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80 :in `block in tagged`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:28 :in `tagged`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80 :in `tagged`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/logging.rb:45 :in `tag_logger`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/logging.rb:21 :in `block (2 levels) in <module:Logging>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `instance_exec`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `block in run_callbacks`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139 :in `run_callbacks`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/execution.rb:39 :in `perform_now`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/execution.rb:25 :in `block in execute`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112 :in `block in run_callbacks`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/railtie.rb:43 :in `block (4 levels) in <class:Railtie>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/execution_wrapper.rb:88 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/reloader.rb:72 :in `block in wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/execution_wrapper.rb:84 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/reloader.rb:71 :in `wrap`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/railtie.rb:42 :in `block (3 levels) in <class:Railtie>`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `instance_exec`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121 :in `block in run_callbacks`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139 :in `run_callbacks`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/execution.rb:23 :in `execute`
    [GEM_ROOT]/gems/activejob-6.0.3.7/lib/active_job/queue_adapters/sidekiq_adapter.rb:42 :in `perform`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196 :in `execute_job`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164 :in `block (2 levels) in process`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138 :in `block in invoke`
    [GEM_ROOT]/gems/scout_apm-4.0.4/lib/scout_apm/background_job_integrations/sidekiq.rb:68 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [PROJECT_ROOT]/lib/sidekiq/honeycomb_middleware.rb:24 :in `block in call`
    [GEM_ROOT]/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70 :in `start_span`
    [PROJECT_ROOT]/vendor/ruby-2.7.3/lib/ruby/2.7.0/forwardable.rb:235 :in `start_span`
    [PROJECT_ROOT]/lib/sidekiq/honeycomb_middleware.rb:17 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-pro-5.2.2/lib/sidekiq/batch/middleware.rb:54 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/unique.rb:151 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent/limiter/middleware.rb:38 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:143 :in `invoke`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163 :in `block in process`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136 :in `block (6 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112 :in `local`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135 :in `block (5 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14 :in `block in call`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/execution_wrapper.rb:88 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/reloader.rb:72 :in `block in wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/execution_wrapper.rb:88 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.7/lib/active_support/reloader.rb:71 :in `wrap`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131 :in `block (4 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257 :in `stats`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126 :in `block (3 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13 :in `call`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125 :in `block (2 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79 :in `global`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124 :in `block in dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11 :in `with`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33 :in `prepare`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123 :in `dispatch`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162 :in `process`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78 :in `process_one`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68 :in `run`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43 :in `watchdog`
    [GEM_ROOT]/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52 :in `block in safe_thread` 
</details>

<details>
  <summary>Job Logs</summary>

```
May 10 15:12:54 stormy-depths-3143 app[slow_worker] INFO I, [2021-05-10T15:12:53.924159 #3]  INFO -- : [ActiveJob] [CallableJob] [adc618ee-b877-4dd5-a086-6ca5dc023085] Enqueued UniqueCallableJob (Job ID: f28fde90-e7d8-43a3-a16f-135f303c71a7) to Sidekiq(default) with arguments: "Campaigns::StepCountsRefresher", #<GlobalID:0x00007faa49482f38 @uri=#<URI::GID gid://synchroform/Campaign/68913>>
May 10 15:12:56 stormy-depths-3143 app[default_worker] INFO I, [2021-05-10T15:12:56.130779 #3]  INFO -- : [ActiveJob] [UniqueCallableJob] [f28fde90-e7d8-43a3-a16f-135f303c71a7] Performing UniqueCallableJob (Job ID: f28fde90-e7d8-43a3-a16f-135f303c71a7) from Sidekiq(default) enqueued at 2021-05-10T22:12:53Z with arguments: "Campaigns::StepCountsRefresher", #<GlobalID:0x00007fb7a9b8dbf8 @uri=#<URI::GID gid://synchroform/Campaign/68913>>
May 10 15:12:56 stormy-depths-3143 app[default_worker] ERROR E, [2021-05-10T15:12:56.138510 #3] ERROR -- : [ActiveJob] [UniqueCallableJob] [f28fde90-e7d8-43a3-a16f-135f303c71a7] Error performing UniqueCallableJob (Job ID: f28fde90-e7d8-43a3-a16f-135f303c71a7) from Sidekiq(default) in 7.43ms: NoMethodError (undefined method `save' for Campaigns::StepCountsRefresher:Class):
May 10 15:12:56 stormy-depths-3143 app[default_worker] WARN pid=3 tid=3n1b WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","unique_for":"1800","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"UniqueCallableJob","args":[{"job_class":"UniqueCallableJob","job_id":"f28fde90-e7d8-43a3-a16f-135f303c71a7","provider_job_id":null,"queue_name":"default","priority":null,"arguments":["Campaigns::StepCountsRefresher",{"_aj_globalid":"gid://synchroform/Campaign/68913"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2021-05-10T22:12:53Z"}],"jid":"2158e415421cce609ff008af","created_at":1620684773.9197536,"unique_token":"baa439b2375562ccecda43a764aa2c7180749f34","unlocks_at":"1620686573.9197733","enqueued_at":1620684773.921941},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"unique_for\":\"1800\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"UniqueCallableJob\",\"args\":[{\"job_class\":\"UniqueCallableJob\",\"job_id\":\"f28fde90-e7d8-43a3-a16f-135f303c71a7\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"Campaigns::StepCountsRefresher\",{\"_aj_globalid\":\"gid://synchroform/Campaign/68913\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-05-10T22:12:53Z\"}],\"jid\":\"2158e415421cce609ff008af\",\"created_at\":1620684773.9197536,\"unique_token\":\"baa439b2375562ccecda43a764aa2c7180749f34\",\"unlocks_at\":\"1620686573.9197733\",\"enqueued_at\":1620684773.921941}"}
May 10 15:13:26 stormy-depths-3143 app[default_worker] INFO I, [2021-05-10T15:13:25.785192 #3]  INFO -- : [ActiveJob] [UniqueCallableJob] [f28fde90-e7d8-43a3-a16f-135f303c71a7] Performing UniqueCallableJob (Job ID: f28fde90-e7d8-43a3-a16f-135f303c71a7) from Sidekiq(default) enqueued at 2021-05-10T22:12:53Z with arguments: "Campaigns::StepCountsRefresher", #<GlobalID:0x00007ff1a3c232a0 @uri=#<URI::GID gid://synchroform/Campaign/68913>>

...

May 10 15:13:26 stormy-depths-3143 app[default_worker] INFO I, [2021-05-10T15:13:25.902789 #3]  INFO -- : [ActiveJob] [UniqueCallableJob] [f28fde90-e7d8-43a3-a16f-135f303c71a7] Performed UniqueCallableJob (Job ID: f28fde90-e7d8-43a3-a16f-135f303c71a7) from Sidekiq(default) in 117.39ms 
```

</details>

<details>
  <summary>Sidekiq initializer</summary>

```rb
require 'sidekiq'

redis_config = {
  network_timeout: Integer(ENV.fetch('SIDEKIQ_NETWORK_TIMEOUT')),
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
}

class CarrierWaveCleanupMiddleware
  def call(*)
    CarrierWave.clean_cached_files!(3.hours)
    yield
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add CarrierWaveCleanupMiddleware
  end
  config.redis = redis_config
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::HoneycombMiddleware
  end
  config.redis = redis_config
  config.reliable_scheduler!
  ActiveRecord::Base.establish_connection
end

Sidekiq::Enterprise.unique! unless Rails.env.test?
```
</details>

<details>
  <summary>sidekiq.yml</summary>

```yml
:concurrency: 26
```

</details>

Other things of note:

* In this case it happened on a job with `unique_for`, but we've also seen it on jobs without uniqueness settings.
* We recently switched Redis providers from Redis Labs to Heroku Redis. One difference is that Heroku Redis seems to be much faster, so I was wondering if it was surfacing some sort of race condition. These errors started happening after that switch.
* There are frequently jobs of both types being enqueued, often in rapid succession.
* We're running our background jobs on Heroku Performance-L dynos.

**Comment by mockdeep** [comment]
@mperham I'm not entirely sure what you mean by "job dispatch layer". We don't really add any logic for dispatching jobs. We've got one primary generic job class `CallableJob`, which instantiates the class its given and calls it with the given parameters.

As for why, it's because we often want to background work, and it doesn't make a whole lot of sense to have to add a new job class every time we want to move something to the background. It's especially painful due to the fact that we do zero-downtime deploys, which would require coordinating deploys to add a new job class and then start using it. We've been using this strategy for several years without any incident until recently.

It doesn't make a whole lot of sense to use `Sidekiq::Worker` directly since that adds its own complexity. The abstraction that `ActiveJob` provides removes a lot of boilerplate logic that we would otherwise end up trying to come up with our own abstraction for.

**Comment by mockdeep** [comment]
@mperham we're still seeing this issue a couple of times a week.

**Comment by mperham** [comment]
But no one else is and you’ve already shown that you are providing your own job class look up. Therefore I have to assume the bug is local to your application and environment.

**Comment by mockdeep** [comment]
We're not providing our own job class lookup. We're using a single job class and then looking up a plain ruby class to pass the arguments to.

**Comment by mperham** [comment]
I've looked at the code you supplied. I don't see any issues but no one else is complaining of anything even remotely like this so what do you expect me to do?

**Comment by mockdeep** [comment]
I honestly don't know, but for this sort of issue you seem like the person best equipped to help debug it. The only thing that coincides with the error is upgrading to a faster redis provider, which leads me to the idea of a race condition in Sidekiq, or ActiveJob, or maybe something deeper, like `#constantize`. I'd be happy to jump on a call and walk you through our setup in more detail if you'd be up for it. Maybe that would jog something loose for one of us.

**Comment by mperham** [comment]
You are welcome to stop by Happy Hour next week, 6/11. https://sidekiq.org/support.html

**Comment by mockdeep** [comment]
We usually have team meetings on Fridays, but I'll see if I can make that happen.
