### ISSUE TITLE
Batches, failed jobs and retries not showing

### ISSUE THREAD

**Issue by honzasterba** [mperham/sidekiq#4900]
Ruby version: 2.7.2
Rails version: 6.1.3.1
Sidekiq version: 6.2.1 (PRO 5.2.2)
Sidekiq / Pro / Enterprise version(s): PRO

Initializer

```
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end

schedule_file = "config/schedule.yml"
if File.exist?(schedule_file) && Sidekiq.server? && Rails.env.production?
  Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)
end

Sidekiq.logger = Rails.logger if Rails.env.test?
```

I am having a hard time with Batches and failed jobs. Attached is a screenshot of one such batch after it “finished”.

<img width="1216" alt="Screenshot 2021-05-12 at 18 19 54" src="https://user-images.githubusercontent.com/22641/118011872-c479bc00-b350-11eb-8030-5bb191e293a2.png">

The on_complete callback has not been called yet, I guess because there are still pending jobs to be finished.

But in UI there is nowhere to be found what jobs are still pending. Is this intentional? Should I write my own UI which will let me see what jobs are pending for a batch? I am pretty sure these will succeed if retried now but now way to trigger the retry since there are 0 retries in the queue.

**Comment by mperham** [comment]
What version of Pro?

**Comment by honzasterba** [comment]
added to issue description - 5.2.2

**Comment by mperham** [comment]
Can you run “redis-cli info” against your production Redis instance and put the output here?

**Comment by honzasterba** [comment]
```
# Server
redis_version:6.2.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d361d564ea80f534
redis_mode:standalone
os:Linux 5.4.0-1045-aws x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:1
process_supervised:no
run_id:d7d7afe3a60b178a44e5cb0d69d727b5092caa02
tcp_port:10000
server_time_usec:1620845340927172
uptime_in_seconds:165940
uptime_in_days:1
hz:10
configured_hz:10
lru_clock:10232604
executable:/data/redis-server
config_file:/data/./redis.conf
io_threads_active:0

# Clients
connected_clients:13
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:136
client_recent_max_output_buffer:0
blocked_clients:2
tracking_clients:0
clients_in_timeout_table:2

# Memory
used_memory:7416272
used_memory_human:7.07M
used_memory_rss:12128256
used_memory_rss_human:11.57M
used_memory_peak:42118064
used_memory_peak_human:40.17M
used_memory_peak_perc:17.61%
used_memory_overhead:1345600
used_memory_startup:809880
used_memory_dataset:6070672
used_memory_dataset_perc:91.89%
allocator_allocated:7438664
allocator_active:8343552
allocator_resident:11800576
total_system_memory:33016700928
total_system_memory_human:30.75G
used_memory_lua:41984
used_memory_lua_human:41.00K
used_memory_scripts:4352
used_memory_scripts_human:4.25K
number_of_cached_scripts:4
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.12
allocator_frag_bytes:904888
allocator_rss_ratio:1.41
allocator_rss_bytes:3457024
rss_overhead_ratio:1.03
rss_overhead_bytes:327680
mem_fragmentation_ratio:1.66
mem_fragmentation_bytes:4816688
mem_not_counted_for_evict:2554
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:246264
mem_aof_buffer:2560
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:2957253
rdb_bgsave_in_progress:0
rdb_last_save_time:1620679400
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:1359872
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:8877162
aof_base_size:4927567
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:38876
total_commands_processed:6857417
instantaneous_ops_per_sec:7
total_net_input_bytes:693664184
total_net_output_bytes:169673923
instantaneous_input_kbps:0.87
instantaneous_output_kbps:0.04
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:110
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:7873
evicted_keys:0
keyspace_hits:559126
keyspace_misses:1296176
pubsub_channels:0
pubsub_patterns:1
latest_fork_usec:475
total_forks:6
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:2855738
total_writes_processed:2812857
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:328487ee5fee2a891489ff664895ae98ec552a16
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:320.764240
used_cpu_user:244.593013
used_cpu_sys_children:0.180377
used_cpu_user_children:0.636180
used_cpu_sys_main_thread:308.281367
used_cpu_user_main_thread:240.204608

# Modules

# Errorstats

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=5333,expires=111,avg_ttl=60054543258
```

**Comment by mperham** [comment]
Thanks, your Redis looks great. Your versions are current. I’m not sure what the problem is. When a batch has less than 10 pending jobs, it will display the set of JIDs that are still pending. Your example has exactly 10 still pending so it doesn’t show. :-(

It is possible the 10 jobs are stuck in a private queue and super_fetch will rescue them after some time but there is no visibility into those private queues today. I think Sidekiq Pro 6.0 should add a tab to inspect those queues. Do you happen to know if your Sidekiq processes are crashing at all?

**Comment by honzasterba** [comment]
My sidekiq process are never crashing, but we are deploying quite often so the processes get killed and new ones started, AFAIK the processes always finish the jobs started since the jobs are pretty short.

Is there a piece of code I could run to see if your theory is correct? I have left the system in the state described above and I suspect it will stay like this for a while.

**Comment by honzasterba** [comment]
correction: I can see in the logs a bunch of `SuperFetch recovered orphan job` so maybe the jobs are not finishing and are actually being picked up by the newly deployed instance.

**Comment by honzasterba** [comment]
correction 2: I have checked again and the batch is now finished and the on_complete hook has been called 

this was probabyl triggered by another deploy, I can see 10+ orphan jobs being recovered

**Comment by mperham** [comment]
It's possible your shutdown timeout is not configured correctly and something is killing your Sidekiq processes during deploy. If configured correctly, deploys should not orphan jobs.

**Comment by honzasterba** [comment]
yes, this this looks like the explanation

might I suggest improving the documentation for the shutdown timeout options. It is nowhere to be found on the https://github.com/mperham/sidekiq/wiki/Advanced-Options page, the only place I found is a mention on the https://github.com/mperham/sidekiq/wiki/Signals page which does pretty good job of explaining what -t does, but its pretty well hidden.

**Comment by mperham** [comment]
The first paragraph of the Deployment page talks about safe shutdown and the `-t` parameter. I don't know how to make it more obvious than that. I did add a note at the very end of the Batches page.

**Comment by honzasterba** [comment]
Thanks for adding the note, it is helpful. I think it would be even more helpful to have all config options / CLI args on one page for quick reference with links to pages with more details (like linking from Advanced options to Deployment).
Basically like a man page for the sidekiq command is what I am missing.
