### ISSUE TITLE
Doesn't work with rails_semantic_logger gem

### ISSUE THREAD

**Issue by norioumata** [mperham/sidekiq#4903]
Can't see **Sidekiq** logs when use rails_semantic_logger together. Just seeing this.

![image](https://user-images.githubusercontent.com/49550016/118320337-18f47700-b4ca-11eb-9d9a-e2698f79c02d.png)

**Comment by mperham** [comment]
Is this a Sidekiq issue?

**Comment by norioumata** [comment]
Sorry No. Closing now.
