### ISSUE TITLE
Recursive Batch Jobs

### ISSUE THREAD

**Issue by jolim** [mperham/sidekiq#4905]
I have two parent jobs (Job A, Job B) that spawn other jobs (Job Alpha, Job Beta). 

I would like to create a batch with Job A and Job B and run them in parallel in the background. I would consider Job A finished when all of its Job Alpha children are finished, and all of Job B finished when all of its Job Beta children are finished. When all of Alpha and Beta are finished, I would invoke the success callback.

My problem is that the parent jobs return as completed when they finish their spawning, regardless of the state of the Alphas and Betas.

How would I get the batch to recognize the completion of Jobs Alpha and Beta?

**Comment by mperham** [comment]
You want two Batches which work in parallel. Jobs A & B will reopen their batch to add the necessary jobs.

```ruby
parent = Sidekiq::Batch.new
parent.on(:success, "MyCallbacks#all_done", "workflow specific data" => "can go here")
parent.jobs do
  a = Sidekiq::Batch.new
  a.on(:complete, "MyCallbacks#alphas_done", ...)
  a.jobs do
    JobA.perform_async
  end
  b = Sidekiq::Batch.new
  b.on(:complete, "MyCallbacks#betas_done", ...)
  b.jobs do
    JobB.perform_async
  end
end

class JobA
  include Sidekiq::Worker
  def perform
    batch.jobs do # we reopen the batch here and add more jobs
      JobAlpha.perform_async
    end
  end
end

class JobB
  include Sidekiq::Worker
  def perform
    batch.jobs do # we reopen the batch here and add more jobs
      JobBeta.perform_async
    end
  end
end
```

**Comment by jolim** [comment]
Thanks. Do we need to pass the batch in to the JobBeta for this example? 

```
  a.jobs do
    JobA.perform_async(batch: a)
  end
```

Or does `Sidekiq::Worker` automatically identify the parent's batch via a reserved word `batch`?

**Comment by mperham** [comment]
It's automatic.
