### ISSUE TITLE
The best way to pause a Sidekiq job

### ISSUE THREAD

**Issue by troessner** [mperham/sidekiq#491]
Hey Mike,

first of all apologies for using the "issues" section for a question - as a compensation I promise to transform the answers into a wiki article..:)

The title says it all: What would be the best strategy to pause a Sidekiq job?

What I want to do is basically:

``` Ruby
Foo.bars.each do |bar|
  bar.do_stuff
  sleep 5
end
```

I assume using `sleep` here is _not_ the best way to do this - what strategy would you use?

**Comment by shartep** [comment]
I have additional question, if job thread blocks when we use `sleep`, or maybe there are can be some workaround, because in my case it is not very easy solution to split job on several jobs and schedule them one by one

**Comment by amyin** [comment]
I also want to use sleep for simplicity for an exchange rate refresher. I want to spread out the requests I send by putting a 3s sleep between each of the 16 requests to an external service to reduce throttling. Is there any downside to doing so? It just feels like unnecessary extra overhead to spin up 16 new jobs that's all.
