### ISSUE TITLE
Need a social media preview image

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4910]
Per GitHub:

```
Social preview
Upload an image to customize your repository’s social media preview.

Images should be at least 640×320px (1280×640px for best display)
```

Template here: 
![repository-open-graph-template](https://user-images.githubusercontent.com/2911/119726356-e29dec80-be25-11eb-960f-5930117b9af8.png)

**Comment by mperham** [comment]
I'm terrible at anything image-related. Designer help very appreciated.

**Comment by mperham** [comment]
I have placed a bunch of assets here which may be helpful.

https://sidekiq.org/about.html

**Comment by mabdelfattah** [comment]
![sidekiq](https://user-images.githubusercontent.com/721987/127684604-b4ccb25b-c95c-4d4d-b3f6-4bf1c3c12c7e.png)

**Comment by mabdelfattah** [comment]
![sidekiq_2](https://user-images.githubusercontent.com/721987/127684763-d7c82629-4978-47c7-8ece-a92900d580df.png)

**Comment by mperham** [comment]
Thank you, those look wonderful. I've updated the repo so future links should show your image.
