### ISSUE TITLE
Sidekiq WebUI "Forbidden" issue

### ISSUE THREAD

**Issue by aliahmed922** [mperham/sidekiq#4913]
Ruby version: 2.6.7
Rails version: 6.0.3
Sidekiq version: 5.2.9

The issue with seeing the `Forbidden` error on any operation performed over Sidekiq Web UI was already got [closed](https://github.com/mperham/sidekiq/issues/2560#) but I'm still not able to figure the problem. Even tho I've made every configuration as per the suggestions in the wiki and comments the issue never goes away for me in my production environment specifically. 

This is what I have added in the top of my `routes.rb`:

```ruby
require 'sidekiq/web'

Sidekiq::Web.set :session_secret, Rails.application.credentials.secret_key_base
Sidekiq::Web.use ActionDispatch::Cookies
Sidekiq::Web.use Rails.application.config.session_store, Rails.application.config.session_options
```

And this is my `nginx.conf`:

```
upstream app {
  server unix:///var/run/puma/app.sock;
}

log_format healthd '$msec"$uri"'
'$status"$request_time"$upstream_response_time"'
'$http_x_forwarded_for';

server {
  listen 80;
  server_name localhost; # need to listen to localhost for worker tier

  if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})T(\d{2})") {
    set $year $1;
    set $month $2;
    set $day $3;
    set $hour $4;
  }

  access_log  /var/log/nginx/access.log  main;
  access_log /var/log/nginx/healthd/application.log.$year-$month-$day-$hour healthd;

  location / {
    proxy_pass http://app; # match the name of upstream directive which is defined above
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /assets {
    alias /var/app/current/public/assets;
    gzip_static on;
    gzip on;
    expires max;
    add_header Cache-Control public;
  }

  location /public {
    alias /var/app/current/public;
    gzip_static on;
    gzip on;
    expires max;
    add_header Cache-Control public;
  }
}
```

This my Rails API Only application and I deployed it through elastic beanstalk. It's been more than a week I'm hitting my head to find out why "Forbidden" is keep showing on any operations I perform on Sidekiq Web UI. Can anyone please help me in this.

**Comment by mperham** [comment]
Upgrade. The wiki only covers the latest version. Sidekiq 6.2 made some major changes to improve session reliability.

**Comment by aliahmed922** [comment]
@mperham I just upgraded my sidekiq to 6.2 and it seems like the "Forbidden" error is still there. Is there something wrong with my nginx.conf you think?

**Comment by mperham** [comment]
I don’t know. Can you reproduce the error without using nginx?
