### ISSUE TITLE
Sidekiq Pro Batches Ran out of Memory

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#4914]
Our redis instance just ran out of memory, and we had to upgrade. (From 250 MB)

Looking into our redis keyspace, we can see that it is full of batches, some successfully finished, some failed.

```
> KEYS *
....
12329) b-77ttk4VvK6xDUg-failinfo
12330) b-wWwQzkTsOF75fw-complete
12331) b-3WHtYi2J8ULSHQ-jids
12332) b-1vzT3K7EOV1W6Q-jids
12333) b-RE9Xh5n5BvFh4A-notify
12334) b-GRxftHJVuWdjCQ-complete
12335) b-cemnPvIy07MghA
12336) b-9K_wXzFi4PR-JQ-failinfo
12337) b-gncZM_bdDjRqHw-notify
12338) b-_xQQwTR05Ds60w
12339) b-pp0o407nf8tEnQ-notify
12340) b-DYLlm5uYwY6sZQ-failinfo
12341) b-78Tyrh5n1DDIdA-notify
12342) b-Yn02juHbWHbqaQ
12343) b-EBArzZ8-65bzhw-notify
12344) b-Sc4As__P1hXGJA-notify
12345) b-b_aN0uS7lt_kUQ-died
12346) b-MfoA3Zlu6F1yHQ-jids
12347) b-VT3KHjYynDmmeg-notify
12348) b-BBLjrrzFYskIjQ
12349) b-NCWjuEDEY8QDZA
12350) b-xttaApXobJIrfw
12351) b-X5EE6AzBMikZew
12352) b-wjwt5ka7S1EZ6w
12353) b-tyLxHolLDh-VIA-failinfo
```

In the web UI, we have 84 pages (!) of batches.

Whats the suggested way for us to make sure that we don't run out of memory again?

**Comment by mollerhoj** [comment]
Looking into the code, I believe the jobs linger because they contain jobs that are not retried (`retry: false`).
The default expiry of batches with jobs is 30 days. I guess a solution would be to set this to 1 day instead. Does this mean we have to override the EXPIRY constant?

**Comment by mperham** [comment]
That is one solution but not the desired solution.

Batches assume that jobs to eventually succeed. Use retries. If a job dies, the batch dies.

**Comment by mperham** [comment]
Did you see the note in 5.2.1?

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md#521
