### ISSUE TITLE
Sidekiq starting successfully, but systemd restarts every 1 minute anyway

### ISSUE THREAD

**Issue by culov** [mperham/sidekiq#4915]
Rails: 6.0.3
Sidekiq: 6.1.2
Ruby 2.7.2
Running on AWS Amazon Linux 2

I'm running a fairly simply Sidekiq configuration on production, and using the boilerplate systemd/sidekiq.service file from the examples directory.

I noticed that my workers can not run long jobs because they are killed every 1 minute or so. I was able to track down what's happening, and it appears that systemd is restarting sidekiq, even though it is successfully started. It appears that it never receives the message that the service started successfully, so systemd is killing the process.

Here are the logs:

```systemd: sidekiq.service start operation timed out. Terminating.
sidekiq: 2021-06-01T23:30:56.510Z pid=24939 tid=gir INFO: Shutting down
sidekiq: 2021-06-01T23:30:56.511Z pid=24939 tid=4jxb INFO: Scheduler exiting...
systemd: Failed to start sidekiq.
systemd: Unit sidekiq.service entered failed state.
systemd: sidekiq.service failed.
sidekiq: 2021-06-01T23:30:56.513Z pid=24939 tid=gir INFO: Terminating quiet workers
sidekiq: 2021-06-01T23:30:56.513Z pid=24939 tid=4jvn INFO: Scheduler exiting...
sidekiq: 2021-06-01T23:30:57.015Z pid=24939 tid=gir INFO: Pausing to allow workers to finish...
sidekiq: 2021-06-01T23:30:57.516Z pid=24939 tid=gir INFO: Bye!
systemd: sidekiq.service holdoff time over, scheduling restart.
systemd: Starting sidekiq...
sidekiq: 2021-06-01T23:30:58.991Z pid=32046 tid=fs6 INFO: Enabling systemd notification integration
sidekiq: 2021-06-01T23:31:04.475Z pid=32046 tid=fs6 INFO: Booting Sidekiq 6.1.2 with redis options {:url=>"redis://******"}
sidekiq: 2021-06-01T23:31:08.869Z pid=32046 tid=fs6 INFO: Running in ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
sidekiq: 2021-06-01T23:31:08.870Z pid=32046 tid=fs6 INFO: See LICENSE and the LGPL-3.0 for licensing details.
systemd: sidekiq.service: Got notification message from PID 32046, but reception only permitted for main PID 31981

```

Following these messages, the sidekiq worker will successfully perform the jobs from the queue for about 1 minute before it's restarted again. This cycle continues forever. 

I've tried modifying the sidekiq.service file a number of different ways, but nothing seems to do the trick. Any ideas on how I can ensure that systemd accurately knows when a job succeeds/fails to start?

Here is my current systemd/sidekiq.service file:

```
#
# This file tells systemd how to run Sidekiq as a 24/7 long-running daemon.
#
# Customize this file based on your bundler location, app directory, etc.
# Customize and copy this into /usr/lib/systemd/system (CentOS) or /lib/systemd/system (Ubuntu).
# Then run:
#   - systemctl enable sidekiq
#   - systemctl {start,stop,restart} sidekiq
#
# This file corresponds to a single Sidekiq process.  Add multiple copies
# to run multiple processes (sidekiq-1, sidekiq-2, etc).
#
# Use `journalctl -u sidekiq -rn 100` to view the last 100 lines of log output.
#
[Unit]
Description=sidekiq
# start us only once the network and logging subsystems are available,
# consider adding redis-server.service if Redis is local and systemd-managed.
After=syslog.target network.target

# See these pages for lots of options:
#
#   https://www.freedesktop.org/software/systemd/man/systemd.service.html
#   https://www.freedesktop.org/software/systemd/man/systemd.exec.html
#
# THOSE PAGES ARE CRITICAL FOR ANY LINUX DEVOPS WORK; read them multiple
# times! systemd is a critical tool for all developers to know and understand.
#
[Service]
#
#      !!!!  !!!!  !!!!
#

# As of v6.0.6, Sidekiq automatically supports systemd's `Type=notify` and watchdog service
# monitoring. If you are using an earlier version of Sidekiq, change this to `Type=simple`
# and remove the `WatchdogSec` line.
#
#      !!!!  !!!!  !!!!
#
Type=notify
# If your Sidekiq process locks up, systemd's watchdog will restart it within seconds.
WatchdogSec=10

TimeoutSec=900
TimeoutStartSec=900

EnvironmentFile=/opt/elasticbeanstalk/deployment/custom_env_var
WorkingDirectory=/var/app/current
# If you use rbenv:
# ExecStart=/bin/bash -lc 'exec /home/deploy/.rbenv/shims/bundle exec sidekiq -e production'
# If you use the system's ruby:
# ExecStart=/usr/local/bin/bundle exec sidekiq -e production
# If you use rvm in production without gemset and your ruby version is 2.6.5
# ExecStart=/home/deploy/.rvm/gems/ruby-2.6.5/wrappers/bundle exec sidekiq -e production
# If you use rvm in production with gemset and your ruby version is 2.6.5
# ExecStart=/home/deploy/.rvm/gems/ruby-2.6.5@gemset-name/wrappers/bundle exec sidekiq -e production
# If you use rvm in production with gemset and ruby version/gemset is specified in .ruby-version,
# .ruby-gemsetor or .rvmrc file in the working directory
ExecStart=/var/app/current/bundle exec sidekiq -e production

# Use `systemctl kill -s TSTP sidekiq` to quiet the Sidekiq process

# !!! Change this to your deploy user account !!!
User=ec2-user
Group=ec2-user
UMask=0002

# Greatly reduce Ruby memory fragmentation and heap usage
# https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
Environment=MALLOC_ARENA_MAX=2

# if we crash, restart
RestartSec=1
Restart=on-failure

# output goes to /var/log/syslog (Ubuntu) or /var/log/messages (CentOS)
StandardOutput=syslog
StandardError=syslog

# This will default to "bundler" if we don't specify it
SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target
```

**Comment by mperham** [comment]
I don’t see anything that would cause a minutely restart.

**Comment by culov** [comment]
I've continue troubleshooting this the last few weeks, and still don't have an answer, but I believe its now a timeout issue due to this line:

```Jun 28 19:48:20 systemd[1]: sidekiq.service start operation timed out. Terminating.```


To summarize, the process begins successfully (successfully in that it starts up and begins to process jobs successfully). But after about a minute, we arrive at this series of messages:

```
.....processing jobs successfully......
Jun 28 19:48:20 systemd[1]: sidekiq.service start operation timed out. Terminating.
Jun 28 19:48:20 sidekiq[21937]: 2021-06-28T19:48:20.039Z pid=22002 tid=ke2 INFO: Shutting down
Jun 28 19:48:20 sidekiq[21937]: 2021-06-28T19:48:20.039Z pid=22002 tid=4k6i INFO: Scheduler exiting...
Jun 28 19:48:20 systemd[1]: Failed to start sidekiq.
Jun 28 19:48:20 systemd[1]: Unit sidekiq.service entered failed state.
Jun 28 19:48:20 sidekiq[21937]: 2021-06-28T19:48:20.040Z pid=22002 tid=ke2 INFO: Terminating quiet workers
Jun 28 19:48:20 sidekiq[21937]: 2021-06-28T19:48:20.040Z pid=22002 tid=4k66 INFO: Scheduler exiting...
Jun 28 19:48:20 systemd[1]: sidekiq.service failed.
Jun 28 19:48:20 sidekiq[21937]: 2021-06-28T19:48:20.541Z pid=22002 tid=ke2 INFO: Bye!
Jun 28 19:48:21 systemd[1]: sidekiq.service holdoff time over, scheduling restart.
Jun 28 19:48:21 systemd[1]: Starting sidekiq...
.......processing jobs successfully......
```

And then it repeats this cycle again and again. Starting up, beginning to process jobs successfully for about a minute, before it shuts down again.

I believe I found a good hint by running the command `sudo systemctl show sidekiq | grep ^Timeout`, which prints: 
```TimeoutStartUSec=1min 30s TimeoutStopUSec=1min 30s```

The 1min30s timeout matches with the minutely restart behavior, but the question is why is it restarting and how to fix it?

The service is starting successfully as far as I can tell, so why is it timing out? My best guess as to why is that the successful notification message is being delivered to the wrong PID (```sidekiq.service: Got notification message from PID 17740, but reception only permitted for main PID 17619```).

I was able to slow down the restarts by setting `TimeoutSec=900`, but this does seem like a band-aid. Is there a better way to ensure the process starts up successfully?

**Comment by mperham** [comment]
Systemd thinks it is starting bash but Sidekiq is the process it’s managing. Remove the extra bash garbage from your ExecStart.

**Comment by culov** [comment]
> Systemd thinks it is starting bash but Sidekiq is the process it’s managing. Remove the extra bash garbage from your ExecStart.

Sorry, i should have mentioned that I updated my sidekiq.service file to get rid of that, so now it reads `ExecStart=/var/app/current/bundle exec sidekiq -e production`. So this is the issue I'm seeing even without the extra bash garbage. Edited my OP sidekiq.service job to reflect the latest.

**Comment by mperham** [comment]
It’s still starting bash. You have to tell systemd to reload the service file.

**Comment by markroxor** [comment]
```
Jun 09 03:58:29 ip-172-1-4-1 sudo[11664]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu/dir ; USER=root ; COMMAND=/usr/sbin/service sidekiq start
Jun 09 03:58:29 ip-172-1-4-1 sudo[11664]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Jun 09 03:58:30 ip-172-1-4-1 systemd[1]: Starting sidekiq...
-- Subject: Unit sidekiq.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sidekiq.service has begun starting up.

Jun 09 03:58:33 ip-172-1-4-1 sidekiq[11694]: 2022-06-09T03:58:33.273Z 11694 TID-20y INFO: Booting Sidekiq 5.2.9 with redis options {:url=>"redis://stage.us1.cache.amazonaws.com:6379/0", :size=>1, :network_timeout=>5, :id=>"Sidekiq-server-PID-11694"}
Jun 09 03:58:33 ip-172-1-4-1 sidekiq[11694]: 2022-06-09T03:58:33.555Z 11694 TID-20y INFO: Running in ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
Jun 09 03:58:33 ip-172-1-4-1 sidekiq[11694]: 2022-06-09T03:58:33.555Z 11694 TID-20y INFO: See LICENSE and the LGPL-3.0 for licensing details.
Jun 09 03:58:33 ip-172-1-4-1 sidekiq[11694]: 2022-06-09T03:58:33.556Z 11694 TID-20y INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
Jun 09 03:58:33 ip-172-1-4-1 sidekiq[11694]: 2022-06-09T03:58:33.560Z 11694 TID-20y INFO: Starting processing, hit Ctrl-C to stop
```
@mperham in my case even after a successfully initialisation of the service sidekiq gets forever stuck at `sudo service sidekiq start` 

my system service file is just like OP's updated service file (after removing bash).

**Comment by vignesh-svmx** [comment]
when i run chef-client on homebase-worker node the sidekiq is restarting automatically even there is no changes in the configuration

root@ip-10-11-2-184:~# systemctl status supervisor
● supervisor.service - Supervisor process control system for UNIX
   Loaded: loaded (/lib/systemd/system/supervisor.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2024-03-12 07:24:24 UTC; 1 day 3h ago
     Docs: http://supervisord.org
 Main PID: 21550 (supervisord)
    Tasks: 76 (limit: 4612)
   CGroup: /system.slice/supervisor.service
           ├─13045 /srv/homebase/releases/57ed367f349ab6fbc41d407730cb28d9da6409d3/vendor/bundle/ruby/3.1.0/bin/shoryuken -C /etc/sqs/homebase-sqs-dev-
           ├─13046 sidekiq 5.2.10 homebase [0 of 10 busy]
           ├─13047 /srv/homebase/releases/57ed367f349ab6fbc41d407730cb28d9da6409d3/vendor/bundle/ruby/3.1.0/bin/shoryuken -C /etc/sqs/homebase-sqs-dev-
           ├─13048 sidekiq 5.2.10 homebase [0 of 15 busy]
           ├─13049 sidekiq 5.2.10 homebase [0 of 5 busy]
           └─21550 /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf

Mar 13 10:56:36 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:36,187 INFO spawned: 'sqs-homebase-sqs-dev-ses-inbound-email-proc' with pid 13045
Mar 13 10:56:36 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:36,191 INFO spawned: 'sidekiq-homebase-default-0' with pid 13046
Mar 13 10:56:36 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:36,194 INFO spawned: 'sqs-homebase-sqs-dev-ses-outbound-notifications-proc' with pi
Mar 13 10:56:36 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:36,201 INFO spawned: 'sidekiq-homebase-high-0' with pid 13048
Mar 13 10:56:36 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:36,230 INFO spawned: 'sidekiq-homebase-low-0' with pid 13049
Mar 13 10:56:37 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:37,806 INFO success: sqs-homebase-sqs-dev-ses-inbound-email-proc entered RUNNING st
Mar 13 10:56:37 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:37,807 INFO success: sidekiq-homebase-default-0 entered RUNNING state, process has 
Mar 13 10:56:37 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:37,807 INFO success: sqs-homebase-sqs-dev-ses-outbound-notifications-proc entered R
Mar 13 10:56:37 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:37,807 INFO success: sidekiq-homebase-high-0 entered RUNNING state, process has sta
Mar 13 10:56:37 ip-10-11-2-184 supervisord[21550]: 2024-03-13 10:56:37,808 INFO success: sidekiq-homebase-low-0 entered RUNNING state, process has stay
