### ISSUE TITLE
Recommended Heroku Configurations

### ISSUE THREAD

**Issue by chai2** [mperham/sidekiq#4916]
We are using Sidekiq to send bulk emails(5k) every hour(only 3-4 hours during the day). We are using Heroku with Standard 2x dynos with autoscaling enabled(gets upto 3 dynos) with Heroku Redis add-on Premium-1. About 2000 emails are being delayed by 10-15 minutes, but eventually, get delivered after several retries. 

Any advice on what should be done to reduce the delay? 

Ruby version: 2.7.2
Rails version: 6.1.3.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.1.0

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - high
  - default
  - mailers

**Comment by mperham** [comment]
The delay is due to retry. What error is causing the retry?

**Comment by chai2** [comment]
This is the error that causes the retry. 

```
ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.042 seconds); all pooled connections were in use. 
```

FWIW - We started using `sidekiq-status` gem too to track scheduled jobs(and ability to cancel scheduled jobs - if needed). Do you think, that might have anything to do with this error?

**Comment by mperham** [comment]
Make sure you have `pool: 10` in `config/database.yml`.

**Comment by mperham** [comment]
The best performance on Heroku requires Sidekiq Enterprise + Perf-L dynos:

https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#heroku

sidekiq-status has nothing to do with database pool timeouts.

**Comment by chai2** [comment]
Thank you!

**Comment by chai2** [comment]
@mperham - Thanks again for recommending setting the pool size. That resolved the issue.

**Comment by brandoncc** [comment]
Check out this video that I found somewhere in the wiki @chai2  https://www.youtube.com/watch?v=XOfELjqm188 I found it very helpful.

**Comment by chai2** [comment]
Thanks @brandoncc
