### ISSUE TITLE
Error when run job from two Rails apps

### ISSUE THREAD

**Issue by buithehien1991** [mperham/sidekiq#4920]
Dear all,

I have two rails apps (App1 and App2).
At first I setup App1 and run sidekiq service (sidekiq.service with WorkingDirectory=/path/to/App1. Job from App1 working correctly.

And now we have App2. And I don't know setting new sidekiq service for App2. I think we can use from App1 but WorkingDirectory still is App1.

I tried run from background job from App2 and have problem

`NameError: uninitialized constant FeedUploadJob`

In App2. I using SidekiqCron with command
`Sidekiq::Cron::Job.create(name: "Upload", cron: "* * * * *", class: 'FeedUploadJob')`

On development mode, it also work normally but error in production mode. 
I guest sidekiq on production unknown where is 'FeedUploadJob' ?

Do you know why happen and have solution for it?

Thank you so much!!

**Comment by mperham** [comment]
Separate apps need separate Redis databases. Apps cannot share the same key space within Redis.

**Comment by buithehien1991** [comment]
Dear @mperham 
Thank you so much for your answer. 

I separate databases using redis-namespace and setting in sidekiq.rb

But when I run jobs. It was pushed to Queue but not run 

![image](https://user-images.githubusercontent.com/577666/121459873-3be54e80-c9d6-11eb-9a19-83e46f74f536.png)

Sidekiq from App1 still run normally.

Could you please tell me how to run them?

Thank you so much and best regards,
Bui The Hien

**Comment by mperham** [comment]
Take a look at the Sharding wiki page. I assume you are trying to have App1 enqueue a job for App2 to process.

**Comment by buithehien1991** [comment]
@mperham 
That's not true. App1 and App2 is independent.

**Comment by mperham** [comment]
Post your initializer.

**Comment by buithehien1991** [comment]
sidekiq.rb
```
require 'sidekiq'
Sidekiq.configure_server do |config|
  config.redis = {
    url: 'redis://127.0.0.1:6379/4',
    namespace: 'ffh'
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: 'redis://127.0.0.1:6379/4',
    namespace: 'ffh'
  }
end
```

sidekiq.yml
```
---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - ffh_production_default
  - low
```

@mperham 
I wrote sidekiq.yml but still did not call it anywhere. (Actually I don't how to pass it). Thank you so much

**Comment by mperham** [comment]
And the initializer for App2?

**Comment by buithehien1991** [comment]
Above is belong to App2.

In App1. I keep old setting, didn't change anything. It mean config without namespace for App1
I don't have initializer (sidekiq.rb)

Only have sidekiq.yml
```
---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - tda_prod_default
  - low
```

**Comment by mperham** [comment]
All of that looks right to me. I can’t explain.

**Comment by buithehien1991** [comment]
@mperham 
Here is my sidekiq.service
```
WorkingDirectory=/tda/git/dethimoi
ExecStart=/home/ubuntu/.rvm/gems/ruby-2.5.1/wrappers/bundle exec sidekiq -e production
```

I think sidekiq is running from `/tda/git/dethimoi`

Therefore it can't start queue from App2, is right?

Thanks

**Comment by buithehien1991** [comment]
@mperham 

I edited 

`WorkingDirectory=/path/to/app2`

=> Queue from App2 ran. But queue from App1 was stopped. All jobs pushed to Queues

Can I run both Queues from App1 and App2 at the same time ?
Create another service sidekiq2.service, right?

**Comment by buithehien1991** [comment]
@mperham 

I create multiple service to run it

Thank you so much for your help.
