### ISSUE TITLE
Increasing concurrency seems to increase database connections

### ISSUE THREAD

**Issue by StevenJL** [mperham/sidekiq#4924]
Dear sidekiq community,

I'm using sidekiq 5.1.3 along with a Rails 4.2.11.3 application using postgresql 10 as the database.  The `database.yml` pool settings looks like this:

```
production:
  <<: *default
  pool: 6
```

I was playing around the concurrency settings on sidekiq.  When I increased the concurrency through the command-line flag:

```
bundle exec sidekiq -c <concurrency>
```
I noticed a sudden increase in the number of active database connections.  But I thought increasing concurrency only increases the number of threads in the sidekiq process, which shouldn't increase the number of database connections, as that is capped by the `pool` value in `database.yml`.  Am I correct in this assumption that increasing the concurrency should not increase the number of active database connections?

EDIT: fixed typo `sidekiq.yml` -> `database.yml`

**Comment by mperham** [comment]
I don't know. There are other things than Sidekiq concurrency that can affect pool size so I can't say for sure. Sidekiq concurrency == number of concurrent job execution threads but those threads can do anything, including spawning their own threads.

**Comment by StevenJL** [comment]
Thanks for responding!
