### ISSUE TITLE
Jobs stuck in the development environment (when the code is changed)

### ISSUE THREAD

**Issue by jankeesvw** [mperham/sidekiq#4925]
We are using Sidekiq with Rails, and we are facing an issue where jobs stop processing. 

I've seen this happen when we change the code in one of our jobs. It feels like some kind of dead lock.

If I try to kill Sidekiq after it's stuck, I see this:

```
2021-06-17T06:49:54.846Z pid=66408 tid=ce0 INFO: queueing DataSource::SolarLogJob (solar_log)
^C
2021-06-17T11:00:45.347Z pid=66408 tid=1jm0 INFO: Shutting down
2021-06-17T11:00:45.349Z pid=66408 tid=1jm0 INFO: Terminating quiet workers
```

It just keeps hanging, when I do `ps aux` I see this:

```
➜ ps aux | grep sidekiq

jankeesvw        66408   0.0  0.5  4593724  84828 s006  S+    8:47AM   0:54.44 sidekiq 6.2.1 StekkerWeb [1 of 1 busy] stopping
```

I played with the concurrency in `sidekiq.yml`, and looked at the FAQ and some other wikis.

Anyone tips on how to find the issue?

**Comment by mperham** [comment]
Use the TTIN signal, as noted on the Problems and Troubleshooting page.

**Comment by jankeesvw** [comment]
Thanks for the quick response ✨ 

Do you mean I need to debug using `gdb`? The problem is not that I can't quit it, the problem is that it's stuck.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Signals#ttin
