### ISSUE TITLE
Batches death callbacks are triggered even when jobs have retry disabled

### ISSUE THREAD

**Issue by Draiken** [mperham/sidekiq#4926]
The batches [documentation](https://github.com/mperham/sidekiq/wiki/Batches#callbacks) mentions:

> The :death callback is not fired for every job in the batch that dies, only the first job that dies. If you configure your jobs to disable retries or the death process, it will also skip the :death callback.

However, we tested this and it worked: https://gist.github.com/Erol/e58257ce67d0fa8c795f7b1c33da750c

After reading through the changelog, it seems that #3980 changed this behavior and now even jobs with `retry: false` will trigger the `death` callbacks for batches.

If this is true, the documentation should be updated to reflect that only jobs with `death: false` would not trigger the callback

**Comment by mperham** [comment]
The death callback should fire, no matter how the job is configured. The docs are wrong.

I also noticed that the Batch UI can really be improved for dead batches. I will put some effort into improving the display (highlighting it with a different color, showing the dead JIDs, etc) so I will keep this issue open.
