### ISSUE TITLE
Limiting/unique jobs in enterprise

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4927]
Does the enterprise version have an alternate to https://github.com/brainopia/sidekiq-limit_fetch that is built in?

I have one specific job that doesn't run in a way that is concurrently-idempotent. That probably sounds weird, but what I mean is that it is idempotent if run in sequence, just not when running multiple times in parallel. Because of this, I use limit_fetch to limit this queue to one job at a time. The job accepts an id, and this requirement is per-id. Multiple jobs can run at the same time, just not with the same id. 

I believe there is a unique job aspect to the enterprise version, and I'm wondering if that would be usable as a substitute to fill my requirement. Would the unique job feature disallow running multiple copies of the same job with the same inputs?

Thanks!

**Comment by mperham** [comment]
Use enterprise’s concurrent rate limiter set to 1 to get something more reliable than uniqueness. That should get you similar semantics.

**Comment by brandoncc** [comment]
Thank you for this information.

This seems like it would work for us. I would actually prefer to use uniqueness of the id so that the job doesn't back up if many come in with different ids as their inputs. 

The docs say:

> Each limiter must have a name, consisting only of letters, numbers, hyphens and underscores. name can be static (e.g. "erp") for a global limiter or dynamic (e.g. "stripe-#{userid}") to create multiple context-sensitive limiters.

The concurrent limiters seem to be assigned to constants though, so I'm not sure how to interpolate my id into the limiter name. Can I do this with a concurrent limiter?

```ruby
def perform(project_id)
  limiter = Sidekiq::Limiter.concurrent("my-limiter-#{project_id}", 50, wait_timeout: 5, lock_timeout: 30)
  limiter.within_limit do
    # call ERP
  end
end
```

**Comment by mperham** [comment]
You can use both features in tandem. Yes, you can use a concurrent limiter
simply as a normal variable so it can be dynamically named.

**Comment by brandoncc** [comment]
Thank you for all of your help, I think this would work out perfectly for us!

**Comment by brandoncc** [comment]
Thank you again for all of your help Mike, we should be signing up for enterprise today 👍
