### ISSUE TITLE
queue in sidekiq_options is not read

### ISSUE THREAD

**Issue by getachew** [mperham/sidekiq#4928]
Ruby version:2.5.9
Sidekiq: 5.2.9 (also tried with 6.1.2)

I was trying to start run a sidekiq worker in a `por` file and assign that worker to a specific queue via the `sidekiq_options`

```ruby
class Worker
  include Sidekiq::Worker
  sidekiq_options retry: false, queue: "my-queue"

  def perform
    puts "...working"
  end
end 
```
I start the worker using `bundle exec sidekiq -r ./por.rb` 

but the process start without ever reconfiguring the queue from sidekiq_options.... it defaults to the `default` queue with the following verbose log. 
```
2021-06-18T03:17:54.027Z 81264 TID-ouh15s28w DEBUG: {:queues=>["default"], :labels=>[], :concurrency=>10, :require=>"./por.rb",..."}

```

What am I doing wrong? If I pass the queue name from the terminal using `-q` or configure it via config yaml, it works. But I was looking to do it purely programmatically.

**Comment by mperham** [comment]
The queues to process must be specified in sidekiq.yml or on the command line with `-q`.

**Comment by getachew** [comment]
thanks Mike. closing
