### ISSUE TITLE
"Keep last" option for unique jobs

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4929]
Our application has jobs that look like this:

```
class SmallJob
  def perform(task)
    project = task_from(project)
    # do stuff
    ProjectJob.perform_async(project.id)
  end
end
```

A bunch of small jobs for a single project can be enqueued, and they will all enqueue `ProjectJob` after they do their work. We really only need to ensure that `ProjectJob` runs once, but it has to run after all of the `SmallJob` jobs. Is there a "keep last" option for the uniqueness feature of Enterprise which will allow newly-enqueued jobs to replace any duplicates that already exist in the queue? I'd like to drop any existing and add a new item to the end of the queue each time a duplicate of `ProjectJob` is added to the queue (duplicate based on the arguments).

**Comment by mperham** [comment]
You can use a batch to create a set of jobs to run some code after they are all finished but it doesn’t sound like that applies here.  You can repeatedly schedule a unique job to run in 10 minutes, maybe that would work better for this use case?

**Comment by mperham** [comment]
There’s no way to implement this safely though. “After some time, run ProjectJob” is just a heuristic.

**Comment by brandoncc** [comment]
> You can repeatedly schedule a unique job to run in 10 minutes, maybe that would work better for this use case?

Are scheduled jobs deduped automatically? If not, wouldn't I end up with a bunch of `ProjectJob` scheduled just the same as if I just do `ProjectJob.perform_async` a bunch of times?

> There’s no way to implement this safely though.

Can you clarify what you mean by "safely", and how it will be unsafe?

---

I wonder if I could implement a module that I can include which checks for existing duplicates in the queue, then deletes them, and then enqueues itself. I'm not sure if this is possible without messing with the sidekiq internals.

This is something I'd really like to achieve, because `SmallJob` can be run 100-200 times for a project...and `ProjectJob` only needs to be run once (but at the end).

I agree, it doesn't sound like batches will work here.

---

In case a little more detail helps to clarify the use case:

A (or many) user(s) can contribute content to a project (which is collaborative). They can also edit the content they already contributed.

When any contribution is created/updated, we use a job to cache the number of printed pages that the contribution will fill (`SmallJob` in my example).

After the contribution's page count is cached, a job runs to update the total page count of the project which retrieves all contributions from the database and adds the page counts together.

There is no telling how often these things will happen in a project. There are also some actions the project organizer can execute which cause edits (and, as such, page count caching) on all contributions to a project at once (which can be 100+)...This actually results in 300 jobs being run for a project with 100 contributions although only 201 are necessary.
