### ISSUE TITLE
sidekiqswarm concurrency

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4930]
Hello,

I know concurrency has come up in almost 450 issues, so I apologize for opening another one. I didn't find one that fit exactly my question though.

I'm working on switching our codebase from Sidekiq to Sidekiq Enterprise, and I am trying to understand how concurrency and multi-process work together.

If I have:
Heroku Performance-L dyno
10 concurrency
`pool: 10` in database.yml (by following https://www.youtube.com/watch?v=XOfELjqm188)

Will this work okay? There will be 8 processes, so that means 80 total max concurrency...how does that work with `pool: 10`? Is `pool` in the database.yml a per-sidekiqswarm-process setting? Or am I setting an overall max concurrency that is 8x the size of the database connection pool available the processes?

Thanks for all the help!

**Comment by mperham** [comment]
Pools are per-process so 10 will work perfect. Yes, you’ll have 80 threads in 8 processes unless you configure it differently.

**Comment by brandoncc** [comment]
Thanks Mike, I have one more question that I should have asked in my original question. How should I dial my redis config?

Would it be like this?

```yml
Sidekiq.configure_client do |config|
  config.redis = {
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
    size: 1
  }

  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
end

Sidekiq.configure_server do |config|
  config.redis = {
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
    size: 12
  }
end
```

https://manuelvanrijn.nl/sidekiq-heroku-redis-calc/ doesn't have a "sidekiqswarm" option and I haven't made the connection in my mind to answer this with 100% certainty yet.

Does this look correct for my swarm based on my configuration above?

![image](https://user-images.githubusercontent.com/543973/122816038-12a4a800-d28b-11eb-9b6d-ccbcdc805c52.png)

**Comment by mperham** [comment]
Get rid of the sizes. Let Sidekiq size the pool automatically.

**Comment by brandoncc** [comment]
Done, thanks!
