### ISSUE TITLE
Wrong enterprise version being installed?

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4931]
For some reason, my installed version of Enterprise seems to be dependent on Sidekiq 4:

![image](https://user-images.githubusercontent.com/543973/122818635-50570000-d28e-11eb-90fa-fca3a35b0136.png)

This is what my Gemfile looks like:

```
gem 'sidekiq'
source "**redacted**" do
  gem 'sidekiq-pro'
  gem 'sidekiq-ent'
end

gem 'sidekiq-failures'
gem 'sidekiq-history'
gem 'sidekiq-scheduler'
gem 'sidekiq-status'

```

I started down this path because after installing ent/pro sass-rails started throwing "can't modify frozen Array" when starting `sidekiqswarm` locally....I'm not sure if that is related or not but now I found this version issue.

**Comment by mperham** [comment]
Get rid of as many of those extensions as you can. Then upgrade everything Sidekiq related in your Gemfile.

**Comment by mperham** [comment]
Put an explicit dependency on Sidekiq 6.x in your Gemfile and Bundler will tell you which gem is conflicting with that rule.

**Comment by brandoncc** [comment]
Thanks Mike, I don't know why I didn't think of doing that.

For anyone else that hits this and is on Rails 4, Sidekiq 6 depends on Rack 2 but Rails 4 depends on Rack `~> 1.6`.

I guess I finally get to upgrade Rails!
