### ISSUE TITLE
Class instance variables

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4932]
I'm going through our gems and I found this:

https://github.com/blocknotes/prawn-styled-text/blob/b3771e1f3aed1cbd4d415ac196d5bb365ca93550/lib/prawn-styled-text/prawn-styled-text.rb#L17-L19

Based on these lines, I believe using this gem with multi-process is a terrible idea. Is that correct?

**Comment by mperham** [comment]
I would open an issue there and ask.
