### ISSUE TITLE
Unique jobs in testing

### ISSUE THREAD

**Issue by rmachielse** [mperham/sidekiq#4934]
Hi @mperham, we are using unique sidekiq jobs through the enterprise subscription. During testing we use the `Sidekiq::Testing.inline!` strategy, which runs all jobs right away. With larger tests, this causes jobs to be run a lot more often than necessary.

For example, let's say we have a `User` and a `Post` model and a sidekiq job is triggered for each new post by a user. Then if we have an RSpec test like this:

```ruby
describe 'with 4 posts' do
  before do
    create_list(:post, 4, user: user)
  end

  it do
    # test that depends on sidekiq job being run
  end
end
```

In this case the sidekiq job will be executed 4 times.

Would it be a possibility to have a testing strategy that saves up the sidekiq jobs for the entire before block and executes them all together at the end of the before phase, while applying uniqueness? This would mean running only one job instead of 4 in this example. Over the entire codebase, this could improve the performance of tests a lot, without losing representability.

I'm looking forward to hearing your perspective on this!

**Comment by mperham** [comment]
If you want to speed up your tests, don't run jobs inline or make each test opt into inline jobs. Use the default testing setup and opt into `inline` for specific jobs that need it.
