### ISSUE TITLE
Delay for job being picked up by superfetch

### ISSUE THREAD

**Issue by gleseur** [mperham/sidekiq#4937]
Ruby version: 2.6.6
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): 5.1.3 / 4.0.2 / 1.7.2

Hi Mike,

Sometimes we have jobs that do not finish and are later picked up by the super fetch.
However this picking up only happens when we restart the dyno which can lead to a fairly long delay in the processing of the task (hours)

For instance it happened to the job JID-bb12ff36ed1011f4a2e11aea and when filtering the logs on this id, we only get the 3 lines:

Jun 23 07:23:55  app/worker.1 81 TID-owvme9cdh PackageAssembler JID-bb12ff36ed1011f4a2e11aea BID-HxBtApqAroMAzw INFO: start
Jun 23 08:42:03 app/worker.1 79 TID-go0xh45ef PackageAssembler JID-bb12ff36ed1011f4a2e11aea BID-HxBtApqAroMAzw INFO: start
Jun 23 08:42:08 app/worker.1 79 TID-go0xh45ef PackageAssembler JID-bb12ff36ed1011f4a2e11aea BID-HxBtApqAroMAzw INFO: done: 5.195 sec

The first execution never finishes so the job is picked up later (at 8:42 after a manual retry

Additionally we have
Jun 23 07:24:02 fcv-oms-private app/worker.1 [swarm] Child exited, PID 81, code , restarting...

Given the timings, I believe this is the reason for the job never finished

So is it considered a normal behavior?
Is there any way to have the "lost" jobs recovered more often than on a dyno restart ?

This is quite rare, we process millions of tasks per day and I've only seen it a couple times in the past weeks
and we've only noticed this since moving to Enterprise and setting up swarm

But the behavior is still quite problematic for us as some of the tasks are a bit time sensitive.

Thanks,
Guillaume

From changelog, I don't think this was improved

sidekiq.yml:
:dead_max_jobs: 1_000_000

initializer:
```ruby
# frozen_string_literal: true

Sidekiq::Extensions.enable_delay!
require 'sidekiq/pro/web'
Sidekiq::Web.set(:sessions, domain: Figaro.env.devise_cookie_domain)

schedule_file = 'config/sidekiq_schedule.yml'

if File.exist?(schedule_file) && Sidekiq.server?
  Sidekiq::Cron::Job.load_from_hash(
    YAML.load_file(schedule_file)
  )
end

# See https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud
Sidekiq.configure_client do |config|
  config.redis = {
    url: Figaro.env.REDIS_URL,
    driver: :ruby,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
    network_timeout: 5
  }
end

DIARIST_REDIS = ConnectionPool.new do
  if Figaro.env.DIARIST_REDIS_URL.blank?
    raise 'Did you set DIARIST_REDIS_URL in your env?'
  end
  Redis.new(url: Figaro.env.DIARIST_REDIS_URL)
end

# https://github.com/mperham/sidekiq/wiki/Reliability#setup
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end
```

**Comment by mperham** [comment]
Your versions are years old.  Can you please update?

**Comment by mperham** [comment]
I believe new versions will check for orphans more frequently but I don’t recall which version.
