### ISSUE TITLE
[Pro] `cleanup_the_dead` VS `check_for_orphans`

### ISSUE THREAD

**Issue by dv** [mperham/sidekiq#4939]
I was reading through the source code for Sidekiq Pro and noticed that orphan jobs are recovered in two places, namely `cleanup_the_dead` and in `check_for_orphans`. The latter is the intense process that only runs once per hour, the former is the light version that runs at every bootup.

I'm having a hard time imagining a scenario where orphan jobs would be picked up by `check_for_orphans` but not by `cleanup_the_dead`. Would it be possible to explain how one could end up in that situation, where the `super_processes` set does not contain the dead worker, yet the dead worker's private queue was also not recovered yet?

Or is `check_for_orphans` truly for those catastrophic scenarios beyond standard operating Sidekiq code, where e.g. random keys have been removed or a rogue piece of code has altered the data inconsistently?

**Comment by mperham** [comment]
I agree with you, I can't think of a scenario where `check_for_orphans` is still necessary unless we are guarding against catastrophic code bugs or manipulated Redis data. It provides an extra paranoid double check to ensure we didn't orphan a queue somehow but I'm unable to articulate a possible scenario.

**Comment by dv** [comment]
Thank you @mperham for confirming that!
