### ISSUE TITLE
Is there an in-built way to error when jobs are submitted to a queue sidekiq has not been made explicitly aware of?

### ISSUE THREAD

**Issue by john-h-k** [mperham/sidekiq#4944]
If you do 

```bash
sidekiq -q foo -q bar -q baz
```

but then submit a job to a queue named `important`, it silently sits in redis doing nothing. Surely this is sometimes desired behaviour, but more often *isn't* and is indicative of a bug. Is there an underlying technical reason sidekiq provides no way to verify submitted jobs are in an expected queue (we worked around this with a custom client middleware), and if not, would it be suitable as a feature for sidekiq?

**Comment by mperham** [comment]
In Redis, there’s no difference between an empty queue and a nonexistent queue. Technically this is possible to implement; it would add an extra network round trip to verify queue existence upon push so would impact performance. And then you’d need to manually unregister a queue if you want to stop using a queue, etc.
