### ISSUE TITLE
[WEB MONITORING] change root path

### ISSUE THREAD

**Issue by marcinmmalec** [mperham/sidekiq#4946]
Hello, I would like to propose a feature/change to the application that changes the root path.

Background: Our application is similar to https://github.com/mperham/sidekiq/issues/3815 where we have two applications on our website. 

`dissolve.com` is our main commerce app and we have our creators app at `dissolve.com/creators`. We have sidekiq setup on the commerce app and been trying to setup sidekiq ui, but have been having trouble with the static assets pointing to `/sidekiq` when we need it to point to `/creators/sidekiq`. The issue also extends to internal links in the ui. 

So in a similar style as proposed in https://github.com/mperham/sidekiq/issues/1873, I've developed a potential solution that allows clients to provide an alternative root that prefixes `/sidekiq`. For now I just call it `redirect_path`, but any other name would be better.

![Screen Shot 2021-07-19 at 5 46 19 PM](https://user-images.githubusercontent.com/23348776/126241463-2d0e239a-fea7-4358-88c6-1bcbfc63d044.png)
_Our sidekiq.rb initializer_

The idea is that a client can enter a value or not and the root path would reflect that. So no value equates to `/sidekiq` while entering `Sidekiq::Web.redirect_path = "/creators"` would results in `/creators/sidekiq`

![Screen Shot 2021-07-19 at 5 53 25 PM](https://user-images.githubusercontent.com/23348776/126241819-72171812-4400-4021-bdfa-0c0fc7a8a5df.png)
_Sidekiq on staging environment_

![Screen Shot 2021-07-19 at 5 54 27 PM](https://user-images.githubusercontent.com/23348776/126241887-fb81bed2-c8b6-4e11-84fb-9b5e157c90b7.png)
_Sideiq on development environment_

![Screen Shot 2021-07-19 at 5 55 32 PM](https://user-images.githubusercontent.com/23348776/126241940-7e47777a-17f8-4089-b3bc-2e58d9920778.png)
_These are the proposed changes_

Thank you for hearing me out

**Comment by mperham** [comment]
Did you see the section in the wiki about proxying the Web UI? That’s the
solution.

**Comment by marcinmmalec** [comment]
Unfortunately, that solution isn't compatible with our current setup of nginx

Thank you anyway
