### ISSUE TITLE
Clarification required on Redis version requirements

### ISSUE THREAD

**Issue by ziggythehamster** [mperham/sidekiq#4947]
The docs and upgrade guides are ambiguous about the Redis version requirements. In some places, it's mentioned that Sidekiq now requires `redis-rb >= 4.0`, but in other places, it's mentioned you need `Redis 4+`. These could mean the same thing, or they could mean two different things (redis-rb and the Redis server).

Can this be clarified so that both the minimum Redis and minimum redis-rb version are stated?

**Comment by mperham** [comment]
Sidekiq 6 requires Redis server 4+. Redis-rb version is controlled by the
gemspec dependency and can change from version to version.
