### ISSUE TITLE
Document how to extend validation

### ISSUE THREAD

**Issue by edusantana** [mperham/sidekiq#4948]
Sidekiq has this validation:

https://github.com/mperham/sidekiq/blob/e8df351f0a6b222807ecf2e05a98149187b02e48/lib/sidekiq/client.rb#L222-L228

How can we extend this validation?

```ruby
class Worker::EmailScheduler
  include Sidekiq::Worker
  sidekiq_options :queue => :email_scheduler, :backtrace => true

  def perform(data)
    email_sending_config = data['email_sending_config']
#... send email

  end

    def extended_validattion(item)
       # raise if item doesn't have valid email
    end

end
```

**Comment by mperham** [comment]
That’s not something Sidekiq provides today. Ruby provides several ways to patch in your own validations including Module#prepend, which you can use to wrap perform_async.
