### ISSUE TITLE
Ent sidekiqswarm forking, semantic logger

### ISSUE THREAD

**Issue by kornate** [mperham/sidekiq#4949]
As per: https://logger.rocketjob.io/forking.html

How can I get Semantic Logger working with Sidkiq Swarm?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#application-preload

this section has an example of an after fork block.

**Comment by kornate** [comment]
```
Sidekiq.configure_server do |config|
  config.on(:fork) do
    SemanticLogger.reopen
  end
end
```

Awesome, I missed that, thank you!
