### ISSUE TITLE
model associations cant be find

### ISSUE THREAD

**Issue by KanielOutis** [mperham/sidekiq#4951]
Ruby version: 2.7.0
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): 6.0.0 and 6.2 ( try with both )

I have a model `Customer` in my application and only on that model can't use any type of assotioantion while using perform_async with `Sidekiq::Worker`: 

`sidekiq 2021-07-27T13:25:10.117033715Z 2021-07-27T13:25:10.116Z pid=18 tid=1t2q WARN: ActiveRecord::AssociationNotFoundError: Association named 'any_assoc' was not found on 
Customer; perhaps you misspelled it?`

It doesn't work with eager_loading through `includes` and lazy loading after record found. On other models i have no that problem

**Comment by mperham** [comment]
Restart Sidekiq.

**Comment by KanielOutis** [comment]
It restarts on every deploy

**Comment by KanielOutis** [comment]
> Restart Sidekiq.

It restarts on every deploy
