### ISSUE TITLE
Question: Concurrent/Parallel calls

### ISSUE THREAD

**Issue by debow77** [mperham/sidekiq#4953]
I'm trying to figure out the best way to have either 2 methods run at the same time or one method get called but continue to the next block of code.

Issue is, I moved my app to kubernetes so have 3 worker nodes now. My old method called JOB1 which within the perform called JOB2 and JOB3. Problem is JOB1 creates files that were read and made DB updates by JOB2. Now my issue is getting JOB1 to create the files but also run the same code that parses the files and updates the database as the method that creates the file runs. I don't want to wait until the files are done righting. I can't use different JOBS as the files might be created on a different worker then the JOB trying to read the files.

I've been trying to use Concurrent::Promise which seemed like it was working but have noticed the JOB will complete while the promise is still running. If I try to promise.wait or check its state etc. it seems to make things worse.

Ideally I'm trying to
```
def perform(**args)
  ...promise(kick call to monitor files)
  start_cmd(...) This kicks the call off that starts to write the files.

  Here I want to wait for both start_cmd to finish and the promise. It seems like once the start_cmd is done the Job 
  completes and the promise runs in the background.
end
```

**Comment by mperham** [comment]
Sounds like you want Batches. https://github.com/mperham/sidekiq/wiki/Batches

**Comment by debow77** [comment]
> Sounds like you want Batches. https://github.com/mperham/sidekiq/wiki/Batches

Thank you, I'll take a look for sure. I would assume the batches would run from the same worker?

**Comment by mperham** [comment]
> Thank you, I'll take a look for sure. I would assume the batches would run from the same worker?

I don’t know what you mean. What is a worker? A batch does not run, jobs run. A batch is a group of jobs, jobs can execute in any Sidekiq process that pulls that job from its queue.

**Comment by debow77** [comment]
Sorry about that, we have our rails app spread out in K8 with 3 app pods/nodes and 3 worker pods/nodes(running Sidekiq) leveraging redis/postgres DB. So redis is picking up the Job sending it to the worker.

High level config.
![image](https://user-images.githubusercontent.com/8048889/128090206-41a5d821-e7c2-445b-aebc-6db7084b8ae0.png)

So right now if JOB1 is picked up and inside it calls another Job.perform_later that might be picked up by another sidekiq worker where my files from JOB1 won't exist.

With batches if JOB1 creates a batch of JOBS I'm not sure if redis is going to also send those to different workers or if they'll all run from the same which is what I'm after.

**Comment by mperham** [comment]
https://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/

**Comment by debow77** [comment]
Thanks, I'll look into that. Sounds exactly like my issue.

**Comment by ashortt** [comment]
Hi, @mperham are batches available in Enterprise, or only Pro?  I was looking into using Concurrent in Enterprise (with a max concurrency of 1) but saw the following statement:

```
Rate limiters do not slow down Sidekiq's job processing. If you push 1000 jobs to Redis, Sidekiq will run those jobs as fast as possible which may cause many of those jobs to fail with an OverLimit error. If you want to trickle jobs into Sidekiq slowly, the only way to do that is with manual scheduling. Here's how you can schedule 1 job per second to ensure that Sidekiq doesn't run all jobs immediately:

1000.times do |index|
  SomeWorker.perform_in(index, some_args)
end
Remember that Sidekiq's scheduler checks every 5 seconds on average so you can get a small clump of jobs running concurrently.
```

**Comment by mperham** [comment]
Batches are in Pro. Rate limiters are in Enterprise.

Yes, the jobs can run concurrently BUT the code within a rate limited block will run within a Mutex. Any other job will wait or raise an OverLimit error.

**Comment by ashortt** [comment]
I have about 20 000 jobs that need to run in parallel, so if they raise an OverLimit error, will they automatically reschedule?

**Comment by mperham** [comment]
Yes. It's also recommended you schedule those jobs across time so as to avoid those concurrency conflicts. A conflict reschedule is just wasted CPU time.

**Comment by ashortt** [comment]
Yes we do currenlty schedule them now, however with so many jobs to schedule, it's impossible to schedule them given they could complete anywhere from 10seconds to 1 minute, that's why the batch feature in Pro looked interesting.  Is there anyway to replicate that behaviour in Enterprise.

**Comment by mperham** [comment]
Enterprise is a superset of Pro. Enterprise has the Batches feature.

**Comment by ashortt** [comment]
Thanks for all your help that’s great!
