### ISSUE TITLE
SIDEKIQ NOT WORKING CORRETLY 

### ISSUE THREAD

**Issue by ciscolive** [mperham/sidekiq#4954]
root@cnsz-ifa-ipam:/data/mojo|master⚡ ⇒   rails about
About your application's environment
Rails version             6.1.4
Ruby version              ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
RubyGems version          3.2.19
Rack version              2.2.3
Middleware                Rack::Cors, ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, Rack::Head, Rack::ConditionalGet, Rack::ETag, Warden::Manager, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, Warden::JWTAuth::Middleware
Application root          /data/mojo
Environment               development
Database adapter          postgresql
Database schema version   20210730075326

```ruby
14:10:19 sidekiq.1 | {"time":"2021-08-05T14:10:19+08:00","severity":"error","class":"Async::Task","oid":67420,"pid":9123,"subject":"#<Async::Task:0x1075c connected to #<Addrinfo: 10.248.110.11:8080 TCP> [fd=105] (failed)>","message":"can't add a new key into hash during iteration"}
14:10:19 sidekiq.1 | 2021-08-05T06:10:19.982Z pid=9123 tid=50j class=HealthCheckJob jid=a241b0f6a6fb1ea79ebc325b elapsed=0.013 INFO: done
14:10:19 sidekiq.1 | 2021-08-05T06:10:19.982Z pid=9123 tid=50j class=HealthCheckJob jid=d6ca08f14659f7e9b9e45fbf INFO: start
14:10:19 sidekiq.1 | {"time":"2021-08-05T14:10:19+08:00","severity":"error","class":"Async::Task","oid":67480,"pid":9123,"subject":"#<Async::Task:0x10798 connected to #<Addrinfo: 10.248.110.11:8080 TCP> [fd=106] (failed)>","message":"can't add a new key into hash during iteration"}
14:10:19 sidekiq.1 | 2021-08-05T06:10:19.995Z pid=9123 tid=50j class=HealthCheckJob jid=d6ca08f14659f7e9b9e45fbf elapsed=0.013 INFO: done
14:10:19 sidekiq.1 | 2021-08-05T06:10:19.996Z pid=9123 tid=50j class=HealthCheckJob jid=148128e37f1c4d7d1899d7f4 INFO: start
14:10:20 sidekiq.1 | {"time":"2021-08-05T14:10:20+08:00","severity":"error","class":"Async::Task","oid":67540,"pid":9123,"subject":"#<Async::Task:0x107d4 connected to #<Addrinfo: 10.248.110.11:8080 TCP> [fd=107] (failed)>","message":"can't add a new key into hash during iteration"}
```

**Comment by mperham** [comment]
I need the backtrace for the error.

**Comment by seuros** [comment]
This is not related to sidekiq. The stack shows you altering a hash while it doing iteration,
