### ISSUE TITLE
Row locks

### ISSUE THREAD

**Issue by brandoncc** [mperham/sidekiq#4958]
I remember reading something in the docs about postgres locks not working with certain features of sidekiq enterprise, but I can't find it now. 

Can I use row locking like [this](https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html) with all of the features of sidekiq enterprise?

Thanks!

**Comment by mperham** [comment]
Sidekiq should be orthogonal to your database. I can’t imagine why that wouldn’t work.

**Comment by brandoncc** [comment]
Thank you Mike, I wish I could remember what I read about locks and where it was.
