### ISSUE TITLE
Mixing Batches with Concurrency

### ISSUE THREAD

**Issue by ashortt** [mperham/sidekiq#4960]
Hi,

I read this article: https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches

Is it possible to use concurrency from Sidekiq enterprise with this feature?  For example, where you have these jobs working in parallel, I would instead like them performed in sequence.

```ruby
step2.jobs do
  B.perform_async
  C.perform_async
  D.perform_async
  E.perform_async
  F.perform_async
end
```

**Comment by mperham** [comment]
Do you mean serially?

Batches are the only mechanism to enforce serial execution, by creating a workflow using callbacks to create C only after B is successful.

Yes, the concurrent rate limiter can be used with those jobs to ensure only N copies of B can run concurrently.
