### ISSUE TITLE
100% CPU usage with sidekiq service

### ISSUE THREAD

**Issue by msetbar** [mperham/sidekiq#4961]
Ruby version: 2.3.0
Rails version: 5.0.0
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 4.0.3, sidekiq-ent 1.6.1, sidekiq 5.0.5

My sidekiq service is utilizing 100% of CPU with 30 workers on a 4 core CPU in docker swarm. I have decreased number of workers multiple times from 50 to 30 but there is no change in the CPU utilization. What can be the main reason?

**Comment by mperham** [comment]
Hi, a couple of things:

* that version of Sidekiq Enterprise is four years old. Please upgrade to a newer version using `bundle up sidekiq-ent`.
* I don't know what a "worker" means. Please specify process count and thread count (aka concurrency or -c).
