### ISSUE TITLE
Scrub PII

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#4962]
Ruby version: 2.6.5
Rails version: 5.1.4
Sidekiq / Pro / Enterprise version(s): 5.2.7

We need to scrub PII from logs, web interface and etc.

We are currently doing some monkey patches like this:

```ruby
module Sidekiq
  module WebHelpersExtension
    ARGS_FILTER = ActionDispatch::Http::ParameterFilter.new(MY_APP::SENSITIVE_PARAMS)

    def display_args(args, truncate_after_chars = 2000)
      super(
        args.map do |arg|
          arg.is_a?(Hash) ? ARGS_FILTER.filter(arg) : arg
        end,
        truncate_after_chars,
      )
    end
  end
end
```

What do you think about supporting this natively?

**Comment by sobrinho** [comment]
Something simple like this would suffice to not couple to any implementation:

```ruby
Sidekiq.configure_client do |client|
  client.data_scruber = ->(data) {
    data.transform_values { |value| "[REDACTED]" }
  }
end
```

That way we could use the Rails scrubber as we have in the rest of the app, like this:

```ruby
ARGS_FILTER = ActionDispatch::Http::ParameterFilter.new(MY_APP::SENSITIVE_PARAMS)

Sidekiq.configure_client do |client|
  client.data_scruber = ARGS_FILTER
end
```

**Comment by mperham** [comment]
This is one advantage of Enterprise's encryption support. Scrubbing output is like playing whack-a-mole, you'll be adding new sensitive data over time and adjusting that params list. Is the better solution to provide your own encryption of sensitive data?

**Comment by mperham** [comment]
https://miacupcake.com/wp-content/uploads/2019/10/whack-a-mole.gif

**Comment by sobrinho** [comment]
I see but we already have to play the whack-a-mole for the rails params logging 🤷

**Comment by mperham** [comment]
I’m going to recommend encryption. There are OSS plugins if you don’t want to buy Enterprise.

**Comment by sobrinho** [comment]
Sounds good, thanks for the support! ❤️
