### ISSUE TITLE
Sidekiq options don't work for ActiveJob when scheduling periodic jobs

### ISSUE THREAD

**Issue by katyho** [mperham/sidekiq#4963]
Ruby version: 2.7.3
Rails version: 6.0.3.7
Sidekiq / Pro / Enterprise version(s): 6.1.1 / 5.1.1 / 2.1.1

We use sidekiq to schedule periodic cron jobs. We've been using ActiveJobs just fine for cron jobs, but when we specify custom sidekiq_options in an ActiveJob, we get the following error upon booting sidekiq:
```
NoMethodError: undefined method `sidekiq_options' for <JobClass>
```

This only happens for cron jobs, which suggests a loading order issue when sidekiq is booted and these jobs are first registered.

**Comment by katyho** [comment]
Thanks for your quick response!

From https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#notes
> Starting in Rails 6.0, initializers are not allowed to load application classes so the API was adjusted to pass class name as a String instead.

We found that we're able to mostly load ActiveJob classes in the initializer, just not fully (e.g. not when we have a sidekiq_option specified). I think we can work around this by registering the cron jobs in an after_initialize hook. Is there a reason why passing in the raw string class name is preferred? It feels more versatile to do it in the after_initialize hook, in case we want to peek into the job class to extract some information when we register it.

**Comment by mperham** [comment]
If you load your application code in an initializer, rails can’t autoload it for each request in development mode.

**Comment by gustavompo** [comment]
Is supporting ActiveJob planned for some next release?
We'd really like to keep consistency in our jobs as well as maintaining the existing middlewares we have in place for ActiveJob. Alternatives out there that at some extent, work with ActiveJob, are definitely not well maintained repos anymore (e.g https://github.com/ondrejbartas/sidekiq-cron/issues/304)

**Comment by mperham** [comment]
It is not a goal of mine to make every feature transparently work with Active Job but I am always willing to listen to suggestions for quality of life improvements in the integration.
