### ISSUE TITLE
Sidekiq going over retry count specified in job's sidekiq_options

### ISSUE THREAD

**Issue by feliperaul** [mperham/sidekiq#4965]
Ruby version: 2.7.2
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): 6.2.1

No initializer, sidekiq.yml just has 3 queues an concurrency 25.

Given a job:

```rb
class ImportXmlListWorker
  include Sidekiq::Worker

  MAX_RETRIES = 16

  SIDEKIQ_QUEUE_NAME = "importers"

  sidekiq_options(
    backtrace: true,
    retry: MAX_RETRIES,
    dead: false,
    queue: SIDEKIQ_QUEUE_NAME
  )

sidekiq_retries_exhausted do |msg|
    user_id = msg['args'].first
    user = User.find(user_id)
    XmlImporterService.disable_import_for_user(user)
  end
```

I'm seeing retries go as far as 17 right now, without sidekiq making the job go away (it should disappear since `dead` is set to false.

How one would go about debugging why the max retries are not in effect?

**Comment by lmansur** [comment]
Did you change the retry value to 16 **after** the job had been enqueued for the first time? The max retry value is sent to Redis with the job's payload, and the job retrier uses that value to determine when to stop retrying.

If the job is still alive, you can find it with `job = Sidekiq::RetrySet.new.find_job(jid)` and check it's max retry count with `job.item["retry"]`.

**Comment by feliperaul** [comment]
@lmansur That was exactly what had happened. Thank you :)
