### ISSUE TITLE
Frequent Redis::ConnectionError: Connection lost (ECONNRESET) in Sidekiq Pro

### ISSUE THREAD

**Issue by technofreak** [mperham/sidekiq#4969]
Ruby version: 2.6.6
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): Pro (6.2.1)

**Initializer**

```
require 'sidekiq'
require 'sidekiq/web'

Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == [ENV['AUTH_EMAIL'], ENV['AUTH_PASSWORD']]
end

if Rails.env.staging? && defined?(Sidekiq)
  Sidekiq.configure_server do |config|
    config.redis = {url: ENV['REDIS_URL'], reconnect_attempts: 3, tcp_keepalive: 60}
  end
  
  Sidekiq.configure_client do |config|
    config.redis = {url: ENV['REDIS_URL'], reconnect_attempts: 3, tcp_keepalive: 60}
  end
end
```

_We're testing sidekiq-pro in our staging environment_.

**Error Backtrace**

We get the following error every 1 minute.

```
2021-08-17T02:24:31.946Z pid=6 tid=oxowxsjgm WARN: Redis::ConnectionError: Connection lost (ECONNRESET)
2021-08-17T02:24:31.947Z pid=6 tid=oxowxsjgm WARN: /vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:292:in `rescue in io'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:284:in `io'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:296:in `read'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:164:in `block (3 levels) in call_loop'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:163:in `loop'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:163:in `block (2 levels) in call_loop'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:265:in `block (2 levels) in process'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:406:in `ensure_connected'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:162:in `block in call_loop'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:317:in `with_socket_timeout'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/client.rb:161:in `call_loop'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/subscribe.rb:44:in `subscription'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis/subscribe.rb:22:in `psubscribe'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis.rb:3613:in `_subscription'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis.rb:2400:in `block in psubscribe'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
/vendor/bundle/ruby/2.6.0/gems/redis-4.4.0/lib/redis.rb:2399:in `psubscribe'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:63:in `block in listen'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:98:in `block in redis'
/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq.rb:95:in `redis'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:62:in `listen'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

**System architecture**

We have recently upgraded from Sidekiq v6.1.1 to Sidekiq Pro (6.2.1). We are testing this currently in our staging environment.

We run our rails apps and sidekiq in a dockerized environment using Nomad.

We connect to a self-hosted Redis server (redis:6.0.9-alpine3.12), implemented as a Redis Sentinel of 3 nodes (1 master, 2 slaves) with AOF persistence enabled. This is also orchestrated by Nomad in a dockerized environment. Redis is also used as a secondary datastore in the Rails applications.

Sidekiq and Rails connect (SSL) to this Redis through HAProxy, which decides the master node to connect by talking with the Sentinel.

**Comment by mperham** [comment]
You have Nomad, Docker, HaProxy, Redis Sentinel all in your network. That’s an extremely complex architecture. The issue is very likely some configuration element in one of those pieces. You’ll need to start pulling out one piece at a time and seeing if the behavior changes, eg Use a single Redis, not Sentinel, remove HaProxy, etc. The good news is that because you can reproduce it, you should be able to narrow it down quickly.

**Comment by technofreak** [comment]
@mperham We have not seen this problem while using the Sidekiq 6.1.1, the open source version, while the network setup has been the same. Is the monit process specific to Sidekiq Pro? 

Also, is there a way to trigger the monit/watchdog process via the API so that we can test it independently?

We also notice that while all other Sidekiq logs are appearing with a timestamp in AEDT matching our rails configuration, these error messages appear in UTC. We doubt that it might not be picking up things configured in rails properly.

`2021-08-19 09:49:22.398 | 2021-08-18T23:49:22.398Z pid=6 tid=ovuc4nooq WARN: Redis::ConnectionError: Connection lost (ECONNRESET)`

**Comment by mperham** [comment]
This is due to a long-lasting connection (which is used to implement queue pausing) that is being reset by something in your network architecture. Sidekiq OSS does not have this feature so it does not display this error.

You need to find the thing that is resetting persistent Redis connections after 60 seconds. Possibly HAProxy.

But the important thing to note here: Sidekiq Pro can't do anything to fix or workaround this behavior. The only thing I could possibly do is not log the error but then you risk not seeing other network issues.

**Comment by mperham** [comment]
The next version of Sidekiq Pro (coming tomorrow) will ignore the first exception and only log the second exception. This will allow systems to kill the socket and Sidekiq Pro will quietly re-establish the socket. If it immediately fails, that exception will be logged.

This should provide the semantics you want: connections are not held forever (so you can fail over) but the fail over is "quiet" and does not add unnecessary noise to your logs.

**Comment by technofreak** [comment]
@mperham Thanks for the additional information. That should help us in finding what's wrong on our end and fix it. Am I correct in inferring that would also mean the queue pausing feature will not be functional until we fix this?

**Comment by mperham** [comment]
No, that is incorrect. The connection errors and Pro immediately reestablishes the connection. It logs the error but recovers. The next version will not log the error unless it happens twice in a row.
