### ISSUE TITLE
Breaking changes from 6.2.1 to 6.2.2

### ISSUE THREAD

**Issue by james-em** [mperham/sidekiq#4973]
Ruby version: 3.0.1
Rails version: 6.1.4.1
Sidekiq [6.2.1 --> 6.2.2]

Sidekiq 6.2.1 works fine.
Sidekiq 6.2.2 generates the exception below.

All my gems are up to date as of today.

**Initializer**

```
Rails.application.reloader.to_prepare do
  # expiration = default expiration for how long job status are persisted in Redis.
  Sidekiq.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware, expiration: 12.hours
    chain.add SidekiqUniqueJobs::Middleware::Client
    chain.add Sidekiq::Middlewares::Client::HistoryMiddleware
  end

  Sidekiq.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 12.hours
    chain.add SidekiqUniqueJobs::Middleware::Server
    chain.add Sidekiq::Middlewares::Server::HistoryMiddleware
  end
end
```

**Error**
![Screen Shot 2021-08-25 at 8 51 28 AM](https://user-images.githubusercontent.com/63726983/130794015-74241d38-8ea0-4cdf-84ed-640655eb0edd.png)

**Code specific**
![Screen Shot 2021-08-25 at 8 54 33 AM](https://user-images.githubusercontent.com/63726983/130794138-868706b6-d6d7-43da-bb20-0cc7b88cc168.png)
![Screen Shot 2021-08-25 at 8 54 26 AM](https://user-images.githubusercontent.com/63726983/130794140-10c955c1-5977-4dda-917d-ae15cb6f9c0a.png)

**Comment by mperham** [comment]
https://github.com/kenaniah/sidekiq-status/issues/4
