### ISSUE TITLE
Sidekiq jobs "hang" when connecting to pgbouncer

### ISSUE THREAD

**Issue by StevenJL** [mperham/sidekiq#4974]
Ruby version: 2.5.8
Rails version:  4.2.11.3
Sidekiq / Pro / Enterprise version(s): 6.2

Dear Sidekiq community,

Has anyone ever successfully connected sidekiq to pgbouncer?  We switched to pgbouncer recently for better db connection pooling.  The puma/rails processes are able connect to the database fine, but the sidekiq processes don't seem to be working.  What I mean is:

At first right when we start up the sidekiq process, it is able to process jobs in a timely manner.  But after a while (a hour or so), jobs that normally take milliseconds end up "hanging" for 50+ minutes or longer, yet we see no queries in the database coming from sidekiq.  We conclude that the sidekiq processes are no longer able to connect to the postgres database through pgbouncer.

Anyone experience this? Any resolutions?

Thank you so much!

**Comment by mperham** [comment]
I've heard from dozens of customers using pgbouncer successfully. I have no idea what might cause that behavior.
