### ISSUE TITLE
When restarting workers, jobs are processed on paused queues

### ISSUE THREAD

**Issue by aaugustin** [mperham/sidekiq#4975]
I put a queue on pause (with the Sidekiq Pro UI). While most of the jobs on that queue were indeed blocked, I noticed that 2 or 3 jobs got processed once in a while.

After some investigation, I could correlate with deployments triggered by our CI/CD pipeline. Every time we deploy a new version of the API, Sidekiq Pro workers are redeployed. At this point, 2 or 3 jobs from the queue are processed, even though the queue is paused. I suspect that workers start processing jobs before loading the paused status of queues.

I didn't try to make a minimal repro. However, if you enqueue some jobs, pause the queue, and start a worker, you should be able to reproduce.

Ruby version: 2.7.1
Rails version: 6.0.4
Sidekiq / Pro / Enterprise version(s): Pro < 6

Unroll to see sidekiq.rb:

<details>

```ruby
# frozen_string_literal: true

redis_opts = if Rails.env.test? && defined?(Redis::Connection::Memory)
  {driver: Redis::Connection::Memory}
else
  YAML.safe_load(ERB.new(File.read("#{Rails.root}/config/redis.yml")).result)[Rails.env]
end

# https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Client
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_client do |config|
  config.redis = redis_opts
end

# https://github.com/mperham/sidekiq/wiki/Reliability
Sidekiq.configure_server do |config|
  config.super_fetch!
  config.redis = redis_opts
  config.average_scheduled_poll_interval = 1
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new

  config.server_middleware do |chain|
    require "prometheus_exporter/instrumentation"
    chain.add PrometheusExporter::Instrumentation::Sidekiq
  end

  config.death_handlers << PrometheusExporter::Instrumentation::Sidekiq.death_handler

  config.on :startup do
    require "prometheus_exporter/instrumentation"
    PrometheusExporter::Instrumentation::SidekiqQueue.start
    PrometheusExporter::Instrumentation::Process.start type: "sidekiq"
  end

  at_exit do
    PrometheusExporter::Client.default.stop(wait_timeout_seconds: 10)
  end
end

Sidekiq.options[:max_retries] = 0
Sidekiq.options[:dead_max_jobs] = 100_000
Sidekiq.default_worker_options = {"backtrace" => true}
```

</details>

**Comment by aaugustin** [comment]
As I'm writing this the latest release is still 5.2.3. It would be super useful if you can confirm when 5.2.4 is available.

**Comment by mperham** [comment]
Thanks for the reminder, 5.2.4 is now available.

**Comment by aaugustin** [comment]
Fantastic! Going to deploy it right now :-)
