### ISSUE TITLE
api available on gem server?

### ISSUE THREAD

**Issue by thomasLeclaire** [mperham/sidekiq#4988]
Hello, 

i'm trying to install a tool (Renovate :https://renovatebot.com/) on my repos in orders to check the dependencies and manage updates. 
basically it requests the "standard" endpoints like on rubygems.org
so is there any plan to have link like https://enterprise.contribsys.com/api/v1/dependencies?gems=sidekiq-pro available ?

goes in 404 error for now

thanks anyway!

**Comment by mperham** [comment]
The commercial gem server implements only the endpoints for Bundler to properly find and download the correct gem versions.  Today, that is all of the legacy Rubygems static files and:

```
/versions
/names
/info/{sidekiq-pro,sidekiq-ent}
```

**Comment by thomasLeclaire** [comment]
Hi! thx for the reply!
I didn't find anything on bundler or rubygems side about the official endpoints or legacy ones. 
do you have some infos which could be provided there : https://github.com/renovatebot/renovate/discussions/11407#discussioncomment-1300392 

thx!!

**Comment by mperham** [comment]
I don't have any resources for you. I opened an issue with Bundler and asked for help in implementing the necessary endpoints. Googling isn't helping.

@indirect Where is the best documentation for the current Bundler endpoints and their purpose?

**Comment by indirect** [comment]
Conceptually, probably this blog post: https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/

Technically, this repo, where we keep the reference implementation that RubyGems.org uses: https://github.com/rubygems/compact_index
