### ISSUE TITLE
sidekiq_retry_in won't work for ActiveJob

### ISSUE THREAD

**Issue by travisp** [mperham/sidekiq#4998]
Ruby version: 3.0.2
Rails version: 6.1.4.1
Sidekiq verison: 6.2.1

I know the recommendation is to directly use Sidekiq Workers but I'm using an app that already makes use of ActiveJob. I was hoping to use the `sidekiq_retry_in` block with ActiveJob, and no errors are raised because sidekiq includes these options into the activejob classes automatically.

However, in Sidekiq's JobRetry class, it checks the `worker` argument for the `sidekiq_retry_in_block` variable, but only gets nil because worker is `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` and not the underlying ActiveJob class. 

It seems like for this to work, the `attempt_retry` method of JobRetry should look to see if the worker is wrapping another and obtain the wrapped class. Is there any intended support for this, or is this just something I either have to switch to pure sidekiq for or patch sidekiq?

**Comment by mperham** [comment]
This is on purpose. ActiveJob has its own retry implementation, conventions and idioms and I don't want to confuse the issue by mixing in every last Sidekiq feature. If you want to customize Sidekiq's retry subsystem for your job, you should be using Sidekiq::Worker.
