### ISSUE TITLE
Enterprise unique jobs uniqueness keys not removed when jobs are deleted/killed

### ISSUE THREAD

**Issue by sjahu** [mperham/sidekiq#5002]
The `unique:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` keys stored in Redis by Sidekiq Enterprise don't seem to be deleted when a matching unique job is deleted from the "Scheduled  Jobs" page or killed/deleted from the "Retries" page. Subsequent attempts to schedule a matching job fail until the `unique_for` time has elapsed and the Redis key expires, even though no "live" jobs with the same uniqueness hash remain.

**Comment by mperham** [comment]
Killed jobs should have their unique locks deleted; I'm pretty sure this was added semi-recently. You don't say your version, maybe you need an upgrade. I will confirm tomorrow.

**Comment by sjahu** [comment]
Oh, thanks Mike! I'm on Sidekiq 6.2.2 / Pro 5.2.4 / Ent 2.2.3. If it has already been fixed, sorry for the spam! Cheers.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/issues/4162 In 2.0.0.
