### ISSUE TITLE
Sidekiq Pro queue pause doesn't work

### ISSUE THREAD

**Issue by ermkv98** [mperham/sidekiq#5006]
Ruby version: 3.0.1
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): 6.2.2 / 5.2.4

Hi!
I've noticed that in `Sidekiq::Pro::SuperFetch#active_queues` there is subtraction of array of symbols and array of strings
`@options[:queues] - @paused.to_a`, in raw data it's something like `[:queue_name]` and `#<Set: {\"queue_name\"}>`
As result we're getting `active_queues` unchanged and queue pause doesn't work

**Comment by mperham** [comment]
Show me your initializer?

**Comment by ermkv98** [comment]
```
require "sidekiq/pro/api"
require "sidekiq/pro/web"
require "sidekiq-scheduler/web"
...
Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq.configure_server do |config|
  Logging.redirect(:rails, "sidekiq_rails")

  File.open("/tmp/sidekiq-ready", "w") rescue nil # Used for health probes

  config.redis = redis_options.call
  config.reliable!

  config.on(:startup) do
    config = YAML.load_file(Rails.root.join("config/sidekiq_scheduler.yml")).fetch(Rails.env)

    config.each do |key, value|
      value["queue"] = Object.const_get(key, false).queue_name
    end

    Sidekiq.schedule = config
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end

  config.server_middleware do |chain|
    chain.prepend(Lamian::SidekiqRavenMiddleware)
  end
end

Sidekiq.configure_client do |config|
  config.redis = redis_options.call rescue {}
end


class ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper
  sidekiq_retry_in { |count| ApplicationJob.retry_interval(count) }
end

module ActiveJobExtension
  def enqueue(*opts)
    message = <<~MSG.squish
      Enqueuing job #{self.class.name} (Job ID: #{job_id})
      with args: #{arguments.inspect}, options: #{opts}
    MSG
    logger.debug(message)

    DB.after_commit { super }
  end
end

ActiveJob::Base.prepend(ActiveJobExtension)
```

**Comment by mperham** [comment]
You have something which is symbolizing the queues array. When I start Sidekiq, I can see that the queues array is normally Strings. Do you have a `config/sidekiq.yml`?

```
> bundle exec sidekiq -q foo -q bar -v
...
2021-09-29T13:06:39.525Z pid=88140 tid=1t1g DEBUG: {:queues=>["foo", "bar"], 
...
```

**Comment by ermkv98** [comment]
Yeah, it's looks like this

```
defaults: &defaults
  :concurrency: 4
  :queues: &queues-defaults
    foo: 10
    bar: 10
    ...
    
development:
  <<: *defaults

test:
  <<: *defaults
  :queues:
    default: 10
    test: 5

staging:
  <<: *defaults

production:
  <<: *defaults
```

**Comment by mperham** [comment]
I suspect that's your problem. Use Strings for queue names, don't use the Symbol format.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/master/examples/config.yml#L13

For weights, use this:

```
:queues:
  - ["default", 10]
  - ["test", 5]
```

**Comment by ermkv98** [comment]
Thanks, issue resolved!
But could be any changes on this config notation? Symbols looks like more readable. I guess, that would be very helpful and could help to avoid this issue in future. In YAML notation those lines are in string format, but somehow parsed as a symbols 🤔

**Comment by mperham** [comment]
For safety, I will `to_s` the contents. Probably a good idea.
