### ISSUE TITLE
Should `sidekiqswarm` work with `https://github.com/DataDog/dd-trace-rb`?

### ISSUE THREAD

**Issue by justin808** [mperham/sidekiq#5007]
I've filed an issue: https://github.com/DataDog/dd-trace-rb/issues/1705.

I'm not sure if this is a DataDog or SideKiq issue.

**Comment by mperham** [comment]
It is ddtracerb that is failing so I would start there. If I need to do something specific to add support, please open an issue with relevant info and I’d be happy to consider the request.

Please don’t capitalize the K.  It’s Sidekiq.
