### ISSUE TITLE
Sidekiq stops working after Redis RTT information

### ISSUE THREAD

**Issue by c2ofh** [mperham/sidekiq#5017]
Ruby version: 2.7.3
Rails version: 5.2.6
Sidekiq version(s): 6.2.1, 6.2.2

**Initializer**
```ruby
require 'sidekiq_alive'
require 'sidekiq_queue_metrics'

redis_url = ENV['REDIS_URL'] || 'redis://localhost:6379/0'

Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url }
end

SidekiqAlive.setup do |config|
  config.queue_prefix = :x_alive
  config.server = 'puma'
end

Sidekiq.configure_server do |config|
  Sidekiq::QueueMetrics.init(config)
end
```

**sidekiq.yml**
```ruby
---
:verbose: false
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 3 %>

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [default, 1]
  - [storage, 1]
  - [links, 1]
  - [videos, 1]
  - [weathers, 1]
  - [statistics, 2]
  - [demo, 3]
  - [business, 3]
  - [mailers, 4]
  - [payment, 4]
  - [navigation, 5]
```

Since a few weeks we have the problem that jobs are suddenly not processed anymore. As soon as you don't look in for a few hours, there are 20000 jobs in the queue and the active jobs have been standing for 10 hours.

We have Sidekiq running in a Kubernetes cluster where Redis also has its workload. (Both on the same server)
When I restart the Sidekiq pods, it runs again without any issues for several hours or days. Then suddenly everything will stop. 

When all jobs stop the log is full of these messages:
![sidekiq](https://user-images.githubusercontent.com/10913793/136756133-d05bd46e-b256-41b5-b3e5-a8dfe5df78d2.jpg)

Shouldn't this just be an info and not stop the whole process? Redis is available all the time. 
Nothing has been changed technically that Redis would suddenly be accessible differently. The setup has been running for over 1 year without any problems. Only since about 2 weeks the problem occures.  
2 Weeks ago we updated sidekiq to Version 6.2.2, then the problems started, so we downgraded the gem to the previous version 6.2.1 but nothing has changed.

I have no Idea how to handle this problem.

**Comment by mperham** [comment]
Do you have a Kubernetes CPU limit on Redis? Your Redis is pausing exactly 100ms every time, a sign it is a configuration problem somewhere.

https://mcrthr.com/kubernetes-cpu-limits

> The default period is actually 100ms, and can be overridden as of Kubernetes 0.12

**Comment by t1ll** [comment]
@c2ofh we had the exact issue you described just today on Heroku. Were you able find out what it was related to?

**Comment by nateberkopec** [comment]
I want to leave a comment here that this may not necessarily be Redis latency and can be caused by an overloaded Sidekiq instance with a high concurrency setting: #5025
