### ISSUE TITLE
Web UI isn't working

### ISSUE THREAD

**Issue by ArcDlrt** [mperham/sidekiq#5019]
Ruby version: 2.6.3
Rails version: 6.0.4.1
Sidekiq / Pro / Enterprise version(s): 6.1.3 and 6.2.2 /  5.0.1 /  2.0.1

My web UI is not working. I'm updating sidekiq from 6.0.6 to a newer versions 6.2.2 originally after that I tried 6.13 but had the same issue.

I'm not getting any error in rails console, and in the browser I only see a 500 error

```ruby
## Initializer
Sidekiq.configure_server do |config|
  config.redis = { url: "#{ENV['redis_url']}/4/sidekiq" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "#{ENV['redis_url']}/4/sidekiq" }
end

if Rails.env.production?
  Sidekiq.configure_server do |config|
    config.periodic do |mgr|
      # 6 p.m
      mgr.register('0 18 * * *', Stp::FooWorker)
      # 11:55 p.m
      mgr.register('55 23 * * *', Stp::BarWorker)
    end
  end
end
```

```yaml
## sidekiq.yml
:timeout: 30
:concurrency: 1
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
FYI this is wrong: `"#{ENV['redis_url']}/4/sidekiq"`. A Redis URL looks like this: `host:port/dbnumber`, e.g. `localhost:6379/4`. It makes no sense to add "/sidekiq" on the end.
