### ISSUE TITLE
`check_rtt` also warns when a Sidekiq process is fully-utilized

### ISSUE THREAD

**Issue by nateberkopec** [mperham/sidekiq#5025]
Because the `ping` releases the GVL and other Sidekiq threads can do work in the background between lines 196 and 198, a fully-utilized Sidekiq server will constantly complain about its Redis RTT. I think this is misleading and could cause people to spend a lot of time debugging their Redis install when it's really just the case that their Sidekiq threads are completely loaded.

This could occur for any Sidekiq process that is highly utilized.

**Comment by mperham** [comment]
Not seeing any movement on that issue I created. I massaged the log message to note the possibility of CPU saturation.
