### ISSUE TITLE
Customize statsd tags in Sidekiq Pro

### ISSUE THREAD

**Issue by jordan-brough** [mperham/sidekiq#5037]
We have a multi-tenant application and we'd like to add a "tenant" tag to our Sidekiq statsd metrics.

We'd like to be able to group or filter metrics by tenant using the existing metrics that Pro provides ("jobs.count/perform/success/failure").

E.g. in Datadog we'd like to be able to create graphs for queries like this:
```sum:sidekiq.jobs.count{env:production} by {tenant}.as_count()```
or this:
```max:sidekiq.jobs.perform.max{env:production,tenant:some-tenant}```

If it were possible to do something like set thread-local tags that Sidekiq would include on any metrics it emits that could work great.

See also discussion here: https://groups.google.com/g/sidekiq/c/6E0sKogqFoQ/m/1jelx7DdAgAJ

**Comment by mperham** [comment]
I've added the ability to customize metric options per job by providing a custom Proc which generates the options:

```ruby
# add to your initializer
Sidekiq::Server::Middleware::Statsd.options = ->(w, j, q) do
  {tags: ["worker:#{w}", "queue:#{q}"]}.tap do |h|
    h[:tags] << "tenant:#{j['tenant_id']}" if j["tenant_id"]
  end
end
```

**Comment by mperham** [comment]
This will be in the forthcoming 5.3.0 release.
