### ISSUE TITLE
We need documentation for configuration

### ISSUE THREAD

**Issue by tonytonyjan** [mperham/sidekiq#5040]
I have spent over 15 minutes navigating the repository from source code to wiki pages trying to find a document of configuration but in vain.

There is no such document in README, [Getting Started](Getting-Started) or [The Basics](https://github.com/mperham/sidekiq/wiki/The-Basics). I wonder where I can find the documentation?

The only one I've found is in [Using-Redis](https://github.com/mperham/sidekiq/wiki/Using-Redis):

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://redis.example.com:7372/0' }
end
```

Looks like the `config` might have some attributes other than `redis` but it doesn't tell us what else `configure_client` and `configure_server` can do.

Besides, is it possible to configure Sidekiq by YAML file? If yes, where can I find the documentation?

**Comment by mperham** [comment]
We’ve never provided a comprehensive set of configuration options.  The wiki is more designed to help you configure features, not provide every knob you can turn. I see this as a feature, not a bug. One of the most common failures I see in users is them over-configuring Sidekiq and making it perform worse.

Yes, many options can be tuned by YAML. The example config file shows those options.
