### ISSUE TITLE
Feature Proposal: `Sidekiq::Worker.perform_bulk` to provide an API similar to `.perform_async` for bulk work 

### ISSUE THREAD

**Issue by kellysutton** [mperham/sidekiq#5041]
We've got a monkey-patch into `Sidekiq::Worker::ClassMethods` and `Sidekiq::Worker::Setter` that we have been getting a lot of mileage out of that might be worth upstreaming. 

Background: We do a lot of batch processing, needing to enqueue 1000's or 100's of K's of jobs at once. We were using [`Sidekiq::Client.push_bulk`](https://www.rubydoc.info/github/mperham/sidekiq/Sidekiq%2FClient:push_bulk) with an `each_slice` to create chunks of 1000. 

Enter what we call `.perform_bulk`. It's an implementation of `Sidekiq::Client.push_bulk` that encodes the best practice of 1000 jobs at a time. This allows clients to enqueue many jobs without the sharp edge of forgetting to slice their batch up into smaller chunks.

Downside here is that the `.push_bulk`-based approach _does_ communicate to the client, "Hey, you're interacting with the network N times (once per loop)."

Here's what the implementation could look like:

```ruby
module Sidekiq
  module Worker
    module ClassMethods
      def perform_bulk(args, batch_size: 1000)
        args.each_slice(batch_size) do |slice|
          Sidekiq::Client.push_bulk(@opts.merge('class' => @klass, 'args' => slice))
        end
      end
    end 
  end
end
```

Proposing here as a means of conversation. Can put together a Pull Request with tests if this seems worthwhile to get added to Sidekiq. Cheers!

**Comment by mperham** [comment]
Yeah send a PR. 6.3 is coming soon and we can sneak this in too if you’re
quick.
