### ISSUE TITLE
HEROKU wiki release recommendation missing failure handling

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#5047]
In https://github.com/mperham/sidekiq/wiki/Heroku#shutdown-timeout it says

> Heroku puts a hard limit of 30 seconds on a process restart, Sidekiq's default of `-t 25` gives jobs 25 seconds to finish before starting the "force shutdown" procedure. After 25 seconds, Sidekiq will push any remaining unfinished jobs back to Redis and exit.
Make sure your jobs are [idempotent](Best-Practices) so they will safely restart when the process starts back up.

> You can optionally use `require 'sidekiq/api';Sidekiq::ProcessSet.new.each(&:quiet!)` in a pre-deploy hook to give your jobs even more time to finish.

BUT, if you quiet all processes in your release task and the release fails for some reason, the queue backs up because the processes are never restarted.

Example from our app

```rake
desc "Run this task on release. (See Procfile)"
task release: :environment do
  release!
end

def release!
  $stderr.puts "Telling Sidekiq not to process any new jobs"
  require Rails.root.join "lib", "redis_connection"
  if RedisConnection.ok?
    require "sidekiq/api"
    Sidekiq::ProcessSet.new.each(&:quiet!)
  end
  $stderr.puts "Running migrations"
  Rake::Task["db:migrate"].invoke
end
```

(Procfile line is `release: env DATABASE_TIMEOUT=240 bin/rails release && bin/rails r 'puts "Booted"'` )

As you can see from the above, to give any jobs the most time to stop, the first thing we do is quiet them. But then the next thing, say the migration task fails, so the release fails, which is fine.. except that now the queue is no longer processing jobs. It doesn't seem there's an easy way to restart the workers from process set, and in any case, I think this is a caveat worth documenting beyond the note at the top of the deployment page that the solution is to send a TERM

>  Using TSTP+TERM in your deploy process gives your jobs the maximum amount of time to finish before exiting.

It appears that if I stop a worker, it restarts, which I suspect is a Heroku feature not part of Sidekiq.

So, that means I could edit my method to add

```ruby
rescue
  if defined?(RedisConnection) && RedisConnection.ok?
    # https://github.com/mperham/sidekiq/issues/5047
    $stderr.puts "Telling Sidekiq to stop the quieted workers (TERM). They'll scale back up."
    require "sidekiq/api"
    Sidekiq::ProcessSet.new.each(&:stop!)
  end
  raise
end
```

**Comment by mperham** [comment]
Yep, once you `quiet`, you must `term`. There's no rollback from quiet so your last suggestion is on point. Heroku is acting like any decent process manager; if the process exits, it should be restarted. That's what systemd and upstart do too.

**Comment by mperham** [comment]
BTW I wouldn't just quiet the workers and then immediately migrate. A running job could still be using the database and conflict with the migration. Best to scale down, migrate and then scale up.

I've updated the wiki to point here.

**Comment by justin808** [comment]
@mperham could you provide a snippet of code to that is the best way to wait until a quieted queue is done?

Is this the right check that the quieted queue is done with processing active jobs?

```ruby
Sidekiq::Queue.new('my-queue').size == 0
```

**Comment by mperham** [comment]
That means there are no more jobs in the queue. The jobs may still be executing. Do your jobs take longer than 25 sec to run?

**Comment by justin808** [comment]
Ahhh, thanks for the clarification. The code snippet I gave would be to check the queue is done, not paused. 

Does Sidekiq keep track of how many jobs are executing?

Jobs could take longer than 25 seconds, but that's infrequent. If jobs are killed by a TERM, will they retry?

**Comment by mperham** [comment]
That code will check if the queue is empty. "done" is something Sidekiq::Batch tracks.

Current jobs executing are tracked in the Sidekiq::WorkSet API, see [here](https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/#work).

Yes, if the process is shut down cleanly, Sidekiq will immediately restart those jobs on startup. If jobs are shut down uncleanly (e.g. `kill -9`), super_fetch will eventually rescue them and re-enqueue them for execution. Neither of those scenarios are considered a "retry". A retry happens when your job raises an error.
