### ISSUE TITLE
Periodic jobs failed to schedule for an hour this evening (suspect due to Daylight Savings Time)

### ISSUE THREAD

**Issue by Laundrysheet** [mperham/sidekiq#5049]
Ruby version: 2.5.5
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): 6.07 / 2.0.1 / 5.0.1

This evening we noticed that many of our jobs which are periodically scheduled to be run every minute, five minutes, etc. didn't run at all for an hour. We have never had this issue before so I suspect it's due to Daylight Savings Time ending this evening (in which an hour was rolled back).

This is the config for one of our workers whose sole purpose is to just run every minute and ping an endpoint to let us know that Sidekiq is up:

```ruby
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
     mgr.register("* * * * *", "Sidekiq::HeartbeatMonitoringWorker")
  end
end
```

And here is a screenshot in the Sidekiq Web UI for `Sidekiq::HeartbeatMonitoringWorker` showing jobs missing during the span of **12:00 - 01:00**. Our `TZ` environment variable is set to `America/Los_Angeles`.

![CleanShot 2021-11-07 at 01 03 27@2x](https://user-images.githubusercontent.com/2215940/140639381-323871c5-112f-4e44-be02-c423197ebced.png)

Does this sound like an issue due to Daylight Savings Time? I don't remember it happening when we "sprang forward" so it seems like this might only happen for when we "fall back" in which we lose an hour. Thanks for your assistance with this!

**Comment by mperham** [comment]
It does sound like a DST issue. I'll have to look at the cron logic to see; it may be doing something naive like `hour += 1` which will fail when falling back and the hour remains the same.

**Comment by mperham** [comment]
Are you loading Rails in this Sidekiq process?

**Comment by Laundrysheet** [comment]
@mperham Yep it should be since the Rails environment is available in every job. The process being run with

```
bundle exec sidekiq
```

Does that help?

**Comment by mperham** [comment]
Whew, this was a fun one. I tracked it down to a bug in the cron logic, fixed here:

https://github.com/siebertm/parse-cron/pull/40

**Comment by Laundrysheet** [comment]
@mperham Thanks for looking into it! 

Unfortunately it looks https://github.com/siebertm/parse-cron hasn't had a commit since 2016 so it feels unlikely that PR will be merged. What would the recommended short-term workaround be here?

**Comment by mperham** [comment]
It is fixed. I'm using a fork of that code.
