### ISSUE TITLE
`sidekiq_retries_exhausted` block is not using custom server middleware

### ISSUE THREAD

**Issue by dojutsu-user** [mperham/sidekiq#5050]
Ruby version: 2.5.5
Rails version: 6.0.3
Versions: Sidekiq v5.2.9 / Sidekiq Pro v3.7.1

I am using sidekiq custom middlewares to tag all the logs with some extra information. Each log is tagged except the logs inside the `sidekiq_retries_exhausted` block. It seems like custom server middlewares are not getting invoked for `sidekiq_retries_exhausted` block.

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version? yes

Please help me with this.

**Comment by mperham** [comment]
That’s right, that callback does not run within server middleware.
