### ISSUE TITLE
Sidekiq 6.3.1: "Uncaught EvalError" in Web UI / Live Poll

### ISSUE THREAD

**Issue by tagliala** [mperham/sidekiq#5053]
Ruby version: 2.7.4
Rails version: 6.1.4.1
Sidekiq / Pro / Enterprise version(s): 6.3.1 (and master)

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

- No initializer / default / N/A
- No sidekiq.yml / default / N/A

Relevant commits: 
- ✅  https://github.com/diowa/ruby3-rails6-bootstrap-heroku/commit/cf866b5f8b97f8e26ed24be748eb1d2b57ac5d2b
- ❌ https://github.com/diowa/ruby3-rails6-bootstrap-heroku/commit/3c7d30c5d156721bc83daadc1722ee851084ca44

### Screenshot

As you can see, live polling is missing after the first refresh

![image](https://user-images.githubusercontent.com/556268/140913187-9aeeb7c9-b011-418f-8b3d-9e44f47b9953.png)

### Browser console

```
application.js:2 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https: http: 'unsafe-inline'".

    at eval (<anonymous>)
    at application.js:2
    at Function.globalEval (application.js:2)
    at text script (application.js:2)
    at Xb (application.js:2)
    at y (application.js:2)
    at c (application.js:2)
    at Object.send (application.js:2)
    at Function.ajax (application.js:2)
    at Function.n._evalUrl (application.js:2)
```

**Comment by JasonBarnabe** [comment]
This seems to happen after the first "live poll" of the Dashboard page. Other pages are unaffected.

**Comment by tagliala** [comment]
> This seems to happen after the first "live poll" of the Dashboard page. Other pages are unaffected.

Yes, sorry, it is about the live polling feature. will add this detail in the opening post

**Comment by mperham** [comment]
PRs welcome. I’m at Rubyconf for the next few days.

**Comment by tagliala** [comment]
Trying to work on this, but I cannot replicate anymore

Closing here, if someone has the same issue please comment

**Comment by datanoise** [comment]
We are getting the same issue when viewing in Safari. It works fine in Chrome or Firefox.

**Comment by tagliala** [comment]
Reopening, will try to reproduce in Safari. I was getting this issue in Chrome, but unfortunately I didn't check the version :(

**Comment by josefbilendo** [comment]
I just upgraded sidekiq from `Sidekiq 6.2.1 / Pro 5.1.1 / Ent 2.2.2` to `Sidekiq 6.3.1 / Pro 5.3.0 / Ent 2.3.0`.
Locally, everything works as expected.

But on production I'm having the same issue in all my installed browsers:
- Chrome (v95.0.4638.69)
- Firefox (v94.0.1 )
- Safari (v15.1 )

---
Output from Chrome dev console:
```
application.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ application.js:2
application.js:2 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https: http: 'unsafe-inline'".

    at eval (<anonymous>)
    at application.js:2
    at Function.globalEval (application.js:2)
    at text script (application.js:2)
    at Xb (application.js:2)
    at y (application.js:2)
    at c (application.js:2)
    at Object.send (application.js:2)
    at Function.ajax (application.js:2)
    at Function.n._evalUrl (application.js:2)
```

---
In addition, the polling button(s) seem to be messed up:

<img width="1423" alt="Bildschirmfoto 2021-11-17 um 23 07 04" src="https://user-images.githubusercontent.com/20594372/142290173-5637aa35-c4f8-4309-bacd-ca0e0d3638f8.png">

**Comment by JasonBarnabe** [comment]
I had this issue after upgrading because I had nginx config to deal with https://github.com/mperham/sidekiq/wiki/FAQ#why-dont-cssjsimg-assets-load-properly-when-i-go-to-sidekiqs-web-ui, but this config was specific to the version of sidekiq. After updating the config, it works.
