### ISSUE TITLE
Web UI navbar shifts because "Active" and "Idle" indicators have different widths

### ISSUE THREAD

**Issue by JasonBarnabe** [mperham/sidekiq#5054]
Ruby version: 2.6.6
Rails version: 6.1.4.1
Sidekiq / Pro / Enterprise version(s): 6.3.1

The active/idle indicators in the top left of the Web UI have different widths, so the navigation items (Dashboard, Busy, etc.) jump left and right when Live Poll is on.

**Comment by mperham** [comment]
Would love to see a PR to fix this.
