### ISSUE TITLE
Configuration - JobLogger: Allow an option to control the start/done/fail logs level? or Custom Job Logger class

### ISSUE THREAD

**Issue by wspurgin** [mperham/sidekiq#5059]
👋 Long time listener first time caller

My org is always on the lookout to trim log volume (💸), and the Sidekiq Job Logger got called out for being particularly noisy 🙉 🙊 

Specifically, the `start` / `done` logs of the job at info level. I personally _like_ the logs, but I do acknowledge the argument that they're more of a `debug` level thing.

I discovered that I _can_ just roll my own custom job logger class that essentially copies the existing one and switches out the log level `s/info/debug`... Is that the recommended approach? (I don't love having to roll my own just to change the log level, but I think the risk of the Job Logger changing drastically and the custom class causing troubles for my whole org is _pretty_ low).

Or, would it be in line with Sidekiq Design goals (or at least not at odds with them) to provide a configuration/option that controls the internal log level of the Sidekiq Job Logger? (just to map out the idea, I sketched it out https://github.com/mperham/sidekiq/compare/main...wspurgin:ws/enhancement/control-job-logger-internal-log-message-level?expand=1)

```ruby
Sidekiq.configure_server do |sidekiq_config|
  sidekiq_config.options[:job_logger_internal_level] = :debug
end
```

**Comment by mperham** [comment]
The default logging allows you to track execution and elapsed time per-JID or per-jobtype. You can increase the log level to WARN, filter the lines via regexp, or replace the logger with your own class. Other suggestions welcome but most people seem ok with the current logging as is. I haven't seen much of any pushback.

**Comment by wspurgin** [comment]
Thanks @mperham I appreciate the suggestions and consideration. It is certainly a minor thing, and I'm fine with the custom class as a easily plugged solution. Thanks!
