### ISSUE TITLE
Batches Redis Memory Usage

### ISSUE THREAD

**Issue by mbbertino** [mperham/sidekiq#5063]
Since attempting to build a complex workflow with the "batches" features I'm seeing significant redis memory usage. 

<img width="1142" alt="Screen Shot 2021-11-16 at 3 19 18 PM" src="https://user-images.githubusercontent.com/6395112/142060600-6e39fc7d-7cfe-4d60-970e-9aa90cabb834.png">

``` ruby 
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
  config.periodic do |mgr|
    # crontab reference for the first argument https://crontab.guru/
    mgr.register('*/15 * * * *', 'Shopify::EnqueueStoreSyncsWorker') if Rails.env.production?
  end
end

# 

module Shopify
  class EnqueueStoreSyncsWorker
    include Sidekiq::Worker

    def perform
      max = Time.current
      min = max - 20.minutes

      ShopifyStore.active.pluck(:id).each do |shop_id|
        Shopify::StoreSyncWorker.perform_async(shop_id, min, max)
      end
    end
  end
end

#
module Shopify
  class StoreSyncWorker
    include Sidekiq::Worker
    sidekiq_options queue: :internal, retry: 0

    # https://medium.com/aaron-renner/building-workflows-with-sidekiq-batches-903937abccb0
    def perform(shop_id, min, max)
      ShopifyStore.find(shop_id).activate_gateway
      ShopifyAPI::Shop.current

      batch = Sidekiq::Batch.new
      batch.description = "Syncing #{shop_id} from #{min} to #{max}"
      batch.jobs do
        sync_orders(shop_id, min, max)
      end
    rescue ActiveResource::ClientError => e
      return if %w[404].include?(e.response.code.to_s)
      raise e unless %w[402 404].include?(e.response.code.to_s)

      Shopify::StoreSyncWorker.perform_in(1.day.from_now, shop_id, min, max)
    end

    def sync_orders(shop_id, min, max)
      orders_batch = Sidekiq::Batch.new
      orders_batch.description = "Syncing Orders for #{shop_id} from #{min} to #{max}"
      orders_batch.on(
        :success, "#{self.class}#sync_customers",
        { 'shop_id' => shop_id, 'min' => min, 'max' => max }
      )
      orders_batch.jobs do
        Shopify::SyncOrdersWorker.perform_async(shop_id, min, max)
      end
    end

    def sync_customers(_status, options)
      shop_id = options['shop_id']
      min = options['min']
      max = options['max']

      customers_batch = Sidekiq::Batch.new
      customers_batch.description = "Syncing Customers for #{shop_id} from #{min} to #{max}"
      customers_batch.jobs do
        Shopify::SyncCustomersWorker.perform_async(shop_id, min, max)
      end
    end
  end
end
```

Is this expected or am I doing something incorrectly?

**Version data:** 
Ruby version: 2.6.8
Rails version: 6.0.4
Sidekiq / Pro / Enterprise version(s):
    sidekiq-ent (2.2.3)
      einhorn (>= 0.7.4)
      sidekiq (>= 6.2.0)
      sidekiq-pro (>= 5.2.0)
    sidekiq-pro (5.2.4)
      sidekiq (>= 6.2.0)

**Comment by mperham** [comment]
How many jobs are in your batches?

**Comment by mbbertino** [comment]
When I queue up the `Shopify::EnqueueStoreSyncsWorker`

``` ruby 
module Shopify
  class EnqueueStoreSyncsWorker
    include Sidekiq::Worker

    def perform
      max = Time.current
      min = max - 20.minutes

      ShopifyStore.active.pluck(:id).each do |shop_id|
        Shopify::StoreSyncWorker.perform_async(shop_id, min, max)
      end
    end
  end
```

There around a few thousand of the `Shopify::StoreSyncWorker`s running and each of those will have 1 `Shopify::SyncOrdersWorker` and 1 `Shopify::SyncCustomersWorker `

**Comment by mperham** [comment]
Sounds like you might have 15k jobs or so.

Take a look a few jobs in the queue. How big is a random job payload?

**Comment by mbbertino** [comment]
We've tried to stick with the ids only mantra so hopefully it's not too bad. Heres are a couple of screenshots
<img width="1206" alt="Screen Shot 2021-11-16 at 4 01 04 PM" src="https://user-images.githubusercontent.com/6395112/142065010-25605535-c9c1-48cc-a303-b500229ffa36.png">
<img width="1337" alt="Screen Shot 2021-11-16 at 4 00 22 PM" src="https://user-images.githubusercontent.com/6395112/142064962-0c7dc122-57f3-4e35-b839-4bc8773f8784.png">
What do you think?

**Comment by mperham** [comment]
You can click into a job to see more context but you really need to go into
Redis itself and get the actual payload string. It’s possible you have some
middleware which is stashing some large value in the payload.

**Comment by mbbertino** [comment]
Hmmm, so I took a look into this and I'm not really seeing a place to click to see more context - is there a specific link that I'm missing? Is there a specific tab? Are you referring to the batches?

In terms of Redis - I've never debugged redis before so I installed RedisMonitor from RedisGreen. The only think that seems interesting to me it the memory map where 95% of the memory usage is being take up by "b-*" keys. 

<img width="1067" alt="Screen Shot 2021-11-17 at 8 17 58 AM" src="https://user-images.githubusercontent.com/6395112/142208020-b4423b84-b51f-41ef-9c92-12145c0e8227.png">

<img width="1467" alt="Screen Shot 2021-11-17 at 8 19 01 AM" src="https://user-images.githubusercontent.com/6395112/142208173-6c23ee1b-5111-4d8f-b336-0b2e7a166db6.png">


Are these the batches?

**Comment by mperham** [comment]
Sorry, I forgot you can't click a job in the queue. You can click a job in the Retry/Schedule set, click there and see the job details.

Yes, batches are prefixed with `b-`. Looks like you have a lot of batches in Redis. No single batch is dominating memory usage but when you create a batch, one Set stores every JID in the batch; that will be the biggest `b-` memory user. JIDs are 16 bytes, assuming two additional 64-bit pointers and 100,000 jobs means that one element will take at least 3.2MB. But by far the dominate memory user should be the actual job data itself in the queue. If a job takes 200 bytes, 100,000 jobs is ~20MB.

There are some notes here and suggestions for additional resources are always welcome.

https://github.com/mperham/sidekiq/wiki/Using-Redis#notes

**Comment by mbbertino** [comment]
Ah, thanks for the clarification on the details. 

Here's a sample one from the schedule set 
<img width="1227" alt="Screen Shot 2021-11-17 at 11 57 53 AM" src="https://user-images.githubusercontent.com/6395112/142246224-b6e1d394-f0c4-4ff6-847f-6e0949772617.png">

In regard to the memory map, so I think I'm following but I've got a follow-up question: If B Keys are taking up 95%  of used memory (at the time of this 167.31 MB) wouldn't that mean that each of the b-keys are much larger than 16 bytes? At this point it says there are 204K "b-*" keys which would mean each of them is actually 820.15 bytes (if my math is right). This seems similar with the Largest Keys list I'm seeing 

<img width="420" alt="Screen Shot 2021-11-17 at 12 08 48 PM" src="https://user-images.githubusercontent.com/6395112/142248048-e953dc34-74da-402a-9717-43c6e3dd367e.png">

One of those says it's storing 8 elements
<img width="559" alt="Screen Shot 2021-11-17 at 12 09 36 PM" src="https://user-images.githubusercontent.com/6395112/142248180-7ed71c57-9a6d-4d86-85e9-1691fe6073f6.png">

**Comment by mperham** [comment]
Right, the main batch data structure is that Hash which tracks the metadata for the batch. There is a separate Set for the JIDs and a few other separate elements, all named "b-#{bid}-#{suffix}", e.g.

```ruby
              "b-#{bid}-failinfo",
              "b-#{bid}-notify",
              "b-#{bid}-cbsucc",
              "b-#{bid}-success",
              "b-#{bid}-complete",
   ```

The JIDs and any failure info will consume the most memory.

So far I'm not seeing any bugs, it looks like you just have a lot of batches in Redis somehow. If you are testing and clearing queues after each test run, make sure you flush the entire Redis database with FLUSHDB. Clearing the job queue only will orphan the batch data, meaning it will take 30 days to expire. That's one way you can get a lot of batch data sitting around.

**Comment by mbbertino** [comment]
Got it. Thanks for the further details. I think that helps me wrap my mind around it. 

I probably can't use the FLUSHDB since this is what's happening in Production. That said, I thought the deadset commands mentioned [here](https://github.com/mperham/sidekiq/wiki/Batches#death) would've cleared out all the other batch information. 

But if I'm understanding correctly that means that the successfully completed ones are still sitting there for 30 days. Is that right?

Like you said it doesn't sound like a bug so I'm going to close this.

**Comment by mperham** [comment]
As batch jobs are successfully processed, the batch's memory usage should go down rapidly.  The job is discarded and its JID removed from the batch's JID set. If you see that memory spike go down rapidly, that's what's happening. Successful batches are removed from Redis completely. But if any jobs fail and linger in Redis, the batch data will remain, including any failure info. Typically that will be a small number of jobs and so the remaining batch data should be small too.
