### ISSUE TITLE
Darkmode is broken on Firefox

### ISSUE THREAD

**Issue by deneuxa** [mperham/sidekiq#5067]
On firefox :

<img width="1883" alt="image" src="https://user-images.githubusercontent.com/359847/142986801-a8a64f25-b36a-45f5-ad2a-072d682d3d06.png">

=> you can see that the links on the top-main menu are too dark, also colors and text on some buttons are not correct

<img width="1887" alt="image" src="https://user-images.githubusercontent.com/359847/142986839-79af36a3-0ec1-49d8-8d8c-19b22ca9d520.png">

=> the backgrounds on the table are incorrects

Same screens on Safari for example : 

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/359847/142986895-9da36570-7beb-42bf-9a00-13749fcdcfab.png">

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/359847/142989202-be4d6691-6265-4762-8a66-911853cb4f2f.png">

I think Firefox load some default HTML CSS for elements like body, table, buttons.
These CSS rules need to be overwritten by the Sidekiq's CSS.

**Comment by mperham** [comment]
Does 6.3.1 work better? It looks fine for me on Firefox.

**Comment by deneuxa** [comment]
I just made a try.
Same problem :/

I am using firefox 94.0.2 (64 bits) on MacOs.


Le mar. 23 nov. 2021 à 21:35, Mike Perham ***@***.***> a
écrit :

**Comment by deneuxa** [comment]
hello,
any update here ?

**Comment by mperham** [comment]
No one's working on this. Until someone can tell me how to reproduce it, I can only assume the problem is in your local browser configuration. Extensions, custom userstyles, etc.

**Comment by brandonhilkert** [comment]
Sidekiq Pro 5.2.0 / 6.2.1 looks fine here

<img width="1305" alt="Screen Shot 2022-01-17 at 4 16 01 PM" src="https://user-images.githubusercontent.com/744212/149850281-dde97057-ef55-4893-865d-9ffab4912fc7.png">

**Comment by deneuxa** [comment]
this is so weird
Are you using firefox on Mac OS also ?



Le mar. 18 janv. 2022 à 01:17, Brandon Hilkert ***@***.***> a
écrit :

**Comment by brandonhilkert** [comment]
Yes. Just updated to Sidekiq 6.3.1 and same result. Do you have any extensions installed in Firefox?

**Comment by delphaber** [comment]
Maybe a cache problem? I had a similar problem in production: it was cloudflare caching the old css :)

**Comment by mperham** [comment]
No one can reproduce, assuming this is a local issue.
