### ISSUE TITLE
Sidekiq batch on_success callback fire prematurely

### ISSUE THREAD

**Issue by junjianglin** [mperham/sidekiq#5068]
Ruby version: 2.7.2
Rails version: 6.0.4.1
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 4.0.5

We are running into a problem that on_success callback is fired before all the batch jobs finish. One symptoms is that some of the jobs are not finished and re-enqueued with a different job id. The on_success callback is fired after all original jobs are processed (in log it starts performing each job). However, many jobs may not finish and get re-enqueued with a different job id. Those seems to be independent and outside of the batch control. Eventually all of the batch jobs will finish but our downstream job could not behave correctly by relying on the on_success callback. 

Do you have any ideas and potential suggestions I can try?
Thanks!

Below is the rough code framework we use to run our batch job. And BTW does SideKiq callback has any conflicts with ActiveJob::Callbacks?
```
class BaseCollectionJob
    include ::ActiveJob::Callbacks
    include ::ActiveSupport::Rescuable
    include ::Sidekiq::Worker
    include ::ActiveJob::Logging

    def perform(*args)
        if args.present?
          perform_one(*args)
        else
          perform_all
        end
      end

      def perform_one(_item)
        raise NotImplementedError
      end

      def perform_all
          class_name = self.class.name
          batch = Sidekiq::Batch.new
          batch.description = class_name
          batch.on(:success, "#{class_name}#on_batch_success") if respond_to?(:on_batch_success, true)
          batch.on(:complete, "#{class_name}#on_batch_complete") if respond_to?(:on_batch_complete, true)
          batch.jobs { enqueue_collection }
      end

      def enqueue_collection
          collection.each { |item| enqueue_one(item) }
      end

      def enqueue_one(item)
          self.class.perform_later(item)
    end`

```

```
  class TestCollectionJob < BaseCollectionJob
    def on_batch_success(_status, options)
      puts "checkpoint: on success "#{DateTime.now}"
      # upload_finished_file_to_s3
    end

    def perform_one(options)
      #do something
      puts "some operation"
    end

    def collection
      array = (1..10000).to_a
    end
  end

```
And the job is simply ran as 
```
TestCollectionJob.perform_now
```

**Comment by mperham** [comment]
You cannot “requeue the same job with a different job Id”. That’s just a different job.

if you create another job, you have to add it to the batch if you wish for the batch to wait for it. The wiki covers how to reopen the batch and add more jobs to it.

**Comment by junjianglin** [comment]
@mperham 
Thanks for the reply! My intention is not to re-enqueue jobs. 
I think SideKiq somehow does that.

My intention is to just run all the batched jobs and have a on_success callback. But from my observations, some of the jobs are not finished before on_success fire. Those jobs somehow get re-generated with different job id but same argument.

Below is a logging example:

job102 (arg2) =>  start and finish, this job has the same arg as job2, and it is auto-generated with a different Job id. 
on_success fire
job100 (arg100) start and finish
...
job3 (arg3) start and finish
job2 (arg2) start but not finish
job1 (arg1) start and finish

**Comment by mperham** [comment]
Sidekick does not re-enqueue any jobs with a different job ID. If that is happening to you it is possible that a third-party gem is doing it. You will need to figure out where job102 is created.

**Comment by junjianglin** [comment]
@mperham 
I see, thank you so much!
Just want to understand more about the batch callback.
In above situation job2 is not finished, but why on_success still fires? What kind of events will trigger the on_success callback?

**Comment by mperham** [comment]
Job2 is finished. I suspect your system is not letting it become a retry.
Are you using ActiveJob error handling?

**Comment by junjianglin** [comment]
Yes. I checked the log again, and it is interesting that job2 does finish with a success signal, but it does not actually perform the work. And another job with same args get enqueued, and have the same situation as job2, then eventually job1002 come in with same args as job2 and finish the actual work. Will this be related to memory/resource? I do see "Bounded Memory" error all the time and sideKiq seems to restart itself.

**Comment by junjianglin** [comment]
Some further deep dive shows that this is due to concurrency. 
In above example, job2 is re-enqueue in Xs (for example 100s), then it get re-enqueue as job102. When the re-enqueue operation performed, the job2 is somehow marked as success. That lead to the early on_success firing

**Comment by junjianglin** [comment]
Actually last question,
How the Sidekiq batch determines that all the child jobs are success?

**Comment by mperham** [comment]
If a job does not raise an error, it was a success.

**Comment by junjianglin** [comment]
Does the "success" signal get stored somewhere (like redis) and read by the batch in the end?

**Comment by mperham** [comment]
Do you know that you can just read the batch code? `bundle open sidekiq-pro`

**Comment by junjianglin** [comment]
okay, thanks!
