### ISSUE TITLE
Sidekiq's reliable push not recovering jobs

### ISSUE THREAD

**Issue by altjx** [mperham/sidekiq#5069]
Hey @mperham,

Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
Rails version: 6.1.4
Sidekiq v6.3.0 / Sidekiq Pro v5.2.4

Just want to first and foremost say thanks so much for your amazing work on this gem. I have a very interesting issue that keeps occurring and I can't quite pinpoint if it's the gem that has an issue or if it's just the way I'm actually expecting it to work.

For example, I have Sidekiq containers in AWS EC2 instances and there are 2 instances where Sidekiq may be interrupted:

1. If AWS sends a 2-minute warning signal to terminate my EC2 instance since we're using AWS Spot Instances
2. If we push code changes to production and codepipeline spins up a new sidekiq container after codebuild finishes.

Now with that being said, there are a few rare cases where I actually have a `binding.pry` in just a few workers that will trigger (along with sending a message to Slack) in these cases where I only have a limited amount of time to troubleshoot a bug in production before the data gets removed. However, I notice that if the worker is sitting at `binding.pry` and the container is unexpectedly terminated (due to one of the 2 reasons above), the new container that spins up doesn't actually re-run the job that was interrupted from the first container.

Is there something in the Sidekiq container that is keeping track of the reliability (like is this being tracked in a local file somewhere)?

Only other possible reason I can think of is that we're spinning up a new Sidekiq container before the 1st one is killed to minimize impact in production. If so, would this be why the second container isn't picking up the job that was interrupted from the first container?

Sorry if I'm misunderstanding this.

**Comment by mperham** [comment]
Could you please supply the info the issue template asks for? Behavior is version and feature dependent.

**Comment by altjx** [comment]
Updated original post. Sorry about that @mperham

**Comment by mperham** [comment]
It’s the super_fetch feature which recovers jobs which started but never finished. Did you enable it? It can also take an unpredictable amount of time to recover; it won’t recover them within minutes.

**Comment by altjx** [comment]
Yep I have it enabled in `config/initializers/sidekiq.rb`:

```
Sidekiq::Client.reliable_push! if Rails.env.production?
Sidekiq.configure_server do |config|
  config.death_handlers << lambda { |job, err|
    options = {
      color: '#FF0000',
      title: ':fire: Worker Crash Alert!',
      text: "`#{job['class']}` crashed with the following error message: \n```#{err.inspect}````",
      attachment: true
    }
    SlackBot.new.send_message(options)
  }

  if Rails.env.production?
    # Sidekiq Pro
    config.super_fetch!
    config.reliable_scheduler!
  end
end
```

**Comment by mperham** [comment]
And you find that these jobs are still missing days later? Are you giving them time to be recovered? The job should be recovered hours or days later, not immediately.

**Comment by altjx** [comment]
Yep, in fact I notice that several days later some of the previous jobs that would have triggered other jobs didn't trigger those jobs because the first job wasn't resumed. For days later, I think that would be a pretty big impact to performance for us. Is there anything that we can do or configure to decrease the time window for resuming jobs by chance?

**Comment by mperham** [comment]
The orphan job scan runs when you start a new Sidekiq process, up to once
an hour. So if you are deploying multiple times per day, it will scan. If
you aren’t deploying or restarting your processes often, it won’t rescue
those lost jobs often.

**Comment by altjx** [comment]
Got it. Thanks @mperham. Going to keep an eye out on this.

**Comment by altjx** [comment]
Hey @mperham,

I just realized what's going on. Our infrastructure deploys a 2nd sidekiq instance when pushing updates and, after it detects sidekiq instance 2 running, it shuts down sidekiq instance 1, which causes interruptions (not that often but often enough). However, since sidekiq instance 2 is already running, it's not trying to "recover" anything per se. It only happens whenever I restart sidekiq.

Have two quick questions:

1. Is there anyway sidekiq can lookout for failed jobs from another sidekiq instance while it's currently running
2. Is there a "safe" way to handle this if the above can't happen? Not sure if I should schedule some kind of job to auto restart sidekiq every few hours to be on the safe side or something.

**Comment by mperham** [comment]
Each Sidekiq process, on start, tries to recover lost jobs **as long as** the recovery process has not been run in the last hour. It is typical to reboot Sidekiq instances daily to deal with any memory bloat or leaks. This reboot would recover any jobs lost that day too.

Jobs are orphaned due to crashed or killed Sidekiq processes. You should focus on determining why your jobs are being lost. What is killing your Sidekiq processes?

**Comment by altjx** [comment]
Got it. We're using spot instances for sidekiq and so when CloudWatch sends the 2-minute termination warning, we have a process that spins up another spot instance with sidekiq running on it. it's usually up and running within 30-45 seconds, so by the time the 1st sidekiq instance terminates, the 2nd one is running.

**Comment by mperham** [comment]
That doesn’t matter. You can have 1000 processes running but if you start a
1001th and no one else has recovered in the last hour, 1001 will run the
recovery process.

**Comment by altjx** [comment]
Yeah exactly. The issue here though is sidekiq2 stands up before sidekiq1 gets interrupted, so technically sidekiq2 starts and there's nothing to recover. Sidekiq1 doesn't "fail" or get interrupted until a minute or so after sidekiq2 stands up. Since we're not restarting sidekiq until code changes, I realize they're getting recovered sometimes a week later whenever we push out a new sidekiq instance.

If a job fails in queue `XYZ` and I start sidekiq for queue `abc123` does it recover jobs that failed in `xyz` and send it to that queue? If so, I may just be able to simply create a task to start/stop sidekiq in a random tmux window for the sake of recovering failed jobs.

Does that make sense?

**Comment by mperham** [comment]
The recovery process find any jobs in any queues that don’t have a process
record in Redis. The process record expires after 60 seconds without a
heartbeat. But again the fundamental question is why are your processes
dying?

**Comment by altjx** [comment]
Gotcha. Because AWS is killing the container with the 2 minute warning. So if a ton of sidekiq jobs are running for 5 seconds and AWS kills the container 2-3 seconds into a job, it's dead.

**Comment by mperham** [comment]
You should send the TSTP or TERM signal upon the 2 minute warning.

**Comment by altjx** [comment]
Got it. Yep that's in the roadmap now that we've started investigating this further. Good to know that's your suggestion as well. I really appreciate it Mike as always man!!
