### ISSUE TITLE
[Proposal] Primitive Checks for Job Args

### ISSUE THREAD

**Issue by kellysutton** [mperham/sidekiq#5070]
The goal of this issue is to propose what runtime arg-checking might look like for Sidekiq. If it's interesting, I can put together a PR implementing things.

Essentially, we'd encode Sidekiq's [first best practice of making job parameters "small and simple."](https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple)

Here's the sketch:

- On every set of args, run the check snippet (below)
- This would be configurable per-environment, so that we can fail in dev/test but pass-through and warn in production.
- We'd need to make sure this wouldn't add undue performance overhead.
- By making it configurable, this also opens the option of changing the default in a future major version of Sidekiq. (It would be a breaking change.)
- (Optional) Provide a callback when a complex argument is received.

**Snippet:**

```ruby
# any time we get `args`
klasses = [String, Numeric, TrueClass, FalseClass, NilClass] # would be stored in a constant somewhere
args.each do |arg|
  if klasses.none? { |klass| arg.is_a?(klass) }
    if Sidekiq.raise_on_complex_arguments
      raise Sidekiq::ComplexArgumentError
    else
      Sidekiq.logger.warn "Receive a complex argument"
    end
  end
end
```

That's the sketch. We've been bitten by this a few times as we've scaled where the documentation and knowledge of it is not evenly distributed, but Sidekiq usage is.

**Comment by sobrinho** [comment]
@kellysutton would you create a PR?

**Comment by kellysutton** [comment]
Yep, I'll try to put something together this week. Thanks!
