### ISSUE TITLE
Sidekiq 6.3.1 UI can't stop polling & can't add scheduled jobs to queue

### ISSUE THREAD

**Issue by netwire88** [mperham/sidekiq#5078]
Ruby version: 3.0.3
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.3.1

When we upgrade Sidekiq from 6.2.1 to 6.3.1, we can no longer add a scheduled job to queue via UI. When we looked deeper, it looks like the page is refreshing often and we can't select a job before it gets deselected again. When we tried to click "Stop Polling", nothing happens and the page continues to refresh.

**Comment by mperham** [comment]
A few people have reported issues but I can’t reproduce the problem. Can you tell me what browser and version you are using?

**Comment by netwire88** [comment]
Thanks @mperham , I'm using Chrome 96.0.4664.55

**Comment by mperham** [comment]
I believe sidekiq defaults to caching its assets for 24 hours in the browser. If you literally just upgraded today it might quietly fix itself tomorrow.
