### ISSUE TITLE
Parallel questions 

### ISSUE THREAD

**Issue by dortin42** [mperham/sidekiq#5079]
Hi, I'm running some tests with ActiveJob Rspec, Parallel gem https://github.com/grosser/parallel and Sidekiq of course, putting jobs inside Parallel with any in_processes value than 0, makes jobs not to queue, my question is, is this intended in sidekiq or it's a Parallel bug? What happens if my server receives multiple requests queueing 2 or more jobs at the same time?

**Comment by mperham** [comment]
> Hi, I'm running some tests with ActiveJob Rspec, Parallel gem https://github.com/grosser/parallel and Sidekiq of course, putting jobs inside Parallel with any in_processes value than 0, makes jobs not to queue, my question is, is this intended in sidekiq or it's a Parallel bug?

I don't know because I don't know why it's not queuing. In test mode, jobs often don't queue depending on your test config.

> What happens if my server receives multiple requests queueing 2 or more jobs at the same time?

They both should queue in Redis, in a non-deterministic order.
