### ISSUE TITLE
Using Sidekiq::Worker.set does not work with symbol keys when using #perform_bulk

### ISSUE THREAD

**Issue by danarnold** [mperham/sidekiq#5081]
Ruby version: 2.7.3p183
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): sidekiq 6.3.1, sidekiq-pro 5.3.0

I was updating some code that previously used push_bulk to use perform_bulk instead when I came across this issue. The code in question schedules workers dynamically into different queues. So, when writing the scheduling code using perform_bulk, I updated it to use `set(queue: queue_name)` as the [announcement shows](https://www.mikeperham.com/2021/11/07/whats-new-in-sidekiq-6.3/#bulk-perform). 

So, the new code looked like this:

```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  ExampleWorker.set(queue: "example").perform_bulk(array_of_args_arrays)
end
```
Once I started testing this code, I noticed that the workers were being scheduled into our default queue instead of the specific queues they should have gone into. When investigating this issue, I took a look at where Sidekiq::Worker.set is defined and made an extremely superficial analysis of the underlying code. I noticed that Sidekiq::Setter#set runs `@opts.merge!(options)`, which presumably would merge in the symbol key of `:queue`, and then I noticed that elsewhere, @opts keys were being accessed as strings. On a hunch, I decided to try changing `queue` to a string to see if it being merged into @opts as a string would solve the issue. I didn't really expect it to make a difference, but it actually did fix the issue. The current code, which looks like this, properly puts the workers into their queues:

```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  ExampleWorker.set("queue" => "example").perform_bulk(array_of_args_arrays)
end
```

I then tried changing the code to use a standard perform_async instead of perform_bulk and to queue each worker individually, like so:

```ruby
batch = Sidekiq::Batch.new
batch.jobs do
  jobs_to_queue.each do |job|
    ExampleWorker.set(queue: "example").perform_async(job[:args])
  end
end
```

This worked as expected, putting the workers into the correct queues. Therefore, I concluded that the string/symbol key issue is exclusive to perform_bulk.

I've included the batch creation code around the examples I've given because these workers are executing in a batch. I don't actually think it's related to them being in batches, but I also can't say it isn't, so I've included the batch code in the interest of including as much context as possible.

**Comment by mperham** [comment]
Sounds like we forgot a `stringify_keys` somewhere. PRs welcome.
