### ISSUE TITLE
Sidekiq::Pro.dogstatsd breaks in lib/sidekiq/pro/metrics.rb because there is no :: before Datadog::Statsd

### ISSUE THREAD

**Issue by weijenlarryli** [mperham/sidekiq#5083]
Ruby version: 2.6.3
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 5.3.0

When I use `Sidekiq::Pro.dogstatsd = -> { Datadog::Statsd.new(some_params) }`
lib/sidekiq/pro/metrics.rb breaks at `unless Datadog::Statsd.instance_methods.index(:batch)` in class Dogstatsd initialize

The error is `NameError: uninitialized constant Sidekiq::Datadog::Statsd`
It seems Datadog::Statsd is used without "::" before Datadog. So rails picks the wrong class.

**Comment by mperham** [comment]
This works fine for me.

```ruby
require 'datadog/statsd'
Sidekiq::Pro.dogstatsd = -> { Datadog::Statsd.new }
```

**Comment by weijenlarryli** [comment]
I think rails gets confused by `sidekiq-pro and sidekiq-datadog`
I see this NameError when I have both `sidekiq-pro and sidekiq-datadog` in my Gemfile.

**Comment by mperham** [comment]
I don’t know what sidekiq-datadog is and don’t support it.
