### ISSUE TITLE
Redis.info current policy not detected

### ISSUE THREAD

**Issue by sarodspirit** [mperham/sidekiq#5086]
Ruby version: 3.0.3p157
Rails version: Rails 6.1.4.1
Sidekiq / Pro / Enterprise version(s):
sidekiq-pro5.2.4

The 'noeviction' maxmemory policy is recommended (current policy: '').

This happens with eviction policy set to volatile-lru on Redis-Enterprise-Cloud in Heroku
Redis version 6.0.9

**Comment by mperham** [comment]
Can you show me the full Redis INFO output?

**Comment by sarodspirit** [comment]
`{"redis_version"=>"6.0.9",
 "redis_git_sha1"=>"00000000",
 "redis_git_dirty"=>"0",
 "redis_build_id"=>"0000000000000000000000000000000000000000",
 "redis_mode"=>"standalone",
 "os"=>"Linux 5.4.0-1051-aws x86_64",
 "arch_bits"=>"64",
 "multiplexing_api"=>"epoll",
 "gcc_version"=>"7.5.0",
 "process_id"=>"7463228",
 "run_id"=>"37278d06bac0c36a66a7f95500b5c3ffa173e799",
 "tcp_port"=>"18103",
 "uptime_in_seconds"=>"244566003",
 "uptime_in_days"=>"2830",
 "hz"=>"10",
 "lru_clock"=>"0",
 "config_file"=>"",
 "connected_clients"=>"391",
 "client_longest_output_list"=>"0",
 "client_biggest_input_buf"=>"0",
 "blocked_clients"=>"22",
 "used_memory"=>"1054058256",
 "used_memory_human"=>"1005.22M",
 "used_memory_rss"=>"1054058256",
 "used_memory_peak"=>"8394904312",
 "used_memory_peak_human"=>"7.81G",
 "used_memory_lua"=>"65536",
 "mem_fragmentation_ratio"=>"1",
 "mem_allocator"=>"jemalloc-5.1.0",
 "loading"=>"0",
 "rdb_changes_since_last_save"=>"13057573309",
 "rdb_bgsave_in_progress"=>"0",
 "rdb_last_save_time"=>"1625393041",
 "rdb_last_bgsave_status"=>"ok",
 "rdb_last_bgsave_time_sec"=>"0",
 "rdb_current_bgsave_time_sec"=>"-1",
 "aof_enabled"=>"1",
 "aof_rewrite_in_progress"=>"0",
 "aof_rewrite_scheduled"=>"0",
 "aof_last_rewrite_time_sec"=>"-1",
 "aof_current_rewrite_time_sec"=>"-1",
 "aof_last_bgrewrite_status"=>"ok",
 "aof_last_write_status"=>"ok",
 "aof_current_size"=>"0",
 "aof_base_size"=>"0",
 "aof_pending_rewrite"=>"0",
 "aof_buffer_length"=>"0",
 "aof_rewrite_buffer_length"=>"0",
 "aof_pending_bio_fsync"=>"0",
 "aof_delayed_fsync"=>"0",
 "total_connections_received"=>"161970",
 "total_commands_processed"=>"4020043741",
 "instantaneous_ops_per_sec"=>"397",
 "total_net_input_bytes"=>"2984459417623",
 "total_net_output_bytes"=>"6122182379768",
 "instantaneous_input_kbps"=>"34.14",
 "instantaneous_output_kbps"=>"26.11",
 "rejected_connections"=>"0",
 "sync_full"=>"0",
 "sync_partial_ok"=>"0",
 "sync_partial_err"=>"0",
 "expired_keys"=>"46470148",
 "evicted_keys"=>"257989",
 "keyspace_hits"=>"4557264305",
 "keyspace_misses"=>"4348997219",
 "pubsub_channels"=>"0",
 "pubsub_patterns"=>"13",
 "latest_fork_usec"=>"0",
 "migrate_cached_sockets"=>"0",
 "role"=>"master",
 "connected_slaves"=>"0",
 "master_repl_offset"=>"0",
 "repl_backlog_active"=>"0",
 "repl_backlog_size"=>"1048576",
 "repl_backlog_first_byte_offset"=>"0",
 "repl_backlog_histlen"=>"0",
 "used_cpu_sys"=>"0.00",
 "used_cpu_user"=>"0.00",
 "used_cpu_sys_children"=>"0.00",
 "used_cpu_user_children"=>"0.00",
 "cluster_enabled"=>"0",
 "db0"=>"keys=288165,expires=10719,avg_ttl=1606530082"}
`

**Comment by mperham** [comment]
Sounds like's Heroku's offering has a bug. They should list the memory policy in the INFO output like normal Redis.
