### ISSUE TITLE
Cleanup logic not always executed by threads

### ISSUE THREAD

**Issue by teckwan** [mperham/sidekiq#5095]
Ruby version: 2.7.4
Rails version: 6.1.3
Sidekiq / Pro / Enterprise version(s): Sidekiq (6.2.2) Pro (5.2.0)

Hello,
My organization leverages extensive use of Sidekiq and we have been very satisfied with how it has been performing.
We have however recently came across an issue. Our stack is deployed on Heroku, and due to business logic necessities,
some of our job classes have clean-up logic integrated(light operations such as deleting a redis key) to assure
graceful exit in case of dyno restarts or redeployments.

Most of our clean-up logic goes by the form of :
```ruby
def perform
  # do stuff
rescue SignalException
  # clean up
  raise
end
```

We have however noticed that this logic is not always run. Through investigation, we found out that this is due to
how Sidekiq exits. On `hard_shutdown`, `Sidekiq::Shutdown` is raised in the threads and `exit(0)` is called afterwards
without waiting for the threads to respond to this error. Some threads are then killed before it can handle the `Sidekiq::Shutdown`.
I’m wondering if it is possible to have a configuration to allow waiting for the response of these threads before exiting
(with the existence of the `wait` parameter in `#kill`), or if you have a better idea on handling job-specific graceful exit logic.

**Comment by mperham** [comment]
Use “ensure” to cleanup?

**Comment by teckwan** [comment]
@mperham this isn't sufficient. A simple example to illustrate:
```ruby
Thread.fork do
ensure
  sleep 10
  puts "clean up"
end

exit(0)
```
"clean up" isn't printed to the console, the threads are killed.

**Comment by mperham** [comment]
Well, yeah. Sidekiq gives threads 5 seconds to cleanup by default. `ensure` isn't at fault here, `sleep 10` is.

**Comment by teckwan** [comment]
There is a default timeout of 25 seconds between when `Sidekiq::Manager#stop` is called and when `Sidekiq::Manager#hard_shutdown` is called. The `Sidekiq::Shutdown` error is raised only when `hard_shutdown` is invoked. Between `hard_shutdown` and `exit(0)`, there does not seem to be a time given for threads to cleanup. I could not find the part where Sidekiq gives threads 5 seconds to cleanup as the `exit(0)` is just after the `raise` for the threads. @mperham

**Comment by mperham** [comment]
`exit` waits for all threads to unwind. Sidekiq raises the Shutdown exception at 25 and Heroku/systemd kills the process at 30, that's the 5 seconds.

**Comment by teckwan** [comment]
Thanks for the explanation.

> `exit` waits for all threads to unwind.

This does not seem to be the case. From what I understand, `exit` does not wait for `ensure` blocks to finish execution. This is reproduced in the following example :

```ruby
th = Thread.fork do
  sleep 100
ensure
  puts "clean up"
end

th.raise StandardError
exit(0)
```

"clean up" is never printed (with or without the `sleep 100`). @mperham

**Comment by mperham** [comment]
You don't need to explicitly @ me. I'm quite literally paid to monitor this project and its issues.

I will investigate a bit today.

**Comment by teckwan** [comment]
Sorry about that, I'm not quite used to creating issues.. Kind of new around here. Thanks for the tip! And the investigation as well :)

**Comment by mperham** [comment]
Try that and see if it behaves better for you.

**Comment by PikachuEXE** [comment]
So what's the recommended or possible way(s) to cleanup in a job now (with latest version released)?

**Comment by mperham** [comment]
Use an ensure block like normal. 6.4.0 should have better behavior.

**Comment by jarthod** [comment]
For the record, this is what we reported a couple years ago in #4101 and had to write a monkey patch on our end. Good to know it's now in main branch ! cc @ylecuyer @cedricbm
