### ISSUE TITLE
Question: What is the difference in test my job directly and testing inline?

### ISSUE THREAD

**Issue by CaioFML** [mperham/sidekiq#5096]
Hello, guys!

I have a question about testing my job directly, I saw this two topics on the docs: [testing workers directly](https://github.com/mperham/sidekiq/wiki/Testing#testing-workers-directly) and [Testing workers inline](https://github.com/mperham/sidekiq/wiki/Testing#testing-workers-inline)

Following the first example, I test my job directly taking my job, getting a new instance and calling `.perform`, ex:

```ruby
  subject(:perform) { described_class.new.perform(args) }
   
  it do
    perform

    expect(...).to something(...)
  end
```

But the part of [testing workers inline](https://github.com/mperham/sidekiq/wiki/Testing#testing-workers-inline) caused me to be confused because I understood that this code above could be write in that way:

```ruby
  subject(:perform) { described_class.perform_async(args) }

  before { Sidekiq::Testing.inline! }

  it do
    perform

    expect(...).to something(...)
  end
```

So, there is any difference? I think the first one is less verbose and with test the behavior of the job, but in the second we enqueued the job and it's immediatly executed with the `Sidekiq::Testing.inline!`, this is more close to the entire behavior on the application, but testing if the job was enqueued from where is called the `MyJob.perform_async(args)` already checks that behavior or I misunderstood something?

@mperham

**Comment by mperham** [comment]
inline will marshal the arguments through JSON, so you'll get a more accurate set of arguments to `perform` as it would look in production.
