### ISSUE TITLE
Do not queue jobs?

### ISSUE THREAD

**Issue by wojciech-rzepecki** [mperham/sidekiq#5097]
If is it possible to not queue jobs and just fetch jobs from Redis only if there are free threads that will instantly execute jobs?

I am asking because I would like to run Sidekiq with App Engine in Google Cloud that would be increase instances based on load demand, but need to sure to not queue jobs to instance where currently there are full threads used. If I did not explain it clearly, please give me feedback I will try again with other words :smile:

**Comment by mperham** [comment]
There is no way to do this. Queues are designed to back up during busy times. You can use tools like Rails Autoscale to handle an increase in traffic.

**Comment by wojciech-rzepecki** [comment]
@mperham Thanks for answer, but there will be race between two sidekiq instances for fetching jobs to queue from Redis right? For example I have very long queue and in some way I am scaling Sidekiq by add new instance, and now that busy Sidekiq instance still will be racing with new instance for fetching jobs right?

**Comment by mperham** [comment]
Yes, they will both pull and execute jobs at the same time.
