### ISSUE TITLE
Failed messages not going to the retries and dead queues

### ISSUE THREAD

**Issue by ctobon** [mperham/sidekiq#5098]
Hello, we haven't changed our Sidekiq configuration in at least a year but we've experiencing this issue for a few months now. 

Failed messages were previously going to the retries queue and, after a number of retries, going to the dead queue. From the dead queue we were able to retry them, as needed. However, failed messages are not making it to the retries queue and perhaps for that reason not making it to the dead queue either. Perhaps due to the version of Sidekiq we use, we're not able to see the contents of the failed queue.

Can you please help us diagnose why failed messages are not making it to the retries queue?

Regards,
Carolina 

Ruby version: 2.6.6p146
Rails version: 6.0.4
Sidekiq / Pro / Enterprise version(s): v6.1.2

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
---
:concurrency: 5
beta:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - mailers
  - active_storage_analysis

--------------------

**Comment by mperham** [comment]
Show me

* the output of `redis-cli info` on your Redis instance
* the counts at the top of the Web UI
* any initializer you have
* the output of `sidekiq -v` on startup so I can see the global `Sidekiq.options`

Do you see any backtraces in the logs?
