### ISSUE TITLE
Sidekiq::Pro::Web and "name"

### ISSUE THREAD

**Issue by samsm** [mperham/sidekiq#5099]
Hello!

Noticed a hiccup when dynamically creating `Sidekiq::Pro::Web`s for use in routes.

Was taking this sort of workflow (which works):
```ruby
POOL1 = ConnectionPool.new { Redis.new(:url => "redis://localhost:6379/0") }
mount Sidekiq::Pro::Web.with(redis_pool: POOL1), at: '/sidekiq1', as: 'sidekiq1' # shard1
```

... and making it something like this:

```ruby
OurCode::Engine.routes.draw do
  constraints RouteConstraints do
    sidekiq_configuration.pools.each_pair do |name, pool|
      mount Sidekiq::Pro::Web.with(redis_pool: pool), at: "/#{name}", as: 'name'
    end
  end
end

```

This was getting us an unexpected error deep in Rails routing:
```
~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/mapper.rb:674:in `app_name': undefined method `tr' for nil:NilClass (NoMethodError)
```

The issue seemed to be a lack of `name` on the class generated by `Sidekiq::Pro::Web.with`. After patching a name onto that generated class, things seemed to work fine. 

I'm not clear on why this is needed in our situation, but this reminds me strongly of:
```ruby
Foo = Class.new
Foo.name == "Foo"

foo = Class.new
foo.name == nil
```

Thanks for reading! If you would like an example of this happening I could probably create one.

**Comment by mperham** [comment]
You'll need to give me more. These two codepaths look identical, save for the typo around 'name'.

```ruby
mount Sidekiq::Pro::Web.with(redis_pool: POOL1), at: '/sidekiq1', as: 'sidekiq1' # shard1
mount Sidekiq::Pro::Web.with(redis_pool: pool), at: "/#{name}", as: 'name'
```

**Comment by samsm** [comment]
Here's an example in a fresh Rails app ... it required more tweaking than I expected to reproduce!

https://github.com/samsm/sidekiq_pro_web_ui_name/blob/main/config/initializers/sidekiq_dynamic.rb

If you run `rails server` if should raise an exception as described above. If you uncomment the `define_singleton_method` line, it will boot and work fine.

Hope that helps!

**Comment by mperham** [comment]
The issue is that you are trying to remove the `as` attribute. If you do this, Rails tries to mount it based on the app's class name which Sidekiq Pro does not have because `with` creates the Rack app dynamically. `as` is required.  This works fine:

```diff
 SidekiqDynamic.routes.draw do
   require 'sidekiq/pro/web'
   SidekiqDynamic.webs.each_pair do |name, web|
-    mount web, at: "/#{name}"
+    mount web, at: "/#{name}", as: name
   end
 end
```
