### ISSUE TITLE
[Question] Possible to grab 'tags' within Sidekiq Worker

### ISSUE THREAD

**Issue by OskarEichler** [mperham/sidekiq#5102]
Hey Mike,

We are starting to make use of the 'tags' feature, and it's awesome to keep track of where a certain job got scheduled at. 

My question is - does the worker have access to its own tags? We tried calling sidekiq_options_hash, but it doesn't seem to return the tags.

Reason we would be interested in having access to them is to pass them onto the next worker if there is a chain of jobs, so that we can backtrace its origin.

**Comment by mperham** [comment]
Nope, workers only have direct access to args. Use Rails’s
CurrentAttributes to read/write a request_id or origin tag. See the change
notes for Sidekiq 6.3.0.

**Comment by OskarEichler** [comment]
Ahh perfect, thank you Mike! Appreciate the swift response!
