### ISSUE TITLE
[sidekiq-ent] rolling restarts do not terminate paused workers

### ISSUE THREAD

**Issue by josefbilendo** [mperham/sidekiq#5104]
Ruby version: 2.5.8
Rails version: 5.2.6
Sidekiq / Pro / Enterprise version(s): 6.3.1 / 5.3.0 / 2.3.0

---
# Description
I'm currently setting up rolling restarts for our sidekiq swarms.
Everything works as expected: A rolling restart starts new workers and gracefully terminates old ones.

However, if we pause a worker (e.g. in the sidekiq-ent web interface), a rolling restart will start new workers but it won't terminate the paused worker.

**Comment by mperham** [comment]
Sidekiq doesn’t have a pause worker feature.

**Comment by josefbilendo** [comment]
Thank you for your quick response.
I'm sorry, it's called "quiet".

A rolling restart does not terminate quiet workers.

<img width="1202" alt="Bildschirmfoto 2021-12-23 um 15 54 42" src="https://user-images.githubusercontent.com/20594372/147257227-c51238f6-b6f4-4244-80a6-0bff29af64d3.png">

**Comment by mperham** [comment]
Right. Today rolling restarts only work on processes which are actively fetching jobs. Because you’ve manually quieted the process, you must manually terminate it too.

**Comment by josefbilendo** [comment]
Okay, thanks for confirming the issue.

I think it would be helpful to mention that in the documentation.
What do you think?

**Comment by mperham** [comment]
Sure.
