### ISSUE TITLE
Swarm leader in a concurrency=1 setup never picks up jobs

### ISSUE THREAD

**Issue by patbenatar** [mperham/sidekiq#5107]
Ruby version: 2.7.1
Rails version: 6.1.4.3
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.3.1 / Pro 5.2.4 / Ent 2.2.3

We're using swarm to run CPU-bound jobs with 1 thread per core to avoid contention. The leader process is always at 0% utilization. Is this by design that the leader avoids full utilization?

We also launch another swarm configuration on a separate server with a higher concurrency -- this one runs jobs from a more general-purpose queue of predominantly IO-bound jobs. When one of these processes is chosen as the leader, the CPU-bound processes all reach 100% utilization. If reduced utilization for the leader is normal, is there a way I can force one of these higher concurrency processes to be the leader?

**Comment by mperham** [comment]
We can discuss options but more generally that's just not a supported use case. Sidekiq is a multithreaded system; executing jobs have to share the CPU with their fellow threads, even if it means throwing a hack like `Thread.pass` in the inner loop.

**Comment by mperham** [comment]
And no, there is no configuration or API for leadership.

**Comment by patbenatar** [comment]
These jobs run in well under 1s (most 100ms or less), so even though their sharing skills rival a toddler while they're running, my assumption is control goes back to Sidekiq often enough that it should be able to manage itself in the time between jobs running? 

That seems a little beside the point though, since I'm seeing 0% utilization on this leader so my toddler jobs aren't even able to greedily use its CPU in the first place. Is there code that prevents the leader from saturating its threads so that it can try to guarantee it has the resources needed for whatever leader responsibilities it has?

**Comment by mperham** [comment]
Hmm. Sidekiq may have up to a dozen threads internally, all fighting your job for CPU time. Throw a Thread.pass or some sort of yield in your code if possible and see if that helps. If the process makes no progress after minutes, use TTIN or gdb to debug per the problems wiki page.

**Comment by patbenatar** [comment]
Thanks @mperham -- I'm deploying a `Thread.pass` today and will see what that does. Closing this for now; will re-open if that doesn't help and I can gather more diagnostics to help debug.
