### ISSUE TITLE
[sidekiq-ent] Control over unique arguments

### ISSUE THREAD

**Issue by benjaminwols** [mperham/sidekiq#5108]
Hi Mike,

I'd like to have control over the arguments used to calculate the unique hexdigest.
In my case I send 2 args to a worker and I want uniqueness to be only based on the second argument. 
It would be great if I could define the uniqueness in the worker similar to what [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs#finer-control-over-uniqueness) does.
I'd love to hear your thoughts.

**Comment by mperham** [comment]
Please give me more context. What is the first arg? Why doesn’t it indicate uniqueness?

**Comment by benjaminwols** [comment]
We develop an educational grading platform. If multiple students give the same answer to a question, we sync the grading scheme to the other students that gave the same answer. 
A simplified version is as follows: 
3 students have given the same answer to an open question. After the first student is graded, we create 2 jobs with args [sync_from_id, sync_to_id] => So that would look like [1, 2] and [1, 3]. 

If the second student is graded, before the background jobs have run, another job is scheduled to copy the grading from student 2 to student 3. A job with args [2, 3]. In this case I don't want to create the job, because the second argument is already present. The combination of the arguments is always different, so the jobs are always unique.

This is a simplified version, because we run into issues when more than 1000 students have given the same answer. The jobs are not in the high queue, so they are not processed directly. When a teacher starts grading we get [1000, 999, 998, ...] etc jobs scheduled and this is causing issues for us.

**Comment by mperham** [comment]
I don’t have any plans to add the feature you described. Part of the advantage of my uniqueness impl is that it is far simpler and bug free compared to s-u-j.

I know that doesn’t help you out. I think you’ll need to restructure your impl to work with sidekiq-ent or use s-u-j. You could use 6.3’s new CurrentAttributes support to pass the sync_from_id as state which is not passed via args.

**Comment by benjaminwols** [comment]
Thanks for the quick response. I'll look into using CurrentAttributes.
