### ISSUE TITLE
Can rescaling servers cause batches to lose jobs and callbacks never run

### ISSUE THREAD

**Issue by justin808** [mperham/sidekiq#5109]
Ruby version: 2.7.5
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.3.1 / Pro 5.3.0 / Ent 2.3.0

How can I debug why I'm getting stuck with batches that have **pending jobs** but the queue is **totally empty**?

I'm relying on the success callback to create more jobs in a workflow.

While jobs are running:

1. The number of Sidekiq worker instances might scale up or down, I'm using up to 50 concurrent P-L workers.
2. I'm using `sidkiqswarm` with ENV `SIDEKIQ_COUNT` set to 3 and 5 for concurrency
2. The Heroku release might change, with staging promoting to production. 

**How does sidekiqswarm behave when processes are killed and restarted?**

I suspect the jobs are either killed or finishing and not letting the batch know that they finished.

I'm using the option:

retry: false

other options are at default

I'm not seeing anything in the logs, although I've got 

```ruby
Sidekiq.configure_server do |config|
    config.logger.level = Logger::WARN
end
```

This is a pretty bad problem as the workflow is just hung without the success callback running.

Ideas?
1. Should I have a retry of 1 rather than zero?
2. Should I have info level logging until I figure this out?
3. Can I have some sort of watcher process that can take corrective action when the queue goes to zero, but batches indicate that some are alive?
4. What can I do with the mystery jids in the zombie batches?

**Comment by justin808** [comment]
I noticed that we didn't have 

`config.super_fetch!`

in the config, even though the server is "enterprise."

Would that help?
What would be the default?

**Comment by mperham** [comment]
Please don't use the word `worker` anymore. Use a specific term: process, thread, job. I don't know what "50 concurrent P-L workers" means.

Yes, it's likely that `super_fetch!` would solve your issue, it is not the default. All Pro and Enterprise features must be explicitly enabled.

**Comment by justin808** [comment]
I updated the description to use "Heroku Performance Large dynos."

I'll let you know if the `super_fetch!` solves the issue.

Any suggestions on ideas above, 1-4? Maybe these are all unnecessary until I discovered orphaned batches again?

**Comment by mperham** [comment]
I'm positive it will at least help solve your problem.

1. Why are you touching retry at all? Leave it to the default. If a job runs out of retries, it dies and the batch callback will never be called unless you run the job manually from the Dead tab.
2. More logging is always more helpful than less. super_fetch does log when it recovers a job.
3/4. super_fetch should fix these.

**Comment by justin808** [comment]
**Unfortunately, I immediately caused orphaned jobs again even with super_fetch on.**

The reproduction step was to scale the number of dynos from 37 to  1.

I set the sidekiq logs to info, so I could see some logs for the jobs that are pending.

I searched for one of the jids and found that some of the jobs started, but were never logged as "done". Some never started. Somehow, the batch didn't realize that.

**What else can I do to help troubleshoot?**

I will turn on reliable_push as well.

Is there any existing Sidekiq utility method to delete orphaned batches?

![image](https://user-images.githubusercontent.com/1118459/147994248-2281dc44-9280-46a1-91cd-d8519bf65b57.png)

![image](https://user-images.githubusercontent.com/1118459/147994376-2b52892c-f04a-466f-975d-12ed6e51eda1.png)

**Comment by mperham** [comment]
Yes, jobs can still be orphaned. Super_fetch will rescue them next time you restart a worker dyno. You will lose jobs if Sidekiq does not cleanly shut down within 30 seconds as noted here:

https://github.com/mperham/sidekiq/wiki/Heroku#shutdown-timeout

**Comment by justin808** [comment]
Turns out that superfetch found all the missing jobs, but only after scaling servers up. Scaling down from 37 to 1 Heroku dynos resulted in lost jobs. Scaling up to 2 caused the super fetch to find the jobs. I read somewhere that a job will run hourly to look for lost jobs.

**Comment by justin808** [comment]
What is a -1 for pending?

![image](https://user-images.githubusercontent.com/1118459/148033150-6b0abfc4-dd82-4608-828d-d64b6918afe4.png)

**Comment by mperham** [comment]
Correct, the rescue process is not a job but rather happens synchronously when you start a Sidekiq process. Scaling down does not start anything.

The most common cause of -1 is your Redis is configured incorrectly and evicted some batch data from Redis. https://github.com/mperham/sidekiq/wiki/Using-Redis#memory

**Comment by justin808** [comment]
@mperham I caused the bad pending number by scaling up and down the dynos a lot. The redis configuration is the Heroku default.

**Comment by justin808** [comment]
@mperham Here's another snapshot. Let me know if I can help with any logs. It's super easy to reproduce this. 

Regarding:
> Memory
Redis runs best when all data fits in memory. You should set maxmemory-policy noeviction in redis.conf so Redis doesn't drop Sidekiq's data silently.

Since I'm on the default, https://devcenter.heroku.com/articles/heroku-redis
![image](https://user-images.githubusercontent.com/1118459/148194860-b9ca94f6-841b-43a0-a71b-6ac6ed9f90f8.png)

Here's what I see in the UX:

![image](https://user-images.githubusercontent.com/1118459/148194382-afc3c224-36ad-4768-99d2-6624fd1ed874.png)

**Comment by mperham** [comment]
If you are repeatedly losing jobs on deploy, that means you aren't giving Sidekiq enough time to shut down cleanly. Heroku will `kill -9` Sidekiq after 30 seconds so that is a hard time limit for shutdown.

By default when you send TERM, Sidekiq pauses up to 25 seconds for executing jobs to finish. After 25 seconds, Sidekiq kills any remaining job threads and pushes the job data back to Redis. We have a 5 second time budget to do this.

Perhaps your Redis or network is performing poorly and you need more than 5 seconds to do this. Or the thread killing is taking a long time to unwind `ensure` blocks. One thing I would do is decrease your timeout setting, `-t`. Set it to 20 so Sidekiq has 10 seconds to cleanup. Ideally we want to find a happy medium between giving executing jobs as much time to finish as possible while also giving Sidekiq as much time as necessary to shut everything down cleanly.

What is your concurrency setting? Is it higher than 10?

**Comment by justin808** [comment]
Hi Mike, the concurrency setting is '5'. I'll try a 20 second timeout.

**Comment by justin808** [comment]
Would this command work to set the timeout on sidekiqswarm?
```
bundle exec ddtracerb exec sidekiqswarm -t 20 -e $RACK_ENV --config config/sidekiq_cache_warmer.yml
```

**Comment by mperham** [comment]
That’s right.
