### ISSUE TITLE
Sidekiq Pros profiling story

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#5111]
Hi Mike

I'm looking into profiling Sidekiq jobs in production - (As concurrent jobs and server setup might affect each others performance, we hope to be able to run some kind of profiling in our actual staging or production env).

One idea was to run the jobs inline, setup a http endpoint and simply use rack-mini-profiler. Unfortunately, the http request would timeout (heroku's 30s limit)

I know you've been looking into profiling Sidekiq in the past. Did you make any progress? Any advice?

Thanks

**Comment by mperham** [comment]
AFAIK It is effectively impossible to profile a running sidekiq job in production, because Ruby does not have any support for profiling a single thread within a multi threaded process.

The closest you might get is profiling running the job manually in an IRB session on a production machine.
