### ISSUE TITLE
Einhorn is no longer maintained

### ISSUE THREAD

**Issue by adamniedzielski** [mperham/sidekiq#5113]
I learned about the existence of https://github.com/stripe-archive/einhorn from https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts when I was implementing rolling restarts. After some time I wanted to contribute something back to the project and noticed that the project got archived (initially without much of a comment). https://github.com/stripe-archive/einhorn says now:

> This project is deprecated and is no longer being actively maintained.

but I haven't found any reason why it's no longer being maintained by Stripe. I went through https://github.com/stripe-archive/einhorn/network/members and didn't find any fork where somebody picked up the work. The only interesting one seems to be https://github.com/intercom/einhorn, because of [this (how smart) commit](https://github.com/intercom/einhorn/commit/9377f140eeaa211bc384ce39717aba04eefd34bf), but I'm not sure if it shows any commitment from Intercom to really maintain the gem.

I wonder what we should do in this situation?

1. find a completely different alternative and update https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts?
2. add a warning to https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts that Einhorn is no longer actively maintained and somebody could take over the maintenance if they want
3. reach out to Intercom and ask if they are committed to maintaining Einhorn. https://github.com/mperham/sidekiq/blob/63f6e68777fee1b5272288078a3d48c3695b2d70/Pro-Changes.md#191 suggests that they at least were a subscriber so maybe you @mperham have a direct contact to them
4. ???

**Comment by mperham** [comment]
Yes, they are an Enterprise customer.

I don’t see any great need to fork or actively look for a replacement. Enterprise has been using Einhorn for 5 years now without issue.

**Comment by mperham** [comment]
Might be a good instance for https://blog.rubygems.org/2022/01/19/rubygems-adoptions.html
