### ISSUE TITLE
Gemfile.lock checked into repo makes handling diverse Rubies difficult

### ISSUE THREAD

**Issue by petergoldstein** [mperham/sidekiq#5114]
Ruby version: 2.5-3.1
Rails version: N/A
Sidekiq

I'm trying to add Ruby 3.1 to the CI matrix, but I'm running into issues because the Gemfile.lock is checked into the repo.  I'm not entirely sure why.

The problem is that there isn't a single version of Nokogiri that works with Ruby 2.5 and Ruby 3.1.  Nokogiri 1.13 is the first version that supports Ruby 3.1 natively.  But it requires Ruby 2.6+, so the Ruby 2.5 run fails on `bundle install`.

Can we remove the Gemfile.lock from the repo?  That should fix the issue.

**Comment by mperham** [comment]
I think I'd rather have 2.5 removed from the matrix. Support for 2.5 is on life support at this point.

**Comment by petergoldstein** [comment]
Ok, I put up a PR (https://github.com/mperham/sidekiq/pull/5115) but it's not green.  Psych changes are a problem for the Delayed Extensions features.

**Comment by petergoldstein** [comment]
With the latest commit - that shifts the range of tested Rubies to 2.6-3.1 - I'll call this closed.
