### ISSUE TITLE
Keeping Periodic Job history during sidekiq restarts

### ISSUE THREAD

**Issue by jirihradil** [mperham/sidekiq#5116]
Hi,

We use sidekiq enterprise (great job, thank you!) and I'm curious if it's possible to keep the history of each periodic job's run? When we redeploy our app, the history of previous runs is automatically deleted. Haven't found anything in the docs about this.

Thank you!

**Comment by mperham** [comment]
Periodic job history should not be cleared by a deploy. I'm not sure why you're losing your history but that's unexpected.

**Comment by jirihradil** [comment]
Thanks - our periodic job history survived about 10 restarts/redeploys since last week and everything was fine until today. All the queues (Retries/Scheduled/Dead) are OK and kept, only period job history has this problem. The clear happened only once, all further deploys were OK and history is kept.

Is it possible that history clear was caused by Gemfile.lock changes or Redis records have an expiration set? We don't have any special setup, just common configuration according to https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#testing (we use the `PERIODIC_JOBS` constant) extracted to `lib/period_job.rb`.

**Comment by mperham** [comment]
It’s possible you’ll lose history if you add/remove a periodic job.

**Comment by jirihradil** [comment]
> It’s possible you’ll lose history if you add/remove a periodic job.

Yes, you are right, the history was cleared after I changed the cron schedule expression for some of the existing jobs.

Problem solved, thank you!
