### ISSUE TITLE
UPDATE_ATTRIBUTES DEPRECATED

### ISSUE THREAD

**Issue by Dandush03** [mperham/sidekiq#5121]
Ruby version: 3.1
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): Enterprise (kidding, just want a solution)

NoMethodError: undefined method `update_attributes' for #<Sidekiq::Monitor::Job id:

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Sidekiq::Monitor is not something I support. I assume it's some third party gem.
