### ISSUE TITLE
[Question] I wanna `stop!` a specific running worker.

### ISSUE THREAD

**Issue by y-okamoto-1113** [mperham/sidekiq#5124]
Ruby version: 2.4.1
Rails version: 5.1.6.1
Sidekiq  version: 5.2.3

Hi Mike.
I apologize if this question has been asked before.
I googled about this, but could not find a straight answer.

I want to keep the process running, but kill only a certain worker.
So, I wanna use `stop!` method at `Sidekiq::Worker` object.
but, can not use. 
Because this method is defined in `Sidekiq::ProcessSet`.

please would you teach me how to kill only a certain running worker?

**Comment by mperham** [comment]
You can’t safely kill a Thread in Ruby, so Sidekiq has no API to do it. If you want your job to stop, you must shut down the process or build in support for stopping into your app code.
