### ISSUE TITLE
Worker's `pool` option is ignored when pushed by `Client`'s methods.

### ISSUE THREAD

**Issue by m1kit** [mperham/sidekiq#5126]
Ruby version: 3.0.2
Rails version:6.1.4.4
Sidekiq / Pro / Enterprise version(s): 6.3.1

## Issue
[The doc](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/client.rb#L58-L59) says:

> If class is set to the class name, the jobs' options will be based on Sidekiq's default worker options. **Otherwise, they will be based on the job class's options.**

However,  if we push something via these methods, the `@redis_pool` of the client is used and the pool specified by the worker class's option is ignored.

## Workaround
We can use `Client.via` to set `@redis_pool` with desired value.
However, if the pool is fixed for each worker, wrapping with `via` every time is painful.

**Comment by mperham** [comment]
Can you give me code which reproduces the issue?

**Comment by m1kit** [comment]
@mperham 

Could you tell me about that behavior a bit more?

I understand that using the client cause all jobs goes to the pool managed by the pool.
However, I feel it is unnatural that jobs queued by `Worker.perform_bulk` ignores the `pool` option of the worker.

**Comment by mperham** [comment]
Yeah that doesn't sound right.

**Comment by m1kit** [comment]
> Yeah that doesn't sound right.

I'd like to create a PR about this.

**Comment by mperham** [comment]
Sure, looks like it's just a few lines in worker.rb.

**Comment by locofocos** [comment]
We were running into a similar problem. I thought there was a bug present for the _general_ case, where calling `Sidekiq::Client.push_bulk` did not honor `sidekiq_options` at all.

After studying the source [5.x](https://github.com/mperham/sidekiq/blob/5-x/lib/sidekiq/client.rb#L234-L241) / [current main](https://github.com/mperham/sidekiq/blob/c4dbc922305effd1db98527c293e0354456fc79a/lib/sidekiq/job_util.rb#L56-L63), I found that it depends on whether you pass the `class` param as a Class or a String.

```
# This does NOT honor sidekiq_options defined in Images::ImportWorker
Sidekiq::Client.push_bulk('class' => "Images::ImportWorker", 'args' => ...)

# This does honor them
Sidekiq::Client.push_bulk('class' => Images::ImportWorker, 'args' => ...)
```

**Comment by bagiojm** [comment]
I am trying to invoke a sidekiq job from rails, I have tried passing "pool" worker option for sidekiq job, but somehow perform_async ignores this option and passes the job to default config sidekiq has been initialised with..

REDIS = ConnectionPool.new { Redis.new(url: '', namespace: '') }
Sidekiq::MyWorker.set("pool" => REDIS).perform_async()

Am I doing this right way?

**Comment by mperham** [comment]
@bagiojm Try:

```ruby
Sidekiq::Client.via(REDIS) do
  MyWorker.perform_async
end
```
