### ISSUE TITLE
[Question] I want to test the sidekiq job deletion API from rspec

### ISSUE THREAD

**Issue by nayoothant** [mperham/sidekiq#5130]
Ruby version: 2.4.1
Rails version: 5.1.6.1
Sidekiq version: 5.2.3

Hi Mike, I am trying to test an API that is called to delete the sidekiq job in the Queue.
I implemented `MyWorker.perform_in(3.minutes)` in rspec to make the Queue busy.
but when I try to get the busy job in my API `Sidekiq::Queue.new("queue_name").size` is `0`.
I google about it and I have some answers that I called the perform_in method in sidekiq-testing and check the queue in
API is appropriate.
How Can I implement this?
Please would u teach me how to test API for deleting a job in `Sidekiq::Queue.new("queue_name")`

My API
```
      queue = Sidekiq::Queue.new("queue_name")
      queue.each do |job|
        if job.jid == "12345678"
          job.delete
        end
      end
```

**Comment by mperham** [comment]
`perform_in(3.minutes,...)` does not enqueue a job, it schedules a job to be enqueued in 3 minutes. Use `perform_async` to enqueue a job.

**Comment by nayoothant** [comment]
@mperham 
Thank you!!
