### ISSUE TITLE
Heroku Rails app - job not running

### ISSUE THREAD

**Issue by joshmrallen** [mperham/sidekiq#5132]
Ruby version: 2.6.6
Rails version: 6.1.4.1
Sidekiq version: 5.0.4

## Overview

We have an events ticketing app that has a bit of legacy code in it and I'm having an issue with a few features not behaving as expected *only on production*. development and staging apps work as expected.

I specifically went after one feature, because it's very important. Here's the flow:
1. User is viewing their cart and clicks/taps the button: 'Release Tickets'
2. Params sent to controller include a property: params[:release_cart] -- value is the cart id
3. If a value is present, the value is used to find the cart instance
4. expire_cart! is called on the instance (see code below for all related methods)
5. user is redirected to the event page

## Expected behavior:
- cart is locked using with_lock, and methods are executed to deallocate ticket inventory
- a method is executed that runs a sidekiq job to send a followup email in 3 hours

## Actual behavior:
- expire_cart! runs, but the method to deallocate doesn't run at all
- no errors are thrown, even when I add error handling for each method used, all the way down

## Debugging:
- I ran some script in the rails console and got an ArgumentError (see below)
- I followed this issue that said an ArgumentError meant needing to restart sidekiq: 
https://github.com/mperham/sidekiq/issues/2423
- I attempted to 'restart' sidekiq on our heroku app as per this stackoverflow 
https://stackoverflow.com/questions/53272262/how-to-restart-sidekiq-when-running-on-heroku
- This article was referring to 'memory fragmentation problems which we do seem to have quite a few errors in the log for:
```
2022-01-20T18:46:04.858044+00:00 heroku[worker.1]: Process running mem=1595M(155.6%)
2022-01-20T18:46:04.881326+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-01-20T18:46:23.064951+00:00 heroku[worker.1]: Process running mem=1594M(155.5%)
2022-01-20T18:46:23.113402+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-01-20T18:46:43.186537+00:00 heroku[worker.1]: Process running mem=1594M(155.5%)
2022-01-20T18:46:43.243132+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
```
- Until now I wasn't sure if this was a related problem or not, but that article seems to suggest it is and it also points to a solution that calls for restarting heroku dynos regularly: 
https://dev.to/nicolrx/how-to-easily-avoid-hitting-the-memory-limit-on-heroku-2mha
However, I wanted to make sure before: 1. adding a new gem and 2. regularly restarting dynos (our clients use our app around the clock, 24/7)
I first tried restarting the dynos by scaling them down and restarting the app:
1. Turning on mainenance mode
2. Scaling down worker dynos down
3. Restarting the app
4. Scaling worker dynos back up
5. Turning off maintenance mode
- But the problem still persisted

## On the Rails console:
```
irb(main):029:0> def expire(email)
irb(main):030:1>         user = User.find_by(email: email)
irb(main):031:1>         cart = user.carts.order(created_at: :desc).first
irb(main):032:1>         puts "Before expire_cart! command =============="
irb(main):033:1>         cart.expire_cart!
irb(main):034:1>         puts "After expire_cart! Expired: #{cart.expired ? true : false} ============"
irb(main):035:1> end
=> :expire
irb(main):036:0> expire(email)
Before expire_cart! command ==============
Traceback (most recent call last):
        7: from (irb):36
        6: from (irb):33:in `expire'
        5: from app/models/cart.rb:99:in `expire_cart!'
        4: from app/models/cart.rb:55:in `deallocate_ticket_inventory_and_expire_cart'
        3: from app/models/cart.rb:91:in `block in deallocate_ticket_inventory_and_expire_cart'
        2: from app/models/cart.rb:103:in `trigger_followup'
        1: from (irb):29:in `expire'
ArgumentError (wrong number of arguments (given 2, expected 1))
```

## Here are the respective methods:

```
# app/models/cart.rb

Class Cart

# some relationships, etc ...

    
def deallocate_ticket_inventory_and_expire_cart
    self.with_lock do
      if self.purchased_at.blank? && self.expire_after < Time.now && self.purchase_in_progress.blank? && !self.expired?
        deallocate_ptfs    = Hash.new(0)
        deallocate_plfs    = Hash.new(0)
        deallocate_showing = Hash.new(0)
  
        begin
          self.line_items.where(item_type: 'PriceTypeForShowing').each do |li|
    
            item = li.item
    
            deallocate_ptfs[item.id] += li.quantity
            deallocate_plfs[item.price_level_for_showing_id] += li.quantity
            deallocate_showing[item.showing_id] += li.quantity
          end
    
          PriceTypeForShowingInventory.for(deallocate_ptfs.keys).each do |inv|
            inv.deallocate!(deallocate_ptfs[inv.price_type_for_showing_id])
          end
    
          PriceLevelForShowingInventory.for(deallocate_plfs.keys).each do |inv|
            inv.deallocate!(deallocate_plfs[inv.price_level_for_showing_id])
          end
    
          ShowingInventory.for(deallocate_showing.keys).each do |inv|
            inv.deallocate!(deallocate_showing[inv.showing_id])
          end
          
          self.expired = true
          self.save

        rescue StandardError => e
          Airbrake.notify(e)
        end
  
      end
      trigger_followup
    end
  end

    def trigger_followup
        AbandonedCartJob.perform_in(3.hours, self.id)
    end

end

```

## Here's the sidekiq worker:

```
class AbandonedCartJob
  include Sidekiq::Worker
  sidekiq_options queue: :medium

  attr_reader :cart_id

  def perform(cart_id)
    @cart_id = cart_id
    return if should_abort?

    send_email
    log_email
  end

  private

  def send_email
    OrganizationMailer.abandoned_cart(user, event).deliver_now
  end

  def log_email
    mailer_log = MailerLog.create user_id: user.id, user_email: user.email, mailer_name: 'abandoned_cart'
    mailer_log.update scheduled_at: mailer_log.created_at
  end

    
  # a bunch more private methods here

end

```

## Here's the part of the controller where the expire_cart! method is called:
```
def expire_redirect    
    cart = Cart.find_by id: params[:release_cart]
    cart.expire_cart! if cart.present?
    redirect_to event_path @event.url_name, access_code: cart.try(:access_code_string)
end
```

## Initializer and yml files:

```
# config/sidekiq.yml

---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - [high, 8]
  - [medium, 4]
  - [low, 2]
  - [mailers, 2]
  - [ahoy, 1]
  - [default, 1]
  - [scheduled_reports, 1]
  - 
###########################

# config/initializers/sidekiq.rb

require 'sidekiq-status'

if Rails.env.test?
  require 'sidekiq/testing'
  Sidekiq::Testing.inline!
end

if ENV['REDIS_URL'].nil?
  rails_root        = ENV['RAILS_ROOT'] || File.dirname(__FILE__) + '/../..'
  rails_env         = ENV['RAILS_ENV'] || 'development'
  redis_config      = YAML.load_file(rails_root + '/config/redis.yml')
  ENV['REDIS_URL']  = redis_config[rails_env]
end

Rails.logger.debug ENV['REDIS_URL']

Sidekiq.configure_server do |config|
  config.redis = { :url => ENV['REDIS_URL'], :namespace => 'fresh' }

  database_url = ENV['DATABASE_URL']
  if database_url
    ENV['DATABASE_URL'] = "#{database_url}?pool=25"
    ActiveRecord::Base.establish_connection
  end
end

Sidekiq.configure_client do |config|
  config.redis = { :url => ENV['REDIS_URL'], :namespace => 'fresh' }
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
end


```

## If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?
- I checked and noticed that support for Rails 5.1 was dropped, but we are currently at Rails 6.1, previously Rails 5.2.7, and previously Rails 4.2.9.11 -- the issue has persisted through each upgrade

## More information:
- I originally thought that removing the with_lock would help fix things, but I was wrong -- the issue still persisted even after removing with_lock
- I tried calling the sidekiq job directly from the aforementioned expire_cart! method and it still doesn't execute
- When it works: we have a cart timer and a job that expires carts that have 'expired.' Upon actually expireing (reaching 0 without updating the time), the ExpireCartJob successfully runs and works as expected.
- On heroku, we use **Redis Enterprise Cloud** add-on
- I viewed the heroku worker logs specifically with the command: `heroku logs -t -a app-name --dyno worker` 

## Questions
- Is it because we have another job or something for this expiration, that trying to call the ExpireCartJob in addition to that interferes? I remember seeing in a stackoverflow that calling multiple jobs for the same object/task can sometimes cause problems.
- How exactly do I test if it's a memory leakage issue?
- Reading through [mperham's article here on using jemalloc](https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/), how would I implement this for a heroku rails app?

**Comment by joshmrallen** [comment]
Update:
I tried the following to deal with the memory quota errors:
1. added MALLOC_ARENA_MAX = 2 to our heroku config vars

the error messages in the worker log disappeared, but the issue with the "cart release/allocation" still persists

2. Changed our WEB_CONCURRENCY config var from 11 to 10
- the issue with the cart release still persists
This value is used in the `config/puma.rb` file:
```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup DefaultRackup
port ENV['PORT'] || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Valid on Rails up to 4.1 the initializer method of setting `pool` size
  ActiveSupport.on_load(:active_record) do
    config = ActiveRecord::Base.configurations[Rails.env] || Rails.application.config.database_configuration[Rails.env]
    # config['pool'] = ENV['MAX_THREADS'] || 5
    ActiveRecord::Base.establish_connection(config)
  end
end
```

**Comment by mperham** [comment]
I can’t help with cart release, that’s an app specific bug and my support is not designed for debugging app issues.
