### ISSUE TITLE
Sidekiq 6.4.0 changes behavior of Sidekiq::JobRecord#display_args

### ISSUE THREAD

**Issue by thachck** [mperham/sidekiq#5133]
Ruby version: 2.7.5
Rails version: 6.1.4.4
Sidekiq version: 6.4.0

There is a change in behavior of `Sidekiq::JobRecord#display_args` in Sidekiq 6.4.0 compared with Sidekiq 6.3.1

Sidekiq 6.3.1
<img width="871" alt="Screen Shot 2022-01-22 at 3 49 52 PM" src="https://user-images.githubusercontent.com/640707/150631830-4b8343cc-ebe7-4180-97ac-f3398efbad53.png">

Sidekiq 6.4.0
<img width="856" alt="Screen Shot 2022-01-22 at 3 50 38 PM" src="https://user-images.githubusercontent.com/640707/150631839-23440281-49cb-4ed1-add0-412716c484ed.png">

The codebase is the same, it is just the Sidekiq version changes between the two screenshots.

Here is the shorten code snippet of the `ZoomVideo::NotificationReminderService`
```ruby
class ZoomVideo
  class NotificationReminderService
    def initialize(zoom_video_id:)
    end

   def send_reminder_notification
   end
   
   def self.send_reminder_notification(*args)
      new(*args).send_reminder_notification
    end
  end
end
```

I guess this is related to #5120 where we add the support for keyword arguments in extensions, and we might need another method such as `Sidekiq::Job#display_kwargs` to handle this situation.

Please let me know if you think that is reasonable. I'm willing to add a PR for that.

Thanks for your great gem.

**Comment by mperham** [comment]
Happy to get a PR for this.

**Comment by thachck** [comment]
@mperham Thanks. I have opened PR #5134 . Please have a look if you have time.
