### ISSUE TITLE
[Question] OpenSSL certificate error in sidekiq gem installing

### ISSUE THREAD

**Issue by nayoothant** [mperham/sidekiq#5144]
Hi Mike,

I recently bought sidekiq-pro and try to install the gem with key that I got.
After setting the configuration with key and run `bundle install` , the following error occured.
```
Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://gems.contribsys.com/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates
 needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without 
using SSL, edit your Gemfile sources and change 'https' to 'http'.

```
I've change `https://gems.contribsys.com/.` to `http://gems.contribsys.com/.` But it didn't help.
I am using docker,
Ruby : 2.4.1
Bundler : 2.3.5
how can I configure a SSL certificate in Docker?
Please teach me...

**Comment by mperham** [comment]
#5008
