### ISSUE TITLE
Throttling jobs for specific queue, worker, strategy

### ISSUE THREAD

**Issue by Blokh** [mperham/sidekiq#5154]
Greetings,

We're using sidekiq-pro (5.0.0).
We've updated the basic_fetch to super_fetch, and it seems to work seamlessly.

The issue is that we used to use a gem name sidekiq-throttle in order to throttle some jobs ( by specific concurrency ) for heavy jobs in order not to overload the system.

the throttle gem seems not to work with super-fetch.

The question is. is there some built-in way to throttle sidekiq jobs ( add max concurrency )?
 is there a way to run max jobs in a queue without managing it by stopping and resuming it?
 
Thanks in advance,
Daniel

**Comment by mperham** [comment]
The only way to throttle a sidekiq queue is to provide a separate process
with limited concurrency that only processes jobs from the queue.
