### ISSUE TITLE
Remove parallel code paths caused by "push" and "push_bulk"

### ISSUE THREAD

**Issue by adamniedzielski** [mperham/sidekiq#5158]
1. `Sidekiq::Worker.perform_bulk` calls `Sidekiq::Client#push_bulk`
2. `Sidekiq::Worker.client_push` calls `Sidekiq::Client#push`
3. `Sidekiq::Client#push_bulk` and `Sidekiq::Client#push` both end up calling `Sidekiq::Client#raw_push`
4. I believe that the intention is that they are consistent

Would you accept a PR where I try to:
1. refactor `Sidekiq::Client#push` to call `Sidekiq::Client#push_bulk` as it's just a special case of having one job to push
2. refactor `Sidekiq::Worker` to always use `Sidekiq::Client#push_bulk` so there's one interaction point between `Worker` and `Client`
3. (optionally) introduce lightweight dependency injection of `Client` so that it's possible to provide custom client implementation for `Worker` - for example through worker options

? Or am I missing some practical considerations here?

**Comment by mperham** [comment]
I’m fine with refactoring but we need to be very careful about changing any documented public APIs.
