### ISSUE TITLE
Add better contributing guidelines

### ISSUE THREAD

**Issue by adamniedzielski** [mperham/sidekiq#5161]
I noticed that Sidekiq has [brief information how to contribute](https://github.com/mperham/sidekiq/blob/10e7feb312cbcd5c14c89e8a8dd9e74a6355f588/.github/contributing.md), but it's not linked from the README.

I wonder if it would make sense to:
1. link it from the README so it's clearly visible when you visit the repo
2. add instructions about setting up the dev environment
3. improve the overall contributor experience by, for example, adding `.ruby-version` file to the repo for folks to easily figure out what's the default version for development, or even Docker setup to make it even easier.

What do you think?

**Comment by mperham** [comment]
If you are a Rubyist with Redis installed, the dev setup is `bundle ; bundle exec rake`. So it's not documented because it's pretty simple. Am I making assumptions?

I don't want a .ruby-version because I don't want to force a particular version of Ruby on all developers who want to contribute. `main` should work with any Ruby 2.5+.

**Comment by adamniedzielski** [comment]
I've been developing with Ruby for the last 9 years and I'd still appreciate some simple instructions that I can just follow 🙂 I went to https://github.com/mperham/sidekiq/blob/cd553fa14cefe789684f3cf35b0f61e4e22b6305/.github/workflows/ci.yml to check what happens on CI. I can imagine that a junior programmer may not do it and just decides that Sidekiq is not the right OSS project for the to contribute.

> I don't want a .ruby-version because I don't want to force a particular version of Ruby on all developers who want to contribute. main should work with any Ruby 2.5+.

Fair point 👍 I could be described as "Please check the required Ruby version in `sidekiq.gemspec` and pick any version that satisfies this requirement for development." in the contributing instructions. There is still a possibility that a new Ruby version is released and Sidekiq doesn't support it yet, but that's hopefully a short time window.

I'm happy to make a PR.

**Comment by adamniedzielski** [comment]
Side question: if Sidekiq should work with Ruby 2.5+ why is Ruby 2.5 not being tested on CI?

**Comment by adamniedzielski** [comment]
> with Redis installed

Oh, I actually missed this part of your answer. These days I run my Ruby applications in Docker containers which means that I may actually not have Redis installed on the host. Therefore I'm surprised that I actually got the test suite running, because I don't remember installing Redis on this laptop.

That would be it on the topic of assumptions.

**Comment by mperham** [comment]
We removed 2.5 recently because it was giving us issues with the recent kwargs changes. 2.5 is EOL and will be removed from support once 7.0 ships this Spring (Railsconf maybe?).

**Comment by mperham** [comment]
I think a simple section in the README would suffice. Advanced users may run Docker if they want but the happy path should assume a local Redis install.
