### ISSUE TITLE
Redis::TimeoutError: Connection timed out

### ISSUE THREAD

**Issue by tanelsuurhans** [mperham/sidekiq#517]
We have been using Sidekiq in our production environment for a while now with great success.
Since moving from a Ubuntu LTS setup to a RHEL one, and upgrading Sidekiq to the latest version, we have started getting a lot of Redis connection timeouts. Not sure what these could be caused by either.

The setup we have is Rails with Unicorn, 12 workers per server across 6 nodes. Each node also runs Sidekiq workers - 10 of them, plus 2 util servers which also run 10 workers. The Unicorn related config (client settings for Sidekiq) are according to the Wiki examples - size => 1
Redis has a pretty stock config, so the maxclients setting is 10 000. Based on this it doesn't seem like we would be running out of connections or anything. Our traffic is pretty much the same as before too, and we didnt have any issues like this, not even once. Now we're seeing a couple of timeouts per hour easily.

Whats making things worse is that we are also getting PostgreSQL connection errors from inside the executed Sidekiq tasks.

`PG::Error: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.`

And this is only occurring inside tasks, nowhere else in the app.
I've sat on this for two days straight now, trying to find out what the issue could be with no clue whatsoever. Any ideas?

**Comment by igorkasyanchuk** [comment]
please tell what you did to fix this issue. thanks

**Comment by M034B5** [comment]
Bump, how did you fix it?
