### ISSUE TITLE
Allow "at" to be a Proc so we can schedule dynamically in bulk

### ISSUE THREAD

**Issue by adamniedzielski** [mperham/sidekiq#5176]
Extracted from https://github.com/mperham/sidekiq/pull/5171#issuecomment-1028420419:

Allow "at" to be a Proc so we can schedule dynamically in bulk. Might be a little tricky to implement since `raw_push` handles `at`. Like:

```ruby
now = Time.now.to_f
push_bulk('class' => Foo, 'args' => 10.times.to_a.map {|idx| Array(idx) }, 'at' => ->(idx) { now + idx })
```

That would allow the caller to smear jobs over time in bulk.

**Comment by adamniedzielski** [comment]
@mperham I looked at this and I'm not sure if I understand the advantage of supporting a Proc. What's currently possible:

```ruby
now = Time.now.to_f
push_bulk('class' => Foo, 'args' => 10.times.to_a.map { |idx| Array(idx) }, 'at' => 10.times.to_a.map { |idx| now + idx })
```

"at" can be an array of timestamps. [Here is a test case for that](https://github.com/mperham/sidekiq/blob/6a6fda35fa9d07c4fe8ed3b05609a0eba6781101/test/test_client.rb#L246-L253).

Am I misunderstanding something here?

**Comment by mperham** [comment]
I'm trying to avoid the client having to pre-calculate a huge Array into memory. Alternatively we could have a `stream_bulk` API which doesn't require precalculating `args` or `at` but allows `Sidekiq::Client` to stream 1000 jobs at a time into Redis. More of a lazy Enumerator approach...

**Comment by adamniedzielski** [comment]
> I'm trying to avoid the client having to pre-calculate a huge Array into memory.

Got it 👍 My guess is that the Array of `args` is going to be of a comparable magnitude.

> Alternatively we could have a stream_bulk API which doesn't require precalculating args or at but allows Sidekiq::Client to stream 1000 jobs at a time into Redis. More of a lazy Enumerator approach...

Interesting 🤔 That said, I never worked on an application that required something like this, `push_bulk` was all that we needed. Therefore, I'm going to close this issue, because I don't think that I'm going to implement that or even be able to write the problem statement 🙂
