### ISSUE TITLE
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0 (WARNING)

### ISSUE THREAD

**Issue by NemyaNation** [mperham/sidekiq#5178]
Ruby version: ruby 2.6.6p146
Rails version: Rails 6.1.3.1
Sidekiq / Pro / Enterprise version(s): 6.4.0

This just started a coulple of hours ago, approximiately ever 2s I get more than 100 lines of this warning repeated again and again since the latest update to (6.4.0)

warning in logs: 

```
app[web] info redis.pipelined do
app[web] info   redis.get("key")
app[web] info end
app[web] info
app[web] info should be replaced by
app[web] info
app[web] info redis.pipelined do |pipeline|
app[web] info   pipeline.get("key")
app[web] info end
app[web] info
app[web] info (called from /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/api.rb:57:in `block in fetch_stats_fast!'}
Feb 4 00:09:38 my-app app[web] info Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
```

`initializers/sidekiq.rb`

```
Sidekiq.configure_server do |config|
	config.redis = {
		url: ENV["REDISCLOUD_URL"]
	}
end

Sidekiq.configure_client do |config|
	config.redis = {
		url: ENV["REDISCLOUD_URL"],
		size: 2
	}
end

Sidekiq.strict_args!(false)

```

Still clogging up my logs, and this is just from live polling on the dashboard.

I thought it might be fixed by adding `Sidekiq.strict_args!(false)` but this did not help, doesn't look like it's from my end and instead something needs to be updated in the gem itself?

**Comment by mperham** [comment]
That’s from the Redis gem. 6.4.1 will be released Monday and fix it.
Downgrade that gem or use Sidekiq’s main branch if you want an immediate
fix.

**Comment by NemyaNation** [comment]
@mperham brilliant, no I'll wait, I just was wondered if you guys were aware the latest update was causing this warning.

will leave open until monday and I see that the warning has subsided.

**Comment by kooshywoosh** [comment]
still seeing these warnings (although less frequently) after upgrading to 6.4.1

**Comment by resistorsoftware** [comment]
I just updated to Sidekiq 6.4.1 and running Rails 7 with Redis 4.6, this is still an issue. Logs fill continuously with notice about using pipeline key.

**Comment by mperham** [comment]
Do you use any other Sidekiq extensions?

**Comment by seanwmitchell** [comment]
Thanks for the fix, my logs are empty now. Rail 7.0.1, Sidekiq 6.4.1, sidekiq-congestion 0.1.1 and Redis 4.6.0 on Ubuntu 20.04.3 LTS.

**Comment by resistorsoftware** [comment]
> Do you use any other Sidekiq extensions?

No. My gemfile is "redis" and "sidekiq"

**Comment by resistorsoftware** [comment]
> > Do you use any other Sidekiq extensions?
> 
> No. My gemfile is "redis" and "sidekiq"

Ack. NVM... 

Was just a bad bundle

**Comment by celsoMartins** [comment]
I'm also still getting the warning on my logs.

These are the env information.

```
redis-server --version
Redis server v=6.2.6 sha=00000000:0 malloc=libc bits=64 build=c6f3693d1aced7d9
gem list|grep sidekiq
sidekiq (6.4.1)
sidekiq-limit_fetch (3.4.0)
```

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end
```

```
gem 'sidekiq'
gem 'sidekiq-limit_fetch'
```

and the redis was installed using homebrew.

**Comment by petergoldstein** [comment]
@celsoMartins It's in `sidekiq-limit_fetch`.  I just put up a PR to resolve - https://github.com/brainopia/sidekiq-limit_fetch/pull/121

**Comment by vinc** [comment]
https://github.com/brainopia/sidekiq-limit_fetch/pull/119

**Comment by kimpastro** [comment]
gem redis 4.6 and sidekiq 6.4.1 works for me.

**Comment by pinkyrout** [comment]
I am still getting the warnings after upgrading sidekiq from 4.2.10 to 6.4.1 or 6.4.0 and even tried using the main branch from Sidekiq.
My ruby version is 2.7.5 and Rails version is 6.0 .

**Comment by Laykou** [comment]
It may be due to other gems, in my case it was sidekiq-cron. Here is a discussion and fix in forked branch: https://github.com/ondrejbartas/sidekiq-cron/issues/310#issuecomment-1048372868

**Comment by pinkyrout** [comment]
Thanks, it worked for me. The issue was with sidekiq-cron.
