### ISSUE TITLE
Methods with emoji names are hard to debug

### ISSUE THREAD

**Issue by dorianmariefr** [mperham/sidekiq#5179]
Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
Rails version: Rails 7.1.0.alpha
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.0

```
(called from /Users/dorianmariefr/.rvm/gems/ruby-3.1.0/gems/sidekiq-6.4.0/lib/sidekiq/launcher.rb:164:in `block in ❤'}
```

What does ❤️ even means in this context? is this some obfuscation? ok, after reading the code it seems to mean `heartbeat`? Why not name it just that? and have an alias for backward compatibility? like what is done for 💣 https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/api.rb#L296 where we can see it means `clear`

**Comment by mperham** [comment]
I like them. They add fun and whimsy to boring code.

**Comment by dorianmariefr** [comment]
Maybe a comment saying it means heartbeat?

**Comment by dorianmariefr** [comment]
I can't even search for it on github: https://github.com/mperham/sidekiq/search?q=%E2%9D%A4%EF%B8%8F

**Comment by dorianmariefr** [comment]
https://github.com/mperham/sidekiq/pull/5181

**Comment by dorianmariefr** [comment]
For instance I'm a big fan of `When you HTTParty, you must party hard`, but this is just obfuscation, maybe fun for you but not for those that read it and have to understand it
