### ISSUE TITLE
`sidekiq -v` should return the version

### ISSUE THREAD

**Issue by dorianmariefr** [mperham/sidekiq#5180]
Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
Rails version: Rails 7.1.0.alpha
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.0

Running `sidekiq -v` runs sidekiq like a regular run, and from the help it means `verbose` but it seems that by convention `-v` returns the version, e.g. `ruby -v`, `rails -v`, etc.

**Comment by mperham** [comment]
There's precedent for `-v` too. ssh and curl both use it. I'd be happy to see a PR for `-V`.

**Comment by dorianmariefr** [comment]
I don't think there is a point to do `-V`, people (at least me) would do `sidekiq -v`, see it doesn't return the version then do `sidekiq --version` and see it does

**Comment by dorianmariefr** [comment]
I think it's much more common to ask for the version that to ask for the verbose option
