### ISSUE TITLE
[Question] How to structure Sidekiq Server/Client middleware integration test with RSpec.

### ISSUE THREAD

**Issue by kshvesov** [mperham/sidekiq#5187]
Ruby version: 2.7.4
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): 6.4.0
RSpec version: 3.10.0

## Problem
We are trying to create an end-to-end test for our client and Server [Sidekiq Custom Middleware](https://github.com/mperham/sidekiq/wiki/Middleware) using RSpec. As a guide we are using [Testing Server Middleware](https://github.com/mperham/sidekiq/wiki/Testing#testing-server-middleware) wiki. Our custom middleware contains code related to serialization so want to include Redis and full Sidekiq flow to prove everything is working as expected. Just server or client middleware separately do work as expected in test but together in the same test they do behave unexpected and it seems to be related to how middleware registered in Sidekiq.

Please help us to figure out if there is better approach to organize end-to-end test for custom middleware with Sidekiq.
<rb/>

## Example
We came up with the test structure which seem to be working but Im sure is suboptimal and can be improved.
```ruby
RSpec.describe "My::Sidekiq::Middleware" do

  before do
    Sidekiq::Testing.disable!
    Sidekiq.options[:queues] << "default"
    @launcher = Sidekiq::Launcher.new(Sidekiq.options)
  end

  after do
    @launcher&.stop
  end

  describe "End to end custom middleware test" do
    it "can send Sidekiq job from client to server though middleware" do

      Sidekiq.configure_client do |config|
        config.client_middleware do |chain|
          chain.add My::Sidekiq::Middleware::Client
        end
      end

      EmptyWorker.perform_async

     # This is important to put this require after Client Middleware registered. Otherwise client middleware does not get to register.
      require "sidekiq/cli"
      Sidekiq.configure_server do |config|
        config.server_middleware do |chain|
          chain.add My::Sidekiq::Middleware::Server
        end
      end

      @launcher.run

     .... Additional logic to capture jobs
    end
  end
```

**Comment by mperham** [comment]
There's no official API to end-to-end test server-side middleware. You can call it directly.

```ruby
My::Middle::Ware.new.call(job_inst, hash, queue)
```

I don't recommend requiring `sidekiq/cli`. Instead call `Sidekiq.server_middleware` or `Sidekiq.client_middleware` directly to establish your middleware chains.
