### ISSUE TITLE
Is it safe to upgrade from 6.3.1 to 6.4.1?

### ISSUE THREAD

**Issue by yob** [mperham/sidekiq#5188]
We are running v6.3.1 in production and would like to upgrade to get the DOS upgrade first shipped in v6.4.0. We were cautious about rushing into the upgrade due to #5138.

We notice the 6.4.1 has now been released, and the keyword arg support in 6.4.1 has been reverted (and removed from the 6.4.0 changelog).

Is it safe to assume we can upgrade from 6.3.1 to 6.4.1 to get the DOS fix, and jobs queued prior to the upgrade will execute as expected on sidekiq workers running 6.4.1?

**Comment by mperham** [comment]
That is the expectation. I’ve fixed everything reported.

**Comment by yob** [comment]
thanks!
