### ISSUE TITLE
sidekiqmon doesn't exit with non-zero exit code when there's an error

### ISSUE THREAD

**Issue by stephenwiebe** [mperham/sidekiq#5195]
It seems that sidekiqmon doesn't support connecting to a Redis URL that has transit encryption enabled. At least that's what I'm assuming is going on:

```
/shopvox # REDIS_URL=redis://master.xxx.use1.cache.amazonaws.com:6379/0 sidekiqmon
Sidekiq 6.4.0
2022-02-11 18:16:21 UTC

---- Overview ----
Couldn't get status: Connection timed out
```

I wonder if there could be an optional flag added to sidekiqmon that would allow us to attempt the connection with SSL enabled?

Ruby version: 2.6.6
Rails version: 6.0.4
Sidekiq / Pro / Enterprise version(s): 6.4.0

**Comment by stephenwiebe** [comment]
That works, thank you! This might be a separate issue/request, but I'd like to use sidekiqmon as a container health check. I noticed when it errored out, the exit status code was still 0. I can set my health check to grep the output for what I'm expecting, but it'd be easier to just check for a non-zero sidekiqmon exit code. What do you think?

**Comment by mperham** [comment]
Send a PR
