### ISSUE TITLE
Strict argument check raises JSON::GeneratorError error on binary data

### ISSUE THREAD

**Issue by dbackeus** [mperham/sidekiq#5201]
Ruby version: 3.1.0
Rails version: 6.1.4.6
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 5.3.1

We're running a Rails app with a GraphQL API. The GraphQL API has a tracer plugin to post metrics to [Apollo Studio](**url**). The way the tracer works is it Protobuf encodes incoming metrics, then gzips the protobuf and passes the payload into a Sidekiq worker as an argument to `perform_async`.

In our Sidekiq upgrade branch we started getting Invalid Unicode errors all over the place, eg:
```
     Failure/Error: ApolloTracing::UploadWorker.set(log_level: :warn).perform_async(body, headers)
     
     JSON::GeneratorError:
       Invalid Unicode [8b 08 00 1a 15] at 1
```

We can circumvent the error by disabling the new strict argument check by adding `Sidekiq.strict_args!(false)` to an initializer. However I guess the intent of the check is to just display a warning (and then raise in Sidekiq 7), not to hit a JSON error while doing the check.

Also it would be nice if we didn't have to disable `strict_args` globally as it only affects this one Worker.

**Comment by mperham** [comment]
You need to Base64 that value. It's illegal JSON, full stop. Use Base64.[urlsafe_encode64](https://ruby-doc.org/stdlib-2.5.3/libdoc/base64/rdoc/Base64.html#method-i-urlsafe_encode64) to convert the binary data to something legal.
