### ISSUE TITLE
Can not Bump the pro/ent latest version 

### ISSUE THREAD

**Issue by BeastRush1231** [mperham/sidekiq#5206]
Ruby version: 3.0.0p0
Rails version: 6.1.4.6
Sidekiq / Pro / Enterprise version(s): 6.4.1

Hi Devs,

I try to upgrade my sidekiq-ent from `2.3.0` to `2.3.1` and sidekiq-pro from `5.3.0` to `5.3.1`,
refer the guideline to UPGRADE https://sidekiq.org/products/enterprise.html, still can not bump the version.

Where is the problem? I see the changelog has the latest version.

**Comment by adamniedzielski** [comment]
Would you mind posting the stacktrace of the error you’re getting?
