### ISSUE TITLE
Clarify custom Job Logger support and add to documentation

### ISSUE THREAD

**Issue by iMacTia** [mperham/sidekiq#5207]
Sidekiq allows to provide a custom `JobLogger` via its configuration:

```ruby
# my_custom_job_logger.rb
class MyCustomJobLogger < Sidekiq::JobLogger
  def call(item, queue)
    ...
  end
end

# initializer
config.options[:job_logger] = MyCustomJobLogger
```

This seems to be officially supported, and there's even a test for it:
https://github.com/mperham/sidekiq/blob/6a6fda35fa9d07c4fe8ed3b05609a0eba6781101/test/test_processor.rb#L319-L334

However, the Wiki does not mention it at all, and the latest 6.4.1 release [has broken its public interface](https://github.com/mperham/sidekiq/commit/01686c5e25dd83ab89c6d85b36feec26e203e81b#diff-ea165841c7daea83067e8903be22ed970caa75b69cf85d4e014691fcd827437c) despite being a bugfix release.

Right now it's unclear what should be considered safe when customizing the job logger to avoid surprises upon upgrading Sidekiq.
My guess is that it's OK to subclass `Sidekiq::JobLogger` and provide a custom `call` method, but it would be great if we could get an explicit mention of it in the Wiki and/or a guarantee that this won't change, at least until the next major version or a future v8.

**Comment by mperham** [comment]
Subclassing with a `call` method is the main public API. Other tiny helper methods were removed recently that shouldn't have been public. Apologies if you were using one of those.

I tend not to document options in the code if I don't want people using them without very good reason. This is one of those options.

**Comment by iMacTia** [comment]
Yeah I totally get this is one of those "features" that doesn't really fall into the core bucket, but especially in enterprise settings there are use-cases for custom logging (e.g. to comply with a company log taxonomy).

Thanks for clarifying, at least we now know it is OK to do so 👍 .
I'd only suggest to add a quick note on the Wiki, as this might help people to find this information if they need to. It's totally fine if it's together with a "please don't use it unless you necessarily need to" disclaimer.

The changes were also towards a performance improvement, so very much appreciated!
It was really just the surprise element that caught us, and unfortunately that also happened in production because the job logger doesn't seem to be called while running tests?
That's another thing I'd really like your input on, as it might help us writing a quick test and avoid this problem in future 🙏

**Comment by mperham** [comment]
Yeah, the JobLogger is part of Sidekiq's core which is typically not run in tests because it is multithreaded and quite heavyweight to start/stop. Job testing usually just invokes Job#perform directly. This is where a staging environment makes sense. Any suggestions for improvement are welcome.

**Comment by iMacTia** [comment]
Yeah I could imagine that was the issue. Staging environment sounds like the only option here.
Still it would be good to know we can expect the API to be respected until at least the next major/minor version 👍.
It would let us ship bugfix updates without having to go through staging, which would be great in a CD environment
