### ISSUE TITLE
Add exception class to Statsd increment in Sidekiq Pro?

### ISSUE THREAD

**Issue by jordan-brough** [mperham/sidekiq#5211]
When an error happens while processing a job it'd be helpful to have the error class sent to statsd as a tag, along with the other info that is already sent.

I believe this would involve adding something like an `error_class` tag inside the `rescue Exception` block in `Sidekiq::Middleware::Server::Statsd#call` in sidekiq-pro.

Is this something that you'd be willing to add to Sidekiq?

We can alternatively add something to `config.error_handlers` to do this, but that's a bit tedious and we'll essentially have duplicate events for `jobs.failure` and the error class seems like a reasonable thing to send by default?

**Comment by mperham** [comment]
I like this idea, it'll be in the next release. No ETA right now.

**Comment by mperham** [comment]
It's an `error_type` tag.

**Comment by jordan-brough** [comment]
Thank you!
