### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by dpep** [mperham/sidekiq#5213]
We are (tragically) still running Rails 5 and are a huge user of Sidekiq / Pro / Ent.  We would love to upgrade to Sidekiq 7, which claims to support older versions or Rails, but the CLI apparently does not.  Could Sidekiq please either support Rails 5 or remove the claim that it does?

https://github.com/mperham/sidekiq/blob/7-0/README.md?plain=1#L33
> Sidekiq 7.0 supports Rails 6.0+ but does not require it.

https://github.com/mperham/sidekiq/blob/7-0/lib/sidekiq/cli.rb#L269-L271
```ruby
if ::Rails::VERSION::MAJOR < 6
          raise "Sidekiq no longer supports this version of Rails"
```

**Comment by mperham** [comment]
7.0 is not ready for use.

I'm not sure I understand your confusion, the readme does say that you need rails 6+. 5 will not work.

**Comment by erchn** [comment]
I think the way the readme is written is slightly nebulous.  It support rails 6+ but you don't have to use Rails at all.  You could read it as Rails 6 is supported, but so are lower versions.  Fair to close the issue I think, sorry for the confusion @dpep .

**Comment by dpep** [comment]
haha, ok so apparently I just suck at english...apologies and thanks for clarifying

**Comment by adamniedzielski** [comment]
@dpep if it was confusing for you it may be confusing for somebody in the future 💛 And there are more programmers that are non-native English speakers (myself included) than native English speakers. It's good to overcommunicate sometimes.
