### ISSUE TITLE
CronParser#next reports incorrect time

### ISSUE THREAD

**Issue by cdonati** [mperham/sidekiq#5214]
Ruby version: 2.6.6
Rails version: 5.2.6.2
Sidekiq / Pro / Enterprise version(s): 6.4.1 / 5.3.1 / **2.3.1**

`#next` now appears to use the current offset when determining future invocations. For example, with my current -8 offset, `.next` for `* * * 5 *` reports that the job will be run on May 5 with a -8 offset.
```
>> Time.now
=> 2022-02-22 10:39:51 -0800
>> Sidekiq::CronParser.new('* * * 5 *').next
=> 2022-05-01 00:00:00 -0800
```

If I change my system clock to Mar 14, I get a different result:
```
>> Time.now
=> 2022-03-14 10:41:01 -0700
>> Sidekiq::CronParser.new('* * * 5 *').next
=> 2022-05-01 00:00:00 -0700
```

**Comment by mperham** [comment]
I can't stress how much I regret adding "support" for timezones in cron jobs. If you want predictability and smooth bug-free operation, don't use timezones. Use UTC.

**Comment by mperham** [comment]
Going to close this as WONTFIX. DST is being phased out and I don't want to regress any other edge cases.

**Comment by mbarany** [comment]
Unfortunately DST is not yet phased out and we found this out today. Expecting a job to run at midnight (in New York) every day works well when there are 24 hours in the day, but not when there are 25 🥲 

![image](https://github.com/user-attachments/assets/a8b5d5f8-6da8-4ba2-9e04-9f5d0365fe9c)
