### ISSUE TITLE
Sidekiq-pro question: batch metrics not increased without explicit callback

### ISSUE THREAD

**Issue by TomNaessens** [mperham/sidekiq#5217]
Ruby version: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21]
Rails version:  6.1.4.6
Sidekiq / Pro / Enterprise version(s): sidekiq (6.4.1) / sidekiq-pro (5.3.1)

Hi,

A question:
Is it by design that the Sidekiq-pro batch metrics only increase when a batch job has explicit callbacks defined? 

Context:
We'd like to add some Datadog metrics related to the success/completion/failure of a batch job. Checking the [Datadog Sidekiq documentation](https://docs.datadoghq.com/integrations/sidekiq/#data-collected), the following metrics should be available: `sidekiq.batch.created`, `sidekiq.batch.complete` and `sidekiq.batch.success`, but they didn't turn up in our metrics. 
Debugging for a bit, it seems like the batch metrics are only increased in the `execute_callback` method that only runs when there is at least one explicit callback defined.
I was expecting the callbacks to always be fired, regardless of any defined callbacks.
Additionally, if the metric is increased in each callback call, won't this result in the same batch job firing multiple metric increases when multiple of the same callbacks have been added, even though the batch has just completed "once"?

Thanks!

**Comment by adamniedzielski** [comment]
Without digging too much into your issue I’d say “no, it doesn’t seem
expected”.

What do you think about reporting it in
https://github.com/DataDog/dogstatsd-ruby as well and cross linking?

1. Datadog owns the documentation and the integration.
2. They may describe this edge case in their documentation as a short term
workaround.
3. They may even investigate it for a paying customer.
4. And then patch their integration.
5. Submitting a patch to Sidekiq will be hard unfortunately. The code of
Pro version is sadly not public (mind the difference between public and
open source) so you’d have to have access to Pro and send a patch file to
@mperham via email.

**Comment by TomNaessens** [comment]
Hi @adamniedzielski,

Thanks for your reply!

As I'm not familiar with the product and who owns what exactly: does DataDog maintain the code in Sidekiq-pro calling `Sidekiq::Pro.metrics` as well? If it's a bug, I think the offending code is in there and consequently unrelated to the dogstatsd library (or any other integration supported by the `Sidekiq::Pro.metrics`). 

I can still drop a ticket in https://github.com/DataDog/documentation so they're aware.

**Comment by adamniedzielski** [comment]
> does DataDog maintain the code in Sidekiq-pro calling Sidekiq::Pro.metrics as well

No, it's just @mperham.

> I think the offending code is in there

Have you already tried `bundle show sidekiq-pro` and fixing it?

**Comment by mperham** [comment]
Yep, I see your issue and I think I agree with your assessment. "batch.success" should increment, even without an explicitly defined callback, so people can see that their batches succeeded. Will be in the next Pro release.
