### ISSUE TITLE
Sidekiq 6.4.1 NoMethodError: undefined method `[]=' for nil:NilClass  /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:21:in `add'

### ISSUE THREAD

**Issue by thilton-oddball** [mperham/sidekiq#5220]
Ruby version: 2.7.4
Rails version: 6.1.4.6
Sidekiq / Pro / Enterprise version(s): 6.4.1

`Error`
Failure/Error: super(item, queue)

NoMethodError: undefined method []=' for nil:NilClass /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:21:in add' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:18:in rescue in call' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:9:in call' ./lib/sidekiq/semantic_logging.rb:19:in block in call' /usr/local/bundle/gems/semantic_logger-4.10.0/lib/semantic_logger/semantic_logger.rb:395:in named_tagged' /usr/local/bundle/gems/semantic_logger-4.10.0/lib/semantic_logger/base.rb:196:in tagged' ./lib/sidekiq/semantic_logging.rb:18:in call' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in block in invoke' ./lib/sidekiq/downtime_checker_middleware.rb:10:in call' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in block in invoke' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in invoke' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:294:in process_job' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:89:in block in raw_push' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:85:in each' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:85:in raw_push' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/client.rb:77:in push' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/worker.rb:358:in client_push' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/worker.rb:196:in perform_async' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/worker.rb:289:in perform_async' ./modules/appeals_api/app/services/appeals_api/events/handler.rb:19:in handle!' ./modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb:198:in update_status!' ./modules/appeals_api/spec/mailers/daily_error_report_mailer_spec.rb:19:in block (6 levels) in <top (required)>' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:16:in __set_test_mode' /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/testing.rb:34:in inline!' ./modules/appeals_api/spec/mailers/daily_error_report_mailer_spec.rb:18:in block (5 levels) in <top (required)>' /usr/local/bundle/gems/timecop-0.9.4/lib/timecop/timecop.rb:201:in travel' /usr/local/bundle/gems/timecop-0.9.4/lib/timecop/timecop.rb:129:in send_travel' /usr/local/bundle/gems/timecop-0.9.4/lib/timecop/timecop.rb:50:in freeze' ./modules/appeals_api/spec/mailers/daily_error_report_mailer_spec.rb:17:in block (4 levels) in <top (required)>' ./spec/rails_helper.rb:57:in with_settings' ./modules/appeals_api/spec/mailers/daily_error_report_mailer_spec.rb:12:in block (3 levels) in <top (required)>' /usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in block (2 levels) in <top (required)>' /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in block in run' /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in loop' /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in run' /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in run_with_retry' /usr/local/bundle/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in block (2 levels) in setup'

--- Caused by: ---
NoMethodError:
  undefined method `[]=' for nil:NilClass
  /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:21:in add

`config/initializers/sidekiq.rb`
require 'sidekiq_stats_instrumentation/client_middleware'
require 'sidekiq_stats_instrumentation/server_middleware'
require 'sidekiq/retry_monitoring'
require 'sidekiq/error_tag'
require 'sidekiq/semantic_logging'
require 'sidekiq/set_request_id'
require 'sidekiq/set_request_attributes'
require 'sidekiq/downtime_checker_middleware'

Rails.application.reloader.to_prepare do
  Sidekiq::Enterprise.unique! if Rails.env.production?

  Sidekiq.configure_server do |config|
    config.redis = REDIS_CONFIG[:sidekiq]
    config.super_fetch! if defined?(Sidekiq::Pro)

    config.on(:startup) do
      Sidekiq.schedule = YAML.safe_load(
        ERB.new(File.read(File.expand_path('../sidekiq_scheduler.yml', __dir__))).result
      )
      Sidekiq::Scheduler.reload_schedule!
    end

    config.server_middleware do |chain|
      chain.add Sidekiq::DowntimeCheckerMiddleware
      chain.add Sidekiq::SemanticLogging
      chain.add SidekiqStatsInstrumentation::ServerMiddleware
      chain.add Sidekiq::RetryMonitoring
      chain.add Sidekiq::ErrorTag
    end

    config.client_middleware do |chain|
      chain.add SidekiqStatsInstrumentation::ClientMiddleware
    end
  end

  Sidekiq.configure_client do |config|
    config.redis = REDIS_CONFIG[:sidekiq]

    config.client_middleware do |chain|
      chain.add SidekiqStatsInstrumentation::ClientMiddleware
      chain.add Sidekiq::SetRequestId
      chain.add Sidekiq::SetRequestAttributes
    end

    config.error_handlers.delete_if { |handler| handler.is_a?(Sidekiq::ExceptionHandler::Logger) }
  end
end

`sidekiq.yml`
---
:concurrency: 16

**Comment by mperham** [comment]
It looks like you're executing server middleware not within the Sidekiq server but inside your test suite. That's not a supported mode of operation. Things can break from release to release. In this case if you want to run `job_logger.call`, you have to call `job_logger.prepare` first. I don't know what `Sidekiq::SemanticLogging` is but I'd look into it.
