### ISSUE TITLE
Introduce `Sidekiq::Config`

### ISSUE THREAD

**Issue by adamniedzielski** [mperham/sidekiq#5225]
First step towards https://github.com/mperham/sidekiq/issues/4758, see https://github.com/mperham/sidekiq/issues/4758#issuecomment-1046208730 for the explanation on why I think it's the most reasonable first step.

Regardless of the topic of running Sidekiq client and server next to each other I see the following benefits:
1. easy to find - you search for config and it has its own file / module / class / concept. You want to add new config option, you know where it should go
2. clean the code up a bit internally and make it visible which config options come from the command line, YAML, initializer
3. make it explicit which options apply to server-only, to client-only, or to both
4. differentiate between "scalar" config values (boolean flag, array of queues) and "vector" values (default Redis connection pool). The labels "scalar" and "vector" help me, because I studied some physics and this metaphor resonates with me, but maybe somebody has a better naming suggestion for this kind of distinction?
5. making the God of Immutable Objects happy. I could write more here, but I'm going to save my time by turning this point into a joke and I can pull it through

@mperham before I move forward with the implementation I wanted to check in with you:

1. Are you in general onboard with the idea of introducing `Sidekiq::Config`?
2. Do you have any expectations ("I need X to be satisfied so I can accept the PR")?
3. Do you have any personal wishes ("It's a good opportunity to also do Y")?
4. Do you have any blessings for me ("Z is going to be dragons, but good luck with that!")?

**Comment by mperham** [comment]
I like where you’re going here. I dislike the global Sidekiq.options blob and seeing people muck about with it. Really grinds my gears.

**Comment by mperham** [comment]
As long as we continue to support the existing documented config knobs, I’m happy with any refactoring that might clean up configuration, esp if it better enables embedding Sidekiq. Today Sidekiq really doesn’t have a supported way to start a Sidekiq instance within another process (e.g. starting Sidekiq within a puma process).
