### ISSUE TITLE
Set Thread.current in the logger.rb

### ISSUE THREAD

**Issue by RachalCassity** [mperham/sidekiq#5226]
Ruby version: 2.7.4
Rails version: 6.1.4.6
Sidekiq / Pro / Enterprise version(s): 6.4.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```
# frozen_string_literal: true

require 'sidekiq'
require 'sidekiq/job_logger'

class Sidekiq::SemanticLogging < Sidekiq::JobLogger
  def call(_worker, item, queue)
    logger_tags = {
      class: item['class'],
      jid: item['jid'],
      request_id: item['request_id'],
      remote_ip: item['remote_ip'],
      user_agent: item['user_agent'],
      user_uuid: item['user_uuid'] || 'N/A',
      source: item['source']
    }


    @logger.tagged(**logger_tags) do
      super(item, queue)
    end
  end
end

```

My Team and I have been trying to debug this issue since we have upgraded to Sidekiq 6.4.1.  Degbugging in rspec, I noticed that in my config file, when running **Sidekiq::Context.add(:elapsed, elapsed(start))**, I would get this error: NoMethodError: undefined method `[]=' for nil:NilClass.

Looking through the Sidekiq code, I noticed Thread.current[:sidekiq_context] was nil. This cannot be nil, this should be defined as a hash.

The following is my debugging:

 [19] pry(#<Sidekiq::SemanticLogging>)> Sidekiq::Context.add(:elapsed, elapsed(start))
NoMethodError: undefined method `[]=' for nil:NilClass
from /Users/rachalcassity/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:21:in `add'
[20] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context]
=> nil
[21] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context][:elasped]
NoMethodError: undefined method `[]' for nil:NilClass
from (pry):21:in `call'
[22] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context]
=> nil
[23] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context] = 1
=> 1
[24] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context] ||= {} 
=> 1
[25] pry(#<Sidekiq::SemanticLogging>)> Sidekiq::Context.add(:elapsed, elapsed(start))
NoMethodError: undefined method `[]=' for 1:Integer
Did you mean?  []
from /Users/rachalcassity/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:21:in `add'
[26] pry(#<Sidekiq::SemanticLogging>)> Thread.current[:sidekiq_context] = {} 
=> {}
[27] pry(#<Sidekiq::SemanticLogging>)> Sidekiq::Context.add(:elapsed, elapsed(start))
=> 136.445

**Comment by mperham** [comment]
Do you see the new prepare method in JobLogger? Do you see how Sidekiq::Processor calls prepare before calling call?

None of these internals are documented public APIs and can change from version to version. Use a server middleware if you want a solid foundation.

**Comment by RachalCassity** [comment]
> Do you see the new prepare method in JobLogger? Do you see how Sidekiq::Processor calls prepare before calling call?
> 
> None of these internals are documented public APIs and can change from version to version. Use a server middleware if you want a solid foundation.

I appreciate everything you have done for Sidekiq. I was just looking at this:

```
    def self.current
      Thread.current[:sidekiq_context] ||= {}
    end

    def self.add(k, v)
      Thread.current[:sidekiq_context][k] = v
    end
```
I was assuming self.add should reference the current method. 
    def self.add(k, v)
      logger.current[k] = v
    end
