### ISSUE TITLE
Strict argument warning doesn't log the correct class name

### ISSUE THREAD

**Issue by rahul342** [mperham/sidekiq#5228]
Ruby version: 2.7.5
Rails version: 6.0.4.6
Sidekiq / Pro / Enterprise version(s): 6.4.0

If you are using an old version, have you checked the changelogs to see if your issue has [been fixed in a later version?
> yes

### What is happening?

[This line](https://github.com/mperham/sidekiq/blob/5776c7ae8711e14959d880dd907c9e79709d5b41/lib/sidekiq/job_util.rb#L24) logs `item['class']` which prints 
``` Job arguments to ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper do not serialize to JSON safely ```.  It's the same log irrespective of the job class. The class name is not useful.

### Expectation?
Looking at the `item` param, should we log `item['wrapped']` in the warning for ActiveJob case? Apologies if I am missing something in our config and this is not a bug.

**Comment by mperham** [comment]
💯 Send a PR?

**Comment by rahul342** [comment]
@mperham sure thing. Will create one.

**Comment by rahul342** [comment]
@mperham https://github.com/mperham/sidekiq/pull/5235, I couldn't figure how to get the activejob test working.
