### ISSUE TITLE
How to clean out these Busy jobs. 

### ISSUE THREAD

**Issue by resistorsoftware** [mperham/sidekiq#5237]
Ruby version: 3.1.1
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 6.4.1

My initializer for Sidekiq is:

    require "sidekiq"

    Sidekiq.configure_client do |config|
      config.redis = {size: 1}
    end

     Sidekiq.configure_server do |config|
       config.redis = {size: 12}
     end

This is running on 2 Dynos at Heroku with the procfile: worker: bundle exec sidekiq -c 3

I have no idea what I have done, but I did it. I have 3 jobs in busy status. I cannot kill them. I cannot seemingly do anything. I am stuck. My dashboard shows this:
<img width="1245" alt="Screen Shot 2022-03-09 at 6 56 56 PM" src="https://user-images.githubusercontent.com/123307/157559870-22321523-800d-4549-9cb5-7017dc02e804.png">

No matter what I try, these things persist. What the heck do I do to kill these things? I started them just at my heroku command line using 

     SalesReportJob.perform_later(params)

Thinking I could just monitor what happened.. instead these jobs are like zombies!!

**Comment by mperham** [comment]
Restarting Sidekiq will typically clear them out.

**Comment by resistorsoftware** [comment]
I ran a heroku ps:restart to document what happens. What happens is this...

workers boot... then I see:

**Comment by mperham** [comment]
That's right. Sidekiq does its best to not lose jobs. Your jobs aren't finishing so you'll need to debug and figure out why. I'm not sure the best way to debug in production on Heroku.

**Comment by resistorsoftware** [comment]
So the only recourse, is to let these 3 jobs sit there forever? Wow. I guess I can always just delete Redis. That should do the trick.

**Comment by resistorsoftware** [comment]
Simply by fixing the job, they all finished. All clean now. Thanks!

**Comment by mperham** [comment]
Or deploy a fix. Or deploy a change that adds “return” to the top of the
perform method. Or use the Queue API to clear all the jobs in that queue
after shutting down Sidekiq.
