### ISSUE TITLE
Serialization warning using oj gem

### ISSUE THREAD

**Issue by Pimentoso** [mperham/sidekiq#5240]
Ruby version: 3.0.2
Rails version: 6.1.4.6
Sidekiq / Pro / Enterprise version(s): sidekiq 6.4.1, pro 5.3.0

I'm using the oj gem in my project to speed up JSON serialization. I was getting random serialization warnings from sidekiq
```
Job arguments to MyApp::RealtimeJob do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```

Turned out because the payload contains a float for created_at, which can randomly have 5, 6 or 7 decimals
```
        {"queue"=>"development-default",
         "class"=>"MyApp::RealtimeJob",
         "args"=>[{"id"=>684}],
         "jid"=>"d44254e2a44b81570f9c5cd9",
         "created_at"=>1645714939.1176121}
```

The `json_safe?` check that is done to raise the warning fails when there are 7 decimals, because with oj is truncated to 6 decimals (I get `"created_at"=>1645714939.117612` for the case above)

Is there a point in having `created_at` value this precise? Could it just be rounded to 3/4/5 decimals safely? From what I've seen in the code, it's only used to calculate job latency.

**Comment by mperham** [comment]
I would recommend removing the oj gem or disabling JSON mimicking. I don't believe the different is significant enough to use it. The benchmarks I've seen are from 8-9 years ago, do you know of any modern benchmarks with e.g. Ruby 3?

https://github.com/ohler55/oj/blob/develop/pages/JsonGem.md#json-quickstart

**Comment by wspurgin** [comment]
Hi just a lurker (and not advocating for a mimic JSON), but just to answer the question asked about modern benchmarks... I don't know, [but I threw one together](https://gist.github.com/wspurgin/21a651906155254d11de6326288fd119) with just the gems and `benchmark`

```
Host OS: darwin19
Ruby Version 3.0.3
OJ version 3.13.11
JSON version 2.6.1
Number of iterations: 100000
                     user     system      total        real
Oj.load          0.460000   0.000802   0.460802 (  0.461237)
JSON.load        0.679385   0.001759   0.681144 (  0.681957)
OJ-per-parse     0.000005   0.000000   0.000005 (  0.000005)
JSON-per-parse   0.000007   0.000000   0.000007 (  0.000007)
Oj parses/sec 217012.9469924176
JSON parses/sec 146811.8342083319
                     user     system      total        real
Oj.dump          0.260016   0.003615   0.263631 (  0.263895)
JSON.dump        0.513998   0.003328   0.517326 (  0.517703)
OJ-per-gen       0.000003   0.000000   0.000003 (  0.000003)
JSON-per-gen     0.000005   0.000000   0.000005 (  0.000005)
Oj gens/sec 379318.0619881576
JSON gens/sec 193301.70917371253
```

🤷 Seems to be generally faster than the latest `JSON::Ext` in Ruby 3 (The code that generated [those comparisons](http://www.ohler.com/dev/oj_misc/performance_strict.html from 8-9 years ago isn't anywhere I could quickly find).
