### ISSUE TITLE
Sidekiq-ent 1.8 memory leak 

### ISSUE THREAD

**Issue by alexrobinson-drizly** [mperham/sidekiq#5243]
Hello, we are running ruby 2.7.2, rails 5.2.2, and sidekiq-ent 1.8. 

On one of our queues that we have labeled "Heavy", there is a constant memory leak happening that stops the application after a day or so of use which requires a reboot to mitigate each time.

How can we go about resolving this issue with sidekiq? Can you let us know what other additional information you would require to help solve this issue?

**Comment by mperham** [comment]
Please review https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting

**Comment by mperham** [comment]
Is there some reason you have not upgraded to a recent version?

**Comment by alexrobinson-drizly** [comment]
I spoke to my management, and there are other dependencies needed before updating to the latest version. Has this issue been solved in a newer release?

**Comment by mperham** [comment]
Sidekiq has not had an actual memory leak in its source code for many years. I am almost 100% sure this is something to do with the gems or application code you are using. Have you tuned Malloc arena Max yet as recommended by the problems and troubleshooting wiki page?
