### ISSUE TITLE
Strict arguments and middleware

### ISSUE THREAD

**Issue by benedikt** [mperham/sidekiq#5246]
We're using a custom middleware layer to serialize/deserialize Ruby objects into strict JSON payloads. Unfortunately, with the recent changes to how strict arguments are enforced, this now raises a deprecation warning. 

While I fully understand and appreciate the tighter checks, I was wondering if it would make sense to do them _after_ the middleware chain or _as a part of_ the middleware chain?

This would still allow implementing custom serialization/deserialization schemes while also ensuring that only valid JSON gets into Sidekiq's core.

**Comment by mperham** [comment]
Can you give me more detail about your middleware? What deprecation warning?

**Comment by benedikt** [comment]
The middleware is converting objects that implement `GlobalID::Identification` into a known JSON object and vice-versa. 

The deprecation warning I'm getting is this: 

```
WARN: Job arguments to DemoWorker do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```

**Comment by mperham** [comment]
Ah, I see. You are using a middleware to convert unsupported arguments into something which will safely serialize. So you need the validation to occur after the middleware runs. Got it and I agree 💯, will fix.

**Comment by keiko713** [comment]
Thanks for the quick fix on this! We're hitting the same issue and glad that it's fixed now. I wonder if you have a plan to cut a new version release with this change, so that we can use this fix.

**Comment by mperham** [comment]
You can run main for now. I don’t plan a release in the next week.
