### ISSUE TITLE
Can different major versions cause issues with web UI?

### ISSUE THREAD

**Issue by silent-e** [mperham/sidekiq#5255]
Ruby version: 2.4.10
Rails version: 4.2.11.3
Sidekiq / Pro / Enterprise version(s): 
  * sidekiq (5.2.8)
  * sidekiq-ent (1.8.1)
  * sidekiq-pro (4.0.5)

Is it necessary for all instances of Sidekiq used across separate installed services to be running the same major version?  I have three services sending jobs to each other.  Two installs running the latest major versions of the gems and one website running the versions listed above.  This last website is the one running the web UI and I'm getting the following error when looking at a job in the Retry panel.

```
NoMethodError (undefined method `join' for #<String:0x0000000004683838>):
  (eval):23:in `_erb_retry'
  sidekiq (5.2.8) lib/sidekiq/web/action.rb:85:in `_erb'
  sidekiq (5.2.8) lib/sidekiq/web/action.rb:54:in `erb'
  sidekiq (5.2.8) lib/sidekiq/web/application.rb:172:in `block in <class:WebApplication>'
  sidekiq (5.2.8) lib/sidekiq/web/application.rb:287:in `instance_exec'
  sidekiq (5.2.8) lib/sidekiq/web/application.rb:287:in `block in call'
  sidekiq (5.2.8) lib/sidekiq/web/application.rb:283:in `catch'
  sidekiq (5.2.8) lib/sidekiq/web/application.rb:283:in `call'
```

Unfortunately, I am unable to upgrade this website right now.  The jobs execute fine, it's just when I'm trying to see the details of an individual retry.

matte

**Comment by mperham** [comment]
Yes, in general there’s no attempt to make the Web UI of one major version
work with data from another major version.  If you have a problem with
different minor versions, I’d be more willing to accept that as a bug.

All that said, I’d be happy to consider a PR which restores backwards
compatibility if the code is relatively easy/clean. No one wants to
maintain a mess of hacks forever, that’s one reason for major version
bumps: to remove hacks.

**Comment by silent-e** [comment]
Good to hear about compatibility.  Do you have any thoughts on why we're getting the error.  I was able to replicate it locally where I have a Better Errors error page and the local variables listing has an `_erbout` key with the following value

`"<header>\n <h3>Job</h3>\n</header>\n\n<div class=\"table_container\">\n <table class=\"table table-bordered table-striped\">\n <tbody>\n <tr>\n <th>Queue</th>\n <td>\n <a href=\"/admin/sidekiq/queues/intake\">intake</a>\n </td>\n </tr>\n <tr>\n <th>Job</th>\n <td>\n <code>SampleExceptionJob</code>\n </td>\n </tr>\n <tr>\n <th>Arguments</th>\n <td>\n <code class=\"code-wrap\">\n \n <div class=\"args-extended\"></div>\n </code>\n </td>\n </tr>\n <tr>\n <th>JID</th>\n <td>\n <code>366a0e7619a3fd4180d0d8f4</code>\n </td>\n </tr>\n <tr>\n <th>Created At</th>\n <td><time class=\"ltr\" dir=\"ltr\" title=\"2022-03-24T04:19:06Z\" datetime=\"2022-03-24T04:19:06Z\">2022-03-24 04:19:06 UTC</time></td>\n </tr>\n <tr>\n <th>Enqueued</th>\n <td><time class=\"ltr\" dir=\"ltr\" title=\"2022-03-24T19:06:34Z\" datetime=\"2022-03-24T19:06:34Z\">2022-03-24 19:06:34 UTC</time></td>\n </tr>\n \n <tr>\n <th>Extras</th>\n <td>\n <code>\n {\"unique_for\"=>\"3600\", \"unique_token\"=>\"8b78d96d7e9423107a3ca363abc576edbc29e263\", \"unlocks_at\"=>\"1648099146.199952\"}\n </code>\n </td>\n </tr>\n \n \n \n <tr>\n <th>Retry Count</th>\n <td>3</td>\n </tr>\n <tr>\n <th>Last Retry</th>\n <td><time class=\"ltr\" dir=\"ltr\" title=\"2022-03-24T19:06:34Z\" datetime=\"2022-03-24T19:06:34Z\">2022-03-24 12:06:34 -0700</time></td>\n </tr>\n \n <tr>\n <th>Next Retry</th>\n <td><time class=\"ltr\" dir=\"ltr\" title=\"2022-03-24T19:08:42Z\" datetime=\"2022-03-24T19:08:42Z\">2022-03-24 19:08:42 UTC</time></td>\n </tr>\n \n \n \n </tbody>\n </table>\n</div>\n\n\n<h3>Error</h3>\n<div class=\"table_container\">\n <table class=\"error table table-bordered table-striped\">\n <tbody>\n <tr>\n <th>Error Class</th>\n <td>\n <code>StandardError</code>\n </td>\n </tr>\n <tr>\n <th>Error Message</th>\n <td>text exception from a sidekiq job at 2022-03-24 12:06:34 -0700</td>\n </tr>\n \n <tr>\n <th>Error Backtrace</th>\n <td>\n <code>"
`

Is this the string that `join` is trying to be called on?

**Comment by mperham** [comment]
More than anything, I need the exact backtrace and the version you are
using.

**Comment by silent-e** [comment]
I'm pretty sure I've figured it out.  It's definitely incompatibility between jobs created in v6 being displayed in a v5 install.

In commit https://github.com/mperham/sidekiq/commit/251be7dd02c07b5780a7aa10e92fe062689b14a8 the method of storing the backtrace changed in `lib/sidekiq/job_retry.rb` from a basic Array to a compressed/base64 string.  The jobs I'm trying to display were created in v6 but the web ui in v5 is expecting the backtrace data to be an array.  v6 goes through an `uncompress_backtrace` method that turns it back into an array.

The `uncompress_backtrace` method in v6 is backward compatible with v5 array-based backtraces but, understandably, v5 is not forward compatible.

**Comment by mperham** [comment]
Right, I do make some effort for newer versions to work with older data so users can migrate up without issue but forward compatibility is impossible. As I noted before, I do not recommend or support using different versions at the same time.
