### ISSUE TITLE
Changing RSS Info Link in Web UI to Target Blank

### ISSUE THREAD

**Issue by pmichaeljones** [mperham/sidekiq#5263]
I love using Sidekiq and I'd like to submit a pull request, but you mention asking first before investing the time to write the code. 

When clicking the question mark RSS info button on the web UI, I think it should open in a new tab, instead of taking us away from the web UI in localhost. Then there's no need to click BACK after reading the [RSS info page.](https://github.com/mperham/sidekiq/wiki/Memory#rss).

If I submit a PR, would it be accepted? Does it fit your design goals?

Thanks 

-Patrick

<img width="643" alt="Screen Shot 2022-03-25 at 4 43 25 PM" src="https://user-images.githubusercontent.com/6728265/160153950-36af454e-cc62-4e9d-9d18-06ec8158786c.png">

<img width="605" alt="Screen Shot 2022-03-25 at 4 44 14 PM" src="https://user-images.githubusercontent.com/6728265/160154104-a0fac3f5-3d03-495f-bb3b-793319b89d22.png">

**Comment by mperham** [comment]
💯 👍🏻

**Comment by pmichaeljones** [comment]
Great! I'll submit a PR this weekend.

**Comment by pmichaeljones** [comment]
Hi Mike. Forgive my naivety. 

I forked the repo to make my fix and I'm setting it up on my local machine. Am I to understand that myapp is a basic rails app inside the Sidekiq repo that uses the Sidekiq code from the local repo? 

`gem 'sidekiq', :path => '..'`

Meaning, I will be able to make changes to the Sidekiq UI code and see it by launching "rails s" inside the myapp folder and then going to "/sidekiq"

If I've understood correctly, maybe I can add some wording to the contributing page as well to help explain to novices like myself how to get up and running the first time when contributing to Sidekiq.

**Comment by mperham** [comment]
Yes, that’s exactly right.

**Comment by mperham** [comment]
I think it’s a great idea, go for it.
