### ISSUE TITLE
Host specific queue configuration generating an error

### ISSUE THREAD

**Issue by jackruder** [mperham/sidekiq#5265]
I am working in a project using sidekiq, and having issues starting the sidekiq worker when including the line   - <%= \`hostname\`.strip %> as a queue in sidekiq.yml.

bundle exec sidekiq generates the following:

2022-03-27T19:55:25.197Z pid=50812 tid=17xo WARN: Errno::ENOENT: No such file or directory - hostname
2022-03-27T19:55:25.197Z pid=50812 tid=17xo WARN: /home/jack/project/config/sidekiq.yml:18:in \`\`'
/home/jack/project/config/sidekiq.yml:18:in \`<main>\'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/3.1.0/erb.rb:905:in \`eval'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/3.1.0/erb.rb:905:in \`result'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:385:in \`parse_config'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:250:in \`setup_options'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:24:in \`parse'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.1/bin/sidekiq:27:in \`<top (required)>'
/home/jack/.rbenv/versions/3.1.0/bin/sidekiq:25:in \`load'
/home/jack/.rbenv/versions/3.1.0/bin/sidekiq:25:in \`<top (required)>'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in \`load'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in \`kernel_load'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in \`run'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in \`exec'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in \`run'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in \`invoke_command'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in \`dispatch'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in \`dispatch'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in \`start'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in \`start'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:48:in \`block in <top (required)>'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in \`with_friendly_errors'
/home/jack/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:36:in \`<top (required)>'
/home/jack/.rbenv/versions/3.1.0/bin/bundle:25:in \`load'
/home/jack/.rbenv/versions/3.1.0/bin/bundle:25:in \`<main>'

Here is the sidekiq.yml file:

---
:verbose: false
:concurrency: 10

:timeout: 30

:queues:
  - critical
  - default
  - <%= \`hostname\`.strip %>
  - mailers
  - low

production:
  :concurrency: 25
staging:
  :concurrency: 15

The <%= \`hostname\`.strip %> is the line causing issues, even if I comment it out the issues are still there. Removing the line allows sidekiq to boot without issue.

I am new to rails and trying to jump into a project using sidekiq so its very possible the issue lies in some mistake in configuring my development environment and setting up dependencies, (which seems likely since others do not have this issue). I am on arch linux if that is relevant.

Thanks

**Comment by mperham** [comment]
You need to wrap hostname in backticks.

**Comment by jackruder** [comment]
It is wrapped, github uses double backticks to markdown code, I am going through trying to escape all of them. Sorry about that

**Comment by jackruder** [comment]
I edited my initial issue to escape the backticks, \' lets you markdown code in github and I forgot to escape them when I copy-pasted

**Comment by mperham** [comment]
Presumably the container or system you are running in does not have the hostname binary available in the PATH for you to run. You can try running https://ruby-doc.org/stdlib-3.0.1/libdoc/socket/rdoc/Socket.html#method-c-gethostname

**Comment by jackruder** [comment]
When I run Socket.gethostname either via rails console or have its output displayed on the server, it outputs my machine's hostname, which is 'jackarch'. Seems like this works, unless I misunderstood what I should run.
