### ISSUE TITLE
Sidekiq tries to load gems from development and test groups of Gemfile in production environment

### ISSUE THREAD

**Issue by binhly** [mperham/sidekiq#5268]
Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
Rails version: 7.0.2.3
Sidekiq / Pro / Enterprise version(s): Sidekiq

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

Initializer
```
redis_config = Rails.application.config_for("redis")

Sidekiq.configure_server do |config|
  config.redis = { url: "redis://#{redis_config[:host]}:#{redis_config[:port]}/12" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://#{redis_config[:host]}:#{redis_config[:port]}/12" }
end
```

Sidekiq.yml
```
:queues:
  - meta
  - default
  - apns

production:
  :concurrency: 10
```

I'm currently running a Rails 7 application on ElasticBeanstalk on the latest platform version.  The application deploys and runs without an issue.

When I added Sidekiq into the mix deploys stopped working because Sidekiq is trying to load gems from the development and test groups of the Gemfile.

Running ExecStart command manual I see this:

**Could not find debug-1.4.0, irb-1.4.1, reline-0.3.1, io-console-0.5.11 in any of the sources
Run `bundle install` to install missing gems.**

To trigger the failed deploy so that I could grab the error message I uncommented the "debug" gem in the Gemfile.

If I comment out all of the gems in the development and test groups of the Gemfile deploys work and Sidekiq starts successfully.

This is my ExecStart

`ExecStart=/bin/bash -lc "export RAILS_ENV=production && export APP_DATABASE_URL=$(/opt/elasticbeanstalk/bin/get-config environment -k APP_DATABASE_URL) && export APP_DATABASE_PASSWORD=$(/opt/elasticbeanstalk/bin/get-config environment -k APP_DATABASE_PASSWORD) && export RAILS_MASTER_KEY=$(/opt/elasticbeanstalk/bin/get-config environment -k RAILS_MASTER_KEY) && export APP_REDIS_URL=$(/opt/elasticbeanstalk/bin/get-config environment -k APP_REDIS_URL) && exec /opt/elasticbeanstalk/.rbenv/shims/bundle exec sidekiq -e production"`

Has anyone experienced anything like this before?  Or have any pointers on how I could resolve this?

Thanks

**Comment by mperham** [comment]
Sidekiq does not call or use any Bundler APIs at all. Your problem is likely in `config/application.rb` where Rails calls Bundler to load environment-specific gems.

```ruby
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
```

**Comment by binhly** [comment]
You were right.  Thanks for the tip.
