### ISSUE TITLE
Token encoding/decoding issues with Rack::Protection::AuthenticityToken

### ISSUE THREAD

**Issue by dominikb** [mperham/sidekiq#5273]
Ruby version: 2.7.2
Rails version: 6.1.1
Sidekiq / Pro / Enterprise version(s): 6.4.1
[rack/protection](https://github.com/sinatra/sinatra/tree/master/rack-protection): 2.2

CSRF tokens generated by rack/protection are [reused](https://github.com/mperham/sidekiq/blob/213977c46025aca6b46f1d132f1bc541fb8d9bf3/lib/sidekiq/web/csrf_protection.rb#L46-L53) by Sidekiq::Web::CsrfProtection and are then masked. 

We encountered an edge case where the base64 encoded token stored in `session(env)[:csrf]` contained a `+` or `/` that was replaced by `-` or `_` respectively and led to an error during decoding.

```ruby
"/w==" == Base64.strict_encode64("\xff")
"_w==" == Base64.urlsafe_encode64("\xff") # This is stored in session(env)[:csrf]

Base64.strict_decode64("_w==") # ArgumentError (invalid base64)
```

`csrf_protection.rb` should also use `Base64.urlsafe_encode64` and `Base64.urlsafe_decode64` to be compatible with `Sidekiq::Web::CsrfProtection`.

As a work-around, we patched the methods in our initializer:
```ruby
# config/initializers/sidekiq.rb
require 'sidekiq/web'
Sidekiq::Web::CsrfProtection.define_method(:decode_token) do  |token|
  Base64.urlsafe_decode64(token)
end
Sidekiq::Web::CsrfProtection.define_method(:encode_token) do |token|
  Base64.urlsafe_encode64(token)
end
```

<details>
<summary>Stacktrace</summary>
ArgumentError: invalid base64

from <internal:pack>:281:in `unpack1'

from vendor/ruby-2.7.2/lib/ruby/2.7.0/base64.rb:74:in `strict_decode64'

from sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb:172:in `decode_token'

from sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb:142:in `mask_token'

from sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb:51:in `admit'

from sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb:41:in `call'

from rack (2.2.3) lib/rack/static.rb:161:in `call'

from rack (2.2.3) lib/rack/builder.rb:244:in `call'

from sidekiq (6.4.1) lib/sidekiq/web.rb:108:in `call'

from sidekiq (6.4.1) lib/sidekiq/web.rb:113:in `call'

from actionpack (6.1.5) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'

from actionpack (6.1.5) lib/action_dispatch/routing/mapper.rb:49:in `serve'

from actionpack (6.1.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'

from actionpack (6.1.5) lib/action_dispatch/journey/router.rb:32:in `each'

from actionpack (6.1.5) lib/action_dispatch/journey/router.rb:32:in `serve'

from actionpack (6.1.5) lib/action_dispatch/routing/route_set.rb:842:in `call'

from omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'

from omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'

from omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'

from omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'

from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'

from warden (1.2.9) lib/warden/manager.rb:34:in `catch'

from warden (1.2.9) lib/warden/manager.rb:34:in `call'

from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'

from rack (2.2.3) lib/rack/etag.rb:27:in `call'

from rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'

from rack (2.2.3) lib/rack/head.rb:12:in `call'

...
</details>

**Comment by mperham** [comment]
The code has been this way for some time. Why has no one else reported this issue until now?

**Comment by mperham** [comment]
Ah, Sidekiq does not use rack/protection. Why are you using its tokens in Sidekiq::Web?

**Comment by dominikb** [comment]
I'm using rack/protection on the frontend. The flow is as follows:

- login at `myapp.com/login`
- successful login takes me to `myapp.com/dashboard`
- when navigating to `myapp.com/developers/sidekiq` a csrf token is already present in the active `rack.session` resolved [here](https://github.com/mperham/sidekiq/blob/213977c46025aca6b46f1d132f1bc541fb8d9bf3/lib/sidekiq/web/csrf_protection.rb#L68)

> The code has been this way for some time. Why has no one else reported this issue until now?

Honestly, I don't know. It may have to do with this happening scarcely? For me it also only happened when using rack/protetion in combination with `omniauth` for Google SSO but as I could not track down any the issue there.

**Comment by bessey** [comment]
I've also just runn into this, after upgrade the popular [Flipper](https://github.com/jnunemaker/flipper) gem to latest. Which resulted in rack-protection being upgrade from 2.0.8.1 to 2.2, so somewhere between those two this issue is introduced.

It has no changelogs, so I am solving just by pinning rack-protection to the older version for now.

Our stack trace, for reference:
```
ArgumentError
invalid base64

base64.rb in strict_decode64 at line 74

sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb in decode_token at line 172
sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb in mask_token at line 142
sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb in admit at line 51
sidekiq (6.4.1) lib/sidekiq/web/csrf_protection.rb in call at line 41
rack-protection (2.2.0) lib/rack/protection/xss_header.rb in call at line 18
rack-protection (2.2.0) lib/rack/protection/base.rb in call at line 50
1
rack-protection (2.2.0) lib/rack/protection/path_traversal.rb in call at line 16
rack-protection (2.2.0) lib/rack/protection/json_csrf.rb in call at line 26
rack-protection (2.2.0) lib/rack/protection/base.rb in call at line 50
rack-protection (2.2.0) lib/rack/protection/frame_options.rb in call at line 31
rack-protection (2.2.0) lib/rack/protection/base.rb in call at line 50
...
```

**Comment by andresgutgon** [comment]
☝️ This error just happened to me with Sidekiq 6.x . It solved by restarting Google Chrome 😂 . You have to love tech
