### ISSUE TITLE
Need Account Details

### ISSUE THREAD

**Issue by rprice330v8** [mperham/sidekiq#5276]
Hello Sidekiq!

I believe we have a company account with you but we aren't entirely sure if we do or who the admin would be. I'm the Head of Enterprise Applications and our engineers have expressed that we may need to upgrade or update our plan. Can you tell me if there is a business account for Prime Trust LLC with any admins that have the "@primetrust.com" domain?

Thank you,

Rob Price
Head of Enterprise Applications
214.914.6154 m
rprice@primetrust.com
https://primetrust.com

**Comment by mperham** [comment]
Hey Rob, you can always email ***@***.*** with account inquiries.
I’d be happy to help there to keep things private.
