### ISSUE TITLE
Mobile UI dropdown menu broken

### ISSUE THREAD

**Issue by tysliu** [mperham/sidekiq#5281]
Ruby version: 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin20]
Rails version: 7.0.2.2
Sidekiq / Pro / Enterprise version(s):
Community (6.4.1)
Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
<img width="1692" alt="Screen Shot 2022-04-12 at 12 02 33 PM" src="https://user-images.githubusercontent.com/68217/162878460-914caf75-d3d8-4b08-b344-53808c8c9a4b.png">

**Comment by mperham** [comment]
Send a PR to fix it? https://github.com/mperham/sidekiq/blob/b201ce54b21e911865377057ba1d7d2bdb46c5cd/lib/sidekiq/web/application.rb#L8
