### ISSUE TITLE
Latency vs Queue Length Issue

### ISSUE THREAD

**Issue by danmayer** [mperham/sidekiq#5282]
We had an incident that lead to our Redis filling up. Investigating various things, we thought we had tracked the issue down to our sidekiq calls looking like so `Sidekiq::Queue.new(queue_name).latency` when we drained the queue we had a pretty direct looking `1:1` correlation of queue_size decreasing along with the latency. In this setup the workers were isolated from the rest of production, IE no new jobs or anything was accessing this isolated Redis. We had workers connecting to it only to drain, in this process-only mode we collected some of the data.

I wrote a post about this and you commended on twitter that it shouldn't be true... After some additional investigation, it still seems like what we were observing.

* post: https://www.mayerdan.com/ruby/2022/04/10/redis-sidekiq
* thread: https://twitter.com/danmayer/status/1513561092026511367

I was thinking we could set up a simulation on an isolated deployment out of production with two queues and two jobs one that just logs a line and another that calls `Sidekiq::Queue.new(queue_name).latency` and logs the line and collect data to see if we observe the same sort of issue. Any thoughts on the best ways to dig in a bit more to further understand the problem? I am happy to help try to sort this out as I would like to better understand the issue as we are adding instrumentation and moving a large number of apps from resque to sidekiq, and it feels valuable to get a better grasp on things.

**Comment by mperham** [comment]
This is the LRANGE in question. Afaict it should be O(1) because it is only looking at the one element at the head of the list. I have had people see a little bit of variation in the call if the job payload happens to be quite large so the JSON parsing takes longer.

https://github.com/mperham/sidekiq/blob/152c3d8104295afc5b34ed9c190eaa85806b722f/lib/sidekiq/api.rb#L249

**Comment by danmayer** [comment]
hmm, yeah that really doesn't seem like it should be the culprit, going to see if I can find anything else that was also getting triggered in our instrumentation that would better explain it... 

The job payload is sort of interesting these are large messages, but that shouldn't have changed related to the queue size and stayed pretty consistent over the 5M jobs.

**Comment by danmayer** [comment]
looking into other calls, and confirmed that benchmarks of `conn.lrange(@rname, -1, -1)` show no impact on queue size.

**Comment by danmayer** [comment]
Well, I guess I will close this, I haven't been able to reproduce anything so far in my isolated tests. I still have a few other tests I could try, but may or may not have time to follow up.
