### ISSUE TITLE
Error while fetching jobs in particular host 

### ISSUE THREAD

**Issue by shekhar098** [mperham/sidekiq#5284]
We are trying to fetch the number of running jobs to host via  

ps = Sidekiq::ProcessSet.new.
ps.select {|p| p['hostname'] == hostname }.map {|p| p['busy'] }

But sometimes it throws the error randomly "no implicit conversion of nil into String (TypeError)"

from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/json-1.8.6/lib/json/common.rb:155:in `new'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/sidekiq-4.2.10/lib/sidekiq.rb:177:in `load_json'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/sidekiq-4.2.10/lib/sidekiq/api.rb:709:in `block (2 levels) in each'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/sidekiq-4.2.10/lib/sidekiq/api.rb:708:in `each'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/sidekiq-4.2.10/lib/sidekiq/api.rb:708:in `block in each'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/sidekiq-4.2.10/lib/sidekiq.rb:95:in `block in redis'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
from /home/ubuntu/.rvm/gems/ruby-2.3.1@base/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'

**Comment by mperham** [comment]
I don’t support Sidekiq 4 anymore. It’s over five years old now.
