### ISSUE TITLE
Question: SIDEKIQ_PRELOAD_APP configuration for forking

### ISSUE THREAD

**Issue by jongbeau** [mperham/sidekiq#5288]
Ruby version: 2.6.5
Rails version: 6.0.3
Sidekiq / Pro / Enterprise version(s): Sidekiq-ent 2.3.0

I'm reading the guide here:
https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#application-preload

I'd like to turn on `SIDEKIQ_PRELOAD_APP` to get some memory usage improvements, but I need to make sure i'm setting up our redis and database pools safely.

This is the general skeleton I have for `initializers/sidekiq.rb`:

```
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add SidekiqRequestStoreMiddleware
  end

  ActiveRecord::Base.connection_pool.disconnect!

  config.super_fetch!
  config.reliable_scheduler!

  config.on(:fork) do
    # this gets executed with sidekiqswarm, but not with regular sidekiq
    $redis_pool = ConnectionPool.new { Redis.new }
    ActiveRecord::Base.establish_connection()
  end

  config.on(:startup) do
    # do some initialization stuff on the leader
  end

  config.on(:shutdown) do
    # shutdown stuff
  end
end
```

My question is whether the `on(:fork)` block is the best place to initiate the global `$redis_pool` and establish the active record connection? In development, we don't run `sidekiqswarm` or `SIDEKIQ_PRELOAD_APP=1` so the `on(:fork)` never gets executed, so i'd rather move that into the `on(:startup)` block so it can work the same with `sidekiqswarm` or regular `bundle exec sidekiq`.

Any guidance?

Thanks!

**Comment by jongbeau** [comment]
I'm also curious what `SIDEKIQ_PRELOAD_APP=1` does with `sidekiqswarm`? I thought maybe it would run something like `Rails.application.eager_load!` but it happens too fast for that to be the case.

**Comment by mperham** [comment]
bundle open sidekiq-ent, lib/sidekiq-ent/swarm.rb

**Comment by mperham** [comment]
I don’t believe you need any :fork code with modern gems these days. Most gems auto-detect forking so you don’t need to worry about it. Please correct me if you know differently.

**Comment by jongbeau** [comment]
@mperham - I still need to put the redis and activerecord connection after the fork though, correct?

**Comment by mperham** [comment]
That’s what I’m saying, I don’t know of any reason why you do need to put there. Are you cargo culting that code from somewhere or did you actually put it there because you found you needed it?

**Comment by jongbeau** [comment]
It's what we do in `puma.rb` after the fork when the worker boots. The code has been there since 2015 though, so maybe times have changed 🤷

**Comment by mperham** [comment]
I would remove all that junk. Don’t carry over legacy — it will only break something else in the future.
