### ISSUE TITLE
Sidekiq::Context.add exception in occasional circumstances

### ISSUE THREAD

**Issue by oskarpearson** [mperham/sidekiq#5292]
Ruby version: 2.7.4
Rails version: 6.1.5
Sidekiq / Pro / Enterprise version(s): Sidekiq Pro 6.4.1 (should also appear in 6.4.2 given a quick code review)

This is similar to issue https://github.com/mperham/sidekiq/issues/5226 Similarly, it's possible that I'm not using things in quite the right way. I'd appreciate it if you could let me know if I'm done something off-track here. I'm raising this as a new issue to validate my approach.

### Overview / Context

I have recently added code to our codebase that automatically tags sidekiq jobs with datadog attributes. These attributes are used both in logging and in datadog APM tracing. Most of our jobs use sidekiq directly, but a few of them also use ActiveJob.

### Sidekiq Job structure

With sidekiq jobs, I use this pattern, **which works fine, from what I can tell**:

```
class BaseSidekiqWorker
  include Sidekiq::Worker
  include DatadogAutoTagging
end
```

```
class SomeWorker < BaseSidekiqWorker
  # custom code here
end

```

And I then have some sidekiq middleware:
```
module SidekiqMiddleware
  class DatadogAutoTaggingTracer
    def call(worker, _job, _queue)
      if worker.respond_to?(:datadog_autotag_setup)
        worker.datadog_autotag_setup(worker)

        Sidekiq::Context.add(:something, worker.something)
      end

      yield
    end
  end
end
```

So far.. so good...

### ActiveJob structure

With ActiveJob, things are a little more complicated, since `worker` is actually an ActiveJob wrapper when the middleware executes. So it doesn't respond to `datadog_autotag_setup` (though the wrapped active job would)

I thus settled on this for ActiveJob - adding it to ApplicationJob, so it could apply to all Active Jobs.

```
class ApplicationJob < ActiveJob::Base
  # This should be deleted once all active job items are removed
  include DatadogAutoTagging

  before_perform do |job|
    if job.respond_to?(:datadog_autotag_setup)
      job.datadog_autotag_setup(job)
      Sidekiq::Context.add(:something, worker.something)
    end
  end
end
```

**Question:** Should I instead have used the existing middleware and 'un-wrap' the ActiveJob job instead? The 'before_perform' method seemed like it better fit how ActiveJob should idiomatically be used.

### The Exception

The above (both sidekiq and ActiveJob) both appear to work fine "in the real world" without exceptions. However when running specs locally (specifically that use `Sidekiq::Testing.inline!`), I will occasionally get this (please excuse the redacted trace - let me know if it interferes with your debugging)

```
Minitest::UnexpectedError:
  NoMethodError: undefined method `[]=' for nil:NilClass
    REDACTED/gems/sidekiq-6.4.1/lib/sidekiq/logger.rb:25:in `add'
    REDACTED/application_job.rb:10:in `block in <class:ApplicationJob>'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:427:in `instance_exec'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:427:in `block in make_lambda'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:603:in `catch'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:603:in `block in default_terminator'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:199:in `block in halting'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:512:in `block in invoke_before'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:512:in `each'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:512:in `invoke_before'
    REDACTED/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:115:in `block in run_callbacks'
    ...REDACTED...
```

A little frustratingly, this disappears when I try and stick some `byebug` calls into the sidekiq Gem. However, if I trace things through with good-old-puts, the problem is that in some situations `Sidekiq::Context.add` (https://github.com/mperham/sidekiq/blob/v6.4.1/lib/sidekiq/logger.rb#L20-L22) is being called before `Sidekiq::Context.current` has been executed. So `Thread.current[:sidekiq_context]` is nil when `add` is called, and that and leads to the above errors.

I can fix this by running `Sidekiq::Context.current` before attempting to use `Sidekiq::Context.add` in ApplicationJob - but I thought I should check if I have gone down the wrong path here?

I'm wary that (as per that other ticket) I am mucking around with Sidekiq internals. But it does seem like `Sidekiq::Context.add` should work reliably.

Working ActiveJob base:
```
class ApplicationJob < ActiveJob::Base
  include DatadogAutoTagging

  before_perform do |job|
    if job.respond_to?(:datadog_autotag_setup)
      # Ensure Sidekiq Context is initialized 
      Sidekiq::Context.current

      job.datadog_autotag_setup(job)

      Sidekiq::Context.add(:something, worker.something)
    end
  end
end
```

It seems like this would be fixed with the following change to logger.rb - but it may have performance impact:

```
    def self.add(k, v)
      Thread.current[:sidekiq_context] ||= {}  # New assignment - similar to the `current` a few lines above
      Thread.current[:sidekiq_context][k] = v
    end
```

Thanks for your help!

**Comment by mperham** [comment]
Fixed by 2ca1a026d23f0190c8e4e77c33b93ed43940751a
