### ISSUE TITLE
Sidekiq API retry method on Sidekiq::SortedEntry not working

### ISSUE THREAD

**Issue by khrisnagunanasurya** [mperham/sidekiq#5293]
Ruby version: 3.0.3
Rails version: 7.0.2.2
Sidekiq version: 6.4.1

I have a problem with re-ordering DeadJob(s).
In the job arguments, there is a uuid and unix timestamp in millisecond, which if the jobs are error, I need to run a custom rake task, to fix it, which I only need to pass the uuid. and it is expected to be retry all job based on the uuid with the unix timestamp in the argument by ascending.

So here is what I have tried so far:

```ruby
dead_jobs = []

ds = Sidekiq::DeadSet.new
ds.scan("{uuid}") { |job| dead_jobs << job }

# Sort by unix timestamp
dead_jobs.sort_by! { |job| job.args[1] }.each do |job|
    # https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/api.rb#L502
    (Sidekiq::SortedEntry.new(job.parent, job.score, job.item)).retry
end
```

from this line https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/api.rb#L502, it's clear enough for me that it should retry the job, but it's not working at all. is this a bug? expected? or did I miss something?

**Comment by mperham** [comment]
I don't know. Did you resolve this?
