### ISSUE TITLE
Sidekiq 6.4.2 introduces a breaking change by using logger.fatal!

### ISSUE THREAD

**Issue by simonc** [mperham/sidekiq#5297]
Ruby version: 2.6.6
Rails version: 6.0.0
Sidekiq / Pro / Enterprise version(s): 6.4.2

We use the `semantic_logger` and `rails_semantic_logger` gems (v4.10.0) in our project, next to Sidekiq.
By default, RailsSemanticLogger will replace the default Sidekiq logger with its own.
In our initializer, we set Sidekiq's logger to `nil` as we use ActiveJob and use its logger instead.

Doing so will call the [following code](https://github.com/mperham/sidekiq/blob/20cdf68a7362c9f7cc40508e294b96026754772b/lib/sidekiq.rb#L212) in Sidekiq:

```ruby
def self.logger=(logger)
  if logger.nil?
    self.logger.fatal!
    return self.logger
  end

  logger.extend(Sidekiq::LoggingUtils)

  @logger = logger
end
```

The problem is that at this point, RailsSemanticLogger has already replaced Sidekiq's logger and it does not implement the `fatal!` method, resulting in an undefined method error . Prior to Sidekiq 6.4.2, the code was:

```ruby
def self.logger=(logger)
  if logger.nil?
    self.logger.level = Logger::FATAL
    return self.logger
  end

  logger.extend(Sidekiq::LoggingUtils)
  @logger = logger
end
```

This makes it a breaking change and that was probably not the intention in a patch version 🙂

**Comment by mperham** [comment]
Send a PR?

**Comment by mperham** [comment]
git blame shows that the line came from someone "improving" compatibility with semantic logger. 🤷🏻‍♂️

**Comment by simonc** [comment]
I know but I think it's more of an issue with RailsSemanticLogger than SemanticLogger itself as RSL set Sidekiq's logger before user-made initializers. I guess settings `Sidekiq.logger = nil` after that is somewhat an edge-case 🤷

**Comment by simonc** [comment]
Thanks for the merge ❤️
