### ISSUE TITLE
Handle jobs that can't be processed

### ISSUE THREAD

**Issue by stympy** [mperham/sidekiq#5300]
I had a job that could not be completed because it was causing Sidekiq to use too much memory, and the job would be sent back to the queue when the Sidekiq process was terminated by our OOM-killer. This process repeated (fetch the job, get OOM-killed, push the job back) ad infinitum until I intervened. It would be nice to have a way to handle jobs that will never be successfully processed, and that never raise an error (which would put them in the morgue).

One possible implementation would be to be able to specify a job ID (obtained from the log output when the thread is terminated while still working the job) that would be blocked from processing. The next time a worker fetched the job and noticed the ID had been blocked, it would either discard the job or put it in the morgue.

Another possibility (and the one I would prefer) would be to implement something like [SQS' `maxReceiveCount`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#sqs-dead-letter-queues-how-they-work), where after detecting that a job has been fetched X times, Sidekiq could assume that the job can't be processed, and send it to the morgue.

**Comment by mperham** [comment]
What versions are you using?

**Comment by mperham** [comment]
I ask because 5.2.0 added poison pill detection #4633 and it sounds like this should have caught this poor behavior.

https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md#520
