### ISSUE TITLE
ENT collaboration

### ISSUE THREAD

**Issue by cameronmccord2** [mperham/sidekiq#5302]
Enterprise license holder: developer@aboutshout.com

I assign all rights, including copyright, to any future Sidekiq work by myself to Mike Perham

**Comment by mperham** [comment]
Hey Cameron, what are you looking to do with the access? Do you want to open an issue?

**Comment by cameronmccord2** [comment]
At shoutsocial.com we're using each of the Sidekiq::Limiter that are available; loving them by the way. They work great. 

I've been wanting to play with combining 2 limiters so either they both consume limit or neither do. I'd be surprised if this is simple/doable using multiple round trips to redis. I think I'd first start with seeing if I could pre-flight a limiter to see if there is availability(knowing another thread could consume that availability before the preflighted thread). Maybe a function could exist that would check and pass multiple limiters.

```ruby
Sidekiq::Limiter.within_limits([limiter1, limiter2]) { ... }
```

We have a particularly critical spot that has a limiter inside of a limiter. ie: Your account can do x operations per window1 but our entire system is also limited to y operations per window2. At the moment if you can make it through your limiter (consuming some of your limit) but fail to pass through limiter 2 you job is retried but some of your account limit was consumed without you getting any benefit from it.

We can tolerate a bit of looseness in this particular code path in that if we here-and-there go slightly above the limit, its not the end of the world.

**Comment by mperham** [comment]
Yeah, combining limiters is a terrifying prospect to me. The core issue is that it is racy because checking more than 1 limiter is not atomic, it's one Redis call per limit and other operations can interleave between the two checks. I don't see any way to fix this. Do you have ideas on how to handle this safely?

**Comment by cameronmccord2** [comment]
I spent the weekend fiddling and I can't see a way to make an always-correct solution given the not-atomic issue. Thanks for your time and having a fantastic product.
