### ISSUE TITLE
Sidekiq Ent - Periodic Jobs - Support Step Values in Cron Schedule?

### ISSUE THREAD

**Issue by jonstone904** [mperham/sidekiq#5304]
Ruby version: 2.7.5
Rails version: 4.2.11.3
Sidekiq / Pro / Enterprise version(s): 5.2.7, 5.0.0, 1.8.1

This is more of a question, and if the answer is that it is not currently possible then a feature request, but do Periodic Jobs in Sidekiq-Ent support step values in the Cron schedule?

For example, I'm currently using `0 0,3,6,9,12,15,18,21 * * *` to have a job run every 3 hours as it is "standard". However, I'd love to be able to instead use `* 0/3 * * *` which accomplishes the desired schedule, but when I tried to implement this then the job never appears in the queue on the Cron tab.

Thanks in advance!

**Comment by mperham** [comment]
Try `* 0-23/3 * * *`.

Sidekiq Enteprise uses this cron parser (very lightly modified) so you can see how it parses.

https://github.com/siebertm/parse-cron/blob/5ff2cd5bb6c469bf5aa499a90fa49bdc19fcd94b/lib/cron_parser.rb

**Comment by jonstone904** [comment]
Thanks @mperham! Looks like `0 0-23/3 * * *` accomplishes what we need. Much appreciated!
