### ISSUE TITLE
Question: possible to add one job to multiple batches?

### ISSUE THREAD

**Issue by JacobEvelyn** [mperham/sidekiq#5308]
I'm pretty sure this is not possible from playing with the API and looking at how the code is structured, but I just wanted to confirm: am I correct that there's no way to add a single job to multiple batches (without the job executing twice)? (It would be useful to us if this were possible.)

**Comment by mperham** [comment]
Correct, a job may only have one bid attribute. You’d have to create two
different jobs.

**Comment by JacobEvelyn** [comment]
Thank you!
