### ISSUE TITLE
Issue while delivering email

### ISSUE THREAD

**Issue by simtiaz013** [mperham/sidekiq#5313]
We are facing some issues completing jobs. It shows the response of the jobs as completed/done in console but sometimes it does not deliver the emails we are sending in the jobs. To send the email we are using MailChimp. Job does not even add email to the mailchimp list to send the email. 
Is there any ongoing issue that will cause this problem?

**Comment by mperham** [comment]
Sidekiq is software that runs on your machines and executes your jobs. If email delivery is spotty, I don't see how Sidekiq could be at fault.
