### ISSUE TITLE
Push a job twice with the same parameters

### ISSUE THREAD

**Issue by orklann** [mperham/sidekiq#5314]
Let's say we have a Simple Job:

```ruby
class SimpleJob
  include Sidekiq::Job

  def perform(name)
    puts name
  end
end
```

And I run the job twice, by using
```ruby
SimpleJob.perform_async("James")
SimpleJob.perform_async("James")
```

I guess because these jobs hash string will be the same in the Redis ordered set, so there will be one job picked up by the server, right? How can I run the same job twice?

**Comment by mperham** [comment]
Your assumption is incorrect. That will create two jobs unless you have a uniqueness plugin which blocks the second job.
