### ISSUE TITLE
Leaky Bucket Starvation / Leaky Bucket FIFO implementation?

### ISSUE THREAD

**Issue by stuarth** [mperham/sidekiq#5315]
Ruby version: 2.7.5
Rails version: 5.2
Sidekiq / Pro / Enterprise version(s): 6.4.2 / 5.2.2 / 2.2.2

We have (up to) 100 worker threads waiting on a leaky bucket limiter with size 300 over 1 minute, and a wait time of 5 minutes. Ideally I think we wouldn't see OverLimit errors since we'd turn over the entire worker queue every ~20 seconds (100th worker waits 99 * 0.2 seconds). My reading of the implementation is that starvation is possible because, [referencing the blog post](https://www.mikeperham.com/2020/11/09/the-leaky-bucket-rate-limiter/)

```
return (lastcall + driprate) - current_time
``` 

creates a race and the possibility of some workers consistently losing out because `lastcall` is only reset when the limiter has capacity (and so all limited threads receive the same time). 

Potentially a FIFO variation could be added that returns the last quoted wait time + driprate?

**Comment by mperham** [comment]
So we’d get a thundering herd? I don’t want to create another limiter variant but starvation is a bug. Would adding a little random jitter help?

I’m not sure I understand your FIFO proposal. Can you give more detail?

**Comment by stuarth** [comment]
I don't think a jitter would change the potential for starvation since it'd still be a random process, right?

I'll explain my half-formed FIFO proposal in relation to how I understand the current implementation:

Current: If two workers request access to a saturated limiter moments apart, they'll both receive offsets refer to the same clock time (worker 1 told to wait for W, worker 2 requests a moment later and gets W - a moment).
Alternative: Worker 1 gets same value as above, worker 2 gets worker 1's + time for a new drip (`last` updated not just in the available capacity codepath)

**Comment by mperham** [comment]
But we have no guarantee the worker will make a call then. Your proposal
will “allocate” a drip window to a given caller without knowing it will
actually be used, right? Is that an issue?
