### ISSUE TITLE
Sidekiq not processing enqueued job

### ISSUE THREAD

**Issue by alondnim** [mperham/sidekiq#5318]
Ruby version: 2.5.3
Rails version: 6.0
Sidekiq / Pro / Enterprise version(s): 
Sidekiq-pro 3.7.1
Sidekiq 4.2.10

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

No error. Sidekiq fetch and process enqueued job only once redis is cleared.
That means I don't have issue on sidekiq.yml

It happens only in local development where I don't keep sidekiq up for 24 hours
It's fine in production

Thanks

**Comment by mperham** [comment]
@alondnim I don't support Sidekiq 4.x anymore. Upgrade.
@wikimo Please review the Problems and Troubleshooting wiki page.
