### ISSUE TITLE
Ability to configure sample_rate for statsd

### ISSUE THREAD

**Issue by jclusso** [mperham/sidekiq#5319]
The dogstatsd client takes a sample rate on most methods which would be great if we could configure when setting statsd. Since this is part of Sidekiq Pro I don't really know how I could contribute or I'd try myself. Documentation for what I'm looking for is [here](https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/).

**Comment by mperham** [comment]
In your initializer, you can configure the global sample_rate as a per-process option:

```ruby
Sidekiq::Pro.dogstatsd = ->{ Datadog::Statsd.new("metrics.example.com", 8125, sample_rate: 0.5) }
```

or you can configure the per-job options to sample dynamically based on the job payload:

```ruby
Sidekiq::Middleware::Server::Statsd::DEFAULT_OPTIONS = ->(w, j, q) do
  {
    tags: %w(foo:2 bar:3),
    sample_rate: (j['class'] == "HighVolume" ? 0.1 : 1.0)
  }
end
```

Unfortunately you'd need to fork the code to get any more specific or customized than that. Further suggestions and improvements obviously welcome!

**Comment by mperham** [comment]
That last one is actually a pretty killer idea. Mike, you're a genius!

**Comment by jclusso** [comment]
This is awesome - should add to the docs!

**Comment by mperham** [comment]
That feature was newly added in 5.3.0, you're right it's overdue to be added to Pro-Metrics.

**Comment by jclusso** [comment]
Where should that last example go? Would you just drop that in the initializer or does it have to go int he server block?

**Comment by jclusso** [comment]
Not that this is the end of the world, but this will throw a warning. 

`sidekiq.rb:43: warning: already initialized constant Sidek
iq::Middleware::Server::Statsd::DEFAULT_OPTIONS`

**Comment by mperham** [comment]
Oops, docs improved.

**Comment by jclusso** [comment]
I'm not really sure how I test this and confirm this but sampling doesn't seem to work for me. I stuck a pry in the block and I can confirm that my per-worker sample rate was being set. I even hard coded it at 0.1 to test and it didn't sample what was sent to statsd from what I can tell. Any recomendations on a local statsd client I can run on MacOS to further test this instead of contiously having to deploy to staging? Also, have you used this before or is this something that "should" work?

**Comment by mperham** [comment]
I haven’t tried it. Perhaps sample rate is not part of the options hash but
rather a separate argument? I’d get it working in a snippet of code with
just the datadog client first.

**Comment by jclusso** [comment]
It appears to be there. It's oddly not in the comment though. https://github.com/DataDog/dogstatsd-ruby/blob/50dd3e7f89a485afba09f41f4a0d4671e3ec972d/lib/datadog/statsd.rb#L80

This would be the way Sidekiq uses it right?

**Comment by mperham** [comment]
Yes, here's how I increment:

```ruby
              b.increment("jobs.count", opts)
```

and you can see it in use here:

https://github.com/DataDog/dogstatsd-ruby/blob/50dd3e7f89a485afba09f41f4a0d4671e3ec972d/lib/datadog/statsd.rb#L135
