### ISSUE TITLE
Question: How to run the job sequentially by timestamp?

### ISSUE THREAD

**Issue by khrisnagunanasurya** [mperham/sidekiq#5322]
Hi, how to run the job sequentially by timestamp from the `perform` arguments while having 5 threads?

Currently, I'm already implemented Redis lock, to be able to make sure that the job is run sequentially, but I need to make a sure run by the timestamp provided on the `perform` method by ascending. with the Redis lock key is in this format `"lock:status_update:#{user}"` by using this [gem](https://github.com/rwojsznis/sidekiq-lock)

Example:
6 jobs that need to be run exactly sequently by the timestamp, to make sure the data train is correct
```
Job(1652285271, 'userA', 'statusA')
Job(1652285272, 'userA', 'statusB')
Job(1652285273, 'userA', 'statusA')
Job(1652285274, 'userA', 'statusB')
Job(1652285275, 'userA', 'statusA')
Job(1652285276, 'userA', 'statusB')
```

With 5 threads, 5 jobs will be executed simultaneously.
```
Job(1652285271, 'userA', 'statusA')  # finished no.3
Job(1652285272, 'userA', 'statusB')  # finished no.2
Job(1652285273, 'userA', 'statusA')  # finished no.1
Job(1652285274, 'userA', 'statusB')  # finished no.5
Job(1652285275, 'userA', 'statusA')  # finished no.4
```

### Expected result in database
```
- id: 1
   status: statusA
   created_at: 1652285271
- id: 2
   status: statusB
   created_at: 1652285272
- id: 3
   status: statusA
   created_at: 1652285273
- id: 4
   status: statusB
   created_at: 1652285274
- id: 5
   status: statusA
   created_at: 1652285275
```

### Actual results
```
- id: 1
   status: statusA
   created_at: 1652285273
- id: 2
   status: statusA
   created_at: 1652285275
- id: 3
   status: statusB
   created_at: 1652285272
- id: 4
   status: statusB
   created_at: 1652285274
- id: 5
   status: statusA
   created_at: 1652285271
```

### What I'm already trying

I'm trying to get the workers that are executed at the same time, and I want to get the timestamp inside the `#perform` args, but somehow it's only printed out `active_worker` no arguments printed out.

```ruby
  ...
  private

  def active_workers
    workers = Sidekiq::Workers.new
    puts "active_workers"
    workers.each do |_, _, work|
      puts "args# #{work['args']}"
      puts "args## #{work[:args]}"
    end
  end
  ...
```

Is this achievable by Sidekiq without making the thread only 1? (because in the future I need to increase the thread to 25)

**Comment by mperham** [comment]
Sidekiq is an asynchronous job system, it provides no ordering guarantees when running jobs. For instance, retries will always execute out of order. You should rethink your approach, perhaps Sidekiq is not the right tool for this work.

**Comment by khrisnagunanasurya** [comment]
I see, then is it possible to set 1 Sidekiq service, with multiple queues, but each queue has a different thread? 
because if not I need to create 3 different services, and I want to save up some money if possible.
ex:
```sh
bundle exec sidekiq -q default -c 3
bundle exec sidekiq -q create -c 1
bundle exec sidekiq -q default -c 1
```

**Comment by mperham** [comment]
Nope. I think you are trying to fit a square peg into a round hole. Use a different approach.
