### ISSUE TITLE
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

### ISSUE THREAD

**Issue by Rubioli** [mperham/sidekiq#5323]
Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
Rails version: '~> 6.1.4', '>= 6.1.4.4'
Sidekiq: ~> 6.4

My logs are filed with:
```
App 525335 output: Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
App 525335 output: 
App 525335 output: redis.pipelined do
App 525335 output:   redis.get("key")
App 525335 output: end
App 525335 output: 
App 525335 output: should be replaced by
App 525335 output: 
App 525335 output: redis.pipelined do |pipeline|
App 525335 output:   pipeline.get("key")
App 525335 output: end
App 525335 output: 
App 525335 output: (called from /home/edge/bunu/shared/bundle/ruby/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/api.rb:104:in `block in fetch_stats_slow!'}
```

Is there any ways to fix the issue?

**Comment by mperham** [comment]
Upgrade Sidekiq?

**Comment by Rubioli** [comment]
I can't confirm that I need to upgrade from 6.4 to 6.4.2.

Thanks @mperham

**Comment by silent-e** [comment]
For those of us stuck on Sidekiq 5 this warning was added in version 4.6.0 of the redis gem.  Setting your redis gem requirement to `'< 4.6.0'` or even just `'4.5.1'` is enough to avoid this until you can upgrade.
