### ISSUE TITLE
Using jitter for sidekiq_retry_in block

### ISSUE THREAD

**Issue by alexgreat70** [mperham/sidekiq#5324]
Ruby version: 2.7.5
Rails version: 5.2.7.1

In our project, we ran into an issue with the expected retry time of a **job** when using 'sidekiq_retry_in'
Here is an example:
```Ruby
sidekiq_retry_in do |count, exception|
  current_count = count + 1
  default_duration = current_count * 5
  case exception
  when RateLimitError
    default_duration + 1.minute.to_i
  when PendingError
    15
  else
    default_duration
  end
end
```

We expect that upon receiving a **PendingError**, the job will start after **15 seconds**, but this turned out to be not entirely true, we started looking for what the problem was and found.

**Using jiiter in Sidekiq::JobRetry#delay_for**

```Ruby
def delay_for(worker, count, exception)
  jitter = rand(10) * (count + 1)
  if worker&.sidekiq_retry_in_block
    custom_retry_in = retry_in(worker, count, exception).to_i
    return custom_retry_in + jitter if custom_retry_in > 0
  end
    (count**4) + 15 + jitter
end
```

**custom_retry_in + jitter** - we consider the use of such a bundle to be erroneous, since the meaning of sidekiq_retry_in is lost.

Because we have everything to adjust the behavior of the snooze time, but these settings do not correspond to reality

**Comment by mperham** [comment]
That's the expected behavior. Sidekiq does not guarantee exact timing for any of its operations.

**Comment by alexgreat70** [comment]
And can you tell me how it is possible to implement so that the correct time is guaranteed?

**Comment by mperham** [comment]
That's not supported. If you need precise timing, Sidekiq is not the right tool.
