### ISSUE TITLE
Extract config into a Sidekiq::Config API

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5329]
Today Sidekiq still uses a global API with a hodge-podge of class methods in the Sidekiq module for system configuration. It would be nice to get a refactored internal API into the 7.0 release.

- [x] Provide an API to configure Sidekiq::Config instances
- [x] Update the Launcher to launch a Config instance
- [x] Have CLI create a Config singleton, configure via `Sidekiq.configure_{client,server}` and launch it
- [x] Update various utilities and APIs to avoid using those global `Sidekiq` methods if possible
- [x] Backwards compatibility is important. We don't want to break the world but this is a major version bump. Provide deprecations where necessary.

I have an offshoot of the 7.0 branch in progress right now.

**Comment by adamniedzielski** [comment]
> Update the Launcher to launch a Config instance
> Have CLI create a Config singleton

Why singleton? Or rather: what do you understand by "singleton" here? I'd imagine it's possible to create a Config instance in CLI and pass it further, without turning it into a singleton. Or am I missing something?

**Comment by mperham** [comment]
Well, Sidekiq::CLI sets up the Sidekiq process when it boots. That process contains one Sidekiq::Config instance which represents the process config so CLI is the right place to create that instance. I don't literally mean a ::Singleton, but currently I have `Sidekiq.config` holding that single Sidekiq::Config instance.

**Comment by adamniedzielski** [comment]
> Well, Sidekiq::CLI sets up the Sidekiq process when it boots. That process contains one Sidekiq::Config instance which represents the process config so CLI is the right place to create that instance.

👍 

> I don't literally mean a ::Singleton

👍 👍 

> currently I have Sidekiq.config holding that single Sidekiq::Config instance

Do we still need to keep global `Sidekiq.config` though?

**Comment by mperham** [comment]
I’m redesigning the internal components to not need a global Sidekiq.config but the issue with APIs like `Sidekiq.redis` which is far too pervasive to break and needs access to the configured Redis pool. Same with Sidekiq.logger.

**Comment by adamniedzielski** [comment]
Makes sense. Step by step then 🙂 I think that it's already going to be a great improvement. Looking forward to see your implementation.
