### ISSUE TITLE
Problems with Sidekiq Ent setup

### ISSUE THREAD

**Issue by yossiedri** [mperham/sidekiq#5330]
Hello,
i have two major issues, the first is that after loading sidekiq i dont see the registration of periodic jobs in the console nor in the UI.
the second thing is sidekiq process is not stoped when hitting Ctr+c.
Im in the middle of an upgrade to my application and i want to use Sidekiq Ent and the time is on the matter,
please help  

```
Gemfile:
source "https://enterprise.contribsys.com/" do
  # gem 'sidekiq-pro'
  gem 'sidekiq-ent'
end

Ruby version: ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-darwin20]
Rails version: Rails 5.2.7.1
Sidekiq / Pro / Enterprise version(s): 
Using sidekiq 6.4.2
Using sidekiq-pro 5.3.1
Using sidekiq-ent 2.3.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
initializer:
require 'rake'
require 'sidekiq/web'
# require 'sidekiq/ent'
# require 'sidekiq/pro/expiry'

if Rake::Task.tasks.empty?
	Rails.app_class.load_tasks 
end
Sidekiq::Enterprise.unique! unless Rails.env.test?
 
puts "SIDEKIQ::REDIS_CONFIG: #{REDIS_CONFIG}"
$redis = Redis.new(REDIS_CONFIG) unless defined?($redis)

redis_conn = proc {
	$redis 
}

Sidekiq.configure_client do |config|
	config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
	config.redis = ConnectionPool.new(size: 25, &redis_conn)
	config.periodic do |mgr|
		mgr.register('0 1 * * *', 'FixIssueRootAndTreeWorker')
		mgr.register('1 0 * * *', 'CheckFaildAttachments')
		mgr.register('0 1 * * *', 'SprintCompletionStats')
		mgr.register('43 4 * * *', 'SyncTestCases')
		mgr.register('2 3 * * *', 'SwMspSyncAll')
		mgr.register('0,10,20,30,40,50 * * * *','RetryFailedNvbugUpdates')
		mgr.register('32 3 * * *', 'SyncPls')
		mgr.register('32 3 * * *', 'SyncAllAgileChanges')
		mgr.register('42 3 * * *', 'SyncUserDeps')
		mgr.register('20 2 1,8,15,22 * *', 'RightLeftCheckByEqualEstimatedField')
		mgr.register('58 23 * * *', 'LdapRevokedUsersReports')
		mgr.register('0,30 * * * *', 'SyncAllLdapRevokedUsers')
		mgr.register('0 4 * * *', 'SyncAllNVLdapGroups')
		mgr.register('0 4 * * *', 'PopulateProjects')
		mgr.register('* 2 * * *', 'SetPointerIssues')
		mgr.register('* 22 * * *', 'SetPointerIssuesNight')
		mgr.register('30 4 * * *', 'DeliverQuery')
		mgr.register('14 4 * * *', 'BuildFromTables')
		mgr.register('0,5,10,15,20,25,30,35,40,45,50,55 * * * *', 'SyncAll')
		mgr.register('0 1 * * *', 'PopulateSfProjects')
		mgr.register('15 1 * * *', 'PopulateProjectCategories')
		mgr.register('58 23 * * *', 'UpdateDw')
		mgr.register('0,30 * * * *', 'UpdateDwCheckTime')
		mgr.register('0,15,30,45 * * * *', 'FetchChangesets')
		mgr.register('0 6 * * *', 'CreateFrSalesforceData')
		mgr.register('0 1 * * *', 'AddHistoryDwhIssueIds')
		mgr.register('0 4 * * *', 'CloseVersions')
		mgr.register('* * * * *', 'FixLftRgt')
		mgr.register('0 * * * *', 'ScrumTypeFix')
		mgr.register('30 3 * * *', 'GitUp')
		mgr.register('55 2 * * *', 'HgUp')
		mgr.register('14 2 * * *', 'ClearCronLogs')
		mgr.register('*/2 * * * *', 'CheckIssuePositionAndSprintInconsistency')
		mgr.register('* * * * *', 'UpdateActiveProjectPath')
	end
end

Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]

sidekiq.yml:
---
:logfile: 'log/sidekiq.log'
:pidfile: 'tmp/pids/sidekiq.pid'
:dynamic: true 
:enabled: true

:queues:
  - [default,1]
  - [mailer,2]
  - [nvbug,3]
  - [analytics, 3]
  - [fast_issue,4]
  - [journal_worker,5]
  - [often, 6]
  - [update_dwh,7]
  - [create_dwh,8]
  - [sync_project_issues,9]
  - [send_by_mail,10]

development:
  :concurrency: 1
  :timeout: 10000
  :verbose: false
  :queues:
    - [default,1]
    - [mailer,2]
    - [nvbug,3]
    - [development_analytics, 3]
    - [development_fast_issue, 4]
    - [development_journal_worker,5]
    - [development_often, 6]
    - [development_update_dwh,7]
    - [development_create_dwh,8]
    - [development_sync_project_issues,9]
    - [development_send_by_mail,10]

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

Here is a  periodic jobs class in app/workers for example:
class FixIssueRootAndTreeWorker
    include Sidekiq::Job
    sidekiq_options unique_for: 30.minutes, queue: 'default',backtrace: true,retry: false,dead: true, tags: ["FixIssueRootAndTree"]
    def perform
        Rake::Task["fixes:update_root_id[]"].execute
    end
end
```

**Comment by mperham** [comment]
> redis_conn = proc {
	$redis 
}

where did you get this code? Do not ever use global Redis connections in Sidekiq.

**Comment by mperham** [comment]
Please link directly to where you saw it. It is a terrible, terrible example and the author should remove it from the Internet; it literally breaks Sidekiq.

Again, you are still using global Redis connections. Do this:

```ruby
redis_conn = proc {
  Redis.new(REDIS_CONFIG)
}
```

**Comment by mperham** [comment]
Or better yet:

```ruby
Sidekiq.configure_server do |config|
  config.redis = REDIS_CONFIG
end
```

**Comment by yossiedri** [comment]
Yes its working 10x

**Comment by yossiedri** [comment]
Any idea why i get this morning?

2022-05-16T18:32:38.648Z pid=14423 tid=ox175fo1j INFO: Booted Rails 5.2.7.1 application in development environment
2022-05-16T18:32:38.648Z pid=14423 tid=ox175fo1j INFO: Running in ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-darwin20]
2022-05-16T18:32:38.648Z pid=14423 tid=ox175fo1j INFO: Sidekiq Pro 5.3.1 / Sidekiq Enterprise 2.3.1, commercially licensed.
2022-05-16T18:32:38.654Z pid=14423 tid=ox175fo1j INFO: Starting processing, hit Ctrl-C to stop
2022-05-16T18:32:38.673Z pid=14423 tid=ox18x4gcf INFO: Managing 34 periodic jobs
2022-05-16T18:32:38.677Z pid=14423 tid=ox18x4gcf INFO: Gained leadership of the cluster
^A2022-05-16T18:33:00.139Z pid=14423 tid=ox18xdthf WARN: NameError: uninitialized constant FixLftRgt
2022-05-16T18:33:00.140Z pid=14423 tid=ox18xdthf WARN: /Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:199:in `const_get'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:199:in `constantize'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:174:in `enqueue_job'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:130:in `process'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:83:in `block in cycle'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:73:in `block in wrap'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/activesupport-5.2.7.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/activesupport-5.2.7.1/lib/active_support/reloader.rb:72:in `wrap'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/periodic/manager.rb:82:in `cycle'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
/Users/yedri/.rvm/gems/ruby-2.6.9/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'

**Comment by mperham** [comment]
NameError: uninitialized constant FixLftRgt 

This is a standard code loading issue in any Rails app.  Shouldn’t have anything to do with Sidekiq.
