### ISSUE TITLE
my sidekiq has an error starting

### ISSUE THREAD

**Issue by sujit-kulkarni** [mperham/sidekiq#5333]
I am new to the app. I have my ruby on rails app and sidekiq running on AWS ec2 instance and redis on AWS elastic cache.
I have provided the redis url into the sidekiq configuration as a part of REDIS_URL variable.

As I execute : bundle exec sidekiq
Below is the error encountered.

2022-05-17T11:15:13.169Z 27730 TID-6c2 ERROR: MOVED 9259 172.31.24.68:6379
2022-05-17T11:15:13.169Z 27730 TID-6c2 WARN: Redis::CommandError: MOVED 9259 172.31.24.68:6379
2022-05-17T11:15:13.169Z 27730 TID-6c2 WARN: /home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:163:in `call'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:2874:in `block in _scan'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/3.0.0/monitor.rb:202:in `synchronize'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:2873:in `_scan'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:3023:in `sscan'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:11:in `block in sscan'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:10:in `loop'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:10:in `sscan'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:747:in `block in cleanup'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq.rb:97:in `block in redis'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq.rb:94:in `redis'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:746:in `cleanup'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/api.rb:739:in `initialize'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/scheduled.rb:155:in `new'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/scheduled.rb:155:in `process_count'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/scheduled.rb:120:in `random_poll_interval'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/scheduled.rb:89:in `wait'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/scheduled.rb:69:in `block in start'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/util.rb:16:in `watchdog'
/home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sidekiq-5.2.10/lib/sidekiq/util.rb:25:in `block in safe_thread'
2022-05-17T11:15:16.528Z 27730 TID-6dy ERROR: heartbeat: MOVED 15458 172.31.31.5:6379
2022-05-17T11:15:18.170Z 27730 TID-6c2 ERROR: MOVED 14815 172.31.31.5:6379
2022-05-17T11:15:18.170Z 27730 TID-6c2 WARN: Redis::CommandError: MOVED 14815 172.31.31.5:6379
2022-05-17T11:15:18.170Z 27730 TID-6c2 WARN: /home/ec2-user/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:163:in `call'

Also, the Appurl/sidekiq thrwows an error saying no route to /sidekiq 404 error.
Kindly help me for the same.

![image](https://user-images.githubusercontent.com/11851341/168800107-01c3bbe6-3e60-4e29-a7fd-f1754ac9524a.png)

**Comment by mperham** [comment]
MOVED is an error specific to Redis in Cluster mode and the Using Redis wiki page specifically states that Cluster mode is not supported. You must use a Primary / Replica deployment model.

**Comment by mperham** [comment]
Looks like you are using Redis Cluster, which Sidekiq doesn’t support.
MOVED is a cluster thing.
