### ISSUE TITLE
Question: Sidekiq Limit Tab dashboard for enterprise accounts

### ISSUE THREAD

**Issue by hnrqer** [mperham/sidekiq#5334]
Ruby: 2.7.5
Sidekiq 6.4.1 / Pro 5.3.1 / Ent 2.3.1

Hello, I was wondering if current documentation is still valid for displaying Sidekiq  Limits in the Web UI for enterprise accounts. Right now this is what I can see:
![Annotation on 2022-05-17 at 21-06-05](https://user-images.githubusercontent.com/1770506/168931623-52c0a5ed-9a29-45d8-bc8c-bc80db48cd1e.png)

According to documentation this is how it should look like:
https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#web-ui
![Screen Shot 2022-05-17 at 21 09 51](https://user-images.githubusercontent.com/1770506/168931912-a881a30f-ca2b-4763-ab1c-e086e7b17cfc.png)

Missing metrics and some other statuses.

BTW, already added this to my routes.rb file:

```
require "sidekiq-ent/web"
```

Regards,

**Comment by mperham** [comment]
Those are two different types of limiters. The window limiter does not provide any metrics.
