### ISSUE TITLE
Unusual proposal

### ISSUE THREAD

**Issue by paneq** [mperham/sidekiq#5336]
Ruby version: unrelated
Rails version: 6.05 and many higher and lower versions
Sidekiq / Pro / Enterprise version(s): 6.4.1 and higher probably

Hey :)

I am coming to you with a very unusual story and request and I understand if you decide to reject this idea. But this caused a couple of hour of debugging and firefighting in my team so I hope you can see that I am coming with good intentions.

Imagine you have:

* a sidekiq job which has this code (for some unrelated reasons):

```
def sidekiq_queue
  @sidekiq_queue ||= Sidekiq::Queue.all.find { |q| q.name == 'foo' }
end
```

* Sidekiq Queue implementation of 

```
class Queue
    include Enumerable

    def each
      ...
    end
```

* Rails active support extension of:

```
module Enumerable
  def as_json(options = nil) #:nodoc:
    to_a.as_json(options)
  end
end
```

* An exception tracker which tries to a serialize job context (i.e. instance variables) when reporting an error and using sidekiq itself as a delivery mechanism.

Result:

* `@sidekiq_queue` ivar can get serialized to hundreds of MBs depending on queue size
* A job of such size is being put to redis to send an error exception to error tracker backend

As you can see this is a pretty unusual combination of multiple of things and no-ones fault at particular with sidekiq deserving no blame at all. Sidekiq does not implement `as_json` and yet the class is serializable by taking into account all its elements :(

I kindly propose you implement something akin to

```
class Queue
  include Enumerable

  def as_json(options = nil) #:nodoc:
    {name: name}
  end
end
```

to overwrite this problematic rails definition coming from `Enumerable` extension.

I doubt anyone ever uses `Sidekiq::Queue#as_json` intentionally so I believe it would not be a breaking change.

**Comment by mperham** [comment]
Whew, that's a crazy story. Thank you for sharing, it made me laugh and cry.

1. Your first code snippet could be:
```ruby
def sidekiq_queue
  @sidekiq_queue ||= Sidekiq::Queue.new("foo")
end
```
2. I don't want to mess with any Rails extensions but I also don't know of any way to mark an instance as not serializable. It would be reasonable for you to ask the Rails team if they know of any way to prevent this situation from happening. Ultimately I don't think Queue should ever be converted to JSON but it absolutely makes sense for it to be Enumerable.

**Comment by riffraff** [comment]
maybe `Sidekiq::Queue` could implement `#to_a` so it raises an exception? 
Other instances of "non-arrayzable" enumerables like endless ranges do this, and IMVHO it kinda makes sense to be able to find things in a queue through enumerable methods, while also not being able to make it into an array.

**Comment by mperham** [comment]
`to_a` is useful in integration test scenarios to validate queue contents. I don't want to cripple the existing API. I think @paneq's suggestion is the best. Send a PR for Sidekiq::Queue and Sidekiq::SortedSet?

**Comment by paneq** [comment]
@riffraff I like the idea.

@mperham There is kinda ugly a workaround if we make `to_a` unusuable, which is to replace it in test scenarios with explicit `each.to_a`.

To make it work, we would `#each` implementation to return `Enumerator` if block is not provided:

```
def each
  return enum_for(:each) unless block_given?
  # ...
end
```

It is a [standard ruby practice anyway](https://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/).

**Comment by paneq** [comment]
@mperham just to double check, do you still prefer to overwrite `as_json` over `to_a`?

**Comment by mperham** [comment]
Yes. It makes little sense to call as_json on a queue. It makes a lot of sense to call to_a.
