### ISSUE TITLE
 Understanding jobs.count and jobs.failure metrics

### ISSUE THREAD

**Issue by hunter-moeller** [mperham/sidekiq#5337]
Ruby version: 2.7
Rails version: - 
Sidekiq / Pro / Enterprise version(s): sidekiq-pro 5.3.1

https://github.com/mperham/sidekiq/wiki/Pro-Metrics#metrics describes the sidekiq metrics including:
> i.e. `count` will always be incremented. `success` or `failure` will be incremented based on the outcome.

At what point does the incrementing happen?  In particular Im wondering if it happens only when the job reaches its final state or if it can happen after a retry failure.  (In the context of https://github.com/mperham/sidekiq/wiki/Job-Lifecycle)

Say a job fails on first try but is successful on first retry.  Is it correct to say that `jobs.count` will be incremented twice, `jobs.failure` incremented once and `jobs.success` incremented once?

(Im wondering because Im trying to determine if the metrics can be used to back out how many messages were enqueued in a period of time)

Thanks!

**Comment by mperham** [comment]
See for yourself:

bundle open sidekiq-pro

**Comment by hunter-moeller** [comment]
I found it in the source code, thanks
