### ISSUE TITLE
Sidekiq 6.5 changes

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5345]
Sidekiq 7.0 makes significant breaking API changes so we need to stage those changes in 6.5 to give people a clean upgrade path.

- [x] Support old `redis` and new `redis-client` gems in parallel, allowing testing with the new gem.
- [x] #5340  Migrate internal Sidekiq components to use local configuration rather than pulling from global `Sidekiq` config.
- [x] Document the migration path for existing APIs on the top-level Sidekiq module, see `docs/`.

**Comment by bf4** [comment]
Any thoughts on splitting sidekiq/util into sidekiq/job_util and sidekiq/component for people who had used Sidekiq::Util? The context is that I'm looking at this in https://github.com/klaxit/sidekiq-worker-killer/pull/21 and I couldn't find a nice diff/commit in this repo to look at and the docs didn't answer my question.  Apologies if you'd rather I commented elsewhere. This seemed a reasonable place to me.  Acceptable responses are 'don't do that' :)
