### ISSUE TITLE
Uninitialized constant error when running sidekiqswarm with bootsnap

### ISSUE THREAD

**Issue by guigs** [mperham/sidekiq#5346]
Ruby version: 3.0.3
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.4.2 / 5.3.1 / 2.3.1

We had an issue with our Rails app that raised an uninitialized constant error only when app is run via sidekiqswarm.

```
[swarm] uninitialized constant #<Class:0x00007fbbfc58e340>::NestedThing
Did you mean?  MyApi::Thing::NestedThing
[swarm] /home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/grape-1.6.2/lib/grape/api.rb:87:in `const_get'
/home/guigs/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/grape-1.6.2/lib/grape/api.rb:87:in `const_missing'
```

I discover it is related to bootsnap, as it does not happen when bootsnap is disabled. It is also somehow related to [Grape](https://github.com/ruby-grape/grape), as it only happens when loading a nested class of class that inherits from `Grape::API`.

I created a [minimal Rails app to demonstrate the issue](https://github.com/heyjobs/grapeboot) and added more details in the README.

Maybe this is related to #4766, as using `SIDEKIQ_PRELOAD=` is one way to prevent the error.

**Comment by mperham** [comment]
As we discussed during Office Hour, I'd suggest you open an issue with bootsnap.

All the preload option does is this:

```ruby
cli = Sidekiq::CLI.new.tap {|c| c.parse}
if @preload
  log "Preloading application"
  cli.send(:boot_application)
end

# fork the process N times
```

You can see the Sidekiq::CLI#boot_application method here:

https://github.com/mperham/sidekiq/blob/b201ce54b21e911865377057ba1d7d2bdb46c5cd/lib/sidekiq/cli.rb#L264-L279

**Comment by guigs** [comment]
@mperham Thanks, I was able to remove sidekiq as dependency of the demo app and simulated the boot with custom sidekiqswarm script. https://github.com/heyjobs/grapeboot/commit/00d02af3c4ee232b2868954189317a0a26e40ac8.

I'll open an issue on [bootsnap](https://github.com/Shopify/bootsnap).
