### ISSUE TITLE
Sidekiq.strict_args! and a long Float number as an argument to the job causes the exception

### ISSUE THREAD

**Issue by ArturT** [mperham/sidekiq#5347]
Ruby version: 3.1.2
Rails version: 6.1.6
Sidekiq version: 6.4.2

I added the following code to `config/initializers/sidekiq.rb`.

```
Sidekiq.strict_args!
```

I use `MyJob.perform_async(hash.stringify_keys)` as suggested in [best practices](https://github.com/mperham/sidekiq/wiki/Best-Practices).

But I noticed I keep getting the error:

```
 WARN: ArgumentError: Job arguments to MyJob must be native JSON types, see https://github.com/mperham/sidekiq/wiki/Best-Practices.
To disable this error, remove `Sidekiq.strict_args!` from your initializer.
```

It's due to how `json_safe?` method works in https://github.com/mperham/sidekiq/blob/994a4fa216a575b29ced2506c8b635515cc1029d/lib/sidekiq/job_util.rb#L67

```ruby
def json_safe?(item)
  JSON.parse(JSON.dump(item["args"])) == item["args"]
end
```

I reproduced the problem, here is my `arg` to the `MyJob`:

```
3.1.2 :026 > arg = { key: 0.0011285007931292057 }
 => {:key=>0.0011285007931292057}
3.1.2 :027 > stringify_arg = arg.stringify_keys # doing what is suggested in best practices
 => {"key"=>0.0011285007931292057}
3.1.2 :028 > restored_args = JSON.parse(JSON.dump(stringify_arg)) # do what json_safe? method does
 => {"key"=>0.001128500793129206}
3.1.2 :029 > restored_args == stringify_arg # check as in json_safe? method
 => false

3.1.2 :030 > '0.0011285007931292057'.size
 => 21
3.1.2 :031 > '0.001128500793129206'.size
 => 20
```

It looks like Float is too long to be `JSON.dump`'ed. The Float `0.0011285007931292057` is rounded to `0.001128500793129206` because of how `JSON.dump` works.

I'm not sure how to approach this problem. Am I not allowed to pass Float longer than 20 chars in Sidekiq 7.x? 

Will l be able to use `Sidekiq.strict_args!(false)` in Sidekiq 7.x?
https://github.com/mperham/sidekiq/blob/main/Changes.md#640

From my app business logic perspective, nothing bad happens that the number was rounded. The only downside is that `Sidekiq.strict_args!` prevents the job from running.

For a workaround, I could try round number earlier before passing it as an argument to Sidekiq to fix the problem.  

I'm reporting this issue just in case. Maybe it would be somehow relevant to know about this edge case if you did not consider it before.

BTW I'm not sure what's the recommended way to ensure my app is working fine. Adding `Sidekiq.strict_args!` did not cause my tests to fail. I only get errors when running jobs in the development and browsing Sidekiq logs or Sidekiq UI.

@mperham Thanks for the great work on Sidekiq.

**Comment by mperham** [comment]
JSON is JavaScript and JS has weird rules around floating point values, they can’t use the full 64-bits so you’ll often see truncation like this. Go’s JSON library has the same drawback, they covert to a String internally.

Most articles I have read recommend you don’t pass Floats or convert them to Strings if you need to put them in JSON.

**Comment by ArturT** [comment]
I found out that the root issue is `oj` gem in my project. 
Probably related topic https://github.com/ohler55/oj/issues/628 
`oj` gem impacts the result of `JSON.dump`.

When I run this in IRB (outside of my project directory - without `oj`) everything works good:

```ruby
3.1.2 :012 > stringify_arg = { 'key' => 0.0011285007931292057 }
 => {"key"=>0.0011285007931292057}
3.1.2 :013 > restored_args = JSON.parse(JSON.dump(stringify_arg))
3.1.2 :014 > restored_args == stringify_arg
 => true
3.1.2 :015 > JSON.dump(stringify_arg)
 => "{\"key\":0.0011285007931292057}"
```

I guess I'll have to stick with some workaround.
