### ISSUE TITLE
Migrate test suite to 100% describe format

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5350]
A few of the files in `test/` still use the old `test/unit` syntax rather than the `describe` format. These files all descend from Minitest::Test. Migrate them to the describe format (like most of the test files) so we can use niceties like scoped `before` blocks, etc.

**Comment by mperham** [comment]
I can't assign this to you @samardrey. Do you have some privacy setting on so people can't search or find you?

**Comment by mperham** [comment]
Here are the files.

```
% git grep Minitest::Test test/
test/test_csrf.rb:class TestCsrf < Minitest::Test
test/test_current_attributes.rb:class TestCurrentAttributes < Minitest::Test
test/test_job.rb:class TestJob < Minitest::Test
test/test_job_logger.rb:class TestJobLogger < Minitest::Test
test/test_logger.rb:class TestLogger < Minitest::Test
test/test_systemd.rb:class TestSystemd < Minitest::Test
test/test_web_helpers.rb:class TestWebHelpers < Minitest::Test
```

**Comment by SamArdrey** [comment]
Weird, I went through my settings and couldn't find anything that should block you from assigning me. Do I need to do anything special with the repo, like subscribe or anything?

**Comment by SamArdrey** [comment]
- [ ] test/test_csrf.rb:class TestCsrf < Minitest::Test
- [ ] test/test_current_attributes.rb:class TestCurrentAttributes < Minitest::Test
- [ ] test/test_job.rb:class TestJob < Minitest::Test
- [ ] test/test_job_logger.rb:class TestJobLogger < Minitest::Test
- [ ] test/test_logger.rb:class TestLogger < Minitest::Test
- [ ] test/test_systemd.rb:class TestSystemd < Minitest::Test
- [ ] test/test_web_helpers.rb:class TestWebHelpers < Minitest::Test
