### ISSUE TITLE
What is the ACL for redis 6.x

### ISSUE THREAD

**Issue by jrgifford** [mperham/sidekiq#5353]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): N/A

In Redis 6.x+, the [ACL](https://redis.io/docs/manual/security/acl/) command was updated to include `username` as a parameter. 

As we look towards upgrading to Redis 6, [what is the ACL](https://redis.io/docs/manual/security/acl/#command-categories) that Sidekiq requires for operation? I'm not super keen on using the `default` user, or using `@all` as the ACL.

**Comment by mperham** [comment]
Good question, I don't believe Sidekiq uses any of the dangerous commands *except* INFO, which it uses to get the Redis version and memory usage for display on boot and in the Web UI so something like:

```
+@all -@dangerous +info
```

seems about right. I don't think it would be wise to commit to any specific ACL since that would restrict potential command usage in the future. wdyt?

**Comment by jrgifford** [comment]
That seems reasonable to me! I'll work with my app teams and we'll try it out and get back to you as to how it goes.

**Comment by hmcfletch** [comment]
@mperham I'm in the process of setting up some ACL lists for Redis for the first time and stumbled across this ticket. I have a few comments/questions. Question first:

- Do you think that adding `-@admin -@connection` would restrict Sidekiq access? I'm looking at something like:
  - `on ~* +@all -@dangerous -@admin -@connection +info`

I could see a committed ACL being an optional thing, you could supply multiple levels, one that is a general one like and one that is tighter. Users could choose:
- general: `on ~* +@all -@dangerous -@admin -@connection +info`
- tighter: `on ~* +brpop ...`
- super tight: `on <sidekiq key patterns> +brpop ...`

The tight and super tight options are more of a thought exercise. They would really only make sense in a situation where your Sidekiq shares a Redis instance with data from other clients. Changes would either need to be tied to semver or explicitly mentioned that they aren't provided as is and might break in the future. 

I don't see these being overly useful and a really big effort to be maintained. Not to mention any 3rd party extensions access would have to be factored in. Yeah, way too much effort.

I don't think committing to the more general form would be overly restrictive and a change could be added as a breaking change in a major version bump.

Some more ACL categories that might be able to be trimmed (I haven't verified), but I can't really see a reason to:
- `hyperloglog`
- `stream`
- `pubsub`
- `geo`

Would it be useful to add some information to the wiki about the more general option with a YMMV disclaimer?

**Comment by mperham** [comment]
Sidekiq Pro uses pubsub but the other three categories are unused by my gems. Other gems or plugins might use those commands. 

Things like PING could be useful during normal runtime so I’m pretty uncomfortable endorsing @connection. YMMV

**Comment by jrgifford** [comment]
So far, the ACL Mike shared in May has worked well for us. Since Sidekiq is the only thing on that redis, we haven't felt the need to restrict it further.

**Comment by hmcfletch** [comment]
@mperham Good call on `@connection`, but do you think that restricting `@admin` is okay?

FYI, this is what is in `@admin`:
- `slaveof`
 - `debug`
 - `bgsave`
 - `monitor`
 - `bgrewriteaof`
 - `psync`
 - `lastsave`
 - `acl`
 - `config`
- `replicaof`
- `replconf`
- `cluster`
- `module`
- `save`
- `failover`
- `pfselftest`
- `sync`
- `pfdebug`
- `client`
- `latency`
- `shutdown`
- `slowlog`

**Comment by mperham** [comment]
@hmcfletch Those are Redis administrative commands. Sidekiq is, in a sense, a Redis application and basic security protocol is that apps should never use any commands considered administrative.

**Comment by hmcfletch** [comment]
That was my assumption, but you know what they say assumptions :p

I appreciate you reengaging with this ticket though, and I see that you already added a blurb to the wiki!
