### ISSUE TITLE
Process a single job and exit

### ISSUE THREAD

**Issue by axos88** [mperham/sidekiq#5356]
For debugging purposes I would like to start up a sidekiq processor that would process one (or n) jobs, then exit, so that I can check the state of the system. I could not find any such option in the sidekiq --help.

Is there a way to achieve this?

**Comment by mperham** [comment]
Not easily but you could hack something together. Use `-c 1` along with a custom server middleware which sends TSTP to itself before the job and TERM after the job.

Sidekiq (and Rails more generally) is designed to be a long-running process and not designed to quickly start/stop.
