### ISSUE TITLE
Create RDoc for sidekiq/api

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5362]
`sidekiq/api` is Sidekiq's Ruby API for all of the runtime data stored in Redis.

https://www.mikeperham.com/2021/04/20/a-tour-of-the-sidekiq-api/

The API has never been "properly" documented for users but it has reached a point of stability where quality RDoc for it would be beneficial. Go through the code in sidekiq/api and document the various classes and methods.

**Comment by SamArdrey** [comment]
@mperham is there a URL you'd like this to point to? It creates .html files

**Comment by mperham** [comment]
There’s at least one or two community our dock sites that will automatically build and serve the generated HTML. https://Rdoc.info is one of them I believe
