### ISSUE TITLE
Sidekiq 6.5.0 breaks with Sidekiq Pro 5.2.2

### ISSUE THREAD

**Issue by matt-taylor** [mperham/sidekiq#5373]
Ruby version: 2.7.x / 3.x
Rails version: 5.2.x / 6.x
Sidekiq / Pro / Enterprise version(s): 6.5.0 / 5.2.2 / 5.2.2

----

```
LoadError:
  cannot load such file -- sidekiq/util
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:1:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/config.rb:1:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/api.rb:5:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq/pro/api.rb:5:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq-pro.rb:6:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-pro-5.2.2/lib/sidekiq-pro.rb:6:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent.rb:3:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-2.2.2/lib/sidekiq-ent.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
# ./spec/spec_helper.rb:7:in `<top (required)>'
```

Sidekiq Pro v5.2.2 requires `sidekiq/util`. Now while the easy answer may be to upgrade Sidekiq Pro, we are not quite ready for that.

There does not seem to be any changes in the Changelog about this for ENT nor PRO. This seems to be a breaking change. Should `v6.5.0` have been a major version bump instead?

----

This is similar to https://github.com/mperham/sidekiq/issues/5372

**Comment by mperham** [comment]
Correct, Sidekiq Pro 5.5 works with 6.5. You’ll need to stay on 6.4 if you can’t bump Pro.

**Comment by matt-taylor** [comment]
@mperham Can you update the changelog to reflect that since this is a breaking change?

**Comment by mperham** [comment]
I will do so but you should not expect old versions of Pro/Ent to work with every new version of Sidekiq. The gems are released in tandem and they are meant to be upgraded in tandem. Patch releases are meant to be safe but minor bumps can contain refactoring across gem boundaries.

**Comment by christos** [comment]
@mperham I think more people will come across this issue because @dependabot doesn't upgrade the three gems in tandem.

**Comment by mperham** [comment]
@christos Well, that sucks. If you are running Sidekiq Pro, you need to upgrade it with `bundle exec sidekiq-pro`. If you lock Sidekiq to a specific minor release, you should be ok: `gem "sidekiq", "~> 6.4.0".

The issue is that I don't use semantic versioning between the three projects because I fully control them under the assumption that they are all upgraded at the same time. I can't possibly know whether Sidekiq Pro 5.2.2 will be compatible with the next minor version of Sidekiq or not so I can't put a max version constraint in the gemspec. I'll think about how I can improve this, at the very least I can put a constraint on the major version.

**Comment by erik-ekberg-gd** [comment]
> ... so I can't put a max version constraint in the gemspec.

You can, you just choose not to. You know that `sidekiq-pro 5.5.2` will be compatible with `gem 'sidekiq', '~> 6.5.0'` because `sidekiq` patches are not breaking.

If you don't know if `sidekiq-pro` is going to be compatible with some future version of some gem, do not say they are compatible in your code. Likewise, if you know `sidekiq-pro` will be compatible up to a certain version of that gem, state where that upper bound is in your code. 

And if somebody comes along and wants to go use `sidekiq ~> 12.3.4` just force them to hunt down a compatible version of `sidekiq-pro` (or visa versa) rather than breaking your customers applications trying to leave it open ended.

**Comment by stream-toma** [comment]
@mperham , I might be getting confused here but 

Should the require sidekiq/utils error be resolved if using the following versions:

```
Using sidekiq 6.5.0
Using sidekiq-pro 5.5.0
Using sidekiq-ent 2.3.1
```

```
/Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent/metrics.rb:4:in `<main>'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/sidekiq-ent-2.3.1/lib/sidekiq-ent.rb:14:in `<main>'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/runtime.rb:55:in `each'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/runtime.rb:44:in `each'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/runtime.rb:44:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler.rb:176:in `require'
	from /Users/toma/Dev/console-api/config/application.rb:22:in `<top (required)>'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:93:in `require'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:93:in `preload'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:162:in `serve'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
	from /Users/toma/.rvm/gems/ruby-3.1.2/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/Users/toma/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/toma/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```
