### ISSUE TITLE
How to access initializer server_config in rspec

### ISSUE THREAD

**Issue by tcarac** [mperham/sidekiq#5376]
Hi!
I want to test scheduled jobs configuration within rspec context.
I was wondering how to access sidekiq.rb initializer server_configuration from and if it is possible within a rspec test.

The section to be tested is
```ruby
Sidekiq.configure_server do |config|
   config.periodic do | sched| 
       sched.schedule('0 1 * * * ', 'SomeClass')
   end
  end
  ```

I just want to verify that the cron format is correct and that the klass exists.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs#testing

Personally I'd test it by starting Sidekiq.
