### ISSUE TITLE
When using `Sidekiq::JobRetry`: `undefined method "logger" for {}:Hash`

### ISSUE THREAD

**Issue by ioquatix** [mperham/sidekiq#5380]
https://github.com/mperham/sidekiq/blob/4026085d35f1436f597fc107d331ae429e4d825a/lib/sidekiq/job_retry.rb#L73

It looks like `options` here can be a hash, butlater on in `Sidekiq::Component` it expects `config.logger` to work:

https://github.com/mperham/sidekiq/blob/4026085d35f1436f597fc107d331ae429e4d825a/lib/sidekiq/component.rb#L22

There are various other methods which don't seem to make sense for a `Hash` instance, unless `JobRetry` isn't expected to be instantiated with a Hash.

It's not really obvious from the documentation what is expected and if this has changed.

Thanks!

**Comment by mperham** [comment]
In 6.5, that arg is the Sidekiq module itself, quacking like a config hash. In 7.0 it will be a Sidekiq::Config instance.  See the notes in docs/.

**Comment by ioquatix** [comment]
Okay thanks. It might make sense to document the expected types next to the `def initialize(options)` method.
