### ISSUE TITLE
Potential database connections leaks from pool with .transactional_push!

### ISSUE THREAD

**Issue by Galathius** [mperham/sidekiq#5385]
Please check [this issue](https://github.com/Envek/after_commit_everywhere/issues/20) for `after_commit_everywhere` gem.

cc: @adamniedzielski, @mperham

**Comment by mperham** [comment]
Sidekiq always enqueues within an Executor. A 3rd party plugin might not.

**Comment by Galathius** [comment]
I wish it was true, but seems the problem is still here with `TransactionAwareClient`. 

You can check it by running the next two examples in rails console (which does not wrap the code with Rails Executor).

### Pre-requirements:

```
$ bundle add after_commit_everywhere sidekiq
```

`config/initializers/sidekiq.rb`:
```ruby
Sidekiq.transactional_push!
```

`app/jobs/test_job.rb`:
```ruby
class TestJob
  include Sidekiq::Job

  def perform
    # do nothing
  end
end

```

### Examples:
```ruby
5.times.map do |i|
  Thread.new do
    Rails.application.executor.wrap do
      sleep i
      TestJob.perform_async
    end
  end
end.map(&:join)

ActiveRecord::Base.connection_pool.connections.count # => 0
```
Everything is okay here, not db connection leaks.

```ruby
ActiveRecord::Base.connection # This line is needed to reproduce the problem with `after_commit_everywhere` 1.2.1 version
5.times.map do |i|
  Thread.new do
    sleep i
    TestJob.perform_async
  end
end.map(&:join)

ActiveRecord::Base.connection_pool.connections.count # => 5
```
5 connections were not retrieved to db connection pool. 

I'm still not sure where it should be fixed. Maybe we need to wrap `sidekiq client` code within **Rails Executor** context, or maybe will be enough to fix this issue on the `after_commit_everywhere` side. 

But anyway, would be better to be informed about this possible problem.
