### ISSUE TITLE
LoadError: cannot load such file -- rails

### ISSUE THREAD

**Issue by excelsior** [mperham/sidekiq#5386]
Ruby version: 3.1.2
Rails version: none
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.5.0

After upgrading to 6.5, launching Sidekiq fails with the following error:

```
/var/deploy/cr/web_head/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/cli.rb:269:in `require': cannot load such file -- rails (LoadError)
	from /var/deploy/cr/web_head/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/cli.rb:269:in `boot_application'
	from /var/deploy/cr/web_head/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.0/lib/sidekiq/cli.rb:42:in `run'
	from /var/deploy/cr/web_head/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.0/bin/sidekiq:31:in `<top (required)>'
	from bin/sidekiq:29:in `load'
	from bin/sidekiq:29:in `<main>'
```

We use Sidekiq in a non-Rails app, so naturally there's no `rails` file to load.

**Comment by mperham** [comment]
I'm not aware of any changes to cli.rb which would affect how it loads your application code. How exactly are you starting Sidekiq?

**Comment by excelsior** [comment]
By running a binstub generated via Bundler:

```
require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"

load Gem.bin_path("sidekiq", "sidekiq")
```

As far as I can see, `cli.rb` requires the `rails` file (which comes from the `railties` gem in Rails-based projects) in order to check whether the current Rails version is supported. However, Sidekiq doesn't depend on `railties`, hence the LoadError exception in a non-Rails environment.

**Comment by mperham** [comment]
I mean your command line. If you are not using Rails, you must point Sidekiq to an entrypoint to your app with `-r`, e.g. `-r ./boot_app.rb`.
