### ISSUE TITLE
Track where the job is being enqueued as ActiveRecord do with queries

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5390]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Sidekiq-Pro 5.2.4

Hey there, again!

I have an application that is queueing jobs more than expected and those jobs can be enqueued from dozens of different places (models, controllers, other jobs and so on).

How do you feel about adding some logging to track this in general (like AR for queries) in the logs?

Example:

```
Vendor Load (1.3ms)  SELECT "vendors".* FROM "vendors" WHERE "vendors"."id" = $1  [["id", 1]]
↳ app/controllers/vendors_controller.rb:100:in `update'
VendorWorker Enqueued (1.3ms)
↳ app/controllers/vendors_controller.rb:101:in `update'
```

That's just the rough idea but the goal is to be able to track from where the jobs are being enqueued from the logs.

A job might be enqueued from another worker, where we would see something like this:

```
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a INFO: start
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a worker=AnotherWorker INFO: enqueued
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a worker=AnotherWorker INFO: enqueued
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a worker=AnotherWorker INFO: enqueued
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a worker=AnotherWorker INFO: enqueued
pid=1 tid=3ksp class=VendorWorker jid=8ef28a988aa86dcea52f251a elapsed=2.988 INFO: done
```

That way we could tell/track from the logs "okay, VendorWorker was enqueued from controller X. this worker enqueued another 4 jobs and concluded.".

**Comment by mperham** [comment]
I'm fine with the idea in general. I have no problem adding more ActiveSupport instrumentation as long as it's optional. Sidekiq should not require Rails.

**Comment by sobrinho** [comment]
Alright, I will try to make a PR in the next few days.

**Comment by sobrinho** [comment]
Got busy with other stuff but I will try as soon I get some spare time, you can keep it closed.

If someone wants to implement this, ping me first if I didn't update here yet.

**Comment by tiegz** [comment]
Just ran across this PR because I have a similar desire, and wanted to mention that it's pretty simple with client middleware:

```
module Sidekiq
  module Middleware
    class EnqueueLogger
      include Sidekiq::ClientMiddleware

      def call(worker, job, queue, redis_pool)
        logger.info "enqueue worker=#{job["class"]} jid=#{job["jid"]} queue=#{job["queue"]}"
        yield
      end
    end
  end
end

Sidekiq.configure_client do |config|
  config.client_middleware do |chain|
    chain.add Sidekiq::Middleware::EnqueueLogger
  end
end
```

**Comment by sobrinho** [comment]
Also, you might want to add it on the server middleware as well.

**Comment by fatkodima** [comment]
Opened - https://github.com/sidekiq/sidekiq/pull/5833. Let me know what you think.

**Comment by mperham** [comment]
This isn’t something I want in core.  You are welcome to publish a gem.

**Comment by fatkodima** [comment]
Yes, I can do that. It can even be generalized to track locations for activejob, other background processors. 
This isn't something I am sure I would benefit on the projects I worked previously, so want to confirm its usefulness. 
@byroot  @nateberkopec you are working on huge rails codebases with lots and lots of background jobs and places where they are enqueued. Would such a tool (potentially) be useful there?

**Comment by nateberkopec** [comment]
Absolutely - was thinking of hooking this up to Gusto in the test environment actually. I want more visibility as to what jobs are being enqueued and executed in test envs.

**Comment by byroot** [comment]
> Would such a tool (potentially) be useful there?

So we don't use Sidekiq on our bigger apps, but I think we already do have a similar feature. I think it's useful yes. Could even make sense in Active Job IMO.

**Comment by fatkodima** [comment]
I created a draft version (no tests, no docs, not released yet etc) of the future gem - https://github.com/fatkodima/job_enqueue_logger. You can test it, it currently works only with sidekiq. Logging backtrace locations is disabled by default, only the log line stating the fact that the job was enqueued is printed. To enable backtrace locations: `JobEnqueueLogger.backtrace = true`. 

The [original PR](https://github.com/sidekiq/sidekiq/pull/5833) was implemented using sidekiq middleware. That would be the ideal approach, which does not depend on internals, but it has a flaw - for batch enqueuing jobs it will generate dozens of log lines (1 for each job), which makes these logs unusable. 

@sobrinho @nateberkopec Since you showed some interest in this, I need some help from you. Before finishing that gem, I would like to ask:
1. Can you share what, in your opinion, should this tool additionally do (besides just logging and backtraces) to be useful, if anything? How would you expect to use it (maybe describe some use case)?
2. Is `job_enqueue_logger` gem name good enough? Maybe you can propose some shorter and better name.

**Comment by fatkodima** [comment]
Released as a gem - https://github.com/fatkodima/job_enqueue_logger.

**Comment by sobrinho** [comment]
Thanks @fatkodima! ❤️❤️❤️

**Comment by fatkodima** [comment]
@byroot 
> So we don't use Sidekiq on our bigger apps, but I think we already do have a similar feature.

1. If that is easy to find in the shopify's codebase, can you share some details about what else it is doing besides maybe logging and backtraces, so I can improve the released gem? And it patches ActiveJob, correct?

> Could even make sense in Active Job IMO.

2. I am going to implement a PR to add printing backtraces to ActiveJob, so do you still feel like this is a good idea?

3. ActiveRecord prints only the top line of the stack - https://github.com/rails/rails/blob/021ed2526ad3770cec3877dcaf83da24b2ca894e/activerecord/lib/active_record/log_subscriber.rb#L150-L152 but that is not always enough to get the full picture and multiple lines would be needed. Wdyt about implementing some ability (via config option, for example) to be able to specify how many lines to print? That would be definitely implemented as a separate change.

**Comment by byroot** [comment]
> If that is easy to find in the shopify's codebase,

I couldn't find it after a few minutes, I'll see if I have more time later, sorry.

> do you still feel like this is a good idea?

Yes. However the devil is in the details of the implementation, but yes, please feel free to take a stab at it and ping me.

> 3\. Wdyt about implementing some ability (via config option, for example) to be able to specify how many lines to print?

Yes, there is definitely a tradeoff here. The last line isn't always enough, but printing lots of logs can be costly especially in production. I'd definitely start with one and see later about allowing more via a config
