### ISSUE TITLE
v6.5 "breaking" change?

### ISSUE THREAD

**Issue by codebender** [mperham/sidekiq#5391]
Ruby version: 3.1
Rails version: 6.1.x
Sidekiq / Pro / Enterprise version(s): 6.5

Hey Sidekiqers!

Previously in order to remove Sidekiq's default exception handling logger, some projects would do something like this:
```ruby
Sidekiq.error_handlers << MyCustom::ExceptionHandler::Logger.new
Sidekiq.error_handlers.reject! { |handler| handler.is_a?(Sidekiq::ExceptionHandler::Logger) }
```
Here is an example from gitlabs: https://github.com/gitlabhq/gitlabhq/blob/7eca3f56625526ffa7f263c1fef0fcea34de8ca6/config/initializers/sidekiq.rb#L33-L40

It looks like PR https://github.com/mperham/sidekiq/pull/5340 might have created an unintended breaking change while progressing forward to v7. Does it make sense to note this as a breaking change in the Changes.md?

It looks like the fix would be to update the `reject!` from the example line to something like: 
```ruby
Sidekiq.error_handlers.reject! { |handler| handler == Sidekiq.method(:default_error_handler) }
```

Perhaps we should add documentation around this in the wiki https://github.com/mperham/sidekiq/wiki/Error-Handling

Cheers

**Comment by mperham** [comment]
Use `clear` instead of depending on an impl detail.

**Comment by codebender** [comment]
Well I didn't want to clear what was already added by other initializers/gems. For example here is the list of error_handlers when the sidekiq.rb file is loaded:

```
#<Method: Sidekiq.default_error_handler(ex, ctx) /Users/matthewbender/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.1/lib/sidekiq.rb:81
#<Proc:0x0000000117c51ee0 /Users/matthewbender/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/newrelic_rpm-8.8.0/lib/new_relic/agent/instrumentation/sidekiq.rb:96
#<Proc:0x00000001171ab3d8 /Users/matthewbender/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rollbar-3.3.0/lib/rollbar/plugins/sidekiq.rb:15
```

 If I `.clear`, I lose my rollbar and newrelic error handlers, so I sort of have to depend on that implementation detail 😿

**Comment by mperham** [comment]
I wish I had a good answer for you. At some point, someone depends every implementation detail in Sidekiq and I can't refactor anything without breaking someone.

Any suggestions to improve this? Maybe use a default constant so you can do `error_handlers.remove(DEFAULT_HANDLER)`?

**Comment by codebender** [comment]
Not a big deal at all and totally understandable. 

💡 
Maybe we could add an opt out hatch while configuring, `config.remove_default_exception_handler`. Then the internals of what needs to be removed from `error_handlers` would be owned by the sidekiq code instead of the external code that is configuring sidekiq

**Comment by mperham** [comment]
I’m trying to avoid providing disable APIs for every Sidekiq default behavior. That’s more config knobs I have to test.

**Comment by codebender** [comment]
I feel your two arguments are contradictory. Depending on implementation details is bad of course but also not providing a safe way to opt out of the chosen default behaviors means people have to depend on implementation details of the gem to hack them out.

**Comment by mperham** [comment]
I would gladly accept a PR which enables `error_handlers.remove(DEFAULT_HANDLER)`. That's an easy fix and doesn't require a new API.

**Comment by codebender** [comment]
Mike,

So I think that would require me to convert error_handlers from being an Array and create a new Class that implements or delegates all the Array methods and adds the additional `.remove` method.  Am I thinking about that correctly?

**Comment by mperham** [comment]
I just intend for it to be an array and you’d  remove elements as normal.
Maybe I meant delete?

**Comment by codebender** [comment]
Ahh that makes a lot more sense
