### ISSUE TITLE
Sidekiq Pro SuperFetch implicitly depends on redis >= 4.5.0

### ISSUE THREAD

**Issue by mlarraz** [mperham/sidekiq#5394]
Sidekiq version: 6.5.1
Sidekiq Pro version: 5.5.0
Redis gem version: 4.4.0

Updating Sidekiq Pro from 5.2.3 -> 5.5.0 started throwing a few errors with `super_fetch` enabled.

Looking at the backtrace shows the code uses the ```conn.exists(x) > 0``` style.
However `#exists` only returns an Integer by default as of [redis 4.5.0](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#450).

This can be fixed by either raising the version constraint or using `#exists?` instead which is available since [redis 4.2.0](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#420) and works the same across versions.

**Comment by mperham** [comment]
Please use 4.5.0. I will fix the dependency version constraint.
