### ISSUE TITLE
Best practice for Puma?

### ISSUE THREAD

**Issue by softwaregravy** [mperham/sidekiq#5396]
Hi. Just piecing together some of the docs. I am using Rails on Puma on Heroku, all up to date. For a best practice, should I be doing anything in `config/puma.rb`? Specifically in the `on_worker_boot` method. Currently I am doing nothing special for Redis or Sidekiq. Currently I'm using Redis Enterprise Cloud plugin on Heroku and just setting the config var: `REDIS_PROVIDER:               REDISCLOUD_URL`

I am asking because I've seen a couple of posts (not in the sidekiq wiki) that suggest I should be open/closing connections. e.g. https://enmanuelmedina.com/en/posts/rails-sidekiq-heroku and https://devcenter.heroku.com/articles/concurrency-and-database-connections#multi-process-servers

Reading this, maybe I should be doing something like ...
```ruby
on_worker_boot do
  Sidekiq.reconnect! # no idea how to actually do this or if I should be trying
end
```
Thank you!

**Comment by mperham** [comment]
There’s nothing documented because there’s nothing for you to do.

**Comment by softwaregravy** [comment]
fantastic. Thank you
