### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by IK-Xneelo** [mperham/sidekiq#5405]
Ruby version:
`
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
`
Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.2.1
Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
```yml
---
:verbose: false
:require: ./config/boot.rb
:pidfile: ./tmp/pids/workers.pid
:max_retries: 5
:concurrency: 10
:queues:
  - critical
  - default
  - low

```

On production we are using Redis SSL of redis lab (rediss://username:password@redis-url.redislabs.com:port), It is working perfectly when we are trying to hit the API from (Postman/react-app), however, when we are trying to execute worker manually in production console (which is non-rails app) we are getting certificate error.

Also, I don't find any issue with Redis/RedisLab because when we are hitting redis with the same creds we are getting correct response (PONG).

```ruby

Sidekiq.configure_server do |config|
   ...
  config.redis = RedisEnvConfig.new.to_h
end

Redis.new(RedisEnvConfig.new.to_h).ping
=> "PONG"

```

**RedisEnvConfig** is our custom gem which returns below hash
```ruby
RedisEnvConfig.new.to_h
=> {:url=>"RedisLab URL",
 :password=>"password",
 :ssl_params=>
  {:cert=>
    #<OpenSSL::X509::Certificate
     subject=#<OpenSSL::X509::Name ...attributes >,
     issuer=#<OpenSSL::X509::Name ...attributes >,
     serial=#<OpenSSL::BN ...attributes>,
     not_before=2021-04-30 08:48:05 UTC,
     not_after=2026-04-30 08:48:05 UTC>,
   :key=>#<OpenSSL::PKey::RSA:0x000055b9ee15ac68>,
   :ca_file=>"/usr/src/redis_ca.pem"}}
```

**Comment by mperham** [comment]
This is not something Sidekiq can fix or help with. Several people have reported issues with SSL and Heroku recently.

**Comment by IK-Xneelo** [comment]
> This is not something Sidekiq can fix or help with. Several people have reported issues with SSL and Heroku recently.

Yes I get it. but we don't see any issue with redis/ssl config. Also, we are not using Heroku in our case. I might be wrong but there is some issue where sidekiq is unable to build a connection with redis when trying to start console. Because it is working perfectly when we are hitting the API from frontend.

**Comment by mperham** [comment]
You have not included a backtrace so I can’t tell where the error is occurring.

**Comment by mperham** [comment]
Maybe remove your custom cert config.

**Comment by IK-Xneelo** [comment]
> You have not included a backtrace so I can’t tell where the error is occurring.

So as I am trying to hit one of our worker from ruby console. We only have 2 lines in backtrace. I hope it will help you.

```ruby
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
from /usr/local/bundle/gems/redis-4.4.0/lib/redis/connection/ruby.rb:260:in `connect_nonblock'
```

> Maybe remove your custom cert config and see if it works by default.
It is working perfectly when hit by API. It is production environment I won't be able to remove the certification easily to verify it.

**Comment by mperham** [comment]
It specifically says the issue is local so I imagine there is some difference in production vs console.

**Comment by cabe56** [comment]
https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-from-sidekiq

**Comment by IK-Xneelo** [comment]
> Heroku uses self-signed certs. If using Rails, Sidekiq config has to be updated in an initializer. Here's how: https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-from-sidekiq

@cabe56 we are using RedisLab certs for our application and configuration is done in initializer. The thing is it works on production from API level but not from rails console.
