### ISSUE TITLE
retry count (not retry_in) based on error?

### ISSUE THREAD

**Issue by netwire88** [mperham/sidekiq#5406]
Ruby version:  3.1.2
Rails version: 6.1.5
Sidekiq / Pro / Enterprise version(s):  Sidekiq 6.4.1

Is there a way to customize the retry count within the worker class based on the error class that was raised? I know you can customize `sidekiq_retry_in`, but can I return false or something so it stops retrying and send directly to Deadset? The [help doc](https://github.com/mperham/sidekiq/wiki/Error-Handling) doesn't describe it.

Something like this:

```
  sidekiq_retry_in do |count, exception|
    case exception
    when SpecialException
      false
    end
  end
```

**Comment by mperham** [comment]
No, there’s nothing that I can think of to do this.

**Comment by mperham** [comment]
I don't like false because it's nebulous but as an alternative suggestion, what do you think about adding support for "action symbols" in the return value of `sidekiq_retry_in`, e.g. `return :kill` or `return :discard`?

**Comment by fatkodima** [comment]
Lgtm 👍 This way there is no need to introduce another api. 
I think, it is better to use `return :kill` since the `kill` terminology is already used in the source.

**Comment by netwire88** [comment]
Yes, less new API is better. As for terminology, on a minor note, :stop might less aggressive than :kill given everything that's going on

**Comment by mperham** [comment]
I’m ok with aliases and we should also support the same terminology as
ActiveJob as long as the semantics are the same.

**Comment by mperham** [comment]
Moving discussion to PR.
