### ISSUE TITLE
Sidekiq Entreprise Web shows internal container ip in queue name

### ISSUE THREAD

**Issue by tcarac** [mperham/sidekiq#5409]
Hi Michael, 

We recently switched from Heroku to ECS and queues started showing their internal ip in the process section.

Any clue if this can be fixed ? 

Ruby version: 3.1.2
Rails version: 7.0.1
Sidekiq Versions:
```
   sidekiq-ent (2.3.1)
      einhorn (>= 0.7.4)
      sidekiq (>= 6.3.0)
      sidekiq-pro (>= 5.3.0)
    sidekiq-pro (5.3.1)
      sidekiq (>= 6.3.0)
```

**Comment by tcarac** [comment]
![Screen Shot 2022-06-30 at 19 38 37](https://user-images.githubusercontent.com/64477810/176790615-9b55cf36-ebc4-4b13-8504-66b33f3251e7.png)

**Comment by tcarac** [comment]
![Screen Shot 2022-06-30 at 19 38 37](https://user-images.githubusercontent.com/64477810/176790770-a3bd27ed-b3ed-4d15-91fc-76ed96bf81d5.png)

**Comment by mperham** [comment]
That’s the machine’s hostname. Set the hostname to some thing else.
