### ISSUE TITLE
Advice: Limited list of Queues

### ISSUE THREAD

**Issue by softwaregravy** [mperham/sidekiq#5410]
Seeking some advice. Apologies if this is in the docs and I missed it.

I'm looking for a way to make sure I don't have orphaned jobs. I have a number of workers and a jobs. I put them in different queues to I can manage load and priority -- long running background jobs go in one queue with workers segregated from fast jobs which are more customer-impacting. 

As I create more jobs, I'm concerned one day I may fat-finger a queue name and not catch it. e.g. my workers read off queue "high" and I accidentally specify a queue for my job as "hihg" or something else. Any way to test that jobs and workers are only being assigned to work / enqueuing to a limited set of queues? I'd love to get an exception if I try to enqueue to a queue that doesn't exist or have a worker reading from it. Even better I would catch this before deploying

**Comment by mperham** [comment]
I don’t have a solution for you. To me this sounds like a linter or rubocop
cop to be run in CI.
