### ISSUE TITLE
Sidekiq not processing jobs

### ISSUE THREAD

**Issue by aramani-smartsheet** [mperham/sidekiq#5419]

**Comment by aramani-smartsheet** [comment]
Hello,
Our account (Smartsheet) is seeing Sidekiq not process any jobs in our production environment. We are seeing two things that stand out:
1. Sidekiq is throwing a LimiterError
2. Large number of deadlocks on our database (MySQL 5.7)
The queue size of unprocessed jobs is now 1.17 million and we need to troubleshoot this and drain the queue ASAP.

**Comment by swordfish444** [comment]
@mperham We're in the process of performing the steps in the troubleshooting. So far we've been able to clear the jobs in the queue by removing the Limitter. We found that the limiter was causing a problem where Redis `brpoplpush` would take longer than the default client timeout of 1s, and therefore, fail. 

Once we removed the limiter, we are continuing to see the _root cause_ (which likely led to the job queue building up to the point where redis operation took longer than 1s), which is jobs becoming stuck indefinitely. 

If you have any immediate thoughts on what we can try, please let us know. This is urgent. If you can join a hangout, that would be even better =D

**Comment by mperham** [comment]
@swordfish444 I don't understand your description of the Limiter issue. Can you expand?

I don't provide emergency debugging of Sidekiq problems. You have access to the full source code for everything; your team needs to be able to debug and diagnose your production issues. I will help where I can but I'm not a miracle worker -- I can't know what gems and other app code are doing.

**Comment by mperham** [comment]
If you use Scount, `bundle up scout_apm`.

**Comment by mperham** [comment]
The TTIN signal is your main tool for diagnosis. I am not available at all
this week.
