### ISSUE TITLE
What does `Sidekiq::Batch::Status.deleted` mean?

### ISSUE THREAD

**Issue by mollerhoj** [mperham/sidekiq#5420]
Sidekiq / Pro / Enterprise version(s):
```
    sidekiq-pro (5.3.1)
      sidekiq (>= 6.3.0)
```

Hi Mike, I'm trying to debug a batch - it's jobs are not run, but are logged as "deleted". I'm unsure what this means, and it does not seem to be mentioned in the wiki: https://github.com/mperham/sidekiq/wiki/Batches..

The jobs get "deleted" as soon as I start them. Any clue what could case this?

I don't use any 3-party plugins, and generally think my setup is fairly standard.

```
 #<Sidekiq::Batch::Status:0x00007fd9a7554258
  @bid="REwnfbWEmvFUPg",
  @completed=0,
  @failures=0,
  @pending=0,
  @props=
   {"created_at"=>"1657220428.8375108",
    "callbacks"=>"{\"success\":[{\"ItemManager\":{\"manager_id\":120956}}]}",
    "description"=>"...",
    "pending"=>"0",
    "total"=>"2",
    "kids"=>"0",
    "deleted"=>"2"},
  @total=2>]
  ```

**Comment by mperham** [comment]
Have you opened the code and looked where it sets the deleted flag to 2?

**Comment by mollerhoj** [comment]
A shot, turn out I grepped in sidekiqs code, not sidekiq-pros code. I see, `deleted == "2"` means that the batch completed.

I still think it might be worth it to add that info to the wiki - I thought deleted ment that that jobs were not run and got confused.

**Comment by mperham** [comment]
I try not to overload the wiki with really specific implementation detail. It's not black or white what details I should include or not. You're the first person to ask about this point so I think I will continue to advise people to dive into the code itself if they want to know some fine detail. I hope you were able to solve your problem.
