### ISSUE TITLE
JobRetry no longer sets default options param in v6.5 (breaking change)

### ISSUE THREAD

**Issue by mchong1** [mperham/sidekiq#5422]
Ruby version: 2.7.6
Rails version: 5.3.4
Sidekiq / Pro / Enterprise version(s): Ent: 2.5.0

As of [this change](https://github.com/mperham/sidekiq/pull/5340/files#diff-a2a78bd5586e1300341bb91dc8be382aa98126dcde11bd507fe9886d2e643ee7R73), JobRetries no longer accepts a default value for the `options` arg.  This breaks usages of JobRetry that don't pass a default value, for example, in the sidekiq-failures gem [here](https://github.com/mperham/sidekiq/pull/5340/files#diff-a2a78bd5586e1300341bb91dc8be382aa98126dcde11bd507fe9886d2e643ee7R73):

```ruby
      def retry_middleware
        @retry_middleware ||=
          Sidekiq::Failures.retry_middleware_class.new
      end
```
(Note that `Sidekiq::Failures.retry_middleware_class` returns `Sidekiq::JobRetry` for sidekiq versions >= 5.0.0).

Since this  behaviour changed between minor versions, I think it makes sense to report this as a breaking change here?
Seems like it would be a quick change to re-add the default value and add some specs, so happy to submit a PR if helpful.

Thanks!

**Comment by mperham** [comment]
Unless the API is considered public and documented in the wiki, I consider everything else an implementation detail which can change in a minor bump. Major bumps are for changes which will require significant user attention, e.g. Ruby version support, public API deprecation or change. Middleware is documented in the wiki but JobRetry is not a middleware.

I recommend you CI against Sidekiq main if you are using Sidekiq internal components and wish to catch breaking changes as early as possible.

I've never really understood the point of sidekiq-failures. The Retries and Dead tabs provide pretty comprehensive support for tracking and dealing with job failures. 🤷🏻‍♂️
