### ISSUE TITLE
Sidekiq::Senate.leader? doesn't seem to work as documented

### ISSUE THREAD

**Issue by jdelStrother** [mperham/sidekiq#5425]
Ruby version: 3.1.1
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.5.1 / Sidekiq Pro 5.5.1 / Sidekiq Enterprise 2.5.1

```ruby
class MyActor
  def initialize
    @done = false
  end

  def start
    @thread = Thread.new(&method(:process))
  end

  def stop
    @done = true
  end

  private

  def process
    until @done
      if Sidekiq::Senate.leader?
        puts "IM THE LEADER"
      end
      sleep 30
    end
  end
end

Sidekiq.configure_server do |config|
  config.on(:startup) do
    $my = MyActor.new
    $my.start
  end
  config.on(:quiet) do
    $my.stop
  end
end
```

I'm trying to have my leader process report queue stats to NewRelic, but the example code from https://github.com/mperham/sidekiq/wiki/Ent-Leader-Election#running-code-on-the-leader doesn't seem to work.  I get `undefined method 'leader?' for Sidekiq::Senate:Class (NoMethodError)`

It _is_ available as an instance method on that class, but I can't see a clean way of getting hold of the main Senate instance. What am I missing?

**Comment by mperham** [comment]
6.5.0 saw the start of some major refactoring around global APIs. You need to make your Actor a Sidekiq::Component and then you can simply call `leader?` implicitly.

```ruby
Sidekiq.configure_server do |config|
  config.on(:startup) do
    $my = MyActor.new(config)
    $my.start
  end
end

class MyActor
  include Sidekiq::Component
  def initialize(config)
    @config = config
  end
end
```

https://github.com/mperham/sidekiq/blob/main/docs/component.md

**Comment by jdelStrother** [comment]
Ohhh. Thanks, that works.

**Comment by Aubermean** [comment]
Enterprise Wiki [entry](https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election/fbcf7b2104d1bb399340f4fe84ac879ac08ee5e3) not updated since 2015, would helpful if it could be updated based on changes mentioned.

**Comment by mperham** [comment]
@Aubermean thanks, I've freshed it up.

**Comment by Aubermean** [comment]
Thanks @mperham! Updated URL for anyone who lands here :) https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election
