### ISSUE TITLE
Web UI assets not loading in apps deployed on Heroku (X-Sendfile not supported)

### ISSUE THREAD

**Issue by TheCorp** [mperham/sidekiq#543]
I am on 2.5.3 and not sure if I need to be on master to get the latest fixes for this stuff but when we deploy our sidekiq app to Heroku none of the web UI assets show up.

Unfortunately none of the FAQ/Troubleshooting advice applies to use since we don't have specific apache or nginix config to play around with on Heroku. Heroku does a rake assets:precompile upon deploy and I assume the assets in the Sidekiq gem don't get included in this and so requests to stuff like:

http://whatever.com/sidekiq/stylesheets/bootstrap.css return 200 but with a blank file. Here's the x-sendfile request I am seeing in Firebug

X-Sendfile  /app/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.5.3/web/assets/stylesheets/bootstrap.css

The file exists on the heroku dynos and I can load it from my Heroku console but X-Sendfile is not supported on the Heroku platform.

Any ideas on what the best way to resolve this would be?

**Comment by pedrocunha** [comment]
Posting here - since this is the first results on google. I've just fixed an issue with Rails 4.2 + sidekiq where accessing the sidekiq web UI used to never load properly assets on first hit. 

By disabling turbolinks in the original link it fixes the issue, example:
```ruby
 link_to 'Monitoring', sidekiq_web_path, data: { no_turbolink: true }
```
