### ISSUE TITLE
Sporadic failure loading web UI

### ISSUE THREAD

**Issue by darkhelmet** [mperham/sidekiq#5431]
Ruby version: 3.1.2
Rails version: 6.1.5.1
Sidekiq / Pro / Enterprise version(s): 6.5.1 / 5.5.1 / 2.5.1

- Initializer: https://gist.github.com/darkhelmet/a635bf70ef684eff1568dba79438bbad
- We don't use sidekiq.yml, just `bundle exec sidekiq -q ... -c ...`
- I upgraded to `hiredis-client` 0.5.1 as part of the upgrade to 6.5.x

![Screen Shot 2022-07-14 at 2 25 06 PM](https://user-images.githubusercontent.com/36123/179046366-6b34495a-7e5b-4b95-aa45-2cc48551334b.png)

I can refresh the various web UI pages and will sporadically get this failure with the 500 error page.

**Comment by darkhelmet** [comment]
I'll get a small app running to try.

I can run `1000.times { Sidekiq.redis { |r| r.call("INFO") { |i| i.lines(chomp: true).map { |l| l.split(":", 2) }.select { |l| l.size == 2 }.to_h } } }` in the `rails console` and it basically always works.

I also see that `Sidekiq.redis { |r| r.info }` gets the same output, but maybe that's a misuse of `redis-client`

**Comment by darkhelmet** [comment]
Related errors:

![Screen Shot 2022-07-14 at 2 51 07 PM](https://user-images.githubusercontent.com/36123/179049746-9ecfe5ce-4e42-4a5b-87bd-eec6a58b563c.png)
![Screen Shot 2022-07-14 at 2 51 01 PM](https://user-images.githubusercontent.com/36123/179049749-07f46e09-1cba-4d41-8f30-202303796cab.png)
![Screen Shot 2022-07-14 at 2 50 54 PM](https://user-images.githubusercontent.com/36123/179049755-f0f403a0-27e4-460a-8be6-af839fcf5602.png)

**Comment by mperham** [comment]
I can't tell what Redis code is running because the issue is with the return value, the stack has unwound from the redis library. I'll need that app to debug it.
