### ISSUE TITLE
Minimize bootup time overhead

### ISSUE THREAD

**Issue by fotinakis** [mperham/sidekiq#5435]
There are two places in sidekiq & sidekiq-pro which do "heavy" operations on bootup. In our use case, we are running thousands of sidekiq processes, so this bootup overhead slams redis often and creates spikey load issues.

In sidekiq: `Sidekiq::ProcessSet.cleanup` method
In sidekiq-pro: `Sidekiq::Pro::SuperFetch.cleanup_the_dead`

**Fix:** we discussed the fix for this as adding a 1 minute time-based lock/guard to throttle these methods from running too often. (It would be great if the lock seconds was a configurable option, so that we could tune this for our needs if needed)

**Comment by fotinakis** [comment]
Thanks very much @mperham and @SamArdrey !

Looking forward to upgrading this week once released and trying this out in prod.

**Comment by fotinakis** [comment]
@mperham friendly check in, do you have an ETA for 6.5.2 release which will include these changes?

**Comment by mperham** [comment]
You can run main today. I don’t have a release date and don’t expect one in the near future.

**Comment by fotinakis** [comment]
@mperham ok can do that for sidekiq, but I assume we can't access that for sidekiq-pro without a gem publish? Could you publish a beta version or something for us if not ready for a full patch release?

**Comment by mperham** [comment]
I just looked and 6.5.2 has more changes in it than I remembered so I will do a release. Thanks for the poke.

**Comment by fotinakis** [comment]
Fantastic, thanks!

**Comment by fotinakis** [comment]
@mperham do you have an ETA for the next sidekiq-pro release?

**Comment by mperham** [comment]
ETA: 1 minute ago.

**Comment by fotinakis** [comment]
Thank you!

**Comment by fotinakis** [comment]
@mperham @SamArdrey just wanted to send you a note to say thanks! These simple changes in sidekiq & sidekiq-pro to throttle the bootup overhead had a fantastic impact on the redis DB in our large sidekiq deployment:

![image](https://user-images.githubusercontent.com/75300/183760248-37644453-d2a2-4da6-8aa8-537c24290d8c.png)
^ we used to see spikes up to 150k ops/sec when autoscaling up many workers, now we rarely see 10k+ ops/sec

![image](https://user-images.githubusercontent.com/75300/183760627-2bd9edc1-eae1-482d-bf5a-1ca74b081763.png)
^ similarly, CPU would spike up to 80-100% and cause major redis latency issues and ops headaches, now we sit around 20% utilization

Huge impact, thanks for working through this with us and tackling this so quickly!
