### ISSUE TITLE
Retrieve Sidekiq batch status after completion

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#5436]
The documentation here (https://github.com/mperham/sidekiq/wiki/Batches) says - `Normally batches complete quickly and are removed from Redis upon success.`

Does this mean the following will fail if it is called after the batch has been completed?

```ruby
status = Sidekiq::Batch::Status.new(bid)
status.total 
status.complete?
```

We are on the following Sidekiq version - `Sidekiq v6.5.1 / Sidekiq Pro v5.5.1`

Thanks.

**Comment by mperham** [comment]
I've rewritten that section, I hope it answers your question:

https://github.com/mperham/sidekiq/wiki/Batches#linger-and-expiration
