### ISSUE TITLE
Unable to test sidekiq unique job

### ISSUE THREAD

**Issue by kimyu92** [mperham/sidekiq#5437]
Ruby version: 3.0.4
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.4.1 / 5.3.1 / 2.3.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
## Sidekiq Initializer
```
# config/initializers/sidekiq.rb
Sidekiq::Enterprise.unique!
```

## Sample code
```ruby
# Worker class
module Workers
  class FooBar
    include Sidekiq::Worker

    sidekiq_options unique_for: 5.minutes, unique_until: :start
  
    def perform(id)
      logger.info id
    end
  end
end

# Sample Service
class FooBarService
  def self.perform
    Workers::FooBar.perform_in(5.minutes, 1)
  end
end

# RSpec test
describe 'FooBarService' do
  let(:sidekiq_logger) { instance_double(Sidekiq::Logger, info: true) }

  before do
    allow(Workers::FooBar).to receive(:perform)
    allow(Sidekiq::Logger).to receive(:sidekiq_logger)
  end

  describe '.perform' do
    it 'calls right amount of times' do
      current_time = Time.current

      Timecop.freeze(current_time)
      FooBarService.perform

      Timecop.travel(6.minutes.after(current_time))
      expect(Workers::Foobar.jobs.size).to eq(1)

      Workers::Foobar.drain
      # uncomment out still not fixing the problem
      # Sidekiq::Worker.drain_all
      # Sidekiq::Worker.clear_all
      expect(Workers::Foobar.jobs.size).to eq(0)

      Timecop.travel(10.minutes.after(current_time))
      FooBarService.perform

      # Will probably see skipping enqueue for Workers::Foobar, not unique.
      # travel to any time would not work either
      # expect(Workers::Foobar.jobs.size).to eq(1)

      Timecop.travel(16.minutes.after(current_time))
      # Failing from here
      expect(Workers::Foobar.jobs.size).to eq(1)

      ::Workers::Foobar.drain
      # uncomment out still not fixing the problem
      # Sidekiq::Worker.drain_all
      # Sidekiq::Worker.clear_all

      expect(sidekiq_logger).to have_received(:info).exactly(2).times
      
      Timecop.return
    end
  end
end
```

## Issue 
I wasn't able to test whether some functionalities have being invoked at approximately right number of times. 

Somehow, Sidekiq doesn't seem to allow pushing the second job after the first one even after draining or moving time via `Timecop`. It still tries to `Skipping enqueue for Workers::FooBar` even though `Workers::FooBar.jobs.size` is down to zero.

**Comment by mperham** [comment]
Your test suite should test your code, not mine. The idea is you can test your configuration manually once and then forget about it.

**Comment by kimyu92** [comment]
> Your test suite should test your code, not mine. The idea is you can test your configuration manually once and then forget about it.

Normally that's the case. However, is there a reason why it doesn't work on test environment? 🤔  

The use case is that if the code is very critical, we want to assure it's always working. It also helps to detect if there might be regression introduced by sidekiq though.

**Comment by mperham** [comment]
Yes, setting up a full integration test environment with client side and
server side middlewares both running is quite tricky. Better to just test
manually.

**Comment by kimyu92** [comment]
> Yes, setting up a full integration test environment with client side and
server side middlewares both running is quite tricky. Better to just test
manually.

So, are you suggesting it's tricky and possible or it's completely not possible due to how it's implemented?

**Comment by mperham** [comment]
Anything is possible with enough time and effort.  I’m suggesting it’s not worth the time and effort.
