### ISSUE TITLE
RFC: Be able to test for "Redis connections is too small" before raising in Cli#run

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#5441]
## Background

I tried setting up my own Redis connection pool today for sidekiq.  The tests passed and the app booted and sidekiq web looked fine.  But, the workers had crashed on boot and could recover.

> Your pool of 5 Redis connections is too small, please increase the size to at least 12

## The 'ask'

I'd like to have a first-class way to handle this error, probably having a first class way to check that sidekiq can boot and/or have a way to configure notification of this failure.

## Relevant Code

```ruby
    # Code within this method is not tested because it alters
    # global process state irreversibly.  PRs which improve the
    # test coverage of Sidekiq::CLI are welcomed.
    def run(boot_app: true)
.....
      # Since the user can pass us a connection pool explicitly in the initializer, we
      # need to verify the size is large enough or else Sidekiq's performance is dramatically slowed.
      cursize = @config.redis_pool.size
      needed = @config[:concurrency] + 2
      raise "Your pool of #{cursize} Redis connections is too small, please increase the size to at least #{needed}" if cursize < needed
....
```

## Proposal

something like 

```ruby
def Cli.validate_pool!
      # Since the user can pass us a connection pool explicitly in the initializer, we
      # need to verify the size is large enough or else Sidekiq's performance is dramatically slowed.
      cursize = @config.redis_pool.size
      needed = @config[:concurrency] + 2
      raise "Your pool of #{cursize} Redis connections is too small, please increase the size to at least #{needed}" if cursize < needed
  true
end
```

and something like

```ruby
self.failsafe_notifier = ->(e, msg) {
  Rollbar.with_config(use_async: false) do
    Rollbar.error(e, msg)
  end
}
```

**Comment by mperham** [comment]
My suggestion is not to explicitly size the pool. Can you let Sidekiq size
it?

**Comment by bf4** [comment]
I can share the code which didn't work. I didn't size the pool with any explicit option

**Comment by mperham** [comment]
Please do. Something is forcing it to 5.

**Comment by bf4** [comment]
looks like the validation code is basically 

```ruby
Sidekiq.redis_pool.size < Sidekiq[:concurrency] + 2
```

and `Sidekiq.redis_pool` is 5 because `ConnectionPool:: DEFAULTS[:size]` is 5


looks like [sidekiq internals](https://github.com/mperham/sidekiq/blob/v6.5.1/lib/sidekiq/redis_connection.rb) are smarter that I am

```ruby
        size = if symbolized_options[:size]
          symbolized_options[:size]
        elsif Sidekiq.server?
          # Give ourselves plenty of connections.  pool is lazy
          # so we won't create them until we need them.
          Sidekiq[:concurrency] + 5
        elsif ENV["RAILS_MAX_THREADS"]
          Integer(ENV["RAILS_MAX_THREADS"])
        else
          5
        end

        verify_sizing(size, Sidekiq[:concurrency]) if Sidekiq.server?

        pool_timeout = symbolized_options[:pool_timeout] || 1

...
        ConnectionPool.new(timeout: pool_timeout, size: size) do
          redis_config.new_client
        end
```

it already makes a pool just fine and picks the pool size just fine and verifies it just fine

**Comment by bf4** [comment]
Unless I'm reading it wrong, the ConnectionPool gem has default to 5 when you wrote that code in 2011 https://github.com/mperham/connection_pool/commit/035e7519d2bfbafff04a5b15d57b6b9743989ea8 

```ruby
ConnectionPool.new {}.size
=> 5
```

**Comment by mperham** [comment]
I don't see an easy way to do this. My best practice is to let Sidekiq create and size the pool. If you create it yourself, you're taking on that responsibility to size it correctly.

**Comment by mperham** [comment]
I think Sidekiq only uses the default pool size on the client-side.
Server-side it always supplies a size value but it uses some fairly complex
logic to determine the size which can be very environment-specific. I don't
know that it's feasible to provide a CI helper.

**Comment by bf4** [comment]
Noting that this logic has moved to the [cli.rb in Sidekiq 7.x](https://github.com/mperham/sidekiq/blob/v7.0.1/lib/sidekiq/cli.rb#L91-L94) and the `Sidekiq[:concurrency]` interface present in 6.5.1 is not present in 7.x
