### ISSUE TITLE
undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by jcohenho** [mperham/sidekiq#5443]
I wish I could provide better context, but I can't pin down why or how this error happens, any ideas? 
Some things I did recently: 
Upgraded Rails from 5.2.3 -> 5.2.8 
Updated REDIS_PROVIDER env var in Heroku to a new Redis instance 

Sidekiq jobs are running and completing without any issue, but this error pops up in the logs every once in a while.

Ruby version: 2.7.3
Rails version: 5.2.8

Initializer: none (using REDIS_PROVIDER env var)

sidekiq.yml: 
```l
:concurrency: 5
:queues:
  - default
  - synchronize_to_redshift
```

Error:

`NoMethodError: undefined method 'call' for nil:NilClass`

Backtrace: 

`@callback.call(self, ex)`

Link to backtrace: https://github.com/mperham/sidekiq/blob/9d33caf487df94938bb39a8887983c1b28df5662//lib/sidekiq/processor.rb#L73

**Comment by mperham** [comment]
If you use Scout, update their gem.

**Comment by jcohenho** [comment]
@mperham This seems to have fixed the error, closing this issue now. It would be great if you could comment on why this was happening, thanks!

**Comment by mperham** [comment]
Search for scout in the closed issues and you'll find your explanation.
