### ISSUE TITLE
Straightforward way to report on which jobs were killed without turning on all debug logging?

### ISSUE THREAD

**Issue by f1sherman** [mperham/sidekiq#5445]
Ruby version: 3.1.2p20
Rails version: 6.1.6.1
Sidekiq / Pro / Enterprise version(s): 6.5.1 / 2.5.1 / 5.5.1

We would previously report on which jobs were running when dynos were shut down (which would help us know which jobs needed to be fixed) using the `Jobs still in progress` logging. This changed to the debug level in https://github.com/mperham/sidekiq/commit/062f07a7a5a8fba3f50464681215183de96ad265, which caused our logging to no longer pick these up. The reasoning for the change makes sense, but it would be great to have this ability back without having to turn on all debug logging. Any tips for how to do this?

**Comment by mperham** [comment]
I believe super_fetch logs the type of jobs it rescues. Would that give you the info you want?

**Comment by mperham** [comment]
I suppose we could adjust the logging back to info as long as we can trim the output to not be a giant hash.

**Comment by f1sherman** [comment]
> I believe super_fetch logs the type of jobs it rescues. Would that give you the info you want?

Yeah that would work. Any insight on what we could search for to find that log statement?

> I suppose we could adjust the logging back to info as long as we can trim the output to not be a giant hash.

That would work too, all we need is the job class name.

**Comment by mperham** [comment]
I believe the string “SuperFetch” will find relevant lines.

**Comment by f1sherman** [comment]
I'm looking but sadly I can't find anything useful when searching for "SuperFetch". I do see lines like the below, but they only print the job ID rather than the class name:

```
INFO: SuperFetch: Moving job from queue:sq|worker.1:53:050b294ce80a|low_priority back to queue:low_priority 
```

**Comment by f1sherman** [comment]
Ah, nevermind. I wasn't looking back far enough. I do see a log statement starting with `SuperFetch recovered orphan job:` that should work for our purposes. Thanks!
