### ISSUE TITLE
Feature Request: Allow customizing job display in Sidekiq Web admin

### ISSUE THREAD

**Issue by jordan-brough** [mperham/sidekiq#5448]
We'd like to be able to display custom job attributes in the Sidekiq admin. The admin displays job _arguments_, but when using an Sidekiq extension that adds a custom attribute, it'd be helpful to be able to see that also.

For example, we use [ros-apartment](https://github.com/rails-on-services/apartment) and [ros-apartment-sidekiq](https://github.com/rails-on-services/apartment-sidekiq) for multi-tenancy.
Those gems add an `apartment` attribute to Sidekiq jobs. i.e., they store data like this:
```ruby
>> Sidekiq::Queue.new('default').first.item['apartment']
=> 'sometenant'
```

When I view jobs in the Sidekiq admin I can't see the `apartment` attribute in the admin.

We recently added this to our codebase:
```ruby
module SidekiqJobRecordDisplayArgs
  def display_args
    [super, item.slice("apartment")]
  end
end
Sidekiq::JobRecord.prepend(SidekiqJobRecordDisplayArgs)
```
and that works well enough for what we need:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/23050/181129693-54502f8b-0d53-40c7-9144-39af209a869e.png">

Is there any kind of config available or that you might be willing to add along these lines that makes something like this possible without monkey patching?

**Comment by mperham** [comment]
The data does appear on the job detail page, see eg the retry tab and its linked jobs. Enqueued jobs usually go by so fast that there’s little point in seeing a lot of detail on that page.

**Comment by jordan-brough** [comment]
It would similarly be nice to be able to display the tenant directly on the `/sidekiq/retries` page, instead of having to click through into the details, though I haven't wanted that as often as I've wanted it on the `/sidekiq/queues/xxx` page.

**Comment by mperham** [comment]
I think anything you want displayed on the page, you can pass it as an argument to the job. Works everywhere today.

**Comment by jordan-brough** [comment]
@mperham that doesn't work with `ros-apartment-sidekiq` because the tenant is an item-level attribute rather than a job argument.

Are you saying that you'd prefer to see a multi-tenant application pass the tenant as an extra argument to every job? Rather than adding it as an item-level attribute?
If so that would make it harder to add something like `ros-apartment-sidekiq` to an application. And if you wanted to use any third-party-provided jobs, you'd need to add some sort of wrapper around them in order to enable that, I think?

But if you think `ros-apartment-sidekiq` uses a reasonable approach to providing multi-tenancy then what you suggest doesn't seem possible.

**Comment by mperham** [comment]
I'm saying the value can be in both places. Item-level for r-a-s, job argument for web ui visibility.

**Comment by jordan-brough** [comment]
You're saying I would keep the item-level attribute that the apartment gem provides automatically, and then I would _also_ update all my jobs to take "tenant" as an extra argument, and then all my enqueues look like:
```ruby
MyJob.perform_async(arg1, arg2, arg3, Apartment::Tenant.current)
```
?
And if I have any third-party provided jobs then I write a wrapper around them?

I was hoping that whatever solution came out of this issue might be something that I could contribute upstream to the apartment gem, but the above sounds pretty unlikely.  It also sounds fairly verbose & tedious compared to exposing information that's already available in every job.  Do you not feel that setting item-level attributes is a reasonable thing for sidekiq extensions to do?

**Comment by jordan-brough** [comment]
E.g. one thought I had was it would be nice to have a Sidekiq config like:
```ruby
Sidekiq.configure_server do |config|
  config.display_item_attributes = ["apartment"]
end
```

But do you not officially support adding item-level attributes, or something like that?

**Comment by mperham** [comment]
I think I’m ok with displaying any ctx hash associated with ActiveSupport::CurrentAttributes as that is a Rails standard. I’m not ok with a bunch of logic to pull out arbitrary item-level k/v pairs.

**Comment by mperham** [comment]
Oops, “cattr”. https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/middleware/current_attributes.rb

**Comment by jordan-brough** [comment]
I think that will work great. 👍 I didn't know `Sidekiq::CurrentAttributes` existed.
That will let us eliminate some other custom code we had as well.

I'll also take that to the `ros-apartment-sidekiq` maintainers and see if they'd considering updating their code to use `ActiveSupport::CurrentAttributes` and `Sidekiq::CurrentAttributes` as the method of storing/fetching the current tenant, instead of setting an attribute directly on the job.

Should I open a separate issue requesting the display of CurrentAttributes on `/sidekiq/queues/xxx` and `/sidekiq/retries`?

**Comment by mperham** [comment]
That sounds good. 👍🏼 The Web UI logic becomes as simple as `show_cattr_column if defined?(Sidekiq::CurrentAttributes)`. 

I wonder what percentage of users enable CurrentAttributes and if it should simply be enabled by default... 🤔

**Comment by mperham** [comment]
> I didn't know `Sidekiq::CurrentAttributes` existed.

Always read the changelog. I don't have a better way to announce new features. https://github.com/mperham/sidekiq/blob/main/Changes.md#630

**Comment by jordan-brough** [comment]
New issue: https://github.com/mperham/sidekiq/issues/5450
