### ISSUE TITLE
Feature request: Display CurrentAttributes on index pages

### ISSUE THREAD

**Issue by jordan-brough** [mperham/sidekiq#5450]
This request came out of https://github.com/mperham/sidekiq/issues/5448.

We have a multi-tenant application and it would be very helpful to be able to see tenant information on admin pages like  `/sidekiq/queues/<queue_name>` and `/sidekiq/retries`.

In our case we have a hack in place to display the tenant (the `apartment`) like this:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/23050/181129693-54502f8b-0d53-40c7-9144-39af209a869e.png">

@mperham said in https://github.com/mperham/sidekiq/issues/5448 that it would be reasonable to display the `cattr` attributes when present (or possibly even by default)

Some context from me from the other issue, regarding displaying a job's tenant on these pages:
> The times when I want [the tenant] on the "Current jobs" page are often error scenarios. E.g. we got a bunch of errors and I've paused the queue and I want to see what's in it. Or the queue has grown large and I want to get a feel for the contents by randomly paging through some of the pages.
> In those scenarios knowing the tenant is usually important, and it's really helpful to have that show up on those index pages (without having to click through into any job details even).

**Comment by jordan-brough** [comment]
RE @mperham's comment in the other issue:

> The Web UI logic becomes as simple as `show_cattr_column if defined?(Sidekiq::CurrentAttributes)`.
> I wonder what percentage of users enable CurrentAttributes and if it should simply be enabled by default

Having a column show up by default might be a nice way to advertise the availability of the feature?

**Comment by mperham** [comment]
I've added a Context column to the queue table only for now. The retry table has a lot more columns and is pretty busy already to justify another column.

**Comment by jordan-brough** [comment]
That was fast! Thank you!
