### ISSUE TITLE
Sidekiq Jobs stuck in the busy tab for hours and restart is required

### ISSUE THREAD

**Issue by md-farhan-memon** [mperham/sidekiq#5453]
Ruby version: 2.7.3
Rails version: 6.1.6
Sidekiq version(s): 6.5.1, 5.2.10, 4.2.10

It all started when we upgraded to rails 6 from 5 few days ago. Things were good on staging environment when tested. Only difference on staging/development and production is that on production we use multiple instances of Sidekiq on production.

Issue:
Sidekiq Jobs get stuck for minutes and hours which for a fact I know should not take more than few seconds.
We thought it is due to some incompatibility or version conflicts and read in Sidekiq wiki to upgrade 1 major version at a time, thus downgraded sidekiq to v5.x, then back to v4.x. But same behaviour.

Now I tried similar configuration on my dev machine and ran two instances on sidekiq. I could reproduce it.

![screencapture-localhost-3000-sidekiq-busy-2022-07-30-13_34_55](https://user-images.githubusercontent.com/16094436/181903332-1cea2a9f-9c05-4e2a-be84-d0f1f97c68b3.png)

Nothing suspicious in the logs, infact the stuck jobs were not printed in the logs I believe.
Then I hit `ctrl + c` and tried to stop worker, and it was really new for me, lots of logs and crash report. I tried to wrap my head around it but unfortunately it was beyond.

I am adding those logs and crash report here, it is for Sidekiq v4.2.10. Since it is a production and critical issue for us, please help me what am I missing or guide in some direction. Much appreciated.

[terminal_logs.log](https://github.com/mperham/sidekiq/files/9225865/terminal_logs.log)
[DiagnosticReports_ruby-2022-07-30-132650.ips.log](https://github.com/mperham/sidekiq/files/9225868/DiagnosticReports_ruby-2022-07-30-132650.ips.log)

Sidekiq initializer:
````
require 'sidekiq'
require 'sidekiq/web'
require "sidekiq/api"
require 'sidekiq-scheduler/web'

Sidekiq::Web.use Rack::Auth::Basic do |user, password|
  [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
end

if Rails.env.production?
  namespace = "redis-#{Rails.env}"
else
  namespace = "redis-comm-dashboard-#{Rails.env}"
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'],
                   network_timeout: 5,
                   namespace: namespace
                 }
  config.error_handlers << Proc.new do |ex,ctx_hash|
    Rails.logger.error('Captured in sidekiq error block')
    Airbrake.notify(ex, ctx_hash)
  end
  SidekiqScheduler::Scheduler.enabled = false
end

Sidekiq.configure_client do |config|
  config.redis = {
                   url: ENV['REDIS_URL'],
                   network_timeout: 5,
                   namespace: namespace
                 }
end

Sidekiq.logger.level = Logger::INFO

if Sidekiq.server? && ENV['SCHEDULER'] == 'yes'
  SidekiqScheduler::Scheduler.enabled = true
  Sidekiq.logger.info("Detected sidekiq server initialization, loading schedule.")
  reminder_schedules = Sidekiq.get_schedule.select {|k, v| k.starts_with?("#{ReminderSchedule::REMINDER_SCHEDULE_PREFIX}_")}
  schedule = reminder_schedules.merge(YAML.load_file(File.expand_path("../../../config/cron.yml",__FILE__)))
  Sidekiq.schedule = schedule
end
````
sidekiq.yml
````
---
:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:dynamic: true
development:
  :concurrency: 30
staging:
  :concurrency: 5
sandbox:
  :concurrency: 5
production:
  :concurrency: 30
:queues:
  - q_1
  - q_2
  - [q_3, 2]
  - q_4
:process_limits:
  q_1: 2
:limits:
  q_2: 1
````

**Comment by mperham** [comment]
It looks like you are triggering rails/rails#36810 somehow.

```
action_mailer/rescuable.rb:25:in `block in process'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in `process'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/simpl-farhan/Documents/workspace/communication-dashboard/bundle/ruby/2.7.0/gems/actiontext-6.1.6.1/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine

**Comment by mperham** [comment]
The only known major crash with current sidekiq and current rails is with the scout_apm gem. If you use it make sure you have updated it to the latest version.

**Comment by mperham** [comment]
The only known major crash with current sidekiq and current rails is with the scout_apm gem. If you use it make sure you have updated it to the latest version.

**Comment by md-farhan-memon** [comment]
Thanks for some info @mperham .
We are not using `scout_apm` so that's out of the picture at least.
But the behaviour is exactly what is described in rails issue. We are not on `zeitwerk` yet and use defaults of '5.0`.

Although issue was closed, it doesn't seem to have resolved. Somebody reported in v7 too.

Any thoughts / work arounds on this?

**Comment by mperham** [comment]
Get on zeitwerk.

**Comment by md-farhan-memon** [comment]
The issue was identified. It was due to the ruby v2.7.3 [bug](https://bugs.ruby-lang.org/issues/17781). We upgraded to a later version and it is now resolved. 
It might help others in future searches.
