### ISSUE TITLE
Sidekiq server enqueueing jobs in a different redis?

### ISSUE THREAD

**Issue by tomassiNico** [mperham/sidekiq#5454]
Hi there!

In my company we are trying to do a migration from one redis to a new one.

At first we tried to migrate the redis data with `MIGRATE` command of Redis, but we got problems with the new redis that uses ssl conection.
So we decided to let 2 sidekiq servers running, one pointing to the new redis (all the new jobs are enqueue in the new redis) and one sidekiq server pointing to the old redis (OLD_SIDEKIQ_SERVER). The idea is let the OLD_SIDEKIQ_SERVER proceesses all the remaining jobs and empties redis, and after that we gonna remove this sidekiq server.

We have this sidekiq configuration:

```rb
# sidekiq.rb
# frozen_string_literal: true

Redis.exists_returns_integer = true

sidekiq_redis_url = if ENV['USE_OLD_REDIS_URL_SIDEKIQ'].present?
                      Rails.application.credentials.old_sidekiq_redis.fetch(:url) { 'redis://localhost:6382/0' }
                    else
                      Rails.application.credentials.sidekiq_redis.fetch(:url) { 'redis://localhost:6379/0' }
                    end

Redis.current = ConnectionPool.new(size: (Sidekiq.server? ? 25 : 5), timeout: 5) do
  Redis.new url: sidekiq_redis_url, network_timeout: 5
end

Sidekiq.configure_server do |config|
  config.redis = Redis.current
end

Sidekiq.configure_client do |config|
  config.redis = Redis.current
end
```
We run 2 sidekiq server, one pointing to the new redis and other pointing to the old redis, also we have 1 redis client pointing to the new redis. We don't have any redis client pointing to the old redis to avoid enqueue new jobs in that redis.

But we saw that the `scheduled_size` of the OLD_SIDEKIQ_SERVER was increasing. We think that is because we have some jobs that use `Sidekiq::Client.push_bulk`, but this new jobs were enqueued in the old redis.

For exampe we have some jobs like this
```rb
class CreateBulkDummyJobs
  include Sidekiq::Worker
  include Logable

  def perform
    logger.info { "Enquing DummyJobs" }

    pushed_jobs_ids = Sidekiq::Client.push_bulk('class' => DummyJob, 'args' => [[1], [3], [4], [5], [6]])
  end
end
```

So we try this config

```rb
sidekiq_redis_url = if ENV['USE_OLD_REDIS_URL_SIDEKIQ'].present?
                      Rails.application.credentials.old_sidekiq_redis.fetch(:url) { 'redis://localhost:6382/0' }
                    else
                      Rails.application.credentials.sidekiq_redis.fetch(:url) { 'redis://localhost:6379/0' }
                    end

Redis.current = ConnectionPool.new(size: (Sidekiq.server? ? 25 : 5), timeout: 5) do
  Redis.new url: sidekiq_redis_url, network_timeout: 5
end

Sidekiq.configure_server do |config|
  config.redis = Redis.current
end

Sidekiq.configure_client do |config|
  # this is because we wish that new jobs or retries of old jobs are enqueued in the new redis, but we saw that this block is not executed when you run a sidekiq server
  config.redis = ConnectionPool.new(size: (Sidekiq.server? ? 25 : 5), timeout: 5) do
    Redis.new url: Rails.application.credentials.sidekiq_redis.fetch(:url) { 'redis://localhost:6379/0' }, network_timeout: 5
  end
end
```

But this config does not work :(
When `Sidekiq::Client.push_bulk` is called the connection used is with the old redis.

I saw that I can initialize the `Sidekiq::Client` with a new connection like this

```rb
class CreateBulkDummyJobs
  include Sidekiq::Worker
  include Logable

  def perform
    logger.info { "Enquing DummyJobs" }

    redis_pool = ConnectionPool.new(size: (Sidekiq.server? ? 25 : 5), timeout: 5) do
      Redis.new url: Rails.application.credentials.sidekiq_redis.fetch(:url) { 'redis://localhost:6379/0' }, network_timeout: 5
    end

    pushed_jobs_ids = Sidekiq::Client.new(redis_pool).push_bulk('class' => DummyJob, 'args' => [[1], [3], [4], [5], [6]])
  end
end
```

But I have to change it everywhere where `Sidekiq::Client` it's called.
Do you see any problem with this implementation? Or are there a better way to this?  I would like that all the new job are enqueued in a specific redis and not the same from it was taken.

Sidekiq v6.1.2

**Comment by mperham** [comment]
The best and quickest way to migrate Redis is to use replication to seed
the new server and accept a few seconds of downtime to switch over.

You can adjust the client Redis easily but, as you've discovered, the
default connection pool for Sidekiq::Client within the Sidekiq process is
the server pool. You either need to use a Sharding setup (which you've
done) or let the old Redis get new jobs from the Sidekiq process. They will
trickle down and eventually stop over time.

**Comment by tomassiNico** [comment]
Hi Mike,
>The best and quickest way to migrate Redis is to use replication to seed
the new server and accept a few seconds of downtime to switch over.

We cannot use replication because our provider does not support this feature. 

So we gonna use Sharding.

Thanks for your answer.
