### ISSUE TITLE
Children empty batches do not trigger callback

### ISSUE THREAD

**Issue by thom-des** [mperham/sidekiq#5455]
Ruby version: 3.1.1
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): Entreprise
Sidekiq version : 6.3.1 (reproduced with 6.5.1)
Sidekiq Pro version : 5.3.1 (reproduced with 5.5.2)
Sidekiq Ent version : 2.3.1 (reproduced with 2.5.1)

When starting a batch from within a parent batch, it pushes the batch to redis even if it has no jobs. The implementation explicitly non skipping it when the batch has a `myparent` it pushes an empty batch that will never be able to complete.

<img width="1176" alt="Capture d’écran 2022-08-04 à 19 00 02" src="https://user-images.githubusercontent.com/20637989/182910809-9bc0b02a-6fbf-4f17-a040-85042ae03a8b.png">

Our usage looks like :

```
class ParentWorker
  include Sidekiq::Job

  def perform
    batch.jobs do
      ChildWorker.perform_async(batch.bid)
    end
  end

  def batch
    @batch ||= Sidekiq::Batch.new.tap do |batch|
      batch.description = "Parent batch".
      batch.on(:success, MyCallback)
    end
  end
end

class ChildWorker
  include Sidekiq::Job

  def perform(parent_bid)
    Sidekiq::Batch.new(parent_bid).jobs do
      batch.jobs do
        # Do stuff but don't schedule any job
      end
    end
  end

  def batch
    @batch ||= Sidekiq::Batch.new.tap do |batch|
      batch.description = "Child batch".
      batch.on(:success, MyCallback)
    end
  end
end
```

**Comment by mperham** [comment]
The Batches wiki page explicitly states that empty batch behavior is
undefined.
