### ISSUE TITLE
v6.5.2 introduced an undeclared dependency on concurrent-ruby

### ISSUE THREAD

**Issue by fallwith** [mperham/sidekiq#5456]
#5384 added a new `require "concurrent"` line atop `lib/sidekiq/metrics/shared.rb`, effectively making the project depend on [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby) and crashing a system of ours that didn't posses that library.

We noticed this unexpected dependency change when upgrading from v6.5.1 to v6.5.2.

Is it possible to make the `require` statement conditional on `concurrent-ruby`'s optional presence or to declare a `concurrent-ruby` dependency in `sidekiq.gemspec` if it's truly going to be required going forward?

**Comment by mperham** [comment]
Sorry about that, I haven't decided if I want to depend on `concurrent-ruby` just for one class. I'll hash that out for 7.0; metrics is meant to be opt-in until 7.0.

**Comment by mperham** [comment]
6.5.3 is out.

**Comment by fallwith** [comment]
Thanks very much for the quick turnaround, @mperham! I retested with v6.5.3 and unfortunately the `metrics/query.rb` file still gets brought in, and it in turn brings in `metrics/shared.rb`. It doesn't look like I can reopen this issue, so I've created #5457.

**Comment by mperham** [comment]
Ugh, I need to really integration test against bare Ruby.

I can't fix this until tomorrow.
