### ISSUE TITLE
Improve metrics UI

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5458]
This is a general placeholder for any upcoming work on improving and polishing the Metrics UI.

**Comment by adamlogic** [comment]
Hey @mperham, I'd love to help with this! I've spent a bit of time digging into the current implementation, and I want to summarize my current understanding.

**Data**

From what I can tell, the current metrics implementation gives us access to the following data:

- Processed count, failed count, and total exec time
	- For all jobs, and each individual job class
	- By the day, hour, and minute (retained for 90 days, 7 days, and 8 hours respectively)
	- Stored as hashes at each point in time
	- Processed count includes successful and failed jobs
	- Exec time does not include failed jobs
- Histogram exec times
	- For each individual job class
	- By the minute (retained for 24 hours)
	- Stored as BITFIELD for each combination of job class and point in time
	- Histogram is a collection of job counts broken up over 26 exec time buckets

**Tracking & collection**

The `ExecutionTracker` is injected as server middleware. For each job, it tracks the execution time and records the histogram value. This data is kept in memory.

On each "beat" (which I think runs every 5 seconds—I'm still a bit confused by the heartbeat), these in-memory metrics are flushed to Redis.

**JS lbraries**

Here are the tools/libraries I see currently in use by the Sidekiq UI:

- Charts: [D3](https://d3js.org) [3.5.16](https://github.com/d3/d3/releases/tag/v3.5.16) & [Rickshaw](https://tech.shutterstock.com/rickshaw/) [1.6.0](https://github.com/shutterstock/rickshaw/releases/tag/v1.6.0)
- JS behavior utilities: None

**Technical questions**

- Are you open to tracking other metrics? Personally I think latency per queue over time would be very useful.
- Are you open to other charting libraries? I use D3 on Rails Autoscale, and while it's super powerful, I'm not sure I'd recommended for open source. It's got a significant learning curve, and it's very easy to get out of date (v3.5.16 is over six years old). I don't have a ton of experience with other libraries, but I'd probably recommend [Chart.js](https://www.chartjs.org) for its popularity, ecosystem, docs, and beautiful charts.
- Are you open to lightweight JS behavior utilities like [Alpine](https://alpinejs.dev) or [Stimulus](https://stimulus.hotwired.dev)? Both of these operate on server-generated HTML—no client-side rendering. I'm a huge Alpine fan, but Stimulus is more common in Rubyland.

**Functional questions**

- Are there specific charts you have in mind?
- Are there specific questions you want these visualizations to answer for a user?

Happy to pair on this with Tuple, or we can keep it async if you prefer.

**Comment by mperham** [comment]
That’s a really impressive summary of the current implementation.

 I would prefer to use the existing Javascript because it is already there and we don’t have to make any changes, however I’m OK with using specific JavaScripts just on the metrics pages if necessary.

Queue latency is already something that sidekiq enterprise emits metrics for and people likely already have dashboards around so I don’t see any reason to include that when most of our use cases here are around profiling job run times.

i’ll schedule some time tomorrow for us to pair and chat more about this sometime next week

**Comment by mperham** [comment]
See the Metrics wiki page for rough use cases.

**Comment by mperham** [comment]
Ideas to ponder further:

- Rewrite real-time Dashboard to immediately fill with metrics data from the last hour, rather than relying on it filling up over time as today.
- On Metrics home page, show some sort of graph too? No live polling or real-time updates. User should refresh the page manually if they want current data.
- On Metrics Job page, show graphs with job performance over last hour. Integrate histogram bucket data somehow. Bubble graph? Box plot with whiskers?
- Graphs should answer questions: which job types are slowest? Which job types are variable in performance?

**Comment by adamlogic** [comment]
@mperham When you're working on the web UI (specifically for the `myapp` sample app), have you found a dev workflow that lets you see your changes without restarting your Rails server?

**Comment by mperham** [comment]
I think there a FAQ entry in the wiki about this, never used it.

**Comment by adamlogic** [comment]
I posted a draft PR with an initial attempt. https://github.com/mperham/sidekiq/pull/5467

**Comment by collimarco** [comment]
+1 for "**queue time**" (i.e. "time job execution starts" - "time a job is scheduled to run")

It would be really useful to have this included in the Sidekiq dashboard.

**Comment by collimarco** [comment]
Another interesting metric would be **throughput** of a queue (i.e. number of jobs finished each minute). For example a job that is finished, should increment a counter in Redis "myqueue:20221026_17:06". Then we can easily plot that counters on a graph and see the throughput (useful for example to see the max throughput during peak usage and see how infrastructure changes may impact the throughput).

**Comment by mperham** [comment]
The job metrics, as currently implemented, are focused on job class. They don't track anything about queue as that's orthogonal to job class.

**Comment by mperham** [comment]
DataDog and similar systems may already collect and provide runtime data/graphs on queues if you want something today.

**Comment by collimarco** [comment]
I said "queues" but in reality it would be also interesting to have those metrics for each "job class" (it would be equally useful for us). It is just an idea in any case, for now we use a custom solution with Rails / Datadog. In the future it would be nice to have "queue time" and "throughput" in the Sidekiq metrics.

**Comment by jrcasso** [comment]
@mperham what do you think about adding pagination to the Sidekiq Metrics UI at the bottom? We have many jobs that we'd like to view metrics on, some that run less frequently than the top 20.

**Comment by mperham** [comment]
I'm not really a fan of paginating the data. The data is sorted so the top rows are the ones really needing attention. We could increase the row count to 30 or 50, that would be easy enough and keeps the page simple.
