### ISSUE TITLE
retry_count not populated for hard shutdowns

### ISSUE THREAD

**Issue by acatighera** [mperham/sidekiq#5459]
Ruby version: 3.0.4
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): Enterprise

```
class SidekiqRetryMiddleware
  def call(_worker, job, _queue)
    JobLatch.modify_job_hash_with_retry_count_token!(job)
    yield
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add SidekiqRetryMiddleware
  end
end
```

We added some custom middleware and it seems like retry_count is not populated for Sidekiq::Shutdown. It is always populated whenever there is a normal exception. The retry_count behavior isn't documented anywhere I could find. It seems like an issue that retries from hard shutdowns don't increment the retry_count.

Thanks for the help!

**Comment by mperham** [comment]
Hard shutdowns do not generate retries. Retries are for when a job raises an unexpected error due to a bug. Shutdown means the process is exiting and the job will be restarted ASAP.

**Comment by acatighera** [comment]
Is there anyway using middleware or callback to add a custom additional count argument to the jobs that get bulk re-enqueued?

**Comment by mperham** [comment]
Nope, bulk requeue uses the original JSON string as it needs to happen as fast as possible since the process is shutting down ASAP. If you do have a long running job which is frequently restarted, you should keep track of progress somewhere else.

Retries do serialize the job hash to preserve any mutation in state, obviously because the failure data is part of that state.

**Comment by acatighera** [comment]
I see, one last followup q, does this on-shutdown event always happen before job restart?
```
Sidekiq.configure_server do |config|
  config.on(:shutdown) do
```

**Comment by mperham** [comment]
Yes, it fires when the process first receives TERM. hard_shutdown will occur N (`-t N`) seconds later.
