### ISSUE TITLE
Different process+worker name in Heroku logs

### ISSUE THREAD

**Issue by jchatel** [mperham/sidekiq#5465]
Ruby version: 2.7.2
Rails version: 6.1.5
Sidekiq / Pro / Enterprise version(s): Entreprise

```
gem 'sidekiq', '~> 6.2.2'
gem 'sidekiq-scheduler', '~> 2.2.2'
gem 'sidekiq-unique-jobs', '7.0.0.beta27'
gem 'sidekiq-pro', '~> 5.2.4'
gem 'sidekiq-ent', '~> 2.2.3'
```

Now we are moving to Entrprise and since we will significantly reduce the number of dynos, pretty much all our logs will be prefixed with `app[sidekiq.1]`

<img width="182" alt="image" src="https://user-images.githubusercontent.com/3944757/183925551-4c35c3d9-9a45-414e-bcc8-72e93e53ccb3.png">

This makes investigation significantly harder when dealing with 30 million jobs per day.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3944757/183926034-4227183d-69ab-4193-a02c-add6e5f52c94.png">

Is there a way on heroku to either get the full process name? e.g. `app[sidekiq.1:58]` or in Sidekiq to specify that each process worker should have a different name?

**Comment by mperham** [comment]
`58` is the PID so you should be able to `| grep pid=58` the logfile.

**Comment by jchatel** [comment]
`pid` is not on every line so that doesn't solve the problem.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/3944757/183947956-99f60586-b4b7-490a-978d-95d26934c2e3.png">

**Comment by mperham** [comment]
The stuff in green comes from Heroku, Sidekiq does not control it. The Sidekiq logger does put pid=XX in every line but it sounds like your Rails logger or `puts` does not, you'd need to adjust them.

https://github.com/mperham/sidekiq/blob/7003aeb6336d3fdaed27f7444998a5891aef8f1b/lib/sidekiq/logger.rb#L135
