### ISSUE TITLE
Proposal to improve `WorkSet#each` method

### ISSUE THREAD

**Issue by leandro** [mperham/sidekiq#5472]
**Sidekiq / Pro / Enterprise version(s)**: Sidekiq 6.5.1 (but also related to latest version -- 7)

It has come to my attention that it seems like [current implementation of WorkSet#each](https://github.com/mperham/sidekiq/blob/7-0/lib/sidekiq/api.rb#L1048-L1069) can be improved. I have an idea to improve it but I'd like to understand first the reasons behind the current approach has been used in there.

The amount of `pipelined` calls to redis will depend on the amount of Sidekiq processes running. With that, if `Sidekiq::WorkSet.new.any? { ... }` is called very frequently (which is my case -- because I'm using it to prevent jobs duplication to be run), reducing the amount of such `pipelined` calls could reduce significantly the load on Redis (which we've been facing lately on the company I work for). And I know that preventing duplicated jobs from running at same time is an included feature in Sidekiq Enterprise (we already use Sidekiq Pro and we might get to use Enterprise version quite soon), but my real question about this context is: why is that logic really bothering in filtering out inexistent workers with that `exists?` call on line 1054 while it could simply call all the `pipeline.hgetall("#{key}:work")` for all the processes at once in a single `pipelined` call to redis and just skip the returned empty hashes? Would such approach impact too much performance or anything? If not, I could send a PR to change that.

**Comment by mperham** [comment]
I don't recall any reason why your idea wouldn't work. A PR would be awesome, please include a benchmark for 1000 processes before/after so we can verify the performance improvement at a large scale.

**Comment by mperham** [comment]
> I'm using it to prevent jobs duplication to be run

This is not a good idea. Work is only updated every N seconds so you'll get dupes anyways.

**Comment by leandro** [comment]
> > I'm using it to prevent jobs duplication to be run
> 
> This is not a good idea. Work is only updated every N seconds so you'll get dupes anyways.

That's good to know. Thanks for pointing it out. I wasn't aware of that. Could you point out the piece of code where that is being done? I mean, the "every N seconds" updates...And still, after I applied the solution I mentioned, the duplicated jobs occurrence dropped immensely (by more than 95%-98%), so it worked almost perfectly and that's why I'd like to see where that happens in the Sidekiq's source code.

**Comment by mperham** [comment]
It's part of the heartbeat:

https://github.com/mperham/sidekiq/blob/a2708ea849aabdb7f62129a07ba752225c621e89/lib/sidekiq/launcher.rb#L150-L158

**Comment by fatkodima** [comment]
I made some investigation on the performance improvements.

## Benchmark script
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "sidekiq", github: "mperham/sidekiq", branch: "main"
  gem "toxiproxy"
  gem "memory_profiler"
end

require "sidekiq/api"

class NewWorkSet
  include Enumerable

  def each(&block)
    results = []
    Sidekiq.redis do |conn|
      procs = conn.sscan_each("processes").to_a

      all_workers = conn.pipelined do |pipeline|
        procs.sort.each do |key|
          pipeline.hgetall("#{key}:work")
        end
      end

      procs.zip(all_workers).each do |key, workers|
        workers.each_pair do |tid, json|
          next if json.empty?

          hsh = Sidekiq.load_json(json)
          p = hsh["payload"]
          # avoid breaking API, this is a side effect of the JSON optimization in #4316
          hsh["payload"] = Sidekiq.load_json(p) if p.is_a?(String)
          results << [key, tid, hsh]
        end
      end
    end

    results.sort_by { |(_, _, hsh)| hsh["run_at"] }.each(&block)
  end
end

Sidekiq.configure_client do |config|
  config.redis = {db: 13, port: 6380}
end

Toxiproxy.populate([{
  name: "redis",
  listen: "127.0.0.1:6380",
  upstream: "127.0.0.1:6379"
}])

Sidekiq.redis { |c| c.flushdb }

PROCESS_COUNT = 1000
WORKERS_PER_PROCESS = 10
LATENCY = 3
MEASURE_MEMORY = false

Sidekiq.redis do |conn|
  conn.pipelined do
    PROCESS_COUNT.times do |pi|
      process_name = "process-#{pi}"
      conn.sadd("processes", process_name)
      conn.set(process_name, "exists")

      WORKERS_PER_PROCESS.times do |wi|
        conn.hset("#{process_name}:work", wi,
          Sidekiq.dump_json({"payload" => {}, "run_at" => (Time.now - rand(10))})
        )
      end
    end
  end
end

def with_latency(latency, &block)
  puts "Simulating #{latency}ms of latency between Sidekiq and redis"
  if latency > 0
    Toxiproxy[:redis].downstream(:latency, latency: latency).apply(&block)
  else
    yield
  end
end

def timed
  start = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  yield
  elapsed = Process.clock_gettime(Process::CLOCK_MONOTONIC) - start
  puts "Elapsed: #{elapsed}s"
end

def measuring_memory(name)
  if MEASURE_MEMORY
    report = MemoryProfiler.report do
      yield
    end
    report.pretty_print(scale_bytes: true, to_file: "tmp/#{name}_memory_profiler.txt")
  else
    yield
  end
end

with_latency(LATENCY) do
  timed do
    puts "==== Old ===="
    works = Sidekiq::WorkSet.new

    measuring_memory("old") do
      works.to_a.size
    end
  end
end

with_latency(LATENCY) do
  timed do
    puts "==== New ===="
    works = NewWorkSet.new

    measuring_memory("new") do
      works.to_a.size
    end
  end
end
```

| Processes count      | Latency | Time (old) / Time (new) | Memory (old) / Memory(new) |
| ----------- | ----------- |---|---|
| 100 | 1ms | 0.23s / 0.08s | 8mb / 54mb | 
| 100 | 3ms | 0.54s / 0.12s | 8mb / 54mb | 
| 300 | 1ms | 0.72s / 0.32s | 24mb / 162mb | 
| 300 | 3ms | 1.6s / 0.4s | 24mb / 162mb | 
| 1000 | 1ms | 2.3s / 0.82s | 80mb / 540mb | 
| 1000 | 3ms | 5.5s / 1s | 80mb / 540mb | 

So sometimes we see 4/5x speed improvements, but the memory is linearly skyrocketing because of the large pipelined request/response. But yes, we have O(1) number of redis requests instead of O(N).

@mperham, so what do you think about this?

**Comment by mperham** [comment]
I think that's a worthwhile change. The memory increase is painful but I don't see any obvious improvements without a larger, possibly painful, refactoring.
