### ISSUE TITLE
Unable to upgrade Sidekiq to 6.5.x

### ISSUE THREAD

**Issue by imhamzaimran** [mperham/sidekiq#5481]
Hello, I'm trying to update my application sidekiq version from 5.2.9 to 6.5.x. However I was able to successfully upgrade it to 6.4.x, but when I try to upgrade to 6.5.x. I am getting these errors. Please the full back trace below.
![Screenshot from 2022-08-19 11-37-45](https://user-images.githubusercontent.com/40744095/185558995-14637a0c-140f-4804-924a-4245e5eb7e76.png)
![Screenshot from 2022-08-19 11-37-53](https://user-images.githubusercontent.com/40744095/185559009-9b0d9e5d-cc5f-46c9-9dac-5fd218614e60.png)
.

**Comment by davidwessman** [comment]
Seems to be related to `sidekiq-throttled`.

https://github.com/sensortower/sidekiq-throttled/issues/120

Have you upgraded that to latest version?

**Comment by imhamzaimran** [comment]
Yes I did. Then I get Uninitialized Constant Sidekiq::Component(NameError) error.

**Comment by imhamzaimran** [comment]
![image](https://user-images.githubusercontent.com/40744095/185560704-3c0ef92a-d76d-46a1-8996-9b8d9fb1af10.jpeg)Yes I did. Then I get Uninitialized Constant Sidekiq::Component(NameError) error.

**Comment by mperham** [comment]
That's a bug in 6.5.4 that is fixed on main. You can try 6.5.1.

**Comment by davidwessman** [comment]
@imhamzaimran 6.5.5 has been released, does it help?

**Comment by imhamzaimran** [comment]
Yes, it did. Thanks.

**Comment by davidwessman** [comment]
@imhamzaimran Please close the issue! 🙂
