### ISSUE TITLE
redis-rb 4.8.0 deprecations

### ISSUE THREAD

**Issue by pbhogan** [mperham/sidekiq#5484]
Sidekiq 6.5.4 + redis-rb 4.8.0 hits a few deprecations in redis-rb ([https://github.com/redis/redis-rb/blob/4.x/CHANGELOG.md#480](https://github.com/redis/redis-rb/blob/4.x/CHANGELOG.md#480))

The usages in Sidekiq that spewed warnings immediately were:

- https://github.com/mperham/sidekiq/blob/3f963816202940f36809561aef8e22f0cc1aea22/lib/sidekiq/fetch.rb#L31
- https://github.com/mperham/sidekiq/blob/3f963816202940f36809561aef8e22f0cc1aea22/lib/sidekiq/fetch.rb#L50

Changing to `<< "timeout:#{TIMEOUT}"` seems to address those.

- https://github.com/mperham/sidekiq/blob/3f963816202940f36809561aef8e22f0cc1aea22/lib/sidekiq/launcher.rb#L104

Changing to `.sadd("processes", [key])` seems to be the fix here? Could use `.sadd?` but that would require Redis 4.8.0

There could be more instances in Sidekiq, but these were the ones that clogged my logs right off the bat. ¯\_(ツ)_/¯

**Comment by mperham** [comment]
Sigh, I literally just released 6.5.5 an hour ago.

**Comment by wrburgess** [comment]
I believe the logging behavior below is related to this closed issue, so wanted to first post here:

## Updated Versions 
```
heroku stack heroku-22
ruby "3.1.2"
gem "rails", "7.0.3.1"
gem "sidekiq", "6.5.5"
gem "redis", "4.8.0"
```

## Logs After Deploy

``` 
Aug 23 12:29:13 [app](https://my.papertrailapp.com/xxx) [app/worker.1](https://my.papertrailapp.com/xxx)

redis.brpop("queue:default", "queue:mailers", "queue:searchkick", timeout: 2)(called from: /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')

Aug 23 12:29:13 [app](https://my.papertrailapp.com/xxx) [heroku/release.3793](https://my.papertrailapp.com/xxx)

Process exited with status 0

Aug 23 12:29:13 [app](https://my.papertrailapp.com/xxx) [heroku/release.3793](https://my.papertrailapp.com/xxx)

State changed from up to complete

Aug 23 12:29:13 [app](https://my.papertrailapp.com/xxx) [heroku/release.3793](https://my.papertrailapp.com/xxx)

Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument:

Aug 23 12:29:13 [app](https://my.papertrailapp.com/xxx) [heroku/release.3793](https://my.papertrailapp.com/xxx)

redis.brpop("queue:default", "queue:mailers", "queue:searchkick", timeout: 2)(called from: /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/fetch.rb:49:in `block in retrieve_work')
```

## Reversal Versions and Heroku Dynos Reboot

```
heroku stack heroku-22
ruby "3.1.2"
gem "rails", "7.0.3.1"
gem "sidekiq", "6.5.5"
gem "redis", "4.7.1"
```

_No errors_

**Comment by sander-deryckere** [comment]
When is the new release planned?

Just to know if we need to work of master now, or if we can wait a day or two for a new release.

Thanks
