### ISSUE TITLE
Specific errors cause ThreadError in Sidekiq::Component#safe_thread

### ISSUE THREAD

**Issue by ts-3156** [mperham/sidekiq#5492]
Hi,

When specific errors occur in an application code, the application may not be able to do `Thread.new` in subsequent code. And, when those errors are unhandled in a worker class, a ThreadError happens in sidekiq::Component#safe_thread. Eventually, the number of threads displayed on the Sidekiq dashboard will not match the actual number of active threads.

I suggest that Sidekiq has a function to detect this state and re-create an instance of Sidekiq::Processor. Or, since I think Sidekiq is not the root problem, I suggest that simply mentioning ThreadError on [Problems and Troubleshooting](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting).

----

#### Errors causing this problem:

```ruby
AccessLog.create!(attrs)
# => #<ActiveRecord::StatementInvalid: Mysql2::Error: This connection is still waiting for a result, try again once you have the result>

Zlib::Deflate.deflate(data.to_json)
# => #<Zlib::DataError: data error>
```

#### Affected area:

A thread. Once a thread reaches this state, `Thread.new` will continue to fail in the thread, but other threads can execute `Thread.new` as usual.

If I catch those errors in a worker class, the thread keeps running broken. For example, if I catch ActiveRecord::StatementInvalid, Model#save! will fail to save without raising an exception from then on.

If I don't catch those errors in a worker class, a ThreadError is raised in Sidekiq::Component#safe_thread and an instance of Sidekiq::Processor that has the thread keeps running broken.

#### How to detect this state:

`Thread.current.status == 'aborting'` and `Thread.main.status == 'dead'`.

```ruby
# https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/component.rb#L14-L19
def safe_thread(name, &block)
  ...
rescue => e
  if e.class == ThreadError
    logger.warn "name=#{name} current=#{Thread.current} main=#{Thread.main} exception=#{e.inspect}"
    # => name=processor current=#<Thread:0x00005647343e4c80@processor [path]/lib/sidekiq/component.rb:15 aborting> main=#<Thread:0x000056472d126e00 dead> exception=#<ThreadError: can't alloc thread>
  end
  raise
end

```

Ruby version:
2.7.2p137

Rails version:
6.1.4.1

Sidekiq / Pro / Enterprise version(s):
6.4.2

**Comment by mperham** [comment]
Do you have any code which reproduces the problem?

**Comment by ts-3156** [comment]
#### ActiveRecord::StatementInvalid

This is the actual code to reproduce the ActiveRecord::StatementInvalid described above.

```ruby
class CreateSearchLogWorker
  include Sidekiq::Worker
  prepend LoggingWrapper
  sidekiq_options queue: 'logging', retry: 0, backtrace: false

  def perform(attrs)
    SearchLog.create!(attrs)
  end
end

module LoggingWrapper
  def perform(*args)
    super
  rescue ActiveRecord::StatementInvalid => e
    raise StatementInvalid.new(e.inspect)
  rescue => e
    Airbag.exception e, args: args
  end

  class StatementInvalid < StandardError
  end
end
```

As a side note that the SearchLog model does not have any unique key or reference key on the database. There are four Sidekiq processes on an EC2 instance. For each process, the Sidekiq concurrency is 5 and database pool size is 120. The MySQL process is running in a separate RDS instance. On the Sidekiq server, CPU utilization is less than 20% and memory utilization is less than 50%. On the MySQL server, CPU utilization is less than 20% and memory utilization is approximately 80%.

I am sorry, but I have never been able to reproduce this error in my development environment for years, even though I know the specific code so well. Perhaps a combination of network conditions and multi-threaded conditions causes this error.

#### Zlib::DataError

This is the actual code to reproduce the Zlib::DataError described above.

```
Base64.encode64(Zlib::Deflate.deflate(data.to_json))
```

I have not yet identified the specific data when this error occurs. My guess is that since this data contains Twitter user profiles and tweets, a special byte sequence causes this error.

**Comment by ts-3156** [comment]
This error occurs once every few days at most, but I have taken steps to prevent it and have not experienced much inconvenience.

Please point out any data needed for future debugging. I will collect that little by little.

**Comment by mperham** [comment]
Ok, no reproduction yet.

Both of these load native libraries (libz and libmysql) but I don't see any other commonalities. Both exceptions are StandardErrors and should be rescued by Sidekiq's job retry logic.

Reading your report further, it looks like Thread.current is aborting but Thread.main is dead!?!? Thread.main should never be dead, maybe that's why MRI won't create any more Threads.

**Comment by ts-3156** [comment]
Yes, the status of Thread.main is dead. This is why I think Sidekiq is not the root problem.

Despite the fact that Thread.main is dead, the Sidekiq process and the invalid thread continue to run. I sometimes see bug reports of "data disappearing when using Sidekiq" and I think one of the causes of the reports may be the issue I' reporting here.

I think that you will not be able to fix this problem without reproduction at your environment. Please feel free to close this issue if you can do nothing with it. I hope that someone else who has encountered the same problem will write additional information in the future.
