### ISSUE TITLE
Metrics uses Redis bitfield, not set successfully through redis-namespace

### ISSUE THREAD

**Issue by bf4** [mperham/sidekiq#5502]
Ruby version: 3.0.3 mri
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): 6.5.6 / 5.5.2 / na

Issue:

Seems bitfield isn't compatible with redis-namespace https://github.com/resque/redis-namespace/tree/v1.9 at this time

> undefined method `bitfield' for #<Redis::Namespace:0x00007f1ee23f2cf0>

per https://github.com/mperham/sidekiq/blob/v6.5.6/lib/sidekiq/metrics/shared.rb#L72-L75

**Comment by mperham** [comment]
Metrics is in beta until Sidekiq 7.0 which also removes support for redis-namespace.

**Comment by bf4** [comment]
💯

**Comment by Vasfed** [comment]
A quick and dirty solution to make redis-namespace work (put this in an initializer):
```ruby
require 'redis/namespace'
class Redis
  class Namespace
    Redis::Namespace::NAMESPACED_COMMANDS["bitfield"] ||= %i[first]
    Redis::Namespace::COMMANDS["bitfield"] ||= %i[first]

    def bitfield(*args, &block)
      call_with_namespace('bitfield', *args, &block)
    end
    ruby2_keywords(:bitfield) if respond_to?(:ruby2_keywords, true)
  end
end
```
