### ISSUE TITLE
Sidekiq 6.4.2 - 'Busy' screen doesn't show available workers or running jobs (eventhough jobs are processed)

### ISSUE THREAD

**Issue by svgr-slth** [mperham/sidekiq#5504]
Hello there, 

I upgraded my app to Rails 6 and the Redis gem has been updated to version 5.0.1in the process.
Since that update it seems that none of my available workers, running jobs, or stats (RSS and such) are listed on the 'Busy' tab (see screenshot)

![sk issue](https://user-images.githubusercontent.com/92316565/187910006-d32edb72-000e-4301-8a36-fd792e0f0916.png)

Nevertheless it seems that workers are doing their job and are properly processing everything. Also, I see anything else properly on other tabs (Queued jobs, Failures, etc..)

I have managed to fix the issue by manually adding Redis to my gemfile, and limiting its version to 4.8.0, but i would love to let Sidekiq handle its dependencies on its own without me having to tweak the Redis version manually. 

Here is a small extract of the Gemfile.lock if that can be of any help:

```
    redis (5.0.1)
      redis-client (~> 0.7)
    redis-client (0.7.1)
      connection_pool
    sidekiq (6.4.2)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
```

If anybody has a clue about what is happening i would greatly appreciate an input!

**Comment by mperham** [comment]
Latest version 6.5.6 locks redis to <5.0.

**Comment by mperham** [comment]
Update Sidekiq.
