### ISSUE TITLE
Latency is based job original enqueue time, even if re-enqueued due to TERM

### ISSUE THREAD

**Issue by JasonBarnabe** [mperham/sidekiq#5506]
Ruby version: 2.6.7
Rails version: 6.1.6
Sidekiq / Pro / Enterprise version(s): 6.4.2

We have alarms set up based on the latency reported for each queue in sidekiq (read like so: `Sidekiq::Queue.all.map{|q| [q.name, q.latency] }`). We also have some long-running jobs - I know this is not recommended but these are "cleanup" type jobs and can be stopped and restarted without issue.

When we need to restart sidekiq (e.g. during a deploy) and there is a long-running job running, often we need to kill it with a [TERM signal](https://github.com/mperham/sidekiq/wiki/Signals#term).

>  Any workers that do not finish within the timeout are forcefully terminated and their messages are pushed back to Redis to be executed again when Sidekiq starts up.

The problem is that when this happens, it looks like the latency is calculated based on the original time the job was enqueued: if the job was running for 10 minutes before the TERM, now the latency is reported as 10 minutes until the job is picked up again. I would expect that when a job is re-enqueued due to TERM, its latency is calculated based on when it was re-enqueued, not the time it was originally enqueued.

To reproduce:

```
class SlowJob < ApplicationJob
  queue_as :high

  def perform
    sleep 3600
  end
end
```
From console:

```
SlowJob.perform_later
sleep 5
Sidekiq::Queue.all.find{|q| q.name == 'high'}.latency
=> 0
```
(latency is 0 while it runs).

Wait a couple minutes, then kill the process:
```
kill -TERM 123456
```

Once the process stops, check the latency

```
Sidekiq::Queue.all.find{|q| q.name == 'high'}.latency
=> 162.64900541305542
```
This is the time since I originally enqueued it, not the time since it got placed back in the queue due to TERM. You can start sidekiq again, and when the job begins processing, the latency goes back to 0, but if you TERM it again, the latency stat continues to grow based on the original enqueue time.

**Comment by mperham** [comment]
Yep, this is a limitation. Your alerts should only trigger if multiple jobs over a few seconds are over the latency threshold.

**Comment by mperham** [comment]
doesn't exist. requires an O(N) linear scan and parsing of every single item.

**Comment by mperham** [comment]
You could implement a heuristic like minimum of the latencies of the first N jobs.

**Comment by JasonBarnabe** [comment]
In case anyone else has this problem, we solved by implementing a new latency method that took the minimum latency of the first 10 jobs in the queue.
```
module Sidekiq::TopNLatency
  # Same as Sidekiq::Queue#latency, but adjusted to take the minimum of the top N instead of top 1.
  def top_n_latency(count=10)
    entries = Sidekiq.redis { |conn|
      conn.lrange(@rname, count * -1, -1)
    }
    return 0 unless entries.any?
    latest_enqueued_at = entries.filter_map do |entry|
      job = Sidekiq.load_json(entry)
      job['enqueued_at']
    end.max
    return 0 unless latest_enqueued_at
    Time.now.to_f - latest_enqueued_at
  end
end
Sidekiq::Queue.prepend Sidekiq::TopNLatency
```

**Comment by gstokkink** [comment]
Hi @JasonBarnabe, I'm wondering of this is still an issue with recent versionsof Sidekiq Pro? I cannot reproduce your test case anymore, the latency of the queue remains 0 after terminating the Sidekiq process. Perhaps @mperham had fixed it despite calling it a limitation earlier?

**Comment by mperham** [comment]
This can be an issue with long running jobs. Sidekiq 7.3 will introduce a new API to create interruptible jobs which can run long safely, based on the existing functionality in the sidekiq-iteration gem. See the new Iteration wiki page if curious.

**Comment by gstokkink** [comment]
But the test case seems to indicate that `enqueued_at` is now properly reset when re-enqueuing an orphaned job? In what cases is the latency inaccurate for forcefully terminated long-running jobs then?

**Comment by mperham** [comment]
What test case?

**Comment by gstokkink** [comment]
The one in the opening post 🙂 Starting a long running job, then killing the process, no longer results in an ever-increasing queue latency it seems. At least, I could not reproduce it locally using Sidekiq Pro 7.2.1.

**Comment by mperham** [comment]
Yeah, that’s why I said “can be”. I’m glad it’s working for you.

**Comment by gstokkink** [comment]
Yeah, still, we’re going to work on our long running jobs and try and replace them with batched jobs.

Any idea when 7.3 will be released? Maybe it's worth waiting for. Iterations look like a better solution than batches at first glance. Is there a beta branch perhaps?

**Comment by mperham** [comment]
https://github.com/sidekiq/sidekiq/milestone/8

You can use sidekiq-iteration today too.

**Comment by gstokkink** [comment]
Good point 👍🏻 Thanks for your hard work!
