### ISSUE TITLE
Running SIDEKIQ_PRELOAD_APP=1 bundle exec sidekiqswarm -e staging resolve in an error

### ISSUE THREAD

**Issue by yossiedri** [mperham/sidekiq#5511]
SIDEKIQ_PRELOAD_APP=1 bundle exec sidekiqswarm -e staging
looks like  -e staging is not working

[swarm] Preloading Bundler groups ["default"]
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:53: warning: constant ::UploadIO is deprecated
/var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:59: warning: constant ::UploadIO is deprecated
/var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:61: warning: constant ::Parts is deprecated
2022-09-06T13:03:19.453Z pid=14196 tid=afnio INFO: Booting Sidekiq 6.5.1 with Sidekiq::RedisConnection::RedisAdapter options {}
[swarm] Preloading application
/var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_symbol_connection': 'development' database is not configured. Available: ["staging", "portal-prod"] (ActiveRecord::AdapterNotSpecified)
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:241:in `resolve_connection'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:143:in `resolve'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/connection_handling.rb:57:in `establish_connection'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.7.1/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `run'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /var/www/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/railties-5.2.7.1/lib/rails/application.rb:361:in `initialize!'
	from /var/www/html/redmine/releases/20220906112702/config/environment.rb:16:in `<top (required)>'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `block in require'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/sidekiq-6.5.1/lib/sidekiq/cli.rb:274:in `boot_application'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/sidekiq-ent-2.5.1/lib/sidekiq-ent/swarm.rb:68:in `start'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/sidekiq-ent-2.5.1/lib/sidekiq-ent/swarm.rb:90:in `start_and_monitor'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/gems/sidekiq-ent-2.5.1/bin/sidekiqswarm:49:in `<top (required)>'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/bin/sidekiqswarm:23:in `load'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/bin/sidekiqswarm:23:in `<main>'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `eval'
	from /var/www/html/redmine/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `<main>'

Gemfile:

source "https://enterprise.contribsys.com/" do
  gem 'sidekiq-ent'
end
Ruby version: ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-darwin20]
Rails version: Rails 5.2.7.1
Sidekiq / Pro / Enterprise version(s):
Using sidekiq 6.4.2
Using sidekiq-pro 5.3.1
Using sidekiq-ent 2.3.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
initializer:

require 'rake'
require 'sidekiq/web'
# require 'sidekiq/ent'
# require 'sidekiq/pro/expiry'

if Rake::Task.tasks.empty?
	Rails.app_class.load_tasks 
end
Sidekiq::Enterprise.unique! unless Rails.env.test?
 
puts "SIDEKIQ::REDIS_CONFIG: #{REDIS_CONFIG}"
$redis = Redis.new(REDIS_CONFIG) unless defined?($redis)

redis_conn = proc {
	$redis 
}

Sidekiq.configure_client do |config|
	config.redis = ConnectionPool.new(size: 5, &redis_conn)
end

Sidekiq.configure_server do |config|
	config.redis = ConnectionPool.new(size: 25, &redis_conn)
	config.periodic do |mgr|
		mgr.register('0 1 * * *', 'FixIssueRootAndTreeWorker')
		mgr.register('1 0 * * *', 'CheckFaildAttachments')
		mgr.register('0 1 * * *', 'SprintCompletionStats')
		mgr.register('43 4 * * *', 'SyncTestCases')
		mgr.register('2 3 * * *', 'SwMspSyncAll')
		mgr.register('0,10,20,30,40,50 * * * *','RetryFailedNvbugUpdates')
		mgr.register('32 3 * * *', 'SyncPls')
		mgr.register('32 3 * * *', 'SyncAllAgileChanges')
		mgr.register('42 3 * * *', 'SyncUserDeps')
		mgr.register('20 2 1,8,15,22 * *', 'RightLeftCheckByEqualEstimatedField')
		mgr.register('58 23 * * *', 'LdapRevokedUsersReports')
		mgr.register('0,30 * * * *', 'SyncAllLdapRevokedUsers')
		mgr.register('0 4 * * *', 'SyncAllNVLdapGroups')
		mgr.register('0 4 * * *', 'PopulateProjects')
		mgr.register('* 2 * * *', 'SetPointerIssues')
		mgr.register('* 22 * * *', 'SetPointerIssuesNight')
		mgr.register('30 4 * * *', 'DeliverQuery')
		mgr.register('14 4 * * *', 'BuildFromTables')
		mgr.register('0,5,10,15,20,25,30,35,40,45,50,55 * * * *', 'SyncAll')
		mgr.register('0 1 * * *', 'PopulateSfProjects')
		mgr.register('15 1 * * *', 'PopulateProjectCategories')
		mgr.register('58 23 * * *', 'UpdateDw')
		mgr.register('0,30 * * * *', 'UpdateDwCheckTime')
		mgr.register('0,15,30,45 * * * *', 'FetchChangesets')
		mgr.register('0 6 * * *', 'CreateFrSalesforceData')
		mgr.register('0 1 * * *', 'AddHistoryDwhIssueIds')
		mgr.register('0 4 * * *', 'CloseVersions')
		mgr.register('* * * * *', 'FixLftRgt')
		mgr.register('0 * * * *', 'ScrumTypeFix')
		mgr.register('30 3 * * *', 'GitUp')
		mgr.register('55 2 * * *', 'HgUp')
		mgr.register('14 2 * * *', 'ClearCronLogs')
		mgr.register('*/2 * * * *', 'CheckIssuePositionAndSprintInconsistency')
		mgr.register('* * * * *', 'UpdateActiveProjectPath')
	end
end

Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
sidekiq.yml:
:logfile: 'log/sidekiq.log'
:pidfile: 'tmp/pids/sidekiq.pid'
:dynamic: true
:enabled: true

:queues:

[default,1]
[mailer,2]
[nvbug,3]
[analytics, 3]
[fast_issue,4]
[journal_worker,5]
[often, 6]
[update_dwh,7]
[create_dwh,8]
[sync_project_issues,9]
[send_by_mail,10]
development:
:concurrency: 1
:timeout: 10000
:verbose: false
:queues:
- [default,1]
- [mailer,2]
- [nvbug,3]
- [development_analytics, 3]
- [development_fast_issue, 4]
- [development_journal_worker,5]
- [development_often, 6]
- [development_update_dwh,7]
- [development_create_dwh,8]
- [development_sync_project_issues,9]
- [development_send_by_mail,10]

**Comment by mperham** [comment]
Could you please format your content in the future? Wrap code in code fences, etc.

Did you try `RAILS_ENV=staging ...` instead of `-e staging`?

**Comment by yossiedri** [comment]
I did try RAILS_ENV=staging and it looks like it doesn't pick it up

**Comment by yossiedri** [comment]
can you please help here

**Comment by yossiedri** [comment]
Also here is my systemd service file:

[Unit]
Description=sidekiq for staging
After=syslog.target network.target

[Service]
Type=notify

WorkingDirectory=/var/www/html/redmine/current
ExecStart=/var/www/.rvm/bin/rvm ruby-2.6.9 do bundle exec sidekiqswarm -e staging
ExecReload=/bin/kill -TSTP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID
StandardOutput=append:/var/www/html/redmine/shared/log/sidekiq.log
StandardError=append:/var/www/html/redmine/shared/log/sidekiq.error.log
User=my_user
Group=my_user
UMask=0002

Environment=SIDEKIQ_PRELOAD_APP=1
Environment=MALLOC_ARENA_MAX=2

RestartSec=1
Restart=always

SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target
