### ISSUE TITLE
WebUI - sorry something went wrong

### ISSUE THREAD

**Issue by bkd** [mperham/sidekiq#5517]
From time to time I have experienced the WebUI producing the "We're sorry, but something went wrong.
If you are the application owner check the logs for more information" message. No idea why and impossible to trace or find out where the issue is coming from. How can I find out where this is coming from?

**Comment by mperham** [comment]
check the logs? talk to the person who owns the app in your organization and ask them for advice?

**Comment by bkd** [comment]
Unfortunately not a single thing in the logs, full debug mode for logs and
still not a clue. Using Rails.cache.clear - I can get it working again so
seems to be something funky going on

**Comment by mperham** [comment]
Well, what’s in the logs?

**Comment by bkd** [comment]
Sorry been extremely busy with the "other job" - nothing at all. I cant find anything at all in the logs. I've turned the logs to :debug, tried to dig into an unpacked copy of the gem also to track - and still yet to find a clue. Rails.cache.clear - works sometimes, not every time - I am guessing the data in the queue could be an issue but I can't track it down what has caused the issue ;-(. I've gone as far as using begin / rescue trying to see anywhere in the gem that can lead to a problem but nada. Not a thing...I'm probably missing something obvious.  Also totally cleared the queues so they are all empty and still the error prevails. Re compiled assets, checked nginx logs and not a dickybird.

**Comment by bkd** [comment]
I managed to run it as a standalone app through config.ru along side the rails app then used nginx to secure it for now. Its working again.
