### ISSUE TITLE
Inconsistent error where saved model values is not found with `.find` within the job

### ISSUE THREAD

**Issue by TTD93** [mperham/sidekiq#5522]
So I have a model where I add some values right before I start the mailer job, however it's very inconsistent if the value is set or not with `.find` within the mailer. I first thought it was some race condition but when I check the log, this is the only place where the record is found. 

Ruby version: 2.6.7
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): 6.5.6

Sidekiq.yml
concurrency: 5
queues:
  - default
  - mailers

```
def send_user_mailers(users)
  users.each do |req|
    req = set_some_random_values(req)
    ModelMailer.mail_to_user(req.id).deliver_later
  end
end

def set_some_random_values(req)
  req.update!(some_column_value: 3, some_column_value_2: 2)
  logger.info 'so this happened'
  req
end

def 

class ModelMailer < ApplicationMailer
  def mail_to_user(user_id)
    user = User.find(user_id)
    # user.some_column_value is sometimes null
  end
end
```

**Comment by davidwessman** [comment]
Is `send_user_mailers` called within a database transaction?
That usually causes errors like this:
1. Open transaction
2. Save record within transaction
2. Schedule job
3. Sidekiq picks up job, cannot find id
4. Transaction closes, writes to database

**Comment by TTD93** [comment]
Yeah, tried to check for that as well but unfortunately it is not.

**Comment by mperham** [comment]
I'm sure it's a transactional issue. Try enabling the new transaction-aware client extension in Sidekiq 6.5. https://github.com/mperham/sidekiq/blob/main/Changes.md#650

**Comment by TTD93** [comment]
Yup, you were both correct! Thanks for the help!
