### ISSUE TITLE
transactional_push is ignored by ActiveJob

### ISSUE THREAD

**Issue by jdelStrother** [mperham/sidekiq#5526]
Just wanted to note a potential caveat with transactional_push. I noticed that things like `UserMailer.creation_message(self).deliver_later` were being run by sidekiq instantly, rather than getting deferred until the transaction completes.

On looking into it, ActiveJob is hardcoding `Sidekiq::Client` - I think it probably needs to be something like `JobWrapper.build_client` in order to get the transaction-aware client.

It's not clear to me if [build_client](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/worker.rb#L363) is considered public api, though - is that the best entry point?

Ruby version: 3.1
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 6.5.6 / 5.5.2 / 2.5.1

**Comment by jdelStrother** [comment]
(And thinking about it further, I wonder why they call Client.push directly, instead of something like 
```ruby
      def enqueue(job) # :nodoc:
        # Sidekiq::Client does not support symbols as keys
        job.provider_job_id = JobWrapper.perform_async({
          "wrapped" => job.class,
          "queue"   => job.queue_name,
          "args"    => [ job.serialize ]
         })
      end
```
)

**Comment by mperham** [comment]
Right, I can't guarantee every Sidekiq feature will work with ActiveJob as I don't control ActiveJob. That said, your build_client suggestion is a good one but it's not technically a public API meant to be used by other libraries. It would be better to use `client_push`.

**Comment by jdelStrother** [comment]
@mperham if you have chance I'd appreciate any extra eyes on https://github.com/rails/rails/pull/46080 to check I'm not missing anything stupid.

**Comment by nateberkopec** [comment]
Thanks for fixing that @jdelStrother !

**Comment by palexvs** [comment]
I'm afraid this fix breaks https://github.com/sidekiq/sidekiq/wiki/Ent-Unique-Jobs#lock-context as in
in `lib/sidekiq-ent/unique.rb`
```
      def self.context_for(klass, job)
        if klass.respond_to?(:sidekiq_unique_context)
```

`klass` becomes `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` not a real job class

**Comment by palexvs** [comment]
maybe a fix should be something like:
```
def self.context_for(_klass, job)
  klass = job["wrapped"] || job["class"]
....
```
