### ISSUE TITLE
Rolling restarts and super_fetch!.

### ISSUE THREAD

**Issue by kevinjcoleman** [mperham/sidekiq#5540]
We noticed while using Sidekiq Pro, that super_fetch is reliably picking up orphaned processes, but only on a subsequent deploy. Since we do a rolling restart, the processes running the new version have already started before the processes running the old version are killed and therefore `super_fetch!` isn't rescuing those jobs.

For example:
We have Host A running version 1, start Host B with Version 2 and then kill Host A. Host B doesn't check for the orphaned jobs from Host A because it was killed after Host B had already started. We don't see super_fetch pickup those jobs until another deploy goes out, or a host goes down and has to be restarted.

Is there a way to force `super_fetch!` to run once an hour or something like that to ensure we aren't waiting until the next deploy to rescue these jobs?

**Comment by kevinjcoleman** [comment]
Would there be any concern to doing this in a periodic job that runs every half an hour? Since `check` already checks if super_fetch has been run recently it shouldn't put too large a load on redis.

```
def perform
  require "sidekiq/pro/super_fetch"                          
  Sidekiq::Pro::SuperFetch.new(Sidekiq).check
end
```

**Comment by mperham** [comment]
With rolling restarts, the old processes A should be given a long period of time to finish their jobs and wind down. That's why A and B are running at the same time. Why are they being killed?

Fix the deploy so it is not orphaning jobs, that's what I'd recommend.

**Comment by kevinjcoleman** [comment]
Unfortunately we're using a 3rd party, Aptible, so we don't have a ton of control over how it kills the processes during the rollout but I'll take a look and see if we can change that.
