### ISSUE TITLE
Sidekiq Ent Unique Job Key

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5544]
Ruby version: 2.7.6p219
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): 6.4.2 / 5.3.0 / 2.3.0

Hey there again!

What about allowing to customize the definition of the unique lock key?

We have a job that must be unique for a period of time regardless of its arguments (which is a random key shared among a few different workers).

_I'm thinking of using the `Sidekiq::Limiter.concurrent` to work around the limitation or storing this random key somewhere else and retrieving it but it doesn't seem the right way to go._

**Comment by sobrinho** [comment]
For example:

```ruby
class MyJob
  sidekiq_options(
    unique_for: 12.hours,
    unique_key: -> (klass, args) { [klass, args[0]].join('|') }
  )

  def perform(arg_a, another_arg_which_i_dont_care_for_lock)
  end
end
```

**Comment by mperham** [comment]
This has been requested before but it's a very sharp config option, easy to forget if args change, etc so I've been reluctant to add it.

**Comment by mperham** [comment]
What do you think about an option to ignore the last argument only? That last argument could be a Hash of other options which aren't relevant for uniqueness. Enterprise's Encryption feature uses a similar idea for its "secret bag".

**Comment by sobrinho** [comment]
It would work for my case but might not be suitable for others.

This feature could be defined as Advanced with warnings about it perils, I don't know, and even be a bit more bureaucratic to be used (maybe even not documented, I don't know):

```ruby
class MyJob
  sidekiq_options(
    unique_for: 12.hours
  )

  def self. experimental_unique_key(klass, args)
    [klass, args[0]].join('|')
  end

  def perform(arg_a, another_arg_which_i_dont_care_for_lock)
  end
end

**Comment by benedikt** [comment]
I'd love to have a way to define a custom way of how the unique key is computed. In our case, we only pass in one an object (and event), but we'd like to specify uniqueness based on who triggered the event. 

So for us it would be something like `[klass, args[0]['user_id']]`.

It's definitely a sharp config option, but I'm close to monkey-patching Sidekiq internals (`Sidekiq::Enterprise::Unique.context_for`) which I'd rather not do 🙈

**Comment by mperham** [comment]
Correct. Today the only way to control which arguments are relevant to the lock is by monkeypatching `context_for`.

I will prototype a solution this week and see if I'm happy with it.

**Comment by benedikt** [comment]
@mperham Cool! I'd be happy to test it once you've got something that you like or help in any other way.

**Comment by mperham** [comment]
This API will be in the upcoming Enterprise 7.0.3 release.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#lock-context

**Comment by benedikt** [comment]
@mperham Thank you!

**Comment by sobrinho** [comment]
Thanks @mperham !

**Comment by sobrinho** [comment]
@mperham seems brittle to allow to mutate the args there.

Shouldn't we pass a deep frozen copy of the arguments or ignore if they are mutated to avoid silly mistakes in mutating those?

**Comment by mperham** [comment]
I think you're right. This code path happens during client middleware execution. The job hash has traditionally been mutable by client middleware but that doesn't mean it needs to be mutable within this method.

**Comment by mperham** [comment]
I'm `dup`ing now which only protects the Array itself, it does not prevent mutation of the contents. If the user passes a Hash as `args[0]`, they could still mutate the contents of the Hash.

Does Ruby have a deep_freeze method?

**Comment by sobrinho** [comment]
Not that I'm aware of. I heard about icenine I think once but doesn't worth to bring a 3rd dependency just for that, I would say.

Since we assume the args are JSON'able, we could be doing something slow like `JSON.parse(JSON.dump(args))` to ignore any mutations.

I think we even do that for something else, maybe we can reuse it?

**Comment by mperham** [comment]
> Since we assume the args are JSON'able, we could be doing something slow like `JSON.parse(JSON.dump(args))` to ignore any mutations.
> 
> I think we even do that for something else, maybe we can reuse it?

Ah right, we used to use `Marshal.load(Marshal.dump(args))`. Not a bad idea. I don't recall why it was removed.
