### ISSUE TITLE
Retry count not increased by manual retry

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [mperham/sidekiq#5548]
Ruby version: `MRI 2.7.6` 
Sinatra version: `2.2.2`
Sidekiq / Pro / Enterprise version(s): `Sidekiq 6.5.6 / Pro 5.5.2 / Ent 2.5.1`

The `retry_count`, of a failed job, is not increased, when the job is retried manually via the WebUI.
Is this the expected behaviour?
If so, can you please point me to the documentation?

**Comment by mperham** [comment]
It does not increase, correct. retry_count counts automatic retries. Any retries you trigger manually do not affect that automatic count. Otherwise triggering retries could cause the job to disappear.
