### ISSUE TITLE
Don't warn on volatile-lru and volatile-lfu for maxmemory_policy

### ISSUE THREAD

**Issue by mltsy** [mperham/sidekiq#5562]
Sidekiq::CLI spits out a warning when your Redis maxmemory_policy isn't `noeviction`
https://github.com/mperham/sidekiq/blob/ad9442f116086424948d60ec059755f9168a6bc8/lib/sidekiq/cli.rb#L80

However, isn't it true that `volatile-lru` and `volatile-lfu` should also be safe, since [according to the documentation](https://redis.io/docs/manual/eviction/) they only evict keys "with expire field set to true"?  I don't think sidekiq job keys have expirations set do they?  Is there actually a danger with these policies of losing important sidekiq data?

If not, Sidekiq should silence this warning for those policies as well.

**Comment by mperham** [comment]
Redis cannot evict Sidekiq’s data, period. Otherwise chaos ensues.

**Comment by mltsy** [comment]
Right - my point was I didn't think these policies would evict sidekiq data because sidekiq keys don't have the expire field set to "true".  Is that not correct?

**Comment by mperham** [comment]
They have the expire field set because they have an expiry. Volatile only works for caches.

**Comment by mltsy** [comment]
Ah!  Alright, thank you.  I guess we will have to change our redis config :)

Incidentally, is there any documentation on how long the expirations are, or how to configure them for a job?  (Or are expirations just used for the unique locks?)

**Comment by mperham** [comment]
Almost all Sidekiq data has an expiry. See wherever Sidekiq uses the EXPIRE command, eg

https://github.com/mperham/sidekiq/blob/a25a34c6d90ed92b6a537e15882c870731f46a5b/lib/sidekiq/launcher.rb#L119
