### ISSUE TITLE
Composable Rate Limit on Enterprise

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5580]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): N/A

Hi there again!

Chargebee has two rate limits at the same time: bucket and concurrent (see https://apidocs.chargebee.com/docs/api?prod_cat_ver=2#api_rate_limits).

I'm guessing the way to go is to do that:

```ruby
key = "chargebee-#{site}"
bucket = Sidekiq::Limiter.bucket(key, 150, :second, wait_timeout: 5)
concurrent_get = Sidekiq::Limiter.concurrent(key, 50, wait_timeout: 5, lock_timeout: 30)
concurrent_post = Sidekiq::Limiter.concurrent(key, 100, wait_timeout: 5, lock_timeout: 30) 

bucket.within_limit do
  concurrent_get.within_limit do
    # a get request
  end
end

bucket.within_limit do
  concurrent_post.within_limit do
    # a post request
  end
end
```

I'm not sure it will work as expected and also to avoid spreading this around, we are creating a helper like this:

```ruby
key = "chargebee-#{site}"
bucket = Sidekiq::Limiter.bucket(key, 150, :second, wait_timeout: 5)
concurrent_get = Sidekiq::Limiter.concurrent(key, 50, wait_timeout: 5, lock_timeout: 30)
concurrent_post = Sidekiq::Limiter.concurrent(key, 100, wait_timeout: 5, lock_timeout: 30) 

def within_get_limiter(&block)
  bucket.within_limit do
    concurrent_get.within_limit(&block)
  end
end

def within_post_limiter(&block)
  bucket.within_limit do
    concurrent_post.within_limit(&block)
  end
end
```

We could have a generic limiter that combines limiters like this:

```ruby
key = "chargebee-#{site}"
bucket = Sidekiq::Limiter.bucket(key, 150, :second, wait_timeout: 5)
concurrent_get = Sidekiq::Limiter.concurrent(key, 50, wait_timeout: 5, lock_timeout: 30)
my_limiter = Sidekiq::Limiter.composed(bucket, concurrent_get)

my_limiter.within do
  # ...
end
```

This is more a suggestion than an issue, so, feel free to close if you don't think this is generic enough to be supported by Sidekiq itself :)

**Comment by mperham** [comment]
The issue is that `within_limit` works like this:

```ruby
if less than limit
  increment limit
  yield
end
```

If you call `within_limit` twice, the inner limit might fail but the outer limit will have already incremented, meaning you "use" the limit without any benefit.

```ruby
if less than limitA
  increment limitA
    if less than limitB
      increment limitB
      yield
    end
end

**Comment by mperham** [comment]
So any composition will need to use Lua, perform both checks and increment only if both are ok. The limiter implementation is not written to be composable today.

**Comment by sobrinho** [comment]
Maybe we could do something like

```ruby
if less than limit
  increment limit
  yield
rescue another limiter error maybe?
  decrement limit
end

**Comment by mperham** [comment]
I think that's a hack, an approach I'd regret if I decided to build and support it long-term. Users will want to compose N limiters, will it handle different ordering for different types? That's not clear to me.

**Comment by sobrinho** [comment]
Makes sense, thanks again @mperham !
