### ISSUE TITLE
Dashboard UI broken

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [mperham/sidekiq#5584]
Hello! 

We are using Sidekiq Pro and our dashboard UI is broken. 

<img width="1342" alt="Screen Shot 2022-10-24 at 9 21 03 AM" src="https://user-images.githubusercontent.com/1152361/197576002-7e2c7e78-2afb-46cc-8e58-82563130ee46.png">

The gem we're using is `gem 'sidekiq-pro', source: "https://gems.contribsys.com/"`. Specifically:

```
GEM
  remote: https://gems.contribsys.com/
  specs:
    sidekiq-pro (5.0.0)
      concurrent-ruby (>= 1.0.5)
      sidekiq (>= 5.2.7)
```

We're using Ruby version 2.6.6, and Rails version 5.2.6. Any tips on what we should debug to get this back online? Thanks!

**Comment by davidwessman** [comment]
Any error messages in the server log or browser console log?

**Comment by tyrannosaurus-becks** [comment]
We propagate our logs to Datadog and aren't getting any errors. The warnings we have are related to a background job that times out hitting someone else's API, and they don't seem relevant to this.

<img width="1344" alt="Screen Shot 2022-10-24 at 3 50 28 PM" src="https://user-images.githubusercontent.com/1152361/197644600-c1ec0c7e-1c0f-4e6f-9629-91946ac2a5a9.png">

Any other thoughts on how we might track down the root cause? Appreciate your attention to this.

**Comment by mperham** [comment]
I've never seen anything like that behavior before, I can't imagine why the page would be simply cut-off like that.

**Comment by mperham** [comment]
Try another browser?

**Comment by nateberkopec** [comment]
I wonder if you look at the source/actual response, if it cuts off in the same place every time and if where it cuts off tells you something about what the problem is.

**Comment by davidwessman** [comment]
It seems super weird that it made it to `Dashb` in the header the first time and then `Dashbo` in the next ones.

**Comment by tyrannosaurus-becks** [comment]
Looks like it persists in Safari too. 

Well, if anything else comes to mind, let me know! Thanks!
