### ISSUE TITLE
Web UI clash with sidekiq-cron

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5590]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Pro 5.3.0 / Ent 2.3.0

Since sidekiq-cron is using the name `Cron` for the tab and also is Sidekiq Ent, one is overriding the other.

Can we change it to `Periodic` for instance?

The reason we are using the sidekiq-cron is that we want the ability to pause a cron from being scheduled and Enterprise doesn't support it yet (see https://github.com/mperham/sidekiq/issues/5000).

If we don't require the enterprise web UI, we can't see the `Limits` tabs either.

**Comment by mperham** [comment]
Given that the feature is called Periodic Jobs everywhere else, I don’t think this is unreasonable. I can get this into Ent 7.0.

**Comment by sobrinho** [comment]
In the case someone needs it before Ent 7.0, that will make both available at the same time:

```ruby
Sidekiq::Web.tabs["Cron"] = "cron"
Sidekiq::Web.tabs["Periodic"] = "loops"
```
