### ISSUE TITLE
Feedback: Embedded Mode Logger Messages

### ISSUE THREAD

**Issue by mieko** [mperham/sidekiq#5593]
I've been experimenting with the embedded mode since yesterday, and it seems to be a really awesome feature.  I was initially confused by one thing, though:

I had configured the embedded mode like so:
```ruby
Sidekiq.configure_embed do |config|
  config.concurrency = 1
end
```

And upon seeing the following message:
```
INFO: Embedded mode running with 6 threads
```

I (wrongly) assumed that either my `configure_server` block or `RAILS_MAX_THREADS` were somehow overriding embedded mode's concurrency, and spent a bit trying to track down the problem.  I now know (via source inspection) that the thread-count is the total count of threads in the process, not just Sidekiq's job-processing threads.  This might have been more confusing because my non-embedded dedicated Sidekiq processes were set to `-c 6`.

If the message would've included the thread names (like it does with DEBUG log level), or explicitly reinforced Sidekiq's configured concurrency, I think I would've avoided this mistake.

**Comment by mperham** [comment]
I changed the wording slightly to "total process thread count: 6".
