### ISSUE TITLE
Metrics page breaks with polling enabled

### ISSUE THREAD

**Issue by xdmx** [mperham/sidekiq#5595]
I've just upgraded to Sidekiq 7.0 and noticed that the metrics page breaks when the polling is enabled and it refreshes the data. The first load works, but then the graph breaks.

Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0

**Comment by mperham** [comment]
The metrics data does not auto-refresh just yet. You’ll need to manually refresh for now.

**Comment by davidwessman** [comment]
Should the polling button be removed?

**Comment by mperham** [comment]
Sure.
