### ISSUE TITLE
Doubt about usage with Azure Queue Storage

### ISSUE THREAD

**Issue by piradata** [mperham/sidekiq#5596]
Hello!

On our current project we have the default configuration of sidekiq listening to the asynchronous jobs queue from redis, but we are hosted on azure and were thinking about migrating the redis to a similar service on azure called [Azure Queue Storage](https://learn.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction) (or AQS for short).

It seems very similar with the AWS SQS (Simple Queue Service) and I have read already that this one works well as a job queue. One example with sidekiq would be the implementations of the [sidekiq-sqs gem](https://rubygems.org/gems/sidekiq-sqs/versions/0.0.17) and the Implementation done with [Shoryuken using SQS](https://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/).

My doubt is, it works out of the box as fine as within redis and SQS or do I need to do some tweaking for that to work?

If someone has already tested to run sidekiq together with AQS and could share the results/experiences I would be really glad 🙂

**Comment by mperham** [comment]
Sidekiq only supports Redis. It won’t ever support SQS or AQS.
