### ISSUE TITLE
Feature Proposal: Hooks in job info ERB file to allow for custom rows in the UI

### ISSUE THREAD

**Issue by pharris2411** [mperham/sidekiq#5613]
I've created a bit of a Javascript hack to parse job ID information in the UI and append additional rows for my own personal use, and I'd love to make this a more formalized capability. While it'd be easy to grab [_job_info.erb](https://github.com/mperham/sidekiq/blob/main/web/views/_job_info.erb) and override locally, we'd like to avoid this if possible to make upgrading easier. I think this could work by adding hooks into `_job_info.erb` similar to how custom tabs work, with additional rows being appended and content coming from a `call!` method of classes we pass in. Those classes would need access to the job details but read only.

I've attached an example screenshot -- the Datadog links are in the Job ID row, but could easily be their own row. (I also added a Sidekiq Batch link to make linking between batches and jobs easier -- I think this would be a great addition to the base product even without the need for a custom hook.)

If this seems like a feature you'd be interested I'd be happy to put together a PR. Thanks!

<img width="1247" alt="196208589-f83a452c-24da-41b0-8185-befcc460b5dc" src="https://user-images.githubusercontent.com/1631278/199349189-8077ab36-c79c-447a-bd3c-f43b0b69832c.png">

**Comment by mperham** [comment]
Much of that could be auto-detected and built in (e.g. if the payload contains a BID, link to /batches/BID). I'd be happy to get a PR with any improvements.

**Comment by pharris2411** [comment]
Closing as this PR has been merged: https://github.com/mperham/sidekiq/pull/5624
