### ISSUE TITLE
Deploy is not shown in metrics if Sidekiq is configured to use non-default (non-0) Redis DB number

### ISSUE THREAD

**Issue by davidrunger** [mperham/sidekiq#5615]
## Problem

A Deploy marked via `Sidekiq::Deploy.mark!(gitdesc)`, as documented [here][mark-documentation], will not be shown in the Sidekiq web UI metrics graph (as a vertical red line) if Sidekiq is configured to use a non-default Redis DB number (i.e. a Redis DB index other than 0).

[mark-documentation]: https://github.com/mperham/sidekiq/wiki/Metrics#tracking-deployments

## Cause

The Deploy doesn't appear because the deploy gets recorded in Redis DB 0 (because [here](https://github.com/mperham/sidekiq/blob/v7.0.0/lib/sidekiq/deploy.rb#L28) it uses `Sidekiq::RedisConnection.create`, which does not take into account the Sidekiq Redis configuration in `config/initializers/sidekiq.rb`), but the metrics query will attempt to retrieve the deploy marks from whichever non-default Redis DB (e.g. DB index 1) Sidekiq has been configured to use (because [here](https://github.com/mperham/sidekiq/blob/v7.0.0/lib/sidekiq/metrics/query.rb#L18) it uses `Sidekiq.default_configuration.redis_pool`, which does respect the Sidekiq configuration), and so the deploy marks are not found to display.

## Workaround

As a workaround, I'm instead marking the Deploy like this:

```rb
require 'sidekiq/deploy'
gitdesc = ENV.fetch('GIT_REV').first(7)
Sidekiq::Deploy.new(Sidekiq.redis_pool).mark(label: gitdesc)
```

Instead of using the default `Sidekiq::RedisConnection.create`, this uses `Sidekiq.redis_pool`, which uses Redis DB 1, as I have configured Sidekiq to do.

## Environment info

Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0 / nil / nil

`config/initializers/sidekiq.rb`:

```rb
# frozen_string_literal: true

# Note: we are using Redis DB index 1.
redis_url = "#{ENV.fetch('REDIS_URL')}/1"

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url }
end

Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }
end
```

`config/sidekiq.yml`:

```yml
:concurrency: 3
development:
  :concurrency: 1

:queues:
  - ['default', 3]
  # [... various other queues ...]
  - ['mailers', 1]
```

**Comment by mperham** [comment]
Get rid of your initializer, that's unnecessary. Use REDIS_URL:

```
REDIS_URL=redis://localhost:6379/1 bundle exec rake deploy:mark (or whatever...)
```

**Comment by davidrunger** [comment]
Thanks for your quick reply, @mperham !

I'm having a difficult time writing this reply in a way that captures my gratitude and deference to you. I don't want to be difficult, just to add some context.

FWIW, the solution you offered doesn't work so well for me, because I am not marking the Sidekiq deploys within a dedicated rake task along the lines of `bundle exec rake deploy:mark`, for which I could set the `REDIS_URL` environment variable to the desired value.

Rather, I am marking the Sidekiq deploys within a larger "`release-tasks`" script (you can see it [here](https://github.com/davidrunger/david_runger/blob/66c195e/bin/release-tasks#L45-L49), if you like). Thus, it isn't really appropriate for me to set `REDIS_URL=redis://localhost:6379/1` for that whole script, because some of the other things done in that script are not Sidekiq-related, and should instead use Redis DB 0 (which is the Redis DB index that my app uses for its non-Sidekiq Redis uses).

Of course, I have several options available:

1. separate out a `sidekiq_deploy:mark` rake task and then do `REDIS_URL=redis://localhost:6379/1 bundle exec rake sidekiq_deploy:mark`, as you suggested
2. temporarily modify `ENV` (`ENV['REDIS_URL'] = 'redis://localhost:6379/1'`) within the part of the `release-tasks` script that calls `Sidekiq::Deploy.mark!(gitdesc)` and then restore `ENV['REDIS_URL']` to its original value
3. continue using the workaround that I mentioned in my original issue description
4. stop using a non-0 Redis DB for Sidekiq

From my perspective, none of those options seem quite ideal. I think it would be nice if the documented `Sidekiq::Deploy.mark!(gitdesc)` would Just Work™ out of the box, even for Sidekiq setups such as mine. Barring that, it might be useful to add a note about this potential "gotcha" to the documentation, and/or maybe to expand the method signature of `Sidekiq::Deploy::mark!` to accept an optional additional parameter specifying a Redis DB index within which to mark the deploy?

I fully understand if accommodating my app's Sidekiq setup / release process is not within the scope that you want for the Sidekiq library and/or its documentation, but I would feel somewhat remiss if I did not share that the solution which you suggested doesn't work super well for me.

Thanks for reading and for your consideration! I'm just putting these thoughts out there. I don't expect/require a reply. Thanks for everything you do!

**Comment by mperham** [comment]
Yeah totally, when you do everything within a monolithic process, configuration can be tricky.

You don't even need a rake task, just an .rb file with those three lines. Your big process can just spin off a child process to do so and you can configure that child ENV separately. Here's an example:

```ruby
# deploy.rb
require "sidekiq/deploy"
puts ENV["REDIS_URL"]
label = `git log -1 --format="%h %s"`.strip
Sidekiq::Deploy.mark!(label)
```

```ruby
# runner.rb
puts ENV["REDIS_URL"]
system({"REDIS_URL" => "redis://localhost:6379/12"}, "bundle exec ruby deploy.rb")
```

```
% REDIS_URL=redis://localhost:6379/11 bundle exec ruby runner.rb
redis://localhost:6379/11
redis://localhost:6379/12
```

So runner.rb (your big app) has DB 11 but deploy.rb has DB 12. I hope that helps.

**Comment by davidrunger** [comment]
@mperham I think that's a pretty good solution. 👍 I think I'll do something like that. Thanks for the suggestion!
