### ISSUE TITLE
 uninitialized constant Sidekiq::Web

### ISSUE THREAD

**Issue by earnold** [mperham/sidekiq#5617]
Ruby version: 3.1.2
Rails version:  7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.0

I'm in a brand new rails app. When I attempt to mount the Web UI I get an error. Below are my routes and the error message.

I saw in the changelog a mention of a new metrics page. However, I didn't see any details about the previous web version being deprecated. Maybe I'm missing something obvious?  Thanks in advance!

```
Rails.application.routes.draw do
  resources :customers
  # root "articles#index"

  mount Sidekiq::Web => "/sidekiq"
end
```

Error message: 
```
17:00:34 sidekiq.1 | uninitialized constant Sidekiq::Web
17:00:34 sidekiq.1 | 
17:00:34 sidekiq.1 |   mount Sidekiq::Web => "/sidekiq"
17:00:34 sidekiq.1 |                ^^^^^

```

**Comment by samcambridge** [comment]
@earnold please don't close an issue without saying how you fixed it, I'm experiencing this issue

**Comment by samcambridge** [comment]
I wasn't requiring `require 'sidekiq/web'` 🤦

**Comment by 34code** [comment]
thanks I ran into the same thing
