### ISSUE TITLE
Embedded sidekiq hook before_worker_boot failed with wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by eddygarcas** [mperham/sidekiq#5629]
Ruby version: 3.1.2
Rails version: "~> 7.0.3"
Sidekiq / Pro / Enterprise version(s): 7.0.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

I'm getting the following error running sidekiq on an embedded mode:

```
12:27:45 web.1  | [8353] ! WARNING: Detected running cluster mode with 1 worker.
12:27:45 web.1  | [8353] ! Running Puma in cluster mode with a single worker is often a misconfiguration.
12:27:45 web.1  | [8353] ! Consider running Puma in single-mode (workers = 0) in order to reduce memory overhead.
12:27:45 web.1  | [8353] ! Set the `silence_single_worker_warning` option to silence this warning message.
12:27:45 web.1  | DEBUGGER: Attaching after process 8353 fork to child process 8364
12:27:45 web.1  | Subprocess Debugger (ruby-debug-ide 0.7.3, debase 0.2.5.beta2, file filtering is supported) listens on 0.0.0.0:36159
12:28:45 web.1  | [8353] ! Terminating timed out worker (worker failed to boot within 60 seconds): 8364
12:28:45 web.1  | DEBUGGER[bin/rails#8441]: Attaching after process 8353 fork to child process 8441
12:28:45 web.1  | Subprocess Debugger (ruby-debug-ide 0.7.3, debase 0.2.5.beta2, file filtering is supported) listens on 0.0.0.0:43215
12:29:14 web.1  | [8441] WARNING hook before_worker_boot failed with exception (ArgumentError) wrong number of arguments (given 2, expected 1)
```
This error happens when **Sidekiq::Embedded.run** method calls:

` @launcher = Sidekiq::Launcher.new(@config, embedded: true)`

I've followed the steps described on the wiki to test the embedded mode described here: 
[https://github.com/mperham/sidekiq/wiki/Embedding#puma](https://github.com/mperham/sidekiq/wiki/Embedding#puma)

Any advice would be appreciate it.

**Comment by mperham** [comment]
You'll need to provide the full backtrace associated with that ArgumentError.

**Comment by eddygarcas** [comment]
Here the stack trace, thanks!


`/3.1.0/bundler/gems/sidekiq-cron-70ce5c57ab36/lib/sidekiq/cron/launcher.rb:17:in 'initialize'`
`/3.1.0/gems/sidekiq-7.0.1/lib/sidekiq/embedded.rb:16:in 'new'`
`/3.1.0/gems/sidekiq-7.0.1/lib/sidekiq/embedded.rb:16:in 'run' config/puma.rb:50:in 'block in _load_from'`
`/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:297:in 'block in run_hooks'`
`/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:295:in 'each'`
`/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:295:in 'run_hooks'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster/worker.rb:55:in 'run'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:204:in 'worker'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:97:in 'block in spawn_worker' (eval):7:in 'block in fork' (eval):7:in 'fork' (eval):7:in 'fork'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:97:in 'spawn_worker'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:79:in 'block in spawn_workers'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:72:in 'times'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:72:in 'spawn_workers'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:161:in 'check_workers'`
`/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:435:in 'run'`
`/3.1.0/gems/puma-5.6.5/lib/puma/launcher.rb:193:in 'run'`
`/3.1.0/gems/puma-5.6.5/lib/rack/handler/puma.rb:72:in 'run'`
`/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:327:in 'start'`
`/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in 'start'`
`/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in 'block in perform' <internal:kernel>:90:in 'tap'`
`/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in 'perform'`
`/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in 'run'`
`/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in 'invoke_command'`
`/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in 'dispatch'`
`/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in 'perform'`
`/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in 'invoke'`
`/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in '<main>'`
`/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require'`
`/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in 'require' bin/rails:4:in '<main>'``

**Comment by mperham** [comment]
It looks to me like sidekiq-Cron is the source of that error, which is a third party extension. You will need to ask them for help.

**Comment by eddygarcas** [comment]
Thanks for your time on this @mperham I will contact them thanks!
