### ISSUE TITLE
Live Poll only working on Dashboard

### ISSUE THREAD

**Issue by rctneil** [mperham/sidekiq#5630]
Hi,

I'm finding that Live Poll is not working on any page other than the dashboard.  I can see the requests happening but the actual page doesn't refresh.

Any ideas?

**Comment by mperham** [comment]
Hmmm. No one else has reported this problem. You haven’t given us any information about your versions.

**Comment by rctneil** [comment]
@mperham Apologies for that.   Using latest version of 7 but also happened on latest version of 6 too.

Running latest Rails too and Ubuntu 22.04.

**Comment by mperham** [comment]
Can't reproduce and no other reports. I'm assume this is a local environmental issue.

**Comment by tc-joegiralt** [comment]
I have this exact issue. strangely enough, across all environments

**Comment by dgalliford** [comment]
What does LIVE POLL do?
