### ISSUE TITLE
Set retry on queue level instead of global or job level

### ISSUE THREAD

**Issue by MuhammadRaza29** [mperham/sidekiq#5639]
Currently, we can set retry globally or job level. But i want to set different retry for each queue. If there is smart way to setting it?

**Comment by mperham** [comment]
Nope but you can write your own set of smart job creators and do stuff like:

```ruby
def critical(jobclass)
  jobclass.set(queue: "critical", retry: 0)
end
```

So you can do something like: `critical(DeleteUserJob).perform_async(user_id)` in order to override the job defaults.
