### ISSUE TITLE
Sidekiq weight on Sidekiq UI

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5640]
Ruby version: 2.7.6p219
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Pro 5.3.0 / Ent 2.3.0

Hi there!

Would be nice to see the weights on UI to make sure it is being defined as expected.

Here's how it looks right now:

<img width="1229" alt="Screen Shot 2022-11-17 at 13 27 31" src="https://user-images.githubusercontent.com/26460/202502056-7797782d-8955-4ba0-9222-3b29dc8884f4.png">

Here's how it could look:

<img width="1243" alt="Screen Shot 2022-11-17 at 13 27 59" src="https://user-images.githubusercontent.com/26460/202502162-0fbbba1b-23e3-467c-9c0e-1cb84274bbeb.png">

What do you think?

**Comment by sobrinho** [comment]
I can open a PR if you agree or want to check it! 😬

**Comment by mperham** [comment]
I like that. Do it!

**Comment by mperham** [comment]
@raybaxter Yeah, you're right. If it's using strict priority, it shouldn't show weights at all. Your observation is wrong because the weight display is wrong.
