### ISSUE TITLE
Creating a batch with jobs results in an empty batch immediately?

### ISSUE THREAD

**Issue by TheTeaNerd** [mperham/sidekiq#5643]
**Ruby version**: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
**Rails version**: Rails 7.0.4
**Sidekiq / Pro / Enterprise version(s)**: sidekiq-pro (5.5.5), sidekiq (6.5.8)

My team uses Sidekiq Pro's batch feature heavily. I'm currently looking into a bug where we make a batch, but that batch is immediately empty! We have almost identical batch code elsewhere in the app, so either I'm making a very stupid mistake that I just cannot see, or there's a subtle Sidekiq/Redis bug I've stumbled into - any help or insight very much appreciated.

I've simplified the code to help debug, but I cannot replicate the issue for real outside my legacy app. (Which makes sense, most of the legacy app's batch code Just Works ™️). The batch code is in an ActiveRecord model which handles user uploaded video clips (written before ActiveStorage was available):

```ruby
  def a_public_method_that_adds_a_paperclip_attachment
    # skipping some work copying a cloud file around from where React uploaded it to a holding bucket

    # Let's background the transcoding of various variants, _eg_ thumbnails _etc_
    bid = process_sd_transcodes

    # Debug: Let's print out that details of that batch we just kicked off in the background as it's empty?!
    status = Sidekiq::Batch::Status.new(bid)
    Rails.logger.info("Jobs in the batch: #{status.total}")
    Rails.logger.info("Complete? #{status.complete?}")
    Rails.logger.info("Jobs pending the batch: #{status.pending}")
    Rails.logger.info("Data on the batch: #{status.data}")
  end

  def process_sd_transcodes
    Rails.logger.info("process_sd_transcodes(id: #{id})")

    batch = Sidekiq::Batch.new
    batch_description = "SD transcodes for MediaFile ##{id}"
    batch.jobs do
      high_priority_styles.map(&:to_s).each do |style|
        Rails.logger.info("Adding job for style '#{style}'")
        HelloWorker.perform_in(1.minute, id, style.to_s)
      end
    end
    Rails.logger.info("Batch details: '#{batch.inspect}'")
    batch.bid
  end
```

As you'd guess, `HelloWorker` is just a stripped down job to help debugging:
```ruby
class HelloWorker
  include Sidekiq::Worker

  def perform(id, message)
    Rails.logger.info("HelloWorker(id: #{id}, message: #{message})")
  end
end
```

When I run this, I see jobs being added to a batch (log lines 2-3), but upon inspection (line 4), the batch has an empty `@added[]` attribute, and is shown as having zero jobs, and being complete (lines 5-6) ... before the jobs in the batch even run (lines 9-10)! 

Log:
```
web      | [2022-11-17T20:09:07.753+00:00] INFO: process_sd_transcodes(id: 25, provider: User)
web      | [2022-11-17T20:09:07.754+00:00] INFO: Adding job for style 'video_180p_hover'
web      | [2022-11-17T20:09:07.757+00:00] INFO: Adding job for style 'video_360p_16_9'

# 🐛? Why is @added [] here?
web      | [2022-11-17T20:09:07.758+00:00] INFO: Batch details: '#<Sidekiq::Batch:0x00007f973dace960 @expiry=2592000, @bid="EQKmpr2Fj-v96g", @key="b-EQKmpr2Fj-v96g", @created_at=1668715747.7540343, @callbacks={}, @mutable=false, @new=true, @added=[]>'

# 🐛? Why is the batch empty?! Presumably it's complete just because it's empty.
web      | [2022-11-17T20:09:07.758+00:00] INFO: Jobs in the batch: 0
web      | [2022-11-17T20:09:07.758+00:00] INFO: Complete? true
web      | [2022-11-17T20:09:07.759+00:00] INFO: Jobs pending the batch: 0
web      | [2022-11-17T20:09:07.759+00:00] INFO: Data on the batch: {:is_complete=>true, :bid=>"EQKmpr2Fj-v96g", :total=>0, :pending=>0, :description=>nil, :failures=>0, :created_at=>1668715747.7540343, :fail_info=>[]}

sidekiq  | 2022-11-17T20:10:19.688Z pid=1 tid=227p class=HelloWorker jid=7d88b41fbfe7f6454f8bbb1a INFO: start
sidekiq  | 2022-11-17T20:10:19.689Z pid=1 tid=24rx class=HelloWorker jid=9c1b2bd631288281b08a0498 INFO: start
```

Any suggestions?

Thanks.

For reference, our initialiser `config/initializer/sidekiq.rb`:

```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: REDIS_URL, network_timeout: 5, id: nil, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
  config.super_fetch!
  config.reliable_scheduler!

  config.death_handlers << ->(job, error) do
    Sidekiq.logger.warn("Failed #{job['class']}##{job['jid']} with #{job['args']}: #{error.message}")
    Rails.logger.error(error)
    NewRelic::Agent.notice_error(error)
  end
end

Sidekiq::Client.reliable_push! unless Rails.env.test?
Sidekiq.configure_client do |config|
  config.redis = { url: REDIS_URL, network_timeout: 5, id: nil, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
end

metrics_task = Concurrent::TimerTask.new do
  Rails.application.executor.wrap do
    SendSidekiqStatisticsToNewRelic.call
  end
end
metrics_task.execute

Sidekiq.strict_args! if Rails.env.test? || Rails.env.development?

# Beta: see https://github.com/mperham/sidekiq/blob/main/Changes.md#650
Sidekiq.transactional_push!
```

**Comment by mperham** [comment]
Is it possible you have `Sidekiq::Testing.inline!` mode activated so the jobs don't go to Redis but execute immediately? That's the only remote possibility that came to mind.

**Comment by TheTeaNerd** [comment]
No, I don't think so.  I can't replicate the issue in test, so this is all running locally in development mode. Also inline wouldn't really explain the behaviour as I _do_ see the jobs queue (in the UI) and then execute later. I just never see a batch (or the callbacks fire, which is where this bug really started)

**Comment by TheTeaNerd** [comment]
Ah, it's `Sidekiq.transactional_push!` somehow.

If I disable that, this particular case starts working as expected. I've had this enabled in Production since July and it has _solved_ a few races for us, so that's surprising. All I can think of is that somehow the Paperclip attachment logic is messing with the transaction boundaries, either by being too slow (file IO) or by changing the state of the object repeatedly (as each variant is transcoded.)

We can't jump to Sidekiq 7 as we rely on Sidekiq-cron and, IIRC, it has an incompatibility, so I guess for now, I'll disable `transactional_push!` and re-evaluate the race conditions we'd solved with it. 

Closing as it's an integration issue rather than a bug I can concretely describe.
