### ISSUE TITLE
Unable to pass Hash as job argument

### ISSUE THREAD

**Issue by griley** [mperham/sidekiq#5644]
Ruby version: 3.1.2
Rails version: 7.0.3.1
Sidekiq / Pro / Enterprise version(s): 6.5.6  Sidekiq Pro 5.5.3

When submitting a job with a simple Hash as the arg:
`RemoteJobs::Encoder::ScreenerJob.perform_async({foo: 'bar'})`

You will see a warning in the sidekiq log:
```
WARN: Job arguments to RemoteJobs::Encoder::ScreenerJob do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```

This appears to be due to the fact that the [`json_safe` method](https://github.com/mperham/sidekiq/blob/v6.5.6/lib/sidekiq/job_util.rb#L67) will convert the keys from a symbol to string before it does its comparison to the original args passed in:
```
(rdbg) item
{"retry"=>5, "queue"=>"encode", "backtrace"=>true, "args"=>[{:foo=>"bar"}], "class"=>"RemoteJobs::Encoder::ScreenerJob", "jid"=>"f15ed6d4e6a55790f5feb5ab", "created_at"=>1668731647.8653924, "bid"=>"WyewtZcxbWI76A"}
(ruby) JSON.dump(item["args"])
"[{\"foo\":\"bar\"}]"
(ruby) JSON.parse(JSON.dump(item["args"]))
[{"foo"=>"bar"}]
```

**Workaround**
The workaround for this is to simply ensure you're using string values for your hash keys or doing something like `RemoteJobs::Encoder::ScreenerJob.perform_async({foo: 'bar'}.stringify_keys)`.

**Comment by mperham** [comment]
Symbols are already documented as unsupported.

https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple
