### ISSUE TITLE
Sidekiq 7 (embedding) not rebooting well after bundle update

### ISSUE THREAD

**Issue by jules-w2** [mperham/sidekiq#5646]
Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```ruby
#config/puma/production.rb

require "sidekiq"

env      = "production"
app      = "myapp"
app_path = "/srv/apps/#{env}/#{app}"


redis_db            = 8
sikdkiq             = nil
sikdkiq_queues      = [["critical", 10], "default", "low"]
sidekiq_concurrency = 2


directory "#{app_path}/current"
bind      "unix://#{app_path}/shared/tmp/sockets/puma.sock"


workers 2

threads 1,3

prune_bundler


on_worker_boot do
  sikdkiq = Sidekiq.configure_embed do |config|
    config.redis        = { :db => redis_db }
    config.queues       = sikdkiq_queues
    config.concurrency  = sidekiq_concurrency
  end
  sikdkiq.run
end

on_worker_shutdown do
  sikdkiq&.stop
end
```

After a bundle update, during the deploy Sidekiq is not able to restart well...

```
[2536033] + Gemfile in context: /srv/apps/production/myapp/releases/20221118184013/Gemfile
2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>5, :pool_name=>"internal", :url=>nil}
2022-11-18T19:19:52.999Z pid=2536033 tid=1id7p INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-18T19:19:52.999Z pid=2536033 tid=1id89 INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-18T19:19:53.198Z pid=2536033 tid=1idvl INFO: Sidekiq running embedded, total process thread count: 6
[2536033] ! Unable to start worker
[2536033] You have already activated redis-client 0.11.1, but your Gemfile requires redis-client 0.11.2. Prepending `bundle exec` to your command may solve this.
[2536033] /srv/apps/production/myapp/shared/bundle/ruby/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:308:in `check_for_activated_spec!'
```

On other example with one another gem

```
[2062625] + Gemfile in context: /srv/apps/production/myapp/releases/20221117151740/Gemfile
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Running in ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>5, :pool_name=>"internal", :url=>nil}
2022-11-17T15:47:08.843Z pid=2062625 tid=188px INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-17T15:47:08.843Z pid=2062625 tid=188qh INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
2022-11-17T15:47:09.043Z pid=2062625 tid=18875 INFO: Sidekiq running embedded, total process thread count: 6
[2062625] ! Unable to start worker
[2062625] You have already activated timeout 0.1.0, but your Gemfile requires timeout 0.3.0. Since timeout is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports timeout as a default gem.
```

Do you have any idea how to solve this problem?

**Comment by mperham** [comment]
You need to use “bundle exec” to start Puma. 

On Fri, Nov 18, 2022, at 11:37, Jules wrote:
> 
> 
> 
> Ruby version: 3.1.2
> Rails version: 7.0.4
> Sidekiq / Pro / Enterprise version(s): 7.0.1
> 
> Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
> 
> #config/puma/production.rb
> 
> require "sidekiq"
> 
> env      = "production"
> app      = "myapp"
> app_path = "/srv/apps/#{env}/#{app}"
> 
> 
> redis_db            = 8
> sikdkiq             = nil
> sikdkiq_queues      = [["critical", 10], "default", "low"]
> sidekiq_concurrency = 2
> 
> 
> directory "#{app_path}/current"
> bind      "unix://#{app_path}/shared/tmp/sockets/puma.sock"
> 
> 
> workers 2
> 
> threads 1,3
> 
> prune_bundler
> 
> 
> on_worker_boot do
>   sikdkiq = Sidekiq.configure_embed do |config|
>     config.redis        = { :db => redis_db }
>     config.queues       = sikdkiq_queues
>     config.concurrency  = sidekiq_concurrency
>   end
>   sikdkiq.run
> end
> 
> on_worker_shutdown do
>   sikdkiq&.stop
> end
> After a bundle update, during the deploy Sidekiq is not able to restart well...
> 
> `[2536033] + Gemfile in context: /srv/apps/production/myapp/releases/20221118184013/Gemfile
> 2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
> 2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: See LICENSE and the LGPL-3.0 for licensing details.
> 2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
> 2022-11-18T19:19:52.996Z pid=2536033 tid=1idvl INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>5, :pool_name=>"internal", :url=>nil}
> 2022-11-18T19:19:52.999Z pid=2536033 tid=1id7p INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>2, :pool_name=>"default", :url=>nil}
> 2022-11-18T19:19:52.999Z pid=2536033 tid=1id89 INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>8, :size=>2, :pool_name=>"default", :url=>nil}
> 2022-11-18T19:19:53.198Z pid=2536033 tid=1idvl INFO: Sidekiq running embedded, total process thread count: 6
> [2536033] ! Unable to start worker
> [2536033] You have already activated redis-client 0.11.1, but your Gemfile requires redis-client 0.11.2. Prepending `bundle exec` to your command may solve this.
> [2536033] /srv/apps/production/myapp/shared/bundle/ruby/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:308:in `check_for_activated_spec!'
`
> On other example with one another gem
> 
> `[2062625] + Gemfile in context: /srv/apps/production/myapp/releases/20221117151740/Gemfile
> 2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Running in ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
> 2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: See LICENSE and the LGPL-3.0 for licensing details.
> 2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
> 2022-11-17T15:47:08.841Z pid=2062625 tid=18875 INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>5, :pool_name=>"internal", :url=>nil}
> 2022-11-17T15:47:08.843Z pid=2062625 tid=188px INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
> 2022-11-17T15:47:08.843Z pid=2062625 tid=188qh INFO: Sidekiq 7.0.1 connecting to Redis with options {:db=>21, :size=>2, :pool_name=>"default", :url=>nil}
> 2022-11-17T15:47:09.043Z pid=2062625 tid=18875 INFO: Sidekiq running embedded, total process thread count: 6
> [2062625] ! Unable to start worker
> [2062625] You have already activated timeout 0.1.0, but your Gemfile requires timeout 0.3.0. Since timeout is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports timeout as a default gem.
`

**Comment by jules-w2** [comment]
Puma is start with "bundle exec" and use  the -SIGUSR1 signal to restart, as specified in the Puma documentation for phased restart (0 Downtime)

https://github.com/puma/puma/blob/master/docs/restart.md#phased-restart

```service
# This file tells systemd how to run Puma as a 24/7 long-running daemon.
#
# Customize this file based on your bundler location, app directory, etc.
# Customize and copy this into /usr/lib/systemd/system (CentOS) or /lib/systemd/system (Ubuntu).
# Then run:
#   - systemctl enable puma_myapp_production
#   - systemctl {start,stop,restart} puma_myapp_production
#
#
# Use `journalctl -u puma_myapp_production -rn 100` to view the last 100 lines of log output.
#
[Unit]
Description=Puma HTTP Server for myapp (production)

After=syslog.target network.target

[Service]
Type=notify
WatchdogSec=10
User=root
WorkingDirectory=/srv/apps/production/myapp/current
ExecStart=/usr/local/rvm/bin/rvm 3.1.2@myapp_production do bundle exec puma -e production
ExecReload=/bin/kill -USR1 $MAINPID

# if we crash, restart
RestartSec=1
Restart=on-failure

StandardOutput=append:/srv/apps/production/myapp/shared/log/puma_access.log
StandardError=append:/srv/apps/production/myapp/shared/log/puma_error.log

SyslogIdentifier=puma_myapp_production
[Install]
WantedBy=multi-user.target
```

**Comment by mperham** [comment]
What makes you think this problem is associated with Sidekiq, and it isn’t a general issue with puma and bundler?

**Comment by jules-w2** [comment]
I think this problem is associated with Sidekiq because on my server I have 15 Rails apps (Puma 7 with phased restart), (10 using Sidekiq and 5 not using Sidekiq) and after an bundle update, I only have this issue with the apps using Sidekiq.

I just did a bundle update on an application that does not use Sidekiq and after  a new deployment and everything works fine.

```
==> puma_access.log <==
[4184878] - Starting phased worker restart, phase: 2
[4184878] + Changing to /srv/apps/production/myapp2/current
[4184878] - Stopping 695323 for phased upgrade...
[4184878] - TERM sent to 695323...
[2697668] + Gemfile in context: /srv/apps/production/myapp2/releases/20221119124128/Gemfile
[4184878] - Worker 0 (PID: 2697668) booted in 0.88s, phase: 2
[4184878] - Stopping 695342 for phased upgrade...
[4184878] - TERM sent to 695342...
[2697700] + Gemfile in context: /srv/apps/production/myapp2/releases/20221119124128/Gemfile
[4184878] - Worker 1 (PID: 2697700) booted in 0.86s, phase: 2
```

**Comment by mperham** [comment]
I'm not sure of the issue. Embedded mode is brand new and I figured there would be edge cases like this.

The issue I've seen before with Sidekiq + capistrano + rolling restart is that capistrano creates a new directory for the new deploy but restarting the binary does not `cd` to the new `current` symlink before re-exec'ing. Molly solved this with indirection: instead of exec'ing the binary directly, she exec'd a script which cd's to the current directory and runs the binary.

https://github.com/mperham/sidekiq/issues/4005

The other thing that came to mind is `BUNDLE_GEMFILE`.

**Comment by mperham** [comment]
Ah, embedding requires preload_app in puma. Otherwise the Sidekiq initializer won’t load before onworkerboot.

**Comment by jules-w2** [comment]
prune_bundler is incompatible with preload_app! and prune_bundler is require to phased restart  in Puma.

So if embedding requires preload_app in puma, embedding is not compatible with Phased restart in Puma.

https://puma.io/puma/Puma/DSL.html#prune_bundler-instance_method
Note: This is incompatible with [#preload_app!](https://puma.io/puma/Puma/DSL.html#preload_app!-instance_method).

https://github.com/puma/puma/blob/master/docs/restart.md#phased-restart

**Comment by mperham** [comment]
I think that's right. Preload_app is required to run the initializer first. If you don't need an initializer, you might be able to get it working. 

I suspect another issue might be the require at the top, which is causing the master process to load the Sidekiq gem. Maybe move that to the top of the onworkerboot block?

**Comment by jules-w2** [comment]
I still have the same error by putting the require in the on_worker_boot block...


```ruby
env      = "production"
app      = "myapp"
app_path = "/srv/apps/#{env}/#{app}"


redis_db            = 7
sikdkiq             = nil
sikdkiq_queues      = [["critical", 10], "default", "low"]
sidekiq_concurrency = 2


directory "#{app_path}/current"
bind      "unix://#{app_path}/shared/tmp/sockets/puma.sock"


workers 2

threads 1,10

prune_bundler


on_worker_boot do
  require "sidekiq"
  sikdkiq = Sidekiq.configure_embed do |config|
    config.redis        = { :db => redis_db }
    config.queues       = sikdkiq_queues
    config.concurrency  = sidekiq_concurrency
  end

  sikdkiq.run
end


on_worker_shutdown do
  sikdkiq&.stop
end
```

**Comment by mperham** [comment]
Ok. Well, it's not going to work then.

**Comment by jules-w2** [comment]
ok, I will rollback to the old way to run sidekiq (without embedding)

this feature is not usable at the moment. You should specify it in the embedding Wiki page because phased restart is widely used with Puma to have 0 downtime.

**Comment by mperham** [comment]
> this feature is not usable at the moment.

This is not a fair or true statement. It's a brand new and complex feature, we're still working out its caveats and limitations. Just because it doesn't work with phased restart doesn't make it "unusable".

**Comment by jules-w2** [comment]
You are right, it's more fair to say that Sidekiq embedding feature is not compatible yet with Puma Phased Restart.
With Puma Hot restart (and app_preload) this feature is working well.

**Comment by simptive** [comment]
In my case, while using Rails 7.1.1, Puma 6.4 and Sidekiq 7.1.6; sidekiq starts automatically with Puma without embedding. I'm amazed how it's happening and what can I do to avoid it. Following are related configurations:

**config/puma.rb**
  ```
rails_env = ENV.fetch("RAILS_ENV") { "development" }
  environment rails_env
  app_dir = File.expand_path("../..", __FILE__)
  preload_app!
  
  # Allow puma to be restarted by `rails restart` command.
  plugin :tmp_restart
  
  if rails_env == 'development'
    port 3000
  else
    bind "unix:#{app_dir}/tmp/sockets/puma.sock"
  end
  
  if rails_env == 'production'
    workers 2
    threads 4, 8
  else
    workers 0
    threads 0, 1
  end
```

**config/initializers/sidekiq.rb**
```
Sidekiq.configure_server do |config|
  config.redis = { path: '/var/run/redis/redis-server.sock' }
end

Sidekiq.configure_client do |config|
  config.redis = { path: '/var/run/redis/redis-server.sock' }
end

if Rails.env == 'development'
	Sidekiq.redis { |conn| conn.flushdb }
end
```
**Log:**
```
=> Booting Puma
=> Rails 7.1.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
2023-10-13T18:58:27.115Z pid=64448 tid=1c9s INFO: Sidekiq 7.1.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :path=>"/var/run/redis/redis-server.sock", :url=>nil}
Puma starting in single mode...
* Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 1
*  Environment: development
*          PID: 64448
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```
I just upgraded my whole stack from Rails 6.1. Previously I was used to start sidekiq like following:
```
worker: 
  command: bundle exec sidekiq -C config/sidekiq.yml
  logfile: log/worker.log
```

**Comment by mperham** [comment]
@simptive do not comment on old closed issues. Open your own issue if you have a problem.
