### ISSUE TITLE
Reconsider namespaces

### ISSUE THREAD

**Issue by ipmb** [mperham/sidekiq#5649]
I saw the namespaces functionality was recently removed, but [Redis 6.0 has added functionality which make namespaces more of a first class citizen with proper ACLs](https://redis.io/docs/management/security/acl/). They've also [communicated that ACLs won't be supported for databases and in general, use of databases is not encouraged](https://github.com/redis/redis/issues/8099#issuecomment-741868975).

I've read [your concerns about namespaces](http://www.mikeperham.com/2015/09/24/storing-data-with-redis/#namespaces) and I agree that separate Redis instances is a _better_ solution, but there are certainly scenarios (especially non-production environments) where namespaces with ACLs are a reasonable option.

Given this information, would you reconsider the removal support for namespaces?

**Comment by mperham** [comment]
I can't support N different Sidekiq environments, all running potentially different versions, in the same keyspace. There's too much cognitive overhead and room for subtle errors.

**Comment by ipmb** [comment]
I think I may not have explained myself well based on your response. I'd like to have an option for Sidekiq to prefix all the Redis keys it uses with a predefined string. The use case isn't to run multiple Sidekiq instances in the same keyspace, it's so Sidekiq can be used by Redis users that are set up with [ACLs](https://redis.io/docs/management/security/acl/) that only allow them access to a certain pattern.

For example, if Sidekiq wants to use the key `queue:default`, but I've defined a prefix (or namespace) of `myuser:`, Sidekiq would instead use the key `myuser:queue:default`.

Python's Celery supports this kind of setup with its [`global_keyprefix`](https://docs.celeryq.dev/projects/kombu/en/stable/reference/kombu.transport.redis.html#kombu.transport.redis.Channel.global_keyprefix) option.

Apologies in advance if I've misunderstood your response and am just creating extra noise.

**Comment by mperham** [comment]
Ah, I see. That's effectively what the `redis-namespace` gem does. Support for it was just removed in the 7.0 release and I have no plans to reimplement it. For the time being, the Sidekiq user requires full r/w access to the entire keyspace.

**Comment by jlurena** [comment]
> Ah, I see. That's effectively what the `redis-namespace` gem does. Support for it was just removed in the 7.0 release and I have no plans to reimplement it. For the time being, the Sidekiq user requires full r/w access to the entire keyspace.

Why was it removed? Would you consider a PR adding it back? 

My use case is:

- Redis instances are expensive
    - Ideally, you'd have 3 redis instances. High traffic, medium traffic, low traffic
    - You can have multiple Microservices connect to either of the above redis instances. Namespaced keys prevent conflicts

**Comment by mperham** [comment]
https://www.mikeperham.com/2015/09/24/storing-data-with-redis/

**Comment by misdoro** [comment]
Another possible use-case for the namespaces is multiple staging environments sharing the same Redis cluster

**Comment by smeyfroi** [comment]
Long-time (very happy) sidekiq-ent user here, arguing to the need for a more economical solution for our case with the demise of namespaces.

Our usecase is that we have a large number of deployments running sidekiq for mostly trivial background processing. Think one sidekiq worker on standby to background-import data once a day/week/month/year. We also have projects that use sidekiq more extensively, but not many.

Namespaces allow us to use a few of the tiniest redis instances shared between several of our small sidekiq users. Does it matter if that instance fails? No: nothing is that time sensitive and sidekiq-ent will happily recover for us when we've brought a new redis up.

The removal of namespaces causes collisions of global sidekiq state for us even when each project has unique queue names (we tested). So we have to do something.

Choice 1: partitioning via separate databases is seemingly not preferred by the redis team, and would in any case cause us a management overhead in tracking which project "owns" which numbered DB on which redis instance.

Choice 2: partitioning by use of separate redis instances means multiplying our redis spend by an order of magnitude (and then some) to have largely unused redis servers, each essentially storing just a handful of non-critical data. This doesn't seem like a great solution, although I accept that we could look at replacing our use of sidekiq with cron, or some other lightweight thing that perhaps better matches the majority of our sidekiq use. We'd then have a split in projects that use sidekiq and those that don't.

I suspect we're unusual in that we build a lot of small systems that use sidekiq lightly, as well as a few that use it more heavily. In our case though, the addition of a per-sidekiq key-prefix would be a huge benefit. Unless we've missed some other solution? In which case, very interested to hear suggestions.

Hoping our usecases are a new consideration that might sway the argument in favour of bringing back per-deployment namespacing.

**Comment by mperham** [comment]
@smeyfroi It sounds like you might also consider running your own Redis instances "beside" the app. Do you have the resources and deployment flexibility to run Redis locally on those small app VMs? Redis is very efficient and running it locally makes it very reliable too.

**Comment by smeyfroi** [comment]
> @smeyfroi It sounds like you might also consider running your own Redis instances "beside" the app. Do you have the resources and deployment flexibility to run Redis locally on those small app VMs? Redis is very efficient and running it locally makes it very reliable too.

It's a good idea, but I think that would involve a bit more thought: we use auto-scaling as a standard for production deployments (we're on AWS), mostly as protection against bots. So having a shared redis in that situation is a little tricky to manage when things go crazy and the ASG kicks in. Perhaps that's a downside of us running both web and background workloads co-located in our VMs, but it has suited us very well (so far) to take such a simple-minded approach.

Sounds like we need to put some thought into re-architecting our deployments one way or another, or accept that we'll need to stand up a lot of redis instances.

**Comment by pavel-so** [comment]
> > Why was it removed?
> 
> https://www.mikeperham.com/2015/09/24/storing-data-with-redis/

@mperham 

Our use case is similar to the previous posters: we use same redis instance for multiple staging deployments, this allows us to save on the ops cost and allows us to rapidly spin up as many environments and projects in staging environment as we need, and if everyone follows the namespaces convention, which is really easy, there is no overlap in the namespaces.

The solutions you propose in your post either do not scale well for multi project staging, or require additional cost+work as an overhead. That for lower environments like dev/staging is a little bit too involved.

**Comment by virusman** [comment]
Same: I'm running both staging and production on the same machine, and now it's impossible to upgrade Sidekiq, because setting up separate Redis and dealing with configuration is way too much pain for something that worked just fine.

**Comment by smeyfroi** [comment]
@virusman we recently audited our estate for sidekiq-dependencies and of the ~100 deployments that we have using it, some could run ActiveJob in-memory for simple non-critical async use-cases, and the rest are currently up for migration to something more suitable.

Sidekiq has been our convenient, reliable, no-brainer default for many years, but it seems to be targetting different (exclusively large-scale use-cases) now. There are viable alternatives nowadays, particularly now that ActiveJob exists, each with their own pros and cons.

For us, our migration plan looks as if it will ultimately remove ~20 tiny redis servers, so it's a bit of a win for us all round.

**Comment by phil-janeapp** [comment]
@virusman I obviously don't know the particulars of your use-cases, but have you considered using Redis' native databases?  By default a Redis instance is configured with 16, but the upper limit is only limited by your total memory.  It's under the setting `databases` in redis.conf.

To use a different database you just change the number at the end of `REDIS_URL` - https://www.mikeperham.com/2015/09/24/storing-data-with-redis/ under "Databases" for an example.

**Comment by briceburg** [comment]
surprised/confused by the posture on namespaces here. 

while I get there's 16 native databases, this doesn't scale well when you have 10s, 100s of review/PR environments.  there's clear use-cases for them. and they're familiar and supported by configurations that often run alongside sidekiq such as ActiveSupport's CacheStores -- 

from [RedisCacheStore](Achttps://api.rubyonrails.org/v8.0/classes/ActiveSupport/Cache/RedisCacheStore.html#method-c-new); 
> No namespace is set by default. Provide one if the Redis cache server is shared with other apps: namespace: 'myapp-cache'.

also another thing that https://www.mikeperham.com/2015/09/24/storing-data-with-redis/ completely glosses over... 

**only database 0 is supported in redis cluster mode**

so for those running a redis _cluster_ to support multiple environments.... we can't use sidekiq.

from https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/;
> Redis Cluster does not support multiple databases like the standalone version of Redis. We only support database 0; the [SELECT](https://redis.io/commands/select) command is not allowed.

@mperham please reconsider namespaces. especially considering us who use redis in cluster mode.

**Comment by mperham** [comment]
@briceburg I feel like a broken record but **Sidekiq does not work in Redis cluster mode**. Namespaces and multiple environments have nothing to do with that and they do not fix the issue. Sidekiq requires MULTI transactions and MULTI does not work in cluster mode without very careful data modeling. Sidekiq did not design for cluster mode in 2012, it would require a completely new data model to work.

**Comment by ken39arg** [comment]
Hello,

I've been following the discussion in this issue and fully understand that `redis-namespace` usage isn't recommended. However, as long-time users of Sidekiq, we've faced significant challenges that make avoiding namespaces difficult for our specific setup.

After considerable experimentation, we've found what we believe is a more robust workaround for key namespacing, which I'd like to share.

The method we've discovered involves wrapping `redis-client`'s [`CommandBuilder`](https://github.com/redis-rb/redis-client/blob/master/lib/redis_client/command_builder.rb). This allows us to inject a custom command builder that adds a prefix to keys before they are sent to Redis.

Here's the workaround code:

```ruby
module Sidekiq
  class NamespaceCommandBuilder
    def initialize(namespace = "")
      @namespace = namespace
    end

    def generate(args, kwargs = nil)
      command = RedisClient::CommandBuilder.generate(args, kwargs)
      return command if @namespace.blank? || command.size < 2

      # Determine which arguments are keys and apply the namespace
      case command[0].to_s.upcase
      when "BRPOP", "BLPOP"
        # BLPOP key [key ...] timeout
        command[1..-2].each_with_index do |key, index|
          command[index + 1] = rename_key(key)
        end
      when "MGET", "EXISTS", "DEL"
        # MGET key [key ...]
        command.drop(1).each_with_index do |key, index|
          command[index + 1] = rename_key(key)
        end
      when "MSET", "MSETNX"
        # MSET key value [key value ...]
        command.drop(1).each_with_index do |key, index|
          command[index + 1] = rename_key(key) if index.even?
        end
      when "EVALSHA", "EVAL"
        # EVALSHA sha1 numkeys [key [key ...]] [arg [arg ...]]
        numkeys = command[2].to_i
        actual_keys = [numkeys, command.size - 3].min
        actual_keys.times do |i|
          key_index = 3 + i
          command[key_index] = rename_key(command[key_index]) if command[key_index]
        end
      when "SCRIPT"
        # SCRIPT commands do not typically operate on keys directly in this context
      else
        # Default for single-key commands
        command[1] = rename_key(command[1])
      end

      command
    end

    def rename_key(key)
      return key if @namespace.blank?

      "#{@namespace}:#{key}"
    end
  end
end

Sidekiq.configure_server do |config|
  config.redis = {
    url: "redis://redis:6379/0",
    command_builder: Sidekiq::NamespaceCommandBuilder.new("sidekiq"),
  }
end

Sidekiq.configure_client do |config|
  config.redis = {
    url: "redis://redis:6379/0",
    command_builder: Sidekiq::NamespaceCommandBuilder.new("sidekiq"),
  }
end
```

This approach allows us to apply prefixes to keys used by `Sidekiq.redis` and other integrations (like [`sidekiq-scheduler`](https://github.com/sidekiq-scheduler/sidekiq-scheduler)), providing a similar effect to `redis-namespace` but at a lower, more controlled layer.

#### Potential Considerations:

* This workaround might encounter issues with unverified gems or Sidekiq's internal operations that use Redis commands not explicitly handled in our CommandBuilder's case statement.
* There's a minor performance overhead due to the additional processing.

Despite these points, we currently believe this is the most viable workaround available given our constraints.



#### PS. Our specific challenges that necessitate this approach, as also raised by others, include:

1. Shared Redis instances across multiple environments/applications: 
    We require separate namespaces (prefixes) to share a single Redis instance, as 16 databases aren't sufficient.
2. Key pattern-based ACLs: 
    Related to the above, we need to implement access control based on key patterns.
3. Complex migration for direct Redis pushes:
    We have multiple applications (including non-Ruby ones) that directly LPUSH into Sidekiq queues via Redis. Migrating these systems to a different key structure would be complex and difficult.


Given this context, what are your thoughts on this workaround, and its potential for a more official integration?

**Comment by mperham** [comment]
@ken39arg You are welcome to provide your own 3rd party gem which adds support for namespaces to Sidekiq but it's not something I will support or endorse.

**Comment by jlurena** [comment]
@ken39arg another option is to use ActiveJob with Redis. We moved on from using redis as well to use Kafka.

**Comment by ken39arg** [comment]
Hi everyone,

Following up on this discussion, and understanding that native namespace support won't be integrated directly into Sidekiq, I've developed a new gem, `redis-client-namespace`, to address the need for key prefixes.

It leverages the `redis-client`'s `CommandBuilder` as discussed, providing a robust way to namespace your Redis keys for Sidekiq without relying on `redis-namespace`.

If you're facing similar challenges with Redis key management in Sidekiq, please feel free to check it out and use it:
https://github.com/ken39arg/redis-client-namespace

Hope this helps others in the community!
