### ISSUE TITLE
Add option to add additional context to JobLogger

### ISSUE THREAD

**Issue by fanantoxa** [mperham/sidekiq#5651]
To log when Jobs are start/done/fail Sidekiq has `Sidekiq::JobLogger`.
It send a simple message to the log that contains data as: timestamp, pid, tid, class INFO start/done/fail

From monitoring data this data is enough mostly for load/throughput/activity monitoring. 

For debugging of jobs sometimes requires to know if job was even run with certain arguments or if it was run at all.

Is it make sense to add additional config like `extended_job_tracking` (bool) that will add additional data to the start/done/fail messages like: args, queue, retries ?

If id does I can try make a PR to implement it 🙂

**Comment by mperham** [comment]
If you want to add more info, the easiest way today is to prepend `JobLogger#call`

```ruby
module Loggy
  def call(item, queue)
    Sidekiq::Context.add("queue", queue)
    super
  end
end

Sidekiq.configure_server do |config|
  Sidekiq::JobLogger.prepend(Loggy)
end
```

**Comment by fanantoxa** [comment]
Thank you! Will try this
