### ISSUE TITLE
Consider supporting models in Sidekiq::CurrentAttributes

### ISSUE THREAD

**Issue by fschwahn** [mperham/sidekiq#5653]
I recently stumbled on `Sidekiq::CurrentAttributes`, and I think it is really useful, as I push a lot of file generation tasks to background jobs which need the current users context.

However, the "classic" use case for `ActiveSupport::CurrentAttributes` is storing a user-model (eg. looking at the documentation: https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html), not primitives. Would you consider a PR adding support for (de)serializing ActiveRecord-objects here, similarly to how [ActiveJob does it](https://github.com/rails/rails/blob/main/activejob/lib/active_job/arguments.rb#L77)?

**Comment by mperham** [comment]
I don't want to build in support for framework-specific marshaling. First it's Rails, then I need to build in support for Hanami, Trailblazer, etc.

Your `attribute` should be `user_id` and your Current provide a `user` method which queries the database and caches the User instance.

**Comment by fschwahn** [comment]
Ok, got it - I thought it might be acceptable in this case, as `Sidekiq::CurrentAttributes` is completely specific to Rails anyway.

**Comment by TALlama** [comment]
@mperham I understand your reasoning here, but do you have example code that does this work? I think I've figured out how to do it, but it turned out to be surprisingly tricky to do, assuming you want model-oriented accessors (`user` and `user=`), and you want to cache the instance given to the setter (to avoid multiple DB hits) and clear it on resets (so that `Current.set(user:) { ... }` works).

```rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user_id

  def user=(instance)
    self.user_id = instance&.id
    @user = instance
  end

  def user
    @user ||= (User.find(user_id) if user_id)
  end

  resets { @user = nil }

  def set(...)
    super
  ensure
    @user = nil
  end
end
```

<details>
  <summary>To get this working, I wrote some specs…</summary>

```rb
RSpec.describe Current do
  describe "user" do
    let(:user) { double(:user, id: 1723) }

    def expect_to_find_user
      expect(User).to receive(:find).with(user.id).and_return(user)
    end

    it "allows simple accessors and reset to work" do
      expect(Current.user).to be_nil
      Current.user = user
      expect(Current.user).to eq(user)
      Current.reset
      expect(Current.user).to be_nil
    end

    it "works with Current.set" do
      expect(Current.user).to be_nil
      Current.set(user:) do
        expect(Current.user).to eq(user)
      end
      expect(Current.user).to be_nil
    end

    it "when restoring from Sidekiq, we won't have the cache" do
      expect(Current.user).to be_nil
      Current.set(user_id: user.id) do
        expect_to_find_user
        expect(Current.user).to eq(user)
      end
      expect(Current.user).to be_nil
    end
  end
end
```
</details>


<details>
  <summary>I also made a polymorphic version, since that's what I actually needed.</summary>

```rb
class Current < ActiveSupport::CurrentAttributes
  attribute :author_type, :author_id

  def author=(instance)
    self.author_type = instance&.class&.name
    self.author_id = instance&.id
    @author = instance
  end

  def author
    @author ||= author_type&.constantize&.find(author_id)
  end

  resets { @author = nil }

  def set(...)
    super
  ensure
    @author = nil
  end
end
```

With tests:

```rb
require "spec_helper"

RSpec.describe Current do
  describe "author" do
    let(:author) { double(:user, id: 1723, class: author_class) }
    let(:author_class) { [User, Reference, Applicant].sample }

    def expect_to_find_author(klass:)
      expect(klass).to receive(:find).with(author.id).and_return(author)
    end

    it "allows simple accessors and reset to work" do
      expect(Current.author).to be_nil
      Current.author = author
      expect(Current.author).to eq(author)
      Current.reset
      expect(Current.author).to be_nil
    end

    it "works with Current.set" do
      expect(Current.author).to be_nil
      Current.set(author:) do
        expect(Current.author).to eq(author)
      end
      expect(Current.author).to be_nil
    end

    it "when restoring from Sidekiq, we won't have the cache" do
      expect(Current.author).to be_nil
      Current.set(author_type: author_class.name, author_id: author.id) do
        expect_to_find_author klass: author_class
        expect(Current.author).to eq(author)
      end
      expect(Current.author).to be_nil
    end
  end
end
```
</details>

**Comment by mperham** [comment]
I think this is a better discussion for Rails? They are the ones who could provide cleaner patterns or APIs for this type of usage.

**Comment by tomprats** [comment]
@TALlama Did you have any luck with this? My first thought was to monkeypatch the `Sidekiq::CurrentAttributes::Load` middleware, but then it looked like I'd have to do the same to the `Save` middleware.

We've been using the full objects in `Current` since we started using it, so I am hesitant to switch that in case we run into edge-cases like `RecordNotFound` or something.

**Comment by fschwahn** [comment]
I created a gem for this a few months ago, for anyone who is interested: https://rubygems.org/gems/sidekiq-serialized_current_attributes

**Comment by mperham** [comment]
@fschwahn since you forked the Sidekiq CA code, you’ll need to license that gem LGPL.

**Comment by fschwahn** [comment]
Sorry, about that - I'm currently in holidays, but will correct it right after.
