### ISSUE TITLE
Sidekiq 7 sharding issues

### ISSUE THREAD

**Issue by klizas** [mperham/sidekiq#5654]
Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.1
Redis version: 6.2.7

Hello. I'm working on upgrading our Sidekiq Enterprise installation to Sidekiq 7. We run multiple instances of Sidekiq in our project and – multiple UIs:

Initializer:
```ruby
instance_1_url = "redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/1"
instance_2_url = "redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/3"

$REDIS_INSTANCE_1 = ConnectionPool.new(size: (ENV["SIDEKIQ_CONCURRENCY"] || ENV["RAILS_MAX_THREADS"] || "5").to_i + 8) { Redis.new(url: instance_1_url) }
$REDIS_INSTANCE_2 = ConnectionPool.new(size: (ENV["SIDEKIQ_CONCURRENCY"] || ENV["RAILS_MAX_THREADS"] || "5").to_i + 8) { Redis.new(url: instance_2_url) }

Sidekiq.configure_server do |config|
  config.redis = { url: instance_1_url }
  config.super_fetch!
  config.retain_history(30)
end

Sidekiq.configure_client do |config|
  config.redis = { url: instance_1_url }
end

Sidekiq::Client.reliable_push!
Sidekiq::Enterprise.unique! unless Rails.env.test?
```

Routing:
```ruby
mount Sidekiq::Pro::Web.with(redis_pool: $REDIS_INSTANCE_1), at: "sidekiq/instance_1", as: "sidekiq_instance_1"
mount Sidekiq::Pro::Web.with(redis_pool: $REDIS_INSTANCE_2), at: "sidekiq/instance_2", as: "sidekiq_instance_2"
```

It works well in Sidekiq 6.x, but when I try to access Web UI with Sidekiq 7, I get this error:
![](https://screenshot.click/22-23-soa03-72x70.png)

The problem occurs in `lib/sidekiq/api.rb`:
```ruby
def size
  Sidekiq.redis do |conn|
    procs = conn.sscan("processes").to_a <--- here
    if procs.empty?
      0
    else
      conn.pipelined { |pipeline|
        procs.each do |key|
          pipeline.hget(key, "busy")
        end
      }.sum(&:to_i)
    end
  end
end
```

I noticed that `procs = conn.sscan("processes").to_a` was recently changed from `procs = conn.sscan_each("processes").to_a`.

It seems like Redis `sscan` method requires two arguments instead of one: https://github.com/redis/redis-rb/blob/a8e00cbdac5e2eefc1872c0718d0290975b6e93b/lib/redis/commands/sets.rb#L187

I get the same error with multiple Redis client versions: 4.5.1 and 5.0.5.

How can I get multiple Sidekiq UIs running without getting this error?

**Comment by klizas** [comment]
I guess the issue is that it expects `RedisClient`, instead of `Redis`. But how to achieve Sharding, as explained in https://github.com/mperham/sidekiq/wiki/Pro-Web-UI#sharding with Sidekiq 7.0?

**Comment by mperham** [comment]
Ah right. You can try replacing `Redis` with `RedisClient` in the connection pool blocks and see what happens.

**Comment by klizas** [comment]
Here's the result:
![](https://screenshot.click/22-57-ahrpe-j735r.png)

**Comment by klizas** [comment]
Also it's worth mentioning that ` Sidekiq::Client.via` also does not work with `RedisClient`.

**Comment by mperham** [comment]
If you create the shard pool like Sidekiq creates its internal pools, it should work.

https://github.com/mperham/sidekiq/blob/1db35cc3d722c3e9d53848d699f9aa1ba097443c/lib/sidekiq/redis_connection.rb#L21-L24

**Comment by mperham** [comment]
You can use `Sidekiq::RedisConnection.create(...)` for a simple API.

**Comment by mperham** [comment]
Unfortunately Sidekiq will require a shim for some time but I've made a few changes to reduce the reliance on this shim. `redis-client` does not support Redis calls like `conn.operation(args...)`, instead requiring the caller to use `conn.call("operation", args...)`. I have to provide `method_missing` to bridge the different style. I've removed the usage of the `info` and `evalsha` helpers.

**Comment by klizas** [comment]
Thank you for suggestions. I've tried using `Sidekiq::RedisConnection.create()` for pool creation, but without success:
```ruby
instance_1_url = "redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/1"
instance_2_url = "redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/3"

$REDIS_INSTANCE_1 = Sidekiq::RedisConnection.create(url: instance_1_url)
$REDIS_INSTANCE_2 = Sidekiq::RedisConnection.create(url: instance_2_url)

mount Sidekiq::Pro::Web.with(redis_pool: $REDIS_INSTANCE_1), at: "sidekiq/instance_1", as: "sidekiq_instance_1"
mount Sidekiq::Pro::Web.with(redis_pool: $REDIS_INSTANCE_2), at: "sidekiq/instance_2", as: "sidekiq_instance_2"
```

It results in:
![](https://screenshot.click/22-53-e0ijw-n0eyh.png)

Am I doing something wrong?

**Comment by mperham** [comment]
I'm not sure what is wrong. Your code looks fine. I'll need to investigate.

**Comment by klizas** [comment]
Let me know if you'll find anything. Thank you!

**Comment by mperham** [comment]
This works for me:

```ruby
POOL1 = Sidekiq::RedisConnection.create(url: "redis://localhost:6379/1")
POOL2 = Sidekiq::RedisConnection.create(url: "redis://localhost:6379/2")

Myapp::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount Sidekiq::Pro::Web.with(redis_pool: POOL1), at: "/sidekiq1", as: "sidekiq1"
  mount Sidekiq::Pro::Web.with(redis_pool: POOL2), at: "/sidekiq2", as: "sidekiq2"
```

**Comment by mperham** [comment]
I've updated the wiki page. Thank you for the feedback!

**Comment by klizas** [comment]
Right, it does work! I probably edited something I shouldn't while debugging Sidekiq. Appreciate your help! 🙇
