### ISSUE TITLE
batch closed prematurely

### ISSUE THREAD

**Issue by y-shashank** [mperham/sidekiq#5655]
Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
Rails version:  rails-5.2.8.1
Sidekiq / Pro / Enterprise version(s): 5.2.2/4.0.4
gem 'sidekiq-unique-jobs',        '3.0.11'

I am trying to add more jobs to the current batch, the data loaded from api is very large to i am trying to add few thousand jobs each time. There are hundred of these `MainParent` jobs running and every now and then are getting `Batch J5QLBrm-eRusYQ has finished, you cannot modify it anymore` in the `MainParent` and `ChildJob` both.

The wierd thing is at the very least `MainParent` should keep the batch open till it completes but its also throwing the same error when adding `ChildJob` jobs

```
batch = Sidekiq::Batch.new
batch.on(:complete, "AnotherWorker", mass_gifting_id: gifter.id, schedule_id: params[:schedule_id])

batch.jobs do
   MainParent.perform_async
end

class AnotherWorker < ApplicationWorker
  def perform
  end
  def on_complete(status, options)
  end
end

class MainParent < ApplicationWorker
  sidekiq_options retry: false, unique: true

  def perform
      buffer = []
      300000.time do |idx|
          buffer << idx
          if idx % 1000 == 0
              batch.jobs do
                 ChildJob.perform_async(buffer)
              end
          end
          buffer = []
      end
  end
end

class ChildJob < ApplicationWorker
   sidekiq_options retry: false, unique: false

   def perform(ids)
       batch.jobs do
            Sidekiq::Client.push_bulk('class' => LastWorker, 'args' => ids)
       end
   end
end
```

**Comment by y-shashank** [comment]
We tried to follow this 
>  It is safe to "reopen" the batch and add more jobs from within a job in that batch

Thats why we started the `MainParent` inside the batch and the batch was reopened inside the job running in that batch. 
Is this not the correct way ?

**Comment by mperham** [comment]
Ah, I missed that MainParent was part of a bigger batch. I can't explain why you are seeing that error.

I noticed you are setting `retry: false` and using a unique plugin. Neither are recommended because they can cause batch jobs to disappear and a batch to get stuck.

**Comment by y-shashank** [comment]
We had a serious memory bottleneck and pods were restarting due to this, after resolving that we are not seeing this error anymore.
We are still looking out for the same error but it all looks promising now
