### ISSUE TITLE
Diagnose negative pending on batches

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5659]
Ruby version: 2.7.6
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Pro 5.3.0 / Ent 2.3.0

Hi there!

How can I diagnose a negative pending batch assuming that my Redis is well configured (noeviction, plenty of memory available, no obvious exceptions)?

<img width="1074" alt="Screen Shot 2022-11-23 at 10 01 44" src="https://user-images.githubusercontent.com/26460/203553500-79531bb6-9133-484f-bf44-db682c8871d6.png">

Apparently the jobs did complete as expected but the negative count seems odd.

<img width="1256" alt="Screen Shot 2022-11-23 at 10 00 25" src="https://user-images.githubusercontent.com/26460/203553484-d076b37d-f0ad-4c57-bca7-fd967f8085dd.png">

Important to note that we eventually deploy or restart the process (through sidekiqswarm) when the memory limit is exceeded.

But since we are using super fetch, we expect this to not be an issue.

Any hints?

**Comment by sobrinho** [comment]
FWIW, we are using Heroku Redis.

_We upgraded it to the last version available since the last issue._

**Comment by mperham** [comment]
I've added some code to clamp the pending value to >= 0. If you'd like to beta test a 5.5.6 release, shoot me an email and tell me the best way to get it to you.

**Comment by sobrinho** [comment]
Let me try to upgrade to the latest version and I will let you know if it goes away.

I will reopen the ticket if that happens.
