### ISSUE TITLE
Feature request - `sidekiq-cron`-like "Enqueue Now" from WEB UI for Periodic Jobs

### ISSUE THREAD

**Issue by Epigene** [mperham/sidekiq#5660]
Ruby version: 2.7.6
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s):
sidekiq (5.2.10)
sidekiq-pro (5.0.0)
sidekiq-ent (1.8.1)

Hi, as far as I can tell from [Periodic Job docs](https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs) and enterprise gem change-logs, manual enqueueing is not available.  
Having it would help out testing efforts - no need to wait for the exact moment of scheduled execution, trigger now to check if job gets enqueued and does what's intended.
We don't intent to use this in prod environments (sidekiq web UI is not even mounted there).

**Comment by mperham** [comment]
No plans to add this. You can use IRB/the console, a rake task or automated testing.
