### ISSUE TITLE
Feature Request: Adding a checkpointing mechanism for jobs which can help in code observability.

### ISSUE THREAD

**Issue by yashdave00** [mperham/sidekiq#5662]
Ruby version: 2.5
Rails version: 6.2

Can we have a method to checkpoint a particular job and log the time each block of code between 2 checkpoints take?

Something like this:

```
class HardWorker
  def perform
     servicecall#1
     checkpoint#1
     servicecall#2
     checkpoint#2
     servicecall#3
     checkpoint#3
  end
end
```

In the sidekiq UI it will show the time it took between each checkpoint. Which will help determine the problem right from the sidekiq dashboard. Each checkpoint is a signal to capture and store the current time and storing it.

Happy to submit a PR if needed!

**Comment by mperham** [comment]
It sounds like you want an APM like Skylight, NewRelic, Scout, etc.
