### ISSUE TITLE
Feature Request: Add granted history to the limiters chart

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5663]
Ruby version: 2.7.6
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Pro 5.3.0 / Ent 2.3.0

Hi there again!

I can see how many were tried but not how many was actually granted, would be nice to have it in the same chart or in a different one (in the case of tries are too many which can potentially hide the granted line).

WDYT?

<img width="597" alt="Screen Shot 2022-11-23 at 16 56 08" src="https://user-images.githubusercontent.com/26460/203635354-5c16300a-d0d5-4ac2-8a8f-6edcbfe77f10.png">

**Comment by mperham** [comment]
This graph has been removed in 7.0.

**Comment by sobrinho** [comment]
Alright! 😭
