### ISSUE TITLE
Some workers stucks after deploy

### ISSUE THREAD

**Issue by boxcarracer** [mperham/sidekiq#5666]
Ruby version: 2.7.2
Rails version: 5.2.8
Sidekiq Pro version: 5.3.1

Hello! After updating sidekiq to version 6.4.1, we encountered a problem: after deploy our application to production and sidekiq rebooting some of workers can stuck and jobs hangs the worker for a long time. We made TTIN dumps. Help please!

https://gist.github.com/boxcarracer/1e05a8ae0b0b0ee7a4def567bbd39b1a

**Comment by mperham** [comment]
Look at all of the backtraces from the Threads marked "processor".

You're lazy requiring code in production. It appears that is leading to deadlock. See the backtraces for the code location.
