### ISSUE TITLE
sidekiq-ent's rolling restarts leaving zombie workers in 7.x

### ISSUE THREAD

**Issue by jdelStrother** [mperham/sidekiq#5667]
Ruby version: 3.1.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.1

I'm launching sidekiq with einhorn:

`einhorn -m manual -- bundle exec sidekiq -c 5`

and then asking it to perform a rolling restart with einhornsh:

`einhornsh --execute upgrade`

This results in a new upgraded leader process, but leaves behind a "stopping" process that never exits:

```
$ ps -ef | grep sidekiq
  501 78600 78598   0  5:25pm ttys001    0:04.87 sidekiq 7.0.1 web [0 of 5 busy] stopping
  501 78648 78598   0  5:25pm ttys001    0:03.14 sidekiq 7.0.1 web [0 of 5 busy] leader
```

I think the problem is in sidekiq-ent's restart.rb, which is raising a NoMethodError - 

```
          w = cli.launcher.manager.workers
                          ^^^^^^^^
Did you mean?  managers
               managers=
```

**Comment by mperham** [comment]
Ugh, thanks for finding that and the debugging. Will get this fixed later today.

**Comment by jdelStrother** [comment]
No rush if you're still in the middle of thanksgiving shenanigans

**Comment by jdelStrother** [comment]
Do you know when this might get a release? Just trying to figure out if we should monkeypatch it in the meantime

**Comment by jdelStrother** [comment]
Sorry, scratch that - I see 7.0.2 is out
