### ISSUE TITLE
Sidekiq::Limiter deployment for backoff change

### ISSUE THREAD

**Issue by xenyal** [mperham/sidekiq#5668]
Ruby version: 2.6.8
Rails version: 5.2.2
Sidekiq / Pro / Enterprise version(s): 5.2.9 / 1.8.1 / 5.0.0

Greetings! I had a question about Sidekiq::Limiter, if I have a bunch of them active in production, and I'd like to deploy a change to configure a difference in the `backoff` logic, will I need to recreate the limiter instances, or will it pick up the new backoff logic automatically? Not sure if limiter timings are stored in Redis, of if it's executed off the `backoff` proc every time.

Edit: Is it possible to update the existing limiters with the new backup proc, without doing it globally via `Sidekiq::Limiter.configure`?

**Comment by mperham** [comment]
It will update the limiter in redis when you create the instance. No worries.

**Comment by xenyal** [comment]
@mperham Thank you!

What if I'd like to set the `backoff` directly on the instance of a new limiter, instead of using the global configuration? Will that require deletion before the creation of the limiters?

**Comment by xenyal** [comment]
Ah my above question is answered in https://github.com/mperham/sidekiq/issues/4219.
