### ISSUE TITLE
Setting Retry Count for Jobs that already have more than max

### ISSUE THREAD

**Issue by OskarEichler** [mperham/sidekiq#5675]
We have some jobs in our retry queue that have more than 15 retries already. So we decided to update the job and only allow 7 max retries. However, it seems like jobs that already are above the max retry count ignore the max all together. New jobs that reach the max do get moved into dead queue, but the ones that are already above keep retrying. I assume Sidekiq checks for the exact number of retries, when really it should be the same number and anything above. 

```
    QUEUE = "tracks_#{Rails.env}"
    sidekiq_options queue: QUEUE.to_sym, retry: 7

```

Ruby version: 3.1.1
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 6.5.8

**Comment by fatkodima** [comment]
> but the ones that are already above keep retrying

Yes, because it uses the saved retry count when the job was enqueued - https://github.com/mperham/sidekiq/blob/c4dbc922305effd1db98527c293e0354456fc79a/lib/sidekiq/job_retry.rb#L141

New jobs get the new retry count.

**Comment by fatkodima** [comment]
Updated `retry_queue` will be picked up - https://github.com/mperham/sidekiq/blob/c4dbc922305effd1db98527c293e0354456fc79a/lib/sidekiq/job_retry.rb#L143, so I am thinking why we can't do the same with `retry` count? Seems reasonable to me to have this behavior.

@mperham Are you open for a PR?

**Comment by mperham** [comment]
I'm fine with the current behavior.
