### ISSUE TITLE
doubt about using cluster with redis and sidekiq config

### ISSUE THREAD

**Issue by andreleoni** [mperham/sidekiq#5676]
Hello, Is there a way of using redis cluster of aws with the latest sidekiq version?

How can I configure it?

**Comment by mperham** [comment]
Sidekiq does not support Redis Cluster. Only plain old Redis or Redis Sentinel.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Using-Redis#architecture
