### ISSUE TITLE
Jobs stuck for hours or days

### ISSUE THREAD

**Issue by weavermedia** [mperham/sidekiq#5683]
Ruby version: 3.1
Rails version: 7.0.3
Sidekiq / Pro / Enterprise version(s): 6.4.2

My jobs are getting stuck. Here is the TTIN gist. Am I correct in thinking it's getting stuck in the FFMPEG command run by Terrapin? Fetching an asset file?

https://gist.github.com/weavermedia/58bce73f84060d5158e0765d5a19fc69

**Comment by mperham** [comment]
It appears so. I would also guess you are launching Sidekiq incorrectly because the system seems to think it is bash.

**Comment by weavermedia** [comment]
I'm launching Sidekiq with the usual `worker: bundle exec sidekiq` on Procfile but in the Sidekiq job I'm using [Terrapin](https://github.com/thoughtbot/terrapin) gem to run FFMPEG on the command line. Is that what you're seeing?

**Comment by weavermedia** [comment]
Actually maybe it isn't stuck fetching an asset file. I think this line is just Terrapin waiting for FFMPEG to return a result:
`Dec 04 23:18:43 lingering-hill-8330 bash[42035]: /home/deploy/klippr-app/shared/bundle/ruby/3.1.0/gems/terrapin-0.6.0/lib/terrapin/command_line/multi_pipe.rb:43:in `read_stream'`

Also, not sure if this is relevant but when the jobs get stuck the server CPU drops to almost nothing, maybe 3-4%.

**Comment by mperham** [comment]
Looks like Terrapin is no longer maintained. There is an open PR for an issue that sounds like this problem.

https://github.com/thoughtbot/terrapin/pull/5

Surround the terrapin call with Timeout.timeout call as a last resort.
