### ISSUE TITLE
No more `Sidekiq.logger =` ?

### ISSUE THREAD

**Issue by DannyBen** [mperham/sidekiq#5686]
Ruby version: 3.1.3p185
Rails version: Not on rails
Sidekiq / Pro / Enterprise version(s): 7.0.2

I am getting an error in my setup when trying to assign my custom logger with:

```ruby
Sidekiq.logger = ...
# => NoMethodError: undefined method `logger=' for Sidekiq:Module
```

This used to work with 6.x

Looked for hints in [the upgrade guide](https://github.com/mperham/sidekiq/blob/main/docs/7.0-Upgrade.md), and the [Logging wiki](https://github.com/mperham/sidekiq/wiki/Logging), which still shows it should work.

**Comment by mperham** [comment]
You have to use configure_server:

```ruby
Sidekiq.configure_server do |config|
  config.logger = ...
end
```

**Comment by DannyBen** [comment]
Thank you.
So just note that the first section in the Logging wiki is incorrect (in more than one aspect... 😈): 

> Sidekiq's default logger is pretty simple:
> 
> ```ruby
> Sidekiq.logger = Logger.new(STDOUT)
> ```
> 
> Why make things more complex? YAGNI.
```

**Comment by mperham** [comment]
The wiki still mostly reflects Sidekiq 6.x as most people have not yet upgraded to 7.

**Comment by DannyBen** [comment]
Then perhaps the nice version-specific upgrade guides should mention notable changes? Would probably save time for both the owners and the users.

**Comment by mperham** [comment]
The biggest issue is that we don't really have an upgrade document that focuses on API changes. I'll go through the wiki and clean up things where I can.

**Comment by DannyBen** [comment]
> Send me a PR which has the fix you want to see? 

I can do that.

> The biggest issue is that we don't really have an upgrade document

Well, my two cents as a user:

1. When any release of any software, is immediately accompanied by updated documentation - it helps.
2. When there is a short upgrade guide between version - sort of like Rails is doing - it helps.

I treat documenting in the same way I treat specs. If the docs are not ready, the release is not ready.
