### ISSUE TITLE
Testing sidekiq_options

### ISSUE THREAD

**Issue by amy-hs** [mperham/sidekiq#5690]
Ruby version: 2.7.2
Rails version: 6.0.4.6
Sidekiq / Pro / Enterprise version(s): 5.2.10 / 4.0.3 / 1.7.2 (I know, gotta upgrade Sidekiq!)

This is more of a "is this possible?" question.

We're starting to migrate some workers to use Enterprise's unique jobs subsystem, but we want to test a couple of workers out first before completely cutting over to it. In doing so, we're thinking about using a feature flag (environment variable) to switch between the different `sidekiq_options`. As an example:

```
class MyWorker
  include Sidekiq::Worker

  define_sidekiq_options({ unique_for: 10.minutes }, { lock_ttl: 10.minutes })

  def perform
    # do the thing
  end
end
```

Then `define_sidekiq_options` is something like this:
```
def define_sidekiq_options(enterprise_options={}, original_options={})
  if ENV['ENABLE_ENTERPRISE_UNIQUE_JOBS'].to_b
    sidekiq_options unique_for: enterprise_options[:unique_for]
  else
    sidekiq_options lock_ttl: original_options[:lock_ttl]
  end
end
```

Is this a thing, modifying the `sidekiq_options` like that? Testing the different `sidekiq_options` in `rspec` is also a little strange because the subject class loads before running the code in the examples (which means stubbing the environment variable doesn't quite work).

Thanks for your thoughts!

**Comment by mperham** [comment]
You can just set both values and enable whichever middleware you want to use. Unknown options are ignored.

**Comment by amy-hs** [comment]
🤯 That actually makes life a lot easier. Thanks!
