### ISSUE TITLE
large job on ruby 3 creates runaway FIFO pipes

### ISSUE THREAD

**Issue by rhamilton-wombat** [mperham/sidekiq#5691]
Ruby version: 3.0.2
Rails version: none on this project
Sidekiq / Pro / Enterprise version(s): 4.2.10 (have also tried with 5.2.10) / 3.7.1 / 1.6.1

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.
We use a sidekiq.rb initializer, but here it is. Code is proprietary so some names have been altered and some (mostly logging) lines have been removed:

```
require_relative 'logger'
require_relative 'configuration'
require 'sidekiq-pro'
require "sidekiq-ent"

module Proprietary
  unless const_defined?(:ENVIRONMENT)
    ENVIRONMENT = ENV['RACK_ENV'] || ENV['RAILS_ENV'] || 'development'
  end
  # Sidekiq.client_middleware.add Sidekiq::Middleware::Client::Batch
  REDIS_URL = if ENV["REDIS_URL"].present?
                ENV["REDIS_URL"]
              else
                "redis://#{ENV["REDIS_SERVER"]}:#{ENV["REDIS_PORT"]}"
              end

  METRICS = Statsd.new "10.0.9.215", 8125

  Sidekiq::Enterprise.unique! unless Proprietary::ENVIRONMENT == "test"
  Sidekiq.configure_server do |config|
    # require 'sidekiq/pro/reliable_fetch'
    config.average_scheduled_poll_interval = 2
    config.redis = {
      namespace: Proprietary.config.SIDEKIQ_NAMESPACE,
      url: Proprietary::REDIS_URL
    }
    config.server_middleware do |chain|
      require 'sidekiq/middleware/server/statsd'
      chain.add Sidekiq::Middleware::Server::Statsd, :client => METRICS
    end
    config.error_handlers << Proc.new do |ex,ctx_hash|
      Proprietary.report_exception(ex, "Sidekiq", ctx_hash)
    end
    config.super_fetch!
    config.reliable_scheduler!
  end

  Sidekiq.configure_client do |config|
    config.redis = {
      namespace: Proprietary.config.SIDEKIQ_NAMESPACE,
      url: Proprietary::REDIS_URL,
      size: 15,
      network_timeout: 5
    }
  end
end
```

The error doesn't really have a backtrace other than the standard "too many open files" etc.

We are using Sidekiq to process a number of backend jobs. One in particular is used very heavily. All I can really say about it is that it sends emails. It doesn't do the email creation (that's a separate job), it just sends them. We spin up a new worker for each email that needs to be sent.

We are trying to upgrade to Ruby 3 and having problems, though. Ruby 2.6.8 has no issues; in 3 (as well as 2.7.3 IIRC), if there is a large number of queued workers, it will get through maybe 20K of them, then it will start hemorrhaging FIFO pipes, on the order of 300-1000 ever 5 seconds or so. Eventually it gets to the ulimit on the system (currently set at 64K) and all sockets/connections fail due to insufficient resources.

In trying to debug this issue I did a run with 90% of what the email worker does entirely commented out, so it does basically nothing except make a couple database queries and do some string templating. I thought I was getting somewhere with that approach, as one run (of 50K+ emails) succeeded without the pipe explosion. However, the next run (identical parameters) did wind up with the runaway pipes.

Profiling with rbspy and ruby-prof did not help much, as they primarily focus on the Sidekiq infrastructure, not the workers themselves. 

Looking through our code, I did see that nothing we wrote is ever using IO.* (e.g. IO.popen, IO.select, etc), so I don't see what could be causing the FIFO pipes. 

I did see https://github.com/mperham/sidekiq/wiki/Batches#huge-batches, which is not necessarily what we're doing. If you look at the code snippet below, we're basically creating one large batch. I'm not sure whether pushing jobs in bulk as per the link will help with the problem we're having, but I'm about to give it a try once I rework things a bit.

No matter what I do I can't seem to figure out the following:
1. What is making these pipes? Why are they being created?
2. What is the condition by which the pipes start getting made exponentially? There are two FIFO pipes that open when we start Sidekiq, but until enough work has been done, we don't see more than 2-6 pipes open generally.

Any advice is appreciated, even along the lines of where to look next, as I'm a bit stumped.

Code snippet (sanitized)

```
  def add_targets_to_batch
    @target_count  = targets.count
    queue_counter = 0
    batch.jobs do
      targets.shuffle.each do |target|
        send(target)
        queue_counter += 1
      end
    end
  end

  def send(campaign_target)
    TargetEmailWorker.perform_async(target[:id],
                                            guid,
                                            is_draft ? campaign_target[:email_address] : nil)
      begin
        Target.where(id: target[:id]).update(send_at: Time.now.utc)
      rescue Exception => ex
        
        Proprietary.report_exception(ex, self.class.name, { target_id: target[:id], guid: guid })
      end
    end
  end

```

**Comment by mperham** [comment]
Same, I can't imagine what would cause errors in FIFO pipes. Try refactoring the huge push per that wiki page as that's the only strange thing happening at that point in code: the atomic push could be enormous in size if you are pushing huge amounts of big jobs over a Unix socket to Redis, possibly overrunning a kernel limit? Are you using `unix://` to connect to Redis?

**Comment by rhamilton-wombat** [comment]
Thanks, haven't reached a resolution to the issue so far. But, my initial refactoring of the push has at least altered the rate at which the pipes are created, which is the first thing I've tried that has had any effect on that whatsoever. So I think I'm on the right track. 

AFAICT we're not using Unix sockets to connect to Redis, just HTTP to a local Redis (at least in the test server I'm using; in production we connect to an Elasticache instance).
