### ISSUE TITLE
Sidekiq::CurrentAttributes overwriting values on retry

### ISSUE THREAD

**Issue by fschwahn** [mperham/sidekiq#5692]
I'm running into a problem where `Sidekiq::CurrentAttributes` overwrites existing attributes when triggering a retry from Sidekiq UI. There are a few preconditions to trigger this.
1. I'm using Devise for authentication
2. Sidekiq UI is guarded by devise, eg:
```ruby
authenticate :user, ->(u) { u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end
```
3. `Current` is set in a warden callback, eg:
```ruby
Warden::Manager.prepend_after_set_user do |user, auth, opts|
  Current.user_id = user.id
end
```

That leads to the `cattr`-hash being overwritten with the user id of my admin user when clicking "Retry" in the admin interface. The reason for this is c92a521, which fixed #5090. Both issues could be solved by doing nothing if a `cattr`-hash already exists, eg. just guarding with `unless job.key?("cattr")`.

Maybe there's a different story why you decided to merge the hashes instead, but this lead to some quite surprising results on our end.

**Comment by mperham** [comment]
Oh wow, that's a crazy sequence of events but I can see how that would happen. Nice debugging!
