### ISSUE TITLE
Suggestion: Sidekiq 7 metrics history configurable in web UI

### ISSUE THREAD

**Issue by haffla** [mperham/sidekiq#5693]
Hello!

The new metrics in the web UI are great but only go back 60 minutes. I am not sure if this is an intentional limitation for the free Sidekiq version or for performance reasons? In the beginning it confused me a lot. I thought something is wrong because I knew for sure that some jobs had run last night. Only later I saw the tiny hint at the bottom of the page and realized that metrics only collect data from one hour ago.

What do you think about making it configurable in the web UI using a select input for instance with some standard options like 1h, 6h, 12h, 1day, 2days, 7days? Would you accept a PR? Again sorry if that's not something that you want to offer for users of the free version. Feel free to just close. Cheers.

**Comment by mperham** [comment]
We started small to make sure the feature was solid before expanding the scope. I don’t want to expand into a true APM competitor, data storage can really fill up Redis if we aren’t careful. Right now I think the data lives for 8 hours so we could expand the UI to display 1, 2, 4 and 8 hour windows.
