### ISSUE TITLE
Lock for a unique job

### ISSUE THREAD

**Issue by amy-hs** [mperham/sidekiq#5695]
Ruby version: 2.7.2
Rails version: 6.0.4.6
Sidekiq / Pro / Enterprise version(s): 5.2.10 / 4.0.3 / 1.7.2

Given a unique job, is it possible to search for that specific lock in Redis? We'd like to check if that lock exists in the Redis (and then released).

**Comment by mperham** [comment]
There is a public API, undocumented on purpose, but there to find if you look at the sidekiq-ent/unique.rb source.

**Comment by mperham** [comment]
And please note, your version of Sidekiq is over four years old and no longer supported.

**Comment by amy-hs** [comment]
As a follow up on how to use it: https://github.com/mperham/sidekiq/issues/2932#issuecomment-210602281
