### ISSUE TITLE
Sidekiq Pro Pause/Unpause queue takes effect only after restarting the process.

### ISSUE THREAD

**Issue by andreamoron** [mperham/sidekiq#5700]
Ruby version: 3.0.3
Rails version: 6.1.6.1
Sidekiq / Pro version(s): 6.4.0, pro: 5.3.1
Redis version> 5.0.7

Sidekiq Pro Pause/Unpause queue takes effect only after restarting the process. 

Steps to reproduce:
1. Pause queue using dashbord -> Queue shows "paused" label
2. Add a new job to the queue. The job is processed immediately
3. Go to "Busy" tab, stop the process and verify that is not there anymore
4. Add a new job to the queue. Now the queue has a job enqueued
5. Unpause the queue. Enqueued jobs remain in the queue
6. Go to "Busy" tab and stop the process again
7. Add a new job to the queue
8. Jobs are processed and the queue is emptied

Same behavior is observed using both basic_fetch and super_fetch

**Comment by mperham** [comment]
Have you tried upgrading to see if it was fixed in a later version?

**Comment by mperham** [comment]
This file might give you a hint. https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
