### ISSUE TITLE
Outdated instructions for max_retries config option in JobRetry class

### ISSUE THREAD

**Issue by severinkaelin** [mperham/sidekiq#5704]
Hello
First of all, thanks for the project, especially the recent 7.0 release.

While researching the `max_retries` option I came across the following comment in the codebase:

```ruby
# The default number of retries is 25 which works out to about 3 weeks
# You can change the default maximum number of retries in your initializer:
#
#   Sidekiq.options[:max_retries] = 7
```
[See in source](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/job_retry.rb#L52)

If I'm not mistaken, this no longer works with sidekiq 7. Due to the `Sidekiq::Config` change: https://github.com/mperham/sidekiq/blob/main/docs/capsule.md#sidekiqconfig

If this is indeed the case, it would be good if the comment in the code could be adjusted.

Thanks.

Kind regards
Severin

**Comment by mperham** [comment]
Send a PR which fixes it?

**Comment by severinkaelin** [comment]
> Send a PR which fixes it?

Sure, I'm happy to do that: https://github.com/mperham/sidekiq/pull/5705

**Comment by severinkaelin** [comment]
Closing as this has been implemented in PR (merged): https://github.com/mperham/sidekiq/pull/5705
