### ISSUE TITLE
Wrong retry when we overridden with set

### ISSUE THREAD

**Issue by hugobarthelemy** [mperham/sidekiq#5709]
Ruby version: 3.1.1
Rails version: 6.1.6.1
Sidekiq / Pro / Enterprise version(s): sidekiq 6.5.1 && sidekiq-pro 5.5.1

Hi,

I need to do something if it's the last retry of a job. For that, I check `_retry_count` and I need to access of retry for this job. In many cases, `get_sidekiq_options` are right. But when I set an override retry, `get_sidekiq_options` are wrong.

```ruby
class MyWorker
  include Sidekiq::Worker
  sidekiq_options queue: :low, retry: 8
  def perform
    puts self.class.get_sidekiq_options
  end
end
MyWorker.set(retry: 3).perform_async
=> {"retry"=>8, "queue"=>:low}
```

How can I access the right retry in all cases?

**Comment by mperham** [comment]
The job code in `perform` cannot access the current retry count. This is by design.

**Comment by mperham** [comment]
You can use the `sidekiq_retries_exhausted` block to define a special action to take upon job death.

```ruby
class MyJob
  include Sidekiq::Job

  sidekiq_retries_exhausted do |job, ex|
    puts "job #{job['jid']} just died"
  end

  def perform(...)
  end
end
