### ISSUE TITLE
Alpine 3.17 issue

### ISSUE THREAD

**Issue by jason-hobbs** [mperham/sidekiq#5711]
Ruby version: 3.1.3
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.2

Using docker and alpine 3.17 I am getting an error when sending email through Sidekiq:

[core-575d7955dd-grwgs.log](https://github.com/mperham/sidekiq/files/10323445/core-575d7955dd-grwgs.log)

I don't have this issue with Alpine 3.16

**Comment by jason-hobbs** [comment]
I am assuming this has to do with 3.17 including openssl 3

**Comment by mperham** [comment]
As you point out this has nothing to do with Sidekiq, it's an issue with Ruby and the container environment.
