### ISSUE TITLE
periodic jobs got killed by memory limits

### ISSUE THREAD

**Issue by stereosupersonic** [mperham/sidekiq#5713]
this is a more general issue than a specific one for sidekiq. 

we have a periodic sidekiq job that does some long-running CSV processing (some memory leaks in included 😉 ) 
In the beginning everything worked perfect, then the files got bigger, and we run into our Kubernetes memory limit.
the pod with the sidekiq job got killed without any exception, and we did notice this for a while because no exception or dead job is visible. 

Is there a pattern or workflow to detect not running (or silently failing) periodic jobs, or is there a way that sidekiq detect if a pod got killed?

**Comment by mperham** [comment]
No, there's no way for sidekiq to detect this or prevent it from happening. Sidekiq Pro can rescue the orphaned job and restart it later.

**Comment by fatkodima** [comment]
Not directly answering your question, but you can consider the `sidekiq-iteration` gem for the long running tasks and get away with many mentioned problems. It also has an iterator for a CSV - https://github.com/fatkodima/sidekiq-iteration#iterating-over-csv.
