### ISSUE TITLE
Stopping embedded server from the Web UI kills the whole process

### ISSUE THREAD

**Issue by mikebaldry** [mperham/sidekiq#5714]
Ruby version: 2.7.5p203
Rails version: 6.0.4.8
Sidekiq / Pro / Enterprise version(s): 7.0.2

As per title - if you stop sidekiq via the Web UI stop button, the web server it is embedded in also ends.

I would expect either:
1) embedded servers don't have the option to be controlled like this - they're embedded as part of the app so it doesn't really make sense
2) sidekiq stops but the process keeps running, this would probably leave an app that depends on an embedded sidekiq in a broken state though

**Comment by mperham** [comment]
Yeah, this falls into the category of "probably don't allow this". An embedded instance should not control the process it is running in so I'd be in favor of disabling these buttons. If you're running inside puma, you need to use puma's tools to manage the process.

**Comment by mikebaldry** [comment]
Great. This is what I was also thinking. Please see PR
