### ISSUE TITLE
Do not allow creating batches that have no callbacks

### ISSUE THREAD

**Issue by 97jaz** [mperham/sidekiq#5715]
Ruby version: n/a
Rails version: n/a
Sidekiq / Pro / Enterprise version(s): 7.0.2 / 7.0.4 / 7.0.2

This issue comes out of a separate discussion with mperham. My company started getting an error that's caused by `sidekiq-pro` trying to parse `nil` as JSON. The `nil` value in this case represents that callbacks for a batch. Mike noted that batches without callbacks are useless, and, therefore, the library should not allow batches to be created without at least one callback.

**Comment by mperham** [comment]
I've thought about this some more and I'm wavering in my stance. It's possible the caller could want to dynamically define a callback and have some edge cases where they actually don't need a callback for the batch. For instance, if they want to define a callback only if there is a live WebSocket listener.

The callback hash should never be nil but that doesn't mean it can't be empty. We should definitely find any edge cases that could lead to a `nil` callback hash.
