### ISSUE TITLE
Sidekiq version for rails 4 for parallel jobs

### ISSUE THREAD

**Issue by sathishkumar-ayla** [mperham/sidekiq#5718]
Ruby version: 2.2.6
Rails version: 4.1.16
Sidekiq: 5.0.0
Sidekiq-pro: 3.4.2 

Sidekiq config
:verbose: false
:concurrency: 5
:timeout: 30
:queues:
  - default
development:
  :verbose: true
  :concurrency: 5
  
Is the above requirements are sufficient to run multiple jobs without the jobs getting stuck?

**Comment by mperham** [comment]
No jobs should ever get stuck. You have a bug. Use the TTIN signal.

**Comment by sathishkumar-ayla** [comment]
Bug on the Sidekiq config???

**Comment by mperham** [comment]
I can't possibly know what the bug is. That's why you debug. Read about stuck jobs on the Problems and Troubleshooting wiki page.
