### ISSUE TITLE
Upgrading Sidekiq to 6.5.8 Caused SuperFetch to Find Old Orphaned Jobs

### ISSUE THREAD

**Issue by Jhowden** [mperham/sidekiq#5719]
Ruby version:  2.7.5
Rails version: 6.1.6.1
Sidekiq / Pro / Enterprise version(s): 5.2.10/5.0.0/1.8.1

Sidekiq initializer
```
Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  config.redis = redis_options

  config.options[:job_logger] = Company::Sidekiq::JobLogger
end
```

I recently attempted to update our Sidekiq versions to 6.5.8/5.5.8/2.5.3 and noticed that on the deploy SuperFetch recovered 2,000+ orphaned jobs and then tried to run those jobs again. It is hard to get the full analysis but glancing through the jobs it seems like the majority were part of batches and were most likely orphaned during a deploy while others were one off jobs that for some reason were orphaned. Looking at the enqueued_at times I have found jobs that go all the way back from March 2022 and I would say most of the jobs are over 30 days old. If I look at our logs for deploys that happened before the Sidekiq upgrade I do not see SuperFetch recovering any orphan jobs (and I can confirm that some of our batches have pending job totals but whose jids don't exist in the queue so the batch is stuck).

My main question is if this is expected behavior with the Sidekiq upgrade? Base on this [issue](https://github.com/mperham/sidekiq/issues/5470) it seems like you weren't so surprised that this happened with the upgrade. I was surprised to find such old orphaned jobs still hanging around and being re-enqueued because I thought dead/orphaned jobs would have been cleared after 30 days. I unfortunately had to rollback the Sidekiq upgrade since something was not working correctly but now I am afraid that other orphaned jobs will be re-enqueued again. 

Sidenote, I have read the batches wiki and the deployment FAQ about why jobs can be lost and how batches can have negative pending totals and it isn't great that it is happening. Working my way on fixing those issues but I am taking it one step at a time!

**Comment by mperham** [comment]
I'm sorry for the pain. That's a big upgrade, to go from Pro 5.0.0 (Sept 2019) to 5.5.8 (Dec 2022), over three years of releases. It sounds like maybe there was a super_fetch bugfix which triggered this. I'd encourage you to upgrade at least once per year, especially if you're running a x.0.0 release which is more likely to have new bugs.

Queues live forever in Redis and do not expire. This means that jobs could be recovered months or years later, in unexpected edge cases like this.

**Comment by Jhowden** [comment]
Gotcha, thank you for the reply!
