### ISSUE TITLE
Individual job metrics in standalone WebUI yields NoMethodError

### ISSUE THREAD

**Issue by marclennox** [mperham/sidekiq#5720]
Ruby version: 3.2
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 7.0

When clicking on an individual metrics link for a particular job, it throws a 500 with the following error in the Rack server process.

#<NoMethodError: undefined method `titleize' for "metrics":String>

Here's the config.ru I'm using

https://github.com/tenstartups/sidekiq-web/blob/master/config.ru

**Comment by mperham** [comment]
Fixed on main.

**Comment by marclennox** [comment]
👍
