### ISSUE TITLE
No file descriptors available - getaddrinfo (RedisClient::CannotConnectError)

### ISSUE THREAD

**Issue by marclennox** [mperham/sidekiq#5721]
Ruby version: 3.2
Rails version: 7.0
Sidekiq / Pro / Enterprise version(s): 7.0

I'm seeing quite a few errors in our production environment since updating to Sidekiq 7.0.  The upgrade was also coincident with upgrading Redis to 7.0.  It seems to happen somewhat randomly, and always in bursts where we get a whole bunch of errors from multiple Sidekiq processes and threads, then it quiets down for a while until the next time.

I'm guessing this is not a Sidekiq issue but just looking for some guidance on where to start looking for the problem.

Thanks.

```
Errno::EMFILE: No file descriptors available - getaddrinfo (Errno::EMFILE)
  from socket.rb:231:in `getaddrinfo'
  from socket.rb:231:in `foreach'
  from socket.rb:635:in `tcp'
  from redis-client (0.11.2) lib/redis_client/ruby_connection.rb:49:in `initialize'
  from redis-client (0.11.2) lib/redis_client.rb:660:in `new'
  from redis-client (0.11.2) lib/redis_client.rb:660:in `block in connect'
  from redis-client (0.11.2) lib/redis_client/middlewares.rb:12:in `connect'
  from redis-client (0.11.2) lib/redis_client.rb:659:in `connect'
  from redis-client (0.11.2) lib/redis_client.rb:653:in `raw_connection'
  from redis-client (0.11.2) lib/redis_client.rb:620:in `ensure_connected'
  from redis-client (0.11.2) lib/redis_client.rb:204:in `call'
  from sidekiq (7.0.2) lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'
  from app/poros/sidekiq_unique_job.rb:90:in `release_lock'
  from lib/sidekiq/sidekiq_unique_jobs_middleware.rb:53:in `ensure in call'
  from lib/sidekiq/sidekiq_unique_jobs_middleware.rb:53:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sentry-sidekiq (5.7.0) lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:24:in `track'
  from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:120:in `call'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:180:in `invoke'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:173:in `block in process'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:113:in `local'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/rails.rb:15:in `block in call'
  from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (7.0.2) lib/sidekiq/rails.rb:14:in `call'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:267:in `stats'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:80:in `global'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:128:in `block in dispatch'
  from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:127:in `dispatch'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:172:in `process'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:82:in `process_one'
  from sidekiq (7.0.2) lib/sidekiq/processor.rb:72:in `run'
  from sidekiq (7.0.2) lib/sidekiq/component.rb:8:in `watchdog'
  from sidekiq (7.0.2) lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by mperham** [comment]
Maybe use ‘lsof’ on the process?

On Mon, Jan 9, 2023, at 08:44, Marc Lennox wrote:
> 
> 
> 
> Ruby version: 3.2
> Rails version: 7.0
> Sidekiq / Pro / Enterprise version(s): 7.0
> 
> I'm seeing quite a few errors in our production environment since updating to Sidekiq 7.0. The upgrade was also coincident with upgrading Redis to 7.0. It seems to happen somewhat randomly, and always in bursts where we get a whole bunch of errors from multiple Sidekiq processes and threads, then it quiets down for a while until the next time.
> 
> I'm guessing this is not a Sidekiq issue but just looking for some guidance on where to start looking for the problem.
> 
> Thanks.
> 
> `Errno::EMFILE: No file descriptors available - getaddrinfo (Errno::EMFILE)
>   from socket.rb:231:in `getaddrinfo'
>   from socket.rb:231:in `foreach'
>   from socket.rb:635:in `tcp'
>   from redis-client (0.11.2) lib/redis_client/ruby_connection.rb:49:in `initialize'
>   from redis-client (0.11.2) lib/redis_client.rb:660:in `new'
>   from redis-client (0.11.2) lib/redis_client.rb:660:in `block in connect'
>   from redis-client (0.11.2) lib/redis_client/middlewares.rb:12:in `connect'
>   from redis-client (0.11.2) lib/redis_client.rb:659:in `connect'
>   from redis-client (0.11.2) lib/redis_client.rb:653:in `raw_connection'
>   from redis-client (0.11.2) lib/redis_client.rb:620:in `ensure_connected'
>   from redis-client (0.11.2) lib/redis_client.rb:204:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'
>   from app/poros/sidekiq_unique_job.rb:90:in `release_lock'
>   from lib/sidekiq/sidekiq_unique_jobs_middleware.rb:53:in `ensure in call'
>   from lib/sidekiq/sidekiq_unique_jobs_middleware.rb:53:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
>   from sentry-sidekiq (5.7.0) lib/sentry/sidekiq/sentry_context_middleware.rb:26:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
>   from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:24:in `track'
>   from sidekiq (7.0.2) lib/sidekiq/metrics/tracking.rb:120:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
>   from sidekiq (7.0.2) lib/sidekiq/middleware/chain.rb:180:in `invoke'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:173:in `block in process'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:113:in `local'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/rails.rb:15:in `block in call'
>   from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
>   from activesupport (7.0.4) lib/active_support/reloader.rb:72:in `block in wrap'
>   from activesupport (7.0.4) lib/active_support/execution_wrapper.rb:92:in `wrap'
>   from activesupport (7.0.4) lib/active_support/reloader.rb:71:in `wrap'
>   from sidekiq (7.0.2) lib/sidekiq/rails.rb:14:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:267:in `stats'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:13:in `call'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/job_retry.rb:80:in `global'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:128:in `block in dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/job_logger.rb:39:in `prepare'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:127:in `dispatch'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:172:in `process'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:82:in `process_one'
>   from sidekiq (7.0.2) lib/sidekiq/processor.rb:72:in `run'
>   from sidekiq (7.0.2) lib/sidekiq/component.rb:8:in `watchdog'
>   from sidekiq (7.0.2) lib/sidekiq/component.rb:17:in `block in safe_thread'
`

**Comment by mperham** [comment]
I can't think of any reason why the open file count would increase and I'm not aware of any issues with open files in Sidekiq 7.

**Comment by marclennox** [comment]
Bumping up the nofile ulimit on the Fargate task definition seems to have done the trick, thanks.

**Comment by kalleth** [comment]
I'm running into a similar issue, which seems to take about a week to hit the 4096 file descriptor limit and then fail. I'm also using fargate, but using Sidekiq 6.5.8. An upgrade to 7.0 is on the list shortly.

```
/app # lsof | grep ruby | grep socket | wc -l
845
/app # lsof | grep ruby | grep socket | head
1       /usr/local/bin/ruby     6       socket:[20865]
1       /usr/local/bin/ruby     9       socket:[20122]
1       /usr/local/bin/ruby     10      socket:[20128]
1       /usr/local/bin/ruby     11      socket:[20872]
1       /usr/local/bin/ruby     12      socket:[66695]
1       /usr/local/bin/ruby     13      socket:[20874]
1       /usr/local/bin/ruby     14      socket:[20875]
1       /usr/local/bin/ruby     15      socket:[114578]
1       /usr/local/bin/ruby     16      socket:[84396]
1       /usr/local/bin/ruby     17      socket:[27065]
```

This is after 2 days of runtime. Similar to @marclennox , I'm trying to figure out where to investigate next. It does appear to be limited to sidekiq - on our `web`, `clock` and `sneakers` containers, I get:

```
web# lsof | grep ruby | grep socket | wc -l
38

clock# lsof | grep ruby | grep socket | wc -l
2

sneakers# lsof | grep ruby | grep socket | wc -l
37
```

So it's definitely the container that runs sidekiq that's leaving open sockets. That said, the `sidekiq` container - the jobs it runs - do a lot of web scraping / API requesting - so it could be that (the type of workloads run by this process), and nothing to do with sidekiq/redis -- I just don't know how to investigate that further. Any pointers that would help me rule out Sidekiq as a culprit?

**Comment by marclennox** [comment]
FWIW, I haven't had any issues since bumping up the file descriptors, and I'm running millions of jobs per day through sidekiq.

**Comment by kalleth** [comment]
@marclennox Yeah, I'm not entirely sure that this is a sidekiq issue. I'm wondering if one of my jobs themselves is causing sockets to leak / not close properly. I guess I'm hoping that Mike has seen something similar before and might have some insight into how to debug which one it is? 😅

**Comment by mperham** [comment]
In a typical Unix environment, I'd use root and `lsof` to debug which FDs are open for a process, try to find a pattern for which sockets are oversubscribed and that usually gives me the clue for which code to focus on. I don't know of any open issues for FD leaks.

**Comment by kalleth** [comment]
So, this is interesting. It's definitely an open socket to the redis connection. After `apk add lsof` to install a more detailed version of LSOF, I see:

```
/app # lsof | grep ruby | grep redis | wc -l
16492

/app # lsof | grep ruby | grep redis | head
ruby         1                root    9u     IPv4              20122      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51584->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   10u     IPv4              20128      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51590->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   11u     IPv4              20872      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51606->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   12u     IPv4              66695      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:35022->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   13u     IPv4              20874      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51614->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   14u     IPv4              20875      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:51620->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   15u     IPv4             114578      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:58826->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   16u     IPv4              84396      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:38752->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   17u     IPv4              27065      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:45260->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
ruby         1                root   18u     IPv4              24787      0t0    TCP ip-<CONTAINER_IP>.eu-west-1.compute.internal:47582->ip-<ELASTICACHE_IP>.eu-west-1.compute.internal:redis (ESTABLISHED)
```

So this is _definitely_ narrowed down to the redis connection to our Elasticache instance.

**Comment by mperham** [comment]
Please make sure you're running something released recently. There have been bugs fixed in Redis connection pooling since 7.0.

**Comment by kalleth** [comment]
@mperham -- thanks, I think I just got there myself too, looking at https://github.com/redis/redis-rb/issues/524 (from 2016!).

We're running Sidekiq 6.5.8 (Nov '22) and redis-rb 4.8.1 (Feb '23), so reasonably recent. I can't upgrade to 7.x because I'm blocked by `sidekiq-throttled`, and can't afford sidekiq enterprise to replace the functionality.

So, it doesn't seem like there's a solve for me for sidekiq 6.x. The only solution is to upgrade to 7.x. I guess I'm going to have to dive in to see if I can PR on `sidekiq-throttled` and make it compatible with 7.x.

**Comment by mperham** [comment]
@kalleth I just realized this is @marclennox's closed issue. Please open your own issue describing your problem and system.
