### ISSUE TITLE
Sidekiq::Batch::NoSuchBatch: Couldn't find Batch batch_id in redis

### ISSUE THREAD

**Issue by lordstingray** [mperham/sidekiq#5722]
Ruby version: 3.1
Rails version: 7
Sidekiq Pro version: 7

After just updating my gem version to 7.0, I was unable to figure out the probable reason that is causing my specs to fail. I constantly keep getting this exception **Sidekiq::Batch::NoSuchBatch: Couldn't find Batch batch_id in redis**. To debug this i have couple of following things:

- Verify redis is connected.
- Include Client or server middleware in my custom middleware.
- Verify if specs are not using inline or fake.

I am running sidekiq in embedded mode so sidekiq.yml is of no concern, but here is my configuration files:

```
# config/puma.rb
on_worker_boot do
  ActiveRecord::Base.establish_connection

  if Rails.env.development?
    sidekiq = Sidekiq.configure_embed do |config|
      config.queues = my_queues
      config.concurrency = 5
    end

    sidekiq.run
  end
end



# initializer/sidekiq.rb
module Sidekiq::Middleware::Server
  class CustomMiddleware
    include Sidekiq::ServerMiddleware

    def set_retry
    end
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add Sidekiq::Middleware::Server::CustomMiddleware
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end

Sidekiq.strict_args!
```

**Comment by mperham** [comment]
Show me the full backtrace. 

On Wed, Jan 11, 2023, at 03:37, lordstingray wrote:
> 
> 
> 
> Ruby version: 3.1
> Rails version: 7
> Sidekiq Pro version: 7
> 
> After just updating my gem version to 7.0, I was unable to figure out the probable reason that is causing my specs to fail. I constantly keep getting this exception *Sidekiq::Batch::NoSuchBatch: Couldn't find Batch batch_id in redis*. To debug this i have couple of following things:
> 
>  * Verify redis is connected.
>  * Include Client or server middleware in my custom middleware.
>  * Verify if specs are not using inline or fake.
> I am running sidekiq in embedded mode so sidekiq.yml is of no concern, but here is my configuration files:
> 
> `# config/puma.rb
> on_worker_boot do
>   ActiveRecord::Base.establish_connection
> 
>   if Rails.env.development?
>     sidekiq = Sidekiq.configure_embed do |config|
>       config.queues = my_queues
>       config.concurrency = 5
>     end
> 
>     sidekiq.run
>   end
> end
> 
> 
> 
> # initializer/sidekiq.rb
> module Sidekiq::Middleware::Server
>   class CustomMiddleware
>     include Sidekiq::ServerMiddleware
> 
>     def set_retry
>     end
>   end
> end
> 
> Sidekiq.configure_server do |config|
>   config.server_middleware do |chain|
>     chain.add Sidekiq::Middleware::Server::CustomMiddleware
>   end
> end
> 
> Sidekiq.configure_client do |config|
>   config.redis = { url: 'redis://localhost:6379/0' }
> end
> 
> Sidekiq.strict_args!
`

**Comment by lordstingray** [comment]
```
Sidekiq::Batch::NoSuchBatch:
       Couldn't find Batch cIEh0DeF6yJ3KQ in redis
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/sidekiq-pro-7.0.5/lib/sidekiq/batch.rb:77:in `initialize'
# ./app/models/dummy.rb:49:in `new'
# ./app/models/dummy.rb:49:in `cancel!'
# ./app/controllers/admin/dummy_controller.rb:26:in `cancel'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:215:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb:53:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
# ./app/controllers/concerns/current.rb:14:in `dummy_method'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:233:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:151:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionview-7.0.4/lib/action_view/rendering.rb:39:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/metal.rb:188:in `dispatch'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:601:in `block in process_controller_response'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:591:in `wrap_execution'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:601:in `process_controller_response'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:511:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `catch'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/gon-6.4.0/lib/gon/spec_helpers.rb:15:in `process'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:412:in `post'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
# ./spec/controllers/admin/dummy_controller_spec.rb:88:in `block (4 levels) in <top (required)>'
# ./spec/controllers/admin/dummy_controller_spec.rb:87:in `block (3 levels) in <top (required)>'
# ./spec/support/helpers/database_cleaner.rb:16:in `block (3 levels) in <top (required)>'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:35:in `cleaning'
# ./spec/support/helpers/database_cleaner.rb:16:in `block (2 levels) in <top (required)>'
# /Users/lordstingray/.rvm/gems/ruby-3.1.2@my_project/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

**Comment by mperham** [comment]
Is it possible you’re trying to cancel a batch which is already finished? Generally you want to use the status object to cancel a batch. 

On Wed, Jan 11, 2023, at 04:17, lordstingray wrote:
> 
> 
> `Sidekiq::Batch::NoSuchBatch:
>        Couldn't find Batch cIEh0DeF6yJ3KQ in redis
> # ***@***.***_project/gems/sidekiq-pro-7.0.5/lib/sidekiq/batch.rb:77:in `initialize'
> # ./app/models/dummy.rb:49:in `new'
> # ./app/models/dummy.rb:49:in `cancel!'
> # ./app/controllers/admin/dummy_controller.rb:26:in `cancel'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:215:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb:53:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
> # ./app/controllers/concerns/current.rb:14:in `dummy_method'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:233:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
> # ***@***.***_project/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:151:in `process'
> # ***@***.***_project/gems/actionview-7.0.4/lib/action_view/rendering.rb:39:in `process'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/metal.rb:188:in `dispatch'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:601:in `block in process_controller_response'
> # ***@***.***_project/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:591:in `wrap_execution'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:601:in `process_controller_response'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:511:in `process'
> # ***@***.***_project/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
> # ***@***.***_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `block in process'
> # ***@***.***_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `catch'
> # ***@***.***_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
> # ***@***.***_project/gems/devise-4.8.1/lib/devise/test/controller_helpers.rb:35:in `process'
> # ***@***.***_project/gems/gon-6.4.0/lib/gon/spec_helpers.rb:15:in `process'
> # ***@***.***_project/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:412:in `post'
> # ***@***.***_project/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
> # ./spec/controllers/admin/dummy_controller_spec.rb:88:in `block (4 levels) in <top (required)>'
> # ./spec/controllers/admin/dummy_controller_spec.rb:87:in `block (3 levels) in <top (required)>'
> # ./spec/support/helpers/database_cleaner.rb:16:in `block (3 levels) in <top (required)>'
> # ***@***.***_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
> # ***@***.***_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
> # ***@***.***_project/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:35:in `cleaning'
> # ./spec/support/helpers/database_cleaner.rb:16:in `block (2 levels) in <top (required)>'
> # ***@***.***_project/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
`

**Comment by lordstingray** [comment]
I figured it out why was this happening, with sidekiq version 7, seems like 1.day, 1.hour and other timestamps like these were not processable. Converted them into second while pushing to redis. It is most likely happening by redis updates with version 7. Thanks @mperham for helping out 👍🏻 

PS: I am closing this issue :)
