### ISSUE TITLE
[Question] Sidekiq pro 5.5.8 changelog?

### ISSUE THREAD

**Issue by daande** [mperham/sidekiq#5723]
Just bumping some gems and pulled `Installing sidekiq-pro 5.5.8 (was 5.5.5)` however I can't find an accompanying changelog?

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md#557-558

**Comment by daande** [comment]
is this meant for 5.5.8? https://github.com/mperham/sidekiq/commit/93a8e23a1d805c993798fdd1595749b490b8a065

**Comment by daande** [comment]
Thanks @mperham I looked a minute ago and couldn't find 5.5.8 must be a race condition 😆
