### ISSUE TITLE
Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>

### ISSUE THREAD

**Issue by rainyhuynh** [mperham/sidekiq#5724]
Hello,

I have issue in mailers in sidekiq. When I has job in sidekiq, some emails has attachment automatically change to retries and sent back many times until end of max retries in _sidekiq.yml_  (max_retries = 5)

config/sidekiq.yml
`
:verbose: false
:concurrency: 10
:timeout: 25
:max_retries: 5
:backtrace: true
#:dynamic: true
#:dynamic_every: true
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:schedule:
  folders_cleanup:
    class: FoldersCleanupJob
    queue: :scheduler
    cron: '0 18 * * *' # At 06:00 PM

  waiver_reminder:
    class: Crm::WaiverReminderJob
    queue: :scheduler
    cron: '0 18 * * *' # At 06:00 PM

development:
  :queues:
    - development_mailers
    - default
    - scheduler
    - development_active_storage_purge
    - development_active_storage_analysis
production:
  :concurrency: 10
  :queues:
    - production_mailers
    - default
    - scheduler
    - production_active_storage_purge
    - production_active_storage_analysis
`

Error with some dead job in Production environment
<img width="1184" alt="Screen Shot 2023-01-12 at 16 43 57" src="https://user-images.githubusercontent.com/21411220/212033379-2380e514-5708-4ac2-8847-ec613f358ba9.png">

I try many ways to upgrade sidekiq to ~7.0.2 or another but some errors and not figure out yet. 

This is error when update sidekiq 7.0.2 => **TypeError: no implicit conversion of Sidekiq::Config into Hash**
![image](https://user-images.githubusercontent.com/21411220/212032061-db60fc6e-b3e9-4bb7-b1e0-0959f44db2a2.png)

#config/initializers/sidekiq.rb
`require 'sidekiq'
require 'sidekiq-status'

sidekiq_redis_options = {
  url: ENV["REIDS_URL_SIDEKIQ"],
  id: "Sidekiq-server-PID-#{::Process.pid}",
  namespace: "sidekiq_app_name_#{Rails.env}",
  network_timeout: 60
}

if ENV["REIDS_PASSWORD"]
  sidekiq_redis_options[:password] = ENV["REIDS_PASSWORD"]
end

Sidekiq.configure_server do |config|
  config.redis = sidekiq_redis_options
  Sidekiq::Status.configure_server_middleware config, expiration: 30.minutes
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_redis_options
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes
end
`

Please give me solution to solve it.

Thank you very much.
Rainy

sidekiq (6.5.8)
ruby 2.7.2p137 
Rails 6.0.6

**Comment by liijunwei** [comment]
noticed that you're using [sidekiq-scheduler 4.0.2](https://rubygems.org/gems/sidekiq-scheduler)
- from 4.0.3, it requires sidekiq < 7(I guess this is a fixup)
- from 5.0, it requires sidekiq < 8

so probably it is a compatiblilty issue between sidekiq and sidekiq-scheduler

**Comment by liijunwei** [comment]
- another compatiblilty issue between sidekiq7 and sidekiq-status2: sidekiq7 replaced redis-rb with redis-client
    - https://github.com/mperham/sidekiq/commit/0b3e4c2724b2440e6fff7ed56407e82947919a64

suggestion would be:
- [Kill Your Dependencies | Mike Perham](https://www.mikeperham.com/2016/02/09/kill-your-dependencies/)
- read error messages and backtraces more carefully...

**Comment by rainyhuynh** [comment]
@liijunwei thank you for your support.

Have a nice day.
