### ISSUE TITLE
1-weighted queues are processing in strict queue order

### ISSUE THREAD

**Issue by BobbyMcWho** [mperham/sidekiq#5726]
Ruby version: 2.7.6
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7.0.3 / 7.0.5 / 7.0.3

```yaml
---
:concurrency: 5
:max_retries: 7
:verbose: false
:timeout: 160
:queues:
  - [bulk_audit, 1]
  - [sync, 1]
  - [sync_appts, 1]
  - [sync_patient_recalls, 1]
  - [sync_patients, 1]
  - [sync_unresolved, 1]
  - [sync_postprocessing, 1]
```

Expected behavior: When all queues have 1 weight, queues process at a rate that is distributed across queues
Observed behavior: Queues are processing in strict queue order. 

On Sidekiq 7.0.2 / 7.0.3 / 7.0.2, we noticed that queues were processing in strict queue order
![image](https://user-images.githubusercontent.com/6934825/212126732-9b529403-51fc-43bc-81e2-729dba7ea2d6.png)

Upon investigation, it appeared that [this commit](https://github.com/mperham/sidekiq/commit/1b83a152786ed382f07fff12d2608534f1e3c922) broke it (and was released w/ sidekiq 7, but [this commit](https://github.com/mperham/sidekiq/commit/52d2a6f155b909239b2778ca5d2dad2a5d263022) appeared like it would fix it, which was released in 7.0.3 yesterday. 

However, after deploying 7.0.3 / 7.0.5 / 7.0.3 last night, we're still experiencing the same behavior: 
![image](https://user-images.githubusercontent.com/6934825/212131046-a624f702-053f-4a3d-990c-a85bd286654d.png)

**Comment by BobbyMcWho** [comment]
I think line 44 of super_fetch.rb in sidekiq-pro needs updated to use `capsule.mode` instead of the queue size vs unique check

**Comment by mperham** [comment]
That looks right to me. Pro 7.0.6 coming tomorrow.

**Comment by BobbyMcWho** [comment]
Hey @mperham, just wanted to follow up on this, it doesn't appear sidekiq-pro 7.0.6 has been pushed to the enterprise gem host yet

**Comment by mperham** [comment]
thanks for the reminder, pushed.
