### ISSUE TITLE
Suggestion: Use (B)ZPOPMIN instead of ZRANGEBYSCORE

### ISSUE THREAD

**Issue by stepantubanov** [mperham/sidekiq#5732]
To pop a job by time Sidekiq uses Lua script with `ZRANGEBYSCORE` and `ZREM`, which is called from here:
https://github.com/mperham/sidekiq/blob/c4dbc922305effd1db98527c293e0354456fc79a/lib/sidekiq/scheduled.rb#L52-L64

Since Sidekiq 7 now requires Redis 6.2, it could use [`ZPOPMIN`](https://redis.io/commands/zpopmin/) to do that. And perhaps [`BZPOPMIN`](https://redis.io/commands/bzpopmin/) could be used instead of polling?

**Comment by mperham** [comment]
> Since Sidekiq 7 now requires Redis 6.2, it could use [ZPOPMIN](https://redis.io/commands/zpopmin/) to do that.

Good idea. Send a PR?

> And perhaps [BZPOPMIN](https://redis.io/commands/bzpopmin/) could be used instead of polling?

I'm not sure how this would work. The MIN changes as time passes...
