### ISSUE TITLE
Anyway to ensure fixed hosts for sidekiq webserver

### ISSUE THREAD

**Issue by kutysam** [mperham/sidekiq#5735]
I can't seem a way to enable fixed hostnames for sidekiq.
For example, django has ALLOWED_HOSTS which ensures some security as we can only access the django app on specific hostnames.

This will decrease attacks such as host header injection.

**Comment by mperham** [comment]
Are you talking about the Sidekiq Web UI? It's a Rack app so you can use any Rack middleware for that type of requirement.

**Comment by kutysam** [comment]
Yeap, the web UI. I'll check up on it. Could we leave this issue open for about 2-3 days. If i find a solution, i'll write it down here too. then we can close it.

**Comment by nateberkopec** [comment]
If this is a Rails app, you're looking for [this](https://api.rubyonrails.org/classes/ActionDispatch/HostAuthorization.html).

If it's a Rack app, like Sinatra or Hanami etc, you will have to write your own middleware. I took a quick look and did not find one available as a Ruby gem.

**Comment by kutysam** [comment]
All good! Solution was based on this middleware https://github.com/pusher/rack-headers_filter

`under api/middleware` do the following

```
module Middleware
  class HeadersFilter
    SENSITIVE_HEADERS = %w[
      HTTP_X_FORWARDED_HOST
    ]

    attr_reader :remove_headers

    def initialize(app)
      @remove_headers = SENSITIVE_HEADERS
      @app = app
    end

    def call(env)
      @remove_headers.each { |header| env.delete(header) }
      @app.call(env)
    end
  end
end
```

```
map '/sidekiq' do
  use Middleware::HeadersFilter
  use Rack::Session::Cookie, same_site: true, max_age: 86_400
  run Sidekiq::Web
end
```

And now X_FORWARDED_HOST is dropped on request headers.

Thank you guys for pointing me to the right direction too! I'll close this.
