### ISSUE TITLE
Logging of skipped jobs

### ISSUE THREAD

**Issue by TiesWestendorp** [mperham/sidekiq#5736]
* Ruby: 3.0.4
* Rails: 6.1.6.1
* Sidekiq: 5.2.9
* OS: Debian 4.19.118-2

I'm unsure if this a setting that I've missed, but I find the logging of skipped jobs due to uniqueness to be unhelpful. We're using multiple Sidekiq processes that use the same Redis behind the screens, and cross-referencing logs is a bit cumbersome due to the incompleteness of the following logging rule:
```
INFO: Skipping enqueue for XXXX, not unique.
```
It would be nice if it would report the conflicting/overlapping job ID, like so:
```
INFO: Skipping enqueue for XXXX, not unique (overlaps with JID-ID).
```
Taking it even further, the queue of the overlapping job could maybe be added as well.

**Comment by mperham** [comment]
Good idea, I have implemented it.

```ruby
logger.info { "Skipping enqueue for #{c}, not unique (lock held by JID #{result})" }
```

**Comment by mperham** [comment]
BTW Sidekiq 5 is EOL.
