### ISSUE TITLE
Sidekiq Enterprise version in Ent-Change.md confusing

### ISSUE THREAD

**Issue by manuraj17** [mperham/sidekiq#5737]
Ruby version: N/A
Rails version: N/A
Sidekiq / Pro / Enterprise version(s): Enterprise

I am trying to understand the versioning from the Ent-Changes but the it jumps from `2.5.3` to `7.0.0`. Is that how the versioning went? 

I am trying to restrict my sidekiq to version `< 7` hence I need to find the version of Enterprise I can use to pin the sidekiq version to be below `7` as I am only using that gem. Unable to figure out the versioning from the file.

Queries
1. Is that version jump expected?
2. Which Enterprise version should I stick to prevent upgrade to 7?

**Comment by mperham** [comment]
Yes, the major versions for each product were aligned.

This is why you have version constraints in your Gemfile:

```ruby
gem "sidekiq", "<7"
```

That's it. Just tell Bundler that Sidekiq needs to stay under version 7.
