### ISSUE TITLE
Initialize workers with parameters in perform_async

### ISSUE THREAD

**Issue by bobbytables** [mperham/sidekiq#574]
Is there any reason that workers don't initialize with the parameters passed in `.perform_async` ?

It seems silly to initialize the object, then pass parameters to #perform. That defeats the purpose of OO and makes it extremely difficult to separate out methods in the worker.

TL;DR:
`Worker.perform_async(param1, param2)`

Should make Sidekiq do:

`Worker.new(param1, param2).perform`

**Comment by dissolved** [comment]
@mperham Except now we live in a world with reek...
https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md
