### ISSUE TITLE
TypeError: can't convert nil into Float

### ISSUE THREAD

**Issue by sirwolfgang** [mperham/sidekiq#5744]
Ruby version: 3.1.3
Rails version: 6.1.7
Sidekiq / Pro / Enterprise version(s): 7.0.3 / 7.0.6 / 7.0.3

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

When using the web UI, this error is thrown only on the `retries`, `scheduled`, `morgue` pages after upgrading from sidekiq `6` to `7`.

```ruby
TypeError: can't convert nil into Float
unknown  ?  unknown(...)
unknown:?:in `unknown'
  api.rb  489  initialize(...)
[GEM_ROOT]/gems/sidekiq-7.0.3/lib/sidekiq/api.rb:489:in `initialize'
  application.rb  146  new(...)
[GEM_ROOT]/gems/sidekiq-7.0.3/lib/sidekiq/web/application.rb:146:in `new'
  application.rb  146  block (2 levels) in (...)
[GEM_ROOT]/gems/sidekiq-7.0.3/lib/sidekiq/web/application.rb:146:in `block (2 levels) in <class:WebApplication>'
  application.rb  146  map(...)
[GEM_ROOT]/gems/sidekiq-7.0.3/lib/sidekiq/web/application.rb:146:in `map'
  application.rb  146  block in (...)
[GEM_ROOT]/gems/sidekiq-7.0.3/lib/sidekiq/web/application.rb:146:in `block in <class:WebApplication>'
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/main/Changes.md
https://github.com/mperham/sidekiq/blob/main/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Looking at the code I don't know what the problem is. The sorted set data format did not change at all and no one else is reporting a similar problem. Show us your initializer?

**Comment by sirwolfgang** [comment]
```ruby
# frozen_string_literal: true

require 'sidekiq/middleware/current_attributes'

Rails.application.reloader.to_prepare do
  Sidekiq::CurrentAttributes.persist(Current)
end

unless Rails.env.test?
  Sidekiq::Client.reliable_push!
  Sidekiq::Enterprise.unique!
end

Sidekiq.configure_client do |config|
  config.redis = Redis.persistent_connection_config
end

Sidekiq.configure_server do |config|
  config.redis = Redis.persistent_connection_config

  # @see https://github.com/mperham/sidekiq/wiki/Logging
  config.logger.level = ENV['SIDEKIQ_LOG_LEVEL'] || Logger::WARN

  # @see https://github.com/mperham/sidekiq/wiki/Reliability
  config.super_fetch!
  config.reliable_scheduler!

  # @see https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs
  # @see https://crontab.guru/
  config.periodic do |mgr|
    ...
  end
end

Sidekiq.default_job_options = {
  # Show backtraces only when on development for debugging. On production, they
  #  will be sent to error handler, and not use up REDIS memory
  backtrace: Rails.env.development?,
  retry:     ENV['SIDEKIQ_RETRY_LIMIT'] || 25
}
```

**Comment by sirwolfgang** [comment]
We also recently switched from Heroku Redis to Upstash Redis*. Is it possible some of the compatibility broke here? 
https://docs.upstash.com/redis/overall/rediscompatibility

**Comment by mperham** [comment]
I suppose it's possible. I've heard of a few people having issues with Upstash but I'm not aware of any issues with the sorted set commands.

**Comment by sirwolfgang** [comment]
I haven't noticed anything else, Can you share what other issues I might run into?

**Comment by mperham** [comment]
Search the issues for Upstash, the only known issue is their lack of support for the Metrics subsystem because they don't yet have the BITFIELD command. If you can reproduce this issue with plain vanilla Redis, I'll be happy to investigate but since no one else is reporting this, I have to assume there's some local environmental issue.

**Comment by sirwolfgang** [comment]
This seemed to have repaired its self, I think after a job went into the retries.
