### ISSUE TITLE
Delay method Sidekiq 7

### ISSUE THREAD

**Issue by alexnavarra** [mperham/sidekiq#5746]
Maybe someone know best practice to replace delay i 7 version. Before used like:
`MyClass.delay.execute`
Thanks

**Comment by mperham** [comment]
You could vendor the delayed code. You could use the gem which has adopted the code, https://github.com/gemhome/sidekiq-delay_extensions. You could switch your code to use Sidekiq::Jobs.

I don't have a recommendation, your choice.

**Comment by alexnavarra** [comment]
@mperham Thanks a lot:)
