### ISSUE TITLE
Sidekiq Pro Compatibility

### ISSUE THREAD

**Issue by jageschiff** [mperham/sidekiq#5747]
We are currently upgrading from Rails 4.2.11 to Rails 5.2.8.  The Rails 4 version is on Sidekiq version 5.2.8, the Rails 5 version is on 5.2.10.  Both versions of Rails are running on Ruby 2.4.9.

We have started to experience silently failing jobs from jobs initiated on the Rails 5 job servers.  This only occurs during hours of peak operation, on large jobs, and then on only a hand full of jobs.  During a period of 1.5 weeks out of 23315 jobs that were run in both environments, 47 silently failed.  They just disappear.

Are there any suggestions as to how we might resolve this or concerns about our approach?

We are working on upgrading to a more recent version of Sidekiq, 7.0.2, along with Ruby and Redis.  We are wondering how Sidekiq Pro would work in such an environment.

Can we run Sidekiq Pro under Ruby 2.4.9 in both Rails 4.2.11 and 5.2.8?  Is this "recommended"?

**Comment by mperham** [comment]
Yes, there are older versions of Sidekiq Pro 5.x which work with Sidekiq 5.x. Yes, it's recommended, rescuing lost jobs is the main feature of Pro:

https://github.com/mperham/sidekiq/wiki/Reliability#using-super_fetch
