### ISSUE TITLE
version upgrade failed with err msg "Could not load sidekiq/exception_hanlder" 

### ISSUE THREAD

**Issue by zli-sf** [mperham/sidekiq#5749]
```
LoadError:
  cannot load such file -- sidekiq/exception_handler
# .rvm/gems/ruby-2.6.6/gems/sidekiq-throttled-0.15.0/lib/sidekiq/throttled/communicator.rb:5:in `require'
# .rvm/gems/ruby-2.6.6/gems/sidekiq-throttled-0.15.0/lib/sidekiq/throttled/communicator.rb:5:in `<top (required)>'
# .rvm/gems/ruby-2.6.6/gems/sidekiq-throttled-0.15.0/lib/sidekiq/throttled.rb:8:in `require'
# .rvm/gems/ruby-2.6.6/gems/sidekiq-throttled-0.15.0/lib/sidekiq/throttled.rb:8:in `<top (required)>'
# .rvm/gems/ruby-2.6.6/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
```

Version: 

    sidekiq (6.5.8)
      connection_pool (>= 2.2.5, < 3)
      rack (~> 2.0)
      redis (>= 4.5.0, < 5)
    sidekiq-pro (5.5.8)
      sidekiq (~> 6.0, >= 6.5.6)
    sidekiq-throttled (0.15.0)
      concurrent-ruby
      redis-prescription
      sidekiq

**Comment by dbackeus** [comment]
This issue can be tracked in the current `sidekiq-throttled` repo: https://github.com/ixti/sidekiq-throttled/issues/16

However, maybe the Changes.md should be updated to mention a breaking change to exception_handler (not sure if that was supposed to be a public API or not).

**Comment by mperham** [comment]
The only APIs I make compatibility assurances are APIs which are documented in the wiki. The server exception handling utilities have never been documented so they are considered mutable without documentation. If you use my undocumented internal utilities, you need to be prepared to upgrade them without documentation too.
