### ISSUE TITLE
perform_in doesn't add job to jobs array in tests

### ISSUE THREAD

**Issue by mltsy** [mperham/sidekiq#5756]
Ruby version: 2.7.2
Rails version: 6.1.7.2
Sidekiq / Pro / Enterprise version(s): sidekiq-ent 2.5.3

In an RSpec test, perform_in doesn't seem to interact with the fake jobs queue properly:
```ruby
MyWorker.perform_in(5.seconds, args) # => nil
MyWorker.jobs # => []

MyWorker.perform_at(5.seconds.from_now, args) # => "job ID"
MyWorker.jobs # => [{stuff}]
```

**Comment by mperham** [comment]
Are you using unique jobs with MyWorker? That can prevent an enqueue.
