### ISSUE TITLE
Bad username or password for gems.contribsys.com

### ISSUE THREAD

**Issue by Blokh** [mperham/sidekiq#5758]
Ruby version:2.75
Rails version: 6.1.0
5.2.10 / 5.0.0 / Enterprise version(s):

Unable to install Sidekiq prod. 
returns: 
Bad username or password for gems.contribsys.com.
Please double-check your credentials and correct them.

it does not work in any environment. and nothing changed regarding key/env var.
seems like our account has been deleted for no reason.
The gem version was not updated.

**Comment by mperham** [comment]
Just a note for anyone that finds this. Top causes:

1. Cancelled subscription. Check your account email for billing notices. Purchase a new subscription to regain access.
2. An old Bundler version. Upgrade.

Here's more debugging tips:

https://github.com/mperham/sidekiq/wiki/Commercial-FAQ#how-do-i-debug-a-401-access-denied-error

**Comment by Blokh** [comment]
Thank you very much!!
