### ISSUE TITLE
RSpec Sidekiq Batches and Status

### ISSUE THREAD

**Issue by lerxcl** [mperham/sidekiq#5760]
Hi all, I am using Sidekiq Pro Batches and I am facing the issue where the Status does not update while executing my tests.

Here is my block of code:

```
it "has the jobs completed" do |example|
  b = Sidekiq::Batch.new
  b.jobs do
    3.times {Sidekiq::Worker::Random.perform_async(Time.now.to_i,nil)}
  end
  Sidekiq::Worker::Random.perform_one
  status = Sidekiq::Batch::Status.new(b.bid)
end
```

This is my `status` output:
```#<Sidekiq::Batch::Status:0x000000010c682808 @bid="4tR00OKDnnKWdA", @completed=0, @failures=0, @pending=3, @props={"created_at"=>"1675329197.732366", "callbacks"=>"{}", "pending"=>"3", "total"=>"3"}, @total=3>```

For pending, it is still stuck at 3, where it should have been 2 from `perform_one`, where it will execute and finish the 1st job in the batch.

I have also used the flag `stub_batches: false` to use a real Sidekiq Worker to execute these dummy jobs.
May I know how is the Status for `pending` calculated? 
Thank you!

**Comment by mperham** [comment]
It looks like the client middleware is setup but have you added the batch server middleware to Sidekiq::Testing.server_middleware? Put this in your test helper.

```ruby
Sidekiq::Testing.server_middleware.add Sidekiq::Batch::Server
```

**Comment by lerxcl** [comment]
Thank you @mperham, Status works properly now 👍
