### ISSUE TITLE
How to simulate a failed job in Sidekiq batch specs

### ISSUE THREAD

**Issue by theobarango** [mperham/sidekiq#5763]
Ruby version: 3
Rails version: 5
Sidekiq / Pro / Enterprise version(s): 6 (pro)

Hi Sidekiq team I just have a simple question. How do I simulate a failed job in a sidekiq batch? 

**Context**
I'm writing specs on a callback that gets fired if `status.failure != 0`. So far i'm able to simulate this by doing:

```
allow_any_instance_of(Sidekiq::Batch::Status).to receive(:failure).and_return(1)
```

However, is there a more programatic way to do this?

Thank you.

**Comment by mperham** [comment]
You execute a job which raises an error.

**Comment by theobarango** [comment]
thanks for getting back to me so quickly @mperham . When i do that in rspec the entire spec stops running. pls see below.

```ruby
class NullWorker
   include Sidekiq::Worker

  def perform
     raise
  end
end

let(:b) { Sidekiq::Batch.new }

context 'when failure' do
   it 'status is 1' do
      Sidekiq::Testing.inline! do
         b.jobs do
            NullWorker.perform_async
          end
       end

         status = Sidekiq::Batch::Status.new(b.bid)

         expect(status.failures).to eq(1)
   end
```

However, the result of the above is that the raised error is bubbled up to RSpec and the entire spec stops at the error. 

Am I approaching this wrong?

**Comment by mperham** [comment]
Well, if you're running the job inline, you should rescue the error and assert that it raised as expected.

But why are you testing the batch code? I have a large test suite for batches. Test your code, not mine.

**Comment by theobarango** [comment]
I see what you mean but that's just an example. In reality, I have a line of code in my callback that executes if `status.failures != 0`. So i'm looking for a way to increment failures, so that when I manually run my callback with the status (this status will have failures: 1), the callback can see the failure and execute that line of code.

So adjusting my earlier example to be more similar to my real code:

```ruby
it 'notifies sentry' do
      Sidekiq::Testing.inline! do
         b.jobs do
            NullWorker.perform_async
          end
       end
       status = Sidekiq::Batch::Status.new(b.bid)

         WorkflowCallback.new.workflow_complete(status, nil) # status here should have failure > 0

         expect(Sentry).to have_Received(:capture_Exception)
   end
```

Does this clarify more my question?

**Comment by mperham** [comment]
I would get rid of the batch setup altogether and just pass in a mock for the status argument.

**Comment by theobarango** [comment]
Sounds good. Thanks for the help @mperham. This ticket can be closed
