### ISSUE TITLE
Sidekiq.strict_args! is failing when the arguments for perform_in seem valid

### ISSUE THREAD

**Issue by DariuszMusielak** [mperham/sidekiq#5770]
Ruby version: 2.7.6
Rails version: 6.1.7.1
Sidekiq: 6.4.2
Sidekiq Pro: 5.3.1

I noticed that in my project there are many warning about incorrect format of parameters passed to perform. After reading documentation, I noticed that it is about changing symbol keys to string ones like that: 

From `DummyWorker.perfrom(user_id: 1)` into this: `DummyWorker.perfrom("user_id" => 1)` - and that is totally fine. 

What I do not understand why `Sidekiq.strict_args!` fails when all attributes are passed without keys, like plain values, like this: 
`DummyWorker.perform_in(1, "something"). `

In that case, I get:

```
     ArgumentError:
       Job arguments to DummyWorker must be native JSON types, see https://github.com/mperham/sidekiq/wiki/Best-Practices.
       To disable this error, remove `Sidekiq.strict_args!` from your initializer.

```

Does it mean that in a new version, arguments as plain values are not allowed any more?

**Comment by mperham** [comment]
Can you upgrade and see if the current 6.5.x has the same error?

**Comment by DariuszMusielak** [comment]
To be able to do that, if I [understand correctly](https://github.com/mperham/sidekiq/issues/5373#issuecomment-1149326864), I would need to bump `sidekiq-pro` as well. With sidekiq 6.5.0 I'm getting this:

```
LoadError:
  cannot load such file -- sidekiq/util
```

**Comment by mperham** [comment]
You need to include the full backtrace. Yes, you need to run `bundle up sidekiq-pro` to upgrade all Sidekiq gems.

**Comment by DariuszMusielak** [comment]
NVM ignore me, I found the reason. One of my values is not a plane value... it's an object, it appears that one object returns an object instead of string in one case. Sorry for the noise 🤦 

I will leave something for anyone else who would ever face the same issue. 

The "easy" way, just run `.class` method on each of the values you pass to `peform_in`.

The "hard" way:
1. Find where the validation happens: it was [here](https://github.com/mperham/sidekiq/blob/v6.4.2/lib/sidekiq/job_util.rb#L17)
2. Add binding.pry to see the exact case when the condition is not met: `binding.pry unless json_safe?(item)`
3. `item["args"]` includes all values, run `.class` on them. 

"easy" recommended ;)
