### ISSUE TITLE
Process lifecycle events

### ISSUE THREAD

**Issue by kylejw2** [mperham/sidekiq#5771]
I'm currently producing messages to Kafka via Sidekiq. I've noticed there are leaky connections in Sidekiq. I'm purposefully not closing the connection after it's been used since I don't want the overhead of having to open a new TCP connection each time I produce a message to the same address. Producing new messages, however, is resulting in a new TCP connection, rather than using an already existing connection. I've tested this with `ConnectionPool`, but still experienced the same problem.

An interesting point to make is that under the same configuration, my Rails app does not open a new TCP connection on each new message produced to Kafka.

Is it possible to hook into the Sidekiq process lifecycle? If it is, I'll test closing the connections via the lifecycle hook. I understand this isn't ideal since I'm still facing the issue of having new TCP connections established when there are pre-established connections available, but this might be more preventative of memory leaks in our production environment where Sidekiq is being scaled up and down via ECS.  

I'd want to do something similar to the following:
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDISCLOUD_URL'], network_timeout: 5 } if ENV['REDISCLOUD_URL']

  config.on(:shutdown) do
    Rails.logger.debug { '===Shutting down===' }
    KAFKA_PRODUCER.close
  end
end
```

**Comment by kylejw2** [comment]
This lifecycle hook existed at one point. Not sure why this is no longer available or if there's a better approach.
Reference: https://github.com/mperham/sidekiq/pull/1545

**Comment by mperham** [comment]
> This lifecycle hook existed at one point.

Why do you think it doesn't exist? Sidekiq Pro and Enterprise heavily use the `on` events. They exist.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/config.rb#L22-L30

**Comment by kylejw2** [comment]
Thanks for linking that. I tested it locally with the `boot` event, but got an error and made the assumption that the lifecycle events no longer existed since they're not in the file of the PR I referenced.
