### ISSUE TITLE
Sidekiq Web UI is not displaying any activity

### ISSUE THREAD

**Issue by craigphares** [mperham/sidekiq#5774]
I recently upgraded Sidekiq from 6.1.2 to 7.0.3. I never had this issue before, but now Sidekiq Web UI always displays Idle in the header, and no jobs are ever recorded as processed, failed, enqueued, etc. I know the jobs are running and being processed successfully, because I can see them in the logs. The Web UI is not reflecting the actual job/worker status.

I didn't see any new configuration that needs to be added/changed when upgrading to Sidekiq 7. Am I missing something?

Ruby version: 3.1.3
Rails version: 6.1.7.2
Sidekiq / Pro / Enterprise version(s): 7.0.3

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

### sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV["REDIS_URL"],
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
end
Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV["REDIS_URL"],
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
end
Rails.application.config.active_job.queue_adapter = :sidekiq
```

### sidekiq.yml
```
:queues:
    - critical
    - default
    - mailer
    - mailers
    - slow
```

**Comment by mperham** [comment]
Can you try running main?

**Comment by craigphares** [comment]
@mperham I just did a test using the main branch and had the same result.

I just looked at the rails logs more closely, and it seems like the jobs are being queued from Async, not Sidekiq, even though I've explicitly set the queue_adapter to `:sidekiq`

```
10:01:08 PM web.1               |  [ActiveJob] [TrackMediaClickJob] [ce9ddf56-b228-4c6d-bc74-1d5b022f28e6] Performing TrackMediaClickJob (Job ID: ce9ddf56-b228-4c6d-bc74-1d5b022f28e6) from Async(default) enqueued at 2023-02-08T03:01:08Z with arguments: 2
10:01:08 PM web.1               |  [ActiveJob] [TrackMediaClickJob] [ce9ddf56-b228-4c6d-bc74-1d5b022f28e6] Performed TrackMediaClickJob (Job ID: ce9ddf56-b228-4c6d-bc74-1d5b022f28e6) from Async(default) in 12.18ms
```

**Comment by craigphares** [comment]
@mperham that did the trick! Thank you! 🎉
