### ISSUE TITLE
Optimize retrying all jobs

### ISSUE THREAD

**Issue by fatkodima** [mperham/sidekiq#5781]
`RetrySet#retry_all` and `DeadSet#retry_all` (both used in the web ui to retry all jobs in the set) -
https://github.com/mperham/sidekiq/blob/47b3ddec510f2f80fd312fba65ea3239b35ee372/lib/sidekiq/api.rb#L772-L774 are very inefficient if these sets are large enough, because it iterates over jobs one by one performing several redis calls for each.

I suggest retrying them in batches: take a batch of jobs (100 at a time, for example), regroup them by queue and push bulk into each queue all the jobs from the group. Since most of the failing/dead jobs are from few queues, I believe, this would be much more efficient.

Are you open for such an optimization?

**Comment by mperham** [comment]
These APIs are already documented as being very inefficient, and not recommended for people to use normally. I would prefer the implementation to stay simple and readable, rather than try to optimize every last edge case.

**Comment by mperham** [comment]
If you want to provide a third-party gem which has optimized versions of these APIs, that’s up to you.
