### ISSUE TITLE
perform_async from a rake task does nothing

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#584]
I am trying to queue with the following 

ReportWorker.perform_async(
          "ReportModel.generate_report_data",report_type,report_date
      )

When ever I run this code within a Controller Method it works fine. The tasks get queued and processes fine. 

Although when I run this same line of code from a Rake Task, nothing happens. 

I have even attempted to move the code into the model object and have it execute thinking that there was some dependency that I was missing. 

Still nothing happens. 

The ask it self does not fire any errors. As I stated before running the code from inside a controller action it executes correctly.

**Comment by tilo** [comment]
@mperham I ran into the same issue.

Isn't the sidekiq client configured automatically on boot-up of the rake task?

**Comment by hupad85** [comment]
Adding this in `Rakefile` worked for me

```
Sidekiq.configure_client do |config|
  config.redis = { url: url, namespace: 'nanmespace', size: 1 }
end
```
