### ISSUE TITLE
Latency with odd values on Sidekiq API

### ISSUE THREAD

**Issue by sobrinho** [mperham/sidekiq#5846]
Ruby version: 2.7.6p219
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.5.8 / Pro 5.5.5 / Ent 2.5.3

Hi again!

We have a instrumentation in place with something similar to this:

```ruby
Sidekiq::Queue.all.each do |queue|
  latency, size = queue.latency.to_i, queue.size
  $stdout.puts("measure#sidekiq_latency.#{queue.name}=#{latency}")
  $stdout.puts("measure#sidekiq_size.#{queue.name}=#{size}")
end
```

But once in a while we are seeing odd spikes which doesn't make sense:

<img width="621" alt="Screen Shot 2023-03-23 at 21 42 02" src="https://user-images.githubusercontent.com/26460/227395618-ffa25b58-714d-4c40-858a-e730399a6c95.png">

Latency went from 0 to 10671 in less than 2 minutes, which I would expect to see at most 120 seconds. A few seconds later, down to zero again.

Any reason for that?

As you can see, we are tracking the queue size as well and there wasn't a spike there, the value simple spiked and returned right away.

**Comment by fatkodima** [comment]
Do you use any sidekiq extensions (thinking about some of them modifying `enqueued_at` of the job somehow)? 
`lantency` method looks flawless - https://github.com/sidekiq/sidekiq/blob/3b93c250d08df79e9296ade0c0e15d7e512035af/lib/sidekiq/api.rb#L265-L274

**Comment by mperham** [comment]
This can happen if super_fetch rescues an orphaned job hours later. The rescue process does not update the value of enqueued_at.

**Comment by fatkodima** [comment]
I am not familiar with super_fetch, but I am thinking that could also happen when retrying a job?

**Comment by mperham** [comment]
The scheduler subsystem is what does the job and retry enqueuing, it pushes the job thru Sidekiq::Client.push which will reset enqueued_at. 

Even Pro's reliable scheduler which runs in Lua has some gnarly code to update the value.

It's only the orphan rescue process which does not update it as I was trying to keep the code as simple as possible. Today it just calls brpoplpush which is very reliable but has this one drawback.

**Comment by sobrinho** [comment]
So, this is expected? Or should we fix that somehow?

It messes up with the logs and therefore the charts we have in place to monitor this.

<img width="579" alt="Screen Shot 2023-03-24 at 08 56 58" src="https://user-images.githubusercontent.com/26460/227515025-e46917c4-91d6-429d-8605-7f6787fa574a.png">

The blue line is the mentioned queue, while the other lines are actually correct.

**Comment by sobrinho** [comment]
Yep, we have a bunch of jobs that spikes in memory usage and if we get the lucky of them being processed by the same process at the same time, the process is killed due to OOM and eventually recovered by super fetch.

**Comment by mperham** [comment]
You might reduce concurrency by 1 and see if that eases the memory pressure.

**Comment by sobrinho** [comment]
Yep, dealing with those poison pills as we can, quite big and complex app.

We also have jobs that lasts for half hour or even more sometimes and when a deploy happens, they are pushed back or recovered.

While not that frequent, would this also cause this fake spike?

The app can take up to 2 minutes to boot and if a job that runs for 30 min is recovered, would it spike to about 32 minutes?

**Comment by sobrinho** [comment]
We changed our alerting system to watch for at least to trigger the alert but does not seem to be enough yet, and adding up more time can cause a delay up before something actually alerts.

No need for a realtime alerting here yet but I'm thinking that it might be desired in the future to have it.

**Comment by mperham** [comment]
Yeah, I think we're in agreement. Said another way, this is a good example of why alerting systems need to be stateful; it's not a good idea to alert based only on a single metric value. Ideally you alert only if you see 2-3 high latency values in a row; latency blips can cause alert fatigue in your devops staff on call. As you point out, the latency spikes are a symptom of an underlying issue but not something worthy of an immediate alert.
