### ISSUE TITLE
Rails url helpers not working in Sidekiq job

### ISSUE THREAD

**Issue by lowellk** [mperham/sidekiq#589]
When trying to use a url helper in my job, I'm getting the following error: `Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`

However, the url helpers work fine in my main app. What's the right way to solve this?

Thanks in advance :-)

**Comment by railsr** [comment]
I had to use `host: ActionMailer::Base.default_url_options[:host]` too

**Comment by nightsurge** [comment]
Same
