### ISSUE TITLE
Long Running Job Termination Log

### ISSUE THREAD

**Issue by mgestoquejr** [mperham/sidekiq#5927]
We have poorly implemented Sidekiq such that we are using it for a long running job (takes longer than 4 hours). We noticed that jobs are getting dropped if they take that long. We plan on refactoring the code to have it recursively run smaller jobs. However, before we can pitch the idea, we need to be able to show that Sidekiq does indeed drop them (purposely or intermittently).

Is there logging/exception raised within Sidekiq that we could look for to determine that a job has been terminated prematurely?

These issues are helpful and relevant. But having a bit more information would be useful:
https://github.com/sidekiq/sidekiq/issues/4877
https://github.com/sidekiq/sidekiq/issues/3683

**Comment by mperham** [comment]
Sidekiq::Shutdown is raised in any jobs which don’t stop normally.

**Comment by mperham** [comment]
These two lines are logged if your jobs don't shut down cleanly in time. Note that one is at debug level.

https://github.com/sidekiq/sidekiq/blob/0175cdbe03c3a9edf908a155ae6f006061b5c224/lib/sidekiq/manager.rb#L98-L99

**Comment by fatkodima** [comment]
Not directly answering your question, but you might find https://github.com/fatkodima/sidekiq-iteration useful for long running jobs.

**Comment by mperham** [comment]
If you see normal job logging and then suddenly a restart with no shutdown logging, that sounds like a process crash.
