### ISSUE TITLE
Feature Request - Enqueue Periodic Jobs from Sidekiq UI

### ISSUE THREAD

**Issue by RachalCassity** [mperham/sidekiq#5955]
### Feature Request - Enqueue Periodic Jobs from Sidekiq UI 

Ability to enqueue periodic jobs from the Sidekiq UI. This feature is enabled for Scheduled Jobs. 

### Reason for request

Previously, we have used Sidekiq Scheduler and we are replacing the Sidekiq Scheduler with Periodic Jobs. In ideal situations, a job can be enqueued via the rails console. Unfortunately, for our substantial organization, only limited people can obtain access to the rails console due to PPI information and other sensitive data. By enabling this feature in the Sidekiq UI, multiple teams will be able to enqueue jobs when needed, without breeching sensitive information. 

We would be very appreciative for this feature. Thank you for your time.

### Background
Ruby version: 3.2.2
Rails version: 6.1.7.4
Sidekiq / Pro / Enterprise version(s): 6.5.7 / 5.5.8 / 2.5.3

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version? **Yes.**

https://github.com/sidekiq/sidekiq/blob/main/Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Pro-Changes.md
https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md

**Comment by mperham** [comment]
Thank you for the great explanation: this is how to ask for a new feature!

I still believe the feature is an iceberg. First, enqueue jobs. Then, change arguments. Then, enable and disable crons. Then, …

Could your org provide a script which can enqueue a job class and args without providing complete console access: `enq SomeJob arg1 arg2`

**Comment by RachalCassity** [comment]
Hi Mike, 

Thank you for your prompt response. Since our system is reliant on a complicated web of proxies, our support developers are enqueueing jobs for other teams at the moment. We migrated to EKS over a month ago and we are currently are using ArgoCD UI for terminal access, which is also heavily monitored and developers cannot gain access without overhead approval. I understand that our scenario is an unique situation. 

Just for reference, none of our Periodic Jobs require arguments.

**Comment by mperham** [comment]
There are a dozen OSS extensions which add their own Web UI extension. Look at sidekiq-cron for how to do it.

**Comment by RachalCassity** [comment]
Thank you, I will!
