### ISSUE TITLE
Is there a way to debug/breakpoint sidekiq jobs? 

### ISSUE THREAD

**Issue by cameronkendall** [mperham/sidekiq#626]
The code for one of my workers has a different result compared to running the exact same code in my controller.  Is there a way to debug/breakpoint the values/methods while the workers are running?  If not, why would the result be different for the exact same code, and same variables in a local environment that I'm only affecting (and with no other jobs running)?  Thanks!

**Comment by gazeldx** [comment]
You can use RubyMine. There are debug configuration for debugging. For sidekiq, you need to add a  'Gem Command' configuration.

https://stackoverflow.com/questions/23467254/how-to-start-sidekiq-in-rubymine

**Comment by cdmo** [comment]
binding.pry works just fine for me. Run sidekiq in terminal, and binding.pry where you want it and the terminal running sidekiq will give your pry breakpoint

**Comment by skyuchukov-bp** [comment]
> binding.pry works just fine for me. Run sidekiq in terminal, and binding.pry where you want it and the terminal running sidekiq will give your pry breakpoint

Alternatively, if one uses the `byebug` gem, it does the trick too ;)
