### ISSUE TITLE
What is a server and a client?

### ISSUE THREAD

**Issue by jlecour** [mperham/sidekiq#638]
Hi,

I've looked for a mailing to ask this question but didn't find any. I hope I've searched enough and I'm not abusing the issue tracker with this question.

I am building an app that will push jobs into the queue, and they will be processed by workers in another app.

Do I have to configure one of them as the "client" and the other one as the "server"? Or do I have to configure both apps as "client" **and** "server**?

Thanks

**Comment by sriharshakappala** [comment]
@mperham This post explaining the difference between the sidekiq client and sidekiq server is so helpful. It would be great if the same is added in either README.md or in one of the wiki pages.

**Comment by mperham** [comment]
@sriharshakappala Already covered in "The Basics" wiki page https://github.com/mperham/sidekiq/wiki/The-Basics#client
