### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by dflynn15** [mperham/sidekiq#648]
Ok, this has been an intermittent error for me that past week and after a lot of attempts at fixing it I have come to a stand still.

The error:

2013-01-25T15:30:44+00:00 app[postgres]: [5-1] u4jpkq3jfg8e8q [ROSE] LOG:  could not receive data from client: Connection reset by peer
2013-01-25T15:30:44+00:00 app[postgres]: [6-1] u4jpkq3jfg8e8q [ROSE] LOG:  unexpected EOF on client connection

What I have found during research:

Ultimately that I must have mis-configured Sidekiq with the unicorn workers.
http://stackoverflow.com/questions/13324352/heroku-postgresql-connection-reset-by-peer
https://github.com/defunkt/resque/issues/367
http://stackoverflow.com/questions/9961044/postgres-error-on-heroku-with-resque

Threads from this GitHub (that helped a lot):
https://github.com/mperham/sidekiq/issues/120
https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting
https://github.com/mperham/sidekiq/wiki/Advanced-Options

I came up with the following configuration after using the Sidekiq calculator knowing that I had a Medium RedisToGo and 11 Dynos and 11 Workers for Heroku.

``` ruby
#config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|

  database_url = ENV['DATABASE_URL']
  if(database_url)
    ENV['DATABASE_URL'] = "#{database_url}?pool=40"
    ActiveRecord::Base.establish_connection
  end
  config.redis = { :size => 43 }
end

if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    Sidekiq.configure_client do |config|
      config.redis = { :size => 1 }
    end if forked
  end
end
```

``` ruby
#config/unicorn.rb
worker_processes 3
timeout 150
preload_app true

after_fork do |server,worker|
    if defined?(ActiveRecord::Base)
        ActiveRecord::Base.establish_connection
        Rails.logger.info('Connected to ActiveRecord')
    end

    Sidekiq.configure_client do |config|
        config.redis = { :size => 1 }
    end
end
```

I am clearly missing something here. It might not have to do with sidekiq, but before I ruled it out I wanted to make sure I wasn't completely messing up the configuration and therefore the entire app. This only happens every once in a while so I am having a hard time completely tracking it down, but any help would be greatly appreciated!

**Comment by talkabhishek** [comment]
@dflynn15 Could you let me know how you fixed this issue or what was the problem? 
I am getting this issue with my rails app deployed on Heroku with Postgres add-ons. I am not getting a cause why I am getting this, Fix is something I can try after knowing the cause.
