### ISSUE TITLE
Sidekiq inserting items to front, not back?

### ISSUE THREAD

**Issue by HenleyChiu** [mperham/sidekiq#655]
I've updated the Sidekiq gem to the latest version (was using 2.5.0 earlier). I notice that new items are not being pushed to the front of the queue vs the end of the queue. Is this a recent change or a bug? If its a feature, is there anyway to set the option to insert to back?

**Comment by xanview** [comment]
Any way to control this? - where are jobs inserted currently? - I cannot find this in the documentation.
