### ISSUE TITLE
Filtering on morgue display tags failing in Sidekiq 7.3.7

### ISSUE THREAD

**Issue by calvincchen** [mperham/sidekiq#6554]
Ruby version: 3.3.5
Rails version: 7.2.2.1
Sidekiq / Pro / Enterprise version(s): 7.3.7 / 7.3.4 / 7.3.4

### Summary
After updating to Sidekiq 7.3.7, we're no longer able to filter the morgue using the href associated with a dead job's display tag
Similar to https://github.com/sidekiq/sidekiq/issues/6508

### Steps to Reproduce
1. Update Sidekiq to version 7.3.7
2. Navigate to https://WEBSITE/sidekiq/morgue.
3. Click on a display tag next to a dead job

### Expected Behavior
Redirect to a filtered morgue page
Route: `https://WEBSITE/sidekiq/morgue?substr=mytag`

### Actual Behavior
Redirected to home page, since the route does not exist
Route: `https://WEBSITE/sidekiq/dead?substr=mytag`

I suspect [this line](https://github.com/sidekiq/sidekiq/blob/v7.3.7/web/views/morgue.erb#L43) is the cause? Thanks!

**Comment by calvincchen** [comment]
Thank you!

**Comment by tnordloh** [comment]
I know I'm probably missing something really obvious, but I'm not seeing 7.3.8 in rubygems; what am I missing?  We don't use the broken `morgue` link often, but we do use it.

I tried adding `sidekiq` to our 'enterprise.contribsys.com`, block, assuming that maybe the free version has a delay on release cadence, no luck there.

**Comment by mperham** [comment]
@tnordloh Strange, it's there now. 😁 Thanks for the reminder.
