### ISSUE TITLE
Use with sharded Redis setup?

### ISSUE THREAD

**Issue by xxx** [mperham/sidekiq#660]
Hi,

We have a multi-shard redis cluster in our environment, and would like to plug sidekiq into that, but the config examples, and the code itself, seems to assume a single redis server.

Am I missing something, or is it not possible at the moment to use a distributed redis ring with sidekiq?

**Comment by saipraveen-a** [comment]
@xxx With this configuration, if i have configured a CONCURRENCY setting of 5, I will have 7 workers running? How many of these are going to process jobs from Server1 vs Server2? Is there a way of controlling that?

Also, Can you please explain what is the significance of line 29?
