### ISSUE TITLE
perform method arguments?

### ISSUE THREAD

**Issue by fleshins** [mperham/sidekiq#674]
When I define my perform method with a single argument, e.g. def perform(record_id), sidekiq crashes and tells me it's expecting 2 arguments instead of 1.

WARN: {"retry"=>true, "queue"=>"default", "class"=>"HardWorker", "args"=>[7], "jid"=>"ca925c52784a81adfd6cd747", "error_message"=>"wrong number of arguments (1 for 2)", "error_class"=>"ArgumentError", "failed_at"=>2013-02-02 21:35:58 UTC, "retry_count"=>0}

What is the 2nd argument for? I couldn't figure it out from looking inside lib/sidekiq/worker.rb

I added a dummy argument, def perform(record_id, dummy=1), and now things seem to be working.

Apologies if this is the wrong forum for such a general question!

**Comment by syedhassan** [comment]
@pferdefleisch Cant thank you enough.

Existing workers were a real pain
