### ISSUE TITLE
Sidekiq not picking up alternative Redis URL from initializer

### ISSUE THREAD

**Issue by TheBloke** [mperham/sidekiq#678]
Ruby: 1.9.3p374,  Rails 3.2.11,  Sidekiq 2.7.0

I'm trying to configure Sidekiq to use an alternative Redis URL.

As per docs I have created _config/initializers/sidekiq.rb_, and defined both configure_server and configure_client URLs.

Despite this, on startup it still shows it's connecting to the default URL - _Booting Sidekiq 2.7.0 with Redis at redis://localhost:6379/0_.  And this is confirmed in production where it then errors out due to connection refused, as Prod does not have a Redis server on localhost.

I know that the _config/initializers/sidekiq.rb_ file is being read by Rails, because I got an exception raised on rails server startup one time when I had a typo in it.

Currently I am working around this issue by setting REDIS_URL in my Capistrano deploy recipe in _set :sidekiq_cmd_, but obviously I'd like to get it working the proper way.

My initializer is as follows (note that I am pulling config from a properties.yml file - I have also tried it with a plain, static _:host => "redis://servername.com:.."_ string, removing the from-yaml configuration stuff, just in case that was any issue.  The issue remained.)

``` ruby
host = YamlProperties.redis[:host]
port = YamlProperties.redis[:port]
namespace = YamlProperties.redis[:namespace]
db_num = YamlProperties.redis[:db_num]

Sidekiq.configure_server do |config|
  config.redis = { :host => "redis://#{host}:#{port}/#{db_num}", :namespace => namespace }
end

Sidekiq.configure_client do |config|
  config.redis = { :host => "redis://#{host}:#{port}/#{db_num}", :namespace => namespace }
end
```

Getting:

``` bash
tomj@marvin:~/apps/roi_app$ bundle exec sidekiq
2013-02-04T19:41:24Z 85700 TID-ouoc74ezk INFO: Booting Sidekiq 2.7.0 with Redis at redis://localhost:6379/0
...
```

Thanks in advance

Tom

**Comment by shrihari007** [comment]
For me, the error was from config/cable.yml. The URL configuration was wrong.
