### ISSUE TITLE
sidekiq-web delete action drops http port and defaults to 80

### ISSUE THREAD

**Issue by mittermayr** [mperham/sidekiq#684]
I have sidekiq/rails/unicorn/nginx running on HTTP Port 4444, so on this URL:

http://MYDOMAIN:4444/sidekiq/queues/MYQUEUE

Clicking DELETE on a queued job, actually deletes it, but then redirects to:

http://MYDOMAIN/sidekiq/queues/MYQUEUE

Port is missing, page fails loading.

**Comment by codingleo** [comment]
I had this same problem in production using `https`.
By using this proxy redirect, worked fine.

but instead of:

```
proxy_redirect http://www.mydomain.com/ http://www.mydomain.com:4444/;
```
I've used:
```
proxy_redirect https://$host:80$request_uri; https://$host$request_uri;
```
