### ISSUE TITLE
How to test delay on ActionMailer

### ISSUE THREAD

**Issue by gregorym** [mperham/sidekiq#724]
Hi,
Let's say I send an email through Sidekiq like below.

<pre>
MyMailer.delay.welcome(param1, param2)
</pre>

Now I want to test (with Rspec) that I am actually queuing an email with specific params. How should I do that with Rspec?

I try to stub_chain'' but it did not work.

Thanks

**Comment by rmm5t** [comment]
@FunkyloverOne 

```ruby
class SomeControllerTest < ActionDispatch::IntegrationTest
  include ActiveJob::TestHelper

  test "enque an email" do
    assert_enqueued_with queue: "mailers" do
      post some_path
    end
  end
end
