### ISSUE TITLE
No route match in middleware on Rails 3

### ISSUE THREAD

**Issue by winton** [mperham/sidekiq#734]
On rails (= 3.2.12) I am defining this route as outlined in the [Monitoring](https://github.com/mperham/sidekiq/wiki/Monitoring) section of the wiki:

``` ruby
mount Sidekiq::Web => '/sidekiq'
```

In the logs I continually see:

```
ActionController::RoutingError (No route matches [GET] "/dashboard/stats")
```

However, when I change the route to '/', the 404 disappears:

``` ruby
mount Sidekiq::Web => '/'
```

**Comment by vkeziah** [comment]
```
RSpec.describe  Sidekiq::Web, type: :routing do
  describe "routing" do
    it "routes to #web" do
      expect(get: "/sidekiq").to route_to("work#index")
    end
  end
end
```

```
  1) Sidekiq::Web routing routes to #web
     Failure/Error: expect(get: "/sidekiq").to route_to("work#index")
       No route matches "/sidekiq"
```

Not sure why my test is failing , any idea ?

**Comment by joshm1204** [comment]
Been searching for the same answer for months. Any help appreciated.

**Comment by joshm1204** [comment]
I have the same question as Vkeziah. Any ideas?

**Comment by mperham** [comment]
Please stop commenting on a 9yo issue. Open your own issue if you have a problem.
