### ISSUE TITLE
Process shows 0 workers active, some jobs still processed

### ISSUE THREAD

**Issue by tehprofessor** [mperham/sidekiq#741]
Howdy,

**Background**
I'm using Sidekiq 2.7.5; Rails 3.2.x; Ruby 1.9.3; on Debian Squeeze w/ Redis 2.6+ and PostgreSQL. I have a rake task which initiates background jobs; to build up a database of strings for use in our autocomplete. I use the same worker that I use in the rake task, in the Rails application itself (when I don't need to retroactively create the search slug).

Example Rake Task.

```
namespace :cheese
    desc "Add search slug"
    task :add_all => :environment do |t, args|
        Model.all.each do |m|
            AddSearchEntryWorker.perform_async(m.class.name.downcase, m.id)
        end
    end
end
```

Example Worker.

```
class AddSearchEntryWorker
    include Sidekiq::Worker
    def perform(model_name, id)
        model = model_name.capitalize.constantize
        instance = model.find(id)
        if instance.soulmate_term
            loader = Soulmate::Loader.new(model_name)
            loader.add(
                "term" => instance.soulmate_term, 
                "id" => id)
        end
    end
end
```

**config/initializers/sidekiq.rb**

```
Sidekiq.configure_server do |config|
  config.redis = { :url => 'redis://127.0.0.1:6379/1' }
end

Sidekiq.configure_client do |config|
  config.redis = { :url => 'redis://127.0.0.1:6379/1' }
end
```

Besides that rake task for building up "slugs," I have a few calls to some other workers in the Rails application itself. Everything works fine in development.

**The Problem**

1.) The web UI and `ps aux | grep sidekiq` show zero workers, and zero enqueued tasks when I run the Rake task. 

```
deploy  10412  7.6 11.5 483800 120576 pts/3   Sl+  23:30   0:47 sidekiq 2.7.5 househappy.org [0 of 3 busy]  
```

2.) The rake task's jobs are being processed regardless of not showing up in the UI.

3.) Jobs called from within the Rails app, from say an observer or a controller, to that same worker, or different ones, show up in the Web UI but are never processed. No workers ever show up.

![Snapshot 2:27:13 4:37 PM](https://f.cloud.github.com/assets/995086/203615/255cbb00-813f-11e2-868b-1b9c074366cf.png)

4.) Sidekiq logs show no work being processed.

I've included a screenshot after I flushed Redis.

![sidekiq-sans-work](https://f.cloud.github.com/assets/995086/203483/e45e01aa-8138-11e2-8033-d498ad7bcd16.png)

After I've run the rake task

![Snapshot 2:27:13 4:21 PM](https://f.cloud.github.com/assets/995086/203574/3ccaf2c2-813d-11e2-9183-fca8b9d95826.png)

Redis' memory has increased (which makes sense if the jobs are in fact running) and our autocomplete works (which again makes sense if the jobs are running)... but why are they?

**Fin**

So yeah, that's my problem(s). Any help would be greatly appreciated! I'd be happy to know if I've done something stupid, shit, I'd even prefer it! Because for the time being I'm feeling rather baffled about what is going on... and my own stupidity is something I can live with.

Best,
Seve

Below is anything else I can think of that might help:

sidekiq.yml

```

---
:concurrency: 3
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 3
```

Output when sidekiq is run with -v

```
2013-02-28T00:34:00Z 13905 TID-42vi0 INFO: Booting Sidekiq 2.7.5 with Redis at redis://127.0.0.1:6379/1
2013-02-28T00:34:00Z 13905 TID-42vi0 INFO: Running in ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
2013-02-28T00:34:00Z 13905 TID-42vi0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2013-02-28T00:34:00Z 13905 TID-42vi0 INFO: Starting processing, hit Ctrl-C to stop
2013-02-28T00:34:00Z 13905 TID-12pwvo DEBUG: {:queues=>["default"], :concurrency=>3, :require=>".", :environment=>"staging", :timeout=>8, :profile=>false, :verbose=>true, :namespace=>nil, :tag=>"househappy.org"}
```

`PG::Connection.isthreadsafe` returns `true`

Addendum:

The screenshot showing the item in the queue was taken after the one which shows redis memory usage (in case the order of them makes it the timeline confusing).

**Comment by mandalashwini** [comment]
Hello anyone tell me, I am using sidekiq and there are 200 threads but it shows only 44 busy.
