### ISSUE TITLE
I18n not working with delay and email

### ISSUE THREAD

**Issue by allaire** [mperham/sidekiq#750]
When using Mailer.delay.password_reset(self) with an i18n email, the language is always set to english. if I remove the .delay method and put back .deliver, the mail is delivered with the correct language.

mailers/mailer.rb

```
class Mailer < ActionMailer::Base
  default :from       => '"Lodgem" <support@lodgem.com>',
          :'reply-to' => '"Lodgem" <support@lodgem.com>'

  def password_reset(user)
    @user = user

    params = {
      to: user.email,
      subject: t('email.password_reset.subject')
    }

    mail(params)
  end
end
```

models/user.rb

```
def send_password_reset
  self.password_reset_token = SecureRandom.uuid
  self.password_reset_sent_at = Time.now
  save!(validate: false)

  Mailer.delay.password_reset(self)
end
```

I'm using Rails with locales `en` and `fr-CA`. If you need to see more code or need more info, just ask!

Thank you!

**Comment by rvsingh** [comment]
Hey @Goltergaul, how to require in config? Do you mean in initialisers?

**Comment by Goltergaul** [comment]
@rvsingh that was very long ago... i suppose in sidekiq config which would be in an initializer

**Comment by raphael-souza** [comment]
Thanks @Goltergaul . adding the midlaware to the sidekiq configuration file in initializers worked very well.
