### ISSUE TITLE
Pool size not working

### ISSUE THREAD

**Issue by ogtfaber** [mperham/sidekiq#772]
The database Pool size method as described in the wiki for ActiveRecord was not working for me. Setting the pool size in the Database Url for some reason was never picked up, always back to the standard of 5 for the sidekiq server.

Funny enough, I also configured ?pool=25 in the Heroku config environment variable, and in my normal console I had a pool of 25. Nevertheless, the sidekiq server stayed at 5.

In the configure_server block:

```
database_url = ENV['DATABASE_URL']
if(database_url)
  ENV['DATABASE_URL'] = "#{database_url}?pool=25"
  ActiveRecord::Base.establish_connection
end
```

This seems to work though (in the configure_server block), got it from https://devcenter.heroku.com/articles/concurrency-and-database-connections:

```
ActiveRecord::Base.connection_pool.disconnect!
config = Rails.application.config.database_configuration[Rails.env]
config['reaping_frequency'] = ENV['DB_REAP_FREQ'] || 10 # seconds
config['pool']              = ENV['DB_POOL'] || 25
ActiveRecord::Base.establish_connection(config)
```

**Comment by rcarvalho** [comment]
I had this issue, but it looks like Heroku has a nice solution, now. You can actually specify the connection pool size in your database.yml production configuration and it will actually use it.
