### ISSUE TITLE
Long jobs

### ISSUE THREAD

**Issue by hgsigner** [mperham/sidekiq#781]
Hi,

I'm using sikekiq alongside with mongodb (mongoid 3 + kiqstand). I've got some jobs that delete images from my DB and from S3. Sometimes, it has to delete +2.000 images. In one of these cases, I've just noticed that the worker get stuck after 3 hours running. Do you guys know a way to work around this issue? Is there a way to reset this currently running job?

Thanks
Hugo

**Comment by fruwe** [comment]
but there are cases, where you need to let the job run, e.g. scraping slow web sites. it would be nice to have some kind of info on that topic. like recommended settings or at least some information about sidekiq not being able to run jobs which take longer than x seconds

**Comment by mperham** [comment]
Take a look at Sidekiq Enterprise’s support for rolling restarts in the wiki. It makes long jobs trivial.
