### ISSUE TITLE
Sidekiq error Uninitialized Constant

### ISSUE THREAD

**Issue by juand** [mperham/sidekiq#789]
I'm having an issue with sidekiq. Basically we're getting NameError: uninitialized constant on our sidekiq setup which is causing a large number of jobs to fail.

The error log says:

```
NameError: uninitialized constant GameUser::Lock /data/@myapp/releases/20130321230952/app/models/game_user.rb:71:in `node_calls_base_get_user' 
/data/@myapp/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.8.0/lib/sidekiq/processor.rb:45:in `block (3 levels) in process' 
/data/@myapp/shared/bundled_gems/ruby/1.9.1/gems/sidekiq-2.8.0/lib/sidekiq/middleware/chain.rb:109:in `call'
```

The code is here:

```
# app/models/game_user.rb
def self.node_calls_base_get_user(serial, game_name)
  if Lock.get("user:#{id}") # Set up lock to prevent multiple users to be created      
    Lock.delete("user:#{id}")
  end
  return false
end
```

Lock is defined in a library:

```
# lib/lock.rb
class Lock
  def self.get(key)
    lock = CACHE.add("lock:#{key}", 1, 5) # Let lock autoexpire after 5 seconds
    return true
  end
end
```

And the lib/ folder is automatically loaded with the rest of the configurations.

```
module Myapp
  class Application < Rails::Application
    ...
    # Custom directories with classes and modules you want to be autoloadable.
    config.autoload_paths += %W(#{config.root}/lib)
    ...    
  end
end
```

I have no idea why this is happening. It seems to happen more frequently when we deploy, but it seems to happen often enough otherwise.

I've been following the following thread: https://github.com/mperham/sidekiq/issues/331 but it doesn't seem to offer a solution besides adding the lib folder to the autoload_paths.

I'm using:

```
gem 'rails', '3.2.13' 
gem 'sidekiq', '>= 2.7.5'
```

Any help would be greatly apreciated.

**Comment by pokrovskyy** [comment]
I'm having this kind of error popping up spontaneously on my production workers. I would say rather rarely. It only sometimes happens upon worker boot-up. Missing classes differ much:

uninitialized constant ActiveRecord::Associations::BelongsToAssociation
uninitialized constant ActiveRecord::Associations::HasManyAssociation
uninitialized constant ActiveRecord::Associations::Preloader::BelongsTo
uninitialized constant ActiveRecord::Core::LegacyYamlAdapter
uninitialized constant ActiveRecord::Associations::HasManyThroughAssociation
uninitialized constant ActiveRecord::Associations::JoinDependency::JoinBase
etc.

It really seems like the worker has not yet fully loaded all the requirements, but Sidekiq part already is and starting pulling up jobs and throwing them into the threads. Not sure if it's Sidekiq issue or not, but it really seems like it starts working a little too early, like it should just wait for the requirements to load up. Could not reproduce this in dev env, only happens in high-load production. Any thoughts?

**Comment by seuros** [comment]
@pokrovskyy What versions of the gems do you have ? did you have the latest version on production ?

**Comment by bhaveshf-cuelogic** [comment]
So what's the ideal solution for this problem ? We are also facing this issue in our app with Ruby `2.4.5` & Rails `5.2.0`. We have our rails app running in one container and sidekiq running in another container.

We have some ruby classes in `app/apis/services/<MyClassFile>` which are being called from a worker file placed in `app/workers/<folder>/<MyWorkerClass>`. Whatever lines of code was calling `MyClassFile` from `MyWorkerClass`, we tried to move in models so that it gets autoloaded but still the problem exists.

**Comment by seuros** [comment]
You are not the autoloader correctly . If have workers inside a folder, they should be namespaced with the same name of the folder , or required manually.

**Comment by bhaveshf-cuelogic** [comment]
@seuros : Following is the trimmed down code of my current problem

`app/apis/services/notification/type1_notifier.rb`
```
module Services
  module Notification
    class Type1Notifier
      def initialize()
      ....
      end
    end
  end
end
```

`app/workers/notifications/my_worker.rb`
```
class MyWorker
  include Sidekiq::Worker
  def perform
     Services::Notification::Type1Notifier.new(...)
  end
end
```

**Comment by mperham** [comment]
@bhaveshf-cuelogic https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#autoloading

You can ask for help and people are welcome to help but I make no attempt to solve autoloading problems.  It's always an app problem, not a Sidekiq issue; the best thing to do is review the Rails autoloading guide.

https://guides.rubyonrails.org/autoloading_and_reloading_constants.html
