### ISSUE TITLE
Sinatra error require': cannot load such file -- sinatra/base (LoadError)

### ISSUE THREAD

**Issue by kakubei** [mperham/sidekiq#814]
Hello, I noticed that this same error was logged for Sidekiq Pro but the solution in that issue didn't work for me so I'm asking here what else I can try. 

My Gemfile has:

gem 'sidekiq'
gem 'sinatra', '>= 1.3.0', :require => nil
gem 'slim'

Yet I get this error when issuing `Rails s thin`:

```
gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- sinatra/base (LoadError)
```

Rails version is 3.2.11
Sinatra version 1.3.6
Slim version 1.3.6
activesupport 3.2.11

routes.rb has this:

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

Everything else works fine if I remove the sidekiq lines from routes.rb

Thanks.

**Comment by folubode** [comment]
am geting this error:

Sidekiq 3.5.1 does not support Ruby 1.9. (RuntimeError)

what can i do please?

**Comment by acanyon** [comment]
Try: `gem 'sinatra', :require => nil`

Sinatra is required for the web component so you need it when you add the web component to your routes file.

**Comment by kikocastro** [comment]
updating sidekiq worked fine here! (v 4.2.5)
