### ISSUE TITLE
ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by ingithub** [mperham/sidekiq#816]
Hi,

my SidekiqWorker sometimes doesn't work properly and I really don't know why.

Worker

```
class ConnectWorker
  require 'net/ssh'
  include Sidekiq::Worker
  def perform connect_id
    connect = Connect.find(connect_id)
    Net::SSH.start(connect.server, connect.user, :password => connect.pass) do |sftp|
     # Do some stuff
    end
  end
end
```

Controller

```
class ConnectController < ApplicationController
  def connect
    ConnectWorker.perform_async(params[:id])
    redirect_to :back
  end
end
```

Sometimes is everything ok, sometimes it gives me ActiveRecord::RecordNotFound.
What can I do wrong?
Thanks

**Comment by stuartchaney** [comment]
Another possible solution which i encountered.

The same Sidekiq redis url was being used by another app.
