### ISSUE TITLE
Getting retry count for current job?

### ISSUE THREAD

**Issue by HenleyChiu** [mperham/sidekiq#845]
Is there a way to get the retry count for the current job? I want to know whether it's retry #1, #2, #3, etc.

**Comment by palexvs** [comment]
@mperham is there any reason do not give access to the `retry_count`?

I found a few workarounds ([1](https://stackoverflow.com/questions/23065578/sidekiq-retry-count-in-job) and [2](https://medium.com/appaloosa-store-engineering/make-a-failing-sidekiq-worker-call-a-method-after-a-specific-number-of-retries-709d7f2cb9f3)) but I don't understand why `retry_count` is not a part of standard API

I use Sidekiq to deliver `web_hooks` to clients and if some `web_hook` fails the delivery should be retried 30 times (for 60 days). But I want to notify a client about the issue starting from 5th attempt (don't bother the client if he has a short downtime) and I would expect something like this:
```
class WebhookWorker
  include Sidekiq::Worker
  sidekiq_options queue: :webhook

  def perform(*args)
    # send webhook
  rescue WebHook::Error => ex
    ApplicationErrors.notify_client(...) if retry_count > 4
    raise ex
  end
end
```

Do I do something wrong?

Thank you

**Comment by mperham** [comment]
Sidekiq's internal retry mechanism is not designed for application access, otherwise there would be a thousand configuration knobs for every dev who wanted to customize every aspect of it.  If your app has custom error handling and notification logic, you need to build it in your app code.

https://github.com/mperham/sidekiq/wiki/Error-Handling#no-more-bike-shedding

**Comment by mikegee** [comment]
@palexvs maybe you could pass the current time as one of the arguments to your worker and send the notification if sufficient time has passed rather than counting retries?

**Comment by woodhull** [comment]
I have the exact same use case: helping customers who we send webhooks understand how many times the current job has been retried already by sending that information along in the payload to consumers. 

It's not that folks like @palexvs and I who want this information want a knob, or to change the configuration in sidekiq or do anything with the sidekiq internals beyond accessing it as a read only attribute of the current job being executed. It seems like it is analogous to something like `jid` in this respect, which is easily accessible within worker code. 

I just want to expose the retry count to our API consumers so they can know what's happening (like sidekiq does in its internal web console!) with regard to the retry behavior Sidekiq offers out of the box, not change how retries work in any way at all.

**Comment by mperham** [comment]
@woodhull can you not use server middleware for this purpose?

**Comment by woodhull** [comment]
@mperham I will most likely build this into a middleware packaged up into a gem. 

I just wanted to make sure the use case was clear in order to respond to the "would introduce 🤯  retry logic toggles" objection.  

It doesn't feel like we're asking to bikeshed the retry internals to me which was your objection to making this a part of the official API but rather just expose an integer that is already exposed a bunch of other spots (like the web UI).

**Comment by mperham** [comment]
Yep, the integer is already there: retry_count. It's accessible to middleware.

**Comment by rusterholz** [comment]
If there's no harm in exposing retry_count to the middleware then why is there harm in exposing it to the worker?

**Comment by mperham** [comment]
Because the retry internals are orthogonal to the purpose of the job.

https://en.wikipedia.org/wiki/Separation_of_concerns
https://en.wikipedia.org/wiki/Single-responsibility_principle

**Comment by Nowaker** [comment]
> Sidekiq's retry mechanism is a set of best practices but many people have suggested various knobs and options to tweak in order to handle their own edge case. This way lies madness. Design your code to work well with Sidekiq's retry mechanism as it exists today or patch the JobRetry class to add your own logic. 

Why not expose all job metadata to the job? That doesn't meet the definition of "knobs and options". Just expose Sidekiq's internal data, and developers can use it for their own needs. 

Here's how I did it myself: https://chat.openai.com/share/db538adc-6e8e-4f8f-bcad-1eab6bda660c

**Comment by dhempy** [comment]
Here's a use case I'm facing atm. 

I have a job that does some things with an external API for a user. If the API goes down, I want to retry forever. 

However, there is a potential race condition where a user might not be created for a few seconds. (Yes, it would be best to handle that externally prior to enqueueing the job, but I have no control over that). In this case, I count on retries to find the user and export them in a few seconds

However however, sometimes a user can be legit deleted between those retries, and will never come back. I'd rather not have that job hanging around for 21 days. 

So what I'd like to do is something like: 

```
  def perform(user_id)
    user = User.find(user_id)
    UserExportService.new(user).export
  rescue ActiveRecord::RecordNotFound
    raise if job.retries < 3  # or perhaps job.enqueued_time < 2.minutes
  end  
```

I'm looking deeper into middleware now for the first time.

Regarding separation of concerns, it seems I can have the job code know a little about the retry count (as above), or I can have the middleware know a little about the application code (e.g. know what an ActiveRecord::RecordNotFound exception means). Either way, the line must be blurred. I'm a lazy programmer, so I'd rather blur it the easy way, with the code closer to where I'll be looking for it a year from now.
