### ISSUE TITLE
Remove timeout support

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#862]
timeout is not multithread-safe.  See #852 for one example.  More info: http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html

**Comment by mperham** [comment]
To be clear on this issue:

**PLEASE DON'T USE `Timeout.timeout`, EVER, IN ANY RUBY CODE**  It's nearly impossible to make it work correctly in all cases and can lead to extremely subtle bugs.  You should use proper socket timeouts if you want to ensure network connections time out correctly.  Use Net::HTTP's `open_timeout` and `read_timeout` options, for instance.

**Comment by geku** [comment]
Please be aware that `Net::HTTP` itself uses `Timeout.timeout` to enforce the `open_timeout`. Only the `read_timeout` is passed to the socket.

See https://github.com/ruby/ruby/blob/v2_2_3/lib/net/http.rb#L878

**Comment by szimek** [comment]
@geku @mperham What is a recommended HTTP client to use in Sidekiq jobs then, if `Net::HTTP` and `Excon` use `Timeout.timeout` for their open/connect timeouts?

**Comment by mperham** [comment]
Timeout is only unsafe when wrapping a complex block of work. A block with a single network operation is safe.

**Comment by szimek** [comment]
@mperham Thanks. Last weekend we had an issue where all workers were blocked for the whole day by the same job that makes a request to Facebook using `Net::HTTP` (via Koala and Faraday), even though we have open and read timeouts set. I thought that maybe it's somehow related to the fact that `Net::HTTP` is using `Timeout.timeout` for open timeout.

**Comment by ryansch** [comment]
Excon can be configured to only use socket timeouts.

**Comment by mahemoff** [comment]
Setting only socket timeouts still leaves open the problem of a mid-stream hang though. I've not yet found a completely safe solution for timing out http fetches.

**Comment by geku** [comment]
@mperham thanks for clarification

**Comment by AdamFinley** [comment]
@szimek any luck finding a solution?  timeouts are making my workers grind to a halt.

**Comment by szimek** [comment]
@AdamFinley not really :/ as @ryansch suggested we switched from `Net:HTTP` to `Excon` (in Koala lib)  and fortunately we haven't had any similar issues with workers since.
