### ISSUE TITLE
Signal to reload source without restarting

### ISSUE THREAD

**Issue by MSeifert** [mperham/sidekiq#880]
We are currently still on Resque, but would like to switch because of memory issues. Our main issue is that we have several jobs which are long running (> 24 hours!) and a lot of others which are short running (a few seconds).

When we deploy our app (which happens several times a day) we want to make sure the short-running jobs are immediately running with the new source code, but the long running jobs should be allowed to continue for hours until they are finished, and then restart automatically with the new code. If we terminated them on deploy they would almost never finish at all, since they are taking so long.

On Resque we are handling this by having a custom daemon running in the background which checks every minute which workers are running, and starts those which have shut down. On deploy we simply send a signal to all workers to shut down once they are finished with their job. The background daemon will then restart them when the time comes.

To implement this in Sidekiq, we probably need some way to tell the Sidekiq process to reload its source code and use the new source code for new threads, but still continue with the old source for the old threads.

Any hope of finding a solution here?

**Comment by carnifun** [comment]
@mperham 
> never reloads code. It is impossible to do safely when multithreaded.
is this still relevant ?, taking in count I am using sidekiq 5.0 
I was looking for a possiblity to restart job-Code without having to restart sidekiq 

Thank for any advice

**Comment by mperham** [comment]
It is not relevant anymore.  Rails 5.0 allows code reloading in development mode now.

**Comment by carnifun** [comment]
thanks a lot for your answer.
Is there any way to force reload a specific Job-Class in Production ?

**Comment by mperham** [comment]
no
