### ISSUE TITLE
Custom Job ID

### ISSUE THREAD

**Issue by endymonium** [mperham/sidekiq#896]
Hi,

I needed to set the job id manually to able to bind a worker uniquely to a models instance. 

The change I did (see https://github.com/endymonium/sidekiq/commit/5feb15a097fae2f3afec4db2ba54c70bc3f3e9c8) is not 100% clean, but perhaps something similar could be implemented? Or is there a better way to archive this?

**Example**

```
class TestWorker
  include Sidekiq::Worker

  def perform(args)
    (0..5).each do |i|
      puts 'Run ' + i.to_s
      sleep 10
    end
  end
end
```

then

```
TestWorker.perform_async(jid: 'some_id')
```

**Comment by omarcrz0** [comment]
@endymonium I think i follow what you’re looking to do. Basically just adding some sort either 
1. Prefix parameter 
2. Specific id.
Probably passing specific id might not be “great” idea considering there could be race conditions on the table id (on user creation for example)

The issue that were looking to “fix” is basically being able to find jobs easily, without having to store a random hex in the database. 

If i start a job, and I want to know its status, I must somehow keep that randomhex somewhere, within the scope of the process. 
With a customized jid, it’ll be easier to know how to search for the status for other processes outside of the original scope.
