### ISSUE TITLE
(mongoid) failed with error 10068: "invalid operator: $oid"

### ISSUE THREAD

**Issue by sagivo** [mperham/sidekiq#951]
when using sidekiq with mongoid using SomeObject.find('someid') i get the error above. works fine on version ~> 0.12.0, breaks on version >= 0.14.0.
possible reason - the new version contains new `celluloid` version.

stack trace:
`WARN: The operation: #<Moped::Protocol::Query
  @length=80
  @request_id=4
  @response_to=0
  @op_code=2004
  @flags=[:slave_ok]
  @full_collection_name="test.notifications"
  @skip=0
  @limit=0
  @selector={"_id"=>{"$oid"=>"519d21c6a1f4e7de3d000001"}}
  @fields=nil>
failed with error 10068: "invalid operator: $oid"
See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
2013-05-22T19:51:34Z 8314 TID-ow9d7soxk WARN: /Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:382:in`block in query'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:587:in `[]'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:587:in`block (3 levels) in flush'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:586:in `map'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:586:in`block (2 levels) in flush'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:150:in `ensure_connected'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:582:in`block in flush'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:597:in `logging'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:581:in`flush'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:570:in `process'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/node.rb:370:in`query'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/cursor.rb:138:in `block in load_docs'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/session/context.rb:105:in`block in with_node'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/cluster.rb:251:in `with_secondary'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/session/context.rb:104:in`with_node'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/cursor.rb:137:in `load_docs'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/cursor.rb:25:in`each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/query.rb:76:in `each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/moped-1.5.0/lib/moped/query.rb:76:in`each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:122:in `block in each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:619:in`selecting'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/contextual/mongo.rb:121:in `each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/contextual.rb:19:in`each'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:125:in `entries'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:125:in`from_database'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:93:in `multiple_from_map_or_db'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:19:in`execute_or_raise'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/criterion/findable.rb:40:in `find'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/mongoid-3.1.4/lib/mongoid/finders.rb:85:in`find'
/Users/sagiv/dev/hdi/app/workers/notification_worker.rb:6:in `perform'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:49:in`block (2 levels) in process'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:109:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:109:in`block in invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/instrumentation/sidekiq.rb:25:in `block in call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in`perform_action_with_newrelic_trace'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/instrumentation/sidekiq.rb:24:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in`block in invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in`block in invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/retry_jobs.rb:50:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in`block in invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/logging.rb:22:in`with_context'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in`block in invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:114:in `call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:114:in`invoke'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:48:in `block in process'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:87:in`stats'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:47:in `process'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/calls.rb:25:in`public_send'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/calls.rb:25:in `dispatch'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/calls.rb:125:in`dispatch'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/actor.rb:328:in `block in handle_message'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/tasks.rb:42:in`block in initialize'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/tasks/task_thread.rb:20:in `block in create'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/internal_pool.rb:59:in`call'
/Users/sagiv/.rvm/gems/ruby-1.9.3-p327/gems/celluloid-0.14.0/lib/celluloid/internal_pool.rb:59:in `block in create`

**Comment by coderawal** [comment]
I'm still got this issue in mongoid version 5.1.0. To be clear. i have a rails app that doesn't gave this issue, and another mountable engine app. within main app, I have mongoid added in engine app as dependency, but I'm getting this  issue in engine app. now I would like to know that, does the issue still exists in version 5.1.0, or i'm doing the things wrong way.

**Comment by jonhyman** [comment]
This is a mongo ruby driver issue about json encoding of a bson id. Has nothing to do with sidekiq.
